TModLoader: Terraria.Graphics.FinalFractalHelper.Draw
Draw()
void Terraria.Graphics.FinalFractalHelper.Draw (Projectile proj) inline
Definition at line 190 of file FinalFractalHelper.cs.
    {
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        FinalFractalProfile finalFractalProfile = GetFinalFractalProfile((int)proj.ai[1]);
        MiscShaderData miscShaderData = GameShaders.Misc["FinalFractal"];
        int num = 4;
        int num2 = 0;
        int num3 = 0;
        int num4 = 4;
        miscShaderData.UseShaderSpecificData(new Vector4((float)num, (float)num2, (float)num3, (float)num4));
        miscShaderData.UseImage0("Images/Extra_" + (short)201);
        miscShaderData.UseImage1("Images/Extra_" + (short)193);
        miscShaderData.Apply();
        _vertexStrip.PrepareStrip(proj.oldPos, proj.oldRot, finalFractalProfile.colorMethod, finalFractalProfile.widthMethod, -Main.screenPosition + proj.Size / 2f, proj.oldPos.Length, includeBacksides: true);
        _vertexStrip.DrawTrail();
        Main.pixelShader.CurrentTechnique.Passes[0].Apply();
    }
References Terraria.Graphics.FinalFractalHelper._vertexStrip, Terraria.Graphics.VertexStrip.DrawTrail(), Terraria.Graphics.FinalFractalHelper.GetFinalFractalProfile(), Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.Main.pixelShader, Terraria.Graphics.VertexStrip.PrepareStrip(), and Terraria.Main.screenPosition.