TModLoader: Terraria.ModLoader.Utilities.SpawnCondition.SpawnCondition
SpawnCondition() [3/3]
static Terraria.ModLoader.Utilities.SpawnCondition.SpawnCondition () inline static private
    {
        NebulaTower = new SpawnCondition((NPCSpawnInfo info) => info.Player.ZoneTowerNebula);
        VortexTower = new SpawnCondition((NPCSpawnInfo info) => info.Player.ZoneTowerVortex);
        StardustTower = new SpawnCondition((NPCSpawnInfo info) => info.Player.ZoneTowerStardust);
        SolarTower = new SpawnCondition((NPCSpawnInfo info) => info.Player.ZoneTowerSolar);
        Sky = new SpawnCondition((NPCSpawnInfo info) => info.Sky);
        Invasion = new SpawnCondition((NPCSpawnInfo info) => info.Invasion);
        GoblinArmy = new SpawnCondition(Invasion, (NPCSpawnInfo info) => Main.invasionType == 1);
        FrostLegion = new SpawnCondition(Invasion, (NPCSpawnInfo info) => Main.invasionType == 2);
        Pirates = new SpawnCondition(Invasion, (NPCSpawnInfo info) => Main.invasionType == 3);
        MartianMadness = new SpawnCondition(Invasion, (NPCSpawnInfo info) => Main.invasionType == 4);
        Bartender = new SpawnCondition((NPCSpawnInfo info) => !NPC.savedBartender && DD2Event.ReadyToFindBartender && !NPC.AnyNPCs(579) && !info.Water, 0.0125f);
        SpiderCave = new SpawnCondition((NPCSpawnInfo info) => GetTile(info).wall == 62 || info.SpiderCave);
        DesertCave = new SpawnCondition((NPCSpawnInfo info) => (WallID.Sets.Conversion.HardenedSand[GetTile(info).wall] || WallID.Sets.Conversion.Sandstone[GetTile(info).wall] || info.DesertCave) && WorldGen.checkUnderground(info.SpawnTileX, info.SpawnTileY));
        HardmodeJungleWater = new SpawnCondition((NPCSpawnInfo info) => Main.hardMode && info.Water && info.Player.ZoneJungle, 2f / 3f);
        HardmodeCrimsonWater = new SpawnCondition((NPCSpawnInfo info) => Main.hardMode && info.Water && info.Player.ZoneCrimson, 8f / 9f);
        Ocean = new SpawnCondition((NPCSpawnInfo info) => info.Water && (info.SpawnTileX < 250 || info.SpawnTileX > Main.maxTilesX - 250) && Main.tileSand[info.SpawnTileType] && (double)info.SpawnTileY < Main.rockLayer);
        OceanAngler = new SpawnCondition(Ocean, (NPCSpawnInfo info) => !NPC.savedAngler && !NPC.AnyNPCs(376) && WaterSurface(info));
        OceanMonster = new SpawnCondition(Ocean, (NPCSpawnInfo info) => true);
        BeachAngler = new SpawnCondition((NPCSpawnInfo info) => !info.Water && !NPC.savedAngler && !NPC.AnyNPCs(376) && (info.SpawnTileX < 340 || info.SpawnTileX > Main.maxTilesX - 340) && Main.tileSand[info.SpawnTileType] && (double)info.SpawnTileY < Main.worldSurface);
        JungleWater = new SpawnCondition((NPCSpawnInfo info) => info.Water && info.SpawnTileType == 60);
        CavePiranha = new SpawnCondition((NPCSpawnInfo info) => info.Water && (double)info.SpawnTileY > Main.rockLayer, 0.5f);
        CaveJellyfish = new SpawnCondition((NPCSpawnInfo info) => info.Water && (double)info.SpawnTileY > Main.worldSurface, 1f / 3f);
        WaterCritter = new SpawnCondition((NPCSpawnInfo info) => info.Water, 0.25f);
        CorruptWaterCritter = new SpawnCondition(WaterCritter, (NPCSpawnInfo info) => info.Player.ZoneCorrupt);
        OverworldWaterCritter = new SpawnCondition(WaterCritter, (NPCSpawnInfo info) => (double)info.SpawnTileY < Main.worldSurface && info.SpawnTileY > 50 && Main.dayTime, 2f / 3f);
        OverworldWaterSurfaceCritter = new SpawnCondition(OverworldWaterCritter, WaterSurface);
        OverworldUnderwaterCritter = new SpawnCondition(OverworldWaterCritter, (NPCSpawnInfo info) => true);
        DefaultWaterCritter = new SpawnCondition(WaterCritter, (NPCSpawnInfo info) => true);
        BoundCaveNPC = new SpawnCondition((NPCSpawnInfo info) => !info.Water && (double)info.SpawnTileY >= Main.rockLayer && info.SpawnTileY < Main.maxTilesY - 210, 0.05f);
        TownCritter = new SpawnCondition((NPCSpawnInfo info) => info.PlayerInTown);
        TownWaterCritter = new SpawnCondition(TownCritter, (NPCSpawnInfo info) => info.Water);
        TownOverworldWaterCritter = new SpawnCondition(TownWaterCritter, (NPCSpawnInfo info) => (double)info.SpawnTileY < Main.worldSurface && info.SpawnTileY > 50 && Main.dayTime, 2f / 3f);
        TownOverworldWaterSurfaceCritter = new SpawnCondition(TownOverworldWaterCritter, WaterSurface);
        TownOverworldUnderwaterCritter = new SpawnCondition(TownOverworldWaterCritter, (NPCSpawnInfo info) => true);
        TownDefaultWaterCritter = new SpawnCondition(TownWaterCritter, (NPCSpawnInfo info) => true);
        TownSnowCritter = new SpawnCondition(TownCritter, (NPCSpawnInfo info) => info.SpawnTileType == 147 || info.SpawnTileType == 161);
        TownJungleCritter = new SpawnCondition(TownCritter, (NPCSpawnInfo info) => info.SpawnTileType == 60);
        TownGeneralCritter = new SpawnCondition(TownCritter, (NPCSpawnInfo info) => info.SpawnTileType == 2 || info.SpawnTileType == 109 || (double)info.SpawnTileY > Main.worldSurface);
        Dungeon = new SpawnCondition((NPCSpawnInfo info) => info.Player.ZoneDungeon);
        DungeonGuardian = new SpawnCondition(Dungeon, (NPCSpawnInfo info) => !NPC.downedBoss3);
        DungeonNormal = new SpawnCondition(Dungeon, (NPCSpawnInfo info) => true);
        Meteor = new SpawnCondition((NPCSpawnInfo info) => info.Player.ZoneMeteor);
        OldOnesArmy = new SpawnCondition((NPCSpawnInfo info) => DD2Event.Ongoing && info.Player.ZoneOldOneArmy);
        FrostMoon = new SpawnCondition((NPCSpawnInfo info) => (double)info.SpawnTileY <= Main.worldSurface && !Main.dayTime && Main.snowMoon);
        PumpkinMoon = new SpawnCondition((NPCSpawnInfo info) => (double)info.SpawnTileY <= Main.worldSurface && !Main.dayTime && Main.pumpkinMoon);
        SolarEclipse = new SpawnCondition((NPCSpawnInfo info) => (double)info.SpawnTileY <= Main.worldSurface && Main.dayTime && Main.eclipse);
        HardmodeMushroomWater = new SpawnCondition((NPCSpawnInfo info) => Main.hardMode && info.SpawnTileType == 70 && info.Water);
        OverworldMushroom = new SpawnCondition((NPCSpawnInfo info) => info.SpawnTileType == 70 && (double)info.SpawnTileY <= Main.worldSurface, 2f / 3f);
        UndergroundMushroom = new SpawnCondition((NPCSpawnInfo info) => info.SpawnTileType == 70 && Main.hardMode && (double)info.SpawnTileY >= Main.worldSurface, 2f / 3f);
        CorruptWorm = new SpawnCondition((NPCSpawnInfo info) => info.Player.ZoneCorrupt && !info.PlayerSafe, 1f / 65f);
        UndergroundMimic = new SpawnCondition((NPCSpawnInfo info) => Main.hardMode && (double)info.SpawnTileY > Main.worldSurface, 1f / 70f);
        OverworldMimic = new SpawnCondition((NPCSpawnInfo info) => Main.hardMode && GetTile(info).wall == 2, 0.05f);
        Wraith = new SpawnCondition((NPCSpawnInfo info) => Main.hardMode && (double)info.SpawnTileY <= Main.worldSurface && !Main.dayTime, 0.05f);
        Wraith.WeightFunc = delegate
        {
            float num3 = 0.95f;
            if (Main.moonPhase == 4)
            {
                num3 *= 0.8f;
            }
            return 1f - num3;
        };
        HoppinJack = new SpawnCondition((NPCSpawnInfo info) => Main.hardMode && Main.halloween && (double)info.SpawnTileY <= Main.worldSurface && !Main.dayTime, 0.1f);
        DoctorBones = new SpawnCondition((NPCSpawnInfo info) => info.SpawnTileType == 60 && !Main.dayTime, 0.002f);
        LacBeetle = new SpawnCondition((NPCSpawnInfo info) => info.SpawnTileType == 60 && (double)info.SpawnTileY > Main.worldSurface, 1f / 60f);
        WormCritter = new SpawnCondition((NPCSpawnInfo info) => (double)info.SpawnTileY > Main.worldSurface && info.SpawnTileY < Main.maxTilesY - 210 && !info.Player.ZoneSnow && !info.Player.ZoneCrimson && !info.Player.ZoneCorrupt && !info.Player.ZoneJungle && !info.Player.ZoneHallow, 0.125f);
        MouseCritter = new SpawnCondition((NPCSpawnInfo info) => (double)info.SpawnTileY > Main.worldSurface && info.SpawnTileY < Main.maxTilesY - 210 && !info.Player.ZoneSnow && !info.Player.ZoneCrimson && !info.Player.ZoneCorrupt && !info.Player.ZoneJungle && !info.Player.ZoneHallow, 1f / 13f);
        SnailCritter = new SpawnCondition((NPCSpawnInfo info) => (double)info.SpawnTileY > Main.worldSurface && (double)info.SpawnTileY < (Main.rockLayer + (double)Main.maxTilesY) / 2.0 && !info.Player.ZoneSnow && !info.Player.ZoneCrimson && !info.Player.ZoneCorrupt && !info.Player.ZoneHallow, 1f / 13f);
        FrogCritter = new SpawnCondition((NPCSpawnInfo info) => (double)info.SpawnTileY < Main.worldSurface && info.Player.ZoneJungle, 1f / 9f);
        HardmodeJungle = new SpawnCondition((NPCSpawnInfo info) => info.SpawnTileType == 60 && Main.hardMode, 2f / 3f);
        JungleTemple = new SpawnCondition((NPCSpawnInfo info) => info.SpawnTileType == 226 && info.Lihzahrd);
        UndergroundJungle = new SpawnCondition((NPCSpawnInfo info) => info.SpawnTileType == 60 && (double)info.SpawnTileY > (Main.worldSurface + Main.rockLayer) / 2.0);
        SurfaceJungle = new SpawnCondition((NPCSpawnInfo info) => info.SpawnTileType == 60, 11f / 32f);
        SandstormEvent = new SpawnCondition((NPCSpawnInfo info) => Sandstorm.Happening && info.Player.ZoneSandstorm && TileID.Sets.Conversion.Sand[info.SpawnTileType] && NPC.Spawning_SandstoneCheck(info.SpawnTileX, info.SpawnTileY));
        Mummy = new SpawnCondition((NPCSpawnInfo info) => Main.hardMode && info.SpawnTileType == 53, 1f / 3f);
        DarkMummy = new SpawnCondition((NPCSpawnInfo info) => Main.hardMode && (info.SpawnTileType == 112 || info.SpawnTileType == 234), 0.5f);
        LightMummy = new SpawnCondition((NPCSpawnInfo info) => Main.hardMode && info.SpawnTileType == 116, 0.5f);
        OverworldHallow = new SpawnCondition((NPCSpawnInfo info) => Main.hardMode && !info.Water && (double)info.SpawnTileY < Main.rockLayer && (info.SpawnTileType == 116 || info.SpawnTileType == 117 || info.SpawnTileType == 109 || info.SpawnTileType == 164));
        EnchantedSword = new SpawnCondition((NPCSpawnInfo info) => !info.PlayerSafe && Main.hardMode && !info.Water && (double)info.SpawnTileY >= Main.rockLayer && (info.SpawnTileType == 116 || info.SpawnTileType == 117 || info.SpawnTileType == 109 || info.SpawnTileType == 164), 0.02f);
        Crimson = new SpawnCondition((NPCSpawnInfo info) => (info.SpawnTileType == 204 && info.Player.ZoneCrimson) || info.SpawnTileType == 199 || info.SpawnTileType == 200 || info.SpawnTileType == 203 || info.SpawnTileType == 234);
        Corruption = new SpawnCondition((NPCSpawnInfo info) => (info.SpawnTileType == 22 && info.Player.ZoneCorrupt) || info.SpawnTileType == 23 || info.SpawnTileType == 25 || info.SpawnTileType == 112 || info.SpawnTileType == 163);
        Overworld = new SpawnCondition((NPCSpawnInfo info) => (double)info.SpawnTileY <= Main.worldSurface);
        IceGolem = new SpawnCondition(Overworld, (NPCSpawnInfo info) => info.Player.ZoneSnow && Main.hardMode && Main.cloudAlpha > 0f && !NPC.AnyNPCs(243), 0.05f);
        RainbowSlime = new SpawnCondition(Overworld, (NPCSpawnInfo info) => info.Player.ZoneHallow && Main.hardMode && Main.cloudAlpha > 0f && !NPC.AnyNPCs(244), 0.05f);
        AngryNimbus = new SpawnCondition(Overworld, (NPCSpawnInfo info) => !info.Player.ZoneSnow && Main.hardMode && Main.cloudAlpha > 0f && NPC.CountNPCS(250) < 2, 0.1f);
        MartianProbe = new SpawnCondition(Overworld, (NPCSpawnInfo info) => MartianProbeHelper(info) && Main.hardMode && NPC.downedGolemBoss && !NPC.AnyNPCs(399), 0.0025f);
        MartianProbe.WeightFunc = delegate
        {
            float num2 = 0.9975f;
            if (!NPC.downedMartians)
            {
                num2 *= 0.99f;
            }
            return 1f - num2;
        };
        OverworldDay = new SpawnCondition(Overworld, (NPCSpawnInfo info) => Main.dayTime);
        OverworldDaySnowCritter = new SpawnCondition(OverworldDay, (NPCSpawnInfo info) => InnerThird(info) && (GetTile(info).type == 147 || GetTile(info).type == 161), 1f / 15f);
        OverworldDayGrassCritter = new SpawnCondition(OverworldDay, (NPCSpawnInfo info) => InnerThird(info) && (GetTile(info).type == 2 || GetTile(info).type == 109), 1f / 15f);
        OverworldDaySandCritter = new SpawnCondition(OverworldDay, (NPCSpawnInfo info) => InnerThird(info) && GetTile(info).type == 53, 1f / 15f);
        OverworldMorningBirdCritter = new SpawnCondition(OverworldDay, (NPCSpawnInfo info) => InnerThird(info) && Main.time < 18000.0 && (GetTile(info).type == 2 || GetTile(info).type == 109), 0.25f);
        OverworldDayBirdCritter = new SpawnCondition(OverworldDay, (NPCSpawnInfo info) => InnerThird(info) && (GetTile(info).type == 2 || GetTile(info).type == 109 || GetTile(info).type == 147), 1f / 15f);
        KingSlime = new SpawnCondition(OverworldDay, (NPCSpawnInfo info) => OuterThird(info) && GetTile(info).type == 2 && !NPC.AnyNPCs(50), 0.0033333334f);
        OverworldDayDesert = new SpawnCondition(OverworldDay, (NPCSpawnInfo info) => GetTile(info).type == 53 && !info.Water, 0.2f);
        GoblinScout = new SpawnCondition(OverworldDay, (NPCSpawnInfo info) => OuterThird(info), 1f / 15f);
        GoblinScout.WeightFunc = delegate
        {
            float num = 14f / 15f;
            return (!NPC.downedGoblins && WorldGen.shadowOrbSmashed) ? (num *= 0.85714287f) : (1f - num);
        };
        OverworldDayRain = new SpawnCondition(OverworldDay, (NPCSpawnInfo info) => Main.raining, 2f / 3f);
        OverworldDaySlime = new SpawnCondition(OverworldDay, (NPCSpawnInfo info) => true);
        OverworldNight = new SpawnCondition(Overworld, (NPCSpawnInfo info) => true);
        OverworldFirefly = new SpawnCondition(OverworldNight, (NPCSpawnInfo info) => GetTile(info).type == 2 || GetTile(info).type == 109, 0.1f);
        OverworldFirefly.WeightFunc = () => 1f / (float)NPC.fireFlyChance;
        OverworldNightMonster = new SpawnCondition(OverworldNight, (NPCSpawnInfo info) => true);
        Underground = new SpawnCondition((NPCSpawnInfo info) => (double)info.SpawnTileY <= Main.rockLayer);
        Underworld = new SpawnCondition((NPCSpawnInfo info) => info.SpawnTileY > Main.maxTilesY - 190);
        Cavern = new SpawnCondition((NPCSpawnInfo info) => true);
    }
References Terraria.ModLoader.Utilities.SpawnCondition.SpawnCondition(), Terraria.ModLoader.Utilities.SpawnCondition.AngryNimbus, Terraria.NPC.AnyNPCs(), Terraria.ModLoader.Utilities.SpawnCondition.Bartender, Terraria.ModLoader.Utilities.SpawnCondition.BeachAngler, Terraria.ModLoader.Utilities.SpawnCondition.BoundCaveNPC, Terraria.ModLoader.Utilities.SpawnCondition.CaveJellyfish, Terraria.ModLoader.Utilities.SpawnCondition.CavePiranha, Terraria.ModLoader.Utilities.SpawnCondition.Cavern, Terraria.WorldGen.checkUnderground(), Terraria.Main.cloudAlpha, Terraria.ModLoader.Utilities.SpawnCondition.Corruption, Terraria.ModLoader.Utilities.SpawnCondition.CorruptWaterCritter, Terraria.ModLoader.Utilities.SpawnCondition.CorruptWorm, Terraria.NPC.CountNPCS(), Terraria.ModLoader.Utilities.SpawnCondition.Crimson, Terraria.ModLoader.Utilities.SpawnCondition.DarkMummy, Terraria.Main.dayTime, Terraria.ModLoader.Utilities.SpawnCondition.DefaultWaterCritter, Terraria.ModLoader.Utilities.SpawnCondition.DesertCave, Terraria.ModLoader.Utilities.SpawnCondition.DoctorBones, Terraria.NPC.downedBoss3, Terraria.NPC.downedGoblins, Terraria.NPC.downedGolemBoss, Terraria.NPC.downedMartians, Terraria.ModLoader.Utilities.SpawnCondition.Dungeon, Terraria.ModLoader.Utilities.SpawnCondition.DungeonGuardian, Terraria.ModLoader.Utilities.SpawnCondition.DungeonNormal, Terraria.Main.eclipse, Terraria.ModLoader.Utilities.SpawnCondition.EnchantedSword, Terraria.NPC.fireFlyChance, Terraria.ModLoader.Utilities.SpawnCondition.FrogCritter, Terraria.ModLoader.Utilities.SpawnCondition.FrostLegion, Terraria.ModLoader.Utilities.SpawnCondition.FrostMoon, Terraria.ModLoader.Utilities.SpawnCondition.GetTile(), Terraria.ModLoader.Utilities.SpawnCondition.GoblinArmy, Terraria.ModLoader.Utilities.SpawnCondition.GoblinScout, Terraria.Main.halloween, Terraria.GameContent.Events.Sandstorm.Happening, Terraria.ID.WallID.Sets.Conversion.HardenedSand, Terraria.Main.hardMode, Terraria.ModLoader.Utilities.SpawnCondition.HardmodeCrimsonWater, Terraria.ModLoader.Utilities.SpawnCondition.HardmodeJungle, Terraria.ModLoader.Utilities.SpawnCondition.HardmodeJungleWater, Terraria.ModLoader.Utilities.SpawnCondition.HardmodeMushroomWater, Terraria.ModLoader.Utilities.SpawnCondition.HoppinJack, Terraria.ModLoader.Utilities.SpawnCondition.IceGolem, Terraria.ModLoader.Utilities.SpawnCondition.InnerThird(), Terraria.ModLoader.Utilities.SpawnCondition.Invasion, Terraria.Main.invasionType, Terraria.ModLoader.Utilities.SpawnCondition.JungleTemple, Terraria.ModLoader.Utilities.SpawnCondition.JungleWater, Terraria.ModLoader.Utilities.SpawnCondition.KingSlime, Terraria.ModLoader.Utilities.SpawnCondition.LacBeetle, Terraria.ModLoader.Utilities.SpawnCondition.LightMummy, Terraria.ModLoader.Utilities.SpawnCondition.MartianMadness, Terraria.ModLoader.Utilities.SpawnCondition.MartianProbe, Terraria.ModLoader.Utilities.SpawnCondition.MartianProbeHelper(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.ModLoader.Utilities.SpawnCondition.Meteor, Terraria.Main.moonPhase, Terraria.ModLoader.Utilities.SpawnCondition.MouseCritter, Terraria.ModLoader.Utilities.SpawnCondition.Mummy, Terraria.ModLoader.Utilities.SpawnCondition.NebulaTower, Terraria.ModLoader.Utilities.SpawnCondition.Ocean, Terraria.ModLoader.Utilities.SpawnCondition.OceanAngler, Terraria.ModLoader.Utilities.SpawnCondition.OceanMonster, Terraria.ModLoader.Utilities.SpawnCondition.OldOnesArmy, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.ModLoader.Utilities.SpawnCondition.OuterThird(), Terraria.ModLoader.Utilities.SpawnCondition.Overworld, Terraria.ModLoader.Utilities.SpawnCondition.OverworldDay, Terraria.ModLoader.Utilities.SpawnCondition.OverworldDayBirdCritter, Terraria.ModLoader.Utilities.SpawnCondition.OverworldDayDesert, Terraria.ModLoader.Utilities.SpawnCondition.OverworldDayGrassCritter, Terraria.ModLoader.Utilities.SpawnCondition.OverworldDayRain, Terraria.ModLoader.Utilities.SpawnCondition.OverworldDaySandCritter, Terraria.ModLoader.Utilities.SpawnCondition.OverworldDaySlime, Terraria.ModLoader.Utilities.SpawnCondition.OverworldDaySnowCritter, Terraria.ModLoader.Utilities.SpawnCondition.OverworldFirefly, Terraria.ModLoader.Utilities.SpawnCondition.OverworldHallow, Terraria.ModLoader.Utilities.SpawnCondition.OverworldMimic, Terraria.ModLoader.Utilities.SpawnCondition.OverworldMorningBirdCritter, Terraria.ModLoader.Utilities.SpawnCondition.OverworldMushroom, Terraria.ModLoader.Utilities.SpawnCondition.OverworldNight, Terraria.ModLoader.Utilities.SpawnCondition.OverworldNightMonster, Terraria.ModLoader.Utilities.SpawnCondition.OverworldUnderwaterCritter, Terraria.ModLoader.Utilities.SpawnCondition.OverworldWaterCritter, Terraria.ModLoader.Utilities.SpawnCondition.OverworldWaterSurfaceCritter, Terraria.ModLoader.Utilities.SpawnCondition.Pirates, Terraria.ModLoader.Utilities.SpawnCondition.PumpkinMoon, Terraria.Main.pumpkinMoon, Terraria.ModLoader.Utilities.SpawnCondition.RainbowSlime, Terraria.Main.raining, Terraria.GameContent.Events.DD2Event.ReadyToFindBartender, Terraria.Main.rockLayer, Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.ID.WallID.Sets.Conversion.Sandstone, Terraria.ModLoader.Utilities.SpawnCondition.SandstormEvent, Terraria.NPC.savedAngler, Terraria.NPC.savedBartender, Terraria.WorldGen.shadowOrbSmashed, Terraria.ModLoader.Utilities.SpawnCondition.Sky, Terraria.ModLoader.Utilities.SpawnCondition.SnailCritter, Terraria.Main.snowMoon, Terraria.ModLoader.Utilities.SpawnCondition.SolarEclipse, Terraria.ModLoader.Utilities.SpawnCondition.SolarTower, Terraria.NPC.Spawning_SandstoneCheck(), Terraria.ModLoader.Utilities.SpawnCondition.SpiderCave, Terraria.ModLoader.Utilities.SpawnCondition.StardustTower, Terraria.ModLoader.Utilities.SpawnCondition.SurfaceJungle, Terraria.Main.tileSand, Terraria.Main.time, Terraria.ModLoader.Utilities.SpawnCondition.TownCritter, Terraria.ModLoader.Utilities.SpawnCondition.TownDefaultWaterCritter, Terraria.ModLoader.Utilities.SpawnCondition.TownGeneralCritter, Terraria.ModLoader.Utilities.SpawnCondition.TownJungleCritter, Terraria.ModLoader.Utilities.SpawnCondition.TownOverworldUnderwaterCritter, Terraria.ModLoader.Utilities.SpawnCondition.TownOverworldWaterCritter, Terraria.ModLoader.Utilities.SpawnCondition.TownOverworldWaterSurfaceCritter, Terraria.ModLoader.Utilities.SpawnCondition.TownSnowCritter, Terraria.ModLoader.Utilities.SpawnCondition.TownWaterCritter, Terraria.ModLoader.Utilities.SpawnCondition.Underground, Terraria.ModLoader.Utilities.SpawnCondition.UndergroundJungle, Terraria.ModLoader.Utilities.SpawnCondition.UndergroundMimic, Terraria.ModLoader.Utilities.SpawnCondition.UndergroundMushroom, Terraria.ModLoader.Utilities.SpawnCondition.Underworld, Terraria.ModLoader.Utilities.SpawnCondition.VortexTower, Terraria.ModLoader.Utilities.SpawnCondition.WaterCritter, Terraria.ModLoader.Utilities.SpawnCondition.WaterSurface(), Terraria.Main.worldSurface, Terraria.ModLoader.Utilities.SpawnCondition.WormCritter, and Terraria.ModLoader.Utilities.SpawnCondition.Wraith.
Referenced by Terraria.ModLoader.Utilities.SpawnCondition.SpawnCondition().