TModLoader: Terraria.ID.SoundID.SoundID
SoundID()
static Terraria.ID.SoundID.SoundID () inline static private
    {
        ItemSoundCount = 179;
        DD2_GoblinBomb = new SoundStyle("Terraria/Sounds/NPC_Killed_14")
        {
            Volume = 0.5f
        };
        AchievementComplete = CreateTrackable("achievement_complete");
        BlizzardInsideBuildingLoop = CreateTrackable("blizzard_inside_building_loop", SoundType.Ambient);
        BlizzardStrongLoop = CreateTrackable("blizzard_strong_loop", SoundType.Ambient).WithVolume(0.5f);
        LiquidsHoneyWater = CreateTrackable("liquids_honey_water", 3, SoundType.Ambient);
        LiquidsHoneyLava = CreateTrackable("liquids_honey_lava", 3, SoundType.Ambient);
        LiquidsWaterLava = CreateTrackable("liquids_water_lava", 3, SoundType.Ambient);
        DD2_BallistaTowerShot = CreateTrackable("dd2_ballista_tower_shot", 3);
        DD2_ExplosiveTrapExplode = CreateTrackable("dd2_explosive_trap_explode", 3);
        DD2_FlameburstTowerShot = CreateTrackable("dd2_flameburst_tower_shot", 3);
        DD2_LightningAuraZap = CreateTrackable("dd2_lightning_aura_zap", 4);
        DD2_DefenseTowerSpawn = CreateTrackable("dd2_defense_tower_spawn");
        DD2_BetsyDeath = CreateTrackable("dd2_betsy_death", 3);
        DD2_BetsyFireballShot = CreateTrackable("dd2_betsy_fireball_shot", 3);
        DD2_BetsyFireballImpact = CreateTrackable("dd2_betsy_fireball_impact", 3);
        DD2_BetsyFlameBreath = CreateTrackable("dd2_betsy_flame_breath");
        DD2_BetsyFlyingCircleAttack = CreateTrackable("dd2_betsy_flying_circle_attack");
        DD2_BetsyHurt = CreateTrackable("dd2_betsy_hurt", 3);
        DD2_BetsyScream = CreateTrackable("dd2_betsy_scream");
        DD2_BetsySummon = CreateTrackable("dd2_betsy_summon", 3);
        DD2_BetsyWindAttack = CreateTrackable("dd2_betsy_wind_attack", 3);
        DD2_DarkMageAttack = CreateTrackable("dd2_dark_mage_attack", 3);
        DD2_DarkMageCastHeal = CreateTrackable("dd2_dark_mage_cast_heal", 3);
        DD2_DarkMageDeath = CreateTrackable("dd2_dark_mage_death", 3);
        DD2_DarkMageHealImpact = CreateTrackable("dd2_dark_mage_heal_impact", 3);
        DD2_DarkMageHurt = CreateTrackable("dd2_dark_mage_hurt", 3);
        DD2_DarkMageSummonSkeleton = CreateTrackable("dd2_dark_mage_summon_skeleton", 3);
        DD2_DrakinBreathIn = CreateTrackable("dd2_drakin_breath_in", 3);
        DD2_DrakinDeath = CreateTrackable("dd2_drakin_death", 3);
        DD2_DrakinHurt = CreateTrackable("dd2_drakin_hurt", 3);
        DD2_DrakinShot = CreateTrackable("dd2_drakin_shot", 3);
        DD2_GoblinDeath = CreateTrackable("dd2_goblin_death", 3);
        DD2_GoblinHurt = CreateTrackable("dd2_goblin_hurt", 6);
        DD2_GoblinScream = CreateTrackable("dd2_goblin_scream", 3);
        DD2_GoblinBomberDeath = CreateTrackable("dd2_goblin_bomber_death", 3);
        DD2_GoblinBomberHurt = CreateTrackable("dd2_goblin_bomber_hurt", 3);
        DD2_GoblinBomberScream = CreateTrackable("dd2_goblin_bomber_scream", 3);
        DD2_GoblinBomberThrow = CreateTrackable("dd2_goblin_bomber_throw", 3);
        DD2_JavelinThrowersAttack = CreateTrackable("dd2_javelin_throwers_attack", 3);
        DD2_JavelinThrowersDeath = CreateTrackable("dd2_javelin_throwers_death", 3);
        DD2_JavelinThrowersHurt = CreateTrackable("dd2_javelin_throwers_hurt", 3);
        DD2_JavelinThrowersTaunt = CreateTrackable("dd2_javelin_throwers_taunt", 3);
        DD2_KoboldDeath = CreateTrackable("dd2_kobold_death", 3);
        DD2_KoboldExplosion = CreateTrackable("dd2_kobold_explosion", 3);
        DD2_KoboldHurt = CreateTrackable("dd2_kobold_hurt", 3);
        DD2_KoboldIgnite = CreateTrackable("dd2_kobold_ignite");
        DD2_KoboldIgniteLoop = CreateTrackable("dd2_kobold_ignite_loop");
        DD2_KoboldScreamChargeLoop = CreateTrackable("dd2_kobold_scream_charge_loop");
        DD2_KoboldFlyerChargeScream = CreateTrackable("dd2_kobold_flyer_charge_scream", 3);
        DD2_KoboldFlyerDeath = CreateTrackable("dd2_kobold_flyer_death", 3);
        DD2_KoboldFlyerHurt = CreateTrackable("dd2_kobold_flyer_hurt", 3);
        DD2_LightningBugDeath = CreateTrackable("dd2_lightning_bug_death", 3);
        DD2_LightningBugHurt = CreateTrackable("dd2_lightning_bug_hurt", 3);
        DD2_LightningBugZap = CreateTrackable("dd2_lightning_bug_zap", 3);
        DD2_OgreAttack = CreateTrackable("dd2_ogre_attack", 3);
        DD2_OgreDeath = CreateTrackable("dd2_ogre_death", 3);
        DD2_OgreGroundPound = CreateTrackable("dd2_ogre_ground_pound");
        DD2_OgreHurt = CreateTrackable("dd2_ogre_hurt", 3);
        DD2_OgreRoar = CreateTrackable("dd2_ogre_roar", 3);
        DD2_OgreSpit = CreateTrackable("dd2_ogre_spit");
        DD2_SkeletonDeath = CreateTrackable("dd2_skeleton_death", 3);
        DD2_SkeletonHurt = CreateTrackable("dd2_skeleton_hurt", 3);
        DD2_SkeletonSummoned = CreateTrackable("dd2_skeleton_summoned");
        DD2_WitherBeastAuraPulse = CreateTrackable("dd2_wither_beast_aura_pulse", 2);
        DD2_WitherBeastCrystalImpact = CreateTrackable("dd2_wither_beast_crystal_impact", 3);
        DD2_WitherBeastDeath = CreateTrackable("dd2_wither_beast_death", 3);
        DD2_WitherBeastHurt = CreateTrackable("dd2_wither_beast_hurt", 3);
        DD2_WyvernDeath = CreateTrackable("dd2_wyvern_death", 3);
        DD2_WyvernHurt = CreateTrackable("dd2_wyvern_hurt", 3);
        DD2_WyvernScream = CreateTrackable("dd2_wyvern_scream", 3);
        DD2_WyvernDiveDown = CreateTrackable("dd2_wyvern_dive_down", 3);
        DD2_EtherianPortalDryadTouch = CreateTrackable("dd2_etherian_portal_dryad_touch");
        DD2_EtherianPortalIdleLoop = CreateTrackable("dd2_etherian_portal_idle_loop");
        DD2_EtherianPortalOpen = CreateTrackable("dd2_etherian_portal_open");
        DD2_EtherianPortalSpawnEnemy = CreateTrackable("dd2_etherian_portal_spawn_enemy", 3);
        DD2_CrystalCartImpact = CreateTrackable("dd2_crystal_cart_impact", 3);
        DD2_DefeatScene = CreateTrackable("dd2_defeat_scene");
        DD2_WinScene = CreateTrackable("dd2_win_scene");
        DD2_BetsysWrathShot = DD2_BetsyFireballShot.WithVolume(0.4f);
        DD2_BetsysWrathImpact = DD2_BetsyFireballImpact.WithVolume(0.4f);
        DD2_BookStaffCast = CreateTrackable("dd2_book_staff_cast", 3);
        DD2_BookStaffTwisterLoop = CreateTrackable("dd2_book_staff_twister_loop");
        DD2_GhastlyGlaiveImpactGhost = CreateTrackable("dd2_ghastly_glaive_impact_ghost", 3);
        DD2_GhastlyGlaivePierce = CreateTrackable("dd2_ghastly_glaive_pierce", 3);
        DD2_MonkStaffGroundImpact = CreateTrackable("dd2_monk_staff_ground_impact", 3);
        DD2_MonkStaffGroundMiss = CreateTrackable("dd2_monk_staff_ground_miss", 3);
        DD2_MonkStaffSwing = CreateTrackable("dd2_monk_staff_swing", 4);
        DD2_PhantomPhoenixShot = CreateTrackable("dd2_phantom_phoenix_shot", 3);
        DD2_SonicBoomBladeSlash = CreateTrackable("dd2_sonic_boom_blade_slash", 3, SoundStyleDefaults.ItemDefaults).WithVolume(0.5f);
        DD2_SkyDragonsFuryCircle = CreateTrackable("dd2_sky_dragons_fury_circle", 3);
        DD2_SkyDragonsFuryShot = CreateTrackable("dd2_sky_dragons_fury_shot", 3);
        DD2_SkyDragonsFurySwing = CreateTrackable("dd2_sky_dragons_fury_swing", 4);
        LucyTheAxeTalk = CreateTrackable("lucyaxe_talk", 5).WithVolume(0.4f).WithPitchVariance(0.1f);
        DeerclopsHit = CreateTrackable("deerclops_hit", 3).WithVolume(0.3f);
        DeerclopsDeath = CreateTrackable("deerclops_death");
        DeerclopsScream = CreateTrackable("deerclops_scream", 3);
        DeerclopsIceAttack = CreateTrackable("deerclops_ice_attack", 3).WithVolume(0.1f);
        DeerclopsRubbleAttack = CreateTrackable("deerclops_rubble_attack").WithVolume(0.5f);
        DeerclopsStep = CreateTrackable("deerclops_step").WithVolume(0.2f);
        ChesterOpen = CreateTrackable("chester_open", 2);
        ChesterClose = CreateTrackable("chester_close", 2);
        AbigailSummon = CreateTrackable("abigail_summon");
        AbigailCry = CreateTrackable("abigail_cry", 3).WithVolume(0.4f);
        AbigailAttack = CreateTrackable("abigail_attack").WithVolume(0.35f);
        AbigailUpgrade = CreateTrackable("abigail_upgrade", 3).WithVolume(0.5f);
        GlommerBounce = CreateTrackable("glommer_bounce", 2).WithVolume(0.5f);
        DSTMaleHurt = CreateTrackable("dst_male_hit", 3).WithVolume(0.1f);
        DSTFemaleHurt = CreateTrackable("dst_female_hit", 3).WithVolume(0.1f);
        JimsDrone = CreateTrackable("Drone").WithVolume(0.1f);
        SoundByName = null;
        IndexByName = null;
        SoundByIndex = null;
        Dig = new SoundStyle("Terraria/Sounds/Dig_", 0, 3)
        {
            PitchVariance = 0.2f
        };
        PlayerHit = new SoundStyle("Terraria/Sounds/Player_Hit_", 0, 3)
        {
            PitchVariance = 0.2f
        };
        Item = new SoundStyle("Terraria/Sounds/Item_");
        PlayerKilled = new SoundStyle("Terraria/Sounds/Player_Killed");
        Grass = new SoundStyle("Terraria/Sounds/Grass")
        {
            PitchVariance = 0.6f
        };
        Grab = new SoundStyle("Terraria/Sounds/Grab")
        {
            PitchVariance = 0.2f
        };
        DoorOpen = new SoundStyle("Terraria/Sounds/Door_Opened")
        {
            PitchVariance = 0.4f
        };
        DoorClosed = new SoundStyle("Terraria/Sounds/Door_Closed")
        {
            PitchVariance = 0.4f
        };
        MenuOpen = new SoundStyle("Terraria/Sounds/Menu_Open");
        MenuClose = new SoundStyle("Terraria/Sounds/Menu_Close");
        MenuTick = new SoundStyle("Terraria/Sounds/Menu_Tick")
        {
            PlayOnlyIfFocused = true
        };
        Shatter = new SoundStyle("Terraria/Sounds/Shatter");
        ZombieMoan = new SoundStyle("Terraria/Sounds/Zombie_", 0, 3)
        {
            Volume = 0.4f
        };
        SandShark = new SoundStyle("Terraria/Sounds/Zombie_7")
        {
            Volume = 0.4f
        };
        BloodZombie = new SoundStyle("Terraria/Sounds/Zombie_", 21, 3)
        {
            Volume = 0.4f
        };
        Roar = new SoundStyle("Terraria/Sounds/Roar_0")
        {
            Identifier = "Terraria/Roar",
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        WormDig = new SoundStyle("Terraria/Sounds/Roar_1")
        {
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        WormDigQuiet = WormDig with
        {
            Volume = 0.25f
        };
        ScaryScream = new SoundStyle("Terraria/Sounds/Roar_2")
        {
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        DoubleJump = new SoundStyle("Terraria/Sounds/Double_Jump")
        {
            PitchVariance = 0.2f
        };
        Run = new SoundStyle("Terraria/Sounds/Run")
        {
            PitchVariance = 0.2f
        };
        Coins = new SoundStyle("Terraria/Sounds/Coins");
        Splash = new SoundStyle("Terraria/Sounds/Splash_0")
        {
            PitchVariance = 0.2f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        SplashWeak = new SoundStyle("Terraria/Sounds/Splash_1")
        {
            PitchVariance = 0.2f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        Shimmer1 = new SoundStyle("Terraria/Sounds/Splash_2")
        {
            Volume = 0.75f,
            PitchVariance = 0.2f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        Shimmer2 = new SoundStyle("Terraria/Sounds/Splash_3")
        {
            Volume = 0.75f,
            PitchVariance = 0.2f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        ShimmerWeak1 = new SoundStyle("Terraria/Sounds/Splash_4")
        {
            Volume = 0.75f,
            Pitch = -0.1f,
            PitchVariance = 0.2f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        ShimmerWeak2 = new SoundStyle("Terraria/Sounds/Splash_5")
        {
            Volume = 0.75f,
            Pitch = -0.1f,
            PitchVariance = 0.2f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        FemaleHit = new SoundStyle("Terraria/Sounds/Female_Hit_", 0, 3);
        Tink = new SoundStyle("Terraria/Sounds/Tink_", 0, 3);
        Unlock = new SoundStyle("Terraria/Sounds/Unlock");
        Drown = new SoundStyle("Terraria/Sounds/Drown");
        Chat = new SoundStyle("Terraria/Sounds/Chat");
        MaxMana = new SoundStyle("Terraria/Sounds/MaxMana");
        Mummy = new SoundStyle("Terraria/Sounds/Zombie_", 3, 2)
        {
            Volume = 0.9f,
            PitchVariance = 0.2f
        };
        Pixie = new SoundStyle("Terraria/Sounds/Pixie")
        {
            PitchVariance = 0.2f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        Mech = new SoundStyle("Terraria/Sounds/Mech_0")
        {
            PitchVariance = 0.2f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        Span<(int, float)> span = stackalloc(int, float)[3]
        {
            (10, 300f),
            (11, 300f),
            (12, 1f)
        };
        Duck = new SoundStyle("Terraria/Sounds/Zombie_", span, SoundType.Ambient)
        {
            Volume = 0.75f,
            PitchRange = (minPitch: -0.7f, maxPitch: 0f)
        };
        Frog = new SoundStyle("Terraria/Sounds/Zombie_13", SoundType.Ambient)
        {
            Volume = 0.35f,
            PitchRange = (minPitch: -0.4f, maxPitch: 0.2f)
        };
        Bird = new SoundStyle("Terraria/Sounds/Zombie_", 14, 5, SoundType.Ambient)
        {
            Volume = 0.15f,
            PitchRange = (minPitch: -0.7f, maxPitch: 0.26f),
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        Critter = new SoundStyle("Terraria/Sounds/Zombie_15", SoundType.Ambient)
        {
            Volume = 0.2f,
            PitchRange = (minPitch: -0.1f, maxPitch: 0.3f),
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        Waterfall = new SoundStyle("Terraria/Sounds/Liquid_0", SoundType.Ambient)
        {
            Volume = 0.2f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        Lavafall = new SoundStyle("Terraria/Sounds/Liquid_1", SoundType.Ambient)
        {
            Volume = 0.65f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        ForceRoar = new SoundStyle("Terraria/Sounds/Roar_0")
        {
            Identifier = "Terraria/Roar"
        };
        ForceRoarPitched = new SoundStyle("Terraria/Sounds/Roar_0")
        {
            Pitch = 0.6f,
            Identifier = "Terraria/Roar"
        };
        Meowmere = new SoundStyle("Terraria/Sounds/Item_", 57, 2)
        {
            PitchVariance = 0.8f
        };
        CoinPickup = new SoundStyle("Terraria/Sounds/Coin_", 0, 5)
        {
            PitchVariance = 0.16f
        };
        Drip = new SoundStyle("Terraria/Sounds/Drip_", 0, 3, SoundType.Ambient)
        {
            Volume = 0.5f,
            PitchVariance = 0.6f
        };
        Camera = new SoundStyle("Terraria/Sounds/Camera");
        MoonLord = new SoundStyle("Terraria/Sounds/NPC_Killed_10")
        {
            PitchVariance = 0.2f
        };
        Thunder = new SoundStyle("Terraria/Sounds/Thunder_", 0, 7, SoundType.Ambient)
        {
            MaxInstances = 7,
            PitchVariance = 0.2f
        };
        Seagull = new SoundStyle("Terraria/Sounds/Zombie_", 106, 3)
        {
            Volume = 0.2f,
            PitchRange = (minPitch: -0.7f, maxPitch: 0f)
        };
        Dolphin = new SoundStyle("Terraria/Sounds/Zombie_109")
        {
            Volume = 0.3f,
            PitchVariance = 0.2f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        span = stackalloc(int, float)[5]
        {
            (110, 300f),
            (111, 300f),
            (112, 1f),
            (113, 1f),
            (114, 1f)
        };
        Owl = new SoundStyle("Terraria/Sounds/Zombie_", span)
        {
            PitchVariance = 0.2f
        };
        GuitarC = new SoundStyle("Terraria/Sounds/Item_133")
        {
            Volume = 0.45f,
            Identifier = "Terraria/Guitar"
        };
        GuitarD = new SoundStyle("Terraria/Sounds/Item_134")
        {
            Volume = 0.45f,
            Identifier = "Terraria/Guitar"
        };
        GuitarEm = new SoundStyle("Terraria/Sounds/Item_135")
        {
            Volume = 0.45f,
            Identifier = "Terraria/Guitar"
        };
        GuitarG = new SoundStyle("Terraria/Sounds/Item_136")
        {
            Volume = 0.45f,
            Identifier = "Terraria/Guitar"
        };
        GuitarBm = new SoundStyle("Terraria/Sounds/Item_137")
        {
            Volume = 0.45f,
            Identifier = "Terraria/Guitar"
        };
        GuitarAm = new SoundStyle("Terraria/Sounds/Item_138")
        {
            Volume = 0.45f,
            Identifier = "Terraria/Guitar"
        };
        DrumHiHat = new SoundStyle("Terraria/Sounds/Item_139")
        {
            Volume = 0.7f,
            Identifier = "Terraria/Drums"
        };
        DrumTomHigh = new SoundStyle("Terraria/Sounds/Item_140")
        {
            Volume = 0.7f,
            Identifier = "Terraria/Drums"
        };
        DrumTomLow = new SoundStyle("Terraria/Sounds/Item_141")
        {
            Volume = 0.7f,
            Identifier = "Terraria/Drums"
        };
        DrumTomMid = new SoundStyle("Terraria/Sounds/Item_142")
        {
            Volume = 0.7f,
            Identifier = "Terraria/Drums"
        };
        DrumClosedHiHat = new SoundStyle("Terraria/Sounds/Item_143")
        {
            Volume = 0.7f,
            Identifier = "Terraria/Drums"
        };
        DrumCymbal1 = new SoundStyle("Terraria/Sounds/Item_144")
        {
            Volume = 0.7f,
            Identifier = "Terraria/Drums"
        };
        DrumCymbal2 = new SoundStyle("Terraria/Sounds/Item_145")
        {
            Volume = 0.7f,
            Identifier = "Terraria/Drums"
        };
        DrumKick = new SoundStyle("Terraria/Sounds/Item_146")
        {
            Volume = 0.7f,
            Identifier = "Terraria/Drums"
        };
        DrumTamaSnare = new SoundStyle("Terraria/Sounds/Item_147")
        {
            Volume = 0.7f,
            Identifier = "Terraria/Drums"
        };
        DrumFloorTom = new SoundStyle("Terraria/Sounds/Item_148")
        {
            Volume = 0.7f,
            Identifier = "Terraria/Drums"
        };
        Research = new SoundStyle("Terraria/Sounds/Research_", 1, 3);
        ResearchComplete = new SoundStyle("Terraria/Sounds/Research_0");
        QueenSlime = new SoundStyle("Terraria/Sounds/Zombie_", 115, 3)
        {
            Volume = 0.5f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        Clown = new SoundStyle("Terraria/Sounds/Zombie_", 121, 3)
        {
            Volume = 0.45f,
            PitchVariance = 0.15f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        Cockatiel = new SoundStyle("Terraria/Sounds/Zombie_", 118, 3)
        {
            Volume = 0.3f,
            PitchVariance = 0.05f
        };
        Macaw = new SoundStyle("Terraria/Sounds/Zombie_", 126, 3)
        {
            Volume = 0.22f,
            PitchVariance = 0.05f
        };
        Toucan = new SoundStyle("Terraria/Sounds/Zombie_", 129, 3)
        {
            Volume = 0.2f,
            PitchVariance = 0.05f
        };
        NPCHit1 = NPCHitSound(1);
        NPCHit2 = NPCHitSound(2);
        NPCHit3 = NPCHitSound(3);
        NPCHit4 = NPCHitSound(4);
        NPCHit5 = NPCHitSound(5);
        NPCHit6 = NPCHitSound(6);
        NPCHit7 = NPCHitSound(7);
        NPCHit8 = NPCHitSound(8);
        NPCHit9 = NPCHitSound(9);
        NPCHit10 = NPCHitSound(10);
        NPCHit11 = NPCHitSound(11);
        NPCHit12 = NPCHitSound(12);
        NPCHit13 = NPCHitSound(13);
        NPCHit14 = NPCHitSound(14);
        NPCHit15 = NPCHitSound(15);
        NPCHit16 = NPCHitSound(16);
        NPCHit17 = NPCHitSound(17);
        NPCHit18 = NPCHitSound(18);
        NPCHit19 = NPCHitSound(19);
        NPCHit20 = NPCHitSound(20)with
        {
            Volume = 0.5f
        };
        NPCHit21 = NPCHitSound(21)with
        {
            Volume = 0.5f
        };
        NPCHit22 = NPCHitSound(22)with
        {
            Volume = 0.5f
        };
        NPCHit23 = NPCHitSound(23)with
        {
            Volume = 0.5f
        };
        NPCHit24 = NPCHitSound(24)with
        {
            Volume = 0.5f
        };
        NPCHit25 = NPCHitSound(25)with
        {
            Volume = 0.5f
        };
        NPCHit26 = NPCHitSound(26)with
        {
            Volume = 0.5f
        };
        NPCHit27 = NPCHitSound(27)with
        {
            Volume = 0.5f
        };
        NPCHit28 = NPCHitSound(28)with
        {
            Volume = 0.5f
        };
        NPCHit29 = NPCHitSound(29)with
        {
            Volume = 0.5f
        };
        NPCHit30 = NPCHitSound(30)with
        {
            Volume = 0.5f
        };
        NPCHit31 = NPCHitSound(31)with
        {
            Volume = 0.5f
        };
        NPCHit32 = NPCHitSound(32)with
        {
            Volume = 0.5f
        };
        NPCHit33 = NPCHitSound(33)with
        {
            Volume = 0.5f
        };
        NPCHit34 = NPCHitSound(34)with
        {
            Volume = 0.5f
        };
        NPCHit35 = NPCHitSound(35)with
        {
            Volume = 0.5f
        };
        NPCHit36 = NPCHitSound(36)with
        {
            Volume = 0.5f
        };
        NPCHit37 = NPCHitSound(37)with
        {
            Volume = 0.5f
        };
        NPCHit38 = NPCHitSound(38)with
        {
            Volume = 0.5f
        };
        NPCHit39 = NPCHitSound(39)with
        {
            Volume = 0.5f
        };
        NPCHit40 = NPCHitSound(40)with
        {
            Volume = 0.5f
        };
        NPCHit41 = NPCHitSound(41)with
        {
            Volume = 0.5f
        };
        NPCHit42 = NPCHitSound(42)with
        {
            Volume = 0.5f
        };
        NPCHit43 = NPCHitSound(43)with
        {
            Volume = 0.5f
        };
        NPCHit44 = NPCHitSound(44)with
        {
            Volume = 0.5f
        };
        NPCHit45 = NPCHitSound(45)with
        {
            Volume = 0.5f
        };
        NPCHit46 = NPCHitSound(46)with
        {
            Volume = 0.5f
        };
        NPCHit47 = NPCHitSound(47)with
        {
            Volume = 0.5f
        };
        NPCHit48 = NPCHitSound(48)with
        {
            Volume = 0.5f
        };
        NPCHit49 = NPCHitSound(49)with
        {
            Volume = 0.5f
        };
        NPCHit50 = NPCHitSound(50)with
        {
            Volume = 0.5f
        };
        NPCHit51 = NPCHitSound(51)with
        {
            Volume = 0.5f
        };
        NPCHit52 = NPCHitSound(52)with
        {
            Volume = 0.5f
        };
        NPCHit53 = NPCHitSound(53)with
        {
            Volume = 0.5f
        };
        NPCHit54 = NPCHitSound(54)with
        {
            Volume = 0.5f
        };
        NPCHit55 = NPCHitSound(55)with
        {
            Volume = 0.5f
        };
        NPCHit56 = NPCHitSound(56)with
        {
            Volume = 0.5f
        };
        NPCHit57 = NPCHitSound(57)with
        {
            Volume = 0.6f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        NPCHitCount = 58;
        NPCDeath1 = NPCDeathSound(1);
        NPCDeath2 = NPCDeathSound(2);
        NPCDeath3 = NPCDeathSound(3);
        NPCDeath4 = NPCDeathSound(4);
        NPCDeath5 = NPCDeathSound(5);
        NPCDeath6 = NPCDeathSound(6);
        NPCDeath7 = NPCDeathSound(7);
        NPCDeath8 = NPCDeathSound(8);
        NPCDeath9 = NPCDeathSound(9);
        NPCDeath10 = NPCDeathSound(10)with
        {
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        NPCDeath11 = NPCDeathSound(11);
        NPCDeath12 = NPCDeathSound(12);
        NPCDeath13 = NPCDeathSound(13);
        NPCDeath14 = NPCDeathSound(14);
        NPCDeath15 = NPCDeathSound(15);
        NPCDeath16 = NPCDeathSound(16);
        NPCDeath17 = NPCDeathSound(17);
        NPCDeath18 = NPCDeathSound(18);
        NPCDeath19 = NPCDeathSound(19);
        NPCDeath20 = NPCDeathSound(20);
        NPCDeath21 = NPCDeathSound(21);
        NPCDeath22 = NPCDeathSound(22);
        NPCDeath23 = NPCDeathSound(23)with
        {
            Volume = 0.5f
        };
        NPCDeath24 = NPCDeathSound(24)with
        {
            Volume = 0.5f
        };
        NPCDeath25 = NPCDeathSound(25)with
        {
            Volume = 0.5f
        };
        NPCDeath26 = NPCDeathSound(26)with
        {
            Volume = 0.5f
        };
        NPCDeath27 = NPCDeathSound(27)with
        {
            Volume = 0.5f
        };
        NPCDeath28 = NPCDeathSound(28)with
        {
            Volume = 0.5f
        };
        NPCDeath29 = NPCDeathSound(29)with
        {
            Volume = 0.5f
        };
        NPCDeath30 = NPCDeathSound(30)with
        {
            Volume = 0.5f
        };
        NPCDeath31 = NPCDeathSound(31)with
        {
            Volume = 0.5f
        };
        NPCDeath32 = NPCDeathSound(32)with
        {
            Volume = 0.5f
        };
        NPCDeath33 = NPCDeathSound(33)with
        {
            Volume = 0.5f
        };
        NPCDeath34 = NPCDeathSound(34)with
        {
            Volume = 0.5f
        };
        NPCDeath35 = NPCDeathSound(35)with
        {
            Volume = 0.5f
        };
        NPCDeath36 = NPCDeathSound(36)with
        {
            Volume = 0.5f
        };
        NPCDeath37 = NPCDeathSound(37)with
        {
            Volume = 0.5f
        };
        NPCDeath38 = NPCDeathSound(38)with
        {
            Volume = 0.5f
        };
        NPCDeath39 = NPCDeathSound(39)with
        {
            Volume = 0.5f
        };
        NPCDeath40 = NPCDeathSound(40)with
        {
            Volume = 0.5f
        };
        NPCDeath41 = NPCDeathSound(41)with
        {
            Volume = 0.5f
        };
        NPCDeath42 = NPCDeathSound(42)with
        {
            Volume = 0.5f
        };
        NPCDeath43 = NPCDeathSound(43)with
        {
            Volume = 0.5f
        };
        NPCDeath44 = NPCDeathSound(44)with
        {
            Volume = 0.5f
        };
        NPCDeath45 = NPCDeathSound(45)with
        {
            Volume = 0.5f
        };
        NPCDeath46 = NPCDeathSound(46)with
        {
            Volume = 0.5f
        };
        NPCDeath47 = NPCDeathSound(47)with
        {
            Volume = 0.5f
        };
        NPCDeath48 = NPCDeathSound(48)with
        {
            Volume = 0.5f
        };
        NPCDeath49 = NPCDeathSound(49)with
        {
            Volume = 0.5f
        };
        NPCDeath50 = NPCDeathSound(50)with
        {
            Volume = 0.5f
        };
        NPCDeath51 = NPCDeathSound(51)with
        {
            Volume = 0.5f
        };
        NPCDeath52 = NPCDeathSound(52)with
        {
            Volume = 0.5f
        };
        NPCDeath53 = NPCDeathSound(53)with
        {
            Volume = 0.5f
        };
        NPCDeath54 = NPCDeathSound(54)with
        {
            Volume = 0.5f
        };
        NPCDeath55 = NPCDeathSound(55)with
        {
            Volume = 0.5f
        };
        NPCDeath56 = NPCDeathSound(56)with
        {
            Volume = 0.5f
        };
        NPCDeath57 = NPCDeathSound(57)with
        {
            Volume = 0.5f
        };
        NPCDeath58 = NPCDeathSound(58);
        NPCDeath59 = NPCDeathSound(59);
        NPCDeath60 = NPCDeathSound(60);
        NPCDeath61 = NPCDeathSound(61)with
        {
            Volume = 0.6f
        };
        NPCDeath62 = NPCDeathSound(62)with
        {
            Volume = 0.6f
        };
        NPCDeath63 = NPCDeathSound(63);
        NPCDeath64 = NPCDeathSound(64);
        NPCDeath65 = NPCDeathSound(65);
        NPCDeath66 = NPCDeathSound(66);
        NPCDeathCount = 66;
        Item1 = ItemSound(stackalloc int[3] { 1, 18, 19 });
        Item2 = ItemSound(2);
        Item3 = ItemSound(3);
        Item4 = ItemSound(4);
        Item5 = ItemSound(5);
        Item6 = ItemSound(6);
        Item7 = ItemSound(7);
        Item8 = ItemSound(8);
        Item9 = ItemSound(9);
        Item10 = ItemSound(10);
        Item11 = ItemSound(11);
        Item12 = ItemSound(12);
        Item13 = ItemSound(13);
        Item14 = ItemSound(14);
        Item15 = ItemSound(15);
        Item16 = ItemSound(16);
        Item17 = ItemSound(17);
        Item18 = ItemSound(18);
        Item19 = ItemSound(19);
        Item20 = ItemSound(20);
        Item21 = ItemSound(21);
        Item22 = ItemSound(22);
        Item23 = ItemSound(23);
        Item24 = ItemSound(24);
        Item25 = ItemSound(25);
        Item26 = ItemSound(26)with
        {
            Volume = 0.75f,
            PitchVariance = 0f,
            UsesMusicPitch = true
        };
        Item27 = ItemSound(27);
        Item28 = ItemSound(28);
        Item29 = ItemSound(29);
        Item30 = ItemSound(30);
        Item31 = ItemSound(31);
        Item32 = ItemSound(32);
        Item33 = ItemSound(33);
        Item34 = ItemSound(34);
        Item35 = ItemSound(35)with
        {
            Volume = 0.75f,
            PitchVariance = 0f,
            UsesMusicPitch = true
        };
        Item36 = ItemSound(36);
        Item37 = ItemSound(37)with
        {
            Volume = 0.5f
        };
        Item38 = ItemSound(38);
        Item39 = ItemSound(39);
        Item40 = ItemSound(40);
        Item41 = ItemSound(41);
        Item42 = ItemSound(42);
        Item43 = ItemSound(43);
        Item44 = ItemSound(44);
        Item45 = ItemSound(45);
        Item46 = ItemSound(46);
        Item47 = ItemSound(47)with
        {
            Volume = 0.75f,
            PitchVariance = 0f,
            UsesMusicPitch = true
        };
        Item48 = ItemSound(48);
        Item49 = ItemSound(49);
        Item50 = ItemSound(50);
        Item51 = ItemSound(51);
        Item52 = ItemSound(52)with
        {
            Volume = 0.35f
        };
        Item53 = ItemSound(53)with
        {
            Volume = 0.75f,
            PitchRange = (minPitch: -0.4f, maxPitch: -0.2f),
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        Item54 = ItemSound(54);
        Item55 = ItemSound(55)with
        {
            Volume = 0.5625f,
            PitchRange = (minPitch: -0.4f, maxPitch: -0.2f),
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        Item56 = ItemSound(56);
        Item57 = ItemSound(57);
        Item58 = ItemSound(58);
        Item59 = ItemSound(59);
        Item60 = ItemSound(60);
        Item61 = ItemSound(61);
        Item62 = ItemSound(62);
        Item63 = ItemSound(63);
        Item64 = ItemSound(64);
        Item65 = ItemSound(65);
        Item66 = ItemSound(66);
        Item67 = ItemSound(67);
        Item68 = ItemSound(68);
        Item69 = ItemSound(69);
        Item70 = ItemSound(70);
        Item71 = ItemSound(71);
        Item72 = ItemSound(72);
        Item73 = ItemSound(73);
        Item74 = ItemSound(74);
        Item75 = ItemSound(75);
        Item76 = ItemSound(76);
        Item77 = ItemSound(77);
        Item78 = ItemSound(78);
        Item79 = ItemSound(79);
        Item80 = ItemSound(80);
        Item81 = ItemSound(81);
        Item82 = ItemSound(82);
        Item83 = ItemSound(83);
        Item84 = ItemSound(84);
        Item85 = ItemSound(85);
        Item86 = ItemSound(86);
        Item87 = ItemSound(87);
        Item88 = ItemSound(88);
        Item89 = ItemSound(89);
        Item90 = ItemSound(90);
        Item91 = ItemSound(91);
        Item92 = ItemSound(92);
        Item93 = ItemSound(93);
        Item94 = ItemSound(94);
        Item95 = ItemSound(95);
        Item96 = ItemSound(96);
        Item97 = ItemSound(97);
        Item98 = ItemSound(98);
        Item99 = ItemSound(99);
        Item100 = ItemSound(100);
        Item101 = ItemSound(101);
        Item102 = ItemSound(102);
        Item103 = ItemSound(103);
        Item104 = ItemSound(104);
        Item105 = ItemSound(105);
        Item106 = ItemSound(106);
        Item107 = ItemSound(107);
        Item108 = ItemSound(108);
        Item109 = ItemSound(109);
        Item110 = ItemSound(110);
        Item111 = ItemSound(111);
        Item112 = ItemSound(112);
        Item113 = ItemSound(113);
        Item114 = ItemSound(114);
        Item115 = ItemSound(115);
        Item116 = ItemSound(116)with
        {
            Volume = 0.5f
        };
        Item117 = ItemSound(117);
        Item118 = ItemSound(118);
        Item119 = ItemSound(119);
        Item120 = ItemSound(120);
        Item121 = ItemSound(121);
        Item122 = ItemSound(122);
        Item123 = ItemSound(123)with
        {
            Volume = 0.5f
        };
        Item124 = ItemSound(124)with
        {
            Volume = 0.65f
        };
        Item125 = ItemSound(125)with
        {
            Volume = 0.65f
        };
        Item126 = ItemSound(126);
        Item127 = ItemSound(127);
        Item128 = ItemSound(128);
        Item129 = ItemSound(129)with
        {
            Volume = 0.6f
        };
        Item130 = ItemSound(130);
        Item131 = ItemSound(131);
        Item132 = ItemSound(132)with
        {
            PitchVariance = 0.04f
        };
        Item133 = ItemSound(133);
        Item134 = ItemSound(134);
        Item135 = ItemSound(135);
        Item136 = ItemSound(136);
        Item137 = ItemSound(137);
        Item138 = ItemSound(138);
        Item139 = ItemSound(139);
        Item140 = ItemSound(140);
        Item141 = ItemSound(141);
        Item142 = ItemSound(142);
        Item143 = ItemSound(143);
        Item144 = ItemSound(144);
        Item145 = ItemSound(145);
        Item146 = ItemSound(146);
        Item147 = ItemSound(147);
        Item148 = ItemSound(148);
        Item149 = ItemSound(149);
        Item150 = ItemSound(150);
        Item151 = ItemSound(151);
        Item152 = ItemSound(152);
        Item153 = ItemSound(153)with
        {
            PitchVariance = 0.3f
        };
        Item154 = ItemSound(154);
        Item155 = ItemSound(155);
        Item156 = ItemSound(156)with
        {
            Volume = 0.6f,
            PitchVariance = 0.2f
        };
        Item157 = ItemSound(157)with
        {
            Volume = 0.7f
        };
        Item158 = ItemSound(158)with
        {
            Volume = 0.8f
        };
        Item159 = ItemSound(159)with
        {
            Volume = 0.75f,
            SoundLimitBehavior = SoundLimitBehavior.IgnoreNew
        };
        Item160 = ItemSound(160);
        Item161 = ItemSound(161);
        Item162 = ItemSound(162);
        Item163 = ItemSound(163);
        Item164 = ItemSound(164);
        Item165 = ItemSound(165);
        Item166 = ItemSound(166);
        Item167 = ItemSound(167);
        Item168 = ItemSound(168);
        Item169 = ItemSound(169)with
        {
            Pitch = -0.8f
        };
        Item170 = ItemSound(170);
        Item171 = ItemSound(171);
        Item172 = ItemSound(172);
        Item173 = ItemSound(173);
        Item174 = ItemSound(174);
        Item175 = ItemSound(175);
        Item176 = ItemSound(176);
        Item177 = ItemSound(177);
        Item178 = ItemSound(178);
        Zombie1 = ZombieSound(1);
        Zombie2 = ZombieSound(2);
        Zombie3 = ZombieSound(3);
        Zombie4 = ZombieSound(4);
        Zombie5 = ZombieSound(5);
        Zombie6 = ZombieSound(6);
        Zombie7 = ZombieSound(7);
        Zombie8 = ZombieSound(8);
        Zombie9 = ZombieSound(9);
        Zombie10 = ZombieSound(10);
        Zombie11 = ZombieSound(11);
        Zombie12 = ZombieSound(12);
        Zombie13 = ZombieSound(13);
        Zombie14 = ZombieSound(14);
        Zombie15 = ZombieSound(15);
        Zombie16 = ZombieSound(16);
        Zombie17 = ZombieSound(17);
        Zombie18 = ZombieSound(18);
        Zombie19 = ZombieSound(19);
        Zombie20 = ZombieSound(20);
        Zombie21 = ZombieSound(21);
        Zombie22 = ZombieSound(22);
        Zombie23 = ZombieSound(23);
        Zombie24 = ZombieSound(24)with
        {
            Volume = 0.5f
        };
        Zombie25 = ZombieSound(25)with
        {
            Volume = 0.5f
        };
        Zombie26 = ZombieSound(26)with
        {
            Volume = 0.5f
        };
        Zombie27 = ZombieSound(27)with
        {
            Volume = 0.5f
        };
        Zombie28 = ZombieSound(28)with
        {
            Volume = 0.5f
        };
        Zombie29 = ZombieSound(29)with
        {
            Volume = 0.5f
        };
        Zombie30 = ZombieSound(30)with
        {
            Volume = 0.5f
        };
        Zombie31 = ZombieSound(31)with
        {
            Volume = 0.5f
        };
        Zombie32 = ZombieSound(32)with
        {
            Volume = 0.5f
        };
        Zombie33 = ZombieSound(33)with
        {
            Volume = 0.5f
        };
        Zombie34 = ZombieSound(34)with
        {
            Volume = 0.5f
        };
        Zombie35 = ZombieSound(35)with
        {
            Volume = 0.5f
        };
        Zombie36 = ZombieSound(36)with
        {
            Volume = 0.5f
        };
        Zombie37 = ZombieSound(37)with
        {
            Volume = 0.5f
        };
        Zombie38 = ZombieSound(38)with
        {
            Volume = 0.5f
        };
        Zombie39 = ZombieSound(39)with
        {
            Volume = 0.5f
        };
        Zombie40 = ZombieSound(40)with
        {
            Volume = 0.5f
        };
        Zombie41 = ZombieSound(41)with
        {
            Volume = 0.5f
        };
        Zombie42 = ZombieSound(42)with
        {
            Volume = 0.5f
        };
        Zombie43 = ZombieSound(43)with
        {
            Volume = 0.5f
        };
        Zombie44 = ZombieSound(44)with
        {
            Volume = 0.5f
        };
        Zombie45 = ZombieSound(45)with
        {
            Volume = 0.5f
        };
        Zombie46 = ZombieSound(46)with
        {
            Volume = 0.5f
        };
        Zombie47 = ZombieSound(47)with
        {
            Volume = 0.5f
        };
        Zombie48 = ZombieSound(48)with
        {
            Volume = 0.5f
        };
        Zombie49 = ZombieSound(49)with
        {
            Volume = 0.5f
        };
        Zombie50 = ZombieSound(50)with
        {
            Volume = 0.5f
        };
        Zombie51 = ZombieSound(51)with
        {
            Volume = 0.5f
        };
        Zombie52 = ZombieSound(52)with
        {
            Volume = 0.5f
        };
        Zombie53 = ZombieSound(53)with
        {
            Volume = 0.5f
        };
        Zombie54 = ZombieSound(54)with
        {
            Volume = 0.5f
        };
        Zombie55 = ZombieSound(55)with
        {
            Volume = 0.5f
        };
        Zombie56 = ZombieSound(56)with
        {
            Volume = 0.5f
        };
        Zombie57 = ZombieSound(57)with
        {
            Volume = 0.5f
        };
        Zombie58 = ZombieSound(58)with
        {
            Volume = 0.5f
        };
        Zombie59 = ZombieSound(59)with
        {
            Volume = 0.5f
        };
        Zombie60 = ZombieSound(60)with
        {
            Volume = 0.5f
        };
        Zombie61 = ZombieSound(61)with
        {
            Volume = 0.5f
        };
        Zombie62 = ZombieSound(62)with
        {
            Volume = 0.5f
        };
        Zombie63 = ZombieSound(63)with
        {
            Volume = 0.5f
        };
        Zombie64 = ZombieSound(64)with
        {
            Volume = 0.5f
        };
        Zombie65 = ZombieSound(65)with
        {
            Volume = 0.5f
        };
        Zombie66 = ZombieSound(66)with
        {
            Volume = 0.5f
        };
        Zombie67 = ZombieSound(67)with
        {
            Volume = 0.5f
        };
        Zombie68 = ZombieSound(68)with
        {
            Volume = 0.5f
        };
        Zombie69 = ZombieSound(69)with
        {
            Volume = 0.5f
        };
        Zombie70 = ZombieSound(70)with
        {
            Volume = 0.5f
        };
        Zombie71 = ZombieSound(71)with
        {
            Volume = 0.5f
        };
        Zombie72 = ZombieSound(72)with
        {
            Volume = 0.5f
        };
        Zombie73 = ZombieSound(73)with
        {
            Volume = 0.5f
        };
        Zombie74 = ZombieSound(74)with
        {
            Volume = 0.5f
        };
        Zombie75 = ZombieSound(75)with
        {
            Volume = 0.5f
        };
        Zombie76 = ZombieSound(76)with
        {
            Volume = 0.5f
        };
        Zombie77 = ZombieSound(77)with
        {
            Volume = 0.5f
        };
        Zombie78 = ZombieSound(78)with
        {
            Volume = 0.5f
        };
        Zombie79 = ZombieSound(79)with
        {
            Volume = 0.5f
        };
        Zombie80 = ZombieSound(80)with
        {
            Volume = 0.5f
        };
        Zombie81 = ZombieSound(81)with
        {
            Volume = 0.5f
        };
        Zombie82 = ZombieSound(82)with
        {
            Volume = 0.5f
        };
        Zombie83 = ZombieSound(83)with
        {
            Volume = 0.5f
        };
        Zombie84 = ZombieSound(84)with
        {
            Volume = 0.5f
        };
        Zombie85 = ZombieSound(85)with
        {
            Volume = 0.5f
        };
        Zombie86 = ZombieSound(86)with
        {
            Volume = 0.5f
        };
        Zombie87 = ZombieSound(87)with
        {
            Volume = 0.5f
        };
        Zombie88 = ZombieSound(88)with
        {
            Volume = 0.7f
        };
        Zombie89 = ZombieSound(89)with
        {
            Volume = 0.7f
        };
        Zombie90 = ZombieSound(90)with
        {
            Volume = 0.7f
        };
        Zombie91 = ZombieSound(91)with
        {
            Volume = 0.7f
        };
        Zombie92 = ZombieSound(92)with
        {
            Volume = 0.5f
        };
        Zombie93 = ZombieSound(93)with
        {
            Volume = 0.4f
        };
        Zombie94 = ZombieSound(94)with
        {
            Volume = 0.4f
        };
        Zombie95 = ZombieSound(95)with
        {
            Volume = 0.4f
        };
        Zombie96 = ZombieSound(96)with
        {
            Volume = 0.4f
        };
        Zombie97 = ZombieSound(97)with
        {
            Volume = 0.4f
        };
        Zombie98 = ZombieSound(98)with
        {
            Volume = 0.4f
        };
        Zombie99 = ZombieSound(99)with
        {
            Volume = 0.4f
        };
        Zombie100 = ZombieSound(100)with
        {
            Volume = 0.25f
        };
        Zombie101 = ZombieSound(101)with
        {
            Volume = 0.25f
        };
        Zombie102 = ZombieSound(102)with
        {
            Volume = 0.4f
        };
        Zombie103 = ZombieSound(103)with
        {
            Volume = 0.4f
        };
        Zombie104 = ZombieSound(104)with
        {
            Volume = 0.55f
        };
        Zombie105 = ZombieSound(105);
        Zombie106 = ZombieSound(106);
        Zombie107 = ZombieSound(107);
        Zombie108 = ZombieSound(108);
        Zombie109 = ZombieSound(109);
        Zombie110 = ZombieSound(110);
        Zombie111 = ZombieSound(111);
        Zombie112 = ZombieSound(112);
        Zombie113 = ZombieSound(113);
        Zombie114 = ZombieSound(114);
        Zombie115 = ZombieSound(115);
        Zombie116 = ZombieSound(116);
        Zombie117 = ZombieSound(117);
        Zombie118 = ZombieSound(118);
        Zombie119 = ZombieSound(119);
        Zombie120 = ZombieSound(120);
        Zombie121 = ZombieSound(121);
        Zombie122 = ZombieSound(122);
        Zombie123 = ZombieSound(123);
        Zombie124 = ZombieSound(124);
        Zombie125 = ZombieSound(125);
        Zombie126 = ZombieSound(126);
        Zombie127 = ZombieSound(127);
        Zombie128 = ZombieSound(128);
        Zombie129 = ZombieSound(129);
        Zombie130 = ZombieSound(130);
        legacyArrayedStylesMapping = new SoundStyle[LegacySoundIDs.Count][];
        FillLegacyArrayedStylesMap();
    }
References Terraria.ID.SoundID.AbigailAttack, Terraria.ID.SoundID.AbigailCry, Terraria.ID.SoundID.AbigailSummon, Terraria.ID.SoundID.AbigailUpgrade, Terraria.ID.SoundID.AchievementComplete, Terraria.ID.SoundID.Bird, Terraria.ID.SoundID.BlizzardInsideBuildingLoop, Terraria.ID.SoundID.BlizzardStrongLoop, Terraria.ID.SoundID.BloodZombie, Terraria.ID.SoundID.Camera, Terraria.ID.SoundID.Chat, Terraria.ID.SoundID.ChesterClose, Terraria.ID.SoundID.ChesterOpen, Terraria.ID.SoundID.Clown, Terraria.ID.SoundID.Cockatiel, Terraria.ID.SoundID.CoinPickup, Terraria.ID.SoundID.Coins, Terraria.ID.LegacySoundIDs.Count, Terraria.ID.SoundID.CreateTrackable(), Terraria.ID.SoundID.Critter, Terraria.ID.SoundID.DD2_BallistaTowerShot, Terraria.ID.SoundID.DD2_BetsyDeath, Terraria.ID.SoundID.DD2_BetsyFireballImpact, Terraria.ID.SoundID.DD2_BetsyFireballShot, Terraria.ID.SoundID.DD2_BetsyFlameBreath, Terraria.ID.SoundID.DD2_BetsyFlyingCircleAttack, Terraria.ID.SoundID.DD2_BetsyHurt, Terraria.ID.SoundID.DD2_BetsyScream, Terraria.ID.SoundID.DD2_BetsySummon, Terraria.ID.SoundID.DD2_BetsysWrathImpact, Terraria.ID.SoundID.DD2_BetsysWrathShot, Terraria.ID.SoundID.DD2_BetsyWindAttack, Terraria.ID.SoundID.DD2_BookStaffCast, Terraria.ID.SoundID.DD2_BookStaffTwisterLoop, Terraria.ID.SoundID.DD2_CrystalCartImpact, Terraria.ID.SoundID.DD2_DarkMageAttack, Terraria.ID.SoundID.DD2_DarkMageCastHeal, Terraria.ID.SoundID.DD2_DarkMageDeath, Terraria.ID.SoundID.DD2_DarkMageHealImpact, Terraria.ID.SoundID.DD2_DarkMageHurt, Terraria.ID.SoundID.DD2_DarkMageSummonSkeleton, Terraria.ID.SoundID.DD2_DefeatScene, Terraria.ID.SoundID.DD2_DefenseTowerSpawn, Terraria.ID.SoundID.DD2_DrakinBreathIn, Terraria.ID.SoundID.DD2_DrakinDeath, Terraria.ID.SoundID.DD2_DrakinHurt, Terraria.ID.SoundID.DD2_DrakinShot, Terraria.ID.SoundID.DD2_EtherianPortalDryadTouch, Terraria.ID.SoundID.DD2_EtherianPortalIdleLoop, Terraria.ID.SoundID.DD2_EtherianPortalOpen, Terraria.ID.SoundID.DD2_EtherianPortalSpawnEnemy, Terraria.ID.SoundID.DD2_ExplosiveTrapExplode, Terraria.ID.SoundID.DD2_FlameburstTowerShot, Terraria.ID.SoundID.DD2_GhastlyGlaiveImpactGhost, Terraria.ID.SoundID.DD2_GhastlyGlaivePierce, Terraria.ID.SoundID.DD2_GoblinBomb, Terraria.ID.SoundID.DD2_GoblinBomberDeath, Terraria.ID.SoundID.DD2_GoblinBomberHurt, Terraria.ID.SoundID.DD2_GoblinBomberScream, Terraria.ID.SoundID.DD2_GoblinBomberThrow, Terraria.ID.SoundID.DD2_GoblinDeath, Terraria.ID.SoundID.DD2_GoblinHurt, Terraria.ID.SoundID.DD2_GoblinScream, Terraria.ID.SoundID.DD2_JavelinThrowersAttack, Terraria.ID.SoundID.DD2_JavelinThrowersDeath, Terraria.ID.SoundID.DD2_JavelinThrowersHurt, Terraria.ID.SoundID.DD2_JavelinThrowersTaunt, Terraria.ID.SoundID.DD2_KoboldDeath, Terraria.ID.SoundID.DD2_KoboldExplosion, Terraria.ID.SoundID.DD2_KoboldFlyerChargeScream, Terraria.ID.SoundID.DD2_KoboldFlyerDeath, Terraria.ID.SoundID.DD2_KoboldFlyerHurt, Terraria.ID.SoundID.DD2_KoboldHurt, Terraria.ID.SoundID.DD2_KoboldIgnite, Terraria.ID.SoundID.DD2_KoboldIgniteLoop, Terraria.ID.SoundID.DD2_KoboldScreamChargeLoop, Terraria.ID.SoundID.DD2_LightningAuraZap, Terraria.ID.SoundID.DD2_LightningBugDeath, Terraria.ID.SoundID.DD2_LightningBugHurt, Terraria.ID.SoundID.DD2_LightningBugZap, Terraria.ID.SoundID.DD2_MonkStaffGroundImpact, Terraria.ID.SoundID.DD2_MonkStaffGroundMiss, Terraria.ID.SoundID.DD2_MonkStaffSwing, Terraria.ID.SoundID.DD2_OgreAttack, Terraria.ID.SoundID.DD2_OgreDeath, Terraria.ID.SoundID.DD2_OgreGroundPound, Terraria.ID.SoundID.DD2_OgreHurt, Terraria.ID.SoundID.DD2_OgreRoar, Terraria.ID.SoundID.DD2_OgreSpit, Terraria.ID.SoundID.DD2_PhantomPhoenixShot, Terraria.ID.SoundID.DD2_SkeletonDeath, Terraria.ID.SoundID.DD2_SkeletonHurt, Terraria.ID.SoundID.DD2_SkeletonSummoned, Terraria.ID.SoundID.DD2_SkyDragonsFuryCircle, Terraria.ID.SoundID.DD2_SkyDragonsFuryShot, Terraria.ID.SoundID.DD2_SkyDragonsFurySwing, Terraria.ID.SoundID.DD2_SonicBoomBladeSlash, Terraria.ID.SoundID.DD2_WinScene, Terraria.ID.SoundID.DD2_WitherBeastAuraPulse, Terraria.ID.SoundID.DD2_WitherBeastCrystalImpact, Terraria.ID.SoundID.DD2_WitherBeastDeath, Terraria.ID.SoundID.DD2_WitherBeastHurt, Terraria.ID.SoundID.DD2_WyvernDeath, Terraria.ID.SoundID.DD2_WyvernDiveDown, Terraria.ID.SoundID.DD2_WyvernHurt, Terraria.ID.SoundID.DD2_WyvernScream, Terraria.ID.SoundID.DeerclopsDeath, Terraria.ID.SoundID.DeerclopsHit, Terraria.ID.SoundID.DeerclopsIceAttack, Terraria.ID.SoundID.DeerclopsRubbleAttack, Terraria.ID.SoundID.DeerclopsScream, Terraria.ID.SoundID.DeerclopsStep, Terraria.ID.SoundID.Dig, Terraria.ID.SoundID.Dolphin, Terraria.ID.SoundID.DoorClosed, Terraria.ID.SoundID.DoorOpen, Terraria.ID.SoundID.DoubleJump, Terraria.ID.SoundID.Drip, Terraria.ID.SoundID.Drown, Terraria.ID.SoundID.DrumClosedHiHat, Terraria.ID.SoundID.DrumCymbal1, Terraria.ID.SoundID.DrumCymbal2, Terraria.ID.SoundID.DrumFloorTom, Terraria.ID.SoundID.DrumHiHat, Terraria.ID.SoundID.DrumKick, Terraria.ID.SoundID.DrumTamaSnare, Terraria.ID.SoundID.DrumTomHigh, Terraria.ID.SoundID.DrumTomLow, Terraria.ID.SoundID.DrumTomMid, Terraria.ID.SoundID.DSTFemaleHurt, Terraria.ID.SoundID.DSTMaleHurt, Terraria.ID.SoundID.Duck, Terraria.ID.SoundID.FemaleHit, Terraria.ID.SoundID.FillLegacyArrayedStylesMap(), Terraria.ID.SoundID.ForceRoar, Terraria.ID.SoundID.ForceRoarPitched, Terraria.ID.SoundID.Frog, Terraria.ID.SoundID.GlommerBounce, Terraria.ID.SoundID.Grab, Terraria.ID.SoundID.Grass, Terraria.ID.SoundID.GuitarAm, Terraria.ID.SoundID.GuitarBm, Terraria.ID.SoundID.GuitarC, Terraria.ID.SoundID.GuitarD, Terraria.ID.SoundID.GuitarEm, Terraria.ID.SoundID.GuitarG, Terraria.ID.SoundID.IndexByName, Terraria.ID.SoundID.Item1, Terraria.ID.SoundID.Item10, Terraria.ID.SoundID.Item100, Terraria.ID.SoundID.Item101, Terraria.ID.SoundID.Item102, Terraria.ID.SoundID.Item103, Terraria.ID.SoundID.Item104, Terraria.ID.SoundID.Item105, Terraria.ID.SoundID.Item106, Terraria.ID.SoundID.Item107, Terraria.ID.SoundID.Item108, Terraria.ID.SoundID.Item109, Terraria.ID.SoundID.Item11, Terraria.ID.SoundID.Item110, Terraria.ID.SoundID.Item111, Terraria.ID.SoundID.Item112, Terraria.ID.SoundID.Item113, Terraria.ID.SoundID.Item114, Terraria.ID.SoundID.Item115, Terraria.ID.SoundID.Item116, Terraria.ID.SoundID.Item117, Terraria.ID.SoundID.Item118, Terraria.ID.SoundID.Item119, Terraria.ID.SoundID.Item12, Terraria.ID.SoundID.Item120, Terraria.ID.SoundID.Item121, Terraria.ID.SoundID.Item122, Terraria.ID.SoundID.Item123, Terraria.ID.SoundID.Item124, Terraria.ID.SoundID.Item125, Terraria.ID.SoundID.Item126, Terraria.ID.SoundID.Item127, Terraria.ID.SoundID.Item128, Terraria.ID.SoundID.Item129, Terraria.ID.SoundID.Item13, Terraria.ID.SoundID.Item130, Terraria.ID.SoundID.Item131, Terraria.ID.SoundID.Item132, Terraria.ID.SoundID.Item133, Terraria.ID.SoundID.Item134, Terraria.ID.SoundID.Item135, Terraria.ID.SoundID.Item136, Terraria.ID.SoundID.Item137, Terraria.ID.SoundID.Item138, Terraria.ID.SoundID.Item139, Terraria.ID.SoundID.Item14, Terraria.ID.SoundID.Item140, Terraria.ID.SoundID.Item141, Terraria.ID.SoundID.Item142, Terraria.ID.SoundID.Item143, Terraria.ID.SoundID.Item144, Terraria.ID.SoundID.Item145, Terraria.ID.SoundID.Item146, Terraria.ID.SoundID.Item147, Terraria.ID.SoundID.Item148, Terraria.ID.SoundID.Item149, Terraria.ID.SoundID.Item15, Terraria.ID.SoundID.Item150, Terraria.ID.SoundID.Item151, Terraria.ID.SoundID.Item152, Terraria.ID.SoundID.Item153, Terraria.ID.SoundID.Item154, Terraria.ID.SoundID.Item155, Terraria.ID.SoundID.Item156, Terraria.ID.SoundID.Item157, Terraria.ID.SoundID.Item158, Terraria.ID.SoundID.Item159, Terraria.ID.SoundID.Item16, Terraria.ID.SoundID.Item160, Terraria.ID.SoundID.Item161, Terraria.ID.SoundID.Item162, Terraria.ID.SoundID.Item163, Terraria.ID.SoundID.Item164, Terraria.ID.SoundID.Item165, Terraria.ID.SoundID.Item166, Terraria.ID.SoundID.Item167, Terraria.ID.SoundID.Item168, Terraria.ID.SoundID.Item169, Terraria.ID.SoundID.Item17, Terraria.ID.SoundID.Item170, Terraria.ID.SoundID.Item171, Terraria.ID.SoundID.Item172, Terraria.ID.SoundID.Item173, Terraria.ID.SoundID.Item174, Terraria.ID.SoundID.Item175, Terraria.ID.SoundID.Item176, Terraria.ID.SoundID.Item177, Terraria.ID.SoundID.Item178, Terraria.ID.SoundID.Item18, Terraria.ID.SoundID.Item19, Terraria.ID.SoundID.Item2, Terraria.ID.SoundID.Item20, Terraria.ID.SoundID.Item21, Terraria.ID.SoundID.Item22, Terraria.ID.SoundID.Item23, Terraria.ID.SoundID.Item24, Terraria.ID.SoundID.Item25, Terraria.ID.SoundID.Item26, Terraria.ID.SoundID.Item27, Terraria.ID.SoundID.Item28, Terraria.ID.SoundID.Item29, Terraria.ID.SoundID.Item3, Terraria.ID.SoundID.Item30, Terraria.ID.SoundID.Item31, Terraria.ID.SoundID.Item32, Terraria.ID.SoundID.Item33, Terraria.ID.SoundID.Item34, Terraria.ID.SoundID.Item35, Terraria.ID.SoundID.Item36, Terraria.ID.SoundID.Item37, Terraria.ID.SoundID.Item38, Terraria.ID.SoundID.Item39, Terraria.ID.SoundID.Item4, Terraria.ID.SoundID.Item40, Terraria.ID.SoundID.Item41, Terraria.ID.SoundID.Item42, Terraria.ID.SoundID.Item43, Terraria.ID.SoundID.Item44, Terraria.ID.SoundID.Item45, Terraria.ID.SoundID.Item46, Terraria.ID.SoundID.Item47, Terraria.ID.SoundID.Item48, Terraria.ID.SoundID.Item49, Terraria.ID.SoundID.Item5, Terraria.ID.SoundID.Item50, Terraria.ID.SoundID.Item51, Terraria.ID.SoundID.Item52, Terraria.ID.SoundID.Item53, Terraria.ID.SoundID.Item54, Terraria.ID.SoundID.Item55, Terraria.ID.SoundID.Item56, Terraria.ID.SoundID.Item57, Terraria.ID.SoundID.Item58, Terraria.ID.SoundID.Item59, Terraria.ID.SoundID.Item6, Terraria.ID.SoundID.Item60, Terraria.ID.SoundID.Item61, Terraria.ID.SoundID.Item62, Terraria.ID.SoundID.Item63, Terraria.ID.SoundID.Item64, Terraria.ID.SoundID.Item65, Terraria.ID.SoundID.Item66, Terraria.ID.SoundID.Item67, Terraria.ID.SoundID.Item68, Terraria.ID.SoundID.Item69, Terraria.ID.SoundID.Item7, Terraria.ID.SoundID.Item70, Terraria.ID.SoundID.Item71, Terraria.ID.SoundID.Item72, Terraria.ID.SoundID.Item73, Terraria.ID.SoundID.Item74, Terraria.ID.SoundID.Item75, Terraria.ID.SoundID.Item76, Terraria.ID.SoundID.Item77, Terraria.ID.SoundID.Item78, Terraria.ID.SoundID.Item79, Terraria.ID.SoundID.Item8, Terraria.ID.SoundID.Item80, Terraria.ID.SoundID.Item81, Terraria.ID.SoundID.Item82, Terraria.ID.SoundID.Item83, Terraria.ID.SoundID.Item84, Terraria.ID.SoundID.Item85, Terraria.ID.SoundID.Item86, Terraria.ID.SoundID.Item87, Terraria.ID.SoundID.Item88, Terraria.ID.SoundID.Item89, Terraria.ID.SoundID.Item9, Terraria.ID.SoundID.Item90, Terraria.ID.SoundID.Item91, Terraria.ID.SoundID.Item92, Terraria.ID.SoundID.Item93, Terraria.ID.SoundID.Item94, Terraria.ID.SoundID.Item95, Terraria.ID.SoundID.Item96, Terraria.ID.SoundID.Item97, Terraria.ID.SoundID.Item98, Terraria.ID.SoundID.Item99, Terraria.ID.SoundID.SoundStyleDefaults.ItemDefaults, Terraria.ID.SoundID.ItemSound(), Terraria.ID.SoundID.ItemSoundCount, Terraria.ID.SoundID.JimsDrone, Terraria.ID.SoundID.Lavafall, Terraria.ID.SoundID.legacyArrayedStylesMapping, Terraria.ID.SoundID.LiquidsHoneyLava, Terraria.ID.SoundID.LiquidsHoneyWater, Terraria.ID.SoundID.LiquidsWaterLava, Terraria.ID.SoundID.LucyTheAxeTalk, Terraria.ID.SoundID.Macaw, Terraria.ID.SoundID.MaxMana, Terraria.ID.SoundID.Mech, Terraria.ID.SoundID.MenuClose, Terraria.ID.SoundID.MenuOpen, Terraria.ID.SoundID.MenuTick, Terraria.ID.SoundID.Meowmere, Terraria.ID.SoundID.MoonLord, Terraria.ID.SoundID.Mummy, Terraria.ID.SoundID.NPCDeath1, Terraria.ID.SoundID.NPCDeath10, Terraria.ID.SoundID.NPCDeath11, Terraria.ID.SoundID.NPCDeath12, Terraria.ID.SoundID.NPCDeath13, Terraria.ID.SoundID.NPCDeath14, Terraria.ID.SoundID.NPCDeath15, Terraria.ID.SoundID.NPCDeath16, Terraria.ID.SoundID.NPCDeath17, Terraria.ID.SoundID.NPCDeath18, Terraria.ID.SoundID.NPCDeath19, Terraria.ID.SoundID.NPCDeath2, Terraria.ID.SoundID.NPCDeath20, Terraria.ID.SoundID.NPCDeath21, Terraria.ID.SoundID.NPCDeath22, Terraria.ID.SoundID.NPCDeath23, Terraria.ID.SoundID.NPCDeath24, Terraria.ID.SoundID.NPCDeath25, Terraria.ID.SoundID.NPCDeath26, Terraria.ID.SoundID.NPCDeath27, Terraria.ID.SoundID.NPCDeath28, Terraria.ID.SoundID.NPCDeath29, Terraria.ID.SoundID.NPCDeath3, Terraria.ID.SoundID.NPCDeath30, Terraria.ID.SoundID.NPCDeath31, Terraria.ID.SoundID.NPCDeath32, Terraria.ID.SoundID.NPCDeath33, Terraria.ID.SoundID.NPCDeath34, Terraria.ID.SoundID.NPCDeath35, Terraria.ID.SoundID.NPCDeath36, Terraria.ID.SoundID.NPCDeath37, Terraria.ID.SoundID.NPCDeath38, Terraria.ID.SoundID.NPCDeath39, Terraria.ID.SoundID.NPCDeath4, Terraria.ID.SoundID.NPCDeath40, Terraria.ID.SoundID.NPCDeath41, Terraria.ID.SoundID.NPCDeath42, Terraria.ID.SoundID.NPCDeath43, Terraria.ID.SoundID.NPCDeath44, Terraria.ID.SoundID.NPCDeath45, Terraria.ID.SoundID.NPCDeath46, Terraria.ID.SoundID.NPCDeath47, Terraria.ID.SoundID.NPCDeath48, Terraria.ID.SoundID.NPCDeath49, Terraria.ID.SoundID.NPCDeath5, Terraria.ID.SoundID.NPCDeath50, Terraria.ID.SoundID.NPCDeath51, Terraria.ID.SoundID.NPCDeath52, Terraria.ID.SoundID.NPCDeath53, Terraria.ID.SoundID.NPCDeath54, Terraria.ID.SoundID.NPCDeath55, Terraria.ID.SoundID.NPCDeath56, Terraria.ID.SoundID.NPCDeath57, Terraria.ID.SoundID.NPCDeath58, Terraria.ID.SoundID.NPCDeath59, Terraria.ID.SoundID.NPCDeath6, Terraria.ID.SoundID.NPCDeath60, Terraria.ID.SoundID.NPCDeath61, Terraria.ID.SoundID.NPCDeath62, Terraria.ID.SoundID.NPCDeath63, Terraria.ID.SoundID.NPCDeath64, Terraria.ID.SoundID.NPCDeath65, Terraria.ID.SoundID.NPCDeath66, Terraria.ID.SoundID.NPCDeath7, Terraria.ID.SoundID.NPCDeath8, Terraria.ID.SoundID.NPCDeath9, Terraria.ID.SoundID.NPCDeathCount, Terraria.ID.SoundID.NPCDeathSound(), Terraria.ID.SoundID.NPCHit1, Terraria.ID.SoundID.NPCHit10, Terraria.ID.SoundID.NPCHit11, Terraria.ID.SoundID.NPCHit12, Terraria.ID.SoundID.NPCHit13, Terraria.ID.SoundID.NPCHit14, Terraria.ID.SoundID.NPCHit15, Terraria.ID.SoundID.NPCHit16, Terraria.ID.SoundID.NPCHit17, Terraria.ID.SoundID.NPCHit18, Terraria.ID.SoundID.NPCHit19, Terraria.ID.SoundID.NPCHit2, Terraria.ID.SoundID.NPCHit20, Terraria.ID.SoundID.NPCHit21, Terraria.ID.SoundID.NPCHit22, Terraria.ID.SoundID.NPCHit23, Terraria.ID.SoundID.NPCHit24, Terraria.ID.SoundID.NPCHit25, Terraria.ID.SoundID.NPCHit26, Terraria.ID.SoundID.NPCHit27, Terraria.ID.SoundID.NPCHit28, Terraria.ID.SoundID.NPCHit29, Terraria.ID.SoundID.NPCHit3, Terraria.ID.SoundID.NPCHit30, Terraria.ID.SoundID.NPCHit31, Terraria.ID.SoundID.NPCHit32, Terraria.ID.SoundID.NPCHit33, Terraria.ID.SoundID.NPCHit34, Terraria.ID.SoundID.NPCHit35, Terraria.ID.SoundID.NPCHit36, Terraria.ID.SoundID.NPCHit37, Terraria.ID.SoundID.NPCHit38, Terraria.ID.SoundID.NPCHit39, Terraria.ID.SoundID.NPCHit4, Terraria.ID.SoundID.NPCHit40, Terraria.ID.SoundID.NPCHit41, Terraria.ID.SoundID.NPCHit42, Terraria.ID.SoundID.NPCHit43, Terraria.ID.SoundID.NPCHit44, Terraria.ID.SoundID.NPCHit45, Terraria.ID.SoundID.NPCHit46, Terraria.ID.SoundID.NPCHit47, Terraria.ID.SoundID.NPCHit48, Terraria.ID.SoundID.NPCHit49, Terraria.ID.SoundID.NPCHit5, Terraria.ID.SoundID.NPCHit50, Terraria.ID.SoundID.NPCHit51, Terraria.ID.SoundID.NPCHit52, Terraria.ID.SoundID.NPCHit53, Terraria.ID.SoundID.NPCHit54, Terraria.ID.SoundID.NPCHit55, Terraria.ID.SoundID.NPCHit56, Terraria.ID.SoundID.NPCHit57, Terraria.ID.SoundID.NPCHit6, Terraria.ID.SoundID.NPCHit7, Terraria.ID.SoundID.NPCHit8, Terraria.ID.SoundID.NPCHit9, Terraria.ID.SoundID.NPCHitCount, Terraria.ID.SoundID.NPCHitSound(), Terraria.ID.SoundID.Owl, Terraria.ID.SoundID.Pixie, Terraria.ID.SoundID.PlayerHit, Terraria.ID.SoundID.PlayerKilled, Terraria.ID.SoundID.QueenSlime, Terraria.ID.SoundID.Research, Terraria.ID.SoundID.ResearchComplete, Terraria.ID.SoundID.Roar, Terraria.ID.SoundID.Run, Terraria.ID.SoundID.SandShark, Terraria.ID.SoundID.ScaryScream, Terraria.ID.SoundID.Seagull, Terraria.ID.SoundID.Shatter, Terraria.ID.SoundID.Shimmer1, Terraria.ID.SoundID.Shimmer2, Terraria.ID.SoundID.ShimmerWeak1, Terraria.ID.SoundID.ShimmerWeak2, Terraria.ID.SoundID.SoundByIndex, Terraria.ID.SoundID.SoundByName, Terraria.ID.SoundID.Splash, Terraria.ID.SoundID.SplashWeak, Terraria.ID.SoundID.Thunder, Terraria.ID.SoundID.Tink, Terraria.ID.SoundID.Toucan, Terraria.ID.SoundID.Unlock, Terraria.ID.SoundID.Waterfall, Terraria.Audio.SoundStyle.WithPitchVariance(), Terraria.Audio.SoundStyle.WithVolume(), Terraria.ID.SoundID.WormDig, Terraria.ID.SoundID.WormDigQuiet, Terraria.ID.SoundID.Zombie1, Terraria.ID.SoundID.Zombie10, Terraria.ID.SoundID.Zombie100, Terraria.ID.SoundID.Zombie101, Terraria.ID.SoundID.Zombie102, Terraria.ID.SoundID.Zombie103, Terraria.ID.SoundID.Zombie104, Terraria.ID.SoundID.Zombie105, Terraria.ID.SoundID.Zombie106, Terraria.ID.SoundID.Zombie107, Terraria.ID.SoundID.Zombie108, Terraria.ID.SoundID.Zombie109, Terraria.ID.SoundID.Zombie11, Terraria.ID.SoundID.Zombie110, Terraria.ID.SoundID.Zombie111, Terraria.ID.SoundID.Zombie112, Terraria.ID.SoundID.Zombie113, Terraria.ID.SoundID.Zombie114, Terraria.ID.SoundID.Zombie115, Terraria.ID.SoundID.Zombie116, Terraria.ID.SoundID.Zombie117, Terraria.ID.SoundID.Zombie118, Terraria.ID.SoundID.Zombie119, Terraria.ID.SoundID.Zombie12, Terraria.ID.SoundID.Zombie120, Terraria.ID.SoundID.Zombie121, Terraria.ID.SoundID.Zombie122, Terraria.ID.SoundID.Zombie123, Terraria.ID.SoundID.Zombie124, Terraria.ID.SoundID.Zombie125, Terraria.ID.SoundID.Zombie126, Terraria.ID.SoundID.Zombie127, Terraria.ID.SoundID.Zombie128, Terraria.ID.SoundID.Zombie129, Terraria.ID.SoundID.Zombie13, Terraria.ID.SoundID.Zombie130, Terraria.ID.SoundID.Zombie14, Terraria.ID.SoundID.Zombie15, Terraria.ID.SoundID.Zombie16, Terraria.ID.SoundID.Zombie17, Terraria.ID.SoundID.Zombie18, Terraria.ID.SoundID.Zombie19, Terraria.ID.SoundID.Zombie2, Terraria.ID.SoundID.Zombie20, Terraria.ID.SoundID.Zombie21, Terraria.ID.SoundID.Zombie22, Terraria.ID.SoundID.Zombie23, Terraria.ID.SoundID.Zombie24, Terraria.ID.SoundID.Zombie25, Terraria.ID.SoundID.Zombie26, Terraria.ID.SoundID.Zombie27, Terraria.ID.SoundID.Zombie28, Terraria.ID.SoundID.Zombie29, Terraria.ID.SoundID.Zombie3, Terraria.ID.SoundID.Zombie30, Terraria.ID.SoundID.Zombie31, Terraria.ID.SoundID.Zombie32, Terraria.ID.SoundID.Zombie33, Terraria.ID.SoundID.Zombie34, Terraria.ID.SoundID.Zombie35, Terraria.ID.SoundID.Zombie36, Terraria.ID.SoundID.Zombie37, Terraria.ID.SoundID.Zombie38, Terraria.ID.SoundID.Zombie39, Terraria.ID.SoundID.Zombie4, Terraria.ID.SoundID.Zombie40, Terraria.ID.SoundID.Zombie41, Terraria.ID.SoundID.Zombie42, Terraria.ID.SoundID.Zombie43, Terraria.ID.SoundID.Zombie44, Terraria.ID.SoundID.Zombie45, Terraria.ID.SoundID.Zombie46, Terraria.ID.SoundID.Zombie47, Terraria.ID.SoundID.Zombie48, Terraria.ID.SoundID.Zombie49, Terraria.ID.SoundID.Zombie5, Terraria.ID.SoundID.Zombie50, Terraria.ID.SoundID.Zombie51, Terraria.ID.SoundID.Zombie52, Terraria.ID.SoundID.Zombie53, Terraria.ID.SoundID.Zombie54, Terraria.ID.SoundID.Zombie55, Terraria.ID.SoundID.Zombie56, Terraria.ID.SoundID.Zombie57, Terraria.ID.SoundID.Zombie58, Terraria.ID.SoundID.Zombie59, Terraria.ID.SoundID.Zombie6, Terraria.ID.SoundID.Zombie60, Terraria.ID.SoundID.Zombie61, Terraria.ID.SoundID.Zombie62, Terraria.ID.SoundID.Zombie63, Terraria.ID.SoundID.Zombie64, Terraria.ID.SoundID.Zombie65, Terraria.ID.SoundID.Zombie66, Terraria.ID.SoundID.Zombie67, Terraria.ID.SoundID.Zombie68, Terraria.ID.SoundID.Zombie69, Terraria.ID.SoundID.Zombie7, Terraria.ID.SoundID.Zombie70, Terraria.ID.SoundID.Zombie71, Terraria.ID.SoundID.Zombie72, Terraria.ID.SoundID.Zombie73, Terraria.ID.SoundID.Zombie74, Terraria.ID.SoundID.Zombie75, Terraria.ID.SoundID.Zombie76, Terraria.ID.SoundID.Zombie77, Terraria.ID.SoundID.Zombie78, Terraria.ID.SoundID.Zombie79, Terraria.ID.SoundID.Zombie8, Terraria.ID.SoundID.Zombie80, Terraria.ID.SoundID.Zombie81, Terraria.ID.SoundID.Zombie82, Terraria.ID.SoundID.Zombie83, Terraria.ID.SoundID.Zombie84, Terraria.ID.SoundID.Zombie85, Terraria.ID.SoundID.Zombie86, Terraria.ID.SoundID.Zombie87, Terraria.ID.SoundID.Zombie88, Terraria.ID.SoundID.Zombie89, Terraria.ID.SoundID.Zombie9, Terraria.ID.SoundID.Zombie90, Terraria.ID.SoundID.Zombie91, Terraria.ID.SoundID.Zombie92, Terraria.ID.SoundID.Zombie93, Terraria.ID.SoundID.Zombie94, Terraria.ID.SoundID.Zombie95, Terraria.ID.SoundID.Zombie96, Terraria.ID.SoundID.Zombie97, Terraria.ID.SoundID.Zombie98, Terraria.ID.SoundID.Zombie99, Terraria.ID.SoundID.ZombieMoan, and Terraria.ID.SoundID.ZombieSound().