TModLoader: Terraria.Netplay.OpenPort
OpenPort()
static void Terraria.Netplay.OpenPort (int port) inline static private
    {
        if (!Main.dedServ)
        {
            return;
        }
        string localIPAddress = GetLocalIPAddress();
        if (_upnpnat == null)
        {
            _upnpnat = new UPnPNAT();
            _mappings = _upnpnat.StaticPortMappingCollection;
        }
        if (_mappings == null)
        {
            return;
        }
        bool flag = false;
        foreach (IStaticPortMapping mapping in _mappings)
        {
            if (mapping.InternalPort == port && mapping.InternalClient == localIPAddress && mapping.Protocol == "TCP")
            {
                flag = true;
            }
        }
        if (!flag)
        {
            _mappings.Add(port, "TCP", port, localIPAddress, bEnabled: true, "Terraria Server");
        }
    }
References Terraria.Netplay._mappings, Terraria.Netplay._upnpnat, NATUPNPLib.IStaticPortMappingCollection.Add(), Terraria.Main.dedServ, Terraria.Netplay.GetLocalIPAddress(), and NATUPNPLib.UPnPNAT.StaticPortMappingCollection.
Referenced by Terraria.Netplay.InitializeServer().