TModLoader: Terraria.Netplay.ClientLoopSetup
ClientLoopSetup()
static void Terraria.Netplay.ClientLoopSetup (RemoteAddress address) inline static private
Definition at line 493 of file Netplay.cs.
    {
        string friendlyName = address.GetFriendlyName();
        if (string.IsNullOrEmpty(friendlyName))
        {
            Utils.ShowFancyErrorMessage("Unable to find Steam Hosted Multiplayer server.", 0);
        }
        Logging.Terraria.InfoFormat("Connecting to {0}", (object)friendlyName);
        Connection.ResetSpecialFlags();
        ResetNetDiag();
        Main.ServerSideCharacter = false;
        if (Main.rand == null)
        {
            Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
        }
        Main.player[Main.myPlayer].hostile = false;
        Main.clientPlayer = Main.player[Main.myPlayer].clientClone();
        for (int i = 0; i < 255; i++)
        {
            if (i != Main.myPlayer)
            {
                Main.player[i] = new Player();
            }
        }
        Main.netMode = 1;
        Main.menuMode = 14;
        if (!Main.autoPass)
        {
            Main.statusText = Language.GetTextValue("Net.ConnectingTo", friendlyName);
        }
        Disconnect = false;
        Connection = new RemoteServer();
        Connection.ReadBuffer = new byte[65535];
    }
References Terraria.Main.autoPass, Terraria.Player.clientClone(), Terraria.Netplay.Connection, Terraria.Netplay.Disconnect, Terraria.Localization.Language.GetTextValue(), Terraria.Player.hostile, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.rand, Terraria.Netplay.ResetNetDiag(), Terraria.RemoteServer.ResetSpecialFlags(), Terraria.Utils.ShowFancyErrorMessage(), and Terraria.ModLoader.Logging.Terraria.
Referenced by Terraria.Netplay.SocialClientLoop(), and Terraria.Netplay.TcpClientLoop().