TModLoader: Terraria.Netplay.OnConnectionAccepted
OnConnectionAccepted()
static void Terraria.Netplay.OnConnectionAccepted (ISocket client) inline static private
Definition at line 217 of file Netplay.cs.
    {
        Logging.ServerConsoleLine(Language.GetTextValue("Net.ClientConnecting", client.GetRemoteAddress().GetFriendlyName()));
        int num = FindNextOpenClientSlot();
        if (num != -1)
        {
            Clients[num].Reset();
            Clients[num].Socket = client;
        }
        else
        {
            lock (fullBuffer)
            {
                KickClient(client, NetworkText.FromKey("CLI.ServerIsFull"));
            }
        }
        if (FindNextOpenClientSlot() == -1)
        {
            StopListening();
            IsListening = false;
        }
    }
References Terraria.Netplay.Clients, Terraria.Netplay.FindNextOpenClientSlot(), Terraria.Localization.NetworkText.FromKey(), Terraria.Netplay.fullBuffer, Terraria.Localization.Language.GetTextValue(), Terraria.Netplay.IsListening, Terraria.Netplay.KickClient(), Terraria.RemoteClient.Reset(), Terraria.ModLoader.Logging.ServerConsoleLine(), Terraria.RemoteClient.Socket, and Terraria.Netplay.StopListening().
Referenced by Terraria.Netplay.StartListening().