TModLoader: Terraria.ModLoader.Config.UI.ConfigElement.SetObject
SetObject()
virtual void Terraria.ModLoader.Config.UI.ConfigElement< T >.SetObject (object value) inline protected virtual inherited
Definition at line 140 of file ConfigElement.cs.
    {
        if (List != null)
        {
            List[Index] = value;
            Interface.modConfig.SetPendingChanges();
        }
        else if (MemberInfo.CanWrite)
        {
            MemberInfo.SetValue(Item, value);
            Interface.modConfig.SetPendingChanges();
        }
    }
References Terraria.ModLoader.Config.UI.PropertyFieldWrapper.CanWrite, Terraria.ModLoader.Config.UI.ConfigElement< T >.Index, Terraria.ModLoader.Config.UI.ConfigElement< T >.MemberInfo, Terraria.ModLoader.UI.Interface.modConfig, and Terraria.ModLoader.Config.UI.PropertyFieldWrapper.SetValue().
Referenced by Terraria.ModLoader.Config.UI.DictionaryElement.InitializeCollection(), Terraria.ModLoader.Config.UI.ListElement.InitializeCollection(), Terraria.ModLoader.Config.UI.SetElement.InitializeCollection(), Terraria.ModLoader.Config.UI.CollectionElement.NullCollection(), Terraria.ModLoader.Config.UI.IntInputElement.SetValue(), and Terraria.ModLoader.Config.UI.PrimitiveRangeElement< T >.SetValue().