TModLoader: Terraria.ModLoader.Config.UI.ConfigElement.DrawSelf
DrawSelf()
override void Terraria.ModLoader.Config.UI.ConfigElement< T >.DrawSelf (SpriteBatch spriteBatch) inline protected virtual inherited
Reimplemented from Terraria.UI.UIElement.
Reimplemented in Terraria.ModLoader.Config.UI.RangeElement.
    {
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        base.DrawSelf(spriteBatch);
        CalculatedStyle dimensions = GetDimensions();
        float settingsWidth = dimensions.Width + 1f;
        Vector2 val = new Vector2(dimensions.X, dimensions.Y);
        Vector2 baseScale = default(Vector2);
        ((Vector2)(ref baseScale))._002Ector(0.8f);
        Color color = (base.IsMouseHovering ? Color.White : Color.White);
        if (!MemberInfo.CanWrite)
        {
            color = Color.Gray;
        }
        Color panelColor = (base.IsMouseHovering ? backgroundColor : backgroundColor.MultiplyRGBA(new Color(180, 180, 180)));
        Vector2 position = val;
        DrawPanel2(spriteBatch, position, TextureAssets.SettingsPanel.Value, settingsWidth, dimensions.Height, panelColor);
        if (DrawLabel)
        {
            position.X += 8f;
            position.Y += 8f;
            string label = TextDisplayFunction();
            if (ReloadRequired && ValueChanged)
            {
                label = label + " - [c/FF0000:" + Language.GetTextValue("tModLoader.ModReloadRequired") + "]";
            }
            ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, label, position, color, 0f, Vector2.Zero, baseScale, settingsWidth);
        }
        if (base.IsMouseHovering && TooltipFunction != null)
        {
            string tooltip = TooltipFunction();
            if (ShowReloadRequiredTooltip)
            {
                tooltip += (string.IsNullOrEmpty(tooltip) ? "" : "\n");
                tooltip = tooltip + "[c/" + Color.Orange.Hex3() + ":" + Language.GetTextValue("tModLoader.ModReloadRequiredMemberTooltip") + "]";
            }
            UIModConfig.Tooltip = tooltip;
        }
    }
References Terraria.ModLoader.Config.UI.ConfigElement< T >.backgroundColor, Terraria.ModLoader.Config.UI.PropertyFieldWrapper.CanWrite, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.ModLoader.Config.UI.ConfigElement< T >.DrawLabel, Terraria.ModLoader.Config.UI.ConfigElement< T >.DrawPanel2(), Terraria.UI.UIElement.GetDimensions(), Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.FontAssets.ItemStack, Terraria.ModLoader.Config.UI.ConfigElement< T >.List, Terraria.ModLoader.Config.UI.ConfigElement< T >.MemberInfo, Terraria.ModLoader.Config.UI.ConfigElement< T >.ReloadRequired, Terraria.GameContent.TextureAssets.SettingsPanel, Terraria.ModLoader.Config.UI.ConfigElement< T >.ShowReloadRequiredTooltip, Terraria.ModLoader.Config.UI.ConfigElement< T >.TextDisplayFunction, Terraria.ModLoader.Config.UI.ConfigElement< T >.TooltipFunction, and Terraria.ModLoader.Config.UI.ConfigElement< T >.ValueChanged.