TModLoader: Terraria.ModLoader.Config.UI.ConfigElement.OnBind
OnBind()
virtual void Terraria.ModLoader.Config.UI.ConfigElement< T >.OnBind () inline virtual
Reimplemented in Terraria.ModLoader.Config.UI.BooleanElement, Terraria.ModLoader.Config.UI.CollectionElement, Terraria.ModLoader.Config.UI.ColorElement, Terraria.ModLoader.Config.UI.DefinitionElement< T >, Terraria.ModLoader.Config.UI.EnumElement, Terraria.ModLoader.Config.UI.IntInputElement, Terraria.ModLoader.Config.UI.ObjectElement, Terraria.ModLoader.Config.UI.PrimitiveRangeElement< T >, Terraria.ModLoader.Config.UI.RangeElement, Terraria.ModLoader.Config.UI.StringInputElement, Terraria.ModLoader.Config.UI.StringOptionElement, and Terraria.ModLoader.Config.UI.Vector2Element.
    {
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        LabelAttribute = ConfigManager.GetCustomAttributeFromMemberThenMemberType<LabelKeyAttribute>(MemberInfo, Item, List);
        Label = ConfigManager.GetLocalizedLabel(MemberInfo);
        TextDisplayFunction = () => Label;
        TooltipAttribute = ConfigManager.GetCustomAttributeFromMemberThenMemberType<TooltipKeyAttribute>(MemberInfo, Item, List);
        string tooltip = ConfigManager.GetLocalizedTooltip(MemberInfo);
        if (tooltip != null)
        {
            TooltipFunction = () => tooltip;
        }
        BackgroundColorAttribute = ConfigManager.GetCustomAttributeFromMemberThenMemberType<BackgroundColorAttribute>(MemberInfo, Item, List);
        if (BackgroundColorAttribute != null)
        {
            backgroundColor = BackgroundColorAttribute.Color;
        }
        RangeAttribute = ConfigManager.GetCustomAttributeFromMemberThenMemberType<RangeAttribute>(MemberInfo, Item, List);
        IncrementAttribute = ConfigManager.GetCustomAttributeFromMemberThenMemberType<IncrementAttribute>(MemberInfo, Item, List);
        NullAllowed = ConfigManager.GetCustomAttributeFromMemberThenMemberType<NullAllowedAttribute>(MemberInfo, Item, List) != null;
        JsonDefaultValueAttribute = ConfigManager.GetCustomAttributeFromMemberThenMemberType<JsonDefaultValueAttribute>(MemberInfo, Item, List);
        ShowReloadRequiredTooltip = ConfigManager.GetCustomAttributeFromMemberThenMemberType<ReloadRequiredAttribute>(MemberInfo, Item, List) != null;
        if (ShowReloadRequiredTooltip && List == null && Item is ModConfig modConfig)
        {
            ReloadRequired = true;
            ModConfig loadTimeConfig = ConfigManager.GetLoadTimeConfig(modConfig.Mod, modConfig.Name);
            OldValue = MemberInfo.GetValue(loadTimeConfig);
        }
    }
References Terraria.ModLoader.Config.UI.ConfigElement< T >.backgroundColor, Terraria.ModLoader.Config.BackgroundColorAttribute.Color, Terraria.ModLoader.Config.ConfigManager.GetLoadTimeConfig(), Terraria.ModLoader.Config.ConfigManager.GetLocalizedLabel(), Terraria.ModLoader.Config.ConfigManager.GetLocalizedTooltip(), Terraria.ModLoader.Config.UI.PropertyFieldWrapper.GetValue(), Terraria.ModLoader.Config.UI.ConfigElement< T >.Item, Terraria.ModLoader.Config.UI.ConfigElement< T >.Label, Terraria.ModLoader.Config.UI.ConfigElement< T >.List, Terraria.ModLoader.Config.UI.ConfigElement< T >.MemberInfo, Terraria.ModLoader.Config.UI.ConfigElement< T >.NullAllowed, Terraria.ModLoader.Config.UI.ConfigElement< T >.OldValue, Terraria.ModLoader.Config.UI.ConfigElement< T >.ReloadRequired, Terraria.ModLoader.Config.UI.ConfigElement< T >.ShowReloadRequiredTooltip, Terraria.ModLoader.Config.UI.ConfigElement< T >.TextDisplayFunction, and Terraria.ModLoader.Config.UI.ConfigElement< T >.TooltipFunction.