TModLoader: Terraria.HitTile.HitObject
HitObject()
int Terraria.HitTile.HitObject (int x, int y, int hitType) inline
Definition at line 142 of file HitTile.cs.
    {
        HitTileObject hitTileObject;
        for (int i = 0; i <= 500; i++)
        {
            int num = order[i];
            hitTileObject = data[num];
            if (hitTileObject.type == hitType)
            {
                if (hitTileObject.X == x && hitTileObject.Y == y)
                {
                    return num;
                }
            }
            else if (i != 0 && hitTileObject.type == 0)
            {
                break;
            }
        }
        hitTileObject = data[bufferLocation];
        hitTileObject.X = x;
        hitTileObject.Y = y;
        hitTileObject.type = hitType;
        return bufferLocation;
    }
References Terraria.HitTile.bufferLocation, Terraria.HitTile.data, and Terraria.HitTile.order.
Referenced by Terraria.Player.GetOtherPlayersPickTile(), Terraria.Player.HasEnoughPickPowerToHurtTile(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.Player.PickTile(), Terraria.Player.PickWall(), and Terraria.Player.PlaceThing_TryReplacingTiles().