TModLoader: Terraria.HitTile.AddDamage
AddDamage()
int Terraria.HitTile.AddDamage (int tileId, int damageAmount, bool updateAmount = true) inline
Definition at line 178 of file HitTile.cs.
    {
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        if (tileId < 0 || tileId > 500)
        {
            return 0;
        }
        if (tileId == bufferLocation && damageAmount == 0)
        {
            return 0;
        }
        HitTileObject hitTileObject = data[tileId];
        if (!updateAmount)
        {
            return hitTileObject.damage + damageAmount;
        }
        hitTileObject.damage += damageAmount;
        hitTileObject.timeToLive = 60;
        hitTileObject.animationTimeElapsed = 0;
        hitTileObject.animationDirection = (Main.rand.NextFloat() * ((float)Math.PI * 2f)).ToRotationVector2() * 2f;
        SortSlots(tileId);
        return hitTileObject.damage;
    }
References Terraria.HitTile.bufferLocation, Terraria.HitTile.data, Terraria.Main.rand, and Terraria.HitTile.SortSlots().
Referenced by Terraria.Player.GetOtherPlayersPickTile(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.Player.PickTile(), Terraria.Player.PickWall(), and Terraria.Player.PlaceThing_TryReplacingTiles().