TModLoader: Terraria.HitTile.DrawFreshAnimations
DrawFreshAnimations()
void Terraria.HitTile.DrawFreshAnimations (SpriteBatch spriteBatch) inline
Definition at line 327 of file HitTile.cs.
    {
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0392: Unknown result type (might be due to invalid IL or missing references)
        //IL_039f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_040c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0416: Unknown result type (might be due to invalid IL or missing references)
        //IL_041a: Unknown result type (might be due to invalid IL or missing references)
        //IL_041c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0440: Unknown result type (might be due to invalid IL or missing references)
        //IL_0442: Unknown result type (might be due to invalid IL or missing references)
        //IL_0449: Unknown result type (might be due to invalid IL or missing references)
        //IL_044d: Unknown result type (might be due to invalid IL or missing references)
        //IL_044f: Unknown result type (might be due to invalid IL or missing references)
        for (int i = 0; i < data.Length; i++)
        {
            data[i].animationTimeElapsed++;
        }
        if (!Main.SettingsEnabled_MinersWobble)
        {
            return;
        }
        int num = 1;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)Main.offScreenRange);
        if (Main.drawToScreen)
        {
            vector = Vector2.Zero;
        }
        vector = Vector2.Zero;
        bool flag = Main.ShouldShowInvisibleWalls();
        Rectangle value = default(Rectangle);
        Vector2 vector2 = default(Vector2);
        Vector2 vector3 = default(Vector2);
        for (int j = 0; j < data.Length; j++)
        {
            if (data[j].type != num)
            {
                continue;
            }
            int damage = data[j].damage;
            if (damage < 20)
            {
                continue;
            }
            int x = data[j].X;
            int y = data[j].Y;
            if (!WorldGen.InWorld(x, y))
            {
                continue;
            }
            Tile tile = Main.tile[x, y];
            bool flag2 = tile != null;
            if (flag2 && num == 1)
            {
                flag2 = flag2 && tile.active() && Main.tileSolid[Main.tile[x, y].type] && (!tile.invisibleBlock() || flag);
            }
            if (flag2 && num == 2)
            {
                flag2 = flag2 && tile.wall != 0 && (!tile.invisibleWall() || flag);
            }
            if (!flag2)
            {
                continue;
            }
            bool flag3 = false;
            bool flag4 = false;
            if (TileLoader.IsClosedDoor(tile))
            {
                flag3 = false;
            }
            else if (Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type])
            {
                flag3 = true;
            }
            else if (WorldGen.IsTreeType(tile.type))
            {
                flag4 = true;
                int num2 = tile.frameX / 22;
                int num3 = tile.frameY / 22;
                if (num3 < 9)
                {
                    flag3 = ((num2 != 1 && num2 != 2) || num3 < 6 || num3 > 8) && (num2 != 3 || num3 > 2) && (num2 != 4 || num3 < 3 || num3 > 5) && ((num2 != 5 || num3 < 6 || num3 > 8) ? true : false);
                }
            }
            else if (tile.type == 72)
            {
                flag4 = true;
                if (tile.frameX <= 34)
                {
                    flag3 = true;
                }
            }
            if (!flag3 || tile.slope() != 0 || tile.halfBrick())
            {
                continue;
            }
            int num4 = 0;
            if (damage >= 80)
            {
                num4 = 3;
            }
            else if (damage >= 60)
            {
                num4 = 2;
            }
            else if (damage >= 40)
            {
                num4 = 1;
            }
            else if (damage >= 20)
            {
                num4 = 0;
            }
            ((Rectangle)(ref value))._002Ector(data[j].crackStyle * 18, num4 * 18, 16, 16);
            ((Rectangle)(ref value)).Inflate(-2, -2);
            if (flag4)
            {
                value.X = (4 + data[j].crackStyle / 2) * 18;
            }
            int animationTimeElapsed = data[j].animationTimeElapsed;
            if (!((float)animationTimeElapsed >= 10f))
            {
                float num8 = (float)animationTimeElapsed / 10f;
                Color color = Lighting.GetColor(x, y);
                float rotation = 0f;
                Vector2 zero = Vector2.Zero;
                float num5 = 0.5f;
                float num6 = num8 % num5;
                num6 *= 1f / num5;
                if ((int)(num8 / num5) % 2 == 1)
                {
                    num6 = 1f - num6;
                }
                Tile tileSafely = Framing.GetTileSafely(x, y);
                Tile tile2 = tileSafely;
                Texture2D texture2D = Main.instance.TilePaintSystem.TryGetTileAndRequestIfNotReady(tileSafely.type, 0, tileSafely.color());
                if (texture2D != null)
                {
                    ((Vector2)(ref vector2))._002Ector(8f);
                    ((Vector2)(ref vector3))._002Ector(1f);
                    float num9 = num6 * 0.2f + 1f;
                    float num7 = 1f - num6;
                    num7 = 1f;
                    color *= num7 * num7 * 0.8f;
                    Vector2 scale = num9 * vector3;
                    Vector2 position = (new Vector2((float)(x * 16 - (int)Main.screenPosition.X), (float)(y * 16 - (int)Main.screenPosition.Y)) + vector + vector2 + zero).Floor();
                    spriteBatch.Draw(texture2D, position, (Rectangle?)new Rectangle((int)tile2.frameX, (int)tile2.frameY, 16, 16), color, rotation, vector2, scale, (SpriteEffects)0, 0f);
                    ((Color)(ref color)).A = 180;
                    spriteBatch.Draw(TextureAssets.TileCrack.Value, position, (Rectangle?)value, color, rotation, vector2, scale, (SpriteEffects)0, 0f);
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.HitTile.HitTileObject.animationTimeElapsed, Terraria.HitTile.HitTileObject.crackStyle, Terraria.HitTile.HitTileObject.damage, Terraria.HitTile.data, Terraria.Main.drawToScreen, Terraria.Tile.frameX, Terraria.Lighting.GetColor(), Terraria.Framing.GetTileSafely(), Terraria.Tile.halfBrick(), Terraria.Main.instance, Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.WorldGen.InWorld(), Terraria.ModLoader.TileLoader.IsClosedDoor(), Terraria.WorldGen.IsTreeType(), Terraria.Main.offScreenRange, Terraria.Main.screenPosition, Terraria.Main.SettingsEnabled_MinersWobble, Terraria.Main.ShouldShowInvisibleWalls(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.GameContent.TextureAssets.TileCrack, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Terraria.HitTile.HitTileObject.X, and Terraria.HitTile.HitTileObject.Y.