TModLoader: Terraria.Lang.GetBuffName
GetBuffName()
static string Terraria.Lang.GetBuffName (int id) inline static
Gets the display name of the provided buff type (T:Terraria.ID.BuffID) as a string.
Definition at line 199 of file Lang.cs.
    {
        return _buffNameCache[id].Value;
    }
References Terraria.Lang._buffNameCache, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.DrawInterface_Resources_Buffs(), Terraria.Main.DrawInventory(), and Terraria.ModLoader.Config.UI.BuffDefinitionElement.GetPassedOptionElements().