TModLoader: Terraria.Lang.AnglerQuestChat
AnglerQuestChat()
static string Terraria.Lang.AnglerQuestChat (bool turnIn = false) inline static
Definition at line 422 of file Lang.cs.
    {
        object obj = CreateDialogSubstitutionObject();
        if (turnIn)
        {
            return Language.SelectRandom(CreateDialogFilter("AnglerQuestText.TurnIn_", obj)).FormatWith(obj);
        }
        if (Main.anglerQuestFinished)
        {
            return Language.SelectRandom(CreateDialogFilter("AnglerQuestText.NoQuest_", obj)).FormatWith(obj);
        }
        int id = (Main.npcChatCornerItem = Main.anglerQuestItemNetIDs[Main.anglerQuest]);
        string modText = ItemLoader.AnglerChat(id);
        if (modText != null)
        {
            return modText;
        }
        return Language.GetTextValueWith("AnglerQuestText.Quest_" + ItemID.Search.GetName(id), obj);
    }
References Terraria.ModLoader.ItemLoader.AnglerChat(), Terraria.Main.anglerQuest, Terraria.Main.anglerQuestFinished, Terraria.Main.anglerQuestItemNetIDs, Terraria.Lang.CreateDialogFilter(), Terraria.Lang.CreateDialogSubstitutionObject(), Terraria.Localization.LocalizedText.FormatWith(), Terraria.Localization.Language.GetTextValueWith(), Terraria.ID.ItemID.Search, and Terraria.Localization.Language.SelectRandom().
Referenced by Terraria.Main.GUIChatDrawInner().