TModLoader: Terraria.ModLoader.ModAccessorySlot.ApplyEquipEffects
ApplyEquipEffects()
virtual void Terraria.ModLoader.ModAccessorySlot.ApplyEquipEffects () inline virtual inherited
Override to replace the vanilla effect behavior of the slot with your own. By default calls: Player.VanillaUpdateEquips(FunctionalItem), Player.ApplyEquipFunctional(FunctionalItem, ShowVisuals), Player.ApplyEquipVanity(VanityItem)
Definition at line 119 of file ModAccessorySlot.cs.
    {
        if (FunctionalItem.accessory)
        {
            Player.GrantPrefixBenefits(FunctionalItem);
        }
        Player.GrantArmorBenefits(FunctionalItem);
        Player.ApplyEquipFunctional(FunctionalItem, HideVisuals);
        Player.ApplyEquipVanity(VanityItem);
    }
References Terraria.Item.accessory, Terraria.Player.ApplyEquipFunctional(), Terraria.Player.ApplyEquipVanity(), Terraria.ModLoader.ModAccessorySlot.FunctionalItem, Terraria.Player.GrantArmorBenefits(), Terraria.Player.GrantPrefixBenefits(), Terraria.ModLoader.ModAccessorySlot.HideVisuals, and Terraria.ModLoader.ModAccessorySlot.VanityItem.
Referenced by Terraria.ModLoader.AccessorySlotLoader.CustomUpdateEquips().