TModLoader: Terraria.ModLoader.CommandLoader.GetCommand
GetCommand()
static bool Terraria.ModLoader.CommandLoader.GetCommand (CommandCaller caller, string name, out ModCommand mc) inline static package
Finds a command by name. Handles mod prefixing. Replies with error messages.
Parameters
caller Handles relaying the results of the command and narrows down the search by CommandType context
name The name of the command to retrieve
mc The found command, or null if an error was encountered.
Returns
True if a ModCommand was found, or an error message was replied. False if the command is unrecognized.
Definition at line 52 of file CommandLoader.cs.
    {
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        string modName = null;
        if (name.Contains(':'))
        {
            string[] array = name.Split(':');
            modName = array[0];
            name = array[1];
        }
        mc = null;
        if (!Commands.TryGetValue(name, out var cmdList))
        {
            return false;
        }
        cmdList = cmdList.Where((ModCommand c) => Matches(c.Type, caller.CommandType)).ToList();
        if (cmdList.Count == 0)
        {
            return false;
        }
        if (modName != null)
        {
            if (!ModLoader.TryGetMod(modName, out var mod))
            {
                caller.Reply("Unknown Mod: " + modName, Color.Red);
            }
            else
            {
                mc = cmdList.SingleOrDefault((ModCommand c) => c.Mod == mod);
                if (mc == null)
                {
                    caller.Reply("Mod: " + modName + " does not have a " + name + " command.", Color.Red);
                }
            }
        }
        else if (cmdList.Count > 1)
        {
            caller.Reply("Multiple definitions of command /" + name + ". Try:", Color.Red);
            foreach (ModCommand c2 in cmdList)
            {
                caller.Reply(c2.Mod.Name + ":" + c2.Command, Color.LawnGreen);
            }
        }
        else
        {
            mc = cmdList[0];
        }
        return true;
    }
References Terraria.ModLoader.CommandLoader.Matches(), Terraria.ModLoader.ModType< TEntity, TModType >.Mod, Terraria.ModLoader.ModLoader.TryGetMod(), and Terraria.ModLoader.ModCommand.Type.
Referenced by Terraria.ModLoader.Default.HelpCommand.Action(), and Terraria.ModLoader.CommandLoader.HandleCommand().