TModLoader: Terraria.ModLoader.ModLoader.Mods_Unload
Mods_Unload()
static void Terraria.ModLoader.ModLoader.Mods_Unload () inline static private
Definition at line 304 of file ModLoader.cs.
    {
        Interface.loadMods.SetLoadStage("tModLoader.MSUnloading", Mods.Length);
        WorldGen.clearWorld();
        ModContent.UnloadModContent();
        Mods = new Mod[0];
        modsByName.Clear();
        ModContent.Unload();
        MemoryTracking.Clear();
        Thread.MemoryBarrier();
        AssemblyManager.Unload();
    }
References Terraria.ModLoader.Core.MemoryTracking.Clear(), Terraria.WorldGen.clearWorld(), Terraria.ModLoader.UI.Interface.loadMods, Terraria.ModLoader.ModLoader.Mods, Terraria.ModLoader.ModLoader.modsByName, Terraria.ModLoader.UI.UILoadMods.SetLoadStage(), Terraria.ModLoader.Core.AssemblyManager.Unload(), Terraria.ModLoader.ModContent.Unload(), and Terraria.ModLoader.ModContent.UnloadModContent().
Referenced by Terraria.ModLoader.ModLoader.Unload().