TModLoader: Terraria.ModLoader.ModLoader.TryGetMod
TryGetMod()
static bool Terraria.ModLoader.ModLoader.TryGetMod (string name, out Mod result) inline static
Safely attempts to get the instance of the Mod with the specified name.
Returns
Whether or not the requested instance has been found.
Definition at line 114 of file ModLoader.cs.
    {
        return modsByName.TryGetValue(name, out result);
    }
References Terraria.ModLoader.ModLoader.modsByName.
Referenced by Terraria.ModLoader.Core.ModCompile.Build(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadMods(), Terraria.ModLoader.LocalizationLoader.ExtractLocalizationFiles(), Terraria.ModLoader.ModContent.FileExists(), Terraria.ModLoader.CommandLoader.GetCommand(), Terraria.ModLoader.ModContent.GetFileBytes(), Terraria.ModLoader.ModContent.HasAsset(), Terraria.GameContent.UI.States.WorkshopPublishInfoStateForMods.OnInitialize(), Terraria.ModLoader.UI.UIModItem.OnInitialize(), Terraria.ModLoader.UI.UIModSourceItem.PublishMod(), Terraria.ModLoader.ModNet.ReceiveMod(), Terraria.ModLoader.ModContent.Request< T >(), and Terraria.ModLoader.LocalizationLoader.UpdateLocalizationFilesForMod().