TModLoader: Terraria.ModLoader.ModLoader.Load
Load()
static void Terraria.ModLoader.ModLoader.Load (CancellationToken token = default(CancellationToken)) inline static private
    {
        if (isLoading)
        {
            throw new Exception("Load called twice");
        }
        isLoading = true;
        if (!Unload())
        {
            return;
        }
        LocalMod[] availableMods = ModOrganizer.FindMods(logDuplicates: true);
        try
        {
            List<Mod> list = AssemblyManager.InstantiateMods(ModOrganizer.SelectAndSortMods(availableMods, token), token);
            list.Insert(0, new ModLoaderMod());
            Mods = list.ToArray();
            Mod[] mods = Mods;
            foreach (Mod mod2 in mods)
            {
                modsByName[mod2.Name] = mod2;
            }
            ModContent.Load(token);
            if (OnSuccessfulLoad != null)
            {
                OnSuccessfulLoad();
            }
            else
            {
                Main.menuMode = 0;
            }
        }
        catch when (token.IsCancellationRequested)
        {
            skipLoad = true;
            OnSuccessfulLoad = (Action)Delegate.Combine(OnSuccessfulLoad, (Action)delegate
            {
                Main.menuMode = 10000;
            });
            isLoading = false;
            Load();
        }
        catch (Exception e)
        {
            List<string> responsibleMods = new List<string>();
            if (e.Data.Contains("mod"))
            {
                responsibleMods.Add((string)e.Data["mod"]);
            }
            if (e.Data.Contains("mods"))
            {
                responsibleMods.AddRange((IEnumerable<string>)e.Data["mods"]);
            }
            responsibleMods.Remove("ModLoader");
            if (responsibleMods.Count == 0 && AssemblyManager.FirstModInStackTrace(new StackTrace(e), out var stackMod))
            {
                responsibleMods.Add(stackMod);
            }
            string msg = Language.GetTextValue("tModLoader.LoadError", string.Join(", ", responsibleMods));
            if (responsibleMods.Count == 1)
            {
                LocalMod mod = availableMods.FirstOrDefault((LocalMod m) => m.Name == responsibleMods[0]);
                if (mod != null)
                {
                    msg += $" v{mod.properties.version}";
                }
                if (mod != null && mod.tModLoaderVersion.MajorMinorBuild() != BuildInfo.tMLVersion.MajorMinorBuild())
                {
                    msg = msg + "\n" + Language.GetTextValue("tModLoader.LoadErrorVersionMessage", mod.tModLoaderVersion, versionedName);
                }
                else if (mod != null)
                {
                    SteamedWraps.QueueForceValidateSteamInstall();
                }
                if (e is JITException)
                {
                    msg = msg + "\nThe mod will need to be updated to match the current tModLoader version, or may be incompatible with the version of some of your other mods. Click the '" + Language.GetTextValue("tModLoader.OpenWebHelp") + "' button to learn more.";
                }
            }
            msg = ((responsibleMods.Count <= 0) ? (msg + "\n" + Language.GetTextValue("tModLoader.LoadErrorCulpritUnknown")) : (msg + "\n" + Language.GetTextValue("tModLoader.LoadErrorDisabled")));
            if (e is ReflectionTypeLoadException reflectionTypeLoadException)
            {
                msg = msg + "\n\n" + string.Join("\n", reflectionTypeLoadException.LoaderExceptions.Select((Exception x) => x.Message));
            }
            if (e.Data.Contains("contentType") && e.Data["contentType"] is Type contentType)
            {
                msg = msg + "\n" + Language.GetTextValue("tModLoader.LoadErrorContentType", contentType.FullName);
            }
            Logging.tML.Error((object)msg, e);
            foreach (string item in responsibleMods)
            {
                DisableMod(item);
            }
            isLoading = false;
            DisplayLoadError(msg, e, e.Data.Contains("fatal"), responsibleMods.Count == 0);
        }
        finally
        {
            isLoading = false;
            OnSuccessfulLoad = null;
            skipLoad = false;
            ModNet.NetReloadActive = false;
        }
    }
References Terraria.ModLoader.ModLoader.DisableMod(), Terraria.ModLoader.ModLoader.DisplayLoadError(), Terraria.ModLoader.Core.ModOrganizer.FindMods(), Terraria.ModLoader.Core.AssemblyManager.FirstModInStackTrace(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.Core.AssemblyManager.InstantiateMods(), Terraria.ModLoader.ModLoader.isLoading, Terraria.ModLoader.ModContent.Load(), Terraria.ModLoader.ModLoader.Load(), Terraria.ModLoader.ModLoader.Mods, Terraria.ModLoader.ModLoader.modsByName, Terraria.ModLoader.ModLoader.OnSuccessfulLoad, Terraria.Social.Steam.SteamedWraps.QueueForceValidateSteamInstall(), Terraria.ModLoader.Core.ModOrganizer.SelectAndSortMods(), Terraria.ModLoader.ModLoader.skipLoad, Terraria.ModLoader.Logging.tML, Terraria.ModLoader.BuildInfo.tMLVersion, Terraria.ModLoader.Core.LocalMod.tModLoaderVersion, Terraria.ModLoader.ModLoader.Unload(), and Terraria.ModLoader.ModLoader.versionedName.
Referenced by Terraria.ModLoader.ModLoader.BeginLoad(), Terraria.ModLoader.ModLoader.Load(), and Terraria.ModLoader.ModLoader.Reload().