TModLoader: Terraria.ModLoader.ModLoader.Reload
Reload()
static void Terraria.ModLoader.ModLoader.Reload () inline static package
    {
        if (Main.dedServ)
        {
            Load();
        }
        else
        {
            Main.menuMode = 10002;
        }
    }
References Terraria.Main.dedServ, and Terraria.ModLoader.ModLoader.Load().
Referenced by Terraria.Main.DedServ(), Terraria.ModLoader.ModLoader.DisplayLoadError(), Terraria.ModLoader.UI.UIModPackItem.EnableList(), Terraria.ModLoader.UI.Interface.ModLoaderMenus(), Terraria.ModLoader.ModNet.OnModsDownloaded(), Terraria.GameContent.UI.Elements.UIWorldListItem.PlayGame(), Terraria.ModLoader.UI.UIMods.ReloadMods(), Terraria.ModLoader.UI.UIModPackItem.RemoveModPackLocal(), and Terraria.ModLoader.UI.UIModPackItem.UpdateModPack().