TModLoader: Terraria.ModLoader.ModLoader.DisplayLoadError
DisplayLoadError()
static void Terraria.ModLoader.ModLoader.DisplayLoadError (string msg, Exception e, bool fatal, bool continueIsRetry = false) inline static private
    {
        msg = msg + "\n\n" + (e.Data.Contains("hideStackTrace") ? e.Message : e.ToString());
        if (Main.dedServ)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(msg);
            Console.ResetColor();
            if (fatal)
            {
                Console.WriteLine("Press any key to exit...");
                Console.ReadKey();
                Environment.Exit(-1);
            }
            else
            {
                Reload();
            }
        }
        else
        {
            Interface.errorMessage.Show(msg, fatal ? (-1) : 10006, null, e.HelpLink, continueIsRetry, !fatal);
        }
    }
References Terraria.ModLoader.Console, Terraria.Main.dedServ, Terraria.ModLoader.Environment, Terraria.ModLoader.UI.Interface.errorMessage, Terraria.ModLoader.ModLoader.Reload(), and Terraria.ModLoader.UI.UIErrorMessage.Show().
Referenced by Terraria.ModLoader.ModLoader.Load(), and Terraria.ModLoader.ModLoader.Unload().