TModLoader: Terraria.GameContent.TeleportPylonsSystem.UpdatePylonsListAndBroadcastChanges
UpdatePylonsListAndBroadcastChanges()
void Terraria.GameContent.TeleportPylonsSystem.UpdatePylonsListAndBroadcastChanges () inline private
    {
        Utils.Swap(ref _pylons, ref _pylonsOld);
        _pylons.Clear();
        foreach (TileEntity value in TileEntity.ByPosition.Values)
        {
            if (!(value is IPylonTileEntity))
            {
                continue;
            }
            TeleportPylonInfo teleportPylonInfo = default(TeleportPylonInfo);
            teleportPylonInfo.PositionInTiles = value.Position;
            if (value is TETeleportationPylon vanillaPylon && vanillaPylon.TryGetPylonType(out var vanillaType))
            {
                teleportPylonInfo.TypeOfPylon = vanillaType;
            }
            else
            {
                if (!TEModdedPylon.GetModPylonFromCoords(value.Position.X, value.Position.Y, out var modPylon))
                {
                    continue;
                }
                teleportPylonInfo.TypeOfPylon = modPylon.PylonType;
            }
            TeleportPylonInfo item = teleportPylonInfo;
            _pylons.Add(item);
        }
        IEnumerable<TeleportPylonInfo> enumerable = _pylonsOld.Except(_pylons);
        foreach (TeleportPylonInfo item2 in _pylons.Except(_pylonsOld))
        {
            NetManager.Instance.BroadcastOrLoopback(NetTeleportPylonModule.SerializePylonWasAddedOrRemoved(item2, NetTeleportPylonModule.SubPacketType.PylonWasAdded));
        }
        foreach (TeleportPylonInfo item3 in enumerable)
        {
            NetManager.Instance.BroadcastOrLoopback(NetTeleportPylonModule.SerializePylonWasAddedOrRemoved(item3, NetTeleportPylonModule.SubPacketType.PylonWasRemoved));
        }
    }
References Terraria.GameContent.TeleportPylonsSystem._pylons, Terraria.GameContent.TeleportPylonsSystem._pylonsOld, Terraria.DataStructures.TileEntity.ByPosition, Terraria.ModLoader.Default.TEModdedPylon.GetModPylonFromCoords(), Terraria.Net.NetManager.Instance, Terraria.DataStructures.TileEntity.Position, Terraria.GameContent.NetModules.NetTeleportPylonModule.SerializePylonWasAddedOrRemoved(), Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.GameContent.TeleportPylonsSystem.RequestImmediateUpdate(), and Terraria.GameContent.TeleportPylonsSystem.Update().