TModLoader: Terraria.GameContent.TeleportPylonsSystem.SpawnInWorldDust
SpawnInWorldDust()
static void Terraria.GameContent.TeleportPylonsSystem.SpawnInWorldDust (int tileStyle, Rectangle dustBox) inline static
Definition at line 416 of file TeleportPylonsSystem.cs.
    {
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        //IL_014b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        float r = 1f;
        float g = 1f;
        float b = 1f;
        switch ((byte)tileStyle)
        {
        case 0:
            r = 0.05f;
            g = 0.8f;
            b = 0.3f;
            break;
        case 1:
            r = 0.7f;
            g = 0.8f;
            b = 0.05f;
            break;
        case 2:
            r = 0.5f;
            g = 0.3f;
            b = 0.7f;
            break;
        case 3:
            r = 0.4f;
            g = 0.4f;
            b = 0.6f;
            break;
        case 4:
            r = 0.2f;
            g = 0.2f;
            b = 0.95f;
            break;
        case 5:
            r = 0.85f;
            g = 0.45f;
            b = 0.1f;
            break;
        case 6:
            r = 1f;
            g = 1f;
            b = 1.2f;
            break;
        case 7:
            r = 0.4f;
            g = 0.7f;
            b = 1.2f;
            break;
        case 8:
            r = 0.7f;
            g = 0.7f;
            b = 0.7f;
            break;
        }
        int num = Dust.NewDust(dustBox.TopLeft(), dustBox.Width, dustBox.Height, 43, 0f, 0f, 254, new Color(r, g, b, 1f), 0.5f);
        Dust obj = Main.dust[num];
        obj.velocity *= 0.1f;
        Main.dust[num].velocity.Y -= 0.2f;
    }
References Terraria.Main.dust, and Terraria.Dust.NewDust().
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.Main.TeleportEffect(), and Terraria.Player.UpdateTeleportVisuals().