TModLoader: Terraria.GameContent.TeleportPylonsSystem.DoesPositionHaveEnoughNPCs
DoesPositionHaveEnoughNPCs()
static bool Terraria.GameContent.TeleportPylonsSystem.DoesPositionHaveEnoughNPCs (int necessaryNPCCount, Point16 centerPoint) inline static
Definition at line 283 of file TeleportPylonsSystem.cs.
    {
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        if (necessaryNPCCount <= 0)
        {
            return true;
        }
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector(centerPoint.X - Main.buffScanAreaWidth / 2, centerPoint.Y - Main.buffScanAreaHeight / 2, Main.buffScanAreaWidth, Main.buffScanAreaHeight);
        int num = necessaryNPCCount;
        Vector2 value2 = default(Vector2);
        for (int i = 0; i < 200; i++)
        {
            NPC nPC = Main.npc[i];
            if (!nPC.active || !nPC.isLikeATownNPC || nPC.homeless || !((Rectangle)(ref rectangle)).Contains(nPC.homeTileX, nPC.homeTileY))
            {
                continue;
            }
            Vector2 val = new Vector2((float)nPC.homeTileX, (float)nPC.homeTileY);
            ((Vector2)(ref value2))._002Ector(nPC.Center.X / 16f, nPC.Center.Y / 16f);
            if (Vector2.Distance(val, value2) < 100f)
            {
                num--;
                if (num == 0)
                {
                    return true;
                }
            }
        }
        return false;
    }
References Terraria.Main.buffScanAreaHeight, Terraria.Main.buffScanAreaWidth, and Terraria.Main.npc.
Referenced by Terraria.Condition(), Terraria.GameContent.TeleportPylonsSystem.DoesPylonHaveEnoughNPCsAroundIt(), Terraria.ModLoader.ModPylon.ValidTeleportCheck_NPCCount(), and Terraria.Chest.VanillaSetupShop().