TModLoader: Terraria.GameContent.TeleportPylonsSystem.DoesPylonAcceptTeleportation
DoesPylonAcceptTeleportation()
bool Terraria.GameContent.TeleportPylonsSystem.DoesPylonAcceptTeleportation (TeleportPylonInfo info, Player player) inline private
Definition at line 323 of file TeleportPylonsSystem.cs.
    {
        if (Main.netMode != 2 && Main.DroneCameraTracker != null && Main.DroneCameraTracker.IsInUse())
        {
            return false;
        }
        bool? flag5 = PylonLoader.ValidTeleportCheck_PreBiomeRequirements(info, _sceneMetrics);
        if (flag5.HasValue)
        {
            return flag5.GetValueOrDefault();
        }
        ModPylon pylon = info.ModPylon;
        if (pylon != null)
        {
            return pylon.ValidTeleportCheck_BiomeRequirements(info, _sceneMetrics);
        }
        switch (info.TypeOfPylon)
        {
        case TeleportPylonType.SurfacePurity:
        {
            bool flag = (double)info.PositionInTiles.Y <= Main.worldSurface;
            if (Main.remixWorld)
            {
                flag = (double)info.PositionInTiles.Y > Main.rockLayer && info.PositionInTiles.Y < Main.maxTilesY - 350;
            }
            bool flag2 = info.PositionInTiles.X >= Main.maxTilesX - 380 || info.PositionInTiles.X <= 380;
            if (!flag || flag2)
            {
                return false;
            }
            if (_sceneMetrics.EnoughTilesForJungle || _sceneMetrics.EnoughTilesForSnow || _sceneMetrics.EnoughTilesForDesert || _sceneMetrics.EnoughTilesForGlowingMushroom || _sceneMetrics.EnoughTilesForHallow || _sceneMetrics.EnoughTilesForCrimson || _sceneMetrics.EnoughTilesForCorruption)
            {
                return false;
            }
            return true;
        }
        case TeleportPylonType.Jungle:
            return _sceneMetrics.EnoughTilesForJungle;
        case TeleportPylonType.Snow:
            return _sceneMetrics.EnoughTilesForSnow;
        case TeleportPylonType.Desert:
            return _sceneMetrics.EnoughTilesForDesert;
        case TeleportPylonType.Beach:
        {
            bool flag3 = (double)info.PositionInTiles.Y <= Main.worldSurface && (double)info.PositionInTiles.Y > Main.worldSurface * 0.3499999940395355;
            bool flag4 = info.PositionInTiles.X >= Main.maxTilesX - 380 || info.PositionInTiles.X <= 380;
            if (Main.remixWorld)
            {
                flag3 |= (double)info.PositionInTiles.Y > Main.rockLayer && info.PositionInTiles.Y < Main.maxTilesY - 350;
                flag4 |= (double)info.PositionInTiles.X < (double)Main.maxTilesX * 0.43 || (double)info.PositionInTiles.X > (double)Main.maxTilesX * 0.57;
            }
            return flag4 && flag3;
        }
        case TeleportPylonType.GlowingMushroom:
            if (Main.remixWorld && info.PositionInTiles.Y >= Main.maxTilesY - 200)
            {
                return false;
            }
            return _sceneMetrics.EnoughTilesForGlowingMushroom;
        case TeleportPylonType.Hallow:
            return _sceneMetrics.EnoughTilesForHallow;
        case TeleportPylonType.Underground:
            return (double)info.PositionInTiles.Y >= Main.worldSurface;
        case TeleportPylonType.Victory:
            return true;
        default:
            return true;
        }
    }
References Terraria.GameContent.TeleportPylonsSystem._sceneMetrics, Terraria.Main.DroneCameraTracker, Terraria.SceneMetrics.EnoughTilesForCorruption, Terraria.SceneMetrics.EnoughTilesForCrimson, Terraria.SceneMetrics.EnoughTilesForDesert, Terraria.SceneMetrics.EnoughTilesForGlowingMushroom, Terraria.SceneMetrics.EnoughTilesForHallow, Terraria.SceneMetrics.EnoughTilesForJungle, Terraria.SceneMetrics.EnoughTilesForSnow, Terraria.DataStructures.DroneCameraTracker.IsInUse(), Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.ModLoader.PylonLoader.ValidTeleportCheck_PreBiomeRequirements(), and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.TeleportPylonsSystem.HandleTeleportRequest().