TModLoader: Terraria.GameContent.TeleportPylonsSystem.HandleTeleportRequest
HandleTeleportRequest()
void Terraria.GameContent.TeleportPylonsSystem.HandleTeleportRequest (TeleportPylonInfo info, int playerIndex) inline
    {
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_035f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0302: Unknown result type (might be due to invalid IL or missing references)
        //IL_0316: Unknown result type (might be due to invalid IL or missing references)
        //IL_032e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0335: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[playerIndex];
        string key = null;
        bool flag = true;
        if (flag)
        {
            flag &= IsPlayerNearAPylon(player);
            if (!flag)
            {
                key = "Net.CannotTeleportToPylonBecausePlayerIsNotNearAPylon";
            }
        }
        if (flag)
        {
            int necessaryNPCCount = HowManyNPCsDoesPylonNeed(info, player);
            flag &= DoesPylonHaveEnoughNPCsAroundIt(info, necessaryNPCCount);
            if (!flag)
            {
                key = "Net.CannotTeleportToPylonBecauseNotEnoughNPCs";
            }
        }
        if (flag)
        {
            flag &= !NPC.AnyDanger(quickBossNPCCheck: false, ignorePillarsAndMoonlordCountdown: true);
            bool? flag3 = PylonLoader.ValidTeleportCheck_PreAnyDanger(info);
            int num3;
            if (!flag3.HasValue)
            {
                num3 = ((info.ModPylon?.ValidTeleportCheck_AnyDanger(info) ?? flag) ? 1 : 0);
            }
            else
            {
                bool value = flag3.GetValueOrDefault();
                num3 = (value ? 1 : 0);
            }
            flag = (byte)num3 != 0;
            if (!flag)
            {
                key = "Net.CannotTeleportToPylonBecauseThereIsDanger";
            }
        }
        if (flag)
        {
            if (!NPC.downedPlantBoss && (double)info.PositionInTiles.Y > Main.worldSurface && Framing.GetTileSafely(info.PositionInTiles.X, info.PositionInTiles.Y).wall == 87)
            {
                flag = false;
            }
            if (!flag)
            {
                key = "Net.CannotTeleportToPylonBecauseAccessingLihzahrdTempleEarly";
            }
        }
        if (flag)
        {
            _sceneMetrics.ScanAndExportToMain(new SceneMetricsScanSettings
            {
                VisualScanArea = null,
                BiomeScanCenterPositionInWorld = info.PositionInTiles.ToWorldCoordinates(),
                ScanOreFinderData = false
            });
            flag = DoesPylonAcceptTeleportation(info, player);
            if (!flag)
            {
                key = "Net.CannotTeleportToPylonBecauseNotMeetingBiomeRequirements";
            }
        }
        info.ModPylon?.ValidTeleportCheck_DestinationPostCheck(info, ref flag, ref key);
        TeleportPylonInfo nearbyInfo = default(TeleportPylonInfo);
        bool flag2 = false;
        int num = 0;
        for (int i = 0; i < _pylons.Count; i++)
        {
            TeleportPylonInfo info2 = _pylons[i];
            if (!player.InInteractionRange(info2.PositionInTiles.X, info2.PositionInTiles.Y, TileReachCheckSettings.Pylons))
            {
                continue;
            }
            nearbyInfo = info2;
            if (num < 1)
            {
                num = 1;
            }
            int necessaryNPCCount2 = HowManyNPCsDoesPylonNeed(info2, player);
            if (DoesPylonHaveEnoughNPCsAroundIt(info2, necessaryNPCCount2))
            {
                if (num < 2)
                {
                    num = 2;
                }
                _sceneMetrics.ScanAndExportToMain(new SceneMetricsScanSettings
                {
                    VisualScanArea = null,
                    BiomeScanCenterPositionInWorld = info2.PositionInTiles.ToWorldCoordinates(),
                    ScanOreFinderData = false
                });
                if (DoesPylonAcceptTeleportation(info2, player))
                {
                    flag2 = true;
                    break;
                }
            }
        }
        if (!flag2)
        {
            key = num switch
            {
                1 => "Net.CannotTeleportToPylonBecauseNotEnoughNPCsAtCurrentPylon",
                2 => "Net.CannotTeleportToPylonBecauseNotMeetingBiomeRequirements",
                _ => "Net.CannotTeleportToPylonBecausePlayerIsNotNearAPylon",
            };
        }
        nearbyInfo.ModPylon?.ValidTeleportCheck_NearbyPostCheck(nearbyInfo, ref flag, ref flag2, ref key);
        PylonLoader.PostValidTeleportCheck(info, nearbyInfo, ref flag, ref flag2, ref key);
        if (flag && flag2)
        {
            Vector2 newPos = info.PositionInTiles.ToWorldCoordinates() - new Vector2(0f, (float)player.HeightOffsetBoost);
            info.ModPylon?.ModifyTeleportationPosition(info, ref newPos);
            int num2 = 9;
            int typeOfPylon = (int)info.TypeOfPylon;
            int number = 0;
            player.Teleport(newPos, num2, typeOfPylon);
            player.velocity = Vector2.Zero;
            if (Main.netMode == 2)
            {
                RemoteClient.CheckSection(player.whoAmI, player.position);
                NetMessage.SendData(65, -1, -1, null, 0, player.whoAmI, newPos.X, newPos.Y, num2, number, typeOfPylon);
            }
        }
        else
        {
            ChatHelper.SendChatMessageToClient(NetworkText.FromKey(key), new Color(255, 240, 20), playerIndex);
        }
    }
References Terraria.GameContent.TeleportPylonsSystem._pylons, Terraria.GameContent.TeleportPylonsSystem._sceneMetrics, Terraria.NPC.AnyDanger(), Terraria.RemoteClient.CheckSection(), Terraria.GameContent.TeleportPylonsSystem.DoesPylonAcceptTeleportation(), Terraria.GameContent.TeleportPylonsSystem.DoesPylonHaveEnoughNPCsAroundIt(), Terraria.NPC.downedPlantBoss, Terraria.Localization.NetworkText.FromKey(), Terraria.Framing.GetTileSafely(), Terraria.Player.HeightOffsetBoost, Terraria.GameContent.TeleportPylonsSystem.HowManyNPCsDoesPylonNeed(), Terraria.Player.InInteractionRange(), Terraria.GameContent.TeleportPylonsSystem.IsPlayerNearAPylon(), Terraria.Main.netMode, Terraria.Main.player, Terraria.Entity.position, Terraria.ModLoader.PylonLoader.PostValidTeleportCheck(), Terraria.DataStructures.TileReachCheckSettings.Pylons, Terraria.SceneMetrics.ScanAndExportToMain(), Terraria.Chat.ChatHelper.SendChatMessageToClient(), Terraria.NetMessage.SendData(), Terraria.Player.Teleport(), Terraria.ModLoader.PylonLoader.ValidTeleportCheck_PreAnyDanger(), and Terraria.Entity.whoAmI.