TModLoader: Terraria.Gore.GetAlpha
GetAlpha()
Color Terraria.Gore.GetAlpha (Color newColor) inline
    {
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        Color? val = ModGore?.GetAlpha(this, newColor);
        if (val.HasValue)
        {
            return val.GetValueOrDefault();
        }
        float num = (float)(255 - alpha) / 255f;
        int r;
        int g;
        int b;
        if (type == 16 || type == 17)
        {
            r = ((Color)(ref newColor)).R;
            g = ((Color)(ref newColor)).G;
            b = ((Color)(ref newColor)).B;
        }
        else
        {
            if (type == 716)
            {
                return new Color(255, 255, 255, 200);
            }
            if (type >= 570 && type <= 572)
            {
                byte b2 = (byte)(255 - alpha);
                return new Color((int)b2, (int)b2, (int)b2, b2 / 2);
            }
            if (type == 331)
            {
                return new Color(255, 255, 255, 50);
            }
            if (type == 1225)
            {
                return new Color(num, num, num, num);
            }
            r = (int)((float)(int)((Color)(ref newColor)).R * num);
            g = (int)((float)(int)((Color)(ref newColor)).G * num);
            b = (int)((float)(int)((Color)(ref newColor)).B * num);
        }
        int num2 = ((Color)(ref newColor)).A - alpha;
        if (num2 < 0)
        {
            num2 = 0;
        }
        if (num2 > 255)
        {
            num2 = 255;
        }
        if (type >= 1202 && type <= 1204)
        {
            return new Color(r, g, b, (num2 < 20) ? num2 : 20);
        }
        return new Color(r, g, b, num2);
    }
References Terraria.Gore.alpha, Terraria.ModLoader.ModGore.GetAlpha(), and Terraria.Gore.type.
Referenced by Terraria.Main.DrawGore(), and Terraria.Main.DrawGoreBehind().