TModLoader: Terraria.Gore.Gore_UpdateLeaf
Gore_UpdateLeaf()
void Terraria.Gore.Gore_UpdateLeaf () inline private
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_0347: Unknown result type (might be due to invalid IL or missing references)
        //IL_035a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0360: Unknown result type (might be due to invalid IL or missing references)
        //IL_0362: Unknown result type (might be due to invalid IL or missing references)
        //IL_0372: Unknown result type (might be due to invalid IL or missing references)
        //IL_0385: Unknown result type (might be due to invalid IL or missing references)
        //IL_038b: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03df: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0403: Unknown result type (might be due to invalid IL or missing references)
        //IL_0415: Unknown result type (might be due to invalid IL or missing references)
        //IL_0423: Unknown result type (might be due to invalid IL or missing references)
        //IL_0431: Unknown result type (might be due to invalid IL or missing references)
        //IL_043f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0444: Unknown result type (might be due to invalid IL or missing references)
        //IL_0445: Unknown result type (might be due to invalid IL or missing references)
        //IL_044a: Unknown result type (might be due to invalid IL or missing references)
        //IL_044f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0450: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0475: Unknown result type (might be due to invalid IL or missing references)
        //IL_047f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0485: Unknown result type (might be due to invalid IL or missing references)
        //IL_048a: Unknown result type (might be due to invalid IL or missing references)
        //IL_048f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0494: Unknown result type (might be due to invalid IL or missing references)
        //IL_0496: Unknown result type (might be due to invalid IL or missing references)
        //IL_049d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0102: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_0140: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_051c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0523: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0566: Unknown result type (might be due to invalid IL or missing references)
        //IL_056b: Unknown result type (might be due to invalid IL or missing references)
        //IL_056c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0571: Unknown result type (might be due to invalid IL or missing references)
        //IL_0577: Unknown result type (might be due to invalid IL or missing references)
        //IL_0217: Unknown result type (might be due to invalid IL or missing references)
        //IL_021e: Unknown result type (might be due to invalid IL or missing references)
        //IL_054b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_025a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_0268: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0295: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = position + new Vector2(12f) / 2f - new Vector2(4f) / 2f;
        vector.Y -= 4f;
        Vector2 vector2 = position - vector;
        if (velocity.Y < 0f)
        {
            Vector2 vector3 = default(Vector2);
            ((Vector2)(ref vector3))._002Ector(velocity.X, -0.2f);
            int num = 4;
            num = (int)((float)num * 0.9f);
            Point point = (new Vector2((float)num, (float)num) / 2f + vector).ToTileCoordinates();
            if (!WorldGen.InWorld(point.X, point.Y))
            {
                active = false;
                return;
            }
            Tile tile = Main.tile[point.X, point.Y];
            if (tile == null)
            {
                active = false;
                return;
            }
            int num2 = 6;
            Rectangle rectangle = default(Rectangle);
            ((Rectangle)(ref rectangle))._002Ector(point.X * 16, point.Y * 16 + tile.liquid / 16, 16, 16 - tile.liquid / 16);
            Rectangle value = default(Rectangle);
            ((Rectangle)(ref value))._002Ector((int)vector.X, (int)vector.Y + num2, num, num);
            bool flag = tile != null && tile.liquid > 0 && ((Rectangle)(ref rectangle)).Intersects(value);
            if (flag)
            {
                if (tile.honey())
                {
                    vector3.X = 0f;
                }
                else if (tile.lava())
                {
                    active = false;
                    for (int i = 0; i < 5; i++)
                    {
                        Dust.NewDust(position, num, num, 31, 0f, -0.2f);
                    }
                }
                else
                {
                    vector3.X = Main.WindForVisuals;
                }
                if ((double)position.Y > Main.worldSurface * 16.0)
                {
                    vector3.X = 0f;
                }
            }
            if (!WorldGen.SolidTile(point.X, point.Y + 1) && !flag)
            {
                velocity.Y = 0.1f;
                timeLeft = 0;
                alpha += 20;
            }
            vector3 = Collision.TileCollision(vector, vector3, num, num);
            if (flag)
            {
                rotation = vector3.ToRotation() + (float)Math.PI / 2f;
            }
            vector3.X *= 0.94f;
            if (!flag || ((double)vector3.X > -0.01 && (double)vector3.X < 0.01))
            {
                vector3.X = 0f;
            }
            if (timeLeft > 0)
            {
                timeLeft -= GoreID.Sets.DisappearSpeed[type];
            }
            else
            {
                alpha += GoreID.Sets.DisappearSpeedAlpha[type];
            }
            velocity.X = vector3.X;
            position.X += velocity.X;
            return;
        }
        velocity.Y += (float)Math.PI / 180f;
        Vector2 vector4 = default(Vector2);
        ((Vector2)(ref vector4))._002Ector(Vector2.UnitY.RotatedBy(velocity.Y).X * 1f, Math.Abs(Vector2.UnitY.RotatedBy(velocity.Y).Y) * 1f);
        int num3 = 4;
        if ((double)position.Y < Main.worldSurface * 16.0)
        {
            vector4.X += Main.WindForVisuals * 4f;
        }
        Vector2 vector5 = vector4;
        vector4 = Collision.TileCollision(vector, vector4, num3, num3);
        Vector4 vector6 = Collision.SlopeCollision(vector, vector4, num3, num3, 1f);
        position.X = vector6.X;
        position.Y = vector6.Y;
        vector4.X = vector6.Z;
        vector4.Y = vector6.W;
        position += vector2;
        if (vector4 != vector5)
        {
            velocity.Y = -1f;
        }
        Point point2 = (new Vector2(Width, Height) * 0.5f + position).ToTileCoordinates();
        if (!WorldGen.InWorld(point2.X, point2.Y))
        {
            active = false;
            return;
        }
        Tile tile2 = Main.tile[point2.X, point2.Y];
        if (tile2 == null)
        {
            active = false;
            return;
        }
        int num4 = 6;
        Rectangle rectangle2 = default(Rectangle);
        ((Rectangle)(ref rectangle2))._002Ector(point2.X * 16, point2.Y * 16 + tile2.liquid / 16, 16, 16 - tile2.liquid / 16);
        Rectangle value2 = default(Rectangle);
        ((Rectangle)(ref value2))._002Ector((int)vector.X, (int)vector.Y + num4, num3, num3);
        if (tile2 != null && tile2.liquid > 0 && ((Rectangle)(ref rectangle2)).Intersects(value2))
        {
            velocity.Y = -1f;
        }
        position += vector4;
        rotation = vector4.ToRotation() + (float)Math.PI / 2f;
        if (timeLeft > 0)
        {
            timeLeft -= GoreID.Sets.DisappearSpeed[type];
        }
        else
        {
            alpha += GoreID.Sets.DisappearSpeedAlpha[type];
        }
    }
References Terraria.Gore.active, Terraria.Gore.alpha, Terraria.ID.GoreID.Sets.DisappearSpeed, Terraria.ID.GoreID.Sets.DisappearSpeedAlpha, Terraria.Gore.Height, Terraria.Tile.honey(), Terraria.WorldGen.InWorld(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Dust.NewDust(), Terraria.Gore.position, Terraria.Gore.rotation, Terraria.Collision.SlopeCollision(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Collision.TileCollision(), Terraria.Gore.timeLeft, Terraria.Gore.type, Terraria.Gore.velocity, Terraria.Gore.Width, Terraria.Main.WindForVisuals, and Terraria.Main.worldSurface.
Referenced by Terraria.Gore.Update().