TModLoader: Terraria.Gore.NewGoreDirect
NewGoreDirect() [2/2]
static Gore Terraria.Gore.NewGoreDirect (Vector2 Position, Vector2 Velocity, int Type, float Scale = 1f) inline static package
Definition at line 1587 of file Gore.cs.
    {
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        return NewGoreDirect(IEntitySource.GetGoreFallback(), Position, Velocity, Type, Scale);
    }
References Terraria.DataStructures.IEntitySource.GetGoreFallback(), and Terraria.Gore.NewGoreDirect().
Referenced by Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_110_Betsy(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.Projectile.AI_136_BetsyBreath(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_153_ToiletPop(), Terraria.Projectile.AI_155_SpawnRopeIn(), Terraria.Projectile.AI_163_Chum(), Terraria.Projectile.CreateGroundExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.ElderSlimeEffect(), Terraria.GameContent.Drawing.TileDrawing.EmitTreeLeaves(), Terraria.Projectile.Kill(), Terraria.Gore.NewGoreDirect(), Terraria.Gore.NewGorePerfect(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PetExchange(), Terraria.WorldGen.TreeGrowFX_AshShake(), and Terraria.Gore.Update().