TModLoader: Terraria.Gore.NewGore
NewGore() [1/2]
static int Terraria.Gore.NewGore (IEntitySource source, Vector2 Position, Vector2 Velocity, int Type, float Scale = 1f) inline static
Spawns a gore with given properties.
Parameters
source Recommend using M:Terraria.Entity.GetSource_Death(System.String) or M:Terraria.Entity.GetSource_FromThis(System.String)" as the spawn source</param> <param name="Position"></param> <param name="Velocity"></param> <param name="Type"></param> <param name="Scale"></param> <returns>The index of the gore in the <see cref="F:Terraria.Main.gore" /> array
Definition at line 1649 of file Gore.cs.
    {
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_034e: Unknown result type (might be due to invalid IL or missing references)
        //IL_047f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0484: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0422: Unknown result type (might be due to invalid IL or missing references)
        //IL_0510: Unknown result type (might be due to invalid IL or missing references)
        //IL_0515: Unknown result type (might be due to invalid IL or missing references)
        //IL_054d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0577: Unknown result type (might be due to invalid IL or missing references)
        //IL_070e: Unknown result type (might be due to invalid IL or missing references)
        //IL_070f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0720: Unknown result type (might be due to invalid IL or missing references)
        //IL_074a: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode == 2)
        {
            return 600;
        }
        if (Main.gamePaused)
        {
            return 600;
        }
        if (WorldGen.gen)
        {
            return 600;
        }
        if (Main.rand == null)
        {
            Main.rand = new UnifiedRandom();
        }
        if (Type <= 0)
        {
            return 600;
        }
        int num = 600;
        for (int i = 0; i < 600; i++)
        {
            if (!Main.gore[i].active)
            {
                num = i;
                break;
            }
        }
        if (num == 600)
        {
            return num;
        }
        Main.gore[num].Frame = new SpriteFrame(1, 1);
        Main.gore[num].frameCounter = 0;
        Main.gore[num].behindTiles = false;
        Main.gore[num].light = 0f;
        Main.gore[num].position = Position;
        Main.gore[num].velocity = Velocity;
        Main.gore[num].velocity.Y -= (float)Main.rand.Next(10, 31) * 0.1f;
        Main.gore[num].velocity.X += (float)Main.rand.Next(-20, 21) * 0.1f;
        Main.gore[num].type = Type;
        Main.gore[num].active = true;
        Main.gore[num].alpha = 0;
        Main.gore[num].rotation = 0f;
        Main.gore[num].scale = Scale;
        if (!ChildSafety.Disabled && ChildSafety.DangerousGore(Type))
        {
            Main.gore[num].type = Main.rand.Next(11, 14);
            Main.gore[num].scale = Main.rand.NextFloat() * 0.5f + 0.5f;
            Gore obj = Main.gore[num];
            obj.velocity /= 2f;
        }
        if (goreTime == 0 || Type == 11 || Type == 12 || Type == 13 || Type == 16 || Type == 17 || Type == 61 || Type == 62 || Type == 63 || Type == 99 || Type == 220 || Type == 221 || Type == 222 || Type == 435 || Type == 436 || Type == 437 || (Type >= 861 && Type <= 862))
        {
            Main.gore[num].sticky = false;
        }
        else if (Type >= 375 && Type <= 377)
        {
            Main.gore[num].sticky = false;
            Main.gore[num].alpha = 100;
        }
        else
        {
            Main.gore[num].sticky = true;
            Main.gore[num].timeLeft = goreTime;
        }
        if ((Type >= 706 && Type <= 717) || Type == 943 || Type == 1147 || (Type >= 1160 && Type <= 1162))
        {
            Main.gore[num].numFrames = 15;
            Main.gore[num].behindTiles = true;
            Main.gore[num].timeLeft = goreTime * 3;
        }
        if (Type == 16 || Type == 17)
        {
            Main.gore[num].alpha = 100;
            Main.gore[num].scale = 0.7f;
            Main.gore[num].light = 1f;
        }
        if (Type >= 570 && Type <= 572)
        {
            Main.gore[num].velocity = Velocity;
        }
        if (Type == 1201 || Type == 1208)
        {
            Main.gore[num].Frame = new SpriteFrame(1, 4);
        }
        if (Type == 1217 || Type == 1218)
        {
            Main.gore[num].Frame = new SpriteFrame(1, 3);
        }
        if (Type == 1225)
        {
            Main.gore[num].Frame = new SpriteFrame(1, 3);
            Main.gore[num].timeLeft = 10 + Main.rand.Next(6);
            Main.gore[num].sticky = false;
            if (TextureAssets.Gore[Type].IsLoaded)
            {
                Main.gore[num].position.X = Position.X - (float)(TextureAssets.Gore[Type].Width() / 2) * Scale;
                Main.gore[num].position.Y = Position.Y - (float)TextureAssets.Gore[Type].Height() * Scale / 2f;
            }
        }
        int num3 = GoreID.Sets.SpecialAI[Type];
        if (num3 == 3)
        {
            Main.gore[num].velocity = new Vector2((Main.rand.NextFloat() - 0.5f) * 1f, Main.rand.NextFloat() * ((float)Math.PI * 2f));
            bool flag = GoreID.Sets.PaintedFallingLeaf[Type];
            Gore obj2 = Main.gore[num];
            SpriteFrame spriteFrame2 = new SpriteFrame((byte)((!flag) ? 1u : 32u), 8)
            {
                CurrentRow = (byte)Main.rand.Next(8)
            };
            SpriteFrame spriteFrame = spriteFrame2;
            obj2.Frame = spriteFrame;
            Main.gore[num].frameCounter = (byte)Main.rand.Next(8);
        }
        if (num3 == 1)
        {
            Main.gore[num].velocity = new Vector2((Main.rand.NextFloat() - 0.5f) * 3f, Main.rand.NextFloat() * ((float)Math.PI * 2f));
        }
        if (Type >= 411 && Type <= 430 && TextureAssets.Gore[Type].IsLoaded)
        {
            Main.gore[num].position.X = Position.X - (float)(TextureAssets.Gore[Type].Width() / 2) * Scale;
            Main.gore[num].position.Y = Position.Y - (float)TextureAssets.Gore[Type].Height() * Scale;
            Main.gore[num].velocity.Y *= (float)Main.rand.Next(90, 150) * 0.01f;
            Main.gore[num].velocity.X *= (float)Main.rand.Next(40, 90) * 0.01f;
            int num2 = Main.rand.Next(4) * 5;
            Main.gore[num].type += num2;
            Main.gore[num].timeLeft = Main.rand.Next(goreTime / 2, goreTime * 2);
            Main.gore[num].sticky = true;
            if (goreTime == 0)
            {
                Main.gore[num].timeLeft = Main.rand.Next(150, 600);
            }
        }
        if (Type >= 907 && Type <= 909)
        {
            Main.gore[num].sticky = true;
            Main.gore[num].numFrames = 3;
            Main.gore[num].frame = (byte)Main.rand.Next(3);
            Main.gore[num].frameCounter = (byte)Main.rand.Next(5);
            Main.gore[num].rotation = 0f;
        }
        if (num3 == 2)
        {
            Main.gore[num].sticky = false;
            if (TextureAssets.Gore[Type].IsLoaded)
            {
                Main.gore[num].alpha = 150;
                Main.gore[num].velocity = Velocity;
                Main.gore[num].position.X = Position.X - (float)(TextureAssets.Gore[Type].Width() / 2) * Scale;
                Main.gore[num].position.Y = Position.Y - (float)TextureAssets.Gore[Type].Height() * Scale / 2f;
                Main.gore[num].timeLeft = Main.rand.Next(goreTime / 2, goreTime + 1);
            }
        }
        if (num3 == 4)
        {
            Main.gore[num].alpha = 254;
            Main.gore[num].timeLeft = 300;
        }
        if (num3 == 5)
        {
            Main.gore[num].alpha = 254;
            Main.gore[num].timeLeft = 240;
        }
        if (num3 == 6)
        {
            Main.gore[num].alpha = 254;
            Main.gore[num].timeLeft = 480;
        }
        Gore gore = Main.gore[num];
        gore.ResetNewFields();
        gore.ModGore = GoreLoader.GetModGore(gore.type);
        gore.ModGore?.OnSpawn(gore, source ?? IEntitySource.GetGoreFallback());
        if (Main.gore[num].DeactivateIfOutsideOfWorld())
        {
            return 600;
        }
        return num;
    }
References Terraria.Gore.active, Terraria.Gore.alpha, Terraria.Gore.behindTiles, Terraria.GameContent.ChildSafety.DangerousGore(), Terraria.Gore.DeactivateIfOutsideOfWorld(), Terraria.GameContent.ChildSafety.Disabled, Terraria.Gore.Frame, Terraria.Gore.frame, Terraria.Gore.frameCounter, Terraria.Main.gamePaused, Terraria.WorldGen.gen, Terraria.DataStructures.IEntitySource.GetGoreFallback(), Terraria.ModLoader.GoreLoader.GetModGore(), Terraria.GameContent.TextureAssets.Gore, Terraria.Main.gore, Terraria.Gore.goreTime, Terraria.Gore.light, Terraria.Gore.ModGore, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Gore.numFrames, Terraria.ModLoader.ModGore.OnSpawn(), Terraria.ID.GoreID.Sets.PaintedFallingLeaf, Terraria.Gore.position, Terraria.Main.rand, Terraria.Gore.ResetNewFields(), Terraria.Gore.rotation, Terraria.Gore.scale, Terraria.ID.GoreID.Sets.SpecialAI, Terraria.Gore.sticky, Terraria.Gore.timeLeft, Terraria.Gore.type, and Terraria.Gore.velocity.