TModLoader: Terraria.ModLoader.Mod.Autoload
Autoload()
void Terraria.ModLoader.Mod.Autoload () inline package inherited
Definition at line 504 of file Mod.cs.
    {
        if (Code == null)
        {
            return;
        }
        LocalizationLoader.Autoload(this);
        Interface.loadMods.SubProgressText = Language.GetTextValue("tModLoader.MSFinishingResourceLoading");
        while (AsyncLoadQueue.Count > 0)
        {
            AsyncLoadQueue.Dequeue().Wait();
        }
        ModSourceBestiaryInfoElement = new ModSourceBestiaryInfoElement(this, DisplayName);
        if (ContentAutoloadingEnabled)
        {
            LoaderUtils.ForEachAndAggregateExceptions((from t in AssemblyManager.GetLoadableTypes(Code)
                where !t.IsAbstract && !t.ContainsGenericParameters
                where t.IsAssignableTo(typeof(ILoadable))
                where t.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, Type.EmptyTypes) != null
                where AutoloadAttribute.GetValue(t).NeedsAutoloading
                select t).OrderBy<Type, string>((Type type) => type.FullName, StringComparer.InvariantCulture), delegate(Type t)
            {
                AddContent((ILoadable)Activator.CreateInstance(t, nonPublic: true));
            });
        }
        if (!Main.dedServ)
        {
            if (GoreAutoloadingEnabled)
            {
                GoreLoader.AutoloadGores(this);
            }
            if (MusicAutoloadingEnabled)
            {
                MusicLoader.AutoloadMusic(this);
            }
            if (BackgroundAutoloadingEnabled)
            {
                BackgroundTextureLoader.AutoloadBackgrounds(this);
            }
        }
    }
References Terraria.ModLoader.Mod.AddContent(), Terraria.ModLoader.Mod.AsyncLoadQueue, Terraria.ModLoader.LocalizationLoader.Autoload(), Terraria.ModLoader.BackgroundTextureLoader.AutoloadBackgrounds(), Terraria.ModLoader.GoreLoader.AutoloadGores(), Terraria.ModLoader.MusicLoader.AutoloadMusic(), Terraria.ModLoader.Mod.BackgroundAutoloadingEnabled, Terraria.ModLoader.Mod.Code, Terraria.ModLoader.Mod.ContentAutoloadingEnabled, Terraria.Main.dedServ, Terraria.ModLoader.Mod.DisplayName, Terraria.ModLoader.Core.AssemblyManager.GetLoadableTypes(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.AutoloadAttribute.GetValue(), Terraria.ModLoader.Mod.GoreAutoloadingEnabled, Terraria.ModLoader.Mod.ModSourceBestiaryInfoElement, and Terraria.ModLoader.Mod.MusicAutoloadingEnabled.
Referenced by Terraria.ModLoader.ModContent.Load().