TModLoader: Terraria.ModLoader.Mod.AutoloadConfig
AutoloadConfig()
void Terraria.ModLoader.Mod.AutoloadConfig () inline package inherited
Definition at line 130 of file Mod.cs.
    {
        if (Code == null)
        {
            return;
        }
        foreach (Type type2 in from type in AssemblyManager.GetLoadableTypes(Code)
            orderby type.FullName
            select type)
        {
            if (!type2.IsAbstract && type2.IsSubclassOf(typeof(ModConfig)))
            {
                ModConfig mc = (ModConfig)Activator.CreateInstance(type2, nonPublic: true);
                if (mc.Mode == ConfigScope.ServerSide && (Side == ModSide.Client || Side == ModSide.NoSync))
                {
                    throw new Exception("The ModConfig " + mc.Name + " can't be loaded because the config is ServerSide but this Mods ModSide isn't Both or Server");
                }
                if (mc.Mode == ConfigScope.ClientSide && Side == ModSide.Server)
                {
                    throw new Exception("The ModConfig " + mc.Name + " can't be loaded because the config is ClientSide but this Mods ModSide is Server");
                }
                mc.Mod = this;
                string name = type2.Name;
                if (mc.Autoload(ref name))
                {
                    AddConfig(name, mc);
                }
            }
        }
    }
References Terraria.ModLoader.Mod.AddConfig(), Terraria.ModLoader.Mod.Code, Terraria.ModLoader.Core.AssemblyManager.GetLoadableTypes(), and Terraria.ModLoader.Mod.Side.
Referenced by Terraria.ModLoader.ModContent.Load().