TModLoader: Terraria.ModLoader.Mod.UnloadContent
UnloadContent()
void Terraria.ModLoader.Mod.UnloadContent () inline package inherited
Definition at line 491 of file Mod.cs.
    {
        SystemLoader.OnModUnload(this);
        Unload();
        foreach (ILoadable item in content.Reverse())
        {
            item.Unload();
        }
        content.Clear();
        equipTextures.Clear();
        Assets?.Dispose();
    }
References Terraria.ModLoader.Mod.content, Terraria.ModLoader.Mod.equipTextures, Terraria.ModLoader.SystemLoader.OnModUnload(), Terraria.ModLoader.ILoadable.Unload(), and Terraria.ModLoader.Mod.Unload().
Referenced by Terraria.ModLoader.ModContent.UnloadModContent().