TModLoader: Terraria.ModLoader.Mod.PrepareAssets
PrepareAssets()
void Terraria.ModLoader.Mod.PrepareAssets () inline package inherited
    {
        fileHandle = File?.Open();
        RootContentSource = CreateDefaultContentSource();
        Assets = new AssetRepository(((IServiceProvider)((Game)Main.instance).Services).Get<AssetReaderCollection>(), new IContentSource[1] { RootContentSource })
        {
            AssetLoadFailHandler = OnceFailedLoadingAnAsset
        };
    }
References Terraria.ModLoader.Mod.Assets, Terraria.ModLoader.Mod.CreateDefaultContentSource(), Terraria.ModLoader.Mod.File, Terraria.ModLoader.Mod.fileHandle, Terraria.Main.instance, Terraria.ModLoader.Mod.OnceFailedLoadingAnAsset(), Terraria.ModLoader.Core.TmodFile.Open(), and Terraria.ModLoader.Mod.RootContentSource.
Referenced by Terraria.ModLoader.ModContent.Load().