TModLoader: Terraria.ModLoader.Mod.AddContent
AddContent()
bool Terraria.ModLoader.Mod.AddContent (ILoadable instance) inline inherited
Call this to manually add the given content instance to the game.
Parameters
instance The content instance to add
Returns
true if the instance was successfully added
Definition at line 180 of file Mod.cs.
    {
        if (!loading)
        {
            throw new Exception(Language.GetTextValue("tModLoader.LoadErrorNotLoading"));
        }
        if (!instance.IsLoadingEnabled(this))
        {
            return false;
        }
        instance.Load(this);
        content.Add(instance);
        ContentInstance.Register(instance);
        return true;
    }
References Terraria.ModLoader.Mod.content, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.ILoadable.IsLoadingEnabled(), Terraria.ModLoader.ILoadable.Load(), Terraria.ModLoader.Mod.loading, and Terraria.ModLoader.ContentInstance< T >.Register().
Referenced by Terraria.ModLoader.Mod.AddContent< T >(), and Terraria.ModLoader.Mod.Autoload().