TModLoader: Terraria.ModLoader.Default.Patreon.OrianSetEffectPlayer.PostUpdate
PostUpdate()
override void Terraria.ModLoader.Default.Patreon.OrianSetEffectPlayer.PostUpdate () inline virtual
This is called at the very end of the Player.Update method. Final general update tasks can be placed here.
Reimplemented from Terraria.ModLoader.ModPlayer.
    {
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        if (!IsActive)
        {
            return;
        }
        Player player = base.Player;
        Vector2 playerCenter = player.Center;
        Main.npc.Any((NPC x) => x != Main.npc[Main.maxNPCs] && x.active && !x.friendly && !NPCID.Sets.TownCritter[x.type] && x.type != 488 && x.WithinRange(player.position, 300f));
        float maxIntensity = 0f;
        for (int i = 0; i < Main.maxNPCs; i++)
        {
            NPC npc = Main.npc[i];
            if (npc.active && npc.damage > 0 && !npc.friendly && !NPCID.Sets.TownCritter[npc.type] && npc.type != 488)
            {
                float distanceSquared = npc.DistanceSQ(playerCenter);
                float intensity = 1f - MathF.Min(1f, distanceSquared / 262144f);
                intensity *= intensity;
                maxIntensity = MathF.Max(maxIntensity, intensity);
            }
        }
        if (maxIntensity > 0f)
        {
            float pulse = MathF.Sin((float)Main.GameUpdateCount / 17f) * 0.25f + 0.75f;
            Color deepSkyBlue = Color.DeepSkyBlue;
            Lighting.AddLight(playerCenter, ((Color)(ref deepSkyBlue)).ToVector3() * maxIntensity * pulse * 1.5f);
        }
    }
References Terraria.Entity.active, Terraria.Lighting.AddLight(), Terraria.Entity.Center, Terraria.NPC.damage, Terraria.Entity.DistanceSQ(), Terraria.NPC.friendly, Terraria.Main.GameUpdateCount, Terraria.ModLoader.Default.Patreon.OrianSetEffectPlayer.IsActive, Terraria.Main.maxNPCs, Terraria.Main.npc, Terraria.Entity.position, Terraria.ID.NPCID.Sets.TownCritter, Terraria.NPC.type, and Terraria.Entity.WithinRange().