TModLoader: Terraria.ModLoader.RecipeLoader.OnCraft
OnCraft() [2/2]
static void Terraria.ModLoader.RecipeLoader.OnCraft (Item item, Recipe recipe, List< Item > consumedItems, Item destinationStack) inline static
recipe.OnCraftHooks followed by Calls ItemLoader.OnCreate with a RecipeCreationContext
Parameters
item The item crafted.
recipe The recipe used to craft the item.
consumedItems Materials used to craft the item.
destinationStack The stack that the crafted item will be combined with
Definition at line 216 of file RecipeLoader.cs.
    {
        recipe.OnCraftHooks?.Invoke(recipe, item, consumedItems, destinationStack);
        item.OnCreated(new RecipeItemCreationContext(recipe, consumedItems, destinationStack));
    }
References Terraria.Recipe.OnCraftHooks, and Terraria.Item.OnCreated().
Referenced by Terraria.Main.CraftItem(), and Terraria.ModLoader.RecipeLoader.OnCraft().