TModLoader: Terraria.ModLoader.UI.UILoadMods.SetLoadStage
SetLoadStage()
void Terraria.ModLoader.UI.UILoadMods.SetLoadStage (string stageText, int modCount = -1) inline
Definition at line 35 of file UILoadMods.cs.
    {
        this.stageText = stageText;
        this.modCount = modCount;
        if (modCount < 0)
        {
            SetProgressText(Language.GetTextValue(stageText));
        }
        base.Progress = 0f;
        base.SubProgressText = "";
    }
References Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.UILoadMods.modCount, Terraria.ModLoader.UI.UILoadMods.SetProgressText(), and Terraria.ModLoader.UI.UILoadMods.stageText.
Referenced by Terraria.ModLoader.Core.AssemblyManager.InstantiateMods(), Terraria.ModLoader.ModContent.Load(), Terraria.ModLoader.ModLoader.Mods_Unload(), Terraria.ModLoader.UI.UILoadMods.OnActivate(), Terraria.ModLoader.Core.ModOrganizer.SelectAndSortMods(), and Terraria.ModLoader.ModContent.SetupRecipes().