TModLoader: Terraria.ModLoader.Default.TEModdedPylon.Hook_AfterPlacement
Hook_AfterPlacement()
override int Terraria.ModLoader.Default.TEModdedPylon.Hook_AfterPlacement (int i, int j, int type, int style, int direction, int alternate) inline virtual
This method does not get called by tModLoader, and is only included for you convenience so you do not have to cast the result of Mod.GetTileEntity.
Reimplemented from Terraria.ModLoader.ModTileEntity.
    {
        TileObjectData tileData = TileObjectData.GetTileData(type, style, alternate);
        int topLeftX = i - tileData.Origin.X;
        int topLeftY = j - tileData.Origin.Y;
        if (Main.netMode == 1)
        {
            NetMessage.SendTileSquare(Main.myPlayer, topLeftX, topLeftY, tileData.Width, tileData.Height);
            NetMessage.SendData(87, -1, -1, null, topLeftX, topLeftY, base.Type);
            return -1;
        }
        return Place(topLeftX, topLeftY);
    }
References Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.ModLoader.Default.TEModdedPylon.Place(), Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), and Terraria.DataStructures.TileEntity.type.