TModLoader: Terraria.ModLoader.Default.TEModdedPylon.NetPlaceEntityAttempt
NetPlaceEntityAttempt()
override void Terraria.ModLoader.Default.TEModdedPylon.NetPlaceEntityAttempt (int x, int y) inline virtual
Reimplemented from Terraria.DataStructures.TileEntity.
Definition at line 13 of file TEModdedPylon.cs.
    {
        if (!GetModPylonFromCoords(x, y, out var pylon))
        {
            RejectPlacementFromNet(x, y);
            return;
        }
        if (!(PylonLoader.PreCanPlacePylon(x, y, pylon.Type, pylon.PylonType) ?? pylon.CanPlacePylon()))
        {
            RejectPlacementFromNet(x, y);
            return;
        }
        int ID = Place(x, y);
        NetMessage.SendData(86, -1, -1, null, ID, x, y);
    }
References Terraria.ModLoader.Default.TEModdedPylon.GetModPylonFromCoords(), Terraria.DataStructures.TileEntity.ID, Terraria.ModLoader.Default.TEModdedPylon.Place(), Terraria.ModLoader.PylonLoader.PreCanPlacePylon(), Terraria.ModLoader.Default.TEModdedPylon.RejectPlacementFromNet(), and Terraria.NetMessage.SendData().