TModLoader: Terraria.ID.TileID.Sets.DisableSmartCursor
DisableSmartCursor
bool [] Terraria.ID.TileID.Sets.DisableSmartCursor = Factory.CreateBoolSet(4, 10, 11, 13, 21, 29, 33, 49, 50, 55, 79, 85, 88, 97, 104, 125, 132, 136, 139, 144, 174, 207, 209, 212, 216, 219, 237, 287, 334, 335, 338, 354, 386, 387, 388, 389, 411, 425, 441, 463, 467, 468, 491, 494, 510, 511, 573, 621, 642) static
Whether or not the smart cursor function is disabled when the cursor hovers above this tile.
Referenced by Terraria.GameContent.SmartCursorHelper.IsHoveringOverAnInteractibleTileThatBlocksSmartCursor(), Terraria.ModLoader.Default.UnloadedChest.SetStaticDefaults(), Terraria.ModLoader.Default.UnloadedDresser.SetStaticDefaults(), Terraria.ModLoader.Default.UnloadedNonSolidTile.SetStaticDefaults(), Terraria.ModLoader.Default.UnloadedSemiSolidTile.SetStaticDefaults(), Terraria.ModLoader.Default.UnloadedSolidTile.SetStaticDefaults(), and Terraria.ModLoader.Default.UnloadedSupremeFurniture.SetStaticDefaults().