TModLoader: Terraria.ModLoader.UI.UIButton.Draw
Draw()
override void Terraria.ModLoader.UI.UIButton< T >.Draw (SpriteBatch spriteBatch) inline virtual
Reimplemented from Terraria.UI.UIElement.
    {
        base.Draw(spriteBatch);
        SetPanelColors();
        if (!base.IsMouseHovering)
        {
            return;
        }
        T val;
        object obj;
        if (!UseAltColors())
        {
            ref T reference = ref HoverText;
            val = default(T);
            if (val == null)
            {
                val = reference;
                reference = ref val;
                if (val == null)
                {
                    obj = null;
                    goto IL_0091;
                }
            }
            obj = reference.ToString();
        }
        else
        {
            ref T reference2 = ref AltHoverText;
            val = default(T);
            if (val == null)
            {
                val = reference2;
                reference2 = ref val;
                if (val == null)
                {
                    obj = null;
                    goto IL_0091;
                }
            }
            obj = reference2.ToString();
        }
        goto IL_0091;
        IL_0091:
        string text = (string)obj;
        if (text != null)
        {
            if (TooltipText)
            {
                UICommon.TooltipMouseText(text);
            }
            else
            {
                Main.instance.MouseText(text, 0, 0);
            }
        }
    }
References Terraria.ModLoader.UI.UIButton< T >.AltHoverText, Terraria.ModLoader.UI.UIButton< T >.HoverText, Terraria.Main.instance, Terraria.Main.MouseText(), Terraria.ModLoader.UI.UIButton< T >.SetPanelColors(), Terraria.ModLoader.UI.UICommon.TooltipMouseText(), Terraria.ModLoader.UI.UIButton< T >.TooltipText, and Terraria.ModLoader.UI.UIButton< T >.UseAltColors.