TModLoader: Terraria.ObjectData.TileObjectData.GetTileData
GetTileData() [1/2]
static TileObjectData Terraria.ObjectData.TileObjectData.GetTileData (int type, int style, int alternate = 0) inline static
Definition at line 4380 of file TileObjectData.cs.
    {
        if (type < 0 || type >= _data.Count)
        {
            throw new ArgumentOutOfRangeException("Function called with a bad type argument");
        }
        if (style < 0)
        {
            throw new ArgumentOutOfRangeException("Function called with a bad style argument");
        }
        TileObjectData tileObjectData = _data[type];
        if (tileObjectData == null)
        {
            return null;
        }
        List<TileObjectData> subTiles = tileObjectData.SubTiles;
        if (subTiles != null && style < subTiles.Count)
        {
            TileObjectData tileObjectData2 = subTiles[style];
            if (tileObjectData2 != null)
            {
                tileObjectData = tileObjectData2;
            }
        }
        alternate--;
        List<TileObjectData> alternates = tileObjectData.Alternates;
        if (alternates != null && alternate >= 0 && alternate < alternates.Count)
        {
            TileObjectData tileObjectData3 = alternates[alternate];
            if (tileObjectData3 != null)
            {
                tileObjectData = tileObjectData3;
            }
        }
        return tileObjectData;
    }
References Terraria.ObjectData.TileObjectData._data.
Referenced by Terraria.ObjectData.TileObjectData.CallPostPlacementPlayerHook(), Terraria.TileObject.CanPlace(), Terraria.ObjectData.TileObjectData.CheckLavaDeath(), Terraria.ObjectData.TileObjectData.CheckLavaDeath(), Terraria.ObjectData.TileObjectData.CheckLiquidPlacement(), Terraria.ModLoader.TileLoader.CheckModTile(), Terraria.WorldGen.CheckSuper(), Terraria.WorldGen.CheckTallGate(), Terraria.ObjectData.TileObjectData.CheckWaterDeath(), Terraria.ObjectData.TileObjectData.CheckWaterDeath(), Terraria.ModLoader.ModPylon.DefaultDrawPylonCrystal(), Terraria.ModLoader.ModPylon.DrawEffects(), Terraria.TileObject.DrawPreview(), Terraria.ModLoader.TileLoader.Drop(), Terraria.ObjectData.TileObjectData.FullCopyFrom(), Terraria.Projectile.GasTrapCheck(), Terraria.ModLoader.TileLoader.GetItemDrops(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.ModLoader.Default.TEModdedPylon.Hook_AfterPlacement(), Terraria.ModLoader.Default.TEModdedPylon.IsTileValidForEntity(), Terraria.ModLoader.TileLoader.ModifySmartInteractCoords(), Terraria.ObjectData.TileObjectData.OriginToTopLeft(), Terraria.TileObject.Place(), Terraria.WorldGen.PlaceTile(), Terraria.ModLoader.TileLoader.SetDrawPositions(), Terraria.WorldGen.ShiftTallGate(), Terraria.ObjectData.TileObjectData.SyncObjectPlacement(), and Terraria.ModLoader.ModPylon.TileFrame().