TModLoader: Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.GenerateModDownloadItemFromQuery
GenerateModDownloadItemFromQuery()
ModDownloadItem Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.GenerateModDownloadItemFromQuery (uint i) inline package
            {
                //IL_0007: Unknown result type (might be due to invalid IL or missing references)
                //IL_000d: Unknown result type (might be due to invalid IL or missing references)
                //IL_0012: Unknown result type (might be due to invalid IL or missing references)
                //IL_0013: Unknown result type (might be due to invalid IL or missing references)
                //IL_0014: Unknown result type (might be due to invalid IL or missing references)
                //IL_0019: Unknown result type (might be due to invalid IL or missing references)
                //IL_001a: Unknown result type (might be due to invalid IL or missing references)
                //IL_001b: Unknown result type (might be due to invalid IL or missing references)
                //IL_0024: Unknown result type (might be due to invalid IL or missing references)
                //IL_0025: Unknown result type (might be due to invalid IL or missing references)
                //IL_002b: Invalid comparison between Unknown and I4
                //IL_0077: Unknown result type (might be due to invalid IL or missing references)
                //IL_008f: Unknown result type (might be due to invalid IL or missing references)
                //IL_0037: Unknown result type (might be due to invalid IL or missing references)
                //IL_0038: Unknown result type (might be due to invalid IL or missing references)
                //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
                //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
                //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
                //IL_026c: Unknown result type (might be due to invalid IL or missing references)
                //IL_027a: Unknown result type (might be due to invalid IL or missing references)
                SteamUGCDetails_t pDetails = SteamedWraps.FetchItemDetails(_primaryUGCHandle, i);
                PublishedFileId_t id = pDetails.m_nPublishedFileId;
                if ((int)pDetails.m_eVisibility != 0)
                {
                    return null;
                }
                if ((int)pDetails.m_eResult != 1)
                {
                    ILog tML = Logging.tML;
                    PublishedFileId_t val = id;
                    tML.Warn((object)("Unable to fetch mod PublishId#" + ((object)(PublishedFileId_t)(ref val)).ToString() + " information. " + ((object)(EResult)(ref pDetails.m_eResult)).ToString()));
                    return null;
                }
                string ownerId = pDetails.m_ulSteamIDOwner.ToString();
                DateTime lastUpdate = Utils.UnixTimeStampToDateTime(pDetails.m_rtimeUpdated);
                string displayname = ((SteamUGCDetails_t)(ref pDetails)).m_rgchTitle;
                SteamedWraps.FetchMetadata(_primaryUGCHandle, i, out var metadata);
                if (metadata["versionsummary"] == null)
                {
                    metadata["versionsummary"] = metadata["version"];
                }
                string[] missingKeys = MetadataKeys.Where((string k) => metadata.Get(k) == null).ToArray();
                if (missingKeys.Length != 0)
                {
                    Logging.tML.Warn((object)$"Mod '{displayname}' is missing required metadata: {string.Join(',', missingKeys.Select((string k) => "'" + k + "'"))}.");
                    return null;
                }
                if (string.IsNullOrWhiteSpace(metadata["name"]))
                {
                    Logging.tML.Warn((object)$"Mod has no name: {id}");
                    return null;
                }
                string[] refsById = (from x in SteamedWraps.FetchItemDependencies(_primaryUGCHandle, i, pDetails.m_unNumChildren)
                    select x.m_PublishedFileId.ToString()).ToArray();
                (Version, Version) cVersion = CalculateRelevantVersion(((SteamUGCDetails_t)(ref pDetails)).m_rgchDescription, metadata);
                ModSide modside = ModSide.Both;
                if (metadata["modside"] == "Client")
                {
                    modside = ModSide.Client;
                }
                if (metadata["modside"] == "Server")
                {
                    modside = ModSide.Server;
                }
                if (metadata["modside"] == "NoSync")
                {
                    modside = ModSide.NoSync;
                }
                SteamedWraps.FetchPreviewImageUrl(_primaryUGCHandle, i, out var modIconURL);
                SteamedWraps.FetchPlayTimeStats(_primaryUGCHandle, i, out var hot, out var downloads);
                return new ModDownloadItem(displayname, metadata["name"], cVersion.Item1, metadata["author"], metadata["modreferences"], modside, modIconURL, id.m_PublishedFileId.ToString(), (int)downloads, (int)hot, lastUpdate, cVersion.Item2, metadata["homepage"], ownerId, refsById);
            }
References Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance._primaryUGCHandle, Terraria.Social.Steam.WorkshopHelper.CalculateRelevantVersion(), Terraria.Social.Steam.SteamedWraps.FetchItemDependencies(), Terraria.Social.Steam.SteamedWraps.FetchItemDetails(), Terraria.Social.Steam.SteamedWraps.FetchMetadata(), Terraria.Social.Steam.SteamedWraps.FetchPlayTimeStats(), Terraria.Social.Steam.SteamedWraps.FetchPreviewImageUrl(), Terraria.Social.Steam.WorkshopHelper.MetadataKeys, Terraria.ModLoader.Logging.tML, and Terraria.Utils.UnixTimeStampToDateTime().
Referenced by Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.ProcessPageResult(), Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.QueryItemsSynchronously(), and Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.TrySearchByInternalName().