TModLoader: Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.QueryItemsSynchronously
QueryItemsSynchronously()
List< ModDownloadItem > Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.QueryItemsSynchronously (out List< string > missingMods) inline package
For direct information gathering of particular mod/workshop items. Synchronous. Note that the List size is 1 to 1 with the provided array. If the Mod is not found, the space is filled with a null.
Definition at line 780 of file WorkshopHelper.cs.
            {
                //IL_0084: Unknown result type (might be due to invalid IL or missing references)
                double numPages = Math.Ceiling((float)queryParameters.searchModIds.Length / 50f);
                List<ModDownloadItem> items = new List<ModDownloadItem>();
                missingMods = new List<string>();
                for (int i = 0; (double)i < numPages; i++)
                {
                    string[] idArray = (from x in queryParameters.searchModIds.Take((i * 50)..(50 * (i + 1)))
                        select x.m_ModPubId).ToArray();
                    try
                    {
                        WaitForQueryResult(SteamedWraps.GenerateDirectItemsQuery(idArray));
                        for (int j = 0; j < _queryReturnCount; j++)
{
                            ModDownloadItem item = GenerateModDownloadItemFromQuery((uint)j);
                            if (item == null)
{
                                Logging.tML.Warn((object)("Unable to find Mod with ID " + idArray[j] + " on the Steam Workshop"));
                                missingMods.Add(idArray[j]);
                            }
                            else
{
                                item.UpdateInstallState();
                                items.Add(item);
                            }
                        }
                    }
                    finally
                    {
                        ReleaseWorkshopQuery();
                    }
                }
                return items;
            }
References Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance._queryReturnCount, Terraria.Social.Steam.SteamedWraps.GenerateDirectItemsQuery(), Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.GenerateModDownloadItemFromQuery(), Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.queryParameters, Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.ReleaseWorkshopQuery(), Terraria.Social.Base.QueryParameters.searchModIds, Terraria.ModLoader.Logging.tML, Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.UpdateInstallState(), and Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.WaitForQueryResult().
Referenced by Terraria.Social.Steam.WorkshopBrowserModule.DirectQueryItems().