TModLoader: Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.WaitForQueryResultAsync
WaitForQueryResultAsync()
async Task Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.WaitForQueryResultAsync (SteamAPICall_t query, CancellationToken token = default(CancellationToken)) inline package
Definition at line 912 of file WorkshopHelper.cs.
            {
                //IL_0016: Unknown result type (might be due to invalid IL or missing references)
                //IL_0017: Unknown result type (might be due to invalid IL or missing references)
                _primaryQueryResult = (EResult)0;
                _queryHook.Set(query, (APIDispatchDelegate<SteamUGCQueryCompleted_t>)null);
                Stopwatch stopwatch = Stopwatch.StartNew();
                while (true)
                {
                    SteamedWraps.RunCallbacks();
                    if ((int)_primaryQueryResult != 0)
                    {
                        break;
                    }
                    if (stopwatch.Elapsed.TotalSeconds >= 10.0)
                    {
                        throw new TimeoutException("No response from steam workshop query");
                    }
                    await Task.Delay(1, token);
                }
                if ((int)_primaryQueryResult != 1)
                {
                    SteamedWraps.ReportCheckSteamLogs();
                    throw new Exception($"Error: Unable to access Steam Workshop. ERROR CODE: {_primaryQueryResult}");
                }
            }
References Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance._primaryQueryResult, Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance._queryHook, Terraria.Social.Steam.SteamedWraps.ReportCheckSteamLogs(), and Terraria.Social.Steam.SteamedWraps.RunCallbacks().
Referenced by Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.QueryAllWorkshopItems(), and Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.WaitForQueryResult().