TModLoader: Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.ReleaseWorkshopQuery
ReleaseWorkshopQuery()
void Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.ReleaseWorkshopQuery () inline private
Ought be called to release the existing query when we are done with it. Frees memory associated with the handle.
            {
                //IL_0001: Unknown result type (might be due to invalid IL or missing references)
                SteamedWraps.ReleaseWorkshopHandle(_primaryUGCHandle);
            }
References Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance._primaryUGCHandle, and Terraria.Social.Steam.SteamedWraps.ReleaseWorkshopHandle().
Referenced by Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.QueryAllWorkshopItems(), Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.QueryItemsSynchronously(), and Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.TrySearchByInternalName().