TModLoader: Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.QueryAllWorkshopItems
QueryAllWorkshopItems()
async IAsyncEnumerable< ModDownloadItem > Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.QueryAllWorkshopItems ([EnumeratorCancellation] CancellationToken token = default(CancellationToken)) inline package
Definition at line 816 of file WorkshopHelper.cs.
            {
                uint currentPage = 1u;
                int currentPageAttempts = 0;
                uint num;
                do
                {
                    token.ThrowIfCancellationRequested();
                    try
                    {
                        try
{
                            await WaitForQueryResultAsync(SteamedWraps.GenerateAndSubmitModBrowserQuery(currentPage, queryParameters), token);
                        }
                        catch
{
                            if (currentPageAttempts == 1)
{
                                throw;
                            }
                            await Task.Delay(100, token);
                            currentPage--;
                            currentPageAttempts++;
                            goto end_IL_0088;
                        }
                        foreach (ModDownloadItem item in await Task.Run((Func<IEnumerable<ModDownloadItem>>)ProcessPageResult))
{
                            yield return item;
                        }
                        goto IL_02f0;
                        end_IL_0088:;
                    }
                    finally
                    {
                        ReleaseWorkshopQuery();
                    }
                    goto IL_02f7;
                    IL_02f0:
                    currentPageAttempts = 0;
                    goto IL_02f7;
                    IL_02f7:
                    num = currentPage + 1;
                    currentPage = num;
                }
                while (num <= numberPages);
            }
References Terraria.Social.Steam.SteamedWraps.GenerateAndSubmitModBrowserQuery(), Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.numberPages, Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.ProcessPageResult(), Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.queryParameters, Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.ReleaseWorkshopQuery(), and Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.WaitForQueryResultAsync().