TModLoader: Terraria.ModLoader.UI.UIModPacks.OnActivate
OnActivate()
override void Terraria.ModLoader.UI.UIModPacks.OnActivate () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 256 of file UIModPacks.cs.
    {
        _cts = new CancellationTokenSource();
        _scrollPanel.Append(_uiLoader);
        _modPacks.Clear();
        Task.Run(delegate
        {
            Directory.CreateDirectory(ModPacksDirectory);
            string[] directories = Directory.GetDirectories(ModPacksDirectory, "*", SearchOption.TopDirectoryOnly);
            string[] files = Directory.GetFiles(ModPacksDirectory, "*.json", SearchOption.TopDirectoryOnly);
            List<UIElement> ModPacksToAdd = new List<UIElement>();
            foreach (string current in files.Concat(directories))
            {
                try
                {
                    if (!IsValidModpackName(Path.GetFileNameWithoutExtension(current)))
                    {
                        throw new Exception();
                    }
                    if (Directory.Exists(current))
                    {
                        ModPacksToAdd.Add(LoadModernModPack(current));
                    }
                    else
                    {
                        ModPacksToAdd.Add(LoadLegacyModPack(current));
                    }
                }
                catch
                {
                    UIAutoScaleTextTextPanel<string> item = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.ModPackMalformed", Path.GetFileName(current)))
                    {
                        Width =
{
                            Percent = 1f
                        },
                        Height =
{
                            Pixels = 50f,
                            Percent = 0f
                        }
                    };
                    ModPacksToAdd.Add(item);
                }
            }
            Main.QueueMainThreadAction(delegate
            {
                _modPacks.AddRange(ModPacksToAdd);
                _scrollPanel.RemoveChild(_uiLoader);
            });
        });
    }
References Terraria.ModLoader.UI.UIModPacks._cts, Terraria.ModLoader.UI.UIModPacks._modPacks, Terraria.ModLoader.UI.UIModPacks._scrollPanel, Terraria.ModLoader.UI.UIModPacks._uiLoader, Terraria.GameContent.UI.Elements.UIList.AddRange(), Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.Height, Terraria.ModLoader.UI.UIModPacks.IsValidModpackName(), Terraria.ModLoader.UI.UIModPacks.LoadLegacyModPack(), Terraria.ModLoader.UI.UIModPacks.LoadModernModPack(), Terraria.ModLoader.UI.UIModPacks.ModPacksDirectory, Terraria.Main.QueueMainThreadAction(), Terraria.UI.UIElement.RemoveChild(), and Terraria.UI.UIElement.Width.