TModLoader: Terraria.ModLoader.UI.UIModPacks.ExportSnapshot
ExportSnapshot()
static void Terraria.ModLoader.UI.UIModPacks.ExportSnapshot (string modPackName) inline static
    {
        string instancePath = Path.Combine(Directory.GetCurrentDirectory(), modPackName);
        Directory.CreateDirectory(instancePath);
        Directory.CreateDirectory(Path.Combine(instancePath, "SaveData"));
        string sourcePath = ModPackModsPath(modPackName);
        string configPath = ConfigManager.ModConfigPath;
        FileUtilities.CopyFolder(sourcePath, Path.Combine(instancePath, "SaveData", "Mods"));
        FileUtilities.CopyFolder(configPath, Path.Combine(instancePath, "SaveData", "ModConfigs"));
        File.WriteAllText(Path.Combine(instancePath, "cli-argsConfig.txt"), "-tmlsavedirectory " + Path.Combine(instancePath, "SaveData") + "\n-steamworkshopfolder none");
        Logging.tML.Info((object)("Exported instance of Frozen Mod Pack " + modPackName + " to " + instancePath));
        Utils.OpenFolder(instancePath);
    }
References Terraria.Utilities.FileUtilities.CopyFolder(), Terraria.ModLoader.Config.ConfigManager.ModConfigPath, Terraria.ModLoader.UI.UIModPacks.ModPackModsPath(), Terraria.Utils.OpenFolder(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.ModLoader.UI.UIModPackItem.ExportInstance().