TModLoader: Terraria.ModLoader.UI.UIModPacks.OnDeactivate
OnDeactivate()
override void Terraria.ModLoader.UI.UIModPacks.OnDeactivate () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 249 of file UIModPacks.cs.
    {
        _cts?.Cancel(throwOnFirstException: false);
        _cts?.Dispose();
        _cts = null;
    }
References Terraria.ModLoader.UI.UIModPacks._cts.
Referenced by Terraria.ModLoader.UI.UIModPackItem.DeleteButtonClick(), Terraria.ModLoader.UI.UIModPackItem.DeleteInstance(), Terraria.ModLoader.UI.UIModPackItem.ExportInstance(), and Terraria.ModLoader.UI.UIModPackItem.UpdateModPack().