TModLoader: Terraria.ModLoader.UI.UIModPacks.ModPacksDirectory
ModPacksDirectory
string Terraria.ModLoader.UI.UIModPacks.ModPacksDirectory = Path.Combine(ModLoader.ModPath, "ModPacks") static package
Referenced by Terraria.ModLoader.Core.ModOrganizer.CommandLineModPackOverride(), Terraria.ModLoader.UI.UIModPackItem.DeleteButtonClick(), Terraria.ModLoader.UI.UIModPacks.ModPackConfigPath(), Terraria.ModLoader.UI.UIModPacks.ModPackModsPath(), Terraria.ModLoader.UI.UIModPacks.OnActivate(), and Terraria.ModLoader.UI.UIModPacks.OpenFolder().