TModLoader: Terraria.ModLoader.UI.UIModPacks.SaveSnapshot
SaveSnapshot()
static void Terraria.ModLoader.UI.UIModPacks.SaveSnapshot (string configsPath, string modsPath) inline static
Definition at line 328 of file UIModPacks.cs.
    {
        if (!Directory.Exists(ConfigManager.ModConfigPath))
        {
            Directory.CreateDirectory(ConfigManager.ModConfigPath);
        }
        Directory.CreateDirectory(configsPath);
        Directory.CreateDirectory(modsPath);
        Directory.EnumerateFiles(ConfigManager.ModConfigPath);
        File.Copy(Path.Combine(ModOrganizer.modPath, "enabled.json"), Path.Combine(modsPath, "enabled.json"), overwrite: true);
        File.WriteAllText(Path.Combine(modsPath, "tmlversion.txt"), BuildInfo.tMLVersion.ToString());
        List<string> workshopIds = new List<string>();
        Mod[] mods = ModLoader.Mods;
        foreach (Mod mod in mods)
        {
            if (mod.File != null)
            {
                if (ModOrganizer.TryReadManifest(ModOrganizer.GetParentDir(mod.File.path), out var info))
                {
                    workshopIds.Add(info.workshopEntryId.ToString());
                }
                if (mod.File.path != Path.Combine(modsPath, mod.Name + ".tmod"))
                {
                    File.Copy(mod.File.path, Path.Combine(modsPath, mod.Name + ".tmod"), overwrite: true);
                }
            }
        }
        File.WriteAllLines(Path.Combine(modsPath, "install.txt"), workshopIds);
    }
References Terraria.ModLoader.Mod.File, Terraria.ModLoader.Core.ModOrganizer.GetParentDir(), Terraria.ModLoader.Config.ConfigManager.ModConfigPath, Terraria.ModLoader.Core.ModOrganizer.modPath, Terraria.ModLoader.ModLoader.Mods, Terraria.ModLoader.Mod.Name, Terraria.ModLoader.Core.TmodFile.path, Terraria.ModLoader.BuildInfo.tMLVersion, and Terraria.ModLoader.Core.ModOrganizer.TryReadManifest().
Referenced by Terraria.ModLoader.UI.UIModPacks.SaveModPack().