TModLoader: Terraria.ModLoader.UI.UIModPacks.OnInitialize
OnInitialize()
override void Terraria.ModLoader.UI.UIModPacks.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
    {
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0198: Unknown result type (might be due to invalid IL or missing references)
        //IL_019d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0220: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_022a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0230: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02db: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0327: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_035d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0361: Unknown result type (might be due to invalid IL or missing references)
        //IL_0367: Unknown result type (might be due to invalid IL or missing references)
        //IL_036b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0371: Unknown result type (might be due to invalid IL or missing references)
        UIElement uIElement = new UIElement
        {
            Width =
            {
                Percent = 0.8f
            },
            MaxWidth = UICommon.MaxPanelWidth,
            Top =
            {
                Pixels = 220f
            },
            Height =
            {
                Pixels = -220f,
                Percent = 1f
            },
            HAlign = 0.5f
        };
        _uiLoader = new UILoaderAnimatedImage(0.5f, 0.5f);
        _scrollPanel = new UIPanel
        {
            Width =
            {
                Percent = 1f
            },
            Height =
            {
                Pixels = -65f,
                Percent = 0.9f
            },
            BackgroundColor = UICommon.MainPanelBackground
        };
        uIElement.Append(_scrollPanel);
        _modPacks = new UIList
        {
            Width =
            {
                Pixels = -25f,
                Percent = 1f
            },
            Height =
            {
                Percent = 0.9f
            },
            ListPadding = 5f
        };
        _scrollPanel.Append(_modPacks);
        UIScrollbar uIScrollbar = new UIScrollbar
        {
            Height =
            {
                Percent = 0.9f
            },
            HAlign = 1f
        }.WithView(100f, 1000f);
        _scrollPanel.Append(uIScrollbar);
        _modPacks.SetScrollbar(uIScrollbar);
        UITextPanel<LocalizedText> titleTextPanel = new UITextPanel<LocalizedText>(Language.GetText("tModLoader.ModPacksHeader"), 0.8f, large: true)
        {
            HAlign = 0.5f,
            Top =
            {
                Pixels = -35f
            },
            BackgroundColor = UICommon.DefaultUIBlue
        }.WithPadding(15f);
        uIElement.Append(titleTextPanel);
        UIAutoScaleTextTextPanel<LocalizedText> folderButton = new UIAutoScaleTextTextPanel<LocalizedText>(Language.GetText("tModLoader.OpenModPackFolder"))
        {
            Width = new StyleDimension(-10f, 0.5f),
            Height =
            {
                Pixels = 40f
            },
            VAlign = 0.9f,
            HAlign = 0f,
            Top =
            {
                Pixels = -20f
            }
        }.WithFadedMouseOver();
        folderButton.OnLeftClick += OpenFolder;
        uIElement.Append(folderButton);
        UIAutoScaleTextTextPanel<LocalizedText> backButton = new UIAutoScaleTextTextPanel<LocalizedText>(Language.GetText("UI.Back"))
        {
            Width = new StyleDimension(-10f, 0.5f),
            Height =
            {
                Pixels = 40f
            },
            VAlign = 1f,
            HAlign = 0f,
            Top =
            {
                Pixels = -20f
            }
        }.WithFadedMouseOver();
        backButton.OnLeftClick += BackClick;
        uIElement.Append(backButton);
        UIAutoScaleTextTextPanel<LocalizedText> saveNewButton = new UIAutoScaleTextTextPanel<LocalizedText>(Language.GetText("tModLoader.ModPacksSaveEnabledAsNewPack"));
        saveNewButton.CopyStyle(backButton);
        saveNewButton.TextColor = Color.Green;
        saveNewButton.VAlign = 1f;
        saveNewButton.HAlign = 1f;
        saveNewButton.WithFadedMouseOver();
        saveNewButton.OnLeftClick += SaveNewModList;
        uIElement.Append(saveNewButton);
        Append(uIElement);
    }
References Terraria.ModLoader.UI.UIModPacks._modPacks, Terraria.ModLoader.UI.UIModPacks._scrollPanel, Terraria.ModLoader.UI.UIModPacks._uiLoader, Terraria.UI.UIElement.Append(), Terraria.ModLoader.UI.UIModPacks.BackClick(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.ModLoader.UI.UICommon.MaxPanelWidth, Terraria.UI.UIElement.MaxWidth, Terraria.ModLoader.UI.UIModPacks.OpenFolder(), Terraria.ModLoader.UI.UIModPacks.SaveNewModList(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.