TModLoader: Terraria.GameContent.DoorOpeningHelper.TryGetHandler
TryGetHandler()
bool Terraria.GameContent.DoorOpeningHelper.TryGetHandler (Point tileCoords, out DoorAutoHandler infoProvider) inline private
    {
        //IL_0003: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        infoProvider = null;
        if (!WorldGen.InWorld(tileCoords.X, tileCoords.Y, 3))
        {
            return false;
        }
        Tile tile = Main.tile[tileCoords.X, tileCoords.Y];
        if (tile == null)
        {
            return false;
        }
        int type = tile.type;
        ModTile modTile = ModContent.GetModTile(type);
        if (modTile != null && TileID.Sets.OpenDoorID[modTile.Type] > -1)
        {
            type = 10;
        }
        return _handlerByTileType.TryGetValue(type, out infoProvider);
    }
References Terraria.GameContent.DoorOpeningHelper._handlerByTileType, Terraria.ModLoader.ModContent.GetModTile(), Terraria.WorldGen.InWorld(), Terraria.ID.TileID.Sets.OpenDoorID, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.GameContent.DoorOpeningHelper.TryAutoOpeningDoor().