TModLoader: Terraria.Audio.GStreamerAudioSupport.Init
Init()
static void Terraria.Audio.GStreamerAudioSupport.Init () inline static
Call this before loading the FAudio dll.
Definition at line 61 of file GStreamerAudioSupport.cs.
    {
        string gstreamer_dir = Path.Combine(Environment.CurrentDirectory, "Libraries", "Native", "Windows", "gstreamer");
        Environment.SetEnvironmentVariable("GST_REGISTRY", Path.Combine(gstreamer_dir, "registry"));
        Environment.SetEnvironmentVariable("GST_PLUGIN_PATH", Path.Combine(gstreamer_dir, "plugins"));
        if (Environment.OSVersion.Platform == PlatformID.Win32NT)
        {
            try
            {
                SetDefaultDllDirectories(4096);
                AddDllDirectory(gstreamer_dir);
            }
            catch
            {
                SetDllDirectory(gstreamer_dir);
            }
        }
    }
References Terraria.Audio.GStreamerAudioSupport.AddDllDirectory(), Terraria.Audio.GStreamerAudioSupport.SetDefaultDllDirectories(), and Terraria.Audio.GStreamerAudioSupport.SetDllDirectory().