TModLoader: Terraria.ModLoader.UI.UIErrorMessage.Show
Show()
void Terraria.ModLoader.UI.UIErrorMessage.Show (string message, int gotoMenu, UIState gotoState = null, string webHelpURL = "", bool continueIsRetry = false, bool showSkip = false, Action retryAction = null) inline package
Definition at line 224 of file UIErrorMessage.cs.
    {
        if (!Program.IsMainThread)
        {
            Main.QueueMainThreadAction(delegate
            {
                Show(message, gotoMenu, gotoState, webHelpURL, continueIsRetry, showSkip, retryAction);
            });
            return;
        }
        this.message = message;
        this.gotoMenu = gotoMenu;
        this.gotoState = gotoState;
        this.webHelpURL = webHelpURL;
        this.continueIsRetry = continueIsRetry;
        this.showSkip = showSkip;
        this.retryAction = retryAction;
        Main.gameMenu = true;
        Main.menuMode = 10005;
    }
References Terraria.ModLoader.UI.UIErrorMessage.continueIsRetry, Terraria.ModLoader.UI.UIErrorMessage.gotoMenu, Terraria.ModLoader.UI.UIErrorMessage.gotoState, Terraria.Program.IsMainThread, Terraria.ModLoader.UI.UIErrorMessage.message, Terraria.Main.QueueMainThreadAction(), Terraria.ModLoader.UI.UIErrorMessage.retryAction, Terraria.ModLoader.UI.UIErrorMessage.Show(), Terraria.ModLoader.UI.UIErrorMessage.showSkip, and Terraria.ModLoader.UI.UIErrorMessage.webHelpURL.
Referenced by Terraria.ModLoader.UI.UIBuildMod.BuildMod(), Terraria.ModLoader.ModLoader.DisplayLoadError(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadModsAndReturnToBrowser(), Terraria.ModLoader.ModNet.ReceiveMod(), Terraria.ModLoader.UI.UIErrorMessage.Show(), Terraria.Utils.ShowFancyErrorMessage(), and Terraria.ModLoader.ModNet.SyncClientMods().