TModLoader: Terraria.ModLoader.UI.UIErrorMessage.OnActivate
OnActivate()
override void Terraria.ModLoader.UI.UIErrorMessage.OnActivate () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 204 of file UIErrorMessage.cs.
    {
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        Netplay.Disconnect = true;
        messageBox.SetText(message);
        string continueKey = ((gotoMenu < 0) ? "Exit" : (continueIsRetry ? "Retry" : "Continue"));
        continueButton.SetText(Language.GetTextValue("tModLoader." + continueKey));
        continueButton.TextColor = ((gotoMenu >= 0) ? Color.White : Color.Red);
        area.AddOrRemoveChild(webHelpButton, !string.IsNullOrEmpty(webHelpURL));
        area.AddOrRemoveChild(skipLoadButton, showSkip);
        area.AddOrRemoveChild(exitAndDisableAllButton, gotoMenu < 0);
        area.AddOrRemoveChild(retryButton, retryAction != null);
    }
References Terraria.ModLoader.UI.UIErrorMessage.area, Terraria.ModLoader.UI.UIErrorMessage.continueButton, Terraria.ModLoader.UI.UIErrorMessage.continueIsRetry, Terraria.ModLoader.UI.UIErrorMessage.exitAndDisableAllButton, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.UIErrorMessage.gotoMenu, Terraria.ModLoader.UI.UIErrorMessage.message, Terraria.ModLoader.UI.UIErrorMessage.messageBox, Terraria.ModLoader.UI.UIErrorMessage.retryAction, Terraria.ModLoader.UI.UIErrorMessage.retryButton, Terraria.ModLoader.UI.UIMessageBox.SetText(), Terraria.GameContent.UI.Elements.UITextPanel< T >.SetText(), Terraria.ModLoader.UI.UIErrorMessage.showSkip, Terraria.ModLoader.UI.UIErrorMessage.skipLoadButton, Terraria.ModLoader.UI.UIErrorMessage.webHelpButton, and Terraria.ModLoader.UI.UIErrorMessage.webHelpURL.