TModLoader: Terraria.GameContent.Biomes.CaveHouse.HouseUtils.AreRoomsValid
AreRoomsValid()
static bool Terraria.GameContent.Biomes.CaveHouse.HouseUtils.AreRoomsValid (IEnumerable< Rectangle > rooms, StructureMap structures, HouseType style) inline static private
    {
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        foreach (Rectangle room in rooms)
        {
            if (style != HouseType.Granite && WorldUtils.Find(new Point(room.X - 2, room.Y - 2), Searches.Chain(new Searches.Rectangle(room.Width + 4, room.Height + 4).RequireAll(mode: false), new Conditions.HasLava()), out var _))
            {
                return false;
            }
            if (WorldGen.notTheBees)
            {
                if (!structures.CanPlace(room, BeelistedTiles, 5))
                {
                    return false;
                }
            }
            else if (!structures.CanPlace(room, BlacklistedTiles, 5))
            {
                return false;
            }
        }
        return true;
    }
References Terraria.GameContent.Biomes.CaveHouse.HouseUtils.BeelistedTiles, Terraria.GameContent.Biomes.CaveHouse.HouseUtils.BlacklistedTiles, Terraria.WorldBuilding.Searches.Chain(), Terraria.WorldBuilding.WorldUtils.Find(), Terraria.WorldGen.notTheBees, and Terraria.WorldBuilding.GenSearch.RequireAll().
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseUtils.CreateBuilder().