TModLoader: Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawCursors
DrawCursors()
void Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawCursors (SpriteBatch sb) inline private
        {
            //IL_0014: Unknown result type (might be due to invalid IL or missing references)
            //IL_001e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0023: Unknown result type (might be due to invalid IL or missing references)
            //IL_0028: Unknown result type (might be due to invalid IL or missing references)
            //IL_0029: Unknown result type (might be due to invalid IL or missing references)
            //IL_0036: Unknown result type (might be due to invalid IL or missing references)
            //IL_003b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0045: Unknown result type (might be due to invalid IL or missing references)
            //IL_004a: Unknown result type (might be due to invalid IL or missing references)
            //IL_004f: Unknown result type (might be due to invalid IL or missing references)
            //IL_006f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0074: Unknown result type (might be due to invalid IL or missing references)
            //IL_0079: Unknown result type (might be due to invalid IL or missing references)
            //IL_007b: Unknown result type (might be due to invalid IL or missing references)
            //IL_008e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0095: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
            //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
            //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
            //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
            //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
            //IL_00da: Unknown result type (might be due to invalid IL or missing references)
            //IL_00db: Unknown result type (might be due to invalid IL or missing references)
            //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
            //IL_0057: Unknown result type (might be due to invalid IL or missing references)
            //IL_0058: Unknown result type (might be due to invalid IL or missing references)
            //IL_005d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0062: Unknown result type (might be due to invalid IL or missing references)
            //IL_0063: Unknown result type (might be due to invalid IL or missing references)
            //IL_0064: Unknown result type (might be due to invalid IL or missing references)
            //IL_0069: Unknown result type (might be due to invalid IL or missing references)
            //IL_006e: Unknown result type (might be due to invalid IL or missing references)
            //IL_014f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0154: Unknown result type (might be due to invalid IL or missing references)
            //IL_0100: Unknown result type (might be due to invalid IL or missing references)
            //IL_0134: Unknown result type (might be due to invalid IL or missing references)
            //IL_0307: Unknown result type (might be due to invalid IL or missing references)
            //IL_030c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0160: Unknown result type (might be due to invalid IL or missing references)
            //IL_0165: Unknown result type (might be due to invalid IL or missing references)
            //IL_016f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0174: Unknown result type (might be due to invalid IL or missing references)
            //IL_03ea: Unknown result type (might be due to invalid IL or missing references)
            //IL_03f1: Unknown result type (might be due to invalid IL or missing references)
            //IL_036c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0373: Unknown result type (might be due to invalid IL or missing references)
            //IL_0383: Unknown result type (might be due to invalid IL or missing references)
            //IL_0388: Unknown result type (might be due to invalid IL or missing references)
            //IL_03a8: Unknown result type (might be due to invalid IL or missing references)
            //IL_03af: Unknown result type (might be due to invalid IL or missing references)
            //IL_03bf: Unknown result type (might be due to invalid IL or missing references)
            //IL_03c1: Unknown result type (might be due to invalid IL or missing references)
            //IL_03c6: Unknown result type (might be due to invalid IL or missing references)
            //IL_03c8: Unknown result type (might be due to invalid IL or missing references)
            //IL_03ca: Unknown result type (might be due to invalid IL or missing references)
            //IL_03cb: Unknown result type (might be due to invalid IL or missing references)
            //IL_03cc: Unknown result type (might be due to invalid IL or missing references)
            //IL_03d1: Unknown result type (might be due to invalid IL or missing references)
            //IL_03d3: Unknown result type (might be due to invalid IL or missing references)
            //IL_03d5: Unknown result type (might be due to invalid IL or missing references)
            //IL_03da: Unknown result type (might be due to invalid IL or missing references)
            //IL_03dc: Unknown result type (might be due to invalid IL or missing references)
            //IL_0258: Unknown result type (might be due to invalid IL or missing references)
            //IL_025a: Unknown result type (might be due to invalid IL or missing references)
            //IL_025c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0261: Unknown result type (might be due to invalid IL or missing references)
            //IL_0263: Unknown result type (might be due to invalid IL or missing references)
            //IL_0265: Unknown result type (might be due to invalid IL or missing references)
            //IL_0266: Unknown result type (might be due to invalid IL or missing references)
            //IL_0267: Unknown result type (might be due to invalid IL or missing references)
            //IL_026c: Unknown result type (might be due to invalid IL or missing references)
            //IL_026e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0273: Unknown result type (might be due to invalid IL or missing references)
            //IL_027d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0287: Unknown result type (might be due to invalid IL or missing references)
            //IL_028c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0291: Unknown result type (might be due to invalid IL or missing references)
            //IL_0293: Unknown result type (might be due to invalid IL or missing references)
            //IL_0298: Unknown result type (might be due to invalid IL or missing references)
            //IL_029a: Unknown result type (might be due to invalid IL or missing references)
            //IL_02a6: Unknown result type (might be due to invalid IL or missing references)
            //IL_02a8: Unknown result type (might be due to invalid IL or missing references)
            //IL_0183: Unknown result type (might be due to invalid IL or missing references)
            //IL_0185: Unknown result type (might be due to invalid IL or missing references)
            //IL_018f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0194: Unknown result type (might be due to invalid IL or missing references)
            //IL_0199: Unknown result type (might be due to invalid IL or missing references)
            //IL_019b: Unknown result type (might be due to invalid IL or missing references)
            //IL_019d: Unknown result type (might be due to invalid IL or missing references)
            //IL_019f: Unknown result type (might be due to invalid IL or missing references)
            //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
            //IL_01b2: Unknown result type (might be due to invalid IL or missing references)
            //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
            //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
            //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
            //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
            //IL_0474: Unknown result type (might be due to invalid IL or missing references)
            //IL_0479: Unknown result type (might be due to invalid IL or missing references)
            //IL_0429: Unknown result type (might be due to invalid IL or missing references)
            //IL_045d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0402: Unknown result type (might be due to invalid IL or missing references)
            //IL_0413: Unknown result type (might be due to invalid IL or missing references)
            //IL_0415: Unknown result type (might be due to invalid IL or missing references)
            //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
            //IL_02b3: Unknown result type (might be due to invalid IL or missing references)
            //IL_02b5: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e5: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e7: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
            //IL_01ee: Unknown result type (might be due to invalid IL or missing references)
            //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
            //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
            //IL_062e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0633: Unknown result type (might be due to invalid IL or missing references)
            //IL_0485: Unknown result type (might be due to invalid IL or missing references)
            //IL_048a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0494: Unknown result type (might be due to invalid IL or missing references)
            //IL_0499: Unknown result type (might be due to invalid IL or missing references)
            //IL_02d3: Unknown result type (might be due to invalid IL or missing references)
            //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
            //IL_02e6: Unknown result type (might be due to invalid IL or missing references)
            //IL_02eb: Unknown result type (might be due to invalid IL or missing references)
            //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
            //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
            //IL_0200: Unknown result type (might be due to invalid IL or missing references)
            //IL_0202: Unknown result type (might be due to invalid IL or missing references)
            //IL_0717: Unknown result type (might be due to invalid IL or missing references)
            //IL_071e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0699: Unknown result type (might be due to invalid IL or missing references)
            //IL_06a0: Unknown result type (might be due to invalid IL or missing references)
            //IL_06b0: Unknown result type (might be due to invalid IL or missing references)
            //IL_06b5: Unknown result type (might be due to invalid IL or missing references)
            //IL_06d5: Unknown result type (might be due to invalid IL or missing references)
            //IL_06dc: Unknown result type (might be due to invalid IL or missing references)
            //IL_06ec: Unknown result type (might be due to invalid IL or missing references)
            //IL_06ee: Unknown result type (might be due to invalid IL or missing references)
            //IL_06f3: Unknown result type (might be due to invalid IL or missing references)
            //IL_06f5: Unknown result type (might be due to invalid IL or missing references)
            //IL_06f7: Unknown result type (might be due to invalid IL or missing references)
            //IL_06f8: Unknown result type (might be due to invalid IL or missing references)
            //IL_06f9: Unknown result type (might be due to invalid IL or missing references)
            //IL_06fe: Unknown result type (might be due to invalid IL or missing references)
            //IL_0700: Unknown result type (might be due to invalid IL or missing references)
            //IL_0702: Unknown result type (might be due to invalid IL or missing references)
            //IL_0707: Unknown result type (might be due to invalid IL or missing references)
            //IL_0709: Unknown result type (might be due to invalid IL or missing references)
            //IL_0583: Unknown result type (might be due to invalid IL or missing references)
            //IL_0585: Unknown result type (might be due to invalid IL or missing references)
            //IL_0587: Unknown result type (might be due to invalid IL or missing references)
            //IL_058c: Unknown result type (might be due to invalid IL or missing references)
            //IL_058e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0590: Unknown result type (might be due to invalid IL or missing references)
            //IL_0591: Unknown result type (might be due to invalid IL or missing references)
            //IL_0592: Unknown result type (might be due to invalid IL or missing references)
            //IL_0597: Unknown result type (might be due to invalid IL or missing references)
            //IL_0599: Unknown result type (might be due to invalid IL or missing references)
            //IL_059e: Unknown result type (might be due to invalid IL or missing references)
            //IL_05a8: Unknown result type (might be due to invalid IL or missing references)
            //IL_05b2: Unknown result type (might be due to invalid IL or missing references)
            //IL_05b7: Unknown result type (might be due to invalid IL or missing references)
            //IL_05bc: Unknown result type (might be due to invalid IL or missing references)
            //IL_05be: Unknown result type (might be due to invalid IL or missing references)
            //IL_05c3: Unknown result type (might be due to invalid IL or missing references)
            //IL_05c5: Unknown result type (might be due to invalid IL or missing references)
            //IL_05d1: Unknown result type (might be due to invalid IL or missing references)
            //IL_05d3: Unknown result type (might be due to invalid IL or missing references)
            //IL_04a8: Unknown result type (might be due to invalid IL or missing references)
            //IL_04aa: Unknown result type (might be due to invalid IL or missing references)
            //IL_04b4: Unknown result type (might be due to invalid IL or missing references)
            //IL_04b9: Unknown result type (might be due to invalid IL or missing references)
            //IL_04be: Unknown result type (might be due to invalid IL or missing references)
            //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
            //IL_04c2: Unknown result type (might be due to invalid IL or missing references)
            //IL_04c4: Unknown result type (might be due to invalid IL or missing references)
            //IL_04c6: Unknown result type (might be due to invalid IL or missing references)
            //IL_04d7: Unknown result type (might be due to invalid IL or missing references)
            //IL_04e1: Unknown result type (might be due to invalid IL or missing references)
            //IL_04e6: Unknown result type (might be due to invalid IL or missing references)
            //IL_04eb: Unknown result type (might be due to invalid IL or missing references)
            //IL_04f0: Unknown result type (might be due to invalid IL or missing references)
            //IL_072f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0740: Unknown result type (might be due to invalid IL or missing references)
            //IL_0742: Unknown result type (might be due to invalid IL or missing references)
            //IL_05dc: Unknown result type (might be due to invalid IL or missing references)
            //IL_05de: Unknown result type (might be due to invalid IL or missing references)
            //IL_05e0: Unknown result type (might be due to invalid IL or missing references)
            //IL_050a: Unknown result type (might be due to invalid IL or missing references)
            //IL_050c: Unknown result type (might be due to invalid IL or missing references)
            //IL_050d: Unknown result type (might be due to invalid IL or missing references)
            //IL_050e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0513: Unknown result type (might be due to invalid IL or missing references)
            //IL_0515: Unknown result type (might be due to invalid IL or missing references)
            //IL_0517: Unknown result type (might be due to invalid IL or missing references)
            //IL_05fe: Unknown result type (might be due to invalid IL or missing references)
            //IL_060f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0611: Unknown result type (might be due to invalid IL or missing references)
            //IL_0616: Unknown result type (might be due to invalid IL or missing references)
            //IL_0620: Unknown result type (might be due to invalid IL or missing references)
            //IL_0523: Unknown result type (might be due to invalid IL or missing references)
            //IL_0525: Unknown result type (might be due to invalid IL or missing references)
            //IL_0527: Unknown result type (might be due to invalid IL or missing references)
            float num = 1f / Main.cursorScale;
            float num2 = 0.8f / num;
            Vector2 vector = Main.screenPosition + new Vector2(30f);
            Vector2 max = vector + new Vector2((float)Main.screenWidth, (float)Main.screenHeight) - new Vector2(60f);
            if (Main.mapFullscreen)
            {
                vector -= Main.screenPosition;
                max -= Main.screenPosition;
            }
            Vector3 vector2 = Main.rgbToHsl(Main.cursorColor);
            Color color = Main.hslToRgb((vector2.X + 0.33f) % 1f, vector2.Y, vector2.Z);
            Color color2 = Main.hslToRgb((vector2.X - 0.33f) % 1f, vector2.Y, vector2.Z);
            color = (color2 = Color.White);
            bool flag = Main.player[Main.myPlayer].gravDir == -1f;
            if (!EdgeAPinned)
            {
                Utils.DrawCursorSingle(sb, color, 3.926991f, Main.cursorScale * num * num2, new Vector2((float)Main.mouseX - 5f + 12f, (float)Main.mouseY + 2.5f + 12f), 4);
            }
            else
            {
                int specialMode = 0;
                float num3 = 0f;
                Vector2 zero = Vector2.Zero;
                if (!Main.mapFullscreen)
                {
                    Vector2 vector3 = EdgeA.ToVector2() * 16f;
                    if (!EdgeBPinned)
                    {
                        specialMode = 1;
                        vector3 += Vector2.One * 8f;
                        zero = vector3;
                        num3 = (-vector3 + Main.ReverseGravitySupport(new Vector2((float)Main.mouseX, (float)Main.mouseY), 0f) + Main.screenPosition).ToRotation();
                        if (flag)
{
                            num3 = 0f - num3;
                        }
                        zero = Vector2.Clamp(vector3, vector, max);
                        if (zero != vector3)
{
                            num3 = (vector3 - zero).ToRotation();
                        }
                    }
                    else
                    {
                        Vector2 vector4 = default(Vector2);
                        ((Vector2)(ref vector4))._002Ector((float)((EdgeA.X > EdgeB.X).ToInt() * 16), (float)((EdgeA.Y > EdgeB.Y).ToInt() * 16));
                        vector3 += vector4;
                        zero = Vector2.Clamp(vector3, vector, max);
                        num3 = (EdgeB.ToVector2() * 16f + new Vector2(16f) - vector4 - zero).ToRotation();
                        if (zero != vector3)
{
                            num3 = (vector3 - zero).ToRotation();
                            specialMode = 1;
                        }
                        if (flag)
{
                            num3 *= -1f;
                        }
                    }
                    Utils.DrawCursorSingle(sb, color, num3 - (float)Math.PI / 2f, Main.cursorScale * num, Main.ReverseGravitySupport(zero - Main.screenPosition), 4, specialMode);
                }
                else
                {
                    Point result = EdgeA;
                    if (EdgeBPinned)
                    {
                        int num4 = (EdgeA.X > EdgeB.X).ToInt();
                        int num5 = (EdgeA.Y > EdgeB.Y).ToInt();
                        result.X += num4;
                        result.Y += num5;
                        GetMapCoords(result.X, result.Y, 1, out result);
                        Point result2 = EdgeB;
                        result2.X += 1 - num4;
                        result2.Y += 1 - num5;
                        GetMapCoords(result2.X, result2.Y, 1, out result2);
                        zero = result.ToVector2();
                        zero = Vector2.Clamp(zero, vector, max);
                        num3 = (result2.ToVector2() - zero).ToRotation();
                    }
                    else
                    {
                        GetMapCoords(result.X, result.Y, 1, out result);
                    }
                    Utils.DrawCursorSingle(sb, color, num3 - (float)Math.PI / 2f, Main.cursorScale * num, result.ToVector2(), 4);
                }
            }
            if (!EdgeBPinned)
            {
                Utils.DrawCursorSingle(sb, color2, 0.7853981f, Main.cursorScale * num * num2, new Vector2((float)Main.mouseX + 2.5f + 12f, (float)Main.mouseY - 5f + 12f), 5);
                return;
            }
            int specialMode2 = 0;
            float num6 = 0f;
            Vector2 zero2 = Vector2.Zero;
            if (!Main.mapFullscreen)
            {
                Vector2 vector5 = EdgeB.ToVector2() * 16f;
                if (!EdgeAPinned)
                {
                    specialMode2 = 1;
                    vector5 += Vector2.One * 8f;
                    zero2 = vector5;
                    num6 = (-vector5 + Main.ReverseGravitySupport(new Vector2((float)Main.mouseX, (float)Main.mouseY), 0f) + Main.screenPosition).ToRotation();
                    if (flag)
                    {
                        num6 = 0f - num6;
                    }
                    zero2 = Vector2.Clamp(vector5, vector, max);
                    if (zero2 != vector5)
                    {
                        num6 = (vector5 - zero2).ToRotation();
                    }
                }
                else
                {
                    Vector2 vector6 = default(Vector2);
                    ((Vector2)(ref vector6))._002Ector((float)((EdgeB.X >= EdgeA.X).ToInt() * 16), (float)((EdgeB.Y >= EdgeA.Y).ToInt() * 16));
                    vector5 += vector6;
                    zero2 = Vector2.Clamp(vector5, vector, max);
                    num6 = (EdgeA.ToVector2() * 16f + new Vector2(16f) - vector6 - zero2).ToRotation();
                    if (zero2 != vector5)
                    {
                        num6 = (vector5 - zero2).ToRotation();
                        specialMode2 = 1;
                    }
                    if (flag)
                    {
                        num6 *= -1f;
                    }
                }
                Utils.DrawCursorSingle(sb, color2, num6 - (float)Math.PI / 2f, Main.cursorScale * num, Main.ReverseGravitySupport(zero2 - Main.screenPosition), 5, specialMode2);
            }
            else
            {
                Point result3 = EdgeB;
                if (EdgeAPinned)
                {
                    int num7 = (EdgeB.X >= EdgeA.X).ToInt();
                    int num8 = (EdgeB.Y >= EdgeA.Y).ToInt();
                    result3.X += num7;
                    result3.Y += num8;
                    GetMapCoords(result3.X, result3.Y, 1, out result3);
                    Point result4 = EdgeA;
                    result4.X += 1 - num7;
                    result4.Y += 1 - num8;
                    GetMapCoords(result4.X, result4.Y, 1, out result4);
                    zero2 = result3.ToVector2();
                    zero2 = Vector2.Clamp(zero2, vector, max);
                    num6 = (result4.ToVector2() - zero2).ToRotation();
                }
                else
                {
                    GetMapCoords(result3.X, result3.Y, 1, out result3);
                }
                Utils.DrawCursorSingle(sb, color2, num6 - (float)Math.PI / 2f, Main.cursorScale * num, result3.ToVector2(), 5);
            }
        }
References Terraria.Main.cursorColor, Terraria.Main.cursorScale, Terraria.Utils.DrawCursorSingle(), Terraria.Graphics.Capture.CaptureInterface.EdgeA, Terraria.Graphics.Capture.CaptureInterface.EdgeAPinned, Terraria.Graphics.Capture.CaptureInterface.EdgeB, Terraria.Graphics.Capture.CaptureInterface.EdgeBPinned, Terraria.Graphics.Capture.CaptureInterface.GetMapCoords(), Terraria.Main.hslToRgb(), Terraria.Main.mapFullscreen, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.ReverseGravitySupport(), Terraria.Main.rgbToHsl(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, and Terraria.Main.screenWidth.
Referenced by Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.Draw().