TModLoader: Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawMarkedArea
DrawMarkedArea()
void Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawMarkedArea (SpriteBatch sb) inline private
Definition at line 133 of file CaptureInterface.cs.
        {
            //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e4: Unknown result type (might be due to invalid IL or missing references)
            //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
            //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
            //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
            //IL_0201: Unknown result type (might be due to invalid IL or missing references)
            //IL_0230: Unknown result type (might be due to invalid IL or missing references)
            //IL_0097: Unknown result type (might be due to invalid IL or missing references)
            //IL_009c: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
            //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
            //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
            //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
            //IL_00de: Unknown result type (might be due to invalid IL or missing references)
            //IL_023c: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
            //IL_024a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0252: Unknown result type (might be due to invalid IL or missing references)
            //IL_026a: Unknown result type (might be due to invalid IL or missing references)
            //IL_026c: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
            //IL_0100: Unknown result type (might be due to invalid IL or missing references)
            //IL_0118: Unknown result type (might be due to invalid IL or missing references)
            //IL_011a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0289: Unknown result type (might be due to invalid IL or missing references)
            //IL_0290: Unknown result type (might be due to invalid IL or missing references)
            //IL_0137: Unknown result type (might be due to invalid IL or missing references)
            //IL_013e: Unknown result type (might be due to invalid IL or missing references)
            //IL_02a0: Unknown result type (might be due to invalid IL or missing references)
            //IL_014e: Unknown result type (might be due to invalid IL or missing references)
            //IL_02a8: Unknown result type (might be due to invalid IL or missing references)
            //IL_02b0: Unknown result type (might be due to invalid IL or missing references)
            //IL_02b5: Unknown result type (might be due to invalid IL or missing references)
            //IL_02ca: Unknown result type (might be due to invalid IL or missing references)
            //IL_0156: Unknown result type (might be due to invalid IL or missing references)
            //IL_015e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0163: Unknown result type (might be due to invalid IL or missing references)
            //IL_0178: Unknown result type (might be due to invalid IL or missing references)
            //IL_02da: Unknown result type (might be due to invalid IL or missing references)
            //IL_0188: Unknown result type (might be due to invalid IL or missing references)
            //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
            //IL_02ea: Unknown result type (might be due to invalid IL or missing references)
            //IL_02f1: Unknown result type (might be due to invalid IL or missing references)
            //IL_02f6: Unknown result type (might be due to invalid IL or missing references)
            //IL_0190: Unknown result type (might be due to invalid IL or missing references)
            //IL_0198: Unknown result type (might be due to invalid IL or missing references)
            //IL_019f: Unknown result type (might be due to invalid IL or missing references)
            //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
            if (!EdgeAPinned || !EdgeBPinned)
            {
                return;
            }
            int num = Math.Min(EdgeA.X, EdgeB.X);
            int num2 = Math.Min(EdgeA.Y, EdgeB.Y);
            int num3 = Math.Abs(EdgeA.X - EdgeB.X);
            int num4 = Math.Abs(EdgeA.Y - EdgeB.Y);
            if (!Main.mapFullscreen)
            {
                Rectangle value = Main.ReverseGravitySupport(new Rectangle(num * 16, num2 * 16, (num3 + 1) * 16, (num4 + 1) * 16));
                Rectangle value2 = Main.ReverseGravitySupport(new Rectangle((int)Main.screenPosition.X, (int)Main.screenPosition.Y, Main.screenWidth + 1, Main.screenHeight + 1));
                Rectangle result = default(Rectangle);
                Rectangle.Intersect(ref value2, ref value, ref result);
                if (result.Width != 0 && result.Height != 0)
                {
                    ((Rectangle)(ref result)).Offset(-value2.X, -value2.Y);
                    sb.Draw(TextureAssets.MagicPixel.Value, result, Settings.MarkedAreaColor);
                    for (int i = 0; i < 2; i++)
                    {
                        sb.Draw(TextureAssets.MagicPixel.Value, new Rectangle(result.X, result.Y + ((i == 1) ? result.Height : (-2)), result.Width, 2), Color.White);
                        sb.Draw(TextureAssets.MagicPixel.Value, new Rectangle(result.X + ((i == 1) ? result.Width : (-2)), result.Y, 2, result.Height), Color.White);
                    }
                }
                return;
            }
            GetMapCoords(num, num2, 1, out var result2);
            GetMapCoords(num + num3 + 1, num2 + num4 + 1, 1, out var result3);
            Rectangle value3 = default(Rectangle);
            ((Rectangle)(ref value3))._002Ector(result2.X, result2.Y, result3.X - result2.X, result3.Y - result2.Y);
            Rectangle value4 = default(Rectangle);
            ((Rectangle)(ref value4))._002Ector(0, 0, Main.screenWidth + 1, Main.screenHeight + 1);
            Rectangle result4 = default(Rectangle);
            Rectangle.Intersect(ref value4, ref value3, ref result4);
            if (result4.Width != 0 && result4.Height != 0)
            {
                ((Rectangle)(ref result4)).Offset(-value4.X, -value4.Y);
                sb.Draw(TextureAssets.MagicPixel.Value, result4, Settings.MarkedAreaColor);
                for (int j = 0; j < 2; j++)
                {
                    sb.Draw(TextureAssets.MagicPixel.Value, new Rectangle(result4.X, result4.Y + ((j == 1) ? result4.Height : (-2)), result4.Width, 2), Color.White);
                    sb.Draw(TextureAssets.MagicPixel.Value, new Rectangle(result4.X + ((j == 1) ? result4.Width : (-2)), result4.Y, 2, result4.Height), Color.White);
                }
            }
        }
References Terraria.Graphics.Capture.CaptureInterface.EdgeA, Terraria.Graphics.Capture.CaptureInterface.EdgeAPinned, Terraria.Graphics.Capture.CaptureInterface.EdgeB, Terraria.Graphics.Capture.CaptureInterface.EdgeBPinned, Terraria.Graphics.Capture.CaptureInterface.GetMapCoords(), Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.mapFullscreen, Terraria.Graphics.Capture.CaptureInterface.Settings.MarkedAreaColor, Terraria.Main.ReverseGravitySupport(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, and Terraria.Main.screenWidth.
Referenced by Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.Draw().