TModLoader: Terraria.Utilities.NPCUtils.TargetClosestOldOnesInvasion
TargetClosestOldOnesInvasion()
static void Terraria.Utilities.NPCUtils.TargetClosestOldOnesInvasion (NPC searcher, bool faceTarget = true, Vector2? checkPosition = null) inline static
Definition at line 279 of file NPCUtils.cs.
    {
        //IL_0003: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        TargetSearchResults searchResults = SearchForTarget(searcher, TargetSearchFlag.All, SearchFilters.OnlyPlayersInCertainDistance(searcher.Center, 200f), SearchFilters.OnlyCrystal);
        if (searchResults.FoundTarget)
        {
            searcher.target = searchResults.NearestTargetIndex;
            searcher.targetRect = searchResults.NearestTargetHitbox;
            if (searcher.ShouldFaceTarget(ref searchResults) && faceTarget)
            {
                searcher.FaceTarget();
            }
        }
    }
References Terraria.Utilities.NPCUtils.SearchFilters.OnlyCrystal(), Terraria.Utilities.NPCUtils.SearchFilters.OnlyPlayersInCertainDistance(), and Terraria.Utilities.NPCUtils.SearchForTarget().
Referenced by Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_109_DarkMage(), and Terraria.NPC.AI_111_DD2LightningBug().