TModLoader: Terraria.ModLoader.BuilderToggleLoader.ActiveBuilderTogglesList
ActiveBuilderTogglesList()
static List< BuilderToggle > Terraria.ModLoader.BuilderToggleLoader.ActiveBuilderTogglesList () inline static package
    {
        List<BuilderToggle> activeToggles = new List<BuilderToggle>(BuilderToggleCount);
        for (int i = 0; i < BuilderToggles.Count; i++)
        {
            if (BuilderToggles[i].Active())
            {
                activeToggles.Add(BuilderToggles[i]);
            }
        }
        return activeToggles;
    }
References Terraria.ModLoader.BuilderToggleLoader.Active(), Terraria.ModLoader.BuilderToggleLoader.BuilderToggleCount, and Terraria.ModLoader.BuilderToggleLoader.BuilderToggles.
Referenced by Terraria.ModLoader.BuilderToggleLoader.ActiveBuilderToggles(), and Terraria.Main.DrawBuilderAccToggles_Inner().