TModLoader: Terraria.ModLoader.IO.TagIO.Serialize
Serialize()
static object Terraria.ModLoader.IO.TagIO.Serialize (object value) inline static
    {
        ArgumentNullException.ThrowIfNull(value, "value");
        if (value is string || value is int || value is TagCompound || value is List<TagCompound>)
        {
            return value;
        }
        Type type = value.GetType();
        if (TagSerializer.TryGetSerializer(type, out TagSerializer serializer))
        {
            return serializer.Serialize(value);
        }
        if (GetPayloadId(type) != 9)
        {
            return value;
        }
        IList list = (IList)value;
        Type elemType = type.GetElementType() ?? type.GetGenericArguments()[0];
        if (TagSerializer.TryGetSerializer(elemType, out serializer))
        {
            return serializer.SerializeList(list);
        }
        if (GetPayloadId(elemType) != 9)
        {
            return list;
        }
        List<IList> serializedList = new List<IList>(list.Count);
        foreach (object elem in list)
        {
            serializedList.Add((IList)Serialize(elem));
        }
        return serializedList;
    }
References Terraria.ModLoader.IO.TagIO.GetPayloadId(), Terraria.ModLoader.IO.TagIO.Serialize(), and Terraria.ModLoader.IO.TagSerializer< T, S >.TryGetSerializer().
Referenced by Terraria.ModLoader.IO.MultiDimArraySerializer.Serialize(), Terraria.ModLoader.IO.TagIO.Serialize(), and Terraria.ModLoader.IO.TagCompound.Set().