TModLoader: Terraria.ModLoader.IO.TagIO.Deserialize
Deserialize()
static object Terraria.ModLoader.IO.TagIO.Deserialize (Type type, object? tag) inline static
    {
        ArgumentNullException.ThrowIfNull(type, "type");
        if (type.IsInstanceOfType(tag))
        {
            return tag;
        }
        if (TagSerializer.TryGetSerializer(type, out TagSerializer serializer))
        {
            if (tag == null)
            {
                tag = Deserialize(serializer.TagType, null);
            }
            return serializer.Deserialize(tag);
        }
        if (tag == null && !type.IsArray)
        {
            if (type.GetGenericArguments().Length == 0)
            {
                return GetHandler(GetPayloadId(type)).Default();
            }
            if (type.GetGenericTypeDefinition() == typeof(Nullable<>))
            {
                return Activator.CreateInstance(type);
            }
        }
        if (tag == null || tag is IList || type.IsArray)
        {
            if (type.IsArray)
            {
                Type elemType = type.GetElementType();
                if (tag == null)
                {
                    return Array.CreateInstance(elemType, 0);
                }
                IList serializedList = (IList)tag;
                if (TagSerializer.TryGetSerializer(elemType, out serializer))
                {
                    IList array = Array.CreateInstance(elemType, serializedList.Count);
                    for (int i = 0; i < serializedList.Count; i++)
                    {
                        array[i] = serializer.Deserialize(serializedList[i]);
                    }
                    return array;
                }
                IList deserializedArray = Array.CreateInstance(elemType, serializedList.Count);
                for (int j = 0; j < serializedList.Count; j++)
                {
                    deserializedArray[j] = Deserialize(elemType, serializedList[j]);
                }
                return deserializedArray;
            }
            if (type.GetGenericArguments().Length == 1)
            {
                Type elemType2 = type.GetGenericArguments()[0];
                Type newListType = typeof(List<>).MakeGenericType(elemType2);
                if (type.IsAssignableFrom(newListType))
                {
                    if (tag == null)
                    {
                        return Activator.CreateInstance(newListType);
                    }
                    if (TagSerializer.TryGetSerializer(elemType2, out serializer))
                    {
                        return serializer.DeserializeList((IList)tag);
                    }
                    IList oldList = (IList)tag;
                    IList newList = (IList)Activator.CreateInstance(newListType, oldList.Count);
                    {
                        foreach (object elem in oldList)
{
                            newList.Add(Deserialize(elemType2, elem));
                        }
                        return newList;
                    }
                }
            }
        }
        if (tag == null)
        {
            throw new IOException($"Invalid NBT payload type '{type}'");
        }
        throw new InvalidCastException($"Unable to cast object of type '{tag.GetType()}' to type '{type}'");
    }
References Terraria.ModLoader.IO.TagIO.PayloadHandler< T >.Default(), Terraria.ModLoader.IO.TagIO.Deserialize(), Terraria.ModLoader.IO.TagIO.GetHandler(), Terraria.ModLoader.IO.TagIO.GetPayloadId(), and Terraria.ModLoader.IO.TagSerializer< T, S >.TryGetSerializer().
Referenced by Terraria.ModLoader.IO.MultiDimArraySerializer.Deserialize(), Terraria.ModLoader.IO.TagIO.Deserialize(), Terraria.ModLoader.IO.TagIO.Deserialize< T >(), Terraria.ModLoader.IO.TagCompound.Get< T >(), and Terraria.ModLoader.IO.TagCompound.TryGet< T >().