TModLoader: Terraria.ModLoader.Default.UnloadedChest.SetStaticDefaults
SetStaticDefaults()
override void Terraria.ModLoader.Default.UnloadedChest.SetStaticDefaults () inline virtual
Allows you to modify the properties after initial loading has completed.
Reimplemented from Terraria.ModLoader.ModType< TEntity, TModType >.
    {
        //IL_00da: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        TileIO.Tiles.unloadedTypes.Add(base.Type);
        Main.tileFrameImportant[base.Type] = true;
        TileID.Sets.DisableSmartCursor[base.Type] = true;
        Main.tileSolid[base.Type] = false;
        Main.tileNoAttach[base.Type] = true;
        TileID.Sets.BasicChest[base.Type] = true;
        TileObjectData.newTile.CopyFrom(TileObjectData.Style2x2);
        TileObjectData.addTile(base.Type);
        Main.tileSpelunker[base.Type] = true;
        Main.tileContainer[base.Type] = true;
        Main.tileShine2[base.Type] = true;
        Main.tileShine[base.Type] = 1200;
        Main.tileOreFinderPriority[base.Type] = 500;
        base.AdjTiles = new int[1] { 21 };
        AddMapEntry(new Color(200, 200, 200), this.GetLocalization("MapEntry0"), MapChestName);
        AddMapEntry(new Color(0, 141, 63), this.GetLocalization("MapEntry1"), MapChestName);
    }
References Terraria.ModLoader.ModTile.AddMapEntry(), Terraria.ObjectData.TileObjectData.addTile(), Terraria.ID.TileID.Sets.BasicChest, Terraria.ObjectData.TileObjectData.CopyFrom(), Terraria.ID.TileID.Sets.DisableSmartCursor, Terraria.ModLoader.Default.UnloadedChest.MapChestName(), Terraria.ObjectData.TileObjectData.newTile, Terraria.ObjectData.TileObjectData.Style2x2, Terraria.Main.tileContainer, Terraria.Main.tileFrameImportant, Terraria.Main.tileNoAttach, Terraria.Main.tileOreFinderPriority, Terraria.ModLoader.IO.TileIO.Tiles, Terraria.Main.tileShine, Terraria.Main.tileShine2, Terraria.Main.tileSolid, Terraria.Main.tileSpelunker, and Terraria.ModLoader.IO.TileIO.IOImpl< TBlock, TEntry >.unloadedTypes.