TModLoader: Terraria.GameContent.UI.Elements.UISearchBar.SetContents
SetContents()
void Terraria.GameContent.UI.Elements.UISearchBar.SetContents (string contents, bool forced = false) inline
    {
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        if (!(actualContents == contents) || forced)
        {
            actualContents = contents;
            if (string.IsNullOrEmpty(actualContents))
            {
                _text.TextColor = Color.Gray;
                _text.SetText(_textToShowWhenEmpty.Value, _textScale, large: false);
            }
            else
            {
                _text.TextColor = Color.White;
                _text.SetText(actualContents);
                actualContents = _text.Text;
            }
            TrimDisplayIfOverElementDimensions(0);
            if (this.OnContentsChanged != null)
            {
                this.OnContentsChanged(contents);
            }
        }
    }
References Terraria.GameContent.UI.Elements.UISearchBar._text, Terraria.GameContent.UI.Elements.UISearchBar._textScale, Terraria.GameContent.UI.Elements.UISearchBar._textToShowWhenEmpty, Terraria.GameContent.UI.Elements.UISearchBar.actualContents, Terraria.GameContent.UI.Elements.UISearchBar.OnContentsChanged, Terraria.GameContent.UI.Elements.UITextBox.SetText(), Terraria.GameContent.UI.Elements.UITextPanel< T >.Text, and Terraria.GameContent.UI.Elements.UISearchBar.TrimDisplayIfOverElementDimensions().
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildInfinitesMenuContents(), Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage(), Terraria.GameContent.UI.Elements.UISearchBar.DrawSelf(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.OnFinishedSettingName(), Terraria.GameContent.UI.States.UIBestiaryTest.OnFinishedSettingName(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.searchCancelButton_OnClick(), and Terraria.GameContent.UI.States.UIBestiaryTest.searchCancelButton_OnClick().