TModLoader: Terraria.Initializers.DyeInitializer.LoadLegacyHairdyes
LoadLegacyHairdyes()
static void Terraria.Initializers.DyeInitializer.LoadLegacyHairdyes () inline static private
    {
        _ = Main.PixelShaderRef;
        GameShaders.Hair.BindShader(1977, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
        {
            //IL_0035: Unknown result type (might be due to invalid IL or missing references)
            ((Color)(ref newColor)).R = (byte)((float)player.statLife / (float)player.statLifeMax2 * 235f + 20f);
            ((Color)(ref newColor)).B = 20;
            ((Color)(ref newColor)).G = 20;
            return newColor;
        }));
        GameShaders.Hair.BindShader(1978, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
        {
            //IL_005e: Unknown result type (might be due to invalid IL or missing references)
            ((Color)(ref newColor)).R = (byte)((1f - (float)player.statMana / (float)player.statManaMax2) * 200f + 50f);
            ((Color)(ref newColor)).B = byte.MaxValue;
            ((Color)(ref newColor)).G = (byte)((1f - (float)player.statMana / (float)player.statManaMax2) * 180f + 75f);
            return newColor;
        }));
        GameShaders.Hair.BindShader(1979, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
        {
            //IL_0052: Unknown result type (might be due to invalid IL or missing references)
            //IL_0057: Unknown result type (might be due to invalid IL or missing references)
            //IL_0059: Unknown result type (might be due to invalid IL or missing references)
            //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
            //IL_0063: Unknown result type (might be due to invalid IL or missing references)
            //IL_0140: Unknown result type (might be due to invalid IL or missing references)
            //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
            //IL_024b: Unknown result type (might be due to invalid IL or missing references)
            //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
            //IL_014d: Unknown result type (might be due to invalid IL or missing references)
            //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
            float num27 = (float)(Main.worldSurface * 0.45) * 16f;
            float num28 = (float)(Main.worldSurface + Main.rockLayer) * 8f;
            float num29 = (float)(Main.rockLayer + (double)Main.maxTilesY) * 8f;
            float num30 = (float)(Main.maxTilesY - 150) * 16f;
            Vector2 center = player.Center;
            if (center.Y < num27)
            {
                float num31 = center.Y / num27;
                float num32 = 1f - num31;
                ((Color)(ref newColor)).R = (byte)(116f * num32 + 28f * num31);
                ((Color)(ref newColor)).G = (byte)(160f * num32 + 216f * num31);
                ((Color)(ref newColor)).B = (byte)(249f * num32 + 94f * num31);
            }
            else if (center.Y < num28)
            {
                float num33 = num27;
                float num34 = (center.Y - num33) / (num28 - num33);
                float num35 = 1f - num34;
                ((Color)(ref newColor)).R = (byte)(28f * num35 + 151f * num34);
                ((Color)(ref newColor)).G = (byte)(216f * num35 + 107f * num34);
                ((Color)(ref newColor)).B = (byte)(94f * num35 + 75f * num34);
            }
            else if (center.Y < num29)
            {
                float num36 = num28;
                float num37 = (center.Y - num36) / (num29 - num36);
                float num38 = 1f - num37;
                ((Color)(ref newColor)).R = (byte)(151f * num38 + 128f * num37);
                ((Color)(ref newColor)).G = (byte)(107f * num38 + 128f * num37);
                ((Color)(ref newColor)).B = (byte)(75f * num38 + 128f * num37);
            }
            else if (center.Y < num30)
            {
                float num39 = num29;
                float num40 = (center.Y - num39) / (num30 - num39);
                float num41 = 1f - num40;
                ((Color)(ref newColor)).R = (byte)(128f * num41 + 255f * num40);
                ((Color)(ref newColor)).G = (byte)(128f * num41 + 50f * num40);
                ((Color)(ref newColor)).B = (byte)(128f * num41 + 15f * num40);
            }
            else
            {
                ((Color)(ref newColor)).R = byte.MaxValue;
                ((Color)(ref newColor)).G = 50;
                ((Color)(ref newColor)).B = 10;
            }
            return newColor;
        }));
        GameShaders.Hair.BindShader(1980, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
        {
            //IL_02ba: Unknown result type (might be due to invalid IL or missing references)
            //IL_02b6: Unknown result type (might be due to invalid IL or missing references)
            //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
            long num15 = 0L;
            for (int i = 0; i < 54; i++)
            {
                if (player.inventory[i].type == 71)
                {
                    num15 += player.inventory[i].stack;
                }
                if (player.inventory[i].type == 72)
                {
                    num15 += (long)player.inventory[i].stack * 100L;
                }
                if (player.inventory[i].type == 73)
                {
                    num15 += (long)player.inventory[i].stack * 10000L;
                }
                if (player.inventory[i].type == 74)
                {
                    num15 += (long)player.inventory[i].stack * 1000000L;
                }
            }
            if (num15 < 0 || num15 > 999999999)
            {
                num15 = 999999999L;
            }
            float num16 = Item.buyPrice(0, 5);
            float num17 = Item.buyPrice(0, 50);
            float num18 = Item.buyPrice(2);
            Color val7 = default(Color);
            ((Color)(ref val7))._002Ector(226, 118, 76);
            Color val8 = default(Color);
            ((Color)(ref val8))._002Ector(174, 194, 196);
            Color val9 = default(Color);
            ((Color)(ref val9))._002Ector(204, 181, 72);
            Color val10 = default(Color);
            ((Color)(ref val10))._002Ector(161, 172, 173);
            if ((float)num15 < num16)
            {
                float num19 = (float)num15 / num16;
                float num20 = 1f - num19;
                ((Color)(ref newColor)).R = (byte)((float)(int)((Color)(ref val7)).R * num20 + (float)(int)((Color)(ref val8)).R * num19);
                ((Color)(ref newColor)).G = (byte)((float)(int)((Color)(ref val7)).G * num20 + (float)(int)((Color)(ref val8)).G * num19);
                ((Color)(ref newColor)).B = (byte)((float)(int)((Color)(ref val7)).B * num20 + (float)(int)((Color)(ref val8)).B * num19);
            }
            else if ((float)num15 < num17)
            {
                float num21 = num16;
                float num22 = ((float)num15 - num21) / (num17 - num21);
                float num23 = 1f - num22;
                ((Color)(ref newColor)).R = (byte)((float)(int)((Color)(ref val8)).R * num23 + (float)(int)((Color)(ref val9)).R * num22);
                ((Color)(ref newColor)).G = (byte)((float)(int)((Color)(ref val8)).G * num23 + (float)(int)((Color)(ref val9)).G * num22);
                ((Color)(ref newColor)).B = (byte)((float)(int)((Color)(ref val8)).B * num23 + (float)(int)((Color)(ref val9)).B * num22);
            }
            else if ((float)num15 < num18)
            {
                float num24 = num17;
                float num25 = ((float)num15 - num24) / (num18 - num24);
                float num26 = 1f - num25;
                ((Color)(ref newColor)).R = (byte)((float)(int)((Color)(ref val9)).R * num26 + (float)(int)((Color)(ref val10)).R * num25);
                ((Color)(ref newColor)).G = (byte)((float)(int)((Color)(ref val9)).G * num26 + (float)(int)((Color)(ref val10)).G * num25);
                ((Color)(ref newColor)).B = (byte)((float)(int)((Color)(ref val9)).B * num26 + (float)(int)((Color)(ref val10)).B * num25);
            }
            else
            {
                newColor = val10;
            }
            return newColor;
        }));
        GameShaders.Hair.BindShader(1981, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
        {
            //IL_027c: Unknown result type (might be due to invalid IL or missing references)
            Color val3 = default(Color);
            ((Color)(ref val3))._002Ector(1, 142, 255);
            Color val4 = default(Color);
            ((Color)(ref val4))._002Ector(255, 255, 0);
            Color val5 = default(Color);
            ((Color)(ref val5))._002Ector(211, 45, 127);
            Color val6 = default(Color);
            ((Color)(ref val6))._002Ector(67, 44, 118);
            if (Main.dayTime)
            {
                if (Main.time < 27000.0)
                {
                    float num5 = (float)(Main.time / 27000.0);
                    float num6 = 1f - num5;
                    ((Color)(ref newColor)).R = (byte)((float)(int)((Color)(ref val3)).R * num6 + (float)(int)((Color)(ref val4)).R * num5);
                    ((Color)(ref newColor)).G = (byte)((float)(int)((Color)(ref val3)).G * num6 + (float)(int)((Color)(ref val4)).G * num5);
                    ((Color)(ref newColor)).B = (byte)((float)(int)((Color)(ref val3)).B * num6 + (float)(int)((Color)(ref val4)).B * num5);
                }
                else
                {
                    float num7 = 27000f;
                    float num8 = (float)((Main.time - (double)num7) / (54000.0 - (double)num7));
                    float num9 = 1f - num8;
                    ((Color)(ref newColor)).R = (byte)((float)(int)((Color)(ref val4)).R * num9 + (float)(int)((Color)(ref val5)).R * num8);
                    ((Color)(ref newColor)).G = (byte)((float)(int)((Color)(ref val4)).G * num9 + (float)(int)((Color)(ref val5)).G * num8);
                    ((Color)(ref newColor)).B = (byte)((float)(int)((Color)(ref val4)).B * num9 + (float)(int)((Color)(ref val5)).B * num8);
                }
            }
            else if (Main.time < 16200.0)
            {
                float num10 = (float)(Main.time / 16200.0);
                float num11 = 1f - num10;
                ((Color)(ref newColor)).R = (byte)((float)(int)((Color)(ref val5)).R * num11 + (float)(int)((Color)(ref val6)).R * num10);
                ((Color)(ref newColor)).G = (byte)((float)(int)((Color)(ref val5)).G * num11 + (float)(int)((Color)(ref val6)).G * num10);
                ((Color)(ref newColor)).B = (byte)((float)(int)((Color)(ref val5)).B * num11 + (float)(int)((Color)(ref val6)).B * num10);
            }
            else
            {
                float num12 = 16200f;
                float num13 = (float)((Main.time - (double)num12) / (32400.0 - (double)num12));
                float num14 = 1f - num13;
                ((Color)(ref newColor)).R = (byte)((float)(int)((Color)(ref val6)).R * num14 + (float)(int)((Color)(ref val3)).R * num13);
                ((Color)(ref newColor)).G = (byte)((float)(int)((Color)(ref val6)).G * num14 + (float)(int)((Color)(ref val3)).G * num13);
                ((Color)(ref newColor)).B = (byte)((float)(int)((Color)(ref val6)).B * num14 + (float)(int)((Color)(ref val3)).B * num13);
            }
            return newColor;
        }));
        GameShaders.Hair.BindShader(1982, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
        {
            //IL_002a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0023: Unknown result type (might be due to invalid IL or missing references)
            //IL_0028: Unknown result type (might be due to invalid IL or missing references)
            if (player.team >= 0 && player.team < Main.teamColor.Length)
            {
                newColor = Main.teamColor[player.team];
            }
            return newColor;
        }));
        GameShaders.Hair.BindShader(1983, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
        {
            //IL_0002: Unknown result type (might be due to invalid IL or missing references)
            //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
            //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
            //IL_0162: Unknown result type (might be due to invalid IL or missing references)
            //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
            //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
            //IL_0167: Unknown result type (might be due to invalid IL or missing references)
            //IL_0152: Unknown result type (might be due to invalid IL or missing references)
            //IL_0180: Unknown result type (might be due to invalid IL or missing references)
            //IL_0185: Unknown result type (might be due to invalid IL or missing references)
            //IL_013f: Unknown result type (might be due to invalid IL or missing references)
            //IL_012c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0116: Unknown result type (might be due to invalid IL or missing references)
            //IL_0103: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
            //IL_028a: Unknown result type (might be due to invalid IL or missing references)
            //IL_028b: Unknown result type (might be due to invalid IL or missing references)
            //IL_028d: Unknown result type (might be due to invalid IL or missing references)
            //IL_00da: Unknown result type (might be due to invalid IL or missing references)
            //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
            //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
            //IL_008d: Unknown result type (might be due to invalid IL or missing references)
            Color val = default(Color);
            if (!player.ZoneShimmer)
            {
                val = ((Main.waterStyle == 2) ? new Color(124, 118, 242) : ((Main.waterStyle == 3) ? new Color(143, 215, 29) : ((Main.waterStyle == 4) ? new Color(78, 193, 227) : ((Main.waterStyle == 5) ? new Color(189, 231, 255) : ((Main.waterStyle == 6) ? new Color(230, 219, 100) : ((Main.waterStyle == 7) ? new Color(151, 107, 75) : ((Main.waterStyle == 8) ? new Color(128, 128, 128) : ((Main.waterStyle == 9) ? new Color(200, 0, 0) : ((Main.waterStyle == 10) ? new Color(208, 80, 80) : ((Main.waterStyle == 12) ? new Color(230, 219, 100) : ((Main.waterStyle != 13) ? new Color(28, 216, 94) : new Color(28, 216, 94))))))))))));
                if (Main.waterStyle >= 15)
                {
                    val = LoaderManager.Get<WaterStylesLoader>().Get(Main.waterStyle).BiomeHairColor();
                }
            }
            else
            {
                TorchID.TorchColor(23, out var R, out var G, out var B);
                ((Color)(ref val))._002Ector(R, G, B);
            }
            Color val2 = player.hairDyeColor;
            if (((Color)(ref val2)).A == 0)
            {
                val2 = val;
            }
            if (((Color)(ref val2)).R > ((Color)(ref val)).R)
            {
                byte r = ((Color)(ref val2)).R;
                ((Color)(ref val2)).R = (byte)(r - 1);
            }
            if (((Color)(ref val2)).R < ((Color)(ref val)).R)
            {
                byte r = ((Color)(ref val2)).R;
                ((Color)(ref val2)).R = (byte)(r + 1);
            }
            if (((Color)(ref val2)).G > ((Color)(ref val)).G)
            {
                byte r = ((Color)(ref val2)).G;
                ((Color)(ref val2)).G = (byte)(r - 1);
            }
            if (((Color)(ref val2)).G < ((Color)(ref val)).G)
            {
                byte r = ((Color)(ref val2)).G;
                ((Color)(ref val2)).G = (byte)(r + 1);
            }
            if (((Color)(ref val2)).B > ((Color)(ref val)).B)
            {
                byte r = ((Color)(ref val2)).B;
                ((Color)(ref val2)).B = (byte)(r - 1);
            }
            if (((Color)(ref val2)).B < ((Color)(ref val)).B)
            {
                byte r = ((Color)(ref val2)).B;
                ((Color)(ref val2)).B = (byte)(r + 1);
            }
            newColor = val2;
            return newColor;
        }));
        GameShaders.Hair.BindShader(1984, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
        {
            //IL_0013: Unknown result type (might be due to invalid IL or missing references)
            ((Color)(ref newColor))._002Ector(244, 22, 175);
            return newColor;
        }));
        GameShaders.Hair.BindShader(1985, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
        {
            //IL_0016: Unknown result type (might be due to invalid IL or missing references)
            ((Color)(ref newColor))._002Ector(Main.DiscoR, Main.DiscoG, Main.DiscoB);
            return newColor;
        }));
        GameShaders.Hair.BindShader(1986, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
        {
            //IL_0094: Unknown result type (might be due to invalid IL or missing references)
            float num = Math.Abs(player.velocity.X) + Math.Abs(player.velocity.Y);
            float num2 = 10f;
            if (num > num2)
            {
                num = num2;
            }
            float num3 = num / num2;
            float num4 = 1f - num3;
            ((Color)(ref newColor)).R = (byte)(75f * num3 + (float)(int)((Color)(ref player.hairColor)).R * num4);
            ((Color)(ref newColor)).G = (byte)(255f * num3 + (float)(int)((Color)(ref player.hairColor)).G * num4);
            ((Color)(ref newColor)).B = (byte)(200f * num3 + (float)(int)((Color)(ref player.hairColor)).B * num4);
            return newColor;
        }));
        GameShaders.Hair.BindShader(2863, new LegacyHairShaderData().UseLegacyMethod(delegate(Player player, Color newColor, ref bool lighting)
        {
            //IL_0050: Unknown result type (might be due to invalid IL or missing references)
            //IL_0055: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
            lighting = false;
            int x = (int)((double)player.position.X + (double)player.width * 0.5) / 16;
            int y = (int)(((double)player.position.Y + (double)player.height * 0.25) / 16.0);
            Color color = Lighting.GetColor(x, y);
            ((Color)(ref newColor)).R = (byte)(((Color)(ref color)).R + ((Color)(ref newColor)).R >> 1);
            ((Color)(ref newColor)).G = (byte)(((Color)(ref color)).G + ((Color)(ref newColor)).G >> 1);
            ((Color)(ref newColor)).B = (byte)(((Color)(ref color)).B + ((Color)(ref newColor)).B >> 1);
            return newColor;
        }));
    }
References Terraria.Item.buyPrice(), Terraria.Entity.Center, Terraria.Main.dayTime, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.Lighting.GetColor(), Terraria.Graphics.Shaders.GameShaders.Hair, Terraria.Player.hairColor, Terraria.Player.hairDyeColor, Terraria.Entity.height, Terraria.Player.inventory, Terraria.Main.maxTilesY, Terraria.Main.PixelShaderRef, Terraria.Main.rockLayer, Terraria.Item.stack, Terraria.Player.statLifeMax2, Terraria.Player.statMana, Terraria.Player.statManaMax2, Terraria.Player.team, Terraria.Main.teamColor, Terraria.Main.time, Terraria.ID.TorchID.TorchColor(), Terraria.Item.type, Terraria.GameContent.Dyes.LegacyHairShaderData.UseLegacyMethod(), Terraria.Entity.velocity, Terraria.Main.waterStyle, Terraria.Entity.width, Terraria.Main.worldSurface, and Terraria.Player.ZoneShimmer.
Referenced by Terraria.Initializers.DyeInitializer.LoadHairDyes().