TModLoader: Terraria.Rain.MakeRain
MakeRain()
static void Terraria.Rain.MakeRain () inline static
    {
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_021b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0294: Unknown result type (might be due to invalid IL or missing references)
        //IL_0299: Unknown result type (might be due to invalid IL or missing references)
        //IL_029b: Unknown result type (might be due to invalid IL or missing references)
        //IL_029c: Unknown result type (might be due to invalid IL or missing references)
        if (Main.shimmerAlpha > 0f || Main.netMode == 2 || Main.gamePaused)
        {
            return;
        }
        if (Main.remixWorld)
        {
            if (!((double)(Main.player[Main.myPlayer].position.Y / 16f) > Main.rockLayer) || !(Main.player[Main.myPlayer].position.Y / 16f < (float)(Main.maxTilesY - 350)) || Main.player[Main.myPlayer].ZoneDungeon)
            {
                return;
            }
        }
        else if ((double)Main.screenPosition.Y > Main.worldSurface * 16.0)
        {
            return;
        }
        if (Main.gameMenu)
        {
            return;
        }
        float num = (float)Main.screenWidth / 1920f;
        num *= 25f;
        num *= 0.25f + 1f * Main.cloudAlpha;
        if (Filters.Scene["Sandstorm"].IsActive())
        {
            return;
        }
        Vector2 vector = default(Vector2);
        for (int i = 0; (float)i < num; i++)
        {
            int num2 = 600;
            if (Main.player[Main.myPlayer].velocity.Y < 0f)
            {
                num2 += (int)(Math.Abs(Main.player[Main.myPlayer].velocity.Y) * 30f);
            }
            vector.X = Main.rand.Next((int)Main.screenPosition.X - num2, (int)Main.screenPosition.X + Main.screenWidth + num2);
            vector.Y = Main.screenPosition.Y - (float)Main.rand.Next(20, 100);
            vector.X -= Main.windSpeedCurrent * 15f * 40f;
            vector.X += Main.player[Main.myPlayer].velocity.X * 40f;
            if (vector.X < 0f)
            {
                vector.X = 0f;
            }
            if (vector.X > (float)((Main.maxTilesX - 1) * 16))
            {
                vector.X = (Main.maxTilesX - 1) * 16;
            }
            int num3 = (int)vector.X / 16;
            int num4 = (int)vector.Y / 16;
            if (num3 < 0)
            {
                num3 = 0;
            }
            if (num3 > Main.maxTilesX - 1)
            {
                num3 = Main.maxTilesX - 1;
            }
            if (num4 < 0)
            {
                num4 = 0;
            }
            if (num4 > Main.maxTilesY - 1)
            {
                num4 = Main.maxTilesY - 1;
            }
            if (Main.remixWorld || Main.gameMenu || (!WorldGen.SolidTile(num3, num4) && Main.tile[num3, num4].wall <= 0))
            {
                Vector2 rainFallVelocity = GetRainFallVelocity();
                NewRain(vector, rainFallVelocity);
            }
        }
    }
References Terraria.Main.cloudAlpha, Terraria.Main.gameMenu, Terraria.Main.gamePaused, Terraria.Rain.GetRainFallVelocity(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Rain.NewRain(), Terraria.Main.player, Terraria.Entity.position, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.Graphics.Effects.Filters.Scene, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.shimmerAlpha, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Entity.velocity, Terraria.Main.worldSurface, and Terraria.Player.ZoneDungeon.
Referenced by Terraria.Main.DoUpdate().