TModLoader: Terraria.GameContent.ChromaHotkeyPainter.Step_QuickHeal
Step_QuickHeal()
void Terraria.GameContent.ChromaHotkeyPainter.Step_QuickHeal () inline private
    {
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        PaintKey healKey = _healKey;
        if (_player.QuickHeal_GetItemToUse() == null || _player.DeadOrGhost)
        {
            healKey.SetClear();
            _quickHealAlert = 0;
        }
        else if (_player.potionDelay > 0)
        {
            float lerpValue = Utils.GetLerpValue(_player.potionDelayTime, 0f, _player.potionDelay, clamped: true);
            Color solid = Color.Lerp(PainterColors.DangerKeyBlocked, PainterColors.QuickHealCooldown, lerpValue) * lerpValue * lerpValue * lerpValue;
            healKey.SetSolid(solid);
            _quickHealAlert = 0;
        }
        else if (_player.statLife == _player.statLifeMax2)
        {
            healKey.SetClear();
            _quickHealAlert = 0;
        }
        else if ((float)_player.statLife <= (float)_player.statLifeMax2 / 4f)
        {
            if (_quickHealAlert != 1)
            {
                _quickHealAlert = 1;
                healKey.SetAlert(Color.Black, PainterColors.QuickHealReadyUrgent, -1f, 2f);
            }
        }
        else if ((float)_player.statLife <= (float)_player.statLifeMax2 / 2f)
        {
            if (_quickHealAlert != 2)
            {
                _quickHealAlert = 2;
                healKey.SetAlert(Color.Black, PainterColors.QuickHealReadyUrgent, -1f, 2f);
            }
        }
        else
        {
            healKey.SetSolid(PainterColors.QuickHealReady);
            _quickHealAlert = 0;
        }
    }
References Terraria.GameContent.ChromaHotkeyPainter._healKey, Terraria.GameContent.ChromaHotkeyPainter._player, Terraria.GameContent.ChromaHotkeyPainter._quickHealAlert, Terraria.GameContent.ChromaHotkeyPainter.PainterColors.DangerKeyBlocked, Terraria.Player.DeadOrGhost, Terraria.Utils.GetLerpValue(), Terraria.Player.potionDelay, Terraria.Player.potionDelayTime, Terraria.Player.QuickHeal_GetItemToUse(), Terraria.GameContent.ChromaHotkeyPainter.PainterColors.QuickHealCooldown, Terraria.GameContent.ChromaHotkeyPainter.PainterColors.QuickHealReady, Terraria.GameContent.ChromaHotkeyPainter.PainterColors.QuickHealReadyUrgent, Terraria.Player.statLife, and Terraria.Player.statLifeMax2.
Referenced by Terraria.GameContent.ChromaHotkeyPainter.Update().