TModLoader: Terraria.GameInput.SmartSelectGamepadPointer.SmartSelectLookup_GetTargetTile
SmartSelectLookup_GetTargetTile()
void Terraria.GameInput.SmartSelectGamepadPointer.SmartSelectLookup_GetTargetTile (Player player, out int tX, out int tY) inline
Definition at line 23 of file SmartSelectGamepadPointer.cs.
    {
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        tX = (int)(((float)Main.mouseX + Main.screenPosition.X) / 16f);
        tY = (int)(((float)Main.mouseY + Main.screenPosition.Y) / 16f);
        if (player.gravDir == -1f)
        {
            tY = (int)((Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY) / 16f);
        }
        if (ShouldBeUsed())
        {
            Point point = GetPointerPosition().ToPoint();
            tX = (int)(((float)point.X + Main.screenPosition.X) / 16f);
            tY = (int)(((float)point.Y + Main.screenPosition.Y) / 16f);
            if (player.gravDir == -1f)
            {
                tY = (int)((Main.screenPosition.Y + (float)Main.screenHeight - (float)point.Y) / 16f);
            }
        }
    }
References Terraria.GameInput.SmartSelectGamepadPointer.GetPointerPosition(), Terraria.Player.gravDir, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.screenPosition, and Terraria.GameInput.SmartSelectGamepadPointer.ShouldBeUsed().
Referenced by Terraria.Player.SmartSelectLookup().