TModLoader: Terraria.ModLoader.ProjectileLoader.ProjectileAI
ProjectileAI()
static void Terraria.ModLoader.ProjectileLoader.ProjectileAI (Projectile projectile) inline static
    {
        if (PreAI(projectile))
        {
            int type = projectile.type;
            int num;
            if (projectile.ModProjectile != null)
            {
                num = ((projectile.ModProjectile.AIType > 0) ? 1 : 0);
                if (num != 0)
                {
                    projectile.type = projectile.ModProjectile.AIType;
                }
            }
            else
            {
                num = 0;
            }
            projectile.VanillaAI();
            if (num != 0)
            {
                projectile.type = type;
            }
            AI(projectile);
        }
        PostAI(projectile);
    }
References Terraria.ModLoader.ProjectileLoader.AI(), Terraria.Projectile.ModProjectile, Terraria.ModLoader.ProjectileLoader.PostAI(), Terraria.ModLoader.ProjectileLoader.PreAI(), Terraria.Projectile.type, and Terraria.Projectile.VanillaAI().
Referenced by Terraria.Projectile.AI().