TModLoader: Terraria.ModLoader.ProjectileLoader.UseGrapple
UseGrapple()
static void Terraria.ModLoader.ProjectileLoader.UseGrapple (Player player, ref int type) inline static
Definition at line 772 of file ProjectileLoader.cs.
    {
        GetProjectile(type)?.UseGrapple(player, ref type);
        ReadOnlySpan<GlobalProjectile> readOnlySpan = HookUseGrapple.Enumerate();
        for (int i = 0; i < readOnlySpan.Length; i++)
        {
            readOnlySpan[i].UseGrapple(player, ref type);
        }
    }
References Terraria.ModLoader.ProjectileLoader.GetProjectile(), Terraria.ModLoader.ProjectileLoader.HookUseGrapple, and Terraria.ModLoader.ModProjectile.UseGrapple().
Referenced by Terraria.Player.QuickGrapple().