TModLoader: Terraria.ModLoader.ProjectileLoader.FinishSetup
FinishSetup()
static void Terraria.ModLoader.ProjectileLoader.FinishSetup () inline static package
Definition at line 183 of file ProjectileLoader.cs.
    {
        GlobalLoaderUtils<GlobalProjectile, Projectile>.BuildTypeLookups(new Projectile().SetDefaults);
        UpdateHookLists();
        GlobalTypeLookups<GlobalProjectile>.LogStats();
        foreach (ModProjectile proj in projectiles)
        {
            Lang._projectileNameCache[proj.Type] = proj.DisplayName;
        }
    }
References Terraria.Lang._projectileNameCache, Terraria.ModLoader.ProjectileLoader.projectiles, Terraria.ModLoader.ProjectileLoader.SetDefaults(), and Terraria.ModLoader.ProjectileLoader.UpdateHookLists().
Referenced by Terraria.ModLoader.ModContent.Load().