TModLoader: Terraria.ModLoader.ProjectileLoader.GetProjectile
GetProjectile()
static ModProjectile Terraria.ModLoader.ProjectileLoader.GetProjectile (int type) inline static
Gets the ModProjectile template instance corresponding to the specified type (not the clone/new instance which gets added to Projectiles as the game is played).
Parameters
type The type of the projectile
Returns
The ModProjectile instance in the projectiles array, null if not found.
    {
        if (type < ProjectileID.Count || type >= ProjectileCount)
        {
            return null;
        }
        return projectiles[type - ProjectileID.Count];
    }
References Terraria.ID.ProjectileID.Count, Terraria.ModLoader.ProjectileLoader.ProjectileCount, and Terraria.ModLoader.ProjectileLoader.projectiles.
Referenced by Terraria.ModLoader.ProjectileLoader.CanUseGrapple(), Terraria.ModLoader.ModContent.GetModProjectile(), Terraria.ModLoader.Config.UI.ProjectileDefinitionElement.GetPassedOptionElements(), Terraria.ModLoader.ProjectileLoader.SetDefaults(), and Terraria.ModLoader.ProjectileLoader.UseGrapple().