TModLoader: Terraria.GameContent.UI.Elements.EmoteButton.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.EmoteButton.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 84 of file EmoteButton.cs.
    {
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0102: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_0118: Unknown result type (might be due to invalid IL or missing references)
        CalculatedStyle dimensions = GetDimensions();
        Vector2 vector = dimensions.Position() + new Vector2(dimensions.Width, dimensions.Height) / 2f;
        Rectangle frame = GetFrame();
        Rectangle value = _bubbleTexture.Frame(8, 39, 1);
        Vector2 origin = frame.Size() / 2f;
        Color white = Color.White;
        Color color = Color.Black;
        if (_hovered)
        {
            color = Main.OurFavoriteColor;
        }
        if (EmoteBubbleLoader.PreDrawInEmoteMenu(_emoteIndex, spriteBatch, this, vector, frame, origin))
        {
            spriteBatch.Draw(_bubbleTexture.Value, vector, (Rectangle?)value, white, 0f, origin, 1f, (SpriteEffects)0, 0f);
            spriteBatch.Draw(_texture.Value, vector, (Rectangle?)frame, white, 0f, origin, 1f, (SpriteEffects)0, 0f);
            spriteBatch.Draw(_textureBorder.Value, vector - Vector2.One * 2f, (Rectangle?)null, color, 0f, origin, 1f, (SpriteEffects)0, 0f);
        }
        EmoteBubbleLoader.PostDrawInEmoteMenu(_emoteIndex, spriteBatch, this, vector, frame, origin);
        if (_hovered)
        {
            if (_emoteIndex >= EmoteID.Count)
            {
                Main.instance.MouseText("/" + Lang.GetEmojiName(_emoteIndex), 0, 0);
                return;
            }
            string name = EmoteID.Search.GetName(_emoteIndex);
            string cursorText = "/" + Language.GetTextValue("EmojiName." + name);
            Main.instance.MouseText(cursorText, 0, 0);
        }
    }
References Terraria.GameContent.UI.Elements.EmoteButton._bubbleTexture, Terraria.GameContent.UI.Elements.EmoteButton._emoteIndex, Terraria.GameContent.UI.Elements.EmoteButton._hovered, Terraria.GameContent.UI.Elements.EmoteButton._texture, Terraria.GameContent.UI.Elements.EmoteButton._textureBorder, Terraria.GameContent.UI.EmoteID.Count, Terraria.UI.UIElement.GetDimensions(), Terraria.Lang.GetEmojiName(), Terraria.GameContent.UI.Elements.EmoteButton.GetFrame(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.instance, Terraria.Main.MouseText(), Terraria.Main.OurFavoriteColor, Terraria.ModLoader.EmoteBubbleLoader.PostDrawInEmoteMenu(), Terraria.ModLoader.EmoteBubbleLoader.PreDrawInEmoteMenu(), and Terraria.GameContent.UI.EmoteID.Search.