TModLoader: Terraria.GameContent.UI.Elements.EmoteButton.EmoteButton
EmoteButton()
Terraria.GameContent.UI.Elements.EmoteButton.EmoteButton (int emoteIndex) inline
Definition at line 35 of file EmoteButton.cs.
    {
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        if (emoteIndex >= EmoteID.Count)
        {
            _texture = ModContent.Request<Texture2D>(EmoteBubbleLoader.GetEmoteBubble(emoteIndex).Texture);
        }
        else
        {
            _texture = Main.Assets.Request<Texture2D>("Images/Extra_" + (short)48);
        }
        _bubbleTexture = Main.Assets.Request<Texture2D>("Images/Extra_" + (short)48);
        _textureBorder = Main.Assets.Request<Texture2D>("Images/UI/EmoteBubbleBorder");
        _emoteIndex = emoteIndex;
        Rectangle frame = GetFrame();
        Width.Set(frame.Width, 0f);
        Height.Set(frame.Height, 0f);
    }
References Terraria.GameContent.UI.Elements.EmoteButton._bubbleTexture, Terraria.GameContent.UI.Elements.EmoteButton._emoteIndex, Terraria.GameContent.UI.Elements.EmoteButton._texture, Terraria.GameContent.UI.Elements.EmoteButton._textureBorder, Terraria.Main.Assets, Terraria.GameContent.UI.EmoteID.Count, Terraria.ModLoader.EmoteBubbleLoader.GetEmoteBubble(), Terraria.GameContent.UI.Elements.EmoteButton.GetFrame(), Terraria.UI.UIElement.Height, Terraria.UI.StyleDimension.Set(), and Terraria.UI.UIElement.Width.