TModLoader: Terraria.GameContent.UI.Elements.EmoteButton.GetFrame
GetFrame()
Rectangle Terraria.GameContent.UI.Elements.EmoteButton.GetFrame () inline private
    {
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        int num = ((_frameCounter >= 10) ? 1 : 0);
        if (_emoteIndex >= EmoteID.Count)
        {
            return (Rectangle)(((_003F?)EmoteBubbleLoader.GetFrameInEmoteMenu(_emoteIndex, num, _frameCounter)) ?? _texture.Frame(2, 1, num));
        }
        return _texture.Frame(8, EmoteBubble.EMOTE_SHEET_VERTICAL_FRAMES, _emoteIndex % 4 * 2 + num, _emoteIndex / 4 + 1);
    }
References Terraria.GameContent.UI.Elements.EmoteButton._emoteIndex, Terraria.GameContent.UI.Elements.EmoteButton._frameCounter, Terraria.GameContent.UI.Elements.EmoteButton._texture, Terraria.GameContent.UI.EmoteID.Count, Terraria.GameContent.UI.EmoteBubble.EMOTE_SHEET_VERTICAL_FRAMES, and Terraria.ModLoader.EmoteBubbleLoader.GetFrameInEmoteMenu().
Referenced by Terraria.GameContent.UI.Elements.EmoteButton.EmoteButton(), and Terraria.GameContent.UI.Elements.EmoteButton.DrawSelf().