TModLoader: Terraria.GameInput.PlayerInput.UpdateInput
UpdateInput()
static void Terraria.GameInput.PlayerInput.UpdateInput () inline static
    {
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        if (reinitialize)
        {
            ReInitialize();
        }
        SettingsForUI.UpdateCounters();
        Triggers.Reset();
        ScrollWheelValueOld = ScrollWheelValue;
        ScrollWheelValue = 0;
        GamepadThumbstickLeft = Vector2.Zero;
        GamepadThumbstickRight = Vector2.Zero;
        GrappleAndInteractAreShared = (UsingGamepad || SteamDeckIsUsed) && CurrentProfile.InputModes[InputMode.XBoxGamepad].DoGrappleAndInteractShareTheSameKey;
        if (InBuildingMode && !UsingGamepad)
        {
            ExitBuildingMode();
        }
        if (_canReleaseRebindingLock && NavigatorRebindingLock > 0)
        {
            NavigatorRebindingLock--;
            Triggers.Current.UsedMovementKey = false;
            if (NavigatorRebindingLock == 0 && _memoOfLastPoint != -1)
            {
                UIManageControls.ForceMoveTo = _memoOfLastPoint;
                _memoOfLastPoint = -1;
            }
        }
        _canReleaseRebindingLock = true;
        VerifyBuildingMode();
        MouseInput();
        int num = 0 | (KeyboardInput() ? 1 : 0) | (GamePadInput() ? 1 : 0);
        Triggers.Update();
        PostInput();
        ScrollWheelDelta = ScrollWheelValue - ScrollWheelValueOld;
        ScrollWheelDeltaForUI = ScrollWheelDelta;
        WritingText = false;
        UpdateMainMouse();
        Main.mouseLeft = Triggers.Current.MouseLeft;
        Main.mouseRight = Triggers.Current.MouseRight;
        Main.mouseMiddle = Triggers.Current.MouseMiddle;
        Main.mouseXButton1 = Triggers.Current.MouseXButton1;
        Main.mouseXButton2 = Triggers.Current.MouseXButton2;
        CacheZoomableValues();
        if (num != 0 && PlayerInput.OnActionableInput != null)
        {
            PlayerInput.OnActionableInput();
        }
    }
References Terraria.GameInput.PlayerInput._canReleaseRebindingLock, Terraria.GameInput.PlayerInput._memoOfLastPoint, Terraria.GameInput.PlayerInput.CacheZoomableValues(), Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.GameInput.PlayerInput.ExitBuildingMode(), Terraria.GameInput.PlayerInput.GamePadInput(), Terraria.GameInput.PlayerInput.GamepadThumbstickLeft, Terraria.GameInput.PlayerInput.GamepadThumbstickRight, Terraria.GameInput.PlayerInput.GrappleAndInteractAreShared, Terraria.GameInput.PlayerInput.InBuildingMode, Terraria.GameInput.PlayerInput.KeyboardInput(), Terraria.GameInput.PlayerInput.MouseInput(), Terraria.GameInput.PlayerInput.NavigatorRebindingLock, Terraria.GameInput.PlayerInput.OnActionableInput, Terraria.GameInput.PlayerInput.PostInput(), Terraria.GameInput.PlayerInput.reinitialize, Terraria.GameInput.PlayerInput.ReInitialize(), Terraria.GameInput.PlayerInput.ScrollWheelDelta, Terraria.GameInput.PlayerInput.ScrollWheelDeltaForUI, Terraria.GameInput.PlayerInput.ScrollWheelValue, Terraria.GameInput.PlayerInput.ScrollWheelValueOld, Terraria.GameInput.PlayerInput.SteamDeckIsUsed, Terraria.GameInput.PlayerInput.Triggers, Terraria.GameInput.PlayerInput.SettingsForUI.UpdateCounters(), Terraria.GameInput.PlayerInput.UpdateMainMouse(), Terraria.GameInput.PlayerInput.UsingGamepad, Terraria.GameInput.PlayerInput.VerifyBuildingMode(), and Terraria.GameInput.PlayerInput.WritingText.
Referenced by Terraria.Main.DoUpdate_HandleInput().