TModLoader: Terraria.GameInput.PlayerInput.ReInitialize
ReInitialize()
static void Terraria.GameInput.PlayerInput.ReInitialize () inline static private
Definition at line 538 of file PlayerInput.cs.
    {
        Profiles.Clear();
        OriginalProfiles.Clear();
        Initialize_Inner();
        Load();
        reinitialize = false;
    }
References Terraria.GameInput.PlayerInput.Initialize_Inner(), Terraria.GameInput.PlayerInput.Load(), Terraria.GameInput.PlayerInput.OriginalProfiles, and Terraria.GameInput.PlayerInput.reinitialize.
Referenced by Terraria.GameInput.PlayerInput.UpdateInput().