TModLoader: Terraria.GameInput.PlayerInput.HandleDpadSnap
HandleDpadSnap()
static void Terraria.GameInput.PlayerInput.HandleDpadSnap () inline static private
Definition at line 1739 of file PlayerInput.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        Vector2 zero = Vector2.Zero;
        Player player = Main.player[Main.myPlayer];
        for (int i = 0; i < 4; i++)
        {
            bool flag = false;
            Vector2 vector = Vector2.Zero;
            if (Main.gameMenu || (UILinkPointNavigator.Available && !InBuildingMode))
            {
                return;
            }
            switch (i)
            {
            case 0:
                flag = Triggers.Current.DpadMouseSnap1;
                vector = -Vector2.UnitY;
                break;
            case 1:
                flag = Triggers.Current.DpadMouseSnap2;
                vector = Vector2.UnitX;
                break;
            case 2:
                flag = Triggers.Current.DpadMouseSnap3;
                vector = Vector2.UnitY;
                break;
            case 3:
                flag = Triggers.Current.DpadMouseSnap4;
                vector = -Vector2.UnitX;
                break;
            }
            if (DpadSnapCooldown[i] > 0)
            {
                DpadSnapCooldown[i]--;
            }
            if (flag)
            {
                if (DpadSnapCooldown[i] == 0)
                {
                    int num = 6;
                    if (ItemSlot.IsABuildingItem(player.inventory[player.selectedItem]))
                    {
                        num = CombinedHooks.TotalUseTime(player.inventory[player.selectedItem].useTime, player, player.inventory[player.selectedItem]);
                    }
                    DpadSnapCooldown[i] = num;
                    zero += vector;
                }
            }
            else
            {
                DpadSnapCooldown[i] = 0;
            }
        }
        if (zero != Vector2.Zero)
        {
            Main.SmartCursorWanted_GamePad = false;
            Matrix zoomMatrix = Main.GameViewMatrix.ZoomMatrix;
            Matrix matrix = Matrix.Invert(zoomMatrix);
            Vector2 mouseScreen = Main.MouseScreen;
            Vector2.Transform(Main.screenPosition, matrix);
            Vector2 val = Vector2.Transform((Vector2.Transform(mouseScreen, matrix) + zero * new Vector2(16f) + Main.screenPosition).ToTileCoordinates().ToWorldCoordinates() - Main.screenPosition, zoomMatrix);
            MouseX = (int)val.X;
            MouseY = (int)val.Y;
            SettingsForUI.SetCursorMode(CursorMode.Gamepad);
        }
    }
References Terraria.UI.Gamepad.UILinkPointNavigator.Available, Terraria.GameInput.PlayerInput.DpadSnapCooldown, Terraria.Main.gameMenu, Terraria.Main.GameViewMatrix, Terraria.GameInput.PlayerInput.InBuildingMode, Terraria.Player.inventory, Terraria.UI.ItemSlot.IsABuildingItem(), Terraria.Main.MouseScreen, Terraria.GameInput.PlayerInput.MouseX, Terraria.GameInput.PlayerInput.MouseY, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.screenPosition, Terraria.Player.selectedItem, Terraria.GameInput.PlayerInput.SettingsForUI.SetCursorMode(), Terraria.ModLoader.CombinedHooks.TotalUseTime(), Terraria.GameInput.PlayerInput.Triggers, and Terraria.Item.useTime.
Referenced by Terraria.GameInput.PlayerInput.GamePadInput().