TModLoader: Terraria.GameInput.PlayerInput.LockVanillaMouseScroll
LockVanillaMouseScroll()
static void Terraria.GameInput.PlayerInput.LockVanillaMouseScroll (string myUI) inline static
Locks the vanilla scrollbar for the upcoming cycle when called. Autoclears in Player. Takes a string to denote that your UI has registered to lock vanilla scrolling. String does not need to be unique.
Definition at line 2841 of file PlayerInput.cs.
    {
        if (!MouseInModdedUI.Contains(myUI))
        {
            MouseInModdedUI.Add(myUI);
        }
    }
References Terraria.GameInput.PlayerInput.MouseInModdedUI.
Referenced by Terraria.ModLoader.AccessorySlotLoader.DrawScrollbar(), Terraria.GameContent.UI.Elements.UIList.MouseOver(), Terraria.GameContent.UI.Elements.UIScrollbar.MouseOver(), Terraria.ModLoader.Config.UI.NestedUIList.MouseOver(), and Terraria.ModLoader.UI.Elements.UIGrid.MouseOver().