TModLoader: Terraria.GameInput.PlayerInput.SetZoom_MouseInWorld
SetZoom_MouseInWorld()
static void Terraria.GameInput.PlayerInput.SetZoom_MouseInWorld () inline static
Definition at line 2702 of file PlayerInput.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = Main.screenPosition + new Vector2((float)Main.screenWidth, (float)Main.screenHeight) / 2f;
        Vector2 vector2 = Main.screenPosition + new Vector2((float)_originalMouseX, (float)_originalMouseY);
        Vector2 val = Main.screenPosition + new Vector2((float)_originalLastMouseX, (float)_originalLastMouseY);
        Vector2 vector3 = vector2 - vector;
        Vector2 vector4 = val - vector;
        float num = 1f / Main.GameViewMatrix.Zoom.X;
        Vector2 val2 = vector - Main.screenPosition + vector3 * num;
        Main.mouseX = (int)val2.X;
        Main.mouseY = (int)val2.Y;
        Vector2 val3 = vector - Main.screenPosition + vector4 * num;
        Main.lastMouseX = (int)val3.X;
        Main.lastMouseY = (int)val3.Y;
    }
References Terraria.GameInput.PlayerInput._originalLastMouseX, Terraria.GameInput.PlayerInput._originalLastMouseY, Terraria.GameInput.PlayerInput._originalMouseX, Terraria.GameInput.PlayerInput._originalMouseY, Terraria.Main.GameViewMatrix, Terraria.Main.screenHeight, and Terraria.Main.screenWidth.
Referenced by Terraria.Main.DoUpdate_HandleInput(), Terraria.Main.DrawInterface_38_MouseCarriedObject(), Terraria.Main.DrawMouseOver(), Terraria.Main.DrawProjectiles(), Terraria.Main.HoverOverNPCs(), Terraria.GameInput.PlayerInput.SetZoom_Context(), and Terraria.GameInput.PlayerInput.SetZoom_World().