TModLoader: Terraria.GameInput.PlayerInput.KeyboardInput
KeyboardInput()
static bool Terraria.GameInput.PlayerInput.KeyboardInput () inline static private
Definition at line 1450 of file PlayerInput.cs.
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Invalid comparison between Unknown and I4
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Invalid comparison between Unknown and I4
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Invalid comparison between Unknown and I4
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Invalid comparison between Unknown and I4
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_021a: Unknown result type (might be due to invalid IL or missing references)
        //IL_022e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        bool flag = false;
        bool flag2 = false;
        List<Keys> pressedKeys = GetPressedKeys();
        DebugKeys(pressedKeys);
        Keys val;
        if (pressedKeys.Count == 0 && MouseKeys.Count == 0)
        {
            val = (Keys)0;
            Main.blockKey = ((object)(Keys)(ref val)).ToString();
            return false;
        }
        for (int i = 0; i < pressedKeys.Count; i++)
        {
            if ((int)pressedKeys[i] == 160 || (int)pressedKeys[i] == 161)
            {
                flag = true;
            }
            else if ((int)pressedKeys[i] == 164 || (int)pressedKeys[i] == 165)
            {
                flag2 = true;
            }
            Main.ChromaPainter.PressKey(pressedKeys[i]);
        }
        string blockKey = Main.blockKey;
        val = (Keys)0;
        if (blockKey != ((object)(Keys)(ref val)).ToString())
        {
            bool flag3 = false;
            for (int j = 0; j < pressedKeys.Count; j++)
            {
                val = pressedKeys[j];
                if (((object)(Keys)(ref val)).ToString() == Main.blockKey)
                {
                    pressedKeys[j] = (Keys)0;
                    flag3 = true;
                }
            }
            if (!flag3)
            {
                val = (Keys)0;
                Main.blockKey = ((object)(Keys)(ref val)).ToString();
            }
        }
        KeyConfiguration keyConfiguration = CurrentProfile.InputModes[InputMode.Keyboard];
        if (Main.gameMenu && !WritingText)
        {
            keyConfiguration = CurrentProfile.InputModes[InputMode.KeyboardUI];
        }
        List<string> list = new List<string>(pressedKeys.Count);
        for (int k = 0; k < pressedKeys.Count; k++)
        {
            val = pressedKeys[k];
            list.Add(((object)(Keys)(ref val)).ToString());
        }
        if (WritingText)
        {
            list.Clear();
        }
        int count = list.Count;
        list.AddRange(MouseKeys);
        bool flag4 = false;
        for (int l = 0; l < list.Count; l++)
        {
            if (l < count && (int)pressedKeys[l] == 0)
            {
                continue;
            }
            string newKey = list[l];
            string text = list[l];
            val = (Keys)9;
            if (!(text == ((object)(Keys)(ref val)).ToString()) || !((flag && SocialAPI.Mode == SocialMode.Steam) || flag2))
            {
                if (CheckRebindingProcessKeyboard(newKey))
                {
                    return false;
                }
                _ = Main.oldKeyState;
                if (l >= count || !((KeyboardState)(ref Main.oldKeyState)).IsKeyDown(pressedKeys[l]))
                {
                    keyConfiguration.Processkey(Triggers.Current, newKey, InputMode.Keyboard);
                }
                else
                {
                    keyConfiguration.CopyKeyState(Triggers.Old, Triggers.Current, newKey);
                }
                if (l >= count || (int)pressedKeys[l] != 0)
                {
                    flag4 = true;
                }
            }
        }
        if (flag4)
        {
            CurrentInputMode = InputMode.Keyboard;
        }
        return flag4;
    }
References Terraria.Main.blockKey, Terraria.GameInput.PlayerInput.CheckRebindingProcessKeyboard(), Terraria.Main.ChromaPainter, Terraria.GameInput.PlayerInput.CurrentInputMode, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.GameInput.PlayerInput.DebugKeys(), Terraria.Main.gameMenu, Terraria.GameInput.PlayerInput.GetPressedKeys(), Terraria.GameInput.PlayerInput.MouseKeys, Terraria.Main.oldKeyState, Terraria.GameInput.PlayerInput.Triggers, and Terraria.GameInput.PlayerInput.WritingText.
Referenced by Terraria.GameInput.PlayerInput.UpdateInput().