TModLoader: Terraria.GameInput.PlayerInput.GamePadInput
GamePadInput()
static bool Terraria.GameInput.PlayerInput.GamePadInput () inline static private
    {
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_019d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_020c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_023f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0244: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_024e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        //IL_0255: Unknown result type (might be due to invalid IL or missing references)
        //IL_0257: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_025b: Unknown result type (might be due to invalid IL or missing references)
        //IL_025d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_0272: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_0276: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0342: Unknown result type (might be due to invalid IL or missing references)
        //IL_0347: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0352: Unknown result type (might be due to invalid IL or missing references)
        //IL_0301: Unknown result type (might be due to invalid IL or missing references)
        //IL_041f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0424: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_036a: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0488: Unknown result type (might be due to invalid IL or missing references)
        //IL_048d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0492: Unknown result type (might be due to invalid IL or missing references)
        //IL_042f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        //IL_0393: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0501: Unknown result type (might be due to invalid IL or missing references)
        //IL_049d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0447: Unknown result type (might be due to invalid IL or missing references)
        //IL_0407: Unknown result type (might be due to invalid IL or missing references)
        //IL_0565: Unknown result type (might be due to invalid IL or missing references)
        //IL_056a: Unknown result type (might be due to invalid IL or missing references)
        //IL_056f: Unknown result type (might be due to invalid IL or missing references)
        //IL_050c: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0470: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05de: Unknown result type (might be due to invalid IL or missing references)
        //IL_057a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0524: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0644: Unknown result type (might be due to invalid IL or missing references)
        //IL_0649: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0598: Unknown result type (might be due to invalid IL or missing references)
        //IL_054d: Unknown result type (might be due to invalid IL or missing references)
        //IL_069e: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_065b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0601: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0684: Unknown result type (might be due to invalid IL or missing references)
        //IL_062a: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0876: Unknown result type (might be due to invalid IL or missing references)
        //IL_087b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0880: Unknown result type (might be due to invalid IL or missing references)
        //IL_088a: Unknown result type (might be due to invalid IL or missing references)
        //IL_088f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0894: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0919: Unknown result type (might be due to invalid IL or missing references)
        //IL_0920: Unknown result type (might be due to invalid IL or missing references)
        //IL_095a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0964: Unknown result type (might be due to invalid IL or missing references)
        //IL_0966: Unknown result type (might be due to invalid IL or missing references)
        //IL_0945: Unknown result type (might be due to invalid IL or missing references)
        //IL_0abf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0afa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b06: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a53: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_09bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_09cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b49: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b55: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b75: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b80: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ccf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bcf: Unknown result type (might be due to invalid IL or missing references)
        bool flag = false;
        ScrollWheelValue += GamepadScrollValue;
        GamePadState gamePadState = default(GamePadState);
        bool flag2 = false;
        for (int i = 0; i < 4; i++)
        {
            GamePadState state = GamePad.GetState((PlayerIndex)i);
            if (((GamePadState)(ref state)).IsConnected)
            {
                flag2 = true;
                gamePadState = state;
                break;
            }
        }
        if (Main.SettingBlockGamepadsEntirely)
        {
            return false;
        }
        if (!flag2)
        {
            return false;
        }
        if (!((Game)Main.instance).IsActive && !Main.AllowUnfocusedInputOnGamepad)
        {
            return false;
        }
        Player player = Main.player[Main.myPlayer];
        bool flag3 = UILinkPointNavigator.Available && !InBuildingMode;
        InputMode inputMode = InputMode.XBoxGamepad;
        if (Main.gameMenu || flag3 || player.talkNPC != -1 || player.sign != -1 || IngameFancyUI.CanCover())
        {
            inputMode = InputMode.XBoxGamepadUI;
        }
        if (!Main.gameMenu && InBuildingMode)
        {
            inputMode = InputMode.XBoxGamepad;
        }
        if (CurrentInputMode == InputMode.XBoxGamepad && inputMode == InputMode.XBoxGamepadUI)
        {
            flag = true;
        }
        if (CurrentInputMode == InputMode.XBoxGamepadUI && inputMode == InputMode.XBoxGamepad)
        {
            flag = true;
        }
        if (flag)
        {
            CurrentInputMode = inputMode;
        }
        KeyConfiguration keyConfiguration = CurrentProfile.InputModes[inputMode];
        int num = 2145386496;
        for (int j = 0; j < ButtonsGamepad.Length; j++)
        {
            if ((int)((uint)num & (uint)ButtonsGamepad[j]) > 0)
            {
                continue;
            }
            string text = ((object)(Buttons)(ref ButtonsGamepad[j])).ToString();
            bool flag4 = _buttonsLocked.Contains(text);
            if (((GamePadState)(ref gamePadState)).IsButtonDown(ButtonsGamepad[j]))
            {
                if (!flag4)
                {
                    if (CheckRebindingProcessGamepad(text))
                    {
                        return false;
                    }
                    keyConfiguration.Processkey(Triggers.Current, text, inputMode);
                    flag = true;
                }
            }
            else
            {
                _buttonsLocked.Remove(text);
            }
        }
        GamePadThumbSticks thumbSticks = ((GamePadState)(ref gamePadState)).ThumbSticks;
        GamepadThumbstickLeft = ((GamePadThumbSticks)(ref thumbSticks)).Left * new Vector2(1f, -1f) * new Vector2((float)(CurrentProfile.LeftThumbstickInvertX.ToDirectionInt() * -1), (float)(CurrentProfile.LeftThumbstickInvertY.ToDirectionInt() * -1));
        thumbSticks = ((GamePadState)(ref gamePadState)).ThumbSticks;
        GamepadThumbstickRight = ((GamePadThumbSticks)(ref thumbSticks)).Right * new Vector2(1f, -1f) * new Vector2((float)(CurrentProfile.RightThumbstickInvertX.ToDirectionInt() * -1), (float)(CurrentProfile.RightThumbstickInvertY.ToDirectionInt() * -1));
        Vector2 gamepadThumbstickRight = GamepadThumbstickRight;
        Vector2 gamepadThumbstickLeft = GamepadThumbstickLeft;
        Vector2 vector = gamepadThumbstickRight;
        if (vector != Vector2.Zero)
        {
            ((Vector2)(ref vector)).Normalize();
        }
        Vector2 vector2 = gamepadThumbstickLeft;
        if (vector2 != Vector2.Zero)
        {
            ((Vector2)(ref vector2)).Normalize();
        }
        float num10 = 0.6f;
        float triggersDeadzone = CurrentProfile.TriggersDeadzone;
        if (inputMode == InputMode.XBoxGamepadUI)
        {
            num10 = 0.4f;
            if (GamepadAllowScrolling)
            {
                GamepadScrollValue -= (int)(gamepadThumbstickRight.Y * 16f);
            }
            GamepadAllowScrolling = false;
        }
        Buttons val;
        if (Vector2.Dot(-Vector2.UnitX, vector2) >= num10 && gamepadThumbstickLeft.X < 0f - CurrentProfile.LeftThumbstickDeadzoneX)
        {
            val = (Buttons)2097152;
            if (CheckRebindingProcessGamepad(((object)(Buttons)(ref val)).ToString()))
            {
                return false;
            }
            TriggersSet current = Triggers.Current;
            val = (Buttons)2097152;
            keyConfiguration.Processkey(current, ((object)(Buttons)(ref val)).ToString(), inputMode);
            flag = true;
        }
        if (Vector2.Dot(Vector2.UnitX, vector2) >= num10 && gamepadThumbstickLeft.X > CurrentProfile.LeftThumbstickDeadzoneX)
        {
            val = (Buttons)1073741824;
            if (CheckRebindingProcessGamepad(((object)(Buttons)(ref val)).ToString()))
            {
                return false;
            }
            TriggersSet current2 = Triggers.Current;
            val = (Buttons)1073741824;
            keyConfiguration.Processkey(current2, ((object)(Buttons)(ref val)).ToString(), inputMode);
            flag = true;
        }
        if (Vector2.Dot(-Vector2.UnitY, vector2) >= num10 && gamepadThumbstickLeft.Y < 0f - CurrentProfile.LeftThumbstickDeadzoneY)
        {
            val = (Buttons)268435456;
            if (CheckRebindingProcessGamepad(((object)(Buttons)(ref val)).ToString()))
            {
                return false;
            }
            TriggersSet current3 = Triggers.Current;
            val = (Buttons)268435456;
            keyConfiguration.Processkey(current3, ((object)(Buttons)(ref val)).ToString(), inputMode);
            flag = true;
        }
        if (Vector2.Dot(Vector2.UnitY, vector2) >= num10 && gamepadThumbstickLeft.Y > CurrentProfile.LeftThumbstickDeadzoneY)
        {
            val = (Buttons)536870912;
            if (CheckRebindingProcessGamepad(((object)(Buttons)(ref val)).ToString()))
            {
                return false;
            }
            TriggersSet current4 = Triggers.Current;
            val = (Buttons)536870912;
            keyConfiguration.Processkey(current4, ((object)(Buttons)(ref val)).ToString(), inputMode);
            flag = true;
        }
        if (Vector2.Dot(-Vector2.UnitX, vector) >= num10 && gamepadThumbstickRight.X < 0f - CurrentProfile.RightThumbstickDeadzoneX)
        {
            val = (Buttons)134217728;
            if (CheckRebindingProcessGamepad(((object)(Buttons)(ref val)).ToString()))
            {
                return false;
            }
            TriggersSet current5 = Triggers.Current;
            val = (Buttons)134217728;
            keyConfiguration.Processkey(current5, ((object)(Buttons)(ref val)).ToString(), inputMode);
            flag = true;
        }
        if (Vector2.Dot(Vector2.UnitX, vector) >= num10 && gamepadThumbstickRight.X > CurrentProfile.RightThumbstickDeadzoneX)
        {
            val = (Buttons)67108864;
            if (CheckRebindingProcessGamepad(((object)(Buttons)(ref val)).ToString()))
            {
                return false;
            }
            TriggersSet current6 = Triggers.Current;
            val = (Buttons)67108864;
            keyConfiguration.Processkey(current6, ((object)(Buttons)(ref val)).ToString(), inputMode);
            flag = true;
        }
        if (Vector2.Dot(-Vector2.UnitY, vector) >= num10 && gamepadThumbstickRight.Y < 0f - CurrentProfile.RightThumbstickDeadzoneY)
        {
            val = (Buttons)16777216;
            if (CheckRebindingProcessGamepad(((object)(Buttons)(ref val)).ToString()))
            {
                return false;
            }
            TriggersSet current7 = Triggers.Current;
            val = (Buttons)16777216;
            keyConfiguration.Processkey(current7, ((object)(Buttons)(ref val)).ToString(), inputMode);
            flag = true;
        }
        if (Vector2.Dot(Vector2.UnitY, vector) >= num10 && gamepadThumbstickRight.Y > CurrentProfile.RightThumbstickDeadzoneY)
        {
            val = (Buttons)33554432;
            if (CheckRebindingProcessGamepad(((object)(Buttons)(ref val)).ToString()))
            {
                return false;
            }
            TriggersSet current8 = Triggers.Current;
            val = (Buttons)33554432;
            keyConfiguration.Processkey(current8, ((object)(Buttons)(ref val)).ToString(), inputMode);
            flag = true;
        }
        GamePadTriggers triggers = ((GamePadState)(ref gamePadState)).Triggers;
        if (((GamePadTriggers)(ref triggers)).Left > triggersDeadzone)
        {
            val = (Buttons)8388608;
            if (CheckRebindingProcessGamepad(((object)(Buttons)(ref val)).ToString()))
            {
                return false;
            }
            TriggersSet current9 = Triggers.Current;
            val = (Buttons)8388608;
            keyConfiguration.Processkey(current9, ((object)(Buttons)(ref val)).ToString(), inputMode);
            flag = true;
        }
        triggers = ((GamePadState)(ref gamePadState)).Triggers;
        if (((GamePadTriggers)(ref triggers)).Right > triggersDeadzone)
        {
            val = (Buttons)4194304;
            string newKey = ((object)(Buttons)(ref val)).ToString();
            if (CheckRebindingProcessGamepad(newKey))
            {
                return false;
            }
            if (inputMode == InputMode.XBoxGamepadUI && SteamDeckIsUsed && SettingsForUI.CurrentCursorMode == CursorMode.Mouse)
            {
                Triggers.Current.MouseLeft = true;
            }
            else
            {
                keyConfiguration.Processkey(Triggers.Current, newKey, inputMode);
                flag = true;
            }
        }
        if (player.HeldItem.type >= ItemID.Sets.GamepadWholeScreenUseRange.Length)
        {
            return false;
        }
        bool flag5 = ItemID.Sets.GamepadWholeScreenUseRange[player.inventory[player.selectedItem].type] || player.scope;
        Item item = player.inventory[player.selectedItem];
        int num11 = item.tileBoost + ItemID.Sets.GamepadExtraRange[item.type];
        if (player.yoyoString && ItemID.Sets.Yoyo[item.type])
        {
            num11 += 5;
        }
        else if (item.createTile < 0 && item.createWall <= 0 && item.shoot > 0)
        {
            num11 += 10;
        }
        else if (player.controlTorch)
        {
            num11++;
        }
        if (item.createWall > 0 || item.createTile > 0 || item.tileWand > 0)
        {
            num11 += player.blockRange;
        }
        if (flag5)
        {
            num11 += 30;
        }
        if (player.mount.Active && player.mount.Type == 8)
        {
            num11 = 10;
        }
        bool flag6 = false;
        bool flag7 = !Main.gameMenu && !flag3 && Main.SmartCursorWanted;
        if (!CursorIsBusy)
        {
            bool flag8 = Main.mapFullscreen || (!Main.gameMenu && !flag3);
            int num12 = Main.screenWidth / 2;
            int num13 = Main.screenHeight / 2;
            if (!Main.mapFullscreen && flag8 && !flag5)
            {
                Point val2 = Main.ReverseGravitySupport(player.Center - Main.screenPosition).ToPoint();
                num12 = val2.X;
                num13 = val2.Y;
            }
            if (player.velocity == Vector2.Zero && gamepadThumbstickLeft == Vector2.Zero && gamepadThumbstickRight == Vector2.Zero && flag7)
            {
                num12 += player.direction * 10;
            }
            float k = Main.GameViewMatrix.ZoomMatrix.M11;
            smartSelectPointer.UpdateSize(new Vector2((float)(Player.tileRangeX * 16 + num11 * 16), (float)(Player.tileRangeY * 16 + num11 * 16)) * k);
            if (flag5)
            {
                smartSelectPointer.UpdateSize(new Vector2((float)(Math.Max(Main.screenWidth, Main.screenHeight) / 2)));
            }
            smartSelectPointer.UpdateCenter(new Vector2((float)num12, (float)num13));
            if (gamepadThumbstickRight != Vector2.Zero && flag8)
            {
                Vector2 vector3 = default(Vector2);
                ((Vector2)(ref vector3))._002Ector(8f);
                if (!Main.gameMenu && Main.mapFullscreen)
                {
                    ((Vector2)(ref vector3))._002Ector(16f);
                }
                if (flag7)
                {
                    ((Vector2)(ref vector3))._002Ector((float)(Player.tileRangeX * 16), (float)(Player.tileRangeY * 16));
                    if (num11 != 0)
                    {
                        vector3 += new Vector2((float)(num11 * 16), (float)(num11 * 16));
                    }
                    if (flag5)
                    {
                        ((Vector2)(ref vector3))._002Ector((float)(Math.Max(Main.screenWidth, Main.screenHeight) / 2));
                    }
                }
                else if (!Main.mapFullscreen)
                {
                    vector3 = ((!player.inventory[player.selectedItem].mech) ? (vector3 + new Vector2((float)num11) / 4f) : (vector3 + Vector2.Zero));
                }
                float m2 = Main.GameViewMatrix.ZoomMatrix.M11;
                Vector2 vector4 = gamepadThumbstickRight * vector3 * m2;
                int num14 = MouseX - num12;
                int num15 = MouseY - num13;
                if (flag7)
                {
                    num14 = 0;
                    num15 = 0;
                }
                num14 += (int)vector4.X;
                num15 += (int)vector4.Y;
                MouseX = num14 + num12;
                MouseY = num15 + num13;
                flag = true;
                flag6 = true;
                SettingsForUI.SetCursorMode(CursorMode.Gamepad);
            }
            bool allowSecondaryGamepadAim = SettingsForUI.AllowSecondaryGamepadAim;
            if (gamepadThumbstickLeft != Vector2.Zero && flag8)
            {
                float num16 = 8f;
                if (!Main.gameMenu && Main.mapFullscreen)
                {
                    num16 = 3f;
                }
                if (Main.mapFullscreen)
                {
                    Vector2 vector5 = gamepadThumbstickLeft * num16;
                    Main.mapFullscreenPos += vector5 * num16 * (1f / Main.mapFullscreenScale);
                    flag = true;
                }
                else if (!flag6 && Main.SmartCursorWanted && allowSecondaryGamepadAim)
                {
                    float m3 = Main.GameViewMatrix.ZoomMatrix.M11;
                    Vector2 vector6 = gamepadThumbstickLeft * new Vector2((float)(Player.tileRangeX * 16), (float)(Player.tileRangeY * 16)) * m3;
                    if (num11 != 0)
                    {
                        vector6 = gamepadThumbstickLeft * new Vector2((float)((Player.tileRangeX + num11) * 16), (float)((Player.tileRangeY + num11) * 16)) * m3;
                    }
                    if (flag5)
                    {
                        vector6 = new Vector2((float)(Math.Max(Main.screenWidth, Main.screenHeight) / 2)) * gamepadThumbstickLeft;
                    }
                    int num17 = (int)vector6.X;
                    int num18 = (int)vector6.Y;
                    MouseX = num17 + num12;
                    MouseY = num18 + num13;
                    flag6 = true;
                }
                flag = true;
            }
            if (CurrentInputMode == InputMode.XBoxGamepad)
            {
                HandleDpadSnap();
                if (SettingsForUI.AllowSecondaryGamepadAim)
                {
                    int num2 = MouseX - num12;
                    int num3 = MouseY - num13;
                    if (!Main.gameMenu && !flag3)
                    {
                        if (flag5 && !Main.mapFullscreen)
{
                            float num4 = 1f;
                            int num5 = Main.screenWidth / 2;
                            int num6 = Main.screenHeight / 2;
                            num2 = (int)Utils.Clamp(num2, (float)(-num5) * num4, (float)num5 * num4);
                            num3 = (int)Utils.Clamp(num3, (float)(-num6) * num4, (float)num6 * num4);
                        }
                        else
{
                            float num7 = 0f;
                            if (player.HeldItem.createTile >= 0 || player.HeldItem.createWall > 0 || player.HeldItem.tileWand >= 0)
{
                                num7 = 0.5f;
                            }
                            float m4 = Main.GameViewMatrix.ZoomMatrix.M11;
                            float num8 = (0f - ((float)(Player.tileRangeY + num11) - num7)) * 16f * m4;
                            float max = ((float)(Player.tileRangeY + num11) - num7) * 16f * m4;
                            num8 -= (float)(player.height / 16 / 2 * 16);
                            num2 = (int)Utils.Clamp(num2, (0f - ((float)(Player.tileRangeX + num11) - num7)) * 16f * m4, ((float)(Player.tileRangeX + num11) - num7) * 16f * m4);
                            num3 = (int)Utils.Clamp(num3, num8, max);
                        }
                        if (flag7 && (!flag || flag5))
{
                            float num9 = 0.81f;
                            if (flag5)
{
                                num9 = 0.95f;
                            }
                            num2 = (int)((float)num2 * num9);
                            num3 = (int)((float)num3 * num9);
                        }
                    }
                    else
                    {
                        num2 = Utils.Clamp(num2, -num12 + 10, num12 - 10);
                        num3 = Utils.Clamp(num3, -num13 + 10, num13 - 10);
                    }
                    MouseX = num2 + num12;
                    MouseY = num3 + num13;
                }
            }
        }
        if (flag)
        {
            CurrentInputMode = inputMode;
        }
        if (CurrentInputMode == InputMode.XBoxGamepad)
        {
            Main.SetCameraGamepadLerp(0.1f);
        }
        if (CurrentInputMode != InputMode.XBoxGamepadUI && flag)
        {
            PreventCursorModeSwappingToGamepad = true;
        }
        if (!flag)
        {
            PreventCursorModeSwappingToGamepad = false;
        }
        if (CurrentInputMode == InputMode.XBoxGamepadUI && flag && !PreventCursorModeSwappingToGamepad)
        {
            SettingsForUI.SetCursorMode(CursorMode.Gamepad);
        }
        return flag;
    }
References Terraria.GameInput.PlayerInput._buttonsLocked, Terraria.Mount.Active, Terraria.GameInput.PlayerInput.SettingsForUI.AllowSecondaryGamepadAim, Terraria.Main.AllowUnfocusedInputOnGamepad, Terraria.Player.blockRange, Terraria.GameInput.PlayerInput.ButtonsGamepad, Terraria.UI.IngameFancyUI.CanCover(), Terraria.Entity.Center, Terraria.GameInput.PlayerInput.CheckRebindingProcessGamepad(), Terraria.Player.controlTorch, Terraria.Item.createTile, Terraria.Item.createWall, Terraria.GameInput.TriggersPack.Current, Terraria.GameInput.PlayerInput.SettingsForUI.CurrentCursorMode, Terraria.GameInput.PlayerInput.CurrentInputMode, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.GameInput.PlayerInput.CursorIsBusy, Terraria.Main.gameMenu, Terraria.GameInput.PlayerInput.GamepadAllowScrolling, Terraria.ID.ItemID.Sets.GamepadExtraRange, Terraria.GameInput.PlayerInput.GamepadScrollValue, Terraria.GameInput.PlayerInput.GamepadThumbstickLeft, Terraria.GameInput.PlayerInput.GamepadThumbstickRight, Terraria.ID.ItemID.Sets.GamepadWholeScreenUseRange, Terraria.Main.GameViewMatrix, Terraria.GameInput.PlayerInput.HandleDpadSnap(), Terraria.Entity.height, Terraria.Player.HeldItem, Terraria.GameInput.PlayerInput.InBuildingMode, Terraria.GameInput.PlayerInputProfile.InputModes, Terraria.Main.instance, Terraria.Player.inventory, Terraria.GameInput.PlayerInputProfile.LeftThumbstickDeadzoneX, Terraria.GameInput.PlayerInputProfile.LeftThumbstickDeadzoneY, Terraria.GameInput.PlayerInputProfile.LeftThumbstickInvertX, Terraria.GameInput.PlayerInputProfile.LeftThumbstickInvertY, Terraria.Main.mapFullscreen, Terraria.Main.mapFullscreenScale, Terraria.Item.mech, Terraria.Player.mount, Terraria.GameInput.PlayerInput.MouseX, Terraria.GameInput.PlayerInput.MouseY, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.GameInput.PlayerInput.PreventCursorModeSwappingToGamepad, Terraria.Main.ReverseGravitySupport(), Terraria.GameInput.PlayerInputProfile.RightThumbstickDeadzoneX, Terraria.GameInput.PlayerInputProfile.RightThumbstickDeadzoneY, Terraria.GameInput.PlayerInputProfile.RightThumbstickInvertX, Terraria.GameInput.PlayerInputProfile.RightThumbstickInvertY, Terraria.Player.scope, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.GameInput.PlayerInput.ScrollWheelValue, Terraria.Player.selectedItem, Terraria.Main.SetCameraGamepadLerp(), Terraria.GameInput.PlayerInput.SettingsForUI.SetCursorMode(), Terraria.Main.SettingBlockGamepadsEntirely, Terraria.Item.shoot, Terraria.Player.sign, Terraria.Main.SmartCursorWanted, Terraria.GameInput.PlayerInput.smartSelectPointer, Terraria.GameInput.PlayerInput.SteamDeckIsUsed, Terraria.Player.talkNPC, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Item.tileWand, Terraria.GameInput.PlayerInput.Triggers, Terraria.GameInput.PlayerInputProfile.TriggersDeadzone, Terraria.Item.type, Terraria.Mount.Type, Terraria.GameInput.SmartSelectGamepadPointer.UpdateCenter(), Terraria.GameInput.SmartSelectGamepadPointer.UpdateSize(), Terraria.Entity.velocity, Terraria.ID.ItemID.Sets.Yoyo, and Terraria.Player.yoyoString.
Referenced by Terraria.GameInput.PlayerInput.UpdateInput().