TModLoader: Terraria.UI.UIElement.GetClippingRectangle
GetClippingRectangle()
Rectangle Terraria.UI.UIElement.GetClippingRectangle (SpriteBatch spriteBatch) inline inherited
Definition at line 287 of file UIElement.cs.
    {
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(_innerDimensions.X, _innerDimensions.Y);
        Vector2 position = new Vector2(_innerDimensions.Width, _innerDimensions.Height) + vector;
        vector = Vector2.Transform(vector, Main.UIScaleMatrix);
        position = Vector2.Transform(position, Main.UIScaleMatrix);
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector((int)vector.X, (int)vector.Y, (int)(position.X - vector.X), (int)(position.Y - vector.Y));
        int num = (int)((float)Main.screenWidth * Main.UIScale);
        int num2 = (int)((float)Main.screenHeight * Main.UIScale);
        rectangle.X = Utils.Clamp(rectangle.X, 0, num);
        rectangle.Y = Utils.Clamp(rectangle.Y, 0, num2);
        rectangle.Width = Utils.Clamp(rectangle.Width, 0, num - rectangle.X);
        rectangle.Height = Utils.Clamp(rectangle.Height, 0, num2 - rectangle.Y);
        Rectangle scissorRectangle = ((GraphicsResource)spriteBatch).GraphicsDevice.ScissorRectangle;
        int num3 = Utils.Clamp(((Rectangle)(ref rectangle)).Left, ((Rectangle)(ref scissorRectangle)).Left, ((Rectangle)(ref scissorRectangle)).Right);
        int num4 = Utils.Clamp(((Rectangle)(ref rectangle)).Top, ((Rectangle)(ref scissorRectangle)).Top, ((Rectangle)(ref scissorRectangle)).Bottom);
        int num5 = Utils.Clamp(((Rectangle)(ref rectangle)).Right, ((Rectangle)(ref scissorRectangle)).Left, ((Rectangle)(ref scissorRectangle)).Right);
        int num6 = Utils.Clamp(((Rectangle)(ref rectangle)).Bottom, ((Rectangle)(ref scissorRectangle)).Top, ((Rectangle)(ref scissorRectangle)).Bottom);
        return new Rectangle(num3, num4, num5 - num3, num6 - num4);
    }
References Terraria.UI.UIElement._innerDimensions, Terraria.UI.CalculatedStyle.Height, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.Top, Terraria.Main.UIScale, Terraria.Main.UIScaleMatrix, Terraria.UI.CalculatedStyle.Width, Terraria.UI.CalculatedStyle.X, and Terraria.UI.CalculatedStyle.Y.
Referenced by Terraria.UI.UIElement.Draw(), Terraria.GameContent.UI.States.UIEmotesMenu.RemoveSnapPointsOutOfScreen(), Terraria.GameContent.UI.States.UICharacterSelect.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIManageControls.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.SetupGamepadPoints(), and Terraria.GameContent.UI.States.UIWorldSelect.SetupGamepadPoints().