TModLoader: Terraria.UI.UIElement.MouseOver
MouseOver()
virtual void Terraria.UI.UIElement.MouseOver (UIMouseEvent evt) inline virtual inherited
Reimplemented in Terraria.GameContent.UI.Elements.EmoteButton, Terraria.GameContent.UI.Elements.GroupOptionButton< T >, Terraria.GameContent.UI.Elements.UIAchievementListItem, Terraria.GameContent.UI.Elements.UICharacterListItem, Terraria.GameContent.UI.Elements.UICharacterNameButton, Terraria.GameContent.UI.Elements.UIClothStyleButton, Terraria.GameContent.UI.Elements.UIColoredImageButton, Terraria.GameContent.UI.Elements.UIDifficultyButton, Terraria.GameContent.UI.Elements.UIHairStyleButton, Terraria.GameContent.UI.Elements.UIIconTextButton, Terraria.GameContent.UI.Elements.UIImageButton, Terraria.GameContent.UI.Elements.UIList, Terraria.GameContent.UI.Elements.UIResourcePack, Terraria.GameContent.UI.Elements.UIScrollbar, Terraria.GameContent.UI.Elements.UISearchBar, Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem, Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem, Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem, Terraria.GameContent.UI.Elements.UIWorldListItem, Terraria.ModLoader.Config.UI.NestedUIList, Terraria.ModLoader.UI.Elements.UIGrid, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem, Terraria.ModLoader.UI.UIButton< T >, Terraria.ModLoader.UI.UIModItem, Terraria.ModLoader.UI.UIModPackItem, and Terraria.ModLoader.UI.UIModSourceItem.
Definition at line 585 of file UIElement.cs.
    {
        IsMouseHovering = true;
        if (this.OnMouseOver != null)
        {
            this.OnMouseOver(evt, this);
        }
        if (Parent != null)
        {
            Parent.MouseOver(evt);
        }
    }
References Terraria.UI.UIElement.IsMouseHovering, Terraria.UI.UIElement.MouseOver(), Terraria.UI.UIElement.OnMouseOver, and Terraria.UI.UIElement.Parent.
Referenced by Terraria.UI.UIElement.MouseOver(), and Terraria.UI.UserInterface.Update_Inner().