TModLoader: Terraria.UI.UIElement.RemoveChild
RemoveChild()
void Terraria.UI.UIElement.RemoveChild (UIElement child) inline inherited
    {
        Elements.Remove(child);
        child.Parent = null;
    }
Referenced by Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.UIBestiaryEntryButton(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.CheckIfAnyModUpdateIsAvailable(), Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.CheckScrollBar(), Terraria.GameContent.UI.States.UIBestiaryTest.CloseFilteringGrid(), Terraria.GameContent.UI.States.UIBestiaryTest.CloseSortingGrid(), Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.MouseOut(), Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.MouseOver(), Terraria.ModLoader.Config.UI.UIModConfig.OnActivate(), Terraria.ModLoader.UI.UIModPacks.OnActivate(), Terraria.GameContent.UI.States.UIBestiaryTest.OpenOrCloseFilteringGrid(), Terraria.GameContent.UI.States.UIBestiaryTest.OpenOrCloseSortingOptions(), Terraria.GameContent.UI.States.UICharacterSelect.Recalculate(), Terraria.GameContent.UI.States.UIEmotesMenu.Recalculate(), Terraria.GameContent.UI.States.UIReportsPage.Recalculate(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.Recalculate(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.Recalculate(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.Recalculate(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.Recalculate(), Terraria.GameContent.UI.States.UIWorldSelect.Recalculate(), Terraria.UI.UIElement.Remove(), Terraria.GameContent.UI.Elements.UIList.Remove(), Terraria.ModLoader.UI.Elements.UIGrid.Remove(), Terraria.ModLoader.Config.UI.UIModConfig.Unload(), Terraria.ModLoader.Config.UI.CollectionElement.Update(), Terraria.ModLoader.UI.UICreateMod.Update(), Terraria.ModLoader.UI.UIExpandablePanel.Update(), Terraria.ModLoader.UI.UIModInfo.Update(), Terraria.ModLoader.UI.UIMods.Update(), Terraria.ModLoader.UI.UIModSources.Update(), and Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.UpdateScrollbar().