TModLoader: Terraria.ModLoader.Core.ModCompile.BuildModCommandLine
BuildModCommandLine()
static void Terraria.ModLoader.Core.ModCompile.BuildModCommandLine (string modFolder) inline static package
Definition at line 192 of file ModCompile.cs.
    {
        UpdateReferencesFolder();
        LanguageManager.Instance.SetLanguage(GameCulture.DefaultCulture);
        Lang.InitializeLegacyLocalization();
        try
        {
            new ModCompile(new ConsoleBuildStatus()).Build(modFolder);
        }
        catch (BuildException e2)
        {
            Console.Error.WriteLine("Error: " + e2.Message);
            if (e2.InnerException != null)
            {
                Console.Error.WriteLine(e2.InnerException);
            }
            Environment.Exit(1);
        }
        catch (Exception e)
        {
            Console.Error.WriteLine(e);
            Environment.Exit(1);
        }
        WorkshopSocialModule.SteamCMDPublishPreparer(modFolder);
        Environment.Exit(0);
    }
References Terraria.ModLoader.Core.ModCompile.Build(), Terraria.ModLoader.Console, Terraria.Localization.GameCulture.DefaultCulture, Terraria.ModLoader.Environment, Terraria.Lang.InitializeLegacyLocalization(), Terraria.Localization.LanguageManager.Instance, Terraria.Localization.LanguageManager.SetLanguage(), Terraria.Social.Steam.WorkshopSocialModule.SteamCMDPublishPreparer(), and Terraria.ModLoader.Core.ModCompile.UpdateReferencesFolder().
Referenced by Terraria.Program.LaunchGame_().