TModLoader: Terraria.ModLoader.Core.ModCompile.Build
Build() [1/2]
void Terraria.ModLoader.Core.ModCompile.Build (BuildingMod mod) inline private
    {
        try
        {
            status.SetStatus(Language.GetTextValue("tModLoader.Building", mod.Name));
            BuildMod(mod, out var code, out var pdb);
            mod.modFile.AddFile(mod.Name + ".dll", code);
            if (pdb != null)
            {
                mod.modFile.AddFile(mod.Name + ".pdb", pdb);
            }
            PackageMod(mod);
            if (ModLoader.TryGetMod(mod.Name, out var loadedMod))
            {
                loadedMod.Close();
            }
            mod.modFile.Save();
            ModLoader.EnableMod(mod.Name);
            LocalizationLoader.HandleModBuilt(mod.Name);
        }
        catch (Exception ex)
        {
            ex.Data["mod"] = mod.Name;
            throw;
        }
    }
References Terraria.ModLoader.Core.ModCompile.BuildMod(), Terraria.ModLoader.ModLoader.EnableMod(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.LocalizationLoader.HandleModBuilt(), Terraria.ModLoader.Core.LocalMod.modFile, Terraria.ModLoader.Core.LocalMod.Name, Terraria.ModLoader.Core.ModCompile.PackageMod(), Terraria.ModLoader.Core.ModCompile.IBuildStatus.SetStatus(), Terraria.ModLoader.Core.ModCompile.status, and Terraria.ModLoader.ModLoader.TryGetMod().