TModLoader: Terraria.ModLoader.Core.ModCompile.CompileMod
CompileMod()
void Terraria.ModLoader.Core.ModCompile.CompileMod (BuildingMod mod, out byte[] code, out byte[] pdb) inline private
    {
        status.SetStatus(Language.GetTextValue("tModLoader.Compiling", mod.Name + ".dll"));
        string tempDir = Path.Combine(mod.path, "compile_temp");
        if (Directory.Exists(tempDir))
        {
            Directory.Delete(tempDir, recursive: true);
        }
        Directory.CreateDirectory(tempDir);
        List<string> refs = new List<string>();
        refs.AddRange(GetTerrariaReferences());
        refs.AddRange(mod.properties.dllReferences.Select((string dllName) => DllRefPath(mod, dllName)));
        foreach (LocalMod refMod in FindReferencedMods(mod.properties))
        {
            using (refMod.modFile.Open())
            {
                string path = Path.Combine(tempDir, refMod?.ToString() + ".dll");
                File.WriteAllBytes(path, refMod.modFile.GetModAssembly());
                refs.Add(path);
                string[] dllReferences = refMod.properties.dllReferences;
                foreach (string refDll in dllReferences)
                {
                    path = Path.Combine(tempDir, refDll + ".dll");
                    File.WriteAllBytes(path, refMod.modFile.GetBytes("lib/" + refDll + ".dll"));
                    refs.Add(path);
                }
            }
        }
        string[] files = (from file in Directory.GetFiles(mod.path, "*.cs", SearchOption.AllDirectories)
            where !IgnoreCompletely(mod, file)
            select file).ToArray();
        string unsafeParam;
        bool _allowUnsafe = default(bool);
        bool allowUnsafe = Program.LaunchParameters.TryGetValue("-unsafe", out unsafeParam) && bool.TryParse(unsafeParam, out _allowUnsafe) && _allowUnsafe;
        List<string> preprocessorSymbols = new List<string> { "FNA" };
        if (Program.LaunchParameters.TryGetValue("-define", out var defineParam))
        {
            preprocessorSymbols.AddRange(defineParam.Split(';', ' '));
        }
        if (BuildInfo.IsStable)
        {
            string tmlVersionPreprocessorSymbol = $"TML_{BuildInfo.tMLVersion.Major}_{BuildInfo.tMLVersion.Minor:D2}";
            preprocessorSymbols.Add(tmlVersionPreprocessorSymbol);
        }
        Diagnostic[] results = RoslynCompile(mod.Name, refs, files, preprocessorSymbols.ToArray(), allowUnsafe, out code, out pdb);
        int numWarnings = results.Count((Diagnostic e) => e.Severity == DiagnosticSeverity.Warning);
        int numErrors = results.Length - numWarnings;
        status.LogCompilerLine(Language.GetTextValue("tModLoader.CompilationResult", numErrors, numWarnings), Level.Info);
        Diagnostic[] array = results;
        foreach (Diagnostic line in array)
        {
            status.LogCompilerLine(line.ToString(), (line.Severity == DiagnosticSeverity.Warning) ? Level.Warn : Level.Error);
        }
        try
        {
            if (Directory.Exists(tempDir))
            {
                Directory.Delete(tempDir, recursive: true);
            }
        }
        catch (Exception)
        {
        }
        if (numErrors > 0)
        {
            Diagnostic firstError = results.First((Diagnostic e) => e.Severity == DiagnosticSeverity.Error);
            throw new BuildException(Language.GetTextValue("tModLoader.CompileError", mod.Name + ".dll", numErrors, numWarnings) + $"\nError: {firstError}");
        }
    }
References Terraria.ModLoader.Core.ModCompile.DllRefPath(), Terraria.ModLoader.Core.ModCompile.FindReferencedMods(), Terraria.ModLoader.Core.ModCompile.GetTerrariaReferences(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.Core.ModCompile.IgnoreCompletely(), Terraria.ModLoader.BuildInfo.IsStable, Terraria.Program.LaunchParameters, Terraria.ModLoader.Core.ModCompile.IBuildStatus.LogCompilerLine(), Terraria.ModLoader.Core.LocalMod.Name, Terraria.ModLoader.Core.ModCompile.BuildingMod.path, Terraria.ModLoader.Core.LocalMod.properties, Terraria.ModLoader.Core.ModCompile.RoslynCompile(), Terraria.ModLoader.Core.ModCompile.IBuildStatus.SetStatus(), and Terraria.ModLoader.Core.ModCompile.status.
Referenced by Terraria.ModLoader.Core.ModCompile.BuildMod().