TModLoader: Terraria.ModLoader.Core.ModCompile.BuildAll
BuildAll()
void Terraria.ModLoader.Core.ModCompile.BuildAll () inline package
    {
        List<LocalMod> modList = new List<LocalMod>();
        string[] array = FindModSources();
        foreach (string modFolder in array)
        {
            modList.Add(ReadBuildInfo(modFolder));
        }
        List<LocalMod> installedMods = (from mod in ModOrganizer.FindMods()
            where !modList.Exists((LocalMod m) => m.Name == mod.Name)
            select mod).ToList();
        HashSet<LocalMod> requiredFromInstall = new HashSet<LocalMod>();
        foreach (LocalMod mod3 in modList)
        {
            Require(mod3, includeWeak: true);
        }
        modList.AddRange(requiredFromInstall);
        List<BuildingMod> modsToBuild;
        try
        {
            ModOrganizer.EnsureDependenciesExist(modList, includeWeak: true);
            ModOrganizer.EnsureTargetVersionsMet(modList);
            modsToBuild = ModOrganizer.Sort(modList).OfType<BuildingMod>().ToList();
        }
        catch (ModSortingException ex)
        {
            throw new BuildException(ex.Message);
        }
        int num = 0;
        foreach (BuildingMod mod2 in modsToBuild)
        {
            status.SetProgress(num++, modsToBuild.Count);
            Build(mod2);
        }
        void Require(LocalMod mod, bool includeWeak)
        {
            foreach (string dep in mod.properties.RefNames(includeWeak))
            {
                LocalMod depMod = installedMods.SingleOrDefault((LocalMod m) => m.Name == dep);
                if (depMod != null && requiredFromInstall.Add(depMod))
                {
                    Require(depMod, includeWeak: false);
                }
            }
        }
    }
References Terraria.ModLoader.Core.ModCompile.Build(), Terraria.ModLoader.Core.ModOrganizer.EnsureDependenciesExist(), Terraria.ModLoader.Core.ModOrganizer.EnsureTargetVersionsMet(), Terraria.ModLoader.Core.ModOrganizer.FindMods(), Terraria.ModLoader.Core.ModCompile.FindModSources(), Terraria.ModLoader.Core.LocalMod.properties, Terraria.ModLoader.Core.ModCompile.ReadBuildInfo(), Terraria.ModLoader.Core.ModCompile.IBuildStatus.SetProgress(), Terraria.ModLoader.Core.ModOrganizer.Sort(), and Terraria.ModLoader.Core.ModCompile.status.