TModLoader: Terraria.ModLoader.Core.ModCompile.BuildMod
BuildMod()
void Terraria.ModLoader.Core.ModCompile.BuildMod (BuildingMod mod, out byte[] code, out byte[] pdb) inline private
Definition at line 366 of file ModCompile.cs.
    {
        string dllName = mod.Name + ".dll";
        string dllPath = null;
        string eacValue;
        if (mod.properties.noCompile)
        {
            dllPath = Path.Combine(mod.path, dllName);
        }
        else if (Program.LaunchParameters.TryGetValue("-eac", out eacValue))
        {
            dllPath = eacValue;
            mod.properties.eacPath = pdbPath();
            status.SetStatus(Language.GetTextValue("tModLoader.EnabledEAC", mod.properties.eacPath));
        }
        if (dllPath != null)
        {
            if (!File.Exists(dllPath))
            {
                throw new BuildException(Language.GetTextValue("tModLoader.BuildErrorLoadingPrecompiled", dllPath));
            }
            status.SetStatus(Language.GetTextValue("tModLoader.LoadingPrecompiled", dllName, Path.GetFileName(dllPath)));
            code = File.ReadAllBytes(dllPath);
            pdb = (File.Exists(pdbPath()) ? File.ReadAllBytes(pdbPath()) : null);
        }
        else
        {
            CompileMod(mod, out code, out pdb);
        }
        string pdbPath()
        {
            return Path.ChangeExtension(dllPath, "pdb");
        }
    }
References Terraria.ModLoader.Core.ModCompile.CompileMod(), Terraria.Localization.Language.GetTextValue(), Terraria.Program.LaunchParameters, Terraria.ModLoader.Core.ModCompile.BuildingMod.path, Terraria.ModLoader.Core.LocalMod.properties, Terraria.ModLoader.Core.ModCompile.IBuildStatus.SetStatus(), and Terraria.ModLoader.Core.ModCompile.status.
Referenced by Terraria.ModLoader.Core.ModCompile.Build().