TModLoader: Terraria.ModLoader.Core.ModCompile.ReadBuildInfo
ReadBuildInfo()
BuildingMod Terraria.ModLoader.Core.ModCompile.ReadBuildInfo (string modFolder) inline private
    {
        if (modFolder.EndsWith("\\") || modFolder.EndsWith("/"))
        {
            modFolder = modFolder.Substring(0, modFolder.Length - 1);
        }
        string modName = Path.GetFileName(modFolder);
        status.SetStatus(Language.GetTextValue("tModLoader.ReadingProperties", modName));
        BuildProperties properties;
        try
        {
            properties = BuildProperties.ReadBuildFile(modFolder);
        }
        catch (Exception e)
        {
            throw new BuildException(Language.GetTextValue("tModLoader.BuildErrorFailedLoadBuildTxt", Path.Combine(modFolder, "build.txt")), e);
        }
        return new BuildingMod(new TmodFile(Path.Combine(ModLoader.ModPath, modName + ".tmod"), modName, properties.version), properties, modFolder);
    }
References Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.ModLoader.ModPath, Terraria.ModLoader.Core.BuildProperties.ReadBuildFile(), Terraria.ModLoader.Core.ModCompile.IBuildStatus.SetStatus(), Terraria.ModLoader.Core.ModCompile.status, and Terraria.ModLoader.Core.BuildProperties.version.
Referenced by Terraria.ModLoader.Core.ModCompile.Build(), and Terraria.ModLoader.Core.ModCompile.BuildAll().