TModLoader: Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DrawMarkedArea
DrawMarkedArea()
void Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DrawMarkedArea (SpriteBatch sb) inline
Definition at line 914 of file CaptureInterface.cs.
        {
            //IL_012d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0134: Unknown result type (might be due to invalid IL or missing references)
            //IL_013b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0142: Unknown result type (might be due to invalid IL or missing references)
            //IL_014a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0151: Unknown result type (might be due to invalid IL or missing references)
            //IL_0180: Unknown result type (might be due to invalid IL or missing references)
            //IL_0097: Unknown result type (might be due to invalid IL or missing references)
            //IL_009c: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
            //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
            //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
            //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
            //IL_00de: Unknown result type (might be due to invalid IL or missing references)
            //IL_0189: Unknown result type (might be due to invalid IL or missing references)
            //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
            //IL_0195: Unknown result type (might be due to invalid IL or missing references)
            //IL_019d: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
            //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
            //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
            //IL_01b7: Unknown result type (might be due to invalid IL or missing references)
            //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
            //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
            //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
            //IL_02be: Unknown result type (might be due to invalid IL or missing references)
            //IL_0212: Unknown result type (might be due to invalid IL or missing references)
            //IL_0219: Unknown result type (might be due to invalid IL or missing references)
            //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
            //IL_02cc: Unknown result type (might be due to invalid IL or missing references)
            //IL_0229: Unknown result type (might be due to invalid IL or missing references)
            //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
            //IL_0231: Unknown result type (might be due to invalid IL or missing references)
            //IL_01fb: Unknown result type (might be due to invalid IL or missing references)
            //IL_0203: Unknown result type (might be due to invalid IL or missing references)
            //IL_0282: Unknown result type (might be due to invalid IL or missing references)
            //IL_024c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0292: Unknown result type (might be due to invalid IL or missing references)
            //IL_025c: Unknown result type (might be due to invalid IL or missing references)
            //IL_029a: Unknown result type (might be due to invalid IL or missing references)
            //IL_02a2: Unknown result type (might be due to invalid IL or missing references)
            //IL_0264: Unknown result type (might be due to invalid IL or missing references)
            //IL_026c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0273: Unknown result type (might be due to invalid IL or missing references)
            if (!EdgeAPinned || !EdgeBPinned)
            {
                return;
            }
            int num = Math.Min(EdgeA.X, EdgeB.X);
            int num2 = Math.Min(EdgeA.Y, EdgeB.Y);
            int num3 = Math.Abs(EdgeA.X - EdgeB.X);
            int num4 = Math.Abs(EdgeA.Y - EdgeB.Y);
            Rectangle result = default(Rectangle);
            if (!Main.mapFullscreen)
            {
                Rectangle value = Main.ReverseGravitySupport(new Rectangle(num * 16, num2 * 16, (num3 + 1) * 16, (num4 + 1) * 16));
                Rectangle value3 = Main.ReverseGravitySupport(new Rectangle((int)Main.screenPosition.X, (int)Main.screenPosition.Y, Main.screenWidth + 1, Main.screenHeight + 1));
                Rectangle.Intersect(ref value3, ref value, ref result);
                if (result.Width == 0 || result.Height == 0)
                {
                    return;
                }
                ((Rectangle)(ref result)).Offset(-value3.X, -value3.Y);
            }
            else
            {
                GetMapCoords(num, num2, 1, out var result2);
                GetMapCoords(num + num3 + 1, num2 + num4 + 1, 1, out var result3);
                Rectangle value2 = default(Rectangle);
                ((Rectangle)(ref value2))._002Ector(result2.X, result2.Y, result3.X - result2.X, result3.Y - result2.Y);
                Rectangle value4 = default(Rectangle);
                ((Rectangle)(ref value4))._002Ector(0, 0, Main.screenWidth + 1, Main.screenHeight + 1);
                Rectangle.Intersect(ref value4, ref value2, ref result);
                if (result.Width == 0 || result.Height == 0)
                {
                    return;
                }
                ((Rectangle)(ref result)).Offset(-value4.X, -value4.Y);
            }
            sb.Draw(TextureAssets.MagicPixel.Value, result, Settings.MarkedAreaColor);
            Rectangle rectangle = Rectangle.Empty;
            for (int i = 0; i < 2; i++)
            {
                if (currentAim != i)
                {
                    DrawBound(sb, new Rectangle(result.X, result.Y + ((i == 1) ? result.Height : (-2)), result.Width, 2), 0);
                }
                else
                {
                    ((Rectangle)(ref rectangle))._002Ector(result.X, result.Y + ((i == 1) ? result.Height : (-2)), result.Width, 2);
                }
                if (currentAim != i + 2)
                {
                    DrawBound(sb, new Rectangle(result.X + ((i == 1) ? result.Width : (-2)), result.Y, 2, result.Height), 0);
                }
                else
                {
                    ((Rectangle)(ref rectangle))._002Ector(result.X + ((i == 1) ? result.Width : (-2)), result.Y, 2, result.Height);
                }
            }
            if (rectangle != Rectangle.Empty)
            {
                DrawBound(sb, rectangle, 1 + dragging.ToInt());
            }
        }
References Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.currentAim, Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.dragging, Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DrawBound(), Terraria.Graphics.Capture.CaptureInterface.EdgeA, Terraria.Graphics.Capture.CaptureInterface.EdgeAPinned, Terraria.Graphics.Capture.CaptureInterface.EdgeB, Terraria.Graphics.Capture.CaptureInterface.EdgeBPinned, Terraria.Graphics.Capture.CaptureInterface.GetMapCoords(), Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.mapFullscreen, Terraria.Graphics.Capture.CaptureInterface.Settings.MarkedAreaColor, Terraria.Main.ReverseGravitySupport(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, and Terraria.Main.screenWidth.
Referenced by Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.Draw().