TModLoader: Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DragBounds
DragBounds()
void Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DragBounds (Vector2 mouse) inline private
Definition at line 646 of file CaptureInterface.cs.
        {
            //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e4: Unknown result type (might be due to invalid IL or missing references)
            //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
            //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
            //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
            //IL_0201: Unknown result type (might be due to invalid IL or missing references)
            //IL_0230: Unknown result type (might be due to invalid IL or missing references)
            //IL_0147: Unknown result type (might be due to invalid IL or missing references)
            //IL_014c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0151: Unknown result type (might be due to invalid IL or missing references)
            //IL_0177: Unknown result type (might be due to invalid IL or missing references)
            //IL_017c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0181: Unknown result type (might be due to invalid IL or missing references)
            //IL_018e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0040: Unknown result type (might be due to invalid IL or missing references)
            //IL_0047: Unknown result type (might be due to invalid IL or missing references)
            //IL_002c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0031: Unknown result type (might be due to invalid IL or missing references)
            //IL_0032: Unknown result type (might be due to invalid IL or missing references)
            //IL_0037: Unknown result type (might be due to invalid IL or missing references)
            //IL_003c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0239: Unknown result type (might be due to invalid IL or missing references)
            //IL_0197: Unknown result type (might be due to invalid IL or missing references)
            //IL_0245: Unknown result type (might be due to invalid IL or missing references)
            //IL_024d: Unknown result type (might be due to invalid IL or missing references)
            //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
            //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
            //IL_0069: Unknown result type (might be due to invalid IL or missing references)
            //IL_006b: Unknown result type (might be due to invalid IL or missing references)
            //IL_007d: Unknown result type (might be due to invalid IL or missing references)
            //IL_007f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0352: Unknown result type (might be due to invalid IL or missing references)
            //IL_0354: Unknown result type (might be due to invalid IL or missing references)
            //IL_0358: Unknown result type (might be due to invalid IL or missing references)
            //IL_0360: Unknown result type (might be due to invalid IL or missing references)
            //IL_0370: Unknown result type (might be due to invalid IL or missing references)
            //IL_0371: Unknown result type (might be due to invalid IL or missing references)
            //IL_0284: Unknown result type (might be due to invalid IL or missing references)
            //IL_029f: Unknown result type (might be due to invalid IL or missing references)
            //IL_02a6: Unknown result type (might be due to invalid IL or missing references)
            //IL_0291: Unknown result type (might be due to invalid IL or missing references)
            //IL_0296: Unknown result type (might be due to invalid IL or missing references)
            //IL_029b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0389: Unknown result type (might be due to invalid IL or missing references)
            //IL_038d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0392: Unknown result type (might be due to invalid IL or missing references)
            //IL_039f: Unknown result type (might be due to invalid IL or missing references)
            //IL_03a0: Unknown result type (might be due to invalid IL or missing references)
            //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
            //IL_02ba: Unknown result type (might be due to invalid IL or missing references)
            //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
            //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
            //IL_031d: Unknown result type (might be due to invalid IL or missing references)
            //IL_033a: Unknown result type (might be due to invalid IL or missing references)
            if (!EdgeAPinned || !EdgeBPinned)
            {
                bool flag = false;
                if (Main.mouseLeft)
                {
                    flag = true;
                }
                if (flag)
                {
                    bool flag2 = true;
                    Point result;
                    if (!Main.mapFullscreen)
                    {
                        result = (Main.screenPosition + mouse).ToTileCoordinates();
                    }
                    else
                    {
                        flag2 = GetMapCoords((int)mouse.X, (int)mouse.Y, 0, out result);
                    }
                    if (flag2)
                    {
                        if (!EdgeAPinned)
{
                            EdgeAPinned = true;
                            EdgeA = result;
                        }
                        if (!EdgeBPinned)
{
                            EdgeBPinned = true;
                            EdgeB = result;
                        }
                    }
                    currentAim = 3;
                    caughtEdge = 1;
                }
            }
            int num = Math.Min(EdgeA.X, EdgeB.X);
            int num2 = Math.Min(EdgeA.Y, EdgeB.Y);
            int num3 = Math.Abs(EdgeA.X - EdgeB.X);
            int num4 = Math.Abs(EdgeA.Y - EdgeB.Y);
            bool value = Main.player[Main.myPlayer].gravDir == -1f;
            int num5 = 1 - value.ToInt();
            int num6 = value.ToInt();
            Rectangle value2 = default(Rectangle);
            Rectangle value3 = default(Rectangle);
            Rectangle result2 = default(Rectangle);
            if (!Main.mapFullscreen)
            {
                value2 = Main.ReverseGravitySupport(new Rectangle(num * 16, num2 * 16, (num3 + 1) * 16, (num4 + 1) * 16));
                value3 = Main.ReverseGravitySupport(new Rectangle((int)Main.screenPosition.X, (int)Main.screenPosition.Y, Main.screenWidth + 1, Main.screenHeight + 1));
                Rectangle.Intersect(ref value3, ref value2, ref result2);
                if (result2.Width == 0 || result2.Height == 0)
                {
                    return;
                }
                ((Rectangle)(ref result2)).Offset(-value3.X, -value3.Y);
            }
            else
            {
                GetMapCoords(num, num2, 1, out var result3);
                GetMapCoords(num + num3 + 1, num2 + num4 + 1, 1, out var result4);
                ((Rectangle)(ref value2))._002Ector(result3.X, result3.Y, result4.X - result3.X, result4.Y - result3.Y);
                ((Rectangle)(ref value3))._002Ector(0, 0, Main.screenWidth + 1, Main.screenHeight + 1);
                Rectangle.Intersect(ref value3, ref value2, ref result2);
                if (result2.Width == 0 || result2.Height == 0)
                {
                    return;
                }
                ((Rectangle)(ref result2)).Offset(-value3.X, -value3.Y);
            }
            dragging = false;
            if (!Main.mouseLeft)
            {
                currentAim = -1;
            }
            if (currentAim != -1)
            {
                dragging = true;
                Point point = default(Point);
                if (!Main.mapFullscreen)
                {
                    point = Main.MouseWorld.ToTileCoordinates();
                }
                else
                {
                    if (!GetMapCoords((int)mouse.X, (int)mouse.Y, 0, out var result5))
                    {
                        return;
                    }
                    point = result5;
                }
                switch (currentAim)
                {
                case 0:
                case 1:
                    if (caughtEdge == 0)
                    {
                        EdgeA.Y = point.Y;
                    }
                    if (caughtEdge == 1)
                    {
                        EdgeB.Y = point.Y;
                    }
                    break;
                case 2:
                case 3:
                    if (caughtEdge == 0)
                    {
                        EdgeA.X = point.X;
                    }
                    if (caughtEdge == 1)
                    {
                        EdgeB.X = point.X;
                    }
                    break;
                }
            }
            else
            {
                caughtEdge = -1;
                Rectangle drawbox = value2;
                ((Rectangle)(ref drawbox)).Offset(-value3.X, -value3.Y);
                inMap = ((Rectangle)(ref drawbox)).Contains(mouse.ToPoint());
                for (int i = 0; i < 4; i++)
                {
                    Rectangle bound = GetBound(drawbox, i);
                    ((Rectangle)(ref bound)).Inflate(8, 8);
                    if (!((Rectangle)(ref bound)).Contains(mouse.ToPoint()))
                    {
                        continue;
                    }
                    currentAim = i;
                    switch (i)
                    {
                    case 0:
                        if (EdgeA.Y < EdgeB.Y)
{
                            caughtEdge = num6;
                        }
                        else
{
                            caughtEdge = num5;
                        }
                        break;
                    case 1:
                        if (EdgeA.Y >= EdgeB.Y)
{
                            caughtEdge = num6;
                        }
                        else
{
                            caughtEdge = num5;
                        }
                        break;
                    case 2:
                        if (EdgeA.X < EdgeB.X)
{
                            caughtEdge = 0;
                        }
                        else
{
                            caughtEdge = 1;
                        }
                        break;
                    case 3:
                        if (EdgeA.X >= EdgeB.X)
{
                            caughtEdge = 0;
                        }
                        else
{
                            caughtEdge = 1;
                        }
                        break;
                    }
                    break;
                }
            }
            ConstraintPoints();
        }
References Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.caughtEdge, Terraria.Graphics.Capture.CaptureInterface.ConstraintPoints(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.currentAim, Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.dragging, Terraria.Graphics.Capture.CaptureInterface.EdgeA, Terraria.Graphics.Capture.CaptureInterface.EdgeAPinned, Terraria.Graphics.Capture.CaptureInterface.EdgeB, Terraria.Graphics.Capture.CaptureInterface.EdgeBPinned, Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.GetBound(), Terraria.Graphics.Capture.CaptureInterface.GetMapCoords(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.inMap, Terraria.Main.mapFullscreen, Terraria.Main.mouseLeft, Terraria.Main.MouseWorld, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.ReverseGravitySupport(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, and Terraria.Main.screenWidth.
Referenced by Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.Update().