TModLoader: Terraria.ModLoader.UI.UIInputTextField.DrawSelf
DrawSelf()
override void Terraria.ModLoader.UI.UIInputTextField.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 44 of file UIInputTextField.cs.
    {
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        if (((KeyboardState)(ref Main.keyState)).IsKeyDown((Keys)27) && !((KeyboardState)(ref Main.oldKeyState)).IsKeyDown((Keys)27))
        {
            UILinksInitializer.FancyExit();
        }
        PlayerInput.WritingText = true;
        Main.instance.HandleIME();
        string newString = Main.GetInputText(_currentString);
        if (newString != _currentString)
        {
            _currentString = newString;
            this.OnTextChange?.Invoke(this, EventArgs.Empty);
        }
        string displayString = _currentString;
        if (++_textBlinkerCount / 20 % 2 == 0)
        {
            displayString += "|";
        }
        CalculatedStyle space = GetDimensions();
        if (_currentString.Length == 0)
        {
            Utils.DrawBorderString(spriteBatch, _hintText, new Vector2(space.X, space.Y), Color.Gray);
        }
        else
        {
            Utils.DrawBorderString(spriteBatch, displayString, new Vector2(space.X, space.Y), Color.White);
        }
    }
References Terraria.ModLoader.UI.UIInputTextField._currentString, Terraria.ModLoader.UI.UIInputTextField._hintText, Terraria.ModLoader.UI.UIInputTextField._textBlinkerCount, Terraria.Utils.DrawBorderString(), Terraria.Initializers.UILinksInitializer.FancyExit(), Terraria.UI.UIElement.GetDimensions(), Terraria.Main.GetInputText(), Terraria.Main.HandleIME(), Terraria.Main.instance, Terraria.Main.keyState, and Terraria.Main.oldKeyState.