TModLoader: Terraria.ModLoader.UI.UIAutoScaleTextTextPanel.SetText
SetText() [1/2]
void Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.SetText (T text) inline inherited
    {
        SetText(text, TextScaleMax, IsLarge);
    }
References Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.IsLarge, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.SetText(), and Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.TextScaleMax.
Referenced by Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.UIAutoScaleTextTextPanel(), Terraria.ModLoader.UI.UIModInfo.ExtractLocalization(), Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.Recalculate(), Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.SetText(), Terraria.ModLoader.UI.UIModInfo.Update(), and Terraria.ModLoader.UI.UIProgressBar.Update().