TModLoader: Terraria.ModLoader.UI.UIAutoScaleTextTextPanel.DrawSelf
DrawSelf()
override void Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.DrawSelf (SpriteBatch spriteBatch) inline protected virtual inherited
Reimplemented from Terraria.GameContent.UI.Elements.UIPanel.
    {
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        if (float.IsNaN(TextScale))
        {
            Recalculate();
        }
        if (DrawPanel)
        {
            base.DrawSelf(spriteBatch);
        }
        Rectangle innerDimensions = (UseInnerDimensions ? GetInnerDimensions().ToRectangle() : GetDimensions().ToRectangle());
        if (UseInnerDimensions)
        {
            ((Rectangle)(ref innerDimensions)).Inflate(0, 6);
        }
        else
        {
            ((Rectangle)(ref innerDimensions)).Inflate(-4, -8);
        }
        for (int i = 0; i < textStrings.Length; i++)
        {
            Vector2 pos = innerDimensions.TopLeft() + drawOffsets[i];
            if (IsLarge)
            {
                Utils.DrawBorderStringBig(spriteBatch, textStrings[i], pos, TextColor, TextScale);
            }
            else
            {
                Utils.DrawBorderString(spriteBatch, textStrings[i], pos, TextColor, TextScale);
            }
        }
    }
References Terraria.Utils.DrawBorderString(), Terraria.Utils.DrawBorderStringBig(), Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.drawOffsets, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.DrawPanel, Terraria.UI.UIElement.GetDimensions(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.IsLarge, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.Recalculate(), Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.TextColor, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.TextScale, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.textStrings, Terraria.UI.CalculatedStyle.ToRectangle(), and Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.UseInnerDimensions.