TModLoader: Terraria.ModLoader.UI.UIAutoScaleTextTextPanel.SetText
SetText() [2/2]
virtual void Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.SetText (T text, float textScaleMax, bool large) inline virtual inherited
Definition at line 80 of file UIAutoScaleTextTextPanel.cs.
    {
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0304: Unknown result type (might be due to invalid IL or missing references)
        //IL_031f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0331: Unknown result type (might be due to invalid IL or missing references)
        //IL_033a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0369: Unknown result type (might be due to invalid IL or missing references)
        //IL_036e: Unknown result type (might be due to invalid IL or missing references)
        if (ScalePanel)
        {
            Vector2 textSize = ChatManager.GetStringSize(IsLarge ? FontAssets.DeathText.Value : FontAssets.MouseText.Value, Text, new Vector2(TextScaleMax));
            Width.Set(PaddingLeft + textSize.X + PaddingRight, 0f);
            Height.Set(PaddingTop + (IsLarge ? 32f : 16f) + PaddingBottom, 0f);
            base.Recalculate();
        }
        Rectangle innerDimensionsRectangle = (UseInnerDimensions ? GetInnerDimensions().ToRectangle() : GetDimensions().ToRectangle());
        if (!(text.ToString() != oldText) && !(oldInnerDimensions != innerDimensionsRectangle))
        {
            return;
        }
        oldInnerDimensions = innerDimensionsRectangle;
        TextScaleMax = textScaleMax;
        DynamicSpriteFont dynamicSpriteFont = (large ? FontAssets.DeathText.Value : FontAssets.MouseText.Value);
        Vector2 textSize2 = ChatManager.GetStringSize(dynamicSpriteFont, text.ToString(), new Vector2(TextScaleMax));
        if (UseInnerDimensions)
        {
            ((Rectangle)(ref innerDimensionsRectangle)).Inflate(0, 6);
        }
        else
        {
            ((Rectangle)(ref innerDimensionsRectangle)).Inflate(-4, 0);
        }
        Vector2 availableSpace = default(Vector2);
        ((Vector2)(ref availableSpace))._002Ector((float)innerDimensionsRectangle.Width, (float)innerDimensionsRectangle.Height);
        if (textSize2.X > availableSpace.X || textSize2.Y > availableSpace.Y)
        {
            float scale = ((textSize2.X / availableSpace.X > textSize2.Y / availableSpace.Y) ? (availableSpace.X / textSize2.X) : (availableSpace.Y / textSize2.Y));
            TextScale = scale;
            textSize2 = ChatManager.GetStringSize(dynamicSpriteFont, text.ToString(), new Vector2(TextScale));
        }
        else
        {
            TextScale = TextScaleMax;
        }
        if (!UseInnerDimensions)
        {
            innerDimensionsRectangle.Y += 8;
            innerDimensionsRectangle.Height -= 8;
        }
        _text = text;
        oldText = _text?.ToString();
        TextSize = textSize2;
        IsLarge = large;
        textStrings = text.ToString().Split('\n');
        drawOffsets = (Vector2[])(object)new Vector2[textStrings.Length];
        for (int i = 0; i < textStrings.Length; i++)
        {
            Vector2 size = ChatManager.GetStringSize(dynamicSpriteFont, textStrings[i], new Vector2(TextScale));
            if (UseInnerDimensions)
            {
                size.Y = (IsLarge ? 32f : 16f);
            }
            float x = ((float)innerDimensionsRectangle.Width - size.X) * TextOriginX;
            float y = (float)(-textStrings.Length) * size.Y * TextOriginY + (float)i * size.Y + (float)innerDimensionsRectangle.Height * TextOriginY;
            if (UseInnerDimensions)
            {
                y -= 2f;
            }
            drawOffsets[i] = new Vector2(x, y);
        }
    }
References Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >._text, Terraria.GameContent.FontAssets.DeathText, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.drawOffsets, Terraria.UI.UIElement.GetDimensions(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.UI.UIElement.Height, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.IsLarge, Terraria.GameContent.FontAssets.MouseText, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.oldInnerDimensions, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.oldText, Terraria.UI.UIElement.PaddingBottom, Terraria.UI.UIElement.PaddingLeft, Terraria.UI.UIElement.PaddingRight, Terraria.UI.UIElement.PaddingTop, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.ScalePanel, Terraria.UI.StyleDimension.Set(), Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.Text, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.TextOriginX, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.TextOriginY, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.TextScale, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.TextScaleMax, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.TextSize, Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.textStrings, Terraria.UI.CalculatedStyle.ToRectangle(), Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.UseInnerDimensions, and Terraria.UI.UIElement.Width.