TModLoader: Terraria.Social.Steam.WorkshopSocialModule.CalculateVersionsData
CalculateVersionsData()
static bool Terraria.Social.Steam.WorkshopSocialModule.CalculateVersionsData (string workshopPath, ref NameValueCollection buildData) inline static
Definition at line 347 of file WorkshopSocialModule.cs.
    {
        foreach (string item in Directory.EnumerateFiles(workshopPath, "*.tmod*", SearchOption.AllDirectories))
        {
            LocalMod mod = OpenModFile(item);
            if (mod.tModLoaderVersion.MajorMinor() <= BuildInfo.tMLVersion.MajorMinor() && mod.properties.version >= new Version(buildData["version"]))
            {
                return false;
            }
            if (mod.tModLoaderVersion.MajorMinor() != BuildInfo.tMLVersion.MajorMinor())
            {
                buildData["versionsummary"] += $";{mod.tModLoaderVersion}:{mod.properties.version}";
            }
        }
        return true;
    }
References Terraria.Social.Steam.WorkshopSocialModule.OpenModFile(), Terraria.ModLoader.Core.LocalMod.properties, Terraria.ModLoader.BuildInfo.tMLVersion, and Terraria.ModLoader.Core.LocalMod.tModLoaderVersion.
Referenced by Terraria.Social.Steam.WorkshopSocialModule._PublishMod(), and Terraria.Social.Steam.WorkshopSocialModule.SteamCMDPublishPreparer().