TModLoader: Terraria.Social.Steam.WorkshopSocialModule._PublishMod
_PublishMod()
bool Terraria.Social.Steam.WorkshopSocialModule._PublishMod (TmodFile modFile, NameValueCollection buildData, WorkshopItemPublishSettings settings) inline private
    {
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        if (!SteamedWraps.SteamClient)
        {
            base.IssueReporter.ReportInstantUploadProblem("tModLoader.SteamPublishingLimit");
            return false;
        }
        if (modFile.TModLoaderVersion.MajorMinor() != BuildInfo.tMLVersion.MajorMinor())
        {
            base.IssueReporter.ReportInstantUploadProblem("tModLoader.WrongVersionCantPublishError");
            return false;
        }
        if (BuildInfo.IsDev)
        {
            base.IssueReporter.ReportInstantUploadProblem("tModLoader.BetaModCantPublishError");
            return false;
        }
        string workshopFolderPath = GetTemporaryFolderPath() + modFile.Name;
        buildData["versionsummary"] = $"{new Version(buildData["modloaderversion"])}:{buildData["version"]}";
        buildData["trueversion"] = buildData["version"];
        if (currPublishID != 0L)
        {
            CSteamID currID = SteamUser.GetSteamID();
            if (existingAuthorID != currID.m_SteamID)
            {
                base.IssueReporter.ReportInstantUploadProblem("tModLoader.ModAlreadyUploaded");
                return false;
            }
            workshopFolderPath = Path.Combine(Directory.GetParent(ModOrganizer.WorkshopFileFinder.ModPaths[0]).ToString(), $"{currPublishID}");
            FixErrorsInWorkshopFolder(workshopFolderPath);
            if (!CalculateVersionsData(workshopFolderPath, ref buildData))
            {
                base.IssueReporter.ReportInstantUploadProblem("tModLoader.ModVersionInfoUnchanged");
                return false;
            }
        }
        string name = buildData["displaynameclean"];
        if (name.Length >= 129)
        {
            base.IssueReporter.ReportInstantUploadProblem("tModLoader.TitleLengthExceedLimit");
            return false;
        }
        string description = buildData["description"] + "\n[quote=tModLoader]Developed By " + buildData["author"] + "[/quote]";
        if (description.Length >= 8000)
        {
            base.IssueReporter.ReportInstantUploadProblem("tModLoader.DescriptionLengthExceedLimit");
            return false;
        }
        List<string> tagsList = new List<string>();
        tagsList.AddRange(settings.GetUsedTagsInternalNames());
        tagsList.Add(buildData["modside"]);
        if (!TryCalculateWorkshopDeps(ref buildData))
        {
            base.IssueReporter.ReportInstantUploadProblem("tModLoader.NoWorkshopAccess");
            return false;
        }
        string contentFolderPath = $"{workshopFolderPath}/{BuildInfo.tMLVersion.Major}.{BuildInfo.tMLVersion.Minor}";
        if (MakeTemporaryFolder(contentFolderPath))
        {
            string modPath = Path.Combine(contentFolderPath, modFile.Name + ".tmod");
            File.Copy(modFile.path, modPath, overwrite: true);
            ModOrganizer.CleanupOldPublish(workshopFolderPath);
            tagsList.AddRange(DetermineSupportedVersionsFromWorkshop(workshopFolderPath));
            WorkshopHelper.ModPublisherInstance modPublisherInstance = new WorkshopHelper.ModPublisherInstance();
            _publisherInstances.Add(modPublisherInstance);
            modPublisherInstance.PublishContent(_publishedItems, base.IssueReporter, Forget, name, description, workshopFolderPath, settings.PreviewImagePath, settings.Publicity, tagsList.ToArray(), buildData, currPublishID, settings.ChangeNotes);
            return true;
        }
        return false;
    }
References Terraria.Social.Steam.WorkshopSocialModule._publishedItems, Terraria.Social.Steam.WorkshopSocialModule._publisherInstances, Terraria.Social.Steam.WorkshopSocialModule.CalculateVersionsData(), Terraria.ModLoader.Core.ModOrganizer.CleanupOldPublish(), Terraria.Social.Steam.WorkshopSocialModule.currPublishID, Terraria.Social.Steam.WorkshopSocialModule.DetermineSupportedVersionsFromWorkshop(), Terraria.Social.Steam.WorkshopSocialModule.existingAuthorID, Terraria.Social.Steam.WorkshopSocialModule.FixErrorsInWorkshopFolder(), Terraria.Social.Steam.WorkshopSocialModule.Forget(), Terraria.Social.Steam.WorkshopSocialModule.GetTemporaryFolderPath(), Terraria.ModLoader.BuildInfo.IsDev, Terraria.Social.Steam.WorkshopSocialModule.MakeTemporaryFolder(), Terraria.ModLoader.Core.TmodFile.Name, Terraria.ModLoader.Core.TmodFile.path, Terraria.Social.Steam.SteamedWraps.SteamClient, Terraria.ModLoader.BuildInfo.tMLVersion, Terraria.ModLoader.Core.TmodFile.TModLoaderVersion, Terraria.Social.Steam.WorkshopSocialModule.TryCalculateWorkshopDeps(), and Terraria.ModLoader.Core.ModOrganizer.WorkshopFileFinder.
Referenced by Terraria.Social.Steam.WorkshopSocialModule.PublishMod().