TModLoader: Terraria.Social.Steam.WorkshopSocialModule.TryGetInfoForMod
TryGetInfoForMod()
override bool Terraria.Social.Steam.WorkshopSocialModule.TryGetInfoForMod (TmodFile modFile, out FoundWorkshopEntryInfo info) inline
Definition at line 238 of file WorkshopSocialModule.cs.
    {
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        info = null;
        QueryParameters query = default(QueryParameters);
        query.searchModSlugs = new string[1] { modFile.Name };
        query.queryType = QueryType.SearchDirect;
        if (!WorkshopHelper.TryGetModDownloadItemsByInternalName(query, out var mods))
        {
            base.IssueReporter.ReportInstantUploadProblem("tModLoader.NoWorkshopAccess");
            return false;
        }
        if (!mods.Any())
        {
            return false;
        }
        currPublishID = ulong.Parse(mods[0].PublishId.m_ModPubId);
        existingAuthorID = ulong.Parse(mods[0].OwnerId);
        SteamedWraps.Download(new PublishedFileId_t(currPublishID), null, forceUpdate: true);
        return ModOrganizer.TryReadManifest(Path.Combine(Directory.GetParent(ModOrganizer.WorkshopFileFinder.ModPaths[0]).ToString(), $"{currPublishID}"), out info);
    }
References Terraria.Social.Steam.WorkshopSocialModule.currPublishID, Terraria.Social.Steam.SteamedWraps.Download(), Terraria.Social.Steam.WorkshopSocialModule.existingAuthorID, Terraria.Social.Steam.WorkshopHelper.TryGetModDownloadItemsByInternalName(), Terraria.ModLoader.Core.ModOrganizer.TryReadManifest(), and Terraria.ModLoader.Core.ModOrganizer.WorkshopFileFinder.