TModLoader: Terraria.Social.Steam.WorkshopSocialModule.SteamCMDPublishPreparer
SteamCMDPublishPreparer()
static void Terraria.Social.Steam.WorkshopSocialModule.SteamCMDPublishPreparer (string modFolder) inline static
    {
        if (!Program.LaunchParameters.ContainsKey("-ciprep") || !Program.LaunchParameters.ContainsKey("-publishedmodfiles"))
        {
            return;
        }
        Console.WriteLine("Preparing Files for CI...");
        Program.LaunchParameters.TryGetValue("-ciprep", out var changeNotes);
        Program.LaunchParameters.TryGetValue("-publishedmodfiles", out var publishedModFiles);
        Program.LaunchParameters.TryGetValue("-uploadfolder", out var uploadFolder);
        string publishFolder = ModOrganizer.modPath + "/Workshop";
        string modName = Directory.GetParent(modFolder).Name;
        string newModPath = Path.Combine(ModOrganizer.modPath, modName + ".tmod");
        LocalMod newMod = OpenModFile(newModPath);
        NameValueCollection buildData = new NameValueCollection
        {
            ["version"] = newMod.properties.version.ToString(),
            ["versionsummary"] = $"{newMod.tModLoaderVersion}:{newMod.properties.version}",
            ["description"] = newMod.properties.description
        };
        if (!CalculateVersionsData(publishedModFiles, ref buildData))
        {
            Utils.LogAndConsoleErrorMessage("Unable to update mod. " + buildData["version"] + " is not higher than existing version");
            return;
        }
        Console.WriteLine($"Built Mod Version is: {buildData["version"]}. tMod Version is: {BuildInfo.tMLVersion}");
        string contentFolder = $"{publishFolder}/{BuildInfo.tMLVersion.MajorMinor()}";
        if (!Directory.Exists(contentFolder))
        {
            Directory.CreateDirectory(contentFolder);
        }
        FileUtilities.CopyFolder(publishedModFiles, publishFolder);
        File.Copy(newModPath, Path.Combine(contentFolder, modName + ".tmod"), overwrite: true);
        ModOrganizer.CleanupOldPublish(publishFolder);
        string workshopDescFile = Path.Combine(modFolder, "description_workshop.txt");
        string descriptionFinal = string.Concat(str1: File.Exists(workshopDescFile) ? File.ReadAllText(workshopDescFile) : buildData["description"], str0: $"[quote=GithubActions(Don't Modify)]Version Summary {buildData["versionsummary"]}\nDeveloped By {buildData["author"]}[/quote]");
        AWorkshopEntry.TryReadingManifest(Path.Combine(publishedModFiles, "workshop.json"), out var steamInfo);
        string vdf = ModOrganizer.modPath + "/publish.vdf";
        string[] lines = new string[8]
        {
            "\"workshopitem\"",
            "{",
            "\"appid\" \"1281930\"",
            "\"publishedfileid\" \"" + steamInfo.workshopEntryId + "\"",
            "\"contentfolder\" \"" + uploadFolder + "/Workshop\"",
            "\"changenote\" \"" + changeNotes + "\"",
            "\"description\" \"" + descriptionFinal + "\"",
            "}"
        };
        if (File.Exists(vdf))
        {
            File.Delete(vdf);
        }
        File.WriteAllLines(vdf, lines);
        Console.WriteLine("CI Files Prepared");
    }
References Terraria.Social.Steam.WorkshopSocialModule.CalculateVersionsData(), Terraria.ModLoader.Core.ModOrganizer.CleanupOldPublish(), Terraria.ModLoader.Console, Terraria.Utilities.FileUtilities.CopyFolder(), Terraria.Program.LaunchParameters, Terraria.Utils.LogAndConsoleErrorMessage(), Terraria.ModLoader.Core.ModOrganizer.modPath, Terraria.Social.Steam.WorkshopSocialModule.OpenModFile(), and Terraria.Social.Base.AWorkshopEntry.TryReadingManifest().
Referenced by Terraria.ModLoader.Core.ModCompile.BuildModCommandLine().