TModLoader: Terraria.ModLoader.NPCShopDatabase.RegisterSkeletonMerchant
RegisterSkeletonMerchant()
static void Terraria.ModLoader.NPCShopDatabase.RegisterSkeletonMerchant () inline static private
    {
        Condition spelunkerGlowCondition = new Condition("Conditions.NightDayFullMoon", () => !Main.dayTime || Main.moonPhase == 0);
        Condition glowstickCondition = new Condition("Conditions.DaytimeNotFullMoon", () => Main.dayTime && Main.moonPhase != 0);
        Condition artisanCondition = new Condition("Conditions.NoAteLoaf", () => !Main.LocalPlayer.ateArtisanBread);
        Condition boneTorchCondition = new Condition("Conditions.Periodically", () => Main.time % 60.0 <= 30.0);
        Condition torchCondition = new Condition("Conditions.Periodically", () => Main.time % 60.0 > 30.0);
        new NPCShop(453).Add(284, Condition.MoonPhaseFull).Add(946, Condition.MoonPhaseWaningGibbous).Add(3069, Condition.MoonPhaseThirdQuarter, Condition.NotRemixWorld)
            .Add(517, Condition.MoonPhaseThirdQuarter, Condition.RemixWorld)
            .Add(4341, Condition.MoonPhaseWaningCrescent)
            .Add(285, Condition.MoonPhaseNew)
            .Add(953, Condition.MoonPhaseWaxingCrescent)
            .Add(3068, Condition.MoonPhaseFirstQuarter)
            .Add(3084, Condition.MoonPhaseWaxingGibbous)
            .Add(3001, Condition.MoonPhasesEven)
            .Add(28, Condition.MoonPhasesOdd)
            .Add(188, Condition.Hardmode, Condition.MoonPhasesOdd)
            .Add(3002, spelunkerGlowCondition)
            .Add(5377, spelunkerGlowCondition, Condition.PlayerCarriesItem(930))
            .Add(282, glowstickCondition)
            .Add(3004, boneTorchCondition)
            .Add(8, torchCondition)
            .Add(3003, Condition.MoonPhasesEvenQuarters)
            .Add(40, Condition.MoonPhasesOddQuarters)
            .Add(3310, Condition.MoonPhases04)
            .Add(3313, Condition.MoonPhases15)
            .Add(3312, Condition.MoonPhases26)
            .Add(3311, Condition.MoonPhases37)
            .Add(166)
            .Add(965)
            .Add(3316, Condition.Hardmode, Condition.MoonPhasesHalf0)
            .Add(3315, Condition.Hardmode, Condition.MoonPhasesHalf1)
            .Add(3334, Condition.Hardmode)
            .Add(3258, Condition.Hardmode, Condition.BloodMoon)
            .Add(3043, Condition.TimeNight, Condition.MoonPhaseFull)
            .Add(5326, artisanCondition, Condition.MoonPhasesNearNew)
            .Register();
    }
References Terraria.ModLoader.NPCShop.Add(), Terraria.Condition(), Terraria.Main.dayTime, Terraria.Main.LocalPlayer, Terraria.Main.moonPhase, Terraria.ModLoader.AbstractNPCShop.Register(), and Terraria.Main.time.
Referenced by Terraria.ModLoader.NPCShopDatabase.RegisterVanillaNPCShops().