TModLoader: Terraria.ModLoader.NPCShopDatabase.GetPylonEntries
GetPylonEntries()
static IEnumerable< NPCShop.Entry > Terraria.ModLoader.NPCShopDatabase.GetPylonEntries () inline static
Definition at line 159 of file NPCShopDatabase.cs.
    {
        Condition forestPylonCondition = new Condition("Conditions.ForestPylon", delegate
        {
            //IL_0078: Unknown result type (might be due to invalid IL or missing references)
            //IL_0056: Unknown result type (might be due to invalid IL or missing references)
            //IL_0099: Unknown result type (might be due to invalid IL or missing references)
            if (Main.LocalPlayer.ZoneSnow || Main.LocalPlayer.ZoneDesert || Main.LocalPlayer.ZoneBeach || Main.LocalPlayer.ZoneJungle || Main.LocalPlayer.ZoneHallow || Main.LocalPlayer.ZoneGlowshroom)
            {
                return false;
            }
            if (!Main.remixWorld)
            {
                return (double)Main.LocalPlayer.Center.Y / 16.0 < Main.worldSurface;
            }
            return (double)Main.LocalPlayer.Center.Y / 16.0 > Main.rockLayer && Main.LocalPlayer.Center.Y / 16f < (float)(Main.maxTilesY - 350);
        });
        Condition cavernPylonCondition = new Condition("Conditions.UndergroundPylon", () => !Main.LocalPlayer.ZoneSnow && !Main.LocalPlayer.ZoneDesert && !Main.LocalPlayer.ZoneBeach && !Main.LocalPlayer.ZoneJungle && !Main.LocalPlayer.ZoneHallow && (Main.remixWorld || !Main.LocalPlayer.ZoneGlowshroom) && (double)Main.LocalPlayer.Center.Y / 16.0 >= Main.worldSurface);
        Condition oceanPylonCondition = new Condition("Conditions.InBeach", delegate
        {
            bool flag = Main.LocalPlayer.ZoneBeach && (double)Main.LocalPlayer.position.Y < Main.worldSurface * 16.0;
            if (Main.remixWorld)
            {
                double num = (double)Main.LocalPlayer.position.X / 16.0;
                double num2 = (double)Main.LocalPlayer.position.Y / 16.0;
                flag |= (num < (double)Main.maxTilesX * 0.43 || num > (double)Main.maxTilesX * 0.57) && num2 > Main.rockLayer && num2 < (double)(Main.maxTilesY - 350);
            }
            return flag;
        });
        Condition mushroomPylonCondition = new Condition("Conditions.InGlowshroom", () => Main.LocalPlayer.ZoneGlowshroom && (!Main.remixWorld || !Main.LocalPlayer.ZoneUnderworldHeight));
        yield return new NPCShop.Entry(4876, Condition.HappyEnoughToSellPylons, Condition.AnotherTownNPCNearby, Condition.NotInEvilBiome, forestPylonCondition).OrderLast();
        yield return new NPCShop.Entry(4920, Condition.HappyEnoughToSellPylons, Condition.AnotherTownNPCNearby, Condition.NotInEvilBiome, Condition.InSnow).OrderLast();
        yield return new NPCShop.Entry(4919, Condition.HappyEnoughToSellPylons, Condition.AnotherTownNPCNearby, Condition.NotInEvilBiome, Condition.InDesert).OrderLast();
        yield return new NPCShop.Entry(4917, Condition.HappyEnoughToSellPylons, Condition.AnotherTownNPCNearby, Condition.NotInEvilBiome, cavernPylonCondition).OrderLast();
        yield return new NPCShop.Entry(4918, Condition.HappyEnoughToSellPylons, Condition.AnotherTownNPCNearby, Condition.NotInEvilBiome, oceanPylonCondition).OrderLast();
        yield return new NPCShop.Entry(4875, Condition.HappyEnoughToSellPylons, Condition.AnotherTownNPCNearby, Condition.NotInEvilBiome, Condition.InJungle).OrderLast();
        yield return new NPCShop.Entry(4916, Condition.HappyEnoughToSellPylons, Condition.AnotherTownNPCNearby, Condition.NotInEvilBiome, Condition.InHallow).OrderLast();
        yield return new NPCShop.Entry(4921, Condition.HappyEnoughToSellPylons, Condition.AnotherTownNPCNearby, Condition.NotInEvilBiome, mushroomPylonCondition).OrderLast();
        foreach (ModPylon modPylon in PylonLoader.modPylons)
        {
            NPCShop.Entry entry = modPylon.GetNPCShopEntry();
            if (entry != null)
            {
                yield return entry.OrderLast();
            }
        }
    }
References Terraria.Condition(), Terraria.Main.LocalPlayer, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.ModLoader.PylonLoader.modPylons, Terraria.ModLoader.NPCShop.Entry.OrderLast(), Terraria.Main.remixWorld, Terraria.Main.rockLayer, and Terraria.Main.worldSurface.
Referenced by Terraria.ModLoader.Default.PylonShopNPC.ModifyShop().