TModLoader: Terraria.ModLoader.NPCShopDatabase.RegisterVanillaNPCShops
RegisterVanillaNPCShops()
static void Terraria.ModLoader.NPCShopDatabase.RegisterVanillaNPCShops () inline static private
    {
        NoPylons.Add(GetShopName(368));
        NoPylons.Add(GetShopName(453));
        NoPylons.Add(GetShopName(550));
        NoPylons.Add(GetShopName(142));
        RegisterMerchant();
        RegisterArmsDealer();
        RegisterDryad();
        RegisterBombGuy();
        RegisterClothier();
        RegisterGoblin();
        RegisterWizard();
        RegisterMechanic();
        RegisterSantaClaws();
        RegisterTruffle();
        RegisterSteampunker();
        RegisterDyeTrader();
        RegisterPartyGirl();
        RegisterCyborg();
        RegisterPainter();
        RegisterWitchDoctor();
        RegisterPirate();
        RegisterStylist();
        RegisterSkeletonMerchant();
        RegisterBartender();
        RegisterGolfer();
        RegisterZoologist();
        RegisterPrincess();
        RegisterTravellingMerchant();
    }
References Terraria.ModLoader.NPCShopDatabase.GetShopName(), Terraria.ModLoader.NPCShopDatabase.NoPylons, Terraria.ModLoader.NPCShopDatabase.RegisterArmsDealer(), Terraria.ModLoader.NPCShopDatabase.RegisterBartender(), Terraria.ModLoader.NPCShopDatabase.RegisterBombGuy(), Terraria.ModLoader.NPCShopDatabase.RegisterClothier(), Terraria.ModLoader.NPCShopDatabase.RegisterCyborg(), Terraria.ModLoader.NPCShopDatabase.RegisterDryad(), Terraria.ModLoader.NPCShopDatabase.RegisterDyeTrader(), Terraria.ModLoader.NPCShopDatabase.RegisterGoblin(), Terraria.ModLoader.NPCShopDatabase.RegisterGolfer(), Terraria.ModLoader.NPCShopDatabase.RegisterMechanic(), Terraria.ModLoader.NPCShopDatabase.RegisterMerchant(), Terraria.ModLoader.NPCShopDatabase.RegisterPainter(), Terraria.ModLoader.NPCShopDatabase.RegisterPartyGirl(), Terraria.ModLoader.NPCShopDatabase.RegisterPirate(), Terraria.ModLoader.NPCShopDatabase.RegisterPrincess(), Terraria.ModLoader.NPCShopDatabase.RegisterSantaClaws(), Terraria.ModLoader.NPCShopDatabase.RegisterSkeletonMerchant(), Terraria.ModLoader.NPCShopDatabase.RegisterSteampunker(), Terraria.ModLoader.NPCShopDatabase.RegisterStylist(), Terraria.ModLoader.NPCShopDatabase.RegisterTravellingMerchant(), Terraria.ModLoader.NPCShopDatabase.RegisterTruffle(), Terraria.ModLoader.NPCShopDatabase.RegisterWitchDoctor(), Terraria.ModLoader.NPCShopDatabase.RegisterWizard(), and Terraria.ModLoader.NPCShopDatabase.RegisterZoologist().
Referenced by Terraria.ModLoader.NPCShopDatabase.Initialize().