TModLoader: Terraria.ModLoader.NPCShopDatabase.RegisterTravellingMerchant
RegisterTravellingMerchant()
static void Terraria.ModLoader.NPCShopDatabase.RegisterTravellingMerchant () inline static private
Definition at line 1104 of file NPCShopDatabase.cs.
    {
        new TravellingMerchantShop(368).AddInfoEntry(3309).AddInfoEntry(3314).AddInfoEntry(1987)
            .AddInfoEntry(2270, Condition.Hardmode)
            .AddInfoEntry(4760, Condition.Hardmode)
            .AddInfoEntry(2278)
            .AddInfoEntry(2271)
            .AddInfoEntry(2223, Condition.DownedDestroyer, Condition.DownedTwins, Condition.DownedSkeletronPrime)
            .AddInfoEntry(2272)
            .AddInfoEntry(2276)
            .AddInfoEntry(2284)
            .AddInfoEntry(2285)
            .AddInfoEntry(2286)
            .AddInfoEntry(2287)
            .AddInfoEntry(4744)
            .AddInfoEntry(2296, Condition.DownedSkeletron)
            .AddInfoEntry(3628)
            .AddInfoEntry(4091, Condition.Hardmode)
            .AddInfoEntry(4603)
            .AddInfoEntry(4604)
            .AddInfoEntry(5297)
            .AddInfoEntry(4605)
            .AddInfoEntry(4550)
            .AddInfoEntry(2268)
            .AddInfoEntry(2269, Condition.SmashedShadowOrb)
            .AddInfoEntry(1988)
            .AddInfoEntry(2275)
            .AddInfoEntry(2279)
            .AddInfoEntry(2277)
            .AddInfoEntry(4555)
            .AddInfoEntry(4321)
            .AddInfoEntry(4323)
            .AddInfoEntry(5390)
            .AddInfoEntry(4549)
            .AddInfoEntry(4561)
            .AddInfoEntry(4774)
            .AddInfoEntry(5136)
            .AddInfoEntry(5305)
            .AddInfoEntry(4562)
            .AddInfoEntry(4558)
            .AddInfoEntry(4559)
            .AddInfoEntry(4563)
            .AddInfoEntry(4666)
            .AddInfoEntry(4347, Condition.DownedEarlygameBoss)
            .AddInfoEntry(4348, Condition.Hardmode)
            .AddInfoEntry(3262, Condition.DownedEyeOfCthulhu)
            .AddInfoEntry(3284, Condition.DownedMechBossAny)
            .AddInfoEntry(2267)
            .AddInfoEntry(2214)
            .AddInfoEntry(2215)
            .AddInfoEntry(2216)
            .AddInfoEntry(2217)
            .AddInfoEntry(3624)
            .AddInfoEntry(671, Condition.RemixWorld)
            .AddInfoEntry(2273, Condition.NotRemixWorld)
            .AddInfoEntry(2274)
            .AddInfoEntry(2266)
            .AddInfoEntry(2281)
            .AddInfoEntry(2282)
            .AddInfoEntry(2283)
            .AddInfoEntry(2258)
            .AddInfoEntry(2242)
            .AddInfoEntry(2260)
            .AddInfoEntry(3637)
            .AddInfoEntry(4420)
            .AddInfoEntry(3119)
            .AddInfoEntry(3118)
            .AddInfoEntry(3099)
            .Register();
    }
References Terraria.ModLoader.TravellingMerchantShop.AddInfoEntry(), Terraria.Condition(), and Terraria.ModLoader.AbstractNPCShop.Register().
Referenced by Terraria.ModLoader.NPCShopDatabase.RegisterVanillaNPCShops().