TModLoader: Terraria.ModLoader.NPCShopDatabase.RegisterGolfer
RegisterGolfer()
static void Terraria.ModLoader.NPCShopDatabase.RegisterGolfer () inline static private
    {
        Condition scoreOver1002 = Condition.GolfScoreOver(500);
        Condition scoreOver1000 = Condition.GolfScoreOver(1000);
        Condition scoreOver1001 = Condition.GolfScoreOver(2000);
        new NPCShop(588).Add(4587).Add(4590).Add(4589)
            .Add(4588)
            .Add(4083)
            .Add(4084)
            .Add(4085)
            .Add(4086)
            .Add(4087)
            .Add(4088)
            .Add(4039, scoreOver1002)
            .Add(4094, scoreOver1002)
            .Add(4093, scoreOver1002)
            .Add(4092, scoreOver1002)
            .Add(4089)
            .Add(3989)
            .Add(4095)
            .Add(4040)
            .Add(4319)
            .Add(4320)
            .Add(4591, scoreOver1000)
            .Add(4594, scoreOver1000)
            .Add(4593, scoreOver1000)
            .Add(4592, scoreOver1000)
            .Add(4135)
            .Add(4138)
            .Add(4136)
            .Add(4137)
            .Add(4049)
            .Add(4265, scoreOver1002)
            .Add(4595, scoreOver1001)
            .Add(4598, scoreOver1001)
            .Add(4597, scoreOver1001)
            .Add(4596, scoreOver1001)
            .Add(4264, scoreOver1001, Condition.DownedSkeletron)
            .Add(4599, scoreOver1002)
            .Add(4600, scoreOver1000)
            .Add(4601, scoreOver1001)
            .Add(4658, scoreOver1001, Condition.MoonPhasesQuarter0)
            .Add(4659, scoreOver1001, Condition.MoonPhasesQuarter1)
            .Add(4660, scoreOver1001, Condition.MoonPhasesQuarter2)
            .Add(4661, scoreOver1001, Condition.MoonPhasesQuarter3)
            .Register();
    }
References Terraria.ModLoader.NPCShop.Add(), Terraria.Condition(), and Terraria.ModLoader.AbstractNPCShop.Register().
Referenced by Terraria.ModLoader.NPCShopDatabase.RegisterVanillaNPCShops().