TModLoader: Terraria.ModLoader.NPCShopDatabase.RegisterBartender
RegisterBartender()
static void Terraria.ModLoader.NPCShopDatabase.RegisterBartender () inline static private
Definition at line 794 of file NPCShopDatabase.cs.
    {
        NPCShop shop = new NPCShop(550).AllowFillingLastSlot();
        shop.Add(353);
        shop.Add(new NPCShop.Entry(3828).AddShopOpenedCallback(delegate(Item item, NPC npc)
        {
            if (NPC.downedGolemBoss)
            {
                item.shopCustomPrice = Item.buyPrice(0, 4);
            }
            else if (NPC.downedMechBossAny)
            {
                item.shopCustomPrice = Item.buyPrice(0, 1);
            }
            else
            {
                item.shopCustomPrice = Item.buyPrice(0, 0, 25);
            }
        }));
        shop.Add(3816);
        AddEntry(3813, 50, Array.Empty<Condition>());
        AddEntry(3800, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3801, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3802, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3871, 50, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3872, 50, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3873, 50, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3818, 5, Array.Empty<Condition>());
        AddEntry(3824, 5, Array.Empty<Condition>());
        AddEntry(3832, 5, Array.Empty<Condition>());
        AddEntry(3829, 5, Array.Empty<Condition>());
        AddEntry(3797, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3798, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3799, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3874, 50, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3875, 50, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3876, 50, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3819, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3825, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3833, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3830, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3803, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3804, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3805, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3877, 50, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3878, 50, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3879, 50, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3820, 60, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3826, 60, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3834, 60, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3831, 60, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3806, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3807, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3808, 15, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedMechBossAny
        });
        AddEntry(3880, 50, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3881, 50, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        AddEntry(3882, 50, new Condition[2]
        {
            Condition.Hardmode,
            Condition.DownedGolem
        });
        shop.Register();
        void AddEntry(int id, int price, Condition[] conditions)
        {
            shop.Add(new NPCShop.Entry(new Item(id)
            {
                shopCustomPrice = price,
                shopSpecialCurrency = CustomCurrencyID.DefenderMedals
            }, conditions).ReserveSlot());
        }
    }
References Terraria.ModLoader.NPCShop.Add(), Terraria.ModLoader.NPCShop.Entry.AddShopOpenedCallback(), Terraria.ModLoader.NPCShop.AllowFillingLastSlot(), Terraria.Condition(), Terraria.NPC.downedGolemBoss, Terraria.NPC.downedMechBossAny, and Terraria.ModLoader.AbstractNPCShop.Register().
Referenced by Terraria.ModLoader.NPCShopDatabase.RegisterVanillaNPCShops().