TModLoader: Terraria.ModLoader.NPCShopDatabase.RegisterSteampunker
RegisterSteampunker()
static void Terraria.ModLoader.NPCShopDatabase.RegisterSteampunker () inline static private
Definition at line 474 of file NPCShopDatabase.cs.
    {
        Condition steampunkerOutfitCondition = new Condition("Conditions.MoonPhasesHalf0OrPreHardmode", () => Condition.PreHardmode.IsMet() || Condition.MoonPhasesHalf0.IsMet());
        new NPCShop(178).Add(779, Condition.NotRemixWorld).Add(839, steampunkerOutfitCondition).Add(840, steampunkerOutfitCondition)
            .Add(841, steampunkerOutfitCondition)
            .Add(748, Condition.Hardmode, Condition.MoonPhasesHalf1)
            .Add(948, Condition.DownedGolem)
            .Add(3623, Condition.Hardmode)
            .Add(3603)
            .Add(3604)
            .Add(3607)
            .Add(3605)
            .Add(3606)
            .Add(3608)
            .Add(3618)
            .Add(3602)
            .Add(3663)
            .Add(3609)
            .Add(3610)
            .Add(995, new Condition("Conditions.HardmodeFTW", () => Main.hardMode || !Main.getGoodWorld))
            .Add(2203, Condition.DownedEyeOfCthulhu, Condition.DownedEowOrBoc, Condition.DownedSkeletron)
            .Add(2193, Condition.CrimsonWorld)
            .Add(4142, Condition.CorruptWorld)
            .Add(2192, Condition.InGraveyard)
            .Add(2204, Condition.InJungle)
            .Add(2198, Condition.InSnow)
            .Add(2197, Condition.InSpace)
            .Add(2196, Condition.PlayerCarriesItem(832))
            .Add(784, Condition.NotRemixWorld, Condition.EclipseOrBloodMoon, Condition.CrimsonWorld)
            .Add(782, Condition.NotRemixWorld, Condition.EclipseOrBloodMoon, Condition.CorruptWorld)
            .Add(781, Condition.NotRemixWorld, Condition.NotEclipseAndNotBloodMoon, Condition.InHallow)
            .Add(780, Condition.NotRemixWorld, Condition.NotEclipseAndNotBloodMoon, Condition.NotInHallow)
            .Add(5392, Condition.NotRemixWorld, Condition.DownedMoonLord)
            .Add(5393, Condition.NotRemixWorld, Condition.DownedMoonLord)
            .Add(5394, Condition.NotRemixWorld, Condition.DownedMoonLord)
            .Add(1344, Condition.Hardmode)
            .Add(4472, Condition.Hardmode)
            .Add(1742, Condition.Halloween)
            .Register();
    }
References Terraria.ModLoader.NPCShop.Add(), Terraria.Condition(), Terraria.Main.getGoodWorld, Terraria.Main.hardMode, and Terraria.ModLoader.AbstractNPCShop.Register().
Referenced by Terraria.ModLoader.NPCShopDatabase.RegisterVanillaNPCShops().