TModLoader: Terraria.ModLoader.NPCShopDatabase.Initialize
Initialize()
static void Terraria.ModLoader.NPCShopDatabase.Initialize () inline static
    {
        npcShopByName.Clear();
        NoPylons.Clear();
        RegisterVanillaNPCShops();
        for (int i = 0; i < NPCLoader.NPCCount; i++)
        {
            NPCLoader.AddShops(i);
        }
        foreach (NPCShop item in AllShops.OfType<NPCShop>())
        {
            NPCLoader.ModifyShop(item);
        }
    }
References Terraria.ModLoader.NPCLoader.AddShops(), Terraria.ModLoader.NPCShopDatabase.AllShops, Terraria.ModLoader.NPCLoader.ModifyShop(), Terraria.ModLoader.NPCShopDatabase.NoPylons, Terraria.ModLoader.NPCLoader.NPCCount, Terraria.ModLoader.NPCShopDatabase.npcShopByName, and Terraria.ModLoader.NPCShopDatabase.RegisterVanillaNPCShops().
Referenced by Terraria.ModLoader.ModContent.Load().