TModLoader: Terraria.ModLoader.NPCShopDatabase.RegisterCyborg
RegisterCyborg()
static void Terraria.ModLoader.NPCShopDatabase.RegisterCyborg () inline static private
    {
        Condition portalGunStation = new Condition(Language.GetText("Conditions.PlayerCarriesItem2").WithFormatArgs(Lang.GetItemName(3384), Lang.GetItemName(3664)), () => Main.LocalPlayer.HasItem(3384) || Main.LocalPlayer.HasItem(3664));
        new NPCShop(209).Add(771).Add(772, Condition.BloodMoon).Add(773, Condition.NightOrEclipse)
            .Add(774, Condition.Eclipse)
            .Add(4445, Condition.DownedMartians)
            .Add(4446, Condition.DownedMartians, Condition.EclipseOrBloodMoon)
            .Add(4459, Condition.Hardmode)
            .Add(760, Condition.Hardmode)
            .Add(1346, Condition.Hardmode)
            .Add(5451, Condition.Hardmode)
            .Add(5452, Condition.Hardmode)
            .Add(4409, Condition.InGraveyard)
            .Add(4392, Condition.InGraveyard)
            .Add(1743, Condition.Halloween)
            .Add(1744, Condition.Halloween)
            .Add(1745, Condition.Halloween)
            .Add(2862, Condition.DownedMartians)
            .Add(3109, Condition.DownedMartians)
            .Add(3664, portalGunStation)
            .Register();
    }
References Terraria.ModLoader.NPCShop.Add(), Terraria.Condition(), Terraria.Lang.GetItemName(), Terraria.Localization.Language.GetText(), Terraria.Main.LocalPlayer, and Terraria.ModLoader.AbstractNPCShop.Register().
Referenced by Terraria.ModLoader.NPCShopDatabase.RegisterVanillaNPCShops().