TModLoader: Terraria.ModLoader.NPCShopDatabase.RegisterStylist
RegisterStylist()
static void Terraria.ModLoader.NPCShopDatabase.RegisterStylist () inline static private
Definition at line 706 of file NPCShopDatabase.cs.
    {
        Condition maxLife = new Condition(Language.GetText("Conditions.AtleastXHealth").WithFormatArgs(400), () => Main.LocalPlayer.ConsumedLifeCrystals == 15);
        Condition maxMana = new Condition(Language.GetText("Conditions.AtleastXMana").WithFormatArgs(200), () => Main.LocalPlayer.ConsumedManaCrystals == 9);
        Condition moneyHair = new Condition("Conditions.PlatinumCoin", delegate
        {
            long num = 0L;
            for (int i = 0; i < 54; i++)
            {
                if (Main.LocalPlayer.inventory[i].type == 71)
                {
                    num += Main.LocalPlayer.inventory[i].stack;
                }
                else if (Main.LocalPlayer.inventory[i].type == 72)
                {
                    num += Main.LocalPlayer.inventory[i].stack * 100;
                }
                else if (Main.LocalPlayer.inventory[i].type == 73)
                {
                    num += Main.LocalPlayer.inventory[i].stack * 10000;
                }
                else if (Main.LocalPlayer.inventory[i].type == 74)
                {
                    num += Main.LocalPlayer.inventory[i].stack * 1000000;
                }
                if (num >= 1000000)
                {
                    return true;
                }
            }
            return false;
        });
        Condition timeHair = new Condition("Conditions.StyleMoon", () => Main.moonPhase % 2 == (!Main.dayTime).ToInt());
        Condition teamHair = new Condition("Conditions.OnTeam", () => Main.LocalPlayer.team != 0);
        new NPCShop(353).Add(1990).Add(1979).Add(1977, maxLife)
            .Add(1978, maxMana)
            .Add(1980, moneyHair)
            .Add(1981, timeHair)
            .Add(1982, teamHair)
            .Add(1983, Condition.Hardmode)
            .Add(1984, Condition.NpcIsPresent(208))
            .Add(1985, Condition.Hardmode, Condition.DownedTwins, Condition.DownedSkeletronPrime, Condition.DownedDestroyer)
            .Add(1986, Condition.Hardmode, Condition.DownedMechBossAny)
            .Add(2863, Condition.DownedMartians)
            .Add(3259, Condition.DownedMartians)
            .Add(5104)
            .Register();
    }
References Terraria.ModLoader.NPCShop.Add(), Terraria.Condition(), Terraria.Main.dayTime, Terraria.Localization.Language.GetText(), Terraria.Main.LocalPlayer, Terraria.Main.moonPhase, and Terraria.ModLoader.AbstractNPCShop.Register().
Referenced by Terraria.ModLoader.NPCShopDatabase.RegisterVanillaNPCShops().