TModLoader: Terraria.ModLoader.NPCShopDatabase.RegisterPainter
RegisterPainter()
static void Terraria.ModLoader.NPCShopDatabase.RegisterPainter () inline static private
    {
        new NPCShop(227).Add(1071).Add(1072).Add(1100)
            .Add(1073)
            .Add(1074)
            .Add(1075)
            .Add(1076)
            .Add(1077)
            .Add(1078)
            .Add(1079)
            .Add(1080)
            .Add(1081)
            .Add(1082)
            .Add(1083)
            .Add(1084)
            .Add(1097)
            .Add(1099)
            .Add(1098)
            .Add(1966)
            .Add(1967, Condition.Hardmode)
            .Add(1968, Condition.Hardmode)
            .Add(4668, Condition.InGraveyard)
            .Add(5344, Condition.InGraveyard, Condition.DownedPlantera)
            .Register();
        new NPCShop(227, "Decor").Add(1948, Condition.Christmas).Add(1949, Condition.Christmas).Add(1950, Condition.Christmas)
            .Add(1951, Condition.Christmas)
            .Add(1952, Condition.Christmas)
            .Add(1953, Condition.Christmas)
            .Add(1954, Condition.Christmas)
            .Add(1955, Condition.Christmas)
            .Add(1956, Condition.Christmas)
            .Add(1957, Condition.Christmas)
            .Add(2158)
            .Add(2159)
            .Add(2160)
            .Add(2008)
            .Add(2009)
            .Add(2010)
            .Add(2011)
            .Add(2012)
            .Add(2013)
            .Add(2014)
            .Add(1490, Condition.NotInGraveyard)
            .Add(1481, Condition.NotInGraveyard, Condition.MoonPhasesQuarter0)
            .Add(1482, Condition.NotInGraveyard, Condition.MoonPhasesQuarter1)
            .Add(1483, Condition.NotInGraveyard, Condition.MoonPhasesQuarter2)
            .Add(1484, Condition.NotInGraveyard, Condition.MoonPhasesQuarter3)
            .Add(5245, Condition.InShoppingZoneForest)
            .Add(1492, Condition.InCrimson)
            .Add(1488, Condition.InCorrupt)
            .Add(1489, Condition.InHallow)
            .Add(1486, Condition.InJungle)
            .Add(1487, Condition.InSnow)
            .Add(1491, Condition.InDesert)
            .Add(1493, Condition.BloodMoon)
            .Add(1485, Condition.NotInGraveyard, Condition.InSpace)
            .Add(1494, Condition.NotInGraveyard, Condition.Hardmode, Condition.InSpace)
            .Add(5251, Condition.Thunderstorm)
            .Add(4723, Condition.InGraveyard)
            .Add(4724, Condition.InGraveyard)
            .Add(4725, Condition.InGraveyard)
            .Add(4726, Condition.InGraveyard)
            .Add(4727, Condition.InGraveyard)
            .Add(5257, Condition.InGraveyard)
            .Add(4728, Condition.InGraveyard)
            .Add(4729, Condition.InGraveyard)
            .Register();
    }
References Terraria.ModLoader.NPCShop.Add(), Terraria.Condition(), and Terraria.ModLoader.AbstractNPCShop.Register().
Referenced by Terraria.ModLoader.NPCShopDatabase.RegisterVanillaNPCShops().