TModLoader: Terraria.ModLoader.NPCShopDatabase.GetShopName
GetShopName()
static string Terraria.ModLoader.NPCShopDatabase.GetShopName (int npcType, string shopName = "Shop") inline static
Gets a shop name (identifier) in the format matching P:Terraria.ModLoader.AbstractNPCShop.FullName
Can be used with M:Terraria.ModLoader.NPCShopDatabase.TryGetNPCShop(System.String,Terraria.ModLoader.AbstractNPCShop@) and M:Terraria.ModLoader.GlobalNPC.ModifyActiveShop(Terraria.NPC,System.String,Terraria.Item[])
Parameters
npcType
shopName
Returns
Definition at line 89 of file NPCShopDatabase.cs.
    {
        return ((npcType < NPCID.Count) ? ("Terraria/" + NPCID.Search.GetName(npcType)) : NPCLoader.GetNPC(npcType).FullName) + "/" + shopName;
    }
References Terraria.ID.NPCID.Count, Terraria.ModLoader.ModType< TEntity, TModType >.FullName, Terraria.ModLoader.NPCLoader.GetNPC(), and Terraria.ID.NPCID.Search.
Referenced by Terraria.ModLoader.Default.PylonShopNPC.ModifyActiveShop(), Terraria.ModLoader.NPCLoader.OnChatButtonClicked(), and Terraria.ModLoader.NPCShopDatabase.RegisterVanillaNPCShops().