TModLoader: Terraria.ModLoader.NPCShopDatabase.RegisterClothier
RegisterClothier()
static void Terraria.ModLoader.NPCShopDatabase.RegisterClothier () inline static private
    {
        Condition taxCollectorIsPresent = Condition.NpcIsPresent(441);
        new NPCShop(54).Add(254).Add(981).Add(242, Condition.TimeDay)
            .Add(245, Condition.MoonPhaseFull)
            .Add(246, Condition.MoonPhaseFull)
            .Add(1288, Condition.MoonPhaseFull, Condition.TimeNight)
            .Add(1289, Condition.MoonPhaseFull, Condition.TimeNight)
            .Add(325, Condition.MoonPhaseWaningGibbous)
            .Add(326, Condition.MoonPhaseWaningGibbous)
            .Add(269)
            .Add(270)
            .Add(271)
            .Add(503, Condition.DownedClown)
            .Add(504, Condition.DownedClown)
            .Add(505, Condition.DownedClown)
            .Add(322, Condition.BloodMoon)
            .Add(3362, Condition.BloodMoon)
            .Add(3363, Condition.BloodMoon)
            .Add(2856, Condition.TimeDay, Condition.DownedCultist)
            .Add(2858, Condition.TimeDay, Condition.DownedCultist)
            .Add(2857, Condition.TimeNight, Condition.DownedCultist)
            .Add(2859, Condition.TimeNight, Condition.DownedCultist)
            .Add(3242, taxCollectorIsPresent)
            .Add(3243, taxCollectorIsPresent)
            .Add(3244, taxCollectorIsPresent)
            .Add(4685, Condition.InGraveyard)
            .Add(4686, Condition.InGraveyard)
            .Add(4704, Condition.InGraveyard)
            .Add(4705, Condition.InGraveyard)
            .Add(4706, Condition.InGraveyard)
            .Add(4707, Condition.InGraveyard)
            .Add(4708, Condition.InGraveyard)
            .Add(4709, Condition.InGraveyard)
            .Add(1429, Condition.InSnow)
            .Add(1740, Condition.Halloween)
            .Add(869, Condition.Hardmode, Condition.MoonPhaseThirdQuarter)
            .Add(4994, Condition.Hardmode, Condition.MoonPhaseWaningCrescent)
            .Add(4997, Condition.Hardmode, Condition.MoonPhaseWaningCrescent)
            .Add(864, Condition.Hardmode, Condition.MoonPhaseNew)
            .Add(865, Condition.Hardmode, Condition.MoonPhaseNew)
            .Add(4995, Condition.Hardmode, Condition.MoonPhaseWaxingCrescent)
            .Add(4998, Condition.Hardmode, Condition.MoonPhaseWaxingCrescent)
            .Add(873, Condition.Hardmode, Condition.MoonPhaseFirstQuarter)
            .Add(874, Condition.Hardmode, Condition.MoonPhaseFirstQuarter)
            .Add(875, Condition.Hardmode, Condition.MoonPhaseFirstQuarter)
            .Add(4996, Condition.Hardmode, Condition.MoonPhaseWaxingGibbous)
            .Add(4999, Condition.Hardmode, Condition.MoonPhaseWaxingGibbous)
            .Add(1275, Condition.DownedFrostLegion, Condition.TimeDay)
            .Add(1276, Condition.DownedFrostLegion, Condition.TimeNight)
            .Add(3246, Condition.Halloween)
            .Add(3247, Condition.Halloween)
            .Add(3730, Condition.BirthdayParty)
            .Add(3731, Condition.BirthdayParty)
            .Add(3733, Condition.BirthdayParty)
            .Add(3734, Condition.BirthdayParty)
            .Add(3735, Condition.BirthdayParty)
            .Add(4744, Condition.GolfScoreOver(2000))
            .Add(5308)
            .Register();
    }
References Terraria.ModLoader.NPCShop.Add(), Terraria.Condition(), and Terraria.ModLoader.AbstractNPCShop.Register().
Referenced by Terraria.ModLoader.NPCShopDatabase.RegisterVanillaNPCShops().