TModLoader: Terraria.ModLoader.NPCShopDatabase.RegisterZoologist
RegisterZoologist()
static void Terraria.ModLoader.NPCShopDatabase.RegisterZoologist () inline static private
Definition at line 1038 of file NPCShopDatabase.cs.
    {
        new NPCShop(633).Add(4776, new Condition("Conditions.BestiaryWinx", () => Chest.BestiaryGirl_IsFairyTorchAvailable())).Add(4767).Add(4759)
            .Add(5253, Condition.MoonPhaseFull, Condition.TimeNight)
            .Add(4672, BestiaryFilledPercent(10))
            .Add(4829)
            .Add(4830, BestiaryFilledPercent(25))
            .Add(4910, BestiaryFilledPercent(45))
            .Add(4871, BestiaryFilledPercent(30))
            .Add(4907, BestiaryFilledPercent(30))
            .Add(4677, Condition.DownedSolarPillar)
            .Add(4676, BestiaryFilledPercent(10))
            .Add(4762, BestiaryFilledPercent(30))
            .Add(4716, BestiaryFilledPercent(25))
            .Add(4785, BestiaryFilledPercent(30))
            .Add(4786, BestiaryFilledPercent(30))
            .Add(4787, BestiaryFilledPercent(30))
            .Add(4788, BestiaryFilledPercent(30), Condition.Hardmode)
            .Add(4763, BestiaryFilledPercent(35))
            .Add(4955, BestiaryFilledPercent(40))
            .Add(4736, Condition.Hardmode, Condition.BloodMoon)
            .Add(4701, Condition.DownedPlantera)
            .Add(4765, BestiaryFilledPercent(50))
            .Add(4766, BestiaryFilledPercent(50))
            .Add(5285, BestiaryFilledPercent(50))
            .Add(4777, BestiaryFilledPercent(50))
            .Add(4735, BestiaryFilledPercent(70))
            .Add(4951, new Condition("Conditions.BestiaryFull", () => Main.GetBestiaryProgressReport().CompletionPercent >= 1f))
            .Add(4768, Condition.MoonPhasesQuarter0)
            .Add(4769, Condition.MoonPhasesQuarter0)
            .Add(4770, Condition.MoonPhasesQuarter1)
            .Add(4771, Condition.MoonPhasesQuarter1)
            .Add(4772, Condition.MoonPhasesQuarter2)
            .Add(4773, Condition.MoonPhasesQuarter2)
            .Add(4560, Condition.MoonPhasesQuarter3)
            .Add(4775, Condition.MoonPhasesQuarter3)
            .Register();
        static Condition BestiaryFilledPercent(int percent)
        {
            return new Condition(Language.GetText("Conditions.BestiaryPercentage").WithFormatArgs(percent), () => Main.GetBestiaryProgressReport().CompletionPercent >= (float)percent / 100f);
        }
    }
References Terraria.ModLoader.NPCShop.Add(), Terraria.Chest.BestiaryGirl_IsFairyTorchAvailable(), Terraria.Condition(), Terraria.Main.GetBestiaryProgressReport(), Terraria.Localization.Language.GetText(), Terraria.ModLoader.AbstractNPCShop.Register(), and Terraria.Localization.LocalizedText.WithFormatArgs().
Referenced by Terraria.ModLoader.NPCShopDatabase.RegisterVanillaNPCShops().