TModLoader: Terraria.ModLoader.Engine.ServerHangWatchdog.Run
Run()
static void Terraria.ModLoader.Engine.ServerHangWatchdog.Run (Thread mainThread) inline static private
Definition at line 39 of file ServerHangWatchdog.cs.
    {
        while (true)
        {
            Thread.Sleep(1000);
            if (DateTime.Now - lastCheckin.Value > TIMEOUT)
            {
                Logging.ServerConsoleLine("Server hung for more than 10 seconds. Cannot determine cause from watchdog thread", Level.Warn, null, Logging.tML);
                Checkin();
            }
        }
    }
References Terraria.ModLoader.Engine.ServerHangWatchdog.Checkin(), Terraria.ModLoader.Engine.ServerHangWatchdog.lastCheckin, Terraria.ModLoader.Logging.ServerConsoleLine(), Terraria.ModLoader.Engine.ServerHangWatchdog.TIMEOUT, and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.ModLoader.Engine.ServerHangWatchdog.Start().