TModLoader: Terraria.ModLoader.PlayerLoader.SetStartInventory
SetStartInventory()
static void Terraria.ModLoader.PlayerLoader.SetStartInventory (Player player, IList< Item > items) inline static
Definition at line 462 of file PlayerLoader.cs.
    {
        if (items.Count <= 50)
        {
            for (int i = 0; i < 50; i++)
            {
                if (i < items.Count)
                {
                    player.inventory[i] = items[i];
                }
                else
                {
                    player.inventory[i].SetDefaults();
                }
            }
            return;
        }
        for (int k = 0; k < 49; k++)
        {
            player.inventory[k] = items[k];
        }
        Item bag = new Item();
        bag.SetDefaults(ModContent.ItemType<StartBag>());
        for (int j = 49; j < items.Count; j++)
        {
            ((StartBag)bag.ModItem).AddItem(items[j]);
        }
        player.inventory[49] = bag;
    }
References Terraria.Player.inventory, and Terraria.Item.SetDefaults().
Referenced by Terraria.Player.DropItems_End(), and Terraria.GameContent.UI.States.UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty().