TModLoader: Terraria.ModLoader.PlayerLoader.ModifyHurt
ModifyHurt()
static void Terraria.ModLoader.PlayerLoader.ModifyHurt (Player player, ref Player::HurtModifiers modifiers) inline static
Definition at line 998 of file PlayerLoader.cs.
    {
        if (modifiers.DamageSource.TryGetCausingEntity(out var sourceEntity))
        {
            Entity entity = sourceEntity;
            if (!(entity is Projectile proj))
            {
                if (!(entity is NPC npc))
                {
                    if (entity is Player sourcePlayer)
                    {
                        Item item = modifiers.DamageSource.SourceItem;
                        if (item != null && modifiers.PvP)
{
                            ItemLoader.ModifyHitPvp(item, sourcePlayer, player, ref modifiers);
                        }
                    }
                }
                else
                {
                    CombinedHooks.ModifyHitByNPC(player, npc, ref modifiers);
                }
            }
            else
            {
                CombinedHooks.ModifyHitByProjectile(player, proj, ref modifiers);
            }
        }
        FilteredSpanEnumerator<ModPlayer> enumerator = HookModifyHurt.Enumerate(player).GetEnumerator();
        while (enumerator.MoveNext())
        {
            ModPlayer modPlayer = enumerator.Current;
            try
            {
                modPlayer.ModifyHurt(ref modifiers);
            }
            catch
            {
            }
        }
    }
References Terraria.ModLoader.PlayerLoader.HookModifyHurt, Terraria.ModLoader.CombinedHooks.ModifyHitByNPC(), Terraria.ModLoader.CombinedHooks.ModifyHitByProjectile(), and Terraria.ModLoader.ItemLoader.ModifyHitPvp().
Referenced by Terraria.Player.Hurt().