TModLoader: Terraria.ModLoader.PlayerLoader.ModifyMaxStats
ModifyMaxStats()
static void Terraria.ModLoader.PlayerLoader.ModifyMaxStats (Player player) inline static
Reset this player's F:Terraria.Player.statLifeMax and F:Terraria.Player.statManaMax to their vanilla defaults, applies M:Terraria.ModLoader.ModPlayer.ModifyMaxStats(Terraria.ModLoader.StatModifier@,Terraria.ModLoader.StatModifier@) to them, then modifies F:Terraria.Player.statLifeMax2 and F:Terraria.Player.statManaMax2
Parameters
player
    {
        ResetMaxStatsToVanilla(player);
        StatModifier cumulativeHealth = StatModifier.Default;
        StatModifier cumulativeMana = StatModifier.Default;
        FilteredSpanEnumerator<ModPlayer> enumerator = HookModifyMaxStats.Enumerate(player).GetEnumerator();
        while (enumerator.MoveNext())
        {
            enumerator.Current.ModifyMaxStats(out var health, out var mana);
            cumulativeHealth = cumulativeHealth.CombineWith(health);
            cumulativeMana = cumulativeMana.CombineWith(mana);
        }
        player.statLifeMax = (int)cumulativeHealth.ApplyTo(player.statLifeMax);
        player.statManaMax = (int)cumulativeMana.ApplyTo(player.statManaMax);
    }
References Terraria.ModLoader.StatModifier.Default, Terraria.ModLoader.PlayerLoader.HookModifyMaxStats, Terraria.ModLoader.PlayerLoader.ResetMaxStatsToVanilla(), Terraria.Player.statLifeMax, and Terraria.Player.statManaMax.
Referenced by Terraria.Player.Player(), Terraria.Player.ResetEffects(), and Terraria.GameContent.UI.States.UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty().