TModLoader: Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButton_Inner
MakeFancyButton_Inner()
UIElement Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButton_Inner (Asset< Texture2D > iconImage, string textKey) inline private
    {
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        UIPanel uIPanel = new UIPanel();
        int num = -3;
        int num2 = -3;
        uIPanel.Width = StyleDimension.FromPixelsAndPercent(num, 0.5f);
        uIPanel.Height = StyleDimension.FromPixelsAndPercent(num2, 0.33f);
        uIPanel.OnMouseOver += SetColorsToHovered;
        uIPanel.OnMouseOut += SetColorsToNotHovered;
        uIPanel.BackgroundColor = new Color(63, 82, 151) * 0.7f;
        uIPanel.BorderColor = new Color(89, 116, 213) * 0.7f;
        uIPanel.SetPadding(6f);
        UIImage uIImage = new UIImage(iconImage)
        {
            IgnoresMouseInteraction = true,
            VAlign = 0.5f
        };
        uIImage.Left.Set(2f, 0f);
        uIPanel.Append(uIImage);
        uIPanel.OnMouseOver += ShowOptionDescription;
        uIPanel.OnMouseOut += ClearOptionDescription;
        UIText uIText = new UIText(Language.GetText(textKey), 0.45f, large: true)
        {
            HAlign = 0f,
            VAlign = 0.5f,
            Width = StyleDimension.FromPixelsAndPercent(-80f, 1f),
            Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
            Top = StyleDimension.FromPixelsAndPercent(5f, 0f),
            Left = StyleDimension.FromPixels(80f),
            IgnoresMouseInteraction = true,
            TextOriginX = 0f,
            TextOriginY = 0f
        };
        uIText.PaddingLeft = 0f;
        uIText.PaddingRight = 20f;
        uIText.PaddingTop = 10f;
        uIText.IsWrapped = true;
        uIPanel.Append(uIText);
        uIPanel.SetSnapPoint("Button", 0);
        return uIPanel;
    }
References Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UIWorkshopHub.ClearOptionDescription(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.States.UIWorkshopHub.SetColorsToHovered(), Terraria.GameContent.UI.States.UIWorkshopHub.SetColorsToNotHovered(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.States.UIWorkshopHub.ShowOptionDescription(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButton(), and Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButtonMod().