TModLoader: Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButtonMod
MakeFancyButtonMod()
UIElement Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButtonMod (string path, string textKey) inline private
Definition at line 509 of file UIWorkshopHub.cs.
    {
        return MakeFancyButton_Inner(Terraria.ModLoader.ModLoader.ManifestAssets.Request<Texture2D>(path), textKey);
    }
References Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButton_Inner(), and Terraria.ModLoader.ModLoader.ManifestAssets.
Referenced by Terraria.GameContent.UI.States.UIWorkshopHub.MakeButton_ModPackMenu(), Terraria.GameContent.UI.States.UIWorkshopHub.MakeButton_OpenModBrowserMenu(), Terraria.GameContent.UI.States.UIWorkshopHub.MakeButton_OpenModsMenu(), and Terraria.GameContent.UI.States.UIWorkshopHub.MakeButton_OpenModSourcesMenu().