TModLoader: Terraria.Physics.BallCollision.GetClosestEdgeToCircle
GetClosestEdgeToCircle()
static bool Terraria.Physics.BallCollision.GetClosestEdgeToCircle (Vector2 position, Vector2 size, Vector2 velocity, out Vector2 collisionPoint, out Tile collisionTile) inline static private
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_012e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        Rectangle tileBounds = GetTileBounds(position, size);
        Vector2 vector = position + size * 0.5f;
        TileEdges tileEdges = TileEdges.None;
        tileEdges = ((!(velocity.Y < 0f)) ? (tileEdges | TileEdges.Top) : (tileEdges | TileEdges.Bottom));
        tileEdges = ((!(velocity.X < 0f)) ? (tileEdges | TileEdges.Left) : (tileEdges | TileEdges.Right));
        tileEdges = ((!(velocity.Y > velocity.X)) ? (tileEdges | TileEdges.TopRightSlope) : (tileEdges | TileEdges.BottomLeftSlope));
        tileEdges = ((!(velocity.Y > 0f - velocity.X)) ? (tileEdges | TileEdges.TopLeftSlope) : (tileEdges | TileEdges.BottomRightSlope));
        collisionPoint = Vector2.Zero;
        collisionTile = default(Tile);
        float num = float.MaxValue;
        Vector2 closestPointOut = default(Vector2);
        float distanceSquaredOut = 0f;
        for (int i = ((Rectangle)(ref tileBounds)).Left; i < ((Rectangle)(ref tileBounds)).Right; i++)
        {
            for (int j = ((Rectangle)(ref tileBounds)).Top; j < ((Rectangle)(ref tileBounds)).Bottom; j++)
            {
                if (GetCollisionPointForTile(tileEdges, i, j, vector, ref closestPointOut, ref distanceSquaredOut) && !(distanceSquaredOut >= num) && !(Vector2.Dot(velocity, vector - closestPointOut) > 0f))
                {
                    num = distanceSquaredOut;
                    collisionPoint = closestPointOut;
                    collisionTile = Main.tile[i, j];
                }
            }
        }
        float num2 = size.X / 2f;
        return num < num2 * num2;
    }
References Terraria.Physics.BallCollision.Bottom, Terraria.Physics.BallCollision.GetCollisionPointForTile(), Terraria.Physics.BallCollision.GetTileBounds(), Terraria.Physics.BallCollision.Right, and Terraria.Main.tile.
Referenced by Terraria.Physics.BallCollision.Step().