TModLoader: Terraria.Physics.BallCollision.GetLeftOrRightEdge
GetLeftOrRightEdge()
static bool Terraria.Physics.BallCollision.GetLeftOrRightEdge (TileEdges edgesToTest, int x, int y, Vector2 tilePosition, ref LineSegment edge) inline static private
    {
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        if ((edgesToTest & TileEdges.Left) != 0)
        {
            Tile tile = Main.tile[x, y];
            Tile tile2 = Main.tile[x - 1, y];
            if (IsNeighborSolid(tile2) && tile2.slope() != 1 && tile2.slope() != 3 && (!tile2.halfBrick() || tile.halfBrick()))
            {
                return false;
            }
            edge.Start = new Vector2(tilePosition.X, tilePosition.Y);
            edge.End = new Vector2(tilePosition.X, tilePosition.Y + 16f);
            if (tile.halfBrick())
            {
                edge.Start.Y += 8f;
            }
            return true;
        }
        if ((edgesToTest & TileEdges.Right) != 0)
        {
            Tile tile3 = Main.tile[x, y];
            Tile tile4 = Main.tile[x + 1, y];
            if (IsNeighborSolid(tile4) && tile4.slope() != 2 && tile4.slope() != 4 && (!tile4.halfBrick() || tile3.halfBrick()))
            {
                return false;
            }
            edge.Start = new Vector2(tilePosition.X + 16f, tilePosition.Y);
            edge.End = new Vector2(tilePosition.X + 16f, tilePosition.Y + 16f);
            if (tile3.halfBrick())
            {
                edge.Start.Y += 8f;
            }
            return true;
        }
        return false;
    }
References Terraria.Tile.halfBrick(), Terraria.Physics.BallCollision.IsNeighborSolid(), and Terraria.Main.tile.
Referenced by Terraria.Physics.BallCollision.GetCollisionPointForTile().