TModLoader: Terraria.Physics.BallCollision.GetCollisionPointForTile
GetCollisionPointForTile()
static bool Terraria.Physics.BallCollision.GetCollisionPointForTile (TileEdges edgesToTest, int x, int y, Vector2 center, ref Vector2 closestPointOut, ref float distanceSquaredOut) inline static private
    {
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0126: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_0107: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        Tile tile = Main.tile[x, y];
        if (tile == null || !tile.nactive() || (!Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type]))
        {
            return false;
        }
        if (!Main.tileSolid[tile.type] && Main.tileSolidTop[tile.type] && tile.frameY != 0)
        {
            return false;
        }
        if (Main.tileSolidTop[tile.type])
        {
            edgesToTest &= TileEdges.Top | TileEdges.BottomLeftSlope | TileEdges.BottomRightSlope;
        }
        Vector2 tilePosition = default(Vector2);
        ((Vector2)(ref tilePosition))._002Ector((float)x * 16f, (float)y * 16f);
        bool flag = false;
        LineSegment edge = default(LineSegment);
        if (GetSlopeEdge(ref edgesToTest, tile, tilePosition, ref edge))
        {
            closestPointOut = ClosestPointOnLineSegment(center, edge);
            distanceSquaredOut = Vector2.DistanceSquared(closestPointOut, center);
            flag = true;
        }
        if (GetTopOrBottomEdge(edgesToTest, x, y, tilePosition, ref edge))
        {
            Vector2 vector = ClosestPointOnLineSegment(center, edge);
            float num = Vector2.DistanceSquared(vector, center);
            if (!flag || num < distanceSquaredOut)
            {
                distanceSquaredOut = num;
                closestPointOut = vector;
            }
            flag = true;
        }
        if (GetLeftOrRightEdge(edgesToTest, x, y, tilePosition, ref edge))
        {
            Vector2 vector2 = ClosestPointOnLineSegment(center, edge);
            float num2 = Vector2.DistanceSquared(vector2, center);
            if (!flag || num2 < distanceSquaredOut)
            {
                distanceSquaredOut = num2;
                closestPointOut = vector2;
            }
            flag = true;
        }
        return flag;
    }
References Terraria.Physics.BallCollision.ClosestPointOnLineSegment(), Terraria.Tile.frameY, Terraria.Physics.BallCollision.GetLeftOrRightEdge(), Terraria.Physics.BallCollision.GetSlopeEdge(), Terraria.Physics.BallCollision.GetTopOrBottomEdge(), Terraria.Tile.nactive(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.Physics.BallCollision.GetClosestEdgeToCircle().