TModLoader: Terraria.Physics.BallCollision.Step
Step()
static BallStepResult Terraria.Physics.BallCollision.Step (PhysicsProperties physicsProperties, Entity entity, ref float entityAngularVelocity, IBallContactListener listener) inline static
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_020d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0212: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0266: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_014b: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0230: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_016f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0174: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_023d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_024a: Unknown result type (might be due to invalid IL or missing references)
        Vector2 position = entity.position;
        Vector2 velocity = entity.velocity;
        Vector2 size = entity.Size;
        float num = entityAngularVelocity;
        float num2 = size.X * 0.5f;
        num *= physicsProperties.Drag;
        velocity *= physicsProperties.Drag;
        float num3 = ((Vector2)(ref velocity)).Length();
        if (num3 > 1000f)
        {
            velocity = 1000f * Vector2.Normalize(velocity);
            num3 = 1000f;
        }
        int num4 = Math.Max(1, (int)Math.Ceiling(num3 / 2f));
        float num5 = 1f / (float)num4;
        velocity *= num5;
        num *= num5;
        float num6 = physicsProperties.Gravity / (float)(num4 * num4);
        bool flag = false;
        for (int i = 0; i < num4; i++)
        {
            velocity.Y += num6;
            if (CheckForPassThrough(position + size * 0.5f, out var type, out var contactTile))
            {
                if (type == BallPassThroughType.Tile && Main.tileSolid[contactTile.type] && !Main.tileSolidTop[contactTile.type])
                {
                    velocity *= 0f;
                    num *= 0f;
                    flag = true;
                }
                else
                {
                    BallPassThroughEvent passThrough = new BallPassThroughEvent(num5, contactTile, entity, type);
                    listener.OnPassThrough(physicsProperties, ref position, ref velocity, ref num, ref passThrough);
                }
            }
            position += velocity;
            if (!IsBallInWorld(position, size))
            {
                return BallStepResult.OutOfBounds();
            }
            if (GetClosestEdgeToCircle(position, size, velocity, out var collisionPoint, out contactTile))
            {
                Vector2 vector = Vector2.Normalize(position + size * 0.5f - collisionPoint);
                position = collisionPoint + vector * (num2 + 0.0001f) - size * 0.5f;
                BallCollisionEvent collision = new BallCollisionEvent(num5, vector, collisionPoint, contactTile, entity);
                flag = true;
                velocity = Vector2.Reflect(velocity, collision.Normal);
                listener.OnCollision(physicsProperties, ref position, ref velocity, ref collision);
                num = (collision.Normal.X * velocity.Y - collision.Normal.Y * velocity.X) / num2;
            }
        }
        velocity /= num5;
        num /= num5;
        BallStepResult result = BallStepResult.Moving();
        if (flag && velocity.X > -0.01f && velocity.X < 0.01f && velocity.Y <= 0f && velocity.Y > 0f - physicsProperties.Gravity)
        {
            result = BallStepResult.Resting();
        }
        entity.position = position;
        entity.velocity = velocity;
        entityAngularVelocity = num;
        return result;
    }
References Terraria.Physics.BallCollision.CheckForPassThrough(), Terraria.Physics.BallCollision.GetClosestEdgeToCircle(), Terraria.Physics.BallCollision.IsBallInWorld(), Terraria.Physics.BallStepResult.Moving(), Terraria.Physics.BallStepResult.OutOfBounds(), Terraria.Entity.position, Terraria.Physics.BallStepResult.Resting(), Terraria.Entity.Size, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Entity.velocity.
Referenced by Terraria.GameContent.Golf.GolfHelper.StepGolfBall().