TModLoader: Terraria.Localization.LocalizedText.Format
Format()
string Terraria.Localization.LocalizedText.Format (params object[] args) inline
Creates a string from this LocalizedText populated with data from the provided args arguments. Formats the string in the same manner as string.Format. Placeholders such as "{0}", "{1}", etc will be replaced with the string representation of the corresponding objects provided.
Additionally, pluralization is supported as well. The Contributing Localization Guideteaches more about placeholders and plural support.
Parameters
args
Returns
Definition at line 207 of file LocalizedText.cs.
    {
        string value = Value;
        bool valueOrDefault = _hasPlurals.GetValueOrDefault();
        bool num;
        if (!_hasPlurals.HasValue)
        {
            valueOrDefault = PluralizationPatternRegex.IsMatch(value);
            _hasPlurals = valueOrDefault;
            num = valueOrDefault;
        }
        else
        {
            num = valueOrDefault;
        }
        if (num)
        {
            value = ApplyPluralization(value, args);
        }
        try
        {
            return string.Format(value, args);
        }
        catch (FormatException e)
        {
            throw new Exception($"The localization key:\n  \"{Key}\"\nwith a value of:\n  \"{value}\"\nfailed to be formatted with the inputs:\n  [{string.Join(", ", args)}]", e);
        }
    }
References Terraria.Localization.LocalizedText._hasPlurals, Terraria.Localization.LocalizedText.ApplyPluralization(), Terraria.Localization.LocalizedText.PluralizationPatternRegex, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Localization.LocalizedText.BindArgs(), Terraria.NetMessage.SyncOnePlayer(), and Terraria.WorldGen.UnspawnTravelNPC().