TModLoader: Terraria.GameContent.ShimmerHelper.IsSpotShimmerFree
IsSpotShimmerFree()
static bool Terraria.GameContent.ShimmerHelper.IsSpotShimmerFree (Entity entity, Vector2 landingPosition, bool allowSolidTop) inline static private
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        if (Collision.SolidCollision(landingPosition, entity.width, entity.height))
        {
            return false;
        }
        if (!Collision.SolidCollision(landingPosition + new Vector2(0f, (float)entity.height), entity.width, 100, allowSolidTop))
        {
            return false;
        }
        if (Collision.WetCollision(landingPosition, entity.width, entity.height + 100) && Collision.shimmer)
        {
            return false;
        }
        return true;
    }
References Terraria.Entity.height, Terraria.Collision.shimmer, Terraria.Collision.SolidCollision(), Terraria.Collision.WetCollision(), and Terraria.Entity.width.
Referenced by Terraria.GameContent.ShimmerHelper.FindSpotWithoutShimmer().