TModLoader: Terraria.NPC.AI_87_BigMimic_ShootItem
AI_87_BigMimic_ShootItem()
void Terraria.NPC.AI_87_BigMimic_ShootItem (int itemID) inline private
    {
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        int num = Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, itemID, 1, noBroadcast: false, -1, noGrabDelay: true);
        float num5 = Main.rand.Next(10, 26);
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
        Vector2 val = Main.player[target].Center - new Vector2(0f, 120f);
        float num2 = val.X - vector.X;
        float num3 = val.Y - vector.Y;
        num2 += (float)Main.rand.Next(-50, 51) * 0.1f;
        num3 += (float)Main.rand.Next(-50, 51) * 0.1f;
        float num4 = (float)Math.Sqrt(num2 * num2 + num3 * num3);
        num4 = num5 / num4;
        num2 *= num4;
        num3 *= num4;
        num2 += (float)Main.rand.Next(-50, 51) * 0.1f;
        num3 += (float)Main.rand.Next(-50, 51) * 0.1f;
        Main.item[num].velocity.X = num2;
        Main.item[num].velocity.Y = num3;
        Main.item[num].noGrabDelay = 100;
        if (Main.netMode != 0)
        {
            NetMessage.SendData(21, -1, -1, null, num);
        }
    }
References Terraria.Entity.Center, Terraria.NPC.GetItemSource_Loot(), Terraria.Entity.height, Terraria.Main.item, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Item.noGrabDelay, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.NPC.target, Terraria.Entity.velocity, and Terraria.Entity.width.
Referenced by Terraria.NPC.AI_87_BigMimic_FireStuffCannonBurst().