TModLoader: Terraria.NPC.FairyEffects
FairyEffects()
static void Terraria.NPC.FairyEffects (Vector2 Position, int type) inline static
Definition at line 51078 of file NPC.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        Color value = Color.HotPink;
        Color value2 = Color.LightPink;
        int num = 4;
        if (type == 1)
        {
            value = Color.LimeGreen;
            value2 = Color.LightSeaGreen;
        }
        if (type == 2)
        {
            value = Color.RoyalBlue;
            value2 = Color.LightBlue;
        }
        for (int i = 0; i < 40; i++)
        {
            Dust dust = Dust.NewDustDirect(Position - new Vector2((float)num) * 0.5f, num + 4, num + 4, 278, 0f, 0f, 200, Color.Lerp(value, value2, Main.rand.NextFloat()), 0.65f);
            dust.velocity *= 1.5f;
            if (i >= 30)
            {
                dust.velocity *= 3.5f;
            }
            else if (i >= 20)
            {
                dust.velocity *= 2f;
            }
            dust.fadeIn = (float)Main.rand.Next(0, 17) * 0.1f;
            dust.noGravity = true;
        }
        SoundEngine.PlaySound(SoundID.Item4, (int)Position.X, (int)Position.Y);
    }
References Terraria.ID.SoundID.Item4, Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.NPC.type, and Terraria.NPC.value.
Referenced by Terraria.NPC.AI_112_FairyCritter(), and Terraria.MessageBuffer.GetData().