TModLoader: Terraria.NPC.AI_115_LadyBugs
AI_115_LadyBugs()
void Terraria.NPC.AI_115_LadyBugs () inline private
    {
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0217: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0222: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_047c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0494: Unknown result type (might be due to invalid IL or missing references)
        //IL_0244: Unknown result type (might be due to invalid IL or missing references)
        //IL_0254: Unknown result type (might be due to invalid IL or missing references)
        //IL_05dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0340: Unknown result type (might be due to invalid IL or missing references)
        //IL_0351: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0533: Unknown result type (might be due to invalid IL or missing references)
        //IL_0130: Unknown result type (might be due to invalid IL or missing references)
        //IL_0558: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode != 1)
        {
            if (ai[1] == 0f)
            {
                ai[1] = Main.rand.NextFloat() * 0.2f + 0.7f;
                netUpdate = true;
            }
            if ((localAI[0] -= 1f) <= 0f)
            {
                localAI[0] = Main.rand.Next(60, 181);
                if (Main.rand.Next(5) == 0)
                {
                    if (ai[2] == 0f)
                    {
                        ai[2] = 1f;
                        ai[0] = 0f;
                        netUpdate = true;
                    }
                    else if (ai[2] == 1f)
                    {
                        TargetClosest();
                        ai[2] = 0f;
                        ai[0] = Main.rand.NextFloat() * ((float)Math.PI * 2f);
                        if (Distance(Main.player[target].Center) > 700f)
{
                            ai[0] = AngleTo(Main.player[target].Center) + Main.rand.NextFloatDirection() * 0.3f;
                        }
                        netUpdate = true;
                    }
                }
                TargetClosest();
                ai[0] = Main.rand.NextFloat() * ((float)Math.PI * 2f);
                if (Distance(Main.player[target].Center) > 700f)
                {
                    ai[0] = AngleTo(Main.player[target].Center) + Main.rand.NextFloatDirection() * 0.3f;
                }
                netUpdate = true;
            }
        }
        scale = ai[1];
        if (ai[2] == 0f)
        {
            Vector2 value = ai[0].ToRotationVector2() * 1f;
            value.X += Main.windSpeedTarget * 0.8f;
            velocity = Vector2.Lerp(velocity, value, 0.0125f);
            if (velocity.Y > 0f)
            {
                int num = 4;
                int num2 = (int)base.Center.X / 16;
                int num3 = (int)base.Center.Y / 16;
                for (int i = num3; i < num3 + num; i++)
                {
                    if (Main.tile[num2, i] != null && ((Main.tile[num2, i].nactive() && Main.tileSolid[Main.tile[num2, i].type]) || Main.tile[num2, i].liquid > 0))
                    {
                        ai[0] = 0f - ai[0];
                        if (velocity.Y > 0f)
{
                            velocity.Y *= 0.9f;
                        }
                    }
                }
            }
            if (velocity.Y < 0f)
            {
                int num4 = 30;
                bool flag = false;
                int num5 = (int)base.Center.X / 16;
                int num6 = (int)base.Center.Y / 16;
                for (int j = num6; j < num6 + num4; j++)
                {
                    if (Main.tile[num5, j] != null && ((Main.tile[num5, j].nactive() && Main.tileSolid[Main.tile[num5, j].type]) || Main.tile[num5, j].liquid > 0))
                    {
                        flag = true;
                    }
                }
                if (!flag)
                {
                    ai[0] = 0f - ai[0];
                    if (velocity.Y < 0f)
                    {
                        velocity.Y *= 0.9f;
                    }
                }
            }
            if (collideX)
            {
                ai[0] = 0f - ai[0] + (float)Math.PI;
                velocity.X *= -0.2f;
            }
        }
        else
        {
            if (velocity.Y > 0f)
            {
                int num7 = 4;
                int num8 = (int)base.Center.X / 16 + direction;
                int num9 = (int)base.Center.Y / 16;
                for (int k = num9; k < num9 + num7; k++)
                {
                    if (Main.tile[num8, k] != null && Main.tile[num8, k].liquid > 0)
                    {
                        TargetClosest();
                        velocity.Y = -1f;
                        ai[2] = 0f;
                        ai[0] = Main.rand.NextFloat() * ((float)Math.PI / 4f) - (float)Math.PI / 2f;
                        if (Distance(Main.player[target].Center) > 700f)
{
                            ai[0] = AngleTo(Main.player[target].Center) + Main.rand.NextFloatDirection() * 0.3f;
                        }
                        netUpdate = true;
                        return;
                    }
                }
            }
            if (velocity.Y != 0f)
            {
                velocity.X *= 0.98f;
                velocity.Y = MathHelper.Lerp(velocity.Y, 2f, 0.005f);
            }
            else
            {
                velocity = Vector2.Lerp(velocity, Vector2.UnitX * (float)direction, 0.05f);
                velocity.Y += 0.2f;
                if (collideX)
                {
                    direction *= -1;
                    velocity.X *= -0.2f;
                    netUpdate = true;
                }
            }
        }
        direction = ((velocity.X > 0f) ? 1 : (-1));
    }
References Terraria.NPC.ai, Terraria.Entity.AngleTo(), Terraria.Entity.Center, Terraria.NPC.collideX, Terraria.Entity.direction, Terraria.Entity.Distance(), Terraria.NPC.localAI, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Main.rand, Terraria.NPC.scale, Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.NPC.value, and Terraria.Entity.velocity.
Referenced by Terraria.NPC.VanillaAI_Inner().