TModLoader: Terraria.NPC.AI_007_TryForcingSitting
AI_007_TryForcingSitting()
void Terraria.NPC.AI_007_TryForcingSitting (int homeFloorX, int homeFloorY) inline private
Definition at line 56168 of file NPC.cs.
    {
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_019b: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0113: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        Tile tile = Main.tile[homeFloorX, homeFloorY - 1];
        bool flag = !NPCID.Sets.CannotSitOnFurniture[type] && !NPCID.Sets.IsTownSlime[type] && ai[0] != 5f;
        if (flag)
        {
            flag &= tile != null && tile.active() && TileID.Sets.CanBeSatOnForNPCs[tile.type];
        }
        if (flag)
        {
            flag &= tile.type != 15 || tile.frameY < 1080 || tile.frameY > 1098;
        }
        if (flag)
        {
            Point point = (base.Bottom + Vector2.UnitY * -2f).ToTileCoordinates();
            for (int i = 0; i < 200; i++)
            {
                if (Main.npc[i].active && Main.npc[i].aiStyle == 7 && Main.npc[i].townNPC && Main.npc[i].ai[0] == 5f && (Main.npc[i].Bottom + Vector2.UnitY * -2f).ToTileCoordinates() == point)
                {
                    flag = false;
                    break;
                }
            }
        }
        if (flag)
        {
            ai[0] = 5f;
            ai[1] = 900 + Main.rand.Next(10800);
            SitDown(new Point(homeFloorX, homeFloorY - 1), out var targetDirection, out var bottom);
            direction = targetDirection;
            base.Bottom = bottom;
            velocity = Vector2.Zero;
            localAI[3] = 0f;
            netUpdate = true;
        }
    }
References Terraria.Entity.active, Terraria.Tile.active(), Terraria.NPC.ai, Terraria.NPC.aiStyle, Terraria.Entity.Bottom, Terraria.ID.TileID.Sets.CanBeSatOnForNPCs, Terraria.ID.NPCID.Sets.CannotSitOnFurniture, Terraria.Entity.direction, Terraria.ID.NPCID.Sets.IsTownSlime, Terraria.NPC.localAI, Terraria.NPC.netUpdate, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Main.rand, Terraria.NPC.SitDown(), Terraria.Main.tile, Terraria.NPC.townNPC, Terraria.NPC.type, Terraria.Tile.type, and Terraria.Entity.velocity.
Referenced by Terraria.NPC.AI_007_TownEntities(), and Terraria.NPC.AI_007_TownEntities_TeleportToHome().