TModLoader: Terraria.NPC.GetAlpha
GetAlpha()
Color Terraria.NPC.GetAlpha (Color newColor) inline
    {
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0137: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0218: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_022e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_0246: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        //IL_0255: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_029c: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02da: Unknown result type (might be due to invalid IL or missing references)
        //IL_02db: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0358: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_0363: Unknown result type (might be due to invalid IL or missing references)
        //IL_0368: Unknown result type (might be due to invalid IL or missing references)
        //IL_036a: Unknown result type (might be due to invalid IL or missing references)
        //IL_032b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0391: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0417: Unknown result type (might be due to invalid IL or missing references)
        //IL_0437: Unknown result type (might be due to invalid IL or missing references)
        //IL_0438: Unknown result type (might be due to invalid IL or missing references)
        //IL_0442: Unknown result type (might be due to invalid IL or missing references)
        //IL_0447: Unknown result type (might be due to invalid IL or missing references)
        //IL_0449: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_0521: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_057c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0643: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0667: Unknown result type (might be due to invalid IL or missing references)
        //IL_0843: Unknown result type (might be due to invalid IL or missing references)
        //IL_0705: Unknown result type (might be due to invalid IL or missing references)
        //IL_0706: Unknown result type (might be due to invalid IL or missing references)
        //IL_0710: Unknown result type (might be due to invalid IL or missing references)
        //IL_0715: Unknown result type (might be due to invalid IL or missing references)
        //IL_0717: Unknown result type (might be due to invalid IL or missing references)
        //IL_0721: Unknown result type (might be due to invalid IL or missing references)
        //IL_0726: Unknown result type (might be due to invalid IL or missing references)
        //IL_0728: Unknown result type (might be due to invalid IL or missing references)
        if (IsABestiaryIconDummy)
        {
            newColor = Color.White;
        }
        Color? val = NPCLoader.GetAlpha(this, newColor);
        if (val.HasValue)
        {
            return val.GetValueOrDefault();
        }
        float num = (float)(255 - alpha) / 255f;
        int num2 = (int)((float)(int)((Color)(ref newColor)).R * num);
        int num3 = (int)((float)(int)((Color)(ref newColor)).G * num);
        int num4 = (int)((float)(int)((Color)(ref newColor)).B * num);
        int num5 = ((Color)(ref newColor)).A - alpha;
        if (type == 402)
        {
            return new Color(255, 255, 255, 255);
        }
        if (type == 484)
        {
            return new Color(250, 250, 250, 200);
        }
        if (type >= 542 && type <= 545 && num2 + num3 + num4 > 10 && num2 + num3 + num4 >= 60)
        {
            num2 *= 2;
            num3 *= 2;
            num4 *= 2;
            if (num2 > 255)
            {
                num2 = 255;
            }
            if (num3 > 255)
            {
                num3 = 255;
            }
            if (num4 > 255)
            {
                num4 = 255;
            }
        }
        if (type == 681)
        {
            return Color.Lerp(newColor, Color.White, 0.4f) * Opacity;
        }
        if (type == 683 || type == 687)
        {
            float num6 = Utils.Remap(Utils.WrappedLerp(0.75f, 1f, (float)Main.timeForVisualEffects % 120f / 120f), 0f, 1f, 0.5f, 1f);
            Color result = Color.Lerp(newColor, new Color(255, 255, 100), 0.4f * num6) * Opacity;
            if (((Color)(ref result)).B < num4)
            {
                ((Color)(ref result)).B = (byte)num4;
            }
            return result;
        }
        if (type == 658 || type == 659 || type == 660)
        {
            return Color.Lerp(newColor, Color.White, 0.4f) * Opacity;
        }
        if (type == 662)
        {
            Color color = Color.Lerp(Color.White, Color.Cyan, 0.5f);
            ((Color)(ref color)).A = (byte)(((Color)(ref color)).A / 4);
            return color * Opacity;
        }
        if ((type >= 454 && type <= 459) || type == 521)
        {
            newColor = Color.Lerp(newColor, Color.White, 0.4f);
            ((Color)(ref newColor)).A = 150;
            newColor *= (float)num5 / 255f;
            return newColor;
        }
        if (type == 636)
        {
            newColor = Color.Lerp(newColor, Color.White, 0.25f);
            return newColor * Opacity;
        }
        if (type == 440)
        {
            byte b = 180;
            if (Main.expertMode)
            {
                b = 210;
            }
            b = (byte)((float)(int)b * num);
            return new Color((int)b, (int)b, (int)b, (int)b);
        }
        if (type == 583 || type == 584 || type == 585)
        {
            newColor = Color.Lerp(newColor, Color.White, 0.5f);
            return newColor;
        }
        if (type == 516)
        {
            return new Color(alpha, alpha, alpha, alpha);
        }
        if (type == 522)
        {
            return new Color(255 - alpha, 255 - alpha, 255 - alpha, 255 - alpha);
        }
        if (type == 523)
        {
            return new Color(255 - alpha, 255 - alpha, 255 - alpha, 255 - alpha);
        }
        if (type == 395 || type == 519)
        {
            newColor = Color.Lerp(newColor, Color.White, 0.4f);
            return newColor;
        }
        if (type == 370 && ai[0] != -1f && ai[0] < 9f)
        {
            float num7 = MathHelper.Lerp(num, 1f, 0.25f);
            if (num7 > 1f)
            {
                num7 = 1f;
            }
            num4 = (int)((float)(int)((Color)(ref newColor)).B * num7);
        }
        if (type == 30 || type == 665)
        {
            return new Color(250, 250, 250, 100);
        }
        if (!IsABestiaryIconDummy && (type == 25 || type == 30 || type == 665 || type == 59 || type == 60))
        {
            return new Color(200, 200, 200, 0);
        }
        if (type == 360)
        {
            num2 = ((Color)(ref newColor)).R;
            num3 = ((Color)(ref newColor)).G;
            num4 = ((Color)(ref newColor)).B;
            if (num2 < 75)
            {
                num2 = 75;
            }
            if (num3 < 175)
            {
                num3 = 175;
            }
            if (num4 < 255)
            {
                num4 = 255;
            }
            return new Color(num2, num3, num4, 255);
        }
        if (type == 655)
        {
            num2 = ((Color)(ref newColor)).R;
            num3 = ((Color)(ref newColor)).G;
            num4 = ((Color)(ref newColor)).B;
            if (num2 < 255)
            {
                num2 = 255;
            }
            if (num3 < 100)
            {
                num3 = 100;
            }
            if (num4 < 50)
            {
                num4 = 50;
            }
            return new Color(num2, num3, num4, 255);
        }
        if (type == 352)
        {
            return new Color(255, 255, 255, 200);
        }
        if (type == 72)
        {
            num2 = ((Color)(ref newColor)).R;
            num3 = ((Color)(ref newColor)).G;
            num4 = ((Color)(ref newColor)).B;
        }
        else
        {
            if (type == 288)
            {
                return new Color(200, 200, 200, 0);
            }
            if (type == 289)
            {
                return new Color(250, 250, 250, 50);
            }
            if (type >= 254 && type <= 261)
            {
                num4 = 255;
                if (num2 < 100)
                {
                    num2 = 100;
                }
                if (num3 < 150)
                {
                    num3 = 150;
                }
            }
            else if (type == 374 || type == 634 || type == 635)
            {
                num4 = 255;
                if (num2 < 100)
                {
                    num2 = 100;
                }
                if (num3 < 150)
                {
                    num3 = 150;
                }
            }
            else
            {
                if (type == 549)
                {
                    newColor = Color.Lerp(newColor, Color.White, 0.4f);
                    newColor *= (float)num5 / 255f;
                    return newColor;
                }
                if (type == 64 || type == 63 || type == 75 || type == 103 || type == 400)
                {
                    num2 = (int)((double)(int)((Color)(ref newColor)).R * 1.5);
                    num3 = (int)((double)(int)((Color)(ref newColor)).G * 1.5);
                    num4 = (int)((double)(int)((Color)(ref newColor)).B * 1.5);
                    if (num2 > 255)
                    {
                        num2 = 255;
                    }
                    if (num3 > 255)
                    {
                        num3 = 255;
                    }
                    if (num4 > 255)
                    {
                        num4 = 255;
                    }
                }
            }
        }
        if (shimmerTransparency > 0f && !CanApplyHunterPotionEffects())
        {
            num2 = (byte)((float)num2 * (1f - shimmerTransparency));
            num3 = (byte)((float)num3 * (1f - shimmerTransparency));
            num4 = (byte)((float)num4 * (1f - shimmerTransparency));
            num5 = (byte)((float)num5 * (1f - shimmerTransparency));
        }
        if (num5 < 0)
        {
            num5 = 0;
        }
        if (num5 > 255)
        {
            num5 = 255;
        }
        return new Color(num2, num3, num4, num5);
    }
References Terraria.Main.expertMode, Terraria.ModLoader.NPCLoader.GetAlpha(), Terraria.Utils.Remap(), Terraria.Main.timeForVisualEffects, and Terraria.Utils.WrappedLerp().