TModLoader: Terraria.NPC.AI_111_DD2LightningBug
AI_111_DD2LightningBug()
void Terraria.NPC.AI_111_DD2LightningBug () inline private
    {
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00da: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_059f: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_020d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0217: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_023f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0244: Unknown result type (might be due to invalid IL or missing references)
        //IL_0257: Unknown result type (might be due to invalid IL or missing references)
        //IL_0261: Unknown result type (might be due to invalid IL or missing references)
        //IL_026b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0271: Unknown result type (might be due to invalid IL or missing references)
        //IL_027f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        //IL_028e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0608: Unknown result type (might be due to invalid IL or missing references)
        //IL_0614: Unknown result type (might be due to invalid IL or missing references)
        //IL_0619: Unknown result type (might be due to invalid IL or missing references)
        //IL_061b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0621: Unknown result type (might be due to invalid IL or missing references)
        //IL_0626: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        //IL_0649: Unknown result type (might be due to invalid IL or missing references)
        //IL_0655: Unknown result type (might be due to invalid IL or missing references)
        //IL_065a: Unknown result type (might be due to invalid IL or missing references)
        //IL_065c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0662: Unknown result type (might be due to invalid IL or missing references)
        //IL_0667: Unknown result type (might be due to invalid IL or missing references)
        //IL_0351: Unknown result type (might be due to invalid IL or missing references)
        //IL_0356: Unknown result type (might be due to invalid IL or missing references)
        //IL_0671: Unknown result type (might be due to invalid IL or missing references)
        //IL_082b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0836: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_084a: Unknown result type (might be due to invalid IL or missing references)
        //IL_084f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0854: Unknown result type (might be due to invalid IL or missing references)
        //IL_0856: Unknown result type (might be due to invalid IL or missing references)
        //IL_085d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0871: Unknown result type (might be due to invalid IL or missing references)
        //IL_0878: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        //IL_0402: Unknown result type (might be due to invalid IL or missing references)
        //IL_040f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0414: Unknown result type (might be due to invalid IL or missing references)
        //IL_041a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0420: Unknown result type (might be due to invalid IL or missing references)
        //IL_0425: Unknown result type (might be due to invalid IL or missing references)
        //IL_042a: Unknown result type (might be due to invalid IL or missing references)
        //IL_070a: Unknown result type (might be due to invalid IL or missing references)
        //IL_072b: Unknown result type (might be due to invalid IL or missing references)
        //IL_073c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0741: Unknown result type (might be due to invalid IL or missing references)
        //IL_0746: Unknown result type (might be due to invalid IL or missing references)
        //IL_0794: Unknown result type (might be due to invalid IL or missing references)
        //IL_0796: Unknown result type (might be due to invalid IL or missing references)
        //IL_079b: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fd: Unknown result type (might be due to invalid IL or missing references)
        bool flag = true;
        float num = 7f;
        float num8 = 60f;
        float num9 = 60f;
        float num10 = 1f;
        float num11 = 0.96f;
        int num12 = 30;
        int num13 = 20;
        float num14 = 200f;
        int num15 = 40;
        int num2 = 438;
        float num3 = 10f;
        float num4 = 100f;
        bool flag2 = false;
        float num5 = 0.05f;
        Vector2 center = base.Center;
        NPCUtils.TargetClosestOldOnesInvasion(this);
        NPCAimedTarget targetData = GetTargetData();
        bool flag3 = false;
        if (type == 578)
        {
            num = 4f;
            num8 = 20f;
            num9 = 20f;
            flag3 = true;
            flag2 = true;
            num5 = 0.1f;
            num2 = 682;
            num15 = 50;
            num3 = 10f;
            num4 = 50f;
            num12 = 5;
            num13 = 30;
            center += new Vector2((float)(-spriteDirection * 20), 10f);
            position += netOffset;
            if (Main.rand.Next(15) == 0)
            {
                Vector2 vector = position;
                if (direction == -1)
                {
                    vector.X += width / 2;
                }
                Dust dust = Dust.NewDustDirect(vector, width / 2, height, 272);
                dust.scale = 0.65f;
                dust.velocity.Y -= 0.8f;
                if (dust.velocity.X * (float)direction > 0f)
                {
                    dust.velocity.X *= -1f;
                }
                if (dust.velocity.Y > 0f)
                {
                    dust.velocity *= -0.5f;
                }
            }
            if (Main.rand.Next(80) == 0)
            {
                Vector2 vector2 = (Main.rand.NextFloat() * ((float)Math.PI * 2f)).ToRotationVector2();
                Dust dust2 = Dust.NewDustPerfect(base.Center, 272, vector2);
                dust2.velocity *= 1.1f;
                dust2.noGravity = true;
                dust2.customData = this;
                Dust dust3 = Dust.NewDustPerfect(base.Center, 272, vector2);
                dust3.velocity *= 1.5f;
                dust3.noGravity = true;
                dust3.customData = this;
            }
            position -= netOffset;
        }
        if (flag3)
        {
            if (localAI[1] == 0f)
            {
                alpha = 255;
            }
            if (localAI[1] == 30f)
            {
                SoundEngine.PlayTrackedSound(in SoundID.DD2_EtherianPortalSpawnEnemy, base.Center);
            }
            if (localAI[1] < 60f)
            {
                localAI[1] += 1f;
                alpha -= 5;
                if (alpha < 0)
                {
                    alpha = 0;
                }
                int num6 = (int)localAI[1] / 10;
                Vector2 size = base.Size;
                float num7 = ((Vector2)(ref size)).Length() / 2f;
                num7 /= 20f;
                int maxValue = 5;
                if (type == 576 || type == 577)
                {
                    maxValue = 1;
                }
                for (int i = 0; i < num6; i++)
                {
                    if (Main.rand.Next(maxValue) == 0)
                    {
                        Dust dust4 = Dust.NewDustDirect(position, width, height, 27, velocity.X * 1f, 0f, 100);
                        dust4.scale = 0.55f;
                        dust4.fadeIn = 0.7f;
                        dust4.velocity *= 0.1f * num7;
                        dust4.velocity += velocity;
                    }
                }
            }
        }
        if (flag2)
        {
            for (int j = 0; j < 200; j++)
            {
                if (j != whoAmI && Main.npc[j].active && Main.npc[j].type == type && Math.Abs(position.X - Main.npc[j].position.X) + Math.Abs(position.Y - Main.npc[j].position.Y) < (float)width)
                {
                    if (position.X < Main.npc[j].position.X)
                    {
                        velocity.X -= num5;
                    }
                    else
                    {
                        velocity.X += num5;
                    }
                    if (position.Y < Main.npc[j].position.Y)
                    {
                        velocity.Y -= num5;
                    }
                    else
                    {
                        velocity.Y += num5;
                    }
                }
            }
        }
        rotation = Math.Abs(velocity.X) * (float)direction * 0.1f;
        spriteDirection = direction;
        Vector2 vector3 = center;
        Vector2 vector4 = targetData.Center - vector3;
        Vector2 vector5 = vector4.SafeNormalize(Vector2.UnitY) * num;
        bool flag4 = Collision.CanHit(base.Center, 1, 1, targetData.Center, 1, 1);
        if (localAI[0] < 0f)
        {
            localAI[0] += 1f;
        }
        if (!flag)
        {
            velocity = (velocity * (num8 - 1f) + vector5) / num8;
            EncourageDespawn(10);
        }
        else if (((Vector2)(ref vector4)).Length() > num14 || !flag4)
        {
            velocity = (velocity * (num9 - 1f) + vector5) / num9;
        }
        else if (vector4.Y < num4)
        {
            velocity.Y -= 0.03f;
        }
        else if (localAI[0] >= 0f)
        {
            velocity *= num11;
            if (((Vector2)(ref velocity)).Length() < num10 && Main.netMode != 1)
            {
                localAI[0] += 1f;
                if (localAI[0] >= (float)num12)
                {
                    localAI[0] = -num13;
                    direction = (spriteDirection = ((vector5.X > 0f) ? 1 : (-1)));
                    vector5 = vector4 + Utils.RandomVector2(Main.rand, -25f, 25f);
                    vector5.X *= 1f + (float)Main.rand.Next(-20, 21) * 0.005f;
                    vector5.Y *= 1f + (float)Main.rand.Next(-20, 21) * 0.005f;
                    vector5 = vector5.SafeNormalize(Vector2.UnitY) * num3;
                    vector5.X *= 1f + (float)Main.rand.Next(-20, 21) * (1f / 160f);
                    vector5.Y *= 1f + (float)Main.rand.Next(-20, 21) * (1f / 160f);
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector3, vector5, num2, num15, 0f, Main.myPlayer);
                }
            }
        }
        if (!flag)
        {
            return;
        }
        bool flag5 = false;
        if (targetData.Center.Y < base.Center.Y)
        {
            flag5 = true;
        }
        if (!flag5)
        {
            Point point = base.Center.ToTileCoordinates();
            if (WorldGen.InWorld(point.X, point.Y, 2))
            {
                Tile tile = Main.tile[point.X, point.Y];
                if (tile != null && tile.active() && WorldGen.SolidTile(tile))
                {
                    flag5 = true;
                }
            }
        }
        if (flag5)
        {
            velocity.Y -= 0.2f;
            if (velocity.Y < -10f)
            {
                velocity.Y = -10f;
            }
        }
    }
References Terraria.Entity.active, Terraria.Tile.active(), Terraria.NPC.alpha, Terraria.Collision.CanHit(), Terraria.ID.SoundID.DD2_EtherianPortalSpawnEnemy, Terraria.Entity.direction, Terraria.NPC.EncourageDespawn(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetTargetData(), Terraria.Entity.height, Terraria.WorldGen.InWorld(), Terraria.NPC.localAI, Terraria.Main.myPlayer, Terraria.NPC.netOffset, Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Utils.RandomVector2(), Terraria.NPC.rotation, Terraria.WorldGen.SolidTile(), Terraria.NPC.spriteDirection, Terraria.Utilities.NPCUtils.TargetClosestOldOnesInvasion(), Terraria.Main.tile, Terraria.NPC.type, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.NPC.VanillaAI_Inner().