TModLoader: Terraria.NPC.TransformElderSlime
TransformElderSlime()
static void Terraria.NPC.TransformElderSlime (int npcIndex) inline static
    {
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode == 1)
        {
            NetMessage.SendData(140, -1, -1, null, 2, npcIndex);
        }
        else if (!unlockedSlimeOldSpawn && Main.npc.IndexInRange(npcIndex))
        {
            NPC nPC = Main.npc[npcIndex];
            if (nPC.type == 685)
            {
                unlockedSlimeOldSpawn = true;
                NetMessage.SendData(7);
                Vector2 vector = nPC.velocity;
                nPC.Transform(679);
                nPC.netUpdate = true;
                nPC.velocity = vector;
                ParticleOrchestrator.BroadcastParticleSpawn(ParticleOrchestraType.TownSlimeTransform, new ParticleOrchestraSettings
                {
                    PositionInWorld = nPC.Center,
                    MovementVector = Vector2.Zero,
                    UniqueInfoPiece = 2
                });
            }
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastParticleSpawn(), Terraria.Main.netMode, Terraria.Main.npc, Terraria.NetMessage.SendData(), and Terraria.NPC.unlockedSlimeOldSpawn.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Main.HoverOverNPCs().