TModLoader: Terraria.NPC.AI_007_FindGoodRestingSpot
AI_007_FindGoodRestingSpot()
void Terraria.NPC.AI_007_FindGoodRestingSpot (int myTileX, int myTileY, out int floorX, out int floorY) inline private
Definition at line 56066 of file NPC.cs.
    {
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_00da: Unknown result type (might be due to invalid IL or missing references)
        //IL_0160: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_021b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_0238: Unknown result type (might be due to invalid IL or missing references)
        //IL_023d: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02de: Unknown result type (might be due to invalid IL or missing references)
        //IL_029b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_02af: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b9: Unknown result type (might be due to invalid IL or missing references)
        floorX = homeTileX;
        floorY = homeTileY;
        if (floorX == -1 || floorY == -1)
        {
            return;
        }
        while (!WorldGen.SolidOrSlopedTile(floorX, floorY) && floorY < Main.maxTilesY - 20)
        {
            floorY++;
        }
        if (Main.dayTime || (ai[0] == 5f && Math.Abs(myTileX - floorX) < 7 && Math.Abs(myTileY - floorY) < 7))
        {
            return;
        }
        Point point = default(Point);
        ((Point)(ref point))._002Ector(floorX, floorY);
        Point point2 = default(Point);
        ((Point)(ref point2))._002Ector(-1, -1);
        int num = -1;
        if (type == 638 || type == 656 || NPCID.Sets.IsTownSlime[type] || ai[0] == 5f)
        {
            return;
        }
        int num2 = 7;
        int num3 = 6;
        int num4 = 1;
        int num5 = 1;
        int num6 = 1;
        for (int i = point.X - num2; i <= point.X + num2; i += num5)
        {
            for (int num7 = point.Y + num4; num7 >= point.Y - num3; num7 -= num6)
            {
                Tile tile = Main.tile[i, num7];
                if (tile != null && tile.active() && TileID.Sets.CanBeSatOnForNPCs[tile.type])
                {
                    int num8 = Math.Abs(i - point.X) + Math.Abs(num7 - point.Y);
                    if (num == -1 || num8 < num)
                    {
                        num = num8;
                        point2.X = i;
                        point2.Y = num7;
                    }
                }
            }
        }
        if (num == -1)
        {
            return;
        }
        Tile tile2 = Main.tile[point2.X, point2.Y];
        if (tile2.type == 497 || tile2.type == 15)
        {
            if (tile2.frameY % 40 != 0)
            {
                point2.Y--;
            }
            point2.Y += 2;
        }
        else if (tile2.type >= TileID.Count)
        {
            TileRestingInfo info = new TileRestingInfo(this, point2, Vector2.Zero, direction);
            TileLoader.ModifySittingTargetInfo(point2.X, point2.Y, tile2.type, ref info);
            point2 = info.AnchorTilePosition;
            point2.Y++;
        }
        for (int j = 0; j < 200; j++)
        {
            if (Main.npc[j].active && Main.npc[j].aiStyle == 7 && Main.npc[j].townNPC && Main.npc[j].ai[0] == 5f && (Main.npc[j].Bottom + Vector2.UnitY * -2f).ToTileCoordinates() == point2)
            {
                return;
            }
        }
        floorX = point2.X;
        floorY = point2.Y;
    }
References Terraria.Tile.active(), Terraria.NPC.ai, Terraria.ID.TileID.Sets.CanBeSatOnForNPCs, Terraria.ID.TileID.Count, Terraria.Main.dayTime, Terraria.Entity.direction, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Terraria.ID.NPCID.Sets.IsTownSlime, Terraria.Main.maxTilesY, Terraria.ModLoader.TileLoader.ModifySittingTargetInfo(), Terraria.Main.npc, Terraria.WorldGen.SolidOrSlopedTile(), Terraria.Main.tile, Terraria.NPC.type, and Terraria.Tile.type.
Referenced by Terraria.NPC.AI_007_TownEntities().