TModLoader: Terraria.NPC.AI_121_QueenSlime
AI_121_QueenSlime()
void Terraria.NPC.AI_121_QueenSlime () inline private
Definition at line 45955 of file NPC.cs.
    {
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0534: Unknown result type (might be due to invalid IL or missing references)
        //IL_0547: Unknown result type (might be due to invalid IL or missing references)
        //IL_0556: Unknown result type (might be due to invalid IL or missing references)
        //IL_056c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0201: Unknown result type (might be due to invalid IL or missing references)
        //IL_0206: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b30: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b35: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a20: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a90: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b78: Unknown result type (might be due to invalid IL or missing references)
        //IL_1496: Unknown result type (might be due to invalid IL or missing references)
        //IL_149b: Unknown result type (might be due to invalid IL or missing references)
        //IL_18f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bda: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1092: Unknown result type (might be due to invalid IL or missing references)
        //IL_101a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1026: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0502: Unknown result type (might be due to invalid IL or missing references)
        //IL_050b: Unknown result type (might be due to invalid IL or missing references)
        //IL_051a: Unknown result type (might be due to invalid IL or missing references)
        //IL_028e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1503: Unknown result type (might be due to invalid IL or missing references)
        //IL_1506: Unknown result type (might be due to invalid IL or missing references)
        //IL_150b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1510: Unknown result type (might be due to invalid IL or missing references)
        //IL_1517: Unknown result type (might be due to invalid IL or missing references)
        //IL_151c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1521: Unknown result type (might be due to invalid IL or missing references)
        //IL_1526: Unknown result type (might be due to invalid IL or missing references)
        //IL_152d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1537: Unknown result type (might be due to invalid IL or missing references)
        //IL_153c: Unknown result type (might be due to invalid IL or missing references)
        //IL_14b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_14bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1043: Unknown result type (might be due to invalid IL or missing references)
        //IL_1744: Unknown result type (might be due to invalid IL or missing references)
        //IL_1752: Unknown result type (might be due to invalid IL or missing references)
        //IL_1757: Unknown result type (might be due to invalid IL or missing references)
        //IL_175c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0307: Unknown result type (might be due to invalid IL or missing references)
        //IL_02da: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bfb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c05: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_14de: Unknown result type (might be due to invalid IL or missing references)
        //IL_177a: Unknown result type (might be due to invalid IL or missing references)
        //IL_177d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1782: Unknown result type (might be due to invalid IL or missing references)
        //IL_1787: Unknown result type (might be due to invalid IL or missing references)
        //IL_1789: Unknown result type (might be due to invalid IL or missing references)
        //IL_178b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1790: Unknown result type (might be due to invalid IL or missing references)
        //IL_179a: Unknown result type (might be due to invalid IL or missing references)
        //IL_179f: Unknown result type (might be due to invalid IL or missing references)
        //IL_17a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_17a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_17ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_17b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_17ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_1801: Unknown result type (might be due to invalid IL or missing references)
        //IL_1762: Unknown result type (might be due to invalid IL or missing references)
        //IL_176e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1773: Unknown result type (might be due to invalid IL or missing references)
        //IL_1778: Unknown result type (might be due to invalid IL or missing references)
        //IL_0315: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_11b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_11de: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1203: Unknown result type (might be due to invalid IL or missing references)
        //IL_121c: Unknown result type (might be due to invalid IL or missing references)
        //IL_121e: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_10fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1102: Unknown result type (might be due to invalid IL or missing references)
        //IL_1129: Unknown result type (might be due to invalid IL or missing references)
        //IL_1607: Unknown result type (might be due to invalid IL or missing references)
        //IL_1618: Unknown result type (might be due to invalid IL or missing references)
        //IL_161d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1622: Unknown result type (might be due to invalid IL or missing references)
        //IL_162b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1636: Unknown result type (might be due to invalid IL or missing references)
        //IL_1640: Unknown result type (might be due to invalid IL or missing references)
        //IL_1647: Unknown result type (might be due to invalid IL or missing references)
        //IL_0323: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0331: Unknown result type (might be due to invalid IL or missing references)
        //IL_047f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0492: Unknown result type (might be due to invalid IL or missing references)
        //IL_0897: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bb: Unknown result type (might be due to invalid IL or missing references)
        int num = 30;
        int num11 = 40;
        _ = Main.expertMode;
        float num22 = 1f;
        bool flag = false;
        bool flag2 = life <= lifeMax / 2;
        if (localAI[0] == 0f)
        {
            ai[1] = -100f;
            localAI[0] = lifeMax;
            TargetClosest();
            netUpdate = true;
        }
        Lighting.AddLight(base.Center, 1f, 0.7f, 0.9f);
        int num27 = 500;
        if (Main.player[target].dead || Math.Abs(base.Center.X - Main.player[target].Center.X) / 16f > (float)num27)
        {
            TargetClosest();
            if (Main.player[target].dead || Math.Abs(base.Center.X - Main.player[target].Center.X) / 16f > (float)num27)
            {
                EncourageDespawn(10);
                if (Main.player[target].Center.X < base.Center.X)
                {
                    direction = 1;
                }
                else
                {
                    direction = -1;
                }
            }
        }
        if (!Main.player[target].dead && timeLeft > 10 && !flag2 && ai[3] >= 300f && ai[0] == 0f && velocity.Y == 0f)
        {
            ai[0] = 2f;
            ai[1] = 0f;
            if (Main.netMode != 1)
            {
                netUpdate = true;
                TargetClosest(faceTarget: false);
                Point point = base.Center.ToTileCoordinates();
                Point point2 = Main.player[target].Center.ToTileCoordinates();
                Vector2 vector = Main.player[target].Center - base.Center;
                int num28 = 10;
                int num29 = 0;
                int num30 = 7;
                int num31 = 0;
                bool flag3 = false;
                if (ai[3] >= 360f || ((Vector2)(ref vector)).Length() > 2000f)
                {
                    if (ai[3] > 360f)
                    {
                        ai[3] = 360f;
                    }
                    flag3 = true;
                    num31 = 100;
                }
                while (!flag3 && num31 < 100)
                {
                    num31++;
                    int num32 = Main.rand.Next(point2.X - num28, point2.X + num28 + 1);
                    int num2 = Main.rand.Next(point2.Y - num28, point2.Y + 1);
                    if ((num2 >= point2.Y - num30 && num2 <= point2.Y + num30 && num32 >= point2.X - num30 && num32 <= point2.X + num30) || (num2 >= point.Y - num29 && num2 <= point.Y + num29 && num32 >= point.X - num29 && num32 <= point.X + num29) || Main.tile[num32, num2].nactive())
                    {
                        continue;
                    }
                    int num3 = num2;
                    int i = 0;
                    if (Main.tile[num32, num3].nactive() && Main.tileSolid[Main.tile[num32, num3].type] && !Main.tileSolidTop[Main.tile[num32, num3].type])
                    {
                        i = 1;
                    }
                    else
                    {
                        for (; i < 150 && num3 + i < Main.maxTilesY; i++)
{
                            int num4 = num3 + i;
                            if (Main.tile[num32, num4].nactive() && Main.tileSolid[Main.tile[num32, num4].type] && !Main.tileSolidTop[Main.tile[num32, num4].type])
{
                                i--;
                                break;
                            }
                        }
                    }
                    num2 += i;
                    bool flag4 = true;
                    if (flag4 && Main.tile[num32, num2].lava())
                    {
                        flag4 = false;
                    }
                    if (flag4 && !Collision.CanHitLine(base.Center, 0, 0, Main.player[target].Center, 0, 0))
                    {
                        flag4 = false;
                    }
                    if (flag4)
                    {
                        localAI[1] = num32 * 16 + 8;
                        localAI[2] = num2 * 16 + 16;
                        flag3 = true;
                        break;
                    }
                }
                if (num31 >= 100)
                {
                    Vector2 bottom = Main.player[Player.FindClosest(position, width, height)].Bottom;
                    localAI[1] = bottom.X;
                    localAI[2] = bottom.Y;
                    ai[3] = 0f;
                }
            }
        }
        if (!flag2 && (!Collision.CanHitLine(base.Center, 0, 0, Main.player[target].Center, 0, 0) || Math.Abs(base.Top.Y - Main.player[target].Bottom.Y) > 320f))
        {
            ai[3] += 1.5f;
        }
        else
        {
            float num5 = ai[3];
            ai[3] -= 1f;
            if (ai[3] < 0f)
            {
                if (Main.netMode != 1 && num5 > 0f)
                {
                    netUpdate = true;
                }
                ai[3] = 0f;
            }
        }
        if (timeLeft <= 10 && ((flag2 && ai[0] != 0f) || (!flag2 && ai[0] != 3f)))
        {
            if (flag2)
            {
                ai[0] = 0f;
            }
            else
            {
                ai[0] = 3f;
            }
            ai[1] = 0f;
            ai[2] = 0f;
            ai[3] = 0f;
            netUpdate = true;
        }
        noTileCollide = false;
        noGravity = false;
        if (flag2)
        {
            localAI[3] += 1f;
            if (localAI[3] >= 24f)
            {
                localAI[3] = 0f;
            }
            if (ai[0] == 4f && ai[2] == 1f)
            {
                localAI[3] = 6f;
            }
            if (ai[0] == 5f && ai[2] != 1f)
            {
                localAI[3] = 7f;
            }
        }
        switch ((int)ai[0])
        {
        case 0:
        {
            if (flag2)
            {
                AI_121_QueenSlime_FlyMovement();
            }
            else
            {
                noTileCollide = false;
                noGravity = false;
                if (velocity.Y == 0f)
                {
                    velocity.X *= 0.8f;
                    if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
                    {
                        velocity.X = 0f;
                    }
                }
            }
            if (timeLeft <= 10 || (!flag2 && velocity.Y != 0f))
            {
                break;
            }
            ai[1] += 1f;
            int num10 = 60;
            if (flag2)
            {
                num10 = 120;
            }
            if (!(ai[1] > (float)num10))
            {
                break;
            }
            ai[1] = 0f;
            if (flag2)
            {
                Player player = Main.player[target];
                if (Main.rand.Next(2) != 1)
                {
                    ai[0] = 4f;
                }
                else
                {
                    ai[0] = 5f;
                }
                if (ai[0] == 4f)
                {
                    ai[2] = 1f;
                    if (player != null && player.active && !player.dead && (player.Bottom.Y < base.Bottom.Y || Math.Abs(player.Center.X - base.Center.X) > 250f))
                    {
                        ai[0] = 5f;
                        ai[2] = 0f;
                    }
                }
            }
            else
            {
                switch (Main.rand.Next(3))
                {
                default:
                    ai[0] = 3f;
                    break;
                case 1:
                    ai[0] = 4f;
                    break;
                case 2:
                    ai[0] = 5f;
                    break;
                }
            }
            netUpdate = true;
            break;
        }
        case 1:
        {
            rotation = 0f;
            ai[1] += 1f;
            num22 = MathHelper.Clamp(ai[1] / 30f, 0f, 1f);
            num22 = 0.5f + num22 * 0.5f;
            if (ai[1] >= 30f && Main.netMode != 1)
            {
                ai[0] = 0f;
                ai[1] = 0f;
                netUpdate = true;
                TargetClosest();
            }
            if (Main.netMode == 1 && ai[1] >= 60f)
            {
                ai[0] = 0f;
                ai[1] = 0f;
                TargetClosest();
            }
            Color newColor2 = AI_121_QueenSlime_GetDustColor();
            ((Color)(ref newColor2)).A = 150;
            for (int num19 = 0; num19 < 10; num19++)
            {
                int num20 = Dust.NewDust(position + Vector2.UnitX * -20f, width + 40, height, 4, velocity.X, velocity.Y, 50, newColor2, 1.5f);
                Main.dust[num20].noGravity = true;
                Dust obj2 = Main.dust[num20];
                obj2.velocity *= 2f;
            }
            break;
        }
        case 2:
            rotation = 0f;
            ai[1] += 1f;
            num22 = MathHelper.Clamp((60f - ai[1]) / 60f, 0f, 1f);
            num22 = 0.5f + num22 * 0.5f;
            if (ai[1] >= 60f)
            {
                flag = true;
            }
            if (ai[1] == 60f)
            {
                Gore.NewGore(base.Center + new Vector2(-40f, (float)(-height / 2)), velocity, 1258);
            }
            if (ai[1] >= 60f && Main.netMode != 1)
            {
                base.Bottom = new Vector2(localAI[1], localAI[2]);
                ai[0] = 1f;
                ai[1] = 0f;
                netUpdate = true;
            }
            if (Main.netMode == 1 && ai[1] >= 120f)
            {
                ai[0] = 1f;
                ai[1] = 0f;
            }
            if (!flag)
            {
                Color newColor = AI_121_QueenSlime_GetDustColor();
                ((Color)(ref newColor)).A = 150;
                for (int n = 0; n < 10; n++)
                {
                    int num18 = Dust.NewDust(position + Vector2.UnitX * -20f, width + 40, height, 4, velocity.X, velocity.Y, 50, newColor, 1.5f);
                    Main.dust[num18].noGravity = true;
                    Dust obj = Main.dust[num18];
                    obj.velocity *= 0.5f;
                }
            }
            break;
        case 3:
            rotation = 0f;
            if (velocity.Y == 0f)
            {
                velocity.X *= 0.8f;
                if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
                {
                    velocity.X = 0f;
                }
                ai[1] += 4f;
                if ((double)life < (double)lifeMax * 0.66)
                {
                    ai[1] += 4f;
                }
                if ((double)life < (double)lifeMax * 0.33)
                {
                    ai[1] += 4f;
                }
                if (!(ai[1] >= 0f))
                {
                    break;
                }
                netUpdate = true;
                TargetClosest();
                if (ai[2] == 3f)
                {
                    velocity.Y = -13f;
                    velocity.X += 3.5f * (float)direction;
                    ai[1] = 0f;
                    ai[2] = 0f;
                    if (timeLeft > 10)
                    {
                        ai[0] = 0f;
                    }
                    else
                    {
                        ai[1] = -60f;
                    }
                }
                else if (ai[2] == 2f)
                {
                    velocity.Y = -6f;
                    velocity.X += 4.5f * (float)direction;
                    ai[1] = -40f;
                    ai[2] += 1f;
                }
                else
                {
                    velocity.Y = -8f;
                    velocity.X += 4f * (float)direction;
                    ai[1] = -40f;
                    ai[2] += 1f;
                }
            }
            else
            {
                if (target >= 255)
                {
                    break;
                }
                float num12 = 3f;
                if (Main.getGoodWorld)
                {
                    num12 = 7f;
                }
                if ((direction == 1 && velocity.X < num12) || (direction == -1 && velocity.X > 0f - num12))
                {
                    if ((direction == -1 && (double)velocity.X < 0.1) || (direction == 1 && (double)velocity.X > -0.1))
                    {
                        velocity.X += 0.2f * (float)direction;
                    }
                    else
                    {
                        velocity.X *= 0.93f;
                    }
                }
            }
            break;
        case 4:
        {
            rotation *= 0.9f;
            noTileCollide = true;
            noGravity = true;
            if (ai[2] == 1f)
            {
                noTileCollide = false;
                noGravity = false;
                int num13 = 30;
                if (flag2)
                {
                    num13 = 10;
                }
                if (Main.getGoodWorld)
                {
                    num13 = 0;
                }
                Player player2 = Main.player[target];
                _ = base.Center;
                if (!player2.dead && player2.active && Math.Abs(base.Center.X - player2.Center.X) / 16f <= (float)num27)
                {
                    _ = player2.Center;
                }
                if (velocity.Y == 0f)
                {
                    ai[0] = 0f;
                    ai[1] = 0f;
                    ai[2] = 0f;
                    netUpdate = true;
                    SoundEngine.PlaySound(in SoundID.Item167, base.Center);
                    if (Main.netMode != 1)
                    {
                        Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Bottom, Vector2.Zero, 922, num11, 0f, Main.myPlayer);
                    }
                    for (int l = 0; l < 20; l++)
                    {
                        int num14 = Dust.NewDust(base.Bottom - new Vector2((float)(width / 2), 30f), width, 30, 31, velocity.X, velocity.Y, 40, AI_121_QueenSlime_GetDustColor());
                        Main.dust[num14].noGravity = true;
                        Main.dust[num14].velocity.Y = -5f + Main.rand.NextFloat() * -3f;
                        Main.dust[num14].velocity.X *= 7f;
                    }
                }
                else if (ai[1] >= (float)num13)
                {
                    for (int m = 0; m < 4; m++)
                    {
                        Vector2 vector3 = base.Bottom - new Vector2(Main.rand.NextFloatDirection() * 16f, (float)Main.rand.Next(8));
                        int num15 = Dust.NewDust(vector3, 2, 2, 31, velocity.X, velocity.Y, 40, AI_121_QueenSlime_GetDustColor(), 1.4f);
                        Main.dust[num15].position = vector3;
                        Main.dust[num15].noGravity = true;
                        Main.dust[num15].velocity.Y = velocity.Y * 0.9f;
                        Main.dust[num15].velocity.X = ((Main.rand.Next(2) == 0) ? (-10f) : 10f) + Main.rand.NextFloatDirection() * 3f;
                    }
                }
                velocity.X *= 0.8f;
                float num16 = ai[1];
                ai[1] += 1f;
                if (ai[1] >= (float)num13)
                {
                    if (num16 < (float)num13)
                    {
                        netUpdate = true;
                    }
                    if (flag2 && ai[1] > (float)(num13 + 120))
                    {
                        ai[0] = 0f;
                        ai[1] = 0f;
                        ai[2] = 0f;
                        velocity.Y *= 0.8f;
                        netUpdate = true;
                        break;
                    }
                    velocity.Y += 1f;
                    float num17 = 14f;
                    if (Main.getGoodWorld)
                    {
                        velocity.Y += 1f;
                        num17 = 15.99f;
                    }
                    if (velocity.Y == 0f)
                    {
                        velocity.Y = 0.01f;
                    }
                    if (velocity.Y >= num17)
                    {
                        velocity.Y = num17;
                    }
                }
                else
                {
                    velocity.Y *= 0.8f;
                }
                break;
            }
            if (Main.netMode != 1 && ai[1] == 0f)
            {
                TargetClosest();
                netUpdate = true;
            }
            ai[1] += 1f;
            if (!(ai[1] >= 30f))
            {
                break;
            }
            if (ai[1] >= 60f)
            {
                ai[1] = 60f;
                if (Main.netMode != 1)
                {
                    ai[1] = 0f;
                    ai[2] = 1f;
                    velocity.Y = -3f;
                    netUpdate = true;
                }
            }
            Player player3 = Main.player[target];
            Vector2 center = base.Center;
            if (!player3.dead && player3.active && Math.Abs(base.Center.X - player3.Center.X) / 16f <= (float)num27)
            {
                center = player3.Center;
            }
            center.Y -= 384f;
            if (velocity.Y == 0f)
            {
                velocity = center - base.Center;
                velocity = velocity.SafeNormalize(Vector2.Zero);
                velocity *= 20f;
            }
            else
            {
                velocity.Y *= 0.95f;
            }
            break;
        }
        case 5:
        {
            rotation *= 0.9f;
            noTileCollide = true;
            noGravity = true;
            if (flag2)
            {
                ai[3] = 0f;
            }
            if (ai[2] == 1f)
            {
                ai[1] += 1f;
                if (!(ai[1] >= 10f))
                {
                    break;
                }
                if (Main.netMode != 1)
                {
                    int num6 = 10;
                    if (Main.getGoodWorld)
                    {
                        num6 = 15;
                    }
                    int num7 = num6;
                    if (!flag2)
                    {
                        num7 = 6;
                    }
                    Vector2 spinningpoint = default(Vector2);
                    for (int j = 0; j < num7; j++)
                    {
                        ((Vector2)(ref spinningpoint))._002Ector(9f, 0f);
                        spinningpoint = spinningpoint.RotatedBy((float)(-j) * ((float)Math.PI * 2f) / (float)num6, Vector2.Zero);
                        Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, spinningpoint.X, spinningpoint.Y, 926, num, 0f, Main.myPlayer);
                    }
                }
                ai[0] = 0f;
                ai[1] = 0f;
                ai[2] = 0f;
                netUpdate = true;
                break;
            }
            if (Main.netMode != 1 && ai[1] == 0f)
            {
                TargetClosest();
                netUpdate = true;
            }
            ai[1] += 1f;
            if (ai[1] >= 50f)
            {
                ai[1] = 50f;
                if (Main.netMode != 1)
                {
                    ai[1] = 0f;
                    ai[2] = 1f;
                    netUpdate = true;
                }
            }
            float num8 = 100f;
            for (int k = 0; k < 4; k++)
            {
                Vector2 vector2 = base.Center + Main.rand.NextVector2CircularEdge(num8, num8);
                if (!flag2)
                {
                    vector2 += new Vector2(0f, 20f);
                }
                Vector2 v = vector2 - base.Center;
                v = v.SafeNormalize(Vector2.Zero) * -8f;
                int num9 = Dust.NewDust(vector2, 2, 2, 31, v.X, v.Y, 40, AI_121_QueenSlime_GetDustColor(), 1.8f);
                Main.dust[num9].position = vector2;
                Main.dust[num9].noGravity = true;
                Main.dust[num9].alpha = 250;
                Main.dust[num9].velocity = v;
                Main.dust[num9].customData = this;
            }
            if (flag2)
            {
                AI_121_QueenSlime_FlyMovement();
            }
            break;
        }
        }
        dontTakeDamage = (hide = flag);
        if (num22 != scale)
        {
            position.X += width / 2;
            position.Y += height;
            scale = num22;
            width = (int)(114f * scale);
            height = (int)(100f * scale);
            position.X -= width / 2;
            position.Y -= height;
        }
        if (life <= 0)
        {
            return;
        }
        if (Main.rand.Next(360) == 0)
        {
            SoundEngine.PlaySound(65, position);
        }
        if (Main.netMode == 1)
        {
            return;
        }
        if (localAI[0] >= (float)(lifeMax / 2) && life < lifeMax / 2)
        {
            localAI[0] = life;
            ai[0] = 0f;
            ai[1] = 0f;
            ai[2] = 0f;
            netUpdate = true;
        }
        int num21 = (int)((float)lifeMax * 0.02f);
        if (flag2)
        {
            num21 = (int)((float)lifeMax * 0.015f);
        }
        if (!((float)(life + num21) < localAI[0]))
        {
            return;
        }
        localAI[0] = life;
        int num23 = Main.rand.Next(1, 3);
        for (int num24 = 0; num24 < num23; num24++)
        {
            int x = (int)(position.X + (float)Main.rand.Next(width - 32));
            int y = (int)(position.Y + (float)Main.rand.Next(height - 32));
            int num25 = 658;
            switch (Main.rand.Next(3))
            {
            case 0:
                num25 = 658;
                break;
            case 1:
                num25 = 659;
                break;
            case 2:
                num25 = 660;
                break;
            }
            int num26 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), x, y, num25);
            Main.npc[num26].SetDefaults(num25);
            Main.npc[num26].velocity.X = (float)Main.rand.Next(-15, 16) * 0.1f;
            Main.npc[num26].velocity.Y = (float)Main.rand.Next(-30, 1) * 0.1f;
            Main.npc[num26].ai[0] = -500 * Main.rand.Next(3);
            Main.npc[num26].ai[1] = 0f;
            if (Main.netMode == 2 && num26 < 200)
            {
                NetMessage.SendData(23, -1, -1, null, num26);
            }
        }
    }
References Terraria.Entity.active, Terraria.Lighting.AddLight(), Terraria.NPC.ai, Terraria.NPC.AI_121_QueenSlime_FlyMovement(), Terraria.NPC.AI_121_QueenSlime_GetDustColor(), Terraria.Entity.Bottom, Terraria.Collision.CanHitLine(), Terraria.Entity.Center, Terraria.Player.dead, Terraria.Entity.direction, Terraria.NPC.dontTakeDamage, Terraria.Main.dust, Terraria.NPC.EncourageDespawn(), Terraria.Main.expertMode, Terraria.Player.FindClosest(), Terraria.Main.getGoodWorld, Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.Entity.height, Terraria.NPC.hide, Terraria.ID.SoundID.Item167, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Main.maxTilesY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.NPC.noGravity, Terraria.NPC.noTileCollide, Terraria.Main.npc, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.rotation, Terraria.NPC.scale, Terraria.NetMessage.SendData(), Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.NPC.timeLeft, Terraria.Entity.velocity, and Terraria.Entity.width.
Referenced by Terraria.NPC.VanillaAI_Inner().