TModLoader: Terraria.NPC.Transform
Transform()
void Terraria.NPC.Transform (int newType) inline
Definition at line 91590 of file NPC.cs.
    {
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode != 1)
        {
            int num = extraValue;
            bool flag = false;
            if (value == 0f)
            {
                flag = true;
            }
            int[] array = new int[maxBuffs];
            int[] array2 = new int[maxBuffs];
            for (int i = 0; i < maxBuffs; i++)
            {
                array[i] = buffType[i];
                array2[i] = buffTime[i];
            }
            float num2 = shimmerTransparency;
            _ = height;
            int oldType = type;
            int num3 = life;
            int num4 = lifeMax;
            Vector2 vector = velocity;
            position.Y += height;
            int num5 = spriteDirection;
            bool spawnedFromStatue = SpawnedFromStatue;
            SetDefaultsKeepPlayerInteraction(newType);
            SpawnedFromStatue = spawnedFromStatue;
            spriteDirection = num5;
            TargetClosest();
            velocity = vector;
            position.Y -= height;
            for (int j = 0; j < maxBuffs; j++)
            {
                buffType[j] = array[j];
                buffTime[j] = array2[j];
            }
            if (flag)
            {
                value = 0f;
            }
            if (lifeMax == num4)
            {
                life = num3;
            }
            shimmerTransparency = num2;
            switch (newType)
            {
            case 107:
            case 108:
            case 124:
            case 353:
            case 369:
            case 550:
            case 588:
            case 679:
            case 680:
            case 683:
            case 684:
                UpdateHomeTileState(homeless: true, (int)(position.X + (float)(width / 2)) / 16, (int)(position.Y + (float)height) / 16);
                break;
            }
            extraValue = num;
            if (Main.netMode == 2)
            {
                netUpdate = true;
                NetMessage.SendData(23, -1, -1, null, whoAmI);
                NetMessage.SendData(54, -1, -1, null, whoAmI);
            }
            TransformVisuals(oldType, newType);
            GiveTownUniqueDataToNPCsThatNeedIt(type, whoAmI);
            if (townNPC)
            {
                homeless = true;
                WorldGen.CheckAchievement_RealEstateAndTownSlimes();
            }
            altTexture = 0;
        }
    }
References Terraria.WorldGen.CheckAchievement_RealEstateAndTownSlimes(), Terraria.Main.netMode, and Terraria.NetMessage.SendData().
Referenced by Terraria.NPC.AI_000_TransformBoundNPC(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_007_TownEntities(), and Terraria.NPC.VanillaAI_Inner().