TModLoader: Terraria.NPC.SlimeRainSpawns
SlimeRainSpawns()
static void Terraria.NPC.SlimeRainSpawns (int plr) inline static
    {
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        int logicCheckScreenHeight = Main.LogicCheckScreenHeight;
        int logicCheckScreenWidth = Main.LogicCheckScreenWidth;
        float num = 15f;
        Player player = Main.player[plr];
        if ((double)player.position.Y > Main.worldSurface * 16.0 + (double)(logicCheckScreenHeight / 2) || player.nearbyActiveNPCs > num)
        {
            return;
        }
        float num2 = player.nearbyActiveNPCs / num;
        int num3 = 45 + (int)(450f * num2);
        if (Main.expertMode)
        {
            num3 = (int)((double)num3 * 0.85);
        }
        if (Main.GameModeInfo.IsJourneyMode)
        {
            CreativePowers.SpawnRateSliderPerPlayerPower power = CreativePowerManager.Instance.GetPower<CreativePowers.SpawnRateSliderPerPlayerPower>();
            if (power != null && power.GetIsUnlocked())
            {
                if (power.GetShouldDisableSpawnsFor(plr))
                {
                    return;
                }
                if (power.GetRemappedSliderValueFor(plr, out var num4))
                {
                    num3 = (int)((float)num3 / num4);
                }
            }
        }
        if (Main.rand.Next(num3) != 0)
        {
            return;
        }
        int num5 = (int)(player.Center.X - (float)logicCheckScreenWidth);
        int maxValue = num5 + logicCheckScreenWidth * 2;
        int minValue = (int)((double)player.Center.Y - (double)logicCheckScreenHeight * 1.5);
        int maxValue2 = (int)((double)player.Center.Y - (double)logicCheckScreenHeight * 0.75);
        int num6 = Main.rand.Next(num5, maxValue);
        int num7 = Main.rand.Next(minValue, maxValue2);
        num6 /= 16;
        num7 /= 16;
        if (num6 < 10 || num6 > Main.maxTilesX + 10 || (double)num7 < Main.worldSurface * 0.3 || (double)num7 > Main.worldSurface || Collision.SolidTiles(num6 - 3, num6 + 3, num7 - 5, num7 + 2) || Main.wallHouse[Main.tile[num6, num7].wall])
        {
            return;
        }
        int num8 = NewNPC(GetSpawnSourceForNaturalSpawn(), num6 * 16 + 8, num7 * 16, 1);
        if (Main.rand.Next(200) == 0)
        {
            Main.npc[num8].SetDefaults(-4);
        }
        else if (Main.expertMode)
        {
            if (Main.rand.Next(7) == 0)
            {
                Main.npc[num8].SetDefaults(-7);
            }
            else if (Main.rand.Next(3) == 0)
            {
                Main.npc[num8].SetDefaults(-3);
            }
        }
        else if (Main.rand.Next(10) == 0)
        {
            Main.npc[num8].SetDefaults(-7);
        }
        else if (Main.rand.Next(5) < 2)
        {
            Main.npc[num8].SetDefaults(-3);
        }
    }
References Terraria.Entity.Center, Terraria.Main.expertMode, Terraria.Main.GameModeInfo, Terraria.GameContent.Creative.CreativePowerManager.Instance, Terraria.DataStructures.GameModeData.IsJourneyMode, Terraria.Main.LogicCheckScreenHeight, Terraria.Main.LogicCheckScreenWidth, Terraria.Main.maxTilesX, Terraria.Player.nearbyActiveNPCs, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.SetDefaults(), Terraria.Collision.SolidTiles(), Terraria.Main.tile, Terraria.Main.wallHouse, and Terraria.Main.worldSurface.