TModLoader: Terraria.NPC.ReflectProjectile
ReflectProjectile()
void Terraria.NPC.ReflectProjectile (Projectile proj) inline
    {
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        SoundEngine.PlaySound(in SoundID.Item150, proj.position);
        for (int i = 0; i < 3; i++)
        {
            int num = Dust.NewDust(proj.position, proj.width, proj.height, 31);
            Dust obj = Main.dust[num];
            obj.velocity *= 0.3f;
        }
        proj.reflected = true;
        proj.hostile = true;
        proj.friendly = false;
        Vector2 vector = Main.player[proj.owner].Center - proj.Center;
        ((Vector2)(ref vector)).Normalize();
        vector *= ((Vector2)(ref proj.oldVelocity)).Length();
        proj.velocity = new Vector2((float)Main.rand.Next(-100, 101), (float)Main.rand.Next(-100, 101));
        ((Vector2)(ref proj.velocity)).Normalize();
        proj.velocity *= ((Vector2)(ref vector)).Length();
        proj.velocity += vector * 20f;
        ((Vector2)(ref proj.velocity)).Normalize();
        proj.velocity *= ((Vector2)(ref vector)).Length();
        proj.damage /= 2;
        proj.damage /= 2;
        proj.penetrate = 1;
    }
References Terraria.Main.dust, Terraria.ID.SoundID.Item150, Terraria.Dust.NewDust(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.rand.
Referenced by Terraria.NPC.ReflectProjectiles().