TModLoader: Terraria.NPC.UpdateNPC_TeleportVisuals
UpdateNPC_TeleportVisuals()
void Terraria.NPC.UpdateNPC_TeleportVisuals () inline private
    {
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0145: Unknown result type (might be due to invalid IL or missing references)
        //IL_0158: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        if (!(teleportTime > 0f))
        {
            return;
        }
        if (teleportStyle == 0)
        {
            if ((float)Main.rand.Next(100) <= 100f * teleportTime * 2f)
            {
                int num = Dust.NewDust(new Vector2((float)getRect().X, (float)getRect().Y), getRect().Width, getRect().Height, 159);
                Main.dust[num].scale = teleportTime * 1.5f;
                Main.dust[num].noGravity = true;
                Dust obj = Main.dust[num];
                obj.velocity *= 1.1f;
            }
        }
        else if (teleportStyle == 4)
        {
            teleportTime -= 0.02f;
            if ((float)Main.rand.Next(100) <= 100f * teleportTime)
            {
                Dust obj2 = Main.dust[Dust.NewDust(position, width, height, 263)];
                obj2.color = PortalHelper.GetPortalColor(lastPortalColorIndex);
                obj2.noLight = true;
                obj2.noGravity = true;
                obj2.scale = 1.2f;
                obj2.fadeIn = 0.4f;
            }
        }
        else if (teleportStyle == 12)
        {
            teleportTime -= 0.02f;
            if ((float)Main.rand.Next(100) <= 100f * teleportTime)
            {
                Dust obj3 = Main.dust[Dust.NewDust(position, width, height, 263)];
                obj3.color = Main.hslToRgb((float)(Main.timeForVisualEffects / 60.0) % 1f, 1f, 0.75f, 0);
                obj3.noLight = true;
                obj3.noGravity = true;
                obj3.scale = 1.2f;
                obj3.fadeIn = 0.4f;
            }
        }
        else if (teleportStyle == 13)
        {
            teleportTime = 0f;
        }
        teleportTime = Math.Max(0f, teleportTime - 0.005f);
    }
References Terraria.Main.dust, Terraria.GameContent.PortalHelper.GetPortalColor(), Terraria.Main.hslToRgb(), Terraria.Dust.NewDust(), Terraria.Main.rand, and Terraria.Main.timeForVisualEffects.