TModLoader: Terraria.NPC.AI_005_EaterOfSouls
AI_005_EaterOfSouls()
void Terraria.NPC.AI_005_EaterOfSouls () inline private
    {
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_066d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0684: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_026c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0272: Unknown result type (might be due to invalid IL or missing references)
        //IL_0277: Unknown result type (might be due to invalid IL or missing references)
        //IL_027c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0176: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_023d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0243: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_0257: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0adc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0afb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b03: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b12: Unknown result type (might be due to invalid IL or missing references)
        //IL_129f: Unknown result type (might be due to invalid IL or missing references)
        //IL_12a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_12aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_12af: Unknown result type (might be due to invalid IL or missing references)
        //IL_12c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_12fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_1300: Unknown result type (might be due to invalid IL or missing references)
        //IL_1317: Unknown result type (might be due to invalid IL or missing references)
        //IL_1321: Unknown result type (might be due to invalid IL or missing references)
        //IL_1326: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e52: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e59: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e60: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e45: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_147b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1481: Unknown result type (might be due to invalid IL or missing references)
        //IL_1486: Unknown result type (might be due to invalid IL or missing references)
        //IL_148b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1711: Unknown result type (might be due to invalid IL or missing references)
        //IL_14da: Unknown result type (might be due to invalid IL or missing references)
        //IL_1507: Unknown result type (might be due to invalid IL or missing references)
        //IL_150d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1403: Unknown result type (might be due to invalid IL or missing references)
        //IL_1431: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a99: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1aa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1aa3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1aa8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1aad: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ad1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ad6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1875: Unknown result type (might be due to invalid IL or missing references)
        //IL_187f: Unknown result type (might be due to invalid IL or missing references)
        //IL_189b: Unknown result type (might be due to invalid IL or missing references)
        //IL_18a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1959: Unknown result type (might be due to invalid IL or missing references)
        //IL_1960: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d21: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d28: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d32: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d48: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d53: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d62: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d67: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d76: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d97: Unknown result type (might be due to invalid IL or missing references)
        //IL_1db2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dcc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ddf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1de4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1deb: Unknown result type (might be due to invalid IL or missing references)
        if (type == 210 || type == 211)
        {
            NPCUtils.TargetClosestNonBees(this);
        }
        else if (target < 0 || target <= 255 || Main.player[target].dead)
        {
            TargetClosest();
        }
        if (type == 619)
        {
            if (Main.dayTime)
            {
                velocity.Y -= 0.3f;
                EncourageDespawn(60);
            }
            position += netOffset;
            if (alpha == 255)
            {
                spriteDirection = direction;
                velocity.Y = -6f;
                for (int i = 0; i < 35; i++)
                {
                    Dust dust = Dust.NewDustDirect(position, width, height, 5);
                    dust.velocity *= 1f;
                    dust.scale = 1f + Main.rand.NextFloat() * 0.5f;
                    dust.fadeIn = 1.5f + Main.rand.NextFloat() * 0.5f;
                    dust.velocity += velocity * 0.5f;
                }
            }
            alpha -= 15;
            if (alpha < 0)
            {
                alpha = 0;
            }
            if (alpha != 0)
            {
                for (int j = 0; j < 2; j++)
                {
                    Dust dust2 = Dust.NewDustDirect(position, width, height, 5);
                    dust2.velocity *= 1f;
                    dust2.scale = 1f + Main.rand.NextFloat() * 0.5f;
                    dust2.fadeIn = 1.5f + Main.rand.NextFloat() * 0.5f;
                    dust2.velocity += velocity * 0.3f;
                }
            }
            position -= netOffset;
        }
        NPCAimedTarget targetData = GetTargetData();
        bool flag = false;
        if (targetData.Type == NPCTargetType.Player)
        {
            flag = Main.player[target].dead;
        }
        float num = 6f;
        float num12 = 0.05f;
        if (type == 6 || type == 173)
        {
            num = 4f;
            num12 = 0.02f;
            if (type == 6 && Main.expertMode)
            {
                num12 = 0.035f;
            }
            if (Main.remixWorld)
            {
                num12 = 0.06f;
                num = 5f;
            }
        }
        else if (type == 94)
        {
            num = 4.2f;
            num12 = 0.022f;
        }
        else if (type == 619)
        {
            num = 6f;
            num12 = 0.1f;
        }
        else if (type == 252)
        {
            if (targetData.Type != 0 && Collision.CanHit(this, targetData))
            {
                num = 6f;
                num12 = 0.1f;
            }
            else
            {
                num12 = 0.01f;
                num = 2f;
            }
        }
        else if (type == 42 || (type >= 231 && type <= 235))
        {
            num = 3.5f;
            num12 = 0.021f;
            if (type == 231)
            {
                num = 3f;
                num12 = 0.017f;
            }
            num *= 1f - scale;
            num12 *= 1f - scale;
            if ((double)(position.Y / 16f) < Main.worldSurface)
            {
                if (Main.player[target].position.Y - position.Y > 300f && velocity.Y < 0f)
                {
                    velocity.Y *= 0.97f;
                }
                if (Main.player[target].position.Y - position.Y < 80f && velocity.Y > 0f)
                {
                    velocity.Y *= 0.97f;
                }
            }
        }
        else if (type == 205)
        {
            num = 3.25f;
            num12 = 0.018f;
        }
        else if (type == 176)
        {
            num = 4f;
            num12 = 0.017f;
        }
        else if (type == 23)
        {
            num = 1f;
            num12 = 0.03f;
        }
        else if (type == 5)
        {
            num = 5f;
            num12 = 0.03f;
        }
        else if (type == 210 || type == 211)
        {
            ai[1] += 1f;
            float num22 = (ai[1] - 60f) / 60f;
            if (num22 > 1f)
            {
                num22 = 1f;
            }
            else
            {
                if (velocity.X > 6f)
                {
                    velocity.X = 6f;
                }
                if (velocity.X < -6f)
                {
                    velocity.X = -6f;
                }
                if (velocity.Y > 6f)
                {
                    velocity.Y = 6f;
                }
                if (velocity.Y < -6f)
                {
                    velocity.Y = -6f;
                }
            }
            num = 5f;
            num12 = 0.1f;
            num12 *= num22;
        }
        else if (type == 139 && Main.zenithWorld)
        {
            num = 3f;
        }
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
        float num23 = targetData.Position.X + (float)(targetData.Width / 2);
        float num24 = targetData.Position.Y + (float)(targetData.Height / 2);
        num23 = (int)(num23 / 8f) * 8;
        num24 = (int)(num24 / 8f) * 8;
        vector.X = (int)(vector.X / 8f) * 8;
        vector.Y = (int)(vector.Y / 8f) * 8;
        num23 -= vector.X;
        num24 -= vector.Y;
        float num25 = (float)Math.Sqrt(num23 * num23 + num24 * num24);
        float num26 = num25;
        bool flag2 = false;
        if (num25 > 600f)
        {
            flag2 = true;
        }
        if (num25 == 0f)
        {
            num23 = velocity.X;
            num24 = velocity.Y;
        }
        else
        {
            num25 = num / num25;
            num23 *= num25;
            num24 *= num25;
        }
        bool num28 = type == 6 || type == 139 || type == 173 || type == 205;
        bool flag3 = type == 42 || type == 94 || type == 619 || type == 176 || type == 210 || type == 211 || (type >= 231 && type <= 235);
        bool flag4 = type != 173 && type != 6 && type != 42 && (type < 231 || type > 235) && type != 94 && type != 139 && type != 619;
        if (num28 || flag3)
        {
            if (num26 > 100f || flag3)
            {
                ai[0] += 1f;
                if (ai[0] > 0f)
                {
                    velocity.Y += 0.023f;
                }
                else
                {
                    velocity.Y -= 0.023f;
                }
                if (ai[0] < -100f || ai[0] > 100f)
                {
                    velocity.X += 0.023f;
                }
                else
                {
                    velocity.X -= 0.023f;
                }
                if (ai[0] > 200f)
                {
                    ai[0] = -200f;
                }
            }
            if (num26 < 150f && (type == 6 || type == 94 || type == 173 || type == 619))
            {
                velocity.X += num23 * 0.007f;
                velocity.Y += num24 * 0.007f;
            }
        }
        if (flag)
        {
            num23 = (float)direction * num / 2f;
            num24 = (0f - num) / 2f;
        }
        else if (type == 619 && base.Center.Y > targetData.Center.Y - 200f)
        {
            velocity.Y -= 0.3f;
        }
        if (type == 139 && ai[3] != 0f)
        {
            if (IsMechQueenUp)
            {
                NPC nPC = Main.npc[mechQueen];
                Vector2 vector2 = default(Vector2);
                ((Vector2)(ref vector2))._002Ector(26f * ai[3], 0f);
                int num27 = (int)ai[2];
                if (num27 < 0 || num27 >= 200)
                {
                    num27 = FindFirstNPC(134);
                    ai[2] = num27;
                    netUpdate = true;
                }
                if (num27 > -1)
                {
                    NPC nPC2 = Main.npc[num27];
                    if (!nPC2.active || nPC2.type != 134)
                    {
                        dontTakeDamage = false;
                        if (ai[3] > 0f)
{
                            netUpdate = true;
                        }
                        ai[3] = 0f;
                    }
                    else
                    {
                        Vector2 spinningpoint = nPC2.Center + vector2;
                        spinningpoint = spinningpoint.RotatedBy(nPC2.rotation, nPC2.Center);
                        base.Center = spinningpoint;
                        velocity = nPC.velocity;
                        dontTakeDamage = true;
                    }
                }
                else
                {
                    dontTakeDamage = false;
                    if (ai[3] > 0f)
                    {
                        netUpdate = true;
                    }
                    ai[3] = 0f;
                }
            }
            else
            {
                dontTakeDamage = false;
                if (ai[3] > 0f)
                {
                    netUpdate = true;
                }
                ai[3] = 0f;
            }
        }
        else
        {
            if (type == 139)
            {
                dontTakeDamage = false;
            }
            if (velocity.X < num23)
            {
                velocity.X += num12;
                if (flag4 && velocity.X < 0f && num23 > 0f)
                {
                    velocity.X += num12;
                }
            }
            else if (velocity.X > num23)
            {
                velocity.X -= num12;
                if (flag4 && velocity.X > 0f && num23 < 0f)
                {
                    velocity.X -= num12;
                }
            }
            if (velocity.Y < num24)
            {
                velocity.Y += num12;
                if (flag4 && velocity.Y < 0f && num24 > 0f)
                {
                    velocity.Y += num12;
                }
            }
            else if (velocity.Y > num24)
            {
                velocity.Y -= num12;
                if (flag4 && velocity.Y > 0f && num24 < 0f)
                {
                    velocity.Y -= num12;
                }
            }
        }
        if (type == 23)
        {
            if (num23 > 0f)
            {
                spriteDirection = 1;
                rotation = (float)Math.Atan2(num24, num23);
            }
            else if (num23 < 0f)
            {
                spriteDirection = -1;
                rotation = (float)Math.Atan2(num24, num23) + 3.14f;
            }
        }
        else if (type == 139)
        {
            localAI[0] += 1f;
            if (ai[3] != 0f)
            {
                localAI[0] += 2f;
            }
            if (justHit)
            {
                localAI[0] = 0f;
            }
            float num2 = 120f;
            if (IsMechQueenUp)
            {
                num2 = 360f;
            }
            if (Main.netMode != 1 && localAI[0] >= num2)
            {
                localAI[0] = 0f;
                if (targetData.Type != 0 && Collision.CanHit(this, targetData))
                {
                    int attackDamage_ForProjectiles = GetAttackDamage_ForProjectiles(25f, 22f);
                    int num3 = 84;
                    Vector2 vector3 = default(Vector2);
                    ((Vector2)(ref vector3))._002Ector(num23, num24);
                    if (IsMechQueenUp)
                    {
                        Vector2 v3 = targetData.Center - base.Center - targetData.Velocity * 20f;
                        float num4 = 8f;
                        vector3 = v3.SafeNormalize(Vector2.UnitY) * num4;
                    }
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector.X, vector.Y, vector3.X, vector3.Y, num3, attackDamage_ForProjectiles, 0f, Main.myPlayer);
                }
            }
            int num5 = (int)position.X + width / 2;
            int num6 = (int)position.Y + height / 2;
            num5 /= 16;
            num6 /= 16;
            if (WorldGen.InWorld(num5, num6) && !WorldGen.SolidTile(num5, num6))
            {
                Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.3f, 0.1f, 0.05f);
            }
            if (num23 > 0f)
            {
                spriteDirection = 1;
                rotation = (float)Math.Atan2(num24, num23);
            }
            if (num23 < 0f)
            {
                spriteDirection = -1;
                rotation = (float)Math.Atan2(num24, num23) + 3.14f;
            }
        }
        else if (type == 6 || type == 94 || type == 173 || type == 619)
        {
            rotation = (float)Math.Atan2(num24, num23) - 1.57f;
        }
        else if (type == 42 || type == 176 || type == 205 || (type >= 231 && type <= 235))
        {
            if (velocity.X > 0f)
            {
                spriteDirection = 1;
            }
            if (velocity.X < 0f)
            {
                spriteDirection = -1;
            }
            rotation = velocity.X * 0.1f;
        }
        else
        {
            rotation = (float)Math.Atan2(velocity.Y, velocity.X) - 1.57f;
        }
        if (type == 6 || type == 619 || type == 23 || type == 42 || type == 94 || type == 139 || type == 173 || type == 176 || type == 205 || type == 210 || type == 211 || (type >= 231 && type <= 235))
        {
            float num7 = 0.7f;
            if (type == 6 || type == 173)
            {
                num7 = 0.4f;
            }
            if (collideX)
            {
                netUpdate = true;
                velocity.X = oldVelocity.X * (0f - num7);
                if (direction == -1 && velocity.X > 0f && velocity.X < 2f)
                {
                    velocity.X = 2f;
                }
                if (direction == 1 && velocity.X < 0f && velocity.X > -2f)
                {
                    velocity.X = -2f;
                }
            }
            if (collideY)
            {
                netUpdate = true;
                velocity.Y = oldVelocity.Y * (0f - num7);
                if (velocity.Y > 0f && (double)velocity.Y < 1.5)
                {
                    velocity.Y = 2f;
                }
                if (velocity.Y < 0f && (double)velocity.Y > -1.5)
                {
                    velocity.Y = -2f;
                }
            }
            position += netOffset;
            if (type == 619)
            {
                int num8 = Dust.NewDust(position, width, height, 5, velocity.X * 0.2f, velocity.Y * 0.2f, 100);
                Dust obj = Main.dust[num8];
                obj.velocity *= 0.5f;
            }
            else if (type != 42 && type != 139 && type != 176 && type != 205 && type != 210 && type != 211 && type != 252 && (type < 231 || type > 235) && Main.rand.Next(20) == 0)
            {
                int num9 = 18;
                if (type == 173)
                {
                    num9 = 5;
                }
                int num10 = Dust.NewDust(new Vector2(position.X, position.Y + (float)height * 0.25f), width, (int)((float)height * 0.5f), num9, velocity.X, 2f, 75, color, scale);
                Main.dust[num10].velocity.X *= 0.5f;
                Main.dust[num10].velocity.Y *= 0.1f;
            }
            position -= netOffset;
        }
        else if (type != 252 && Main.rand.Next(40) == 0)
        {
            int num11 = Dust.NewDust(new Vector2(position.X, position.Y + (float)height * 0.25f), width, (int)((float)height * 0.5f), 5, velocity.X, 2f);
            Main.dust[num11].velocity.X *= 0.5f;
            Main.dust[num11].velocity.Y *= 0.1f;
        }
        if ((type == 6 || type == 94 || type == 173 || type == 619) && wet)
        {
            if (velocity.Y > 0f)
            {
                velocity.Y *= 0.95f;
            }
            velocity.Y -= 0.3f;
            if (velocity.Y < -2f)
            {
                velocity.Y = -2f;
            }
        }
        if (type == 205 && wet)
        {
            if (velocity.Y > 0f)
            {
                velocity.Y *= 0.95f;
            }
            velocity.Y -= 0.5f;
            if (velocity.Y < -4f)
            {
                velocity.Y = -4f;
            }
            TargetClosest();
        }
        if (type == 42 || type == 176 || (type >= 231 && type <= 235))
        {
            if (wet)
            {
                if (velocity.Y > 0f)
                {
                    velocity.Y *= 0.95f;
                }
                velocity.Y -= 0.5f;
                if (velocity.Y < -4f)
                {
                    velocity.Y = -4f;
                }
                TargetClosest();
            }
            if (ai[1] == 101f)
            {
                SoundEngine.PlaySound(in SoundID.Item17, position);
                ai[1] = 0f;
            }
            if (Main.netMode != 1)
            {
                ai[1] += (float)Main.rand.Next(5, 20) * 0.1f * scale;
                if (type == 176)
                {
                    ai[1] += (float)Main.rand.Next(5, 20) * 0.1f * scale;
                }
                if (Main.getGoodWorld)
                {
                    ai[1] += (float)Main.rand.Next(5, 20) * 0.1f * scale;
                }
                if (targetData.Type == NPCTargetType.Player)
                {
                    Player player = Main.player[target];
                    if (player != null && player.stealth == 0f && player.itemAnimation == 0)
                    {
                        ai[1] = 0f;
                    }
                }
                if (ai[1] >= 130f)
                {
                    if (targetData.Type != 0 && Collision.CanHit(this, targetData))
                    {
                        float num13 = 8f;
                        Vector2 vector4 = default(Vector2);
                        ((Vector2)(ref vector4))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)(height / 2));
                        float num14 = targetData.Center.X - vector4.X + (float)Main.rand.Next(-20, 21);
                        float num15 = targetData.Center.Y - vector4.Y + (float)Main.rand.Next(-20, 21);
                        if ((num14 < 0f && velocity.X < 0f) || (num14 > 0f && velocity.X > 0f))
{
                            float num16 = (float)Math.Sqrt(num14 * num14 + num15 * num15);
                            num16 = num13 / num16;
                            num14 *= num16;
                            num15 *= num16;
                            int num17 = (int)(10f * scale);
                            if (type == 176)
{
                                num17 = (int)(30f * scale);
                            }
                            int num18 = 55;
                            int num19 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector4.X, vector4.Y, num14, num15, num18, num17, 0f, Main.myPlayer);
                            Main.projectile[num19].timeLeft = 300;
                            ai[1] = 101f;
                            netUpdate = true;
                        }
                        else
{
                            ai[1] = 0f;
                        }
                    }
                    else
                    {
                        ai[1] = 0f;
                    }
                }
            }
        }
        if (type == 139 && flag2)
        {
            if ((velocity.X > 0f && num23 > 0f) || (velocity.X < 0f && num23 < 0f))
            {
                int num20 = 12;
                if (IsMechQueenUp)
                {
                    num20 = 5;
                }
                if (Math.Abs(velocity.X) < (float)num20)
                {
                    velocity.X *= 1.05f;
                }
            }
            else
            {
                velocity.X *= 0.9f;
            }
        }
        if (type == 139 && IsMechQueenUp && ai[2] == 0f)
        {
            Vector2 center = GetTargetData().Center;
            Vector2 v2 = center - base.Center;
            int num21 = 120;
            if (((Vector2)(ref v2)).Length() < (float)num21)
            {
                base.Center = center - v2.SafeNormalize(Vector2.UnitY) * (float)num21;
            }
        }
        if (Main.netMode != 1)
        {
            if (Main.getGoodWorld && type == 6 && AnyNPCs(13))
            {
                if (justHit)
                {
                    localAI[0] = 0f;
                }
                localAI[0] += 1f;
                if (localAI[0] == 60f)
                {
                    if (targetData.Type != 0 && Collision.CanHit(this, targetData))
                    {
                        NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2) + velocity.X), (int)(position.Y + (float)(height / 2) + velocity.Y), 666);
                    }
                    localAI[0] = 0f;
                }
            }
            if (type == 94 && !flag)
            {
                if (justHit)
                {
                    localAI[0] = 0f;
                }
                localAI[0] += 1f;
                if (localAI[0] == 180f)
                {
                    if (targetData.Type != 0 && Collision.CanHit(this, targetData))
                    {
                        NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2) + velocity.X), (int)(position.Y + (float)(height / 2) + velocity.Y), 112);
                    }
                    localAI[0] = 0f;
                }
            }
            if (type == 619 && !flag)
            {
                if (justHit)
                {
                    localAI[0] += 10f;
                }
                localAI[0] += 1f;
                if (localAI[0] >= 120f)
                {
                    if (targetData.Type != 0 && Collision.CanHit(this, targetData))
                    {
                        Vector2 val = base.Center - targetData.Center;
                        if (((Vector2)(ref val)).Length() < 400f)
{
                            Vector2 vector5 = DirectionTo(new Vector2(targetData.Center.X, targetData.Position.Y));
                            velocity = -vector5 * 5f;
                            netUpdate = true;
                            localAI[0] = 0f;
                            vector5 = DirectionTo(new Vector2(targetData.Center.X + (float)Main.rand.Next(-100, 101), targetData.Position.Y + (float)Main.rand.Next(-100, 101)));
                            Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center, vector5 * 15f, 811, 35, 1f, Main.myPlayer);
                        }
                        else
{
                            localAI[0] = 50f;
                        }
                    }
                    else
                    {
                        localAI[0] = 50f;
                    }
                }
            }
        }
        if ((Main.IsItDay() && type != 173 && type != 619 && type != 6 && type != 23 && type != 42 && type != 94 && type != 176 && type != 205 && type != 210 && type != 211 && type != 252 && (type < 231 || type > 235)) || flag)
        {
            velocity.Y -= num12 * 2f;
            EncourageDespawn(10);
        }
        if (((velocity.X > 0f && oldVelocity.X < 0f) || (velocity.X < 0f && oldVelocity.X > 0f) || (velocity.Y > 0f && oldVelocity.Y < 0f) || (velocity.Y < 0f && oldVelocity.Y > 0f)) && !justHit)
        {
            netUpdate = true;
        }
    }
References Terraria.Lighting.AddLight(), Terraria.NPC.ai, Terraria.NPC.alpha, Terraria.NPC.AnyNPCs(), Terraria.Collision.CanHit(), Terraria.DataStructures.NPCAimedTarget.Center, Terraria.NPC.collideX, Terraria.NPC.collideY, Terraria.NPC.color, Terraria.Main.dayTime, Terraria.Entity.direction, Terraria.Entity.DirectionTo(), Terraria.NPC.dontTakeDamage, Terraria.Main.dust, Terraria.NPC.EncourageDespawn(), Terraria.Main.expertMode, Terraria.NPC.FindFirstNPC(), Terraria.NPC.GetAttackDamage_ForProjectiles(), Terraria.Main.getGoodWorld, Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.NPC.GetTargetData(), Terraria.Entity.height, Terraria.WorldGen.InWorld(), Terraria.Main.IsItDay(), Terraria.NPC.IsMechQueenUp, Terraria.ID.SoundID.Item17, Terraria.Player.itemAnimation, Terraria.NPC.justHit, Terraria.NPC.localAI, Terraria.NPC.mechQueen, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netOffset, Terraria.NPC.netUpdate, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.Entity.oldVelocity, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.NPC.rotation, Terraria.NPC.scale, Terraria.WorldGen.SolidTile(), Terraria.NPC.spriteDirection, Terraria.Player.stealth, Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Utilities.NPCUtils.TargetClosestNonBees(), Terraria.NPC.type, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Entity.width, Terraria.Main.worldSurface, and Terraria.Main.zenithWorld.
Referenced by Terraria.NPC.VanillaAI_Inner().