TModLoader: Terraria.NPC.AI_112_FairyCritter
AI_112_FairyCritter()
void Terraria.NPC.AI_112_FairyCritter () inline private
Definition at line 50288 of file NPC.cs.
    {
        //IL_107c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a87: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a92: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0644: Unknown result type (might be due to invalid IL or missing references)
        //IL_064f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0960: Unknown result type (might be due to invalid IL or missing references)
        //IL_096b: Unknown result type (might be due to invalid IL or missing references)
        //IL_093b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0945: Unknown result type (might be due to invalid IL or missing references)
        //IL_094a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cfc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d05: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0767: Unknown result type (might be due to invalid IL or missing references)
        //IL_076a: Unknown result type (might be due to invalid IL or missing references)
        //IL_076f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0774: Unknown result type (might be due to invalid IL or missing references)
        //IL_0777: Unknown result type (might be due to invalid IL or missing references)
        //IL_0779: Unknown result type (might be due to invalid IL or missing references)
        //IL_0783: Unknown result type (might be due to invalid IL or missing references)
        //IL_0788: Unknown result type (might be due to invalid IL or missing references)
        //IL_078b: Unknown result type (might be due to invalid IL or missing references)
        //IL_06df: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d37: Unknown result type (might be due to invalid IL or missing references)
        //IL_1178: Unknown result type (might be due to invalid IL or missing references)
        //IL_117d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1192: Unknown result type (might be due to invalid IL or missing references)
        //IL_1197: Unknown result type (might be due to invalid IL or missing references)
        //IL_119a: Unknown result type (might be due to invalid IL or missing references)
        //IL_119c: Unknown result type (might be due to invalid IL or missing references)
        //IL_119e: Unknown result type (might be due to invalid IL or missing references)
        //IL_11a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_11b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_11bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_10e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_10f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_027d: Unknown result type (might be due to invalid IL or missing references)
        //IL_079d: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0edd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1470: Unknown result type (might be due to invalid IL or missing references)
        //IL_1475: Unknown result type (might be due to invalid IL or missing references)
        //IL_1476: Unknown result type (might be due to invalid IL or missing references)
        //IL_147b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0702: Unknown result type (might be due to invalid IL or missing references)
        //IL_0712: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f09: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d60: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bce: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bde: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_148b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1490: Unknown result type (might be due to invalid IL or missing references)
        //IL_1491: Unknown result type (might be due to invalid IL or missing references)
        //IL_1496: Unknown result type (might be due to invalid IL or missing references)
        //IL_087d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0884: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a12: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a14: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f31: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f36: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f29: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_14a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_14a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_14aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_14af: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_0218: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        //IL_0896: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f56: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0def: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df9: Unknown result type (might be due to invalid IL or missing references)
        //IL_121c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b75: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1581: Unknown result type (might be due to invalid IL or missing references)
        //IL_1588: Unknown result type (might be due to invalid IL or missing references)
        //IL_1592: Unknown result type (might be due to invalid IL or missing references)
        //IL_14bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_14c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_14cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_14dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_14eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_150a: Unknown result type (might be due to invalid IL or missing references)
        //IL_150b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1516: Unknown result type (might be due to invalid IL or missing references)
        //IL_1527: Unknown result type (might be due to invalid IL or missing references)
        //IL_1531: Unknown result type (might be due to invalid IL or missing references)
        //IL_1536: Unknown result type (might be due to invalid IL or missing references)
        //IL_153d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1543: Unknown result type (might be due to invalid IL or missing references)
        //IL_154d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1552: Unknown result type (might be due to invalid IL or missing references)
        //IL_1557: Unknown result type (might be due to invalid IL or missing references)
        //IL_156b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1571: Unknown result type (might be due to invalid IL or missing references)
        //IL_1576: Unknown result type (might be due to invalid IL or missing references)
        //IL_157b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1003: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e09: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1279: Unknown result type (might be due to invalid IL or missing references)
        //IL_1286: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e73: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e78: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e82: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e86: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e92: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_15b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_15bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ece: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed3: Unknown result type (might be due to invalid IL or missing references)
        bool flag = false;
        lavaImmune = true;
        if (Main.netMode != 1 && ai[2] > 1f)
        {
            int num = 18000;
            localAI[1] += 1f;
            if (localAI[1] >= (float)num)
            {
                ai[2] = 7f;
                if (Main.player[target].Center.X < base.Center.X)
                {
                    direction = 1;
                }
                else
                {
                    direction = -1;
                }
                netUpdate = true;
            }
        }
        Rectangle val;
        switch ((int)ai[2])
        {
        case 0:
        {
            lavaImmune = false;
            noTileCollide = false;
            if (ai[0] == 0f && ai[1] == 0f)
            {
                ai[0] = base.Center.X;
                ai[1] = base.Center.Y;
            }
            if (localAI[0] == 0f)
            {
                localAI[0] = 1f;
                velocity = new Vector2(MathHelper.Lerp(2f, 4f, Main.rand.NextFloat()) * (float)(Main.rand.Next(2) * 2 - 1), MathHelper.Lerp(1f, 2f, Main.rand.NextFloat()) * (float)(Main.rand.Next(2) * 2 - 1));
                velocity *= 0.7f;
                netUpdate = true;
            }
            Vector2 vector4 = new Vector2(ai[0], ai[1]) - base.Center;
            if (((Vector2)(ref vector4)).Length() > 20f)
            {
                Vector2 vector5 = default(Vector2);
                ((Vector2)(ref vector5))._002Ector((float)((vector4.X > 0f) ? 1 : (-1)), (float)((vector4.Y > 0f) ? 1 : (-1)));
                velocity += vector5 * 0.04f;
                if (Math.Abs(velocity.Y) > 2f)
                {
                    velocity.Y *= 0.95f;
                }
            }
            TargetClosest();
            Player player = Main.player[target];
            if (!player.dead && player.Distance(base.Center) < 250f)
            {
                ai[2] = 1f;
                direction = ((!(player.Center.X > base.Center.X)) ? 1 : (-1));
                if (velocity.X * (float)direction < 0f)
                {
                    velocity.X = direction * 2;
                }
                ai[3] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 1:
        {
            lavaImmune = false;
            noTileCollide = false;
            if (collideX)
            {
                direction *= -1;
                velocity.X = direction * 2;
            }
            if (collideY)
            {
                velocity.Y = ((oldVelocity.Y > 0f) ? 1 : (-1));
            }
            float num4 = 4.5f;
            if (Math.Sign(velocity.X) != direction || Math.Abs(velocity.X) < num4)
            {
                velocity.X += (float)direction * 0.04f;
                if (velocity.X * (float)direction < 0f)
                {
                    if (Math.Abs(velocity.X) > num4)
                    {
                        velocity.X += (float)direction * 0.4f;
                    }
                    else
                    {
                        velocity.X += (float)direction * 0.2f;
                    }
                }
                else if (Math.Abs(velocity.X) > num4)
                {
                    velocity.X = (float)direction * num4;
                }
            }
            int num5 = (int)((position.X + (float)(width / 2)) / 16f);
            int num6 = 20;
            if (direction < 0)
            {
                num5 -= num6;
            }
            int num7 = (int)((position.Y + (float)height) / 16f);
            bool flag4 = true;
            int num8 = 8;
            bool flag5 = false;
            for (int i = num5; i <= num5 + num6; i++)
            {
                for (int j = num7; j < num7 + num8; j++)
                {
                    if (Main.tile[i, j] == null)
                    {
                        Main.tile[i, j] = default(Tile);
                    }
                    if ((Main.tile[i, j].nactive() && Main.tileSolid[Main.tile[i, j].type]) || Main.tile[i, j].liquid > 0)
                    {
                        if (j < num7 + 5)
{
                            flag5 = true;
                        }
                        flag4 = false;
                        break;
                    }
                }
            }
            if (flag4)
            {
                velocity.Y += 0.05f;
            }
            else
            {
                velocity.Y -= 0.2f;
            }
            if (flag5)
            {
                velocity.Y -= 0.3f;
            }
            if (velocity.Y > 3f)
            {
                velocity.Y = 3f;
            }
            if (velocity.Y < -5f)
            {
                velocity.Y = -5f;
            }
            break;
        }
        case 2:
        {
            noTileCollide = true;
            NPCAimedTarget targetData = GetTargetData();
            bool flag2 = false;
            if (targetData.Type == NPCTargetType.Player)
            {
                flag2 = Main.player[target].dead;
            }
            if (flag2)
            {
                ai[2] = 1f;
                direction = ((!(targetData.Center.X > base.Center.X)) ? 1 : (-1));
                if (velocity.X * (float)direction < 0f)
                {
                    velocity.X = direction * 2;
                }
                ai[3] = 0f;
                netUpdate = true;
                break;
            }
            Rectangle r = Utils.CenteredRectangle(targetData.Center, new Vector2((float)(targetData.Width + 60), (float)(targetData.Height / 2)));
            if (Main.netMode != 1)
            {
                val = base.Hitbox;
                if (((Rectangle)(ref val)).Intersects(r))
                {
                    if (GetFairyTreasureCoords(out var treasureCoords2))
                    {
                        ai[0] = treasureCoords2.X;
                        ai[1] = treasureCoords2.Y;
                        ai[2] = 3f;
                        ai[3] = 0f;
                        netUpdate = true;
                    }
                    else
                    {
                        ai[2] = 6f;
                        ai[3] = 0f;
                        netUpdate = true;
                    }
                    break;
                }
            }
            Vector2 vector3 = r.ClosestPointInRect(base.Center);
            Vector2 value = DirectionTo(vector3) * 2f;
            float num15 = Distance(vector3);
            if (num15 > 150f)
            {
                value *= 2f;
            }
            else if (num15 > 80f)
            {
                value *= 1.5f;
            }
            velocity = Vector2.Lerp(velocity, value, 0.07f);
            Point point = base.Center.ToTileCoordinates();
            if (ai[3] < 300f)
            {
                GetBirdFlightRecommendation(6, 3, point, out var goDownwards, out var goUpwards);
                if (goDownwards)
                {
                    velocity.Y += 0.05f;
                }
                if (goUpwards)
                {
                    velocity.Y -= 0.02f;
                }
                if (velocity.Y > 2f)
                {
                    velocity.Y = 2f;
                }
                if (velocity.Y < -4f)
                {
                    velocity.Y = -4f;
                }
            }
            if (WorldGen.InWorld(point.X, point.Y))
            {
                if (WorldGen.SolidTile(point))
                {
                    ai[3] = Math.Min(ai[3] + 2f, 400f);
                }
                else
                {
                    ai[3] = Math.Max(ai[3] - 1f, 0f);
                }
            }
            break;
        }
        case 3:
            noTileCollide = true;
            if (ai[3] == 15f)
            {
                SoundEngine.PlaySound(27, (int)position.X, (int)position.Y);
            }
            if (ai[3] <= 15f)
            {
                velocity *= 0.9f;
            }
            else
            {
                if (Main.player[target].Center.X > base.Center.X)
                {
                    spriteDirection = -1;
                }
                else
                {
                    spriteDirection = 1;
                }
                flag = true;
                float num13 = 0f;
                float num14 = ai[3] - 15f;
                float circleHeight = 22f;
                if (num14 <= 65f)
                {
                    num13 = (float)Math.PI / 8f;
                    circleHeight = 14f;
                }
                else if (num14 <= 130f)
                {
                    num13 = -(float)Math.PI / 8f;
                    circleHeight = 18f;
                }
                num13 *= (float)direction;
                Vector2 fairyCircleOffset3 = GetFairyCircleOffset(num14 / 65f, num13, circleHeight);
                Vector2 fairyCircleOffset4 = GetFairyCircleOffset(num14 / 65f + 1f / 65f, num13, circleHeight);
                velocity = fairyCircleOffset4 - fairyCircleOffset3;
            }
            ai[3] += 1f;
            if (ai[3] >= 210f)
            {
                ai[2] = 4f;
                TargetClosest();
                ai[3] = 0f;
                netUpdate = true;
            }
            break;
        case 6:
        {
            noTileCollide = true;
            Vector2 vector = Main.player[target].Center - base.Center;
            if (((Vector2)(ref vector)).Length() > 100f)
            {
                ai[2] = 2f;
                TargetClosest();
                ai[3] = 0f;
                netUpdate = true;
                break;
            }
            if (!Collision.SolidCollision(position, width, height))
            {
                noTileCollide = false;
                if (collideX)
                {
                    velocity.X *= -1f;
                }
                if (collideY)
                {
                    velocity.Y *= -1f;
                }
            }
            if (((Vector2)(ref vector)).Length() > 20f)
            {
                Vector2 vector2 = default(Vector2);
                ((Vector2)(ref vector2))._002Ector((float)((vector.X > 0f) ? 1 : (-1)), (float)((vector.Y > 0f) ? 1 : (-1)));
                velocity += vector2 * 0.04f;
                if (Math.Abs(velocity.Y) > 2f)
                {
                    velocity.Y *= 0.95f;
                }
            }
            if (Main.netMode != 1 && GetFairyTreasureCoords(out var treasureCoords))
            {
                ai[0] = treasureCoords.X;
                ai[1] = treasureCoords.Y;
                ai[2] = 3f;
                ai[3] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 4:
        {
            noTileCollide = true;
            NPCAimedTarget targetData2 = GetTargetData();
            bool flag3 = false;
            if (targetData2.Type == NPCTargetType.Player)
            {
                flag3 = Main.player[target].dead;
            }
            if (flag3)
            {
                ai[2] = 1f;
                direction = ((!(targetData2.Center.X > base.Center.X)) ? 1 : (-1));
                if (velocity.X * (float)direction < 0f)
                {
                    velocity.X = direction * 2;
                }
                ai[3] = 0f;
                netUpdate = true;
                break;
            }
            Rectangle r2 = Utils.CenteredRectangle(new Vector2(ai[0] * 16f + 8f, ai[1] * 16f + 8f), Vector2.One * 5f);
            val = base.Hitbox;
            if (((Rectangle)(ref val)).Intersects(r2))
            {
                ai[2] = 5f;
                ai[3] = 0f;
                netUpdate = true;
                break;
            }
            float num16 = Distance(targetData2.Center);
            float num2 = 300f;
            if (num16 > num2)
            {
                if (num16 < num2 + 100f && !Collision.SolidCollision(position, width, height))
                {
                    noTileCollide = false;
                    if (collideX)
                    {
                        velocity.X *= -1f;
                    }
                    if (collideY)
                    {
                        velocity.Y *= -1f;
                    }
                }
                flag = true;
                if (Main.player[target].Center.X > base.Center.X)
                {
                    spriteDirection = -1;
                }
                else
                {
                    spriteDirection = 1;
                }
                Vector2 vector6 = DirectionFrom(targetData2.Center);
                if (num16 > num2 + 60f)
                {
                    velocity += vector6 * -0.1f;
                    if (Main.rand.Next(30) == 0)
                    {
                        SoundEngine.PlaySound(27, (int)position.X, (int)position.Y);
                    }
                }
                else if (num16 < num2 + 30f)
                {
                    Vector2 destination = r2.ClosestPointInRect(base.Center);
                    Vector2 vector7 = DirectionTo(destination);
                    velocity += vector7 * 0.1f;
                }
                if (((Vector2)(ref velocity)).Length() > 1f)
                {
                    velocity *= 1f / ((Vector2)(ref velocity)).Length();
                }
                break;
            }
            Vector2 vector8 = r2.ClosestPointInRect(base.Center);
            Vector2 value2 = DirectionTo(vector8);
            float num3 = Distance(vector8);
            if (num3 > 150f)
            {
                value2 *= 3f;
            }
            else if (num3 > 80f)
            {
                value2 *= 2f;
            }
            Point point2 = base.Center.ToTileCoordinates();
            if (ai[3] < 300f)
            {
                velocity = Vector2.Lerp(velocity, value2, 0.07f);
                GetBirdFlightRecommendation(4, 2, point2, out var goDownwards2, out var goUpwards2);
                if (goDownwards2)
                {
                    velocity.Y += 0.05f;
                }
                if (goUpwards2)
                {
                    velocity.Y -= 0.05f;
                }
                if (velocity.Y > 1f)
                {
                    velocity.Y = 1f;
                }
                if (velocity.Y < -1f)
                {
                    velocity.Y = -1f;
                }
            }
            else
            {
                velocity = Vector2.Lerp(velocity, value2, 0.07f);
            }
            if (WorldGen.SolidTile(point2))
            {
                ai[3] = Math.Min(ai[3] + 2f, 400f);
            }
            else
            {
                ai[3] = Math.Max(ai[3] - 1f, 0f);
            }
            break;
        }
        case 5:
        {
            localAI[1] = 0f;
            noTileCollide = true;
            Tile tileSafely = Framing.GetTileSafely(new Point((int)ai[0], (int)ai[1]));
            if (tileSafely.active())
            {
                SceneMetrics.IsValidForOreFinder(tileSafely);
            }
            if (ai[3] == 15f)
            {
                SoundEngine.PlaySound(27, (int)position.X, (int)position.Y);
            }
            if (ai[3] <= 15f)
            {
                velocity *= 0.9f;
            }
            else
            {
                flag = true;
                float num10 = 0f;
                float num11 = ai[3] - 15f;
                float num12 = 22f;
                int num17 = (int)(num11 / 50f);
                num10 = (float)Math.Cos((float)num17 * 1f) * ((float)Math.PI * 2f) / 16f;
                num12 = (float)Math.Cos((float)num17 * 2f) * 10f + 8f;
                num10 *= (float)direction;
                Vector2 fairyCircleOffset = GetFairyCircleOffset(num11 / 50f, num10, num12);
                Vector2 fairyCircleOffset2 = GetFairyCircleOffset(num11 / 50f + 0.02f, num10, num12);
                velocity = fairyCircleOffset2 - fairyCircleOffset;
                if (Main.player[target].Center.X > base.Center.X)
                {
                    spriteDirection = -1;
                }
                else
                {
                    spriteDirection = 1;
                }
            }
            ai[3] += 1f;
            if (Main.netMode != 1 && ai[3] > 200f)
            {
                active = false;
                if (Main.netMode == 0)
                {
                    FairyEffects(base.Center, type - 583);
                }
                else if (Main.netMode == 2)
                {
                    netSkip = -1;
                    life = 0;
                    NetMessage.SendData(23, -1, -1, null, whoAmI);
                    NetMessage.SendData(112, -1, -1, null, 2, (int)base.Center.X, (int)base.Center.Y, 0f, type - 583);
                }
            }
            break;
        }
        case 7:
            noTileCollide = true;
            velocity.X += 0.05f * (float)direction;
            velocity.X = MathHelper.Clamp(velocity.X, -10f, 10f);
            velocity.Y -= 0.025f;
            velocity.Y = MathHelper.Clamp(velocity.Y, -5f, 5f);
            EncourageDespawn(10);
            break;
        }
        dontTakeDamage = (dontTakeDamageFromHostiles = ai[2] > 1f);
        for (int k = 0; k < 200; k++)
        {
            if (k != whoAmI && Main.npc[k].active && Main.npc[k].aiStyle == 112 && Math.Abs(position.X - Main.npc[k].position.X) + Math.Abs(position.Y - Main.npc[k].position.Y) < (float)width * 1.5f)
            {
                if (position.Y < Main.npc[k].position.Y)
                {
                    velocity.Y -= 0.05f;
                }
                else
                {
                    velocity.Y += 0.05f;
                }
            }
        }
        if (!flag)
        {
            direction = ((velocity.X >= 0f) ? 1 : (-1));
            spriteDirection = -direction;
        }
        Color value3 = Color.HotPink;
        Color value4 = Color.LightPink;
        int num9 = 4;
        if (type == 584)
        {
            value3 = Color.LimeGreen;
            value4 = Color.LightSeaGreen;
        }
        if (type == 585)
        {
            value3 = Color.RoyalBlue;
            value4 = Color.LightBlue;
        }
        if ((int)Main.timeForVisualEffects % 2 == 0)
        {
            position += netOffset;
            Dust dust = Dust.NewDustDirect(base.Center - new Vector2((float)num9) * 0.5f, num9 + 4, num9 + 4, 278, 0f, 0f, 200, Color.Lerp(value3, value4, Main.rand.NextFloat()), 0.65f);
            dust.velocity *= 0f;
            dust.velocity += velocity * 0.3f;
            dust.noGravity = true;
            dust.noLight = true;
            position -= netOffset;
        }
        Lighting.AddLight(base.Center, ((Color)(ref value3)).ToVector3() * 0.7f);
        if (Main.netMode == 2)
        {
            return;
        }
        Player localPlayer = Main.LocalPlayer;
        if (!localPlayer.dead)
        {
            val = localPlayer.HitboxForBestiaryNearbyCheck;
            if (((Rectangle)(ref val)).Intersects(base.Hitbox))
            {
                AchievementsHelper.HandleSpecialEvent(localPlayer, 22);
            }
        }
    }
References Terraria.Entity.active, Terraria.Lighting.AddLight(), Terraria.NPC.ai, Terraria.NPC.aiStyle, Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.NPC.collideX, Terraria.NPC.collideY, Terraria.Player.dead, Terraria.Entity.direction, Terraria.Entity.DirectionFrom(), Terraria.Entity.DirectionTo(), Terraria.Entity.Distance(), Terraria.NPC.dontTakeDamage, Terraria.NPC.dontTakeDamageFromHostiles, Terraria.NPC.EncourageDespawn(), Terraria.NPC.FairyEffects(), Terraria.NPC.GetBirdFlightRecommendation(), Terraria.NPC.GetFairyCircleOffset(), Terraria.NPC.GetFairyTreasureCoords(), Terraria.NPC.GetTargetData(), Terraria.Framing.GetTileSafely(), Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Entity.height, Terraria.WorldGen.InWorld(), Terraria.SceneMetrics.IsValidForOreFinder(), Terraria.NPC.lavaImmune, Terraria.NPC.life, Terraria.NPC.localAI, Terraria.Main.LocalPlayer, Terraria.Main.netMode, Terraria.NPC.netOffset, Terraria.NPC.netSkip, Terraria.NPC.netUpdate, Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.NPC.noTileCollide, Terraria.Main.npc, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Collision.SolidCollision(), Terraria.WorldGen.SolidTile(), Terraria.NPC.spriteDirection, Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.NPC.type, Terraria.NPC.value, Terraria.Entity.velocity, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.NPC.VanillaAI_Inner().