TModLoader: Terraria.NPC.HaveDryadDoStardewAnimation
HaveDryadDoStardewAnimation()
static void Terraria.NPC.HaveDryadDoStardewAnimation () inline static
Definition at line 13959 of file NPC.cs.
    {
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0140: Unknown result type (might be due to invalid IL or missing references)
        //IL_014b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector2 = default(Vector2);
        for (int i = 0; i < 200; i++)
        {
            NPC nPC = Main.npc[i];
            if (!nPC.active || nPC.type != 20)
            {
                continue;
            }
            nPC.localAI[2] = 480f;
            nPC.ai[0] = 24f;
            nPC.ai[1] = 480f;
            nPC.ai[2] = 0f;
            nPC.localAI[3] = 0f;
            nPC.netUpdate = true;
            nPC.direction = 1;
            nPC.spriteDirection = 1;
            Vector2 vector = nPC.Bottom + new Vector2(100f, 0f);
            Point p = vector.ToTileCoordinates();
            p.Y = Utils.Clamp(p.Y - 10, 10, Main.maxTilesY - 10);
            int y = p.Y;
            int num = 15;
            int num2 = p.Y + num;
            bool flag = false;
            for (int j = p.Y; j < num2; j++)
            {
                Tile tile = Main.tile[p.X, j];
                p.Y = j;
                if (tile.active() && Main.tileSolid[tile.type])
                {
                    if (j == y)
                    {
                        flag = true;
                    }
                    break;
                }
            }
            ((Vector2)(ref vector2))._002Ector(0f, -52f);
            Vector2 vector3 = p.ToWorldCoordinates(8f, 0f);
            if (flag)
            {
                vector3 = vector;
            }
            Projectile.NewProjectile(new EntitySource_DebugCommand("DryadStardewAnimation"), vector3 + vector2, Vector2.Zero, 995, 0, 0f, Main.myPlayer);
            break;
        }
    }
References Terraria.Tile.active(), Terraria.Main.maxTilesY, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Main.GUIChatDrawInner().