TModLoader: Terraria.NPC.AI_065_Butterflies
AI_065_Butterflies()
void Terraria.NPC.AI_065_Butterflies () inline private
    {
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_068a: Unknown result type (might be due to invalid IL or missing references)
        //IL_069b: Unknown result type (might be due to invalid IL or missing references)
        //IL_077e: Unknown result type (might be due to invalid IL or missing references)
        //IL_078f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0476: Unknown result type (might be due to invalid IL or missing references)
        //IL_048c: Unknown result type (might be due to invalid IL or missing references)
        //IL_088f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0894: Unknown result type (might be due to invalid IL or missing references)
        //IL_0912: Unknown result type (might be due to invalid IL or missing references)
        //IL_0916: Unknown result type (might be due to invalid IL or missing references)
        //IL_091b: Unknown result type (might be due to invalid IL or missing references)
        //IL_091d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0924: Unknown result type (might be due to invalid IL or missing references)
        //IL_0929: Unknown result type (might be due to invalid IL or missing references)
        //IL_092d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0932: Unknown result type (might be due to invalid IL or missing references)
        //IL_0934: Unknown result type (might be due to invalid IL or missing references)
        //IL_0939: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0206: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_023f: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0262: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        //IL_028a: Unknown result type (might be due to invalid IL or missing references)
        //IL_028f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0952: Unknown result type (might be due to invalid IL or missing references)
        //IL_0957: Unknown result type (might be due to invalid IL or missing references)
        //IL_095c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0966: Unknown result type (might be due to invalid IL or missing references)
        //IL_096b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0322: Unknown result type (might be due to invalid IL or missing references)
        //IL_032c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0331: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a31: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a41: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a56: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0add: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a87: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aaa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad6: Unknown result type (might be due to invalid IL or missing references)
        float num = ai[0];
        float num12 = ai[1];
        Color newColor2;
        if (type == 661)
        {
            newColor2 = Main.hslToRgb(Main.GlobalTimeWrappedHourly * 0.33f % 1f, 1f, 0.5f);
            Vector3 rgb = ((Color)(ref newColor2)).ToVector3() * 0.3f;
            rgb += Vector3.One * 0.1f;
            Lighting.AddLight(base.Center, rgb);
            int num22 = 60;
            bool flag = false;
            int num28 = 50;
            NPCAimedTarget targetData = GetTargetData();
            if (targetData.Invalid || targetData.Center.Distance(base.Center) >= 300f)
            {
                flag = true;
            }
            if (!Main.remixWorld && !targetData.Invalid && targetData.Type == NPCTargetType.Player && !Main.player[target].ZoneHallow)
            {
                num28 = num22;
                flag = true;
            }
            ai[2] = MathHelper.Clamp(ai[2] + (float)flag.ToDirectionInt(), 0f, (float)num28);
            if (ai[2] >= (float)num22)
            {
                active = false;
                if (Main.netMode != 1)
                {
                    NetMessage.SendData(23, -1, -1, null, whoAmI);
                }
                return;
            }
            Opacity = Utils.GetLerpValue(num22, (float)num28 / 2f, ai[2], clamped: true);
            if (ai[2] > 0f)
            {
                int num29 = 1;
                for (int i = 0; i < num29; i++)
                {
                    if (Main.rand.Next(5) == 0)
                    {
                        float num30 = MathHelper.Lerp(0.9f, 0.6f, Opacity);
                        Color newColor = Main.hslToRgb(Main.GlobalTimeWrappedHourly * 0.3f % 1f, 1f, 0.5f) * 0.5f;
                        int num31 = Dust.NewDust(position, width, height, 267, 0f, 0f, 0, newColor);
                        Main.dust[num31].position = base.Center + Main.rand.NextVector2Circular(width, height);
                        Dust obj = Main.dust[num31];
                        obj.velocity *= Main.rand.NextFloat() * 0.8f;
                        Dust obj2 = Main.dust[num31];
                        obj2.velocity += velocity * 0.6f;
                        Main.dust[num31].noGravity = true;
                        Main.dust[num31].fadeIn = 0.6f + Main.rand.NextFloat() * 0.7f * num30;
                        Main.dust[num31].scale = 0.35f;
                        if (num31 != 6000)
{
                            Dust dust = Dust.CloneDust(num31);
                            dust.scale /= 2f;
                            dust.fadeIn *= 0.85f;
                            dust.color = new Color(255, 255, 255, 255) * 0.5f;
                        }
                    }
                }
            }
            dontTakeDamage = ai[2] >= (float)(num28 / 2);
        }
        if (Main.netMode != 1)
        {
            if (ai[2] == 0f && type != 661)
            {
                int num32 = 0;
                int num33 = 4;
                int num2 = 6;
                int num3 = 3;
                int num4 = 7;
                int num5 = 2;
                int num6 = 1;
                int num7 = 5;
                int num8 = Main.rand.Next(100);
                num8 = ((num8 == 0) ? num7 : ((num8 < 3) ? num6 : ((num8 < 9) ? num5 : ((num8 < 19) ? num4 : ((num8 < 34) ? num3 : ((num8 < 53) ? num2 : ((num8 >= 75) ? num32 : num33)))))));
                ai[2] = 1 + num8;
            }
            if (ai[3] == 0f)
            {
                ai[3] = (float)Main.rand.Next(75, 111) * 0.01f;
            }
            localAI[0] -= 1f;
            if (localAI[0] <= 0f)
            {
                localAI[0] = Main.rand.Next(90, 240);
                TargetClosest();
                float num9 = Math.Abs(base.Center.X - Main.player[target].Center.X);
                if (num9 > 700f && localAI[3] == 0f)
                {
                    float num10 = (float)Main.rand.Next(50, 151) * 0.01f;
                    if (num9 > 1000f)
                    {
                        num10 = (float)Main.rand.Next(150, 201) * 0.01f;
                    }
                    else if (num9 > 850f)
                    {
                        num10 = (float)Main.rand.Next(100, 151) * 0.01f;
                    }
                    int num11 = direction * Main.rand.Next(100, 251);
                    int num13 = Main.rand.Next(-50, 51);
                    if (position.Y > Main.player[target].position.Y - 100f)
                    {
                        num13 -= Main.rand.Next(100, 251);
                    }
                    float num14 = num10 / (float)Math.Sqrt(num11 * num11 + num13 * num13);
                    num = (float)num11 * num14;
                    num12 = (float)num13 * num14;
                }
                else
                {
                    localAI[3] = 1f;
                    float num34 = (float)Main.rand.Next(26, 301) * 0.01f;
                    int num15 = Main.rand.Next(-100, 101);
                    int num16 = Main.rand.Next(-100, 101);
                    float num17 = num34 / (float)Math.Sqrt(num15 * num15 + num16 * num16);
                    num = (float)num15 * num17;
                    num12 = (float)num16 * num17;
                }
                netUpdate = true;
            }
        }
        scale = ai[3];
        int num18 = 60;
        velocity.X = (velocity.X * (float)(num18 - 1) + num) / (float)num18;
        velocity.Y = (velocity.Y * (float)(num18 - 1) + num12) / (float)num18;
        if (velocity.Y > 0f)
        {
            int num19 = 3;
            int num20 = (int)base.Center.X / 16;
            int num21 = (int)base.Center.Y / 16;
            for (int j = num21; j < num21 + num19; j++)
            {
                if (Main.tile[num20, j] != null && ((Main.tile[num20, j].nactive() && Main.tileSolid[Main.tile[num20, j].type]) || Main.tile[num20, j].liquid > 0))
                {
                    num12 *= -1f;
                    if (velocity.Y > 0f)
                    {
                        velocity.Y *= 0.9f;
                    }
                }
            }
        }
        if (velocity.Y < 0f)
        {
            int num23 = 30;
            bool flag2 = false;
            int num24 = (int)base.Center.X / 16;
            int num25 = (int)base.Center.Y / 16;
            for (int k = num25; k < num25 + num23; k++)
            {
                if (Main.tile[num24, k] != null && Main.tile[num24, k].nactive() && Main.tileSolid[Main.tile[num24, k].type])
                {
                    flag2 = true;
                }
            }
            if (!flag2)
            {
                num12 *= -1f;
                if (velocity.Y < 0f)
                {
                    velocity.Y *= 0.9f;
                }
            }
        }
        if (localAI[1] > 0f)
        {
            localAI[1] -= 1f;
        }
        else
        {
            localAI[1] = 15f;
            if (type == 661)
            {
                localAI[1] = 10f;
            }
            float num26 = 0f;
            Vector2 zero = Vector2.Zero;
            for (int l = 0; l < 200; l++)
            {
                NPC nPC = Main.npc[l];
                if (nPC.active && nPC.damage > 0 && !nPC.friendly && nPC.Hitbox.Distance(base.Center) <= 100f)
                {
                    num26 += 1f;
                    zero += DirectionFrom(nPC.Center);
                }
            }
            if (num26 > 0f)
            {
                zero /= num26;
                zero *= 2f;
                velocity += zero;
                if (((Vector2)(ref velocity)).Length() > 16f)
                {
                    velocity = velocity.SafeNormalize(Vector2.Zero) * 16f;
                }
            }
        }
        if (collideX)
        {
            num = ((!(velocity.X < 0f)) ? (0f - Math.Abs(num)) : Math.Abs(num));
            velocity.X *= -0.2f;
        }
        if (velocity.X < 0f)
        {
            direction = -1;
        }
        if (velocity.X > 0f)
        {
            direction = 1;
        }
        ai[0] = num;
        ai[1] = num12;
        if (type == 356)
        {
            catchItem = (short)(1994f + ai[2] - 1f);
        }
        if (type == 653)
        {
            position += netOffset;
            Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.6f, 0.3f, 0.1f);
            if (Main.rand.Next(60) == 0)
            {
                Vector2 val = position;
                int num35 = width;
                int num36 = height;
                newColor2 = default(Color);
                int num27 = Dust.NewDust(val, num35, num36, 6, 0f, 0f, 254, newColor2);
                Dust obj3 = Main.dust[num27];
                obj3.velocity *= 0f;
            }
            position -= netOffset;
        }
    }
References Terraria.Entity.active, Terraria.Lighting.AddLight(), Terraria.NPC.ai, Terraria.NPC.catchItem, Terraria.Entity.Center, Terraria.Dust.CloneDust(), Terraria.NPC.collideX, Terraria.Entity.direction, Terraria.Entity.DirectionFrom(), Terraria.NPC.dontTakeDamage, Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Utils.GetLerpValue(), Terraria.NPC.GetTargetData(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Entity.height, Terraria.Main.hslToRgb(), Terraria.NPC.localAI, Terraria.Main.netMode, Terraria.NPC.netOffset, Terraria.NPC.netUpdate, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.npc, Terraria.NPC.Opacity, Terraria.Main.player, Terraria.Dust.position, Terraria.Entity.position, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Dust.scale, Terraria.NPC.scale, Terraria.NetMessage.SendData(), Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.NPC.type, Terraria.Entity.velocity, Terraria.Entity.whoAmI, Terraria.Entity.width, and Terraria.Player.ZoneHallow.
Referenced by Terraria.NPC.VanillaAI_Inner().