TModLoader: Terraria.NPC.BeHurtByOtherNPC
BeHurtByOtherNPC()
void Terraria.NPC.BeHurtByOtherNPC (int npcIndex, NPC thatNPC) inline private
    {
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        int num = 30;
        if (type == 548)
        {
            num = 20;
        }
        int num3 = 6;
        int num4 = ((!(thatNPC.Center.X > base.Center.X)) ? 1 : (-1));
        HitModifiers modifiers = GetIncomingStrikeModifiers(DamageClass.Default, num4);
        NPCLoader.ModifyHitNPC(thatNPC, this, ref modifiers);
        HitInfo strike = modifiers.ToHitInfo(thatNPC.damage, crit: false, num3, damageVariation: true);
        double num5 = StrikeNPC(strike, fromNet: false, noPlayerInteraction: true);
        if (Main.netMode != 0)
        {
            NetMessage.SendStrikeNPC(this, in strike);
        }
        netUpdate = true;
        immune[255] = num;
        NPCLoader.OnHitNPC(thatNPC, this, in strike);
        int num2 = strike.SourceDamage;
        if (dryadWard)
        {
            num2 = (int)num5 / 3;
            num3 = 6;
            num4 *= -1;
            thatNPC.StrikeNPCNoInteraction(num2, num3, num4);
            if (Main.netMode != 0)
            {
                NetMessage.SendData(28, -1, -1, null, npcIndex, num2, num3, num4);
            }
            thatNPC.netUpdate = true;
            thatNPC.immune[255] = num;
        }
        if (NPCID.Sets.HurtingBees[thatNPC.type])
        {
            num2 = damage;
            num3 = 6;
            num4 *= -1;
            thatNPC.StrikeNPCNoInteraction(num2, num3, num4);
            if (Main.netMode != 0)
            {
                NetMessage.SendData(28, -1, -1, null, npcIndex, num2, num3, num4);
            }
            thatNPC.netUpdate = true;
            thatNPC.immune[255] = num;
        }
    }
References Terraria.ModLoader.DamageClass.Default, Terraria.ID.NPCID.Sets.HurtingBees, Terraria.ModLoader.NPCLoader.ModifyHitNPC(), Terraria.Main.netMode, Terraria.ModLoader.NPCLoader.OnHitNPC(), Terraria.NetMessage.SendData(), and Terraria.NetMessage.SendStrikeNPC().