TModLoader: Terraria.NPC.AI_007_TownEntities
AI_007_TownEntities()
void Terraria.NPC.AI_007_TownEntities () inline private
Definition at line 56255 of file NPC.cs.
    {
        //IL_0ac5: Unknown result type (might be due to invalid IL or missing references)
        //IL_066c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0671: Unknown result type (might be due to invalid IL or missing references)
        //IL_069a: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0607: Unknown result type (might be due to invalid IL or missing references)
        //IL_0730: Unknown result type (might be due to invalid IL or missing references)
        //IL_0732: Unknown result type (might be due to invalid IL or missing references)
        //IL_0746: Unknown result type (might be due to invalid IL or missing references)
        //IL_074b: Unknown result type (might be due to invalid IL or missing references)
        //IL_075a: Unknown result type (might be due to invalid IL or missing references)
        //IL_075f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0773: Unknown result type (might be due to invalid IL or missing references)
        //IL_0789: Unknown result type (might be due to invalid IL or missing references)
        //IL_078f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0791: Unknown result type (might be due to invalid IL or missing references)
        //IL_079e: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0661: Unknown result type (might be due to invalid IL or missing references)
        //IL_0666: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d24: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_090d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0912: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0809: Unknown result type (might be due to invalid IL or missing references)
        //IL_080b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0813: Unknown result type (might be due to invalid IL or missing references)
        //IL_0815: Unknown result type (might be due to invalid IL or missing references)
        //IL_0833: Unknown result type (might be due to invalid IL or missing references)
        //IL_0839: Unknown result type (might be due to invalid IL or missing references)
        //IL_083b: Unknown result type (might be due to invalid IL or missing references)
        //IL_084a: Unknown result type (might be due to invalid IL or missing references)
        //IL_084f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0989: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1008: Unknown result type (might be due to invalid IL or missing references)
        //IL_100d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1011: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c50: Unknown result type (might be due to invalid IL or missing references)
        //IL_516e: Unknown result type (might be due to invalid IL or missing references)
        //IL_11a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_688f: Unknown result type (might be due to invalid IL or missing references)
        //IL_5247: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f62: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f67: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f71: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f76: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f80: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f87: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_68dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fc6: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_52b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_52b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1236: Unknown result type (might be due to invalid IL or missing references)
        //IL_1241: Unknown result type (might be due to invalid IL or missing references)
        //IL_52ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_52dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_196d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2230: Unknown result type (might be due to invalid IL or missing references)
        //IL_223a: Unknown result type (might be due to invalid IL or missing references)
        //IL_223f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3154: Unknown result type (might be due to invalid IL or missing references)
        //IL_3166: Unknown result type (might be due to invalid IL or missing references)
        //IL_3108: Unknown result type (might be due to invalid IL or missing references)
        //IL_311a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3129: Unknown result type (might be due to invalid IL or missing references)
        //IL_546b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_50e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_50e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_50ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_50ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_50f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_50f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_50fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_5105: Unknown result type (might be due to invalid IL or missing references)
        //IL_419a: Unknown result type (might be due to invalid IL or missing references)
        //IL_41a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_41ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_41b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_41b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_41ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_41c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_35e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_35e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_35ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_41eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_41f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_41f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_4200: Unknown result type (might be due to invalid IL or missing references)
        //IL_4216: Unknown result type (might be due to invalid IL or missing references)
        //IL_4226: Unknown result type (might be due to invalid IL or missing references)
        //IL_422d: Unknown result type (might be due to invalid IL or missing references)
        //IL_36b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_59c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_36c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_360b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3626: Unknown result type (might be due to invalid IL or missing references)
        //IL_3643: Unknown result type (might be due to invalid IL or missing references)
        //IL_3648: Unknown result type (might be due to invalid IL or missing references)
        //IL_364d: Unknown result type (might be due to invalid IL or missing references)
        //IL_3652: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ff3: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ff9: Unknown result type (might be due to invalid IL or missing references)
        //IL_5db9: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dbe: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dcd: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dd7: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dd9: Unknown result type (might be due to invalid IL or missing references)
        //IL_5de0: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ae9: Unknown result type (might be due to invalid IL or missing references)
        //IL_59d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_59e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_3e94: Unknown result type (might be due to invalid IL or missing references)
        //IL_3e99: Unknown result type (might be due to invalid IL or missing references)
        //IL_36e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_36ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_36f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_36f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_3705: Unknown result type (might be due to invalid IL or missing references)
        //IL_370a: Unknown result type (might be due to invalid IL or missing references)
        //IL_370f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3670: Unknown result type (might be due to invalid IL or missing references)
        //IL_368b: Unknown result type (might be due to invalid IL or missing references)
        //IL_36a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_36ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_36b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_36b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_601c: Unknown result type (might be due to invalid IL or missing references)
        //IL_6030: Unknown result type (might be due to invalid IL or missing references)
        //IL_6035: Unknown result type (might be due to invalid IL or missing references)
        //IL_603a: Unknown result type (might be due to invalid IL or missing references)
        //IL_603f: Unknown result type (might be due to invalid IL or missing references)
        //IL_6041: Unknown result type (might be due to invalid IL or missing references)
        //IL_6048: Unknown result type (might be due to invalid IL or missing references)
        //IL_5cde: Unknown result type (might be due to invalid IL or missing references)
        //IL_5af9: Unknown result type (might be due to invalid IL or missing references)
        //IL_5b02: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d45: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d52: Unknown result type (might be due to invalid IL or missing references)
        //IL_4aa9: Unknown result type (might be due to invalid IL or missing references)
        //IL_4aae: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ab2: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ab9: Unknown result type (might be due to invalid IL or missing references)
        //IL_4abe: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ac1: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ac6: Unknown result type (might be due to invalid IL or missing references)
        //IL_4acd: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ad4: Unknown result type (might be due to invalid IL or missing references)
        //IL_455f: Unknown result type (might be due to invalid IL or missing references)
        //IL_4564: Unknown result type (might be due to invalid IL or missing references)
        //IL_4035: Unknown result type (might be due to invalid IL or missing references)
        //IL_403a: Unknown result type (might be due to invalid IL or missing references)
        //IL_403f: Unknown result type (might be due to invalid IL or missing references)
        //IL_4041: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ec7: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ea9: Unknown result type (might be due to invalid IL or missing references)
        //IL_3eb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ebb: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ec0: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ec5: Unknown result type (might be due to invalid IL or missing references)
        //IL_37fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_3811: Unknown result type (might be due to invalid IL or missing references)
        //IL_3821: Unknown result type (might be due to invalid IL or missing references)
        //IL_3828: Unknown result type (might be due to invalid IL or missing references)
        //IL_605b: Unknown result type (might be due to invalid IL or missing references)
        //IL_6062: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ee8: Unknown result type (might be due to invalid IL or missing references)
        //IL_5eef: Unknown result type (might be due to invalid IL or missing references)
        //IL_5cee: Unknown result type (might be due to invalid IL or missing references)
        //IL_5cf7: Unknown result type (might be due to invalid IL or missing references)
        //IL_45bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_4574: Unknown result type (might be due to invalid IL or missing references)
        //IL_458f: Unknown result type (might be due to invalid IL or missing references)
        //IL_45ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_45b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_45b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_45bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_404f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ed0: Unknown result type (might be due to invalid IL or missing references)
        //IL_379f: Unknown result type (might be due to invalid IL or missing references)
        //IL_37b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_37c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_37cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_3739: Unknown result type (might be due to invalid IL or missing references)
        //IL_374f: Unknown result type (might be due to invalid IL or missing references)
        //IL_375f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3766: Unknown result type (might be due to invalid IL or missing references)
        //IL_60b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_60bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_55b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ed6: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ede: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ee3: Unknown result type (might be due to invalid IL or missing references)
        //IL_4eeb: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ef5: Unknown result type (might be due to invalid IL or missing references)
        //IL_4efa: Unknown result type (might be due to invalid IL or missing references)
        //IL_45c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_4064: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ef7: Unknown result type (might be due to invalid IL or missing references)
        //IL_3efb: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f00: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f02: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f13: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f18: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f71: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f85: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f92: Unknown result type (might be due to invalid IL or missing references)
        //IL_55cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_45ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_45f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_45f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_45f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_4609: Unknown result type (might be due to invalid IL or missing references)
        //IL_460e: Unknown result type (might be due to invalid IL or missing references)
        //IL_4613: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fa4: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fba: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fca: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f50: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f60: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f67: Unknown result type (might be due to invalid IL or missing references)
        //IL_57cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_55df: Unknown result type (might be due to invalid IL or missing references)
        //IL_55e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_57e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2925: Unknown result type (might be due to invalid IL or missing references)
        //IL_293e: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e47: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e56: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e60: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e65: Unknown result type (might be due to invalid IL or missing references)
        //IL_5eb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_5eba: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ebf: Unknown result type (might be due to invalid IL or missing references)
        //IL_57f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_57fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_471b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4728: Unknown result type (might be due to invalid IL or missing references)
        //IL_4732: Unknown result type (might be due to invalid IL or missing references)
        //IL_4737: Unknown result type (might be due to invalid IL or missing references)
        //IL_4744: Unknown result type (might be due to invalid IL or missing references)
        //IL_4758: Unknown result type (might be due to invalid IL or missing references)
        //IL_475d: Unknown result type (might be due to invalid IL or missing references)
        //IL_4767: Unknown result type (might be due to invalid IL or missing references)
        //IL_476c: Unknown result type (might be due to invalid IL or missing references)
        //IL_4771: Unknown result type (might be due to invalid IL or missing references)
        //IL_4656: Unknown result type (might be due to invalid IL or missing references)
        //IL_465b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4664: Unknown result type (might be due to invalid IL or missing references)
        //IL_467a: Unknown result type (might be due to invalid IL or missing references)
        //IL_468a: Unknown result type (might be due to invalid IL or missing references)
        //IL_4691: Unknown result type (might be due to invalid IL or missing references)
        //IL_4699: Unknown result type (might be due to invalid IL or missing references)
        //IL_46a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_62d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_62e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_618e: Unknown result type (might be due to invalid IL or missing references)
        //IL_61a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_4a2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_4a44: Unknown result type (might be due to invalid IL or missing references)
        //IL_4a54: Unknown result type (might be due to invalid IL or missing references)
        //IL_4a5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_49b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_49c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_49d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_49dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_488b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4898: Unknown result type (might be due to invalid IL or missing references)
        //IL_48ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_48b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_48bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_48c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_48c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_3cf3: Unknown result type (might be due to invalid IL or missing references)
        //IL_6465: Unknown result type (might be due to invalid IL or missing references)
        //IL_6474: Unknown result type (might be due to invalid IL or missing references)
        //IL_61be: Unknown result type (might be due to invalid IL or missing references)
        //IL_4e0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_480f: Unknown result type (might be due to invalid IL or missing references)
        //IL_4816: Unknown result type (might be due to invalid IL or missing references)
        //IL_47e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_47ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_65e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_65f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_64bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_64c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_64c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_64c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_6339: Unknown result type (might be due to invalid IL or missing references)
        //IL_6346: Unknown result type (might be due to invalid IL or missing references)
        //IL_62f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_6308: Unknown result type (might be due to invalid IL or missing references)
        //IL_4943: Unknown result type (might be due to invalid IL or missing references)
        //IL_494a: Unknown result type (might be due to invalid IL or missing references)
        //IL_491b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4926: Unknown result type (might be due to invalid IL or missing references)
        //IL_4787: Unknown result type (might be due to invalid IL or missing references)
        //IL_4794: Unknown result type (might be due to invalid IL or missing references)
        //IL_479e: Unknown result type (might be due to invalid IL or missing references)
        //IL_47a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_47b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_47c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_47c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_47d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_47d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_47dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_6785: Unknown result type (might be due to invalid IL or missing references)
        //IL_6794: Unknown result type (might be due to invalid IL or missing references)
        //IL_64da: Unknown result type (might be due to invalid IL or missing references)
        //IL_6488: Unknown result type (might be due to invalid IL or missing references)
        //IL_6497: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_4e24: Unknown result type (might be due to invalid IL or missing references)
        //IL_4e37: Unknown result type (might be due to invalid IL or missing references)
        //IL_48da: Unknown result type (might be due to invalid IL or missing references)
        //IL_48e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_48fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_4900: Unknown result type (might be due to invalid IL or missing references)
        //IL_490a: Unknown result type (might be due to invalid IL or missing references)
        //IL_490f: Unknown result type (might be due to invalid IL or missing references)
        //IL_4914: Unknown result type (might be due to invalid IL or missing references)
        //IL_660a: Unknown result type (might be due to invalid IL or missing references)
        //IL_6619: Unknown result type (might be due to invalid IL or missing references)
        //IL_6517: Unknown result type (might be due to invalid IL or missing references)
        //IL_67a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_67b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f72: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f81: Unknown result type (might be due to invalid IL or missing references)
        ShimmeredTownNPCs[type] = IsShimmerVariant;
        if (type == 441 && GivenName == "Andrew")
        {
            defDefense = 200;
        }
        int num = 300;
        if (type == 638 || type == 656 || NPCID.Sets.IsTownSlime[type])
        {
            num = 0;
        }
        bool flag = Main.raining;
        if (!Main.dayTime)
        {
            flag = true;
        }
        if (Main.eclipse)
        {
            flag = true;
        }
        if (Main.slimeRain)
        {
            flag = true;
        }
        float num42 = 1f;
        if (Main.masterMode)
        {
            defense = (dryadWard ? (defDefense + 14) : defDefense);
        }
        else if (Main.expertMode)
        {
            defense = (dryadWard ? (defDefense + 10) : defDefense);
        }
        else
        {
            defense = (dryadWard ? (defDefense + 6) : defDefense);
        }
        if (isLikeATownNPC)
        {
            if (combatBookWasUsed)
            {
                num42 += 0.2f;
                defense += 6;
            }
            if (combatBookVolumeTwoWasUsed)
            {
                num42 += 0.2f;
                defense += 6;
            }
            if (downedBoss1)
            {
                num42 += 0.1f;
                defense += 3;
            }
            if (downedBoss2)
            {
                num42 += 0.1f;
                defense += 3;
            }
            if (downedBoss3)
            {
                num42 += 0.1f;
                defense += 3;
            }
            if (downedQueenBee)
            {
                num42 += 0.1f;
                defense += 3;
            }
            if (Main.hardMode)
            {
                num42 += 0.4f;
                defense += 12;
            }
            if (downedQueenSlime)
            {
                num42 += 0.15f;
                defense += 6;
            }
            if (downedMechBoss1)
            {
                num42 += 0.15f;
                defense += 6;
            }
            if (downedMechBoss2)
            {
                num42 += 0.15f;
                defense += 6;
            }
            if (downedMechBoss3)
            {
                num42 += 0.15f;
                defense += 6;
            }
            if (downedPlantBoss)
            {
                num42 += 0.15f;
                defense += 8;
            }
            if (downedEmpressOfLight)
            {
                num42 += 0.15f;
                defense += 8;
            }
            if (downedGolemBoss)
            {
                num42 += 0.15f;
                defense += 8;
            }
            if (downedAncientCultist)
            {
                num42 += 0.15f;
                defense += 8;
            }
            NPCLoader.BuffTownNPC(ref num42, ref defense);
        }
        if (type == 142 && Main.netMode != 1 && !Main.xMas)
        {
            StrikeNPCNoInteraction(9999, 0f, 0);
            if (Main.netMode == 2)
            {
                NetMessage.SendData(28, -1, -1, null, whoAmI, 9999f);
            }
        }
        if ((type == 148 || type == 149) && localAI[0] == 0f)
        {
            localAI[0] = Main.rand.Next(1, 5);
        }
        if (type == 124)
        {
            int num53 = lazyNPCOwnedProjectileSearchArray[whoAmI];
            bool flag12 = false;
            if (Main.projectile.IndexInRange(num53))
            {
                Projectile projectile = Main.projectile[num53];
                if (projectile.active && projectile.type == 582 && projectile.ai[1] == (float)whoAmI)
                {
                    flag12 = true;
                }
            }
            localAI[0] = flag12.ToInt();
        }
        if ((type == 362 || type == 364 || type == 602 || type == 608) && Main.netMode != 1 && (velocity.Y > 4f || velocity.Y < -4f || wet))
        {
            int num64 = direction;
            Transform(type + 1);
            TargetClosest();
            direction = num64;
            netUpdate = true;
            return;
        }
        switch (type)
        {
        case 588:
            savedGolfer = true;
            break;
        case 441:
            savedTaxCollector = true;
            break;
        case 107:
            savedGoblin = true;
            break;
        case 108:
            savedWizard = true;
            break;
        case 124:
            savedMech = true;
            break;
        case 353:
            savedStylist = true;
            break;
        case 369:
            savedAngler = true;
            break;
        case 550:
            savedBartender = true;
            break;
        }
        dontTakeDamage = false;
        Color newColor;
        if (ai[0] == 25f)
        {
            dontTakeDamage = true;
            if (ai[1] == 0f)
            {
                velocity.X = 0f;
            }
            shimmerWet = false;
            wet = false;
            lavaWet = false;
            honeyWet = false;
            if (ai[1] == 0f && Main.netMode == 1)
            {
                return;
            }
            if (ai[1] == 0f && ai[2] < 1f)
            {
                AI_007_TownEntities_Shimmer_TeleportToLandingSpot();
            }
            if (ai[2] > 0f)
            {
                ai[2] -= 1f;
                if (ai[2] <= 0f)
                {
                    ai[1] = 1f;
                }
                return;
            }
            ai[1] += 1f;
            if (ai[1] >= 30f)
            {
                if (!Collision.WetCollision(position, width, height))
                {
                    shimmerTransparency = MathHelper.Clamp(shimmerTransparency - 1f / 60f, 0f, 1f);
                }
                else
                {
                    ai[1] = 30f;
                }
                velocity = new Vector2(0f, -4f * shimmerTransparency);
            }
            Rectangle hitbox = base.Hitbox;
            hitbox.Y += 20;
            hitbox.Height -= 20;
            float num75 = Main.rand.NextFloatDirection();
            Vector2 center = base.Center;
            newColor = Main.hslToRgb((float)Main.timeForVisualEffects / 360f % 1f, 0.6f, 0.65f);
            Lighting.AddLight(center, ((Color)(ref newColor)).ToVector3() * Utils.Remap(ai[1], 30f, 90f, 0f, 0.7f));
            if (Main.rand.NextFloat() > Utils.Remap(ai[1], 30f, 60f, 1f, 0.5f))
            {
                Vector2 val = Main.rand.NextVector2FromRectangle(hitbox) + Main.rand.NextVector2Circular(8f, 0f) + new Vector2(0f, 4f);
                Vector2? val2 = Utils.RotatedBy(new Vector2(0f, -2f), num75 * ((float)Math.PI * 2f) * 0.11f);
                newColor = default(Color);
                Dust.NewDustPerfect(val, 309, val2, 0, newColor, 1.7f - Math.Abs(num75) * 1.3f);
            }
            if (ai[1] > 60f && Main.rand.Next(15) == 0)
            {
                for (int i = 0; i < 3; i++)
                {
                    Vector2 vector = Main.rand.NextVector2FromRectangle(base.Hitbox);
                    ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.ShimmerBlock, new ParticleOrchestraSettings
                    {
                        PositionInWorld = vector,
                        MovementVector = DirectionTo(vector).RotatedBy((float)Math.PI * 9f / 20f * (float)(Main.rand.Next(2) * 2 - 1)) * Main.rand.NextFloat()
                    });
                }
            }
            TargetClosest();
            NPCAimedTarget targetData = GetTargetData();
            if (ai[1] >= 75f && shimmerTransparency <= 0f && Main.netMode != 1)
            {
                ai[0] = 0f;
                ai[1] = 0f;
                ai[2] = 0f;
                ai[3] = 0f;
                Math.Sign(targetData.Center.X - base.Center.X);
                velocity = new Vector2(0f, -4f);
                localAI[0] = 0f;
                localAI[1] = 0f;
                localAI[2] = 0f;
                localAI[3] = 0f;
                netUpdate = true;
                townNpcVariationIndex = ((townNpcVariationIndex != 1) ? 1 : 0);
                NetMessage.SendData(56, -1, -1, null, whoAmI);
                Teleport(position, 12);
                ParticleOrchestrator.BroadcastParticleSpawn(ParticleOrchestraType.ShimmerTownNPC, new ParticleOrchestraSettings
                {
                    PositionInWorld = base.Center
                });
            }
            return;
        }
        if (type >= 0 && NPCID.Sets.TownCritter[type] && target == 255)
        {
            TargetClosest();
            if (position.X < Main.player[target].position.X)
            {
                direction = 1;
                spriteDirection = direction;
            }
            if (position.X > Main.player[target].position.X)
            {
                direction = -1;
                spriteDirection = direction;
            }
            if (homeTileX == -1)
            {
                UpdateHomeTileState(homeless, (int)((position.X + (float)(width / 2)) / 16f), homeTileY);
            }
        }
        else if (homeTileX == -1 && homeTileY == -1 && velocity.Y == 0f && !shimmering)
        {
            UpdateHomeTileState(homeless, (int)base.Center.X / 16, (int)(position.Y + (float)height + 4f) / 16);
        }
        bool flag23 = false;
        int num86 = (int)(position.X + (float)(width / 2)) / 16;
        int num97 = (int)(position.Y + (float)height + 1f) / 16;
        AI_007_FindGoodRestingSpot(num86, num97, out var floorX, out var floorY);
        if (type == 441)
        {
            taxCollector = true;
        }
        directionY = -1;
        if (direction == 0)
        {
            direction = 1;
        }
        if (ai[0] != 24f)
        {
            for (int j = 0; j < 255; j++)
            {
                if (Main.player[j].active && Main.player[j].talkNPC == whoAmI)
                {
                    flag23 = true;
                    if (ai[0] != 0f)
                    {
                        netUpdate = true;
                    }
                    ai[0] = 0f;
                    ai[1] = 300f;
                    localAI[3] = 100f;
                    if (Main.player[j].position.X + (float)(Main.player[j].width / 2) < position.X + (float)(width / 2))
                    {
                        direction = -1;
                    }
                    else
                    {
                        direction = 1;
                    }
                }
            }
        }
        if (ai[3] == 1f)
        {
            life = -1;
            HitEffect();
            active = false;
            netUpdate = true;
            if (type == 37)
            {
                SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
            }
            return;
        }
        if (type == 37 && Main.netMode != 1)
        {
            UpdateHomeTileState(homeless: false, Main.dungeonX, Main.dungeonY);
            if (downedBoss3)
            {
                ai[3] = 1f;
                netUpdate = true;
            }
        }
        if (type == 368)
        {
            homeless = true;
            if (!Main.dayTime)
            {
                if (!shimmering)
                {
                    UpdateHomeTileState(homeless, (int)(base.Center.X / 16f), (int)(position.Y + (float)height + 2f) / 16);
                }
                if (!flag23 && ai[0] == 0f)
                {
                    ai[0] = 1f;
                    ai[1] = 200f;
                }
                flag = false;
            }
        }
        if (type == 369 && homeless && wet)
        {
            if (base.Center.X / 16f < 380f || base.Center.X / 16f > (float)(Main.maxTilesX - 380))
            {
                UpdateHomeTileState(homeless, Main.spawnTileX, Main.spawnTileY);
                ai[0] = 1f;
                ai[1] = 200f;
            }
            if (position.X / 16f < 300f)
            {
                direction = 1;
            }
            else if (position.X / 16f > (float)(Main.maxTilesX - 300))
            {
                direction = -1;
            }
        }
        if (!WorldGen.InWorld(num86, num97) || (Main.netMode == 1 && !Main.sectionManager.TileLoaded(num86, num97)))
        {
            return;
        }
        if (!homeless && Main.netMode != 1 && townNPC && (flag || (type == 37 && Main.tileDungeon[Main.tile[num86, num97].type])) && !AI_007_TownEntities_IsInAGoodRestingSpot(num86, num97, floorX, floorY))
        {
            bool flag27 = true;
            Rectangle rectangle = default(Rectangle);
            for (int k = 0; k < 2; k++)
            {
                if (!flag27)
                {
                    break;
                }
                ((Rectangle)(ref rectangle))._002Ector((int)(position.X + (float)(width / 2) - (float)(sWidth / 2) - (float)safeRangeX), (int)(position.Y + (float)(height / 2) - (float)(sHeight / 2) - (float)safeRangeY), sWidth + safeRangeX * 2, sHeight + safeRangeY * 2);
                if (k == 1)
                {
                    ((Rectangle)(ref rectangle))._002Ector(floorX * 16 + 8 - sWidth / 2 - safeRangeX, floorY * 16 + 8 - sHeight / 2 - safeRangeY, sWidth + safeRangeX * 2, sHeight + safeRangeY * 2);
                }
                for (int l = 0; l < 255; l++)
                {
                    if (Main.player[l].active)
                    {
                        Rectangle val3 = new Rectangle((int)Main.player[l].position.X, (int)Main.player[l].position.Y, Main.player[l].width, Main.player[l].height);
                        if (((Rectangle)(ref val3)).Intersects(rectangle))
{
                            flag27 = false;
                            break;
                        }
                    }
                }
            }
            if (flag27)
            {
                AI_007_TownEntities_TeleportToHome(floorX, floorY);
            }
        }
        bool flag28 = type == 300 || type == 447 || type == 610;
        bool flag29 = type == 616 || type == 617 || type == 625;
        bool flag30 = type == 361 || type == 445 || type == 687;
        bool flag31 = NPCID.Sets.IsTownSlime[type];
        _ = NPCID.Sets.IsTownPet[type];
        bool flag32 = flag29 || flag30;
        bool flag2 = flag29 || flag30;
        bool flag3 = flag31;
        bool flag4 = flag31;
        float num108 = 200f;
        if (NPCID.Sets.DangerDetectRange[type] != -1)
        {
            num108 = NPCID.Sets.DangerDetectRange[type];
        }
        bool flag5 = false;
        bool flag6 = false;
        float num119 = -1f;
        float num2 = -1f;
        int num13 = 0;
        int num24 = -1;
        int num35 = -1;
        bool keepwalking4;
        if (!flag29 && Main.netMode != 1 && !flag23)
        {
            for (int m = 0; m < 200; m++)
            {
                if (!Main.npc[m].active || Main.npc[m].friendly || Main.npc[m].damage <= 0 || !(Main.npc[m].Distance(base.Center) < num108) || (type == 453 && NPCID.Sets.Skeletons[Main.npc[m].type]) || (!Main.npc[m].noTileCollide && !Collision.CanHit(base.Center, 0, 0, Main.npc[m].Center, 0, 0)) || !NPCLoader.CanHitNPC(Main.npc[m], this))
                {
                    continue;
                }
                bool flag7 = Main.npc[m].CanBeChasedBy(this);
                flag5 = true;
                float num36 = Main.npc[m].Center.X - base.Center.X;
                if (type == 614)
                {
                    if (num36 < 0f && (num119 == -1f || num36 > num119))
                    {
                        num2 = num36;
                        num35 = m;
                    }
                    if (num36 > 0f && (num2 == -1f || num36 < num2))
                    {
                        num119 = num36;
                        num24 = m;
                    }
                    continue;
                }
                if (num36 < 0f && (num119 == -1f || num36 > num119))
                {
                    num119 = num36;
                    if (flag7)
                    {
                        num24 = m;
                    }
                }
                if (num36 > 0f && (num2 == -1f || num36 < num2))
                {
                    num2 = num36;
                    if (flag7)
                    {
                        num35 = m;
                    }
                }
            }
            if (flag5)
            {
                num13 = ((num119 == -1f) ? 1 : ((num2 != -1f) ? (num2 < 0f - num119).ToDirectionInt() : (-1)));
                float num37 = 0f;
                if (num119 != -1f)
                {
                    num37 = 0f - num119;
                }
                if (num37 == 0f || (num2 < num37 && num2 > 0f))
                {
                    num37 = num2;
                }
                if (ai[0] == 8f)
                {
                    if (direction == -num13)
                    {
                        ai[0] = 1f;
                        ai[1] = 300 + Main.rand.Next(300);
                        ai[2] = 0f;
                        localAI[3] = 0f;
                        netUpdate = true;
                    }
                }
                else if (ai[0] != 10f && ai[0] != 12f && ai[0] != 13f && ai[0] != 14f && ai[0] != 15f)
                {
                    if (NPCID.Sets.PrettySafe[type] != -1 && (float)NPCID.Sets.PrettySafe[type] < num37)
                    {
                        flag5 = false;
                        flag6 = NPCID.Sets.AttackType[type] > -1;
                    }
                    else if (ai[0] != 1f)
                    {
                        int tileX = (int)((position.X + (float)(width / 2) + (float)(15 * direction)) / 16f);
                        int tileY = (int)((position.Y + (float)height - 16f) / 16f);
                        bool currentlyDrowning = wet && !flag32;
                        AI_007_TownEntities_GetWalkPrediction(num86, floorX, flag32, currentlyDrowning, tileX, tileY, out keepwalking4, out var avoidFalling);
                        if (!avoidFalling)
{
                            if (ai[0] == 3f || ai[0] == 4f || ai[0] == 16f || ai[0] == 17f)
{
                                NPC nPC = Main.npc[(int)ai[2]];
                                if (nPC.active)
{
                                    nPC.ai[0] = 1f;
                                    nPC.ai[1] = 120 + Main.rand.Next(120);
                                    nPC.ai[2] = 0f;
                                    nPC.localAI[3] = 0f;
                                    nPC.direction = -num13;
                                    nPC.netUpdate = true;
                                }
                            }
                            ai[0] = 1f;
                            ai[1] = 120 + Main.rand.Next(120);
                            ai[2] = 0f;
                            localAI[3] = 0f;
                            direction = -num13;
                            netUpdate = true;
                        }
                    }
                    else if (ai[0] == 1f && direction != -num13)
                    {
                        direction = -num13;
                        netUpdate = true;
                    }
                }
            }
        }
        if (ai[0] == 0f)
        {
            if (localAI[3] > 0f)
            {
                localAI[3] -= 1f;
            }
            int num38 = 120;
            if (type == 638)
            {
                num38 = 60;
            }
            if ((flag30 || flag31) && wet)
            {
                ai[0] = 1f;
                ai[1] = 200 + Main.rand.Next(500, 700);
                ai[2] = 0f;
                localAI[3] = 0f;
                netUpdate = true;
            }
            else if (flag && !flag23 && !NPCID.Sets.TownCritter[type])
            {
                if (Main.netMode != 1)
                {
                    if (num86 == floorX && num97 == floorY)
                    {
                        if (velocity.X != 0f)
{
                            netUpdate = true;
                        }
                        if (velocity.X > 0.1f)
{
                            velocity.X -= 0.1f;
                        }
                        else if (velocity.X < -0.1f)
{
                            velocity.X += 0.1f;
                        }
                        else
{
                            velocity.X = 0f;
                            AI_007_TryForcingSitting(floorX, floorY);
                        }
                        if (NPCID.Sets.IsTownPet[type])
{
                            AI_007_AttemptToPlayIdleAnimationsForPets(num38 * 4);
                        }
                    }
                    else
                    {
                        if (num86 > floorX)
{
                            direction = -1;
                        }
                        else
{
                            direction = 1;
                        }
                        ai[0] = 1f;
                        ai[1] = 200 + Main.rand.Next(200);
                        ai[2] = 0f;
                        localAI[3] = 0f;
                        netUpdate = true;
                    }
                }
            }
            else
            {
                if (flag28)
                {
                    velocity.X *= 0.5f;
                }
                if (velocity.X > 0.1f)
                {
                    velocity.X -= 0.1f;
                }
                else if (velocity.X < -0.1f)
                {
                    velocity.X += 0.1f;
                }
                else
                {
                    velocity.X = 0f;
                }
                if (Main.netMode != 1)
                {
                    if (!flag23 && NPCID.Sets.IsTownPet[type] && ai[1] >= 100f && ai[1] <= 150f)
                    {
                        AI_007_AttemptToPlayIdleAnimationsForPets(num38);
                    }
                    if (ai[1] > 0f)
                    {
                        ai[1] -= 1f;
                    }
                    bool flag8 = true;
                    int tileX2 = (int)((position.X + (float)(width / 2) + (float)(15 * direction)) / 16f);
                    int tileY2 = (int)((position.Y + (float)height - 16f) / 16f);
                    bool currentlyDrowning2 = wet && !flag32;
                    AI_007_TownEntities_GetWalkPrediction(num86, floorX, flag32, currentlyDrowning2, tileX2, tileY2, out keepwalking4, out var avoidFalling2);
                    if (wet && !flag32)
                    {
                        bool currentlyDrowning3 = Collision.DrownCollision(position, width, height, 1f, includeSlopes: true);
                        if (AI_007_TownEntities_CheckIfWillDrown(currentlyDrowning3))
{
                            ai[0] = 1f;
                            ai[1] = 200 + Main.rand.Next(300);
                            ai[2] = 0f;
                            if (NPCID.Sets.TownCritter[type])
{
                                ai[1] += Main.rand.Next(200, 400);
                            }
                            localAI[3] = 0f;
                            netUpdate = true;
                        }
                    }
                    if (avoidFalling2)
                    {
                        flag8 = false;
                    }
                    if (ai[1] <= 0f)
                    {
                        if (flag8 && !avoidFalling2)
{
                            ai[0] = 1f;
                            ai[1] = 200 + Main.rand.Next(300);
                            ai[2] = 0f;
                            if (NPCID.Sets.TownCritter[type])
{
                                ai[1] += Main.rand.Next(200, 400);
                            }
                            localAI[3] = 0f;
                            netUpdate = true;
                        }
                        else
{
                            direction *= -1;
                            ai[1] = 60 + Main.rand.Next(120);
                            netUpdate = true;
                        }
                    }
                }
            }
            if (Main.netMode != 1 && (!flag || AI_007_TownEntities_IsInAGoodRestingSpot(num86, num97, floorX, floorY)))
            {
                if (num86 < floorX - 25 || num86 > floorX + 25)
                {
                    if (localAI[3] == 0f)
                    {
                        if (num86 < floorX - 50 && direction == -1)
{
                            direction = 1;
                            netUpdate = true;
                        }
                        else if (num86 > floorX + 50 && direction == 1)
{
                            direction = -1;
                            netUpdate = true;
                        }
                    }
                }
                else if (Main.rand.Next(80) == 0 && localAI[3] == 0f)
                {
                    localAI[3] = 200f;
                    direction *= -1;
                    netUpdate = true;
                }
            }
        }
        else if (ai[0] == 1f)
        {
            if (Main.netMode != 1 && flag && AI_007_TownEntities_IsInAGoodRestingSpot(num86, num97, floorX, floorY) && !NPCID.Sets.TownCritter[type])
            {
                ai[0] = 0f;
                ai[1] = 200 + Main.rand.Next(200);
                localAI[3] = 60f;
                netUpdate = true;
            }
            else
            {
                bool flag9 = !flag32 && Collision.DrownCollision(position, width, height, 1f, includeSlopes: true);
                if (!flag9)
                {
                    if (Main.netMode != 1 && !homeless && !Main.tileDungeon[Main.tile[num86, num97].type] && (num86 < floorX - 35 || num86 > floorX + 35))
                    {
                        if (position.X < (float)(floorX * 16) && direction == -1)
{
                            ai[1] -= 5f;
                        }
                        else if (position.X > (float)(floorX * 16) && direction == 1)
{
                            ai[1] -= 5f;
                        }
                    }
                    ai[1] -= 1f;
                }
                if (ai[1] <= 0f)
                {
                    ai[0] = 0f;
                    ai[1] = 300 + Main.rand.Next(300);
                    ai[2] = 0f;
                    if (NPCID.Sets.TownCritter[type])
                    {
                        ai[1] -= Main.rand.Next(100);
                    }
                    else
                    {
                        ai[1] += Main.rand.Next(900);
                    }
                    localAI[3] = 60f;
                    netUpdate = true;
                }
                if (closeDoor && ((position.X + (float)(width / 2)) / 16f > (float)(doorX + 2) || (position.X + (float)(width / 2)) / 16f < (float)(doorX - 2)))
                {
                    Tile tileSafely = Framing.GetTileSafely(doorX, doorY);
                    if (TileLoader.CloseDoorID(tileSafely) >= 0)
                    {
                        if (WorldGen.CloseDoor(doorX, doorY))
{
                            closeDoor = false;
                            NetMessage.SendData(19, -1, -1, null, 1, doorX, doorY, direction);
                        }
                        if ((position.X + (float)(width / 2)) / 16f > (float)(doorX + 4) || (position.X + (float)(width / 2)) / 16f < (float)(doorX - 4) || (position.Y + (float)(height / 2)) / 16f > (float)(doorY + 4) || (position.Y + (float)(height / 2)) / 16f < (float)(doorY - 4))
{
                            closeDoor = false;
                        }
                    }
                    else if (tileSafely.type == 389)
                    {
                        if (WorldGen.ShiftTallGate(doorX, doorY, closing: true))
{
                            closeDoor = false;
                            NetMessage.SendData(19, -1, -1, null, 5, doorX, doorY);
                        }
                        if ((position.X + (float)(width / 2)) / 16f > (float)(doorX + 4) || (position.X + (float)(width / 2)) / 16f < (float)(doorX - 4) || (position.Y + (float)(height / 2)) / 16f > (float)(doorY + 4) || (position.Y + (float)(height / 2)) / 16f < (float)(doorY - 4))
{
                            closeDoor = false;
                        }
                    }
                    else
                    {
                        closeDoor = false;
                    }
                }
                float num39 = 1f;
                float num40 = 0.07f;
                if (type == 614 && flag5)
                {
                    num39 = 1.5f;
                    num40 = 0.1f;
                }
                else if (type == 299 || type == 539 || type == 538 || (type >= 639 && type <= 645))
                {
                    num39 = 1.5f;
                }
                else if (flag29)
                {
                    if (wet)
                    {
                        num40 = 1f;
                        num39 = 2f;
                    }
                    else
                    {
                        num40 = 0.07f;
                        num39 = 0.5f;
                    }
                }
                if (type == 625)
                {
                    if (wet)
                    {
                        num40 = 1f;
                        num39 = 2.5f;
                    }
                    else
                    {
                        num40 = 0.07f;
                        num39 = 0.2f;
                    }
                }
                if (flag28)
                {
                    num39 = 2f;
                    num40 = 1f;
                }
                if (friendly && (flag5 || flag9))
                {
                    num39 = 1.5f;
                    float num41 = 1f - (float)life / (float)lifeMax;
                    num39 += num41 * 0.9f;
                    num40 = 0.1f;
                }
                if (flag3 && wet)
                {
                    num39 = 2f;
                    num40 = 0.2f;
                }
                if (flag30 && wet)
                {
                    if (Math.Abs(velocity.X) < 0.05f && Math.Abs(velocity.Y) < 0.05f)
                    {
                        velocity.X += num39 * 10f * (float)direction;
                    }
                    else
                    {
                        velocity.X *= 0.9f;
                    }
                }
                else if (velocity.X < 0f - num39 || velocity.X > num39)
                {
                    if (velocity.Y == 0f)
                    {
                        velocity *= 0.8f;
                    }
                }
                else if (velocity.X < num39 && direction == 1)
                {
                    velocity.X += num40;
                    if (velocity.X > num39)
                    {
                        velocity.X = num39;
                    }
                }
                else if (velocity.X > 0f - num39 && direction == -1)
                {
                    velocity.X -= num40;
                    if (velocity.X > num39)
                    {
                        velocity.X = num39;
                    }
                }
                bool flag10 = true;
                if ((float)(homeTileY * 16 - 32) > position.Y)
                {
                    flag10 = false;
                }
                if (!flag10 && velocity.Y == 0f)
                {
                    Collision.StepDown(ref position, ref velocity, width, height, ref stepSpeed, ref gfxOffY);
                }
                if (velocity.Y >= 0f)
                {
                    Collision.StepUp(ref position, ref velocity, width, height, ref stepSpeed, ref gfxOffY, 1, flag10, 1);
                }
                if (velocity.Y == 0f)
                {
                    int num43 = (int)((position.X + (float)(width / 2) + (float)(15 * direction)) / 16f);
                    int num44 = (int)((position.Y + (float)height - 16f) / 16f);
                    int num45 = 180;
                    AI_007_TownEntities_GetWalkPrediction(num86, floorX, flag32, flag9, num43, num44, out var keepwalking3, out var avoidFalling3);
                    bool flag11 = false;
                    bool flag13 = false;
                    if (wet && !flag32 && townNPC && (flag13 = AI_007_TownEntities_CheckIfWillDrown(flag9)) && localAI[3] <= 0f)
                    {
                        avoidFalling3 = true;
                        localAI[3] = num45;
                        int num46 = 0;
                        for (int n = 0; n <= 10 && Framing.GetTileSafely(num43 - direction, num44 - n).liquid != 0; n++)
{
                            num46++;
                        }
                        float num47 = 0.3f;
                        float num48 = (float)Math.Sqrt((float)(num46 * 16 + 16) * 2f * num47);
                        if (num48 > 26f)
{
                            num48 = 26f;
                        }
                        velocity.Y = 0f - num48;
                        localAI[3] = position.X;
                        flag11 = true;
                    }
                    if (avoidFalling3 && !flag11)
                    {
                        int num49 = (int)((position.X + (float)(width / 2)) / 16f);
                        int num50 = 0;
                        for (int num51 = -1; num51 <= 1; num51++)
{
                            Tile tileSafely2 = Framing.GetTileSafely(num49 + num51, num44 + 1);
                            if (tileSafely2.nactive() && Main.tileSolid[tileSafely2.type])
{
                                num50++;
                            }
                        }
                        if (num50 <= 2)
{
                            if (velocity.X != 0f)
{
                                netUpdate = true;
                            }
                            keepwalking3 = (avoidFalling3 = false);
                            ai[0] = 0f;
                            ai[1] = 50 + Main.rand.Next(50);
                            ai[2] = 0f;
                            localAI[3] = 40f;
                        }
                    }
                    if (position.X == localAI[3] && !flag11)
                    {
                        direction *= -1;
                        netUpdate = true;
                        localAI[3] = num45;
                    }
                    if (flag9 && !flag11)
                    {
                        if (localAI[3] > (float)num45)
{
                            localAI[3] = num45;
                        }
                        if (localAI[3] > 0f)
{
                            localAI[3] -= 1f;
                        }
                    }
                    else
                    {
                        localAI[3] = -1f;
                    }
                    Tile tileSafely3 = Framing.GetTileSafely(num43, num44);
                    Tile tileSafely4 = Framing.GetTileSafely(num43, num44 - 1);
                    Tile tileSafely5 = Framing.GetTileSafely(num43, num44 - 2);
                    bool flag14 = height / 16 < 3;
                    if ((townNPC || NPCID.Sets.AllowDoorInteraction[type]) && tileSafely5.nactive() && (TileLoader.IsClosedDoor(tileSafely5) || tileSafely5.type == 388) && (Main.rand.Next(10) == 0 || flag))
                    {
                        if (Main.netMode != 1)
{
                            if (WorldGen.OpenDoor(num43, num44 - 2, direction))
{
                                closeDoor = true;
                                doorX = num43;
                                doorY = num44 - 2;
                                NetMessage.SendData(19, -1, -1, null, 0, num43, num44 - 2, direction);
                                netUpdate = true;
                                ai[1] += 80f;
                            }
                            else if (WorldGen.OpenDoor(num43, num44 - 2, -direction))
{
                                closeDoor = true;
                                doorX = num43;
                                doorY = num44 - 2;
                                NetMessage.SendData(19, -1, -1, null, 0, num43, num44 - 2, -direction);
                                netUpdate = true;
                                ai[1] += 80f;
                            }
                            else if (WorldGen.ShiftTallGate(num43, num44 - 2, closing: false))
{
                                closeDoor = true;
                                doorX = num43;
                                doorY = num44 - 2;
                                NetMessage.SendData(19, -1, -1, null, 4, num43, num44 - 2);
                                netUpdate = true;
                                ai[1] += 80f;
                            }
                            else
{
                                direction *= -1;
                                netUpdate = true;
                            }
                        }
                    }
                    else
                    {
                        if ((velocity.X < 0f && direction == -1) || (velocity.X > 0f && direction == 1))
{
                            bool flag15 = false;
                            bool flag16 = false;
                            if (tileSafely5.nactive() && Main.tileSolid[tileSafely5.type] && !Main.tileSolidTop[tileSafely5.type] && (!flag14 || (tileSafely4.nactive() && Main.tileSolid[tileSafely4.type] && !Main.tileSolidTop[tileSafely4.type])))
{
                                if (!Collision.SolidTilesVersatile(num43 - direction * 2, num43 - direction, num44 - 5, num44 - 1) && !Collision.SolidTiles(num43, num43, num44 - 5, num44 - 3))
{
                                    velocity.Y = -6f;
                                    netUpdate = true;
                                }
                                else if (flag28)
{
                                    if (WorldGen.SolidTile((int)(base.Center.X / 16f) + direction, (int)(base.Center.Y / 16f)))
{
                                        direction *= -1;
                                        velocity.X *= 0f;
                                        netUpdate = true;
                                    }
                                }
                                else if (flag5)
{
                                    flag16 = true;
                                    flag15 = true;
                                }
                                else if (!flag13)
{
                                    flag15 = true;
                                }
                            }
                            else if (tileSafely4.nactive() && Main.tileSolid[tileSafely4.type] && !Main.tileSolidTop[tileSafely4.type])
{
                                if (!Collision.SolidTilesVersatile(num43 - direction * 2, num43 - direction, num44 - 4, num44 - 1) && !Collision.SolidTiles(num43, num43, num44 - 4, num44 - 2))
{
                                    velocity.Y = -5f;
                                    netUpdate = true;
                                }
                                else if (flag5)
{
                                    flag16 = true;
                                    flag15 = true;
                                }
                                else
{
                                    flag15 = true;
                                }
                            }
                            else if (position.Y + (float)height - (float)(num44 * 16) > 20f && tileSafely3.nactive() && Main.tileSolid[tileSafely3.type] && !tileSafely3.topSlope())
{
                                if (!Collision.SolidTilesVersatile(num43 - direction * 2, num43, num44 - 3, num44 - 1))
{
                                    velocity.Y = -4.4f;
                                    netUpdate = true;
                                }
                                else if (flag5)
{
                                    flag16 = true;
                                    flag15 = true;
                                }
                                else
{
                                    flag15 = true;
                                }
                            }
                            else if (avoidFalling3)
{
                                if (!flag13)
{
                                    flag15 = true;
                                }
                                if (flag5)
{
                                    flag16 = true;
                                }
                            }
                            else if (flag4 && !Collision.SolidTilesVersatile(num43 - direction * 2, num43 - direction, num44 - 2, num44 - 1))
{
                                velocity.Y = -5f;
                                netUpdate = true;
                            }
                            if (flag16)
{
                                keepwalking3 = false;
                                velocity.X = 0f;
                                ai[0] = 8f;
                                ai[1] = 240f;
                                netUpdate = true;
                            }
                            if (flag15)
{
                                direction *= -1;
                                velocity.X *= -1f;
                                netUpdate = true;
                            }
                            if (keepwalking3)
{
                                ai[1] = 90f;
                                netUpdate = true;
                            }
                            if (velocity.Y < 0f)
{
                                localAI[3] = position.X;
                            }
                        }
                        if (velocity.Y < 0f && wet)
{
                            velocity.Y *= 1.2f;
                        }
                        if (velocity.Y < 0f && NPCID.Sets.TownCritter[type] && !flag28)
{
                            velocity.Y *= 1.2f;
                        }
                    }
                }
                else if (flag4 && !wet)
                {
                    int num52 = (int)(base.Center.X / 16f);
                    int num54 = (int)((position.Y + (float)height - 16f) / 16f);
                    int num55 = 0;
                    for (int num56 = -1; num56 <= 1; num56++)
                    {
                        for (int num57 = 1; num57 <= 6; num57++)
{
                            Tile tileSafely6 = Framing.GetTileSafely(num52 + num56, num54 + num57);
                            if (tileSafely6.liquid > 0 || (tileSafely6.nactive() && Main.tileSolid[tileSafely6.type]))
{
                                num55++;
                            }
                        }
                    }
                    if (num55 <= 2)
                    {
                        if (velocity.X != 0f)
{
                            netUpdate = true;
                        }
                        velocity.X *= 0.2f;
                        ai[0] = 0f;
                        ai[1] = 50 + Main.rand.Next(50);
                        ai[2] = 0f;
                        localAI[3] = 40f;
                    }
                }
            }
        }
        else if (ai[0] == 2f || ai[0] == 11f)
        {
            if (Main.netMode != 1)
            {
                localAI[3] -= 1f;
                if (Main.rand.Next(60) == 0 && localAI[3] == 0f)
                {
                    localAI[3] = 60f;
                    direction *= -1;
                    netUpdate = true;
                }
            }
            ai[1] -= 1f;
            velocity.X *= 0.8f;
            if (ai[1] <= 0f)
            {
                localAI[3] = 40f;
                ai[0] = 0f;
                ai[1] = 60 + Main.rand.Next(60);
                netUpdate = true;
            }
        }
        else if (ai[0] == 3f || ai[0] == 4f || ai[0] == 5f || ai[0] == 8f || ai[0] == 9f || ai[0] == 16f || ai[0] == 17f || ai[0] == 20f || ai[0] == 21f || ai[0] == 22f || ai[0] == 23f)
        {
            velocity.X *= 0.8f;
            ai[1] -= 1f;
            if (ai[0] == 8f && ai[1] < 60f && flag5)
            {
                ai[1] = 180f;
                netUpdate = true;
            }
            if (ai[0] == 5f)
            {
                Point coords = (base.Bottom + Vector2.UnitY * -2f).ToTileCoordinates();
                Tile tile = Main.tile[coords.X, coords.Y];
                if (!TileID.Sets.CanBeSatOnForNPCs[tile.type])
                {
                    ai[1] = 0f;
                }
                else
                {
                    Main.sittingManager.AddNPC(whoAmI, coords);
                }
            }
            if (ai[1] <= 0f)
            {
                ai[0] = 0f;
                ai[1] = 60 + Main.rand.Next(60);
                ai[2] = 0f;
                localAI[3] = 30 + Main.rand.Next(60);
                netUpdate = true;
            }
        }
        else if (ai[0] == 6f || ai[0] == 7f || ai[0] == 18f || ai[0] == 19f)
        {
            if (ai[0] == 18f && (localAI[3] < 1f || localAI[3] > 2f))
            {
                localAI[3] = 2f;
            }
            velocity.X *= 0.8f;
            ai[1] -= 1f;
            int num58 = (int)ai[2];
            if (num58 < 0 || num58 > 255 || !Main.player[num58].CanBeTalkedTo || Main.player[num58].Distance(base.Center) > 200f || !Collision.CanHitLine(base.Top, 0, 0, Main.player[num58].Top, 0, 0))
            {
                ai[1] = 0f;
            }
            if (ai[1] > 0f)
            {
                int num59 = ((base.Center.X < Main.player[num58].Center.X) ? 1 : (-1));
                if (num59 != direction)
                {
                    netUpdate = true;
                }
                direction = num59;
            }
            else
            {
                ai[0] = 0f;
                ai[1] = 60 + Main.rand.Next(60);
                ai[2] = 0f;
                localAI[3] = 30 + Main.rand.Next(60);
                netUpdate = true;
            }
        }
        else if (ai[0] == 10f)
        {
            int num60 = 0;
            int num61 = 0;
            float knockBack = 0f;
            float num62 = 0f;
            int num63 = 0;
            int num65 = 0;
            int maxValue = 0;
            float num66 = 0f;
            float num67 = NPCID.Sets.DangerDetectRange[type];
            float num68 = 0f;
            if ((float)NPCID.Sets.AttackTime[type] == ai[1])
            {
                frameCounter = 0.0;
                localAI[3] = 0f;
            }
            if (type == 38)
            {
                num60 = 30;
                num62 = 6f;
                num61 = 20;
                num63 = 10;
                num65 = 180;
                maxValue = 120;
                num66 = 16f;
                knockBack = 7f;
            }
            else if (type == 633)
            {
                num60 = 880;
                num62 = 24f;
                num61 = 15;
                num63 = 1;
                num66 = 0f;
                knockBack = 7f;
                num65 = 15;
                maxValue = 10;
                if (ShouldBestiaryGirlBeLycantrope())
                {
                    num60 = 929;
                    num61 = (int)((float)num61 * 1.5f);
                }
            }
            else if (type == 550)
            {
                num60 = 669;
                num62 = 6f;
                num61 = 24;
                num63 = 10;
                num65 = 120;
                maxValue = 60;
                num66 = 16f;
                knockBack = 9f;
            }
            else if (type == 588)
            {
                num60 = 721;
                num62 = 8f;
                num61 = 15;
                num63 = 5;
                num65 = 20;
                maxValue = 10;
                num66 = 16f;
                knockBack = 9f;
            }
            else if (type == 208)
            {
                num60 = 588;
                num62 = 6f;
                num61 = 30;
                num63 = 10;
                num65 = 60;
                maxValue = 120;
                num66 = 16f;
                knockBack = 6f;
            }
            else if (type == 17)
            {
                num60 = 48;
                num62 = 9f;
                num61 = 12;
                num63 = 10;
                num65 = 60;
                maxValue = 60;
                num66 = 16f;
                knockBack = 1.5f;
            }
            else if (type == 369)
            {
                num60 = 520;
                num62 = 12f;
                num61 = 10;
                num63 = 10;
                num65 = 0;
                maxValue = 1;
                num66 = 16f;
                knockBack = 3f;
            }
            else if (type == 453)
            {
                num60 = 21;
                num62 = 14f;
                num61 = 14;
                num63 = 10;
                num65 = 0;
                maxValue = 1;
                num66 = 16f;
                knockBack = 3f;
            }
            else if (type == 107)
            {
                num60 = 24;
                num62 = 5f;
                num61 = 15;
                num63 = 10;
                num65 = 60;
                maxValue = 60;
                num66 = 16f;
                knockBack = 1f;
            }
            else if (type == 124)
            {
                num60 = 582;
                num62 = 10f;
                num61 = 11;
                num63 = 1;
                num65 = 30;
                maxValue = 30;
                knockBack = 3.5f;
            }
            else if (type == 18)
            {
                num60 = 583;
                num62 = 8f;
                num61 = 8;
                num63 = 1;
                num65 = 15;
                maxValue = 10;
                knockBack = 2f;
                num66 = 10f;
            }
            else if (type == 142)
            {
                num60 = 589;
                num62 = 7f;
                num61 = 22;
                num63 = 1;
                num65 = 10;
                maxValue = 1;
                knockBack = 2f;
                num66 = 10f;
            }
            NPCLoader.TownNPCAttackStrength(this, ref num61, ref knockBack);
            NPCLoader.TownNPCAttackCooldown(this, ref num65, ref maxValue);
            NPCLoader.TownNPCAttackProj(this, ref num60, ref num63);
            NPCLoader.TownNPCAttackProjSpeed(this, ref num62, ref num66, ref num68);
            if (Main.expertMode)
            {
                num61 = (int)((float)num61 * Main.GameModeInfo.TownNPCDamageMultiplier);
            }
            num61 = (int)((float)num61 * num42);
            velocity.X *= 0.8f;
            ai[1] -= 1f;
            localAI[3] += 1f;
            if (localAI[3] == (float)num63 && Main.netMode != 1)
            {
                Vector2 vec = -Vector2.UnitY;
                if (num13 == 1 && spriteDirection == 1 && num35 != -1)
                {
                    vec = DirectionTo(Main.npc[num35].Center + new Vector2(0f, (0f - num66) * MathHelper.Clamp(Distance(Main.npc[num35].Center) / num67, 0f, 1f)));
                }
                if (num13 == -1 && spriteDirection == -1 && num24 != -1)
                {
                    vec = DirectionTo(Main.npc[num24].Center + new Vector2(0f, (0f - num66) * MathHelper.Clamp(Distance(Main.npc[num24].Center) / num67, 0f, 1f)));
                }
                if (vec.HasNaNs() || Math.Sign(vec.X) != spriteDirection)
                {
                    ((Vector2)(ref vec))._002Ector((float)spriteDirection, -1f);
                }
                vec *= num62;
                vec += Utils.RandomVector2(Main.rand, 0f - num68, num68);
                int num69 = 1000;
                num69 = ((type == 124) ? Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec.X, vec.Y, num60, num61, knockBack, Main.myPlayer, 0f, whoAmI, townNpcVariationIndex) : ((type != 142) ? Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec.X, vec.Y, num60, num61, knockBack, Main.myPlayer) : Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec.X, vec.Y, num60, num61, knockBack, Main.myPlayer, 0f, Main.rand.Next(5))));
                Main.projectile[num69].npcProj = true;
                Main.projectile[num69].noDropItem = true;
                if (type == 588)
                {
                    Main.projectile[num69].timeLeft = 480;
                }
            }
            if (ai[1] <= 0f)
            {
                ai[0] = ((localAI[2] == 8f && flag5) ? 8 : 0);
                ai[1] = num65 + Main.rand.Next(maxValue);
                ai[2] = 0f;
                localAI[1] = (localAI[3] = num65 / 2 + Main.rand.Next(maxValue));
                netUpdate = true;
            }
        }
        else if (ai[0] == 12f)
        {
            int num70 = 0;
            int num71 = 0;
            float num72 = 0f;
            int num73 = 0;
            int num74 = 0;
            int maxValue2 = 0;
            float knockBack2 = 0f;
            float num76 = 0f;
            bool flag17 = false;
            float num77 = 0f;
            if ((float)NPCID.Sets.AttackTime[type] == ai[1])
            {
                frameCounter = 0.0;
                localAI[3] = 0f;
            }
            int num78 = -1;
            if (num13 == 1 && spriteDirection == 1)
            {
                num78 = num35;
            }
            if (num13 == -1 && spriteDirection == -1)
            {
                num78 = num24;
            }
            if (type == 19)
            {
                num70 = 14;
                num72 = 13f;
                num71 = 24;
                num74 = 14;
                maxValue2 = 4;
                knockBack2 = 3f;
                num73 = 1;
                num77 = 0.5f;
                if ((float)NPCID.Sets.AttackTime[type] == ai[1])
                {
                    frameCounter = 0.0;
                    localAI[3] = 0f;
                }
                if (Main.hardMode)
                {
                    num71 = 15;
                    if (localAI[3] > (float)num73)
                    {
                        num73 = 10;
                        flag17 = true;
                    }
                    if (localAI[3] > (float)num73)
                    {
                        num73 = 20;
                        flag17 = true;
                    }
                    if (localAI[3] > (float)num73)
                    {
                        num73 = 30;
                        flag17 = true;
                    }
                }
            }
            else if (type == 227)
            {
                num70 = 587;
                num72 = 10f;
                num71 = 8;
                num74 = 10;
                maxValue2 = 1;
                knockBack2 = 1.75f;
                num73 = 1;
                num77 = 0.5f;
                if (localAI[3] > (float)num73)
                {
                    num73 = 12;
                    flag17 = true;
                }
                if (localAI[3] > (float)num73)
                {
                    num73 = 24;
                    flag17 = true;
                }
                if (Main.hardMode)
                {
                    num71 += 2;
                }
            }
            else if (type == 368)
            {
                num70 = 14;
                num72 = 13f;
                num71 = 24;
                num74 = 12;
                maxValue2 = 5;
                knockBack2 = 2f;
                num73 = 1;
                num77 = 0.2f;
                if (Main.hardMode)
                {
                    num71 = 30;
                    num70 = 357;
                }
            }
            else if (type == 22)
            {
                num72 = 10f;
                num71 = 8;
                num73 = 1;
                if (Main.hardMode)
                {
                    num70 = 2;
                    num74 = 15;
                    maxValue2 = 10;
                    num71 += 6;
                }
                else
                {
                    num70 = 1;
                    num74 = 30;
                    maxValue2 = 20;
                }
                knockBack2 = 2.75f;
                num76 = 4f;
                num77 = 0.7f;
            }
            else if (type == 228)
            {
                num70 = 267;
                num72 = 14f;
                num71 = 20;
                num73 = 1;
                num74 = 10;
                maxValue2 = 1;
                knockBack2 = 3f;
                num76 = 6f;
                num77 = 0.4f;
            }
            else if (type == 178)
            {
                num70 = 242;
                num72 = 13f;
                num71 = ((!Main.hardMode) ? 11 : 15);
                num74 = 10;
                maxValue2 = 1;
                knockBack2 = 2f;
                num73 = 1;
                if (localAI[3] > (float)num73)
                {
                    num73 = 8;
                    flag17 = true;
                }
                if (localAI[3] > (float)num73)
                {
                    num73 = 16;
                    flag17 = true;
                }
                num77 = 0.3f;
            }
            else if (type == 229)
            {
                num70 = 14;
                num72 = 14f;
                num71 = 24;
                num74 = 10;
                maxValue2 = 1;
                knockBack2 = 2f;
                num73 = 1;
                num77 = 0.7f;
                if (localAI[3] > (float)num73)
                {
                    num73 = 16;
                    flag17 = true;
                }
                if (localAI[3] > (float)num73)
                {
                    num73 = 24;
                    flag17 = true;
                }
                if (localAI[3] > (float)num73)
                {
                    num73 = 32;
                    flag17 = true;
                }
                if (localAI[3] > (float)num73)
                {
                    num73 = 40;
                    flag17 = true;
                }
                if (localAI[3] > (float)num73)
                {
                    num73 = 48;
                    flag17 = true;
                }
                if (localAI[3] == 0f && num78 != -1 && Distance(Main.npc[num78].Center) < (float)NPCID.Sets.PrettySafe[type])
                {
                    num77 = 0.1f;
                    num70 = 162;
                    num71 = 50;
                    knockBack2 = 10f;
                    num72 = 24f;
                }
            }
            else if (type == 209)
            {
                num70 = Utils.SelectRandom<int>(Main.rand, 134, 133, 135);
                num73 = 1;
                switch (num70)
                {
                case 135:
                    num72 = 12f;
                    num71 = 30;
                    num74 = 30;
                    maxValue2 = 10;
                    knockBack2 = 7f;
                    num77 = 0.2f;
                    break;
                case 133:
                    num72 = 10f;
                    num71 = 25;
                    num74 = 10;
                    maxValue2 = 1;
                    knockBack2 = 6f;
                    num77 = 0.2f;
                    break;
                case 134:
                    num72 = 13f;
                    num71 = 20;
                    num74 = 20;
                    maxValue2 = 10;
                    knockBack2 = 4f;
                    num77 = 0.1f;
                    break;
                }
            }
            NPCLoader.TownNPCAttackStrength(this, ref num71, ref knockBack2);
            NPCLoader.TownNPCAttackCooldown(this, ref num74, ref maxValue2);
            NPCLoader.TownNPCAttackProj(this, ref num70, ref num73);
            NPCLoader.TownNPCAttackProjSpeed(this, ref num72, ref num76, ref num77);
            NPCLoader.TownNPCAttackShoot(this, ref flag17);
            if (Main.expertMode)
            {
                num71 = (int)((float)num71 * Main.GameModeInfo.TownNPCDamageMultiplier);
            }
            num71 = (int)((float)num71 * num42);
            velocity.X *= 0.8f;
            ai[1] -= 1f;
            localAI[3] += 1f;
            if (localAI[3] == (float)num73 && Main.netMode != 1)
            {
                Vector2 vec2 = Vector2.Zero;
                if (num78 != -1)
                {
                    vec2 = DirectionTo(Main.npc[num78].Center + new Vector2(0f, 0f - num76));
                }
                if (vec2.HasNaNs() || Math.Sign(vec2.X) != spriteDirection)
                {
                    ((Vector2)(ref vec2))._002Ector((float)spriteDirection, 0f);
                }
                vec2 *= num72;
                vec2 += Utils.RandomVector2(Main.rand, 0f - num77, num77);
                int num79 = 1000;
                num79 = ((type != 227) ? Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec2.X, vec2.Y, num70, num71, knockBack2, Main.myPlayer) : Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec2.X, vec2.Y, num70, num71, knockBack2, Main.myPlayer, 0f, (float)Main.rand.Next(12) / 6f));
                Main.projectile[num79].npcProj = true;
                Main.projectile[num79].noDropItem = true;
            }
            if (localAI[3] == (float)num73 && flag17 && num78 != -1)
            {
                Vector2 vector2 = DirectionTo(Main.npc[num78].Center);
                if (vector2.Y <= 0.5f && vector2.Y >= -0.5f)
                {
                    ai[2] = vector2.Y;
                }
            }
            if (ai[1] <= 0f)
            {
                ai[0] = ((localAI[2] == 8f && flag5) ? 8 : 0);
                ai[1] = num74 + Main.rand.Next(maxValue2);
                ai[2] = 0f;
                localAI[1] = (localAI[3] = num74 / 2 + Main.rand.Next(maxValue2));
                netUpdate = true;
            }
        }
        else if (ai[0] == 13f)
        {
            velocity.X *= 0.8f;
            if ((float)NPCID.Sets.AttackTime[type] == ai[1])
            {
                frameCounter = 0.0;
            }
            ai[1] -= 1f;
            localAI[3] += 1f;
            if (localAI[3] == 1f && Main.netMode != 1)
            {
                Vector2 vec3 = DirectionTo(Main.npc[(int)ai[2]].Center + new Vector2(0f, -20f));
                if (vec3.HasNaNs() || Math.Sign(vec3.X) == -spriteDirection)
                {
                    ((Vector2)(ref vec3))._002Ector((float)spriteDirection, -1f);
                }
                vec3 *= 8f;
                int num80 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec3.X, vec3.Y, 584, 0, 0f, Main.myPlayer, ai[2]);
                Main.projectile[num80].npcProj = true;
                Main.projectile[num80].noDropItem = true;
            }
            if (ai[1] <= 0f)
            {
                ai[0] = 0f;
                ai[1] = 10 + Main.rand.Next(10);
                ai[2] = 0f;
                localAI[3] = 5 + Main.rand.Next(10);
                netUpdate = true;
            }
        }
        else if (ai[0] == 14f)
        {
            int num81 = 0;
            int num82 = 0;
            float num83 = 0f;
            int num84 = 0;
            int num85 = 0;
            int maxValue3 = 0;
            float knockBack3 = 0f;
            float num87 = 0f;
            float num88 = NPCID.Sets.DangerDetectRange[type];
            float num89 = 1f;
            float num90 = 0f;
            if ((float)NPCID.Sets.AttackTime[type] == ai[1])
            {
                frameCounter = 0.0;
                localAI[3] = 0f;
            }
            int num91 = -1;
            if (num13 == 1 && spriteDirection == 1)
            {
                num91 = num35;
            }
            if (num13 == -1 && spriteDirection == -1)
            {
                num91 = num24;
            }
            if (type == 54)
            {
                num81 = 585;
                num83 = 10f;
                num82 = 16;
                num84 = 30;
                num85 = 20;
                maxValue3 = 15;
                knockBack3 = 2f;
                num90 = 1f;
            }
            else if (type == 108)
            {
                num81 = 15;
                num83 = 6f;
                num82 = 18;
                num84 = 15;
                num85 = 15;
                maxValue3 = 5;
                knockBack3 = 3f;
                num87 = 20f;
            }
            else if (type == 160)
            {
                num81 = 590;
                num82 = 40;
                num84 = 15;
                num85 = 10;
                maxValue3 = 1;
                knockBack3 = 3f;
                for (; localAI[3] > (float)num84; num84 += 15)
                {
                }
            }
            else if (type == 663)
            {
                num81 = 950;
                num82 = ((!Main.hardMode) ? 15 : 20);
                num84 = 15;
                num85 = 0;
                maxValue3 = 0;
                knockBack3 = 3f;
                for (; localAI[3] > (float)num84; num84 += 10)
                {
                }
            }
            else if (type == 20)
            {
                num81 = 586;
                num84 = 24;
                num85 = 10;
                maxValue3 = 1;
                knockBack3 = 3f;
            }
            NPCLoader.TownNPCAttackStrength(this, ref num82, ref knockBack3);
            NPCLoader.TownNPCAttackCooldown(this, ref num85, ref maxValue3);
            NPCLoader.TownNPCAttackProj(this, ref num81, ref num84);
            NPCLoader.TownNPCAttackProjSpeed(this, ref num83, ref num87, ref num90);
            NPCLoader.TownNPCAttackMagic(this, ref num89);
            if (Main.expertMode)
            {
                num82 = (int)((float)num82 * Main.GameModeInfo.TownNPCDamageMultiplier);
            }
            num82 = (int)((float)num82 * num42);
            velocity.X *= 0.8f;
            ai[1] -= 1f;
            localAI[3] += 1f;
            if (localAI[3] == (float)num84 && Main.netMode != 1)
            {
                Vector2 vec4 = Vector2.Zero;
                if (num91 != -1)
                {
                    vec4 = DirectionTo(Main.npc[num91].Center + new Vector2(0f, (0f - num87) * MathHelper.Clamp(Distance(Main.npc[num91].Center) / num88, 0f, 1f)));
                }
                if (vec4.HasNaNs() || Math.Sign(vec4.X) != spriteDirection)
                {
                    ((Vector2)(ref vec4))._002Ector((float)spriteDirection, 0f);
                }
                vec4 *= num83;
                vec4 += Utils.RandomVector2(Main.rand, 0f - num90, num90);
                if (type == 108)
                {
                    int num92 = Utils.SelectRandom<int>(Main.rand, 1, 1, 1, 1, 2, 2, 3);
                    for (int num93 = 0; num93 < num92; num93++)
                    {
                        Vector2 vector3 = Utils.RandomVector2(Main.rand, -3.4f, 3.4f);
                        int num94 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec4.X + vector3.X, vec4.Y + vector3.Y, num81, num82, knockBack3, Main.myPlayer, 0f, 0f, townNpcVariationIndex);
                        Main.projectile[num94].npcProj = true;
                        Main.projectile[num94].noDropItem = true;
                    }
                }
                else if (type == 160)
                {
                    if (num91 != -1)
                    {
                        Vector2 vector4 = Main.npc[num91].position - Main.npc[num91].Size * 2f + Main.npc[num91].Size * Utils.RandomVector2(Main.rand, 0f, 1f) * 5f;
                        int num95 = 10;
                        while (num95 > 0 && WorldGen.SolidTile(Framing.GetTileSafely((int)vector4.X / 16, (int)vector4.Y / 16)))
{
                            num95--;
                            vector4 = Main.npc[num91].position - Main.npc[num91].Size * 2f + Main.npc[num91].Size * Utils.RandomVector2(Main.rand, 0f, 1f) * 5f;
                        }
                        int num96 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector4.X, vector4.Y, 0f, 0f, num81, num82, knockBack3, Main.myPlayer, 0f, 0f, townNpcVariationIndex);
                        Main.projectile[num96].npcProj = true;
                        Main.projectile[num96].noDropItem = true;
                    }
                }
                else if (type == 663)
                {
                    if (num91 != -1)
                    {
                        Vector2 vector5 = Main.npc[num91].position + Main.npc[num91].Size * Utils.RandomVector2(Main.rand, 0f, 1f) * 1f;
                        int num98 = 5;
                        while (num98 > 0 && WorldGen.SolidTile(Framing.GetTileSafely((int)vector5.X / 16, (int)vector5.Y / 16)))
{
                            num98--;
                            vector5 = Main.npc[num91].position + Main.npc[num91].Size * Utils.RandomVector2(Main.rand, 0f, 1f) * 1f;
                        }
                        int num99 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector5.X, vector5.Y, 0f, 0f, num81, num82, knockBack3, Main.myPlayer, 0f, 0f, townNpcVariationIndex);
                        Main.projectile[num99].npcProj = true;
                        Main.projectile[num99].noDropItem = true;
                    }
                }
                else if (type == 20)
                {
                    int num100 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec4.X, vec4.Y, num81, num82, knockBack3, Main.myPlayer, 0f, whoAmI, townNpcVariationIndex);
                    Main.projectile[num100].npcProj = true;
                    Main.projectile[num100].noDropItem = true;
                }
                else
                {
                    int num101 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * 16), base.Center.Y - 2f, vec4.X, vec4.Y, num81, num82, knockBack3, Main.myPlayer);
                    Main.projectile[num101].npcProj = true;
                    Main.projectile[num101].noDropItem = true;
                }
            }
            if (num89 > 0f)
            {
                newColor = GetMagicAuraColor();
                Vector3 vector6 = ((Color)(ref newColor)).ToVector3() * num89;
                Lighting.AddLight(base.Center, vector6.X, vector6.Y, vector6.Z);
            }
            if (ai[1] <= 0f)
            {
                ai[0] = ((localAI[2] == 8f && flag5) ? 8 : 0);
                ai[1] = num85 + Main.rand.Next(maxValue3);
                ai[2] = 0f;
                localAI[1] = (localAI[3] = num85 / 2 + Main.rand.Next(maxValue3));
                netUpdate = true;
            }
        }
        else if (ai[0] == 15f)
        {
            int num102 = 0;
            int maxValue4 = 0;
            if ((float)NPCID.Sets.AttackTime[type] == ai[1])
            {
                frameCounter = 0.0;
                localAI[3] = 0f;
            }
            int num103 = 0;
            float num104 = 0f;
            int num105 = 0;
            int num106 = 0;
            if (num13 == 1)
            {
                _ = spriteDirection;
            }
            if (num13 == -1)
            {
                _ = spriteDirection;
            }
            if (type == 207)
            {
                num103 = 11;
                num105 = (num106 = 32);
                num102 = 12;
                maxValue4 = 6;
                num104 = 4.25f;
            }
            else if (type == 441)
            {
                num103 = 9;
                num105 = (num106 = 28);
                num102 = 9;
                maxValue4 = 3;
                num104 = 3.5f;
                if (GivenName == "Andrew")
                {
                    num103 *= 2;
                    num104 *= 2f;
                }
            }
            else if (type == 353)
            {
                num103 = 10;
                num105 = (num106 = 32);
                num102 = 15;
                maxValue4 = 8;
                num104 = 5f;
            }
            else if (NPCID.Sets.IsTownPet[type])
            {
                num103 = 10;
                num105 = (num106 = 32);
                num102 = 15;
                maxValue4 = 8;
                num104 = 3f;
            }
            NPCLoader.TownNPCAttackStrength(this, ref num103, ref num104);
            NPCLoader.TownNPCAttackCooldown(this, ref num102, ref maxValue4);
            NPCLoader.TownNPCAttackSwing(this, ref num105, ref num106);
            if (Main.expertMode)
            {
                num103 = (int)((float)num103 * Main.GameModeInfo.TownNPCDamageMultiplier);
            }
            num103 = (int)((float)num103 * num42);
            velocity.X *= 0.8f;
            ai[1] -= 1f;
            if (Main.netMode != 1)
            {
                Tuple<Vector2, float> swingStats = GetSwingStats(NPCID.Sets.AttackTime[type] * 2, (int)ai[1], spriteDirection, num105, num106);
                Rectangle itemRectangle = default(Rectangle);
                ((Rectangle)(ref itemRectangle))._002Ector((int)swingStats.Item1.X, (int)swingStats.Item1.Y, num105, num106);
                if (spriteDirection == -1)
                {
                    itemRectangle.X -= num105;
                }
                itemRectangle.Y -= num106;
                TweakSwingStats(NPCID.Sets.AttackTime[type] * 2, (int)ai[1], spriteDirection, ref itemRectangle);
                int myPlayer = Main.myPlayer;
                for (int num107 = 0; num107 < 200; num107++)
                {
                    NPC nPC2 = Main.npc[num107];
                    if (nPC2.active && nPC2.immune[myPlayer] == 0 && !nPC2.dontTakeDamage && !nPC2.friendly && nPC2.damage > 0 && ((Rectangle)(ref itemRectangle)).Intersects(nPC2.Hitbox) && (nPC2.noTileCollide || Collision.CanHit(position, width, height, nPC2.position, nPC2.width, nPC2.height)))
                    {
                        nPC2.StrikeNPCNoInteraction(num103, num104, spriteDirection);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(28, -1, -1, null, num107, num103, num104, spriteDirection);
                        }
                        nPC2.netUpdate = true;
                        nPC2.immune[myPlayer] = (int)ai[1] + 2;
                    }
                }
            }
            if (ai[1] <= 0f)
            {
                bool flag18 = false;
                if (flag5)
                {
                    int num109 = -num13;
                    if (!Collision.CanHit(base.Center, 0, 0, base.Center + Vector2.UnitX * (float)num109 * 32f, 0, 0) || localAI[2] == 8f)
                    {
                        flag18 = true;
                    }
                    if (flag18)
                    {
                        int num110 = NPCID.Sets.AttackTime[type];
                        int num111 = ((num13 == 1) ? num35 : num24);
                        int num112 = ((num13 == 1) ? num24 : num35);
                        if (num111 != -1 && !Collision.CanHit(base.Center, 0, 0, Main.npc[num111].Center, 0, 0))
{
                            num111 = ((num112 == -1 || !Collision.CanHit(base.Center, 0, 0, Main.npc[num112].Center, 0, 0)) ? (-1) : num112);
                        }
                        if (num111 != -1)
{
                            ai[0] = 15f;
                            ai[1] = num110;
                            ai[2] = 0f;
                            localAI[3] = 0f;
                            direction = ((position.X < Main.npc[num111].position.X) ? 1 : (-1));
                            netUpdate = true;
                        }
                        else
{
                            flag18 = false;
                        }
                    }
                }
                if (!flag18)
                {
                    ai[0] = ((localAI[2] == 8f && flag5) ? 8 : 0);
                    ai[1] = num102 + Main.rand.Next(maxValue4);
                    ai[2] = 0f;
                    localAI[1] = (localAI[3] = num102 / 2 + Main.rand.Next(maxValue4));
                    netUpdate = true;
                }
            }
        }
        else if (ai[0] == 24f)
        {
            velocity.X *= 0.8f;
            ai[1] -= 1f;
            localAI[3] += 1f;
            direction = 1;
            spriteDirection = 1;
            newColor = GetMagicAuraColor();
            Vector3 vector7 = ((Color)(ref newColor)).ToVector3();
            Lighting.AddLight(base.Center, vector7.X, vector7.Y, vector7.Z);
            if (ai[1] <= 0f)
            {
                ai[0] = 0f;
                ai[1] = 480f;
                ai[2] = 0f;
                localAI[1] = 480f;
                netUpdate = true;
            }
        }
        if (flag3 && wet)
        {
            int num113 = (int)(base.Center.X / 16f);
            int num114 = 5;
            if (collideX || (num113 < num114 && direction == -1) || (num113 > Main.maxTilesX - num114 && direction == 1))
            {
                direction *= -1;
                velocity.X *= -0.25f;
                netUpdate = true;
            }
            velocity.Y *= 0.9f;
            velocity.Y -= 0.5f;
            if (velocity.Y < -15f)
            {
                velocity.Y = -15f;
            }
        }
        if (flag2 && wet)
        {
            if (flag30)
            {
                ai[1] = 50f;
            }
            int num115 = (int)(base.Center.X / 16f);
            int num116 = 5;
            if (collideX || (num115 < num116 && direction == -1) || (num115 > Main.maxTilesX - num116 && direction == 1))
            {
                direction *= -1;
                velocity.X *= -0.25f;
                netUpdate = true;
            }
            if (Collision.GetWaterLine(base.Center.ToTileCoordinates(), out var waterLineHeight))
            {
                float num117 = base.Center.Y + 1f;
                if (base.Center.Y > waterLineHeight)
                {
                    velocity.Y -= 0.8f;
                    if (velocity.Y < -4f)
                    {
                        velocity.Y = -4f;
                    }
                    if (num117 + velocity.Y < waterLineHeight)
                    {
                        velocity.Y = waterLineHeight - num117;
                    }
                }
                else
                {
                    velocity.Y = MathHelper.Min(velocity.Y, waterLineHeight - num117);
                }
            }
            else
            {
                velocity.Y -= 0.2f;
            }
        }
        if (Main.netMode != 1 && isLikeATownNPC && !flag23)
        {
            bool flag19 = ai[0] < 2f && !flag5 && !wet;
            bool flag20 = (ai[0] < 2f || ai[0] == 8f) && (flag5 || flag6);
            if (localAI[1] > 0f)
            {
                localAI[1] -= 1f;
            }
            if (localAI[1] > 0f)
            {
                flag20 = false;
            }
            if (flag20 && type == 124 && localAI[0] == 1f)
            {
                flag20 = false;
            }
            if (flag20 && type == 20)
            {
                flag20 = false;
                for (int num118 = 0; num118 < 200; num118++)
                {
                    NPC nPC3 = Main.npc[num118];
                    if (nPC3.active && nPC3.townNPC && !(Distance(nPC3.Center) > 1200f) && nPC3.FindBuffIndex(165) == -1)
                    {
                        flag20 = true;
                        break;
                    }
                }
            }
            if (CanTalk && flag19 && ai[0] == 0f && velocity.Y == 0f && Main.rand.Next(300) == 0)
            {
                int num120 = 420;
                num120 = ((Main.rand.Next(2) != 0) ? (num120 * Main.rand.Next(1, 3)) : (num120 * Main.rand.Next(1, 4)));
                int num121 = 100;
                int num122 = 20;
                for (int num123 = 0; num123 < 200; num123++)
                {
                    NPC nPC4 = Main.npc[num123];
                    bool flag21 = (nPC4.ai[0] == 1f && nPC4.closeDoor) || (nPC4.ai[0] == 1f && nPC4.ai[1] > 200f) || nPC4.ai[0] > 1f || nPC4.wet;
                    if (nPC4 != this && nPC4.active && nPC4.CanBeTalkedTo && !flag21 && nPC4.Distance(base.Center) < (float)num121 && nPC4.Distance(base.Center) > (float)num122 && Collision.CanHit(base.Center, 0, 0, nPC4.Center, 0, 0))
                    {
                        int num124 = (position.X < nPC4.position.X).ToDirectionInt();
                        ai[0] = 3f;
                        ai[1] = num120;
                        ai[2] = num123;
                        direction = num124;
                        netUpdate = true;
                        nPC4.ai[0] = 4f;
                        nPC4.ai[1] = num120;
                        nPC4.ai[2] = whoAmI;
                        nPC4.direction = -num124;
                        nPC4.netUpdate = true;
                        break;
                    }
                }
            }
            else if (CanTalk && flag19 && ai[0] == 0f && velocity.Y == 0f && Main.rand.Next(1800) == 0)
            {
                int num125 = 420;
                num125 = ((Main.rand.Next(2) != 0) ? (num125 * Main.rand.Next(1, 3)) : (num125 * Main.rand.Next(1, 4)));
                int num126 = 100;
                int num127 = 20;
                for (int num128 = 0; num128 < 200; num128++)
                {
                    NPC nPC5 = Main.npc[num128];
                    bool flag22 = (nPC5.ai[0] == 1f && nPC5.closeDoor) || (nPC5.ai[0] == 1f && nPC5.ai[1] > 200f) || nPC5.ai[0] > 1f || nPC5.wet;
                    if (nPC5 != this && nPC5.active && nPC5.CanBeTalkedTo && !NPCID.Sets.IsTownPet[nPC5.type] && !flag22 && nPC5.Distance(base.Center) < (float)num126 && nPC5.Distance(base.Center) > (float)num127 && Collision.CanHit(base.Center, 0, 0, nPC5.Center, 0, 0))
                    {
                        int num129 = (position.X < nPC5.position.X).ToDirectionInt();
                        ai[0] = 16f;
                        ai[1] = num125;
                        ai[2] = num128;
                        localAI[2] = Main.rand.Next(4);
                        localAI[3] = Main.rand.Next(3 - (int)localAI[2]);
                        direction = num129;
                        netUpdate = true;
                        nPC5.ai[0] = 17f;
                        nPC5.ai[1] = num125;
                        nPC5.ai[2] = whoAmI;
                        nPC5.localAI[2] = 0f;
                        nPC5.localAI[3] = 0f;
                        nPC5.direction = -num129;
                        nPC5.netUpdate = true;
                        break;
                    }
                }
            }
            else if (!NPCID.Sets.IsTownPet[type] && flag19 && ai[0] == 0f && velocity.Y == 0f && Main.rand.Next(1200) == 0 && (type == 208 || (BirthdayParty.PartyIsUp && NPCID.Sets.AttackType[type] == NPCID.Sets.AttackType[208])))
            {
                int num3 = 300;
                int num4 = 150;
                for (int num5 = 0; num5 < 255; num5++)
                {
                    Player player = Main.player[num5];
                    if (player.active && !player.dead && player.Distance(base.Center) < (float)num4 && Collision.CanHitLine(base.Top, 0, 0, player.Top, 0, 0))
                    {
                        int num6 = (position.X < player.position.X).ToDirectionInt();
                        ai[0] = 6f;
                        ai[1] = num3;
                        ai[2] = num5;
                        direction = num6;
                        netUpdate = true;
                        break;
                    }
                }
            }
            else if (flag19 && ai[0] == 0f && velocity.Y == 0f && Main.rand.Next(600) == 0 && type == 550)
            {
                int num7 = 300;
                int num8 = 150;
                for (int num9 = 0; num9 < 255; num9++)
                {
                    Player player2 = Main.player[num9];
                    if (player2.active && !player2.dead && player2.Distance(base.Center) < (float)num8 && Collision.CanHitLine(base.Top, 0, 0, player2.Top, 0, 0))
                    {
                        int num10 = (position.X < player2.position.X).ToDirectionInt();
                        ai[0] = 18f;
                        ai[1] = num7;
                        ai[2] = num9;
                        direction = num10;
                        netUpdate = true;
                        break;
                    }
                }
            }
            else if (!NPCID.Sets.IsTownPet[type] && flag19 && ai[0] == 0f && velocity.Y == 0f && Main.rand.Next(1800) == 0)
            {
                ai[0] = 2f;
                ai[1] = 45 * Main.rand.Next(1, 2);
                netUpdate = true;
            }
            else if (flag19 && ai[0] == 0f && velocity.Y == 0f && Main.rand.Next(600) == 0 && type == 229 && !flag6)
            {
                ai[0] = 11f;
                ai[1] = 30 * Main.rand.Next(1, 4);
                netUpdate = true;
            }
            else if (flag19 && ai[0] == 0f && velocity.Y == 0f && Main.rand.Next(1200) == 0)
            {
                int num11 = 220;
                int num12 = 150;
                for (int num14 = 0; num14 < 255; num14++)
                {
                    Player player3 = Main.player[num14];
                    if (player3.CanBeTalkedTo && player3.Distance(base.Center) < (float)num12 && Collision.CanHitLine(base.Top, 0, 0, player3.Top, 0, 0))
                    {
                        int num15 = (position.X < player3.position.X).ToDirectionInt();
                        ai[0] = 7f;
                        ai[1] = num11;
                        ai[2] = num14;
                        direction = num15;
                        netUpdate = true;
                        break;
                    }
                }
            }
            else if (flag19 && ai[0] == 1f && velocity.Y == 0f && num > 0 && Main.rand.Next(num) == 0)
            {
                Point point = (base.Bottom + Vector2.UnitY * -2f).ToTileCoordinates();
                bool flag24 = WorldGen.InWorld(point.X, point.Y, 1);
                if (flag24)
                {
                    for (int num16 = 0; num16 < 200; num16++)
                    {
                        if (Main.npc[num16].active && Main.npc[num16].aiStyle == 7 && Main.npc[num16].townNPC && Main.npc[num16].ai[0] == 5f && (Main.npc[num16].Bottom + Vector2.UnitY * -2f).ToTileCoordinates() == point)
{
                            flag24 = false;
                            break;
                        }
                    }
                    for (int num17 = 0; num17 < 255; num17++)
                    {
                        if (Main.player[num17].active && Main.player[num17].sitting.isSitting && Main.player[num17].Center.ToTileCoordinates() == point)
{
                            flag24 = false;
                            break;
                        }
                    }
                }
                if (flag24)
                {
                    Tile tile2 = Main.tile[point.X, point.Y];
                    flag24 = TileID.Sets.CanBeSatOnForNPCs[tile2.type];
                    if (flag24 && tile2.type == 15 && tile2.frameY >= 1080 && tile2.frameY <= 1098)
                    {
                        flag24 = false;
                    }
                    if (flag24)
                    {
                        ai[0] = 5f;
                        ai[1] = 900 + Main.rand.Next(10800);
                        SitDown(point, out var targetDirection, out var bottom);
                        direction = targetDirection;
                        base.Bottom = bottom;
                        velocity = Vector2.Zero;
                        localAI[3] = 0f;
                        netUpdate = true;
                    }
                }
            }
            else if (flag19 && ai[0] == 1f && velocity.Y == 0f && Main.rand.Next(600) == 0 && Utils.PlotTileLine(base.Top, base.Bottom, width, DelegateMethods.SearchAvoidedByNPCs))
            {
                Point point2 = (base.Center + new Vector2((float)(direction * 10), 0f)).ToTileCoordinates();
                bool flag25 = WorldGen.InWorld(point2.X, point2.Y, 1);
                if (flag25)
                {
                    Tile tileSafely7 = Framing.GetTileSafely(point2.X, point2.Y);
                    if (!tileSafely7.nactive() || !TileID.Sets.InteractibleByNPCs[tileSafely7.type])
                    {
                        flag25 = false;
                    }
                }
                if (flag25)
                {
                    ai[0] = 9f;
                    ai[1] = 40 + Main.rand.Next(90);
                    velocity = Vector2.Zero;
                    localAI[3] = 0f;
                    netUpdate = true;
                }
            }
            if (Main.netMode != 1 && ai[0] < 2f && velocity.Y == 0f && type == 18 && breath > 0)
            {
                int num18 = -1;
                for (int num19 = 0; num19 < 200; num19++)
                {
                    NPC nPC6 = Main.npc[num19];
                    if (nPC6.active && nPC6.townNPC && nPC6.life != nPC6.lifeMax && (num18 == -1 || nPC6.lifeMax - nPC6.life > Main.npc[num18].lifeMax - Main.npc[num18].life) && Collision.CanHitLine(position, width, height, nPC6.position, nPC6.width, nPC6.height) && Distance(nPC6.Center) < 500f)
                    {
                        num18 = num19;
                    }
                }
                if (num18 != -1)
                {
                    ai[0] = 13f;
                    ai[1] = 34f;
                    ai[2] = num18;
                    localAI[3] = 0f;
                    direction = ((position.X < Main.npc[num18].position.X) ? 1 : (-1));
                    netUpdate = true;
                }
            }
            if (flag20 && velocity.Y == 0f && NPCID.Sets.AttackType[type] == 0 && NPCID.Sets.AttackAverageChance[type] > 0 && Main.rand.Next(NPCID.Sets.AttackAverageChance[type] * 2) == 0)
            {
                int num20 = NPCID.Sets.AttackTime[type];
                int num21 = ((num13 == 1) ? num35 : num24);
                int num22 = ((num13 == 1) ? num24 : num35);
                if (num21 != -1 && !Collision.CanHit(base.Center, 0, 0, Main.npc[num21].Center, 0, 0))
                {
                    num21 = ((num22 == -1 || !Collision.CanHit(base.Center, 0, 0, Main.npc[num22].Center, 0, 0)) ? (-1) : num22);
                }
                bool flag26 = num21 != -1;
                if (flag26 && type == 633)
                {
                    flag26 = Vector2.Distance(base.Center, Main.npc[num21].Center) <= 50f;
                }
                if (flag26)
                {
                    localAI[2] = ai[0];
                    ai[0] = 10f;
                    ai[1] = num20;
                    ai[2] = 0f;
                    localAI[3] = 0f;
                    direction = ((position.X < Main.npc[num21].position.X) ? 1 : (-1));
                    netUpdate = true;
                }
            }
            else if (flag20 && velocity.Y == 0f && NPCID.Sets.AttackType[type] == 1 && NPCID.Sets.AttackAverageChance[type] > 0 && Main.rand.Next(NPCID.Sets.AttackAverageChance[type] * 2) == 0)
            {
                int num23 = NPCID.Sets.AttackTime[type];
                int num25 = ((num13 == 1) ? num35 : num24);
                int num26 = ((num13 == 1) ? num24 : num35);
                if (num25 != -1 && !Collision.CanHitLine(base.Center, 0, 0, Main.npc[num25].Center, 0, 0))
                {
                    num25 = ((num26 == -1 || !Collision.CanHitLine(base.Center, 0, 0, Main.npc[num26].Center, 0, 0)) ? (-1) : num26);
                }
                if (num25 != -1)
                {
                    Vector2 vector8 = DirectionTo(Main.npc[num25].Center);
                    if (vector8.Y <= 0.5f && vector8.Y >= -0.5f)
                    {
                        localAI[2] = ai[0];
                        ai[0] = 12f;
                        ai[1] = num23;
                        ai[2] = vector8.Y;
                        localAI[3] = 0f;
                        direction = ((position.X < Main.npc[num25].position.X) ? 1 : (-1));
                        netUpdate = true;
                    }
                }
            }
            if (flag20 && velocity.Y == 0f && NPCID.Sets.AttackType[type] == 2 && NPCID.Sets.AttackAverageChance[type] > 0 && Main.rand.Next(NPCID.Sets.AttackAverageChance[type] * 2) == 0)
            {
                int num27 = NPCID.Sets.AttackTime[type];
                int num28 = ((num13 == 1) ? num35 : num24);
                int num29 = ((num13 == 1) ? num24 : num35);
                if (num28 != -1 && !Collision.CanHitLine(base.Center, 0, 0, Main.npc[num28].Center, 0, 0))
                {
                    num28 = ((num29 == -1 || !Collision.CanHitLine(base.Center, 0, 0, Main.npc[num29].Center, 0, 0)) ? (-1) : num29);
                }
                if (num28 != -1)
                {
                    localAI[2] = ai[0];
                    ai[0] = 14f;
                    ai[1] = num27;
                    ai[2] = 0f;
                    localAI[3] = 0f;
                    direction = ((position.X < Main.npc[num28].position.X) ? 1 : (-1));
                    netUpdate = true;
                }
                else if (type == 20)
                {
                    localAI[2] = ai[0];
                    ai[0] = 14f;
                    ai[1] = num27;
                    ai[2] = 0f;
                    localAI[3] = 0f;
                    netUpdate = true;
                }
            }
            if (flag20 && velocity.Y == 0f && NPCID.Sets.AttackType[type] == 3 && NPCID.Sets.AttackAverageChance[type] > 0 && Main.rand.Next(NPCID.Sets.AttackAverageChance[type] * 2) == 0)
            {
                int num30 = NPCID.Sets.AttackTime[type];
                int num31 = ((num13 == 1) ? num35 : num24);
                int num32 = ((num13 == 1) ? num24 : num35);
                if (num31 != -1 && !Collision.CanHit(base.Center, 0, 0, Main.npc[num31].Center, 0, 0))
                {
                    num31 = ((num32 == -1 || !Collision.CanHit(base.Center, 0, 0, Main.npc[num32].Center, 0, 0)) ? (-1) : num32);
                }
                if (num31 != -1)
                {
                    localAI[2] = ai[0];
                    ai[0] = 15f;
                    ai[1] = num30;
                    ai[2] = 0f;
                    localAI[3] = 0f;
                    direction = ((position.X < Main.npc[num31].position.X) ? 1 : (-1));
                    netUpdate = true;
                }
            }
        }
        if (type == 681)
        {
            float R = 0f;
            float G = 0f;
            float B = 0f;
            TorchID.TorchColor(23, out R, out G, out B);
            float num33 = 0.35f;
            R *= num33;
            G *= num33;
            B *= num33;
            Lighting.AddLight(base.Center, R, G, B);
        }
        if (type == 683 || type == 687)
        {
            float num34 = Utils.WrappedLerp(0.75f, 1f, (float)Main.timeForVisualEffects % 120f / 120f);
            Lighting.AddLight(base.Center, 0.25f * num34, 0.25f * num34, 0.1f * num34);
        }
    }
References Terraria.Entity.active, Terraria.Lighting.AddLight(), Terraria.DataStructures.AnchoredEntitiesCollection.AddNPC(), Terraria.NPC.ai, Terraria.Projectile.ai, Terraria.NPC.AI_007_AttemptToPlayIdleAnimationsForPets(), Terraria.NPC.AI_007_FindGoodRestingSpot(), Terraria.NPC.AI_007_TownEntities_CheckIfWillDrown(), Terraria.NPC.AI_007_TownEntities_GetWalkPrediction(), Terraria.NPC.AI_007_TownEntities_IsInAGoodRestingSpot(), Terraria.NPC.AI_007_TownEntities_Shimmer_TeleportToLandingSpot(), Terraria.NPC.AI_007_TownEntities_TeleportToHome(), Terraria.NPC.AI_007_TryForcingSitting(), Terraria.NPC.aiStyle, Terraria.ID.NPCID.Sets.AllowDoorInteraction, Terraria.ID.NPCID.Sets.AttackAverageChance, Terraria.ID.NPCID.Sets.AttackTime, Terraria.ID.NPCID.Sets.AttackType, Terraria.Entity.Bottom, Terraria.NPC.breath, Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastParticleSpawn(), Terraria.ModLoader.NPCLoader.BuffTownNPC(), Terraria.NPC.CanBeChasedBy(), Terraria.ID.TileID.Sets.CanBeSatOnForNPCs, Terraria.Player.CanBeTalkedTo, Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.ModLoader.NPCLoader.CanHitNPC(), Terraria.NPC.CanTalk, Terraria.Entity.Center, Terraria.NPC.closeDoor, Terraria.WorldGen.CloseDoor(), Terraria.ModLoader.TileLoader.CloseDoorID(), Terraria.NPC.collideX, Terraria.NPC.combatBookVolumeTwoWasUsed, Terraria.NPC.combatBookWasUsed, Terraria.NPC.damage, Terraria.ID.NPCID.Sets.DangerDetectRange, Terraria.Main.dayTime, Terraria.Player.dead, Terraria.NPC.defDefense, Terraria.NPC.defense, Terraria.Entity.direction, Terraria.Entity.DirectionTo(), Terraria.NPC.directionY, Terraria.Entity.Distance(), Terraria.NPC.dontTakeDamage, Terraria.NPC.doorX, Terraria.NPC.doorY, Terraria.NPC.downedAncientCultist, Terraria.NPC.downedBoss1, Terraria.NPC.downedBoss2, Terraria.NPC.downedBoss3, Terraria.NPC.downedEmpressOfLight, Terraria.NPC.downedGolemBoss, Terraria.NPC.downedMechBoss1, Terraria.NPC.downedMechBoss2, Terraria.NPC.downedMechBoss3, Terraria.NPC.downedPlantBoss, Terraria.NPC.downedQueenBee, Terraria.NPC.downedQueenSlime, Terraria.Collision.DrownCollision(), Terraria.NPC.dryadWard, Terraria.Main.dungeonX, Terraria.Main.dungeonY, Terraria.Main.eclipse, Terraria.Main.expertMode, Terraria.NPC.frameCounter, Terraria.NPC.friendly, Terraria.Main.GameModeInfo, Terraria.NPC.GetMagicAuraColor(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetSwingStats(), Terraria.NPC.GetTargetData(), Terraria.Framing.GetTileSafely(), Terraria.Collision.GetWaterLine(), Terraria.NPC.gfxOffY, Terraria.NPC.GivenName, Terraria.Main.hardMode, Terraria.Entity.height, Terraria.NPC.HitEffect(), Terraria.NPC.homeless, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Terraria.Entity.honeyWet, Terraria.Main.hslToRgb(), Terraria.ID.TileID.Sets.InteractibleByNPCs, Terraria.WorldGen.InWorld(), Terraria.ModLoader.TileLoader.IsClosedDoor(), Terraria.NPC.isLikeATownNPC, Terraria.NPC.IsShimmerVariant, Terraria.GameContent.PlayerSittingHelper.isSitting, Terraria.ID.NPCID.Sets.IsTownPet, Terraria.ID.NPCID.Sets.IsTownSlime, Terraria.Entity.lavaWet, Terraria.NPC.lazyNPCOwnedProjectileSearchArray, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Main.masterMode, Terraria.Main.maxTilesX, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.Dust.NewDustPerfect(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Projectile.noDropItem, Terraria.NPC.noTileCollide, Terraria.Main.npc, Terraria.Projectile.npcProj, Terraria.WorldGen.OpenDoor(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Utils.PlotTileLine(), Terraria.Entity.position, Terraria.ID.NPCID.Sets.PrettySafe, Terraria.Main.projectile, Terraria.Main.raining, Terraria.Main.rand, Terraria.Utils.RandomVector2(), Terraria.Utils.Remap(), Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Utils.RotatedBy(), Terraria.NPC.safeRangeX, Terraria.NPC.safeRangeY, Terraria.NPC.savedAngler, Terraria.NPC.savedBartender, Terraria.NPC.savedGoblin, Terraria.NPC.savedGolfer, Terraria.NPC.savedMech, Terraria.NPC.savedStylist, Terraria.NPC.savedTaxCollector, Terraria.NPC.savedWizard, Terraria.DelegateMethods.SearchAvoidedByNPCs(), Terraria.Main.sectionManager, Terraria.NetMessage.SendData(), Terraria.NPC.sHeight, Terraria.WorldGen.ShiftTallGate(), Terraria.NPC.ShimmeredTownNPCs, Terraria.NPC.shimmering, Terraria.NPC.shimmerTransparency, Terraria.Entity.shimmerWet, Terraria.NPC.ShouldBestiaryGirlBeLycantrope(), Terraria.NPC.SitDown(), Terraria.Player.sitting, Terraria.Main.sittingManager, Terraria.Entity.Size, Terraria.ID.NPCID.Sets.Skeletons, Terraria.Main.slimeRain, Terraria.WorldGen.SolidTile(), Terraria.Collision.SolidTiles(), Terraria.Collision.SolidTilesVersatile(), Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, Terraria.NPC.spriteDirection, Terraria.Collision.StepDown(), Terraria.NPC.stepSpeed, Terraria.Collision.StepUp(), Terraria.NPC.StrikeNPCNoInteraction(), Terraria.NPC.sWidth, Terraria.Player.talkNPC, Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.NPC.taxCollector, Terraria.NPC.Teleport(), Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.WorldSections.TileLoaded(), Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Main.timeForVisualEffects, Terraria.Projectile.timeLeft, Terraria.Entity.Top, Terraria.ID.TorchID.TorchColor(), Terraria.ID.NPCID.Sets.TownCritter, Terraria.NPC.townNPC, Terraria.ModLoader.NPCLoader.TownNPCAttackCooldown(), Terraria.ModLoader.NPCLoader.TownNPCAttackMagic(), Terraria.ModLoader.NPCLoader.TownNPCAttackProj(), Terraria.ModLoader.NPCLoader.TownNPCAttackProjSpeed(), Terraria.ModLoader.NPCLoader.TownNPCAttackShoot(), Terraria.ModLoader.NPCLoader.TownNPCAttackStrength(), Terraria.ModLoader.NPCLoader.TownNPCAttackSwing(), Terraria.DataStructures.GameModeData.TownNPCDamageMultiplier, Terraria.NPC.townNpcVariationIndex, Terraria.NPC.Transform(), Terraria.NPC.TweakSwingStats(), Terraria.NPC.type, Terraria.Projectile.type, Terraria.Tile.type, Terraria.NPC.UpdateHomeTileState(), Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Collision.WetCollision(), Terraria.Entity.whoAmI, Terraria.Entity.width, Terraria.Utils.WrappedLerp(), and Terraria.Main.xMas.
Referenced by Terraria.NPC.VanillaAI_Inner().