TModLoader: Terraria.NPC.AI_123_Deerclops_Movement
AI_123_Deerclops_Movement()
void Terraria.NPC.AI_123_Deerclops_Movement (bool haltMovement, bool goHome) inline private
    {
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0218: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_022a: Unknown result type (might be due to invalid IL or missing references)
        //IL_023b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0254: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        //IL_028a: Unknown result type (might be due to invalid IL or missing references)
        float num = (float)life / (float)lifeMax;
        float num6 = 1f - num;
        float num7 = 3.5f + 1f * num6;
        float num8 = 4f;
        float num9 = -0.4f;
        float min = -8f;
        float num10 = 0.4f;
        Rectangle rectangle = GetTargetData().Hitbox;
        if (goHome)
        {
            ((Rectangle)(ref rectangle))._002Ector(homeTileX * 16, homeTileY * 16, 16, 16);
            if (Distance(((Rectangle)(ref rectangle)).Center.ToVector2()) < 240f)
            {
                rectangle.X = (int)(base.Center.X + (float)(160 * direction));
            }
        }
        float num11 = (float)((Rectangle)(ref rectangle)).Center.X - base.Center.X;
        float num13 = Math.Abs(num11);
        if (goHome && num11 != 0f)
        {
            direction = (spriteDirection = Math.Sign(num11));
        }
        bool flag = num13 < 80f;
        bool flag2 = flag || haltMovement;
        if (ai[0] == -1f)
        {
            num11 = 5f;
            num7 = 5.35f;
            flag2 = false;
        }
        if (flag2)
        {
            velocity.X *= 0.9f;
            if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
            {
                velocity.X = 0f;
            }
        }
        else
        {
            int num12 = Math.Sign(num11);
            velocity.X = MathHelper.Lerp(velocity.X, (float)num12 * num7, 1f / num8);
        }
        int num2 = 40;
        int num3 = 20;
        int num4 = 0;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(base.Center.X - (float)(num2 / 2), position.Y + (float)height - (float)num3 + (float)num4);
        bool num14 = vector.X < (float)rectangle.X && vector.X + (float)width > (float)(rectangle.X + rectangle.Width);
        bool flag3 = vector.Y + (float)num3 < (float)(rectangle.Y + rectangle.Height - 16);
        bool acceptTopSurfaces = base.Bottom.Y >= (float)((Rectangle)(ref rectangle)).Top;
        bool flag4 = Collision.SolidCollision(vector, num2, num3, acceptTopSurfaces);
        bool flag5 = Collision.SolidCollision(vector, num2, num3 - 4, acceptTopSurfaces);
        bool flag6 = !Collision.SolidCollision(vector + new Vector2((float)(num2 * direction), 0f), 16, 80, acceptTopSurfaces);
        float num5 = 8f;
        if (flag4 || flag5)
        {
            localAI[0] = 0f;
        }
        if ((num14 || flag) && flag3)
        {
            velocity.Y = MathHelper.Clamp(velocity.Y + num10 * 2f, 0.001f, 16f);
        }
        else if (flag4 && !flag5)
        {
            velocity.Y = 0f;
        }
        else if (flag4)
        {
            velocity.Y = MathHelper.Clamp(velocity.Y + num9, min, 0f);
        }
        else if (velocity.Y == 0f && flag6)
        {
            velocity.Y = 0f - num5;
            localAI[0] = 1f;
        }
        else
        {
            velocity.Y = MathHelper.Clamp(velocity.Y + num10, 0f - num5, 16f);
        }
    }
References Terraria.NPC.ai, Terraria.Entity.direction, Terraria.Entity.Distance(), Terraria.NPC.GetTargetData(), Terraria.Entity.height, Terraria.DataStructures.NPCAimedTarget.Hitbox, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Entity.position, Terraria.Collision.SolidCollision(), Terraria.NPC.spriteDirection, Terraria.Entity.velocity, and Terraria.Entity.width.
Referenced by Terraria.NPC.AI_123_Deerclops().