TModLoader: Terraria.NPC.AI_026_Unicorns
AI_026_Unicorns()
void Terraria.NPC.AI_026_Unicorns () inline private
    {
        //IL_02bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0258: Unknown result type (might be due to invalid IL or missing references)
        //IL_026c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0271: Unknown result type (might be due to invalid IL or missing references)
        //IL_0291: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0319: Unknown result type (might be due to invalid IL or missing references)
        //IL_031e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0323: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_034f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0361: Unknown result type (might be due to invalid IL or missing references)
        //IL_0369: Unknown result type (might be due to invalid IL or missing references)
        //IL_036e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0375: Unknown result type (might be due to invalid IL or missing references)
        //IL_0382: Unknown result type (might be due to invalid IL or missing references)
        //IL_0388: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_072a: Unknown result type (might be due to invalid IL or missing references)
        //IL_072f: Unknown result type (might be due to invalid IL or missing references)
        //IL_073b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0745: Unknown result type (might be due to invalid IL or missing references)
        //IL_074a: Unknown result type (might be due to invalid IL or missing references)
        //IL_074f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0756: Unknown result type (might be due to invalid IL or missing references)
        //IL_076c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0772: Unknown result type (might be due to invalid IL or missing references)
        //IL_077f: Unknown result type (might be due to invalid IL or missing references)
        //IL_078d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0792: Unknown result type (might be due to invalid IL or missing references)
        //IL_0795: Unknown result type (might be due to invalid IL or missing references)
        //IL_0797: Unknown result type (might be due to invalid IL or missing references)
        //IL_079e: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0634: Unknown result type (might be due to invalid IL or missing references)
        //IL_063f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0811: Unknown result type (might be due to invalid IL or missing references)
        //IL_0816: Unknown result type (might be due to invalid IL or missing references)
        //IL_0822: Unknown result type (might be due to invalid IL or missing references)
        //IL_082c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0831: Unknown result type (might be due to invalid IL or missing references)
        //IL_0836: Unknown result type (might be due to invalid IL or missing references)
        //IL_083d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0853: Unknown result type (might be due to invalid IL or missing references)
        //IL_0859: Unknown result type (might be due to invalid IL or missing references)
        //IL_0866: Unknown result type (might be due to invalid IL or missing references)
        //IL_0874: Unknown result type (might be due to invalid IL or missing references)
        //IL_0879: Unknown result type (might be due to invalid IL or missing references)
        //IL_087c: Unknown result type (might be due to invalid IL or missing references)
        //IL_087e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0885: Unknown result type (might be due to invalid IL or missing references)
        //IL_088a: Unknown result type (might be due to invalid IL or missing references)
        //IL_088f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0895: Unknown result type (might be due to invalid IL or missing references)
        //IL_089c: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08db: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ccd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0afc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0975: Unknown result type (might be due to invalid IL or missing references)
        //IL_098b: Unknown result type (might be due to invalid IL or missing references)
        //IL_05be: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d17: Unknown result type (might be due to invalid IL or missing references)
        //IL_05dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_13f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_13f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1410: Unknown result type (might be due to invalid IL or missing references)
        //IL_1439: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_12f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1303: Unknown result type (might be due to invalid IL or missing references)
        //IL_1308: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fd7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fd9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fde: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fe5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ffe: Unknown result type (might be due to invalid IL or missing references)
        //IL_2004: Unknown result type (might be due to invalid IL or missing references)
        //IL_2012: Unknown result type (might be due to invalid IL or missing references)
        //IL_2017: Unknown result type (might be due to invalid IL or missing references)
        //IL_1553: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1570: Unknown result type (might be due to invalid IL or missing references)
        //IL_1889: Unknown result type (might be due to invalid IL or missing references)
        //IL_189a: Unknown result type (might be due to invalid IL or missing references)
        int num = 30;
        int num12 = 10;
        bool flag = false;
        bool flag2 = false;
        bool flag3 = false;
        if (velocity.Y == 0f && ((velocity.X > 0f && direction < 0) || (velocity.X < 0f && direction > 0)))
        {
            flag2 = true;
            ai[3] += 1f;
        }
        if (type == 546)
        {
            num12 = 4;
            bool flag4 = velocity.Y == 0f;
            for (int i = 0; i < 200; i++)
            {
                if (i != whoAmI && Main.npc[i].active && Main.npc[i].type == type && Math.Abs(position.X - Main.npc[i].position.X) + Math.Abs(position.Y - Main.npc[i].position.Y) < (float)width)
                {
                    if (position.X < Main.npc[i].position.X)
                    {
                        velocity.X -= 0.05f;
                    }
                    else
                    {
                        velocity.X += 0.05f;
                    }
                    if (position.Y < Main.npc[i].position.Y)
                    {
                        velocity.Y -= 0.05f;
                    }
                    else
                    {
                        velocity.Y += 0.05f;
                    }
                }
            }
            if (flag4)
            {
                velocity.Y = 0f;
            }
        }
        if (type == 315)
        {
            int num18 = 480;
            if (localAI[0]++ >= (float)num18)
            {
                localAI[0] = 0f;
                int num19 = target;
                if (Main.netMode != 1 && num19 != 255)
                {
                    int attackDamage_ForProjectiles = GetAttackDamage_ForProjectiles(40f, 30f);
                    Projectile.NewProjectile(GetSpawnSourceForNPCFromNPCAI(), base.Center + Main.rand.NextVector2Circular(40f, 40f), new Vector2(velocity.X, Main.rand.NextFloatDirection() * 3f), 1001, attackDamage_ForProjectiles, 0f, Main.myPlayer, num19);
                }
            }
            Lighting.AddLight(base.Center, 0.4f, 0.36f, 0.2f);
            int num20 = frame.Height;
            if (num20 < 1)
            {
                num20 = 1;
            }
            int num21 = frame.Y / num20;
            if (num21 >= 4 && num21 <= 7)
            {
                Vector2 vector = base.Bottom + new Vector2(-30f, -8f);
                Vector2 vector2 = default(Vector2);
                ((Vector2)(ref vector2))._002Ector(60f, 8f);
                if (Main.rand.Next(3) != 0)
                {
                    Dust dust = Dust.NewDustPerfect(vector + new Vector2(Main.rand.NextFloat() * vector2.X, Main.rand.NextFloat() * vector2.Y), 6, velocity);
                    dust.scale = 0.6f;
                    dust.fadeIn = 1.1f;
                    dust.noGravity = true;
                    dust.noLight = true;
                }
            }
        }
        if (position.X == oldPosition.X || ai[3] >= (float)num || flag2)
        {
            ai[3] += 1f;
            flag3 = true;
        }
        else if (ai[3] > 0f)
        {
            ai[3] -= 1f;
        }
        if (ai[3] > (float)(num * num12))
        {
            ai[3] = 0f;
        }
        if (justHit)
        {
            ai[3] = 0f;
        }
        if (ai[3] == (float)num)
        {
            netUpdate = true;
        }
        Vector2 vector3 = default(Vector2);
        ((Vector2)(ref vector3))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
        float num24 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector3.X;
        float num22 = Main.player[target].position.Y - vector3.Y;
        float num23 = (float)Math.Sqrt(num24 * num24 + num22 * num22);
        if (num23 < 200f && !flag3)
        {
            ai[3] = 0f;
        }
        if (type == 410)
        {
            ai[1] += 1f;
            bool flag5 = ai[1] >= 240f;
            if (!flag5 && velocity.Y == 0f)
            {
                for (int j = 0; j < 255; j++)
                {
                    if (Main.player[j].active && !Main.player[j].dead && Main.player[j].Distance(base.Center) < 800f && Main.player[j].Center.Y < base.Center.Y && Math.Abs(Main.player[j].Center.X - base.Center.X) < 20f)
                    {
                        flag5 = true;
                        break;
                    }
                }
            }
            if (flag5 && Main.netMode != 1)
            {
                for (int k = 0; k < 3; k++)
                {
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, (Main.rand.NextFloat() - 0.5f) * 2f, -4f - 10f * Main.rand.NextFloat(), 538, 50, 0f, Main.myPlayer);
                }
                HitEffect(9999);
                active = false;
                return;
            }
        }
        else if (type == 423)
        {
            if (ai[2] == 1f)
            {
                ai[1] += 1f;
                velocity.X *= 0.7f;
                if (ai[1] < 30f)
                {
                    Vector2 vector4 = base.Center + Vector2.UnitX * (float)spriteDirection * -20f;
                    Dust obj = Main.dust[Dust.NewDust(vector4, 0, 0, 242)];
                    Vector2 vector5 = Vector2.UnitY.RotatedByRandom(6.2831854820251465);
                    obj.position = vector4 + vector5 * 20f;
                    obj.velocity = -vector5 * 2f;
                    obj.scale = 0.5f + vector5.X * (float)(-spriteDirection);
                    obj.fadeIn = 1f;
                    obj.noGravity = true;
                }
                else if (ai[1] == 30f)
                {
                    for (int l = 0; l < 20; l++)
                    {
                        Vector2 vector6 = base.Center + Vector2.UnitX * (float)spriteDirection * -20f;
                        Dust obj2 = Main.dust[Dust.NewDust(vector6, 0, 0, 242)];
                        Vector2 vector7 = Vector2.UnitY.RotatedByRandom(6.2831854820251465);
                        obj2.position = vector6 + vector7 * 4f;
                        obj2.velocity = vector7 * 4f + Vector2.UnitX * Main.rand.NextFloat() * (float)spriteDirection * -5f;
                        obj2.scale = 0.5f + vector7.X * (float)(-spriteDirection);
                        obj2.fadeIn = 1f;
                        obj2.noGravity = true;
                    }
                }
                if (velocity.X > -0.5f && velocity.X < 0.5f)
                {
                    velocity.X = 0f;
                }
                if (ai[1] == 30f && Main.netMode != 1)
                {
                    int attackDamage_ForProjectiles2 = GetAttackDamage_ForProjectiles(50f, 35f);
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X + (float)(spriteDirection * -20), base.Center.Y, spriteDirection * -7, 0f, 575, attackDamage_ForProjectiles2, 0f, Main.myPlayer, target);
                }
                if (ai[1] >= 60f)
                {
                    ai[1] = -Main.rand.Next(320, 601);
                    ai[2] = 0f;
                }
            }
            else
            {
                ai[1] += 1f;
                if (ai[1] >= 180f && num23 < 500f && velocity.Y == 0f)
                {
                    flag = true;
                    ai[1] = 0f;
                    ai[2] = 1f;
                    netUpdate = true;
                }
                else if (velocity.Y == 0f && num23 < 100f && Math.Abs(velocity.X) > 3f && ((base.Center.X < Main.player[target].Center.X && velocity.X > 0f) || (base.Center.X > Main.player[target].Center.X && velocity.X < 0f)))
                {
                    velocity.Y -= 4f;
                }
            }
        }
        else if (type == 155 || type == 329)
        {
            if (velocity.Y == 0f && num23 < 100f && Math.Abs(velocity.X) > 3f && ((position.X + (float)(width / 2) < Main.player[target].position.X + (float)(Main.player[target].width / 2) && velocity.X > 0f) || (position.X + (float)(width / 2) > Main.player[target].position.X + (float)(Main.player[target].width / 2) && velocity.X < 0f)))
            {
                velocity.Y -= 4f;
            }
        }
        else if (type == 546 && velocity.Y == 0f && Math.Abs(velocity.X) > 3f && ((base.Center.X < Main.player[target].Center.X && velocity.X > 0f) || (base.Center.X > Main.player[target].Center.X && velocity.X < 0f)))
        {
            velocity.Y -= 4f;
            SoundEngine.PlaySound(3, base.Center, 11);
        }
        if (type == 546 && !Main.player[target].ZoneDesert)
        {
            int num2 = direction;
            TargetClosest();
            if (!Main.player[target].ZoneDesert)
            {
                EncourageDespawn(10);
                ai[3] = num;
                direction = num2;
            }
        }
        if (ai[3] < (float)num)
        {
            if ((type == 329 || type == 315) && !Main.pumpkinMoon)
            {
                EncourageDespawn(10);
            }
            else
            {
                TargetClosest();
            }
        }
        else
        {
            if (velocity.X == 0f)
            {
                if (velocity.Y == 0f)
                {
                    ai[0] += 1f;
                    if (ai[0] >= 2f)
                    {
                        direction *= -1;
                        spriteDirection = direction;
                        ai[0] = 0f;
                    }
                }
            }
            else
            {
                ai[0] = 0f;
            }
            directionY = -1;
            if (direction == 0)
            {
                direction = 1;
            }
        }
        float num3 = 6f;
        float num4 = 0.07f;
        if (!flag && (velocity.Y == 0f || wet || (velocity.X <= 0f && direction < 0) || (velocity.X >= 0f && direction > 0)))
        {
            if (type == 155)
            {
                if (velocity.X > 0f && direction < 0)
                {
                    velocity.X *= 0.95f;
                }
                if (velocity.X < 0f && direction > 0)
                {
                    velocity.X *= 0.95f;
                }
            }
            else if (type == 329)
            {
                if (velocity.X > 0f && direction < 0)
                {
                    velocity.X *= 0.9f;
                }
                if (velocity.X < 0f && direction > 0)
                {
                    velocity.X *= 0.9f;
                }
                if (direction > 0 && velocity.X < 3f)
                {
                    velocity.X += 0.1f;
                }
                if (direction < 0 && velocity.X > -3f)
                {
                    velocity.X -= 0.1f;
                }
            }
            else if (type == 315)
            {
                if (velocity.X > 0f && direction < 0)
                {
                    velocity.X *= 0.95f;
                }
                if (velocity.X < 0f && direction > 0)
                {
                    velocity.X *= 0.95f;
                }
                if (velocity.X < 0f - num3 || velocity.X > num3)
                {
                    if (velocity.Y == 0f)
                    {
                        velocity *= 0.8f;
                    }
                }
                else if (velocity.X < num3 && direction == 1)
                {
                    velocity.X += 0.07f;
                    if (velocity.X > num3)
                    {
                        velocity.X = num3;
                    }
                }
                else if (velocity.X > 0f - num3 && direction == -1)
                {
                    velocity.X -= 0.07f;
                    if (velocity.X < 0f - num3)
                    {
                        velocity.X = 0f - num3;
                    }
                }
            }
            else if (type == 410)
            {
                if (Math.Sign(velocity.X) != direction)
                {
                    velocity.X *= 0.9f;
                }
                num3 = 6f;
                num4 = 0.2f;
            }
            else if (type == 423)
            {
                if (Math.Sign(velocity.X) != direction)
                {
                    velocity.X *= 0.85f;
                }
                num3 = 10f;
                num4 = 0.2f;
            }
            else if (type == 546)
            {
                if (Math.Sign(velocity.X) != direction)
                {
                    velocity.X *= 0.92f;
                }
                float num5 = MathHelper.Lerp(0.6f, 1f, Math.Abs(Main.windSpeedTarget)) * (float)Math.Sign(Main.windSpeedTarget);
                if (!Main.player[target].ZoneSandstorm)
                {
                    num5 = 0f;
                }
                num3 = 4f + num5 * (float)direction * 3f;
                num4 = 0.05f;
            }
            if (velocity.X < 0f - num3 || velocity.X > num3)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.8f;
                }
            }
            else if (velocity.X < num3 && direction == 1)
            {
                velocity.X += num4;
                if (velocity.X > num3)
                {
                    velocity.X = num3;
                }
            }
            else if (velocity.X > 0f - num3 && direction == -1)
            {
                velocity.X -= num4;
                if (velocity.X < 0f - num3)
                {
                    velocity.X = 0f - num3;
                }
            }
        }
        if (velocity.Y >= 0f)
        {
            int num6 = 0;
            if (velocity.X < 0f)
            {
                num6 = -1;
            }
            if (velocity.X > 0f)
            {
                num6 = 1;
            }
            Vector2 vector8 = position;
            vector8.X += velocity.X;
            int num7 = (int)((vector8.X + (float)(width / 2) + (float)((width / 2 + 1) * num6)) / 16f);
            int num8 = (int)((vector8.Y + (float)height - 1f) / 16f);
            if (Main.tile[num7, num8] == null)
            {
                Main.tile[num7, num8] = default(Tile);
            }
            if (Main.tile[num7, num8 - 1] == null)
            {
                Main.tile[num7, num8 - 1] = default(Tile);
            }
            if (Main.tile[num7, num8 - 2] == null)
            {
                Main.tile[num7, num8 - 2] = default(Tile);
            }
            if (Main.tile[num7, num8 - 3] == null)
            {
                Main.tile[num7, num8 - 3] = default(Tile);
            }
            if (Main.tile[num7, num8 + 1] == null)
            {
                Main.tile[num7, num8 + 1] = default(Tile);
            }
            if ((float)(num7 * 16) < vector8.X + (float)width && (float)(num7 * 16 + 16) > vector8.X && ((Main.tile[num7, num8].nactive() && !Main.tile[num7, num8].topSlope() && !Main.tile[num7, num8 - 1].topSlope() && Main.tileSolid[Main.tile[num7, num8].type] && !Main.tileSolidTop[Main.tile[num7, num8].type]) || (Main.tile[num7, num8 - 1].halfBrick() && Main.tile[num7, num8 - 1].nactive())) && (!Main.tile[num7, num8 - 1].nactive() || !Main.tileSolid[Main.tile[num7, num8 - 1].type] || Main.tileSolidTop[Main.tile[num7, num8 - 1].type] || (Main.tile[num7, num8 - 1].halfBrick() && (!Main.tile[num7, num8 - 4].nactive() || !Main.tileSolid[Main.tile[num7, num8 - 4].type] || Main.tileSolidTop[Main.tile[num7, num8 - 4].type]))) && (!Main.tile[num7, num8 - 2].nactive() || !Main.tileSolid[Main.tile[num7, num8 - 2].type] || Main.tileSolidTop[Main.tile[num7, num8 - 2].type]) && (!Main.tile[num7, num8 - 3].nactive() || !Main.tileSolid[Main.tile[num7, num8 - 3].type] || Main.tileSolidTop[Main.tile[num7, num8 - 3].type]) && (!Main.tile[num7 - num6, num8 - 3].nactive() || !Main.tileSolid[Main.tile[num7 - num6, num8 - 3].type]))
            {
                float num9 = num8 * 16;
                if (Main.tile[num7, num8].halfBrick())
                {
                    num9 += 8f;
                }
                if (Main.tile[num7, num8 - 1].halfBrick())
                {
                    num9 -= 8f;
                }
                if (num9 < vector8.Y + (float)height)
                {
                    float num10 = vector8.Y + (float)height - num9;
                    if ((double)num10 <= 16.1)
                    {
                        gfxOffY += position.Y + (float)height - num9;
                        position.Y = num9 - (float)height;
                        if (num10 < 9f)
{
                            stepSpeed = 1f;
                        }
                        else
{
                            stepSpeed = 2f;
                        }
                    }
                }
            }
        }
        if (velocity.Y == 0f)
        {
            bool flag6 = true;
            int num11 = (int)(position.Y - 7f) / 16;
            int num25 = (int)(position.X - 7f) / 16;
            int num13 = (int)(position.X + (float)width + 7f) / 16;
            for (int m = num25; m <= num13; m++)
            {
                if (Main.tile[m, num11] != null && Main.tile[m, num11].nactive() && Main.tileSolid[Main.tile[m, num11].type])
                {
                    flag6 = false;
                    break;
                }
            }
            if (flag6)
            {
                int num14 = (int)((position.X + (float)(width / 2) + (float)((width / 2 + 2) * direction) + velocity.X * 5f) / 16f);
                int num15 = (int)((position.Y + (float)height - 15f) / 16f);
                if (Main.tile[num14, num15] == null)
                {
                    Main.tile[num14, num15] = default(Tile);
                }
                if (Main.tile[num14, num15 - 1] == null)
                {
                    Main.tile[num14, num15 - 1] = default(Tile);
                }
                if (Main.tile[num14, num15 - 2] == null)
                {
                    Main.tile[num14, num15 - 2] = default(Tile);
                }
                if (Main.tile[num14, num15 - 3] == null)
                {
                    Main.tile[num14, num15 - 3] = default(Tile);
                }
                if (Main.tile[num14, num15 + 1] == null)
                {
                    Main.tile[num14, num15 + 1] = default(Tile);
                }
                if (Main.tile[num14 + direction, num15 - 1] == null)
                {
                    Main.tile[num14 + direction, num15 - 1] = default(Tile);
                }
                if (Main.tile[num14 + direction, num15 + 1] == null)
                {
                    Main.tile[num14 + direction, num15 + 1] = default(Tile);
                }
                if (Main.tile[num14 - direction, num15 + 1] == null)
                {
                    Main.tile[num14 - direction, num15 + 1] = default(Tile);
                }
                if (Main.tile[num14 + direction, num15 + 3] == null)
                {
                    Main.tile[num14 + direction, num15 + 3] = default(Tile);
                }
                int num16 = spriteDirection;
                if (type == 423 || type == 410 || type == 546)
                {
                    num16 *= -1;
                }
                if ((velocity.X < 0f && num16 == -1) || (velocity.X > 0f && num16 == 1))
                {
                    bool flag7 = type == 410 || type == 423;
                    float num17 = 3f;
                    if (Main.tile[num14, num15 - 2].nactive() && Main.tileSolid[Main.tile[num14, num15 - 2].type])
                    {
                        if (Main.tile[num14, num15 - 3].nactive() && Main.tileSolid[Main.tile[num14, num15 - 3].type])
{
                            velocity.Y = -8.5f;
                            netUpdate = true;
                        }
                        else
{
                            velocity.Y = -7.5f;
                            netUpdate = true;
                        }
                    }
                    else if (Main.tile[num14, num15 - 1].nactive() && !Main.tile[num14, num15 - 1].topSlope() && Main.tileSolid[Main.tile[num14, num15 - 1].type])
                    {
                        velocity.Y = -7f;
                        netUpdate = true;
                    }
                    else if (position.Y + (float)height - (float)(num15 * 16) > 20f && Main.tile[num14, num15].nactive() && !Main.tile[num14, num15].topSlope() && Main.tileSolid[Main.tile[num14, num15].type])
                    {
                        velocity.Y = -6f;
                        netUpdate = true;
                    }
                    else if ((directionY < 0 || Math.Abs(velocity.X) > num17) && (!flag7 || !Main.tile[num14, num15 + 1].nactive() || !Main.tileSolid[Main.tile[num14, num15 + 1].type]) && (!Main.tile[num14, num15 + 2].nactive() || !Main.tileSolid[Main.tile[num14, num15 + 2].type]) && (!Main.tile[num14 + direction, num15 + 3].nactive() || !Main.tileSolid[Main.tile[num14 + direction, num15 + 3].type]))
                    {
                        velocity.Y = -8f;
                        netUpdate = true;
                    }
                }
            }
        }
        if (type == 423 && Math.Abs(velocity.X) >= num3 * 0.95f)
        {
            Rectangle hitbox = base.Hitbox;
            for (int n = 0; n < 2; n++)
            {
                if (Main.rand.Next(3) == 0)
                {
                    Dust obj3 = Main.dust[Dust.NewDust(hitbox.TopLeft(), hitbox.Width, hitbox.Height, 242)];
                    obj3.velocity = Vector2.Zero;
                    obj3.noGravity = true;
                    obj3.fadeIn = 1f;
                    obj3.scale = 0.5f + Main.rand.NextFloat();
                }
            }
        }
        if (type == 546)
        {
            rotation += velocity.X * 0.05f;
            spriteDirection = -direction;
        }
    }
References Terraria.Entity.active, Terraria.Lighting.AddLight(), Terraria.NPC.ai, Terraria.Entity.direction, Terraria.NPC.directionY, Terraria.Main.dust, Terraria.NPC.EncourageDespawn(), Terraria.NPC.frame, Terraria.NPC.GetAttackDamage_ForProjectiles(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.NPC.gfxOffY, Terraria.Entity.height, Terraria.NPC.HitEffect(), Terraria.NPC.justHit, Terraria.NPC.localAI, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.Entity.oldPosition, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.pumpkinMoon, Terraria.Main.rand, Terraria.NPC.rotation, Terraria.NPC.spriteDirection, Terraria.NPC.stepSpeed, Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.NPC.type, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Entity.whoAmI, Terraria.Entity.width, and Terraria.Main.windSpeedTarget.
Referenced by Terraria.NPC.VanillaAI_Inner().