TModLoader: Terraria.NPC.UpdateNPC_BuffApplyVFX
UpdateNPC_BuffApplyVFX()
void Terraria.NPC.UpdateNPC_BuffApplyVFX () inline private
Definition at line 108008 of file NPC.cs.
    {
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0397: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0400: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_050b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0511: Unknown result type (might be due to invalid IL or missing references)
        //IL_0529: Unknown result type (might be due to invalid IL or missing references)
        //IL_0533: Unknown result type (might be due to invalid IL or missing references)
        //IL_0538: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0633: Unknown result type (might be due to invalid IL or missing references)
        //IL_0639: Unknown result type (might be due to invalid IL or missing references)
        //IL_064d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0657: Unknown result type (might be due to invalid IL or missing references)
        //IL_065c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0694: Unknown result type (might be due to invalid IL or missing references)
        //IL_0699: Unknown result type (might be due to invalid IL or missing references)
        //IL_069f: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0723: Unknown result type (might be due to invalid IL or missing references)
        //IL_0728: Unknown result type (might be due to invalid IL or missing references)
        //IL_075a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0779: Unknown result type (might be due to invalid IL or missing references)
        //IL_090b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0949: Unknown result type (might be due to invalid IL or missing references)
        //IL_094f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0963: Unknown result type (might be due to invalid IL or missing references)
        //IL_0983: Unknown result type (might be due to invalid IL or missing references)
        //IL_0988: Unknown result type (might be due to invalid IL or missing references)
        //IL_098d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0867: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a20: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a25: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a85: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07db: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0803: Unknown result type (might be due to invalid IL or missing references)
        //IL_0808: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b03: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b14: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b35: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b52: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b63: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b76: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b80: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b85: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bbe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cde: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ebf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e03: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fed: Unknown result type (might be due to invalid IL or missing references)
        //IL_102d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1033: Unknown result type (might be due to invalid IL or missing references)
        //IL_104b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1055: Unknown result type (might be due to invalid IL or missing references)
        //IL_105a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d38: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d42: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1118: Unknown result type (might be due to invalid IL or missing references)
        //IL_1158: Unknown result type (might be due to invalid IL or missing references)
        //IL_115e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1176: Unknown result type (might be due to invalid IL or missing references)
        //IL_1180: Unknown result type (might be due to invalid IL or missing references)
        //IL_1185: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e56: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e60: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e65: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e82: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e92: Unknown result type (might be due to invalid IL or missing references)
        //IL_1243: Unknown result type (might be due to invalid IL or missing references)
        //IL_1280: Unknown result type (might be due to invalid IL or missing references)
        //IL_1286: Unknown result type (might be due to invalid IL or missing references)
        //IL_129e: Unknown result type (might be due to invalid IL or missing references)
        //IL_12a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f78: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0faa: Unknown result type (might be due to invalid IL or missing references)
        //IL_1400: Unknown result type (might be due to invalid IL or missing references)
        //IL_1406: Unknown result type (might be due to invalid IL or missing references)
        //IL_140b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1410: Unknown result type (might be due to invalid IL or missing references)
        if (!canDisplayBuffs)
        {
            return;
        }
        position += netOffset;
        if (markedByScytheWhip && Main.rand.Next(3) == 0)
        {
            ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.BlackLightningSmall, new ParticleOrchestraSettings
            {
                MovementVector = Main.rand.NextVector2Circular(1f, 1f),
                PositionInWorld = Main.rand.NextVector2FromRectangle(base.Hitbox)
            });
        }
        if (poisoned && Main.rand.Next(30) == 0)
        {
            Dust dust24 = Dust.NewDustDirect(position, width, height, 46, 0f, 0f, 120, default(Color), 0.2f);
            dust24.noGravity = true;
            dust24.fadeIn = 1.9f;
        }
        if (venom && Main.rand.Next(10) == 0)
        {
            Dust dust25 = Dust.NewDustDirect(position, width, height, 171, 0f, 0f, 100, default(Color), 0.5f);
            dust25.noGravity = true;
            dust25.fadeIn = 1.5f;
        }
        if (shadowFlame && Main.rand.Next(5) < 4)
        {
            Dust dust19 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 27, velocity.X * 0.4f, velocity.Y * 0.4f, 180, default(Color), 1.95f);
            dust19.noGravity = true;
            dust19.velocity *= 0.75f;
            dust19.velocity.X *= 0.75f;
            dust19.velocity.Y -= 1f;
            if (Main.rand.Next(4) == 0)
            {
                dust19.noGravity = false;
                dust19.scale *= 0.5f;
            }
        }
        if (onFire)
        {
            if (Main.rand.Next(4) < 3)
            {
                Dust dust20 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 6, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3.5f);
                dust20.noGravity = true;
                dust20.velocity *= 1.8f;
                dust20.velocity.Y -= 0.5f;
                if (Main.rand.Next(4) == 0)
                {
                    dust20.noGravity = false;
                    dust20.scale *= 0.5f;
                }
            }
            Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f + 1f), 1f, 0.3f, 0.1f);
        }
        if (onFire3)
        {
            if (Main.rand.Next(4) < 3)
            {
                Dust dust21 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 6, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3.5f);
                dust21.noGravity = true;
                dust21.velocity *= 1.8f;
                dust21.velocity.Y -= 0.5f;
                if (Main.rand.Next(4) == 0)
                {
                    dust21.noGravity = false;
                    dust21.scale *= 0.5f;
                }
                dust21.customData = 0;
            }
            Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f + 1f), 1f, 0.3f, 0.1f);
        }
        if (daybreak)
        {
            if (Main.rand.Next(4) < 3)
            {
                Dust dust22 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 158, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3.5f);
                dust22.noGravity = true;
                dust22.velocity *= 2.8f;
                dust22.velocity.Y -= 0.5f;
                if (Main.rand.Next(4) == 0)
                {
                    dust22.noGravity = false;
                    dust22.scale *= 0.5f;
                }
            }
            Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f + 1f), 1f, 0.3f, 0.1f);
        }
        if (betsysCurse)
        {
            if (Main.rand.Next(4) < 3)
            {
                Dust dust26 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 55, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3.5f);
                dust26.noGravity = true;
                dust26.velocity *= 2.8f;
                dust26.velocity.Y -= 1.5f;
                dust26.noGravity = false;
                dust26.scale = 0.9f;
                dust26.color = new Color(0, 0, 180, 255);
                dust26.velocity *= 0.2f;
            }
            Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f + 1f), 0.6f, 0.1f, 0.9f);
        }
        if (oiled && Main.rand.Next(3) != 0)
        {
            int num = 175;
            Color newColor = default(Color);
            ((Color)(ref newColor))._002Ector(0, 0, 0, 250);
            Vector2 vector = position;
            vector.X -= 2f;
            vector.Y -= 2f;
            if (Main.rand.Next(2) == 0)
            {
                Dust dust23 = Dust.NewDustDirect(vector, width + 4, height + 2, 4, 0f, 0f, num, newColor, 1.4f);
                if (Main.rand.Next(2) == 0)
                {
                    dust23.alpha += 25;
                }
                if (Main.rand.Next(2) == 0)
                {
                    dust23.alpha += 25;
                }
                dust23.noLight = true;
                dust23.velocity *= 0.2f;
                dust23.velocity.Y += 0.2f;
                dust23.velocity += velocity;
            }
        }
        if (dryadWard && velocity.X != 0f && Main.rand.Next(4) == 0)
        {
            Dust dust27 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y + (float)height - 2f), width + 4, 4, 163, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 1.5f);
            dust27.noGravity = true;
            dust27.noLight = true;
            dust27.velocity *= 0f;
        }
        if (dryadBane && Main.rand.Next(4) == 0)
        {
            Dust dust28 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y), width + 4, height, 163, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 1.5f);
            dust28.noGravity = true;
            dust28.velocity *= new Vector2(Main.rand.NextFloat() * 4f - 2f, 0f);
            dust28.noLight = true;
        }
        if (loveStruck && Main.rand.Next(5) == 0)
        {
            Vector2 vector2 = default(Vector2);
            ((Vector2)(ref vector2))._002Ector((float)Main.rand.Next(-10, 11), (float)Main.rand.Next(-10, 11));
            ((Vector2)(ref vector2)).Normalize();
            vector2.X *= 0.66f;
            int num2 = Gore.NewGore(position + new Vector2((float)Main.rand.Next(width + 1), (float)Main.rand.Next(height + 1)), vector2 * (float)Main.rand.Next(3, 6) * 0.33f, 331, (float)Main.rand.Next(40, 121) * 0.01f);
            Main.gore[num2].sticky = false;
            Gore obj = Main.gore[num2];
            obj.velocity *= 0.4f;
            Main.gore[num2].velocity.Y -= 0.6f;
        }
        if (stinky && Main.rand.Next(5) == 0)
        {
            Vector2 vector3 = default(Vector2);
            ((Vector2)(ref vector3))._002Ector((float)Main.rand.Next(-10, 11), (float)Main.rand.Next(-10, 11));
            ((Vector2)(ref vector3)).Normalize();
            vector3.X *= 0.66f;
            vector3.Y = Math.Abs(vector3.Y);
            Vector2 vector4 = vector3 * (float)Main.rand.Next(3, 5) * 0.25f;
            Dust dust29 = Dust.NewDustDirect(position, width, height, 188, vector4.X, vector4.Y * 0.5f, 100, default(Color), 1.5f);
            dust29.velocity *= 0.1f;
            dust29.velocity.Y -= 0.5f;
        }
        if (dripping && Main.rand.Next(4) != 0)
        {
            Vector2 vector5 = position;
            vector5.X -= 2f;
            vector5.Y -= 2f;
            if (Main.rand.Next(2) == 0)
            {
                Dust dust12 = Dust.NewDustDirect(vector5, width + 4, height + 2, 211, 0f, 0f, 50, default(Color), 0.8f);
                if (Main.rand.Next(2) == 0)
                {
                    dust12.alpha += 25;
                }
                if (Main.rand.Next(2) == 0)
                {
                    dust12.alpha += 25;
                }
                dust12.noLight = true;
                dust12.velocity *= 0.2f;
                dust12.velocity.Y += 0.2f;
                dust12.velocity += velocity;
            }
            else
            {
                Dust dust13 = Dust.NewDustDirect(vector5, width + 8, height + 8, 211, 0f, 0f, 50, default(Color), 1.1f);
                if (Main.rand.Next(2) == 0)
                {
                    dust13.alpha += 25;
                }
                if (Main.rand.Next(2) == 0)
                {
                    dust13.alpha += 25;
                }
                dust13.noLight = true;
                dust13.noGravity = true;
                dust13.velocity *= 0.2f;
                dust13.velocity.Y += 1f;
                dust13.velocity += velocity;
            }
        }
        if (drippingSlime && Main.rand.Next(4) != 0)
        {
            int num3 = 175;
            Color newColor2 = default(Color);
            ((Color)(ref newColor2))._002Ector(0, 80, 255, 100);
            Vector2 vector6 = position;
            vector6.X -= 2f;
            vector6.Y -= 2f;
            if (Main.rand.Next(2) == 0)
            {
                Dust dust14 = Dust.NewDustDirect(vector6, width + 4, height + 2, 4, 0f, 0f, num3, newColor2, 1.4f);
                if (Main.rand.Next(2) == 0)
                {
                    dust14.alpha += 25;
                }
                if (Main.rand.Next(2) == 0)
                {
                    dust14.alpha += 25;
                }
                dust14.noLight = true;
                dust14.velocity *= 0.2f;
                dust14.velocity.Y += 0.2f;
                dust14.velocity += velocity;
            }
        }
        if (drippingSparkleSlime && Main.rand.Next(4) != 0)
        {
            int num4 = 150;
            Vector2 vector7 = position;
            vector7.X -= 2f;
            vector7.Y -= 2f;
            if (Main.rand.Next(2) == 0)
            {
                Dust dust15 = Dust.NewDustDirect(vector7, width + 4, height + 2, 243, 0f, 0f, num4);
                if (Main.rand.Next(2) == 0)
                {
                    dust15.alpha += 25;
                }
                if (Main.rand.Next(2) == 0)
                {
                    dust15.alpha += 25;
                }
                dust15.noLight = true;
                dust15.velocity *= 0.2f;
                dust15.velocity.Y += 0.2f;
                dust15.velocity += velocity;
            }
        }
        if (onFrostBurn)
        {
            if (Main.rand.Next(4) < 3)
            {
                Dust dust16 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 135, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3.5f);
                dust16.noGravity = true;
                dust16.velocity *= 1.8f;
                dust16.velocity.Y -= 0.5f;
                if (Main.rand.Next(4) == 0)
                {
                    dust16.noGravity = false;
                    dust16.scale *= 0.5f;
                }
            }
            Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f + 1f), 0.1f, 0.6f, 1f);
        }
        if (onFrostBurn2)
        {
            if (Main.rand.Next(4) < 3)
            {
                Dust dust17 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 135, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3.5f);
                dust17.noGravity = true;
                dust17.velocity *= 1.8f;
                dust17.velocity.Y -= 0.5f;
                if (Main.rand.Next(4) == 0)
                {
                    dust17.noGravity = false;
                    dust17.scale *= 0.5f;
                }
            }
            Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f + 1f), 0.1f, 0.6f, 1f);
        }
        if (onFire2)
        {
            if (Main.rand.Next(4) < 3)
            {
                Dust dust18 = Dust.NewDustDirect(new Vector2(position.X - 2f, position.Y - 2f), width + 4, height + 4, 75, velocity.X * 0.4f, velocity.Y * 0.4f, 100, default(Color), 3.5f);
                dust18.noGravity = true;
                dust18.velocity *= 1.8f;
                dust18.velocity.Y -= 0.5f;
                if (Main.rand.Next(4) == 0)
                {
                    dust18.noGravity = false;
                    dust18.scale *= 0.5f;
                }
            }
            Lighting.AddLight((int)(position.X / 16f), (int)(position.Y / 16f + 1f), 1f, 0.3f, 0.1f);
        }
        netShimmer = false;
        if (shimmering)
        {
            shimmerTransparency += 0.01f;
            if (Main.netMode != 1 && (double)shimmerTransparency > 0.9)
            {
                GetShimmered();
            }
            if (shimmerTransparency > 1f)
            {
                shimmerTransparency = 1f;
            }
        }
        else if (shimmerTransparency > 0f)
        {
            if (justHit)
            {
                shimmerTransparency -= 0.1f;
            }
            if (buffImmune[353])
            {
                shimmerTransparency -= 0.015f;
            }
            else
            {
                shimmerTransparency -= 0.001f;
            }
            if (shimmerTransparency < 0f)
            {
                shimmerTransparency = 0f;
            }
        }
        position -= netOffset;
    }
References Terraria.Lighting.AddLight(), Terraria.Main.gore, Terraria.Main.netMode, Terraria.Dust.NewDustDirect(), Terraria.Gore.NewGore(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Gore.sticky, and Terraria.Gore.velocity.