TModLoader: Terraria.NPC.BloodNautilus_CallForHelp
BloodNautilus_CallForHelp()
void Terraria.NPC.BloodNautilus_CallForHelp () inline private
    {
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode == 1 || !Main.player[target].active || Main.player[target].dead || Distance(Main.player[target].Center) > 2000f || CountNPCS(619) >= 3)
        {
            return;
        }
        Point point = base.Center.ToTileCoordinates();
        Point point2 = point;
        int num = 20;
        int num2 = 3;
        int num3 = 8;
        int num4 = 2;
        int num5 = 0;
        bool flag = false;
        while (!flag && num5 < 100)
        {
            num5++;
            int num6 = Main.rand.Next(point2.X - num, point2.X + num + 1);
            int num7 = Main.rand.Next(point2.Y - num, point2.Y + num + 1);
            if ((num7 < point2.Y - num3 || num7 > point2.Y + num3 || num6 < point2.X - num3 || num6 > point2.X + num3) && (num7 < point.Y - num2 || num7 > point.Y + num2 || num6 < point.X - num2 || num6 > point.X + num2) && !Main.tile[num6, num7].nactive())
            {
                bool flag2 = true;
                if (flag2 && Main.tile[num6, num7].lava())
                {
                    flag2 = false;
                }
                if (flag2 && Collision.SolidTiles(num6 - num4, num6 + num4, num7 - num4, num7 + num4))
                {
                    flag2 = false;
                }
                if (flag2 && !Collision.CanHitLine(base.Center, 0, 0, Main.player[target].Center, 0, 0))
                {
                    flag2 = false;
                }
                if (flag2)
                {
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), num6 * 16 + 8, num7 * 16 + 8, 0f, 0f, 813, 0, 0f, Main.myPlayer);
                    flag = true;
                    break;
                }
            }
        }
    }
References Terraria.Collision.CanHitLine(), Terraria.NPC.CountNPCS(), Terraria.Entity.Distance(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.NewProjectile(), Terraria.Main.player, Terraria.Main.rand, Terraria.Collision.SolidTiles(), Terraria.NPC.target, and Terraria.Main.tile.
Referenced by Terraria.NPC.AI_117_BloodNautilus().