TModLoader: Terraria.NPC.SitDown
SitDown()
void Terraria.NPC.SitDown (Point anchorTilePosition, out int direction, out Vector2 bottom) inline
Helper method for getting the parameters for seating a town NPC. Assumes the tile at anchorTilePosition is a valid tile for sitting.
    {
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        Tile tile = Main.tile[anchorTilePosition.X, anchorTilePosition.Y];
        if (tile.type < TileID.Count)
        {
            anchorTilePosition.Y--;
        }
        TileRestingInfo info = new TileRestingInfo(this, anchorTilePosition, Vector2.Zero, (tile.frameX != 0) ? 1 : (-1), 2);
        TileLoader.ModifySittingTargetInfo(anchorTilePosition.X, anchorTilePosition.Y, tile.type, ref info);
        int anchorX = info.AnchorTilePosition.X;
        int anchorY = info.AnchorTilePosition.Y;
        int directionOffset = info.DirectionOffset;
        direction = info.TargetDirection;
        Vector2 finalOffset = info.FinalOffset;
        bottom = Utils.ToWorldCoordinates(new Point(anchorX, anchorY), 8f, 16f);
        bottom.X += direction * directionOffset;
        bottom += finalOffset;
    }
References Terraria.ID.TileID.Count, Terraria.Tile.frameX, Terraria.ModLoader.TileLoader.ModifySittingTargetInfo(), Terraria.Main.tile, Terraria.Utils.ToWorldCoordinates(), and Terraria.Tile.type.
Referenced by Terraria.NPC.AI_007_TownEntities(), and Terraria.NPC.AI_007_TryForcingSitting().