TModLoader: Terraria.NPC.TransformCopperSlime
TransformCopperSlime()
static void Terraria.NPC.TransformCopperSlime (int npcIndex) inline static
Definition at line 13924 of file NPC.cs.
    {
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode == 1)
        {
            NetMessage.SendData(140, -1, -1, null, 1, npcIndex);
        }
        else if (!unlockedSlimeCopperSpawn && Main.npc.IndexInRange(npcIndex))
        {
            NPC nPC = Main.npc[npcIndex];
            if (nPC.type >= 0 && NPCID.Sets.CanConvertIntoCopperSlimeTownNPC[nPC.type])
            {
                unlockedSlimeCopperSpawn = true;
                NetMessage.SendData(7);
                Vector2 vector = nPC.velocity;
                nPC.Transform(684);
                nPC.netUpdate = true;
                nPC.velocity = vector;
                ParticleOrchestrator.BroadcastParticleSpawn(ParticleOrchestraType.TownSlimeTransform, new ParticleOrchestraSettings
                {
                    PositionInWorld = nPC.Center,
                    MovementVector = Vector2.Zero,
                    UniqueInfoPiece = 1
                });
            }
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastParticleSpawn(), Terraria.ID.NPCID.Sets.CanConvertIntoCopperSlimeTownNPC, Terraria.Main.netMode, Terraria.Main.npc, Terraria.NetMessage.SendData(), and Terraria.NPC.unlockedSlimeCopperSpawn.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Item.GetPickedUpByMonsters_Special().