TModLoader: Terraria.NPC.AI_069_DukeFishron
AI_069_DukeFishron()
void Terraria.NPC.AI_069_DukeFishron () inline private
Definition at line 51255 of file NPC.cs.
    {
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_0295: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_025b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0405: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_064a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0737: Unknown result type (might be due to invalid IL or missing references)
        //IL_097a: Unknown result type (might be due to invalid IL or missing references)
        //IL_098c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0991: Unknown result type (might be due to invalid IL or missing references)
        //IL_0996: Unknown result type (might be due to invalid IL or missing references)
        //IL_0998: Unknown result type (might be due to invalid IL or missing references)
        //IL_099e: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09af: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_095d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0961: Unknown result type (might be due to invalid IL or missing references)
        //IL_0966: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_12f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_12fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fcf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fdb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f92: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e09: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e30: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e42: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e49: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e75: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ebd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ecb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0edb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a19: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_14c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_14c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1339: Unknown result type (might be due to invalid IL or missing references)
        //IL_1341: Unknown result type (might be due to invalid IL or missing references)
        //IL_1045: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0801: Unknown result type (might be due to invalid IL or missing references)
        //IL_0807: Unknown result type (might be due to invalid IL or missing references)
        //IL_080c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0811: Unknown result type (might be due to invalid IL or missing references)
        //IL_0813: Unknown result type (might be due to invalid IL or missing references)
        //IL_0818: Unknown result type (might be due to invalid IL or missing references)
        //IL_081d: Unknown result type (might be due to invalid IL or missing references)
        //IL_081f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0821: Unknown result type (might be due to invalid IL or missing references)
        //IL_082d: Unknown result type (might be due to invalid IL or missing references)
        //IL_083a: Unknown result type (might be due to invalid IL or missing references)
        //IL_084b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0851: Unknown result type (might be due to invalid IL or missing references)
        //IL_0883: Unknown result type (might be due to invalid IL or missing references)
        //IL_0885: Unknown result type (might be due to invalid IL or missing references)
        //IL_088f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0894: Unknown result type (might be due to invalid IL or missing references)
        //IL_08aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1505: Unknown result type (might be due to invalid IL or missing references)
        //IL_150d: Unknown result type (might be due to invalid IL or missing references)
        //IL_109b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1019: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a45: Unknown result type (might be due to invalid IL or missing references)
        //IL_137f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1384: Unknown result type (might be due to invalid IL or missing references)
        //IL_1390: Unknown result type (might be due to invalid IL or missing references)
        //IL_1395: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_13ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_13ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_13c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_13c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1409: Unknown result type (might be due to invalid IL or missing references)
        //IL_1410: Unknown result type (might be due to invalid IL or missing references)
        //IL_10f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b14: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_15e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_15f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_15f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_15fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1600: Unknown result type (might be due to invalid IL or missing references)
        //IL_1606: Unknown result type (might be due to invalid IL or missing references)
        //IL_160b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1610: Unknown result type (might be due to invalid IL or missing references)
        //IL_1617: Unknown result type (might be due to invalid IL or missing references)
        //IL_161c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1629: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_15ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e47: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e51: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e56: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c45: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a74: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a90: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a95: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1abf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1acc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ace: Unknown result type (might be due to invalid IL or missing references)
        //IL_1aee: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b00: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b05: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b07: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b09: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b15: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b22: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b33: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b39: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b76: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b89: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b94: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b99: Unknown result type (might be due to invalid IL or missing references)
        //IL_1681: Unknown result type (might be due to invalid IL or missing references)
        //IL_114f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1157: Unknown result type (might be due to invalid IL or missing references)
        //IL_111f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e92: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1db2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1db8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dba: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dbf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c77: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c83: Unknown result type (might be due to invalid IL or missing references)
        //IL_16d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1655: Unknown result type (might be due to invalid IL or missing references)
        //IL_122f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1239: Unknown result type (might be due to invalid IL or missing references)
        //IL_1189: Unknown result type (might be due to invalid IL or missing references)
        //IL_1195: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f95: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cac: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cb1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cc0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cca: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ccf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cde: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ce6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d33: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d38: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d53: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d55: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d61: Unknown result type (might be due to invalid IL or missing references)
        //IL_172f: Unknown result type (might be due to invalid IL or missing references)
        //IL_16ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_11bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_11fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_202c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2036: Unknown result type (might be due to invalid IL or missing references)
        //IL_203b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ed2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ed9: Unknown result type (might be due to invalid IL or missing references)
        //IL_177c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1786: Unknown result type (might be due to invalid IL or missing references)
        //IL_1703: Unknown result type (might be due to invalid IL or missing references)
        //IL_2077: Unknown result type (might be due to invalid IL or missing references)
        //IL_207f: Unknown result type (might be due to invalid IL or missing references)
        //IL_175b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2644: Unknown result type (might be due to invalid IL or missing references)
        //IL_264e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2653: Unknown result type (might be due to invalid IL or missing references)
        //IL_218f: Unknown result type (might be due to invalid IL or missing references)
        //IL_21a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_21a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_21ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_21ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_21b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_21b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_21bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_21c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_21c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_21cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_21d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_21e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2172: Unknown result type (might be due to invalid IL or missing references)
        //IL_2176: Unknown result type (might be due to invalid IL or missing references)
        //IL_217b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c84: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c86: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c92: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c97: Unknown result type (might be due to invalid IL or missing references)
        //IL_28b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_28cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_28d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_28d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_28d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2890: Unknown result type (might be due to invalid IL or missing references)
        //IL_2898: Unknown result type (might be due to invalid IL or missing references)
        //IL_268e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2696: Unknown result type (might be due to invalid IL or missing references)
        //IL_2447: Unknown result type (might be due to invalid IL or missing references)
        //IL_244c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2468: Unknown result type (might be due to invalid IL or missing references)
        //IL_246d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2477: Unknown result type (might be due to invalid IL or missing references)
        //IL_2497: Unknown result type (might be due to invalid IL or missing references)
        //IL_249d: Unknown result type (might be due to invalid IL or missing references)
        //IL_249f: Unknown result type (might be due to invalid IL or missing references)
        //IL_24a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_24a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_24c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_24d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_24dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_24df: Unknown result type (might be due to invalid IL or missing references)
        //IL_24e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_24ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_24fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_250b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2511: Unknown result type (might be due to invalid IL or missing references)
        //IL_2544: Unknown result type (might be due to invalid IL or missing references)
        //IL_254e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2553: Unknown result type (might be due to invalid IL or missing references)
        //IL_2561: Unknown result type (might be due to invalid IL or missing references)
        //IL_2567: Unknown result type (might be due to invalid IL or missing references)
        //IL_256c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2571: Unknown result type (might be due to invalid IL or missing references)
        //IL_2705: Unknown result type (might be due to invalid IL or missing references)
        //IL_271d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2722: Unknown result type (might be due to invalid IL or missing references)
        //IL_2727: Unknown result type (might be due to invalid IL or missing references)
        //IL_272a: Unknown result type (might be due to invalid IL or missing references)
        //IL_272c: Unknown result type (might be due to invalid IL or missing references)
        //IL_272d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2734: Unknown result type (might be due to invalid IL or missing references)
        //IL_2736: Unknown result type (might be due to invalid IL or missing references)
        //IL_273a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2744: Unknown result type (might be due to invalid IL or missing references)
        //IL_26e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_26ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_26f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_232d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2332: Unknown result type (might be due to invalid IL or missing references)
        //IL_2334: Unknown result type (might be due to invalid IL or missing references)
        //IL_2339: Unknown result type (might be due to invalid IL or missing references)
        //IL_2340: Unknown result type (might be due to invalid IL or missing references)
        //IL_2345: Unknown result type (might be due to invalid IL or missing references)
        //IL_222f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2234: Unknown result type (might be due to invalid IL or missing references)
        //IL_18d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_18dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_18de: Unknown result type (might be due to invalid IL or missing references)
        //IL_18e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_18ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_18ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_1957: Unknown result type (might be due to invalid IL or missing references)
        //IL_195c: Unknown result type (might be due to invalid IL or missing references)
        //IL_195e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1963: Unknown result type (might be due to invalid IL or missing references)
        //IL_196a: Unknown result type (might be due to invalid IL or missing references)
        //IL_196f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2792: Unknown result type (might be due to invalid IL or missing references)
        //IL_2797: Unknown result type (might be due to invalid IL or missing references)
        bool expertMode = Main.expertMode;
        float num = (expertMode ? 1.2f : 1f);
        bool flag = (double)life <= (double)lifeMax * 0.5;
        bool flag2 = expertMode && (double)life <= (double)lifeMax * 0.15;
        bool flag3 = ai[0] > 4f;
        bool flag4 = ai[0] > 9f;
        bool flag5 = ai[3] < 10f;
        if (flag4)
        {
            damage = (int)((float)defDamage * 1.1f * num);
            defense = 0;
        }
        else if (flag3)
        {
            damage = (int)((float)defDamage * 1.2f * num);
            defense = (int)((float)defDefense * 0.8f);
        }
        else
        {
            damage = defDamage;
            defense = defDefense;
        }
        int num12 = (expertMode ? 40 : 60);
        float num23 = (expertMode ? 0.55f : 0.45f);
        float num34 = (expertMode ? 8.5f : 7.5f);
        if (flag4)
        {
            num23 = 0.7f;
            num34 = 12f;
            num12 = 30;
        }
        else if (flag3 && flag5)
        {
            num23 = (expertMode ? 0.6f : 0.5f);
            num34 = (expertMode ? 10f : 8f);
            num12 = (expertMode ? 40 : 20);
        }
        else if (flag5 && !flag3 && !flag4)
        {
            num12 = 30;
        }
        int num36 = (expertMode ? 28 : 30);
        float num37 = (expertMode ? 17f : 16f);
        if (flag4)
        {
            num36 = 25;
            num37 = 27f;
        }
        else if (flag5 && flag3)
        {
            num36 = (expertMode ? 27 : 30);
            if (expertMode)
            {
                num37 = 21f;
            }
        }
        int num38 = 80;
        int num39 = 4;
        float num40 = 0.3f;
        float num2 = 5f;
        int num3 = 90;
        int num4 = 180;
        int num5 = 180;
        int num6 = 30;
        int num7 = 120;
        int num8 = 4;
        float num9 = 6f;
        float num10 = 20f;
        float num11 = (float)Math.PI * 2f / (float)(num7 / 2);
        int num13 = 75;
        Vector2 center = base.Center;
        Player player = Main.player[target];
        if (target < 0 || target == 255 || player.dead || !player.active || Vector2.Distance(player.Center, center) > 5600f)
        {
            TargetClosest();
            player = Main.player[target];
            netUpdate = true;
        }
        if (player.dead || Vector2.Distance(player.Center, center) > 5600f)
        {
            velocity.Y -= 0.4f;
            EncourageDespawn(10);
            if (ai[0] > 4f)
            {
                ai[0] = 5f;
            }
            else
            {
                ai[0] = 0f;
            }
            ai[2] = 0f;
        }
        bool flag6 = player.position.Y < 800f || (double)player.position.Y > Main.worldSurface * 16.0 || (player.position.X > 6400f && player.position.X < (float)(Main.maxTilesX * 16 - 6400));
        if (flag6)
        {
            num12 = 10;
            damage = defDamage * 2;
            defense = defDefense * 2;
            num37 += 6f;
        }
        bool flag7 = true;
        if (localAI[0] == 0f)
        {
            localAI[0] = 1f;
            alpha = 255;
            rotation = 0f;
            if (Main.netMode != 1)
            {
                ai[0] = -1f;
                netUpdate = true;
            }
        }
        float num14 = (float)Math.Atan2(player.Center.Y - center.Y, player.Center.X - center.X);
        if (spriteDirection == 1)
        {
            num14 += (float)Math.PI;
        }
        if (num14 < 0f)
        {
            num14 += (float)Math.PI * 2f;
        }
        if (num14 > (float)Math.PI * 2f)
        {
            num14 -= (float)Math.PI * 2f;
        }
        if (ai[0] == -1f)
        {
            num14 = 0f;
        }
        if (ai[0] == 3f)
        {
            num14 = 0f;
        }
        if (ai[0] == 4f)
        {
            num14 = 0f;
        }
        if (ai[0] == 8f)
        {
            num14 = 0f;
        }
        float num15 = 0.04f;
        if (ai[0] == 1f || ai[0] == 6f)
        {
            num15 = 0f;
        }
        if (ai[0] == 7f)
        {
            num15 = 0f;
        }
        if (ai[0] == 3f)
        {
            num15 = 0.01f;
        }
        if (ai[0] == 4f)
        {
            num15 = 0.01f;
        }
        if (ai[0] == 8f)
        {
            num15 = 0.01f;
        }
        if (rotation < num14)
        {
            if ((double)(num14 - rotation) > Math.PI)
            {
                rotation -= num15;
            }
            else
            {
                rotation += num15;
            }
        }
        if (rotation > num14)
        {
            if ((double)(rotation - num14) > Math.PI)
            {
                rotation += num15;
            }
            else
            {
                rotation -= num15;
            }
        }
        if (rotation > num14 - num15 && rotation < num14 + num15)
        {
            rotation = num14;
        }
        if (rotation < 0f)
        {
            rotation += (float)Math.PI * 2f;
        }
        if (rotation > (float)Math.PI * 2f)
        {
            rotation -= (float)Math.PI * 2f;
        }
        if (rotation > num14 - num15 && rotation < num14 + num15)
        {
            rotation = num14;
        }
        if (ai[0] != -1f && ai[0] < 9f)
        {
            if (Collision.SolidCollision(position, width, height))
            {
                alpha += 15;
            }
            else
            {
                alpha -= 15;
            }
            if (alpha < 0)
            {
                alpha = 0;
            }
            if (alpha > 150)
            {
                alpha = 150;
            }
        }
        if (ai[0] == -1f)
        {
            flag7 = false;
            velocity *= 0.98f;
            int num16 = Math.Sign(player.Center.X - center.X);
            if (num16 != 0)
            {
                direction = num16;
                spriteDirection = -direction;
            }
            if (ai[2] > 20f)
            {
                velocity.Y = -2f;
                alpha -= 5;
                if (Collision.SolidCollision(position, width, height))
                {
                    alpha += 15;
                }
                if (alpha < 0)
                {
                    alpha = 0;
                }
                if (alpha > 150)
                {
                    alpha = 150;
                }
            }
            if (ai[2] == (float)(num3 - 30))
            {
                int num17 = 36;
                for (int i = 0; i < num17; i++)
                {
                    Vector2 val = (Vector2.Normalize(velocity) * new Vector2((float)width / 2f, (float)height) * 0.75f * 0.5f).RotatedBy((float)(i - (num17 / 2 - 1)) * ((float)Math.PI * 2f) / (float)num17) + base.Center;
                    Vector2 vector15 = val - base.Center;
                    int num18 = Dust.NewDust(val + vector15, 0, 0, 172, vector15.X * 2f, vector15.Y * 2f, 100, default(Color), 1.4f);
                    Main.dust[num18].noGravity = true;
                    Main.dust[num18].noLight = true;
                    Main.dust[num18].velocity = Vector2.Normalize(vector15) * 3f;
                }
                SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
            }
            ai[2] += 1f;
            if (ai[2] >= (float)num13)
            {
                ai[0] = 0f;
                ai[1] = 0f;
                ai[2] = 0f;
                netUpdate = true;
            }
        }
        else if (ai[0] == 0f && !player.dead)
        {
            if (ai[1] == 0f)
            {
                ai[1] = 300 * Math.Sign((center - player.Center).X);
            }
            Vector2 vector16 = Vector2.Normalize(player.Center + new Vector2(ai[1], -200f) - center - velocity) * num34;
            if (velocity.X < vector16.X)
            {
                velocity.X += num23;
                if (velocity.X < 0f && vector16.X > 0f)
                {
                    velocity.X += num23;
                }
            }
            else if (velocity.X > vector16.X)
            {
                velocity.X -= num23;
                if (velocity.X > 0f && vector16.X < 0f)
                {
                    velocity.X -= num23;
                }
            }
            if (velocity.Y < vector16.Y)
            {
                velocity.Y += num23;
                if (velocity.Y < 0f && vector16.Y > 0f)
                {
                    velocity.Y += num23;
                }
            }
            else if (velocity.Y > vector16.Y)
            {
                velocity.Y -= num23;
                if (velocity.Y > 0f && vector16.Y < 0f)
                {
                    velocity.Y -= num23;
                }
            }
            int num19 = Math.Sign(player.Center.X - center.X);
            if (num19 != 0)
            {
                if (ai[2] == 0f && num19 != direction)
                {
                    rotation += (float)Math.PI;
                }
                direction = num19;
                if (spriteDirection != -direction)
                {
                    rotation += (float)Math.PI;
                }
                spriteDirection = -direction;
            }
            ai[2] += 1f;
            if (ai[2] >= (float)num12)
            {
                int num20 = 0;
                switch ((int)ai[3])
                {
                case 0:
                case 1:
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                    num20 = 1;
                    break;
                case 10:
                    ai[3] = 1f;
                    num20 = 2;
                    break;
                case 11:
                    ai[3] = 0f;
                    num20 = 3;
                    break;
                }
                if (flag6 && num20 == 2)
                {
                    num20 = 3;
                }
                if (flag)
                {
                    num20 = 4;
                }
                switch (num20)
                {
                case 1:
                    ai[0] = 1f;
                    ai[1] = 0f;
                    ai[2] = 0f;
                    velocity = Vector2.Normalize(player.Center - center) * num37;
                    rotation = (float)Math.Atan2(velocity.Y, velocity.X);
                    if (num19 != 0)
                    {
                        direction = num19;
                        if (spriteDirection == 1)
{
                            rotation += (float)Math.PI;
                        }
                        spriteDirection = -direction;
                    }
                    break;
                case 2:
                    ai[0] = 2f;
                    ai[1] = 0f;
                    ai[2] = 0f;
                    break;
                case 3:
                    ai[0] = 3f;
                    ai[1] = 0f;
                    ai[2] = 0f;
                    if (flag6)
                    {
                        ai[2] = num3 - 40;
                    }
                    break;
                case 4:
                    ai[0] = 4f;
                    ai[1] = 0f;
                    ai[2] = 0f;
                    break;
                }
                netUpdate = true;
            }
        }
        else if (ai[0] == 1f)
        {
            int num21 = 7;
            for (int j = 0; j < num21; j++)
            {
                Vector2 val2 = (Vector2.Normalize(velocity) * new Vector2((float)(width + 50) / 2f, (float)height) * 0.75f).RotatedBy((double)(j - (num21 / 2 - 1)) * Math.PI / (double)(float)num21) + center;
                Vector2 vector17 = ((float)(Main.rand.NextDouble() * 3.1415927410125732) - (float)Math.PI / 2f).ToRotationVector2() * (float)Main.rand.Next(3, 8);
                int num22 = Dust.NewDust(val2 + vector17, 0, 0, 172, vector17.X * 2f, vector17.Y * 2f, 100, default(Color), 1.4f);
                Main.dust[num22].noGravity = true;
                Main.dust[num22].noLight = true;
                Dust obj = Main.dust[num22];
                obj.velocity /= 4f;
                Dust obj2 = Main.dust[num22];
                obj2.velocity -= velocity;
            }
            ai[2] += 1f;
            if (ai[2] >= (float)num36)
            {
                ai[0] = 0f;
                ai[1] = 0f;
                ai[2] = 0f;
                ai[3] += 2f;
                netUpdate = true;
            }
        }
        else if (ai[0] == 2f)
        {
            if (ai[1] == 0f)
            {
                ai[1] = 300 * Math.Sign((center - player.Center).X);
            }
            Vector2 vector18 = Vector2.Normalize(player.Center + new Vector2(ai[1], -200f) - center - velocity) * num2;
            if (velocity.X < vector18.X)
            {
                velocity.X += num40;
                if (velocity.X < 0f && vector18.X > 0f)
                {
                    velocity.X += num40;
                }
            }
            else if (velocity.X > vector18.X)
            {
                velocity.X -= num40;
                if (velocity.X > 0f && vector18.X < 0f)
                {
                    velocity.X -= num40;
                }
            }
            if (velocity.Y < vector18.Y)
            {
                velocity.Y += num40;
                if (velocity.Y < 0f && vector18.Y > 0f)
                {
                    velocity.Y += num40;
                }
            }
            else if (velocity.Y > vector18.Y)
            {
                velocity.Y -= num40;
                if (velocity.Y > 0f && vector18.Y < 0f)
                {
                    velocity.Y -= num40;
                }
            }
            if (ai[2] == 0f)
            {
                SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
            }
            if (ai[2] % (float)num39 == 0f)
            {
                SoundEngine.PlaySound(4, (int)base.Center.X, (int)base.Center.Y, 19);
                if (Main.netMode != 1)
                {
                    Vector2 vector19 = Vector2.Normalize(player.Center - center) * (float)(width + 20) / 2f + center;
                    NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)vector19.X, (int)vector19.Y + 45, 371);
                }
            }
            int num24 = Math.Sign(player.Center.X - center.X);
            if (num24 != 0)
            {
                direction = num24;
                if (spriteDirection != -direction)
                {
                    rotation += (float)Math.PI;
                }
                spriteDirection = -direction;
            }
            ai[2] += 1f;
            if (ai[2] >= (float)num38)
            {
                ai[0] = 0f;
                ai[1] = 0f;
                ai[2] = 0f;
                netUpdate = true;
            }
        }
        else if (ai[0] == 3f)
        {
            velocity *= 0.98f;
            velocity.Y = MathHelper.Lerp(velocity.Y, 0f, 0.02f);
            if (ai[2] == (float)(num3 - 30))
            {
                SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 9);
            }
            if (Main.netMode != 1 && ai[2] == (float)(num3 - 30))
            {
                Vector2 vector20 = rotation.ToRotationVector2() * (Vector2.UnitX * (float)direction) * (float)(width + 20) / 2f + center;
                Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector20.X, vector20.Y, direction * 2, 8f, 385, 0, 0f, Main.myPlayer);
                Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector20.X, vector20.Y, -direction * 2, 8f, 385, 0, 0f, Main.myPlayer);
            }
            ai[2] += 1f;
            if (ai[2] >= (float)num3)
            {
                ai[0] = 0f;
                ai[1] = 0f;
                ai[2] = 0f;
                netUpdate = true;
            }
        }
        else if (ai[0] == 4f)
        {
            flag7 = false;
            velocity *= 0.98f;
            velocity.Y = MathHelper.Lerp(velocity.Y, 0f, 0.02f);
            if (ai[2] == (float)(num4 - 60))
            {
                SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
            }
            ai[2] += 1f;
            if (ai[2] >= (float)num4)
            {
                ai[0] = 5f;
                ai[1] = 0f;
                ai[2] = 0f;
                ai[3] = 0f;
                netUpdate = true;
            }
        }
        else if (ai[0] == 5f && !player.dead)
        {
            if (ai[1] == 0f)
            {
                ai[1] = 300 * Math.Sign((center - player.Center).X);
            }
            Vector2 vector21 = Vector2.Normalize(player.Center + new Vector2(ai[1], -200f) - center - velocity) * num34;
            if (velocity.X < vector21.X)
            {
                velocity.X += num23;
                if (velocity.X < 0f && vector21.X > 0f)
                {
                    velocity.X += num23;
                }
            }
            else if (velocity.X > vector21.X)
            {
                velocity.X -= num23;
                if (velocity.X > 0f && vector21.X < 0f)
                {
                    velocity.X -= num23;
                }
            }
            if (velocity.Y < vector21.Y)
            {
                velocity.Y += num23;
                if (velocity.Y < 0f && vector21.Y > 0f)
                {
                    velocity.Y += num23;
                }
            }
            else if (velocity.Y > vector21.Y)
            {
                velocity.Y -= num23;
                if (velocity.Y > 0f && vector21.Y < 0f)
                {
                    velocity.Y -= num23;
                }
            }
            int num25 = Math.Sign(player.Center.X - center.X);
            if (num25 != 0)
            {
                if (ai[2] == 0f && num25 != direction)
                {
                    rotation += (float)Math.PI;
                }
                direction = num25;
                if (spriteDirection != -direction)
                {
                    rotation += (float)Math.PI;
                }
                spriteDirection = -direction;
            }
            ai[2] += 1f;
            if (ai[2] >= (float)num12)
            {
                int num26 = 0;
                switch ((int)ai[3])
                {
                case 0:
                case 1:
                case 2:
                case 3:
                case 4:
                case 5:
                    num26 = 1;
                    break;
                case 6:
                    ai[3] = 1f;
                    num26 = 2;
                    break;
                case 7:
                    ai[3] = 0f;
                    num26 = 3;
                    break;
                }
                if (flag2)
                {
                    num26 = 4;
                }
                if (flag6 && num26 == 2)
                {
                    num26 = 3;
                }
                switch (num26)
                {
                case 1:
                    ai[0] = 6f;
                    ai[1] = 0f;
                    ai[2] = 0f;
                    velocity = Vector2.Normalize(player.Center - center) * num37;
                    rotation = (float)Math.Atan2(velocity.Y, velocity.X);
                    if (num25 != 0)
                    {
                        direction = num25;
                        if (spriteDirection == 1)
{
                            rotation += (float)Math.PI;
                        }
                        spriteDirection = -direction;
                    }
                    break;
                case 2:
                    velocity = Vector2.Normalize(player.Center - center) * num10;
                    rotation = (float)Math.Atan2(velocity.Y, velocity.X);
                    if (num25 != 0)
                    {
                        direction = num25;
                        if (spriteDirection == 1)
{
                            rotation += (float)Math.PI;
                        }
                        spriteDirection = -direction;
                    }
                    ai[0] = 7f;
                    ai[1] = 0f;
                    ai[2] = 0f;
                    break;
                case 3:
                    ai[0] = 8f;
                    ai[1] = 0f;
                    ai[2] = 0f;
                    break;
                case 4:
                    ai[0] = 9f;
                    ai[1] = 0f;
                    ai[2] = 0f;
                    break;
                }
                netUpdate = true;
            }
        }
        else if (ai[0] == 6f)
        {
            int num27 = 7;
            for (int k = 0; k < num27; k++)
            {
                Vector2 val3 = (Vector2.Normalize(velocity) * new Vector2((float)(width + 50) / 2f, (float)height) * 0.75f).RotatedBy((double)(k - (num27 / 2 - 1)) * Math.PI / (double)(float)num27) + center;
                Vector2 vector11 = ((float)(Main.rand.NextDouble() * 3.1415927410125732) - (float)Math.PI / 2f).ToRotationVector2() * (float)Main.rand.Next(3, 8);
                int num28 = Dust.NewDust(val3 + vector11, 0, 0, 172, vector11.X * 2f, vector11.Y * 2f, 100, default(Color), 1.4f);
                Main.dust[num28].noGravity = true;
                Main.dust[num28].noLight = true;
                Dust obj3 = Main.dust[num28];
                obj3.velocity /= 4f;
                Dust obj4 = Main.dust[num28];
                obj4.velocity -= velocity;
            }
            ai[2] += 1f;
            if (ai[2] >= (float)num36)
            {
                ai[0] = 5f;
                ai[1] = 0f;
                ai[2] = 0f;
                ai[3] += 2f;
                netUpdate = true;
            }
        }
        else if (ai[0] == 7f)
        {
            if (ai[2] == 0f)
            {
                SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
            }
            if (ai[2] % (float)num8 == 0f)
            {
                SoundEngine.PlaySound(4, (int)base.Center.X, (int)base.Center.Y, 19);
                if (Main.netMode != 1)
                {
                    Vector2 vector12 = Vector2.Normalize(velocity) * (float)(width + 20) / 2f + center;
                    int num29 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)vector12.X, (int)vector12.Y + 45, 371);
                    Main.npc[num29].target = target;
                    Main.npc[num29].velocity = Vector2.Normalize(velocity).RotatedBy((float)Math.PI / 2f * (float)direction) * num9;
                    Main.npc[num29].netUpdate = true;
                    Main.npc[num29].ai[3] = (float)Main.rand.Next(80, 121) / 100f;
                }
            }
            velocity = velocity.RotatedBy((0f - num11) * (float)direction);
            rotation -= num11 * (float)direction;
            ai[2] += 1f;
            if (ai[2] >= (float)num7)
            {
                ai[0] = 5f;
                ai[1] = 0f;
                ai[2] = 0f;
                netUpdate = true;
            }
        }
        else if (ai[0] == 8f)
        {
            velocity *= 0.98f;
            velocity.Y = MathHelper.Lerp(velocity.Y, 0f, 0.02f);
            if (ai[2] == (float)(num3 - 30))
            {
                SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
            }
            if (Main.netMode != 1 && ai[2] == (float)(num3 - 30))
            {
                Projectile.NewProjectile(GetSpawnSource_ForProjectile(), center.X, center.Y, 0f, 0f, 385, 0, 0f, Main.myPlayer, 1f, target + 1, flag6 ? 1 : 0);
            }
            ai[2] += 1f;
            if (ai[2] >= (float)num3)
            {
                ai[0] = 5f;
                ai[1] = 0f;
                ai[2] = 0f;
                netUpdate = true;
            }
        }
        else if (ai[0] == 9f)
        {
            flag7 = false;
            if (ai[2] < (float)(num5 - 90))
            {
                if (Collision.SolidCollision(position, width, height))
                {
                    alpha += 15;
                }
                else
                {
                    alpha -= 15;
                }
                if (alpha < 0)
                {
                    alpha = 0;
                }
                if (alpha > 150)
                {
                    alpha = 150;
                }
            }
            else if (alpha < 255)
            {
                alpha += 4;
                if (alpha > 255)
                {
                    alpha = 255;
                }
            }
            velocity *= 0.98f;
            velocity.Y = MathHelper.Lerp(velocity.Y, 0f, 0.02f);
            if (ai[2] == (float)(num5 - 60))
            {
                SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
            }
            ai[2] += 1f;
            if (ai[2] >= (float)num5)
            {
                ai[0] = 10f;
                ai[1] = 0f;
                ai[2] = 0f;
                ai[3] = 0f;
                netUpdate = true;
            }
        }
        else if (ai[0] == 10f && !player.dead)
        {
            chaseable = false;
            if (alpha < 255)
            {
                alpha += 25;
                if (alpha > 255)
                {
                    alpha = 255;
                }
            }
            if (ai[1] == 0f)
            {
                ai[1] = 360 * Math.Sign((center - player.Center).X);
            }
            Vector2 desiredVelocity = Vector2.Normalize(player.Center + new Vector2(ai[1], -200f) - center - velocity) * num34;
            SimpleFlyMovement(desiredVelocity, num23);
            int num30 = Math.Sign(player.Center.X - center.X);
            if (num30 != 0)
            {
                if (ai[2] == 0f && num30 != direction)
                {
                    rotation += (float)Math.PI;
                    for (int l = 0; l < oldPos.Length; l++)
                    {
                        oldPos[l] = Vector2.Zero;
                    }
                }
                direction = num30;
                if (spriteDirection != -direction)
                {
                    rotation += (float)Math.PI;
                }
                spriteDirection = -direction;
            }
            ai[2] += 1f;
            if (ai[2] >= (float)num12)
            {
                int num31 = 0;
                switch ((int)ai[3])
                {
                case 0:
                case 2:
                case 3:
                case 5:
                case 6:
                case 7:
                    num31 = 1;
                    break;
                case 1:
                case 4:
                case 8:
                    num31 = 2;
                    break;
                }
                switch (num31)
                {
                case 1:
                    ai[0] = 11f;
                    ai[1] = 0f;
                    ai[2] = 0f;
                    velocity = Vector2.Normalize(player.Center - center) * num37;
                    rotation = (float)Math.Atan2(velocity.Y, velocity.X);
                    if (num30 != 0)
                    {
                        direction = num30;
                        if (spriteDirection == 1)
{
                            rotation += (float)Math.PI;
                        }
                        spriteDirection = -direction;
                    }
                    break;
                case 2:
                    ai[0] = 12f;
                    ai[1] = 0f;
                    ai[2] = 0f;
                    break;
                case 3:
                    ai[0] = 13f;
                    ai[1] = 0f;
                    ai[2] = 0f;
                    break;
                }
                netUpdate = true;
            }
        }
        else if (ai[0] == 11f)
        {
            chaseable = true;
            alpha -= 25;
            if (alpha < 0)
            {
                alpha = 0;
            }
            int num32 = 7;
            for (int m = 0; m < num32; m++)
            {
                Vector2 val4 = (Vector2.Normalize(velocity) * new Vector2((float)(width + 50) / 2f, (float)height) * 0.75f).RotatedBy((double)(m - (num32 / 2 - 1)) * Math.PI / (double)(float)num32) + center;
                Vector2 vector13 = ((float)(Main.rand.NextDouble() * 3.1415927410125732) - (float)Math.PI / 2f).ToRotationVector2() * (float)Main.rand.Next(3, 8);
                int num33 = Dust.NewDust(val4 + vector13, 0, 0, 172, vector13.X * 2f, vector13.Y * 2f, 100, default(Color), 1.4f);
                Main.dust[num33].noGravity = true;
                Main.dust[num33].noLight = true;
                Dust obj5 = Main.dust[num33];
                obj5.velocity /= 4f;
                Dust obj6 = Main.dust[num33];
                obj6.velocity -= velocity;
            }
            ai[2] += 1f;
            if (ai[2] >= (float)num36)
            {
                ai[0] = 10f;
                ai[1] = 0f;
                ai[2] = 0f;
                ai[3] += 1f;
                netUpdate = true;
            }
        }
        else if (ai[0] == 12f)
        {
            flag7 = false;
            chaseable = false;
            if (alpha < 255)
            {
                alpha += 17;
                if (alpha > 255)
                {
                    alpha = 255;
                }
            }
            velocity *= 0.98f;
            velocity.Y = MathHelper.Lerp(velocity.Y, 0f, 0.02f);
            if (ai[2] == (float)(num6 / 2))
            {
                SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
            }
            if (Main.netMode != 1 && ai[2] == (float)(num6 / 2))
            {
                if (ai[1] == 0f)
                {
                    ai[1] = 300 * Math.Sign((center - player.Center).X);
                }
                Vector2 vector14 = player.Center + new Vector2(0f - ai[1], -200f);
                Vector2 val6 = (base.Center = vector14);
                center = val6;
                int num35 = Math.Sign(player.Center.X - center.X);
                if (num35 != 0)
                {
                    if (ai[2] == 0f && num35 != direction)
                    {
                        rotation += (float)Math.PI;
                        for (int n = 0; n < oldPos.Length; n++)
{
                            oldPos[n] = Vector2.Zero;
                        }
                    }
                    direction = num35;
                    if (spriteDirection != -direction)
                    {
                        rotation += (float)Math.PI;
                    }
                    spriteDirection = -direction;
                }
            }
            ai[2] += 1f;
            if (ai[2] >= (float)num6)
            {
                ai[0] = 10f;
                ai[1] = 0f;
                ai[2] = 0f;
                ai[3] += 1f;
                if (ai[3] >= 9f)
                {
                    ai[3] = 0f;
                }
                netUpdate = true;
            }
        }
        else if (ai[0] == 13f)
        {
            if (ai[2] == 0f)
            {
                SoundEngine.PlaySound(29, (int)center.X, (int)center.Y, 20);
            }
            velocity = velocity.RotatedBy((0f - num11) * (float)direction);
            rotation -= num11 * (float)direction;
            ai[2] += 1f;
            if (ai[2] >= (float)num7)
            {
                ai[0] = 10f;
                ai[1] = 0f;
                ai[2] = 0f;
                ai[3] += 1f;
                netUpdate = true;
            }
        }
        dontTakeDamage = !flag7;
    }
References Terraria.Entity.active, Terraria.NPC.ai, Terraria.NPC.alpha, Terraria.Entity.Center, Terraria.NPC.chaseable, Terraria.NPC.damage, Terraria.Player.dead, Terraria.NPC.defDamage, Terraria.NPC.defDefense, Terraria.NPC.defense, Terraria.Entity.direction, Terraria.NPC.dontTakeDamage, Terraria.Main.dust, Terraria.NPC.EncourageDespawn(), Terraria.Main.expertMode, Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.Entity.height, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.Dust.NewDust(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Main.npc, Terraria.NPC.oldPos, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.rotation, Terraria.NPC.SimpleFlyMovement(), Terraria.Collision.SolidCollision(), Terraria.NPC.spriteDirection, Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Entity.width, and Terraria.Main.worldSurface.
Referenced by Terraria.NPC.VanillaAI_Inner().