TModLoader: Terraria.NPC.UpdateNPC_Inner
UpdateNPC_Inner()
void Terraria.NPC.UpdateNPC_Inner (int i) inline private
Definition at line 107078 of file NPC.cs.
    {
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0160: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0527: Unknown result type (might be due to invalid IL or missing references)
        //IL_052d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0532: Unknown result type (might be due to invalid IL or missing references)
        //IL_0537: Unknown result type (might be due to invalid IL or missing references)
        //IL_053d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0561: Unknown result type (might be due to invalid IL or missing references)
        //IL_0567: Unknown result type (might be due to invalid IL or missing references)
        //IL_057e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0588: Unknown result type (might be due to invalid IL or missing references)
        //IL_058d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0594: Unknown result type (might be due to invalid IL or missing references)
        //IL_059a: Unknown result type (might be due to invalid IL or missing references)
        //IL_059f: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_078a: Unknown result type (might be due to invalid IL or missing references)
        //IL_078f: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0834: Unknown result type (might be due to invalid IL or missing references)
        //IL_0846: Unknown result type (might be due to invalid IL or missing references)
        if (offSetDelayTime > 0)
        {
            netOffset *= 0f;
        }
        else if (Main.netMode == 2)
        {
            netOffset *= 0f;
        }
        else if (Main.multiplayerNPCSmoothingRange <= 0)
        {
            netOffset *= 0f;
        }
        else if (netOffset != new Vector2(0f, 0f))
        {
            if (NPCID.Sets.NoMultiplayerSmoothingByType[type])
            {
                netOffset *= 0f;
            }
            else if (aiStyle >= 0 && aiStyle < NPCLoader.NPCCount && NPCID.Sets.NoMultiplayerSmoothingByAI[aiStyle])
            {
                netOffset *= 0f;
            }
            else
            {
                float num = 2f;
                float num4 = Main.multiplayerNPCSmoothingRange;
                float num5 = ((Vector2)(ref netOffset)).Length();
                if (num5 > num4)
                {
                    ((Vector2)(ref netOffset)).Normalize();
                    netOffset *= num4;
                    num5 = ((Vector2)(ref netOffset)).Length();
                }
                num += num5 / num4 * num;
                Vector2 vector = netOffset;
                ((Vector2)(ref vector)).Normalize();
                vector *= num;
                netOffset -= vector;
                if (((Vector2)(ref netOffset)).Length() < num)
                {
                    netOffset *= 0f;
                }
                if (townNPC)
                {
                    if (Vector2.Distance(position, new Vector2((float)(homeTileX * 16 + 8 - width / 2), (float)(homeTileY * 16 - height) - 0.1f)) < 1f)
                    {
                        netOffset *= 0f;
                    }
                    if (ai[0] == 25f)
                    {
                        netOffset *= 0f;
                    }
                }
            }
        }
        UpdateAltTexture();
        if (type == 368)
        {
            travelNPC = true;
        }
        if (Main.netMode != 2)
        {
            UpdateNPC_CastLights();
        }
        UpdateNPC_TeleportVisuals();
        UpdateNPC_CritterSounds();
        TrySyncingUniqueTownNPCData(i);
        if (aiStyle == 7 && position.Y > Main.bottomWorld - 640f + (float)height && Main.netMode != 1 && !Main.xMas)
        {
            StrikeNPCNoInteraction(9999, 0f, 0);
            if (Main.netMode == 2)
            {
                NetMessage.SendData(28, -1, -1, null, whoAmI, 9999f);
            }
        }
        if (Main.netMode == 1)
        {
            int num6 = (int)(position.X + (float)(width / 2)) / 16;
            int num7 = (int)(position.Y + (float)(height / 2)) / 16;
            if (!Main.sectionManager.TilesLoaded(num6 - 3, num7 - 3, num6 + 3, num7 + 3))
            {
                return;
            }
        }
        UpdateNPC_BuffFlagsReset();
        NPCLoader.ResetEffects(this);
        UpdateNPC_UpdateGravity();
        UpdateNPC_BuffSetFlags();
        UpdateNPC_SoulDrainDebuff();
        UpdateNPC_BuffClearExpiredBuffs();
        UpdateNPC_BuffApplyDOTs();
        UpdateNPC_BuffApplyVFX();
        UpdateNPC_BloodMoonTransformations();
        if (soundDelay > 0)
        {
            soundDelay--;
        }
        if (life <= 0)
        {
            active = false;
            UpdateNetworkCode(i);
            netUpdate = false;
            justHit = false;
            return;
        }
        oldTarget = target;
        oldDirection = direction;
        oldDirectionY = directionY;
        float num8 = 1f + Math.Abs(velocity.X) / 3f;
        if (gfxOffY > 0f)
        {
            gfxOffY -= num8 * stepSpeed;
            if (gfxOffY < 0f)
            {
                gfxOffY = 0f;
            }
        }
        else if (gfxOffY < 0f)
        {
            gfxOffY += num8 * stepSpeed;
            if (gfxOffY > 0f)
            {
                gfxOffY = 0f;
            }
        }
        if (gfxOffY > 16f)
        {
            gfxOffY = 16f;
        }
        if (gfxOffY < -16f)
        {
            gfxOffY = -16f;
        }
        TryPortalJumping();
        IdleSounds();
        AI();
        SubAI_HandleTemporaryCatchableNPCPlayerInvulnerability();
        if (Main.netMode != 2 && extraValue > 0)
        {
            int num9 = 244;
            float num10 = 30f;
            if (extraValue >= 1000000)
            {
                num9 = 247;
                num10 *= 0.25f;
            }
            else if (extraValue >= 10000)
            {
                num9 = 246;
                num10 *= 0.5f;
            }
            else if (extraValue >= 100)
            {
                num9 = 245;
                num10 *= 0.75f;
            }
            if (Main.rand.Next((int)num10) == 0)
            {
                position += netOffset;
                int num11 = Dust.NewDust(position, width, height, num9, 0f, 0f, 254, default(Color), 0.25f);
                Dust obj = Main.dust[num11];
                obj.velocity *= 0.1f;
                position -= netOffset;
            }
        }
        for (int j = 0; j < 256; j++)
        {
            if (immune[j] > 0)
            {
                immune[j]--;
            }
        }
        if (!noGravity && !noTileCollide)
        {
            int num2 = (int)(position.X + (float)(width / 2)) / 16;
            int num3 = (int)(position.Y + (float)(height / 2)) / 16;
            if (WorldGen.InWorld(num2, num3) && Main.tile[num2, num3] == null)
            {
                gravity = 0f;
                velocity.X = 0f;
                velocity.Y = 0f;
            }
        }
        if (!noGravity)
        {
            velocity.Y += gravity;
            if (velocity.Y > maxFallSpeed)
            {
                velocity.Y = maxFallSpeed;
            }
        }
        if ((double)velocity.X < 0.005 && (double)velocity.X > -0.005)
        {
            velocity.X = 0f;
        }
        if (Main.netMode != 1 && type != 37 && (friendly || NPCID.Sets.TakesDamageFromHostilesWithoutBeingFriendly[type]))
        {
            if (townNPC)
            {
                CheckDrowning();
            }
            CheckLifeRegen();
            GetHurtByOtherNPCs(NPCID.Sets.AllNPCs);
        }
        if (Main.netMode != 1 && (npcsFoundForCheckActive[210] || npcsFoundForCheckActive[211]) && !NPCID.Sets.HurtingBees[type])
        {
            GetHurtByOtherNPCs(NPCID.Sets.HurtingBees);
        }
        if (!noTileCollide)
        {
            UpdateCollision();
        }
        else
        {
            oldPosition = position;
            oldDirection = direction;
            position += velocity;
            if (onFire && boss && Main.netMode != 1 && Collision.WetCollision(position, width, height))
            {
                for (int k = 0; k < maxBuffs; k++)
                {
                    if (buffType[k] == 24)
                    {
                        DelBuff(k);
                    }
                }
            }
        }
        if (Main.netMode != 1 && !noTileCollide && lifeMax > 1 && Collision.SwitchTiles(position, width, height, oldPosition, 2) && (type == 46 || type == 148 || type == 149 || type == 303 || type == 361 || type == 362 || type == 364 || type == 366 || type == 367 || (type >= 442 && type <= 448) || type == 602 || type == 608 || type == 614 || type == 687))
        {
            ai[0] = 1f;
            ai[1] = 400f;
            ai[2] = 0f;
        }
        FindFrame();
        UpdateNPC_UpdateTrails();
        UpdateNetworkCode(i);
        CheckActive();
        netUpdate = false;
        justHit = false;
    }
References Terraria.ID.NPCID.Sets.AllNPCs, Terraria.Main.bottomWorld, Terraria.Main.dust, Terraria.ID.NPCID.Sets.HurtingBees, Terraria.WorldGen.InWorld(), Terraria.Main.multiplayerNPCSmoothingRange, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.ID.NPCID.Sets.NoMultiplayerSmoothingByAI, Terraria.ID.NPCID.Sets.NoMultiplayerSmoothingByType, Terraria.ModLoader.NPCLoader.NPCCount, Terraria.Main.rand, Terraria.ModLoader.NPCLoader.ResetEffects(), Terraria.Main.sectionManager, Terraria.NetMessage.SendData(), Terraria.Collision.SwitchTiles(), Terraria.ID.NPCID.Sets.TakesDamageFromHostilesWithoutBeingFriendly, Terraria.Main.tile, Terraria.Collision.WetCollision(), and Terraria.Main.xMas.