TModLoader: Terraria.NPC.UnlockOrExchangePet
UnlockOrExchangePet()
static void Terraria.NPC.UnlockOrExchangePet (ref bool petBoughtFlag, int npcType, string textKeyForLicense, int netMessageData) inline static
Definition at line 91335 of file NPC.cs.
    {
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        Color color = default(Color);
        ((Color)(ref color))._002Ector(50, 255, 130);
        if (Main.netMode == 1)
        {
            if (!petBoughtFlag || AnyNPCs(npcType))
            {
                NetMessage.SendData(61, -1, -1, null, Main.myPlayer, netMessageData);
            }
        }
        else if (!petBoughtFlag)
        {
            petBoughtFlag = true;
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey(textKeyForLicense), color);
            NetMessage.TrySendData(7);
        }
        else if (RerollVariationForNPCType(npcType))
        {
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Misc.PetExchangeSuccess"), color);
        }
        else
        {
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Misc.PetExchangeFail"), color);
        }
    }
References Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Localization.NetworkText.FromKey(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NetMessage.SendData(), and Terraria.NetMessage.TrySendData().
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Player.LicenseOrExchangePet().