TModLoader: Terraria.NPC.RerollVariation
RerollVariation()
bool Terraria.NPC.RerollVariation () inline
Definition at line 91378 of file NPC.cs.
    {
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        if (!TownNPCProfiles.Instance.GetProfile(this, out var profile))
        {
            return false;
        }
        int num = townNpcVariationIndex;
        int num2 = 0;
        while (num2++ < 100 && townNpcVariationIndex == num)
        {
            townNpcVariationIndex = profile.RollVariation();
        }
        if (num == townNpcVariationIndex)
        {
            return false;
        }
        GivenName = profile.GetNameForVariant(this);
        life = lifeMax;
        if (Main.netMode != 1)
        {
            ParticleOrchestraSettings particleOrchestraSettings = default(ParticleOrchestraSettings);
            particleOrchestraSettings.PositionInWorld = base.Center;
            particleOrchestraSettings.MovementVector = velocity;
            ParticleOrchestraSettings settings = particleOrchestraSettings;
            ParticleOrchestrator.BroadcastParticleSpawn(ParticleOrchestraType.PetExchange, settings);
        }
        NetMessage.TrySendData(56, -1, -1, null, whoAmI);
        return true;
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastParticleSpawn(), Terraria.GameContent.TownNPCProfiles.GetProfile(), Terraria.GameContent.TownNPCProfiles.Instance, Terraria.Main.netMode, and Terraria.NetMessage.TrySendData().