TModLoader: Terraria.NPC.AI_007_TownEntities_GetWalkPrediction
AI_007_TownEntities_GetWalkPrediction()
void Terraria.NPC.AI_007_TownEntities_GetWalkPrediction (int myTileX, int homeFloorX, bool canBreathUnderWater, bool currentlyDrowning, int tileX, int tileY, out bool keepwalking, out bool avoidFalling) inline private
Definition at line 59252 of file NPC.cs.
    {
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00de: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_021a: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_0228: Unknown result type (might be due to invalid IL or missing references)
        keepwalking = false;
        avoidFalling = true;
        bool flag = myTileX >= homeFloorX - 35 && myTileX <= homeFloorX + 35;
        if (townNPC && ai[1] < 30f)
        {
            keepwalking = !Utils.PlotTileLine(base.Top, base.Bottom, width, DelegateMethods.SearchAvoidedByNPCs);
            if (!keepwalking)
            {
                Rectangle hitbox = base.Hitbox;
                hitbox.X -= 20;
                hitbox.Width += 40;
                for (int i = 0; i < 200; i++)
                {
                    if (Main.npc[i].active && Main.npc[i].friendly && i != whoAmI && Main.npc[i].velocity.X == 0f && ((Rectangle)(ref hitbox)).Intersects(Main.npc[i].Hitbox))
                    {
                        keepwalking = true;
                        break;
                    }
                }
            }
        }
        if (!keepwalking && currentlyDrowning)
        {
            keepwalking = true;
        }
        if (avoidFalling && (NPCID.Sets.TownCritter[type] || (!flag && direction == Math.Sign(homeFloorX - myTileX))))
        {
            avoidFalling = false;
        }
        if (!avoidFalling)
        {
            return;
        }
        bool flag2 = false;
        Point p = default(Point);
        int num = 0;
        for (int j = -1; j <= 4; j++)
        {
            Tile tileSafely = Framing.GetTileSafely(tileX, tileY + j);
            if (tileSafely.liquid > 0)
            {
                num++;
                if (tileSafely.lava())
                {
                    flag2 = true;
                    break;
                }
            }
            if (tileSafely.nactive() && Main.tileSolid[tileSafely.type])
            {
                if (num > 0)
                {
                    p.X = tileX;
                    p.Y = tileY + j;
                }
                avoidFalling = false;
                break;
            }
        }
        avoidFalling |= flag2;
        double num2 = Math.Ceiling((float)height / 16f);
        if ((double)num >= num2)
        {
            avoidFalling = true;
        }
        if (!avoidFalling && p.X != 0 && p.Y != 0)
        {
            Vector2 vector = p.ToWorldCoordinates(8f, 0f) + new Vector2((float)(-width / 2), (float)(-height));
            avoidFalling = Collision.DrownCollision(vector, width, height, 1f);
        }
    }
References Terraria.NPC.ai, Terraria.Entity.direction, Terraria.Collision.DrownCollision(), Terraria.Framing.GetTileSafely(), Terraria.Entity.height, Terraria.Main.npc, Terraria.Utils.PlotTileLine(), Terraria.DelegateMethods.SearchAvoidedByNPCs(), Terraria.Main.tileSolid, Terraria.ID.NPCID.Sets.TownCritter, Terraria.NPC.townNPC, Terraria.NPC.type, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.NPC.AI_007_TownEntities().