TModLoader: Terraria.NPC.DropTombstoneTownNPC
DropTombstoneTownNPC()
void Terraria.NPC.DropTombstoneTownNPC (NetworkText deathText) inline
Definition at line 83929 of file NPC.cs.
    {
        if (Main.netMode != 1)
        {
            float num = 0.1f;
            if (Main.rand.Next(2) == 0)
            {
                num = -0.1f;
            }
            float num2;
            for (num2 = (float)Main.rand.Next(-35, 36) * 0.1f; num2 < 2f && num2 > -2f; num2 += (float)Main.rand.Next(-30, 31) * 0.1f)
            {
            }
            int num3 = Main.rand.Next(6);
            if (type != 17 && type != 441)
            {
                num3 = ((num3 != 0) ? (num3 + 200) : 43);
            }
            else
            {
                num3 = Main.rand.Next(5);
                num3 += 527;
            }
            int num4 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), position.X + (float)(width / 2), position.Y + (float)(height / 2), (float)Main.rand.Next(10, 30) * num + num2, (float)Main.rand.Next(-40, -20) * 0.1f, num3, 0, 0f, Main.myPlayer);
            Main.projectile[num4].miscText = deathText.ToString();
        }
    }
References Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.Entity.height, Terraria.Projectile.miscText, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.projectile, Terraria.Main.rand, Terraria.NPC.type, and Terraria.Entity.width.
Referenced by Terraria.NPC.checkDead().