TModLoader: Terraria.NPC.SpawnOnPlayer
SpawnOnPlayer()
static void Terraria.NPC.SpawnOnPlayer (int plr, int Type) inline static
    {
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_044e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0371: Unknown result type (might be due to invalid IL or missing references)
        //IL_0257: Unknown result type (might be due to invalid IL or missing references)
        //IL_093a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0733: Unknown result type (might be due to invalid IL or missing references)
        //IL_073d: Unknown result type (might be due to invalid IL or missing references)
        //IL_074f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0759: Unknown result type (might be due to invalid IL or missing references)
        //IL_0772: Unknown result type (might be due to invalid IL or missing references)
        //IL_077c: Unknown result type (might be due to invalid IL or missing references)
        //IL_078c: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode == 1 || (Type == 262 && AnyNPCs(262)))
        {
            return;
        }
        Tile tile;
        switch (Type)
        {
        case 245:
            if (AnyNPCs(245))
            {
                return;
            }
            try
            {
                int num12 = (int)Main.player[plr].Center.X / 16;
                int num23 = (int)Main.player[plr].Center.Y / 16;
                int num25 = 0;
                int num26 = 0;
                for (int j = num12 - 20; j < num12 + 20; j++)
                {
                    for (int k = num23 - 20; k < num23 + 20; k++)
                    {
                        tile = Main.tile[j, k];
                        if (!tile.active())
{
                            continue;
                        }
                        tile = Main.tile[j, k];
                        if (tile.type != 237)
{
                            continue;
                        }
                        tile = Main.tile[j, k];
                        if (tile.frameX == 18)
{
                            tile = Main.tile[j, k];
                            if (tile.frameY == 0)
{
                                num25 = j;
                                num26 = k;
                            }
                        }
                    }
                }
                if (num25 <= 0 || num26 <= 0)
                {
                    return;
                }
                int num27 = num26 - 15;
                int num28 = num26 - 15;
                for (int num29 = num26; num29 > num26 - 50; num29--)
                {
                    if (WorldGen.SolidTile(num25, num29))
                    {
                        num27 = num29;
                        break;
                    }
                }
                for (int l = num26; l < num26 + 50; l++)
                {
                    if (WorldGen.SolidTile(num25, l))
                    {
                        num28 = l;
                        break;
                    }
                }
                num26 = (num27 + num27 + num28) / 3;
                int num30 = NewNPC(GetBossSpawnSource(plr), num25 * 16 + 8, num26 * 16, 245);
                Main.npc[num30].target = plr;
                string typeName2 = Main.npc[num30].TypeName;
                if (Main.netMode == 0)
                {
                    Main.NewText(Language.GetTextValue("Announcement.HasAwoken", typeName2), 175, 75);
                }
                else if (Main.netMode == 2)
                {
                    ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", Main.npc[num30].GetTypeNetName()), new Color(175, 75, 255));
                }
                return;
            }
            catch
            {
                return;
            }
        case 370:
        {
            Player player2 = Main.player[plr];
            if (!player2.active || player2.dead)
            {
                return;
            }
            for (int i = 0; i < 1000; i++)
            {
                Projectile projectile = Main.projectile[i];
                if (projectile.active && projectile.bobber && projectile.owner == plr)
                {
                    int num = NewNPC(GetBossSpawnSource(plr), (int)projectile.Center.X, (int)projectile.Center.Y + 100, 370);
                    string typeName = Main.npc[num].TypeName;
                    if (Main.netMode == 0)
                    {
                        Main.NewText(Language.GetTextValue("Announcement.HasAwoken", typeName), 175, 75);
                    }
                    else if (Main.netMode == 2)
                    {
                        ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", Main.npc[num].GetTypeNetName()), new Color(175, 75, 255));
                    }
                    break;
                }
            }
            return;
        }
        case 398:
            if (!AnyNPCs(Type))
            {
                Player player = Main.player[plr];
                NewNPC(GetBossSpawnSource(plr), (int)player.Center.X, (int)player.Center.Y - 150, Type);
                if (Main.netMode == 0)
                {
                    Main.NewText(Language.GetTextValue("Announcement.HasAwoken", Language.GetTextValue("Enemies.MoonLord")), 175, 75);
                }
                else if (Main.netMode == 2)
                {
                    ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", NetworkText.FromKey("Enemies.MoonLord")), new Color(175, 75, 255));
                }
            }
            return;
        }
        bool flag = false;
        int num2 = 0;
        int num3 = 0;
        int num4 = (int)(Main.player[plr].position.X / 16f) - spawnRangeX * 2;
        int num5 = (int)(Main.player[plr].position.X / 16f) + spawnRangeX * 2;
        int num6 = (int)(Main.player[plr].position.Y / 16f) - spawnRangeY * 2;
        int num7 = (int)(Main.player[plr].position.Y / 16f) + spawnRangeY * 2;
        int num8 = (int)(Main.player[plr].position.X / 16f) - safeRangeX;
        int num9 = (int)(Main.player[plr].position.X / 16f) + safeRangeX;
        int num10 = (int)(Main.player[plr].position.Y / 16f) - safeRangeY;
        int num11 = (int)(Main.player[plr].position.Y / 16f) + safeRangeY;
        if (num4 < 0)
        {
            num4 = 0;
        }
        if (num5 > Main.maxTilesX)
        {
            num5 = Main.maxTilesX;
        }
        if (num6 < 0)
        {
            num6 = 0;
        }
        if (num7 > Main.maxTilesY)
        {
            num7 = Main.maxTilesY;
        }
        Rectangle rectangle = default(Rectangle);
        Rectangle rectangle2 = default(Rectangle);
        for (int m = 0; m < 1000; m++)
        {
            for (int n = 0; n < 100; n++)
            {
                int num13 = Main.rand.Next(num4, num5);
                int num14 = Main.rand.Next(num6, num7);
                tile = Main.tile[num13, num14];
                if (tile.nactive())
                {
                    bool[] tileSolid = Main.tileSolid;
                    tile = Main.tile[num13, num14];
                    if (tileSolid[tile.type])
                    {
                        goto IL_085c;
                    }
                }
                bool[] wallHouse = Main.wallHouse;
                tile = Main.tile[num13, num14];
                if (wallHouse[tile.wall] && m < 999)
                {
                    continue;
                }
                if (Type == 50 && m < 500)
                {
                    tile = Main.tile[num14, num14];
                    if (tile.wall > 0)
                    {
                        continue;
                    }
                }
                for (int num15 = num14; num15 < Main.maxTilesY; num15++)
                {
                    tile = Main.tile[num13, num15];
                    if (!tile.nactive())
                    {
                        continue;
                    }
                    bool[] tileSolid2 = Main.tileSolid;
                    tile = Main.tile[num13, num15];
                    if (tileSolid2[tile.type])
                    {
                        if ((num13 < num8 || num13 > num9 || num15 < num10 || num15 > num11 || m == 999) && ((num13 >= num4 && num13 <= num5 && num15 >= num6 && num15 <= num7) || m == 999))
{
                            tile = Main.tile[num13, num15];
                            _ = ref tile.type;
                            num2 = num13;
                            num3 = num15;
                            flag = true;
                        }
                        break;
                    }
                }
                if (flag && Type == 50 && m < 900)
                {
                    int num16 = 20;
                    if (!Collision.CanHit(new Vector2((float)num2, (float)(num3 - 1)) * 16f, 16, 16, new Vector2((float)num2, (float)(num3 - 1 - num16)) * 16f, 16, 16) || !Collision.CanHit(new Vector2((float)num2, (float)(num3 - 1 - num16)) * 16f, 16, 16, Main.player[plr].Center, 0, 0))
                    {
                        num2 = 0;
                        num3 = 0;
                        flag = false;
                    }
                }
                if (flag && m < 999)
                {
                    int num17 = num2 - spawnSpaceX / 2;
                    int num18 = num2 + spawnSpaceX / 2;
                    int num19 = num3 - spawnSpaceY;
                    int num20 = num3;
                    if (num17 < 0)
                    {
                        flag = false;
                    }
                    if (num18 > Main.maxTilesX)
                    {
                        flag = false;
                    }
                    if (num19 < 0)
                    {
                        flag = false;
                    }
                    if (num20 > Main.maxTilesY)
                    {
                        flag = false;
                    }
                    if (flag)
                    {
                        for (int num21 = num17; num21 < num18; num21++)
{
                            for (int num22 = num19; num22 < num20; num22++)
{
                                tile = Main.tile[num21, num22];
                                if (tile.nactive())
{
                                    bool[] tileSolid3 = Main.tileSolid;
                                    tile = Main.tile[num21, num22];
                                    if (tileSolid3[tile.type])
{
                                        flag = false;
                                        break;
                                    }
                                }
                            }
                        }
                    }
                }
                goto IL_085c;
                IL_085c:
                if (flag || flag)
                {
                    break;
                }
            }
            if (flag && m < 999)
            {
                ((Rectangle)(ref rectangle))._002Ector(num2 * 16, num3 * 16, 16, 16);
                for (int num24 = 0; num24 < 255; num24++)
                {
                    if (Main.player[num24].active)
                    {
                        ((Rectangle)(ref rectangle2))._002Ector((int)(Main.player[num24].position.X + (float)(Main.player[num24].width / 2) - (float)(sWidth / 2) - (float)safeRangeX), (int)(Main.player[num24].position.Y + (float)(Main.player[num24].height / 2) - (float)(sHeight / 2) - (float)safeRangeY), sWidth + safeRangeX * 2, sHeight + safeRangeY * 2);
                        if (((Rectangle)(ref rectangle)).Intersects(rectangle2))
{
                            flag = false;
                        }
                    }
                }
            }
            if (flag)
            {
                break;
            }
        }
        if (flag)
        {
            int spawnPositionX = num2 * 16 + 8;
            int spawnPositionY = num3 * 16;
            SpawnBoss(spawnPositionX, spawnPositionY, Type, plr);
        }
    }
References Terraria.Entity.active, Terraria.Tile.active(), Terraria.Projectile.bobber, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Localization.NetworkText.FromKey(), Terraria.Localization.Language.GetTextValue(), Terraria.NPC.GetTypeNetName(), Terraria.Entity.height, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Main.NewText(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.WorldGen.SolidTile(), Terraria.NPC.target, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, Terraria.NPC.TypeName, Terraria.Tile.wall, Terraria.Main.wallHouse, and Terraria.Entity.width.
Referenced by Terraria.WorldGen.Check3x3(), Terraria.WorldGen.CheckJunglePlant(), Terraria.WorldGen.CheckOrb(), Terraria.WorldGen.CheckSign(), Terraria.NPC.DoDeathEvents(), Terraria.NPC.DoDeathEvents_AdvanceSlimeRain(), Terraria.MessageBuffer.GetData(), Terraria.Player.ItemCheck_CheckFishingBobber_PullBobber(), Terraria.Player.ItemCheck_UseBossSpawners(), Terraria.WorldGen.SmashAltar(), Terraria.NPC.SpawnMechQueen(), Terraria.GameContent.Events.DD2Event.SummonBetsy(), Terraria.Player.TileInteractionsUse(), and Terraria.Main.UpdateTime().