TModLoader: Terraria.NPC.GetShimmered
GetShimmered()
void Terraria.NPC.GetShimmered () inline private
    {
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0201: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        if (SpawnedFromStatue)
        {
            if (Main.netMode == 0)
            {
                Item.ShimmerEffect(base.Center);
            }
            else
            {
                NetMessage.SendData(146, -1, -1, null, 0, (int)base.Center.X, (int)base.Center.Y);
            }
            noSpawnCycle = true;
            active = false;
            if (Main.netMode == 2)
            {
                netSkip = -1;
                life = 0;
                NetMessage.SendData(23, -1, -1, null, whoAmI);
            }
        }
        else if (NPCID.Sets.ShimmerTransformToNPC[type] >= 0)
        {
            Transform(NPCID.Sets.ShimmerTransformToNPC[type]);
            if (Main.netMode == 0)
            {
                Item.ShimmerEffect(base.Center);
            }
            else
            {
                NetMessage.SendData(146, -1, -1, null, 0, (int)base.Center.X, (int)base.Center.Y);
            }
        }
        else if (NPCID.Sets.ShimmerTransformToItem[type] >= 0)
        {
            int num = Item.NewItem(GetItemSource_Misc(8), (int)position.X, (int)position.Y, width, height, NPCID.Sets.ShimmerTransformToItem[type]);
            Main.item[num].stack = 1;
            Main.item[num].shimmerTime = 1f;
            Main.item[num].shimmered = true;
            Main.item[num].shimmerWet = true;
            Main.item[num].wet = true;
            Item obj = Main.item[num];
            obj.velocity *= 0.1f;
            Main.item[num].playerIndexTheItemIsReservedFor = Main.myPlayer;
            NetMessage.SendData(145, -1, -1, null, num, 1f);
            if (Main.netMode == 0)
            {
                Item.ShimmerEffect(base.Center);
            }
            else
            {
                NetMessage.SendData(146, -1, -1, null, 0, (int)base.Center.X, (int)base.Center.Y);
            }
            noSpawnCycle = true;
            active = false;
            if (Main.netMode == 2)
            {
                netSkip = -1;
                life = 0;
                NetMessage.SendData(23, -1, -1, null, whoAmI);
            }
        }
        else if (NPCID.Sets.ShimmerTownTransform[type])
        {
            ai[0] = 25f;
            ai[1] = 0f;
            ai[2] = 0f;
            ai[3] = 0f;
            netUpdate = true;
            shimmerTransparency = 0.89f;
            int num2 = FindBuffIndex(353);
            if (num2 != -1)
            {
                DelBuff(num2);
            }
        }
    }
References Terraria.Main.item, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Item.playerIndexTheItemIsReservedFor, Terraria.NetMessage.SendData(), Terraria.Item.shimmered, Terraria.Item.ShimmerEffect(), Terraria.Item.shimmerTime, Terraria.ID.NPCID.Sets.ShimmerTownTransform, Terraria.ID.NPCID.Sets.ShimmerTransformToItem, Terraria.ID.NPCID.Sets.ShimmerTransformToNPC, Terraria.Entity.shimmerWet, Terraria.Item.stack, and Terraria.Entity.wet.
Referenced by Terraria.NPC.VanillaAI_Inner().