TModLoader: Terraria.NPC.GetMeleeCollisionData
GetMeleeCollisionData()
static void Terraria.NPC.GetMeleeCollisionData (Rectangle victimHitbox, int enemyIndex, ref int specialHitSetter, ref float damageMultiplier, ref Rectangle npcRect) inline static
    {
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_012e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0202: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_025a: Unknown result type (might be due to invalid IL or missing references)
        //IL_025c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0349: Unknown result type (might be due to invalid IL or missing references)
        //IL_0384: Unknown result type (might be due to invalid IL or missing references)
        //IL_038f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0377: Unknown result type (might be due to invalid IL or missing references)
        //IL_041c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03af: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0466: Unknown result type (might be due to invalid IL or missing references)
        //IL_043e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0474: Unknown result type (might be due to invalid IL or missing references)
        //IL_0476: Unknown result type (might be due to invalid IL or missing references)
        //IL_0506: Unknown result type (might be due to invalid IL or missing references)
        //IL_0541: Unknown result type (might be due to invalid IL or missing references)
        //IL_054c: Unknown result type (might be due to invalid IL or missing references)
        //IL_055e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0534: Unknown result type (might be due to invalid IL or missing references)
        //IL_0569: Unknown result type (might be due to invalid IL or missing references)
        //IL_056b: Unknown result type (might be due to invalid IL or missing references)
        NPC nPC = Main.npc[enemyIndex];
        if (!NPCLoader.ModifyCollisionData(nPC, victimHitbox, ref specialHitSetter, ref damageMultiplier, ref npcRect))
        {
            return;
        }
        if (((nPC.type >= 430 && nPC.type <= 436) || nPC.type == 591) && nPC.ai[2] > 5f)
        {
            int num = 34;
            if (nPC.spriteDirection < 0)
            {
                npcRect.X -= num;
                npcRect.Width += num;
            }
            else
            {
                npcRect.Width += num;
            }
            damageMultiplier *= 1.25f;
        }
        else if (nPC.type >= 494 && nPC.type <= 495 && nPC.ai[2] > 5f)
        {
            int num2 = 18;
            if (nPC.spriteDirection < 0)
            {
                npcRect.X -= num2;
                npcRect.Width += num2;
            }
            else
            {
                npcRect.Width += num2;
            }
            damageMultiplier *= 1.25f;
        }
        else if (nPC.type == 460)
        {
            Rectangle rectangle = default(Rectangle);
            ((Rectangle)(ref rectangle))._002Ector(0, 0, 30, 14);
            rectangle.X = (int)nPC.Center.X;
            if (nPC.direction < 0)
            {
                rectangle.X -= rectangle.Width;
            }
            rectangle.Y = (int)nPC.position.Y + nPC.height - 20;
            if (((Rectangle)(ref victimHitbox)).Intersects(rectangle))
            {
                npcRect = rectangle;
                damageMultiplier *= 1.35f;
            }
        }
        else if (nPC.type == 417 && nPC.ai[0] == 6f && nPC.ai[3] > 0f && nPC.ai[3] < 4f)
        {
            Rectangle rectangle2 = Utils.CenteredRectangle(nPC.Center, new Vector2(100f));
            if (((Rectangle)(ref victimHitbox)).Intersects(rectangle2))
            {
                npcRect = rectangle2;
                damageMultiplier *= 1.35f;
            }
        }
        else if (nPC.type == 466)
        {
            Rectangle rectangle3 = default(Rectangle);
            ((Rectangle)(ref rectangle3))._002Ector(0, 0, 30, 8);
            rectangle3.X = (int)nPC.Center.X;
            if (nPC.direction < 0)
            {
                rectangle3.X -= rectangle3.Width;
            }
            rectangle3.Y = (int)nPC.position.Y + nPC.height - 32;
            if (((Rectangle)(ref victimHitbox)).Intersects(rectangle3))
            {
                npcRect = rectangle3;
                damageMultiplier *= 1.75f;
            }
        }
        else if (nPC.type == 576 || nPC.type == 577)
        {
            NPC nPC2 = nPC;
            bool flag = true;
            int y = nPC2.frame.Y;
            int num3 = 0;
            int num4 = 0;
            Rectangle rectangle4 = default(Rectangle);
            ((Rectangle)(ref rectangle4))._002Ector(0, 0, 30, 8);
            switch (y)
            {
            case 15:
                specialHitSetter = 2;
                rectangle4.Width = 120;
                rectangle4.Height = 30;
                num4 = 24;
                break;
            case 16:
                specialHitSetter = 2;
                rectangle4.Width = 120;
                rectangle4.Height = 60;
                num3 = 10;
                break;
            case 17:
                specialHitSetter = 2;
                rectangle4.Width = 100;
                rectangle4.Height = 90;
                num3 = 50;
                break;
            case 18:
                specialHitSetter = 2;
                rectangle4.Width = 100;
                rectangle4.Height = 50;
                num3 = 90;
                num4 = 10;
                break;
            default:
                flag = false;
                break;
            }
            if (flag)
            {
                rectangle4.X = (int)nPC2.Center.X - num3 * nPC2.direction;
                if (nPC2.direction < 0)
                {
                    rectangle4.X -= rectangle4.Width;
                }
                rectangle4.Y = (int)nPC2.Center.Y - rectangle4.Height + num4;
                if (((Rectangle)(ref victimHitbox)).Intersects(rectangle4))
                {
                    npcRect = rectangle4;
                    damageMultiplier *= 1.75f;
                }
            }
        }
        else if ((nPC.type == 552 || nPC.type == 553 || nPC.type == 554) && nPC.ai[0] > 0f && nPC.ai[0] < 24f)
        {
            Rectangle rectangle5 = default(Rectangle);
            ((Rectangle)(ref rectangle5))._002Ector(0, 0, 34, 14);
            rectangle5.X = (int)nPC.Center.X;
            if (nPC.direction < 0)
            {
                rectangle5.X -= rectangle5.Width;
            }
            rectangle5.Y = (int)nPC.position.Y + nPC.height - 20;
            if (((Rectangle)(ref victimHitbox)).Intersects(rectangle5))
            {
                npcRect = rectangle5;
                damageMultiplier *= 1.35f;
            }
        }
        else
        {
            if (nPC.type != 668)
            {
                return;
            }
            npcRect.Height -= 80;
            NPC nPC3 = nPC;
            bool flag2 = true;
            int y2 = nPC3.frame.Y;
            int num5 = 0;
            int num6 = 0;
            Rectangle rectangle6 = default(Rectangle);
            ((Rectangle)(ref rectangle6))._002Ector(0, 0, 30, 8);
            if (y2 == 15)
            {
                rectangle6.Width = 64;
                rectangle6.Height = 180;
                num6 = 80;
                num5 = -42;
                if (nPC3.ai[0] == 4f)
                {
                    flag2 = false;
                }
            }
            else
            {
                flag2 = false;
            }
            if (flag2)
            {
                rectangle6.X = (int)nPC3.Center.X - num5 * nPC3.direction;
                if (nPC3.direction < 0)
                {
                    rectangle6.X -= rectangle6.Width;
                }
                rectangle6.Y = (int)nPC3.Center.Y - rectangle6.Height + num6;
                if (((Rectangle)(ref victimHitbox)).Intersects(rectangle6))
                {
                    npcRect = rectangle6;
                }
            }
        }
    }
References Terraria.Utils.CenteredRectangle(), Terraria.ModLoader.NPCLoader.ModifyCollisionData(), and Terraria.Main.npc.
Referenced by Terraria.Player.Update_NPCCollision().