TModLoader: Terraria.NPC.AI_122_PirateGhost
AI_122_PirateGhost()
void Terraria.NPC.AI_122_PirateGhost () inline
    {
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        if (localAI[0] == 0f)
        {
            localAI[0] = 1f;
            SoundEngine.PlaySound(in SoundID.NPCHit6, position);
        }
        NPCAimedTarget targetData = GetTargetData();
        if (targetData.Invalid)
        {
            TargetClosest();
            targetData = GetTargetData();
        }
        if (targetData.Invalid)
        {
            velocity *= 0.9f;
            alpha = Utils.Clamp(alpha + 5, 0, 255);
            if (alpha >= 255)
            {
                StrikeNPCNoInteraction(9999, 0f, 0);
            }
            return;
        }
        alpha = Utils.Clamp(alpha - 5, 0, 255);
        Vector2 targetPosition = Vector2.Zero.MoveTowards(targetData.Center - base.Center, 4f);
        velocity = velocity.MoveTowards(targetPosition, 2f / 15f);
        for (int i = 0; i < 200; i++)
        {
            if (Main.npc[i].active && Main.npc[i].type == type && i != whoAmI)
            {
                Vector2 vector = Main.npc[i].Center - base.Center;
                if (((Vector2)(ref vector)).Length() < 50f)
                {
                    ((Vector2)(ref vector)).Normalize();
                    vector *= 0.1f;
                    velocity -= vector;
                    velocity.X -= vector.X * 1f;
                }
            }
        }
    }
References Terraria.Entity.active, Terraria.NPC.alpha, Terraria.Entity.Center, Terraria.NPC.GetTargetData(), Terraria.NPC.localAI, Terraria.Main.npc, Terraria.ID.SoundID.NPCHit6, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.NPC.StrikeNPCNoInteraction(), Terraria.NPC.TargetClosest(), Terraria.NPC.type, Terraria.Entity.velocity, and Terraria.Entity.whoAmI.
Referenced by Terraria.NPC.VanillaAI_Inner().