TModLoader: Terraria.NPC.ReflectProjectiles
ReflectProjectiles()
void Terraria.NPC.ReflectProjectiles (Rectangle myRect) inline
    {
        for (int i = 0; i < 1000; i++)
        {
            if (Main.projectile[i].active && Main.projectile[i].CanBeReflected() && CanReflectProjectile(Main.projectile[i]))
            {
                ReflectProjectile(Main.projectile[i]);
            }
        }
    }
References Terraria.Entity.active, Terraria.Projectile.CanBeReflected(), Terraria.NPC.CanReflectProjectile(), Terraria.Main.projectile, and Terraria.NPC.ReflectProjectile().
Referenced by Terraria.NPC.VanillaAI_Inner().