TModLoader: Terraria.NPC.AI_123_Deerclops_TryMakingSpike_FindBestY
AI_123_Deerclops_TryMakingSpike_FindBestY()
int Terraria.NPC.AI_123_Deerclops_TryMakingSpike_FindBestY (ref Point sourceTileCoords, int x) inline private
    {
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        int num = sourceTileCoords.Y;
        NPCAimedTarget targetData = GetTargetData();
        if (!targetData.Invalid)
        {
            Rectangle hitbox = targetData.Hitbox;
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector((float)((Rectangle)(ref hitbox)).Center.X, (float)((Rectangle)(ref hitbox)).Bottom);
            int num7 = (int)(vector.Y / 16f);
            int num2 = Math.Sign(num7 - num);
            int num3 = num7 + num2 * 15;
            int? num4 = null;
            float num5 = float.PositiveInfinity;
            for (int i = num; i != num3; i += num2)
            {
                if (WorldGen.ActiveAndWalkableTile(x, i))
                {
                    float num6 = Utils.ToWorldCoordinates(new Point(x, i), 8f, 8f).Distance(vector);
                    if (!num4.HasValue || !(num6 >= num5))
                    {
                        num4 = i;
                        num5 = num6;
                    }
                }
            }
            if (num4.HasValue)
            {
                num = num4.Value;
            }
        }
        for (int j = 0; j < 20; j++)
        {
            if (num < 10)
            {
                break;
            }
            if (!WorldGen.SolidTile(x, num))
            {
                break;
            }
            num--;
        }
        for (int k = 0; k < 20; k++)
        {
            if (num > Main.maxTilesY - 10)
            {
                break;
            }
            if (WorldGen.ActiveAndWalkableTile(x, num))
            {
                break;
            }
            num++;
        }
        return num;
    }
References Terraria.WorldGen.ActiveAndWalkableTile(), Terraria.Entity.Bottom, Terraria.Entity.Center, Terraria.Entity.Distance(), Terraria.NPC.GetTargetData(), Terraria.Main.maxTilesY, Terraria.WorldGen.SolidTile(), and Terraria.Utils.ToWorldCoordinates().
Referenced by Terraria.NPC.AI_123_Deerclops_TryMakingSpike().