TModLoader: Terraria.NPC.CheckCatchNPC
CheckCatchNPC()
static bool Terraria.NPC.CheckCatchNPC (NPC npc, Rectangle catchToolRectangle, Item item, Player player, bool lavaProofTool = false) inline static
Runs most code related to the process of checking whether or not an NPC can be caught.
After that, M:Terraria.ModLoader.CombinedHooks.OnCatchNPC(Terraria.Player,Terraria.NPC,Terraria.Item,System.Boolean) is run, followed by the code responsible for catching the NPC if applicable.
You will need to call this manually if you want to make an NPC-catching tool which acts differently from vanilla's, such as one that uses a projectile instead of an item.
As a note, if calling this manually, you will need to check npc.active && npc.catchItem > 0 yourself.
Parameters
npc The NPC which can potentially be caught.
catchToolRectangle The hitbox of the tool being used to catch the NPC — be it an item, a projectile, or something else entirely.
item The item to be used as a reference for the purposes of M:Terraria.ModLoader.CombinedHooks.CanCatchNPC(Terraria.Player,Terraria.NPC,Terraria.Item) and M:Terraria.ModLoader.CombinedHooks.OnCatchNPC(Terraria.Player,Terraria.NPC,Terraria.Item,System.Boolean).
player The player that owns the referenced item.
lavaProofTool Whether or not the tool is lavaproof for the purposes of catching vanilla's Underworld critters. Defaults to false.
Returns
Whether or not the NPC was successfully caught.
Definition at line 112597 of file NPC.cs.
    {
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        Rectangle value = default(Rectangle);
        ((Rectangle)(ref value))._002Ector((int)npc.position.X, (int)npc.position.Y, npc.width, npc.height);
        if (!((Rectangle)(ref catchToolRectangle)).Intersects(value))
        {
            return false;
        }
        bool? canCatch = CombinedHooks.CanCatchNPC(player, npc, item);
        if (canCatch.HasValue)
        {
            CombinedHooks.OnCatchNPC(player, npc, item, !canCatch.Value);
            if (canCatch.Value)
            {
                CatchNPC(npc.whoAmI, player.whoAmI);
            }
            return canCatch.Value;
        }
        if (!lavaProofTool && ItemID.Sets.IsLavaBait[npc.catchItem])
        {
            CombinedHooks.OnCatchNPC(player, npc, item, failed: true);
            if (Main.myPlayer == player.whoAmI && player.Hurt(PlayerDeathReason.ByNPC(npc.whoAmI), 1, (npc.Center.X < player.Center.X) ? 1 : (-1), pvp: false, quiet: false, 3) > 0.0 && !player.dead)
            {
                player.AddBuff(24, 300);
            }
            return false;
        }
        int num = npc.type;
        if (num == 585 || num == 583 || num == 584)
        {
            bool canCatchFairy = npc.ai[2] <= 1f;
            CombinedHooks.OnCatchNPC(player, npc, item, !canCatchFairy);
            if (canCatchFairy)
            {
                CatchNPC(npc.whoAmI, player.whoAmI);
            }
            return canCatchFairy;
        }
        CombinedHooks.OnCatchNPC(player, npc, item, failed: false);
        CatchNPC(npc.whoAmI, player.whoAmI);
        return true;
    }
References Terraria.Player.AddBuff(), Terraria.NPC.ai, Terraria.DataStructures.PlayerDeathReason.ByNPC(), Terraria.ModLoader.CombinedHooks.CanCatchNPC(), Terraria.NPC.catchItem, Terraria.Entity.Center, Terraria.Player.dead, Terraria.Entity.height, Terraria.Player.Hurt(), Terraria.ID.ItemID.Sets.IsLavaBait, Terraria.Main.myPlayer, Terraria.ModLoader.CombinedHooks.OnCatchNPC(), Terraria.Entity.position, Terraria.NPC.type, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.ItemCheck_CatchCritters().