TModLoader: Terraria.NPC.SpawnStardustMark_StardustTower
SpawnStardustMark_StardustTower()
void Terraria.NPC.SpawnStardustMark_StardustTower () inline private
Definition at line 44155 of file NPC.cs.
    {
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_0239: Unknown result type (might be due to invalid IL or missing references)
        //IL_0243: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_0257: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0282: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f0: Unknown result type (might be due to invalid IL or missing references)
        List<int> list = new List<int>();
        if (CountNPCS(405) + CountNPCS(406) < 2)
        {
            list.Add(405);
        }
        if (CountNPCS(402) < 2)
        {
            list.Add(402);
        }
        if (CountNPCS(407) < 1)
        {
            list.Add(407);
        }
        if (list.Count > 0)
        {
            int num = Utils.SelectRandom(Main.rand, list.ToArray());
            ai[1] = 30 * Main.rand.Next(5, 16);
            int num5 = Main.rand.Next(3, 6);
            int num6 = Main.rand.Next(0, 4);
            int num7 = 0;
            List<Tuple<Vector2, int, int>> list2 = new List<Tuple<Vector2, int, int>>();
            List<Vector2> list3 = new List<Vector2>();
            list2.Add(Tuple.Create<Vector2, int, int>(base.Top - Vector2.UnitY * 120f, num5, 0));
            int num8 = 0;
            int num9 = list2.Count;
            while (list2.Count > 0)
            {
                Vector2 item = list2[0].Item1;
                int num10 = 1;
                int num11 = 1;
                if (num8 > 0 && num6 > 0 && (Main.rand.Next(3) != 0 || num8 == 1))
                {
                    num11 = Main.rand.Next(Math.Max(1, list2[0].Item2));
                    num10++;
                    num6--;
                }
                for (int i = 0; i < num10; i++)
                {
                    int num12 = list2[0].Item3;
                    if (num8 == 0)
                    {
                        num12 = Utils.SelectRandom<int>(Main.rand, -1, 1);
                    }
                    else if (i == 1)
                    {
                        num12 *= -1;
                    }
                    float num2 = ((num8 % 2 == 0) ? 0f : ((float)Math.PI)) + (0.5f - Main.rand.NextFloat()) * ((float)Math.PI / 4f) + (float)num12 * ((float)Math.PI / 4f) * (float)(num8 % 2 == 0).ToDirectionInt();
                    float num3 = 100f + 50f * Main.rand.NextFloat();
                    int num4 = list2[0].Item2;
                    if (i != 0)
                    {
                        num4 = num11;
                    }
                    if (num8 == 0)
                    {
                        num2 = (0.5f - Main.rand.NextFloat()) * ((float)Math.PI / 4f);
                        num3 = 100f + 100f * Main.rand.NextFloat();
                    }
                    Vector2 vector = (-Vector2.UnitY).RotatedBy(num2) * num3;
                    if (num4 - 1 < 0)
                    {
                        vector = Vector2.Zero;
                    }
                    num7 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), item.X, item.Y, vector.X, vector.Y, 540, 0, 0f, Main.myPlayer, (float)(-num8) * 10f, 0.5f + Main.rand.NextFloat() * 0.5f);
                    list3.Add(item + vector);
                    if (num8 < num5 && list2[0].Item2 > 0)
                    {
                        list2.Add(Tuple.Create<Vector2, int, int>(item + vector, num4 - 1, num12));
                    }
                }
                list2.Remove(list2[0]);
                if (--num9 == 0)
                {
                    num9 = list2.Count;
                    num8++;
                }
            }
            Main.projectile[num7].localAI[0] = num;
        }
        else
        {
            ai[1] = 30f;
        }
    }
References Terraria.NPC.ai, Terraria.NPC.CountNPCS(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.Projectile.localAI, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.projectile, and Terraria.Main.rand.
Referenced by Terraria.NPC.VanillaAI_Inner().