TModLoader: Terraria.NPC.AI_084_LunaticCultist
AI_084_LunaticCultist()
void Terraria.NPC.AI_084_LunaticCultist () inline private
Definition at line 68990 of file NPC.cs.
    {
        //IL_0496: Unknown result type (might be due to invalid IL or missing references)
        //IL_049b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0303: Unknown result type (might be due to invalid IL or missing references)
        //IL_0308: Unknown result type (might be due to invalid IL or missing references)
        //IL_051c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0521: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0853: Unknown result type (might be due to invalid IL or missing references)
        //IL_085d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_075f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0769: Unknown result type (might be due to invalid IL or missing references)
        //IL_076e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1201: Unknown result type (might be due to invalid IL or missing references)
        //IL_1206: Unknown result type (might be due to invalid IL or missing references)
        //IL_1208: Unknown result type (might be due to invalid IL or missing references)
        //IL_120d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1212: Unknown result type (might be due to invalid IL or missing references)
        //IL_1214: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1922: Unknown result type (might be due to invalid IL or missing references)
        //IL_1927: Unknown result type (might be due to invalid IL or missing references)
        //IL_1929: Unknown result type (might be due to invalid IL or missing references)
        //IL_192e: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_11cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1946: Unknown result type (might be due to invalid IL or missing references)
        //IL_15eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_15f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_21b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_21b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_21b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_21bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_21c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_21c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_217a: Unknown result type (might be due to invalid IL or missing references)
        //IL_217f: Unknown result type (might be due to invalid IL or missing references)
        //IL_145e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1468: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_10cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_10d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_10d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_18eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_18f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_1103: Unknown result type (might be due to invalid IL or missing references)
        //IL_1108: Unknown result type (might be due to invalid IL or missing references)
        //IL_110d: Unknown result type (might be due to invalid IL or missing references)
        //IL_149b: Unknown result type (might be due to invalid IL or missing references)
        //IL_14a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_14a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_14a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_14b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_14b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_14bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_14c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_14c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2923: Unknown result type (might be due to invalid IL or missing references)
        //IL_2928: Unknown result type (might be due to invalid IL or missing references)
        //IL_25e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_25e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_20f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_20f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_14f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_14fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_1114: Unknown result type (might be due to invalid IL or missing references)
        //IL_111b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1120: Unknown result type (might be due to invalid IL or missing references)
        //IL_1128: Unknown result type (might be due to invalid IL or missing references)
        //IL_112f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1136: Unknown result type (might be due to invalid IL or missing references)
        //IL_113d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a94: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aaf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2408: Unknown result type (might be due to invalid IL or missing references)
        //IL_2412: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f46: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f59: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fef: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ff4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ff6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ff9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ffe: Unknown result type (might be due to invalid IL or missing references)
        //IL_2003: Unknown result type (might be due to invalid IL or missing references)
        //IL_2005: Unknown result type (might be due to invalid IL or missing references)
        //IL_2007: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f22: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f27: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f29: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f31: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f36: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f38: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1509: Unknown result type (might be due to invalid IL or missing references)
        //IL_1522: Unknown result type (might be due to invalid IL or missing references)
        //IL_1527: Unknown result type (might be due to invalid IL or missing references)
        //IL_1529: Unknown result type (might be due to invalid IL or missing references)
        //IL_1534: Unknown result type (might be due to invalid IL or missing references)
        //IL_1539: Unknown result type (might be due to invalid IL or missing references)
        //IL_1541: Unknown result type (might be due to invalid IL or missing references)
        //IL_1548: Unknown result type (might be due to invalid IL or missing references)
        //IL_154f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1556: Unknown result type (might be due to invalid IL or missing references)
        //IL_26bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_26c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2445: Unknown result type (might be due to invalid IL or missing references)
        //IL_244a: Unknown result type (might be due to invalid IL or missing references)
        //IL_244c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2453: Unknown result type (might be due to invalid IL or missing references)
        //IL_245d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2462: Unknown result type (might be due to invalid IL or missing references)
        //IL_2467: Unknown result type (might be due to invalid IL or missing references)
        //IL_246c: Unknown result type (might be due to invalid IL or missing references)
        //IL_246e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2026: Unknown result type (might be due to invalid IL or missing references)
        //IL_2013: Unknown result type (might be due to invalid IL or missing references)
        //IL_2018: Unknown result type (might be due to invalid IL or missing references)
        //IL_201d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f59: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f46: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f50: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dda: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ddf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1de1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1de4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1de9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dee: Unknown result type (might be due to invalid IL or missing references)
        //IL_1df0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1df2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d12: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d14: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d17: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d21: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d23: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d25: Unknown result type (might be due to invalid IL or missing references)
        //IL_16d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_16dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_16e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_16ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_1306: Unknown result type (might be due to invalid IL or missing references)
        //IL_130b: Unknown result type (might be due to invalid IL or missing references)
        //IL_130f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1319: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f95: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb7: Unknown result type (might be due to invalid IL or missing references)
        //IL_248b: Unknown result type (might be due to invalid IL or missing references)
        //IL_249f: Unknown result type (might be due to invalid IL or missing references)
        //IL_24a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_24a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2048: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e11: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dfe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e03: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e08: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d44: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d31: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d36: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fcc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2072: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fa5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e33: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d66: Unknown result type (might be due to invalid IL or missing references)
        //IL_171f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1724: Unknown result type (might be due to invalid IL or missing references)
        //IL_1726: Unknown result type (might be due to invalid IL or missing references)
        //IL_172d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1737: Unknown result type (might be due to invalid IL or missing references)
        //IL_173c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1741: Unknown result type (might be due to invalid IL or missing references)
        //IL_1746: Unknown result type (might be due to invalid IL or missing references)
        //IL_1748: Unknown result type (might be due to invalid IL or missing references)
        //IL_1848: Unknown result type (might be due to invalid IL or missing references)
        //IL_1853: Unknown result type (might be due to invalid IL or missing references)
        //IL_134e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1353: Unknown result type (might be due to invalid IL or missing references)
        //IL_1355: Unknown result type (might be due to invalid IL or missing references)
        //IL_135c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1366: Unknown result type (might be due to invalid IL or missing references)
        //IL_136b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1370: Unknown result type (might be due to invalid IL or missing references)
        //IL_1375: Unknown result type (might be due to invalid IL or missing references)
        //IL_1377: Unknown result type (might be due to invalid IL or missing references)
        //IL_24c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_24c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_24ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_24cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_24e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_24ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_24ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_24f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_251f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2527: Unknown result type (might be due to invalid IL or missing references)
        //IL_253e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2545: Unknown result type (might be due to invalid IL or missing references)
        //IL_2560: Unknown result type (might be due to invalid IL or missing references)
        //IL_2562: Unknown result type (might be due to invalid IL or missing references)
        //IL_22ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_22b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_22b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_22be: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d90: Unknown result type (might be due to invalid IL or missing references)
        //IL_1764: Unknown result type (might be due to invalid IL or missing references)
        //IL_1775: Unknown result type (might be due to invalid IL or missing references)
        //IL_177a: Unknown result type (might be due to invalid IL or missing references)
        //IL_177f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1393: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_13ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_138c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1391: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1011: Unknown result type (might be due to invalid IL or missing references)
        //IL_1016: Unknown result type (might be due to invalid IL or missing references)
        //IL_1018: Unknown result type (might be due to invalid IL or missing references)
        //IL_1023: Unknown result type (might be due to invalid IL or missing references)
        //IL_1028: Unknown result type (might be due to invalid IL or missing references)
        //IL_1030: Unknown result type (might be due to invalid IL or missing references)
        //IL_1037: Unknown result type (might be due to invalid IL or missing references)
        //IL_103e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1045: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b81: Unknown result type (might be due to invalid IL or missing references)
        //IL_2700: Unknown result type (might be due to invalid IL or missing references)
        //IL_2705: Unknown result type (might be due to invalid IL or missing references)
        //IL_270a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2718: Unknown result type (might be due to invalid IL or missing references)
        //IL_271d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2722: Unknown result type (might be due to invalid IL or missing references)
        //IL_2730: Unknown result type (might be due to invalid IL or missing references)
        //IL_2736: Unknown result type (might be due to invalid IL or missing references)
        //IL_273b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2740: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1aa1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ab9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1abf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1acd: Unknown result type (might be due to invalid IL or missing references)
        //IL_22f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_22f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_22fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_2301: Unknown result type (might be due to invalid IL or missing references)
        //IL_230b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2310: Unknown result type (might be due to invalid IL or missing references)
        //IL_2315: Unknown result type (might be due to invalid IL or missing references)
        //IL_231a: Unknown result type (might be due to invalid IL or missing references)
        //IL_231c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1789: Unknown result type (might be due to invalid IL or missing references)
        //IL_17a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_17a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_17a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_17b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_17b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_17c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_17c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_17cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_13d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_13d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_13d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_13e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_13e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_13f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_13f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_13fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1405: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bfb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c09: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c12: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c17: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c43: Unknown result type (might be due to invalid IL or missing references)
        //IL_2338: Unknown result type (might be due to invalid IL or missing references)
        //IL_2349: Unknown result type (might be due to invalid IL or missing references)
        //IL_234e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2353: Unknown result type (might be due to invalid IL or missing references)
        //IL_2331: Unknown result type (might be due to invalid IL or missing references)
        //IL_2336: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2779: Unknown result type (might be due to invalid IL or missing references)
        //IL_2783: Unknown result type (might be due to invalid IL or missing references)
        //IL_279b: Unknown result type (might be due to invalid IL or missing references)
        //IL_27a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_27ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_27f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_27c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_235d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2376: Unknown result type (might be due to invalid IL or missing references)
        //IL_237b: Unknown result type (might be due to invalid IL or missing references)
        //IL_237d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2388: Unknown result type (might be due to invalid IL or missing references)
        //IL_238d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2395: Unknown result type (might be due to invalid IL or missing references)
        //IL_239c: Unknown result type (might be due to invalid IL or missing references)
        //IL_23a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_23aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_2803: Unknown result type (might be due to invalid IL or missing references)
        //IL_27d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2811: Unknown result type (might be due to invalid IL or missing references)
        //IL_27e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c66: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ca4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ca9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cc9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cce: Unknown result type (might be due to invalid IL or missing references)
        //IL_281f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b41: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b59: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b61: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b66: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c17: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b80: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b88: Unknown result type (might be due to invalid IL or missing references)
        if (this.ai[0] != -1f && Main.rand.Next(1000) == 0)
        {
            SoundEngine.PlaySound(29, (int)position.X, (int)position.Y, Main.rand.Next(88, 92));
        }
        bool expertMode = Main.expertMode;
        bool flag = life <= lifeMax / 2;
        int num = 120;
        int attackDamage_ForProjectiles = GetAttackDamage_ForProjectiles(35f, 25f);
        if (expertMode)
        {
            num = 90;
        }
        if (Main.getGoodWorld)
        {
            num -= 30;
        }
        int num12 = 18;
        int num23 = 3;
        int attackDamage_ForProjectiles2 = GetAttackDamage_ForProjectiles(30f, 20f);
        if (expertMode)
        {
            num12 = 12;
            num23 = 4;
        }
        if (Main.getGoodWorld)
        {
            num12 = 10;
            num23 = 5;
        }
        int num34 = 80;
        int attackDamage_ForProjectiles3 = GetAttackDamage_ForProjectiles(45f, 30f);
        if (expertMode)
        {
            num34 = 40;
        }
        if (Main.getGoodWorld)
        {
            num34 -= 20;
        }
        int num45 = 20;
        int num56 = 2;
        if (expertMode)
        {
            num45 = 30;
            num56 = 2;
        }
        int num58 = 20;
        int num59 = 3;
        bool flag2 = type == 439;
        bool flag3 = false;
        bool flag4 = false;
        if (flag)
        {
            defense = (int)((float)defDefense * 0.65f);
        }
        if (!flag2)
        {
            if (this.ai[3] < 0f || !Main.npc[(int)this.ai[3]].active || Main.npc[(int)this.ai[3]].type != 439)
            {
                life = 0;
                HitEffect();
                active = false;
                return;
            }
            this.ai[0] = Main.npc[(int)this.ai[3]].ai[0];
            this.ai[1] = Main.npc[(int)this.ai[3]].ai[1];
            if (this.ai[0] == 5f)
            {
                if (justHit)
                {
                    life = 0;
                    HitEffect();
                    active = false;
                    if (Main.netMode != 1)
                    {
                        NetMessage.SendData(23, -1, -1, null, whoAmI);
                    }
                    NPC obj = Main.npc[(int)this.ai[3]];
                    obj.ai[0] = 6f;
                    obj.ai[1] = 0f;
                    obj.netUpdate = true;
                }
            }
            else
            {
                flag3 = true;
                flag4 = true;
            }
        }
        else if (this.ai[0] == 5f && this.ai[1] >= 120f && this.ai[1] < 420f && justHit)
        {
            this.ai[0] = 0f;
            this.ai[1] = 0f;
            this.ai[3] += 1f;
            velocity = Vector2.Zero;
            netUpdate = true;
            List<int> list = new List<int>();
            for (int i = 0; i < 200; i++)
            {
                if (Main.npc[i].active && Main.npc[i].type == 440 && Main.npc[i].ai[3] == (float)whoAmI)
                {
                    list.Add(i);
                }
            }
            int num60 = 10;
            if (Main.expertMode)
            {
                num60 = 3;
            }
            foreach (int item in list)
            {
                NPC nPC = Main.npc[item];
                if (nPC.localAI[1] == localAI[1] && num60 > 0)
                {
                    num60--;
                    nPC.life = 0;
                    nPC.HitEffect();
                    nPC.active = false;
                    if (Main.netMode != 1)
                    {
                        NetMessage.SendData(23, -1, -1, null, item);
                    }
                }
                else if (num60 > 0)
                {
                    num60--;
                    nPC.life = 0;
                    nPC.HitEffect();
                    nPC.active = false;
                }
            }
            Main.projectile[(int)this.ai[2]].ai[1] = -1f;
            Main.projectile[(int)this.ai[2]].netUpdate = true;
        }
        Vector2 center = base.Center;
        Player player = Main.player[target];
        float num2 = 5600f;
        if (target < 0 || target == 255 || player.dead || !player.active || Vector2.Distance(player.Center, center) > num2)
        {
            TargetClosest(faceTarget: false);
            player = Main.player[target];
            netUpdate = true;
        }
        if (player.dead || !player.active || Vector2.Distance(player.Center, center) > num2)
        {
            life = 0;
            HitEffect();
            active = false;
            if (Main.netMode != 1)
            {
                NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
            }
            new List<int>().Add(whoAmI);
            for (int j = 0; j < 200; j++)
            {
                if (Main.npc[j].active && Main.npc[j].type == 440 && Main.npc[j].ai[3] == (float)whoAmI)
                {
                    Main.npc[j].life = 0;
                    Main.npc[j].HitEffect();
                    Main.npc[j].active = false;
                    if (Main.netMode != 1)
                    {
                        NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
                    }
                }
            }
        }
        float num3 = this.ai[3];
        if (localAI[0] == 0f)
        {
            SoundEngine.PlaySound(29, (int)position.X, (int)position.Y, 89);
            localAI[0] = 1f;
            alpha = 255;
            rotation = 0f;
            if (Main.netMode != 1)
            {
                this.ai[0] = -1f;
                netUpdate = true;
            }
        }
        if (this.ai[0] == -1f)
        {
            alpha -= 5;
            if (alpha < 0)
            {
                alpha = 0;
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= 420f)
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            else if (this.ai[1] > 360f)
            {
                velocity *= 0.95f;
                if (localAI[2] != 13f)
                {
                    SoundEngine.PlaySound(29, (int)position.X, (int)position.Y, 105);
                }
                localAI[2] = 13f;
            }
            else if (this.ai[1] > 300f)
            {
                velocity = -Vector2.UnitY;
                localAI[2] = 10f;
            }
            else if (this.ai[1] > 120f)
            {
                localAI[2] = 1f;
            }
            else
            {
                localAI[2] = 0f;
            }
            flag3 = true;
            flag4 = true;
        }
        Vector2 center8;
        if (this.ai[0] == 0f)
        {
            if (this.ai[1] == 0f)
            {
                TargetClosest(faceTarget: false);
            }
            localAI[2] = 10f;
            int num4 = Math.Sign(player.Center.X - center.X);
            if (num4 != 0)
            {
                direction = (spriteDirection = num4);
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= 40f && flag2)
            {
                int num5 = 0;
                if (flag)
                {
                    switch ((int)this.ai[3])
                    {
                    case 0:
                        num5 = 0;
                        break;
                    case 1:
                        num5 = 1;
                        break;
                    case 2:
                        num5 = 0;
                        break;
                    case 3:
                        num5 = 5;
                        break;
                    case 4:
                        num5 = 0;
                        break;
                    case 5:
                        num5 = 3;
                        break;
                    case 6:
                        num5 = 0;
                        break;
                    case 7:
                        num5 = 5;
                        break;
                    case 8:
                        num5 = 0;
                        break;
                    case 9:
                        num5 = 2;
                        break;
                    case 10:
                        num5 = 0;
                        break;
                    case 11:
                        num5 = 3;
                        break;
                    case 12:
                        num5 = 0;
                        break;
                    case 13:
                        num5 = 4;
                        this.ai[3] = -1f;
                        break;
                    default:
                        this.ai[3] = -1f;
                        break;
                    }
                }
                else
                {
                    switch ((int)this.ai[3])
                    {
                    case 0:
                        num5 = 0;
                        break;
                    case 1:
                        num5 = 1;
                        break;
                    case 2:
                        num5 = 0;
                        break;
                    case 3:
                        num5 = 2;
                        break;
                    case 4:
                        num5 = 0;
                        break;
                    case 5:
                        num5 = 3;
                        break;
                    case 6:
                        num5 = 0;
                        break;
                    case 7:
                        num5 = 1;
                        break;
                    case 8:
                        num5 = 0;
                        break;
                    case 9:
                        num5 = 2;
                        break;
                    case 10:
                        num5 = 0;
                        break;
                    case 11:
                        num5 = 4;
                        this.ai[3] = -1f;
                        break;
                    default:
                        this.ai[3] = -1f;
                        break;
                    }
                }
                int maxValue = 6;
                if (life < lifeMax / 3)
                {
                    maxValue = 4;
                }
                if (life < lifeMax / 4)
                {
                    maxValue = 3;
                }
                if (expertMode && flag && Main.rand.Next(maxValue) == 0 && num5 != 0 && num5 != 4 && num5 != 5 && CountNPCS(523) < 10)
                {
                    num5 = 6;
                }
                if (num5 == 0)
                {
                    center8 = player.Center + new Vector2(0f, -100f) - center;
                    float num6 = (float)Math.Ceiling(((Vector2)(ref center8)).Length() / 50f);
                    if (num6 == 0f)
                    {
                        num6 = 1f;
                    }
                    List<int> list2 = new List<int>();
                    int num7 = 0;
                    list2.Add(whoAmI);
                    for (int k = 0; k < 200; k++)
                    {
                        if (Main.npc[k].active && Main.npc[k].type == 440 && Main.npc[k].ai[3] == (float)whoAmI)
{
                            list2.Add(k);
                        }
                    }
                    bool flag5 = list2.Count % 2 == 0;
                    foreach (int item2 in list2)
                    {
                        NPC nPC2 = Main.npc[item2];
                        Vector2 center2 = nPC2.Center;
                        float num8 = (float)((num7 + flag5.ToInt() + 1) / 2) * ((float)Math.PI * 2f) * 0.4f / (float)list2.Count;
                        if (num7 % 2 == 1)
{
                            num8 *= -1f;
                        }
                        if (list2.Count == 1)
{
                            num8 = 0f;
                        }
                        Vector2 spinningpoint3 = new Vector2(0f, -1f);
                        double radians = num8;
                        center8 = default(Vector2);
                        Vector2 vector = Utils.RotatedBy(spinningpoint3, radians, center8) * new Vector2(300f, 200f);
                        Vector2 vector9 = player.Center + vector - center2;
                        nPC2.ai[0] = 1f;
                        nPC2.ai[1] = num6 * 2f;
                        nPC2.velocity = vector9 / num6;
                        if (whoAmI >= nPC2.whoAmI)
{
                            nPC2.position -= nPC2.velocity;
                        }
                        nPC2.netUpdate = true;
                        num7++;
                    }
                }
                switch (num5)
                {
                case 1:
                    this.ai[0] = 3f;
                    this.ai[1] = 0f;
                    break;
                case 2:
                    this.ai[0] = 2f;
                    this.ai[1] = 0f;
                    break;
                case 3:
                    this.ai[0] = 4f;
                    this.ai[1] = 0f;
                    break;
                case 4:
                    this.ai[0] = 5f;
                    this.ai[1] = 0f;
                    break;
                }
                if (num5 == 5)
                {
                    this.ai[0] = 7f;
                    this.ai[1] = 0f;
                }
                if (num5 == 6)
                {
                    this.ai[0] = 8f;
                    this.ai[1] = 0f;
                }
                netUpdate = true;
            }
        }
        else if (this.ai[0] == 1f)
        {
            flag3 = true;
            localAI[2] = 10f;
            if ((float)(int)this.ai[1] % 2f != 0f && this.ai[1] != 1f)
            {
                position -= velocity;
            }
            this.ai[1] -= 1f;
            if (this.ai[1] <= 0f)
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                this.ai[3] += 1f;
                velocity = Vector2.Zero;
                netUpdate = true;
            }
        }
        else if (this.ai[0] == 2f)
        {
            localAI[2] = 11f;
            Vector2 vec = Vector2.Normalize(player.Center - center);
            if (vec.HasNaNs())
            {
                ((Vector2)(ref vec))._002Ector((float)direction, 0f);
            }
            if (this.ai[1] >= 4f && flag2 && (int)(this.ai[1] - 4f) % num == 0)
            {
                if (Main.netMode != 1)
                {
                    List<int> list3 = new List<int>();
                    for (int l = 0; l < 200; l++)
                    {
                        if (Main.npc[l].active && Main.npc[l].type == 440 && Main.npc[l].ai[3] == (float)whoAmI)
{
                            list3.Add(l);
                        }
                    }
                    foreach (int item3 in list3)
                    {
                        NPC nPC3 = Main.npc[item3];
                        Vector2 center3 = nPC3.Center;
                        int num9 = Math.Sign(player.Center.X - center3.X);
                        if (num9 != 0)
{
                            nPC3.direction = (nPC3.spriteDirection = num9);
                        }
                        if (Main.netMode != 1)
{
                            vec = Vector2.Normalize(player.Center - center3 + player.velocity * 20f);
                            if (vec.HasNaNs())
{
                                vec = new Vector2((float)direction, 0f);
                            }
                            Vector2 vector10 = center3 + new Vector2((float)(direction * 30), 12f);
                            for (int m = 0; m < 1; m++)
{
                                Vector2 spinninpoint = vec * (6f + (float)Main.rand.NextDouble() * 4f);
                                spinninpoint = spinninpoint.RotatedByRandom(0.5235987901687622);
                                Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector10.X, vector10.Y, spinninpoint.X, spinninpoint.Y, 468, 18, 0f, Main.myPlayer);
                            }
                        }
                    }
                }
                if (Main.netMode != 1)
                {
                    vec = Vector2.Normalize(player.Center - center + player.velocity * 20f);
                    if (vec.HasNaNs())
                    {
                        ((Vector2)(ref vec))._002Ector((float)direction, 0f);
                    }
                    Vector2 vector11 = base.Center + new Vector2((float)(direction * 30), 12f);
                    for (int n = 0; n < 1; n++)
                    {
                        Vector2 vector12 = vec * 4f;
                        Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector11.X, vector11.Y, vector12.X, vector12.Y, 464, attackDamage_ForProjectiles, 0f, Main.myPlayer, 0f, 1f);
                    }
                }
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= (float)(4 + num))
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                this.ai[3] += 1f;
                velocity = Vector2.Zero;
                netUpdate = true;
            }
        }
        else if (this.ai[0] == 3f)
        {
            localAI[2] = 11f;
            Vector2 vec2 = Vector2.Normalize(player.Center - center);
            if (vec2.HasNaNs())
            {
                ((Vector2)(ref vec2))._002Ector((float)direction, 0f);
            }
            if (this.ai[1] >= 4f && flag2 && (int)(this.ai[1] - 4f) % num12 == 0)
            {
                if ((int)(this.ai[1] - 4f) / num12 == 2)
                {
                    List<int> list4 = new List<int>();
                    for (int num10 = 0; num10 < 200; num10++)
                    {
                        if (Main.npc[num10].active && Main.npc[num10].type == 440 && Main.npc[num10].ai[3] == (float)whoAmI)
{
                            list4.Add(num10);
                        }
                    }
                    if (Main.netMode != 1)
                    {
                        foreach (int item4 in list4)
{
                            NPC nPC4 = Main.npc[item4];
                            Vector2 center4 = nPC4.Center;
                            int num11 = Math.Sign(player.Center.X - center4.X);
                            if (num11 != 0)
{
                                nPC4.direction = (nPC4.spriteDirection = num11);
                            }
                            if (Main.netMode != 1)
{
                                vec2 = Vector2.Normalize(player.Center - center4 + player.velocity * 20f);
                                if (vec2.HasNaNs())
{
                                    vec2 = new Vector2((float)direction, 0f);
                                }
                                Vector2 vector13 = center4 + new Vector2((float)(direction * 30), 12f);
                                for (int num13 = 0; num13 < 1; num13++)
{
                                    Vector2 spinninpoint2 = vec2 * (6f + (float)Main.rand.NextDouble() * 4f);
                                    spinninpoint2 = spinninpoint2.RotatedByRandom(0.5235987901687622);
                                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector13.X, vector13.Y, spinninpoint2.X, spinninpoint2.Y, 468, 18, 0f, Main.myPlayer);
                                }
                            }
                        }
                    }
                }
                int num14 = Math.Sign(player.Center.X - center.X);
                if (num14 != 0)
                {
                    direction = (spriteDirection = num14);
                }
                if (Main.netMode != 1)
                {
                    vec2 = Vector2.Normalize(player.Center - center + player.velocity * 20f);
                    if (vec2.HasNaNs())
                    {
                        ((Vector2)(ref vec2))._002Ector((float)direction, 0f);
                    }
                    Vector2 vector14 = base.Center + new Vector2((float)(direction * 30), 12f);
                    for (int num15 = 0; num15 < 1; num15++)
                    {
                        Vector2 spinninpoint3 = vec2 * (6f + (float)Main.rand.NextDouble() * 4f);
                        spinninpoint3 = spinninpoint3.RotatedByRandom(0.5235987901687622);
                        Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector14.X, vector14.Y, spinninpoint3.X, spinninpoint3.Y, 467, attackDamage_ForProjectiles2, 0f, Main.myPlayer);
                    }
                }
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= (float)(4 + num12 * num23))
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                this.ai[3] += 1f;
                velocity = Vector2.Zero;
                netUpdate = true;
            }
        }
        else if (this.ai[0] == 4f)
        {
            if (flag2)
            {
                localAI[2] = 12f;
            }
            else
            {
                localAI[2] = 11f;
            }
            if (this.ai[1] == 20f && flag2 && Main.netMode != 1)
            {
                List<int> list5 = new List<int>();
                for (int num16 = 0; num16 < 200; num16++)
                {
                    if (Main.npc[num16].active && Main.npc[num16].type == 440 && Main.npc[num16].ai[3] == (float)whoAmI)
                    {
                        list5.Add(num16);
                    }
                }
                foreach (int item5 in list5)
                {
                    NPC nPC5 = Main.npc[item5];
                    Vector2 center5 = nPC5.Center;
                    int num17 = Math.Sign(player.Center.X - center5.X);
                    if (num17 != 0)
                    {
                        nPC5.direction = (nPC5.spriteDirection = num17);
                    }
                    if (Main.netMode != 1)
                    {
                        Vector2 vector15 = Vector2.Normalize(player.Center - center5 + player.velocity * 20f);
                        if (vector15.HasNaNs())
{
                            ((Vector2)(ref vector15))._002Ector((float)direction, 0f);
                        }
                        Vector2 vector16 = center5 + new Vector2((float)(direction * 30), 12f);
                        for (int num18 = 0; num18 < 1; num18++)
{
                            Vector2 spinninpoint4 = vector15 * (6f + (float)Main.rand.NextDouble() * 4f);
                            spinninpoint4 = spinninpoint4.RotatedByRandom(0.5235987901687622);
                            Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector16.X, vector16.Y, spinninpoint4.X, spinninpoint4.Y, 468, 18, 0f, Main.myPlayer);
                        }
                    }
                }
                if ((int)(this.ai[1] - 20f) % num34 == 0)
                {
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y - 100f, 0f, 0f, 465, attackDamage_ForProjectiles3, 0f, Main.myPlayer);
                }
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= (float)(20 + num34))
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                this.ai[3] += 1f;
                velocity = Vector2.Zero;
                netUpdate = true;
            }
        }
        else if (this.ai[0] == 5f)
        {
            localAI[2] = 10f;
            if (Vector2.Normalize(player.Center - center).HasNaNs())
            {
                new Vector2((float)direction, 0f);
            }
            if (this.ai[1] >= 0f && this.ai[1] < 30f)
            {
                flag3 = true;
                flag4 = true;
                float num19 = (this.ai[1] - 0f) / 30f;
                alpha = (int)(num19 * 255f);
            }
            else if (this.ai[1] >= 30f && this.ai[1] < 90f)
            {
                if (this.ai[1] == 30f && Main.netMode != 1 && flag2)
                {
                    localAI[1] += 1f;
                    Vector2 spinningpoint = default(Vector2);
                    ((Vector2)(ref spinningpoint))._002Ector(180f, 0f);
                    List<int> list6 = new List<int>();
                    for (int num20 = 0; num20 < 200; num20++)
                    {
                        if (Main.npc[num20].active && Main.npc[num20].type == 440 && Main.npc[num20].ai[3] == (float)whoAmI)
{
                            list6.Add(num20);
                        }
                    }
                    int num21 = 6 - list6.Count;
                    if (num21 > 2)
                    {
                        num21 = 2;
                    }
                    int num22 = list6.Count + num21 + 1;
                    float[] array = new float[num22];
                    for (int num24 = 0; num24 < array.Length; num24++)
                    {
                        int num61 = num24;
                        Vector2 center9 = base.Center;
                        Vector2 spinningpoint4 = spinningpoint;
                        double radians2 = (float)num24 * ((float)Math.PI * 2f) / (float)num22 - (float)Math.PI / 2f;
                        center8 = default(Vector2);
                        array[num61] = Vector2.Distance(center9 + spinningpoint4.RotatedBy(radians2, center8), player.Center);
                    }
                    int num25 = 0;
                    for (int num26 = 1; num26 < array.Length; num26++)
                    {
                        if (array[num25] > array[num26])
{
                            num25 = num26;
                        }
                    }
                    num25 = ((num25 >= num22 / 2) ? (num25 - num22 / 2) : (num25 + num22 / 2));
                    int num27 = num21;
                    for (int num28 = 0; num28 < array.Length; num28++)
                    {
                        if (num25 != num28)
{
                            Vector2 center10 = base.Center;
                            Vector2 spinningpoint5 = spinningpoint;
                            double radians3 = (float)num28 * ((float)Math.PI * 2f) / (float)num22 - (float)Math.PI / 2f;
                            center8 = default(Vector2);
                            Vector2 center6 = center10 + spinningpoint5.RotatedBy(radians3, center8);
                            if (num27-- > 0)
{
                                int num29 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)center6.X, (int)center6.Y + height / 2, 440, whoAmI);
                                Main.npc[num29].ai[3] = whoAmI;
                                Main.npc[num29].netUpdate = true;
                                Main.npc[num29].localAI[1] = localAI[1];
                            }
                            else
{
                                int num30 = list6[-num27 - 1];
                                Main.npc[num30].Center = center6;
                                NetMessage.SendData(23, -1, -1, null, num30);
                            }
                        }
                    }
                    this.ai[2] = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, 0f, 0f, 490, 0, 0f, Main.myPlayer, 0f, whoAmI);
                    Vector2 center11 = base.Center;
                    Vector2 spinningpoint6 = spinningpoint;
                    double radians4 = (float)num25 * ((float)Math.PI * 2f) / (float)num22 - (float)Math.PI / 2f;
                    center8 = default(Vector2);
                    base.Center = center11 + spinningpoint6.RotatedBy(radians4, center8);
                    netUpdate = true;
                    list6.Clear();
                }
                flag3 = true;
                flag4 = true;
                alpha = 255;
                if (flag2)
                {
                    Vector2 vector2 = Main.projectile[(int)this.ai[2]].Center;
                    vector2 -= base.Center;
                    if (vector2 == Vector2.Zero)
                    {
                        vector2 = -Vector2.UnitY;
                    }
                    ((Vector2)(ref vector2)).Normalize();
                    if (Math.Abs(vector2.Y) < 0.77f)
                    {
                        localAI[2] = 11f;
                    }
                    else if (vector2.Y < 0f)
                    {
                        localAI[2] = 12f;
                    }
                    else
                    {
                        localAI[2] = 10f;
                    }
                    int num31 = Math.Sign(vector2.X);
                    if (num31 != 0)
                    {
                        direction = (spriteDirection = num31);
                    }
                }
                else
                {
                    Vector2 vector3 = Main.projectile[(int)Main.npc[(int)this.ai[3]].ai[2]].Center;
                    vector3 -= base.Center;
                    if (vector3 == Vector2.Zero)
                    {
                        vector3 = -Vector2.UnitY;
                    }
                    ((Vector2)(ref vector3)).Normalize();
                    if (Math.Abs(vector3.Y) < 0.77f)
                    {
                        localAI[2] = 11f;
                    }
                    else if (vector3.Y < 0f)
                    {
                        localAI[2] = 12f;
                    }
                    else
                    {
                        localAI[2] = 10f;
                    }
                    int num32 = Math.Sign(vector3.X);
                    if (num32 != 0)
                    {
                        direction = (spriteDirection = num32);
                    }
                }
            }
            else if (this.ai[1] >= 90f && this.ai[1] < 120f)
            {
                flag3 = true;
                flag4 = true;
                float num33 = (this.ai[1] - 90f) / 30f;
                alpha = 255 - (int)(num33 * 255f);
            }
            else if (this.ai[1] >= 120f && this.ai[1] < 420f)
            {
                flag4 = true;
                alpha = 0;
                if (flag2)
                {
                    Vector2 vector4 = Main.projectile[(int)this.ai[2]].Center;
                    vector4 -= base.Center;
                    if (vector4 == Vector2.Zero)
                    {
                        vector4 = -Vector2.UnitY;
                    }
                    ((Vector2)(ref vector4)).Normalize();
                    if (Math.Abs(vector4.Y) < 0.77f)
                    {
                        localAI[2] = 11f;
                    }
                    else if (vector4.Y < 0f)
                    {
                        localAI[2] = 12f;
                    }
                    else
                    {
                        localAI[2] = 10f;
                    }
                    int num35 = Math.Sign(vector4.X);
                    if (num35 != 0)
                    {
                        direction = (spriteDirection = num35);
                    }
                }
                else
                {
                    Vector2 vector5 = Main.projectile[(int)Main.npc[(int)this.ai[3]].ai[2]].Center;
                    vector5 -= base.Center;
                    if (vector5 == Vector2.Zero)
                    {
                        vector5 = -Vector2.UnitY;
                    }
                    ((Vector2)(ref vector5)).Normalize();
                    if (Math.Abs(vector5.Y) < 0.77f)
                    {
                        localAI[2] = 11f;
                    }
                    else if (vector5.Y < 0f)
                    {
                        localAI[2] = 12f;
                    }
                    else
                    {
                        localAI[2] = 10f;
                    }
                    int num36 = Math.Sign(vector5.X);
                    if (num36 != 0)
                    {
                        direction = (spriteDirection = num36);
                    }
                }
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= 420f)
            {
                flag4 = true;
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                this.ai[3] += 1f;
                velocity = Vector2.Zero;
                netUpdate = true;
            }
        }
        else if (this.ai[0] == 6f)
        {
            localAI[2] = 13f;
            this.ai[1] += 1f;
            if (this.ai[1] >= 120f)
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                this.ai[3] += 1f;
                velocity = Vector2.Zero;
                netUpdate = true;
            }
        }
        else if (this.ai[0] == 7f)
        {
            localAI[2] = 11f;
            Vector2 vec3 = Vector2.Normalize(player.Center - center);
            if (vec3.HasNaNs())
            {
                ((Vector2)(ref vec3))._002Ector((float)direction, 0f);
            }
            if (this.ai[1] >= 4f && flag2 && (int)(this.ai[1] - 4f) % num45 == 0)
            {
                if ((int)(this.ai[1] - 4f) / num45 == 2)
                {
                    List<int> list7 = new List<int>();
                    for (int num37 = 0; num37 < 200; num37++)
                    {
                        if (Main.npc[num37].active && Main.npc[num37].type == 440 && Main.npc[num37].ai[3] == (float)whoAmI)
{
                            list7.Add(num37);
                        }
                    }
                    foreach (int item6 in list7)
                    {
                        NPC nPC6 = Main.npc[item6];
                        Vector2 center7 = nPC6.Center;
                        int num38 = Math.Sign(player.Center.X - center7.X);
                        if (num38 != 0)
{
                            nPC6.direction = (nPC6.spriteDirection = num38);
                        }
                        if (Main.netMode != 1)
{
                            vec3 = Vector2.Normalize(player.Center - center7 + player.velocity * 20f);
                            if (vec3.HasNaNs())
{
                                vec3 = new Vector2((float)direction, 0f);
                            }
                            Vector2 vector6 = center7 + new Vector2((float)(direction * 30), 12f);
                            for (int num39 = 0; (float)num39 < 5f; num39++)
{
                                Vector2 spinninpoint5 = vec3 * (6f + (float)Main.rand.NextDouble() * 4f);
                                spinninpoint5 = spinninpoint5.RotatedByRandom(1.2566370964050293);
                                Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector6.X, vector6.Y, spinninpoint5.X, spinninpoint5.Y, 468, 18, 0f, Main.myPlayer);
                            }
                        }
                    }
                }
                int num40 = Math.Sign(player.Center.X - center.X);
                if (num40 != 0)
                {
                    direction = (spriteDirection = num40);
                }
                if (Main.netMode != 1)
                {
                    vec3 = Vector2.Normalize(player.Center - center + player.velocity * 20f);
                    if (vec3.HasNaNs())
                    {
                        ((Vector2)(ref vec3))._002Ector((float)direction, 0f);
                    }
                    Vector2 vector7 = base.Center + new Vector2((float)(direction * 30), 12f);
                    float num41 = 8f;
                    float num42 = (float)Math.PI * 2f / 25f;
                    for (int num43 = 0; (float)num43 < 5f; num43++)
                    {
                        Vector2 spinningpoint2 = vec3 * num41;
                        Vector2 spinningpoint7 = spinningpoint2;
                        double radians5 = num42 * (float)num43 - ((float)Math.PI * 2f / 5f - num42) / 2f;
                        center8 = default(Vector2);
                        spinningpoint2 = spinningpoint7.RotatedBy(radians5, center8);
                        float ai = (Main.rand.NextFloat() - 0.5f) * 0.3f * ((float)Math.PI * 2f) / 60f;
                        int num44 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)vector7.X, (int)vector7.Y + 7, 522, 0, 0f, ai, spinningpoint2.X, spinningpoint2.Y);
                        Main.npc[num44].velocity = spinningpoint2;
                        Main.npc[num44].netUpdate = true;
                    }
                }
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= (float)(4 + num45 * num56))
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                this.ai[3] += 1f;
                velocity = Vector2.Zero;
                netUpdate = true;
            }
        }
        else if (this.ai[0] == 8f)
        {
            localAI[2] = 13f;
            if (this.ai[1] >= 4f && flag2 && (int)(this.ai[1] - 4f) % num58 == 0)
            {
                List<int> list8 = new List<int>();
                for (int num46 = 0; num46 < 200; num46++)
                {
                    if (Main.npc[num46].active && Main.npc[num46].type == 440 && Main.npc[num46].ai[3] == (float)whoAmI)
                    {
                        list8.Add(num46);
                    }
                }
                int num47 = list8.Count + 1;
                if (num47 > 3)
                {
                    num47 = 3;
                }
                int num48 = Math.Sign(player.Center.X - center.X);
                if (num48 != 0)
                {
                    direction = (spriteDirection = num48);
                }
                if (Main.netMode != 1)
                {
                    for (int num49 = 0; num49 < num47; num49++)
                    {
                        Point point = base.Center.ToTileCoordinates();
                        Point point2 = Main.player[target].Center.ToTileCoordinates();
                        Vector2 vector8 = Main.player[target].Center - base.Center;
                        int num50 = 20;
                        int num51 = 3;
                        int num52 = 7;
                        int num53 = 2;
                        int num54 = 0;
                        bool flag6 = false;
                        if (((Vector2)(ref vector8)).Length() > 2000f)
{
                            flag6 = true;
                        }
                        while (!flag6 && num54 < 100)
{
                            num54++;
                            int num55 = Main.rand.Next(point2.X - num50, point2.X + num50 + 1);
                            int num57 = Main.rand.Next(point2.Y - num50, point2.Y + num50 + 1);
                            if ((num57 < point2.Y - num52 || num57 > point2.Y + num52 || num55 < point2.X - num52 || num55 > point2.X + num52) && (num57 < point.Y - num51 || num57 > point.Y + num51 || num55 < point.X - num51 || num55 > point.X + num51) && !Main.tile[num55, num57].nactive())
{
                                bool flag7 = true;
                                if (flag7 && Collision.SolidTiles(num55 - num53, num55 + num53, num57 - num53, num57 + num53))
{
                                    flag7 = false;
                                }
                                if (flag7)
{
                                    NewNPC(GetSpawnSourceForNPCFromNPCAI(), num55 * 16 + 8, num57 * 16 + 8, 523, 0, whoAmI);
                                    flag6 = true;
                                    break;
                                }
                            }
                        }
                    }
                }
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= (float)(4 + num58 * num59))
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                this.ai[3] += 1f;
                velocity = Vector2.Zero;
                netUpdate = true;
            }
        }
        if (!flag2)
        {
            this.ai[3] = num3;
        }
        dontTakeDamage = flag3;
        chaseable = !flag4;
    }
References Terraria.Entity.active, Terraria.NPC.ai, Terraria.NPC.alpha, Terraria.Entity.Center, Terraria.NPC.chaseable, Terraria.NPC.CountNPCS(), Terraria.Player.dead, Terraria.NPC.defDefense, Terraria.NPC.defense, Terraria.Entity.direction, Terraria.NPC.dontTakeDamage, Terraria.Main.expertMode, Terraria.NPC.GetAttackDamage_ForProjectiles(), Terraria.Main.getGoodWorld, Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.Entity.height, Terraria.NPC.HitEffect(), Terraria.NPC.justHit, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.Main.npc, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Utils.RotatedBy(), Terraria.NPC.rotation, Terraria.NetMessage.SendData(), Terraria.Collision.SolidTiles(), Terraria.NPC.spriteDirection, Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Main.tile, Terraria.NPC.type, Terraria.Entity.velocity, and Terraria.Entity.whoAmI.
Referenced by Terraria.NPC.VanillaAI_Inner().