TModLoader: Terraria.NPC.AI_117_BloodNautilus
AI_117_BloodNautilus()
void Terraria.NPC.AI_117_BloodNautilus () inline private
Definition at line 48795 of file NPC.cs.
    {
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0102: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0181: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        //IL_0198: Unknown result type (might be due to invalid IL or missing references)
        //IL_024e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0258: Unknown result type (might be due to invalid IL or missing references)
        //IL_025d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0264: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0500: Unknown result type (might be due to invalid IL or missing references)
        //IL_0503: Unknown result type (might be due to invalid IL or missing references)
        //IL_0508: Unknown result type (might be due to invalid IL or missing references)
        //IL_0660: Unknown result type (might be due to invalid IL or missing references)
        //IL_066c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b29: Unknown result type (might be due to invalid IL or missing references)
        //IL_11be: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0531: Unknown result type (might be due to invalid IL or missing references)
        //IL_053d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0517: Unknown result type (might be due to invalid IL or missing references)
        //IL_0519: Unknown result type (might be due to invalid IL or missing references)
        //IL_051f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0524: Unknown result type (might be due to invalid IL or missing references)
        //IL_0527: Unknown result type (might be due to invalid IL or missing references)
        //IL_0682: Unknown result type (might be due to invalid IL or missing references)
        //IL_0689: Unknown result type (might be due to invalid IL or missing references)
        //IL_068e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b46: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0420: Unknown result type (might be due to invalid IL or missing references)
        //IL_0553: Unknown result type (might be due to invalid IL or missing references)
        //IL_055a: Unknown result type (might be due to invalid IL or missing references)
        //IL_055f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1203: Unknown result type (might be due to invalid IL or missing references)
        //IL_1209: Unknown result type (might be due to invalid IL or missing references)
        //IL_120e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1213: Unknown result type (might be due to invalid IL or missing references)
        //IL_1256: Unknown result type (might be due to invalid IL or missing references)
        //IL_125b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1262: Unknown result type (might be due to invalid IL or missing references)
        //IL_1267: Unknown result type (might be due to invalid IL or missing references)
        //IL_126d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1272: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_12e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_12e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1371: Unknown result type (might be due to invalid IL or missing references)
        //IL_1377: Unknown result type (might be due to invalid IL or missing references)
        //IL_137c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1381: Unknown result type (might be due to invalid IL or missing references)
        //IL_1301: Unknown result type (might be due to invalid IL or missing references)
        //IL_130b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1310: Unknown result type (might be due to invalid IL or missing references)
        //IL_1326: Unknown result type (might be due to invalid IL or missing references)
        //IL_1337: Unknown result type (might be due to invalid IL or missing references)
        //IL_134b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1350: Unknown result type (might be due to invalid IL or missing references)
        //IL_1355: Unknown result type (might be due to invalid IL or missing references)
        //IL_135b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1365: Unknown result type (might be due to invalid IL or missing references)
        //IL_136a: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02da: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0308: Unknown result type (might be due to invalid IL or missing references)
        //IL_030d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0317: Unknown result type (might be due to invalid IL or missing references)
        //IL_0321: Unknown result type (might be due to invalid IL or missing references)
        //IL_033d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_0345: Unknown result type (might be due to invalid IL or missing references)
        //IL_034b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0350: Unknown result type (might be due to invalid IL or missing references)
        //IL_0355: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0361: Unknown result type (might be due to invalid IL or missing references)
        //IL_0363: Unknown result type (might be due to invalid IL or missing references)
        //IL_0365: Unknown result type (might be due to invalid IL or missing references)
        //IL_036d: Unknown result type (might be due to invalid IL or missing references)
        //IL_037a: Unknown result type (might be due to invalid IL or missing references)
        //IL_038b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0391: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bfd: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0901: Unknown result type (might be due to invalid IL or missing references)
        //IL_0906: Unknown result type (might be due to invalid IL or missing references)
        //IL_092e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0935: Unknown result type (might be due to invalid IL or missing references)
        //IL_0741: Unknown result type (might be due to invalid IL or missing references)
        //IL_074b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0750: Unknown result type (might be due to invalid IL or missing references)
        //IL_076f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0775: Unknown result type (might be due to invalid IL or missing references)
        //IL_077a: Unknown result type (might be due to invalid IL or missing references)
        //IL_077f: Unknown result type (might be due to invalid IL or missing references)
        //IL_078e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0790: Unknown result type (might be due to invalid IL or missing references)
        //IL_0797: Unknown result type (might be due to invalid IL or missing references)
        //IL_079c: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0801: Unknown result type (might be due to invalid IL or missing references)
        //IL_0806: Unknown result type (might be due to invalid IL or missing references)
        //IL_0817: Unknown result type (might be due to invalid IL or missing references)
        //IL_081c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0829: Unknown result type (might be due to invalid IL or missing references)
        //IL_082b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0832: Unknown result type (might be due to invalid IL or missing references)
        //IL_0837: Unknown result type (might be due to invalid IL or missing references)
        //IL_0841: Unknown result type (might be due to invalid IL or missing references)
        //IL_0846: Unknown result type (might be due to invalid IL or missing references)
        //IL_085d: Unknown result type (might be due to invalid IL or missing references)
        //IL_087e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0883: Unknown result type (might be due to invalid IL or missing references)
        //IL_0894: Unknown result type (might be due to invalid IL or missing references)
        //IL_0899: Unknown result type (might be due to invalid IL or missing references)
        //IL_089e: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_072b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d63: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d73: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c25: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c53: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c79: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c94: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cbf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ccb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cda: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d38: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d54: Unknown result type (might be due to invalid IL or missing references)
        //IL_0947: Unknown result type (might be due to invalid IL or missing references)
        //IL_094e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0954: Unknown result type (might be due to invalid IL or missing references)
        //IL_095b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0960: Unknown result type (might be due to invalid IL or missing references)
        //IL_096a: Unknown result type (might be due to invalid IL or missing references)
        //IL_096f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0974: Unknown result type (might be due to invalid IL or missing references)
        //IL_0645: Unknown result type (might be due to invalid IL or missing references)
        //IL_0626: Unknown result type (might be due to invalid IL or missing references)
        //IL_1178: Unknown result type (might be due to invalid IL or missing references)
        //IL_117e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1183: Unknown result type (might be due to invalid IL or missing references)
        //IL_1188: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f54: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f59: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f60: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f65: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0981: Unknown result type (might be due to invalid IL or missing references)
        //IL_0983: Unknown result type (might be due to invalid IL or missing references)
        //IL_098a: Unknown result type (might be due to invalid IL or missing references)
        //IL_098f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0999: Unknown result type (might be due to invalid IL or missing references)
        //IL_099e: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_09de: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a06: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a12: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a17: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a21: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a54: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a84: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0abe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ade: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dfe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e03: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e12: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e41: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e52: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e86: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e90: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e95: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ead: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0edd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0efd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f14: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f19: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f21: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f26: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f79: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f80: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f85: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f94: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fbe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fde: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1001: Unknown result type (might be due to invalid IL or missing references)
        //IL_1008: Unknown result type (might be due to invalid IL or missing references)
        //IL_100d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1012: Unknown result type (might be due to invalid IL or missing references)
        //IL_1017: Unknown result type (might be due to invalid IL or missing references)
        //IL_1019: Unknown result type (might be due to invalid IL or missing references)
        //IL_1020: Unknown result type (might be due to invalid IL or missing references)
        //IL_1025: Unknown result type (might be due to invalid IL or missing references)
        //IL_102f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1034: Unknown result type (might be due to invalid IL or missing references)
        //IL_104a: Unknown result type (might be due to invalid IL or missing references)
        //IL_105f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1064: Unknown result type (might be due to invalid IL or missing references)
        //IL_1075: Unknown result type (might be due to invalid IL or missing references)
        //IL_107a: Unknown result type (might be due to invalid IL or missing references)
        //IL_107f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1096: Unknown result type (might be due to invalid IL or missing references)
        //IL_109b: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_10af: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_10e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_10f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_110c: Unknown result type (might be due to invalid IL or missing references)
        //IL_111d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1122: Unknown result type (might be due to invalid IL or missing references)
        //IL_1127: Unknown result type (might be due to invalid IL or missing references)
        //IL_112f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1131: Unknown result type (might be due to invalid IL or missing references)
        //IL_1138: Unknown result type (might be due to invalid IL or missing references)
        //IL_113d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1142: Unknown result type (might be due to invalid IL or missing references)
        float moveSpeed = 0.15f;
        float num = 7.5f;
        float num12 = 60f;
        float num14 = 90f;
        float num15 = 180f;
        float num16 = 90f;
        float num17 = 90f;
        int num18 = 3;
        float num19 = 180f;
        bool flag = false;
        if (localAI[0] == 0f)
        {
            localAI[0] = 1f;
            alpha = 255;
            if (Main.netMode != 1)
            {
                ai[0] = -1f;
                netUpdate = true;
            }
        }
        if (ai[0] != -1f && Main.rand.Next(4) == 0)
        {
            position += netOffset;
            Dust dust = Dust.NewDustDirect(position + new Vector2(5f), width - 10, height - 10, 5);
            dust.velocity *= 0.5f;
            if (dust.velocity.Y < 0f)
            {
                dust.velocity.Y *= -1f;
            }
            dust.alpha = 120;
            dust.scale = 1f + Main.rand.NextFloat() * 0.4f;
            dust.velocity += velocity * 0.3f;
            position -= netOffset;
        }
        if (target == 255)
        {
            TargetClosest();
            ai[2] = direction;
        }
        if (Main.player[target].dead || Vector2.Distance(Main.player[target].Center, base.Center) > 2000f)
        {
            TargetClosest();
        }
        NPCAimedTarget nPCAimedTarget = GetTargetData();
        if (Main.dayTime || !Main.bloodMoon)
        {
            nPCAimedTarget = default(NPCAimedTarget);
        }
        int num20 = -1;
        Vector2 mouthPosition6 = default(Vector2);
        switch ((int)ai[0])
        {
        case -1:
        {
            velocity *= 0.98f;
            int num9 = Math.Sign(nPCAimedTarget.Center.X - base.Center.X);
            if (num9 != 0)
            {
                direction = num9;
                spriteDirection = -direction;
            }
            if (localAI[1] == 0f && alpha < 100)
            {
                localAI[1] = 1f;
                int num10 = 36;
                for (int l = 0; l < num10; l++)
                {
                    position += netOffset;
                    Vector2 spinningpoint = Vector2.Normalize(velocity) * new Vector2((float)width / 2f, (float)height) * 0.75f * 0.5f;
                    double radians = (float)(l - (num10 / 2 - 1)) * ((float)Math.PI * 2f) / (float)num10;
                    mouthPosition6 = default(Vector2);
                    Vector2 val = spinningpoint.RotatedBy(radians, mouthPosition6) + base.Center;
                    Vector2 vector3 = val - base.Center;
                    int num11 = Dust.NewDust(val + vector3, 0, 0, 5, vector3.X * 2f, vector3.Y * 2f, 100, default(Color), 1.4f);
                    Main.dust[num11].noGravity = true;
                    Main.dust[num11].velocity = Vector2.Normalize(vector3) * 3f;
                    position -= netOffset;
                }
            }
            if (ai[2] > 5f)
            {
                velocity.Y = -2.5f;
                alpha -= 10;
                if (Collision.SolidCollision(position, width, height))
                {
                    alpha += 15;
                    if (alpha > 150)
                    {
                        alpha = 150;
                    }
                }
                if (alpha < 0)
                {
                    alpha = 0;
                }
            }
            ai[2] += 1f;
            if (ai[2] >= 50f)
            {
                ai[0] = 0f;
                ai[1] = 0f;
                ai[2] = 0f;
                ai[3] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 0:
        {
            Vector2 destination = nPCAimedTarget.Center + new Vector2((0f - ai[2]) * 300f, -200f);
            if (base.Center.Distance(destination) > 50f)
            {
                Vector2 desiredVelocity = DirectionTo(destination) * num;
                SimpleFlyMovement(desiredVelocity, moveSpeed);
            }
            direction = ((base.Center.X < nPCAimedTarget.Center.X) ? 1 : (-1));
            float num7 = base.Center.DirectionTo(nPCAimedTarget.Center).ToRotation() - 0.47123894f * (float)spriteDirection;
            if (spriteDirection == -1)
            {
                num7 += (float)Math.PI;
            }
            if (spriteDirection != direction)
            {
                spriteDirection = direction;
                rotation = 0f - rotation;
                num7 = 0f - num7;
            }
            rotation = rotation.AngleTowards(num7, 0.02f);
            ai[1] += 1f;
            if (ai[1] > num12)
            {
                num20 = 1;
                int num8 = (int)ai[3];
                if (num8 % 7 == 3)
                {
                    num20 = 3;
                }
                else if (num8 % 2 == 0)
                {
                    SoundEngine.PlaySound(in SoundID.Item170, base.Center);
                    num20 = 2;
                }
                else
                {
                    SoundEngine.PlaySound(in SoundID.Item170, base.Center);
                    num20 = 1;
                }
            }
            break;
        }
        case 1:
        {
            direction = ((!(base.Center.X < nPCAimedTarget.Center.X)) ? 1 : (-1));
            float num13 = base.Center.DirectionFrom(nPCAimedTarget.Center).ToRotation() - 0.47123894f * (float)spriteDirection;
            if (spriteDirection == -1)
            {
                num13 += (float)Math.PI;
            }
            bool flag2 = ai[1] < num14;
            if (spriteDirection != direction && flag2)
            {
                spriteDirection = direction;
                rotation = 0f - rotation;
                num13 = 0f - num13;
            }
            if (ai[1] < num14)
            {
                if (ai[1] == num14 - 1f)
                {
                    SoundEngine.PlaySound(in SoundID.Item172, base.Center);
                }
                flag = true;
                velocity *= 0.95f;
                rotation = rotation.AngleLerp(num13, 0.02f);
                position += netOffset;
                BloodNautilus_GetMouthPositionAndRotation(out var mouthPosition4, out var mouthDirection4);
                Dust dust5 = Dust.NewDustDirect(mouthPosition4 + mouthDirection4 * 60f - new Vector2(40f), 80, 80, 16, 0f, 0f, 150, Color.Transparent, 0.6f);
                dust5.fadeIn = 1f;
                dust5.velocity = dust5.position.DirectionTo(mouthPosition4 + Main.rand.NextVector2Circular(15f, 15f)) * ((Vector2)(ref dust5.velocity)).Length();
                dust5.noGravity = true;
                dust5 = Dust.NewDustDirect(mouthPosition4 + mouthDirection4 * 100f - new Vector2(30f), 60, 60, 16, 0f, 0f, 100, Color.Transparent, 0.9f);
                dust5.fadeIn = 1.5f;
                dust5.velocity = dust5.position.DirectionTo(mouthPosition4 + Main.rand.NextVector2Circular(15f, 15f)) * (((Vector2)(ref dust5.velocity)).Length() + 5f);
                dust5.noGravity = true;
                position -= netOffset;
            }
            else if (ai[1] < num14 + num15)
            {
                position += netOffset;
                rotation = rotation.AngleLerp(num13, 0.05f);
                BloodNautilus_GetMouthPositionAndRotation(out var mouthPosition5, out var mouthDirection5);
                if (base.Center.Distance(nPCAimedTarget.Center) > 150f)
                {
                    velocity = mouthDirection5 * -16f + base.Center.DirectionTo(nPCAimedTarget.Center) * 1.5f;
                }
                for (int m = 0; m < 4; m++)
                {
                    Dust dust6 = Dust.NewDustDirect(mouthPosition5 + mouthDirection5 * 60f - new Vector2(15f), 30, 30, 5, 0f, 0f, 0, Color.Transparent, 1.5f);
                    dust6.velocity = dust6.position.DirectionFrom(mouthPosition5 + Main.rand.NextVector2Circular(5f, 5f)) * ((Vector2)(ref dust6.velocity)).Length();
                    Dust dust12 = dust6;
                    dust12.position -= mouthDirection5 * 60f;
                    dust6 = Dust.NewDustDirect(mouthPosition5 + mouthDirection5 * 100f - new Vector2(20f), 40, 40, 5, 0f, 0f, 100, Color.Transparent, 1.5f);
                    dust6.velocity = dust6.position.DirectionFrom(mouthPosition5 + Main.rand.NextVector2Circular(10f, 10f)) * (((Vector2)(ref dust6.velocity)).Length() + 5f);
                    Dust dust13 = dust6;
                    dust13.position -= mouthDirection5 * 100f;
                }
                position -= netOffset;
            }
            ai[1] += 1f;
            if (ai[1] >= num14 + num15)
            {
                num20 = 0;
            }
            break;
        }
        case 2:
        {
            direction = ((base.Center.X < nPCAimedTarget.Center.X) ? 1 : (-1));
            float num4 = base.Center.DirectionTo(nPCAimedTarget.Center).ToRotation() - 0.47123894f * (float)spriteDirection;
            if (spriteDirection == -1)
            {
                num4 += (float)Math.PI;
            }
            if (spriteDirection != direction)
            {
                spriteDirection = direction;
                rotation = 0f - rotation;
                num4 = 0f - num4;
            }
            rotation = rotation.AngleLerp(num4, 0.2f);
            if (ai[1] < num16)
            {
                position += netOffset;
                velocity *= 0.95f;
                BloodNautilus_GetMouthPositionAndRotation(out var mouthPosition2, out var mouthDirection2);
                if (Main.rand.Next(4) != 0)
                {
                    Dust dust2 = Dust.NewDustDirect(mouthPosition2 + mouthDirection2 * 60f - new Vector2(60f), 120, 120, 16, 0f, 0f, 150, Color.Transparent, 0.6f);
                    dust2.fadeIn = 1f;
                    dust2.velocity = dust2.position.DirectionTo(mouthPosition2 + Main.rand.NextVector2Circular(15f, 15f)) * (((Vector2)(ref dust2.velocity)).Length() + 3f);
                    dust2.noGravity = true;
                    dust2 = Dust.NewDustDirect(mouthPosition2 + mouthDirection2 * 100f - new Vector2(80f), 160, 160, 16, 0f, 0f, 100, Color.Transparent, 0.9f);
                    dust2.fadeIn = 1.5f;
                    dust2.velocity = dust2.position.DirectionTo(mouthPosition2 + Main.rand.NextVector2Circular(15f, 15f)) * (((Vector2)(ref dust2.velocity)).Length() + 5f);
                    dust2.noGravity = true;
                }
                position -= netOffset;
            }
            else if (ai[1] < num16 + num17)
            {
                position += netOffset;
                velocity *= 0.9f;
                float num5 = (ai[1] - num16) % (num17 / (float)num18);
                BloodNautilus_GetMouthPositionAndRotation(out var mouthPosition3, out var mouthDirection3);
                if (num5 < num17 / (float)num18 * 0.8f)
                {
                    for (int i = 0; i < 5; i++)
                    {
                        Dust dust3 = Dust.NewDustDirect(mouthPosition3 + mouthDirection3 * 50f - new Vector2(15f), 30, 30, 5, 0f, 0f, 0, Color.Transparent, 1.5f);
                        dust3.velocity = dust3.position.DirectionFrom(mouthPosition3 + Main.rand.NextVector2Circular(5f, 5f)) * ((Vector2)(ref dust3.velocity)).Length();
                        Dust dust8 = dust3;
                        dust8.position -= mouthDirection3 * 60f;
                        dust3 = Dust.NewDustDirect(mouthPosition3 + mouthDirection3 * 90f - new Vector2(20f), 40, 40, 5, 0f, 0f, 100, Color.Transparent, 1.5f);
                        dust3.velocity = dust3.position.DirectionFrom(mouthPosition3 + Main.rand.NextVector2Circular(10f, 10f)) * (((Vector2)(ref dust3.velocity)).Length() + 5f);
                        Dust dust9 = dust3;
                        dust9.position -= mouthDirection3 * 100f;
                    }
                }
                if ((int)num5 == 0)
                {
                    velocity += mouthDirection3 * -8f;
                    for (int j = 0; j < 20; j++)
                    {
                        Dust dust4 = Dust.NewDustDirect(mouthPosition3 + mouthDirection3 * 60f - new Vector2(15f), 30, 30, 5, 0f, 0f, 0, Color.Transparent, 1.5f);
                        dust4.velocity = dust4.position.DirectionFrom(mouthPosition3 + Main.rand.NextVector2Circular(5f, 5f)) * ((Vector2)(ref dust4.velocity)).Length();
                        Dust dust10 = dust4;
                        dust10.position -= mouthDirection3 * 60f;
                        dust4 = Dust.NewDustDirect(mouthPosition3 + mouthDirection3 * 100f - new Vector2(20f), 40, 40, 5, 0f, 0f, 100, Color.Transparent, 1.5f);
                        dust4.velocity = dust4.position.DirectionFrom(mouthPosition3 + Main.rand.NextVector2Circular(10f, 10f)) * (((Vector2)(ref dust4.velocity)).Length() + 5f);
                        Dust dust11 = dust4;
                        dust11.position -= mouthDirection3 * 100f;
                    }
                    if (Main.netMode != 1)
                    {
                        int num6 = Main.rand.Next(5, 11);
                        Vector2 vector = mouthDirection3 * 10f;
                        int attackDamage_ForProjectiles = GetAttackDamage_ForProjectiles(30f, 25f);
                        for (int k = 0; k < num6; k++)
{
                            Vector2 vector2 = vector + Main.rand.NextVector2Square(-6f, 6f);
                            Projectile.NewProjectile(GetSpawnSource_ForProjectile(), mouthPosition3 - mouthDirection3 * 5f, vector2, 814, attackDamage_ForProjectiles, 0f, Main.myPlayer);
                        }
                    }
                }
                position -= netOffset;
            }
            ai[1] += 1f;
            if (ai[1] >= num16 + num17)
            {
                num20 = 0;
            }
            break;
        }
        case 3:
        {
            direction = ((base.Center.X < nPCAimedTarget.Center.X) ? 1 : (-1));
            float targetAngle = 0f;
            spriteDirection = direction;
            if (ai[1] < num19)
            {
                position += netOffset;
                float num2 = MathHelper.Clamp(1f - ai[1] / num19 * 1.5f, 0f, 1f);
                ((Vector2)(ref mouthPosition6))._002Ector(0f, num2 * -1.5f);
                velocity = Vector2.Lerp(velocity, mouthPosition6, 0.03f);
                velocity = Vector2.Zero;
                rotation = rotation.AngleLerp(targetAngle, 0.02f);
                BloodNautilus_GetMouthPositionAndRotation(out mouthPosition6, out var _);
                float t = ai[1] / num19;
                float num3 = Utils.GetLerpValue(0f, 0.5f, t) * Utils.GetLerpValue(1f, 0.5f, t);
                Lighting.AddLight(base.Center, new Vector3(1f, 0.5f, 0.5f) * num3);
                if (Main.rand.Next(3) != 0)
                {
                    Dust dust7 = Dust.NewDustDirect(base.Center - new Vector2(6f), 12, 12, 5, 0f, 0f, 60, Color.Transparent, 1.4f);
                    dust7.position += new Vector2((float)(spriteDirection * 12), 12f);
                    dust7.velocity *= 0.1f;
                }
                position -= netOffset;
            }
            if (ai[1] == 10f || ai[1] == 20f || ai[1] == 30f)
            {
                BloodNautilus_CallForHelp();
            }
            ai[1] += 1f;
            if (ai[1] >= num19)
            {
                num20 = 0;
            }
            break;
        }
        }
        if (num20 != -1)
        {
            ai[0] = num20;
            ai[1] = 0f;
            ai[2] = 0f;
            netUpdate = true;
            TargetClosest();
            if (num20 == 0)
            {
                ai[2] = direction;
            }
            else
            {
                ai[3] += 1f;
            }
        }
        reflectsProjectiles = flag;
    }
References Terraria.Lighting.AddLight(), Terraria.NPC.ai, Terraria.NPC.alpha, Terraria.Main.bloodMoon, Terraria.NPC.BloodNautilus_CallForHelp(), Terraria.NPC.BloodNautilus_GetMouthPositionAndRotation(), Terraria.Entity.Center, Terraria.Main.dayTime, Terraria.Player.dead, Terraria.Entity.direction, Terraria.Entity.DirectionTo(), Terraria.Main.dust, Terraria.NPC.GetAttackDamage_ForProjectiles(), Terraria.Utils.GetLerpValue(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetTargetData(), Terraria.Entity.height, Terraria.ID.SoundID.Item170, Terraria.ID.SoundID.Item172, Terraria.NPC.localAI, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netOffset, Terraria.NPC.netUpdate, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.reflectsProjectiles, Terraria.NPC.rotation, Terraria.NPC.SimpleFlyMovement(), Terraria.Collision.SolidCollision(), Terraria.NPC.spriteDirection, Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Dust.velocity, Terraria.Entity.velocity, and Terraria.Entity.width.
Referenced by Terraria.NPC.VanillaAI_Inner().