TModLoader: Terraria.NPC.AI_123_Deerclops_MakeSpikesBothSides
AI_123_Deerclops_MakeSpikesBothSides()
void Terraria.NPC.AI_123_Deerclops_MakeSpikesBothSides (int AISLOT_PhaseCounter, NPCAimedTarget targetData) inline private
    {
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode == 1)
        {
            return;
        }
        int num = 56;
        if (!(ai[AISLOT_PhaseCounter] < (float)num))
        {
            Point sourceTileCoords = base.Bottom.ToTileCoordinates();
            int num2 = 15;
            int num3 = 1;
            int num7 = (int)ai[AISLOT_PhaseCounter] - num;
            if (num7 == 0)
            {
                PunchCameraModifier modifier = new PunchCameraModifier(base.Center, new Vector2(0f, 1f), 20f, 6f, 30, 1000f, "Deerclops");
                Main.instance.CameraModifiers.Add(modifier);
            }
            int num4 = 2;
            int num5 = num7 / num4 * num4;
            int num6 = num5 + num4;
            if (num7 % num4 != 0)
            {
                num6 = num5;
            }
            for (int i = num5; i >= 0 && i < num6 && i < num2; i++)
            {
                int xOffset = i * num3;
                AI_123_Deerclops_TryMakingSpike(ref sourceTileCoords, direction, num2, -i, xOffset);
                AI_123_Deerclops_TryMakingSpike(ref sourceTileCoords, -direction, num2, -i, xOffset);
            }
        }
    }
References Terraria.Graphics.CameraModifiers.CameraModifierStack.Add(), Terraria.NPC.ai, Terraria.NPC.AI_123_Deerclops_TryMakingSpike(), Terraria.Main.CameraModifiers, Terraria.Entity.direction, Terraria.Main.instance, and Terraria.Main.netMode.
Referenced by Terraria.NPC.AI_123_Deerclops().