TModLoader: Terraria.NPC.AI_047_GolemFist
AI_047_GolemFist()
void Terraria.NPC.AI_047_GolemFist () inline private
    {
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_0420: Unknown result type (might be due to invalid IL or missing references)
        //IL_0432: Unknown result type (might be due to invalid IL or missing references)
        //IL_0437: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0465: Unknown result type (might be due to invalid IL or missing references)
        //IL_046a: Unknown result type (might be due to invalid IL or missing references)
        //IL_046c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0473: Unknown result type (might be due to invalid IL or missing references)
        //IL_047d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0482: Unknown result type (might be due to invalid IL or missing references)
        //IL_0493: Unknown result type (might be due to invalid IL or missing references)
        //IL_0498: Unknown result type (might be due to invalid IL or missing references)
        //IL_049b: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_081c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0826: Unknown result type (might be due to invalid IL or missing references)
        //IL_082b: Unknown result type (might be due to invalid IL or missing references)
        //IL_083c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0841: Unknown result type (might be due to invalid IL or missing references)
        //IL_0844: Unknown result type (might be due to invalid IL or missing references)
        //IL_0849: Unknown result type (might be due to invalid IL or missing references)
        //IL_084b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0850: Unknown result type (might be due to invalid IL or missing references)
        //IL_0852: Unknown result type (might be due to invalid IL or missing references)
        //IL_085c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0864: Unknown result type (might be due to invalid IL or missing references)
        //IL_0919: Unknown result type (might be due to invalid IL or missing references)
        //IL_0924: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0608: Unknown result type (might be due to invalid IL or missing references)
        //IL_0612: Unknown result type (might be due to invalid IL or missing references)
        //IL_0628: Unknown result type (might be due to invalid IL or missing references)
        //IL_0632: Unknown result type (might be due to invalid IL or missing references)
        //IL_094a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0955: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0301: Unknown result type (might be due to invalid IL or missing references)
        //IL_031b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0337: Unknown result type (might be due to invalid IL or missing references)
        float num = GetMyBalance();
        if (Main.getGoodWorld)
        {
            num += 3f;
        }
        if ((!Main.player[target].ZoneLihzhardTemple && !Main.player[target].ZoneJungle) || (double)Main.player[target].Center.Y < Main.worldSurface * 16.0)
        {
            num *= 2f;
        }
        if (golemBoss < 0)
        {
            StrikeNPCNoInteraction(9999, 0f, 0);
            return;
        }
        if (alpha > 0)
        {
            alpha -= 10;
            if (alpha < 0)
            {
                alpha = 0;
            }
            ai[1] = 0f;
        }
        Player player = Main.player[target];
        NPC nPC = Main.npc[golemBoss];
        Vector2 vector = nPC.Center + nPC.velocity + new Vector2(0f, -9f * scale);
        vector.X += (float)((type == 247) ? (-84) : 78) * scale;
        Vector2 vector2 = vector - base.Center;
        float num6 = ((Vector2)(ref vector2)).Length();
        if (ai[0] == 0f)
        {
            noTileCollide = true;
            float num7 = 14f;
            if (life < lifeMax / 2)
            {
                num7 += 3f;
            }
            if (life < lifeMax / 4)
            {
                num7 += 3f;
            }
            if (Main.npc[golemBoss].life < Main.npc[golemBoss].lifeMax)
            {
                num7 += 8f;
            }
            num7 *= (num + 3f) / 4f;
            if (num7 > 32f)
            {
                num7 = 32f;
            }
            float x = vector2.X;
            float y = vector2.Y;
            float num8 = num6;
            if (num8 < 12f + num7)
            {
                rotation = 0f;
                velocity.X = x;
                velocity.Y = y;
                float num9 = num;
                ai[1] += num9;
                if (life < lifeMax / 2)
                {
                    ai[1] += num9;
                }
                if (life < lifeMax / 4)
                {
                    ai[1] += num9;
                }
                if (Main.npc[golemBoss].life < Main.npc[golemBoss].lifeMax)
                {
                    ai[1] += 10f * num9;
                }
                if (ai[1] >= 60f)
                {
                    TargetClosest();
                    if ((type == 247 && base.Center.X + 100f > Main.player[target].Center.X) || (type == 248 && base.Center.X - 100f < Main.player[target].Center.X))
                    {
                        ai[1] = 0f;
                        ai[0] = 1f;
                    }
                    else
                    {
                        ai[1] = 0f;
                    }
                }
            }
            else
            {
                num8 = num7 / num8;
                velocity.X = x * num8;
                velocity.Y = y * num8;
                rotation = (float)Math.Atan2(0f - velocity.Y, 0f - velocity.X);
                if (type == 247)
                {
                    rotation = (float)Math.Atan2(velocity.Y, velocity.X);
                }
            }
        }
        else if (ai[0] == 1f)
        {
            ai[1] += 1f;
            base.Center = vector;
            rotation = 0f;
            velocity = Vector2.Zero;
            if (ai[1] <= 15f)
            {
                for (int i = 0; i < 1; i++)
                {
                    Vector2 vector3 = Main.rand.NextVector2Circular(80f, 80f);
                    Vector2 vector4 = vector3 * -1f * 0.05f;
                    Vector2 vector5 = Main.rand.NextVector2Circular(20f, 20f);
                    Dust dust = Dust.NewDustPerfect(base.Center + vector4 + vector3 + vector5, 228, vector4);
                    dust.fadeIn = 1.5f;
                    dust.scale = 0.5f;
                    if (Main.getGoodWorld)
                    {
                        dust.noLight = true;
                    }
                    dust.noGravity = true;
                }
            }
            if (ai[1] >= 30f)
            {
                noTileCollide = true;
                collideX = false;
                collideY = false;
                ai[0] = 2f;
                ai[1] = 0f;
                float num10 = 12f;
                if (life < lifeMax / 2)
                {
                    num10 += 4f;
                }
                if (life < lifeMax / 4)
                {
                    num10 += 4f;
                }
                if (Main.npc[golemBoss].life < Main.npc[golemBoss].lifeMax)
                {
                    num10 += 10f;
                }
                num10 *= (num + 3f) / 4f;
                if (num10 > 48f)
                {
                    num10 = 48f;
                }
                Vector2 vector6 = default(Vector2);
                ((Vector2)(ref vector6))._002Ector(base.Center.X, base.Center.Y);
                float num11 = Main.player[target].Center.X - vector6.X;
                float num12 = Main.player[target].Center.Y - vector6.Y;
                float num13 = (float)Math.Sqrt(num11 * num11 + num12 * num12);
                num13 = num10 / num13;
                velocity.X = num11 * num13;
                velocity.Y = num12 * num13;
                rotation = (float)Math.Atan2(velocity.Y, velocity.X);
                if (type == 247)
                {
                    rotation = (float)Math.Atan2(0f - velocity.Y, 0f - velocity.X);
                }
            }
        }
        else if (ai[0] == 2f)
        {
            if (Main.netMode != 1 && Main.getGoodWorld)
            {
                for (int j = (int)(position.X / 16f) - 1; (float)j < (position.X + (float)width) / 16f + 1f; j++)
                {
                    for (int k = (int)(position.Y / 16f) - 1; (float)k < (position.Y + (float)width) / 16f + 1f; k++)
                    {
                        if (Main.tile[j, k].type == 4)
{
                            Main.tile[j, k].active(active: false);
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, j, k);
                            }
                        }
                    }
                }
            }
            ai[1] += 1f;
            if (ai[1] == 1f)
            {
                SoundEngine.PlaySound(in SoundID.Item14, position);
            }
            if (Main.rand.Next(2) == 0)
            {
                Vector2 vector7 = velocity * 0.5f;
                Vector2 vector8 = Main.rand.NextVector2Circular(20f, 20f);
                Dust.NewDustPerfect(base.Center + vector7 + vector8, 306, vector7, 0, Main.OurFavoriteColor).scale = 2f;
            }
            if (Math.Abs(velocity.X) > Math.Abs(velocity.Y))
            {
                if (velocity.X > 0f && base.Center.X > player.Center.X)
                {
                    noTileCollide = false;
                }
                if (velocity.X < 0f && base.Center.X < player.Center.X)
                {
                    noTileCollide = false;
                }
            }
            else
            {
                if (velocity.Y > 0f && base.Center.Y > player.Center.Y)
                {
                    noTileCollide = false;
                }
                if (velocity.Y < 0f && base.Center.Y < player.Center.Y)
                {
                    noTileCollide = false;
                }
            }
            if (num6 > 700f || collideX || collideY)
            {
                noTileCollide = true;
                ai[0] = 0f;
            }
        }
        else
        {
            if (ai[0] != 3f)
            {
                return;
            }
            noTileCollide = true;
            float num2 = 0.4f;
            Vector2 vector9 = default(Vector2);
            ((Vector2)(ref vector9))._002Ector(base.Center.X, base.Center.Y);
            float num3 = Main.player[target].Center.X - vector9.X;
            float num4 = Main.player[target].Center.Y - vector9.Y;
            float num5 = (float)Math.Sqrt(num3 * num3 + num4 * num4);
            num5 = 12f / num5;
            num3 *= num5;
            num4 *= num5;
            if (velocity.X < num3)
            {
                velocity.X += num2;
                if (velocity.X < 0f && num3 > 0f)
                {
                    velocity.X += num2 * 2f;
                }
            }
            else if (velocity.X > num3)
            {
                velocity.X -= num2;
                if (velocity.X > 0f && num3 < 0f)
                {
                    velocity.X -= num2 * 2f;
                }
            }
            if (velocity.Y < num4)
            {
                velocity.Y += num2;
                if (velocity.Y < 0f && num4 > 0f)
                {
                    velocity.Y += num2 * 2f;
                }
            }
            else if (velocity.Y > num4)
            {
                velocity.Y -= num2;
                if (velocity.Y > 0f && num4 < 0f)
                {
                    velocity.Y -= num2 * 2f;
                }
            }
            rotation = (float)Math.Atan2(velocity.Y, velocity.X);
            if (type == 247)
            {
                rotation = (float)Math.Atan2(0f - velocity.Y, 0f - velocity.X);
            }
        }
    }
References Terraria.Entity.active, Terraria.NPC.ai, Terraria.NPC.alpha, Terraria.Entity.Center, Terraria.NPC.collideX, Terraria.NPC.collideY, Terraria.Main.getGoodWorld, Terraria.NPC.GetMyBalance(), Terraria.NPC.golemBoss, Terraria.ID.SoundID.Item14, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.Main.netMode, Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.NPC.noTileCollide, Terraria.Main.npc, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.rotation, Terraria.Dust.scale, Terraria.NPC.scale, Terraria.NetMessage.SendTileSquare(), Terraria.NPC.StrikeNPCNoInteraction(), Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Main.tile, Terraria.NPC.type, Terraria.Entity.velocity, Terraria.Entity.width, Terraria.Main.worldSurface, Terraria.Player.ZoneJungle, and Terraria.Player.ZoneLihzhardTemple.
Referenced by Terraria.NPC.VanillaAI_Inner().