TModLoader: Terraria.NPC.AI_107_ImprovedWalkers
AI_107_ImprovedWalkers()
void Terraria.NPC.AI_107_ImprovedWalkers () inline private
Definition at line 67051 of file NPC.cs.
    {
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_19eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_19f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_19fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a00: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a06: Unknown result type (might be due to invalid IL or missing references)
        //IL_1721: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_0410: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f23: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f28: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2436: Unknown result type (might be due to invalid IL or missing references)
        //IL_142f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1450: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ee4: Unknown result type (might be due to invalid IL or missing references)
        //IL_19c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_25e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_25f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bf7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bfc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1afb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b00: Unknown result type (might be due to invalid IL or missing references)
        //IL_14db: Unknown result type (might be due to invalid IL or missing references)
        //IL_14bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0509: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0591: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2613: Unknown result type (might be due to invalid IL or missing references)
        //IL_2619: Unknown result type (might be due to invalid IL or missing references)
        //IL_261e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2623: Unknown result type (might be due to invalid IL or missing references)
        //IL_262c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2630: Unknown result type (might be due to invalid IL or missing references)
        //IL_2635: Unknown result type (might be due to invalid IL or missing references)
        //IL_2639: Unknown result type (might be due to invalid IL or missing references)
        //IL_263e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2642: Unknown result type (might be due to invalid IL or missing references)
        //IL_2647: Unknown result type (might be due to invalid IL or missing references)
        //IL_249a: Unknown result type (might be due to invalid IL or missing references)
        //IL_249f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0825: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fbf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0926: Unknown result type (might be due to invalid IL or missing references)
        //IL_092b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0948: Unknown result type (might be due to invalid IL or missing references)
        //IL_0953: Unknown result type (might be due to invalid IL or missing references)
        //IL_0958: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f93: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fa1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fab: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fee: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ff4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ffe: Unknown result type (might be due to invalid IL or missing references)
        //IL_2003: Unknown result type (might be due to invalid IL or missing references)
        //IL_2008: Unknown result type (might be due to invalid IL or missing references)
        //IL_084c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1009: Unknown result type (might be due to invalid IL or missing references)
        //IL_102f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2148: Unknown result type (might be due to invalid IL or missing references)
        //IL_214e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2153: Unknown result type (might be due to invalid IL or missing references)
        //IL_2158: Unknown result type (might be due to invalid IL or missing references)
        //IL_210a: Unknown result type (might be due to invalid IL or missing references)
        //IL_212a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2130: Unknown result type (might be due to invalid IL or missing references)
        //IL_213c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2141: Unknown result type (might be due to invalid IL or missing references)
        //IL_2697: Unknown result type (might be due to invalid IL or missing references)
        //IL_269b: Unknown result type (might be due to invalid IL or missing references)
        //IL_26a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c34: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c48: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c81: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c87: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cdb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ce2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cf1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cf6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d28: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b38: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b67: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bb7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bcd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1523: Unknown result type (might be due to invalid IL or missing references)
        //IL_1538: Unknown result type (might be due to invalid IL or missing references)
        //IL_1542: Unknown result type (might be due to invalid IL or missing references)
        //IL_155d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1562: Unknown result type (might be due to invalid IL or missing references)
        //IL_1567: Unknown result type (might be due to invalid IL or missing references)
        //IL_1569: Unknown result type (might be due to invalid IL or missing references)
        //IL_156b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1570: Unknown result type (might be due to invalid IL or missing references)
        //IL_1572: Unknown result type (might be due to invalid IL or missing references)
        //IL_1579: Unknown result type (might be due to invalid IL or missing references)
        //IL_11b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_11cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1112: Unknown result type (might be due to invalid IL or missing references)
        //IL_10f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0997: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09be: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09da: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a18: Unknown result type (might be due to invalid IL or missing references)
        //IL_204f: Unknown result type (might be due to invalid IL or missing references)
        //IL_206e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2074: Unknown result type (might be due to invalid IL or missing references)
        //IL_2082: Unknown result type (might be due to invalid IL or missing references)
        //IL_208c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2091: Unknown result type (might be due to invalid IL or missing references)
        //IL_20cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_20d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_20df: Unknown result type (might be due to invalid IL or missing references)
        //IL_20e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_20e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_26c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_26c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_26c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_26ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_26aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_26af: Unknown result type (might be due to invalid IL or missing references)
        //IL_26b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_26b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1588: Unknown result type (might be due to invalid IL or missing references)
        //IL_1596: Unknown result type (might be due to invalid IL or missing references)
        //IL_15b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_15cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_15de: Unknown result type (might be due to invalid IL or missing references)
        //IL_15e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_121b: Unknown result type (might be due to invalid IL or missing references)
        //IL_125a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1264: Unknown result type (might be due to invalid IL or missing references)
        //IL_1269: Unknown result type (might be due to invalid IL or missing references)
        //IL_2192: Unknown result type (might be due to invalid IL or missing references)
        //IL_161d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1623: Unknown result type (might be due to invalid IL or missing references)
        //IL_1628: Unknown result type (might be due to invalid IL or missing references)
        //IL_162d: Unknown result type (might be due to invalid IL or missing references)
        //IL_12c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_12d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_12de: Unknown result type (might be due to invalid IL or missing references)
        //IL_1164: Unknown result type (might be due to invalid IL or missing references)
        //IL_1146: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a49: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0acc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b12: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b38: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b54: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b92: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0baa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0baf: Unknown result type (might be due to invalid IL or missing references)
        //IL_21a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_21b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_28db: Unknown result type (might be due to invalid IL or missing references)
        //IL_28e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_28e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_28e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_28eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_28f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_28f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_28f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_2902: Unknown result type (might be due to invalid IL or missing references)
        //IL_2913: Unknown result type (might be due to invalid IL or missing references)
        //IL_2915: Unknown result type (might be due to invalid IL or missing references)
        //IL_291a: Unknown result type (might be due to invalid IL or missing references)
        //IL_291f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2926: Unknown result type (might be due to invalid IL or missing references)
        //IL_292b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2782: Unknown result type (might be due to invalid IL or missing references)
        //IL_2795: Unknown result type (might be due to invalid IL or missing references)
        //IL_24f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2521: Unknown result type (might be due to invalid IL or missing references)
        //IL_2527: Unknown result type (might be due to invalid IL or missing references)
        //IL_254b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2558: Unknown result type (might be due to invalid IL or missing references)
        //IL_255d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2563: Unknown result type (might be due to invalid IL or missing references)
        //IL_2569: Unknown result type (might be due to invalid IL or missing references)
        //IL_256e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2573: Unknown result type (might be due to invalid IL or missing references)
        //IL_21d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_21d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_21de: Unknown result type (might be due to invalid IL or missing references)
        //IL_21e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_21f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_21fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_2201: Unknown result type (might be due to invalid IL or missing references)
        //IL_220d: Unknown result type (might be due to invalid IL or missing references)
        //IL_27df: Unknown result type (might be due to invalid IL or missing references)
        //IL_27e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_27ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_27ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_27b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_27c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c20: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c26: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c42: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c50: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c56: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c63: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c86: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2222: Unknown result type (might be due to invalid IL or missing references)
        //IL_2935: Unknown result type (might be due to invalid IL or missing references)
        //IL_2937: Unknown result type (might be due to invalid IL or missing references)
        //IL_2939: Unknown result type (might be due to invalid IL or missing references)
        //IL_293b: Unknown result type (might be due to invalid IL or missing references)
        //IL_34c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_34c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_34ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_34d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_34d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_3426: Unknown result type (might be due to invalid IL or missing references)
        //IL_343d: Unknown result type (might be due to invalid IL or missing references)
        //IL_344c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e14: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e20: Unknown result type (might be due to invalid IL or missing references)
        //IL_2958: Unknown result type (might be due to invalid IL or missing references)
        //IL_2969: Unknown result type (might be due to invalid IL or missing references)
        //IL_296e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2973: Unknown result type (might be due to invalid IL or missing references)
        //IL_2946: Unknown result type (might be due to invalid IL or missing references)
        //IL_294a: Unknown result type (might be due to invalid IL or missing references)
        //IL_294f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2954: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d29: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d50: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d52: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d68: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ccc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2975: Unknown result type (might be due to invalid IL or missing references)
        //IL_2977: Unknown result type (might be due to invalid IL or missing references)
        //IL_297b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2980: Unknown result type (might be due to invalid IL or missing references)
        //IL_2985: Unknown result type (might be due to invalid IL or missing references)
        //IL_3540: Unknown result type (might be due to invalid IL or missing references)
        //IL_355c: Unknown result type (might be due to invalid IL or missing references)
        //IL_34fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_3500: Unknown result type (might be due to invalid IL or missing references)
        //IL_3502: Unknown result type (might be due to invalid IL or missing references)
        //IL_3507: Unknown result type (might be due to invalid IL or missing references)
        //IL_352a: Unknown result type (might be due to invalid IL or missing references)
        //IL_352c: Unknown result type (might be due to invalid IL or missing references)
        //IL_352e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3533: Unknown result type (might be due to invalid IL or missing references)
        //IL_2995: Unknown result type (might be due to invalid IL or missing references)
        //IL_2997: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dfd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e19: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f31: Unknown result type (might be due to invalid IL or missing references)
        //IL_330a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f34: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f39: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f40: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f44: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f49: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f50: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f73: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f78: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f84: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b16: Unknown result type (might be due to invalid IL or missing references)
        //IL_39db: Unknown result type (might be due to invalid IL or missing references)
        //IL_39e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_331f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3332: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b91: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b91: Unknown result type (might be due to invalid IL or missing references)
        //IL_3bd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b31: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a02: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_31c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_31d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f90: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f92: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f94: Unknown result type (might be due to invalid IL or missing references)
        //IL_3024: Unknown result type (might be due to invalid IL or missing references)
        //IL_3030: Unknown result type (might be due to invalid IL or missing references)
        //IL_31f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_31fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_3202: Unknown result type (might be due to invalid IL or missing references)
        //IL_3207: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fb1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fcc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fa3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fa8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fad: Unknown result type (might be due to invalid IL or missing references)
        //IL_3061: Unknown result type (might be due to invalid IL or missing references)
        //IL_306d: Unknown result type (might be due to invalid IL or missing references)
        //IL_304b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c10: Unknown result type (might be due to invalid IL or missing references)
        //IL_324a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3256: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fce: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fd0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fd9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fde: Unknown result type (might be due to invalid IL or missing references)
        //IL_3097: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3287: Unknown result type (might be due to invalid IL or missing references)
        //IL_3293: Unknown result type (might be due to invalid IL or missing references)
        //IL_3271: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fee: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ff0: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c49: Unknown result type (might be due to invalid IL or missing references)
        //IL_32bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_30b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2be6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c13: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c19: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c67: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c71: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c76: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c60: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_32d6: Unknown result type (might be due to invalid IL or missing references)
        bool flag = velocity.X == 0f && velocity.Y == 0f && !justHit;
        bool flag12 = false;
        bool flag23 = false;
        bool flag34 = false;
        int num = 32;
        int num12 = 15;
        float num23 = 9f;
        bool flag36 = false;
        float num32 = 40f;
        int num42 = 30;
        int num53 = 0;
        bool flag37 = false;
        bool flag38 = true;
        float num63 = 0.9f;
        bool flag39 = false;
        bool flag40 = false;
        bool flag2 = false;
        bool flag3 = false;
        bool flag4 = false;
        bool flag5 = false;
        bool flag6 = false;
        bool flag7 = true;
        int num66 = 70;
        int num67 = num66 / 2;
        float num2 = 11f;
        Vector2 vector = Vector2.Zero;
        int num3 = 1;
        int num4 = 81;
        float num5 = 700f;
        float num6 = 0f;
        float num7 = 0.1f;
        Vector2? vector7 = null;
        float num8 = 0.5f;
        int num9 = 1;
        float num10 = 1f;
        bool flag8 = false;
        float num11 = 30f;
        float num13 = 0f;
        bool flag9 = false;
        bool flag10 = true;
        bool flag11 = false;
        int num14 = 30;
        bool flag13 = false;
        bool flag14 = false;
        bool flag15 = false;
        bool flag16 = false;
        SoundStyle? style = null;
        int num15 = 0;
        bool flag17 = false;
        float num16 = 1f;
        float num17 = 0.07f;
        float num18 = 0.8f;
        float num19 = width / 2 + 6;
        bool flag18 = directionY < 0;
        bool flag19 = false;
        int num20 = 1;
        bool flag20 = false;
        float num21 = 5f;
        float num22 = 3f;
        float num24 = 8f;
        float amount = 0.05f;
        float amount2 = 0.04f;
        float amount3 = 0.1f;
        bool flag21 = false;
        float num25 = 0.025f;
        NPCAimedTarget targetData = GetTargetData();
        NPCUtils.NPCTargetingMethod nPCTargetingMethod = NPCUtils.TargetClosestCommon;
        if (NPCID.Sets.BelongsToInvasionOldOnesArmy[type])
        {
            nPCTargetingMethod = NPCUtils.TargetClosestOldOnesInvasion;
        }
        if (targetData.Type == NPCTargetType.NPC && Main.npc[TranslatedTargetIndex].type == 548 && Main.npc[TranslatedTargetIndex].dontTakeDamageFromHostiles)
        {
            nPCTargetingMethod(this, faceTarget: true, null);
            targetData = GetTargetData();
        }
        if (NPCID.Sets.FighterUsesDD2PortalAppearEffect[type])
        {
            if (!targetData.Invalid)
            {
                flag12 = !Collision.CanHit(base.Center, 0, 0, targetData.Center, 0, 0) && (direction == Math.Sign(targetData.Center.X - base.Center.X) || (noGravity && Distance(targetData.Center) > 50f && base.Center.Y > targetData.Center.Y));
            }
            flag12 &= ai[0] <= 0f;
        }
        if (flag12)
        {
            if (velocity.Y == 0f || Math.Abs(targetData.Center.Y - base.Center.Y) > 800f)
            {
                noGravity = true;
                noTileCollide = true;
            }
        }
        else
        {
            noGravity = false;
            noTileCollide = false;
        }
        bool flag22 = NPCID.Sets.FighterUsesDD2PortalAppearEffect[type];
        bool flag24 = true;
        Vector2 center2;
        switch (type)
        {
        case 576:
        case 577:
            num15 = 700;
            style = SoundID.DD2_OgreRoar;
            num19 -= 32f;
            flag36 = true;
            num53 = 60;
            num32 = 130f;
            num42 = 44;
            flag14 = DD2Event.EnemiesShouldChasePlayers;
            num63 = 0.7f;
            if (localAI[0] > 0f)
            {
                localAI[0] -= 1f;
            }
            if (ai[0] <= 0f)
            {
                float num27 = ai[1];
                float num28 = Distance(targetData.Center);
                if (localAI[3] >= 60f)
                {
                    if (num28 <= num32 + 300f && localAI[0] <= 0f)
                    {
                        ai[1] = 2f;
                    }
                    else if (num28 > num32 + 30f)
                    {
                        ai[1] = 1f;
                    }
                    else if (!(num28 > num32))
                    {
                        ai[1] = 0f;
                        if (num27 == 1f)
{
                            ai[0] = 0f;
                        }
                    }
                }
                if (num27 != ai[1])
                {
                    netUpdate = true;
                }
            }
            else if (ai[1] == 2f)
            {
                localAI[0] = 300f;
            }
            switch ((int)ai[1])
            {
            case 0:
                num42 = 44;
                if (ai[0] == 40f)
                {
                    SoundEngine.PlayTrackedSound(in SoundID.DD2_OgreAttack, base.Center);
                }
                break;
            case 2:
                num42 = 90;
                num32 = 250f;
                flag34 = true;
                num3 = GetAttackDamage_ForProjectiles(60f, 40f);
                num67 = 36;
                num = 56;
                num12 = 41;
                num23 = 13f;
                flag23 = true;
                num4 = 683;
                flag7 = false;
                ((Vector2)(ref vector))._002Ector((float)(-direction * 20), (float)(height / 2 - 1));
                if (ai[0] == 40f)
                {
                    SoundEngine.PlayTrackedSound(in SoundID.DD2_OgreGroundPound, base.Center);
                }
                break;
            case 1:
                flag23 = true;
                num42 = 90;
                num32 = 1000f;
                num53 = 240;
                num3 = GetAttackDamage_ForProjectiles(40f, 30f);
                flag7 = false;
                ((Vector2)(ref vector))._002Ector((float)(direction * 30), -70f);
                num4 = 676;
                if (ai[0] == 80f)
                {
                    SoundEngine.PlayTrackedSound(in SoundID.DD2_OgreSpit, base.Center);
                }
                break;
            }
            if (ai[0] < (float)(-num53))
            {
                ai[0] = -num53;
            }
            break;
        case 552:
        case 553:
        case 554:
            style = SoundID.DD2_GoblinScream;
            num15 = 1000;
            flag36 = true;
            flag14 = DD2Event.EnemiesShouldChasePlayers;
            if (type == 553)
            {
                num17 += 0.01f;
                num16 += 0.2f;
            }
            if (type == 554)
            {
                num17 += 0.02f;
                num16 += 0.4f;
            }
            if (!(localAI[3] >= 60f))
            {
                num17 = 0.01f + localAI[3] / 60f * 0.05f;
            }
            break;
        case 570:
        case 571:
            flag14 = DD2Event.EnemiesShouldChasePlayers;
            flag17 = true;
            flag4 = true;
            flag7 = ai[1] > 40f;
            num66 = 60;
            num67 = 40;
            if (type == 571 && ai[1] > 10f && ai[1] <= 40f && (int)ai[1] % 6 == 0)
            {
                num67 = (int)ai[1] - 1;
            }
            if (type == 570 && ai[1] > 10f && ai[1] <= 40f && (int)ai[1] % 9 == 0)
            {
                num67 = (int)ai[1] - 1;
            }
            num4 = 671;
            vector.X += 22 * direction;
            num7 = 0.15f;
            num8 = 1.5f;
            num5 = 600f;
            num2 = 13f;
            num9 = 1;
            num10 = 0f;
            if (type == 570)
            {
                num8 = 2.5f;
            }
            num3 = GetAttackDamage_ForProjectiles(35f, 25f);
            if (type == 571)
            {
                num3 = GetAttackDamage_ForProjectiles(60f, 45f);
            }
            num16 = 0.77f;
            if (ai[0] > 0f)
            {
                if (ai[1] == 40f)
                {
                    SoundEngine.PlayTrackedSound(in SoundID.DD2_DrakinShot, base.Center);
                }
                else if (ai[1] == 60f)
                {
                    SoundEngine.PlayTrackedSound(in SoundID.DD2_DrakinBreathIn, base.Center);
                }
            }
            if (!(localAI[3] >= 60f))
            {
                num5 = 1f;
                num17 = 0.01f + localAI[3] / 60f * 0.05f;
            }
            break;
        case 572:
        case 573:
            if (localAI[3] == 0f)
            {
                localAI[0] = SlotId.Invalid.ToFloat();
                localAI[1] = SlotId.Invalid.ToFloat();
            }
            flag14 = DD2Event.EnemiesShouldChasePlayers;
            if (ai[1] == 2f)
            {
                SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[0]))?.Stop();
                SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]))?.Stop();
                position = base.Center;
                width = (height = 192);
                base.Center = position;
                velocity = Vector2.Zero;
                damage = GetAttackDamage_ScaledByStrength(80f);
                alpha = 255;
                for (int k = 0; k < 4; k++)
                {
                    int num29 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                    Main.dust[num29].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * (float)width / 2f;
                }
                for (int l = 0; l < 20; l++)
                {
                    int num30 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 200, default(Color), 3.7f);
                    Main.dust[num30].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * (float)width / 2f;
                    Main.dust[num30].noGravity = true;
                    Dust obj = Main.dust[num30];
                    obj.velocity *= 3f;
                    num30 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                    Main.dust[num30].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * (float)width / 4f;
                    Dust obj2 = Main.dust[num30];
                    obj2.velocity *= 2f;
                    Main.dust[num30].noGravity = true;
                    Main.dust[num30].fadeIn = 2.5f;
                }
                for (int m = 0; m < 6; m++)
                {
                    int num31 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 0, default(Color), 2.7f);
                    Dust obj3 = Main.dust[num31];
                    Vector2 center = base.Center;
                    Vector2 spinningpoint = Vector2.UnitX.RotatedByRandom(3.1415927410125732);
                    double radians = velocity.ToRotation();
                    center2 = default(Vector2);
                    obj3.position = center + spinningpoint.RotatedBy(radians, center2) * (float)width / 2f;
                    Main.dust[num31].noGravity = true;
                    Dust obj4 = Main.dust[num31];
                    obj4.velocity *= 3f;
                }
                for (int n = 0; n < 12; n++)
                {
                    int num33 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 0, default(Color), 1.5f);
                    Dust obj5 = Main.dust[num33];
                    Vector2 center3 = base.Center;
                    Vector2 spinningpoint2 = Vector2.UnitX.RotatedByRandom(3.1415927410125732);
                    double radians2 = velocity.ToRotation();
                    center2 = default(Vector2);
                    obj5.position = center3 + spinningpoint2.RotatedBy(radians2, center2) * (float)width / 2f;
                    Main.dust[num33].noGravity = true;
                    Dust obj6 = Main.dust[num33];
                    obj6.velocity *= 3f;
                }
                for (int num34 = 0; num34 < 5; num34++)
                {
                    Vector2 val = position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f;
                    center2 = default(Vector2);
                    int num35 = Gore.NewGore(val, center2, Main.rand.Next(61, 64));
                    Main.gore[num35].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * (float)width / 2f;
                    Gore obj7 = Main.gore[num35];
                    obj7.velocity *= 0.3f;
                    Main.gore[num35].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                    Main.gore[num35].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
                }
                ai[0] += 1f;
                if (ai[0] >= 3f)
                {
                    SoundEngine.PlayTrackedSound(in SoundID.DD2_KoboldExplosion, base.Center);
                    life = 0;
                    HitEffect();
                    active = false;
                }
                return;
            }
            if (ai[0] > 0f && ai[1] == 0f && life > 0)
            {
                if (!SlotId.FromFloat(localAI[0]).IsValid)
                {
                    localAI[0] = SoundEngine.PlayTrackedSound(in SoundID.DD2_KoboldIgnite, base.Center).ToFloat();
                }
                localAI[2] += 1f;
                if (localAI[2] == 30f)
                {
                    localAI[0] = SoundEngine.PlayTrackedSound(in SoundID.DD2_KoboldIgniteLoop, base.Center).ToFloat();
                    localAI[1] = SoundEngine.PlayTrackedSound(in SoundID.DD2_KoboldScreamChargeLoop, base.Center).ToFloat();
                }
            }
            if (ai[0] > 0f && ai[1] == 1f)
            {
                ai[0] = 0f;
                ai[1] = 2f;
                netUpdate = true;
                return;
            }
            num16 = 0.88f;
            if (ai[0] == 1f)
            {
                ai[1] = 1f;
            }
            if (ai[0] == 0f && ai[1] == 1f)
            {
                ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[0]));
                if (activeSound == null)
                {
                    localAI[0] = SoundEngine.PlayTrackedSound(in SoundID.DD2_KoboldIgniteLoop, base.Center).ToFloat();
                }
                else
                {
                    activeSound.Position = base.Center;
                }
                ActiveSound activeSound2 = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
                if (activeSound2 == null)
                {
                    localAI[1] = SoundEngine.PlayTrackedSound(in SoundID.DD2_KoboldScreamChargeLoop, base.Center).ToFloat();
                }
                else
                {
                    activeSound2.Position = base.Center;
                }
            }
            if (ai[1] > 0f && ai[0] == 0f)
            {
                flag36 = true;
                num42 = 40;
                num32 = 64f;
                num17 = 0.3f;
                num16 = 4f;
                Vector2 vector8 = base.Center + new Vector2((float)(spriteDirection * 12), 0f);
                if (Main.rand.Next(6) == 0)
                {
                    Dust dust10 = Dust.NewDustDirect(vector8, 1, 1, 213, Main.rand.Next(-2, 3), Main.rand.Next(-2, 3), 100, new Color(255, 255, 255, 0));
                    dust10.noGravity = true;
                    dust10.fadeIn = dust10.scale + 1f + 0.01f * (float)Main.rand.Next(0, 51);
                    dust10.velocity *= 0.3f;
                    dust10.velocity.X += (float)(-spriteDirection) * 1.2f;
                    dust10.velocity.Y += -3.5f;
                    dust10.velocity.X += velocity.X;
                }
                if (Main.rand.Next(12) == 0)
                {
                    Dust dust11 = Dust.NewDustPerfect(vector8, 6, velocity, 100);
                    dust11.noGravity = true;
                    dust11.velocity.Y -= 1f + Main.rand.NextFloat();
                    dust11.scale = 1.1f;
                    dust11.fadeIn = 0.5f;
                    dust11.customData = this;
                }
            }
            else
            {
                flag36 = true;
                num42 = 40;
                num32 = 700f;
            }
            if (!(localAI[3] >= 60f))
            {
                num17 = 0.01f + localAI[3] / 60f * 0.05f;
            }
            break;
        case 568:
        case 569:
        {
            num42 = 110;
            num17 = 0.16f;
            num18 = 0.7f;
            num16 = 1.4f;
            flag36 = true;
            num32 = 600f;
            flag14 = DD2Event.EnemiesShouldChasePlayers;
            if (!(localAI[3] >= 60f))
            {
                num17 = 0.01f + localAI[3] / 60f * 0.05f;
            }
            if (ai[0] == 0f)
            {
                localAI[1] = SlotId.Invalid.ToFloat();
            }
            if (ai[0] != 1f)
            {
                break;
            }
            HitSound = SoundID.DD2_WitherBeastCrystalImpact;
            ai[0] += 1f;
            if (Main.rand.Next(10) == 0)
            {
                Dust dust12 = Dust.NewDustDirect(base.TopLeft, width, height, 271, 0f, -3f, 0, Color.Transparent, 0.6f);
                dust12.velocity.X /= 2f;
                dust12.noGravity = true;
                dust12.fadeIn = 1.5f;
                dust12.position.Y += 4f;
            }
            ActiveSound activeSound3 = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
            if (activeSound3 == null)
            {
                localAI[1] = SoundEngine.PlayTrackedSound(in SoundID.DD2_WitherBeastAuraPulse, base.Center).ToFloat();
            }
            else
            {
                activeSound3.Position = base.Center;
            }
            localAI[0] += 1f;
            if (localAI[0] > 60f && Main.rand.Next(10) == 0)
            {
                Vector2 vec = base.Center + (Main.rand.NextFloat() * ((float)Math.PI * 2f)).ToRotationVector2() * 400f * (0.3f + 0.7f * Main.rand.NextFloat());
                Point point = vec.ToTileCoordinates();
                if (!WorldGen.SolidTile(point.X, point.Y))
                {
                    Dust dust7 = Dust.NewDustPerfect(vec, 27, (Vector2?)new Vector2(0f, -3f), 0, new Color(255, 255, 255, 127), 1.5f);
                    dust7.velocity = DirectionTo(dust7.position) * ((Vector2)(ref dust7.velocity)).Length();
                    dust7.fadeIn = 1.5f;
                }
            }
            if (Main.netMode != 2)
            {
                Player player = Main.player[Main.myPlayer];
                if (!player.dead && player.active)
                {
                    center2 = player.Center - base.Center;
                    if (((Vector2)(ref center2)).Length() < 400f && !player.creativeGodMode)
                    {
                        player.AddBuff(195, 3, quiet: false);
                    }
                }
            }
            if (ai[1] > 0f)
            {
                ai[1] -= 1f;
            }
            if (!(ai[1] <= 0f))
            {
                break;
            }
            ai[1] = 60f;
            if (Main.netMode != 1)
            {
                int num44 = lifeMax / 20;
                if (num44 > lifeMax - life)
                {
                    num44 = lifeMax - life;
                }
                if (num44 > 0)
                {
                    life += num44;
                    HealEffect(num44);
                    netUpdate = true;
                }
            }
            break;
        }
        case 561:
        case 562:
        case 563:
        {
            bool num69 = localAI[3] >= 60f;
            if (ai[1] == 82f)
            {
                SoundEngine.PlayTrackedSound(in SoundID.DD2_JavelinThrowersAttack, base.Center);
                num15 = 7;
                style = SoundID.DD2_JavelinThrowersTaunt;
            }
            flag14 = DD2Event.EnemiesShouldChasePlayers;
            flag17 = true;
            flag4 = true;
            flag7 = ai[1] > 82f;
            num66 = 90;
            num67 = 82;
            num4 = 662;
            if (type == 563)
            {
                num4 = 685;
            }
            vector.Y -= 14f;
            num7 = 0f;
            num8 = 0.5f;
            num5 = 600f;
            num2 = 13f;
            if (!num69)
            {
                num5 = 1f;
                num17 = 0.01f + localAI[3] / 60f * 0.05f;
            }
            if (type == 561)
            {
                num16 = 0.88f;
                num8 = 0.6f;
                num3 = GetAttackDamage_ForProjectiles(15f, 10f);
                num2 = 11.5f;
                num5 -= 100f;
            }
            if (type == 562)
            {
                num16 = 0.94f;
                num8 = 0.5f;
                num3 = GetAttackDamage_ForProjectiles(30f, 20f);
                num2 = 12.2f;
                num5 -= 50f;
            }
            if (type == 563)
            {
                num16 = 1f;
                num8 = 0.4f;
                num3 = GetAttackDamage_ForProjectiles(45f, 30f);
            }
            break;
        }
        case 555:
        case 556:
        case 557:
        {
            num15 = 800;
            style = SoundID.DD2_GoblinBomberScream;
            bool num68 = localAI[3] >= 60f;
            flag14 = DD2Event.EnemiesShouldChasePlayers;
            flag17 = true;
            flag4 = true;
            flag7 = ai[1] > 18f;
            num66 = 42;
            num67 = 18;
            num4 = 681;
            num3 = 10;
            vector.Y -= 14f;
            num7 = 0.4f;
            num8 = 0.5f;
            num5 = 280f;
            num2 = 6f;
            if (!num68)
            {
                num5 = 1f;
                num17 = 0.01f + localAI[3] / 60f * 0.05f;
            }
            if (type == 555)
            {
                num16 = 0.88f;
                num8 = 0.6f;
                num3 = GetAttackDamage_ForProjectiles(20f, 15f);
            }
            if (type == 556)
            {
                num16 = 0.88f;
                num8 = 0.6f;
                num3 = GetAttackDamage_ForProjectiles(30f, 25f);
            }
            if (type == 557)
            {
                num16 = 1.12f;
                num8 = 0.4f;
                num3 = GetAttackDamage_ForProjectiles(40f, 35f);
            }
            if (ai[1] == (float)num67)
            {
                SoundEngine.PlayTrackedSound(in SoundID.DD2_GoblinBomberThrow, base.Center);
            }
            break;
        }
        case 566:
        case 567:
        {
            DelegateMethods.v3_1 = new Vector3(0.3f, 0.05f, 0.45f) * 1.5f;
            Utils.PlotTileLine(base.Top, base.Bottom, width, DelegateMethods.CastLightOpen);
            flag14 = DD2Event.EnemiesShouldChasePlayers;
            bool num70 = localAI[3] >= 120f;
            if (!num70)
            {
                num17 = 0f;
            }
            if (num70)
            {
                dontTakeDamage = false;
                break;
            }
            dontTakeDamage = true;
            velocity.X = 0f;
            flag17 = true;
            flag13 = true;
            ai[3] = 0f;
            if (localAI[3] == 0f)
            {
                alpha = 255;
            }
            localAI[3] += 1f;
            float num36 = localAI[3];
            if (num36 >= 110f)
            {
                alpha -= 26;
                if (alpha < 0)
                {
                    alpha = 0;
                }
            }
            if (num36 >= 100f)
            {
                int num37 = (int)localAI[3] / 20;
                center2 = base.Size;
                float num38 = ((Vector2)(ref center2)).Length() / 2f;
                num38 /= 20f;
                int maxValue = 5;
                for (int num39 = 0; num39 < num37 * 2; num39++)
                {
                    if (Main.rand.Next(maxValue) == 0)
                    {
                        Dust dust5 = Dust.NewDustDirect(position, width, height, 236, velocity.X * 1f);
                        dust5.scale = 1f;
                        dust5.fadeIn = 0.3f;
                        dust5.velocity = new Vector2(Main.rand.NextFloatDirection() * 1f, 0f - ((Vector2)(ref dust5.velocity)).Length()) * 1.25f * num38;
                    }
                }
            }
            else
            {
                int num40 = (int)localAI[3] / 10;
                center2 = base.Size;
                float num41 = ((Vector2)(ref center2)).Length() / 2f;
                num41 /= 20f;
                int maxValue2 = 5;
                for (int num43 = 0; (float)num43 < (float)num40 * 1.3f; num43++)
                {
                    if (Main.rand.Next(maxValue2) == 0)
                    {
                        Dust dust6 = Dust.NewDustDirect(position + new Vector2((float)(-width / 2), 8f), width + width, height, 27, velocity.X * 1f, 0f, 100);
                        dust6.scale = 1.1f;
                        dust6.fadeIn = 0.1f;
                        dust6.velocity = new Vector2(Main.rand.NextFloatDirection() * 0.1f, 0f - ((Vector2)(ref dust6.velocity)).Length()) * 1.05f * num41 * Main.rand.NextFloat();
                        dust6.velocity.Y *= Utils.GetLerpValue((float)width * 0.75f, 0f, Math.Abs(dust6.position.X - base.Center.X), clamped: true);
                    }
                }
            }
            if (num36 > 100f && (int)num36 % 4 == 0)
            {
                Gore.NewGoreDirect(base.Left, new Vector2(0f, -3f), Utils.SelectRandom<int>(Main.rand, 971, 972), 0.85f).velocity.X *= 0.8f;
            }
            break;
        }
        case 620:
        {
            flag20 = wet;
            flag24 = false;
            flag8 = true;
            num13 = 150f;
            num11 = 20f;
            bool dayTime = Main.dayTime;
            flag14 = !dayTime;
            flag17 = true;
            flag4 = true;
            flag7 = ai[1] > 40f;
            num66 = 60;
            num67 = 40;
            if (ai[1] > 10f && ai[1] <= 40f && (int)ai[1] % 5 == 0)
            {
                num67 = (int)ai[1] - 1;
            }
            num4 = 811;
            vector.X -= 4 * direction;
            vector.Y -= 20f;
            num7 = 0.15f;
            num8 = 2.5f;
            num5 = 600f;
            num2 = 13f;
            num9 = 1;
            num10 = 0f;
            num3 = GetAttackDamage_ForProjectiles(40f, 30f);
            num16 = 8f;
            num17 *= 3f;
            num18 = 0.9f;
            if (ai[0] > 0f)
            {
                if (ai[1] == 40f)
                {
                    SoundEngine.PlayTrackedSound(in SoundID.DD2_DrakinShot, base.Center);
                }
                else if (ai[1] == 60f)
                {
                    SoundEngine.PlayTrackedSound(in SoundID.DD2_DrakinBreathIn, base.Center);
                }
            }
            position += netOffset;
            if (alpha == 255)
            {
                spriteDirection = direction;
                velocity.Y = -6f;
                netUpdate = true;
                for (int i = 0; i < 35; i++)
                {
                    Dust dust8 = Dust.NewDustDirect(position, width, height, 5);
                    dust8.velocity *= 1f;
                    dust8.scale = 1f + Main.rand.NextFloat() * 0.5f;
                    dust8.fadeIn = 1.5f + Main.rand.NextFloat() * 0.5f;
                    dust8.velocity += velocity * 0.5f;
                }
            }
            alpha -= 15;
            if (alpha < 0)
            {
                alpha = 0;
            }
            if (alpha != 0)
            {
                for (int j = 0; j < 2; j++)
                {
                    Dust dust9 = Dust.NewDustDirect(position, width, height, 5);
                    dust9.velocity *= 1f;
                    dust9.scale = 1f + Main.rand.NextFloat() * 0.5f;
                    dust9.fadeIn = 1.5f + Main.rand.NextFloat() * 0.5f;
                    dust9.velocity += velocity * 0.3f;
                }
            }
            if (Main.rand.Next(3) == 0)
            {
                Dust.NewDustDirect(position, width, height, 5, 0f, 0f, 50, default(Color), 1.3f).velocity = Vector2.Zero;
            }
            position -= netOffset;
            if (dayTime)
            {
                flag4 = false;
                flag17 = false;
                flag16 = true;
            }
            else
            {
                if (velocity.Y != 0f || !((float)((Rectangle)(ref targetData.Hitbox)).Bottom < base.Top.Y) || !(Math.Abs(base.Center.X - (float)((Rectangle)(ref targetData.Hitbox)).Center.X) < (float)(width * 3)) || !Collision.CanHit(base.Hitbox.TopLeft(), base.Hitbox.Width, base.Hitbox.Height, targetData.Hitbox.TopLeft(), targetData.Hitbox.Width, targetData.Hitbox.Height))
                {
                    break;
                }
                int num26 = (int)((base.Bottom.Y - 16f - (float)((Rectangle)(ref targetData.Hitbox)).Bottom) / 16f);
                if (num26 < 27)
                {
                    if (num26 < 11)
                    {
                        velocity.Y = -11f;
                    }
                    else if (num26 < 15)
                    {
                        velocity.Y = -13f;
                    }
                    else if (num26 < 19)
                    {
                        velocity.Y = -14f;
                    }
                    else
                    {
                        velocity.Y = -15.9f;
                    }
                }
            }
            break;
        }
        }
        if (flag21)
        {
            bool flag25 = velocity.Y == 0f;
            for (int num45 = 0; num45 < 200; num45++)
            {
                if (num45 != whoAmI && Main.npc[num45].active && Main.npc[num45].type == type && Math.Abs(position.X - Main.npc[num45].position.X) + Math.Abs(position.Y - Main.npc[num45].position.Y) < (float)width)
                {
                    if (position.X < Main.npc[num45].position.X)
                    {
                        velocity.X -= num25;
                    }
                    else
                    {
                        velocity.X += num25;
                    }
                    if (position.Y < Main.npc[num45].position.Y)
                    {
                        velocity.Y -= num25;
                    }
                    else
                    {
                        velocity.Y += num25;
                    }
                }
            }
            if (flag25)
            {
                velocity.Y = 0f;
            }
        }
        if (flag22)
        {
            if (localAI[3] == 0f)
            {
                alpha = 255;
            }
            if (localAI[3] == 30f)
            {
                SoundEngine.PlayTrackedSound(in SoundID.DD2_EtherianPortalSpawnEnemy, base.Center);
            }
            if (localAI[3] < 60f)
            {
                localAI[3] += 1f;
                alpha -= 5;
                if (alpha < 0)
                {
                    alpha = 0;
                }
                int num46 = (int)localAI[3] / 10;
                center2 = base.Size;
                float num47 = ((Vector2)(ref center2)).Length() / 2f;
                num47 /= 20f;
                int maxValue3 = 5;
                if (type == 576 || type == 577)
                {
                    maxValue3 = 1;
                }
                for (int num48 = 0; num48 < num46; num48++)
                {
                    if (Main.rand.Next(maxValue3) == 0)
                    {
                        Dust dust13 = Dust.NewDustDirect(position, width, height, 27, velocity.X * 1f, 0f, 100);
                        dust13.scale = 0.55f;
                        dust13.fadeIn = 0.7f;
                        dust13.velocity *= 0.1f * num47;
                        dust13.velocity += velocity;
                    }
                }
            }
        }
        if (flag20)
        {
            noGravity = true;
            TargetClosest(faceTarget: false);
            if (collideX)
            {
                velocity.X = 0f - oldVelocity.X;
            }
            if (velocity.X != 0f)
            {
                direction = Math.Sign(direction);
            }
            if (Collision.CanHit(position, width, height, targetData.Position, targetData.Width, targetData.Height))
            {
                Vector2 value = targetData.Center - base.Center;
                ((Vector2)(ref value)).Normalize();
                value *= num21;
                velocity = Vector2.Lerp(velocity, value, amount);
                return;
            }
            float num49 = num21;
            if (velocity.Y > 0f)
            {
                num49 = num22;
            }
            if (velocity.Y < 0f)
            {
                num49 = num24;
            }
            Vector2 value2 = default(Vector2);
            ((Vector2)(ref value2))._002Ector((float)direction, -1f);
            ((Vector2)(ref value2)).Normalize();
            value2 *= num49;
            if (num49 < num21)
            {
                velocity = Vector2.Lerp(velocity, value2, amount2);
            }
            else
            {
                velocity = Vector2.Lerp(velocity, value2, amount3);
            }
            return;
        }
        bool flag26 = false;
        if ((flag4 || flag36) && ai[0] > 0f)
        {
            flag10 = false;
        }
        if (flag4 && ai[1] > 0f)
        {
            flag15 = true;
        }
        if (flag36 && ai[0] > 0f)
        {
            flag15 = true;
        }
        if (flag36)
        {
            if (ai[0] < 0f)
            {
                ai[0] += 1f;
                flag = false;
            }
            if (ai[0] == 0f && (velocity.Y == 0f || flag37) && targetData.Type != 0 && (Collision.CanHit(position, width, height, targetData.Position, targetData.Width, targetData.Height) || Collision.CanHitLine(position, width, height, targetData.Position, targetData.Width, targetData.Height)))
            {
                center2 = targetData.Center - base.Center;
                if (((Vector2)(ref center2)).Length() < num32)
                {
                    ai[0] = num42;
                    netUpdate = true;
                }
            }
            if (ai[0] > 0f)
            {
                spriteDirection = direction * num20;
                if (flag38)
                {
                    velocity.X *= num63;
                    flag17 = true;
                    flag13 = true;
                    ai[3] = 0f;
                    netUpdate = true;
                }
                ai[0] -= 1f;
                if (ai[0] == 0f)
                {
                    ai[0] = -num53;
                    netUpdate = true;
                }
            }
        }
        if (flag23 && ai[0] > 0f)
        {
            if (flag7)
            {
                nPCTargetingMethod(this, faceTarget: true, null);
                targetData = GetTargetData();
            }
            if (ai[0] == (float)num67)
            {
                Vector2 vector9 = base.Center + vector;
                Vector2 v = targetData.Center - vector9;
                v.Y -= Math.Abs(v.X) * num7;
                Vector2 vector10 = v.SafeNormalize(-Vector2.UnitY) * num2;
                for (int num50 = 0; num50 < num9; num50++)
                {
                    Vector2 vector11 = vector10;
                    Vector2 vector12 = vector9;
                    vector11 = ((!vector7.HasValue) ? (vector11 + Utils.RandomVector2(Main.rand, 0f - num8, num8)) : (vector11 + vector7.Value));
                    vector12 += vector10 * num10;
                    if (Main.netMode != 1)
                    {
                        Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector12, vector11, num4, num3, 0f, Main.myPlayer);
                    }
                }
            }
        }
        if (flag34 && ai[0] > 0f)
        {
            if (velocity.Y != 0f && ai[0] < (float)num12)
            {
                ai[0] = num12;
            }
            if (ai[0] == (float)num)
            {
                velocity.Y = 0f - num23;
            }
        }
        if (!flag9 && flag10)
        {
            if (velocity.Y == 0f && velocity.X * (float)direction < 0f)
            {
                flag11 = true;
            }
            if (position.X == oldPosition.X || ai[3] >= (float)num14 || flag11)
            {
                ai[3] += 1f;
            }
            else if (Math.Abs(velocity.X) > 0.9f && ai[3] > 0f)
            {
                ai[3] -= 1f;
            }
            if (ai[3] > (float)(num14 * 10))
            {
                ai[3] = 0f;
            }
            if (justHit && !flag24)
            {
                ai[3] = 0f;
            }
            if (((Rectangle)(ref targetData.Hitbox)).Intersects(base.Hitbox))
            {
                ai[3] = 0f;
            }
            if (ai[3] == (float)num14)
            {
                netUpdate = true;
                if (flag24)
                {
                    noGravity = true;
                    noTileCollide = true;
                    position.X += direction * width * 2;
                    int num51 = 20;
                    center2 = base.Size;
                    float num52 = ((Vector2)(ref center2)).Length() / 2f;
                    num52 /= 20f;
                    int maxValue4 = 5;
                    if (type == 576 || type == 577)
                    {
                        maxValue4 = 1;
                    }
                    for (int num54 = 0; num54 < num51; num54++)
                    {
                        if (Main.rand.Next(maxValue4) == 0)
{
                            Dust dust14 = Dust.NewDustDirect(position, width, height, 27, velocity.X * 1f, 0f, 100);
                            dust14.scale = 0.55f;
                            dust14.fadeIn = 0.7f;
                            dust14.velocity *= 3f * num52;
                            dust14.noGravity = true;
                            dust14.fadeIn = 1.5f;
                            dust14.velocity *= 3f;
                        }
                    }
                    return;
                }
            }
        }
        if (!flag13)
        {
            if (ai[3] < (float)num14 && flag14)
            {
                if (num15 > 0 && Main.rand.Next(num15) == 0 && style.HasValue)
                {
                    SoundStyle style2 = style.Value;
                    SoundEngine.PlayTrackedSound(in style2, base.Center);
                }
                bool hasValidTarget = HasValidTarget;
                nPCTargetingMethod(this, faceTarget: true, null);
                targetData = GetTargetData();
                if (hasValidTarget != HasValidTarget)
                {
                    netUpdate = true;
                }
            }
            else if (!flag15)
            {
                if (flag16)
                {
                    EncourageDespawn(10);
                }
                if (velocity.X == 0f)
                {
                    if (velocity.Y == 0f)
                    {
                        ai[2] += 1f;
                        if (ai[2] >= 2f)
{
                            direction *= -1;
                            spriteDirection = direction * num20;
                            ai[2] = 0f;
                            netUpdate = true;
                        }
                    }
                }
                else if (ai[2] != 0f)
                {
                    ai[2] = 0f;
                    netUpdate = true;
                }
                if (direction == 0)
                {
                    direction = 1;
                }
            }
        }
        if (!flag17)
        {
            if (velocity.X < 0f - num16 || velocity.X > num16)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= num18;
                }
            }
            else if ((velocity.X < num16 && direction == 1) || (velocity.X > 0f - num16 && direction == -1))
            {
                velocity.X = MathHelper.Clamp(velocity.X + num17 * (float)direction, 0f - num16, num16);
            }
        }
        if (flag4)
        {
            if (confused)
            {
                ai[0] = 0f;
            }
            else
            {
                if (ai[1] > 0f)
                {
                    ai[1] -= 1f;
                }
                if (justHit)
                {
                    ai[1] = num11;
                    ai[0] = 0f;
                }
                if (ai[0] > 0f)
                {
                    if (flag7)
                    {
                        nPCTargetingMethod(this, faceTarget: true, null);
                        targetData = GetTargetData();
                    }
                    if (ai[1] == (float)num67)
                    {
                        Vector2 vector13 = base.Center + vector;
                        Vector2 v2 = targetData.Center - vector13;
                        v2.Y -= Math.Abs(v2.X) * num7;
                        Vector2 vector14 = v2.SafeNormalize(-Vector2.UnitY) * num2;
                        for (int num55 = 0; num55 < num9; num55++)
{
                            Vector2 vector2 = vector13;
                            Vector2 vector3 = vector14;
                            vector3 = ((!vector7.HasValue) ? (vector3 + Utils.RandomVector2(Main.rand, 0f - num8, num8)) : (vector3 + vector7.Value));
                            vector2 += vector3 * num10;
                            if (Main.netMode != 1)
{
                                Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector2, vector3, num4, num3, 0f, Main.myPlayer);
                            }
                        }
                        if (Math.Abs(vector14.Y) > Math.Abs(vector14.X) * 2f)
{
                            ai[0] = ((vector14.Y > 0f) ? 1 : 5);
                        }
                        else if (Math.Abs(vector14.X) > Math.Abs(vector14.Y) * 2f)
{
                            ai[0] = 3f;
                        }
                        else
{
                            ai[0] = ((vector14.Y > 0f) ? 2 : 4);
                        }
                        if (flag8)
{
                            direction = ((vector14.X > 0f) ? 1 : (-1));
                        }
                    }
                    bool flag27 = true;
                    if ((velocity.Y != 0f && !flag6) || ai[1] <= 0f)
                    {
                        bool flag28 = false;
                        if (num13 != 0f && ai[1] <= 0f)
{
                            flag28 = true;
                        }
                        ai[0] = 0f;
                        ai[1] = (flag28 ? num13 : 0f);
                    }
                    else if (!flag5 || (!flag27 && (!flag6 || velocity.Y == 0f)))
                    {
                        velocity.X *= 0.9f;
                        spriteDirection = direction * num20;
                    }
                }
                if ((ai[0] <= 0f || flag5) && (velocity.Y == 0f || flag6) && ai[1] <= 0f && targetData.Type != 0 && Collision.CanHit(position, width, height, targetData.Position, targetData.Width, targetData.Height))
                {
                    Vector2 vector4 = targetData.Center - base.Center;
                    if (((Vector2)(ref vector4)).Length() < num5)
                    {
                        netUpdate = true;
                        velocity.X *= 0.5f;
                        ai[0] = 3f;
                        ai[1] = num66;
                        if (Math.Abs(vector4.Y) > Math.Abs(vector4.X) * 2f)
{
                            ai[0] = ((vector4.Y > 0f) ? 1 : 5);
                        }
                        else if (Math.Abs(vector4.X) > Math.Abs(vector4.Y) * 2f)
{
                            ai[0] = 3f;
                        }
                        else
{
                            ai[0] = ((vector4.Y > 0f) ? 2 : 4);
                        }
                        if (flag8)
{
                            direction = ((vector4.X > 0f) ? 1 : (-1));
                        }
                    }
                }
                if (ai[0] <= 0f || flag5)
                {
                    bool flag29 = Distance(targetData.Center) < num6;
                    if (flag29 && Collision.CanHitLine(position, width, height, targetData.Position, targetData.Width, targetData.Height))
                    {
                        ai[3] = 0f;
                    }
                    if (velocity.X < 0f - num16 || velocity.X > num16 || flag29)
                    {
                        if (velocity.Y == 0f)
{
                            velocity.X *= num18;
                        }
                    }
                    else if ((velocity.X < num16 && direction == 1) || (velocity.X > 0f - num16 && direction == -1))
                    {
                        velocity.X = MathHelper.Clamp(velocity.X + num17 * (float)direction, 0f - num16, num16);
                    }
                }
            }
        }
        if (velocity.Y == 0f)
        {
            int num56 = (int)(base.Bottom.Y + 7f) / 16;
            int num71 = (int)base.Left.X / 16;
            int num57 = (int)base.Right.X / 16;
            int num58;
            for (num58 = num71; num58 <= num57; num58++)
            {
                num58 = Utils.Clamp(num58, 0, Main.maxTilesX);
                num56 = Utils.Clamp(num56, 0, Main.maxTilesY);
                Tile tile = Main.tile[num58, num56];
                if (tile == null)
                {
                    return;
                }
                if (tile.nactive() && Main.tileSolid[tile.type])
                {
                    flag26 = true;
                    break;
                }
            }
        }
        Point point2 = base.Center.ToTileCoordinates();
        if (WorldGen.InWorld(point2.X, point2.Y, 5) && !noGravity)
        {
            GetTileCollisionParameters(out var cPosition, out var cWidth, out var cHeight);
            Vector2 vector5 = position - cPosition;
            Collision.StepUp(ref cPosition, ref velocity, cWidth, cHeight, ref stepSpeed, ref gfxOffY);
            position = cPosition + vector5;
        }
        if (flag26)
        {
            int num59 = (int)(base.Center.X + num19 * (float)direction) / 16;
            int num60 = ((int)base.Bottom.Y - 15) / 16;
            bool flag30 = position.Y + (float)height - (float)(num60 * 16) > 20f;
            Tile tileSafely = Framing.GetTileSafely(num59 + direction, num60 + 1);
            Tile tileSafely2 = Framing.GetTileSafely(num59, num60 + 1);
            Tile tileSafely3 = Framing.GetTileSafely(num59, num60);
            Tile tileSafely4 = Framing.GetTileSafely(num59, num60 - 1);
            Tile tileSafely5 = Framing.GetTileSafely(num59, num60 - 2);
            Tile tileSafely6 = Framing.GetTileSafely(num59, num60 - 3);
            if (flag39 && tileSafely4.nactive() && (TileLoader.IsClosedDoor(tileSafely4) || tileSafely4.type == 388))
            {
                ai[0] += 1f;
                ai[3] = 0f;
                if (ai[0] >= 60f)
                {
                    if (flag40)
                    {
                        ai[1] = 0f;
                    }
                    int num61 = 5;
                    if (Main.tile[num59, num60 - 1].type == 388)
                    {
                        num61 = 2;
                    }
                    velocity.X = 0.5f * (float)(-direction);
                    ai[1] += num61;
                    bool flag31 = false;
                    if (ai[1] >= 10f)
                    {
                        flag31 = true;
                        ai[1] = 10f;
                    }
                    if (flag2)
                    {
                        flag31 = true;
                    }
                    WorldGen.KillTile(num59, num60 - 1, fail: true);
                    if (Main.netMode != 1 && flag31)
                    {
                        if (flag3)
{
                            WorldGen.KillTile(num59, num60 - 1);
                            if (Main.netMode == 2)
{
                                NetMessage.SendData(17, -1, -1, null, 0, num59, num60 - 1);
                            }
                        }
                        else
{
                            if (TileLoader.IsClosedDoor(tileSafely4))
{
                                bool flag32 = WorldGen.OpenDoor(num59, num60 - 1, direction);
                                if (!flag32)
{
                                    ai[3] = num14;
                                    netUpdate = true;
                                }
                                if (Main.netMode == 2 && flag32)
{
                                    NetMessage.SendData(19, -1, -1, null, 0, num59, num60 - 1, direction);
                                }
                            }
                            if (tileSafely4.type == 388)
{
                                bool flag33 = WorldGen.ShiftTallGate(num59, num60 - 1, closing: false);
                                if (!flag33)
{
                                    ai[3] = num14;
                                    netUpdate = true;
                                }
                                if (Main.netMode == 2 && flag33)
{
                                    NetMessage.SendData(19, -1, -1, null, 4, num59, num60 - 1, direction);
                                }
                            }
                        }
                    }
                }
            }
            else
            {
                int num62 = spriteDirection * num20;
                if (velocity.X * (float)num62 > 0f)
                {
                    if (height >= 32 && tileSafely5.nactive() && Main.tileSolid[tileSafely5.type])
                    {
                        netUpdate = true;
                        velocity.Y = -7f;
                        if (tileSafely6.nactive() && Main.tileSolid[tileSafely6.type])
{
                            velocity.Y = -8f;
                        }
                    }
                    else if (tileSafely4.nactive() && Main.tileSolid[tileSafely4.type])
                    {
                        velocity.Y = -6f;
                        netUpdate = true;
                    }
                    else if (flag30 && tileSafely3.nactive() && !tileSafely3.topSlope() && Main.tileSolid[tileSafely3.type])
                    {
                        velocity.Y = -5f;
                        netUpdate = true;
                    }
                    else if (flag18 && (!tileSafely2.nactive() || !Main.tileSolid[tileSafely2.type]) && (!tileSafely.nactive() || !Main.tileSolid[tileSafely.type]))
                    {
                        velocity.X *= 1.5f;
                        velocity.Y = -8f;
                        netUpdate = true;
                    }
                    else if (flag39)
                    {
                        ai[0] = 0f;
                        ai[1] = 0f;
                    }
                    if (velocity.Y == 0f && flag && ai[3] == 1f)
                    {
                        velocity.Y = -5f;
                        netUpdate = true;
                    }
                }
                if (flag19 && velocity.Y == 0f && Math.Abs(targetData.Center.X - base.Center.X) < 100f && Math.Abs(targetData.Center.Y - base.Center.Y) < 50f && Math.Abs(velocity.X) >= 1f && velocity.X * (float)direction > 0f)
                {
                    velocity.X = MathHelper.Clamp(velocity.X * 2f, -3f, 3f);
                    velocity.Y = -4f;
                    netAlways = true;
                }
            }
        }
        else if (flag39)
        {
            ai[0] = 0f;
            ai[1] = 0f;
        }
        if (!flag12 || !noTileCollide)
        {
            return;
        }
        wet = false;
        if (flag22)
        {
            if (alpha < 60)
            {
                alpha += 20;
            }
            localAI[3] = 40f;
        }
        bool num72 = velocity.Y == 0f;
        if (Math.Abs(base.Center.X - targetData.Center.X) > 200f)
        {
            spriteDirection = (direction = ((targetData.Center.X > base.Center.X) ? 1 : (-1)));
            velocity.X = MathHelper.Lerp(velocity.X, (float)direction, 0.05f);
        }
        int num64 = 80;
        int num65 = height;
        Vector2 vector6 = default(Vector2);
        ((Vector2)(ref vector6))._002Ector(base.Center.X - (float)(num64 / 2), position.Y + (float)height - (float)num65);
        bool flag35 = false;
        if (position.Y + (float)height < targetData.Position.Y + (float)targetData.Height - 16f)
        {
            flag35 = true;
        }
        if (flag35)
        {
            velocity.Y += 0.5f;
        }
        else if (Collision.SolidCollision(vector6, num64, num65) || targetData.Center.Y - base.Center.Y < -100f || (targetData.Center.Y - base.Center.Y < 10f && Math.Abs(targetData.Center.X - base.Center.X) < 60f))
        {
            if (velocity.Y > 0f)
            {
                velocity.Y = 0f;
            }
            if ((double)velocity.Y > -0.2)
            {
                velocity.Y -= 0.025f;
            }
            else
            {
                velocity.Y -= 0.2f;
            }
            if (velocity.Y < -4f)
            {
                velocity.Y = -4f;
            }
        }
        else
        {
            if (velocity.Y < 0f)
            {
                velocity.Y = 0f;
            }
            if ((double)velocity.Y < 0.1)
            {
                velocity.Y += 0.025f;
            }
            else
            {
                velocity.Y += 0.5f;
            }
        }
        if (velocity.Y > 10f)
        {
            velocity.Y = 10f;
        }
        if (num72)
        {
            velocity.Y = 0f;
        }
    }
References Terraria.Entity.active, Terraria.Player.AddBuff(), Terraria.NPC.ai, Terraria.NPC.alpha, Terraria.ID.NPCID.Sets.BelongsToInvasionOldOnesArmy, Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.DelegateMethods.CastLightOpen(), Terraria.NPC.collideX, Terraria.NPC.confused, Terraria.Player.creativeGodMode, Terraria.NPC.damage, Terraria.Main.dayTime, Terraria.ID.SoundID.DD2_DrakinBreathIn, Terraria.ID.SoundID.DD2_DrakinShot, Terraria.ID.SoundID.DD2_EtherianPortalSpawnEnemy, Terraria.ID.SoundID.DD2_GoblinBomberScream, Terraria.ID.SoundID.DD2_GoblinBomberThrow, Terraria.ID.SoundID.DD2_GoblinScream, Terraria.ID.SoundID.DD2_JavelinThrowersAttack, Terraria.ID.SoundID.DD2_JavelinThrowersTaunt, Terraria.ID.SoundID.DD2_KoboldExplosion, Terraria.ID.SoundID.DD2_KoboldIgnite, Terraria.ID.SoundID.DD2_KoboldIgniteLoop, Terraria.ID.SoundID.DD2_KoboldScreamChargeLoop, Terraria.ID.SoundID.DD2_OgreAttack, Terraria.ID.SoundID.DD2_OgreGroundPound, Terraria.ID.SoundID.DD2_OgreRoar, Terraria.ID.SoundID.DD2_OgreSpit, Terraria.ID.SoundID.DD2_WitherBeastAuraPulse, Terraria.ID.SoundID.DD2_WitherBeastCrystalImpact, Terraria.Player.dead, Terraria.Entity.direction, Terraria.Entity.DirectionTo(), Terraria.NPC.directionY, Terraria.Entity.Distance(), Terraria.NPC.dontTakeDamage, Terraria.Main.dust, Terraria.NPC.EncourageDespawn(), Terraria.GameContent.Events.DD2Event.EnemiesShouldChasePlayers, Terraria.ID.NPCID.Sets.FighterUsesDD2PortalAppearEffect, Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.NPC.GetAttackDamage_ForProjectiles(), Terraria.NPC.GetAttackDamage_ScaledByStrength(), Terraria.Utils.GetLerpValue(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetTargetData(), Terraria.NPC.GetTileCollisionParameters(), Terraria.Framing.GetTileSafely(), Terraria.NPC.gfxOffY, Terraria.Main.gore, Terraria.NPC.HasValidTarget, Terraria.NPC.HealEffect(), Terraria.Entity.height, Terraria.NPC.HitEffect(), Terraria.NPC.HitSound, Terraria.WorldGen.InWorld(), Terraria.ModLoader.TileLoader.IsClosedDoor(), Terraria.NPC.justHit, Terraria.WorldGen.KillTile(), Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.myPlayer, Terraria.Tile.nactive(), Terraria.NPC.netAlways, Terraria.Main.netMode, Terraria.NPC.netOffset, Terraria.NPC.netUpdate, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Gore.NewGore(), Terraria.Gore.NewGoreDirect(), Terraria.Projectile.NewProjectile(), Terraria.NPC.noGravity, Terraria.NPC.noTileCollide, Terraria.Main.npc, Terraria.Entity.oldPosition, Terraria.Entity.oldVelocity, Terraria.WorldGen.OpenDoor(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Utils.PlotTileLine(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Utils.RandomVector2(), Terraria.NetMessage.SendData(), Terraria.WorldGen.ShiftTallGate(), Terraria.Collision.SolidCollision(), Terraria.WorldGen.SolidTile(), Terraria.NPC.spriteDirection, Terraria.NPC.stepSpeed, Terraria.Collision.StepUp(), Terraria.NPC.TargetClosest(), Terraria.Utilities.NPCUtils.TargetClosestCommon(), Terraria.Utilities.NPCUtils.TargetClosestOldOnesInvasion(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.NPC.TranslatedTargetIndex, Terraria.NPC.type, Terraria.Tile.type, Terraria.NPC.value, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.NPC.VanillaAI_Inner().