TModLoader: Terraria.NPC.AI_007_TownEntities_Shimmer_TeleportToLandingSpot
AI_007_TownEntities_Shimmer_TeleportToLandingSpot()
void Terraria.NPC.AI_007_TownEntities_Shimmer_TeleportToLandingSpot () inline private
    {
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        Vector2? vector = AI_007_TownEntities_Shimmer_ScanForBestSpotToLandOn();
        if (vector.HasValue)
        {
            Vector2 vector2 = position;
            position = vector.Value;
            Vector2 movementVector = position - vector2;
            int num = 560;
            if (((Vector2)(ref movementVector)).Length() >= (float)num)
            {
                ai[2] = 30f;
                ParticleOrchestrator.BroadcastParticleSpawn(ParticleOrchestraType.ShimmerTownNPCSend, new ParticleOrchestraSettings
                {
                    PositionInWorld = vector2 + base.Size / 2f,
                    MovementVector = movementVector
                });
            }
            netUpdate = true;
        }
    }
References Terraria.NPC.ai, Terraria.NPC.AI_007_TownEntities_Shimmer_ScanForBestSpotToLandOn(), Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastParticleSpawn(), Terraria.NPC.netUpdate, and Terraria.Entity.position.
Referenced by Terraria.NPC.AI_007_TownEntities().