TModLoader: Terraria.NPC.AI_109_DarkMage
AI_109_DarkMage()
void Terraria.NPC.AI_109_DarkMage () inline private
    {
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0118: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_09df: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a06: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a12: Unknown result type (might be due to invalid IL or missing references)
        //IL_097b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0986: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0501: Unknown result type (might be due to invalid IL or missing references)
        //IL_0506: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0666: Unknown result type (might be due to invalid IL or missing references)
        //IL_027a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0280: Unknown result type (might be due to invalid IL or missing references)
        //IL_0294: Unknown result type (might be due to invalid IL or missing references)
        //IL_0299: Unknown result type (might be due to invalid IL or missing references)
        //IL_029e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_0214: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_021e: Unknown result type (might be due to invalid IL or missing references)
        //IL_024a: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_034a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0535: Unknown result type (might be due to invalid IL or missing references)
        //IL_053a: Unknown result type (might be due to invalid IL or missing references)
        //IL_053c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0584: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_040a: Unknown result type (might be due to invalid IL or missing references)
        //IL_040f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0724: Unknown result type (might be due to invalid IL or missing references)
        //IL_0751: Unknown result type (might be due to invalid IL or missing references)
        //IL_0757: Unknown result type (might be due to invalid IL or missing references)
        //IL_077b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0788: Unknown result type (might be due to invalid IL or missing references)
        //IL_078d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0793: Unknown result type (might be due to invalid IL or missing references)
        //IL_0799: Unknown result type (might be due to invalid IL or missing references)
        //IL_079e: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a3: Unknown result type (might be due to invalid IL or missing references)
        bool flag = false;
        bool flag4 = false;
        bool flag5 = true;
        bool flag6 = false;
        int num = 4;
        int num11 = 3;
        int num14 = 0;
        float num15 = 0.2f;
        float num16 = 2f;
        float num17 = -0.2f;
        float num18 = -4f;
        bool flag7 = true;
        float num19 = 2f;
        float num20 = 0.1f;
        float num2 = 1f;
        float num3 = 0.04f;
        bool flag8 = false;
        float num4 = 0.96f;
        bool flag9 = true;
        NPCAimedTarget targetData = GetTargetData();
        if (type == 564 || type == 565)
        {
            flag7 = false;
            rotation = velocity.X * 0.04f;
            spriteDirection = ((direction > 0) ? 1 : (-1));
            num14 = 2;
            num17 = -0.05f;
            num18 = -0.4f;
            num15 = 0.05f;
            num16 = 0.2f;
            num2 = 0.5f;
            num3 = 0.02f;
            num19 = 0.5f;
            num20 = 0.1f;
            localAI[2] = 0f;
            DelegateMethods.v3_1 = new Vector3(0.3f, 0.05f, 0.45f) * 1.5f;
            Utils.PlotTileLine(base.Top, base.Bottom, width, DelegateMethods.CastLightOpen);
            if (ai[0] < 0f)
            {
                ai[0] = MathHelper.Min(ai[0] + 1f, 0f);
            }
            if (ai[0] > 0f)
            {
                flag9 = false;
                flag8 = true;
                num4 = 0.9f;
                ai[0] -= 1f;
                if (ai[0] == 80f && ai[1] == 2f)
                {
                    SoundEngine.PlayTrackedSound(in SoundID.DD2_DarkMageSummonSkeleton, base.Center);
                }
                if (ai[1] == 2f && ai[0] == 64f && Main.netMode != 1)
                {
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center + new Vector2((float)(direction * 24), -40f), Vector2.Zero, 673, 0, 0f, Main.myPlayer);
                    DD2Event.RaiseGoblins(this, base.Center);
                }
                if (ai[1] == 0f && ai[0] == 32f)
                {
                    Vector2 vector = (targetData.Center - (base.Center + new Vector2((float)(direction * 10), -16f))).SafeNormalize(Vector2.UnitY) * 14f;
                    direction = ((vector.X > 0f) ? 1 : (-1));
                    if (Main.netMode != 1)
                    {
                        Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center + new Vector2((float)(direction * 10), -16f), vector, 675, 40, 0f, Main.myPlayer);
                    }
                }
                if (ai[0] == 126f && ai[1] == 1f)
                {
                    SoundEngine.PlayTrackedSound(in SoundID.DD2_DarkMageCastHeal, base.Center);
                }
                if (ai[1] == 1f && Main.netMode != 1 && (ai[0] == 40f || ai[0] == 48f || ai[0] == 56f) && WorldUtils.Find(Utils.ToTileCoordinates(new Vector2(base.Center.X + (float)(direction * 240), base.Center.Y)), Searches.Chain(new Searches.Down(50), new Terraria.WorldBuilding.Conditions.IsSolid()), out var result))
                {
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), result.ToWorldCoordinates(8f, 0f), Vector2.Zero, 674, 0, 0f, Main.myPlayer);
                }
                if (ai[0] <= 0f)
                {
                    float num21 = ai[1];
                    ai[1] += 1f;
                    if (ai[1] >= 3f)
                    {
                        ai[1] = 0f;
                    }
                    ai[0] = -120f;
                    if (num21 == 0f)
                    {
                        ai[0] = -20f;
                    }
                    netUpdate = true;
                }
            }
            if (ai[0] == 0f && localAI[3] >= 60f)
            {
                bool flag10 = false;
                Vector2 minimum = base.Center + new Vector2(-600f, -200f);
                Vector2 maximum = base.Center + new Vector2(600f, 200f);
                int num5 = 0;
                for (int i = 0; i < 200; i++)
                {
                    NPC nPC = Main.npc[i];
                    if (nPC.active && nPC.lifeMax != nPC.life && nPC.Center.Between(minimum, maximum) && ++num5 >= 2)
                    {
                        flag10 = true;
                        break;
                    }
                }
                if (!flag10)
                {
                    ai[1] = 2f;
                }
                if (ai[1] == 2f && !DD2Event.CanRaiseGoblinsHere(base.Center))
                {
                    ai[1] = 0f;
                }
                bool flag11 = true;
                if (ai[1] == 0f && (Distance(targetData.Center) >= 1000f || !Collision.CanHitLine(base.Center, 0, 0, targetData.Center, 0, 0)))
                {
                    flag11 = false;
                }
                if (flag11)
                {
                    switch ((int)ai[1])
                    {
                    case 0:
                        ai[0] = 97f;
                        break;
                    case 1:
                        ai[0] = 127f;
                        break;
                    case 2:
                        ai[0] = 183f;
                        break;
                    }
                    netUpdate = true;
                    flag8 = true;
                }
            }
            if (localAI[3] == 0f)
            {
                alpha = 255;
            }
            if (localAI[3] == 30f)
            {
                SoundEngine.PlayTrackedSound(in SoundID.DD2_EtherianPortalSpawnEnemy, base.Center);
            }
            if (localAI[3] < 60f)
            {
                localAI[3] += 1f;
                alpha -= 5;
                if (alpha < 0)
                {
                    alpha = 0;
                }
                int num6 = (int)localAI[3] / 10;
                Vector2 size = base.Size;
                float num7 = ((Vector2)(ref size)).Length() / 2f;
                num7 /= 20f;
                int maxValue = 5;
                if (type == 576 || type == 577)
                {
                    maxValue = 1;
                }
                for (int j = 0; j < num6; j++)
                {
                    if (Main.rand.Next(maxValue) == 0)
                    {
                        Dust dust = Dust.NewDustDirect(position, width, height, 27, velocity.X * 1f, 0f, 100);
                        dust.scale = 0.55f;
                        dust.fadeIn = 0.7f;
                        dust.velocity *= 0.1f * num7;
                        dust.velocity += velocity;
                    }
                }
            }
        }
        if (justHit)
        {
            localAI[2] = 0f;
        }
        if (!flag4)
        {
            if (localAI[2] >= 0f)
            {
                float num8 = 16f;
                bool flag2 = false;
                bool flag3 = false;
                if (position.X > localAI[0] - num8 && position.X < localAI[0] + num8)
                {
                    flag2 = true;
                }
                else if ((velocity.X < 0f && direction > 0) || (velocity.X > 0f && direction < 0))
                {
                    flag2 = true;
                    num8 += 24f;
                }
                if (position.Y > localAI[1] - num8 && position.Y < localAI[1] + num8)
                {
                    flag3 = true;
                }
                if (flag2 && flag3)
                {
                    localAI[2] += 1f;
                    if (localAI[2] >= 30f && num8 == 16f)
                    {
                        flag = true;
                    }
                    if (localAI[2] >= 60f)
                    {
                        localAI[2] = -180f;
                        direction *= -1;
                        velocity.X *= -1f;
                        collideX = false;
                    }
                }
                else
                {
                    localAI[0] = position.X;
                    localAI[1] = position.Y;
                    localAI[2] = 0f;
                }
                if (flag9)
                {
                    NPCUtils.TargetClosestOldOnesInvasion(this);
                }
            }
            else
            {
                localAI[2] += 1f;
                direction = ((targetData.Center.X > base.Center.X) ? 1 : (-1));
            }
        }
        int num9 = (int)((position.X + (float)(width / 2)) / 16f) + direction * 2;
        int num10 = (int)((position.Y + (float)height) / 16f);
        int num12 = (int)base.Bottom.Y / 16;
        int num13 = (int)base.Bottom.X / 16;
        if (flag8)
        {
            velocity *= num4;
            return;
        }
        for (int k = num10; k < num10 + num; k++)
        {
            if (Main.tile[num9, k] == null)
            {
                Main.tile[num9, k] = default(Tile);
            }
            if ((Main.tile[num9, k].nactive() && Main.tileSolid[Main.tile[num9, k].type]) || Main.tile[num9, k].liquid > 0)
            {
                if (k <= num10 + 1)
                {
                    flag6 = true;
                }
                flag5 = false;
                break;
            }
        }
        for (int l = num12; l < num12 + num14; l++)
        {
            if (Main.tile[num13, l] == null)
            {
                Main.tile[num13, l] = default(Tile);
            }
            if ((Main.tile[num13, l].nactive() && Main.tileSolid[Main.tile[num13, l].type]) || Main.tile[num13, l].liquid > 0)
            {
                flag6 = true;
                flag5 = false;
                break;
            }
        }
        if (flag7)
        {
            for (int m = num10 - num11; m < num10; m++)
            {
                if (Main.tile[num9, m] == null)
                {
                    Main.tile[num9, m] = default(Tile);
                }
                if ((Main.tile[num9, m].nactive() && Main.tileSolid[Main.tile[num9, m].type]) || Main.tile[num9, m].liquid > 0)
                {
                    flag6 = false;
                    flag = true;
                    break;
                }
            }
        }
        if (flag)
        {
            flag6 = false;
            flag5 = true;
        }
        if (flag5)
        {
            velocity.Y += num15;
            if (velocity.Y > num16)
            {
                velocity.Y = num16;
            }
        }
        else
        {
            if ((directionY < 0 && velocity.Y > 0f) || flag6)
            {
                velocity.Y += num17;
            }
            if (velocity.Y < num18)
            {
                velocity.Y = num18;
            }
        }
        if (collideX)
        {
            velocity.X = oldVelocity.X * -0.4f;
            if (direction == -1 && velocity.X > 0f && velocity.X < 1f)
            {
                velocity.X = 1f;
            }
            if (direction == 1 && velocity.X < 0f && velocity.X > -1f)
            {
                velocity.X = -1f;
            }
        }
        if (collideY)
        {
            velocity.Y = oldVelocity.Y * -0.25f;
            if (velocity.Y > 0f && velocity.Y < 1f)
            {
                velocity.Y = 1f;
            }
            if (velocity.Y < 0f && velocity.Y > -1f)
            {
                velocity.Y = -1f;
            }
        }
        if (direction == -1 && velocity.X > 0f - num19)
        {
            velocity.X -= num20;
            if (velocity.X > num19)
            {
                velocity.X -= num20;
            }
            else if (velocity.X > 0f)
            {
                velocity.X += num20 / 2f;
            }
            if (velocity.X < 0f - num19)
            {
                velocity.X = 0f - num19;
            }
        }
        else if (direction == 1 && velocity.X < num19)
        {
            velocity.X += num20;
            if (velocity.X < 0f - num19)
            {
                velocity.X += num20;
            }
            else if (velocity.X < 0f)
            {
                velocity.X -= num20 / 2f;
            }
            if (velocity.X > num19)
            {
                velocity.X = num19;
            }
        }
        if (directionY == -1 && velocity.Y > 0f - num2)
        {
            velocity.Y -= num3;
            if (velocity.Y > num2)
            {
                velocity.Y -= num3 * 1.25f;
            }
            else if (velocity.Y > 0f)
            {
                velocity.Y += num3 * 0.75f;
            }
            if (velocity.Y < 0f - num2)
            {
                velocity.Y = 0f - num19;
            }
        }
        else if (directionY == 1 && velocity.Y < num2)
        {
            velocity.Y += num3;
            if (velocity.Y < 0f - num2)
            {
                velocity.Y += num3 * 1.25f;
            }
            else if (velocity.Y < 0f)
            {
                velocity.Y -= num3 * 0.75f;
            }
            if (velocity.Y > num2)
            {
                velocity.Y = num2;
            }
        }
    }
References Terraria.NPC.ai, Terraria.NPC.alpha, Terraria.Collision.CanHitLine(), Terraria.GameContent.Events.DD2Event.CanRaiseGoblinsHere(), Terraria.DelegateMethods.CastLightOpen(), Terraria.WorldBuilding.Searches.Chain(), Terraria.NPC.collideX, Terraria.NPC.collideY, Terraria.ID.SoundID.DD2_DarkMageCastHeal, Terraria.ID.SoundID.DD2_DarkMageSummonSkeleton, Terraria.ID.SoundID.DD2_EtherianPortalSpawnEnemy, Terraria.Entity.direction, Terraria.NPC.directionY, Terraria.Entity.Distance(), Terraria.WorldBuilding.WorldUtils.Find(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetTargetData(), Terraria.Entity.height, Terraria.NPC.justHit, Terraria.NPC.localAI, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.Dust.NewDustDirect(), Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Utils.PlotTileLine(), Terraria.Entity.position, Terraria.GameContent.Events.DD2Event.RaiseGoblins(), Terraria.Main.rand, Terraria.NPC.rotation, Terraria.NPC.spriteDirection, Terraria.Utilities.NPCUtils.TargetClosestOldOnesInvasion(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Utils.ToTileCoordinates(), Terraria.NPC.type, Terraria.Entity.velocity, and Terraria.Entity.width.
Referenced by Terraria.NPC.VanillaAI_Inner().