TModLoader: Terraria.NPC.AI_120_HallowBoss_DoMagicEffect
AI_120_HallowBoss_DoMagicEffect()
void Terraria.NPC.AI_120_HallowBoss_DoMagicEffect (Vector2 spot, int effectType, float progress) inline private
    {
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01be: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_023d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0242: Unknown result type (might be due to invalid IL or missing references)
        //IL_030b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_0338: Unknown result type (might be due to invalid IL or missing references)
        //IL_0342: Unknown result type (might be due to invalid IL or missing references)
        //IL_0347: Unknown result type (might be due to invalid IL or missing references)
        //IL_0364: Unknown result type (might be due to invalid IL or missing references)
        //IL_036a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0374: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_037e: Unknown result type (might be due to invalid IL or missing references)
        //IL_029e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02de: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e3: Unknown result type (might be due to invalid IL or missing references)
        float num = 4f;
        float num2 = 1f;
        float fadeIn = 0f;
        float num3 = 0.5f;
        int num4 = 2;
        int num5 = 267;
        switch (effectType)
        {
        case 1:
            num2 = 0.5f;
            fadeIn = 2f;
            num3 = 0f;
            break;
        case 2:
        case 4:
            num = 50f;
            num2 = 0.5f;
            fadeIn = 0f;
            num3 = 0f;
            num4 = 4;
            break;
        case 3:
            num = 30f;
            num2 = 0.1f;
            fadeIn = 2.5f;
            num3 = 0f;
            break;
        case 5:
            if (progress == 0f)
            {
                num4 = 0;
            }
            else
            {
                num4 = 5;
                num5 = Main.rand.Next(86, 92);
            }
            if (progress >= 1f)
            {
                num4 = 0;
            }
            break;
        }
        for (int i = 0; i < num4; i++)
        {
            Dust dust = Dust.NewDustPerfect(spot, num5, Main.rand.NextVector2CircularEdge(num, num) * (Main.rand.NextFloat() * (1f - num3) + num3), 0, Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f), (Main.rand.NextFloat() * 2f + 2f) * num2);
            dust.fadeIn = fadeIn;
            dust.noGravity = true;
            switch (effectType)
            {
            case 2:
            case 4:
            {
                dust.velocity *= 0.005f;
                dust.scale = 3f * Utils.GetLerpValue(0.7f, 0f, progress, clamped: true) * Utils.GetLerpValue(0f, 0.3f, progress, clamped: true);
                dust.velocity = ((float)Math.PI * 2f * ((float)i / 4f) + (float)Math.PI / 4f).ToRotationVector2() * 8f * Utils.GetLerpValue(1f, 0f, progress, clamped: true);
                dust.velocity += velocity * 0.3f;
                float num6 = 0f;
                if (effectType == 4)
                {
                    num6 = 0.5f;
                }
                dust.color = Main.hslToRgb(((float)i / 5f + num6 + progress * 0.5f) % 1f, 1f, 0.5f);
                ref Color reference = ref dust.color;
                ((Color)(ref reference)).A = (byte)(((Color)(ref reference)).A / 2);
                dust.alpha = 127;
                break;
            }
            case 5:
                if (progress == 0f)
                {
                    dust.customData = this;
                    dust.scale = 1.5f;
                    dust.fadeIn = 0f;
                    dust.velocity = new Vector2(0f, -1f) + Main.rand.NextVector2Circular(1f, 1f);
                    dust.color = new Color(255, 255, 255, 80) * 0.3f;
                }
                else
                {
                    dust.color = Main.hslToRgb(progress * 2f % 1f, 1f, 0.5f);
                    dust.alpha = 0;
                    dust.scale = 1f;
                    dust.fadeIn = 1.3f;
                    dust.velocity *= 3f;
                    dust.velocity.X *= 0.1f;
                    dust.velocity += velocity * 1f;
                }
                break;
            }
        }
    }
References Terraria.Dust.color, Terraria.Utils.GetLerpValue(), Terraria.Main.hslToRgb(), Terraria.Dust.NewDustPerfect(), Terraria.Main.rand, and Terraria.Entity.velocity.
Referenced by Terraria.NPC.AI_120_HallowBoss().