TModLoader: Terraria.NPC.ScaleStats_ApplyMultiplayerStats
ScaleStats_ApplyMultiplayerStats()
void Terraria.NPC.ScaleStats_ApplyMultiplayerStats (int numPlayers, float balance, float boost, float bossAdjustment) inline private
Definition at line 13285 of file NPC.cs.
    {
        int num = numPlayers - 1;
        if (type == 5)
        {
            lifeMax = (int)((float)lifeMax * 0.75f * bossAdjustment);
        }
        if (type == 4)
        {
            lifeMax = (int)((double)lifeMax * 0.65 * (double)balance * (double)bossAdjustment);
        }
        if (type >= 13 && type <= 15)
        {
            lifeMax = (int)((double)lifeMax * 0.7 * (double)balance * (double)bossAdjustment);
            if (type == 13)
            {
                damage = (int)((double)damage * 1.1);
            }
            if (type == 14)
            {
                damage = (int)((double)damage * 0.8);
            }
            if (type == 15)
            {
                damage = (int)((double)damage * 0.8);
            }
            scale *= 1.2f;
            defense += 2;
        }
        if (type == 266 || type == 267)
        {
            lifeMax = (int)((double)lifeMax * 0.85 * (double)balance * (double)bossAdjustment);
            damage = (int)((double)damage * 0.9);
            scale *= 1.05f;
            for (float num2 = 1f; num2 < balance; num2 += 0.34f)
            {
                if ((double)knockBackResist < 0.1)
                {
                    knockBackResist = 0f;
                    break;
                }
                knockBackResist *= 0.8f;
            }
        }
        if (type == 50)
        {
            lifeMax = (int)((double)lifeMax * 0.7 * (double)balance * (double)bossAdjustment);
            damage = (int)((double)damage * 0.8);
        }
        if (type == 471)
        {
            lifeMax = (int)((double)lifeMax * 0.85 * (double)(balance * 2f + 1f) / 3.0);
        }
        if (type == 472)
        {
            lifeMax = (int)((double)lifeMax * 0.85 * (double)(balance + 1f) / 2.0);
            damage = (int)((double)damage * 0.8);
        }
        if (type == 222)
        {
            lifeMax = (int)((double)lifeMax * 0.7 * (double)balance * (double)bossAdjustment);
            damage = (int)((double)damage * 0.9);
        }
        if (type == 210 || type == 211)
        {
            lifeMax = (int)((double)lifeMax * 0.75);
        }
        if (type == 35)
        {
            lifeMax = (int)((float)lifeMax * balance * bossAdjustment);
            damage = (int)((double)damage * 1.1);
        }
        else if (type == 36)
        {
            lifeMax = (int)((double)lifeMax * 1.3 * (double)balance * (double)bossAdjustment);
            damage = (int)((double)damage * 1.1);
        }
        if (type == 668)
        {
            lifeMax = (int)((double)lifeMax * 0.85 * (double)balance * (double)bossAdjustment);
            damage = damage;
        }
        if (type == 113 || type == 114)
        {
            defense += 6;
            lifeMax = (int)((double)lifeMax * 0.7 * (double)balance * (double)bossAdjustment);
            damage = (int)((double)damage * 1.5);
        }
        else if (type == 115)
        {
            lifeMax = (int)((double)lifeMax * 0.7 * (double)balance);
            if (numPlayers > 4)
            {
                knockBackResist = 0f;
            }
            else if (numPlayers > 1)
            {
                knockBackResist *= 1f - boost;
            }
            defense += 6;
        }
        else if (type == 116)
        {
            lifeMax = (int)((double)lifeMax * 0.7 * (double)balance);
            if (numPlayers > 4)
            {
                knockBackResist = 0f;
            }
            else if (numPlayers > 1)
            {
                knockBackResist *= 1f - boost;
            }
        }
        else if (type == 117 || type == 118 || type == 119)
        {
            lifeMax = (int)((double)lifeMax * 0.8);
        }
        if (type == 657)
        {
            lifeMax = (int)((float)lifeMax * 0.8f * balance * bossAdjustment);
        }
        if (type >= 658 && type <= 660)
        {
            lifeMax = (int)((float)lifeMax * 0.75f * balance * bossAdjustment);
        }
        if (type >= 134 && type <= 136)
        {
            lifeMax = (int)((double)lifeMax * 0.75 * (double)balance * (double)bossAdjustment);
            if (type == 134)
            {
                damage *= 2;
            }
            if (type == 135)
            {
                damage = (int)((double)damage * 0.85);
            }
            if (type == 136)
            {
                damage = (int)((double)damage * 0.85);
            }
            scale *= 1.05f;
        }
        else if (type == 139)
        {
            lifeMax = (int)((double)lifeMax * 0.75 * (double)(balance * 2f + 1f) / 3.0);
            damage = (int)((double)damage * 0.8);
            scale *= 1.05f;
        }
        if (type >= 127 && type <= 131)
        {
            lifeMax = (int)((double)lifeMax * 0.75 * (double)balance * (double)bossAdjustment);
            damage = (int)((double)damage * 0.85);
        }
        if (type >= 125 && type <= 126)
        {
            lifeMax = (int)((double)lifeMax * 0.75 * (double)balance * (double)bossAdjustment);
            damage = (int)((double)damage * 0.85);
        }
        if (type == 262)
        {
            lifeMax = (int)((double)lifeMax * 0.7 * (double)balance * (double)bossAdjustment);
            damage = (int)((double)damage * 1.15);
        }
        else if (type == 264)
        {
            lifeMax = (int)((float)lifeMax * balance * bossAdjustment);
            damage = (int)((double)damage * 1.15);
        }
        if (type == 636)
        {
            lifeMax = (int)((double)lifeMax * 0.7 * (double)balance * (double)bossAdjustment);
            damage = (int)((double)damage * 1.15);
        }
        if (type >= 245 && type <= 249)
        {
            lifeMax = (int)((double)lifeMax * 0.75 * (double)balance * (double)bossAdjustment);
            damage = (int)((double)damage * 0.8);
        }
        if (type == 370)
        {
            lifeMax = (int)((double)lifeMax * 0.65 * (double)balance * (double)bossAdjustment);
            damage = (int)((double)damage * 0.7);
        }
        else if (type == 371 || type == 372 || type == 373)
        {
            if (type != 371)
            {
                lifeMax = (int)((double)lifeMax * 0.75);
            }
            damage = (int)((double)damage * 0.75);
        }
        if (type == 439 || type == 440 || (type >= 454 && type <= 459) || type == 522 || type == 523)
        {
            if (type != 522)
            {
                lifeMax = (int)((float)lifeMax * 0.75f * balance * bossAdjustment);
            }
            damage = (int)((double)damage * 0.75);
        }
        if (type == 397 || type == 396 || type == 398)
        {
            lifeMax = (int)((double)lifeMax * 0.75 * (double)balance * (double)bossAdjustment);
            damage = (int)((double)damage * 0.75);
        }
        if (type == 551)
        {
            lifeMax = (int)((double)lifeMax * 0.75 * (double)balance * (double)bossAdjustment);
            damage = (int)((double)damage * 0.65);
        }
        else if (NPCID.Sets.BelongsToInvasionOldOnesArmy[type])
        {
            int num3 = 7;
            float num4 = (balance * (float)(num3 - 1) + 1f) / (float)num3;
            lifeMax = (int)((float)lifeMax * num4 * bossAdjustment);
        }
        float num5 = 1f + (float)num * 0.2f;
        switch (type)
        {
        case 305:
        case 306:
        case 307:
        case 308:
        case 309:
        case 310:
        case 311:
        case 312:
        case 313:
        case 314:
        case 326:
        case 329:
        case 330:
            lifeMax = (int)((double)lifeMax * 0.75 * (double)num5);
            damage = (int)((double)damage * 0.75);
            break;
        case 315:
        case 325:
        case 327:
            lifeMax = (int)((double)lifeMax * 0.65 * (double)bossAdjustment);
            damage = (int)((double)damage * 0.75);
            break;
        }
        switch (type)
        {
        case 338:
        case 339:
        case 340:
        case 341:
        case 342:
        case 343:
        case 347:
        case 348:
        case 349:
        case 350:
        case 351:
        case 352:
            lifeMax = (int)((double)lifeMax * 0.75 * (double)num5);
            damage = (int)((double)damage * 0.75);
            break;
        case 344:
        case 345:
        case 346:
            lifeMax = (int)((double)lifeMax * 0.65 * (double)bossAdjustment);
            damage = (int)((double)damage * 0.75);
            break;
        }
        if (Main.getGoodWorld)
        {
            if (type == 6 && AnyNPCs(13))
            {
                lifeMax = (int)((double)lifeMax * 1.5 * (double)bossAdjustment);
                defense += 2;
            }
            if (type == 32 && AnyNPCs(35))
            {
                lifeMax = (int)((double)lifeMax * 1.5 * (double)bossAdjustment);
                defense += 6;
            }
            if (type == 24 && AnyNPCs(113))
            {
                lifeMax = (int)((double)lifeMax * 1.5 * (double)bossAdjustment);
                defense += 10;
            }
        }
        NPCLoader.ApplyDifficultyAndPlayerScaling(this, numPlayers, balance, bossAdjustment);
        defDefense = defense;
        defDamage = damage;
        life = lifeMax;
    }
References Terraria.NPC.AnyNPCs(), Terraria.ModLoader.NPCLoader.ApplyDifficultyAndPlayerScaling(), Terraria.ID.NPCID.Sets.BelongsToInvasionOldOnesArmy, Terraria.NPC.damage, Terraria.NPC.defDamage, Terraria.NPC.defDefense, Terraria.NPC.defense, Terraria.Main.getGoodWorld, Terraria.NPC.knockBackResist, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.scale, and Terraria.NPC.type.
Referenced by Terraria.NPC.ScaleStats().