TModLoader: Terraria.NPC.TransformVisuals
TransformVisuals()
void Terraria.NPC.TransformVisuals (int oldType, int newType) inline
Definition at line 91412 of file NPC.cs.
    {
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0145: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0549: Unknown result type (might be due to invalid IL or missing references)
        //IL_054f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0554: Unknown result type (might be due to invalid IL or missing references)
        //IL_0559: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_020c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0212: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        //IL_022f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0302: Unknown result type (might be due to invalid IL or missing references)
        //IL_0307: Unknown result type (might be due to invalid IL or missing references)
        //IL_030c: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_031a: Unknown result type (might be due to invalid IL or missing references)
        //IL_031f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0324: Unknown result type (might be due to invalid IL or missing references)
        //IL_032b: Unknown result type (might be due to invalid IL or missing references)
        //IL_032d: Unknown result type (might be due to invalid IL or missing references)
        //IL_035a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0366: Unknown result type (might be due to invalid IL or missing references)
        //IL_036b: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0400: Unknown result type (might be due to invalid IL or missing references)
        //IL_0406: Unknown result type (might be due to invalid IL or missing references)
        //IL_0448: Unknown result type (might be due to invalid IL or missing references)
        //IL_045a: Unknown result type (might be due to invalid IL or missing references)
        //IL_045f: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04da: Unknown result type (might be due to invalid IL or missing references)
        //IL_051c: Unknown result type (might be due to invalid IL or missing references)
        //IL_052e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0533: Unknown result type (might be due to invalid IL or missing references)
        position += netOffset;
        if ((oldType == 158 && newType == 159) || (oldType == 159 && newType == 158))
        {
            SoundEngine.PlaySound(in SoundID.Item8, position);
            int num = Gore.NewGore(new Vector2(position.X, position.Y - 10f), velocity, 99, scale);
            Gore obj = Main.gore[num];
            obj.velocity *= 0.3f;
            num = Gore.NewGore(new Vector2(position.X, position.Y + (float)(height / 2) - 10f), velocity, 99, scale);
            Gore obj2 = Main.gore[num];
            obj2.velocity *= 0.3f;
            num = Gore.NewGore(new Vector2(position.X, position.Y + (float)height - 10f), velocity, 99, scale);
            Gore obj3 = Main.gore[num];
            obj3.velocity *= 0.3f;
        }
        else if (oldType == 478 && newType == 479)
        {
            for (int i = 0; i < 30; i++)
            {
                int num2 = Dust.NewDust(position, width, height, 238, 0f, -2f);
                if (Main.rand.Next(2) == 0)
                {
                    Main.dust[num2].noGravity = true;
                }
            }
            Gore.NewGore(position, velocity, 684, scale);
            Gore.NewGore(position, velocity, 685, scale);
            Gore.NewGore(position, velocity, 686, scale);
            Gore.NewGore(position, velocity, 684 + Main.rand.Next(3), scale);
        }
        else if (oldType == 406 && newType == 405)
        {
            float num3 = Main.rand.Next(10, 21);
            float num4 = (float)Math.PI * 2f * Main.rand.NextFloat();
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector(22f, 22f);
            for (float num5 = 0f; num5 < num3; num5 += 1f)
            {
                Dust dust = Main.dust[Dust.NewDust(base.Center, 0, 0, 229)];
                Vector2 vector2 = Vector2.UnitY.RotatedBy(num5 * ((float)Math.PI * 2f) / num3 + num4);
                dust.position = base.Center + vector2 * vector / 2f;
                dust.velocity = vector2;
                dust.noGravity = true;
                dust.scale = 0.6f + Main.rand.NextFloat() * 1.8f;
                dust.velocity *= dust.scale;
                dust.fadeIn = Main.rand.NextFloat() * 2f;
            }
        }
        if (oldType == 428 && newType == 427)
        {
            for (int j = 0; j < 20; j++)
            {
                int num6 = Utils.SelectRandom<int>(Main.rand, 229, 240);
                Dust dust2 = Main.dust[Dust.NewDust(position, width, height, num6)];
                dust2.noGravity = true;
                dust2.scale = 0.6f + Main.rand.NextFloat() * 1.8f;
                dust2.fadeIn = 0.25f;
                dust2.velocity *= dust2.scale / 2f;
            }
        }
        if (oldType == 427 && newType == 426)
        {
            for (int k = 0; k < 30; k++)
            {
                int num7 = Utils.SelectRandom<int>(Main.rand, 229, 240, 240);
                Dust dust3 = Main.dust[Dust.NewDust(position, width, height, num7)];
                dust3.noGravity = true;
                dust3.scale = 0.6f + Main.rand.NextFloat() * 1.8f;
                dust3.fadeIn = 0.25f;
                dust3.velocity *= dust3.scale * 0.75f;
            }
        }
        position -= netOffset;
    }
References Terraria.Main.dust, Terraria.Main.gore, Terraria.ID.SoundID.Item8, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, and Terraria.Dust.scale.