TModLoader: Terraria.NPC.AI_006_Worms
AI_006_Worms()
void Terraria.NPC.AI_006_Worms () inline private
    {
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0230: Unknown result type (might be due to invalid IL or missing references)
        //IL_0236: Unknown result type (might be due to invalid IL or missing references)
        //IL_023b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0240: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_03af: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03db: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0345: Unknown result type (might be due to invalid IL or missing references)
        //IL_034a: Unknown result type (might be due to invalid IL or missing references)
        //IL_034f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_2be2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0619: Unknown result type (might be due to invalid IL or missing references)
        //IL_062d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0406: Unknown result type (might be due to invalid IL or missing references)
        //IL_040b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0297: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        //IL_077c: Unknown result type (might be due to invalid IL or missing references)
        //IL_078f: Unknown result type (might be due to invalid IL or missing references)
        //IL_041e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0442: Unknown result type (might be due to invalid IL or missing references)
        //IL_0448: Unknown result type (might be due to invalid IL or missing references)
        //IL_0493: Unknown result type (might be due to invalid IL or missing references)
        //IL_0495: Unknown result type (might be due to invalid IL or missing references)
        //IL_0586: Unknown result type (might be due to invalid IL or missing references)
        //IL_058b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0590: Unknown result type (might be due to invalid IL or missing references)
        //IL_059a: Unknown result type (might be due to invalid IL or missing references)
        //IL_059f: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0543: Unknown result type (might be due to invalid IL or missing references)
        //IL_0545: Unknown result type (might be due to invalid IL or missing references)
        //IL_0699: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c78: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c83: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c88: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c42: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d68: Unknown result type (might be due to invalid IL or missing references)
        //IL_204c: Unknown result type (might be due to invalid IL or missing references)
        //IL_21bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_21c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_21c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_21cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_21d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_21e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_21ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_21f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_21f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_21ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_2209: Unknown result type (might be due to invalid IL or missing references)
        //IL_220e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2215: Unknown result type (might be due to invalid IL or missing references)
        //IL_2217: Unknown result type (might be due to invalid IL or missing references)
        //IL_2219: Unknown result type (might be due to invalid IL or missing references)
        //IL_2239: Unknown result type (might be due to invalid IL or missing references)
        //IL_226a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2274: Unknown result type (might be due to invalid IL or missing references)
        //IL_2279: Unknown result type (might be due to invalid IL or missing references)
        //IL_227e: Unknown result type (might be due to invalid IL or missing references)
        //IL_228e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2293: Unknown result type (might be due to invalid IL or missing references)
        //IL_229d: Unknown result type (might be due to invalid IL or missing references)
        //IL_229f: Unknown result type (might be due to invalid IL or missing references)
        //IL_22a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_22c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_22f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_22fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2301: Unknown result type (might be due to invalid IL or missing references)
        //IL_2306: Unknown result type (might be due to invalid IL or missing references)
        //IL_2316: Unknown result type (might be due to invalid IL or missing references)
        //IL_231b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2322: Unknown result type (might be due to invalid IL or missing references)
        //IL_2328: Unknown result type (might be due to invalid IL or missing references)
        //IL_232d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2332: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e57: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e93: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ea7: Unknown result type (might be due to invalid IL or missing references)
        //IL_2963: Unknown result type (might be due to invalid IL or missing references)
        //IL_297c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2995: Unknown result type (might be due to invalid IL or missing references)
        //IL_29a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_264e: Unknown result type (might be due to invalid IL or missing references)
        //IL_266d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a39: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a71: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aac: Unknown result type (might be due to invalid IL or missing references)
        //IL_26fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_2713: Unknown result type (might be due to invalid IL or missing references)
        //IL_27c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_27cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_27d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2766: Unknown result type (might be due to invalid IL or missing references)
        //IL_2748: Unknown result type (might be due to invalid IL or missing references)
        //IL_27eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_27f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_27f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_28e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_28ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_28ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_28f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2842: Unknown result type (might be due to invalid IL or missing references)
        //IL_2848: Unknown result type (might be due to invalid IL or missing references)
        //IL_284d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2852: Unknown result type (might be due to invalid IL or missing references)
        //IL_290b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2912: Unknown result type (might be due to invalid IL or missing references)
        //IL_2917: Unknown result type (might be due to invalid IL or missing references)
        //IL_291b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2927: Unknown result type (might be due to invalid IL or missing references)
        //IL_2869: Unknown result type (might be due to invalid IL or missing references)
        //IL_2870: Unknown result type (might be due to invalid IL or missing references)
        //IL_2875: Unknown result type (might be due to invalid IL or missing references)
        //IL_2879: Unknown result type (might be due to invalid IL or missing references)
        //IL_2885: Unknown result type (might be due to invalid IL or missing references)
        //IL_32b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_32c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_32c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_3abf: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ac5: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ae0: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ae6: Unknown result type (might be due to invalid IL or missing references)
        //IL_3aeb: Unknown result type (might be due to invalid IL or missing references)
        //IL_3af0: Unknown result type (might be due to invalid IL or missing references)
        //IL_3afb: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b10: Unknown result type (might be due to invalid IL or missing references)
        //IL_34a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_34b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_34b6: Unknown result type (might be due to invalid IL or missing references)
        if (type == 117 && localAI[1] == 0f)
        {
            localAI[1] = 1f;
            SoundEngine.PlaySound(in SoundID.NPCDeath13, position);
            int num = 1;
            if (velocity.X < 0f)
            {
                num = -1;
            }
            for (int i = 0; i < 20; i++)
            {
                Dust.NewDust(new Vector2(position.X - 20f, position.Y - 20f), width + 40, height + 40, 5, num * 8, -1f);
            }
        }
        if (type == 454 && localAI[3] == 0f)
        {
            SoundEngine.PlaySound(in SoundID.Item119, position);
            localAI[3] = 1f;
        }
        if (type >= 454 && type <= 459)
        {
            dontTakeDamage = alpha > 0;
            if (type == 454 || (type != 454 && Main.npc[(int)ai[1]].alpha < 85))
            {
                if (dontTakeDamage)
                {
                    for (int j = 0; j < 2; j++)
                    {
                        int num12 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 228, 0f, 0f, 100, default(Color), 2f);
                        Main.dust[num12].noGravity = true;
                        Main.dust[num12].noLight = true;
                    }
                }
                alpha -= 42;
                if (alpha < 0)
                {
                    alpha = 0;
                }
            }
        }
        if (type >= 621 && type <= 623)
        {
            position += netOffset;
            dontTakeDamage = alpha > 0;
            if (type == 621 || (type != 621 && Main.npc[(int)ai[1]].alpha < 85))
            {
                if (dontTakeDamage)
                {
                    for (int k = 0; k < 2; k++)
                    {
                        Dust.NewDust(position, width, height, 5, 0f, 0f, 100);
                    }
                }
                alpha -= 42;
                if (alpha < 0)
                {
                    alpha = 0;
                }
            }
            if (alpha == 0 && Main.rand.Next(5) == 0)
            {
                Dust.NewDust(position, width, height, 5, 0f, 0f, 100);
            }
            position -= netOffset;
        }
        else if (type == 402)
        {
            ai[2] += 1f;
            float num23 = 600f;
            float num34 = num23 - 30f;
            if (((Vector2)(ref velocity)).Length() >= 1f && ai[2] <= num34)
            {
                velocity *= Utils.Remap(ai[2], num34 * 0.5f, num34, 1f, 0.5f);
            }
            if (ai[2] == num34)
            {
                for (int l = 0; l < 50; l++)
                {
                    Vector2 vector = Main.rand.NextVector2Circular(8f, 8f);
                    if (Main.rand.Next(2) == 0)
                    {
                        int num45 = Dust.NewDust(position, width, height, 180, 0f, 0f, 100);
                        Main.dust[num45].scale += (float)Main.rand.Next(50) * 0.04f;
                        Main.dust[num45].noGravity = true;
                        Main.dust[num45].velocity = vector;
                        Main.dust[num45].fadeIn = Main.rand.NextFloat() * 1.5f;
                    }
                    if (Main.rand.Next(2) == 0)
                    {
                        int num55 = Dust.NewDust(position, width, height, 176, 0f, 0f, 100);
                        Main.dust[num55].scale += 0.3f + (float)Main.rand.Next(50) * 0.01f;
                        Main.dust[num55].noGravity = true;
                        Main.dust[num55].velocity = vector;
                        Main.dust[num55].fadeIn = Main.rand.NextFloat() * 1.5f;
                    }
                }
                if (Main.netMode != 1)
                {
                    SpawnStardustMark_StardustWorm();
                    velocity = velocity.SafeNormalize(Vector2.Zero) * 6f;
                    netUpdate = true;
                }
            }
            if (ai[2] >= num23 && Main.netMode != 1)
            {
                ai[2] = 0f;
                netUpdate = true;
            }
        }
        if (Main.netMode != 1 && Main.expertMode)
        {
            if (type == 14 && ((double)(position.Y / 16f) < Main.worldSurface || Main.getGoodWorld))
            {
                int num66 = (int)(base.Center.X / 16f);
                int num76 = (int)(base.Center.Y / 16f);
                if (WorldGen.InWorld(num66, num76) && Main.tile[num66, num76].wall == 0)
                {
                    int num79 = 900;
                    if (Main.getGoodWorld)
                    {
                        num79 /= 2;
                    }
                    if (Main.rand.Next(num79) == 0)
                    {
                        TargetClosest();
                        if (Collision.CanHitLine(base.Center, 1, 1, Main.player[target].Center, 1, 1))
{
                            NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2) + velocity.X), (int)(position.Y + (float)(height / 2) + velocity.Y), 666, 0, 0f, 1f);
                        }
                    }
                }
            }
            else if (type == 13)
            {
                int num2 = 90;
                num2 += (int)((float)life / (float)lifeMax * 60f * 5f);
                if (Main.rand.Next(num2) == 0)
                {
                    TargetClosest();
                    if (Collision.CanHitLine(base.Center, 1, 1, Main.player[target].Center, 1, 1))
                    {
                        NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2) + velocity.X), (int)(position.Y + (float)(height / 2) + velocity.Y), 666, 0, 0f, 1f);
                    }
                }
            }
        }
        bool flag = false;
        float num3 = 0.2f;
        switch (type)
        {
        case 513:
            flag = !Main.player[target].ZoneUndergroundDesert;
            num3 = 0.1f;
            break;
        case 10:
        case 39:
        case 95:
        case 117:
        case 510:
            flag = true;
            break;
        case 621:
            flag = false;
            break;
        }
        if (type >= 13 && type <= 15)
        {
            realLife = -1;
        }
        else if (ai[3] > 0f)
        {
            realLife = (int)ai[3];
        }
        if (target < 0 || target == 255 || Main.player[target].dead || (flag && (double)Main.player[target].position.Y < Main.worldSurface * 16.0))
        {
            TargetClosest();
        }
        if (Main.player[target].dead || (flag && (double)Main.player[target].position.Y < Main.worldSurface * 16.0))
        {
            EncourageDespawn(300);
            if (flag)
            {
                velocity.Y += num3;
            }
        }
        if (type == 621 && Main.dayTime)
        {
            EncourageDespawn(60);
            velocity.Y += 1f;
        }
        if (Main.netMode != 1)
        {
            if (type == 87 && ai[0] == 0f)
            {
                ai[3] = whoAmI;
                realLife = whoAmI;
                int num4 = 0;
                int num5 = whoAmI;
                for (int m = 0; m < 14; m++)
                {
                    int num6 = 89;
                    switch (m)
                    {
                    case 1:
                    case 8:
                        num6 = 88;
                        break;
                    case 11:
                        num6 = 90;
                        break;
                    case 12:
                        num6 = 91;
                        break;
                    case 13:
                        num6 = 92;
                        break;
                    }
                    num4 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), num6, whoAmI);
                    Main.npc[num4].ai[3] = whoAmI;
                    Main.npc[num4].realLife = whoAmI;
                    Main.npc[num4].ai[1] = num5;
                    Main.npc[num4].CopyInteractions(this);
                    Main.npc[num5].ai[0] = num4;
                    NetMessage.SendData(23, -1, -1, null, num4);
                    num5 = num4;
                }
            }
            if (type == 454 && ai[0] == 0f)
            {
                ai[3] = whoAmI;
                realLife = whoAmI;
                int num7 = 0;
                int num8 = whoAmI;
                for (int n = 0; n < 30; n++)
                {
                    int num9 = 456;
                    if ((n - 2) % 4 == 0 && n < 26)
                    {
                        num9 = 455;
                    }
                    else
                    {
                        switch (n)
{
                        case 27:
                            num9 = 457;
                            break;
                        case 28:
                            num9 = 458;
                            break;
                        case 29:
                            num9 = 459;
                            break;
                        }
                    }
                    num7 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), num9, whoAmI);
                    Main.npc[num7].ai[3] = whoAmI;
                    Main.npc[num7].realLife = whoAmI;
                    Main.npc[num7].ai[1] = num8;
                    Main.npc[num7].CopyInteractions(this);
                    Main.npc[num8].ai[0] = num7;
                    NetMessage.SendData(23, -1, -1, null, num7);
                    num8 = num7;
                }
            }
            if (type == 513 && ai[0] == 0f)
            {
                ai[3] = whoAmI;
                realLife = whoAmI;
                int num10 = 0;
                int num11 = whoAmI;
                int num13 = Main.rand.Next(6, 10);
                for (int num14 = 0; num14 < num13; num14++)
                {
                    int num15 = 514;
                    if (num14 == num13 - 1)
                    {
                        num15 = 515;
                    }
                    num10 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), num15, whoAmI);
                    Main.npc[num10].ai[3] = whoAmI;
                    Main.npc[num10].realLife = whoAmI;
                    Main.npc[num10].ai[1] = num11;
                    Main.npc[num10].CopyInteractions(this);
                    Main.npc[num11].ai[0] = num10;
                    NetMessage.SendData(23, -1, -1, null, num10);
                    num11 = num10;
                }
            }
            if (type == 510 && ai[0] == 0f)
            {
                ai[3] = whoAmI;
                realLife = whoAmI;
                int num16 = 0;
                int num17 = whoAmI;
                int num18 = Main.rand.Next(12, 21);
                for (int num19 = 0; num19 < num18; num19++)
                {
                    int num20 = 511;
                    if (num19 == num18 - 1)
                    {
                        num20 = 512;
                    }
                    num16 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), num20, whoAmI);
                    Main.npc[num16].ai[3] = whoAmI;
                    Main.npc[num16].realLife = whoAmI;
                    Main.npc[num16].ai[1] = num17;
                    Main.npc[num16].CopyInteractions(this);
                    Main.npc[num17].ai[0] = num16;
                    NetMessage.SendData(23, -1, -1, null, num16);
                    num17 = num16;
                }
            }
            if (type == 621 && ai[0] == 0f)
            {
                ai[3] = whoAmI;
                realLife = whoAmI;
                int num21 = 0;
                int num22 = whoAmI;
                int num24 = 16;
                for (int num25 = 0; num25 < num24; num25++)
                {
                    int num26 = 622;
                    if (num25 == num24 - 1)
                    {
                        num26 = 623;
                    }
                    num21 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), num26, whoAmI);
                    Main.npc[num21].ai[3] = whoAmI;
                    Main.npc[num21].realLife = whoAmI;
                    Main.npc[num21].ai[1] = num22;
                    Main.npc[num21].CopyInteractions(this);
                    Main.npc[num22].ai[0] = num21;
                    NetMessage.SendData(23, -1, -1, null, num21);
                    num22 = num21;
                }
            }
            else if ((type == 7 || type == 8 || type == 10 || type == 11 || type == 13 || type == 14 || type == 39 || type == 40 || type == 95 || type == 96 || type == 98 || type == 99 || type == 117 || type == 118) && ai[0] == 0f)
            {
                if (type == 7 || type == 10 || type == 13 || type == 39 || type == 95 || type == 98 || type == 117)
                {
                    if (type < 13 || type > 15)
                    {
                        ai[3] = whoAmI;
                        realLife = whoAmI;
                    }
                    ai[2] = Main.rand.Next(8, 13);
                    if (type == 10)
                    {
                        ai[2] = Main.rand.Next(4, 7);
                    }
                    if (type == 13)
                    {
                        ai[2] = GetEaterOfWorldsSegmentsCount();
                    }
                    if (type == 39)
                    {
                        ai[2] = Main.rand.Next(14, 23);
                        if (Main.getGoodWorld)
{
                            ai[2] += 3f;
                            if (Main.remixWorld)
{
                                ai[2] += 4f;
                            }
                        }
                    }
                    if (type == 95)
                    {
                        ai[2] = Main.rand.Next(6, 12);
                    }
                    if (type == 98)
                    {
                        ai[2] = Main.rand.Next(20, 26);
                    }
                    if (type == 117)
                    {
                        ai[2] = Main.rand.Next(3, 6);
                    }
                    if (type == 7 && Main.remixWorld)
                    {
                        ai[2] *= 2f;
                    }
                    ai[0] = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), type + 1, whoAmI);
                    Main.npc[(int)ai[0]].CopyInteractions(this);
                }
                else if ((type == 8 || type == 11 || type == 14 || type == 40 || type == 96 || type == 99 || type == 118) && ai[2] > 0f)
                {
                    ai[0] = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), type, whoAmI);
                    Main.npc[(int)ai[0]].CopyInteractions(this);
                }
                else
                {
                    ai[0] = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), type + 1, whoAmI);
                    Main.npc[(int)ai[0]].CopyInteractions(this);
                }
                if (type < 13 || type > 15)
                {
                    Main.npc[(int)ai[0]].ai[3] = ai[3];
                    Main.npc[(int)ai[0]].realLife = realLife;
                }
                Main.npc[(int)ai[0]].ai[1] = whoAmI;
                Main.npc[(int)ai[0]].ai[2] = ai[2] - 1f;
                netUpdate = true;
            }
            if (type == 412 && ai[0] == 0f)
            {
                ai[3] = whoAmI;
                realLife = whoAmI;
                int num27 = 0;
                int num28 = whoAmI;
                int num29 = 30;
                for (int num30 = 0; num30 < num29; num30++)
                {
                    int num31 = 413;
                    if (num30 == num29 - 1)
                    {
                        num31 = 414;
                    }
                    num27 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), num31, whoAmI);
                    Main.npc[num27].ai[3] = whoAmI;
                    Main.npc[num27].realLife = whoAmI;
                    Main.npc[num27].ai[1] = num28;
                    Main.npc[num27].CopyInteractions(this);
                    Main.npc[num28].ai[0] = num27;
                    NetMessage.SendData(23, -1, -1, null, num27);
                    num28 = num27;
                }
            }
            switch (type)
            {
            case 8:
            case 9:
            case 11:
            case 12:
            case 40:
            case 41:
            case 88:
            case 89:
            case 90:
            case 91:
            case 92:
            case 96:
            case 97:
            case 99:
            case 100:
            case 118:
            case 119:
            case 413:
            case 414:
            case 455:
            case 456:
            case 457:
            case 458:
            case 459:
            case 511:
            case 512:
            case 514:
            case 515:
            case 622:
            case 623:
                if (!Main.npc[(int)ai[1]].active || Main.npc[(int)ai[1]].aiStyle != aiStyle)
                {
                    life = 0;
                    HitEffect();
                    checkDead();
                    active = false;
                    NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
                    return;
                }
                break;
            }
            switch (type)
            {
            case 7:
            case 8:
            case 10:
            case 11:
            case 39:
            case 40:
            case 87:
            case 88:
            case 89:
            case 90:
            case 91:
            case 95:
            case 96:
            case 98:
            case 99:
            case 117:
            case 118:
            case 412:
            case 413:
            case 454:
            case 455:
            case 456:
            case 457:
            case 458:
            case 510:
            case 511:
            case 513:
            case 514:
            case 621:
            case 622:
                if (!Main.npc[(int)ai[0]].active || Main.npc[(int)ai[0]].aiStyle != aiStyle)
                {
                    life = 0;
                    HitEffect();
                    checkDead();
                    active = false;
                    NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
                    return;
                }
                break;
            }
            if (type == 13 || type == 14 || type == 15)
            {
                if (!Main.npc[(int)ai[1]].active && !Main.npc[(int)ai[0]].active)
                {
                    life = 0;
                    HitEffect();
                    checkDead();
                    active = false;
                    NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
                    return;
                }
                if (type == 13 && !Main.npc[(int)ai[0]].active)
                {
                    life = 0;
                    HitEffect();
                    checkDead();
                    active = false;
                    NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
                    return;
                }
                if (type == 15 && !Main.npc[(int)ai[1]].active)
                {
                    life = 0;
                    HitEffect();
                    checkDead();
                    active = false;
                    NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
                    return;
                }
                if (type == 14 && (!Main.npc[(int)ai[1]].active || Main.npc[(int)ai[1]].aiStyle != aiStyle))
                {
                    type = 13;
                    int num32 = whoAmI;
                    float num33 = (float)life / (float)lifeMax;
                    float num35 = ai[0];
                    SetDefaultsKeepPlayerInteraction(type);
                    life = (int)((float)lifeMax * num33);
                    ai[0] = num35;
                    TargetClosest();
                    netUpdate = true;
                    whoAmI = num32;
                    alpha = 0;
                }
                if (type == 14 && (!Main.npc[(int)ai[0]].active || Main.npc[(int)ai[0]].aiStyle != aiStyle))
                {
                    type = 15;
                    int num36 = whoAmI;
                    float num37 = (float)life / (float)lifeMax;
                    float num38 = ai[1];
                    SetDefaultsKeepPlayerInteraction(type);
                    life = (int)((float)lifeMax * num37);
                    ai[1] = num38;
                    TargetClosest();
                    netUpdate = true;
                    whoAmI = num36;
                    alpha = 0;
                }
            }
            if (!active && Main.netMode == 2)
            {
                NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
            }
        }
        int num39 = (int)(position.X / 16f) - 1;
        int num40 = (int)((position.X + (float)width) / 16f) + 2;
        int num41 = (int)(position.Y / 16f) - 1;
        int num42 = (int)((position.Y + (float)height) / 16f) + 2;
        if (num39 < 0)
        {
            num39 = 0;
        }
        if (num40 > Main.maxTilesX)
        {
            num40 = Main.maxTilesX;
        }
        if (num41 < 0)
        {
            num41 = 0;
        }
        if (num42 > Main.maxTilesY)
        {
            num42 = Main.maxTilesY;
        }
        bool flag2 = false;
        if (type >= 87 && type <= 92)
        {
            flag2 = true;
        }
        if (type >= 454 && type <= 459)
        {
            flag2 = true;
        }
        if (type >= 621 && type <= 623)
        {
            flag2 = true;
        }
        if (type >= 412 && type <= 414)
        {
            flag2 = true;
        }
        if (type == 402)
        {
            flag2 = true;
        }
        if (!flag2)
        {
            Vector2 vector2 = default(Vector2);
            for (int num43 = num39; num43 < num40; num43++)
            {
                for (int num44 = num41; num44 < num42; num44++)
                {
                    if (Main.tile[num43, num44] == null || ((!Main.tile[num43, num44].nactive() || (!Main.tileSolid[Main.tile[num43, num44].type] && (!Main.tileSolidTop[Main.tile[num43, num44].type] || Main.tile[num43, num44].frameY != 0))) && Main.tile[num43, num44].liquid <= 64))
                    {
                        continue;
                    }
                    vector2.X = num43 * 16;
                    vector2.Y = num44 * 16;
                    if (position.X + (float)width > vector2.X && position.X < vector2.X + 16f && position.Y + (float)height > vector2.Y && position.Y < vector2.Y + 16f)
                    {
                        flag2 = true;
                        if (Main.rand.Next(100) == 0 && type != 117 && Main.tile[num43, num44].nactive() && Main.tileSolid[Main.tile[num43, num44].type])
{
                            WorldGen.KillTile(num43, num44, fail: true, effectOnly: true);
                        }
                    }
                }
            }
        }
        if (!flag2 && (type == 7 || type == 10 || type == 13 || type == 39 || type == 95 || type == 98 || type == 117 || type == 375 || type == 454 || type == 510 || type == 513 || type == 621))
        {
            Rectangle rectangle = default(Rectangle);
            ((Rectangle)(ref rectangle))._002Ector((int)position.X, (int)position.Y, width, height);
            int num46 = 1000;
            bool flag3 = true;
            Rectangle rectangle2 = default(Rectangle);
            for (int num47 = 0; num47 < 255; num47++)
            {
                if (Main.player[num47].active)
                {
                    ((Rectangle)(ref rectangle2))._002Ector((int)Main.player[num47].position.X - num46, (int)Main.player[num47].position.Y - num46, num46 * 2, num46 * 2);
                    if (((Rectangle)(ref rectangle)).Intersects(rectangle2))
                    {
                        flag3 = false;
                        break;
                    }
                }
            }
            if (flag3)
            {
                flag2 = true;
            }
        }
        if ((type >= 87 && type <= 92) || (type >= 454 && type <= 459) || (type >= 621 && type <= 623))
        {
            if (velocity.X < 0f)
            {
                spriteDirection = 1;
            }
            else if (velocity.X > 0f)
            {
                spriteDirection = -1;
            }
        }
        if (type == 414)
        {
            if (justHit)
            {
                localAI[3] = 3f;
            }
            if (localAI[2] > 0f)
            {
                localAI[2] -= 16f;
                if (localAI[2] == 0f)
                {
                    localAI[2] = -128f;
                }
            }
            else if (localAI[2] < 0f)
            {
                localAI[2] += 16f;
            }
            else if (localAI[3] > 0f)
            {
                localAI[2] = 128f;
                localAI[3] -= 1f;
            }
        }
        if (type == 412)
        {
            position += netOffset;
            Vector2 vector3 = base.Center + (rotation - (float)Math.PI / 2f).ToRotationVector2() * 8f;
            Vector2 vector4 = rotation.ToRotationVector2() * 16f;
            Dust obj = Main.dust[Dust.NewDust(vector3 + vector4, 0, 0, 6, velocity.X, velocity.Y, 100, Color.Transparent, 1f + Main.rand.NextFloat() * 3f)];
            obj.noGravity = true;
            obj.noLight = true;
            obj.position -= new Vector2(4f);
            obj.fadeIn = 1f;
            obj.velocity = Vector2.Zero;
            Dust obj2 = Main.dust[Dust.NewDust(vector3 - vector4, 0, 0, 6, velocity.X, velocity.Y, 100, Color.Transparent, 1f + Main.rand.NextFloat() * 3f)];
            obj2.noGravity = true;
            obj2.noLight = true;
            obj2.position -= new Vector2(4f);
            obj2.fadeIn = 1f;
            obj2.velocity = Vector2.Zero;
            position -= netOffset;
        }
        float num48 = 8f;
        float num49 = 0.07f;
        if (type == 95)
        {
            num48 = 5.5f;
            num49 = 0.045f;
        }
        if (type == 10)
        {
            num48 = 6f;
            num49 = 0.05f;
        }
        if (type == 513)
        {
            num48 = 7f;
            num49 = 0.1f;
        }
        if (type == 7)
        {
            num48 = 9f;
            num49 = 0.1f;
        }
        if (type == 13)
        {
            num48 = 10f;
            num49 = 0.07f;
            if (Main.expertMode)
            {
                num48 = 12f;
                num49 = 0.15f;
            }
            if (Main.getGoodWorld)
            {
                num48 += 4f;
                num49 += 0.05f;
            }
        }
        if (type == 510)
        {
            if (!Main.player[target].dead && Main.player[target].ZoneSandstorm)
            {
                num48 = 16f;
                num49 = 0.35f;
            }
            else
            {
                num48 = 10f;
                num49 = 0.25f;
            }
        }
        if (type == 87)
        {
            num48 = 11f;
            num49 = 0.25f;
        }
        if (type == 621)
        {
            num48 = 15f;
            num49 = 0.45f;
        }
        if (type == 375)
        {
            num48 = 6f;
            num49 = 0.15f;
        }
        if (type == 454)
        {
            num48 = 20f;
            num49 = 0.55f;
        }
        if (type == 402)
        {
            num48 = 9f;
            num49 = 0.3f;
        }
        if (type == 117 && Main.wofNPCIndex >= 0)
        {
            float num80 = (float)Main.npc[Main.wofNPCIndex].life / (float)Main.npc[Main.wofNPCIndex].lifeMax;
            if ((double)num80 < 0.5)
            {
                num48 += 1f;
                num49 += 0.1f;
            }
            if ((double)num80 < 0.25)
            {
                num48 += 1f;
                num49 += 0.1f;
            }
            if ((double)num80 < 0.1)
            {
                num48 += 2f;
                num49 += 0.1f;
            }
        }
        if (type == 39)
        {
            num48 = 9f;
            num49 = 0.1f;
            if (Main.getGoodWorld)
            {
                num48 = 10f;
                num49 = 0.12f;
            }
        }
        Vector2 vector5 = default(Vector2);
        ((Vector2)(ref vector5))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
        float num50 = Main.player[target].position.X + (float)(Main.player[target].width / 2);
        float num51 = Main.player[target].position.Y + (float)(Main.player[target].height / 2);
        if (type == 412)
        {
            num48 = 10f;
            num49 = 0.3f;
            int num52 = -1;
            int num53 = (int)(Main.player[target].Center.X / 16f);
            int num54 = (int)(Main.player[target].Center.Y / 16f);
            for (int num56 = num53 - 2; num56 <= num53 + 2; num56++)
            {
                for (int num57 = num54; num57 <= num54 + 15; num57++)
                {
                    if (WorldGen.SolidTile2(num56, num57))
                    {
                        num52 = num57;
                        break;
                    }
                }
                if (num52 > 0)
                {
                    break;
                }
            }
            if (num52 > 0)
            {
                num52 *= 16;
                float num58 = num52 - 800;
                if (Main.player[target].position.Y > num58)
                {
                    num51 = num58;
                    if (Math.Abs(base.Center.X - Main.player[target].Center.X) < 500f)
                    {
                        num50 = ((!(velocity.X > 0f)) ? (Main.player[target].Center.X - 600f) : (Main.player[target].Center.X + 600f));
                    }
                }
            }
            else
            {
                num48 = 14f;
                num49 = 0.5f;
            }
            float num59 = num48 * 1.3f;
            float num60 = num48 * 0.7f;
            float num61 = ((Vector2)(ref velocity)).Length();
            if (num61 > 0f)
            {
                if (num61 > num59)
                {
                    ((Vector2)(ref velocity)).Normalize();
                    velocity *= num59;
                }
                else if (num61 < num60)
                {
                    ((Vector2)(ref velocity)).Normalize();
                    velocity *= num60;
                }
            }
            if (num52 > 0)
            {
                for (int num62 = 0; num62 < 200; num62++)
                {
                    if (Main.npc[num62].active && Main.npc[num62].type == type && num62 != whoAmI)
                    {
                        Vector2 vector6 = Main.npc[num62].Center - base.Center;
                        if (((Vector2)(ref vector6)).Length() < 400f)
{
                            ((Vector2)(ref vector6)).Normalize();
                            vector6 *= 1000f;
                            num50 -= vector6.X;
                            num51 -= vector6.Y;
                        }
                    }
                }
            }
            else
            {
                for (int num63 = 0; num63 < 200; num63++)
                {
                    if (Main.npc[num63].active && Main.npc[num63].type == type && num63 != whoAmI)
                    {
                        Vector2 vector7 = Main.npc[num63].Center - base.Center;
                        if (((Vector2)(ref vector7)).Length() < 60f)
{
                            ((Vector2)(ref vector7)).Normalize();
                            vector7 *= 200f;
                            num50 -= vector7.X;
                            num51 -= vector7.Y;
                        }
                    }
                }
            }
        }
        num50 = (int)(num50 / 16f) * 16;
        num51 = (int)(num51 / 16f) * 16;
        vector5.X = (int)(vector5.X / 16f) * 16;
        vector5.Y = (int)(vector5.Y / 16f) * 16;
        num50 -= vector5.X;
        num51 -= vector5.Y;
        if (type == 375)
        {
            num50 *= -1f;
            num51 *= -1f;
        }
        float num64 = (float)Math.Sqrt(num50 * num50 + num51 * num51);
        if (ai[1] > 0f && ai[1] < (float)Main.npc.Length)
        {
            try
            {
                vector5 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                num50 = Main.npc[(int)ai[1]].position.X + (float)(Main.npc[(int)ai[1]].width / 2) - vector5.X;
                num51 = Main.npc[(int)ai[1]].position.Y + (float)(Main.npc[(int)ai[1]].height / 2) - vector5.Y;
            }
            catch
            {
            }
            rotation = (float)Math.Atan2(num51, num50) + 1.57f;
            num64 = (float)Math.Sqrt(num50 * num50 + num51 * num51);
            int num65 = width;
            if (type >= 87 && type <= 92)
            {
                num65 = 42;
            }
            if (type >= 454 && type <= 459)
            {
                num65 = 36;
            }
            if (type >= 13 && type <= 15)
            {
                num65 = (int)((float)num65 * scale);
            }
            if (type >= 513 && type <= 515)
            {
                num65 -= 6;
            }
            if (type >= 412 && type <= 414)
            {
                num65 += 6;
            }
            if (type >= 621 && type <= 623)
            {
                num65 = 24;
            }
            if (Main.getGoodWorld && type >= 13 && type <= 15)
            {
                num65 = 62;
            }
            num64 = (num64 - (float)num65) / num64;
            num50 *= num64;
            num51 *= num64;
            velocity = Vector2.Zero;
            position.X += num50;
            position.Y += num51;
            if (type >= 87 && type <= 92)
            {
                if (num50 < 0f)
                {
                    spriteDirection = 1;
                }
                else if (num50 > 0f)
                {
                    spriteDirection = -1;
                }
            }
            if (type >= 454 && type <= 459)
            {
                if (num50 < 0f)
                {
                    spriteDirection = 1;
                }
                else if (num50 > 0f)
                {
                    spriteDirection = -1;
                }
            }
            if (type >= 621 && type <= 623)
            {
                if (num50 < 0f)
                {
                    spriteDirection = 1;
                }
                else if (num50 > 0f)
                {
                    spriteDirection = -1;
                }
            }
        }
        else
        {
            if (!flag2)
            {
                TargetClosest();
                if (type == 39 && velocity.Y < 0f)
                {
                    velocity.Y += 0.08f;
                }
                else
                {
                    velocity.Y += 0.11f;
                }
                if (velocity.Y > num48)
                {
                    velocity.Y = num48;
                }
                if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num48 * 0.4)
                {
                    if (velocity.X < 0f)
                    {
                        velocity.X -= num49 * 1.1f;
                    }
                    else
                    {
                        velocity.X += num49 * 1.1f;
                    }
                }
                else if (velocity.Y == num48)
                {
                    if (velocity.X < num50)
                    {
                        velocity.X += num49;
                    }
                    else if (velocity.X > num50)
                    {
                        velocity.X -= num49;
                    }
                }
                else if (velocity.Y > 4f)
                {
                    if (velocity.X < 0f)
                    {
                        velocity.X += num49 * 0.9f;
                    }
                    else
                    {
                        velocity.X -= num49 * 0.9f;
                    }
                }
            }
            else
            {
                if (type != 621 && type != 87 && type != 117 && type != 454 && type != 412 && soundDelay == 0)
                {
                    float num67 = num64 / 40f;
                    if (num67 < 10f)
                    {
                        num67 = 10f;
                    }
                    if (num67 > 20f)
                    {
                        num67 = 20f;
                    }
                    soundDelay = (int)num67;
                    SoundEngine.PlaySound(15, (int)position.X, (int)position.Y);
                }
                num64 = (float)Math.Sqrt(num50 * num50 + num51 * num51);
                float num68 = Math.Abs(num50);
                float num69 = Math.Abs(num51);
                float num70 = num48 / num64;
                num50 *= num70;
                num51 *= num70;
                bool flag4 = false;
                if ((type == 7 || type == 13) && ((!Main.player[target].ZoneCorrupt && !Main.player[target].ZoneCrimson) || Main.player[target].dead))
                {
                    flag4 = true;
                }
                if ((type == 513 && (double)Main.player[target].position.Y < Main.worldSurface * 16.0 && !Main.player[target].ZoneSandstorm && !Main.player[target].ZoneUndergroundDesert) || Main.player[target].dead)
                {
                    flag4 = true;
                }
                if ((type == 510 && (double)Main.player[target].position.Y < Main.worldSurface * 16.0 && !Main.player[target].ZoneSandstorm && !Main.player[target].ZoneUndergroundDesert) || Main.player[target].dead)
                {
                    flag4 = true;
                }
                if (flag4)
                {
                    bool flag5 = true;
                    for (int num71 = 0; num71 < 255; num71++)
                    {
                        if (Main.player[num71].active && !Main.player[num71].dead && Main.player[num71].ZoneCorrupt)
{
                            flag5 = false;
                        }
                    }
                    if (flag5)
                    {
                        if (Main.netMode != 1 && (double)(position.Y / 16f) > (Main.rockLayer + (double)Main.maxTilesY) / 2.0)
{
                            active = false;
                            int num72 = (int)ai[0];
                            while (num72 > 0 && num72 < 200 && Main.npc[num72].active && Main.npc[num72].aiStyle == aiStyle)
{
                                int num81 = (int)Main.npc[num72].ai[0];
                                Main.npc[num72].active = false;
                                life = 0;
                                if (Main.netMode == 2)
{
                                    NetMessage.SendData(23, -1, -1, null, num72);
                                }
                                num72 = num81;
                            }
                            if (Main.netMode == 2)
{
                                NetMessage.SendData(23, -1, -1, null, whoAmI);
                            }
                        }
                        num50 = 0f;
                        num51 = num48;
                    }
                }
                bool flag6 = false;
                if (type == 87)
                {
                    if (((velocity.X > 0f && num50 < 0f) || (velocity.X < 0f && num50 > 0f) || (velocity.Y > 0f && num51 < 0f) || (velocity.Y < 0f && num51 > 0f)) && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > num49 / 2f && num64 < 300f)
                    {
                        flag6 = true;
                        if (Math.Abs(velocity.X) + Math.Abs(velocity.Y) < num48)
{
                            velocity *= 1.1f;
                        }
                    }
                    if (position.Y > Main.player[target].position.Y || (double)(Main.player[target].position.Y / 16f) > Main.worldSurface || Main.player[target].dead)
                    {
                        flag6 = true;
                        if (Math.Abs(velocity.X) < num48 / 2f)
{
                            if (velocity.X == 0f)
{
                                velocity.X -= direction;
                            }
                            velocity.X *= 1.1f;
                        }
                        else if (velocity.Y > 0f - num48)
{
                            velocity.Y -= num49;
                        }
                    }
                }
                if (type == 454 || type == 621)
                {
                    float num73 = 300f;
                    if (type == 621)
                    {
                        num73 = 120f;
                    }
                    if (((velocity.X > 0f && num50 < 0f) || (velocity.X < 0f && num50 > 0f) || (velocity.Y > 0f && num51 < 0f) || (velocity.Y < 0f && num51 > 0f)) && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > num49 / 2f && num64 < num73)
                    {
                        flag6 = true;
                        if (Math.Abs(velocity.X) + Math.Abs(velocity.Y) < num48)
{
                            velocity *= 1.1f;
                        }
                    }
                    if (position.Y > Main.player[target].position.Y || Main.player[target].dead)
                    {
                        flag6 = true;
                        if (Math.Abs(velocity.X) < num48 / 2f)
{
                            if (velocity.X == 0f)
{
                                velocity.X -= direction;
                            }
                            velocity.X *= 1.1f;
                        }
                        else if (velocity.Y > 0f - num48)
{
                            velocity.Y -= num49;
                        }
                    }
                }
                if (!flag6)
                {
                    if ((velocity.X > 0f && num50 > 0f) || (velocity.X < 0f && num50 < 0f) || (velocity.Y > 0f && num51 > 0f) || (velocity.Y < 0f && num51 < 0f))
                    {
                        if (velocity.X < num50)
{
                            velocity.X += num49;
                        }
                        else if (velocity.X > num50)
{
                            velocity.X -= num49;
                        }
                        if (velocity.Y < num51)
{
                            velocity.Y += num49;
                        }
                        else if (velocity.Y > num51)
{
                            velocity.Y -= num49;
                        }
                        if ((double)Math.Abs(num51) < (double)num48 * 0.2 && ((velocity.X > 0f && num50 < 0f) || (velocity.X < 0f && num50 > 0f)))
{
                            if (velocity.Y > 0f)
{
                                velocity.Y += num49 * 2f;
                            }
                            else
{
                                velocity.Y -= num49 * 2f;
                            }
                        }
                        if ((double)Math.Abs(num50) < (double)num48 * 0.2 && ((velocity.Y > 0f && num51 < 0f) || (velocity.Y < 0f && num51 > 0f)))
{
                            if (velocity.X > 0f)
{
                                velocity.X += num49 * 2f;
                            }
                            else
{
                                velocity.X -= num49 * 2f;
                            }
                        }
                    }
                    else if (num68 > num69)
                    {
                        if (velocity.X < num50)
{
                            velocity.X += num49 * 1.1f;
                        }
                        else if (velocity.X > num50)
{
                            velocity.X -= num49 * 1.1f;
                        }
                        if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num48 * 0.5)
{
                            if (velocity.Y > 0f)
{
                                velocity.Y += num49;
                            }
                            else
{
                                velocity.Y -= num49;
                            }
                        }
                    }
                    else
                    {
                        if (velocity.Y < num51)
{
                            velocity.Y += num49 * 1.1f;
                        }
                        else if (velocity.Y > num51)
{
                            velocity.Y -= num49 * 1.1f;
                        }
                        if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num48 * 0.5)
{
                            if (velocity.X > 0f)
{
                                velocity.X += num49;
                            }
                            else
{
                                velocity.X -= num49;
                            }
                        }
                    }
                }
            }
            rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
            if (type == 7 || type == 10 || type == 13 || type == 39 || type == 95 || type == 98 || type == 117 || type == 510 || type == 513 || type == 621)
            {
                if (flag2)
                {
                    if (localAI[0] != 1f)
                    {
                        netUpdate = true;
                    }
                    localAI[0] = 1f;
                }
                else
                {
                    if (localAI[0] != 0f)
                    {
                        netUpdate = true;
                    }
                    localAI[0] = 0f;
                }
                if (((velocity.X > 0f && oldVelocity.X < 0f) || (velocity.X < 0f && oldVelocity.X > 0f) || (velocity.Y > 0f && oldVelocity.Y < 0f) || (velocity.Y < 0f && oldVelocity.Y > 0f)) && !justHit)
                {
                    netUpdate = true;
                }
            }
            if (type == 454)
            {
                float num74 = Vector2.Distance(Main.player[target].Center, base.Center);
                int num75 = 0;
                if (Vector2.Normalize(Main.player[target].Center - base.Center).ToRotation().AngleTowards(velocity.ToRotation(), (float)Math.PI / 2f) == velocity.ToRotation() && num74 < 350f)
                {
                    num75 = 4;
                }
                if ((double)num75 > frameCounter)
                {
                    frameCounter += 1.0;
                }
                if ((double)num75 < frameCounter)
                {
                    frameCounter -= 1.0;
                }
                if (frameCounter < 0.0)
                {
                    frameCounter = 0.0;
                }
                if (frameCounter > 4.0)
                {
                    frameCounter = 4.0;
                }
            }
        }
        if (type < 13 || type > 15 || (type != 13 && (type == 13 || Main.npc[(int)ai[1]].alpha >= 85)))
        {
            return;
        }
        if (alpha > 0 && life > 0)
        {
            for (int num77 = 0; num77 < 2; num77++)
            {
                int num78 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 14, 0f, 0f, 100, default(Color), 2f);
                Main.dust[num78].noGravity = true;
                Main.dust[num78].noLight = true;
            }
        }
        Vector2 val = position - oldPosition;
        if (((Vector2)(ref val)).Length() > 2f)
        {
            alpha -= 42;
            if (alpha < 0)
            {
                alpha = 0;
            }
        }
    }
References Terraria.Entity.active, Terraria.NPC.ai, Terraria.NPC.aiStyle, Terraria.NPC.alpha, Terraria.Collision.CanHitLine(), Terraria.NPC.checkDead(), Terraria.NPC.CopyInteractions(), Terraria.Main.dayTime, Terraria.Entity.direction, Terraria.NPC.dontTakeDamage, Terraria.Main.dust, Terraria.NPC.EncourageDespawn(), Terraria.Main.expertMode, Terraria.NPC.frameCounter, Terraria.NPC.GetEaterOfWorldsSegmentsCount(), Terraria.Main.getGoodWorld, Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.Entity.height, Terraria.NPC.HitEffect(), Terraria.WorldGen.InWorld(), Terraria.ID.SoundID.Item119, Terraria.NPC.justHit, Terraria.WorldGen.KillTile(), Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.NPC.netOffset, Terraria.NPC.netUpdate, Terraria.Dust.NewDust(), Terraria.NPC.NewNPC(), Terraria.Main.npc, Terraria.ID.SoundID.NPCDeath13, Terraria.Entity.oldPosition, Terraria.Entity.oldVelocity, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.realLife, Terraria.Utils.Remap(), Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.NPC.rotation, Terraria.NPC.scale, Terraria.NetMessage.SendData(), Terraria.NPC.SetDefaultsKeepPlayerInteraction(), Terraria.WorldGen.SolidTile2(), Terraria.NPC.soundDelay, Terraria.NPC.SpawnStardustMark_StardustWorm(), Terraria.NPC.spriteDirection, Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.NPC.type, Terraria.Entity.velocity, Terraria.Entity.whoAmI, Terraria.Entity.width, Terraria.Main.wofNPCIndex, and Terraria.Main.worldSurface.
Referenced by Terraria.NPC.VanillaAI_Inner().