TModLoader: Terraria.NPC.AI_108_DivingFlyer
AI_108_DivingFlyer()
void Terraria.NPC.AI_108_DivingFlyer () inline private
    {
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_0530: Unknown result type (might be due to invalid IL or missing references)
        //IL_0535: Unknown result type (might be due to invalid IL or missing references)
        //IL_0539: Unknown result type (might be due to invalid IL or missing references)
        //IL_053e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0540: Unknown result type (might be due to invalid IL or missing references)
        //IL_0545: Unknown result type (might be due to invalid IL or missing references)
        //IL_0547: Unknown result type (might be due to invalid IL or missing references)
        //IL_0549: Unknown result type (might be due to invalid IL or missing references)
        //IL_054f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0554: Unknown result type (might be due to invalid IL or missing references)
        //IL_0559: Unknown result type (might be due to invalid IL or missing references)
        //IL_0562: Unknown result type (might be due to invalid IL or missing references)
        //IL_0564: Unknown result type (might be due to invalid IL or missing references)
        //IL_056b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0570: Unknown result type (might be due to invalid IL or missing references)
        //IL_0572: Unknown result type (might be due to invalid IL or missing references)
        //IL_0574: Unknown result type (might be due to invalid IL or missing references)
        //IL_057b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0580: Unknown result type (might be due to invalid IL or missing references)
        //IL_0583: Unknown result type (might be due to invalid IL or missing references)
        //IL_058c: Unknown result type (might be due to invalid IL or missing references)
        //IL_072c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0733: Unknown result type (might be due to invalid IL or missing references)
        //IL_0738: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_099a: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_088a: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_08de: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0320: Unknown result type (might be due to invalid IL or missing references)
        //IL_032d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0332: Unknown result type (might be due to invalid IL or missing references)
        //IL_0338: Unknown result type (might be due to invalid IL or missing references)
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_0348: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b96: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0606: Unknown result type (might be due to invalid IL or missing references)
        //IL_0630: Unknown result type (might be due to invalid IL or missing references)
        //IL_0642: Unknown result type (might be due to invalid IL or missing references)
        //IL_064d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0966: Unknown result type (might be due to invalid IL or missing references)
        //IL_0948: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_081b: Unknown result type (might be due to invalid IL or missing references)
        //IL_083a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a71: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a75: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0acf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0adb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cce: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c70: Unknown result type (might be due to invalid IL or missing references)
        //IL_132c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d92: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e09: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e44: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e84: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ebd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f79: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f83: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0faa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffc: Unknown result type (might be due to invalid IL or missing references)
        //IL_101b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1021: Unknown result type (might be due to invalid IL or missing references)
        //IL_1038: Unknown result type (might be due to invalid IL or missing references)
        //IL_103d: Unknown result type (might be due to invalid IL or missing references)
        //IL_104b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1051: Unknown result type (might be due to invalid IL or missing references)
        //IL_105e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1064: Unknown result type (might be due to invalid IL or missing references)
        //IL_1066: Unknown result type (might be due to invalid IL or missing references)
        //IL_1072: Unknown result type (might be due to invalid IL or missing references)
        //IL_107c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1081: Unknown result type (might be due to invalid IL or missing references)
        //IL_1086: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_10e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1102: Unknown result type (might be due to invalid IL or missing references)
        //IL_1108: Unknown result type (might be due to invalid IL or missing references)
        //IL_111f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1124: Unknown result type (might be due to invalid IL or missing references)
        //IL_1132: Unknown result type (might be due to invalid IL or missing references)
        //IL_1138: Unknown result type (might be due to invalid IL or missing references)
        //IL_1145: Unknown result type (might be due to invalid IL or missing references)
        //IL_114b: Unknown result type (might be due to invalid IL or missing references)
        //IL_114d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1159: Unknown result type (might be due to invalid IL or missing references)
        //IL_1163: Unknown result type (might be due to invalid IL or missing references)
        //IL_1168: Unknown result type (might be due to invalid IL or missing references)
        //IL_116d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1189: Unknown result type (might be due to invalid IL or missing references)
        //IL_1193: Unknown result type (might be due to invalid IL or missing references)
        //IL_1198: Unknown result type (might be due to invalid IL or missing references)
        //IL_11b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1202: Unknown result type (might be due to invalid IL or missing references)
        //IL_1207: Unknown result type (might be due to invalid IL or missing references)
        //IL_120e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1214: Unknown result type (might be due to invalid IL or missing references)
        //IL_1239: Unknown result type (might be due to invalid IL or missing references)
        //IL_123e: Unknown result type (might be due to invalid IL or missing references)
        //IL_124c: Unknown result type (might be due to invalid IL or missing references)
        //IL_125c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1268: Unknown result type (might be due to invalid IL or missing references)
        //IL_1272: Unknown result type (might be due to invalid IL or missing references)
        //IL_1277: Unknown result type (might be due to invalid IL or missing references)
        //IL_127c: Unknown result type (might be due to invalid IL or missing references)
        //IL_128a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1294: Unknown result type (might be due to invalid IL or missing references)
        //IL_1299: Unknown result type (might be due to invalid IL or missing references)
        rotation = velocity.ToRotation();
        float num = 0.4f;
        float num12 = 10f;
        float num22 = 200f;
        float num23 = 750f;
        float num24 = 30f;
        float num25 = 30f;
        float num26 = 0.95f;
        int num27 = 50;
        float num28 = 14f;
        float num2 = 30f;
        float num3 = 100f;
        float num4 = 20f;
        float num5 = 0f;
        float num6 = 7f;
        bool flag = true;
        bool flag2 = true;
        int num7 = 120;
        bool flag3 = false;
        bool flag4 = false;
        float num8 = 0.05f;
        float num9 = 0f;
        bool flag5 = false;
        switch (type)
        {
        case 558:
        case 559:
        case 560:
            flag4 = true;
            num = 0.7f;
            if (type == 559)
            {
                num = 0.5f;
            }
            if (type == 560)
            {
                num = 0.2f;
            }
            num12 = 3f;
            num22 = 400f;
            num23 = 500f;
            num24 = 90f;
            num25 = 20f;
            num26 = 0.95f;
            num27 = 0;
            num28 = 8f;
            num2 = 30f;
            num3 = 150f;
            num4 = 60f;
            num5 = 0.05f;
            num6 = 6f;
            flag2 = false;
            flag5 = true;
            break;
        case 574:
        case 575:
            flag4 = true;
            num = 0.6f;
            if (type == 575)
            {
                num = 0.4f;
            }
            num12 = 4f;
            num22 = 400f;
            num23 = 500f;
            num24 = 90f;
            num25 = 30f;
            num26 = 0.95f;
            num27 = 3;
            num28 = 8f;
            num2 = 30f;
            num3 = 150f;
            num4 = 10f;
            num5 = 0.05f;
            num6 = 0f;
            num9 = -0.1f;
            flag3 = true;
            flag5 = true;
            break;
        }
        NPCUtils.TargetClosestOldOnesInvasion(this);
        NPCAimedTarget targetData = GetTargetData();
        Vector2 center3;
        if (flag5)
        {
            if (localAI[0] == 0f)
            {
                alpha = 255;
            }
            if (localAI[0] == 30f)
            {
                SoundEngine.PlayTrackedSound(in SoundID.DD2_EtherianPortalSpawnEnemy, base.Center);
            }
            if (localAI[0] < 60f)
            {
                localAI[0] += 1f;
                alpha -= 5;
                if (alpha < 0)
                {
                    alpha = 0;
                }
                int num10 = (int)localAI[0] / 10;
                center3 = base.Size;
                float num11 = ((Vector2)(ref center3)).Length() / 2f;
                num11 /= 20f;
                int maxValue = 5;
                if (type == 576 || type == 577)
                {
                    maxValue = 1;
                }
                for (int i = 0; i < num10; i++)
                {
                    if (Main.rand.Next(maxValue) == 0)
                    {
                        Dust dust = Dust.NewDustDirect(position, width, height, 27, velocity.X * 1f, 0f, 100);
                        dust.scale = 0.55f;
                        dust.fadeIn = 0.7f;
                        dust.velocity *= 0.1f * num11;
                        dust.velocity += velocity;
                    }
                }
            }
        }
        if (flag4)
        {
            for (int j = 0; j < 200; j++)
            {
                if (j != whoAmI && Main.npc[j].active && Main.npc[j].type == type && Math.Abs(position.X - Main.npc[j].position.X) + Math.Abs(position.Y - Main.npc[j].position.Y) < (float)width)
                {
                    if (position.X < Main.npc[j].position.X)
                    {
                        velocity.X -= num8;
                    }
                    else
                    {
                        velocity.X += num8;
                    }
                    if (position.Y < Main.npc[j].position.Y)
                    {
                        velocity.Y -= num8;
                    }
                    else
                    {
                        velocity.Y += num8;
                    }
                }
            }
        }
        if (Math.Sign(velocity.X) != 0)
        {
            spriteDirection = -Math.Sign(velocity.X);
        }
        if (rotation < -(float)Math.PI / 2f)
        {
            rotation += (float)Math.PI;
        }
        if (rotation > (float)Math.PI / 2f)
        {
            rotation -= (float)Math.PI;
        }
        num5 *= num4;
        if (Main.expertMode)
        {
            num *= Main.GameModeInfo.KnockbackToEnemiesMultiplier;
        }
        if (ai[0] == 0f)
        {
            knockBackResist = num;
            float num13 = num12;
            Vector2 center = base.Center;
            Vector2 vector = targetData.Center - center;
            Vector2 vector2 = vector - Vector2.UnitY * num22;
            float num29 = ((Vector2)(ref vector)).Length();
            vector = Vector2.Normalize(vector) * num13;
            vector2 = Vector2.Normalize(vector2) * num13;
            bool flag6 = Collision.CanHit(base.Center, 1, 1, targetData.Center, 1, 1);
            if (ai[3] >= (float)num7)
            {
                flag6 = true;
            }
            float num14 = 8f;
            flag6 = flag6 && vector.ToRotation() > (float)Math.PI / num14 && vector.ToRotation() < (float)Math.PI - (float)Math.PI / num14;
            if (num29 > num23 || !flag6)
            {
                velocity.X = (velocity.X * (num24 - 1f) + vector2.X) / num24;
                velocity.Y = (velocity.Y * (num24 - 1f) + vector2.Y) / num24;
                if (targetData.Center.Y < base.Center.Y)
                {
                    velocity.Y -= 0.2f;
                    if (velocity.Y < -10f)
                    {
                        velocity.Y = -10f;
                    }
                }
                if (!flag6)
                {
                    ai[3] += 1f;
                    if (ai[3] == (float)num7)
                    {
                        netUpdate = true;
                    }
                }
                else
                {
                    ai[3] = 0f;
                }
            }
            else
            {
                ai[0] = 1f;
                ai[2] = vector.X;
                ai[3] = vector.Y;
                netUpdate = true;
            }
        }
        else if (ai[0] == 1f)
        {
            knockBackResist = 0f;
            velocity *= num26;
            velocity.Y += num9;
            ai[1] += 1f;
            if (ai[1] == num25)
            {
                if (type == 558 || type == 559 || type == 560)
                {
                    localAI[1] = SoundEngine.PlayTrackedSound(in SoundID.DD2_WyvernDiveDown, base.Center).ToFloat();
                    if (Main.rand.Next(5) == 0)
                    {
                        localAI[2] = SoundEngine.PlayTrackedSound(in SoundID.DD2_WyvernScream, base.Center).ToFloat();
                    }
                }
                else if (type == 574 || type == 575)
                {
                    localAI[1] = SoundEngine.PlayTrackedSound(in SoundID.DD2_KoboldFlyerChargeScream, base.Center).ToFloat();
                    SoundEngine.PlayTrackedSound(in SoundID.DD2_KoboldIgnite, base.Center);
                }
            }
            if (ai[1] >= num25)
            {
                ai[0] = 2f;
                ai[1] = 0f;
                netUpdate = true;
                Vector2 vector3 = new Vector2(ai[2], ai[3]) + new Vector2((float)Main.rand.Next(-num27, num27 + 1), (float)Main.rand.Next(-num27, num27 + 1)) * 0.04f;
                ((Vector2)(ref vector3)).Normalize();
                vector3 = (velocity = vector3 * num28);
            }
        }
        else if (ai[0] == 2f)
        {
            if (ai[1] >= 20f && (type == 574 || type == 575))
            {
                ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[2]));
                if (activeSound == null)
                {
                    localAI[2] = SoundEngine.PlayTrackedSound(in SoundID.DD2_KoboldIgniteLoop, base.Center).ToFloat();
                }
                else
                {
                    activeSound.Position = base.Center;
                }
            }
            knockBackResist = 0f;
            float num15 = num2;
            ai[1] += 1f;
            bool flag7 = Vector2.Distance(base.Center, targetData.Center) > num3 && base.Center.Y > targetData.Center.Y;
            if (flag3)
            {
                flag7 = false;
            }
            if ((ai[1] >= num15 && flag7) || ((Vector2)(ref velocity)).Length() < num6)
            {
                ai[0] = 0f;
                ai[1] = 0f;
                ai[2] = 0f;
                ai[3] = 0f;
                velocity /= 2f;
                netUpdate = true;
                if (flag)
                {
                    ai[1] = 45f;
                    ai[0] = 4f;
                }
            }
            else
            {
                Vector2 center2 = base.Center;
                Vector2 vector4 = targetData.Center - center2;
                ((Vector2)(ref vector4)).Normalize();
                if (vector4.HasNaNs())
                {
                    ((Vector2)(ref vector4))._002Ector((float)direction, 0f);
                }
                velocity = (velocity * (num4 - 1f) + vector4 * (((Vector2)(ref velocity)).Length() + num5)) / num4;
            }
            if (flag2 && Collision.SolidCollision(position, width, height))
            {
                ai[0] = 3f;
                ai[1] = 0f;
                ai[2] = 0f;
                ai[3] = 0f;
                netUpdate = true;
            }
        }
        else if (ai[0] == 4f)
        {
            ai[1] -= 3f;
            if (ai[1] <= 0f)
            {
                ai[0] = 0f;
                ai[1] = 0f;
                netUpdate = true;
            }
            velocity *= 0.95f;
        }
        ActiveSound activeSound2 = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
        if (activeSound2 != null)
        {
            activeSound2.Position = base.Center;
        }
        else
        {
            localAI[1] = SlotId.Invalid.ToFloat();
        }
        if (type == 558 || type == 559 || type == 560)
        {
            activeSound2 = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[2]));
            if (activeSound2 != null)
            {
                activeSound2.Position = base.Center;
            }
            else
            {
                localAI[2] = SlotId.Invalid.ToFloat();
            }
        }
        if (flag2 && ai[0] != 3f && Vector2.Distance(base.Center, targetData.Center) < 64f)
        {
            ai[0] = 3f;
            ai[1] = 0f;
            ai[2] = 0f;
            ai[3] = 0f;
            netUpdate = true;
        }
        if (ai[0] != 3f)
        {
            return;
        }
        position = base.Center;
        width = (height = 192);
        position.X -= width / 2;
        position.Y -= height / 2;
        velocity = Vector2.Zero;
        damage = GetAttackDamage_ScaledByStrength(80f);
        alpha = 255;
        if (ai[1] == 0f && (type == 574 || type == 575))
        {
            for (int k = 0; k < 4; k++)
            {
                int num16 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num16].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * (float)width / 2f;
            }
            for (int l = 0; l < 20; l++)
            {
                int num17 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 200, default(Color), 3.7f);
                Main.dust[num17].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * (float)width / 2f;
                Main.dust[num17].noGravity = true;
                Dust obj = Main.dust[num17];
                obj.velocity *= 3f;
                num17 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num17].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * (float)width / 4f;
                Dust obj2 = Main.dust[num17];
                obj2.velocity *= 2f;
                Main.dust[num17].noGravity = true;
                Main.dust[num17].fadeIn = 2.5f;
            }
            for (int m = 0; m < 6; m++)
            {
                int num18 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 0, default(Color), 2.7f);
                Dust obj3 = Main.dust[num18];
                Vector2 center4 = base.Center;
                Vector2 spinningpoint = Vector2.UnitX.RotatedByRandom(3.1415927410125732);
                double radians = velocity.ToRotation();
                center3 = default(Vector2);
                obj3.position = center4 + spinningpoint.RotatedBy(radians, center3) * (float)width / 2f;
                Main.dust[num18].noGravity = true;
                Dust obj4 = Main.dust[num18];
                obj4.velocity *= 3f;
            }
            for (int n = 0; n < 12; n++)
            {
                int num19 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 0, default(Color), 1.5f);
                Dust obj5 = Main.dust[num19];
                Vector2 center5 = base.Center;
                Vector2 spinningpoint2 = Vector2.UnitX.RotatedByRandom(3.1415927410125732);
                double radians2 = velocity.ToRotation();
                center3 = default(Vector2);
                obj5.position = center5 + spinningpoint2.RotatedBy(radians2, center3) * (float)width / 2f;
                Main.dust[num19].noGravity = true;
                Dust obj6 = Main.dust[num19];
                obj6.velocity *= 3f;
            }
            for (int num20 = 0; num20 < 5; num20++)
            {
                Vector2 val = position + new Vector2((float)(width * Main.rand.Next(100)) / 100f, (float)(height * Main.rand.Next(100)) / 100f) - Vector2.One * 10f;
                center3 = default(Vector2);
                int num21 = Gore.NewGore(val, center3, Main.rand.Next(61, 64));
                Main.gore[num21].position = base.Center + Vector2.UnitY.RotatedByRandom(3.1415927410125732) * (float)Main.rand.NextDouble() * (float)width / 2f;
                Gore obj7 = Main.gore[num21];
                obj7.velocity *= 0.3f;
                Main.gore[num21].velocity.X += (float)Main.rand.Next(-10, 11) * 0.05f;
                Main.gore[num21].velocity.Y += (float)Main.rand.Next(-10, 11) * 0.05f;
            }
        }
        ai[1] += 1f;
        if (ai[1] >= 3f)
        {
            SoundEngine.PlaySound(in SoundID.Item14, position);
            life = 0;
            HitEffect();
            active = false;
        }
    }
References Terraria.Entity.active, Terraria.NPC.ai, Terraria.NPC.alpha, Terraria.Collision.CanHit(), Terraria.NPC.damage, Terraria.ID.SoundID.DD2_EtherianPortalSpawnEnemy, Terraria.ID.SoundID.DD2_KoboldFlyerChargeScream, Terraria.ID.SoundID.DD2_KoboldIgnite, Terraria.ID.SoundID.DD2_KoboldIgniteLoop, Terraria.ID.SoundID.DD2_WyvernDiveDown, Terraria.ID.SoundID.DD2_WyvernScream, Terraria.Entity.direction, Terraria.Main.dust, Terraria.Main.expertMode, Terraria.Main.GameModeInfo, Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.NPC.GetAttackDamage_ScaledByStrength(), Terraria.NPC.GetTargetData(), Terraria.Main.gore, Terraria.Entity.height, Terraria.NPC.HitEffect(), Terraria.ID.SoundID.Item14, Terraria.NPC.knockBackResist, Terraria.NPC.life, Terraria.NPC.localAI, Terraria.NPC.netUpdate, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Gore.NewGore(), Terraria.Main.npc, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.rotation, Terraria.Collision.SolidCollision(), Terraria.NPC.spriteDirection, Terraria.Utilities.NPCUtils.TargetClosestOldOnesInvasion(), Terraria.NPC.type, Terraria.Entity.velocity, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.NPC.VanillaAI_Inner().