TModLoader: Terraria.NPC.StrikeNPC
StrikeNPC() [1/2]
int Terraria.NPC.StrikeNPC (HitInfo hit, bool fromNet = false, bool noPlayerInteraction = false) inline
Directly deals damage to the NPC, spawns combat text, plays hit sound, deals knockback based on the provided T:Terraria.NPC.HitInfo
Calls M:Terraria.NPC.HitEffect(Terraria.NPC.HitInfo) and associated hooks after dealing damage.
Calls M:Terraria.NPC.checkDead
Does not automatically send packets. Use M:Terraria.NetMessage.SendStrikeNPC(Terraria.NPC,Terraria.NPC.HitInfo@,System.Int32) to synchronize hits.
Parameters
hit The parameters of the hit. Normally obtained via T:Terraria.NPC.HitModifiers or M:Terraria.NPC.CalculateHitInfo(System.Int32,System.Int32,System.Boolean,System.Single,Terraria.ModLoader.DamageClass,System.Boolean,System.Single)
fromNet true if this strike came from another client over the network. Just changes the combat text to be darker in color.
noPlayerInteraction Prevents M:Terraria.NPC.PlayerInteraction(System.Int32) from being called in single player. In multiplayer, player interaction is handled by the server.
Returns
The actual health lost by the NPC. Normally this is P:Terraria.NPC.HitInfo.Damage but it is capped at the current health of the NPC, and represents the actual damage dealt in the case of F:Terraria.NPC.HitInfo.InstantKill
    {
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_0438: Unknown result type (might be due to invalid IL or missing references)
        //IL_043e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0846: Unknown result type (might be due to invalid IL or missing references)
        bool flag = Main.netMode == 0;
        flag = flag && !noPlayerInteraction;
        if (!active || life <= 0)
        {
            return 0;
        }
        double num = hit.Damage;
        bool crit = hit.Crit;
        int hitDirection = hit.HitDirection;
        if (hit.InstantKill)
        {
            num = ((realLife > 0) ? Main.npc[realLife].life : life);
        }
        if (!hit.HideCombatText && !hit.InstantKill && lifeMax > 1 && !HideStrikeDamage)
        {
            if (friendly)
            {
                Color color = (crit ? CombatText.DamagedFriendlyCrit : CombatText.DamagedFriendly);
                CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), color, (int)num, crit);
            }
            else
            {
                Color color2 = (crit ? CombatText.DamagedHostileCrit : CombatText.DamagedHostile);
                if (fromNet)
                {
                    color2 = (crit ? CombatText.OthersDamagedHostileCrit : CombatText.OthersDamagedHostile);
                }
                CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), color2, (int)num, crit);
            }
        }
        if (num >= 1.0)
        {
            if (flag)
            {
                PlayerInteraction(Main.myPlayer);
            }
            justHit = true;
            if ((type == 438 || type == 379) && Main.netMode != 1)
            {
                int num2 = (int)(0f - ai[3] - 1f);
                if (num2 > -1 && Main.npc[num2].localAI[0] == 0f)
                {
                    Main.npc[num2].localAI[0] = 1f;
                }
            }
            if (townNPC)
            {
                if (aiStyle == 7 && (ai[0] == 3f || ai[0] == 4f || ai[0] == 16f || ai[0] == 17f))
                {
                    NPC nPC = Main.npc[(int)ai[2]];
                    if (nPC.active)
                    {
                        nPC.ai[0] = 1f;
                        nPC.ai[1] = 300 + Main.rand.Next(300);
                        nPC.ai[2] = 0f;
                        nPC.localAI[3] = 0f;
                        nPC.direction = hitDirection;
                        nPC.netUpdate = true;
                    }
                }
                ai[0] = 1f;
                ai[1] = 300 + Main.rand.Next(300);
                ai[2] = 0f;
                localAI[3] = 0f;
                direction = hitDirection;
                netUpdate = true;
            }
            if (aiStyle == 8 && Main.netMode != 1)
            {
                if (type == 172)
                {
                    ai[0] = 450f;
                }
                else if (type == 283 || type == 284)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        ai[0] = 390f;
                        netUpdate = true;
                    }
                }
                else if (type == 533)
                {
                    if (Main.rand.Next(3) != 0)
                    {
                        ai[0] = 181f;
                        netUpdate = true;
                    }
                }
                else
                {
                    ai[0] = 400f;
                }
                TargetClosest();
            }
            if (aiStyle == 97 && Main.netMode != 1)
            {
                localAI[1] = 1f;
                TargetClosest();
            }
            if (type == 371)
            {
                num = 0.0;
                ai[0] = 1f;
                ai[1] = 4f;
                dontTakeDamage = true;
            }
            if (type == 346 && (double)life >= (double)lifeMax * 0.5 && (double)life - num < (double)lifeMax * 0.5)
            {
                Gore.NewGore(position, velocity, 517);
            }
            if (type == 184)
            {
                localAI[0] = 60f;
            }
            if (type == 535)
            {
                localAI[0] = 60f;
            }
            if (type == 185)
            {
                localAI[0] = 1f;
            }
            if (!immortal)
            {
                if (realLife >= 0)
                {
                    Main.npc[realLife].life -= (int)num;
                    life = Main.npc[realLife].life;
                    lifeMax = Main.npc[realLife].lifeMax;
                }
                else
                {
                    life -= (int)num;
                }
            }
            if (hit.Knockback > 0f)
            {
                float num3 = hit.Knockback;
                if (num3 > 8f)
                {
                    float num4 = num3 - 8f;
                    num4 *= 0.9f;
                    num3 = 8f + num4;
                }
                if (num3 > 10f)
                {
                    float num5 = num3 - 10f;
                    num5 *= 0.8f;
                    num3 = 10f + num5;
                }
                if (num3 > 12f)
                {
                    float num6 = num3 - 12f;
                    num6 *= 0.7f;
                    num3 = 12f + num6;
                }
                if (num3 > 14f)
                {
                    float num7 = num3 - 14f;
                    num7 *= 0.6f;
                    num3 = 14f + num7;
                }
                if (num3 > 16f)
                {
                    num3 = 16f;
                }
                if (crit)
                {
                    num3 *= 1.4f;
                }
                int num8 = (int)num * 10;
                if (Main.expertMode)
                {
                    num8 = (int)num * 15;
                }
                if (num8 > lifeMax)
                {
                    if (hitDirection < 0 && velocity.X > 0f - num3)
                    {
                        if (velocity.X > 0f)
{
                            velocity.X -= num3;
                        }
                        velocity.X -= num3;
                        if (velocity.X < 0f - num3)
{
                            velocity.X = 0f - num3;
                        }
                    }
                    else if (hitDirection > 0 && velocity.X < num3)
                    {
                        if (velocity.X < 0f)
{
                            velocity.X += num3;
                        }
                        velocity.X += num3;
                        if (velocity.X > num3)
{
                            velocity.X = num3;
                        }
                    }
                    if (type == 185)
                    {
                        num3 *= 1.5f;
                    }
                    num3 = (noGravity ? (num3 * -0.5f) : (num3 * -0.75f));
                    if (velocity.Y > num3)
                    {
                        velocity.Y += num3;
                        if (velocity.Y < num3)
{
                            velocity.Y = num3;
                        }
                    }
                }
                else
                {
                    if (!noGravity)
                    {
                        velocity.Y = (0f - num3) * 0.75f * knockBackResist;
                    }
                    else
                    {
                        velocity.Y = (0f - num3) * 0.5f * knockBackResist;
                    }
                    velocity.X = num3 * (float)hitDirection * knockBackResist;
                }
            }
            if ((type == 113 || type == 114) && life <= 0)
            {
                for (int i = 0; i < 200; i++)
                {
                    if (Main.npc[i].active && (Main.npc[i].type == 113 || Main.npc[i].type == 114))
                    {
                        Main.npc[i].HitEffect(hitDirection, num, hit.InstantKill);
                    }
                }
            }
            else
            {
                HitEffect(hit);
            }
            if (HitSound.HasValue)
            {
                SoundEngine.PlaySound(HitSound, position);
            }
            if (realLife >= 0)
            {
                Main.npc[realLife].checkDead();
            }
            else
            {
                checkDead();
            }
            return (int)num;
        }
        return 0;
    }
References Terraria.Entity.active, Terraria.NPC.checkDead(), Terraria.CombatText.DamagedFriendly, Terraria.CombatText.DamagedHostile, Terraria.Main.expertMode, Terraria.NPC.HitEffect(), Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Gore.NewGore(), Terraria.CombatText.NewText(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.CombatText.OthersDamagedHostile, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, and Terraria.NPC.type.