TModLoader: Terraria.NPC.SpawnSkeletron
SpawnSkeletron()
static void Terraria.NPC.SpawnSkeletron (int onWho) inline static
    {
        //IL_0004: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        bool flag = true;
        bool flag2 = false;
        Vector2 zero = Vector2.Zero;
        int num = 0;
        int num2 = 0;
        for (int i = 0; i < 200; i++)
        {
            if (Main.npc[i].active && Main.npc[i].type == 35)
            {
                flag = false;
                break;
            }
        }
        for (int j = 0; j < 200; j++)
        {
            if (!Main.npc[j].active)
            {
                continue;
            }
            if (Main.npc[j].type == 37)
            {
                flag2 = true;
                Main.npc[j].ai[3] = 1f;
                zero = Main.npc[j].position;
                num = Main.npc[j].width;
                num2 = Main.npc[j].height;
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(23, -1, -1, null, j);
                }
            }
            else if (Main.npc[j].type == 54)
            {
                flag2 = true;
                zero = Main.npc[j].position;
                num = Main.npc[j].width;
                num2 = Main.npc[j].height;
            }
        }
        if (flag && flag2)
        {
            int num3 = NewNPC(GetBossSpawnSource(onWho), (int)zero.X + num / 2, (int)zero.Y + num2 / 2, 35);
            Main.npc[num3].netUpdate = true;
            string nPCNameValue = Lang.GetNPCNameValue(35);
            if (Main.netMode == 0)
            {
                Main.NewText(Language.GetTextValue("Announcement.HasAwoken", nPCNameValue), 175, 75);
            }
            else if (Main.netMode == 2)
            {
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", Lang.GetNPCName(35).ToNetworkText()), new Color(175, 75, 255));
            }
        }
    }
References Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Localization.NetworkText.FromKey(), Terraria.Lang.GetNPCName(), Terraria.Lang.GetNPCNameValue(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.netMode, Terraria.Main.NewText(), Terraria.Main.npc, and Terraria.NetMessage.SendData().
Referenced by Terraria.NPC.checkDead(), Terraria.MessageBuffer.GetData(), and Terraria.Main.GUIChatDrawInner().