TModLoader: Terraria.NPC.HitEffect
HitEffect() [2/2]
void Terraria.NPC.HitEffect (int hitDirection = 0, double dmg = 10::0, bool? instantKill = null) inline
    {
        bool valueOrDefault = instantKill.GetValueOrDefault();
        if (!instantKill.HasValue)
        {
            valueOrDefault = dmg == 9999.0;
            instantKill = valueOrDefault;
        }
        HitEffect(new HitInfo
        {
            DamageType = DamageClass.Default,
            SourceDamage = (instantKill.Value ? 1 : ((int)dmg)),
            Damage = (instantKill.Value ? 1 : ((int)dmg)),
            Crit = false,
            HitDirection = hitDirection,
            Knockback = 0f,
            InstantKill = instantKill.Value
        });
    }
References Terraria.GameContent.Damage, and Terraria.ModLoader.DamageClass.Default.
Referenced by Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_123_Deerclops(), Terraria.NPC.AI_125_ClumsySlimeBalloon(), Terraria.MessageBuffer.GetData(), Terraria.NPC.StrikeNPC(), and Terraria.NPC.VanillaAI_Inner().