TModLoader: Terraria.NPC.SpawnBoss
SpawnBoss()
static void Terraria.NPC.SpawnBoss (int spawnPositionX, int spawnPositionY, int Type, int targetPlayerIndex) inline static
    {
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_020c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        int num = 200;
        if (Type == 127 && mechQueen != -1)
        {
            num = (mechQueen = NewNPC(GetBossSpawnSource(targetPlayerIndex), spawnPositionX, spawnPositionY, Type, 100));
            Main.npc[mechQueen].ai[3] = mechQueen;
        }
        else
        {
            num = NewNPC(GetBossSpawnSource(targetPlayerIndex), spawnPositionX, spawnPositionY, Type, 1);
        }
        if (num == 200)
        {
            return;
        }
        Main.npc[num].target = targetPlayerIndex;
        Main.npc[num].timeLeft *= 20;
        string typeName = Main.npc[num].TypeName;
        if (Main.netMode == 2 && num < 200)
        {
            NetMessage.SendData(23, -1, -1, null, num);
        }
        if (Type == 134 || Type == 127 || Type == 126 || Type == 125)
        {
            AchievementsHelper.CheckMechaMayhem();
        }
        if (Type == 127 && mechQueen == num)
        {
            if (Main.netMode == 0)
            {
                Main.NewText(Lang.misc[107].Value, 175, 75);
            }
            else if (Main.netMode == 2)
            {
                ChatHelper.BroadcastChatMessage(Lang.misc[107].ToNetworkText(), new Color(175, 75, 255));
            }
            return;
        }
        switch (Type)
        {
        case 125:
            if (Main.netMode == 0)
            {
                Main.NewText(Lang.misc[48].Value, 175, 75);
            }
            else if (Main.netMode == 2)
            {
                ChatHelper.BroadcastChatMessage(Lang.misc[48].ToNetworkText(), new Color(175, 75, 255));
            }
            return;
        case 50:
        case 82:
        case 126:
        case 316:
        case 398:
        case 551:
        case 662:
            return;
        }
        if (Main.netMode == 0)
        {
            Main.NewText(Language.GetTextValue("Announcement.HasAwoken", typeName), 175, 75);
        }
        else if (Main.netMode == 2)
        {
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", Main.npc[num].GetTypeNetName()), new Color(175, 75, 255));
        }
    }
References Terraria.NPC.ai, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.GameContent.Achievements.AchievementsHelper.CheckMechaMayhem(), Terraria.Localization.NetworkText.FromKey(), Terraria.Localization.Language.GetTextValue(), Terraria.NPC.GetTypeNetName(), Terraria.Lang.misc, Terraria.Main.netMode, Terraria.Main.NewText(), Terraria.Main.npc, Terraria.NetMessage.SendData(), Terraria.NPC.target, Terraria.NPC.timeLeft, Terraria.Localization.LocalizedText.ToNetworkText(), Terraria.NPC.TypeName, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.NPC.DoDeathEvents().