TModLoader: Terraria.NPC.AI_119_Dandelion
AI_119_Dandelion()
void Terraria.NPC.AI_119_Dandelion () inline private
    {
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_020d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0212: Unknown result type (might be due to invalid IL or missing references)
        //IL_0214: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_0236: Unknown result type (might be due to invalid IL or missing references)
        if (!Main.IsItAHappyWindyDay && timeLeft > 10)
        {
            timeLeft = 10;
        }
        bool flag = false;
        float num = 0f;
        float num2 = 0f;
        NPCUtils.TargetClosestDownwindFromNPC(this, 600f);
        NPCAimedTarget targetData = GetTargetData();
        if (targetData.Type == NPCTargetType.Player)
        {
            Rectangle hitbox = targetData.Hitbox;
            float windSpeedCurrent = Main.windSpeedCurrent;
            num = (float)((Rectangle)(ref hitbox)).Center.X - base.Center.X;
            num2 = Math.Abs(num);
            flag = Math.Abs((float)((Rectangle)(ref hitbox)).Center.Y - base.Center.Y) < 100f && num2 < 600f && ((num > 0f && windSpeedCurrent > 0f) || (num < 0f && windSpeedCurrent < 0f));
        }
        if (ai[0] == 1f)
        {
            localAI[0] = 0f;
            if (num2 < 500f)
            {
                localAI[0] = 1f;
            }
            if (Main.netMode == 1)
            {
                return;
            }
            if (!flag)
            {
                ai[0] = 0f;
                netUpdate = true;
            }
            else
            {
                if (localAI[0] != 1f)
                {
                    return;
                }
                localAI[1] += 1f;
                if (localAI[1] > 80f)
                {
                    ai[0] = 0f;
                    netUpdate = true;
                }
                else
                {
                    if (localAI[1] != 40f)
                    {
                        return;
                    }
                    Vector2 vector = default(Vector2);
                    Vector2 vector2 = default(Vector2);
                    for (int i = 0; i < 1 + Main.rand.Next(3); i++)
                    {
                        int num3 = -1;
                        if (num > 0f)
{
                            num3 = 1;
                        }
                        ((Vector2)(ref vector))._002Ector((float)(num3 * Main.rand.Next(-2, 10)), (float)(10 + Main.rand.Next(-6, 6)));
                        ((Vector2)(ref vector2))._002Ector(2f * (float)num3, -2f);
                        vector2 += vector * 0.25f;
                        if (vector2.Y > -3f)
{
                            vector2.Y = -3f;
                        }
                        Vector2 vector3 = base.Center + vector;
                        vector3.X += num3 * 6;
                        int num4 = 7;
                        Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector3, vector2, 836, num4, 1f, Main.myPlayer, 0f, target);
                    }
                    netUpdate = true;
                }
            }
        }
        else if (ai[0] == 0f)
        {
            localAI[0] = 0f;
            localAI[1] = 0f;
            if (Main.netMode != 1 && flag)
            {
                ai[0] = 1f;
                netUpdate = true;
            }
        }
    }
References Terraria.NPC.ai, Terraria.Entity.Center, Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetTargetData(), Terraria.Main.IsItAHappyWindyDay, Terraria.NPC.localAI, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.Projectile.NewProjectile(), Terraria.Main.rand, Terraria.NPC.target, Terraria.Utilities.NPCUtils.TargetClosestDownwindFromNPC(), Terraria.NPC.timeLeft, and Terraria.Main.windSpeedCurrent.
Referenced by Terraria.NPC.VanillaAI_Inner().