TModLoader: Terraria.NPC.DoDeathEvents_DropBossPotionsAndHearts
DoDeathEvents_DropBossPotionsAndHearts()
void Terraria.NPC.DoDeathEvents_DropBossPotionsAndHearts (ref string typeName) inline private
    {
        int stack = Main.rand.Next(5, 16);
        int num = 28;
        if (type == 113)
        {
            num = 188;
        }
        else if (type == 35)
        {
            num = 188;
        }
        else if (type == 668)
        {
            num = 188;
        }
        else if (type == 222)
        {
            num = 1134;
        }
        else if (type == 657)
        {
            num = 499;
        }
        else if (type > 113 && type < 222)
        {
            num = 499;
        }
        else if (type == 636)
        {
            num = 499;
        }
        else if (type == 245 || type == 262)
        {
            num = 499;
        }
        else if (type == 370)
        {
            num = 499;
        }
        else if (type == 395)
        {
            num = 499;
        }
        else if (type == 439)
        {
            num = 499;
        }
        else if (type == 398)
        {
            num = 3544;
        }
        NPCLoader.BossLoot(this, ref typeName, ref num);
        Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, num, stack);
        int num2 = Main.rand.Next(5) + 5;
        for (int i = 0; i < num2; i++)
        {
            Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 58);
        }
        if (type == 4)
        {
            EoCKilledToday = true;
        }
        else if (type == 113)
        {
            WoFKilledToday = true;
        }
        if (EoCKilledToday && WoFKilledToday)
        {
            ResetBadgerHatTime();
            Item.NewItem(GetItemSource_Loot(), (int)position.X, (int)position.Y, width, height, 5004);
        }
    }
References Terraria.ModLoader.NPCLoader.BossLoot(), Terraria.NPC.EoCKilledToday, Terraria.NPC.GetItemSource_Loot(), Terraria.Entity.height, Terraria.Item.NewItem(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.ResetBadgerHatTime(), Terraria.NPC.type, Terraria.Entity.width, and Terraria.NPC.WoFKilledToday.
Referenced by Terraria.NPC.DoDeathEvents().