TModLoader: Terraria.NPC.AI_037_Destroyer
AI_037_Destroyer()
void Terraria.NPC.AI_037_Destroyer () inline private
Definition at line 52583 of file NPC.cs.
    {
        //IL_0d41: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d46: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1602: Unknown result type (might be due to invalid IL or missing references)
        //IL_1607: Unknown result type (might be due to invalid IL or missing references)
        //IL_161a: Unknown result type (might be due to invalid IL or missing references)
        //IL_161c: Unknown result type (might be due to invalid IL or missing references)
        //IL_161e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1623: Unknown result type (might be due to invalid IL or missing references)
        //IL_1639: Unknown result type (might be due to invalid IL or missing references)
        //IL_163e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1640: Unknown result type (might be due to invalid IL or missing references)
        //IL_1645: Unknown result type (might be due to invalid IL or missing references)
        //IL_1648: Unknown result type (might be due to invalid IL or missing references)
        //IL_164b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1655: Unknown result type (might be due to invalid IL or missing references)
        //IL_165a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1661: Unknown result type (might be due to invalid IL or missing references)
        //IL_1666: Unknown result type (might be due to invalid IL or missing references)
        //IL_166b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0417: Unknown result type (might be due to invalid IL or missing references)
        //IL_0434: Unknown result type (might be due to invalid IL or missing references)
        //IL_0181: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0512: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b65: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b71: Unknown result type (might be due to invalid IL or missing references)
        //IL_07aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bfc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_095d: Unknown result type (might be due to invalid IL or missing references)
        //IL_07be: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f4: Unknown result type (might be due to invalid IL or missing references)
        int num = 0;
        int num12 = 10;
        if (IsMechQueenUp && type != 134)
        {
            int num23 = (int)ai[1];
            while (num23 > 0 && num23 < 200)
            {
                if (Main.npc[num23].active && Main.npc[num23].type >= 134 && Main.npc[num23].type <= 136)
                {
                    num++;
                    if (Main.npc[num23].type == 134)
                    {
                        break;
                    }
                    if (num >= num12)
                    {
                        num = 0;
                        break;
                    }
                    num23 = (int)Main.npc[num23].ai[1];
                    continue;
                }
                num = 0;
                break;
            }
        }
        if (ai[3] > 0f)
        {
            realLife = (int)ai[3];
        }
        if (target < 0 || target == 255 || Main.player[target].dead)
        {
            TargetClosest();
        }
        if (type >= 134 && type <= 136)
        {
            ((Vector2)(ref velocity)).Length();
            if (type == 134 || (type != 134 && Main.npc[(int)ai[1]].alpha < 128))
            {
                if (alpha != 0)
                {
                    for (int i = 0; i < 2; i++)
                    {
                        int num25 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 182, 0f, 0f, 100, default(Color), 2f);
                        Main.dust[num25].noGravity = true;
                        Main.dust[num25].noLight = true;
                    }
                }
                alpha -= 42;
                if (alpha < 0)
                {
                    alpha = 0;
                }
            }
        }
        if (type > 134)
        {
            bool flag = false;
            if (ai[1] <= 0f)
            {
                flag = true;
            }
            else if (Main.npc[(int)ai[1]].life <= 0)
            {
                flag = true;
            }
            if (flag)
            {
                life = 0;
                HitEffect();
                checkDead();
            }
        }
        if (Main.netMode != 1)
        {
            if (ai[0] == 0f && type == 134)
            {
                ai[3] = whoAmI;
                realLife = whoAmI;
                int num26 = 0;
                int num27 = whoAmI;
                int destroyerSegmentsCount = GetDestroyerSegmentsCount();
                for (int j = 0; j <= destroyerSegmentsCount; j++)
                {
                    int num28 = 135;
                    if (j == destroyerSegmentsCount)
                    {
                        num28 = 136;
                    }
                    num26 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)(position.X + (float)(width / 2)), (int)(position.Y + (float)height), num28, whoAmI);
                    Main.npc[num26].ai[3] = whoAmI;
                    Main.npc[num26].realLife = whoAmI;
                    Main.npc[num26].ai[1] = num27;
                    Main.npc[num27].ai[0] = num26;
                    NetMessage.SendData(23, -1, -1, null, num26);
                    num27 = num26;
                }
            }
            if (type == 135)
            {
                localAI[0] += Main.rand.Next(4);
                if (localAI[0] >= (float)Main.rand.Next(1400, 26000))
                {
                    localAI[0] = 0f;
                    TargetClosest();
                    if (Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
                    {
                        Vector2 vector = default(Vector2);
                        ((Vector2)(ref vector))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)(height / 2));
                        float num29 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector.X + (float)Main.rand.Next(-20, 21);
                        float num30 = Main.player[target].position.Y + (float)Main.player[target].height * 0.5f - vector.Y + (float)Main.rand.Next(-20, 21);
                        float num2 = (float)Math.Sqrt(num29 * num29 + num30 * num30);
                        num2 = 8f / num2;
                        num29 *= num2;
                        num30 *= num2;
                        num29 += (float)Main.rand.Next(-20, 21) * 0.05f;
                        num30 += (float)Main.rand.Next(-20, 21) * 0.05f;
                        int attackDamage_ForProjectiles = GetAttackDamage_ForProjectiles(22f, 18f);
                        int num3 = 100;
                        vector.X += num29 * 5f;
                        vector.Y += num30 * 5f;
                        int num4 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector.X, vector.Y, num29, num30, num3, attackDamage_ForProjectiles, 0f, Main.myPlayer);
                        Main.projectile[num4].timeLeft = 300;
                        netUpdate = true;
                    }
                }
            }
        }
        int num5 = (int)(position.X / 16f) - 1;
        int num6 = (int)((position.X + (float)width) / 16f) + 2;
        int num7 = (int)(position.Y / 16f) - 1;
        int num8 = (int)((position.Y + (float)height) / 16f) + 2;
        if (num5 < 0)
        {
            num5 = 0;
        }
        if (num6 > Main.maxTilesX)
        {
            num6 = Main.maxTilesX;
        }
        if (num7 < 0)
        {
            num7 = 0;
        }
        if (num8 > Main.maxTilesY)
        {
            num8 = Main.maxTilesY;
        }
        bool flag2 = false;
        if (!flag2)
        {
            Vector2 vector2 = default(Vector2);
            for (int k = num5; k < num6; k++)
            {
                for (int l = num7; l < num8; l++)
                {
                    if (Main.tile[k, l] != null && ((Main.tile[k, l].nactive() && (Main.tileSolid[Main.tile[k, l].type] || (Main.tileSolidTop[Main.tile[k, l].type] && Main.tile[k, l].frameY == 0))) || Main.tile[k, l].liquid > 64))
                    {
                        vector2.X = k * 16;
                        vector2.Y = l * 16;
                        if (position.X + (float)width > vector2.X && position.X < vector2.X + 16f && position.Y + (float)height > vector2.Y && position.Y < vector2.Y + 16f)
{
                            flag2 = true;
                            break;
                        }
                    }
                }
            }
        }
        if (!flag2)
        {
            if (type != 135 || ai[2] != 1f)
            {
                Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.3f, 0.1f, 0.05f);
            }
            localAI[1] = 1f;
            if (type == 134)
            {
                Rectangle rectangle = default(Rectangle);
                ((Rectangle)(ref rectangle))._002Ector((int)position.X, (int)position.Y, width, height);
                int num9 = 1000;
                bool flag3 = true;
                if (position.Y > Main.player[target].position.Y)
                {
                    Rectangle rectangle2 = default(Rectangle);
                    for (int m = 0; m < 255; m++)
                    {
                        if (Main.player[m].active)
{
                            ((Rectangle)(ref rectangle2))._002Ector((int)Main.player[m].position.X - num9, (int)Main.player[m].position.Y - num9, num9 * 2, num9 * 2);
                            if (((Rectangle)(ref rectangle)).Intersects(rectangle2))
{
                                flag3 = false;
                                break;
                            }
                        }
                    }
                    if (flag3)
                    {
                        flag2 = true;
                    }
                }
            }
        }
        else
        {
            localAI[1] = 0f;
        }
        float num10 = 16f;
        if (Main.IsItDay() || Main.player[target].dead)
        {
            flag2 = false;
            velocity.Y += 1f;
            if ((double)position.Y > Main.worldSurface * 16.0)
            {
                velocity.Y += 1f;
                num10 = 32f;
            }
            if ((double)position.Y > Main.rockLayer * 16.0)
            {
                for (int n = 0; n < 200; n++)
                {
                    if (Main.npc[n].aiStyle == aiStyle)
                    {
                        Main.npc[n].active = false;
                    }
                }
            }
        }
        float num11 = 0.1f;
        float num13 = 0.15f;
        if (Main.getGoodWorld)
        {
            num11 *= 1.2f;
            num13 *= 1.2f;
        }
        Vector2 vector3 = default(Vector2);
        ((Vector2)(ref vector3))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
        float num14 = Main.player[target].position.X + (float)(Main.player[target].width / 2);
        float num15 = Main.player[target].position.Y + (float)(Main.player[target].height / 2);
        num14 = (int)(num14 / 16f) * 16;
        num15 = (int)(num15 / 16f) * 16;
        vector3.X = (int)(vector3.X / 16f) * 16;
        vector3.Y = (int)(vector3.Y / 16f) * 16;
        num14 -= vector3.X;
        num15 -= vector3.Y;
        float num16 = (float)Math.Sqrt(num14 * num14 + num15 * num15);
        if (ai[1] > 0f && ai[1] < (float)Main.npc.Length)
        {
            int num17 = (int)(44f * scale);
            try
            {
                vector3 = new Vector2(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                num14 = Main.npc[(int)ai[1]].position.X + (float)(Main.npc[(int)ai[1]].width / 2) - vector3.X;
                num15 = Main.npc[(int)ai[1]].position.Y + (float)(Main.npc[(int)ai[1]].height / 2) - vector3.Y;
            }
            catch
            {
            }
            if (num > 0)
            {
                float num18 = (float)num17 - (float)num17 * (((float)num - 1f) * 0.1f);
                if (num18 < 0f)
                {
                    num18 = 0f;
                }
                if (num18 > (float)num17)
                {
                    num18 = num17;
                }
                num15 = Main.npc[(int)ai[1]].position.Y + (float)(Main.npc[(int)ai[1]].height / 2) + num18 - vector3.Y;
            }
            rotation = (float)Math.Atan2(num15, num14) + 1.57f;
            num16 = (float)Math.Sqrt(num14 * num14 + num15 * num15);
            if (num > 0)
            {
                num17 = num17 / num12 * num;
            }
            num16 = (num16 - (float)num17) / num16;
            num14 *= num16;
            num15 *= num16;
            velocity = Vector2.Zero;
            position.X += num14;
            position.Y += num15;
            num14 = Main.npc[(int)ai[1]].position.X + (float)(Main.npc[(int)ai[1]].width / 2) - vector3.X;
            num15 = Main.npc[(int)ai[1]].position.Y + (float)(Main.npc[(int)ai[1]].height / 2) - vector3.Y;
            rotation = (float)Math.Atan2(num15, num14) + 1.57f;
        }
        else
        {
            if (!flag2)
            {
                TargetClosest();
                velocity.Y += 0.15f;
                if (velocity.Y > num10)
                {
                    velocity.Y = num10;
                }
                if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num10 * 0.4)
                {
                    if (velocity.X < 0f)
                    {
                        velocity.X -= num11 * 1.1f;
                    }
                    else
                    {
                        velocity.X += num11 * 1.1f;
                    }
                }
                else if (velocity.Y == num10)
                {
                    if (velocity.X < num14)
                    {
                        velocity.X += num11;
                    }
                    else if (velocity.X > num14)
                    {
                        velocity.X -= num11;
                    }
                }
                else if (velocity.Y > 4f)
                {
                    if (velocity.X < 0f)
                    {
                        velocity.X += num11 * 0.9f;
                    }
                    else
                    {
                        velocity.X -= num11 * 0.9f;
                    }
                }
            }
            else
            {
                if (soundDelay == 0)
                {
                    float num19 = num16 / 40f;
                    if (num19 < 10f)
                    {
                        num19 = 10f;
                    }
                    if (num19 > 20f)
                    {
                        num19 = 20f;
                    }
                    soundDelay = (int)num19;
                    SoundEngine.PlaySound(15, (int)position.X, (int)position.Y);
                }
                num16 = (float)Math.Sqrt(num14 * num14 + num15 * num15);
                float num20 = Math.Abs(num14);
                float num21 = Math.Abs(num15);
                float num22 = num10 / num16;
                num14 *= num22;
                num15 *= num22;
                if (((velocity.X > 0f && num14 > 0f) || (velocity.X < 0f && num14 < 0f)) && ((velocity.Y > 0f && num15 > 0f) || (velocity.Y < 0f && num15 < 0f)))
                {
                    if (velocity.X < num14)
                    {
                        velocity.X += num13;
                    }
                    else if (velocity.X > num14)
                    {
                        velocity.X -= num13;
                    }
                    if (velocity.Y < num15)
                    {
                        velocity.Y += num13;
                    }
                    else if (velocity.Y > num15)
                    {
                        velocity.Y -= num13;
                    }
                }
                if ((velocity.X > 0f && num14 > 0f) || (velocity.X < 0f && num14 < 0f) || (velocity.Y > 0f && num15 > 0f) || (velocity.Y < 0f && num15 < 0f))
                {
                    if (velocity.X < num14)
                    {
                        velocity.X += num11;
                    }
                    else if (velocity.X > num14)
                    {
                        velocity.X -= num11;
                    }
                    if (velocity.Y < num15)
                    {
                        velocity.Y += num11;
                    }
                    else if (velocity.Y > num15)
                    {
                        velocity.Y -= num11;
                    }
                    if ((double)Math.Abs(num15) < (double)num10 * 0.2 && ((velocity.X > 0f && num14 < 0f) || (velocity.X < 0f && num14 > 0f)))
                    {
                        if (velocity.Y > 0f)
{
                            velocity.Y += num11 * 2f;
                        }
                        else
{
                            velocity.Y -= num11 * 2f;
                        }
                    }
                    if ((double)Math.Abs(num14) < (double)num10 * 0.2 && ((velocity.Y > 0f && num15 < 0f) || (velocity.Y < 0f && num15 > 0f)))
                    {
                        if (velocity.X > 0f)
{
                            velocity.X += num11 * 2f;
                        }
                        else
{
                            velocity.X -= num11 * 2f;
                        }
                    }
                }
                else if (num20 > num21)
                {
                    if (velocity.X < num14)
                    {
                        velocity.X += num11 * 1.1f;
                    }
                    else if (velocity.X > num14)
                    {
                        velocity.X -= num11 * 1.1f;
                    }
                    if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num10 * 0.5)
                    {
                        if (velocity.Y > 0f)
{
                            velocity.Y += num11;
                        }
                        else
{
                            velocity.Y -= num11;
                        }
                    }
                }
                else
                {
                    if (velocity.Y < num15)
                    {
                        velocity.Y += num11 * 1.1f;
                    }
                    else if (velocity.Y > num15)
                    {
                        velocity.Y -= num11 * 1.1f;
                    }
                    if ((double)(Math.Abs(velocity.X) + Math.Abs(velocity.Y)) < (double)num10 * 0.5)
                    {
                        if (velocity.X > 0f)
{
                            velocity.X += num11;
                        }
                        else
{
                            velocity.X -= num11;
                        }
                    }
                }
            }
            rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
            if (type == 134)
            {
                if (flag2)
                {
                    if (localAI[0] != 1f)
                    {
                        netUpdate = true;
                    }
                    localAI[0] = 1f;
                }
                else
                {
                    if (localAI[0] != 0f)
                    {
                        netUpdate = true;
                    }
                    localAI[0] = 0f;
                }
                if (((velocity.X > 0f && oldVelocity.X < 0f) || (velocity.X < 0f && oldVelocity.X > 0f) || (velocity.Y > 0f && oldVelocity.Y < 0f) || (velocity.Y < 0f && oldVelocity.Y > 0f)) && !justHit)
                {
                    netUpdate = true;
                }
            }
        }
        if (IsMechQueenUp && type == 134)
        {
            NPC nPC = Main.npc[mechQueen];
            Vector2 mechQueenCenter = nPC.GetMechQueenCenter();
            Vector2 vector4 = default(Vector2);
            ((Vector2)(ref vector4))._002Ector(0f, 100f);
            Vector2 spinningpoint = mechQueenCenter + vector4;
            float num24 = nPC.velocity.X * 0.025f;
            spinningpoint = spinningpoint.RotatedBy(num24, mechQueenCenter);
            position = spinningpoint - base.Size / 2f + nPC.velocity;
            velocity.X = 0f;
            velocity.Y = 0f;
            rotation = num24 * 0.75f + (float)Math.PI;
        }
    }
References Terraria.Lighting.AddLight(), Terraria.NPC.ai, Terraria.NPC.aiStyle, Terraria.NPC.alpha, Terraria.Collision.CanHit(), Terraria.NPC.checkDead(), Terraria.Main.dust, Terraria.NPC.GetAttackDamage_ForProjectiles(), Terraria.NPC.GetDestroyerSegmentsCount(), Terraria.Main.getGoodWorld, Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.Entity.height, Terraria.NPC.HitEffect(), Terraria.Main.IsItDay(), Terraria.NPC.IsMechQueenUp, Terraria.NPC.justHit, Terraria.NPC.life, Terraria.NPC.localAI, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.NPC.mechQueen, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.Dust.NewDust(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.Entity.oldVelocity, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.NPC.realLife, Terraria.NPC.rotation, Terraria.NPC.scale, Terraria.NetMessage.SendData(), Terraria.NPC.soundDelay, Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.NPC.type, Terraria.Entity.velocity, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.NPC.VanillaAI_Inner().