TModLoader: Terraria.NPC.AI_123_Deerclops_TryMakingSpike
AI_123_Deerclops_TryMakingSpike()
void Terraria.NPC.AI_123_Deerclops_TryMakingSpike (ref Point sourceTileCoords, int dir, int howMany, int whichOne, int xOffset) inline private
    {
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        int num = 13;
        int num2 = sourceTileCoords.X + xOffset * dir;
        int num3 = AI_123_Deerclops_TryMakingSpike_FindBestY(ref sourceTileCoords, num2);
        if (WorldGen.ActiveAndWalkableTile(num2, num3))
        {
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector((float)(num2 * 16 + 8), (float)(num3 * 16 - 8));
            Vector2 vector2 = Utils.RotatedBy(new Vector2(0f, -1f), (float)(whichOne * dir) * 0.7f * ((float)Math.PI / 4f / (float)howMany));
            Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector, vector2, 961, num, 0f, Main.myPlayer, 0f, 0.1f + Main.rand.NextFloat() * 0.1f + (float)xOffset * 1.1f / (float)howMany);
        }
    }
References Terraria.WorldGen.ActiveAndWalkableTile(), Terraria.NPC.AI_123_Deerclops_TryMakingSpike_FindBestY(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Main.rand, and Terraria.Utils.RotatedBy().
Referenced by Terraria.NPC.AI_123_Deerclops_MakeSpikesBothSides(), and Terraria.NPC.AI_123_Deerclops_MakeSpikesForward().