TModLoader: Terraria.NPC.AI_045_Golem
AI_045_Golem()
void Terraria.NPC.AI_045_Golem () inline private
    {
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0365: Unknown result type (might be due to invalid IL or missing references)
        //IL_036b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0370: Unknown result type (might be due to invalid IL or missing references)
        //IL_0375: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_038b: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0407: Unknown result type (might be due to invalid IL or missing references)
        //IL_0411: Unknown result type (might be due to invalid IL or missing references)
        //IL_0416: Unknown result type (might be due to invalid IL or missing references)
        //IL_053e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0556: Unknown result type (might be due to invalid IL or missing references)
        //IL_0566: Unknown result type (might be due to invalid IL or missing references)
        //IL_057d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0583: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0482: Unknown result type (might be due to invalid IL or missing references)
        //IL_049a: Unknown result type (might be due to invalid IL or missing references)
        //IL_04aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0761: Unknown result type (might be due to invalid IL or missing references)
        //IL_077e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0735: Unknown result type (might be due to invalid IL or missing references)
        //IL_074b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0635: Unknown result type (might be due to invalid IL or missing references)
        //IL_064d: Unknown result type (might be due to invalid IL or missing references)
        //IL_065d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0672: Unknown result type (might be due to invalid IL or missing references)
        //IL_0678: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_078d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d78: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a54: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a59: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a95: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac9: Unknown result type (might be due to invalid IL or missing references)
        golemBoss = whoAmI;
        float num = GetMyBalance();
        if (Main.getGoodWorld)
        {
            num += 2f;
        }
        if ((!Main.player[target].ZoneLihzhardTemple && !Main.player[target].ZoneJungle) || (double)Main.player[target].Center.Y < Main.worldSurface * 16.0)
        {
            num *= 2f;
        }
        if (localAI[0] == 0f)
        {
            localAI[0] = 1f;
            NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X - 84, (int)base.Center.Y - 9, 247);
            NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X + 78, (int)base.Center.Y - 9, 248);
            NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X - 3, (int)base.Center.Y - 57, 246);
        }
        if (target >= 0 && Main.player[target].dead)
        {
            TargetClosest();
            if (Main.player[target].dead)
            {
                noTileCollide = true;
            }
        }
        if (alpha > 0)
        {
            alpha -= 10;
            if (alpha < 0)
            {
                alpha = 0;
            }
            ai[1] = 0f;
        }
        bool flag = false;
        bool flag2 = false;
        bool flag3 = false;
        dontTakeDamage = false;
        for (int i = 0; i < 200; i++)
        {
            if (Main.npc[i].active && Main.npc[i].type == 246)
            {
                flag = true;
            }
            if (Main.npc[i].active && Main.npc[i].type == 247)
            {
                flag2 = true;
            }
            if (Main.npc[i].active && Main.npc[i].type == 248)
            {
                flag3 = true;
            }
        }
        dontTakeDamage = flag;
        if (Main.netMode != 1 && Main.getGoodWorld && velocity.Y > 0f)
        {
            for (int j = (int)(position.X / 16f); (float)j < (position.X + (float)width) / 16f; j++)
            {
                for (int k = (int)(position.Y / 16f); (float)k < (position.Y + (float)width) / 16f; k++)
                {
                    if (Main.tile[j, k].type == 4)
                    {
                        Main.tile[j, k].active(active: false);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, j, k);
                        }
                    }
                }
            }
        }
        position += netOffset;
        if (!Main.getGoodWorld)
        {
            if (!flag2)
            {
                int num2 = Dust.NewDust(new Vector2(base.Center.X - 80f * scale, base.Center.Y - 9f), 8, 8, 31, 0f, 0f, 100);
                Main.dust[num2].alpha += Main.rand.Next(100);
                Dust obj = Main.dust[num2];
                obj.velocity *= 0.2f;
                Main.dust[num2].velocity.Y -= 0.5f + (float)Main.rand.Next(10) * 0.1f;
                Main.dust[num2].fadeIn = 0.5f + (float)Main.rand.Next(10) * 0.1f;
                if (Main.rand.Next(10) == 0)
                {
                    num2 = Dust.NewDust(new Vector2(base.Center.X - 80f * scale, base.Center.Y - 9f), 8, 8, 6);
                    if (Main.rand.Next(20) != 0)
                    {
                        Main.dust[num2].noGravity = true;
                        Main.dust[num2].scale *= 1f + (float)Main.rand.Next(10) * 0.1f;
                        Main.dust[num2].velocity.Y -= 1f;
                    }
                }
            }
            if (!flag3)
            {
                int num3 = Dust.NewDust(new Vector2(base.Center.X + 62f * scale, base.Center.Y - 9f), 8, 8, 31, 0f, 0f, 100);
                Main.dust[num3].alpha += Main.rand.Next(100);
                Dust obj2 = Main.dust[num3];
                obj2.velocity *= 0.2f;
                Main.dust[num3].velocity.Y -= 0.5f + (float)Main.rand.Next(10) * 0.1f;
                Main.dust[num3].fadeIn = 0.5f + (float)Main.rand.Next(10) * 0.1f;
                if (Main.rand.Next(10) == 0)
                {
                    num3 = Dust.NewDust(new Vector2(base.Center.X + 62f * scale, base.Center.Y - 9f), 8, 8, 6);
                    if (Main.rand.Next(20) != 0)
                    {
                        Main.dust[num3].noGravity = true;
                        Main.dust[num3].scale *= 1f + (float)Main.rand.Next(10) * 0.1f;
                        Main.dust[num3].velocity.Y -= 1f;
                    }
                }
            }
        }
        position -= netOffset;
        if (noTileCollide && !Main.player[target].dead)
        {
            if (velocity.Y > 0f && base.Bottom.Y > Main.player[target].Top.Y)
            {
                noTileCollide = false;
            }
            else if (Collision.CanHit(position, width, height, Main.player[target].Center, 1, 1) && !Collision.SolidTiles(position, width, height))
            {
                noTileCollide = false;
            }
        }
        if (ai[0] == 0f)
        {
            if (velocity.Y == 0f)
            {
                velocity.X *= 0.8f;
                float num4 = 1f;
                if (ai[1] > 0f)
                {
                    if (!flag2)
                    {
                        num4 += 2f;
                    }
                    if (!flag3)
                    {
                        num4 += 2f;
                    }
                    if (!flag)
                    {
                        num4 += 2f;
                    }
                    if (life < lifeMax)
                    {
                        num4 += 1f;
                    }
                    if (life < lifeMax / 2)
                    {
                        num4 += 4f;
                    }
                    if (life < lifeMax / 3)
                    {
                        num4 += 8f;
                    }
                    num4 *= num;
                    if (Main.getGoodWorld)
                    {
                        num4 += 100f;
                    }
                }
                ai[1] += num4;
                if (ai[1] >= 300f)
                {
                    ai[1] = -20f;
                    frameCounter = 0.0;
                }
                else if (ai[1] == -1f)
                {
                    noTileCollide = true;
                    TargetClosest();
                    velocity.X = 4 * direction;
                    if (life < lifeMax)
                    {
                        velocity.Y = -12.1f * (num + 9f) / 10f;
                        if ((double)velocity.Y < -19.1)
{
                            velocity.Y = -19.1f;
                        }
                    }
                    else
                    {
                        velocity.Y = -12.1f;
                    }
                    ai[0] = 1f;
                    ai[1] = 0f;
                }
            }
        }
        else if (ai[0] == 1f)
        {
            if (velocity.Y == 0f)
            {
                SoundEngine.PlaySound(in SoundID.Item14, position);
                ai[0] = 0f;
                for (int l = (int)position.X - 20; l < (int)position.X + width + 40; l += 20)
                {
                    for (int m = 0; m < 4; m++)
                    {
                        int num5 = Dust.NewDust(new Vector2(position.X - 20f, position.Y + (float)height), width + 20, 4, 31, 0f, 0f, 100, default(Color), 1.5f);
                        Dust obj3 = Main.dust[num5];
                        obj3.velocity *= 0.2f;
                    }
                    int num6 = Gore.NewGore(new Vector2((float)(l - 20), position.Y + (float)height - 8f), default(Vector2), Main.rand.Next(61, 64));
                    Gore obj4 = Main.gore[num6];
                    obj4.velocity *= 0.4f;
                }
            }
            else
            {
                TargetClosest();
                if (position.X < Main.player[target].position.X && position.X + (float)width > Main.player[target].position.X + (float)Main.player[target].width)
                {
                    velocity.X *= 0.9f;
                    if (base.Bottom.Y < Main.player[target].position.Y)
                    {
                        velocity.Y += 0.2f * (num + 1f) / 2f;
                    }
                }
                else
                {
                    if (direction < 0)
                    {
                        velocity.X -= 0.2f;
                    }
                    else if (direction > 0)
                    {
                        velocity.X += 0.2f;
                    }
                    float num7 = 3f;
                    if (life < lifeMax)
                    {
                        num7 += 1f;
                    }
                    if (life < lifeMax / 2)
                    {
                        num7 += 1f;
                    }
                    if (life < lifeMax / 4)
                    {
                        num7 += 1f;
                    }
                    num7 *= (num + 1f) / 2f;
                    if (velocity.X < 0f - num7)
                    {
                        velocity.X = 0f - num7;
                    }
                    if (velocity.X > num7)
                    {
                        velocity.X = num7;
                    }
                }
            }
        }
        if (target <= 0 || target == 255 || Main.player[target].dead)
        {
            TargetClosest();
        }
        int num8 = 3000;
        if (Math.Abs(base.Center.X - Main.player[target].Center.X) + Math.Abs(base.Center.Y - Main.player[target].Center.Y) > (float)num8)
        {
            TargetClosest();
            if (Math.Abs(base.Center.X - Main.player[target].Center.X) + Math.Abs(base.Center.Y - Main.player[target].Center.Y) > (float)num8)
            {
                active = false;
            }
        }
    }
References Terraria.Entity.active, Terraria.NPC.ai, Terraria.NPC.alpha, Terraria.Collision.CanHit(), Terraria.Entity.direction, Terraria.NPC.dontTakeDamage, Terraria.Main.dust, Terraria.NPC.frameCounter, Terraria.Main.getGoodWorld, Terraria.NPC.GetMyBalance(), Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.NPC.golemBoss, Terraria.Main.gore, Terraria.Entity.height, Terraria.ID.SoundID.Item14, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Main.netMode, Terraria.NPC.netOffset, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.NPC.NewNPC(), Terraria.NPC.noTileCollide, Terraria.Main.npc, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.scale, Terraria.NetMessage.SendTileSquare(), Terraria.Collision.SolidTiles(), Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Main.tile, Terraria.Entity.velocity, Terraria.Entity.whoAmI, Terraria.Entity.width, and Terraria.Main.worldSurface.
Referenced by Terraria.NPC.VanillaAI_Inner().