TModLoader: Terraria.NPC.AI_003_Fighters
AI_003_Fighters()
void Terraria.NPC.AI_003_Fighters () inline private
Definition at line 59421 of file NPC.cs.
    {
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00de: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0734: Unknown result type (might be due to invalid IL or missing references)
        //IL_0739: Unknown result type (might be due to invalid IL or missing references)
        //IL_0751: Unknown result type (might be due to invalid IL or missing references)
        //IL_076d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0528: Unknown result type (might be due to invalid IL or missing references)
        //IL_052d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0545: Unknown result type (might be due to invalid IL or missing references)
        //IL_0561: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_0137: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_041e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0431: Unknown result type (might be due to invalid IL or missing references)
        //IL_0947: Unknown result type (might be due to invalid IL or missing references)
        //IL_094d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0952: Unknown result type (might be due to invalid IL or missing references)
        //IL_0957: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0878: Unknown result type (might be due to invalid IL or missing references)
        //IL_0897: Unknown result type (might be due to invalid IL or missing references)
        //IL_089d: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0908: Unknown result type (might be due to invalid IL or missing references)
        //IL_090d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0912: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0abb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0acb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a53: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a70: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aaa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aaf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab4: Unknown result type (might be due to invalid IL or missing references)
        //IL_060c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0612: Unknown result type (might be due to invalid IL or missing references)
        //IL_0617: Unknown result type (might be due to invalid IL or missing references)
        //IL_061c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0625: Unknown result type (might be due to invalid IL or missing references)
        //IL_062c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0631: Unknown result type (might be due to invalid IL or missing references)
        //IL_0635: Unknown result type (might be due to invalid IL or missing references)
        //IL_063f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0644: Unknown result type (might be due to invalid IL or missing references)
        //IL_0646: Unknown result type (might be due to invalid IL or missing references)
        //IL_0650: Unknown result type (might be due to invalid IL or missing references)
        //IL_0655: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d63: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d68: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d70: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0afb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b08: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0970: Unknown result type (might be due to invalid IL or missing references)
        //IL_098f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0995: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a05: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1034: Unknown result type (might be due to invalid IL or missing references)
        //IL_1040: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dfc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e01: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0707: Unknown result type (might be due to invalid IL or missing references)
        //IL_070c: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06df: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c40: Unknown result type (might be due to invalid IL or missing references)
        //IL_169b: Unknown result type (might be due to invalid IL or missing references)
        //IL_16a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_133c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1343: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c56: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c60: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c65: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c71: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c76: Unknown result type (might be due to invalid IL or missing references)
        //IL_27a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_27b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_16c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_16d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cfb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d00: Unknown result type (might be due to invalid IL or missing references)
        //IL_2dda: Unknown result type (might be due to invalid IL or missing references)
        //IL_2deb: Unknown result type (might be due to invalid IL or missing references)
        //IL_27d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_27dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f84: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f94: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fb3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fb7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fbc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fc0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fcd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fdb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fe0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1788: Unknown result type (might be due to invalid IL or missing references)
        //IL_178e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1793: Unknown result type (might be due to invalid IL or missing references)
        //IL_1798: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d35: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d44: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d46: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d50: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d55: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d17: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_316c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3172: Unknown result type (might be due to invalid IL or missing references)
        //IL_3177: Unknown result type (might be due to invalid IL or missing references)
        //IL_317c: Unknown result type (might be due to invalid IL or missing references)
        //IL_28be: Unknown result type (might be due to invalid IL or missing references)
        //IL_28cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_28d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_28d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_28dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_28de: Unknown result type (might be due to invalid IL or missing references)
        //IL_27f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_280c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fef: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e85: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e94: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e99: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ea1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ea9: Unknown result type (might be due to invalid IL or missing references)
        //IL_19da: Unknown result type (might be due to invalid IL or missing references)
        //IL_19e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_19e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_19ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_19f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_170f: Unknown result type (might be due to invalid IL or missing references)
        //IL_15cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_3364: Unknown result type (might be due to invalid IL or missing references)
        //IL_336a: Unknown result type (might be due to invalid IL or missing references)
        //IL_336f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3374: Unknown result type (might be due to invalid IL or missing references)
        //IL_3275: Unknown result type (might be due to invalid IL or missing references)
        //IL_31a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_300d: Unknown result type (might be due to invalid IL or missing references)
        //IL_301e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2900: Unknown result type (might be due to invalid IL or missing references)
        //IL_2904: Unknown result type (might be due to invalid IL or missing references)
        //IL_2909: Unknown result type (might be due to invalid IL or missing references)
        //IL_28f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_28f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_28fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_2076: Unknown result type (might be due to invalid IL or missing references)
        //IL_2081: Unknown result type (might be due to invalid IL or missing references)
        //IL_1724: Unknown result type (might be due to invalid IL or missing references)
        //IL_1737: Unknown result type (might be due to invalid IL or missing references)
        //IL_34e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_34e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_34ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_34f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_3338: Unknown result type (might be due to invalid IL or missing references)
        //IL_333e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3343: Unknown result type (might be due to invalid IL or missing references)
        //IL_3348: Unknown result type (might be due to invalid IL or missing references)
        //IL_2eae: Unknown result type (might be due to invalid IL or missing references)
        //IL_2eb4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2eb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ebe: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ec9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2eec: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ef2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f22: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f27: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f38: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f45: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f56: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f60: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f95: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fa5: Unknown result type (might be due to invalid IL or missing references)
        //IL_20b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_20be: Unknown result type (might be due to invalid IL or missing references)
        //IL_343e: Unknown result type (might be due to invalid IL or missing references)
        //IL_345f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3391: Unknown result type (might be due to invalid IL or missing references)
        //IL_33b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_30da: Unknown result type (might be due to invalid IL or missing references)
        //IL_30e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_30e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_30ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_30f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_3118: Unknown result type (might be due to invalid IL or missing references)
        //IL_311e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3145: Unknown result type (might be due to invalid IL or missing references)
        //IL_314b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3150: Unknown result type (might be due to invalid IL or missing references)
        //IL_3155: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aab: Unknown result type (might be due to invalid IL or missing references)
        //IL_2406: Unknown result type (might be due to invalid IL or missing references)
        //IL_240b: Unknown result type (might be due to invalid IL or missing references)
        //IL_22ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_2296: Unknown result type (might be due to invalid IL or missing references)
        //IL_22a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_22a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bdb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1be1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1be6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1beb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1984: Unknown result type (might be due to invalid IL or missing references)
        //IL_199f: Unknown result type (might be due to invalid IL or missing references)
        //IL_19a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_19aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_19af: Unknown result type (might be due to invalid IL or missing references)
        //IL_186a: Unknown result type (might be due to invalid IL or missing references)
        //IL_187d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1882: Unknown result type (might be due to invalid IL or missing references)
        //IL_1887: Unknown result type (might be due to invalid IL or missing references)
        //IL_1478: Unknown result type (might be due to invalid IL or missing references)
        //IL_147d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1482: Unknown result type (might be due to invalid IL or missing references)
        //IL_2be3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2be9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bee: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bf3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2acc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ad7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ad9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ade: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ae3: Unknown result type (might be due to invalid IL or missing references)
        //IL_3496: Unknown result type (might be due to invalid IL or missing references)
        //IL_34b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_34cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_34d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_33ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_3410: Unknown result type (might be due to invalid IL or missing references)
        //IL_3425: Unknown result type (might be due to invalid IL or missing references)
        //IL_342b: Unknown result type (might be due to invalid IL or missing references)
        //IL_32ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_330e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3323: Unknown result type (might be due to invalid IL or missing references)
        //IL_3329: Unknown result type (might be due to invalid IL or missing references)
        //IL_3226: Unknown result type (might be due to invalid IL or missing references)
        //IL_3247: Unknown result type (might be due to invalid IL or missing references)
        //IL_325c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3262: Unknown result type (might be due to invalid IL or missing references)
        //IL_2af3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b06: Unknown result type (might be due to invalid IL or missing references)
        //IL_2463: Unknown result type (might be due to invalid IL or missing references)
        //IL_246b: Unknown result type (might be due to invalid IL or missing references)
        //IL_21bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_21c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_18c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_18d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_18ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_18f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_18fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_1910: Unknown result type (might be due to invalid IL or missing references)
        //IL_1916: Unknown result type (might be due to invalid IL or missing references)
        //IL_1924: Unknown result type (might be due to invalid IL or missing references)
        //IL_1926: Unknown result type (might be due to invalid IL or missing references)
        //IL_192a: Unknown result type (might be due to invalid IL or missing references)
        //IL_192f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1934: Unknown result type (might be due to invalid IL or missing references)
        //IL_1941: Unknown result type (might be due to invalid IL or missing references)
        //IL_1948: Unknown result type (might be due to invalid IL or missing references)
        //IL_194d: Unknown result type (might be due to invalid IL or missing references)
        //IL_14a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_14bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_14c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_14cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_14cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c01: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c06: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c12: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c21: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c26: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c43: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c49: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c56: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c64: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c69: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c75: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c85: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c91: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ca0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cac: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cc0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ccb: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d03: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d09: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d13: Unknown result type (might be due to invalid IL or missing references)
        //IL_2362: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b21: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b56: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b72: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b80: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b82: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b86: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b90: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ba4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ba9: Unknown result type (might be due to invalid IL or missing references)
        //IL_14f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1501: Unknown result type (might be due to invalid IL or missing references)
        //IL_1506: Unknown result type (might be due to invalid IL or missing references)
        //IL_150b: Unknown result type (might be due to invalid IL or missing references)
        //IL_150d: Unknown result type (might be due to invalid IL or missing references)
        //IL_150f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1514: Unknown result type (might be due to invalid IL or missing references)
        //IL_1519: Unknown result type (might be due to invalid IL or missing references)
        //IL_151b: Unknown result type (might be due to invalid IL or missing references)
        //IL_151f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1524: Unknown result type (might be due to invalid IL or missing references)
        //IL_152c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1533: Unknown result type (might be due to invalid IL or missing references)
        //IL_153a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1541: Unknown result type (might be due to invalid IL or missing references)
        //IL_35b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_35c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_35c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_35d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_35df: Unknown result type (might be due to invalid IL or missing references)
        //IL_35e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_35e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_35f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_365d: Unknown result type (might be due to invalid IL or missing references)
        //IL_3686: Unknown result type (might be due to invalid IL or missing references)
        //IL_24ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_24fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2512: Unknown result type (might be due to invalid IL or missing references)
        //IL_2517: Unknown result type (might be due to invalid IL or missing references)
        //IL_2519: Unknown result type (might be due to invalid IL or missing references)
        //IL_251b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2527: Unknown result type (might be due to invalid IL or missing references)
        //IL_253e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2543: Unknown result type (might be due to invalid IL or missing references)
        //IL_2556: Unknown result type (might be due to invalid IL or missing references)
        //IL_255c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2572: Unknown result type (might be due to invalid IL or missing references)
        //IL_2574: Unknown result type (might be due to invalid IL or missing references)
        //IL_257e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2583: Unknown result type (might be due to invalid IL or missing references)
        //IL_23a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_23bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c30: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c36: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c40: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d71: Unknown result type (might be due to invalid IL or missing references)
        //IL_26c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_26cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_26d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_26d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_36c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_36e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_36e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ca0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cab: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c76: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c78: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ccc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cd7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3735: Unknown result type (might be due to invalid IL or missing references)
        //IL_375f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3765: Unknown result type (might be due to invalid IL or missing references)
        //IL_37aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_37b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_37b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_37ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d05: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d22: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d31: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d49: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d58: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d66: Unknown result type (might be due to invalid IL or missing references)
        //IL_4285: Unknown result type (might be due to invalid IL or missing references)
        //IL_4296: Unknown result type (might be due to invalid IL or missing references)
        //IL_44a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_44ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_44b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_44b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_482f: Unknown result type (might be due to invalid IL or missing references)
        //IL_47ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_47fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_46e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_4704: Unknown result type (might be due to invalid IL or missing references)
        //IL_44f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_450c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3edb: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ee0: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ee5: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cbc: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_452e: Unknown result type (might be due to invalid IL or missing references)
        //IL_4544: Unknown result type (might be due to invalid IL or missing references)
        //IL_457e: Unknown result type (might be due to invalid IL or missing references)
        //IL_4594: Unknown result type (might be due to invalid IL or missing references)
        //IL_4762: Unknown result type (might be due to invalid IL or missing references)
        //IL_4773: Unknown result type (might be due to invalid IL or missing references)
        //IL_4778: Unknown result type (might be due to invalid IL or missing references)
        //IL_477d: Unknown result type (might be due to invalid IL or missing references)
        //IL_45bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_45d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_43bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_43cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fce: Unknown result type (might be due to invalid IL or missing references)
        //IL_45f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_460e: Unknown result type (might be due to invalid IL or missing references)
        //IL_43ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_43f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_43f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_43fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_440e: Unknown result type (might be due to invalid IL or missing references)
        //IL_441e: Unknown result type (might be due to invalid IL or missing references)
        //IL_4423: Unknown result type (might be due to invalid IL or missing references)
        //IL_4427: Unknown result type (might be due to invalid IL or missing references)
        //IL_4431: Unknown result type (might be due to invalid IL or missing references)
        //IL_4436: Unknown result type (might be due to invalid IL or missing references)
        //IL_4438: Unknown result type (might be due to invalid IL or missing references)
        //IL_4442: Unknown result type (might be due to invalid IL or missing references)
        //IL_4447: Unknown result type (might be due to invalid IL or missing references)
        //IL_408d: Unknown result type (might be due to invalid IL or missing references)
        //IL_4093: Unknown result type (might be due to invalid IL or missing references)
        //IL_4098: Unknown result type (might be due to invalid IL or missing references)
        //IL_409d: Unknown result type (might be due to invalid IL or missing references)
        //IL_40a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_40a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_40aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_40af: Unknown result type (might be due to invalid IL or missing references)
        //IL_4e7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_4e89: Unknown result type (might be due to invalid IL or missing references)
        //IL_4e8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_4635: Unknown result type (might be due to invalid IL or missing references)
        //IL_464b: Unknown result type (might be due to invalid IL or missing references)
        //IL_500b: Unknown result type (might be due to invalid IL or missing references)
        //IL_5015: Unknown result type (might be due to invalid IL or missing references)
        //IL_501a: Unknown result type (might be due to invalid IL or missing references)
        //IL_7a21: Unknown result type (might be due to invalid IL or missing references)
        //IL_7a30: Unknown result type (might be due to invalid IL or missing references)
        //IL_7a35: Unknown result type (might be due to invalid IL or missing references)
        //IL_79dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_79ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_51d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_51df: Unknown result type (might be due to invalid IL or missing references)
        //IL_51e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_411f: Unknown result type (might be due to invalid IL or missing references)
        //IL_4123: Unknown result type (might be due to invalid IL or missing references)
        //IL_4128: Unknown result type (might be due to invalid IL or missing references)
        //IL_410d: Unknown result type (might be due to invalid IL or missing references)
        //IL_410f: Unknown result type (might be due to invalid IL or missing references)
        //IL_4111: Unknown result type (might be due to invalid IL or missing references)
        //IL_4116: Unknown result type (might be due to invalid IL or missing references)
        //IL_7a6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_7a79: Unknown result type (might be due to invalid IL or missing references)
        //IL_7a7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_7a81: Unknown result type (might be due to invalid IL or missing references)
        //IL_7a90: Unknown result type (might be due to invalid IL or missing references)
        //IL_7a95: Unknown result type (might be due to invalid IL or missing references)
        //IL_7a9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_416b: Unknown result type (might be due to invalid IL or missing references)
        //IL_418a: Unknown result type (might be due to invalid IL or missing references)
        //IL_4191: Unknown result type (might be due to invalid IL or missing references)
        //IL_4140: Unknown result type (might be due to invalid IL or missing references)
        //IL_4146: Unknown result type (might be due to invalid IL or missing references)
        //IL_414b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4150: Unknown result type (might be due to invalid IL or missing references)
        //IL_4159: Unknown result type (might be due to invalid IL or missing references)
        //IL_415d: Unknown result type (might be due to invalid IL or missing references)
        //IL_4162: Unknown result type (might be due to invalid IL or missing references)
        //IL_7ac2: Unknown result type (might be due to invalid IL or missing references)
        //IL_7acc: Unknown result type (might be due to invalid IL or missing references)
        //IL_7ad1: Unknown result type (might be due to invalid IL or missing references)
        //IL_7ad4: Unknown result type (might be due to invalid IL or missing references)
        //IL_7ae3: Unknown result type (might be due to invalid IL or missing references)
        //IL_7ae8: Unknown result type (might be due to invalid IL or missing references)
        //IL_7aed: Unknown result type (might be due to invalid IL or missing references)
        //IL_7b15: Unknown result type (might be due to invalid IL or missing references)
        //IL_7b1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_7b24: Unknown result type (might be due to invalid IL or missing references)
        //IL_7b27: Unknown result type (might be due to invalid IL or missing references)
        //IL_7b36: Unknown result type (might be due to invalid IL or missing references)
        //IL_7b3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_7b40: Unknown result type (might be due to invalid IL or missing references)
        //IL_92e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_931d: Unknown result type (might be due to invalid IL or missing references)
        //IL_7d4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_7c04: Unknown result type (might be due to invalid IL or missing references)
        //IL_93a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_93b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_544d: Unknown result type (might be due to invalid IL or missing references)
        //IL_5457: Unknown result type (might be due to invalid IL or missing references)
        //IL_545c: Unknown result type (might be due to invalid IL or missing references)
        //IL_7d6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_7d88: Unknown result type (might be due to invalid IL or missing references)
        //IL_7c4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_7ca0: Unknown result type (might be due to invalid IL or missing references)
        //IL_8303: Unknown result type (might be due to invalid IL or missing references)
        //IL_7cee: Unknown result type (might be due to invalid IL or missing references)
        //IL_9458: Unknown result type (might be due to invalid IL or missing references)
        //IL_945e: Unknown result type (might be due to invalid IL or missing references)
        //IL_9463: Unknown result type (might be due to invalid IL or missing references)
        //IL_9468: Unknown result type (might be due to invalid IL or missing references)
        //IL_9471: Unknown result type (might be due to invalid IL or missing references)
        //IL_9478: Unknown result type (might be due to invalid IL or missing references)
        //IL_947d: Unknown result type (might be due to invalid IL or missing references)
        //IL_9498: Unknown result type (might be due to invalid IL or missing references)
        //IL_94a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_94ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_94b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_8d21: Unknown result type (might be due to invalid IL or missing references)
        //IL_8bb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_8bcc: Unknown result type (might be due to invalid IL or missing references)
        //IL_8a81: Unknown result type (might be due to invalid IL or missing references)
        //IL_8321: Unknown result type (might be due to invalid IL or missing references)
        //IL_833e: Unknown result type (might be due to invalid IL or missing references)
        //IL_7e64: Unknown result type (might be due to invalid IL or missing references)
        //IL_7e77: Unknown result type (might be due to invalid IL or missing references)
        //IL_8d3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_8d5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_8be9: Unknown result type (might be due to invalid IL or missing references)
        //IL_8c02: Unknown result type (might be due to invalid IL or missing references)
        //IL_8aa2: Unknown result type (might be due to invalid IL or missing references)
        //IL_8abf: Unknown result type (might be due to invalid IL or missing references)
        //IL_870a: Unknown result type (might be due to invalid IL or missing references)
        //IL_871d: Unknown result type (might be due to invalid IL or missing references)
        //IL_7eb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_7ec9: Unknown result type (might be due to invalid IL or missing references)
        //IL_7ee2: Unknown result type (might be due to invalid IL or missing references)
        //IL_7eed: Unknown result type (might be due to invalid IL or missing references)
        //IL_873a: Unknown result type (might be due to invalid IL or missing references)
        //IL_8745: Unknown result type (might be due to invalid IL or missing references)
        //IL_875e: Unknown result type (might be due to invalid IL or missing references)
        //IL_8769: Unknown result type (might be due to invalid IL or missing references)
        //IL_80c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_80ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_80cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_80d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_80da: Unknown result type (might be due to invalid IL or missing references)
        //IL_80ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_80f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_80f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_8102: Unknown result type (might be due to invalid IL or missing references)
        //IL_8107: Unknown result type (might be due to invalid IL or missing references)
        //IL_810c: Unknown result type (might be due to invalid IL or missing references)
        //IL_811d: Unknown result type (might be due to invalid IL or missing references)
        //IL_8127: Unknown result type (might be due to invalid IL or missing references)
        //IL_813b: Unknown result type (might be due to invalid IL or missing references)
        //IL_8145: Unknown result type (might be due to invalid IL or missing references)
        //IL_814a: Unknown result type (might be due to invalid IL or missing references)
        //IL_814f: Unknown result type (might be due to invalid IL or missing references)
        //IL_8156: Unknown result type (might be due to invalid IL or missing references)
        //IL_815f: Unknown result type (might be due to invalid IL or missing references)
        //IL_8166: Unknown result type (might be due to invalid IL or missing references)
        //IL_816f: Unknown result type (might be due to invalid IL or missing references)
        //IL_8198: Unknown result type (might be due to invalid IL or missing references)
        //IL_819a: Unknown result type (might be due to invalid IL or missing references)
        //IL_81a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_81ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_81b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_81b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_9f50: Unknown result type (might be due to invalid IL or missing references)
        //IL_9f5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_83ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_83f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_83f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_83f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_8405: Unknown result type (might be due to invalid IL or missing references)
        //IL_8425: Unknown result type (might be due to invalid IL or missing references)
        //IL_969a: Unknown result type (might be due to invalid IL or missing references)
        //IL_96b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_843c: Unknown result type (might be due to invalid IL or missing references)
        //IL_844f: Unknown result type (might be due to invalid IL or missing references)
        //IL_99db: Unknown result type (might be due to invalid IL or missing references)
        //IL_99f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_96c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_96df: Unknown result type (might be due to invalid IL or missing references)
        //IL_96ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_970c: Unknown result type (might be due to invalid IL or missing references)
        //IL_8fd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_8fd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_8fdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_8fe2: Unknown result type (might be due to invalid IL or missing references)
        //IL_900f: Unknown result type (might be due to invalid IL or missing references)
        //IL_8ef9: Unknown result type (might be due to invalid IL or missing references)
        //IL_8eff: Unknown result type (might be due to invalid IL or missing references)
        //IL_8f04: Unknown result type (might be due to invalid IL or missing references)
        //IL_8f09: Unknown result type (might be due to invalid IL or missing references)
        //IL_8f14: Unknown result type (might be due to invalid IL or missing references)
        //IL_8508: Unknown result type (might be due to invalid IL or missing references)
        //IL_851c: Unknown result type (might be due to invalid IL or missing references)
        //IL_8521: Unknown result type (might be due to invalid IL or missing references)
        //IL_8526: Unknown result type (might be due to invalid IL or missing references)
        //IL_8535: Unknown result type (might be due to invalid IL or missing references)
        //IL_853a: Unknown result type (might be due to invalid IL or missing references)
        //IL_8542: Unknown result type (might be due to invalid IL or missing references)
        //IL_8547: Unknown result type (might be due to invalid IL or missing references)
        //IL_8549: Unknown result type (might be due to invalid IL or missing references)
        //IL_9a0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_9a20: Unknown result type (might be due to invalid IL or missing references)
        //IL_9a30: Unknown result type (might be due to invalid IL or missing references)
        //IL_9a4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_97b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_97eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_9887: Unknown result type (might be due to invalid IL or missing references)
        //IL_988e: Unknown result type (might be due to invalid IL or missing references)
        //IL_90cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_90d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_90da: Unknown result type (might be due to invalid IL or missing references)
        //IL_90df: Unknown result type (might be due to invalid IL or missing references)
        //IL_90ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_9103: Unknown result type (might be due to invalid IL or missing references)
        //IL_9109: Unknown result type (might be due to invalid IL or missing references)
        //IL_911b: Unknown result type (might be due to invalid IL or missing references)
        //IL_856b: Unknown result type (might be due to invalid IL or missing references)
        //IL_857c: Unknown result type (might be due to invalid IL or missing references)
        //IL_858d: Unknown result type (might be due to invalid IL or missing references)
        //IL_8597: Unknown result type (might be due to invalid IL or missing references)
        //IL_859f: Unknown result type (might be due to invalid IL or missing references)
        //IL_9af2: Unknown result type (might be due to invalid IL or missing references)
        //IL_9b2b: Unknown result type (might be due to invalid IL or missing references)
        //IL_9bc3: Unknown result type (might be due to invalid IL or missing references)
        //IL_9bca: Unknown result type (might be due to invalid IL or missing references)
        //IL_9028: Unknown result type (might be due to invalid IL or missing references)
        //IL_902d: Unknown result type (might be due to invalid IL or missing references)
        //IL_9050: Unknown result type (might be due to invalid IL or missing references)
        //IL_9056: Unknown result type (might be due to invalid IL or missing references)
        //IL_9065: Unknown result type (might be due to invalid IL or missing references)
        //IL_906f: Unknown result type (might be due to invalid IL or missing references)
        //IL_9081: Unknown result type (might be due to invalid IL or missing references)
        //IL_9086: Unknown result type (might be due to invalid IL or missing references)
        //IL_908b: Unknown result type (might be due to invalid IL or missing references)
        //IL_9090: Unknown result type (might be due to invalid IL or missing references)
        //IL_90a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_90ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_90b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_90b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_8f2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_8f32: Unknown result type (might be due to invalid IL or missing references)
        //IL_8f58: Unknown result type (might be due to invalid IL or missing references)
        //IL_8f5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_8f6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_8f77: Unknown result type (might be due to invalid IL or missing references)
        //IL_8f7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_8f87: Unknown result type (might be due to invalid IL or missing references)
        //IL_8f8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_8f91: Unknown result type (might be due to invalid IL or missing references)
        //IL_8fa9: Unknown result type (might be due to invalid IL or missing references)
        //IL_8faf: Unknown result type (might be due to invalid IL or missing references)
        //IL_8fb4: Unknown result type (might be due to invalid IL or missing references)
        //IL_8fb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_85b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_85be: Unknown result type (might be due to invalid IL or missing references)
        //IL_85c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_85c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_85d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_9135: Unknown result type (might be due to invalid IL or missing references)
        //IL_913a: Unknown result type (might be due to invalid IL or missing references)
        //IL_913f: Unknown result type (might be due to invalid IL or missing references)
        //IL_9197: Unknown result type (might be due to invalid IL or missing references)
        //IL_919d: Unknown result type (might be due to invalid IL or missing references)
        //IL_91a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_91a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_85f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_8609: Unknown result type (might be due to invalid IL or missing references)
        //IL_8617: Unknown result type (might be due to invalid IL or missing references)
        //IL_861c: Unknown result type (might be due to invalid IL or missing references)
        //IL_8621: Unknown result type (might be due to invalid IL or missing references)
        //IL_8629: Unknown result type (might be due to invalid IL or missing references)
        //IL_8630: Unknown result type (might be due to invalid IL or missing references)
        //IL_8637: Unknown result type (might be due to invalid IL or missing references)
        //IL_863e: Unknown result type (might be due to invalid IL or missing references)
        //IL_5566: Unknown result type (might be due to invalid IL or missing references)
        //IL_5570: Unknown result type (might be due to invalid IL or missing references)
        //IL_5575: Unknown result type (might be due to invalid IL or missing references)
        //IL_5b9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ba6: Unknown result type (might be due to invalid IL or missing references)
        //IL_5bab: Unknown result type (might be due to invalid IL or missing references)
        //IL_bc0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_bc17: Unknown result type (might be due to invalid IL or missing references)
        //IL_bfae: Unknown result type (might be due to invalid IL or missing references)
        //IL_bfb3: Unknown result type (might be due to invalid IL or missing references)
        //IL_bfd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_c008: Unknown result type (might be due to invalid IL or missing references)
        //IL_bc90: Unknown result type (might be due to invalid IL or missing references)
        //IL_bc9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_ddc0: Unknown result type (might be due to invalid IL or missing references)
        //IL_dde0: Unknown result type (might be due to invalid IL or missing references)
        //IL_ddf4: Unknown result type (might be due to invalid IL or missing references)
        //IL_ddf9: Unknown result type (might be due to invalid IL or missing references)
        //IL_de26: Unknown result type (might be due to invalid IL or missing references)
        //IL_de4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_b301: Unknown result type (might be due to invalid IL or missing references)
        //IL_b31e: Unknown result type (might be due to invalid IL or missing references)
        //IL_b8b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_b8c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_baef: Unknown result type (might be due to invalid IL or missing references)
        //IL_bafe: Unknown result type (might be due to invalid IL or missing references)
        //IL_bb03: Unknown result type (might be due to invalid IL or missing references)
        //IL_bb08: Unknown result type (might be due to invalid IL or missing references)
        //IL_b35e: Unknown result type (might be due to invalid IL or missing references)
        //IL_b36d: Unknown result type (might be due to invalid IL or missing references)
        //IL_b372: Unknown result type (might be due to invalid IL or missing references)
        //IL_b385: Unknown result type (might be due to invalid IL or missing references)
        //IL_b8db: Unknown result type (might be due to invalid IL or missing references)
        //IL_b8ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_c1e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_b91e: Unknown result type (might be due to invalid IL or missing references)
        //IL_b92f: Unknown result type (might be due to invalid IL or missing references)
        //IL_b46b: Unknown result type (might be due to invalid IL or missing references)
        //IL_b4c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_c20a: Unknown result type (might be due to invalid IL or missing references)
        //IL_b941: Unknown result type (might be due to invalid IL or missing references)
        //IL_b954: Unknown result type (might be due to invalid IL or missing references)
        //IL_b9c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_b9d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_b9d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_d2bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_c60e: Unknown result type (might be due to invalid IL or missing references)
        //IL_c626: Unknown result type (might be due to invalid IL or missing references)
        //IL_d551: Unknown result type (might be due to invalid IL or missing references)
        //IL_d55c: Unknown result type (might be due to invalid IL or missing references)
        //IL_d56c: Unknown result type (might be due to invalid IL or missing references)
        //IL_d582: Unknown result type (might be due to invalid IL or missing references)
        //IL_a686: Unknown result type (might be due to invalid IL or missing references)
        //IL_a634: Unknown result type (might be due to invalid IL or missing references)
        //IL_a644: Unknown result type (might be due to invalid IL or missing references)
        //IL_a649: Unknown result type (might be due to invalid IL or missing references)
        //IL_a64e: Unknown result type (might be due to invalid IL or missing references)
        //IL_d5d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_d5ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_d6ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_d6f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_d725: Unknown result type (might be due to invalid IL or missing references)
        //IL_d73d: Unknown result type (might be due to invalid IL or missing references)
        //IL_6322: Unknown result type (might be due to invalid IL or missing references)
        //IL_632c: Unknown result type (might be due to invalid IL or missing references)
        //IL_6331: Unknown result type (might be due to invalid IL or missing references)
        //IL_a827: Unknown result type (might be due to invalid IL or missing references)
        //IL_64a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_64b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_64b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_65cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_65d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_65dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_6731: Unknown result type (might be due to invalid IL or missing references)
        //IL_673b: Unknown result type (might be due to invalid IL or missing references)
        //IL_6740: Unknown result type (might be due to invalid IL or missing references)
        //IL_6895: Unknown result type (might be due to invalid IL or missing references)
        //IL_689f: Unknown result type (might be due to invalid IL or missing references)
        //IL_68a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_69f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_6a00: Unknown result type (might be due to invalid IL or missing references)
        //IL_6a05: Unknown result type (might be due to invalid IL or missing references)
        //IL_61ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_61f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_61fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f48: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_6e7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_6e88: Unknown result type (might be due to invalid IL or missing references)
        //IL_6e8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_6f88: Unknown result type (might be due to invalid IL or missing references)
        //IL_6f9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_6eaf: Unknown result type (might be due to invalid IL or missing references)
        //IL_6eb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_6ebe: Unknown result type (might be due to invalid IL or missing references)
        //IL_715e: Unknown result type (might be due to invalid IL or missing references)
        //IL_7165: Unknown result type (might be due to invalid IL or missing references)
        //IL_716a: Unknown result type (might be due to invalid IL or missing references)
        //IL_6c56: Unknown result type (might be due to invalid IL or missing references)
        //IL_6c60: Unknown result type (might be due to invalid IL or missing references)
        //IL_6c65: Unknown result type (might be due to invalid IL or missing references)
        //IL_72e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_72eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_72f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_73f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_7402: Unknown result type (might be due to invalid IL or missing references)
        //IL_7407: Unknown result type (might be due to invalid IL or missing references)
        //IL_740c: Unknown result type (might be due to invalid IL or missing references)
        //IL_7440: Unknown result type (might be due to invalid IL or missing references)
        //IL_7453: Unknown result type (might be due to invalid IL or missing references)
        //IL_ad93: Unknown result type (might be due to invalid IL or missing references)
        //IL_ad98: Unknown result type (might be due to invalid IL or missing references)
        //IL_adaf: Unknown result type (might be due to invalid IL or missing references)
        //IL_adb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_adc0: Unknown result type (might be due to invalid IL or missing references)
        //IL_ade3: Unknown result type (might be due to invalid IL or missing references)
        //IL_adfd: Unknown result type (might be due to invalid IL or missing references)
        //IL_ae04: Unknown result type (might be due to invalid IL or missing references)
        //IL_ae09: Unknown result type (might be due to invalid IL or missing references)
        //IL_afb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_afc0: Unknown result type (might be due to invalid IL or missing references)
        //IL_aec3: Unknown result type (might be due to invalid IL or missing references)
        //IL_aee8: Unknown result type (might be due to invalid IL or missing references)
        //IL_af52: Unknown result type (might be due to invalid IL or missing references)
        //IL_af59: Unknown result type (might be due to invalid IL or missing references)
        //IL_b12f: Unknown result type (might be due to invalid IL or missing references)
        //IL_b136: Unknown result type (might be due to invalid IL or missing references)
        //IL_b0c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_b0cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_b11d: Unknown result type (might be due to invalid IL or missing references)
        //IL_b122: Unknown result type (might be due to invalid IL or missing references)
        //IL_b018: Unknown result type (might be due to invalid IL or missing references)
        //IL_b02d: Unknown result type (might be due to invalid IL or missing references)
        //IL_77c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_77cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_77d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_77d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_7905: Unknown result type (might be due to invalid IL or missing references)
        //IL_790f: Unknown result type (might be due to invalid IL or missing references)
        //IL_7914: Unknown result type (might be due to invalid IL or missing references)
        if (Main.player[target].position.Y + (float)Main.player[target].height == position.Y + (float)height)
        {
            directionY = -1;
        }
        bool flag = false;
        if (type == 624 && AI_003_Gnomes_ShouldTurnToStone())
        {
            int num = (int)(base.Center.X / 16f);
            int num110 = (int)(base.Bottom.Y / 16f);
            position += netOffset;
            int num127 = Dust.NewDust(position, width, height, 43, 0f, 0f, 254, Color.White, 0.5f);
            Dust obj = Main.dust[num127];
            obj.velocity *= 0.2f;
            position -= netOffset;
            if (WorldGen.SolidTileAllowBottomSlope(num, num110))
            {
                for (int i = 0; i < 5; i++)
                {
                    position += netOffset;
                    int num138 = Dust.NewDust(position, width, height, 43, 0f, 0f, 254, Color.White, 0.5f);
                    Dust obj2 = Main.dust[num138];
                    obj2.velocity *= 0.2f;
                    position -= netOffset;
                }
                if (Main.netMode != 1 && TileObject.CanPlace(num, num110 - 1, 567, 0, direction, out var _, onlyCheck: true) && WorldGen.PlaceTile(num, num110 - 1, 567, mute: false, forced: false, -1, Main.rand.Next(5)))
                {
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, num, num110 - 2, 1, 2);
                    }
                    if (Main.netMode != 1)
                    {
                        if (IsNPCValidForBestiaryKillCredit())
{
                            Main.BestiaryTracker.Kills.RegisterKill(this);
                        }
                        CountKillForBannersAndDropThem();
                    }
                    life = 0;
                    active = false;
                    AchievementsHelper.NotifyProgressionEvent(24);
                    return;
                }
            }
        }
        Vector2 val;
        if (type == 466)
        {
            int num148 = 200;
            if (ai[2] == 0f)
            {
                alpha = num148;
                TargetClosest();
                if (!Main.player[target].dead)
                {
                    val = Main.player[target].Center - base.Center;
                    if (((Vector2)(ref val)).Length() < 170f)
                    {
                        ai[2] = -16f;
                    }
                }
                if (velocity.X != 0f || velocity.Y < 0f || velocity.Y > 2f || justHit)
                {
                    ai[2] = -16f;
                }
                return;
            }
            if (ai[2] < 0f)
            {
                if (alpha > 0)
                {
                    alpha -= num148 / 16;
                    if (alpha < 0)
                    {
                        alpha = 0;
                    }
                }
                ai[2] += 1f;
                if (ai[2] == 0f)
                {
                    ai[2] = 1f;
                    velocity.X = direction * 2;
                }
                return;
            }
            alpha = 0;
        }
        if (type == 166)
        {
            if (Main.netMode != 1 && Main.rand.Next(240) == 0)
            {
                ai[2] = Main.rand.Next(-480, -60);
                netUpdate = true;
            }
            if (ai[2] < 0f)
            {
                TargetClosest();
                if (justHit)
                {
                    ai[2] = 0f;
                }
                if (Collision.CanHit(base.Center, 1, 1, Main.player[target].Center, 1, 1))
                {
                    ai[2] = 0f;
                }
            }
            if (ai[2] < 0f)
            {
                velocity.X *= 0.9f;
                if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
                {
                    velocity.X = 0f;
                }
                ai[2] += 1f;
                if (ai[2] == 0f)
                {
                    velocity.X = (float)direction * 0.1f;
                }
                return;
            }
        }
        if (type == 461)
        {
            if (wet)
            {
                knockBackResist = 0f;
                ai[3] = -0.10101f;
                noGravity = true;
                Vector2 center = base.Center;
                width = 34;
                height = 24;
                position.X = center.X - (float)(width / 2);
                position.Y = center.Y - (float)(height / 2);
                TargetClosest();
                if (collideX)
                {
                    velocity.X = 0f - oldVelocity.X;
                }
                if (velocity.X < 0f)
                {
                    direction = -1;
                }
                if (velocity.X > 0f)
                {
                    direction = 1;
                }
                if (Collision.CanHit(position, width, height, Main.player[target].Center, 1, 1))
                {
                    Vector2 vector = Main.player[target].Center - base.Center;
                    ((Vector2)(ref vector)).Normalize();
                    vector *= 5f;
                    velocity = (velocity * 19f + vector) / 20f;
                    return;
                }
                float num158 = 5f;
                if (velocity.Y > 0f)
                {
                    num158 = 3f;
                }
                if (velocity.Y < 0f)
                {
                    num158 = 8f;
                }
                Vector2 vector10 = default(Vector2);
                ((Vector2)(ref vector10))._002Ector((float)direction, -1f);
                ((Vector2)(ref vector10)).Normalize();
                vector10 *= num158;
                if (num158 < 5f)
                {
                    velocity = (velocity * 24f + vector10) / 25f;
                }
                else
                {
                    velocity = (velocity * 9f + vector10) / 10f;
                }
                return;
            }
            knockBackResist = 0.4f * Main.GameModeInfo.KnockbackToEnemiesMultiplier;
            noGravity = false;
            Vector2 center2 = base.Center;
            width = 18;
            height = 40;
            position.X = center2.X - (float)(width / 2);
            position.Y = center2.Y - (float)(height / 2);
            if (ai[3] == -0.10101f)
            {
                ai[3] = 0f;
                float num169 = ((Vector2)(ref velocity)).Length();
                num169 *= 2f;
                if (num169 > 10f)
                {
                    num169 = 10f;
                }
                ((Vector2)(ref velocity)).Normalize();
                velocity *= num169;
                if (velocity.X < 0f)
                {
                    direction = -1;
                }
                if (velocity.X > 0f)
                {
                    direction = 1;
                }
                spriteDirection = direction;
            }
        }
        if (type == 586)
        {
            if (alpha == 255)
            {
                TargetClosest();
                spriteDirection = direction;
                velocity.Y = -6f;
                netUpdate = true;
                for (int j = 0; j < 35; j++)
                {
                    Dust dust6 = Dust.NewDustDirect(position, width, height, 5);
                    dust6.velocity *= 1f;
                    dust6.scale = 1f + Main.rand.NextFloat() * 0.5f;
                    dust6.fadeIn = 1.5f + Main.rand.NextFloat() * 0.5f;
                    dust6.velocity += velocity * 0.5f;
                }
            }
            alpha -= 15;
            if (alpha < 0)
            {
                alpha = 0;
            }
            position += netOffset;
            if (alpha != 0)
            {
                for (int k = 0; k < 2; k++)
                {
                    Dust dust7 = Dust.NewDustDirect(position, width, height, 5);
                    dust7.velocity *= 1f;
                    dust7.scale = 1f + Main.rand.NextFloat() * 0.5f;
                    dust7.fadeIn = 1.5f + Main.rand.NextFloat() * 0.5f;
                    dust7.velocity += velocity * 0.3f;
                }
            }
            if (Main.rand.Next(3) == 0)
            {
                Dust dust8 = Dust.NewDustDirect(position, width, height, 5);
                dust8.velocity *= 0f;
                dust8.alpha = 120;
                dust8.scale = 0.7f + Main.rand.NextFloat() * 0.5f;
                dust8.velocity += velocity * 0.3f;
            }
            position -= netOffset;
            if (wet)
            {
                knockBackResist = 0f;
                ai[3] = -0.10101f;
                noGravity = true;
                Vector2 center3 = base.Center;
                position.X = center3.X - (float)(width / 2);
                position.Y = center3.Y - (float)(height / 2);
                TargetClosest();
                if (collideX)
                {
                    velocity.X = 0f - oldVelocity.X;
                }
                if (velocity.X < 0f)
                {
                    direction = -1;
                }
                if (velocity.X > 0f)
                {
                    direction = 1;
                }
                if (Collision.CanHit(position, width, height, Main.player[target].Center, 1, 1))
                {
                    Vector2 vector21 = Main.player[target].Center - base.Center;
                    ((Vector2)(ref vector21)).Normalize();
                    float num180 = 1f;
                    num180 += Math.Abs(base.Center.Y - Main.player[target].Center.Y) / 40f;
                    num180 = MathHelper.Clamp(num180, 5f, 20f);
                    vector21 *= num180;
                    if (velocity.Y > 0f)
                    {
                        velocity = (velocity * 29f + vector21) / 30f;
                    }
                    else
                    {
                        velocity = (velocity * 4f + vector21) / 5f;
                    }
                    return;
                }
                float num191 = 5f;
                if (velocity.Y > 0f)
                {
                    num191 = 3f;
                }
                if (velocity.Y < 0f)
                {
                    num191 = 8f;
                }
                Vector2 vector31 = default(Vector2);
                ((Vector2)(ref vector31))._002Ector((float)direction, -1f);
                ((Vector2)(ref vector31)).Normalize();
                vector31 *= num191;
                if (num191 < 5f)
                {
                    velocity = (velocity * 24f + vector31) / 25f;
                }
                else
                {
                    velocity = (velocity * 9f + vector31) / 10f;
                }
                return;
            }
            noGravity = false;
            Vector2 center4 = base.Center;
            position.X = center4.X - (float)(width / 2);
            position.Y = center4.Y - (float)(height / 2);
            if (ai[3] == -0.10101f)
            {
                ai[3] = 0f;
                float num2 = ((Vector2)(ref velocity)).Length();
                num2 *= 2f;
                if (num2 > 15f)
                {
                    num2 = 15f;
                }
                ((Vector2)(ref velocity)).Normalize();
                velocity *= num2;
                if (velocity.X < 0f)
                {
                    direction = -1;
                }
                if (velocity.X > 0f)
                {
                    direction = 1;
                }
                spriteDirection = direction;
            }
        }
        if (type == 379 || type == 380)
        {
            if (ai[3] < 0f)
            {
                directionY = -1;
                flag = false;
                damage = 0;
                velocity.X *= 0.93f;
                if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
                {
                    velocity.X = 0f;
                }
                int num13 = (int)(0f - ai[3] - 1f);
                int num24 = Math.Sign(Main.npc[num13].Center.X - base.Center.X);
                if (num24 != direction)
                {
                    velocity.X = 0f;
                    direction = num24;
                    netUpdate = true;
                }
                if (justHit && Main.netMode != 1 && Main.npc[num13].localAI[0] == 0f)
                {
                    Main.npc[num13].localAI[0] = 1f;
                }
                if (ai[0] < 1000f)
                {
                    ai[0] = 1000f;
                }
                if ((ai[0] += 1f) >= 1300f)
                {
                    ai[0] = 1000f;
                    netUpdate = true;
                }
                return;
            }
            if (ai[0] >= 1000f)
            {
                ai[0] = 0f;
            }
            damage = defDamage;
        }
        if (type == 383 && ai[2] == 0f && localAI[0] == 0f && Main.netMode != 1)
        {
            int num34 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X, (int)base.Center.Y, 384, whoAmI);
            ai[2] = num34 + 1;
            localAI[0] = -1f;
            netUpdate = true;
            Main.npc[num34].ai[0] = whoAmI;
            Main.npc[num34].netUpdate = true;
        }
        if (type == 383)
        {
            int num45 = (int)ai[2] - 1;
            if (num45 != -1 && Main.npc[num45].active && Main.npc[num45].type == 384)
            {
                dontTakeDamage = true;
            }
            else
            {
                dontTakeDamage = false;
                ai[2] = 0f;
                if (localAI[0] == -1f)
                {
                    localAI[0] = 180f;
                }
                if (localAI[0] > 0f)
                {
                    localAI[0] -= 1f;
                }
            }
        }
        if (type == 482)
        {
            int num56 = 300;
            int num67 = 120;
            dontTakeDamage = false;
            if (ai[2] < 0f)
            {
                dontTakeDamage = true;
                ai[2] += 1f;
                velocity.X *= 0.9f;
                if ((double)Math.Abs(velocity.X) < 0.001)
                {
                    velocity.X = 0.001f * (float)direction;
                }
                if (Math.Abs(velocity.Y) > 1f)
                {
                    ai[2] += 10f;
                }
                if (ai[2] >= 0f)
                {
                    netUpdate = true;
                    velocity.X += (float)direction * 0.3f;
                }
                return;
            }
            if (ai[2] < (float)num56)
            {
                if (justHit)
                {
                    ai[2] += 15f;
                }
                ai[2] += 1f;
            }
            else if (velocity.Y == 0f)
            {
                ai[2] = -num67;
                netUpdate = true;
            }
        }
        Rectangle hitbox;
        if (type == 631)
        {
            if (target < 0 || target == 255 || Main.player[target].dead || !Main.player[target].active)
            {
                TargetClosest(ai[2] > 0f);
            }
            Player player = Main.player[target];
            bool flag12 = !player.dead && player.active && base.Center.Distance(player.Center) < 320f;
            int num78 = 100;
            int num89 = 32;
            if (ai[2] == 0f)
            {
                ai[3] = 65f;
                if (flag12 && Collision.CanHit(player, this))
                {
                    ai[2] = num78;
                    ai[3] = 0f;
                    velocity.X = (float)direction * 0.01f;
                    netUpdate = true;
                }
            }
            else
            {
                if (ai[2] < (float)num78)
                {
                    ai[2] += 1f;
                    velocity.X *= 0.9f;
                    if ((double)Math.Abs(velocity.X) < 0.001)
                    {
                        velocity.X = 0f;
                    }
                    if (Math.Abs(velocity.Y) > 1f)
                    {
                        ai[2] = 0f;
                    }
                    if (ai[2] == (float)(num78 - num89 / 2) && Main.netMode != 1)
                    {
                        hitbox = player.Hitbox;
                        if (!((Rectangle)(ref hitbox)).Intersects(base.Hitbox) && Collision.CanHit(player, this))
{
                            float num99 = 8f;
                            Vector2 center5 = base.Center;
                            Vector2 vector32 = DirectionTo(Main.player[target].Center) * num99;
                            if (vector32.HasNaNs())
{
                                ((Vector2)(ref vector32))._002Ector((float)direction * num99, 0f);
                            }
                            int num111 = 20;
                            Vector2 v = vector32 + Utils.RandomVector2(Main.rand, -0.8f, 0.8f);
                            v = v.SafeNormalize(Vector2.Zero);
                            v *= num99;
                            Projectile.NewProjectile(GetSpawnSource_ForProjectile(), center5.X, center5.Y, v.X, v.Y, 909, num111, 1f, Main.myPlayer);
                        }
                    }
                    if (ai[2] >= (float)num78)
                    {
                        ai[2] = num78;
                        ai[3] = 0f;
                        velocity.X = (float)direction * 0.01f;
                        netUpdate = true;
                    }
                    return;
                }
                if (velocity.Y == 0f && flag12)
                {
                    hitbox = player.Hitbox;
                    if (((Rectangle)(ref hitbox)).Intersects(base.Hitbox) || Collision.CanHit(player, this))
                    {
                        ai[2] = num78 - num89;
                        netUpdate = true;
                    }
                }
            }
        }
        if (type == 480)
        {
            int num118 = 180;
            int num119 = 300;
            int num120 = 180;
            int num121 = 60;
            int num122 = 20;
            if (life < lifeMax / 3)
            {
                num118 = 120;
                num119 = 240;
                num120 = 240;
                num121 = 90;
            }
            if (ai[2] > 0f)
            {
                ai[2] -= 1f;
            }
            else if (ai[2] == 0f)
            {
                if (((Main.player[target].Center.X < base.Center.X && direction < 0) || (Main.player[target].Center.X > base.Center.X && direction > 0)) && velocity.Y == 0f && Distance(Main.player[target].Center) < 900f && Collision.CanHit(base.Center, 1, 1, Main.player[target].Center, 1, 1))
                {
                    ai[2] = -num120 - num122;
                    netUpdate = true;
                }
            }
            else
            {
                if (ai[2] < 0f && ai[2] < (float)(-num120))
                {
                    position += netOffset;
                    velocity.X *= 0.9f;
                    if (velocity.Y < -2f || velocity.Y > 4f || justHit)
                    {
                        ai[2] = num118;
                    }
                    else
                    {
                        ai[2] += 1f;
                        if (ai[2] == 0f)
{
                            ai[2] = num119;
                        }
                    }
                    float num123 = ai[2] + (float)num120 + (float)num122;
                    if (num123 == 1f)
                    {
                        SoundEngine.PlaySound(4, (int)position.X, (int)position.Y, 17);
                    }
                    if (num123 < (float)num122)
                    {
                        Vector2 vector33 = base.Top + new Vector2((float)(spriteDirection * 6), 6f);
                        float num124 = MathHelper.Lerp(20f, 30f, (num123 * 3f + 50f) / 182f);
                        Main.rand.NextFloat();
                        for (float num125 = 0f; num125 < 2f; num125 += 1f)
{
                            Vector2 vector34 = Vector2.UnitY.RotatedByRandom(6.2831854820251465) * (Main.rand.NextFloat() * 0.5f + 0.5f);
                            Dust obj3 = Main.dust[Dust.NewDust(vector33, 0, 0, 228)];
                            obj3.position = vector33 + vector34 * num124;
                            obj3.noGravity = true;
                            obj3.velocity = vector34 * 2f;
                            obj3.scale = 0.5f + Main.rand.NextFloat() * 0.5f;
                        }
                    }
                    Lighting.AddLight(base.Center, 0.9f, 0.75f, 0.1f);
                    position -= netOffset;
                    return;
                }
                if (ai[2] < 0f && ai[2] >= (float)(-num120))
                {
                    position += netOffset;
                    Lighting.AddLight(base.Center, 0.9f, 0.75f, 0.1f);
                    velocity.X *= 0.9f;
                    if (velocity.Y < -2f || velocity.Y > 4f || justHit)
                    {
                        ai[2] = num118;
                    }
                    else
                    {
                        ai[2] += 1f;
                        if (ai[2] == 0f)
{
                            ai[2] = num119;
                        }
                    }
                    float num126 = ai[2] + (float)num120;
                    if (num126 < 180f && (Main.rand.Next(3) == 0 || ai[2] % 3f == 0f))
                    {
                        Vector2 vector35 = base.Top + new Vector2((float)(spriteDirection * 10), 10f);
                        float num128 = MathHelper.Lerp(20f, 30f, (num126 * 3f + 50f) / 182f);
                        Main.rand.NextFloat();
                        for (float num129 = 0f; num129 < 1f; num129 += 1f)
{
                            Vector2 vector36 = Vector2.UnitY.RotatedByRandom(6.2831854820251465) * (Main.rand.NextFloat() * 0.5f + 0.5f);
                            Dust obj4 = Main.dust[Dust.NewDust(vector35, 0, 0, 228)];
                            obj4.position = vector35 + vector36 * num128;
                            obj4.noGravity = true;
                            obj4.velocity = vector36 * 4f;
                            obj4.scale = 0.5f + Main.rand.NextFloat();
                        }
                    }
                    position -= netOffset;
                    if (Main.netMode == 2)
                    {
                        return;
                    }
                    Player player2 = Main.player[Main.myPlayer];
                    _ = Main.myPlayer;
                    if (player2.dead || !player2.active || player2.FindBuffIndex(156) != -1)
                    {
                        return;
                    }
                    Vector2 vector2 = player2.Center - base.Center;
                    if (!(((Vector2)(ref vector2)).Length() < 700f))
                    {
                        return;
                    }
                    bool flag21 = ((Vector2)(ref vector2)).Length() < 30f;
                    if (!flag21)
                    {
                        float x = ((float)Math.PI / 4f).ToRotationVector2().X;
                        Vector2 vector3 = Vector2.Normalize(vector2);
                        if (vector3.X > x || vector3.X < 0f - x)
{
                            flag21 = true;
                        }
                    }
                    if (((player2.Center.X < base.Center.X && direction < 0 && player2.direction > 0) || (player2.Center.X > base.Center.X && direction > 0 && player2.direction < 0)) && flag21 && (Collision.CanHitLine(base.Center, 1, 1, player2.Center, 1, 1) || Collision.CanHitLine(base.Center - Vector2.UnitY * 16f, 1, 1, player2.Center, 1, 1) || Collision.CanHitLine(base.Center + Vector2.UnitY * 8f, 1, 1, player2.Center, 1, 1)) && !player2.creativeGodMode)
                    {
                        player2.AddBuff(156, num121 + (int)ai[2] * -1);
                    }
                    return;
                }
            }
        }
        if (type == 471)
        {
            if (ai[3] < 0f)
            {
                knockBackResist = 0f;
                defense = (int)((double)defDefense * 1.1);
                noGravity = true;
                noTileCollide = true;
                if (velocity.X < 0f)
                {
                    direction = -1;
                }
                else if (velocity.X > 0f)
                {
                    direction = 1;
                }
                rotation = velocity.X * 0.1f;
                if (Main.netMode != 1)
                {
                    localAI[3] += 1f;
                    if (localAI[3] > (float)Main.rand.Next(20, 180))
                    {
                        localAI[3] = 0f;
                        Vector2 center6 = base.Center;
                        center6 += velocity;
                        NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)center6.X, (int)center6.Y, 30);
                    }
                }
            }
            else
            {
                localAI[3] = 0f;
                knockBackResist = 0.35f * Main.GameModeInfo.KnockbackToEnemiesMultiplier;
                rotation *= 0.9f;
                defense = defDefense;
                noGravity = false;
                noTileCollide = false;
            }
            if (ai[3] == 1f)
            {
                knockBackResist = 0f;
                defense += 10;
            }
            if (ai[3] == -1f)
            {
                TargetClosest();
                float num130 = 8f;
                float num131 = 40f;
                Vector2 vector4 = Main.player[target].Center - base.Center;
                float num132 = ((Vector2)(ref vector4)).Length();
                num130 += num132 / 200f;
                ((Vector2)(ref vector4)).Normalize();
                vector4 *= num130;
                velocity = (velocity * (num131 - 1f) + vector4) / num131;
                if (num132 < 500f && !Collision.SolidCollision(position, width, height))
                {
                    ai[3] = 0f;
                    ai[2] = 0f;
                }
                return;
            }
            if (ai[3] == -2f)
            {
                velocity.Y -= 0.2f;
                if (velocity.Y < -10f)
                {
                    velocity.Y = -10f;
                }
                if (Main.player[target].Center.Y - base.Center.Y > 200f)
                {
                    TargetClosest();
                    ai[3] = -3f;
                    if (Main.player[target].Center.X > base.Center.X)
                    {
                        ai[2] = 1f;
                    }
                    else
                    {
                        ai[2] = -1f;
                    }
                }
                velocity.X *= 0.99f;
                return;
            }
            if (ai[3] == -3f)
            {
                if (direction == 0)
                {
                    TargetClosest();
                }
                if (ai[2] == 0f)
                {
                    ai[2] = direction;
                }
                velocity.Y *= 0.9f;
                velocity.X += ai[2] * 0.3f;
                if (velocity.X > 10f)
                {
                    velocity.X = 10f;
                }
                if (velocity.X < -10f)
                {
                    velocity.X = -10f;
                }
                float num133 = Main.player[target].Center.X - base.Center.X;
                if ((ai[2] < 0f && num133 > 300f) || (ai[2] > 0f && num133 < -300f))
                {
                    ai[3] = -4f;
                    ai[2] = 0f;
                }
                else if (Math.Abs(num133) > 800f)
                {
                    ai[3] = -1f;
                    ai[2] = 0f;
                }
                return;
            }
            if (ai[3] == -4f)
            {
                ai[2] += 1f;
                velocity.Y += 0.1f;
                if (((Vector2)(ref velocity)).Length() > 4f)
                {
                    velocity *= 0.9f;
                }
                int num134 = (int)base.Center.X / 16;
                int num135 = (int)(position.Y + (float)height + 12f) / 16;
                bool flag22 = false;
                for (int l = num134 - 1; l <= num134 + 1; l++)
                {
                    if (Main.tile[l, num135] == null)
                    {
                        Main.tile[num134, num135] = default(Tile);
                    }
                    if (Main.tile[l, num135].active() && Main.tileSolid[Main.tile[l, num135].type])
                    {
                        flag22 = true;
                    }
                }
                if (flag22 && !Collision.SolidCollision(position, width, height))
                {
                    ai[3] = 0f;
                    ai[2] = 0f;
                }
                else if (ai[2] > 300f || base.Center.Y > Main.player[target].Center.Y + 200f)
                {
                    ai[3] = -1f;
                    ai[2] = 0f;
                }
            }
            else
            {
                if (ai[3] == 1f)
                {
                    Vector2 center7 = base.Center;
                    center7.Y -= 70f;
                    velocity.X *= 0.8f;
                    ai[2] += 1f;
                    if (ai[2] == 60f)
                    {
                        if (Main.netMode != 1)
{
                            NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)center7.X, (int)center7.Y + 18, 472);
                        }
                    }
                    else if (ai[2] >= 90f)
                    {
                        ai[3] = -2f;
                        ai[2] = 0f;
                    }
                    Vector2 vector5 = default(Vector2);
                    for (int m = 0; m < 2; m++)
                    {
                        Vector2 val2 = center7;
                        ((Vector2)(ref vector5))._002Ector((float)Main.rand.Next(-100, 101), (float)Main.rand.Next(-100, 101));
                        ((Vector2)(ref vector5)).Normalize();
                        vector5 *= (float)Main.rand.Next(0, 100) * 0.1f;
                        Vector2 val3 = val2 + vector5;
                        ((Vector2)(ref vector5)).Normalize();
                        vector5 *= (float)Main.rand.Next(50, 90) * 0.1f;
                        int num136 = Dust.NewDust(val3, 1, 1, 27);
                        Main.dust[num136].velocity = -vector5 * 0.3f;
                        Main.dust[num136].alpha = 100;
                        if (Main.rand.Next(2) == 0)
{
                            Main.dust[num136].noGravity = true;
                            Main.dust[num136].scale += 0.3f;
                        }
                    }
                    return;
                }
                ai[2] += 1f;
                int num137 = 10;
                if (velocity.Y == 0f && CountNPCS(472) < num137)
                {
                    if (ai[2] >= 180f)
                    {
                        ai[2] = 0f;
                        ai[3] = 1f;
                    }
                }
                else
                {
                    if (CountNPCS(472) >= num137)
                    {
                        ai[2] += 1f;
                    }
                    if (ai[2] >= 360f)
                    {
                        ai[2] = 0f;
                        ai[3] = -2f;
                        velocity.Y -= 3f;
                    }
                }
                if (target >= 0 && !Main.player[target].dead)
                {
                    val = Main.player[target].Center - base.Center;
                    if (((Vector2)(ref val)).Length() > 800f)
                    {
                        ai[3] = -1f;
                        ai[2] = 0f;
                    }
                }
            }
            if (Main.player[target].dead)
            {
                TargetClosest();
                if (Main.player[target].dead)
                {
                    EncourageDespawn(1);
                }
            }
        }
        if (type == 419)
        {
            reflectsProjectiles = false;
            takenDamageMultiplier = 1f;
            int num139 = 6;
            int num140 = 10;
            float num141 = 16f;
            if (ai[2] > 0f)
            {
                ai[2] -= 1f;
            }
            if (ai[2] == 0f)
            {
                if (((Main.player[target].Center.X < base.Center.X && direction < 0) || (Main.player[target].Center.X > base.Center.X && direction > 0)) && Collision.CanHit(base.Center, 1, 1, Main.player[target].Center, 1, 1))
                {
                    ai[2] = -1f;
                    netUpdate = true;
                    TargetClosest();
                }
            }
            else
            {
                if (ai[2] < 0f && ai[2] > (float)(-num139))
                {
                    ai[2] -= 1f;
                    velocity.X *= 0.9f;
                    return;
                }
                if (ai[2] == (float)(-num139))
                {
                    ai[2] -= 1f;
                    TargetClosest();
                    Vector2 vector6 = DirectionTo(Main.player[target].Top + new Vector2(0f, -30f));
                    if (vector6.HasNaNs())
                    {
                        vector6 = Vector2.Normalize(new Vector2((float)spriteDirection, -1f));
                    }
                    velocity = vector6 * num141;
                    netUpdate = true;
                    return;
                }
                if (ai[2] < (float)(-num139))
                {
                    ai[2] -= 1f;
                    if (velocity.Y == 0f)
                    {
                        ai[2] = 60f;
                    }
                    else if (ai[2] < (float)(-num139 - num140))
                    {
                        velocity.Y += 0.15f;
                        if (velocity.Y > 24f)
{
                            velocity.Y = 24f;
                        }
                    }
                    reflectsProjectiles = true;
                    takenDamageMultiplier = 3f;
                    if (justHit)
                    {
                        ai[2] = 60f;
                        netUpdate = true;
                    }
                    return;
                }
            }
        }
        if (type == 415)
        {
            int num142 = 42;
            int num143 = 18;
            if (justHit)
            {
                ai[2] = 120f;
                netUpdate = true;
            }
            if (ai[2] > 0f)
            {
                ai[2] -= 1f;
            }
            if (ai[2] == 0f)
            {
                int num144 = 0;
                for (int n = 0; n < 200; n++)
                {
                    if (Main.npc[n].active && Main.npc[n].type == 516)
                    {
                        num144++;
                    }
                }
                if (num144 > 6)
                {
                    ai[2] = 90f;
                }
                else if (((Main.player[target].Center.X < base.Center.X && direction < 0) || (Main.player[target].Center.X > base.Center.X && direction > 0)) && Collision.CanHit(base.Center, 1, 1, Main.player[target].Center, 1, 1))
                {
                    ai[2] = -1f;
                    netUpdate = true;
                    TargetClosest();
                }
            }
            else if (ai[2] < 0f && ai[2] > (float)(-num142))
            {
                ai[2] -= 1f;
                if (ai[2] == (float)(-num142))
                {
                    ai[2] = 180 + 30 * Main.rand.Next(10);
                }
                velocity.X *= 0.8f;
                if (ai[2] == (float)(-num143) || ai[2] == (float)(-num143 - 8) || ai[2] == (float)(-num143 - 16))
                {
                    position += netOffset;
                    for (int num145 = 0; num145 < 20; num145++)
                    {
                        Vector2 vector7 = base.Center + Vector2.UnitX * (float)spriteDirection * 40f;
                        Dust obj5 = Main.dust[Dust.NewDust(vector7, 0, 0, 259)];
                        Vector2 vector8 = Vector2.UnitY.RotatedByRandom(6.2831854820251465);
                        obj5.position = vector7 + vector8 * 4f;
                        obj5.velocity = vector8 * 2f + Vector2.UnitX * Main.rand.NextFloat() * (float)spriteDirection * 3f;
                        obj5.scale = 0.3f + vector8.X * (float)(-spriteDirection);
                        obj5.fadeIn = 0.7f;
                        obj5.noGravity = true;
                    }
                    position -= netOffset;
                    if (velocity.X > -0.5f && velocity.X < 0.5f)
                    {
                        velocity.X = 0f;
                    }
                    if (Main.netMode != 1)
                    {
                        NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X + spriteDirection * 45, (int)base.Center.Y + 8, 516, 0, 0f, 0f, 0f, 0f, target);
                    }
                }
                return;
            }
        }
        if (type == 428)
        {
            localAI[0] += 1f;
            if (localAI[0] >= 300f)
            {
                int num202 = (int)base.Center.X / 16 - 1;
                int num146 = (int)base.Center.Y / 16 - 1;
                if (!Collision.SolidTiles(num202, num202 + 2, num146, num146 + 1) && Main.netMode != 1)
                {
                    Transform(427);
                    life = lifeMax;
                    localAI[0] = 0f;
                    return;
                }
            }
            int num147 = 0;
            num147 = ((localAI[0] < 60f) ? 16 : ((localAI[0] < 120f) ? 8 : ((localAI[0] < 180f) ? 4 : ((localAI[0] < 240f) ? 2 : ((!(localAI[0] < 300f)) ? 1 : 1)))));
            if (Main.rand.Next(num147) == 0)
            {
                position += netOffset;
                Dust dust4 = Main.dust[Dust.NewDust(position, width, height, 229)];
                dust4.noGravity = true;
                dust4.scale = 1f;
                dust4.noLight = true;
                dust4.velocity = DirectionFrom(dust4.position) * ((Vector2)(ref dust4.velocity)).Length();
                dust4.position -= dust4.velocity * 5f;
                dust4.position.X += direction * 6;
                dust4.position.Y += 4f;
                position -= netOffset;
            }
        }
        if (type == 427)
        {
            localAI[0] += 1f;
            localAI[0] += Math.Abs(velocity.X) / 2f;
            if (localAI[0] >= 1200f && Main.netMode != 1)
            {
                int num203 = (int)base.Center.X / 16 - 2;
                int num149 = (int)base.Center.Y / 16 - 3;
                if (!Collision.SolidTiles(num203, num203 + 4, num149, num149 + 4))
                {
                    Transform(426);
                    life = lifeMax;
                    localAI[0] = 0f;
                    return;
                }
            }
            int num150 = 0;
            num150 = ((localAI[0] < 360f) ? 32 : ((localAI[0] < 720f) ? 16 : ((localAI[0] < 1080f) ? 6 : ((localAI[0] < 1440f) ? 2 : ((!(localAI[0] < 1800f)) ? 1 : 1)))));
            if (Main.rand.Next(num150) == 0)
            {
                position += netOffset;
                Dust obj6 = Main.dust[Dust.NewDust(position, width, height, 229)];
                obj6.noGravity = true;
                obj6.scale = 1f;
                obj6.noLight = true;
                position -= netOffset;
            }
        }
        if (type == 590)
        {
            position += netOffset;
            int num151 = (int)(position.Y + 6f) / 16;
            if (spriteDirection < 0)
            {
                int num152 = (int)(base.Center.X - 22f) / 16;
                Tile tileSafely = Framing.GetTileSafely(num152, num151);
                Tile tileSafely2 = Framing.GetTileSafely(num152 + 1, num151);
                if (WorldGen.InWorld(num152, num151) && tileSafely2.liquid == 0 && tileSafely.liquid == 0)
                {
                    Lighting.AddLight(num152, num151, 1f, 0.95f, 0.8f);
                    if (Main.rand.Next(30) == 0)
                    {
                        Dust.NewDust(new Vector2(base.Center.X - 22f, position.Y + 6f), 1, 1, 6);
                    }
                }
            }
            else
            {
                int num153 = (int)(base.Center.X + 14f) / 16;
                Tile tileSafely3 = Framing.GetTileSafely(num153, num151);
                Tile tileSafely4 = Framing.GetTileSafely(num153 - 1, num151);
                if (WorldGen.InWorld(num153, num151) && tileSafely4.liquid == 0 && tileSafely3.liquid == 0)
                {
                    Lighting.AddLight(num153, num151, 1f, 0.95f, 0.8f);
                    if (Main.rand.Next(30) == 0)
                    {
                        Dust.NewDust(new Vector2(base.Center.X + 14f, position.Y + 6f), 1, 1, 6);
                    }
                }
            }
            position -= netOffset;
        }
        else if (type == 591)
        {
            position += netOffset;
            if (!wet)
            {
                if (spriteDirection < 0)
                {
                    Lighting.AddLight(new Vector2(base.Center.X - 36f, position.Y + 24f), 1f, 0.95f, 0.8f);
                    if (ai[2] == 0f && Main.rand.Next(30) == 0)
                    {
                        Dust.NewDust(new Vector2(base.Center.X - 36f, position.Y + 24f), 1, 1, 6);
                    }
                }
                else
                {
                    Lighting.AddLight(new Vector2(base.Center.X + 28f, position.Y + 24f), 1f, 0.95f, 0.8f);
                    if (ai[2] == 0f && Main.rand.Next(30) == 0)
                    {
                        Dust.NewDust(new Vector2(base.Center.X + 28f, position.Y + 24f), 1, 1, 6);
                    }
                }
            }
            position -= netOffset;
        }
        bool flag23 = false;
        bool flag24 = false;
        if (velocity.X == 0f)
        {
            flag24 = true;
        }
        if (justHit)
        {
            flag24 = false;
        }
        if (Main.netMode != 1 && type == 198 && (double)life <= (double)lifeMax * 0.55)
        {
            Transform(199);
        }
        if (Main.netMode != 1 && type == 348 && (double)life <= (double)lifeMax * 0.55)
        {
            Transform(349);
        }
        int num154 = 60;
        if (type == 120)
        {
            num154 = 180;
            if (ai[3] == -120f)
            {
                velocity *= 0f;
                ai[3] = 0f;
                position += netOffset;
                SoundEngine.PlaySound(in SoundID.Item8, position);
                Vector2 vector9 = default(Vector2);
                ((Vector2)(ref vector9))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                float num155 = oldPos[2].X + (float)width * 0.5f - vector9.X;
                float num156 = oldPos[2].Y + (float)height * 0.5f - vector9.Y;
                float num157 = (float)Math.Sqrt(num155 * num155 + num156 * num156);
                num157 = 2f / num157;
                num155 *= num157;
                num156 *= num157;
                for (int num159 = 0; num159 < 20; num159++)
                {
                    int num160 = Dust.NewDust(position, width, height, 71, num155, num156, 200, default(Color), 2f);
                    Main.dust[num160].noGravity = true;
                    Main.dust[num160].velocity.X *= 2f;
                }
                for (int num161 = 0; num161 < 20; num161++)
                {
                    int num162 = Dust.NewDust(oldPos[2], width, height, 71, 0f - num155, 0f - num156, 200, default(Color), 2f);
                    Main.dust[num162].noGravity = true;
                    Main.dust[num162].velocity.X *= 2f;
                }
                position -= netOffset;
            }
        }
        bool flag25 = false;
        bool flag26 = true;
        if (type == 343 || type == 47 || type == 67 || type == 109 || type == 110 || type == 111 || type == 120 || type == 163 || type == 164 || type == 239 || type == 168 || type == 199 || type == 206 || type == 214 || type == 215 || type == 216 || type == 217 || type == 218 || type == 219 || type == 220 || type == 226 || type == 243 || type == 251 || type == 257 || type == 258 || type == 290 || type == 291 || type == 292 || type == 293 || type == 305 || type == 306 || type == 307 || type == 308 || type == 309 || type == 348 || type == 349 || type == 350 || type == 351 || type == 379 || (type >= 430 && type <= 436) || type == 591 || type == 380 || type == 381 || type == 382 || type == 383 || type == 386 || type == 391 || (type >= 449 && type <= 452) || type == 466 || type == 464 || type == 166 || type == 469 || type == 468 || type == 471 || type == 470 || type == 480 || type == 481 || type == 482 || type == 411 || type == 424 || type == 409 || (type >= 494 && type <= 506) || type == 425 || type == 427 || type == 426 || type == 428 || type == 580 || type == 508 || type == 415 || type == 419 || type == 520 || (type >= 524 && type <= 527) || type == 528 || type == 529 || type == 530 || type == 532 || type == 582 || type == 624 || type == 631)
        {
            flag26 = false;
        }
        bool flag27 = false;
        int num163 = type;
        if (num163 == 425 || num163 == 471)
        {
            flag27 = true;
        }
        bool flag2 = true;
        switch (type)
        {
        case 110:
        case 111:
        case 206:
        case 214:
        case 215:
        case 216:
        case 291:
        case 292:
        case 293:
        case 350:
        case 379:
        case 380:
        case 381:
        case 382:
        case 409:
        case 411:
        case 424:
        case 426:
        case 466:
        case 498:
        case 499:
        case 500:
        case 501:
        case 502:
        case 503:
        case 504:
        case 505:
        case 506:
        case 520:
            if (ai[2] > 0f)
            {
                flag2 = false;
            }
            break;
        }
        if (!flag27 && flag2)
        {
            if (velocity.Y == 0f && ((velocity.X > 0f && direction < 0) || (velocity.X < 0f && direction > 0)))
            {
                flag25 = true;
            }
            if (position.X == oldPosition.X || ai[3] >= (float)num154 || flag25)
            {
                ai[3] += 1f;
            }
            else if ((double)Math.Abs(velocity.X) > 0.9 && ai[3] > 0f)
            {
                ai[3] -= 1f;
            }
            if (ai[3] > (float)(num154 * 10))
            {
                ai[3] = 0f;
            }
            if (justHit)
            {
                ai[3] = 0f;
            }
            if (ai[3] == (float)num154)
            {
                netUpdate = true;
            }
            hitbox = Main.player[target].Hitbox;
            if (((Rectangle)(ref hitbox)).Intersects(base.Hitbox))
            {
                ai[3] = 0f;
            }
        }
        if (type == 463 && Main.netMode != 1)
        {
            if (localAI[3] > 0f)
            {
                localAI[3] -= 1f;
            }
            if (justHit && localAI[3] <= 0f && Main.rand.Next(3) == 0)
            {
                localAI[3] = 30f;
                int num164 = Main.rand.Next(3, 6);
                int[] array = new int[num164];
                int num165 = 0;
                for (int num166 = 0; num166 < 255; num166++)
                {
                    if (Main.player[num166].active && !Main.player[num166].dead && Collision.CanHitLine(position, width, height, Main.player[num166].position, Main.player[num166].width, Main.player[num166].height))
                    {
                        array[num165] = num166;
                        num165++;
                        if (num165 == num164)
{
                            break;
                        }
                    }
                }
                if (num165 > 1)
                {
                    for (int num167 = 0; num167 < 100; num167++)
                    {
                        int num168 = Main.rand.Next(num165);
                        int num170;
                        for (num170 = num168; num170 == num168; num170 = Main.rand.Next(num165))
{
                        }
                        int num171 = array[num168];
                        array[num168] = array[num170];
                        array[num170] = num171;
                    }
                }
                Vector2 vector11 = default(Vector2);
                ((Vector2)(ref vector11))._002Ector(-1f, -1f);
                for (int num172 = 0; num172 < num165; num172++)
                {
                    Vector2 vector12 = Main.npc[array[num172]].Center - base.Center;
                    ((Vector2)(ref vector12)).Normalize();
                    vector11 += vector12;
                }
                ((Vector2)(ref vector11)).Normalize();
                Vector2 vector13 = default(Vector2);
                for (int num173 = 0; num173 < num164; num173++)
                {
                    float num174 = Main.rand.Next(8, 13);
                    ((Vector2)(ref vector13))._002Ector((float)Main.rand.Next(-100, 101), (float)Main.rand.Next(-100, 101));
                    ((Vector2)(ref vector13)).Normalize();
                    if (num165 > 0)
                    {
                        vector13 += vector11;
                        ((Vector2)(ref vector13)).Normalize();
                    }
                    vector13 *= num174;
                    if (num165 > 0)
                    {
                        num165--;
                        vector13 = Main.player[array[num165]].Center - base.Center;
                        ((Vector2)(ref vector13)).Normalize();
                        vector13 *= num174;
                    }
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, position.Y + (float)(width / 4), vector13.X, vector13.Y, 498, (int)((double)damage * 0.15), 1f, Main.myPlayer);
                }
            }
        }
        if (type == 460)
        {
            if (velocity.Y < 0f - gravity || velocity.Y > gravity)
            {
                knockBackResist = 0f;
            }
            else
            {
                knockBackResist = 0.25f * Main.GameModeInfo.KnockbackToEnemiesMultiplier;
            }
        }
        if (type == 469)
        {
            knockBackResist = 0.45f * Main.GameModeInfo.KnockbackToEnemiesMultiplier;
            if (ai[2] == 1f)
            {
                knockBackResist = 0f;
            }
            bool flag3 = false;
            int num175 = (int)base.Center.X / 16;
            int num176 = (int)base.Center.Y / 16;
            for (int num177 = num175 - 1; num177 <= num175 + 1; num177++)
            {
                for (int num178 = num176 - 1; num178 <= num176 + 1; num178++)
                {
                    if (Main.tile[num177, num178] != null && Main.tile[num177, num178].wall > 0)
                    {
                        flag3 = true;
                        break;
                    }
                }
                if (flag3)
                {
                    break;
                }
            }
            if (ai[2] == 0f && flag3)
            {
                if (velocity.Y == 0f)
                {
                    flag = true;
                    velocity.Y = -4.6f;
                    velocity.X *= 1.3f;
                }
                else if (velocity.Y > 0f && !Main.player[target].dead)
                {
                    ai[2] = 1f;
                }
            }
            if (flag3 && ai[2] == 1f && !Main.player[target].dead && Collision.CanHit(base.Center, 1, 1, Main.player[target].Center, 1, 1))
            {
                Vector2 vector14 = Main.player[target].Center - base.Center;
                float num179 = ((Vector2)(ref vector14)).Length();
                ((Vector2)(ref vector14)).Normalize();
                vector14 *= 4.5f + num179 / 300f;
                velocity = (velocity * 29f + vector14) / 30f;
                noGravity = true;
                ai[2] = 1f;
                return;
            }
            noGravity = false;
            ai[2] = 0f;
        }
        if (type == 462 && velocity.Y == 0f)
        {
            val = Main.player[target].Center - base.Center;
            if (((Vector2)(ref val)).Length() < 150f && Math.Abs(velocity.X) > 3f && ((velocity.X < 0f && base.Center.X > Main.player[target].Center.X) || (velocity.X > 0f && base.Center.X < Main.player[target].Center.X)))
            {
                flag = true;
                velocity.X *= 1.75f;
                velocity.Y -= 4.5f;
                if (base.Center.Y - Main.player[target].Center.Y > 20f)
                {
                    velocity.Y -= 0.5f;
                }
                if (base.Center.Y - Main.player[target].Center.Y > 40f)
                {
                    velocity.Y -= 1f;
                }
                if (base.Center.Y - Main.player[target].Center.Y > 80f)
                {
                    velocity.Y -= 1.5f;
                }
                if (base.Center.Y - Main.player[target].Center.Y > 100f)
                {
                    velocity.Y -= 1.5f;
                }
                if (Math.Abs(velocity.X) > 7f)
                {
                    if (velocity.X < 0f)
                    {
                        velocity.X = -7f;
                    }
                    else
                    {
                        velocity.X = 7f;
                    }
                }
            }
        }
        if (type == 624 && target < 255)
        {
            if (!Main.remixWorld && !Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
            {
                ai[3] = num154;
                directionY = -1;
                if (type == 624 && !AI_003_Gnomes_ShouldTurnToStone())
                {
                    val = base.Center - Main.player[target].Center;
                    if (((Vector2)(ref val)).Length() > 500f)
                    {
                        velocity.X *= 0.95f;
                        if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
{
                            velocity.X = 0f;
                        }
                        return;
                    }
                }
            }
            else if (Main.player[target].Center.Y > base.Center.Y - 128f)
            {
                ai[3] = 0f;
            }
        }
        if (ai[3] < (float)num154 && DespawnEncouragement_AIStyle3_Fighters_NotDiscouraged(type, position, this))
        {
            if (shimmerTransparency < 1f)
            {
                if ((type == 3 || type == 591 || type == 590 || type == 331 || type == 332 || type == 21 || (type >= 449 && type <= 452) || type == 31 || type == 294 || type == 295 || type == 296 || type == 77 || type == 110 || type == 132 || type == 167 || type == 161 || type == 162 || type == 186 || type == 187 || type == 188 || type == 189 || type == 197 || type == 200 || type == 201 || type == 202 || type == 203 || type == 223 || type == 291 || type == 292 || type == 293 || type == 320 || type == 321 || type == 319 || type == 481 || type == 632 || type == 635) && Main.rand.Next(1000) == 0)
                {
                    SoundEngine.PlaySound(14, (int)position.X, (int)position.Y);
                }
                if ((type == 489 || type == 586) && Main.rand.Next(800) == 0)
                {
                    SoundEngine.PlaySound(14, (int)position.X, (int)position.Y, type);
                }
                if ((type == 78 || type == 79 || type == 80 || type == 630) && Main.rand.Next(500) == 0)
                {
                    SoundEngine.PlaySound(26, (int)position.X, (int)position.Y);
                }
                if (type == 159 && Main.rand.Next(500) == 0)
                {
                    SoundEngine.PlaySound(29, (int)position.X, (int)position.Y, 7);
                }
                if (type == 162 && Main.rand.Next(500) == 0)
                {
                    SoundEngine.PlaySound(29, (int)position.X, (int)position.Y, 6);
                }
                if (type == 181 && Main.rand.Next(500) == 0)
                {
                    SoundEngine.PlaySound(29, (int)position.X, (int)position.Y, 8);
                }
                if (type >= 269 && type <= 280 && Main.rand.Next(1000) == 0)
                {
                    SoundEngine.PlaySound(14, (int)position.X, (int)position.Y);
                }
            }
            TargetClosest();
            if (directionY > 0 && Main.player[target].Center.Y <= base.Bottom.Y)
            {
                directionY = -1;
            }
        }
        else if (!(ai[2] > 0f) || !DespawnEncouragement_AIStyle3_Fighters_CanBeBusyWithAction(type))
        {
            if (Main.IsItDay() && (double)(position.Y / 16f) < Main.worldSurface && type != 624 && type != 631)
            {
                EncourageDespawn(10);
            }
            if (velocity.X == 0f)
            {
                if (velocity.Y == 0f)
                {
                    ai[0] += 1f;
                    if (ai[0] >= 2f)
                    {
                        direction *= -1;
                        spriteDirection = direction;
                        ai[0] = 0f;
                    }
                }
            }
            else
            {
                ai[0] = 0f;
            }
            if (direction == 0)
            {
                direction = 1;
            }
        }
        if (type == 159 || type == 349)
        {
            if (type == 159 && ((velocity.X > 0f && direction < 0) || (velocity.X < 0f && direction > 0)))
            {
                velocity.X *= 0.95f;
            }
            if (velocity.X < -6f || velocity.X > 6f)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.8f;
                }
            }
            else if (velocity.X < 6f && direction == 1)
            {
                if (velocity.Y == 0f && velocity.X < 0f)
                {
                    velocity.X *= 0.99f;
                }
                velocity.X += 0.07f;
                if (velocity.X > 6f)
                {
                    velocity.X = 6f;
                }
            }
            else if (velocity.X > -6f && direction == -1)
            {
                if (velocity.Y == 0f && velocity.X > 0f)
                {
                    velocity.X *= 0.99f;
                }
                velocity.X -= 0.07f;
                if (velocity.X < -6f)
                {
                    velocity.X = -6f;
                }
            }
        }
        else if (type == 199)
        {
            if (velocity.X < -4f || velocity.X > 4f)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.8f;
                }
            }
            else if (velocity.X < 4f && direction == 1)
            {
                if (velocity.Y == 0f && velocity.X < 0f)
                {
                    velocity.X *= 0.8f;
                }
                velocity.X += 0.1f;
                if (velocity.X > 4f)
                {
                    velocity.X = 4f;
                }
            }
            else if (velocity.X > -4f && direction == -1)
            {
                if (velocity.Y == 0f && velocity.X > 0f)
                {
                    velocity.X *= 0.8f;
                }
                velocity.X -= 0.1f;
                if (velocity.X < -4f)
                {
                    velocity.X = -4f;
                }
            }
        }
        else if (type == 120 || type == 166 || type == 213 || type == 258 || type == 528 || type == 529)
        {
            if (velocity.X < -3f || velocity.X > 3f)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.8f;
                }
            }
            else if (velocity.X < 3f && direction == 1)
            {
                if (velocity.Y == 0f && velocity.X < 0f)
                {
                    velocity.X *= 0.99f;
                }
                velocity.X += 0.07f;
                if (velocity.X > 3f)
                {
                    velocity.X = 3f;
                }
            }
            else if (velocity.X > -3f && direction == -1)
            {
                if (velocity.Y == 0f && velocity.X > 0f)
                {
                    velocity.X *= 0.99f;
                }
                velocity.X -= 0.07f;
                if (velocity.X < -3f)
                {
                    velocity.X = -3f;
                }
            }
        }
        else if (type == 461 || type == 27 || type == 77 || type == 104 || type == 163 || type == 162 || type == 196 || type == 197 || type == 212 || type == 257 || type == 326 || type == 343 || type == 348 || type == 351 || (type >= 524 && type <= 527) || type == 530 || type == 236)
        {
            if (velocity.X < -2f || velocity.X > 2f)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.8f;
                }
            }
            else if (velocity.X < 2f && direction == 1)
            {
                velocity.X += 0.07f;
                if (velocity.X > 2f)
                {
                    velocity.X = 2f;
                }
            }
            else if (velocity.X > -2f && direction == -1)
            {
                velocity.X -= 0.07f;
                if (velocity.X < -2f)
                {
                    velocity.X = -2f;
                }
            }
        }
        else if (type == 109)
        {
            if (velocity.X < -2f || velocity.X > 2f)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.8f;
                }
            }
            else if (velocity.X < 2f && direction == 1)
            {
                velocity.X += 0.04f;
                if (velocity.X > 2f)
                {
                    velocity.X = 2f;
                }
            }
            else if (velocity.X > -2f && direction == -1)
            {
                velocity.X -= 0.04f;
                if (velocity.X < -2f)
                {
                    velocity.X = -2f;
                }
            }
        }
        else if (type == 21 || type == 26 || type == 31 || type == 294 || type == 295 || type == 296 || type == 47 || type == 73 || type == 140 || type == 164 || type == 239 || type == 167 || type == 168 || type == 185 || type == 198 || type == 201 || type == 202 || type == 203 || type == 217 || type == 218 || type == 219 || type == 226 || type == 181 || type == 254 || type == 338 || type == 339 || type == 340 || type == 342 || type == 385 || type == 389 || type == 462 || type == 463 || type == 466 || type == 464 || type == 469 || type == 470 || type == 480 || type == 482 || type == 425 || type == 429 || type == 586 || type == 631 || type == 635)
        {
            float num181 = 1.5f;
            if (type == 181 && Main.remixWorld)
            {
                num181 = 3.75f;
            }
            else if (type == 294)
            {
                num181 = 2f;
            }
            else if (type == 295)
            {
                num181 = 1.75f;
            }
            else if (type == 296)
            {
                num181 = 1.25f;
            }
            else if (type == 201)
            {
                num181 = 1.1f;
            }
            else if (type == 202)
            {
                num181 = 0.9f;
            }
            else if (type == 203)
            {
                num181 = 1.2f;
            }
            else if (type == 338)
            {
                num181 = 1.75f;
            }
            else if (type == 339)
            {
                num181 = 1.25f;
            }
            else if (type == 340)
            {
                num181 = 2f;
            }
            else if (type == 385)
            {
                num181 = 1.8f;
            }
            else if (type == 389)
            {
                num181 = 2.25f;
            }
            else if (type == 462)
            {
                num181 = 4f;
            }
            else if (type == 463)
            {
                num181 = 0.75f;
            }
            else if (type == 466)
            {
                num181 = 3.75f;
            }
            else if (type == 469)
            {
                num181 = 3.25f;
            }
            else if (type == 480)
            {
                num181 = 1.5f + (1f - (float)life / (float)lifeMax) * 2f;
            }
            else if (type == 425)
            {
                num181 = 6f;
            }
            else if (type == 429)
            {
                num181 = 4f;
            }
            else if (type == 631)
            {
                num181 = 0.9f;
            }
            else if (type == 586)
            {
                num181 = 1.5f + (1f - (float)life / (float)lifeMax) * 3.5f;
            }
            if (type == 21 || type == 201 || type == 202 || type == 203 || type == 342 || type == 635)
            {
                num181 *= 1f + (1f - scale);
            }
            if (velocity.X < 0f - num181 || velocity.X > num181)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.8f;
                }
            }
            else if (velocity.X < num181 && direction == 1)
            {
                if (type == 466 && velocity.X < -2f)
                {
                    velocity.X *= 0.9f;
                }
                if (type == 586 && velocity.Y == 0f && velocity.X < -1f)
                {
                    velocity.X *= 0.9f;
                }
                velocity.X += 0.07f;
                if (velocity.X > num181)
                {
                    velocity.X = num181;
                }
            }
            else if (velocity.X > 0f - num181 && direction == -1)
            {
                if (type == 466 && velocity.X > 2f)
                {
                    velocity.X *= 0.9f;
                }
                if (type == 586 && velocity.Y == 0f && velocity.X > 1f)
                {
                    velocity.X *= 0.9f;
                }
                velocity.X -= 0.07f;
                if (velocity.X < 0f - num181)
                {
                    velocity.X = 0f - num181;
                }
            }
            if (velocity.Y == 0f && type == 462 && ((direction > 0 && velocity.X < 0f) || (direction < 0 && velocity.X > 0f)))
            {
                velocity.X *= 0.9f;
            }
        }
        else if (type >= 269 && type <= 280)
        {
            float num182 = 1.5f;
            if (type == 269)
            {
                num182 = 2f;
            }
            if (type == 270)
            {
                num182 = 1f;
            }
            if (type == 271)
            {
                num182 = 1.5f;
            }
            if (type == 272)
            {
                num182 = 3f;
            }
            if (type == 273)
            {
                num182 = 1.25f;
            }
            if (type == 274)
            {
                num182 = 3f;
            }
            if (type == 275)
            {
                num182 = 3.25f;
            }
            if (type == 276)
            {
                num182 = 2f;
            }
            if (type == 277)
            {
                num182 = 2.75f;
            }
            if (type == 278)
            {
                num182 = 1.8f;
            }
            if (type == 279)
            {
                num182 = 1.3f;
            }
            if (type == 280)
            {
                num182 = 2.5f;
            }
            num182 *= 1f + (1f - scale);
            if (velocity.X < 0f - num182 || velocity.X > num182)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.8f;
                }
            }
            else if (velocity.X < num182 && direction == 1)
            {
                velocity.X += 0.07f;
                if (velocity.X > num182)
                {
                    velocity.X = num182;
                }
            }
            else if (velocity.X > 0f - num182 && direction == -1)
            {
                velocity.X -= 0.07f;
                if (velocity.X < 0f - num182)
                {
                    velocity.X = 0f - num182;
                }
            }
        }
        else if (type >= 305 && type <= 314)
        {
            float num183 = 1.5f;
            if (type == 305 || type == 310)
            {
                num183 = 2f;
            }
            if (type == 306 || type == 311)
            {
                num183 = 1.25f;
            }
            if (type == 307 || type == 312)
            {
                num183 = 2.25f;
            }
            if (type == 308 || type == 313)
            {
                num183 = 1.5f;
            }
            if (type == 309 || type == 314)
            {
                num183 = 1f;
            }
            if (type < 310)
            {
                if (velocity.Y == 0f)
                {
                    velocity.X *= 0.85f;
                    if ((double)velocity.X > -0.3 && (double)velocity.X < 0.3)
                    {
                        flag = true;
                        velocity.Y = -7f;
                        velocity.X = num183 * (float)direction;
                    }
                }
                else if (spriteDirection == direction)
                {
                    velocity.X = (velocity.X * 10f + num183 * (float)direction) / 11f;
                }
            }
            else if (velocity.X < 0f - num183 || velocity.X > num183)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.8f;
                }
            }
            else if (velocity.X < num183 && direction == 1)
            {
                velocity.X += 0.07f;
                if (velocity.X > num183)
                {
                    velocity.X = num183;
                }
            }
            else if (velocity.X > 0f - num183 && direction == -1)
            {
                velocity.X -= 0.07f;
                if (velocity.X < 0f - num183)
                {
                    velocity.X = 0f - num183;
                }
            }
        }
        else if (type == 67 || type == 220 || type == 428)
        {
            if (velocity.X < -0.5f || velocity.X > 0.5f)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.7f;
                }
            }
            else if (velocity.X < 0.5f && direction == 1)
            {
                velocity.X += 0.03f;
                if (velocity.X > 0.5f)
                {
                    velocity.X = 0.5f;
                }
            }
            else if (velocity.X > -0.5f && direction == -1)
            {
                velocity.X -= 0.03f;
                if (velocity.X < -0.5f)
                {
                    velocity.X = -0.5f;
                }
            }
        }
        else if (type == 78 || type == 79 || type == 80 || type == 630)
        {
            float num184 = 1f;
            float num185 = 0.05f;
            if (life < lifeMax / 2)
            {
                num184 = 2f;
                num185 = 0.1f;
            }
            if (type == 79 || type == 630)
            {
                num184 *= 1.5f;
            }
            if (velocity.X < 0f - num184 || velocity.X > num184)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.7f;
                }
            }
            else if (velocity.X < num184 && direction == 1)
            {
                velocity.X += num185;
                if (velocity.X > num184)
                {
                    velocity.X = num184;
                }
            }
            else if (velocity.X > 0f - num184 && direction == -1)
            {
                velocity.X -= num185;
                if (velocity.X < 0f - num184)
                {
                    velocity.X = 0f - num184;
                }
            }
        }
        else if (type == 287)
        {
            float num186 = 5f;
            float num187 = 0.2f;
            if (velocity.X < 0f - num186 || velocity.X > num186)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.7f;
                }
            }
            else if (velocity.X < num186 && direction == 1)
            {
                velocity.X += num187;
                if (velocity.X > num186)
                {
                    velocity.X = num186;
                }
            }
            else if (velocity.X > 0f - num186 && direction == -1)
            {
                velocity.X -= num187;
                if (velocity.X < 0f - num186)
                {
                    velocity.X = 0f - num186;
                }
            }
        }
        else if (type == 243)
        {
            float num188 = 1f;
            float num189 = 0.07f;
            num188 += (1f - (float)life / (float)lifeMax) * 1.5f;
            num189 += (1f - (float)life / (float)lifeMax) * 0.15f;
            if (velocity.X < 0f - num188 || velocity.X > num188)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.7f;
                }
            }
            else if (velocity.X < num188 && direction == 1)
            {
                velocity.X += num189;
                if (velocity.X > num188)
                {
                    velocity.X = num188;
                }
            }
            else if (velocity.X > 0f - num188 && direction == -1)
            {
                velocity.X -= num189;
                if (velocity.X < 0f - num188)
                {
                    velocity.X = 0f - num188;
                }
            }
        }
        else if (type == 251)
        {
            float num190 = 1f;
            float num192 = 0.08f;
            num190 += (1f - (float)life / (float)lifeMax) * 2f;
            num192 += (1f - (float)life / (float)lifeMax) * 0.2f;
            if (velocity.X < 0f - num190 || velocity.X > num190)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.7f;
                }
            }
            else if (velocity.X < num190 && direction == 1)
            {
                velocity.X += num192;
                if (velocity.X > num190)
                {
                    velocity.X = num190;
                }
            }
            else if (velocity.X > 0f - num190 && direction == -1)
            {
                velocity.X -= num192;
                if (velocity.X < 0f - num190)
                {
                    velocity.X = 0f - num190;
                }
            }
        }
        else if (type == 386)
        {
            if (ai[2] > 0f)
            {
                if (velocity.Y == 0f)
                {
                    velocity.X *= 0.8f;
                }
            }
            else
            {
                float num193 = 0.15f;
                float num194 = 1.5f;
                if (velocity.X < 0f - num194 || velocity.X > num194)
                {
                    if (velocity.Y == 0f)
                    {
                        velocity *= 0.7f;
                    }
                }
                else if (velocity.X < num194 && direction == 1)
                {
                    velocity.X += num193;
                    if (velocity.X > num194)
                    {
                        velocity.X = num194;
                    }
                }
                else if (velocity.X > 0f - num194 && direction == -1)
                {
                    velocity.X -= num193;
                    if (velocity.X < 0f - num194)
                    {
                        velocity.X = 0f - num194;
                    }
                }
            }
        }
        else if (type == 460)
        {
            float num195 = 3f;
            float num196 = 0.1f;
            if (Math.Abs(velocity.X) > 2f)
            {
                num196 *= 0.8f;
            }
            if ((double)Math.Abs(velocity.X) > 2.5)
            {
                num196 *= 0.8f;
            }
            if (Math.Abs(velocity.X) > 3f)
            {
                num196 *= 0.8f;
            }
            if ((double)Math.Abs(velocity.X) > 3.5)
            {
                num196 *= 0.8f;
            }
            if (Math.Abs(velocity.X) > 4f)
            {
                num196 *= 0.8f;
            }
            if ((double)Math.Abs(velocity.X) > 4.5)
            {
                num196 *= 0.8f;
            }
            if (Math.Abs(velocity.X) > 5f)
            {
                num196 *= 0.8f;
            }
            if ((double)Math.Abs(velocity.X) > 5.5)
            {
                num196 *= 0.8f;
            }
            num195 += (1f - (float)life / (float)lifeMax) * 3f;
            if (velocity.X < 0f - num195 || velocity.X > num195)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.7f;
                }
            }
            else if (velocity.X < num195 && direction == 1)
            {
                if (velocity.X < 0f)
                {
                    velocity.X *= 0.93f;
                }
                velocity.X += num196;
                if (velocity.X > num195)
                {
                    velocity.X = num195;
                }
            }
            else if (velocity.X > 0f - num195 && direction == -1)
            {
                if (velocity.X > 0f)
                {
                    velocity.X *= 0.93f;
                }
                velocity.X -= num196;
                if (velocity.X < 0f - num195)
                {
                    velocity.X = 0f - num195;
                }
            }
        }
        else if (type == 508 || type == 580 || type == 582)
        {
            float num197 = 2.5f;
            float num198 = 10f;
            float num199 = Math.Abs(velocity.X);
            if (type == 582)
            {
                num197 = 2.25f;
                num198 = 7f;
                if (num199 > 2.5f)
                {
                    num197 = 3f;
                    num198 += 75f;
                }
                else if (num199 > 2f)
                {
                    num197 = 2.75f;
                    num198 += 55f;
                }
            }
            else if (num199 > 2.75f)
            {
                num197 = 3.5f;
                num198 += 80f;
            }
            else if ((double)num199 > 2.25)
            {
                num197 = 3f;
                num198 += 60f;
            }
            if ((double)Math.Abs(velocity.Y) < 0.5)
            {
                if (velocity.X > 0f && direction < 0)
                {
                    velocity *= 0.95f;
                }
                if (velocity.X < 0f && direction > 0)
                {
                    velocity *= 0.95f;
                }
            }
            if (Math.Abs(velocity.Y) > gravity)
            {
                float num200 = 3f;
                if (type == 582)
                {
                    num200 = 2f;
                }
                num198 *= num200;
            }
            if (velocity.X <= 0f && direction < 0)
            {
                velocity.X = (velocity.X * num198 - num197) / (num198 + 1f);
            }
            else if (velocity.X >= 0f && direction > 0)
            {
                velocity.X = (velocity.X * num198 + num197) / (num198 + 1f);
            }
            else if (Math.Abs(base.Center.X - Main.player[target].Center.X) > 20f && Math.Abs(velocity.Y) <= gravity)
            {
                velocity.X *= 0.99f;
                velocity.X += (float)direction * 0.025f;
            }
        }
        else if (type == 391 || type == 427 || type == 415 || type == 419 || type == 518 || type == 532)
        {
            float num201 = 5f;
            float num3 = 0.25f;
            float num4 = 0.7f;
            if (type == 427)
            {
                num201 = 6f;
                num3 = 0.2f;
                num4 = 0.8f;
            }
            else if (type == 415)
            {
                num201 = 4f;
                num3 = 0.1f;
                num4 = 0.95f;
            }
            else if (type == 419)
            {
                num201 = 6f;
                num3 = 0.15f;
                num4 = 0.85f;
            }
            else if (type == 518)
            {
                num201 = 5f;
                num3 = 0.1f;
                num4 = 0.95f;
            }
            else if (type == 532)
            {
                num201 = 5f;
                num3 = 0.15f;
                num4 = 0.98f;
            }
            if (velocity.X < 0f - num201 || velocity.X > num201)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= num4;
                }
            }
            else if (velocity.X < num201 && direction == 1)
            {
                velocity.X += num3;
                if (velocity.X > num201)
                {
                    velocity.X = num201;
                }
            }
            else if (velocity.X > 0f - num201 && direction == -1)
            {
                velocity.X -= num3;
                if (velocity.X < 0f - num201)
                {
                    velocity.X = 0f - num201;
                }
            }
        }
        else if ((type >= 430 && type <= 436) || type == 494 || type == 495 || type == 591)
        {
            if (ai[2] == 0f)
            {
                damage = defDamage;
                float num5 = 1f;
                num5 *= 1f + (1f - scale);
                if (velocity.X < 0f - num5 || velocity.X > num5)
                {
                    if (velocity.Y == 0f)
                    {
                        velocity *= 0.8f;
                    }
                }
                else if (velocity.X < num5 && direction == 1)
                {
                    velocity.X += 0.07f;
                    if (velocity.X > num5)
                    {
                        velocity.X = num5;
                    }
                }
                else if (velocity.X > 0f - num5 && direction == -1)
                {
                    velocity.X -= 0.07f;
                    if (velocity.X < 0f - num5)
                    {
                        velocity.X = 0f - num5;
                    }
                }
                if (velocity.Y == 0f && (!Main.IsItDay() || (double)position.Y > Main.worldSurface * 16.0) && !Main.player[target].dead)
                {
                    Vector2 vector15 = base.Center - Main.player[target].Center;
                    int num6 = 50;
                    if (type >= 494 && type <= 495)
                    {
                        num6 = 42;
                    }
                    if (((Vector2)(ref vector15)).Length() < (float)num6 && Collision.CanHit(base.Center, 1, 1, Main.player[target].Center, 1, 1))
                    {
                        velocity.X *= 0.7f;
                        ai[2] = 1f;
                    }
                }
            }
            else
            {
                damage = (int)((double)defDamage * 1.5);
                ai[3] = 1f;
                velocity.X *= 0.9f;
                if ((double)Math.Abs(velocity.X) < 0.1)
                {
                    velocity.X = 0f;
                }
                ai[2] += 1f;
                if (ai[2] >= 20f || velocity.Y != 0f || (Main.IsItDay() && (double)position.Y < Main.worldSurface * 16.0))
                {
                    ai[2] = 0f;
                }
            }
        }
        else if (type != 110 && type != 111 && type != 206 && type != 214 && type != 215 && type != 216 && type != 290 && type != 291 && type != 292 && type != 293 && type != 350 && type != 379 && type != 380 && type != 381 && type != 382 && (type < 449 || type > 452) && type != 468 && type != 481 && type != 411 && type != 409 && (type < 498 || type > 506) && type != 424 && type != 426 && type != 520)
        {
            float num7 = 1f;
            if (type == 624)
            {
                num7 = 2.5f;
            }
            if (type == 186)
            {
                num7 = 1.1f;
            }
            if (type == 187)
            {
                num7 = 0.9f;
            }
            if (type == 188)
            {
                num7 = 1.2f;
            }
            if (type == 189)
            {
                num7 = 0.8f;
            }
            if (type == 132)
            {
                num7 = 0.95f;
            }
            if (type == 200)
            {
                num7 = 0.87f;
            }
            if (type == 223)
            {
                num7 = 1.05f;
            }
            if (type == 632)
            {
                num7 = 0.8f;
            }
            if (type == 489)
            {
                val = Main.player[target].Center - base.Center;
                float num8 = ((Vector2)(ref val)).Length();
                num8 *= 0.0025f;
                if ((double)num8 > 1.5)
                {
                    num8 = 1.5f;
                }
                num7 = ((!Main.expertMode) ? (2.5f - num8) : (3f - num8));
                num7 *= 0.8f;
            }
            if (type == 489 || type == 3 || type == 132 || type == 186 || type == 187 || type == 188 || type == 189 || type == 200 || type == 223 || type == 331 || type == 332)
            {
                num7 *= 1f + (1f - scale);
            }
            if (velocity.X < 0f - num7 || velocity.X > num7)
            {
                if (velocity.Y == 0f)
                {
                    velocity *= 0.8f;
                }
            }
            else if (velocity.X < num7 && direction == 1)
            {
                velocity.X += 0.07f;
                if (velocity.X > num7)
                {
                    velocity.X = num7;
                }
            }
            else if (velocity.X > 0f - num7 && direction == -1)
            {
                velocity.X -= 0.07f;
                if (velocity.X < 0f - num7)
                {
                    velocity.X = 0f - num7;
                }
            }
        }
        if (type >= 277 && type <= 280)
        {
            Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.2f, 0.1f, 0f);
        }
        else if (type == 520)
        {
            Lighting.AddLight(base.Top + new Vector2(0f, 20f), 0.3f, 0.3f, 0.7f);
        }
        else if (type == 525)
        {
            Vector3 rgb = new Vector3(0.7f, 1f, 0.2f) * 0.5f;
            Lighting.AddLight(base.Top + new Vector2(0f, 15f), rgb);
        }
        else if (type == 526)
        {
            Vector3 rgb2 = new Vector3(1f, 1f, 0.5f) * 0.4f;
            Lighting.AddLight(base.Top + new Vector2(0f, 15f), rgb2);
        }
        else if (type == 527)
        {
            Vector3 rgb3 = new Vector3(0.6f, 0.3f, 1f) * 0.4f;
            Lighting.AddLight(base.Top + new Vector2(0f, 15f), rgb3);
        }
        else if (type == 415)
        {
            hide = false;
            for (int num9 = 0; num9 < 200; num9++)
            {
                if (Main.npc[num9].active && Main.npc[num9].type == 416 && Main.npc[num9].ai[0] == (float)whoAmI)
                {
                    hide = true;
                    break;
                }
            }
        }
        else if (type == 258)
        {
            if (velocity.Y != 0f)
            {
                TargetClosest();
                spriteDirection = direction;
                if (Main.player[target].Center.X < position.X && velocity.X > 0f)
                {
                    velocity.X *= 0.95f;
                }
                else if (Main.player[target].Center.X > position.X + (float)width && velocity.X < 0f)
                {
                    velocity.X *= 0.95f;
                }
                if (Main.player[target].Center.X < position.X && velocity.X > -5f)
                {
                    velocity.X -= 0.1f;
                }
                else if (Main.player[target].Center.X > position.X + (float)width && velocity.X < 5f)
                {
                    velocity.X += 0.1f;
                }
            }
            else if (Main.player[target].Center.Y + 50f < position.Y && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
            {
                flag = true;
                velocity.Y = -7f;
            }
        }
        else if (type == 425)
        {
            if (localAI[3] == 0f)
            {
                localAI[3] = 1f;
                ai[3] = -120f;
            }
            if (velocity.Y == 0f)
            {
                ai[2] = 0f;
            }
            if (velocity.Y != 0f && ai[2] == 1f)
            {
                TargetClosest();
                spriteDirection = -direction;
                if (Collision.CanHit(base.Center, 0, 0, Main.player[target].Center, 0, 0))
                {
                    float num10 = 0.3f;
                    float num11 = 8f;
                    float num12 = 0.3f;
                    float num14 = 7f;
                    float num15 = Main.player[target].Center.X - (float)(direction * 300) - base.Center.X;
                    float num16 = Main.player[target].Bottom.Y - base.Bottom.Y;
                    if (num15 < 0f && velocity.X > 0f)
                    {
                        velocity.X *= 0.9f;
                    }
                    else if (num15 > 0f && velocity.X < 0f)
                    {
                        velocity.X *= 0.9f;
                    }
                    if (num15 < 0f && velocity.X > 0f - num14)
                    {
                        velocity.X -= num12;
                    }
                    else if (num15 > 0f && velocity.X < num14)
                    {
                        velocity.X += num12;
                    }
                    if (velocity.X > num14)
                    {
                        velocity.X = num14;
                    }
                    if (velocity.X < 0f - num14)
                    {
                        velocity.X = 0f - num14;
                    }
                    if (num16 < -20f && velocity.Y > 0f)
                    {
                        velocity.Y *= 0.8f;
                    }
                    else if (num16 > 20f && velocity.Y < 0f)
                    {
                        velocity.Y *= 0.8f;
                    }
                    if (num16 < -20f && velocity.Y > 0f - num11)
                    {
                        velocity.Y -= num10;
                    }
                    else if (num16 > 20f && velocity.Y < num11)
                    {
                        velocity.Y += num10;
                    }
                }
                if (Main.rand.Next(3) == 0)
                {
                    position += netOffset;
                    Vector2 vector16 = base.Center + new Vector2((float)(direction * -14), -8f) - Vector2.One * 4f;
                    Vector2 vector17 = new Vector2((float)(direction * -6), 12f) * 0.2f + Utils.RandomVector2(Main.rand, -1f, 1f) * 0.1f;
                    Dust obj7 = Main.dust[Dust.NewDust(vector16, 8, 8, 229, vector17.X, vector17.Y, 100, Color.Transparent, 1f + Main.rand.NextFloat() * 0.5f)];
                    obj7.noGravity = true;
                    obj7.velocity = vector17;
                    obj7.customData = this;
                    position -= netOffset;
                }
                for (int num17 = 0; num17 < 200; num17++)
                {
                    if (num17 != whoAmI && Main.npc[num17].active && Main.npc[num17].type == type && Math.Abs(position.X - Main.npc[num17].position.X) + Math.Abs(position.Y - Main.npc[num17].position.Y) < (float)width)
                    {
                        if (position.X < Main.npc[num17].position.X)
{
                            velocity.X -= 0.15f;
                        }
                        else
{
                            velocity.X += 0.15f;
                        }
                        if (position.Y < Main.npc[num17].position.Y)
{
                            velocity.Y -= 0.15f;
                        }
                        else
{
                            velocity.Y += 0.15f;
                        }
                    }
                }
            }
            else if (Main.player[target].Center.Y + 100f < position.Y && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
            {
                flag = true;
                velocity.Y = -5f;
                ai[2] = 1f;
            }
            if (ai[3] < 0f)
            {
                ai[3] += 1f;
            }
            int num18 = 30;
            int num19 = 10;
            int num20 = 180;
            if (ai[3] >= 0f && ai[3] <= (float)num18)
            {
                Vector2 vector18 = DirectionTo(Main.player[target].Center);
                bool flag4 = Math.Abs(vector18.Y) <= Math.Abs(vector18.X);
                bool flag5 = Distance(Main.player[target].Center) < 800f && flag4 && Collision.CanHitLine(base.Center, 0, 0, Main.player[target].Center, 0, 0);
                ai[3] = MathHelper.Clamp(ai[3] + (float)flag5.ToDirectionInt(), 0f, (float)num18);
            }
            if (ai[3] >= (float)(num18 + 1) && (ai[3] += 1f) >= (float)(num18 + num19))
            {
                ai[3] = num18 - num20;
                netUpdate = true;
            }
            if (Main.netMode != 1 && ai[3] == (float)num18)
            {
                ai[3] += 1f;
                netUpdate = true;
                int num21 = 20;
                Vector2 chaserPosition = base.Center + new Vector2((float)(direction * 30), 2f);
                Vector2 vector19 = DirectionTo(Main.player[target].Center) * (float)num21;
                if (vector19.HasNaNs())
                {
                    ((Vector2)(ref vector19))._002Ector((float)(direction * num21), 0f);
                }
                int num22 = 2;
                Utils.ChaseResults chaseResults = Utils.GetChaseResults(chaserPosition, num21, Main.player[target].Center, Main.player[target].velocity * 0.5f / (float)num22);
                if (chaseResults.InterceptionHappens)
                {
                    Vector2 vector20 = chaseResults.ChaserVelocity / (float)num22;
                    vector19.X = vector20.X;
                    vector19.Y = vector20.Y;
                }
                int attackDamage_ForProjectiles = GetAttackDamage_ForProjectiles(75f, 50f);
                for (int num23 = 0; num23 < 4; num23++)
                {
                    Vector2 vector22 = vector19 + Utils.RandomVector2(Main.rand, -0.8f, 0.8f) * (float)((num23 != 0) ? 1 : 0);
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), chaserPosition.X, chaserPosition.Y, vector22.X, vector22.Y, 577, attackDamage_ForProjectiles, 1f, Main.myPlayer);
                }
            }
        }
        else if (type == 427)
        {
            if (velocity.Y == 0f)
            {
                ai[2] = 0f;
                rotation = 0f;
            }
            else
            {
                rotation = velocity.X * 0.1f;
            }
            if (velocity.Y != 0f && ai[2] == 1f)
            {
                TargetClosest();
                spriteDirection = -direction;
                if (Collision.CanHit(base.Center, 0, 0, Main.player[target].Center, 0, 0))
                {
                    float num25 = Main.player[target].Center.X - base.Center.X;
                    float num26 = Main.player[target].Center.Y - base.Center.Y;
                    if (num25 < 0f && velocity.X > 0f)
                    {
                        velocity.X *= 0.98f;
                    }
                    else if (num25 > 0f && velocity.X < 0f)
                    {
                        velocity.X *= 0.98f;
                    }
                    if (num25 < -20f && velocity.X > -6f)
                    {
                        velocity.X -= 0.015f;
                    }
                    else if (num25 > 20f && velocity.X < 6f)
                    {
                        velocity.X += 0.015f;
                    }
                    if (velocity.X > 6f)
                    {
                        velocity.X = 6f;
                    }
                    if (velocity.X < -6f)
                    {
                        velocity.X = -6f;
                    }
                    if (num26 < -20f && velocity.Y > 0f)
                    {
                        velocity.Y *= 0.98f;
                    }
                    else if (num26 > 20f && velocity.Y < 0f)
                    {
                        velocity.Y *= 0.98f;
                    }
                    if (num26 < -20f && velocity.Y > -6f)
                    {
                        velocity.Y -= 0.15f;
                    }
                    else if (num26 > 20f && velocity.Y < 6f)
                    {
                        velocity.Y += 0.15f;
                    }
                }
                for (int num27 = 0; num27 < 200; num27++)
                {
                    if (num27 != whoAmI && Main.npc[num27].active && Main.npc[num27].type == type && Math.Abs(position.X - Main.npc[num27].position.X) + Math.Abs(position.Y - Main.npc[num27].position.Y) < (float)width)
                    {
                        if (position.X < Main.npc[num27].position.X)
{
                            velocity.X -= 0.05f;
                        }
                        else
{
                            velocity.X += 0.05f;
                        }
                        if (position.Y < Main.npc[num27].position.Y)
{
                            velocity.Y -= 0.05f;
                        }
                        else
{
                            velocity.Y += 0.05f;
                        }
                    }
                }
            }
            else if (Main.player[target].Center.Y + 100f < position.Y && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
            {
                flag = true;
                velocity.Y = -5f;
                ai[2] = 1f;
            }
        }
        else if (type == 426)
        {
            float num28 = 6f;
            float num29 = 0.2f;
            float num30 = 6f;
            if (ai[1] > 0f && velocity.Y > 0f)
            {
                velocity.Y *= 0.85f;
                if (velocity.Y == 0f)
                {
                    velocity.Y = -0.4f;
                }
            }
            if (velocity.Y != 0f)
            {
                TargetClosest();
                spriteDirection = direction;
                if (Collision.CanHit(base.Center, 0, 0, Main.player[target].Center, 0, 0))
                {
                    float num31 = Main.player[target].Center.X - (float)(direction * 300) - base.Center.X;
                    if (num31 < 40f && velocity.X > 0f)
                    {
                        velocity.X *= 0.98f;
                    }
                    else if (num31 > 40f && velocity.X < 0f)
                    {
                        velocity.X *= 0.98f;
                    }
                    if (num31 < 40f && velocity.X > 0f - num28)
                    {
                        velocity.X -= num29;
                    }
                    else if (num31 > 40f && velocity.X < num28)
                    {
                        velocity.X += num29;
                    }
                    if (velocity.X > num28)
                    {
                        velocity.X = num28;
                    }
                    if (velocity.X < 0f - num28)
                    {
                        velocity.X = 0f - num28;
                    }
                }
            }
            else if (Main.player[target].Center.Y + 100f < position.Y && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
            {
                flag = true;
                velocity.Y = 0f - num30;
            }
            for (int num32 = 0; num32 < 200; num32++)
            {
                if (num32 != whoAmI && Main.npc[num32].active && Main.npc[num32].type == type && Math.Abs(position.X - Main.npc[num32].position.X) + Math.Abs(position.Y - Main.npc[num32].position.Y) < (float)width)
                {
                    if (position.X < Main.npc[num32].position.X)
                    {
                        velocity.X -= 0.1f;
                    }
                    else
                    {
                        velocity.X += 0.1f;
                    }
                    if (position.Y < Main.npc[num32].position.Y)
                    {
                        velocity.Y -= 0.1f;
                    }
                    else
                    {
                        velocity.Y += 0.1f;
                    }
                }
            }
            if (Main.rand.Next(6) == 0 && ai[1] <= 20f)
            {
                position += netOffset;
                Dust obj8 = Main.dust[Dust.NewDust(base.Center + new Vector2((float)((spriteDirection == 1) ? 8 : (-20)), -20f), 8, 8, 229, velocity.X, velocity.Y, 100)];
                obj8.velocity = obj8.velocity / 4f + velocity / 2f;
                obj8.scale = 0.6f;
                obj8.noLight = true;
                position -= netOffset;
            }
            if (ai[1] >= 57f)
            {
                position += netOffset;
                int num33 = Utils.SelectRandom<int>(Main.rand, 161, 229);
                Dust obj9 = Main.dust[Dust.NewDust(base.Center + new Vector2((float)((spriteDirection == 1) ? 8 : (-20)), -20f), 8, 8, num33, velocity.X, velocity.Y, 100)];
                obj9.velocity = obj9.velocity / 4f + DirectionTo(Main.player[target].Top);
                obj9.scale = 1.2f;
                obj9.noLight = true;
                position -= netOffset;
            }
            if (Main.rand.Next(6) == 0)
            {
                position += netOffset;
                Dust dust5 = Main.dust[Dust.NewDust(base.Center, 2, 2, 229)];
                dust5.position = base.Center + new Vector2((float)((spriteDirection == 1) ? 26 : (-26)), 24f);
                dust5.velocity.X = 0f;
                if (dust5.velocity.Y < 0f)
                {
                    dust5.velocity.Y = 0f;
                }
                dust5.noGravity = true;
                dust5.scale = 1f;
                dust5.noLight = true;
                position -= netOffset;
            }
        }
        else if (type == 185)
        {
            if (velocity.Y == 0f)
            {
                rotation = 0f;
                localAI[0] = 0f;
            }
            else if (localAI[0] == 1f)
            {
                rotation += velocity.X * 0.05f;
            }
        }
        else if (type == 428)
        {
            if (velocity.Y == 0f)
            {
                rotation = 0f;
            }
            else
            {
                rotation += velocity.X * 0.08f;
            }
        }
        if (type == 159 && Main.netMode != 1)
        {
            Vector2 vector23 = default(Vector2);
            ((Vector2)(ref vector23))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
            float num204 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector23.X;
            float num35 = Main.player[target].position.Y + (float)Main.player[target].height * 0.5f - vector23.Y;
            if ((float)Math.Sqrt(num204 * num204 + num35 * num35) > 300f)
            {
                Transform(158);
            }
        }
        if (Main.netMode != 1)
        {
            if (Main.expertMode && target >= 0 && (type == 163 || type == 238 || type == 236 || type == 237) && Collision.CanHit(base.Center, 1, 1, Main.player[target].Center, 1, 1))
            {
                localAI[0] += 1f;
                if (justHit)
                {
                    localAI[0] -= Main.rand.Next(20, 60);
                    if (localAI[0] < 0f)
                    {
                        localAI[0] = 0f;
                    }
                }
                if (localAI[0] > (float)Main.rand.Next(180, 900))
                {
                    localAI[0] = 0f;
                    Vector2 vector24 = Main.player[target].Center - base.Center;
                    ((Vector2)(ref vector24)).Normalize();
                    vector24 *= 8f;
                    int attackDamage_ForProjectiles2 = GetAttackDamage_ForProjectiles(18f, 18f);
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, vector24.X, vector24.Y, 472, attackDamage_ForProjectiles2, 0f, Main.myPlayer);
                }
            }
            if (velocity.Y == 0f)
            {
                int num36 = -1;
                switch (type)
                {
                case 164:
                    num36 = 165;
                    break;
                case 236:
                    num36 = 237;
                    break;
                case 163:
                    num36 = 238;
                    break;
                case 239:
                    num36 = 240;
                    break;
                case 530:
                    num36 = 531;
                    break;
                }
                if (num36 != -1 && NPCCanStickToWalls())
                {
                    Transform(num36);
                }
            }
        }
        if (type == 243)
        {
            if (justHit && Main.rand.Next(3) == 0)
            {
                ai[2] -= Main.rand.Next(30);
            }
            if (ai[2] < 0f)
            {
                ai[2] = 0f;
            }
            if (confused)
            {
                ai[2] = 0f;
            }
            ai[2] += 1f;
            float num37 = Main.rand.Next(30, 900);
            num37 *= (float)life / (float)lifeMax;
            num37 += 30f;
            if (Main.netMode != 1 && ai[2] >= num37 && velocity.Y == 0f && !Main.player[target].dead && !Main.player[target].frozen && ((direction > 0 && base.Center.X < Main.player[target].Center.X) || (direction < 0 && base.Center.X > Main.player[target].Center.X)) && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
            {
                Vector2 vector25 = default(Vector2);
                ((Vector2)(ref vector25))._002Ector(position.X + (float)width * 0.5f, position.Y + 20f);
                vector25.X += 10 * direction;
                float num38 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector25.X;
                float num39 = Main.player[target].position.Y + (float)Main.player[target].height * 0.5f - vector25.Y;
                num38 += (float)Main.rand.Next(-40, 41);
                num39 += (float)Main.rand.Next(-40, 41);
                float num40 = (float)Math.Sqrt(num38 * num38 + num39 * num39);
                netUpdate = true;
                num40 = 15f / num40;
                num38 *= num40;
                num39 *= num40;
                int num41 = 32;
                int num42 = 257;
                vector25.X += num38 * 3f;
                vector25.Y += num39 * 3f;
                Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector25.X, vector25.Y, num38, num39, num42, num41, 0f, Main.myPlayer);
                ai[2] = 0f;
            }
        }
        if (type == 251)
        {
            if (justHit)
            {
                ai[2] -= Main.rand.Next(30);
            }
            if (ai[2] < 0f)
            {
                ai[2] = 0f;
            }
            if (confused)
            {
                ai[2] = 0f;
            }
            ai[2] += 1f;
            float num43 = Main.rand.Next(60, 1800);
            num43 *= (float)life / (float)lifeMax;
            num43 += 15f;
            if (Main.netMode != 1 && ai[2] >= num43 && velocity.Y == 0f && !Main.player[target].dead && !Main.player[target].frozen && ((direction > 0 && base.Center.X < Main.player[target].Center.X) || (direction < 0 && base.Center.X > Main.player[target].Center.X)) && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
            {
                Vector2 vector26 = default(Vector2);
                ((Vector2)(ref vector26))._002Ector(position.X + (float)width * 0.5f, position.Y + 12f);
                vector26.X += 6 * direction;
                float num44 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector26.X;
                float num46 = Main.player[target].position.Y + (float)Main.player[target].height * 0.5f - vector26.Y;
                num44 += (float)Main.rand.Next(-40, 41);
                num46 += (float)Main.rand.Next(-30, 0);
                float num47 = (float)Math.Sqrt(num44 * num44 + num46 * num46);
                netUpdate = true;
                num47 = 15f / num47;
                num44 *= num47;
                num46 *= num47;
                int num48 = 30;
                int num49 = 83;
                vector26.X += num44 * 3f;
                vector26.Y += num46 * 3f;
                Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector26.X, vector26.Y, num44, num46, num49, num48, 0f, Main.myPlayer);
                ai[2] = 0f;
            }
        }
        if (type == 386)
        {
            if (confused)
            {
                ai[2] = -60f;
            }
            else
            {
                if (ai[2] < 60f)
                {
                    ai[2] += 1f;
                }
                if (ai[2] > 0f && CountNPCS(387) >= 4 * CountNPCS(386))
                {
                    ai[2] = 0f;
                }
                if (justHit)
                {
                    ai[2] = -30f;
                }
                if (ai[2] == 30f)
                {
                    int num50 = (int)position.X / 16;
                    int num51 = (int)position.Y / 16;
                    int num52 = (int)position.X / 16;
                    int num53 = (int)position.Y / 16;
                    int num54 = 5;
                    int num55 = 0;
                    bool flag6 = false;
                    int num57 = 2;
                    int num58 = 0;
                    while (!flag6 && num55 < 100)
                    {
                        num55++;
                        int num59 = Main.rand.Next(num50 - num54, num50 + num54);
                        for (int num60 = Main.rand.Next(num51 - num54, num51 + num54); num60 < num51 + num54; num60++)
{
                            if ((num60 < num51 - num57 || num60 > num51 + num57 || num59 < num50 - num57 || num59 > num50 + num57) && (num60 < num53 - num58 || num60 > num53 + num58 || num59 < num52 - num58 || num59 > num52 + num58) && Main.tile[num59, num60].nactive())
{
                                bool flag7 = true;
                                if (Main.tile[num59, num60 - 1].lava())
{
                                    flag7 = false;
                                }
                                if (flag7 && Main.tileSolid[Main.tile[num59, num60].type] && !Collision.SolidTiles(num59 - 1, num59 + 1, num60 - 4, num60 - 1))
{
                                    int num61 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), num59 * 16 - width / 2, num60 * 16, 387);
                                    Main.npc[num61].position.Y = num60 * 16 - Main.npc[num61].height;
                                    flag6 = true;
                                    netUpdate = true;
                                    break;
                                }
                            }
                        }
                    }
                }
                if (ai[2] == 60f)
                {
                    ai[2] = -120f;
                }
            }
        }
        if (type == 389)
        {
            if (confused)
            {
                ai[2] = -60f;
            }
            else
            {
                if (ai[2] < 20f)
                {
                    ai[2] += 1f;
                }
                if (justHit)
                {
                    ai[2] = -30f;
                }
                if (ai[2] == 20f && Main.netMode != 1)
                {
                    ai[2] = -10 + Main.rand.Next(3) * -10;
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y + 8f, direction * 6, 0f, 437, 25, 1f, Main.myPlayer);
                }
            }
        }
        if (type == 110 || type == 111 || type == 206 || type == 214 || type == 215 || type == 216 || type == 290 || type == 291 || type == 292 || type == 293 || type == 350 || type == 379 || type == 380 || type == 381 || type == 382 || (type >= 449 && type <= 452) || type == 468 || type == 481 || type == 411 || type == 409 || (type >= 498 && type <= 506) || type == 424 || type == 426 || type == 520)
        {
            bool flag8 = type == 381 || type == 382 || type == 520;
            bool flag9 = type == 426;
            bool flag10 = true;
            int num62 = -1;
            int num63 = -1;
            if (type == 411)
            {
                flag8 = true;
                num62 = 120;
                num63 = 120;
                if (ai[1] <= 220f)
                {
                    flag10 = false;
                }
            }
            if (ai[1] > 0f)
            {
                ai[1] -= 1f;
            }
            if (justHit)
            {
                ai[1] = 30f;
                ai[2] = 0f;
            }
            int num64 = 70;
            if (type == 379 || type == 380)
            {
                num64 = 80;
            }
            if (type == 381 || type == 382)
            {
                num64 = 80;
            }
            if (type == 520)
            {
                num64 = 15;
            }
            if (type == 350)
            {
                num64 = 110;
            }
            if (type == 291)
            {
                num64 = 200;
            }
            if (type == 292)
            {
                num64 = 120;
            }
            if (type == 293)
            {
                num64 = 90;
            }
            if (type == 111)
            {
                num64 = 180;
            }
            if (type == 206)
            {
                num64 = 50;
            }
            if (type == 481)
            {
                num64 = 100;
            }
            if (type == 214)
            {
                num64 = 40;
            }
            if (type == 215)
            {
                num64 = 80;
            }
            if (type == 290)
            {
                num64 = 30;
            }
            if (type == 411)
            {
                num64 = 330;
            }
            if (type == 409)
            {
                num64 = 60;
            }
            if (type == 424)
            {
                num64 = 180;
            }
            if (type == 426)
            {
                num64 = 60;
            }
            bool flag11 = false;
            if (type == 216)
            {
                if (localAI[2] >= 20f)
                {
                    flag11 = true;
                }
                num64 = ((!flag11) ? 8 : 60);
            }
            int num65 = num64 / 2;
            if (type == 424)
            {
                num65 = num64 - 1;
            }
            if (type == 426)
            {
                num65 = num64 - 1;
            }
            if (type == 411)
            {
                num65 = 220;
            }
            if (confused)
            {
                ai[2] = 0f;
            }
            if (ai[2] > 0f)
            {
                if (flag10)
                {
                    TargetClosest();
                }
                if (ai[1] == (float)num65)
                {
                    if (type == 216)
                    {
                        localAI[2] += 1f;
                    }
                    float num66 = 11f;
                    if (type == 111)
                    {
                        num66 = 9f;
                    }
                    if (type == 206)
                    {
                        num66 = 7f;
                    }
                    if (type == 290)
                    {
                        num66 = 9f;
                    }
                    if (type == 293)
                    {
                        num66 = 4f;
                    }
                    if (type == 214)
                    {
                        num66 = 14f;
                    }
                    if (type == 215)
                    {
                        num66 = 16f;
                    }
                    if (type == 382)
                    {
                        num66 = 7f;
                    }
                    if (type == 520)
                    {
                        num66 = 8f;
                    }
                    if (type == 409)
                    {
                        num66 = 4f;
                    }
                    if (type >= 449 && type <= 452)
                    {
                        num66 = 7f;
                    }
                    if (type == 481)
                    {
                        num66 = 8f;
                    }
                    if (type == 468)
                    {
                        num66 = 7.5f;
                    }
                    if (type == 411)
                    {
                        num66 = 1f;
                    }
                    if (type >= 498 && type <= 506)
                    {
                        num66 = 7f;
                    }
                    Vector2 chaserPosition2 = default(Vector2);
                    ((Vector2)(ref chaserPosition2))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                    if (type == 481)
                    {
                        chaserPosition2.Y -= 14f;
                    }
                    if (type == 206)
                    {
                        chaserPosition2.Y -= 10f;
                    }
                    if (type == 290)
                    {
                        chaserPosition2.Y -= 10f;
                    }
                    if (type == 381 || type == 382)
                    {
                        chaserPosition2.Y += 6f;
                    }
                    if (type == 520)
                    {
                        chaserPosition2.Y = position.Y + 20f;
                    }
                    if (type >= 498 && type <= 506)
                    {
                        chaserPosition2.Y -= 8f;
                    }
                    if (type == 426)
                    {
                        chaserPosition2 += new Vector2((float)(spriteDirection * 2), -12f);
                        num66 = 7f;
                    }
                    float num68 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - chaserPosition2.X;
                    float num69 = Math.Abs(num68) * 0.1f;
                    if (type == 291 || type == 292)
                    {
                        num69 = 0f;
                    }
                    if (type == 215)
                    {
                        num69 = Math.Abs(num68) * 0.08f;
                    }
                    if (type == 214 || (type == 216 && !flag11))
                    {
                        num69 = 0f;
                    }
                    if (type == 381 || type == 382 || type == 520)
                    {
                        num69 = 0f;
                    }
                    if (type >= 449 && type <= 452)
                    {
                        num69 = Math.Abs(num68) * (float)Main.rand.Next(10, 50) * 0.01f;
                    }
                    if (type == 468)
                    {
                        num69 = Math.Abs(num68) * (float)Main.rand.Next(10, 50) * 0.01f;
                    }
                    if (type == 481)
                    {
                        num69 = Math.Abs(num68) * (float)Main.rand.Next(-10, 11) * 0.0035f;
                    }
                    if (type >= 498 && type <= 506)
                    {
                        num69 = Math.Abs(num68) * (float)Main.rand.Next(1, 11) * 0.0025f;
                    }
                    float num70 = Main.player[target].position.Y + (float)Main.player[target].height * 0.5f - chaserPosition2.Y - num69;
                    if (type == 291)
                    {
                        num68 += (float)Main.rand.Next(-40, 41) * 0.2f;
                        num70 += (float)Main.rand.Next(-40, 41) * 0.2f;
                    }
                    else if (type == 381 || type == 382 || type == 520)
                    {
                        num68 += (float)Main.rand.Next(-100, 101) * 0.4f;
                        num70 += (float)Main.rand.Next(-100, 101) * 0.4f;
                        num68 *= (float)Main.rand.Next(85, 116) * 0.01f;
                        num70 *= (float)Main.rand.Next(85, 116) * 0.01f;
                        if (type == 520)
{
                            num68 += (float)Main.rand.Next(-100, 101) * 0.6f;
                            num70 += (float)Main.rand.Next(-100, 101) * 0.6f;
                            num68 *= (float)Main.rand.Next(85, 116) * 0.015f;
                            num70 *= (float)Main.rand.Next(85, 116) * 0.015f;
                        }
                    }
                    else if (type == 481)
                    {
                        num68 += (float)Main.rand.Next(-40, 41) * 0.4f;
                        num70 += (float)Main.rand.Next(-40, 41) * 0.4f;
                    }
                    else if (type >= 498 && type <= 506)
                    {
                        num68 += (float)Main.rand.Next(-40, 41) * 0.3f;
                        num70 += (float)Main.rand.Next(-40, 41) * 0.3f;
                    }
                    else if (type == 426)
                    {
                        num68 += (float)Main.rand.Next(-30, 31) * 0.3f;
                        num70 += (float)Main.rand.Next(-30, 31) * 0.3f;
                    }
                    else if (type != 292)
                    {
                        num68 += (float)Main.rand.Next(-40, 41);
                        num70 += (float)Main.rand.Next(-40, 41);
                    }
                    float num71 = (float)Math.Sqrt(num68 * num68 + num70 * num70);
                    netUpdate = true;
                    num71 = num66 / num71;
                    num68 *= num71;
                    num70 *= num71;
                    int num72 = 35;
                    int num73 = 82;
                    if (type == 111)
                    {
                        num72 = 11;
                    }
                    if (type == 206)
                    {
                        num72 = 37;
                    }
                    if (type == 379 || type == 380)
                    {
                        num72 = 40;
                    }
                    if (type == 350)
                    {
                        num72 = 45;
                    }
                    if (type == 468)
                    {
                        num72 = 50;
                    }
                    if (type == 111)
                    {
                        num73 = 81;
                    }
                    if (type == 379 || type == 380)
                    {
                        num73 = 81;
                    }
                    if (type == 381)
                    {
                        num73 = 436;
                        num72 = 24;
                    }
                    if (type == 382)
                    {
                        num73 = 438;
                        num72 = 30;
                    }
                    if (type == 520)
                    {
                        num73 = 592;
                        num72 = 35;
                    }
                    if (type >= 449 && type <= 452)
                    {
                        num73 = 471;
                        num72 = 15;
                    }
                    if (type >= 498 && type <= 506)
                    {
                        num73 = 572;
                        num72 = 14;
                    }
                    if (type == 481)
                    {
                        num73 = 508;
                        num72 = 18;
                    }
                    if (type == 206)
                    {
                        num73 = 177;
                    }
                    if (type == 468)
                    {
                        num73 = 501;
                    }
                    if (type == 411)
                    {
                        num73 = 537;
                        num72 = GetAttackDamage_ForProjectiles(60f, 45f);
                    }
                    if (type == 424)
                    {
                        num73 = 573;
                        num72 = GetAttackDamage_ForProjectiles(60f, 45f);
                    }
                    if (type == 426)
                    {
                        num73 = 581;
                        num72 = GetAttackDamage_ForProjectiles(60f, 45f);
                    }
                    if (type == 291)
                    {
                        num73 = 302;
                        num72 = 100;
                    }
                    if (type == 290)
                    {
                        num73 = 300;
                        num72 = 60;
                    }
                    if (type == 293)
                    {
                        num73 = 303;
                        num72 = 60;
                    }
                    if (type == 214)
                    {
                        num73 = 180;
                        num72 = 25;
                    }
                    if (type == 215)
                    {
                        num73 = 82;
                        num72 = 40;
                    }
                    if (type == 292)
                    {
                        num72 = 50;
                        num73 = 180;
                    }
                    if (type == 216)
                    {
                        num73 = 180;
                        num72 = 30;
                        if (flag11)
{
                            num72 = 100;
                            num73 = 240;
                            localAI[2] = 0f;
                        }
                    }
                    Player player3 = Main.player[target];
                    Vector2? vector27 = null;
                    if (type == 426)
                    {
                        vector27 = Main.rand.NextVector2FromRectangle(player3.Hitbox);
                    }
                    if (vector27.HasValue)
                    {
                        Utils.ChaseResults chaseResults2 = Utils.GetChaseResults(chaserPosition2, num66, vector27.Value, player3.velocity);
                        if (chaseResults2.InterceptionHappens)
{
                            Vector2 val4 = Utils.FactorAcceleration(chaseResults2.ChaserVelocity, chaseResults2.InterceptionTime, new Vector2(0f, 0.1f), 15);
                            num68 = val4.X;
                            num70 = val4.Y;
                        }
                    }
                    chaserPosition2.X += num68;
                    chaserPosition2.Y += num70;
                    if (type == 290)
                    {
                        num72 = GetAttackDamage_ForProjectiles(num72, (float)num72 * 0.75f);
                    }
                    if (type >= 381 && type <= 392)
                    {
                        num72 = GetAttackDamage_ForProjectiles(num72, (float)num72 * 0.8f);
                    }
                    if (Main.netMode != 1)
                    {
                        if (type == 292)
{
                            for (int num74 = 0; num74 < 4; num74++)
{
                                num68 = player3.position.X + (float)player3.width * 0.5f - chaserPosition2.X;
                                num70 = player3.position.Y + (float)player3.height * 0.5f - chaserPosition2.Y;
                                num71 = (float)Math.Sqrt(num68 * num68 + num70 * num70);
                                num71 = 12f / num71;
                                num68 = (num68 += (float)Main.rand.Next(-40, 41));
                                num70 = (num70 += (float)Main.rand.Next(-40, 41));
                                num68 *= num71;
                                num70 *= num71;
                                Projectile.NewProjectile(GetSpawnSource_ForProjectile(), chaserPosition2.X, chaserPosition2.Y, num68, num70, num73, num72, 0f, Main.myPlayer);
                            }
                        }
                        else if (type == 411)
{
                            Projectile.NewProjectile(GetSpawnSource_ForProjectile(), chaserPosition2.X, chaserPosition2.Y, num68, num70, num73, num72, 0f, Main.myPlayer, 0f, whoAmI);
                        }
                        else if (type == 424)
{
                            for (int num75 = 0; num75 < 4; num75++)
{
                                Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center.X - (float)(spriteDirection * 4), base.Center.Y + 6f, (float)(-3 + 2 * num75) * 0.15f, (float)(-Main.rand.Next(0, 3)) * 0.2f - 0.1f, num73, num72, 0f, Main.myPlayer, 0f, whoAmI);
                            }
                        }
                        else if (type == 409)
{
                            int num76 = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X, (int)base.Center.Y, 410, whoAmI);
                            Main.npc[num76].velocity = new Vector2(num68, -6f + num70);
                        }
                        else
{
                            Projectile.NewProjectile(GetSpawnSource_ForProjectile(), chaserPosition2.X, chaserPosition2.Y, num68, num70, num73, num72, 0f, Main.myPlayer);
                        }
                    }
                    if (Math.Abs(num70) > Math.Abs(num68) * 2f)
                    {
                        if (num70 > 0f)
{
                            ai[2] = 1f;
                        }
                        else
{
                            ai[2] = 5f;
                        }
                    }
                    else if (Math.Abs(num68) > Math.Abs(num70) * 2f)
                    {
                        ai[2] = 3f;
                    }
                    else if (num70 > 0f)
                    {
                        ai[2] = 2f;
                    }
                    else
                    {
                        ai[2] = 4f;
                    }
                }
                if ((velocity.Y != 0f && !flag9) || ai[1] <= 0f)
                {
                    ai[2] = 0f;
                    ai[1] = 0f;
                }
                else if (!flag8 || (num62 != -1 && ai[1] >= (float)num62 && ai[1] < (float)(num62 + num63) && (!flag9 || velocity.Y == 0f)))
                {
                    velocity.X *= 0.9f;
                    spriteDirection = direction;
                }
            }
            if (type == 468 && !Main.eclipse)
            {
                flag8 = true;
            }
            else if ((ai[2] <= 0f || flag8) && (velocity.Y == 0f || flag9) && ai[1] <= 0f && !Main.player[target].dead)
            {
                bool flag13 = Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height);
                if (type == 520)
                {
                    flag13 = Collision.CanHitLine(base.Top + new Vector2(0f, 20f), 0, 0, Main.player[target].position, Main.player[target].width, Main.player[target].height);
                }
                if (Main.player[target].stealth == 0f && Main.player[target].itemAnimation == 0)
                {
                    flag13 = false;
                }
                if (flag13)
                {
                    float num77 = 10f;
                    Vector2 vector28 = default(Vector2);
                    ((Vector2)(ref vector28))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                    float num79 = Main.player[target].position.X + (float)Main.player[target].width * 0.5f - vector28.X;
                    float num80 = Math.Abs(num79) * 0.1f;
                    float num81 = Main.player[target].position.Y + (float)Main.player[target].height * 0.5f - vector28.Y - num80;
                    num79 += (float)Main.rand.Next(-40, 41);
                    num81 += (float)Main.rand.Next(-40, 41);
                    float num82 = (float)Math.Sqrt(num79 * num79 + num81 * num81);
                    float num83 = 700f;
                    if (type == 214)
                    {
                        num83 = 550f;
                    }
                    if (type == 215)
                    {
                        num83 = 800f;
                    }
                    if (type >= 498 && type <= 506)
                    {
                        num83 = 190f;
                    }
                    if (type >= 449 && type <= 452)
                    {
                        num83 = 200f;
                    }
                    if (type == 481)
                    {
                        num83 = 400f;
                    }
                    if (type == 468)
                    {
                        num83 = 400f;
                    }
                    if (num82 < num83)
                    {
                        netUpdate = true;
                        velocity.X *= 0.5f;
                        num82 = num77 / num82;
                        num79 *= num82;
                        num81 *= num82;
                        ai[2] = 3f;
                        ai[1] = num64;
                        if (Math.Abs(num81) > Math.Abs(num79) * 2f)
{
                            if (num81 > 0f)
{
                                ai[2] = 1f;
                            }
                            else
{
                                ai[2] = 5f;
                            }
                        }
                        else if (Math.Abs(num79) > Math.Abs(num81) * 2f)
{
                            ai[2] = 3f;
                        }
                        else if (num81 > 0f)
{
                            ai[2] = 2f;
                        }
                        else
{
                            ai[2] = 4f;
                        }
                    }
                }
            }
            if (ai[2] <= 0f || (flag8 && (num62 == -1 || !(ai[1] >= (float)num62) || !(ai[1] < (float)(num62 + num63)))))
            {
                float num84 = 1f;
                float num85 = 0.07f;
                float num86 = 0.8f;
                if (type == 214)
                {
                    num84 = 2f;
                    num85 = 0.09f;
                }
                else if (type == 215)
                {
                    num84 = 1.5f;
                    num85 = 0.08f;
                }
                else if (type == 381 || type == 382)
                {
                    num84 = 2f;
                    num85 = 0.5f;
                }
                else if (type == 520)
                {
                    num84 = 4f;
                    num85 = 1f;
                    num86 = 0.7f;
                }
                else if (type == 411)
                {
                    num84 = 2f;
                    num85 = 0.5f;
                }
                else if (type == 409)
                {
                    num84 = 2f;
                    num85 = 0.5f;
                }
                else if (type == 426)
                {
                    num84 = 4f;
                    num85 = 0.6f;
                    num86 = 0.95f;
                }
                bool flag14 = false;
                if ((type == 381 || type == 382) && Vector2.Distance(base.Center, Main.player[target].Center) < 300f && Collision.CanHitLine(base.Center, 0, 0, Main.player[target].Center, 0, 0))
                {
                    flag14 = true;
                    ai[3] = 0f;
                }
                if (type == 520 && Vector2.Distance(base.Center, Main.player[target].Center) < 400f && Collision.CanHitLine(base.Center, 0, 0, Main.player[target].Center, 0, 0))
                {
                    flag14 = true;
                    ai[3] = 0f;
                }
                if (velocity.X < 0f - num84 || velocity.X > num84 || flag14)
                {
                    if (velocity.Y == 0f)
                    {
                        velocity *= num86;
                    }
                }
                else if (velocity.X < num84 && direction == 1)
                {
                    velocity.X += num85;
                    if (velocity.X > num84)
                    {
                        velocity.X = num84;
                    }
                }
                else if (velocity.X > 0f - num84 && direction == -1)
                {
                    velocity.X -= num85;
                    if (velocity.X < 0f - num84)
                    {
                        velocity.X = 0f - num84;
                    }
                }
            }
            if (type == 520)
            {
                localAI[2] += 1f;
                if (localAI[2] >= 6f)
                {
                    localAI[2] = 0f;
                    localAI[3] = Main.player[target].DirectionFrom(base.Top + new Vector2(0f, 20f)).ToRotation();
                }
            }
        }
        if (type == 109 && Main.netMode != 1 && !Main.player[target].dead)
        {
            if (justHit)
            {
                ai[2] = 0f;
            }
            ai[2] += 1f;
            if (ai[2] > 60f)
            {
                Vector2 vector29 = default(Vector2);
                ((Vector2)(ref vector29))._002Ector(position.X + (float)width * 0.5f - (float)(direction * 24), position.Y + 4f);
                if (Main.rand.Next(5) != 0 || AnyNPCs(378))
                {
                    int num87 = Main.rand.Next(3, 8) * direction;
                    int num88 = Main.rand.Next(-8, -5);
                    int num90 = Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector29.X, vector29.Y, num87, num88, 75, 80, 0f, Main.myPlayer, 0f, 0f, 0f);
                    Main.projectile[num90].timeLeft = 300;
                    ai[2] = 0f;
                }
                else
                {
                    ai[2] = -120f;
                    int number = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)vector29.X, (int)vector29.Y, 378);
                    NetMessage.SendData(23, -1, -1, null, number);
                }
            }
        }
        if (velocity.Y == 0f || flag)
        {
            int num91 = (int)(position.Y + (float)height + 7f) / 16;
            int num92 = (int)(position.Y - 9f) / 16;
            int num93 = (int)position.X / 16;
            int num94 = (int)(position.X + (float)width) / 16;
            int num205 = (int)(position.X + 8f) / 16;
            int num95 = (int)(position.X + (float)width - 8f) / 16;
            bool flag15 = false;
            for (int num96 = num205; num96 <= num95; num96++)
            {
                if (num96 >= num93 && num96 <= num94 && Main.tile[num96, num91] == null)
                {
                    flag15 = true;
                    continue;
                }
                if (Main.tile[num96, num92] != null && Main.tile[num96, num92].nactive() && Main.tileSolid[Main.tile[num96, num92].type])
                {
                    flag23 = false;
                    break;
                }
                if (!flag15 && num96 >= num93 && num96 <= num94 && Main.tile[num96, num91].nactive() && Main.tileSolid[Main.tile[num96, num91].type])
                {
                    flag23 = true;
                }
            }
            if (!flag23 && velocity.Y < 0f)
            {
                velocity.Y = 0f;
            }
            if (flag15)
            {
                return;
            }
        }
        if (type == 428)
        {
            flag23 = false;
        }
        if (velocity.Y >= 0f && (type != 580 || directionY != 1))
        {
            int num97 = 0;
            if (velocity.X < 0f)
            {
                num97 = -1;
            }
            if (velocity.X > 0f)
            {
                num97 = 1;
            }
            Vector2 vector30 = position;
            vector30.X += velocity.X;
            int num98 = (int)((vector30.X + (float)(width / 2) + (float)((width / 2 + 1) * num97)) / 16f);
            int num100 = (int)((vector30.Y + (float)height - 1f) / 16f);
            if (WorldGen.InWorld(num98, num100, 4))
            {
                if (Main.tile[num98, num100] == null)
                {
                    Main.tile[num98, num100] = default(Tile);
                }
                if (Main.tile[num98, num100 - 1] == null)
                {
                    Main.tile[num98, num100 - 1] = default(Tile);
                }
                if (Main.tile[num98, num100 - 2] == null)
                {
                    Main.tile[num98, num100 - 2] = default(Tile);
                }
                if (Main.tile[num98, num100 - 3] == null)
                {
                    Main.tile[num98, num100 - 3] = default(Tile);
                }
                if (Main.tile[num98, num100 + 1] == null)
                {
                    Main.tile[num98, num100 + 1] = default(Tile);
                }
                if (Main.tile[num98 - num97, num100 - 3] == null)
                {
                    Main.tile[num98 - num97, num100 - 3] = default(Tile);
                }
                if ((float)(num98 * 16) < vector30.X + (float)width && (float)(num98 * 16 + 16) > vector30.X && ((Main.tile[num98, num100].nactive() && !Main.tile[num98, num100].topSlope() && !Main.tile[num98, num100 - 1].topSlope() && Main.tileSolid[Main.tile[num98, num100].type] && !Main.tileSolidTop[Main.tile[num98, num100].type]) || (Main.tile[num98, num100 - 1].halfBrick() && Main.tile[num98, num100 - 1].nactive())) && (!Main.tile[num98, num100 - 1].nactive() || !Main.tileSolid[Main.tile[num98, num100 - 1].type] || Main.tileSolidTop[Main.tile[num98, num100 - 1].type] || (Main.tile[num98, num100 - 1].halfBrick() && (!Main.tile[num98, num100 - 4].nactive() || !Main.tileSolid[Main.tile[num98, num100 - 4].type] || Main.tileSolidTop[Main.tile[num98, num100 - 4].type]))) && (!Main.tile[num98, num100 - 2].nactive() || !Main.tileSolid[Main.tile[num98, num100 - 2].type] || Main.tileSolidTop[Main.tile[num98, num100 - 2].type]) && (!Main.tile[num98, num100 - 3].nactive() || !Main.tileSolid[Main.tile[num98, num100 - 3].type] || Main.tileSolidTop[Main.tile[num98, num100 - 3].type]) && (!Main.tile[num98 - num97, num100 - 3].nactive() || !Main.tileSolid[Main.tile[num98 - num97, num100 - 3].type]))
                {
                    float num101 = num100 * 16;
                    if (Main.tile[num98, num100].halfBrick())
                    {
                        num101 += 8f;
                    }
                    if (Main.tile[num98, num100 - 1].halfBrick())
                    {
                        num101 -= 8f;
                    }
                    if (num101 < vector30.Y + (float)height)
                    {
                        float num102 = vector30.Y + (float)height - num101;
                        float num103 = 16.1f;
                        if (type == 163 || type == 164 || type == 236 || type == 239 || type == 530)
{
                            num103 += 8f;
                        }
                        if (num102 <= num103)
{
                            gfxOffY += position.Y + (float)height - num101;
                            position.Y = num101 - (float)height;
                            if (num102 < 9f)
{
                                stepSpeed = 1f;
                            }
                            else
{
                                stepSpeed = 2f;
                            }
                        }
                    }
                }
            }
        }
        if (flag23)
        {
            int num104 = (int)((position.X + (float)(width / 2) + (float)(15 * direction)) / 16f);
            int num105 = (int)((position.Y + (float)height - 15f) / 16f);
            if (type == 109 || type == 163 || type == 164 || type == 199 || type == 236 || type == 239 || type == 257 || type == 258 || type == 290 || type == 391 || type == 425 || type == 427 || type == 426 || type == 580 || type == 508 || type == 415 || type == 530 || type == 532 || type == 582)
            {
                num104 = (int)((position.X + (float)(width / 2) + (float)((width / 2 + 16) * direction)) / 16f);
            }
            if (Main.tile[num104, num105] == null)
            {
                Main.tile[num104, num105] = default(Tile);
            }
            if (Main.tile[num104, num105 - 1] == null)
            {
                Main.tile[num104, num105 - 1] = default(Tile);
            }
            if (Main.tile[num104, num105 - 2] == null)
            {
                Main.tile[num104, num105 - 2] = default(Tile);
            }
            if (Main.tile[num104, num105 - 3] == null)
            {
                Main.tile[num104, num105 - 3] = default(Tile);
            }
            if (Main.tile[num104, num105 + 1] == null)
            {
                Main.tile[num104, num105 + 1] = default(Tile);
            }
            if (Main.tile[num104 + direction, num105 - 1] == null)
            {
                Main.tile[num104 + direction, num105 - 1] = default(Tile);
            }
            if (Main.tile[num104 + direction, num105 + 1] == null)
            {
                Main.tile[num104 + direction, num105 + 1] = default(Tile);
            }
            if (Main.tile[num104 - direction, num105 + 1] == null)
            {
                Main.tile[num104 - direction, num105 + 1] = default(Tile);
            }
            Main.tile[num104, num105 + 1].halfBrick();
            if (Main.tile[num104, num105 - 1].nactive() && (TileLoader.IsClosedDoor(Main.tile[num104, num105 - 1]) || Main.tile[num104, num105 - 1].type == 388) && flag26)
            {
                ai[2] += 1f;
                ai[3] = 0f;
                if (ai[2] >= 60f)
                {
                    bool flag16 = type == 3 || type == 430 || type == 590 || type == 331 || type == 332 || type == 132 || type == 161 || type == 186 || type == 187 || type == 188 || type == 189 || type == 200 || type == 223 || type == 320 || type == 321 || type == 319 || type == 21 || type == 324 || type == 323 || type == 322 || type == 44 || type == 196 || type == 167 || type == 77 || type == 197 || type == 202 || type == 203 || type == 449 || type == 450 || type == 451 || type == 452 || type == 481 || type == 201 || type == 635;
                    bool flag17 = Main.player[target].ZoneGraveyard && Main.rand.Next(60) == 0;
                    if ((!Main.bloodMoon || Main.getGoodWorld) && !flag17 && flag16)
                    {
                        ai[1] = 0f;
                    }
                    velocity.X = 0.5f * (float)(-direction);
                    int num106 = 5;
                    if (Main.tile[num104, num105 - 1].type == 388)
                    {
                        num106 = 2;
                    }
                    ai[1] += num106;
                    if (type == 27)
                    {
                        ai[1] += 1f;
                    }
                    if (type == 31 || type == 294 || type == 295 || type == 296)
                    {
                        ai[1] += 6f;
                    }
                    ai[2] = 0f;
                    bool flag18 = false;
                    if (ai[1] >= 10f)
                    {
                        flag18 = true;
                        ai[1] = 10f;
                    }
                    if (type == 460)
                    {
                        flag18 = true;
                    }
                    WorldGen.KillTile(num104, num105 - 1, fail: true);
                    if ((Main.netMode != 1 || !flag18) && flag18 && Main.netMode != 1)
                    {
                        if (type == 26)
{
                            WorldGen.KillTile(num104, num105 - 1);
                            if (Main.netMode == 2)
{
                                NetMessage.SendData(17, -1, -1, null, 0, num104, num105 - 1);
                            }
                        }
                        else
{
                            if (TileLoader.IsClosedDoor(Main.tile[num104, num105 - 1]))
{
                                bool flag19 = WorldGen.OpenDoor(num104, num105 - 1, direction);
                                if (!flag19)
{
                                    ai[3] = num154;
                                    netUpdate = true;
                                }
                                if (Main.netMode == 2 && flag19)
{
                                    NetMessage.SendData(19, -1, -1, null, 0, num104, num105 - 1, direction);
                                }
                            }
                            if (Main.tile[num104, num105 - 1].type == 388)
{
                                bool flag20 = WorldGen.ShiftTallGate(num104, num105 - 1, closing: false);
                                if (!flag20)
{
                                    ai[3] = num154;
                                    netUpdate = true;
                                }
                                if (Main.netMode == 2 && flag20)
{
                                    NetMessage.SendData(19, -1, -1, null, 4, num104, num105 - 1);
                                }
                            }
                        }
                    }
                }
            }
            else
            {
                int num107 = spriteDirection;
                if (type == 425)
                {
                    num107 *= -1;
                }
                if ((velocity.X < 0f && num107 == -1) || (velocity.X > 0f && num107 == 1))
                {
                    if (height >= 32 && Main.tile[num104, num105 - 2].nactive() && Main.tileSolid[Main.tile[num104, num105 - 2].type])
                    {
                        if (Main.tile[num104, num105 - 3].nactive() && Main.tileSolid[Main.tile[num104, num105 - 3].type])
{
                            velocity.Y = -8f;
                            netUpdate = true;
                        }
                        else
{
                            velocity.Y = -7f;
                            netUpdate = true;
                        }
                    }
                    else if (Main.tile[num104, num105 - 1].nactive() && Main.tileSolid[Main.tile[num104, num105 - 1].type])
                    {
                        if (type == 624)
{
                            velocity.Y = -8f;
                            int num108 = (int)(position.Y + (float)height) / 16;
                            if (WorldGen.SolidTile((int)base.Center.X / 16, num108 - 8))
{
                                direction *= -1;
                                spriteDirection = direction;
                                velocity.X = 3 * direction;
                            }
                        }
                        else
{
                            velocity.Y = -6f;
                        }
                        netUpdate = true;
                    }
                    else if (position.Y + (float)height - (float)(num105 * 16) > 20f && Main.tile[num104, num105].nactive() && !Main.tile[num104, num105].topSlope() && Main.tileSolid[Main.tile[num104, num105].type])
                    {
                        velocity.Y = -5f;
                        netUpdate = true;
                    }
                    else if (directionY < 0 && type != 67 && (!Main.tile[num104, num105 + 1].nactive() || !Main.tileSolid[Main.tile[num104, num105 + 1].type]) && (!Main.tile[num104 + direction, num105 + 1].nactive() || !Main.tileSolid[Main.tile[num104 + direction, num105 + 1].type]))
                    {
                        velocity.Y = -8f;
                        velocity.X *= 1.5f;
                        netUpdate = true;
                    }
                    else if (flag26)
                    {
                        ai[1] = 0f;
                        ai[2] = 0f;
                    }
                    if (velocity.Y == 0f && flag24 && ai[3] == 1f)
                    {
                        velocity.Y = -5f;
                    }
                    if (velocity.Y == 0f && (Main.expertMode || type == 586) && Main.player[target].Bottom.Y < base.Top.Y && Math.Abs(base.Center.X - Main.player[target].Center.X) < (float)(Main.player[target].width * 3) && Collision.CanHit(this, Main.player[target]))
                    {
                        if (type == 586)
{
                            int num109 = (int)((base.Bottom.Y - 16f - Main.player[target].Bottom.Y) / 16f);
                            if (num109 < 14 && Collision.CanHit(this, Main.player[target]))
{
                                if (num109 < 7)
{
                                    velocity.Y = -8.8f;
                                }
                                else if (num109 < 8)
{
                                    velocity.Y = -9.2f;
                                }
                                else if (num109 < 9)
{
                                    velocity.Y = -9.7f;
                                }
                                else if (num109 < 10)
{
                                    velocity.Y = -10.3f;
                                }
                                else if (num109 < 11)
{
                                    velocity.Y = -10.6f;
                                }
                                else
{
                                    velocity.Y = -11f;
                                }
                            }
                        }
                        if (velocity.Y == 0f)
{
                            int num112 = 6;
                            if (Main.player[target].Bottom.Y > base.Top.Y - (float)(num112 * 16))
{
                                velocity.Y = -7.9f;
                            }
                            else
{
                                int num113 = (int)(base.Center.X / 16f);
                                int num114 = (int)(base.Bottom.Y / 16f) - 1;
                                for (int num115 = num114; num115 > num114 - num112; num115--)
{
                                    if (Main.tile[num113, num115].nactive() && TileID.Sets.Platforms[Main.tile[num113, num115].type])
{
                                        velocity.Y = -7.9f;
                                        break;
                                    }
                                }
                            }
                        }
                    }
                }
                if ((type == 31 || type == 294 || type == 295 || type == 296 || type == 47 || type == 77 || type == 104 || type == 168 || type == 196 || type == 385 || type == 389 || type == 464 || type == 470 || (type >= 524 && type <= 527)) && velocity.Y == 0f)
                {
                    int num116 = 100;
                    int num117 = 50;
                    if (type == 586)
                    {
                        num116 = 150;
                        num117 = 150;
                    }
                    if (Math.Abs(position.X + (float)(width / 2) - (Main.player[target].position.X + (float)(Main.player[target].width / 2))) < (float)num116 && Math.Abs(position.Y + (float)(height / 2) - (Main.player[target].position.Y + (float)(Main.player[target].height / 2))) < (float)num117 && ((direction > 0 && velocity.X >= 1f) || (direction < 0 && velocity.X <= -1f)))
                    {
                        if (type == 586)
{
                            velocity.X += direction;
                            velocity.X *= 2f;
                            if (velocity.X > 8f)
{
                                velocity.X = 8f;
                            }
                            if (velocity.X < -8f)
{
                                velocity.X = -8f;
                            }
                            velocity.Y = -4.5f;
                            if (position.Y > Main.player[target].position.Y + 40f)
{
                                velocity.Y -= 2f;
                            }
                            if (position.Y > Main.player[target].position.Y + 80f)
{
                                velocity.Y -= 2f;
                            }
                            if (position.Y > Main.player[target].position.Y + 120f)
{
                                velocity.Y -= 2f;
                            }
                        }
                        else
{
                            velocity.X *= 2f;
                            if (velocity.X > 3f)
{
                                velocity.X = 3f;
                            }
                            if (velocity.X < -3f)
{
                                velocity.X = -3f;
                            }
                            velocity.Y = -4f;
                        }
                        netUpdate = true;
                    }
                }
                if (type == 120 && velocity.Y < 0f)
                {
                    velocity.Y *= 1.1f;
                }
                if (type == 287 && velocity.Y == 0f && Math.Abs(position.X + (float)(width / 2) - (Main.player[target].position.X + (float)(Main.player[target].width / 2))) < 150f && Math.Abs(position.Y + (float)(height / 2) - (Main.player[target].position.Y + (float)(Main.player[target].height / 2))) < 50f && ((direction > 0 && velocity.X >= 1f) || (direction < 0 && velocity.X <= -1f)))
                {
                    velocity.X = 8 * direction;
                    velocity.Y = -4f;
                    netUpdate = true;
                }
                if (type == 287 && velocity.Y < 0f)
                {
                    velocity.X *= 1.2f;
                    velocity.Y *= 1.1f;
                }
                if (type == 460 && velocity.Y < 0f)
                {
                    velocity.X *= 1.3f;
                    velocity.Y *= 1.1f;
                }
            }
        }
        else if (flag26)
        {
            ai[1] = 0f;
            ai[2] = 0f;
        }
        if (Main.netMode != 1 && type == 120 && ai[3] >= (float)num154)
        {
            int targetTileX = (int)Main.player[target].Center.X / 16;
            int targetTileY = (int)Main.player[target].Center.Y / 16;
            Vector2 chosenTile = Vector2.Zero;
            if (AI_AttemptToFindTeleportSpot(ref chosenTile, targetTileX, targetTileY, 20, 9))
            {
                position.X = chosenTile.X * 16f - (float)(width / 2);
                position.Y = chosenTile.Y * 16f - (float)height;
                ai[3] = -120f;
                netUpdate = true;
            }
        }
    }
References Terraria.Entity.active, Terraria.Lighting.AddLight(), Terraria.NPC.ai, Terraria.NPC.AI_003_Gnomes_ShouldTurnToStone(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.NPC.alpha, Terraria.NPC.AnyNPCs(), Terraria.Main.BestiaryTracker, Terraria.Main.bloodMoon, Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.TileObject.CanPlace(), Terraria.Entity.Center, Terraria.NPC.collideX, Terraria.NPC.confused, Terraria.NPC.CountKillForBannersAndDropThem(), Terraria.NPC.CountNPCS(), Terraria.NPC.damage, Terraria.NPC.defDamage, Terraria.NPC.defDefense, Terraria.NPC.defense, Terraria.NPC.DespawnEncouragement_AIStyle3_Fighters_CanBeBusyWithAction(), Terraria.NPC.DespawnEncouragement_AIStyle3_Fighters_NotDiscouraged(), Terraria.Entity.direction, Terraria.Entity.DirectionFrom(), Terraria.Entity.DirectionTo(), Terraria.NPC.directionY, Terraria.Entity.Distance(), Terraria.NPC.dontTakeDamage, Terraria.Main.dust, Terraria.Main.eclipse, Terraria.NPC.EncourageDespawn(), Terraria.Main.expertMode, Terraria.Utils.FactorAcceleration(), Terraria.Main.GameModeInfo, Terraria.NPC.GetAttackDamage_ForProjectiles(), Terraria.Utils.GetChaseResults(), Terraria.Main.getGoodWorld, Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.Framing.GetTileSafely(), Terraria.NPC.gfxOffY, Terraria.NPC.gravity, Terraria.Entity.height, Terraria.NPC.hide, Terraria.Entity.Hitbox, Terraria.WorldGen.InWorld(), Terraria.ModLoader.TileLoader.IsClosedDoor(), Terraria.Main.IsItDay(), Terraria.NPC.IsNPCValidForBestiaryKillCredit(), Terraria.ID.SoundID.Item8, Terraria.NPC.justHit, Terraria.WorldGen.KillTile(), Terraria.NPC.knockBackResist, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netOffset, Terraria.NPC.netUpdate, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.NPC.noGravity, Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.NPC.noTileCollide, Terraria.Main.npc, Terraria.NPC.NPCCanStickToWalls(), Terraria.NPC.oldPos, Terraria.Entity.oldPosition, Terraria.Entity.oldVelocity, Terraria.WorldGen.OpenDoor(), Terraria.WorldGen.PlaceTile(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Utils.RandomVector2(), Terraria.NPC.reflectsProjectiles, Terraria.Main.remixWorld, Terraria.NPC.rotation, Terraria.NPC.scale, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.ShiftTallGate(), Terraria.NPC.shimmerTransparency, Terraria.Collision.SolidCollision(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.Collision.SolidTiles(), Terraria.NPC.spriteDirection, Terraria.NPC.stepSpeed, Terraria.NPC.takenDamageMultiplier, Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.NPC.Transform(), Terraria.NPC.type, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Entity.whoAmI, Terraria.Entity.width, and Terraria.Main.worldSurface.
Referenced by Terraria.NPC.VanillaAI_Inner().