TModLoader: Terraria.NPC.TryTeleportingCaughtMysticFrog
TryTeleportingCaughtMysticFrog()
bool Terraria.NPC.TryTeleportingCaughtMysticFrog () inline private
    {
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode == 1)
        {
            return false;
        }
        if (type != 687)
        {
            return false;
        }
        Vector2 chosenTile = Vector2.Zero;
        Point point = base.Center.ToTileCoordinates();
        if (AI_AttemptToFindTeleportSpot(ref chosenTile, point.X, point.Y, 15, 8))
        {
            Vector2 newPos = default(Vector2);
            ((Vector2)(ref newPos))._002Ector(chosenTile.X * 16f - (float)(width / 2), chosenTile.Y * 16f - (float)height);
            NetMessage.SendData(23, -1, -1, null, whoAmI);
            Teleport(newPos, 13);
            return true;
        }
        Vector2 vector = base.Center - new Vector2(20f);
        Utils.PoofOfSmoke(vector);
        active = false;
        NetMessage.SendData(23, -1, -1, null, whoAmI);
        NetMessage.SendData(106, -1, -1, null, (int)vector.X, vector.Y);
        return false;
    }
References Terraria.Main.netMode, Terraria.Utils.PoofOfSmoke(), and Terraria.NetMessage.SendData().
Referenced by Terraria.NPC.CatchNPC().