TModLoader: Terraria.NPC.AI_120_HallowBoss
AI_120_HallowBoss()
void Terraria.NPC.AI_120_HallowBoss () inline private
    {
        //IL_0d42: Unknown result type (might be due to invalid IL or missing references)
        //IL_1427: Unknown result type (might be due to invalid IL or missing references)
        //IL_142c: Unknown result type (might be due to invalid IL or missing references)
        //IL_142e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1433: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a82: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a84: Unknown result type (might be due to invalid IL or missing references)
        //IL_23f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_122d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1232: Unknown result type (might be due to invalid IL or missing references)
        //IL_1234: Unknown result type (might be due to invalid IL or missing references)
        //IL_1239: Unknown result type (might be due to invalid IL or missing references)
        //IL_11fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1451: Unknown result type (might be due to invalid IL or missing references)
        //IL_1449: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1df2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dcf: Unknown result type (might be due to invalid IL or missing references)
        //IL_2206: Unknown result type (might be due to invalid IL or missing references)
        //IL_2210: Unknown result type (might be due to invalid IL or missing references)
        //IL_2215: Unknown result type (might be due to invalid IL or missing references)
        //IL_21de: Unknown result type (might be due to invalid IL or missing references)
        //IL_21fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_21ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_2437: Unknown result type (might be due to invalid IL or missing references)
        //IL_2441: Unknown result type (might be due to invalid IL or missing references)
        //IL_2446: Unknown result type (might be due to invalid IL or missing references)
        //IL_240f: Unknown result type (might be due to invalid IL or missing references)
        //IL_242b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2430: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0290: Unknown result type (might be due to invalid IL or missing references)
        //IL_0238: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a00: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c62: Unknown result type (might be due to invalid IL or missing references)
        //IL_124c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1251: Unknown result type (might be due to invalid IL or missing references)
        //IL_1253: Unknown result type (might be due to invalid IL or missing references)
        //IL_1456: Unknown result type (might be due to invalid IL or missing references)
        //IL_1459: Unknown result type (might be due to invalid IL or missing references)
        //IL_145b: Unknown result type (might be due to invalid IL or missing references)
        //IL_145d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1638: Unknown result type (might be due to invalid IL or missing references)
        //IL_1630: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a05: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a08: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c75: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c84: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dde: Unknown result type (might be due to invalid IL or missing references)
        //IL_1292: Unknown result type (might be due to invalid IL or missing references)
        //IL_128a: Unknown result type (might be due to invalid IL or missing references)
        //IL_146d: Unknown result type (might be due to invalid IL or missing references)
        //IL_146f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1471: Unknown result type (might be due to invalid IL or missing references)
        //IL_1476: Unknown result type (might be due to invalid IL or missing references)
        //IL_147b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1480: Unknown result type (might be due to invalid IL or missing references)
        //IL_1487: Unknown result type (might be due to invalid IL or missing references)
        //IL_1491: Unknown result type (might be due to invalid IL or missing references)
        //IL_163d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1640: Unknown result type (might be due to invalid IL or missing references)
        //IL_1642: Unknown result type (might be due to invalid IL or missing references)
        //IL_1643: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cdb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ce0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ea7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e54: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e63: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e68: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ccd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e25: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e28: Unknown result type (might be due to invalid IL or missing references)
        //IL_1297: Unknown result type (might be due to invalid IL or missing references)
        //IL_129a: Unknown result type (might be due to invalid IL or missing references)
        //IL_129c: Unknown result type (might be due to invalid IL or missing references)
        //IL_129d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1653: Unknown result type (might be due to invalid IL or missing references)
        //IL_1655: Unknown result type (might be due to invalid IL or missing references)
        //IL_1656: Unknown result type (might be due to invalid IL or missing references)
        //IL_165b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1660: Unknown result type (might be due to invalid IL or missing references)
        //IL_1665: Unknown result type (might be due to invalid IL or missing references)
        //IL_166c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1676: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1eac: Unknown result type (might be due to invalid IL or missing references)
        //IL_1eaf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1eb1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1eb2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2246: Unknown result type (might be due to invalid IL or missing references)
        //IL_224b: Unknown result type (might be due to invalid IL or missing references)
        //IL_224d: Unknown result type (might be due to invalid IL or missing references)
        //IL_24ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_064d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0657: Unknown result type (might be due to invalid IL or missing references)
        //IL_065c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a56: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a58: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e38: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e40: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e45: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e51: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_12af: Unknown result type (might be due to invalid IL or missing references)
        //IL_12b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_12b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_12bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_12c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ec2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ec4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ec5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1eca: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ecf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ed4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1edb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_0338: Unknown result type (might be due to invalid IL or missing references)
        //IL_033b: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0373: Unknown result type (might be due to invalid IL or missing references)
        //IL_0397: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_041f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0424: Unknown result type (might be due to invalid IL or missing references)
        //IL_042e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0433: Unknown result type (might be due to invalid IL or missing references)
        //IL_0438: Unknown result type (might be due to invalid IL or missing references)
        //IL_0637: Unknown result type (might be due to invalid IL or missing references)
        //IL_0641: Unknown result type (might be due to invalid IL or missing references)
        //IL_0646: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0603: Unknown result type (might be due to invalid IL or missing references)
        //IL_0606: Unknown result type (might be due to invalid IL or missing references)
        //IL_05dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_16ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_16f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_16f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_16f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c24: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c29: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1be2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d38: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d47: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_22c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_22d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_22d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_22d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_22dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_22de: Unknown result type (might be due to invalid IL or missing references)
        //IL_22e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2802: Unknown result type (might be due to invalid IL or missing references)
        //IL_2807: Unknown result type (might be due to invalid IL or missing references)
        //IL_2812: Unknown result type (might be due to invalid IL or missing references)
        //IL_0497: Unknown result type (might be due to invalid IL or missing references)
        //IL_049c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1709: Unknown result type (might be due to invalid IL or missing references)
        //IL_170e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1710: Unknown result type (might be due to invalid IL or missing references)
        //IL_1715: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bf8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c02: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c07: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b33: Unknown result type (might be due to invalid IL or missing references)
        //IL_22f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_22f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_22f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_22fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_253b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2540: Unknown result type (might be due to invalid IL or missing references)
        //IL_2543: Unknown result type (might be due to invalid IL or missing references)
        //IL_2549: Unknown result type (might be due to invalid IL or missing references)
        //IL_2553: Unknown result type (might be due to invalid IL or missing references)
        //IL_2558: Unknown result type (might be due to invalid IL or missing references)
        //IL_257d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2594: Unknown result type (might be due to invalid IL or missing references)
        //IL_25ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_25b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_25b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_25c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_25d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_25de: Unknown result type (might be due to invalid IL or missing references)
        //IL_2643: Unknown result type (might be due to invalid IL or missing references)
        //IL_2648: Unknown result type (might be due to invalid IL or missing references)
        //IL_2652: Unknown result type (might be due to invalid IL or missing references)
        //IL_2657: Unknown result type (might be due to invalid IL or missing references)
        //IL_265c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ada: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b53: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b58: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b63: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b68: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_26bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_26c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b17: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1317: Unknown result type (might be due to invalid IL or missing references)
        //IL_1330: Unknown result type (might be due to invalid IL or missing references)
        //IL_1336: Unknown result type (might be due to invalid IL or missing references)
        //IL_1338: Unknown result type (might be due to invalid IL or missing references)
        //IL_133d: Unknown result type (might be due to invalid IL or missing references)
        //IL_177c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1791: Unknown result type (might be due to invalid IL or missing references)
        //IL_1798: Unknown result type (might be due to invalid IL or missing references)
        //IL_179d: Unknown result type (might be due to invalid IL or missing references)
        //IL_17a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_17b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_17b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_17be: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_17dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_17e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_17f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_17f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_17fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1802: Unknown result type (might be due to invalid IL or missing references)
        //IL_1814: Unknown result type (might be due to invalid IL or missing references)
        //IL_181b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1822: Unknown result type (might be due to invalid IL or missing references)
        //IL_1827: Unknown result type (might be due to invalid IL or missing references)
        //IL_182c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1855: Unknown result type (might be due to invalid IL or missing references)
        //IL_1870: Unknown result type (might be due to invalid IL or missing references)
        //IL_1877: Unknown result type (might be due to invalid IL or missing references)
        //IL_187c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1881: Unknown result type (might be due to invalid IL or missing references)
        //IL_18b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_18bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_18c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_18ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_18cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_18d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_18e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_18eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_18f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_18f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_18f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_190e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1915: Unknown result type (might be due to invalid IL or missing references)
        //IL_191a: Unknown result type (might be due to invalid IL or missing references)
        //IL_191f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1938: Unknown result type (might be due to invalid IL or missing references)
        //IL_193c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1941: Unknown result type (might be due to invalid IL or missing references)
        //IL_1946: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b95: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ba4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f16: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f20: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f22: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f24: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f29: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f42: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f45: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ece: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed5: Unknown result type (might be due to invalid IL or missing references)
        //IL_134d: Unknown result type (might be due to invalid IL or missing references)
        //IL_134f: Unknown result type (might be due to invalid IL or missing references)
        //IL_135c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1362: Unknown result type (might be due to invalid IL or missing references)
        //IL_1364: Unknown result type (might be due to invalid IL or missing references)
        //IL_136e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1373: Unknown result type (might be due to invalid IL or missing references)
        //IL_1378: Unknown result type (might be due to invalid IL or missing references)
        //IL_137f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f66: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f70: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f72: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f76: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f80: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f82: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f84: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1554: Unknown result type (might be due to invalid IL or missing references)
        //IL_1556: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fc3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fc5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fca: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f91: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f93: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f98: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_235c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2361: Unknown result type (might be due to invalid IL or missing references)
        //IL_2363: Unknown result type (might be due to invalid IL or missing references)
        //IL_2368: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f20: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f23: Unknown result type (might be due to invalid IL or missing references)
        //IL_1954: Unknown result type (might be due to invalid IL or missing references)
        //IL_1956: Unknown result type (might be due to invalid IL or missing references)
        //IL_1960: Unknown result type (might be due to invalid IL or missing references)
        //IL_1965: Unknown result type (might be due to invalid IL or missing references)
        //IL_196a: Unknown result type (might be due to invalid IL or missing references)
        //IL_196c: Unknown result type (might be due to invalid IL or missing references)
        //IL_196e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fda: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fdc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ff2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fac: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fae: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fb7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fbc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fa8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1faa: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f36: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f40: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f45: Unknown result type (might be due to invalid IL or missing references)
        //IL_1976: Unknown result type (might be due to invalid IL or missing references)
        //IL_1980: Unknown result type (might be due to invalid IL or missing references)
        //IL_1987: Unknown result type (might be due to invalid IL or missing references)
        //IL_198c: Unknown result type (might be due to invalid IL or missing references)
        //IL_198e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1992: Unknown result type (might be due to invalid IL or missing references)
        //IL_1997: Unknown result type (might be due to invalid IL or missing references)
        //IL_1999: Unknown result type (might be due to invalid IL or missing references)
        //IL_199e: Unknown result type (might be due to invalid IL or missing references)
        //IL_19a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_19a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_19a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_19ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_19b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_19b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_19bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f65: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f71: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f76: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f86: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f53: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_19d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_19d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_19e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0feb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0911: Unknown result type (might be due to invalid IL or missing references)
        //IL_0916: Unknown result type (might be due to invalid IL or missing references)
        //IL_091b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0920: Unknown result type (might be due to invalid IL or missing references)
        //IL_092c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0937: Unknown result type (might be due to invalid IL or missing references)
        //IL_094d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0953: Unknown result type (might be due to invalid IL or missing references)
        //IL_0955: Unknown result type (might be due to invalid IL or missing references)
        //IL_095f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0964: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fcd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fcf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fcb: Unknown result type (might be due to invalid IL or missing references)
        //IL_205a: Unknown result type (might be due to invalid IL or missing references)
        //IL_205f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2064: Unknown result type (might be due to invalid IL or missing references)
        //IL_2066: Unknown result type (might be due to invalid IL or missing references)
        //IL_2068: Unknown result type (might be due to invalid IL or missing references)
        //IL_206d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2072: Unknown result type (might be due to invalid IL or missing references)
        //IL_2081: Unknown result type (might be due to invalid IL or missing references)
        //IL_2086: Unknown result type (might be due to invalid IL or missing references)
        //IL_208c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2090: Unknown result type (might be due to invalid IL or missing references)
        //IL_2098: Unknown result type (might be due to invalid IL or missing references)
        //IL_209d: Unknown result type (might be due to invalid IL or missing references)
        //IL_20a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_20a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_20a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_20ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_20b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_20b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_20b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_20f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_20f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_20fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2104: Unknown result type (might be due to invalid IL or missing references)
        //IL_2106: Unknown result type (might be due to invalid IL or missing references)
        //IL_211c: Unknown result type (might be due to invalid IL or missing references)
        //IL_20c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_20c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_20c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_20ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_20cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_20ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_20de: Unknown result type (might be due to invalid IL or missing references)
        //IL_20e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_20e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_20e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_20ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_20f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_20da: Unknown result type (might be due to invalid IL or missing references)
        //IL_20dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_107b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1080: Unknown result type (might be due to invalid IL or missing references)
        //IL_1084: Unknown result type (might be due to invalid IL or missing references)
        //IL_1089: Unknown result type (might be due to invalid IL or missing references)
        //IL_108e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1093: Unknown result type (might be due to invalid IL or missing references)
        //IL_10af: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_10bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_10cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_10d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_10d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_10e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_10e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_10eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_112e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1130: Unknown result type (might be due to invalid IL or missing references)
        //IL_1135: Unknown result type (might be due to invalid IL or missing references)
        //IL_113d: Unknown result type (might be due to invalid IL or missing references)
        //IL_113f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1155: Unknown result type (might be due to invalid IL or missing references)
        //IL_10fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_10fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_10fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1103: Unknown result type (might be due to invalid IL or missing references)
        //IL_1105: Unknown result type (might be due to invalid IL or missing references)
        //IL_1107: Unknown result type (might be due to invalid IL or missing references)
        //IL_1117: Unknown result type (might be due to invalid IL or missing references)
        //IL_1119: Unknown result type (might be due to invalid IL or missing references)
        //IL_111b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1122: Unknown result type (might be due to invalid IL or missing references)
        //IL_1127: Unknown result type (might be due to invalid IL or missing references)
        //IL_112c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1113: Unknown result type (might be due to invalid IL or missing references)
        //IL_1115: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(-150f, -250f);
        Vector2 vector10 = default(Vector2);
        ((Vector2)(ref vector10))._002Ector(150f, -250f);
        Vector2 vector21 = default(Vector2);
        ((Vector2)(ref vector21))._002Ector(0f, -350f);
        Vector2 vector29 = default(Vector2);
        ((Vector2)(ref vector29))._002Ector(0f, -350f);
        Vector2 vector30 = default(Vector2);
        ((Vector2)(ref vector30))._002Ector(-80f, -500f);
        float num = 0.5f;
        float num12 = 12f;
        float num23 = 40f;
        float num34 = 6400f;
        int num45 = 40;
        int num56 = 50;
        int num67 = 70;
        int num78 = 45;
        int num88 = 45;
        int num2 = 50;
        bool flag = AI_120_HallowBoss_IsInPhase2();
        bool flag5 = Main.expertMode;
        bool flag6 = flag && flag5;
        bool flag7 = ShouldEmpressBeEnraged();
        if (life == lifeMax && flag7 && !AI_120_HallowBoss_IsGenuinelyEnraged())
        {
            this.ai[3] += 2f;
        }
        bool flag8 = true;
        int num3 = 30;
        int num4 = 30;
        int num5 = 30;
        int num6 = 35;
        int num7 = 65;
        if (flag)
        {
            num56 = 60;
            num78 = 50;
            num88 = 50;
            num2 = 60;
            num67 = 65;
            num3 = 35;
            num4 = 35;
            num5 = 35;
            num6 = 40;
            num7 = 30;
        }
        num56 = GetAttackDamage_ForProjectiles(num56, num3);
        num78 = GetAttackDamage_ForProjectiles(num78, num4);
        num88 = GetAttackDamage_ForProjectiles(num88, num5);
        num2 = GetAttackDamage_ForProjectiles(num2, num6);
        num67 = GetAttackDamage_ForProjectiles(num67, num7);
        if (flag7)
        {
            num56 = 9999;
            num78 = 9999;
            num88 = 9999;
            num2 = 9999;
            num67 = 9999;
            flag5 = true;
        }
        float num8 = (flag5 ? 0.3f : 1f);
        bool flag9 = true;
        int num9 = 0;
        if (flag)
        {
            num9 += 15;
        }
        if (flag5)
        {
            num9 += 5;
        }
        Vector2 val = default(Vector2);
        switch ((int)this.ai[0])
        {
        case 0:
            if (this.ai[1] == 0f)
            {
                velocity = new Vector2(0f, 5f);
                if (Main.netMode != 1)
                {
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center + new Vector2(0f, -80f), Vector2.Zero, 874, 0, 0f, Main.myPlayer);
                }
            }
            if (this.ai[1] == 10f)
            {
                SoundEngine.PlaySound(in SoundID.Item161, base.Center);
            }
            velocity *= 0.95f;
            if (this.ai[1] > 10f && this.ai[1] < 150f)
            {
                int num64 = 2;
                for (int m = 0; m < num64; m++)
                {
                    float num65 = MathHelper.Lerp(1.3f, 0.7f, Opacity) * Utils.GetLerpValue(0f, 120f, this.ai[1], clamped: true);
                    Color newColor2 = Main.hslToRgb(this.ai[1] / 180f, 1f, 0.5f);
                    int num66 = Dust.NewDust(position, width, height, 267, 0f, 0f, 0, newColor2);
                    Main.dust[num66].position = base.Center + Main.rand.NextVector2Circular((float)width * 3f, (float)height * 3f) + new Vector2(0f, -150f);
                    Dust obj3 = Main.dust[num66];
                    obj3.velocity *= Main.rand.NextFloat() * 0.8f;
                    Main.dust[num66].noGravity = true;
                    Main.dust[num66].fadeIn = 0.6f + Main.rand.NextFloat() * 0.7f * num65;
                    Dust obj4 = Main.dust[num66];
                    obj4.velocity += Vector2.UnitY * 3f;
                    Main.dust[num66].scale = 0.35f;
                    if (num66 != 6000)
                    {
                        Dust dust2 = Dust.CloneDust(num66);
                        dust2.scale /= 2f;
                        dust2.fadeIn *= 0.85f;
                        dust2.color = new Color(255, 255, 255, 255);
                    }
                }
            }
            this.ai[1] += 1f;
            flag8 = false;
            flag9 = false;
            Opacity = MathHelper.Clamp(this.ai[1] / 180f, 0f, 1f);
            if (this.ai[1] >= 180f)
            {
                if (flag7 && !AI_120_HallowBoss_IsGenuinelyEnraged())
                {
                    this.ai[3] += 2f;
                }
                this.ai[0] = 1f;
                this.ai[1] = 0f;
                netUpdate = true;
                TargetClosest();
            }
            break;
        case 1:
        {
            float num28 = (flag ? 20f : 45f);
            if (Main.getGoodWorld)
            {
                num28 /= 2f;
            }
            if (this.ai[1] <= 10f)
            {
                if (this.ai[1] == 0f)
                {
                    TargetClosest();
                }
                NPCAimedTarget targetData6 = GetTargetData();
                if (targetData6.Invalid)
                {
                    this.ai[0] = 13f;
                    this.ai[1] = 0f;
                    this.ai[2] += 1f;
                    velocity /= 4f;
                    netUpdate = true;
                    break;
                }
                Vector2 center = targetData6.Center;
                AI_120_HallowBoss_DashTo(center);
                netUpdate = true;
            }
            if (((Vector2)(ref velocity)).Length() > 16f && this.ai[1] > 10f)
            {
                velocity /= 2f;
            }
            velocity *= 0.92f;
            this.ai[1] += 1f;
            if (!(this.ai[1] >= num28))
            {
                break;
            }
            int num29 = (int)this.ai[2];
            int num30 = 2;
            int num31 = 0;
            if (!flag)
            {
                int num32 = num31++;
                int num33 = num31++;
                int num35 = num31++;
                int num36 = num31++;
                int num37 = num31++;
                int num38 = num31++;
                int num39 = num31++;
                int num40 = num31++;
                int num41 = num31++;
                int num42 = num31++;
                if (num29 % num31 == num32)
                {
                    num30 = 2;
                }
                if (num29 % num31 == num33)
                {
                    num30 = 8;
                }
                if (num29 % num31 == num35)
                {
                    num30 = 6;
                }
                if (num29 % num31 == num36)
                {
                    num30 = 8;
                }
                if (num29 % num31 == num37)
                {
                    num30 = 5;
                }
                if (num29 % num31 == num38)
                {
                    num30 = 2;
                }
                if (num29 % num31 == num39)
                {
                    num30 = 8;
                }
                if (num29 % num31 == num40)
                {
                    num30 = 4;
                }
                if (num29 % num31 == num41)
                {
                    num30 = 8;
                }
                if (num29 % num31 == num42)
                {
                    num30 = 5;
                }
                if ((float)life / (float)lifeMax <= 0.5f)
                {
                    num30 = 10;
                }
            }
            if (flag)
            {
                int num43 = num31++;
                int num44 = num31++;
                int num46 = num31++;
                int num47 = -1;
                if (flag5)
                {
                    num47 = num31++;
                }
                int num48 = num31++;
                int num49 = num31++;
                int num50 = num31++;
                int num51 = num31++;
                int num52 = num31++;
                int num53 = num31++;
                if (num29 % num31 == num43)
                {
                    num30 = 7;
                }
                if (num29 % num31 == num44)
                {
                    num30 = 2;
                }
                if (num29 % num31 == num46)
                {
                    num30 = 8;
                }
                if (num29 % num31 == num48)
                {
                    num30 = 5;
                }
                if (num29 % num31 == num49)
                {
                    num30 = 2;
                }
                if (num29 % num31 == num50)
                {
                    num30 = 6;
                }
                if (num29 % num31 == num50)
                {
                    num30 = 6;
                }
                if (num29 % num31 == num51)
                {
                    num30 = 4;
                }
                if (num29 % num31 == num52)
                {
                    num30 = 8;
                }
                if (num29 % num31 == num47)
                {
                    num30 = 11;
                }
                if (num29 % num31 == num53)
                {
                    num30 = 12;
                }
            }
            TargetClosest();
            NPCAimedTarget targetData7 = GetTargetData();
            bool flag4 = false;
            if (AI_120_HallowBoss_IsGenuinelyEnraged())
            {
                if (!Main.dayTime)
                {
                    flag4 = true;
                }
                if (Main.dayTime && Main.time >= 53400.0)
                {
                    flag4 = true;
                }
            }
            if (targetData7.Invalid || Distance(targetData7.Center) > num34 || flag4)
            {
                num30 = 13;
            }
            if (num30 == 8 && targetData7.Center.X > base.Center.X)
            {
                num30 = 9;
            }
            if (flag5 && num30 != 5 && num30 != 12)
            {
                Vector2 spinningpoint2 = DirectionFrom(targetData7.Center).SafeNormalize(Vector2.Zero);
                double radians2 = (float)Math.PI / 2f * (float)(targetData7.Center.X > base.Center.X).ToDirectionInt();
                val = default(Vector2);
                velocity = spinningpoint2.RotatedBy(radians2, val) * 20f;
            }
            this.ai[0] = num30;
            this.ai[1] = 0f;
            this.ai[2] += 1f;
            netUpdate = true;
            break;
        }
        case 2:
        {
            if (this.ai[1] == 0f)
            {
                SoundEngine.PlaySound(in SoundID.Item164, base.Center);
            }
            float num89 = 90f - (float)num9;
            Vector2 vector26 = default(Vector2);
            ((Vector2)(ref vector26))._002Ector(-55f, -30f);
            NPCAimedTarget targetData3 = GetTargetData();
            Vector2 vector27 = (targetData3.Invalid ? base.Center : targetData3.Center);
            if (Distance(vector27 + vector) > num23)
            {
                SimpleFlyMovement(DirectionTo(vector27 + vector).SafeNormalize(Vector2.Zero) * num12, num);
            }
            if (this.ai[1] < 60f)
            {
                AI_120_HallowBoss_DoMagicEffect(base.Center + vector26, 1, Utils.GetLerpValue(0f, 60f, this.ai[1], clamped: true));
            }
            int num90 = 3;
            if (flag5)
            {
                num90 = 2;
            }
            if ((int)this.ai[1] % num90 == 0 && this.ai[1] < 60f)
            {
                float ai3 = this.ai[1] / 60f;
                Vector2 spinningpoint3 = new Vector2(0f, -6f);
                double radians5 = (float)Math.PI / 2f * Main.rand.NextFloatDirection();
                val = default(Vector2);
                Vector2 vector28 = Utils.RotatedBy(spinningpoint3, radians5, val);
                if (flag6)
                {
                    Vector2 spinningpoint4 = new Vector2(0f, -10f);
                    double radians6 = (float)Math.PI * 2f * Main.rand.NextFloat();
                    val = default(Vector2);
                    vector28 = Utils.RotatedBy(spinningpoint4, radians6, val);
                }
                if (Main.netMode != 1)
                {
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center + vector26, vector28, 873, num78, 0f, Main.myPlayer, target, ai3);
                }
                if (Main.netMode != 1)
                {
                    int num91 = (int)(this.ai[1] / (float)num90);
                    for (int num92 = 0; num92 < 255; num92++)
                    {
                        if (Boss_CanShootExtraAt(num92, num91 % 3, 3, 2400f))
{
                            Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center + vector26, vector28, 873, num78, 0f, Main.myPlayer, num92, ai3);
                        }
                    }
                }
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= 60f + num89)
            {
                this.ai[0] = 1f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 3:
        {
            this.ai[1] += 1f;
            NPCAimedTarget targetData10 = GetTargetData();
            Vector2 vector14 = (targetData10.Invalid ? base.Center : targetData10.Center);
            if (Distance(vector14 + vector10) > num23)
            {
                SimpleFlyMovement(DirectionTo(vector14 + vector10).SafeNormalize(Vector2.Zero) * num12, num);
            }
            if ((int)this.ai[1] % 180 == 0)
            {
                Vector2 vector15 = default(Vector2);
                ((Vector2)(ref vector15))._002Ector(0f, -100f);
                Projectile.NewProjectile(GetSpawnSource_ForProjectile(), targetData10.Center + vector15, Vector2.Zero, 874, num45, 0f, Main.myPlayer);
            }
            if (this.ai[1] >= 120f)
            {
                this.ai[0] = 1f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 4:
        {
            float num80 = 20 - num9;
            new Vector2(0f, -100f);
            if (this.ai[1] == 0f)
            {
                SoundEngine.PlaySound(in SoundID.Item162, base.Center);
            }
            if (this.ai[1] >= 6f && this.ai[1] < 54f)
            {
                AI_120_HallowBoss_DoMagicEffect(base.Center + new Vector2(-55f, -20f), 2, Utils.GetLerpValue(0f, 100f, this.ai[1], clamped: true));
                AI_120_HallowBoss_DoMagicEffect(base.Center + new Vector2(55f, -20f), 4, Utils.GetLerpValue(0f, 100f, this.ai[1], clamped: true));
            }
            NPCAimedTarget targetData2 = GetTargetData();
            Vector2 vector20 = (targetData2.Invalid ? base.Center : targetData2.Center);
            if (Distance(vector20 + vector21) > num23)
            {
                SimpleFlyMovement(DirectionTo(vector20 + vector21).SafeNormalize(Vector2.Zero) * num12, num);
            }
            int num81 = 4;
            if (flag5)
            {
                num81 = 5;
            }
            if ((int)this.ai[1] % 4 == 0 && this.ai[1] < 100f)
            {
                int num82 = 1;
                for (int n = 0; n < num82; n++)
                {
                    int num83 = (int)this.ai[1] / 4;
                    Vector2 unitX = Vector2.UnitX;
                    double radians4 = (float)Math.PI / (float)(num81 * 2) + (float)num83 * ((float)Math.PI / (float)num81) + 0f;
                    val = default(Vector2);
                    Vector2 vector22 = unitX.RotatedBy(radians4, val);
                    if (!flag5)
                    {
                        vector22.X += ((vector22.X > 0f) ? 0.5f : (-0.5f));
                    }
                    ((Vector2)(ref vector22)).Normalize();
                    float num84 = 300f;
                    if (flag5)
                    {
                        num84 = 450f;
                    }
                    Vector2 center4 = targetData2.Center;
                    if (Distance(center4) > 2400f)
                    {
                        continue;
                    }
                    if (Vector2.Dot(targetData2.Velocity.SafeNormalize(Vector2.UnitY), vector22) > 0f)
                    {
                        vector22 *= -1f;
                    }
                    int num85 = 90;
                    Vector2 val4 = center4 + targetData2.Velocity * (float)num85;
                    Vector2 vector23 = center4 + vector22 * num84 - targetData2.Velocity * 30f;
                    if (vector23.Distance(center4) < num84)
                    {
                        Vector2 vector24 = center4 - vector23;
                        if (vector24 == Vector2.Zero)
{
                            vector24 = vector22;
                        }
                        vector23 = center4 - Vector2.Normalize(vector24) * num84;
                    }
                    Vector2 v3 = val4 - vector23;
                    if (Main.netMode != 1)
                    {
                        Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector23, Vector2.Zero, 919, num56, 0f, Main.myPlayer, v3.ToRotation(), this.ai[1] / 100f);
                    }
                    if (Main.netMode == 1)
                    {
                        continue;
                    }
                    int num86 = (int)(this.ai[1] / 4f);
                    for (int num87 = 0; num87 < 255; num87++)
                    {
                        if (!Boss_CanShootExtraAt(num87, num86 % 3, 3, 2400f))
{
                            continue;
                        }
                        Player player2 = Main.player[num87];
                        center4 = player2.Center;
                        if (Vector2.Dot(player2.velocity.SafeNormalize(Vector2.UnitY), vector22) > 0f)
{
                            vector22 *= -1f;
                        }
                        Vector2 val5 = center4 + player2.velocity * (float)num85;
                        vector23 = center4 + vector22 * num84 - player2.velocity * 30f;
                        if (vector23.Distance(center4) < num84)
{
                            Vector2 vector25 = center4 - vector23;
                            if (vector25 == Vector2.Zero)
{
                                vector25 = vector22;
                            }
                            vector23 = center4 - Vector2.Normalize(vector25) * num84;
                        }
                        v3 = val5 - vector23;
                        Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector23, Vector2.Zero, 919, num56, 0f, Main.myPlayer, v3.ToRotation(), this.ai[1] / 100f);
                    }
                }
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= 100f + num80)
            {
                this.ai[0] = 1f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 5:
        {
            if (this.ai[1] == 0f)
            {
                SoundEngine.PlaySound(in SoundID.Item163, base.Center);
            }
            float num60 = 30f;
            num60 -= (float)num9;
            Vector2 vector9 = default(Vector2);
            ((Vector2)(ref vector9))._002Ector(55f, -30f);
            Vector2 vector11 = base.Center + vector9;
            if (this.ai[1] < 42f)
            {
                AI_120_HallowBoss_DoMagicEffect(base.Center + vector9, 3, Utils.GetLerpValue(0f, 42f, this.ai[1], clamped: true));
            }
            NPCAimedTarget targetData9 = GetTargetData();
            Vector2 vector12 = (targetData9.Invalid ? base.Center : targetData9.Center);
            if (Distance(vector12 + vector29) > num23)
            {
                SimpleFlyMovement(DirectionTo(vector12 + vector29).SafeNormalize(Vector2.Zero) * num12, num);
            }
            if ((int)this.ai[1] % 42 == 0 && this.ai[1] < 42f)
            {
                float num61 = (float)Math.PI * 2f * Main.rand.NextFloat();
                for (float num62 = 0f; num62 < 1f; num62 += 1f / 13f)
                {
                    float num63 = num62;
                    Vector2 unitY = Vector2.UnitY;
                    double radians3 = (float)Math.PI / 2f + (float)Math.PI * 2f * num63 + num61;
                    val = default(Vector2);
                    Vector2 vector13 = unitY.RotatedBy(radians3, val);
                    if (Main.netMode != 1)
                    {
                        IEntitySource spawnSource_ForProjectile = GetSpawnSource_ForProjectile();
                        val = default(Vector2);
                        Projectile.NewProjectile(spawnSource_ForProjectile, vector11 + vector13.RotatedBy(-1.5707963705062866, val) * 30f, vector13 * 8f, 872, num88, 0f, Main.myPlayer, 0f, num63);
                    }
                }
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= 42f + num60)
            {
                this.ai[0] = 1f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 6:
        {
            float num18 = 120 - num9;
            Vector2 vector33 = default(Vector2);
            ((Vector2)(ref vector33))._002Ector(0f, -100f);
            Vector2 vector34 = base.Center + vector33;
            NPCAimedTarget targetData4 = GetTargetData();
            Vector2 vector2 = (targetData4.Invalid ? base.Center : targetData4.Center);
            if (Distance(vector2 + vector30) > num23)
            {
                SimpleFlyMovement(DirectionTo(vector2 + vector30).SafeNormalize(Vector2.Zero) * num12 * 0.3f, num * 0.7f);
            }
            if ((int)this.ai[1] % 60 == 0 && this.ai[1] < 180f)
            {
                int num19 = (int)this.ai[1] / 60;
                int num20 = ((targetData4.Center.X > base.Center.X) ? 1 : 0);
                float num21 = 6f;
                if (flag5)
                {
                    num21 = 8f;
                }
                float num22 = 1f / num21;
                for (float num24 = 0f; num24 < 1f; num24 += num22)
                {
                    float num25 = (num24 + num22 * 0.5f + (float)num19 * num22 * 0.5f) % 1f;
                    float ai = (float)Math.PI * 2f * (num25 + (float)num20);
                    if (Main.netMode != 1)
                    {
                        Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector34, Vector2.Zero, 923, num2, 0f, Main.myPlayer, ai, whoAmI);
                    }
                }
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= 180f + num18)
            {
                this.ai[0] = 1f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 7:
        {
            float num68 = 20f;
            float num69 = 60f;
            float num70 = num69 * 4f;
            if (flag5)
            {
                num68 = 40f;
                num69 = 40f;
                num70 = num69 * 6f;
            }
            num68 -= (float)num9;
            NPCAimedTarget targetData11 = GetTargetData();
            Vector2 vector16 = (targetData11.Invalid ? base.Center : targetData11.Center);
            if (Distance(vector16 + vector29) > num23)
            {
                SimpleFlyMovement(DirectionTo(vector16 + vector29).SafeNormalize(Vector2.Zero) * num12 * 0.4f, num);
            }
            if ((float)(int)this.ai[1] % num69 == 0f && this.ai[1] < num70)
            {
                SoundEngine.PlaySound(in SoundID.Item162, base.Center);
                Main.rand.NextFloat();
                int num71 = (int)this.ai[1] / (int)num69;
                float num72 = 13f;
                float num73 = 150f;
                float num74 = num72 * num73;
                Vector2 center3 = targetData11.Center;
                if (Distance(center3) <= 3200f)
                {
                    Vector2 vector17 = Vector2.Zero;
                    Vector2 vector18 = Vector2.UnitY;
                    float num75 = 0.4f;
                    float num76 = 1.4f;
                    float num77 = 1f;
                    if (flag5)
                    {
                        num72 += 5f;
                        num73 += 50f;
                        num77 *= 1f;
                        num74 *= 0.5f;
                    }
                    switch (num71)
                    {
                    case 0:
                        center3 += new Vector2((0f - num74) / 2f, 0f) * num77;
                        ((Vector2)(ref vector17))._002Ector(0f, num74);
                        vector18 = Vector2.UnitX;
                        break;
                    case 1:
                        center3 += new Vector2(num74 / 2f, num73 / 2f) * num77;
                        ((Vector2)(ref vector17))._002Ector(0f, num74);
                        vector18 = -Vector2.UnitX;
                        break;
                    case 2:
                        center3 += new Vector2(0f - num74, 0f - num74) * num75 * num77;
                        ((Vector2)(ref vector17))._002Ector(num74 * num76, 0f);
                        ((Vector2)(ref vector18))._002Ector(1f, 1f);
                        break;
                    case 3:
                        center3 += new Vector2(num74 * num75 + num73 / 2f, (0f - num74) * num75) * num77;
                        ((Vector2)(ref vector17))._002Ector((0f - num74) * num76, 0f);
                        ((Vector2)(ref vector18))._002Ector(-1f, 1f);
                        break;
                    case 4:
                        center3 += new Vector2(0f - num74, num74) * num75 * num77;
                        ((Vector2)(ref vector17))._002Ector(num74 * num76, 0f);
                        vector18 = center3.DirectionTo(targetData11.Center);
                        break;
                    case 5:
                        center3 += new Vector2(num74 * num75 + num73 / 2f, num74 * num75) * num77;
                        ((Vector2)(ref vector17))._002Ector((0f - num74) * num76, 0f);
                        vector18 = center3.DirectionTo(targetData11.Center);
                        break;
                    }
                    for (float num79 = 0f; num79 <= 1f; num79 += 1f / num72)
                    {
                        Vector2 origin = center3 + vector17 * (num79 - 0.5f);
                        Vector2 v2 = vector18;
                        if (flag5)
{
                            Vector2 vector19 = targetData11.Velocity * 20f * num79;
                            Vector2 value2 = origin.DirectionTo(targetData11.Center + vector19);
                            v2 = Vector2.Lerp(vector18, value2, 0.75f).SafeNormalize(Vector2.UnitY);
                        }
                        float ai2 = num79;
                        if (Main.netMode != 1)
{
                            Projectile.NewProjectile(GetSpawnSource_ForProjectile(), origin, Vector2.Zero, 919, num67, 0f, Main.myPlayer, v2.ToRotation(), ai2);
                        }
                    }
                }
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= num70 + num68)
            {
                this.ai[0] = 1f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 8:
        case 9:
        {
            float num26 = 20 - num9;
            Vector2 vector3 = default(Vector2);
            ((Vector2)(ref vector3))._002Ector(0f, -100f);
            _ = base.Center + vector3;
            flag9 = !(this.ai[1] >= 6f) || !(this.ai[1] <= 40f);
            int num27 = ((this.ai[0] != 8f) ? 1 : (-1));
            AI_120_HallowBoss_DoMagicEffect(base.Center, 5, Utils.GetLerpValue(40f, 90f, this.ai[1], clamped: true));
            if (this.ai[1] <= 40f)
            {
                if (this.ai[1] == 20f)
                {
                    SoundEngine.PlaySound(in SoundID.Item160, base.Center);
                }
                NPCAimedTarget targetData5 = GetTargetData();
                Vector2 destination = (targetData5.Invalid ? base.Center : targetData5.Center) + new Vector2((float)(num27 * -550), 0f);
                SimpleFlyMovement(DirectionTo(destination).SafeNormalize(Vector2.Zero) * num12, num * 2f);
                if (this.ai[1] == 40f)
                {
                    velocity *= 0.3f;
                }
            }
            else if (this.ai[1] <= 90f)
            {
                ((Vector2)(ref val))._002Ector((float)(num27 * 50), 0f);
                velocity = Vector2.Lerp(velocity, val, 0.05f);
                if (this.ai[1] == 90f)
                {
                    velocity *= 0.7f;
                }
                num8 *= 1.5f;
            }
            else
            {
                velocity *= 0.92f;
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= 90f + num26)
            {
                this.ai[0] = 1f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 10:
        {
            float num93 = 20 - num9;
            if (this.ai[1] == 0f)
            {
                SoundEngine.PlaySound(in SoundID.Item161, base.Center);
            }
            flag9 = !(this.ai[1] >= 30f) || !(this.ai[1] <= 170f);
            velocity *= 0.95f;
            if (this.ai[1] == 90f)
            {
                if (this.ai[3] == 0f)
                {
                    this.ai[3] = 1f;
                }
                if (this.ai[3] == 2f)
                {
                    this.ai[3] = 3f;
                }
                base.Center = GetTargetData().Center + new Vector2(0f, -250f);
                netUpdate = true;
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= 180f + num93)
            {
                this.ai[0] = 1f;
                this.ai[1] = 0f;
                this.ai[2] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 11:
        {
            if (this.ai[1] == 0f)
            {
                SoundEngine.PlaySound(in SoundID.Item162, base.Center);
            }
            float num54 = 20 - num9;
            new Vector2(0f, -100f);
            if (this.ai[1] >= 6f && this.ai[1] < 54f)
            {
                AI_120_HallowBoss_DoMagicEffect(base.Center + new Vector2(-55f, -20f), 2, Utils.GetLerpValue(0f, 100f, this.ai[1], clamped: true));
                AI_120_HallowBoss_DoMagicEffect(base.Center + new Vector2(55f, -20f), 4, Utils.GetLerpValue(0f, 100f, this.ai[1], clamped: true));
            }
            NPCAimedTarget targetData8 = GetTargetData();
            Vector2 vector4 = (targetData8.Invalid ? base.Center : targetData8.Center);
            if (Distance(vector4 + vector21) > num23)
            {
                SimpleFlyMovement(DirectionTo(vector4 + vector21).SafeNormalize(Vector2.Zero) * num12, num);
            }
            if ((int)this.ai[1] % 3 == 0 && this.ai[1] < 100f)
            {
                int num55 = 1;
                for (int k = 0; k < num55; k++)
                {
                    Vector2 vector5 = -targetData8.Velocity;
                    vector5.SafeNormalize(-Vector2.UnitY);
                    float num57 = 100f;
                    Vector2 center2 = targetData8.Center;
                    if (Distance(center2) > 2400f)
                    {
                        continue;
                    }
                    int num58 = 90;
                    Vector2 val2 = center2 + targetData8.Velocity * (float)num58;
                    Vector2 vector6 = center2 + vector5 * num57;
                    if (vector6.Distance(center2) < num57)
                    {
                        Vector2 vector7 = center2 - vector6;
                        if (vector7 == Vector2.Zero)
{
                            vector7 = vector5;
                        }
                        vector6 = center2 - Vector2.Normalize(vector7) * num57;
                    }
                    Vector2 v = val2 - vector6;
                    if (Main.netMode != 1)
                    {
                        Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector6, Vector2.Zero, 919, num56, 0f, Main.myPlayer, v.ToRotation(), this.ai[1] / 100f);
                    }
                    if (Main.netMode == 1)
                    {
                        continue;
                    }
                    int num59 = (int)(this.ai[1] / 3f);
                    for (int l = 0; l < 255; l++)
                    {
                        if (!Boss_CanShootExtraAt(l, num59 % 3, 3, 2400f))
{
                            continue;
                        }
                        Player player = Main.player[l];
                        vector5 = -player.velocity;
                        vector5.SafeNormalize(-Vector2.UnitY);
                        num57 = 100f;
                        center2 = player.Center;
                        num58 = 90;
                        Vector2 val3 = center2 + player.velocity * (float)num58;
                        vector6 = center2 + vector5 * num57;
                        if (vector6.Distance(center2) < num57)
{
                            Vector2 vector8 = center2 - vector6;
                            if (vector8 == Vector2.Zero)
{
                                vector8 = vector5;
                            }
                            vector6 = center2 - Vector2.Normalize(vector8) * num57;
                        }
                        v = val3 - vector6;
                        Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector6, Vector2.Zero, 919, num56, 0f, Main.myPlayer, v.ToRotation(), this.ai[1] / 100f);
                    }
                }
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= 100f + num54)
            {
                this.ai[0] = 1f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 12:
        {
            float num14 = 90f - (float)num9;
            Vector2 vector31 = default(Vector2);
            ((Vector2)(ref vector31))._002Ector(-55f, -30f);
            if (this.ai[1] == 0f)
            {
                SoundEngine.PlaySound(in SoundID.Item165, base.Center);
                velocity = new Vector2(0f, -12f);
            }
            velocity *= 0.95f;
            bool flag3 = this.ai[1] < 60f && this.ai[1] >= 10f;
            if (flag3)
            {
                AI_120_HallowBoss_DoMagicEffect(base.Center + vector31, 1, Utils.GetLerpValue(0f, 60f, this.ai[1], clamped: true));
            }
            int num15 = 6;
            if (flag5)
            {
                num15 = 4;
            }
            float num16 = (this.ai[1] - 10f) / 50f;
            if ((int)this.ai[1] % num15 == 0 && flag3)
            {
                _ = this.ai[1] / 60f;
                Vector2 spinningpoint = new Vector2(0f, -20f);
                double radians = (float)Math.PI * 2f * num16;
                val = default(Vector2);
                Vector2 vector32 = (vector32 = Utils.RotatedBy(spinningpoint, radians, val));
                if (Main.netMode != 1)
                {
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center + vector31, vector32, 873, num78, 0f, Main.myPlayer, target, num16);
                }
                if (Main.netMode != 1)
                {
                    int num17 = (int)(this.ai[1] % (float)num15);
                    for (int j = 0; j < 255; j++)
                    {
                        if (Boss_CanShootExtraAt(j, num17 % 3, 3, 2400f))
{
                            Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center + vector31, vector32, 873, num78, 0f, Main.myPlayer, j, num16);
                        }
                    }
                }
            }
            this.ai[1] += 1f;
            if (this.ai[1] >= 60f + num14)
            {
                this.ai[0] = 1f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 13:
        {
            new Vector2(-55f, -30f);
            if (this.ai[1] == 0f)
            {
                SoundEngine.PlaySound(in SoundID.Item165, base.Center);
                velocity = new Vector2(0f, -7f);
            }
            velocity *= 0.95f;
            TargetClosest();
            NPCAimedTarget targetData = GetTargetData();
            flag8 = false;
            bool flag10 = false;
            bool flag11 = false;
            if (!flag10)
            {
                if (AI_120_HallowBoss_IsGenuinelyEnraged())
                {
                    if (!Main.dayTime)
                    {
                        flag11 = true;
                    }
                    if (Main.dayTime && Main.time >= 53400.0)
                    {
                        flag11 = true;
                    }
                }
                flag10 = flag10 || flag11;
            }
            if (!flag10)
            {
                bool flag12 = targetData.Invalid || Distance(targetData.Center) > num34;
                flag10 = flag10 || flag12;
            }
            alpha = Utils.Clamp(alpha + flag10.ToDirectionInt() * 5, 0, 255);
            bool flag2 = alpha == 0 || alpha == 255;
            int num10 = 5;
            for (int i = 0; i < num10; i++)
            {
                float num11 = MathHelper.Lerp(1.3f, 0.7f, Opacity);
                Color newColor = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f);
                int num13 = Dust.NewDust(position - base.Size * 0.5f, width * 2, height * 2, 267, 0f, 0f, 0, newColor);
                Main.dust[num13].position = base.Center + Main.rand.NextVector2Circular(width, height);
                Dust obj = Main.dust[num13];
                obj.velocity *= Main.rand.NextFloat() * 0.8f;
                Main.dust[num13].noGravity = true;
                Main.dust[num13].scale = 0.9f + Main.rand.NextFloat() * 1.2f;
                Main.dust[num13].fadeIn = 0.4f + Main.rand.NextFloat() * 1.2f * num11;
                Dust obj2 = Main.dust[num13];
                obj2.velocity += Vector2.UnitY * -2f;
                Main.dust[num13].scale = 0.35f;
                if (num13 != 6000)
                {
                    Dust dust = Dust.CloneDust(num13);
                    dust.scale /= 2f;
                    dust.fadeIn *= 0.85f;
                    dust.color = new Color(255, 255, 255, 255);
                }
            }
            this.ai[1] += 1f;
            if (!(this.ai[1] >= 20f && flag2))
            {
                break;
            }
            if (alpha == 255)
            {
                active = false;
                if (Main.netMode != 1)
                {
                    NetMessage.SendData(23, -1, -1, null, whoAmI);
                }
                return;
            }
            this.ai[0] = 1f;
            this.ai[1] = 0f;
            netUpdate = true;
            break;
        }
        }
        dontTakeDamage = !flag9;
        damage = GetAttackDamage_ScaledByStrength((float)defDamage * num8);
        if (flag7)
        {
            damage = 9999;
        }
        if (flag)
        {
            defense = (int)((float)defDefense * 1.2f);
        }
        else
        {
            defense = defDefense;
        }
        if ((localAI[0] += 1f) >= 44f)
        {
            localAI[0] = 0f;
        }
        if (flag8)
        {
            alpha = Utils.Clamp(alpha - 5, 0, 255);
        }
        Lighting.AddLight(base.Center, Vector3.One * Opacity);
    }
References Terraria.Entity.active, Terraria.Lighting.AddLight(), Terraria.NPC.ai, Terraria.NPC.AI_120_HallowBoss_DashTo(), Terraria.NPC.AI_120_HallowBoss_DoMagicEffect(), Terraria.NPC.AI_120_HallowBoss_IsGenuinelyEnraged(), Terraria.NPC.AI_120_HallowBoss_IsInPhase2(), Terraria.NPC.alpha, Terraria.NPC.Boss_CanShootExtraAt(), Terraria.DataStructures.NPCAimedTarget.Center, Terraria.Entity.Center, Terraria.Dust.CloneDust(), Terraria.NPC.damage, Terraria.Main.dayTime, Terraria.NPC.defDamage, Terraria.NPC.defDefense, Terraria.NPC.defense, Terraria.Entity.DirectionFrom(), Terraria.Entity.DirectionTo(), Terraria.Entity.Distance(), Terraria.NPC.dontTakeDamage, Terraria.Main.dust, Terraria.Main.expertMode, Terraria.NPC.GetAttackDamage_ForProjectiles(), Terraria.NPC.GetAttackDamage_ScaledByStrength(), Terraria.Main.getGoodWorld, Terraria.Utils.GetLerpValue(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetTargetData(), Terraria.Entity.height, Terraria.Main.hslToRgb(), Terraria.ID.SoundID.Item160, Terraria.ID.SoundID.Item161, Terraria.ID.SoundID.Item162, Terraria.ID.SoundID.Item163, Terraria.ID.SoundID.Item164, Terraria.ID.SoundID.Item165, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.Dust.NewDust(), Terraria.Projectile.NewProjectile(), Terraria.NPC.Opacity, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Utils.RotatedBy(), Terraria.NetMessage.SendData(), Terraria.NPC.ShouldEmpressBeEnraged(), Terraria.NPC.SimpleFlyMovement(), Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Main.time, Terraria.Entity.velocity, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.NPC.VanillaAI_Inner().