TModLoader: Terraria.NPC.SimpleFlyMovement
SimpleFlyMovement()
void Terraria.NPC.SimpleFlyMovement (Vector2 desiredVelocity, float moveSpeed) inline
    {
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_012e: Unknown result type (might be due to invalid IL or missing references)
        if (velocity.X < desiredVelocity.X)
        {
            velocity.X += moveSpeed;
            if (velocity.X < 0f && desiredVelocity.X > 0f)
            {
                velocity.X += moveSpeed;
            }
        }
        else if (velocity.X > desiredVelocity.X)
        {
            velocity.X -= moveSpeed;
            if (velocity.X > 0f && desiredVelocity.X < 0f)
            {
                velocity.X -= moveSpeed;
            }
        }
        if (velocity.Y < desiredVelocity.Y)
        {
            velocity.Y += moveSpeed;
            if (velocity.Y < 0f && desiredVelocity.Y > 0f)
            {
                velocity.Y += moveSpeed;
            }
        }
        else if (velocity.Y > desiredVelocity.Y)
        {
            velocity.Y -= moveSpeed;
            if (velocity.Y > 0f && desiredVelocity.Y < 0f)
            {
                velocity.Y -= moveSpeed;
            }
        }
    }
References Terraria.Entity.velocity.
Referenced by Terraria.NPC.AI_069_DukeFishron(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_121_QueenSlime_FlyMovement(), and Terraria.NPC.VanillaAI_Inner().