TModLoader: Terraria.NPC.AI_121_QueenSlime_FlyMovement
AI_121_QueenSlime_FlyMovement()
void Terraria.NPC.AI_121_QueenSlime_FlyMovement () inline private
    {
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0130: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_0206: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        noTileCollide = true;
        noGravity = true;
        float num = 12f;
        float num2 = 0.085f;
        float num3 = 250f;
        TargetClosest();
        Vector2 desiredVelocity = base.Center;
        if (timeLeft > 10)
        {
            if (!Collision.CanHit(this, Main.player[target]))
            {
                bool flag = false;
                Vector2 center = Main.player[target].Center;
                for (int i = 0; i < 16; i++)
                {
                    float num4 = 16 * i;
                    Point point = (center + new Vector2(0f, 0f - num4)).ToTileCoordinates();
                    if (WorldGen.SolidOrSlopedTile(point.X, point.Y))
                    {
                        desiredVelocity = center + new Vector2(0f, 0f - num4 + 16f) - base.Center;
                        flag = true;
                        break;
                    }
                }
                if (!flag)
                {
                    desiredVelocity = center - base.Center;
                }
            }
            else
            {
                desiredVelocity = Main.player[target].Center + new Vector2(0f, 0f - num3) - base.Center;
            }
        }
        else
        {
            desiredVelocity = base.Center + new Vector2(500f * (float)direction, 0f - num3) - base.Center;
        }
        float num5 = ((Vector2)(ref desiredVelocity)).Length();
        if (Math.Abs(desiredVelocity.X) < 40f)
        {
            desiredVelocity.X = velocity.X;
        }
        float num6 = num - 2f;
        if (num5 > 100f && ((velocity.X < 0f - num6 && desiredVelocity.X > 0f) || (velocity.X > num6 && desiredVelocity.X < 0f)))
        {
            num2 *= 2f;
        }
        if (num5 < 40f)
        {
            desiredVelocity = velocity;
        }
        else if (num5 < 80f)
        {
            ((Vector2)(ref desiredVelocity)).Normalize();
            desiredVelocity *= num * 0.65f;
        }
        else
        {
            ((Vector2)(ref desiredVelocity)).Normalize();
            desiredVelocity *= num;
        }
        SimpleFlyMovement(desiredVelocity, num2);
        rotation = velocity.X * 0.1f;
        if (rotation > 0.5f)
        {
            rotation = 0.5f;
        }
        if (rotation < -0.5f)
        {
            rotation = -0.5f;
        }
    }
References Terraria.Collision.CanHit(), Terraria.Entity.direction, Terraria.NPC.noGravity, Terraria.NPC.noTileCollide, Terraria.Main.player, Terraria.NPC.rotation, Terraria.NPC.SimpleFlyMovement(), Terraria.WorldGen.SolidOrSlopedTile(), Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.NPC.timeLeft, and Terraria.Entity.velocity.
Referenced by Terraria.NPC.AI_121_QueenSlime().