TModLoader: Terraria.NPC.DoDeathEvents_CelebrateBossDeath
DoDeathEvents_CelebrateBossDeath()
void Terraria.NPC.DoDeathEvents_CelebrateBossDeath (string typeName) inline private
Definition at line 84627 of file NPC.cs.
    {
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        if (type == 125 || type == 126)
        {
            if (Main.netMode == 0)
            {
                Main.NewText(Language.GetTextValue("Announcement.HasBeenDefeated_Plural", Language.GetTextValue("Enemies.TheTwins")), 175, 75);
            }
            else if (Main.netMode == 2)
            {
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasBeenDefeated_Plural", NetworkText.FromKey("Enemies.TheTwins")), new Color(175, 75, 255));
            }
        }
        else if (type == 398)
        {
            if (Main.netMode == 0)
            {
                Main.NewText(Language.GetTextValue("Announcement.HasBeenDefeated_Single", Language.GetTextValue("Enemies.MoonLord")), 175, 75);
            }
            else if (Main.netMode == 2)
            {
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasBeenDefeated_Single", NetworkText.FromKey("Enemies.MoonLord")), new Color(175, 75, 255));
            }
        }
        else if (Main.netMode == 0)
        {
            Main.NewText(Language.GetTextValue("Announcement.HasBeenDefeated_Single", typeName), 175, 75);
        }
        else if (Main.netMode == 2)
        {
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasBeenDefeated_Single", GetTypeNetName()), new Color(175, 75, 255));
        }
    }
References Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Localization.NetworkText.FromKey(), Terraria.Localization.Language.GetTextValue(), Terraria.NPC.GetTypeNetName(), Terraria.Main.netMode, Terraria.Main.NewText(), and Terraria.NPC.type.
Referenced by Terraria.NPC.DoDeathEvents().