TModLoader: Terraria.NPC.AI_114_Dragonflies
AI_114_Dragonflies()
void Terraria.NPC.AI_114_Dragonflies () inline private
    {
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_0214: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_026a: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_047d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0482: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_050c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0512: Unknown result type (might be due to invalid IL or missing references)
        //IL_0560: Unknown result type (might be due to invalid IL or missing references)
        //IL_0562: Unknown result type (might be due to invalid IL or missing references)
        //IL_0567: Unknown result type (might be due to invalid IL or missing references)
        //IL_0568: Unknown result type (might be due to invalid IL or missing references)
        //IL_056b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0570: Unknown result type (might be due to invalid IL or missing references)
        //IL_0573: Unknown result type (might be due to invalid IL or missing references)
        //IL_0578: Unknown result type (might be due to invalid IL or missing references)
        //IL_0579: Unknown result type (might be due to invalid IL or missing references)
        //IL_057e: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_052b: Unknown result type (might be due to invalid IL or missing references)
        //IL_052f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0534: Unknown result type (might be due to invalid IL or missing references)
        //IL_0539: Unknown result type (might be due to invalid IL or missing references)
        //IL_053e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0625: Unknown result type (might be due to invalid IL or missing references)
        //IL_062b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0630: Unknown result type (might be due to invalid IL or missing references)
        //IL_0635: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0597: Unknown result type (might be due to invalid IL or missing references)
        //IL_059c: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0701: Unknown result type (might be due to invalid IL or missing references)
        if (localAI[0] == 0f && Main.netMode != 1)
        {
            localAI[0] = 1f;
            Vector2 center = base.Center;
            ai[2] = center.X;
            ai[3] = center.Y;
            velocity = (Main.rand.NextVector2Circular(5f, 3f) + Main.rand.NextVector2CircularEdge(5f, 3f)) * 0.4f;
            ai[1] = 0f;
            ai[0] = 1f;
            netUpdate = true;
        }
        switch ((int)ai[0])
        {
        case 0:
            velocity *= 0.94f;
            if (Main.netMode != 1 && (ai[1] += 1f) >= (float)(60 + Main.rand.Next(60)))
            {
                Vector2 vector = default(Vector2);
                ((Vector2)(ref vector))._002Ector(ai[2], ai[3]);
                if (Distance(vector) > 96f)
                {
                    velocity = DirectionTo(vector) * 3f;
                }
                else if (Distance(vector) > 16f)
                {
                    velocity = DirectionTo(vector) * 1f + Main.rand.NextVector2Circular(1f, 0.5f);
                }
                else
                {
                    velocity = (Main.rand.NextVector2Circular(5f, 3f) + Main.rand.NextVector2CircularEdge(5f, 3f)) * 0.4f;
                }
                ai[1] = 0f;
                ai[0] = 1f;
                netUpdate = true;
            }
            break;
        case 1:
        {
            int num = 4;
            Vector2 other = default(Vector2);
            ((Vector2)(ref other))._002Ector(ai[2], ai[3]);
            if (Distance(other) > 112f)
            {
                num = 200;
            }
            if ((ai[1] += 1f) >= (float)num)
            {
                ai[1] = 0f;
                ai[0] = 0f;
                netUpdate = true;
            }
            int num2 = (int)base.Center.X / 16;
            int num3 = (int)base.Center.Y / 16;
            int num4 = 3;
            for (int i = num3; i < num3 + num4; i++)
            {
                if (Main.tile[num2, i] != null && ((Main.tile[num2, i].nactive() && Main.tileSolid[Main.tile[num2, i].type]) || Main.tile[num2, i].liquid > 0))
                {
                    if (velocity.Y > 0f)
                    {
                        velocity.Y *= 0.9f;
                    }
                    velocity.Y -= 0.2f;
                }
            }
            if (!(velocity.Y < 0f))
            {
                break;
            }
            int num5 = 30;
            bool flag = false;
            for (int j = num3; j < num3 + num5; j++)
            {
                if (Main.tile[num2, j] != null && Main.tile[num2, j].nactive() && Main.tileSolid[Main.tile[num2, j].type])
                {
                    flag = true;
                    break;
                }
            }
            if (!flag && velocity.Y < 0f)
            {
                velocity.Y *= 0.9f;
            }
            break;
        }
        }
        if (velocity.X != 0f)
        {
            direction = ((velocity.X > 0f) ? 1 : (-1));
        }
        if (wet)
        {
            velocity.Y = -3f;
        }
        if (localAI[1] > 0f)
        {
            localAI[1] -= 1f;
            return;
        }
        localAI[1] = 15f;
        float num6 = 0f;
        Vector2 zero = Vector2.Zero;
        for (int k = 0; k < 200; k++)
        {
            NPC nPC = Main.npc[k];
            if (nPC.active && nPC.damage > 0 && !nPC.friendly && nPC.Hitbox.Distance(base.Center) <= 100f)
            {
                num6 += 1f;
                zero += DirectionFrom(nPC.Center);
            }
        }
        for (int l = 0; l < 255; l++)
        {
            Player player = Main.player[l];
            if (player.active && player.Hitbox.Distance(base.Center) <= 150f)
            {
                num6 += 1f;
                zero += DirectionFrom(player.Center);
            }
        }
        if (num6 > 0f)
        {
            float num7 = 2f;
            zero /= num6;
            zero *= num7;
            velocity += zero;
            if (((Vector2)(ref velocity)).Length() > 16f)
            {
                velocity = velocity.SafeNormalize(Vector2.Zero) * 16f;
            }
            Vector2 vector2 = base.Center + zero * 10f;
            ai[1] = -10f;
            ai[0] = 1f;
            ai[2] = vector2.X;
            ai[3] = vector2.Y;
            netUpdate = true;
        }
        else
        {
            if (Main.netMode == 1)
            {
                return;
            }
            Vector2 val = new Vector2(ai[2], ai[3]) - base.Center;
            if (!(((Vector2)(ref val)).Length() < 16f))
            {
                return;
            }
            int maxValue = 30;
            if (Main.tile[(int)ai[2] / 16, (int)ai[3] / 16].type != 519)
            {
                maxValue = 4;
            }
            if (Main.rand.Next(maxValue) != 0)
            {
                return;
            }
            int cattailX = (int)ai[2];
            int cattailY = (int)ai[2];
            if (FindCattailTop((int)ai[2] / 16, (int)ai[3] / 16, out cattailX, out cattailY))
            {
                ai[2] = cattailX * 16;
                ai[3] = cattailY * 16;
                netUpdate = true;
                return;
            }
            int num8 = (int)(base.Center.X / 16f);
            int m;
            for (m = (int)(base.Center.Y / 16f); !WorldGen.SolidTile(num8, m) && (double)m < Main.worldSurface; m++)
            {
            }
            m -= Main.rand.Next(3, 6);
            ai[2] = num8 * 16;
            ai[3] = m * 16;
            netUpdate = true;
        }
    }
References Terraria.Entity.active, Terraria.NPC.ai, Terraria.Entity.Center, Terraria.Entity.direction, Terraria.Entity.DirectionFrom(), Terraria.Entity.DirectionTo(), Terraria.Entity.Distance(), Terraria.NPC.FindCattailTop(), Terraria.Entity.Hitbox, Terraria.NPC.localAI, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Main.player, Terraria.Main.rand, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Entity.velocity, Terraria.Entity.wet, and Terraria.Main.worldSurface.
Referenced by Terraria.NPC.VanillaAI_Inner().