TModLoader: Terraria.NPC.AI_113_WindyBalloon
AI_113_WindyBalloon()
void Terraria.NPC.AI_113_WindyBalloon () inline private
Definition at line 50061 of file NPC.cs.
    {
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_0164: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01be: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_087b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_020c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_052f: Unknown result type (might be due to invalid IL or missing references)
        //IL_054c: Unknown result type (might be due to invalid IL or missing references)
        //IL_058c: Unknown result type (might be due to invalid IL or missing references)
        //IL_061f: Unknown result type (might be due to invalid IL or missing references)
        //IL_073d: Unknown result type (might be due to invalid IL or missing references)
        //IL_074c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0751: Unknown result type (might be due to invalid IL or missing references)
        //IL_0769: Unknown result type (might be due to invalid IL or missing references)
        //IL_076e: Unknown result type (might be due to invalid IL or missing references)
        //IL_077a: Unknown result type (might be due to invalid IL or missing references)
        //IL_077f: Unknown result type (might be due to invalid IL or missing references)
        if (localAI[0] == 0f && Main.netMode != 1)
        {
            TargetClosest();
            localAI[0] = 1f;
            ai[2] = Main.rand.Next(7) + 1;
            int num = NewNPC(GetSpawnSourceForNPCFromNPCAI(), (int)position.X, (int)position.Y, 1);
            if (Main.rand.Next(180) == 0)
            {
                Main.npc[num].SetDefaults(-4);
            }
            else if (Main.rand.Next(10) == 0)
            {
                Main.npc[num].SetDefaults(-7);
            }
            else if (Main.rand.Next(3) == 0)
            {
                Main.npc[num].SetDefaults(-3);
            }
            Main.npc[num].ai[0] = -999f;
            Main.npc[num].netUpdate = true;
            ai[3] = num;
            netUpdate = true;
            ai[1] = Main.npc[num].scale;
        }
        position = base.Center;
        base.Size = new Vector2(20f, 20f) * ai[1];
        scale = ai[1];
        base.Center = position;
        NPC nPC = AI_113_WindyBalloon_GetSlaveNPC();
        rotation = velocity.X * 0.05f;
        if (nPC != null)
        {
            NPCAimedTarget targetData = GetTargetData();
            float num4 = float.PositiveInfinity;
            int num5 = 0;
            Vector2 zero = Vector2.Zero;
            if (!targetData.Invalid)
            {
                zero = targetData.Center - base.Bottom;
                if (zero.Y < 0f)
                {
                    num5 = (int)zero.Y / -16;
                }
                num4 = ((Vector2)(ref zero)).Length();
                if (direction != Math.Sign(zero.X))
                {
                    num5 = 0;
                }
            }
            if (wet || nPC.wet || collideX || (collideY && oldVelocity.Y < 0f))
            {
                float num6 = oldVelocity.X + (float)(direction * 8);
                position.X -= num6;
                nPC.position.X -= num6;
                TargetClosest(faceTarget: false);
                direction *= -1;
                velocity.X = direction * 2;
                life = -1;
                HitEffect();
                active = false;
                netUpdate = true;
                SoundEngine.PlaySound(DeathSound, position);
                return;
            }
            if (collideY)
            {
                velocity.Y = ((oldVelocity.Y > 0f) ? 1 : (-1));
                TargetClosest(faceTarget: false);
            }
            float num7 = 2f + Math.Abs(Main.windSpeedTarget) * 2f;
            if (Math.Sign(velocity.X) != direction || Math.Abs(velocity.X) < num7)
            {
                velocity.X += (float)direction * 0.01f;
                if (velocity.X * (float)direction < 0f)
                {
                    if (Math.Abs(velocity.X) > num7)
                    {
                        velocity.X += (float)direction * 0.1f;
                    }
                    else
                    {
                        velocity.X += (float)direction * 0.05f;
                    }
                }
                else if (Math.Abs(velocity.X) > num7)
                {
                    velocity.X = (float)direction * num7;
                }
            }
            int num8 = (int)((position.X + (float)(width / 2)) / 16f) + direction;
            int num9 = (int)((position.Y + (float)height) / 16f);
            bool flag = true;
            int num10 = 8 + num5;
            bool flag2 = false;
            for (int i = num9; i < num9 + num10; i++)
            {
                if (Main.tile[num8, i] == null)
                {
                    Main.tile[num8, i] = default(Tile);
                }
                if ((Main.tile[num8, i].nactive() && Main.tileSolid[Main.tile[num8, i].type]) || Main.tile[num8, i].liquid > 0)
                {
                    if (i < num9 + 5 + num5)
                    {
                        flag2 = true;
                    }
                    flag = false;
                    break;
                }
            }
            if (num4 < 400f && Collision.CanHit(position, width, height, Main.player[target].position, Main.player[target].width, Main.player[target].height))
            {
                float num11 = 2f;
                float num2 = 0.035f;
                if (base.Center.Y + (float)(height / 4) > Main.player[target].position.Y + (float)(Main.player[target].height / 4) && velocity.Y > 0f - num11)
                {
                    velocity.Y -= num2;
                    if (velocity.Y > 0f)
                    {
                        velocity.Y -= num2;
                    }
                }
                else if (base.Center.Y + (float)(height / 4) < Main.player[target].position.Y + (float)(Main.player[target].height / 4) && velocity.Y < num11)
                {
                    velocity.Y += num2;
                    if (velocity.Y < 0f)
                    {
                        velocity.Y += num2;
                    }
                }
            }
            else
            {
                if (flag)
                {
                    velocity.Y += 0.05f;
                }
                else
                {
                    velocity.Y -= 0.1f;
                }
                if (flag2)
                {
                    velocity.Y -= 0.2f;
                }
                if (velocity.Y > 2f)
                {
                    velocity.Y = 2f;
                }
                if (velocity.Y < -4f)
                {
                    velocity.Y = -4f;
                }
            }
            nPC.Center = base.Bottom + new Vector2(0f, -8f) + new Vector2(0f, 56f * ai[1]);
            nPC.velocity = velocity;
        }
        else
        {
            velocity.Y = MathHelper.Clamp(velocity.Y - 0.2f, -8f, 8f);
            velocity.X = MathHelper.Clamp(velocity.X + Main.windSpeedTarget * 0.3f, -4f, 4f);
            if (collideX || collideY)
            {
                float num3 = oldVelocity.X + (float)(direction * 8);
                position.X -= num3;
                TargetClosest(faceTarget: false);
                direction *= -1;
                velocity.X = direction * 2;
                life = -1;
                HitEffect();
                active = false;
                netUpdate = true;
                SoundEngine.PlaySound(DeathSound, position);
            }
        }
    }
References Terraria.Entity.active, Terraria.NPC.ai, Terraria.NPC.AI_113_WindyBalloon_GetSlaveNPC(), Terraria.Collision.CanHit(), Terraria.NPC.collideX, Terraria.NPC.collideY, Terraria.NPC.DeathSound, Terraria.Entity.direction, Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.NPC.GetTargetData(), Terraria.Entity.height, Terraria.NPC.HitEffect(), Terraria.NPC.life, Terraria.NPC.localAI, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Entity.oldVelocity, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.rotation, Terraria.NPC.scale, Terraria.NPC.SetDefaults(), Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Entity.width, and Terraria.Main.windSpeedTarget.
Referenced by Terraria.NPC.VanillaAI_Inner().