TModLoader: Terraria.NPC.NPCCanStickToWalls
NPCCanStickToWalls()
bool Terraria.NPC.NPCCanStickToWalls () inline
Definition at line 59382 of file NPC.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        int num = (int)base.Center.X / 16;
        int num2 = (int)base.Center.Y / 16;
        int num3 = 0;
        for (int i = num - 1; i <= num + 1; i++)
        {
            for (int j = num2 - 1; j <= num2 + 1; j++)
            {
                Tile tileSafely = Framing.GetTileSafely(i, j);
                if ((!tileSafely.active() || !Main.tileSolid[tileSafely.type] || TileID.Sets.Platforms[tileSafely.type]) && tileSafely.wall > 0)
                {
                    num3++;
                    if (num3 > 4)
                    {
                        return true;
                    }
                }
            }
        }
        return false;
    }
References Terraria.Framing.GetTileSafely(), Terraria.ID.TileID.Sets.Platforms, and Terraria.Main.tileSolid.
Referenced by Terraria.NPC.AI_003_Fighters(), and Terraria.NPC.VanillaAI_Inner().