TModLoader: Terraria.NPC.AI_110_Betsy
AI_110_Betsy()
void Terraria.NPC.AI_110_Betsy () inline private
    {
        //IL_01a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01be: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_047a: Unknown result type (might be due to invalid IL or missing references)
        //IL_076f: Unknown result type (might be due to invalid IL or missing references)
        //IL_077b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0529: Unknown result type (might be due to invalid IL or missing references)
        //IL_0535: Unknown result type (might be due to invalid IL or missing references)
        //IL_0504: Unknown result type (might be due to invalid IL or missing references)
        //IL_1278: Unknown result type (might be due to invalid IL or missing references)
        //IL_127d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aeb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bcc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07da: Unknown result type (might be due to invalid IL or missing references)
        //IL_07de: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0563: Unknown result type (might be due to invalid IL or missing references)
        //IL_0579: Unknown result type (might be due to invalid IL or missing references)
        //IL_057e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0583: Unknown result type (might be due to invalid IL or missing references)
        //IL_0586: Unknown result type (might be due to invalid IL or missing references)
        //IL_0588: Unknown result type (might be due to invalid IL or missing references)
        //IL_058f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0594: Unknown result type (might be due to invalid IL or missing references)
        //IL_0597: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0903: Unknown result type (might be due to invalid IL or missing references)
        //IL_0925: Unknown result type (might be due to invalid IL or missing references)
        //IL_0934: Unknown result type (might be due to invalid IL or missing references)
        //IL_0939: Unknown result type (might be due to invalid IL or missing references)
        //IL_093e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0864: Unknown result type (might be due to invalid IL or missing references)
        //IL_0869: Unknown result type (might be due to invalid IL or missing references)
        //IL_086e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0880: Unknown result type (might be due to invalid IL or missing references)
        //IL_0882: Unknown result type (might be due to invalid IL or missing references)
        //IL_088e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0893: Unknown result type (might be due to invalid IL or missing references)
        //IL_0898: Unknown result type (might be due to invalid IL or missing references)
        //IL_089b: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0605: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_096d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0987: Unknown result type (might be due to invalid IL or missing references)
        //IL_0995: Unknown result type (might be due to invalid IL or missing references)
        //IL_099b: Unknown result type (might be due to invalid IL or missing references)
        //IL_099d: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0823: Unknown result type (might be due to invalid IL or missing references)
        //IL_0826: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0620: Unknown result type (might be due to invalid IL or missing references)
        //IL_062a: Unknown result type (might be due to invalid IL or missing references)
        //IL_062f: Unknown result type (might be due to invalid IL or missing references)
        //IL_033a: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0344: Unknown result type (might be due to invalid IL or missing references)
        //IL_0347: Unknown result type (might be due to invalid IL or missing references)
        //IL_039e: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0400: Unknown result type (might be due to invalid IL or missing references)
        //IL_0403: Unknown result type (might be due to invalid IL or missing references)
        //IL_08db: Unknown result type (might be due to invalid IL or missing references)
        //IL_08df: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0695: Unknown result type (might be due to invalid IL or missing references)
        //IL_0656: Unknown result type (might be due to invalid IL or missing references)
        //IL_065c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d70: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09db: Unknown result type (might be due to invalid IL or missing references)
        //IL_035f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_041b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0387: Unknown result type (might be due to invalid IL or missing references)
        //IL_038b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0390: Unknown result type (might be due to invalid IL or missing references)
        //IL_0443: Unknown result type (might be due to invalid IL or missing references)
        //IL_0447: Unknown result type (might be due to invalid IL or missing references)
        //IL_044c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d91: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_100f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1024: Unknown result type (might be due to invalid IL or missing references)
        //IL_1033: Unknown result type (might be due to invalid IL or missing references)
        //IL_1038: Unknown result type (might be due to invalid IL or missing references)
        //IL_1042: Unknown result type (might be due to invalid IL or missing references)
        //IL_105d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1062: Unknown result type (might be due to invalid IL or missing references)
        //IL_1067: Unknown result type (might be due to invalid IL or missing references)
        //IL_1069: Unknown result type (might be due to invalid IL or missing references)
        //IL_106d: Unknown result type (might be due to invalid IL or missing references)
        //IL_107e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1080: Unknown result type (might be due to invalid IL or missing references)
        //IL_1085: Unknown result type (might be due to invalid IL or missing references)
        //IL_108d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1094: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f73: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f78: Unknown result type (might be due to invalid IL or missing references)
        //IL_1158: Unknown result type (might be due to invalid IL or missing references)
        //IL_115d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1162: Unknown result type (might be due to invalid IL or missing references)
        //IL_116a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1171: Unknown result type (might be due to invalid IL or missing references)
        //IL_11a4: Unknown result type (might be due to invalid IL or missing references)
        NPCUtils.TargetClosestBetsy(this, faceTarget: false);
        NPCAimedTarget targetData = GetTargetData();
        int num = -1;
        float num12 = 1f;
        int num23 = 35;
        int num34 = 35;
        float num43 = 10f;
        float num44 = 0.45f;
        float num45 = 7.5f;
        float num46 = 30f;
        float num47 = 30f;
        float num2 = 23f;
        float num3 = 600f;
        float num4 = 12f;
        float num5 = 40f;
        float num6 = 80f;
        float num7 = num5 + num6;
        float num8 = 1500f;
        float num9 = 60f;
        float num10 = 13f;
        float amount = 1f / 30f;
        float num11 = 12f;
        int num13 = 10;
        int num14 = 6 * num13;
        float num15 = 60f;
        float num16 = num9 + (float)num14 + num15;
        float num17 = 60f;
        float num18 = 1f;
        float num19 = (float)Math.PI * 2f * (num18 / num17);
        float num20 = 0.1f;
        float num21 = 32f;
        float num22 = 90f;
        float num24 = 20f;
        _ = ai[0];
        if (ai[0] == 0f)
        {
            if ((ai[1] += 1f) >= num43)
            {
                ai[1] = 0f;
                ai[0] = 1f;
                ai[2] = 0f;
                netUpdate = true;
            }
        }
        else if (ai[0] == 1f)
        {
            if (ai[2] == 0f)
            {
                ai[2] = ((base.Center.X < targetData.Center.X) ? 1 : (-1));
            }
            Vector2 destination = targetData.Center + new Vector2((0f - ai[2]) * 300f, -200f);
            Vector2 desiredVelocity = DirectionTo(destination) * num45;
            SimpleFlyMovement(desiredVelocity, num44);
            int num25 = ((base.Center.X < targetData.Center.X) ? 1 : (-1));
            direction = (spriteDirection = num25);
            if ((ai[1] += 1f) >= num46)
            {
                int num26 = 1;
                if (ai[3] == 5f && Main.rand.Next(3) == 0)
                {
                    ai[3] += 1f;
                }
                switch ((int)ai[3])
                {
                case 0:
                case 1:
                case 3:
                    num26 = 2;
                    break;
                case 2:
                    num26 = 3;
                    break;
                case 4:
                    num26 = 4;
                    break;
                case 5:
                    num26 = 5;
                    break;
                case 6:
                    num26 = 3;
                    break;
                case 7:
                    num26 = 6;
                    break;
                }
                ai[0] = num26;
                ai[1] = 0f;
                ai[2] = 0f;
                ai[3] += 1f;
                netUpdate = true;
                if (ai[3] >= 8f)
                {
                    ai[3] = 0f;
                }
                switch (num26)
                {
                case 2:
                {
                    Vector2 vector2 = DirectionTo(targetData.Center);
                    spriteDirection = ((vector2.X > 0f) ? 1 : (-1));
                    rotation = vector2.ToRotation();
                    if (spriteDirection == -1)
                    {
                        rotation += (float)Math.PI;
                    }
                    velocity = vector2 * num2;
                    break;
                }
                case 3:
                {
                    Vector2 vector3 = default(Vector2);
                    ((Vector2)(ref vector3))._002Ector((float)((targetData.Center.X > base.Center.X) ? 1 : (-1)), 0f);
                    spriteDirection = ((vector3.X > 0f) ? 1 : (-1));
                    velocity = vector3 * -2f;
                    break;
                }
                case 5:
                {
                    Vector2 vector = DirectionTo(targetData.Center);
                    spriteDirection = ((vector.X > 0f) ? 1 : (-1));
                    rotation = vector.ToRotation();
                    if (spriteDirection == -1)
                    {
                        rotation += (float)Math.PI;
                    }
                    velocity = vector * num21;
                    break;
                }
                }
            }
        }
        else if (ai[0] == 2f)
        {
            if (ai[1] == 0f)
            {
                SoundEngine.PlayTrackedSound(in SoundID.DD2_BetsyWindAttack, base.Center);
            }
            if ((ai[1] += 1f) >= num47)
            {
                ai[0] = 1f;
                ai[1] = 0f;
                ai[2] = 0f;
            }
        }
        else if (ai[0] == 3f)
        {
            ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[2]));
            if (activeSound != null)
            {
                activeSound.Position = base.Center;
            }
            ai[1] += 1f;
            int num27 = ((base.Center.X < targetData.Center.X) ? 1 : (-1));
            ai[2] = num27;
            if (ai[1] < num5)
            {
                Vector2 vector4 = targetData.Center + new Vector2((float)num27 * (0f - num3), -250f);
                Vector2 vector5 = DirectionTo(vector4) * num4;
                if (Distance(vector4) < num4)
                {
                    base.Center = vector4;
                }
                else
                {
                    position += vector5;
                }
                if (Vector2.Distance(vector4, base.Center) < 16f)
                {
                    ai[1] = num5 - 1f;
                }
                num12 = 1.5f;
            }
            if (ai[1] == num5)
            {
                int num28 = ((targetData.Center.X > base.Center.X) ? 1 : (-1));
                velocity = new Vector2((float)num28, 0f) * 10f;
                direction = (spriteDirection = num28);
                if (Main.netMode != 1)
                {
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), base.Center, velocity, 687, num23, 0f, Main.myPlayer, 0f, whoAmI);
                }
                localAI[2] = SoundEngine.PlayTrackedSound(in SoundID.DD2_BetsyFlameBreath, base.Center).ToFloat();
            }
            if (ai[1] >= num5)
            {
                num12 = 1.5f;
                if (Math.Abs(targetData.Center.X - base.Center.X) > 550f && Math.Abs(velocity.X) < 20f)
                {
                    velocity.X += (float)Math.Sign(velocity.X) * 0.5f;
                }
            }
            if (ai[1] >= num7)
            {
                ai[0] = 1f;
                ai[1] = 0f;
                ai[2] = 0f;
            }
        }
        else if (ai[0] == 4f)
        {
            int num29 = ((base.Center.X < targetData.Center.X) ? 1 : (-1));
            ai[2] = num29;
            if (ai[1] < num9)
            {
                Vector2 vector6 = targetData.Center + new Vector2((float)num29 * (0f - num8), -350f);
                Vector2 value = DirectionTo(vector6) * num10;
                velocity = Vector2.Lerp(velocity, value, amount);
                int num30 = ((base.Center.X < targetData.Center.X) ? 1 : (-1));
                direction = (spriteDirection = num30);
                if (Vector2.Distance(vector6, base.Center) < 16f)
                {
                    ai[1] = num9 - 1f;
                }
                num12 = 1.5f;
            }
            else if (ai[1] == num9)
            {
                Vector2 v = DirectionTo(targetData.Center);
                v.Y *= 0.25f;
                v = v.SafeNormalize(Vector2.UnitX * (float)direction);
                spriteDirection = ((v.X > 0f) ? 1 : (-1));
                rotation = v.ToRotation();
                if (spriteDirection == -1)
                {
                    rotation += (float)Math.PI;
                }
                velocity = v * num11;
            }
            else
            {
                position.X += DirectionTo(targetData.Center).X * 7f;
                position.Y += DirectionTo(targetData.Center + new Vector2(0f, -400f)).Y * 6f;
                if (ai[1] <= num16 - num15)
                {
                    num12 = 1.5f;
                }
                float num31 = 30f;
                Vector2 vector7 = base.Center + Utils.RotatedBy(new Vector2((110f + num31) * (float)direction, 20f), rotation);
                int num32 = (int)(ai[1] - num9 + 1f);
                if (num32 <= num14 && num32 % num13 == 0 && Main.netMode != 1)
                {
                    Projectile.NewProjectile(GetSpawnSource_ForProjectile(), vector7, velocity, 686, num34, 0f, Main.myPlayer);
                }
            }
            if (ai[1] > num16 - num15)
            {
                velocity.Y -= 0.1f;
            }
            ai[1] += 1f;
            if (ai[1] >= num16)
            {
                ai[0] = 1f;
                ai[1] = 0f;
                ai[2] = 0f;
            }
        }
        else if (ai[0] == 5f)
        {
            velocity = velocity.RotatedBy((0f - num19) * (float)direction);
            position.Y -= num20;
            position += DirectionTo(targetData.Center) * 10f;
            rotation -= num19 * (float)direction;
            num12 *= 0.7f;
            if (ai[1] == 1f)
            {
                SoundEngine.PlayTrackedSound(in SoundID.DD2_BetsyFlyingCircleAttack, base.Center);
            }
            if ((ai[1] += 1f) >= num17)
            {
                ai[0] = 1f;
                ai[1] = 0f;
                ai[2] = 0f;
                velocity /= 2f;
            }
        }
        else if (ai[0] == 6f)
        {
            if (ai[1] == 0f)
            {
                Vector2 destination2 = targetData.Center + new Vector2(0f, -200f);
                Vector2 desiredVelocity2 = DirectionTo(destination2) * num45 * 2f;
                SimpleFlyMovement(desiredVelocity2, num44 * 2f);
                int num33 = ((base.Center.X < targetData.Center.X) ? 1 : (-1));
                direction = (spriteDirection = num33);
                ai[2] += 1f;
                if (Distance(targetData.Center) < 350f || ai[2] >= 180f)
                {
                    ai[1] = 1f;
                    netUpdate = true;
                }
            }
            else
            {
                if (ai[1] == 1f)
                {
                    SoundEngine.PlayTrackedSound(in SoundID.DD2_BetsyScream);
                }
                if (ai[1] < num24)
                {
                    velocity *= 0.95f;
                }
                else
                {
                    velocity *= 0.98f;
                }
                if (ai[1] == num24)
                {
                    if (velocity.Y > 0f)
                    {
                        velocity.Y /= 3f;
                    }
                    velocity.Y -= 3f;
                }
                num12 *= 0.85f;
                if (ai[1] == 20f || ai[1] == 25f || ai[1] == 30f)
                {
                    Point point = base.Center.ToTileCoordinates();
                    int num35 = 30;
                    int num36 = 35;
                    int num37 = 4;
                    for (int i = point.X - num35; i <= point.X + num35; i++)
                    {
                        bool flag = false;
                        for (int j = point.Y - num36 / 3; j < point.Y + num36; j++)
{
                            Tile tileSafely = Framing.GetTileSafely(i, j);
                            bool flag2 = tileSafely.active() && Main.tileSolid[tileSafely.type] && !Main.tileFrameImportant[tileSafely.type];
                            if (flag && flag2)
{
                                int num38 = WorldGen.KillTile_GetTileDustAmount(fail: true, tileSafely, i, j);
                                for (int k = 0; k < num38; k++)
{
                                    Dust obj = Main.dust[WorldGen.KillTile_MakeTileDust(i, j, tileSafely)];
                                    obj.velocity.Y -= 3f + (float)num37 * 1.5f;
                                    obj.velocity.Y *= Main.rand.NextFloat();
                                    obj.scale += (float)num37 * 0.03f;
                                }
                                for (int l = 0; l < num38 - 1; l++)
{
                                    Dust obj2 = Main.dust[WorldGen.KillTile_MakeTileDust(i, j, tileSafely)];
                                    obj2.velocity.Y -= 1f + (float)num37;
                                    obj2.velocity.Y *= Main.rand.NextFloat();
                                }
                                if (num38 > 0 && Main.rand.Next(3) != 0)
{
                                    float num39 = Math.Abs(point.X - i) / (num35 / 2);
                                    Gore gore = Gore.NewGoreDirect(position, Vector2.Zero, 61 + Main.rand.Next(3), 1f - (float)num37 * 0.15f + num39 * 0.5f);
                                    gore.velocity.Y -= 0.1f + (float)num37 * 0.5f + num39 * (float)num37 * 1f;
                                    gore.velocity.Y *= Main.rand.NextFloat();
                                    gore.position = new Vector2((float)(i * 16 + 20), (float)(j * 16 + 20));
                                }
                            }
                            flag = !flag2;
                        }
                    }
                }
                bool flag3 = ai[1] == 20f || ai[1] == 45f || ai[1] == 70f;
                if (CountNPCS(560) > 4)
                {
                    flag3 = false;
                }
                if (flag3 && Main.netMode != 1)
                {
                    for (int m = 0; m < 1; m++)
                    {
                        Vector2 vector8 = base.Center + ((float)Math.PI * 2f * Main.rand.NextFloat()).ToRotationVector2() * new Vector2(2f, 1f) * 300f * (0.6f + Main.rand.NextFloat() * 0.4f);
                        if (Vector2.Distance(vector8, targetData.Center) > 100f)
{
                            Point point2 = vector8.ToPoint();
                            NewNPC(GetSpawnSourceForNPCFromNPCAI(), point2.X, point2.Y, 560, whoAmI);
                            SoundEngine.PlayTrackedSound(in SoundID.DD2_BetsySummon, vector8);
                        }
                    }
                    List<NPC> list = new List<NPC>();
                    for (int n = 0; n < 200; n++)
                    {
                        NPC nPC = Main.npc[n];
                        if (nPC.active && nPC.type == 549)
{
                            list.Add(nPC);
                        }
                    }
                    if (list.Count > 0)
                    {
                        for (int num40 = 0; num40 < 3; num40++)
{
                            NPC nPC2 = list[Main.rand.Next(list.Count)];
                            Point point3 = nPC2.Center.ToPoint();
                            NewNPC(GetSpawnSourceForNPCFromNPCAI(), point3.X, point3.Y, 560);
                            SoundEngine.PlayTrackedSound(in SoundID.DD2_BetsySummon, nPC2.Center);
                        }
                    }
                }
                ai[1] += 1f;
            }
            if (ai[1] >= num22)
            {
                ai[0] = 1f;
                ai[1] = 0f;
                ai[2] = 0f;
            }
        }
        localAI[0] += num12;
        if (localAI[0] >= 36f)
        {
            localAI[0] = 0f;
        }
        if (num != -1)
        {
            localAI[0] = num * 4;
        }
        if ((localAI[1] += 1f) >= 60f)
        {
            localAI[1] = 0f;
        }
        float num41 = DirectionTo(targetData.Center).ToRotation();
        float num42 = 0.04f;
        switch ((int)ai[0])
        {
        case 2:
        case 5:
            num42 = 0f;
            break;
        case 3:
            num42 = 0.01f;
            num41 = 0f;
            if (spriteDirection == -1)
            {
                num41 -= (float)Math.PI;
            }
            if (ai[1] >= num5)
            {
                num41 += (float)spriteDirection * (float)Math.PI / 12f;
                num42 = 0.05f;
            }
            break;
        case 4:
            num42 = 0.01f;
            num41 = (float)Math.PI;
            if (spriteDirection == 1)
            {
                num41 += (float)Math.PI;
            }
            break;
        case 6:
            num42 = 0.02f;
            num41 = 0f;
            if (spriteDirection == -1)
            {
                num41 -= (float)Math.PI;
            }
            break;
        }
        if (spriteDirection == -1)
        {
            num41 += (float)Math.PI;
        }
        if (num42 != 0f)
        {
            rotation = rotation.AngleTowards(num41, num42);
        }
        if (SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[2])) == null)
        {
            localAI[2] = SlotId.Invalid.ToFloat();
        }
    }
References Terraria.NPC.ai, Terraria.NPC.CountNPCS(), Terraria.ID.SoundID.DD2_BetsyFlameBreath, Terraria.ID.SoundID.DD2_BetsyFlyingCircleAttack, Terraria.ID.SoundID.DD2_BetsyScream, Terraria.ID.SoundID.DD2_BetsySummon, Terraria.ID.SoundID.DD2_BetsyWindAttack, Terraria.Entity.direction, Terraria.Entity.DirectionTo(), Terraria.Entity.Distance(), Terraria.Main.dust, Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.NPC.GetTargetData(), Terraria.Framing.GetTileSafely(), Terraria.WorldGen.KillTile_GetTileDustAmount(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.NPC.localAI, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.Gore.NewGoreDirect(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Utils.RotatedBy(), Terraria.NPC.rotation, Terraria.NPC.SimpleFlyMovement(), Terraria.NPC.spriteDirection, Terraria.Utilities.NPCUtils.TargetClosestBetsy(), Terraria.Main.tileFrameImportant, Terraria.Main.tileSolid, Terraria.NPC.value, Terraria.Entity.velocity, and Terraria.Entity.whoAmI.
Referenced by Terraria.NPC.VanillaAI_Inner().