TModLoader: Terraria.NPC.AI_123_Deerclops
AI_123_Deerclops()
void Terraria.NPC.AI_123_Deerclops () inline private
Definition at line 44403 of file NPC.cs.
    {
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_0137: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00de: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_0445: Unknown result type (might be due to invalid IL or missing references)
        //IL_0454: Unknown result type (might be due to invalid IL or missing references)
        //IL_0459: Unknown result type (might be due to invalid IL or missing references)
        //IL_045e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0461: Unknown result type (might be due to invalid IL or missing references)
        //IL_0466: Unknown result type (might be due to invalid IL or missing references)
        //IL_0468: Unknown result type (might be due to invalid IL or missing references)
        //IL_046d: Unknown result type (might be due to invalid IL or missing references)
        //IL_046e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0470: Unknown result type (might be due to invalid IL or missing references)
        //IL_0475: Unknown result type (might be due to invalid IL or missing references)
        //IL_0478: Unknown result type (might be due to invalid IL or missing references)
        //IL_047d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0482: Unknown result type (might be due to invalid IL or missing references)
        //IL_0493: Unknown result type (might be due to invalid IL or missing references)
        //IL_049f: Unknown result type (might be due to invalid IL or missing references)
        //IL_089f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a11: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b83: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_031b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0325: Unknown result type (might be due to invalid IL or missing references)
        //IL_0337: Unknown result type (might be due to invalid IL or missing references)
        //IL_0348: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a71: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ded: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e02: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cfb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_093c: Unknown result type (might be due to invalid IL or missing references)
        //IL_094b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0568: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e78: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0afa: Unknown result type (might be due to invalid IL or missing references)
        //IL_075d: Unknown result type (might be due to invalid IL or missing references)
        deerclopsBoss = whoAmI;
        int num = 15;
        NPCAimedTarget targetData = GetTargetData();
        bool haltMovement = false;
        bool goHome = false;
        bool flag = Distance(targetData.Center) >= 450f;
        localAI[3] = MathHelper.Clamp(localAI[3] + (float)flag.ToDirectionInt(), 0f, 30f);
        dontTakeDamage = localAI[3] >= 30f;
        float lifePercent = (float)life / (float)lifeMax;
        bool expertMode = Main.expertMode;
        int shadowHandDamage = 10;
        float num9 = Utils.Remap(localAI[3], 0f, 30f, 0f, 1f);
        if (num9 > 0f)
        {
            float num10 = Main.rand.NextFloat() * num9 * 3f;
            while (num10 > 0f)
            {
                num10 -= 1f;
                Dust.NewDustDirect(position, width, height, 109, 0f, -3f, 0, default(Color), 1.4f).noGravity = true;
            }
        }
        if (homeTileX == -1 && homeTileY == -1)
        {
            Point point = base.Bottom.ToTileCoordinates();
            homeTileX = point.X;
            homeTileY = point.Y;
            this.ai[2] = homeTileX;
            this.ai[3] = homeTileY;
            netUpdate = true;
            timeLeft = 86400;
        }
        timeLeft -= Main.worldEventUpdates;
        if (timeLeft < 0)
        {
            timeLeft = 0;
        }
        homeTileX = (int)this.ai[2];
        homeTileY = (int)this.ai[3];
        if (!expertMode)
        {
            localAI[2] = 0f;
        }
        if (expertMode && Main.netMode != 1)
        {
            SpawnPassiveShadowHands(lifePercent, shadowHandDamage);
        }
        Vector2 val2;
        switch ((int)this.ai[0])
        {
        case -1:
            localAI[3] = -10f;
            break;
        case 6:
        {
            TargetClosest(faceTarget: false);
            targetData = GetTargetData();
            if (Main.netMode != 1)
            {
                if (!ShouldRunAway(ref targetData, isChasing: false))
                {
                    this.ai[0] = 0f;
                    this.ai[1] = 0f;
                    localAI[1] = 0f;
                    netUpdate = true;
                    break;
                }
                if (timeLeft <= 0)
                {
                    this.ai[0] = 8f;
                    this.ai[1] = 0f;
                    localAI[1] = 0f;
                    netUpdate = true;
                    break;
                }
            }
            if (direction != oldDirection)
            {
                netUpdate = true;
            }
            goHome = true;
            this.ai[1] += 1f;
            Vector2 other = default(Vector2);
            ((Vector2)(ref other))._002Ector((float)(homeTileX * 16), (float)(homeTileY * 16));
            bool flag2 = base.Top.Y > other.Y + 1600f;
            bool num16 = Distance(other) < 1020f;
            Distance(targetData.Center);
            float num11 = this.ai[1] % 600f;
            if (num16 && num11 < 420f)
            {
                haltMovement = true;
            }
            bool flag3 = false;
            int num12 = 300;
            if (flag2 && this.ai[1] >= (float)num12)
            {
                flag3 = true;
            }
            int num13 = 1500;
            if (!num16 && this.ai[1] >= (float)num13)
            {
                flag3 = true;
            }
            if (flag3)
            {
                this.ai[0] = 7f;
                this.ai[1] = 0f;
                localAI[1] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 0:
        {
            TargetClosest();
            targetData = GetTargetData();
            if (ShouldRunAway(ref targetData, isChasing: true))
            {
                this.ai[0] = 6f;
                this.ai[1] = 0f;
                localAI[1] = 0f;
                netUpdate = true;
                break;
            }
            this.ai[1] += 1f;
            Vector2 vector = base.Bottom + new Vector2(0f, -32f);
            Vector2 val = targetData.Hitbox.ClosestPointInRect(vector);
            Vector2 vector2 = val - vector;
            val2 = val - base.Center;
            ((Vector2)(ref val2)).Length();
            float num6 = 0.6f;
            bool flag4 = Math.Abs(vector2.X) >= Math.Abs(vector2.Y) * num6 || ((Vector2)(ref vector2)).Length() < 48f;
            bool flag5 = vector2.Y <= (float)(100 + targetData.Height) && vector2.Y >= -200f;
            if (Math.Abs(vector2.X) < 120f && flag5 && velocity.Y == 0f && localAI[1] >= 2f)
            {
                velocity.X = 0f;
                this.ai[0] = 4f;
                this.ai[1] = 0f;
                localAI[1] = 0f;
                netUpdate = true;
                break;
            }
            if (Math.Abs(vector2.X) < 120f && flag5 && velocity.Y == 0f && flag4)
            {
                velocity.X = 0f;
                this.ai[0] = 1f;
                this.ai[1] = 0f;
                localAI[1] += 1f;
                netUpdate = true;
                break;
            }
            bool flag6 = this.ai[1] >= 240f;
            if (velocity.Y == 0f && velocity.X != 0f && flag6)
            {
                velocity.X = 0f;
                this.ai[0] = 2f;
                this.ai[1] = 0f;
                localAI[1] = 0f;
                netUpdate = true;
                break;
            }
            bool flag7 = this.ai[1] >= 90f;
            if (velocity.Y == 0f && velocity.X == 0f && flag7)
            {
                velocity.X = 0f;
                this.ai[0] = 5f;
                this.ai[1] = 0f;
                localAI[1] = 0f;
                netUpdate = true;
                break;
            }
            bool flag8 = this.ai[1] >= 120f;
            int num7 = 32;
            bool flag9 = targetData.Type == NPCTargetType.Player && !Main.player[target].buffImmune[num7] && Main.player[target].FindBuffIndex(num7) == -1;
            if (velocity.Y == 0f && flag8 && flag9 && Math.Abs(vector2.X) > 100f)
            {
                velocity.X = 0f;
                this.ai[0] = 3f;
                this.ai[1] = 0f;
                localAI[1] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 1:
            this.ai[1] += 1f;
            haltMovement = true;
            AI_123_Deerclops_MakeSpikesForward(1, targetData);
            if (this.ai[1] >= 80f)
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        case 4:
            this.ai[1] += 1f;
            haltMovement = true;
            TargetClosest();
            AI_123_Deerclops_MakeSpikesBothSides(1, targetData);
            if (this.ai[1] >= 90f)
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        case 2:
        {
            int num14 = 4;
            int num15 = 8 * num14;
            this.ai[1] += 1f;
            if (this.ai[1] == (float)(num15 - 20))
            {
                SoundEngine.PlaySound(in SoundID.DeerclopsScream, base.Center);
            }
            if (this.ai[1] == (float)num15)
            {
                SoundEngine.PlaySound(in SoundID.DeerclopsRubbleAttack, base.Center);
            }
            haltMovement = true;
            if (Main.netMode != 1 && this.ai[1] >= (float)num15)
            {
                Point sourceTileCoords = base.Top.ToTileCoordinates();
                int num2 = 20;
                int distancedByThisManyTiles = 1;
                float upBiasPerSpike = 200f;
                sourceTileCoords.X += direction * 3;
                sourceTileCoords.Y -= 10;
                int num17 = (int)this.ai[1] - num15;
                if (num17 == 0)
                {
                    PunchCameraModifier modifier4 = new PunchCameraModifier(base.Center, new Vector2(0f, -1f), 20f, 6f, 30, 1000f, "Deerclops");
                    Main.instance.CameraModifiers.Add(modifier4);
                }
                int num3 = 1;
                int num4 = num17 / num3 * num3;
                int num5 = num4 + num3;
                if (num17 % num3 != 0)
                {
                    num5 = num4;
                }
                for (int j = num4; j < num5 && j < num2; j++)
                {
                    AI_123_Deerclops_ShootRubbleUp(ref targetData, ref sourceTileCoords, num2, distancedByThisManyTiles, upBiasPerSpike, j);
                }
            }
            if (this.ai[1] >= 60f)
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        }
        case 3:
            if (this.ai[1] == 30f)
            {
                SoundEngine.PlaySound(in SoundID.DeerclopsScream, base.Center);
            }
            this.ai[1] += 1f;
            haltMovement = true;
            if ((int)this.ai[1] % 4 == 0 && this.ai[1] >= 28f)
            {
                PunchCameraModifier modifier5 = new PunchCameraModifier(base.Center, (Main.rand.NextFloat() * ((float)Math.PI * 2f)).ToRotationVector2(), 20f, 6f, 20, 1000f, "Deerclops");
                Main.instance.CameraModifiers.Add(modifier5);
                if (Main.netMode != 2)
                {
                    Player player = Main.player[Main.myPlayer];
                    _ = Main.myPlayer;
                    int num8 = 32;
                    int timeToAdd = 720;
                    if (!player.dead && player.active && player.FindBuffIndex(num8) == -1)
                    {
                        val2 = player.Center - base.Center;
                        if (((Vector2)(ref val2)).Length() < 800f && !player.creativeGodMode)
{
                            player.AddBuff(num8, timeToAdd);
                        }
                    }
                }
            }
            if (this.ai[1] == 30f)
            {
                TargetClosest();
            }
            if (this.ai[1] >= 60f)
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        case 7:
            if (this.ai[1] == 30f)
            {
                SoundEngine.PlaySound(in SoundID.DeerclopsScream, base.Center);
            }
            this.ai[1] += 1f;
            haltMovement = true;
            if ((int)this.ai[1] % 4 == 0 && this.ai[1] >= 28f)
            {
                PunchCameraModifier modifier3 = new PunchCameraModifier(base.Center, (Main.rand.NextFloat() * ((float)Math.PI * 2f)).ToRotationVector2(), 20f, 6f, 20, 1000f, "Deerclops");
                Main.instance.CameraModifiers.Add(modifier3);
            }
            if (this.ai[1] == 40f)
            {
                TargetClosest();
                if (Main.netMode != 1)
                {
                    netUpdate = true;
                    base.Bottom = new Vector2((float)(homeTileX * 16), (float)(homeTileY * 16));
                }
            }
            if (this.ai[1] >= 60f)
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        case 8:
            if (this.ai[1] == 30f)
            {
                SoundEngine.PlaySound(in SoundID.DeerclopsScream, base.Center);
            }
            this.ai[1] += 1f;
            haltMovement = true;
            if ((int)this.ai[1] % 4 == 0 && this.ai[1] >= 28f)
            {
                PunchCameraModifier modifier2 = new PunchCameraModifier(base.Center, (Main.rand.NextFloat() * ((float)Math.PI * 2f)).ToRotationVector2(), 20f, 6f, 20, 1000f, "Deerclops");
                Main.instance.CameraModifiers.Add(modifier2);
            }
            if (this.ai[1] >= 40f)
            {
                life = -1;
                HitEffect();
                active = false;
                if (Main.netMode != 1)
                {
                    NetMessage.SendData(28, -1, -1, null, whoAmI, -1f);
                }
                return;
            }
            break;
        case 5:
            if (this.ai[1] == 30f)
            {
                SoundEngine.PlaySound(in SoundID.DeerclopsScream, base.Center);
            }
            this.ai[1] += 1f;
            haltMovement = true;
            if ((int)this.ai[1] % 4 == 0 && this.ai[1] >= 28f)
            {
                PunchCameraModifier modifier = new PunchCameraModifier(base.Center, (Main.rand.NextFloat() * ((float)Math.PI * 2f)).ToRotationVector2(), 20f, 6f, 20, 1000f, "Deerclops");
                Main.instance.CameraModifiers.Add(modifier);
            }
            if (this.ai[1] == 30f)
            {
                TargetClosest();
                if (Main.netMode != 1)
                {
                    for (int i = 0; i < 6; i++)
                    {
                        Projectile.RandomizeInsanityShadowFor(Main.player[target], isHostile: true, out var spawnposition, out var spawnvelocity, out var ai, out var ai2);
                        Projectile.NewProjectile(GetSpawnSource_ForProjectile(), spawnposition, spawnvelocity, 965, num, 0f, Main.myPlayer, ai, ai2);
                    }
                }
            }
            if (this.ai[1] >= 60f)
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                netUpdate = true;
            }
            break;
        }
        AI_123_Deerclops_Movement(haltMovement, goHome);
    }
References Terraria.Entity.active, Terraria.Player.AddBuff(), Terraria.NPC.ai, Terraria.NPC.AI_123_Deerclops_MakeSpikesBothSides(), Terraria.NPC.AI_123_Deerclops_MakeSpikesForward(), Terraria.NPC.AI_123_Deerclops_Movement(), Terraria.NPC.AI_123_Deerclops_ShootRubbleUp(), Terraria.Player.creativeGodMode, Terraria.Player.dead, Terraria.NPC.deerclopsBoss, Terraria.ID.SoundID.DeerclopsRubbleAttack, Terraria.ID.SoundID.DeerclopsScream, Terraria.Entity.direction, Terraria.Entity.Distance(), Terraria.NPC.dontTakeDamage, Terraria.Main.expertMode, Terraria.Player.FindBuffIndex(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetTargetData(), Terraria.Entity.height, Terraria.NPC.HitEffect(), Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Terraria.Main.instance, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.Dust.NewDustDirect(), Terraria.Projectile.NewProjectile(), Terraria.NPC.noGravity, Terraria.Entity.oldDirection, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Projectile.RandomizeInsanityShadowFor(), Terraria.Utils.Remap(), Terraria.NetMessage.SendData(), Terraria.NPC.ShouldRunAway(), Terraria.NPC.SpawnPassiveShadowHands(), Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.NPC.timeLeft, Terraria.Entity.velocity, Terraria.Entity.whoAmI, Terraria.Entity.width, and Terraria.Main.worldEventUpdates.
Referenced by Terraria.NPC.VanillaAI_Inner().