TModLoader: Terraria.NPC.GetFairyTreasureCoords
GetFairyTreasureCoords()
bool Terraria.NPC.GetFairyTreasureCoords (out Point treasureCoords) inline private
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        treasureCoords = default(Point);
        Point point = base.Center.ToTileCoordinates();
        Rectangle value = default(Rectangle);
        ((Rectangle)(ref value))._002Ector(point.X, point.Y, 1, 1);
        ((Rectangle)(ref value)).Inflate(75, 50);
        int num = 40;
        Rectangle value2 = default(Rectangle);
        ((Rectangle)(ref value2))._002Ector(0, 0, Main.maxTilesX, Main.maxTilesY);
        ((Rectangle)(ref value2)).Inflate(-num, -num);
        value = Rectangle.Intersect(value, value2);
        int num2 = -1;
        float num3 = -1f;
        for (int i = ((Rectangle)(ref value)).Left; i <= ((Rectangle)(ref value)).Right; i++)
        {
            for (int j = ((Rectangle)(ref value)).Top; j <= ((Rectangle)(ref value)).Bottom; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile == null || !tile.active() || !TileID.Sets.FriendlyFairyCanLureTo[tile.type] || !SceneMetrics.IsValidForOreFinder(tile))
                {
                    continue;
                }
                short num4 = Main.tileOreFinderPriority[tile.type];
                if (TileID.Sets.Ore[tile.type])
                {
                    int num5 = 3;
                    int num6 = 3;
                    int num7 = 40;
                    int num8 = 0;
                    for (int k = i - num5; k <= i + num5; k++)
                    {
                        for (int l = j - num6; l <= j + num6; l++)
{
                            if (Main.tile[k, l].active() && Main.tile[k, l].type == tile.type)
{
                                num8++;
                            }
                        }
                    }
                    if (num8 < num7)
                    {
                        num4 = -1;
                    }
                }
                if (num2 <= num4)
                {
                    float num9 = Distance(new Vector2((float)(i * 16 + 8), (float)(j * 16 + 8)));
                    if (num2 != num4 || !(num9 >= num3))
                    {
                        num2 = num4;
                        num3 = num9;
                        treasureCoords.X = i;
                        treasureCoords.Y = j;
                    }
                }
            }
        }
        return num2 != -1;
    }
References Terraria.Tile.active(), Terraria.Entity.Bottom, Terraria.Entity.Distance(), Terraria.ID.TileID.Sets.FriendlyFairyCanLureTo, Terraria.SceneMetrics.IsValidForOreFinder(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.ID.TileID.Sets.Ore, Terraria.Entity.Right, Terraria.Main.tile, Terraria.Main.tileOreFinderPriority, Terraria.Tile.type, and Terraria.NPC.value.
Referenced by Terraria.NPC.AI_112_FairyCritter().