TModLoader: Terraria.NPC.UpdateNPC_BuffApplyDOTs
UpdateNPC_BuffApplyDOTs()
void Terraria.NPC.UpdateNPC_BuffApplyDOTs () inline private
Definition at line 108598 of file NPC.cs.
    {
        //IL_089a: Unknown result type (might be due to invalid IL or missing references)
        //IL_089f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0793: Unknown result type (might be due to invalid IL or missing references)
        //IL_0798: Unknown result type (might be due to invalid IL or missing references)
        if (dontTakeDamage)
        {
            return;
        }
        int num = lifeRegenExpectedLossPerSecond;
        if (poisoned)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegen -= 12;
        }
        if (onFire)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegen -= 8;
        }
        if (onFire3)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegen -= 30;
            if (num < 5)
            {
                num = 5;
            }
        }
        if (onFrostBurn)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegen -= 16;
            if (num < 2)
            {
                num = 2;
            }
        }
        if (onFrostBurn2)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegen -= 50;
            if (num < 10)
            {
                num = 10;
            }
        }
        if (onFire2)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegen -= 48;
            if (num < 10)
            {
                num = 10;
            }
        }
        if (venom)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegen -= 60;
            if (num < 15)
            {
                num = 15;
            }
        }
        if (shadowFlame)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegen -= 30;
            if (num < 5)
            {
                num = 5;
            }
        }
        if (oiled && (onFire || onFire2 || onFire3 || onFrostBurn || onFrostBurn2 || shadowFlame))
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegen -= 50;
            if (num < 10)
            {
                num = 10;
            }
        }
        if (javelined)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            int num7 = 0;
            int num8 = 1;
            for (int i = 0; i < 1000; i++)
            {
                if (Main.projectile[i].active && Main.projectile[i].type == 598 && Main.projectile[i].ai[0] == 1f && Main.projectile[i].ai[1] == (float)whoAmI)
                {
                    num7++;
                }
            }
            lifeRegen -= num7 * 2 * 3;
            if (num < num7 * 3 / num8)
            {
                num = num7 * 3 / num8;
            }
        }
        if (tentacleSpiked)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            int num9 = 0;
            int num10 = 1;
            for (int j = 0; j < 1000; j++)
            {
                if (Main.projectile[j].active && Main.projectile[j].type == 971 && Main.projectile[j].ai[0] == 1f && Main.projectile[j].ai[1] == (float)whoAmI)
                {
                    num9++;
                }
            }
            lifeRegen -= num9 * 2 * 3;
            if (num < num9 * 3 / num10)
            {
                num = num9 * 3 / num10;
            }
        }
        if (bloodButchered)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            int num11 = 0;
            int num12 = 1;
            for (int k = 0; k < 1000; k++)
            {
                if (Main.projectile[k].active && Main.projectile[k].type == 975 && Main.projectile[k].ai[0] == 1f && Main.projectile[k].ai[1] == (float)whoAmI)
                {
                    num11++;
                }
            }
            lifeRegen -= num11 * 2 * 4;
            if (num < num11 * 4 / num12)
            {
                num = num11 * 4 / num12;
            }
        }
        if (daybreak)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            int num13 = 0;
            int num14 = 4;
            for (int l = 0; l < 1000; l++)
            {
                if (Main.projectile[l].active && Main.projectile[l].type == 636 && Main.projectile[l].ai[0] == 1f && Main.projectile[l].ai[1] == (float)whoAmI)
                {
                    num13++;
                }
            }
            if (num13 == 0)
            {
                num13 = 1;
            }
            lifeRegen -= num13 * 2 * 100;
            if (num < num13 * 100 / num14)
            {
                num = num13 * 100 / num14;
            }
        }
        if (celled)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            int num2 = 0;
            for (int m = 0; m < 1000; m++)
            {
                if (Main.projectile[m].active && Main.projectile[m].type == 614 && Main.projectile[m].ai[0] == 1f && Main.projectile[m].ai[1] == (float)whoAmI)
                {
                    num2++;
                }
            }
            lifeRegen -= num2 * 2 * 20;
            if (num < num2 * 20)
            {
                num = num2 * 20 / 2;
            }
        }
        if (dryadBane)
        {
            int num3 = 4;
            float num4 = 1f;
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            if (downedBoss1)
            {
                num4 += 0.1f;
            }
            if (downedBoss2)
            {
                num4 += 0.1f;
            }
            if (downedBoss3)
            {
                num4 += 0.1f;
            }
            if (downedQueenBee)
            {
                num4 += 0.1f;
            }
            if (Main.hardMode)
            {
                num4 += 0.4f;
            }
            if (downedMechBoss1)
            {
                num4 += 0.15f;
            }
            if (downedMechBoss2)
            {
                num4 += 0.15f;
            }
            if (downedMechBoss3)
            {
                num4 += 0.15f;
            }
            if (downedPlantBoss)
            {
                num4 += 0.15f;
            }
            if (downedGolemBoss)
            {
                num4 += 0.15f;
            }
            if (downedAncientCultist)
            {
                num4 += 0.15f;
            }
            if (Main.expertMode)
            {
                num4 *= Main.GameModeInfo.TownNPCDamageMultiplier;
            }
            num3 = (int)((float)num3 * num4);
            lifeRegen -= 2 * num3;
            if (num < num3)
            {
                num = num3 / 3;
            }
        }
        if (soulDrain && realLife == -1)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegen -= 50;
            if (num < 5)
            {
                num = 5;
            }
        }
        NPCLoader.UpdateLifeRegen(this, ref num);
        if (lifeRegen <= -240 && num < 2)
        {
            num = 2;
        }
        lifeRegenCount += lifeRegen;
        while (lifeRegenCount >= 120)
        {
            lifeRegenCount -= 120;
            if (!immortal)
            {
                if (life < lifeMax)
                {
                    life++;
                }
                if (life > lifeMax)
                {
                    life = lifeMax;
                }
            }
        }
        if (num > 0)
        {
            while (lifeRegenCount <= -120 * num)
            {
                lifeRegenCount += 120 * num;
                int num5 = whoAmI;
                if (realLife >= 0)
                {
                    num5 = realLife;
                }
                if (!Main.npc[num5].immortal)
                {
                    Main.npc[num5].life -= num;
                }
                CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegenNegative, num, dramatic: false, dot: true);
                if (Main.npc[num5].life > 0 || Main.npc[num5].immortal)
                {
                    continue;
                }
                Main.npc[num5].life = 1;
                if (Main.netMode != 1)
                {
                    Main.npc[num5].StrikeNPCNoInteraction(9999, 0f, 0);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(28, -1, -1, null, num5, 9999f);
                    }
                }
            }
            return;
        }
        while (lifeRegenCount <= -120)
        {
            lifeRegenCount += 120;
            int num6 = whoAmI;
            if (realLife >= 0)
            {
                num6 = realLife;
            }
            if (!Main.npc[num6].immortal)
            {
                Main.npc[num6].life--;
            }
            CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegenNegative, 1, dramatic: false, dot: true);
            if (Main.npc[num6].life > 0 || Main.npc[num6].immortal)
            {
                continue;
            }
            Main.npc[num6].life = 1;
            if (Main.netMode != 1)
            {
                Main.npc[num6].StrikeNPCNoInteraction(9999, 0f, 0);
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(28, -1, -1, null, num6, 9999f);
                }
            }
        }
    }
References Terraria.Main.expertMode, Terraria.Main.GameModeInfo, Terraria.Main.hardMode, Terraria.CombatText.LifeRegenNegative, Terraria.Main.netMode, Terraria.CombatText.NewText(), Terraria.Main.npc, Terraria.Main.projectile, Terraria.NetMessage.SendData(), and Terraria.ModLoader.NPCLoader.UpdateLifeRegen().