TModLoader: Terraria.NPC.Collision_WaterCollision
Collision_WaterCollision()
bool Terraria.NPC.Collision_WaterCollision (bool lava) inline private
Definition at line 110269 of file NPC.cs.
    {
        //IL_08ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f90: Unknown result type (might be due to invalid IL or missing references)
        //IL_0faf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0781: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c20: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c42: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c48: Unknown result type (might be due to invalid IL or missing references)
        //IL_0401: Unknown result type (might be due to invalid IL or missing references)
        //IL_0423: Unknown result type (might be due to invalid IL or missing references)
        //IL_0429: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a71: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a94: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0253: Unknown result type (might be due to invalid IL or missing references)
        //IL_0258: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_027a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0297: Unknown result type (might be due to invalid IL or missing references)
        //IL_029c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ada: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        bool flag = false;
        if (type == 72 || aiStyle == 21 || aiStyle == 67 || type == 376 || type == 579 || type == 541 || (aiStyle == 7 && ai[0] == 25f))
        {
            flag = false;
            wetCount = 0;
            lava = false;
        }
        else
        {
            flag = Collision.WetCollision(position, width, height);
            if (Collision.honey)
            {
                honeyWet = true;
            }
            if (Collision.shimmer)
            {
                shimmerWet = true;
                AddBuff(353, 100);
            }
        }
        if (aiStyle == 116)
        {
            wetCount = 10;
        }
        if (flag)
        {
            if (onFire && !lavaWet && Main.netMode != 1)
            {
                for (int i = 0; i < maxBuffs; i++)
                {
                    if (buffType[i] == 24)
                    {
                        DelBuff(i);
                    }
                }
            }
            if (!wet && wetCount == 0)
            {
                wetCount = 10;
                if (!lava)
                {
                    if (shimmerWet)
                    {
                        if (type != 617 && type != 616 && type != 625)
{
                            for (int j = 0; j < 30; j++)
{
                                int num = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 308);
                                Main.dust[num].velocity.Y -= 4f;
                                Main.dust[num].velocity.X *= 2.5f;
                                Main.dust[num].scale = 0.8f;
                                Main.dust[num].noGravity = true;
                                switch (Main.rand.Next(6))
{
                                case 0:
                                    Main.dust[num].color = new Color(255, 255, 210);
                                    break;
                                case 1:
                                    Main.dust[num].color = new Color(190, 245, 255);
                                    break;
                                case 2:
                                    Main.dust[num].color = new Color(255, 150, 255);
                                    break;
                                default:
                                    Main.dust[num].color = new Color(190, 175, 255);
                                    break;
                                }
                            }
                            if ((type != 376 && type != 579 && aiStyle != 1 && type != 1 && type != 16 && type != 147 && type != 59 && type != 300 && aiStyle != 39 && aiStyle != 68 && type != 362 && type != 364 && type != 361 && type != 445 && !noGravity) || type == 615)
{
                                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 4);
                            }
                        }
                    }
                    else if (honeyWet)
                    {
                        for (int k = 0; k < 10; k++)
{
                            int num4 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 152);
                            Main.dust[num4].velocity.Y -= 1f;
                            Main.dust[num4].velocity.X *= 2.5f;
                            Main.dust[num4].scale = 1.3f;
                            Main.dust[num4].alpha = 100;
                            Main.dust[num4].noGravity = true;
                        }
                        if (aiStyle != 1 && type != 1 && type != 16 && type != 147 && type != 59 && type != 300 && aiStyle != 39 && !noGravity)
{
                            SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                        }
                    }
                    else if (type != 617 && type != 616 && type != 625)
                    {
                        for (int l = 0; l < 30; l++)
{
                            int num5 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, Dust.dustWater());
                            Main.dust[num5].velocity.Y -= 4f;
                            Main.dust[num5].velocity.X *= 2.5f;
                            Main.dust[num5].scale *= 0.8f;
                            Main.dust[num5].alpha = 100;
                            Main.dust[num5].noGravity = true;
                        }
                        if ((type != 376 && type != 579 && aiStyle != 1 && type != 1 && type != 16 && type != 147 && type != 59 && type != 300 && aiStyle != 39 && aiStyle != 68 && type != 362 && type != 364 && type != 361 && type != 445 && !noGravity) || type == 615)
{
                            SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 0);
                        }
                    }
                }
                else
                {
                    for (int m = 0; m < 10; m++)
                    {
                        int num6 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 35);
                        Main.dust[num6].velocity.Y -= 1.5f;
                        Main.dust[num6].velocity.X *= 2.5f;
                        Main.dust[num6].scale = 1.3f;
                        Main.dust[num6].alpha = 100;
                        Main.dust[num6].noGravity = true;
                    }
                    if (aiStyle != 1 && type != 1 && type != 16 && type != 147 && type != 59 && type != 300 && aiStyle != 39 && !noGravity)
                    {
                        SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                    }
                }
            }
            wet = true;
        }
        else if (wet)
        {
            velocity.X *= 0.5f;
            wet = false;
            if (type == 620 && GetTargetData().Center.Y < base.Center.Y)
            {
                velocity.Y -= 8f;
            }
            if (wetCount == 0)
            {
                wetCount = 10;
                if (!lavaWet)
                {
                    if (shimmerWet)
                    {
                        if (type != 617 && type != 616 && type != 625)
{
                            for (int n = 0; n < 30; n++)
{
                                int num7 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 308);
                                Main.dust[num7].velocity.Y -= 4f;
                                Main.dust[num7].velocity.X *= 2.5f;
                                Main.dust[num7].scale = 0.8f;
                                Main.dust[num7].noGravity = true;
                                switch (Main.rand.Next(6))
{
                                case 0:
                                    Main.dust[num7].color = new Color(255, 255, 210);
                                    break;
                                case 1:
                                    Main.dust[num7].color = new Color(190, 245, 255);
                                    break;
                                case 2:
                                    Main.dust[num7].color = new Color(255, 150, 255);
                                    break;
                                default:
                                    Main.dust[num7].color = new Color(190, 175, 255);
                                    break;
                                }
                            }
                            if ((type != 376 && type != 579 && aiStyle != 1 && type != 1 && type != 16 && type != 147 && type != 59 && type != 300 && aiStyle != 39 && aiStyle != 68 && type != 362 && type != 364 && type != 361 && type != 445 && !noGravity) || type == 615)
{
                                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 5);
                            }
                        }
                    }
                    else if (honeyWet)
                    {
                        for (int num8 = 0; num8 < 10; num8++)
{
                            int num9 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 152);
                            Main.dust[num9].velocity.Y -= 1f;
                            Main.dust[num9].velocity.X *= 2.5f;
                            Main.dust[num9].scale = 1.3f;
                            Main.dust[num9].alpha = 100;
                            Main.dust[num9].noGravity = true;
                        }
                        if (aiStyle != 1 && type != 1 && type != 16 && type != 147 && type != 300 && type != 59 && aiStyle != 39 && !noGravity)
{
                            SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                        }
                    }
                    else if (type != 617 && type != 616 && type != 625)
                    {
                        for (int num10 = 0; num10 < 30; num10++)
{
                            int num11 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, Dust.dustWater());
                            Main.dust[num11].velocity.Y -= 4f;
                            Main.dust[num11].velocity.X *= 2.5f;
                            Main.dust[num11].scale *= 0.8f;
                            Main.dust[num11].alpha = 100;
                            Main.dust[num11].noGravity = true;
                        }
                        if ((type != 376 && type != 579 && aiStyle != 1 && type != 1 && type != 16 && type != 59 && type != 300 && aiStyle != 39 && aiStyle != 68 && type != 362 && type != 364 && type != 361 && type != 445 && !noGravity) || type == 615)
{
                            SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 0);
                        }
                    }
                }
                else
                {
                    for (int num2 = 0; num2 < 10; num2++)
                    {
                        int num3 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 35);
                        Main.dust[num3].velocity.Y -= 1.5f;
                        Main.dust[num3].velocity.X *= 2.5f;
                        Main.dust[num3].scale = 1.3f;
                        Main.dust[num3].alpha = 100;
                        Main.dust[num3].noGravity = true;
                    }
                    if (aiStyle != 1 && type != 1 && type != 16 && type != 59 && type != 300 && aiStyle != 39 && !noGravity)
                    {
                        SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                    }
                }
            }
        }
        return lava;
    }
References Terraria.Main.dust, Terraria.Dust.dustWater(), Terraria.Collision.honey, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Collision.shimmer, and Terraria.Collision.WetCollision().