TModLoader: Terraria.ModLoader.EquipLoader.GetEquipSlot
GetEquipSlot()
static int Terraria.ModLoader.EquipLoader.GetEquipSlot (Mod mod, string name, EquipType type) inline static
Gets the slot/ID of the equipment texture corresponding to the given name. Returns -1 if no EquipTexture with the given name is found.
Parameters
mod The mod the equipment texture is from.
name The name.
type
Returns
    {
        return GetEquipTexture(mod, name, type)?.Slot ?? (-1);
    }
References Terraria.ModLoader.EquipLoader.GetEquipTexture().
Referenced by Terraria.ModLoader.Default.Patreon.MayneWingLayer.GetDefaultVisibility(), Terraria.ModLoader.Default.Patreon.xAqultFaceLayer.GetDefaultVisibility(), Terraria.ModLoader.Default.Patreon.xAqultWingLayer.GetDefaultVisibility(), Terraria.ModLoader.Default.Developer.Jofairden.Jofairden_Head.IsVanitySet(), Terraria.ModLoader.Default.Patreon.Guildpack_Head.IsVanitySet(), Terraria.ModLoader.Default.Patreon.HER0zero_Body.IsVanitySet(), Terraria.ModLoader.Default.Patreon.Orian_Head.IsVanitySet(), Terraria.ModLoader.Default.Patreon.Saethar_Head.IsVanitySet(), Terraria.ModLoader.Default.Patreon.FrostyPlayer.ModifyDrawInfo(), Terraria.ModLoader.Default.Patreon.xAqultPlayer.ModifyDrawInfo(), and Terraria.ModLoader.Default.Patreon.xAqult_Lens.SetStaticDefaults().