TModLoader: Terraria.ModLoader.EquipLoader.ResizeAndFillArrays
ResizeAndFillArrays()
static void Terraria.ModLoader.EquipLoader.ResizeAndFillArrays () inline static package
    {
        Array.Resize(ref TextureAssets.ArmorHead, nextEquip[EquipType.Head]);
        Array.Resize(ref TextureAssets.ArmorBody, nextEquip[EquipType.Body]);
        Array.Resize(ref TextureAssets.ArmorBodyComposite, nextEquip[EquipType.Body]);
        Array.Resize(ref TextureAssets.FemaleBody, nextEquip[EquipType.Body]);
        Array.Resize(ref TextureAssets.ArmorArm, nextEquip[EquipType.Body]);
        Array.Resize(ref TextureAssets.ArmorLeg, nextEquip[EquipType.Legs]);
        Array.Resize(ref TextureAssets.AccHandsOn, nextEquip[EquipType.HandsOn]);
        Array.Resize(ref TextureAssets.AccHandsOnComposite, nextEquip[EquipType.HandsOn]);
        Array.Resize(ref TextureAssets.AccHandsOff, nextEquip[EquipType.HandsOff]);
        Array.Resize(ref TextureAssets.AccHandsOffComposite, nextEquip[EquipType.HandsOff]);
        Array.Resize(ref TextureAssets.AccBack, nextEquip[EquipType.Back]);
        Array.Resize(ref TextureAssets.AccFront, nextEquip[EquipType.Front]);
        Array.Resize(ref TextureAssets.AccShoes, nextEquip[EquipType.Shoes]);
        Array.Resize(ref TextureAssets.AccWaist, nextEquip[EquipType.Waist]);
        Array.Resize(ref TextureAssets.Wings, nextEquip[EquipType.Wings]);
        Array.Resize(ref TextureAssets.AccShield, nextEquip[EquipType.Shield]);
        Array.Resize(ref TextureAssets.AccNeck, nextEquip[EquipType.Neck]);
        Array.Resize(ref TextureAssets.AccFace, nextEquip[EquipType.Face]);
        Array.Resize(ref TextureAssets.AccBeard, nextEquip[EquipType.Beard]);
        Array.Resize(ref TextureAssets.AccBalloon, nextEquip[EquipType.Balloon]);
        LoaderUtils.ResetStaticMembers(typeof(ArmorIDs));
        WingStatsInitializer.Load();
        EquipType[] equipTypes = EquipTypes;
        foreach (EquipType type in equipTypes)
        {
            foreach (KeyValuePair<int, EquipTexture> entry in equipTextures[type])
            {
                int slot = entry.Key;
                string texture = entry.Value.Texture;
                GetTextureArray(type)[slot] = ModContent.Request<Texture2D>(texture);
                switch (type)
                {
                case EquipType.Body:
                    ArmorIDs.Body.Sets.UsesNewFramingCode[slot] = true;
                    break;
                case EquipType.HandsOn:
                    ArmorIDs.HandOn.Sets.UsesNewFramingCode[slot] = true;
                    break;
                case EquipType.HandsOff:
                    ArmorIDs.HandOff.Sets.UsesNewFramingCode[slot] = true;
                    break;
                }
            }
        }
        ResizeAndRegisterType(EquipType.Head, ref Item.headType);
        ResizeAndRegisterType(EquipType.Body, ref Item.bodyType);
        ResizeAndRegisterType(EquipType.Legs, ref Item.legType);
        static void ResizeAndRegisterType(EquipType equipType, ref int[] typeArray)
        {
            Array.Resize(ref typeArray, nextEquip[equipType]);
            foreach (KeyValuePair<int, int> entry2 in slotToId[equipType])
            {
                typeArray[entry2.Key] = entry2.Value;
            }
        }
    }
References Terraria.GameContent.TextureAssets.AccBack, Terraria.GameContent.TextureAssets.AccBalloon, Terraria.GameContent.TextureAssets.AccBeard, Terraria.GameContent.TextureAssets.AccFace, Terraria.GameContent.TextureAssets.AccFront, Terraria.GameContent.TextureAssets.AccHandsOff, Terraria.GameContent.TextureAssets.AccHandsOffComposite, Terraria.GameContent.TextureAssets.AccHandsOn, Terraria.GameContent.TextureAssets.AccHandsOnComposite, Terraria.GameContent.TextureAssets.AccNeck, Terraria.GameContent.TextureAssets.AccShield, Terraria.GameContent.TextureAssets.AccShoes, Terraria.GameContent.TextureAssets.AccWaist, Terraria.GameContent.TextureAssets.ArmorArm, Terraria.GameContent.TextureAssets.ArmorBody, Terraria.GameContent.TextureAssets.ArmorBodyComposite, Terraria.GameContent.TextureAssets.ArmorHead, Terraria.GameContent.TextureAssets.ArmorLeg, Terraria.Item.bodyType, Terraria.ModLoader.EquipLoader.equipTextures, Terraria.ModLoader.EquipLoader.EquipTypes, Terraria.GameContent.TextureAssets.FemaleBody, Terraria.ModLoader.EquipLoader.GetTextureArray(), Terraria.Item.headType, Terraria.Item.legType, Terraria.Initializers.WingStatsInitializer.Load(), Terraria.ModLoader.EquipLoader.nextEquip, Terraria.ModLoader.Core.LoaderUtils.ResetStaticMembers(), Terraria.ModLoader.EquipLoader.slotToId, Terraria.ID.ArmorIDs.Body.Sets.UsesNewFramingCode, Terraria.ID.ArmorIDs.HandOn.Sets.UsesNewFramingCode, Terraria.ID.ArmorIDs.HandOff.Sets.UsesNewFramingCode, and Terraria.GameContent.TextureAssets.Wings.
Referenced by Terraria.ModLoader.ModContent.ResizeArrays().