TModLoader: Terraria.ModLoader.EquipLoader.EquipFrameEffects
EquipFrameEffects()
static void Terraria.ModLoader.EquipLoader.EquipFrameEffects (Player player) inline static
Hook Player.PlayerFrame Calls each of the item's equipment texture's FrameEffects hook.
    {
        EquipType[] equipTypes = EquipTypes;
        foreach (EquipType type in equipTypes)
        {
            int slot = GetPlayerEquip(player, type);
            GetEquipTexture(type, slot)?.FrameEffects(player, type);
        }
    }
References Terraria.ModLoader.EquipLoader.EquipTypes, Terraria.ModLoader.EquipTexture.FrameEffects(), Terraria.ModLoader.EquipLoader.GetEquipTexture(), and Terraria.ModLoader.EquipLoader.GetPlayerEquip().
Referenced by Terraria.ModLoader.CombinedHooks.PlayerFrameEffects().