TModLoader: Terraria.ModLoader.EquipLoader.AddEquipTexture
AddEquipTexture()
static int Terraria.ModLoader.EquipLoader.AddEquipTexture (Mod mod, string texture, EquipType type, ModItem item = null, string name = null, EquipTexture equipTexture = null) inline static
Adds an equipment texture of the specified type, internal name, and/or associated item to your mod.
If no internal name is provided, the associated item's name will be used instead.
You can then get the ID for your texture by calling EquipLoader.GetEquipTexture, and using the EquipTexture's Slot property.
If you need to override EquipmentTexture's hooks, you can specify the class of the equipment texture class.
If both an internal name and associated item are provided, the EquipTexture's name will be set to the internal name, alongside the keys for the equipTexture dictionary.
Additionally, if multiple EquipTextures of the same type are registered for the same item, the first one to be added will be the one automatically displayed on the player and mannequins.
Parameters
mod The mod the equipment texture is from.
equipTexture The equip texture.
item The item.
name The internal name.
type The type.
texture The texture.
Returns
the ID / slot that is assigned to the equipment texture.
Definition at line 284 of file EquipLoader.cs.
    {
        if (!mod.loading)
        {
            throw new Exception("AddEquipTexture can only be called from Mod.Load or Mod.Autoload");
        }
        if (name == null && item == null)
        {
            throw new Exception("AddEquipTexture requires either an item or a name be provided");
        }
        if (equipTexture == null)
        {
            equipTexture = new EquipTexture();
        }
        ModContent.Request<Texture2D>(texture);
        equipTexture.Texture = texture;
        equipTexture.Name = name ?? item.Name;
        equipTexture.Type = type;
        equipTexture.Item = item;
        int num2 = (equipTexture.Slot = ReserveEquipID(type));
        int slot = num2;
        equipTextures[type][slot] = equipTexture;
        mod.equipTextures[Tuple.Create(name ?? item.Name, type)] = equipTexture;
        if (item != null)
        {
            if (!idToSlot.TryGetValue(item.Type, out var slots))
            {
                slots = (idToSlot[item.Type] = new Dictionary<EquipType, int>());
            }
            slots[type] = slot;
            if (type == EquipType.Head || type == EquipType.Body || type == EquipType.Legs)
            {
                slotToId[type][slot] = item.Type;
            }
        }
        return slot;
    }
References Terraria.ModLoader.EquipLoader.equipTextures, Terraria.ModLoader.Mod.equipTextures, Terraria.ModLoader.EquipLoader.idToSlot, Terraria.ModLoader.Mod.loading, Terraria.ModLoader.EquipLoader.ReserveEquipID(), and Terraria.ModLoader.EquipLoader.slotToId.
Referenced by Terraria.ModLoader.Default.Patreon.xAqult_Lens.Load(), Terraria.ModLoader.Default.Patreon.Tantamount_Head.OnCreated(), and Terraria.ModLoader.ModItem.Register().