TModLoader: Terraria.ModLoader.EquipLoader.GetEquipTexture
GetEquipTexture() [1/2]
static EquipTexture Terraria.ModLoader.EquipLoader.GetEquipTexture (EquipType type, int slot) inline static
Gets the equipment texture for the specified equipment type and ID.
Parameters
type
slot
Returns
    {
        if (!equipTextures[type].TryGetValue(slot, out var texture))
        {
            return null;
        }
        return texture;
    }
References Terraria.ModLoader.EquipLoader.equipTextures.
Referenced by Terraria.ModLoader.ItemLoader.ArmorArmGlowMask(), Terraria.ModLoader.ItemLoader.ArmorSetShadows(), Terraria.ModLoader.ItemLoader.DrawArmorColor(), Terraria.ModLoader.EquipLoader.EquipFrameEffects(), Terraria.ModLoader.EquipLoader.GetEquipSlot(), Terraria.ModLoader.ModContent.GetEquipTexture(), Terraria.ModLoader.ItemLoader.HorizontalWingSpeeds(), Terraria.ModLoader.ItemLoader.PreUpdateVanitySet(), Terraria.ModLoader.ItemLoader.SetMatch(), Terraria.ModLoader.ItemLoader.UpdateVanitySet(), Terraria.ModLoader.ItemLoader.VerticalWingSpeeds(), and Terraria.ModLoader.ItemLoader.WingUpdate().