TModLoader: Terraria.ModLoader.ModMount.Register
Register()
override void Terraria.ModLoader.ModMount.Register () inline sealed protected
    {
        if (Mount.mounts == null || Mount.mounts.Length == MountID.Count)
        {
            Mount.Initialize();
        }
        Type = MountLoader.ReserveMountID();
        ModTypeLookup<ModMount>.Register(this);
        MountLoader.mountDatas[Type] = this;
        foreach (MountTextureType textureType in Enum.GetValues(typeof(MountTextureType)))
        {
            string extraTexture = GetExtraTexture(textureType);
            if (!string.IsNullOrEmpty(extraTexture) && ModContent.RequestIfExists(extraTexture, out Asset<Texture2D> textureAsset, AssetRequestMode.AsyncLoad))
            {
                switch (textureType)
                {
                case MountTextureType.Back:
                    MountData.backTexture = textureAsset;
                    break;
                case MountTextureType.BackGlow:
                    MountData.backTextureGlow = textureAsset;
                    break;
                case MountTextureType.BackExtra:
                    MountData.backTextureExtra = textureAsset;
                    break;
                case MountTextureType.BackExtraGlow:
                    MountData.backTextureExtraGlow = textureAsset;
                    break;
                case MountTextureType.Front:
                    MountData.frontTexture = textureAsset;
                    break;
                case MountTextureType.FrontGlow:
                    MountData.frontTextureGlow = textureAsset;
                    break;
                case MountTextureType.FrontExtra:
                    MountData.frontTextureExtra = textureAsset;
                    break;
                case MountTextureType.FrontExtraGlow:
                    MountData.frontTextureExtraGlow = textureAsset;
                    break;
                }
            }
        }
    }
References Terraria.ID.MountID.Count, Terraria.ModLoader.ModMount.GetExtraTexture(), Terraria.Mount.Initialize(), Terraria.ModLoader.MountLoader.mountDatas, Terraria.Mount.mounts, Terraria.ModLoader.MountLoader.ReserveMountID(), and Terraria.ModLoader.ModMount.Type.