TModLoader: Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerFull
DrawPlayerFull()
void Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerFull (Camera camera, Player drawPlayer) inline private
    {
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01de: Unknown result type (might be due to invalid IL or missing references)
        //IL_0202: Unknown result type (might be due to invalid IL or missing references)
        //IL_0207: Unknown result type (might be due to invalid IL or missing references)
        //IL_0272: Unknown result type (might be due to invalid IL or missing references)
        //IL_0242: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_0222: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0519: Unknown result type (might be due to invalid IL or missing references)
        //IL_052f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0573: Unknown result type (might be due to invalid IL or missing references)
        //IL_0589: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0608: Unknown result type (might be due to invalid IL or missing references)
        //IL_06aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0380: Unknown result type (might be due to invalid IL or missing references)
        //IL_0389: Unknown result type (might be due to invalid IL or missing references)
        //IL_0744: Unknown result type (might be due to invalid IL or missing references)
        //IL_077f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0788: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_080e: Unknown result type (might be due to invalid IL or missing references)
        //IL_081e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0823: Unknown result type (might be due to invalid IL or missing references)
        //IL_0828: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_090f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0918: Unknown result type (might be due to invalid IL or missing references)
        //IL_0871: Unknown result type (might be due to invalid IL or missing references)
        //IL_087a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0893: Unknown result type (might be due to invalid IL or missing references)
        //IL_0899: Unknown result type (might be due to invalid IL or missing references)
        //IL_089b: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b3: Unknown result type (might be due to invalid IL or missing references)
        SpriteBatch spriteBatch = camera.SpriteBatch;
        SamplerState samplerState = camera.Sampler;
        if (drawPlayer.mount.Active && drawPlayer.fullRotation != 0f)
        {
            samplerState = MountedSamplerState;
        }
        spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend, samplerState, DepthStencilState.None, camera.Rasterizer, (Effect)null, camera.GameViewMatrix.TransformationMatrix);
        if (Main.gamePaused)
        {
            drawPlayer.PlayerFrame();
        }
        if (drawPlayer.ghost)
        {
            for (int i = 0; i < 3; i++)
            {
                Vector2 vector = drawPlayer.shadowPos[i];
                vector = drawPlayer.position - drawPlayer.velocity * (float)(2 + i * 2);
                DrawGhost(camera, drawPlayer, vector, 0.5f + 0.2f * (float)i);
            }
            DrawGhost(camera, drawPlayer, drawPlayer.position);
        }
        else
        {
            if (drawPlayer.inventory[drawPlayer.selectedItem].flame || drawPlayer.head == 137 || drawPlayer.wings == 22)
            {
                drawPlayer.itemFlameCount--;
                if (drawPlayer.itemFlameCount <= 0)
                {
                    drawPlayer.itemFlameCount = 5;
                    for (int j = 0; j < 7; j++)
                    {
                        drawPlayer.itemFlamePos[j].X = (float)Main.rand.Next(-10, 11) * 0.15f;
                        drawPlayer.itemFlamePos[j].Y = (float)Main.rand.Next(-10, 1) * 0.35f;
                    }
                }
            }
            if (drawPlayer.armorEffectDrawShadowEOCShield)
            {
                int num = drawPlayer.eocDash / 4;
                if (num > 3)
                {
                    num = 3;
                }
                for (int k = 0; k < num; k++)
                {
                    DrawPlayer(camera, drawPlayer, drawPlayer.shadowPos[k], drawPlayer.shadowRotation[k], drawPlayer.shadowOrigin[k], 0.5f + 0.2f * (float)k);
                }
            }
            Vector2 position = default(Vector2);
            if (drawPlayer.invis)
            {
                drawPlayer.armorEffectDrawOutlines = false;
                drawPlayer.armorEffectDrawShadow = false;
                drawPlayer.armorEffectDrawShadowSubtle = false;
                position = drawPlayer.position;
                if (drawPlayer.aggro <= -750)
                {
                    DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin, 1f);
                }
                else
                {
                    drawPlayer.invis = false;
                    DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin);
                    drawPlayer.invis = true;
                }
            }
            if (drawPlayer.armorEffectDrawOutlines)
            {
                _ = drawPlayer.position;
                if (!Main.gamePaused)
                {
                    drawPlayer.ghostFade += drawPlayer.ghostDir * 0.075f;
                }
                if ((double)drawPlayer.ghostFade < 0.1)
                {
                    drawPlayer.ghostDir = 1f;
                    drawPlayer.ghostFade = 0.1f;
                }
                else if ((double)drawPlayer.ghostFade > 0.9)
                {
                    drawPlayer.ghostDir = -1f;
                    drawPlayer.ghostFade = 0.9f;
                }
                float num5 = drawPlayer.ghostFade * 5f;
                for (int l = 0; l < 4; l++)
                {
                    float num6;
                    float num7;
                    switch (l)
                    {
                    default:
                        num6 = num5;
                        num7 = 0f;
                        break;
                    case 1:
                        num6 = 0f - num5;
                        num7 = 0f;
                        break;
                    case 2:
                        num6 = 0f;
                        num7 = num5;
                        break;
                    case 3:
                        num6 = 0f;
                        num7 = 0f - num5;
                        break;
                    }
                    ((Vector2)(ref position))._002Ector(drawPlayer.position.X + num6, drawPlayer.position.Y + drawPlayer.gfxOffY + num7);
                    DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin, drawPlayer.ghostFade);
                }
            }
            if (drawPlayer.armorEffectDrawOutlinesForbidden)
            {
                _ = drawPlayer.position;
                if (!Main.gamePaused)
                {
                    drawPlayer.ghostFade += drawPlayer.ghostDir * 0.025f;
                }
                if ((double)drawPlayer.ghostFade < 0.1)
                {
                    drawPlayer.ghostDir = 1f;
                    drawPlayer.ghostFade = 0.1f;
                }
                else if ((double)drawPlayer.ghostFade > 0.9)
                {
                    drawPlayer.ghostDir = -1f;
                    drawPlayer.ghostFade = 0.9f;
                }
                float num8 = drawPlayer.ghostFade * 5f;
                for (int m = 0; m < 4; m++)
                {
                    float num9;
                    float num10;
                    switch (m)
                    {
                    default:
                        num9 = num8;
                        num10 = 0f;
                        break;
                    case 1:
                        num9 = 0f - num8;
                        num10 = 0f;
                        break;
                    case 2:
                        num9 = 0f;
                        num10 = num8;
                        break;
                    case 3:
                        num9 = 0f;
                        num10 = 0f - num8;
                        break;
                    }
                    ((Vector2)(ref position))._002Ector(drawPlayer.position.X + num9, drawPlayer.position.Y + drawPlayer.gfxOffY + num10);
                    DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin, drawPlayer.ghostFade);
                }
            }
            if (drawPlayer.armorEffectDrawShadowBasilisk)
            {
                int num11 = (int)(drawPlayer.basiliskCharge * 3f);
                for (int n = 0; n < num11; n++)
                {
                    DrawPlayer(camera, drawPlayer, drawPlayer.shadowPos[n], drawPlayer.shadowRotation[n], drawPlayer.shadowOrigin[n], 0.5f + 0.2f * (float)n);
                }
            }
            else if (drawPlayer.armorEffectDrawShadow)
            {
                for (int num12 = 0; num12 < 3; num12++)
                {
                    DrawPlayer(camera, drawPlayer, drawPlayer.shadowPos[num12], drawPlayer.shadowRotation[num12], drawPlayer.shadowOrigin[num12], 0.5f + 0.2f * (float)num12);
                }
            }
            if (drawPlayer.armorEffectDrawShadowLokis)
            {
                for (int num2 = 0; num2 < 3; num2++)
                {
                    DrawPlayer(camera, drawPlayer, Vector2.Lerp(drawPlayer.shadowPos[num2], drawPlayer.position + new Vector2(0f, drawPlayer.gfxOffY), 0.5f), drawPlayer.shadowRotation[num2], drawPlayer.shadowOrigin[num2], MathHelper.Lerp(1f, 0.5f + 0.2f * (float)num2, 0.5f));
                }
            }
            if (drawPlayer.armorEffectDrawShadowSubtle)
            {
                for (int num3 = 0; num3 < 4; num3++)
                {
                    position.X = drawPlayer.position.X + (float)Main.rand.Next(-20, 21) * 0.1f;
                    position.Y = drawPlayer.position.Y + (float)Main.rand.Next(-20, 21) * 0.1f + drawPlayer.gfxOffY;
                    DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin, 0.9f);
                }
            }
            if (drawPlayer.shadowDodge)
            {
                drawPlayer.shadowDodgeCount += 1f;
                if (drawPlayer.shadowDodgeCount > 30f)
                {
                    drawPlayer.shadowDodgeCount = 30f;
                }
            }
            else
            {
                drawPlayer.shadowDodgeCount -= 1f;
                if (drawPlayer.shadowDodgeCount < 0f)
                {
                    drawPlayer.shadowDodgeCount = 0f;
                }
            }
            if (drawPlayer.shadowDodgeCount > 0f)
            {
                _ = drawPlayer.position;
                position.X = drawPlayer.position.X + drawPlayer.shadowDodgeCount;
                position.Y = drawPlayer.position.Y + drawPlayer.gfxOffY;
                DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin, 0.5f + (float)Main.rand.Next(-10, 11) * 0.005f);
                position.X = drawPlayer.position.X - drawPlayer.shadowDodgeCount;
                DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin, 0.5f + (float)Main.rand.Next(-10, 11) * 0.005f);
            }
            if (drawPlayer.brainOfConfusionDodgeAnimationCounter > 0)
            {
                Vector2 vector2 = drawPlayer.position + new Vector2(0f, drawPlayer.gfxOffY);
                float lerpValue = Utils.GetLerpValue(300f, 270f, drawPlayer.brainOfConfusionDodgeAnimationCounter);
                float y = MathHelper.Lerp(2f, 120f, lerpValue);
                if (lerpValue >= 0f && lerpValue <= 1f)
                {
                    for (float num4 = 0f; num4 < (float)Math.PI * 2f; num4 += (float)Math.PI / 3f)
                    {
                        position = vector2 + Utils.RotatedBy(new Vector2(0f, y), (float)Math.PI * 2f * lerpValue * 0.5f + num4);
                        DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin, lerpValue);
                    }
                }
            }
            position = drawPlayer.position;
            position.Y += drawPlayer.gfxOffY;
            if (drawPlayer.stoned)
            {
                DrawPlayerStoned(camera, drawPlayer, position);
            }
            else if (!drawPlayer.invis)
            {
                DrawPlayer(camera, drawPlayer, position, drawPlayer.fullRotation, drawPlayer.fullRotationOrigin);
            }
        }
        spriteBatch.End();
    }
References Terraria.Mount.Active, Terraria.Player.aggro, Terraria.Player.armorEffectDrawOutlines, Terraria.Player.armorEffectDrawOutlinesForbidden, Terraria.Player.armorEffectDrawShadow, Terraria.Player.armorEffectDrawShadowBasilisk, Terraria.Player.armorEffectDrawShadowEOCShield, Terraria.Player.armorEffectDrawShadowLokis, Terraria.Player.armorEffectDrawShadowSubtle, Terraria.Player.basiliskCharge, Terraria.Player.brainOfConfusionDodgeAnimationCounter, Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawGhost(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerStoned(), Terraria.Item.flame, Terraria.Player.fullRotation, Terraria.Player.fullRotationOrigin, Terraria.Main.gamePaused, Terraria.Utils.GetLerpValue(), Terraria.Player.gfxOffY, Terraria.Player.ghost, Terraria.Player.ghostFade, Terraria.Player.head, Terraria.Player.inventory, Terraria.Player.invis, Terraria.Player.itemFlameCount, Terraria.Player.itemFlamePos, Terraria.Player.mount, Terraria.Graphics.Renderers.LegacyPlayerRenderer.MountedSamplerState, Terraria.Player.PlayerFrame(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Utils.RotatedBy(), Terraria.Player.selectedItem, Terraria.Player.shadowDodge, Terraria.Player.shadowDodgeCount, Terraria.Player.shadowOrigin, Terraria.Player.shadowPos, Terraria.Player.shadowRotation, Terraria.Player.stoned, and Terraria.Player.wings.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayers().