TModLoader: Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawGhost
DrawGhost()
void Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawGhost (Camera camera, Player drawPlayer, Vector2 position, float shadow = 0f) inline private
    {
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        byte mouseTextColor = Main.mouseTextColor;
        SpriteEffects effects = (SpriteEffects)(drawPlayer.direction != 1);
        Color immuneAlpha = drawPlayer.GetImmuneAlpha(Lighting.GetColor((int)((double)drawPlayer.position.X + (double)drawPlayer.width * 0.5) / 16, (int)((double)drawPlayer.position.Y + (double)drawPlayer.height * 0.5) / 16, new Color(mouseTextColor / 2 + 100, mouseTextColor / 2 + 100, mouseTextColor / 2 + 100, mouseTextColor / 2 + 100)), shadow);
        ((Color)(ref immuneAlpha)).A = (byte)((float)(int)((Color)(ref immuneAlpha)).A * (1f - Math.Max(0.5f, shadow - 0.5f)));
        Rectangle value = default(Rectangle);
        ((Rectangle)(ref value))._002Ector(0, TextureAssets.Ghost.Height() / 4 * drawPlayer.ghostFrame, TextureAssets.Ghost.Width(), TextureAssets.Ghost.Height() / 4);
        Vector2 origin = default(Vector2);
        ((Vector2)(ref origin))._002Ector((float)value.Width * 0.5f, (float)value.Height * 0.5f);
        camera.SpriteBatch.Draw(TextureAssets.Ghost.Value, new Vector2((float)(int)(position.X - camera.UnscaledPosition.X + (float)(value.Width / 2)), (float)(int)(position.Y - camera.UnscaledPosition.Y + (float)(value.Height / 2))), (Rectangle?)value, immuneAlpha, 0f, origin, 1f, effects, 0f);
    }
References Terraria.Entity.direction, Terraria.Lighting.GetColor(), Terraria.Player.GetImmuneAlpha(), Terraria.GameContent.TextureAssets.Ghost, Terraria.Player.ghostFrame, Terraria.Entity.height, Terraria.Main.mouseTextColor, Terraria.Entity.position, and Terraria.Entity.width.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerFull().