TModLoader: Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerInternal
DrawPlayerInternal()
void Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerInternal (Camera camera, Player drawPlayer, Vector2 position, float rotation, Vector2 rotationOrigin, float shadow = 0f, float alpha = 1f, float scale = 1f, bool headOnly = false) inline private
    {
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        if (drawPlayer.ShouldNotDraw)
        {
            return;
        }
        PlayerDrawSet drawInfo = default(PlayerDrawSet);
        _drawData.Clear();
        _dust.Clear();
        _gore.Clear();
        if (headOnly)
        {
            drawInfo.HeadOnlySetup(drawPlayer, _drawData, _dust, _gore, position.X, position.Y, alpha, scale);
        }
        else
        {
            drawInfo.BoringSetup(drawPlayer, _drawData, _dust, _gore, position, shadow, rotation, rotationOrigin);
        }
        PlayerLoader.ModifyDrawInfo(ref drawInfo);
        PlayerDrawLayer[] drawLayers = PlayerDrawLayerLoader.GetDrawLayers(drawInfo);
        foreach (PlayerDrawLayer layer in drawLayers)
        {
            if (!headOnly || layer.IsHeadLayer)
            {
                layer.DrawWithTransformationAndChildren(ref drawInfo);
            }
        }
        PlayerDrawLayers.DrawPlayer_MakeIntoFirstFractalAfterImage(ref drawInfo);
        PlayerDrawLayers.DrawPlayer_TransformDrawData(ref drawInfo);
        if (scale != 1f)
        {
            PlayerDrawLayers.DrawPlayer_ScaleDrawData(ref drawInfo, scale);
        }
        PlayerDrawLayers.DrawPlayer_RenderAllLayers(ref drawInfo);
        if (!drawInfo.drawPlayer.mount.Active || !drawInfo.drawPlayer.UsingSuperCart)
        {
            return;
        }
        for (int i = 0; i < 1000; i++)
        {
            if (Main.projectile[i].active && Main.projectile[i].owner == drawInfo.drawPlayer.whoAmI && Main.projectile[i].type == 591)
            {
                Main.instance.DrawProj(i);
            }
        }
    }
References Terraria.Graphics.Renderers.LegacyPlayerRenderer._drawData, Terraria.Graphics.Renderers.LegacyPlayerRenderer._dust, Terraria.Graphics.Renderers.LegacyPlayerRenderer._gore, Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_MakeIntoFirstFractalAfterImage(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_RenderAllLayers(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_ScaleDrawData(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_TransformDrawData(), Terraria.ModLoader.PlayerDrawLayerLoader.GetDrawLayers(), Terraria.Main.instance, Terraria.ModLoader.PlayerLoader.ModifyDrawInfo(), Terraria.Main.projectile, and Terraria.Player.ShouldNotDraw.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer(), and Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerHead().