TModLoader: Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Draw
Draw()
override void Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Draw (SpriteBatch sb) inline
Definition at line 1300 of file CaptureInterface.cs.
        {
            //IL_0026: Unknown result type (might be due to invalid IL or missing references)
            //IL_007e: Unknown result type (might be due to invalid IL or missing references)
            //IL_008e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0093: Unknown result type (might be due to invalid IL or missing references)
            //IL_0095: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
            //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
            //IL_00db: Unknown result type (might be due to invalid IL or missing references)
            //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
            //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
            //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
            //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
            //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
            //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
            //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
            //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
            //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
            //IL_010c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0111: Unknown result type (might be due to invalid IL or missing references)
            //IL_0116: Unknown result type (might be due to invalid IL or missing references)
            //IL_011d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0122: Unknown result type (might be due to invalid IL or missing references)
            //IL_0131: Unknown result type (might be due to invalid IL or missing references)
            //IL_0143: Unknown result type (might be due to invalid IL or missing references)
            //IL_0144: Unknown result type (might be due to invalid IL or missing references)
            //IL_0156: Unknown result type (might be due to invalid IL or missing references)
            //IL_015b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0160: Unknown result type (might be due to invalid IL or missing references)
            //IL_0172: Unknown result type (might be due to invalid IL or missing references)
            //IL_0177: Unknown result type (might be due to invalid IL or missing references)
            //IL_017c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0181: Unknown result type (might be due to invalid IL or missing references)
            //IL_0190: Unknown result type (might be due to invalid IL or missing references)
            //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
            //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
            if (!Selected)
            {
                return;
            }
            sb.End();
            sb.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, Main.CurrentWantedZoomMatrix);
            PlayerInput.SetZoom_Context();
            ((ModeDragBounds)Modes[1]).currentAim = -1;
            ((ModeDragBounds)Modes[1]).DrawMarkedArea(sb);
            sb.End();
            sb.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, Main.UIScaleMatrix);
            PlayerInput.SetZoom_UI();
            Rectangle rect = GetRect();
            Utils.DrawInvBG(sb, rect, new Color(63, 65, 151, 255) * 0.485f);
            for (int i = 0; i < 7; i++)
            {
                string key = "";
                string value = "";
                ButtonDraw(i, ref key, ref value);
                Color baseColor = Color.White;
                if (i == hoveredButton)
                {
                    baseColor = Color.Gold;
                }
                ChatManager.DrawColorCodedStringWithShadow(sb, FontAssets.ItemStack.Value, key, rect.TopLeft() + new Vector2(20f, (float)(20 + 20 * i)), baseColor, 0f, Vector2.Zero, Vector2.One);
                ChatManager.DrawColorCodedStringWithShadow(sb, FontAssets.ItemStack.Value, value, rect.TopRight() + new Vector2(-20f, (float)(20 + 20 * i)), baseColor, 0f, FontAssets.ItemStack.Value.MeasureString(value) * Vector2.UnitX, Vector2.One);
            }
            DrawWaterChoices(sb, (rect.TopLeft() + new Vector2((float)(rect.Width / 2 - 84), 90f)).ToPoint(), Main.MouseScreen.ToPoint());
        }
References Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.ButtonDraw(), Terraria.Main.CurrentWantedZoomMatrix, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Utils.DrawInvBG(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.DrawWaterChoices(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.GetRect(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.hoveredButton, Terraria.GameContent.FontAssets.ItemStack, Terraria.Graphics.Capture.CaptureInterface.Modes, Terraria.Main.MouseScreen, Terraria.Graphics.Capture.CaptureInterface.CaptureInterfaceMode.Selected, Terraria.GameInput.PlayerInput.SetZoom_Context(), Terraria.GameInput.PlayerInput.SetZoom_UI(), and Terraria.Main.UIScaleMatrix.