TModLoader: Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.DrawWaterChoices
DrawWaterChoices()
void Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.DrawWaterChoices (SpriteBatch spritebatch, Point start, Point mouse) inline private
Definition at line 1159 of file CaptureInterface.cs.
        {
            //IL_002d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0044: Unknown result type (might be due to invalid IL or missing references)
            //IL_005b: Unknown result type (might be due to invalid IL or missing references)
            //IL_00de: Unknown result type (might be due to invalid IL or missing references)
            //IL_0151: Unknown result type (might be due to invalid IL or missing references)
            //IL_0152: Unknown result type (might be due to invalid IL or missing references)
            //IL_015b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0165: Unknown result type (might be due to invalid IL or missing references)
            //IL_016c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0176: Unknown result type (might be due to invalid IL or missing references)
            //IL_0180: Unknown result type (might be due to invalid IL or missing references)
            //IL_010c: Unknown result type (might be due to invalid IL or missing references)
            //IL_010d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0116: Unknown result type (might be due to invalid IL or missing references)
            //IL_0120: Unknown result type (might be due to invalid IL or missing references)
            //IL_012a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0134: Unknown result type (might be due to invalid IL or missing references)
            //IL_0193: Unknown result type (might be due to invalid IL or missing references)
            //IL_0194: Unknown result type (might be due to invalid IL or missing references)
            //IL_019e: Unknown result type (might be due to invalid IL or missing references)
            //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
            //IL_01af: Unknown result type (might be due to invalid IL or missing references)
            //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
            //IL_01c0: Unknown result type (might be due to invalid IL or missing references)
            Rectangle r = default(Rectangle);
            ((Rectangle)(ref r))._002Ector(0, 0, 20, 20);
            for (int i = 0; i < 2; i++)
            {
                for (int j = 0; j < 7; j++)
                {
                    if (i == 1 && j == 6)
                    {
                        continue;
                    }
                    int num5 = j + i * 7;
                    r.X = start.X + 24 * j + 12 * i;
                    r.Y = start.Y + 24 * i;
                    int num2 = num5;
                    int num3 = 0;
                    if (((Rectangle)(ref r)).Contains(mouse))
                    {
                        if (Main.mouseLeft && Main.mouseLeftRelease)
{
                            SoundEngine.PlaySound(12);
                            Settings.BiomeChoiceIndex = num2;
                        }
                        Main.instance.MouseText(Language.GetTextValue("CaptureBiomeChoice." + num2), 0, 0);
                        num3++;
                    }
                    if (Settings.BiomeChoiceIndex == num2)
                    {
                        num3 += 2;
                    }
                    Texture2D value = TextureAssets.Extra[130].Value;
                    int x = num5 * 18;
                    _ = Color.White;
                    float num4 = 1f;
                    if (num3 < 2)
                    {
                        num4 *= 0.5f;
                    }
                    if (num3 % 2 == 1)
                    {
                        spritebatch.Draw(TextureAssets.MagicPixel.Value, r.TopLeft(), (Rectangle?)new Rectangle(0, 0, 1, 1), Color.Gold, 0f, Vector2.Zero, new Vector2(20f), (SpriteEffects)0, 0f);
                    }
                    else
                    {
                        spritebatch.Draw(TextureAssets.MagicPixel.Value, r.TopLeft(), (Rectangle?)new Rectangle(0, 0, 1, 1), Color.White * num4, 0f, Vector2.Zero, new Vector2(20f), (SpriteEffects)0, 0f);
                    }
                    spritebatch.Draw(value, r.TopLeft() + new Vector2(2f), (Rectangle?)new Rectangle(x, 0, 16, 16), Color.White * num4);
                }
            }
        }
References Terraria.Graphics.Capture.CaptureInterface.Settings.BiomeChoiceIndex, Terraria.GameContent.TextureAssets.Extra, Terraria.Localization.Language.GetTextValue(), Terraria.Main.instance, Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.MouseText(), and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Draw().