TModLoader: Terraria.Liquid.LiquidCheck
LiquidCheck()
static void Terraria.Liquid.LiquidCheck (int x, int y, int thisLiquidType) inline static
Definition at line 1224 of file Liquid.cs.
    {
        if (WorldGen.SolidTile(x, y))
        {
            return;
        }
        Tile tile = Main.tile[x - 1, y];
        Tile tile2 = Main.tile[x + 1, y];
        Tile tile3 = Main.tile[x, y - 1];
        Tile tile4 = Main.tile[x, y + 1];
        Tile tile5 = Main.tile[x, y];
        if ((tile.liquid > 0 && tile.liquidType() != thisLiquidType) || (tile2.liquid > 0 && tile2.liquidType() != thisLiquidType) || (tile3.liquid > 0 && tile3.liquidType() != thisLiquidType))
        {
            int num = 0;
            if (tile.liquidType() != thisLiquidType)
            {
                num += tile.liquid;
                tile.liquid = 0;
            }
            if (tile2.liquidType() != thisLiquidType)
            {
                num += tile2.liquid;
                tile2.liquid = 0;
            }
            if (tile3.liquidType() != thisLiquidType)
            {
                num += tile3.liquid;
                tile3.liquid = 0;
            }
            int liquidMergeTileType = 56;
            int liquidMergeType = 0;
            bool waterNearby = tile.liquidType() == 0 || tile2.liquidType() == 0 || tile3.liquidType() == 0;
            bool lavaNearby = tile.lava() || tile2.lava() || tile3.lava();
            bool honeyNearby = tile.honey() || tile2.honey() || tile3.honey();
            bool shimmerNearby = tile.shimmer() || tile2.shimmer() || tile3.shimmer();
            GetLiquidMergeTypes(thisLiquidType, out liquidMergeTileType, out liquidMergeType, waterNearby, lavaNearby, honeyNearby, shimmerNearby);
            if (num < 24 || liquidMergeType == thisLiquidType)
            {
                return;
            }
            if (tile5.active() && Main.tileObsidianKill[tile5.type])
            {
                WorldGen.KillTile(x, y);
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, x, y);
                }
            }
            if (!tile5.active())
            {
                tile5.liquid = 0;
                switch (thisLiquidType)
                {
                case 1:
                    tile5.lava(lava: false);
                    break;
                case 2:
                    tile5.honey(honey: false);
                    break;
                case 3:
                    tile5.shimmer(shimmer: false);
                    break;
                }
                TileChangeType liquidChangeType = WorldGen.GetLiquidChangeType(thisLiquidType, liquidMergeType);
                if (!WorldGen.gen)
                {
                    WorldGen.PlayLiquidChangeSound(liquidChangeType, x, y);
                }
                WorldGen.PlaceTile(x, y, liquidMergeTileType, mute: true, forced: true);
                WorldGen.SquareTileFrame(x, y);
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, x - 1, y - 1, 3, liquidChangeType);
                }
            }
        }
        else
        {
            if (tile4.liquid <= 0 || tile4.liquidType() == thisLiquidType)
            {
                return;
            }
            bool flag = false;
            if (tile5.active() && TileID.Sets.IsAContainer[tile5.type] && !TileID.Sets.IsAContainer[tile4.type])
            {
                flag = true;
            }
            if (thisLiquidType != 0 && Main.tileCut[tile4.type])
            {
                WorldGen.KillTile(x, y + 1);
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, x, y + 1);
                }
            }
            else if (tile4.active() && Main.tileObsidianKill[tile4.type])
            {
                WorldGen.KillTile(x, y + 1);
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, x, y + 1);
                }
            }
            if (!(!tile4.active() || flag))
            {
                return;
            }
            if (tile5.liquid < 24)
            {
                tile5.liquid = 0;
                tile5.liquidType(0);
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, x - 1, y, 3);
                }
                return;
            }
            int liquidMergeTileType2 = 56;
            int liquidMergeType2 = 0;
            bool waterNearby2 = tile4.liquidType() == 0;
            bool lavaNearby2 = tile4.lava();
            bool honeyNearby2 = tile4.honey();
            bool shimmerNearby2 = tile4.shimmer();
            GetLiquidMergeTypes(thisLiquidType, out liquidMergeTileType2, out liquidMergeType2, waterNearby2, lavaNearby2, honeyNearby2, shimmerNearby2);
            tile5.liquid = 0;
            switch (thisLiquidType)
            {
            case 1:
                tile5.lava(lava: false);
                break;
            case 2:
                tile5.honey(honey: false);
                break;
            case 3:
                tile5.shimmer(shimmer: false);
                break;
            }
            tile4.liquid = 0;
            TileChangeType liquidChangeType2 = WorldGen.GetLiquidChangeType(thisLiquidType, liquidMergeType2);
            if (!Main.gameMenu)
            {
                WorldGen.PlayLiquidChangeSound(liquidChangeType2, x, y);
            }
            WorldGen.PlaceTile(x, y + 1, liquidMergeTileType2, mute: true, forced: true);
            WorldGen.SquareTileFrame(x, y + 1);
            if (Main.netMode == 2)
            {
                NetMessage.SendTileSquare(-1, x - 1, y, 3, liquidChangeType2);
            }
        }
    }
References Terraria.Main.gameMenu, Terraria.WorldGen.gen, Terraria.WorldGen.GetLiquidChangeType(), Terraria.Liquid.GetLiquidMergeTypes(), Terraria.Tile.honey(), Terraria.ID.TileID.Sets.IsAContainer, Terraria.WorldGen.KillTile(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.netMode, Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.PlayLiquidChangeSound(), Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.Tile.shimmer(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Main.tileObsidianKill, Terraria.Liquid.x, and Terraria.Liquid.y.
Referenced by Terraria.Liquid.HoneyCheck(), Terraria.Liquid.LavaCheck(), and Terraria.Liquid.ShimmerCheck().