TModLoader: Terraria.Tile.color
color() [1/2]
byte Terraria.Tile.color () inline package
Legacy code, use P:Terraria.Tile.TileColor instead.
Returns
    {
        return TileColor;
    }
References Terraria.Tile.TileColor.
Referenced by Terraria.Graphics.Light.TileLightScanner.ApplyTileLight(), Terraria.TileColorCache.ApplyToBlock(), Terraria.Tile.BlockColorAndCoating(), Terraria.Tile.ClearBlockPaintAndCoating(), Terraria.Tile.color(), Terraria.IO.WorldFile.ConvertIlluminantPaintToNewField(), Terraria.Tile.CopyPaintAndCoating(), Terraria.Map.MapHelper.CreateMapTile(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.WorldGen.GrowPalmTree(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.GameContent.Drawing.TileDrawing.MakeExtraPreparations(), Terraria.WorldGen.PaintTheClouds(), Terraria.WorldGen.PaintTheDungeon(), Terraria.WorldGen.PaintTheLivingTrees(), Terraria.WorldGen.PaintTheMushrooms(), Terraria.WorldGen.PaintThePurityGrass(), Terraria.WorldGen.PaintThePyramids(), Terraria.WorldGen.PaintTheSand(), Terraria.WorldGen.PaintTheTemple(), Terraria.WorldGen.PaintTheTrees(), Terraria.WorldGen.paintTile(), Terraria.Player.PlaceThing_PaintScrapper_TryScrapping(), Terraria.WorldGen.PlaceTile(), Terraria.GameContent.Drawing.TileDrawing.PrepareForAreaDrawing(), Terraria.ModLoader.IO.TileIO.TileIOImpl.ReadData(), Terraria.ModLoader.IO.TileIO.ReadModTile(), Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.GameContent.SmartCursorHelper.Step_PaintBrush(), Terraria.GameContent.SmartCursorHelper.Step_PaintScrapper(), Terraria.Minecart.TrackColors(), and Terraria.ModLoader.IO.TileIO.TileIOImpl.WriteData().