TModLoader: Terraria.Tile.honey
honey() [1/2]
bool Terraria.Tile.honey () inline package
Legacy code, use tile.LiquidType == LiquidID.Honey instead.
Returns
Definition at line 1213 of file Tile.cs.
    {
        return LiquidType == 2;
    }
References Terraria.Tile.LiquidType.
Referenced by Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.GameContent.Tile_Entities.TELogicSensor.GetState(), Terraria.Graphics.Light.TileLightScanner.GetTileMask(), Terraria.Gore.Gore_UpdateLeaf(), Terraria.Tile.honey(), Terraria.Player.ItemCheck_UseBuckets(), Terraria.WorldGen.KillTile_GetItemDrops(), Terraria.Liquid.LiquidCheck(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.Liquid.SettleWaterAt(), and Terraria.Liquid.Update().