TModLoader: Terraria.Tile.SmoothSlope
SmoothSlope()
static void Terraria.Tile.SmoothSlope (int x, int y, bool applyToNeighbors = true, bool sync = false) inline static
Slopes a tile based on the tiles adjacent to it.
Parameters
x The X coordinate of the tile.
y The Y coordinate of the tile.
applyToNeighbors Whether the adjacent tiles should be automatically smoothed.
sync Whether the changes should automatically be synced to multiplayer.
Definition at line 793 of file Tile.cs.
    {
        if (applyToNeighbors)
        {
            SmoothSlope(x + 1, y, applyToNeighbors: false, sync);
            SmoothSlope(x - 1, y, applyToNeighbors: false, sync);
            SmoothSlope(x, y + 1, applyToNeighbors: false, sync);
            SmoothSlope(x, y - 1, applyToNeighbors: false, sync);
        }
        Tile tile = Main.tile[x, y];
        if (!WorldGen.CanPoundTile(x, y) || !WorldGen.SolidOrSlopedTile(x, y))
        {
            return;
        }
        bool flag = !WorldGen.TileEmpty(x, y - 1);
        bool flag2 = !WorldGen.SolidOrSlopedTile(x, y - 1) && flag;
        bool flag3 = WorldGen.SolidOrSlopedTile(x, y + 1);
        bool flag4 = WorldGen.SolidOrSlopedTile(x - 1, y);
        bool flag5 = WorldGen.SolidOrSlopedTile(x + 1, y);
        int num = ((flag ? 1 : 0) << 3) | ((flag3 ? 1 : 0) << 2) | ((flag4 ? 1 : 0) << 1) | (flag5 ? 1 : 0);
        bool flag6 = tile.halfBrick();
        int num2 = tile.slope();
        switch (num)
        {
        case 10:
            if (!flag2)
            {
                tile.halfBrick(halfBrick: false);
                tile.slope(3);
            }
            break;
        case 9:
            if (!flag2)
            {
                tile.halfBrick(halfBrick: false);
                tile.slope(4);
            }
            break;
        case 6:
            tile.halfBrick(halfBrick: false);
            tile.slope(1);
            break;
        case 5:
            tile.halfBrick(halfBrick: false);
            tile.slope(2);
            break;
        case 4:
            tile.slope(0);
            tile.halfBrick(halfBrick: true);
            break;
        default:
            tile.halfBrick(halfBrick: false);
            tile.slope(0);
            break;
        }
        if (sync)
        {
            int num3 = tile.slope();
            bool flag7 = flag6 != tile.halfBrick();
            bool flag8 = num2 != num3;
            if (flag7 && flag8)
            {
                NetMessage.SendData(17, -1, -1, null, 23, x, y, num3);
            }
            else if (flag7)
            {
                NetMessage.SendData(17, -1, -1, null, 7, x, y, 1f);
            }
            else if (flag8)
            {
                NetMessage.SendData(17, -1, -1, null, 14, x, y, num3);
            }
        }
    }
References Terraria.WorldGen.CanPoundTile(), Terraria.Tile.halfBrick(), Terraria.NetMessage.SendData(), Terraria.Tile.slope(), Terraria.Tile.SmoothSlope(), Terraria.WorldGen.SolidOrSlopedTile(), Terraria.Main.tile, and Terraria.WorldGen.TileEmpty().
Referenced by Terraria.WorldBuilding.Actions.Smooth.Apply(), Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClusters(), Terraria.GameContent.Biomes.DunesBiome.PlaceCurvedLine(), Terraria.GameContent.Biomes.GraniteBiome.PlaceDecorations(), Terraria.GameContent.Generation.TrackGenerator.PlacePath(), Terraria.GameContent.Biomes.MarbleBiome.PlaceSlab(), Terraria.Tile.SmoothSlope(), and Terraria.Mount.UseDrill().