TModLoader: Terraria.Tile.Clear
Clear()
void Terraria.Tile.Clear (TileDataType types) inline
Clears the specified data at this position based on the given T:Terraria.DataStructures.TileDataType.
Parameters
types The T:Terraria.DataStructures.TileDataType to clear.
Definition at line 738 of file Tile.cs.
    {
        if ((types & TileDataType.Tile) != 0)
        {
            type = 0;
            active(active: false);
            frameX = 0;
            frameY = 0;
        }
        if ((types & TileDataType.Wall) != 0)
        {
            wall = 0;
            wallFrameX(0);
            wallFrameY(0);
        }
        if ((types & TileDataType.TilePaint) != 0)
        {
            ClearBlockPaintAndCoating();
        }
        if ((types & TileDataType.WallPaint) != 0)
        {
            ClearWallPaintAndCoating();
        }
        if ((types & TileDataType.Liquid) != 0)
        {
            liquid = 0;
            liquidType(0);
            checkingLiquid(checkingLiquid: false);
        }
        if ((types & TileDataType.Slope) != 0)
        {
            slope(0);
            halfBrick(halfBrick: false);
        }
        if ((types & TileDataType.Wiring) != 0)
        {
            wire(wire: false);
            wire2(wire2: false);
            wire3(wire3: false);
            wire4(wire4: false);
        }
        if ((types & TileDataType.Actuator) != 0)
        {
            actuator(actuator: false);
            inActive(inActive: false);
        }
    }
References Terraria.Tile.active(), Terraria.Tile.actuator(), Terraria.Tile.checkingLiquid(), Terraria.Tile.ClearBlockPaintAndCoating(), Terraria.Tile.ClearWallPaintAndCoating(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Tile.slope(), Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallFrameX(), Terraria.Tile.wallFrameY(), Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), and Terraria.Tile.wire4().
Referenced by Terraria.WorldGen.EmptyLiquid().