TModLoader: Terraria.ModLoader.Engine.TMLContentManager.OpenStream
OpenStream()
override Stream Terraria.ModLoader.Engine.TMLContentManager.OpenStream (string assetName) inline protected
Definition at line 50 of file TMLContentManager.cs.
    {
        if (!assetName.StartsWith("tmod:"))
        {
            if (overrideContentManager != null && File.Exists(Path.Combine(((ContentManager)overrideContentManager).RootDirectory, assetName + ".xnb")))
            {
                try
                {
                    using (new Logging.QuietExceptionHandle())
                    {
                        return ((ContentManager)overrideContentManager).OpenStream(assetName);
                    }
                }
                catch
                {
                }
            }
            return ((ContentManager)this).OpenStream(assetName);
        }
        if (!assetName.EndsWith(".xnb"))
        {
            assetName += ".xnb";
        }
        return ModContent.OpenRead(assetName);
    }
References Terraria.ModLoader.ModContent.OpenRead(), Terraria.ModLoader.Engine.TMLContentManager.OpenStream(), and Terraria.ModLoader.Engine.TMLContentManager.overrideContentManager.
Referenced by Terraria.ModLoader.Engine.TMLContentManager.OpenStream().