TModLoader: Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.GetHoverText
GetHoverText()
string Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.GetHoverText (BestiaryUICollectionInfo providedInfo) inline
Implements Terraria.GameContent.Bestiary.IEntryIcon.
Definition at line 248 of file UnlockableNPCEntryIcon.cs.
    {
        string result = Lang.GetNPCNameValue(_npcCache.netID);
        if (!string.IsNullOrWhiteSpace(_overrideNameKey))
        {
            result = Language.GetTextValue(_overrideNameKey);
        }
        if (GetUnlockState(providedInfo))
        {
            return result;
        }
        return "???";
    }
References Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon._npcCache, Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon._overrideNameKey, Terraria.Lang.GetNPCNameValue(), Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.GetUnlockState(), and Terraria.NPC.netID.