TModLoader: Terraria.GameContent.Biomes.DeadMansChestBiome.GetPossibleChestsToTrapify
GetPossibleChestsToTrapify()
List< int > Terraria.GameContent.Biomes.DeadMansChestBiome.GetPossibleChestsToTrapify (StructureMap structures) inline
Definition at line 468 of file DeadMansChestBiome.cs.
    {
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        List<int> list = new List<int>();
        bool[] array = new bool[TileID.Sets.GeneralPlacementTiles.Length];
        for (int i = 0; i < array.Length; i++)
        {
            array[i] = TileID.Sets.GeneralPlacementTiles[i];
        }
        array[21] = true;
        array[467] = true;
        Point position = default(Point);
        Point position2 = default(Point);
        for (int j = 0; j < 8000; j++)
        {
            Chest chest = Main.chest[j];
            if (chest == null)
            {
                continue;
            }
            ((Point)(ref position))._002Ector(chest.x, chest.y);
            if (IsAGoodSpot(position))
            {
                ClearCaches();
                ((Point)(ref position2))._002Ector(position.X, position.Y + 1);
                FindBoulderTrapSpots(position2);
                FindDartTrapSpots(position2);
                if (AreThereEnoughTraps() && (structures == null || structures.CanPlace(new Rectangle(position.X, position.Y, 1, 1), array, 10)))
                {
                    list.Add(j);
                }
            }
        }
        return list;
    }
References Terraria.GameContent.Biomes.DeadMansChestBiome.AreThereEnoughTraps(), Terraria.WorldBuilding.StructureMap.CanPlace(), Terraria.Main.chest, Terraria.GameContent.Biomes.DeadMansChestBiome.ClearCaches(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindBoulderTrapSpots(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpots(), Terraria.ID.TileID.Sets.GeneralPlacementTiles, Terraria.GameContent.Biomes.DeadMansChestBiome.IsAGoodSpot(), Terraria.Chest.x, and Terraria.Chest.y.