TModLoader: Terraria.GameContent.UI.Chat.ItemTagHandler.GenerateTag
GenerateTag()
static string Terraria.GameContent.UI.Chat.ItemTagHandler.GenerateTag (Item I) inline static
    {
        string text = "[i";
        if (ItemLoader.NeedsModSaving(I) || ItemIO.SaveGlobals(I) != null)
        {
            text = text + "/d" + ItemIO.ToBase64(I);
        }
        else
        {
            if (I.prefix != 0)
            {
                text = text + "/p" + I.prefix;
            }
            if (I.stack != 1)
            {
                text = text + "/s" + I.stack;
            }
        }
        return text + ":" + I.netID + "]";
    }
References Terraria.ModLoader.ItemLoader.NeedsModSaving(), Terraria.ModLoader.IO.ItemIO.SaveGlobals(), and Terraria.ModLoader.IO.ItemIO.ToBase64().
Referenced by Terraria.Main.GUIChatDrawInner(), and Terraria.UI.ItemSlot.OverrideLeftClick().