TModLoader: Terraria.DataStructures.SpriteDrawBuffer.QueueSprite
QueueSprite()
void Terraria.DataStructures.SpriteDrawBuffer.QueueSprite (Vector4 destinationRect, Vector2 origin, VertexColors colors, Vector4 sourceRectangle, Vector2 texCoordTL, Vector2 texCoordBR, Texture2D texture, float depth, float rotation) inline private
Definition at line 254 of file SpriteDrawBuffer.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0113: Unknown result type (might be due to invalid IL or missing references)
        //IL_0140: Unknown result type (might be due to invalid IL or missing references)
        //IL_0146: Unknown result type (might be due to invalid IL or missing references)
        //IL_014b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        float num = origin.X / sourceRectangle.Z;
        float num6 = origin.Y / sourceRectangle.W;
        float x = destinationRect.X;
        float y = destinationRect.Y;
        float z = destinationRect.Z;
        float w = destinationRect.W;
        float num2 = num * z;
        float num3 = num6 * w;
        float num4;
        float num5;
        if (rotation != 0f)
        {
            num4 = (float)Math.Cos(rotation);
            num5 = (float)Math.Sin(rotation);
        }
        else
        {
            num4 = 1f;
            num5 = 0f;
        }
        if (vertexCount + 4 >= maxSprites * 4)
        {
            maxSprites *= 2;
            CreateBuffers();
        }
        textures[vertexCount / 4] = (Texture)(object)texture;
        PushVertex(new Vector3(x + num2 * num4 - num3 * num5, y + num2 * num5 + num3 * num4, depth), colors.TopLeftColor, texCoordTL);
        PushVertex(new Vector3(x + (num2 + z) * num4 - num3 * num5, y + (num2 + z) * num5 + num3 * num4, depth), colors.TopRightColor, new Vector2(texCoordBR.X, texCoordTL.Y));
        PushVertex(new Vector3(x + num2 * num4 - (num3 + w) * num5, y + num2 * num5 + (num3 + w) * num4, depth), colors.BottomLeftColor, new Vector2(texCoordTL.X, texCoordBR.Y));
        PushVertex(new Vector3(x + (num2 + z) * num4 - (num3 + w) * num5, y + (num2 + z) * num5 + (num3 + w) * num4, depth), colors.BottomRightColor, texCoordBR);
    }
References Terraria.DataStructures.SpriteDrawBuffer.CreateBuffers(), Terraria.DataStructures.SpriteDrawBuffer.maxSprites, Terraria.DataStructures.SpriteDrawBuffer.PushVertex(), Terraria.DataStructures.SpriteDrawBuffer.textures, and Terraria.DataStructures.SpriteDrawBuffer.vertexCount.
Referenced by Terraria.DataStructures.SpriteDrawBuffer.Draw().