TModLoader: Terraria.GameContent.UI.Chat.ItemTagHandler.Parse
Parse()
TextSnippet ITagHandler. Terraria.GameContent.UI.Chat.ItemTagHandler.Parse (string text, Color baseColor, string options) inline private
Implements Terraria.UI.Chat.ITagHandler.
Definition at line 76 of file ItemTagHandler.cs.
    {
        Item item = new Item();
        if (int.TryParse(text, out var result) && result < ItemLoader.ItemCount)
        {
            item.netDefaults(result);
        }
        if (ItemID.Search.TryGetId(text, out result))
        {
            item.netDefaults(result);
        }
        if (item.type <= 0)
        {
            return new TextSnippet(text);
        }
        item.stack = 1;
        if (options != null)
        {
            string[] array = options.Split(',');
            for (int i = 0; i < array.Length; i++)
            {
                if (array[i].Length == 0)
                {
                    continue;
                }
                switch (array[i][0])
                {
                case 'd':
                    item = ItemIO.FromBase64(array[i].Substring(1));
                    break;
                case 's':
                case 'x':
                {
                    if (int.TryParse(array[i].Substring(1), out var result3))
                    {
                        item.stack = Utils.Clamp(result3, 1, item.maxStack);
                    }
                    break;
                }
                case 'p':
                {
                    if (int.TryParse(array[i].Substring(1), out var result2))
                    {
                        item.Prefix((byte)Utils.Clamp(result2, 0, PrefixLoader.PrefixCount));
                    }
                    break;
                }
                }
            }
        }
        string text2 = "";
        if (item.stack > 1)
        {
            text2 = " (" + item.stack + ")";
        }
        return new ItemSnippet(item)
        {
            Text = "[" + item.AffixName() + text2 + "]",
            CheckForHover = true,
            DeleteWhole = true
        };
    }
References Terraria.Item.AffixName(), Terraria.ModLoader.IO.ItemIO.FromBase64(), Terraria.ModLoader.ItemLoader.ItemCount, Terraria.Item.maxStack, Terraria.Item.netDefaults(), Terraria.Item.Prefix(), Terraria.ModLoader.PrefixLoader.PrefixCount, Terraria.ID.ItemID.Search, Terraria.Item.stack, and Terraria.Item.type.