TModLoader: Terraria.GameContent.Tile_Entities.TEWeaponsRack.Framing_CheckTile
Framing_CheckTile()
static void Terraria.GameContent.Tile_Entities.TEWeaponsRack.Framing_CheckTile (int callX, int callY) inline static
    {
        int num = 3;
        int num2 = 3;
        if (WorldGen.destroyObject)
        {
            return;
        }
        int num3 = callX;
        int num4 = callY;
        Tile tileSafely = Framing.GetTileSafely(callX, callY);
        num3 -= tileSafely.frameX / 18 % num;
        num4 -= tileSafely.frameY / 18 % num2;
        bool flag = false;
        for (int i = num3; i < num3 + num; i++)
        {
            for (int j = num4; j < num4 + num2; j++)
            {
                Tile tile = Main.tile[i, j];
                if (!tile.active() || tile.type != 471 || tile.wall == 0)
                {
                    flag = true;
                }
            }
        }
        if (!flag)
        {
            return;
        }
        int num5 = Find(num3, num4);
        if (num5 != -1 && ((TEWeaponsRack)TileEntity.ByID[num5]).item.stack > 0)
        {
            ((TEWeaponsRack)TileEntity.ByID[num5]).DropItem();
            if (Main.netMode != 2)
            {
                Main.LocalPlayer.InterruptItemUsageIfOverTile(471);
            }
        }
        WorldGen.destroyObject = true;
        bool drop = TileLoader.Drop(callX, callY, 471);
        for (int k = num3; k < num3 + num; k++)
        {
            for (int l = num4; l < num4 + num2; l++)
            {
                if (Main.tile[k, l].active() && Main.tile[k, l].type == 471)
                {
                    WorldGen.KillTile(k, l);
                }
            }
        }
        if (drop)
        {
            Item.NewItem(new EntitySource_TileBreak(num3, num4), num3 * 16, num4 * 16, 48, 48, 2699);
        }
        Kill(num3, num4);
        WorldGen.destroyObject = false;
    }
References Terraria.GameContent.Tile_Entities.TEWeaponsRack.TEWeaponsRack(), Terraria.Tile.active(), Terraria.DataStructures.TileEntity.ByID, Terraria.WorldGen.destroyObject, Terraria.ModLoader.TileLoader.Drop(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Find(), Terraria.Framing.GetTileSafely(), Terraria.Player.InterruptItemUsageIfOverTile(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Kill(), Terraria.WorldGen.KillTile(), Terraria.Main.LocalPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.TileFrame().