TModLoader: Terraria.GameContent.UI.States.WorkshopPublishInfoStateForMods.OnInitialize
OnInitialize()
override void Terraria.GameContent.UI.States.WorkshopPublishInfoStateForMods.OnInitialize () inline
Definition at line 128 of file WorkshopPublishInfoStateForMods.cs.
    {
        //IL_036c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0356: Unknown result type (might be due to invalid IL or missing references)
        base.OnInitialize();
        if (!Terraria.ModLoader.ModLoader.TryGetMod(_dataObject.Name, out var mod))
        {
            return;
        }
        Dictionary<GameCulture, int> localizationCounts = LocalizationLoader.GetLocalizationCounts(mod);
        int countMaxEntries = localizationCounts.DefaultIfEmpty().Max((KeyValuePair<GameCulture, int> x) => x.Value);
        Logging.tML.Info((object)("Determining localization progress for " + mod.Name + ":"));
        foreach (GroupOptionButton<WorkshopTagOption> tagOption in _tagOptions)
        {
            if (tagOption.OptionValue.NameKey.StartsWith("tModLoader.TagsLanguage_"))
            {
                GameCulture culture = tagOption.OptionValue.NameKey.Split('_')[1] switch
                {
                    "English" => GameCulture.FromName("en-US"),
                    "Spanish" => GameCulture.FromName("es-ES"),
                    "French" => GameCulture.FromName("fr-FR"),
                    "Italian" => GameCulture.FromName("it-IT"),
                    "Russian" => GameCulture.FromName("ru-RU"),
                    "Chinese" => GameCulture.FromName("zh-Hans"),
                    "Portuguese" => GameCulture.FromName("pt-BR"),
                    "German" => GameCulture.FromName("de-DE"),
                    "Polish" => GameCulture.FromName("pl-PL"),
                    _ => throw new NotImplementedException(),
                };
                localizationCounts.TryGetValue(culture, out var countOtherEntries);
                float localizationProgress = (float)countOtherEntries / (float)countMaxEntries;
                Logging.tML.Info((object)$"{culture.Name}, {countOtherEntries}/{countMaxEntries}, {localizationProgress:P0}, missing {countMaxEntries - countOtherEntries}");
                bool languageMostlyLocalized = localizationProgress > 0.75f;
                tagOption.SetCurrentOption(languageMostlyLocalized ? tagOption.OptionValue : null);
                tagOption.SetColor((Color)(tagOption.IsSelected ? new Color(192, 175, 235) : Colors.InventoryDefaultColor), 1f);
            }
        }
    }
References Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TmodFile >._dataObject, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TmodFile >._tagOptions, Terraria.Localization.GameCulture.FromName(), Terraria.ModLoader.LocalizationLoader.GetLocalizationCounts(), Terraria.ID.Colors.InventoryDefaultColor, Terraria.ModLoader.Logging.tML, and Terraria.ModLoader.ModLoader.TryGetMod().