TModLoader: Terraria.GameContent.UI.States.WorkshopPublishInfoStateForMods.CreateTmlDisclaimer
CreateTmlDisclaimer()
UIElement Terraria.GameContent.UI.States.WorkshopPublishInfoStateForMods.CreateTmlDisclaimer (string tagGroup) inline package
    {
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        float num = 60f;
        float num2 = 0f + num;
        GroupOptionButton<bool> groupOptionButton = new GroupOptionButton<bool>(option: true, null, null, Color.White, null, 1f, 0.5f, 16f);
        groupOptionButton.HAlign = 0.5f;
        groupOptionButton.VAlign = 0f;
        groupOptionButton.Width = StyleDimension.FromPixelsAndPercent(0f, 1f);
        groupOptionButton.Left = StyleDimension.FromPixels(0f);
        groupOptionButton.Height = StyleDimension.FromPixelsAndPercent(num2 + 4f, 0f);
        groupOptionButton.Top = StyleDimension.FromPixels(0f);
        groupOptionButton.ShowHighlightWhenSelected = false;
        groupOptionButton.SetCurrentOption(option: false);
        groupOptionButton.Width.Set(0f, 1f);
        UIElement uIElement = new UIElement
        {
            HAlign = 0.5f,
            VAlign = 1f,
            Width = new StyleDimension(0f, 1f),
            Height = new StyleDimension(num, 0f)
        };
        groupOptionButton.Append(uIElement);
        UIText uIText = new UIText(Language.GetText("tModLoader.WorkshopDisclaimer"))
        {
            HAlign = 0f,
            VAlign = 0f,
            Width = StyleDimension.FromPixelsAndPercent(-40f, 1f),
            Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
            TextColor = Color.Cyan,
            IgnoresMouseInteraction = true
        };
        uIText.PaddingLeft = 20f;
        uIText.PaddingRight = 20f;
        uIText.PaddingTop = 4f;
        uIText.IsWrapped = true;
        _tMLDisclaimerText = uIText;
        groupOptionButton.OnLeftClick += TmlDisclaimerText_OnClick;
        groupOptionButton.OnMouseOver += TmlDisclaimerText_OnMouseOver;
        groupOptionButton.OnMouseOut += TmlDisclaimerText_OnMouseOut;
        uIElement.Append(uIText);
        uIText.SetSnapPoint(tagGroup, 0);
        _tMLDisclaimerButton = uIText;
        return groupOptionButton;
    }
References Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TmodFile >._tMLDisclaimerButton, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TmodFile >._tMLDisclaimerText, Terraria.UI.UIElement.Append(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.GameContent.UI.States.WorkshopPublishInfoStateForMods.TmlDisclaimerText_OnClick(), Terraria.GameContent.UI.States.WorkshopPublishInfoStateForMods.TmlDisclaimerText_OnMouseOut(), and Terraria.GameContent.UI.States.WorkshopPublishInfoStateForMods.TmlDisclaimerText_OnMouseOver().