TModLoader: Terraria.Minecart.TrackCollision
TrackCollision()
static BitsByte Terraria.Minecart.TrackCollision (Player Player, ref Vector2 Position, ref Vector2 Velocity, ref Vector2 lastBoost, int Width, int Height, bool followDown, bool followUp, int fallStart, bool trackOnly, Mount::MountDelegatesData delegatesData) inline static
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_025d: Unknown result type (might be due to invalid IL or missing references)
        //IL_025f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0261: Unknown result type (might be due to invalid IL or missing references)
        //IL_0266: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_022e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0230: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_0237: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        //IL_0287: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        //IL_028e: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_071a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0336: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03da: Unknown result type (might be due to invalid IL or missing references)
        //IL_03aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0809: Unknown result type (might be due to invalid IL or missing references)
        //IL_080e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0733: Unknown result type (might be due to invalid IL or missing references)
        //IL_035e: Unknown result type (might be due to invalid IL or missing references)
        //IL_036b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0370: Unknown result type (might be due to invalid IL or missing references)
        //IL_0372: Unknown result type (might be due to invalid IL or missing references)
        //IL_0377: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_074a: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0404: Unknown result type (might be due to invalid IL or missing references)
        //IL_0763: Unknown result type (might be due to invalid IL or missing references)
        //IL_0412: Unknown result type (might be due to invalid IL or missing references)
        //IL_0825: Unknown result type (might be due to invalid IL or missing references)
        //IL_082c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0856: Unknown result type (might be due to invalid IL or missing references)
        //IL_0858: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0791: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_087f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0891: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05df: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07db: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07eb: Unknown result type (might be due to invalid IL or missing references)
        if (followDown && followUp)
        {
            followDown = false;
            followUp = false;
        }
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)(Width / 2) - 25f, (float)(Height / 2));
        Vector2 vector2 = Position + new Vector2((float)(Width / 2) - 25f, (float)(Height / 2)) + _trackMagnetOffset;
        Vector2 vector3 = Velocity;
        float num = ((Vector2)(ref vector3)).Length();
        ((Vector2)(ref vector3)).Normalize();
        Vector2 vector4 = vector2;
        Tile tile = default(Tile);
        bool flag = false;
        bool flag2 = true;
        int num12 = -1;
        int num20 = -1;
        int num21 = -1;
        TrackState trackState = TrackState.NoTrack;
        bool flag3 = false;
        bool flag4 = false;
        bool flag5 = false;
        bool flag6 = false;
        Vector2 vector5 = Vector2.Zero;
        Vector2 vector6 = Vector2.Zero;
        BitsByte result = default(BitsByte);
        while (true)
        {
            int num22 = (int)(vector4.X / 16f);
            int num23 = (int)(vector4.Y / 16f);
            int num24 = (int)vector4.X % 16 / 2;
            if (flag2)
            {
                num21 = num24;
            }
            bool flag7 = num24 != num21;
            if ((trackState == TrackState.OnBack || trackState == TrackState.OnTrack || trackState == TrackState.OnFront) && num22 != num12)
            {
                int num25 = ((trackState != TrackState.OnBack) ? tile.FrontTrack() : tile.BackTrack());
                switch ((!(vector3.X < 0f)) ? _rightSideConnection[num25] : _leftSideConnection[num25])
                {
                case 0:
                    num23--;
                    vector4.Y -= 2f;
                    break;
                case 2:
                    num23++;
                    vector4.Y += 2f;
                    break;
                }
            }
            TrackState trackState2 = TrackState.NoTrack;
            bool flag8 = false;
            if (num22 != num12 || num23 != num20)
            {
                if (flag2)
                {
                    flag2 = false;
                }
                else
                {
                    flag8 = true;
                }
                tile = Main.tile[num22, num23];
                if (tile == null)
                {
                    tile = (Main.tile[num22, num23] = default(Tile));
                }
                flag = ((tile.nactive() && tile.type == 314) ? true : false);
            }
            if (flag)
            {
                TrackState trackState3 = TrackState.NoTrack;
                int num26 = tile.FrontTrack();
                int num2 = tile.BackTrack();
                int num3 = _tileHeight[num26][num24];
                switch (num3)
                {
                case -4:
                    if (trackState == TrackState.OnFront)
                    {
                        if (trackOnly)
{
                            vector4 -= vector6;
                            num = 0f;
                            trackState2 = TrackState.OnFront;
                            flag6 = true;
                        }
                        else
{
                            trackState2 = TrackState.NoTrack;
                            flag5 = true;
                        }
                    }
                    break;
                case -1:
                    if (trackState == TrackState.OnFront)
                    {
                        vector4 -= vector6;
                        num = 0f;
                        trackState2 = TrackState.OnFront;
                        flag6 = true;
                    }
                    break;
                case -2:
                    if (trackState != TrackState.OnFront)
                    {
                        break;
                    }
                    if (trackOnly)
                    {
                        vector4 -= vector6;
                        num = 0f;
                        trackState2 = TrackState.OnFront;
                        flag6 = true;
                        break;
                    }
                    if (vector3.X < 0f)
                    {
                        float num6 = (float)(num22 * 16 + (num24 + 1) * 2) - vector4.X;
                        vector4.X += num6;
                        num += num6 / vector3.X;
                    }
                    vector3.X = 0f - vector3.X;
                    result[1] = true;
                    trackState2 = TrackState.OnFront;
                    break;
                case -3:
                    if (trackState == TrackState.OnFront)
                    {
                        trackState = TrackState.NoTrack;
                        Matrix val = ((!(Velocity.X > 0f)) ? ((_rightSideConnection[num26] != 2) ? Matrix.CreateRotationZ(-(float)Math.PI / 4f) : Matrix.CreateRotationZ((float)Math.PI / 4f)) : ((_leftSideConnection[num26] != 2) ? Matrix.CreateRotationZ((float)Math.PI / 4f) : Matrix.CreateRotationZ(-(float)Math.PI / 4f)));
                        vector5 = Vector2.Transform(new Vector2(Velocity.X, 0f), val);
                        vector5.X = Velocity.X;
                        flag4 = true;
                        num = 0f;
                    }
                    break;
                default:
                {
                    float num4 = num23 * 16 + num3;
                    if (num22 != num12 && trackState == TrackState.NoTrack && vector4.Y > num4 && vector4.Y - num4 < 2f)
                    {
                        flag8 = false;
                        trackState = TrackState.AboveFront;
                    }
                    TrackState trackState4 = ((!(vector4.Y < num4)) ? ((!(vector4.Y > num4)) ? TrackState.OnTrack : TrackState.BelowTrack) : TrackState.AboveTrack);
                    if (num2 != -1)
                    {
                        float num5 = num23 * 16 + _tileHeight[num2][num24];
                        trackState3 = ((!(vector4.Y < num5)) ? ((!(vector4.Y > num5)) ? TrackState.OnTrack : TrackState.BelowTrack) : TrackState.AboveTrack);
                    }
                    switch (trackState4)
                    {
                    case TrackState.OnTrack:
                        trackState2 = ((trackState3 == TrackState.OnTrack) ? TrackState.OnTrack : TrackState.OnFront);
                        break;
                    case TrackState.AboveTrack:
                        trackState2 = trackState3 switch
{
                            TrackState.OnTrack => TrackState.OnBack,
                            TrackState.BelowTrack => TrackState.AboveFront,
                            TrackState.AboveTrack => TrackState.AboveTrack,
                            _ => TrackState.AboveFront,
                        };
                        break;
                    case TrackState.BelowTrack:
                        trackState2 = trackState3 switch
{
                            TrackState.OnTrack => TrackState.OnBack,
                            TrackState.AboveTrack => TrackState.AboveBack,
                            TrackState.BelowTrack => TrackState.BelowTrack,
                            _ => TrackState.BelowTrack,
                        };
                        break;
                    }
                    break;
                }
                }
            }
            if (!flag8)
            {
                if (trackState != trackState2)
                {
                    bool flag9 = false;
                    if (flag7 || vector3.Y > 0f)
                    {
                        switch (trackState)
{
                        case TrackState.AboveTrack:
                            switch (trackState2)
{
                            case TrackState.AboveFront:
                                trackState2 = TrackState.OnBack;
                                break;
                            case TrackState.AboveBack:
                                trackState2 = TrackState.OnFront;
                                break;
                            case TrackState.AboveTrack:
                                trackState2 = TrackState.OnTrack;
                                break;
                            }
                            break;
                        case TrackState.AboveFront:
                            if (trackState2 == TrackState.BelowTrack)
{
                                trackState2 = TrackState.OnFront;
                            }
                            break;
                        case TrackState.AboveBack:
                            if (trackState2 == TrackState.BelowTrack)
{
                                trackState2 = TrackState.OnBack;
                            }
                            break;
                        case TrackState.OnFront:
                            trackState2 = TrackState.OnFront;
                            flag9 = true;
                            break;
                        case TrackState.OnBack:
                            trackState2 = TrackState.OnBack;
                            flag9 = true;
                            break;
                        case TrackState.OnTrack:
{
                            int num7 = _tileHeight[tile.FrontTrack()][num24];
                            int num8 = _tileHeight[tile.BackTrack()][num24];
                            trackState2 = ((!followDown) ? ((!followUp) ? TrackState.OnFront : ((num7 >= num8) ? TrackState.OnBack : TrackState.OnFront)) : ((num7 >= num8) ? TrackState.OnFront : TrackState.OnBack));
                            flag9 = true;
                            break;
                        }
                        }
                        int num9 = -1;
                        switch (trackState2)
{
                        case TrackState.OnTrack:
                        case TrackState.OnFront:
                            num9 = tile.FrontTrack();
                            break;
                        case TrackState.OnBack:
                            num9 = tile.BackTrack();
                            break;
                        }
                        if (num9 != -1)
{
                            if (!flag9 && Velocity.Y > Player.defaultGravity)
{
                                int num10 = (int)(Position.Y / 16f);
                                if (fallStart < num10 - 1)
{
                                    delegatesData.MinecartLandingSound(Player, Position, Width, Height);
                                    WheelSparks(delegatesData.MinecartDust, Position, Width, Height, 10);
                                }
                            }
                            if (trackState == TrackState.AboveFront && _trackType[num9] == 1)
{
                                flag3 = true;
                            }
                            vector3.Y = 0f;
                            vector4.Y = num23 * 16 + _tileHeight[num9][num24];
                        }
                    }
                }
            }
            else if (trackState2 == TrackState.OnFront || trackState2 == TrackState.OnBack || trackState2 == TrackState.OnTrack)
            {
                if (flag && _trackType[tile.FrontTrack()] == 1)
                {
                    flag3 = true;
                }
                vector3.Y = 0f;
            }
            if (trackState2 == TrackState.OnFront)
            {
                int num11 = tile.FrontTrack();
                if (_trackType[num11] == 2 && lastBoost.X == 0f && lastBoost.Y == 0f)
                {
                    lastBoost = new Vector2((float)num22, (float)num23);
                    if (_boostLeft[num11])
                    {
                        result[4] = true;
                    }
                    else
                    {
                        result[5] = true;
                    }
                }
            }
            num21 = num24;
            trackState = trackState2;
            num12 = num22;
            num20 = num23;
            if (num > 0f)
            {
                float num13 = vector4.X % 2f;
                float num14 = vector4.Y % 2f;
                float num15 = 3f;
                float num16 = 3f;
                if (vector3.X < 0f)
                {
                    num15 = num13 + 0.125f;
                }
                else if (vector3.X > 0f)
                {
                    num15 = 2f - num13;
                }
                if (vector3.Y < 0f)
                {
                    num16 = num14 + 0.125f;
                }
                else if (vector3.Y > 0f)
                {
                    num16 = 2f - num14;
                }
                if (num15 == 3f && num16 == 3f)
                {
                    break;
                }
                float num17 = Math.Abs(num15 / vector3.X);
                float num18 = Math.Abs(num16 / vector3.Y);
                float num19 = ((num17 < num18) ? num17 : num18);
                if (num19 > num)
                {
                    vector6 = vector3 * num;
                    num = 0f;
                }
                else
                {
                    vector6 = vector3 * num19;
                    num -= num19;
                }
                vector4 += vector6;
                continue;
            }
            if (lastBoost.X != (float)num12 || lastBoost.Y != (float)num20)
            {
                lastBoost = Vector2.Zero;
            }
            break;
        }
        if (flag3)
        {
            result[3] = true;
        }
        if (flag5)
        {
            Velocity.X = vector4.X - vector2.X;
            Velocity.Y = Player.defaultGravity;
        }
        else if (flag4)
        {
            result[2] = true;
            Velocity = vector5;
        }
        else if (result[1])
        {
            Velocity.X = 0f - Velocity.X;
            Position.X = vector4.X - _trackMagnetOffset.X - vector.X - Velocity.X;
            if (vector3.Y == 0f)
            {
                Velocity.Y = 0f;
            }
        }
        else
        {
            if (flag6)
            {
                Velocity.X = vector4.X - vector2.X;
            }
            if (vector3.Y == 0f)
            {
                Velocity.Y = 0f;
            }
        }
        Position.Y += vector4.Y - vector2.Y - Velocity.Y;
        Position.Y = (float)Math.Round(Position.Y, 2);
        if (trackState == TrackState.OnTrack || (uint)(trackState - 5) <= 1u)
        {
            result[0] = true;
        }
        return result;
    }
References Terraria.Minecart._boostLeft, Terraria.Minecart._leftSideConnection, Terraria.Minecart._rightSideConnection, Terraria.Minecart._tileHeight, Terraria.Minecart._trackMagnetOffset, Terraria.Minecart._trackType, Terraria.Player.defaultGravity, Terraria.Tile.nactive(), Terraria.Main.tile, and Terraria.Minecart.WheelSparks().
Referenced by Terraria.Minecart.GetWheelsPositions(), and Terraria.Player.Update().