TModLoader: Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.Draw
Draw()
void Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.Draw () inline
Implements Terraria.GameContent.UI.IMultiplayerClosePlayersOverlay.
    {
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_0206: Unknown result type (might be due to invalid IL or missing references)
        //IL_0208: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0342: Unknown result type (might be due to invalid IL or missing references)
        int teamNamePlateDistance = Main.teamNamePlateDistance;
        if (teamNamePlateDistance <= 0)
        {
            return;
        }
        _playerOnScreenCache.Clear();
        _playerOffScreenCache.Clear();
        SpriteBatch spriteBatch = Main.spriteBatch;
        PlayerInput.SetZoom_World();
        int screenWidth = Main.screenWidth;
        int screenHeight = Main.screenHeight;
        Vector2 screenPosition = Main.screenPosition;
        PlayerInput.SetZoom_UI();
        int num = teamNamePlateDistance * 8;
        Player[] player = Main.player;
        int myPlayer = Main.myPlayer;
        byte mouseTextColor = Main.mouseTextColor;
        Color[] teamColor = Main.teamColor;
        _ = Main.screenPosition;
        Player player2 = player[myPlayer];
        float num2 = (float)(int)mouseTextColor / 255f;
        if (player2.team == 0)
        {
            return;
        }
        DynamicSpriteFont value = FontAssets.MouseText.Value;
        Color color = default(Color);
        for (int i = 0; i < 255; i++)
        {
            if (i == myPlayer)
            {
                continue;
            }
            Player player3 = player[i];
            if (!player3.active || player3.dead || player3.team != player2.team)
            {
                continue;
            }
            string name = player3.name;
            GetDistance(screenWidth, screenHeight, screenPosition, player2, value, player3, name, out var namePlatePos, out var namePlateDist, out var measurement);
            ((Color)(ref color))._002Ector((int)(byte)((float)(int)((Color)(ref teamColor[player3.team])).R * num2), (int)(byte)((float)(int)((Color)(ref teamColor[player3.team])).G * num2), (int)(byte)((float)(int)((Color)(ref teamColor[player3.team])).B * num2), (int)mouseTextColor);
            if (namePlateDist > 0f)
            {
                float num3 = player3.Distance(player2.Center);
                if (!(num3 > (float)num))
                {
                    float num4 = 20f;
                    float num5 = -27f;
                    num5 -= (measurement.X - 85f) / 2f;
                    string textValue = Language.GetTextValue("GameUI.PlayerDistance", (int)(num3 / 16f * 2f));
                    Vector2 npDistPos = value.MeasureString(textValue);
                    npDistPos.X = namePlatePos.X - num5;
                    npDistPos.Y = namePlatePos.Y + measurement.Y / 2f - npDistPos.Y / 2f - num4;
                    _playerOffScreenCache.Add(new PlayerOffScreenCache(name, namePlatePos, color, npDistPos, textValue, player3, measurement));
                }
            }
            else
            {
                _playerOnScreenCache.Add(new PlayerOnScreenCache(name, namePlatePos, color));
            }
        }
        spriteBatch.End();
        spriteBatch.Begin((SpriteSortMode)0, (BlendState)null, (SamplerState)null, (DepthStencilState)null, (RasterizerState)null, (Effect)null, Main.UIScaleMatrix);
        for (int j = 0; j < _playerOnScreenCache.Count; j++)
        {
            _playerOnScreenCache[j].DrawPlayerName_WhenPlayerIsOnScreen(spriteBatch);
        }
        for (int k = 0; k < _playerOffScreenCache.Count; k++)
        {
            _playerOffScreenCache[k].DrawPlayerName(spriteBatch);
        }
        for (int l = 0; l < _playerOffScreenCache.Count; l++)
        {
            _playerOffScreenCache[l].DrawPlayerDistance(spriteBatch);
        }
        spriteBatch.End();
        spriteBatch.Begin((SpriteSortMode)0, (BlendState)null, (SamplerState)null, (DepthStencilState)null, (RasterizerState)null, (Effect)null, Main.UIScaleMatrix);
        for (int m = 0; m < _playerOffScreenCache.Count; m++)
        {
            _playerOffScreenCache[m].DrawLifeBar();
        }
        spriteBatch.End();
        spriteBatch.Begin((SpriteSortMode)1, (BlendState)null, (SamplerState)null, (DepthStencilState)null, (RasterizerState)null, (Effect)null, Main.UIScaleMatrix);
        for (int n = 0; n < _playerOffScreenCache.Count; n++)
        {
            _playerOffScreenCache[n].DrawPlayerHead();
        }
    }
References Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay._playerOffScreenCache, Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay._playerOnScreenCache, Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.GetDistance(), Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameInput.PlayerInput.SetZoom_World(), Terraria.Main.spriteBatch, Terraria.Main.teamColor, Terraria.Main.teamNamePlateDistance, and Terraria.Main.UIScaleMatrix.