TModLoader: Terraria.GameContent.UI.Elements.UISelectableTextPanel.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UISelectableTextPanel< T >.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.GameContent.UI.Elements.UIPanel.
Definition at line 36 of file UISelectableTextPanel.cs.
    {
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        if (_drawPanel)
        {
            CalculatedStyle dimensions = GetDimensions();
            int num = 4;
            int num2 = 10;
            int num3 = 10;
            Utils.DrawSplicedPanel(spriteBatch, _BasePanelTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, num2, num2, num3, num3, Color.Lerp(Color.Black, _color, 0.8f) * 0.5f);
            if (IsSelected != null && IsSelected(this))
            {
                Utils.DrawSplicedPanel(spriteBatch, _BasePanelTexture.Value, (int)dimensions.X + num, (int)dimensions.Y + num, (int)dimensions.Width - num * 2, (int)dimensions.Height - num * 2, num2, num2, num3, num3, Color.Lerp(_color, Color.White, 0.7f) * 0.5f);
            }
            if (base.IsMouseHovering)
            {
                Utils.DrawSplicedPanel(spriteBatch, _hoveredBorderTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, num2, num2, num3, num3, Color.White);
            }
        }
        DrawText(spriteBatch);
    }
References Terraria.GameContent.UI.Elements.UISelectableTextPanel< T >._BasePanelTexture, Terraria.GameContent.UI.Elements.UITextPanel< T >._color, Terraria.GameContent.UI.Elements.UITextPanel< T >._drawPanel, Terraria.GameContent.UI.Elements.UISelectableTextPanel< T >._hoveredBorderTexture, Terraria.Utils.DrawSplicedPanel(), Terraria.GameContent.UI.Elements.UITextPanel< T >.DrawText(), Terraria.UI.UIElement.GetDimensions(), and Terraria.GameContent.UI.Elements.UISelectableTextPanel< T >.IsSelected.