TModLoader: Terraria.GameContent.Skies.AmbientSky.HellBatsGoupSkyEntity.CreateGroup
CreateGroup()
static List< HellBatsGoupSkyEntity > Terraria.GameContent.Skies.AmbientSky.HellBatsGoupSkyEntity.CreateGroup (Player player, FastRandom random) inline static
        {
            //IL_002d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0031: Unknown result type (might be due to invalid IL or missing references)
            //IL_0037: Unknown result type (might be due to invalid IL or missing references)
            //IL_003a: Invalid comparison between Unknown and I4
            //IL_0065: Unknown result type (might be due to invalid IL or missing references)
            //IL_0040: Unknown result type (might be due to invalid IL or missing references)
            //IL_004c: Unknown result type (might be due to invalid IL or missing references)
            //IL_010d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0117: Unknown result type (might be due to invalid IL or missing references)
            //IL_011c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0148: Unknown result type (might be due to invalid IL or missing references)
            //IL_016a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0174: Unknown result type (might be due to invalid IL or missing references)
            //IL_0179: Unknown result type (might be due to invalid IL or missing references)
            //IL_017e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0185: Unknown result type (might be due to invalid IL or missing references)
            //IL_0187: Unknown result type (might be due to invalid IL or missing references)
            //IL_0190: Unknown result type (might be due to invalid IL or missing references)
            //IL_01b2: Unknown result type (might be due to invalid IL or missing references)
            //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
            //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
            //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
            List<HellBatsGoupSkyEntity> list = new List<HellBatsGoupSkyEntity>();
            int num = 100;
            int num2 = random.Next(20, 40);
            VirtualCamera virtualCamera = new VirtualCamera(player);
            SpriteEffects spriteEffects = (SpriteEffects)(!(Main.WindForVisuals > 0f));
            Vector2 vector = default(Vector2);
            if ((int)spriteEffects == 1)
            {
                vector.X = virtualCamera.Position.X + virtualCamera.Size.X + (float)num;
            }
            else
            {
                vector.X = virtualCamera.Position.X - (float)num;
            }
            vector.Y = random.NextFloat() * 800f + (float)(Main.UnderworldLayer * 16);
            float num3 = random.NextFloat() * 5f + 3f;
            int num4 = random.Next(30, 61) * 60;
            Vector2 vector2 = default(Vector2);
            ((Vector2)(ref vector2))._002Ector(random.NextFloat() * 0.5f + 0.5f, random.NextFloat() * 0.5f + 0.5f);
            Vector2 targetOffset = new Vector2(random.NextFloat() * 2f - 1f, random.NextFloat() * 2f - 1f) * 100f;
            for (int i = 0; i < num2; i++)
            {
                HellBatsGoupSkyEntity hellBatsGoupSkyEntity = new HellBatsGoupSkyEntity(player, random);
                hellBatsGoupSkyEntity.Depth = num3 + random.NextFloat() * 0.5f;
                hellBatsGoupSkyEntity.Position = vector + new Vector2(random.NextFloat() * 20f - 10f, random.NextFloat() * 3f) * 50f;
                hellBatsGoupSkyEntity.Effects = spriteEffects;
                hellBatsGoupSkyEntity.SetPositionInWorldBasedOnScreenSpace(hellBatsGoupSkyEntity.Position);
                hellBatsGoupSkyEntity.LifeTime = num4 + random.Next(301);
                hellBatsGoupSkyEntity.SetMagnetization(vector2 * (random.NextFloat() * 0.3f + 0.85f) * 0.05f, targetOffset);
                list.Add(hellBatsGoupSkyEntity);
            }
            return list;
        }
References Terraria.GameContent.Skies.AmbientSky.HellBatsGoupSkyEntity.HellBatsGoupSkyEntity(), Terraria.Utilities.FastRandom.Next(), Terraria.Utilities.FastRandom.NextFloat(), Terraria.Main.UnderworldLayer, and Terraria.Main.WindForVisuals.
Referenced by Terraria.GameContent.Skies.AmbientSky.Spawn().