TModLoader: Terraria.ModLoader.WallLoader.KillSound
KillSound()
static bool Terraria.ModLoader.WallLoader.KillSound (int i, int j, int type, bool fail) inline static
Definition at line 168 of file WallLoader.cs.
    {
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        Func<int, int, int, bool, bool>[] hookKillSound = HookKillSound;
        for (int k = 0; k < hookKillSound.Length; k++)
        {
            if (!hookKillSound[k](i, j, type, fail))
            {
                return false;
            }
        }
        ModWall modWall = GetWall(type);
        if (modWall != null)
        {
            if (!modWall.KillSound(i, j, fail))
            {
                return false;
            }
            SoundEngine.PlaySound(modWall.HitSound, (Vector2?)new Vector2((float)(i * 16), (float)(j * 16)));
            return false;
        }
        return true;
    }
References Terraria.ModLoader.WallLoader.GetWall(), Terraria.ModLoader.WallLoader.HookKillSound, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.WorldGen.KillWall_PlaySounds().