TModLoader: Terraria.ModLoader.WallLoader.Drop
Drop()
static bool Terraria.ModLoader.WallLoader.Drop (int i, int j, int type, ref int dropType) inline static
    {
        DelegateDrop[] hookDrop = HookDrop;
        for (int k = 0; k < hookDrop.Length; k++)
        {
            if (!hookDrop[k](i, j, type, ref dropType))
            {
                return false;
            }
        }
        ModWall modWall = GetWall(type);
        if (modWall != null)
        {
            if (wallTypeToItemType.TryGetValue(type, out var value))
            {
                dropType = value;
            }
            return modWall.Drop(i, j, ref dropType);
        }
        return true;
    }
References Terraria.ModLoader.WallLoader.DelegateDrop(), Terraria.ModLoader.WallLoader.GetWall(), Terraria.ModLoader.WallLoader.HookDrop, and Terraria.ModLoader.WallLoader.wallTypeToItemType.
Referenced by Terraria.WorldGen.KillWall_DropItems().