TModLoader: Terraria.ModLoader.WallLoader.GetWall
GetWall()
static ModWall Terraria.ModLoader.WallLoader.GetWall (int type) inline static
Gets the ModWall instance with the given type. If no ModWall with the given type exists, returns null.
    {
        if (type < WallID.Count || type >= WallCount)
        {
            return null;
        }
        return walls[type - WallID.Count];
    }
References Terraria.ID.WallID.Count, Terraria.ModLoader.WallLoader.WallCount, and Terraria.ModLoader.WallLoader.walls.
Referenced by Terraria.ModLoader.WallLoader.CanExplode(), Terraria.ModLoader.WallLoader.CanPlace(), Terraria.ModLoader.WallLoader.CreateDust(), Terraria.ModLoader.WallLoader.Drop(), Terraria.ModLoader.ModContent.GetModWall(), Terraria.ModLoader.WallLoader.KillSound(), Terraria.ModLoader.WallLoader.KillWall(), Terraria.WorldGen.KillWall_MakeWallDust(), Terraria.ModLoader.WallLoader.ModifyLight(), Terraria.ModLoader.MapLoader.ModMapOption(), Terraria.ModLoader.WallLoader.NumDust(), Terraria.ModLoader.WallLoader.PlaceInWorld(), Terraria.ModLoader.WallLoader.PostDraw(), Terraria.ModLoader.WallLoader.PreDraw(), Terraria.ModLoader.WallLoader.RandomUpdate(), Terraria.ModLoader.WallLoader.WallFrame(), and Terraria.ModLoader.IO.MapIO.WriteModMap().