TModLoader: Terraria.ModLoader.WallLoader.ResizeArrays
ResizeArrays()
static void Terraria.ModLoader.WallLoader.ResizeArrays (bool unloading = false) inline static package
    {
        Array.Resize(ref TextureAssets.Wall, nextWall);
        LoaderUtils.ResetStaticMembers(typeof(WallID));
        Array.Resize(ref Main.wallHouse, nextWall);
        Array.Resize(ref Main.wallDungeon, nextWall);
        Array.Resize(ref Main.wallLight, nextWall);
        Array.Resize(ref Main.wallBlend, nextWall);
        Array.Resize(ref Main.wallLargeFrames, nextWall);
        Array.Resize(ref Main.wallFrame, nextWall);
        Array.Resize(ref Main.wallFrameCounter, nextWall);
        ModLoader.BuildGlobalHook<GlobalWall, Func<int, int, int, bool, bool>>(ref HookKillSound, globalWalls, (GlobalWall g) => g.KillSound);
        ModLoader.BuildGlobalHook<GlobalWall, DelegateNumDust>(ref HookNumDust, globalWalls, (GlobalWall g) => g.NumDust);
        ModLoader.BuildGlobalHook<GlobalWall, DelegateCreateDust>(ref HookCreateDust, globalWalls, (GlobalWall g) => g.CreateDust);
        ModLoader.BuildGlobalHook<GlobalWall, DelegateDrop>(ref HookDrop, globalWalls, (GlobalWall g) => g.Drop);
        ModLoader.BuildGlobalHook<GlobalWall, DelegateKillWall>(ref HookKillWall, globalWalls, (GlobalWall g) => g.KillWall);
        ModLoader.BuildGlobalHook<GlobalWall, DelegateWallFrame>(ref HookWallFrame, globalWalls, (GlobalWall g) => g.WallFrame);
        ModLoader.BuildGlobalHook<GlobalWall, Func<int, int, int, bool>>(ref HookCanPlace, globalWalls, (GlobalWall g) => g.CanPlace);
        ModLoader.BuildGlobalHook<GlobalWall, Func<int, int, int, bool>>(ref HookCanExplode, globalWalls, (GlobalWall g) => g.CanExplode);
        ModLoader.BuildGlobalHook<GlobalWall, DelegateModifyLight>(ref HookModifyLight, globalWalls, (GlobalWall g) => g.ModifyLight);
        ModLoader.BuildGlobalHook<GlobalWall, Action<int, int, int>>(ref HookRandomUpdate, globalWalls, (GlobalWall g) => g.RandomUpdate);
        ModLoader.BuildGlobalHook<GlobalWall, Func<int, int, int, SpriteBatch, bool>>(ref HookPreDraw, globalWalls, (GlobalWall g) => g.PreDraw);
        ModLoader.BuildGlobalHook<GlobalWall, Action<int, int, int, SpriteBatch>>(ref HookPostDraw, globalWalls, (GlobalWall g) => g.PostDraw);
        ModLoader.BuildGlobalHook<GlobalWall, Action<int, int, int, Item>>(ref HookPlaceInWorld, globalWalls, (GlobalWall g) => g.PlaceInWorld);
        if (!unloading)
        {
            loaded = true;
        }
    }
References Terraria.ModLoader.WallLoader.DelegateCreateDust(), Terraria.ModLoader.WallLoader.DelegateDrop(), Terraria.ModLoader.WallLoader.DelegateKillWall(), Terraria.ModLoader.WallLoader.DelegateModifyLight(), Terraria.ModLoader.WallLoader.DelegateNumDust(), Terraria.ModLoader.WallLoader.DelegateWallFrame(), Terraria.ModLoader.WallLoader.globalWalls, Terraria.ModLoader.WallLoader.HookCanExplode, Terraria.ModLoader.WallLoader.HookCanPlace, Terraria.ModLoader.WallLoader.HookCreateDust, Terraria.ModLoader.WallLoader.HookDrop, Terraria.ModLoader.WallLoader.HookKillSound, Terraria.ModLoader.WallLoader.HookKillWall, Terraria.ModLoader.WallLoader.HookModifyLight, Terraria.ModLoader.WallLoader.HookNumDust, Terraria.ModLoader.WallLoader.HookPlaceInWorld, Terraria.ModLoader.WallLoader.HookPostDraw, Terraria.ModLoader.WallLoader.HookPreDraw, Terraria.ModLoader.WallLoader.HookRandomUpdate, Terraria.ModLoader.WallLoader.HookWallFrame, Terraria.ModLoader.WallLoader.loaded, Terraria.ModLoader.WallLoader.nextWall, Terraria.ModLoader.Core.LoaderUtils.ResetStaticMembers(), Terraria.GameContent.TextureAssets.Wall, Terraria.Main.wallBlend, Terraria.Main.wallDungeon, Terraria.Main.wallFrame, Terraria.Main.wallFrameCounter, Terraria.Main.wallHouse, Terraria.Main.wallLargeFrames, and Terraria.Main.wallLight.
Referenced by Terraria.ModLoader.ModContent.ResizeArrays().