TModLoader: Terraria.ModLoader.WallLoader.PlaceInWorld
PlaceInWorld()
static void Terraria.ModLoader.WallLoader.PlaceInWorld (int i, int j, Item item) inline static
    {
        int type = item.createWall;
        if (type >= 0)
        {
            Action<int, int, int, Item>[] hookPlaceInWorld = HookPlaceInWorld;
            for (int k = 0; k < hookPlaceInWorld.Length; k++)
            {
                hookPlaceInWorld[k](i, j, type, item);
            }
            GetWall(type)?.PlaceInWorld(i, j, item);
        }
    }
References Terraria.Item.createWall, Terraria.ModLoader.WallLoader.GetWall(), Terraria.ModLoader.WallLoader.HookPlaceInWorld, and Terraria.ModLoader.ModBlockType.PlaceInWorld().
Referenced by Terraria.Player.PlaceThing_Walls().