TModLoader: Terraria.ModLoader.NPCLoader.GetNPC
GetNPC()
static ModNPC Terraria.ModLoader.NPCLoader.GetNPC (int type) inline static
Gets the ModNPC template instance corresponding to the specified type (not the clone/new instance which gets added to NPCs as the game is played).
Parameters
type The type of the npc
Returns
The ModNPC instance in the F:Terraria.ModLoader.NPCLoader.npcs array, null if not found.
Definition at line 295 of file NPCLoader.cs.
    {
        if (type < NPCID.Count || type >= NPCCount)
        {
            return null;
        }
        return npcs[type - NPCID.Count];
    }
References Terraria.ID.NPCID.Count, Terraria.ModLoader.NPCLoader.NPCCount, and Terraria.ModLoader.NPCLoader.npcs.
Referenced by Terraria.ModLoader.NPCLoader.AddShops(), Terraria.ModLoader.NPCLoader.CheckConditions(), Terraria.ModLoader.ModContent.GetModNPC(), Terraria.ModLoader.Config.UI.NPCDefinitionElement.GetPassedOptionElements(), Terraria.ModLoader.NPCShopDatabase.GetShopName(), Terraria.ModLoader.NPCLoader.ModifyActiveShop(), Terraria.Item.NPCtoBanner(), Terraria.ModLoader.IO.WorldIO.SaveNPCBestiaryChats(), Terraria.ModLoader.IO.WorldIO.SaveNPCBestiaryKills(), Terraria.ModLoader.IO.WorldIO.SaveNPCBestiarySights(), Terraria.ModLoader.IO.WorldIO.SaveNPCKillCounts(), Terraria.ModLoader.IO.WorldIO.SaveTownManager(), Terraria.ModLoader.NPCLoader.SetDefaults(), and Terraria.ModLoader.NPCLoader.SpawnNPC().