TModLoader: Terraria.ModLoader.NPCLoader.ModifyActiveShop
ModifyActiveShop()
static void Terraria.ModLoader.NPCLoader.ModifyActiveShop (NPC npc, string shopName, Item[] shopContents) inline static
Definition at line 1505 of file NPCLoader.cs.
    {
        GetNPC(npc.type)?.ModifyActiveShop(shopName, shopContents);
        EntityGlobalsEnumerator<GlobalNPC> enumerator = HookModifyActiveShop.Enumerate(npc).GetEnumerator();
        while (enumerator.MoveNext())
        {
            enumerator.Current.ModifyActiveShop(npc, shopName, shopContents);
        }
    }
References Terraria.ModLoader.NPCLoader.GetNPC(), Terraria.ModLoader.NPCLoader.HookModifyActiveShop, Terraria.ModLoader.ModNPC.ModifyActiveShop(), and Terraria.NPC.type.
Referenced by Terraria.Chest.SetupShop().