TModLoader: Terraria.ModLoader.NPCLoader.OnChatButtonClicked
OnChatButtonClicked()
static void Terraria.ModLoader.NPCLoader.OnChatButtonClicked (bool firstButton) inline static
Definition at line 1467 of file NPCLoader.cs.
    {
        NPC npc = Main.LocalPlayer.TalkNPC;
        string shopName = null;
        if (npc.ModNPC != null)
        {
            npc.ModNPC.OnChatButtonClicked(firstButton, ref shopName);
            SoundEngine.PlaySound(in SoundID.MenuTick);
            if (shopName != null)
            {
                Main.playerInventory = true;
                Main.stackSplit = 9999;
                Main.npcChatText = "";
                Main.SetNPCShopIndex(1);
                Main.instance.shop[Main.npcShop].SetupShop(NPCShopDatabase.GetShopName(npc.type, shopName), npc);
            }
        }
        EntityGlobalsEnumerator<GlobalNPC> enumerator = HookOnChatButtonClicked.Enumerate(npc).GetEnumerator();
        while (enumerator.MoveNext())
        {
            enumerator.Current.OnChatButtonClicked(npc, firstButton);
        }
    }
References Terraria.ModLoader.NPCShopDatabase.GetShopName(), Terraria.ModLoader.NPCLoader.HookOnChatButtonClicked, Terraria.Main.instance, Terraria.Main.LocalPlayer, Terraria.ID.SoundID.MenuTick, Terraria.NPC.ModNPC, Terraria.Main.npcShop, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.SetNPCShopIndex(), Terraria.Chest.SetupShop(), Terraria.Main.shop, Terraria.Player.TalkNPC, and Terraria.NPC.type.
Referenced by Terraria.Main.GUIChatDrawInner().