TModLoader: Terraria.ModLoader.NPCLoader.RegisterTownNPCMoodLocalizations
RegisterTownNPCMoodLocalizations()
static void Terraria.ModLoader.NPCLoader.RegisterTownNPCMoodLocalizations (ModNPC npc) inline static package
Definition at line 361 of file NPCLoader.cs.
    {
        if (!npc.NPC.townNPC || NPCID.Sets.IsTownPet[npc.NPC.type] || NPCID.Sets.NoTownNPCHappiness[npc.NPC.type])
        {
            return;
        }
        string prefix = npc.GetLocalizationKey("TownNPCMood");
        List<string> keys = new List<string> { "Content", "NoHome", "FarFromHome", "LoveSpace", "DislikeCrowded", "HateCrowded" };
        if (Main.ShopHelper._database.TryGetProfileByNPCID(npc.NPC.type, out var personalityProfile))
        {
            List<IShopPersonalityTrait> shopModifiers = personalityProfile.ShopModifiers;
            BiomePreferenceListTrait biomePreferenceList = (BiomePreferenceListTrait)shopModifiers.SingleOrDefault((IShopPersonalityTrait t) => t is BiomePreferenceListTrait);
            if (biomePreferenceList != null)
            {
                if (biomePreferenceList.Preferences.Any((BiomePreferenceListTrait.BiomePreference x) => x.Affection == AffectionLevel.Love))
                {
                    keys.Add("LoveBiome");
                }
                if (biomePreferenceList.Preferences.Any((BiomePreferenceListTrait.BiomePreference x) => x.Affection == AffectionLevel.Like))
                {
                    keys.Add("LikeBiome");
                }
                if (biomePreferenceList.Preferences.Any((BiomePreferenceListTrait.BiomePreference x) => x.Affection == AffectionLevel.Dislike))
                {
                    keys.Add("DislikeBiome");
                }
                if (biomePreferenceList.Preferences.Any((BiomePreferenceListTrait.BiomePreference x) => x.Affection == AffectionLevel.Hate))
                {
                    keys.Add("HateBiome");
                }
            }
            if (shopModifiers.Any((IShopPersonalityTrait t) => t is NPCPreferenceTrait nPCPreferenceTrait4 && nPCPreferenceTrait4.Level == AffectionLevel.Love))
            {
                keys.Add("LoveNPC");
            }
            if (shopModifiers.Any((IShopPersonalityTrait t) => t is NPCPreferenceTrait nPCPreferenceTrait3 && nPCPreferenceTrait3.Level == AffectionLevel.Like))
            {
                keys.Add("LikeNPC");
            }
            if (shopModifiers.Any((IShopPersonalityTrait t) => t is NPCPreferenceTrait nPCPreferenceTrait2 && nPCPreferenceTrait2.Level == AffectionLevel.Dislike))
            {
                keys.Add("DislikeNPC");
            }
            if (shopModifiers.Any((IShopPersonalityTrait t) => t is NPCPreferenceTrait nPCPreferenceTrait && nPCPreferenceTrait.Level == AffectionLevel.Hate))
            {
                keys.Add("HateNPC");
            }
        }
        keys.Add("LikeNPC_Princess");
        keys.Add("Princess_LovesNPC");
        foreach (string key in keys)
        {
            string oldKey = npc.Mod.GetLocalizationKey("TownNPCMood." + npc.Name + "." + key);
            if (key == "Princess_LovesNPC")
            {
                oldKey = "TownNPCMood_Princess.LoveNPC_" + npc.FullName;
            }
            string key2 = prefix + "." + key;
            string defaultValueKey = "TownNPCMood." + key;
            Language.GetOrRegister(key2, () => (!Language.Exists(oldKey)) ? Language.GetTextValue(defaultValueKey) : ("{$" + oldKey + "}"));
        }
    }
References Terraria.GameContent.ShopHelper._database, Terraria.Localization.Language.Exists(), Terraria.ModLoader.ModType< TEntity, TModType >.FullName, Terraria.ModLoader.Mod.GetLocalizationKey(), Terraria.Localization.Language.GetOrRegister(), Terraria.Localization.Language.GetTextValue(), Terraria.ID.NPCID.Sets.IsTownPet, Terraria.ModLoader.ModType< TEntity, TModType >.Mod, Terraria.ModLoader.ModType< TEntity, TModType >.Name, Terraria.ID.NPCID.Sets.NoTownNPCHappiness, Terraria.ModLoader.ModNPC.NPC, Terraria.Main.ShopHelper, Terraria.NPC.townNPC, Terraria.GameContent.Personalities.PersonalityDatabase.TryGetProfileByNPCID(), and Terraria.NPC.type.
Referenced by Terraria.ModLoader.NPCLoader.FinishSetup().