TModLoader: Terraria.ModLoader.NPCLoader.ChooseSpawn
ChooseSpawn()
static ? int Terraria.ModLoader.NPCLoader.ChooseSpawn (NPCSpawnInfo spawnInfo) inline static
    {
        NPCSpawnHelper.Reset();
        NPCSpawnHelper.DoChecks(spawnInfo);
        IDictionary<int, float> pool = new Dictionary<int, float>();
        pool[0] = 1f;
        foreach (ModNPC npc in npcs)
        {
            float weight2 = npc.SpawnChance(spawnInfo);
            if (weight2 > 0f)
            {
                pool[npc.NPC.type] = weight2;
            }
        }
        ReadOnlySpan<GlobalNPC> readOnlySpan = HookEditSpawnPool.Enumerate();
        for (int i = 0; i < readOnlySpan.Length; i++)
        {
            readOnlySpan[i].EditSpawnPool(pool, spawnInfo);
        }
        float totalWeight = 0f;
        foreach (int type2 in pool.Keys)
        {
            if (pool[type2] < 0f)
            {
                pool[type2] = 0f;
            }
            totalWeight += pool[type2];
        }
        float choice = (float)Main.rand.NextDouble() * totalWeight;
        foreach (int type in pool.Keys)
        {
            float weight = pool[type];
            if (choice < weight)
            {
                return type;
            }
            choice -= weight;
        }
        return null;
    }
References Terraria.ModLoader.Utilities.NPCSpawnHelper.DoChecks(), Terraria.ModLoader.NPCLoader.HookEditSpawnPool, Terraria.ModLoader.ModNPC.NPC, Terraria.ModLoader.NPCLoader.npcs, Terraria.Main.rand, Terraria.ModLoader.Utilities.NPCSpawnHelper.Reset(), Terraria.ModLoader.ModNPC.SpawnChance(), and Terraria.NPC.type.
Referenced by Terraria.NPC.SpawnNPC().