TModLoader: Terraria.ModLoader.NPCLoader.SpawnNPC
SpawnNPC()
static int Terraria.ModLoader.NPCLoader.SpawnNPC (int type, int tileX, int tileY) inline static
Definition at line 1330 of file NPCLoader.cs.
    {
        int npc = ((type >= NPCID.Count) ? GetNPC(type).SpawnNPC(tileX, tileY) : NPC.NewNPC(NPC.GetSpawnSourceForNaturalSpawn(), tileX * 16 + 8, tileY * 16, type));
        EntityGlobalsEnumerator<GlobalNPC> enumerator = HookSpawnNPC.Enumerate(Main.npc[npc]).GetEnumerator();
        while (enumerator.MoveNext())
        {
            enumerator.Current.SpawnNPC(npc, tileX, tileY);
        }
        return npc;
    }
References Terraria.ID.NPCID.Count, Terraria.ModLoader.NPCLoader.GetNPC(), Terraria.NPC.GetSpawnSourceForNaturalSpawn(), Terraria.ModLoader.NPCLoader.HookSpawnNPC, Terraria.NPC.NewNPC(), and Terraria.Main.npc.
Referenced by Terraria.NPC.SpawnNPC().