TModLoader: Terraria.ModLoader.NPCLoader.DrawHealthBar
DrawHealthBar() [1/2]
static bool Terraria.ModLoader.NPCLoader.DrawHealthBar (NPC npc, ref float scale) inline static
    {
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        Vector2 position = default(Vector2);
        ((Vector2)(ref position))._002Ector(npc.position.X + (float)(npc.width / 2), npc.position.Y + npc.gfxOffY);
        if (Main.HealthBarDrawSettings == 1)
        {
            position.Y += (float)npc.height + 10f + Main.NPCAddHeight(npc);
        }
        else if (Main.HealthBarDrawSettings == 2)
        {
            position.Y -= 24f + Main.NPCAddHeight(npc) / 2f;
        }
        EntityGlobalsEnumerator<GlobalNPC> enumerator = HookDrawHealthBar.Enumerate(npc).GetEnumerator();
        while (enumerator.MoveNext())
        {
            bool? result2 = enumerator.Current.DrawHealthBar(npc, Main.HealthBarDrawSettings, ref scale, ref position);
            if (result2.HasValue)
            {
                if (result2.Value)
                {
                    DrawHealthBar(npc, position, scale);
                }
                return false;
            }
        }
        if (IsModNPC(npc))
        {
            bool? result = npc.ModNPC.DrawHealthBar(Main.HealthBarDrawSettings, ref scale, ref position);
            if (result.HasValue)
            {
                if (result.Value)
                {
                    DrawHealthBar(npc, position, scale);
                }
                return false;
            }
        }
        return true;
    }
References Terraria.ModLoader.NPCLoader.DrawHealthBar(), Terraria.NPC.gfxOffY, Terraria.Main.HealthBarDrawSettings, Terraria.Entity.height, Terraria.ModLoader.NPCLoader.HookDrawHealthBar, Terraria.ModLoader.NPCLoader.IsModNPC(), Terraria.NPC.ModNPC, Terraria.Main.NPCAddHeight(), and Terraria.Entity.position.
Referenced by Terraria.ModLoader.NPCLoader.DrawHealthBar(), and Terraria.Main.DrawInterface_14_EntityHealthBars().