TModLoader: Terraria.ModLoader.NPCLoader.SetBestiary
SetBestiary()
static void Terraria.ModLoader.NPCLoader.SetBestiary (NPC npc, BestiaryDatabase database, BestiaryEntry bestiaryEntry) inline static
Definition at line 482 of file NPCLoader.cs.
    {
        if (IsModNPC(npc))
        {
            bestiaryEntry.Info.Add(npc.ModNPC.Mod.ModSourceBestiaryInfoElement);
            int[] spawnModBiomes = npc.ModNPC.SpawnModBiomes;
            foreach (int type in spawnModBiomes)
            {
                bestiaryEntry.Info.Add(LoaderManager.Get<BiomeLoader>().Get(type).ModBiomeBestiaryInfoElement);
            }
        }
        npc.ModNPC?.SetBestiary(database, bestiaryEntry);
        EntityGlobalsEnumerator<GlobalNPC> enumerator = HookSetBestiary.Enumerate(npc).GetEnumerator();
        while (enumerator.MoveNext())
        {
            enumerator.Current.SetBestiary(npc, database, bestiaryEntry);
        }
    }
References Terraria.ModLoader.Loader< T >.Get(), Terraria.ModLoader.NPCLoader.HookSetBestiary, Terraria.ModLoader.NPCLoader.IsModNPC(), and Terraria.NPC.ModNPC.
Referenced by Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddEmptyEntries_CrittersAndEnemies_Automated().