TModLoader: Terraria.ModLoader.NPCLoader.ResizeArrays
ResizeArrays()
static void Terraria.ModLoader.NPCLoader.ResizeArrays (bool unloading) inline static package
    {
        if (!unloading)
        {
            GlobalList<GlobalNPC>.FinishLoading(NPCCount);
        }
        Array.Resize(ref TextureAssets.Npc, NPCCount);
        LoaderUtils.ResetStaticMembers(typeof(NPCID));
        Main.ShopHelper.ReinitializePersonalityDatabase();
        NPCHappiness.RegisterVanillaNpcRelationships();
        Array.Resize(ref Main.townNPCCanSpawn, NPCCount);
        Array.Resize(ref Main.slimeRainNPC, NPCCount);
        Array.Resize(ref Main.npcCatchable, NPCCount);
        Array.Resize(ref Main.npcFrameCount, NPCCount);
        Array.Resize(ref Main.SceneMetrics.NPCBannerBuff, NPCCount);
        Array.Resize(ref NPC.killCount, NPCCount);
        Array.Resize(ref NPC.ShimmeredTownNPCs, NPCCount);
        Array.Resize(ref NPC.npcsFoundForCheckActive, NPCCount);
        Array.Resize(ref Lang._npcNameCache, NPCCount);
        Array.Resize(ref EmoteBubble.CountNPCs, NPCCount);
        Array.Resize(ref WorldGen.TownManager._hasRoom, NPCCount);
        Player[] player = Main.player;
        for (int j = 0; j < player.Length; j++)
        {
            Array.Resize(ref player[j].npcTypeNoAggro, NPCCount);
        }
        for (int i = NPCID.Count; i < NPCCount; i++)
        {
            Main.npcFrameCount[i] = 1;
            Lang._npcNameCache[i] = LocalizedText.Empty;
        }
    }
References Terraria.Lang._npcNameCache, Terraria.ID.NPCID.Count, Terraria.GameContent.UI.EmoteBubble.CountNPCs, Terraria.Localization.LocalizedText.Empty, Terraria.NPC.killCount, Terraria.GameContent.TextureAssets.Npc, Terraria.Main.npcCatchable, Terraria.ModLoader.NPCLoader.NPCCount, Terraria.Main.npcFrameCount, Terraria.NPC.npcsFoundForCheckActive, Terraria.Main.player, Terraria.ModLoader.NPCHappiness.RegisterVanillaNpcRelationships(), Terraria.ModLoader.Core.LoaderUtils.ResetStaticMembers(), Terraria.Main.SceneMetrics, Terraria.NPC.ShimmeredTownNPCs, Terraria.Main.ShopHelper, Terraria.Main.slimeRainNPC, Terraria.WorldGen.TownManager, and Terraria.Main.townNPCCanSpawn.
Referenced by Terraria.ModLoader.ModContent.ResizeArrays().