TModLoader: Terraria.ModLoader.NPCLoader.IsModNPC
IsModNPC()
static bool Terraria.ModLoader.NPCLoader.IsModNPC (NPC npc) inline static package
Definition at line 438 of file NPCLoader.cs.
    {
        return npc.type >= NPCID.Count;
    }
References Terraria.ID.NPCID.Count.
Referenced by Terraria.ModLoader.NPCLoader.DrawHealthBar(), Terraria.ModLoader.IO.WorldIO.SaveNPCs(), Terraria.IO.WorldFile.SaveNPCs(), Terraria.ModLoader.NPCLoader.SetBestiary(), and Terraria.ModLoader.NPCLoader.SetDefaults().