TModLoader: UwUPnP.Gateway.RunCommand
RunCommand()
Dictionary< string, string > UwUPnP.Gateway.RunCommand (string action, params(string Key, object Value)[] args) inline private
Definition at line 193 of file Gateway.cs.
    {
        string requestData = GetRequestData(action, args);
        return GetResponse(SendRequest(action, requestData));
    }
References UwUPnP.Gateway.GetRequestData(), UwUPnP.Gateway.GetResponse(), and UwUPnP.Gateway.SendRequest().
Referenced by UwUPnP.Gateway.AddPortMapping(), UwUPnP.Gateway.DeletePortMapping(), UwUPnP.Gateway.GetGenericPortMappingEntry(), and UwUPnP.Gateway.SpecificPortMappingExists().