TModLoader: Terraria.ModLoader.Engine.LoggingHooks.HookWebRequests
HookWebRequests()
static void Terraria.ModLoader.Engine.LoggingHooks.HookWebRequests () inline static private
Attempt to hook the .NET internal methods to log when requests are sent to web addresses. Use the right internal methods to capture redirects.
Definition at line 87 of file LoggingHooks.cs.
    {
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Expected O, but got Unknown
        try
        {
            MethodInfo sendAsyncCoreMethodInfo = typeof(HttpClient).Assembly.GetType("System.Net.Http.HttpConnectionPoolManager")?.GetMethod("SendAsyncCore", BindingFlags.Instance | BindingFlags.Public);
            if (sendAsyncCoreMethodInfo != null)
            {
                httpSendAsyncHook = new Hook((MethodBase)sendAsyncCoreMethodInfo, (Delegate)(hook_SendAsyncCore)delegate(orig_SendAsyncCore orig, object self, HttpRequestMessage request, Uri? proxyUri, bool async, bool doRequestAuth, bool isProxyConnect, CancellationToken cancellationToken)
                {
                    if (IncludeURIInRequestLogging(request.RequestUri))
                    {
                        Logging.tML.Debug((object)$"Web Request: {request.RequestUri}");
                    }
                    return orig(self, request, proxyUri, async, doRequestAuth, isProxyConnect, cancellationToken);
                });
                return;
            }
        }
        catch
        {
        }
        Logging.tML.Warn((object)"HttpWebRequest send/submit method not found");
    }
References Terraria.ModLoader.Engine.LoggingHooks.hook_SendAsyncCore(), Terraria.ModLoader.Engine.LoggingHooks.httpSendAsyncHook, Terraria.ModLoader.Engine.LoggingHooks.IncludeURIInRequestLogging(), Terraria.ModLoader.Engine.LoggingHooks.orig_SendAsyncCore(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.ModLoader.Engine.LoggingHooks.Init().