TModLoader: Terraria.ModLoader.EmoteBubbleLoader.globalEmoteBubbles
globalEmoteBubbles
readonly List<GlobalEmoteBubble> Terraria.ModLoader.EmoteBubbleLoader.globalEmoteBubbles = new List<GlobalEmoteBubble>() static package
Referenced by Terraria.ModLoader.EmoteBubbleLoader.GetFrame(), Terraria.ModLoader.EmoteBubbleLoader.GetFrameInEmoteMenu(), Terraria.ModLoader.EmoteBubbleLoader.OnSpawn(), Terraria.ModLoader.EmoteBubbleLoader.PostDraw(), Terraria.ModLoader.EmoteBubbleLoader.PostDrawInEmoteMenu(), Terraria.ModLoader.EmoteBubbleLoader.PreDraw(), Terraria.ModLoader.EmoteBubbleLoader.PreDrawInEmoteMenu(), Terraria.ModLoader.GlobalEmoteBubble.Register(), Terraria.ModLoader.EmoteBubbleLoader.Unload(), Terraria.ModLoader.EmoteBubbleLoader.UpdateFrame(), and Terraria.ModLoader.EmoteBubbleLoader.UpdateFrameInEmoteMenu().