TModLoader: Terraria.ModLoader.EmoteBubbleLoader.GetEmoteBubble
GetEmoteBubble()
static ModEmoteBubble Terraria.ModLoader.EmoteBubbleLoader.GetEmoteBubble (int type) inline static
Gets the T:Terraria.ModLoader.ModEmoteBubble instance corresponding to the specified ID.
Parameters
type The ID of the emote bubble
Returns
The T:Terraria.ModLoader.ModEmoteBubble instance in the emote bubbles array, null if not found.
    {
        if (type < EmoteID.Count || type >= EmoteBubbleCount)
        {
            return null;
        }
        return emoteBubbles[type - EmoteID.Count];
    }
References Terraria.GameContent.UI.EmoteID.Count, Terraria.ModLoader.EmoteBubbleLoader.EmoteBubbleCount, and Terraria.ModLoader.EmoteBubbleLoader.emoteBubbles.
Referenced by Terraria.GameContent.UI.Elements.EmoteButton.EmoteButton(), Terraria.ModLoader.EmoteBubbleLoader.GetFrameInEmoteMenu(), Terraria.ModLoader.EmoteBubbleLoader.OnSpawn(), Terraria.ModLoader.EmoteBubbleLoader.PostDrawInEmoteMenu(), Terraria.ModLoader.EmoteBubbleLoader.PreDrawInEmoteMenu(), and Terraria.ModLoader.EmoteBubbleLoader.UpdateFrameInEmoteMenu().