TModLoader: Terraria.ModLoader.EmoteBubbleLoader.UpdateFrameInEmoteMenu
UpdateFrameInEmoteMenu()
static bool Terraria.ModLoader.EmoteBubbleLoader.UpdateFrameInEmoteMenu (int emoteType, ref int frameCounter) inline static
    {
        bool result = true;
        foreach (GlobalEmoteBubble globalEmoteBubble in globalEmoteBubbles)
        {
            result &= globalEmoteBubble.UpdateFrameInEmoteMenu(emoteType, ref frameCounter);
        }
        if (!result)
        {
            return false;
        }
        return GetEmoteBubble(emoteType)?.UpdateFrameInEmoteMenu(ref frameCounter) ?? true;
    }
References Terraria.ModLoader.EmoteBubbleLoader.GetEmoteBubble(), Terraria.ModLoader.EmoteBubbleLoader.globalEmoteBubbles, and Terraria.ModLoader.ModEmoteBubble.UpdateFrameInEmoteMenu().
Referenced by Terraria.GameContent.UI.Elements.EmoteButton.UpdateFrame().