TModLoader: Terraria.ModLoader.UI.Interface.ModLoaderMenus
ModLoaderMenus()
static void Terraria.ModLoader.UI.Interface.ModLoaderMenus (Main main, int selectedMenu, string[] buttonNames, float[] buttonScales, int[] buttonVerticalSpacing, ref int offY, ref int spacing, ref int numButtons, ref bool backButtonDown) inline static package
    {
        if (Main.menuMode == 10002)
        {
            if (ModLoader.ShowFirstLaunchWelcomeMessage)
            {
                ModLoader.ShowFirstLaunchWelcomeMessage = false;
                infoMessage.Show(Language.GetTextValue("tModLoader.FirstLaunchWelcomeMessage"), Main.menuMode);
            }
            else if (SteamedWraps.FamilyShared && !ModLoader.WarnedFamilyShare)
            {
                ModLoader.WarnedFamilyShare = true;
                infoMessage.Show(Language.GetTextValue("tModLoader.SteamFamilyShareWarning"), Main.menuMode);
            }
            else if (ModLoader.ShowWhatsNew)
            {
                ModLoader.ShowWhatsNew = false;
                if (File.Exists("RecentGitHubCommits.txt"))
                {
                    bool LastLaunchedShaInRecentGitHubCommits = false;
                    StringBuilder messages = new StringBuilder();
                    foreach (string item2 in File.ReadLines("RecentGitHubCommits.txt"))
                    {
                        string[] parts = item2.Split(' ', 2);
                        if (parts.Length == 2)
{
                            string sha = parts[0];
                            string message2 = parts[1];
                            if (sha != ModLoader.LastLaunchedTModLoaderAlphaSha)
{
                                messages.Append("\n  " + message2);
                            }
                            if (sha == ModLoader.LastLaunchedTModLoaderAlphaSha)
{
                                LastLaunchedShaInRecentGitHubCommits = true;
                                break;
                            }
                        }
                    }
                    if (LastLaunchedShaInRecentGitHubCommits)
                    {
                        infoMessage.Show(Language.GetTextValue("tModLoader.WhatsNewMessage") + messages.ToString(), Main.menuMode, null, Language.GetTextValue("tModLoader.ViewOnGitHub"), delegate
{
                            Utils.OpenToURL("https://github.com/tModLoader/tModLoader/compare/" + ModLoader.LastLaunchedTModLoaderAlphaSha + "...1.4");
                        });
                    }
                }
            }
            else if (ModLoader.PreviewFreezeNotification)
            {
                ModLoader.PreviewFreezeNotification = false;
                ModLoader.LastPreviewFreezeNotificationSeen = BuildInfo.tMLVersion.MajorMinor();
                infoMessage.Show(Language.GetTextValue("tModLoader.WelcomeMessagePreview"), Main.menuMode, null, Language.GetTextValue("tModLoader.ModsMoreInfo"), delegate
                {
                    Utils.OpenToURL("https://github.com/tModLoader/tModLoader/wiki/tModLoader-Release-Cycle#14");
                });
                Main.SaveSettings();
            }
            else if (!ModLoader.DownloadedDependenciesOnStartup)
            {
                ModLoader.DownloadedDependenciesOnStartup = true;
                List<string> missingDeps = ModOrganizer.IdentifyMissingWorkshopDependencies().ToList();
                bool num = missingDeps.Count != 0;
                string message = string.Concat(ModOrganizer.DetectModChangesForInfoMessage(), "\n", string.Concat(missingDeps)).Trim('\n');
                string cancelButton = (num ? Language.GetTextValue("tModLoader.ContinueAnyway") : null);
                string continueButton = (num ? Language.GetTextValue("tModLoader.InstallDependencies") : "");
                Action downloadAction = delegate
                {
                    HashSet<ModDownloadItem> hashSet = new HashSet<ModDownloadItem>();
                    foreach (string current in missingDeps)
                    {
                        if (!WorkshopHelper.TryGetModDownloadItem(current, out var item))
{
                            Logging.tML.Error((object)("Could not find required mod dependency on Workshop: " + current));
                        }
                        else
{
                            hashSet.Add(item);
                        }
                    }
                    UIModBrowser.DownloadMods(hashSet, 10002);
                };
                if (!string.IsNullOrWhiteSpace(message))
                {
                    Logging.tML.Info((object)("Mod Changes since last launch:\n" + message));
                    infoMessage.Show(message, Main.menuMode, null, continueButton, downloadAction, cancelButton);
                }
            }
        }
        if (Main.menuMode == 10000)
        {
            Main.MenuUI.SetState(modsMenu);
            Main.menuMode = 888;
        }
        else if (Main.menuMode == 10001)
        {
            Main.menuMode = 888;
            Main.MenuUI.SetState(modSources);
        }
        else if (Main.menuMode == 10025)
        {
            Main.MenuUI.SetState(createMod);
            Main.menuMode = 888;
        }
        else if (Main.menuMode == 10002)
        {
            Main.menuMode = 888;
            Main.MenuUI.SetState(loadMods);
        }
        else if (Main.menuMode == 10003)
        {
            Main.MenuUI.SetState(buildMod);
            Main.menuMode = 888;
        }
        else if (Main.menuMode == 10005)
        {
            Main.MenuUI.SetState(errorMessage);
            Main.menuMode = 888;
        }
        else if (Main.menuMode == 10006)
        {
            ModLoader.Reload();
        }
        else if (Main.menuMode == 10007)
        {
            Main.MenuUI.SetState(modBrowser);
            Main.menuMode = 888;
        }
        else if (Main.menuMode == 10008)
        {
            Main.MenuUI.SetState(modInfo);
            Main.menuMode = 888;
        }
        else if (Main.menuMode == 10012)
        {
            Main.MenuUI.SetState(updateMessage);
            Main.menuMode = 888;
        }
        else if (Main.menuMode == 10013)
        {
            Main.MenuUI.SetState(infoMessage);
            Main.menuMode = 888;
        }
        else if (Main.menuMode == 10016)
        {
            Main.MenuUI.SetState(modPacksMenu);
            Main.menuMode = 888;
        }
        else if (Main.menuMode == 10019)
        {
            Main.MenuUI.SetState(extractMod);
            Main.menuMode = 888;
        }
        else if (Main.menuMode == 10023)
        {
            Main.MenuUI.SetState(progress);
            Main.menuMode = 888;
        }
        else if (Main.menuMode == 10020)
        {
            Main.MenuUI.SetState(downloadProgress);
            Main.menuMode = 888;
        }
        else if (Main.menuMode == 10017)
        {
            offY = 210;
            spacing = 42;
            numButtons = 10;
            buttonVerticalSpacing[numButtons - 1] = 18;
            for (int i = 0; i < numButtons; i++)
            {
                buttonScales[i] = 0.75f;
            }
            int buttonIndex = 0;
            buttonNames[buttonIndex] = (ModNet.downloadModsFromServers ? Language.GetTextValue("tModLoader.DownloadFromServersYes") : Language.GetTextValue("tModLoader.DownloadFromServersNo"));
            if (selectedMenu == buttonIndex)
            {
                SoundEngine.PlaySound(in SoundID.MenuTick);
                ModNet.downloadModsFromServers = !ModNet.downloadModsFromServers;
            }
            buttonIndex++;
            buttonNames[buttonIndex] = (ModNet.onlyDownloadSignedMods ? Language.GetTextValue("tModLoader.DownloadSignedYes") : Language.GetTextValue("tModLoader.DownloadSignedNo"));
            if (selectedMenu == buttonIndex)
            {
                SoundEngine.PlaySound(in SoundID.MenuTick);
                ModNet.onlyDownloadSignedMods = !ModNet.onlyDownloadSignedMods;
            }
            buttonIndex++;
            buttonNames[buttonIndex] = (ModLoader.autoReloadAndEnableModsLeavingModBrowser ? Language.GetTextValue("tModLoader.AutomaticallyReloadAndEnableModsLeavingModBrowserYes") : Language.GetTextValue("tModLoader.AutomaticallyReloadAndEnableModsLeavingModBrowserNo"));
            if (selectedMenu == buttonIndex)
            {
                SoundEngine.PlaySound(in SoundID.MenuTick);
                ModLoader.autoReloadAndEnableModsLeavingModBrowser = !ModLoader.autoReloadAndEnableModsLeavingModBrowser;
            }
            buttonIndex++;
            buttonNames[buttonIndex] = (ModLoader.autoReloadRequiredModsLeavingModsScreen ? Language.GetTextValue("tModLoader.AutomaticallyReloadRequiredModsLeavingModsScreenYes") : Language.GetTextValue("tModLoader.AutomaticallyReloadRequiredModsLeavingModsScreenNo"));
            if (selectedMenu == buttonIndex)
            {
                SoundEngine.PlaySound(in SoundID.MenuTick);
                ModLoader.autoReloadRequiredModsLeavingModsScreen = !ModLoader.autoReloadRequiredModsLeavingModsScreen;
            }
            buttonIndex++;
            buttonNames[buttonIndex] = Language.GetTextValue("tModLoader.RemoveForcedMinimumZoom" + (ModLoader.removeForcedMinimumZoom ? "Yes" : "No"));
            if (selectedMenu == buttonIndex)
            {
                SoundEngine.PlaySound(in SoundID.MenuTick);
                ModLoader.removeForcedMinimumZoom = !ModLoader.removeForcedMinimumZoom;
            }
            buttonIndex++;
            buttonNames[buttonIndex] = Language.GetTextValue($"tModLoader.AttackSpeedScalingTooltipVisibility{ModLoader.attackSpeedScalingTooltipVisibility}");
            if (selectedMenu == buttonIndex)
            {
                SoundEngine.PlaySound(in SoundID.MenuTick);
                ModLoader.attackSpeedScalingTooltipVisibility = (ModLoader.attackSpeedScalingTooltipVisibility + 1) % 3;
            }
            buttonIndex++;
            buttonNames[buttonIndex] = Language.GetTextValue("tModLoader.ShowMemoryEstimates" + (ModLoader.showMemoryEstimates ? "Yes" : "No"));
            if (selectedMenu == buttonIndex)
            {
                SoundEngine.PlaySound(in SoundID.MenuTick);
                ModLoader.showMemoryEstimates = !ModLoader.showMemoryEstimates;
            }
            buttonIndex++;
            buttonNames[buttonIndex] = Language.GetTextValue("tModLoader.ShowModMenuNotifications" + (ModLoader.notifyNewMainMenuThemes ? "Yes" : "No"));
            if (selectedMenu == buttonIndex)
            {
                SoundEngine.PlaySound(in SoundID.MenuTick);
                ModLoader.notifyNewMainMenuThemes = !ModLoader.notifyNewMainMenuThemes;
            }
            buttonIndex++;
            buttonNames[buttonIndex] = Language.GetTextValue("tModLoader.ShowNewUpdatedModsInfo" + (ModLoader.showNewUpdatedModsInfo ? "Yes" : "No"));
            if (selectedMenu == buttonIndex)
            {
                SoundEngine.PlaySound(in SoundID.MenuTick);
                ModLoader.showNewUpdatedModsInfo = !ModLoader.showNewUpdatedModsInfo;
            }
            buttonIndex++;
            buttonNames[buttonIndex] = Lang.menu[5].Value;
            if ((selectedMenu == buttonIndex) | backButtonDown)
            {
                backButtonDown = false;
                Main.menuMode = 11;
                SoundEngine.PlaySound(11);
            }
        }
        else if (Main.menuMode == 10024)
        {
            Main.MenuUI.SetState(modConfig);
            Main.menuMode = 888;
        }
        else if (Main.menuMode == 10027)
        {
            Main.MenuUI.SetState(modConfigList);
            Main.menuMode = 888;
        }
        else if (Main.menuMode == 10026)
        {
            Environment.Exit(0);
        }
    }
References Terraria.ModLoader.ModLoader.autoReloadAndEnableModsLeavingModBrowser, Terraria.ModLoader.ModLoader.autoReloadRequiredModsLeavingModsScreen, Terraria.ModLoader.UI.Interface.buildMod, Terraria.ModLoader.UI.Interface.createMod, Terraria.ModLoader.Core.ModOrganizer.DetectModChangesForInfoMessage(), Terraria.ModLoader.ModLoader.DownloadedDependenciesOnStartup, Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadMods(), Terraria.ModLoader.ModNet.downloadModsFromServers, Terraria.ModLoader.UI.Interface.downloadProgress, Terraria.ModLoader.Environment, Terraria.ModLoader.UI.Interface.errorMessage, Terraria.ModLoader.UI.Interface.extractMod, Terraria.Social.Steam.SteamedWraps.FamilyShared, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.Core.ModOrganizer.IdentifyMissingWorkshopDependencies(), Terraria.ModLoader.UI.Interface.infoMessage, Terraria.ModLoader.ModLoader.LastLaunchedTModLoaderAlphaSha, Terraria.ModLoader.UI.Interface.loadMods, Terraria.Lang.menu, Terraria.Main.menuMode, Terraria.ID.SoundID.MenuTick, Terraria.Main.MenuUI, Terraria.ModLoader.UI.Interface.modBrowser, Terraria.ModLoader.UI.Interface.modConfig, Terraria.ModLoader.UI.Interface.modConfigList, Terraria.ModLoader.UI.Interface.modInfo, Terraria.ModLoader.UI.Interface.modPacksMenu, Terraria.ModLoader.UI.Interface.modsMenu, Terraria.ModLoader.UI.Interface.modSources, Terraria.ModLoader.ModLoader.notifyNewMainMenuThemes, Terraria.ModLoader.ModNet.onlyDownloadSignedMods, Terraria.Audio.SoundEngine.PlaySound(), Terraria.ModLoader.ModLoader.PreviewFreezeNotification, Terraria.ModLoader.UI.Interface.progress, Terraria.ModLoader.ModLoader.Reload(), Terraria.ModLoader.ModLoader.removeForcedMinimumZoom, Terraria.Main.SaveSettings(), Terraria.ModLoader.UI.UIInfoMessage.Show(), Terraria.ModLoader.ModLoader.ShowFirstLaunchWelcomeMessage, Terraria.ModLoader.ModLoader.showMemoryEstimates, Terraria.ModLoader.ModLoader.showNewUpdatedModsInfo, Terraria.ModLoader.ModLoader.ShowWhatsNew, Terraria.ModLoader.Logging.tML, Terraria.ModLoader.BuildInfo.tMLVersion, Terraria.Social.Steam.WorkshopHelper.TryGetModDownloadItem(), Terraria.ModLoader.UI.Interface.updateMessage, Terraria.Localization.LocalizedText.Value, and Terraria.ModLoader.ModLoader.WarnedFamilyShare.
Referenced by Terraria.Main.DrawMenu().