TModLoader: Terraria.ModLoader.UI.Interface.modConfig
modConfig
UIModConfig Terraria.ModLoader.UI.Interface.modConfig = new UIModConfig() static package
Definition at line 83 of file Interface.cs.
Referenced by Terraria.ModLoader.Config.UI.DictionaryElement.AddItem(), Terraria.Main.CanPauseGame(), Terraria.ModLoader.Config.UI.EnumElement.DefaultSetValue(), Terraria.ModLoader.Config.UI.StringOptionElement.DefaultSetValue(), Terraria.ModLoader.Config.UI.UIModConfig.DoMenuModeState(), Terraria.ModLoader.Config.ConfigManager.HandleInGameChangeConfigPacket(), Terraria.ModLoader.Config.UI.UIModConfig.MakeSeparateListPanel(), Terraria.ModLoader.UI.Interface.ModLoaderMenus(), Terraria.ModLoader.Config.UI.CollectionElement.OnBind(), Terraria.ModLoader.Config.UI.ObjectElement.OnBind(), Terraria.ModLoader.Config.UI.StringOptionElement.OnBind(), Terraria.ModLoader.Config.UI.UIModConfigList.PopulateConfigs(), Terraria.ModLoader.Config.UI.ConfigElement< T >.SetObject(), Terraria.ModLoader.Config.ConfigManager.SetPendingChanges(), Terraria.ModLoader.Config.UI.DictionaryElement.SetupList(), Terraria.ModLoader.Config.UI.ListElement.SetupList(), Terraria.ModLoader.Config.UI.SetElement.SetupList(), Terraria.ModLoader.Config.UI.UIModConfig.SwitchToSubConfig(), Terraria.ModLoader.Config.ConfigManager.Unload(), Terraria.ModLoader.Config.UI.Vector2Element.Vector2Object.Update(), and Terraria.ModLoader.Config.UI.UIModConfig.WrapIt().