TModLoader: Terraria.ModLoader.UI.Interface.modBrowser
modBrowser
UIModBrowser Terraria.ModLoader.UI.Interface.modBrowser = new UIModBrowser(WorkshopBrowserModule.Instance) static package
Definition at line 69 of file Interface.cs.
Referenced by Terraria.GameContent.UI.States.UIWorkshopHub.Click_OpenModBrowserMenu(), Terraria.ModLoader.UI.UIModPackItem.DownloadMissingMods(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadMods(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.DownloadWithDeps(), Terraria.ModLoader.UI.Interface.ModLoaderMenus(), Terraria.ModLoader.UI.Interface.ResetData(), Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.UpdateInstallState(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ViewModInfo(), and Terraria.ModLoader.UI.UIModInfo.VisitModHostPageInner().