TModLoader: Terraria.ModLoader.UI.Interface.EnableDepsRecursive
EnableDepsRecursive()
static void Terraria.ModLoader.UI.Interface.EnableDepsRecursive (LocalMod mod, LocalMod[] mods, List< string > missingRefs) inline static private
Definition at line 442 of file Interface.cs.
    {
        string[] array = mod.properties.modReferences.Select((BuildProperties.ModReference x) => x.mod).ToArray();
        foreach (string name in array)
        {
            LocalMod dep = mods.FirstOrDefault((LocalMod x) => x.Name == name);
            if (dep == null)
            {
                missingRefs.Add(name);
                continue;
            }
            EnableDepsRecursive(dep, mods, missingRefs);
            if (!dep.Enabled)
            {
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("Automatically enabling " + dep.DisplayName + " required by " + mod.DisplayName);
                Console.ResetColor();
            }
            dep.Enabled = !dep.Enabled;
        }
    }
References Terraria.ModLoader.Console, Terraria.ModLoader.UI.Interface.EnableDepsRecursive(), Terraria.ModLoader.Core.LocalMod.Name, and Terraria.ModLoader.Core.LocalMod.properties.
Referenced by Terraria.ModLoader.UI.Interface.EnableDepsRecursive(), and Terraria.ModLoader.UI.Interface.ServerModMenu().