TModLoader: Terraria.Audio.SoundEngine.GetActiveSound
GetActiveSound()
static ? ActiveSound Terraria.Audio.SoundEngine.GetActiveSound (SlotId slotId) inline static package
Definition at line 237 of file SoundEngine.cs.
    {
        if (!TryGetActiveSound(slotId, out ActiveSound result))
        {
            return null;
        }
        return result;
    }
References Terraria.Audio.SoundEngine.TryGetActiveSound().
Referenced by Terraria.Projectile.AI_001(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_110_Betsy(), Terraria.Projectile.AI_143_MonkStaffT2Ghast(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_187_ShadowHand(), Terraria.Projectile.AI_195_JimsDrone(), Terraria.Projectile.Kill(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.UpdateBiomes(), Terraria.NPC.VanillaAI_Inner(), and Terraria.NPC.VanillaHitEffect().