TModLoader: Terraria.Audio.SoundEngine.PlaySound
PlaySound() [3/6]
static ? SoundEffectInstance Terraria.Audio.SoundEngine.PlaySound (int type, int x = -1, int y = -1, int Style = 1, float volumeScale = 1f, float pitchOffset = 0f) inline static package
Definition at line 205 of file SoundEngine.cs.
    {
        if (!SoundID.TryGetLegacyStyle(type, Style, out var soundStyle))
        {
            Logging.tML.Warn((object)$"Failed to get legacy sound style for ({type}, {Style}) input.");
            return null;
        }
        soundStyle = soundStyle with
        {
            Volume = soundStyle.Volume * volumeScale,
            Pitch = soundStyle.Pitch + pitchOffset
        };
        SlotId slotId = PlaySound(in soundStyle, XYToOptionalPosition(x, y));
        if (!slotId.IsValid)
        {
            return null;
        }
        return GetActiveSound(slotId)?.Sound;
    }
References Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Audio.ActiveSound.Sound, Terraria.ModLoader.Logging.tML, Terraria.ID.SoundID.TryGetLegacyStyle(), and Terraria.Audio.SoundEngine.XYToOptionalPosition().