TModLoader: Terraria.Audio.SoundEngine.PlayTrackedSound
PlayTrackedSound()
static SlotId Terraria.Audio.SoundEngine.PlayTrackedSound (in SoundStyle style, Vector2? position = null) inline static package
Definition at line 225 of file SoundEngine.cs.
    {
        return PlaySound(in style, position);
    }
References Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.Projectile.AI_001(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.Projectile.AI_131_FlameBurstShot(), Terraria.Projectile.AI_134_Ballista(), Terraria.Projectile.AI_137_LightningAura(), Terraria.Projectile.AI_138_ExplosiveTrap(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.AI_143_MonkStaffT2Ghast(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_187_ShadowHand(), Terraria.Projectile.Kill(), Terraria.Initializers.AchievementInitializer.OnAchievementCompleted(), Terraria.Player.UpdateBiomes(), and Terraria.NPC.VanillaAI_Inner().