TModLoader: Terraria.GameContent.UI.CustomCurrencySingleCoin.DrawSavingsMoney
DrawSavingsMoney()
override void Terraria.GameContent.UI.CustomCurrencySingleCoin.DrawSavingsMoney (SpriteBatch sb, string text, float shopx, float shopy, long totalCoins, bool horizontal = false) inline virtual
Reimplemented from Terraria.GameContent.UI.CustomCurrencySystem.
    {
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_0158: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        int num = _valuePerUnit.Keys.ElementAt(0);
        Main.instance.LoadItem(num);
        Texture2D value = TextureAssets.Item[num].Value;
        if (horizontal)
        {
            Vector2 position = default(Vector2);
            ((Vector2)(ref position))._002Ector(shopx + ChatManager.GetStringSize(FontAssets.MouseText.Value, text, Vector2.One).X + 45f, shopy + 50f);
            sb.Draw(value, position, (Rectangle?)null, Color.White, 0f, value.Size() / 2f, CurrencyDrawScale, (SpriteEffects)0, 0f);
            Utils.DrawBorderStringFourWay(sb, FontAssets.ItemStack.Value, totalCoins.ToString(), position.X - 11f, position.Y, Color.White, Color.Black, new Vector2(0.3f), 0.75f);
        }
        else
        {
            int num2 = ((totalCoins > 99) ? (-6) : 0);
            sb.Draw(value, new Vector2(shopx + 11f, shopy + 75f), (Rectangle?)null, Color.White, 0f, value.Size() / 2f, CurrencyDrawScale, (SpriteEffects)0, 0f);
            Utils.DrawBorderStringFourWay(sb, FontAssets.ItemStack.Value, totalCoins.ToString(), shopx + (float)num2, shopy + 75f, Color.White, Color.Black, new Vector2(0.3f), 0.75f);
        }
    }
References Terraria.GameContent.UI.CustomCurrencySystem._valuePerUnit, Terraria.GameContent.UI.CustomCurrencySingleCoin.CurrencyDrawScale, Terraria.Utils.DrawBorderStringFourWay(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Main.instance, Terraria.GameContent.TextureAssets.Item, Terraria.GameContent.FontAssets.ItemStack, Terraria.Main.LoadItem(), and Terraria.GameContent.FontAssets.MouseText.