TModLoader: Terraria.UI.UserInterface.Update_Inner
Update_Inner()
void Terraria.UI.UserInterface.Update_Inner (GameTime time, UIElement uIElement, ref bool num) inline private
Definition at line 267 of file UserInterface.cs.
    {
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        if (uIElement != _lastElementHover)
        {
            if (_lastElementHover != null)
            {
                _lastElementHover.MouseOut(new UIMouseEvent(_lastElementHover, MousePosition));
            }
            uIElement?.MouseOver(new UIMouseEvent(uIElement, MousePosition));
            _lastElementHover = uIElement;
        }
        if (!num)
        {
            HandleClick(LeftMouse, time, Main.mouseLeft && Main.hasFocus, uIElement);
            HandleClick(RightMouse, time, Main.mouseRight && Main.hasFocus, uIElement);
            HandleClick(MiddleMouse, time, Main.mouseMiddle && Main.hasFocus, uIElement);
            HandleClick(XButton1Mouse, time, Main.mouseXButton1 && Main.hasFocus, uIElement);
            HandleClick(XButton2Mouse, time, Main.mouseXButton2 && Main.hasFocus, uIElement);
        }
        if (PlayerInput.ScrollWheelDeltaForUI != 0)
        {
            uIElement?.ScrollWheel(new UIScrollWheelEvent(uIElement, MousePosition, PlayerInput.ScrollWheelDeltaForUI));
        }
    }
References Terraria.UI.UserInterface._lastElementHover, Terraria.UI.UserInterface.HandleClick(), Terraria.Main.hasFocus, Terraria.UI.UserInterface.LeftMouse, Terraria.UI.UserInterface.MiddleMouse, Terraria.Main.mouseLeft, Terraria.Main.mouseMiddle, Terraria.UI.UIElement.MouseOut(), Terraria.UI.UIElement.MouseOver(), Terraria.UI.UserInterface.MousePosition, Terraria.Main.mouseRight, Terraria.Main.mouseXButton1, Terraria.Main.mouseXButton2, Terraria.UI.UserInterface.RightMouse, Terraria.UI.UIElement.ScrollWheel(), Terraria.GameInput.PlayerInput.ScrollWheelDeltaForUI, Terraria.UI.UserInterface.XButton1Mouse, and Terraria.UI.UserInterface.XButton2Mouse.
Referenced by Terraria.UI.UserInterface.Update().