TModLoader: Terraria.GameContent.UI.Elements.UICharacter.DrawPets
DrawPets()
void Terraria.GameContent.UI.Elements.UICharacter.DrawPets (SpriteBatch spriteBatch) inline
Definition at line 144 of file UICharacter.cs.
    {
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        CalculatedStyle dimensions = GetDimensions();
        Vector2 playerPosition = GetPlayerPosition(ref dimensions);
        for (int i = 0; i < _petProjectiles.Length; i++)
        {
            Projectile projectile = _petProjectiles[i];
            Vector2 vector = playerPosition + new Vector2(0f, (float)_player.height) + new Vector2(20f, 0f) + new Vector2(0f, (float)(-projectile.height));
            projectile.position = vector + Main.screenPosition;
            projectile.velocity = new Vector2(0.1f, 0f);
            projectile.direction = 1;
            projectile.owner = Main.myPlayer;
            ProjectileID.Sets.CharacterPreviewAnimations[projectile.type].ApplyTo(projectile, _animated);
            Player player = Main.player[Main.myPlayer];
            Main.player[Main.myPlayer] = _player;
            Main.instance.DrawProjDirect(projectile);
            Main.player[Main.myPlayer] = player;
        }
        spriteBatch.End();
        spriteBatch.Begin((SpriteSortMode)1, ((GraphicsResource)spriteBatch).GraphicsDevice.BlendState, ((GraphicsResource)spriteBatch).GraphicsDevice.SamplerStates[0], ((GraphicsResource)spriteBatch).GraphicsDevice.DepthStencilState, ((GraphicsResource)spriteBatch).GraphicsDevice.RasterizerState, (Effect)null, Main.UIScaleMatrix);
    }
References Terraria.GameContent.UI.Elements.UICharacter._animated, Terraria.GameContent.UI.Elements.UICharacter._petProjectiles, Terraria.GameContent.UI.Elements.UICharacter._player, Terraria.ID.ProjectileID.Sets.CharacterPreviewAnimations, Terraria.UI.UIElement.GetDimensions(), Terraria.GameContent.UI.Elements.UICharacter.GetPlayerPosition(), Terraria.Entity.height, Terraria.Main.instance, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.screenPosition, Terraria.Projectile.type, and Terraria.Main.UIScaleMatrix.
Referenced by Terraria.GameContent.UI.Elements.UICharacter.DrawSelf().