TModLoader: Terraria.DelegateMethods.SpreadDirt
SpreadDirt()
static bool Terraria.DelegateMethods.SpreadDirt (int x, int y) inline static
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        if (Vector2.Distance(v2_1, new Vector2((float)x, (float)y)) > f_1)
        {
            return false;
        }
        WorldGen.TryKillingReplaceableTile(x, y, 0);
        if (WorldGen.PlaceTile(x, y, 0))
        {
            if (Main.netMode != 0)
            {
                NetMessage.SendData(17, -1, -1, null, 1, x, y);
            }
            Vector2 position = default(Vector2);
            ((Vector2)(ref position))._002Ector((float)(x * 16), (float)(y * 16));
            int num = 0;
            for (int i = 0; i < 3; i++)
            {
                Dust dust = Dust.NewDustDirect(position, 16, 16, num, 0f, 0f, 100, Color.Transparent, 2.2f);
                dust.noGravity = true;
                dust.velocity.Y -= 1.2f;
                dust.velocity *= 4f;
                Dust dust2 = Dust.NewDustDirect(position, 16, 16, num, 0f, 0f, 100, Color.Transparent, 1.3f);
                dust2.velocity.Y -= 1.2f;
                dust2.velocity *= 2f;
            }
            int num2 = y + 1;
            if (Main.tile[x, num2] != null && !TileID.Sets.Platforms[Main.tile[x, num2].type] && (Main.tile[x, num2].topSlope() || Main.tile[x, num2].halfBrick()))
            {
                WorldGen.SlopeTile(x, num2);
                if (Main.netMode != 0)
                {
                    NetMessage.SendData(17, -1, -1, null, 14, x, num2);
                }
            }
            num2 = y - 1;
            if (Main.tile[x, num2] != null && !TileID.Sets.Platforms[Main.tile[x, num2].type] && Main.tile[x, num2].bottomSlope())
            {
                WorldGen.SlopeTile(x, num2);
                if (Main.netMode != 0)
                {
                    NetMessage.SendData(17, -1, -1, null, 14, x, num2);
                }
            }
            for (int j = x - 1; j <= x + 1; j++)
            {
                for (int k = y - 1; k <= y + 1; k++)
                {
                    Tile tile = Main.tile[j, k];
                    if (!tile.active() || num == tile.type || (tile.type != 2 && tile.type != 23 && tile.type != 60 && tile.type != 70 && tile.type != 109 && tile.type != 199 && tile.type != 477 && tile.type != 492))
                    {
                        continue;
                    }
                    bool flag = true;
                    for (int l = j - 1; l <= j + 1; l++)
                    {
                        for (int m = k - 1; m <= k + 1; m++)
{
                            if (!WorldGen.SolidTile(l, m))
{
                                flag = false;
                            }
                        }
                    }
                    if (flag)
                    {
                        WorldGen.KillTile(j, k, fail: true);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, j, k, 1f);
                        }
                    }
                }
            }
            return true;
        }
        Tile tile2 = Main.tile[x, y];
        if (tile2 == null)
        {
            return false;
        }
        if (tile2.type < 0)
        {
            return false;
        }
        if (Main.tileSolid[tile2.type] && !TileID.Sets.Platforms[tile2.type])
        {
            return tile2.type == 380;
        }
        return true;
    }
References Terraria.Tile.active(), Terraria.DelegateMethods.f_1, Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.Dust.NewDustDirect(), Terraria.WorldGen.PlaceTile(), Terraria.ID.TileID.Sets.Platforms, Terraria.NetMessage.SendData(), Terraria.WorldGen.SlopeTile(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.WorldGen.TryKillingReplaceableTile(), and Terraria.DelegateMethods.v2_1.
Referenced by Terraria.Projectile.Kill().