TModLoader: Terraria.DelegateMethods.SpreadWater
SpreadWater()
static bool Terraria.DelegateMethods.SpreadWater (int x, int y) inline static
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        if (Vector2.Distance(v2_1, new Vector2((float)x, (float)y)) > f_1)
        {
            return false;
        }
        if (WorldGen.PlaceLiquid(x, y, 0, byte.MaxValue))
        {
            Vector2 position = default(Vector2);
            ((Vector2)(ref position))._002Ector((float)(x * 16), (float)(y * 16));
            int type = Dust.dustWater();
            for (int i = 0; i < 3; i++)
            {
                Dust dust = Dust.NewDustDirect(position, 16, 16, type, 0f, 0f, 100, Color.Transparent, 2.2f);
                dust.noGravity = true;
                dust.velocity.Y -= 1.2f;
                dust.velocity *= 7f;
                Dust dust2 = Dust.NewDustDirect(position, 16, 16, type, 0f, 0f, 100, Color.Transparent, 1.3f);
                dust2.velocity.Y -= 1.2f;
                dust2.velocity *= 4f;
            }
            return true;
        }
        return false;
    }
References Terraria.Dust.dustWater(), Terraria.DelegateMethods.f_1, Terraria.Dust.NewDustDirect(), Terraria.WorldGen.PlaceLiquid(), and Terraria.DelegateMethods.v2_1.
Referenced by Terraria.Projectile.Kill().