TModLoader: Terraria.Graphics.Capture.CaptureBiome.GetBiomeByWater
GetBiomeByWater()
static CaptureBiome Terraria.Graphics.Capture.CaptureBiome.GetBiomeByWater () inline static private
    {
        int num = Main.CalculateWaterStyle(ignoreFountains: true);
        for (int i = 0; i < BiomesByWaterStyle.Length; i++)
        {
            CaptureBiome captureBiome = BiomesByWaterStyle[i];
            if (captureBiome != null && captureBiome.WaterStyle == num)
            {
                return captureBiome;
            }
        }
        SceneEffectLoader.SceneEffectInstance sceneEffect = Main.LocalPlayer.CurrentSceneEffect;
        if (sceneEffect.waterStyle.value >= 15)
        {
            return new CaptureBiome(sceneEffect.surfaceBackground.value, sceneEffect.waterStyle.value, sceneEffect.tileColorStyle);
        }
        return null;
    }
References Terraria.Graphics.Capture.CaptureBiome.CaptureBiome(), Terraria.Graphics.Capture.CaptureBiome.BiomesByWaterStyle, Terraria.Main.CalculateWaterStyle(), and Terraria.Main.LocalPlayer.
Referenced by Terraria.Graphics.Capture.CaptureBiome.GetCaptureBiome().