TModLoader: Terraria.DelegateMethods.SpreadDry
SpreadDry()
static bool Terraria.DelegateMethods.SpreadDry (int x, int y) inline static
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        if (Vector2.Distance(v2_1, new Vector2((float)x, (float)y)) > f_1)
        {
            return false;
        }
        if (WorldGen.EmptyLiquid(x, y))
        {
            Vector2 position = default(Vector2);
            ((Vector2)(ref position))._002Ector((float)(x * 16), (float)(y * 16));
            int type = 31;
            for (int i = 0; i < 3; i++)
            {
                Dust dust = Dust.NewDustDirect(position, 16, 16, type, 0f, 0f, 100, Color.Transparent, 1.2f);
                dust.noGravity = true;
                dust.velocity *= 7f;
                Dust dust2 = Dust.NewDustDirect(position, 16, 16, type, 0f, 0f, 100, Color.Transparent, 0.8f);
                dust2.velocity *= 4f;
            }
            return true;
        }
        return false;
    }
References Terraria.WorldGen.EmptyLiquid(), Terraria.DelegateMethods.f_1, Terraria.Dust.NewDustDirect(), and Terraria.DelegateMethods.v2_1.
Referenced by Terraria.Projectile.Kill().