TModLoader: Terraria.DelegateMethods.SpreadLava
SpreadLava()
static bool Terraria.DelegateMethods.SpreadLava (int x, int y) inline static
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        if (Vector2.Distance(v2_1, new Vector2((float)x, (float)y)) > f_1)
        {
            return false;
        }
        if (WorldGen.PlaceLiquid(x, y, 1, byte.MaxValue))
        {
            Vector2 position = default(Vector2);
            ((Vector2)(ref position))._002Ector((float)(x * 16), (float)(y * 16));
            int type = 35;
            for (int i = 0; i < 3; i++)
            {
                Dust dust = Dust.NewDustDirect(position, 16, 16, type, 0f, 0f, 100, Color.Transparent, 1.2f);
                dust.velocity *= 7f;
                Dust dust2 = Dust.NewDustDirect(position, 16, 16, type, 0f, 0f, 100, Color.Transparent, 0.8f);
                dust2.velocity *= 4f;
            }
            return true;
        }
        return false;
    }
References Terraria.DelegateMethods.f_1, Terraria.Dust.NewDustDirect(), Terraria.WorldGen.PlaceLiquid(), and Terraria.DelegateMethods.v2_1.
Referenced by Terraria.Projectile.Kill().