TModLoader: Terraria.GameContent.UI.Elements.UIColoredSlider.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIColoredSlider.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
    {
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        UISliderBase.CurrentAimedSlider = null;
        if (!Main.mouseLeft)
        {
            UISliderBase.CurrentLockedSlider = null;
        }
        int usageLevel = GetUsageLevel();
        float num = 8f;
        base.DrawSelf(spriteBatch);
        CalculatedStyle dimensions = GetDimensions();
        Vector2 val = new Vector2(dimensions.X, dimensions.Y);
        bool flag = false;
        bool flag2 = base.IsMouseHovering;
        if (usageLevel == 2)
        {
            flag2 = false;
        }
        if (usageLevel == 1)
        {
            flag2 = true;
        }
        Vector2 vector2 = val + new Vector2(0f, 2f);
        Color.Lerp(flag ? Color.Gold : (flag2 ? Color.White : Color.Silver), Color.White, flag2 ? 0.5f : 0f);
        new Vector2(0.8f);
        vector2.X += 8f;
        vector2.Y += num;
        vector2.X -= 17f;
        TextureAssets.ColorBar.Frame();
        ((Vector2)(ref vector2))._002Ector(dimensions.X + dimensions.Width - 10f, dimensions.Y + 10f + num);
        bool wasInBar;
        float obj = DrawValueBar(spriteBatch, vector2, 1f, _getStatusTextAct(), usageLevel, out wasInBar, _blipFunc);
        if (UISliderBase.CurrentLockedSlider == this || wasInBar)
        {
            UISliderBase.CurrentAimedSlider = this;
            if (PlayerInput.Triggers.Current.MouseLeft && !PlayerInput.UsingGamepad && UISliderBase.CurrentLockedSlider == this)
            {
                _slideKeyboardAction(obj);
                if (!_soundedUsage)
                {
                    SoundEngine.PlaySound(12);
                }
                _soundedUsage = true;
            }
            else
            {
                _soundedUsage = false;
            }
        }
        if (UISliderBase.CurrentAimedSlider != null && UISliderBase.CurrentLockedSlider == null)
        {
            UISliderBase.CurrentLockedSlider = UISliderBase.CurrentAimedSlider;
        }
        if (_isReallyMouseOvered)
        {
            _slideGamepadAction();
        }
    }
References Terraria.GameContent.UI.Elements.UIColoredSlider._blipFunc, Terraria.GameContent.UI.Elements.UIColoredSlider._getStatusTextAct, Terraria.GameContent.UI.Elements.UIColoredSlider._isReallyMouseOvered, Terraria.GameContent.UI.Elements.UIColoredSlider._slideGamepadAction, Terraria.GameContent.UI.Elements.UIColoredSlider._slideKeyboardAction, Terraria.GameContent.UI.Elements.UIColoredSlider._soundedUsage, Terraria.GameContent.TextureAssets.ColorBar, Terraria.GameContent.UI.Elements.UISliderBase.CurrentAimedSlider, Terraria.GameContent.UI.Elements.UISliderBase.CurrentLockedSlider, Terraria.GameContent.UI.Elements.UIColoredSlider.DrawValueBar(), Terraria.UI.UIElement.GetDimensions(), Terraria.GameContent.UI.Elements.UISliderBase.GetUsageLevel(), Terraria.Main.mouseLeft, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameInput.PlayerInput.Triggers, and Terraria.GameInput.PlayerInput.UsingGamepad.