TModLoader: Terraria.GameContent.UI.States.UIManageControls.CreateElementGroup
CreateElementGroup()
void Terraria.GameContent.UI.States.UIManageControls.CreateElementGroup (UIList parent, List< string > bindings, InputMode currentInputMode, Color color) inline private
Definition at line 403 of file UIManageControls.cs.
    {
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        for (int i = 0; i < bindings.Count; i++)
        {
            _ = bindings[i];
            UISortableElement uISortableElement = new UISortableElement(i);
            uISortableElement.Width.Set(0f, 1f);
            uISortableElement.Height.Set(30f, 0f);
            uISortableElement.HAlign = 0.5f;
            parent.Add(uISortableElement);
            if (_BindingsHalfSingleLine.Contains(bindings[i]))
            {
                UIElement uIElement = CreatePanel(bindings[i], currentInputMode, color);
                uIElement.Width.Set(0f, 0.5f);
                uIElement.HAlign = 0.5f;
                uIElement.Height.Set(0f, 1f);
                uIElement.SetSnapPoint("Wide", SnapPointIndex++);
                uISortableElement.Append(uIElement);
                continue;
            }
            if (_BindingsFullLine.Contains(bindings[i]))
            {
                UIElement uIElement2 = CreatePanel(bindings[i], currentInputMode, color);
                uIElement2.Width.Set(0f, 1f);
                uIElement2.Height.Set(0f, 1f);
                uIElement2.SetSnapPoint("Wide", SnapPointIndex++);
                uISortableElement.Append(uIElement2);
                continue;
            }
            if (_ModNames.Contains(bindings[i]))
            {
                UIElement header = new HeaderElement(bindings[i]);
                header.Width.Set(0f, 1f);
                header.Height.Set(0f, 1f);
                header.SetSnapPoint("Wide", SnapPointIndex++);
                uISortableElement.Append(header);
                continue;
            }
            UIElement uIElement3 = CreatePanel(bindings[i], currentInputMode, color);
            uIElement3.Width.Set(-5f, 0.5f);
            uIElement3.Height.Set(0f, 1f);
            uIElement3.SetSnapPoint("Thin", SnapPointIndex++);
            uISortableElement.Append(uIElement3);
            i++;
            if (i < bindings.Count)
            {
                uIElement3 = CreatePanel(bindings[i], currentInputMode, color);
                uIElement3.Width.Set(-5f, 0.5f);
                uIElement3.Height.Set(0f, 1f);
                uIElement3.HAlign = 1f;
                uIElement3.SetSnapPoint("Thin", SnapPointIndex++);
                uISortableElement.Append(uIElement3);
            }
        }
    }
References Terraria.GameContent.UI.States.UIManageControls._BindingsFullLine, Terraria.GameContent.UI.States.UIManageControls._BindingsHalfSingleLine, Terraria.GameContent.UI.States.UIManageControls._ModNames, Terraria.GameContent.UI.States.UIManageControls.CreatePanel(), Terraria.UI.UIElement.Height, Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.States.UIManageControls.SnapPointIndex, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIManageControls.CreateBindingGroup().