TModLoader: Terraria.GameContent.UI.States.UIManageControls.CreateBindingGroup
CreateBindingGroup()
UISortableElement Terraria.GameContent.UI.States.UIManageControls.CreateBindingGroup (int elementIndex, List< string > bindings, InputMode currentInputMode) inline private
Definition at line 292 of file UIManageControls.cs.
    {
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        //IL_019f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        UISortableElement uISortableElement = new UISortableElement(elementIndex);
        uISortableElement.HAlign = 0.5f;
        uISortableElement.Width.Set(0f, 1f);
        uISortableElement.Height.Set(2000f, 0f);
        UIPanel uIPanel = new UIPanel();
        uIPanel.Width.Set(0f, 1f);
        uIPanel.Height.Set(-16f, 1f);
        uIPanel.VAlign = 1f;
        uIPanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
        uISortableElement.Append(uIPanel);
        UIList uIList = new UIList();
        uIList.OverflowHidden = false;
        uIList.Width.Set(0f, 1f);
        uIList.Height.Set(-8f, 1f);
        uIList.VAlign = 1f;
        uIList.ListPadding = 5f;
        uIPanel.Append(uIList);
        _ = uIPanel.BackgroundColor;
        switch (elementIndex)
        {
        case 0:
            uIPanel.BackgroundColor = Color.Lerp(uIPanel.BackgroundColor, Color.Green, 0.18f);
            break;
        case 1:
            uIPanel.BackgroundColor = Color.Lerp(uIPanel.BackgroundColor, Color.Goldenrod, 0.18f);
            break;
        case 2:
            uIPanel.BackgroundColor = Color.Lerp(uIPanel.BackgroundColor, Color.HotPink, 0.18f);
            break;
        case 3:
            uIPanel.BackgroundColor = Color.Lerp(uIPanel.BackgroundColor, Color.Indigo, 0.18f);
            break;
        case 4:
            uIPanel.BackgroundColor = Color.Lerp(uIPanel.BackgroundColor, Color.Turquoise, 0.18f);
            break;
        case 5:
            uIPanel.BackgroundColor = Color.Lerp(uIPanel.BackgroundColor, Color.Yellow, 0.18f);
            break;
        }
        CreateElementGroup(uIList, bindings, currentInputMode, uIPanel.BackgroundColor);
        uIPanel.BackgroundColor = uIPanel.BackgroundColor.MultiplyRGBA(new Color(111, 111, 111));
        LocalizedText text = LocalizedText.Empty;
        switch (elementIndex)
        {
        case 0:
            text = ((currentInputMode == InputMode.Keyboard || currentInputMode == InputMode.XBoxGamepad) ? Lang.menu[164] : Lang.menu[243]);
            break;
        case 1:
            text = Lang.menu[165];
            break;
        case 2:
            text = Lang.menu[166];
            break;
        case 3:
            text = Lang.menu[167];
            break;
        case 4:
            text = Lang.menu[198];
            break;
        case 5:
            text = Language.GetText("tModLoader.ModControls");
            break;
        }
        UITextPanel<LocalizedText> element = new UITextPanel<LocalizedText>(text, 0.7f)
        {
            VAlign = 0f,
            HAlign = 0.5f
        };
        uISortableElement.Append(element);
        uISortableElement.Recalculate();
        float totalHeight = uIList.GetTotalHeight();
        uISortableElement.Width.Set(0f, 1f);
        uISortableElement.Height.Set(totalHeight + 30f + 16f, 0f);
        return uISortableElement;
    }
References Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIPanel.BackgroundColor, Terraria.GameContent.UI.States.UIManageControls.CreateElementGroup(), Terraria.Localization.LocalizedText.Empty, Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.Lang.menu, Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIManageControls.AssembleBindPanels().