TModLoader: Terraria.GameContent.UI.States.UIManageControls.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIManageControls.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 1263 of file UIManageControls.cs.
    {
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_020d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0212: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_021e: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0225: Unknown result type (might be due to invalid IL or missing references)
        //IL_022a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_025f: Unknown result type (might be due to invalid IL or missing references)
        //IL_042b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        UILinkPointNavigator.Shortcuts.BackButtonCommand = 4;
        int num = 3000;
        Rectangle val = _buttonBack.GetInnerDimensions().ToRectangle();
        UILinkPointNavigator.SetPosition(num, ((Rectangle)(ref val)).Center.ToVector2());
        int iD = num + 1;
        val = _buttonKeyboard.GetInnerDimensions().ToRectangle();
        UILinkPointNavigator.SetPosition(iD, ((Rectangle)(ref val)).Center.ToVector2());
        int iD2 = num + 2;
        val = _buttonGamepad.GetInnerDimensions().ToRectangle();
        UILinkPointNavigator.SetPosition(iD2, ((Rectangle)(ref val)).Center.ToVector2());
        int iD3 = num + 3;
        val = _buttonProfile.GetInnerDimensions().ToRectangle();
        UILinkPointNavigator.SetPosition(iD3, ((Rectangle)(ref val)).Center.ToVector2());
        int iD4 = num + 4;
        val = _buttonVs1.GetInnerDimensions().ToRectangle();
        UILinkPointNavigator.SetPosition(iD4, ((Rectangle)(ref val)).Center.ToVector2());
        int iD5 = num + 5;
        val = _buttonVs2.GetInnerDimensions().ToRectangle();
        UILinkPointNavigator.SetPosition(iD5, ((Rectangle)(ref val)).Center.ToVector2());
        int key = num;
        UILinkPoint uILinkPoint = UILinkPointNavigator.Points[key];
        uILinkPoint.Unlink();
        uILinkPoint.Up = num + 6;
        key = num + 1;
        UILinkPoint uILinkPoint2 = UILinkPointNavigator.Points[key];
        uILinkPoint2.Unlink();
        uILinkPoint2.Right = num + 2;
        uILinkPoint2.Down = num + 6;
        key = num + 2;
        UILinkPoint uILinkPoint3 = UILinkPointNavigator.Points[key];
        uILinkPoint3.Unlink();
        uILinkPoint3.Left = num + 1;
        uILinkPoint3.Right = num + 4;
        uILinkPoint3.Down = num + 6;
        key = num + 4;
        UILinkPoint uILinkPoint4 = UILinkPointNavigator.Points[key];
        uILinkPoint4.Unlink();
        uILinkPoint4.Left = num + 2;
        uILinkPoint4.Right = num + 5;
        uILinkPoint4.Down = num + 6;
        key = num + 5;
        UILinkPoint uILinkPoint5 = UILinkPointNavigator.Points[key];
        uILinkPoint5.Unlink();
        uILinkPoint5.Left = num + 4;
        uILinkPoint5.Right = num + 3;
        uILinkPoint5.Down = num + 6;
        key = num + 3;
        UILinkPoint uILinkPoint6 = UILinkPointNavigator.Points[key];
        uILinkPoint6.Unlink();
        uILinkPoint6.Left = num + 5;
        uILinkPoint6.Down = num + 6;
        float num2 = 1f / Main.UIScale;
        Rectangle clippingRectangle = _uilist.GetClippingRectangle(spriteBatch);
        Vector2 minimum = clippingRectangle.TopLeft() * num2;
        Vector2 maximum = clippingRectangle.BottomRight() * num2;
        List<SnapPoint> snapPoints = _uilist.GetSnapPoints();
        for (int i = 0; i < snapPoints.Count; i++)
        {
            if (!snapPoints[i].Position.Between(minimum, maximum))
            {
                _ = snapPoints[i].Position;
                snapPoints.Remove(snapPoints[i]);
                i--;
            }
        }
        snapPoints.Sort((SnapPoint x, SnapPoint y) => x.Id.CompareTo(y.Id));
        for (int j = 0; j < snapPoints.Count; j++)
        {
            key = num + 6 + j;
            if (snapPoints[j].Name == "Thin")
            {
                UILinkPoint uILinkPoint7 = UILinkPointNavigator.Points[key];
                uILinkPoint7.Unlink();
                UILinkPointNavigator.SetPosition(key, snapPoints[j].Position);
                uILinkPoint7.Right = key + 1;
                uILinkPoint7.Down = ((j < snapPoints.Count - 2) ? (key + 2) : num);
                uILinkPoint7.Up = ((j < 2) ? (num + 1) : ((snapPoints[j - 1].Name == "Wide") ? (key - 1) : (key - 2)));
                UILinkPointNavigator.Points[num].Up = key;
                UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX = key;
                j++;
                if (j < snapPoints.Count)
                {
                    key = num + 6 + j;
                    UILinkPoint uILinkPoint8 = UILinkPointNavigator.Points[key];
                    uILinkPoint8.Unlink();
                    UILinkPointNavigator.SetPosition(key, snapPoints[j].Position);
                    uILinkPoint8.Left = key - 1;
                    uILinkPoint8.Down = ((j >= snapPoints.Count - 1) ? num : ((snapPoints[j + 1].Name == "Wide") ? (key + 1) : (key + 2)));
                    uILinkPoint8.Up = ((j < 2) ? (num + 1) : (key - 2));
                    UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX = key;
                }
            }
            else
            {
                UILinkPoint uILinkPoint9 = UILinkPointNavigator.Points[key];
                uILinkPoint9.Unlink();
                UILinkPointNavigator.SetPosition(key, snapPoints[j].Position);
                uILinkPoint9.Down = ((j < snapPoints.Count - 1) ? (key + 1) : num);
                uILinkPoint9.Up = ((j < 1) ? (num + 1) : ((snapPoints[j - 1].Name == "Wide") ? (key - 1) : (key - 2)));
                UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX = key;
                UILinkPointNavigator.Points[num].Up = key;
            }
        }
        if (ForceMoveTo != -1)
        {
            UILinkPointNavigator.ChangePoint((int)MathHelper.Clamp((float)ForceMoveTo, (float)num, (float)UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX));
            ForceMoveTo = -1;
        }
    }
References Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX, Terraria.UI.UIElement.GetClippingRectangle(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.GameContent.UI.Elements.UIList.GetSnapPoints(), Terraria.UI.SnapPoint.Id, Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.UI.CalculatedStyle.ToRectangle(), and Terraria.Main.UIScale.