TModLoader: Terraria.ModLoader.UI.UIModSources.OnInitialize
OnInitialize()
override void Terraria.ModLoader.UI.UIModSources.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 48 of file UIModSources.cs.
    {
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_033d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0342: Unknown result type (might be due to invalid IL or missing references)
        //IL_050b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0511: Unknown result type (might be due to invalid IL or missing references)
        //IL_0515: Unknown result type (might be due to invalid IL or missing references)
        //IL_051b: Unknown result type (might be due to invalid IL or missing references)
        //IL_051f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0525: Unknown result type (might be due to invalid IL or missing references)
        //IL_0529: Unknown result type (might be due to invalid IL or missing references)
        //IL_052f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0575: Unknown result type (might be due to invalid IL or missing references)
        //IL_057b: Unknown result type (might be due to invalid IL or missing references)
        //IL_057f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0585: Unknown result type (might be due to invalid IL or missing references)
        //IL_0589: Unknown result type (might be due to invalid IL or missing references)
        //IL_058f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0593: Unknown result type (might be due to invalid IL or missing references)
        //IL_0599: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0603: Unknown result type (might be due to invalid IL or missing references)
        //IL_0607: Unknown result type (might be due to invalid IL or missing references)
        //IL_060d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0611: Unknown result type (might be due to invalid IL or missing references)
        //IL_0617: Unknown result type (might be due to invalid IL or missing references)
        //IL_0674: Unknown result type (might be due to invalid IL or missing references)
        //IL_067a: Unknown result type (might be due to invalid IL or missing references)
        //IL_067e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0684: Unknown result type (might be due to invalid IL or missing references)
        //IL_0688: Unknown result type (might be due to invalid IL or missing references)
        //IL_068e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0692: Unknown result type (might be due to invalid IL or missing references)
        //IL_0698: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0700: Unknown result type (might be due to invalid IL or missing references)
        //IL_0704: Unknown result type (might be due to invalid IL or missing references)
        //IL_070a: Unknown result type (might be due to invalid IL or missing references)
        //IL_070e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0714: Unknown result type (might be due to invalid IL or missing references)
        _uIElement = new UIElement
        {
            Width =
            {
                Percent = 0.8f
            },
            MaxWidth = UICommon.MaxPanelWidth,
            Top =
            {
                Pixels = 220f
            },
            Height =
            {
                Pixels = -220f,
                Percent = 1f
            },
            HAlign = 0.5f
        };
        _uIPanel = new UIPanel
        {
            Width =
            {
                Percent = 1f
            },
            Height =
            {
                Pixels = -65f,
                Percent = 1f
            },
            BackgroundColor = UICommon.MainPanelBackground,
            PaddingTop = 0f
        };
        _uIElement.Append(_uIPanel);
        _uiLoader = new UILoaderAnimatedImage(0.5f, 0.5f);
        UIElement upperMenuContainer = new UIElement
        {
            Width =
            {
                Percent = 1f
            },
            Height =
            {
                Pixels = 82f
            },
            Top =
            {
                Pixels = 10f
            }
        };
        UIPanel filterTextBoxBackground = new UIPanel
        {
            Top =
            {
                Percent = 0f
            },
            Left =
            {
                Pixels = -135f,
                Percent = 1f
            },
            Width =
            {
                Pixels = 135f
            },
            Height =
            {
                Pixels = 32f
            }
        };
        filterTextBoxBackground.OnRightClick += delegate
        {
            filterTextBox.Text = "";
        };
        upperMenuContainer.Append(filterTextBoxBackground);
        filterTextBox = new UIInputTextField(Language.GetTextValue("tModLoader.ModsTypeToSearch"))
        {
            Top =
            {
                Pixels = 5f
            },
            Left =
            {
                Pixels = -125f,
                Percent = 1f
            },
            Width =
            {
                Pixels = 120f
            },
            Height =
            {
                Pixels = 20f
            }
        };
        filterTextBox.OnRightClick += delegate
        {
            filterTextBox.Text = "";
        };
        filterTextBox.OnTextChange += delegate
        {
            _updateNeeded = true;
        };
        upperMenuContainer.Append(filterTextBox);
        _uIPanel.Append(upperMenuContainer);
        _modList = new UIList
        {
            Width =
            {
                Pixels = -25f,
                Percent = 1f
            },
            Height =
            {
                Pixels = -134f,
                Percent = 1f
            },
            Top =
            {
                Pixels = 134f
            },
            ListPadding = 5f
        };
        _uIPanel.Append(_modList);
        UIScrollbar uIScrollbar = new UIScrollbar
        {
            Height =
            {
                Pixels = -134f,
                Percent = 1f
            },
            Top =
            {
                Pixels = 134f
            },
            HAlign = 1f
        }.WithView(100f, 1000f);
        _uIPanel.Append(uIScrollbar);
        _modList.SetScrollbar(uIScrollbar);
        UITextPanel<string> uIHeaderTextPanel = new UITextPanel<string>(Language.GetTextValue("tModLoader.MenuModSources"), 0.8f, large: true)
        {
            HAlign = 0.5f,
            Top =
            {
                Pixels = -35f
            },
            BackgroundColor = UICommon.DefaultUIBlue
        }.WithPadding(15f);
        _uIElement.Append(uIHeaderTextPanel);
        _links = new UIPanel
        {
            Width =
            {
                Percent = 1f
            },
            Height =
            {
                Pixels = 78f
            },
            Top =
            {
                Pixels = 46f
            }
        };
        _links.SetPadding(8f);
        _uIPanel.Append(_links);
        AddLink(Language.GetText("tModLoader.VersionUpgrade"), 0.5f, 0f, "https://github.com/tModLoader/tModLoader/wiki/Update-Migration-Guide");
        AddLink(Language.GetText("tModLoader.WikiLink"), 0f, 0.5f, "https://github.com/tModLoader/tModLoader/wiki/");
        string exampleModBranch = (BuildInfo.IsStable ? "stable" : (BuildInfo.IsPreview ? "preview" : "1.4.4"));
        AddLink(Language.GetText("tModLoader.ExampleModLink"), 1f, 0.5f, "https://github.com/tModLoader/tModLoader/tree/" + exampleModBranch + "/ExampleMod");
        string docsURL = (BuildInfo.IsStable ? "stable" : "preview");
        AddLink(Language.GetText("tModLoader.DocumentationLink"), 0f, 1f, "https://docs.tmodloader.net/docs/" + docsURL + "/annotated.html");
        AddLink(Language.GetText("tModLoader.DiscordLink"), 1f, 1f, "https://tmodloader.net/discord");
        UIAutoScaleTextTextPanel<string> buttonBA = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.MSBuildAll"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 1f / 3f
            },
            Height =
            {
                Pixels = 40f
            },
            VAlign = 1f,
            Top =
            {
                Pixels = -65f
            }
        };
        buttonBA.WithFadedMouseOver();
        buttonBA.OnLeftClick += BuildMods;
        UIAutoScaleTextTextPanel<string> uIAutoScaleTextTextPanel = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.MSBuildReloadAll"));
        uIAutoScaleTextTextPanel.CopyStyle(buttonBA);
        uIAutoScaleTextTextPanel.HAlign = 0.5f;
        uIAutoScaleTextTextPanel.WithFadedMouseOver();
        uIAutoScaleTextTextPanel.OnLeftClick += BuildAndReload;
        UIAutoScaleTextTextPanel<string> buttonCreateMod = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.MSCreateMod"));
        buttonCreateMod.CopyStyle(buttonBA);
        buttonCreateMod.HAlign = 1f;
        buttonCreateMod.Top.Pixels = -20f;
        buttonCreateMod.WithFadedMouseOver();
        buttonCreateMod.OnLeftClick += ButtonCreateMod_OnClick;
        _uIElement.Append(buttonCreateMod);
        UIAutoScaleTextTextPanel<string> buttonB = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("UI.Back"));
        buttonB.CopyStyle(buttonBA);
        buttonB.Top.Pixels = -20f;
        buttonB.WithFadedMouseOver();
        buttonB.OnLeftClick += BackClick;
        _uIElement.Append(buttonB);
        UIAutoScaleTextTextPanel<string> buttonOS = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.MSOpenSources"));
        buttonOS.CopyStyle(buttonB);
        buttonOS.HAlign = 0.5f;
        buttonOS.WithFadedMouseOver();
        buttonOS.OnLeftClick += OpenSources;
        _uIElement.Append(buttonOS);
        Append(_uIElement);
    }
References Terraria.ModLoader.UI.UIModSources._links, Terraria.ModLoader.UI.UIModSources._modList, Terraria.ModLoader.UI.UIModSources._uIElement, Terraria.ModLoader.UI.UIModSources._uiLoader, Terraria.ModLoader.UI.UIModSources._uIPanel, Terraria.ModLoader.UI.UIModSources._updateNeeded, Terraria.ModLoader.UI.UIModSources.AddLink(), Terraria.UI.UIElement.Append(), Terraria.ModLoader.UI.UIModSources.BackClick(), Terraria.ModLoader.UI.UIModSources.BuildAndReload(), Terraria.ModLoader.UI.UIModSources.BuildMods(), Terraria.ModLoader.UI.UIModSources.ButtonCreateMod_OnClick(), Terraria.ModLoader.UI.UIModSources.filterTextBox, Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.ModLoader.UI.UICommon.MainPanelBackground, Terraria.ModLoader.UI.UICommon.MaxPanelWidth, Terraria.UI.UIElement.MaxWidth, Terraria.ModLoader.UI.UIModSources.OpenSources(), Terraria.UI.UIElement.PaddingTop, Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.