TModLoader: Terraria.ModLoader.UI.UIModSources.BuildMods
BuildMods()
void Terraria.ModLoader.UI.UIModSources.BuildMods (UIMouseEvent evt, UIElement listeningElement) inline private
    {
        SoundEngine.PlaySound(10);
        if (_modList.Count > 0)
        {
            Interface.buildMod.BuildAll(reload: false);
        }
    }
References Terraria.ModLoader.UI.UIModSources._modList, Terraria.ModLoader.UI.UIBuildMod.BuildAll(), Terraria.ModLoader.UI.Interface.buildMod, Terraria.GameContent.UI.Elements.UIList.Count, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.ModLoader.UI.UIModSources.OnInitialize().