TModLoader: Terraria.ModLoader.UI.UIModSources.Populate
Populate()
void Terraria.ModLoader.UI.UIModSources.Populate () inline package
    {
        Task.Run(delegate
        {
            string[] array = ModCompile.FindModSources();
            IReadOnlyList<LocalMod> source = ModOrganizer.FindDevFolderMods();
            string[] array2 = array;
            foreach (string sourcePath in array2)
            {
                LocalMod builtMod = source.SingleOrDefault((LocalMod m) => m.Name == Path.GetFileName(sourcePath));
                _items.Add(new UIModSourceItem(sourcePath, builtMod));
            }
            _updateNeeded = true;
        });
    }
References Terraria.ModLoader.UI.UIModSources._items, Terraria.ModLoader.UI.UIModSources._updateNeeded, Terraria.ModLoader.Core.ModOrganizer.FindDevFolderMods(), and Terraria.ModLoader.Core.ModCompile.FindModSources().
Referenced by Terraria.ModLoader.UI.UIModSources.OnActivate().