TModLoader: Terraria.ModLoader.UI.UIModSources.OnActivate
OnActivate()
override void Terraria.ModLoader.UI.UIModSources.OnActivate () inline virtual
Reimplemented from Terraria.UI.UIElement.
    {
        _cts = new CancellationTokenSource();
        ModCompile.UpdateReferencesFolder();
        _uIPanel.Append(_uiLoader);
        _modList.Clear();
        _items.Clear();
        if (!ShowInfoMessages())
        {
            Populate();
        }
    }
References Terraria.ModLoader.UI.UIModSources._cts, Terraria.ModLoader.UI.UIModSources._items, Terraria.ModLoader.UI.UIModSources._modList, Terraria.ModLoader.UI.UIModSources._uiLoader, Terraria.ModLoader.UI.UIModSources._uIPanel, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.ModLoader.UI.UIModSources.Populate(), Terraria.ModLoader.UI.UIModSources.ShowInfoMessages(), and Terraria.ModLoader.Core.ModCompile.UpdateReferencesFolder().