TModLoader: Terraria.ModLoader.UI.UIModSources.AddLink
AddLink()
void Terraria.ModLoader.UI.UIModSources.AddLink (LocalizedText text, float hAlign, float vAlign, string url) inline private
    {
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        UIText link = new UIText(text)
        {
            TextColor = Color.White,
            HAlign = hAlign,
            VAlign = vAlign
        };
        link.OnMouseOver += delegate
        {
            //IL_001b: Unknown result type (might be due to invalid IL or missing references)
            SoundEngine.PlaySound(in SoundID.MenuTick);
            link.TextColor = Main.OurFavoriteColor;
        };
        link.OnMouseOut += delegate
        {
            //IL_0006: Unknown result type (might be due to invalid IL or missing references)
            link.TextColor = Color.White;
        };
        link.OnLeftClick += delegate
        {
            SoundEngine.PlaySound(in SoundID.MenuOpen);
            Utils.OpenToURL(url);
        };
        _links.Append(link);
    }
References Terraria.ModLoader.UI.UIModSources._links, Terraria.UI.UIElement.Append(), Terraria.UI.UIElement.HAlign, Terraria.ID.SoundID.MenuOpen, Terraria.ID.SoundID.MenuTick, Terraria.Utils.OpenToURL(), Terraria.Main.OurFavoriteColor, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.UI.UIElement.VAlign.
Referenced by Terraria.ModLoader.UI.UIModSources.OnInitialize().