TModLoader: Terraria.ModLoader.UI.UIModSources.Update
Update()
override void Terraria.ModLoader.UI.UIModSources.Update (GameTime gameTime) inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 562 of file UIModSources.cs.
    {
        base.Update(gameTime);
        if (_updateNeeded)
        {
            _updateNeeded = false;
            _uIPanel.RemoveChild(_uiLoader);
            _modList.Clear();
            string filter = filterTextBox.Text;
            _modList.AddRange(_items.Where((UIModSourceItem item) => filter.Length <= 0 || item.modName.IndexOf(filter, StringComparison.OrdinalIgnoreCase) != -1));
            Recalculate();
            _modList.ViewPosition = modListViewPosition;
        }
    }
References Terraria.ModLoader.UI.UIModSources._items, Terraria.ModLoader.UI.UIModSources._modList, Terraria.ModLoader.UI.UIModSources._uiLoader, Terraria.ModLoader.UI.UIModSources._uIPanel, Terraria.ModLoader.UI.UIModSources._updateNeeded, Terraria.GameContent.UI.Elements.UIList.AddRange(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.ModLoader.UI.UIModSources.filterTextBox, Terraria.ModLoader.UI.UIModSources.modListViewPosition, Terraria.ModLoader.UI.UIModSourceItem.modName, Terraria.UI.UIElement.Recalculate(), Terraria.UI.UIElement.RemoveChild(), and Terraria.ModLoader.UI.UIInputTextField.Text.