TModLoader: Terraria.UI.InGamePopups.AchievementUnlockedPopup.DrawInGame
DrawInGame()
void Terraria.UI.InGamePopups.AchievementUnlockedPopup.DrawInGame (SpriteBatch sb, Vector2 bottomAnchorPosition) inline
Implements Terraria.UI.IInGameNotification.
        {
            //IL_002f: Unknown result type (might be due to invalid IL or missing references)
            //IL_003e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0043: Unknown result type (might be due to invalid IL or missing references)
            //IL_0049: Unknown result type (might be due to invalid IL or missing references)
            //IL_004e: Unknown result type (might be due to invalid IL or missing references)
            //IL_004f: Unknown result type (might be due to invalid IL or missing references)
            //IL_005a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0067: Unknown result type (might be due to invalid IL or missing references)
            //IL_006c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0071: Unknown result type (might be due to invalid IL or missing references)
            //IL_0072: Unknown result type (might be due to invalid IL or missing references)
            //IL_0077: Unknown result type (might be due to invalid IL or missing references)
            //IL_0078: Unknown result type (might be due to invalid IL or missing references)
            //IL_007d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0081: Unknown result type (might be due to invalid IL or missing references)
            //IL_0083: Unknown result type (might be due to invalid IL or missing references)
            //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
            //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
            //IL_0099: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
            //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
            //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
            //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
            //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
            //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
            //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
            //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
            //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
            //IL_0101: Unknown result type (might be due to invalid IL or missing references)
            //IL_0106: Unknown result type (might be due to invalid IL or missing references)
            //IL_0114: Unknown result type (might be due to invalid IL or missing references)
            //IL_0117: Unknown result type (might be due to invalid IL or missing references)
            //IL_0121: Unknown result type (might be due to invalid IL or missing references)
            //IL_0127: Unknown result type (might be due to invalid IL or missing references)
            //IL_0144: Unknown result type (might be due to invalid IL or missing references)
            //IL_0162: Unknown result type (might be due to invalid IL or missing references)
            //IL_016e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0174: Unknown result type (might be due to invalid IL or missing references)
            //IL_0191: Unknown result type (might be due to invalid IL or missing references)
            //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
            //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
            //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
            //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
            //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
            //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
            //IL_01de: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
            //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
            float opacity = Opacity;
            if (opacity > 0f)
            {
                float num = Scale * 1.1f;
                Vector2 size = (FontAssets.ItemStack.Value.MeasureString(_title) + new Vector2(58f, 10f)) * num;
                Rectangle r = Utils.CenteredRectangle(bottomAnchorPosition + new Vector2(0f, (0f - size.Y) * 0.5f), size);
                Vector2 mouseScreen = Main.MouseScreen;
                bool num3 = ((Rectangle)(ref r)).Contains(mouseScreen.ToPoint());
                Utils.DrawInvBG(c: num3 ? (new Color(64, 109, 164) * 0.75f) : (new Color(64, 109, 164) * 0.5f), sb: sb, R: r);
                float num2 = num * 0.3f;
                Vector2 vector = r.Right() - Vector2.UnitX * num * (12f + num2 * (float)_achievementIconFrame.Width);
                sb.Draw(_achievementTexture.Value, vector, (Rectangle?)_achievementIconFrame, Color.White * opacity, 0f, new Vector2(0f, (float)(_achievementIconFrame.Height / 2)), num2, (SpriteEffects)0, 0f);
                sb.Draw(_achievementBorderTexture.Value, vector, (Rectangle?)null, Color.White * opacity, 0f, new Vector2(0f, (float)(_achievementIconFrame.Height / 2)), num2, (SpriteEffects)0, 0f);
                Utils.DrawBorderString(color: new Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, Main.mouseTextColor / 5, (int)Main.mouseTextColor) * opacity, sb: sb, text: _title, pos: vector - Vector2.UnitX * 10f, scale: num * 0.9f, anchorx: 1f, anchory: 0.4f);
                if (num3)
                {
                    OnMouseOver();
                }
            }
        }
References Terraria.UI.InGamePopups.AchievementUnlockedPopup._achievementBorderTexture, Terraria.UI.InGamePopups.AchievementUnlockedPopup._achievementIconFrame, Terraria.UI.InGamePopups.AchievementUnlockedPopup._achievementTexture, Terraria.UI.InGamePopups.AchievementUnlockedPopup._title, Terraria.Utils.CenteredRectangle(), Terraria.Utils.DrawBorderString(), Terraria.Utils.DrawInvBG(), Terraria.GameContent.FontAssets.ItemStack, Terraria.Main.MouseScreen, Terraria.Main.mouseTextColor, Terraria.UI.InGamePopups.AchievementUnlockedPopup.OnMouseOver(), Terraria.UI.InGamePopups.AchievementUnlockedPopup.Opacity, and Terraria.UI.InGamePopups.AchievementUnlockedPopup.Scale.