TModLoader: Terraria.GameContent.UI.States.UICharacterCreation.SelectColorPicker
SelectColorPicker()
void Terraria.GameContent.UI.States.UICharacterCreation.SelectColorPicker (CategoryId selection) inline private
    {
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_012e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        _selectedPicker = selection;
        switch (selection)
        {
        case CategoryId.CharInfo:
            Click_CharInfo(null, null);
            return;
        case CategoryId.Clothing:
            Click_ClothStyles(null, null);
            return;
        case CategoryId.HairStyle:
            Click_HairStyles(null, null);
            return;
        }
        UnselectAllCategories();
        _middleContainer.Append(_hslContainer);
        for (int i = 0; i < _colorPickers.Length; i++)
        {
            if (_colorPickers[i] != null)
            {
                _colorPickers[i].SetSelected(i == (int)selection);
            }
        }
        Vector3 currentColorHSL = Vector3.One;
        switch (_selectedPicker)
        {
        case CategoryId.HairColor:
            currentColorHSL = RgbToScaledHsl(_player.hairColor);
            break;
        case CategoryId.Eye:
            currentColorHSL = RgbToScaledHsl(_player.eyeColor);
            break;
        case CategoryId.Skin:
            currentColorHSL = RgbToScaledHsl(_player.skinColor);
            break;
        case CategoryId.Shirt:
            currentColorHSL = RgbToScaledHsl(_player.shirtColor);
            break;
        case CategoryId.Undershirt:
            currentColorHSL = RgbToScaledHsl(_player.underShirtColor);
            break;
        case CategoryId.Pants:
            currentColorHSL = RgbToScaledHsl(_player.pantsColor);
            break;
        case CategoryId.Shoes:
            currentColorHSL = RgbToScaledHsl(_player.shoeColor);
            break;
        }
        _currentColorHSL = currentColorHSL;
        UpdateHexText(ScaledHslToRgb(currentColorHSL.X, currentColorHSL.Y, currentColorHSL.Z));
    }
References Terraria.GameContent.UI.States.UICharacterCreation._colorPickers, Terraria.GameContent.UI.States.UICharacterCreation._currentColorHSL, Terraria.GameContent.UI.States.UICharacterCreation._hslContainer, Terraria.GameContent.UI.States.UICharacterCreation._middleContainer, Terraria.GameContent.UI.States.UICharacterCreation._player, Terraria.GameContent.UI.States.UICharacterCreation._selectedPicker, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UICharacterCreation.Click_CharInfo(), Terraria.GameContent.UI.States.UICharacterCreation.Click_ClothStyles(), Terraria.GameContent.UI.States.UICharacterCreation.Click_HairStyles(), Terraria.GameContent.UI.States.UICharacterCreation.RgbToScaledHsl(), Terraria.GameContent.UI.States.UICharacterCreation.ScaledHslToRgb(), Terraria.GameContent.UI.Elements.UIColoredImageButton.SetSelected(), Terraria.GameContent.UI.States.UICharacterCreation.UnselectAllCategories(), and Terraria.GameContent.UI.States.UICharacterCreation.UpdateHexText().
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.Click_ColorPicker(), and Terraria.GameContent.UI.States.UICharacterCreation.TryMovingCategory().