TModLoader: Terraria.GameContent.UI.States.UICharacterCreation.BuildPage
BuildPage()
void Terraria.GameContent.UI.States.UICharacterCreation.BuildPage () inline private
Definition at line 113 of file UICharacterCreation.cs.
    {
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        RemoveAllChildren();
        int num = 4;
        UIElement uIElement = new UIElement
        {
            Width = StyleDimension.FromPixels(500f),
            Height = StyleDimension.FromPixels(380 + num),
            Top = StyleDimension.FromPixels(220f),
            HAlign = 0.5f,
            VAlign = 0f
        };
        uIElement.SetPadding(0f);
        Append(uIElement);
        UIPanel uIPanel = new UIPanel
        {
            Width = StyleDimension.FromPercent(1f),
            Height = StyleDimension.FromPixels(uIElement.Height.Pixels - 150f - (float)num),
            Top = StyleDimension.FromPixels(50f),
            BackgroundColor = new Color(33, 43, 79) * 0.8f
        };
        uIPanel.SetPadding(0f);
        uIElement.Append(uIPanel);
        MakeBackAndCreatebuttons(uIElement);
        MakeCharPreview(uIPanel);
        UIElement uIElement2 = new UIElement
        {
            Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
            Height = StyleDimension.FromPixelsAndPercent(50f, 0f)
        };
        uIElement2.SetPadding(0f);
        uIElement2.PaddingTop = 4f;
        uIElement2.PaddingBottom = 0f;
        uIPanel.Append(uIElement2);
        UIElement uIElement3 = new UIElement
        {
            Top = StyleDimension.FromPixelsAndPercent(uIElement2.Height.Pixels + 6f, 0f),
            Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
            Height = StyleDimension.FromPixelsAndPercent(uIPanel.Height.Pixels - 70f, 0f)
        };
        uIElement3.SetPadding(0f);
        uIElement3.PaddingTop = 3f;
        uIElement3.PaddingBottom = 0f;
        uIPanel.Append(uIElement3);
        _topContainer = uIElement2;
        _middleContainer = uIElement3;
        MakeInfoMenu(uIElement3);
        MakeHSLMenu(uIElement3);
        MakeHairsylesMenu(uIElement3);
        MakeClothStylesMenu(uIElement3);
        MakeCategoriesBar(uIElement2);
        Click_CharInfo(null, null);
    }
References Terraria.GameContent.UI.States.UICharacterCreation._middleContainer, Terraria.GameContent.UI.States.UICharacterCreation._topContainer, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UICharacterCreation.Click_CharInfo(), Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.GameContent.UI.States.UICharacterCreation.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UICharacterCreation.MakeCategoriesBar(), Terraria.GameContent.UI.States.UICharacterCreation.MakeCharPreview(), Terraria.GameContent.UI.States.UICharacterCreation.MakeClothStylesMenu(), Terraria.GameContent.UI.States.UICharacterCreation.MakeHairsylesMenu(), Terraria.GameContent.UI.States.UICharacterCreation.MakeHSLMenu(), Terraria.GameContent.UI.States.UICharacterCreation.MakeInfoMenu(), Terraria.UI.StyleDimension.Pixels, Terraria.UI.UIElement.RemoveAllChildren(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UICharacterCreation.UICharacterCreation().