TModLoader: Terraria.TileObject.DrawPreview
DrawPreview()
static void Terraria.TileObject.DrawPreview (SpriteBatch sb, TileObjectPreviewData op, Vector2 position) inline static
    {
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_024a: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_024e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0261: Unknown result type (might be due to invalid IL or missing references)
        //IL_0262: Unknown result type (might be due to invalid IL or missing references)
        Point16 coordinates = op.Coordinates;
        Texture2D value = TextureAssets.Tile[op.Type].Value;
        TileObjectData tileData = TileObjectData.GetTileData(op.Type, op.Style, op.Alternate);
        int num = 0;
        int num5 = 0;
        int num6 = tileData.CalculatePlacementStyle(op.Style, op.Alternate, op.Random);
        int num7 = 0;
        int num8 = tileData.DrawYOffset;
        int drawXOffset = tileData.DrawXOffset;
        num6 += tileData.DrawStyleOffset;
        int num9 = tileData.StyleWrapLimit;
        int num10 = tileData.StyleLineSkip;
        if (tileData.StyleWrapLimitVisualOverride.HasValue)
        {
            num9 = tileData.StyleWrapLimitVisualOverride.Value;
        }
        if (tileData.styleLineSkipVisualOverride.HasValue)
        {
            num10 = tileData.styleLineSkipVisualOverride.Value;
        }
        if (num9 > 0)
        {
            num7 = num6 / num9 * num10;
            num6 %= num9;
        }
        if (tileData.StyleHorizontal)
        {
            num = tileData.CoordinateFullWidth * num6;
            num5 = tileData.CoordinateFullHeight * num7;
        }
        else
        {
            num = tileData.CoordinateFullWidth * num7;
            num5 = tileData.CoordinateFullHeight * num6;
        }
        for (int i = 0; i < op.Size.X; i++)
        {
            int x = num + (i - op.ObjectStart.X) * (tileData.CoordinateWidth + tileData.CoordinatePadding);
            int num11 = num5;
            for (int j = 0; j < op.Size.Y; j++)
            {
                int num12 = coordinates.X + i;
                int num2 = coordinates.Y + j;
                if (j == 0 && tileData.DrawStepDown != 0 && WorldGen.SolidTile(Framing.GetTileSafely(num12, num2 - 1)))
                {
                    num8 += tileData.DrawStepDown;
                }
                if (op.Type == 567)
                {
                    num8 = ((j != 0) ? tileData.DrawYOffset : (tileData.DrawYOffset - 2));
                }
                int num3 = op[i, j];
                Color color;
                if (num3 != 1)
                {
                    if (num3 != 2)
                    {
                        continue;
                    }
                    color = Color.Red * 0.7f;
                }
                else
                {
                    color = Color.White;
                }
                color *= 0.5f;
                if (i >= op.ObjectStart.X && i < op.ObjectStart.X + tileData.Width && j >= op.ObjectStart.Y && j < op.ObjectStart.Y + tileData.Height)
                {
                    SpriteEffects spriteEffects = (SpriteEffects)0;
                    if (tileData.DrawFlipHorizontal && num12 % 2 == 0)
                    {
                        spriteEffects = (SpriteEffects)(spriteEffects | 1);
                    }
                    if (tileData.DrawFlipVertical && num2 % 2 == 0)
                    {
                        spriteEffects = (SpriteEffects)(spriteEffects | 2);
                    }
                    int coordinateWidth = tileData.CoordinateWidth;
                    int num4 = tileData.CoordinateHeights[j - op.ObjectStart.Y];
                    if (op.Type == 114 && j == 1)
                    {
                        num4 += 2;
                    }
                    Rectangle? val = new Rectangle(x, num11, coordinateWidth, num4);
                    sb.Draw(value, new Vector2((float)(num12 * 16 - (int)(position.X + (float)(coordinateWidth - 16) / 2f) + drawXOffset), (float)(num2 * 16 - (int)position.Y + num8)), val, color, 0f, Vector2.Zero, 1f, spriteEffects, 0f);
                    num11 += num4 + tileData.CoordinatePadding;
                }
            }
        }
    }
References Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.Framing.GetTileSafely(), Terraria.WorldGen.SolidTile(), and Terraria.GameContent.TextureAssets.Tile.
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw().