TModLoader: Terraria.GameContent.ShopHelper.AddHappinessReportText
AddHappinessReportText()
void Terraria.GameContent.ShopHelper.AddHappinessReportText (string textKeyInCategory, object substitutes = null, int otherNPCType = 0) inline private
    {
        string text = "TownNPCMood_" + NPCID.Search.GetName(_currentNPCBeingTalkedTo.netID);
        if (textKeyInCategory == "Princess_LovesNPC")
        {
            text = ModContent.GetModNPC(otherNPCType).GetLocalizationKey("TownNPCMood");
        }
        else
        {
            ModNPC modNPC = _currentNPCBeingTalkedTo.ModNPC;
            if (modNPC != null)
            {
                text = modNPC.GetLocalizationKey("TownNPCMood");
            }
        }
        if (_currentNPCBeingTalkedTo.type == 633 && _currentNPCBeingTalkedTo.altTexture == 2)
        {
            text += "Transformed";
        }
        string textValueWith = Language.GetTextValueWith(text + "." + textKeyInCategory, substitutes);
        _currentHappiness = _currentHappiness + textValueWith + " ";
    }
References Terraria.GameContent.ShopHelper._currentHappiness, Terraria.GameContent.ShopHelper._currentNPCBeingTalkedTo, Terraria.NPC.altTexture, Terraria.ModLoader.ModContent.GetModNPC(), Terraria.Localization.Language.GetTextValueWith(), Terraria.NPC.ModNPC, Terraria.NPC.netID, Terraria.ID.NPCID.Search, and Terraria.NPC.type.
Referenced by Terraria.GameContent.ShopHelper.ApplyBiomeRelationshipEffect(), Terraria.GameContent.ShopHelper.ApplyNpcRelationshipEffect(), Terraria.GameContent.ShopHelper.IsFarFromHome(), Terraria.GameContent.ShopHelper.IsPlayerInEvilBiomes(), Terraria.GameContent.ShopHelper.LikePrincess(), Terraria.GameContent.ShopHelper.LoveNPCByTypeName(), Terraria.GameContent.ShopHelper.ProcessMood(), and Terraria.GameContent.ShopHelper.RuinMoodIfHomeless().