TModLoader: Terraria.ModLoader.Core.BuildProperties.ReadFromStream
ReadFromStream()
static BuildProperties Terraria.ModLoader.Core.BuildProperties.ReadFromStream (Stream stream) inline static package
    {
        BuildProperties properties = new BuildProperties();
        properties.hideCode = true;
        properties.hideResources = true;
        using BinaryReader reader = new BinaryReader(stream);
        string tag = reader.ReadString();
        while (tag.Length > 0)
        {
            if (tag == "dllReferences")
            {
                properties.dllReferences = ReadList(reader).ToArray();
            }
            if (tag == "modReferences")
            {
                properties.modReferences = ReadList(reader).Select(ModReference.Parse).ToArray();
            }
            if (tag == "weakReferences")
            {
                properties.weakReferences = ReadList(reader).Select(ModReference.Parse).ToArray();
            }
            if (tag == "sortAfter")
            {
                properties.sortAfter = ReadList(reader).ToArray();
            }
            if (tag == "sortBefore")
            {
                properties.sortBefore = ReadList(reader).ToArray();
            }
            if (tag == "author")
            {
                properties.author = reader.ReadString();
            }
            if (tag == "version")
            {
                properties.version = new Version(reader.ReadString());
            }
            if (tag == "displayName")
            {
                properties.displayName = reader.ReadString();
            }
            if (tag == "homepage")
            {
                properties.homepage = reader.ReadString();
            }
            if (tag == "description")
            {
                properties.description = reader.ReadString();
            }
            if (tag == "noCompile")
            {
                properties.noCompile = true;
            }
            if (tag == "!playableOnPreview")
            {
                properties.playableOnPreview = false;
            }
            if (tag == "translationMod")
            {
                properties.translationMod = true;
            }
            if (tag == "!hideCode")
            {
                properties.hideCode = false;
            }
            if (tag == "!hideResources")
            {
                properties.hideResources = false;
            }
            if (tag == "includeSource")
            {
                properties.includeSource = true;
            }
            if (tag == "eacPath")
            {
                properties.eacPath = reader.ReadString();
            }
            if (tag == "side")
            {
                properties.side = (ModSide)reader.ReadByte();
            }
            if (tag == "buildVersion")
            {
                properties.buildVersion = new Version(reader.ReadString());
            }
            tag = reader.ReadString();
        }
        return properties;
    }
References Terraria.ModLoader.Core.BuildProperties.ModReference.Parse(), and Terraria.ModLoader.Core.BuildProperties.ReadList().
Referenced by Terraria.ModLoader.Core.BuildProperties.InfoToBuildTxt(), and Terraria.ModLoader.Core.BuildProperties.ReadModFile().