TModLoader: Terraria.ModLoader.Core.BuildProperties.ReadBuildFile
ReadBuildFile()
static BuildProperties Terraria.ModLoader.Core.BuildProperties.ReadBuildFile (string modDir) inline static package
    {
        string propertiesFile = modDir + Path.DirectorySeparatorChar + "build.txt";
        string descriptionfile = modDir + Path.DirectorySeparatorChar + "description.txt";
        BuildProperties properties = new BuildProperties();
        if (!File.Exists(propertiesFile))
        {
            return properties;
        }
        if (File.Exists(descriptionfile))
        {
            properties.description = File.ReadAllText(descriptionfile);
        }
        string[] array = File.ReadAllLines(propertiesFile);
        foreach (string line in array)
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }
            int split = line.IndexOf('=');
            string property = line.Substring(0, split).Trim();
            string value = line.Substring(split + 1).Trim();
            if (value.Length == 0)
            {
                continue;
            }
            switch (property)
            {
            case "dllReferences":
                properties.dllReferences = ReadList(value).ToArray();
                break;
            case "modReferences":
                properties.modReferences = ReadList(value).Select(ModReference.Parse).ToArray();
                break;
            case "weakReferences":
                properties.weakReferences = ReadList(value).Select(ModReference.Parse).ToArray();
                break;
            case "sortBefore":
                properties.sortBefore = ReadList(value).ToArray();
                break;
            case "sortAfter":
                properties.sortAfter = ReadList(value).ToArray();
                break;
            case "author":
                properties.author = value;
                break;
            case "version":
                properties.version = new Version(value);
                break;
            case "displayName":
                properties.displayName = value;
                break;
            case "homepage":
                properties.homepage = value;
                break;
            case "noCompile":
                properties.noCompile = string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);
                break;
            case "playableOnPreview":
                properties.playableOnPreview = string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);
                break;
            case "translationMod":
                properties.translationMod = string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);
                break;
            case "hideCode":
                properties.hideCode = string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);
                break;
            case "hideResources":
                properties.hideResources = string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);
                break;
            case "includeSource":
                properties.includeSource = string.Equals(value, "true", StringComparison.OrdinalIgnoreCase);
                break;
            case "buildIgnore":
                properties.buildIgnores = (from s in value.Split(',')
                    select s.Trim().Replace('\\', Path.DirectorySeparatorChar).Replace('/', Path.DirectorySeparatorChar) into s
                    where s.Length > 0
                    select s).ToArray();
                break;
            case "side":
                if (!Enum.TryParse<ModSide>(value, ignoreCase: true, out properties.side))
                {
                    throw new Exception("side is not one of (Both, Client, Server, NoSync): " + value);
                }
                break;
            }
        }
        List<string> refs = properties.RefNames(includeWeak: true).ToList();
        if (refs.Count != refs.Distinct().Count())
        {
            throw new Exception("Duplicate mod/weak reference");
        }
        properties.sortAfter = (from dep in properties.RefNames(includeWeak: true)
            where !properties.sortBefore.Contains(dep)
            select dep).Concat(properties.sortAfter).Distinct().ToArray();
        return properties;
    }
References Terraria.ModLoader.Core.BuildProperties.ModReference.Parse(), and Terraria.ModLoader.Core.BuildProperties.ReadList().
Referenced by Terraria.ModLoader.Core.ModCompile.ReadBuildInfo().