TModLoader: Terraria.UI.Chat.ChatManager.GetStringSize
GetStringSize() [1/2]
static Vector2 Terraria.UI.Chat.ChatManager.GetStringSize (DynamicSpriteFont font, string text, Vector2 baseScale, float maxWidth = -1f) inline static
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        TextSnippet[] snippets = ParseMessage(text, Color.White).ToArray();
        return GetStringSize(font, snippets, baseScale, maxWidth);
    }
References Terraria.UI.Chat.ChatManager.GetStringSize(), and Terraria.UI.Chat.ChatManager.ParseMessage().
Referenced by Terraria.ModLoader.Config.UI.HeaderElement.HeaderElement(), Terraria.UI.Chat.ChatManager.AddChatText(), Terraria.Main.DoUpdate_HandleChat(), Terraria.Utils.DrawBorderStringBig(), Terraria.Main.DrawGamepadInstructions(), Terraria.ModLoader.UI.UICommon.DrawHoverStringInBounds(), Terraria.Main.DrawInterface_14_EntityHealthBars(), Terraria.UI.ItemSlot.DrawMoney(), Terraria.Main.DrawNetplayStatusText(), Terraria.Main.DrawNPCChatButtons(), Terraria.Main.DrawPlayerChat(), Terraria.GameContent.UI.CustomCurrencySingleCoin.DrawSavingsMoney(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingSimpleListItem.DrawSelf(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Main.GUIChatDrawInner(), Terraria.GameContent.UI.Elements.UIText.InternalSetText(), Terraria.Main.MouseText_DrawBuffTooltip(), Terraria.Main.MouseText_DrawItemTooltip(), Terraria.Player.OverheadMessage.NewMessage(), Terraria.GameContent.UI.Elements.UITextPanel< T >.SetText(), Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.SetText(), and Terraria.ModLoader.MenuLoader.UpdateAndDrawModMenu().