TModLoader: Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow
DrawColorCodedStringWithShadow() [2/5]
static Vector2 Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow (SpriteBatch spriteBatch, DynamicSpriteFont font, string text, Vector2 position, Color baseColor, float rotation, Vector2 origin, Vector2 baseScale, float maxWidth = -1f, float spread = 2f) inline static
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        TextSnippet[] snippets = ParseMessage(text, baseColor).ToArray();
        ConvertNormalSnippets(snippets);
        DrawColorCodedStringShadow(spriteBatch, font, snippets, position, new Color(0, 0, 0, (int)((Color)(ref baseColor)).A), rotation, origin, baseScale, maxWidth, spread);
        int hoveredSnippet;
        return DrawColorCodedString(spriteBatch, font, snippets, position, Color.White, rotation, origin, baseScale, out hoveredSnippet, maxWidth);
    }
References Terraria.UI.Chat.ChatManager.ConvertNormalSnippets(), Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow(), and Terraria.UI.Chat.ChatManager.ParseMessage().