TModLoader: Terraria.UI.Chat.ChatManager.DrawColorCodedString
DrawColorCodedString() [2/2]
static Vector2 Terraria.UI.Chat.ChatManager.DrawColorCodedString (SpriteBatch spriteBatch, DynamicSpriteFont font, TextSnippet[] snippets, Vector2 position, Color baseColor, float rotation, Vector2 origin, Vector2 baseScale, out int hoveredSnippet, float maxWidth, bool ignoreColors = false) inline static
Definition at line 267 of file ChatManager.cs.
    {
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0335: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_0140: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_022a: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_022f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_0257: Unknown result type (might be due to invalid IL or missing references)
        //IL_025c: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_025f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0261: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0202: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0282: Unknown result type (might be due to invalid IL or missing references)
        //IL_0291: Unknown result type (might be due to invalid IL or missing references)
        //IL_0297: Unknown result type (might be due to invalid IL or missing references)
        int num = -1;
        Vector2 vec = default(Vector2);
        ((Vector2)(ref vec))._002Ector((float)Main.mouseX, (float)Main.mouseY);
        Vector2 vector = position;
        Vector2 result = vector;
        float x = font.MeasureString(" ").X;
        Color color = baseColor;
        float num2 = 1f;
        float num3 = 0f;
        for (int i = 0; i < snippets.Length; i++)
        {
            TextSnippet textSnippet = snippets[i];
            textSnippet.Update();
            if (!ignoreColors)
            {
                color = textSnippet.GetVisibleColor();
            }
            num2 = textSnippet.Scale;
            if (textSnippet.UniqueDraw(justCheckingString: false, out var size, spriteBatch, vector, color, baseScale.X * num2))
            {
                if (vec.Between(vector, vector + size))
                {
                    num = i;
                }
                vector.X += size.X;
                result.X = Math.Max(result.X, vector.X);
                continue;
            }
            string[] array = textSnippet.Text.Split('\n');
            array = Regex.Split(textSnippet.Text, "(\n)");
            bool flag = true;
            string[] array3 = array;
            foreach (string obj in array3)
            {
                string[] array2 = Regex.Split(obj, "( )");
                array2 = obj.Split(' ');
                if (obj == "\n")
                {
                    vector.Y += (float)font.LineSpacing * num3 * baseScale.Y;
                    vector.X = position.X;
                    result.Y = Math.Max(result.Y, vector.Y);
                    num3 = 0f;
                    flag = false;
                    continue;
                }
                for (int j = 0; j < array2.Length; j++)
                {
                    if (j != 0)
                    {
                        vector.X += x * baseScale.X * num2;
                    }
                    if (maxWidth > 0f)
                    {
                        float num4 = font.MeasureString(array2[j]).X * baseScale.X * num2;
                        if (vector.X - position.X + num4 > maxWidth)
{
                            vector.X = position.X;
                            vector.Y += (float)font.LineSpacing * num3 * baseScale.Y;
                            result.Y = Math.Max(result.Y, vector.Y);
                            num3 = 0f;
                        }
                    }
                    if (num3 < num2)
                    {
                        num3 = num2;
                    }
                    spriteBatch.DrawString(font, array2[j], vector, color, rotation, origin, baseScale * textSnippet.Scale * num2, (SpriteEffects)0, 0f);
                    Vector2 vector2 = font.MeasureString(array2[j]);
                    if (vec.Between(vector, vector + vector2))
                    {
                        num = i;
                    }
                    vector.X += vector2.X * baseScale.X * num2;
                    result.X = Math.Max(result.X, vector.X);
                }
                if (array.Length > 1 && flag)
                {
                    vector.Y += (float)font.LineSpacing * num3 * baseScale.Y;
                    vector.X = position.X;
                    result.Y = Math.Max(result.Y, vector.Y);
                    num3 = 0f;
                }
                flag = true;
            }
        }
        hoveredSnippet = num;
        return result;
    }
References Terraria.Main.mouseX, and Terraria.Main.mouseY.
Referenced by Terraria.GameContent.Animations.Segments.LocalizedTextSegment.Draw(), Terraria.Utils.DrawBorderStringBig(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Main.DrawInterface_14_EntityHealthBars(), Terraria.Main.DrawNetplayStatusText(), and Terraria.GameContent.UI.Elements.UIText.DrawSelf().