TModLoader: Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow
DrawColorCodedStringShadow() [2/2]
static void Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow (SpriteBatch spriteBatch, DynamicSpriteFont font, TextSnippet[] snippets, Vector2 position, Color baseColor, float rotation, Vector2 origin, Vector2 baseScale, float maxWidth = -1f, float spread = 2f) inline static
    {
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        for (int i = 0; i < ShadowDirections.Length; i++)
        {
            DrawColorCodedString(spriteBatch, font, snippets, position + ShadowDirections[i] * spread, baseColor, rotation, origin, baseScale, out var _, maxWidth, ignoreColors: true);
        }
    }
References Terraria.UI.Chat.ChatManager.DrawColorCodedString(), and Terraria.UI.Chat.ChatManager.ShadowDirections.
Referenced by Terraria.GameContent.Animations.Segments.LocalizedTextSegment.Draw(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Main.DrawInterface_14_EntityHealthBars(), and Terraria.GameContent.UI.Elements.UIText.DrawSelf().