TModLoader: Terraria.Chest.FindEmptyChest
FindEmptyChest()
static int Terraria.Chest.FindEmptyChest (int x, int y, int type = 21, int style = 0, int direction = 1, int alternate = 0) inline static
Determines if a new chest can exist at tile coordinates (x , y).
Parameters
x The x-coordinate to check, in tile coordinates.
y The y-coordinate to check, in tile coordinates.
type Unused, but required for use with F:Terraria.DataStructures.PlacementHook.hook.
style Unused, but required for use with F:Terraria.DataStructures.PlacementHook.hook.
direction Unused, but required for use with F:Terraria.DataStructures.PlacementHook.hook.
alternate Unused, but required for use with F:Terraria.DataStructures.PlacementHook.hook.
Returns
-1 if there exists a chest in F:Terraria.Main.chest at the coordinates (x , y), or if F:Terraria.Main.chest contains no null elements.
Otherwise, the index in F:Terraria.Main.chest of the first null element.
Definition at line 805 of file Chest.cs.
    {
        int num = -1;
        for (int i = 0; i < 8000; i++)
        {
            Chest chest = Main.chest[i];
            if (chest != null)
            {
                if (chest.x == x && chest.y == y)
                {
                    return -1;
                }
            }
            else if (num == -1)
            {
                num = i;
            }
        }
        return num;
    }
References Terraria.Main.chest, Terraria.Chest.x, and Terraria.Chest.y.
Referenced by Terraria.Chest.AfterPlacement_Hook(), Terraria.Chest.CreateChest(), and Terraria.ObjectData.TileObjectData.Initialize().