TModLoader: Terraria.Chest.SetupShop
SetupShop() [2/2]
void Terraria.Chest.SetupShop (string shopName, NPC npc) inline
Definition at line 3825 of file Chest.cs.
    {
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        Array.Fill(this.item, null);
        if (NPCShopDatabase.TryGetNPCShop(shopName, out var shop))
        {
            shop.FillShop(this.item, npc, out var overflow);
            if (overflow)
            {
                Main.NewText(Language.GetTextValue("tModLoader.ShopOverflow"), Color.Orange);
                Logging.tML.Warn((object)("Unable to fit all item in the shop " + shopName));
            }
        }
        if (npc != null)
        {
            NPCLoader.ModifyActiveShop(npc, shopName, this.item);
        }
        Span<Item> span = this.item.AsSpan();
        for (int i = 0; i < span.Length; i++)
        {
            ref Item item = ref span[i];
            if (item == null)
            {
                item = new Item();
            }
            item.isAShopItem = true;
        }
    }
References Terraria.Localization.Language.GetTextValue(), Terraria.Chest.item, Terraria.ModLoader.NPCLoader.ModifyActiveShop(), Terraria.Main.NewText(), Terraria.ModLoader.Logging.tML, and Terraria.ModLoader.NPCShopDatabase.TryGetNPCShop().