TModLoader: Terraria.Chest.ServerPlaceItem
ServerPlaceItem()
static void Terraria.Chest.ServerPlaceItem (int plr, int slot) inline static
Attempts to move the item in plr 's inventory or Void Vault into nearby chests.
Only called on F:Terraria.ID.NetmodeID.Server.
Parameters
plr The index of the T:Terraria.Player in F:Terraria.Main.player to try moving an item for.
slot The T:Terraria.ID.PlayerItemSlotID to move an item from.
If slot < 58, then that slot of plr 's inventory is moved.
If slot >= F:Terraria.ID.PlayerItemSlotID.Bank4_0 && slot < F:Terraria.ID.PlayerItemSlotID.Bank4_0 + 40, then that slot (minus F:Terraria.ID.PlayerItemSlotID.Bank4_0) of plr 's Void Vault is moved.
Otherwise, no item is moved.
It's recommended to use M:Terraria.Player.QuickStackAllChests to handle this automatically.
    {
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        if (slot >= PlayerItemSlotID.Bank4_0 && slot < PlayerItemSlotID.Bank4_0 + 40)
        {
            int num = slot - PlayerItemSlotID.Bank4_0;
            Main.player[plr].bank4.item[num] = PutItemInNearbyChest(Main.player[plr].bank4.item[num], Main.player[plr].Center);
            NetMessage.SendData(5, -1, -1, null, plr, slot, Main.player[plr].bank4.item[num].prefix);
        }
        else if (slot < 58)
        {
            Main.player[plr].inventory[slot] = PutItemInNearbyChest(Main.player[plr].inventory[slot], Main.player[plr].Center);
            NetMessage.SendData(5, -1, -1, null, plr, slot, Main.player[plr].inventory[slot].prefix);
        }
    }
References Terraria.ID.PlayerItemSlotID.Bank4_0, Terraria.Main.player, Terraria.Chest.PutItemInNearbyChest(), and Terraria.NetMessage.SendData().
Referenced by Terraria.MessageBuffer.GetData().