TModLoader: Terraria.Chest.Lock
Lock()
static bool Terraria.Chest.Lock (int X, int Y) inline static
Locks an unlocked chest.
Parameters
X The x-coordinate of the unlocked chest, in tile coordinates.
Y The y-coordinate of the unlocked chest, in tile coordinates.
Returns
true if the chest successfully locked, false otherwise.
    {
        if (Main.tile[X, Y] == null || Main.tile[X + 1, Y] == null || Main.tile[X, Y + 1] == null || Main.tile[X + 1, Y + 1] == null)
        {
            return false;
        }
        short num = 0;
        Tile tileSafely = Framing.GetTileSafely(X, Y);
        int type = tileSafely.type;
        int num2 = tileSafely.frameX / 36;
        if (Main.tile[X, Y].type >= TileID.Count)
        {
            num = 36;
            bool manual = false;
            if (!TileLoader.LockChest(X, Y, Main.tile[X, Y].type, ref num, ref manual))
            {
                return false;
            }
            if (manual)
            {
                return true;
            }
        }
        else
        {
            switch (type)
            {
            case 21:
                switch (num2)
                {
                case 1:
                    num = 36;
                    break;
                case 3:
                    num = 36;
                    break;
                case 18:
                case 19:
                case 20:
                case 21:
                case 22:
                    if (!NPC.downedPlantBoss)
                    {
                        return false;
                    }
                    num = 180;
                    break;
                case 35:
                case 37:
                case 39:
                    num = 36;
                    break;
                default:
                    return false;
                }
                break;
            case 467:
                if (num2 == 12)
                {
                    if (!NPC.downedPlantBoss)
                    {
                        return false;
                    }
                    num = 36;
                    AchievementsHelper.NotifyProgressionEvent(20);
                    break;
                }
                return false;
            }
        }
        SoundEngine.PlaySound(22, X * 16, Y * 16);
        for (int i = X; i <= X + 1; i++)
        {
            for (int j = Y; j <= Y + 1; j++)
            {
                Tile tileSafely2 = Framing.GetTileSafely(i, j);
                if (tileSafely2.type == type)
                {
                    tileSafely2.frameX += num;
                }
            }
        }
        return true;
    }
References Terraria.ID.TileID.Count, Terraria.NPC.downedPlantBoss, Terraria.Framing.GetTileSafely(), Terraria.ModLoader.TileLoader.LockChest(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.tile.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Player.PlaceThing_LockChest().