TModLoader: Terraria.Chest.AfterPlacement_Hook
AfterPlacement_Hook()
static int Terraria.Chest.AfterPlacement_Hook (int x, int y, int type = 21, int style = 0, int direction = 1, int alternate = 0) inline static
Registers a placed chest into the world.
Parameters
x The x-coordinate to check, in tile coordinates.
y The y-coordinate to check, in tile coordinates.
type The tile type of the placed chest.
style The tile style of the placed chest.
direction Unused, but required for use with F:Terraria.DataStructures.PlacementHook.hook.
alternate Unused, but required for use with F:Terraria.DataStructures.PlacementHook.hook.
Returns
-1 if there exists a chest in F:Terraria.Main.chest at the coordinates (x , y), or if F:Terraria.Main.chest contains no null elements.
Otherwise, the index in F:Terraria.Main.chest of the newly-created chest.
    {
        Point16 baseCoords = new Point16(x, y);
        TileObjectData.OriginToTopLeft(type, style, ref baseCoords);
        int num = FindEmptyChest(baseCoords.X, baseCoords.Y);
        if (num == -1)
        {
            return -1;
        }
        if (Main.netMode != 1)
        {
            Chest chest = new Chest();
            chest.x = baseCoords.X;
            chest.y = baseCoords.Y;
            for (int i = 0; i < 40; i++)
            {
                chest.item[i] = new Item();
            }
            Main.chest[num] = chest;
        }
        else
        {
            switch (type)
            {
            case 21:
                NetMessage.SendData(34, -1, -1, null, 0, x, y, style);
                break;
            case 467:
                NetMessage.SendData(34, -1, -1, null, 4, x, y, style);
                break;
            case 88:
                NetMessage.SendData(34, -1, -1, null, 2, x, y, style);
                break;
            default:
                if (TileID.Sets.BasicChest[type])
                {
                    NetMessage.SendData(34, -1, -1, null, 100, x, y, style, 0, type);
                }
                else if (TileID.Sets.BasicDresser[type])
                {
                    NetMessage.SendData(34, -1, -1, null, 102, x, y, style, 0, type);
                }
                break;
            }
        }
        return num;
    }
References Terraria.ID.TileID.Sets.BasicChest, Terraria.ID.TileID.Sets.BasicDresser, Terraria.Main.chest, Terraria.Chest.FindEmptyChest(), Terraria.Chest.item, Terraria.Main.netMode, Terraria.ObjectData.TileObjectData.OriginToTopLeft(), Terraria.NetMessage.SendData(), Terraria.Chest.x, and Terraria.Chest.y.
Referenced by Terraria.ObjectData.TileObjectData.Initialize().