TModLoader: Terraria.Chest.PutItemInNearbyChest
PutItemInNearbyChest()
static Item Terraria.Chest.PutItemInNearbyChest (Item item, Vector2 position) inline static
Attempts to move the given item into any chests near the given position. Cannot place items into a chest if M:Terraria.Chest.IsPlayerInChest(System.Int32) or if that chest M:Terraria.Chest.IsLocked(System.Int32,System.Int32)
Parameters
item The item to attempt moving.
position The position to attempt moving from.
Returns
If on F:Terraria.ID.NetmodeID.MultiplayerClient, item without modification.
Otherwise, item after being quick-stacked into any nearby chests. May be P:Terraria.Item.IsAir.
    {
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode == 1)
        {
            return item;
        }
        bool flag = true;
        Vector2 vector = default(Vector2);
        for (int i = 0; i < 8000; i++)
        {
            bool flag2 = false;
            bool flag3 = false;
            if (Main.chest[i] == null || IsPlayerInChest(i) || IsLocked(Main.chest[i].x, Main.chest[i].y))
            {
                continue;
            }
            ((Vector2)(ref vector))._002Ector((float)(Main.chest[i].x * 16 + 16), (float)(Main.chest[i].y * 16 + 16));
            Vector2 val = vector - position;
            if (((Vector2)(ref val)).Length() >= 600f)
            {
                continue;
            }
            for (int j = 0; j < Main.chest[i].item.Length; j++)
            {
                if (Main.chest[i].item[j].IsAir)
                {
                    flag3 = true;
                }
                else if (item.IsTheSameAs(Main.chest[i].item[j]))
                {
                    flag2 = true;
                    if (ItemLoader.TryStackItems(Main.chest[i].item[j], item, out var numTransfered))
                    {
                        if (numTransfered > 0)
{
                            VisualizeChestTransfer(position, vector, item, numTransfered);
                        }
                        if (item.stack <= 0)
{
                            item.SetDefaults();
                            return item;
                        }
                    }
                }
                else
                {
                    flag3 = true;
                }
            }
            if (!(flag2 && flag3) || item.stack <= 0)
            {
                continue;
            }
            for (int k = 0; k < Main.chest[i].item.Length; k++)
            {
                if (Main.chest[i].item[k].type == 0 || Main.chest[i].item[k].stack == 0)
                {
                    VisualizeChestTransfer(position, vector, item, item.stack);
                    if (flag)
                    {
                        Main.chest[i].item[k] = item.Clone();
                        item.SetDefaults();
                    }
                    return item;
                }
            }
        }
        return item;
    }
References Terraria.Main.chest, Terraria.Item.Clone(), Terraria.Chest.IsLocked(), Terraria.Chest.IsPlayerInChest(), Terraria.Item.IsTheSameAs(), Terraria.Chest.item, Terraria.Main.netMode, Terraria.Item.SetDefaults(), Terraria.Item.stack, Terraria.ModLoader.ItemLoader.TryStackItems(), and Terraria.Chest.VisualizeChestTransfer().
Referenced by Terraria.Player.QuickStackAllChests(), and Terraria.Chest.ServerPlaceItem().