TModLoader: Terraria.Chest.Unlock
Unlock()
static bool Terraria.Chest.Unlock (int X, int Y) inline static
Unlocks a locked chest.
Parameters
X The x-coordinate of the locked chest, in tile coordinates.
Y The y-coordinate of the locked chest, in tile coordinates.
Returns
true if the chest successfully unlocked, false otherwise.
    {
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f9: Unknown result type (might be due to invalid IL or missing references)
        if (Main.tile[X, Y] == null || Main.tile[X + 1, Y] == null || Main.tile[X, Y + 1] == null || Main.tile[X + 1, Y + 1] == null)
        {
            return false;
        }
        short num = 0;
        int type = 0;
        Tile tileSafely = Framing.GetTileSafely(X, Y);
        int type2 = tileSafely.type;
        int num2 = tileSafely.frameX / 36;
        if (Main.tile[X, Y].type >= TileID.Count)
        {
            num = -36;
            type = 11;
            bool manual = false;
            if (!TileLoader.UnlockChest(X, Y, Main.tile[X, Y].type, ref num, ref type, ref manual))
            {
                return false;
            }
            if (manual)
            {
                return true;
            }
            num *= -1;
        }
        else
        {
            switch (type2)
            {
            case 21:
                switch (num2)
                {
                case 2:
                    num = 36;
                    type = 11;
                    AchievementsHelper.NotifyProgressionEvent(19);
                    break;
                case 4:
                    num = 36;
                    type = 11;
                    break;
                case 23:
                case 24:
                case 25:
                case 26:
                case 27:
                    if (!NPC.downedPlantBoss)
                    {
                        return false;
                    }
                    num = 180;
                    type = 11;
                    AchievementsHelper.NotifyProgressionEvent(20);
                    break;
                case 36:
                case 38:
                case 40:
                    num = 36;
                    type = 11;
                    break;
                default:
                    return false;
                }
                break;
            case 467:
                if (num2 == 13)
                {
                    if (!NPC.downedPlantBoss)
                    {
                        return false;
                    }
                    num = 36;
                    type = 11;
                    AchievementsHelper.NotifyProgressionEvent(20);
                    break;
                }
                return false;
            }
        }
        SoundEngine.PlaySound(22, X * 16, Y * 16);
        for (int i = X; i <= X + 1; i++)
        {
            for (int j = Y; j <= Y + 1; j++)
            {
                Tile tileSafely2 = Framing.GetTileSafely(i, j);
                if (tileSafely2.type == type2)
                {
                    tileSafely2.frameX -= num;
                    for (int k = 0; k < 4; k++)
                    {
                        Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, type);
                    }
                }
            }
        }
        return true;
    }
References Terraria.ID.TileID.Count, Terraria.NPC.downedPlantBoss, Terraria.Framing.GetTileSafely(), Terraria.Dust.NewDust(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.tile, and Terraria.ModLoader.TileLoader.UnlockChest().
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Player.TileInteractionsUse().