TModLoader: Terraria.ModLoader.PylonLoader.PreCanPlacePylon
PreCanPlacePylon()
static ? bool Terraria.ModLoader.PylonLoader.PreCanPlacePylon (int x, int y, int tileType, TeleportPylonType pylonType) inline static
Definition at line 65 of file PylonLoader.cs.
    {
        bool? returnValue = null;
        foreach (GlobalPylon globalPylon in globalPylons)
        {
            bool? shouldSucceed = globalPylon.PreCanPlacePylon(x, y, tileType, pylonType);
            if (shouldSucceed.HasValue)
            {
                if (!shouldSucceed.Value)
                {
                    return false;
                }
                returnValue = true;
            }
        }
        return returnValue;
    }
References Terraria.ModLoader.PylonLoader.globalPylons.
Referenced by Terraria.GameContent.Tile_Entities.TETeleportationPylon.NetPlaceEntityAttempt(), Terraria.ModLoader.Default.TEModdedPylon.NetPlaceEntityAttempt(), Terraria.ModLoader.Default.TEModdedPylon.PlacementPreviewHook_CheckIfCanPlace(), and Terraria.GameContent.Tile_Entities.TETeleportationPylon.PlacementPreviewHook_CheckIfCanPlace().