TModLoader: Terraria.GameContent.UI.Elements.UICharacterListItem.AddTmlElements
AddTmlElements()
void Terraria.GameContent.UI.Elements.UICharacterListItem.AddTmlElements (PlayerFileData data) inline private
    {
        if (data.customDataFail != null)
        {
            UIImageButton errorButton = new UIImageButton(_errorTexture)
            {
                VAlign = 1f,
                HAlign = 1f
            };
            errorButton.Left.Set(-24f, 0f);
            errorButton.OnLeftClick += ErrorButtonClick;
            errorButton.OnMouseOver += ErrorMouseOver;
            errorButton.OnMouseOut += DeleteMouseOut;
            Append(errorButton);
        }
        if (data.Player.usedMods == null)
        {
            return;
        }
        string[] currentModNames = Terraria.ModLoader.ModLoader.Mods.Select((Mod m) => m.Name).ToArray();
        List<string> missingMods = data.Player.usedMods.Except(currentModNames).ToList();
        List<string> newMods = currentModNames.Except(new string[1] { "ModLoader" }).Except(data.Player.usedMods).ToList();
        bool checkModPack = Path.GetFileNameWithoutExtension(ModOrganizer.ModPackActive) != data.Player.modPack;
        if (!checkModPack && missingMods.Count <= 0 && newMods.Count <= 0)
        {
            return;
        }
        UIText warningLabel = new UIText("")
        {
            VAlign = 0f,
            HAlign = 1f
        };
        warningLabel.Left.Set(-30f, 0f);
        warningLabel.Top.Set(3f, 0f);
        Append(warningLabel);
        UIImageButton modListWarning = new UIImageButton(_errorTexture)
        {
            VAlign = 0f,
            HAlign = 1f
        };
        modListWarning.Top.Set(-2f, 0f);
        StringBuilder fullSB = new StringBuilder(Language.GetTextValue("tModLoader.ModsDifferentSinceLastPlay"));
        StringBuilder shortSB = new StringBuilder();
        if (checkModPack)
        {
            string pack = data.Player.modPack;
            if (string.IsNullOrEmpty(pack))
            {
                pack = "None";
            }
            shortSB.Append(Separator() + Language.GetTextValue("tModLoader.ModPackMismatch", pack));
            fullSB.Append("\n" + Language.GetTextValue("tModLoader.ModPackMismatch", pack));
        }
        if (missingMods.Count > 0)
        {
            shortSB.Append(Separator() + ((missingMods.Count > 1) ? Language.GetTextValue("tModLoader.MissingXMods", missingMods.Count) : Language.GetTextValue("tModLoader.Missing1Mod")));
            fullSB.Append("\n" + Language.GetTextValue("tModLoader.MissingModsListing", string.Join("\n", missingMods.Select((string x) => "- " + x))));
        }
        if (newMods.Count > 0)
        {
            shortSB.Append(Separator() + ((newMods.Count > 1) ? Language.GetTextValue("tModLoader.NewXMods", newMods.Count) : Language.GetTextValue("tModLoader.New1Mod")));
            fullSB.Append("\n" + Language.GetTextValue("tModLoader.NewModsListing", string.Join("\n", newMods.Select((string x) => "- " + x))));
        }
        if (shortSB.Length != 0)
        {
            shortSB.Append('.');
        }
        string warning = shortSB.ToString();
        string fullWarning = fullSB.ToString();
        modListWarning.OnMouseOver += delegate
        {
            warningLabel.SetText(warning);
        };
        modListWarning.OnMouseOut += delegate
        {
            warningLabel.SetText("");
        };
        modListWarning.OnLeftClick += delegate
        {
            Interface.infoMessage.Show(fullWarning, 888, Main._characterSelectMenu);
        };
        Append(modListWarning);
        string Separator()
        {
            if (shortSB.Length == 0)
            {
                return null;
            }
            return "; ";
        }
    }
References Terraria.Main._characterSelectMenu, Terraria.GameContent.UI.Elements.UICharacterListItem._errorTexture, Terraria.UI.UIElement.Append(), Terraria.IO.PlayerFileData.customDataFail, Terraria.GameContent.UI.Elements.UICharacterListItem.DeleteMouseOut(), Terraria.GameContent.UI.Elements.UICharacterListItem.ErrorButtonClick(), Terraria.GameContent.UI.Elements.UICharacterListItem.ErrorMouseOver(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.HAlign, Terraria.ModLoader.UI.Interface.infoMessage, Terraria.Player.modPack, Terraria.ModLoader.Core.ModOrganizer.ModPackActive, Terraria.ModLoader.ModLoader.Mods, Terraria.IO.PlayerFileData.Player, Terraria.Player.usedMods, and Terraria.UI.UIElement.VAlign.
Referenced by Terraria.GameContent.UI.Elements.UICharacterListItem.UICharacterListItem().