TModLoader: Terraria.GameContent.UI.Elements.UICharacterListItem.DeleteMouseOver
DeleteMouseOver()
void Terraria.GameContent.UI.Elements.UICharacterListItem.DeleteMouseOver (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 197 of file UICharacterListItem.cs.
    {
        if (_data.IsFavorite)
        {
            _deleteButtonLabel.SetText(Language.GetTextValue("UI.CannotDeleteFavorited"));
        }
        else
        {
            _deleteButtonLabel.SetText(Language.GetTextValue("UI.Delete"));
        }
    }
References Terraria.GameContent.UI.Elements.UICharacterListItem._data, Terraria.GameContent.UI.Elements.UICharacterListItem._deleteButtonLabel, Terraria.Localization.Language.GetTextValue(), Terraria.IO.FileData.IsFavorite, and Terraria.GameContent.UI.Elements.UIText.SetText().
Referenced by Terraria.GameContent.UI.Elements.UICharacterListItem.UICharacterListItem().