TModLoader: Terraria.GameContent.UI.Elements.UICharacterListItem.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UICharacterListItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 383 of file UICharacterListItem.cs.
    {
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00de: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0209: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_021a: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_026a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0276: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0280: Unknown result type (might be due to invalid IL or missing references)
        //IL_0295: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_032b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        //IL_0340: Unknown result type (might be due to invalid IL or missing references)
        //IL_0345: Unknown result type (might be due to invalid IL or missing references)
        //IL_0355: Unknown result type (might be due to invalid IL or missing references)
        //IL_035a: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0372: Unknown result type (might be due to invalid IL or missing references)
        //IL_0388: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0392: Unknown result type (might be due to invalid IL or missing references)
        //IL_0397: Unknown result type (might be due to invalid IL or missing references)
        //IL_0399: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0437: Unknown result type (might be due to invalid IL or missing references)
        //IL_044d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0463: Unknown result type (might be due to invalid IL or missing references)
        //IL_0468: Unknown result type (might be due to invalid IL or missing references)
        //IL_046d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0472: Unknown result type (might be due to invalid IL or missing references)
        //IL_0474: Unknown result type (might be due to invalid IL or missing references)
        //IL_0489: Unknown result type (might be due to invalid IL or missing references)
        base.DrawSelf(spriteBatch);
        CalculatedStyle innerDimensions = GetInnerDimensions();
        CalculatedStyle dimensions = _playerPanel.GetDimensions();
        float num = dimensions.X + dimensions.Width;
        Color color = Color.White;
        string text = _data.Name;
        if (_data.Player.loadStatus != 0)
        {
            color = Color.Gray;
            string name = StatusID.Search.GetName(_data.Player.loadStatus);
            text = "(" + name + ") " + text;
        }
        Utils.DrawBorderString(spriteBatch, text, new Vector2(num + 6f, dimensions.Y - 2f), color);
        spriteBatch.Draw(_dividerTexture.Value, new Vector2(num, innerDimensions.Y + 21f), (Rectangle?)null, Color.White, 0f, Vector2.Zero, new Vector2((GetDimensions().X + GetDimensions().Width - num) / 8f, 1f), (SpriteEffects)0, 0f);
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(num + 6f, innerDimensions.Y + 29f);
        float num2 = 200f;
        Vector2 vector2 = vector;
        DrawPanel(spriteBatch, vector2, num2);
        spriteBatch.Draw(TextureAssets.Heart.Value, vector2 + new Vector2(5f, 2f), Color.White);
        vector2.X += 10f + (float)TextureAssets.Heart.Width();
        Utils.DrawBorderString(spriteBatch, _data.Player.statLifeMax2 + Language.GetTextValue("GameUI.PlayerLifeMax"), vector2 + new Vector2(0f, 3f), Color.White);
        vector2.X += 65f;
        spriteBatch.Draw(TextureAssets.Mana.Value, vector2 + new Vector2(5f, 2f), Color.White);
        vector2.X += 10f + (float)TextureAssets.Mana.Width();
        Utils.DrawBorderString(spriteBatch, _data.Player.statManaMax2 + Language.GetTextValue("GameUI.PlayerManaMax"), vector2 + new Vector2(0f, 3f), Color.White);
        vector.X += num2 + 5f;
        Vector2 vector3 = vector;
        float num3 = 140f;
        if (GameCulture.FromCultureName(GameCulture.CultureName.Russian).IsActive)
        {
            num3 = 180f;
        }
        DrawPanel(spriteBatch, vector3, num3);
        string text2 = "";
        Color color2 = Color.White;
        switch (_data.Player.difficulty)
        {
        case 0:
            text2 = Language.GetTextValue("UI.Softcore");
            break;
        case 1:
            text2 = Language.GetTextValue("UI.Mediumcore");
            color2 = Main.mcColor;
            break;
        case 2:
            text2 = Language.GetTextValue("UI.Hardcore");
            color2 = Main.hcColor;
            break;
        case 3:
            text2 = Language.GetTextValue("UI.Creative");
            color2 = Main.creativeModeColor;
            break;
        }
        vector3 += new Vector2(num3 * 0.5f - FontAssets.MouseText.Value.MeasureString(text2).X * 0.5f, 3f);
        Utils.DrawBorderString(spriteBatch, text2, vector3, color2);
        vector.X += num3 + 5f;
        Vector2 vector4 = vector;
        float num4 = innerDimensions.X + innerDimensions.Width - vector4.X;
        DrawPanel(spriteBatch, vector4, num4);
        TimeSpan playTime = _data.GetPlayTime();
        int num5 = playTime.Days * 24 + playTime.Hours;
        string text3 = ((num5 < 10) ? "0" : "") + num5 + playTime.ToString("\\:mm\\:ss");
        vector4 += new Vector2(num4 * 0.5f - FontAssets.MouseText.Value.MeasureString(text3).X * 0.5f, 3f);
        Utils.DrawBorderString(spriteBatch, text3, vector4, Color.White);
    }
References Terraria.GameContent.UI.Elements.UICharacterListItem._data, Terraria.GameContent.UI.Elements.UICharacterListItem._dividerTexture, Terraria.GameContent.UI.Elements.UICharacterListItem._playerPanel, Terraria.Main.creativeModeColor, Terraria.Player.difficulty, Terraria.Utils.DrawBorderString(), Terraria.GameContent.UI.Elements.UICharacterListItem.DrawPanel(), Terraria.Localization.GameCulture.FromCultureName(), Terraria.UI.UIElement.GetDimensions(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.IO.PlayerFileData.GetPlayTime(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.hcColor, Terraria.GameContent.TextureAssets.Heart, Terraria.Player.loadStatus, Terraria.GameContent.TextureAssets.Mana, Terraria.Main.mcColor, Terraria.GameContent.FontAssets.MouseText, Terraria.IO.FileData.Name, Terraria.IO.PlayerFileData.Player, Terraria.ID.StatusID.Search, Terraria.Player.statLifeMax2, Terraria.Player.statManaMax2, and Terraria.UI.UIElement.Width.