TModLoader: Terraria.ModLoader.IO.MultiDimArraySerializer.Deserialize
Deserialize() [3/3]
override Array Terraria.ModLoader.IO.MultiDimArraySerializer.Deserialize (TagCompound tag) inline
Definition at line 46 of file MultiDimArraySerializer.cs.
    {
        ArgumentNullException.ThrowIfNull(tag, "tag");
        return FromTagCompound(tag, ArrayType, (object e) => TagIO.Deserialize(ElementType, e));
    }
References Terraria.ModLoader.IO.MultiDimArraySerializer.ArrayType, Terraria.ModLoader.IO.TagIO.Deserialize(), Terraria.ModLoader.IO.MultiDimArraySerializer.ElementType, and Terraria.ModLoader.IO.MultiDimArraySerializer.FromTagCompound().
Referenced by Terraria.ModLoader.IO.MultiDimArraySerializer.DeserializeList().