TModLoader: Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.PopulateEntries
PopulateEntries()
void Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.PopulateEntries () inline
    {
        _entries.Clear();
        IOrderedEnumerable<ResourcePack> collection = from x in AssetInitializer.CreatePublishableResourcePacksList((IServiceProvider)((Game)Main.instance).Services).AllPacks
            where x.Branding == ResourcePack.BrandingType.None
            orderby x.IsCompressed
            select x;
        _entries.AddRange(collection);
        _entryList.Clear();
        int num = 0;
        foreach (ResourcePack entry in _entries)
        {
            _entryList.Add(new UIWorkshopPublishResourcePackListItem(this, entry, num++, !entry.IsCompressed));
        }
    }
References Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish._entries, Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish._entryList, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.IO.ResourcePackList.AllPacks, Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.Initializers.AssetInitializer.CreatePublishableResourcePacksList(), Terraria.Main.instance, and Terraria.IO.ResourcePack.IsCompressed.
Referenced by Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.OnActivate().