TModLoader: Terraria.Graphics.Renderers.ReturnGatePlayerRenderer.DrawReturnGateInWorld
DrawReturnGateInWorld()
void Terraria.Graphics.Renderers.ReturnGatePlayerRenderer.DrawReturnGateInWorld (Camera camera, Player player) inline private
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        Rectangle homeHitbox = Rectangle.Empty;
        if (!PotionOfReturnHelper.TryGetGateHitbox(player, out homeHitbox))
        {
            return;
        }
        int num = 0;
        AHoverInteractionChecker.HoverStatus hoverStatus = AHoverInteractionChecker.HoverStatus.NotSelectable;
        if (player == Main.LocalPlayer)
        {
            _interactionChecker.AttemptInteraction(player, homeHitbox);
        }
        if (Main.SmartInteractPotionOfReturn)
        {
            hoverStatus = AHoverInteractionChecker.HoverStatus.Selected;
        }
        num = (int)hoverStatus;
        if (!player.PotionOfReturnOriginalUsePosition.HasValue)
        {
            return;
        }
        SpriteBatch spriteBatch = camera.SpriteBatch;
        SamplerState sampler = camera.Sampler;
        spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend, sampler, DepthStencilState.None, camera.Rasterizer, (Effect)null, camera.GameViewMatrix.TransformationMatrix);
        float opacity = ((player.whoAmI == Main.myPlayer) ? 1f : 0.1f);
        Vector2 value = player.PotionOfReturnOriginalUsePosition.Value;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(0f, -21f);
        Vector2 worldPosition = value + vector;
        Vector2 worldPosition2 = ((Rectangle)(ref homeHitbox)).Center.ToVector2();
        PotionOfReturnGateHelper potionOfReturnGateHelper = new PotionOfReturnGateHelper(PotionOfReturnGateHelper.GateType.ExitPoint, worldPosition, opacity);
        PotionOfReturnGateHelper potionOfReturnGateHelper2 = new PotionOfReturnGateHelper(PotionOfReturnGateHelper.GateType.EntryPoint, worldPosition2, opacity);
        if (!Main.gamePaused)
        {
            potionOfReturnGateHelper.Update();
            potionOfReturnGateHelper2.Update();
        }
        _voidLensData.Clear();
        potionOfReturnGateHelper.DrawToDrawData(_voidLensData, 0);
        potionOfReturnGateHelper2.DrawToDrawData(_voidLensData, num);
        foreach (DrawData voidLensDatum in _voidLensData)
        {
            voidLensDatum.Draw(spriteBatch);
        }
        spriteBatch.End();
    }
References Terraria.Graphics.Renderers.ReturnGatePlayerRenderer._interactionChecker, Terraria.Graphics.Renderers.ReturnGatePlayerRenderer._voidLensData, Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.AttemptInteraction(), Terraria.Main.gamePaused, Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Player.PotionOfReturnOriginalUsePosition, Terraria.Main.SmartInteractPotionOfReturn, and Terraria.GameContent.ObjectInteractions.PotionOfReturnHelper.TryGetGateHitbox().
Referenced by Terraria.Graphics.Renderers.ReturnGatePlayerRenderer.DrawPlayer(), and Terraria.Graphics.Renderers.ReturnGatePlayerRenderer.DrawPlayers().