TModLoader: Terraria.ModLoader.Default.StartBag.RightClick
RightClick()
override void Terraria.ModLoader.Default.StartBag.RightClick (Player player) inline virtual
Allows you to make things happen when this item is right-clicked in the inventory.
Parameters
player The player.
Reimplemented from Terraria.ModLoader.ModItem.
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        IEntitySource itemSource = player.GetItemSource_OpenItem(base.Type);
        foreach (Item item in items)
        {
            int i = Item.NewItem(itemSource, player.getRect(), item.type, item.stack, noBroadcast: false, item.prefix);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, i, 1f);
            }
        }
    }
References Terraria.Player.GetItemSource_OpenItem(), Terraria.ModLoader.Default.StartBag.items, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Item.prefix, Terraria.NetMessage.SendData(), Terraria.Item.stack, and Terraria.Item.type.