TModLoader: Terraria.Graphics.Shaders.ScreenShaderData.Apply
Apply()
override void Terraria.Graphics.Shaders.ScreenShaderData.Apply () inline virtual
Reimplemented from Terraria.Graphics.Shaders.ShaderData.
Definition at line 90 of file ScreenShaderData.cs.
    {
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0113: Unknown result type (might be due to invalid IL or missing references)
        //IL_012e: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0130: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_0176: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_031e: Unknown result type (might be due to invalid IL or missing references)
        //IL_032b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)Main.offScreenRange, (float)Main.offScreenRange);
        Vector2 value = new Vector2((float)Main.screenWidth, (float)Main.screenHeight) / Main.GameViewMatrix.Zoom;
        Vector2 vector2 = new Vector2((float)Main.screenWidth, (float)Main.screenHeight) * 0.5f;
        Vector2 vector3 = Main.screenPosition + vector2 * (Vector2.One - Vector2.One / Main.GameViewMatrix.Zoom);
        base.Shader.Parameters["uColor"].SetValue(_uColor);
        base.Shader.Parameters["uOpacity"].SetValue(CombinedOpacity);
        base.Shader.Parameters["uSecondaryColor"].SetValue(_uSecondaryColor);
        base.Shader.Parameters["uTime"].SetValue(Main.GlobalTimeWrappedHourly);
        base.Shader.Parameters["uScreenResolution"].SetValue(value);
        base.Shader.Parameters["uScreenPosition"].SetValue(vector3 - vector);
        base.Shader.Parameters["uTargetPosition"].SetValue(_uTargetPosition - vector);
        base.Shader.Parameters["uImageOffset"].SetValue(_uImageOffset);
        base.Shader.Parameters["uIntensity"].SetValue(_uIntensity);
        base.Shader.Parameters["uProgress"].SetValue(_uProgress);
        base.Shader.Parameters["uDirection"].SetValue(_uDirection);
        base.Shader.Parameters["uZoom"].SetValue(Main.GameViewMatrix.Zoom);
        for (int i = 0; i < _uAssetImages.Length; i++)
        {
            Texture2D texture2D = _uCustomImages[i];
            if (_uAssetImages[i] != null && _uAssetImages[i].IsLoaded)
            {
                texture2D = _uAssetImages[i].Value;
            }
            if (texture2D != null)
            {
                Main.graphics.GraphicsDevice.Textures[i + 1] = (Texture)(object)texture2D;
                int width = texture2D.Width;
                int height = texture2D.Height;
                if (_samplerStates[i] != null)
                {
                    Main.graphics.GraphicsDevice.SamplerStates[i + 1] = _samplerStates[i];
                }
                else if (Utils.IsPowerOfTwo(width) && Utils.IsPowerOfTwo(height))
                {
                    Main.graphics.GraphicsDevice.SamplerStates[i + 1] = SamplerState.LinearWrap;
                }
                else
                {
                    Main.graphics.GraphicsDevice.SamplerStates[i + 1] = SamplerState.AnisotropicClamp;
                }
                base.Shader.Parameters["uImageSize" + (i + 1)].SetValue(new Vector2((float)width, (float)height) * _imageScales[i]);
            }
        }
        base.Apply();
    }
References Terraria.Graphics.Shaders.ScreenShaderData._imageScales, Terraria.Graphics.Shaders.ScreenShaderData._samplerStates, Terraria.Graphics.Shaders.ScreenShaderData._uAssetImages, Terraria.Graphics.Shaders.ScreenShaderData._uColor, Terraria.Graphics.Shaders.ScreenShaderData._uCustomImages, Terraria.Graphics.Shaders.ScreenShaderData._uDirection, Terraria.Graphics.Shaders.ScreenShaderData._uImageOffset, Terraria.Graphics.Shaders.ScreenShaderData._uIntensity, Terraria.Graphics.Shaders.ScreenShaderData._uProgress, Terraria.Graphics.Shaders.ScreenShaderData._uSecondaryColor, Terraria.Graphics.Shaders.ScreenShaderData._uTargetPosition, Terraria.Graphics.Shaders.ScreenShaderData.CombinedOpacity, Terraria.Main.GameViewMatrix, Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.graphics, Terraria.Utils.IsPowerOfTwo(), Terraria.Main.offScreenRange, Terraria.Main.screenHeight, and Terraria.Main.screenWidth.
Referenced by Terraria.Graphics.Effects.Filter.Apply(), and Terraria.Graphics.Effects.SimpleOverlay.Draw().