TModLoader: Terraria.ModLoader.NPCShop.FillShop
FillShop() [2/2]
override void Terraria.ModLoader.NPCShop.FillShop (Item[] items, NPC npc, out bool overflow) inline
Fills a shop array with the contents of this shop, evaluating conditions and running callbacks.
Does not fill the entire array if there are insufficient entries.
The last slot will be kept empty (null) if P:Terraria.ModLoader.NPCShop.FillLastSlot is false.
Parameters
items Array to be filled.
npc The NPC the player is talking to, for M:Terraria.ModLoader.NPCShop.Entry.OnShopOpen(Terraria.Item,Terraria.NPC) calls.
overflow True if some items were unable to fit in the provided array.
Definition at line 254 of file NPCShop.cs.
    {
        overflow = false;
        int limit = (FillLastSlot ? items.Length : (items.Length - 1));
        int i = 0;
        foreach (Entry entry in _entries)
        {
            if (entry.Disabled)
            {
                continue;
            }
            bool conditionsMet = entry.ConditionsMet();
            if (conditionsMet || entry.SlotReserved)
            {
                if (i == limit)
                {
                    overflow = true;
                    break;
                }
                Item item;
                if (conditionsMet)
                {
                    item = entry.Item.Clone();
                    entry.OnShopOpen(item, npc);
                }
                else
                {
                    item = new Item(0);
                }
                items[i++] = item;
            }
        }
    }
References Terraria.ModLoader.NPCShop._entries, Terraria.Item.Clone(), Terraria.ModLoader.NPCShop.Entry.ConditionsMet(), Terraria.ModLoader.NPCShop.Entry.Disabled, Terraria.ModLoader.NPCShop.FillLastSlot, Terraria.ModLoader.NPCShop.Entry.Item, Terraria.ModLoader.NPCShop.Entry.OnShopOpen(), and Terraria.ModLoader.NPCShop.Entry.SlotReserved.