TModLoader: Terraria.ModLoader.Config.ConfigManager.GetLocalizedHeader
GetLocalizedHeader()
static ? HeaderAttribute Terraria.ModLoader.Config.ConfigManager.GetLocalizedHeader (MemberInfo memberInfo) inline static package
Definition at line 567 of file ConfigManager.cs.
    {
        HeaderAttribute header = memberInfo.GetCustomAttribute<HeaderAttribute>();
        if (header == null)
        {
            return null;
        }
        if (header.malformed)
        {
            throw new ValueNotTranslationKeyException($"{"HeaderAttribute"} only accepts localization keys or identifiers for the 'identifierOrKey' parameter. Neither can have spaces.\nThe member '{memberInfo.Name}' found in the '{memberInfo.DeclaringType}' class caused this exception.\nClick Open Web Help for more information.");
        }
        if (header.IsIdentifier)
        {
            header.key = GetDefaultLocalizationKey(memberInfo.DeclaringType, "Headers." + header.identifier);
        }
        return header;
    }
References Terraria.ModLoader.Config.ConfigManager.GetDefaultLocalizationKey(), Terraria.ModLoader.Config.HeaderAttribute.identifier, Terraria.ModLoader.Config.HeaderAttribute.IsIdentifier, and Terraria.ModLoader.Config.HeaderAttribute.malformed.
Referenced by Terraria.ModLoader.Config.UI.UIModConfig.HandleHeader(), and Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForMembers().