TModLoader: Terraria.ModLoader.Config.ConfigManager.Load
Load()
static void Terraria.ModLoader.Config.ConfigManager.Load (ModConfig config) inline static package
    {
        ModConfig config2 = config;
        string filename = config2.Mod.Name + "_" + config2.Name + ".json";
        string path = Path.Combine(ModConfigPath, filename);
        if (config2.Mode == ConfigScope.ServerSide && ModNet.NetReloadActive)
        {
            JsonConvert.PopulateObject(ModNet.pendingConfigs.Single((ModNet.NetConfig x) => x.modname == config2.Mod.Name && x.configname == config2.Name).json, (object)config2, serializerSettingsCompact);
            return;
        }
        bool jsonFileExists = File.Exists(path);
        string json = (jsonFileExists ? File.ReadAllText(path) : "{}");
        try
        {
            JsonConvert.PopulateObject(json, (object)config2, serializerSettings);
        }
        catch (Exception ex) when (jsonFileExists && (ex is JsonReaderException || ex is JsonSerializationException))
        {
            Logging.tML.Warn((object)$"Then config file {config2.Name} from the mod {config2.Mod.Name} located at {path} failed to load. The file was likely corrupted somehow, so the defaults will be loaded and the file deleted.");
            File.Delete(path);
            JsonConvert.PopulateObject("{}", (object)config2, serializerSettings);
        }
    }
References Terraria.ModLoader.Config.ConfigManager.ModConfigPath, Terraria.ModLoader.ModNet.NetReloadActive, Terraria.ModLoader.ModNet.pendingConfigs, Terraria.ModLoader.Config.ConfigManager.serializerSettings, Terraria.ModLoader.Config.ConfigManager.serializerSettingsCompact, and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.ModLoader.Config.ConfigManager.Add(), Terraria.ModLoader.Config.ConfigManager.LoadAll(), and Terraria.ModLoader.Config.UI.UIModConfig.SaveConfig().