TModLoader: Terraria.ModLoader.Config.ConfigManager.GetLocalizedText< T, TArgs >
GetLocalizedText< T, TArgs >()
static ? string Terraria.ModLoader.Config.ConfigManager.GetLocalizedText< T, TArgs > (PropertyFieldWrapper memberInfo, string dataName) inline static private
Type Constraints
T : ConfigKeyAttribute
TArgs : ConfigArgsAttribute
Definition at line 543 of file ConfigManager.cs.
                                                                                                                : ConfigKeyAttribute where TArgs : ConfigArgsAttribute
    {
        string memberKey = GetConfigKey<T>(memberInfo.MemberInfo, dataName);
        if (!Language.Exists(memberKey))
        {
            return null;
        }
        LocalizedText memberLocalization = Language.GetText(memberKey);
        if (memberLocalization.Value != "")
        {
            return FormatTextAttribute(memberLocalization, memberInfo.MemberInfo.GetCustomAttribute<TArgs>()?.args);
        }
        if (memberInfo.Type.IsPrimitive)
        {
            return null;
        }
        string typeKey = GetConfigKey<T>(memberInfo.Type, dataName);
        if (!Language.Exists(typeKey))
        {
            return null;
        }
        return FormatTextAttribute(Language.GetText(typeKey), memberInfo.Type.GetCustomAttribute<TArgs>()?.args);
    }
References Terraria.Localization.Language.Exists(), Terraria.ModLoader.Config.ConfigManager.FormatTextAttribute(), Terraria.ModLoader.Config.ConfigManager.GetConfigKey< T >(), and Terraria.Localization.Language.GetText().