TModLoader: Terraria.ModLoader.Config.ConfigManager.HandleInGameChangeConfigPacket
HandleInGameChangeConfigPacket()
static void Terraria.ModLoader.Config.ConfigManager.HandleInGameChangeConfigPacket (BinaryReader reader, int whoAmI) inline static package
    {
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode == 1)
        {
            bool num = reader.ReadBoolean();
            NetworkText message = NetworkText.Deserialize(reader);
            if (num)
            {
                string modname = reader.ReadString();
                string configname = reader.ReadString();
                string text = reader.ReadString();
                ModConfig activeConfig = GetConfig(ModLoader.GetMod(modname), configname);
                JsonConvert.PopulateObject(text, (object)activeConfig, serializerSettingsCompact);
                activeConfig.OnChanged();
                Main.NewText(Language.GetTextValue("tModLoader.ModConfigSharedConfigChanged", message, modname, configname));
                if (Main.InGameUI.CurrentState == Interface.modConfig)
                {
                    Main.InGameUI.SetState(Interface.modConfig);
                    Interface.modConfig.SetMessage(Language.GetTextValue("tModLoader.ModConfigServerResponse", message), Color.Green);
                }
            }
            else
            {
                Main.NewText(Language.GetTextValue("tModLoader.ModConfigServerRejectedChanges", message));
                if (Main.InGameUI.CurrentState == Interface.modConfig)
                {
                    Interface.modConfig.SetMessage(Language.GetTextValue("tModLoader.ModConfigServerRejectedChanges", message), Color.Red);
                }
            }
            return;
        }
        string modname2 = reader.ReadString();
        string configname2 = reader.ReadString();
        string json = reader.ReadString();
        Mod mod = ModLoader.GetMod(modname2);
        ModConfig config = GetConfig(mod, configname2);
        ModConfig loadTimeConfig = GetLoadTimeConfig(mod, configname2);
        ModConfig pendingConfig = GeneratePopulatedClone(config);
        JsonConvert.PopulateObject(json, (object)pendingConfig, serializerSettingsCompact);
        bool success = true;
        NetworkText message2 = NetworkText.FromKey("tModLoader.ModConfigAccepted");
        if (loadTimeConfig.NeedsReload(pendingConfig))
        {
            success = false;
            message2 = NetworkText.FromKey("tModLoader.ModConfigCantSaveBecauseChangesWouldRequireAReload");
        }
        string stringMessage = "";
        success &= config.AcceptClientChanges(pendingConfig, whoAmI, ref message2);
        success &= config.AcceptClientChanges(pendingConfig, whoAmI, ref stringMessage);
        if (!string.IsNullOrEmpty(stringMessage))
        {
            message2 = NetworkText.FromLiteral(stringMessage);
        }
        if (success)
        {
            Save(pendingConfig);
            JsonConvert.PopulateObject(json, (object)config, serializerSettingsCompact);
            config.OnChanged();
            ModPacket p = new ModPacket(249);
            p.Write(value: true);
            message2.Serialize(p);
            p.Write(modname2);
            p.Write(configname2);
            p.Write(json);
            p.Send();
        }
        else
        {
            ModPacket p2 = new ModPacket(249);
            p2.Write(value: false);
            message2.Serialize(p2);
            p2.Send(whoAmI);
        }
    }
References Terraria.Localization.NetworkText.Deserialize(), Terraria.Localization.NetworkText.FromKey(), Terraria.Localization.NetworkText.FromLiteral(), Terraria.ModLoader.Config.ConfigManager.GeneratePopulatedClone(), Terraria.ModLoader.Config.ConfigManager.GetConfig(), Terraria.ModLoader.Config.ConfigManager.GetLoadTimeConfig(), Terraria.ModLoader.ModLoader.GetMod(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.InGameUI, Terraria.ModLoader.UI.Interface.modConfig, Terraria.Main.netMode, Terraria.Main.NewText(), Terraria.ModLoader.Config.ConfigManager.Save(), and Terraria.ModLoader.Config.ConfigManager.serializerSettingsCompact.
Referenced by Terraria.MessageBuffer.GetData().