TModLoader: Terraria.ModLoader.Config.ConfigManager.FormatTextAttribute
FormatTextAttribute()
static string Terraria.ModLoader.Config.ConfigManager.FormatTextAttribute (LocalizedText localizedText, object?[] args) inline static package
Definition at line 474 of file ConfigManager.cs.
    {
        if (args == null)
        {
            return localizedText.Value;
        }
        for (int i = 0; i < args.Length; i++)
        {
            if (args[i] is string s && s.StartsWith("$"))
            {
                args[i] = Language.GetTextValue(FindKeyInScope(s.Substring(1), localizedText.Key));
            }
        }
        return localizedText.Format(args);
        static string FindKeyInScope(string key, string scope)
        {
            if (LanguageManager.Instance.Exists(key))
            {
                return key;
            }
            string[] splitKey = scope.Split(".");
            for (int j = splitKey.Length - 1; j >= 0; j--)
            {
                string combinedKey = string.Join(".", splitKey.Take(j + 1)) + "." + key;
                if (LanguageManager.Instance.Exists(combinedKey))
                {
                    return combinedKey;
                }
            }
            return key;
        }
    }
References Terraria.Localization.LanguageManager.Exists(), Terraria.Localization.Language.GetTextValue(), and Terraria.Localization.LanguageManager.Instance.
Referenced by Terraria.ModLoader.Config.ConfigManager.GetLocalizedText< T, TArgs >().