TModLoader: Terraria.ModLoader.Config.ConfigManager.GetLoadTimeConfig
GetLoadTimeConfig()
static ModConfig Terraria.ModLoader.Config.ConfigManager.GetLoadTimeConfig (Mod mod, string config) inline static package
Definition at line 299 of file ConfigManager.cs.
    {
        string config2 = config;
        if (loadTimeConfigs.TryGetValue(mod, out List<ModConfig> configs))
        {
            return configs.Single((ModConfig x) => x.Name == config2);
        }
        throw new MissingResourceException("Missing config named " + config2 + " in mod " + mod.Name);
    }
References Terraria.ModLoader.Config.ConfigManager.loadTimeConfigs, Terraria.ModLoader.Config.ModConfig.Name, and Terraria.ModLoader.Mod.Name.
Referenced by Terraria.ModLoader.Config.ConfigManager.HandleInGameChangeConfigPacket(), Terraria.ModLoader.Config.UI.ConfigElement< T >.OnBind(), and Terraria.ModLoader.Config.UI.UIModConfig.SaveConfig().