TModLoader: Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForMembers
RegisterLocalizationKeysForMembers()
static void Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForMembers (Type type) inline static private
Definition at line 117 of file ConfigManager.cs.
    {
        AssemblyManager.GetAssemblyOwner(type.Assembly, out var _);
        foreach (PropertyFieldWrapper variable in GetFieldsAndProperties(type))
        {
            LabelAttribute labelObsolete = GetLegacyLabelAttribute(variable.MemberInfo);
            TooltipAttribute tooltipObsolete = GetLegacyTooltipAttribute(variable.MemberInfo);
            if (Attribute.IsDefined(variable.MemberInfo, typeof(JsonIgnoreAttribute)) && labelObsolete == null && !Attribute.IsDefined(variable.MemberInfo, typeof(ShowDespiteJsonIgnoreAttribute)))
            {
                continue;
            }
            RegisterLocalizationKeysForMemberType(variable.Type, type.Assembly);
            HeaderAttribute header = GetLocalizedHeader(variable.MemberInfo);
            if (header != null)
            {
                string identifier = (header.IsIdentifier ? header.identifier : variable.Name);
                Language.GetOrRegister(header.key, () => Regex.Replace(identifier, "([A-Z])", " $1").Trim() + " Header");
            }
            Language.GetOrRegister(GetConfigKey<LabelKeyAttribute>(variable.MemberInfo, "Label"), () => labelObsolete?.LocalizationEntry ?? Regex.Replace(variable.Name, "([A-Z])", " $1").Trim());
            Language.GetOrRegister(GetConfigKey<TooltipKeyAttribute>(variable.MemberInfo, "Tooltip"), () => tooltipObsolete?.LocalizationEntry ?? "");
        }
    }
References Terraria.ModLoader.Core.AssemblyManager.GetAssemblyOwner(), Terraria.ModLoader.Config.ConfigManager.GetFieldsAndProperties(), Terraria.ModLoader.Config.ConfigManager.GetLegacyLabelAttribute(), Terraria.ModLoader.Config.ConfigManager.GetLegacyTooltipAttribute(), Terraria.ModLoader.Config.ConfigManager.GetLocalizedHeader(), Terraria.Localization.Language.GetOrRegister(), Terraria.ModLoader.Config.HeaderAttribute.key, and Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForMemberType().
Referenced by Terraria.ModLoader.Config.ConfigManager.FinishSetup(), and Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForMemberType().