TModLoader: Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForMemberType
RegisterLocalizationKeysForMemberType()
static void Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForMemberType (Type type, Assembly owningAssembly) inline static private
    {
        if (type.IsGenericType)
        {
            Type[] genericArguments = type.GetGenericArguments();
            for (int i = 0; i < genericArguments.Length; i++)
            {
                RegisterLocalizationKeysForMemberType(genericArguments[i], owningAssembly);
            }
        }
        if ((type.IsClass || type.IsEnum) && type.Assembly == owningAssembly && typesWithLocalizationRegistered.Add(type))
        {
            Language.GetOrRegister(GetConfigKey<TooltipKeyAttribute>(type, "Tooltip"), () => "");
            if (type.IsClass)
            {
                RegisterLocalizationKeysForMembers(type);
            }
            else
            {
                RegisterLocalizationKeysForEnumMembers(type);
            }
        }
    }
References Terraria.Localization.Language.GetOrRegister(), Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForEnumMembers(), Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForMembers(), Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForMemberType(), and Terraria.ModLoader.Config.ConfigManager.typesWithLocalizationRegistered.
Referenced by Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForMembers(), and Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForMemberType().