TModLoader: Terraria.UI.ChestUI.DrawName
DrawName()
static void Terraria.UI.ChestUI.DrawName (SpriteBatch spritebatch) inline static private
Definition at line 97 of file ChestUI.cs.
    {
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_032e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_0339: Unknown result type (might be due to invalid IL or missing references)
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[Main.myPlayer];
        string text = string.Empty;
        if (Main.editChest)
        {
            text = Main.npcChatText;
            Main.instance.textBlinkerCount++;
            if (Main.instance.textBlinkerCount >= 20)
            {
                if (Main.instance.textBlinkerState == 0)
                {
                    Main.instance.textBlinkerState = 1;
                }
                else
                {
                    Main.instance.textBlinkerState = 0;
                }
                Main.instance.textBlinkerCount = 0;
            }
            if (Main.instance.textBlinkerState == 1)
            {
                text += "|";
            }
            Main.instance.DrawWindowsIMEPanel(new Vector2(120f, 518f));
        }
        else if (player.chest > -1)
        {
            if (Main.chest[player.chest] == null)
            {
                Main.chest[player.chest] = new Chest();
            }
            Chest chest = Main.chest[player.chest];
            if (chest.name != "")
            {
                text = chest.name;
            }
            else
            {
                Tile tile = Main.tile[player.chestX, player.chestY];
                if (tile.type == 21)
                {
                    text = Lang.chestType[tile.frameX / 36].Value;
                }
                else if (tile.type == 467 && tile.frameX / 36 == 4)
                {
                    text = Lang.GetItemNameValue(3988);
                }
                else if (tile.type == 467)
                {
                    text = Lang.chestType2[tile.frameX / 36].Value;
                }
                else if (tile.type == 88)
                {
                    text = Lang.dresserType[tile.frameX / 54].Value;
                }
                else if (TileID.Sets.BasicChest[Main.tile[player.chestX, player.chestY].type] || TileID.Sets.BasicDresser[Main.tile[player.chestX, player.chestY].type])
                {
                    text = TileLoader.DefaultContainerName(tile.type, tile.TileFrameX, tile.TileFrameY);
                }
            }
        }
        else if (player.chest == -2)
        {
            text = Lang.inter[32].Value;
        }
        else if (player.chest == -3)
        {
            text = Lang.inter[33].Value;
        }
        else if (player.chest == -4)
        {
            text = Lang.GetItemNameValue(3813);
        }
        else if (player.chest == -5)
        {
            text = Lang.GetItemNameValue(4076);
        }
        Color color = default(Color);
        ((Color)(ref color))._002Ector((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor);
        color = Color.White * (1f - (255f - (float)(int)Main.mouseTextColor) / 255f * 0.5f);
        ((Color)(ref color)).A = byte.MaxValue;
        Utils.WordwrapString(text, FontAssets.MouseText.Value, 200, 1, out var lineAmount);
        lineAmount++;
        for (int i = 0; i < lineAmount; i++)
        {
            ChatManager.DrawColorCodedStringWithShadow(spritebatch, FontAssets.MouseText.Value, text, new Vector2(504f, (float)(Main.instance.invBottom + i * 26)), color, 0f, Vector2.Zero, Vector2.One, -1f, 1.5f);
        }
    }
References Terraria.ID.TileID.Sets.BasicChest, Terraria.ID.TileID.Sets.BasicDresser, Terraria.Main.chest, Terraria.Player.chest, Terraria.Lang.chestType, Terraria.Lang.chestType2, Terraria.Player.chestX, Terraria.Player.chestY, Terraria.ModLoader.TileLoader.DefaultContainerName(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Main.DrawWindowsIMEPanel(), Terraria.Lang.dresserType, Terraria.Main.editChest, Terraria.Tile.frameX, Terraria.Lang.GetItemNameValue(), Terraria.Main.instance, Terraria.Lang.inter, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.myPlayer, Terraria.Chest.name, Terraria.Main.npcChatText, Terraria.Main.player, Terraria.Main.textBlinkerCount, Terraria.Main.textBlinkerState, Terraria.Main.tile, Terraria.Tile.TileFrameX, Terraria.Tile.TileFrameY, Terraria.Tile.type, Terraria.Localization.LocalizedText.Value, and Terraria.Utils.WordwrapString().
Referenced by Terraria.UI.ChestUI.Draw().