TModLoader: Terraria.UI.ChestUI.QuickStack
QuickStack()
static void Terraria.UI.ChestUI.QuickStack (ContainerTransferContext context, bool voidStack = false) inline static
    {
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_035a: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0555: Unknown result type (might be due to invalid IL or missing references)
        //IL_0556: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[Main.myPlayer];
        Item[] array = player.inventory;
        if (voidStack)
        {
            array = player.bank4.item;
        }
        Vector2 center = player.Center;
        Vector2 containerWorldPosition = context.GetContainerWorldPosition();
        bool canVisualizeTransfers = context.CanVisualizeTransfers;
        if (!voidStack && player.chest == -5)
        {
            long coinsMoved = MoveCoins(array, player.bank4.item, context);
            if (canVisualizeTransfers)
            {
                Chest.VisualizeChestTransfer_CoinsBatch(center, containerWorldPosition, coinsMoved);
            }
        }
        else if (player.chest == -4)
        {
            long coinsMoved2 = MoveCoins(array, player.bank3.item, context);
            if (canVisualizeTransfers)
            {
                Chest.VisualizeChestTransfer_CoinsBatch(center, containerWorldPosition, coinsMoved2);
            }
        }
        else if (player.chest == -3)
        {
            long coinsMoved3 = MoveCoins(array, player.bank2.item, context);
            if (canVisualizeTransfers)
            {
                Chest.VisualizeChestTransfer_CoinsBatch(center, containerWorldPosition, coinsMoved3);
            }
        }
        else if (player.chest == -2)
        {
            long coinsMoved4 = MoveCoins(array, player.bank.item, context);
            if (canVisualizeTransfers)
            {
                Chest.VisualizeChestTransfer_CoinsBatch(center, containerWorldPosition, coinsMoved4);
            }
        }
        Item[] item = player.bank.item;
        if (player.chest > -1)
        {
            item = Main.chest[player.chest].item;
        }
        else if (player.chest == -2)
        {
            item = player.bank.item;
        }
        else if (player.chest == -3)
        {
            item = player.bank2.item;
        }
        else if (player.chest == -4)
        {
            item = player.bank3.item;
        }
        else if (!voidStack && player.chest == -5)
        {
            item = player.bank4.item;
        }
        List<int> list = new List<int>();
        List<int> list2 = new List<int>();
        List<int> list3 = new List<int>();
        Dictionary<int, int> dictionary = new Dictionary<int, int>();
        List<int> list4 = new List<int>();
        bool[] array2 = new bool[item.Length];
        for (int i = 0; i < 40; i++)
        {
            if (item[i].type > 0 && item[i].stack > 0 && (item[i].type < 71 || item[i].type > 74))
            {
                list2.Add(i);
                list.Add(item[i].netID);
            }
            if (item[i].type == 0 || item[i].stack <= 0)
            {
                list3.Add(i);
            }
        }
        int num = 50;
        int num2 = 10;
        if (player.chest <= -2)
        {
            num += 4;
        }
        if (voidStack)
        {
            num2 = 0;
            num = 40;
        }
        for (int j = num2; j < num; j++)
        {
            if (list.Contains(array[j].netID) && !array[j].favorited)
            {
                dictionary.Add(j, array[j].netID);
            }
        }
        for (int k = 0; k < list2.Count; k++)
        {
            int num3 = list2[k];
            int netID = item[num3].netID;
            foreach (KeyValuePair<int, int> item2 in dictionary)
            {
                if (item2.Value == netID && array[item2.Key].netID == netID)
                {
                    int num4 = array[item2.Key].stack;
                    int num5 = item[num3].maxStack - item[num3].stack;
                    if (num5 == 0)
                    {
                        break;
                    }
                    if (num4 > num5)
                    {
                        num4 = num5;
                    }
                    SoundEngine.PlaySound(7);
                    ItemLoader.TryStackItems(item[num3], array[item2.Key], out num4);
                    if (canVisualizeTransfers && num4 > 0)
                    {
                        Chest.VisualizeChestTransfer(center, containerWorldPosition, item[num3], num4);
                    }
                    array2[num3] = true;
                }
            }
        }
        foreach (KeyValuePair<int, int> item3 in dictionary)
        {
            if (array[item3.Key].stack == 0)
            {
                list4.Add(item3.Key);
            }
        }
        foreach (int item4 in list4)
        {
            dictionary.Remove(item4);
        }
        for (int l = 0; l < list3.Count; l++)
        {
            int num6 = list3[l];
            bool flag = true;
            int num7 = item[num6].netID;
            if (num7 >= 71 && num7 <= 74)
            {
                continue;
            }
            foreach (KeyValuePair<int, int> item5 in dictionary)
            {
                if ((item5.Value != num7 || array[item5.Key].netID != num7) && (!flag || array[item5.Key].stack <= 0))
                {
                    continue;
                }
                SoundEngine.PlaySound(7);
                if (flag)
                {
                    num7 = item5.Value;
                    item[num6] = array[item5.Key];
                    array[item5.Key] = new Item();
                    if (canVisualizeTransfers)
                    {
                        Chest.VisualizeChestTransfer(center, containerWorldPosition, item[num6], item[num6].stack);
                    }
                }
                else
                {
                    int num8 = array[item5.Key].stack;
                    int num9 = item[num6].maxStack - item[num6].stack;
                    if (num9 == 0)
                    {
                        break;
                    }
                    if (num8 > num9)
                    {
                        num8 = num9;
                    }
                    ItemLoader.TryStackItems(item[num6], array[item5.Key], out num8);
                    if (canVisualizeTransfers && num8 > 0)
                    {
                        Chest.VisualizeChestTransfer(center, containerWorldPosition, item[num6], num8);
                    }
                    if (array[item5.Key].stack == 0)
                    {
                        array[item5.Key] = new Item();
                    }
                }
                array2[num6] = true;
                flag = false;
            }
        }
        if (Main.netMode == 1 && player.chest >= 0)
        {
            for (int m = 0; m < array2.Length; m++)
            {
                NetMessage.SendData(32, -1, -1, null, player.chest, m);
            }
        }
        list.Clear();
        list2.Clear();
        list3.Clear();
        dictionary.Clear();
        list4.Clear();
    }
References Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.DataStructures.ContainerTransferContext.CanVisualizeTransfers, Terraria.Entity.Center, Terraria.Main.chest, Terraria.Player.chest, Terraria.Item.favorited, Terraria.DataStructures.ContainerTransferContext.GetContainerWorldPosition(), Terraria.Player.inventory, Terraria.Chest.item, Terraria.Item.maxStack, Terraria.UI.ChestUI.MoveCoins(), Terraria.Main.myPlayer, Terraria.Item.netID, Terraria.Main.netMode, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), Terraria.Item.stack, Terraria.ModLoader.ItemLoader.TryStackItems(), Terraria.Chest.VisualizeChestTransfer(), and Terraria.Chest.VisualizeChestTransfer_CoinsBatch().
Referenced by Terraria.UI.ChestUI.DrawButton(), and Terraria.Player.QuickStackAllChests().