TModLoader: Terraria.UI.ChestUI.LootAll
LootAll()
static void Terraria.UI.ChestUI.LootAll () inline static
    {
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0246: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        GetItemSettings lootAllSettings = GetItemSettings.LootAllSettings;
        Player player = Main.player[Main.myPlayer];
        if (player.chest > -1)
        {
            GetItemSettings lootAllSettingsRegularChest = GetItemSettings.LootAllSettingsRegularChest;
            Chest chest = Main.chest[player.chest];
            for (int i = 0; i < 40; i++)
            {
                if (chest.item[i].type > 0)
                {
                    chest.item[i].position = player.Center;
                    chest.item[i] = player.GetItem(Main.myPlayer, chest.item[i], lootAllSettingsRegularChest);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(32, -1, -1, null, player.chest, i);
                    }
                }
            }
            return;
        }
        if (player.chest == -3)
        {
            for (int j = 0; j < 40; j++)
            {
                if (player.bank2.item[j].type > 0)
                {
                    player.bank2.item[j].position = player.Center;
                    player.bank2.item[j] = player.GetItem(Main.myPlayer, player.bank2.item[j], lootAllSettings);
                }
            }
            return;
        }
        if (player.chest == -4)
        {
            for (int k = 0; k < 40; k++)
            {
                if (player.bank3.item[k].type > 0)
                {
                    player.bank3.item[k].position = player.Center;
                    player.bank3.item[k] = player.GetItem(Main.myPlayer, player.bank3.item[k], lootAllSettings);
                }
            }
            return;
        }
        if (player.chest == -5)
        {
            for (int l = 0; l < 40; l++)
            {
                if (player.bank4.item[l].type > 0 && !player.bank4.item[l].favorited)
                {
                    player.bank4.item[l].position = player.Center;
                    player.bank4.item[l] = player.GetItem(Main.myPlayer, player.bank4.item[l], lootAllSettings);
                }
            }
            return;
        }
        for (int m = 0; m < 40; m++)
        {
            if (player.bank.item[m].type > 0)
            {
                player.bank.item[m].position = player.Center;
                player.bank.item[m] = player.GetItem(Main.myPlayer, player.bank.item[m], lootAllSettings);
            }
        }
    }
References Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Entity.Center, Terraria.Main.chest, Terraria.Player.chest, Terraria.Item.favorited, Terraria.Player.GetItem(), Terraria.Chest.item, Terraria.GetItemSettings.LootAllSettings, Terraria.GetItemSettings.LootAllSettingsRegularChest, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.Entity.position, Terraria.NetMessage.SendData(), and Terraria.Item.type.
Referenced by Terraria.UI.ChestUI.DrawButton().