TModLoader: Terraria.UI.ChestUI.TryPlacingInChest
TryPlacingInChest()
static bool Terraria.UI.ChestUI.TryPlacingInChest (Item I, bool justCheck, int itemSlotContext) inline static
Definition at line 1317 of file ChestUI.cs.
    {
        GetContainerUsageInfo(out var sync, out var chestinv);
        if (IsBlockedFromTransferIntoChest(I, chestinv))
        {
            return false;
        }
        Player player = Main.player[Main.myPlayer];
        bool flag = false;
        if (I.maxStack > 1)
        {
            for (int i = 0; i < 40; i++)
            {
                if (chestinv[i].stack >= chestinv[i].maxStack || !I.IsTheSameAs(chestinv[i]) || !ItemLoader.CanStack(chestinv[i], I))
                {
                    continue;
                }
                int num = I.stack;
                if (I.stack + chestinv[i].stack > chestinv[i].maxStack)
                {
                    num = chestinv[i].maxStack - chestinv[i].stack;
                }
                if (justCheck)
                {
                    flag = flag || num > 0;
                    break;
                }
                ItemLoader.StackItems(chestinv[i], I, out var _);
                SoundEngine.PlaySound(7);
                if (I.stack <= 0)
                {
                    I.SetDefaults();
                    if (sync)
                    {
                        NetMessage.SendData(32, -1, -1, null, player.chest, i);
                    }
                    break;
                }
                if (chestinv[i].type == 0)
                {
                    chestinv[i] = I.Clone();
                    I.SetDefaults();
                }
                if (sync)
                {
                    NetMessage.SendData(32, -1, -1, null, player.chest, i);
                }
            }
        }
        if (I.stack > 0)
        {
            for (int j = 0; j < 40; j++)
            {
                if (chestinv[j].stack != 0)
                {
                    continue;
                }
                if (justCheck)
                {
                    flag = true;
                    break;
                }
                SoundEngine.PlaySound(7);
                chestinv[j] = I.Clone();
                I.SetDefaults();
                ItemSlot.AnnounceTransfer(new ItemSlot.ItemTransferInfo(chestinv[j], 0, 3));
                if (sync)
                {
                    NetMessage.SendData(32, -1, -1, null, player.chest, j);
                }
                break;
            }
        }
        return flag;
    }
References Terraria.UI.ItemSlot.AnnounceTransfer(), Terraria.ModLoader.ItemLoader.CanStack(), Terraria.Player.chest, Terraria.UI.ChestUI.GetContainerUsageInfo(), Terraria.UI.ChestUI.IsBlockedFromTransferIntoChest(), Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), and Terraria.ModLoader.ItemLoader.StackItems().
Referenced by Terraria.UI.ItemSlot.GetOverrideInstructions(), Terraria.UI.ItemSlot.OverrideHover(), and Terraria.UI.ItemSlot.OverrideLeftClick().