TModLoader: Terraria.Player.Hooks.EnterWorld
EnterWorld()
static void Terraria.Player.Hooks.EnterWorld (int playerIndex) inline static
        {
            Logging.Terraria.InfoFormat("Entering world with player: {0}, IsCloud={1}, Width: {2}, Height: {3}, Evil: {4}, GameMode: {5}", new object[6]
            {
                Main.ActivePlayerFileData.Name,
                Main.ActivePlayerFileData.IsCloudSave,
                Main.maxTilesX,
                Main.maxTilesY,
                WorldGen.crimson.ToInt(),
                Main.GameMode
            });
            Interface.ResetData();
            if (Hooks.OnEnterWorld != null)
            {
                Hooks.OnEnterWorld(Main.player[playerIndex]);
            }
            PlayerLoader.OnEnterWorld(playerIndex);
            if (playerIndex == Main.myPlayer)
            {
                Main.ToggleGameplayUpdates(state: true);
                SteamedWraps.BeginPlaytimeTracking();
            }
        }
References Terraria.Main.ActivePlayerFileData, Terraria.Social.Steam.SteamedWraps.BeginPlaytimeTracking(), Terraria.WorldGen.crimson, Terraria.Main.GameMode, Terraria.IO.FileData.IsCloudSave, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.myPlayer, Terraria.IO.FileData.Name, Terraria.ModLoader.PlayerLoader.OnEnterWorld(), Terraria.Player.Hooks.OnEnterWorld, Terraria.Main.player, Terraria.ModLoader.UI.Interface.ResetData(), Terraria.ModLoader.Logging.Terraria, and Terraria.Main.ToggleGameplayUpdates().
Referenced by Terraria.Player.Spawn().