TModLoader: Terraria.Projectile.AI_145_BookStaffStorm
AI_145_BookStaffStorm()
void Terraria.Projectile.AI_145_BookStaffStorm () inline private
    {
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_039d: Unknown result type (might be due to invalid IL or missing references)
        //IL_039f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03be: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03db: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_041d: Unknown result type (might be due to invalid IL or missing references)
        //IL_052c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0540: Unknown result type (might be due to invalid IL or missing references)
        //IL_0546: Unknown result type (might be due to invalid IL or missing references)
        //IL_054b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0550: Unknown result type (might be due to invalid IL or missing references)
        //IL_057c: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_060a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0610: Unknown result type (might be due to invalid IL or missing references)
        //IL_0615: Unknown result type (might be due to invalid IL or missing references)
        //IL_061a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0646: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f5: Unknown result type (might be due to invalid IL or missing references)
        float num = 300f;
        if (soundDelay == 0)
        {
            soundDelay = -1;
            localAI[1] = SoundEngine.PlayTrackedSound(in SoundID.DD2_BookStaffTwisterLoop, base.Center).ToFloat();
        }
        ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
        if (activeSound != null)
        {
            activeSound.Position = base.Center;
            activeSound.Volume = 1f - Math.Max(ai[0] - (num - 15f), 0f) / 15f;
        }
        else
        {
            localAI[1] = SlotId.Invalid.ToFloat();
        }
        if (localAI[0] >= 16f && ai[0] < num - 15f)
        {
            ai[0] = num - 15f;
        }
        ai[0] += 1f;
        if (ai[0] >= num)
        {
            Kill();
        }
        Vector2 top = base.Top;
        Vector2 bottom = base.Bottom;
        Vector2 vector = Vector2.Lerp(top, bottom, 0.5f);
        Vector2 vector2 = default(Vector2);
        ((Vector2)(ref vector2))._002Ector(0f, bottom.Y - top.Y);
        vector2.X = vector2.Y * 0.2f;
        int num2 = 16;
        int num3 = 160;
        Vector2 vector3 = default(Vector2);
        for (int i = 0; i < 1; i++)
        {
            ((Vector2)(ref vector3))._002Ector(base.Center.X - (float)(num2 / 2), position.Y + (float)height - (float)num3);
            if (Collision.SolidCollision(vector3, num2, num3) || Collision.WetCollision(vector3, num2, num3))
            {
                if (velocity.Y > 0f)
                {
                    velocity.Y = 0f;
                }
                if (velocity.Y > -4f)
                {
                    velocity.Y -= 2f;
                }
                else
                {
                    velocity.Y -= 4f;
                    localAI[0] += 2f;
                }
                if (velocity.Y < -16f)
                {
                    velocity.Y = -16f;
                }
                continue;
            }
            localAI[0] -= 1f;
            if (localAI[0] < 0f)
            {
                localAI[0] = 0f;
            }
            if (velocity.Y < 0f)
            {
                velocity.Y = 0f;
            }
            if (velocity.Y < 4f)
            {
                velocity.Y += 2f;
            }
            else
            {
                velocity.Y += 4f;
            }
            if (velocity.Y > 16f)
            {
                velocity.Y = 16f;
            }
        }
        if (ai[0] < num - 30f)
        {
            Vector2 vector4 = default(Vector2);
            Vector2 vector5 = default(Vector2);
            for (int j = 0; j < 1; j++)
            {
                float value = -1f;
                float value2 = 0.9f;
                float amount = Main.rand.NextFloat();
                ((Vector2)(ref vector4))._002Ector(MathHelper.Lerp(0.1f, 1f, Main.rand.NextFloat()), MathHelper.Lerp(value, value2, amount));
                vector4.X *= MathHelper.Lerp(2.2f, 0.6f, amount);
                vector4.X *= -1f;
                ((Vector2)(ref vector5))._002Ector(6f, 10f);
                Vector2 vector6 = vector + vector2 * vector4 * 0.5f + vector5;
                Dust dust = Main.dust[Dust.NewDust(vector6, 0, 0, 274)];
                dust.position = vector6;
                dust.fadeIn = 1.3f;
                dust.scale = 0.87f;
                dust.alpha = 211;
                if (vector4.X > -1.2f)
                {
                    dust.velocity.X = 1f + Main.rand.NextFloat();
                }
                dust.noGravity = true;
                dust.velocity.Y = Main.rand.NextFloat() * -0.5f - 1.3f;
                dust.velocity.X += velocity.X * 2.1f;
                dust.noLight = true;
            }
        }
        Vector2 vector7 = base.Bottom + new Vector2(-25f, -25f);
        for (int k = 0; k < 4; k++)
        {
            Dust dust2 = Dust.NewDustDirect(vector7, 50, 25, 31, velocity.X, -2f, 100);
            dust2.fadeIn = 1.1f;
            dust2.noGravity = true;
        }
        for (int l = 0; l < 1; l++)
        {
            if (Main.rand.Next(5) == 0)
            {
                Gore gore = Gore.NewGoreDirect(base.TopLeft + Main.rand.NextVector2Square(0f, 1f) * base.Size, new Vector2(velocity.X * 1.5f, (0f - Main.rand.NextFloat()) * 16f), Utils.SelectRandom<int>(Main.rand, 1007, 1008, 1008));
                gore.timeLeft = 60;
                gore.alpha = 50;
                gore.velocity.X += velocity.X;
            }
        }
        for (int m = 0; m < 1; m++)
        {
            if (Main.rand.Next(7) == 0)
            {
                Gore gore2 = Gore.NewGoreDirect(base.TopLeft + Main.rand.NextVector2Square(0f, 1f) * base.Size, new Vector2(velocity.X * 1.5f, (0f - Main.rand.NextFloat()) * 16f), Utils.SelectRandom<int>(Main.rand, 1007, 1008, 1008));
                gore2.timeLeft = 0;
                gore2.alpha = 80;
            }
        }
        for (int n = 0; n < 1; n++)
        {
            if (Main.rand.Next(7) == 0)
            {
                Gore gore3 = Gore.NewGoreDirect(base.TopLeft + Main.rand.NextVector2Square(0f, 1f) * base.Size, new Vector2(velocity.X * 1.5f, (0f - Main.rand.NextFloat()) * 16f), Utils.SelectRandom<int>(Main.rand, 1007, 1008, 1008));
                gore3.timeLeft = 0;
                gore3.alpha = 80;
            }
        }
    }
References Terraria.ID.SoundID.DD2_BookStaffTwisterLoop, Terraria.Main.dust, Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Gore.NewGoreDirect(), Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Main.rand, Terraria.Collision.SolidCollision(), and Terraria.Collision.WetCollision().