TModLoader: Terraria.Projectile.AI_147_Celeb2Rocket
AI_147_Celeb2Rocket()
void Terraria.Projectile.AI_147_Celeb2Rocket () inline private
Definition at line 55752 of file Projectile.cs.
    {
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_083f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0844: Unknown result type (might be due to invalid IL or missing references)
        //IL_0849: Unknown result type (might be due to invalid IL or missing references)
        //IL_085f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0865: Unknown result type (might be due to invalid IL or missing references)
        //IL_0867: Unknown result type (might be due to invalid IL or missing references)
        //IL_0874: Unknown result type (might be due to invalid IL or missing references)
        //IL_0879: Unknown result type (might be due to invalid IL or missing references)
        //IL_087e: Unknown result type (might be due to invalid IL or missing references)
        //IL_088e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0894: Unknown result type (might be due to invalid IL or missing references)
        //IL_0896: Unknown result type (might be due to invalid IL or missing references)
        //IL_089b: Unknown result type (might be due to invalid IL or missing references)
        //IL_089f: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0784: Unknown result type (might be due to invalid IL or missing references)
        //IL_0790: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_020c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_0220: Unknown result type (might be due to invalid IL or missing references)
        //IL_0225: Unknown result type (might be due to invalid IL or missing references)
        //IL_022a: Unknown result type (might be due to invalid IL or missing references)
        //IL_022f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_0242: Unknown result type (might be due to invalid IL or missing references)
        //IL_0248: Unknown result type (might be due to invalid IL or missing references)
        //IL_024a: Unknown result type (might be due to invalid IL or missing references)
        //IL_024f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_026a: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0305: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_030f: Unknown result type (might be due to invalid IL or missing references)
        //IL_031d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0328: Unknown result type (might be due to invalid IL or missing references)
        //IL_032d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0349: Unknown result type (might be due to invalid IL or missing references)
        //IL_034c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_035f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0361: Unknown result type (might be due to invalid IL or missing references)
        //IL_036b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0370: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b4: Unknown result type (might be due to invalid IL or missing references)
        int num = 0;
        int num11 = 1;
        int num16 = 1;
        localAI[num] += 1f;
        alpha = 0;
        rotation = velocity.ToRotation() + (float)Math.PI / 2f;
        int num17 = (int)ai[0];
        Vector2 center = base.Center;
        Color celeb2Color = GetCeleb2Color();
        Lighting.AddLight(center, ((Color)(ref celeb2Color)).ToVector3() * 0.5f);
        switch (num17)
        {
        case 0:
            if (localAI[num] >= 20f)
            {
                velocity.Y += 0.12f;
                penetrate = (maxPenetrate = -1);
            }
            if (velocity.Y > 16f)
            {
                velocity.Y = 16f;
            }
            if (localAI[num] > 20f && localAI[num] % 20f == 0f)
            {
                AI_147_Explosion();
            }
            break;
        case 1:
        {
            if (localAI[num] == 10f)
            {
                velocity.Y -= 10f;
            }
            if (localAI[num] >= 10f)
            {
                velocity.Y += 0.25f;
            }
            if (velocity.Y > 16f)
            {
                velocity.Y = 16f;
            }
            if (!(localAI[num] >= 10f))
            {
                break;
            }
            scale += 0.015f;
            if (scale > 2.5f)
            {
                scale = 2.5f;
            }
            if (localAI[num] % 10f != 0f)
            {
                break;
            }
            _ = velocity;
            for (float num18 = 0f; num18 < 1f; num18 += 0.12f)
            {
                Vector2 spinningpoint = Vector2.UnitX * -8f;
                spinningpoint += -Vector2.UnitY.RotatedBy(num18 * ((float)Math.PI * 2f)) * new Vector2(2f, 4f);
                spinningpoint = spinningpoint.RotatedBy(rotation - (float)Math.PI / 2f);
                int num19 = Dust.NewDust(base.Center, 0, 0, 267, 0f, 0f, 0, Color.Lerp(GetCeleb2Color(), Color.White, Main.rand.NextFloat() * 0.3f));
                Main.dust[num19].scale = 0.9f;
                Main.dust[num19].fadeIn = 1.1f;
                Main.dust[num19].noGravity = true;
                Main.dust[num19].position = base.Center + spinningpoint;
                Main.dust[num19].velocity = -velocity * 0.35f + spinningpoint * 0.35f;
                Dust obj = Main.dust[num19];
                obj.velocity *= scale;
                if (localAI[num] == 10f)
                {
                    Main.dust[num19].velocity = spinningpoint.RotatedBy(velocity.ToRotation()) * 0.3f;
                }
            }
            break;
        }
        case 2:
            if (localAI[num] >= 60f)
            {
                velocity.Y += 0.15f;
            }
            if (velocity.Y > 16f)
            {
                velocity.Y = 16f;
            }
            break;
        case 3:
        {
            float num20 = localAI[num11];
            if (num20 == 0f)
            {
                float num21 = ((Vector2)(ref velocity)).Length();
                localAI[num11] = num21;
                num20 = num21;
            }
            if (localAI[num] >= 25f && ai[num16] == 0f)
            {
                if (localAI[num] >= 20f)
                {
                    velocity.Y += 0.15f;
                }
                if (velocity.Y > 16f)
                {
                    velocity.Y = 16f;
                }
            }
            if (!(localAI[num] >= 20f))
            {
                break;
            }
            float num22 = position.X;
            float num2 = position.Y;
            float num3 = 800f;
            bool flag = false;
            int num4 = 0;
            if (ai[num16] == 0f)
            {
                for (int i = 0; i < 200; i++)
                {
                    if (Main.npc[i].CanBeChasedBy(this) && (ai[num16] == 0f || ai[num16] == (float)(i + 1)))
                    {
                        float num5 = Main.npc[i].position.X + (float)(Main.npc[i].width / 2);
                        float num6 = Main.npc[i].position.Y + (float)(Main.npc[i].height / 2);
                        float num7 = Math.Abs(position.X + (float)(width / 2) - num5) + Math.Abs(position.Y + (float)(height / 2) - num6);
                        if (num7 < num3 && Collision.CanHit(new Vector2(position.X + (float)(width / 2), position.Y + (float)(height / 2)), 1, 1, Main.npc[i].position, Main.npc[i].width, Main.npc[i].height))
{
                            num3 = num7;
                            num22 = num5;
                            num2 = num6;
                            flag = true;
                            num4 = i;
                        }
                    }
                }
                if (flag)
                {
                    ai[1] = num4 + 1;
                }
                flag = false;
            }
            if (ai[num16] != 0f)
            {
                int num8 = (int)(ai[num16] - 1f);
                if (Main.npc[num8].active && Main.npc[num8].CanBeChasedBy(this, ignoreDontTakeDamage: true))
                {
                    float num9 = Main.npc[num8].position.X + (float)(Main.npc[num8].width / 2);
                    float num10 = Main.npc[num8].position.Y + (float)(Main.npc[num8].height / 2);
                    if (Math.Abs(position.X + (float)(width / 2) - num9) + Math.Abs(position.Y + (float)(height / 2) - num10) < 1000f)
                    {
                        flag = true;
                        num22 = Main.npc[num8].position.X + (float)(Main.npc[num8].width / 2);
                        num2 = Main.npc[num8].position.Y + (float)(Main.npc[num8].height / 2);
                    }
                }
            }
            if (!friendly)
            {
                flag = false;
            }
            if (flag)
            {
                float num23 = num20;
                Vector2 vector2 = default(Vector2);
                ((Vector2)(ref vector2))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                float num12 = num22 - vector2.X;
                float num13 = num2 - vector2.Y;
                float num14 = (float)Math.Sqrt(num12 * num12 + num13 * num13);
                num14 = num23 / num14;
                num12 *= num14;
                num13 *= num14;
                int num15 = 8;
                velocity.X = (velocity.X * (float)(num15 - 1) + num12) / (float)num15;
                velocity.Y = (velocity.Y * (float)(num15 - 1) + num13) / (float)num15;
            }
            break;
        }
        case 4:
        {
            if (localAI[num] == 1f && ai[1] == 1f)
            {
                localAI[num] += 45f;
            }
            float x = velocity.SafeNormalize(Vector2.Zero).RotatedBy(localAI[num] * ((float)Math.PI / 45f)).X;
            Vector2 vector = velocity.SafeNormalize(Vector2.Zero).RotatedBy(1.5707963705062866);
            position += vector * x * 3f;
            scale = 2f;
            if (localAI[num] >= 10f)
            {
                velocity.Y += 0.04f;
            }
            if (velocity.Y > 16f)
            {
                velocity.Y = 16f;
            }
            break;
        }
        case 5:
            if (localAI[num] >= 40f)
            {
                velocity.Y += 0.08f;
            }
            if (velocity.Y > 16f)
            {
                velocity.Y = 16f;
            }
            break;
        case 6:
            if (localAI[num] >= 30f)
            {
                velocity.Y += 0.1f;
            }
            if (velocity.Y > 16f)
            {
                velocity.Y = 16f;
            }
            break;
        }
    }
References Terraria.Entity.active, Terraria.Lighting.AddLight(), Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHit(), Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Entity.height, Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Terraria.Main.npc, Terraria.Dust.position, Terraria.Entity.position, Terraria.Main.rand, Terraria.Dust.scale, Terraria.Dust.velocity, and Terraria.Entity.width.