TModLoader: Terraria.Projectile.CanHitWithOwnBody
CanHitWithOwnBody()
bool Terraria.Projectile.CanHitWithOwnBody (Entity ent) inline
    {
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_0217: Unknown result type (might be due to invalid IL or missing references)
        //IL_021a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0214: Unknown result type (might be due to invalid IL or missing references)
        if (Distance(ent.Center) > ownerHitCheckDistance)
        {
            return false;
        }
        bool flag = Collision.CanHit(base.position, width, height, ent.position, ent.width, ent.height) || Collision.CanHitLine(base.Center + new Vector2((float)(direction * width / 2), (float)(-height / 3)), 0, 0, ent.Center + new Vector2(0f, (float)(-ent.height / 3)), 0, 0) || Collision.CanHitLine(base.Center + new Vector2((float)(direction * width / 2), (float)(-height / 3)), 0, 0, ent.Center, 0, 0) || Collision.CanHitLine(base.Center + new Vector2((float)(direction * width / 2), 0f), 0, 0, ent.Center + new Vector2(0f, (float)(ent.height / 3)), 0, 0);
        float num = ProjectileID.Sets.ExtendedCanHitCheckRange[type];
        if (num != 0f)
        {
            if (flag)
            {
                return flag;
            }
            GenSearch genSearch = ProjectileID.Sets.ExtendedCanHitCheckSearch[type];
            Vector2 position = base.Top + new Vector2(0f, 0f - num);
            Vector2 position2 = ent.Top + new Vector2(0f, 0f - num);
            if (genSearch != null)
            {
                if (WorldUtils.Find(base.Top.ToTileCoordinates(), Searches.Chain(genSearch, _cachedConditions_notNull, _cachedConditions_solid), out var result))
                {
                    position = result.ToWorldCoordinates();
                }
                if (WorldUtils.Find(ent.Top.ToTileCoordinates(), Searches.Chain(genSearch, _cachedConditions_notNull, _cachedConditions_solid), out result))
                {
                    position2 = result.ToWorldCoordinates();
                }
            }
            flag |= Collision.CanHitLine(position, 0, 0, position2, 0, 0);
        }
        return flag;
    }
References Terraria.Projectile._cachedConditions_notNull, Terraria.Projectile._cachedConditions_solid, Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.WorldBuilding.Searches.Chain(), Terraria.Entity.direction, Terraria.Entity.Distance(), Terraria.ID.ProjectileID.Sets.ExtendedCanHitCheckRange, Terraria.ID.ProjectileID.Sets.ExtendedCanHitCheckSearch, Terraria.WorldBuilding.WorldUtils.Find(), Terraria.Entity.height, Terraria.Projectile.ownerHitCheckDistance, Terraria.Entity.position, Terraria.Projectile.type, and Terraria.Entity.width.