TModLoader: Terraria.Projectile.LightDisc_Bounce
LightDisc_Bounce()
void Terraria.Projectile.LightDisc_Bounce (Vector2 hitPoint, Vector2 normal) inline private
Definition at line 19325 of file Projectile.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        Vector2 spinningpoint = Vector2.Reflect(velocity, normal);
        for (int i = 0; i < 4; i++)
        {
            Dust dust = Dust.NewDustPerfect(hitPoint, 306, spinningpoint.RotatedBy((float)Math.PI / 4f * Main.rand.NextFloatDirection()) * 0.6f * Main.rand.NextFloat(), 200, default(Color), 1.6f);
            dust.color = Color.Lerp(new Color(219, 253, 0), Color.Cyan, Main.rand.NextFloat());
            Dust dust2 = Dust.CloneDust(dust);
            dust2.color = Color.White;
            dust2.scale = 1f;
            dust2.alpha = 50;
        }
    }
References Terraria.Dust.CloneDust(), Terraria.Dust.NewDustPerfect(), Terraria.Main.rand, and Terraria.Entity.velocity.
Referenced by Terraria.Projectile.Damage(), and Terraria.Projectile.HandleMovement().