TModLoader: Terraria.Projectile.AI_187_ShadowHand
AI_187_ShadowHand()
void Terraria.Projectile.AI_187_ShadowHand () inline private
Definition at line 43768 of file Projectile.cs.
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0341: Unknown result type (might be due to invalid IL or missing references)
        //IL_0348: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_037b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fa: Unknown result type (might be due to invalid IL or missing references)
        AI_187_ShadowHand_GetVariation(out var variation, out var fakeCounter, out var counterMax);
        float fromValue = fakeCounter / counterMax;
        if (fakeCounter == 0f)
        {
            localAI[1] = SoundEngine.PlayTrackedSound(in SoundID.DD2_GhastlyGlaiveImpactGhost, base.Center).ToFloat();
        }
        ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
        if (activeSound == null)
        {
            localAI[1] = SlotId.Invalid.ToFloat();
        }
        else
        {
            activeSound.Position = base.Center;
        }
        float num = counterMax - 15f;
        if (fakeCounter > num)
        {
            alpha += 25;
            if (alpha > 255)
            {
                alpha = 255;
            }
        }
        else
        {
            alpha -= 25;
            if (alpha < 50)
            {
                alpha = 50;
            }
        }
        if (fakeCounter >= counterMax - 1f)
        {
            Kill();
            return;
        }
        if (variation == 0)
        {
            velocity *= 0.98f;
            direction = (spriteDirection = ((velocity.X > 0f) ? 1 : (-1)));
            rotation = velocity.ToRotation();
            if (spriteDirection == -1)
            {
                rotation += (float)Math.PI;
            }
        }
        if (variation == 1)
        {
            float num2 = 70f;
            direction = (spriteDirection = ((velocity.X > 0f) ? 1 : (-1)));
            if (((Vector2)(ref velocity)).Length() > 0.1f)
            {
                velocity *= 0.95f;
            }
            num2 *= (float)direction;
            Vector2 vector = base.Center - rotation.ToRotationVector2() * num2;
            float num8 = Utils.Remap(fromValue, 0.3f, 0.5f, 0f, 1f) * Utils.Remap(fromValue, 0.45f, 0.5f, 1f, 0f);
            float num3 = Utils.Remap(fromValue, 0.5f, 0.55f, 0f, 1f) * Utils.Remap(fromValue, 0.5f, 1f, 1f, 0f);
            float num4 = num8 * (float)Math.PI * 1f / 60f;
            num4 += num3 * -(float)Math.PI * 8f / 60f;
            rotation += num4 * (float)(-direction);
            rotation = MathHelper.WrapAngle(rotation);
            base.Center = vector + rotation.ToRotationVector2() * num2;
        }
        if (variation == 2)
        {
            float f = ai[1];
            float num9 = Utils.Remap(fromValue, 0f, 0.4f, 1f, 0f);
            float num5 = Utils.Remap(fromValue, 0.3f, 0.4f, 0f, 1f) * Utils.Remap(fromValue, 0.4f, 1f, 1f, 0f);
            float num6 = num9 * 2f + num5 * 8f + 0.01f;
            velocity = f.ToRotationVector2() * num6;
            direction = (spriteDirection = ((velocity.X > 0f) ? 1 : (-1)));
            rotation = velocity.ToRotation();
            if (spriteDirection == -1)
            {
                rotation += (float)Math.PI;
            }
        }
        if (variation == 3)
        {
            float num7 = ai[1];
            velocity = velocity.RotatedBy(num7);
            direction = (spriteDirection = ((velocity.X > 0f) ? 1 : (-1)));
            rotation = velocity.ToRotation();
            if (spriteDirection == -1)
            {
                rotation += (float)Math.PI;
            }
        }
        ai[0] += 1f;
    }
References Terraria.ID.SoundID.DD2_GhastlyGlaiveImpactGhost, Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.Audio.SoundEngine.PlayTrackedSound(), and Terraria.Utils.Remap().