TModLoader: Terraria.Projectile.AI_061_FishingBobber_GiveItemToPlayer
AI_061_FishingBobber_GiveItemToPlayer()
void Terraria.Projectile.AI_061_FishingBobber_GiveItemToPlayer (Player thePlayer, int itemType) inline private
Definition at line 57283 of file Projectile.cs.
    {
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        Item item = new Item();
        item.SetDefaults(itemType);
        if (itemType == 3196)
        {
            int finalFishingLevel = thePlayer.GetFishingConditions().FinalFishingLevel;
            int minValue = (finalFishingLevel / 20 + 3) / 2;
            int num = (finalFishingLevel / 10 + 6) / 2;
            if (Main.rand.Next(50) < finalFishingLevel)
            {
                num++;
            }
            if (Main.rand.Next(100) < finalFishingLevel)
            {
                num++;
            }
            if (Main.rand.Next(150) < finalFishingLevel)
            {
                num++;
            }
            if (Main.rand.Next(200) < finalFishingLevel)
            {
                num++;
            }
            int stack = Main.rand.Next(minValue, num + 1);
            item.stack = stack;
        }
        if (itemType == 3197)
        {
            int finalFishingLevel2 = thePlayer.GetFishingConditions().FinalFishingLevel;
            int minValue2 = (finalFishingLevel2 / 4 + 15) / 2;
            int num2 = (finalFishingLevel2 / 2 + 40) / 2;
            if (Main.rand.Next(50) < finalFishingLevel2)
            {
                num2 += 6;
            }
            if (Main.rand.Next(100) < finalFishingLevel2)
            {
                num2 += 6;
            }
            if (Main.rand.Next(150) < finalFishingLevel2)
            {
                num2 += 6;
            }
            if (Main.rand.Next(200) < finalFishingLevel2)
            {
                num2 += 6;
            }
            int stack2 = Main.rand.Next(minValue2, num2 + 1);
            item.stack = stack2;
        }
        PlayerLoader.ModifyCaughtFish(thePlayer, item);
        ItemLoader.CaughtFishStack(item);
        item.newAndShiny = true;
        Item item2 = thePlayer.GetItem(owner, item, default(GetItemSettings));
        if (item2.stack > 0)
        {
            int number = Item.NewItem(new EntitySource_OverfullInventory(thePlayer), (int)position.X, (int)position.Y, width, height, itemType, item2.stack, noBroadcast: false, 0, noGrabDelay: true);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number, 1f);
            }
        }
        else
        {
            item.position.X = base.Center.X - (float)(item.width / 2);
            item.position.Y = base.Center.Y - (float)(item.height / 2);
            item.active = true;
            PopupText.NewText(PopupTextContext.RegularItemPickup, item, 0);
        }
    }
References Terraria.ModLoader.ItemLoader.CaughtFishStack(), Terraria.Entity.height, Terraria.ModLoader.PlayerLoader.ModifyCaughtFish(), Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.PopupText.NewText(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), and Terraria.Entity.width.