TModLoader: Terraria.Projectile.AI_007_GrapplingHooks
AI_007_GrapplingHooks()
void Terraria.Projectile.AI_007_GrapplingHooks () inline private
Definition at line 55312 of file Projectile.cs.
    {
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_0146: Unknown result type (might be due to invalid IL or missing references)
        //IL_022e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0283: Unknown result type (might be due to invalid IL or missing references)
        //IL_0288: Unknown result type (might be due to invalid IL or missing references)
        //IL_028e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0293: Unknown result type (might be due to invalid IL or missing references)
        //IL_031f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0324: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e20: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e68: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0650: Unknown result type (might be due to invalid IL or missing references)
        //IL_065a: Unknown result type (might be due to invalid IL or missing references)
        //IL_065f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0664: Unknown result type (might be due to invalid IL or missing references)
        //IL_0667: Unknown result type (might be due to invalid IL or missing references)
        //IL_0671: Unknown result type (might be due to invalid IL or missing references)
        //IL_0676: Unknown result type (might be due to invalid IL or missing references)
        //IL_067b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0682: Unknown result type (might be due to invalid IL or missing references)
        //IL_0687: Unknown result type (might be due to invalid IL or missing references)
        //IL_068c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0691: Unknown result type (might be due to invalid IL or missing references)
        //IL_0698: Unknown result type (might be due to invalid IL or missing references)
        //IL_069d: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0801: Unknown result type (might be due to invalid IL or missing references)
        //IL_0749: Unknown result type (might be due to invalid IL or missing references)
        //IL_074e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0753: Unknown result type (might be due to invalid IL or missing references)
        //IL_0755: Unknown result type (might be due to invalid IL or missing references)
        //IL_0861: Unknown result type (might be due to invalid IL or missing references)
        //IL_086e: Unknown result type (might be due to invalid IL or missing references)
        //IL_087a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0881: Unknown result type (might be due to invalid IL or missing references)
        //IL_078b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0795: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0893: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0928: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c23: Unknown result type (might be due to invalid IL or missing references)
        if (Main.player[owner].dead || Main.player[owner].stoned || Main.player[owner].webbed || Main.player[owner].frozen)
        {
            Kill();
            return;
        }
        Vector2 mountedCenter = Main.player[owner].MountedCenter;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
        float num = mountedCenter.X - vector.X;
        float num12 = mountedCenter.Y - vector.Y;
        float num13 = (float)Math.Sqrt(num * num + num12 * num12);
        rotation = (float)Math.Atan2(num12, num) - 1.57f;
        if (ai[0] == 2f && type == 865)
        {
            float num14 = (float)Math.PI / 2f;
            int num15 = (int)Math.Round(rotation / num14);
            rotation = (float)num15 * num14;
        }
        if (Main.myPlayer == owner)
        {
            int num16 = (int)(base.Center.X / 16f);
            int num17 = (int)(base.Center.Y / 16f);
            if (num16 > 0 && num17 > 0 && num16 < Main.maxTilesX && num17 < Main.maxTilesY && Main.tile[num16, num17].nactive() && TileID.Sets.CrackedBricks[Main.tile[num16, num17].type] && Main.rand.Next(16) == 0)
            {
                WorldGen.KillTile(num16, num17);
                if (Main.netMode != 0)
                {
                    NetMessage.SendData(17, -1, -1, null, 20, num16, num17);
                }
            }
        }
        if (num13 > 2500f)
        {
            Kill();
        }
        if (type == 256)
        {
            rotation = (float)Math.Atan2(num12, num) + 3.9250002f;
        }
        if (type == 446)
        {
            Lighting.AddLight(mountedCenter, 0f, 0.4f, 0.3f);
            localAI[0] += 1f;
            if (localAI[0] >= 28f)
            {
                localAI[0] = 0f;
            }
            DelegateMethods.v3_1 = new Vector3(0f, 0.4f, 0.3f);
            Utils.PlotTileLine(base.Center, mountedCenter, 8f, DelegateMethods.CastLightOpen);
        }
        if (type == 652 && ++frameCounter >= 7)
        {
            frameCounter = 0;
            if (++frame >= Main.projFrames[type])
            {
                frame = 0;
            }
        }
        if (type >= 646 && type <= 649)
        {
            Vector3 vector2 = Vector3.Zero;
            switch (type)
            {
            case 646:
                ((Vector3)(ref vector2))._002Ector(0.7f, 0.5f, 0.1f);
                break;
            case 647:
                ((Vector3)(ref vector2))._002Ector(0f, 0.6f, 0.7f);
                break;
            case 648:
                ((Vector3)(ref vector2))._002Ector(0.6f, 0.2f, 0.6f);
                break;
            case 649:
                ((Vector3)(ref vector2))._002Ector(0.6f, 0.6f, 0.9f);
                break;
            }
            Lighting.AddLight(mountedCenter, vector2);
            Lighting.AddLight(base.Center, vector2);
            DelegateMethods.v3_1 = vector2;
            Utils.PlotTileLine(base.Center, mountedCenter, 8f, DelegateMethods.CastLightOpen);
        }
        if (ai[0] == 0f)
        {
            if ((num13 > 300f && type == 13) || (num13 > 400f && type == 32) || (num13 > 440f && type == 73) || (num13 > 440f && type == 74) || (num13 > 375f && type == 165) || (num13 > 350f && type == 256) || (num13 > 500f && type == 315) || (num13 > 550f && type == 322) || (num13 > 400f && type == 331) || (num13 > 550f && type == 332) || (num13 > 400f && type == 372) || (num13 > 300f && type == 396) || (num13 > 550f && type >= 646 && type <= 649) || (num13 > 600f && type == 652) || (num13 > 300f && type == 865) || (num13 > 500f && type == 935) || (num13 > 480f && type >= 486 && type <= 489) || (num13 > 500f && type == 446))
            {
                ai[0] = 1f;
            }
            else if (type >= 230 && type <= 235)
            {
                int num18 = 300 + (type - 230) * 30;
                if (num13 > (float)num18)
                {
                    ai[0] = 1f;
                }
            }
            else if (type == 753)
            {
                int num19 = 420;
                if (num13 > (float)num19)
                {
                    ai[0] = 1f;
                }
            }
            else if (ProjectileLoader.GrappleOutOfRange(num13, this))
            {
                ai[0] = 1f;
            }
            Vector2 vector3 = base.Center - new Vector2(5f);
            Vector2 val = base.Center + new Vector2(5f);
            Point point = (vector3 - new Vector2(16f)).ToTileCoordinates();
            Point val2 = (val + new Vector2(32f)).ToTileCoordinates();
            int num2 = point.X;
            int num3 = val2.X;
            int num4 = point.Y;
            int num5 = val2.Y;
            if (num2 < 0)
            {
                num2 = 0;
            }
            if (num3 > Main.maxTilesX)
            {
                num3 = Main.maxTilesX;
            }
            if (num4 < 0)
            {
                num4 = 0;
            }
            if (num5 > Main.maxTilesY)
            {
                num5 = Main.maxTilesY;
            }
            Player player = Main.player[owner];
            List<Point> list = new List<Point>();
            Point point2 = default(Point);
            for (int i = 0; i < player.grapCount; i++)
            {
                Projectile projectile = Main.projectile[player.grappling[i]];
                if (projectile.aiStyle != 7 || projectile.ai[0] != 2f)
                {
                    continue;
                }
                Point pt = projectile.Center.ToTileCoordinates();
                Tile tileSafely = Framing.GetTileSafely(pt);
                if (tileSafely.type != 314 && !TileID.Sets.Platforms[tileSafely.type])
                {
                    continue;
                }
                for (int j = -2; j <= 2; j++)
                {
                    for (int k = -2; k <= 2; k++)
                    {
                        ((Point)(ref point2))._002Ector(pt.X + j, pt.Y + k);
                        Tile tileSafely2 = Framing.GetTileSafely(point2);
                        if (tileSafely2.type == 314 || TileID.Sets.Platforms[tileSafely2.type])
{
                            list.Add(point2);
                        }
                    }
                }
            }
            Vector2 vector4 = default(Vector2);
            for (int l = num2; l < num3; l++)
            {
                for (int m = num4; m < num5; m++)
                {
                    if (Main.tile[l, m] == null)
                    {
                        Main.tile[l, m] = default(Tile);
                    }
                    vector4.X = l * 16;
                    vector4.Y = m * 16;
                    if (!(vector3.X + 10f > vector4.X) || !(vector3.X < vector4.X + 16f) || !(vector3.Y + 10f > vector4.Y) || !(vector3.Y < vector4.Y + 16f))
                    {
                        continue;
                    }
                    Tile tile = Main.tile[l, m];
                    if (!AI_007_GrapplingHooks_CanTileBeLatchedOnTo(l, m) || list.Contains(new Point(l, m)) || (type == 403 && tile.type != 314) || Main.player[owner].IsBlacklistedForGrappling(new Point(l, m)))
                    {
                        continue;
                    }
                    if (Main.player[owner].grapCount < 10)
                    {
                        Main.player[owner].grappling[Main.player[owner].grapCount] = whoAmI;
                        Main.player[owner].grapCount++;
                    }
                    if (Main.myPlayer != owner)
                    {
                        continue;
                    }
                    int num6 = 0;
                    int num7 = -1;
                    int num8 = 100000;
                    if (type == 73 || type == 74)
                    {
                        for (int n = 0; n < 1000; n++)
{
                            if (n != whoAmI && Main.projectile[n].active && Main.projectile[n].owner == owner && Main.projectile[n].aiStyle == 7 && Main.projectile[n].ai[0] == 2f)
{
                                Main.projectile[n].Kill();
                            }
                        }
                    }
                    else
                    {
                        int num9 = 3;
                        if (type == 165)
{
                            num9 = 8;
                        }
                        if (type == 256)
{
                            num9 = 2;
                        }
                        if (type == 372)
{
                            num9 = 2;
                        }
                        if (type == 652)
{
                            num9 = 1;
                        }
                        if (type >= 646 && type <= 649)
{
                            num9 = 4;
                        }
                        ProjectileLoader.NumGrappleHooks(this, Main.player[owner], ref num9);
                        for (int num10 = 0; num10 < 1000; num10++)
{
                            if (Main.projectile[num10].active && Main.projectile[num10].owner == owner && Main.projectile[num10].aiStyle == 7)
{
                                if (Main.projectile[num10].timeLeft < num8)
{
                                    num7 = num10;
                                    num8 = Main.projectile[num10].timeLeft;
                                }
                                num6++;
                            }
                        }
                        if (num6 > num9)
{
                            Main.projectile[num7].Kill();
                        }
                    }
                    WorldGen.KillTile(l, m, fail: true, effectOnly: true);
                    SoundEngine.PlaySound(0, l * 16, m * 16);
                    velocity.X = 0f;
                    velocity.Y = 0f;
                    ai[0] = 2f;
                    position.X = l * 16 + 8 - width / 2;
                    position.Y = m * 16 + 8 - height / 2;
                    Rectangle? tileVisualHitbox = WorldGen.GetTileVisualHitbox(l, m);
                    if (tileVisualHitbox.HasValue)
                    {
                        Rectangle value = tileVisualHitbox.Value;
                        base.Center = ((Rectangle)(ref value)).Center.ToVector2();
                    }
                    damage = 0;
                    netUpdate = true;
                    if (Main.myPlayer == owner)
                    {
                        if (type == 935)
{
                            Main.player[owner].DoQueenSlimeHookTeleport(base.Center);
                        }
                        NetMessage.SendData(13, -1, -1, null, owner);
                    }
                    break;
                }
                if (ai[0] == 2f)
                {
                    break;
                }
            }
        }
        else if (ai[0] == 1f)
        {
            float num11 = 11f;
            if (type == 32)
            {
                num11 = 15f;
            }
            if (type == 73 || type == 74)
            {
                num11 = 17f;
            }
            if (type == 315)
            {
                num11 = 20f;
            }
            if (type == 322)
            {
                num11 = 22f;
            }
            if (type >= 230 && type <= 235)
            {
                num11 = 11f + (float)(type - 230) * 0.75f;
            }
            if (type == 753)
            {
                num11 = 15f;
            }
            if (type == 446)
            {
                num11 = 20f;
            }
            if (type >= 486 && type <= 489)
            {
                num11 = 18f;
            }
            if (type >= 646 && type <= 649)
            {
                num11 = 24f;
            }
            if (type == 652)
            {
                num11 = 24f;
            }
            if (type == 332)
            {
                num11 = 17f;
            }
            ProjectileLoader.GrappleRetreatSpeed(this, Main.player[owner], ref num11);
            if (num13 < 24f)
            {
                Kill();
            }
            num13 = num11 / num13;
            num *= num13;
            num12 *= num13;
            velocity.X = num;
            velocity.Y = num12;
        }
        else if (ai[0] == 2f)
        {
            Point point3 = base.Center.ToTileCoordinates();
            if (Main.tile[point3.X, point3.Y] == null)
            {
                Main.tile[point3.X, point3.Y] = default(Tile);
            }
            bool flag = true;
            if (AI_007_GrapplingHooks_CanTileBeLatchedOnTo(point3.X, point3.Y))
            {
                flag = false;
            }
            if (flag)
            {
                ai[0] = 1f;
            }
            else if (Main.player[owner].grapCount < 10)
            {
                Main.player[owner].grappling[Main.player[owner].grapCount] = whoAmI;
                Main.player[owner].grapCount++;
            }
        }
    }
References Terraria.Entity.active, Terraria.Lighting.AddLight(), Terraria.Projectile.ai, Terraria.Projectile.aiStyle, Terraria.DelegateMethods.CastLightOpen(), Terraria.Entity.Center, Terraria.ID.TileID.Sets.CrackedBricks, Terraria.Player.dead, Terraria.Player.DoQueenSlimeHookTeleport(), Terraria.Player.frozen, Terraria.Framing.GetTileSafely(), Terraria.WorldGen.GetTileVisualHitbox(), Terraria.Player.grapCount, Terraria.ModLoader.ProjectileLoader.GrappleOutOfRange(), Terraria.ModLoader.ProjectileLoader.GrappleRetreatSpeed(), Terraria.Player.grappling, Terraria.Player.IsBlacklistedForGrappling(), Terraria.Projectile.Kill(), Terraria.WorldGen.KillTile(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Player.MountedCenter, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.ModLoader.ProjectileLoader.NumGrappleHooks(), Terraria.Projectile.owner, Terraria.ID.TileID.Sets.Platforms, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Utils.PlotTileLine(), Terraria.Main.projectile, Terraria.Main.projFrames, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Player.stoned, Terraria.Main.tile, Terraria.Projectile.timeLeft, Terraria.Tile.type, and Terraria.Player.webbed.