TModLoader: Terraria.Projectile.RandomizeInsanityShadowFor
RandomizeInsanityShadowFor()
static void Terraria.Projectile.RandomizeInsanityShadowFor (Entity targetEntity, bool isHostile, out Vector2 spawnposition, out Vector2 spawnvelocity, out float ai0, out float ai1) inline static
    {
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_019b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0212: Unknown result type (might be due to invalid IL or missing references)
        //IL_0217: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_022e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0233: Unknown result type (might be due to invalid IL or missing references)
        //IL_023c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_0243: Unknown result type (might be due to invalid IL or missing references)
        //IL_0248: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_025a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0262: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        //IL_0277: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        int num = Main.rand.Next(2) * 2 - 1;
        int num10 = Main.rand.Next(4);
        float num3 = (isHostile ? 200f : 100f);
        float num4 = (isHostile ? 30 : 20);
        float num5 = (isHostile ? 30 : 0);
        float num6 = Main.rand.NextFloatDirection() * (float)Math.PI * 0.125f;
        if (isHostile && targetEntity.velocity.X * (float)num > 0f)
        {
            num *= -1;
        }
        if (num10 == 0 && isHostile)
        {
            num4 += 10f;
        }
        spawnposition = targetEntity.Center + targetEntity.velocity * num5 + Utils.RotatedBy(new Vector2((float)num * (0f - num3), 0f), num6);
        spawnvelocity = Utils.RotatedBy(new Vector2((float)num * num3 / num4, 0f), num6);
        ai0 = 0f;
        ai1 = 0f;
        if (num10 == 1)
        {
            float num7 = (float)Math.PI * 2f * Main.rand.NextFloat();
            spawnposition = targetEntity.Center - num7.ToRotationVector2() * (isHostile ? num3 : (num3 * 0.5f));
            ai0 = 180f;
            ai1 = num7 - (float)Math.PI / 2f;
            spawnvelocity = num7.ToRotationVector2() * (float)(isHostile ? 4 : 2);
        }
        if (num10 == 2)
        {
            float num8 = (float)Math.PI * 2f * Main.rand.NextFloat();
            spawnposition = targetEntity.Center - num8.ToRotationVector2() * num3;
            ai0 = 300f;
            ai1 = num8;
            spawnvelocity = num8.ToRotationVector2() * (float)(isHostile ? 4 : 2);
        }
        if (num10 == 3)
        {
            float f = (float)Math.PI * 2f * Main.rand.NextFloat();
            float num9 = (isHostile ? 60 : 30);
            float num2 = (float)Math.PI / 2f / num9 * Main.rand.NextFloatDirection();
            spawnposition = targetEntity.Center + targetEntity.velocity * num9;
            Vector2 vector = f.ToRotationVector2() * (float)(isHostile ? 8 : 3);
            for (int i = 0; (float)i < num9; i++)
            {
                spawnposition -= vector;
                vector = vector.RotatedBy(0f - num2);
            }
            spawnvelocity = vector;
            ai0 = 390f;
            ai1 = num2;
        }
    }
References Terraria.Main.rand, and Terraria.Utils.RotatedBy().
Referenced by Terraria.NPC.AI_123_Deerclops(), Terraria.Player.SpawnHallucination(), and Terraria.NPC.SpawnPassiveShadowHands().