TModLoader: Terraria.Projectile.AI_015_Flails
AI_015_Flails()
void Terraria.Projectile.AI_015_Flails () inline private
    {
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_046b: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_084d: Unknown result type (might be due to invalid IL or missing references)
        //IL_084e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0853: Unknown result type (might be due to invalid IL or missing references)
        //IL_0858: Unknown result type (might be due to invalid IL or missing references)
        //IL_085d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0860: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03da: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0300: Unknown result type (might be due to invalid IL or missing references)
        //IL_030c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0311: Unknown result type (might be due to invalid IL or missing references)
        //IL_0316: Unknown result type (might be due to invalid IL or missing references)
        //IL_0319: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0873: Unknown result type (might be due to invalid IL or missing references)
        //IL_087d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0882: Unknown result type (might be due to invalid IL or missing references)
        //IL_0889: Unknown result type (might be due to invalid IL or missing references)
        //IL_088e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0892: Unknown result type (might be due to invalid IL or missing references)
        //IL_0899: Unknown result type (might be due to invalid IL or missing references)
        //IL_089e: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_08af: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08be: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0980: Unknown result type (might be due to invalid IL or missing references)
        //IL_098b: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0412: Unknown result type (might be due to invalid IL or missing references)
        //IL_0413: Unknown result type (might be due to invalid IL or missing references)
        //IL_041a: Unknown result type (might be due to invalid IL or missing references)
        //IL_041f: Unknown result type (might be due to invalid IL or missing references)
        //IL_042a: Unknown result type (might be due to invalid IL or missing references)
        //IL_042f: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0549: Unknown result type (might be due to invalid IL or missing references)
        //IL_0553: Unknown result type (might be due to invalid IL or missing references)
        //IL_0558: Unknown result type (might be due to invalid IL or missing references)
        //IL_064e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0658: Unknown result type (might be due to invalid IL or missing references)
        //IL_065d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0664: Unknown result type (might be due to invalid IL or missing references)
        //IL_0669: Unknown result type (might be due to invalid IL or missing references)
        //IL_066d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0674: Unknown result type (might be due to invalid IL or missing references)
        //IL_0679: Unknown result type (might be due to invalid IL or missing references)
        //IL_0680: Unknown result type (might be due to invalid IL or missing references)
        //IL_068b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0633: Unknown result type (might be due to invalid IL or missing references)
        //IL_063d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0642: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_035d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0362: Unknown result type (might be due to invalid IL or missing references)
        //IL_0367: Unknown result type (might be due to invalid IL or missing references)
        //IL_036d: Unknown result type (might be due to invalid IL or missing references)
        //IL_057e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0584: Unknown result type (might be due to invalid IL or missing references)
        //IL_077d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0787: Unknown result type (might be due to invalid IL or missing references)
        //IL_078c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0793: Unknown result type (might be due to invalid IL or missing references)
        //IL_0799: Unknown result type (might be due to invalid IL or missing references)
        //IL_079a: Unknown result type (might be due to invalid IL or missing references)
        //IL_079f: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_073c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0746: Unknown result type (might be due to invalid IL or missing references)
        //IL_074b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0752: Unknown result type (might be due to invalid IL or missing references)
        //IL_0758: Unknown result type (might be due to invalid IL or missing references)
        //IL_0759: Unknown result type (might be due to invalid IL or missing references)
        //IL_075e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0763: Unknown result type (might be due to invalid IL or missing references)
        //IL_076a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0771: Unknown result type (might be due to invalid IL or missing references)
        //IL_0776: Unknown result type (might be due to invalid IL or missing references)
        //IL_0820: Unknown result type (might be due to invalid IL or missing references)
        //IL_082b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b4d: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        if (!player.active || player.dead || player.noItems || player.CCed || Vector2.Distance(base.Center, player.Center) > 900f)
        {
            Kill();
            return;
        }
        if (Main.myPlayer == owner && Main.mapFullscreen)
        {
            Kill();
            return;
        }
        if (type == 948 && wet && !lavaWet)
        {
            type = 947;
            netUpdate = true;
        }
        Vector2 mountedCenter = player.MountedCenter;
        bool doFastThrowDust = false;
        bool flag = true;
        bool flag2 = false;
        int num = 10;
        float num11 = 24f;
        float num16 = 800f;
        float num17 = 3f;
        float num18 = 16f;
        float num19 = 6f;
        float num20 = 48f;
        float num21 = 1f;
        float num22 = 14f;
        int num2 = 60;
        int num3 = 10;
        int num4 = 15;
        int num5 = 10;
        int num6 = num + 5;
        switch (type)
        {
        case 947:
        case 948:
            num = 13;
            num11 = 12f;
            num18 = 8f;
            num20 = 13f;
            break;
        case 25:
            num = 15;
            num11 = 14f;
            num18 = 10f;
            num20 = 15f;
            break;
        case 154:
            num = 15;
            num11 = 15f;
            num18 = 11f;
            num20 = 16f;
            break;
        case 26:
            num = 15;
            num11 = 16f;
            num18 = 12f;
            num20 = 16f;
            break;
        case 35:
            num = 15;
            num11 = 17f;
            num18 = 14f;
            num20 = 18f;
            break;
        case 63:
            num = 13;
            num11 = 21f;
            num18 = 20f;
            num20 = 24f;
            num4 = 12;
            break;
        case 757:
            num = 13;
            num11 = 22f;
            num18 = 22f;
            num20 = 26f;
            num4 = 12;
            break;
        case 247:
            num = 13;
            num11 = 23f;
            num4 = 12;
            break;
        }
        float num7 = 1f / player.inverseMeleeSpeed;
        num11 *= num7;
        num21 *= num7;
        num22 *= num7;
        num17 *= num7;
        num18 *= num7;
        num19 *= num7;
        num20 *= num7;
        float num8 = num11 * (float)num;
        float num9 = num8 + 160f;
        localNPCHitCooldown = num3;
        switch ((int)ai[0])
        {
        case 0:
        {
            flag2 = true;
            if (owner == Main.myPlayer)
            {
                Vector2 mouseWorld = Main.MouseWorld;
                Vector2 vector3 = mountedCenter.DirectionTo(mouseWorld).SafeNormalize(Vector2.UnitX * (float)player.direction);
                player.ChangeDir((vector3.X > 0f) ? 1 : (-1));
                if (!player.channel)
                {
                    ai[0] = 1f;
                    ai[1] = 0f;
                    velocity = vector3 * num11 + player.velocity;
                    base.Center = mountedCenter;
                    netUpdate = true;
                    ResetLocalNPCHitImmunity();
                    localNPCHitCooldown = num5;
                    break;
                }
            }
            localAI[1] += 1f;
            Vector2 vector4 = Utils.RotatedBy(new Vector2((float)player.direction), (float)Math.PI * 10f * (localAI[1] / 60f) * (float)player.direction);
            vector4.Y *= 0.8f;
            if (vector4.Y * player.gravDir > 0f)
            {
                vector4.Y *= 0.5f;
            }
            base.Center = mountedCenter + vector4 * 30f;
            velocity = Vector2.Zero;
            localNPCHitCooldown = num4;
            break;
        }
        case 1:
        {
            doFastThrowDust = true;
            bool flag3 = ai[1]++ >= (float)num;
            flag3 |= Distance(mountedCenter) >= num16;
            if (player.controlUseItem)
            {
                ai[0] = 6f;
                ai[1] = 0f;
                netUpdate = true;
                velocity *= 0.2f;
                if (Main.myPlayer == owner && type == 757)
                {
                    NewProjectile(GetProjectileSource_FromThis(), base.Center, velocity, 928, damage, knockBack, Main.myPlayer);
                }
                break;
            }
            if (flag3)
            {
                ai[0] = 2f;
                ai[1] = 0f;
                netUpdate = true;
                velocity *= 0.3f;
                if (Main.myPlayer == owner && type == 757)
                {
                    NewProjectile(GetProjectileSource_FromThis(), base.Center, velocity, 928, damage, knockBack, Main.myPlayer);
                }
            }
            player.ChangeDir((player.Center.X < base.Center.X) ? 1 : (-1));
            localNPCHitCooldown = num5;
            break;
        }
        case 2:
        {
            Vector2 vector = DirectionTo(mountedCenter).SafeNormalize(Vector2.Zero);
            if (Distance(mountedCenter) <= num18)
            {
                Kill();
                return;
            }
            if (player.controlUseItem)
            {
                ai[0] = 6f;
                ai[1] = 0f;
                netUpdate = true;
                velocity *= 0.2f;
            }
            else
            {
                velocity *= 0.98f;
                velocity = velocity.MoveTowards(vector * num18, num17);
                player.ChangeDir((player.Center.X < base.Center.X) ? 1 : (-1));
            }
            break;
        }
        case 3:
        {
            if (!player.controlUseItem)
            {
                ai[0] = 4f;
                ai[1] = 0f;
                netUpdate = true;
                break;
            }
            float num10 = Distance(mountedCenter);
            tileCollide = ai[1] == 1f;
            bool flag4 = num10 <= num8;
            if (flag4 != tileCollide)
            {
                tileCollide = flag4;
                ai[1] = (tileCollide ? 1 : 0);
                netUpdate = true;
            }
            if (num10 > (float)num2)
            {
                if (num10 >= num8)
                {
                    velocity *= 0.5f;
                    velocity = velocity.MoveTowards(DirectionTo(mountedCenter).SafeNormalize(Vector2.Zero) * num22, num22);
                }
                velocity *= 0.98f;
                velocity = velocity.MoveTowards(DirectionTo(mountedCenter).SafeNormalize(Vector2.Zero) * num22, num21);
            }
            else
            {
                if (((Vector2)(ref velocity)).Length() < 6f)
                {
                    velocity.X *= 0.96f;
                    velocity.Y += 0.2f;
                }
                if (player.velocity.X == 0f)
                {
                    velocity.X *= 0.96f;
                }
            }
            player.ChangeDir((player.Center.X < base.Center.X) ? 1 : (-1));
            break;
        }
        case 4:
        {
            tileCollide = false;
            Vector2 vector2 = DirectionTo(mountedCenter).SafeNormalize(Vector2.Zero);
            if (Distance(mountedCenter) <= num20)
            {
                Kill();
                return;
            }
            velocity *= 0.98f;
            velocity = velocity.MoveTowards(vector2 * num20, num19);
            Vector2 target = base.Center + velocity;
            Vector2 value = mountedCenter.DirectionFrom(target).SafeNormalize(Vector2.Zero);
            if (Vector2.Dot(vector2, value) < 0f)
            {
                Kill();
                return;
            }
            player.ChangeDir((player.Center.X < base.Center.X) ? 1 : (-1));
            break;
        }
        case 5:
            if (ai[1]++ >= (float)num6)
            {
                ai[0] = 6f;
                ai[1] = 0f;
                netUpdate = true;
            }
            else
            {
                localNPCHitCooldown = num5;
                velocity.Y += 0.6f;
                velocity.X *= 0.95f;
                player.ChangeDir((player.Center.X < base.Center.X) ? 1 : (-1));
            }
            break;
        case 6:
            if (!player.controlUseItem || Distance(mountedCenter) > num9)
            {
                ai[0] = 4f;
                ai[1] = 0f;
                netUpdate = true;
                break;
            }
            if (!shimmerWet)
            {
                velocity.Y += 0.8f;
            }
            velocity.X *= 0.95f;
            player.ChangeDir((player.Center.X < base.Center.X) ? 1 : (-1));
            break;
        }
        if (type == 247)
        {
            flag = false;
            float num12 = (Math.Abs(velocity.X) + Math.Abs(velocity.Y)) * 0.01f;
            rotation += ((velocity.X > 0f) ? num12 : (0f - num12));
            if (ai[0] == 0f)
            {
                rotation += (float)Math.PI * 2f / 15f * (float)player.direction;
            }
            float num13 = 600f;
            NPC nPC = null;
            if (owner == Main.myPlayer)
            {
                localAI[0] += 1f;
                if (localAI[0] >= 20f)
                {
                    localAI[0] = 17f;
                    for (int i = 0; i < 200; i++)
                    {
                        NPC nPC2 = Main.npc[i];
                        if (nPC2.CanBeChasedBy(this))
{
                            float num14 = Distance(nPC2.Center);
                            if (!(num14 >= num13) && Collision.CanHit(position, width, height, nPC2.position, nPC2.width, nPC2.height))
{
                                nPC = nPC2;
                                num13 = num14;
                            }
                        }
                    }
                }
                if (nPC != null)
                {
                    localAI[0] = 0f;
                    float num15 = 14f;
                    Vector2 center = base.Center;
                    Vector2 vector5 = center.DirectionTo(nPC.Center) * num15;
                    NewProjectile(GetProjectileSource_FromThis(), center, vector5, 248, (int)((double)damage / 1.5), knockBack / 2f, Main.myPlayer);
                }
            }
        }
        direction = ((velocity.X > 0f) ? 1 : (-1));
        spriteDirection = direction;
        ownerHitCheck = flag2;
        if (flag)
        {
            if (((Vector2)(ref velocity)).Length() > 1f)
            {
                rotation = velocity.ToRotation() + velocity.X * 0.1f;
            }
            else
            {
                rotation += velocity.X * 0.1f;
            }
        }
        timeLeft = 2;
        player.heldProj = whoAmI;
        player.SetDummyItemTime(2);
        player.itemRotation = DirectionFrom(mountedCenter).ToRotation();
        if (base.Center.X < mountedCenter.X)
        {
            player.itemRotation += (float)Math.PI;
        }
        player.itemRotation = MathHelper.WrapAngle(player.itemRotation);
        AI_015_Flails_Dust(doFastThrowDust);
    }
References Terraria.Entity.active, Terraria.Collision.CanHit(), Terraria.Player.CCed, Terraria.Entity.Center, Terraria.Player.ChangeDir(), Terraria.Player.channel, Terraria.Player.controlUseItem, Terraria.Player.dead, Terraria.Entity.direction, Terraria.Player.gravDir, Terraria.Player.inverseMeleeSpeed, Terraria.Player.itemRotation, Terraria.Main.mapFullscreen, Terraria.Player.MountedCenter, Terraria.Main.MouseWorld, Terraria.Main.myPlayer, Terraria.Player.noItems, Terraria.Main.npc, Terraria.Main.player, Terraria.Utils.RotatedBy(), Terraria.Player.SetDummyItemTime(), and Terraria.Entity.velocity.