TModLoader: Terraria.Projectile.FillWhipControlPoints
FillWhipControlPoints()
static void Terraria.Projectile.FillWhipControlPoints (Projectile proj, List< Vector2 > controlPoints) inline static
Definition at line 51265 of file Projectile.cs.
    {
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0225: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_022c: Unknown result type (might be due to invalid IL or missing references)
        //IL_022f: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_024f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_0253: Unknown result type (might be due to invalid IL or missing references)
        GetWhipSettings(proj, out var timeToFlyOut, out var segments, out var rangeMultiplier);
        float num = proj.ai[0] / timeToFlyOut;
        float num10 = 0.5f;
        float num11 = 1f + num10;
        float num12 = (float)Math.PI * 10f * (1f - num * num11) * (float)(-proj.spriteDirection) / (float)segments;
        float num13 = num * num11;
        float num14 = 0f;
        if (num13 > 1f)
        {
            num14 = (num13 - 1f) / num10;
            num13 = MathHelper.Lerp(1f, 0f, num14);
        }
        float num15 = proj.ai[0] - 1f;
        Player player = Main.player[proj.owner];
        Item heldItem = Main.player[proj.owner].HeldItem;
        num15 = (float)(ContentSamples.ItemsByType[heldItem.type].useAnimation * 2) * num * player.whipRangeMultiplier;
        float num16 = ((Vector2)(ref proj.velocity)).Length() * num15 * num13 * rangeMultiplier / (float)segments;
        float num17 = 1f;
        Vector2 playerArmPosition = Main.GetPlayerArmPosition(proj);
        Vector2 vector = playerArmPosition;
        float num2 = -(float)Math.PI / 2f;
        Vector2 vector2 = vector;
        float num3 = (float)Math.PI / 2f + (float)Math.PI / 2f * (float)proj.spriteDirection;
        Vector2 vector3 = vector;
        float num4 = (float)Math.PI / 2f;
        controlPoints.Add(playerArmPosition);
        for (int i = 0; i < segments; i++)
        {
            float num5 = (float)i / (float)segments;
            float num6 = num12 * num5 * num17;
            Vector2 vector4 = vector + num2.ToRotationVector2() * num16;
            Vector2 vector5 = vector3 + num4.ToRotationVector2() * (num16 * 2f);
            Vector2 val = vector2 + num3.ToRotationVector2() * (num16 * 2f);
            float num7 = 1f - num13;
            float num8 = 1f - num7 * num7;
            Vector2 value = Vector2.Lerp(vector5, vector4, num8 * 0.9f + 0.1f);
            Vector2 vector6 = Vector2.Lerp(val, value, num8 * 0.7f + 0.3f);
            Vector2 spinningpoint = playerArmPosition + (vector6 - playerArmPosition) * new Vector2(1f, num11);
            float num9 = num14;
            num9 *= num9;
            Vector2 item = spinningpoint.RotatedBy(proj.rotation + 4.712389f * num9 * (float)proj.spriteDirection, playerArmPosition);
            controlPoints.Add(item);
            num2 += num6;
            num4 += num6;
            num3 += num6;
            vector = vector4;
            vector3 = vector5;
            vector2 = val;
        }
    }
References Terraria.Main.GetPlayerArmPosition(), Terraria.Player.HeldItem, Terraria.ID.ContentSamples.ItemsByType, Terraria.Main.player, Terraria.Item.type, and Terraria.Player.whipRangeMultiplier.
Referenced by Terraria.Projectile.Colliding(), Terraria.Projectile.CutTiles(), Terraria.Main.DrawWhip(), and Terraria.Projectile.UpdateEnchantmentVisuals().