TModLoader: Terraria.Projectile.AI_019_Spears
AI_019_Spears()
void Terraria.Projectile.AI_019_Spears () inline private
Definition at line 48474 of file Projectile.cs.
    {
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_043b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0472: Unknown result type (might be due to invalid IL or missing references)
        //IL_0478: Unknown result type (might be due to invalid IL or missing references)
        //IL_048f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0499: Unknown result type (might be due to invalid IL or missing references)
        //IL_049e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0753: Unknown result type (might be due to invalid IL or missing references)
        //IL_075e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0525: Unknown result type (might be due to invalid IL or missing references)
        //IL_0530: Unknown result type (might be due to invalid IL or missing references)
        //IL_0848: Unknown result type (might be due to invalid IL or missing references)
        //IL_084d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0859: Unknown result type (might be due to invalid IL or missing references)
        //IL_085e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0864: Unknown result type (might be due to invalid IL or missing references)
        //IL_0869: Unknown result type (might be due to invalid IL or missing references)
        //IL_0875: Unknown result type (might be due to invalid IL or missing references)
        //IL_087a: Unknown result type (might be due to invalid IL or missing references)
        //IL_067b: Unknown result type (might be due to invalid IL or missing references)
        //IL_068d: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05df: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_06af: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0afd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b12: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b68: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e36: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e40: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e45: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cce: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cfa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d56: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d70: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0902: Unknown result type (might be due to invalid IL or missing references)
        //IL_0907: Unknown result type (might be due to invalid IL or missing references)
        //IL_0927: Unknown result type (might be due to invalid IL or missing references)
        //IL_092d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e86: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e96: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f2b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f31: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f40: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f45: Unknown result type (might be due to invalid IL or missing references)
        //IL_094c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0957: Unknown result type (might be due to invalid IL or missing references)
        //IL_095c: Unknown result type (might be due to invalid IL or missing references)
        //IL_099b: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09db: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_09eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a11: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a37: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        Vector2 center = player.RotatedRelativePoint(player.MountedCenter);
        direction = player.direction;
        player.heldProj = whoAmI;
        player.MatchItemTimeToItemAnimation();
        base.Center = center;
        bool flag = Main.player[owner].itemAnimation < Main.player[owner].itemAnimationMax / 3;
        int itemAnimationMax = player.itemAnimationMax;
        int itemAnimation = player.itemAnimation;
        int num = Main.player[owner].itemAnimationMax / 3;
        float num12 = MathHelper.Min((float)itemAnimation, (float)num);
        float num19 = (float)itemAnimation - num12;
        float num20 = 0f;
        float num21 = 0f;
        float num22 = 0f;
        bool flag2 = false;
        spriteDirection = -direction;
        switch (type)
        {
        case 46:
            num20 = 3f;
            num22 = 1.6f;
            num21 = 1.4f;
            break;
        case 105:
            num20 = 3f;
            num22 = 2.4f;
            num21 = 2.1f;
            break;
        case 367:
            num20 = 3f;
            num22 = 1.6f;
            num21 = 1.5f;
            break;
        case 368:
            num20 = 3f;
            num22 = 1.5f;
            num21 = 1.4f;
            break;
        case 222:
            num20 = 3f;
            num22 = 2.4f;
            num21 = 2.1f;
            break;
        case 342:
            num20 = 3f;
            num22 = 2.4f;
            num21 = 2.1f;
            break;
        case 47:
            num20 = 4f;
            num22 = 1.2f;
            num21 = 0.9f;
            break;
        case 153:
            num20 = 4f;
            num22 = 1.5f;
            num21 = 1.3f;
            break;
        case 49:
            num20 = 4f;
            num22 = 1.1f;
            num21 = 0.85f;
            break;
        case 730:
            num20 = 8f;
            num22 = 1.5f;
            num21 = 1.2f;
            break;
        case 877:
        case 878:
        case 879:
            alpha -= 40;
            if (alpha < 0)
            {
                alpha = 0;
            }
            num20 = 28f;
            num22 = 0.4f;
            num21 = 0.4f;
            flag2 = true;
            break;
        case 64:
        case 215:
            spriteDirection = -direction;
            num20 = 3f;
            num22 = 1.9f;
            num21 = 1.7f;
            break;
        case 66:
        case 97:
        case 212:
        case 218:
            num20 = 3f;
            num22 = 2.1f;
            num21 = 1.9f;
            break;
        case 130:
            num20 = 3f;
            num22 = 1.3f;
            num21 = 1f;
            break;
        }
        float num23 = (float)(itemAnimationMax - num) - num19;
        float num24 = (float)num - num12;
        float num25 = num20 + num21 * num23 - num22 * num24;
        position += velocity * num25;
        switch (type)
        {
        case 47:
            if (Main.player[owner].wet && Main.rand.Next(2) == 0)
            {
                int num2 = Dust.NewDust(Main.player[owner].position, Main.player[owner].width, Main.player[owner].height, 15, 0f, 0f, 100, default(Color), 0.8f);
                Dust obj = Main.dust[num2];
                obj.velocity *= 0.1f;
            }
            break;
        case 130:
            if ((localAI[0] == 0f || localAI[0] == 4f || localAI[0] == 8f || localAI[0] == 12f || localAI[0] == 16f || localAI[0] == 20f || localAI[0] == 24f) && owner == Main.myPlayer)
            {
                NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, velocity.X, velocity.Y, 131, damage / 3, 0f, owner);
            }
            localAI[0] += 1f;
            break;
        case 730:
            if (localAI[0] == 0f && Main.myPlayer == owner)
            {
                localAI[0] = 1f;
                Vector2 vector = velocity * 4f;
                NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, vector.X, vector.Y, 732, (int)((double)damage * 1.5), knockBack * 0.5f, owner);
            }
            break;
        case 342:
            if (flag && localAI[0] == 0f && Main.myPlayer == owner)
            {
                localAI[0] = 1f;
                if (Collision.CanHit(player.position, player.width, player.height, position, width, height))
                {
                    NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, velocity.X * 2.4f, velocity.Y * 2.4f, 343, damage, knockBack * 0.85f, owner);
                }
            }
            break;
        case 222:
            if (flag && localAI[0] == 0f && Main.myPlayer == owner)
            {
                localAI[0] = 1f;
                NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, velocity.X, velocity.Y, 228, damage, knockBack, owner);
            }
            break;
        }
        if (flag2 && player.channel && player.itemAnimation < num)
        {
            player.SetDummyItemTime(num);
        }
        rotation = (float)Math.Atan2(velocity.Y, velocity.X) + (float)Math.PI / 2f + (float)Math.PI / 4f;
        if (spriteDirection == -1)
        {
            rotation -= (float)Math.PI / 2f;
        }
        AI_019_Spears_GetExtensionHitbox(out var _);
        if (type == 878 || type == 879)
        {
            float num3 = 6f;
            float num4 = 0.8f;
            float num5 = Vector2.Dot(velocity.SafeNormalize(Vector2.UnitX * (float)player.direction), player.velocity.SafeNormalize(Vector2.UnitX * (float)player.direction));
            float num6 = ((Vector2)(ref player.velocity)).Length();
            if (num6 > num3 && num5 > num4)
            {
                int num7 = 8;
                if (num6 > num3 + 1f)
                {
                    num7 = 5;
                }
                if (num6 > num3 + 2f)
                {
                    num7 = 2;
                }
                int num8 = 14;
                int num9 = 27;
                int num10 = 4;
                if (type == 879)
                {
                    num8 = 43;
                    num9 = 57;
                }
                if (Main.rand.Next(num7 + 3) == 0)
                {
                    Dust.NewDust(base.Center - new Vector2((float)num10, (float)num10), num10 * 2, num10 * 2, num8, 0f, 0f, 150, default(Color), 1.4f);
                }
                if (Main.rand.Next(num7) == 0)
                {
                    int num11 = Dust.NewDust(base.Center - new Vector2((float)num10, (float)num10), num10 * 2, num10 * 2, num9, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.2f);
                    Main.dust[num11].noGravity = true;
                    Dust obj2 = Main.dust[num11];
                    obj2.velocity *= 0.25f;
                    num11 = Dust.NewDust(base.Center - new Vector2((float)num10, (float)num10), num10 * 2, num10 * 2, num9, 0f, 0f, 150, default(Color), 1.4f);
                    Dust obj3 = Main.dust[num11];
                    obj3.velocity *= 0.25f;
                }
            }
        }
        if (type == 46)
        {
            if (Main.rand.Next(5) == 0)
            {
                Dust.NewDust(position, width, height, 14, 0f, 0f, 150, default(Color), 1.4f);
            }
            int num13 = Dust.NewDust(position, width, height, 27, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.2f);
            Main.dust[num13].noGravity = true;
            Dust obj4 = Main.dust[num13];
            obj4.velocity /= 2f;
            num13 = Dust.NewDust(position - velocity * 2f, width, height, 27, 0f, 0f, 150, default(Color), 1.4f);
            Dust obj5 = Main.dust[num13];
            obj5.velocity /= 5f;
        }
        if (type == 730)
        {
            if (Main.rand.Next(5) == 0)
            {
                Dust dust = Dust.NewDustDirect(position, width, height, 226, 0f, 0f, 150, default(Color), 0.7f);
                dust.noGravity = true;
                dust.velocity *= 1.4f;
            }
            if (Main.rand.Next(5) == 0)
            {
                Dust.NewDustDirect(position, width, height, 226, 0f, 0f, 150, default(Color), 0.5f).velocity.Y -= 0.5f;
            }
        }
        else if (type == 105)
        {
            if (Main.rand.Next(3) == 0)
            {
                int num14 = Dust.NewDust(position, width, height, 57, velocity.X * 0.2f, velocity.Y * 0.2f, 200, default(Color), 1.2f);
                Dust obj6 = Main.dust[num14];
                obj6.velocity += velocity * 0.3f;
                Dust obj7 = Main.dust[num14];
                obj7.velocity *= 0.2f;
            }
            if (Main.rand.Next(4) == 0)
            {
                int num15 = Dust.NewDust(position, width, height, 43, 0f, 0f, 254, default(Color), 0.3f);
                Dust obj8 = Main.dust[num15];
                obj8.velocity += velocity * 0.5f;
                Dust obj9 = Main.dust[num15];
                obj9.velocity *= 0.5f;
            }
        }
        else if (type == 153)
        {
            int num16 = Dust.NewDust(position - velocity * 3f, width, height, 115, velocity.X * 0.4f, velocity.Y * 0.4f, 140);
            Main.dust[num16].noGravity = true;
            Main.dust[num16].fadeIn = 1.25f;
            Dust obj10 = Main.dust[num16];
            obj10.velocity *= 0.25f;
        }
        if (type == 342)
        {
            Lighting.AddLight(base.Center, 0.65f, 0.9f, 1f);
            if (timeLeft % 2 == 0)
            {
                int num17 = 10;
                int num18 = Dust.NewDust(position - velocity * 3f - new Vector2((float)num17, (float)num17), width + num17 * 2, height + num17 * 2, 135, velocity.X * 0.4f, velocity.Y * 0.4f, 50, default(Color), 1.2f);
                Dust obj11 = Main.dust[num18];
                obj11.velocity *= 0.5f;
                Dust obj12 = Main.dust[num18];
                obj12.velocity += velocity * 0.25f;
            }
        }
        ai[0] += 1f;
        bool flag3 = ai[0] >= (float)itemAnimationMax;
        if (flag2)
        {
            flag3 &= !player.channel;
        }
        if (flag3)
        {
            Kill();
        }
    }
References Terraria.Lighting.AddLight(), Terraria.Collision.CanHit(), Terraria.Player.channel, Terraria.Entity.direction, Terraria.Main.dust, Terraria.Entity.height, Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, Terraria.Player.MatchItemTimeToItemAnimation(), Terraria.Player.MountedCenter, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Main.player, Terraria.Entity.position, Terraria.Main.rand, Terraria.Player.RotatedRelativePoint(), Terraria.Player.SetDummyItemTime(), Terraria.Entity.velocity, and Terraria.Entity.width.