TModLoader: Terraria.Projectile.AI_182_FinalFractal
AI_182_FinalFractal()
void Terraria.Projectile.AI_182_FinalFractal () inline private
Definition at line 44658 of file Projectile.cs.
    {
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_021a: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0237: Unknown result type (might be due to invalid IL or missing references)
        //IL_0239: Unknown result type (might be due to invalid IL or missing references)
        //IL_023b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0350: Unknown result type (might be due to invalid IL or missing references)
        //IL_0352: Unknown result type (might be due to invalid IL or missing references)
        //IL_035b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_037e: Unknown result type (might be due to invalid IL or missing references)
        //IL_039e: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03db: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0400: Unknown result type (might be due to invalid IL or missing references)
        //IL_040a: Unknown result type (might be due to invalid IL or missing references)
        if (type == 933 && localAI[1] == 0f)
        {
            localAI[1] = 1f;
            SoundEngine.PlaySound(in SoundID.Item169, base.Center);
        }
        Player player = Main.player[owner];
        Vector2 mountedCenter = player.MountedCenter;
        float lerpValue = Utils.GetLerpValue(900f, 0f, ((Vector2)(ref velocity)).Length() * 2f, clamped: true);
        float num = MathHelper.Lerp(0.7f, 2f, lerpValue);
        localAI[0] += num;
        if (localAI[0] >= 120f)
        {
            Kill();
            return;
        }
        float lerpValue2 = Utils.GetLerpValue(0f, 1f, localAI[0] / 60f, clamped: true);
        float num11 = localAI[0] / 60f;
        float num4 = ai[0];
        float num5 = velocity.ToRotation();
        float num6 = (float)Math.PI;
        float num7 = ((velocity.X > 0f) ? 1 : (-1));
        float num8 = num6 + num7 * lerpValue2 * ((float)Math.PI * 2f);
        float num9 = ((Vector2)(ref velocity)).Length() + Utils.GetLerpValue(0.5f, 1f, lerpValue2, clamped: true) * 40f;
        float num10 = 60f;
        if (num9 < num10)
        {
            num9 = num10;
        }
        Vector2 val = mountedCenter + velocity;
        Vector2 spinningpoint = Utils.RotatedBy(new Vector2(1f, 0f), num8) * new Vector2(num9, num4 * MathHelper.Lerp(2f, 1f, lerpValue));
        Vector2 vector2 = val + spinningpoint.RotatedBy(num5);
        Vector2 vector3 = (1f - Utils.GetLerpValue(0f, 0.5f, lerpValue2, clamped: true)) * new Vector2((float)((velocity.X > 0f) ? 1 : (-1)) * (0f - num9) * 0.1f, (0f - ai[0]) * 0.3f);
        float num2 = num8 + num5;
        rotation = num2 + (float)Math.PI / 2f;
        base.Center = vector2 + vector3;
        spriteDirection = (direction = ((velocity.X > 0f) ? 1 : (-1)));
        if (num4 < 0f)
        {
            rotation = num6 + num7 * lerpValue2 * ((float)Math.PI * -2f) + num5;
            rotation += (float)Math.PI / 2f;
            spriteDirection = (direction = ((!(velocity.X > 0f)) ? 1 : (-1)));
        }
        if (num11 < 1f)
        {
            FinalFractalHelper.FinalFractalProfile finalFractalProfile = FinalFractalHelper.GetFinalFractalProfile((int)ai[1]);
            Vector2 vector4 = (rotation - (float)Math.PI / 2f).ToRotationVector2();
            Vector2 center = base.Center;
            int num3 = 1 + (int)(((Vector2)(ref velocity)).Length() / 100f);
            num3 = (int)((float)num3 * Utils.GetLerpValue(0f, 0.5f, lerpValue2, clamped: true) * Utils.GetLerpValue(1f, 0.5f, lerpValue2, clamped: true));
            if (num3 < 1)
            {
                num3 = 1;
            }
            for (int i = 0; i < num3; i++)
            {
                finalFractalProfile.dustMethod(center + vector4 * finalFractalProfile.trailWidth * MathHelper.Lerp(0.5f, 1f, Main.rand.NextFloat()), rotation - (float)Math.PI / 2f + (float)Math.PI / 2f * (float)spriteDirection, player.velocity);
            }
            Vector3 vector5 = ((Color)(ref finalFractalProfile.trailColor)).ToVector3();
            Vector3 vector6 = Vector3.Lerp(Vector3.One, vector5, 0.7f);
            Lighting.AddLight(base.Center, vector5 * 0.5f * Opacity);
            Lighting.AddLight(mountedCenter, vector6 * Opacity * 0.15f);
        }
        Opacity = Utils.GetLerpValue(0f, 5f, localAI[0], clamped: true) * Utils.GetLerpValue(120f, 115f, localAI[0], clamped: true);
    }
References Terraria.Lighting.AddLight(), Terraria.Graphics.FinalFractalHelper.GetFinalFractalProfile(), Terraria.Utils.GetLerpValue(), Terraria.ID.SoundID.Item169, Terraria.Player.MountedCenter, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Utils.RotatedBy(), and Terraria.Entity.velocity.