TModLoader: Terraria.Projectile.Update
Update()
void Terraria.Projectile.Update (int i) inline
Definition at line 15676 of file Projectile.cs.
    {
        //IL_03f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0402: Unknown result type (might be due to invalid IL or missing references)
        //IL_04aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04de: Unknown result type (might be due to invalid IL or missing references)
        //IL_0502: Unknown result type (might be due to invalid IL or missing references)
        //IL_0511: Unknown result type (might be due to invalid IL or missing references)
        //IL_0643: Unknown result type (might be due to invalid IL or missing references)
        //IL_065c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1205: Unknown result type (might be due to invalid IL or missing references)
        //IL_120a: Unknown result type (might be due to invalid IL or missing references)
        //IL_121c: Unknown result type (might be due to invalid IL or missing references)
        //IL_12c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_12e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_12e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_131e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1342: Unknown result type (might be due to invalid IL or missing references)
        //IL_1348: Unknown result type (might be due to invalid IL or missing references)
        //IL_137d: Unknown result type (might be due to invalid IL or missing references)
        //IL_139e: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1625: Unknown result type (might be due to invalid IL or missing references)
        //IL_1637: Unknown result type (might be due to invalid IL or missing references)
        //IL_15a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_15ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_1414: Unknown result type (might be due to invalid IL or missing references)
        //IL_1438: Unknown result type (might be due to invalid IL or missing references)
        //IL_143e: Unknown result type (might be due to invalid IL or missing references)
        //IL_16be: Unknown result type (might be due to invalid IL or missing references)
        //IL_16c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1671: Unknown result type (might be due to invalid IL or missing references)
        //IL_1676: Unknown result type (might be due to invalid IL or missing references)
        //IL_168e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1693: Unknown result type (might be due to invalid IL or missing references)
        //IL_14b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_14db: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b47: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b58: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b62: Unknown result type (might be due to invalid IL or missing references)
        //IL_192a: Unknown result type (might be due to invalid IL or missing references)
        //IL_192f: Unknown result type (might be due to invalid IL or missing references)
        //IL_196f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1974: Unknown result type (might be due to invalid IL or missing references)
        //IL_16f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_16f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_170f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1714: Unknown result type (might be due to invalid IL or missing references)
        //IL_171a: Unknown result type (might be due to invalid IL or missing references)
        //IL_171f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1525: Unknown result type (might be due to invalid IL or missing references)
        //IL_1561: Unknown result type (might be due to invalid IL or missing references)
        //IL_1567: Unknown result type (might be due to invalid IL or missing references)
        //IL_19cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_19d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a11: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a16: Unknown result type (might be due to invalid IL or missing references)
        //IL_1807: Unknown result type (might be due to invalid IL or missing references)
        //IL_180c: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_110d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1113: Unknown result type (might be due to invalid IL or missing references)
        //IL_0baf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bce: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b87: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c14: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d44: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_07dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0805: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c71: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cb1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cc3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bc9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bce: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1002: Unknown result type (might be due to invalid IL or missing references)
        //IL_1008: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0efa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0993: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_1be8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bed: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bef: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bf4: Unknown result type (might be due to invalid IL or missing references)
        //IL_17b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_17c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_17c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e50: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e55: Unknown result type (might be due to invalid IL or missing references)
        //IL_090b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0910: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a62: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a67: Unknown result type (might be due to invalid IL or missing references)
        //IL_18a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_18ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_18b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_18bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_18c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ae0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1aed: Unknown result type (might be due to invalid IL or missing references)
        //IL_1af2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1af7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1afc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1aae: Unknown result type (might be due to invalid IL or missing references)
        //IL_1abd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac9: Unknown result type (might be due to invalid IL or missing references)
        if (!active)
        {
            return;
        }
        if (Main.netMode == 1 && (ProjectileID.Sets.IsAGolfBall[type] || type == 820))
        {
            int num = (int)(position.X + (float)(width / 2)) / 16;
            int num11 = (int)(position.Y + (float)(height / 2)) / 16;
            if (!Main.sectionManager.TileLoaded(num, num11))
            {
                return;
            }
        }
        numUpdates = extraUpdates;
        Vector2 vector = default(Vector2);
        Vector2 vector2 = default(Vector2);
        while (numUpdates >= 0)
        {
            numUpdates--;
            if (type == 640 && ai[1] > 0f)
            {
                ai[1] -= 1f;
                continue;
            }
            if (position.X <= Main.leftWorld || position.X + (float)width >= Main.rightWorld || position.Y <= Main.topWorld || position.Y + (float)height >= Main.bottomWorld)
            {
                active = false;
                return;
            }
            if (!noEnchantmentVisuals)
            {
                UpdateEnchantmentVisuals();
            }
            if (minion || sentry || ContinuouslyUpdateDamageStats)
            {
                Player player = Main.player[owner];
                damage = (int)player.GetTotalDamage(DamageType).ApplyTo(originalDamage);
                CritChance = (int)((float)OriginalCritChance + player.GetTotalCritChance(DamageType) + 5E-06f);
                ArmorPenetration = (int)((float)OriginalArmorPenetration + player.GetTotalArmorPenetration(DamageType) + 5E-06f);
            }
            if (minion && numUpdates == -1 && type != 625 && type != 628)
            {
                minionPos = Main.player[owner].numMinions;
                if (Main.player[owner].slotsMinions + minionSlots > (float)Main.player[owner].maxMinions && owner == Main.myPlayer)
                {
                    if ((type == 627 || type == 626) && owner == Main.myPlayer)
                    {
                        int byUUID = GetByUUID(owner, ai[0]);
                        if (byUUID != -1)
{
                            Projectile projectile = Main.projectile[byUUID];
                            if (projectile.type != 625)
{
                                projectile.localAI[1] = localAI[1];
                            }
                            projectile = Main.projectile[(int)localAI[1]];
                            projectile.ai[0] = ai[0];
                            projectile.ai[1] = 1f;
                            projectile.netUpdate = true;
                        }
                    }
                    Kill();
                }
                else
                {
                    Main.player[owner].numMinions++;
                    Main.player[owner].slotsMinions += minionSlots;
                }
            }
            float num22 = 1f + Math.Abs(velocity.X) / 3f;
            if (gfxOffY > 0f)
            {
                gfxOffY -= num22 * stepSpeed;
                if (gfxOffY < 0f)
                {
                    gfxOffY = 0f;
                }
            }
            else if (gfxOffY < 0f)
            {
                gfxOffY += num22 * stepSpeed;
                if (gfxOffY > 0f)
                {
                    gfxOffY = 0f;
                }
            }
            if (gfxOffY > 16f)
            {
                gfxOffY = 16f;
            }
            if (gfxOffY < -16f)
            {
                gfxOffY = -16f;
            }
            Vector2 wetVelocity = velocity;
            oldVelocity = velocity;
            whoAmI = i;
            if (soundDelay > 0)
            {
                soundDelay--;
            }
            netUpdate = false;
            for (int j = 0; j < 255; j++)
            {
                if (playerImmune[j] > 0)
                {
                    playerImmune[j]--;
                }
            }
            if (usesLocalNPCImmunity)
            {
                for (int k = 0; k < 200; k++)
                {
                    if (localNPCImmunity[k] > 0)
                    {
                        localNPCImmunity[k]--;
                    }
                }
            }
            AI();
            if (ShouldUseWindPhysics() && (double)base.Center.Y < Main.worldSurface * 16.0 && Main.tile[(int)base.Center.X / 16, (int)base.Center.Y / 16] != null && Main.tile[(int)base.Center.X / 16, (int)base.Center.Y / 16].wall == 0 && ((velocity.X > 0f && Main.windSpeedCurrent < 0f) || (velocity.X < 0f && Main.windSpeedCurrent > 0f) || Math.Abs(velocity.X) < Math.Abs(Main.windSpeedCurrent * Main.windPhysicsStrength) * 180f) && Math.Abs(velocity.X) < 16f)
            {
                velocity.X += Main.windSpeedCurrent * Main.windPhysicsStrength;
                MathHelper.Clamp(velocity.X, -16f, 16f);
            }
            if (owner < 255 && !Main.player[owner].active)
            {
                Kill();
            }
            if (type == 242 || type == 302 || type == 638)
            {
                wet = false;
            }
            int overrideWidth;
            if (!ignoreWater)
            {
                bool flag;
                bool flag2;
                try
                {
                    flag = Collision.LavaCollision(position, width, height);
                    flag2 = Collision.WetCollision(position, width, height);
                    if (flag)
                    {
                        lavaWet = true;
                    }
                    if (Collision.honey)
                    {
                        honeyWet = true;
                    }
                    if (Collision.shimmer)
                    {
                        shimmerWet = true;
                    }
                }
                catch
                {
                    active = false;
                    return;
                }
                if (wet && !lavaWet)
                {
                    if (type == 85 || type == 15 || type == 188)
                    {
                        Kill();
                    }
                    if (type == 2)
                    {
                        type = 1;
                        light = 0f;
                    }
                }
                if (type == 34)
                {
                    if (wet && !lavaWet)
                    {
                        Kill();
                    }
                    if (lavaWet)
                    {
                        flag2 = (wet = (lavaWet = false));
                    }
                }
                if (type == 80)
                {
                    flag2 = false;
                    wet = false;
                    if (flag && ai[0] >= 0f)
                    {
                        Kill();
                    }
                }
                if (flag2)
                {
                    if (type != 155 && wetCount == 0 && !wet)
                    {
                        if (!flag)
{
                            if (shimmerWet)
{
                                for (int l = 0; l < 10; l++)
{
                                    int num28 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 308);
                                    Main.dust[num28].velocity.Y -= 4f;
                                    Main.dust[num28].velocity.X *= 2.5f;
                                    Main.dust[num28].scale = 1.3f;
                                    Main.dust[num28].noGravity = true;
                                    overrideWidth = Main.rand.Next(6);
                                    switch (overrideWidth)
{
                                    case 0:
                                        Main.dust[num28].color = new Color(255, 255, 210);
                                        break;
                                    case 1:
                                        Main.dust[num28].color = new Color(190, 245, 255);
                                        break;
                                    case 2:
                                        Main.dust[num28].color = new Color(255, 150, 255);
                                        break;
                                    default:
                                        Main.dust[num28].color = new Color(190, 175, 255);
                                        break;
                                    }
                                    SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 4);
                                }
                            }
                            else if (honeyWet)
{
                                for (int m = 0; m < 10; m++)
{
                                    int num29 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 152);
                                    Main.dust[num29].velocity.Y -= 1f;
                                    Main.dust[num29].velocity.X *= 2.5f;
                                    Main.dust[num29].scale = 1.3f;
                                    Main.dust[num29].alpha = 100;
                                    Main.dust[num29].noGravity = true;
                                }
                                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                            }
                            else
{
                                for (int n = 0; n < 10; n++)
{
                                    int num30 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, Dust.dustWater());
                                    Main.dust[num30].velocity.Y -= 4f;
                                    Main.dust[num30].velocity.X *= 2.5f;
                                    Main.dust[num30].scale = 1.3f;
                                    Main.dust[num30].alpha = 100;
                                    Main.dust[num30].noGravity = true;
                                }
                                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                            }
                        }
                        else
{
                            for (int num31 = 0; num31 < 10; num31++)
{
                                int num32 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 35);
                                Main.dust[num32].velocity.Y -= 1.5f;
                                Main.dust[num32].velocity.X *= 2.5f;
                                Main.dust[num32].scale = 1.3f;
                                Main.dust[num32].alpha = 100;
                                Main.dust[num32].noGravity = true;
                            }
                            SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                        }
                    }
                    wet = true;
                }
                else if (wet)
                {
                    wet = false;
                    if (type == 155)
                    {
                        velocity.Y *= 0.5f;
                    }
                    else if (wetCount == 0)
                    {
                        wetCount = 10;
                        if (!lavaWet)
{
                            if (shimmerWet)
{
                                for (int num33 = 0; num33 < 10; num33++)
{
                                    int num2 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 308);
                                    Main.dust[num2].velocity.Y -= 4f;
                                    Main.dust[num2].velocity.X *= 2.5f;
                                    Main.dust[num2].scale = 1.3f;
                                    Main.dust[num2].noGravity = true;
                                    overrideWidth = Main.rand.Next(6);
                                    switch (overrideWidth)
{
                                    case 0:
                                        Main.dust[num2].color = new Color(255, 255, 210);
                                        break;
                                    case 1:
                                        Main.dust[num2].color = new Color(190, 245, 255);
                                        break;
                                    case 2:
                                        Main.dust[num2].color = new Color(255, 150, 255);
                                        break;
                                    default:
                                        Main.dust[num2].color = new Color(190, 175, 255);
                                        break;
                                    }
                                    SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 5);
                                }
                            }
                            else if (honeyWet)
{
                                for (int num3 = 0; num3 < 10; num3++)
{
                                    int num4 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 152);
                                    Main.dust[num4].velocity.Y -= 1f;
                                    Main.dust[num4].velocity.X *= 2.5f;
                                    Main.dust[num4].scale = 1.3f;
                                    Main.dust[num4].alpha = 100;
                                    Main.dust[num4].noGravity = true;
                                }
                                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                            }
                            else
{
                                for (int num5 = 0; num5 < 10; num5++)
{
                                    int num6 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2)), width + 12, 24, Dust.dustWater());
                                    Main.dust[num6].velocity.Y -= 4f;
                                    Main.dust[num6].velocity.X *= 2.5f;
                                    Main.dust[num6].scale = 1.3f;
                                    Main.dust[num6].alpha = 100;
                                    Main.dust[num6].noGravity = true;
                                }
                                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                            }
                        }
                        else
{
                            for (int num7 = 0; num7 < 10; num7++)
{
                                int num8 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 35);
                                Main.dust[num8].velocity.Y -= 1.5f;
                                Main.dust[num8].velocity.X *= 2.5f;
                                Main.dust[num8].scale = 1.3f;
                                Main.dust[num8].alpha = 100;
                                Main.dust[num8].noGravity = true;
                            }
                            SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                        }
                    }
                }
                if (!wet)
                {
                    lavaWet = false;
                    honeyWet = false;
                    shimmerWet = false;
                }
                if (wetCount > 0)
                {
                    wetCount--;
                }
            }
            if (shimmerWet)
            {
                Shimmer();
            }
            oldPosition = position;
            oldDirection = direction;
            HandleMovement(wetVelocity, out overrideWidth, out var overrideHeight);
            if (AutomaticallyChangesDirection())
            {
                if (velocity.X < 0f)
                {
                    direction = -1;
                }
                else
                {
                    direction = 1;
                }
            }
            if (!active)
            {
                return;
            }
            ProjLight();
            if (!npcProj && friendly && Main.player[owner].magicQuiver && extraUpdates < 1 && arrow)
            {
                extraUpdates = 1;
            }
            if (type == 2 || type == 82)
            {
                Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100);
            }
            else if (type == 172)
            {
                Dust.NewDust(new Vector2(position.X, position.Y), width, height, 135, 0f, 0f, 100);
            }
            else if (type == 103)
            {
                int num9 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 75, 0f, 0f, 100);
                if (Main.rand.Next(2) == 0)
                {
                    Main.dust[num9].noGravity = true;
                    Main.dust[num9].scale *= 2f;
                }
            }
            else if (type == 278)
            {
                int num10 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 169, 0f, 0f, 100);
                if (Main.rand.Next(2) == 0)
                {
                    Main.dust[num10].noGravity = true;
                    Main.dust[num10].scale *= 1.5f;
                }
            }
            else if (type == 4)
            {
                if (Main.rand.Next(5) == 0)
                {
                    Dust.NewDust(new Vector2(position.X, position.Y), width, height, 14, 0f, 0f, 150, default(Color), 1.1f);
                }
            }
            else if (type == 5)
            {
                overrideHeight = Main.rand.Next(3);
                Dust.NewDust(Type: overrideHeight switch
                {
                    0 => 15,
                    1 => 57,
                    _ => 58,
                }, Position: position, Width: width, Height: height, SpeedX: velocity.X * 0.5f, SpeedY: velocity.Y * 0.5f, Alpha: 150, newColor: default(Color), Scale: 1.2f);
            }
            Damage();
            if (type == 434 && localAI[0] == 0f && numUpdates == 0)
            {
                extraUpdates = 1;
                velocity = Vector2.Zero;
                localAI[0] = 1f;
                localAI[1] = 0.9999f;
                netUpdate = true;
            }
            if (Main.netMode != 1 && (type == 99 || type == 1013 || type == 655 || type == 727 || type == 1014 || type == 1021))
            {
                Collision.SwitchTiles(position, width, height, oldPosition, 3);
            }
            if (ProjectileID.Sets.TrailingMode[type] == 0)
            {
                for (int num12 = oldPos.Length - 1; num12 > 0; num12--)
                {
                    oldPos[num12] = oldPos[num12 - 1];
                }
                oldPos[0] = position;
            }
            else if (ProjectileID.Sets.TrailingMode[type] == 1)
            {
                if (frameCounter == 0 || oldPos[0] == Vector2.Zero)
                {
                    for (int num13 = oldPos.Length - 1; num13 > 0; num13--)
                    {
                        oldPos[num13] = oldPos[num13 - 1];
                    }
                    oldPos[0] = position;
                    if (velocity == Vector2.Zero && type == 466)
                    {
                        float num14 = rotation + (float)Math.PI / 2f + ((Main.rand.Next(2) == 1) ? (-1f) : 1f) * ((float)Math.PI / 2f);
                        float num15 = (float)Main.rand.NextDouble() * 2f + 2f;
                        ((Vector2)(ref vector))._002Ector((float)Math.Cos(num14) * num15, (float)Math.Sin(num14) * num15);
                        int num16 = Dust.NewDust(oldPos[oldPos.Length - 1], 0, 0, 229, vector.X, vector.Y);
                        Main.dust[num16].noGravity = true;
                        Main.dust[num16].scale = 1.7f;
                    }
                    if (velocity == Vector2.Zero && type == 580)
                    {
                        float num17 = rotation + (float)Math.PI / 2f + ((Main.rand.Next(2) == 1) ? (-1f) : 1f) * ((float)Math.PI / 2f);
                        float num18 = (float)Main.rand.NextDouble() * 2f + 2f;
                        ((Vector2)(ref vector2))._002Ector((float)Math.Cos(num17) * num18, (float)Math.Sin(num17) * num18);
                        int num19 = Dust.NewDust(oldPos[oldPos.Length - 1], 0, 0, 229, vector2.X, vector2.Y);
                        Main.dust[num19].noGravity = true;
                        Main.dust[num19].scale = 1.7f;
                    }
                }
            }
            else if (ProjectileID.Sets.TrailingMode[type] == 2)
            {
                for (int num20 = oldPos.Length - 1; num20 > 0; num20--)
                {
                    oldPos[num20] = oldPos[num20 - 1];
                    oldRot[num20] = oldRot[num20 - 1];
                    oldSpriteDirection[num20] = oldSpriteDirection[num20 - 1];
                }
                oldPos[0] = position;
                oldRot[0] = rotation;
                oldSpriteDirection[0] = spriteDirection;
            }
            else if (ProjectileID.Sets.TrailingMode[type] == 3)
            {
                for (int num21 = oldPos.Length - 1; num21 > 0; num21--)
                {
                    oldPos[num21] = oldPos[num21 - 1];
                    oldRot[num21] = oldRot[num21 - 1];
                    oldSpriteDirection[num21] = oldSpriteDirection[num21 - 1];
                }
                oldPos[0] = position;
                oldRot[0] = rotation;
                oldSpriteDirection[0] = spriteDirection;
                float amount = 0.65f;
                int num23 = 1;
                for (int num24 = 0; num24 < num23; num24++)
                {
                    for (int num25 = oldPos.Length - 1; num25 > 0; num25--)
                    {
                        if (!(oldPos[num25] == Vector2.Zero))
{
                            if (oldPos[num25].Distance(oldPos[num25 - 1]) > 2f)
{
                                oldPos[num25] = Vector2.Lerp(oldPos[num25], oldPos[num25 - 1], amount);
                            }
                            oldRot[num25] = (oldPos[num25 - 1] - oldPos[num25]).SafeNormalize(Vector2.Zero).ToRotation();
                        }
                    }
                }
            }
            else if (ProjectileID.Sets.TrailingMode[type] == 4)
            {
                Vector2 vector3 = Main.player[owner].position - Main.player[owner].oldPosition;
                for (int num26 = oldPos.Length - 1; num26 > 0; num26--)
                {
                    oldPos[num26] = oldPos[num26 - 1];
                    oldRot[num26] = oldRot[num26 - 1];
                    oldSpriteDirection[num26] = oldSpriteDirection[num26 - 1];
                    if (numUpdates == 0 && oldPos[num26] != Vector2.Zero)
                    {
                        ref Vector2 reference = ref oldPos[num26];
                        reference += vector3;
                    }
                }
                oldPos[0] = position;
                oldRot[0] = rotation;
                oldSpriteDirection[0] = spriteDirection;
            }
            else if (ProjectileID.Sets.TrailingMode[type] == 5)
            {
                for (int num27 = oldPos.Length - 1; num27 > 0; num27--)
                {
                    oldPos[num27] = oldPos[num27 - 1];
                    oldRot[num27] = oldRot[num27 - 1];
                    oldSpriteDirection[num27] = oldSpriteDirection[num27 - 1];
                }
                oldPos[0] = position;
                oldRot[0] = velocity.ToRotation();
                oldSpriteDirection[0] = spriteDirection;
            }
            if (ProjectileID.Sets.IsADD2Turret[type] && DD2Event.Ongoing)
            {
                timeLeft++;
            }
            timeLeft--;
            if (timeLeft <= 0)
            {
                Kill();
            }
            if (penetrate == 0)
            {
                Kill();
            }
            if (!active || owner != Main.myPlayer)
            {
                continue;
            }
            if (netUpdate2)
            {
                netUpdate = true;
            }
            if (!active)
            {
                netSpam = 0;
            }
            if (netUpdate)
            {
                if (netSpam < 60)
                {
                    netSpam += 5;
                    NetMessage.SendData(27, -1, -1, null, i);
                    netUpdate2 = false;
                }
                else
                {
                    netUpdate2 = true;
                }
            }
            if (netSpam > 0)
            {
                netSpam--;
            }
        }
        netUpdate = false;
    }
References Terraria.Entity.active, Terraria.Projectile.ai, Terraria.Projectile.AI(), Terraria.Dust.alpha, Terraria.ModLoader.StatModifier.ApplyTo(), Terraria.Projectile.ArmorPenetration, Terraria.Projectile.arrow, Terraria.Projectile.AutomaticallyChangesDirection(), Terraria.Main.bottomWorld, Terraria.Dust.color, Terraria.Projectile.ContinuouslyUpdateDamageStats, Terraria.Projectile.CritChance, Terraria.Projectile.damage, Terraria.Projectile.Damage(), Terraria.Projectile.DamageType, Terraria.Entity.direction, Terraria.Entity.Distance(), Terraria.Main.dust, Terraria.Dust.dustWater(), Terraria.Projectile.extraUpdates, Terraria.Projectile.frameCounter, Terraria.Projectile.friendly, Terraria.Projectile.GetByUUID(), Terraria.Player.GetTotalArmorPenetration(), Terraria.Player.GetTotalCritChance(), Terraria.Player.GetTotalDamage(), Terraria.Projectile.gfxOffY, Terraria.Projectile.HandleMovement(), Terraria.Entity.height, Terraria.Collision.honey, Terraria.Entity.honeyWet, Terraria.Projectile.ignoreWater, Terraria.ID.ProjectileID.Sets.IsADD2Turret, Terraria.ID.ProjectileID.Sets.IsAGolfBall, Terraria.Projectile.Kill(), Terraria.Collision.LavaCollision(), Terraria.Entity.lavaWet, Terraria.Main.leftWorld, Terraria.Projectile.light, Terraria.Projectile.localAI, Terraria.Projectile.localNPCImmunity, Terraria.Player.magicQuiver, Terraria.Player.maxMinions, Terraria.Projectile.minion, Terraria.Projectile.minionPos, Terraria.Projectile.minionSlots, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.netSpam, Terraria.Projectile.netUpdate, Terraria.Projectile.netUpdate2, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.Projectile.noEnchantmentVisuals, Terraria.Dust.noGravity, Terraria.Projectile.npcProj, Terraria.Player.numMinions, Terraria.Projectile.numUpdates, Terraria.Entity.oldDirection, Terraria.Projectile.oldPos, Terraria.Entity.oldPosition, Terraria.Projectile.oldRot, Terraria.Projectile.oldSpriteDirection, Terraria.Entity.oldVelocity, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Projectile.OriginalArmorPenetration, Terraria.Projectile.OriginalCritChance, Terraria.Projectile.originalDamage, Terraria.Projectile.owner, Terraria.Projectile.penetrate, Terraria.Main.player, Terraria.Projectile.playerImmune, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.projectile, Terraria.Projectile.ProjLight(), Terraria.Main.rand, Terraria.Projectile.rotation, Terraria.Dust.scale, Terraria.Main.sectionManager, Terraria.NetMessage.SendData(), Terraria.Projectile.sentry, Terraria.Collision.shimmer, Terraria.Projectile.Shimmer(), Terraria.Entity.shimmerWet, Terraria.Projectile.ShouldUseWindPhysics(), Terraria.Player.slotsMinions, Terraria.Projectile.soundDelay, Terraria.Projectile.spriteDirection, Terraria.Projectile.stepSpeed, Terraria.Collision.SwitchTiles(), Terraria.Main.tile, Terraria.WorldSections.TileLoaded(), Terraria.Projectile.timeLeft, Terraria.ID.ProjectileID.Sets.TrailingMode, Terraria.Projectile.type, Terraria.Projectile.Type, Terraria.Projectile.UpdateEnchantmentVisuals(), Terraria.Projectile.usesLocalNPCImmunity, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Collision.WetCollision(), Terraria.Entity.wetCount, Terraria.Entity.whoAmI, Terraria.Entity.width, Terraria.Main.windPhysicsStrength, Terraria.Main.windSpeedCurrent, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DoUpdateInWorld(), and Terraria.Main.DrawWallOfStars().