TModLoader: Terraria.Projectile.AI_151_SuperStar
AI_151_SuperStar()
void Terraria.Projectile.AI_151_SuperStar () inline private
Definition at line 20999 of file Projectile.cs.
    {
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        alpha -= 10;
        int num = 100;
        if (alpha < num)
        {
            alpha = num;
        }
        if (soundDelay == 0)
        {
            soundDelay = 20 + Main.rand.Next(40);
            SoundEngine.PlaySound(in SoundID.Item9, position);
        }
        rotation += (Math.Abs(velocity.X) + Math.Abs(velocity.Y)) * 0.005f * (float)direction;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)Main.screenWidth, (float)Main.screenHeight);
        Rectangle hitbox = base.Hitbox;
        if (((Rectangle)(ref hitbox)).Intersects(Utils.CenteredRectangle(Main.screenPosition + vector / 2f, vector + new Vector2(400f))) && Main.rand.Next(6) == 0)
        {
            Gore.NewGore(position, velocity * 0.2f, Utils.SelectRandom<int>(Main.rand, 16, 17, 17, 17));
        }
        for (int i = 0; i < 2; i++)
        {
            if (Main.rand.Next(8) == 0)
            {
                int num2 = 228;
                Dust dust = Dust.NewDustDirect(position, width, height, num2, 0f, 0f, 127);
                dust.velocity *= 0.25f;
                dust.scale = 1.3f;
                dust.noGravity = true;
                dust.velocity += velocity.RotatedBy((float)Math.PI / 8f * (1f - (float)(2 * i))) * 0.2f;
            }
        }
    }
References Terraria.Projectile.alpha, Terraria.Utils.CenteredRectangle(), Terraria.Entity.direction, Terraria.Entity.height, Terraria.ID.SoundID.Item9, Terraria.Dust.NewDustDirect(), Terraria.Gore.NewGore(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Projectile.rotation, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Projectile.soundDelay, Terraria.Entity.velocity, and Terraria.Entity.width.