TModLoader: Terraria.Projectile.AI_153_ToiletPop
AI_153_ToiletPop()
void Terraria.Projectile.AI_153_ToiletPop () inline private
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        Vector2 center = base.Center;
        float speedY = -2f;
        int num = 0;
        int num2 = 0;
        if (ai[0] == 0f)
        {
            num = 6;
            num2 = 1;
        }
        else
        {
            if (!(ai[0] <= 10f))
            {
                Kill();
                return;
            }
            if (Main.rand.Next(5) == 0)
            {
                num2 = 1;
            }
            num = 2;
        }
        ai[0] += 1f;
        for (int i = 0; i < num; i++)
        {
            Dust dust = Dust.NewDustDirect(center, 3, 6, 216, 0f, speedY);
            dust.velocity.X *= 0.5f;
            dust.velocity.Y = 0f - Math.Abs(dust.velocity.Y);
            dust.position -= dust.velocity;
            dust.scale = 0.8f;
        }
        for (int j = 0; j < num2; j++)
        {
            Gore gore = Gore.NewGoreDirect(center, Vector2.UnitY * -3f + Main.rand.NextVector2Circular(1f, 1f), Main.rand.Next(580, 583));
            gore.velocity.Y = 0f - Math.Abs(gore.velocity.Y);
        }
    }
References Terraria.Dust.NewDustDirect(), Terraria.Gore.NewGoreDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Dust.velocity, and Terraria.Gore.velocity.