TModLoader: Terraria.Projectile.AI_142_MonkStaffT2And3
AI_142_MonkStaffT2And3()
void Terraria.Projectile.AI_142_MonkStaffT2And3 () inline private
    {
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_041e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0489: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0500: Unknown result type (might be due to invalid IL or missing references)
        //IL_0502: Unknown result type (might be due to invalid IL or missing references)
        //IL_0511: Unknown result type (might be due to invalid IL or missing references)
        //IL_051b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0521: Unknown result type (might be due to invalid IL or missing references)
        //IL_0523: Unknown result type (might be due to invalid IL or missing references)
        //IL_0528: Unknown result type (might be due to invalid IL or missing references)
        //IL_052d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0532: Unknown result type (might be due to invalid IL or missing references)
        //IL_0537: Unknown result type (might be due to invalid IL or missing references)
        //IL_0538: Unknown result type (might be due to invalid IL or missing references)
        //IL_053f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0545: Unknown result type (might be due to invalid IL or missing references)
        //IL_0547: Unknown result type (might be due to invalid IL or missing references)
        //IL_054c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0561: Unknown result type (might be due to invalid IL or missing references)
        //IL_056b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0571: Unknown result type (might be due to invalid IL or missing references)
        //IL_0573: Unknown result type (might be due to invalid IL or missing references)
        //IL_0578: Unknown result type (might be due to invalid IL or missing references)
        //IL_057d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0580: Unknown result type (might be due to invalid IL or missing references)
        //IL_0582: Unknown result type (might be due to invalid IL or missing references)
        //IL_0583: Unknown result type (might be due to invalid IL or missing references)
        //IL_0588: Unknown result type (might be due to invalid IL or missing references)
        //IL_058d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_0137: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0140: Unknown result type (might be due to invalid IL or missing references)
        //IL_0145: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05de: Unknown result type (might be due to invalid IL or missing references)
        //IL_05df: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0208: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_0218: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0220: Unknown result type (might be due to invalid IL or missing references)
        //IL_0225: Unknown result type (might be due to invalid IL or missing references)
        //IL_022a: Unknown result type (might be due to invalid IL or missing references)
        //IL_022f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0630: Unknown result type (might be due to invalid IL or missing references)
        //IL_0641: Unknown result type (might be due to invalid IL or missing references)
        //IL_0646: Unknown result type (might be due to invalid IL or missing references)
        //IL_064b: Unknown result type (might be due to invalid IL or missing references)
        //IL_064d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0654: Unknown result type (might be due to invalid IL or missing references)
        //IL_0659: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_025d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_0273: Unknown result type (might be due to invalid IL or missing references)
        //IL_0276: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        //IL_028a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0292: Unknown result type (might be due to invalid IL or missing references)
        //IL_0297: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0304: Unknown result type (might be due to invalid IL or missing references)
        //IL_0309: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0675: Unknown result type (might be due to invalid IL or missing references)
        //IL_0682: Unknown result type (might be due to invalid IL or missing references)
        //IL_0688: Unknown result type (might be due to invalid IL or missing references)
        //IL_068a: Unknown result type (might be due to invalid IL or missing references)
        //IL_068f: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0693: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06be: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0344: Unknown result type (might be due to invalid IL or missing references)
        //IL_0360: Unknown result type (might be due to invalid IL or missing references)
        //IL_0366: Unknown result type (might be due to invalid IL or missing references)
        //IL_0376: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_037e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0388: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0395: Unknown result type (might be due to invalid IL or missing references)
        //IL_039a: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0790: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f5: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        Vector2 vector = player.RotatedRelativePoint(player.MountedCenter);
        direction = player.direction;
        player.heldProj = whoAmI;
        base.Center = vector;
        if (player.dead)
        {
            Kill();
            return;
        }
        if (!player.frozen)
        {
            if (type == 699)
            {
                spriteDirection = (direction = player.direction);
                Vector2 vector2 = vector;
                alpha -= 127;
                if (alpha < 0)
                {
                    alpha = 0;
                }
                if (localAI[0] > 0f)
                {
                    localAI[0] -= 1f;
                }
                float num = (float)player.itemAnimation / (float)player.itemAnimationMax;
                float num6 = 1f - num;
                float num7 = velocity.ToRotation();
                float num8 = ((Vector2)(ref velocity)).Length();
                float num9 = 22f;
                Vector2 spinningpoint = Utils.RotatedBy(new Vector2(1f, 0f), (float)Math.PI + num6 * ((float)Math.PI * 2f)) * new Vector2(num8, ai[0]);
                position += spinningpoint.RotatedBy(num7) + Utils.RotatedBy(new Vector2(num8 + num9, 0f), num7);
                Vector2 target = vector2 + spinningpoint.RotatedBy(num7) + Utils.RotatedBy(new Vector2(num8 + num9 + 40f, 0f), num7);
                rotation = vector2.AngleTo(target) + (float)Math.PI / 4f * (float)player.direction;
                if (spriteDirection == -1)
                {
                    rotation += (float)Math.PI;
                }
                vector2.DirectionTo(base.Center);
                Vector2 vector3 = vector2.DirectionTo(target);
                Vector2 vector4 = velocity.SafeNormalize(Vector2.UnitY);
                float num10 = 2f;
                for (int i = 0; (float)i < num10; i++)
                {
                    Dust dust = Dust.NewDustDirect(base.Center, 14, 14, 228, 0f, 0f, 110);
                    dust.velocity = vector2.DirectionTo(dust.position) * 2f;
                    dust.position = base.Center + vector4.RotatedBy(num6 * ((float)Math.PI * 2f) * 2f + (float)i / num10 * ((float)Math.PI * 2f)) * 10f;
                    dust.scale = 1f + 0.6f * Main.rand.NextFloat();
                    dust.velocity += vector4 * 3f;
                    dust.noGravity = true;
                }
                for (int j = 0; j < 1; j++)
                {
                    if (Main.rand.Next(3) == 0)
                    {
                        Dust dust2 = Dust.NewDustDirect(base.Center, 20, 20, 228, 0f, 0f, 110);
                        dust2.velocity = vector2.DirectionTo(dust2.position) * 2f;
                        dust2.position = base.Center + vector3 * -110f;
                        dust2.scale = 0.45f + 0.4f * Main.rand.NextFloat();
                        dust2.fadeIn = 0.7f + 0.4f * Main.rand.NextFloat();
                        dust2.noGravity = true;
                        dust2.noLight = true;
                    }
                }
            }
            else if (type == 708)
            {
                Lighting.AddLight(player.Center, 0.75f, 0.9f, 1.15f);
                spriteDirection = (direction = player.direction);
                alpha -= 127;
                if (alpha < 0)
                {
                    alpha = 0;
                }
                float num11 = (float)player.itemAnimation / (float)player.itemAnimationMax;
                float num12 = 1f - num11;
                float num13 = velocity.ToRotation();
                float num2 = ((Vector2)(ref velocity)).Length();
                float num3 = 22f;
                Vector2 spinningpoint2 = Utils.RotatedBy(new Vector2(1f, 0f), (float)Math.PI + num12 * ((float)Math.PI * 2f)) * new Vector2(num2, ai[0]);
                position += spinningpoint2.RotatedBy(num13) + Utils.RotatedBy(new Vector2(num2 + num3, 0f), num13);
                Vector2 vector5 = vector + spinningpoint2.RotatedBy(num13) + Utils.RotatedBy(new Vector2(num2 + num3 + 40f, 0f), num13);
                rotation = (vector5 - vector).SafeNormalize(Vector2.UnitX).ToRotation() + (float)Math.PI / 4f * (float)player.direction;
                if (spriteDirection == -1)
                {
                    rotation += (float)Math.PI;
                }
                (base.Center - vector).SafeNormalize(Vector2.Zero);
                (vector5 - vector).SafeNormalize(Vector2.Zero);
                Vector2 vector6 = velocity.SafeNormalize(Vector2.UnitY);
                if ((player.itemAnimation == 2 || player.itemAnimation == 6 || player.itemAnimation == 10) && owner == Main.myPlayer)
                {
                    Vector2 vector7 = vector6 + Main.rand.NextVector2Square(-0.2f, 0.2f);
                    vector7 *= 12f;
                    switch (player.itemAnimation)
                    {
                    case 2:
                        vector7 = vector6.RotatedBy(0.3839724659919739);
                        break;
                    case 6:
                        vector7 = vector6.RotatedBy(-0.3839724659919739);
                        break;
                    case 10:
                        vector7 = vector6.RotatedBy(0.0);
                        break;
                    }
                    vector7 *= 10f + (float)Main.rand.Next(4);
                    NewProjectile(GetProjectileSource_FromThis(), base.Center, vector7, 709, damage, 0f, owner);
                }
                for (int k = 0; k < 3; k += 2)
                {
                    float num4 = 1f;
                    float num5 = 1f;
                    switch (k)
                    {
                    case 1:
                        num5 = -1f;
                        break;
                    case 2:
                        num5 = 1.25f;
                        num4 = 0.5f;
                        break;
                    case 3:
                        num5 = -1.25f;
                        num4 = 0.5f;
                        break;
                    }
                    if (Main.rand.Next(6) != 0)
                    {
                        num5 *= 1.2f;
                        Dust dust3 = Dust.NewDustDirect(position, width, height, 226, 0f, 0f, 100);
                        dust3.velocity = vector6 * (4f + 4f * Main.rand.NextFloat()) * num5 * num4;
                        dust3.noGravity = true;
                        dust3.noLight = true;
                        dust3.scale = 0.75f;
                        dust3.fadeIn = 0.8f;
                        dust3.customData = this;
                        if (Main.rand.Next(3) == 0)
{
                            dust3.noGravity = false;
                            dust3.fadeIn = 0f;
                        }
                    }
                }
            }
        }
        if (player.whoAmI == Main.myPlayer && player.itemAnimation <= 2)
        {
            Kill();
            player.reuseDelay = 2;
        }
    }
References Terraria.Lighting.AddLight(), Terraria.Entity.Center, Terraria.Player.dead, Terraria.Entity.direction, Terraria.Player.frozen, Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, Terraria.Player.MountedCenter, Terraria.Main.myPlayer, Terraria.Dust.NewDustDirect(), Terraria.Main.player, Terraria.Dust.position, Terraria.Main.rand, Terraria.Utils.RotatedBy(), Terraria.Player.RotatedRelativePoint(), and Terraria.Entity.whoAmI.