TModLoader: Terraria.Projectile.FindTargetWithLineOfSight
FindTargetWithLineOfSight()
int Terraria.Projectile.FindTargetWithLineOfSight (float maxRange = 800f) inline
Finds the closest NPC to this projectile which can be targeted and which it has line of sight to.
Parameters
maxRange The maximum range at which this projectile should search out a target, measured in pixels.
Defaults to 800 (50 tiles). Each tile, for reference, measures out to be 16x16 pixels.
Returns
The index, in F:Terraria.Main.npc, of the closest targetable NPC.
    {
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        float num = maxRange;
        int result = -1;
        for (int i = 0; i < 200; i++)
        {
            NPC nPC = Main.npc[i];
            bool flag = nPC.CanBeChasedBy(this);
            if (localNPCImmunity[i] != 0)
            {
                flag = false;
            }
            if (flag)
            {
                float num2 = Distance(Main.npc[i].Center);
                if (num2 < num && Collision.CanHit(position, width, height, nPC.position, nPC.width, nPC.height))
                {
                    num = num2;
                    result = i;
                }
            }
        }
        return result;
    }
References Terraria.Collision.CanHit(), and Terraria.Main.npc.
Referenced by Terraria.Projectile.Damage(), and Terraria.Projectile.HandleMovement().