TModLoader: Terraria.Projectile.AI_195_JimsDrone
AI_195_JimsDrone()
void Terraria.Projectile.AI_195_JimsDrone () inline private
    {
        //IL_02af: Unknown result type (might be due to invalid IL or missing references)
        //IL_0266: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0403: Unknown result type (might be due to invalid IL or missing references)
        //IL_0342: Unknown result type (might be due to invalid IL or missing references)
        //IL_0347: Unknown result type (might be due to invalid IL or missing references)
        //IL_034b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0350: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0361: Unknown result type (might be due to invalid IL or missing references)
        //IL_0486: Unknown result type (might be due to invalid IL or missing references)
        //IL_048b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0495: Unknown result type (might be due to invalid IL or missing references)
        //IL_0465: Unknown result type (might be due to invalid IL or missing references)
        //IL_047b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0480: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04de: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0503: Unknown result type (might be due to invalid IL or missing references)
        //IL_0507: Unknown result type (might be due to invalid IL or missing references)
        //IL_0511: Unknown result type (might be due to invalid IL or missing references)
        //IL_0513: Unknown result type (might be due to invalid IL or missing references)
        //IL_0630: Unknown result type (might be due to invalid IL or missing references)
        //IL_054e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0557: Unknown result type (might be due to invalid IL or missing references)
        //IL_055c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0575: Unknown result type (might be due to invalid IL or missing references)
        //IL_057a: Unknown result type (might be due to invalid IL or missing references)
        //IL_058e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0598: Unknown result type (might be due to invalid IL or missing references)
        //IL_059d: Unknown result type (might be due to invalid IL or missing references)
        //IL_059f: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05db: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e1: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        bool flag = false;
        if (player.dead)
        {
            flag = true;
        }
        if (owner == Main.myPlayer)
        {
            if (position.Y - (float)height <= (float)(16 * Main.offScreenRange / 2))
            {
                Kill();
                return;
            }
            if (player.HeldItem.type != 5451)
            {
                flag = true;
            }
            bool flag2 = player.gravDir == -1f;
            BitsByte bitsByte = (byte)0;
            Player.DirectionalInputSyncCache localInputCache = player.LocalInputCache;
            bitsByte[0] = localInputCache.controlLeft ^ flag2;
            bitsByte[1] = localInputCache.controlRight ^ flag2;
            bitsByte[2] = localInputCache.controlUp;
            bitsByte[3] = localInputCache.controlDown;
            float num = (int)(byte)bitsByte;
            if (ai[0] != num)
            {
                ai[0] = num;
                netUpdate = true;
            }
            Main.DroneCameraTracker.Track(this);
        }
        if (flag)
        {
            Kill();
            return;
        }
        BitsByte bitsByte2 = (byte)ai[0];
        rotation = ai[1];
        bool flag3 = bitsByte2[0];
        bool flag4 = bitsByte2[1];
        bool flag5 = bitsByte2[2];
        _ = bitsByte2[3];
        localAI[0] += 1f;
        if (!flag3 && !flag4)
        {
            localAI[0] = 0f;
        }
        bool flag6 = velocity.Y == 0f;
        int num3 = 0;
        if (!flag6)
        {
            num3 = 10;
        }
        if (flag5)
        {
            num3 = 100;
        }
        localAI[1] = MathHelper.Lerp(localAI[1], (float)num3, 0.2f);
        float num4 = Utils.Remap(localAI[0], 0f, 5f, 0f, 1f) * Utils.Remap(localAI[0], 5f, 15f, 1f, 0f);
        float num5 = Utils.Clamp(MathHelper.Max(Utils.Remap(localAI[1], 0f, 100f, 0f, 25f), num4 * 12f), 0f, 100f);
        ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[2]));
        if (activeSound == null && num5 != 0f)
        {
            localAI[2] = SoundEngine.PlayTrackedLoopedSound(in SoundID.JimsDrone, base.Center, new ProjectileAudioTracker(this).IsActiveAndInGame).ToFloat();
            activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[2]));
        }
        if (activeSound != null)
        {
            activeSound.Volume = num5;
            activeSound.Position = base.Center;
            activeSound.Pitch = Utils.Clamp(Utils.Remap(localAI[1], 0f, 100f, -1f, 1f) + num4, -1f, 1f);
        }
        float num6 = 0.15f;
        if (flag6)
        {
            rotation = MathHelper.WrapAngle(rotation) * 0.7f;
            velocity.X *= 0.97f;
            if (flag5)
            {
                Vector2 vector = (rotation - (float)Math.PI / 2f).ToRotationVector2();
                velocity += vector * 0.5f;
                num6 = 0.05f;
            }
        }
        else
        {
            float num7 = (float)Math.PI / 15f;
            num7 = Utils.Remap(localAI[0], 0f, 10f, num7 * 0.1f, num7);
            int num8 = flag4.ToInt() - flag3.ToInt();
            rotation += (float)num8 * num7;
            if (flag5)
            {
                Vector2 vector2 = (rotation - (float)Math.PI / 2f).ToRotationVector2();
                velocity.X *= 0.97f;
                velocity += vector2 * 0.5f;
            }
        }
        velocity.Y += num6;
        ai[1] = rotation;
        if (!flag5 && velocity.Y > 12f)
        {
            velocity.Y *= 0.95f;
        }
        if (((Vector2)(ref velocity)).Length() > 16f)
        {
            velocity *= 16f / ((Vector2)(ref velocity)).Length();
        }
        Lighting.AddLight(base.Center, Vector3.One * 0.3f);
        timeLeft = 2;
        if (!flag6)
        {
            Vector2 vector3 = position;
            float num9 = 0f;
            int num10 = 3;
            int num2 = 16 * num10;
            Vector2 vector4 = default(Vector2);
            for (int i = 0; i < num10; i++)
            {
                ((Vector2)(ref vector4))._002Ector(0f, 16f);
                Vector2 vector5 = Collision.TileCollision(vector3 + vector4 * (float)i, vector4, width, height);
                num9 += vector5.Y;
                if (vector5 != vector4)
                {
                    break;
                }
            }
            if (num9 != (float)num2)
            {
                for (int j = 0; j < 2; j++)
                {
                    if (!(Main.rand.NextFloat() < 0.66f))
                    {
                        Vector2 val = vector3 + new Vector2(0f, num9) + new Vector2((float)width / 2f, (float)height);
                        Vector2 value = Main.rand.NextVector2CircularEdge(2.5f, 1f) * 0.5f;
                        if (value.Y > 0f)
{
                            value.Y *= -1f;
                        }
                        Dust.NewDustPerfect(val, (Main.rand.Next(2) == 0) ? 31 : 16, value, 127);
                    }
                }
            }
        }
        if (Main.netMode == 2 && Main.player.IndexInRange(owner) && Main.player[owner].active)
        {
            RemoteClient.CheckSection(owner, position);
        }
    }
References Terraria.Lighting.AddLight(), Terraria.RemoteClient.CheckSection(), Terraria.Player.dead, Terraria.Main.DroneCameraTracker, Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.Player.HeldItem, Terraria.Audio.ProjectileAudioTracker.IsActiveAndInGame(), Terraria.ID.SoundID.JimsDrone, Terraria.Player.LocalInputCache, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDustPerfect(), Terraria.Main.offScreenRange, Terraria.Main.player, Terraria.Audio.SoundEngine.PlayTrackedLoopedSound(), Terraria.Main.rand, Terraria.Utils.Remap(), Terraria.Collision.TileCollision(), and Terraria.Item.type.