TModLoader: Terraria.Projectile.AI_186_PrincessWeapon
AI_186_PrincessWeapon()
void Terraria.Projectile.AI_186_PrincessWeapon () inline private
Definition at line 43981 of file Projectile.cs.
    {
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_0160: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_0198: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_0208: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_021e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_0236: Unknown result type (might be due to invalid IL or missing references)
        //IL_0287: Unknown result type (might be due to invalid IL or missing references)
        //IL_028f: Unknown result type (might be due to invalid IL or missing references)
        //IL_029c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02de: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0308: Unknown result type (might be due to invalid IL or missing references)
        //IL_030d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0312: Unknown result type (might be due to invalid IL or missing references)
        //IL_039a: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        //IL_03eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0406: Unknown result type (might be due to invalid IL or missing references)
        //IL_040b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0410: Unknown result type (might be due to invalid IL or missing references)
        //IL_0412: Unknown result type (might be due to invalid IL or missing references)
        //IL_0426: Unknown result type (might be due to invalid IL or missing references)
        //IL_043c: Unknown result type (might be due to invalid IL or missing references)
        //IL_043e: Unknown result type (might be due to invalid IL or missing references)
        //IL_048f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0497: Unknown result type (might be due to invalid IL or missing references)
        //IL_049e: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04da: Unknown result type (might be due to invalid IL or missing references)
        //IL_035f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0364: Unknown result type (might be due to invalid IL or missing references)
        //IL_0616: Unknown result type (might be due to invalid IL or missing references)
        //IL_0626: Unknown result type (might be due to invalid IL or missing references)
        //IL_062c: Unknown result type (might be due to invalid IL or missing references)
        //IL_062e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0633: Unknown result type (might be due to invalid IL or missing references)
        //IL_0635: Unknown result type (might be due to invalid IL or missing references)
        //IL_0641: Unknown result type (might be due to invalid IL or missing references)
        //IL_0648: Unknown result type (might be due to invalid IL or missing references)
        //IL_064d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0662: Unknown result type (might be due to invalid IL or missing references)
        //IL_0664: Unknown result type (might be due to invalid IL or missing references)
        //IL_066b: Unknown result type (might be due to invalid IL or missing references)
        //IL_066f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0674: Unknown result type (might be due to invalid IL or missing references)
        //IL_0697: Unknown result type (might be due to invalid IL or missing references)
        //IL_0699: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0563: Unknown result type (might be due to invalid IL or missing references)
        //IL_0581: Unknown result type (might be due to invalid IL or missing references)
        //IL_0587: Unknown result type (might be due to invalid IL or missing references)
        //IL_0589: Unknown result type (might be due to invalid IL or missing references)
        //IL_0598: Unknown result type (might be due to invalid IL or missing references)
        //IL_059d: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0527: Unknown result type (might be due to invalid IL or missing references)
        //IL_052c: Unknown result type (might be due to invalid IL or missing references)
        float num = 60f;
        ai[0] += 1f;
        if (ai[0] >= num)
        {
            Kill();
            return;
        }
        Opacity = Utils.Remap(ai[0], 0f, num, 1f, 0f);
        float num11 = ai[0] / num;
        float num12 = 1f - (1f - num11) * (1f - num11);
        float num13 = 1f - (1f - num12) * (1f - num12);
        float num18 = Utils.Remap(ai[0], num - 15f, num, 0f, 1f);
        float num14 = num18 * num18;
        float num15 = 1f - num14;
        scale = (0.4f + 0.6f * num13) * num15;
        float num16 = Utils.Remap(ai[0], 20f, num, 0f, 1f);
        float num17 = 1f - (1f - num16) * (1f - num16);
        float num2 = 1f - (1f - num17) * (1f - num17);
        localAI[0] = (0.4f + 0.6f * num2) * num15;
        int num3 = width / 2;
        Color newColor = Main.hslToRgb(0.92f, 1f, 0.5f) * Opacity;
        float num4 = 6f;
        float num5 = 2f;
        if (num11 < 0.9f)
        {
            for (int i = 0; i < 3; i++)
            {
                if (Main.rand.Next(2) == 0)
                {
                    Vector2 val = Vector2.UnitX.RotatedBy(Main.rand.NextFloat() * ((float)Math.PI * 2f));
                    Vector2 vector11 = val * ((float)num3 * scale);
                    Vector2 vector12 = base.Center + vector11;
                    Vector2 vector13 = val.RotatedBy(0.7853981852531433);
                    vector12 += vector13 * num4;
                    int num6 = Dust.NewDust(vector12, 0, 0, 267, 0f, 0f, 0, newColor);
                    Main.dust[num6].position = vector12;
                    Main.dust[num6].noGravity = true;
                    Main.dust[num6].scale = 0.3f;
                    Main.dust[num6].fadeIn = Main.rand.NextFloat() * 1.2f * scale;
                    Main.dust[num6].velocity = vector13 * scale * (0f - num5);
                    Main.dust[num6].scale *= scale;
                    Dust obj = Main.dust[num6];
                    obj.velocity += velocity * 0.5f;
                    Dust obj2 = Main.dust[num6];
                    obj2.position += Main.dust[num6].velocity * -5f;
                    if (num6 != 6000)
                    {
                        Dust dust = Dust.CloneDust(num6);
                        dust.scale /= 2f;
                        dust.fadeIn *= 0.85f;
                        dust.color = new Color(255, 255, 255, 255);
                    }
                }
            }
        }
        if (num11 < 0.9f)
        {
            for (int j = 0; j < 3; j++)
            {
                if (Main.rand.Next(2) == 0)
                {
                    Vector2 val2 = Vector2.UnitX.RotatedBy(Main.rand.NextFloat() * ((float)Math.PI * 2f));
                    Vector2 vector14 = val2 * ((float)num3 * scale);
                    Vector2 vector15 = base.Center + vector14;
                    Vector2 vector16 = val2.RotatedBy(0.7853981852531433);
                    vector15 += vector16 * (0f - num4);
                    int num7 = Dust.NewDust(vector15, 0, 0, 267, 0f, 0f, 0, newColor);
                    Main.dust[num7].position = vector15;
                    Main.dust[num7].noGravity = true;
                    Main.dust[num7].scale = 0.3f;
                    Main.dust[num7].fadeIn = Main.rand.NextFloat() * 1.2f * scale;
                    Main.dust[num7].velocity = vector16 * scale * num5;
                    Main.dust[num7].scale *= scale;
                    Main.dust[num7].velocity = velocity * 0.5f;
                    if (num7 != 6000)
                    {
                        Dust dust2 = Dust.CloneDust(num7);
                        dust2.scale /= 2f;
                        dust2.fadeIn *= 0.85f;
                        dust2.color = new Color(255, 255, 255, 255);
                    }
                }
            }
        }
        if (num11 < 0.95f)
        {
            for (float num8 = 0f; num8 < 0.8f; num8 += 1f)
            {
                if (Main.rand.Next(4) == 0)
                {
                    Vector2 vector17 = Vector2.UnitX.RotatedBy(Main.rand.NextFloat() * ((float)Math.PI * 2f) + (float)Math.PI / 2f) * ((float)num3 * scale);
                    Vector2 positionInWorld = base.Center + vector17;
                    ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.PrincessWeapon, new ParticleOrchestraSettings
                    {
                        PositionInWorld = positionInWorld,
                        MovementVector = velocity
                    }, owner);
                }
            }
        }
        if (ai[0] == num - 10f)
        {
            for (float num9 = 0f; num9 < 1f; num9 += 0.25f)
            {
                Vector2 vector10 = Vector2.UnitX.RotatedBy((float)Math.PI * 2f * num9);
                _ = vector10 * ((float)num3 * scale);
                Vector2 center = base.Center;
                float num10 = 1f;
                ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.PrincessWeapon, new ParticleOrchestraSettings
                {
                    PositionInWorld = center,
                    MovementVector = vector10 * num10
                }, owner);
                ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.PrincessWeapon, new ParticleOrchestraSettings
                {
                    PositionInWorld = center,
                    MovementVector = vector10 * num10 * 2f
                }, owner);
            }
        }
    }
References Terraria.Dust.CloneDust(), Terraria.Main.dust, Terraria.Main.hslToRgb(), Terraria.Dust.NewDust(), Terraria.Main.rand, Terraria.Utils.Remap(), and Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn().