TModLoader: Terraria.Projectile.AI_155_MysticSnakeCoil
AI_155_MysticSnakeCoil()
void Terraria.Projectile.AI_155_MysticSnakeCoil () inline private
    {
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0613: Unknown result type (might be due to invalid IL or missing references)
        //IL_0618: Unknown result type (might be due to invalid IL or missing references)
        //IL_061d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0621: Unknown result type (might be due to invalid IL or missing references)
        //IL_0634: Unknown result type (might be due to invalid IL or missing references)
        //IL_0645: Unknown result type (might be due to invalid IL or missing references)
        //IL_06bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_066a: Unknown result type (might be due to invalid IL or missing references)
        //IL_077a: Unknown result type (might be due to invalid IL or missing references)
        //IL_06af: Unknown result type (might be due to invalid IL or missing references)
        //IL_078f: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01de: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0712: Unknown result type (might be due to invalid IL or missing references)
        //IL_072c: Unknown result type (might be due to invalid IL or missing references)
        //IL_073d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0747: Unknown result type (might be due to invalid IL or missing references)
        //IL_074c: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0309: Unknown result type (might be due to invalid IL or missing references)
        //IL_0318: Unknown result type (might be due to invalid IL or missing references)
        //IL_031d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0337: Unknown result type (might be due to invalid IL or missing references)
        //IL_0348: Unknown result type (might be due to invalid IL or missing references)
        //IL_0352: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_0820: Unknown result type (might be due to invalid IL or missing references)
        //IL_0822: Unknown result type (might be due to invalid IL or missing references)
        //IL_040f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0414: Unknown result type (might be due to invalid IL or missing references)
        //IL_0419: Unknown result type (might be due to invalid IL or missing references)
        //IL_041d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0431: Unknown result type (might be due to invalid IL or missing references)
        //IL_0443: Unknown result type (might be due to invalid IL or missing references)
        //IL_044a: Unknown result type (might be due to invalid IL or missing references)
        //IL_045a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0465: Unknown result type (might be due to invalid IL or missing references)
        //IL_0477: Unknown result type (might be due to invalid IL or missing references)
        //IL_048e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0511: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_058f: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05da: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode != 1 && !Main.player[owner].active)
        {
            float num = ai[0];
            float y = position.Y;
            Point point = base.Center.ToTileCoordinates();
            Point end = default(Point);
            ((Point)(ref end))._002Ector(point.X, (int)y / 16);
            Point start = default(Point);
            ((Point)(ref start))._002Ector(point.X, (int)num / 16);
            AI_155_RemoveRope(start, end);
            Kill();
            return;
        }
        int num6 = 100;
        int num7 = 1800;
        if (ai[1] == 0f)
        {
            spriteDirection = ((!(Main.player[owner].Center.X > base.Center.X)) ? 1 : (-1));
            ai[1] = 1f;
            velocity.Y = -5f;
        }
        if (ai[1] == 1f)
        {
            localAI[1] += 1f;
            float num8 = Utils.Remap(localAI[1], 15f, 30f, 0f, 1f);
            int num9 = ((localAI[1] >= 60f) ? 1 : 0);
            velocity.Y = -3f * (1f - num8) + (float)(-32 * num9);
            velocity.Y = (int)velocity.Y;
            if (localAI[1] == 60f)
            {
                for (int i = 0; i < 30; i++)
                {
                    Dust dust = Dust.NewDustDirect(base.TopLeft + new Vector2(-6f, 0f), 24, 16, 27, 0f, 0f, 150, Color.Transparent, 0.6f);
                    dust.velocity *= 1f;
                    dust.velocity.X *= 0.5f;
                    dust.velocity.Y = -3f;
                    dust.fadeIn = 1.2f;
                    dust.noGravity = true;
                    dust.position.X += Main.rand.NextFloatDirection() * 8f;
                    dust.velocity = Utils.RotatedBy(new Vector2(0f, -1f), (float)Math.PI / 4f * Main.rand.NextFloatDirection() * 0f) * (Main.rand.NextFloatDirection() * 9f);
                    if (dust.velocity.Y < 0f)
                    {
                        dust.velocity.Y *= 1f + Main.rand.NextFloat() * 3f;
                    }
                }
            }
            bool flag = num8 > 0f && num9 <= 0;
            if ((Main.rand.Next(6) == 0 || num9 > 0) && !flag)
            {
                Dust dust2 = Dust.NewDustDirect(base.TopLeft + new Vector2(-6f, 0f), 24, 16, 27, 0f, 0f, 150, Color.Transparent, 0.6f);
                dust2.velocity *= 1f;
                dust2.velocity.X *= 0.5f;
                dust2.velocity.Y = -3f;
                dust2.fadeIn = 1.2f;
                dust2.noGravity = true;
            }
            alpha = Utils.Clamp(alpha - 5, 0, 255);
            if (++frameCounter >= 12)
            {
                frameCounter = 0;
                if (++frame >= 4)
                {
                    frame = 0;
                }
            }
            if (Main.myPlayer == owner)
            {
                float num10 = ai[0];
                float y2 = position.Y;
                Point point2 = base.Center.ToTileCoordinates();
                Point point3 = default(Point);
                ((Point)(ref point3))._002Ector(point2.X, (int)y2 / 16);
                Point point4 = default(Point);
                ((Point)(ref point4))._002Ector(point2.X, (int)num10 / 16);
                bool flag2 = point4.Y - point3.Y >= num6;
                int x = point4.X;
                if (!WorldGen.InWorld(x, point3.Y, 40) || !WorldGen.InWorld(x, point4.Y, 40))
                {
                    flag2 = true;
                }
                if (!flag2)
                {
                    for (int num11 = point4.Y; num11 >= point3.Y; num11--)
                    {
                        if (Main.tile[x, num11].active() && !Main.tileCut[Main.tile[x, num11].type] && Main.tile[x, num11].type != 504)
{
                            flag2 = true;
                            break;
                        }
                    }
                }
                if (flag2)
                {
                    int num12 = 0;
                    for (int num13 = point4.Y; num13 > point3.Y; num13--)
                    {
                        if ((WorldGen.TileEmpty(x, num13) || Main.tileCut[Main.tile[x, num13].type]) && WorldGen.PlaceTile(x, num13, 504, mute: false, forced: false, owner))
{
                            num12++;
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(17, -1, -1, null, 1, x, num13, 504f);
                            }
                        }
                    }
                    timeLeft = num7;
                    ai[1] = 2f;
                    netUpdate = true;
                    base.Top = new Vector2((float)(x * 16 + 8), (float)(point3.Y * 16 + 16));
                    velocity = Vector2.Zero;
                }
            }
        }
        if (ai[1] != 2f)
        {
            return;
        }
        alpha = 0;
        _ = timeLeft;
        float num2 = ai[0];
        float y3 = position.Y;
        Point point5 = base.Center.ToTileCoordinates();
        Point end2 = default(Point);
        ((Point)(ref end2))._002Ector(point5.X, (int)y3 / 16);
        Point start2 = default(Point);
        ((Point)(ref start2))._002Ector(point5.X, (int)num2 / 16);
        int x2 = start2.X;
        if (localAI[0] == 0f)
        {
            localAI[0] = 1f;
            for (int num3 = start2.Y; num3 >= end2.Y; num3--)
            {
                Tile tile = Main.tile[x2, num3];
                if (tile.active() && tile.type == 504)
                {
                    AI_155_SpawnRopeIn(x2, num3);
                }
            }
        }
        else
        {
            for (int num4 = start2.Y; num4 >= end2.Y; num4--)
            {
                Tile tile2 = Main.tile[x2, num4];
                if (tile2.active() && tile2.type == 504 && Main.rand.Next(80) == 0)
                {
                    Dust dust3 = Dust.NewDustDirect(new Vector2((float)(x2 * 16 - 6), (float)(num4 * 16)), 28, 16, 27, 0f, 0f, 150, Color.Transparent, 0.6f);
                    dust3.velocity *= 1f;
                    dust3.velocity.X = 0f;
                    dust3.fadeIn = 1.2f;
                    dust3.noGravity = true;
                }
            }
        }
        if (timeLeft == 4)
        {
            for (int num5 = start2.Y; num5 >= end2.Y; num5--)
            {
                Tile tile3 = Main.tile[x2, num5];
                if (tile3.active() && tile3.type == 504)
                {
                    AI_155_SpawnRopeIn(x2, num5);
                }
            }
        }
        if (timeLeft > 4)
        {
            return;
        }
        if (!WorldGen.InWorld(x2, end2.Y, 20) || !WorldGen.InWorld(x2, start2.Y, 20))
        {
            Kill();
            return;
        }
        if (Main.myPlayer == owner)
        {
            AI_155_RemoveRope(start2, end2);
        }
        Kill();
    }
References Terraria.Entity.active, Terraria.Tile.active(), Terraria.Entity.Center, Terraria.WorldGen.InWorld(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.Main.player, Terraria.Main.rand, Terraria.Utils.Remap(), Terraria.Utils.RotatedBy(), Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.WorldGen.TileEmpty(), and Terraria.Dust.velocity.