TModLoader: Terraria.Projectile.AI_099_1
AI_099_1()
void Terraria.Projectile.AI_099_1 () inline private
    {
        //IL_0220: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0230: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_028e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0291: Unknown result type (might be due to invalid IL or missing references)
        //IL_0296: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0316: Unknown result type (might be due to invalid IL or missing references)
        //IL_0320: Unknown result type (might be due to invalid IL or missing references)
        //IL_0325: Unknown result type (might be due to invalid IL or missing references)
        //IL_033a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0345: Unknown result type (might be due to invalid IL or missing references)
        //IL_0362: Unknown result type (might be due to invalid IL or missing references)
        //IL_0378: Unknown result type (might be due to invalid IL or missing references)
        //IL_0387: Unknown result type (might be due to invalid IL or missing references)
        //IL_038e: Unknown result type (might be due to invalid IL or missing references)
        //IL_080d: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0399: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_061a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0621: Unknown result type (might be due to invalid IL or missing references)
        //IL_0626: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0401: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0725: Unknown result type (might be due to invalid IL or missing references)
        //IL_072a: Unknown result type (might be due to invalid IL or missing references)
        //IL_072d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0732: Unknown result type (might be due to invalid IL or missing references)
        //IL_0737: Unknown result type (might be due to invalid IL or missing references)
        //IL_0630: Unknown result type (might be due to invalid IL or missing references)
        //IL_0646: Unknown result type (might be due to invalid IL or missing references)
        //IL_042a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0437: Unknown result type (might be due to invalid IL or missing references)
        //IL_043c: Unknown result type (might be due to invalid IL or missing references)
        //IL_043e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0445: Unknown result type (might be due to invalid IL or missing references)
        //IL_044c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0411: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c55: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c59: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c76: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c82: Unknown result type (might be due to invalid IL or missing references)
        //IL_066d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0683: Unknown result type (might be due to invalid IL or missing references)
        //IL_0652: Unknown result type (might be due to invalid IL or missing references)
        //IL_0516: Unknown result type (might be due to invalid IL or missing references)
        //IL_051b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0526: Unknown result type (might be due to invalid IL or missing references)
        //IL_0536: Unknown result type (might be due to invalid IL or missing references)
        //IL_0543: Unknown result type (might be due to invalid IL or missing references)
        //IL_0548: Unknown result type (might be due to invalid IL or missing references)
        //IL_054a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0478: Unknown result type (might be due to invalid IL or missing references)
        //IL_047d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0488: Unknown result type (might be due to invalid IL or missing references)
        //IL_0498: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_06aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_068f: Unknown result type (might be due to invalid IL or missing references)
        //IL_057b: Unknown result type (might be due to invalid IL or missing references)
        //IL_057d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0562: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04df: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0585: Unknown result type (might be due to invalid IL or missing references)
        //IL_0588: Unknown result type (might be due to invalid IL or missing references)
        //IL_0592: Unknown result type (might be due to invalid IL or missing references)
        //IL_0597: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0506: Unknown result type (might be due to invalid IL or missing references)
        //IL_050b: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09db: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0709: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b54: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_09fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a02: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a26: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2b: Unknown result type (might be due to invalid IL or missing references)
        //IL_092c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0945: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b80: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b87: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a42: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a49: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a52: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a63: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0973: Unknown result type (might be due to invalid IL or missing references)
        //IL_0984: Unknown result type (might be due to invalid IL or missing references)
        //IL_0989: Unknown result type (might be due to invalid IL or missing references)
        //IL_098e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a90: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a95: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aaa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b14: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b25: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0acd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0add: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0afd: Unknown result type (might be due to invalid IL or missing references)
        timeLeft = 6;
        bool flag = true;
        float num = 250f;
        float num6 = 0.1f;
        float num7 = 15f;
        float num8 = 12f;
        num *= 0.5f;
        num7 *= 0.8f;
        num8 *= 1.5f;
        if (owner == Main.myPlayer)
        {
            bool flag2 = false;
            for (int i = 0; i < 1000; i++)
            {
                if (Main.projectile[i].active && Main.projectile[i].owner == owner && Main.projectile[i].aiStyle == 99 && (Main.projectile[i].type < 556 || Main.projectile[i].type > 561))
                {
                    flag2 = true;
                }
            }
            if (!flag2)
            {
                ai[0] = -1f;
                netUpdate = true;
            }
        }
        if (Main.player[owner].yoyoString)
        {
            num += num * 0.25f + 10f;
        }
        rotation += 0.5f;
        if (Main.player[owner].dead)
        {
            Kill();
            return;
        }
        if (!flag)
        {
            Main.player[owner].heldProj = whoAmI;
            Main.player[owner].SetDummyItemTime(2);
            if (position.X + (float)(width / 2) > Main.player[owner].position.X + (float)(Main.player[owner].width / 2))
            {
                Main.player[owner].ChangeDir(1);
                direction = 1;
            }
            else
            {
                Main.player[owner].ChangeDir(-1);
                direction = -1;
            }
        }
        if (ai[0] == 0f || ai[0] == 1f)
        {
            if (ai[0] == 1f)
            {
                num *= 0.75f;
            }
            num8 *= 0.5f;
            bool flag3 = false;
            Vector2 vector = Main.player[owner].Center - base.Center;
            if ((double)((Vector2)(ref vector)).Length() > (double)num * 0.9)
            {
                flag3 = true;
            }
            if (((Vector2)(ref vector)).Length() > num)
            {
                float num9 = ((Vector2)(ref vector)).Length() - num;
                Vector2 vector2 = default(Vector2);
                vector2.X = vector.Y;
                vector2.Y = vector.X;
                ((Vector2)(ref vector)).Normalize();
                vector *= num;
                position = Main.player[owner].Center - vector;
                position.X -= width / 2;
                position.Y -= height / 2;
                float num10 = ((Vector2)(ref velocity)).Length();
                ((Vector2)(ref velocity)).Normalize();
                if (num9 > num10 - 1f)
                {
                    num9 = num10 - 1f;
                }
                velocity *= num10 - num9;
                num10 = ((Vector2)(ref velocity)).Length();
                Vector2 vector3 = default(Vector2);
                ((Vector2)(ref vector3))._002Ector(base.Center.X, base.Center.Y);
                Vector2 vector4 = default(Vector2);
                ((Vector2)(ref vector4))._002Ector(Main.player[owner].Center.X, Main.player[owner].Center.Y);
                if (vector3.Y < vector4.Y)
                {
                    vector2.Y = Math.Abs(vector2.Y);
                }
                else if (vector3.Y > vector4.Y)
                {
                    vector2.Y = 0f - Math.Abs(vector2.Y);
                }
                if (vector3.X < vector4.X)
                {
                    vector2.X = Math.Abs(vector2.X);
                }
                else if (vector3.X > vector4.X)
                {
                    vector2.X = 0f - Math.Abs(vector2.X);
                }
                ((Vector2)(ref vector2)).Normalize();
                vector2 *= ((Vector2)(ref velocity)).Length();
                new Vector2(vector2.X, vector2.Y);
                if (Math.Abs(velocity.X) > Math.Abs(velocity.Y))
                {
                    Vector2 vector5 = velocity;
                    vector5.Y += vector2.Y;
                    ((Vector2)(ref vector5)).Normalize();
                    vector5 *= ((Vector2)(ref velocity)).Length();
                    if ((double)Math.Abs(vector2.X) < 0.1 || (double)Math.Abs(vector2.Y) < 0.1)
                    {
                        velocity = vector5;
                    }
                    else
                    {
                        velocity = (vector5 + velocity * 2f) / 3f;
                    }
                }
                else
                {
                    Vector2 vector6 = velocity;
                    vector6.X += vector2.X;
                    ((Vector2)(ref vector6)).Normalize();
                    vector6 *= ((Vector2)(ref velocity)).Length();
                    if ((double)Math.Abs(vector2.X) < 0.2 || (double)Math.Abs(vector2.Y) < 0.2)
                    {
                        velocity = vector6;
                    }
                    else
                    {
                        velocity = (vector6 + velocity * 2f) / 3f;
                    }
                }
            }
            if (Main.myPlayer == owner)
            {
                if (Main.player[owner].channel)
                {
                    Vector2 vector7 = default(Vector2);
                    ((Vector2)(ref vector7))._002Ector((float)(Main.mouseX - Main.lastMouseX), (float)(Main.mouseY - Main.lastMouseY));
                    if (velocity.X != 0f || velocity.Y != 0f)
                    {
                        if (flag)
{
                            vector7 *= -1f;
                        }
                        if (flag3)
{
                            if (base.Center.X < Main.player[owner].Center.X && vector7.X < 0f)
{
                                vector7.X = 0f;
                            }
                            if (base.Center.X > Main.player[owner].Center.X && vector7.X > 0f)
{
                                vector7.X = 0f;
                            }
                            if (base.Center.Y < Main.player[owner].Center.Y && vector7.Y < 0f)
{
                                vector7.Y = 0f;
                            }
                            if (base.Center.Y > Main.player[owner].Center.Y && vector7.Y > 0f)
{
                                vector7.Y = 0f;
                            }
                        }
                        velocity += vector7 * num6;
                        netUpdate = true;
                    }
                }
                else
                {
                    ai[0] = -1f;
                    netUpdate = true;
                }
            }
            if (flag || type == 562 || type == 547 || type == 555 || type == 564 || type == 552 || type == 563 || type == 549 || type == 550 || type == 554 || type == 553 || type == 603 || type == 999)
            {
                float num11 = 800f;
                Vector2 vector8 = default(Vector2);
                bool flag4 = false;
                if (type == 549)
                {
                    num11 = 200f;
                }
                if (type == 554)
                {
                    num11 = 400f;
                }
                if (type == 553)
                {
                    num11 = 250f;
                }
                if (type == 603)
                {
                    num11 = 320f;
                }
                for (int j = 0; j < 200; j++)
                {
                    if (!Main.npc[j].CanBeChasedBy(this))
                    {
                        continue;
                    }
                    float num12 = Main.npc[j].position.X + (float)(Main.npc[j].width / 2);
                    float num13 = Main.npc[j].position.Y + (float)(Main.npc[j].height / 2);
                    float num2 = Math.Abs(position.X + (float)(width / 2) - num12) + Math.Abs(position.Y + (float)(height / 2) - num13);
                    if (num2 < num11 && (type != 563 || !(num2 < 200f)) && Collision.CanHit(position, width, height, Main.npc[j].position, Main.npc[j].width, Main.npc[j].height))
                    {
                        Vector2 val = Main.npc[j].Center - Main.player[owner].Center;
                        if ((double)((Vector2)(ref val)).Length() < (double)num * 0.9)
{
                            num11 = num2;
                            vector8.X = num12;
                            vector8.Y = num13;
                            flag4 = true;
                        }
                    }
                }
                if (flag4)
                {
                    vector8 -= base.Center;
                    ((Vector2)(ref vector8)).Normalize();
                    if (type == 563)
                    {
                        vector8 *= 4f;
                        velocity = (velocity * 14f + vector8) / 15f;
                    }
                    else if (type == 553)
                    {
                        vector8 *= 5f;
                        velocity = (velocity * 12f + vector8) / 13f;
                    }
                    else if (type == 603)
                    {
                        vector8 *= 16f;
                        velocity = (velocity * 9f + vector8) / 10f;
                    }
                    else if (type == 554)
                    {
                        vector8 *= 8f;
                        velocity = (velocity * 6f + vector8) / 7f;
                    }
                    else
                    {
                        vector8 *= 6f;
                        velocity = (velocity * 7f + vector8) / 8f;
                    }
                }
            }
            if (((Vector2)(ref velocity)).Length() > num7)
            {
                ((Vector2)(ref velocity)).Normalize();
                velocity *= num7;
            }
            if (((Vector2)(ref velocity)).Length() < num8)
            {
                ((Vector2)(ref velocity)).Normalize();
                velocity *= num8;
            }
            return;
        }
        tileCollide = false;
        Vector2 vector9 = Main.player[owner].Center - base.Center;
        float num3 = ((Vector2)(ref vector9)).Length();
        if (num3 < 40f || vector9.HasNaNs() || num3 > 2000f)
        {
            Kill();
            return;
        }
        float num4 = num7 * 1.5f;
        if (type == 546)
        {
            num4 *= 1.5f;
        }
        if (type == 554)
        {
            num4 *= 1.25f;
        }
        if (type == 555)
        {
            num4 *= 1.35f;
        }
        if (type == 562)
        {
            num4 *= 1.25f;
        }
        float num5 = 12f;
        ((Vector2)(ref vector9)).Normalize();
        vector9 *= num4;
        velocity = (velocity * (num5 - 1f) + vector9) / num5;
    }
References Terraria.Entity.active, Terraria.Projectile.aiStyle, Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Player.ChangeDir(), Terraria.Player.channel, Terraria.Player.dead, Terraria.Entity.height, Terraria.Player.heldProj, Terraria.Main.lastMouseX, Terraria.Main.lastMouseY, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Player.SetDummyItemTime(), Terraria.Projectile.type, Terraria.Entity.width, and Terraria.Player.yoyoString.