TModLoader: Terraria.Projectile.MakeBoulderOfEarthExplosion
MakeBoulderOfEarthExplosion()
void Terraria.Projectile.MakeBoulderOfEarthExplosion () inline private
    {
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        localAI[0] = 40f;
        float mAX_SPREAD = 20f;
        int fluff = 10;
        int distFluff = 50;
        int layerStart = 1;
        int num = 6;
        if (((Vector2)(ref velocity)).Length() < 8f || Math.Abs(velocity.Y) < 4f)
        {
            mAX_SPREAD = 15f;
            fluff = 7;
            distFluff = 30;
            num = 4;
        }
        if (((Vector2)(ref velocity)).Length() < 4f || Math.Abs(velocity.Y) < 2f)
        {
            mAX_SPREAD = 15f;
            fluff = 7;
            distFluff = 30;
            num = 2;
            layerStart = 0;
        }
        int layerEnd = num;
        int num2 = num - 2;
        if (num2 < 1)
        {
            num2 = 1;
        }
        CreateGroundExplosion(mAX_SPREAD, fluff, distFluff, layerStart, layerEnd, num2);
        for (int i = 0; i < 10; i++)
        {
            Dust dust = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(width / 2, height / 2), 228, Main.rand.NextVector2Circular(3f, 3f));
            dust.scale = 0.6f;
            if (i < 5)
            {
                dust.noGravity = true;
                dust.scale = 1.8f;
            }
        }
    }
References Terraria.Projectile.CreateGroundExplosion(), Terraria.Entity.height, Terraria.Projectile.localAI, Terraria.Dust.NewDustPerfect(), Terraria.Main.rand, Terraria.Entity.velocity, and Terraria.Entity.width.
Referenced by Terraria.Projectile.HandleMovement().