TModLoader: Terraria.Projectile.CutTiles
CutTiles()
void Terraria.Projectile.CutTiles () inline private
    {
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0176: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0305: Unknown result type (might be due to invalid IL or missing references)
        //IL_030b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0311: Unknown result type (might be due to invalid IL or missing references)
        //IL_0316: Unknown result type (might be due to invalid IL or missing references)
        //IL_031c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0321: Unknown result type (might be due to invalid IL or missing references)
        //IL_0326: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        //IL_0335: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_043f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0449: Unknown result type (might be due to invalid IL or missing references)
        //IL_0454: Unknown result type (might be due to invalid IL or missing references)
        //IL_0459: Unknown result type (might be due to invalid IL or missing references)
        //IL_0467: Unknown result type (might be due to invalid IL or missing references)
        //IL_0471: Unknown result type (might be due to invalid IL or missing references)
        //IL_047c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0481: Unknown result type (might be due to invalid IL or missing references)
        //IL_0492: Unknown result type (might be due to invalid IL or missing references)
        //IL_0497: Unknown result type (might be due to invalid IL or missing references)
        //IL_0499: Unknown result type (might be due to invalid IL or missing references)
        //IL_049f: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e2: Unknown result type (might be due to invalid IL or missing references)
        if (!CanCutTiles())
        {
            return;
        }
        AchievementsHelper.CurrentlyMining = true;
        bool flag = true;
        bool[] tileCutIgnorance = Main.player[owner].GetTileCutIgnorance(allowRegrowth: false, trap);
        DelegateMethods.tilecut_0 = TileCuttingContext.AttackProjectile;
        DelegateMethods.tileCutIgnore = tileCutIgnorance;
        Rectangle extensionBox;
        if (type == 461 || type == 632 || type == 642)
        {
            Utils.PlotTileLine(base.Center, base.Center + velocity * localAI[1], (float)width * scale, DelegateMethods.CutTiles);
        }
        else if (ProjectileID.Sets.IsAWhip[type])
        {
            flag = false;
            WhipPointsForCollision.Clear();
            FillWhipControlPoints(this, WhipPointsForCollision);
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector((float)width * scale / 2f, 0f);
            for (int i = 0; i < WhipPointsForCollision.Count; i++)
            {
                Utils.PlotTileLine(WhipPointsForCollision[i] - vector, WhipPointsForCollision[i] + vector, (float)height * scale, DelegateMethods.CutTiles);
            }
        }
        else if (type == 756)
        {
            Utils.PlotTileLine(base.Center, base.Center + velocity.SafeNormalize(-Vector2.UnitY) * 200f * scale, 22f * scale, DelegateMethods.CutTiles);
        }
        else if (type == 927)
        {
            Vector2 end = base.Center + velocity.SafeNormalize(Vector2.UnitX) * 220f * scale;
            Utils.PlotTileLine(base.Center, end, 80f * scale, DelegateMethods.CutTiles);
        }
        else if (type == 802 || type == 842 || type == 938 || type == 939 || type == 940 || type == 941 || type == 942 || type == 943 || type == 944 || type == 945)
        {
            Utils.PlotTileLine(base.Center, base.Center + velocity.SafeNormalize(-Vector2.UnitY) * 10f, 10f * scale, DelegateMethods.CutTiles);
        }
        else if (type == 611)
        {
            Utils.PlotTileLine(base.Center, base.Center + velocity + velocity.SafeNormalize(Vector2.Zero) * 48f, (float)width * scale, DelegateMethods.CutTiles);
        }
        else if (type == 697 || type == 707)
        {
            float num = 40f;
            if (type == 707)
            {
                num = 60f;
            }
            float f = rotation - (float)Math.PI / 4f * (float)Math.Sign(velocity.X);
            Utils.PlotTileLine(base.Center + f.ToRotationVector2() * (0f - num), base.Center + f.ToRotationVector2() * num, (float)width * scale, DelegateMethods.CutTiles);
        }
        else if (aiStyle == 190 || aiStyle == 191)
        {
            flag = false;
            Vector2 vector2 = (rotation - (float)Math.PI / 4f).ToRotationVector2() * 60f * scale;
            Vector2 vector3 = (rotation + (float)Math.PI / 4f).ToRotationVector2() * 60f * scale;
            float num2 = 60f * scale;
            Utils.PlotTileLine(base.Center + vector2, base.Center + vector3, num2, DelegateMethods.CutTiles);
        }
        else if (aiStyle == 19 && AI_019_Spears_GetExtensionHitbox(out extensionBox))
        {
            CutTilesAt(extensionBox.TopLeft(), extensionBox.Width, extensionBox.Height);
        }
        if (flag)
        {
            CutTilesAt(position, width, height);
        }
        AchievementsHelper.CurrentlyMining = false;
    }
References Terraria.Projectile.AI_019_Spears_GetExtensionHitbox(), Terraria.Projectile.aiStyle, Terraria.Projectile.CanCutTiles(), Terraria.DelegateMethods.CutTiles(), Terraria.Projectile.CutTilesAt(), Terraria.Projectile.FillWhipControlPoints(), Terraria.Player.GetTileCutIgnorance(), Terraria.Entity.height, Terraria.ID.ProjectileID.Sets.IsAWhip, Terraria.Projectile.localAI, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Utils.PlotTileLine(), Terraria.Entity.position, Terraria.Projectile.rotation, Terraria.Projectile.scale, Terraria.Projectile.trap, Terraria.Projectile.type, Terraria.Entity.velocity, Terraria.Projectile.WhipPointsForCollision, and Terraria.Entity.width.
Referenced by Terraria.Projectile.Damage().