TModLoader: Terraria.Projectile.UpdatePosition
UpdatePosition()
void Terraria.Projectile.UpdatePosition (Vector2 wetVelocity) inline private
Definition at line 19456 of file Projectile.cs.
    {
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_019f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f5: Unknown result type (might be due to invalid IL or missing references)
        if (aiStyle == 4 || aiStyle == 38 || aiStyle == 84 || aiStyle == 148 || (aiStyle == 7 && ai[0] == 2f) || ((type == 440 || type == 449 || type == 606) && ai[1] == 1f) || (aiStyle == 93 && ai[0] < 0f) || type == 540 || type == 756 || type == 818 || type == 856 || type == 961 || type == 933 || ProjectileID.Sets.IsAGolfBall[type] || !ProjectileLoader.ShouldUpdatePosition(this))
        {
            return;
        }
        if (wet)
        {
            position += wetVelocity;
        }
        else
        {
            position += velocity;
        }
        if (Main.projPet[type] && tileCollide)
        {
            bool fall = false;
            if (aiStyle == 62)
            {
                fall = true;
            }
            switch (type)
            {
            case 317:
            case 387:
            case 388:
            case 533:
            case 759:
                fall = true;
                break;
            }
            Vector4 vector = Collision.SlopeCollision(position, velocity, width, height, 0f, fall);
            position.X = vector.X;
            position.Y = vector.Y;
            velocity.X = vector.Z;
            velocity.Y = vector.W;
        }
    }
References Terraria.Projectile.ai, Terraria.Projectile.aiStyle, Terraria.Entity.height, Terraria.ID.ProjectileID.Sets.IsAGolfBall, Terraria.Entity.position, Terraria.Main.projPet, Terraria.ModLoader.ProjectileLoader.ShouldUpdatePosition(), Terraria.Collision.SlopeCollision(), Terraria.Projectile.tileCollide, Terraria.Projectile.type, Terraria.Entity.velocity, Terraria.Entity.wet, and Terraria.Entity.width.
Referenced by Terraria.Projectile.HandleMovement().