TModLoader: Terraria.Projectile.AI_120_StardustGuardian
AI_120_StardustGuardian()
void Terraria.Projectile.AI_120_StardustGuardian () inline private
    {
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        //IL_0292: Unknown result type (might be due to invalid IL or missing references)
        //IL_0297: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0555: Unknown result type (might be due to invalid IL or missing references)
        //IL_055a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0323: Unknown result type (might be due to invalid IL or missing references)
        //IL_032d: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_057f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0589: Unknown result type (might be due to invalid IL or missing references)
        //IL_036b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0376: Unknown result type (might be due to invalid IL or missing references)
        //IL_0396: Unknown result type (might be due to invalid IL or missing references)
        //IL_039d: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0408: Unknown result type (might be due to invalid IL or missing references)
        //IL_0413: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0145: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01de: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bcf: Unknown result type (might be due to invalid IL or missing references)
        //IL_042c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0433: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a30: Unknown result type (might be due to invalid IL or missing references)
        //IL_0796: Unknown result type (might be due to invalid IL or missing references)
        //IL_079d: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_060d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0618: Unknown result type (might be due to invalid IL or missing references)
        //IL_062a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0631: Unknown result type (might be due to invalid IL or missing references)
        //IL_0645: Unknown result type (might be due to invalid IL or missing references)
        //IL_0650: Unknown result type (might be due to invalid IL or missing references)
        //IL_0664: Unknown result type (might be due to invalid IL or missing references)
        //IL_066f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a86: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a91: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0688: Unknown result type (might be due to invalid IL or missing references)
        //IL_068f: Unknown result type (might be due to invalid IL or missing references)
        //IL_084b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0856: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0876: Unknown result type (might be due to invalid IL or missing references)
        //IL_087d: Unknown result type (might be due to invalid IL or missing references)
        //IL_049c: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e50: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f02: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c05: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ceb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aaa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0acd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0add: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b11: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b32: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08de: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ff: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        if (!player.active)
        {
            active = false;
            return;
        }
        bool flag = type == 623;
        Vector2 vector = player.Center;
        float num = 100f;
        float num12 = 500f;
        float num15 = 500f;
        float num16 = 100f;
        bool flag2 = true;
        if (flag)
        {
            if (player.dead)
            {
                player.stardustGuardian = false;
            }
            if (player.stardustGuardian)
            {
                timeLeft = 2;
            }
            num = 150f;
            vector.X -= (5 + player.width / 2) * player.direction;
            vector.Y -= 25f;
            Lighting.AddLight(base.Center, 0.9f, 0.9f, 0.7f);
            if (ai[0] != 3f && alpha == 255)
            {
                alpha = 0;
                for (int i = 0; i < 30; i++)
                {
                    int num17 = Dust.NewDust(position, width, height, 135, 0f, 0f, 200, default(Color), 1.7f);
                    Main.dust[num17].noGravity = true;
                    Dust obj = Main.dust[num17];
                    obj.velocity *= 3f;
                    Main.dust[num17].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].cPet, Main.player[owner]);
                    num17 = Dust.NewDust(position, width, height, 135, 0f, 0f, 100);
                    Dust obj2 = Main.dust[num17];
                    obj2.velocity *= 2f;
                    Main.dust[num17].noGravity = true;
                    Main.dust[num17].fadeIn = 2.5f;
                    Main.dust[num17].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].cPet, Main.player[owner]);
                }
            }
        }
        if (ai[0] != 0f)
        {
            Main.player[owner].tankPet = whoAmI;
            Main.player[owner].tankPetReset = false;
        }
        if (ai[0] == 0f)
        {
            base.Center = Vector2.Lerp(base.Center, vector, 0.05f);
            velocity *= 0.5f;
            direction = (spriteDirection = player.direction);
            if (flag && ++frameCounter >= 9)
            {
                frameCounter = 0;
                if (++frame >= 8)
                {
                    frame = 0;
                }
            }
            int targetNPCIndex = -1;
            float distanceToClosestTarget = num12;
            bool flag3 = flag2;
            if (flag && Math.Abs(base.Center.X - vector.X) > num + 20f)
            {
                flag3 = false;
            }
            if (flag3)
            {
                AI_120_StardustGuardian_FindTarget(num12, ref targetNPCIndex, ref distanceToClosestTarget);
            }
            if (targetNPCIndex != -1)
            {
                NPC nPC = Main.npc[targetNPCIndex];
                direction = (spriteDirection = (nPC.Center.X > base.Center.X).ToDirectionInt());
                float num18 = Math.Abs(vector.X - base.Center.X);
                float num19 = Math.Abs(nPC.Center.X - base.Center.X);
                float num20 = Math.Abs(vector.Y - base.Center.Y);
                float num21 = Math.Abs(nPC.Center.Y - base.Bottom.Y);
                float num2 = (nPC.Center.Y > base.Bottom.Y).ToDirectionInt();
                if ((num18 < num || (vector.X - base.Center.X) * (float)direction < 0f) && num19 > 20f && num19 < num - num18 + 100f)
                {
                    velocity.X += 0.1f * (float)direction;
                }
                else
                {
                    velocity.X *= 0.7f;
                }
                if ((num20 < num16 || (vector.Y - base.Bottom.Y) * num2 < 0f) && num21 > 10f && num21 < num16 - num20 + 10f)
                {
                    velocity.Y += 0.1f * num2;
                }
                else
                {
                    velocity.Y *= 0.7f;
                }
                if (owner == Main.myPlayer && num19 < num15)
                {
                    ai[0] = 2f;
                    ai[1] = targetNPCIndex;
                    netUpdate = true;
                }
            }
        }
        else if (ai[0] == 1f)
        {
            if (player.HasMinionRestTarget)
            {
                vector = player.MinionRestTargetPoint;
            }
            else
            {
                ai[0] = 0f;
                netUpdate = true;
            }
            int targetNPCIndex2 = -1;
            float distanceToClosestTarget2 = num12;
            bool flag4 = true;
            if (flag && Math.Abs(base.Center.X - vector.X) > num + 20f)
            {
                flag4 = false;
            }
            if (flag4)
            {
                AI_120_StardustGuardian_FindTarget(num12, ref targetNPCIndex2, ref distanceToClosestTarget2);
            }
            if (targetNPCIndex2 != -1)
            {
                NPC nPC2 = Main.npc[targetNPCIndex2];
                direction = (spriteDirection = (nPC2.Center.X > base.Center.X).ToDirectionInt());
                float num3 = Math.Abs(vector.X - base.Center.X);
                float num4 = Math.Abs(nPC2.Center.X - base.Center.X);
                float num5 = Math.Abs(vector.Y - base.Center.Y);
                float num6 = Math.Abs(nPC2.Center.Y - base.Bottom.Y);
                float num7 = (nPC2.Center.Y > base.Bottom.Y).ToDirectionInt();
                if ((num3 < num || (vector.X - base.Center.X) * (float)direction < 0f) && num4 > 20f && num4 < num - num3 + 100f)
                {
                    velocity.X += 0.1f * (float)direction;
                }
                else
                {
                    velocity.X *= 0.7f;
                }
                if ((num5 < num16 || (vector.Y - base.Bottom.Y) * num7 < 0f) && num6 > 10f && num6 < num16 - num5 + 10f)
                {
                    velocity.Y += 0.1f * num7;
                }
                else
                {
                    velocity.Y *= 0.7f;
                }
                if (owner == Main.myPlayer && num4 < num15)
                {
                    ai[0] = 2f;
                    ai[1] = targetNPCIndex2;
                    netUpdate = true;
                }
            }
            else
            {
                if (Math.Abs(vector.X - base.Center.X) > num + 40f)
                {
                    ai[0] = 3f;
                    netUpdate = true;
                }
                else if (Math.Abs(vector.X - base.Center.X) > 20f)
                {
                    direction = (spriteDirection = (vector.X > base.Center.X).ToDirectionInt());
                    velocity.X += 0.06f * (float)direction;
                }
                else
                {
                    velocity.X *= 0.8f;
                    direction = (spriteDirection = (player.Center.X < base.Center.X).ToDirectionInt());
                }
                if (Math.Abs(vector.Y - base.Center.Y) > num16)
                {
                    ai[0] = 3f;
                    netUpdate = true;
                }
                else if (Math.Abs(vector.Y - base.Center.Y) > 10f)
                {
                    velocity.Y += 0.06f * (float)Math.Sign(vector.Y - base.Center.Y);
                }
                else
                {
                    velocity.Y *= 0.8f;
                }
            }
            if (flag && ++frameCounter >= 9)
            {
                frameCounter = 0;
                if (++frame >= Main.projFrames[type] - 4)
                {
                    frame = 0;
                }
            }
        }
        else if (ai[0] == 2f)
        {
            if (flag)
            {
                int num8 = 3;
                if (frame < 12)
                {
                    frame = 12;
                }
                if (frame == 12 || frame == 13)
                {
                    num8 = 8;
                }
                if (++frameCounter >= num8)
                {
                    frameCounter = 0;
                    if (++frame >= 19)
                    {
                        frame = 14;
                    }
                }
            }
            bool flag5 = false;
            if (flag2)
            {
                flag5 = Distance(player.Center) < num12;
            }
            NPC nPC3 = null;
            int num9 = (int)ai[1];
            if (Main.npc.IndexInRange(num9))
            {
                nPC3 = Main.npc[num9];
                if (!nPC3.CanBeChasedBy(this) || Distance(nPC3.Center) > num15)
                {
                    nPC3 = null;
                }
            }
            if (!flag5 || nPC3 == null)
            {
                ai[1] = 0f;
                ai[0] = 0f;
                netUpdate = true;
                if (frame < 18)
                {
                    frame = 18;
                }
            }
            else
            {
                int num10 = (((nPC3.Center - player.Center).X > 1f) ? 1 : (-1));
                Vector2 targetPosition = nPC3.Center + new Vector2((float)(-num10) * ((float)nPC3.width * 0.5f + 70f), -10f) - base.Center;
                float maxAmountAllowedToMove = 6f * Utils.Remap(((Vector2)(ref targetPosition)).Length(), 50f, 400f, 1f, 4f);
                int num11 = 32;
                Vector2 targetPosition2 = Vector2.Zero.MoveTowards(targetPosition, maxAmountAllowedToMove);
                velocity = velocity.MoveTowards(targetPosition2, num11);
                direction = (spriteDirection = num10);
                if (localAI[0]++ >= 3f)
                {
                    localAI[0] = 0f;
                    int targetNPCIndex3 = -1;
                    float distanceToClosestTarget3 = -1f;
                    AI_120_StardustGuardian_FindTarget(num12, ref targetNPCIndex3, ref distanceToClosestTarget3);
                    if (targetNPCIndex3 != -1)
                    {
                        ai[1] = targetNPCIndex3;
                        netUpdate = true;
                    }
                }
            }
        }
        else
        {
            _ = ai[0];
        }
        if (ai[0] != 3f)
        {
            return;
        }
        if (player.HasMinionRestTarget)
        {
            vector = player.MinionRestTargetPoint;
        }
        else
        {
            ai[0] = 0f;
            netUpdate = true;
        }
        if (alpha == 0)
        {
            alpha = 255;
            for (int j = 0; j < 30; j++)
            {
                int num13 = Dust.NewDust(position, width, height, 135, 0f, 0f, 200, default(Color), 1.7f);
                Main.dust[num13].noGravity = true;
                Dust obj3 = Main.dust[num13];
                obj3.velocity *= 3f;
                Main.dust[num13].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].cPet, Main.player[owner]);
                num13 = Dust.NewDust(position, width, height, 135, 0f, 0f, 100);
                Dust obj4 = Main.dust[num13];
                obj4.velocity *= 2f;
                Main.dust[num13].noGravity = true;
                Main.dust[num13].fadeIn = 2.5f;
                Main.dust[num13].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].cPet, Main.player[owner]);
            }
        }
        else
        {
            for (int k = 0; k < 2; k++)
            {
                int num14 = Dust.NewDust(position, width, height, 135, 0f, 0f, 200, default(Color), 1.7f);
                Main.dust[num14].noGravity = true;
                Dust obj5 = Main.dust[num14];
                obj5.velocity *= 3f;
                Main.dust[num14].noLight = true;
                Main.dust[num14].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].cPet, Main.player[owner]);
                num14 = Dust.NewDust(position, width, height, 135, 0f, 0f, 100);
                Dust obj6 = Main.dust[num14];
                obj6.velocity *= 2f;
                Main.dust[num14].noGravity = true;
                Main.dust[num14].fadeIn = 2.5f;
                Main.dust[num14].noLight = true;
                Main.dust[num14].shader = GameShaders.Armor.GetSecondaryShader(Main.player[owner].cPet, Main.player[owner]);
            }
        }
        velocity *= 0.7f;
        base.Center = Vector2.Lerp(base.Center, vector, 0.2f);
        if (Distance(vector) < 10f)
        {
            ai[0] = 1f;
            netUpdate = true;
        }
    }
References Terraria.Entity.active, Terraria.Lighting.AddLight(), Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Entity.Center, Terraria.Player.cPet, Terraria.Player.dead, Terraria.Entity.direction, Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.Player.HasMinionRestTarget, Terraria.Player.MinionRestTargetPoint, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Main.npc, Terraria.Main.player, Terraria.Main.projFrames, Terraria.Utils.Remap(), Terraria.Dust.shader, Terraria.Player.stardustGuardian, Terraria.Player.tankPet, and Terraria.Player.tankPetReset.