TModLoader: Terraria.Projectile.AI_075
AI_075()
void Terraria.Projectile.AI_075 () inline private
    {
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0521: Unknown result type (might be due to invalid IL or missing references)
        //IL_0523: Unknown result type (might be due to invalid IL or missing references)
        //IL_0569: Unknown result type (might be due to invalid IL or missing references)
        //IL_0584: Unknown result type (might be due to invalid IL or missing references)
        //IL_0594: Unknown result type (might be due to invalid IL or missing references)
        //IL_059e: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0624: Unknown result type (might be due to invalid IL or missing references)
        //IL_0633: Unknown result type (might be due to invalid IL or missing references)
        //IL_0641: Unknown result type (might be due to invalid IL or missing references)
        //IL_0648: Unknown result type (might be due to invalid IL or missing references)
        //IL_064f: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05be: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0601: Unknown result type (might be due to invalid IL or missing references)
        //IL_0607: Unknown result type (might be due to invalid IL or missing references)
        //IL_163f: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1abb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1869: Unknown result type (might be due to invalid IL or missing references)
        //IL_1740: Unknown result type (might be due to invalid IL or missing references)
        //IL_1746: Unknown result type (might be due to invalid IL or missing references)
        //IL_1750: Unknown result type (might be due to invalid IL or missing references)
        //IL_1755: Unknown result type (might be due to invalid IL or missing references)
        //IL_175a: Unknown result type (might be due to invalid IL or missing references)
        //IL_175c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0174: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c84: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c85: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c87: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c98: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ca2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ca4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ca9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bcd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bde: Unknown result type (might be due to invalid IL or missing references)
        //IL_1be4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1be9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bee: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bf8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bfd: Unknown result type (might be due to invalid IL or missing references)
        //IL_196a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1970: Unknown result type (might be due to invalid IL or missing references)
        //IL_197a: Unknown result type (might be due to invalid IL or missing references)
        //IL_197f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1984: Unknown result type (might be due to invalid IL or missing references)
        //IL_1986: Unknown result type (might be due to invalid IL or missing references)
        //IL_177f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1782: Unknown result type (might be due to invalid IL or missing references)
        //IL_178c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1791: Unknown result type (might be due to invalid IL or missing references)
        //IL_17be: Unknown result type (might be due to invalid IL or missing references)
        //IL_17c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_17e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_17ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_17f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_17f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1335: Unknown result type (might be due to invalid IL or missing references)
        //IL_1336: Unknown result type (might be due to invalid IL or missing references)
        //IL_1338: Unknown result type (might be due to invalid IL or missing references)
        //IL_1349: Unknown result type (might be due to invalid IL or missing references)
        //IL_134e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1353: Unknown result type (might be due to invalid IL or missing references)
        //IL_1355: Unknown result type (might be due to invalid IL or missing references)
        //IL_135a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e33: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cde: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ce0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ce5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ce7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_19ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_19af: Unknown result type (might be due to invalid IL or missing references)
        //IL_19b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_19be: Unknown result type (might be due to invalid IL or missing references)
        //IL_19ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_19f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a19: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a24: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a29: Unknown result type (might be due to invalid IL or missing references)
        //IL_138f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1391: Unknown result type (might be due to invalid IL or missing references)
        //IL_1396: Unknown result type (might be due to invalid IL or missing references)
        //IL_1398: Unknown result type (might be due to invalid IL or missing references)
        //IL_1382: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01be: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0201: Unknown result type (might be due to invalid IL or missing references)
        //IL_0207: Unknown result type (might be due to invalid IL or missing references)
        //IL_021e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0228: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d03: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d08: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cf5: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_13be: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0711: Unknown result type (might be due to invalid IL or missing references)
        //IL_34e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_34e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_34ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_34f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_34fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_3501: Unknown result type (might be due to invalid IL or missing references)
        //IL_3508: Unknown result type (might be due to invalid IL or missing references)
        //IL_253c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2541: Unknown result type (might be due to invalid IL or missing references)
        //IL_254b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2550: Unknown result type (might be due to invalid IL or missing references)
        //IL_1eb1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d13: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d18: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_16c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_16ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_16cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_16d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_16d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_13c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_13c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_13c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_13d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_13d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_13dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_13de: Unknown result type (might be due to invalid IL or missing references)
        //IL_13e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_13e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_13e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b38: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b50: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b55: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0782: Unknown result type (might be due to invalid IL or missing references)
        //IL_0785: Unknown result type (might be due to invalid IL or missing references)
        //IL_078f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0794: Unknown result type (might be due to invalid IL or missing references)
        //IL_0796: Unknown result type (might be due to invalid IL or missing references)
        //IL_0749: Unknown result type (might be due to invalid IL or missing references)
        //IL_0753: Unknown result type (might be due to invalid IL or missing references)
        //IL_0758: Unknown result type (might be due to invalid IL or missing references)
        //IL_0762: Unknown result type (might be due to invalid IL or missing references)
        //IL_0767: Unknown result type (might be due to invalid IL or missing references)
        //IL_076c: Unknown result type (might be due to invalid IL or missing references)
        //IL_076e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0773: Unknown result type (might be due to invalid IL or missing references)
        //IL_35b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_35c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_35c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b39: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b44: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_18ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_18f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_18f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_18fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_1903: Unknown result type (might be due to invalid IL or missing references)
        //IL_16f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_16f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_16fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1700: Unknown result type (might be due to invalid IL or missing references)
        //IL_16e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_16ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_16f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_14a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_13fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b84: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_35df: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d60: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d65: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d68: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d74: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d79: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b69: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b72: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b74: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b56: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b62: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b67: Unknown result type (might be due to invalid IL or missing references)
        //IL_191f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1923: Unknown result type (might be due to invalid IL or missing references)
        //IL_1928: Unknown result type (might be due to invalid IL or missing references)
        //IL_192a: Unknown result type (might be due to invalid IL or missing references)
        //IL_190c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1918: Unknown result type (might be due to invalid IL or missing references)
        //IL_191d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1714: Unknown result type (might be due to invalid IL or missing references)
        //IL_1419: Unknown result type (might be due to invalid IL or missing references)
        //IL_141b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dde: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ded: Unknown result type (might be due to invalid IL or missing references)
        //IL_0def: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e06: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e08: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e17: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c73: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c78: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0328: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_032f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0331: Unknown result type (might be due to invalid IL or missing references)
        //IL_031b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3614: Unknown result type (might be due to invalid IL or missing references)
        //IL_3638: Unknown result type (might be due to invalid IL or missing references)
        //IL_3642: Unknown result type (might be due to invalid IL or missing references)
        //IL_3647: Unknown result type (might be due to invalid IL or missing references)
        //IL_364c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3651: Unknown result type (might be due to invalid IL or missing references)
        //IL_3660: Unknown result type (might be due to invalid IL or missing references)
        //IL_366a: Unknown result type (might be due to invalid IL or missing references)
        //IL_366f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3674: Unknown result type (might be due to invalid IL or missing references)
        //IL_3676: Unknown result type (might be due to invalid IL or missing references)
        //IL_367d: Unknown result type (might be due to invalid IL or missing references)
        //IL_3683: Unknown result type (might be due to invalid IL or missing references)
        //IL_3688: Unknown result type (might be due to invalid IL or missing references)
        //IL_3607: Unknown result type (might be due to invalid IL or missing references)
        //IL_29b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_29b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_29c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_29cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_29d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_29d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_29d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_29d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_29e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_29ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_29ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_29f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a19: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a30: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a34: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a41: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a47: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a54: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a56: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a77: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a88: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ac0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ad0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ad6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ad8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2add: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ae7: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aec: Unknown result type (might be due to invalid IL or missing references)
        //IL_2af1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2af5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b02: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b08: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b15: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b17: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b50: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b52: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b57: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b61: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b66: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1eff: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f04: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d97: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1da1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d89: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b88: Unknown result type (might be due to invalid IL or missing references)
        //IL_193e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1730: Unknown result type (might be due to invalid IL or missing references)
        //IL_1732: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bcb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bcd: Unknown result type (might be due to invalid IL or missing references)
        //IL_082b: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07de: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0352: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b80: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b82: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b89: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b90: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ba3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bb2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bb4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bbe: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bcd: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bf2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bf9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bfe: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c09: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c12: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c19: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c26: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c39: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c42: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c47: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c51: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c56: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c82: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c87: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c92: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c94: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ca2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2caf: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cc4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cc6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ccb: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cd0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cda: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cdf: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ce5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ce7: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d04: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d10: Unknown result type (might be due to invalid IL or missing references)
        //IL_25db: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f52: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f54: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f59: Unknown result type (might be due to invalid IL or missing references)
        //IL_1da9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1db0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1db7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dbe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ba4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ba6: Unknown result type (might be due to invalid IL or missing references)
        //IL_195a: Unknown result type (might be due to invalid IL or missing references)
        //IL_195c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0840: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_035d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0362: Unknown result type (might be due to invalid IL or missing references)
        //IL_0364: Unknown result type (might be due to invalid IL or missing references)
        //IL_20f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f81: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f92: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e55: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e86: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ecd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eeb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cfc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d03: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d05: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d14: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d44: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d60: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d73: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d87: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d96: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bfd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0855: Unknown result type (might be due to invalid IL or missing references)
        //IL_0378: Unknown result type (might be due to invalid IL or missing references)
        //IL_086a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0394: Unknown result type (might be due to invalid IL or missing references)
        //IL_0396: Unknown result type (might be due to invalid IL or missing references)
        //IL_3206: Unknown result type (might be due to invalid IL or missing references)
        //IL_370b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3711: Unknown result type (might be due to invalid IL or missing references)
        //IL_371b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3720: Unknown result type (might be due to invalid IL or missing references)
        //IL_373e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3757: Unknown result type (might be due to invalid IL or missing references)
        //IL_3761: Unknown result type (might be due to invalid IL or missing references)
        //IL_3766: Unknown result type (might be due to invalid IL or missing references)
        //IL_376d: Unknown result type (might be due to invalid IL or missing references)
        //IL_377a: Unknown result type (might be due to invalid IL or missing references)
        //IL_377f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3784: Unknown result type (might be due to invalid IL or missing references)
        //IL_26e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_26e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_26ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_26fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_2700: Unknown result type (might be due to invalid IL or missing references)
        //IL_2705: Unknown result type (might be due to invalid IL or missing references)
        //IL_2707: Unknown result type (might be due to invalid IL or missing references)
        //IL_270c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1527: Unknown result type (might be due to invalid IL or missing references)
        //IL_152c: Unknown result type (might be due to invalid IL or missing references)
        //IL_152f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1534: Unknown result type (might be due to invalid IL or missing references)
        //IL_1539: Unknown result type (might be due to invalid IL or missing references)
        //IL_153b: Unknown result type (might be due to invalid IL or missing references)
        //IL_099d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0886: Unknown result type (might be due to invalid IL or missing references)
        //IL_0888: Unknown result type (might be due to invalid IL or missing references)
        //IL_088d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0896: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0420: Unknown result type (might be due to invalid IL or missing references)
        //IL_0426: Unknown result type (might be due to invalid IL or missing references)
        //IL_0428: Unknown result type (might be due to invalid IL or missing references)
        //IL_042d: Unknown result type (might be due to invalid IL or missing references)
        //IL_042f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e78: Unknown result type (might be due to invalid IL or missing references)
        //IL_2741: Unknown result type (might be due to invalid IL or missing references)
        //IL_2743: Unknown result type (might be due to invalid IL or missing references)
        //IL_2748: Unknown result type (might be due to invalid IL or missing references)
        //IL_274a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2734: Unknown result type (might be due to invalid IL or missing references)
        //IL_21ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_21ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_21f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2201: Unknown result type (might be due to invalid IL or missing references)
        //IL_2206: Unknown result type (might be due to invalid IL or missing references)
        //IL_220b: Unknown result type (might be due to invalid IL or missing references)
        //IL_220d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2212: Unknown result type (might be due to invalid IL or missing references)
        //IL_1557: Unknown result type (might be due to invalid IL or missing references)
        //IL_155c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1561: Unknown result type (might be due to invalid IL or missing references)
        //IL_1549: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_044b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0450: Unknown result type (might be due to invalid IL or missing references)
        //IL_0455: Unknown result type (might be due to invalid IL or missing references)
        //IL_043d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2766: Unknown result type (might be due to invalid IL or missing references)
        //IL_276b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2770: Unknown result type (might be due to invalid IL or missing references)
        //IL_2758: Unknown result type (might be due to invalid IL or missing references)
        //IL_2247: Unknown result type (might be due to invalid IL or missing references)
        //IL_2249: Unknown result type (might be due to invalid IL or missing references)
        //IL_224e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2250: Unknown result type (might be due to invalid IL or missing references)
        //IL_223a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffb: Unknown result type (might be due to invalid IL or missing references)
        //IL_09cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_09cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0914: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_045d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0464: Unknown result type (might be due to invalid IL or missing references)
        //IL_046b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0472: Unknown result type (might be due to invalid IL or missing references)
        //IL_37c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_37c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_37cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_37d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_37dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_37e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_37e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_37ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_3809: Unknown result type (might be due to invalid IL or missing references)
        //IL_382d: Unknown result type (might be due to invalid IL or missing references)
        //IL_383a: Unknown result type (might be due to invalid IL or missing references)
        //IL_383f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3844: Unknown result type (might be due to invalid IL or missing references)
        //IL_333c: Unknown result type (might be due to invalid IL or missing references)
        //IL_333d: Unknown result type (might be due to invalid IL or missing references)
        //IL_333f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3350: Unknown result type (might be due to invalid IL or missing references)
        //IL_3355: Unknown result type (might be due to invalid IL or missing references)
        //IL_335a: Unknown result type (might be due to invalid IL or missing references)
        //IL_335c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3361: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f52: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f53: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f55: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f66: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f70: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f72: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f77: Unknown result type (might be due to invalid IL or missing references)
        //IL_2772: Unknown result type (might be due to invalid IL or missing references)
        //IL_2776: Unknown result type (might be due to invalid IL or missing references)
        //IL_277b: Unknown result type (might be due to invalid IL or missing references)
        //IL_277d: Unknown result type (might be due to invalid IL or missing references)
        //IL_27a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_27af: Unknown result type (might be due to invalid IL or missing references)
        //IL_27b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_27b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_27b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_226c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2271: Unknown result type (might be due to invalid IL or missing references)
        //IL_2276: Unknown result type (might be due to invalid IL or missing references)
        //IL_225e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1017: Unknown result type (might be due to invalid IL or missing references)
        //IL_101c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1021: Unknown result type (might be due to invalid IL or missing references)
        //IL_1009: Unknown result type (might be due to invalid IL or missing references)
        //IL_0953: Unknown result type (might be due to invalid IL or missing references)
        //IL_092b: Unknown result type (might be due to invalid IL or missing references)
        //IL_090a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3396: Unknown result type (might be due to invalid IL or missing references)
        //IL_3398: Unknown result type (might be due to invalid IL or missing references)
        //IL_339d: Unknown result type (might be due to invalid IL or missing references)
        //IL_339f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3389: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fac: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fae: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fb3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_27cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2278: Unknown result type (might be due to invalid IL or missing references)
        //IL_227c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2281: Unknown result type (might be due to invalid IL or missing references)
        //IL_2283: Unknown result type (might be due to invalid IL or missing references)
        //IL_22a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_22ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_22ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_22b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_22b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1576: Unknown result type (might be due to invalid IL or missing references)
        //IL_157d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1584: Unknown result type (might be due to invalid IL or missing references)
        //IL_158b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1039: Unknown result type (might be due to invalid IL or missing references)
        //IL_1040: Unknown result type (might be due to invalid IL or missing references)
        //IL_1047: Unknown result type (might be due to invalid IL or missing references)
        //IL_104e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0992: Unknown result type (might be due to invalid IL or missing references)
        //IL_0996: Unknown result type (might be due to invalid IL or missing references)
        //IL_099b: Unknown result type (might be due to invalid IL or missing references)
        //IL_096a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0949: Unknown result type (might be due to invalid IL or missing references)
        //IL_33bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_33c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_33c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_33ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fdb: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fc3: Unknown result type (might be due to invalid IL or missing references)
        //IL_27e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_27ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_22c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0988: Unknown result type (might be due to invalid IL or missing references)
        //IL_33c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_33cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_33d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_33d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fe1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fe6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fe8: Unknown result type (might be due to invalid IL or missing references)
        //IL_22e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_22e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_33e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ffc: Unknown result type (might be due to invalid IL or missing references)
        //IL_27f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_27fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_2804: Unknown result type (might be due to invalid IL or missing references)
        //IL_2809: Unknown result type (might be due to invalid IL or missing references)
        //IL_280b: Unknown result type (might be due to invalid IL or missing references)
        //IL_282d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2833: Unknown result type (might be due to invalid IL or missing references)
        //IL_2835: Unknown result type (might be due to invalid IL or missing references)
        //IL_283a: Unknown result type (might be due to invalid IL or missing references)
        //IL_283c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1146: Unknown result type (might be due to invalid IL or missing references)
        //IL_1147: Unknown result type (might be due to invalid IL or missing references)
        //IL_1158: Unknown result type (might be due to invalid IL or missing references)
        //IL_115d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1160: Unknown result type (might be due to invalid IL or missing references)
        //IL_1165: Unknown result type (might be due to invalid IL or missing references)
        //IL_116c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1171: Unknown result type (might be due to invalid IL or missing references)
        //IL_1173: Unknown result type (might be due to invalid IL or missing references)
        //IL_3402: Unknown result type (might be due to invalid IL or missing references)
        //IL_3409: Unknown result type (might be due to invalid IL or missing references)
        //IL_340e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3018: Unknown result type (might be due to invalid IL or missing references)
        //IL_301f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3024: Unknown result type (might be due to invalid IL or missing references)
        //IL_2858: Unknown result type (might be due to invalid IL or missing references)
        //IL_285d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2862: Unknown result type (might be due to invalid IL or missing references)
        //IL_284a: Unknown result type (might be due to invalid IL or missing references)
        //IL_22f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_22f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2300: Unknown result type (might be due to invalid IL or missing references)
        //IL_2305: Unknown result type (might be due to invalid IL or missing references)
        //IL_2307: Unknown result type (might be due to invalid IL or missing references)
        //IL_2329: Unknown result type (might be due to invalid IL or missing references)
        //IL_232f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2331: Unknown result type (might be due to invalid IL or missing references)
        //IL_2336: Unknown result type (might be due to invalid IL or missing references)
        //IL_2338: Unknown result type (might be due to invalid IL or missing references)
        //IL_118f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1194: Unknown result type (might be due to invalid IL or missing references)
        //IL_1199: Unknown result type (might be due to invalid IL or missing references)
        //IL_1181: Unknown result type (might be due to invalid IL or missing references)
        //IL_2866: Unknown result type (might be due to invalid IL or missing references)
        //IL_286d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2874: Unknown result type (might be due to invalid IL or missing references)
        //IL_287b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2354: Unknown result type (might be due to invalid IL or missing references)
        //IL_2359: Unknown result type (might be due to invalid IL or missing references)
        //IL_235e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2346: Unknown result type (might be due to invalid IL or missing references)
        //IL_341c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3421: Unknown result type (might be due to invalid IL or missing references)
        //IL_3428: Unknown result type (might be due to invalid IL or missing references)
        //IL_342d: Unknown result type (might be due to invalid IL or missing references)
        //IL_342f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3440: Unknown result type (might be due to invalid IL or missing references)
        //IL_3445: Unknown result type (might be due to invalid IL or missing references)
        //IL_344a: Unknown result type (might be due to invalid IL or missing references)
        //IL_344c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3032: Unknown result type (might be due to invalid IL or missing references)
        //IL_3037: Unknown result type (might be due to invalid IL or missing references)
        //IL_303e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3059: Unknown result type (might be due to invalid IL or missing references)
        //IL_305e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3060: Unknown result type (might be due to invalid IL or missing references)
        //IL_2362: Unknown result type (might be due to invalid IL or missing references)
        //IL_2369: Unknown result type (might be due to invalid IL or missing references)
        //IL_2370: Unknown result type (might be due to invalid IL or missing references)
        //IL_2377: Unknown result type (might be due to invalid IL or missing references)
        //IL_3468: Unknown result type (might be due to invalid IL or missing references)
        //IL_346d: Unknown result type (might be due to invalid IL or missing references)
        //IL_3472: Unknown result type (might be due to invalid IL or missing references)
        //IL_345a: Unknown result type (might be due to invalid IL or missing references)
        //IL_307c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3081: Unknown result type (might be due to invalid IL or missing references)
        //IL_3086: Unknown result type (might be due to invalid IL or missing references)
        //IL_306e: Unknown result type (might be due to invalid IL or missing references)
        //IL_295f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2966: Unknown result type (might be due to invalid IL or missing references)
        //IL_296d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2974: Unknown result type (might be due to invalid IL or missing references)
        //IL_23cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_23d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_23d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_23dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_23de: Unknown result type (might be due to invalid IL or missing references)
        //IL_2400: Unknown result type (might be due to invalid IL or missing references)
        //IL_2406: Unknown result type (might be due to invalid IL or missing references)
        //IL_2408: Unknown result type (might be due to invalid IL or missing references)
        //IL_240d: Unknown result type (might be due to invalid IL or missing references)
        //IL_240f: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_11da: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_3474: Unknown result type (might be due to invalid IL or missing references)
        //IL_3476: Unknown result type (might be due to invalid IL or missing references)
        //IL_347a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3481: Unknown result type (might be due to invalid IL or missing references)
        //IL_3488: Unknown result type (might be due to invalid IL or missing references)
        //IL_348f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3088: Unknown result type (might be due to invalid IL or missing references)
        //IL_3099: Unknown result type (might be due to invalid IL or missing references)
        //IL_309e: Unknown result type (might be due to invalid IL or missing references)
        //IL_30a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_30a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_30ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_30b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_30bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_28b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_28ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_28d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_28d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_28db: Unknown result type (might be due to invalid IL or missing references)
        //IL_28dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_242b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2430: Unknown result type (might be due to invalid IL or missing references)
        //IL_2435: Unknown result type (might be due to invalid IL or missing references)
        //IL_241d: Unknown result type (might be due to invalid IL or missing references)
        //IL_28f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_28fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_2903: Unknown result type (might be due to invalid IL or missing references)
        //IL_28eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_2439: Unknown result type (might be due to invalid IL or missing references)
        //IL_2440: Unknown result type (might be due to invalid IL or missing references)
        //IL_2447: Unknown result type (might be due to invalid IL or missing references)
        //IL_244e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2907: Unknown result type (might be due to invalid IL or missing references)
        //IL_290e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2915: Unknown result type (might be due to invalid IL or missing references)
        //IL_291c: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        float num = (float)Math.PI / 2f;
        Vector2 vector = player.RotatedRelativePoint(player.MountedCenter);
        int num12 = 2;
        float num23 = 0f;
        if (type == 439)
        {
            ai[0] += 1f;
            int num34 = 0;
            if (ai[0] >= 40f)
            {
                num34++;
            }
            if (ai[0] >= 80f)
            {
                num34++;
            }
            if (ai[0] >= 120f)
            {
                num34++;
            }
            int num45 = 24;
            int num56 = 6;
            ai[1] += 1f;
            bool flag = false;
            if (ai[1] >= (float)(num45 - num56 * num34))
            {
                ai[1] = 0f;
                flag = true;
            }
            frameCounter += 1 + num34;
            if (frameCounter >= 4)
            {
                frameCounter = 0;
                frame++;
                if (frame >= 6)
                {
                    frame = 0;
                }
            }
            if (soundDelay <= 0)
            {
                soundDelay = num45 - num56 * num34;
                if (ai[0] != 1f)
                {
                    SoundEngine.PlaySound(in SoundID.Item91, position);
                }
            }
            if (ai[1] == 1f && ai[0] != 1f)
            {
                Vector2 spinningpoint = Vector2.UnitX * 24f;
                spinningpoint = spinningpoint.RotatedBy(rotation - (float)Math.PI / 2f);
                Vector2 vector12 = base.Center + spinningpoint;
                for (int i = 0; i < 2; i++)
                {
                    int num66 = Dust.NewDust(vector12 - Vector2.One * 8f, 16, 16, 135, velocity.X / 2f, velocity.Y / 2f, 100);
                    Dust obj = Main.dust[num66];
                    obj.velocity *= 0.66f;
                    Main.dust[num66].noGravity = true;
                    Main.dust[num66].scale = 1.4f;
                }
            }
            if (flag && Main.myPlayer == owner)
            {
                if (player.channel && player.CheckMana(player.inventory[player.selectedItem], -1, pay: true) && !player.noItems && !player.CCed)
                {
                    float num77 = player.inventory[player.selectedItem].shootSpeed * scale;
                    Vector2 vector23 = vector;
                    Vector2 value = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY) - vector23;
                    if (player.gravDir == -1f)
                    {
                        value.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector23.Y;
                    }
                    Vector2 vector34 = Vector2.Normalize(value);
                    if (float.IsNaN(vector34.X) || float.IsNaN(vector34.Y))
                    {
                        vector34 = -Vector2.UnitY;
                    }
                    vector34 *= num77;
                    if (vector34.X != velocity.X || vector34.Y != velocity.Y)
                    {
                        netUpdate = true;
                    }
                    velocity = vector34;
                    int num79 = 440;
                    float num2 = 14f;
                    int num3 = 7;
                    for (int j = 0; j < 2; j++)
                    {
                        vector23 = base.Center + new Vector2((float)Main.rand.Next(-num3, num3 + 1), (float)Main.rand.Next(-num3, num3 + 1));
                        Vector2 spinningpoint3 = Vector2.Normalize(velocity) * num2;
                        spinningpoint3 = spinningpoint3.RotatedBy(Main.rand.NextDouble() * 0.19634954631328583 - 0.09817477315664291);
                        if (float.IsNaN(spinningpoint3.X) || float.IsNaN(spinningpoint3.Y))
{
                            spinningpoint3 = -Vector2.UnitY;
                        }
                        NewProjectile(GetProjectileSource_FromThis(), vector23.X, vector23.Y, spinningpoint3.X, spinningpoint3.Y, num79, damage, knockBack, owner);
                    }
                }
                else
                {
                    Kill();
                }
            }
        }
        if (type == 445)
        {
            if (soundDelay <= 0)
            {
                SoundEngine.PlaySound(in SoundID.Item132, position);
                soundDelay = 23;
            }
            localAI[0] += 1f;
            if (localAI[0] >= 60f)
            {
                localAI[0] = 0f;
            }
            if (Vector2.Distance(vector, base.Center) >= 5f)
            {
                float num4 = localAI[0] / 60f;
                if (num4 > 0.5f)
                {
                    num4 = 1f - num4;
                }
                Vector3 val = new Vector3(0f, 1f, 0.7f);
                Vector3 value5 = default(Vector3);
                ((Vector3)(ref value5))._002Ector(0f, 0.7f, 1f);
                Vector3 vector35 = Vector3.Lerp(val, value5, 1f - num4 * 2f) * 0.5f;
                if (Vector2.Distance(vector, base.Center) >= 30f)
                {
                    Vector2 vector36 = base.Center - vector;
                    ((Vector2)(ref vector36)).Normalize();
                    vector36 *= Vector2.Distance(vector, base.Center) - 30f;
                    DelegateMethods.v3_1 = vector35 * 0.8f;
                    Utils.PlotTileLine(base.Center - vector36, base.Center, 8f, DelegateMethods.CastLightOpen);
                }
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, vector35.X, vector35.Y, vector35.Z);
            }
            if (Main.myPlayer == owner)
            {
                if (localAI[1] > 0f)
                {
                    localAI[1] -= 1f;
                }
                if (!player.channel || player.noItems || player.CCed)
                {
                    Kill();
                }
                else if (localAI[1] == 0f)
                {
                    Vector2 vector37 = vector;
                    Vector2 value6 = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY) - vector37;
                    if (player.gravDir == -1f)
                    {
                        value6.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector37.Y;
                    }
                    if (Main.tile[Player.tileTargetX, Player.tileTargetY].active())
                    {
                        value6 = new Vector2((float)Player.tileTargetX, (float)Player.tileTargetY) * 16f + Vector2.One * 8f - vector37;
                        localAI[1] = 2f;
                    }
                    value6 = Vector2.Lerp(value6, velocity, 0.7f);
                    if (float.IsNaN(value6.X) || float.IsNaN(value6.Y))
                    {
                        value6 = -Vector2.UnitY;
                    }
                    float num5 = 30f;
                    if (((Vector2)(ref value6)).Length() < num5)
                    {
                        value6 = Vector2.Normalize(value6) * num5;
                    }
                    int tileBoost = player.inventory[player.selectedItem].tileBoost;
                    int num6 = -Player.tileRangeX - tileBoost + 1;
                    int num7 = Player.tileRangeX + tileBoost - 1;
                    int num8 = -Player.tileRangeY - tileBoost;
                    int num9 = Player.tileRangeY + tileBoost - 1;
                    int num10 = 12;
                    bool flag7 = false;
                    if (value6.X < (float)(num6 * 16 - num10))
                    {
                        flag7 = true;
                    }
                    if (value6.Y < (float)(num8 * 16 - num10))
                    {
                        flag7 = true;
                    }
                    if (value6.X > (float)(num7 * 16 + num10))
                    {
                        flag7 = true;
                    }
                    if (value6.Y > (float)(num9 * 16 + num10))
                    {
                        flag7 = true;
                    }
                    if (flag7)
                    {
                        Vector2 vector38 = Vector2.Normalize(value6);
                        float num11 = -1f;
                        if (vector38.X < 0f && ((float)(num6 * 16 - num10) / vector38.X < num11 || num11 == -1f))
{
                            num11 = (float)(num6 * 16 - num10) / vector38.X;
                        }
                        if (vector38.X > 0f && ((float)(num7 * 16 + num10) / vector38.X < num11 || num11 == -1f))
{
                            num11 = (float)(num7 * 16 + num10) / vector38.X;
                        }
                        if (vector38.Y < 0f && ((float)(num8 * 16 - num10) / vector38.Y < num11 || num11 == -1f))
{
                            num11 = (float)(num8 * 16 - num10) / vector38.Y;
                        }
                        if (vector38.Y > 0f && ((float)(num9 * 16 + num10) / vector38.Y < num11 || num11 == -1f))
{
                            num11 = (float)(num9 * 16 + num10) / vector38.Y;
                        }
                        value6 = vector38 * num11;
                    }
                    if (value6.X != velocity.X || value6.Y != velocity.Y)
                    {
                        netUpdate = true;
                    }
                    velocity = value6;
                }
            }
        }
        if (type == 460)
        {
            ai[0] += 1f;
            int num13 = 0;
            if (ai[0] >= 80f)
            {
                num13++;
            }
            if (ai[0] >= 180f)
            {
                num13++;
            }
            bool flag8 = false;
            _ = ai[0];
            if (ai[0] == 80f || ai[0] == 180f || (ai[0] > 180f && ai[0] % 20f == 0f))
            {
                flag8 = true;
            }
            bool flag9 = ai[0] >= 180f;
            int num14 = 5;
            if (!flag9)
            {
                ai[1] += 1f;
            }
            bool flag10 = false;
            if (ai[0] == 1f)
            {
                flag10 = true;
            }
            if (flag9 && ai[0] % 20f == 0f)
            {
                flag10 = true;
            }
            if ((!flag9 && ai[1] >= (float)num14) || (flag9 && ai[0] % 5f == 0f))
            {
                if (!flag9)
                {
                    ai[1] = 0f;
                }
                flag10 = true;
                float num15 = player.inventory[player.selectedItem].shootSpeed * scale;
                Vector2 vector39 = vector;
                Vector2 value7 = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY) - vector39;
                if (player.gravDir == -1f)
                {
                    value7.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector39.Y;
                }
                Vector2 vector2 = Vector2.Normalize(value7);
                if (float.IsNaN(vector2.X) || float.IsNaN(vector2.Y))
                {
                    vector2 = -Vector2.UnitY;
                }
                vector2 *= num15;
                if (vector2.X != velocity.X || vector2.Y != velocity.Y)
                {
                    netUpdate = true;
                }
                velocity = vector2;
            }
            if (soundDelay <= 0 && !flag9)
            {
                soundDelay = num14 - num13;
                soundDelay *= 2;
                if (ai[0] != 1f)
                {
                    SoundEngine.PlaySound(in SoundID.Item15, position);
                }
            }
            if (ai[0] > 10f && !flag9)
            {
                Vector2 spinningpoint4 = Vector2.UnitX * 18f;
                spinningpoint4 = spinningpoint4.RotatedBy(rotation - (float)Math.PI / 2f);
                Vector2 vector3 = base.Center + spinningpoint4;
                for (int k = 0; k < num13 + 1; k++)
                {
                    int num16 = 226;
                    float num17 = 0.4f;
                    if (k % 2 == 1)
                    {
                        num16 = 226;
                        num17 = 0.65f;
                    }
                    Vector2 vector4 = vector3 + ((float)Main.rand.NextDouble() * ((float)Math.PI * 2f)).ToRotationVector2() * (12f - (float)(num13 * 2));
                    int num18 = Dust.NewDust(vector4 - Vector2.One * 8f, 16, 16, num16, velocity.X / 2f, velocity.Y / 2f);
                    Main.dust[num18].velocity = Vector2.Normalize(vector3 - vector4) * 1.5f * (10f - (float)num13 * 2f) / 10f;
                    Main.dust[num18].noGravity = true;
                    Main.dust[num18].scale = num17;
                    Main.dust[num18].customData = player;
                }
            }
            if (flag9)
            {
                Vector2 spinningpoint5 = Vector2.UnitX * 14f;
                spinningpoint5 = spinningpoint5.RotatedBy(rotation - (float)Math.PI / 2f);
                Vector2 vector5 = base.Center + spinningpoint5;
                for (int l = 0; l < 2; l++)
                {
                    int num19 = 226;
                    float num20 = 0.35f;
                    if (l % 2 == 1)
                    {
                        num19 = 226;
                        num20 = 0.45f;
                    }
                    float num21 = Main.rand.NextFloatDirection();
                    Vector2 vector6 = vector5 + (rotation + num21 * ((float)Math.PI / 4f) * 0.8f - (float)Math.PI / 2f).ToRotationVector2() * 6f;
                    int num22 = 24;
                    int num24 = Dust.NewDust(vector6 - Vector2.One * (float)(num22 / 2), num22, num22, num19, velocity.X / 2f, velocity.Y / 2f);
                    Main.dust[num24].velocity = (vector6 - vector5).SafeNormalize(Vector2.Zero) * MathHelper.Lerp(1.5f, 9f, Utils.GetLerpValue(1f, 0f, Math.Abs(num21), clamped: true));
                    Main.dust[num24].noGravity = true;
                    Main.dust[num24].scale = num20;
                    Main.dust[num24].customData = player;
                    Main.dust[num24].fadeIn = 0.5f;
                }
            }
            if (flag10 && Main.myPlayer == owner)
            {
                bool flag11 = false;
                flag11 = !flag8 || player.CheckMana(player.inventory[player.selectedItem], -1, pay: true);
                if (player.channel && flag11 && !player.noItems && !player.CCed)
                {
                    if (ai[0] == 180f)
                    {
                        Vector2 center = base.Center;
                        Vector2 vector7 = Vector2.Normalize(velocity);
                        if (float.IsNaN(vector7.X) || float.IsNaN(vector7.Y))
{
                            vector7 = -Vector2.UnitY;
                        }
                        int num25 = (int)((float)damage * 1.5f);
                        int num26 = NewProjectile(GetProjectileSource_FromThis(), center.X, center.Y, vector7.X, vector7.Y, 461, num25, knockBack, owner, 0f, whoAmI);
                        ai[1] = num26;
                        netUpdate = true;
                    }
                    else if (flag9)
                    {
                        Projectile projectile = Main.projectile[(int)ai[1]];
                        if (!projectile.active || projectile.type != 461)
{
                            Kill();
                            return;
                        }
                    }
                    else
                    {
                        bool flag12 = false;
                        if (ai[0] == 1f)
{
                            flag12 = true;
                        }
                        if (ai[0] <= 50f && ai[0] % 10f == 0f)
{
                            flag12 = true;
                        }
                        if (ai[0] >= 80f && ai[0] < 180f && ai[0] % 30f == 0f)
{
                            flag12 = true;
                        }
                        if (flag12)
{
                            Vector2 vector8 = vector;
                            int num27 = 459;
                            float num28 = 10f;
                            vector8 = base.Center;
                            Vector2 vector9 = Vector2.Normalize(velocity) * num28;
                            if (float.IsNaN(vector9.X) || float.IsNaN(vector9.Y))
{
                                vector9 = -Vector2.UnitY;
                            }
                            float num29 = 0.7f + (float)num13 * 0.3f;
                            int num30 = ((num29 < 1f) ? damage : ((int)((float)damage * 2.5f)));
                            NewProjectile(GetProjectileSource_FromThis(), vector8.X, vector8.Y, vector9.X, vector9.Y, num27, num30, knockBack, owner, 0f, num29);
                        }
                    }
                }
                else
                {
                    Kill();
                }
            }
        }
        if (type == 633)
        {
            float num31 = 30f;
            if (ai[0] > 90f)
            {
                num31 = 15f;
            }
            if (ai[0] > 120f)
            {
                num31 = 5f;
            }
            damage = (int)player.GetTotalDamage(DamageClass.Magic).ApplyTo(player.inventory[player.selectedItem].damage);
            ai[0] += 1f;
            ai[1] += 1f;
            bool flag13 = false;
            if (ai[0] % num31 == 0f)
            {
                flag13 = true;
            }
            int num32 = 10;
            bool flag14 = false;
            if (ai[0] % num31 == 0f)
            {
                flag14 = true;
            }
            if (ai[1] >= 1f)
            {
                ai[1] = 0f;
                flag14 = true;
                if (Main.myPlayer == owner)
                {
                    float num33 = player.inventory[player.selectedItem].shootSpeed * scale;
                    Vector2 vector10 = vector;
                    Vector2 value8 = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY) - vector10;
                    if (player.gravDir == -1f)
                    {
                        value8.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector10.Y;
                    }
                    Vector2 value9 = Vector2.Normalize(value8);
                    if (float.IsNaN(value9.X) || float.IsNaN(value9.Y))
                    {
                        value9 = -Vector2.UnitY;
                    }
                    value9 = Vector2.Normalize(Vector2.Lerp(value9, Vector2.Normalize(velocity), 0.92f));
                    value9 *= num33;
                    if (value9.X != velocity.X || value9.Y != velocity.Y)
                    {
                        netUpdate = true;
                    }
                    velocity = value9;
                }
            }
            frameCounter++;
            int num35 = ((!(ai[0] < 120f)) ? 1 : 4);
            if (frameCounter >= num35)
            {
                frameCounter = 0;
                if (++frame >= 5)
                {
                    frame = 0;
                }
            }
            if (soundDelay <= 0)
            {
                soundDelay = num32;
                soundDelay *= 2;
                if (ai[0] != 1f)
                {
                    SoundEngine.PlaySound(in SoundID.Item15, position);
                }
            }
            if (flag14 && Main.myPlayer == owner)
            {
                bool flag2 = false;
                flag2 = !flag13 || player.CheckMana(player.inventory[player.selectedItem], -1, pay: true);
                if (player.channel && flag2 && !player.noItems && !player.CCed)
                {
                    if (ai[0] == 1f)
                    {
                        Vector2 center2 = base.Center;
                        Vector2 vector11 = Vector2.Normalize(velocity);
                        if (float.IsNaN(vector11.X) || float.IsNaN(vector11.Y))
{
                            vector11 = -Vector2.UnitY;
                        }
                        int num36 = damage;
                        for (int m = 0; m < 6; m++)
{
                            NewProjectile(GetProjectileSource_FromThis(), center2.X, center2.Y, vector11.X, vector11.Y, 632, num36, knockBack, owner, m, whoAmI);
                        }
                        netUpdate = true;
                    }
                }
                else
                {
                    Kill();
                }
            }
        }
        if (type == 595)
        {
            num = 0f;
            if (spriteDirection == -1)
            {
                num = (float)Math.PI;
            }
            if (++frame >= Main.projFrames[type])
            {
                frame = 0;
            }
            soundDelay--;
            if (soundDelay <= 0)
            {
                SoundEngine.PlaySound(in SoundID.Item1, base.Center);
                soundDelay = 12;
            }
            if (Main.myPlayer == owner)
            {
                if (player.channel && !player.noItems && !player.CCed)
                {
                    float num37 = 1f;
                    if (player.inventory[player.selectedItem].shoot == type)
                    {
                        num37 = player.inventory[player.selectedItem].shootSpeed * scale;
                    }
                    Vector2 vec = Main.MouseWorld - vector;
                    ((Vector2)(ref vec)).Normalize();
                    if (vec.HasNaNs())
                    {
                        vec = Vector2.UnitX * (float)player.direction;
                    }
                    vec *= num37;
                    if (vec.X != velocity.X || vec.Y != velocity.Y)
                    {
                        netUpdate = true;
                    }
                    velocity = vec;
                }
                else
                {
                    Kill();
                }
            }
            Vector2 vector13 = base.Center + velocity * 3f;
            Lighting.AddLight(vector13, 0.8f, 0.8f, 0.8f);
            if (Main.rand.Next(3) == 0)
            {
                int num38 = Dust.NewDust(vector13 - base.Size / 2f, width, height, 63, velocity.X, velocity.Y, 100, default(Color), 2f);
                Main.dust[num38].noGravity = true;
                Dust obj2 = Main.dust[num38];
                obj2.position -= velocity;
            }
        }
        if (type == 735)
        {
            num = 0f;
            if (spriteDirection == -1)
            {
                num = (float)Math.PI;
            }
            if (++frame >= Main.projFrames[type])
            {
                frame = 0;
            }
            soundDelay--;
            if (soundDelay <= 0)
            {
                SoundEngine.PlaySound(in SoundID.Item1, base.Center);
                soundDelay = 12;
            }
            if (Main.myPlayer == owner)
            {
                if (player.channel && !player.noItems && !player.CCed)
                {
                    float num39 = 1f;
                    if (player.inventory[player.selectedItem].shoot == type)
                    {
                        num39 = player.inventory[player.selectedItem].shootSpeed * scale;
                    }
                    Vector2 vec2 = Main.MouseWorld - vector;
                    ((Vector2)(ref vec2)).Normalize();
                    if (vec2.HasNaNs())
                    {
                        vec2 = Vector2.UnitX * (float)player.direction;
                    }
                    vec2 *= num39;
                    if (vec2.X != velocity.X || vec2.Y != velocity.Y)
                    {
                        netUpdate = true;
                    }
                    velocity = vec2;
                }
                else
                {
                    Kill();
                }
            }
            Vector2 vector14 = base.Center + velocity * 3f;
            Lighting.AddLight(vector14, 0.8f, 0.8f, 0.8f);
            if (Main.rand.Next(3) == 0)
            {
                int num40 = Dust.NewDust(vector14 - base.Size / 2f, width, height, 302, velocity.X, velocity.Y, 100, default(Color), 2f);
                Main.dust[num40].noGravity = true;
                Dust obj3 = Main.dust[num40];
                obj3.position -= velocity;
            }
        }
        if (type == 927)
        {
            num = 0f;
            scale = ai[1];
            ai[0] += 1f;
            if (ai[0] >= 8f)
            {
                ai[0] = 0f;
            }
            num12 = 9;
            num23 = Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.05f;
            soundDelay--;
            if (soundDelay <= 0)
            {
                SoundEngine.PlaySound(in SoundID.Item1, base.Center);
                soundDelay = 6;
            }
            if (Main.myPlayer == owner)
            {
                if (player.channel && !player.noItems && !player.CCed)
                {
                    float num41 = 1f;
                    if (player.inventory[player.selectedItem].shoot == type)
                    {
                        num41 = player.inventory[player.selectedItem].shootSpeed;
                    }
                    Vector2 vec3 = Main.MouseWorld - vector;
                    ((Vector2)(ref vec3)).Normalize();
                    if (vec3.HasNaNs())
                    {
                        vec3 = Vector2.UnitX * (float)player.direction;
                    }
                    vec3 *= num41;
                    if (vec3.X != velocity.X || vec3.Y != velocity.Y)
                    {
                        netUpdate = true;
                    }
                    velocity = vec3;
                }
                else
                {
                    Kill();
                }
            }
            DelegateMethods.v3_1 = new Vector3(0.5f, 0.5f, 0.5f);
            Utils.PlotTileLine(base.Center - velocity, base.Center + velocity.SafeNormalize(Vector2.Zero) * 80f, 16f, DelegateMethods.CastLightOpen);
        }
        if (type == 600)
        {
            _ = ai[0];
            ai[0] += 1f;
            if (Main.myPlayer == owner && ai[0] == 1f)
            {
                float num42 = player.inventory[player.selectedItem].shootSpeed * scale;
                Vector2 vector15 = vector;
                Vector2 value10 = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY) - vector15;
                if (player.gravDir == -1f)
                {
                    value10.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector15.Y;
                }
                Vector2 vector16 = Vector2.Normalize(value10);
                if (float.IsNaN(vector16.X) || float.IsNaN(vector16.Y))
                {
                    vector16 = -Vector2.UnitY;
                }
                vector16 *= num42;
                if (vector16.X != velocity.X || vector16.Y != velocity.Y)
                {
                    netUpdate = true;
                }
                velocity = vector16;
                int num43 = 601;
                float num44 = 3f;
                vector15 = base.Center;
                Vector2 vector17 = Vector2.Normalize(velocity) * num44;
                if (float.IsNaN(vector17.X) || float.IsNaN(vector17.Y))
                {
                    vector17 = -Vector2.UnitY;
                }
                NewProjectile(GetProjectileSource_FromThis(), vector15.X, vector15.Y, vector17.X, vector17.Y, num43, damage, knockBack, owner, ai[1]);
            }
            if (ai[0] >= 30f)
            {
                Kill();
            }
        }
        if (type == 611)
        {
            if (Main.netMode != 2 && localAI[0] == 0f)
            {
                SoundEngine.PlaySound(in SoundID.Item116, base.Center);
            }
            if (localAI[1] > 0f)
            {
                localAI[1] -= 1f;
            }
            alpha -= 42;
            if (alpha < 0)
            {
                alpha = 0;
            }
            if (localAI[0] == 0f)
            {
                localAI[0] = velocity.ToRotation();
            }
            float num46 = ((localAI[0].ToRotationVector2().X >= 0f) ? 1 : (-1));
            if (ai[1] <= 0f)
            {
                num46 *= -1f;
            }
            Vector2 spinningpoint6 = (num46 * (ai[0] / 30f * ((float)Math.PI * 2f) - (float)Math.PI / 2f)).ToRotationVector2();
            spinningpoint6.Y *= (float)Math.Sin(ai[1]);
            if (ai[1] <= 0f)
            {
                spinningpoint6.Y *= -1f;
            }
            spinningpoint6 = spinningpoint6.RotatedBy(localAI[0]);
            ai[0] += 1f;
            if (ai[0] < 30f)
            {
                velocity += 48f * spinningpoint6;
            }
            else
            {
                Kill();
            }
        }
        if (type == 615)
        {
            num = 0f;
            if (spriteDirection == -1)
            {
                num = (float)Math.PI;
            }
            ai[0] += 1f;
            int num47 = 0;
            if (ai[0] >= 40f)
            {
                num47++;
            }
            if (ai[0] >= 80f)
            {
                num47++;
            }
            if (ai[0] >= 120f)
            {
                num47++;
            }
            int num48 = 5;
            int num49 = 0;
            ai[1] -= 1f;
            bool flag3 = false;
            int num50 = -1;
            if (ai[1] <= 0f)
            {
                ai[1] = num48 - num49 * num47;
                flag3 = true;
                if ((int)ai[0] / (num48 - num49 * num47) % 7 == 0)
                {
                    num50 = 0;
                }
            }
            frameCounter += 1 + num47;
            if (frameCounter >= 4)
            {
                frameCounter = 0;
                frame++;
                if (frame >= Main.projFrames[type])
                {
                    frame = 0;
                }
            }
            if (soundDelay <= 0)
            {
                soundDelay = num48 - num49 * num47;
                if (ai[0] != 1f)
                {
                    SoundEngine.PlaySound(in SoundID.Item36, position);
                }
            }
            if (flag3 && Main.myPlayer == owner)
            {
                bool canShoot = player.channel && player.HasAmmo(player.inventory[player.selectedItem], canUse: true) && !player.noItems && !player.CCed;
                int projToShoot = 14;
                float speed = 14f;
                int Damage = player.GetWeaponDamage(player.inventory[player.selectedItem]);
                float KnockBack = player.inventory[player.selectedItem].knockBack;
                if (canShoot)
                {
                    player.PickAmmo(player.inventory[player.selectedItem], ref projToShoot, ref speed, ref canShoot, ref Damage, ref KnockBack, out var usedAmmoItemId);
                    IEntitySource projectileSource_Item_WithPotentialAmmo = player.GetProjectileSource_Item_WithPotentialAmmo(player.HeldItem, usedAmmoItemId);
                    KnockBack = player.GetWeaponKnockback(player.inventory[player.selectedItem], KnockBack);
                    float num51 = player.inventory[player.selectedItem].shootSpeed * scale;
                    Vector2 vector18 = vector;
                    Vector2 value11 = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY) - vector18;
                    if (player.gravDir == -1f)
                    {
                        value11.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector18.Y;
                    }
                    Vector2 spinningpoint7 = Vector2.Normalize(value11);
                    if (float.IsNaN(spinningpoint7.X) || float.IsNaN(spinningpoint7.Y))
                    {
                        spinningpoint7 = -Vector2.UnitY;
                    }
                    spinningpoint7 *= num51;
                    spinningpoint7 = spinningpoint7.RotatedBy(Main.rand.NextDouble() * 0.13089969754219055 - 0.06544984877109528);
                    if (spinningpoint7.X != velocity.X || spinningpoint7.Y != velocity.Y)
                    {
                        netUpdate = true;
                    }
                    velocity = spinningpoint7;
                    for (int n = 0; n < 1; n++)
                    {
                        Vector2 spinningpoint8 = Vector2.Normalize(velocity) * speed;
                        spinningpoint8 = spinningpoint8.RotatedBy(Main.rand.NextDouble() * 0.19634954631328583 - 0.09817477315664291);
                        if (float.IsNaN(spinningpoint8.X) || float.IsNaN(spinningpoint8.Y))
{
                            spinningpoint8 = -Vector2.UnitY;
                        }
                        NewProjectile(projectileSource_Item_WithPotentialAmmo, vector18.X, vector18.Y, spinningpoint8.X, spinningpoint8.Y, projToShoot, Damage, KnockBack, owner);
                    }
                    if (num50 == 0)
                    {
                        projToShoot = 616;
                        speed = 8f;
                        for (int num52 = 0; num52 < 1; num52++)
{
                            Vector2 spinningpoint9 = Vector2.Normalize(velocity) * speed;
                            spinningpoint9 = spinningpoint9.RotatedBy(Main.rand.NextDouble() * 0.39269909262657166 - 0.19634954631328583);
                            if (float.IsNaN(spinningpoint9.X) || float.IsNaN(spinningpoint9.Y))
{
                                spinningpoint9 = -Vector2.UnitY;
                            }
                            NewProjectile(projectileSource_Item_WithPotentialAmmo, vector18.X, vector18.Y, spinningpoint9.X, spinningpoint9.Y, projToShoot, Damage + 20, KnockBack * 1.25f, owner);
                        }
                    }
                }
                else
                {
                    Kill();
                }
            }
        }
        if (type == 714)
        {
            num = 0f;
            if (spriteDirection == -1)
            {
                num = (float)Math.PI;
            }
            ai[0] += 1f;
            int num53 = 0;
            int num54 = 8;
            int num55 = 0;
            ai[1] -= 1f;
            bool flag4 = false;
            int num57 = -1;
            if (ai[1] <= 0f)
            {
                ai[1] = num54 - num55 * num53;
                flag4 = true;
                int num80 = (int)ai[0] / (num54 - num55 * num53);
                if (num80 % 7 == 0)
                {
                    num57 = 0;
                }
                num57 = num80 % 7;
            }
            _ = rotation;
            Vector2 center3 = base.Center;
            _ = direction;
            Vector2 v = velocity;
            frameCounter += 1 + num53;
            if (frameCounter >= 4)
            {
                frameCounter = 0;
                frame++;
                if (frame >= Main.projFrames[type])
                {
                    frame = 0;
                }
            }
            if (soundDelay <= 0 && Main.player[owner].controlUseItem)
            {
                soundDelay = num54 - num55 * num53;
                if (ai[0] != 1f)
                {
                    SoundEngine.PlaySound(in SoundID.Item156, position);
                }
            }
            if (flag4 && Main.myPlayer == owner)
            {
                bool canShoot2 = player.channel && player.HasAmmo(player.inventory[player.selectedItem], canUse: true) && !player.noItems && !player.CCed;
                int projToShoot2 = 134;
                float speed2 = 8f;
                int Damage2 = player.GetWeaponDamage(player.inventory[player.selectedItem]);
                float KnockBack2 = player.inventory[player.selectedItem].knockBack;
                if (num57 == 3)
                {
                    speed2 += 1f;
                }
                if (canShoot2)
                {
                    player.PickAmmo(player.inventory[player.selectedItem], ref projToShoot2, ref speed2, ref canShoot2, ref Damage2, ref KnockBack2, out var usedAmmoItemId2);
                    KnockBack2 = player.GetWeaponKnockback(player.inventory[player.selectedItem], KnockBack2);
                    IEntitySource projectileSource_Item_WithPotentialAmmo2 = player.GetProjectileSource_Item_WithPotentialAmmo(player.HeldItem, usedAmmoItemId2);
                    float num58 = player.inventory[player.selectedItem].shootSpeed * scale;
                    Vector2 vector19 = vector;
                    Vector2 value2 = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY) - vector19;
                    if (player.gravDir == -1f)
                    {
                        value2.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector19.Y;
                    }
                    Vector2 spinningpoint10 = Vector2.Normalize(value2);
                    if (float.IsNaN(spinningpoint10.X) || float.IsNaN(spinningpoint10.Y))
                    {
                        spinningpoint10 = -Vector2.UnitY;
                    }
                    spinningpoint10 *= num58;
                    spinningpoint10 = spinningpoint10.RotatedBy((Main.rand.NextDouble() * 0.13089969754219055 - 0.06544984877109528) * 0.5);
                    if (spinningpoint10.X != velocity.X || spinningpoint10.Y != velocity.Y)
                    {
                        netUpdate = true;
                    }
                    velocity = spinningpoint10;
                    for (int num59 = 0; num59 < 1; num59++)
                    {
                        Vector2 spinningpoint2 = Vector2.Normalize(velocity) * speed2;
                        spinningpoint2 = spinningpoint2.RotatedBy(Main.rand.NextDouble() * 0.19634954631328583 - 0.09817477315664291);
                        if (float.IsNaN(spinningpoint2.X) || float.IsNaN(spinningpoint2.Y))
{
                            spinningpoint2 = -Vector2.UnitY;
                        }
                        NewProjectile(projectileSource_Item_WithPotentialAmmo2, vector19.X, vector19.Y, spinningpoint2.X, spinningpoint2.Y, projToShoot2, Damage2, KnockBack2, owner, num57);
                        if (num57 == 5)
{
                            for (float num60 = -1f; num60 <= 1f; num60 += 2f)
{
                                Vector2 vector20 = spinningpoint2.RotatedBy((float)Math.PI * 2f * num60 * 1f / 80f);
                                if (float.IsNaN(spinningpoint2.X) || float.IsNaN(spinningpoint2.Y))
{
                                    vector20 = -Vector2.UnitY;
                                }
                                NewProjectile(projectileSource_Item_WithPotentialAmmo2, vector19.X, vector19.Y, vector20.X, vector20.Y, projToShoot2, Damage2, KnockBack2, owner, num57);
                            }
                        }
                        if (num57 == 4)
{
                            NewProjectile(projectileSource_Item_WithPotentialAmmo2, vector19.X, vector19.Y, spinningpoint2.X, spinningpoint2.Y, projToShoot2, Damage2, KnockBack2, owner, num57, 1f);
                        }
                    }
                }
                else
                {
                    Kill();
                }
            }
            Vector2 vector21 = base.Center + velocity.ToRotation().ToRotationVector2() * 40f;
            Vector2 vector22 = center3 + v.ToRotation().ToRotationVector2() * 40f;
            Color color = Main.hslToRgb(ai[0] / 90f % 1f, 1f, 0.5f);
            ((Color)(ref color)).A = 120;
            int num61 = 267;
            Dust dust = Dust.NewDustPerfect(vector21, num61, Vector2.Zero);
            dust.color = color;
            dust.scale = 0.6f;
            dust.fadeIn = 0.9f;
            dust.noGravity = true;
            Dust dust2 = Dust.NewDustPerfect(vector21, num61, Vector2.Zero);
            dust2.color = color;
            dust2.scale = 0.6f;
            dust2.fadeIn = 0.7f;
            dust2.noGravity = true;
            dust2.velocity = -velocity.RotatedBy(2.094395160675049) / 10f;
            Dust dust3 = Dust.NewDustPerfect(vector21, num61, Vector2.Zero);
            dust3.color = color;
            dust3.scale = 0.6f;
            dust3.fadeIn = 0.7f;
            dust3.noGravity = true;
            dust3.velocity = -velocity.RotatedBy(-2.094395160675049) / 10f;
            if (vector21 != vector22)
            {
                float num62 = -1f;
                Dust dust4 = Dust.NewDustPerfect(Vector2.Lerp(vector21, vector22, 0.8f), num61, Vector2.Zero);
                dust4.velocity = (vector21 - vector22).SafeNormalize(Vector2.Zero) * 2f;
                dust4.color = color;
                dust4.scale = 0.6f;
                dust4.fadeIn = 0.9f;
                dust4.velocity *= num62;
                dust4.noGravity = true;
                Dust dust5 = Dust.NewDustPerfect(Vector2.Lerp(vector21, vector22, 0.5f), num61, Vector2.Zero);
                dust5.velocity = (vector21 - vector22).SafeNormalize(Vector2.Zero) * 2f;
                dust5.color = color;
                dust5.scale = 0.6f;
                dust5.fadeIn = 0.9f;
                dust5.velocity *= num62;
                dust5.noGravity = true;
                Dust dust6 = Dust.NewDustPerfect(Vector2.Lerp(vector21, vector22, 0.2f), num61, Vector2.Zero);
                dust6.velocity = (vector21 - vector22).SafeNormalize(Vector2.Zero) * 2f;
                dust6.color = color;
                dust6.scale = 0.6f;
                dust6.fadeIn = 0.9f;
                dust6.velocity *= num62;
                dust6.noGravity = true;
            }
        }
        if (type == 630)
        {
            num = 0f;
            if (spriteDirection == -1)
            {
                num = (float)Math.PI;
            }
            ai[0] += 1f;
            int num63 = 0;
            if (ai[0] >= 40f)
            {
                num63++;
            }
            if (ai[0] >= 80f)
            {
                num63++;
            }
            if (ai[0] >= 120f)
            {
                num63++;
            }
            int num64 = 24;
            int num65 = 2;
            ai[1] -= 1f;
            bool flag5 = false;
            if (ai[1] <= 0f)
            {
                ai[1] = num64 - num65 * num63;
                flag5 = true;
                _ = (int)ai[0] / (num64 - num65 * num63);
            }
            bool canShoot3 = player.channel && player.HasAmmo(player.inventory[player.selectedItem], canUse: true) && !player.noItems && !player.CCed;
            if (localAI[0] > 0f)
            {
                localAI[0] -= 1f;
            }
            if (soundDelay <= 0 && canShoot3)
            {
                soundDelay = num64 - num65 * num63;
                if (ai[0] != 1f)
                {
                    SoundEngine.PlaySound(in SoundID.Item5, position);
                }
                localAI[0] = 12f;
            }
            player.phantasmTime = 2;
            if (flag5 && Main.myPlayer == owner)
            {
                int projToShoot3 = 14;
                float speed3 = 14f;
                int Damage3 = player.GetWeaponDamage(player.inventory[player.selectedItem]);
                float KnockBack3 = player.inventory[player.selectedItem].knockBack;
                if (canShoot3)
                {
                    player.PickAmmo(player.inventory[player.selectedItem], ref projToShoot3, ref speed3, ref canShoot3, ref Damage3, ref KnockBack3, out var usedAmmoItemId3);
                    IEntitySource projectileSource_Item_WithPotentialAmmo3 = player.GetProjectileSource_Item_WithPotentialAmmo(player.HeldItem, usedAmmoItemId3);
                    KnockBack3 = player.GetWeaponKnockback(player.inventory[player.selectedItem], KnockBack3);
                    float num67 = player.inventory[player.selectedItem].shootSpeed * scale;
                    Vector2 vector24 = vector;
                    Vector2 value3 = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY) - vector24;
                    if (player.gravDir == -1f)
                    {
                        value3.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector24.Y;
                    }
                    Vector2 vector25 = Vector2.Normalize(value3);
                    if (float.IsNaN(vector25.X) || float.IsNaN(vector25.Y))
                    {
                        vector25 = -Vector2.UnitY;
                    }
                    vector25 *= num67;
                    if (vector25.X != velocity.X || vector25.Y != velocity.Y)
                    {
                        netUpdate = true;
                    }
                    velocity = vector25 * 0.55f;
                    for (int num68 = 0; num68 < 4; num68++)
                    {
                        Vector2 vector26 = Vector2.Normalize(velocity) * speed3 * (0.6f + Main.rand.NextFloat() * 0.8f);
                        if (float.IsNaN(vector26.X) || float.IsNaN(vector26.Y))
{
                            vector26 = -Vector2.UnitY;
                        }
                        Vector2 vector27 = vector24 + Utils.RandomVector2(Main.rand, -15f, 15f);
                        int num69 = NewProjectile(projectileSource_Item_WithPotentialAmmo3, vector27.X, vector27.Y, vector26.X, vector26.Y, projToShoot3, Damage3, KnockBack3, owner);
                        Main.projectile[num69].noDropItem = true;
                    }
                }
                else
                {
                    Kill();
                }
            }
        }
        if (type == 705)
        {
            num = 0f;
            if (spriteDirection == -1)
            {
                num = (float)Math.PI;
            }
            ai[0] += 1f;
            int itemAnimationMax = player.itemAnimationMax;
            ai[1] -= 1f;
            bool flag6 = false;
            if (ai[1] <= 0f)
            {
                ai[1] = itemAnimationMax;
                flag6 = true;
            }
            bool canShoot4 = player.channel && player.HasAmmo(player.inventory[player.selectedItem], canUse: true) && !player.noItems && !player.CCed;
            if (localAI[0] > 0f)
            {
                localAI[0] -= 1f;
            }
            if (soundDelay <= 0 && canShoot4)
            {
                soundDelay = itemAnimationMax;
                if (ai[0] != 1f)
                {
                    SoundEngine.PlaySound(in SoundID.Item5, position);
                }
                localAI[0] = 12f;
            }
            if (flag6 && Main.myPlayer == owner)
            {
                int projToShoot4 = 14;
                float speed4 = 12f;
                int Damage4 = player.GetWeaponDamage(player.inventory[player.selectedItem]);
                float KnockBack4 = player.inventory[player.selectedItem].knockBack;
                int num70 = 2;
                float num71 = 1.5f;
                if (canShoot4)
                {
                    player.PickAmmo(player.inventory[player.selectedItem], ref projToShoot4, ref speed4, ref canShoot4, ref Damage4, ref KnockBack4, out var usedAmmoItemId4);
                    IEntitySource projectileSource_Item_WithPotentialAmmo4 = player.GetProjectileSource_Item_WithPotentialAmmo(player.HeldItem, usedAmmoItemId4);
                    KnockBack4 = player.GetWeaponKnockback(player.inventory[player.selectedItem], KnockBack4);
                    if (projToShoot4 == 1)
                    {
                        projToShoot4 = 2;
                    }
                    if (++player.phantomPhoneixCounter >= 3)
                    {
                        player.phantomPhoneixCounter = 0;
                        num70 = 1;
                        Damage4 *= 2;
                        num71 = 0f;
                        ai[1] *= 1.5f;
                        projToShoot4 = 706;
                        speed4 = 16f;
                    }
                    float num72 = player.inventory[player.selectedItem].shootSpeed * scale;
                    Vector2 vector28 = vector;
                    Vector2 value4 = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY) - vector28;
                    if (player.gravDir == -1f)
                    {
                        value4.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - vector28.Y;
                    }
                    Vector2 vector29 = Vector2.Normalize(value4);
                    if (float.IsNaN(vector29.X) || float.IsNaN(vector29.Y))
                    {
                        vector29 = -Vector2.UnitY;
                    }
                    vector29 *= num72;
                    if (vector29.X != velocity.X || vector29.Y != velocity.Y)
                    {
                        netUpdate = true;
                    }
                    velocity = vector29 * 0.55f;
                    for (int num73 = 0; num73 < num70; num73++)
                    {
                        Vector2 vector30 = Vector2.Normalize(velocity) * speed4;
                        vector30 += Main.rand.NextVector2Square(0f - num71, num71);
                        if (float.IsNaN(vector30.X) || float.IsNaN(vector30.Y))
{
                            vector30 = -Vector2.UnitY;
                        }
                        Vector2 vector31 = vector28;
                        int num74 = NewProjectile(projectileSource_Item_WithPotentialAmmo4, vector31.X, vector31.Y, vector30.X, vector30.Y, projToShoot4, Damage4, KnockBack4, owner);
                        Main.projectile[num74].noDropItem = true;
                    }
                }
                else
                {
                    Kill();
                }
            }
        }
        position = player.RotatedRelativePoint(player.MountedCenter, reverseRotation: false, addGfxOffY: false) - base.Size / 2f;
        rotation = velocity.ToRotation() + num;
        spriteDirection = direction;
        timeLeft = 2;
        player.ChangeDir(direction);
        player.heldProj = whoAmI;
        player.SetDummyItemTime(num12);
        player.itemRotation = MathHelper.WrapAngle((float)Math.Atan2(velocity.Y * (float)direction, velocity.X * (float)direction) + num23);
        if (type == 460 || type == 611)
        {
            Vector2 vector32 = Main.OffsetsPlayerOnhand[player.bodyFrame.Y / 56] * 2f;
            if (player.direction != 1)
            {
                vector32.X = (float)player.bodyFrame.Width - vector32.X;
            }
            if (player.gravDir != 1f)
            {
                vector32.Y = (float)player.bodyFrame.Height - vector32.Y;
            }
            vector32 -= new Vector2((float)(player.bodyFrame.Width - player.width), (float)(player.bodyFrame.Height - 42)) / 2f;
            base.Center = player.RotatedRelativePoint(player.MountedCenter - new Vector2(20f, 42f) / 2f + vector32, reverseRotation: false, addGfxOffY: false) - velocity;
        }
        if (type == 615)
        {
            position.Y += player.gravDir * 2f;
        }
        if (type == 714)
        {
            position.Y += player.gravDir * 2f;
        }
        if (type == 611 && alpha == 0)
        {
            for (int num75 = 0; num75 < 2; num75++)
            {
                Dust obj4 = Main.dust[Dust.NewDust(position + velocity * 2f, width, height, 6, 0f, 0f, 100, Color.Transparent, 2f)];
                obj4.noGravity = true;
                obj4.velocity *= 2f;
                obj4.velocity += localAI[0].ToRotationVector2();
                obj4.fadeIn = 1.5f;
            }
            float num76 = 18f;
            for (int num78 = 0; (float)num78 < num76; num78++)
            {
                if (Main.rand.Next(4) == 0)
                {
                    Vector2 vector33 = position + velocity + velocity * ((float)num78 / num76);
                    Dust obj5 = Main.dust[Dust.NewDust(vector33, width, height, 6, 0f, 0f, 100, Color.Transparent)];
                    obj5.noGravity = true;
                    obj5.fadeIn = 0.5f;
                    obj5.velocity += localAI[0].ToRotationVector2();
                    obj5.noLight = true;
                }
            }
        }
        if (type == 927)
        {
            player.itemAnimation = num12 - (int)ai[0];
        }
    }
References Terraria.Entity.active, Terraria.Lighting.AddLight(), Terraria.ModLoader.StatModifier.ApplyTo(), Terraria.Player.bodyFrame, Terraria.DelegateMethods.CastLightOpen(), Terraria.Player.CCed, Terraria.Player.ChangeDir(), Terraria.Player.channel, Terraria.Player.CheckMana(), Terraria.GameContent.Damage, Terraria.Item.damage, Terraria.Entity.direction, Terraria.Main.dust, Terraria.Utils.GetLerpValue(), Terraria.Player.GetProjectileSource_Item_WithPotentialAmmo(), Terraria.Player.GetTotalDamage(), Terraria.Player.GetWeaponDamage(), Terraria.Player.GetWeaponKnockback(), Terraria.Player.gravDir, Terraria.Player.HasAmmo(), Terraria.Player.HeldItem, Terraria.Main.hslToRgb(), Terraria.Player.inventory, Terraria.ID.SoundID.Item1, Terraria.ID.SoundID.Item116, Terraria.ID.SoundID.Item132, Terraria.ID.SoundID.Item15, Terraria.ID.SoundID.Item156, Terraria.ID.SoundID.Item36, Terraria.ID.SoundID.Item5, Terraria.ID.SoundID.Item91, Terraria.Player.itemAnimationMax, Terraria.Item.knockBack, Terraria.ModLoader.DamageClass.Magic, Terraria.Player.MountedCenter, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Player.noItems, Terraria.Main.OffsetsPlayerOnhand, Terraria.Player.phantomPhoneixCounter, Terraria.Player.PickAmmo(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Utils.PlotTileLine(), Terraria.Main.projectile, Terraria.Main.projFrames, Terraria.Main.rand, Terraria.Utils.RandomVector2(), Terraria.Player.RotatedRelativePoint(), Terraria.Main.screenHeight, Terraria.Player.selectedItem, Terraria.Player.SetDummyItemTime(), Terraria.Item.shoot, Terraria.Item.shootSpeed, Terraria.Main.tile, Terraria.Item.tileBoost, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Projectile.type, and Terraria.Entity.width.