TModLoader: Terraria.Projectile.SummonMonkGhast
SummonMonkGhast()
void Terraria.Projectile.SummonMonkGhast () inline private
Definition at line 13971 of file Projectile.cs.
    {
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00de: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_0113: Unknown result type (might be due to invalid IL or missing references)
        //IL_0118: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        if (localAI[0] > 0f)
        {
            return;
        }
        localAI[0] = 1000f;
        List<NPC> list = new List<NPC>();
        for (int i = 0; i < 200; i++)
        {
            NPC nPC = Main.npc[i];
            if (nPC.CanBeChasedBy(this) && Distance(nPC.Center) < 800f)
            {
                list.Add(nPC);
            }
        }
        Vector2 center = base.Center;
        Vector2 zero = Vector2.Zero;
        if (list.Count > 0)
        {
            NPC nPC2 = list[Main.rand.Next(list.Count)];
            center = nPC2.Center;
            zero = nPC2.velocity;
        }
        int num = Main.rand.Next(2) * 2 - 1;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)num * (4f + (float)Main.rand.Next(3)), 0f);
        Vector2 vector2 = center + new Vector2((float)(-num * 120), 0f);
        vector += (center + zero * 15f - vector2).SafeNormalize(Vector2.Zero) * 2f;
        NewProjectile(GetProjectileSource_FromThis(), vector2, vector, 700, damage, 0f, owner);
    }
References Terraria.Projectile.damage, Terraria.Entity.Distance(), Terraria.Projectile.GetProjectileSource_FromThis(), Terraria.Projectile.localAI, Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.Projectile.owner, and Terraria.Main.rand.
Referenced by Terraria.Projectile.Damage().