TModLoader: Terraria.Projectile.AI_169_Smolstars
AI_169_Smolstars()
void Terraria.Projectile.AI_169_Smolstars () inline private
Definition at line 48269 of file Projectile.cs.
    {
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0397: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        //IL_019a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_0431: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0469: Unknown result type (might be due to invalid IL or missing references)
        //IL_046f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0474: Unknown result type (might be due to invalid IL or missing references)
        //IL_0479: Unknown result type (might be due to invalid IL or missing references)
        //IL_0483: Unknown result type (might be due to invalid IL or missing references)
        //IL_0485: Unknown result type (might be due to invalid IL or missing references)
        //IL_0286: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_032d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0341: Unknown result type (might be due to invalid IL or missing references)
        //IL_0346: Unknown result type (might be due to invalid IL or missing references)
        //IL_034b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04be: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_049b: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0304: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        bool num9 = type == 864;
        Vector2 vector = player.Top + new Vector2(0f, -30f);
        if (num9)
        {
            if (player.dead)
            {
                player.smolstar = false;
            }
            if (player.smolstar)
            {
                timeLeft = 2;
            }
            if (ai[0] == 0f)
            {
                AI_GetMyGroupIndexAndFillBlackList(null, out var index, out var totalIndexesInGroup);
                float num2 = (float)Math.PI * 2f / (float)totalIndexesInGroup;
                float num3 = (float)totalIndexesInGroup * 0.66f;
                Vector2 vector2 = new Vector2(30f, 6f) / 5f * (float)(totalIndexesInGroup - 1);
                Vector2 vector3 = Vector2.UnitY.RotatedBy(num2 * (float)index + Main.GlobalTimeWrappedHourly % num3 / num3 * ((float)Math.PI * 2f));
                vector += vector3 * vector2;
                vector.Y += player.gfxOffY;
                vector = vector.Floor();
            }
        }
        if (ai[0] == 0f)
        {
            Vector2 vector4 = vector - base.Center;
            float num4 = 10f;
            float lerpValue = Utils.GetLerpValue(200f, 600f, ((Vector2)(ref vector4)).Length(), clamped: true);
            num4 += lerpValue * 30f;
            if (((Vector2)(ref vector4)).Length() >= 3000f)
            {
                base.Center = vector;
            }
            velocity = vector4;
            if (((Vector2)(ref velocity)).Length() > num4)
            {
                velocity *= num4 / ((Vector2)(ref velocity)).Length();
            }
            int startAttackRange = 800;
            int attackTarget = -1;
            Minion_FindTargetInRange(startAttackRange, ref attackTarget, skipIfCannotHitWithOwnBody: false);
            if (attackTarget != -1)
            {
                ai[0] = 60f;
                ai[1] = attackTarget;
                netUpdate = true;
            }
            float targetAngle = velocity.SafeNormalize(Vector2.UnitY).ToRotation() + (float)Math.PI / 2f;
            if (((Vector2)(ref vector4)).Length() < 40f)
            {
                targetAngle = Vector2.UnitY.ToRotation() + (float)Math.PI / 2f;
            }
            rotation = rotation.AngleLerp(targetAngle, 0.2f);
            return;
        }
        if (ai[0] == -1f)
        {
            if (ai[1] == 0f)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                for (int i = 0; i < 2; i++)
                {
                    Dust dust = Dust.NewDustDirect(position, width, height, 15, oldVelocity.X * 0.2f, oldVelocity.Y * 0.2f, 0, default(Color), 1.4f);
                    if (Main.rand.Next(3) != 0)
                    {
                        dust.scale *= 1.3f;
                        dust.velocity *= 1.1f;
                    }
                    dust.noGravity = true;
                    dust.fadeIn = 0f;
                }
                velocity += Main.rand.NextVector2CircularEdge(4f, 4f);
            }
            ai[1] += 1f;
            rotation += velocity.X * 0.1f + velocity.Y * 0.05f;
            velocity *= 0.92f;
            if (ai[1] >= 9f)
            {
                ai[0] = 0f;
                ai[1] = 0f;
            }
            return;
        }
        NPC nPC = null;
        int num5 = (int)ai[1];
        if (Main.npc.IndexInRange(num5) && Main.npc[num5].CanBeChasedBy(this))
        {
            nPC = Main.npc[num5];
        }
        if (nPC == null)
        {
            ai[0] = -1f;
            ai[1] = 0f;
            netUpdate = true;
        }
        else if (player.Distance(nPC.Center) >= 900f)
        {
            ai[0] = 0f;
            ai[1] = 0f;
            netUpdate = true;
        }
        else
        {
            Vector2 vector5 = nPC.Center - base.Center;
            float num6 = 16f;
            velocity = vector5;
            if (((Vector2)(ref velocity)).Length() > num6)
            {
                velocity *= num6 / ((Vector2)(ref velocity)).Length();
            }
            float targetAngle2 = velocity.SafeNormalize(Vector2.UnitY).ToRotation() + (float)Math.PI / 2f;
            rotation = rotation.AngleLerp(targetAngle2, 0.4f);
        }
        float num7 = 0.1f;
        float num8 = width * 5;
        for (int j = 0; j < 1000; j++)
        {
            if (j != whoAmI && Main.projectile[j].active && Main.projectile[j].owner == owner && Main.projectile[j].type == type && Math.Abs(position.X - Main.projectile[j].position.X) + Math.Abs(position.Y - Main.projectile[j].position.Y) < num8)
            {
                if (position.X < Main.projectile[j].position.X)
                {
                    velocity.X -= num7;
                }
                else
                {
                    velocity.X += num7;
                }
                if (position.Y < Main.projectile[j].position.Y)
                {
                    velocity.Y -= num7;
                }
                else
                {
                    velocity.Y += num7;
                }
            }
        }
    }
References Terraria.Player.dead, Terraria.Entity.Distance(), Terraria.Utils.GetLerpValue(), Terraria.Player.gfxOffY, Terraria.Main.GlobalTimeWrappedHourly, Terraria.Dust.NewDustDirect(), Terraria.Main.npc, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.projectile, Terraria.Main.rand, and Terraria.Player.smolstar.