TModLoader: Terraria.Projectile.AI_100_Medusa
AI_100_Medusa()
void Terraria.Projectile.AI_100_Medusa () inline private
Definition at line 46478 of file Projectile.cs.
    {
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_069a: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0701: Unknown result type (might be due to invalid IL or missing references)
        //IL_0706: Unknown result type (might be due to invalid IL or missing references)
        //IL_0707: Unknown result type (might be due to invalid IL or missing references)
        //IL_070c: Unknown result type (might be due to invalid IL or missing references)
        //IL_070d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0713: Unknown result type (might be due to invalid IL or missing references)
        //IL_0718: Unknown result type (might be due to invalid IL or missing references)
        //IL_071d: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_0146: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_019f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_063c: Unknown result type (might be due to invalid IL or missing references)
        //IL_025a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0347: Unknown result type (might be due to invalid IL or missing references)
        //IL_034c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0374: Unknown result type (might be due to invalid IL or missing references)
        //IL_039f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0415: Unknown result type (might be due to invalid IL or missing references)
        //IL_041a: Unknown result type (might be due to invalid IL or missing references)
        //IL_041c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0421: Unknown result type (might be due to invalid IL or missing references)
        //IL_0425: Unknown result type (might be due to invalid IL or missing references)
        //IL_043b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0442: Unknown result type (might be due to invalid IL or missing references)
        //IL_0449: Unknown result type (might be due to invalid IL or missing references)
        //IL_0450: Unknown result type (might be due to invalid IL or missing references)
        //IL_048a: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0521: Unknown result type (might be due to invalid IL or missing references)
        //IL_0526: Unknown result type (might be due to invalid IL or missing references)
        //IL_058b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0599: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0535: Unknown result type (might be due to invalid IL or missing references)
        //IL_0543: Unknown result type (might be due to invalid IL or missing references)
        //IL_054d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0553: Unknown result type (might be due to invalid IL or missing references)
        //IL_0555: Unknown result type (might be due to invalid IL or missing references)
        //IL_0564: Unknown result type (might be due to invalid IL or missing references)
        //IL_0569: Unknown result type (might be due to invalid IL or missing references)
        //IL_0584: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ea: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        Vector2 zero = Vector2.Zero;
        if (type == 535)
        {
            zero.X = (float)player.direction * 6f;
            zero.Y = player.gravDir * -14f;
            bool flag = true;
            bool flag2 = ai[0] > 0f;
            if (!player.dead)
            {
                timeLeft = 3;
            }
            if (ai[0] > 0f)
            {
                ai[0] -= 1f;
            }
            if (flag2)
            {
                if (frame < 8)
                {
                    frame = 8;
                }
                if (frame >= 12)
                {
                    frame = 8;
                }
                frameCounter++;
                if (++frameCounter >= 5)
                {
                    frameCounter = 0;
                    if (++frame >= 12)
                    {
                        frame = 8;
                    }
                }
            }
            else if (++frameCounter >= 5)
            {
                frameCounter = 0;
                if (++frame >= 8)
                {
                    frame = 0;
                }
            }
            Vector2 center = player.Center;
            Vector2 vector = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY) - center;
            if (player.gravDir == -1f)
            {
                vector.Y = (float)(Main.screenHeight - Main.mouseY) + Main.screenPosition.Y - center.Y;
            }
            Vector2 vector2 = default(Vector2);
            ((Vector2)(ref vector2))._002Ector((float)Math.Sign((vector.X == 0f) ? ((float)player.direction) : vector.X), 0f);
            if (vector2.X != velocity.X || vector2.Y != velocity.Y)
            {
                netUpdate = true;
            }
            velocity = vector2;
            if (flag2 && soundDelay == 0)
            {
                SoundEngine.PlaySound(4, (int)base.position.X, (int)base.position.Y, 17);
            }
            soundDelay = (flag2 ? 4 : 0);
            if (Main.myPlayer == owner)
            {
                Vector2 position = player.Center + new Vector2((float)(player.direction * 4), player.gravDir * 2f);
                if (!player.channel)
                {
                    Kill();
                    return;
                }
                if (!flag2 || ai[0] % 15f == 0f)
                {
                    bool flag3 = false;
                    for (int i = 0; i < 200; i++)
                    {
                        NPC nPC = Main.npc[i];
                        if (nPC.active && Distance(nPC.Center) < 320f && nPC.CanBeChasedBy(this) && Collision.CanHitLine(nPC.position, nPC.width, nPC.height, position, 0, 0))
{
                            flag3 = true;
                            break;
                        }
                    }
                    if (flag3 && (!flag || player.CheckMana(player.inventory[player.selectedItem], -1, pay: true)))
                    {
                        int num = damage;
                        position = base.Center;
                        int num2 = 0;
                        float num3 = 0f;
                        _medusaHeadTargetList.Clear();
                        for (int j = 0; j < 200; j++)
{
                            NPC nPC2 = Main.npc[j];
                            float num4 = Distance(nPC2.Center);
                            if (nPC2.active && num4 < 320f && nPC2.CanBeChasedBy(this) && Collision.CanHitLine(nPC2.position, nPC2.width, nPC2.height, position, 0, 0))
{
                                _medusaHeadTargetList.Add(Tuple.Create(j, num4));
                            }
                        }
                        _medusaHeadTargetList.Sort(_medusaTargetComparer);
                        for (int k = 0; k < _medusaHeadTargetList.Count && k < 3; k++)
{
                            Tuple<int, float> tuple = _medusaHeadTargetList[k];
                            NPC nPC3 = Main.npc[tuple.Item1];
                            Vector2 v = nPC3.Center - position;
                            num3 += v.ToRotation();
                            num2++;
                            int num5 = NewProjectile(GetProjectileSource_FromThis(), position.X, position.Y, v.X, v.Y, 536, 0, 0f, owner, whoAmI);
                            Main.projectile[num5].Center = nPC3.Center;
                            Main.projectile[num5].damage = num;
                            Main.projectile[num5].Damage();
                            Main.projectile[num5].damage = 0;
                            Main.projectile[num5].Center = position;
                            ai[0] = 180f;
                        }
                        num3 = ((num2 != 0) ? (num3 / (float)num2) : ((player.direction == 1) ? 0f : ((float)Math.PI)));
                        for (int l = 0; l < 4; l++)
{
                            Vector2 zero2 = Vector2.Zero;
                            zero2 = ((Main.rand.Next(4) == 0) ? (Vector2.UnitX.RotatedByRandom(6.2831854820251465) * new Vector2(200f, 50f) * (Main.rand.NextFloat() * 0.7f + 0.3f)) : (Vector2.UnitX.RotatedByRandom(3.1415927410125732).RotatedBy(num3) * new Vector2(200f, 50f) * (Main.rand.NextFloat() * 0.7f + 0.3f)));
                            NewProjectile(GetProjectileSource_FromThis(), position.X, position.Y, zero2.X, zero2.Y, 536, 0, 0f, owner, whoAmI);
                        }
                        ai[0] = 60f;
                        netUpdate = true;
                    }
                }
            }
            Lighting.AddLight(base.Center, 0.9f, 0.75f, 0.1f);
        }
        rotation = ((player.gravDir == 1f) ? 0f : ((float)Math.PI));
        spriteDirection = direction;
        timeLeft = 2;
        Vector2 vector3 = Main.OffsetsPlayerOnhand[player.bodyFrame.Y / 56] * 2f;
        if (player.direction != 1)
        {
            vector3.X = (float)player.bodyFrame.Width - vector3.X;
        }
        vector3 -= (player.bodyFrame.Size() - new Vector2((float)player.width, 42f)) / 2f;
        base.Center = (player.position + vector3 + zero - velocity).Floor();
        player.ChangeDir(direction);
        player.heldProj = whoAmI;
        player.SetDummyItemTime(2);
    }
References Terraria.Lighting.AddLight(), Terraria.Player.bodyFrame, Terraria.Collision.CanHitLine(), Terraria.Entity.Center, Terraria.Player.ChangeDir(), Terraria.Player.channel, Terraria.Player.CheckMana(), Terraria.Projectile.damage, Terraria.Projectile.Damage(), Terraria.Player.dead, Terraria.Entity.direction, Terraria.Player.gravDir, Terraria.Player.inventory, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Main.OffsetsPlayerOnhand, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.projectile, Terraria.Main.rand, Terraria.Main.screenHeight, Terraria.Player.selectedItem, Terraria.Player.SetDummyItemTime(), and Terraria.Entity.width.