TModLoader: Terraria.Projectile.HandleMovement
HandleMovement()
void Terraria.Projectile.HandleMovement (Vector2 wetVelocity, out int overrideWidth, out int overrideHeight) inline private
Definition at line 16673 of file Projectile.cs.
    {
        //IL_50ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_5120: Unknown result type (might be due to invalid IL or missing references)
        //IL_5126: Unknown result type (might be due to invalid IL or missing references)
        //IL_5136: Unknown result type (might be due to invalid IL or missing references)
        //IL_513b: Unknown result type (might be due to invalid IL or missing references)
        //IL_513e: Unknown result type (might be due to invalid IL or missing references)
        //IL_5143: Unknown result type (might be due to invalid IL or missing references)
        //IL_51eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_51f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0363: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0402: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b19: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b27: Unknown result type (might be due to invalid IL or missing references)
        //IL_155d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1560: Unknown result type (might be due to invalid IL or missing references)
        //IL_194e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c08: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c12: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c17: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c29: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c33: Unknown result type (might be due to invalid IL or missing references)
        //IL_19fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a04: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a09: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a14: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a19: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c40: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c56: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cbc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cbf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ccd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ddb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dde: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e06: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d49: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d54: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_13f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_13f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1407: Unknown result type (might be due to invalid IL or missing references)
        //IL_140c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1003: Unknown result type (might be due to invalid IL or missing references)
        //IL_1008: Unknown result type (might be due to invalid IL or missing references)
        //IL_100d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0daf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1422: Unknown result type (might be due to invalid IL or missing references)
        //IL_1425: Unknown result type (might be due to invalid IL or missing references)
        //IL_1434: Unknown result type (might be due to invalid IL or missing references)
        //IL_1439: Unknown result type (might be due to invalid IL or missing references)
        //IL_143c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1441: Unknown result type (might be due to invalid IL or missing references)
        //IL_1443: Unknown result type (might be due to invalid IL or missing references)
        //IL_1448: Unknown result type (might be due to invalid IL or missing references)
        //IL_1027: Unknown result type (might be due to invalid IL or missing references)
        //IL_102c: Unknown result type (might be due to invalid IL or missing references)
        //IL_102e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1034: Unknown result type (might be due to invalid IL or missing references)
        //IL_103a: Unknown result type (might be due to invalid IL or missing references)
        //IL_103c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e65: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e68: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e84: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e86: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_14be: Unknown result type (might be due to invalid IL or missing references)
        //IL_14c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1457: Unknown result type (might be due to invalid IL or missing references)
        //IL_145e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f08: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea1: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1474: Unknown result type (might be due to invalid IL or missing references)
        //IL_123b: Unknown result type (might be due to invalid IL or missing references)
        //IL_123d: Unknown result type (might be due to invalid IL or missing references)
        //IL_124d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb7: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_1481: Unknown result type (might be due to invalid IL or missing references)
        //IL_1493: Unknown result type (might be due to invalid IL or missing references)
        //IL_149a: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_1058: Unknown result type (might be due to invalid IL or missing references)
        //IL_105a: Unknown result type (might be due to invalid IL or missing references)
        //IL_127e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1267: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f30: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0edd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1503: Unknown result type (might be due to invalid IL or missing references)
        //IL_1071: Unknown result type (might be due to invalid IL or missing references)
        //IL_1075: Unknown result type (might be due to invalid IL or missing references)
        //IL_107a: Unknown result type (might be due to invalid IL or missing references)
        //IL_107c: Unknown result type (might be due to invalid IL or missing references)
        //IL_107e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1089: Unknown result type (might be due to invalid IL or missing references)
        //IL_108e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1090: Unknown result type (might be due to invalid IL or missing references)
        //IL_1092: Unknown result type (might be due to invalid IL or missing references)
        //IL_1094: Unknown result type (might be due to invalid IL or missing references)
        //IL_1099: Unknown result type (might be due to invalid IL or missing references)
        //IL_109c: Unknown result type (might be due to invalid IL or missing references)
        //IL_109e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1298: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f46: Unknown result type (might be due to invalid IL or missing references)
        //IL_05af: Unknown result type (might be due to invalid IL or missing references)
        //IL_1510: Unknown result type (might be due to invalid IL or missing references)
        //IL_151e: Unknown result type (might be due to invalid IL or missing references)
        //IL_152b: Unknown result type (might be due to invalid IL or missing references)
        //IL_152d: Unknown result type (might be due to invalid IL or missing references)
        //IL_152f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1534: Unknown result type (might be due to invalid IL or missing references)
        //IL_153f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1551: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_10cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_10d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_10d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_10da: Unknown result type (might be due to invalid IL or missing references)
        //IL_12b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_12b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_12c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_12cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_12cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_12d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_12d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_12db: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f53: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f70: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f82: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f94: Unknown result type (might be due to invalid IL or missing references)
        //IL_121c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1221: Unknown result type (might be due to invalid IL or missing references)
        //IL_1223: Unknown result type (might be due to invalid IL or missing references)
        //IL_1225: Unknown result type (might be due to invalid IL or missing references)
        //IL_1227: Unknown result type (might be due to invalid IL or missing references)
        //IL_122c: Unknown result type (might be due to invalid IL or missing references)
        //IL_11fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1200: Unknown result type (might be due to invalid IL or missing references)
        //IL_1150: Unknown result type (might be due to invalid IL or missing references)
        //IL_1157: Unknown result type (might be due to invalid IL or missing references)
        //IL_10e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_10f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1351: Unknown result type (might be due to invalid IL or missing references)
        //IL_1358: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_12f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a32: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a38: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a42: Unknown result type (might be due to invalid IL or missing references)
        //IL_1162: Unknown result type (might be due to invalid IL or missing references)
        //IL_1169: Unknown result type (might be due to invalid IL or missing references)
        //IL_1106: Unknown result type (might be due to invalid IL or missing references)
        //IL_1363: Unknown result type (might be due to invalid IL or missing references)
        //IL_136a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1307: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_120c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1212: Unknown result type (might be due to invalid IL or missing references)
        //IL_117f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1113: Unknown result type (might be due to invalid IL or missing references)
        //IL_1125: Unknown result type (might be due to invalid IL or missing references)
        //IL_112c: Unknown result type (might be due to invalid IL or missing references)
        //IL_113f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1380: Unknown result type (might be due to invalid IL or missing references)
        //IL_1314: Unknown result type (might be due to invalid IL or missing references)
        //IL_1326: Unknown result type (might be due to invalid IL or missing references)
        //IL_132d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1340: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ab3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a77: Unknown result type (might be due to invalid IL or missing references)
        //IL_1195: Unknown result type (might be due to invalid IL or missing references)
        //IL_1396: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ba5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bab: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bc4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bce: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1abf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a95: Unknown result type (might be due to invalid IL or missing references)
        //IL_11a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_11b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_11bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_11bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_13be: Unknown result type (might be due to invalid IL or missing references)
        //IL_13c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_13c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_13c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_13d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_13e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c19: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c20: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c25: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b76: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b81: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b86: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b66: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b69: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ae0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b47: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c80: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d63: Unknown result type (might be due to invalid IL or missing references)
        //IL_1caf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e66: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d92: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d72: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cb8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e98: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e75: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cde: Unknown result type (might be due to invalid IL or missing references)
        //IL_2282: Unknown result type (might be due to invalid IL or missing references)
        //IL_2034: Unknown result type (might be due to invalid IL or missing references)
        //IL_200c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2012: Unknown result type (might be due to invalid IL or missing references)
        //IL_2017: Unknown result type (might be due to invalid IL or missing references)
        //IL_201c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1eb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_22ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_22ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_2296: Unknown result type (might be due to invalid IL or missing references)
        //IL_2060: Unknown result type (might be due to invalid IL or missing references)
        //IL_2048: Unknown result type (might be due to invalid IL or missing references)
        //IL_2094: Unknown result type (might be due to invalid IL or missing references)
        //IL_20a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_20a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d21: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d28: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2331: Unknown result type (might be due to invalid IL or missing references)
        //IL_2313: Unknown result type (might be due to invalid IL or missing references)
        //IL_22d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_22c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2074: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e04: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e10: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e24: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e29: Unknown result type (might be due to invalid IL or missing references)
        //IL_23a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_23ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_23b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_23b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_23be: Unknown result type (might be due to invalid IL or missing references)
        //IL_23c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2348: Unknown result type (might be due to invalid IL or missing references)
        //IL_20dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_20f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_210b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2110: Unknown result type (might be due to invalid IL or missing references)
        //IL_211d: Unknown result type (might be due to invalid IL or missing references)
        //IL_212d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2133: Unknown result type (might be due to invalid IL or missing references)
        //IL_2135: Unknown result type (might be due to invalid IL or missing references)
        //IL_213a: Unknown result type (might be due to invalid IL or missing references)
        //IL_213c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2157: Unknown result type (might be due to invalid IL or missing references)
        //IL_215c: Unknown result type (might be due to invalid IL or missing references)
        //IL_217d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2182: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f05: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f11: Unknown result type (might be due to invalid IL or missing references)
        //IL_21f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_21f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_221e: Unknown result type (might be due to invalid IL or missing references)
        //IL_223f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2244: Unknown result type (might be due to invalid IL or missing references)
        //IL_225b: Unknown result type (might be due to invalid IL or missing references)
        //IL_23d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_23dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_23e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_23e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_23ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_23f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_23f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f74: Unknown result type (might be due to invalid IL or missing references)
        //IL_2452: Unknown result type (might be due to invalid IL or missing references)
        //IL_2458: Unknown result type (might be due to invalid IL or missing references)
        //IL_245d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2462: Unknown result type (might be due to invalid IL or missing references)
        //IL_2468: Unknown result type (might be due to invalid IL or missing references)
        //IL_246d: Unknown result type (might be due to invalid IL or missing references)
        //IL_248f: Unknown result type (might be due to invalid IL or missing references)
        //IL_250b: Unknown result type (might be due to invalid IL or missing references)
        //IL_24c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_24a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_259a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2537: Unknown result type (might be due to invalid IL or missing references)
        //IL_251f: Unknown result type (might be due to invalid IL or missing references)
        //IL_24d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_25c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_25a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_254e: Unknown result type (might be due to invalid IL or missing references)
        //IL_255b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2627: Unknown result type (might be due to invalid IL or missing references)
        //IL_25d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2650: Unknown result type (might be due to invalid IL or missing references)
        //IL_2636: Unknown result type (might be due to invalid IL or missing references)
        //IL_2659: Unknown result type (might be due to invalid IL or missing references)
        //IL_2672: Unknown result type (might be due to invalid IL or missing references)
        //IL_28de: Unknown result type (might be due to invalid IL or missing references)
        //IL_294b: Unknown result type (might be due to invalid IL or missing references)
        //IL_290a: Unknown result type (might be due to invalid IL or missing references)
        //IL_28f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_27cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2977: Unknown result type (might be due to invalid IL or missing references)
        //IL_295a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2921: Unknown result type (might be due to invalid IL or missing references)
        //IL_27fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_27de: Unknown result type (might be due to invalid IL or missing references)
        //IL_29e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2983: Unknown result type (might be due to invalid IL or missing references)
        //IL_280d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a27: Unknown result type (might be due to invalid IL or missing references)
        //IL_29f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_299a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2832: Unknown result type (might be due to invalid IL or missing references)
        //IL_2838: Unknown result type (might be due to invalid IL or missing references)
        //IL_283d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2842: Unknown result type (might be due to invalid IL or missing references)
        //IL_284b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2858: Unknown result type (might be due to invalid IL or missing references)
        //IL_285d: Unknown result type (might be due to invalid IL or missing references)
        //IL_285f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2866: Unknown result type (might be due to invalid IL or missing references)
        //IL_286b: Unknown result type (might be due to invalid IL or missing references)
        //IL_286f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2879: Unknown result type (might be due to invalid IL or missing references)
        //IL_287e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2885: Unknown result type (might be due to invalid IL or missing references)
        //IL_288a: Unknown result type (might be due to invalid IL or missing references)
        //IL_288c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2891: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ada: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aa4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a33: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_28ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_28b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_28bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b57: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ae6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2abd: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b96: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b70: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b02: Unknown result type (might be due to invalid IL or missing references)
        //IL_2baf: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bef: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bf8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c11: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cca: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cad: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c56: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d37: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cdc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d49: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fde: Unknown result type (might be due to invalid IL or missing references)
        //IL_2dc9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2de1: Unknown result type (might be due to invalid IL or missing references)
        //IL_300a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fed: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e10: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e21: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e59: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e64: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e69: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e70: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e75: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e94: Unknown result type (might be due to invalid IL or missing references)
        //IL_30ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_301c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_311a: Unknown result type (might be due to invalid IL or missing references)
        //IL_30fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f49: Unknown result type (might be due to invalid IL or missing references)
        //IL_3199: Unknown result type (might be due to invalid IL or missing references)
        //IL_319e: Unknown result type (might be due to invalid IL or missing references)
        //IL_31a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_31a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_317a: Unknown result type (might be due to invalid IL or missing references)
        //IL_317f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3186: Unknown result type (might be due to invalid IL or missing references)
        //IL_318b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3190: Unknown result type (might be due to invalid IL or missing references)
        //IL_3126: Unknown result type (might be due to invalid IL or missing references)
        //IL_30cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f91: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f96: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_31ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_31b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_31bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_313d: Unknown result type (might be due to invalid IL or missing references)
        //IL_321d: Unknown result type (might be due to invalid IL or missing references)
        //IL_33e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_3231: Unknown result type (might be due to invalid IL or missing references)
        //IL_3453: Unknown result type (might be due to invalid IL or missing references)
        //IL_340f: Unknown result type (might be due to invalid IL or missing references)
        //IL_33f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_3262: Unknown result type (might be due to invalid IL or missing references)
        //IL_3504: Unknown result type (might be due to invalid IL or missing references)
        //IL_349e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3426: Unknown result type (might be due to invalid IL or missing references)
        //IL_328e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3276: Unknown result type (might be due to invalid IL or missing references)
        //IL_35b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_3545: Unknown result type (might be due to invalid IL or missing references)
        //IL_3518: Unknown result type (might be due to invalid IL or missing references)
        //IL_347e: Unknown result type (might be due to invalid IL or missing references)
        //IL_32a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_3657: Unknown result type (might be due to invalid IL or missing references)
        //IL_35f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_35c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_3559: Unknown result type (might be due to invalid IL or missing references)
        //IL_34cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3683: Unknown result type (might be due to invalid IL or missing references)
        //IL_366b: Unknown result type (might be due to invalid IL or missing references)
        //IL_360b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a23: Unknown result type (might be due to invalid IL or missing references)
        //IL_369a: Unknown result type (might be due to invalid IL or missing references)
        //IL_36d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_32f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_3306: Unknown result type (might be due to invalid IL or missing references)
        //IL_330b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3310: Unknown result type (might be due to invalid IL or missing references)
        //IL_338d: Unknown result type (might be due to invalid IL or missing references)
        //IL_3393: Unknown result type (might be due to invalid IL or missing references)
        //IL_3398: Unknown result type (might be due to invalid IL or missing references)
        //IL_339d: Unknown result type (might be due to invalid IL or missing references)
        //IL_33b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_33b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_33bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a52: Unknown result type (might be due to invalid IL or missing references)
        //IL_3739: Unknown result type (might be due to invalid IL or missing references)
        //IL_373e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3705: Unknown result type (might be due to invalid IL or missing references)
        //IL_36ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_3774: Unknown result type (might be due to invalid IL or missing references)
        //IL_377a: Unknown result type (might be due to invalid IL or missing references)
        //IL_377f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3784: Unknown result type (might be due to invalid IL or missing references)
        //IL_378a: Unknown result type (might be due to invalid IL or missing references)
        //IL_378c: Unknown result type (might be due to invalid IL or missing references)
        //IL_379e: Unknown result type (might be due to invalid IL or missing references)
        //IL_37a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_37ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_371c: Unknown result type (might be due to invalid IL or missing references)
        //IL_332a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3339: Unknown result type (might be due to invalid IL or missing references)
        //IL_3938: Unknown result type (might be due to invalid IL or missing references)
        //IL_397e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3966: Unknown result type (might be due to invalid IL or missing references)
        //IL_39af: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a42: Unknown result type (might be due to invalid IL or missing references)
        //IL_38af: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ad6: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a56: Unknown result type (might be due to invalid IL or missing references)
        //IL_38e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_38c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_3be4: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b66: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b02: Unknown result type (might be due to invalid IL or missing references)
        //IL_3aea: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a85: Unknown result type (might be due to invalid IL or missing references)
        //IL_38f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b75: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3bc6: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b19: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c16: Unknown result type (might be due to invalid IL or missing references)
        //IL_385f: Unknown result type (might be due to invalid IL or missing references)
        //IL_386b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3d25: Unknown result type (might be due to invalid IL or missing references)
        //IL_3d33: Unknown result type (might be due to invalid IL or missing references)
        //IL_3cbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c22: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f15: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c97: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c31: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c37: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c82: Unknown result type (might be due to invalid IL or missing references)
        //IL_4134: Unknown result type (might be due to invalid IL or missing references)
        //IL_4052: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f21: Unknown result type (might be due to invalid IL or missing references)
        //IL_3cde: Unknown result type (might be due to invalid IL or missing references)
        //IL_41bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_413d: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f33: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f39: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f84: Unknown result type (might be due to invalid IL or missing references)
        //IL_42ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_41ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_41f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_420e: Unknown result type (might be due to invalid IL or missing references)
        //IL_4238: Unknown result type (might be due to invalid IL or missing references)
        //IL_414c: Unknown result type (might be due to invalid IL or missing references)
        //IL_4152: Unknown result type (might be due to invalid IL or missing references)
        //IL_419d: Unknown result type (might be due to invalid IL or missing references)
        //IL_3dc5: Unknown result type (might be due to invalid IL or missing references)
        //IL_4317: Unknown result type (might be due to invalid IL or missing references)
        //IL_42d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_42c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_4264: Unknown result type (might be due to invalid IL or missing references)
        //IL_424c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3e0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3dce: Unknown result type (might be due to invalid IL or missing references)
        //IL_4343: Unknown result type (might be due to invalid IL or missing references)
        //IL_4326: Unknown result type (might be due to invalid IL or missing references)
        //IL_42f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_427b: Unknown result type (might be due to invalid IL or missing references)
        //IL_40a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_40a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_40ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_40b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fdc: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fe1: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fe3: Unknown result type (might be due to invalid IL or missing references)
        //IL_3e13: Unknown result type (might be due to invalid IL or missing references)
        //IL_3def: Unknown result type (might be due to invalid IL or missing references)
        //IL_434f: Unknown result type (might be due to invalid IL or missing references)
        //IL_40d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_40d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_40be: Unknown result type (might be due to invalid IL or missing references)
        //IL_40c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_40ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_4006: Unknown result type (might be due to invalid IL or missing references)
        //IL_400b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ff1: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ff8: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ffd: Unknown result type (might be due to invalid IL or missing references)
        //IL_3e5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3e64: Unknown result type (might be due to invalid IL or missing references)
        //IL_3e34: Unknown result type (might be due to invalid IL or missing references)
        //IL_4457: Unknown result type (might be due to invalid IL or missing references)
        //IL_445d: Unknown result type (might be due to invalid IL or missing references)
        //IL_436b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4492: Unknown result type (might be due to invalid IL or missing references)
        //IL_4622: Unknown result type (might be due to invalid IL or missing references)
        //IL_4628: Unknown result type (might be due to invalid IL or missing references)
        //IL_4595: Unknown result type (might be due to invalid IL or missing references)
        //IL_459b: Unknown result type (might be due to invalid IL or missing references)
        //IL_45a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_45a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_45af: Unknown result type (might be due to invalid IL or missing references)
        //IL_45ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_45bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_45c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_45d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_44be: Unknown result type (might be due to invalid IL or missing references)
        //IL_44a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_466a: Unknown result type (might be due to invalid IL or missing references)
        //IL_45df: Unknown result type (might be due to invalid IL or missing references)
        //IL_44d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_4502: Unknown result type (might be due to invalid IL or missing references)
        //IL_451a: Unknown result type (might be due to invalid IL or missing references)
        //IL_43f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_4696: Unknown result type (might be due to invalid IL or missing references)
        //IL_467e: Unknown result type (might be due to invalid IL or missing references)
        //IL_45f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_441a: Unknown result type (might be due to invalid IL or missing references)
        //IL_46aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_4604: Unknown result type (might be due to invalid IL or missing references)
        //IL_4618: Unknown result type (might be due to invalid IL or missing references)
        //IL_461a: Unknown result type (might be due to invalid IL or missing references)
        //IL_48a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_476b: Unknown result type (might be due to invalid IL or missing references)
        //IL_46f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_4709: Unknown result type (might be due to invalid IL or missing references)
        //IL_48d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_48b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_4de9: Unknown result type (might be due to invalid IL or missing references)
        //IL_48e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_502a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5034: Unknown result type (might be due to invalid IL or missing references)
        //IL_5039: Unknown result type (might be due to invalid IL or missing references)
        //IL_4e33: Unknown result type (might be due to invalid IL or missing references)
        //IL_4df8: Unknown result type (might be due to invalid IL or missing references)
        //IL_49e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_48f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_47c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_47ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_47cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_47d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_50d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_50d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_50de: Unknown result type (might be due to invalid IL or missing references)
        //IL_50e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_5074: Unknown result type (might be due to invalid IL or missing references)
        //IL_4e3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_4a16: Unknown result type (might be due to invalid IL or missing references)
        //IL_49ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_483f: Unknown result type (might be due to invalid IL or missing references)
        //IL_50a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_5083: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ff3: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ffd: Unknown result type (might be due to invalid IL or missing references)
        //IL_5002: Unknown result type (might be due to invalid IL or missing references)
        //IL_4abe: Unknown result type (might be due to invalid IL or missing references)
        //IL_4a1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_49fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_486b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4853: Unknown result type (might be due to invalid IL or missing references)
        //IL_480b: Unknown result type (might be due to invalid IL or missing references)
        //IL_50a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_4e5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_4b04: Unknown result type (might be due to invalid IL or missing references)
        //IL_4acd: Unknown result type (might be due to invalid IL or missing references)
        //IL_4a2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_4882: Unknown result type (might be due to invalid IL or missing references)
        //IL_481f: Unknown result type (might be due to invalid IL or missing references)
        //IL_50bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ba8: Unknown result type (might be due to invalid IL or missing references)
        //IL_4b54: Unknown result type (might be due to invalid IL or missing references)
        //IL_4b16: Unknown result type (might be due to invalid IL or missing references)
        //IL_4a41: Unknown result type (might be due to invalid IL or missing references)
        //IL_4a47: Unknown result type (might be due to invalid IL or missing references)
        //IL_4a6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4a77: Unknown result type (might be due to invalid IL or missing references)
        //IL_4c2b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4bd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_4bb7: Unknown result type (might be due to invalid IL or missing references)
        //IL_4b75: Unknown result type (might be due to invalid IL or missing references)
        //IL_4b77: Unknown result type (might be due to invalid IL or missing references)
        //IL_4b7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_4b68: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ca9: Unknown result type (might be due to invalid IL or missing references)
        //IL_4c57: Unknown result type (might be due to invalid IL or missing references)
        //IL_4c3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_4be0: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cb8: Unknown result type (might be due to invalid IL or missing references)
        //IL_4c63: Unknown result type (might be due to invalid IL or missing references)
        //IL_4bfc: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d37: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ce1: Unknown result type (might be due to invalid IL or missing references)
        //IL_4c7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d97: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d49: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cf8: Unknown result type (might be due to invalid IL or missing references)
        //IL_4da3: Unknown result type (might be due to invalid IL or missing references)
        //IL_4dba: Unknown result type (might be due to invalid IL or missing references)
        bool flag = false;
        overrideWidth = -1;
        overrideHeight = -1;
        bool flag7 = false;
        bool? flag8 = ProjectileID.Sets.ForcePlateDetection[type];
        bool flag9 = flag8.HasValue && !flag8.Value;
        bool flag10 = flag8.HasValue && flag8.Value;
        if (tileCollide)
        {
            Vector2 lastVelocity = velocity;
            bool flag11 = true;
            Vector2? vector = null;
            if (Main.projPet[type])
            {
                flag11 = false;
                if (Main.player[owner].position.Y + (float)Main.player[owner].height - 12f > position.Y + (float)height)
                {
                    flag11 = true;
                }
            }
            if (type == 500)
            {
                flag11 = false;
                if (Main.player[owner].Bottom.Y > base.Bottom.Y + 4f)
                {
                    flag11 = true;
                }
            }
            if (type == 653 || type == 668)
            {
                flag11 = false;
                if (Main.player[owner].Bottom.Y > base.Bottom.Y + 4f)
                {
                    flag11 = true;
                }
            }
            if (aiStyle == 62)
            {
                flag11 = true;
            }
            if (aiStyle == 66)
            {
                flag11 = true;
            }
            if (type == 317)
            {
                flag11 = true;
            }
            if (type == 373)
            {
                flag11 = true;
            }
            if (aiStyle == 53)
            {
                flag11 = false;
            }
            if (type == 9 || type == 12 || type == 15 || type == 13)
            {
                flag11 = false;
            }
            if (aiStyle == 10 && ProjectileID.Sets.FallingBlockDoesNotFallThroughPlatforms[type])
            {
                flag11 = false;
            }
            if (type == 24)
            {
                flag11 = false;
            }
            switch (type)
            {
            case 663:
            case 665:
            case 667:
            case 677:
            case 678:
            case 679:
            case 688:
            case 689:
            case 690:
            case 691:
            case 692:
            case 693:
                flag11 = false;
                break;
            case 759:
                flag11 = true;
                break;
            case 1020:
            {
                float num = MathHelper.WrapAngle(rotation);
                flag11 = num >= (float)Math.PI / 2f || num < -(float)Math.PI / 2f;
                break;
            }
            }
            if (decidesManualFallThrough)
            {
                flag11 = shouldFallThrough;
            }
            if (type == 771 || type == 822 || type == 823 || type == 843 || type == 846 || type == 845 || type == 852)
            {
                overrideWidth = width;
                overrideHeight = 34;
                vector = new Vector2(0.75f, 0.75f);
            }
            if (type == 969)
            {
                overrideWidth = 18;
                overrideHeight = 32;
            }
            if (type == 824 || type == 839 || type == 840 || type == 850 || type == 853)
            {
                overrideWidth = width;
                overrideHeight = 58;
                vector = new Vector2(0.75f, 0.75f);
            }
            if (type == 826 || type == 830 || type == 838)
            {
                overrideWidth = width;
                overrideHeight = 38;
                vector = new Vector2(0.75f, 0.75f);
            }
            if (type == 828 || type == 829 || type == 827 || type == 844)
            {
                overrideWidth = width;
                overrideHeight = 22;
                vector = new Vector2(0.75f, 0.75f);
            }
            if (aiStyle == 29 || type == 28 || aiStyle == 49 || type == 906 || type == 903 || type == 904 || type == 910)
            {
                overrideWidth = width - 8;
                overrideHeight = height - 8;
            }
            else if (type == 250 || type == 267 || type == 297 || type == 323 || type == 3 || type == 711)
            {
                overrideWidth = 6;
                overrideHeight = 6;
            }
            else if (type == 308)
            {
                overrideWidth = 26;
                overrideHeight = height;
            }
            else if (type == 663 || type == 665 || type == 667 || type == 677 || type == 678 || type == 679 || type == 691 || type == 692 || type == 693)
            {
                overrideWidth = 16;
                overrideHeight = height;
            }
            else if (type == 688 || type == 689 || type == 690)
            {
                overrideWidth = 16;
                overrideHeight = height;
                vector = new Vector2(0.5f, 1f);
            }
            else if (type == 669 || type == 706)
            {
                overrideWidth = 10;
                overrideHeight = 10;
            }
            else if (type == 261 || type == 277)
            {
                overrideWidth = 26;
                overrideHeight = 26;
            }
            else if (type == 481 || type == 491 || type == 106 || type == 262 || type == 271 || type == 270 || type == 272 || type == 273 || type == 274 || type == 280 || type == 288 || type == 301 || type == 320 || type == 333 || type == 335 || type == 343 || type == 344 || type == 497 || type == 496 || type == 6 || type == 19 || type == 113 || type == 52 || type == 520 || type == 523 || type == 585 || type == 598 || type == 599 || type == 636 || type == 837 || type == 861 || type == 867 || type == 971 || type == 975 || type == 1000)
            {
                overrideWidth = 10;
                overrideHeight = 10;
            }
            else if (type == 514)
            {
                overrideWidth = 4;
                overrideHeight = 4;
            }
            else if (type == 248 || type == 247 || type == 507 || type == 508 || type == 662 || type == 680 || type == 685 || type == 757 || type == 928)
            {
                overrideWidth = width - 12;
                overrideHeight = height - 12;
            }
            else if (aiStyle == 18 || type == 254)
            {
                overrideWidth = width - 36;
                overrideHeight = height - 36;
            }
            else if (type == 182 || type == 190 || type == 33 || type == 229 || type == 237 || type == 243 || type == 866)
            {
                overrideWidth = width - 20;
                overrideHeight = height - 20;
            }
            else if (aiStyle == 27)
            {
                overrideWidth = width - 12;
                overrideHeight = height - 12;
            }
            else if (type == 533 && ai[0] >= 6f)
            {
                overrideWidth = width + 6;
                overrideHeight = height + 6;
            }
            else if (type == 755 && ai[0] >= 0f)
            {
                overrideWidth = width + 6;
                overrideHeight = height + 6;
            }
            else if (type == 759)
            {
                if (velocity.X != lastVelocity.X)
                {
                    velocity.X = 0f - lastVelocity.X;
                }
                if (velocity.Y != lastVelocity.Y)
                {
                    velocity.Y = 0f - lastVelocity.Y;
                }
            }
            else if (type == 582 || type == 634 || type == 635 || type == 902)
            {
                overrideWidth = 8;
                overrideHeight = 8;
            }
            else if (type == 617)
            {
                overrideWidth = (int)(20f * scale);
                overrideHeight = (int)(20f * scale);
            }
            else if (type == 304)
            {
                overrideWidth = 4;
                overrideHeight = 4;
            }
            else if (aiStyle == 9)
            {
                overrideWidth = 4;
                overrideHeight = 4;
            }
            else if (type == 931)
            {
                overrideWidth = 4;
                overrideHeight = 4;
            }
            Vector2 hitboxCenterFrac = (Vector2)(((_003F?)vector) ?? new Vector2(0.5f));
            int num12 = ((overrideWidth != -1) ? overrideWidth : width);
            int num23 = ((overrideHeight != -1) ? overrideHeight : height);
            if (ProjectileLoader.TileCollideStyle(this, ref num12, ref num23, ref flag11, ref hitboxCenterFrac) && ((type != 440 && type != 449 && type != 606) || ai[1] != 1f) && (type != 466 || localAI[1] != 1f) && (type != 580 || !(localAI[1] > 0f)) && (type != 640 || !(localAI[1] > 0f)))
            {
                Vector2 vector12 = position + new Vector2((float)width, (float)height) * 0.5f - new Vector2((float)num12, (float)num23) * hitboxCenterFrac;
                if (aiStyle == 10)
                {
                    velocity = Collision.TileCollision(vector12, velocity, num12, num23, flag11, flag11);
                    if (type >= 411 && type <= 414)
                    {
                        velocity = Collision.AnyCollisionWithSpecificTiles(vector12, velocity, num12, num23, TileID.Sets.Falling, evenActuated: true);
                    }
                }
                else if (wet)
                {
                    if (shimmerWet)
                    {
                        Vector2 vector20 = velocity;
                        velocity = Collision.TileCollision(vector12, velocity, num12, num23, flag11, flag11);
                        wetVelocity = velocity * 0.375f;
                        if (velocity.X != vector20.X)
{
                            wetVelocity.X = velocity.X;
                        }
                        if (velocity.Y != vector20.Y)
{
                            wetVelocity.Y = velocity.Y;
                        }
                    }
                    else if (honeyWet)
                    {
                        Vector2 vector21 = velocity;
                        velocity = Collision.TileCollision(vector12, velocity, num12, num23, flag11, flag11);
                        wetVelocity = velocity * 0.25f;
                        if (velocity.X != vector21.X)
{
                            wetVelocity.X = velocity.X;
                        }
                        if (velocity.Y != vector21.Y)
{
                            wetVelocity.Y = velocity.Y;
                        }
                    }
                    else
                    {
                        Vector2 vector22 = velocity;
                        velocity = Collision.TileCollision(vector12, velocity, num12, num23, flag11, flag11);
                        wetVelocity = velocity * 0.5f;
                        if (velocity.X != vector22.X)
{
                            wetVelocity.X = velocity.X;
                        }
                        if (velocity.Y != vector22.Y)
{
                            wetVelocity.Y = velocity.Y;
                        }
                    }
                    if (!Main.projPet[type])
                    {
                        Vector4 vector23 = Collision.SlopeCollision(vector12, velocity, num12, num23, 0f, fall: true);
                        Vector2 vector24 = position - vector12;
                        if (aiStyle == 137)
{
                            if (vector12.Y != vector23.Y)
{
                                flag = true;
                            }
                            if (velocity.Y != vector23.W)
{
                                flag = true;
                            }
                            vector12.Y = vector23.Y;
                            position.Y = vector12.Y + vector24.Y;
                            velocity.Y = vector23.W;
                        }
                        else
{
                            if (vector12.X != vector23.X)
{
                                flag = true;
                            }
                            if (vector12.Y != vector23.Y)
{
                                flag = true;
                            }
                            if (velocity.X != vector23.Z)
{
                                flag = true;
                            }
                            if (velocity.Y != vector23.W)
{
                                flag = true;
                            }
                            vector12.X = vector23.X;
                            vector12.Y = vector23.Y;
                            position = vector12 + vector24;
                            velocity.X = vector23.Z;
                            velocity.Y = vector23.W;
                        }
                    }
                }
                else
                {
                    int num34 = Math.Min(num12, num23);
                    if (num34 < 3)
                    {
                        num34 = 3;
                    }
                    if (num34 > 16)
                    {
                        num34 = 16;
                    }
                    if (((Vector2)(ref velocity)).Length() > (float)num34)
                    {
                        Vector2 val = Collision.TileCollision(vector12, velocity, num12, num23, flag11, flag11);
                        float num45 = ((Vector2)(ref velocity)).Length();
                        float num50 = num34;
                        Vector2 vector25 = velocity.SafeNormalize(Vector2.Zero);
                        if (val.Y == 0f)
{
                            vector25.Y = 0f;
                        }
                        Vector2 zero = Vector2.Zero;
                        _ = Vector2.Zero;
                        _ = Vector2.Zero;
                        Vector2 vector2 = vector12;
                        int num51 = 0;
                        while (num45 > 0f)
{
                            num51++;
                            if (num51 > 300)
{
                                break;
                            }
                            vector2 = vector12;
                            float num52 = num45;
                            if (num52 > num50)
{
                                num52 = num50;
                            }
                            num45 -= num52;
                            Vector2 vector3 = vector25 * num52;
                            Vector2 vector4 = Collision.TileCollision(vector12, vector3, num12, num23, flag11, flag11);
                            vector12 += vector4;
                            velocity = vector4;
                            if (!Main.projPet[type])
{
                                Vector4 vector5 = Collision.SlopeCollision(vector12, velocity, num12, num23, 0f, fall: true);
                                Vector2 vector6 = position - vector12;
                                if (aiStyle == 137)
{
                                    if (vector12.Y != vector5.Y)
{
                                        flag = true;
                                    }
                                    if (velocity.Y != vector5.W)
{
                                        flag = true;
                                    }
                                    vector12.Y = vector5.Y;
                                    position.Y = vector12.Y + vector6.Y;
                                    velocity.Y = vector5.W;
                                }
                                else
{
                                    if (vector12.X != vector5.X)
{
                                        flag = true;
                                    }
                                    if (vector12.Y != vector5.Y)
{
                                        flag = true;
                                    }
                                    if (velocity.X != vector5.Z)
{
                                        flag = true;
                                    }
                                    if (velocity.Y != vector5.W)
{
                                        flag = true;
                                    }
                                    vector12.X = vector5.X;
                                    vector12.Y = vector5.Y;
                                    position = vector12 + vector6;
                                    velocity.X = vector5.Z;
                                    velocity.Y = vector5.W;
                                }
                            }
                            flag7 = true;
                            if (owner == Main.myPlayer && vector12 != vector2 && !flag9)
{
                                Collision.SwitchTiles(vector12, num12, num23, vector2, 4);
                            }
                            vector4 = velocity;
                            zero += vector4;
                        }
                        velocity = zero;
                        if (Math.Abs(velocity.X - lastVelocity.X) < 0.0001f)
{
                            velocity.X = lastVelocity.X;
                        }
                        if (Math.Abs(velocity.Y - lastVelocity.Y) < 0.0001f)
{
                            velocity.Y = lastVelocity.Y;
                        }
                        if (!Main.projPet[type])
{
                            Vector4 vector7 = Collision.SlopeCollision(vector12, velocity, num12, num23, 0f, fall: true);
                            Vector2 vector8 = position - vector12;
                            if (aiStyle == 137)
{
                                if (vector12.Y != vector7.Y)
{
                                    flag = true;
                                }
                                if (velocity.Y != vector7.W)
{
                                    flag = true;
                                }
                                vector12.Y = vector7.Y;
                                position.Y = vector12.Y + vector8.Y;
                                velocity.Y = vector7.W;
                            }
                            else
{
                                if (vector12.X != vector7.X)
{
                                    flag = true;
                                }
                                if (vector12.Y != vector7.Y)
{
                                    flag = true;
                                }
                                if (velocity.X != vector7.Z)
{
                                    flag = true;
                                }
                                if (velocity.Y != vector7.W)
{
                                    flag = true;
                                }
                                vector12.X = vector7.X;
                                vector12.Y = vector7.Y;
                                position = vector12 + vector8;
                                velocity.X = vector7.Z;
                                velocity.Y = vector7.W;
                            }
                        }
                    }
                    else
                    {
                        velocity = Collision.TileCollision(vector12, velocity, num12, num23, flag11, flag11);
                        if (!Main.projPet[type])
{
                            Vector4 vector9 = Collision.SlopeCollision(vector12, velocity, num12, num23, 0f, fall: true);
                            Vector2 vector10 = position - vector12;
                            if (aiStyle == 137)
{
                                if (vector12.Y != vector9.Y)
{
                                    flag = true;
                                }
                                if (velocity.Y != vector9.W)
{
                                    flag = true;
                                }
                                vector12.Y = vector9.Y;
                                position.Y = vector12.Y + vector10.Y;
                                velocity.Y = vector9.W;
                            }
                            else
{
                                if (vector12.X != vector9.X)
{
                                    flag = true;
                                }
                                if (vector12.Y != vector9.Y)
{
                                    flag = true;
                                }
                                if (velocity.X != vector9.Z)
{
                                    flag = true;
                                }
                                if (velocity.Y != vector9.W)
{
                                    flag = true;
                                }
                                vector12.X = vector9.X;
                                vector12.Y = vector9.Y;
                                position = vector12 + vector10;
                                velocity.X = vector9.Z;
                                velocity.Y = vector9.W;
                            }
                        }
                    }
                }
            }
            if (lastVelocity != velocity)
            {
                flag = true;
            }
            if (flag)
            {
                if (owner == Main.myPlayer && CanCutTiles() && (friendly || hostile) && damage > 0)
                {
                    int num53 = (int)(position.X + velocity.X - 1f) / 16;
                    int num2 = (int)((position.X + (float)width + velocity.X + 1f) / 16f) + 1;
                    int num3 = (int)(position.Y + velocity.Y - 1f) / 16;
                    int num4 = (int)((position.Y + (float)height + velocity.Y + 1f) / 16f) + 1;
                    if (num53 < 0)
                    {
                        num53 = 0;
                    }
                    if (num2 > Main.maxTilesX)
                    {
                        num2 = Main.maxTilesX;
                    }
                    if (num3 < 0)
                    {
                        num3 = 0;
                    }
                    if (num4 > Main.maxTilesY)
                    {
                        num4 = Main.maxTilesY;
                    }
                    bool[] tileCutIgnorance = Main.player[owner].GetTileCutIgnorance(allowRegrowth: false, trap);
                    for (int i = num53; i < num2; i++)
                    {
                        for (int j = num3; j < num4; j++)
{
                            if (Main.tile[i, j] != null && !tileCutIgnorance[Main.tile[i, j].type] && Main.tile[i, j].type == 484 && WorldGen.CanCutTile(i, j, TileCuttingContext.AttackProjectile))
{
                                WorldGen.KillTile(i, j);
                                if (Main.netMode != 0)
{
                                    NetMessage.SendData(17, -1, -1, null, 0, i, j);
                                }
                            }
                        }
                    }
                }
                if (Main.rand.Next(3) == 0 && owner == Main.myPlayer && CanCutTiles() && (friendly || hostile) && damage > 0)
                {
                    int num5 = (int)(position.X + velocity.X - 1f) / 16;
                    int num6 = (int)((position.X + (float)width + velocity.X + 1f) / 16f) + 1;
                    int num7 = (int)(position.Y + velocity.Y - 1f) / 16;
                    int num8 = (int)((position.Y + (float)height + velocity.Y + 1f) / 16f) + 1;
                    if (num5 < 0)
                    {
                        num5 = 0;
                    }
                    if (num6 > Main.maxTilesX)
                    {
                        num6 = Main.maxTilesX;
                    }
                    if (num7 < 0)
                    {
                        num7 = 0;
                    }
                    if (num8 > Main.maxTilesY)
                    {
                        num8 = Main.maxTilesY;
                    }
                    bool[] tileCutIgnorance2 = Main.player[owner].GetTileCutIgnorance(allowRegrowth: false, trap);
                    for (int k = num5; k < num6; k++)
                    {
                        for (int l = num7; l < num8; l++)
{
                            if (Main.tile[k, l] != null && !tileCutIgnorance2[Main.tile[k, l].type] && TileID.Sets.CrackedBricks[Main.tile[k, l].type] && WorldGen.CanCutTile(k, l, TileCuttingContext.AttackProjectile))
{
                                WorldGen.KillTile(k, l);
                                if (Main.netMode != 0)
{
                                    NetMessage.SendData(17, -1, -1, null, 0, k, l);
                                }
                            }
                        }
                    }
                }
                if (ProjectileLoader.OnTileCollide(this, lastVelocity))
                {
                    Vector2 center;
                    if (type == 663 || type == 665 || type == 667 || type == 677 || type == 678 || type == 679 || type == 691 || type == 692 || type == 693 || type == 688 || type == 689 || type == 690)
                    {
                        position += velocity;
                        velocity = Vector2.Zero;
                    }
                    else if (type == 434)
                    {
                        position += velocity;
                        numUpdates = 0;
                    }
                    else if (type == 1020)
                    {
                        if (velocity.X != lastVelocity.X && Math.Abs(lastVelocity.X) > 1f)
{
                            velocity.X = (0f - lastVelocity.X) * 0.25f;
                        }
                        if (velocity.Y != lastVelocity.Y && Math.Abs(lastVelocity.Y) > 1f)
{
                            velocity.Y = (0f - lastVelocity.Y) * 0.25f;
                        }
                    }
                    else if (type == 601)
                    {
                        if (Main.netMode != 2 && alpha > 0)
{
                            if (ai[1] != 0f)
{
                                SoundEngine.PlaySound(in SoundID.Item114, position);
                            }
                            else
{
                                SoundEngine.PlaySound(in SoundID.Item115, position);
                            }
                        }
                        if (owner == Main.myPlayer)
{
                            PortalHelper.TryPlacingPortal(this, lastVelocity, velocity);
                        }
                        position += velocity;
                        Kill();
                    }
                    else if (type == 985)
                    {
                        position += velocity;
                        velocity = lastVelocity;
                        velocity *= 0.01f;
                        localAI[1] = 1f;
                    }
                    else if (type == 451)
                    {
                        ai[0] = 1f;
                        ai[1] = 0f;
                        netUpdate = true;
                        velocity = lastVelocity / 2f;
                    }
                    else if (type == 645)
                    {
                        ai[0] = 0f;
                        ai[1] = -1f;
                        netUpdate = true;
                    }
                    else if (type == 584)
                    {
                        bool flag12 = false;
                        if (velocity.X != lastVelocity.X)
{
                            velocity.X = lastVelocity.X * -0.75f;
                            flag12 = true;
                        }
                        if ((velocity.Y != lastVelocity.Y && lastVelocity.Y > 2f) || velocity.Y == 0f)
{
                            velocity.Y = lastVelocity.Y * -0.75f;
                            flag12 = true;
                        }
                        if (flag12)
{
                            float num9 = ((Vector2)(ref lastVelocity)).Length() / ((Vector2)(ref velocity)).Length();
                            if (num9 == 0f)
{
                                num9 = 1f;
                            }
                            velocity /= num9;
                            penetrate--;
                        }
                    }
                    else if (type == 532)
                    {
                        bool flag13 = false;
                        if (velocity.X != lastVelocity.X)
{
                            velocity.X = lastVelocity.X * -0.75f;
                            flag13 = true;
                        }
                        if ((velocity.Y != lastVelocity.Y && lastVelocity.Y > 2f) || velocity.Y == 0f)
{
                            velocity.Y = lastVelocity.Y * -0.75f;
                            flag13 = true;
                        }
                        if (flag13)
{
                            float num10 = ((Vector2)(ref lastVelocity)).Length() / ((Vector2)(ref velocity)).Length();
                            if (num10 == 0f)
{
                                num10 = 1f;
                            }
                            velocity /= num10;
                            penetrate--;
                            Collision.HitTiles(position, lastVelocity, width, height);
                        }
                    }
                    else if (type == 533)
                    {
                        float num11 = 1f;
                        bool flag14 = false;
                        if (velocity.X != lastVelocity.X)
{
                            velocity.X = lastVelocity.X * (0f - num11);
                            flag14 = true;
                        }
                        if (velocity.Y != lastVelocity.Y || velocity.Y == 0f)
{
                            velocity.Y = lastVelocity.Y * (0f - num11) * 0.5f;
                            flag14 = true;
                        }
                        if (flag14)
{
                            float num13 = ((Vector2)(ref lastVelocity)).Length() / ((Vector2)(ref velocity)).Length();
                            if (num13 == 0f)
{
                                num13 = 1f;
                            }
                            velocity /= num13;
                            if (ai[0] == 7f && (double)velocity.Y < -0.1)
{
                                velocity.Y += 0.1f;
                            }
                            if (ai[0] >= 6f && ai[0] < 9f)
{
                                Collision.HitTiles(position, lastVelocity, width, height);
                            }
                            localAI[2] += 30f;
                        }
                    }
                    else if (type == 502)
                    {
                        ai[0] += 1f;
                        SoundEngine.PlaySound(37, (int)position.X, (int)position.Y, 5 + (int)ai[0]);
                        if (ai[0] >= 5f)
{
                            position += velocity;
                            Kill();
                        }
                        else
{
                            if (velocity.Y != lastVelocity.Y)
{
                                velocity.Y = 0f - lastVelocity.Y;
                            }
                            if (velocity.X != lastVelocity.X)
{
                                velocity.X = 0f - lastVelocity.X;
                            }
                        }
                        Vector2 spinningpoint = Utils.RotatedByRandom(new Vector2(0f, -3f - ai[0]), 3.1415927410125732);
                        float num14 = 10f + ai[0] * 4f;
                        Vector2 vector11 = default(Vector2);
                        ((Vector2)(ref vector11))._002Ector(1.05f, 1f);
                        for (float num15 = 0f; num15 < num14; num15 += 1f)
{
                            int num16 = Dust.NewDust(base.Center, 0, 0, 66, 0f, 0f, 0, Color.Transparent);
                            Main.dust[num16].position = base.Center;
                            Dust obj = Main.dust[num16];
                            double radians = (float)Math.PI * 2f * num15 / num14;
                            center = default(Vector2);
                            obj.velocity = spinningpoint.RotatedBy(radians, center) * vector11 * (0.8f + Main.rand.NextFloat() * 0.4f);
                            Main.dust[num16].color = Main.hslToRgb(num15 / num14, 1f, 0.5f);
                            Main.dust[num16].noGravity = true;
                            Main.dust[num16].scale = 1f + ai[0] / 3f;
                        }
                        if (Main.myPlayer == owner)
{
                            int num17 = width;
                            int num18 = height;
                            int num19 = penetrate;
                            position = base.Center;
                            width = (height = 40 + 8 * (int)ai[0]);
                            base.Center = position;
                            penetrate = -1;
                            Damage();
                            penetrate = num19;
                            position = base.Center;
                            width = num17;
                            height = num18;
                            base.Center = position;
                        }
                    }
                    else if (type == 444)
                    {
                        if (velocity.X != lastVelocity.X)
{
                            velocity.X = 0f - lastVelocity.X;
                        }
                        if (velocity.Y != lastVelocity.Y)
{
                            velocity.Y = 0f - lastVelocity.Y;
                        }
                        ai[0] = velocity.ToRotation();
                    }
                    else if (type == 617)
                    {
                        if (velocity.X != lastVelocity.X)
{
                            velocity.X = (0f - lastVelocity.X) * 0.35f;
                        }
                        if (velocity.Y != lastVelocity.Y)
{
                            velocity.Y = (0f - lastVelocity.Y) * 0.35f;
                        }
                    }
                    else if (type == 440 || type == 449 || type == 606)
                    {
                        if (ai[1] != 1f)
{
                            ai[1] = 1f;
                            position += velocity;
                            velocity = lastVelocity;
                        }
                    }
                    else if (type == 85)
                    {
                        velocity = lastVelocity * 0.95f;
                        position -= velocity;
                    }
                    else if (type == 466 || type == 580 || type == 640)
                    {
                        if (localAI[1] < 1f)
{
                            localAI[1] += 2f;
                            position += velocity;
                            velocity = Vector2.Zero;
                        }
                    }
                    else if (type == 851)
                    {
                        if (velocity.X != lastVelocity.X)
{
                            velocity.X = (0f - lastVelocity.X) * 0.8f;
                        }
                        if (velocity.Y != lastVelocity.Y)
{
                            velocity.Y = (0f - lastVelocity.Y) * 0.5f;
                        }
                    }
                    else if (type == 855)
                    {
                        if (velocity.X != lastVelocity.X)
{
                            velocity.X = 0f - lastVelocity.X;
                        }
                        if (velocity.Y != lastVelocity.Y)
{
                            velocity.Y = 0f - lastVelocity.Y;
                            if (lastVelocity.Y < 0f)
{
                                velocity.Y *= 0.25f;
                            }
                        }
                    }
                    else if (aiStyle == 54)
                    {
                        if (velocity.X != lastVelocity.X)
{
                            velocity.X = lastVelocity.X * -0.6f;
                        }
                        if (velocity.Y != lastVelocity.Y)
{
                            velocity.Y = lastVelocity.Y * -0.6f;
                        }
                    }
                    else if (type == 861)
                    {
                        float num20 = -1f;
                        if (ai[1] == 1f)
{
                            num20 = -0.6f;
                        }
                        if (velocity.X != lastVelocity.X)
{
                            velocity.X = lastVelocity.X * num20;
                        }
                        if (velocity.Y != lastVelocity.Y && (double)lastVelocity.Y > 0.7)
{
                            velocity.Y = lastVelocity.Y * num20;
                        }
                        if (Math.Abs(velocity.Y) < 0.5f)
{
                            velocity.Y = 0f;
                        }
                        if (ai[1] != 1f)
{
                            netUpdate = true;
                        }
                        ai[1] = 1f;
                    }
                    else if (!Main.projPet[type] && type != 500 && type != 820 && aiStyle != 160 && type != 650 && type != 882 && type != 888 && type != 894 && type != 895 && type != 898 && type != 901 && type != 957)
                    {
                        if (aiStyle == 99)
{
                            if (type >= 556 && type <= 561)
{
                                bool flag2 = false;
                                if (velocity.X != lastVelocity.X)
{
                                    flag2 = true;
                                    velocity.X = lastVelocity.X * -1f;
                                }
                                if (velocity.Y != lastVelocity.Y)
{
                                    flag2 = true;
                                    velocity.Y = lastVelocity.Y * -1f;
                                }
                                if (flag2)
{
                                    Vector2 vector13 = Main.player[owner].Center - base.Center;
                                    ((Vector2)(ref vector13)).Normalize();
                                    vector13 *= ((Vector2)(ref velocity)).Length();
                                    vector13 *= 0.25f;
                                    velocity *= 0.75f;
                                    velocity += vector13;
                                    if (((Vector2)(ref velocity)).Length() > 6f)
{
                                        velocity *= 0.5f;
                                    }
                                }
                            }
                        }
                        else if (type == 604)
{
                            if (velocity.X != lastVelocity.X)
{
                                velocity.X = 0f - lastVelocity.X;
                            }
                            if (velocity.Y != lastVelocity.Y)
{
                                velocity.Y = 0f - lastVelocity.Y;
                            }
                        }
                        else if (type == 379)
{
                            if (velocity.X != lastVelocity.X)
{
                                velocity.X = lastVelocity.X * -0.6f;
                            }
                            if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 2f)
{
                                velocity.Y = lastVelocity.Y * -0.6f;
                            }
                        }
                        else if (type == 491)
{
                            if (ai[0] <= 0f)
{
                                ai[0] = -10f;
                            }
                            if (velocity.X != lastVelocity.X && Math.Abs(lastVelocity.X) > 0f)
{
                                velocity.X = lastVelocity.X * -1f;
                            }
                            if (velocity.Y != lastVelocity.Y && Math.Abs(lastVelocity.Y) > 0f)
{
                                velocity.Y = lastVelocity.Y * -1f;
                            }
                        }
                        else if ((type >= 515 && type <= 517) || type == 637)
{
                            if (velocity.X != lastVelocity.X && Math.Abs(lastVelocity.X) > 1f)
{
                                velocity.X = lastVelocity.X * -0.9f;
                            }
                            if (velocity.Y != lastVelocity.Y && Math.Abs(lastVelocity.Y) > 1f)
{
                                velocity.Y = lastVelocity.Y * -0.9f;
                            }
                        }
                        else if (type == 921 || type == 926 || type == 937)
{
                            if (velocity.X != lastVelocity.X && Math.Abs(lastVelocity.X) > 1f)
{
                                velocity.X = lastVelocity.X * -0.4f;
                            }
                            if (velocity.Y != lastVelocity.Y && Math.Abs(lastVelocity.Y) > 1f)
{
                                velocity.Y = lastVelocity.Y * -0.95f;
                            }
                            penetrate--;
                        }
                        else if (type == 969)
{
                            if (velocity.X != lastVelocity.X && Math.Abs(lastVelocity.X) > 1f)
{
                                velocity.X = lastVelocity.X * -0.75f;
                            }
                            if (velocity.Y != lastVelocity.Y && Math.Abs(lastVelocity.Y) > 1f)
{
                                velocity.Y = lastVelocity.Y * -0.75f;
                            }
                        }
                        else if (type == 681)
{
                            timeLeft = 4;
                        }
                        else if (type == 409)
{
                            if (velocity.X != lastVelocity.X)
{
                                velocity.X = lastVelocity.X * -1f;
                            }
                            if (velocity.Y != lastVelocity.Y)
{
                                velocity.Y = lastVelocity.Y * -1f;
                            }
                        }
                        else if (type == 254)
{
                            if (velocity.X != lastVelocity.X)
{
                                velocity.X = lastVelocity.X * -1f;
                            }
                            if (velocity.Y != lastVelocity.Y)
{
                                velocity.Y = lastVelocity.Y * -1f;
                            }
                        }
                        else if (type == 225)
{
                            ai[1] += 1f;
                            if (ai[1] == 1f)
{
                                damage = (int)((float)damage * 0.66f);
                            }
                            if (ai[1] >= 4f)
{
                                Kill();
                                return;
                            }
                            velocity.X = 0f - lastVelocity.X;
                            velocity.Y = 0f - lastVelocity.Y;
                            int num21 = FindTargetWithLineOfSight();
                            if (num21 != -1)
{
                                NPC nPC = Main.npc[num21];
                                float t = Distance(nPC.Center);
                                Vector2 vector14 = -Vector2.UnitY * MathHelper.Lerp((float)nPC.height * 0.1f, (float)nPC.height * 0.5f, Utils.GetLerpValue(0f, 300f, t));
                                velocity = DirectionTo(nPC.Center + vector14).SafeNormalize(-Vector2.UnitY) * ((Vector2)(ref velocity)).Length();
                                netUpdate = true;
                            }
                        }
                        else if (type == 285)
{
                            ai[1] += 1f;
                            if (ai[1] == 1f)
{
                                damage = (int)((float)damage * 0.66f);
                            }
                            if (ai[1] >= 2f)
{
                                Kill();
                                return;
                            }
                            if (velocity.X != lastVelocity.X)
{
                                velocity.X = lastVelocity.X * -1f;
                            }
                            if (velocity.Y != lastVelocity.Y)
{
                                velocity.Y = lastVelocity.Y * -1f;
                            }
                            int num22 = FindTargetWithLineOfSight();
                            if (num22 != -1)
{
                                NPC nPC2 = Main.npc[num22];
                                Distance(nPC2.Center);
                                velocity = DirectionTo(nPC2.Center).SafeNormalize(-Vector2.UnitY) * ((Vector2)(ref velocity)).Length();
                                netUpdate = true;
                            }
                        }
                        else if (type == 931)
{
                            if (velocity.X != lastVelocity.X)
{
                                velocity.X = lastVelocity.X * -1f;
                            }
                            if (velocity.Y != lastVelocity.Y)
{
                                velocity.Y = lastVelocity.Y * -1f;
                            }
                        }
                        else if (type == 155)
{
                            if (ai[1] > 10f)
{
                                NetworkText networkText = NetworkText.FromKey("Game.BallBounceResult", NetworkText.FromKey(Lang.GetProjectileName(type).Key), ai[1]);
                                if (Main.netMode == 0)
{
                                    Main.NewText(networkText.ToString(), byte.MaxValue, 240, 20);
                                }
                                else if (Main.netMode == 2)
{
                                    ChatHelper.BroadcastChatMessage(networkText, new Color(255, 240, 20));
                                }
                            }
                            ai[1] = 0f;
                            if (velocity.X != lastVelocity.X)
{
                                velocity.X = lastVelocity.X * -0.6f;
                            }
                            if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 2f)
{
                                velocity.Y = lastVelocity.Y * -0.6f;
                            }
                        }
                        else if (aiStyle == 33)
{
                            if (localAI[0] == 0f)
{
                                if (wet)
{
                                    position += lastVelocity / 2f;
                                }
                                else
{
                                    position += lastVelocity;
                                }
                                velocity *= 0f;
                                localAI[0] = 1f;
                            }
                        }
                        else if (type != 308 && type != 377 && type != 966)
{
                            if (type == 477)
{
                                if (velocity.Y != lastVelocity.Y || velocity.X != lastVelocity.X)
{
                                    penetrate--;
                                    if (penetrate <= 0)
{
                                        Kill();
                                    }
                                    if (velocity.X != lastVelocity.X)
{
                                        velocity.X = 0f - lastVelocity.X;
                                    }
                                    if (velocity.Y != lastVelocity.Y)
{
                                        velocity.Y = 0f - lastVelocity.Y;
                                    }
                                }
                                if (penetrate > 0 && owner == Main.myPlayer)
{
                                    int[] array = new int[10];
                                    int num24 = 0;
                                    int num25 = 700;
                                    int num26 = 20;
                                    for (int m = 0; m < 200; m++)
{
                                        if (!Main.npc[m].CanBeChasedBy(this))
{
                                            continue;
                                        }
                                        center = base.Center - Main.npc[m].Center;
                                        float num27 = ((Vector2)(ref center)).Length();
                                        if (num27 > (float)num26 && num27 < (float)num25 && Collision.CanHitLine(base.Center, 1, 1, Main.npc[m].Center, 1, 1))
{
                                            array[num24] = m;
                                            num24++;
                                            if (num24 >= 9)
{
                                                break;
                                            }
                                        }
                                    }
                                    if (num24 > 0)
{
                                        num24 = Main.rand.Next(num24);
                                        Vector2 vector15 = Main.npc[array[num24]].Center - base.Center;
                                        float num28 = ((Vector2)(ref velocity)).Length();
                                        ((Vector2)(ref vector15)).Normalize();
                                        velocity = vector15 * num28;
                                        netUpdate = true;
                                    }
                                }
                            }
                            else if (type == 94)
{
                                if (velocity.X != lastVelocity.X)
{
                                    velocity.X = 0f - lastVelocity.X;
                                }
                                if (velocity.Y != lastVelocity.Y)
{
                                    velocity.Y = 0f - lastVelocity.Y;
                                }
                            }
                            else if (type == 496)
{
                                if (velocity.X != lastVelocity.X)
{
                                    if (Math.Abs(velocity.X) < 1f)
{
                                        velocity.X = 0f - lastVelocity.X;
                                    }
                                    else
{
                                        Kill();
                                    }
                                }
                                if (velocity.Y != lastVelocity.Y)
{
                                    if (Math.Abs(velocity.Y) < 1f)
{
                                        velocity.Y = 0f - lastVelocity.Y;
                                    }
                                    else
{
                                        Kill();
                                    }
                                }
                            }
                            else if (type == 311)
{
                                if (velocity.X != lastVelocity.X)
{
                                    velocity.X = 0f - lastVelocity.X;
                                    ai[1] += 1f;
                                }
                                if (velocity.Y != lastVelocity.Y)
{
                                    velocity.Y = 0f - lastVelocity.Y;
                                    ai[1] += 1f;
                                }
                                if (ai[1] > 4f)
{
                                    Kill();
                                }
                            }
                            else if (type == 312)
{
                                if (velocity.X != lastVelocity.X)
{
                                    velocity.X = 0f - lastVelocity.X;
                                    ai[1] += 1f;
                                }
                                if (velocity.Y != lastVelocity.Y)
{
                                    velocity.Y = 0f - lastVelocity.Y;
                                    ai[1] += 1f;
                                }
                            }
                            else if (type == 522 || type == 620)
{
                                if (velocity.X != lastVelocity.X)
{
                                    velocity.X = 0f - lastVelocity.X;
                                }
                                if (velocity.Y != lastVelocity.Y)
{
                                    velocity.Y = 0f - lastVelocity.Y;
                                }
                            }
                            else if (type == 524)
{
                                ai[0] += 100f;
                                if (velocity.X != lastVelocity.X)
{
                                    velocity.X = 0f - lastVelocity.X;
                                }
                                if (velocity.Y != lastVelocity.Y)
{
                                    velocity.Y = 0f - lastVelocity.Y;
                                }
                            }
                            else if (aiStyle == 93)
{
                                if (velocity != lastVelocity)
{
                                    ai[1] = 0f;
                                    ai[0] = 1f;
                                    netUpdate = true;
                                    tileCollide = false;
                                    position += velocity;
                                    velocity = lastVelocity;
                                    ((Vector2)(ref velocity)).Normalize();
                                    velocity *= 3f;
                                }
                            }
                            else if (type == 281)
{
                                bool flag3 = Math.Abs(velocity.X) + Math.Abs(velocity.Y) < 2f || ai[0] == -1f;
                                if (ai[0] == -2f || ai[0] == -3f)
{
                                    flag3 = false;
                                }
                                if (flag3)
{
                                    if (Main.myPlayer == owner)
{
                                        int num29 = ((velocity.X > 0f) ? 1 : 2);
                                        if (damage == 0)
{
                                            num29 += 2;
                                        }
                                        NPC.ReleaseNPC((int)base.Center.X, (int)base.Bottom.Y - 4, 614, num29, owner);
                                        ai[0] = -3f;
                                        netUpdate = true;
                                    }
                                }
                                else
{
                                    if (velocity.X != lastVelocity.X)
{
                                        velocity.X = (0f - lastVelocity.X) * 0.5f;
                                    }
                                    if (velocity.Y != lastVelocity.Y)
{
                                        velocity.Y = (0f - lastVelocity.Y) * 0.5f;
                                    }
                                }
                            }
                            else if (type == 290 || type == 294)
{
                                if (velocity.X != lastVelocity.X)
{
                                    position.X += velocity.X;
                                    velocity.X = 0f - lastVelocity.X;
                                }
                                if (velocity.Y != lastVelocity.Y)
{
                                    position.Y += velocity.Y;
                                    velocity.Y = 0f - lastVelocity.Y;
                                }
                            }
                            else if ((type == 181 || type == 189 || type == 357 || type == 566) && penetrate > 0)
{
                                if (type == 357)
{
                                    damage = (int)((double)damage * 0.9);
                                }
                                penetrate--;
                                if (velocity.X != lastVelocity.X)
{
                                    velocity.X = 0f - lastVelocity.X;
                                }
                                if (velocity.Y != lastVelocity.Y)
{
                                    velocity.Y = 0f - lastVelocity.Y;
                                }
                            }
                            else if (type == 307 && ai[1] < 5f)
{
                                ai[1] += 1f;
                                if (velocity.X != lastVelocity.X)
{
                                    velocity.X = 0f - lastVelocity.X;
                                }
                                if (velocity.Y != lastVelocity.Y)
{
                                    velocity.Y = 0f - lastVelocity.Y;
                                }
                            }
                            else if (type == 99 || type == 1005 || type == 1014)
{
                                if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 5f)
{
                                    Collision.HitTiles(position, velocity, width, height);
                                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                                    velocity.Y = (0f - lastVelocity.Y) * 0.2f;
                                }
                                if (velocity.X != lastVelocity.X)
{
                                    Kill();
                                }
                            }
                            else if (type == 1021)
{
                                if (velocity.Y != lastVelocity.Y)
{
                                    if (lastVelocity.Y > 4f)
{
                                        Collision.HitTiles(position, velocity, width, height);
                                        SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                                        velocity.Y = (0f - lastVelocity.Y) * 0.9f;
                                    }
                                    else if (lastVelocity.Y > 0f)
{
                                        localAI[1] = 999f;
                                    }
                                }
                                if (velocity.X != lastVelocity.X)
{
                                    if (localAI[1] <= 3f)
{
                                        velocity.X = lastVelocity.X * -0.75f;
                                        localAI[1] += 1f;
                                    }
                                    else
{
                                        Kill();
                                    }
                                }
                            }
                            else if (type == 1013)
{
                                float num30 = Math.Abs(lastVelocity.X);
                                float num31 = Math.Abs(lastVelocity.Y);
                                float num32 = 0.95f;
                                float num33 = 0.95f;
                                if (num30 < 0.5f)
{
                                    num32 = 0.1f;
                                }
                                else if (num30 < 0.75f)
{
                                    num32 = 0.25f;
                                }
                                else if (num30 < 1f)
{
                                    num32 = 0.5f;
                                }
                                if (num31 < 0.5f)
{
                                    num33 = 0.1f;
                                }
                                else if (num31 < 0.75f)
{
                                    num33 = 0.25f;
                                }
                                else if (num31 < 1f)
{
                                    num33 = 0.5f;
                                }
                                bool flag4 = false;
                                if (velocity.Y != lastVelocity.Y)
{
                                    if (Math.Abs(lastVelocity.Y) > 5f)
{
                                        flag4 = true;
                                    }
                                    velocity.Y = (0f - lastVelocity.Y) * num33;
                                }
                                if (velocity.X != lastVelocity.X)
{
                                    if (Math.Abs(lastVelocity.X) > 5f)
{
                                        flag4 = true;
                                    }
                                    velocity.X = (0f - lastVelocity.X) * num32;
                                }
                                if (flag4)
{
                                    localAI[1] += 1f;
                                    Collision.HitTiles(position, velocity, width, height);
                                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                                }
                                if (((Vector2)(ref velocity)).Length() < 0.1f && localAI[0] > 50f)
{
                                    Kill();
                                }
                                if (localAI[1] > 20f)
{
                                    Kill();
                                }
                            }
                            else if (type == 727)
{
                                int num35 = 30;
                                float num36 = 2f;
                                float num37 = 2f;
                                if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 5f)
{
                                    Collision.HitTiles(position, velocity, width, height);
                                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                                    velocity.Y = (0f - lastVelocity.Y) * 0.65f;
                                    if (owner == Main.myPlayer)
{
                                        int num38 = Main.rand.Next(3, 6);
                                        float num39 = Main.rand.NextFloat();
                                        for (float num40 = 0f; num40 < 1f; num40 += 1f / (float)num38)
{
                                            Vector2 vector16 = ((num39 + num40) * ((float)Math.PI * 2f)).ToRotationVector2() * num37;
                                            if (vector16.Y > 0f)
{
                                                vector16 *= -0.7f;
                                            }
                                            NewProjectile(GetProjectileSource_FromThis(), base.Center, vector16, 763, num35, num36, Main.myPlayer);
                                        }
                                    }
                                }
                                if (velocity.X != lastVelocity.X)
{
                                    Kill();
                                    if (owner == Main.myPlayer)
{
                                        int num41 = Main.rand.Next(3, 6);
                                        float num42 = Main.rand.NextFloat();
                                        for (float num43 = 0f; num43 < 1f; num43 += 1f / (float)num41)
{
                                            Vector2 vector17 = ((num42 + num43) * ((float)Math.PI * 2f)).ToRotationVector2() * num37;
                                            if (vector17.Y > 0f)
{
                                                vector17 *= -0.7f;
                                            }
                                            NewProjectile(GetProjectileSource_FromThis(), base.Center, vector17, 763, num35, num36, Main.myPlayer);
                                        }
                                    }
                                }
                            }
                            else if (type == 655)
{
                                if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 5f)
{
                                    Collision.HitTiles(position, velocity, width, height);
                                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                                    velocity.Y = (0f - lastVelocity.Y) * 0.2f;
                                }
                                if (velocity.X != lastVelocity.X)
{
                                    Kill();
                                }
                            }
                            else if (type == 36)
{
                                if (penetrate > 1)
{
                                    Collision.HitTiles(position, velocity, width, height);
                                    SoundEngine.PlaySound(in SoundID.Item10, position);
                                    penetrate--;
                                    if (velocity.X != lastVelocity.X)
{
                                        velocity.X = 0f - lastVelocity.X;
                                    }
                                    if (velocity.Y != lastVelocity.Y)
{
                                        velocity.Y = 0f - lastVelocity.Y;
                                    }
                                }
                                else
{
                                    Kill();
                                }
                            }
                            else if (aiStyle == 21)
{
                                if (velocity.X != lastVelocity.X)
{
                                    velocity.X = 0f - lastVelocity.X;
                                }
                                if (velocity.Y != lastVelocity.Y)
{
                                    velocity.Y = 0f - lastVelocity.Y;
                                }
                            }
                            else if (aiStyle == 17)
{
                                if (velocity.X != lastVelocity.X)
{
                                    velocity.X = lastVelocity.X * -0.75f;
                                }
                                if (velocity.Y != lastVelocity.Y && (double)lastVelocity.Y > 1.5)
{
                                    velocity.Y = lastVelocity.Y * -0.7f;
                                }
                            }
                            else if (aiStyle == 15)
{
                                AI_015_HandleMovementCollision(ref wetVelocity, ref lastVelocity);
                            }
                            else if (aiStyle == 9)
{
                                bool flag5 = owner == Main.myPlayer;
                                if (type == 79)
{
                                    bool flag6 = ai[0] >= 0f;
                                    flag5 = flag5 && !flag6;
                                    if (flag6)
{
                                        if (velocity.X != lastVelocity.X)
{
                                            velocity.X *= 0.1f;
                                        }
                                        if (velocity.Y != lastVelocity.Y)
{
                                            velocity.Y *= 0.1f;
                                        }
                                    }
                                }
                                if (flag5)
{
                                    Kill();
                                }
                            }
                            else if (aiStyle == 39)
{
                                Collision.HitTiles(position, velocity, width, height);
                                if (type == 33 || type == 106)
{
                                    if (velocity.X != lastVelocity.X)
{
                                        velocity.X = 0f - lastVelocity.X;
                                    }
                                    if (velocity.Y != lastVelocity.Y)
{
                                        velocity.Y = 0f - lastVelocity.Y;
                                    }
                                }
                                else
{
                                    ai[0] = 1f;
                                    if (aiStyle == 3)
{
                                        velocity.X = 0f - lastVelocity.X;
                                        velocity.Y = 0f - lastVelocity.Y;
                                    }
                                }
                                netUpdate = true;
                                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                            }
                            else if (aiStyle == 3 || aiStyle == 13 || aiStyle == 69 || aiStyle == 109)
{
                                if (type == 106)
{
                                    Vector2 hitPoint = base.Center + velocity.SafeNormalize(Vector2.UnitX) * 8f * scale;
                                    Vector2 normal = default(Vector2);
                                    ((Vector2)(ref normal))._002Ector((float)((velocity.X != lastVelocity.X) ? (-Math.Sign(lastVelocity.X)) : 0), (float)((velocity.Y != lastVelocity.Y) ? (-Math.Sign(lastVelocity.Y)) : 0));
                                    LightDisc_Bounce(hitPoint, normal);
                                }
                                Collision.HitTiles(position, velocity, width, height);
                                if (type == 33 || type == 106 || type == 866)
{
                                    if (velocity.X != lastVelocity.X)
{
                                        velocity.X = 0f - lastVelocity.X;
                                    }
                                    if (velocity.Y != lastVelocity.Y)
{
                                        velocity.Y = 0f - lastVelocity.Y;
                                    }
                                }
                                else
{
                                    ai[0] = 1f;
                                    if ((aiStyle == 3 || aiStyle == 109) && type != 383)
{
                                        velocity.X = 0f - lastVelocity.X;
                                        velocity.Y = 0f - lastVelocity.Y;
                                    }
                                }
                                netUpdate = true;
                                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                            }
                            else if (aiStyle == 8 && type != 96)
{
                                SoundEngine.PlaySound(in SoundID.Item10, position);
                                ai[0] += 1f;
                                int num44 = 5;
                                switch (type)
{
                                case 15:
                                    num44 = 6;
                                    break;
                                case 253:
                                    num44 = 8;
                                    break;
                                }
                                if (ai[0] >= (float)num44)
{
                                    position += velocity;
                                    Kill();
                                }
                                else
{
                                    if (type == 15 && velocity.Y > 4f)
{
                                        if (velocity.Y != lastVelocity.Y)
{
                                            velocity.Y = (0f - lastVelocity.Y) * 0.8f;
                                        }
                                    }
                                    else if (velocity.Y != lastVelocity.Y)
{
                                        velocity.Y = 0f - lastVelocity.Y;
                                    }
                                    if (velocity.X != lastVelocity.X)
{
                                        velocity.X = 0f - lastVelocity.X;
                                    }
                                }
                            }
                            else if (aiStyle == 61)
{
                                if (velocity.X != lastVelocity.X)
{
                                    velocity.X = lastVelocity.X * -0.3f;
                                }
                                if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 1f)
{
                                    velocity.Y = lastVelocity.Y * -0.3f;
                                }
                            }
                            else if (aiStyle == 14)
{
                                if (type == 928)
{
                                    int num46 = 0;
                                    for (int num47 = 1000; num47 >= 0; num47--)
{
                                        if (num47 != whoAmI && Main.projectile[num47].active && Main.projectile[num47].owner == owner && Main.projectile[num47].type == type)
{
                                            num46++;
                                            if (num46 >= 2 && timeLeft > Main.projectile[num47].timeLeft && Main.projectile[num47].timeLeft > 30)
{
                                                Main.projectile[num47].timeLeft = 2;
                                            }
                                        }
                                    }
                                }
                                if (type == 261 && ((velocity.X != lastVelocity.X && (lastVelocity.X < -3f || lastVelocity.X > 3f)) || (velocity.Y != lastVelocity.Y && (lastVelocity.Y < -3f || lastVelocity.Y > 3f))))
{
                                    for (int n = 0; n < 10; n++)
{
                                        Collision.HitTiles(position, velocity, width, height);
                                    }
                                    SoundEngine.PlaySound(0, (int)base.Center.X, (int)base.Center.Y);
                                    MakeBoulderOfEarthExplosion();
                                }
                                if (type >= 326 && type <= 328 && velocity.X != lastVelocity.X)
{
                                    velocity.X = lastVelocity.X * -0.1f;
                                }
                                if (type >= 400 && type <= 402)
{
                                    if (velocity.X != lastVelocity.X)
{
                                        velocity.X = lastVelocity.X * -0.1f;
                                    }
                                }
                                else if (type == 870 && ai[1] == 0f)
{
                                    if (velocity.X != lastVelocity.X || velocity.Y != lastVelocity.Y)
{
                                        velocity = -lastVelocity;
                                        ai[1] = 1f;
                                    }
                                }
                                else if (type == 50)
{
                                    if (velocity.X != lastVelocity.X)
{
                                        velocity.X = lastVelocity.X * -0.2f;
                                    }
                                    if (velocity.Y != lastVelocity.Y && (double)lastVelocity.Y > 1.5)
{
                                        velocity.Y = lastVelocity.Y * -0.2f;
                                    }
                                }
                                else if (type == 185)
{
                                    if (velocity.X != lastVelocity.X)
{
                                        velocity.X = lastVelocity.X * -0.9f;
                                    }
                                    if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 1f)
{
                                        velocity.Y = lastVelocity.Y * -0.9f;
                                    }
                                }
                                else if (type == 277)
{
                                    if (velocity.X != lastVelocity.X)
{
                                        velocity.X = lastVelocity.X * -0.9f;
                                    }
                                    if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 3f)
{
                                        velocity.Y = lastVelocity.Y * -0.9f;
                                    }
                                }
                                else if (type != 480)
{
                                    if (type == 450)
{
                                        if (velocity.X != lastVelocity.X)
{
                                            velocity.X = lastVelocity.X * -0.1f;
                                        }
                                    }
                                    else
{
                                        if (velocity.X != lastVelocity.X)
{
                                            velocity.X = lastVelocity.X * -0.5f;
                                        }
                                        if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 1f)
{
                                            velocity.Y = lastVelocity.Y * -0.5f;
                                        }
                                    }
                                }
                            }
                            else if (aiStyle == 16)
{
                                if (velocity.X != lastVelocity.X)
{
                                    velocity.X = lastVelocity.X * -0.4f;
                                    if (type == 29)
{
                                        velocity.X *= 0.8f;
                                    }
                                }
                                if (velocity.Y != lastVelocity.Y && (double)lastVelocity.Y > 0.7 && type != 102)
{
                                    velocity.Y = lastVelocity.Y * -0.4f;
                                    if (type == 29)
{
                                        velocity.Y *= 0.8f;
                                    }
                                }
                                if (type == 134 || type == 137 || type == 140 || type == 143 || type == 303 || (type >= 338 && type <= 341) || type == 776 || type == 780 || type == 793 || type == 796 || type == 799 || type == 784 || type == 787 || type == 790 || type == 803 || type == 804 || type == 808 || type == 809 || type == 810 || type == 805 || type == 806 || type == 807 || type == 930)
{
                                    velocity *= 0f;
                                    alpha = 255;
                                    timeLeft = 3;
                                }
                            }
                            else if (aiStyle == 68)
{
                                velocity *= 0f;
                                alpha = 255;
                                timeLeft = 3;
                                netUpdate = true;
                            }
                            else if (type == 870)
{
                                if (velocity.X != lastVelocity.X)
{
                                    velocity.X = lastVelocity.X * -0.2f;
                                }
                                if (velocity.Y != lastVelocity.Y && lastVelocity.Y > 0f)
{
                                    velocity.Y = lastVelocity.Y * -0.2f;
                                }
                            }
                            else
{
                                position += velocity;
                                Kill();
                            }
                        }
                    }
                }
            }
        }
        UpdatePosition(wetVelocity);
        if (!flag7 && !flag9 && owner == Main.myPlayer && (tileCollide || flag10) && position != oldPosition)
        {
            Vector2 vector18 = position;
            Vector2 vector19 = oldPosition;
            int num48 = ((overrideWidth != -1) ? overrideWidth : width);
            int num49 = ((overrideHeight != -1) ? overrideHeight : height);
            if (overrideHeight != -1 || overrideWidth != -1)
            {
                ((Vector2)(ref vector18))._002Ector(position.X + (float)(width / 2) - (float)(num48 / 2), position.Y + (float)(height / 2) - (float)(num49 / 2));
                ((Vector2)(ref vector19))._002Ector(oldPosition.X + (float)(width / 2) - (float)(num48 / 2), oldPosition.Y + (float)(height / 2) - (float)(num49 / 2));
            }
            Collision.SwitchTiles(vector18, num48, num49, vector19, 4);
        }
    }
References Terraria.Projectile.ai, Terraria.Projectile.AI_015_HandleMovementCollision(), Terraria.Projectile.aiStyle, Terraria.Projectile.alpha, Terraria.Collision.AnyCollisionWithSpecificTiles(), Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.WorldGen.CanCutTile(), Terraria.Projectile.CanCutTiles(), Terraria.Collision.CanHitLine(), Terraria.ID.TileID.Sets.CrackedBricks, Terraria.Projectile.damage, Terraria.Projectile.Damage(), Terraria.Projectile.decidesManualFallThrough, Terraria.Entity.DirectionTo(), Terraria.Entity.Distance(), Terraria.Main.dust, Terraria.ID.TileID.Sets.Falling, Terraria.ID.ProjectileID.Sets.FallingBlockDoesNotFallThroughPlatforms, Terraria.Projectile.FindTargetWithLineOfSight(), Terraria.ID.ProjectileID.Sets.ForcePlateDetection, Terraria.Projectile.friendly, Terraria.Localization.NetworkText.FromKey(), Terraria.Utils.GetLerpValue(), Terraria.Lang.GetProjectileName(), Terraria.Projectile.GetProjectileSource_FromThis(), Terraria.Entity.height, Terraria.Collision.HitTiles(), Terraria.Entity.honeyWet, Terraria.Projectile.hostile, Terraria.Main.hslToRgb(), Terraria.ID.SoundID.Item10, Terraria.ID.SoundID.Item114, Terraria.ID.SoundID.Item115, Terraria.Projectile.Kill(), Terraria.WorldGen.KillTile(), Terraria.Projectile.LightDisc_Bounce(), Terraria.Projectile.localAI, Terraria.Projectile.MakeBoulderOfEarthExplosion(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.netUpdate, Terraria.Dust.NewDust(), Terraria.Projectile.NewProjectile(), Terraria.Main.NewText(), Terraria.Main.npc, Terraria.Projectile.numUpdates, Terraria.Entity.oldPosition, Terraria.ModLoader.ProjectileLoader.OnTileCollide(), Terraria.Projectile.owner, Terraria.Projectile.penetrate, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.projPet, Terraria.Main.rand, Terraria.NPC.ReleaseNPC(), Terraria.Utils.RotatedByRandom(), Terraria.Projectile.rotation, Terraria.Projectile.scale, Terraria.NetMessage.SendData(), Terraria.Entity.shimmerWet, Terraria.Projectile.shouldFallThrough, Terraria.Collision.SlopeCollision(), Terraria.Collision.SwitchTiles(), Terraria.Main.tile, Terraria.Projectile.tileCollide, Terraria.ModLoader.ProjectileLoader.TileCollideStyle(), Terraria.Collision.TileCollision(), Terraria.Projectile.timeLeft, Terraria.Projectile.trap, Terraria.GameContent.PortalHelper.TryPlacingPortal(), Terraria.Projectile.type, Terraria.Projectile.UpdatePosition(), Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Projectile.Update().