TModLoader: Terraria.Projectile.EmitEnchantmentVisualsAt
EmitEnchantmentVisualsAt()
void Terraria.Projectile.EmitEnchantmentVisualsAt (Vector2 boxPosition, int boxWidth, int boxHeight) inline
    {
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_0238: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0278: Unknown result type (might be due to invalid IL or missing references)
        //IL_027d: Unknown result type (might be due to invalid IL or missing references)
        //IL_029b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_031e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_037d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0387: Unknown result type (might be due to invalid IL or missing references)
        //IL_038c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0403: Unknown result type (might be due to invalid IL or missing references)
        //IL_0427: Unknown result type (might be due to invalid IL or missing references)
        //IL_0431: Unknown result type (might be due to invalid IL or missing references)
        //IL_0436: Unknown result type (might be due to invalid IL or missing references)
        //IL_0476: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_051f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0535: Unknown result type (might be due to invalid IL or missing references)
        //IL_053b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0628: Unknown result type (might be due to invalid IL or missing references)
        //IL_062d: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_063d: Unknown result type (might be due to invalid IL or missing references)
        //IL_064c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0651: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08de: Unknown result type (might be due to invalid IL or missing references)
        //IL_0914: Unknown result type (might be due to invalid IL or missing references)
        //IL_091e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0923: Unknown result type (might be due to invalid IL or missing references)
        //IL_067a: Unknown result type (might be due to invalid IL or missing references)
        //IL_067f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0686: Unknown result type (might be due to invalid IL or missing references)
        //IL_0690: Unknown result type (might be due to invalid IL or missing references)
        //IL_0696: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b7: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        if (player.frostBurn && (melee || ranged) && friendly && !hostile && !noEnchantments && Main.rand.Next(2 * (1 + extraUpdates)) == 0)
        {
            int num = Dust.NewDust(boxPosition, boxWidth, boxHeight, 135, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 2f);
            Main.dust[num].noGravity = true;
            Dust obj = Main.dust[num];
            obj.velocity *= 0.7f;
            Main.dust[num].velocity.Y -= 0.5f;
        }
        if (melee && player.magmaStone && !noEnchantments && Main.rand.Next(3) != 0)
        {
            int num7 = Dust.NewDust(new Vector2(boxPosition.X - 4f, boxPosition.Y - 4f), boxWidth + 8, boxHeight + 8, 6, velocity.X * 0.2f, velocity.Y * 0.2f, 100, default(Color), 2f);
            if (Main.rand.Next(2) == 0)
            {
                Main.dust[num7].scale = 1.5f;
            }
            Main.dust[num7].noGravity = true;
            Main.dust[num7].velocity.X *= 2f;
            Main.dust[num7].velocity.Y *= 2f;
        }
        if ((!melee && !ProjectileID.Sets.IsAWhip[type]) || player.meleeEnchant <= 0 || noEnchantments)
        {
            return;
        }
        if (player.meleeEnchant == 1 && Main.rand.Next(3) == 0)
        {
            int num8 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 171, 0f, 0f, 100);
            Main.dust[num8].noGravity = true;
            Main.dust[num8].fadeIn = 1.5f;
            Dust obj2 = Main.dust[num8];
            obj2.velocity *= 0.25f;
        }
        if (player.meleeEnchant == 1)
        {
            if (Main.rand.Next(3) == 0)
            {
                int num9 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 171, 0f, 0f, 100);
                Main.dust[num9].noGravity = true;
                Main.dust[num9].fadeIn = 1.5f;
                Dust obj3 = Main.dust[num9];
                obj3.velocity *= 0.25f;
            }
        }
        else if (player.meleeEnchant == 2)
        {
            if (Main.rand.Next(2) == 0)
            {
                int num10 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 75, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 2.5f);
                Main.dust[num10].noGravity = true;
                Dust obj4 = Main.dust[num10];
                obj4.velocity *= 0.7f;
                Main.dust[num10].velocity.Y -= 0.5f;
            }
        }
        else if (player.meleeEnchant == 3)
        {
            if (Main.rand.Next(2) == 0)
            {
                int num11 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 6, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 2.5f);
                Main.dust[num11].noGravity = true;
                Dust obj5 = Main.dust[num11];
                obj5.velocity *= 0.7f;
                Main.dust[num11].velocity.Y -= 0.5f;
            }
        }
        else if (player.meleeEnchant == 4)
        {
            int num12 = 0;
            if (Main.rand.Next(2) == 0)
            {
                num12 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 57, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.1f);
                Main.dust[num12].noGravity = true;
                Main.dust[num12].velocity.X /= 2f;
                Main.dust[num12].velocity.Y /= 2f;
            }
        }
        else if (player.meleeEnchant == 5)
        {
            if (Main.rand.Next(2) == 0)
            {
                int num13 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 169, 0f, 0f, 100);
                Main.dust[num13].velocity.X += direction;
                Main.dust[num13].velocity.Y += 0.2f;
                Main.dust[num13].noGravity = true;
            }
        }
        else if (player.meleeEnchant == 6)
        {
            if (Main.rand.Next(2) == 0)
            {
                int num14 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 135, 0f, 0f, 100);
                Main.dust[num14].velocity.X += direction;
                Main.dust[num14].velocity.Y += 0.2f;
                Main.dust[num14].noGravity = true;
            }
        }
        else if (player.meleeEnchant == 7)
        {
            Vector2 vector = velocity;
            if (((Vector2)(ref vector)).Length() > 4f)
            {
                vector *= 4f / ((Vector2)(ref vector)).Length();
            }
            if (Main.rand.Next(20) == 0)
            {
                int num2 = Main.rand.Next(139, 143);
                int num3 = Dust.NewDust(boxPosition, boxWidth, boxHeight, num2, vector.X, vector.Y, 0, default(Color), 1.2f);
                Main.dust[num3].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num3].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num3].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                Main.dust[num3].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
                Main.dust[num3].scale *= 1f + (float)Main.rand.Next(-30, 31) * 0.01f;
            }
            if (Main.rand.Next(40) == 0)
            {
                int num4 = Main.rand.Next(276, 283);
                int num5 = Gore.NewGore(position, vector, num4);
                Main.gore[num5].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num5].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num5].scale *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                Main.gore[num5].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                Main.gore[num5].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
            }
        }
        else if (player.meleeEnchant == 8 && Main.rand.Next(4) == 0)
        {
            int num6 = Dust.NewDust(boxPosition, boxWidth, boxHeight, 46, 0f, 0f, 100);
            Main.dust[num6].noGravity = true;
            Main.dust[num6].fadeIn = 1.5f;
            Dust obj6 = Main.dust[num6];
            obj6.velocity *= 0.25f;
        }
    }
References Terraria.Entity.direction, Terraria.Main.dust, Terraria.Projectile.extraUpdates, Terraria.Projectile.friendly, Terraria.Player.frostBurn, Terraria.Main.gore, Terraria.Projectile.hostile, Terraria.ID.ProjectileID.Sets.IsAWhip, Terraria.Player.magmaStone, Terraria.Projectile.melee, Terraria.Player.meleeEnchant, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Projectile.noEnchantments, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.rand, Terraria.Projectile.ranged, Terraria.Projectile.type, and Terraria.Entity.velocity.
Referenced by Terraria.Projectile.UpdateEnchantmentVisuals().