TModLoader: Terraria.Projectile.AI_177_IceWhipSlicer
AI_177_IceWhipSlicer()
void Terraria.Projectile.AI_177_IceWhipSlicer () inline private
    {
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0377: Unknown result type (might be due to invalid IL or missing references)
        //IL_0381: Unknown result type (might be due to invalid IL or missing references)
        //IL_0386: Unknown result type (might be due to invalid IL or missing references)
        //IL_0339: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0344: Unknown result type (might be due to invalid IL or missing references)
        //IL_0349: Unknown result type (might be due to invalid IL or missing references)
        //IL_034e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0350: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_035b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0360: Unknown result type (might be due to invalid IL or missing references)
        //IL_0363: Unknown result type (might be due to invalid IL or missing references)
        //IL_0369: Unknown result type (might be due to invalid IL or missing references)
        //IL_036e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_0315: Unknown result type (might be due to invalid IL or missing references)
        //IL_0318: Unknown result type (might be due to invalid IL or missing references)
        //IL_031e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0323: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0601: Unknown result type (might be due to invalid IL or missing references)
        //IL_0606: Unknown result type (might be due to invalid IL or missing references)
        //IL_060a: Unknown result type (might be due to invalid IL or missing references)
        //IL_060f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0616: Unknown result type (might be due to invalid IL or missing references)
        //IL_061b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0620: Unknown result type (might be due to invalid IL or missing references)
        //IL_0625: Unknown result type (might be due to invalid IL or missing references)
        //IL_0627: Unknown result type (might be due to invalid IL or missing references)
        //IL_0407: Unknown result type (might be due to invalid IL or missing references)
        //IL_0434: Unknown result type (might be due to invalid IL or missing references)
        //IL_043a: Unknown result type (might be due to invalid IL or missing references)
        //IL_047f: Unknown result type (might be due to invalid IL or missing references)
        //IL_048e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0493: Unknown result type (might be due to invalid IL or missing references)
        //IL_0499: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_051c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0526: Unknown result type (might be due to invalid IL or missing references)
        //IL_0535: Unknown result type (might be due to invalid IL or missing references)
        //IL_053a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0540: Unknown result type (might be due to invalid IL or missing references)
        //IL_054a: Unknown result type (might be due to invalid IL or missing references)
        //IL_054f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0554: Unknown result type (might be due to invalid IL or missing references)
        //IL_055a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0560: Unknown result type (might be due to invalid IL or missing references)
        //IL_056a: Unknown result type (might be due to invalid IL or missing references)
        //IL_056f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0574: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        if (type == 917 && (!player.active || player.dead))
        {
            player.coolWhipBuff = false;
            Kill();
            return;
        }
        if (type == 917 && player.coolWhipBuff)
        {
            timeLeft = 2;
        }
        if (type == 969)
        {
            if (soundDelay == 0)
            {
                soundDelay = -1;
                localAI[1] = SoundEngine.PlayTrackedSound(in SoundID.DD2_BookStaffTwisterLoop, base.Center).ToFloat();
            }
            ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
            if (activeSound != null)
            {
                activeSound.Position = base.Center;
                activeSound.Volume = 1f - Math.Max(ai[1] - 555f, 0f) / 15f;
            }
            else
            {
                localAI[1] = SlotId.Invalid.ToFloat();
            }
            ai[1] += 1f;
            if (ai[1] > 560f)
            {
                alpha = (int)MathHelper.Lerp(0f, 250f, (ai[1] - 560f) / 10f);
            }
            if (ai[1] >= 570f)
            {
                Kill();
            }
            float num = 555f;
            for (int i = 0; i < 1000; i++)
            {
                if (i != whoAmI && Main.projectile[i].active && Main.projectile[i].owner == owner && Main.projectile[i].type == type && timeLeft > Main.projectile[i].timeLeft && Main.projectile[i].ai[1] < num)
                {
                    Main.projectile[i].ai[1] = num;
                    Main.projectile[i].netUpdate = true;
                }
            }
        }
        int num2 = (int)ai[0] - 1;
        if (num2 != -1 && (!Main.npc[num2].CanBeChasedBy(this) || localNPCImmunity[num2] > 0))
        {
            ai[0] = 0f;
            num2 = -1;
        }
        if (num2 == -1)
        {
            bool checkCanHit = false;
            if (type == 969)
            {
                checkCanHit = true;
            }
            NPC nPC = FindTargetWithinRange(400f, checkCanHit);
            if (nPC != null)
            {
                num2 = nPC.whoAmI;
                ai[0] = num2 + 1;
                netUpdate = true;
            }
        }
        float num3 = 18f;
        float amount = 0.1f;
        float num4 = 0f;
        if (type == 969)
        {
            num3 = 8f;
            amount = 0.075f;
            num4 = 25f;
        }
        if (num2 != -1)
        {
            NPC nPC2 = Main.npc[num2];
            float num5 = Distance(nPC2.Center);
            if (num3 > num5)
            {
                num3 = num5;
            }
            Vector2 vector = DirectionTo(nPC2.Center);
            if (!vector.HasNaNs() && num5 >= num4)
            {
                velocity = Vector2.Lerp(velocity, vector * num3, amount);
            }
        }
        else if (type == 969)
        {
            Vector2 vector2 = DirectionTo(base.Center + velocity);
            if (!vector2.HasNaNs())
            {
                velocity = Vector2.Lerp(velocity, vector2 * num3, amount);
            }
        }
        else
        {
            velocity *= 0.92f;
        }
        if (type == 969)
        {
            rotation = velocity.X * 0.0125f;
            if (++frameCounter > 4)
            {
                frameCounter = 0;
                frame++;
                if (frame >= Main.projFrames[type])
                {
                    frame = 0;
                }
            }
            if (timeLeft % 3 == 0)
            {
                int num6 = Dust.NewDust(position, width, height, 16, velocity.X, velocity.Y, 120, default(Color), 0.5f);
                Main.dust[num6].noGravity = true;
                Main.dust[num6].fadeIn = 0.9f;
                Main.dust[num6].velocity = Main.rand.NextVector2Circular(2f, 2f) + new Vector2(0f, -2f) + velocity * 0.75f;
                for (int j = 0; j < 2; j++)
                {
                    Dust dust = Dust.NewDustDirect(position, width, height, 16, velocity.X, velocity.Y, 60, default(Color), 0.5f);
                    dust.noGravity = true;
                    dust.fadeIn = 0.7f;
                    dust.velocity = Main.rand.NextVector2Circular(2f, 2f) * 0.2f + new Vector2(0f, -0.4f) + velocity * 1.5f;
                    dust.position -= velocity * 3f;
                }
            }
        }
        else
        {
            rotation += 0.020943953f + Math.Abs(velocity.X) * 0.2f;
            if (Main.rand.Next(3) == 0)
            {
                Dust dust2 = Dust.NewDustDirect(base.Center, 0, 0, 43, velocity.X, velocity.Y, 254, Color.White, 0.5f);
                Vector2 vector3 = Main.rand.NextVector2Circular(1f, 1f);
                dust2.position = base.Center + vector3 * 10f;
                dust2.velocity = vector3;
            }
        }
    }
References Terraria.Entity.active, Terraria.Projectile.ai, Terraria.NPC.CanBeChasedBy(), Terraria.Player.coolWhipBuff, Terraria.ID.SoundID.DD2_BookStaffTwisterLoop, Terraria.Player.dead, Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.Projectile.netUpdate, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.npc, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Main.projectile, Terraria.Main.projFrames, Terraria.Main.rand, Terraria.Projectile.timeLeft, Terraria.Projectile.type, and Terraria.Dust.velocity.