TModLoader: Terraria.Projectile.AI_009_MagicMissiles
AI_009_MagicMissiles()
void Terraria.Projectile.AI_009_MagicMissiles () inline private
Definition at line 44798 of file Projectile.cs.
    {
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_025b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_026c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0271: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_0246: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0402: Unknown result type (might be due to invalid IL or missing references)
        //IL_0407: Unknown result type (might be due to invalid IL or missing references)
        //IL_0409: Unknown result type (might be due to invalid IL or missing references)
        //IL_040b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0410: Unknown result type (might be due to invalid IL or missing references)
        //IL_0427: Unknown result type (might be due to invalid IL or missing references)
        //IL_042c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0347: Unknown result type (might be due to invalid IL or missing references)
        //IL_0354: Unknown result type (might be due to invalid IL or missing references)
        //IL_058a: Unknown result type (might be due to invalid IL or missing references)
        //IL_058f: Unknown result type (might be due to invalid IL or missing references)
        //IL_048e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0442: Unknown result type (might be due to invalid IL or missing references)
        //IL_0448: Unknown result type (might be due to invalid IL or missing references)
        //IL_044d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0452: Unknown result type (might be due to invalid IL or missing references)
        //IL_0462: Unknown result type (might be due to invalid IL or missing references)
        //IL_0468: Unknown result type (might be due to invalid IL or missing references)
        //IL_046a: Unknown result type (might be due to invalid IL or missing references)
        //IL_046f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0474: Unknown result type (might be due to invalid IL or missing references)
        //IL_047e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0483: Unknown result type (might be due to invalid IL or missing references)
        //IL_0488: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0542: Unknown result type (might be due to invalid IL or missing references)
        //IL_0548: Unknown result type (might be due to invalid IL or missing references)
        //IL_054d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0552: Unknown result type (might be due to invalid IL or missing references)
        //IL_0559: Unknown result type (might be due to invalid IL or missing references)
        //IL_0563: Unknown result type (might be due to invalid IL or missing references)
        //IL_0568: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0601: Unknown result type (might be due to invalid IL or missing references)
        //IL_0606: Unknown result type (might be due to invalid IL or missing references)
        //IL_0865: Unknown result type (might be due to invalid IL or missing references)
        //IL_086a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0871: Unknown result type (might be due to invalid IL or missing references)
        //IL_0876: Unknown result type (might be due to invalid IL or missing references)
        //IL_0889: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0904: Unknown result type (might be due to invalid IL or missing references)
        //IL_090a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0914: Unknown result type (might be due to invalid IL or missing references)
        //IL_0919: Unknown result type (might be due to invalid IL or missing references)
        //IL_091e: Unknown result type (might be due to invalid IL or missing references)
        //IL_068a: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0765: Unknown result type (might be due to invalid IL or missing references)
        //IL_0779: Unknown result type (might be due to invalid IL or missing references)
        //IL_077e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0783: Unknown result type (might be due to invalid IL or missing references)
        //IL_0667: Unknown result type (might be due to invalid IL or missing references)
        //IL_0932: Unknown result type (might be due to invalid IL or missing references)
        //IL_095e: Unknown result type (might be due to invalid IL or missing references)
        //IL_096c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0980: Unknown result type (might be due to invalid IL or missing references)
        //IL_0985: Unknown result type (might be due to invalid IL or missing references)
        //IL_098a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0990: Unknown result type (might be due to invalid IL or missing references)
        //IL_0996: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07db: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0804: Unknown result type (might be due to invalid IL or missing references)
        //IL_0818: Unknown result type (might be due to invalid IL or missing references)
        //IL_081d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0822: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a06: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a46: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a50: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a71: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a76: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a87: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a91: Unknown result type (might be due to invalid IL or missing references)
        if (type == 491)
        {
            AI_009_MagicMissiles_Old();
            return;
        }
        int num = 32;
        Player player = Main.player[owner];
        int num4 = Main.maxTilesY * 16;
        int num5 = 0;
        if (ai[0] >= 0f)
        {
            num5 = (int)(ai[1] / (float)num4);
        }
        bool flag = ai[0] == -1f || ai[0] == -2f;
        if (type == 34)
        {
            if (frameCounter++ >= 4)
            {
                frameCounter = 0;
                if (++frame >= Main.projFrames[type])
                {
                    frame = 0;
                }
            }
            if (penetrate == 1 && ai[0] >= 0f && num5 == 0)
            {
                ai[1] += num4;
                num5 = 1;
                netUpdate = true;
            }
            if (penetrate == 1 && ai[0] == -1f)
            {
                ai[0] = -2f;
                netUpdate = true;
            }
            if (num5 > 0 || ai[0] == -2f)
            {
                localAI[0] += 1f;
            }
        }
        if (owner == Main.myPlayer)
        {
            if (ai[0] >= 0f)
            {
                if (player.channel && player.HeldItem.shoot == type)
                {
                    Vector2 pointPoisition = Main.MouseWorld;
                    player.LimitPointToPlayerReachableArea(ref pointPoisition);
                    if (ai[0] != pointPoisition.X || ai[1] != pointPoisition.Y)
                    {
                        netUpdate = true;
                        ai[0] = pointPoisition.X;
                        ai[1] = pointPoisition.Y + (float)(num4 * num5);
                    }
                }
                else
                {
                    netUpdate = true;
                    ai[0] = -1f;
                    ai[1] = -1f;
                    int num6 = FindTargetWithLineOfSight();
                    if (num6 != -1)
                    {
                        ai[1] = num6;
                    }
                    else if (((Vector2)(ref velocity)).Length() < 2f)
                    {
                        velocity = DirectionFrom(player.Center) * (float)num;
                    }
                    else
                    {
                        velocity = velocity.SafeNormalize(Vector2.Zero) * (float)num;
                    }
                }
            }
            if (flag && ai[1] == -1f)
            {
                int num7 = FindTargetWithLineOfSight();
                if (num7 != -1)
                {
                    ai[1] = num7;
                    netUpdate = true;
                }
            }
        }
        Vector2? vector = null;
        float amount = 1f;
        if (ai[0] > 0f && ai[1] > 0f)
        {
            vector = new Vector2(ai[0], ai[1] % (float)num4);
        }
        if (flag && ai[1] >= 0f)
        {
            int num8 = (int)ai[1];
            if (Main.npc.IndexInRange(num8))
            {
                NPC nPC = Main.npc[num8];
                if (nPC.CanBeChasedBy(this))
                {
                    vector = nPC.Center;
                    float t = Distance(vector.Value);
                    float num9 = Utils.GetLerpValue(0f, 100f, t, clamped: true) * Utils.GetLerpValue(600f, 400f, t, clamped: true);
                    amount = MathHelper.Lerp(0f, 0.2f, Utils.GetLerpValue(200f, 20f, 1f - num9, clamped: true));
                }
                else
                {
                    ai[1] = -1f;
                    netUpdate = true;
                }
            }
        }
        bool flag2 = false;
        if (flag)
        {
            flag2 = true;
        }
        if (vector.HasValue)
        {
            Vector2 value = vector.Value;
            if (Distance(value) >= 64f)
            {
                flag2 = true;
                Vector2 v = value - base.Center;
                Vector2 val = v.SafeNormalize(Vector2.Zero);
                float num10 = Math.Min(num, ((Vector2)(ref v)).Length());
                Vector2 value2 = val * num10;
                if (((Vector2)(ref velocity)).Length() < 4f)
                {
                    velocity += velocity.SafeNormalize(Vector2.Zero).RotatedBy(0.7853981852531433).SafeNormalize(Vector2.Zero) * 4f;
                }
                if (velocity.HasNaNs())
                {
                    Kill();
                }
                velocity = Vector2.Lerp(velocity, value2, amount);
            }
            else
            {
                velocity *= 0.3f;
                velocity += (value - base.Center) * 0.3f;
                flag2 = ((Vector2)(ref velocity)).Length() >= 2f;
            }
            if (timeLeft < 60)
            {
                timeLeft = 60;
            }
        }
        if (flag && ai[1] < 0f)
        {
            if (((Vector2)(ref velocity)).Length() != (float)num)
            {
                velocity = velocity.MoveTowards(velocity.SafeNormalize(Vector2.UnitY) * (float)num, 4f);
            }
            if (timeLeft > 300)
            {
                timeLeft = 300;
            }
        }
        if (flag2 && velocity != Vector2.Zero)
        {
            rotation = rotation.AngleTowards(velocity.ToRotation(), (float)Math.PI / 4f);
        }
        else
        {
            rotation = rotation.AngleLerp(0f, 0.2f);
        }
        bool flag3 = ((Vector2)(ref velocity)).Length() > 0.1f && Vector2.Dot(oldVelocity.SafeNormalize(Vector2.Zero), velocity.SafeNormalize(Vector2.Zero)) < 0.2f;
        if (type == 16)
        {
            if (soundDelay == 0 && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > 2f)
            {
                soundDelay = 10;
                SoundEngine.PlaySound(in SoundID.Item9, position);
            }
            if (Main.rand.Next(9) == 0)
            {
                int num11 = Dust.NewDust(position, width, height, 15, 0f, 0f, 100, default(Color), 2f);
                Dust obj = Main.dust[num11];
                obj.velocity *= 0.3f;
                Main.dust[num11].position.X = position.X + (float)(width / 2) + 4f + (float)Main.rand.Next(-4, 5);
                Main.dust[num11].position.Y = position.Y + (float)(height / 2) + (float)Main.rand.Next(-4, 5);
                Main.dust[num11].noGravity = true;
                Dust obj2 = Main.dust[num11];
                obj2.velocity += Main.rand.NextVector2Circular(2f, 2f);
            }
            if (flag3)
            {
                int num2 = Main.rand.Next(2, 5);
                for (int i = 0; i < num2; i++)
                {
                    Dust dust5 = Dust.NewDustDirect(position, width, height, 15, 0f, 0f, 100, default(Color), 1.5f);
                    dust5.velocity *= 0.3f;
                    dust5.position = base.Center;
                    dust5.noGravity = true;
                    dust5.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                    dust5.fadeIn = 2.2f;
                }
            }
        }
        if (type != 34)
        {
            return;
        }
        float lerpValue = Utils.GetLerpValue(0f, 10f, localAI[0], clamped: true);
        Color newColor = Color.Lerp(Color.Transparent, Color.Crimson, lerpValue);
        if (Main.rand.Next(6) == 0)
        {
            Dust dust6 = Dust.NewDustDirect(base.Center, 0, 0, 6, velocity.X * 0.2f, velocity.Y * 0.2f, 100, newColor, 3.5f);
            dust6.noGravity = true;
            dust6.velocity *= 1.4f;
            dust6.velocity += Main.rand.NextVector2Circular(1f, 1f);
            dust6.velocity += velocity * 0.15f;
        }
        if (Main.rand.Next(12) == 0)
        {
            Dust dust7 = Dust.NewDustDirect(base.Center, 0, 0, 6, velocity.X * 0.2f, velocity.Y * 0.2f, 100, newColor, 1.5f);
            dust7.velocity += Main.rand.NextVector2Circular(1f, 1f);
            dust7.velocity += velocity * 0.15f;
        }
        if (flag3)
        {
            int num3 = Main.rand.Next(2, 5 + (int)(lerpValue * 4f));
            for (int j = 0; j < num3; j++)
            {
                Dust dust4 = Dust.NewDustDirect(position, width, height, 6, 0f, 0f, 100, newColor, 1.5f);
                dust4.velocity *= 0.3f;
                dust4.position = base.Center;
                dust4.noGravity = true;
                dust4.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                dust4.fadeIn = 2.2f;
                dust4.position += (dust4.position - base.Center) * lerpValue * 10f;
            }
        }
    }
References Terraria.Entity.Center, Terraria.Player.channel, Terraria.Main.dust, Terraria.Utils.GetLerpValue(), Terraria.Player.HeldItem, Terraria.ID.SoundID.Item9, Terraria.Player.LimitPointToPlayerReachableArea(), Terraria.Main.MouseWorld, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Main.npc, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.projFrames, Terraria.Main.rand, and Terraria.Item.shoot.