TModLoader: Terraria.Projectile.AI_138_ExplosiveTrap
AI_138_ExplosiveTrap()
void Terraria.Projectile.AI_138_ExplosiveTrap () inline private
    {
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        spriteDirection = (direction = 1);
        int num = 694;
        int num2 = 48;
        int explosiveTrapCooldown = GetExplosiveTrapCooldown(Main.player[owner]);
        switch (type)
        {
        case 692:
            num = 695;
            break;
        case 693:
            num = 696;
            break;
        }
        Lighting.AddLight(base.Center, 0.6f, 0.5f, 0.3f);
        if (++frameCounter >= 12)
        {
            frameCounter = 0;
            if (++frame >= Main.projFrames[type])
            {
                frame = 0;
            }
        }
        if (localAI[0] > 0f)
        {
            localAI[0] -= 1f;
        }
        if (localAI[0] <= 0f && owner == Main.myPlayer)
        {
            localAI[0] = 3f;
            bool flag = false;
            Rectangle rectangle = Utils.CenteredRectangle(base.Center + new Vector2(0f, (float)(-num2)), new Vector2((float)(num2 * 3)));
            for (int i = 0; i < 200; i++)
            {
                NPC nPC = Main.npc[i];
                if (nPC.CanBeChasedBy(this) && ((Rectangle)(ref rectangle)).Intersects(nPC.Hitbox))
                {
                    flag = true;
                    break;
                }
            }
            if (flag)
            {
                SoundEngine.PlayTrackedSound(in SoundID.DD2_ExplosiveTrapExplode);
                localAI[0] = explosiveTrapCooldown;
                NewProjectile(GetProjectileSource_FromThis(), base.Center + new Vector2(0f, (float)(-num2)), Vector2.Zero, num, damage, knockBack, owner);
            }
        }
        tileCollide = true;
        velocity.Y += 0.2f;
    }
References Terraria.Lighting.AddLight(), Terraria.Utils.CenteredRectangle(), Terraria.ID.SoundID.DD2_ExplosiveTrapExplode, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Main.player, Terraria.Audio.SoundEngine.PlayTrackedSound(), and Terraria.Main.projFrames.