TModLoader: Terraria.Projectile.AI_190_NightsEdge
AI_190_NightsEdge()
void Terraria.Projectile.AI_190_NightsEdge () inline private
Definition at line 43150 of file Projectile.cs.
    {
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_0327: Unknown result type (might be due to invalid IL or missing references)
        //IL_032e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0338: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_0348: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0360: Unknown result type (might be due to invalid IL or missing references)
        //IL_0365: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04de: Unknown result type (might be due to invalid IL or missing references)
        //IL_0383: Unknown result type (might be due to invalid IL or missing references)
        //IL_038a: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03da: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_022e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0238: Unknown result type (might be due to invalid IL or missing references)
        //IL_0243: Unknown result type (might be due to invalid IL or missing references)
        //IL_0248: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_059b: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0500: Unknown result type (might be due to invalid IL or missing references)
        //IL_0529: Unknown result type (might be due to invalid IL or missing references)
        //IL_052e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0534: Unknown result type (might be due to invalid IL or missing references)
        //IL_053b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0548: Unknown result type (might be due to invalid IL or missing references)
        //IL_054e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0438: Unknown result type (might be due to invalid IL or missing references)
        //IL_043c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0443: Unknown result type (might be due to invalid IL or missing references)
        //IL_044f: Unknown result type (might be due to invalid IL or missing references)
        //IL_045a: Unknown result type (might be due to invalid IL or missing references)
        //IL_025c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0271: Unknown result type (might be due to invalid IL or missing references)
        //IL_0277: Unknown result type (might be due to invalid IL or missing references)
        //IL_070f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0716: Unknown result type (might be due to invalid IL or missing references)
        //IL_0720: Unknown result type (might be due to invalid IL or missing references)
        //IL_072b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0730: Unknown result type (might be due to invalid IL or missing references)
        //IL_0735: Unknown result type (might be due to invalid IL or missing references)
        //IL_0748: Unknown result type (might be due to invalid IL or missing references)
        //IL_074d: Unknown result type (might be due to invalid IL or missing references)
        //IL_076d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0774: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0621: Unknown result type (might be due to invalid IL or missing references)
        //IL_0626: Unknown result type (might be due to invalid IL or missing references)
        //IL_0630: Unknown result type (might be due to invalid IL or missing references)
        //IL_0637: Unknown result type (might be due to invalid IL or missing references)
        //IL_0643: Unknown result type (might be due to invalid IL or missing references)
        //IL_0648: Unknown result type (might be due to invalid IL or missing references)
        //IL_065d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0799: Unknown result type (might be due to invalid IL or missing references)
        //IL_079b: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0819: Unknown result type (might be due to invalid IL or missing references)
        //IL_081e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0828: Unknown result type (might be due to invalid IL or missing references)
        //IL_082f: Unknown result type (might be due to invalid IL or missing references)
        //IL_083b: Unknown result type (might be due to invalid IL or missing references)
        //IL_083d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0852: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0898: Unknown result type (might be due to invalid IL or missing references)
        //IL_089a: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_08dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0900: Unknown result type (might be due to invalid IL or missing references)
        //IL_0907: Unknown result type (might be due to invalid IL or missing references)
        //IL_0915: Unknown result type (might be due to invalid IL or missing references)
        //IL_091b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0923: Unknown result type (might be due to invalid IL or missing references)
        //IL_093e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0944: Unknown result type (might be due to invalid IL or missing references)
        //IL_094e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0953: Unknown result type (might be due to invalid IL or missing references)
        //IL_0958: Unknown result type (might be due to invalid IL or missing references)
        //IL_0960: Unknown result type (might be due to invalid IL or missing references)
        //IL_0971: Unknown result type (might be due to invalid IL or missing references)
        //IL_0976: Unknown result type (might be due to invalid IL or missing references)
        //IL_097b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0983: Unknown result type (might be due to invalid IL or missing references)
        //IL_098a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0994: Unknown result type (might be due to invalid IL or missing references)
        //IL_0999: Unknown result type (might be due to invalid IL or missing references)
        //IL_099e: Unknown result type (might be due to invalid IL or missing references)
        if (localAI[0] == 0f && type == 984)
        {
            SoundEffectInstance soundEffectInstance = SoundEngine.PlaySound((SoundStyle?)SoundID.Item60, (Vector2?)position);
            if (soundEffectInstance != null)
            {
                soundEffectInstance.Volume *= 0.65f;
            }
        }
        localAI[0] += 1f;
        Player player = Main.player[owner];
        float num = localAI[0] / ai[1];
        float num4 = ai[0];
        float num5 = velocity.ToRotation();
        float num6 = (float)Math.PI * num4 * num + num5 + num4 * (float)Math.PI + player.fullRotation;
        rotation = num6;
        float num7 = 0.2f;
        float num8 = 1f;
        switch (type)
        {
        case 982:
            num7 = 0.6f;
            break;
        case 997:
            num7 = 0.6f;
            break;
        case 983:
            num7 = 1f;
            num8 = 1.2f;
            break;
        case 984:
            num7 = 0.6f;
            break;
        }
        base.Center = player.RotatedRelativePoint(player.MountedCenter) - velocity;
        scale = num8 + num * num7;
        if (type == 972)
        {
            if (Math.Abs(num4) < 0.2f)
            {
                rotation += (float)Math.PI * 4f * num4 * 10f * num;
                float num9 = Utils.Remap(localAI[0], 10f, ai[1] - 5f, 0f, 1f);
                position += velocity.SafeNormalize(Vector2.Zero) * (45f * num9);
                scale += num9 * 0.4f;
            }
            if (Main.rand.Next(2) == 0)
            {
                float f = rotation + Main.rand.NextFloatDirection() * ((float)Math.PI / 2f) * 0.7f;
                Vector2 vector = base.Center + f.ToRotationVector2() * 84f * scale;
                if (Main.rand.Next(5) == 0)
                {
                    Dust dust7 = Dust.NewDustPerfect(vector, 14, null, 150, default(Color), 1.4f);
                    dust7.noLight = (dust7.noLightEmittence = true);
                }
                if (Main.rand.Next(2) == 0)
                {
                    Dust.NewDustPerfect(vector, 27, (Vector2?)new Vector2(player.velocity.X * 0.2f + (float)(player.direction * 3), player.velocity.Y * 0.2f), 100, default(Color), 1.4f).noGravity = true;
                }
            }
        }
        if (type == 982)
        {
            float num10 = rotation + Main.rand.NextFloatDirection() * ((float)Math.PI / 2f) * 0.7f;
            Vector2 vector2 = base.Center + num10.ToRotationVector2() * 84f * scale;
            Vector2 vector3 = (num10 + ai[0] * ((float)Math.PI / 2f)).ToRotationVector2();
            if (Main.rand.NextFloat() * 2f < Opacity)
            {
                Dust dust8 = Dust.NewDustPerfect(base.Center + num10.ToRotationVector2() * (Main.rand.NextFloat() * 80f * scale + 20f * scale), 278, vector3 * 1f, 100, Color.Lerp(Color.Gold, Color.White, Main.rand.NextFloat() * 0.3f), 0.4f);
                dust8.fadeIn = 0.4f + Main.rand.NextFloat() * 0.15f;
                dust8.noGravity = true;
            }
            if (Main.rand.NextFloat() * 1.5f < Opacity)
            {
                Dust.NewDustPerfect(vector2, 43, vector3 * 1f, 100, Color.White * Opacity, 1.2f * Opacity);
            }
        }
        if (type == 997)
        {
            float num11 = rotation + Main.rand.NextFloatDirection() * ((float)Math.PI / 2f) * 0.7f;
            _ = base.Center + num11.ToRotationVector2() * 84f * scale;
            Vector2 vector4 = (num11 + ai[0] * ((float)Math.PI / 2f)).ToRotationVector2();
            if (Main.rand.NextFloat() * 2f < Opacity)
            {
                Dust dust9 = Dust.NewDustPerfect(base.Center + num11.ToRotationVector2() * (Main.rand.NextFloat() * 80f * scale + 20f * scale), 6, vector4 * 4f, 0, default(Color), 0.4f);
                dust9.noGravity = true;
                dust9.scale = 1.4f;
            }
        }
        if (type == 983)
        {
            float num2 = rotation + Main.rand.NextFloatDirection() * ((float)Math.PI / 2f) * 0.7f;
            Vector2 vector5 = base.Center + num2.ToRotationVector2() * 84f * scale;
            Vector2 vector6 = (num2 + ai[0] * ((float)Math.PI / 2f)).ToRotationVector2();
            if (Main.rand.NextFloat() < Opacity)
            {
                Dust dust10 = Dust.NewDustPerfect(base.Center + num2.ToRotationVector2() * (Main.rand.NextFloat() * 80f * scale + 20f * scale), 278, vector6 * 1f, 100, Color.Lerp(Color.HotPink, Color.White, Main.rand.NextFloat() * 0.3f), 0.4f);
                dust10.fadeIn = 0.4f + Main.rand.NextFloat() * 0.15f;
                dust10.noGravity = true;
            }
            if (Main.rand.NextFloat() * 1.5f < Opacity)
            {
                Dust.NewDustPerfect(vector5, 43, vector6 * 1f, 100, Color.White * Opacity, 1.2f * Opacity);
            }
        }
        if (type == 984)
        {
            float num3 = rotation + Main.rand.NextFloatDirection() * ((float)Math.PI / 2f) * 0.7f;
            Vector2 vector7 = base.Center + num3.ToRotationVector2() * 85f * scale;
            Vector2 vector8 = (num3 + ai[0] * ((float)Math.PI / 2f)).ToRotationVector2();
            Color value = default(Color);
            ((Color)(ref value))._002Ector(64, 220, 96);
            Color value2 = default(Color);
            ((Color)(ref value2))._002Ector(15, 84, 125);
            Lighting.AddLight(base.Center, ((Color)(ref value2)).ToVector3());
            if (Main.rand.NextFloat() * 2f < Opacity)
            {
                Color value3 = Color.Lerp(value2, value, Utils.Remap(num, 0f, 0.6f, 0f, 1f));
                value3 = Color.Lerp(value3, Color.White, Utils.Remap(num, 0.6f, 0.8f, 0f, 0.5f));
                Dust dust11 = Dust.NewDustPerfect(base.Center + num3.ToRotationVector2() * (Main.rand.NextFloat() * 80f * scale + 20f * scale), 278, vector8 * 1f, 100, Color.Lerp(value3, Color.White, Main.rand.NextFloat() * 0.3f), 0.4f);
                dust11.fadeIn = 0.4f + Main.rand.NextFloat() * 0.15f;
                dust11.noGravity = true;
            }
            if (Main.rand.NextFloat() < Opacity)
            {
                Color.Lerp(Color.Lerp(Color.Lerp(value2, value, Utils.Remap(num, 0f, 0.6f, 0f, 1f)), Color.White, Utils.Remap(num, 0.6f, 0.8f, 0f, 0.5f)), Color.White, Main.rand.NextFloat() * 0.3f);
                Dust dust6 = Dust.NewDustPerfect(vector7, 107, vector8 * 3f, 100, default(Color) * Opacity, 0.8f * Opacity);
                dust6.velocity += player.velocity * 0.1f;
                dust6.velocity += new Vector2((float)player.direction, 0f);
                dust6.position -= dust6.velocity * 6f;
            }
        }
        scale *= ai[2];
        if (localAI[0] >= ai[1])
        {
            Kill();
        }
    }
References Terraria.Lighting.AddLight(), Terraria.Entity.direction, Terraria.Player.fullRotation, Terraria.ID.SoundID.Item60, Terraria.Player.MountedCenter, Terraria.Dust.NewDustPerfect(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Utils.Remap(), Terraria.Player.RotatedRelativePoint(), and Terraria.Entity.velocity.