TModLoader: Terraria.Projectile.AI_015_HandleMovementCollision
AI_015_HandleMovementCollision()
void Terraria.Projectile.AI_015_HandleMovementCollision (ref Vector2 wetVelocity, ref Vector2 lastVelocity) inline private
Definition at line 45523 of file Projectile.cs.
    {
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_0137: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_023b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0240: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        int num = 10;
        int num2 = 0;
        Vector2 vector = velocity;
        float num3 = 0.2f;
        if (ai[0] == 1f || ai[0] == 5f)
        {
            num3 = 0.4f;
        }
        if (ai[0] == 6f)
        {
            num3 = 0f;
        }
        if (lastVelocity.X != velocity.X)
        {
            if (Math.Abs(lastVelocity.X) > 4f)
            {
                num2 = 1;
            }
            velocity.X = (0f - lastVelocity.X) * num3;
            localAI[0] += 1f;
        }
        if (lastVelocity.Y != velocity.Y)
        {
            if (Math.Abs(lastVelocity.Y) > 4f)
            {
                num2 = 1;
            }
            velocity.Y = (0f - lastVelocity.Y) * num3;
            localAI[0] += 1f;
        }
        if (ai[0] == 1f)
        {
            ai[0] = 5f;
            localNPCHitCooldown = num;
            netUpdate = true;
            Point scanAreaStart = base.TopLeft.ToTileCoordinates();
            Point scanAreaEnd = base.BottomRight.ToTileCoordinates();
            num2 = 2;
            CreateImpactExplosion(2, base.Center, ref scanAreaStart, ref scanAreaEnd, width, out var causedShockwaves);
            CreateImpactExplosion2_FlailTileCollision(base.Center, causedShockwaves, vector);
            position -= vector;
        }
        if (num2 > 0)
        {
            netUpdate = true;
            for (int i = 0; i < num2; i++)
            {
                Collision.HitTiles(position, vector, width, height);
            }
            SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
        }
        if (ai[0] != 3f && ai[0] != 0f && ai[0] != 5f && ai[0] != 6f && localAI[0] >= 10f)
        {
            ai[0] = 4f;
            netUpdate = true;
        }
        if (wet)
        {
            wetVelocity = velocity;
        }
    }
References Terraria.Collision.HitTiles(), and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.Projectile.HandleMovement().