TModLoader: Terraria.Projectile.AI_192_JuminoAnimation
AI_192_JuminoAnimation()
void Terraria.Projectile.AI_192_JuminoAnimation () inline private
Definition at line 42601 of file Projectile.cs.
    {
        //IL_016f: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0626: Unknown result type (might be due to invalid IL or missing references)
        //IL_063e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0643: Unknown result type (might be due to invalid IL or missing references)
        //IL_0652: Unknown result type (might be due to invalid IL or missing references)
        //IL_0659: Unknown result type (might be due to invalid IL or missing references)
        //IL_065e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0663: Unknown result type (might be due to invalid IL or missing references)
        //IL_027a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        //IL_028e: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0312: Unknown result type (might be due to invalid IL or missing references)
        //IL_0317: Unknown result type (might be due to invalid IL or missing references)
        //IL_0888: Unknown result type (might be due to invalid IL or missing references)
        //IL_0897: Unknown result type (might be due to invalid IL or missing references)
        //IL_089c: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_066d: Unknown result type (might be due to invalid IL or missing references)
        //IL_066f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0674: Unknown result type (might be due to invalid IL or missing references)
        //IL_067b: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0464: Unknown result type (might be due to invalid IL or missing references)
        //IL_046e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0473: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04de: Unknown result type (might be due to invalid IL or missing references)
        //IL_07de: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0801: Unknown result type (might be due to invalid IL or missing references)
        //IL_0806: Unknown result type (might be due to invalid IL or missing references)
        //IL_080b: Unknown result type (might be due to invalid IL or missing references)
        //IL_080d: Unknown result type (might be due to invalid IL or missing references)
        //IL_080f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0814: Unknown result type (might be due to invalid IL or missing references)
        //IL_081b: Unknown result type (might be due to invalid IL or missing references)
        //IL_083f: Unknown result type (might be due to invalid IL or missing references)
        //IL_086a: Unknown result type (might be due to invalid IL or missing references)
        //IL_086f: Unknown result type (might be due to invalid IL or missing references)
        //IL_033d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0347: Unknown result type (might be due to invalid IL or missing references)
        //IL_034c: Unknown result type (might be due to invalid IL or missing references)
        //IL_038e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0394: Unknown result type (might be due to invalid IL or missing references)
        //IL_0396: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0709: Unknown result type (might be due to invalid IL or missing references)
        //IL_0718: Unknown result type (might be due to invalid IL or missing references)
        //IL_071d: Unknown result type (might be due to invalid IL or missing references)
        //IL_072c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0731: Unknown result type (might be due to invalid IL or missing references)
        //IL_0736: Unknown result type (might be due to invalid IL or missing references)
        //IL_0738: Unknown result type (might be due to invalid IL or missing references)
        //IL_073a: Unknown result type (might be due to invalid IL or missing references)
        //IL_073f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0746: Unknown result type (might be due to invalid IL or missing references)
        //IL_076a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0795: Unknown result type (might be due to invalid IL or missing references)
        //IL_079a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0536: Unknown result type (might be due to invalid IL or missing references)
        //IL_0540: Unknown result type (might be due to invalid IL or missing references)
        //IL_0545: Unknown result type (might be due to invalid IL or missing references)
        //IL_0575: Unknown result type (might be due to invalid IL or missing references)
        //IL_057b: Unknown result type (might be due to invalid IL or missing references)
        //IL_057d: Unknown result type (might be due to invalid IL or missing references)
        //IL_059e: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b6: Unknown result type (might be due to invalid IL or missing references)
        float num = 120f;
        float num8 = 420f + num;
        float num9 = num8 - 150f;
        if (Opacity > 0f && Opacity < 1f)
        {
            for (int i = 0; i < 1; i++)
            {
                Rectangle r = Utils.CenteredRectangle(base.Center + new Vector2(0f, 20f), new Vector2(32f, 32f));
                Dust dust = Dust.NewDustDirect(r.TopLeft(), r.Width, r.Height, 263, 0f, 0f, 100, new Color(80, 200, 255), 0.6f);
                dust.noGravity = true;
                dust.fadeIn = 0.9f;
                dust.velocity = new Vector2(0f, -0.3f);
            }
        }
        int num10 = 20;
        int num11 = 4;
        if (frame == 1)
        {
            num11 = 60;
        }
        AI_192_GetJuminoFall(this, out var timeSinceFall, out var fall);
        if (timeSinceFall > 0f)
        {
            if (fall < 20f)
            {
                frame = 0;
            }
            else if (++frameCounter >= num11)
            {
                frameCounter = 0;
                if (++frame >= num10)
                {
                    frame = num10 - 1;
                }
            }
        }
        else
        {
            frame = 1;
        }
        float num12 = Main.player[owner].Center.X - base.Center.X;
        direction = (spriteDirection = ((num12 >= 0f) ? 1 : (-1)));
        int num13 = 30;
        float num14 = num8 + (float)(num10 * num11) + (float)num13;
        Opacity = Utils.Remap(ai[0], num9 + 0f, num9 + 20f, 0f, 1f) * Utils.Remap(ai[0], num14 - 5f, num14, 1f, 0.5f);
        ai[0] += 1f;
        if (ai[0] <= 130f && ai[0] >= 60f)
        {
            float num15 = Utils.Remap(ai[0], 60f, 130f, 0f, 1f);
            if (Main.rand.NextFloat() < num15 * 0.5f)
            {
                Rectangle r2 = Utils.CenteredRectangle(base.Center + new Vector2(0f, 0f), new Vector2(70f, 70f) * num15);
                Dust dust2 = Dust.NewDustDirect(r2.TopLeft(), r2.Width, r2.Height, 263, 0f, 0f, 100, new Color(80, 200, 255), 0.6f);
                dust2.noGravity = true;
                dust2.fadeIn = 0.9f;
                dust2.velocity = Main.rand.NextVector2Circular(2f, 2f);
            }
            for (float num2 = 0f; num2 < 1f; num2 += 0.5f)
            {
                if (Main.rand.NextFloat() < 0.5f)
                {
                    Dust dust3 = Dust.NewDustPerfect(base.Center, 263, (-Vector2.UnitY).RotatedBy(((0f - num15) * (3f - num15 * 0.6f) + num2 + Main.rand.NextFloatDirection() * 0.05f * (1f - num15)) * ((float)Math.PI * 2f)) * (2f + Main.rand.NextFloat() + Main.rand.NextFloat() * 3f * num15), 30, new Color(80, 200, 255));
                    dust3.noGravity = true;
                    dust3.fadeIn = 1.1f;
                }
            }
        }
        if (ai[0] <= 60f)
        {
            float num3 = Utils.Remap(ai[0], 0f, 60f, 0f, 1f);
            for (float num4 = 0f; num4 < 1f; num4 += 0.5f)
            {
                if (Main.rand.NextFloat() < 0.5f)
                {
                    Dust dust4 = Dust.NewDustPerfect(base.Center, 263, (-Vector2.UnitY).RotatedBy(((0f - num3) * 3f + num4 + Main.rand.NextFloatDirection() * 0.05f) * ((float)Math.PI * 2f)) * (2f * num3 + Main.rand.NextFloat() * num3), 100, new Color(80, 200, 255), 2f - num3);
                    dust4.noGravity = true;
                    dust4.fadeIn = 1.1f;
                }
            }
            if (ai[0] == 58f)
            {
                for (float num5 = 0f; num5 < 1f; num5 += 1f / 12f)
                {
                    Dust dust5 = Dust.NewDustPerfect(base.Center, 263, (-Vector2.UnitY).RotatedBy(((0f - num3) * 2f + num5 + Main.rand.NextFloatDirection() * 0.05f) * ((float)Math.PI * 2f)) * (1f * num3 + Main.rand.NextFloat() * num3 * 2f), 100, new Color(80, 200, 255), 0.8f);
                    dust5.noGravity = true;
                    dust5.fadeIn = 1.2f;
                }
            }
        }
        if (ai[0] >= num14 - 20f)
        {
            float num6 = Utils.Remap(ai[0], num14 - 20f, num14, 0.25f, 1f);
            Rectangle r3 = Utils.CenteredRectangle(base.Center + new Vector2(0f, 30f + num6 * -20f), new Vector2(82f, 72f) * num6);
            for (int j = 0; j < 5; j++)
            {
                Dust dust6 = Dust.NewDustDirect(r3.TopLeft(), r3.Width, r3.Height, 263, 0f, num6 * -4f, 100, new Color(80, 200, 255) * 0.75f, 0.1f);
                dust6.noGravity = true;
                dust6.fadeIn = 0.6f + Main.rand.NextFloat() * 0.3f;
                dust6.velocity = new Vector2(0f, -0.3f);
            }
            for (int k = 0; k < 1; k++)
            {
                Rectangle r4 = Utils.CenteredRectangle(base.Center + new Vector2(0f, 40f), new Vector2(32f, 32f));
                Dust dust7 = Dust.NewDustDirect(r4.TopLeft(), r4.Width, r4.Height, 263, 0f, 0f, 100, new Color(80, 200, 255), 0.6f);
                dust7.noGravity = true;
                dust7.fadeIn = 0.9f;
                dust7.velocity = new Vector2(0f, -0.3f);
            }
        }
        if (Main.rand.Next(6) == 0 && ai[0] >= 90f && ai[0] < num8)
        {
            Rectangle r5 = Utils.CenteredRectangle(base.Center + new Vector2(0f, 0f), new Vector2(104f, 104f));
            Dust dust8 = Dust.NewDustDirect(r5.TopLeft(), r5.Width, r5.Height, 263, 0f, 0f, 100, new Color(80, 200, 255), 0.6f);
            dust8.noGravity = true;
            dust8.fadeIn = 0.9f;
            dust8.velocity = new Vector2(0f, -0.3f);
        }
        if (ai[0] >= num14)
        {
            int num7 = Item.NewItem(new EntitySource_Gift(this), base.Center + new Vector2(0f, 12f), Vector2.Zero, 5276);
            Main.item[num7].velocity = new Vector2(0f, 0f);
            Kill();
        }
    }
References Terraria.Utils.CenteredRectangle(), Terraria.Main.item, Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Item.NewItem(), Terraria.Main.player, Terraria.Main.rand, and Terraria.Utils.Remap().