TModLoader: Terraria.Projectile.CanHitWithMeleeWeapon
CanHitWithMeleeWeapon()
bool Terraria.Projectile.CanHitWithMeleeWeapon (Entity ent) inline
Definition at line 11486 of file Projectile.cs.
    {
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0160: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        if (Distance(ent.Center) > ownerHitCheckDistance)
        {
            return false;
        }
        if (!Collision.CanHit(Main.player[owner].position, Main.player[owner].width, Main.player[owner].height, ent.position, ent.width, ent.height) && !Collision.CanHitLine(Main.player[owner].Center + new Vector2((float)(Main.player[owner].direction * Main.player[owner].width / 2), Main.player[owner].gravDir * (float)(-Main.player[owner].height) / 3f), 0, 0, ent.Center + new Vector2(0f, (float)(-ent.height / 3)), 0, 0) && !Collision.CanHitLine(Main.player[owner].Center + new Vector2((float)(Main.player[owner].direction * Main.player[owner].width / 2), Main.player[owner].gravDir * (float)(-Main.player[owner].height) / 3f), 0, 0, ent.Center, 0, 0))
        {
            return Collision.CanHitLine(Main.player[owner].Center + new Vector2((float)(Main.player[owner].direction * Main.player[owner].width / 2), 0f), 0, 0, ent.Center + new Vector2(0f, (float)(ent.height / 3)), 0, 0);
        }
        return true;
    }
References Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Entity.Center, Terraria.Entity.direction, Terraria.Entity.Distance(), Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Projectile.owner, Terraria.Projectile.ownerHitCheckDistance, Terraria.Main.player, Terraria.Entity.position, and Terraria.Entity.width.
Referenced by Terraria.Projectile.BombsHurtPlayers(), and Terraria.Projectile.Damage().