TModLoader: Terraria.Projectile.ExplodeTiles
ExplodeTiles()
void Terraria.Projectile.ExplodeTiles (Vector2 compareSpot, int radius, int minI, int maxI, int minJ, int maxJ, bool wallSplode) inline
Explodes tiles within a radius of the given position and within the bounds passed in. The wallSplode parameter should be the result of M:Terraria.Projectile.ShouldWallExplode(Microsoft.Xna.Framework.Vector2,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32) and dictates if walls will also be destroyed. This method honors the tile and wall explosion conditions.
Definition at line 91780 of file Projectile.cs.
    {
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        AchievementsHelper.CurrentlyMining = true;
        for (int i = minI; i <= maxI; i++)
        {
            for (int j = minJ; j <= maxJ; j++)
            {
                float num3 = Math.Abs((float)i - compareSpot.X / 16f);
                float num2 = Math.Abs((float)j - compareSpot.Y / 16f);
                if (!(Math.Sqrt(num3 * num3 + num2 * num2) < (double)radius))
                {
                    continue;
                }
                bool flag = true;
                if (Main.tile[i, j] != null && Main.tile[i, j].active())
                {
                    flag = CanExplodeTile(i, j);
                    if (flag)
                    {
                        WorldGen.KillTile(i, j);
                        if (!Main.tile[i, j].active() && Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, i, j);
                        }
                    }
                }
                if (!flag)
                {
                    continue;
                }
                for (int k = i - 1; k <= i + 1; k++)
                {
                    for (int l = j - 1; l <= j + 1; l++)
                    {
                        if (Main.tile[k, l] != null && Main.tile[k, l].wall > 0 && wallSplode && WallLoader.CanExplode(k, l, Main.tile[k, l].wall))
{
                            WorldGen.KillWall(k, l);
                            if (Main.tile[k, l].wall == 0 && Main.netMode != 0)
{
                                NetMessage.SendData(17, -1, -1, null, 2, k, l);
                            }
                        }
                    }
                }
            }
        }
        AchievementsHelper.CurrentlyMining = false;
    }
References Terraria.ModLoader.WallLoader.CanExplode(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillWall(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), and Terraria.Main.tile.