TModLoader: Terraria.Projectile.AI_144_DD2Pet
AI_144_DD2Pet()
void Terraria.Projectile.AI_144_DD2Pet () inline private
    {
        //IL_0625: Unknown result type (might be due to invalid IL or missing references)
        //IL_062a: Unknown result type (might be due to invalid IL or missing references)
        //IL_062c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0631: Unknown result type (might be due to invalid IL or missing references)
        //IL_0634: Unknown result type (might be due to invalid IL or missing references)
        //IL_0639: Unknown result type (might be due to invalid IL or missing references)
        //IL_065b: Unknown result type (might be due to invalid IL or missing references)
        //IL_065e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0663: Unknown result type (might be due to invalid IL or missing references)
        //IL_0668: Unknown result type (might be due to invalid IL or missing references)
        //IL_064a: Unknown result type (might be due to invalid IL or missing references)
        //IL_064f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0651: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_0683: Unknown result type (might be due to invalid IL or missing references)
        //IL_0685: Unknown result type (might be due to invalid IL or missing references)
        //IL_066f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0679: Unknown result type (might be due to invalid IL or missing references)
        //IL_067e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0202: Unknown result type (might be due to invalid IL or missing references)
        //IL_0208: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0218: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0240: Unknown result type (might be due to invalid IL or missing references)
        //IL_025d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_0269: Unknown result type (might be due to invalid IL or missing references)
        //IL_0273: Unknown result type (might be due to invalid IL or missing references)
        //IL_0278: Unknown result type (might be due to invalid IL or missing references)
        //IL_0295: Unknown result type (might be due to invalid IL or missing references)
        //IL_029b: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04db: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_019b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0506: Unknown result type (might be due to invalid IL or missing references)
        //IL_050c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0511: Unknown result type (might be due to invalid IL or missing references)
        //IL_0550: Unknown result type (might be due to invalid IL or missing references)
        //IL_0556: Unknown result type (might be due to invalid IL or missing references)
        //IL_042b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0431: Unknown result type (might be due to invalid IL or missing references)
        //IL_0436: Unknown result type (might be due to invalid IL or missing references)
        //IL_0475: Unknown result type (might be due to invalid IL or missing references)
        //IL_047b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0489: Unknown result type (might be due to invalid IL or missing references)
        //IL_0493: Unknown result type (might be due to invalid IL or missing references)
        //IL_0498: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        float num = 4f;
        int num4 = 6;
        int num5 = 4;
        int num6 = Main.projFrames[type];
        int num7 = 0;
        float num8 = 0.08f;
        bool flag = false;
        float num9 = 0.1f;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)(player.direction * 30), -20f);
        if (player.dead)
        {
            Kill();
            return;
        }
        bool flag2 = true;
        switch (type)
        {
        case 702:
        {
            if (player.petFlagDD2Ghost)
            {
                timeLeft = 2;
            }
            vector.Y += (float)Math.Cos(localAI[0] * ((float)Math.PI / 60f)) * 2f;
            num5 = 4;
            num4 = 10;
            flag2 = false;
            num = 6f;
            Vector2 vector3 = Utils.RotatedBy(new Vector2((float)((spriteDirection == -1) ? (-6) : (-2)), -26f), rotation);
            if (Main.rand.Next(24) == 0)
            {
                Dust dust2 = Dust.NewDustDirect(base.Center + vector3, 4, 4, 135, 0f, 0f, 100);
                if (Main.rand.Next(3) != 0)
                {
                    dust2.noGravity = true;
                    dust2.velocity.Y -= 3f;
                    dust2.noLight = true;
                }
                else if (Main.rand.Next(2) != 0)
                {
                    dust2.noLight = true;
                }
                dust2.velocity *= 0.5f;
                dust2.velocity.Y -= 0.9f;
                dust2.scale += 0.1f + Main.rand.NextFloat() * 0.6f;
            }
            DelegateMethods.v3_1 = new Vector3(0.3f, 0.5f, 1f);
            Utils.PlotTileLine(base.Center, base.Center + velocity * 6f, 20f, DelegateMethods.CastLightOpen);
            Utils.PlotTileLine(base.Left, base.Right, 20f, DelegateMethods.CastLightOpen);
            Utils.PlotTileLine(player.Center, player.Center + player.velocity * 6f, 40f, DelegateMethods.CastLightOpen);
            Utils.PlotTileLine(player.Left, player.Right, 40f, DelegateMethods.CastLightOpen);
            break;
        }
        case 703:
            if (player.petFlagDD2Gato)
            {
                timeLeft = 2;
            }
            vector.Y += (float)Math.Cos(localAI[0] * ((float)Math.PI / 30f)) * 2f;
            num4 = 4;
            num5 = 2;
            num = 3f;
            num6 = 4;
            break;
        case 701:
            if (player.petFlagDD2Dragon)
            {
                timeLeft = 2;
            }
            break;
        case 764:
        {
            num9 = 0.025f;
            num8 = 0.04f;
            flag = true;
            localAI[0] += 1f;
            if (localAI[0] > 120f)
            {
                localAI[0] = 0f;
            }
            localAI[1] += velocity.X * 0.01f;
            localAI[1] += 1f / 120f;
            if (localAI[1] < (float)Math.PI * -2f)
            {
                localAI[1] += (float)Math.PI * 2f;
            }
            if (localAI[1] > (float)Math.PI * 2f)
            {
                localAI[1] -= (float)Math.PI * 2f;
            }
            if (((Vector2)(ref velocity)).Length() < 4f)
            {
                localAI[1] *= 0.9f;
                if (((Vector2)(ref velocity)).Length() > 0.1f && Main.rand.Next(30) == 0)
                {
                    Dust dust3 = Dust.NewDustDirect(position - velocity, width, height, 292, velocity.X * 0.5f, velocity.Y * 0.5f, 150);
                    dust3.velocity *= 0.3f;
                    dust3.noLightEmittence = true;
                }
            }
            else
            {
                Vector2 vector2 = default(Vector2);
                ((Vector2)(ref vector2))._002Ector((float)Main.screenWidth, (float)Main.screenHeight);
                Rectangle hitbox = base.Hitbox;
                ((Rectangle)(ref hitbox)).Intersects(Utils.CenteredRectangle(Main.screenPosition + vector2 / 2f, vector2 + new Vector2(400f)));
                if (Main.rand.Next(15) == 0)
                {
                    Dust.NewDustDirect(position - velocity, width, height, 292, velocity.X * 0.5f, velocity.Y * 0.5f, 150, default(Color), 0.9f).noLightEmittence = true;
                }
            }
            float num10 = localAI[0] / 120f * 2f;
            if (num10 > 1f)
            {
                num10 = 2f - num10;
            }
            Opacity = MathHelper.Lerp(0.4f, 0.75f, num10);
            vector.Y += (float)Math.Cos(localAI[0] / 120f * ((float)Math.PI * 2f)) * 2f;
            if (player.petFlagUpbeatStar)
            {
                timeLeft = 2;
            }
            break;
        }
        }
        if (flag2 && (player.suspiciouslookingTentacle || player.petFlagDD2Ghost))
        {
            vector.X += -player.direction * 64;
        }
        direction = (spriteDirection = player.direction);
        Vector2 vector4 = player.MountedCenter + vector;
        float num11 = Vector2.Distance(base.Center, vector4);
        if (num11 > 1000f)
        {
            base.Center = player.Center + vector;
        }
        Vector2 vector5 = vector4 - base.Center;
        if (num11 < num)
        {
            velocity *= 0.25f;
        }
        if (vector5 != Vector2.Zero)
        {
            if (((Vector2)(ref vector5)).Length() < num * 0.5f)
            {
                velocity = vector5;
            }
            else
            {
                velocity = vector5 * num9;
            }
        }
        if (((Vector2)(ref velocity)).Length() > 6f)
        {
            float num2 = velocity.X * num8 + velocity.Y * (float)spriteDirection * 0.02f;
            if (Math.Abs(rotation - num2) >= (float)Math.PI)
            {
                if (num2 < rotation)
                {
                    rotation -= (float)Math.PI * 2f;
                }
                else
                {
                    rotation += (float)Math.PI * 2f;
                }
            }
            float num3 = 12f;
            rotation = (rotation * (num3 - 1f) + num2) / num3;
            if (++frameCounter >= num5)
            {
                frameCounter = 0;
                if (++frame >= num6)
                {
                    frame = num7;
                }
            }
        }
        else
        {
            if (rotation > (float)Math.PI)
            {
                rotation -= (float)Math.PI * 2f;
            }
            if (rotation > -0.005f && rotation < 0.005f)
            {
                rotation = 0f;
            }
            else
            {
                rotation *= 0.96f;
            }
            if (++frameCounter >= num4)
            {
                frameCounter = 0;
                if (++frame >= num6)
                {
                    frame = num7;
                }
            }
        }
        if (!flag)
        {
            localAI[0] += 1f;
            if (localAI[0] > 120f)
            {
                localAI[0] = 0f;
            }
        }
    }
References Terraria.DelegateMethods.CastLightOpen(), Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.Player.dead, Terraria.Entity.direction, Terraria.Entity.Left, Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Player.petFlagDD2Dragon, Terraria.Player.petFlagDD2Gato, Terraria.Player.petFlagDD2Ghost, Terraria.Player.petFlagUpbeatStar, Terraria.Main.player, Terraria.Utils.PlotTileLine(), Terraria.Main.projFrames, Terraria.Main.rand, Terraria.Entity.Right, Terraria.Utils.RotatedBy(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Player.suspiciouslookingTentacle, and Terraria.Entity.velocity.