TModLoader: Terraria.Projectile.AI_150_GolfClubHelper
AI_150_GolfClubHelper()
void Terraria.Projectile.AI_150_GolfClubHelper () inline private
Definition at line 55116 of file Projectile.cs.
    {
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0313: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        //IL_0374: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_037b: Unknown result type (might be due to invalid IL or missing references)
        //IL_037e: Unknown result type (might be due to invalid IL or missing references)
        //IL_012e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0419: Unknown result type (might be due to invalid IL or missing references)
        //IL_041e: Unknown result type (might be due to invalid IL or missing references)
        //IL_03eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0392: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0202: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        //IL_024e: Unknown result type (might be due to invalid IL or missing references)
        //IL_025a: Unknown result type (might be due to invalid IL or missing references)
        //IL_025f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        if (!player.active)
        {
            Kill();
            return;
        }
        if (player.gravDir == -1f)
        {
            player.SetDummyItemTime(0);
            Kill();
            return;
        }
        bool flag = false;
        Rectangle rectangle = Utils.CenteredRectangle(player.Center, new Vector2(500f, 500f));
        for (int i = 0; i < 1000; i++)
        {
            Projectile projectile = Main.projectile[i];
            if (projectile.active && projectile.owner == Main.myPlayer && ProjectileID.Sets.IsAGolfBall[projectile.type] && ((Rectangle)(ref rectangle)).Contains(projectile.Center.ToPoint()))
            {
                flag = true;
                break;
            }
        }
        if (!flag && owner == Main.myPlayer && ai[0] == 0f)
        {
            player.TryPlacingAGolfBallNearANearbyTee(Main.player[owner].Center);
        }
        if (!player.channel && ai[0] == 0f)
        {
            SoundEngine.PlaySound(in SoundID.Item1, player.Center);
            for (int j = 0; j < 1000; j++)
            {
                Projectile projectile2 = Main.projectile[j];
                Vector2 shotVector = Main.MouseWorld - projectile2.Center;
                if (!projectile2.active || !ProjectileID.Sets.IsAGolfBall[projectile2.type] || projectile2.owner != owner || !GolfHelper.ValidateShot(projectile2, player, ref shotVector))
                {
                    continue;
                }
                float num = Main.rand.NextFloatDirection();
                for (float num2 = 0f; num2 < 1f; num2 += 0.1f)
                {
                    Dust dust = Dust.NewDustPerfect(projectile2.Center, 31, ((float)Math.PI * 2f * num2 + num).ToRotationVector2() * 0.8f, 127);
                    dust.fadeIn = 0f;
                    if (num2 % 0.2f == 0f)
                    {
                        dust.velocity *= 0.4f;
                    }
                }
                SoundEngine.PlaySound(in SoundID.Item126, projectile2.Center);
                if (owner == Main.myPlayer)
                {
                    GolfHelper.ShotStrength shotStrength = GolfHelper.CalculateShotStrength(this, projectile2);
                    Vector2 vector = Vector2.Normalize(shotVector) * shotStrength.AbsoluteStrength;
                    GolfHelper.HitGolfBall(projectile2, vector, shotStrength.RoughLandResistance);
                    NetMessage.SendData(27, -1, -1, null, j);
                }
            }
            ai[0] = 1f;
            ai[1] = 0f;
            netUpdate = true;
        }
        if (ai[0] == 1f)
        {
            ai[1] += 1f;
            float num3 = player.HeldItem.useAnimation + 30;
            if (ai[1] >= num3)
            {
                Kill();
                return;
            }
            velocity = Vector2.Zero;
            player.ChangeDir(direction);
            player.heldProj = whoAmI;
            int num4 = player.HeldItem.useAnimation - (int)ai[1];
            if (num4 < 2)
            {
                num4 = 2;
            }
            player.SetDummyItemTime(num4);
        }
        if (ai[0] != 0f)
        {
            return;
        }
        if (owner == Main.myPlayer)
        {
            Vector2 mouseWorld = Main.MouseWorld;
            if (mouseWorld != base.Center)
            {
                netUpdate = true;
                base.Center = mouseWorld;
            }
            if (Main.mouseRight && Main.mouseRightRelease)
            {
                Kill();
                player.mouseInterface = true;
                Main.blockMouse = true;
                player.SetItemTime(0);
                player.itemAnimation = 0;
                player.itemAnimationMax = 0;
                player.reuseDelay = 0;
                return;
            }
        }
        if (position != oldPosition)
        {
            if (base.Center.X - player.Center.X > 0f)
            {
                direction = 1;
            }
            else
            {
                direction = -1;
            }
        }
        velocity = Vector2.Zero;
        player.ChangeDir(direction);
        player.heldProj = whoAmI;
        ai[1] += 1f;
        int num5 = player.HeldItem.useAnimation * 4;
        if (ai[1] > (float)(num5 * 3))
        {
            ai[1] = num5;
        }
        int num6 = player.HeldItem.useAnimation + Math.Min(num5, (int)ai[1]);
        if (num6 < 2)
        {
            num6 = 2;
        }
        player.SetDummyItemTime(num6);
    }
References Terraria.Entity.active, Terraria.GameContent.Golf.GolfHelper.CalculateShotStrength(), Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.Player.ChangeDir(), Terraria.Player.channel, Terraria.Player.gravDir, Terraria.GameContent.Golf.GolfHelper.HitGolfBall(), Terraria.ID.ProjectileID.Sets.IsAGolfBall, Terraria.ID.SoundID.Item1, Terraria.ID.SoundID.Item126, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.MouseWorld, Terraria.Main.myPlayer, Terraria.Dust.NewDustPerfect(), Terraria.Projectile.owner, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.projectile, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Player.SetDummyItemTime(), Terraria.Player.SetItemTime(), Terraria.Player.TryPlacingAGolfBallNearANearbyTee(), Terraria.Projectile.type, and Terraria.GameContent.Golf.GolfHelper.ValidateShot().