TModLoader: Terraria.Projectile.DropGeodeLoot
DropGeodeLoot()
static void Terraria.Projectile.DropGeodeLoot (Entity entity) inline static
Will drop loot the same way as when F:Terraria.ID.ProjectileID.Geode is cracked open.
Parameters
entity The entity the loot originates from
Definition at line 93145 of file Projectile.cs.
    {
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        Dictionary<int, (int, int)> dict = ItemID.Sets.GeodeDrops;
        List<int> list = dict.Keys.ToList();
        int attempts = 0;
        while (attempts < 2 && list.Count > 0)
        {
            attempts++;
            int item = Main.rand.Next(list);
            list.Remove(item);
            int stack = Main.rand.Next(dict[item].Item1, dict[item].Item2);
            int num = Item.NewItem(new EntitySource_Loot(entity), entity.position, entity.Size, item, stack);
            Main.item[num].noGrabDelay = 0;
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, num, 1f);
            }
        }
    }
References Terraria.ID.ItemID.Sets.GeodeDrops, Terraria.Main.item, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Item.noGrabDelay, Terraria.Entity.position, Terraria.Main.rand, Terraria.NetMessage.SendData(), and Terraria.Entity.Size.