TModLoader: Terraria.Projectile.AI_158_BabyBird
AI_158_BabyBird()
void Terraria.Projectile.AI_158_BabyBird () inline private
    {
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0465: Unknown result type (might be due to invalid IL or missing references)
        //IL_046a: Unknown result type (might be due to invalid IL or missing references)
        //IL_046d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0225: Unknown result type (might be due to invalid IL or missing references)
        //IL_022a: Unknown result type (might be due to invalid IL or missing references)
        //IL_022f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0233: Unknown result type (might be due to invalid IL or missing references)
        //IL_0238: Unknown result type (might be due to invalid IL or missing references)
        //IL_0245: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_025c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0261: Unknown result type (might be due to invalid IL or missing references)
        //IL_0266: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0202: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0214: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0515: Unknown result type (might be due to invalid IL or missing references)
        //IL_0517: Unknown result type (might be due to invalid IL or missing references)
        //IL_051c: Unknown result type (might be due to invalid IL or missing references)
        //IL_051e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0541: Unknown result type (might be due to invalid IL or missing references)
        //IL_0546: Unknown result type (might be due to invalid IL or missing references)
        //IL_054a: Unknown result type (might be due to invalid IL or missing references)
        //IL_054f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0553: Unknown result type (might be due to invalid IL or missing references)
        //IL_055d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0562: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_028d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0292: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_074b: Unknown result type (might be due to invalid IL or missing references)
        //IL_074d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0752: Unknown result type (might be due to invalid IL or missing references)
        //IL_0756: Unknown result type (might be due to invalid IL or missing references)
        //IL_075b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0768: Unknown result type (might be due to invalid IL or missing references)
        //IL_0775: Unknown result type (might be due to invalid IL or missing references)
        //IL_077f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0784: Unknown result type (might be due to invalid IL or missing references)
        //IL_0789: Unknown result type (might be due to invalid IL or missing references)
        //IL_0578: Unknown result type (might be due to invalid IL or missing references)
        //IL_058b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0590: Unknown result type (might be due to invalid IL or missing references)
        //IL_080f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0832: Unknown result type (might be due to invalid IL or missing references)
        //IL_0837: Unknown result type (might be due to invalid IL or missing references)
        //IL_079e: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b5: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        int totalIndexesInGroup;
        if (type == 759)
        {
            if (player.dead)
            {
                player.babyBird = false;
            }
            if (player.babyBird)
            {
                timeLeft = 2;
            }
            totalIndexesInGroup = ++frameCounter;
            if (totalIndexesInGroup >= 6)
            {
                frameCounter = 0;
                totalIndexesInGroup = ++frame;
                if (totalIndexesInGroup >= Main.projFrames[type] - 1)
                {
                    frame = 0;
                }
            }
        }
        float num = 6f;
        float num4 = 8f;
        int num5 = 800;
        float num6 = 150f;
        int attackTarget = -1;
        Minion_FindTargetInRange(num5, ref attackTarget, skipIfCannotHitWithOwnBody: false);
        if (attackTarget != -1)
        {
            NPC nPC = Main.npc[attackTarget];
            if (player.Distance(nPC.Center) > (float)num5)
            {
                attackTarget = -1;
            }
        }
        if (attackTarget != -1)
        {
            if (!Collision.SolidCollision(position, width, height))
            {
                tileCollide = true;
            }
            NPC nPC2 = Main.npc[attackTarget];
            float num7 = Distance(nPC2.Center);
            Rectangle rectangle = default(Rectangle);
            ((Rectangle)(ref rectangle))._002Ector((int)position.X, (int)position.Y, width, height);
            Rectangle value = default(Rectangle);
            ((Rectangle)(ref value))._002Ector((int)nPC2.position.X, (int)nPC2.position.Y, nPC2.width, nPC2.height);
            if (((Rectangle)(ref rectangle)).Intersects(value))
            {
                tileCollide = false;
                if (Math.Abs(velocity.X) + Math.Abs(velocity.Y) < num4)
                {
                    velocity *= 1.1f;
                }
                if (((Vector2)(ref velocity)).Length() > num4)
                {
                    velocity *= num4 / ((Vector2)(ref velocity)).Length();
                }
            }
            else if (num7 > num6)
            {
                Vector2 vector = DirectionTo(nPC2.Center);
                velocity = Vector2.Lerp(velocity, vector * num, 0.15f);
            }
            else
            {
                tileCollide = false;
                Vector2 vector2 = DirectionTo(nPC2.Center);
                velocity += new Vector2((float)Math.Sign(vector2.X), (float)Math.Sign(vector2.Y)) * 0.35f;
                if (((Vector2)(ref velocity)).Length() > num4)
                {
                    velocity *= num4 / ((Vector2)(ref velocity)).Length();
                }
            }
            float num8 = 0.025f;
            float num9 = width * 3;
            for (int i = 0; i < 1000; i++)
            {
                if (i != whoAmI && Main.projectile[i].active && Main.projectile[i].owner == owner && Main.projectile[i].type == type && Math.Abs(position.X - Main.projectile[i].position.X) + Math.Abs(position.Y - Main.projectile[i].position.Y) < num9)
                {
                    if (position.X < Main.projectile[i].position.X)
                    {
                        velocity.X -= num8;
                    }
                    else
                    {
                        velocity.X += num8;
                    }
                    if (position.Y < Main.projectile[i].position.Y)
                    {
                        velocity.Y -= num8;
                    }
                    else
                    {
                        velocity.Y += num8;
                    }
                }
            }
            rotation = velocity.X * 0.1f;
            direction = ((velocity.X > 0f) ? 1 : (-1));
            spriteDirection = ((velocity.X > 0f) ? 1 : (-1));
            return;
        }
        tileCollide = false;
        List<int> ai158_blacklistedTargets = _ai158_blacklistedTargets;
        ai158_blacklistedTargets.Clear();
        AI_GetMyGroupIndexAndFillBlackList(ai158_blacklistedTargets, out var index, out totalIndexesInGroup);
        localAI[0] = index;
        Vector2 vector3 = AI_158_GetHomeLocation(player, index);
        float num10 = Distance(vector3);
        bool flag = player.gravDir > 0f && player.fullRotation == 0f && player.headRotation == 0f;
        if (num10 > 2000f)
        {
            base.Center = vector3;
            frame = Main.projFrames[type] - 1;
            frameCounter = 0;
            velocity = Vector2.Zero;
            direction = (spriteDirection = player.direction);
            rotation = 0f;
        }
        else if (num10 > 40f)
        {
            float num11 = num + num10 * 0.006f;
            Vector2 vector4 = DirectionTo(vector3);
            vector4 *= MathHelper.Lerp(1f, 5f, Utils.GetLerpValue(40f, 800f, num10, clamped: true));
            velocity = Vector2.Lerp(velocity, vector4 * num11, 0.025f);
            if (((Vector2)(ref velocity)).Length() > num11)
            {
                velocity *= num11 / ((Vector2)(ref velocity)).Length();
            }
            float num2 = 0.05f;
            float num3 = width;
            for (int j = 0; j < 1000; j++)
            {
                if (j != whoAmI && Main.projectile[j].active && Main.projectile[j].owner == owner && Main.projectile[j].type == type && Math.Abs(position.X - Main.projectile[j].position.X) + Math.Abs(position.Y - Main.projectile[j].position.Y) < num3)
                {
                    if (position.X < Main.projectile[j].position.X)
                    {
                        velocity.X -= num2;
                    }
                    else
                    {
                        velocity.X += num2;
                    }
                    if (position.Y < Main.projectile[j].position.Y)
                    {
                        velocity.Y -= num2;
                    }
                    else
                    {
                        velocity.Y += num2;
                    }
                }
            }
            rotation = velocity.X * 0.04f;
            direction = ((velocity.X > 0f) ? 1 : (-1));
            spriteDirection = ((velocity.X > 0f) ? 1 : (-1));
        }
        else if (num10 > 8f + ((Vector2)(ref player.velocity)).Length())
        {
            Vector2 vector5 = DirectionTo(vector3);
            velocity += new Vector2((float)Math.Sign(vector5.X), (float)Math.Sign(vector5.Y)) * 0.05f;
            if (((Vector2)(ref velocity)).Length() > num)
            {
                velocity *= num / ((Vector2)(ref velocity)).Length();
            }
            rotation = velocity.X * 0.1f;
            direction = ((velocity.X > 0f) ? 1 : (-1));
            spriteDirection = ((velocity.X > 0f) ? 1 : (-1));
        }
        else if (flag)
        {
            base.Center = vector3;
            frame = Main.projFrames[type] - 1;
            frameCounter = 0;
            velocity = Vector2.Zero;
            direction = (spriteDirection = player.direction);
            rotation = 0f;
        }
    }
References Terraria.Player.babyBird, Terraria.Player.dead, Terraria.Entity.direction, Terraria.Entity.Distance(), Terraria.Utils.GetLerpValue(), Terraria.Main.npc, Terraria.Main.player, Terraria.Main.projectile, Terraria.Main.projFrames, Terraria.Collision.SolidCollision(), and Terraria.Entity.velocity.