TModLoader: Terraria.Projectile.AI_155_SpawnRopeIn
AI_155_SpawnRopeIn()
void Terraria.Projectile.AI_155_SpawnRopeIn (int x, int y) inline private
Definition at line 54968 of file Projectile.cs.
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)(x * 16 + 8), (float)(y * 16 + 8));
        if (Main.rand.Next(4) != 0)
        {
            Gore gore = Gore.NewGoreDirect(vector, Vector2.Zero, Main.rand.Next(61, 64));
            gore.velocity = Main.rand.NextVector2Circular(1.5f, 0.8f);
            gore.velocity.X += 0.1f * (float)((gore.velocity.X > 0f) ? 1 : (-1));
            gore.position = vector - new Vector2(16f, 16f);
            gore.alpha = 170;
        }
        for (int i = 0; i < 5; i++)
        {
            if (Main.rand.Next(8) == 0)
            {
                Dust dust = Dust.NewDustDirect(vector + new Vector2(-8f), 16, 16, 31, 0f, 0f, 100, Color.Transparent);
                dust.velocity *= 0.4f;
            }
            Dust dust2 = Dust.NewDustDirect(vector + new Vector2(-8f), 16, 16, 27, 0f, 0f, 100, Color.Transparent, 1.7f);
            dust2.velocity *= 2f;
            dust2.noGravity = true;
        }
    }
References Terraria.Dust.NewDustDirect(), Terraria.Gore.NewGoreDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, and Terraria.Gore.velocity.