TModLoader: Terraria.Projectile.AI_009_MagicMissiles_Old
AI_009_MagicMissiles_Old()
void Terraria.Projectile.AI_009_MagicMissiles_Old () inline private
    {
        //IL_0567: Unknown result type (might be due to invalid IL or missing references)
        //IL_056d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0572: Unknown result type (might be due to invalid IL or missing references)
        //IL_0577: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0668: Unknown result type (might be due to invalid IL or missing references)
        //IL_0679: Unknown result type (might be due to invalid IL or missing references)
        //IL_0594: Unknown result type (might be due to invalid IL or missing references)
        //IL_059b: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_035e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c03: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c08: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0acf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b14: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b19: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a60: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a65: Unknown result type (might be due to invalid IL or missing references)
        //IL_095f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0980: Unknown result type (might be due to invalid IL or missing references)
        //IL_0986: Unknown result type (might be due to invalid IL or missing references)
        //IL_099d: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a53: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a58: Unknown result type (might be due to invalid IL or missing references)
        //IL_093c: Unknown result type (might be due to invalid IL or missing references)
        //IL_07df: Unknown result type (might be due to invalid IL or missing references)
        //IL_080d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0827: Unknown result type (might be due to invalid IL or missing references)
        //IL_0831: Unknown result type (might be due to invalid IL or missing references)
        //IL_0836: Unknown result type (might be due to invalid IL or missing references)
        //IL_0844: Unknown result type (might be due to invalid IL or missing references)
        //IL_084a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0854: Unknown result type (might be due to invalid IL or missing references)
        //IL_0859: Unknown result type (might be due to invalid IL or missing references)
        //IL_085e: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00da: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b55: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b83: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bcb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a73: Unknown result type (might be due to invalid IL or missing references)
        //IL_0462: Unknown result type (might be due to invalid IL or missing references)
        //IL_0485: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0705: Unknown result type (might be due to invalid IL or missing references)
        //IL_070b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0722: Unknown result type (might be due to invalid IL or missing references)
        //IL_072c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0731: Unknown result type (might be due to invalid IL or missing references)
        //IL_0746: Unknown result type (might be due to invalid IL or missing references)
        //IL_074c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0751: Unknown result type (might be due to invalid IL or missing references)
        //IL_075b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0760: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0236: Unknown result type (might be due to invalid IL or missing references)
        //IL_0240: Unknown result type (might be due to invalid IL or missing references)
        //IL_0245: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_0256: Unknown result type (might be due to invalid IL or missing references)
        if (Main.myPlayer == owner && ai[0] <= 0f)
        {
            if (Main.player[owner].channel && Main.player[owner].HeldItem.shoot == type)
            {
                float num = 12f;
                if (type == 16)
                {
                    num = 15f;
                }
                if (type == 491)
                {
                    num = 20f;
                }
                Vector2 vector = default(Vector2);
                ((Vector2)(ref vector))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                Vector2 pointPoisition = Main.MouseWorld;
                Main.player[owner].LimitPointToPlayerReachableArea(ref pointPoisition);
                float num11 = pointPoisition.X - vector.X;
                float num12 = pointPoisition.Y - vector.Y;
                float num13 = (float)Math.Sqrt(num11 * num11 + num12 * num12);
                if (ai[0] < 0f)
                {
                    ai[0] += 1f;
                }
                if (type == 491 && num13 < 100f)
                {
                    if (((Vector2)(ref velocity)).Length() < num)
                    {
                        velocity *= 1.1f;
                        if (((Vector2)(ref velocity)).Length() > num)
{
                            ((Vector2)(ref velocity)).Normalize();
                            velocity *= num;
                        }
                    }
                    if (ai[0] == 0f)
                    {
                        ai[0] = -10f;
                    }
                }
                else if (num13 > num)
                {
                    num13 = num / num13;
                    num11 *= num13;
                    num12 *= num13;
                    int num17 = (int)(num11 * 1000f);
                    int num14 = (int)(velocity.X * 1000f);
                    int num15 = (int)(num12 * 1000f);
                    int num16 = (int)(velocity.Y * 1000f);
                    if (num17 != num14 || num15 != num16)
                    {
                        netUpdate = true;
                    }
                    if (type == 491)
                    {
                        Vector2 vector2 = default(Vector2);
                        ((Vector2)(ref vector2))._002Ector(num11, num12);
                        velocity = (velocity * 4f + vector2) / 5f;
                    }
                    else
                    {
                        velocity.X = num11;
                        velocity.Y = num12;
                    }
                }
                else
                {
                    int num18 = (int)(num11 * 1000f);
                    int num2 = (int)(velocity.X * 1000f);
                    int num3 = (int)(num12 * 1000f);
                    int num4 = (int)(velocity.Y * 1000f);
                    if (num18 != num2 || num3 != num4)
                    {
                        netUpdate = true;
                    }
                    velocity.X = num11;
                    velocity.Y = num12;
                }
            }
            else if (ai[0] <= 0f)
            {
                netUpdate = true;
                if (type != 491)
                {
                    Vector2 vector3 = default(Vector2);
                    ((Vector2)(ref vector3))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                    float num5 = (float)Main.mouseX + Main.screenPosition.X - vector3.X;
                    float num6 = (float)Main.mouseY + Main.screenPosition.Y - vector3.Y;
                    if (Main.player[owner].gravDir == -1f)
                    {
                        num6 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - vector3.Y;
                    }
                    float num7 = (float)Math.Sqrt(num5 * num5 + num6 * num6);
                    if (num7 == 0f || ai[0] < 0f)
                    {
                        ((Vector2)(ref vector3))._002Ector(Main.player[owner].position.X + (float)(Main.player[owner].width / 2), Main.player[owner].position.Y + (float)(Main.player[owner].height / 2));
                        num5 = position.X + (float)width * 0.5f - vector3.X;
                        num6 = position.Y + (float)height * 0.5f - vector3.Y;
                        num7 = (float)Math.Sqrt(num5 * num5 + num6 * num6);
                    }
                    num7 = 12f / num7;
                    num5 *= num7;
                    num6 *= num7;
                    velocity.X = num5;
                    velocity.Y = num6;
                    if (velocity.X == 0f && velocity.Y == 0f)
                    {
                        Kill();
                    }
                }
                ai[0] = 1f;
            }
        }
        bool flag = false;
        if (type == 491)
        {
            localAI[0] += 1f;
            if (ai[0] > 0f && localAI[0] > 15f)
            {
                tileCollide = false;
                Vector2 vector4 = Main.player[owner].Center - base.Center;
                if (((Vector2)(ref vector4)).Length() < 20f)
                {
                    Kill();
                }
                ((Vector2)(ref vector4)).Normalize();
                vector4 *= 25f;
                velocity = (velocity * 5f + vector4) / 6f;
            }
            flag = true;
            if (ai[0] < 0f || (velocity.X == 0f && velocity.Y == 0f))
            {
                rotation += 0.3f;
            }
            else if (ai[0] > 0f)
            {
                rotation += 0.3f * (float)direction;
            }
            else
            {
                rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
            }
            if (Vector2.Distance(base.Center, Main.player[owner].Center) > 2000f)
            {
                Kill();
            }
            if (Main.rand.Next(2) == 0)
            {
                int num19 = Main.rand.Next(3);
                int num8 = Dust.NewDust(position, width, height, num19 switch
                {
                    0 => 15,
                    1 => 57,
                    _ => 58,
                }, velocity.X * 0.25f, velocity.Y * 0.25f, 255, default(Color), 0.7f);
                Dust obj = Main.dust[num8];
                obj.velocity *= 0.25f;
                Main.dust[num8].position = (Main.dust[num8].position + position) / 2f;
            }
        }
        if (type == 79)
        {
            if (soundDelay == 0 && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > 2f)
            {
                soundDelay = 10;
                SoundEngine.PlaySound(in SoundID.Item9, position);
            }
            for (int i = 0; i < 1; i++)
            {
                int num9 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 66, 0f, 0f, 100, new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB), 2.5f);
                Dust obj2 = Main.dust[num9];
                obj2.velocity *= 0.1f;
                Dust obj3 = Main.dust[num9];
                obj3.velocity += velocity * 0.2f;
                Main.dust[num9].position.X = position.X + (float)(width / 2) + 4f + (float)Main.rand.Next(-2, 3);
                Main.dust[num9].position.Y = position.Y + (float)(height / 2) + (float)Main.rand.Next(-2, 3);
                Main.dust[num9].noGravity = true;
            }
        }
        if (type == 16)
        {
            if (soundDelay == 0 && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > 2f)
            {
                soundDelay = 10;
                SoundEngine.PlaySound(in SoundID.Item9, position);
            }
            if (Main.rand.Next(9) == 0)
            {
                int num10 = Dust.NewDust(position, width, height, 15, 0f, 0f, 100, default(Color), 2f);
                Dust obj4 = Main.dust[num10];
                obj4.velocity *= 0.3f;
                Main.dust[num10].position.X = position.X + (float)(width / 2) + 4f + (float)Main.rand.Next(-4, 5);
                Main.dust[num10].position.Y = position.Y + (float)(height / 2) + (float)Main.rand.Next(-4, 5);
                Main.dust[num10].noGravity = true;
                Dust obj5 = Main.dust[num10];
                obj5.velocity += Main.rand.NextVector2Circular(2f, 2f);
            }
            flag = true;
            if (velocity != Vector2.Zero)
            {
                rotation = velocity.ToRotation();
            }
        }
        if (type == 34)
        {
            if (Main.rand.Next(12) == 0)
            {
                Dust dust = Dust.NewDustDirect(base.Center, 0, 0, 6, velocity.X * 0.2f, velocity.Y * 0.2f, 100, default(Color), 3.5f);
                dust.noGravity = true;
                dust.velocity *= 1.4f;
                dust.velocity += Main.rand.NextVector2Circular(1f, 1f);
                dust.velocity += velocity * 0.15f;
            }
            if (Main.rand.Next(24) == 0)
            {
                Dust dust2 = Dust.NewDustDirect(base.Center, 0, 0, 6, velocity.X * 0.2f, velocity.Y * 0.2f, 100, default(Color), 1.5f);
                dust2.velocity += Main.rand.NextVector2Circular(1f, 1f);
                dust2.velocity += velocity * 0.15f;
            }
            flag = true;
            if (velocity != Vector2.Zero)
            {
                rotation = velocity.ToRotation();
            }
        }
        if (!flag && velocity != Vector2.Zero)
        {
            rotation = velocity.ToRotation() - (float)Math.PI + (float)Math.PI / 4f;
        }
        if (velocity.Y > 16f)
        {
            velocity.Y = 16f;
        }
    }
References Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.Main.dust, Terraria.ID.SoundID.Item9, Terraria.Main.MouseWorld, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Main.screenHeight, and Terraria.Main.screenPosition.