TModLoader: Terraria.Projectile.AI_137_LightningAura
AI_137_LightningAura()
void Terraria.Projectile.AI_137_LightningAura () inline private
Definition at line 75907 of file Projectile.cs.
    {
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_0137: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_0338: Unknown result type (might be due to invalid IL or missing references)
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0352: Unknown result type (might be due to invalid IL or missing references)
        //IL_0358: Unknown result type (might be due to invalid IL or missing references)
        //IL_035d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0367: Unknown result type (might be due to invalid IL or missing references)
        //IL_036c: Unknown result type (might be due to invalid IL or missing references)
        //IL_038b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_023c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_0243: Unknown result type (might be due to invalid IL or missing references)
        //IL_024f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0254: Unknown result type (might be due to invalid IL or missing references)
        //IL_025c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_026b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_020d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0214: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0404: Unknown result type (might be due to invalid IL or missing references)
        //IL_0409: Unknown result type (might be due to invalid IL or missing references)
        //IL_040e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0410: Unknown result type (might be due to invalid IL or missing references)
        //IL_041b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0432: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_043b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0452: Unknown result type (might be due to invalid IL or missing references)
        //IL_0458: Unknown result type (might be due to invalid IL or missing references)
        //IL_0468: Unknown result type (might be due to invalid IL or missing references)
        //IL_046a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0471: Unknown result type (might be due to invalid IL or missing references)
        //IL_0475: Unknown result type (might be due to invalid IL or missing references)
        //IL_047a: Unknown result type (might be due to invalid IL or missing references)
        //IL_047f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0484: Unknown result type (might be due to invalid IL or missing references)
        //IL_0489: Unknown result type (might be due to invalid IL or missing references)
        //IL_050a: Unknown result type (might be due to invalid IL or missing references)
        //IL_050f: Unknown result type (might be due to invalid IL or missing references)
        //IL_051c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0521: Unknown result type (might be due to invalid IL or missing references)
        //IL_0530: Unknown result type (might be due to invalid IL or missing references)
        //IL_0535: Unknown result type (might be due to invalid IL or missing references)
        //IL_053a: Unknown result type (might be due to invalid IL or missing references)
        //IL_053c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0547: Unknown result type (might be due to invalid IL or missing references)
        //IL_055b: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0603: Unknown result type (might be due to invalid IL or missing references)
        //IL_0608: Unknown result type (might be due to invalid IL or missing references)
        //IL_062d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0633: Unknown result type (might be due to invalid IL or missing references)
        //IL_0641: Unknown result type (might be due to invalid IL or missing references)
        //IL_064b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0650: Unknown result type (might be due to invalid IL or missing references)
        //IL_0657: Unknown result type (might be due to invalid IL or missing references)
        //IL_065c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0666: Unknown result type (might be due to invalid IL or missing references)
        //IL_066b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0670: Unknown result type (might be due to invalid IL or missing references)
        //IL_0564: Unknown result type (might be due to invalid IL or missing references)
        //IL_057b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0581: Unknown result type (might be due to invalid IL or missing references)
        //IL_058f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0599: Unknown result type (might be due to invalid IL or missing references)
        //IL_059e: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05be: Unknown result type (might be due to invalid IL or missing references)
        int num = 10;
        int num2 = 999;
        int num3 = 30;
        int num4 = 40;
        int num5 = 4;
        knockBack = 0f;
        if (Main.player[owner].setMonkT2)
        {
            num3 -= 5;
        }
        if (Main.player[owner].setMonkT3)
        {
            num = 14;
            num5 = 8;
        }
        ai[0] += 1f;
        if (ai[0] >= (float)num3)
        {
            ai[0] = 0f;
        }
        if (ai[0] == 0f)
        {
            bool flag = false;
            for (int i = 0; i < 200; i++)
            {
                NPC nPC = Main.npc[i];
                if (nPC.CanBeChasedBy(this) && nPC.Hitbox.Distance(base.Center) < (float)(width / 2) && Colliding(base.Hitbox, nPC.Hitbox))
                {
                    flag = true;
                    break;
                }
            }
            if (flag)
            {
                SoundEngine.PlayTrackedSound(in SoundID.DD2_LightningAuraZap, base.Center);
            }
        }
        if (localAI[0] == 0f)
        {
            localAI[0] = 1f;
            velocity = Vector2.Zero;
            Point origin = base.Center.ToTileCoordinates();
            bool flag2 = true;
            if (!WorldUtils.Find(origin, Searches.Chain(new Searches.Down(500), _cachedConditions_notNull, _cachedConditions_solid), out var result))
            {
                flag2 = false;
                position.Y += 16f;
                return;
            }
            if (!WorldUtils.Find(new Point(result.X, result.Y - 1), Searches.Chain(new Searches.Up(num), _cachedConditions_notNull, _cachedConditions_solid), out var result2))
            {
                ((Point)(ref result2))._002Ector(origin.X, origin.Y - num - 1);
            }
            int num6 = 0;
            if (flag2 && Main.tile[result.X, result.Y] != null && Main.tile[result.X, result.Y].blockType() == 1)
            {
                num6 += 8;
            }
            Vector2 center = result.ToWorldCoordinates(8f, num6);
            Vector2 vector = result2.ToWorldCoordinates(8f, 0f);
            base.Size = new Vector2(1f, center.Y - vector.Y);
            if (height > num * 16)
            {
                height = num * 16;
            }
            if (height < num5 * 16)
            {
                height = num5 * 16;
            }
            height *= 2;
            width = (int)((float)height * 1f);
            if (width > num2)
            {
                width = num2;
            }
            base.Center = center;
        }
        if (++frameCounter >= 8)
        {
            frameCounter = 0;
            if (++frame >= Main.projFrames[type])
            {
                frame = 0;
            }
        }
        DelegateMethods.v3_1 = new Vector3(0.2f, 0.7f, 1f);
        Utils.PlotTileLine(base.Center + Vector2.UnitX * -40f, base.Center + Vector2.UnitX * 40f, 80f, DelegateMethods.CastLightOpen);
        Vector2 vector2 = default(Vector2);
        ((Vector2)(ref vector2))._002Ector(base.Top.X, position.Y + (float)num4);
        for (int j = 0; j < 4; j++)
        {
            if (Main.rand.Next(6) != 0)
            {
                continue;
            }
            Vector2 vector3 = Main.rand.NextVector2Unit();
            if (!(Math.Abs(vector3.X) < 0.12f))
            {
                Vector2 targetPosition = base.Center + vector3 * new Vector2((float)((height - num4) / 2));
                if (!WorldGen.SolidTile((int)targetPosition.X / 16, (int)targetPosition.Y / 16) && AI_137_CanHit(targetPosition))
                {
                    Dust dust = Dust.NewDustDirect(targetPosition, 0, 0, 226, 0f, 0f, 100);
                    dust.position = targetPosition;
                    dust.velocity = (vector2 - dust.position).SafeNormalize(Vector2.Zero);
                    dust.scale = 0.7f;
                    dust.fadeIn = 1f;
                    dust.noGravity = true;
                    dust.noLight = true;
                }
            }
        }
        for (int k = 0; k < 0; k++)
        {
            if (Main.rand.Next(10) != 0)
            {
                continue;
            }
            Vector2 vector4 = Main.rand.NextVector2Unit();
            if (!(Math.Abs(vector4.X) < 0.12f))
            {
                Vector2 targetPosition2 = base.Center + vector4 * new Vector2((float)((height - num4) / 2)) * Main.rand.NextFloat();
                if (!WorldGen.SolidTile((int)targetPosition2.X / 16, (int)targetPosition2.Y / 16) && AI_137_CanHit(targetPosition2))
                {
                    Dust dust2 = Dust.NewDustDirect(targetPosition2, 0, 0, 226, 0f, 0f, 100);
                    dust2.velocity *= 0.6f;
                    dust2.velocity += Vector2.UnitY * -2f;
                    dust2.noGravity = true;
                    dust2.noLight = true;
                }
            }
        }
        for (int l = 0; l < 4; l++)
        {
            if (Main.rand.Next(10) == 0)
            {
                Dust dust3 = Dust.NewDustDirect(vector2 - new Vector2(8f, 0f), 16, height / 2 - 40, 226, 0f, 0f, 100);
                dust3.velocity *= 0.6f;
                dust3.velocity += Vector2.UnitY * -2f;
                dust3.scale = 0.7f;
                dust3.noGravity = true;
                dust3.noLight = true;
            }
        }
        tileCollide = true;
        velocity.Y += 0.2f;
    }
References Terraria.DelegateMethods.CastLightOpen(), Terraria.WorldBuilding.Searches.Chain(), Terraria.ID.SoundID.DD2_LightningAuraZap, Terraria.WorldBuilding.WorldUtils.Find(), Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Main.player, Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Utils.PlotTileLine(), Terraria.Dust.position, Terraria.Main.projFrames, Terraria.Main.rand, Terraria.Player.setMonkT2, Terraria.Player.setMonkT3, Terraria.WorldGen.SolidTile(), and Terraria.Main.tile.