TModLoader: Terraria.Projectile.AI_162_TigerPounce
AI_162_TigerPounce()
void Terraria.Projectile.AI_162_TigerPounce () inline private
    {
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        //IL_035b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0201: Unknown result type (might be due to invalid IL or missing references)
        //IL_0206: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_025a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_026a: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_0286: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        //IL_028e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_0335: Unknown result type (might be due to invalid IL or missing references)
        //IL_033b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0345: Unknown result type (might be due to invalid IL or missing references)
        //IL_034a: Unknown result type (might be due to invalid IL or missing references)
        //IL_034f: Unknown result type (might be due to invalid IL or missing references)
        if (ai[0] < 0f)
        {
            Opacity = 0f;
            ai[0] += 1f;
            return;
        }
        bool flag = false;
        flag = true;
        if (frameCounter == 0)
        {
            frameCounter = 1;
            localAI[0] = base.Center.X;
            localAI[1] = base.Center.Y;
            flag = true;
        }
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(localAI[0], localAI[1]);
        Vector2 vector2 = vector + velocity;
        float y = Vector2.Distance(vector, vector2) * 1.5f;
        float num = 0.1f;
        Vector2 val = Vector2.Lerp(vector, vector2, 0f - num) + new Vector2(0f, y);
        Vector2 value2 = Vector2.Lerp(vector, vector2, 1f + num) + new Vector2(0f, y);
        if (Opacity < 1f)
        {
            Opacity += 0.1f;
        }
        int num2 = Math.Sign(vector2.X - vector.X);
        rotation += (float)num2 * -0.2f;
        spriteDirection = num2;
        if (ai[1] < 1f)
        {
            ai[1] = 60f;
        }
        ai[0] += 1f / ai[1];
        float num4 = Utils.Clamp(ai[0], 0f, 1f);
        Vector2 vector3 = Vector2.CatmullRom(val, vector, vector2, value2, num4);
        if (flag)
        {
            for (float num3 = 0f; num3 < 1f; num3 += 0.5f)
            {
                if (Main.rand.Next(19) == 0)
                {
                    Vector2 vector4 = base.Center + DirectionTo(vector3).SafeNormalize(Vector2.UnitY) * 100f;
                    Dust dust = Dust.NewDustPerfect(base.Center + base.Size * Main.rand.NextVector2Square(0f, 1f), 278, Main.rand.NextVector2Circular(3f, 3f), 100, Color.White * 0.4f);
                    dust.velocity.Y += -0.6f;
                    dust.velocity += velocity * 0.1f;
                    Main.rand.Next(5);
                    dust.velocity = (vector4 - base.Center) * 0.05f;
                    dust.fadeIn = 0f;
                    dust.scale = 0.7f;
                    dust.noGravity = true;
                }
            }
            if (Main.rand.Next(2) == 0)
            {
                Dust obj = Main.dust[Dust.NewDust(position, width, height, 269)];
                obj.fadeIn = 0.7f;
                obj.scale = 0.4f;
                obj.velocity += velocity * 0.001f;
                obj.noLight = true;
            }
        }
        base.Center = vector3;
        if (ai[0] >= 1f)
        {
            Kill();
        }
    }
References Terraria.Main.dust, Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), and Terraria.Main.rand.