TModLoader: Terraria.Projectile.AI_157_SharpTears
AI_157_SharpTears()
void Terraria.Projectile.AI_157_SharpTears () inline private
    {
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0301: Unknown result type (might be due to invalid IL or missing references)
        //IL_0308: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_032c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0339: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0361: Unknown result type (might be due to invalid IL or missing references)
        //IL_0366: Unknown result type (might be due to invalid IL or missing references)
        //IL_036b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0372: Unknown result type (might be due to invalid IL or missing references)
        //IL_037c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0381: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0416: Unknown result type (might be due to invalid IL or missing references)
        //IL_0423: Unknown result type (might be due to invalid IL or missing references)
        //IL_0429: Unknown result type (might be due to invalid IL or missing references)
        //IL_0437: Unknown result type (might be due to invalid IL or missing references)
        //IL_044b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0450: Unknown result type (might be due to invalid IL or missing references)
        //IL_0455: Unknown result type (might be due to invalid IL or missing references)
        //IL_045c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0466: Unknown result type (might be due to invalid IL or missing references)
        //IL_046b: Unknown result type (might be due to invalid IL or missing references)
        //IL_019f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0209: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_0236: Unknown result type (might be due to invalid IL or missing references)
        //IL_023b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0287: Unknown result type (might be due to invalid IL or missing references)
        int num = 5;
        float num2 = 1f;
        int num3 = 30;
        int num4 = 30;
        int num5 = 2;
        int num6 = 2;
        int num7 = 20;
        int num8 = 30;
        int num9 = 35;
        int maxValue = 6;
        if (type == 961)
        {
            num = 16;
            num2 = 0.75f;
            num3 = 5;
            num4 = 5;
            num5 = 0;
            num6 = 0;
            num7 = 10;
            num8 = 10;
            num9 = 20;
            maxValue = 5;
        }
        bool flag = ai[0] < (float)num7;
        bool flag2 = ai[0] >= (float)num8;
        bool flag3 = ai[0] >= (float)num9;
        ai[0] += 1f;
        if (localAI[0] == 0f)
        {
            localAI[0] = 1f;
            rotation = velocity.ToRotation();
            frame = Main.rand.Next(maxValue);
            for (int i = 0; i < num3; i++)
            {
                Dust dust = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(24f, 24f), num, velocity * num2 * MathHelper.Lerp(0.2f, 0.7f, Main.rand.NextFloat()));
                dust.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                dust.scale = 0.8f + Main.rand.NextFloat() * 0.5f;
            }
            for (int j = 0; j < num4; j++)
            {
                Dust dust2 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(24f, 24f), num, Main.rand.NextVector2Circular(2f, 2f) + velocity * num2 * MathHelper.Lerp(0.2f, 0.5f, Main.rand.NextFloat()));
                dust2.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                dust2.scale = 0.8f + Main.rand.NextFloat() * 0.5f;
                dust2.fadeIn = 1f;
            }
            if (type == 961)
            {
                SoundEngine.PlaySound(in SoundID.DeerclopsIceAttack, base.Center);
            }
            else
            {
                SoundEngine.PlaySound(in SoundID.Item60, base.Center);
            }
        }
        if (flag)
        {
            Opacity += 0.1f;
            scale = Opacity * ai[1];
            for (int k = 0; k < num5; k++)
            {
                Dust dust3 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(16f, 16f), num, velocity * num2 * MathHelper.Lerp(0.2f, 0.5f, Main.rand.NextFloat()));
                dust3.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                dust3.velocity *= 0.5f;
                dust3.scale = 0.8f + Main.rand.NextFloat() * 0.5f;
            }
        }
        if (flag2)
        {
            Opacity -= 0.2f;
            for (int l = 0; l < num6; l++)
            {
                Dust dust4 = Dust.NewDustPerfect(base.Center + Main.rand.NextVector2Circular(16f, 16f), num, velocity * num2 * MathHelper.Lerp(0.2f, 0.5f, Main.rand.NextFloat()));
                dust4.velocity += Main.rand.NextVector2Circular(0.5f, 0.5f);
                dust4.velocity *= 0.5f;
                dust4.scale = 0.8f + Main.rand.NextFloat() * 0.5f;
            }
        }
        if (flag3)
        {
            Kill();
        }
        if (type == 756)
        {
            Lighting.AddLight(base.Center, new Vector3(0.5f, 0.1f, 0.1f) * scale);
        }
    }
References Terraria.Lighting.AddLight(), Terraria.ID.SoundID.DeerclopsIceAttack, Terraria.ID.SoundID.Item60, Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.rand.