TModLoader: Terraria.Projectile.AI_135_OgreStomp
AI_135_OgreStomp()
void Terraria.Projectile.AI_135_OgreStomp () inline private
    {
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0628: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_0615: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0262: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        //IL_0578: Unknown result type (might be due to invalid IL or missing references)
        //IL_057d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0603: Unknown result type (might be due to invalid IL or missing references)
        //IL_0608: Unknown result type (might be due to invalid IL or missing references)
        //IL_0434: Unknown result type (might be due to invalid IL or missing references)
        //IL_0439: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0294: Unknown result type (might be due to invalid IL or missing references)
        //IL_033b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0340: Unknown result type (might be due to invalid IL or missing references)
        //IL_035b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0365: Unknown result type (might be due to invalid IL or missing references)
        //IL_036a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0450: Unknown result type (might be due to invalid IL or missing references)
        //IL_046f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0522: Unknown result type (might be due to invalid IL or missing references)
        //IL_0527: Unknown result type (might be due to invalid IL or missing references)
        //IL_0542: Unknown result type (might be due to invalid IL or missing references)
        //IL_054c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0551: Unknown result type (might be due to invalid IL or missing references)
        float num = 40f;
        if (type == 922)
        {
            num = 30f;
        }
        ai[0] += 1f;
        if (ai[0] > 9f)
        {
            Kill();
            return;
        }
        velocity = Vector2.Zero;
        position = base.Center;
        base.Size = new Vector2(16f, 16f) * MathHelper.Lerp(5f, num, Utils.GetLerpValue(0f, 9f, ai[0]));
        base.Center = position;
        Point point = base.TopLeft.ToTileCoordinates();
        Point point2 = base.BottomRight.ToTileCoordinates();
        int num2 = point.X / 2 + point2.X / 2;
        int num3 = width / 2;
        if ((int)ai[0] % 3 != 0)
        {
            return;
        }
        int num4 = (int)ai[0] / 3;
        for (int i = point.X; i <= point2.X; i++)
        {
            for (int j = point.Y; j <= point2.Y; j++)
            {
                if (Vector2.Distance(base.Center, new Vector2((float)(i * 16), (float)(j * 16))) > (float)num3)
                {
                    continue;
                }
                Tile tileSafely = Framing.GetTileSafely(i, j);
                if (!tileSafely.active() || !Main.tileSolid[tileSafely.type] || Main.tileSolidTop[tileSafely.type] || Main.tileFrameImportant[tileSafely.type])
                {
                    continue;
                }
                Tile tileSafely2 = Framing.GetTileSafely(i, j - 1);
                if (tileSafely2.active() && Main.tileSolid[tileSafely2.type] && !Main.tileSolidTop[tileSafely2.type])
                {
                    continue;
                }
                int num5 = WorldGen.KillTile_GetTileDustAmount(fail: true, tileSafely, i, j);
                for (int k = 0; k < num5; k++)
                {
                    Dust obj = Main.dust[WorldGen.KillTile_MakeTileDust(i, j, tileSafely)];
                    obj.velocity.Y -= 3f + (float)num4 * 1.5f;
                    obj.velocity.Y *= Main.rand.NextFloat();
                    obj.velocity.Y *= 0.75f;
                    obj.scale += (float)num4 * 0.03f;
                }
                if (num4 >= 2)
                {
                    if (type == 922)
                    {
                        Color newColor = NPC.AI_121_QueenSlime_GetDustColor();
                        ((Color)(ref newColor)).A = 150;
                        for (int l = 0; l < num5 - 1; l++)
{
                            int num6 = Dust.NewDust(position, 12, 12, 4, 0f, 0f, 50, newColor, 1.5f);
                            Main.dust[num6].velocity.Y -= 0.1f + (float)num4 * 0.5f;
                            Main.dust[num6].velocity.Y *= Main.rand.NextFloat();
                            Main.dust[num6].velocity.X *= Main.rand.NextFloatDirection() * 3f;
                            Main.dust[num6].position = new Vector2((float)(i * 16 + Main.rand.Next(16)), (float)(j * 16 + Main.rand.Next(16)));
                            if (Main.rand.Next(3) != 0)
{
                                Dust obj2 = Main.dust[num6];
                                obj2.velocity *= 0.5f;
                                Main.dust[num6].noGravity = true;
                            }
                        }
                    }
                    else
                    {
                        for (int m = 0; m < num5 - 1; m++)
{
                            Dust obj3 = Main.dust[WorldGen.KillTile_MakeTileDust(i, j, tileSafely)];
                            obj3.velocity.Y -= 1f + (float)num4;
                            obj3.velocity.Y *= Main.rand.NextFloat();
                            obj3.velocity.Y *= 0.75f;
                        }
                    }
                }
                if (num5 <= 0 || Main.rand.Next(3) == 0)
                {
                    continue;
                }
                float num7 = (float)Math.Abs(num2 - i) / (num / 2f);
                if (type == 922)
                {
                    Color newColor2 = NPC.AI_121_QueenSlime_GetDustColor();
                    ((Color)(ref newColor2)).A = 150;
                    for (int n = 0; n < 3; n++)
                    {
                        int num8 = Dust.NewDust(position, width, height, 31, 0f, 0f, 50, newColor2, 2f - (float)num4 * 0.15f + num7 * 0.5f);
                        Main.dust[num8].velocity.Y -= 0.1f + (float)num4 * 0.5f + num7 * (float)num4 * 1f;
                        Main.dust[num8].velocity.Y *= Main.rand.NextFloat();
                        Main.dust[num8].velocity.X *= Main.rand.NextFloatDirection() * 3f;
                        Main.dust[num8].position = new Vector2((float)(i * 16 + 20), (float)(j * 16 + 20));
                        if (Main.rand.Next(3) != 0)
{
                            Dust obj4 = Main.dust[num8];
                            obj4.velocity *= 0.5f;
                            Main.dust[num8].noGravity = true;
                        }
                    }
                }
                else
                {
                    Gore gore = Gore.NewGoreDirect(position, Vector2.Zero, 61 + Main.rand.Next(3), 1f - (float)num4 * 0.15f + num7 * 0.5f);
                    gore.velocity.Y -= 0.1f + (float)num4 * 0.5f + num7 * (float)num4 * 1f;
                    gore.velocity.Y *= Main.rand.NextFloat();
                    gore.position = new Vector2((float)(i * 16 + 20), (float)(j * 16 + 20));
                }
            }
        }
    }
References Terraria.NPC.AI_121_QueenSlime_GetDustColor(), Terraria.Main.dust, Terraria.Utils.GetLerpValue(), Terraria.Framing.GetTileSafely(), Terraria.WorldGen.KillTile_GetTileDustAmount(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.Dust.NewDust(), Terraria.Gore.NewGoreDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.position, Terraria.Main.rand, Terraria.Main.tileFrameImportant, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Dust.velocity.