TModLoader: Terraria.Projectile.AI_155_RemoveRope
AI_155_RemoveRope()
void Terraria.Projectile.AI_155_RemoveRope (Point start, Point end) inline private
Definition at line 54948 of file Projectile.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        int x = start.X;
        for (int num = start.Y; num >= end.Y; num--)
        {
            Tile tile = Main.tile[x, num];
            if (tile.active() && tile.type == 504)
            {
                WorldGen.KillTile(x, num);
                if (Main.netMode != 0)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, x, num);
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), and Terraria.Main.tile.