TModLoader: Terraria.Projectile.UpdateEnchantmentVisuals
UpdateEnchantmentVisuals()
void Terraria.Projectile.UpdateEnchantmentVisuals () inline private
Definition at line 16425 of file Projectile.cs.
    {
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        if (npcProj)
        {
            return;
        }
        Vector2 boxPosition = position;
        int boxWidth = width;
        int boxHeight = height;
        if (aiStyle == 190 || aiStyle == 191)
        {
            for (float num = -(float)Math.PI / 4f; num <= (float)Math.PI / 4f; num += (float)Math.PI / 2f)
            {
                Rectangle r = Utils.CenteredRectangle(base.Center + (rotation + num).ToRotationVector2() * 70f * scale, new Vector2(60f * scale, 60f * scale));
                EmitEnchantmentVisualsAt(r.TopLeft(), r.Width, r.Height);
            }
        }
        else if (ProjectileID.Sets.IsAWhip[type])
        {
            WhipPointsForCollision.Clear();
            FillWhipControlPoints(this, WhipPointsForCollision);
            Vector2 vector = WhipPointsForCollision[WhipPointsForCollision.Count - 1];
            EmitEnchantmentVisualsAt(new Vector2(vector.X - (float)(width / 2), vector.Y - (float)(height / 2)), width, height);
        }
        else
        {
            EmitEnchantmentVisualsAt(boxPosition, boxWidth, boxHeight);
        }
    }
References Terraria.Projectile.aiStyle, Terraria.Utils.CenteredRectangle(), Terraria.Projectile.EmitEnchantmentVisualsAt(), Terraria.Projectile.FillWhipControlPoints(), Terraria.Entity.height, Terraria.ID.ProjectileID.Sets.IsAWhip, Terraria.Projectile.npcProj, Terraria.Entity.position, Terraria.Projectile.rotation, Terraria.Projectile.scale, Terraria.Projectile.type, Terraria.Projectile.WhipPointsForCollision, and Terraria.Entity.width.
Referenced by Terraria.Projectile.Update().