TModLoader: Terraria.Projectile.AI_149_GolfBall
AI_149_GolfBall()
void Terraria.Projectile.AI_149_GolfBall () inline private
    {
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        if (!npcProj && timeLeft < 10)
        {
            timeLeft = 10;
        }
        if (ai[1] == -1f)
        {
            Tile tileSafely = Framing.GetTileSafely(base.Bottom.ToTileCoordinates());
            if (!tileSafely.active() || tileSafely.type != 494)
            {
                ai[1] = 0f;
                netUpdate = true;
            }
            return;
        }
        BallStepResult ballStepResult = GolfHelper.StepGolfBall(this, ref localAI[0]);
        if (ballStepResult.State == BallState.Resting)
        {
            damage = 0;
            if (Main.netMode == 1 && owner == Main.myPlayer && localAI[1] != (float)ballStepResult.State)
            {
                netUpdate = true;
            }
        }
        localAI[1] = (float)ballStepResult.State;
        rotation += localAI[0];
        if (velocity.Y != 0f && ballStepResult.State == BallState.Moving)
        {
            rotation += velocity.X * 0.1f + velocity.Y * 0.1f;
        }
        if (ballStepResult.State == BallState.Moving && owner == Main.myPlayer)
        {
            bool? flag = ProjectileID.Sets.ForcePlateDetection[135];
            if ((!flag.HasValue || flag.Value) && localAI[1] != 0f)
            {
                Collision.SwitchTiles(position, width, height, oldPosition, 4);
            }
        }
        if (ballStepResult.State == BallState.Moving && Main.netMode == 2 && Main.player.IndexInRange(owner) && Main.player[owner].active)
        {
            RemoteClient.CheckSection(owner, position);
        }
    }
References Terraria.Projectile.ai, Terraria.RemoteClient.CheckSection(), Terraria.Projectile.damage, Terraria.ID.ProjectileID.Sets.ForcePlateDetection, Terraria.Framing.GetTileSafely(), Terraria.Entity.height, Terraria.Projectile.localAI, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.netUpdate, Terraria.Projectile.npcProj, Terraria.Entity.oldPosition, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Entity.position, Terraria.Projectile.rotation, Terraria.GameContent.Golf.GolfHelper.StepGolfBall(), Terraria.Collision.SwitchTiles(), Terraria.Projectile.timeLeft, Terraria.Entity.velocity, and Terraria.Entity.width.