TModLoader: Terraria.Projectile.AI_062
AI_062()
void Terraria.Projectile.AI_062 () inline private
Definition at line 70257 of file Projectile.cs.
    {
        //IL_0278: Unknown result type (might be due to invalid IL or missing references)
        //IL_0306: Unknown result type (might be due to invalid IL or missing references)
        //IL_0338: Unknown result type (might be due to invalid IL or missing references)
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_0383: Unknown result type (might be due to invalid IL or missing references)
        //IL_0388: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_069c: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aca: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_070d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0713: Unknown result type (might be due to invalid IL or missing references)
        //IL_072d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0733: Unknown result type (might be due to invalid IL or missing references)
        //IL_073d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0742: Unknown result type (might be due to invalid IL or missing references)
        //IL_0747: Unknown result type (might be due to invalid IL or missing references)
        //IL_074f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0759: Unknown result type (might be due to invalid IL or missing references)
        //IL_075e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0766: Unknown result type (might be due to invalid IL or missing references)
        //IL_076c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0776: Unknown result type (might be due to invalid IL or missing references)
        //IL_077b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0780: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04de: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0506: Unknown result type (might be due to invalid IL or missing references)
        //IL_0510: Unknown result type (might be due to invalid IL or missing references)
        //IL_0515: Unknown result type (might be due to invalid IL or missing references)
        //IL_051c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0522: Unknown result type (might be due to invalid IL or missing references)
        //IL_052c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0531: Unknown result type (might be due to invalid IL or missing references)
        //IL_0536: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_058d: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0600: Unknown result type (might be due to invalid IL or missing references)
        //IL_0602: Unknown result type (might be due to invalid IL or missing references)
        //IL_0610: Unknown result type (might be due to invalid IL or missing references)
        //IL_0615: Unknown result type (might be due to invalid IL or missing references)
        //IL_061b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0626: Unknown result type (might be due to invalid IL or missing references)
        //IL_062b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0630: Unknown result type (might be due to invalid IL or missing references)
        //IL_0637: Unknown result type (might be due to invalid IL or missing references)
        //IL_0641: Unknown result type (might be due to invalid IL or missing references)
        //IL_0646: Unknown result type (might be due to invalid IL or missing references)
        //IL_07eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_080e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0814: Unknown result type (might be due to invalid IL or missing references)
        //IL_082e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0833: Unknown result type (might be due to invalid IL or missing references)
        //IL_083b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0845: Unknown result type (might be due to invalid IL or missing references)
        //IL_084a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0852: Unknown result type (might be due to invalid IL or missing references)
        //IL_0858: Unknown result type (might be due to invalid IL or missing references)
        //IL_0862: Unknown result type (might be due to invalid IL or missing references)
        //IL_0867: Unknown result type (might be due to invalid IL or missing references)
        //IL_086c: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08af: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c38: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c44: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c50: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c52: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d71: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c79: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ccd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cdb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e26: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e55: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0def: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1017: Unknown result type (might be due to invalid IL or missing references)
        //IL_184f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1862: Unknown result type (might be due to invalid IL or missing references)
        //IL_1160: Unknown result type (might be due to invalid IL or missing references)
        //IL_1163: Unknown result type (might be due to invalid IL or missing references)
        //IL_1168: Unknown result type (might be due to invalid IL or missing references)
        //IL_116d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1178: Unknown result type (might be due to invalid IL or missing references)
        //IL_117a: Unknown result type (might be due to invalid IL or missing references)
        //IL_117f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1184: Unknown result type (might be due to invalid IL or missing references)
        //IL_107c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1196: Unknown result type (might be due to invalid IL or missing references)
        //IL_1198: Unknown result type (might be due to invalid IL or missing references)
        //IL_11a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_11a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_1345: Unknown result type (might be due to invalid IL or missing references)
        //IL_1347: Unknown result type (might be due to invalid IL or missing references)
        //IL_134a: Unknown result type (might be due to invalid IL or missing references)
        //IL_134f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1351: Unknown result type (might be due to invalid IL or missing references)
        //IL_1356: Unknown result type (might be due to invalid IL or missing references)
        //IL_1358: Unknown result type (might be due to invalid IL or missing references)
        //IL_135a: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_112d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1134: Unknown result type (might be due to invalid IL or missing references)
        //IL_1139: Unknown result type (might be due to invalid IL or missing references)
        //IL_18c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_18cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_18cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_18d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_18d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_18e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_18ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_18ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_1372: Unknown result type (might be due to invalid IL or missing references)
        //IL_1374: Unknown result type (might be due to invalid IL or missing references)
        //IL_1379: Unknown result type (might be due to invalid IL or missing references)
        //IL_137e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1380: Unknown result type (might be due to invalid IL or missing references)
        //IL_1382: Unknown result type (might be due to invalid IL or missing references)
        //IL_1389: Unknown result type (might be due to invalid IL or missing references)
        //IL_138e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1393: Unknown result type (might be due to invalid IL or missing references)
        //IL_1395: Unknown result type (might be due to invalid IL or missing references)
        //IL_1366: Unknown result type (might be due to invalid IL or missing references)
        //IL_136b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1370: Unknown result type (might be due to invalid IL or missing references)
        //IL_12a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_12a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_12a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_12b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_12bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_12c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_18fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_190a: Unknown result type (might be due to invalid IL or missing references)
        //IL_190f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1914: Unknown result type (might be due to invalid IL or missing references)
        //IL_1597: Unknown result type (might be due to invalid IL or missing references)
        //IL_159b: Unknown result type (might be due to invalid IL or missing references)
        //IL_15a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_15bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_15e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_156f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1579: Unknown result type (might be due to invalid IL or missing references)
        //IL_157e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1539: Unknown result type (might be due to invalid IL or missing references)
        //IL_153d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1542: Unknown result type (might be due to invalid IL or missing references)
        //IL_1546: Unknown result type (might be due to invalid IL or missing references)
        //IL_1550: Unknown result type (might be due to invalid IL or missing references)
        //IL_1555: Unknown result type (might be due to invalid IL or missing references)
        //IL_1557: Unknown result type (might be due to invalid IL or missing references)
        //IL_1561: Unknown result type (might be due to invalid IL or missing references)
        //IL_1566: Unknown result type (might be due to invalid IL or missing references)
        //IL_13af: Unknown result type (might be due to invalid IL or missing references)
        //IL_1101: Unknown result type (might be due to invalid IL or missing references)
        //IL_1104: Unknown result type (might be due to invalid IL or missing references)
        //IL_1109: Unknown result type (might be due to invalid IL or missing references)
        //IL_110e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1923: Unknown result type (might be due to invalid IL or missing references)
        //IL_193f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1944: Unknown result type (might be due to invalid IL or missing references)
        //IL_1949: Unknown result type (might be due to invalid IL or missing references)
        //IL_1487: Unknown result type (might be due to invalid IL or missing references)
        //IL_148a: Unknown result type (might be due to invalid IL or missing references)
        //IL_148f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1494: Unknown result type (might be due to invalid IL or missing references)
        //IL_149f: Unknown result type (might be due to invalid IL or missing references)
        //IL_14a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_14a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_1971: Unknown result type (might be due to invalid IL or missing references)
        //IL_1976: Unknown result type (might be due to invalid IL or missing references)
        //IL_1978: Unknown result type (might be due to invalid IL or missing references)
        //IL_197d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1654: Unknown result type (might be due to invalid IL or missing references)
        //IL_1658: Unknown result type (might be due to invalid IL or missing references)
        //IL_165d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1661: Unknown result type (might be due to invalid IL or missing references)
        //IL_1667: Unknown result type (might be due to invalid IL or missing references)
        //IL_166c: Unknown result type (might be due to invalid IL or missing references)
        //IL_166e: Unknown result type (might be due to invalid IL or missing references)
        //IL_167a: Unknown result type (might be due to invalid IL or missing references)
        //IL_167f: Unknown result type (might be due to invalid IL or missing references)
        //IL_161c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1626: Unknown result type (might be due to invalid IL or missing references)
        //IL_162b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1316: Unknown result type (might be due to invalid IL or missing references)
        //IL_131d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1322: Unknown result type (might be due to invalid IL or missing references)
        //IL_121b: Unknown result type (might be due to invalid IL or missing references)
        //IL_121d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1227: Unknown result type (might be due to invalid IL or missing references)
        //IL_122c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1231: Unknown result type (might be due to invalid IL or missing references)
        //IL_1238: Unknown result type (might be due to invalid IL or missing references)
        //IL_1243: Unknown result type (might be due to invalid IL or missing references)
        //IL_1755: Unknown result type (might be due to invalid IL or missing references)
        //IL_175f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1764: Unknown result type (might be due to invalid IL or missing references)
        //IL_14fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1504: Unknown result type (might be due to invalid IL or missing references)
        //IL_1509: Unknown result type (might be due to invalid IL or missing references)
        //IL_1402: Unknown result type (might be due to invalid IL or missing references)
        //IL_1404: Unknown result type (might be due to invalid IL or missing references)
        //IL_140e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1413: Unknown result type (might be due to invalid IL or missing references)
        //IL_1418: Unknown result type (might be due to invalid IL or missing references)
        //IL_141f: Unknown result type (might be due to invalid IL or missing references)
        //IL_142a: Unknown result type (might be due to invalid IL or missing references)
        //IL_16d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_16d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_16de: Unknown result type (might be due to invalid IL or missing references)
        //IL_16e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_16ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_16f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_16f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_16fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1702: Unknown result type (might be due to invalid IL or missing references)
        //IL_1707: Unknown result type (might be due to invalid IL or missing references)
        //IL_1713: Unknown result type (might be due to invalid IL or missing references)
        //IL_17fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_1804: Unknown result type (might be due to invalid IL or missing references)
        //IL_1809: Unknown result type (might be due to invalid IL or missing references)
        //IL_178e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1798: Unknown result type (might be due to invalid IL or missing references)
        //IL_179d: Unknown result type (might be due to invalid IL or missing references)
        //IL_17b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_17e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2270: Unknown result type (might be due to invalid IL or missing references)
        //IL_2294: Unknown result type (might be due to invalid IL or missing references)
        //IL_229a: Unknown result type (might be due to invalid IL or missing references)
        //IL_22b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_22bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_22c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_21a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_21c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_21ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_21e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_21ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_21f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_173b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1288: Unknown result type (might be due to invalid IL or missing references)
        //IL_128a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1294: Unknown result type (might be due to invalid IL or missing references)
        //IL_1299: Unknown result type (might be due to invalid IL or missing references)
        //IL_129e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2054: Unknown result type (might be due to invalid IL or missing references)
        //IL_2059: Unknown result type (might be due to invalid IL or missing references)
        //IL_205b: Unknown result type (might be due to invalid IL or missing references)
        //IL_206b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2070: Unknown result type (might be due to invalid IL or missing references)
        //IL_2072: Unknown result type (might be due to invalid IL or missing references)
        //IL_208a: Unknown result type (might be due to invalid IL or missing references)
        //IL_20a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_20a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_20b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_20be: Unknown result type (might be due to invalid IL or missing references)
        //IL_20c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_20c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_20cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1afc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b27: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ab5: Unknown result type (might be due to invalid IL or missing references)
        //IL_146f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1471: Unknown result type (might be due to invalid IL or missing references)
        //IL_147b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1480: Unknown result type (might be due to invalid IL or missing references)
        //IL_1485: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bd7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1be1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1be6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b66: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b68: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b72: Unknown result type (might be due to invalid IL or missing references)
        //IL_23b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_23c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b87: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b90: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b94: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ba3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ba5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1baf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bb4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c00: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ceb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ced: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cf2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cf7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cf9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cfd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d02: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d06: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d10: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d15: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d17: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d21: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d26: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c26: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c28: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c32: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c34: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c38: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c50: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c55: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c59: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c63: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c68: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c74: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c79: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c13: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d73: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d82: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cc9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2701: Unknown result type (might be due to invalid IL or missing references)
        //IL_2704: Unknown result type (might be due to invalid IL or missing references)
        //IL_2709: Unknown result type (might be due to invalid IL or missing references)
        //IL_2767: Unknown result type (might be due to invalid IL or missing references)
        //IL_272e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2731: Unknown result type (might be due to invalid IL or missing references)
        //IL_2736: Unknown result type (might be due to invalid IL or missing references)
        //IL_2790: Unknown result type (might be due to invalid IL or missing references)
        //IL_2793: Unknown result type (might be due to invalid IL or missing references)
        //IL_2798: Unknown result type (might be due to invalid IL or missing references)
        //IL_1eb7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ebc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ec1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ec8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ecd: Unknown result type (might be due to invalid IL or missing references)
        //IL_27f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_27f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_27f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_27fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_27b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_27bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_27be: Unknown result type (might be due to invalid IL or missing references)
        //IL_27c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_27c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_27d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_27d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_27dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_27e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_27e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_27eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b82: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b87: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_28eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_28ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_28f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_28f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bb3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bba: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bbf: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bc5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bca: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bde: Unknown result type (might be due to invalid IL or missing references)
        //IL_2be8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bef: Unknown result type (might be due to invalid IL or missing references)
        //IL_2847: Unknown result type (might be due to invalid IL or missing references)
        //IL_284a: Unknown result type (might be due to invalid IL or missing references)
        //IL_284f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2854: Unknown result type (might be due to invalid IL or missing references)
        //IL_2856: Unknown result type (might be due to invalid IL or missing references)
        //IL_2858: Unknown result type (might be due to invalid IL or missing references)
        //IL_285d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2862: Unknown result type (might be due to invalid IL or missing references)
        //IL_2864: Unknown result type (might be due to invalid IL or missing references)
        //IL_2868: Unknown result type (might be due to invalid IL or missing references)
        //IL_286d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2876: Unknown result type (might be due to invalid IL or missing references)
        //IL_2881: Unknown result type (might be due to invalid IL or missing references)
        //IL_288b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2892: Unknown result type (might be due to invalid IL or missing references)
        //IL_293d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2940: Unknown result type (might be due to invalid IL or missing references)
        //IL_2945: Unknown result type (might be due to invalid IL or missing references)
        //IL_294a: Unknown result type (might be due to invalid IL or missing references)
        //IL_294c: Unknown result type (might be due to invalid IL or missing references)
        //IL_294e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2953: Unknown result type (might be due to invalid IL or missing references)
        //IL_2958: Unknown result type (might be due to invalid IL or missing references)
        //IL_295a: Unknown result type (might be due to invalid IL or missing references)
        //IL_295e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2963: Unknown result type (might be due to invalid IL or missing references)
        //IL_296c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2977: Unknown result type (might be due to invalid IL or missing references)
        //IL_2981: Unknown result type (might be due to invalid IL or missing references)
        //IL_2988: Unknown result type (might be due to invalid IL or missing references)
        //IL_29d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_29dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_29e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_29e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_29ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a31: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a42: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a47: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a54: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a70: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a76: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a90: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a96: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aa5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aaa: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aaf: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ab4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ab9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ac4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ac9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ad3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ad8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2add: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b15: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b17: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b2b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b35: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aea: Unknown result type (might be due to invalid IL or missing references)
        //IL_2af8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b02: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b07: Unknown result type (might be due to invalid IL or missing references)
        float num = 0f;
        float num12 = 0f;
        float num23 = 20f;
        float num34 = 40f;
        float num45 = 0.69f;
        if (type == 963)
        {
            if (Main.player[owner].dead)
            {
                Main.player[owner].abigailMinion = false;
            }
            if (Main.player[owner].abigailMinion)
            {
                timeLeft = 2;
            }
            originalDamage = Main.player[owner].highestAbigailCounterOriginalDamage;
            num12 = Main.player[owner].ownedProjectileCounts[970] - 1;
            num23 = Math.Max(4f, 18f - num12 * 1.75f);
            num = 1.4f;
            num34 = Math.Max(5f, num34 - num12 * 4f);
            num45 = Math.Min(1f, num45 + num12 * 0.03f);
        }
        if (type == 423)
        {
            num34 = 5f;
        }
        if (type == 373)
        {
            if (Main.player[owner].dead)
            {
                Main.player[owner].hornetMinion = false;
            }
            if (Main.player[owner].hornetMinion)
            {
                timeLeft = 2;
            }
        }
        if (type == 375)
        {
            if (Main.player[owner].dead)
            {
                Main.player[owner].impMinion = false;
            }
            if (Main.player[owner].impMinion)
            {
                timeLeft = 2;
            }
        }
        if (type == 407)
        {
            if (Main.player[owner].dead)
            {
                Main.player[owner].sharknadoMinion = false;
            }
            if (Main.player[owner].sharknadoMinion)
            {
                timeLeft = 2;
            }
        }
        if (type == 423)
        {
            if (Main.player[owner].dead)
            {
                Main.player[owner].UFOMinion = false;
            }
            if (Main.player[owner].UFOMinion)
            {
                timeLeft = 2;
            }
        }
        if (type == 613)
        {
            if (Main.player[owner].dead)
            {
                Main.player[owner].stardustMinion = false;
            }
            if (Main.player[owner].stardustMinion)
            {
                timeLeft = 2;
            }
            Lighting.AddLight(base.Center, 0.2f, 0.6f, 0.7f);
            if (localAI[1] > 0f)
            {
                localAI[1] -= 1f;
            }
        }
        if (type == 423)
        {
            if (ai[0] == 2f)
            {
                ai[1] -= 1f;
                tileCollide = false;
                if (ai[1] > 3f)
                {
                    int num48 = Dust.NewDust(base.Center, 0, 0, 220 + Main.rand.Next(2), velocity.X, velocity.Y, 100);
                    Main.dust[num48].scale = 0.5f + (float)Main.rand.NextDouble() * 0.3f;
                    Dust obj = Main.dust[num48];
                    obj.velocity /= 2.5f;
                    Main.dust[num48].noGravity = true;
                    Main.dust[num48].noLight = true;
                    Main.dust[num48].frame.Y = 80;
                }
                if (ai[1] != 0f)
                {
                    return;
                }
                ai[1] = 30f;
                ai[0] = 0f;
                velocity /= 5f;
                velocity.Y = 0f;
                extraUpdates = 0;
                numUpdates = 0;
                netUpdate = true;
                extraUpdates = 0;
                numUpdates = 0;
            }
            if (extraUpdates > 1)
            {
                extraUpdates = 0;
            }
            if (numUpdates > 1)
            {
                numUpdates = 0;
            }
        }
        Vector2 center4;
        if (type == 613)
        {
            if (ai[0] == 2f)
            {
                ai[1] -= 1f;
                tileCollide = false;
                if (ai[1] > 3f)
                {
                    if (numUpdates < 20)
                    {
                        for (int i = 0; i < 3; i++)
{
                            Dust obj2 = Main.dust[Dust.NewDust(position, width, height, 229)];
                            obj2.noGravity = true;
                            obj2.position = base.Center;
                            obj2.velocity *= 3f;
                            obj2.velocity += velocity * 3f;
                            obj2.fadeIn = 1f;
                        }
                    }
                    float num49 = 2f - (float)numUpdates / 30f;
                    if (scale > 0f)
                    {
                        float num50 = 2f;
                        for (int j = 0; (float)j < num50; j++)
{
                            Dust obj3 = Main.dust[Dust.NewDust(position, width, height, 229)];
                            obj3.noGravity = true;
                            Vector2 center3 = base.Center;
                            Vector2 unitY = Vector2.UnitY;
                            double radians = (float)numUpdates * ((float)Math.PI / 30f) + (float)whoAmI * ((float)Math.PI / 4f) + (float)Math.PI / 2f;
                            center4 = default(Vector2);
                            obj3.position = center3 + unitY.RotatedBy(radians, center4) * (float)(height / 2) - velocity * ((float)j / num50);
                            obj3.velocity = velocity / 3f;
                            obj3.fadeIn = num49 / 2f;
                            obj3.scale = num49;
                        }
                    }
                }
                if (ai[1] != 0f)
                {
                    return;
                }
                ai[1] = 30f;
                ai[0] = 0f;
                velocity /= 5f;
                velocity.Y = 0f;
                extraUpdates = 0;
                numUpdates = 0;
                netUpdate = true;
                float num51 = 15f;
                for (int k = 0; (float)k < num51; k++)
                {
                    Dust dust = Main.dust[Dust.NewDust(position, width, height, 229)];
                    dust.noGravity = true;
                    dust.position = base.Center - velocity * 5f;
                    dust.velocity *= 3f;
                    dust.velocity += velocity * 3f;
                    dust.fadeIn = 1f;
                    if (Main.rand.Next(3) != 0)
                    {
                        dust.fadeIn = 2f;
                        dust.scale = 2f;
                        dust.velocity /= 8f;
                    }
                }
                for (int l = 0; (float)l < num51; l++)
                {
                    Dust dust2 = Main.dust[Dust.NewDust(position, width, height, 229)];
                    dust2.noGravity = true;
                    dust2.position = base.Center;
                    dust2.velocity *= 3f;
                    dust2.velocity += velocity * 3f;
                    dust2.fadeIn = 1f;
                    if (Main.rand.Next(3) != 0)
                    {
                        dust2.fadeIn = 2f;
                        dust2.scale = 2f;
                        dust2.velocity /= 8f;
                    }
                }
                extraUpdates = 0;
                numUpdates = 0;
            }
            if (extraUpdates > 1)
            {
                extraUpdates = 0;
            }
            if (numUpdates > 1)
            {
                numUpdates = 0;
            }
        }
        if (type == 423 && localAI[0] > 0f)
        {
            localAI[0] -= 1f;
        }
        if (type == 613 && localAI[0] > 0f)
        {
            localAI[0] -= 1f;
        }
        float num2 = 0.05f;
        float num3 = width;
        if (type == 407)
        {
            num2 = 0.1f;
            num3 *= 2f;
        }
        for (int m = 0; m < 1000; m++)
        {
            if (m != whoAmI && Main.projectile[m].active && Main.projectile[m].owner == owner && Main.projectile[m].type == type && Math.Abs(position.X - Main.projectile[m].position.X) + Math.Abs(position.Y - Main.projectile[m].position.Y) < num3)
            {
                if (position.X < Main.projectile[m].position.X)
                {
                    velocity.X -= num2;
                }
                else
                {
                    velocity.X += num2;
                }
                if (position.Y < Main.projectile[m].position.Y)
                {
                    velocity.Y -= num2;
                }
                else
                {
                    velocity.Y += num2;
                }
            }
        }
        Vector2 vector = position;
        float num4 = 400f;
        if (type == 423)
        {
            num4 = 300f;
        }
        if (type == 613)
        {
            num4 = 300f;
        }
        num4 = 2000f;
        if (type == 963)
        {
            num4 = 700f;
        }
        bool flag = false;
        int num5 = -1;
        tileCollide = true;
        if (type == 963)
        {
            tileCollide = false;
        }
        if (type == 407)
        {
            tileCollide = false;
            if (Collision.SolidCollision(position, width, height))
            {
                alpha += 20;
                if (alpha > 150)
                {
                    alpha = 150;
                }
            }
            else
            {
                alpha -= 50;
                if (alpha < 60)
                {
                    alpha = 60;
                }
            }
        }
        if (type == 407 || type == 613 || type == 423)
        {
            Vector2 center = Main.player[owner].Center;
            Vector2 vector2 = default(Vector2);
            ((Vector2)(ref vector2))._002Ector(0.5f);
            if (type == 423)
            {
                vector2.Y = 0f;
            }
            NPC ownerMinionAttackTargetNPC = OwnerMinionAttackTargetNPC;
            if (ownerMinionAttackTargetNPC != null && ownerMinionAttackTargetNPC.CanBeChasedBy(this))
            {
                Vector2 vector3 = ownerMinionAttackTargetNPC.position + ownerMinionAttackTargetNPC.Size * vector2;
                float num6 = num4 * 3f;
                float num7 = Vector2.Distance(vector3, center);
                if (num7 < num6 && !flag && Collision.CanHitLine(position, width, height, ownerMinionAttackTargetNPC.position, ownerMinionAttackTargetNPC.width, ownerMinionAttackTargetNPC.height))
                {
                    num4 = num7;
                    vector = vector3;
                    flag = true;
                    num5 = ownerMinionAttackTargetNPC.whoAmI;
                }
            }
            if (!flag)
            {
                for (int n = 0; n < 200; n++)
                {
                    NPC nPC = Main.npc[n];
                    if (nPC.CanBeChasedBy(this))
                    {
                        Vector2 vector4 = nPC.position + nPC.Size * vector2;
                        float num8 = Vector2.Distance(vector4, center);
                        if (!(num8 >= num4) && Collision.CanHitLine(position, width, height, nPC.position, nPC.width, nPC.height))
{
                            num4 = num8;
                            vector = vector4;
                            flag = true;
                            num5 = n;
                        }
                    }
                }
            }
        }
        else
        {
            NPC ownerMinionAttackTargetNPC2 = OwnerMinionAttackTargetNPC;
            if (ownerMinionAttackTargetNPC2 != null && ownerMinionAttackTargetNPC2.CanBeChasedBy(this))
            {
                float num9 = Vector2.Distance(ownerMinionAttackTargetNPC2.Center, base.Center);
                float num10 = num4 * 3f;
                if (num9 < num10 && !flag && ((type != 963) ? Collision.CanHitLine(position, width, height, ownerMinionAttackTargetNPC2.position, ownerMinionAttackTargetNPC2.width, ownerMinionAttackTargetNPC2.height) : Collision.CanHit(base.Center, 1, 1, ownerMinionAttackTargetNPC2.Center, 1, 1)))
                {
                    num4 = num9;
                    vector = ownerMinionAttackTargetNPC2.Center;
                    flag = true;
                    num5 = ownerMinionAttackTargetNPC2.whoAmI;
                }
            }
            if (!flag)
            {
                for (int num11 = 0; num11 < 200; num11++)
                {
                    NPC nPC2 = Main.npc[num11];
                    if (nPC2.CanBeChasedBy(this))
                    {
                        float num13 = Vector2.Distance(nPC2.Center, base.Center);
                        if (!(num13 >= num4) && ((type != 963) ? Collision.CanHitLine(position, width, height, nPC2.position, nPC2.width, nPC2.height) : Collision.CanHit(base.Center, 1, 1, nPC2.Center, 1, 1)))
{
                            num4 = num13;
                            vector = nPC2.Center;
                            flag = true;
                            num5 = num11;
                        }
                    }
                }
            }
        }
        int num14 = 500;
        if (type == 963)
        {
            num14 = 800;
        }
        if (flag)
        {
            num14 = 1000;
        }
        if (flag && type == 423)
        {
            num14 = 1200;
        }
        if (flag && type == 613)
        {
            num14 = 1350;
        }
        Player player = Main.player[owner];
        if (Vector2.Distance(player.Center, base.Center) > (float)num14)
        {
            ai[0] = 1f;
            netUpdate = true;
        }
        if (ai[0] == 1f)
        {
            tileCollide = false;
        }
        bool flag2 = false;
        if (type == 963)
        {
            flag2 = true;
        }
        if (flag2)
        {
            if (ai[0] <= 1f && localAI[1] <= 0f)
            {
                localAI[1] = -1f;
            }
            else
            {
                localAI[1] = Utils.Clamp(localAI[1] + 0.05f, 0f, 1f);
                if (localAI[1] == 1f)
                {
                    localAI[1] = -1f;
                }
            }
        }
        if (type == 963 && ((Vector2)(ref velocity)).Length() > 0.1f && Main.rand.Next(1500) == 0)
        {
            SoundEngine.PlaySound(in SoundID.AbigailCry, base.Center);
        }
        bool flag3 = false;
        if (type == 423 || type == 407)
        {
            flag3 = true;
        }
        if (ai[0] >= 2f)
        {
            if (ai[0] == 2f && type == 963)
            {
                SoundEngine.PlaySound(in SoundID.AbigailAttack, base.Center);
            }
            ai[0] += 1f;
            if (flag2)
            {
                localAI[1] = ai[0] / num34;
            }
            if (!flag)
            {
                ai[0] += 1f;
            }
            if (ai[0] > num34)
            {
                ai[0] = 0f;
                netUpdate = true;
                if (flag && type == 963)
                {
                    center4 = vector - base.Center;
                    if (((Vector2)(ref center4)).Length() < 50f)
                    {
                        ai[0] = 2f;
                    }
                }
            }
            velocity *= num45;
        }
        else if (flag && (flag3 || ai[0] == 0f))
        {
            Vector2 v = vector - base.Center;
            float num15 = ((Vector2)(ref v)).Length();
            v = v.SafeNormalize(Vector2.Zero);
            if (type == 423)
            {
                v = vector - Vector2.UnitY * 80f;
                int num16 = (int)v.Y / 16;
                if (num16 < 0)
                {
                    num16 = 0;
                }
                Tile tile = Main.tile[(int)v.X / 16, num16];
                if (tile != null && tile.active() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type])
                {
                    v += Vector2.UnitY * 16f;
                    tile = Main.tile[(int)v.X / 16, (int)v.Y / 16];
                    if (tile != null && tile.active() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type])
                    {
                        v += Vector2.UnitY * 16f;
                    }
                }
                v -= base.Center;
                num15 = ((Vector2)(ref v)).Length();
                v = v.SafeNormalize(Vector2.Zero);
                if (num15 > 300f && num15 <= 800f && localAI[0] == 0f)
                {
                    ai[0] = 2f;
                    ai[1] = (int)(num15 / 10f);
                    extraUpdates = (int)ai[1];
                    velocity = v * 10f;
                    localAI[0] = 60f;
                    return;
                }
            }
            if (type == 613)
            {
                v = vector;
                Vector2 vector5 = base.Center - v;
                if (vector5 == Vector2.Zero)
                {
                    vector5 = -Vector2.UnitY;
                }
                vector5 = vector5.SafeNormalize(Vector2.Zero);
                v += vector5 * 60f;
                int num17 = (int)v.Y / 16;
                if (num17 < 0)
                {
                    num17 = 0;
                }
                Tile tile2 = Main.tile[(int)v.X / 16, num17];
                if (tile2 != null && tile2.active() && Main.tileSolid[tile2.type] && !Main.tileSolidTop[tile2.type])
                {
                    v += Vector2.UnitY * 16f;
                    tile2 = Main.tile[(int)v.X / 16, (int)v.Y / 16];
                    if (tile2 != null && tile2.active() && Main.tileSolid[tile2.type] && !Main.tileSolidTop[tile2.type])
                    {
                        v += Vector2.UnitY * 16f;
                    }
                }
                v -= base.Center;
                num15 = ((Vector2)(ref v)).Length();
                v = v.SafeNormalize(Vector2.Zero);
                if (num15 > 400f && num15 <= 800f && localAI[0] == 0f)
                {
                    ai[0] = 2f;
                    ai[1] = (int)(num15 / 10f);
                    extraUpdates = (int)ai[1];
                    velocity = v * 10f;
                    localAI[0] = 60f;
                    return;
                }
            }
            if (type == 407)
            {
                if (num15 > 400f)
                {
                    float num18 = 3f;
                    v *= num18;
                    velocity = (velocity * 20f + v) / 21f;
                }
                else
                {
                    velocity *= 0.96f;
                }
            }
            if (num15 > 200f)
            {
                float num19 = 6f + num12 * num;
                v *= num19;
                float num20 = num23 * 2f;
                velocity.X = (velocity.X * num20 + v.X) / (num20 + 1f);
                velocity.Y = (velocity.Y * num20 + v.Y) / (num20 + 1f);
            }
            else if (type == 963)
            {
                if (num15 < 50f)
                {
                    velocity *= 0.5f;
                    ai[0] = 2f;
                    netUpdate = true;
                }
                else
                {
                    float num21 = 4f + num12 * num;
                    v *= num21;
                    velocity = (velocity * num23 + v) / (num23 + 1f);
                }
            }
            else if (type == 423 || type == 613)
            {
                if (num15 > 70f && num15 < 130f)
                {
                    float num22 = 7f;
                    if (num15 < 100f)
                    {
                        num22 = -3f;
                    }
                    v *= num22;
                    velocity = (velocity * 20f + v) / 21f;
                    if (Math.Abs(v.X) > Math.Abs(v.Y))
                    {
                        velocity.X = (velocity.X * 10f + v.X) / 11f;
                    }
                }
                else
                {
                    velocity *= 0.97f;
                }
            }
            else if (type == 375)
            {
                if (num15 < 150f)
                {
                    float num24 = 4f;
                    v *= 0f - num24;
                    velocity.X = (velocity.X * 40f + v.X) / 41f;
                    velocity.Y = (velocity.Y * 40f + v.Y) / 41f;
                }
                else
                {
                    velocity *= 0.97f;
                }
            }
            else if (velocity.Y > -1f)
            {
                velocity.Y -= 0.1f;
            }
        }
        else
        {
            if (type != 963 && !Collision.CanHitLine(base.Center, 1, 1, Main.player[owner].Center, 1, 1))
            {
                ai[0] = 1f;
            }
            float num25 = 6f;
            if (ai[0] == 1f)
            {
                num25 = 15f;
            }
            if (type == 407)
            {
                num25 = 9f;
            }
            if (type == 963)
            {
                num25 *= 0.8f;
            }
            Vector2 center2 = base.Center;
            Vector2 v2 = player.Center - center2 + new Vector2(0f, -60f);
            if (type == 407)
            {
                v2 += new Vector2(0f, 40f);
            }
            if (type == 963)
            {
                v2 += new Vector2((float)(-40 * Main.player[owner].direction), 40f);
            }
            if (type == 375)
            {
                ai[1] = 80f;
                netUpdate = true;
                v2 = player.Center - center2;
                int num26 = 1;
                for (int num27 = 0; num27 < whoAmI; num27++)
                {
                    if (Main.projectile[num27].active && Main.projectile[num27].owner == owner && Main.projectile[num27].type == type)
                    {
                        num26++;
                    }
                }
                v2.X -= 10 * Main.player[owner].direction;
                v2.X -= num26 * 40 * Main.player[owner].direction;
                v2.Y -= 10f;
            }
            float num28 = ((Vector2)(ref v2)).Length();
            if (num28 > 200f && num25 < 9f)
            {
                num25 = 9f;
            }
            if ((type == 423 || type == 407) && num28 > 300f && num25 < 12f)
            {
                num25 = 12f;
            }
            if (type == 375)
            {
                num25 = (int)((double)num25 * 0.75);
            }
            if (num28 < 100f && ai[0] == 1f && !Collision.SolidCollision(position, width, height))
            {
                ai[0] = 0f;
                netUpdate = true;
            }
            if (num28 > 2000f)
            {
                position.X = Main.player[owner].Center.X - (float)(width / 2);
                position.Y = Main.player[owner].Center.Y - (float)(width / 2);
            }
            if (type == 375 || type == 963)
            {
                if (num28 > 10f)
                {
                    v2 = v2.SafeNormalize(Vector2.Zero);
                    if (num28 < 50f)
                    {
                        num25 /= 2f;
                    }
                    v2 *= num25;
                    velocity = (velocity * 20f + v2) / 21f;
                }
                else
                {
                    direction = Main.player[owner].direction;
                    velocity *= 0.9f;
                }
            }
            else if (type == 407)
            {
                if (Math.Abs(v2.X) > 40f || Math.Abs(v2.Y) > 10f)
                {
                    v2 = v2.SafeNormalize(Vector2.Zero);
                    v2 *= num25;
                    v2 *= new Vector2(1.25f, 0.65f);
                    velocity = (velocity * 20f + v2) / 21f;
                }
                else
                {
                    if (velocity.X == 0f && velocity.Y == 0f)
                    {
                        velocity.X = -0.15f;
                        velocity.Y = -0.05f;
                    }
                    velocity *= 1.01f;
                }
            }
            else if (num28 > 70f)
            {
                v2 = v2.SafeNormalize(Vector2.Zero);
                v2 *= num25;
                velocity = (velocity * 20f + v2) / 21f;
            }
            else
            {
                if (velocity.X == 0f && velocity.Y == 0f)
                {
                    velocity.X = -0.15f;
                    velocity.Y = -0.05f;
                }
                velocity *= 1.01f;
            }
            if (num28 > 250f && (type == 423 || type == 407))
            {
                float x = Main.player[owner].velocity.X;
                float y = Main.player[owner].velocity.Y;
                if ((velocity.X < 0f && x >= 0f) || (velocity.X >= 0f && x < 0f))
                {
                    velocity.X *= 0.95f;
                }
                else
                {
                    velocity.X += x * 0.125f;
                }
                if ((velocity.Y < 0f && y >= 0f) || (velocity.Y >= 0f && y < 0f))
                {
                    velocity.Y *= 0.95f;
                }
                else
                {
                    velocity.Y += y * 0.125f;
                }
                if (((Vector2)(ref velocity)).Length() > num25)
                {
                    velocity = velocity.SafeNormalize(Vector2.Zero) * num25;
                }
            }
        }
        rotation = velocity.X * 0.05f;
        frameCounter++;
        if (type == 373)
        {
            if (frameCounter > 1)
            {
                frame++;
                frameCounter = 0;
            }
            if (frame > 2)
            {
                frame = 0;
            }
        }
        if (type == 963)
        {
            if (ai[0] >= 2f)
            {
                int num29 = 12;
                if (frame < 8)
                {
                    frameCounter = 0;
                }
                frameCounter++;
                frame = frameCounter / num29;
                if (frame > 6)
                {
                    frameCounter = 0;
                    frame = 5;
                }
                switch (frame)
                {
                case 0:
                case 1:
                case 2:
                    frame = 8 + frame;
                    break;
                case 3:
                case 5:
                case 7:
                    frame = 11;
                    break;
                default:
                    frame = 12;
                    break;
                }
                if (Main.rand.Next(2) == 0)
                {
                    float num30 = 1.1f + Main.rand.NextFloat() * 0.3f;
                    float num31 = 1.4f + Main.rand.NextFloat() * 0.4f;
                    Vector2 vector6 = Main.rand.NextVector2CircularEdge((float)width * num30, (0f - (float)height) * 0.25f * num30);
                    float num32 = vector6.ToRotation() + (float)Math.PI / 2f;
                    int num33 = Dust.NewDust(base.Bottom + vector6, 1, 1, 303, 0f, 0f, 50, Color.GhostWhite, num31);
                    Main.dust[num33].velocity = vector6 * 0.0125f + Utils.RotatedBy(new Vector2(1f, 0f), num32, Vector2.Zero);
                    Main.dust[num33].noGravity = true;
                }
            }
            else
            {
                if (frame > 7)
                {
                    frame = 0;
                    frameCounter = 0;
                }
                if (frameCounter > 6)
                {
                    frameCounter = 0;
                    frame++;
                    if (frame > 7)
                    {
                        frame = 0;
                    }
                }
            }
        }
        if (type == 375)
        {
            if (frameCounter >= 16)
            {
                frameCounter = 0;
            }
            frame = frameCounter / 4;
            if (ai[1] > 0f && ai[1] < 16f)
            {
                frame += 4;
            }
            if (Main.rand.Next(6) == 0)
            {
                int num35 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2f);
                Dust obj4 = Main.dust[num35];
                obj4.velocity *= 0.3f;
                Main.dust[num35].noGravity = true;
                Main.dust[num35].noLight = true;
            }
        }
        if (type == 407)
        {
            int num36 = 2;
            if (frameCounter >= 6 * num36)
            {
                frameCounter = 0;
            }
            frame = frameCounter / num36;
            if (Main.rand.Next(5) == 0)
            {
                int num37 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 217, 0f, 0f, 100, default(Color), 2f);
                Dust obj5 = Main.dust[num37];
                obj5.velocity *= 0.3f;
                Main.dust[num37].noGravity = true;
                Main.dust[num37].noLight = true;
            }
        }
        if (type == 423 || type == 613)
        {
            int num38 = 3;
            if (frameCounter >= 4 * num38)
            {
                frameCounter = 0;
            }
            frame = frameCounter / num38;
        }
        if (velocity.X > 0f)
        {
            spriteDirection = (direction = -1);
        }
        else if (velocity.X < 0f)
        {
            spriteDirection = (direction = 1);
        }
        if (type == 963)
        {
            spriteDirection = (direction *= -1);
            if (!flag && Math.Abs(velocity.X) < 0.1f)
            {
                spriteDirection = ((Main.player[owner].Center.X > base.Center.X) ? 1 : (-1));
            }
        }
        if (type == 373)
        {
            if (ai[1] > 0f)
            {
                ai[1] += Main.rand.Next(1, 4);
            }
            int num39 = 90;
            if (Main.player[owner].strongBees)
            {
                num39 = 70;
            }
            if (ai[1] > (float)num39)
            {
                ai[1] = 0f;
                netUpdate = true;
            }
        }
        else if (type == 375)
        {
            if (ai[1] > 0f)
            {
                ai[1] += 1f;
                if (Main.rand.Next(3) == 0)
                {
                    ai[1] += 1f;
                }
            }
            if (ai[1] > 90f)
            {
                ai[1] = 0f;
                netUpdate = true;
            }
        }
        else if (type == 407)
        {
            if (ai[1] > 0f)
            {
                ai[1] += 1f;
                if (Main.rand.Next(3) != 0)
                {
                    ai[1] += 1f;
                }
            }
            if (ai[1] > 50f)
            {
                ai[1] = 0f;
                netUpdate = true;
            }
        }
        else if (type == 423)
        {
            if (ai[1] > 0f)
            {
                ai[1] += 1f;
                if (Main.rand.Next(3) != 0)
                {
                    ai[1] += 1f;
                }
            }
            if (ai[1] > 40f)
            {
                ai[1] = 0f;
                netUpdate = true;
            }
        }
        else if (type == 613)
        {
            if (ai[1] > 0f)
            {
                ai[1] += 1f;
                if (Main.rand.Next(3) != 0)
                {
                    ai[1] += 1f;
                }
            }
            if (ai[1] > 60f)
            {
                ai[1] = 0f;
                netUpdate = true;
            }
        }
        if (!flag3 && ai[0] != 0f)
        {
            return;
        }
        float num40 = 0f;
        int num41 = 0;
        if (type == 373)
        {
            num40 = 10f;
            num41 = 374;
        }
        else if (type == 375)
        {
            num40 = 11f;
            num41 = 376;
        }
        else if (type == 407)
        {
            num40 = 20f;
            num41 = 408;
        }
        else if (type == 423)
        {
            num40 = 4f;
            num41 = 433;
        }
        else if (type == 613)
        {
            num40 = 14f;
            num41 = 614;
        }
        if (!flag)
        {
            return;
        }
        if (type == 375)
        {
            if ((vector - base.Center).X > 0f)
            {
                spriteDirection = (direction = -1);
            }
            else if ((vector - base.Center).X < 0f)
            {
                spriteDirection = (direction = 1);
            }
        }
        if (type == 407 && Collision.SolidCollision(position, width, height))
        {
            return;
        }
        if (type == 423)
        {
            if (Math.Abs((vector - base.Center).ToRotation() - (float)Math.PI / 2f) > (float)Math.PI / 4f)
            {
                velocity += (vector - base.Center - Vector2.UnitY * 80f).SafeNormalize(Vector2.Zero);
            }
            center4 = vector - base.Center;
            if (!(((Vector2)(ref center4)).Length() > 400f) && ai[1] == 0f)
            {
                ai[1] += 1f;
                if (Main.myPlayer == owner)
                {
                    Vector2 v3 = vector - base.Center;
                    v3 = v3.SafeNormalize(Vector2.Zero);
                    v3 *= num40;
                    NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, v3.X, v3.Y, num41, damage, knockBack, Main.myPlayer);
                    netUpdate = true;
                }
            }
        }
        else if (ai[1] == 0f && type == 613)
        {
            center4 = vector - base.Center;
            if (((Vector2)(ref center4)).Length() > 500f || ai[1] != 0f)
            {
                return;
            }
            ai[1] += 1f;
            if (Main.myPlayer == owner)
            {
                Vector2 v4 = vector - base.Center;
                v4 = v4.SafeNormalize(Vector2.Zero);
                v4 *= num40;
                int num42 = NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, v4.X, v4.Y, num41, damage, knockBack, Main.myPlayer, 0f, num5);
                Main.projectile[num42].timeLeft = 300;
                Main.projectile[num42].netUpdate = true;
                velocity -= v4 / 3f;
                netUpdate = true;
            }
            for (int num43 = 0; num43 < 5; num43++)
            {
                int num44 = width / 4;
                _ = ((float)Main.rand.NextDouble() * ((float)Math.PI * 2f)).ToRotationVector2() * (float)Main.rand.Next(24, 41) / 8f;
                int num46 = Dust.NewDust(base.Center - Vector2.One * (float)num44, num44 * 2, num44 * 2, 88);
                Dust dust3 = Main.dust[num46];
                Vector2 vector7 = (dust3.position - base.Center).SafeNormalize(Vector2.Zero);
                dust3.position = base.Center + vector7 * (float)num44 * scale - new Vector2(4f);
                if (num43 < 30)
                {
                    dust3.velocity = vector7 * ((Vector2)(ref dust3.velocity)).Length() * 2f;
                }
                else
                {
                    dust3.velocity = 2f * vector7 * (float)Main.rand.Next(45, 91) / 10f;
                }
                dust3.noGravity = true;
                dust3.scale = 0.7f + Main.rand.NextFloat();
            }
        }
        else if (ai[1] == 0f)
        {
            Vector2 v5 = vector - base.Center;
            ai[1] += 1f;
            if (Main.myPlayer == owner)
            {
                v5 = v5.SafeNormalize(Vector2.Zero);
                v5 *= num40;
                int num47 = NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, v5.X, v5.Y, num41, damage, knockBack, Main.myPlayer);
                Main.projectile[num47].timeLeft = 300;
                Main.projectile[num47].netUpdate = true;
                netUpdate = true;
            }
        }
    }
References Terraria.ID.SoundID.AbigailAttack, Terraria.ID.SoundID.AbigailCry, Terraria.Player.abigailMinion, Terraria.Entity.active, Terraria.Tile.active(), Terraria.Lighting.AddLight(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Entity.Center, Terraria.Player.dead, Terraria.Entity.direction, Terraria.Main.dust, Terraria.Dust.frame, Terraria.Player.highestAbigailCounterOriginalDamage, Terraria.Player.hornetMinion, Terraria.Player.impMinion, Terraria.Main.myPlayer, Terraria.Projectile.netUpdate, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Main.npc, Terraria.Player.ownedProjectileCounts, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Utils.RotatedBy(), Terraria.Dust.scale, Terraria.Player.sharknadoMinion, Terraria.Collision.SolidCollision(), Terraria.Player.stardustMinion, Terraria.Player.strongBees, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Projectile.timeLeft, Terraria.Projectile.type, Terraria.Tile.type, Terraria.Player.UFOMinion, Terraria.Dust.velocity, and Terraria.Entity.velocity.