TModLoader: Terraria.Projectile.AI_099_2
AI_099_2()
void Terraria.Projectile.AI_099_2 () inline private
    {
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_0469: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0304: Unknown result type (might be due to invalid IL or missing references)
        //IL_030b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_0319: Unknown result type (might be due to invalid IL or missing references)
        //IL_0323: Unknown result type (might be due to invalid IL or missing references)
        //IL_032c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0336: Unknown result type (might be due to invalid IL or missing references)
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0345: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0533: Unknown result type (might be due to invalid IL or missing references)
        //IL_0552: Unknown result type (might be due to invalid IL or missing references)
        //IL_0558: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        //IL_0292: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02db: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b78: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b82: Unknown result type (might be due to invalid IL or missing references)
        //IL_0685: Unknown result type (might be due to invalid IL or missing references)
        //IL_068b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0690: Unknown result type (might be due to invalid IL or missing references)
        //IL_0695: Unknown result type (might be due to invalid IL or missing references)
        //IL_065f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0669: Unknown result type (might be due to invalid IL or missing references)
        //IL_066e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bbc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bde: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_072e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0738: Unknown result type (might be due to invalid IL or missing references)
        //IL_073d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0742: Unknown result type (might be due to invalid IL or missing references)
        //IL_0747: Unknown result type (might be due to invalid IL or missing references)
        //IL_075a: Unknown result type (might be due to invalid IL or missing references)
        //IL_076b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0770: Unknown result type (might be due to invalid IL or missing references)
        //IL_0775: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0915: Unknown result type (might be due to invalid IL or missing references)
        //IL_0789: Unknown result type (might be due to invalid IL or missing references)
        //IL_078d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0792: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0948: Unknown result type (might be due to invalid IL or missing references)
        //IL_095e: Unknown result type (might be due to invalid IL or missing references)
        //IL_07df: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a54: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a58: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a71: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a76: Unknown result type (might be due to invalid IL or missing references)
        //IL_0991: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0814: Unknown result type (might be due to invalid IL or missing references)
        //IL_081e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0823: Unknown result type (might be due to invalid IL or missing references)
        //IL_0831: Unknown result type (might be due to invalid IL or missing references)
        //IL_0836: Unknown result type (might be due to invalid IL or missing references)
        //IL_0838: Unknown result type (might be due to invalid IL or missing references)
        //IL_083d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0abb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0acc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ace: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3e: Unknown result type (might be due to invalid IL or missing references)
        bool flag = false;
        for (int i = 0; i < whoAmI; i++)
        {
            if (Main.projectile[i].active && Main.projectile[i].owner == owner && Main.projectile[i].type == type)
            {
                flag = true;
            }
        }
        if (owner == Main.myPlayer)
        {
            localAI[0] += 1f;
            if (flag)
            {
                localAI[0] += (float)Main.rand.Next(10, 31) * 0.1f;
            }
            float num = localAI[0] / 60f;
            num /= (1f + Main.player[owner].inverseMeleeSpeed) / 2f;
            float num8 = ProjectileID.Sets.YoyosLifeTimeMultiplier[type];
            if (num8 != -1f && num > num8)
            {
                ai[0] = -1f;
            }
        }
        if (type == 603 && owner == Main.myPlayer)
        {
            localAI[1] += 1f;
            if (localAI[1] >= 6f)
            {
                float num9 = 400f;
                Vector2 vector = velocity;
                Vector2 vector2 = default(Vector2);
                ((Vector2)(ref vector2))._002Ector((float)Main.rand.Next(-100, 101), (float)Main.rand.Next(-100, 101));
                ((Vector2)(ref vector2)).Normalize();
                vector2 *= (float)Main.rand.Next(10, 41) * 0.1f;
                if (Main.rand.Next(3) == 0)
                {
                    vector2 *= 2f;
                }
                vector *= 0.25f;
                vector += vector2;
                for (int j = 0; j < 200; j++)
                {
                    if (Main.npc[j].CanBeChasedBy(this))
                    {
                        float num10 = Main.npc[j].position.X + (float)(Main.npc[j].width / 2);
                        float num11 = Main.npc[j].position.Y + (float)(Main.npc[j].height / 2);
                        float num12 = Math.Abs(position.X + (float)(width / 2) - num10) + Math.Abs(position.Y + (float)(height / 2) - num11);
                        if (num12 < num9 && Collision.CanHit(position, width, height, Main.npc[j].position, Main.npc[j].width, Main.npc[j].height))
{
                            num9 = num12;
                            vector.X = num10;
                            vector.Y = num11;
                            vector -= base.Center;
                            ((Vector2)(ref vector)).Normalize();
                            vector *= 8f;
                        }
                    }
                }
                vector *= 0.8f;
                NewProjectile(GetProjectileSource_FromThis(), base.Center.X - vector.X, base.Center.Y - vector.Y, vector.X, vector.Y, 604, damage, knockBack, owner);
                localAI[1] = 0f;
            }
        }
        bool flag2 = false;
        if (type >= 556 && type <= 561)
        {
            flag2 = true;
        }
        if (Main.player[owner].dead)
        {
            Kill();
            return;
        }
        if (!flag2 && !flag)
        {
            Main.player[owner].heldProj = whoAmI;
            Main.player[owner].SetDummyItemTime(2);
            if (position.X + (float)(width / 2) > Main.player[owner].position.X + (float)(Main.player[owner].width / 2))
            {
                Main.player[owner].ChangeDir(1);
                direction = 1;
            }
            else
            {
                Main.player[owner].ChangeDir(-1);
                direction = -1;
            }
        }
        if (velocity.HasNaNs())
        {
            Kill();
        }
        timeLeft = 6;
        float num13 = 10f;
        float num14 = 10f;
        float num15 = 3f;
        float num2 = 200f;
        num2 = ProjectileID.Sets.YoyosMaximumRange[type];
        num14 = ProjectileID.Sets.YoyosTopSpeed[type];
        if (type == 545)
        {
            if (Main.rand.Next(6) == 0)
            {
                int num3 = Dust.NewDust(position, width, height, 6);
                Main.dust[num3].noGravity = true;
            }
        }
        else if (type == 553 && Main.rand.Next(2) == 0)
        {
            int num4 = Dust.NewDust(position, width, height, 6);
            Main.dust[num4].noGravity = true;
            Main.dust[num4].scale = 1.6f;
        }
        if (Main.player[owner].yoyoString)
        {
            num2 = num2 * 1.25f + 30f;
        }
        num2 /= (1f + Main.player[owner].inverseMeleeSpeed * 3f) / 4f;
        num14 /= (1f + Main.player[owner].inverseMeleeSpeed * 3f) / 4f;
        num13 = 14f - num14 / 2f;
        if (num13 < 1f)
        {
            num13 = 1f;
        }
        if (num13 < 1.01f)
        {
            num13 = 1.01f;
        }
        num15 = 5f + num14 / 2f;
        if (flag)
        {
            num15 += 20f;
        }
        if (ai[0] >= 0f)
        {
            if (((Vector2)(ref velocity)).Length() > num14)
            {
                velocity *= 0.98f;
            }
            bool flag3 = false;
            bool flag4 = false;
            Vector2 vector3 = Main.player[owner].Center - base.Center;
            if (((Vector2)(ref vector3)).Length() > num2)
            {
                flag3 = true;
                if ((double)((Vector2)(ref vector3)).Length() > (double)num2 * 1.3)
                {
                    flag4 = true;
                }
            }
            if (owner == Main.myPlayer)
            {
                if (!Main.player[owner].channel || Main.player[owner].stoned || Main.player[owner].frozen)
                {
                    ai[0] = -1f;
                    ai[1] = 0f;
                    netUpdate = true;
                }
                else
                {
                    Vector2 val = Main.ReverseGravitySupport(Main.MouseScreen) + Main.screenPosition;
                    float x = val.X;
                    float y = val.Y;
                    Vector2 vector4 = new Vector2(x, y) - Main.player[owner].Center;
                    if (((Vector2)(ref vector4)).Length() > num2)
                    {
                        ((Vector2)(ref vector4)).Normalize();
                        vector4 *= num2;
                        vector4 = Main.player[owner].Center + vector4;
                        x = vector4.X;
                        y = vector4.Y;
                    }
                    if (ai[0] != x || ai[1] != y)
                    {
                        Vector2 vector5 = new Vector2(x, y) - Main.player[owner].Center;
                        if (((Vector2)(ref vector5)).Length() > num2 - 1f)
{
                            ((Vector2)(ref vector5)).Normalize();
                            vector5 *= num2 - 1f;
                            Vector2 val2 = Main.player[owner].Center + vector5;
                            x = val2.X;
                            y = val2.Y;
                        }
                        ai[0] = x;
                        ai[1] = y;
                        netUpdate = true;
                    }
                }
            }
            if (flag4 && owner == Main.myPlayer)
            {
                ai[0] = -1f;
                netUpdate = true;
            }
            if (ai[0] >= 0f)
            {
                if (flag3)
                {
                    num13 /= 2f;
                    num14 *= 2f;
                    if (base.Center.X > Main.player[owner].Center.X && velocity.X > 0f)
                    {
                        velocity.X *= 0.5f;
                    }
                    if (base.Center.Y > Main.player[owner].Center.Y && velocity.Y > 0f)
                    {
                        velocity.Y *= 0.5f;
                    }
                    if (base.Center.X < Main.player[owner].Center.X && velocity.X < 0f)
                    {
                        velocity.X *= 0.5f;
                    }
                    if (base.Center.Y < Main.player[owner].Center.Y && velocity.Y < 0f)
                    {
                        velocity.Y *= 0.5f;
                    }
                }
                Vector2 vector6 = new Vector2(ai[0], ai[1]) - base.Center;
                if (flag3)
                {
                    num13 = 1f;
                }
                ((Vector2)(ref velocity)).Length();
                float num5 = ((Vector2)(ref vector6)).Length();
                if (num5 > num15)
                {
                    ((Vector2)(ref vector6)).Normalize();
                    float num6 = Math.Min(num5 / 2f, num14);
                    if (flag3)
                    {
                        num6 = Math.Min(num6, num14 / 2f);
                    }
                    vector6 *= num6;
                    velocity = (velocity * (num13 - 1f) + vector6) / num13;
                }
                else if (flag)
                {
                    if ((double)((Vector2)(ref velocity)).Length() < (double)num14 * 0.6)
                    {
                        vector6 = velocity;
                        ((Vector2)(ref vector6)).Normalize();
                        vector6 *= num14 * 0.6f;
                        velocity = (velocity * (num13 - 1f) + vector6) / num13;
                    }
                }
                else
                {
                    velocity *= 0.8f;
                }
                if (flag && !flag3 && (double)((Vector2)(ref velocity)).Length() < (double)num14 * 0.6)
                {
                    ((Vector2)(ref velocity)).Normalize();
                    velocity *= num14 * 0.6f;
                }
            }
        }
        else
        {
            num13 = (int)((double)num13 * 0.8);
            num14 *= 1.5f;
            tileCollide = false;
            Vector2 vector7 = Main.player[owner].Center - base.Center;
            float num7 = ((Vector2)(ref vector7)).Length();
            if (num7 < num14 + 10f || num7 == 0f || num7 > 2000f)
            {
                Kill();
            }
            else
            {
                ((Vector2)(ref vector7)).Normalize();
                vector7 *= num14;
                velocity = (velocity * (num13 - 1f) + vector7) / num13;
            }
        }
        rotation += 0.45f;
    }
References Terraria.Entity.active, Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Player.ChangeDir(), Terraria.Player.channel, Terraria.Player.dead, Terraria.Main.dust, Terraria.Player.frozen, Terraria.Entity.height, Terraria.Player.heldProj, Terraria.Player.inverseMeleeSpeed, Terraria.Main.MouseScreen, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.npc, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Main.ReverseGravitySupport(), Terraria.Dust.scale, Terraria.Main.screenPosition, Terraria.Player.SetDummyItemTime(), Terraria.Player.stoned, Terraria.Projectile.type, Terraria.Entity.width, Terraria.ID.ProjectileID.Sets.YoyosLifeTimeMultiplier, Terraria.ID.ProjectileID.Sets.YoyosMaximumRange, Terraria.ID.ProjectileID.Sets.YoyosTopSpeed, and Terraria.Player.yoyoString.