TModLoader: Terraria.Projectile.Damage
Damage()
void Terraria.Projectile.Damage () inline
    {
        //IL_06c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_072c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0702: Unknown result type (might be due to invalid IL or missing references)
        //IL_4df2: Unknown result type (might be due to invalid IL or missing references)
        //IL_4c81: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ce2: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ce7: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ce9: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cfd: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d05: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f34: Unknown result type (might be due to invalid IL or missing references)
        //IL_4fa5: Unknown result type (might be due to invalid IL or missing references)
        //IL_4fab: Unknown result type (might be due to invalid IL or missing references)
        //IL_4fb1: Unknown result type (might be due to invalid IL or missing references)
        //IL_4881: Unknown result type (might be due to invalid IL or missing references)
        //IL_4884: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0baa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0baf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb4: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ad3: Unknown result type (might be due to invalid IL or missing references)
        //IL_4adf: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ae9: Unknown result type (might be due to invalid IL or missing references)
        //IL_477e: Unknown result type (might be due to invalid IL or missing references)
        //IL_478b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4790: Unknown result type (might be due to invalid IL or missing references)
        //IL_4795: Unknown result type (might be due to invalid IL or missing references)
        //IL_4b27: Unknown result type (might be due to invalid IL or missing references)
        //IL_4b33: Unknown result type (might be due to invalid IL or missing references)
        //IL_4a9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_4aa6: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ab0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e50: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e59: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e05: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e44: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1350: Unknown result type (might be due to invalid IL or missing references)
        //IL_1318: Unknown result type (might be due to invalid IL or missing references)
        //IL_1325: Unknown result type (might be due to invalid IL or missing references)
        //IL_132a: Unknown result type (might be due to invalid IL or missing references)
        //IL_132f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1075: Unknown result type (might be due to invalid IL or missing references)
        //IL_107f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fcb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fcf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1000: Unknown result type (might be due to invalid IL or missing references)
        //IL_1019: Unknown result type (might be due to invalid IL or missing references)
        //IL_101b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1022: Unknown result type (might be due to invalid IL or missing references)
        //IL_1028: Unknown result type (might be due to invalid IL or missing references)
        //IL_103b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1040: Unknown result type (might be due to invalid IL or missing references)
        //IL_1045: Unknown result type (might be due to invalid IL or missing references)
        //IL_1053: Unknown result type (might be due to invalid IL or missing references)
        //IL_106c: Unknown result type (might be due to invalid IL or missing references)
        //IL_106e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1160: Unknown result type (might be due to invalid IL or missing references)
        //IL_1165: Unknown result type (might be due to invalid IL or missing references)
        //IL_11bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_118e: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_11a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_11a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1203: Unknown result type (might be due to invalid IL or missing references)
        //IL_1205: Unknown result type (might be due to invalid IL or missing references)
        //IL_125e: Unknown result type (might be due to invalid IL or missing references)
        //IL_127a: Unknown result type (might be due to invalid IL or missing references)
        //IL_127f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c06: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c10: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c91: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c96: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d72: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d77: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a34: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a39: Unknown result type (might be due to invalid IL or missing references)
        //IL_1af2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1af7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ab0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ab5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1efb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f01: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f06: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f10: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f15: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_22f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2303: Unknown result type (might be due to invalid IL or missing references)
        //IL_220e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2211: Unknown result type (might be due to invalid IL or missing references)
        //IL_221b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2220: Unknown result type (might be due to invalid IL or missing references)
        //IL_2225: Unknown result type (might be due to invalid IL or missing references)
        //IL_222e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2245: Unknown result type (might be due to invalid IL or missing references)
        //IL_224a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2267: Unknown result type (might be due to invalid IL or missing references)
        //IL_2272: Unknown result type (might be due to invalid IL or missing references)
        //IL_227c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2283: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e63: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e68: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e77: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e82: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e87: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e91: Unknown result type (might be due to invalid IL or missing references)
        //IL_237d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2383: Unknown result type (might be due to invalid IL or missing references)
        //IL_2388: Unknown result type (might be due to invalid IL or missing references)
        //IL_2392: Unknown result type (might be due to invalid IL or missing references)
        //IL_2397: Unknown result type (might be due to invalid IL or missing references)
        //IL_203f: Unknown result type (might be due to invalid IL or missing references)
        //IL_204a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2511: Unknown result type (might be due to invalid IL or missing references)
        //IL_2529: Unknown result type (might be due to invalid IL or missing references)
        //IL_253f: Unknown result type (might be due to invalid IL or missing references)
        //IL_265b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2678: Unknown result type (might be due to invalid IL or missing references)
        //IL_26f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_26f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_26fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_2702: Unknown result type (might be due to invalid IL or missing references)
        //IL_256e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2575: Unknown result type (might be due to invalid IL or missing references)
        //IL_257a: Unknown result type (might be due to invalid IL or missing references)
        //IL_257f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2591: Unknown result type (might be due to invalid IL or missing references)
        //IL_259b: Unknown result type (might be due to invalid IL or missing references)
        //IL_25a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_25a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_25ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_25b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_25b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_25ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_25dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_25f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2953: Unknown result type (might be due to invalid IL or missing references)
        //IL_2959: Unknown result type (might be due to invalid IL or missing references)
        //IL_295e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2963: Unknown result type (might be due to invalid IL or missing references)
        //IL_296c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2970: Unknown result type (might be due to invalid IL or missing references)
        //IL_2975: Unknown result type (might be due to invalid IL or missing references)
        //IL_2978: Unknown result type (might be due to invalid IL or missing references)
        //IL_297a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2984: Unknown result type (might be due to invalid IL or missing references)
        //IL_2989: Unknown result type (might be due to invalid IL or missing references)
        //IL_304f: Unknown result type (might be due to invalid IL or missing references)
        //IL_305b: Unknown result type (might be due to invalid IL or missing references)
        //IL_30b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_30be: Unknown result type (might be due to invalid IL or missing references)
        //IL_30eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_30f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ea4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ea9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2eae: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ec5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ec9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ece: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e17: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e21: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b10: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_34fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_3501: Unknown result type (might be due to invalid IL or missing references)
        //IL_3506: Unknown result type (might be due to invalid IL or missing references)
        //IL_350b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3510: Unknown result type (might be due to invalid IL or missing references)
        //IL_351a: Unknown result type (might be due to invalid IL or missing references)
        //IL_351f: Unknown result type (might be due to invalid IL or missing references)
        //IL_353a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3545: Unknown result type (might be due to invalid IL or missing references)
        //IL_354f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3556: Unknown result type (might be due to invalid IL or missing references)
        //IL_35cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_35d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_35e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_3662: Unknown result type (might be due to invalid IL or missing references)
        //IL_366e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3678: Unknown result type (might be due to invalid IL or missing references)
        //IL_3628: Unknown result type (might be due to invalid IL or missing references)
        //IL_3634: Unknown result type (might be due to invalid IL or missing references)
        //IL_363e: Unknown result type (might be due to invalid IL or missing references)
        //IL_38b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_38ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_38de: Unknown result type (might be due to invalid IL or missing references)
        //IL_38e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_38e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_38ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_38f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_38f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_38fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_3902: Unknown result type (might be due to invalid IL or missing references)
        //IL_391a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3921: Unknown result type (might be due to invalid IL or missing references)
        //IL_3928: Unknown result type (might be due to invalid IL or missing references)
        //IL_392f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3961: Unknown result type (might be due to invalid IL or missing references)
        //IL_3968: Unknown result type (might be due to invalid IL or missing references)
        //IL_396f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3976: Unknown result type (might be due to invalid IL or missing references)
        //IL_39a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_39af: Unknown result type (might be due to invalid IL or missing references)
        //IL_39b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_39bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a90: Unknown result type (might be due to invalid IL or missing references)
        //IL_3d0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3d17: Unknown result type (might be due to invalid IL or missing references)
        //IL_4271: Unknown result type (might be due to invalid IL or missing references)
        //IL_427e: Unknown result type (might be due to invalid IL or missing references)
        //IL_4283: Unknown result type (might be due to invalid IL or missing references)
        //IL_4288: Unknown result type (might be due to invalid IL or missing references)
        //IL_4586: Unknown result type (might be due to invalid IL or missing references)
        //IL_4605: Unknown result type (might be due to invalid IL or missing references)
        //IL_460a: Unknown result type (might be due to invalid IL or missing references)
        //IL_4612: Unknown result type (might be due to invalid IL or missing references)
        //IL_4617: Unknown result type (might be due to invalid IL or missing references)
        //IL_46b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_46c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_46c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_46cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_46d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_46ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_46f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_46f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_4717: Unknown result type (might be due to invalid IL or missing references)
        //IL_4732: Unknown result type (might be due to invalid IL or missing references)
        //IL_4737: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fe8: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ff5: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ffa: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fff: Unknown result type (might be due to invalid IL or missing references)
        //IL_40fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_410b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4110: Unknown result type (might be due to invalid IL or missing references)
        //IL_4115: Unknown result type (might be due to invalid IL or missing references)
        //IL_417e: Unknown result type (might be due to invalid IL or missing references)
        //IL_4183: Unknown result type (might be due to invalid IL or missing references)
        //IL_4188: Unknown result type (might be due to invalid IL or missing references)
        //IL_418d: Unknown result type (might be due to invalid IL or missing references)
        bool vanillaCanDamage = true;
        if (type == 18 || type == 72 || type == 86 || type == 87 || aiStyle == 31 || aiStyle == 32 || type == 226 || type == 378 || type == 613 || type == 650 || type == 882 || type == 888 || type == 895 || type == 896 || (type == 434 && localAI[0] != 0f) || type == 439 || type == 444 || (type == 451 && ((int)(ai[0] - 1f) / penetrate == 0 || ai[1] < 5f) && ai[0] != 0f) || type == 500 || type == 653 || type == 1018 || type == 460 || type == 633 || type == 600 || type == 601 || type == 602 || type == 535 || (type == 631 && localAI[1] == 0f) || (type == 537 && localAI[0] <= 30f) || type == 651 || (type == 188 && localAI[0] < 5f) || (aiStyle == 137 && ai[0] != 0f) || aiStyle == 138 || (type == 261 && ((Vector2)(ref velocity)).Length() < 1.5f) || (type == 818 && ai[0] < 1f) || type == 831 || type == 970 || (type == 833 && ai[0] == 4f) || (type == 834 && ai[0] == 4f) || (type == 835 && ai[0] == 4f) || (type == 281 && ai[0] == -3f) || ((type == 598 || type == 636 || type == 614 || type == 971 || type == 975) && ai[0] == 1f) || (type == 923 && localAI[0] <= 60f) || (type == 919 && localAI[0] <= 60f) || (aiStyle == 15 && ai[0] == 0f && localAI[1] <= 12f) || type == 861 || (type >= 511 && type <= 513 && ai[1] >= 1f) || type == 1007 || (aiStyle == 93 && ai[0] != 0f && ai[0] != 2f) || (aiStyle == 10 && localAI[1] == -1f) || (type == 85 && localAI[0] >= 54f) || (Main.projPet[type] && type != 266 && type != 407 && type != 317 && (type != 388 || ai[0] != 2f) && (type < 390 || type > 392) && (type < 393 || type > 395) && (type != 533 || !(ai[0] >= 6f) || !(ai[0] <= 8f)) && (type < 625 || type > 628) && (type != 755 || ai[0] == 0f) && (type != 946 || ai[0] == 0f) && type != 758 && type != 951 && type != 963 && (type != 759 || frame == Main.projFrames[type] - 1) && type != 833 && type != 834 && type != 835 && type != 864 && (type != 623 || ai[0] != 2f)))
        {
            vanillaCanDamage = false;
        }
        if (Main.projPet[type] && ProjectileLoader.MinionContactDamage(this))
        {
            vanillaCanDamage = true;
        }
        if (!(ProjectileLoader.CanDamage(this) ?? vanillaCanDamage))
        {
            return;
        }
        Rectangle rectangle = Damage_GetHitbox();
        if (friendly && Main.getGoodWorld && aiStyle == 16 && Main.netMode == 1 && owner != Main.myPlayer && !npcProj)
        {
            BombsHurtPlayers(rectangle, Main.myPlayer);
            return;
        }
        if (friendly && owner == Main.myPlayer && !npcProj)
        {
            BombsHurtPlayers(rectangle, owner);
            if (!minion)
            {
                CutTiles();
            }
        }
        if (owner == Main.myPlayer)
        {
            float num = 1f;
            if (ProjectileID.Sets.IsARocketThatDealsDoubleDamageToPrimaryEnemy[type] && timeLeft > 3)
            {
                num *= 2f;
            }
            if (ProjectileID.Sets.IsAMineThatDealsTripleDamageWhenStationary[type] && ((Vector2)(ref velocity)).Length() < 0.5f)
            {
                num *= 3f;
            }
            if (type == 34 && penetrate == 1)
            {
                num *= 1f;
            }
            if (aiStyle == 15 && ai[0] == 0f)
            {
                num *= 1.2f;
            }
            if (aiStyle == 15 && (ai[0] == 1f || ai[0] == 2f))
            {
                num *= 2f;
            }
            if (type == 877 || type == 879 || type == 878)
            {
                num = 0.1f + ((Vector2)(ref Main.player[owner].velocity)).Length() / 7f * 0.9f;
            }
            if (type == 968)
            {
                num = 1f;
                switch ((int)ai[1])
                {
                case 0:
                    num = 1.5f;
                    break;
                case 1:
                    num = 1f;
                    break;
                case 2:
                    num = 1.5f;
                    break;
                case 3:
                    num = 0.1f;
                    break;
                case 4:
                    num = 1f;
                    break;
                case 5:
                    num = 1f;
                    break;
                case 6:
                    num = 1f;
                    break;
                case 7:
                    num = 0.25f;
                    break;
                case 8:
                    num = 1f;
                    break;
                case 9:
                    num = 0.75f;
                    break;
                case 10:
                    num = 0.5f;
                    break;
                case 11:
                    num = 0.5f;
                    break;
                case 12:
                    num = 0.5f;
                    break;
                case 13:
                    num = 0.5f;
                    break;
                case 14:
                    num = 0.5f;
                    break;
                case 15:
                    num = 0.5f;
                    break;
                case 16:
                    num = 0.5f;
                    break;
                case 17:
                    num = 1.5f;
                    break;
                case 18:
                    num = 1.6f;
                    break;
                case 19:
                    num = 1.8f;
                    break;
                case 20:
                    num = 1.9f;
                    break;
                case 21:
                    num = 1.7f;
                    break;
                case 22:
                    num = 2f;
                    break;
                case 23:
                    num = 1.9f;
                    break;
                }
            }
            if (type == 533 && localAI[2] >= 40f)
            {
                num *= 0.5f;
            }
            bool flag = !npcProj && !trap;
            bool flag12 = usesOwnerMeleeHitCD && flag && owner < 255;
            bool flag22 = damage > 0;
            if (flag22)
            {
                int[] array = localNPCImmunity;
                if (type == 626 || type == 627 || type == 628)
                {
                    Projectile projectile = FindStardustDragonHeadOfOwner();
                    if (projectile != null)
                    {
                        array = projectile.localNPCImmunity;
                    }
                }
                bool flag23 = true;
                Vector2 vector3 = default(Vector2);
                for (int i = 0; i < 200 && flag23; i++)
                {
                    if (!Main.npc[i].active)
                    {
                        continue;
                    }
                    bool flag24 = (!usesLocalNPCImmunity && !usesIDStaticNPCImmunity) || (usesLocalNPCImmunity && array[i] == 0) || (usesIDStaticNPCImmunity && IsNPCIndexImmuneToProjectileType(type, i));
                    if (flag12 && !Main.player[owner].CanHitNPCWithMeleeHit(i))
                    {
                        flag24 = false;
                    }
                    if (!((!Main.npc[i].dontTakeDamage || NPCID.Sets.ZappingJellyfish[Main.npc[i].type]) && flag24) || (Main.npc[i].aiStyle == 112 && Main.npc[i].ai[2] > 1f))
                    {
                        continue;
                    }
                    bool canHitFlag = false;
                    bool? flag29 = CombinedHooks.CanHitNPCWithProj(this, Main.npc[i]);
                    if (flag29.HasValue)
                    {
                        if (!flag29.GetValueOrDefault())
{
                            continue;
                        }
                        canHitFlag = true;
                    }
                    NPC obj = Main.npc[i];
                    obj.position += Main.npc[i].netOffset;
                    bool flag25 = !Main.npc[i].friendly;
                    flag25 |= type == 318;
                    flag25 |= Main.npc[i].type == 22 && owner < 255 && Main.player[owner].killGuide;
                    flag25 |= Main.npc[i].type == 54 && owner < 255 && Main.player[owner].killClothier;
                    if (owner < 255 && !Main.player[owner].CanNPCBeHitByPlayerOrPlayerProjectile(Main.npc[i], this))
                    {
                        flag25 = false;
                    }
                    bool flag26 = Main.npc[i].friendly && !Main.npc[i].dontTakeDamageFromHostiles;
                    if (canHitFlag || (friendly && (flag25 || NPCID.Sets.ZappingJellyfish[Main.npc[i].type])) || (hostile && flag26))
                    {
                        bool flag27 = maxPenetrate == 1 && !usesLocalNPCImmunity && !usesIDStaticNPCImmunity;
                        if (canHitFlag)
{
                            flag27 = true;
                        }
                        if (owner < 0 || Main.npc[i].immune[owner] == 0 || flag27)
{
                            bool flag28 = false;
                            if (type == 11 && (Main.npc[i].type == 47 || Main.npc[i].type == 57))
{
                                flag28 = true;
                            }
                            else if (type == 31 && Main.npc[i].type == 69)
{
                                flag28 = true;
                            }
                            else if (Main.npc[i].trapImmune && trap)
{
                                flag28 = true;
                            }
                            else if (Main.npc[i].immortal && npcProj)
{
                                flag28 = true;
                            }
                            if (canHitFlag)
{
                                flag28 = false;
                            }
                            if (!flag28 && (Main.npc[i].noTileCollide || !ownerHitCheck || CanHitWithMeleeWeapon(Main.npc[i])))
{
                                bool flag2 = false;
                                if (Main.npc[i].type == 414)
{
                                    Rectangle rect = Main.npc[i].getRect();
                                    int num11 = 8;
                                    rect.X -= num11;
                                    rect.Y -= num11;
                                    rect.Width += num11 * 2;
                                    rect.Height += num11 * 2;
                                    flag2 = Colliding(rectangle, rect);
                                }
                                else
{
                                    flag2 = Colliding(rectangle, Main.npc[i].getRect());
                                }
                                if (flag2)
{
                                    NPC nPC = Main.npc[i];
                                    if (NPCID.Sets.ZappingJellyfish[nPC.type])
{
                                        if ((nPC.dontTakeDamage || !Main.player[owner].CanNPCBeHitByPlayerOrPlayerProjectile(nPC, this)) && (aiStyle == 19 || aiStyle == 161 || aiStyle == 75 || aiStyle == 140 || ProjectileID.Sets.IsAWhip[type] || ProjectileID.Sets.AllowsContactDamageFromJellyfish[type]))
{
                                            Main.player[owner].TakeDamageFromJellyfish(i);
                                        }
                                        if (nPC.dontTakeDamage || !flag25)
{
                                            continue;
                                        }
                                    }
                                    if (type == 876)
{
                                        Vector2 vector = position;
                                        if (Main.rand.Next(20) == 0)
{
                                            tileCollide = false;
                                            position.X += Main.rand.Next(-256, 257);
                                        }
                                        if (Main.rand.Next(20) == 0)
{
                                            tileCollide = false;
                                            position.Y += Main.rand.Next(-256, 257);
                                        }
                                        if (Main.rand.Next(2) == 0)
{
                                            tileCollide = false;
                                        }
                                        if (Main.rand.Next(3) != 0)
{
                                            vector = position;
                                            position -= velocity * (float)Main.rand.Next(0, 40);
                                            if (tileCollide && Collision.SolidTiles(position, width, height))
{
                                                position = vector;
                                                position -= velocity * (float)Main.rand.Next(0, 40);
                                                if (tileCollide && Collision.SolidTiles(position, width, height))
{
                                                    position = vector;
                                                }
                                            }
                                        }
                                        velocity *= 0.6f;
                                        if (Main.rand.Next(7) == 0)
{
                                            velocity.X += (float)Main.rand.Next(30, 31) * 0.01f;
                                        }
                                        if (Main.rand.Next(7) == 0)
{
                                            velocity.Y += (float)Main.rand.Next(30, 31) * 0.01f;
                                        }
                                        damage = (int)((double)damage * 0.9);
                                        knockBack *= 0.9f;
                                        if (Main.rand.Next(20) == 0)
{
                                            knockBack *= 10f;
                                        }
                                        if (Main.rand.Next(50) == 0)
{
                                            damage *= 10;
                                        }
                                        if (Main.rand.Next(7) == 0)
{
                                            vector = position;
                                            position.X += Main.rand.Next(-64, 65);
                                            if (tileCollide && Collision.SolidTiles(position, width, height))
{
                                                position = vector;
                                            }
                                        }
                                        if (Main.rand.Next(7) == 0)
{
                                            vector = position;
                                            position.Y += Main.rand.Next(-64, 65);
                                            if (tileCollide && Collision.SolidTiles(position, width, height))
{
                                                position = vector;
                                            }
                                        }
                                        if (Main.rand.Next(14) == 0)
{
                                            velocity.X *= -1f;
                                        }
                                        if (Main.rand.Next(14) == 0)
{
                                            velocity.Y *= -1f;
                                        }
                                        if (Main.rand.Next(10) == 0)
{
                                            velocity *= (float)Main.rand.Next(1, 201) * 0.0005f;
                                        }
                                        if (tileCollide)
{
                                            ai[1] = 0f;
                                        }
                                        else
{
                                            ai[1] = 1f;
                                        }
                                        netUpdate = true;
                                    }
                                    bool flag3 = nPC.reflectsProjectiles;
                                    if (Main.getGoodWorld && NPCID.Sets.ReflectStarShotsInForTheWorthy[Main.npc[i].type] && (type == 955 || type == 728))
{
                                        flag3 = true;
                                    }
                                    if (flag3 && CanBeReflected() && nPC.CanReflectProjectile(this))
{
                                        nPC.ReflectProjectile(this);
                                        NPC obj2 = Main.npc[i];
                                        obj2.position -= Main.npc[i].netOffset;
                                        return;
                                    }
                                    if (type == 604)
{
                                        Main.player[owner].Counterweight(nPC.Center, damage, knockBack);
                                    }
                                    NPC.HitModifiers modifiers = nPC.GetIncomingStrikeModifiers(DamageType, direction);
                                    modifiers.ArmorPenetration += (float)ArmorPenetration;
                                    CombinedHooks.ModifyHitNPCWithProj(this, nPC, ref modifiers);
                                    float num21 = knockBack;
                                    bool flag4 = false;
                                    int num32 = (int)Main.player[owner].armorPenetration;
                                    float armorPenetrationPercent = 0f;
                                    bool flag5 = false;
                                    switch (type)
{
                                    case 442:
                                        flag5 = true;
                                        break;
                                    case 410:
                                        if (Main.remixWorld)
{
                                            num32 += 20;
                                        }
                                        break;
                                    case 864:
                                        num32 += 25;
                                        break;
                                    case 916:
                                        num32 += 50;
                                        break;
                                    case 917:
                                        num32 += 30;
                                        break;
                                    case 595:
                                        num32 += 20;
                                        break;
                                    case 493:
                                    case 494:
                                        num32 += 10;
                                        break;
                                    case 150:
                                    case 151:
                                    case 152:
                                        num32 += 10;
                                        break;
                                    case 189:
                                        num32 += 10;
                                        if (flag && Main.player[owner].strongBees)
{
                                            modifiers.ArmorPenetration += 5f;
                                        }
                                        break;
                                    case 723:
                                    case 724:
                                    case 725:
                                    case 726:
                                        num32 += 25;
                                        break;
                                    case 532:
                                        num32 += 25;
                                        break;
                                    case 964:
                                        num32 += 20;
                                        break;
                                    case 969:
                                        num32 += 10;
                                        break;
                                    case 85:
                                        num32 += 15;
                                        break;
                                    case 877:
                                    case 878:
                                    case 879:
                                        num21 *= ((Vector2)(ref Main.player[owner].velocity)).Length() / 7f;
                                        break;
                                    case 963:
                                        num21 *= 0.25f;
                                        break;
                                    case 976:
                                        num32 += 20;
                                        break;
                                    case 974:
                                        num32 += 5;
                                        break;
                                    case 977:
                                        num32 += 5;
                                        break;
                                    }
                                    if (flag5)
{
                                        Kill();
                                        return;
                                    }
                                    modifiers.SourceDamage *= num;
                                    float num43 = 1000f;
                                    int num46 = 0;
                                    if (type > 0 && ProjectileID.Sets.StardustDragon[type])
{
                                        float value = (scale - 1f) * 100f;
                                        value = Utils.Clamp(value, 0f, 50f);
                                        num43 = (int)(num43 * (1f + value * 0.23f));
                                    }
                                    if (type > 0 && type < ProjectileID.Count && ProjectileID.Sets.StormTiger[type])
{
                                        int num47 = Math.Max(0, Main.player[owner].ownedProjectileCounts[831] - 1);
                                        num43 = (int)(num43 * (1f + (float)num47 * 0.4f));
                                    }
                                    if (type == 818)
{
                                        int num48 = Math.Max(0, Main.player[owner].ownedProjectileCounts[831] - 1);
                                        num43 = (int)(num43 * (1.5f + (float)num48 * 0.4f));
                                    }
                                    if (type == 963)
{
                                        int num49 = Math.Max(0, Main.player[owner].ownedProjectileCounts[970] - 1);
                                        int num2 = 3 + num49 / 2;
                                        if (CountEnemiesWhoAreImmuneToMeRightNow(num2) >= num2)
{
                                            return;
                                        }
                                        float num3 = 0.55f;
                                        if (Main.hardMode)
{
                                            num3 = 1.3f;
                                        }
                                        num43 = (int)(num43 * (1f + (float)num49 * num3));
                                    }
                                    if (flag && type == 189 && Main.player[owner].strongBees)
{
                                        modifiers.SourceDamage.Base += 5f;
                                    }
                                    if (flag)
{
                                        if (DamageType.UseStandardCritCalcs && Main.rand.Next(100) < CritChance)
{
                                            flag4 = true;
                                        }
                                        if ((uint)(type - 688) <= 2u)
{
                                            if (Main.player[owner].setMonkT3)
{
                                                if (Main.rand.Next(4) == 0)
{
                                                    flag4 = true;
                                                }
                                            }
                                            else if (Main.player[owner].setMonkT2 && Main.rand.Next(6) == 0)
{
                                                flag4 = true;
                                            }
                                        }
                                    }
                                    modifiers.SourceDamage *= num43 / 1000f;
                                    num43 = modifiers.SourceDamage.ApplyTo(damage);
                                    float num4 = ProjectileID.Sets.SummonTagDamageMultiplier[type];
                                    if (flag && (minion || ProjectileID.Sets.MinionShot[type] || sentry || ProjectileID.Sets.SentryShot[type]))
{
                                        bool flag6 = false;
                                        bool flag7 = false;
                                        bool flag8 = false;
                                        bool flag9 = false;
                                        bool flag10 = false;
                                        bool flag11 = false;
                                        bool flag13 = false;
                                        bool flag14 = false;
                                        bool flag15 = false;
                                        for (int j = 0; j < NPC.maxBuffs; j++)
{
                                            if (nPC.buffTime[j] >= 1)
{
                                                switch (nPC.buffType[j])
{
                                                case 307:
                                                    flag6 = true;
                                                    break;
                                                case 309:
                                                    flag7 = true;
                                                    break;
                                                case 313:
                                                    flag8 = true;
                                                    break;
                                                case 310:
                                                    flag9 = true;
                                                    break;
                                                case 315:
                                                    flag10 = true;
                                                    break;
                                                case 326:
                                                    flag11 = true;
                                                    break;
                                                case 319:
                                                    flag14 = true;
                                                    break;
                                                case 316:
                                                    flag15 = true;
                                                    break;
                                                case 340:
                                                    flag13 = true;
                                                    break;
                                                }
                                            }
                                        }
                                        if (flag6)
{
                                            num46 += 4;
                                        }
                                        if (flag10)
{
                                            num46 += 6;
                                        }
                                        if (flag11)
{
                                            num46 += 7;
                                        }
                                        if (flag13)
{
                                            num46 += 6;
                                        }
                                        if (flag7)
{
                                            num46 += 9;
                                        }
                                        if (flag14)
{
                                            num46 += 8;
                                            if (Main.rand.Next(100) < 12)
{
                                                flag4 = true;
                                            }
                                        }
                                        if (flag9)
{
                                            int num5 = 10;
                                            num46 += num5;
                                            int num6 = NewProjectile(GetProjectileSource_FromThis(), nPC.Center, Vector2.Zero, 916, (int)((float)num5 * num4), 0f, owner);
                                            Main.projectile[num6].localNPCImmunity[i] = -1;
                                            EmitBlackLightningParticles(nPC);
                                        }
                                        if (flag15)
{
                                            int num7 = 20;
                                            num46 += num7;
                                            if (Main.rand.Next(10) == 0)
{
                                                flag4 = true;
                                            }
                                            ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.RainbowRodHit, new ParticleOrchestraSettings
{
                                                PositionInWorld = base.Center
                                            });
                                        }
                                        if (flag8)
{
                                            nPC.RequestBuffRemoval(313);
                                            int num8 = (int)(num43 * 1.75f);
                                            int num9 = NewProjectile(GetProjectileSource_FromThis(), nPC.Center, Vector2.Zero, 918, num8, 0f, owner);
                                            Main.projectile[num9].localNPCImmunity[i] = -1;
                                            modifiers.ScalingBonusDamage += 1.75f * num4;
                                        }
                                    }
                                    num46 = (int)((float)num46 * num4);
                                    modifiers.FlatBonusDamage += (float)num46;
                                    if (flag)
{
                                        _ = Main.player[owner].luck;
                                    }
                                    float num10 = 1000f;
                                    if (type == 1002)
{
                                        num10 /= 2f;
                                    }
                                    if (trap && NPCID.Sets.BelongsToInvasionOldOnesArmy[nPC.type])
{
                                        num10 /= 2f;
                                    }
                                    if (type == 482 && (nPC.aiStyle == 6 || nPC.aiStyle == 37))
{
                                        num10 /= 2f;
                                    }
                                    if (flag)
{
                                        Vector2 positionInWorld = Main.rand.NextVector2FromRectangle(nPC.Hitbox);
                                        ParticleOrchestraSettings particleOrchestraSettings = default(ParticleOrchestraSettings);
                                        particleOrchestraSettings.PositionInWorld = positionInWorld;
                                        ParticleOrchestraSettings settings = particleOrchestraSettings;
                                        switch (type)
{
                                        case 972:
                                            ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.NightsEdge, settings, owner);
                                            break;
                                        case 973:
                                            ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.TrueNightsEdge, settings, owner);
                                            break;
                                        case 984:
                                        case 985:
                                            settings.MovementVector = velocity;
                                            ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.TerraBlade, settings, owner);
                                            break;
                                        case 982:
                                            ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.Excalibur, settings, owner);
                                            break;
                                        case 983:
                                            ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.TrueExcalibur, settings, owner);
                                            break;
                                        }
                                    }
                                    if (type == 604)
{
                                        friendly = false;
                                        ai[1] = 1000f;
                                    }
                                    if ((type == 400 || type == 401 || type == 402) && nPC.type >= 13 && nPC.type <= 15)
{
                                        num10 = (int)((double)num10 * 0.65);
                                        if (penetrate > 1)
{
                                            penetrate--;
                                        }
                                    }
                                    if (type == 710 && !WorldUtils.Find(base.Center.ToTileCoordinates(), Searches.Chain(new Searches.Down(12), _cachedConditions_notNull, _cachedConditions_solid), out var _))
{
                                        num10 = (int)(num10 * 1.5f);
                                    }
                                    if (type == 504 || type == 954 || type == 979)
{
                                        float num12 = (60f - ai[0]) / 2f;
                                        ai[0] += num12;
                                    }
                                    if (aiStyle == 3 && type != 301 && type != 866 && type != 902)
{
                                        if (ai[0] == 0f)
{
                                            if (type == 106)
{
                                                LightDisc_Bounce(base.Center + velocity.SafeNormalize(Vector2.UnitX) * 8f, (-velocity).SafeNormalize(Vector2.UnitX));
                                            }
                                            velocity.X = 0f - velocity.X;
                                            velocity.Y = 0f - velocity.Y;
                                            netUpdate = true;
                                        }
                                        ai[0] = 1f;
                                    }
                                    else if (type == 951)
{
                                        Vector2 vector2 = (nPC.Center - base.Center).SafeNormalize(Vector2.Zero);
                                        vector2.X += (-0.5f + Main.rand.NextFloat()) * 13f;
                                        vector2.Y = -5f;
                                        velocity.X = vector2.X;
                                        velocity.Y = vector2.Y;
                                        netUpdate = true;
                                    }
                                    else if (type == 582 || type == 902)
{
                                        if (ai[0] != 0f)
{
                                            direction *= -1;
                                        }
                                    }
                                    else if (type == 612 || type == 953 || type == 978)
{
                                        direction = Main.player[owner].direction;
                                    }
                                    else if (type == 624)
{
                                        float num13 = 1f;
                                        if (nPC.knockBackResist > 0f)
{
                                            num13 = 1f / nPC.knockBackResist;
                                        }
                                        knockBack = 4f * num13;
                                        num21 = knockBack;
                                        if (nPC.Center.X < base.Center.X)
{
                                            direction = 1;
                                        }
                                        else
{
                                            direction = -1;
                                        }
                                    }
                                    else if (aiStyle == 16)
{
                                        if (timeLeft > 3)
{
                                            timeLeft = 3;
                                        }
                                        if (nPC.position.X + (float)(nPC.width / 2) < position.X + (float)(width / 2))
{
                                            direction = -1;
                                        }
                                        else
{
                                            direction = 1;
                                        }
                                    }
                                    else if (aiStyle == 68)
{
                                        if (timeLeft > 3)
{
                                            timeLeft = 3;
                                        }
                                        if (nPC.position.X + (float)(nPC.width / 2) < position.X + (float)(width / 2))
{
                                            direction = -1;
                                        }
                                        else
{
                                            direction = 1;
                                        }
                                    }
                                    else if (aiStyle == 50)
{
                                        if (nPC.position.X + (float)(nPC.width / 2) < position.X + (float)(width / 2))
{
                                            direction = -1;
                                        }
                                        else
{
                                            direction = 1;
                                        }
                                    }
                                    else if (type == 908)
{
                                        if (nPC.position.X + (float)(nPC.width / 2) < position.X + (float)(width / 2))
{
                                            direction = -1;
                                        }
                                        else
{
                                            direction = 1;
                                        }
                                    }
                                    if (type == 509)
{
                                        int num14 = Main.rand.Next(2, 6);
                                        for (int k = 0; k < num14; k++)
{
                                            ((Vector2)(ref vector3))._002Ector((float)Main.rand.Next(-100, 101), (float)Main.rand.Next(-100, 101));
                                            vector3 += velocity * 3f;
                                            ((Vector2)(ref vector3)).Normalize();
                                            vector3 *= (float)Main.rand.Next(35, 81) * 0.1f;
                                            int num15 = (int)((double)damage * 0.5);
                                            NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, vector3.X, vector3.Y, 504, num15, knockBack * 0.2f, owner);
                                        }
                                    }
                                    if ((type == 476 || type == 950) && !npcProj)
{
                                        float x = Main.player[owner].Center.X;
                                        if (nPC.Center.X < x)
{
                                            direction = -1;
                                        }
                                        else
{
                                            direction = 1;
                                        }
                                    }
                                    if (type == 598 || type == 636 || type == 614 || type == 971 || type == 975)
{
                                        ai[0] = 1f;
                                        ai[1] = i;
                                        velocity = (nPC.Center - base.Center) * 0.75f;
                                        netUpdate = true;
                                    }
                                    if (type >= 511 && type <= 513)
{
                                        ai[1] += 1f;
                                        netUpdate = true;
                                    }
                                    if (type == 659)
{
                                        timeLeft = 0;
                                    }
                                    if (type == 524)
{
                                        netUpdate = true;
                                        ai[0] += 50f;
                                    }
                                    if ((type == 688 || type == 689 || type == 690) && nPC.type != 68 && nPC.defense < 999)
{
                                        armorPenetrationPercent = 1f;
                                    }
                                    if (aiStyle == 39)
{
                                        if (ai[1] == 0f)
{
                                            ai[1] = i + 1;
                                            netUpdate = true;
                                        }
                                        if (Main.player[owner].position.X + (float)(Main.player[owner].width / 2) < position.X + (float)(width / 2))
{
                                            direction = 1;
                                        }
                                        else
{
                                            direction = -1;
                                        }
                                    }
                                    if (type == 41 && timeLeft > 1)
{
                                        timeLeft = 1;
                                    }
                                    if (aiStyle == 99)
{
                                        Main.player[owner].Counterweight(nPC.Center, damage, knockBack);
                                        if (nPC.Center.X < Main.player[owner].Center.X)
{
                                            direction = -1;
                                        }
                                        else
{
                                            direction = 1;
                                        }
                                        if (ai[0] >= 0f)
{
                                            Vector2 vector4 = base.Center - nPC.Center;
                                            ((Vector2)(ref vector4)).Normalize();
                                            float num16 = 16f;
                                            velocity *= -0.5f;
                                            velocity += vector4 * num16;
                                            netUpdate = true;
                                            localAI[0] += 20f;
                                            if (!Collision.CanHit(position, width, height, Main.player[owner].position, Main.player[owner].width, Main.player[owner].height))
{
                                                localAI[0] += 40f;
                                                num10 = (int)((double)num10 * 0.75);
                                            }
                                        }
                                    }
                                    if (type == 856 && !Collision.CanHit(position, width, height, Main.player[owner].position, Main.player[owner].width, Main.player[owner].height))
{
                                        num10 = (int)((double)num10 * 0.75);
                                    }
                                    if (aiStyle == 93)
{
                                        if (ai[0] == 0f)
{
                                            ai[1] = 0f;
                                            int num17 = -i - 1;
                                            ai[0] = num17;
                                            velocity = nPC.Center - base.Center;
                                        }
                                        num10 = ((ai[0] != 2f) ? ((int)((double)num10 * 0.15)) : ((int)((double)num10 * 1.35)));
                                    }
                                    if (flag)
{
                                        int num18 = Item.NPCtoBanner(nPC.BannerID());
                                        if (num18 >= 0)
{
                                            Main.player[Main.myPlayer].lastCreatureHit = num18;
                                        }
                                    }
                                    if (Main.netMode != 2 && flag)
{
                                        Main.player[owner].ApplyBannerOffenseBuff(nPC, ref modifiers);
                                    }
                                    if (Main.expertMode)
{
                                        if ((type == 30 || type == 397 || type == 517 || type == 28 || type == 37 || type == 516 || type == 29 || type == 470 || type == 637 || type == 108 || type == 281 || type == 588 || type == 519 || type == 773 || type == 183 || type == 181 || type == 566 || type == 1002) && nPC.type >= 13 && nPC.type <= 15)
{
                                            num10 /= 5f;
                                        }
                                        if (type == 280 && ((nPC.type >= 134 && nPC.type <= 136) || nPC.type == 139))
{
                                            num10 = (int)((double)num10 * 0.75);
                                        }
                                    }
                                    if (Main.netMode != 2 && nPC.type == 439 && type >= 0 && ProjectileID.Sets.CultistIsResistantTo[type])
{
                                        num10 = (int)(num10 * 0.75f);
                                    }
                                    if (type == 497 && penetrate != 1)
{
                                        ai[0] = 25f;
                                        float num19 = ((Vector2)(ref velocity)).Length();
                                        Vector2 vector5 = nPC.Center - base.Center;
                                        ((Vector2)(ref vector5)).Normalize();
                                        vector5 *= num19;
                                        velocity = -vector5 * 0.9f;
                                        netUpdate = true;
                                    }
                                    if (type == 323 && (nPC.type == 159 || nPC.type == 158))
{
                                        num10 *= 10f;
                                    }
                                    if (type == 981 && nPC.type == 104)
{
                                        num10 *= 3f;
                                    }
                                    if (type == 261 && ((Vector2)(ref velocity)).Length() < 3.5f)
{
                                        modifiers.SourceDamage /= 2f;
                                        num21 /= 2f;
                                    }
                                    if (flag && melee && Main.player[owner].parryDamageBuff && !ProjectileID.Sets.DontApplyParryDamageBuff[type])
{
                                        modifiers.ScalingBonusDamage += 4f;
                                        Main.player[owner].parryDamageBuff = false;
                                        Main.player[owner].ClearBuff(198);
                                    }
                                    int? num26 = null;
                                    switch (type)
{
                                    case 697:
                                    case 699:
                                    case 707:
                                    case 708:
                                    case 759:
                                        num26 = ((Main.player[owner].Center.X < nPC.Center.X) ? 1 : (-1));
                                        break;
                                    }
                                    if (aiStyle == 188 || aiStyle == 189 || aiStyle == 190 || aiStyle == 191)
{
                                        num26 = ((Main.player[owner].Center.X < nPC.Center.X) ? 1 : (-1));
                                    }
                                    if (aiStyle == 15)
{
                                        num26 = ((Main.player[owner].Center.X < nPC.Center.X) ? 1 : (-1));
                                        if (ai[0] == 0f)
{
                                            num21 *= 0.35f;
                                        }
                                        if (ai[0] == 6f)
{
                                            num21 *= 0.5f;
                                        }
                                    }
                                    modifiers.ScalingArmorPenetration += armorPenetrationPercent;
                                    modifiers.Knockback *= num21 / knockBack;
                                    modifiers.TargetDamageMultiplier *= num10 / 1000f;
                                    if (num26.HasValue)
{
                                        modifiers.HitDirectionOverride = num26;
                                    }
                                    NPC.HitInfo strike = modifiers.ToHitInfo(damage, flag4, num21, damageVariation: true, flag ? Main.player[owner].luck : 0f);
                                    num26 = strike.HitDirection;
                                    if (type == 294)
{
                                        damage = (int)((double)damage * 0.9);
                                    }
                                    if (type == 265)
{
                                        damage = (int)((double)damage * 0.75);
                                    }
                                    if (type == 355)
{
                                        damage = (int)((double)damage * 0.75);
                                    }
                                    if (type == 114)
{
                                        damage = (int)((double)damage * 0.9);
                                    }
                                    if (type == 76 || type == 78 || type == 77)
{
                                        damage = (int)((double)damage * 0.95);
                                    }
                                    if (type == 85)
{
                                        damage = (int)((double)damage * 0.85);
                                    }
                                    if (type == 866)
{
                                        damage = (int)((double)damage * 0.8);
                                    }
                                    if (type == 841)
{
                                        damage = (int)((double)damage * 0.5);
                                    }
                                    if (type == 914)
{
                                        damage = (int)((double)damage * 0.6);
                                    }
                                    if (type == 952)
{
                                        damage = (int)((double)damage * 0.9);
                                    }
                                    if (type == 913)
{
                                        damage = (int)((double)damage * 0.66);
                                    }
                                    if (type == 912)
{
                                        damage = (int)((double)damage * 0.7);
                                    }
                                    if (type == 847)
{
                                        damage = (int)((double)damage * 0.8);
                                    }
                                    if (type == 848)
{
                                        damage = (int)((double)damage * 0.95);
                                    }
                                    if (type == 849)
{
                                        damage = (int)((double)damage * 0.9);
                                    }
                                    if (type == 915)
{
                                        damage = (int)((double)damage * 0.9);
                                    }
                                    if (type == 931)
{
                                        damage = (int)((double)damage * 0.8);
                                    }
                                    if (type == 242)
{
                                        damage = (int)((double)damage * 0.85);
                                    }
                                    if (type == 323)
{
                                        damage = (int)((double)damage * 0.9);
                                    }
                                    if (type == 5)
{
                                        damage = (int)((double)damage * 0.9);
                                    }
                                    if (type == 4)
{
                                        damage = (int)((double)damage * 0.95);
                                    }
                                    if (type == 309)
{
                                        damage = (int)((double)damage * 0.85);
                                    }
                                    if (type == 132)
{
                                        damage = (int)((double)damage * 0.85);
                                    }
                                    if (type == 985)
{
                                        damage = (int)((double)damage * 0.75);
                                    }
                                    if (type == 950)
{
                                        damage = (int)((double)damage * 0.98);
                                    }
                                    if (type == 964)
{
                                        damage = (int)((double)damage * 0.85);
                                    }
                                    if (type == 477 && penetrate > 1)
{
                                        int[] array2 = new int[10];
                                        int num20 = 0;
                                        int num22 = 700;
                                        int num23 = 20;
                                        for (int l = 0; l < 200; l++)
{
                                            if (l == i || !Main.npc[l].CanBeChasedBy(this))
{
                                                continue;
                                            }
                                            Vector2 val = base.Center - Main.npc[l].Center;
                                            float num24 = ((Vector2)(ref val)).Length();
                                            if (num24 > (float)num23 && num24 < (float)num22 && Collision.CanHitLine(base.Center, 1, 1, Main.npc[l].Center, 1, 1))
{
                                                array2[num20] = l;
                                                num20++;
                                                if (num20 >= 9)
{
                                                    break;
                                                }
                                            }
                                        }
                                        if (num20 > 0)
{
                                            num20 = Main.rand.Next(num20);
                                            Vector2 vector6 = Main.npc[array2[num20]].Center - base.Center;
                                            float num25 = ((Vector2)(ref velocity)).Length();
                                            ((Vector2)(ref vector6)).Normalize();
                                            velocity = vector6 * num25;
                                            netUpdate = true;
                                        }
                                    }
                                    StatusNPC(i);
                                    if (flag && nPC.life > 5)
{
                                        TryDoingOnHitEffects(nPC);
                                    }
                                    if (ProjectileID.Sets.ImmediatelyUpdatesNPCBuffFlags[type])
{
                                        nPC.UpdateNPC_BuffSetFlags(lowerBuffTime: false);
                                    }
                                    if (type == 317)
{
                                        ai[1] = -1f;
                                        netUpdate = true;
                                    }
                                    NPCKillAttempt attempt = new NPCKillAttempt(nPC);
                                    int num27 = nPC.StrikeNPC(strike, fromNet: false, !flag);
                                    if (flag && attempt.DidNPCDie())
{
                                        Main.player[owner].OnKillNPC(ref attempt, this);
                                    }
                                    if (flag && Main.player[owner].accDreamCatcher && !nPC.HideStrikeDamage)
{
                                        Main.player[owner].addDPS(num27);
                                    }
                                    bool flag16 = !nPC.immortal;
                                    bool flag17 = num27 > 0 && nPC.lifeMax > 5 && friendly && !hostile && aiStyle != 59;
                                    bool flag18 = false;
                                    if (flag16 && active && timeLeft > 10 && nPC.active && nPC.type == 676 && CanBeReflected())
{
                                        nPC.ReflectProjectile(this);
                                        penetrate++;
                                    }
                                    if (flag && flag16)
{
                                        if (type == 997 && (!nPC.immortal || flag18) && !nPC.SpawnedFromStatue && !NPCID.Sets.CountsAsCritter[nPC.type])
{
                                            Main.player[owner].HorsemansBlade_SpawnPumpkin(i, (int)((float)damage * 1f), knockBack);
                                        }
                                        if (type == 756 && penetrate == 1)
{
                                            damage = 0;
                                            penetrate = -1;
                                            flag23 = false;
                                        }
                                        if ((flag18 || nPC.value > 0f) && Main.player[owner].hasLuckyCoin && Main.rand.Next(5) == 0)
{
                                            int num28 = 71;
                                            if (Main.rand.Next(10) == 0)
{
                                                num28 = 72;
                                            }
                                            if (Main.rand.Next(100) == 0)
{
                                                num28 = 73;
                                            }
                                            int num29 = Item.NewItem(GetItemSource_OnHit(nPC, 2), (int)nPC.position.X, (int)nPC.position.Y, nPC.width, nPC.height, num28);
                                            Main.item[num29].stack = Main.rand.Next(1, 11);
                                            Main.item[num29].velocity.Y = (float)Main.rand.Next(-20, 1) * 0.2f;
                                            Main.item[num29].velocity.X = (float)Main.rand.Next(10, 31) * 0.2f * (float)num26.Value;
                                            Main.item[num29].timeLeftInWhichTheItemCannotBeTakenByEnemies = 60;
                                            if (Main.netMode == 1)
{
                                                NetMessage.SendData(148, -1, -1, null, num29);
                                            }
                                        }
                                        if (type == 999 && owner == Main.myPlayer && Main.rand.Next(3) == 0)
{
                                            Player player = Main.player[owner];
                                            Vector2 vector7 = (base.Center - nPC.Center).SafeNormalize(Vector2.Zero) * 0.25f;
                                            int dmg = damage / 2;
                                            float kB = knockBack;
                                            int num30 = NewProjectile(GetProjectileSource_FromThis(), base.Center.X, base.Center.Y, vector7.X, vector7.Y, player.beeType(), player.beeDamage(dmg), player.beeKB(kB), owner);
                                            Main.projectile[num30].melee = true;
                                        }
                                        if (flag17)
{
                                            if (type == 304 && !Main.player[owner].moonLeech)
{
                                                vampireHeal(num27, new Vector2(nPC.Center.X, nPC.Center.Y), nPC);
                                            }
                                            if (nPC.canGhostHeal || flag18)
{
                                                if (Main.player[owner].ghostHeal && !Main.player[owner].moonLeech)
{
                                                    ghostHeal(num27, new Vector2(nPC.Center.X, nPC.Center.Y), nPC);
                                                }
                                                if (Main.player[owner].ghostHurt)
{
                                                    ghostHurt(num27, new Vector2(nPC.Center.X, nPC.Center.Y), nPC);
                                                }
                                                if (magic && Main.player[owner].setNebula && Main.player[owner].nebulaCD == 0 && Main.rand.Next(3) == 0)
{
                                                    Main.player[owner].nebulaCD = 30;
                                                    int num31 = Utils.SelectRandom<int>(Main.rand, 3453, 3454, 3455);
                                                    int num33 = Item.NewItem(GetItemSource_OnHit(nPC, 1), (int)nPC.position.X, (int)nPC.position.Y, nPC.width, nPC.height, num31);
                                                    Main.item[num33].velocity.Y = (float)Main.rand.Next(-20, 1) * 0.2f;
                                                    Main.item[num33].velocity.X = (float)Main.rand.Next(10, 31) * 0.2f * (float)num26.Value;
                                                    if (Main.netMode == 1)
{
                                                        NetMessage.SendData(21, -1, -1, null, num33);
                                                    }
                                                }
                                            }
                                            if (melee && Main.player[owner].beetleOffense && (!nPC.immortal || flag18))
{
                                                if (Main.player[owner].beetleOrbs == 0)
{
                                                    Main.player[owner].beetleCounter += num27 * 3;
                                                }
                                                else if (Main.player[owner].beetleOrbs == 1)
{
                                                    Main.player[owner].beetleCounter += num27 * 2;
                                                }
                                                else
{
                                                    Main.player[owner].beetleCounter += num27;
                                                }
                                                Main.player[owner].beetleCountdown = 0;
                                            }
                                            if (arrow && type != 631 && Main.player[owner].phantasmTime > 0)
{
                                                Vector2 source = Main.player[owner].position + Main.player[owner].Size * Utils.RandomVector2(Main.rand, 0f, 1f);
                                                Vector2 vector8 = nPC.DirectionFrom(source) * 6f;
                                                int num34 = (int)((float)damage * 0.3f);
                                                NewProjectile(GetProjectileSource_FromThis(), source.X, source.Y, vector8.X, vector8.Y, 631, num34, 0f, owner, i);
                                                NewProjectile(GetProjectileSource_FromThis(), source.X, source.Y, vector8.X, vector8.Y, 631, num34, 0f, owner, i, 15f);
                                                NewProjectile(GetProjectileSource_FromThis(), source.X, source.Y, vector8.X, vector8.Y, 631, num34, 0f, owner, i, 30f);
                                            }
                                            Player player2 = Main.player[owner];
                                            switch (type)
{
                                            case 914:
                                                player2.AddBuff(314, 180);
                                                break;
                                            case 847:
                                                player2.AddBuff(308, 180);
                                                break;
                                            case 849:
                                                player2.AddBuff(311, 180);
                                                break;
                                            case 912:
{
                                                int num35 = 15;
                                                if (!player2.coolWhipBuff)
{
                                                    NewProjectile(GetProjectileSource_FromThis(), nPC.Center, Vector2.Zero, 917, num35, 0f, owner);
                                                    player2.coolWhipBuff = true;
                                                }
                                                player2.AddBuff(312, 180);
                                                break;
                                            }
                                            }
                                        }
                                    }
                                    if (flag && (melee || ProjectileID.Sets.IsAWhip[type]) && Main.player[owner].meleeEnchant == 7)
{
                                        NewProjectile(GetProjectileSource_FromThis(), nPC.Center.X, nPC.Center.Y, nPC.velocity.X, nPC.velocity.Y, 289, 0, 0f, owner);
                                    }
                                    if (flag && type == 913)
{
                                        localAI[0] = 1f;
                                    }
                                    if (Main.netMode != 0)
{
                                        NetMessage.SendStrikeNPC(nPC, in strike);
                                    }
                                    if (type == 916)
{
                                        EmitBlackLightningParticles(nPC);
                                    }
                                    if (type >= 390 && type <= 392)
{
                                        localAI[1] = 20f;
                                    }
                                    if (usesIDStaticNPCImmunity)
{
                                        if (penetrate != 1 || appliesImmunityTimeOnSingleHits)
{
                                            nPC.immune[owner] = 0;
                                            perIDStaticNPCImmunity[type][i] = Main.GameUpdateCount + (uint)idStaticNPCHitCooldown;
                                        }
                                    }
                                    else if (type == 434)
{
                                        numUpdates = 0;
                                    }
                                    else if (type == 598 || type == 636 || type == 614)
{
                                        Point[] bufferForScan = _javelinsMax6;
                                        if (type == 636)
{
                                            bufferForScan = _javelinsMax8;
                                        }
                                        if (type == 614)
{
                                            bufferForScan = _javelinsMax10;
                                        }
                                        KillOldestJavelin(whoAmI, type, i, bufferForScan);
                                    }
                                    else if (type == 632)
{
                                        nPC.immune[owner] = 5;
                                    }
                                    else if (type == 514)
{
                                        nPC.immune[owner] = 1;
                                    }
                                    else if (type == 611)
{
                                        if (localAI[1] <= 0f)
{
                                            NewProjectile(GetProjectileSource_FromThis(), nPC.Center.X, nPC.Center.Y, 0f, 0f, 612, damage, 10f, owner, 0f, 0.85f + Main.rand.NextFloat() * 1.15f);
                                        }
                                        localAI[1] = 4f;
                                    }
                                    else if (type == 595 || type == 735)
{
                                        nPC.immune[owner] = 5;
                                    }
                                    else if (type == 927)
{
                                        nPC.immune[owner] = 4;
                                    }
                                    else if (type == 286)
{
                                        nPC.immune[owner] = 5;
                                    }
                                    else if (type == 443)
{
                                        nPC.immune[owner] = 8;
                                    }
                                    else if (type >= 424 && type <= 426)
{
                                        nPC.immune[owner] = 5;
                                    }
                                    else if (type == 634 || type == 635)
{
                                        nPC.immune[owner] = 5;
                                    }
                                    else if (type == 659)
{
                                        nPC.immune[owner] = 5;
                                    }
                                    else if (type == 246)
{
                                        nPC.immune[owner] = 7;
                                    }
                                    else if (type == 249)
{
                                        nPC.immune[owner] = 7;
                                    }
                                    else if (type == 16)
{
                                        nPC.immune[owner] = 8;
                                    }
                                    else if (type == 409)
{
                                        nPC.immune[owner] = 6;
                                    }
                                    else if (type == 311)
{
                                        nPC.immune[owner] = 7;
                                    }
                                    else if (type == 582 || type == 902)
{
                                        nPC.immune[owner] = 7;
                                        if (ai[0] != 1f)
{
                                            ai[0] = 1f;
                                            netUpdate = true;
                                        }
                                    }
                                    else
{
                                        if (type == 451)
{
                                            if (ai[0] == 0f)
{
                                                ai[0] += penetrate;
                                            }
                                            else
{
                                                ai[0] -= penetrate + 1;
                                            }
                                            ai[1] = 0f;
                                            netUpdate = true;
                                            NPC obj3 = Main.npc[i];
                                            obj3.position -= Main.npc[i].netOffset;
                                            break;
                                        }
                                        if (type == 864)
{
                                            array[i] = 10;
                                            nPC.immune[owner] = 0;
                                            if (ai[0] > 0f)
{
                                                ai[0] = -1f;
                                                ai[1] = 0f;
                                                netUpdate = true;
                                            }
                                        }
                                        else if (type == 661 || type == 856)
{
                                            array[i] = 8;
                                            nPC.immune[owner] = 0;
                                        }
                                        else if (type == 866)
{
                                            array[i] = -1;
                                            nPC.immune[owner] = 0;
                                            penetrate--;
                                            if (penetrate == 0)
{
                                                penetrate = 1;
                                                damage = 0;
                                                ai[1] = -1f;
                                                netUpdate = true;
                                                NPC obj4 = Main.npc[i];
                                                obj4.position -= Main.npc[i].netOffset;
                                                break;
                                            }
                                            if (owner == Main.myPlayer)
{
                                                int num36 = FindTargetWithLineOfSight();
                                                float num37 = ai[1];
                                                ai[1] = num36;
                                                if (ai[1] != num37)
{
                                                    netUpdate = true;
                                                }
                                                if (num36 != -1)
{
                                                    velocity = ((Vector2)(ref velocity)).Length() * DirectionTo(Main.npc[num36].Center);
                                                }
                                            }
                                        }
                                        else if (usesLocalNPCImmunity && localNPCHitCooldown != -2)
{
                                            nPC.immune[owner] = 0;
                                            array[i] = localNPCHitCooldown;
                                        }
                                        else if (penetrate != 1 || appliesImmunityTimeOnSingleHits)
{
                                            nPC.immune[owner] = 10;
                                        }
                                    }
                                    if (type == 710)
{
                                        BetsySharpnel(i);
                                    }
                                    CombinedHooks.OnHitNPCWithProj(this, nPC, in strike, num27);
                                    if (penetrate > 0 && type != 317 && type != 866)
{
                                        if (type == 357)
{
                                            damage = (int)((double)damage * 0.8);
                                        }
                                        penetrate--;
                                        if (penetrate == 0)
{
                                            NPC obj5 = Main.npc[i];
                                            obj5.position -= Main.npc[i].netOffset;
                                            if (stopsDealingDamageAfterPenetrateHits)
{
                                                penetrate = -1;
                                                damage = 0;
                                            }
                                            flag23 = false;
                                        }
                                    }
                                    if (aiStyle == 7)
{
                                        ai[0] = 1f;
                                        damage = 0;
                                        netUpdate = true;
                                    }
                                    else if (aiStyle == 13)
{
                                        ai[0] = 1f;
                                        netUpdate = true;
                                    }
                                    else if (aiStyle == 69)
{
                                        ai[0] = 1f;
                                        netUpdate = true;
                                    }
                                    else if (type == 607)
{
                                        ai[0] = 1f;
                                        netUpdate = true;
                                        friendly = false;
                                    }
                                    else if (type == 638 || type == 639 || type == 640)
{
                                        array[i] = -1;
                                        nPC.immune[owner] = 0;
                                        damage = (int)((double)damage * 0.96);
                                    }
                                    else if (type == 617)
{
                                        array[i] = 8;
                                        nPC.immune[owner] = 0;
                                    }
                                    else if (type == 656)
{
                                        array[i] = 8;
                                        nPC.immune[owner] = 0;
                                        localAI[0] += 1f;
                                    }
                                    else if (type == 618)
{
                                        array[i] = 20;
                                        nPC.immune[owner] = 0;
                                    }
                                    else if (type == 642)
{
                                        array[i] = 10;
                                        nPC.immune[owner] = 0;
                                    }
                                    else if (type == 857)
{
                                        array[i] = 10;
                                        nPC.immune[owner] = 0;
                                    }
                                    else if (type == 611 || type == 612)
{
                                        array[i] = 6;
                                        nPC.immune[owner] = 4;
                                    }
                                    else if (type == 645)
{
                                        array[i] = -1;
                                        nPC.immune[owner] = 0;
                                        if (ai[1] != -1f)
{
                                            ai[0] = 0f;
                                            ai[1] = -1f;
                                            netUpdate = true;
                                        }
                                    }
                                    numHits++;
                                    if (type == 697)
{
                                        if (ai[0] >= 42f)
{
                                            localAI[1] = 1f;
                                        }
                                    }
                                    else if (type == 699)
{
                                        SummonMonkGhast();
                                    }
                                    else if (type == 706)
{
                                        damage = (int)((float)damage * 0.95f);
                                    }
                                    else if (type == 728)
{
                                        SummonSuperStarSlash(nPC.Center);
                                    }
                                    else if (type == 34)
{
                                        if (ai[0] == -1f)
{
                                            ai[1] = -1f;
                                            netUpdate = true;
                                        }
                                    }
                                    else if (type == 79)
{
                                        if (ai[0] == -1f)
{
                                            ai[1] = -1f;
                                            netUpdate = true;
                                        }
                                        ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.RainbowRodHit, new ParticleOrchestraSettings
{
                                            PositionInWorld = nPC.Center,
                                            MovementVector = velocity
                                        });
                                    }
                                    else if (type == 931)
{
                                        int num38 = FindTargetWithLineOfSight();
                                        if (num38 != -1)
{
                                            ai[0] = num38;
                                            netUpdate = true;
                                        }
                                    }
                                    else if (aiStyle == 165)
{
                                        if (nPC.active)
{
                                            Main.player[owner].MinionAttackTargetNPC = i;
                                        }
                                    }
                                    else if (type == 623)
{
                                        ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.StardustPunch, new ParticleOrchestraSettings
{
                                            PositionInWorld = Vector2.Lerp(base.Center, nPC.Hitbox.ClosestPointInRect(base.Center), 0.5f) + new Vector2(0f, Main.rand.NextFloatDirection() * 10f),
                                            MovementVector = new Vector2((float)direction, Main.rand.NextFloatDirection() * 0.5f) * (3f + 3f * Main.rand.NextFloat())
                                        });
                                    }
                                    if (flag12)
{
                                        Main.player[owner].SetMeleeHitCooldown(i, Main.player[owner].itemAnimation);
                                    }
                                }
                            }
                        }
                    }
                    NPC obj6 = Main.npc[i];
                    obj6.position -= Main.npc[i].netOffset;
                }
            }
            if (flag22 && Main.player[Main.myPlayer].hostile)
            {
                for (int m = 0; m < 255; m++)
                {
                    if (m == owner)
                    {
                        continue;
                    }
                    Player player3 = Main.player[m];
                    if (!player3.active || player3.dead || player3.immune || !player3.hostile || playerImmune[m] > 0 || (Main.player[Main.myPlayer].team != 0 && Main.player[Main.myPlayer].team == player3.team))
                    {
                        continue;
                    }
                    bool flag19 = !ownerHitCheck;
                    if (ownerHitCheck)
                    {
                        flag19 |= CanHitWithMeleeWeapon(player3);
                    }
                    if (!flag19 || !Colliding(rectangle, player3.getRect()) || !CombinedHooks.CanHitPvpWithProj(this, player3))
                    {
                        continue;
                    }
                    if (aiStyle == 3)
                    {
                        if (ai[0] == 0f)
{
                            velocity.X = 0f - velocity.X;
                            velocity.Y = 0f - velocity.Y;
                            netUpdate = true;
                        }
                        ai[0] = 1f;
                    }
                    else if (aiStyle == 16)
                    {
                        if (timeLeft > 3)
{
                            timeLeft = 3;
                        }
                        if (player3.position.X + (float)(player3.width / 2) < position.X + (float)(width / 2))
{
                            direction = -1;
                        }
                        else
{
                            direction = 1;
                        }
                    }
                    else if (aiStyle == 68)
                    {
                        if (timeLeft > 3)
{
                            timeLeft = 3;
                        }
                        if (player3.position.X + (float)(player3.width / 2) < position.X + (float)(width / 2))
{
                            direction = -1;
                        }
                        else
{
                            direction = 1;
                        }
                    }
                    int playerIndex = owner;
                    if (ProjectileID.Sets.IsAGravestone[type])
                    {
                        playerIndex = (int)ai[0];
                    }
                    PlayerDeathReason playerDeathReason = PlayerDeathReason.ByProjectile(playerIndex, whoAmI);
                    if (type == 41 && timeLeft > 1)
                    {
                        timeLeft = 1;
                    }
                    bool flag20 = false;
                    int num39 = Main.DamageVar((int)((float)damage * num), Main.player[owner].luck);
                    bool dodgeable = IsDamageDodgable();
                    if (!player3.immune)
                    {
                        StatusPvP(m);
                    }
                    TryDoingOnHitEffects(player3);
                    int num40 = (int)player3.Hurt(playerDeathReason, num39, direction, pvp: true, quiet: false, flag20, -1, dodgeable);
                    if (num40 > 0 && Main.player[owner].ghostHeal && friendly && !hostile)
                    {
                        ghostHeal(num40, new Vector2(player3.Center.X, player3.Center.Y), player3);
                    }
                    if (type == 304 && num40 > 0)
                    {
                        vampireHeal(num40, new Vector2(player3.Center.X, player3.Center.Y), player3);
                    }
                    if ((melee || ProjectileID.Sets.IsAWhip[type]) && Main.player[owner].meleeEnchant == 7)
                    {
                        NewProjectile(GetProjectileSource_FromThis(), player3.Center.X, player3.Center.Y, player3.velocity.X, player3.velocity.Y, 289, 0, 0f, owner);
                    }
                    if (Main.netMode != 0)
                    {
                        NetMessage.SendPlayerHurt(m, playerDeathReason, num39, direction, flag20, pvp: true, -1);
                    }
                    playerImmune[m] = 40;
                    if (penetrate > 0)
                    {
                        penetrate--;
                        if (penetrate == 0)
{
                            break;
                        }
                    }
                    if (aiStyle == 7)
                    {
                        ai[0] = 1f;
                        damage = 0;
                        netUpdate = true;
                    }
                    else if (aiStyle == 13)
                    {
                        ai[0] = 1f;
                        netUpdate = true;
                    }
                    else if (aiStyle == 69)
                    {
                        ai[0] = 1f;
                        netUpdate = true;
                    }
                }
            }
        }
        if (type == 10 && Main.netMode != 1)
        {
            for (int n = 0; n < 200; n++)
            {
                NPC nPC2 = Main.npc[n];
                if (!nPC2.active)
                {
                    continue;
                }
                if (nPC2.type == 534)
                {
                    if (((Rectangle)(ref rectangle)).Intersects(nPC2.Hitbox))
                    {
                        nPC2.Transform(441);
                    }
                }
                else
                {
                    if (nPC2.type != 687 || !((Rectangle)(ref rectangle)).Intersects(nPC2.Hitbox))
                    {
                        continue;
                    }
                    nPC2.Transform(683);
                    Vector2 vector9 = nPC2.Center - new Vector2(20f);
                    Utils.PoofOfSmoke(vector9);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(106, -1, -1, null, (int)vector9.X, vector9.Y);
                    }
                    if (!NPC.unlockedSlimeYellowSpawn)
                    {
                        NPC.unlockedSlimeYellowSpawn = true;
                        if (Main.netMode == 2)
{
                            NetMessage.SendData(7);
                        }
                    }
                }
            }
        }
        if ((type == 11 || type == 463) && Main.netMode != 1)
        {
            bool crimson = type == 463;
            Rectangle value2 = default(Rectangle);
            for (int num41 = 0; num41 < 200; num41++)
            {
                if (Main.npc[num41].active)
                {
                    ((Rectangle)(ref value2))._002Ector((int)Main.npc[num41].position.X, (int)Main.npc[num41].position.Y, Main.npc[num41].width, Main.npc[num41].height);
                    if (((Rectangle)(ref rectangle)).Intersects(value2))
                    {
                        Main.npc[num41].AttemptToConvertNPCToEvil(crimson);
                    }
                }
            }
        }
        if (Main.netMode == 2 || !hostile || Main.myPlayer >= 255 || damage <= 0)
        {
            return;
        }
        int num42 = -1;
        switch (type)
        {
        case 452:
        case 454:
        case 455:
        case 462:
            num42 = 1;
            break;
        case 871:
        case 872:
        case 873:
        case 874:
        case 919:
        case 923:
        case 924:
            num42 = 1;
            break;
        }
        int myPlayer = Main.myPlayer;
        bool flag21 = Main.player[myPlayer].active && !Main.player[myPlayer].dead && (!Main.player[myPlayer].immune || num42 != -1);
        if (flag21 && type == 281)
        {
            flag21 = ai[1] - 1f == (float)myPlayer;
        }
        if (Main.getGoodWorld && type == 281)
        {
            flag21 = true;
        }
        if (ModProjectile != null)
        {
            num42 = ModProjectile.CooldownSlot;
        }
        if (!flag21 || !Colliding(rectangle, Main.player[myPlayer].getRect()) || !CombinedHooks.CanBeHitByProjectile(Main.player[myPlayer], this))
        {
            return;
        }
        int num44 = direction;
        num44 = ((!(Main.player[myPlayer].position.X + (float)(Main.player[myPlayer].width / 2) < position.X + (float)(width / 2))) ? 1 : (-1));
        if (!Main.player[myPlayer].CanParryAgainst(Main.player[myPlayer].Hitbox, base.Hitbox, velocity))
        {
            int num45 = Main.DamageVar(damage, 0f - Main.player[owner].luck) * 2;
            if (type == 961)
            {
                if (penetrate == 1)
                {
                    damage = 0;
                    penetrate = -1;
                }
                else
                {
                    damage = (int)((double)damage * 0.7);
                }
            }
            bool dodgeable2 = IsDamageDodgable();
            int playerIndex2 = -1;
            if (ProjectileID.Sets.IsAGravestone[type])
            {
                playerIndex2 = (int)ai[0];
            }
            if (Main.player[myPlayer].Hurt(PlayerDeathReason.ByProjectile(playerIndex2, whoAmI), num45, num44, pvp: false, quiet: false, Crit: false, num42, dodgeable2, ArmorPenetration) > 0.0 && !Main.player[myPlayer].dead)
            {
                StatusPlayer(myPlayer);
            }
            if (trap)
            {
                Main.player[myPlayer].trapDebuffSource = true;
                if (Main.player[myPlayer].dead)
                {
                    AchievementsHelper.HandleSpecialEvent(Main.player[myPlayer], 4);
                }
            }
        }
        if (type == 435 || type == 682)
        {
            penetrate--;
        }
        if (type == 436)
        {
            penetrate--;
        }
        if (type == 681)
        {
            timeLeft = 0;
        }
        if (type == 437)
        {
            penetrate--;
        }
    }
References Terraria.Projectile._cachedConditions_notNull, Terraria.Projectile._cachedConditions_solid, Terraria.Projectile._javelinsMax10, Terraria.Projectile._javelinsMax6, Terraria.Projectile._javelinsMax8, Terraria.Player.accDreamCatcher, Terraria.Entity.active, Terraria.Player.addDPS(), Terraria.NPC.ai, Terraria.Projectile.ai, Terraria.NPC.aiStyle, Terraria.Projectile.aiStyle, Terraria.ID.ProjectileID.Sets.AllowsContactDamageFromJellyfish, Terraria.Projectile.appliesImmunityTimeOnSingleHits, Terraria.Player.ApplyBannerOffenseBuff(), Terraria.Player.armorPenetration, Terraria.Projectile.ArmorPenetration, Terraria.Projectile.arrow, Terraria.NPC.AttemptToConvertNPCToEvil(), Terraria.Player.beeDamage(), Terraria.Player.beeKB(), Terraria.Player.beetleCountdown, Terraria.Player.beetleCounter, Terraria.Player.beetleOffense, Terraria.Player.beetleOrbs, Terraria.Player.beeType(), Terraria.ID.NPCID.Sets.BelongsToInvasionOldOnesArmy, Terraria.Projectile.BetsySharpnel(), Terraria.Projectile.BombsHurtPlayers(), Terraria.DataStructures.PlayerDeathReason.ByProjectile(), Terraria.NPC.CanBeChasedBy(), Terraria.ModLoader.CombinedHooks.CanBeHitByProjectile(), Terraria.Projectile.CanBeReflected(), Terraria.ModLoader.ProjectileLoader.CanDamage(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Player.CanHitNPCWithMeleeHit(), Terraria.ModLoader.CombinedHooks.CanHitNPCWithProj(), Terraria.ModLoader.CombinedHooks.CanHitPvpWithProj(), Terraria.Projectile.CanHitWithMeleeWeapon(), Terraria.Player.CanNPCBeHitByPlayerOrPlayerProjectile(), Terraria.Player.CanParryAgainst(), Terraria.Entity.Center, Terraria.WorldBuilding.Searches.Chain(), Terraria.Player.ClearBuff(), Terraria.Projectile.Colliding(), Terraria.ModLoader.ModProjectile.CooldownSlot, Terraria.ID.ProjectileID.Count, Terraria.Projectile.CountEnemiesWhoAreImmuneToMeRightNow(), Terraria.Player.Counterweight(), Terraria.ID.NPCID.Sets.CountsAsCritter, Terraria.Projectile.CritChance, Terraria.ID.ProjectileID.Sets.CultistIsResistantTo, Terraria.Projectile.CutTiles(), Terraria.Projectile.damage, Terraria.Projectile.Damage_GetHitbox(), Terraria.Projectile.DamageType, Terraria.Main.DamageVar(), Terraria.Player.dead, Terraria.Entity.direction, Terraria.Entity.DirectionTo(), Terraria.ID.ProjectileID.Sets.DontApplyParryDamageBuff, Terraria.NPC.dontTakeDamage, Terraria.NPC.dontTakeDamageFromHostiles, Terraria.Projectile.EmitBlackLightningParticles(), Terraria.Main.expertMode, Terraria.WorldBuilding.WorldUtils.Find(), Terraria.Projectile.FindStardustDragonHeadOfOwner(), Terraria.Projectile.FindTargetWithLineOfSight(), Terraria.Projectile.frame, Terraria.NPC.friendly, Terraria.Projectile.friendly, Terraria.Main.getGoodWorld, Terraria.Projectile.GetItemSource_OnHit(), Terraria.Projectile.GetProjectileSource_FromThis(), Terraria.NPC.getRect(), Terraria.Player.getRect(), Terraria.Player.ghostHeal, Terraria.Projectile.ghostHeal(), Terraria.Player.ghostHurt, Terraria.Projectile.ghostHurt(), Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Main.hardMode, Terraria.Player.hasLuckyCoin, Terraria.Entity.height, Terraria.Entity.Hitbox, Terraria.Player.HorsemansBlade_SpawnPumpkin(), Terraria.Player.hostile, Terraria.Projectile.hostile, Terraria.Player.Hurt(), Terraria.Projectile.idStaticNPCHitCooldown, Terraria.ID.ProjectileID.Sets.ImmediatelyUpdatesNPCBuffFlags, Terraria.NPC.immortal, Terraria.NPC.immune, Terraria.Player.immune, Terraria.ID.ProjectileID.Sets.IsAGravestone, Terraria.ID.ProjectileID.Sets.IsAMineThatDealsTripleDamageWhenStationary, Terraria.ID.ProjectileID.Sets.IsARocketThatDealsDoubleDamageToPrimaryEnemy, Terraria.ID.ProjectileID.Sets.IsAWhip, Terraria.Projectile.IsDamageDodgable(), Terraria.Projectile.IsNPCIndexImmuneToProjectileType(), Terraria.Main.item, Terraria.Player.itemAnimation, Terraria.Projectile.Kill(), Terraria.Player.killClothier, Terraria.Player.killGuide, Terraria.Projectile.KillOldestJavelin(), Terraria.Projectile.knockBack, Terraria.Player.lastCreatureHit, Terraria.Projectile.LightDisc_Bounce(), Terraria.Projectile.localAI, Terraria.Projectile.localNPCHitCooldown, Terraria.Projectile.localNPCImmunity, Terraria.Player.luck, Terraria.Projectile.magic, Terraria.NPC.maxBuffs, Terraria.Projectile.maxPenetrate, Terraria.Projectile.melee, Terraria.Player.meleeEnchant, Terraria.Projectile.minion, Terraria.Player.MinionAttackTargetNPC, Terraria.ModLoader.ProjectileLoader.MinionContactDamage(), Terraria.ID.ProjectileID.Sets.MinionShot, Terraria.ModLoader.CombinedHooks.ModifyHitNPCWithProj(), Terraria.Player.moonLeech, Terraria.Main.myPlayer, Terraria.Player.nebulaCD, Terraria.Main.netMode, Terraria.NPC.netOffset, Terraria.Projectile.netUpdate, Terraria.Item.NewItem(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.NPC.noTileCollide, Terraria.Main.npc, Terraria.Projectile.npcProj, Terraria.Item.NPCtoBanner(), Terraria.Projectile.numHits, Terraria.Projectile.numUpdates, Terraria.ModLoader.CombinedHooks.OnHitNPCWithProj(), Terraria.Player.OnKillNPC(), Terraria.Player.ownedProjectileCounts, Terraria.Projectile.owner, Terraria.Projectile.ownerHitCheck, Terraria.Player.parryDamageBuff, Terraria.Projectile.penetrate, Terraria.Projectile.perIDStaticNPCImmunity, Terraria.Player.phantasmTime, Terraria.Main.player, Terraria.Projectile.playerImmune, Terraria.Utils.PoofOfSmoke(), Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.projFrames, Terraria.Main.projPet, Terraria.Main.rand, Terraria.Utils.RandomVector2(), Terraria.ID.NPCID.Sets.ReflectStarShotsInForTheWorthy, Terraria.Main.remixWorld, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Projectile.scale, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendPlayerHurt(), Terraria.NetMessage.SendStrikeNPC(), Terraria.Projectile.sentry, Terraria.ID.ProjectileID.Sets.SentryShot, Terraria.Player.SetMeleeHitCooldown(), Terraria.Player.setMonkT2, Terraria.Player.setMonkT3, Terraria.Player.setNebula, Terraria.Entity.Size, Terraria.Collision.SolidTiles(), Terraria.Item.stack, Terraria.ID.ProjectileID.Sets.StardustDragon, Terraria.Projectile.StatusNPC(), Terraria.Projectile.StatusPlayer(), Terraria.Projectile.StatusPvP(), Terraria.Projectile.stopsDealingDamageAfterPenetrateHits, Terraria.ID.ProjectileID.Sets.StormTiger, Terraria.Player.strongBees, Terraria.Projectile.SummonMonkGhast(), Terraria.Projectile.SummonSuperStarSlash(), Terraria.ID.ProjectileID.Sets.SummonTagDamageMultiplier, Terraria.Player.TakeDamageFromJellyfish(), Terraria.Player.team, Terraria.Projectile.tileCollide, Terraria.Projectile.timeLeft, Terraria.Item.timeLeftInWhichTheItemCannotBeTakenByEnemies, Terraria.Projectile.trap, Terraria.Player.trapDebuffSource, Terraria.NPC.trapImmune, Terraria.Projectile.TryDoingOnHitEffects(), Terraria.NPC.type, Terraria.Projectile.type, Terraria.NPC.unlockedSlimeYellowSpawn, Terraria.Projectile.usesIDStaticNPCImmunity, Terraria.Projectile.usesLocalNPCImmunity, Terraria.Projectile.usesOwnerMeleeHitCD, Terraria.ModLoader.DamageClass.UseStandardCritCalcs, Terraria.Projectile.vampireHeal(), Terraria.Entity.velocity, Terraria.Entity.whoAmI, Terraria.Entity.width, and Terraria.ID.NPCID.Sets.ZappingJellyfish.
Referenced by Terraria.Projectile.AI_100_Medusa(), Terraria.Mount.CastSuperCartLaser(), Terraria.Projectile.HandleMovement(), Terraria.Projectile.NewProjectile(), Terraria.Projectile.NewProjectile(), and Terraria.Projectile.Update().