TModLoader: Terraria.Projectile.AI_152_SuperStarSlash
AI_152_SuperStarSlash()
void Terraria.Projectile.AI_152_SuperStarSlash () inline private
    {
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_043b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02db: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_036d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0377: Unknown result type (might be due to invalid IL or missing references)
        //IL_037c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0404: Unknown result type (might be due to invalid IL or missing references)
        //IL_040a: Unknown result type (might be due to invalid IL or missing references)
        //IL_040b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0420: Unknown result type (might be due to invalid IL or missing references)
        //IL_0425: Unknown result type (might be due to invalid IL or missing references)
        float num = (float)Math.PI / 2f;
        bool flag = true;
        if (type == 976)
        {
            flag = false;
        }
        if (flag)
        {
            alpha -= 10;
            int num2 = 100;
            if (alpha < num2)
            {
                alpha = num2;
            }
        }
        if (soundDelay == 0)
        {
            if (type == 977)
            {
                soundDelay = -1;
                SoundEngine.PlaySound(in SoundID.Item1, position);
            }
            else if (type == 976)
            {
                soundDelay = -1;
            }
            else
            {
                soundDelay = 20 + Main.rand.Next(40);
                SoundEngine.PlaySound(in SoundID.Item9, position);
            }
        }
        if (ai[0] != 0f)
        {
            if (type == 976)
            {
                velocity = velocity.RotatedBy(ai[0]);
            }
            else
            {
                int num3 = 10 * MaxUpdates;
                velocity = velocity.RotatedBy(ai[0] / (float)num3);
            }
        }
        if (type == 977)
        {
            velocity *= 0.96f;
            if (Main.rand.Next(8) == 0)
            {
                Dust dust = Dust.NewDustDirect(base.Center, 0, 0, 172, velocity.X * 0.1f, velocity.Y * 0.1f, 100, default(Color), 0.9f);
                dust.noGravity = true;
                dust.position = base.Center;
                dust.velocity = Main.rand.NextVector2Circular(1f, 1f) + velocity * 0.5f;
            }
        }
        if (type == 976)
        {
            if (Collision.LavaCollision(position, width, height))
            {
                Kill();
                return;
            }
            if (++frameCounter >= 2)
            {
                frameCounter = 0;
                if (++frame >= 7)
                {
                    frame = 0;
                }
            }
            float fromValue = 60 - timeLeft;
            float fromMax = ai[1] + 20f;
            float num4 = Utils.Remap(fromValue, ai[1], fromMax, 0f, 1f) * Utils.Remap(fromValue, ai[1], ai[1] + 60f, 1f, 0f);
            velocity = velocity.SafeNormalize(Vector2.UnitY) * (4f + 12f * (1f - num4));
            Opacity = Utils.Remap(fromValue, 0f, 10f, 0f, 1f) * Utils.Remap(fromValue, 30f, 60f, 1f, 0f);
            num = 0f;
            if (Main.rand.Next(3) == 0)
            {
                Dust dust2 = Dust.NewDustDirect(position, width, height, 40, 0f, 0f, 0, default(Color), 1.2f);
                dust2.noGravity = true;
                dust2.velocity = velocity * 0.5f;
            }
            if (localAI[1] == 0f)
            {
                localAI[1] = 1f;
                for (int i = 0; i < 10; i++)
                {
                    Dust.NewDustDirect(position, width, height, 40, 0f, 0f, 0, default(Color), 0.7f).velocity = velocity.SafeNormalize(Vector2.UnitY).RotatedBy(Main.rand.NextFloat() * ((float)Math.PI * 2f) * 0.25f) * (Main.rand.NextFloat() * 3f);
                }
            }
        }
        rotation = velocity.ToRotation() + num;
        tileCollide = false;
    }
References Terraria.Projectile.ai, Terraria.Projectile.alpha, Terraria.Projectile.frame, Terraria.Projectile.frameCounter, Terraria.Entity.height, Terraria.ID.SoundID.Item1, Terraria.ID.SoundID.Item9, Terraria.Projectile.Kill(), Terraria.Collision.LavaCollision(), Terraria.Projectile.localAI, Terraria.Projectile.MaxUpdates, Terraria.Dust.NewDustDirect(), Terraria.Projectile.Opacity, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Utils.Remap(), Terraria.Projectile.rotation, Terraria.Projectile.soundDelay, Terraria.Projectile.tileCollide, Terraria.Projectile.timeLeft, Terraria.Projectile.type, Terraria.Entity.velocity, and Terraria.Entity.width.