TModLoader: Terraria.Projectile.DoRainbowCrystalStaffExplosion
DoRainbowCrystalStaffExplosion()
void Terraria.Projectile.DoRainbowCrystalStaffExplosion () inline private
Definition at line 91609 of file Projectile.cs.
    {
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0218: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0240: Unknown result type (might be due to invalid IL or missing references)
        //IL_0245: Unknown result type (might be due to invalid IL or missing references)
        //IL_02da: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        Vector2 spinningpoint = Utils.RotatedByRandom(new Vector2(0f, -3f), 3.1415927410125732);
        float num = Main.rand.Next(7, 13);
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(2.1f, 2f);
        Color newColor = Main.hslToRgb(ai[0], 1f, 0.5f);
        ((Color)(ref newColor)).A = byte.MaxValue;
        for (float num2 = 0f; num2 < num; num2 += 1f)
        {
            int num3 = Dust.NewDust(base.Center, 0, 0, 267, 0f, 0f, 0, newColor);
            Main.dust[num3].position = base.Center;
            Main.dust[num3].velocity = spinningpoint.RotatedBy((float)Math.PI * 2f * num2 / num) * vector * (0.8f + Main.rand.NextFloat() * 0.4f);
            Main.dust[num3].noGravity = true;
            Main.dust[num3].scale = 2f;
            Main.dust[num3].fadeIn = Main.rand.NextFloat() * 2f;
            if (num3 != 6000)
            {
                Dust dust = Dust.CloneDust(num3);
                dust.scale /= 2f;
                dust.fadeIn /= 2f;
                dust.color = new Color(255, 255, 255, 255);
            }
        }
        for (float num4 = 0f; num4 < num; num4 += 1f)
        {
            int num5 = Dust.NewDust(base.Center, 0, 0, 267, 0f, 0f, 0, newColor);
            Main.dust[num5].position = base.Center;
            Main.dust[num5].velocity = spinningpoint.RotatedBy((float)Math.PI * 2f * num4 / num) * vector * (0.8f + Main.rand.NextFloat() * 0.4f);
            Dust obj = Main.dust[num5];
            obj.velocity *= Main.rand.NextFloat() * 0.8f;
            Main.dust[num5].noGravity = true;
            Main.dust[num5].scale = Main.rand.NextFloat() * 1f;
            Main.dust[num5].fadeIn = Main.rand.NextFloat() * 2f;
            if (num5 != 6000)
            {
                Dust dust2 = Dust.CloneDust(num5);
                dust2.scale /= 2f;
                dust2.fadeIn /= 2f;
                dust2.color = new Color(255, 255, 255, 255);
            }
        }
    }
References Terraria.Dust.CloneDust(), Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Main.hslToRgb(), Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.position, Terraria.Main.rand, Terraria.Utils.RotatedByRandom(), Terraria.Dust.scale, and Terraria.Dust.velocity.