TModLoader: Terraria.Projectile.AI_191_TrueNightsEdge
AI_191_TrueNightsEdge()
void Terraria.Projectile.AI_191_TrueNightsEdge () inline private
    {
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_057b: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0346: Unknown result type (might be due to invalid IL or missing references)
        //IL_034c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0351: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_035e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0365: Unknown result type (might be due to invalid IL or missing references)
        //IL_036c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0371: Unknown result type (might be due to invalid IL or missing references)
        //IL_0405: Unknown result type (might be due to invalid IL or missing references)
        //IL_040c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0416: Unknown result type (might be due to invalid IL or missing references)
        //IL_0421: Unknown result type (might be due to invalid IL or missing references)
        //IL_0426: Unknown result type (might be due to invalid IL or missing references)
        //IL_042b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0217: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0812: Unknown result type (might be due to invalid IL or missing references)
        //IL_0836: Unknown result type (might be due to invalid IL or missing references)
        //IL_0841: Unknown result type (might be due to invalid IL or missing references)
        //IL_084b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0856: Unknown result type (might be due to invalid IL or missing references)
        //IL_085b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0862: Unknown result type (might be due to invalid IL or missing references)
        //IL_0647: Unknown result type (might be due to invalid IL or missing references)
        //IL_0651: Unknown result type (might be due to invalid IL or missing references)
        //IL_0656: Unknown result type (might be due to invalid IL or missing references)
        //IL_0665: Unknown result type (might be due to invalid IL or missing references)
        //IL_043a: Unknown result type (might be due to invalid IL or missing references)
        //IL_044f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0455: Unknown result type (might be due to invalid IL or missing references)
        //IL_0230: Unknown result type (might be due to invalid IL or missing references)
        //IL_0246: Unknown result type (might be due to invalid IL or missing references)
        //IL_024e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0258: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_0268: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_0286: Unknown result type (might be due to invalid IL or missing references)
        //IL_028e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0299: Unknown result type (might be due to invalid IL or missing references)
        //IL_029e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_047b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0480: Unknown result type (might be due to invalid IL or missing references)
        //IL_0485: Unknown result type (might be due to invalid IL or missing references)
        //IL_048a: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_088f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0891: Unknown result type (might be due to invalid IL or missing references)
        //IL_08af: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08da: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0904: Unknown result type (might be due to invalid IL or missing references)
        //IL_0912: Unknown result type (might be due to invalid IL or missing references)
        //IL_0918: Unknown result type (might be due to invalid IL or missing references)
        //IL_0920: Unknown result type (might be due to invalid IL or missing references)
        //IL_094e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0955: Unknown result type (might be due to invalid IL or missing references)
        //IL_095f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0964: Unknown result type (might be due to invalid IL or missing references)
        //IL_0969: Unknown result type (might be due to invalid IL or missing references)
        //IL_0971: Unknown result type (might be due to invalid IL or missing references)
        //IL_0978: Unknown result type (might be due to invalid IL or missing references)
        //IL_0982: Unknown result type (might be due to invalid IL or missing references)
        //IL_0987: Unknown result type (might be due to invalid IL or missing references)
        //IL_098c: Unknown result type (might be due to invalid IL or missing references)
        //IL_09be: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07af: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0780: Unknown result type (might be due to invalid IL or missing references)
        //IL_078a: Unknown result type (might be due to invalid IL or missing references)
        //IL_078f: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0706: Unknown result type (might be due to invalid IL or missing references)
        //IL_070d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0718: Unknown result type (might be due to invalid IL or missing references)
        //IL_071d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0722: Unknown result type (might be due to invalid IL or missing references)
        //IL_0726: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04da: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a75: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a80: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a85: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b19: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b36: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b50: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b73: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9d: Unknown result type (might be due to invalid IL or missing references)
        float num = 50f;
        float num9 = 15f;
        float num10 = ai[1] + num;
        float num11 = num10 + num9;
        float num12 = 77f;
        if (type == 985)
        {
            num = 0f;
            num10 = ai[1];
            num11 = ai[1] + 25f;
            num12 = num11;
        }
        if (localAI[0] == 0f && type == 973)
        {
            SoundEngine.PlaySound(in SoundID.Item8, base.position);
        }
        localAI[0] += 1f;
        if (type == 985 && localAI[1] == 1f)
        {
            localAI[0] += 2f;
        }
        if (type == 973 && damage == 0 && localAI[0] < MathHelper.Lerp(num10, num11, 0.5f))
        {
            localAI[0] += 6f;
        }
        Opacity = Utils.Remap(localAI[0], 0f, ai[1], 0f, 1f) * Utils.Remap(localAI[0], num10, num11, 1f, 0f);
        if (localAI[0] >= num11)
        {
            localAI[1] = 1f;
            Kill();
            return;
        }
        Player player = Main.player[owner];
        float fromValue = localAI[0] / ai[1];
        float num13 = Utils.Remap(localAI[0], ai[1] * 0.4f, num11, 0f, 1f);
        direction = (spriteDirection = (int)ai[0]);
        if (type == 973)
        {
            int num14 = 3;
            if (damage != 0 && localAI[0] >= num12 + (float)num14)
            {
                damage = 0;
            }
            if (damage != 0)
            {
                int num15 = 80;
                bool flag = false;
                float num16 = velocity.ToRotation();
                for (float num2 = -1f; num2 <= 1f; num2 += 0.5f)
                {
                    Vector2 position = base.Center + (num16 + num2 * ((float)Math.PI / 4f) * 0.25f).ToRotationVector2() * (float)num15 * 0.5f * scale;
                    Vector2 position2 = base.Center + (num16 + num2 * ((float)Math.PI / 4f) * 0.25f).ToRotationVector2() * (float)num15 * scale;
                    if (!Collision.SolidTiles(base.Center, 0, 0) && Collision.CanHit(position, 0, 0, position2, 0, 0))
                    {
                        flag = true;
                        break;
                    }
                }
                if (!flag)
                {
                    damage = 0;
                }
            }
            fromValue = localAI[0] / ai[1];
            localAI[1] += 1f;
            num13 = Utils.Remap(localAI[1], ai[1] * 0.4f, num11, 0f, 1f);
            base.Center = player.RotatedRelativePoint(player.MountedCenter) - velocity + velocity * num13 * num13 * num12;
            rotation += ai[0] * ((float)Math.PI * 2f) * (4f + Opacity * 4f) / 90f;
            scale = Utils.Remap(localAI[0], ai[1] + 2f, num11, 1.12f, 1f) * ai[2];
            float f = rotation + Main.rand.NextFloatDirection() * ((float)Math.PI / 2f) * 0.7f;
            Vector2 vector = base.Center + f.ToRotationVector2() * 84f * scale;
            if (Main.rand.Next(5) == 0)
            {
                Dust dust5 = Dust.NewDustPerfect(vector, 14, null, 150, default(Color), 1.4f);
                dust5.noLight = (dust5.noLightEmittence = true);
            }
            for (int i = 0; (float)i < 3f * Opacity; i++)
            {
                Vector2 vector2 = velocity.SafeNormalize(Vector2.UnitX);
                int num3 = ((Main.rand.NextFloat() < Opacity) ? 75 : 27);
                Dust dust6 = Dust.NewDustPerfect(vector, num3, velocity * 0.2f + vector2 * 3f, 100, default(Color), 1.4f);
                dust6.noGravity = true;
                dust6.customData = Opacity * 0.2f;
            }
        }
        if (type != 985)
        {
            return;
        }
        ownerHitCheck = localAI[0] <= 6f;
        if (localAI[0] >= MathHelper.Lerp(num10, num11, 0.65f))
        {
            damage = 0;
        }
        float fromValue2 = 1f - (1f - num13) * (1f - num13);
        rotation = velocity.ToRotation();
        scale = Utils.Remap(fromValue2, 0f, 1f, 1.5f, 1f) * ai[2];
        num13 = Utils.Remap(localAI[0], ai[1] / 2f, num11, 0f, 1f);
        Opacity = Utils.Remap(localAI[0], 0f, ai[1] * 0.5f, 0f, 1f) * Utils.Remap(localAI[0], num11 - 12f, num11, 1f, 0f);
        if (((Vector2)(ref velocity)).Length() > 8f)
        {
            velocity *= 0.94f;
            new Vector2(32f, 32f);
            float num4 = Utils.Remap(fromValue, 0.7f, 1f, 110f, 110f);
            if (localAI[1] == 0f)
            {
                bool flag2 = false;
                for (float num5 = -1f; num5 <= 1f; num5 += 0.5f)
                {
                    Vector2 position4 = base.Center + (rotation + num5 * ((float)Math.PI / 4f) * 0.25f).ToRotationVector2() * num4 * 0.5f * scale;
                    Vector2 position3 = base.Center + (rotation + num5 * ((float)Math.PI / 4f) * 0.25f).ToRotationVector2() * num4 * scale;
                    if (Collision.CanHit(position4, 0, 0, position3, 0, 0))
                    {
                        flag2 = true;
                        break;
                    }
                }
                if (!flag2)
                {
                    localAI[1] = 1f;
                }
            }
            if (localAI[1] == 1f && ((Vector2)(ref velocity)).Length() > 8f)
            {
                velocity *= 0.8f;
            }
            if (localAI[1] == 1f)
            {
                velocity *= 0.88f;
            }
        }
        float num6 = rotation + Main.rand.NextFloatDirection() * ((float)Math.PI / 2f) * 0.9f;
        Vector2 vector3 = base.Center + num6.ToRotationVector2() * 85f * scale;
        (num6 + ai[0] * ((float)Math.PI / 2f)).ToRotationVector2();
        Color value = default(Color);
        ((Color)(ref value))._002Ector(64, 220, 96);
        Color value2 = default(Color);
        ((Color)(ref value2))._002Ector(15, 84, 125);
        Lighting.AddLight(base.Center + rotation.ToRotationVector2() * 85f * scale, ((Color)(ref value)).ToVector3());
        for (int j = 0; j < 3; j++)
        {
            if (Main.rand.NextFloat() < Opacity + 0.1f)
            {
                Color.Lerp(Color.Lerp(Color.Lerp(value2, value, Utils.Remap(fromValue, 0f, 0.6f, 0f, 1f)), Color.White, Utils.Remap(fromValue, 0.6f, 0.8f, 0f, 0.5f)), Color.White, Main.rand.NextFloat() * 0.3f);
                Dust dust3 = Dust.NewDustPerfect(vector3, 107, velocity * 0.7f, 100, default(Color) * Opacity, 0.8f * Opacity);
                dust3.scale *= 0.7f;
                dust3.velocity += player.velocity * 0.1f;
                dust3.position -= dust3.velocity * 6f;
            }
        }
        if (damage == 0)
        {
            localAI[0] += 3f;
            velocity *= 0.76f;
        }
        if (localAI[0] < 10f && (localAI[1] == 1f || damage == 0))
        {
            localAI[0] += 1f;
            velocity *= 0.85f;
            for (int k = 0; k < 4; k++)
            {
                float num7 = Main.rand.NextFloatDirection();
                float num8 = 1f - Math.Abs(num7);
                num6 = rotation + num7 * ((float)Math.PI / 2f) * 0.9f;
                vector3 = base.Center + num6.ToRotationVector2() * 85f * scale;
                Color.Lerp(Color.Lerp(Color.Lerp(value2, value, Utils.Remap(fromValue, 0f, 0.6f, 0f, 1f)), Color.White, Utils.Remap(fromValue, 0.6f, 0.8f, 0f, 0.5f)), Color.White, Main.rand.NextFloat() * 0.3f);
                Dust dust4 = Dust.NewDustPerfect(vector3, 107, velocity.RotatedBy(num7 * ((float)Math.PI / 4f)) * 0.2f * Main.rand.NextFloat(), 100, default(Color), 1.4f * num8);
                dust4.velocity += player.velocity * 0.1f;
                dust4.position -= dust4.velocity * Main.rand.NextFloat() * 3f;
            }
        }
    }
References Terraria.Lighting.AddLight(), Terraria.Collision.CanHit(), Terraria.ID.SoundID.Item8, Terraria.Player.MountedCenter, Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Utils.Remap(), Terraria.Player.RotatedRelativePoint(), and Terraria.Collision.SolidTiles().