TModLoader: Terraria.Projectile.AI_019_Spears_Old
AI_019_Spears_Old()
void Terraria.Projectile.AI_019_Spears_Old () inline private
Definition at line 48943 of file Projectile.cs.
    {
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_097f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0985: Unknown result type (might be due to invalid IL or missing references)
        //IL_0992: Unknown result type (might be due to invalid IL or missing references)
        //IL_0997: Unknown result type (might be due to invalid IL or missing references)
        //IL_099c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b53: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b96: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0beb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bfb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b45: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ebf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ece: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f56: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dce: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ddd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dfa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e54: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e71: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e80: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e85: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea2: Unknown result type (might be due to invalid IL or missing references)
        //IL_030b: Unknown result type (might be due to invalid IL or missing references)
        //IL_032b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0434: Unknown result type (might be due to invalid IL or missing references)
        //IL_045c: Unknown result type (might be due to invalid IL or missing references)
        //IL_047c: Unknown result type (might be due to invalid IL or missing references)
        //IL_049b: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_072a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0734: Unknown result type (might be due to invalid IL or missing references)
        //IL_0739: Unknown result type (might be due to invalid IL or missing references)
        //IL_0741: Unknown result type (might be due to invalid IL or missing references)
        //IL_0761: Unknown result type (might be due to invalid IL or missing references)
        //IL_0780: Unknown result type (might be due to invalid IL or missing references)
        //IL_0786: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = Main.player[owner].RotatedRelativePoint(Main.player[owner].MountedCenter);
        direction = Main.player[owner].direction;
        Main.player[owner].heldProj = whoAmI;
        Main.player[owner].MatchItemTimeToItemAnimation();
        position.X = vector.X - (float)(width / 2);
        position.Y = vector.Y - (float)(height / 2);
        bool flag = Main.player[owner].itemAnimation < Main.player[owner].itemAnimationMax / 3;
        if (!Main.player[owner].frozen)
        {
            if (type == 46)
            {
                if (ai[0] == 0f)
                {
                    ai[0] = 3f;
                    netUpdate = true;
                }
                if (flag)
                {
                    ai[0] -= 1.6f;
                }
                else
                {
                    ai[0] += 1.4f;
                }
            }
            else if (type == 105)
            {
                if (ai[0] == 0f)
                {
                    ai[0] = 3f;
                    netUpdate = true;
                }
                if (flag)
                {
                    ai[0] -= 2.4f;
                }
                else
                {
                    ai[0] += 2.1f;
                }
            }
            else if (type == 367)
            {
                spriteDirection = -direction;
                if (ai[0] == 0f)
                {
                    ai[0] = 3f;
                    netUpdate = true;
                }
                if (flag)
                {
                    ai[0] -= 1.6f;
                }
                else
                {
                    ai[0] += 1.5f;
                }
            }
            else if (type == 368)
            {
                spriteDirection = -direction;
                if (ai[0] == 0f)
                {
                    ai[0] = 3f;
                    netUpdate = true;
                }
                if (flag)
                {
                    ai[0] -= 1.5f;
                }
                else
                {
                    ai[0] += 1.4f;
                }
            }
            else if (type == 222)
            {
                if (ai[0] == 0f)
                {
                    ai[0] = 3f;
                    netUpdate = true;
                }
                if (flag)
                {
                    ai[0] -= 2.4f;
                    if (localAI[0] == 0f && Main.myPlayer == owner)
                    {
                        localAI[0] = 1f;
                        NewProjectile(GetProjectileSource_FromThis(), base.Center.X + velocity.X * ai[0], base.Center.Y + velocity.Y * ai[0], velocity.X, velocity.Y, 228, damage, knockBack, owner);
                    }
                }
                else
                {
                    ai[0] += 2.1f;
                }
            }
            else if (type == 342)
            {
                if (ai[0] == 0f)
                {
                    ai[0] = 3f;
                    netUpdate = true;
                }
                if (flag)
                {
                    ai[0] -= 2.4f;
                    if (localAI[0] == 0f && Main.myPlayer == owner)
                    {
                        localAI[0] = 1f;
                        if (Collision.CanHit(Main.player[owner].position, Main.player[owner].width, Main.player[owner].height, new Vector2(base.Center.X + velocity.X * ai[0], base.Center.Y + velocity.Y * ai[0]), width, height))
{
                            NewProjectile(GetProjectileSource_FromThis(), base.Center.X + velocity.X * ai[0], base.Center.Y + velocity.Y * ai[0], velocity.X * 2.4f, velocity.Y * 2.4f, 343, (int)((double)damage * 0.8), knockBack * 0.85f, owner);
                        }
                    }
                }
                else
                {
                    ai[0] += 2.1f;
                }
            }
            else if (type == 47)
            {
                if (ai[0] == 0f)
                {
                    ai[0] = 4f;
                    netUpdate = true;
                }
                if (flag)
                {
                    ai[0] -= 1.2f;
                }
                else
                {
                    ai[0] += 0.9f;
                }
            }
            else if (type == 153)
            {
                spriteDirection = -direction;
                if (ai[0] == 0f)
                {
                    ai[0] = 4f;
                    netUpdate = true;
                }
                if (flag)
                {
                    ai[0] -= 1.5f;
                }
                else
                {
                    ai[0] += 1.3f;
                }
            }
            else if (type == 49)
            {
                if (ai[0] == 0f)
                {
                    ai[0] = 4f;
                    netUpdate = true;
                }
                if (flag)
                {
                    ai[0] -= 1.1f;
                }
                else
                {
                    ai[0] += 0.85f;
                }
            }
            else if (type == 730)
            {
                spriteDirection = -direction;
                if (ai[0] == 0f)
                {
                    ai[0] = 8f;
                    netUpdate = true;
                    if (localAI[0] == 0f && Main.myPlayer == owner)
                    {
                        localAI[0] = 1f;
                        Vector2 vector2 = velocity * 4f;
                        NewProjectile(GetProjectileSource_FromThis(), base.Center.X + velocity.X * ai[0], base.Center.Y + velocity.Y * ai[0], vector2.X, vector2.Y, 732, (int)((double)damage * 1.25), knockBack * 0.5f, owner);
                    }
                }
                if (flag)
                {
                    ai[0] -= 1.5f;
                }
                else
                {
                    ai[0] += 1.2f;
                }
            }
            else if (type == 64 || type == 215)
            {
                spriteDirection = -direction;
                if (ai[0] == 0f)
                {
                    ai[0] = 3f;
                    netUpdate = true;
                }
                if (flag)
                {
                    ai[0] -= 1.9f;
                }
                else
                {
                    ai[0] += 1.7f;
                }
            }
            else if (type == 66 || type == 97 || type == 212 || type == 218)
            {
                spriteDirection = -direction;
                if (ai[0] == 0f)
                {
                    ai[0] = 3f;
                    netUpdate = true;
                }
                if (flag)
                {
                    ai[0] -= 2.1f;
                }
                else
                {
                    ai[0] += 1.9f;
                }
            }
            else if (type == 130)
            {
                spriteDirection = -direction;
                if (ai[0] == 0f)
                {
                    ai[0] = 3f;
                    netUpdate = true;
                }
                if (flag)
                {
                    ai[0] -= 1.3f;
                }
                else
                {
                    ai[0] += 1f;
                }
            }
        }
        position += velocity * ai[0];
        if (type == 130)
        {
            if (ai[1] == 0f || ai[1] == 4f || ai[1] == 8f || ai[1] == 12f || ai[1] == 16f || ai[1] == 20f || ai[1] == 24f)
            {
                NewProjectile(GetProjectileSource_FromThis(), position.X + (float)(width / 2), position.Y + (float)(height / 2), velocity.X, velocity.Y, 131, damage / 3, 0f, owner);
            }
            ai[1] += 1f;
        }
        if (Main.player[owner].ItemAnimationEndingOrEnded)
        {
            Kill();
        }
        rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 2.355f;
        if (spriteDirection == -1)
        {
            rotation -= 1.57f;
        }
        if (type == 46)
        {
            if (Main.rand.Next(5) == 0)
            {
                Dust.NewDust(position, width, height, 14, 0f, 0f, 150, default(Color), 1.4f);
            }
            int num = Dust.NewDust(position, width, height, 27, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.2f);
            Main.dust[num].noGravity = true;
            Main.dust[num].velocity.X /= 2f;
            Main.dust[num].velocity.Y /= 2f;
            num = Dust.NewDust(position - velocity * 2f, width, height, 27, 0f, 0f, 150, default(Color), 1.4f);
            Main.dust[num].velocity.X /= 5f;
            Main.dust[num].velocity.Y /= 5f;
        }
        if (type == 730)
        {
            if (Main.rand.Next(5) == 0)
            {
                Dust dust = Dust.NewDustDirect(position, width, height, 226, 0f, 0f, 150, default(Color), 0.7f);
                dust.noGravity = true;
                dust.velocity *= 1.4f;
            }
            if (Main.rand.Next(5) == 0)
            {
                Dust.NewDustDirect(position, width, height, 226, 0f, 0f, 150, default(Color), 0.5f).velocity.Y -= 0.5f;
            }
        }
        else if (type == 105)
        {
            if (Main.rand.Next(3) == 0)
            {
                int num2 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 57, velocity.X * 0.2f, velocity.Y * 0.2f, 200, default(Color), 1.2f);
                Dust obj = Main.dust[num2];
                obj.velocity += velocity * 0.3f;
                Dust obj2 = Main.dust[num2];
                obj2.velocity *= 0.2f;
            }
            if (Main.rand.Next(4) == 0)
            {
                int num3 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 43, 0f, 0f, 254, default(Color), 0.3f);
                Dust obj3 = Main.dust[num3];
                obj3.velocity += velocity * 0.5f;
                Dust obj4 = Main.dust[num3];
                obj4.velocity *= 0.5f;
            }
        }
        else if (type == 153)
        {
            int num4 = Dust.NewDust(position - velocity * 3f, width, height, 115, velocity.X * 0.4f, velocity.Y * 0.4f, 140);
            Main.dust[num4].noGravity = true;
            Main.dust[num4].fadeIn = 1.25f;
            Dust obj5 = Main.dust[num4];
            obj5.velocity *= 0.25f;
        }
    }
References Terraria.Collision.CanHit(), Terraria.Main.dust, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Main.player, and Terraria.Main.rand.