TModLoader: Terraria.Projectile.GetFairyQueenWeaponsColor
GetFairyQueenWeaponsColor()
Color Terraria.Projectile.GetFairyQueenWeaponsColor (float alphaChannelMultiplier = 1f, float lerpToWhite = 0f, float? rawHueOverride = null) inline
Definition at line 20478 of file Projectile.cs.
    {
        //IL_0def: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dfe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e03: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cfd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d02: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d14: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d19: Unknown result type (might be due to invalid IL or missing references)
        //IL_066d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0672: Unknown result type (might be due to invalid IL or missing references)
        //IL_0679: Unknown result type (might be due to invalid IL or missing references)
        //IL_067e: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0688: Unknown result type (might be due to invalid IL or missing references)
        //IL_068a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0690: Unknown result type (might be due to invalid IL or missing references)
        //IL_0695: Unknown result type (might be due to invalid IL or missing references)
        float num = ai[1];
        if (rawHueOverride.HasValue)
        {
            num = rawHueOverride.Value;
        }
        float num2 = (num + 0.5f) % 1f;
        float saturation = 1f;
        float luminosity = 0.5f;
        if (Main.player[owner].active)
        {
            switch (Main.player[owner].name)
            {
            case "Cenx":
            {
                float amount5 = Utils.PingPongFrom01To010(num2);
                amount5 = MathHelper.SmoothStep(0f, 1f, amount5);
                amount5 = MathHelper.SmoothStep(0f, 1f, amount5);
                Color color3 = Color.Lerp(new Color(0.3f, 1f, 0.2f), Color.HotPink, amount5);
                if (lerpToWhite != 0f)
                {
                    color3 = Color.Lerp(color3, Color.White, lerpToWhite);
                }
                ((Color)(ref color3)).A = (byte)((float)(int)((Color)(ref color3)).A * alphaChannelMultiplier);
                return color3;
            }
            case "Crowno":
                luminosity = MathHelper.Lerp(0.25f, 0.4f, Utils.Turn01ToCyclic010(num2));
                num2 = MathHelper.Lerp(127f / 180f, 47f / 60f, Utils.Turn01ToCyclic010(num2));
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                break;
            case "Yoraiz0r":
                num2 = MathHelper.Lerp(0.9f, 0.95f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                break;
            case "Jaxrud":
                num2 = MathHelper.Lerp(13f / 72f, 0.43611112f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                break;
            case "Lazure":
                num2 = MathHelper.Lerp(8f / 15f, 83f / 90f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                break;
            case "Leinfors":
                num2 = MathHelper.Lerp(0.7f, 0.77f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                break;
            case "Grox The Great":
                num2 = MathHelper.Lerp(0.31f, 0.5f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 1f, 0.8f);
                break;
            case "Acamaeda":
                num2 = MathHelper.Lerp(0.06f, 0.28f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                break;
            case "Alchemystics":
                num2 = MathHelper.Lerp(0.74f, 0.96f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.6f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                break;
            case "Antithesis":
            {
                num2 = 0.51f;
                float amount6 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                luminosity = MathHelper.Lerp(0f, 0.5f, amount6);
                break;
            }
            case "Aurora3500":
                num2 = MathHelper.Lerp(0.33f, 0.8f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                break;
            case "Bame":
            {
                float amount4 = Utils.PingPongFrom01To010(num2);
                amount4 = MathHelper.SmoothStep(0f, 1f, amount4);
                amount4 = MathHelper.SmoothStep(0f, 1f, amount4);
                Color color2 = Color.Lerp(Color.Yellow, new Color(0.4f, 0f, 0.75f), amount4);
                if (lerpToWhite != 0f)
                {
                    color2 = Color.Lerp(color2, Color.White, lerpToWhite);
                }
                ((Color)(ref color2)).A = (byte)((float)(int)((Color)(ref color2)).A * alphaChannelMultiplier);
                return color2;
            }
            case "Criddle":
                num2 = MathHelper.Lerp(0.05f, 0.15f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                break;
            case "Darthkitten":
            {
                num2 = 1f;
                float amount3 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                luminosity = MathHelper.Lerp(1f, 0.4f, amount3);
                break;
            }
            case "darthmorf":
            {
                num2 = 0f;
                float amount2 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                luminosity = MathHelper.Lerp(0f, 0.2f, amount2);
                break;
            }
            case "Discipile":
            {
                num2 = 0.53f;
                float amount14 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                luminosity = MathHelper.Lerp(0.05f, 0.5f, amount14);
                break;
            }
            case "Doylee":
                num2 = MathHelper.Lerp(0.68f, 1f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                break;
            case "Ghostar":
            {
                num2 = 0.66f;
                float amount13 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                luminosity = MathHelper.Lerp(0.15f, 0.85f, amount13);
                break;
            }
            case "Jenosis":
                num2 = MathHelper.Lerp(0.9f, 1.13f, Utils.Turn01ToCyclic010(num2)) % 1f;
                luminosity = 0.5f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                break;
            case "Kazzymodus":
            {
                num2 = 0.33f;
                float amount12 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                luminosity = MathHelper.Lerp(0.15f, 0.4f, amount12);
                break;
            }
            case "Khaios":
            {
                num2 = 0.33f;
                float amount11 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                luminosity = MathHelper.Lerp(0f, 0.2f, amount11);
                break;
            }
            case "Loki":
            {
                num2 = 0f;
                float amount10 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                luminosity = MathHelper.Lerp(0f, 0.25f, amount10);
                break;
            }
            case "ManaUser":
                num2 = MathHelper.Lerp(0.41f, 0.57f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                break;
            case "Mid":
            {
                num2 = 0f;
                float amount9 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                luminosity = MathHelper.Lerp(0f, 0.9f, amount9);
                break;
            }
            case "Nimbus":
                num2 = MathHelper.Lerp(0.75f, 1f, Utils.Turn01ToCyclic010(num2));
                luminosity = 1f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.8f);
                break;
            case "Nike Leon":
                num2 = MathHelper.Lerp(0.04f, 0.1f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                break;
            case "ppowersteef":
                num2 = MathHelper.Lerp(0f, 0.15f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                break;
            case "RBrandon":
                num2 = 0.03f;
                luminosity = 0.3f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                break;
            case "Redigit":
                num2 = 0.7f;
                luminosity = 0.5f;
                break;
            case "Serenity":
            {
                num2 = 0.85f;
                float amount8 = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                luminosity = MathHelper.Lerp(1f, 0.5f, amount8);
                break;
            }
            case "Sigma":
                num2 = MathHelper.Lerp(0f, 0.12f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                break;
            case "teiull":
                num2 = MathHelper.Lerp(0.66f, 1f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                break;
            case "Unit One":
            {
                float amount7 = Utils.PingPongFrom01To010(num2);
                amount7 = MathHelper.SmoothStep(0f, 1f, amount7);
                Color color = Color.Lerp(Color.Yellow, Color.Blue, amount7);
                if (lerpToWhite != 0f)
                {
                    color = Color.Lerp(color, Color.White, lerpToWhite);
                }
                ((Color)(ref color)).A = (byte)((float)(int)((Color)(ref color)).A * alphaChannelMultiplier);
                return color;
            }
            case "Vulpes Inculta":
                num2 = MathHelper.Lerp(0.65f, 0.75f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.5f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.5f, 0.5f);
                break;
            case "Waze3174":
                num2 = MathHelper.Lerp(0.33f, 0f, Utils.Turn01ToCyclic010(num2));
                luminosity = 0.3f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                break;
            case "Xman101":
            {
                num2 = 0.06f;
                float amount = (float)Math.Cos(num * ((float)Math.PI * 2f)) * 0.5f + 0.5f;
                luminosity = MathHelper.Lerp(0f, 0.5f, amount);
                break;
            }
            case "Zoomo":
                num2 = 0.77f;
                luminosity = 0.5f;
                alphaChannelMultiplier = MathHelper.Lerp(alphaChannelMultiplier, 0.6f, 0.5f);
                break;
            }
        }
        Color color4 = Main.hslToRgb(num2, saturation, luminosity);
        color4 *= Opacity;
        if (lerpToWhite != 0f)
        {
            color4 = Color.Lerp(color4, Color.White, lerpToWhite);
        }
        ((Color)(ref color4)).A = (byte)((float)(int)((Color)(ref color4)).A * alphaChannelMultiplier);
        return color4;
    }
References Terraria.Projectile.ai, Terraria.Main.hslToRgb(), Terraria.Projectile.Opacity, Terraria.Projectile.owner, Terraria.Utils.PingPongFrom01To010(), Terraria.Main.player, and Terraria.Utils.Turn01ToCyclic010().