TModLoader: Terraria.Projectile.AI_121_StardustDragon
AI_121_StardustDragon()
void Terraria.Projectile.AI_121_StardustDragon () inline private
    {
        //IL_062c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0631: Unknown result type (might be due to invalid IL or missing references)
        //IL_0633: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_016f: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_0368: Unknown result type (might be due to invalid IL or missing references)
        //IL_036b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0370: Unknown result type (might be due to invalid IL or missing references)
        //IL_0375: Unknown result type (might be due to invalid IL or missing references)
        //IL_024e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0254: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_08af: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0909: Unknown result type (might be due to invalid IL or missing references)
        //IL_090e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0938: Unknown result type (might be due to invalid IL or missing references)
        //IL_0942: Unknown result type (might be due to invalid IL or missing references)
        //IL_0944: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0826: Unknown result type (might be due to invalid IL or missing references)
        //IL_084a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0850: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_0973: Unknown result type (might be due to invalid IL or missing references)
        //IL_0951: Unknown result type (might be due to invalid IL or missing references)
        //IL_0953: Unknown result type (might be due to invalid IL or missing references)
        //IL_0955: Unknown result type (might be due to invalid IL or missing references)
        //IL_095c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0963: Unknown result type (might be due to invalid IL or missing references)
        //IL_0968: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_02da: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0302: Unknown result type (might be due to invalid IL or missing references)
        //IL_0307: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_045c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0466: Unknown result type (might be due to invalid IL or missing references)
        //IL_046b: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0404: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0346: Unknown result type (might be due to invalid IL or missing references)
        //IL_034b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0352: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_0317: Unknown result type (might be due to invalid IL or missing references)
        //IL_0321: Unknown result type (might be due to invalid IL or missing references)
        //IL_0326: Unknown result type (might be due to invalid IL or missing references)
        //IL_042a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0432: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0537: Unknown result type (might be due to invalid IL or missing references)
        //IL_053c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0572: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cd: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        if ((int)Main.timeForVisualEffects % 120 == 0)
        {
            netUpdate = true;
        }
        if (!player.active)
        {
            active = false;
            return;
        }
        bool num26 = type == 625;
        bool flag = type == 625 || type == 626 || type == 627 || type == 628;
        int num19 = 10;
        if (flag)
        {
            if (player.dead)
            {
                player.stardustDragon = false;
            }
            if (player.stardustDragon)
            {
                timeLeft = 2;
            }
            num19 = 30;
            if (Main.rand.Next(30) == 0)
            {
                int num21 = Dust.NewDust(position, width, height, 135, 0f, 0f, 0, default(Color), 2f);
                Main.dust[num21].noGravity = true;
                Main.dust[num21].fadeIn = 2f;
                Point point = Main.dust[num21].position.ToTileCoordinates();
                if (WorldGen.InWorld(point.X, point.Y, 5) && WorldGen.SolidTile(point.X, point.Y))
                {
                    Main.dust[num21].noLight = true;
                }
            }
        }
        Vector2 center2;
        if (num26)
        {
            Vector2 center = player.Center;
            float num22 = 700f;
            float num23 = 1000f;
            int num24 = -1;
            if (Distance(center) > 2000f)
            {
                base.Center = center;
                netUpdate = true;
            }
            NPC ownerMinionAttackTargetNPC = OwnerMinionAttackTargetNPC;
            if (ownerMinionAttackTargetNPC != null && ownerMinionAttackTargetNPC.CanBeChasedBy(this) && Distance(ownerMinionAttackTargetNPC.Center) < num22 * 2f)
            {
                num24 = ownerMinionAttackTargetNPC.whoAmI;
                if (ownerMinionAttackTargetNPC.boss)
                {
                    _ = ownerMinionAttackTargetNPC.whoAmI;
                }
                else
                {
                    _ = ownerMinionAttackTargetNPC.whoAmI;
                }
            }
            if (num24 < 0)
            {
                for (int i = 0; i < 200; i++)
                {
                    NPC nPC = Main.npc[i];
                    if (nPC.CanBeChasedBy(this) && player.Distance(nPC.Center) < num23 && Distance(nPC.Center) < num22)
                    {
                        num24 = i;
                        _ = nPC.boss;
                    }
                }
            }
            if (num24 != -1)
            {
                NPC nPC2 = Main.npc[num24];
                Vector2 vector = nPC2.Center - base.Center;
                (vector.X > 0f).ToDirectionInt();
                (vector.Y > 0f).ToDirectionInt();
                float num25 = 0.4f;
                if (((Vector2)(ref vector)).Length() < 600f)
                {
                    num25 = 0.6f;
                }
                if (((Vector2)(ref vector)).Length() < 300f)
                {
                    num25 = 0.8f;
                }
                float num27 = ((Vector2)(ref vector)).Length();
                center2 = nPC2.Size;
                if (num27 > ((Vector2)(ref center2)).Length() * 0.75f)
                {
                    velocity += Vector2.Normalize(vector) * num25 * 1.5f;
                    if (Vector2.Dot(velocity, vector) < 0.25f)
                    {
                        velocity *= 0.8f;
                    }
                }
                float num10 = 30f;
                if (((Vector2)(ref velocity)).Length() > num10)
                {
                    velocity = Vector2.Normalize(velocity) * num10;
                }
            }
            else
            {
                float num11 = 0.2f;
                Vector2 vector2 = center - base.Center;
                if (((Vector2)(ref vector2)).Length() < 200f)
                {
                    num11 = 0.12f;
                }
                if (((Vector2)(ref vector2)).Length() < 140f)
                {
                    num11 = 0.06f;
                }
                if (((Vector2)(ref vector2)).Length() > 100f)
                {
                    if (Math.Abs(center.X - base.Center.X) > 20f)
                    {
                        velocity.X += num11 * (float)Math.Sign(center.X - base.Center.X);
                    }
                    if (Math.Abs(center.Y - base.Center.Y) > 10f)
                    {
                        velocity.Y += num11 * (float)Math.Sign(center.Y - base.Center.Y);
                    }
                }
                else if (((Vector2)(ref velocity)).Length() > 2f)
                {
                    velocity *= 0.96f;
                }
                if (Math.Abs(velocity.Y) < 1f)
                {
                    velocity.Y -= 0.1f;
                }
                float num12 = 15f;
                if (((Vector2)(ref velocity)).Length() > num12)
                {
                    velocity = Vector2.Normalize(velocity) * num12;
                }
            }
            rotation = velocity.ToRotation() + (float)Math.PI / 2f;
            int num28 = direction;
            direction = (spriteDirection = ((velocity.X > 0f) ? 1 : (-1)));
            if (num28 != direction)
            {
                netUpdate = true;
            }
            float num13 = MathHelper.Clamp(localAI[0], 0f, 50f);
            position = base.Center;
            scale = 1f + num13 * 0.01f;
            width = (height = (int)((float)num19 * scale));
            base.Center = position;
            if (alpha > 0)
            {
                for (int j = 0; j < 2; j++)
                {
                    int num14 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 135, 0f, 0f, 100, default(Color), 2f);
                    Main.dust[num14].noGravity = true;
                    Main.dust[num14].noLight = true;
                }
                alpha -= 42;
                if (alpha < 0)
                {
                    alpha = 0;
                }
            }
        }
        else
        {
            bool flag2 = false;
            Vector2 vector3 = Vector2.Zero;
            _ = Vector2.Zero;
            float num15 = 0f;
            float num16 = 0f;
            float num17 = 1f;
            if (ai[1] == 1f)
            {
                ai[1] = 0f;
                netUpdate = true;
            }
            int byUUID = GetByUUID(owner, (int)ai[0]);
            if (Main.projectile.IndexInRange(byUUID))
            {
                Projectile projectile = Main.projectile[byUUID];
                if (flag && projectile.active && (projectile.type == 625 || projectile.type == 626 || projectile.type == 627))
                {
                    flag2 = true;
                    vector3 = projectile.Center;
                    _ = projectile.velocity;
                    num15 = projectile.rotation;
                    num17 = MathHelper.Clamp(projectile.scale, 0f, 50f);
                    num16 = 16f;
                    _ = projectile.alpha;
                    projectile.localAI[0] = localAI[0] + 1f;
                    if (projectile.type != 625)
                    {
                        projectile.localAI[1] = whoAmI;
                    }
                    if (owner == Main.myPlayer && type == 628 && projectile.type == 625)
                    {
                        projectile.Kill();
                        Kill();
                        return;
                    }
                }
            }
            if (!flag2)
            {
                for (int k = 0; k < 1000; k++)
                {
                    Projectile projectile2 = Main.projectile[k];
                    if (projectile2.active && projectile2.owner == owner && ProjectileID.Sets.StardustDragon[projectile2.type] && projectile2.localAI[1] == ai[0])
                    {
                        ai[0] = projectile2.projUUID;
                        projectile2.localAI[1] = whoAmI;
                        netUpdate = true;
                    }
                }
                return;
            }
            if (alpha > 0)
            {
                for (int l = 0; l < 2; l++)
                {
                    int num18 = Dust.NewDust(position, width, height, 135, 0f, 0f, 100, default(Color), 2f);
                    Main.dust[num18].noGravity = true;
                    Main.dust[num18].noLight = true;
                }
            }
            alpha -= 42;
            if (alpha < 0)
            {
                alpha = 0;
            }
            velocity = Vector2.Zero;
            Vector2 vector4 = vector3 - base.Center;
            if (num15 != rotation)
            {
                float num20 = MathHelper.WrapAngle(num15 - rotation);
                Vector2 spinningpoint = vector4;
                double radians = num20 * 0.1f;
                center2 = default(Vector2);
                vector4 = spinningpoint.RotatedBy(radians, center2);
            }
            rotation = vector4.ToRotation() + (float)Math.PI / 2f;
            position = base.Center;
            scale = num17;
            width = (height = (int)((float)num19 * scale));
            base.Center = position;
            if (vector4 != Vector2.Zero)
            {
                base.Center = vector3 - Vector2.Normalize(vector4) * num16 * num17;
            }
            spriteDirection = ((vector4.X > 0f) ? 1 : (-1));
        }
        position.X = MathHelper.Clamp(position.X, 160f, (float)(Main.maxTilesX * 16 - 160));
        position.Y = MathHelper.Clamp(position.Y, 160f, (float)(Main.maxTilesY * 16 - 160));
    }
References Terraria.Entity.active, Terraria.Projectile.alpha, Terraria.Entity.Center, Terraria.Player.dead, Terraria.Entity.Distance(), Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.WorldGen.InWorld(), Terraria.Projectile.Kill(), Terraria.Projectile.localAI, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Main.npc, Terraria.Main.player, Terraria.Dust.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Projectile.rotation, Terraria.Projectile.scale, Terraria.WorldGen.SolidTile(), Terraria.ID.ProjectileID.Sets.StardustDragon, Terraria.Player.stardustDragon, Terraria.Main.timeForVisualEffects, Terraria.Projectile.type, and Terraria.Entity.velocity.