TModLoader: Terraria.Projectile.AI_181_FairyQueenRangedItemShot
AI_181_FairyQueenRangedItemShot()
void Terraria.Projectile.AI_181_FairyQueenRangedItemShot () inline private
    {
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        ai[0] += 1f;
        alpha = (int)MathHelper.Lerp(255f, 0f, Utils.GetLerpValue(0f, 10f, ai[0], clamped: true));
        rotation = velocity.ToRotation();
        if (Main.rand.Next(6) == 0)
        {
            Dust dust = Dust.NewDustPerfect(base.Center, 267);
            dust.fadeIn = 1f;
            dust.noGravity = true;
            dust.alpha = 100;
            dust.color = GetFairyQueenWeaponsColor(1f, Main.rand.NextFloat() * 0.4f);
            dust.noLightEmittence = true;
            dust.scale *= 1.5f;
        }
    }
References Terraria.Utils.GetLerpValue(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), and Terraria.Main.rand.