TModLoader: Terraria.Projectile.AI_171_HallowBossRainbowStreak
AI_171_HallowBossRainbowStreak()
void Terraria.Projectile.AI_171_HallowBossRainbowStreak () inline private
Definition at line 47923 of file Projectile.cs.
    {
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0377: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_0301: Unknown result type (might be due to invalid IL or missing references)
        //IL_0306: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_030f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0276: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0282: Unknown result type (might be due to invalid IL or missing references)
        //IL_0287: Unknown result type (might be due to invalid IL or missing references)
        //IL_0323: Unknown result type (might be due to invalid IL or missing references)
        //IL_034e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cf: Unknown result type (might be due to invalid IL or missing references)
        bool flag = false;
        bool flag2 = false;
        float num = 140f;
        float num2 = 30f;
        float num3 = 0.98f;
        float value = 0.05f;
        float value2 = 0.1f;
        float num4 = 30f;
        if (type == 931)
        {
            num = 180f;
            num2 = 20f;
            num4 = 30f;
            num3 = 0.97f;
            value = 0.075f;
            value2 = 0.125f;
            if (timeLeft == 238)
            {
                int num5 = alpha;
                alpha = 0;
                Color fairyQueenWeaponsColor = GetFairyQueenWeaponsColor();
                alpha = num5;
                for (int i = 0; i < 3; i++)
                {
                    Dust dust = Dust.NewDustPerfect(base.Center, 267, Main.rand.NextVector2CircularEdge(3f, 3f) * (Main.rand.NextFloat() * 0.5f + 0.5f), 0, fairyQueenWeaponsColor);
                    dust.scale *= 1.2f;
                    dust.noGravity = true;
                }
            }
        }
        if ((float)timeLeft > num)
        {
            flag = true;
        }
        else if ((float)timeLeft > num2)
        {
            flag2 = true;
        }
        if (flag)
        {
            float num6 = (float)Math.Cos((float)whoAmI % 6f / 6f + position.X / 320f + position.Y / 160f);
            velocity *= num3;
            velocity = velocity.RotatedBy(num6 * ((float)Math.PI * 2f) * 0.125f * 1f / 30f);
        }
        if (friendly)
        {
            int num7 = (int)ai[0];
            if (Main.npc.IndexInRange(num7) && !Main.npc[num7].CanBeChasedBy(this))
            {
                num7 = -1;
                ai[0] = -1f;
                netUpdate = true;
            }
            if (num7 == -1)
            {
                int num8 = FindTargetWithLineOfSight();
                if (num8 != -1)
                {
                    num7 = num8;
                    ai[0] = num8;
                    netUpdate = true;
                }
            }
        }
        if (flag2)
        {
            int num9 = (int)ai[0];
            Vector2 value3 = velocity;
            if (hostile && Main.player.IndexInRange(num9))
            {
                Player player = Main.player[num9];
                value3 = DirectionTo(player.Center) * num4;
            }
            if (friendly)
            {
                if (Main.npc.IndexInRange(num9))
                {
                    if (timeLeft < 10)
                    {
                        timeLeft = 10;
                    }
                    NPC nPC = Main.npc[num9];
                    value3 = DirectionTo(nPC.Center) * num4;
                }
                else
                {
                    timeLeft--;
                }
            }
            float amount = MathHelper.Lerp(value, value2, Utils.GetLerpValue(num, 30f, timeLeft, clamped: true));
            velocity = Vector2.SmoothStep(velocity, value3, amount);
            if (type == 931)
            {
                velocity *= MathHelper.Lerp(0.85f, 1f, Utils.GetLerpValue(0f, 90f, timeLeft, clamped: true));
            }
        }
        Opacity = Utils.GetLerpValue(240f, 220f, timeLeft, clamped: true);
        rotation = velocity.ToRotation() + (float)Math.PI / 2f;
    }
References Terraria.NPC.CanBeChasedBy(), Terraria.Entity.Center, Terraria.Utils.GetLerpValue(), Terraria.Dust.NewDustPerfect(), Terraria.Main.npc, Terraria.Main.player, and Terraria.Main.rand.