TModLoader: Terraria.Projectile.AI_160_Kites
AI_160_Kites()
void Terraria.Projectile.AI_160_Kites () inline private
Definition at line 51412 of file Projectile.cs.
    {
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_0407: Unknown result type (might be due to invalid IL or missing references)
        //IL_0408: Unknown result type (might be due to invalid IL or missing references)
        //IL_040d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0411: Unknown result type (might be due to invalid IL or missing references)
        //IL_0416: Unknown result type (might be due to invalid IL or missing references)
        //IL_041d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0427: Unknown result type (might be due to invalid IL or missing references)
        //IL_042c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0432: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0268: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_045b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0460: Unknown result type (might be due to invalid IL or missing references)
        //IL_0461: Unknown result type (might be due to invalid IL or missing references)
        //IL_0466: Unknown result type (might be due to invalid IL or missing references)
        //IL_0468: Unknown result type (might be due to invalid IL or missing references)
        //IL_033b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_0358: Unknown result type (might be due to invalid IL or missing references)
        //IL_035d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0368: Unknown result type (might be due to invalid IL or missing references)
        //IL_036d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0371: Unknown result type (might be due to invalid IL or missing references)
        //IL_0376: Unknown result type (might be due to invalid IL or missing references)
        //IL_0380: Unknown result type (might be due to invalid IL or missing references)
        //IL_0382: Unknown result type (might be due to invalid IL or missing references)
        //IL_047c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0488: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[owner];
        Vector2 vector = player.RotatedRelativePoint(player.MountedCenter);
        timeLeft = 60;
        bool flag = false;
        if (player.CCed || player.noItems)
        {
            flag = true;
        }
        else if (player.inventory[player.selectedItem].shoot != type)
        {
            flag = true;
        }
        else if (player.pulley)
        {
            flag = true;
        }
        else if (player.dead)
        {
            flag = true;
        }
        if (!flag)
        {
            Vector2 val = player.Center - base.Center;
            flag = ((Vector2)(ref val)).Length() > 2000f;
        }
        if (flag)
        {
            Kill();
            return;
        }
        float num = 4f;
        float num7 = 500f;
        float num8 = num7 / 2f;
        if (owner == Main.myPlayer && extraUpdates == 0)
        {
            float num14 = ai[0];
            if (ai[0] == 0f)
            {
                ai[0] = num8;
            }
            float num9 = ai[0];
            if (Main.mouseRight)
            {
                num9 -= 5f;
            }
            if (Main.mouseLeft)
            {
                num9 += 5f;
            }
            ai[0] = MathHelper.Clamp(num9, num, num7);
            if (num14 != num9)
            {
                netUpdate = true;
            }
        }
        if (numUpdates == 1)
        {
            extraUpdates = 0;
        }
        int num10 = 0;
        float cloudAlpha = Main.cloudAlpha;
        float num11 = 0f;
        if (WorldGen.InAPlaceWithWind(position, width, height))
        {
            num11 = Main.WindForVisuals;
        }
        float num12 = Utils.GetLerpValue(0.2f, 0.5f, Math.Abs(num11), clamped: true) * 0.5f;
        switch (num10)
        {
        case 0:
        {
            Vector2 mouseWorld = Main.MouseWorld;
            mouseWorld = base.Center;
            mouseWorld += new Vector2(num11, (float)Math.Sin(Main.GlobalTimeWrappedHourly) + cloudAlpha * 5f) * 25f;
            Vector2 v = mouseWorld - base.Center;
            v = v.SafeNormalize(Vector2.Zero) * (3f + cloudAlpha * 7f);
            if (num12 == 0f)
            {
                v = velocity;
            }
            float num13 = Distance(mouseWorld);
            float lerpValue = Utils.GetLerpValue(5f, 10f, num13, clamped: true);
            float y = velocity.Y;
            if (num13 > 10f)
            {
                velocity = Vector2.Lerp(velocity, v, 0.075f * lerpValue);
            }
            velocity.Y = y;
            velocity.Y -= num12;
            velocity.Y += 0.02f + num12 * 0.25f;
            velocity.Y = MathHelper.Clamp(velocity.Y, -2f, 2f);
            if (base.Center.Y + velocity.Y < mouseWorld.Y)
            {
                velocity.Y = MathHelper.Lerp(velocity.Y, velocity.Y + num12 + 0.01f, 0.75f);
            }
            velocity.X *= 0.98f;
            float num2 = Distance(vector);
            float num3 = ai[0];
            if (num2 > num3)
            {
                Vector2 vector3 = DirectionTo(vector);
                float num4 = num2 - num3;
                base.Center += vector3 * num4;
                bool num15 = Vector2.Dot(vector3, Vector2.UnitY) < 0.8f || num12 > 0f;
                velocity.Y += vector3.Y * 0.05f;
                if (num15)
                {
                    velocity.Y -= 0.15f;
                }
                velocity.X += vector3.X * 0.2f;
                if (num3 == num && owner == Main.myPlayer)
                {
                    Kill();
                    return;
                }
            }
            break;
        }
        case 1:
        {
            Vector2 vector2 = DirectionTo(vector);
            velocity = Vector2.Lerp(velocity, vector2 * 16f, 1f);
            if (Distance(vector) < 10f && owner == Main.myPlayer)
            {
                Kill();
                return;
            }
            break;
        }
        }
        timeLeft = 2;
        Vector2 vector4 = base.Center - vector;
        int dir = ((vector4.X > 0f) ? 1 : (-1));
        if (Math.Abs(vector4.X) > Math.Abs(vector4.Y) / 2f)
        {
            player.ChangeDir(dir);
        }
        Vector2 vector5 = DirectionTo(vector).SafeNormalize(Vector2.Zero);
        if (num12 == 0f && velocity.Y > -0.02f)
        {
            rotation *= 0.95f;
        }
        else
        {
            float num5 = (-vector5).ToRotation() + (float)Math.PI / 4f;
            if (spriteDirection == -1)
            {
                num5 -= (float)Math.PI / 2f * (float)player.direction;
            }
            rotation = num5 + velocity.X * 0.05f;
        }
        float num6 = ((Vector2)(ref velocity)).Length();
        switch (type)
        {
        case 771:
        case 822:
        case 823:
        case 827:
        case 830:
        case 838:
        case 843:
        case 844:
        case 845:
        case 846:
        case 850:
        case 852:
            frame = 0;
            break;
        case 828:
        case 829:
            if (num6 < 6f)
            {
                frame = 1;
            }
            else
            {
                frame = 0;
            }
            break;
        case 826:
            frame = (int)ai[1];
            break;
        case 824:
        case 839:
        case 840:
        case 853:
            if (num12 < 0.15f)
            {
                frame = 0;
                break;
            }
            frameCounter++;
            if ((float)frameCounter > (1f - num12) * 10f)
            {
                frameCounter = 0;
                frame = Main.rand.Next(4);
            }
            break;
        default:
            if (num6 < 3f)
            {
                frame = 0;
            }
            else if (num6 < 5f)
            {
                frame = 1;
            }
            else if (num6 < 7f)
            {
                frame = 2;
            }
            else
            {
                frame = 3;
            }
            break;
        }
        spriteDirection = player.direction;
    }
References Terraria.Player.CCed, Terraria.Player.ChangeDir(), Terraria.Main.cloudAlpha, Terraria.Player.dead, Terraria.Entity.direction, Terraria.Utils.GetLerpValue(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.WorldGen.InAPlaceWithWind(), Terraria.Player.inventory, Terraria.Player.MountedCenter, Terraria.Main.mouseLeft, Terraria.Main.mouseRight, Terraria.Main.MouseWorld, Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Player.noItems, Terraria.Main.player, Terraria.Player.pulley, Terraria.Main.rand, Terraria.Player.RotatedRelativePoint(), Terraria.Player.selectedItem, Terraria.Item.shoot, and Terraria.Main.WindForVisuals.