TModLoader: Terraria.Projectile.AI_130_FlameBurstTower
AI_130_FlameBurstTower()
void Terraria.Projectile.AI_130_FlameBurstTower () inline private
Definition at line 74829 of file Projectile.cs.
    {
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0352: Unknown result type (might be due to invalid IL or missing references)
        //IL_0366: Unknown result type (might be due to invalid IL or missing references)
        //IL_0370: Unknown result type (might be due to invalid IL or missing references)
        //IL_037b: Unknown result type (might be due to invalid IL or missing references)
        //IL_038a: Unknown result type (might be due to invalid IL or missing references)
        //IL_038f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_066f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0683: Unknown result type (might be due to invalid IL or missing references)
        //IL_068d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0698: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0704: Unknown result type (might be due to invalid IL or missing references)
        //IL_0709: Unknown result type (might be due to invalid IL or missing references)
        //IL_0253: Unknown result type (might be due to invalid IL or missing references)
        //IL_025f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0570: Unknown result type (might be due to invalid IL or missing references)
        //IL_057c: Unknown result type (might be due to invalid IL or missing references)
        //IL_088d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0899: Unknown result type (might be due to invalid IL or missing references)
        //IL_016f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_048c: Unknown result type (might be due to invalid IL or missing references)
        //IL_048e: Unknown result type (might be due to invalid IL or missing references)
        //IL_049d: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_052e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0533: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_084b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0850: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b20: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b25: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b26: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b41: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a62: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02de: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0334: Unknown result type (might be due to invalid IL or missing references)
        //IL_0339: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a82: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0610: Unknown result type (might be due to invalid IL or missing references)
        //IL_0616: Unknown result type (might be due to invalid IL or missing references)
        //IL_0647: Unknown result type (might be due to invalid IL or missing references)
        //IL_0651: Unknown result type (might be due to invalid IL or missing references)
        //IL_0656: Unknown result type (might be due to invalid IL or missing references)
        //IL_090a: Unknown result type (might be due to invalid IL or missing references)
        //IL_090c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0911: Unknown result type (might be due to invalid IL or missing references)
        //IL_0918: Unknown result type (might be due to invalid IL or missing references)
        //IL_092d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0933: Unknown result type (might be due to invalid IL or missing references)
        //IL_0964: Unknown result type (might be due to invalid IL or missing references)
        //IL_096e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0973: Unknown result type (might be due to invalid IL or missing references)
        float num = 900f;
        float angleRatioMax = 1f;
        Vector2 vector = base.Center;
        int num3 = 664;
        int num4 = 12;
        float num5 = 12f;
        int num6 = 1;
        int num7 = 6;
        int num8 = 4;
        int num9 = 80;
        switch (type)
        {
        case 663:
        {
            Lighting.AddLight(base.Center, new Vector3(0.4f, 0.2f, 0.1f));
            Lighting.AddLight(base.Bottom + new Vector2(0f, -10f), new Vector3(0.4f, 0.2f, 0.1f));
            vector = base.Bottom + new Vector2((float)(direction * 6), -40f);
            if ((localAI[0] += 1f) >= 300f)
            {
                localAI[0] = 0f;
            }
            Rectangle r3 = default(Rectangle);
            ((Rectangle)(ref r3))._002Ector((int)position.X + width / 4, (int)position.Y + height - 16, width / 4 * 3, 6);
            if (direction == 1)
            {
                r3.X -= width / 4;
            }
            for (int m = 0; m < 1; m++)
            {
                if (Main.rand.Next(2) == 0)
                {
                    Dust dust3 = Dust.NewDustDirect(r3.TopLeft() + new Vector2(-2f, -2f), r3.Width + 4, r3.Height + 4, 270, -direction * 2, -2f, 200, new Color(255, 255, 255, 0));
                    dust3.fadeIn = 0.6f + Main.rand.NextFloat() * 0.6f;
                    dust3.scale = 0.4f;
                    dust3.noGravity = true;
                    dust3.noLight = true;
                    dust3.velocity = Vector2.Zero;
                    dust3.velocity.X = (float)(-direction) * Main.rand.NextFloat() * dust3.fadeIn;
                }
            }
            ((Rectangle)(ref r3))._002Ector((int)base.Center.X, (int)base.Bottom.Y, width / 4, 10);
            if (direction == -1)
            {
                r3.X -= r3.Width;
            }
            r3.X += direction * 4;
            r3.Y -= height - 10;
            for (int n = 0; n < 1; n++)
            {
                if (Main.rand.Next(5) == 0)
                {
                    Dust dust6 = Dust.NewDustDirect(r3.TopLeft(), r3.Width, r3.Height, 6);
                    dust6.fadeIn = 1f;
                    dust6.scale = 1f;
                    dust6.noGravity = true;
                    dust6.noLight = true;
                    dust6.velocity *= 2f;
                }
            }
            break;
        }
        case 665:
        {
            Lighting.AddLight(base.Center, new Vector3(0.4f, 0.2f, 0.1f) * 1.2f);
            Lighting.AddLight(base.Bottom + new Vector2(0f, -10f), new Vector3(0.4f, 0.2f, 0.1f) * 1.2f);
            num9 = 70;
            num5 += 3f;
            num7 = 8;
            num3 = 666;
            vector = base.Bottom + new Vector2((float)(direction * 6), -44f);
            if ((localAI[0] += 1f) >= 300f)
            {
                localAI[0] = 0f;
            }
            Rectangle r2 = default(Rectangle);
            ((Rectangle)(ref r2))._002Ector((int)position.X + width / 4, (int)position.Y + height - 16, width / 4 * 2, 6);
            if (direction == 1)
            {
                r2.X -= width / 4;
            }
            for (int k = 0; k < 1; k++)
            {
                if (Main.rand.Next(2) == 0)
                {
                    Dust dust2 = Dust.NewDustDirect(r2.TopLeft() + new Vector2(-2f, -2f), r2.Width + 4, r2.Height + 4, 270, -direction * 2, -2f, 200, new Color(255, 255, 255, 0));
                    dust2.fadeIn = 0.6f + Main.rand.NextFloat() * 0.6f;
                    dust2.scale = 0.4f;
                    dust2.noGravity = true;
                    dust2.noLight = true;
                    dust2.velocity = Vector2.Zero;
                    dust2.velocity.X = (float)(-direction) * Main.rand.NextFloat() * dust2.fadeIn;
                }
            }
            ((Rectangle)(ref r2))._002Ector((int)base.Center.X, (int)base.Bottom.Y, width / 4, 10);
            if (direction == -1)
            {
                r2.X -= r2.Width;
            }
            r2.X += direction * 4;
            r2.Y -= height - 10;
            for (int l = 0; l < 2; l++)
            {
                if (Main.rand.Next(5) == 0)
                {
                    Dust dust5 = Dust.NewDustDirect(r2.TopLeft(), r2.Width, r2.Height, 6);
                    dust5.fadeIn = 1f;
                    dust5.scale = 1f;
                    dust5.noGravity = true;
                    dust5.noLight = true;
                    dust5.velocity *= 2f;
                }
            }
            break;
        }
        case 667:
        {
            Lighting.AddLight(base.Center, new Vector3(0.4f, 0.2f, 0.1f) * 1.5f);
            Lighting.AddLight(base.Bottom + new Vector2(0f, -10f), new Vector3(0.4f, 0.2f, 0.1f) * 1.5f);
            num9 = 60;
            num5 += 6f;
            num7 = 8;
            num3 = 668;
            vector = base.Bottom + new Vector2((float)(direction * 6), -46f);
            if ((localAI[0] += 1f) >= 300f)
            {
                localAI[0] = 0f;
            }
            Rectangle r = default(Rectangle);
            ((Rectangle)(ref r))._002Ector((int)position.X + width / 4, (int)position.Y + height - 16, width / 4 * 2, 6);
            if (direction == 1)
            {
                r.X -= width / 4;
            }
            for (int i = 0; i < 1; i++)
            {
                if (Main.rand.Next(2) == 0)
                {
                    Dust dust = Dust.NewDustDirect(r.TopLeft() + new Vector2(-2f, -2f), r.Width + 4, r.Height + 4, 270, -direction * 2, -2f, 200, new Color(255, 255, 255, 0));
                    dust.fadeIn = 0.6f + Main.rand.NextFloat() * 0.6f;
                    dust.scale = 0.4f;
                    dust.noGravity = true;
                    dust.noLight = true;
                    dust.velocity = Vector2.Zero;
                    dust.velocity.X = (float)(-direction) * Main.rand.NextFloat() * dust.fadeIn;
                }
            }
            ((Rectangle)(ref r))._002Ector((int)base.Center.X, (int)base.Bottom.Y, width / 4, 10);
            if (direction == -1)
            {
                r.X -= r.Width;
            }
            r.X += direction * 4;
            r.Y -= height - 10;
            for (int j = 0; j < 3; j++)
            {
                if (Main.rand.Next(5) == 0)
                {
                    Dust dust4 = Dust.NewDustDirect(r.TopLeft(), r.Width, r.Height, 6);
                    dust4.fadeIn = 1.1f;
                    dust4.scale = 1f;
                    dust4.noGravity = true;
                    dust4.noLight = true;
                    dust4.velocity *= 2.4f;
                }
            }
            break;
        }
        }
        if (Main.player[owner].setApprenticeT2)
        {
            angleRatioMax = 0.1f;
            num *= 1.5f;
            num5 *= 1.4f;
        }
        if (ai[0] == 0f)
        {
            direction = (spriteDirection = Main.player[owner].direction);
            ai[0] = 1f;
            ai[1] = 0f;
            netUpdate = true;
        }
        if (ai[0] == 1f)
        {
            frame = 0;
            bool flag = false;
            if (ai[1] > 0f)
            {
                ai[1] -= 1f;
            }
            else
            {
                flag = true;
            }
            if (flag && owner == Main.myPlayer)
            {
                int num10 = AI_130_FlameBurstTower_FindTarget(num, angleRatioMax, vector);
                if (num10 != -1)
                {
                    direction = Math.Sign(DirectionTo(Main.npc[num10].Center).X);
                    ai[0] = 2f;
                    ai[1] = 0f;
                    netUpdate = true;
                }
            }
        }
        else if (ai[0] == 2f)
        {
            frame = num6 + (int)(ai[1] / (float)num8);
            if (ai[1] == (float)num4)
            {
                Vector2 vector2 = default(Vector2);
                ((Vector2)(ref vector2))._002Ector((float)direction, 0f);
                int num2 = AI_130_FlameBurstTower_FindTarget(num, angleRatioMax, vector, canChangeDirection: false);
                if (num2 != -1)
                {
                    vector2 = (Main.npc[num2].Center - vector).SafeNormalize(Vector2.UnitX * (float)direction);
                }
                Vector2 vector3 = vector2 * num5;
                if (owner == Main.myPlayer)
                {
                    NewProjectile(GetProjectileSource_FromThis(), vector, vector3, num3, damage, knockBack, owner);
                }
            }
            if ((ai[1] += 1f) >= (float)(num7 * num8))
            {
                ai[0] = 1f;
                ai[1] = num9;
            }
        }
        spriteDirection = direction;
        tileCollide = true;
        velocity.Y += 0.2f;
    }
References Terraria.Lighting.AddLight(), Terraria.Entity.Center, Terraria.Entity.direction, Terraria.Dust.fadeIn, Terraria.Main.myPlayer, Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Main.player, Terraria.Main.rand, and Terraria.Player.setApprenticeT2.