TModLoader: Terraria.Projectile.AI_019_Spears_GetExtensionHitbox
AI_019_Spears_GetExtensionHitbox()
bool Terraria.Projectile.AI_019_Spears_GetExtensionHitbox (out Rectangle extensionBox) inline
Definition at line 48890 of file Projectile.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_0107: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        extensionBox = default(Rectangle);
        Player player = Main.player[owner];
        if (player.itemAnimation < player.itemAnimationMax / 3)
        {
            return false;
        }
        int itemAnimationMax = player.itemAnimationMax;
        int itemAnimation = player.itemAnimation;
        int num = player.itemAnimationMax / 3;
        float num2 = Utils.Remap(itemAnimation, itemAnimationMax, num, 0f, 1f);
        float num3 = 10f;
        float num4 = 30f;
        float num5 = 10f;
        float num6 = 10f;
        switch (type)
        {
        default:
            return false;
        case 105:
            num4 = 50f;
            num6 = 20f;
            break;
        case 46:
            num4 = 50f;
            num6 = 15f;
            break;
        case 153:
            num4 = 40f;
            num6 = 10f;
            break;
        }
        num4 *= 1f / player.inverseMeleeSpeed;
        float num7 = num3 + num4 * num2;
        float num8 = num5 + num6 * num2;
        float f = velocity.ToRotation();
        Vector2 center = base.Center + f.ToRotationVector2() * num7;
        extensionBox = Utils.CenteredRectangle(center, new Vector2(num8, num8));
        return true;
    }
References Terraria.Utils.CenteredRectangle(), Terraria.Player.inverseMeleeSpeed, Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, Terraria.Main.player, and Terraria.Utils.Remap().
Referenced by Terraria.Projectile.Colliding(), and Terraria.Projectile.CutTiles().