TModLoader: Terraria.Projectile.AI_180_FairyQueenSunDance
AI_180_FairyQueenSunDance()
void Terraria.Projectile.AI_180_FairyQueenSunDance () inline private
Definition at line 47189 of file Projectile.cs.
    {
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0130: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0140: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        if (localAI[0] == 0f)
        {
            SoundEngine.PlaySound(in SoundID.Item159, base.Center);
        }
        localAI[0] += 1f;
        float num = 180f;
        _ = ai[0] / ((float)Math.PI * 2f);
        float num2 = (float)Math.PI / 9f;
        if (localAI[0] >= num)
        {
            Kill();
            return;
        }
        alpha -= 15;
        if (alpha < 0)
        {
            alpha = 0;
        }
        scale = Utils.GetLerpValue(0f, 20f, localAI[0], clamped: true) * Utils.GetLerpValue(num, num - 60f, localAI[0], clamped: true);
        float lerpValue = Utils.GetLerpValue(50f, num, localAI[0], clamped: true);
        rotation = ai[0] + lerpValue * num2;
        int num3 = (int)ai[1];
        if (Main.npc.IndexInRange(num3))
        {
            NPC nPC = Main.npc[num3];
            if (nPC.active && nPC.type == 636)
            {
                base.Center = nPC.Center;
            }
            velocity = Vector2.Zero;
            Vector2 vector = rotation.ToRotationVector2();
            Color val = Main.hslToRgb((ai[0] / ((float)Math.PI * 2f) + localAI[0] / num) % 1f, 1f, 0.85f);
            Vector3 v3_ = ((Color)(ref val)).ToVector3() * scale;
            float num4 = 800f * scale;
            DelegateMethods.v3_1 = v3_;
            for (float num5 = 0f; num5 <= 1f; num5 += 1f / 12f)
            {
                Point point = (base.Center + vector * num4 * num5).ToTileCoordinates();
                DelegateMethods.CastLightOpen(point.X, point.Y);
            }
        }
        else
        {
            Kill();
        }
    }
References Terraria.DelegateMethods.CastLightOpen(), Terraria.Utils.GetLerpValue(), Terraria.Main.hslToRgb(), Terraria.ID.SoundID.Item159, Terraria.Main.npc, and Terraria.Audio.SoundEngine.PlaySound().