TModLoader: Terraria.Projectile.AI_140_MonkStaffT1
AI_140_MonkStaffT1()
void Terraria.Projectile.AI_140_MonkStaffT1 () inline private
Definition at line 76266 of file Projectile.cs.
    {
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_0991: Unknown result type (might be due to invalid IL or missing references)
        //IL_0994: Unknown result type (might be due to invalid IL or missing references)
        //IL_099e: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09af: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_09bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_053e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0572: Unknown result type (might be due to invalid IL or missing references)
        //IL_0577: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_059b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0676: Unknown result type (might be due to invalid IL or missing references)
        //IL_067b: Unknown result type (might be due to invalid IL or missing references)
        //IL_067e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0680: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0225: Unknown result type (might be due to invalid IL or missing references)
        //IL_022a: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_070f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0714: Unknown result type (might be due to invalid IL or missing references)
        //IL_0717: Unknown result type (might be due to invalid IL or missing references)
        //IL_0719: Unknown result type (might be due to invalid IL or missing references)
        //IL_0723: Unknown result type (might be due to invalid IL or missing references)
        //IL_0246: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        //IL_0255: Unknown result type (might be due to invalid IL or missing references)
        //IL_025a: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_074f: Unknown result type (might be due to invalid IL or missing references)
        //IL_075e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0764: Unknown result type (might be due to invalid IL or missing references)
        //IL_0769: Unknown result type (might be due to invalid IL or missing references)
        //IL_076c: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0269: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02db: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0320: Unknown result type (might be due to invalid IL or missing references)
        //IL_0326: Unknown result type (might be due to invalid IL or missing references)
        //IL_0339: Unknown result type (might be due to invalid IL or missing references)
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0348: Unknown result type (might be due to invalid IL or missing references)
        //IL_034f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_035e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0363: Unknown result type (might be due to invalid IL or missing references)
        //IL_0380: Unknown result type (might be due to invalid IL or missing references)
        //IL_0385: Unknown result type (might be due to invalid IL or missing references)
        //IL_0785: Unknown result type (might be due to invalid IL or missing references)
        //IL_078f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0794: Unknown result type (might be due to invalid IL or missing references)
        //IL_0799: Unknown result type (might be due to invalid IL or missing references)
        //IL_079d: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07be: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07de: Unknown result type (might be due to invalid IL or missing references)
        //IL_0806: Unknown result type (might be due to invalid IL or missing references)
        //IL_080c: Unknown result type (might be due to invalid IL or missing references)
        //IL_081f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0824: Unknown result type (might be due to invalid IL or missing references)
        //IL_082e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0835: Unknown result type (might be due to invalid IL or missing references)
        //IL_083f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0844: Unknown result type (might be due to invalid IL or missing references)
        //IL_0849: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0505: Unknown result type (might be due to invalid IL or missing references)
        //IL_0485: Unknown result type (might be due to invalid IL or missing references)
        //IL_0487: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0409: Unknown result type (might be due to invalid IL or missing references)
        //IL_040e: Unknown result type (might be due to invalid IL or missing references)
        //IL_043a: Unknown result type (might be due to invalid IL or missing references)
        //IL_043f: Unknown result type (might be due to invalid IL or missing references)
        //IL_051d: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0901: Unknown result type (might be due to invalid IL or missing references)
        //IL_0908: Unknown result type (might be due to invalid IL or missing references)
        //IL_090d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0912: Unknown result type (might be due to invalid IL or missing references)
        //IL_0919: Unknown result type (might be due to invalid IL or missing references)
        //IL_0931: Unknown result type (might be due to invalid IL or missing references)
        //IL_0938: Unknown result type (might be due to invalid IL or missing references)
        //IL_093f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0944: Unknown result type (might be due to invalid IL or missing references)
        float num = 50f;
        float num9 = 2f;
        float num10 = 20f;
        Player player = Main.player[owner];
        float num11 = -(float)Math.PI / 4f;
        Vector2 vector = player.RotatedRelativePoint(player.MountedCenter);
        Vector2 vector2 = Vector2.Zero;
        if (player.dead)
        {
            Kill();
            return;
        }
        if (type == 697)
        {
            int num12 = damage * 3;
            int num13 = Math.Sign(velocity.X);
            velocity = new Vector2((float)num13, 0f);
            if (ai[0] == 0f)
            {
                rotation = Utils.ToRotation(new Vector2((float)num13, 0f - player.gravDir)) + num11 + (float)Math.PI;
                if (velocity.X < 0f)
                {
                    rotation -= (float)Math.PI / 2f;
                }
            }
            alpha -= 128;
            if (alpha < 0)
            {
                alpha = 0;
            }
            float num16 = ai[0] / num;
            float num14 = 1f;
            ai[0] += num14;
            rotation += (float)Math.PI * 2f * num9 / num * (float)num13;
            bool flag = ai[0] == (float)(int)(num / 2f);
            if (ai[0] >= num || (flag && !player.controlUseItem))
            {
                Kill();
                player.reuseDelay = 10;
            }
            else if (flag)
            {
                Vector2 mouseWorld = Main.MouseWorld;
                int num15 = ((player.DirectionTo(mouseWorld).X > 0f) ? 1 : (-1));
                if ((float)num15 != velocity.X)
                {
                    player.ChangeDir(num15);
                    velocity = new Vector2((float)num15, 0f);
                    netUpdate = true;
                    rotation -= (float)Math.PI;
                }
            }
            float num2 = rotation - (float)Math.PI / 4f * (float)num13;
            vector2 = (num2 + ((num13 == -1) ? ((float)Math.PI) : 0f)).ToRotationVector2() * (ai[0] / num) * num10;
            Vector2 vector3 = base.Center + (num2 + ((num13 == -1) ? ((float)Math.PI) : 0f)).ToRotationVector2() * 30f;
            if (Main.rand.Next(2) == 0)
            {
                Dust dust = Dust.NewDustDirect(vector3 - new Vector2(5f), 10, 10, 31, player.velocity.X, player.velocity.Y, 150);
                dust.velocity = DirectionTo(dust.position) * 0.1f + dust.velocity * 0.1f;
            }
            if (num16 >= 0.75f)
            {
                Dust dust2 = Dust.NewDustDirect(vector3 - new Vector2(5f), 10, 10, 55, player.velocity.X, player.velocity.Y, 50);
                dust2.velocity = DirectionTo(dust2.position) * 0.1f + dust2.velocity * 0.1f;
                dust2.noGravity = true;
                dust2.color = new Color(20, 255, 100, 160);
            }
            if (ai[0] >= num - 8f && ai[0] < num - 2f)
            {
                for (int i = 0; i < 5; i++)
                {
                    Dust dust5 = Dust.NewDustDirect(vector3 - new Vector2(5f), 10, 10, 55, player.velocity.X, player.velocity.Y, 50);
                    dust5.velocity *= 1.2f;
                    dust5.noGravity = true;
                    dust5.scale += 0.1f;
                    dust5.color = new Color(20, 255, 100, 160);
                }
            }
            if (ai[0] == num - 3f && owner == Main.myPlayer)
            {
                if (localAI[1] == 1f || WorldUtils.Find(vector3.ToTileCoordinates(), Searches.Chain(new Searches.Down(4), _cachedConditions_notNull, _cachedConditions_solid), out var _))
                {
                    NewProjectile(GetProjectileSource_FromThis(), vector3 + new Vector2((float)(num13 * 20), -60f), Vector2.Zero, 698, num12, 0f, owner);
                    SoundEngine.PlayTrackedSound(in SoundID.DD2_MonkStaffGroundImpact, base.Center);
                }
                else
                {
                    SoundEngine.PlayTrackedSound(in SoundID.DD2_MonkStaffGroundMiss, base.Center);
                }
            }
        }
        if (type == 707)
        {
            Lighting.AddLight(player.Center, 0.75f, 0.9f, 1.15f);
            int num3 = Math.Sign(velocity.X);
            velocity = new Vector2((float)num3, 0f);
            if (ai[0] == 0f)
            {
                rotation = Utils.ToRotation(new Vector2((float)num3, 0f - player.gravDir)) + num11 + (float)Math.PI;
                if (velocity.X < 0f)
                {
                    rotation -= (float)Math.PI / 2f;
                }
            }
            alpha -= 128;
            if (alpha < 0)
            {
                alpha = 0;
            }
            _ = ai[0] / num;
            float num4 = 1f;
            ai[0] += num4;
            rotation += (float)Math.PI * 2f * num9 / num * (float)num3;
            bool flag2 = ai[0] == (float)(int)(num / 2f);
            if (ai[0] >= num || (flag2 && !player.controlUseItem))
            {
                Kill();
                player.reuseDelay = 2;
            }
            else if (flag2)
            {
                Vector2 mouseWorld2 = Main.MouseWorld;
                int num5 = ((player.DirectionTo(mouseWorld2).X > 0f) ? 1 : (-1));
                if ((float)num5 != velocity.X)
                {
                    player.ChangeDir(num5);
                    velocity = new Vector2((float)num5, 0f);
                    netUpdate = true;
                    rotation -= (float)Math.PI;
                }
            }
            if ((ai[0] == num4 || (ai[0] == (float)(int)(num / 2f) && active)) && owner == Main.myPlayer)
            {
                Vector2 mouseWorld3 = Main.MouseWorld;
                _ = player.DirectionTo(mouseWorld3) * 0f;
            }
            float num6 = rotation - (float)Math.PI / 4f * (float)num3;
            vector2 = (num6 + ((num3 == -1) ? ((float)Math.PI) : 0f)).ToRotationVector2() * (ai[0] / num) * num10;
            Vector2 vector4 = base.Center + (num6 + ((num3 == -1) ? ((float)Math.PI) : 0f)).ToRotationVector2() * 30f;
            Vector2 vector5 = num6.ToRotationVector2();
            Vector2 vector6 = vector5.RotatedBy((float)Math.PI / 2f * (float)spriteDirection);
            if (Main.rand.Next(2) == 0)
            {
                Dust dust3 = Dust.NewDustDirect(vector4 - new Vector2(5f), 10, 10, 31, player.velocity.X, player.velocity.Y, 150);
                dust3.velocity = DirectionTo(dust3.position) * 0.1f + dust3.velocity * 0.1f;
            }
            for (int j = 0; j < 4; j++)
            {
                float num7 = 1f;
                float num8 = 1f;
                switch (j)
                {
                case 1:
                    num8 = -1f;
                    break;
                case 2:
                    num8 = 1.25f;
                    num7 = 0.5f;
                    break;
                case 3:
                    num8 = -1.25f;
                    num7 = 0.5f;
                    break;
                }
                if (Main.rand.Next(6) != 0)
                {
                    Dust dust4 = Dust.NewDustDirect(position, 0, 0, 226, 0f, 0f, 100);
                    dust4.position = base.Center + vector5 * (60f + Main.rand.NextFloat() * 20f) * num8;
                    dust4.velocity = vector6 * (4f + 4f * Main.rand.NextFloat()) * num8 * num7;
                    dust4.noGravity = true;
                    dust4.noLight = true;
                    dust4.scale = 0.5f;
                    dust4.customData = this;
                    if (Main.rand.Next(4) == 0)
                    {
                        dust4.noGravity = false;
                    }
                }
            }
        }
        position = vector - base.Size / 2f;
        position += vector2;
        spriteDirection = direction;
        timeLeft = 2;
        player.ChangeDir(direction);
        player.heldProj = whoAmI;
        player.SetDummyItemTime(2);
        player.itemRotation = MathHelper.WrapAngle(rotation);
    }
References Terraria.Lighting.AddLight(), Terraria.Entity.Center, Terraria.WorldBuilding.Searches.Chain(), Terraria.Player.ChangeDir(), Terraria.Player.controlUseItem, Terraria.ID.SoundID.DD2_MonkStaffGroundImpact, Terraria.ID.SoundID.DD2_MonkStaffGroundMiss, Terraria.Player.dead, Terraria.Entity.DirectionTo(), Terraria.WorldBuilding.WorldUtils.Find(), Terraria.Player.gravDir, Terraria.Player.MountedCenter, Terraria.Main.MouseWorld, Terraria.Main.myPlayer, Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Dust.position, Terraria.Main.rand, Terraria.Player.RotatedRelativePoint(), Terraria.Player.SetDummyItemTime(), Terraria.Utils.ToRotation(), and Terraria.Entity.velocity.