TModLoader: Terraria.Projectile.AI_111_DryadsWard
AI_111_DryadsWard()
void Terraria.Projectile.AI_111_DryadsWard () inline private
Definition at line 42117 of file Projectile.cs.
    {
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_0276: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0283: Unknown result type (might be due to invalid IL or missing references)
        //IL_0288: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_037f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0415: Unknown result type (might be due to invalid IL or missing references)
        //IL_041f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0424: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0462: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0593: Unknown result type (might be due to invalid IL or missing references)
        //IL_059c: Unknown result type (might be due to invalid IL or missing references)
        if (!Main.npc[(int)ai[1]].active || Main.npc[(int)ai[1]].type != 20 || Main.npc[(int)ai[1]].ai[0] != 14f)
        {
            Kill();
            return;
        }
        ai[0] += 1f;
        rotation += (float)Math.PI / 300f;
        scale = ai[0] / 100f;
        if (scale > 1f)
        {
            scale = 1f;
        }
        alpha = (int)(255f * (1f - scale));
        float num = 300f;
        if (ai[0] >= 100f)
        {
            num = MathHelper.Lerp(300f, 600f, (ai[0] - 100f) / 200f);
        }
        if (num > 600f)
        {
            num = 600f;
        }
        if (ai[0] >= 500f)
        {
            alpha = (int)MathHelper.Lerp(0f, 255f, (ai[0] - 500f) / 100f);
            num = MathHelper.Lerp(600f, 1200f, (ai[0] - 500f) / 100f);
            rotation += (float)Math.PI / 300f;
        }
        int num2 = 163;
        if (ai[2] == 1f)
        {
            float num3 = (float)Math.Sin(ai[0] % 120f * ((float)Math.PI * 2f) / 120f) * 0.5f + 0.5f;
            if (Main.rand.NextFloat() < num3)
            {
                num2 = 70;
            }
        }
        if (Main.rand.Next(4) == 0)
        {
            float num4 = num;
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector((float)Main.rand.Next(-10, 11), (float)Main.rand.Next(-10, 11));
            float num5 = Main.rand.Next(3, 9);
            ((Vector2)(ref vector)).Normalize();
            int num6 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, num2, 0f, 0f, 100);
            Main.dust[num6].noGravity = true;
            Main.dust[num6].position = base.Center + vector * num4;
            if (Main.rand.Next(8) == 0)
            {
                Main.dust[num6].velocity = vector * (0f - num5) * 3f;
                Main.dust[num6].scale += 0.5f;
            }
            else
            {
                Main.dust[num6].velocity = vector * (0f - num5);
            }
        }
        if (Main.rand.Next(2) == 0)
        {
            Vector2 vector2 = default(Vector2);
            ((Vector2)(ref vector2))._002Ector((float)Main.rand.Next(-10, 11), (float)Main.rand.Next(-10, 11));
            float num7 = Main.rand.Next(3, 9);
            ((Vector2)(ref vector2)).Normalize();
            int num8 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, num2, 0f, 0f, 100, default(Color), 1.5f);
            Main.dust[num8].noGravity = true;
            Main.dust[num8].position = base.Center + vector2 * 30f;
            if (Main.rand.Next(8) == 0)
            {
                Main.dust[num8].velocity = vector2 * (0f - num7) * 3f;
                Main.dust[num8].scale += 0.5f;
            }
            else
            {
                Main.dust[num8].velocity = vector2 * (0f - num7);
            }
        }
        if (ai[0] >= 30f && Main.netMode != 2)
        {
            Player player = Main.player[Main.myPlayer];
            if (player.active && !player.dead && Distance(player.Center) <= num && player.FindBuffIndex(165) == -1)
            {
                player.AddBuff(165, 120);
            }
        }
        if (ai[0] >= 30f && ai[0] % 10f == 0f && Main.netMode != 1)
        {
            for (int i = 0; i < 200; i++)
            {
                NPC nPC = Main.npc[i];
                if (nPC.type != 488 && nPC.active && Distance(nPC.Center) <= num)
                {
                    if (nPC.townNPC && (nPC.FindBuffIndex(165) == -1 || nPC.buffTime[nPC.FindBuffIndex(165)] <= 20))
                    {
                        nPC.AddBuff(165, 120);
                    }
                    else if (!nPC.friendly && nPC.lifeMax > 5 && !nPC.dontTakeDamage && (nPC.FindBuffIndex(186) == -1 || nPC.buffTime[nPC.FindBuffIndex(186)] <= 20) && (nPC.dryadBane || Collision.CanHit(base.Center, 1, 1, nPC.position, nPC.width, nPC.height)))
                    {
                        nPC.AddBuff(186, 120);
                    }
                }
            }
        }
        if (ai[0] >= 570f)
        {
            Kill();
        }
    }
References Terraria.Entity.active, Terraria.Player.AddBuff(), Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Player.dead, Terraria.Main.dust, Terraria.Player.FindBuffIndex(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Main.npc, Terraria.Main.player, and Terraria.Main.rand.