TModLoader: Terraria.Projectile.AI_016
AI_016()
void Terraria.Projectile.AI_016 () inline private
    {
        //IL_05e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0672: Unknown result type (might be due to invalid IL or missing references)
        //IL_0677: Unknown result type (might be due to invalid IL or missing references)
        //IL_067c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0689: Unknown result type (might be due to invalid IL or missing references)
        //IL_068e: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0606: Unknown result type (might be due to invalid IL or missing references)
        //IL_0612: Unknown result type (might be due to invalid IL or missing references)
        //IL_0618: Unknown result type (might be due to invalid IL or missing references)
        //IL_061d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0622: Unknown result type (might be due to invalid IL or missing references)
        //IL_0626: Unknown result type (might be due to invalid IL or missing references)
        //IL_062b: Unknown result type (might be due to invalid IL or missing references)
        //IL_062d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0632: Unknown result type (might be due to invalid IL or missing references)
        //IL_063c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0641: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0701: Unknown result type (might be due to invalid IL or missing references)
        //IL_0708: Unknown result type (might be due to invalid IL or missing references)
        //IL_070d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0714: Unknown result type (might be due to invalid IL or missing references)
        //IL_071b: Unknown result type (might be due to invalid IL or missing references)
        //IL_072f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0734: Unknown result type (might be due to invalid IL or missing references)
        //IL_0741: Unknown result type (might be due to invalid IL or missing references)
        //IL_0747: Unknown result type (might be due to invalid IL or missing references)
        //IL_07aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_07af: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07be: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_076d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0777: Unknown result type (might be due to invalid IL or missing references)
        //IL_077c: Unknown result type (might be due to invalid IL or missing references)
        //IL_080d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0812: Unknown result type (might be due to invalid IL or missing references)
        //IL_0819: Unknown result type (might be due to invalid IL or missing references)
        //IL_081e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0825: Unknown result type (might be due to invalid IL or missing references)
        //IL_082c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0840: Unknown result type (might be due to invalid IL or missing references)
        //IL_0845: Unknown result type (might be due to invalid IL or missing references)
        //IL_0852: Unknown result type (might be due to invalid IL or missing references)
        //IL_0858: Unknown result type (might be due to invalid IL or missing references)
        //IL_087e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0888: Unknown result type (might be due to invalid IL or missing references)
        //IL_088d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_028a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0297: Unknown result type (might be due to invalid IL or missing references)
        //IL_029c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0901: Unknown result type (might be due to invalid IL or missing references)
        //IL_0906: Unknown result type (might be due to invalid IL or missing references)
        //IL_090b: Unknown result type (might be due to invalid IL or missing references)
        //IL_090d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0914: Unknown result type (might be due to invalid IL or missing references)
        //IL_091a: Unknown result type (might be due to invalid IL or missing references)
        //IL_091c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0921: Unknown result type (might be due to invalid IL or missing references)
        //IL_0924: Unknown result type (might be due to invalid IL or missing references)
        //IL_0929: Unknown result type (might be due to invalid IL or missing references)
        //IL_092b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0930: Unknown result type (might be due to invalid IL or missing references)
        //IL_0937: Unknown result type (might be due to invalid IL or missing references)
        //IL_093c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0943: Unknown result type (might be due to invalid IL or missing references)
        //IL_094a: Unknown result type (might be due to invalid IL or missing references)
        //IL_094f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0951: Unknown result type (might be due to invalid IL or missing references)
        //IL_095e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0964: Unknown result type (might be due to invalid IL or missing references)
        //IL_0478: Unknown result type (might be due to invalid IL or missing references)
        //IL_111a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1120: Unknown result type (might be due to invalid IL or missing references)
        //IL_112a: Unknown result type (might be due to invalid IL or missing references)
        //IL_112f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1153: Unknown result type (might be due to invalid IL or missing references)
        //IL_1159: Unknown result type (might be due to invalid IL or missing references)
        //IL_119d: Unknown result type (might be due to invalid IL or missing references)
        //IL_11a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0495: Unknown result type (might be due to invalid IL or missing references)
        //IL_1409: Unknown result type (might be due to invalid IL or missing references)
        //IL_140f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1419: Unknown result type (might be due to invalid IL or missing references)
        //IL_141e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1443: Unknown result type (might be due to invalid IL or missing references)
        //IL_1449: Unknown result type (might be due to invalid IL or missing references)
        //IL_1485: Unknown result type (might be due to invalid IL or missing references)
        //IL_148f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1494: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_11fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1205: Unknown result type (might be due to invalid IL or missing references)
        //IL_120a: Unknown result type (might be due to invalid IL or missing references)
        //IL_120f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1692: Unknown result type (might be due to invalid IL or missing references)
        //IL_1698: Unknown result type (might be due to invalid IL or missing references)
        //IL_169d: Unknown result type (might be due to invalid IL or missing references)
        //IL_16a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_16a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_16ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_16b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_16b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_16bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_16c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_16c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_16cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_124c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1252: Unknown result type (might be due to invalid IL or missing references)
        //IL_125c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1261: Unknown result type (might be due to invalid IL or missing references)
        //IL_1266: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_12a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_12a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_12b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_12b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_12bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_15bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_12f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1307: Unknown result type (might be due to invalid IL or missing references)
        //IL_131a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1344: Unknown result type (might be due to invalid IL or missing references)
        //IL_1349: Unknown result type (might be due to invalid IL or missing references)
        //IL_1366: Unknown result type (might be due to invalid IL or missing references)
        //IL_1374: Unknown result type (might be due to invalid IL or missing references)
        //IL_1387: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_13bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_13c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0522: Unknown result type (might be due to invalid IL or missing references)
        //IL_052e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0533: Unknown result type (might be due to invalid IL or missing references)
        //IL_0538: Unknown result type (might be due to invalid IL or missing references)
        //IL_053b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0540: Unknown result type (might be due to invalid IL or missing references)
        //IL_2620: Unknown result type (might be due to invalid IL or missing references)
        //IL_2625: Unknown result type (might be due to invalid IL or missing references)
        //IL_054d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0553: Unknown result type (might be due to invalid IL or missing references)
        //IL_0558: Unknown result type (might be due to invalid IL or missing references)
        //IL_055d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0567: Unknown result type (might be due to invalid IL or missing references)
        //IL_056c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1826: Unknown result type (might be due to invalid IL or missing references)
        //IL_182c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1836: Unknown result type (might be due to invalid IL or missing references)
        //IL_183b: Unknown result type (might be due to invalid IL or missing references)
        //IL_185f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1865: Unknown result type (might be due to invalid IL or missing references)
        //IL_18a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_18b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_18b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bcd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bd7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bdc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1901: Unknown result type (might be due to invalid IL or missing references)
        //IL_1907: Unknown result type (might be due to invalid IL or missing references)
        //IL_1911: Unknown result type (might be due to invalid IL or missing references)
        //IL_1916: Unknown result type (might be due to invalid IL or missing references)
        //IL_191b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1958: Unknown result type (might be due to invalid IL or missing references)
        //IL_195e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1968: Unknown result type (might be due to invalid IL or missing references)
        //IL_196d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1972: Unknown result type (might be due to invalid IL or missing references)
        //IL_19af: Unknown result type (might be due to invalid IL or missing references)
        //IL_19b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_19bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_19c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_19c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a05: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a13: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a26: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1af9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1aff: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b09: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b33: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b39: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b75: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b84: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ab5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1abf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ca1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d16: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_271e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2728: Unknown result type (might be due to invalid IL or missing references)
        //IL_272d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e91: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ea0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ec5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ecb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f18: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fc6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fcc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fe1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1feb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ff0: Unknown result type (might be due to invalid IL or missing references)
        //IL_200d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2052: Unknown result type (might be due to invalid IL or missing references)
        //IL_2058: Unknown result type (might be due to invalid IL or missing references)
        //IL_206d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2077: Unknown result type (might be due to invalid IL or missing references)
        //IL_207c: Unknown result type (might be due to invalid IL or missing references)
        //IL_236e: Unknown result type (might be due to invalid IL or missing references)
        //IL_238e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2394: Unknown result type (might be due to invalid IL or missing references)
        //IL_23c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_23ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_23f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_23fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_2400: Unknown result type (might be due to invalid IL or missing references)
        //IL_240a: Unknown result type (might be due to invalid IL or missing references)
        //IL_240f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2414: Unknown result type (might be due to invalid IL or missing references)
        //IL_2176: Unknown result type (might be due to invalid IL or missing references)
        //IL_2197: Unknown result type (might be due to invalid IL or missing references)
        //IL_219d: Unknown result type (might be due to invalid IL or missing references)
        //IL_220c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2220: Unknown result type (might be due to invalid IL or missing references)
        //IL_222e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2234: Unknown result type (might be due to invalid IL or missing references)
        //IL_2236: Unknown result type (might be due to invalid IL or missing references)
        //IL_2240: Unknown result type (might be due to invalid IL or missing references)
        //IL_2245: Unknown result type (might be due to invalid IL or missing references)
        //IL_224a: Unknown result type (might be due to invalid IL or missing references)
        //IL_22ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_22db: Unknown result type (might be due to invalid IL or missing references)
        //IL_22e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2313: Unknown result type (might be due to invalid IL or missing references)
        //IL_2329: Unknown result type (might be due to invalid IL or missing references)
        //IL_2337: Unknown result type (might be due to invalid IL or missing references)
        //IL_233d: Unknown result type (might be due to invalid IL or missing references)
        //IL_233f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2349: Unknown result type (might be due to invalid IL or missing references)
        //IL_234e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2353: Unknown result type (might be due to invalid IL or missing references)
        if (wet && (type == 799 || type == 800 || type == 801 || type == 810 || type == 906 || type == 784 || type == 785 || type == 786 || type == 805 || type == 903 || type == 787 || type == 788 || type == 789 || type == 806 || type == 904 || type == 790 || type == 791 || type == 792 || type == 807 || type == 905))
        {
            timeLeft = 1;
        }
        if (type == 108 || type == 164 || type == 1002)
        {
            ai[0] += 1f;
            if (ai[0] > 3f)
            {
                Kill();
            }
        }
        if (type == 102)
        {
            int num = (int)(base.Center.X / 16f);
            int num12 = (int)(base.Center.Y / 16f);
            if (WorldGen.InWorld(num, num12))
            {
                Tile tile = Main.tile[num, num12];
                if (tile != null && tile.active() && (TileID.Sets.Platforms[tile.type] || tile.type == 380))
                {
                    Kill();
                    return;
                }
            }
        }
        Vector2 center;
        if (type == 75)
        {
            if (localAI[0] == 0f)
            {
                localAI[0] = 1f;
                SoundEngine.PlaySound(66, (int)position.X, (int)position.Y);
            }
            for (int i = 0; i < 255; i++)
            {
                if (Main.player[i].active && !Main.player[i].dead && !Main.player[i].ghost)
                {
                    center = base.Center - Main.player[i].Center;
                    if (((Vector2)(ref center)).Length() < 40f)
                    {
                        Kill();
                        return;
                    }
                }
            }
        }
        bool flag = false;
        if (type == 37 || type == 397 || type == 470 || type == 519 || type == 773 || type == 911)
        {
            try
            {
                int num23 = (int)(position.X / 16f) - 1;
                int num24 = (int)((position.X + (float)width) / 16f) + 2;
                int num25 = (int)(position.Y / 16f) - 1;
                int num26 = (int)((position.Y + (float)height) / 16f) + 2;
                if (num23 < 0)
                {
                    num23 = 0;
                }
                if (num24 > Main.maxTilesX)
                {
                    num24 = Main.maxTilesX;
                }
                if (num25 < 0)
                {
                    num25 = 0;
                }
                if (num26 > Main.maxTilesY)
                {
                    num26 = Main.maxTilesY;
                }
                Vector2 vector = default(Vector2);
                for (int j = num23; j < num24; j++)
                {
                    for (int k = num25; k < num26; k++)
                    {
                        if (Main.tile[j, k] == null || !Main.tile[j, k].nactive() || !Main.tileSolid[Main.tile[j, k].type] || Main.tileSolidTop[Main.tile[j, k].type])
{
                            continue;
                        }
                        vector.X = j * 16;
                        vector.Y = k * 16;
                        if (!(position.X + (float)width - 4f > vector.X) || !(position.X + 4f < vector.X + 16f) || !(position.Y + (float)height - 4f > vector.Y) || !(position.Y + 4f < vector.Y + 16f))
{
                            continue;
                        }
                        if (type == 911 && owner == Main.myPlayer && localAI[0] == 0f)
{
                            float num27 = 12f;
                            Vector2 value = vector + new Vector2(8f, 8f);
                            if (Vector2.Distance(base.Center, value) < num27)
{
                                base.Center += velocity.SafeNormalize(Vector2.Zero) * -4f;
                            }
                            localAI[0] = 1f;
                            netUpdate = true;
                        }
                        velocity.X = 0f;
                        velocity.Y = -0.2f;
                        flag = true;
                    }
                }
            }
            catch
            {
            }
        }
        if (flag && type == 911)
        {
            Point p = base.Center.ToTileCoordinates();
            if (WorldGen.SolidOrSlopedTile(Framing.GetTileSafely(p.X, p.Y)))
            {
                Vector2 v = p.ToWorldCoordinates() - base.Center;
                base.Center += v.SafeNormalize(Vector2.Zero) * -4f;
            }
        }
        if (flag && type == 773)
        {
            Player player = Main.player[owner];
            Vector2 v2 = DirectionTo(player.Center).SafeNormalize(Vector2.UnitX * (float)player.direction);
            float num28 = rotation;
            float num29 = v2.ToRotation() + (float)Math.PI / 2f;
            rotation = rotation.AngleLerp(num29, 0.2f);
            rotation = rotation.AngleTowards(num29, 0.05f);
            Vector2 vector2 = (rotation - (float)Math.PI / 2f).ToRotationVector2();
            if (Main.rand.Next(3) == 0)
            {
                Dust dust = Dust.NewDustPerfect(base.Center + vector2 * 10f, 59, vector2 * 2f + Main.rand.NextVector2Circular(0.25f, 0.25f), 0, default(Color), 2f);
                dust.noGravity = true;
                if (Main.rand.Next(3) == 0)
                {
                    dust.velocity *= 1.5f;
                    dust.noGravity = false;
                    dust.scale /= 2f;
                }
            }
            if (Main.rand.Next(3) == 0)
            {
                Point scarabBombDigDirectionSnap = GetScarabBombDigDirectionSnap8();
                Dust.NewDustPerfect(base.Center + vector2 * -10f, 59, scarabBombDigDirectionSnap.ToVector2() * 1.5f, 0, default(Color), 2f).noGravity = true;
            }
            if (Main.rand.Next(15) == 0)
            {
                Dust dust2 = Dust.NewDustPerfect(base.Center + vector2 * 10f, 88, vector2 * 3f + Main.rand.NextVector2Circular(0.25f, 0.25f), 0, default(Color), 2f);
                dust2.noGravity = true;
                if (Main.rand.Next(3) == 0)
                {
                    dust2.velocity *= 1.5f;
                }
            }
            bool flag2 = Main.rand.Next(30) == 0;
            if (num28 != rotation && Main.rand.Next(40) == 0)
            {
                flag2 = true;
            }
            if (flag2)
            {
                float num2 = (float)Math.PI * 2f * Main.rand.NextFloat();
                for (float num3 = 0f; num3 < 1f; num3 += 1f / 7f)
                {
                    Vector2 spinningpoint = (num3 * ((float)Math.PI * 2f) + num2).ToRotationVector2();
                    spinningpoint *= new Vector2(1f, 0.3f);
                    Vector2 spinningpoint2 = spinningpoint;
                    double radians = num29;
                    center = default(Vector2);
                    spinningpoint = spinningpoint2.RotatedBy(radians, center);
                    Dust dust5 = Dust.NewDustPerfect(base.Center + spinningpoint + vector2 * 8f, 59, vector2 * 3f + spinningpoint);
                    dust5.noGravity = true;
                    dust5.fadeIn = 1.6f;
                }
            }
            if (++frameCounter >= 3)
            {
                frameCounter = 0;
                if (++frame >= 4)
                {
                    frame = 0;
                }
            }
        }
        if (type == 519)
        {
            localAI[1] += 1f;
            float num4 = 180f - localAI[1];
            if (num4 < 0f)
            {
                num4 = 0f;
            }
            frameCounter++;
            if (num4 < 15f)
            {
                frameCounter++;
            }
            if ((float)frameCounter >= (num4 / 10f + 6f) / 2f)
            {
                frame++;
                frameCounter = 0;
                if (frame >= Main.projFrames[type])
                {
                    frame = 0;
                }
            }
        }
        if (type == 681 && localAI[1] == 0f)
        {
            localAI[1] = 1f;
        }
        int num5 = 6;
        if (type == 776 || type == 780 || type == 803 || type == 804)
        {
            num5 = 228;
        }
        else if (type == 784 || type == 805)
        {
            num5 = ((Main.rand.Next(3) == 0) ? 6 : Dust.dustWater());
        }
        else if (type == 787 || type == 806)
        {
            num5 = ((Main.rand.Next(3) == 0) ? 6 : 35);
        }
        else if (type == 790 || type == 807)
        {
            num5 = ((Main.rand.Next(3) == 0) ? 6 : 152);
        }
        if (type == 102)
        {
            if (velocity.Y > 10f)
            {
                velocity.Y = 10f;
            }
            if (localAI[0] == 0f)
            {
                localAI[0] = 1f;
                SoundEngine.PlaySound(in SoundID.Item10, position);
            }
            frameCounter++;
            if (frameCounter > 3)
            {
                frame++;
                frameCounter = 0;
            }
            if (frame > 1)
            {
                frame = 0;
            }
            if (velocity.Y == 0f)
            {
                position.X += width / 2;
                position.Y += height / 2;
                width = 128;
                height = 128;
                position.X -= width / 2;
                position.Y -= height / 2;
                damage = 40;
                knockBack = 8f;
                timeLeft = 3;
                netUpdate = true;
            }
        }
        if (type == 303 && timeLeft <= 3 && hostile)
        {
            position.X += width / 2;
            position.Y += height / 2;
            width = 128;
            height = 128;
            position.X -= width / 2;
            position.Y -= height / 2;
        }
        if (owner == Main.myPlayer && timeLeft <= 3)
        {
            PrepareBombToBlow();
        }
        else
        {
            if (type != 30 && type != 75 && type != 517 && type != 681 && type != 588 && type != 397 && type != 108 && type != 1002 && type != 133 && type != 134 && type != 135 && type != 136 && type != 137 && type != 138 && type != 139 && type != 140 && type != 141 && type != 142 && type != 143 && type != 144 && type != 164 && type != 303 && type != 338 && type != 339 && type != 340 && type != 341 && (type < 776 || type > 801) && (type < 803 || type > 810) && type != 862 && type != 863 && type != 930)
            {
                damage = 0;
            }
            if (type == 338 || type == 339 || type == 340 || type == 341 || type == 803 || type == 804 || type == 808 || type == 809 || type == 810 || type == 805 || type == 806 || type == 807 || type == 930)
            {
                localAI[1] += 1f;
                if (localAI[1] > 6f)
                {
                    alpha = 0;
                }
                else
                {
                    alpha = (int)(255f - 42f * localAI[1]) + 100;
                    if (alpha > 255)
                    {
                        alpha = 255;
                    }
                }
                for (int l = 0; l < 2; l++)
                {
                    float num6 = 0f;
                    float num7 = 0f;
                    if (l == 1)
                    {
                        num6 = velocity.X * 0.5f;
                        num7 = velocity.Y * 0.5f;
                    }
                    if (!(localAI[1] > 9f))
                    {
                        continue;
                    }
                    if (Main.rand.Next(2) == 0)
                    {
                        int num8 = Dust.NewDust(new Vector2(position.X + 3f + num6, position.Y + 3f + num7) - velocity * 0.5f, width - 8, height - 8, num5, 0f, 0f, 100);
                        Main.dust[num8].scale *= 1.4f + (float)Main.rand.Next(10) * 0.1f;
                        Dust obj2 = Main.dust[num8];
                        obj2.velocity *= 0.2f;
                        Main.dust[num8].noGravity = true;
                        if (Main.dust[num8].type == 152)
{
                            Main.dust[num8].scale *= 0.5f;
                            Dust obj3 = Main.dust[num8];
                            obj3.velocity += velocity * 0.1f;
                        }
                        else if (Main.dust[num8].type == 35)
{
                            Main.dust[num8].scale *= 0.5f;
                            Dust obj4 = Main.dust[num8];
                            obj4.velocity += velocity * 0.1f;
                        }
                        else if (Main.dust[num8].type == Dust.dustWater())
{
                            Main.dust[num8].scale *= 0.65f;
                            Dust obj5 = Main.dust[num8];
                            obj5.velocity += velocity * 0.1f;
                        }
                        if (type == 808 || type == 809)
{
                            Dust dust3 = Main.dust[num8];
                            if (dust3.dustIndex != 6000)
{
                                dust3 = Dust.NewDustPerfect(dust3.position, dust3.type, dust3.velocity, dust3.alpha, dust3.color, dust3.scale + 0.5f);
                                dust3.velocity = Main.rand.NextVector2Circular(3f, 3f);
                                dust3.noGravity = true;
                            }
                            if (dust3.dustIndex != 6000)
{
                                dust3 = Dust.NewDustPerfect(dust3.position, dust3.type, dust3.velocity, dust3.alpha, dust3.color, dust3.scale + 0.5f);
                                dust3.velocity = ((float)Math.PI * 2f * ((float)timeLeft / 20f)).ToRotationVector2() * 3f;
                                dust3.noGravity = true;
                            }
                        }
                    }
                    if (Main.rand.Next(2) == 0)
                    {
                        int num9 = Dust.NewDust(new Vector2(position.X + 3f + num6, position.Y + 3f + num7) - velocity * 0.5f, width - 8, height - 8, 31, 0f, 0f, 100, default(Color), 0.5f);
                        Main.dust[num9].fadeIn = 0.5f + (float)Main.rand.Next(5) * 0.1f;
                        Dust obj6 = Main.dust[num9];
                        obj6.velocity *= 0.05f;
                    }
                }
                float x = position.X;
                float y = position.Y;
                float num10 = 600f;
                if (type == 930)
                {
                    num10 = 650f;
                }
                bool flag3 = false;
                ai[0] += 1f;
                if (ai[0] > 30f)
                {
                    ai[0] = 30f;
                    for (int m = 0; m < 200; m++)
                    {
                        if (Main.npc[m].CanBeChasedBy(this))
{
                            float num11 = Main.npc[m].position.X + (float)(Main.npc[m].width / 2);
                            float num13 = Main.npc[m].position.Y + (float)(Main.npc[m].height / 2);
                            float num14 = Math.Abs(position.X + (float)(width / 2) - num11) + Math.Abs(position.Y + (float)(height / 2) - num13);
                            if (num14 < num10 && Collision.CanHit(position, width, height, Main.npc[m].position, Main.npc[m].width, Main.npc[m].height))
{
                                num10 = num14;
                                x = num11;
                                y = num13;
                                flag3 = true;
                            }
                        }
                    }
                }
                if (!flag3)
                {
                    x = position.X + (float)(width / 2) + velocity.X * 100f;
                    y = position.Y + (float)(height / 2) + velocity.Y * 100f;
                }
                float num15 = 16f;
                if (type == 930)
                {
                    num15 = 12f;
                }
                Vector2 value2 = (new Vector2(x, y) - base.Center).SafeNormalize(-Vector2.UnitY) * num15;
                velocity = Vector2.Lerp(velocity, value2, 1f / 12f);
            }
            else if (type == 134 || type == 137 || type == 140 || type == 143 || type == 303 || type == 776 || type == 780 || type == 793 || type == 796 || type == 799 || type == 784 || type == 787 || type == 790)
            {
                if (Math.Abs(velocity.X) >= 8f || Math.Abs(velocity.Y) >= 8f)
                {
                    for (int n = 0; n < 2; n++)
                    {
                        float num16 = 0f;
                        float num17 = 0f;
                        if (n == 1)
{
                            num16 = velocity.X * 0.5f;
                            num17 = velocity.Y * 0.5f;
                        }
                        int num18 = Dust.NewDust(new Vector2(position.X + 3f + num16, position.Y + 3f + num17) - velocity * 0.5f, width - 8, height - 8, num5, 0f, 0f, 100);
                        Main.dust[num18].scale *= 2f + (float)Main.rand.Next(10) * 0.1f;
                        Dust obj7 = Main.dust[num18];
                        obj7.velocity *= 0.2f;
                        Main.dust[num18].noGravity = true;
                        if (Main.dust[num18].type == 152)
{
                            Main.dust[num18].scale *= 0.5f;
                            Dust obj8 = Main.dust[num18];
                            obj8.velocity += velocity * 0.1f;
                        }
                        else if (Main.dust[num18].type == 35)
{
                            Main.dust[num18].scale *= 0.5f;
                            Dust obj9 = Main.dust[num18];
                            obj9.velocity += velocity * 0.1f;
                        }
                        else if (Main.dust[num18].type == Dust.dustWater())
{
                            Main.dust[num18].scale *= 0.65f;
                            Dust obj10 = Main.dust[num18];
                            obj10.velocity += velocity * 0.1f;
                        }
                        if (type == 793 || type == 796)
{
                            Dust dust4 = Main.dust[num18];
                            if (dust4.dustIndex != 6000)
{
                                dust4 = Dust.NewDustPerfect(dust4.position, dust4.type, dust4.velocity, dust4.alpha, dust4.color, dust4.scale);
                                dust4.velocity = Main.rand.NextVector2Circular(3f, 3f);
                                dust4.noGravity = true;
                            }
                            if (dust4.dustIndex != 6000)
{
                                dust4 = Dust.NewDustPerfect(dust4.position, dust4.type, dust4.velocity, dust4.alpha, dust4.color, dust4.scale);
                                dust4.velocity = ((float)Math.PI * 2f * ((float)timeLeft / 20f)).ToRotationVector2() * 3f;
                                dust4.noGravity = true;
                            }
                        }
                        num18 = Dust.NewDust(new Vector2(position.X + 3f + num16, position.Y + 3f + num17) - velocity * 0.5f, width - 8, height - 8, 31, 0f, 0f, 100, default(Color), 0.5f);
                        Main.dust[num18].fadeIn = 1f + (float)Main.rand.Next(5) * 0.1f;
                        Dust obj11 = Main.dust[num18];
                        obj11.velocity *= 0.05f;
                    }
                }
                if (Math.Abs(velocity.X) < 15f && Math.Abs(velocity.Y) < 15f)
                {
                    velocity *= 1.1f;
                }
            }
            else if (type == 133 || type == 136 || type == 139 || type == 142 || type == 777 || type == 781 || type == 794 || type == 797 || type == 800 || type == 785 || type == 788 || type == 791)
            {
                int num19 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100);
                Main.dust[num19].scale *= 1f + (float)Main.rand.Next(10) * 0.1f;
                Dust obj12 = Main.dust[num19];
                obj12.velocity *= 0.2f;
                Main.dust[num19].noGravity = true;
            }
            else if (type == 135 || type == 138 || type == 141 || type == 144 || type == 778 || type == 782 || type == 795 || type == 798 || type == 801 || type == 786 || type == 789 || type == 792)
            {
                if ((double)velocity.X > -0.2 && (double)velocity.X < 0.2 && (double)velocity.Y > -0.2 && (double)velocity.Y < 0.2)
                {
                    alpha += 2;
                    if (alpha > 200)
                    {
                        alpha = 200;
                    }
                }
                else
                {
                    alpha = 0;
                    int num20 = Dust.NewDust(new Vector2(position.X + 3f, position.Y + 3f) - velocity * 0.5f, width - 8, height - 8, 31, 0f, 0f, 100);
                    Main.dust[num20].scale *= 1.6f + (float)Main.rand.Next(5) * 0.1f;
                    Dust obj13 = Main.dust[num20];
                    obj13.velocity *= 0.05f;
                    Main.dust[num20].noGravity = true;
                }
            }
            else if (type == 779 || type == 783 || type == 862 || type == 863)
            {
                if (Main.rand.Next(25) == 0)
                {
                    Dust dust6 = Dust.NewDustDirect(position, width, height, 228, (0f - velocity.X) / 10f, (0f - velocity.Y) / 10f, 100);
                    dust6.noGravity = true;
                    dust6.velocity *= 0f;
                    dust6.scale = 1.3f;
                }
                if (Main.rand.Next(5) == 0)
                {
                    Dust dust7 = Dust.NewDustDirect(position, width, height, 31, (0f - velocity.X) / 10f, (0f - velocity.Y) / 10f, 100);
                    dust7.noGravity = true;
                    dust7.velocity *= 0f;
                    dust7.scale = 1.3f;
                }
                if (frameCounter == 0)
                {
                    frameCounter = 1;
                    frame = Main.rand.Next(4);
                }
            }
            else if (type != 30 && type != 517 && type != 681 && type != 397 && type != 519 && type != 588 && type != 779 && type != 783 && type != 862 && type != 863 && Main.rand.Next(2) == 0)
            {
                int num21 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100);
                Main.dust[num21].scale = 0.1f + (float)Main.rand.Next(5) * 0.1f;
                Main.dust[num21].fadeIn = 1.5f + (float)Main.rand.Next(5) * 0.1f;
                Main.dust[num21].noGravity = true;
                Dust obj14 = Main.dust[num21];
                Vector2 center2 = base.Center;
                Vector2 spinningpoint3 = new Vector2(0f, (float)(-height / 2));
                double radians2 = rotation;
                center = default(Vector2);
                obj14.position = center2 + Utils.RotatedBy(spinningpoint3, radians2, center) * 1.1f;
                int num22 = 6;
                if (type == 773)
                {
                    num22 = 59;
                }
                if (type == 903)
                {
                    num22 = Dust.dustWater();
                }
                if (type == 904)
                {
                    num22 = 35;
                }
                if (type == 905)
                {
                    num22 = 152;
                }
                if (type == 910 || type == 911)
                {
                    num22 = 0;
                }
                Dust dust8 = Dust.NewDustDirect(position, width, height, num22, 0f, 0f, 100);
                dust8.scale = 1f + (float)Main.rand.Next(5) * 0.1f;
                dust8.noGravity = true;
                Vector2 center3 = base.Center;
                Vector2 spinningpoint4 = new Vector2(0f, (float)(-height / 2 - 6));
                double radians3 = rotation;
                center = default(Vector2);
                dust8.position = center3 + Utils.RotatedBy(spinningpoint4, radians3, center) * 1.1f;
            }
            else if (type == 681)
            {
                Dust dust9 = Dust.NewDustDirect(position, width, height, 6, 0f, 0f, 100);
                dust9.scale = 1f + (float)Main.rand.Next(5) * 0.1f;
                dust9.noGravity = true;
                Vector2 center4 = base.Center;
                Vector2 spinningpoint5 = new Vector2((float)(6 * Math.Sign(velocity.X)), (float)(-height / 2 - 6));
                double radians4 = rotation;
                center = default(Vector2);
                dust9.position = center4 + Utils.RotatedBy(spinningpoint5, radians4, center) * 1.1f;
            }
        }
        ai[0] += 1f;
        if (type == 338 || type == 339 || type == 340 || type == 341 || type == 803 || type == 804 || type == 808 || type == 809 || type == 810 || type == 805 || type == 806 || type == 807 || type == 930)
        {
            if (velocity.X < 0f)
            {
                spriteDirection = -1;
                rotation = (float)Math.Atan2(0f - velocity.Y, 0f - velocity.X) - 1.57f;
            }
            else
            {
                spriteDirection = 1;
                rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
            }
        }
        else if (type == 134 || type == 137 || type == 140 || type == 143 || type == 303 || type == 776 || type == 780 || type == 793 || type == 796 || type == 799 || type == 784 || type == 787 || type == 790)
        {
            if (velocity != Vector2.Zero)
            {
                rotation = (float)Math.Atan2(velocity.Y, velocity.X) + 1.57f;
            }
        }
        else if (type == 135 || type == 138 || type == 141 || type == 144 || type == 778 || type == 782 || type == 795 || type == 798 || type == 801 || type == 786 || type == 789 || type == 792)
        {
            velocity.Y += 0.2f;
            velocity *= 0.97f;
            if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1)
            {
                velocity.X = 0f;
            }
            if ((double)velocity.Y > -0.1 && (double)velocity.Y < 0.1)
            {
                velocity.Y = 0f;
            }
        }
        else if (type == 133 || type == 136 || type == 139 || type == 142 || type == 777 || type == 781 || type == 794 || type == 797 || type == 800 || type == 785 || type == 788 || type == 791)
        {
            if (ai[0] > 15f)
            {
                if (velocity.Y == 0f)
                {
                    velocity.X *= 0.95f;
                }
                velocity.Y += 0.2f;
            }
        }
        else if (((type == 30 || type == 397 || type == 517 || type == 681 || type == 588 || type == 779 || type == 783 || type == 862 || type == 863) && ai[0] > 10f) || (type != 30 && type != 397 && type != 517 && type != 588 && type != 779 && type != 783 && type != 862 && type != 863 && ai[0] > 5f))
        {
            ai[0] = 10f;
            if (velocity.Y == 0f && velocity.X != 0f)
            {
                velocity.X *= 0.97f;
                if (type == 29 || type == 470 || type == 637)
                {
                    velocity.X *= 0.99f;
                }
                if ((double)velocity.X > -0.01 && (double)velocity.X < 0.01)
                {
                    velocity.X = 0f;
                    netUpdate = true;
                }
            }
            velocity.Y += 0.2f;
            if (type == 911)
            {
                velocity.X = MathHelper.Clamp(velocity.X, -8f, 8f);
                velocity.Y = MathHelper.Clamp(velocity.Y, -8f, 8f);
            }
        }
        if (type == 519)
        {
            rotation += velocity.X * 0.06f;
        }
        else if (type != 134 && type != 137 && type != 140 && type != 143 && type != 303 && (type < 338 || type > 341) && type != 776 && type != 780 && type != 793 && type != 796 && type != 799 && type != 784 && type != 787 && type != 790 && type != 803 && type != 804 && type != 808 && type != 809 && type != 810 && type != 805 && type != 806 && type != 807 && type != 930)
        {
            rotation += velocity.X * 0.1f;
        }
    }
References Terraria.Entity.active, Terraria.Tile.active(), Terraria.NPC.CanBeChasedBy(), Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Player.dead, Terraria.Entity.direction, Terraria.Main.dust, Terraria.Dust.dustWater(), Terraria.Dust.fadeIn, Terraria.Framing.GetTileSafely(), Terraria.Player.ghost, Terraria.Entity.height, Terraria.WorldGen.InWorld(), Terraria.ID.SoundID.Item10, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.npc, Terraria.ID.TileID.Sets.Platforms, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.projFrames, Terraria.Main.rand, Terraria.Utils.RotatedBy(), Terraria.Dust.scale, Terraria.WorldGen.SolidOrSlopedTile(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Dust.type, Terraria.Tile.type, and Terraria.Entity.width.