TModLoader: Terraria.Projectile.CreateGroundExplosion
CreateGroundExplosion()
void Terraria.Projectile.CreateGroundExplosion (float MAX_SPREAD, int fluff, int distFluff, int layerStart, int layerEnd, int layerJump) inline private
Definition at line 56678 of file Projectile.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0248: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d8: Unknown result type (might be due to invalid IL or missing references)
        Point point = base.TopLeft.ToTileCoordinates();
        Point point2 = base.BottomRight.ToTileCoordinates();
        point.X -= fluff;
        point.Y -= fluff;
        point2.X += fluff;
        point2.Y += fluff;
        int num = point.X / 2 + point2.X / 2;
        int num2 = width / 2 + distFluff;
        for (int i = layerStart; i < layerEnd; i += layerJump)
        {
            int num3 = i;
            for (int j = point.X; j <= point2.X; j++)
            {
                for (int k = point.Y; k <= point2.Y; k++)
                {
                    if (!WorldGen.InWorld(j, k, 10))
                    {
                        return;
                    }
                    if (Vector2.Distance(base.Center, new Vector2((float)(j * 16), (float)(k * 16))) > (float)num2)
                    {
                        continue;
                    }
                    Tile tileSafely = Framing.GetTileSafely(j, k);
                    if (!tileSafely.active() || !Main.tileSolid[tileSafely.type] || Main.tileSolidTop[tileSafely.type] || Main.tileFrameImportant[tileSafely.type])
                    {
                        continue;
                    }
                    Tile tileSafely2 = Framing.GetTileSafely(j, k - 1);
                    if (tileSafely2.active() && Main.tileSolid[tileSafely2.type] && !Main.tileSolidTop[tileSafely2.type])
                    {
                        continue;
                    }
                    int num4 = WorldGen.KillTile_GetTileDustAmount(fail: true, tileSafely, j, k);
                    for (int l = 0; l < num4; l++)
                    {
                        Dust obj = Main.dust[WorldGen.KillTile_MakeTileDust(j, k, tileSafely)];
                        obj.velocity.Y -= 3f + (float)num3 * 1.5f;
                        obj.velocity.Y *= Main.rand.NextFloat();
                        obj.scale += (float)num3 * 0.03f;
                    }
                    if (num3 >= 2)
                    {
                        for (int m = 0; m < num4 - 1; m++)
{
                            Dust obj2 = Main.dust[WorldGen.KillTile_MakeTileDust(j, k, tileSafely)];
                            obj2.velocity.Y -= 1f + (float)num3;
                            obj2.velocity.Y *= Main.rand.NextFloat();
                        }
                    }
                    if (num4 > 0 && Main.rand.Next(3) != 0)
                    {
                        float num5 = (float)Math.Abs(num - j) / (MAX_SPREAD / 2f);
                        Gore gore = Gore.NewGoreDirect(position, Vector2.Zero, 61 + Main.rand.Next(3), 1f - (float)num3 * 0.15f + num5 * 0.5f);
                        gore.velocity.Y -= 0.1f + (float)num3 * 0.5f + num5 * (float)num3 * 1f;
                        gore.velocity.Y *= Main.rand.NextFloat();
                        gore.position = new Vector2((float)(j * 16 + 20), (float)(k * 16 + 20));
                    }
                }
            }
        }
    }
References Terraria.Main.dust, Terraria.Framing.GetTileSafely(), Terraria.WorldGen.InWorld(), Terraria.WorldGen.KillTile_GetTileDustAmount(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.Gore.NewGoreDirect(), Terraria.Main.rand, Terraria.Main.tileFrameImportant, Terraria.Main.tileSolid, and Terraria.Main.tileSolidTop.
Referenced by Terraria.Projectile.MakeBoulderOfEarthExplosion().