TModLoader: Terraria.Projectile.NewProjectile
NewProjectile() [1/2]
static int Terraria.Projectile.NewProjectile (IEntitySource spawnSource, float X, float Y, float SpeedX, float SpeedY, int Type, int Damage, float KnockBack, int Owner = -1, float ai0 = 0f, float ai1 = 0f, float ai2 = 0f) inline static
Spawns a projectile into the game world with the given type. The spawn position is given in world coordinates by the X and Y parameters. SpeedX and SpeedY dictate the initial velocity. Damage and KnockBack are self-explanatory. Owner is the player who spawned the projectile, almost always Main.myPlayer. ai0, ai1, and ai2 will initialize the Projectile.ai[] array with the supplied values. This can be used to pass in information to the Projectile. The Projectile AI code will have to be written to utilize those values. The return value is the index of the spawned Projectile within the F:Terraria.Main.projectile array.
Make sure that this method is called only by the client in charge of the source causing this projectile to spawn. Failure to do this will result in the projectile spawning once for each player in the world. For example, if Player code uses this method, make sure to first check.
if(Main.myPlayer == Player.whoAmI) to ensure that only the local player spawns the projectile.
Projectiles spawning other projectiles should check if(Main.myPlayer == Projectile.owner)
If the source is an NPC or non-player owned projectile, checking if (Main.netMode != NetmodeID.MultiplayerClient) will ensure that clients don't attempt to spawn the projectile.
Parameters
spawnSource
X
Y
SpeedX
SpeedY
Type Either a T:Terraria.ID.ProjectileID entry or M:Terraria.ModLoader.ModContent.ProjectileType``1, for example F:Terraria.ID.ProjectileID.FireArrow or ModContent.ProjectileType<MyModProjectile>()
Damage
KnockBack
Owner
ai0
ai1
ai2
Returns
Definition at line 10144 of file Projectile.cs.
    {
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        if (Owner == -1)
        {
            Owner = Main.myPlayer;
        }
        int num = 1000;
        for (int i = 0; i < 1000; i++)
        {
            if (!Main.projectile[i].active)
            {
                num = i;
                break;
            }
        }
        if (num == 1000)
        {
            num = FindOldestProjectile();
        }
        Projectile projectile = Main.projectile[num];
        projectile.SetDefaults(Type);
        projectile.position.X = X - (float)projectile.width * 0.5f;
        projectile.position.Y = Y - (float)projectile.height * 0.5f;
        projectile.owner = Owner;
        projectile.velocity.X = SpeedX;
        projectile.velocity.Y = SpeedY;
        projectile.damage = Damage;
        projectile.knockBack = KnockBack;
        projectile.identity = num;
        projectile.gfxOffY = 0f;
        projectile.stepSpeed = 1f;
        projectile.wet = Collision.WetCollision(projectile.position, projectile.width, projectile.height);
        if (projectile.ignoreWater)
        {
            projectile.wet = false;
        }
        projectile.honeyWet = Collision.honey;
        projectile.shimmerWet = Collision.shimmer;
        Main.projectileIdentity[Owner, num] = num;
        FindBannerToAssociateTo(spawnSource, projectile);
        if (projectile.aiStyle == 1)
        {
            while (projectile.velocity.X >= 16f || projectile.velocity.X <= -16f || projectile.velocity.Y >= 16f || projectile.velocity.Y < -16f)
            {
                projectile.velocity.X *= 0.97f;
                projectile.velocity.Y *= 0.97f;
            }
        }
        if (Owner == Main.myPlayer)
        {
            switch (Type)
            {
            case 206:
                projectile.ai[0] = (float)Main.rand.Next(-100, 101) * 0.0005f;
                projectile.ai[1] = (float)Main.rand.Next(-100, 101) * 0.0005f;
                break;
            case 335:
                projectile.ai[1] = Main.rand.Next(4);
                break;
            case 358:
                projectile.ai[1] = (float)Main.rand.Next(10, 31) * 0.1f;
                break;
            case 406:
                projectile.ai[1] = (float)Main.rand.Next(10, 21) * 0.1f;
                break;
            default:
                projectile.ai[0] = ai0;
                projectile.ai[1] = ai1;
                projectile.ai[2] = ai2;
                break;
            }
        }
        if (Type == 434)
        {
            projectile.ai[0] = projectile.position.X;
            projectile.ai[1] = projectile.position.Y;
        }
        if (Type > 0)
        {
            if (ProjectileID.Sets.NeedsUUID[Type])
            {
                projectile.projUUID = projectile.identity;
            }
            if (ProjectileID.Sets.StardustDragon[Type])
            {
                int num2 = Main.projectile[(int)projectile.ai[0]].projUUID;
                if (num2 >= 0)
                {
                    projectile.ai[0] = num2;
                }
            }
        }
        if (Owner == Main.myPlayer)
        {
            if (ProjectileID.Sets.IsAGolfBall[Type] && Damage <= 0)
            {
                int num3 = 0;
                int num4 = 0;
                int num5 = 99999999;
                for (int j = 0; j < 1000; j++)
                {
                    if (Main.projectile[j].active && ProjectileID.Sets.IsAGolfBall[Main.projectile[j].type] && Main.projectile[j].owner == Owner && Main.projectile[j].damage <= 0)
                    {
                        num3++;
                        if (num5 > Main.projectile[j].timeLeft)
{
                            num4 = j;
                            num5 = Main.projectile[j].timeLeft;
                        }
                    }
                }
                if (num3 > 10)
                {
                    Main.projectile[num4].Kill();
                }
            }
            if (Type == 28)
            {
                projectile.timeLeft = 180;
            }
            if (Type == 516)
            {
                projectile.timeLeft = 180;
            }
            if (Type == 519)
            {
                projectile.timeLeft = 180;
            }
            if (Type == 29)
            {
                projectile.timeLeft = 300;
            }
            if (Type == 470)
            {
                projectile.timeLeft = 300;
            }
            if (Type == 637)
            {
                projectile.timeLeft = 300;
            }
            if (Type == 30)
            {
                projectile.timeLeft = 180;
            }
            if (Type == 517)
            {
                projectile.timeLeft = 180;
            }
            if (Type == 37)
            {
                projectile.timeLeft = 180;
            }
            if (Type == 773)
            {
                projectile.timeLeft = 180;
            }
            if (Type == 75)
            {
                projectile.timeLeft = 180;
            }
            if (Type == 133)
            {
                projectile.timeLeft = 180;
            }
            if (Type == 136)
            {
                projectile.timeLeft = 180;
            }
            if (Type == 139)
            {
                projectile.timeLeft = 180;
            }
            if (Type == 142)
            {
                projectile.timeLeft = 180;
            }
            if (Type == 397)
            {
                projectile.timeLeft = 180;
            }
            if (Type == 419)
            {
                projectile.timeLeft = 600;
            }
            if (Type == 420)
            {
                projectile.timeLeft = 600;
            }
            if (Type == 421)
            {
                projectile.timeLeft = 600;
            }
            if (Type == 422)
            {
                projectile.timeLeft = 600;
            }
            if (Type == 588)
            {
                projectile.timeLeft = 180;
            }
            if (Type == 779)
            {
                projectile.timeLeft = 60;
            }
            if (Type == 783)
            {
                projectile.timeLeft = 60;
            }
            if (Type == 862 || Type == 863)
            {
                projectile.timeLeft = 60;
            }
            if (Type == 443)
            {
                projectile.timeLeft = 300;
            }
            if (Type == 681)
            {
                projectile.timeLeft = 600;
            }
            if (Type == 684)
            {
                projectile.timeLeft = 60;
            }
            if (Type == 706)
            {
                projectile.timeLeft = 120;
            }
            if (Type == 680 && Main.player[projectile.owner].setSquireT2)
            {
                projectile.penetrate = 7;
            }
            if (Type == 777 || Type == 781 || Type == 794 || Type == 797 || Type == 800 || Type == 785 || Type == 788 || Type == 791 || Type == 903 || Type == 904 || Type == 905 || Type == 906 || Type == 910 || Type == 911)
            {
                projectile.timeLeft = 180;
            }
            if (Main.netMode != 2)
            {
                Player throwingPlayer = Main.player[Owner];
                if (throwingPlayer.AnyThrownCostReduction && throwingPlayer.HeldItem.CountsAsClass(DamageClass.Throwing) && spawnSource is EntitySource_ItemUse_WithAmmo)
                {
                    projectile.noDropItem = true;
                }
            }
        }
        if (Type == 249)
        {
            projectile.frame = Main.rand.Next(5);
        }
        if (Owner == Main.myPlayer)
        {
            Main.player[Owner].TryUpdateChannel(projectile);
        }
        projectile.ApplyStatsFromSource(spawnSource);
        ProjectileLoader.OnSpawn(projectile, spawnSource);
        if (Main.netMode != 0 && Owner == Main.myPlayer)
        {
            NetMessage.SendData(27, -1, -1, null, num);
        }
        return num;
    }
References Terraria.Projectile.ai, Terraria.Projectile.aiStyle, Terraria.Projectile.ApplyStatsFromSource(), Terraria.Projectile.Damage(), Terraria.Projectile.FindBannerToAssociateTo(), Terraria.Projectile.FindOldestProjectile(), Terraria.Entity.height, Terraria.Collision.honey, Terraria.Projectile.identity, Terraria.Projectile.ignoreWater, Terraria.ID.ProjectileID.Sets.IsAGolfBall, Terraria.Main.myPlayer, Terraria.ID.ProjectileID.Sets.NeedsUUID, Terraria.Main.netMode, Terraria.ModLoader.ProjectileLoader.OnSpawn(), Terraria.Projectile.owner, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.projectileIdentity, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Projectile.SetDefaults(), Terraria.Collision.shimmer, Terraria.ID.ProjectileID.Sets.StardustDragon, Terraria.ModLoader.DamageClass.Throwing, Terraria.Entity.velocity, Terraria.Collision.WetCollision(), and Terraria.Entity.width.