TModLoader: Terraria.Projectile.Colliding
Colliding()
bool Terraria.Projectile.Colliding (Rectangle myRect, Rectangle targetRect) inline
Definition at line 14236 of file Projectile.cs.
    {
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d05: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0145: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d29: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d30: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d36: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d49: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_025d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0262: Unknown result type (might be due to invalid IL or missing references)
        //IL_0271: Unknown result type (might be due to invalid IL or missing references)
        //IL_0276: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_027f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ddf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e05: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e12: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e19: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_040f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0efb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0494: Unknown result type (might be due to invalid IL or missing references)
        //IL_0495: Unknown result type (might be due to invalid IL or missing references)
        //IL_0498: Unknown result type (might be due to invalid IL or missing references)
        //IL_049d: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0417: Unknown result type (might be due to invalid IL or missing references)
        //IL_0418: Unknown result type (might be due to invalid IL or missing references)
        //IL_041d: Unknown result type (might be due to invalid IL or missing references)
        //IL_041e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0424: Unknown result type (might be due to invalid IL or missing references)
        //IL_0429: Unknown result type (might be due to invalid IL or missing references)
        //IL_042d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0432: Unknown result type (might be due to invalid IL or missing references)
        //IL_0438: Unknown result type (might be due to invalid IL or missing references)
        //IL_043d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0441: Unknown result type (might be due to invalid IL or missing references)
        //IL_0446: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fcd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e90: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e96: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eaa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_030d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0312: Unknown result type (might be due to invalid IL or missing references)
        //IL_0319: Unknown result type (might be due to invalid IL or missing references)
        //IL_0338: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05db: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0630: Unknown result type (might be due to invalid IL or missing references)
        //IL_0635: Unknown result type (might be due to invalid IL or missing references)
        //IL_0638: Unknown result type (might be due to invalid IL or missing references)
        //IL_063d: Unknown result type (might be due to invalid IL or missing references)
        //IL_064e: Unknown result type (might be due to invalid IL or missing references)
        //IL_035f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0360: Unknown result type (might be due to invalid IL or missing references)
        //IL_0365: Unknown result type (might be due to invalid IL or missing references)
        //IL_0366: Unknown result type (might be due to invalid IL or missing references)
        //IL_036b: Unknown result type (might be due to invalid IL or missing references)
        //IL_036d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0371: Unknown result type (might be due to invalid IL or missing references)
        //IL_0376: Unknown result type (might be due to invalid IL or missing references)
        //IL_037b: Unknown result type (might be due to invalid IL or missing references)
        //IL_037d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0381: Unknown result type (might be due to invalid IL or missing references)
        //IL_0386: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0723: Unknown result type (might be due to invalid IL or missing references)
        //IL_0656: Unknown result type (might be due to invalid IL or missing references)
        //IL_0657: Unknown result type (might be due to invalid IL or missing references)
        //IL_065c: Unknown result type (might be due to invalid IL or missing references)
        //IL_065d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0663: Unknown result type (might be due to invalid IL or missing references)
        //IL_0668: Unknown result type (might be due to invalid IL or missing references)
        //IL_066c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0671: Unknown result type (might be due to invalid IL or missing references)
        //IL_0677: Unknown result type (might be due to invalid IL or missing references)
        //IL_067c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0680: Unknown result type (might be due to invalid IL or missing references)
        //IL_0685: Unknown result type (might be due to invalid IL or missing references)
        //IL_072b: Unknown result type (might be due to invalid IL or missing references)
        //IL_072c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0731: Unknown result type (might be due to invalid IL or missing references)
        //IL_0732: Unknown result type (might be due to invalid IL or missing references)
        //IL_0738: Unknown result type (might be due to invalid IL or missing references)
        //IL_073d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0741: Unknown result type (might be due to invalid IL or missing references)
        //IL_0746: Unknown result type (might be due to invalid IL or missing references)
        //IL_074c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0751: Unknown result type (might be due to invalid IL or missing references)
        //IL_0755: Unknown result type (might be due to invalid IL or missing references)
        //IL_075a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0795: Unknown result type (might be due to invalid IL or missing references)
        //IL_0796: Unknown result type (might be due to invalid IL or missing references)
        //IL_079b: Unknown result type (might be due to invalid IL or missing references)
        //IL_079d: Unknown result type (might be due to invalid IL or missing references)
        //IL_079e: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0886: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0804: Unknown result type (might be due to invalid IL or missing references)
        //IL_0809: Unknown result type (might be due to invalid IL or missing references)
        //IL_0811: Unknown result type (might be due to invalid IL or missing references)
        //IL_081b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0820: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_088f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0838: Unknown result type (might be due to invalid IL or missing references)
        //IL_083a: Unknown result type (might be due to invalid IL or missing references)
        //IL_083d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0843: Unknown result type (might be due to invalid IL or missing references)
        //IL_0848: Unknown result type (might be due to invalid IL or missing references)
        //IL_0850: Unknown result type (might be due to invalid IL or missing references)
        //IL_085a: Unknown result type (might be due to invalid IL or missing references)
        //IL_085f: Unknown result type (might be due to invalid IL or missing references)
        //IL_089a: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a33: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0902: Unknown result type (might be due to invalid IL or missing references)
        //IL_0911: Unknown result type (might be due to invalid IL or missing references)
        //IL_1014: Unknown result type (might be due to invalid IL or missing references)
        //IL_1015: Unknown result type (might be due to invalid IL or missing references)
        //IL_101a: Unknown result type (might be due to invalid IL or missing references)
        //IL_101b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1021: Unknown result type (might be due to invalid IL or missing references)
        //IL_1027: Unknown result type (might be due to invalid IL or missing references)
        //IL_102d: Unknown result type (might be due to invalid IL or missing references)
        //IL_103a: Unknown result type (might be due to invalid IL or missing references)
        //IL_103f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_09cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a05: Unknown result type (might be due to invalid IL or missing references)
        //IL_1071: Unknown result type (might be due to invalid IL or missing references)
        //IL_1072: Unknown result type (might be due to invalid IL or missing references)
        //IL_1077: Unknown result type (might be due to invalid IL or missing references)
        //IL_1078: Unknown result type (might be due to invalid IL or missing references)
        //IL_107e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1084: Unknown result type (might be due to invalid IL or missing references)
        //IL_108a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1097: Unknown result type (might be due to invalid IL or missing references)
        //IL_109c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a50: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_10cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_10d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_10d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_10db: Unknown result type (might be due to invalid IL or missing references)
        //IL_10e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_10e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_10f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_10f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_10fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1106: Unknown result type (might be due to invalid IL or missing references)
        //IL_110b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aaf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0adc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0962: Unknown result type (might be due to invalid IL or missing references)
        //IL_0967: Unknown result type (might be due to invalid IL or missing references)
        //IL_096c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0970: Unknown result type (might be due to invalid IL or missing references)
        //IL_1141: Unknown result type (might be due to invalid IL or missing references)
        //IL_1146: Unknown result type (might be due to invalid IL or missing references)
        //IL_114b: Unknown result type (might be due to invalid IL or missing references)
        //IL_115b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1161: Unknown result type (might be due to invalid IL or missing references)
        //IL_1163: Unknown result type (might be due to invalid IL or missing references)
        //IL_116e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1173: Unknown result type (might be due to invalid IL or missing references)
        //IL_1175: Unknown result type (might be due to invalid IL or missing references)
        //IL_1176: Unknown result type (might be due to invalid IL or missing references)
        //IL_117b: Unknown result type (might be due to invalid IL or missing references)
        //IL_117c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1182: Unknown result type (might be due to invalid IL or missing references)
        //IL_1187: Unknown result type (might be due to invalid IL or missing references)
        //IL_118e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1193: Unknown result type (might be due to invalid IL or missing references)
        //IL_1199: Unknown result type (might be due to invalid IL or missing references)
        //IL_119e: Unknown result type (might be due to invalid IL or missing references)
        //IL_11a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_11aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b08: Unknown result type (might be due to invalid IL or missing references)
        //IL_11dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_11dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1202: Unknown result type (might be due to invalid IL or missing references)
        //IL_1207: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b83: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1246: Unknown result type (might be due to invalid IL or missing references)
        //IL_1247: Unknown result type (might be due to invalid IL or missing references)
        //IL_124c: Unknown result type (might be due to invalid IL or missing references)
        //IL_124d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1253: Unknown result type (might be due to invalid IL or missing references)
        //IL_1259: Unknown result type (might be due to invalid IL or missing references)
        //IL_125f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1264: Unknown result type (might be due to invalid IL or missing references)
        //IL_1269: Unknown result type (might be due to invalid IL or missing references)
        //IL_126e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1278: Unknown result type (might be due to invalid IL or missing references)
        //IL_1283: Unknown result type (might be due to invalid IL or missing references)
        //IL_1288: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c76: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c85: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bfc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c11: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c29: Unknown result type (might be due to invalid IL or missing references)
        //IL_1304: Unknown result type (might be due to invalid IL or missing references)
        //IL_130f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1319: Unknown result type (might be due to invalid IL or missing references)
        //IL_1320: Unknown result type (might be due to invalid IL or missing references)
        //IL_1325: Unknown result type (might be due to invalid IL or missing references)
        //IL_132a: Unknown result type (might be due to invalid IL or missing references)
        //IL_132d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1338: Unknown result type (might be due to invalid IL or missing references)
        //IL_1342: Unknown result type (might be due to invalid IL or missing references)
        //IL_1349: Unknown result type (might be due to invalid IL or missing references)
        //IL_134e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1353: Unknown result type (might be due to invalid IL or missing references)
        //IL_1355: Unknown result type (might be due to invalid IL or missing references)
        //IL_1356: Unknown result type (might be due to invalid IL or missing references)
        //IL_135b: Unknown result type (might be due to invalid IL or missing references)
        //IL_135c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1361: Unknown result type (might be due to invalid IL or missing references)
        //IL_1363: Unknown result type (might be due to invalid IL or missing references)
        //IL_0caa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cbf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cdc: Unknown result type (might be due to invalid IL or missing references)
        //IL_13e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1512: Unknown result type (might be due to invalid IL or missing references)
        //IL_1518: Unknown result type (might be due to invalid IL or missing references)
        //IL_1525: Unknown result type (might be due to invalid IL or missing references)
        //IL_152b: Unknown result type (might be due to invalid IL or missing references)
        //IL_152d: Unknown result type (might be due to invalid IL or missing references)
        //IL_154a: Unknown result type (might be due to invalid IL or missing references)
        //IL_154f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1568: Unknown result type (might be due to invalid IL or missing references)
        //IL_156d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1574: Unknown result type (might be due to invalid IL or missing references)
        //IL_157a: Unknown result type (might be due to invalid IL or missing references)
        //IL_157c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1581: Unknown result type (might be due to invalid IL or missing references)
        //IL_1590: Unknown result type (might be due to invalid IL or missing references)
        //IL_1595: Unknown result type (might be due to invalid IL or missing references)
        //IL_159a: Unknown result type (might be due to invalid IL or missing references)
        //IL_159e: Unknown result type (might be due to invalid IL or missing references)
        //IL_148d: Unknown result type (might be due to invalid IL or missing references)
        Rectangle val;
        if (aiStyle == 15)
        {
            if (ai[0] == 0f)
            {
                Vector2 mountedCenter = Main.player[owner].MountedCenter;
                Vector2 vector = targetRect.ClosestPointInRect(mountedCenter) - mountedCenter;
                vector.Y /= 0.8f;
                float num = 55f;
                return ((Vector2)(ref vector)).Length() <= num;
            }
        }
        else if (type == 973)
        {
            Vector2 v = targetRect.ClosestPointInRect(base.Center) - base.Center;
            v.SafeNormalize(Vector2.UnitX);
            float num12 = 100f * scale;
            if (((Vector2)(ref v)).Length() < num12 && Collision.CanHit(base.Center, 0, 0, ((Rectangle)(ref targetRect)).Center.ToVector2(), 0, 0))
            {
                return true;
            }
        }
        else
        {
            if (type == 85)
            {
                if (!((Rectangle)(ref myRect)).Intersects(targetRect))
                {
                    return false;
                }
                return Collision.CanHit(base.Center, 0, 0, ((Rectangle)(ref targetRect)).Center.ToVector2(), 0, 0);
            }
            if (type == 985)
            {
                float coneLength = 90f * scale;
                float maximumAngle = (float)Math.PI / 4f;
                float coneRotation = rotation;
                if (targetRect.IntersectsConeFastInaccurate(base.Center, coneLength, coneRotation, maximumAngle) && Collision.CanHit(base.Center, 0, 0, ((Rectangle)(ref targetRect)).Center.ToVector2(), 0, 0))
                {
                    return true;
                }
            }
            else
            {
                if (aiStyle == 190)
                {
                    float coneLength2 = 94f * scale;
                    float num21 = (float)Math.PI * 2f / 25f * ai[0];
                    float maximumAngle2 = (float)Math.PI / 4f;
                    float num22 = rotation + num21;
                    if (targetRect.IntersectsConeSlowMoreAccurate(base.Center, coneLength2, num22, maximumAngle2))
                    {
                        return true;
                    }
                    float num23 = Utils.Remap(localAI[0], ai[1] * 0.3f, ai[1] * 0.5f, 1f, 0f);
                    if (num23 > 0f)
                    {
                        float coneRotation2 = num22 - (float)Math.PI / 4f * ai[0] * num23;
                        if (targetRect.IntersectsConeSlowMoreAccurate(base.Center, coneLength2, coneRotation2, maximumAngle2))
{
                            return true;
                        }
                    }
                    return false;
                }
                if (type == 623)
                {
                    if (ai[0] == 2f)
                    {
                        Rectangle value = Utils.CenteredRectangle(base.Center + new Vector2((float)(direction * 40), 0f), new Vector2(80f, 40f));
                        if (((Rectangle)(ref targetRect)).Intersects(value))
{
                            return true;
                        }
                    }
                }
                else
                {
                    if (type == 933)
                    {
                        float collisionPoint = 0f;
                        float num24 = 40f;
                        for (int i = 14; i < oldPos.Length; i += 15)
{
                            float num25 = localAI[0] - (float)i;
                            if (!(num25 < 0f) && !(num25 > 60f))
{
                                Vector2 vector4 = oldPos[i] + base.Size / 2f;
                                Vector2 vector5 = (oldRot[i] + (float)Math.PI / 2f).ToRotationVector2();
                                _lanceHitboxBounds.X = (int)vector4.X - _lanceHitboxBounds.Width / 2;
                                _lanceHitboxBounds.Y = (int)vector4.Y - _lanceHitboxBounds.Height / 2;
                                if (((Rectangle)(ref _lanceHitboxBounds)).Intersects(targetRect) && Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), vector4 - vector5 * num24, vector4 + vector5 * num24, 20f, ref collisionPoint))
{
                                    return true;
                                }
                            }
                        }
                        Vector2 vector6 = (rotation + (float)Math.PI / 2f).ToRotationVector2();
                        _lanceHitboxBounds.X = (int)position.X - _lanceHitboxBounds.Width / 2;
                        _lanceHitboxBounds.Y = (int)position.Y - _lanceHitboxBounds.Height / 2;
                        if (((Rectangle)(ref _lanceHitboxBounds)).Intersects(targetRect) && Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center - vector6 * num24, base.Center + vector6 * num24, 20f, ref collisionPoint))
{
                            return true;
                        }
                        return false;
                    }
                    if (type == 927)
                    {
                        for (float num26 = 0f; num26 <= 1f; num26 += 0.05f)
{
                            float num27 = Utils.Remap(num26, 0f, 1f, 1f, 5f);
                            Rectangle rectangle = myRect;
                            Vector2 vector7 = velocity.SafeNormalize(Vector2.Zero) * (float)width * num27 * scale;
                            ((Rectangle)(ref rectangle)).Offset((int)vector7.X, (int)vector7.Y);
                            if (((Rectangle)(ref rectangle)).Intersects(targetRect))
{
                                return true;
                            }
                        }
                    }
                    else
                    {
                        if (type == 877 || type == 878 || type == 879)
{
                            float f = rotation - (float)Math.PI / 4f - (float)Math.PI / 2f - ((spriteDirection == 1) ? ((float)Math.PI) : 0f);
                            float collisionPoint10 = 0f;
                            float num2 = 95f;
                            _lanceHitboxBounds.X = (int)position.X - _lanceHitboxBounds.Width / 2;
                            _lanceHitboxBounds.Y = (int)position.Y - _lanceHitboxBounds.Height / 2;
                            if (((Rectangle)(ref _lanceHitboxBounds)).Intersects(targetRect) && Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + f.ToRotationVector2() * num2, 23f * scale, ref collisionPoint10))
{
                                return true;
                            }
                            return false;
                        }
                        if (type == 974)
{
                            float f4 = rotation;
                            float collisionPoint11 = 0f;
                            float num3 = 46f * scale;
                            float num4 = 8f;
                            Vector2 vector8 = f4.ToRotationVector2();
                            Rectangle hitbox = base.Hitbox;
                            ((Rectangle)(ref hitbox)).Inflate((int)num3, (int)num3);
                            if (((Rectangle)(ref hitbox)).Intersects(targetRect) && Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center - vector8 * num3, base.Center + vector8 * num3, num4 * scale, ref collisionPoint11))
{
                                return true;
                            }
                            return false;
                        }
                        if (type == 919 || type == 932)
{
                            float f5 = rotation;
                            float collisionPoint12 = 0f;
                            float num5 = 40f;
                            Vector2 vector9 = f5.ToRotationVector2();
                            _lanceHitboxBounds.X = (int)position.X - _lanceHitboxBounds.Width / 2;
                            _lanceHitboxBounds.Y = (int)position.Y - _lanceHitboxBounds.Height / 2;
                            if (((Rectangle)(ref _lanceHitboxBounds)).Intersects(targetRect) && Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center - vector9 * num5, base.Center + vector9 * num5, 8f, ref collisionPoint12))
{
                                return true;
                            }
                            return false;
                        }
                        if (type == 923)
{
                            float collisionPoint13 = 0f;
                            _ = scale;
                            float f6 = rotation;
                            Vector2 objectPosition = targetRect.TopLeft();
                            Vector2 objectDimensions = targetRect.Size();
                            Vector2 vector10 = f6.ToRotationVector2();
                            float num6 = scale * 0.7f;
                            if (Collision.CheckAABBvLineCollision(objectPosition, objectDimensions, base.Center, base.Center + vector10 * scale * 510f, num6 * 100f, ref collisionPoint13))
{
                                return true;
                            }
                            if (Collision.CheckAABBvLineCollision(objectPosition, objectDimensions, base.Center, base.Center + vector10 * scale * 660f, num6 * 60f, ref collisionPoint13))
{
                                return true;
                            }
                            if (Collision.CheckAABBvLineCollision(objectPosition, objectDimensions, base.Center, base.Center + vector10 * scale * 800f, num6 * 10f, ref collisionPoint13))
{
                                return true;
                            }
                            return false;
                        }
                        if (type == 598 && targetRect.Width > 8 && targetRect.Height > 8)
{
                            ((Rectangle)(ref targetRect)).Inflate(-targetRect.Width / 8, -targetRect.Height / 8);
                        }
                        else
{
                            if (type == 872)
{
                                Rectangle hitbox2 = base.Hitbox;
                                int num7 = 80;
                                for (int j = 0; j < num7; j += 2)
{
                                    Vector2 vector11 = oldPos[j];
                                    if (!(vector11 == Vector2.Zero))
{
                                        hitbox2.X = (int)vector11.X;
                                        hitbox2.Y = (int)vector11.Y;
                                        if (((Rectangle)(ref hitbox2)).Intersects(targetRect))
{
                                            return true;
                                        }
                                    }
                                }
                                return false;
                            }
                            if (type == 871)
{
                                int num8 = AI_172_GetPelletStormsCount();
                                for (int k = 0; k < num8; k++)
{
                                    HallowBossPelletStormInfo hallowBossPelletStormInfo = AI_172_GetPelletStormInfo(k);
                                    for (int l = 0; l < hallowBossPelletStormInfo.BulletsInStorm; l++)
{
                                        if (hallowBossPelletStormInfo.IsValid(l))
{
                                            val = hallowBossPelletStormInfo.GetBulletHitbox(l, base.Center);
                                            if (((Rectangle)(ref val)).Intersects(targetRect))
{
                                                return true;
                                            }
                                        }
                                    }
                                }
                                return false;
                            }
                            if (ProjectileID.Sets.IsAWhip[type])
{
                                WhipPointsForCollision.Clear();
                                FillWhipControlPoints(this, WhipPointsForCollision);
                                for (int m = 0; m < WhipPointsForCollision.Count; m++)
{
                                    Point point = WhipPointsForCollision[m].ToPoint();
                                    ((Rectangle)(ref myRect)).Location = new Point(point.X - myRect.Width / 2, point.Y - myRect.Height / 2);
                                    if (((Rectangle)(ref myRect)).Intersects(targetRect))
{
                                        return true;
                                    }
                                }
                                return false;
                            }
                            if (type == 614 && targetRect.Width > 8 && targetRect.Height > 8)
{
                                ((Rectangle)(ref targetRect)).Inflate(-targetRect.Width / 8, -targetRect.Height / 8);
                            }
                            else if (type == 963 && ai[0] >= 2f)
{
                                ((Rectangle)(ref targetRect)).Inflate(30, 30);
                            }
                            else if (type == 758)
{
                                if (ai[0] == 2f)
{
                                    val = Utils.CenteredRectangle(base.Center + new Vector2((float)(spriteDirection * 30), 0f), new Vector2(50f, 20f));
                                    if (((Rectangle)(ref val)).Intersects(targetRect))
{
                                        return true;
                                    }
                                }
                            }
                            else if (type == 636 && targetRect.Width > 8 && targetRect.Height > 8)
{
                                ((Rectangle)(ref targetRect)).Inflate(-targetRect.Width / 8, -targetRect.Height / 8);
                            }
                            else if (type == 607)
{
                                myRect.X += (int)velocity.X;
                                myRect.Y += (int)velocity.Y;
                            }
                            else if (type == 661)
{
                                if (Vector2.Distance(((Rectangle)(ref myRect)).Center.ToVector2(), ((Rectangle)(ref targetRect)).Center.ToVector2()) > 500f || !Collision.CanHitLine(((Rectangle)(ref myRect)).Center.ToVector2(), 0, 0, ((Rectangle)(ref targetRect)).Center.ToVector2(), 0, 0))
{
                                    return false;
                                }
                            }
                            else
{
                                if (aiStyle == 137)
{
                                    if (((Rectangle)(ref myRect)).Intersects(targetRect) && targetRect.Distance(base.Center) < (float)(height / 2 - 20))
{
                                        if (AI_137_CanHit(((Rectangle)(ref targetRect)).Center.ToVector2()))
{
                                            return true;
                                        }
                                        if (AI_137_CanHit(targetRect.TopLeft() + new Vector2((float)(targetRect.Width / 2), 0f)))
{
                                            return true;
                                        }
                                    }
                                    return false;
                                }
                                if (aiStyle == 19)
{
                                    Vector2 center = base.Center;
                                    if (AI_019_Spears_GetExtensionHitbox(out var extensionBox))
{
                                        Vector2 vector2 = ((Rectangle)(ref extensionBox)).Center.ToVector2();
                                        float num9 = Vector2.Distance(vector2, center);
                                        Vector2 size = extensionBox.Size();
                                        float num10 = MathHelper.Max((float)extensionBox.Width, (float)extensionBox.Height);
                                        if (num10 < 12f)
{
                                            num10 = 12f;
                                        }
                                        for (float num11 = num10; num11 < num9; num11 += num10)
{
                                            val = Utils.CenteredRectangle(Vector2.Lerp(center, vector2, num11 / num9), size);
                                            if (((Rectangle)(ref val)).Intersects(targetRect))
{
                                                return true;
                                            }
                                        }
                                        if (((Rectangle)(ref extensionBox)).Intersects(targetRect))
{
                                            return true;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        bool? flag = ProjectileLoader.Colliding(this, myRect, targetRect);
        if (flag.HasValue)
        {
            return flag.GetValueOrDefault();
        }
        if (((Rectangle)(ref myRect)).Intersects(targetRect))
        {
            return true;
        }
        if (type == 461)
        {
            float collisionPoint14 = 0f;
            if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity * localAI[1], 22f * scale, ref collisionPoint14))
            {
                return true;
            }
            return false;
        }
        if (type == 697 || type == 707)
        {
            float f2 = rotation - (float)Math.PI / 4f * (float)Math.Sign(velocity.X);
            float collisionPoint15 = 0f;
            float num13 = 50f;
            if (type == 697)
            {
                num13 = 65f;
            }
            if (type == 707)
            {
                num13 = 110f;
            }
            if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center + f2.ToRotationVector2() * (0f - num13), base.Center + f2.ToRotationVector2() * num13, 23f * scale, ref collisionPoint15))
            {
                return true;
            }
            return false;
        }
        if (type == 699)
        {
            float f3 = rotation - (float)Math.PI / 4f * (float)Math.Sign(velocity.X) + ((spriteDirection == -1) ? ((float)Math.PI) : 0f);
            float collisionPoint16 = 0f;
            float num14 = -95f;
            if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + f3.ToRotationVector2() * num14, 23f * scale, ref collisionPoint16))
            {
                return true;
            }
            return false;
        }
        if (type == 642)
        {
            float collisionPoint17 = 0f;
            if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity * localAI[1], 30f * scale, ref collisionPoint17))
            {
                return true;
            }
            return false;
        }
        if (type == 802 || type == 842 || type == 938 || type == 939 || type == 940 || type == 941 || type == 942 || type == 943 || type == 944 || type == 945)
        {
            float collisionPoint2 = 0f;
            if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity * 6f, 10f * scale, ref collisionPoint2))
            {
                return true;
            }
            return false;
        }
        if (type == 632)
        {
            float collisionPoint3 = 0f;
            if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity * localAI[1], 22f * scale, ref collisionPoint3))
            {
                return true;
            }
            return false;
        }
        if (type == 455)
        {
            float collisionPoint4 = 0f;
            if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity * localAI[1], 36f * scale, ref collisionPoint4))
            {
                return true;
            }
            return false;
        }
        if (type == 611)
        {
            float collisionPoint5 = 0f;
            if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity + velocity.SafeNormalize(Vector2.Zero) * 48f, 16f * scale, ref collisionPoint5))
            {
                return true;
            }
            return false;
        }
        if (type == 684)
        {
            float collisionPoint6 = 0f;
            Vector2 vector3 = velocity.SafeNormalize(Vector2.UnitY).RotatedBy(-1.5707963705062866) * scale;
            if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center - vector3 * 40f, base.Center + vector3 * 40f, 16f * scale, ref collisionPoint6))
            {
                return true;
            }
            return false;
        }
        if (type == 537)
        {
            float collisionPoint7 = 0f;
            if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity * localAI[1], 22f * scale, ref collisionPoint7))
            {
                return true;
            }
            return false;
        }
        if (type == 756 || type == 961)
        {
            float collisionPoint8 = 0f;
            if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), base.Center, base.Center + velocity.SafeNormalize(-Vector2.UnitY) * 200f * scale, 22f * scale, ref collisionPoint8))
            {
                return true;
            }
            return false;
        }
        if (type == 687)
        {
            float collisionPoint9 = 0f;
            float num15 = ai[0] / 25f;
            if (num15 > 1f)
            {
                num15 = 1f;
            }
            float num16 = (ai[0] - 38f) / 40f;
            if (num16 < 0f)
            {
                num16 = 0f;
            }
            Vector2 lineStart = base.Center + rotation.ToRotationVector2() * 400f * num16;
            Vector2 lineEnd = base.Center + rotation.ToRotationVector2() * 400f * num15;
            if (Collision.CheckAABBvLineCollision(targetRect.TopLeft(), targetRect.Size(), lineStart, lineEnd, 40f * scale, ref collisionPoint9))
            {
                return true;
            }
            return false;
        }
        if (type == 466 || type == 580 || type == 686)
        {
            for (int n = 0; n < oldPos.Length && (oldPos[n].X != 0f || oldPos[n].Y != 0f); n++)
            {
                myRect.X = (int)oldPos[n].X;
                myRect.Y = (int)oldPos[n].Y;
                if (((Rectangle)(ref myRect)).Intersects(targetRect))
                {
                    return true;
                }
            }
            return false;
        }
        if (type == 711)
        {
            if (penetrate != -1)
            {
                for (int num17 = 0; num17 < oldPos.Length && (oldPos[num17].X != 0f || oldPos[num17].Y != 0f); num17++)
                {
                    myRect.X = (int)oldPos[num17].X;
                    myRect.Y = (int)oldPos[num17].Y;
                    if (((Rectangle)(ref myRect)).Intersects(targetRect))
                    {
                        return true;
                    }
                }
            }
        }
        else if (type == 464 && ai[1] != 1f)
        {
            Vector2 val2 = Utils.RotatedBy(new Vector2(0f, -720f), velocity.ToRotation());
            float num18 = ai[0] % 45f / 45f;
            Vector2 spinningpoint = val2 * num18;
            for (int num19 = 0; num19 < 6; num19++)
            {
                float num20 = (float)num19 * ((float)Math.PI * 2f) / 6f;
                val = Utils.CenteredRectangle(base.Center + spinningpoint.RotatedBy(num20), new Vector2(30f, 30f));
                if (((Rectangle)(ref val)).Intersects(targetRect))
                {
                    return true;
                }
            }
        }
        return false;
    }
References Terraria.Projectile._lanceHitboxBounds, Terraria.Projectile.ai, Terraria.Projectile.AI_019_Spears_GetExtensionHitbox(), Terraria.Projectile.AI_137_CanHit(), Terraria.Projectile.AI_172_GetPelletStormInfo(), Terraria.Projectile.AI_172_GetPelletStormsCount(), Terraria.Projectile.aiStyle, Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.Collision.CheckAABBvLineCollision(), Terraria.ModLoader.ProjectileLoader.Colliding(), Terraria.Entity.direction, Terraria.Projectile.FillWhipControlPoints(), Terraria.Entity.height, Terraria.ID.ProjectileID.Sets.IsAWhip, Terraria.Projectile.localAI, Terraria.Player.MountedCenter, Terraria.Projectile.oldPos, Terraria.Projectile.oldRot, Terraria.Projectile.owner, Terraria.Projectile.penetrate, Terraria.Main.player, Terraria.Entity.position, Terraria.Utils.Remap(), Terraria.Utils.RotatedBy(), Terraria.Projectile.rotation, Terraria.Projectile.scale, Terraria.Projectile.spriteDirection, Terraria.Projectile.type, Terraria.Entity.velocity, Terraria.Projectile.WhipPointsForCollision, and Terraria.Entity.width.
Referenced by Terraria.Projectile.Damage(), and Terraria.Projectile.VanillaAI().