TModLoader: Terraria.Projectile.AI_010
AI_010()
void Terraria.Projectile.AI_010 () inline private
Definition at line 62973 of file Projectile.cs.
    {
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0107: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_0254: Unknown result type (might be due to invalid IL or missing references)
        //IL_0280: Unknown result type (might be due to invalid IL or missing references)
        //IL_0286: Unknown result type (might be due to invalid IL or missing references)
        //IL_029c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_030f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0315: Unknown result type (might be due to invalid IL or missing references)
        //IL_037c: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_020d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0212: Unknown result type (might be due to invalid IL or missing references)
        //IL_0217: Unknown result type (might be due to invalid IL or missing references)
        //IL_085b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0876: Unknown result type (might be due to invalid IL or missing references)
        //IL_0409: Unknown result type (might be due to invalid IL or missing references)
        //IL_0429: Unknown result type (might be due to invalid IL or missing references)
        //IL_042f: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_048c: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0512: Unknown result type (might be due to invalid IL or missing references)
        //IL_0535: Unknown result type (might be due to invalid IL or missing references)
        //IL_053b: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0700: Unknown result type (might be due to invalid IL or missing references)
        //IL_0706: Unknown result type (might be due to invalid IL or missing references)
        //IL_062d: Unknown result type (might be due to invalid IL or missing references)
        //IL_065d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0663: Unknown result type (might be due to invalid IL or missing references)
        //IL_0688: Unknown result type (might be due to invalid IL or missing references)
        //IL_0692: Unknown result type (might be due to invalid IL or missing references)
        //IL_0698: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ac: Unknown result type (might be due to invalid IL or missing references)
        if (type == 31 && ai[0] != 2f)
        {
            if (Main.rand.Next(2) == 0)
            {
                int num = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 32, 0f, velocity.Y / 2f);
                Main.dust[num].velocity.X *= 0.4f;
            }
        }
        else if (type == 39)
        {
            if (Main.rand.Next(2) == 0)
            {
                int num9 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 38, 0f, velocity.Y / 2f);
                Main.dust[num9].velocity.X *= 0.4f;
            }
        }
        else if (type >= 411 && type <= 414)
        {
            if (Main.rand.Next(3) == 0)
            {
                int num10 = 9;
                if (type == 412 || type == 414)
                {
                    num10 = 11;
                }
                if (type == 413)
                {
                    num10 = 19;
                }
                int num11 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, num10, 0f, velocity.Y / 2f);
                Main.dust[num11].noGravity = true;
                Dust obj = Main.dust[num11];
                obj.velocity -= velocity * 0.5f;
            }
        }
        else if (type == 40)
        {
            if (Main.rand.Next(2) == 0)
            {
                int num12 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 36, 0f, velocity.Y / 2f);
                Dust obj2 = Main.dust[num12];
                obj2.velocity *= 0.4f;
            }
        }
        else if (type == 42 || type == 31)
        {
            if (Main.rand.Next(2) == 0)
            {
                int num13 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 32);
                Main.dust[num13].velocity.X *= 0.4f;
            }
        }
        else if (type == 56 || type == 65)
        {
            if (Main.rand.Next(2) == 0)
            {
                int num14 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 14);
                Main.dust[num14].velocity.X *= 0.4f;
            }
        }
        else if (type == 67 || type == 68)
        {
            if (Main.rand.Next(2) == 0)
            {
                int num15 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 51);
                Main.dust[num15].velocity.X *= 0.4f;
            }
        }
        else if (type == 71)
        {
            if (Main.rand.Next(2) == 0)
            {
                int num16 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 53);
                Main.dust[num16].velocity.X *= 0.4f;
            }
        }
        else if (type == 179)
        {
            if (Main.rand.Next(2) == 0)
            {
                int num2 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 149);
                Main.dust[num2].velocity.X *= 0.4f;
            }
        }
        else if (type == 241 || type == 354)
        {
            if (Main.rand.Next(2) == 0)
            {
                int num3 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 36);
                Main.dust[num3].velocity.X *= 0.4f;
            }
        }
        else if (type >= 736 && type <= 738)
        {
            if (Main.rand.Next(40) == 0)
            {
                int num4 = Dust.NewDust(position, width, height, type - 736 + 275);
                if (num4 >= 0)
                {
                    Main.dust[num4].velocity = Main.dust[num4].velocity * 0.5f + velocity * 0.5f;
                }
            }
        }
        else if (type != 109 && Main.rand.Next(20) == 0)
        {
            Dust.NewDust(new Vector2(position.X, position.Y), width, height, 0);
        }
        if (type >= 736 && type <= 738)
        {
            if (localAI[0] == 0f)
            {
                frame = Main.rand.Next(3);
                scale = 1f - (float)Main.rand.Next(30) * 0.01f;
            }
            localAI[0] += 1f;
        }
        tileCollide = true;
        localAI[1] = 0f;
        if (Main.myPlayer == owner && ai[0] == 0f)
        {
            tileCollide = false;
            if (Main.player[owner].channel && (type < 736 || type > 738) && type != 40)
            {
                localAI[1] = -1f;
                float num5 = 12f;
                Vector2 vector = default(Vector2);
                ((Vector2)(ref vector))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                float num6 = (float)Main.mouseX + Main.screenPosition.X - vector.X;
                float num7 = (float)Main.mouseY + Main.screenPosition.Y - vector.Y;
                if (Main.player[owner].gravDir == -1f)
                {
                    num7 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - vector.Y;
                }
                float num8 = (float)Math.Sqrt(num6 * num6 + num7 * num7);
                num8 = (float)Math.Sqrt(num6 * num6 + num7 * num7);
                if (num8 > num5)
                {
                    num8 = num5 / num8;
                    num6 *= num8;
                    num7 *= num8;
                    if (num6 != velocity.X || num7 != velocity.Y)
                    {
                        netUpdate = true;
                    }
                    velocity.X = num6;
                    velocity.Y = num7;
                }
                else
                {
                    if (num6 != velocity.X || num7 != velocity.Y)
                    {
                        netUpdate = true;
                    }
                    velocity.X = num6;
                    velocity.Y = num7;
                }
            }
            else
            {
                ai[0] = 1f;
                netUpdate = true;
            }
        }
        if (ai[0] == 1f && type != 109)
        {
            if (type == 42 || type == 65 || type == 68 || type == 354)
            {
                ai[1] += 1f;
                if (ai[1] >= 60f)
                {
                    ai[1] = 60f;
                    velocity.Y += 0.2f;
                }
            }
            else
            {
                velocity.Y += 0.41f;
            }
        }
        else if (ai[0] == 2f && type != 109)
        {
            velocity.Y += 0.2f;
            if ((double)velocity.X < -0.04)
            {
                velocity.X += 0.04f;
            }
            else if ((double)velocity.X > 0.04)
            {
                velocity.X -= 0.04f;
            }
            else
            {
                velocity.X = 0f;
            }
        }
        if (owner == Main.myPlayer && tileCollide)
        {
            for (int i = (int)(position.X / 16f); i <= (int)((position.X + (float)width) / 16f); i++)
            {
                for (int j = (int)(position.Y / 16f); j <= (int)((position.Y + (float)height) / 16f); j++)
                {
                    if (!WorldGen.InWorld(i, j))
                    {
                        continue;
                    }
                    Tile tile = Main.tile[i, j];
                    if (tile == null || !tile.active())
                    {
                        continue;
                    }
                    if ((tile.type >= 185 && tile.type <= 187) || tile.type == 165 || tile.type == 12 || tile.type == 665 || tile.type == 639 || tile.type == 105 || tile.type == 178)
                    {
                        WorldGen.KillTile(i, j);
                    }
                    else if (tile.topSlope() && !TileID.Sets.Platforms[tile.type])
                    {
                        WorldGen.SlopeTile(i, j);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 14, i, j);
                        }
                        position.Y -= 16f;
                    }
                }
            }
        }
        if (type >= 736 && type <= 738)
        {
            if (frame == 0)
            {
                rotation -= 0.1f;
            }
            else if (frame == 1)
            {
                rotation += 0.1f;
            }
            else
            {
                rotation += 0.15f;
            }
            if (velocity.Y > 10f)
            {
                velocity.Y = 10f;
            }
        }
        else
        {
            rotation += 0.1f;
            if (velocity.Y > 10f)
            {
                velocity.Y = 10f;
            }
        }
    }
References Terraria.Tile.active(), Terraria.Player.channel, Terraria.Main.dust, Terraria.Player.gravDir, Terraria.WorldGen.InWorld(), Terraria.WorldGen.KillTile(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.ID.TileID.Sets.Platforms, Terraria.Main.player, Terraria.Main.rand, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.NetMessage.SendData(), Terraria.WorldGen.SlopeTile(), Terraria.Main.tile, Terraria.Tile.topSlope(), Terraria.Tile.type, and Terraria.Dust.velocity.