TModLoader: Terraria.Projectile.AI_143_MonkStaffT2Ghast
AI_143_MonkStaffT2Ghast()
void Terraria.Projectile.AI_143_MonkStaffT2Ghast () inline private
Definition at line 77163 of file Projectile.cs.
    {
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_0209: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_0228: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_0254: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_0268: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0290: Unknown result type (might be due to invalid IL or missing references)
        //IL_0296: Unknown result type (might be due to invalid IL or missing references)
        //IL_029b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a0: Unknown result type (might be due to invalid IL or missing references)
        if (ai[0] == 0f)
        {
            localAI[1] = SoundEngine.PlayTrackedSound(in SoundID.DD2_GhastlyGlaiveImpactGhost, base.Center).ToFloat();
        }
        ActiveSound activeSound = SoundEngine.GetActiveSound(SlotId.FromFloat(localAI[1]));
        if (activeSound == null)
        {
            localAI[1] = SlotId.Invalid.ToFloat();
        }
        else
        {
            activeSound.Position = base.Center;
        }
        ai[0] += 1f;
        if (ai[0] > 50f)
        {
            alpha += 25;
            if (alpha > 255)
            {
                alpha = 255;
            }
        }
        else
        {
            alpha -= 25;
            if (alpha < 100)
            {
                alpha = 100;
            }
        }
        velocity *= 0.98f;
        if (++frameCounter >= 5)
        {
            frameCounter = 0;
            if (++frame >= 4)
            {
                frame = 0;
            }
        }
        if (ai[0] >= 60f)
        {
            Kill();
        }
        direction = (spriteDirection = ((velocity.X > 0f) ? 1 : (-1)));
        rotation = velocity.ToRotation();
        if (spriteDirection == -1)
        {
            rotation += (float)Math.PI;
        }
        if (ai[0] >= 10f && ai[0] < 34f)
        {
            Vector2 vector = velocity.SafeNormalize(Vector2.UnitY);
            float num = ai[0] / 60f;
            float num2 = 2f;
            for (int i = 0; (float)i < num2; i++)
            {
                Dust dust = Dust.NewDustDirect(base.Center, 14, 14, 228, 0f, 0f, 110);
                dust.velocity = vector * 2f;
                dust.position = base.Center + vector.RotatedBy(num * ((float)Math.PI * 2f) * 2f + (float)i / num2 * ((float)Math.PI * 2f)) * 7f;
                dust.scale = 1f + 0.6f * Main.rand.NextFloat();
                dust.velocity += vector * 3f;
                dust.noGravity = true;
            }
        }
    }
References Terraria.ID.SoundID.DD2_GhastlyGlaiveImpactGhost, Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.Dust.NewDustDirect(), Terraria.Audio.SoundEngine.PlayTrackedSound(), and Terraria.Main.rand.