TModLoader: Terraria.Projectile.FishingCheck
FishingCheck()
void Terraria.Projectile.FishingCheck () inline
Definition at line 19511 of file Projectile.cs.
    {
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_067f: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_074f: Unknown result type (might be due to invalid IL or missing references)
        if (Main.player[owner].wet && !(base.Center.Y >= Main.player[owner].RotatedRelativePoint(Main.player[owner].MountedCenter).Y))
        {
            return;
        }
        FishingAttempt fisher = default(FishingAttempt);
        fisher.X = (int)(base.Center.X / 16f);
        fisher.Y = (int)(base.Center.Y / 16f);
        fisher.bobberType = type;
        GetFishingPondState(fisher.X, fisher.Y, out fisher.inLava, out fisher.inHoney, out fisher.waterTilesCount, out fisher.chumsInWater);
        if (Main.notTheBeesWorld && Main.rand.Next(2) == 0)
        {
            fisher.inHoney = false;
        }
        if (fisher.waterTilesCount < 75)
        {
            Main.player[owner].displayedFishingInfo = Language.GetTextValue("GameUI.NotEnoughWater");
            return;
        }
        fisher.playerFishingConditions = Main.player[owner].GetFishingConditions();
        if (fisher.playerFishingConditions.BaitItemType == 2673)
        {
            Main.player[owner].displayedFishingInfo = Language.GetTextValue("GameUI.FishingWarning");
            if ((fisher.X < 380 || fisher.X > Main.maxTilesX - 380) && fisher.waterTilesCount > 1000 && !NPC.AnyNPCs(370))
            {
                ai[1] = Main.rand.Next(-180, -60) - 100;
                localAI[1] = 1f;
                netUpdate = true;
            }
            return;
        }
        fisher.fishingLevel = fisher.playerFishingConditions.FinalFishingLevel;
        if (fisher.fishingLevel == 0)
        {
            return;
        }
        fisher.CanFishInLava = ItemID.Sets.CanFishInLava[fisher.playerFishingConditions.PoleItemType] || ItemID.Sets.IsLavaBait[fisher.playerFishingConditions.BaitItemType] || Main.player[owner].accLavaFishing;
        if (fisher.chumsInWater > 0)
        {
            fisher.fishingLevel += 11;
        }
        if (fisher.chumsInWater > 1)
        {
            fisher.fishingLevel += 6;
        }
        if (fisher.chumsInWater > 2)
        {
            fisher.fishingLevel += 3;
        }
        Main.player[owner].displayedFishingInfo = Language.GetTextValue("GameUI.FishingPower", fisher.fishingLevel);
        fisher.waterNeededToFish = 300;
        float num = (float)Main.maxTilesX / 4200f;
        num *= num;
        fisher.atmo = (float)((double)(position.Y / 16f - (60f + 10f * num)) / (Main.worldSurface / 6.0));
        if ((double)fisher.atmo < 0.25)
        {
            fisher.atmo = 0.25f;
        }
        if (fisher.atmo > 1f)
        {
            fisher.atmo = 1f;
        }
        fisher.waterNeededToFish = (int)((float)fisher.waterNeededToFish * fisher.atmo);
        fisher.waterQuality = (float)fisher.waterTilesCount / (float)fisher.waterNeededToFish;
        if (fisher.waterQuality < 1f)
        {
            fisher.fishingLevel = (int)((float)fisher.fishingLevel * fisher.waterQuality);
        }
        fisher.waterQuality = 1f - fisher.waterQuality;
        if (fisher.waterTilesCount < fisher.waterNeededToFish)
        {
            Main.player[owner].displayedFishingInfo = Language.GetTextValue("GameUI.FullFishingPower", fisher.fishingLevel, 0.0 - Math.Round(fisher.waterQuality * 100f));
        }
        if (Main.player[owner].luck < 0f)
        {
            if (Main.rand.NextFloat() < 0f - Main.player[owner].luck)
            {
                fisher.fishingLevel = (int)((double)fisher.fishingLevel * (0.9 - (double)Main.rand.NextFloat() * 0.3));
            }
        }
        else if (Main.rand.NextFloat() < Main.player[owner].luck)
        {
            fisher.fishingLevel = (int)((double)fisher.fishingLevel * (1.1 + (double)Main.rand.NextFloat() * 0.3));
        }
        int num2 = (fisher.fishingLevel + 75) / 2;
        if (Main.rand.Next(100) > num2)
        {
            return;
        }
        fisher.heightLevel = 0;
        if (Main.remixWorld)
        {
            if ((double)fisher.Y < Main.worldSurface * 0.5)
            {
                fisher.heightLevel = 0;
            }
            else if ((double)fisher.Y < Main.worldSurface)
            {
                fisher.heightLevel = 1;
            }
            else if ((double)fisher.Y < Main.rockLayer)
            {
                fisher.heightLevel = 3;
            }
            else if (fisher.Y < Main.maxTilesY - 300)
            {
                fisher.heightLevel = 2;
            }
            else
            {
                fisher.heightLevel = 4;
            }
            if (fisher.heightLevel == 2 && Main.rand.Next(2) == 0)
            {
                fisher.heightLevel = 1;
            }
        }
        else if ((double)fisher.Y < Main.worldSurface * 0.5)
        {
            fisher.heightLevel = 0;
        }
        else if ((double)fisher.Y < Main.worldSurface)
        {
            fisher.heightLevel = 1;
        }
        else if ((double)fisher.Y < Main.rockLayer)
        {
            fisher.heightLevel = 2;
        }
        else if (fisher.Y < Main.maxTilesY - 300)
        {
            fisher.heightLevel = 3;
        }
        else
        {
            fisher.heightLevel = 4;
        }
        FishingCheck_RollDropLevels(fisher.fishingLevel, out fisher.common, out fisher.uncommon, out fisher.rare, out fisher.veryrare, out fisher.legendary, out fisher.crate);
        PlayerLoader.ModifyFishingAttempt(Main.player[owner], ref fisher);
        FishingCheck_ProbeForQuestFish(ref fisher);
        FishingCheck_RollEnemySpawns(ref fisher);
        FishingCheck_RollItemDrop(ref fisher);
        bool flag = false;
        AdvancedPopupRequest sonar = default(AdvancedPopupRequest);
        Vector2 sonarPosition = default(Vector2);
        ((Vector2)(ref sonarPosition))._002Ector(position.X, position.Y);
        PlayerLoader.CatchFish(Main.player[owner], fisher, ref fisher.rolledItemDrop, ref fisher.rolledEnemySpawn, ref sonar, ref sonarPosition);
        if (sonar.Text != null && Main.player[owner].sonarPotion)
        {
            PopupText.AssignAsSonarText(PopupText.NewText(sonar, sonarPosition));
        }
        if (fisher.rolledItemDrop > 0)
        {
            if (sonar.Text == null && Main.player[owner].sonarPotion)
            {
                Item item = new Item();
                item.SetDefaults(fisher.rolledItemDrop);
                item.position = position;
                PopupText.AssignAsSonarText(PopupText.NewText(PopupTextContext.SonarAlert, item, 1, noStack: true));
            }
            float num3 = fisher.fishingLevel;
            ai[1] = (float)Main.rand.Next(-240, -90) - num3;
            localAI[1] = fisher.rolledItemDrop;
            netUpdate = true;
            flag = true;
        }
        if (fisher.rolledEnemySpawn > 0)
        {
            if (sonar.Text == null && Main.player[owner].sonarPotion)
            {
                PopupText.AssignAsSonarText(PopupText.NewText(PopupTextContext.SonarAlert, fisher.rolledEnemySpawn, base.Center, stay5TimesLonger: false));
            }
            float num4 = fisher.fishingLevel;
            ai[1] = (float)Main.rand.Next(-240, -90) - num4;
            localAI[1] = -fisher.rolledEnemySpawn;
            netUpdate = true;
            flag = true;
        }
        if (!flag && fisher.inLava)
        {
            int num5 = 0;
            if (ItemID.Sets.IsLavaBait[fisher.playerFishingConditions.BaitItemType])
            {
                num5++;
            }
            if (ItemID.Sets.CanFishInLava[fisher.playerFishingConditions.PoleItemType])
            {
                num5++;
            }
            if (Main.player[owner].accLavaFishing)
            {
                num5++;
            }
            if (num5 >= 2)
            {
                localAI[1] += 240f;
            }
        }
        if (fisher.CanFishInLava && fisher.inLava)
        {
            AchievementsHelper.HandleSpecialEvent(Main.player[owner], 19);
        }
    }
References Terraria.Player.accLavaFishing, Terraria.Projectile.ai, Terraria.NPC.AnyNPCs(), Terraria.PopupText.AssignAsSonarText(), Terraria.ID.ItemID.Sets.CanFishInLava, Terraria.ModLoader.PlayerLoader.CatchFish(), Terraria.Player.displayedFishingInfo, Terraria.Projectile.FishingCheck_ProbeForQuestFish(), Terraria.Projectile.FishingCheck_RollDropLevels(), Terraria.Projectile.FishingCheck_RollEnemySpawns(), Terraria.Projectile.FishingCheck_RollItemDrop(), Terraria.Player.GetFishingConditions(), Terraria.Projectile.GetFishingPondState(), Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.ID.ItemID.Sets.IsLavaBait, Terraria.Projectile.localAI, Terraria.Player.luck, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.ModLoader.PlayerLoader.ModifyFishingAttempt(), Terraria.Player.MountedCenter, Terraria.Projectile.netUpdate, Terraria.PopupText.NewText(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.notTheBeesWorld, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.Player.RotatedRelativePoint(), Terraria.Item.SetDefaults(), Terraria.Player.sonarPotion, Terraria.AdvancedPopupRequest.Text, Terraria.Projectile.type, Terraria.Entity.wet, and Terraria.Main.worldSurface.