TModLoader: Terraria.Player.HealEffect
HealEffect()
void Terraria.Player.HealEffect (int healAmount, bool broadcast = true) inline
Spawns a T:Terraria.CombatText indicating the player healed healAmount life and syncs it if broadcast is true.
Note that this doesn't actually heal the player, it only spawns the floating text. The M:Terraria.Player.Heal(System.Int32) method heals the player and calls this method and is more commonly used.
Definition at line 4980 of file Player.cs.
    {
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.HealLife, healAmount);
        if (broadcast && Main.netMode == 1 && whoAmI == Main.myPlayer)
        {
            NetMessage.SendData(35, -1, -1, null, whoAmI, healAmount);
        }
    }
References Terraria.CombatText.HealLife, Terraria.Entity.height, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.CombatText.NewText(), Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.ApplyLifeAndOrMana(), Terraria.Player.Heal(), and Terraria.Player.UseHealthMaxIncreasingItem().