TModLoader: Terraria.Player.SmartSelectLookup
SmartSelectLookup()
void Terraria.Player.SmartSelectLookup () inline
Definition at line 15778 of file Player.cs.
    {
        if (selectedItem == 58)
        {
            return;
        }
        if (mouseInterface)
        {
            controlTorch = false;
        }
        if (controlTorch && itemAnimation == 0)
        {
            PlayerInput.smartSelectPointer.SmartSelectLookup_GetTargetTile(this, out var tX, out var tY);
            SmartSelect_GetToolStrategy(tX, tY, out var toolStrategy, out var wetTile);
            if (PlayerInput.UsingGamepad && _lastSmartCursorToolStrategy != -1)
            {
                toolStrategy = _lastSmartCursorToolStrategy;
            }
            if (toolStrategy == 0 || toolStrategy == 4)
            {
                float num3 = Math.Abs((float)Main.mouseX + Main.screenPosition.X - (position.X + (float)(width / 2)));
                float num2 = Math.Abs((float)Main.mouseY + Main.screenPosition.Y - (position.Y + (float)(height / 2))) * 1.3f;
                if ((float)Math.Sqrt(num3 * num3 + num2 * num2) > 200f)
                {
                    toolStrategy = 5;
                }
            }
            int modSelect = TileLoader.AutoSelect(tX, tY, this);
            if (modSelect >= 0)
            {
                SmartSelect_SelectItem(modSelect);
                return;
            }
            SmartSelect_PickToolForStrategy(tX, tY, toolStrategy, wetTile);
            _lastSmartCursorToolStrategy = toolStrategy;
        }
        else if (itemAnimation == 0 && DpadRadial.SelectedItem != -1 && inventory[DpadRadial.SelectedItem].stack > 0)
        {
            if (nonTorch == -1)
            {
                nonTorch = selectedItem;
            }
            selectedItem = DpadRadial.SelectedItem;
            _lastSmartCursorToolStrategy = -1;
        }
        else if (itemAnimation == 0 && CircularRadial.SelectedItem != -1 && inventory[CircularRadial.SelectedItem].stack > 0)
        {
            if (nonTorch == -1)
            {
                nonTorch = selectedItem;
            }
            selectedItem = CircularRadial.SelectedItem;
            _lastSmartCursorToolStrategy = -1;
        }
        else if (nonTorch > -1 && itemAnimation == 0)
        {
            selectedItem = nonTorch;
            nonTorch = -1;
            _lastSmartCursorToolStrategy = -1;
        }
    }
References Terraria.Player._lastSmartCursorToolStrategy, Terraria.ModLoader.TileLoader.AutoSelect(), Terraria.Player.CircularRadial, Terraria.Player.controlTorch, Terraria.Player.DpadRadial, Terraria.Entity.height, Terraria.Player.inventory, Terraria.Player.itemAnimation, Terraria.Player.mouseInterface, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Player.nonTorch, Terraria.Entity.position, Terraria.Main.screenPosition, Terraria.Player.SelectionRadial.SelectedItem, Terraria.Player.selectedItem, Terraria.Player.SmartSelect_GetToolStrategy(), Terraria.Player.SmartSelect_PickToolForStrategy(), Terraria.Player.SmartSelect_SelectItem(), Terraria.GameInput.PlayerInput.smartSelectPointer, Terraria.Item.stack, Terraria.GameInput.PlayerInput.UsingGamepad, and Terraria.Entity.width.
Referenced by Terraria.Player.ItemCheck_Inner().