TModLoader: Terraria.Player.Hurt
Hurt() [4/4]
double Terraria.Player.Hurt (PlayerDeathReason damageSource, int Damage, int hitDirection, out HurtInfo info, bool pvp = false, bool quiet = false, int cooldownCounter = -1, bool dodgeable = true, float armorPenetration = 0f, float scalingArmorPenetration = 0f, float knockback = 4::5f) inline
Definition at line 37009 of file Player.cs.
    {
        info = default(HurtInfo);
        if (shimmering && AllowShimmerDodge(damageSource, cooldownCounter, dodgeable))
        {
            return 0.0;
        }
        if (creativeGodMode)
        {
            return 0.0;
        }
        if (PlayerLoader.ImmuneTo(this, damageSource, cooldownCounter, dodgeable))
        {
            return 0.0;
        }
        bool flag = !immune;
        bool flag2 = false;
        switch (cooldownCounter)
        {
        case 0:
        case 1:
        case 3:
        case 4:
            flag = hurtCooldowns[cooldownCounter] <= 0;
            break;
        case 2:
            flag2 = true;
            cooldownCounter = -1;
            break;
        }
        if (flag)
        {
            HurtModifiers hurtModifiers = new HurtModifiers();
            hurtModifiers.DamageSource = damageSource;
            hurtModifiers.PvP = pvp;
            hurtModifiers.CooldownCounter = cooldownCounter;
            hurtModifiers.Dodgeable = dodgeable;
            hurtModifiers.HitDirection = hitDirection;
            HurtModifiers modifiers = hurtModifiers;
            PlayerLoader.ModifyHurt(this, ref modifiers);
            modifiers.ArmorPenetration += armorPenetration;
            modifiers.ScalingArmorPenetration += scalingArmorPenetration;
            if (flag2)
            {
                modifiers.Knockback.Base += 6f;
                modifiers.KnockbackImmunityEffectiveness *= 0.8f;
            }
            ApplyVanillaHurtEffectModifiers(ref modifiers);
            info = modifiers.ToHurtInfo(Damage, statDefense, pvp ? 0.5f : DefenseEffectiveness.Value, knockback, noKnockback);
            if (dodgeable)
            {
                if (whoAmI == Main.myPlayer && PlayerLoader.FreeDodge(this, in info))
                {
                    return 0.0;
                }
                if (whoAmI == Main.myPlayer && blackBelt && Main.rand.Next(10) == 0)
                {
                    NinjaDodge();
                    return 0.0;
                }
                if (whoAmI == Main.myPlayer && brainOfConfusionItem != null && !brainOfConfusionItem.IsAir && Main.rand.Next(6) == 0 && FindBuffIndex(321) == -1)
                {
                    BrainOfConfusionDodge();
                    return 0.0;
                }
                if (whoAmI == Main.myPlayer && shadowDodge)
                {
                    ShadowDodge();
                    return 0.0;
                }
                if (whoAmI == Main.myPlayer && PlayerLoader.ConsumableDodge(this, in info))
                {
                    return 0.0;
                }
            }
            Hurt(info, quiet);
            return info.Damage;
        }
        return 0.0;
    }
References Terraria.Player.AllowShimmerDodge(), Terraria.Player.ApplyVanillaHurtEffectModifiers(), Terraria.Player.armorPenetration, Terraria.Player.blackBelt, Terraria.Player.BrainOfConfusionDodge(), Terraria.Player.brainOfConfusionItem, Terraria.ModLoader.PlayerLoader.ConsumableDodge(), Terraria.Player.creativeGodMode, Terraria.GameContent.Damage, Terraria.Player.DefenseEffectiveness, Terraria.Player.FindBuffIndex(), Terraria.ModLoader.PlayerLoader.FreeDodge(), Terraria.Player.Hurt(), Terraria.Player.hurtCooldowns, Terraria.Player.immune, Terraria.ModLoader.PlayerLoader.ImmuneTo(), Terraria.Item.IsAir, Terraria.ModLoader.PlayerLoader.ModifyHurt(), Terraria.Main.myPlayer, Terraria.Player.NinjaDodge(), Terraria.Player.noKnockback, Terraria.Main.rand, Terraria.Player.shadowDodge, Terraria.Player.ShadowDodge(), Terraria.Player.shimmering, Terraria.Player.statDefense, Terraria.ModLoader.MultipliableFloat.Value, and Terraria.Entity.whoAmI.