TModLoader: Terraria.Player.FindSharpTearsSpot
FindSharpTearsSpot()
Point Terraria.Player.FindSharpTearsSpot (Vector2 targetSpot) inline private
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0107: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        Point point = targetSpot.ToTileCoordinates();
        Vector2 center = base.Center;
        Vector2 endPoint = targetSpot;
        int samplesToTake = 3;
        float samplingWidth = 4f;
        Collision.AimingLaserScan(center, endPoint, samplingWidth, samplesToTake, out var vectorTowardsTarget, out var samples);
        float num = float.PositiveInfinity;
        for (int i = 0; i < samples.Length; i++)
        {
            if (samples[i] < num)
            {
                num = samples[i];
            }
        }
        targetSpot = center + vectorTowardsTarget.SafeNormalize(Vector2.Zero) * num;
        point = targetSpot.ToTileCoordinates();
        Rectangle value = default(Rectangle);
        ((Rectangle)(ref value))._002Ector(point.X, point.Y, 1, 1);
        ((Rectangle)(ref value)).Inflate(6, 16);
        Rectangle value2 = default(Rectangle);
        ((Rectangle)(ref value2))._002Ector(0, 0, Main.maxTilesX, Main.maxTilesY);
        ((Rectangle)(ref value2)).Inflate(-40, -40);
        value = Rectangle.Intersect(value, value2);
        List<Point> list = new List<Point>();
        List<Point> list2 = new List<Point>();
        Vector2 value3 = default(Vector2);
        for (int j = ((Rectangle)(ref value)).Left; j <= ((Rectangle)(ref value)).Right; j++)
        {
            for (int k = ((Rectangle)(ref value)).Top; k <= ((Rectangle)(ref value)).Bottom; k++)
            {
                if (!WorldGen.SolidTile2(j, k))
                {
                    continue;
                }
                ((Vector2)(ref value3))._002Ector((float)(j * 16 + 8), (float)(k * 16 + 8));
                if (!(Vector2.Distance(targetSpot, value3) > 200f))
                {
                    if (FindSharpTearsOpening(j, k, j > point.X, j < point.X, k > point.Y, k < point.Y))
                    {
                        list.Add(new Point(j, k));
                    }
                    else
                    {
                        list2.Add(new Point(j, k));
                    }
                }
            }
        }
        if (list.Count == 0 && list2.Count == 0)
        {
            list.Add((base.Center.ToTileCoordinates().ToVector2() + Main.rand.NextVector2Square(-2f, 2f)).ToPoint());
        }
        List<Point> list3 = list;
        if (list3.Count == 0)
        {
            list3 = list2;
        }
        int index = Main.rand.Next(list3.Count);
        return list3[index];
    }
References Terraria.Collision.AimingLaserScan(), Terraria.Entity.Bottom, Terraria.Player.FindSharpTearsOpening(), Terraria.Entity.Left, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Entity.Right, and Terraria.WorldGen.SolidTile2().
Referenced by Terraria.Player.ItemCheck_Shoot().