TModLoader: Terraria.Player.ResetVisibleAccessories
ResetVisibleAccessories()
void Terraria.Player.ResetVisibleAccessories () inline
    {
        handon = -1;
        handoff = -1;
        back = -1;
        front = -1;
        shoe = -1;
        waist = -1;
        shield = -1;
        neck = -1;
        face = -1;
        balloon = -1;
        backpack = -1;
        tail = -1;
        faceHead = -1;
        faceFlower = -1;
        balloonFront = -1;
        beard = -1;
    }
References Terraria.Player.back, Terraria.Player.backpack, Terraria.Player.balloon, Terraria.Player.balloonFront, Terraria.Player.beard, Terraria.Player.face, Terraria.Player.faceFlower, Terraria.Player.faceHead, Terraria.Player.front, Terraria.Player.handoff, Terraria.Player.handon, Terraria.Player.neck, Terraria.Player.shield, Terraria.Player.shoe, Terraria.Player.tail, and Terraria.Player.waist.
Referenced by Terraria.GameContent.Animations.Segments.PlayerSegment.Draw(), Terraria.GameContent.UI.Elements.UICharacter.Update(), Terraria.Player.Update(), and Terraria.Player.UpdateDead().