TModLoader: Terraria.Player.Update
Update()
void Terraria.Player.Update (int i) inline
    {
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_6c9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_6a5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_6df4: Unknown result type (might be due to invalid IL or missing references)
        //IL_6e52: Unknown result type (might be due to invalid IL or missing references)
        //IL_7927: Unknown result type (might be due to invalid IL or missing references)
        //IL_7946: Unknown result type (might be due to invalid IL or missing references)
        //IL_794c: Unknown result type (might be due to invalid IL or missing references)
        //IL_755b: Unknown result type (might be due to invalid IL or missing references)
        //IL_757d: Unknown result type (might be due to invalid IL or missing references)
        //IL_7583: Unknown result type (might be due to invalid IL or missing references)
        //IL_73a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_73c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_73c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0657: Unknown result type (might be due to invalid IL or missing references)
        //IL_067b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0681: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_7819: Unknown result type (might be due to invalid IL or missing references)
        //IL_783b: Unknown result type (might be due to invalid IL or missing references)
        //IL_7841: Unknown result type (might be due to invalid IL or missing references)
        //IL_7711: Unknown result type (might be due to invalid IL or missing references)
        //IL_7733: Unknown result type (might be due to invalid IL or missing references)
        //IL_7739: Unknown result type (might be due to invalid IL or missing references)
        //IL_7620: Unknown result type (might be due to invalid IL or missing references)
        //IL_7625: Unknown result type (might be due to invalid IL or missing references)
        //IL_7643: Unknown result type (might be due to invalid IL or missing references)
        //IL_7648: Unknown result type (might be due to invalid IL or missing references)
        //IL_7666: Unknown result type (might be due to invalid IL or missing references)
        //IL_766b: Unknown result type (might be due to invalid IL or missing references)
        //IL_6fcf: Unknown result type (might be due to invalid IL or missing references)
        //IL_6ff1: Unknown result type (might be due to invalid IL or missing references)
        //IL_6ff7: Unknown result type (might be due to invalid IL or missing references)
        //IL_7689: Unknown result type (might be due to invalid IL or missing references)
        //IL_768e: Unknown result type (might be due to invalid IL or missing references)
        //IL_7293: Unknown result type (might be due to invalid IL or missing references)
        //IL_72b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_72bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_7185: Unknown result type (might be due to invalid IL or missing references)
        //IL_71a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_71ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_7094: Unknown result type (might be due to invalid IL or missing references)
        //IL_7099: Unknown result type (might be due to invalid IL or missing references)
        //IL_70b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_70bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_70da: Unknown result type (might be due to invalid IL or missing references)
        //IL_70df: Unknown result type (might be due to invalid IL or missing references)
        //IL_70fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_7102: Unknown result type (might be due to invalid IL or missing references)
        //IL_7e19: Unknown result type (might be due to invalid IL or missing references)
        //IL_7e1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_7e65: Unknown result type (might be due to invalid IL or missing references)
        //IL_7e6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_8208: Unknown result type (might be due to invalid IL or missing references)
        //IL_820d: Unknown result type (might be due to invalid IL or missing references)
        //IL_822f: Unknown result type (might be due to invalid IL or missing references)
        //IL_7fad: Unknown result type (might be due to invalid IL or missing references)
        //IL_7fb4: Unknown result type (might be due to invalid IL or missing references)
        //IL_7fb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_7fca: Unknown result type (might be due to invalid IL or missing references)
        //IL_7fcf: Unknown result type (might be due to invalid IL or missing references)
        //IL_8274: Unknown result type (might be due to invalid IL or missing references)
        //IL_827a: Unknown result type (might be due to invalid IL or missing references)
        //IL_827f: Unknown result type (might be due to invalid IL or missing references)
        //IL_8284: Unknown result type (might be due to invalid IL or missing references)
        //IL_8032: Unknown result type (might be due to invalid IL or missing references)
        //IL_8038: Unknown result type (might be due to invalid IL or missing references)
        //IL_803d: Unknown result type (might be due to invalid IL or missing references)
        //IL_8080: Unknown result type (might be due to invalid IL or missing references)
        //IL_8085: Unknown result type (might be due to invalid IL or missing references)
        //IL_8151: Unknown result type (might be due to invalid IL or missing references)
        //IL_8158: Unknown result type (might be due to invalid IL or missing references)
        //IL_815d: Unknown result type (might be due to invalid IL or missing references)
        //IL_80a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1987: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e28: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e35: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e41: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e46: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e65: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e80: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e90: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e95: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ea0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ead: Unknown result type (might be due to invalid IL or missing references)
        //IL_2eb3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2eb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ebf: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ec4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1767: Unknown result type (might be due to invalid IL or missing references)
        //IL_1786: Unknown result type (might be due to invalid IL or missing references)
        //IL_178c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ef9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f07: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f14: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f19: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f20: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f25: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f44: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f66: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f70: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f76: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f83: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f89: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f95: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_849f: Unknown result type (might be due to invalid IL or missing references)
        //IL_8489: Unknown result type (might be due to invalid IL or missing references)
        //IL_843b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3159: Unknown result type (might be due to invalid IL or missing references)
        //IL_84b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_84ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_8139: Unknown result type (might be due to invalid IL or missing references)
        //IL_83a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_83aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_83cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_8343: Unknown result type (might be due to invalid IL or missing references)
        //IL_8348: Unknown result type (might be due to invalid IL or missing references)
        //IL_836a: Unknown result type (might be due to invalid IL or missing references)
        //IL_8582: Unknown result type (might be due to invalid IL or missing references)
        //IL_8594: Unknown result type (might be due to invalid IL or missing references)
        //IL_1377: Unknown result type (might be due to invalid IL or missing references)
        //IL_137c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1380: Unknown result type (might be due to invalid IL or missing references)
        //IL_1385: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_14dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_39ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_39fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_359b: Unknown result type (might be due to invalid IL or missing references)
        //IL_35f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b74: Unknown result type (might be due to invalid IL or missing references)
        //IL_64b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_64cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_64da: Unknown result type (might be due to invalid IL or missing references)
        //IL_64df: Unknown result type (might be due to invalid IL or missing references)
        //IL_64e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_64ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_3d76: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ba8: Unknown result type (might be due to invalid IL or missing references)
        //IL_3dc3: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c44: Unknown result type (might be due to invalid IL or missing references)
        //IL_3e5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_66cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_67de: Unknown result type (might be due to invalid IL or missing references)
        //IL_67e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_67e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_37af: Unknown result type (might be due to invalid IL or missing references)
        //IL_460a: Unknown result type (might be due to invalid IL or missing references)
        //IL_4782: Unknown result type (might be due to invalid IL or missing references)
        //IL_473c: Unknown result type (might be due to invalid IL or missing references)
        //IL_483c: Unknown result type (might be due to invalid IL or missing references)
        //IL_47f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_4c56: Unknown result type (might be due to invalid IL or missing references)
        //IL_4dae: Unknown result type (might be due to invalid IL or missing references)
        //IL_4dea: Unknown result type (might be due to invalid IL or missing references)
        //IL_533d: Unknown result type (might be due to invalid IL or missing references)
        //IL_5356: Unknown result type (might be due to invalid IL or missing references)
        //IL_535c: Unknown result type (might be due to invalid IL or missing references)
        //IL_53a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_53ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_53b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_543f: Unknown result type (might be due to invalid IL or missing references)
        //IL_545b: Unknown result type (might be due to invalid IL or missing references)
        //IL_5461: Unknown result type (might be due to invalid IL or missing references)
        //IL_54b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_54bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_54c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_556a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5585: Unknown result type (might be due to invalid IL or missing references)
        //IL_558b: Unknown result type (might be due to invalid IL or missing references)
        //IL_55b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_55ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_55bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_5652: Unknown result type (might be due to invalid IL or missing references)
        //IL_566a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5670: Unknown result type (might be due to invalid IL or missing references)
        //IL_5695: Unknown result type (might be due to invalid IL or missing references)
        //IL_569f: Unknown result type (might be due to invalid IL or missing references)
        //IL_56a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_5757: Unknown result type (might be due to invalid IL or missing references)
        //IL_5773: Unknown result type (might be due to invalid IL or missing references)
        //IL_5779: Unknown result type (might be due to invalid IL or missing references)
        //IL_579f: Unknown result type (might be due to invalid IL or missing references)
        //IL_57a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_57ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_5826: Unknown result type (might be due to invalid IL or missing references)
        //IL_5846: Unknown result type (might be due to invalid IL or missing references)
        //IL_584c: Unknown result type (might be due to invalid IL or missing references)
        //IL_5863: Unknown result type (might be due to invalid IL or missing references)
        //IL_586d: Unknown result type (might be due to invalid IL or missing references)
        //IL_5872: Unknown result type (might be due to invalid IL or missing references)
        //IL_58d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_59b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_59cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_59d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dc6: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dcb: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dda: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ddf: Unknown result type (might be due to invalid IL or missing references)
        //IL_5bf5: Unknown result type (might be due to invalid IL or missing references)
        //IL_5c15: Unknown result type (might be due to invalid IL or missing references)
        //IL_5c1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_5c4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_5c58: Unknown result type (might be due to invalid IL or missing references)
        //IL_5c5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_5c6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_5c71: Unknown result type (might be due to invalid IL or missing references)
        //IL_5c76: Unknown result type (might be due to invalid IL or missing references)
        //IL_5c7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e15: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e51: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e84: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e93: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ea1: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ea7: Unknown result type (might be due to invalid IL or missing references)
        //IL_5eac: Unknown result type (might be due to invalid IL or missing references)
        //IL_5eb1: Unknown result type (might be due to invalid IL or missing references)
        //IL_5eed: Unknown result type (might be due to invalid IL or missing references)
        //IL_5eef: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d02: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d24: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d67: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d80: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d85: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f58: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f93: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f99: Unknown result type (might be due to invalid IL or missing references)
        //IL_5fcc: Unknown result type (might be due to invalid IL or missing references)
        //IL_5fd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_5fdb: Unknown result type (might be due to invalid IL or missing references)
        //IL_5fe9: Unknown result type (might be due to invalid IL or missing references)
        //IL_5fef: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ff4: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ff9: Unknown result type (might be due to invalid IL or missing references)
        //IL_6035: Unknown result type (might be due to invalid IL or missing references)
        //IL_6037: Unknown result type (might be due to invalid IL or missing references)
        using (new Main.CurrentPlayerOverride(this))
        {
            if (i == Main.myPlayer && Main.netMode != 2)
            {
                LockOnHelper.Update();
            }
            if (i == Main.myPlayer && Main.dontStarveWorld)
            {
                DontStarveDarknessDamageDealer.Update(this);
            }
            maxFallSpeed = 10f;
            gravity = defaultGravity;
            jumpHeight = 15;
            jumpSpeed = 5.01f;
            maxRunSpeed = 3f;
            runAcceleration = 0.08f;
            runSlowdown = 0.2f;
            accRunSpeed = maxRunSpeed;
            if (!mount.Active || !mount.Cart)
            {
                onWrongGround = false;
            }
            heldProj = -1;
            instantMovementAccumulatedThisFrame = Vector2.Zero;
            if (PortalPhysicsEnabled)
            {
                maxFallSpeed = 35f;
            }
            if (shimmerWet || shimmering)
            {
                if (shimmering)
                {
                    gravity *= 0.9f;
                    maxFallSpeed *= 0.9f;
                }
                else
                {
                    gravity = 0.15f;
                    jumpHeight = 23;
                    jumpSpeed = 5.51f;
                }
            }
            else if (wet)
            {
                if (honeyWet)
                {
                    gravity = 0.1f;
                    maxFallSpeed = 3f;
                }
                else if (merman)
                {
                    gravity = 0.3f;
                    maxFallSpeed = 7f;
                }
                else if (trident && !lavaWet)
                {
                    gravity = 0.25f;
                    maxFallSpeed = 6f;
                    jumpHeight = 25;
                    jumpSpeed = 5.51f;
                    if (controlUp)
                    {
                        gravity = 0.1f;
                        maxFallSpeed = 2f;
                    }
                }
                else
                {
                    gravity = 0.2f;
                    maxFallSpeed = 5f;
                    jumpHeight = 30;
                    jumpSpeed = 6.01f;
                }
            }
            if (vortexDebuff)
            {
                gravity = 0f;
            }
            maxFallSpeed += 0.01f;
            bool flag = false;
            if (Main.myPlayer == i)
            {
                if (Main.mapFullscreen)
                {
                    GamepadEnableGrappleCooldown();
                }
                else if (_quickGrappleCooldown > 0)
                {
                    _quickGrappleCooldown--;
                }
                TileObject.objectPreview.Reset();
                if (DD2Event.DownedInvasionAnyDifficulty)
                {
                    downedDD2EventAnyDifficulty = true;
                }
                autoReuseAllWeapons = Main.SettingsEnabled_AutoReuseAllItems;
            }
            if (NPC.freeCake && talkNPC >= 0 && Main.npc[talkNPC].type == 208)
            {
                NPC.freeCake = false;
                if (Main.netMode != 1)
                {
                    Item.NewItem(new EntitySource_Gift(Main.npc[talkNPC]), (int)position.X, (int)position.Y, width, height, 3750);
                }
            }
            if (emoteTime > 0)
            {
                emoteTime--;
            }
            if (ghostDmg > 0f)
            {
                ghostDmg -= 6.6666665f;
            }
            if (ghostDmg < 0f)
            {
                ghostDmg = 0f;
            }
            if (Main.expertMode)
            {
                if (lifeSteal < 70f)
                {
                    lifeSteal += 0.5f;
                }
                if (lifeSteal > 70f)
                {
                    lifeSteal = 70f;
                }
            }
            else
            {
                if (lifeSteal < 80f)
                {
                    lifeSteal += 0.6f;
                }
                if (lifeSteal > 80f)
                {
                    lifeSteal = 80f;
                }
            }
            ResizeHitbox();
            if (mount.Active && mount.Type == 0)
            {
                int num111 = (int)(position.X + (float)(width / 2)) / 16;
                int j = (int)(position.Y + (float)(height / 2) - 14f) / 16;
                Lighting.AddLight(num111, j, 0.5f, 0.2f, 0.05f);
                Lighting.AddLight(num111 + direction, j, 0.5f, 0.2f, 0.05f);
                Lighting.AddLight(num111 + direction * 2, j, 0.5f, 0.2f, 0.05f);
            }
            outOfRange = false;
            if (whoAmI != Main.myPlayer)
            {
                int num27 = (int)(position.X + (float)(width / 2)) / 16;
                int num37 = (int)(position.Y + (float)(height / 2)) / 16;
                if (Main.netMode == 1 && !Main.sectionManager.TilesLoaded(num27 - 3, num37 - 3, num27 + 3, num37 + 3))
                {
                    flag = true;
                }
                if (flag)
                {
                    outOfRange = true;
                    numMinions = 0;
                    slotsMinions = 0f;
                    itemAnimation = 0;
                    UpdateBuffs(i);
                    PlayerFrame();
                }
            }
            if (tankPet >= 0)
            {
                if (!tankPetReset)
                {
                    tankPetReset = true;
                }
                else
                {
                    tankPet = -1;
                }
            }
            if (i == Main.myPlayer)
            {
                IsVoidVaultEnabled = HasItem(4131);
            }
            if (chatOverhead.timeLeft > 0)
            {
                chatOverhead.timeLeft--;
            }
            if (snowBallLauncherInteractionCooldown > 0)
            {
                snowBallLauncherInteractionCooldown--;
            }
            environmentBuffImmunityTimer = Math.Max(0, environmentBuffImmunityTimer - 1);
            if (flag)
            {
                return;
            }
            UpdateHairDyeDust();
            UpdateMiscCounter();
            PlayerLoader.PreUpdate(this);
            infernoCounter++;
            if (infernoCounter >= 180)
            {
                infernoCounter = 0;
            }
            timeSinceLastDashStarted++;
            if (timeSinceLastDashStarted >= 300)
            {
                timeSinceLastDashStarted = 300;
            }
            _framesLeftEligibleForDeadmansChestDeathAchievement--;
            if (_framesLeftEligibleForDeadmansChestDeathAchievement < 0)
            {
                _framesLeftEligibleForDeadmansChestDeathAchievement = 0;
            }
            if (titaniumStormCooldown > 0)
            {
                titaniumStormCooldown--;
            }
            if (starCloakCooldown > 0)
            {
                starCloakCooldown--;
                if (Main.rand.Next(5) == 0)
                {
                    for (int k = 0; k < 2; k++)
                    {
                        Dust dust = Dust.NewDustDirect(position, width, height, 45, 0f, 0f, 255, default(Color), (float)Main.rand.Next(20, 26) * 0.1f);
                        dust.noLight = true;
                        dust.noGravity = true;
                        dust.velocity *= 0.5f;
                        dust.velocity.X = 0f;
                        dust.velocity.Y -= 0.5f;
                    }
                }
                if (starCloakCooldown == 0)
                {
                    SoundEngine.PlaySound(25);
                }
            }
            _timeSinceLastImmuneGet++;
            if (_timeSinceLastImmuneGet >= 10000)
            {
                _timeSinceLastImmuneGet = 10000;
            }
            float num47 = (float)Main.maxTilesX / 4200f;
            num47 *= num47;
            float num58 = (float)((double)(position.Y / 16f - (60f + 10f * num47)) / (Main.worldSurface / 6.0));
            if (Main.remixWorld)
            {
                num58 = (float)((double)(position.Y / 16f - (60f + 10f * num47)) / (Main.worldSurface / 1.0));
            }
            if (Main.remixWorld)
            {
                if ((double)num58 < 0.1)
                {
                    num58 = 0.1f;
                }
            }
            else if ((double)num58 < 0.25)
            {
                num58 = 0.25f;
            }
            if (num58 > 1f)
            {
                num58 = 1f;
            }
            gravity *= num58;
            maxRegenDelay = (1f - (float)statMana / (float)statManaMax2) * 60f * 4f + 45f;
            maxRegenDelay *= 0.7f;
            UpdateSocialShadow();
            UpdateTeleportVisuals();
            whoAmI = i;
            if (whoAmI == Main.myPlayer)
            {
                if (!DD2Event.Ongoing)
                {
                    PurgeDD2EnergyCrystals();
                }
                TryPortalJumping();
                if (whoAmI == Main.myPlayer)
                {
                    doorHelper.Update(this);
                }
            }
            if (runSoundDelay > 0)
            {
                runSoundDelay--;
            }
            if (attackCD > 0)
            {
                attackCD--;
            }
            if (itemAnimation == 0)
            {
                attackCD = 0;
            }
            if (potionDelay > 0)
            {
                potionDelay--;
            }
            if (i == Main.myPlayer)
            {
                if (trashItem.type >= 1522 && trashItem.type <= 1527)
                {
                    trashItem.SetDefaults();
                }
                if (trashItem.type == 3643)
                {
                    trashItem.SetDefaults();
                }
                UpdateBiomes();
                UpdateMinionTarget();
            }
            if (ghost)
            {
                Ghost();
                return;
            }
            if (dead)
            {
                UpdateDead();
                ResetProjectileCaches();
                UpdateProjectileCaches(i);
                return;
            }
            TrySpawningFaelings();
            if (i == Main.myPlayer && hasLucyTheAxe)
            {
                LucyAxeMessage.TryPlayingIdleMessage();
            }
            if (velocity.Y == 0f)
            {
                mount.FatigueRecovery();
            }
            Rectangle val;
            if (i == Main.myPlayer && !isControlledByFilm)
            {
                ResetControls();
                if (Main.hasFocus)
                {
                    if (!Main.drawingPlayerChat && !Main.editSign && !Main.editChest && !Main.blockInput)
                    {
                        PlayerInput.Triggers.Current.CopyInto(this);
                        LocalInputCache = new DirectionalInputSyncCache(this);
                        if (Main.mapFullscreen)
{
                            if (controlUp)
{
                                Main.mapFullscreenPos.Y -= 1f * (16f / Main.mapFullscreenScale);
                            }
                            if (controlDown)
{
                                Main.mapFullscreenPos.Y += 1f * (16f / Main.mapFullscreenScale);
                            }
                            if (controlLeft)
{
                                Main.mapFullscreenPos.X -= 1f * (16f / Main.mapFullscreenScale);
                            }
                            if (controlRight)
{
                                Main.mapFullscreenPos.X += 1f * (16f / Main.mapFullscreenScale);
                            }
                            controlUp = false;
                            controlLeft = false;
                            controlDown = false;
                            controlRight = false;
                            controlJump = false;
                            controlUseItem = false;
                            controlUseTile = false;
                            controlThrow = false;
                            controlHook = false;
                            controlTorch = false;
                            controlSmart = false;
                            controlMount = false;
                        }
                        if (isOperatingAnotherEntity)
{
                            controlUp = (controlDown = (controlLeft = (controlRight = (controlJump = false))));
                        }
                        if (controlQuickHeal)
{
                            if (releaseQuickHeal)
{
                                QuickHeal();
                            }
                            releaseQuickHeal = false;
                        }
                        else
{
                            releaseQuickHeal = true;
                        }
                        if (controlQuickMana)
{
                            if (releaseQuickMana)
{
                                QuickMana();
                            }
                            releaseQuickMana = false;
                        }
                        else
{
                            releaseQuickMana = true;
                        }
                        if (controlCreativeMenu)
{
                            if (releaseCreativeMenu)
{
                                ToggleCreativeMenu();
                            }
                            releaseCreativeMenu = false;
                        }
                        else
{
                            releaseCreativeMenu = true;
                        }
                        if (controlLeft && controlRight)
{
                            controlLeft = false;
                            controlRight = false;
                        }
                        if (PlayerInput.UsingGamepad || !mouseInterface || !ItemSlot.Options.DisableLeftShiftTrashCan)
{
                            if (PlayerInput.SteamDeckIsUsed && PlayerInput.SettingsForUI.CurrentCursorMode == CursorMode.Mouse)
{
                                TryToToggleSmartCursor(ref Main.SmartCursorWanted_Mouse);
                            }
                            else if (PlayerInput.UsingGamepad)
{
                                TryToToggleSmartCursor(ref Main.SmartCursorWanted_GamePad);
                            }
                            else
{
                                TryToToggleSmartCursor(ref Main.SmartCursorWanted_Mouse);
                            }
                        }
                        if (controlSmart)
{
                            releaseSmart = false;
                        }
                        else
{
                            releaseSmart = true;
                        }
                        if (controlMount)
{
                            if (releaseMount)
{
                                QuickMount();
                            }
                            releaseMount = false;
                        }
                        else
{
                            releaseMount = true;
                        }
                        if (Main.mapFullscreen)
{
                            if (mapZoomIn)
{
                                Main.mapFullscreenScale *= 1.05f;
                            }
                            if (mapZoomOut)
{
                                Main.mapFullscreenScale *= 0.95f;
                            }
                        }
                        else
{
                            if (Main.mapStyle == 1)
{
                                if (mapZoomIn)
{
                                    Main.mapMinimapScale *= 1.025f;
                                }
                                if (mapZoomOut)
{
                                    Main.mapMinimapScale *= 0.975f;
                                }
                                if (mapAlphaUp)
{
                                    Main.mapMinimapAlpha += 0.015f;
                                }
                                if (mapAlphaDown)
{
                                    Main.mapMinimapAlpha -= 0.015f;
                                }
                            }
                            else if (Main.mapStyle == 2)
{
                                if (mapZoomIn)
{
                                    Main.mapOverlayScale *= 1.05f;
                                }
                                if (mapZoomOut)
{
                                    Main.mapOverlayScale *= 0.95f;
                                }
                                if (mapAlphaUp)
{
                                    Main.mapOverlayAlpha += 0.015f;
                                }
                                if (mapAlphaDown)
{
                                    Main.mapOverlayAlpha -= 0.015f;
                                }
                            }
                            if (mapStyle)
{
                                if (releaseMapStyle)
{
                                    SoundEngine.PlaySound(12);
                                    Main.mapStyle++;
                                    if (Main.mapStyle > 2)
{
                                        Main.mapStyle = 0;
                                    }
                                }
                                releaseMapStyle = false;
                            }
                            else
{
                                releaseMapStyle = true;
                            }
                        }
                        if (mapFullScreen)
{
                            if (releaseMapFullscreen)
{
                                if (Main.mapFullscreen)
{
                                    SoundEngine.PlaySound(11);
                                    Main.mapFullscreen = false;
                                }
                                else
{
                                    TryOpeningFullscreenMap();
                                }
                            }
                            releaseMapFullscreen = false;
                        }
                        else
{
                            releaseMapFullscreen = true;
                        }
                    }
                    else if (!PlayerInput.UsingGamepad && !Main.editSign && !Main.editChest && !Main.blockInput)
                    {
                        PlayerInput.Triggers.Current.CopyIntoDuringChat(this);
                    }
                    if (confused)
                    {
                        bool flag12 = controlLeft;
                        bool flag23 = controlUp;
                        controlLeft = controlRight;
                        controlRight = flag12;
                        controlUp = controlRight;
                        controlDown = flag23;
                    }
                    else if (cartFlip)
                    {
                        if (controlRight || controlLeft)
{
                            bool flag25 = controlLeft;
                            controlLeft = controlRight;
                            controlRight = flag25;
                        }
                        else
{
                            cartFlip = false;
                        }
                    }
                    for (int l = 0; l < doubleTapCardinalTimer.Length; l++)
                    {
                        doubleTapCardinalTimer[l]--;
                        if (doubleTapCardinalTimer[l] < 0)
{
                            doubleTapCardinalTimer[l] = 0;
                        }
                    }
                    for (int m = 0; m < 4; m++)
                    {
                        bool flag26 = false;
                        bool flag27 = false;
                        switch (m)
{
                        case 0:
                            flag26 = controlDown && releaseDown;
                            flag27 = controlDown;
                            break;
                        case 1:
                            flag26 = controlUp && releaseUp;
                            flag27 = controlUp;
                            break;
                        case 2:
                            flag26 = controlRight && releaseRight;
                            flag27 = controlRight;
                            break;
                        case 3:
                            flag26 = controlLeft && releaseLeft;
                            flag27 = controlLeft;
                            break;
                        }
                        if (flag26)
{
                            if (doubleTapCardinalTimer[m] > 0)
{
                                KeyDoubleTap(m);
                            }
                            else
{
                                doubleTapCardinalTimer[m] = 15;
                            }
                        }
                        if (flag27)
{
                            holdDownCardinalTimer[m]++;
                            KeyHoldDown(m, holdDownCardinalTimer[m]);
                        }
                        else
{
                            holdDownCardinalTimer[m] = 0;
                        }
                    }
                    controlDownHold = holdDownCardinalTimer[0] >= 45;
                    PlayerLoader.SetControls(this);
                    if (controlInv)
                    {
                        if (releaseInventory)
{
                            ToggleInv();
                        }
                        releaseInventory = false;
                    }
                    else
                    {
                        releaseInventory = true;
                    }
                    if (delayUseItem)
                    {
                        if (!controlUseItem)
{
                            delayUseItem = false;
                        }
                        controlUseItem = false;
                    }
                    if (itemAnimation == 0 && ItemTimeIsZero && reuseDelay == 0)
                    {
                        dropItemCheck();
                        int num69 = selectedItem;
                        bool flag28 = false;
                        if (!Main.drawingPlayerChat && selectedItem != 58 && !Main.editSign && !Main.editChest)
{
                            if (PlayerInput.Triggers.Current.Hotbar1)
{
                                selectedItem = 0;
                                flag28 = true;
                            }
                            if (PlayerInput.Triggers.Current.Hotbar2)
{
                                selectedItem = 1;
                                flag28 = true;
                            }
                            if (PlayerInput.Triggers.Current.Hotbar3)
{
                                selectedItem = 2;
                                flag28 = true;
                            }
                            if (PlayerInput.Triggers.Current.Hotbar4)
{
                                selectedItem = 3;
                                flag28 = true;
                            }
                            if (PlayerInput.Triggers.Current.Hotbar5)
{
                                selectedItem = 4;
                                flag28 = true;
                            }
                            if (PlayerInput.Triggers.Current.Hotbar6)
{
                                selectedItem = 5;
                                flag28 = true;
                            }
                            if (PlayerInput.Triggers.Current.Hotbar7)
{
                                selectedItem = 6;
                                flag28 = true;
                            }
                            if (PlayerInput.Triggers.Current.Hotbar8)
{
                                selectedItem = 7;
                                flag28 = true;
                            }
                            if (PlayerInput.Triggers.Current.Hotbar9)
{
                                selectedItem = 8;
                                flag28 = true;
                            }
                            if (PlayerInput.Triggers.Current.Hotbar10)
{
                                selectedItem = 9;
                                flag28 = true;
                            }
                            int selectedBinding = DpadRadial.SelectedBinding;
                            int selectedBinding2 = CircularRadial.SelectedBinding;
                            _ = QuicksRadial.SelectedBinding;
                            DpadRadial.Update();
                            CircularRadial.Update();
                            QuicksRadial.Update();
                            if (CircularRadial.SelectedBinding >= 0 && selectedBinding2 != CircularRadial.SelectedBinding)
{
                                DpadRadial.ChangeSelection(-1);
                            }
                            if (DpadRadial.SelectedBinding >= 0 && selectedBinding != DpadRadial.SelectedBinding)
{
                                CircularRadial.ChangeSelection(-1);
                            }
                            if (QuicksRadial.SelectedBinding != -1 && PlayerInput.Triggers.JustReleased.RadialQuickbar && !PlayerInput.MiscSettingsTEMP.HotbarRadialShouldBeUsed)
{
                                switch (QuicksRadial.SelectedBinding)
{
                                case 0:
                                    QuickMount();
                                    break;
                                case 1:
                                    QuickHeal();
                                    break;
                                case 2:
                                    QuickBuff();
                                    break;
                                case 3:
                                    QuickMana();
                                    break;
                                }
                            }
                            if (controlTorch || flag28)
{
                                DpadRadial.ChangeSelection(-1);
                                CircularRadial.ChangeSelection(-1);
                            }
                            if (nonTorch != -1 && flag28)
{
                                if (selectedItem != nonTorch)
{
                                    SoundEngine.PlaySound(12);
                                }
                                nonTorch = selectedItem;
                                selectedItem = num69;
                                flag28 = false;
                            }
                        }
                        bool flag29 = Main.hairWindow;
                        if (flag29)
{
                            int y = Main.screenHeight / 2 + 60;
                            val = new Rectangle(Main.screenWidth / 2 - TextureAssets.HairStyleBack.Width() / 2, y, TextureAssets.HairStyleBack.Width(), TextureAssets.HairStyleBack.Height());
                            flag29 = ((Rectangle)(ref val)).Contains(Main.MouseScreen.ToPoint());
                        }
                        if (flag28 && CaptureManager.Instance.Active)
{
                            CaptureManager.Instance.Active = false;
                        }
                        if (num69 != selectedItem)
{
                            SoundEngine.PlaySound(12);
                        }
                        if (Main.mapFullscreen)
{
                            float num80 = PlayerInput.ScrollWheelDelta / 120;
                            if (PlayerInput.UsingGamepad)
{
                                num80 += (float)(PlayerInput.Triggers.Current.HotbarPlus.ToInt() - PlayerInput.Triggers.Current.HotbarMinus.ToInt()) * 0.1f;
                            }
                            Main.mapFullscreenScale *= 1f + num80 * 0.3f;
                        }
                        else if (CaptureManager.Instance.Active)
{
                            CaptureManager.Instance.Scrolling();
                        }
                        else if (!flag29)
{
                            if (PlayerInput.MouseInModdedUI.Count <= 0)
{
                                if (!Main.playerInventory)
{
                                    HandleHotbar();
                                }
                                else
{
                                    int num90 = GetMouseScrollDelta();
                                    bool flag30 = true;
                                    if (Main.recBigList)
{
                                        int num100 = 42;
                                        int num10 = 340;
                                        int num19 = 310;
                                        PlayerInput.SetZoom_UI();
                                        int num20 = (Main.screenWidth - num19 - 280) / num100;
                                        int num21 = (Main.screenHeight - num10 - 20) / num100;
                                        val = new Rectangle(num19, num10, num20 * num100, num21 * num100);
                                        if (((Rectangle)(ref val)).Contains(Main.MouseScreen.ToPoint()))
{
                                            num90 *= -1;
                                            int num22 = Math.Sign(num90);
                                            while (num90 != 0)
{
                                                if (num90 < 0)
{
                                                    Main.recStart -= num20;
                                                    if (Main.recStart < 0)
{
                                                        Main.recStart = 0;
                                                    }
                                                }
                                                else
{
                                                    Main.recStart += num20;
                                                    if (Main.recStart > Main.numAvailableRecipes - num20)
{
                                                        Main.recStart = Main.numAvailableRecipes - num20;
                                                    }
                                                }
                                                num90 -= num22;
                                            }
                                        }
                                        PlayerInput.SetZoom_World();
                                    }
                                    if (flag30)
{
                                        Main.focusRecipe += num90;
                                        if (Main.focusRecipe > Main.numAvailableRecipes - 1)
{
                                            Main.focusRecipe = Main.numAvailableRecipes - 1;
                                        }
                                        if (Main.focusRecipe < 0)
{
                                            Main.focusRecipe = 0;
                                        }
                                    }
                                }
                            }
                            PlayerInput.MouseInModdedUI.Clear();
                        }
                    }
                    else
                    {
                        bool flag2 = false;
                        if (!Main.drawingPlayerChat && selectedItem != 58 && !Main.editSign && !Main.editChest)
{
                            int num23 = -1;
                            if (((KeyboardState)(ref Main.keyState)).IsKeyDown((Keys)49))
{
                                num23 = 0;
                                flag2 = true;
                            }
                            if (((KeyboardState)(ref Main.keyState)).IsKeyDown((Keys)50))
{
                                num23 = 1;
                                flag2 = true;
                            }
                            if (((KeyboardState)(ref Main.keyState)).IsKeyDown((Keys)51))
{
                                num23 = 2;
                                flag2 = true;
                            }
                            if (((KeyboardState)(ref Main.keyState)).IsKeyDown((Keys)52))
{
                                num23 = 3;
                                flag2 = true;
                            }
                            if (((KeyboardState)(ref Main.keyState)).IsKeyDown((Keys)53))
{
                                num23 = 4;
                                flag2 = true;
                            }
                            if (((KeyboardState)(ref Main.keyState)).IsKeyDown((Keys)54))
{
                                num23 = 5;
                                flag2 = true;
                            }
                            if (((KeyboardState)(ref Main.keyState)).IsKeyDown((Keys)55))
{
                                num23 = 6;
                                flag2 = true;
                            }
                            if (((KeyboardState)(ref Main.keyState)).IsKeyDown((Keys)56))
{
                                num23 = 7;
                                flag2 = true;
                            }
                            if (((KeyboardState)(ref Main.keyState)).IsKeyDown((Keys)57))
{
                                num23 = 8;
                                flag2 = true;
                            }
                            if (((KeyboardState)(ref Main.keyState)).IsKeyDown((Keys)48))
{
                                num23 = 9;
                                flag2 = true;
                            }
                            if (flag2)
{
                                if (num23 != nonTorch)
{
                                    SoundEngine.PlaySound(12);
                                }
                                selectItemOnNextUse = true;
                                nonTorch = num23;
                            }
                        }
                    }
                }
                if (stoned != lastStoned)
                {
                    if (whoAmI == Main.myPlayer && stoned)
                    {
                        int damage = (int)(20.0 * (double)Main.GameModeInfo.EnemyDamageMultiplier);
                        Hurt(PlayerDeathReason.ByOther(5), damage, 0);
                    }
                    SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
                    for (int n = 0; n < 20; n++)
                    {
                        int num24 = Dust.NewDust(position, width, height, 1);
                        if (Main.rand.Next(2) == 0)
{
                            Main.dust[num24].noGravity = true;
                        }
                    }
                }
                lastStoned = stoned;
                if (frozen || webbed || stoned)
                {
                    controlJump = false;
                    controlDown = false;
                    controlLeft = false;
                    controlRight = false;
                    controlUp = false;
                    controlUseItem = false;
                    controlUseTile = false;
                    controlThrow = false;
                    gravDir = 1f;
                }
                if (!controlThrow)
                {
                    releaseThrow = true;
                }
                else
                {
                    releaseThrow = false;
                }
                if (controlDown && releaseDown)
                {
                    if (tryKeepingHoveringUp)
                    {
                        tryKeepingHoveringUp = false;
                    }
                    else
                    {
                        tryKeepingHoveringDown = true;
                    }
                }
                if (controlUp && releaseUp)
                {
                    if (tryKeepingHoveringDown)
                    {
                        tryKeepingHoveringDown = false;
                    }
                    else
                    {
                        tryKeepingHoveringUp = true;
                    }
                }
                if (velocity.Y == 0f)
                {
                    tryKeepingHoveringUp = false;
                    tryKeepingHoveringDown = false;
                }
                if (Settings.HoverControl == Settings.HoverControlMode.Hold)
                {
                    tryKeepingHoveringUp = false;
                    tryKeepingHoveringDown = false;
                }
                TrySyncingInput();
                if (Main.playerInventory)
                {
                    AdjTiles();
                }
                HandleBeingInChestRange();
                tileEntityAnchor.GetTileEntity()?.OnPlayerUpdate(this);
            }
            if (i == Main.myPlayer)
            {
                if (velocity.Y <= 0f)
                {
                    fallStart2 = (int)(position.Y / 16f);
                }
                if (velocity.Y == 0f)
                {
                    int num25 = 25;
                    num25 += extraFall;
                    int num26 = (int)(position.Y / 16f) - fallStart;
                    if (mount.CanFly())
                    {
                        num26 = 0;
                    }
                    if (mount.Cart && Minecart.OnTrack(position, width, height))
                    {
                        num26 = 0;
                    }
                    if (mount.Type == 1)
                    {
                        num26 = 0;
                    }
                    if (num26 > 0 || (gravDir == -1f && num26 < 0))
                    {
                        int num112 = (int)(position.X / 16f);
                        int num28 = (int)((position.X + (float)width) / 16f);
                        int num29 = (int)((position.Y + (float)height + 1f) / 16f);
                        if (gravDir == -1f)
{
                            num29 = (int)((position.Y - 1f) / 16f);
                        }
                        for (int num30 = num112; num30 <= num28; num30++)
{
                            if (Main.tile[num30, num29] != null && Main.tile[num30, num29].active() && (Main.tile[num30, num29].type == 189 || Main.tile[num30, num29].type == 196 || Main.tile[num30, num29].type == 460 || Main.tile[num30, num29].type == 666))
{
                                num26 = 0;
                                break;
                            }
                        }
                    }
                    bool flag3 = equippedWings != null;
                    if (stoned)
                    {
                        int num31 = (int)(((float)num26 * gravDir - 2f) * 20f);
                        if (num31 > 0)
{
                            Hurt(PlayerDeathReason.ByOther(5), num31, 0);
                            immune = false;
                        }
                    }
                    else if (((gravDir == 1f && num26 > num25) || (gravDir == -1f && num26 < -num25)) && !noFallDmg && !flag3)
                    {
                        immune = false;
                        int num32 = (int)((float)num26 * gravDir - (float)num25) * 10;
                        if (mount.Active)
{
                            num32 = (int)((float)num32 * mount.FallDamage);
                        }
                        Hurt(PlayerDeathReason.ByOther(0), num32, 0);
                        if (!dead && statLife <= statLifeMax2 / 10)
{
                            AchievementsHelper.HandleSpecialEvent(this, 8);
                        }
                    }
                    fallStart = (int)(position.Y / 16f);
                }
                if (jump > 0 || rocketDelay > 0 || wet || slowFall || (double)num58 < 0.8 || tongued)
                {
                    fallStart = (int)(position.Y / 16f);
                }
            }
            if (Main.netMode != 1)
            {
                if (chest == -1 && lastChest >= 0 && Main.chest[lastChest] != null)
                {
                    int x6 = Main.chest[lastChest].x;
                    int y2 = Main.chest[lastChest].y;
                    NPC.BigMimicSummonCheck(x6, y2, this);
                }
                if (lastChest != chest && chest >= 0 && Main.chest[chest] != null)
                {
                    int x7 = Main.chest[chest].x;
                    int y3 = Main.chest[chest].y;
                    Projectile.GasTrapCheck(x7, y3, this);
                    ItemSlot.forceClearGlowsOnChest = true;
                }
                lastChest = chest;
            }
            if (mouseInterface)
            {
                delayUseItem = true;
            }
            tileTargetX = (int)(((float)Main.mouseX + Main.screenPosition.X) / 16f);
            tileTargetY = (int)(((float)Main.mouseY + Main.screenPosition.Y) / 16f);
            if (gravDir == -1f)
            {
                tileTargetY = (int)((Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY) / 16f);
            }
            if (tileTargetX >= Main.maxTilesX - 5)
            {
                tileTargetX = Main.maxTilesX - 5;
            }
            if (tileTargetY >= Main.maxTilesY - 5)
            {
                tileTargetY = Main.maxTilesY - 5;
            }
            if (tileTargetX < 5)
            {
                tileTargetX = 5;
            }
            if (tileTargetY < 5)
            {
                tileTargetY = 5;
            }
            if (Main.tile[tileTargetX - 1, tileTargetY] == null)
            {
                Main.tile[tileTargetX - 1, tileTargetY] = default(Tile);
            }
            if (Main.tile[tileTargetX + 1, tileTargetY] == null)
            {
                Main.tile[tileTargetX + 1, tileTargetY] = default(Tile);
            }
            if (Main.tile[tileTargetX, tileTargetY] == null)
            {
                Main.tile[tileTargetX, tileTargetY] = default(Tile);
            }
            if (inventory[selectedItem].axe > 0 && !Main.tile[tileTargetX, tileTargetY].active() && inventory[selectedItem].createWall <= 0 && (inventory[selectedItem].hammer <= 0 || inventory[selectedItem].axe != 0))
            {
                if (Main.tile[tileTargetX - 1, tileTargetY].active() && Main.tile[tileTargetX - 1, tileTargetY].type == 323)
                {
                    if (Main.tile[tileTargetX - 1, tileTargetY].frameY > 4)
                    {
                        tileTargetX--;
                    }
                }
                else if (Main.tile[tileTargetX + 1, tileTargetY].active() && Main.tile[tileTargetX + 1, tileTargetY].type == 323 && Main.tile[tileTargetX + 1, tileTargetY].frameY < -4)
                {
                    tileTargetX++;
                }
            }
            if (i == Main.myPlayer)
            {
                UpdateNearbyInteractibleProjectilesList();
            }
            try
            {
                if (whoAmI == Main.myPlayer && ((Game)Main.instance).IsActive)
                {
                    SmartCursorHelper.SmartCursorLookup(this);
                    SmartInteractLookup();
                }
            }
            catch
            {
                Main.SmartCursorWanted_GamePad = false;
                Main.SmartCursorWanted_Mouse = false;
            }
            UpdateImmunity();
            if (petalTimer > 0)
            {
                petalTimer--;
            }
            if (shadowDodgeTimer > 0)
            {
                shadowDodgeTimer--;
            }
            if (boneGloveTimer > 0)
            {
                boneGloveTimer--;
            }
            if (crystalLeafCooldown > 0)
            {
                crystalLeafCooldown--;
            }
            if (jump > 0 || velocity.Y != 0f)
            {
                ResetFloorFlags();
            }
            bool flag4 = pStone;
            potionDelayTime = Item.potionDelay;
            restorationDelayTime = Item.restorationDelay;
            mushroomDelayTime = Item.mushroomDelay;
            if (pStone)
            {
                potionDelayTime = (int)((float)potionDelayTime * PhilosopherStoneDurationMultiplier);
                restorationDelayTime = (int)((float)restorationDelayTime * PhilosopherStoneDurationMultiplier);
                mushroomDelayTime = (int)((float)mushroomDelayTime * PhilosopherStoneDurationMultiplier);
            }
            if (yoraiz0rEye > 0)
            {
                Yoraiz0rEye();
            }
            ResetEffects();
            UpdateDyes();
            if (CreativePowerManager.Instance.GetPower<CreativePowers.GodmodePower>().IsEnabledForPlayer(whoAmI))
            {
                creativeGodMode = true;
            }
            if (IsStandingStillForSpecialEffects && itemAnimation == 0)
            {
                afkCounter++;
            }
            else
            {
                afkCounter = 0;
            }
            if (whoAmI == Main.myPlayer)
            {
                Main.musicBox2 = -1;
                if (Main.SceneMetrics.WaterCandleCount > 0)
                {
                    AddBuff(86, 2, quiet: false);
                }
                if (Main.SceneMetrics.PeaceCandleCount > 0)
                {
                    AddBuff(157, 2, quiet: false);
                }
                if (Main.SceneMetrics.ShadowCandleCount > 0)
                {
                    AddBuff(350, 2, quiet: false);
                }
                if (Main.SceneMetrics.HasCampfire)
                {
                    AddBuff(87, 2, quiet: false);
                }
                if (Main.SceneMetrics.HasCatBast)
                {
                    AddBuff(215, 2, quiet: false);
                }
                if (Main.SceneMetrics.HasStarInBottle)
                {
                    AddBuff(158, 2, quiet: false);
                }
                if (Main.SceneMetrics.HasHeartLantern)
                {
                    AddBuff(89, 2, quiet: false);
                }
                if (Main.SceneMetrics.HasSunflower)
                {
                    AddBuff(146, 2, quiet: false);
                }
                if (Main.SceneMetrics.hasBanner)
                {
                    AddBuff(147, 2, quiet: false);
                }
                if (!behindBackWall && ZoneSandstorm)
                {
                    AddBuff(194, 2, quiet: false);
                }
            }
            PlayerLoader.PreUpdateBuffs(this);
            for (int num33 = 0; num33 < BuffLoader.BuffCount; num33++)
            {
                buffImmune[num33] = false;
            }
            UpdateProjectileCaches(i);
            UpdateBuffs(i);
            PlayerLoader.PostUpdateBuffs(this);
            if (kbBuff)
            {
                allKB *= 1.5f;
            }
            if (whoAmI == Main.myPlayer)
            {
                if (!onFire && !poisoned)
                {
                    trapDebuffSource = false;
                }
                UpdatePet(i);
                UpdatePetLight(i);
                isOperatingAnotherEntity = ownedProjectileCounts[1020] > 0;
            }
            bool flag5 = wet && !lavaWet && (!mount.Active || !mount.IsConsideredASlimeMount);
            if (accMerman && flag5)
            {
                releaseJump = true;
                wings = 0;
                merman = true;
                accFlipper = true;
                AddBuff(34, 2);
            }
            else
            {
                merman = false;
            }
            if (!flag5 && forceWerewolf)
            {
                forceMerman = false;
            }
            if (forceMerman && flag5)
            {
                wings = 0;
            }
            accMerman = false;
            hideMerman = false;
            forceMerman = false;
            if (wolfAcc && !merman && !Main.dayTime && !wereWolf)
            {
                AddBuff(28, 60);
            }
            wolfAcc = false;
            hideWolf = false;
            forceWerewolf = false;
            if (whoAmI == Main.myPlayer)
            {
                for (int num34 = 0; num34 < maxBuffs; num34++)
                {
                    if (buffType[num34] > 0 && buffTime[num34] <= 0)
                    {
                        DelBuff(num34);
                    }
                }
            }
            beetleDefense = false;
            beetleOffense = false;
            setSolar = false;
            head = armor[0].headSlot;
            body = armor[1].bodySlot;
            legs = armor[2].legSlot;
            ResetVisibleAccessories();
            if (MountFishronSpecialCounter > 0f)
            {
                MountFishronSpecialCounter -= 1f;
            }
            if (_portalPhysicsTime > 0)
            {
                _portalPhysicsTime--;
            }
            UpdateEquips(i);
            if (Main.npcShop <= 0)
            {
                discountAvailable = discountEquipped;
            }
            if (flag4 != pStone)
            {
                AdjustRemainingPotionSickness();
            }
            UpdatePermanentBoosters();
            UpdateLuck();
            shimmerUnstuckHelper.Update(this);
            UpdatePortableStoolUsage();
            if (velocity.Y == 0f || controlJump)
            {
                portalPhysicsFlag = false;
            }
            if (inventory[selectedItem].type == 3384 || portalPhysicsFlag)
            {
                _portalPhysicsTime = 30;
            }
            if (mount.Active)
            {
                mount.UpdateEffects(this);
            }
            gemCount++;
            if (gemCount >= 10)
            {
                gem = -1;
                ownedLargeGems = (byte)0;
                gemCount = 0;
                for (int num35 = 0; num35 <= 58; num35++)
                {
                    if (inventory[num35].type == 0 || inventory[num35].stack == 0)
                    {
                        inventory[num35].TurnToAir();
                    }
                    if (inventory[num35].type >= 1522 && inventory[num35].type <= 1527)
                    {
                        gem = inventory[num35].type - 1522;
                        ownedLargeGems[gem] = true;
                    }
                    if (inventory[num35].type == 3643)
                    {
                        gem = 6;
                        ownedLargeGems[gem] = true;
                    }
                }
            }
            UpdateArmorLights();
            UpdateArmorSets(i);
            if (shadowDodge && !onHitDodge)
            {
                ClearBuff(59);
            }
            PlayerLoader.PostUpdateEquips(this);
            if (maxTurretsOld != maxTurrets)
            {
                UpdateMaxTurrets();
                maxTurretsOld = maxTurrets;
            }
            if (shieldRaised)
            {
                statDefense += 20;
            }
            if ((merman || forceMerman) && flag5)
            {
                wings = 0;
            }
            if (invis)
            {
                if (itemAnimation == 0 && aggro > -750)
                {
                    aggro = -750;
                }
                else if (aggro > -250)
                {
                    aggro = -250;
                }
            }
            if (inventory[selectedItem].type == 3106)
            {
                if (itemAnimation > 0)
                {
                    stealthTimer = 15;
                    if (stealth > 0f)
                    {
                        stealth += 0.1f;
                    }
                }
                else if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1 && (double)velocity.Y > -0.1 && (double)velocity.Y < 0.1 && !mount.Active)
                {
                    if (stealthTimer == 0 && stealth > 0f)
                    {
                        stealth -= 0.02f;
                        if ((double)stealth <= 0.0)
{
                            stealth = 0f;
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(84, -1, -1, null, whoAmI);
                            }
                        }
                    }
                }
                else
                {
                    if (stealth > 0f)
                    {
                        stealth += 0.1f;
                    }
                    if (mount.Active)
                    {
                        stealth = 1f;
                    }
                }
                if (stealth > 1f)
                {
                    stealth = 1f;
                }
                meleeDamage += (1f - stealth) * 3f;
                meleeCrit += (int)((1f - stealth) * 30f);
                GetKnockback(DamageClass.Melee) *= 1f + (1f - stealth);
                aggro -= (int)((1f - stealth) * 750f);
                if (stealthTimer > 0)
                {
                    stealthTimer--;
                }
            }
            else if (shroomiteStealth)
            {
                if (itemAnimation > 0)
                {
                    stealthTimer = 5;
                }
                if ((double)velocity.X > -0.1 && (double)velocity.X < 0.1 && (double)velocity.Y > -0.1 && (double)velocity.Y < 0.1 && !mount.Active)
                {
                    if (stealthTimer == 0 && stealth > 0f)
                    {
                        stealth -= 0.015f;
                        if ((double)stealth <= 0.0)
{
                            stealth = 0f;
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(84, -1, -1, null, whoAmI);
                            }
                        }
                    }
                }
                else
                {
                    float num36 = Math.Abs(velocity.X) + Math.Abs(velocity.Y);
                    stealth += num36 * 0.0075f;
                    if (stealth > 1f)
                    {
                        stealth = 1f;
                    }
                    if (mount.Active)
                    {
                        stealth = 1f;
                    }
                }
                rangedDamage += (1f - stealth) * 0.6f;
                rangedCrit += (int)((1f - stealth) * 10f);
                GetKnockback(DamageClass.Ranged) *= 1f + (1f - stealth) * 0.5f;
                aggro -= (int)((1f - stealth) * 750f);
                if (stealthTimer > 0)
                {
                    stealthTimer--;
                }
            }
            else if (setVortex)
            {
                bool flag6 = false;
                if (vortexStealthActive)
                {
                    float num38 = stealth;
                    stealth -= 0.04f;
                    if (stealth < 0f)
                    {
                        stealth = 0f;
                    }
                    else
                    {
                        flag6 = true;
                    }
                    if (stealth == 0f && num38 != stealth && Main.netMode == 1)
                    {
                        NetMessage.SendData(84, -1, -1, null, whoAmI);
                    }
                    rangedDamage += (1f - stealth) * 0.8f;
                    rangedCrit += (int)((1f - stealth) * 20f);
                    GetKnockback(DamageClass.Ranged) *= 1f + (1f - stealth) * 0.5f;
                    aggro -= (int)((1f - stealth) * 1200f);
                    accRunSpeed *= 0.3f;
                    maxRunSpeed *= 0.3f;
                    if (mount.Active)
                    {
                        vortexStealthActive = false;
                    }
                }
                else
                {
                    float num39 = stealth;
                    stealth += 0.04f;
                    if (stealth > 1f)
                    {
                        stealth = 1f;
                    }
                    else
                    {
                        flag6 = true;
                    }
                    if (stealth == 1f && num39 != stealth && Main.netMode == 1)
                    {
                        NetMessage.SendData(84, -1, -1, null, whoAmI);
                    }
                }
                if (flag6)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        Vector2 vector = Vector2.UnitY.RotatedByRandom(6.2831854820251465);
                        Dust obj2 = Main.dust[Dust.NewDust(base.Center - vector * 30f, 0, 0, 229)];
                        obj2.noGravity = true;
                        obj2.position = base.Center - vector * (float)Main.rand.Next(5, 11);
                        obj2.velocity = vector.RotatedBy(1.5707963705062866) * 4f;
                        obj2.scale = 0.5f + Main.rand.NextFloat();
                        obj2.fadeIn = 0.5f;
                    }
                    if (Main.rand.Next(2) == 0)
                    {
                        Vector2 vector2 = Vector2.UnitY.RotatedByRandom(6.2831854820251465);
                        Dust obj3 = Main.dust[Dust.NewDust(base.Center - vector2 * 30f, 0, 0, 240)];
                        obj3.noGravity = true;
                        obj3.position = base.Center - vector2 * 12f;
                        obj3.velocity = vector2.RotatedBy(-1.5707963705062866) * 2f;
                        obj3.scale = 0.5f + Main.rand.NextFloat();
                        obj3.fadeIn = 0.5f;
                    }
                }
            }
            else
            {
                stealth = 1f;
            }
            if (manaSick)
            {
                magicDamage *= 1f - manaSickReduction;
            }
            if (tileSpeed > 3f)
            {
                tileSpeed = 3f;
            }
            tileSpeed = 1f / tileSpeed;
            if (wallSpeed > 3f)
            {
                wallSpeed = 3f;
            }
            wallSpeed = 1f / wallSpeed;
            if (slowOgreSpit)
            {
                moveSpeed /= 3f;
                if (velocity.Y == 0f && Math.Abs(velocity.X) > 1f)
                {
                    velocity.X /= 2f;
                }
            }
            else if (dazed)
            {
                moveSpeed /= 3f;
            }
            else if (slow)
            {
                moveSpeed /= 2f;
            }
            else if (chilled)
            {
                moveSpeed *= 0.75f;
            }
            if (shieldRaised)
            {
                moveSpeed /= 3f;
                if (velocity.Y == 0f && Math.Abs(velocity.X) > 3f)
                {
                    velocity.X /= 2f;
                }
            }
            if (DD2Event.Ongoing)
            {
                DD2Event.FindArenaHitbox();
                if (DD2Event.ShouldBlockBuilding(base.Center))
                {
                    noBuilding = true;
                    AddBuff(199, 3);
                }
            }
            if ((double)pickSpeed < 0.3)
            {
                pickSpeed = 0.3f;
            }
            CapAttackSpeeds();
            PlayerLoader.PostUpdateMiscEffects(this);
            UpdateLifeRegen();
            soulDrain = 0;
            UpdateManaRegen();
            if (manaRegenCount < 0)
            {
                manaRegenCount = 0;
            }
            if (statMana > statManaMax2)
            {
                statMana = statManaMax2;
            }
            runAcceleration *= moveSpeed;
            maxRunSpeed *= moveSpeed;
            UpdateJumpHeight();
            for (int num40 = 0; num40 < maxBuffs; num40++)
            {
                if (buffType[num40] > 0 && buffTime[num40] > 0 && buffImmune[buffType[num40]])
                {
                    DelBuff(num40);
                }
            }
            if (brokenArmor)
            {
                statDefense /= 2f;
            }
            if (witheredArmor)
            {
                statDefense /= 2f;
            }
            if (witheredWeapon)
            {
                allDamage *= 0.5f;
            }
            lastTileRangeX = tileRangeX;
            lastTileRangeY = tileRangeY;
            if (mount.Active)
            {
                movementAbilitiesCache.CopyFrom(this);
            }
            else
            {
                movementAbilitiesCache.PasteInto(this);
            }
            if (mount.Active && mount.BlockExtraJumps)
            {
                ConsumeAllExtraJumps();
            }
            else if (velocity.Y == 0f || sliding)
            {
                RefreshDoubleJumps();
            }
            else
            {
                ExtraJumpLoader.ConsumeAndStopUnavailableJumps(this);
            }
            if (!carpet)
            {
                canCarpet = false;
                carpetFrame = -1;
            }
            else if (velocity.Y == 0f || sliding)
            {
                canCarpet = true;
                carpetTime = 0;
                carpetFrame = -1;
                carpetFrameCounter = 0f;
            }
            if (gravDir == -1f)
            {
                canCarpet = false;
            }
            if (ropeCount > 0)
            {
                ropeCount--;
            }
            if (!pulley && !frozen && !webbed && !stoned && !controlJump && gravDir == 1f && ropeCount == 0 && grappling[0] == -1 && !tongued && !mount.Active)
            {
                FindPulley();
            }
            UpdatePettingAnimal();
            sitting.UpdateSitting(this);
            sleeping.UpdateState(this);
            eyeHelper.Update(this);
            if (pulley)
            {
                if (mount.Active)
                {
                    pulley = false;
                }
                sandStorm = false;
                CancelAllJumpVisualEffects();
                int num41 = (int)(position.X + (float)(width / 2)) / 16;
                int num42 = (int)(position.Y - 8f) / 16;
                bool flag7 = false;
                if (pulleyDir == 0)
                {
                    pulleyDir = 1;
                }
                if (pulleyDir == 1)
                {
                    if (direction == -1 && controlLeft && (releaseLeft || leftTimer == 0))
                    {
                        pulleyDir = 2;
                        flag7 = true;
                    }
                    else if ((direction == 1 && controlRight && releaseRight) || rightTimer == 0)
                    {
                        pulleyDir = 2;
                        flag7 = true;
                    }
                    else
                    {
                        if (direction == 1 && controlLeft)
{
                            direction = -1;
                            flag7 = true;
                        }
                        if (direction == -1 && controlRight)
{
                            direction = 1;
                            flag7 = true;
                        }
                    }
                }
                else if (pulleyDir == 2)
                {
                    if (direction == 1 && controlLeft)
                    {
                        flag7 = true;
                        if (!Collision.SolidCollision(new Vector2((float)(num41 * 16 + 8 - width / 2), position.Y), width, height))
{
                            pulleyDir = 1;
                            direction = -1;
                            flag7 = true;
                        }
                    }
                    if (direction == -1 && controlRight)
                    {
                        flag7 = true;
                        if (!Collision.SolidCollision(new Vector2((float)(num41 * 16 + 8 - width / 2), position.Y), width, height))
{
                            pulleyDir = 1;
                            direction = 1;
                            flag7 = true;
                        }
                    }
                }
                int num43 = 1;
                if (controlLeft)
                {
                    num43 = -1;
                }
                bool flag8 = CanMoveForwardOnRope(num43, num41, num42);
                if (controlLeft && direction == -1 && flag8)
                {
                    instantMovementAccumulatedThisFrame.X += -1f;
                }
                if (controlRight && direction == 1 && flag8)
                {
                    instantMovementAccumulatedThisFrame.X += 1f;
                }
                bool flag9 = false;
                if (!flag7 && ((controlLeft && (releaseLeft || leftTimer == 0)) || (controlRight && (releaseRight || rightTimer == 0))))
                {
                    int num44 = num41 + num43;
                    if (WorldGen.IsRope(num44, num42))
                    {
                        pulleyDir = 1;
                        direction = num43;
                        int num45 = num44 * 16 + 8 - width / 2;
                        float y4 = position.Y;
                        y4 = num42 * 16 + 22;
                        if (Main.tile[num44, num42 - 1] == null)
{
                            Main.tile[num44, num42 - 1] = default(Tile);
                        }
                        if (Main.tile[num44, num42 + 1] == null)
{
                            Main.tile[num44, num42 + 1] = default(Tile);
                        }
                        if (WorldGen.IsRope(num44, num42 - 1) || WorldGen.IsRope(num44, num42 + 1))
{
                            y4 = num42 * 16 + 22;
                        }
                        if (Collision.SolidCollision(new Vector2((float)num45, y4), width, height))
{
                            pulleyDir = 2;
                            direction = -num43;
                            num45 = ((direction != 1) ? (num44 * 16 + 8 - width / 2 + -6) : (num44 * 16 + 8 - width / 2 + 6));
                        }
                        if (i == Main.myPlayer)
{
                            Main.cameraX = Main.cameraX + position.X - (float)num45;
                        }
                        position.X = num45;
                        gfxOffY = position.Y - y4;
                        position.Y = y4;
                        flag9 = true;
                    }
                }
                if (!flag9 && !flag7 && !controlUp && ((controlLeft && releaseLeft) || (controlRight && releaseRight)))
                {
                    pulley = false;
                    if (controlLeft && velocity.X == 0f)
                    {
                        velocity.X = -1f;
                    }
                    if (controlRight && velocity.X == 0f)
                    {
                        velocity.X = 1f;
                    }
                }
                if (velocity.X != 0f)
                {
                    pulley = false;
                }
                if (Main.tile[num41, num42] == null)
                {
                    Main.tile[num41, num42] = default(Tile);
                }
                if (!WorldGen.IsRope(num41, num42))
                {
                    pulley = false;
                }
                if (gravDir != 1f)
                {
                    pulley = false;
                }
                if (frozen || webbed || stoned)
                {
                    pulley = false;
                }
                if (!pulley)
                {
                    velocity.Y -= gravity;
                }
                if (controlJump)
                {
                    pulley = false;
                    jump = jumpHeight;
                    velocity.Y = 0f - jumpSpeed;
                }
            }
            if (grapCount > 0)
            {
                pulley = false;
            }
            if (NPC.brainOfGravity >= 0 && NPC.brainOfGravity < 200 && Vector2.Distance(base.Center, Main.npc[NPC.brainOfGravity].Center) < 4000f)
            {
                forcedGravity = 10;
            }
            if (forcedGravity > 0)
            {
                gravDir = -1f;
            }
            if (pulley)
            {
                fallStart = (int)position.Y / 16;
                wingFrame = 0;
                if (wings == 4)
                {
                    wingFrame = 3;
                }
                int num46 = (int)(position.X + (float)(width / 2)) / 16;
                int num48 = (int)(position.Y - 16f) / 16;
                int num49 = (int)(position.Y - 8f) / 16;
                bool flag10 = true;
                bool flag11 = false;
                if (WorldGen.IsRope(num46, num49 - 1) || WorldGen.IsRope(num46, num49 + 1))
                {
                    flag11 = true;
                }
                if (Main.tile[num46, num48] == null)
                {
                    Main.tile[num46, num48] = default(Tile);
                }
                if (!WorldGen.IsRope(num46, num48))
                {
                    flag10 = false;
                    if (velocity.Y < 0f)
                    {
                        velocity.Y = 0f;
                    }
                }
                if (flag11)
                {
                    if (controlUp && flag10)
                    {
                        float x3 = position.X;
                        float y5 = position.Y - Math.Abs(velocity.Y) - 2f;
                        if (Collision.SolidCollision(new Vector2(x3, y5), width, height))
{
                            x3 = num46 * 16 + 8 - width / 2 + 6;
                            if (!Collision.SolidCollision(new Vector2(x3, y5), width, (int)((float)height + Math.Abs(velocity.Y) + 2f)))
{
                                if (i == Main.myPlayer)
{
                                    Main.cameraX = Main.cameraX + position.X - x3;
                                }
                                pulleyDir = 2;
                                direction = 1;
                                position.X = x3;
                                velocity.X = 0f;
                            }
                            else
{
                                x3 = num46 * 16 + 8 - width / 2 + -6;
                                if (!Collision.SolidCollision(new Vector2(x3, y5), width, (int)((float)height + Math.Abs(velocity.Y) + 2f)))
{
                                    if (i == Main.myPlayer)
{
                                        Main.cameraX = Main.cameraX + position.X - x3;
                                    }
                                    pulleyDir = 2;
                                    direction = -1;
                                    position.X = x3;
                                    velocity.X = 0f;
                                }
                            }
                        }
                        if (velocity.Y > 0f)
{
                            velocity.Y *= 0.7f;
                        }
                        if (velocity.Y > -3f)
{
                            velocity.Y -= 0.2f;
                        }
                        else
{
                            velocity.Y -= 0.02f;
                        }
                        if (velocity.Y < -8f)
{
                            velocity.Y = -8f;
                        }
                    }
                    else if (controlDown)
                    {
                        float x4 = position.X;
                        float y6 = position.Y;
                        if (Collision.SolidCollision(new Vector2(x4, y6), width, (int)((float)height + Math.Abs(velocity.Y) + 2f)))
{
                            x4 = num46 * 16 + 8 - width / 2 + 6;
                            if (!Collision.SolidCollision(new Vector2(x4, y6), width, (int)((float)height + Math.Abs(velocity.Y) + 2f)))
{
                                if (i == Main.myPlayer)
{
                                    Main.cameraX = Main.cameraX + position.X - x4;
                                }
                                pulleyDir = 2;
                                direction = 1;
                                position.X = x4;
                                velocity.X = 0f;
                            }
                            else
{
                                x4 = num46 * 16 + 8 - width / 2 + -6;
                                if (!Collision.SolidCollision(new Vector2(x4, y6), width, (int)((float)height + Math.Abs(velocity.Y) + 2f)))
{
                                    if (i == Main.myPlayer)
{
                                        Main.cameraX = Main.cameraX + position.X - x4;
                                    }
                                    pulleyDir = 2;
                                    direction = -1;
                                    position.X = x4;
                                    velocity.X = 0f;
                                }
                            }
                        }
                        if (velocity.Y < 0f)
{
                            velocity.Y *= 0.7f;
                        }
                        if (velocity.Y < 3f)
{
                            velocity.Y += 0.2f;
                        }
                        else
{
                            velocity.Y += 0.1f;
                        }
                        if (velocity.Y > maxFallSpeed)
{
                            velocity.Y = maxFallSpeed;
                        }
                    }
                    else
                    {
                        velocity.Y *= 0.7f;
                        if ((double)velocity.Y > -0.1 && (double)velocity.Y < 0.1)
{
                            velocity.Y = 0f;
                        }
                    }
                }
                else if (controlDown)
                {
                    ropeCount = 10;
                    pulley = false;
                    velocity.Y = 1f;
                }
                else
                {
                    velocity.Y = 0f;
                    position.Y = num48 * 16 + 22;
                }
                float num50 = num46 * 16 + 8 - width / 2;
                if (pulleyDir == 1)
                {
                    num50 = num46 * 16 + 8 - width / 2;
                }
                if (pulleyDir == 2)
                {
                    num50 = num46 * 16 + 8 - width / 2 + 6 * direction;
                }
                if (i == Main.myPlayer)
                {
                    Main.cameraX += position.X - num50;
                    Main.cameraX = MathHelper.Clamp(Main.cameraX, -32f, 32f);
                }
                position.X = num50;
                pulleyFrameCounter += Math.Abs(velocity.Y * 0.75f);
                if (velocity.Y != 0f)
                {
                    pulleyFrameCounter += 0.75f;
                }
                if (pulleyFrameCounter > 10f)
                {
                    pulleyFrame++;
                    pulleyFrameCounter = 0f;
                }
                if (pulleyFrame > 1)
                {
                    pulleyFrame = 0;
                }
                canCarpet = true;
                carpetFrame = -1;
                wingTime = wingTimeMax;
                rocketTime = rocketTimeMax;
                rocketDelay = 0;
                rocketFrame = false;
                canRocket = false;
                rocketRelease = false;
                DashMovement();
                UpdateControlHolds();
            }
            else if (grappling[0] == -1 && !tongued)
            {
                if (wingsLogic > 0 && velocity.Y != 0f && !merman && !mount.Active)
                {
                    WingAirLogicTweaks();
                }
                if (empressBrooch)
                {
                    runAcceleration *= 1.75f;
                }
                if (hasMagiluminescence && velocity.Y == 0f)
                {
                    runAcceleration *= 1.75f;
                    maxRunSpeed *= 1.15f;
                    accRunSpeed *= 1.15f;
                    runSlowdown *= 1.75f;
                }
                if (shadowArmor)
                {
                    runAcceleration *= 1.75f;
                    maxRunSpeed *= 1.15f;
                    accRunSpeed *= 1.15f;
                    runSlowdown *= 1.75f;
                }
                if (mount.Active && mount.Type == 43 && velocity.Y != 0f)
                {
                    runSlowdown = 0f;
                }
                if (sticky)
                {
                    maxRunSpeed *= 0.25f;
                    runAcceleration *= 0.25f;
                    runSlowdown *= 2f;
                    if (velocity.X > maxRunSpeed)
                    {
                        velocity.X = maxRunSpeed;
                    }
                    if (velocity.X < 0f - maxRunSpeed)
                    {
                        velocity.X = 0f - maxRunSpeed;
                    }
                }
                else if (powerrun)
                {
                    maxRunSpeed *= 3.5f;
                    runAcceleration *= 1f;
                    runSlowdown *= 2f;
                }
                else if (runningOnSand && desertBoots)
                {
                    float num51 = 1.75f;
                    maxRunSpeed *= num51;
                    accRunSpeed *= num51;
                    runAcceleration *= num51;
                    runSlowdown *= num51;
                }
                else if (slippy2)
                {
                    runAcceleration *= 0.6f;
                    runSlowdown = 0f;
                    if (iceSkate)
                    {
                        runAcceleration *= 3.5f;
                        maxRunSpeed *= 1.25f;
                    }
                }
                else if (slippy)
                {
                    runAcceleration *= 0.7f;
                    if (iceSkate)
                    {
                        runAcceleration *= 3.5f;
                        maxRunSpeed *= 1.25f;
                    }
                    else
                    {
                        runSlowdown *= 0.1f;
                    }
                }
                ExtraJumpLoader.UpdateHorizontalSpeeds(this);
                if (carpetFrame != -1)
                {
                    runAcceleration *= 1.25f;
                    maxRunSpeed *= 1.5f;
                }
                if (inventory[selectedItem].type == 3106 && stealth < 1f)
                {
                    float num52 = maxRunSpeed / 2f * (1f - stealth);
                    maxRunSpeed -= num52;
                    accRunSpeed = maxRunSpeed;
                }
                if (mount.Active)
                {
                    rocketBoots = 0;
                    vanityRocketBoots = 0;
                    wings = 0;
                    wingsLogic = 0;
                    maxRunSpeed = mount.RunSpeed;
                    accRunSpeed = mount.DashSpeed;
                    runAcceleration = mount.Acceleration;
                    if (mount.Type == 12 && !MountFishronSpecial)
                    {
                        runAcceleration /= 2f;
                        maxRunSpeed /= 2f;
                    }
                    mount.AbilityRecovery();
                    if (mount.Cart && velocity.Y == 0f)
                    {
                        if (!Minecart.OnTrack(position, width, height))
{
                            fullRotation = 0f;
                            onWrongGround = true;
                            runSlowdown = 0.2f;
                            if ((controlLeft && releaseLeft) || (controlRight && releaseRight))
{
                                mount.Dismount(this);
                            }
                        }
                        else
{
                            runSlowdown = runAcceleration;
                            onWrongGround = false;
                        }
                    }
                    if (mount.Type == 8)
                    {
                        mount.UpdateDrill(this, controlUp, controlDown);
                    }
                }
                PlayerLoader.PostUpdateRunSpeeds(this);
                HorizontalMovement();
                bool flag13 = !mount.Active;
                if (forcedGravity > 0)
                {
                    gravDir = -1f;
                }
                else if (gravControl && flag13)
                {
                    if (controlUp && releaseUp)
                    {
                        if (gravDir == 1f)
{
                            gravDir = -1f;
                            fallStart = (int)(position.Y / 16f);
                            jump = 0;
                            SoundEngine.PlaySound(in SoundID.Item8, position);
                        }
                        else
{
                            gravDir = 1f;
                            fallStart = (int)(position.Y / 16f);
                            jump = 0;
                            SoundEngine.PlaySound(in SoundID.Item8, position);
                        }
                    }
                }
                else if (gravControl2 && flag13)
                {
                    if (controlUp && releaseUp)
                    {
                        if (gravDir == 1f)
{
                            gravDir = -1f;
                            fallStart = (int)(position.Y / 16f);
                            jump = 0;
                            SoundEngine.PlaySound(in SoundID.Item8, position);
                        }
                        else
{
                            gravDir = 1f;
                            fallStart = (int)(position.Y / 16f);
                            jump = 0;
                            SoundEngine.PlaySound(in SoundID.Item8, position);
                        }
                    }
                }
                else
                {
                    gravDir = 1f;
                }
                if (velocity.Y == 0f && mount.Active && mount.CanHover() && controlUp && releaseUp)
                {
                    velocity.Y = 0f - (mount.Acceleration + gravity + 0.001f);
                }
                UpdateControlHolds();
                sandStorm = false;
                JumpMovement();
                if (wingsLogic == 0)
                {
                    wingTime = 0f;
                }
                if (rocketBoots == 0)
                {
                    rocketTime = 0;
                }
                if (jump == 0)
                {
                    CancelAllJumpVisualEffects();
                }
                DashMovement();
                WallslideMovement();
                CarpetMovement();
                DoubleJumpVisuals();
                if (wingsLogic > 0 || mount.Active)
                {
                    sandStorm = false;
                }
                if (((gravDir == 1f && velocity.Y > 0f - jumpSpeed) || (gravDir == -1f && velocity.Y < jumpSpeed)) && velocity.Y != 0f)
                {
                    canRocket = true;
                }
                bool flag14 = false;
                if (((velocity.Y == 0f || sliding) && releaseJump) || (autoJump && justJumped))
                {
                    mount.ResetFlightTime(velocity.X);
                    wingTime = wingTimeMax;
                }
                if (wingsLogic > 0 && controlJump && wingTime > 0f && jump == 0 && velocity.Y != 0f)
                {
                    flag14 = true;
                }
                if ((wingsLogic == 22 || wingsLogic == 28 || wingsLogic == 30 || wingsLogic == 32 || wingsLogic == 29 || wingsLogic == 33 || wingsLogic == 35 || wingsLogic == 37 || wingsLogic == 45) && controlJump && TryingToHoverDown && wingTime > 0f)
                {
                    flag14 = true;
                }
                if (frozen || webbed || stoned)
                {
                    if (mount.Active)
                    {
                        mount.Dismount(this);
                    }
                    velocity.Y += gravity;
                    if (velocity.Y > maxFallSpeed)
                    {
                        velocity.Y = maxFallSpeed;
                    }
                    sandStorm = false;
                    CancelAllJumpVisualEffects();
                }
                else
                {
                    bool isCustomWings = ItemLoader.WingUpdate(this, flag14);
                    if (flag14)
                    {
                        WingAirVisuals();
                        WingMovement();
                    }
                    WingFrame(flag14, isCustomWings);
                    if (wingsLogic > 0 && rocketBoots != 0 && velocity.Y != 0f && rocketTime != 0)
                    {
                        int num53 = 6;
                        int num54 = rocketTime * num53;
                        wingTime += num54;
                        if (wingTime > (float)(wingTimeMax + num54))
{
                            wingTime = wingTimeMax + num54;
                        }
                        rocketTime = 0;
                    }
                    if (!isCustomWings && flag14 && wings != 4 && wings != 22 && wings != 0 && wings != 24 && wings != 28 && wings != 30 && wings != 33 && wings != 45)
                    {
                        bool flag15 = wingFrame == 3;
                        if (wings == 43 || wings == 44)
{
                            flag15 = wingFrame == 4;
                        }
                        if (flag15)
{
                            if (!flapSound)
{
                                SoundEngine.PlaySound(in SoundID.Item32, position);
                            }
                            flapSound = true;
                        }
                        else
{
                            flapSound = false;
                        }
                    }
                    if (velocity.Y == 0f || sliding || (autoJump && justJumped))
                    {
                        rocketTime = rocketTimeMax;
                    }
                    if (empressBrooch)
                    {
                        rocketTime = rocketTimeMax;
                    }
                    if ((wingTime == 0f || wingsLogic == 0) && rocketBoots != 0 && controlJump && rocketDelay == 0 && canRocket && rocketRelease && !AnyExtraJumpUsable())
                    {
                        if (rocketTime > 0)
{
                            rocketTime--;
                            rocketDelay = 10;
                            if (rocketDelay2 <= 0)
{
                                if (rocketBoots == 1)
{
                                    rocketDelay2 = 30;
                                }
                                else if (rocketBoots == 2 || rocketBoots == 5 || rocketBoots == 3 || rocketBoots == 4)
{
                                    rocketDelay2 = 15;
                                }
                            }
                            if (rocketSoundDelay <= 0)
{
                                if (vanityRocketBoots == 1 || vanityRocketBoots == 5)
{
                                    rocketSoundDelay = 30;
                                    SoundEngine.PlaySound(in SoundID.Item13, position);
                                }
                                else if (vanityRocketBoots == 2 || vanityRocketBoots == 3 || vanityRocketBoots == 4)
{
                                    rocketSoundDelay = 15;
                                    SoundEngine.PlaySound(in SoundID.Item24, position);
                                }
                            }
                        }
                        else
{
                            canRocket = false;
                        }
                    }
                    if (rocketSoundDelay > 0)
                    {
                        rocketSoundDelay--;
                    }
                    if (rocketDelay2 > 0)
                    {
                        rocketDelay2--;
                    }
                    if (rocketDelay == 0)
                    {
                        rocketFrame = false;
                    }
                    if (rocketDelay > 0)
                    {
                        rocketFrame = true;
                        RocketBootVisuals();
                        if (rocketDelay == 0)
{
                            releaseJump = true;
                        }
                        rocketDelay--;
                        velocity.Y -= 0.1f * gravDir;
                        if (gravDir == 1f)
{
                            if (velocity.Y > 0f)
{
                                velocity.Y -= 0.5f;
                            }
                            else if ((double)velocity.Y > (double)(0f - jumpSpeed) * 0.5)
{
                                velocity.Y -= 0.1f;
                            }
                            if (velocity.Y < (0f - jumpSpeed) * 1.5f)
{
                                velocity.Y = (0f - jumpSpeed) * 1.5f;
                            }
                        }
                        else
{
                            if (velocity.Y < 0f)
{
                                velocity.Y += 0.5f;
                            }
                            else if ((double)velocity.Y < (double)jumpSpeed * 0.5)
{
                                velocity.Y += 0.1f;
                            }
                            if (velocity.Y > jumpSpeed * 1.5f)
{
                                velocity.Y = jumpSpeed * 1.5f;
                            }
                        }
                    }
                    else if (!flag14)
                    {
                        if (mount.CanHover())
{
                            mount.Hover(this);
                        }
                        else if (mount.CanFly() && controlJump && jump == 0)
{
                            if (mount.Flight())
{
                                if (TryingToHoverDown)
{
                                    velocity.Y *= 0.9f;
                                    if (velocity.Y > -1f && (double)velocity.Y < 0.5)
{
                                        velocity.Y = 1E-05f;
                                    }
                                }
                                else
{
                                    float num55 = jumpSpeed;
                                    if (mount.Type == 50)
{
                                        num55 *= 0.5f;
                                    }
                                    if (velocity.Y > 0f)
{
                                        velocity.Y -= 0.5f;
                                    }
                                    else if ((double)velocity.Y > (double)(0f - num55) * 1.5)
{
                                        velocity.Y -= 0.1f;
                                    }
                                    if (velocity.Y < (0f - num55) * 1.5f)
{
                                        velocity.Y = (0f - num55) * 1.5f;
                                    }
                                }
                            }
                            else
{
                                velocity.Y += gravity / 3f * gravDir;
                                if (gravDir == 1f)
{
                                    if (velocity.Y > maxFallSpeed / 3f && !TryingToHoverDown)
{
                                        velocity.Y = maxFallSpeed / 3f;
                                    }
                                }
                                else if (velocity.Y < (0f - maxFallSpeed) / 3f && !TryingToHoverUp)
{
                                    velocity.Y = (0f - maxFallSpeed) / 3f;
                                }
                            }
                        }
                        else if (slowFall && !TryingToHoverDown)
{
                            if (TryingToHoverUp)
{
                                gravity = gravity / 10f * gravDir;
                            }
                            else
{
                                gravity = gravity / 3f * gravDir;
                            }
                            velocity.Y += gravity;
                        }
                        else if (wingsLogic > 0 && controlJump && velocity.Y > 0f)
{
                            bool noLightEmittence = wingsLogic != wings;
                            fallStart = (int)(position.Y / 16f);
                            if (velocity.Y > 0f)
{
                                if (wings == 10 && Main.rand.Next(3) == 0)
{
                                    int num56 = 4;
                                    if (direction == 1)
{
                                        num56 = -40;
                                    }
                                    int num57 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num56, position.Y + (float)(height / 2) - 15f), 30, 30, 76, 0f, 0f, 50, default(Color), 0.6f);
                                    Main.dust[num57].fadeIn = 1.1f;
                                    Main.dust[num57].noGravity = true;
                                    Main.dust[num57].noLight = true;
                                    Dust obj4 = Main.dust[num57];
                                    obj4.velocity *= 0.3f;
                                    Main.dust[num57].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                                }
                                if (wings == 34 && ShouldDrawWingsThatAreAlwaysAnimated() && Main.rand.Next(3) == 0)
{
                                    int num59 = 4;
                                    if (direction == 1)
{
                                        num59 = -40;
                                    }
                                    int num60 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num59, position.Y + (float)(height / 2) - 15f), 30, 30, 261, 0f, 0f, 50, default(Color), 0.6f);
                                    Main.dust[num60].fadeIn = 1.1f;
                                    Main.dust[num60].noGravity = true;
                                    Main.dust[num60].noLight = true;
                                    Main.dust[num60].noLightEmittence = noLightEmittence;
                                    Dust obj5 = Main.dust[num60];
                                    obj5.velocity *= 0.3f;
                                    Main.dust[num60].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                                }
                                if (wings == 40)
{
                                    ShouldDrawWingsThatAreAlwaysAnimated();
                                }
                                if (wings == 44)
{
                                    ShouldDrawWingsThatAreAlwaysAnimated();
                                }
                                if (wings == 9 && Main.rand.Next(3) == 0)
{
                                    int num61 = 8;
                                    if (direction == 1)
{
                                        num61 = -40;
                                    }
                                    int num62 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num61, position.Y + (float)(height / 2) - 15f), 30, 30, 6, 0f, 0f, 200, default(Color), 2f);
                                    Main.dust[num62].noGravity = true;
                                    Dust obj6 = Main.dust[num62];
                                    obj6.velocity *= 0.3f;
                                    Main.dust[num62].noLightEmittence = noLightEmittence;
                                    Main.dust[num62].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                                }
                                if (wings == 29 && Main.rand.Next(3) == 0)
{
                                    int num63 = 8;
                                    if (direction == 1)
{
                                        num63 = -40;
                                    }
                                    int num64 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num63, position.Y + (float)(height / 2) - 15f), 30, 30, 6, 0f, 0f, 100, default(Color), 2.4f);
                                    Main.dust[num64].noGravity = true;
                                    Dust obj7 = Main.dust[num64];
                                    obj7.velocity *= 0.3f;
                                    Main.dust[num64].noLightEmittence = noLightEmittence;
                                    if (Main.rand.Next(10) == 0)
{
                                        Main.dust[num64].fadeIn = 2f;
                                    }
                                    Main.dust[num64].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                                }
                                if (wings == 6)
{
                                    if (Main.rand.Next(10) == 0)
{
                                        int num65 = 4;
                                        if (direction == 1)
{
                                            num65 = -40;
                                        }
                                        int num66 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num65, position.Y + (float)(height / 2) - 12f), 30, 20, 55, 0f, 0f, 200);
                                        Main.dust[num66].noLightEmittence = noLightEmittence;
                                        Dust obj8 = Main.dust[num66];
                                        obj8.velocity *= 0.3f;
                                        Main.dust[num66].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                                    }
                                }
                                else if (wings == 5 && Main.rand.Next(6) == 0)
{
                                    int num67 = 6;
                                    if (direction == 1)
{
                                        num67 = -30;
                                    }
                                    int num68 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num67, position.Y), 18, height, 58, 0f, 0f, 255, default(Color), 1.2f);
                                    Dust obj9 = Main.dust[num68];
                                    obj9.velocity *= 0.3f;
                                    Main.dust[num68].noLightEmittence = noLightEmittence;
                                    Main.dust[num68].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                                }
                                if (!isCustomWings)
{
                                    if (wings == 4)
{
                                        rocketDelay2--;
                                        if (rocketDelay2 <= 0)
{
                                            SoundEngine.PlaySound(in SoundID.Item13, position);
                                            rocketDelay2 = 60;
                                        }
                                        int type = 6;
                                        float scale = 1.5f;
                                        int alpha = 100;
                                        float x5 = position.X + (float)(width / 2) + 16f;
                                        if (direction > 0)
{
                                            x5 = position.X + (float)(width / 2) - 26f;
                                        }
                                        float num70 = position.Y + (float)height - 18f;
                                        if (Main.rand.Next(2) == 1)
{
                                            x5 = position.X + (float)(width / 2) + 8f;
                                            if (direction > 0)
{
                                                x5 = position.X + (float)(width / 2) - 20f;
                                            }
                                            num70 += 6f;
                                        }
                                        int num71 = Dust.NewDust(new Vector2(x5, num70), 8, 8, type, 0f, 0f, alpha, default(Color), scale);
                                        Main.dust[num71].velocity.X *= 0.3f;
                                        Main.dust[num71].velocity.Y += 10f;
                                        Main.dust[num71].noGravity = true;
                                        Main.dust[num71].noLightEmittence = noLightEmittence;
                                        Main.dust[num71].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                                        wingFrameCounter++;
                                        if (wingFrameCounter > 4)
{
                                            wingFrame++;
                                            wingFrameCounter = 0;
                                            if (wingFrame >= 3)
{
                                                wingFrame = 0;
                                            }
                                        }
                                    }
                                    else if (wings != 22 && wings != 28)
{
                                        if (wings == 30)
{
                                            wingFrameCounter++;
                                            int num72 = 5;
                                            if (wingFrameCounter >= num72 * 3)
{
                                                wingFrameCounter = 0;
                                            }
                                            wingFrame = 1 + wingFrameCounter / num72;
                                        }
                                        else if (wings == 34)
{
                                            wingFrameCounter++;
                                            int num73 = 7;
                                            if (wingFrameCounter >= num73 * 6)
{
                                                wingFrameCounter = 0;
                                            }
                                            wingFrame = wingFrameCounter / num73;
                                        }
                                        else if (wings != 45)
{
                                            if (wings == 40)
{
                                                wingFrame = 0;
                                            }
                                            else if (wings == 44)
{
                                                wingFrame = 2;
                                            }
                                            else if (wings == 39)
{
                                                wingFrameCounter++;
                                                int num74 = 12;
                                                if (wingFrameCounter >= num74 * 6)
{
                                                    wingFrameCounter = 0;
                                                }
                                                wingFrame = wingFrameCounter / num74;
                                            }
                                            else if (wings == 26)
{
                                                int num75 = 6;
                                                if (direction == 1)
{
                                                    num75 = -30;
                                                }
                                                int num76 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num75, position.Y), 18, height, 217, 0f, 0f, 100, default(Color), 1.4f);
                                                Main.dust[num76].noGravity = true;
                                                Main.dust[num76].noLight = true;
                                                Dust obj10 = Main.dust[num76];
                                                obj10.velocity /= 4f;
                                                Dust obj11 = Main.dust[num76];
                                                obj11.velocity -= velocity;
                                                Main.dust[num76].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                                                if (Main.rand.Next(2) == 0)
{
                                                    num75 = -24;
                                                    if (direction == 1)
{
                                                        num75 = 12;
                                                    }
                                                    float num77 = position.Y;
                                                    if (gravDir == -1f)
{
                                                        num77 += (float)(height / 2);
                                                    }
                                                    num76 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num75, num77), 12, height / 2, 217, 0f, 0f, 100, default(Color), 1.4f);
                                                    Main.dust[num76].noGravity = true;
                                                    Main.dust[num76].noLight = true;
                                                    Dust obj12 = Main.dust[num76];
                                                    obj12.velocity /= 4f;
                                                    Dust obj13 = Main.dust[num76];
                                                    obj13.velocity -= velocity;
                                                    Main.dust[num76].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                                                }
                                                wingFrame = 2;
                                            }
                                            else if (wings == 37)
{
                                                Color color = Color.Lerp(Color.Black, Color.White, Main.rand.NextFloat());
                                                int num78 = 6;
                                                if (direction == 1)
{
                                                    num78 = -30;
                                                }
                                                int num79 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num78, position.Y), 24, height, Utils.SelectRandom<int>(Main.rand, 31, 31, 31), 0f, 0f, 100, default(Color), 0.7f);
                                                Main.dust[num79].noGravity = true;
                                                Main.dust[num79].noLight = true;
                                                Dust obj14 = Main.dust[num79];
                                                obj14.velocity /= 4f;
                                                Dust obj15 = Main.dust[num79];
                                                obj15.velocity -= velocity;
                                                Main.dust[num79].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                                                if (Main.dust[num79].type == 55)
{
                                                    Main.dust[num79].color = color;
                                                }
                                                if (Main.rand.Next(3) == 0)
{
                                                    num78 = -24;
                                                    if (direction == 1)
{
                                                        num78 = 12;
                                                    }
                                                    float num81 = position.Y;
                                                    if (gravDir == -1f)
{
                                                        num81 += (float)(height / 2);
                                                    }
                                                    num79 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num78, num81), 12, height / 2, Utils.SelectRandom<int>(Main.rand, 31, 31, 31), 0f, 0f, 140, default(Color), 0.7f);
                                                    Main.dust[num79].noGravity = true;
                                                    Main.dust[num79].noLight = true;
                                                    Dust obj16 = Main.dust[num79];
                                                    obj16.velocity /= 4f;
                                                    Dust obj17 = Main.dust[num79];
                                                    obj17.velocity -= velocity;
                                                    Main.dust[num79].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                                                    if (Main.dust[num79].type == 55)
{
                                                        Main.dust[num79].color = color;
                                                    }
                                                }
                                                wingFrame = 2;
                                            }
                                            else if (wings != 24)
{
                                                if (wings == 43)
{
                                                    wingFrame = 1;
                                                }
                                                else if (wings == 12)
{
                                                    wingFrame = 3;
                                                }
                                                else
{
                                                    wingFrame = 2;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                            velocity.Y += gravity / 3f * gravDir;
                            if (gravDir == 1f)
{
                                if (velocity.Y > maxFallSpeed / 3f && !TryingToHoverDown)
{
                                    velocity.Y = maxFallSpeed / 3f;
                                }
                            }
                            else if (velocity.Y < (0f - maxFallSpeed) / 3f && !TryingToHoverUp)
{
                                velocity.Y = (0f - maxFallSpeed) / 3f;
                            }
                        }
                        else if (cartRampTime <= 0)
{
                            velocity.Y += gravity * gravDir;
                        }
                        else
{
                            cartRampTime--;
                        }
                    }
                    if (!mount.Active || mount.Type != 5)
                    {
                        if (gravDir == 1f)
{
                            if (velocity.Y > maxFallSpeed)
{
                                velocity.Y = maxFallSpeed;
                            }
                            if (slowFall && velocity.Y > maxFallSpeed / 3f && !TryingToHoverDown)
{
                                velocity.Y = maxFallSpeed / 3f;
                            }
                            if (slowFall && velocity.Y > maxFallSpeed / 5f && TryingToHoverUp)
{
                                velocity.Y = maxFallSpeed / 10f;
                            }
                        }
                        else
{
                            if (velocity.Y < 0f - maxFallSpeed)
{
                                velocity.Y = 0f - maxFallSpeed;
                            }
                            if (slowFall && velocity.Y < (0f - maxFallSpeed) / 3f && !TryingToHoverDown)
{
                                velocity.Y = (0f - maxFallSpeed) / 3f;
                            }
                            if (slowFall && velocity.Y < (0f - maxFallSpeed) / 5f && TryingToHoverUp)
{
                                velocity.Y = (0f - maxFallSpeed) / 10f;
                            }
                        }
                    }
                }
            }
            else
            {
                UpdateControlHolds();
            }
            if (mount.Active)
            {
                wingFrame = 0;
            }
            if ((wingsLogic == 22 || wingsLogic == 28 || wingsLogic == 30 || wingsLogic == 31 || wingsLogic == 33 || wingsLogic == 35 || wingsLogic == 37 || wingsLogic == 45) && TryingToHoverDown && controlJump && wingTime > 0f && !merman)
            {
                float num82 = 0.9f;
                if (wingsLogic == 45)
                {
                    num82 = 0.8f;
                }
                velocity.Y *= num82;
                if (velocity.Y > -2f && velocity.Y < 1f)
                {
                    velocity.Y = 1E-05f;
                }
            }
            if (wingsLogic == 37 && TryingToHoverDown && controlJump && wingTime > 0f && !merman)
            {
                velocity.Y *= 0.92f;
                if (velocity.Y > -2f && velocity.Y < 1f)
                {
                    velocity.Y = 1E-05f;
                }
            }
            GrabItems(i);
            LookForTileInteractions();
            if (tongued)
            {
                StopVanityActions();
                bool flag16 = false;
                if (Main.wofNPCIndex >= 0)
                {
                    NPC nPC = Main.npc[Main.wofNPCIndex];
                    float num113 = nPC.Center.X + (float)(nPC.direction * 200);
                    float y7 = nPC.Center.Y;
                    Vector2 center = base.Center;
                    float num83 = num113 - center.X;
                    float num84 = y7 - center.Y;
                    float num85 = (float)Math.Sqrt(num83 * num83 + num84 * num84);
                    float num86 = 11f;
                    if (Main.expertMode)
                    {
                        float value = 22f;
                        float amount = Math.Min(1f, ((Vector2)(ref nPC.velocity)).Length() / 5f);
                        num86 = MathHelper.Lerp(num86, value, amount);
                    }
                    float num87 = num85;
                    if (num85 > num86)
                    {
                        num87 = num86 / num85;
                    }
                    else
                    {
                        num87 = 1f;
                        flag16 = true;
                    }
                    num83 *= num87;
                    num84 *= num87;
                    velocity.X = num83;
                    velocity.Y = num84;
                }
                else
                {
                    flag16 = true;
                }
                if (flag16 && Main.myPlayer == whoAmI)
                {
                    for (int num88 = 0; num88 < maxBuffs; num88++)
                    {
                        if (buffType[num88] == 38)
{
                            DelBuff(num88);
                        }
                    }
                }
            }
            if (Main.myPlayer == whoAmI)
            {
                WOFTongue();
                if (controlHook)
                {
                    if (releaseHook)
                    {
                        QuickGrapple();
                    }
                    releaseHook = false;
                }
                else
                {
                    releaseHook = true;
                }
                if (talkNPC >= 0)
                {
                    Rectangle rectangle = default(Rectangle);
                    ((Rectangle)(ref rectangle))._002Ector((int)(position.X + (float)(width / 2) - (float)(tileRangeX * 16)), (int)(position.Y + (float)(height / 2) - (float)(tileRangeY * 16)), tileRangeX * 16 * 2, tileRangeY * 16 * 2);
                    Rectangle value2 = default(Rectangle);
                    ((Rectangle)(ref value2))._002Ector((int)Main.npc[talkNPC].position.X, (int)Main.npc[talkNPC].position.Y, Main.npc[talkNPC].width, Main.npc[talkNPC].height);
                    if (!((Rectangle)(ref rectangle)).Intersects(value2) || chest != -1 || !Main.npc[talkNPC].active || tileEntityAnchor.InUse)
                    {
                        if (chest == -1)
{
                            SoundEngine.PlaySound(11);
                        }
                        SetTalkNPC(-1);
                        Main.npcChatCornerItem = 0;
                        Main.npcChatText = "";
                    }
                }
                if (sign >= 0)
                {
                    Rectangle value3 = default(Rectangle);
                    ((Rectangle)(ref value3))._002Ector((int)(position.X + (float)(width / 2) - (float)(tileRangeX * 16)), (int)(position.Y + (float)(height / 2) - (float)(tileRangeY * 16)), tileRangeX * 16 * 2, tileRangeY * 16 * 2);
                    try
                    {
                        bool flag17 = false;
                        if (Main.sign[sign] == null)
{
                            flag17 = true;
                        }
                        if (!flag17)
{
                            val = new Rectangle(Main.sign[sign].x * 16, Main.sign[sign].y * 16, 32, 32);
                            if (!((Rectangle)(ref val)).Intersects(value3))
{
                                flag17 = true;
                            }
                        }
                        if (flag17)
{
                            SoundEngine.PlaySound(11);
                            sign = -1;
                            Main.editSign = false;
                            Main.npcChatText = "";
                        }
                    }
                    catch
                    {
                        SoundEngine.PlaySound(11);
                        sign = -1;
                        Main.editSign = false;
                        Main.npcChatText = "";
                    }
                }
                if (Main.editSign)
                {
                    if (sign == -1)
                    {
                        Main.editSign = false;
                    }
                    else
                    {
                        Main.InputTextSign();
                    }
                }
                else if (Main.editChest)
                {
                    Main.InputTextChest();
                    if (Main.player[Main.myPlayer].chest == -1)
                    {
                        Main.editChest = false;
                    }
                }
                if (mount.Active && mount.Cart && ((Vector2)(ref velocity)).Length() > 4f)
                {
                    Rectangle rectangle2 = default(Rectangle);
                    ((Rectangle)(ref rectangle2))._002Ector((int)position.X, (int)position.Y, width, height);
                    if (velocity.X < -1f)
                    {
                        rectangle2.X -= 15;
                    }
                    if (velocity.X > 1f)
                    {
                        rectangle2.Width += 15;
                    }
                    if (velocity.X < -10f)
                    {
                        rectangle2.X -= 10;
                    }
                    if (velocity.X > 10f)
                    {
                        rectangle2.Width += 10;
                    }
                    if (velocity.Y < -1f)
                    {
                        rectangle2.Y -= 10;
                    }
                    if (velocity.Y > 1f)
                    {
                        rectangle2.Height += 10;
                    }
                    for (int num89 = 0; num89 < 200; num89++)
                    {
                        if (Main.npc[num89].active && !Main.npc[num89].dontTakeDamage && !Main.npc[num89].friendly && Main.npc[num89].immune[i] == 0 && CanNPCBeHitByPlayerOrPlayerProjectile(Main.npc[num89]) && ((Rectangle)(ref rectangle2)).Intersects(new Rectangle((int)Main.npc[num89].position.X, (int)Main.npc[num89].position.Y, Main.npc[num89].width, Main.npc[num89].height)))
{
                            float num91 = DamageClassLoader.DamageClasses.Select((DamageClass t) => GetTotalCritChance(t)).Max();
                            bool crit = false;
                            if ((float)Main.rand.Next(1, 101) <= num91)
{
                                crit = true;
                            }
                            float currentSpeed = ((Vector2)(ref velocity)).Length() / maxRunSpeed;
                            GetMinecartDamage(currentSpeed, out var damage2, out var knockback);
                            int num92 = 1;
                            if (velocity.X < 0f)
{
                                num92 = -1;
                            }
                            if (Main.npc[num89].knockBackResist < 1f && Main.npc[num89].knockBackResist > 0f)
{
                                knockback /= Main.npc[num89].knockBackResist;
                            }
                            if (whoAmI == Main.myPlayer)
{
                                ApplyDamageToNPC(Main.npc[num89], damage2, knockback, num92, crit);
                            }
                            Main.npc[num89].immune[i] = 30;
                            if (!Main.npc[num89].active)
{
                                AchievementsHelper.HandleSpecialEvent(this, 9);
                            }
                        }
                    }
                }
                Update_NPCCollision();
                if (!shimmering)
                {
                    Collision.HurtTile hurtTile = GetHurtTile();
                    if (hurtTile.type >= 0)
                    {
                        ApplyTouchDamage(hurtTile.type, hurtTile.x, hurtTile.y);
                    }
                }
                TryToShimmerUnstuck();
            }
            if (controlRight)
            {
                releaseRight = false;
            }
            else
            {
                releaseRight = true;
                rightTimer = 7;
            }
            if (controlLeft)
            {
                releaseLeft = false;
            }
            else
            {
                releaseLeft = true;
                leftTimer = 7;
            }
            releaseDown = !controlDown;
            if (rightTimer > 0)
            {
                rightTimer--;
            }
            else if (controlRight)
            {
                rightTimer = 7;
            }
            if (leftTimer > 0)
            {
                leftTimer--;
            }
            else if (controlLeft)
            {
                leftTimer = 7;
            }
            GrappleMovement();
            StickyMovement();
            CheckDrowning();
            if (gravDir == -1f)
            {
                waterWalk = false;
                waterWalk2 = false;
            }
            int num93 = height;
            if (waterWalk)
            {
                num93 -= 6;
            }
            bool flag18 = false;
            if (!shimmering)
            {
                flag18 = Collision.LavaCollision(position, width, num93);
            }
            if (flag18)
            {
                if (!lavaImmune && Main.myPlayer == i && hurtCooldowns[4] <= 0)
                {
                    if (lavaTime > 0)
                    {
                        lavaTime--;
                    }
                    else
                    {
                        int num94 = 80;
                        int num95 = 420;
                        if (Main.remixWorld)
{
                            num94 = 200;
                            num95 = 630;
                        }
                        if (!ashWoodBonus || !lavaRose)
{
                            if (ashWoodBonus)
{
                                if (Main.remixWorld)
{
                                    num94 = 145;
                                }
                                num94 /= 2;
                                num95 -= 210;
                            }
                            if (lavaRose)
{
                                num94 -= 45;
                                num95 -= 210;
                            }
                            if (num94 > 0)
{
                                Hurt(PlayerDeathReason.ByOther(2), num94, 0, pvp: false, quiet: false, Crit: false, 4);
                            }
                            if (num95 > 0)
{
                                AddBuff(24, num95);
                            }
                        }
                    }
                }
                lavaWet = true;
            }
            else
            {
                lavaWet = false;
                if (lavaTime < lavaMax)
                {
                    lavaTime++;
                }
            }
            if (lavaTime > lavaMax)
            {
                lavaTime = lavaMax;
            }
            if (waterWalk2 && !waterWalk)
            {
                num93 -= 6;
            }
            bool num114 = Collision.WetCollision(position, width, height);
            bool flag19 = Collision.honey;
            bool shimmer = Collision.shimmer;
            if (shimmer)
            {
                shimmerWet = true;
                if (whoAmI == Main.myPlayer && !shimmerImmune && !shimmerUnstuckHelper.ShouldUnstuck)
                {
                    int num96 = (int)(base.Center.X / 16f);
                    int num97 = (int)((position.Y + 1f) / 16f);
                    if (Main.tile[num96, num97] != null && Main.tile[num96, num97].shimmer() && Main.tile[num96, num97].liquid >= 0 && position.Y / 16f < (float)Main.UnderworldLayer)
                    {
                        AddBuff(353, 60);
                    }
                }
            }
            if (flag19 && !shimmering)
            {
                AddBuff(48, 1800);
                honeyWet = true;
            }
            if (num114)
            {
                if ((onFire || onFire3) && !lavaWet)
                {
                    for (int num98 = 0; num98 < maxBuffs; num98++)
                    {
                        int num99 = buffType[num98];
                        if (num99 == 24 || num99 == 323)
{
                            DelBuff(num98);
                        }
                    }
                }
                if (!wet)
                {
                    if (wetCount == 0)
                    {
                        wetCount = 10;
                        if (!shimmering)
{
                            if (!flag18)
{
                                if (shimmerWet)
{
                                    for (int num101 = 0; num101 < 50; num101++)
{
                                        int num102 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2)), width + 12, 24, 308);
                                        Main.dust[num102].velocity.Y -= 4f;
                                        Main.dust[num102].velocity.X *= 2.5f;
                                        Main.dust[num102].scale = 0.8f;
                                        Main.dust[num102].noGravity = true;
                                        switch (Main.rand.Next(6))
{
                                        case 0:
                                            Main.dust[num102].color = new Color(255, 255, 210);
                                            break;
                                        case 1:
                                            Main.dust[num102].color = new Color(190, 245, 255);
                                            break;
                                        case 2:
                                            Main.dust[num102].color = new Color(255, 150, 255);
                                            break;
                                        default:
                                            Main.dust[num102].color = new Color(190, 175, 255);
                                            break;
                                        }
                                    }
                                    SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 2);
                                }
                                else if (honeyWet)
{
                                    for (int num103 = 0; num103 < 20; num103++)
{
                                        int num104 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 152);
                                        Main.dust[num104].velocity.Y -= 1f;
                                        Main.dust[num104].velocity.X *= 2.5f;
                                        Main.dust[num104].scale = 1.3f;
                                        Main.dust[num104].alpha = 100;
                                        Main.dust[num104].noGravity = true;
                                    }
                                    SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                                }
                                else
{
                                    for (int num105 = 0; num105 < 50; num105++)
{
                                        int num106 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, Dust.dustWater());
                                        Main.dust[num106].velocity.Y -= 3f;
                                        Main.dust[num106].velocity.X *= 2.5f;
                                        Main.dust[num106].scale = 0.8f;
                                        Main.dust[num106].alpha = 100;
                                        Main.dust[num106].noGravity = true;
                                    }
                                    SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 0);
                                }
                            }
                            else
{
                                for (int num107 = 0; num107 < 20; num107++)
{
                                    int num108 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 35);
                                    Main.dust[num108].velocity.Y -= 1.5f;
                                    Main.dust[num108].velocity.X *= 2.5f;
                                    Main.dust[num108].scale = 1.3f;
                                    Main.dust[num108].alpha = 100;
                                    Main.dust[num108].noGravity = true;
                                }
                                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                            }
                        }
                    }
                    wet = true;
                    if (ShouldFloatInWater)
                    {
                        velocity.Y /= 2f;
                        if (velocity.Y > 3f)
{
                            velocity.Y = 3f;
                        }
                    }
                }
            }
            else if (wet)
            {
                wet = false;
                if (jump > jumpHeight / 5 && wetSlime == 0)
                {
                    jump = jumpHeight / 5;
                }
                if (wetCount == 0)
                {
                    wetCount = 10;
                    if (!shimmering)
                    {
                        if (!lavaWet)
{
                            if (shimmerWet)
{
                                for (int num109 = 0; num109 < 50; num109++)
{
                                    int num110 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2)), width + 12, 24, 308);
                                    Main.dust[num110].velocity.Y -= 4f;
                                    Main.dust[num110].velocity.X *= 2.5f;
                                    Main.dust[num110].scale = 0.75f;
                                    Main.dust[num110].noGravity = true;
                                    switch (Main.rand.Next(6))
{
                                    case 0:
                                        Main.dust[num110].color = new Color(255, 255, 210);
                                        break;
                                    case 1:
                                        Main.dust[num110].color = new Color(190, 245, 255);
                                        break;
                                    case 2:
                                        Main.dust[num110].color = new Color(255, 150, 255);
                                        break;
                                    default:
                                        Main.dust[num110].color = new Color(190, 175, 255);
                                        break;
                                    }
                                }
                                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 3);
                            }
                            else if (honeyWet)
{
                                for (int num11 = 0; num11 < 20; num11++)
{
                                    int num12 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 152);
                                    Main.dust[num12].velocity.Y -= 1f;
                                    Main.dust[num12].velocity.X *= 2.5f;
                                    Main.dust[num12].scale = 1.3f;
                                    Main.dust[num12].alpha = 100;
                                    Main.dust[num12].noGravity = true;
                                }
                                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                            }
                            else
{
                                for (int num13 = 0; num13 < 50; num13++)
{
                                    int num14 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2)), width + 12, 24, Dust.dustWater());
                                    Main.dust[num14].velocity.Y -= 4f;
                                    Main.dust[num14].velocity.X *= 2.5f;
                                    Main.dust[num14].scale = 0.8f;
                                    Main.dust[num14].alpha = 100;
                                    Main.dust[num14].noGravity = true;
                                }
                                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 0);
                            }
                        }
                        else
{
                            for (int num15 = 0; num15 < 20; num15++)
{
                                int num16 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 35);
                                Main.dust[num16].velocity.Y -= 1.5f;
                                Main.dust[num16].velocity.X *= 2.5f;
                                Main.dust[num16].scale = 1.3f;
                                Main.dust[num16].alpha = 100;
                                Main.dust[num16].noGravity = true;
                            }
                            SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                        }
                    }
                }
            }
            if (!flag19)
            {
                honeyWet = false;
            }
            if (!shimmer)
            {
                shimmerWet = false;
            }
            if (!wet)
            {
                lavaWet = false;
                honeyWet = false;
                shimmerWet = false;
            }
            if (wetCount > 0)
            {
                wetCount--;
            }
            if (wetSlime > 0)
            {
                wetSlime--;
            }
            if (wet && mount.Active)
            {
                switch (mount.Type)
                {
                case 5:
                case 7:
                    if (whoAmI == Main.myPlayer)
                    {
                        mount.Dismount(this);
                    }
                    break;
                case 3:
                case 50:
                    wetSlime = 30;
                    if (velocity.Y > 2f)
                    {
                        velocity.Y *= 0.9f;
                    }
                    velocity.Y -= 0.5f;
                    if (velocity.Y < -4f)
                    {
                        velocity.Y = -4f;
                    }
                    break;
                }
            }
            if (Main.expertMode && ZoneSnow && wet && !lavaWet && !honeyWet && !arcticDivingGear && environmentBuffImmunityTimer == 0)
            {
                AddBuff(46, 150);
            }
            float num17 = 1f + Math.Abs(velocity.X) / 3f;
            if (gfxOffY > 0f)
            {
                gfxOffY -= num17 * stepSpeed;
                if (gfxOffY < 0f)
                {
                    gfxOffY = 0f;
                }
            }
            else if (gfxOffY < 0f)
            {
                gfxOffY += num17 * stepSpeed;
                if (gfxOffY > 0f)
                {
                    gfxOffY = 0f;
                }
            }
            if (gfxOffY > 32f)
            {
                gfxOffY = 32f;
            }
            if (gfxOffY < -32f)
            {
                gfxOffY = -32f;
            }
            if (Main.myPlayer == i)
            {
                if (!iceSkate)
                {
                    CheckIceBreak();
                }
                CheckCrackedBrickBreak();
            }
            if (!shimmering)
            {
                SlopeDownMovement();
                bool flag20 = mount.Type == 7 || mount.Type == 8 || mount.Type == 12 || mount.Type == 44 || mount.Type == 49;
                if (velocity.Y == gravity && (!mount.Active || (!mount.Cart && mount.Type != 48 && !flag20)))
                {
                    Collision.StepDown(ref position, ref velocity, width, height, ref stepSpeed, ref gfxOffY, (int)gravDir, waterWalk || waterWalk2);
                }
                if (gravDir == -1f)
                {
                    if ((carpetFrame != -1 || velocity.Y <= gravity) && !controlUp)
                    {
                        Collision.StepUp(ref position, ref velocity, width, height, ref stepSpeed, ref gfxOffY, (int)gravDir, controlUp);
                    }
                }
                else if ((carpetFrame != -1 || velocity.Y >= gravity) && !controlDown && !mount.Cart && !flag20 && grappling[0] == -1)
                {
                    Collision.StepUp(ref position, ref velocity, width, height, ref stepSpeed, ref gfxOffY, (int)gravDir, controlUp);
                }
            }
            oldPosition = position;
            oldDirection = direction;
            bool falling = false;
            if (velocity.Y > gravity)
            {
                falling = true;
            }
            if (velocity.Y < 0f - gravity)
            {
                falling = true;
            }
            Vector2 vector3 = velocity;
            slideDir = 0;
            bool ignorePlats = false;
            bool fallThrough = controlDown;
            if ((gravDir == -1f) | (mount.Active && (mount.Cart || mount.Type == 12 || mount.Type == 7 || mount.Type == 8 || mount.Type == 23 || mount.Type == 44 || mount.Type == 48)) | GoingDownWithGrapple | pulley)
            {
                ignorePlats = true;
                fallThrough = true;
            }
            bool flag21 = onTrack;
            onTrack = false;
            bool flag22 = false;
            if (mount.Active && mount.Cart)
            {
                fartKartCloudDelay = Math.Max(0, fartKartCloudDelay - 1);
                float num18 = ((ignoreWater || merman) ? 1f : (shimmerWet ? 0.25f : (honeyWet ? 0.25f : ((!wet) ? 1f : 0.5f))));
                velocity *= num18;
                DelegateMethods.Minecart.rotation = fullRotation;
                DelegateMethods.Minecart.rotationOrigin = fullRotationOrigin;
                BitsByte bitsByte = Minecart.TrackCollision(this, ref position, ref velocity, ref lastBoost, width, height, controlDown, controlUp, fallStart2, trackOnly: false, mount.Delegations);
                if (bitsByte[0])
                {
                    onTrack = true;
                    gfxOffY = Minecart.TrackRotation(this, ref fullRotation, position + velocity, width, height, controlDown, controlUp, mount.Delegations);
                    fullRotationOrigin = new Vector2((float)(width / 2), (float)height);
                }
                if (flag21 && !onTrack)
                {
                    mount.Delegations.MinecartJumpingSound(this, position, width, height);
                }
                if (bitsByte[1])
                {
                    if (controlLeft || controlRight)
                    {
                        if (cartFlip)
{
                            cartFlip = false;
                        }
                        else
{
                            cartFlip = true;
                        }
                    }
                    if (velocity.X > 0f)
                    {
                        direction = 1;
                    }
                    else if (velocity.X < 0f)
                    {
                        direction = -1;
                    }
                    mount.Delegations.MinecartBumperSound(this, position, width, height);
                }
                velocity /= num18;
                if (bitsByte[3] && whoAmI == Main.myPlayer)
                {
                    flag22 = true;
                }
                if (bitsByte[2])
                {
                    cartRampTime = (int)(Math.Abs(velocity.X) / mount.RunSpeed * 20f);
                }
                if (bitsByte[4])
                {
                    trackBoost -= 4f;
                }
                if (bitsByte[5])
                {
                    trackBoost += 4f;
                }
            }
            bool flag24 = whoAmI == Main.myPlayer && !mount.Active;
            Vector2 vector4 = position;
            if (vortexDebuff)
            {
                velocity.Y = velocity.Y * 0.8f + (float)Math.Cos(base.Center.X % 120f / 120f * ((float)Math.PI * 2f)) * 5f * 0.2f;
            }
            PlayerLoader.PreUpdateMovement(this);
            if (tongued)
            {
                position += velocity;
                flag24 = false;
            }
            else if (shimmerWet || shimmering)
            {
                ShimmerCollision(fallThrough, ignorePlats, shimmering);
            }
            else if (honeyWet && !ignoreWater)
            {
                HoneyCollision(fallThrough, ignorePlats);
            }
            else if (wet && !merman && !ignoreWater && !trident)
            {
                WaterCollision(fallThrough, ignorePlats);
            }
            else
            {
                DryCollision(fallThrough, ignorePlats);
                if (mount.Active && mount.IsConsideredASlimeMount && velocity.Y != 0f && !SlimeDontHyperJump)
                {
                    Vector2 vector5 = velocity;
                    velocity.X = 0f;
                    DryCollision(fallThrough, ignorePlats);
                    velocity.X = vector5.X;
                }
                if (mount.Active && mount.Type == 43 && velocity.Y != 0f)
                {
                    Vector2 vector6 = velocity;
                    velocity.X = 0f;
                    DryCollision(fallThrough, ignorePlats);
                    velocity.X = vector6.X;
                }
            }
            UpdateTouchingTiles();
            TryBouncingBlocks(falling);
            TryLandingOnDetonator();
            if (!shimmering && !tongued)
            {
                SlopingCollision(fallThrough, ignorePlats);
                if (!isLockedToATile)
                {
                    Collision.StepConveyorBelt(this, gravDir);
                }
            }
            if (flag24 && velocity.Y == 0f)
            {
                AchievementsHelper.HandleRunning(Math.Abs(position.X - vector4.X));
            }
            if (flag22)
            {
                NetMessage.SendData(13, -1, -1, null, whoAmI);
                Minecart.HitTrackSwitch(new Vector2(position.X, position.Y), width, height);
            }
            if (vector3.X != velocity.X)
            {
                if (vector3.X < 0f)
                {
                    slideDir = -1;
                }
                else if (vector3.X > 0f)
                {
                    slideDir = 1;
                }
            }
            if (gravDir == 1f && Collision.up)
            {
                velocity.Y = 0.01f;
                if (!merman)
                {
                    jump = 0;
                }
            }
            else if (gravDir == -1f && Collision.down)
            {
                velocity.Y = -0.01f;
                if (!merman)
                {
                    jump = 0;
                }
            }
            if (velocity.Y == 0f && grappling[0] == -1)
            {
                FloorVisuals(falling);
            }
            if (whoAmI == Main.myPlayer && !shimmering)
            {
                Collision.SwitchTiles(position, width, height, oldPosition, 1);
            }
            PressurePlateHelper.UpdatePlayerPosition(this);
            BordersMovement();
            numMinions = 0;
            slotsMinions = 0f;
            if (Main.netMode != 2 && mount.Type != 8)
            {
                ItemCheck_ManageRightClickFeatures();
            }
            ItemCheckWrapped(i);
            PlayerFrame();
            if (mount.Type == 8)
            {
                mount.UseDrill(this);
            }
            if (statLife > statLifeMax2)
            {
                statLife = statLifeMax2;
            }
            if (statMana > statManaMax2)
            {
                statMana = statManaMax2;
            }
            grappling[0] = -1;
            grapCount = 0;
            UpdateReleaseUseTile();
            UpdateAdvancedShadows();
            PlayerLoader.PostUpdate(this);
        }
    }
References Terraria.Player._framesLeftEligibleForDeadmansChestDeathAchievement, Terraria.Player._portalPhysicsTime, Terraria.Player._quickGrappleCooldown, Terraria.Player._timeSinceLastImmuneGet, Terraria.Mount.AbilityRecovery(), Terraria.Mount.Acceleration, Terraria.Player.accFlipper, Terraria.Player.accMerman, Terraria.Player.accRunSpeed, Terraria.Graphics.Capture.CaptureManager.Active, Terraria.Entity.active, Terraria.Mount.Active, Terraria.Player.AddBuff(), Terraria.Lighting.AddLight(), Terraria.Player.AdjTiles(), Terraria.Player.AdjustRemainingPotionSickness(), Terraria.Player.afkCounter, Terraria.Player.aggro, Terraria.Player.allDamage, Terraria.Player.allKB, Terraria.Dust.alpha, Terraria.Player.AnyExtraJumpUsable(), Terraria.Player.ApplyDamageToNPC(), Terraria.Player.ApplyTouchDamage(), Terraria.Player.arcticDivingGear, Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.armor, Terraria.Player.ashWoodBonus, Terraria.Player.attackCD, Terraria.Player.autoJump, Terraria.Player.autoReuseAllWeapons, Terraria.Item.axe, Terraria.Player.beetleDefense, Terraria.Player.beetleOffense, Terraria.Player.behindBackWall, Terraria.NPC.BigMimicSummonCheck(), Terraria.Mount.BlockExtraJumps, Terraria.Main.blockInput, Terraria.Player.body, Terraria.Item.bodySlot, Terraria.Player.boneGloveTimer, Terraria.Player.BordersMovement(), Terraria.NPC.brainOfGravity, Terraria.Player.brokenArmor, Terraria.ModLoader.BuffLoader.BuffCount, Terraria.Player.buffImmune, Terraria.Player.buffTime, Terraria.Player.buffType, Terraria.DataStructures.PlayerDeathReason.ByOther(), Terraria.Main.cameraX, Terraria.Player.canCarpet, Terraria.Player.CancelAllJumpVisualEffects(), Terraria.Mount.CanFly(), Terraria.Mount.CanHover(), Terraria.Player.CanMoveForwardOnRope(), Terraria.Player.CanNPCBeHitByPlayerOrPlayerProjectile(), Terraria.Player.canRocket, Terraria.Player.CapAttackSpeeds(), Terraria.Player.carpet, Terraria.Player.carpetFrame, Terraria.Player.carpetFrameCounter, Terraria.Player.CarpetMovement(), Terraria.Player.carpetTime, Terraria.Mount.Cart, Terraria.Player.cartFlip, Terraria.Player.cartRampTime, Terraria.Entity.Center, Terraria.Player.SelectionRadial.ChangeSelection(), Terraria.Player.chatOverhead, Terraria.Player.CheckCrackedBrickBreak(), Terraria.Player.CheckDrowning(), Terraria.Player.CheckIceBreak(), Terraria.Main.chest, Terraria.Player.chest, Terraria.Player.chilled, Terraria.Player.CircularRadial, Terraria.Player.ClearBuff(), Terraria.Dust.color, Terraria.Player.confused, Terraria.Player.ConsumeAllExtraJumps(), Terraria.ModLoader.ExtraJumpLoader.ConsumeAndStopUnavailableJumps(), Terraria.Player.controlCreativeMenu, Terraria.Player.controlDown, Terraria.Player.controlDownHold, Terraria.Player.controlHook, Terraria.Player.controlInv, Terraria.Player.controlJump, Terraria.Player.controlLeft, Terraria.Player.controlMount, Terraria.Player.controlQuickHeal, Terraria.Player.controlQuickMana, Terraria.Player.controlRight, Terraria.Player.controlSmart, Terraria.Player.controlThrow, Terraria.Player.controlTorch, Terraria.Player.controlUp, Terraria.Player.controlUseItem, Terraria.Player.controlUseTile, Terraria.DataStructures.PlayerMovementAccsCache.CopyFrom(), Terraria.GameInput.TriggersSet.CopyInto(), Terraria.GameInput.TriggersSet.CopyIntoDuringChat(), Terraria.Item.createWall, Terraria.Player.creativeGodMode, Terraria.Player.crystalLeafCooldown, Terraria.GameInput.TriggersPack.Current, Terraria.GameInput.PlayerInput.SettingsForUI.CurrentCursorMode, Terraria.Player.cWings, Terraria.ModLoader.DamageClassLoader.DamageClasses, Terraria.Player.DashMovement(), Terraria.Mount.DashSpeed, Terraria.Main.dayTime, Terraria.Player.dazed, Terraria.Player.dead, Terraria.Player.defaultGravity, Terraria.Player.delayUseItem, Terraria.Player.DelBuff(), Terraria.Mount.Delegations, Terraria.Player.desertBoots, Terraria.Entity.direction, Terraria.UI.ItemSlot.Options.DisableLeftShiftTrashCan, Terraria.Player.discountAvailable, Terraria.Player.discountEquipped, Terraria.Mount.Dismount(), Terraria.Main.dontStarveWorld, Terraria.NPC.dontTakeDamage, Terraria.Player.doorHelper, Terraria.Player.DoubleJumpVisuals(), Terraria.Player.doubleTapCardinalTimer, Terraria.Collision.down, Terraria.Player.downedDD2EventAnyDifficulty, Terraria.GameContent.Events.DD2Event.DownedInvasionAnyDifficulty, Terraria.Player.DpadRadial, Terraria.Main.drawingPlayerChat, Terraria.Player.dropItemCheck(), Terraria.Player.DryCollision(), Terraria.Main.dust, Terraria.Dust.dustWater(), Terraria.Main.editChest, Terraria.Main.editSign, Terraria.Player.emoteTime, Terraria.Player.empressBrooch, Terraria.DataStructures.GameModeData.EnemyDamageMultiplier, Terraria.Player.environmentBuffImmunityTimer, Terraria.Player.equippedWings, Terraria.Main.expertMode, Terraria.Player.extraFall, Terraria.Player.eyeHelper, Terraria.Dust.fadeIn, Terraria.Mount.FallDamage, Terraria.Player.fallStart, Terraria.Player.fallStart2, Terraria.Player.fartKartCloudDelay, Terraria.Mount.FatigueRecovery(), Terraria.GameContent.Events.DD2Event.FindArenaHitbox(), Terraria.Player.FindPulley(), Terraria.Player.flapSound, Terraria.Mount.Flight(), Terraria.Player.FloorVisuals(), Terraria.Main.focusRecipe, Terraria.Player.forcedGravity, Terraria.Player.forceMerman, Terraria.Player.forceWerewolf, Terraria.NPC.freeCake, Terraria.NPC.friendly, Terraria.Player.frozen, Terraria.Player.fullRotation, Terraria.Player.fullRotationOrigin, Terraria.Main.GameModeInfo, Terraria.Player.GamepadEnableGrappleCooldown(), Terraria.Projectile.GasTrapCheck(), Terraria.Player.gem, Terraria.Player.gemCount, Terraria.Player.GetHurtTile(), Terraria.Player.GetKnockback(), Terraria.Player.GetMinecartDamage(), Terraria.Player.GetMouseScrollDelta(), Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.DataStructures.PlayerInteractionAnchor.GetTileEntity(), Terraria.Player.GetTotalCritChance(), Terraria.Player.gfxOffY, Terraria.Player.ghost, Terraria.Player.Ghost(), Terraria.Player.ghostDmg, Terraria.Player.GoingDownWithGrapple, Terraria.Player.GrabItems(), Terraria.Player.grapCount, Terraria.Player.GrappleMovement(), Terraria.Player.grappling, Terraria.Player.gravControl, Terraria.Player.gravControl2, Terraria.Player.gravDir, Terraria.Player.gravity, Terraria.GameContent.TextureAssets.HairStyleBack, Terraria.Main.hairWindow, Terraria.Item.hammer, Terraria.Player.HandleBeingInChestRange(), Terraria.Player.HandleHotbar(), Terraria.GameContent.Achievements.AchievementsHelper.HandleRunning(), Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.SceneMetrics.hasBanner, Terraria.SceneMetrics.HasCampfire, Terraria.SceneMetrics.HasCatBast, Terraria.Main.hasFocus, Terraria.SceneMetrics.HasHeartLantern, Terraria.Player.HasItem(), Terraria.Player.hasLucyTheAxe, Terraria.Player.hasMagiluminescence, Terraria.SceneMetrics.HasStarInBottle, Terraria.SceneMetrics.HasSunflower, Terraria.Player.head, Terraria.Item.headSlot, Terraria.Entity.height, Terraria.Player.heldProj, Terraria.Player.hideMerman, Terraria.Player.hideWolf, Terraria.Minecart.HitTrackSwitch(), Terraria.Player.holdDownCardinalTimer, Terraria.Collision.honey, Terraria.Player.HoneyCollision(), Terraria.Entity.honeyWet, Terraria.Player.HorizontalMovement(), Terraria.GameInput.TriggersSet.Hotbar1, Terraria.GameInput.TriggersSet.Hotbar10, Terraria.GameInput.TriggersSet.Hotbar2, Terraria.GameInput.TriggersSet.Hotbar3, Terraria.GameInput.TriggersSet.Hotbar4, Terraria.GameInput.TriggersSet.Hotbar5, Terraria.GameInput.TriggersSet.Hotbar6, Terraria.GameInput.TriggersSet.Hotbar7, Terraria.GameInput.TriggersSet.Hotbar8, Terraria.GameInput.TriggersSet.Hotbar9, Terraria.GameInput.TriggersSet.HotbarMinus, Terraria.GameInput.TriggersSet.HotbarPlus, Terraria.GameInput.PlayerInput.MiscSettingsTEMP.HotbarRadialShouldBeUsed, Terraria.Mount.Hover(), Terraria.Player.Settings.HoverControl, Terraria.Player.Hurt(), Terraria.Player.hurtCooldowns, Terraria.Player.iceSkate, Terraria.Player.ignoreWater, Terraria.NPC.immune, Terraria.Player.immune, Terraria.Player.infernoCounter, Terraria.Main.InputTextChest(), Terraria.Main.InputTextSign(), Terraria.GameContent.Creative.CreativePowerManager.Instance, Terraria.Graphics.Capture.CaptureManager.Instance, Terraria.Main.instance, Terraria.Player.instantMovementAccumulatedThisFrame, Terraria.DataStructures.PlayerInteractionAnchor.InUse, Terraria.Player.inventory, Terraria.Player.invis, Terraria.Mount.IsConsideredASlimeMount, Terraria.Player.isControlledByFilm, Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.IsEnabledForPlayer(), Terraria.Player.isLockedToATile, Terraria.Player.isOperatingAnotherEntity, Terraria.WorldGen.IsRope(), Terraria.Player.IsStandingStillForSpecialEffects, Terraria.Player.IsVoidVaultEnabled, Terraria.ID.SoundID.Item13, Terraria.ID.SoundID.Item24, Terraria.ID.SoundID.Item32, Terraria.ID.SoundID.Item8, Terraria.Player.itemAnimation, Terraria.Player.ItemCheck_ManageRightClickFeatures(), Terraria.Player.ItemCheckWrapped(), Terraria.Player.ItemTimeIsZero, Terraria.Player.jump, Terraria.Player.jumpHeight, Terraria.Player.JumpMovement(), Terraria.Player.jumpSpeed, Terraria.Player.justJumped, Terraria.GameInput.TriggersPack.JustReleased, Terraria.Player.kbBuff, Terraria.Player.KeyDoubleTap(), Terraria.Player.KeyHoldDown(), Terraria.Main.keyState, Terraria.NPC.knockBackResist, Terraria.Player.lastBoost, Terraria.Player.lastChest, Terraria.Player.lastStoned, Terraria.Player.lastTileRangeX, Terraria.Player.lastTileRangeY, Terraria.Collision.LavaCollision(), Terraria.Player.lavaImmune, Terraria.Player.lavaMax, Terraria.Player.lavaRose, Terraria.Player.lavaTime, Terraria.Entity.lavaWet, Terraria.Player.leftTimer, Terraria.Player.legs, Terraria.Item.legSlot, Terraria.Player.lifeSteal, Terraria.Player.LocalInputCache, Terraria.Player.LookForTileInteractions(), Terraria.Player.magicDamage, Terraria.Player.manaRegenCount, Terraria.Player.manaSick, Terraria.Player.manaSickReduction, Terraria.Player.mapAlphaDown, Terraria.Player.mapAlphaUp, Terraria.Main.mapFullscreen, Terraria.Player.mapFullScreen, Terraria.Main.mapFullscreenScale, Terraria.Main.mapStyle, Terraria.Player.mapStyle, Terraria.Player.mapZoomIn, Terraria.Player.mapZoomOut, Terraria.Player.maxBuffs, Terraria.Player.maxFallSpeed, Terraria.Player.maxRegenDelay, Terraria.Player.maxRunSpeed, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Player.maxTurrets, Terraria.Player.maxTurretsOld, Terraria.ModLoader.DamageClass.Melee, Terraria.Player.meleeCrit, Terraria.Player.meleeDamage, Terraria.Player.merman, Terraria.Mount.MountDelegatesData.MinecartBumperSound, Terraria.Mount.MountDelegatesData.MinecartJumpingSound, Terraria.Player.mount, Terraria.Player.MountFishronSpecial, Terraria.Player.MountFishronSpecialCounter, Terraria.GameInput.PlayerInput.MouseInModdedUI, Terraria.Player.mouseInterface, Terraria.Main.MouseScreen, Terraria.Main.mouseY, Terraria.Player.movementAbilitiesCache, Terraria.Player.moveSpeed, Terraria.Item.mushroomDelay, Terraria.Player.mushroomDelayTime, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Player.noBuilding, Terraria.Player.noFallDmg, Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Dust.noLightEmittence, Terraria.Player.nonTorch, Terraria.Main.npc, Terraria.Main.npcShop, Terraria.Main.numAvailableRecipes, Terraria.Player.numMinions, Terraria.TileObject.objectPreview, Terraria.Entity.oldDirection, Terraria.Entity.oldPosition, Terraria.Player.onFire, Terraria.Player.onFire3, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Player.onHitDodge, Terraria.DataStructures.TileEntity.OnPlayerUpdate(), Terraria.Minecart.OnTrack(), Terraria.Player.onTrack, Terraria.Player.onWrongGround, Terraria.Player.outOfRange, Terraria.Player.ownedLargeGems, Terraria.Player.ownedProjectileCounts, Terraria.DataStructures.PlayerMovementAccsCache.PasteInto(), Terraria.SceneMetrics.PeaceCandleCount, Terraria.Player.petalTimer, Terraria.Player.PhilosopherStoneDurationMultiplier, Terraria.Player.pickSpeed, Terraria.Main.player, Terraria.Player.PlayerFrame(), Terraria.Main.playerInventory, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.poisoned, Terraria.Player.PortalPhysicsEnabled, Terraria.Player.portalPhysicsFlag, Terraria.Entity.position, Terraria.ModLoader.PlayerLoader.PostUpdate(), Terraria.ModLoader.PlayerLoader.PostUpdateBuffs(), Terraria.ModLoader.PlayerLoader.PostUpdateEquips(), Terraria.ModLoader.PlayerLoader.PostUpdateMiscEffects(), Terraria.ModLoader.PlayerLoader.PostUpdateRunSpeeds(), Terraria.Item.potionDelay, Terraria.Player.potionDelay, Terraria.Player.potionDelayTime, Terraria.Player.powerrun, Terraria.ModLoader.PlayerLoader.PreUpdate(), Terraria.ModLoader.PlayerLoader.PreUpdateBuffs(), Terraria.ModLoader.PlayerLoader.PreUpdateMovement(), Terraria.Player.pStone, Terraria.Player.pulley, Terraria.Player.pulleyDir, Terraria.Player.pulleyFrame, Terraria.Player.pulleyFrameCounter, Terraria.Player.PurgeDD2EnergyCrystals(), Terraria.Player.QuickBuff(), Terraria.Player.QuickGrapple(), Terraria.Player.QuickHeal(), Terraria.Player.QuickMana(), Terraria.Player.QuickMount(), Terraria.Player.QuicksRadial, Terraria.GameInput.TriggersSet.RadialQuickbar, Terraria.Main.rand, Terraria.ModLoader.DamageClass.Ranged, Terraria.Player.rangedCrit, Terraria.Player.rangedDamage, Terraria.Main.recBigList, Terraria.Main.recStart, Terraria.Player.RefreshDoubleJumps(), Terraria.Player.releaseCreativeMenu, Terraria.Player.releaseDown, Terraria.Player.releaseHook, Terraria.Player.releaseInventory, Terraria.Player.releaseJump, Terraria.Player.releaseLeft, Terraria.Player.releaseMapFullscreen, Terraria.Player.releaseMapStyle, Terraria.Player.releaseMount, Terraria.Player.releaseQuickHeal, Terraria.Player.releaseQuickMana, Terraria.Player.releaseRight, Terraria.Player.releaseSmart, Terraria.Player.releaseThrow, Terraria.Player.releaseUp, Terraria.Main.remixWorld, Terraria.DataStructures.TileObjectPreviewData.Reset(), Terraria.Player.ResetControls(), Terraria.Player.ResetEffects(), Terraria.Mount.ResetFlightTime(), Terraria.Player.ResetFloorFlags(), Terraria.Player.ResetProjectileCaches(), Terraria.Player.ResetVisibleAccessories(), Terraria.Player.ResizeHitbox(), Terraria.Item.restorationDelay, Terraria.Player.restorationDelayTime, Terraria.Player.reuseDelay, Terraria.Player.rightTimer, Terraria.Player.rocketBoots, Terraria.Player.RocketBootVisuals(), Terraria.Player.rocketDelay, Terraria.Player.rocketDelay2, Terraria.Player.rocketFrame, Terraria.Player.rocketRelease, Terraria.Player.rocketSoundDelay, Terraria.Player.rocketTime, Terraria.Player.rocketTimeMax, Terraria.Player.ropeCount, Terraria.Player.runAcceleration, Terraria.Player.runningOnSand, Terraria.Player.runSlowdown, Terraria.Player.runSoundDelay, Terraria.Mount.RunSpeed, Terraria.Player.sandStorm, Terraria.Dust.scale, Terraria.Main.SceneMetrics, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Graphics.Capture.CaptureManager.Scrolling(), Terraria.Main.sectionManager, Terraria.Player.SelectionRadial.SelectedBinding, Terraria.Player.selectedItem, Terraria.Player.selectItemOnNextUse, Terraria.NetMessage.SendData(), Terraria.ModLoader.PlayerLoader.SetControls(), Terraria.Item.SetDefaults(), Terraria.Player.setSolar, Terraria.Player.SetTalkNPC(), Terraria.Main.SettingsEnabled_AutoReuseAllItems, Terraria.Player.setVortex, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameInput.PlayerInput.SetZoom_World(), Terraria.Dust.shader, Terraria.Player.shadowArmor, Terraria.SceneMetrics.ShadowCandleCount, Terraria.Player.shadowDodge, Terraria.Player.shadowDodgeTimer, Terraria.Player.shieldRaised, Terraria.Collision.shimmer, Terraria.Player.ShimmerCollision(), Terraria.Player.shimmerImmune, Terraria.Player.shimmering, Terraria.Player.shimmerUnstuckHelper, Terraria.Entity.shimmerWet, Terraria.GameContent.Events.DD2Event.ShouldBlockBuilding(), Terraria.Player.ShouldDrawWingsThatAreAlwaysAnimated(), Terraria.Player.ShouldFloatInWater, Terraria.GameContent.ShimmerUnstuckHelper.ShouldUnstuck, Terraria.Player.shroomiteStealth, Terraria.Main.sign, Terraria.Player.sign, Terraria.Player.sitting, Terraria.Player.sleeping, Terraria.Player.slideDir, Terraria.Player.sliding, Terraria.Player.SlimeDontHyperJump, Terraria.Player.slippy, Terraria.Player.slippy2, Terraria.Player.SlopeDownMovement(), Terraria.Player.SlopingCollision(), Terraria.Player.slotsMinions, Terraria.Player.slow, Terraria.Player.slowFall, Terraria.Player.slowOgreSpit, Terraria.GameContent.SmartCursorHelper.SmartCursorLookup(), Terraria.Main.SmartCursorWanted_GamePad, Terraria.Main.SmartCursorWanted_Mouse, Terraria.Player.SmartInteractLookup(), Terraria.Player.snowBallLauncherInteractionCooldown, Terraria.Collision.SolidCollision(), Terraria.Player.soulDrain, Terraria.Player.starCloakCooldown, Terraria.Player.statDefense, Terraria.Player.statLife, Terraria.Player.statLifeMax2, Terraria.Player.statMana, Terraria.Player.statManaMax2, Terraria.Player.stealth, Terraria.Player.stealthTimer, Terraria.GameInput.PlayerInput.SteamDeckIsUsed, Terraria.Collision.StepConveyorBelt(), Terraria.Collision.StepDown(), Terraria.Player.stepSpeed, Terraria.Collision.StepUp(), Terraria.Player.sticky, Terraria.Player.StickyMovement(), Terraria.Player.stoned, Terraria.Player.StopVanityActions(), Terraria.Collision.SwitchTiles(), Terraria.Player.talkNPC, Terraria.Player.tankPet, Terraria.Player.tankPetReset, Terraria.Main.tile, Terraria.Player.tileEntityAnchor, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.WorldSections.TilesLoaded(), Terraria.Player.tileSpeed, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Player.OverheadMessage.timeLeft, Terraria.Player.timeSinceLastDashStarted, Terraria.Player.titaniumStormCooldown, Terraria.Player.ToggleCreativeMenu(), Terraria.Player.ToggleInv(), Terraria.Player.tongued, Terraria.Player.trackBoost, Terraria.Minecart.TrackCollision(), Terraria.Minecart.TrackRotation(), Terraria.Player.trapDebuffSource, Terraria.Player.trashItem, Terraria.Player.trident, Terraria.GameInput.PlayerInput.Triggers, Terraria.Player.TryBouncingBlocks(), Terraria.Player.TryingToHoverDown, Terraria.Player.TryingToHoverUp, Terraria.Player.tryKeepingHoveringDown, Terraria.Player.tryKeepingHoveringUp, Terraria.Player.TryLandingOnDetonator(), Terraria.Player.TryOpeningFullscreenMap(), Terraria.GameContent.LucyAxeMessage.TryPlayingIdleMessage(), Terraria.Player.TryPortalJumping(), Terraria.Player.TrySpawningFaelings(), Terraria.Player.TrySyncingInput(), Terraria.Player.TryToShimmerUnstuck(), Terraria.Player.TryToToggleSmartCursor(), Terraria.Item.TurnToAir(), Terraria.Dust.type, Terraria.Item.type, Terraria.Mount.Type, Terraria.NPC.type, Terraria.Main.UnderworldLayer, Terraria.Collision.up, Terraria.GameInput.LockOnHelper.Update(), Terraria.Player.SelectionRadial.Update(), Terraria.GameContent.DontStarveDarknessDamageDealer.Update(), Terraria.GameContent.DoorOpeningHelper.Update(), Terraria.GameContent.PlayerEyeHelper.Update(), Terraria.GameContent.ShimmerUnstuckHelper.Update(), Terraria.Player.Update_NPCCollision(), Terraria.Player.UpdateAdvancedShadows(), Terraria.Player.UpdateArmorLights(), Terraria.Player.UpdateArmorSets(), Terraria.Player.UpdateBiomes(), Terraria.Player.UpdateBuffs(), Terraria.Player.UpdateControlHolds(), Terraria.Player.UpdateDead(), Terraria.Mount.UpdateDrill(), Terraria.Player.UpdateDyes(), Terraria.Mount.UpdateEffects(), Terraria.Player.UpdateEquips(), Terraria.Player.UpdateHairDyeDust(), Terraria.ModLoader.ExtraJumpLoader.UpdateHorizontalSpeeds(), Terraria.Player.UpdateImmunity(), Terraria.Player.UpdateJumpHeight(), Terraria.Player.UpdateLifeRegen(), Terraria.Player.UpdateLuck(), Terraria.Player.UpdateManaRegen(), Terraria.Player.UpdateMaxTurrets(), Terraria.Player.UpdateMinionTarget(), Terraria.Player.UpdateMiscCounter(), Terraria.Player.UpdateNearbyInteractibleProjectilesList(), Terraria.Player.UpdatePermanentBoosters(), Terraria.Player.UpdatePet(), Terraria.Player.UpdatePetLight(), Terraria.Player.UpdatePettingAnimal(), Terraria.GameContent.PressurePlateHelper.UpdatePlayerPosition(), Terraria.Player.UpdatePortableStoolUsage(), Terraria.Player.UpdateProjectileCaches(), Terraria.Player.UpdateReleaseUseTile(), Terraria.GameContent.PlayerSittingHelper.UpdateSitting(), Terraria.Player.UpdateSocialShadow(), Terraria.GameContent.PlayerSleepingHelper.UpdateState(), Terraria.Player.UpdateTeleportVisuals(), Terraria.Player.UpdateTouchingTiles(), Terraria.Mount.UseDrill(), Terraria.GameInput.PlayerInput.UsingGamepad, Terraria.Player.vanityRocketBoots, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Player.vortexDebuff, Terraria.Player.vortexStealthActive, Terraria.Player.WallslideMovement(), Terraria.Player.wallSpeed, Terraria.SceneMetrics.WaterCandleCount, Terraria.Player.WaterCollision(), Terraria.Player.waterWalk, Terraria.Player.waterWalk2, Terraria.Player.webbed, Terraria.Player.wereWolf, Terraria.Entity.wet, Terraria.Collision.WetCollision(), Terraria.Entity.wetCount, Terraria.Player.wetSlime, Terraria.Entity.whoAmI, Terraria.Entity.width, Terraria.Player.WingAirLogicTweaks(), Terraria.Player.WingAirVisuals(), Terraria.Player.wingFrame, Terraria.Player.WingFrame(), Terraria.Player.wingFrameCounter, Terraria.Player.WingMovement(), Terraria.Player.wings, Terraria.Player.wingsLogic, Terraria.Player.wingTime, Terraria.Player.wingTimeMax, Terraria.ModLoader.ItemLoader.WingUpdate(), Terraria.Player.witheredArmor, Terraria.Player.witheredWeapon, Terraria.Main.wofNPCIndex, Terraria.Player.WOFTongue(), Terraria.Player.wolfAcc, Terraria.Chest.x, Terraria.Sign.x, Terraria.Chest.y, Terraria.Sign.y, Terraria.Player.yoraiz0rEye, Terraria.Player.Yoraiz0rEye(), Terraria.Player.ZoneSandstorm, and Terraria.Player.ZoneSnow.
Referenced by Terraria.Main.DoUpdateInWorld().