TModLoader: Terraria.Player.GetItem_FillEmptyInventorySlot
GetItem_FillEmptyInventorySlot()
bool Terraria.Player.GetItem_FillEmptyInventorySlot (int plr, Item newItem, GetItemSettings settings, Item returnItem, int i) inline private
    {
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        if (inventory[i].type != 0)
        {
            return false;
        }
        if (newItem.IsACoin)
        {
            SoundEngine.PlaySound(38, (int)position.X, (int)position.Y);
        }
        else
        {
            SoundEngine.PlaySound(7, (int)position.X, (int)position.Y);
        }
        returnItem.shimmered = false;
        inventory[i] = returnItem;
        if (!settings.NoText)
        {
            PopupText.NewText(PopupTextContext.RegularItemPickup, newItem, newItem.stack, noStack: false, settings.LongText);
        }
        DoCoins(i);
        if (plr == Main.myPlayer)
        {
            Recipe.FindRecipes();
        }
        AchievementsHelper.NotifyItemPickup(this, returnItem);
        if (plr == Main.myPlayer && newItem.type == 5095)
        {
            LucyAxeMessage.Create(LucyAxeMessage.MessageSource.PickedUp, base.Top, new Vector2(0f, -7f));
        }
        settings.HandlePostAction(inventory[i]);
        return true;
    }
References Terraria.GameContent.LucyAxeMessage.Create(), Terraria.Player.DoCoins(), Terraria.Recipe.FindRecipes(), Terraria.Player.inventory, Terraria.Main.myPlayer, Terraria.PopupText.NewText(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemPickup(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Entity.position.
Referenced by Terraria.Player.GetItem().