TModLoader: Terraria.Player.CanHit
CanHit()
bool Terraria.Player.CanHit (Entity ent) inline
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        if (!Collision.CanHit(position, width, height, ent.position, ent.width, ent.height) && !Collision.CanHitLine(base.Center + new Vector2((float)(direction * width / 2), gravDir * (float)(-height) / 3f), 0, 0, ent.Center + new Vector2(0f, (float)(-ent.height / 3)), 0, 0) && !Collision.CanHitLine(base.Center + new Vector2((float)(direction * width / 2), gravDir * (float)(-height) / 3f), 0, 0, ent.Center, 0, 0))
        {
            return Collision.CanHitLine(base.Center + new Vector2((float)(direction * width / 2), 0f), 0, 0, ent.Center + new Vector2(0f, (float)(ent.height / 3)), 0, 0);
        }
        return true;
    }
References Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Entity.direction, Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Entity.position, and Terraria.Entity.width.
Referenced by Terraria.Player.DashMovement(), Terraria.Player.ItemCheck_MeleeHitPVP(), and Terraria.Player.ProcessHitAgainstNPC().