TModLoader: Terraria.Player.ItemCheck_CheckFishingBobber_PickAndConsumeBait
ItemCheck_CheckFishingBobber_PickAndConsumeBait()
void Terraria.Player.ItemCheck_CheckFishingBobber_PickAndConsumeBait (Projectile bobber, out bool pullTheBobber, out int baitTypeUsed) inline private
    {
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        pullTheBobber = false;
        baitTypeUsed = 0;
        int num = -1;
        for (int i = 54; i < 58; i++)
        {
            if (inventory[i].stack > 0 && inventory[i].bait > 0)
            {
                num = i;
                break;
            }
        }
        if (num == -1)
        {
            for (int j = 0; j < 50; j++)
            {
                if (inventory[j].stack > 0 && inventory[j].bait > 0)
                {
                    num = j;
                    break;
                }
            }
        }
        if (num <= -1)
        {
            return;
        }
        Item item = inventory[num];
        bool flag = false;
        float num2 = 1f + (float)item.bait / 6f;
        if (num2 < 1f)
        {
            num2 = 1f;
        }
        if (accTackleBox)
        {
            num2 += 1f;
        }
        if (Main.rand.NextFloat() * num2 < 1f)
        {
            flag = true;
        }
        if (bobber.localAI[1] == -1f)
        {
            flag = true;
        }
        if (bobber.localAI[1] > 0f)
        {
            Item item2 = new Item();
            item2.SetDefaults((int)bobber.localAI[1]);
            if (item2.rare < 0)
            {
                flag = false;
            }
        }
        baitTypeUsed = item.type;
        if (baitTypeUsed == 2895)
        {
            flag = Main.rand.Next(20) == 0;
        }
        if (baitTypeUsed == 2673)
        {
            flag = true;
        }
        if (CombinedHooks.CanConsumeBait(this, item) ?? flag)
        {
            if (item.type == 4361 || item.type == 4362)
            {
                NPC.LadyBugKilled(base.Center, item.type == 4362);
            }
            item.stack--;
            if (item.stack <= 0)
            {
                item.SetDefaults();
            }
        }
        pullTheBobber = true;
    }
References Terraria.Player.accTackleBox, Terraria.Item.bait, Terraria.ModLoader.CombinedHooks.CanConsumeBait(), Terraria.Player.inventory, Terraria.NPC.LadyBugKilled(), Terraria.Projectile.localAI, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Item.SetDefaults(), Terraria.Item.stack, and Terraria.Item.type.
Referenced by Terraria.Player.ItemCheck_CheckFishingBobbers().