TModLoader: Terraria.Player.UpdateHungerBuffs
UpdateHungerBuffs()
void Terraria.Player.UpdateHungerBuffs () inline
Definition at line 10083 of file Player.cs.
    {
        for (int i = 0; i < maxBuffs; i++)
        {
            if (buffType[i] <= 0 || buffTime[i] <= 0)
            {
                continue;
            }
            if (buffType[i] == 332)
            {
                if (buffTime[i] <= 2 && whoAmI == Main.myPlayer)
                {
                    if (Main.remixWorld && Main.dontStarveWorld)
                    {
                        AddBuff(333, 28800);
                    }
                    else
                    {
                        AddBuff(333, 18000);
                    }
                    EmoteBubble.MakeLocalPlayerEmote(147);
                }
                if (!Main.dontStarveWorld)
                {
                    buffTime[i] = 0;
                }
            }
            else if (buffType[i] == 333)
            {
                if (buffTime[i] <= 2 && whoAmI == Main.myPlayer)
                {
                    if (Main.remixWorld && Main.dontStarveWorld)
                    {
                        AddBuff(334, 5);
                    }
                    else
                    {
                        AddBuff(334, 5);
                    }
                    EmoteBubble.MakeLocalPlayerEmote(148);
                }
                if (!Main.dontStarveWorld)
                {
                    buffTime[i] = 0;
                }
            }
            else if (buffType[i] == 334 && !Main.dontStarveWorld)
            {
                buffTime[i] = 0;
            }
        }
    }
References Terraria.Player.AddBuff(), Terraria.Player.buffTime, Terraria.Player.buffType, Terraria.Main.dontStarveWorld, Terraria.GameContent.UI.EmoteBubble.MakeLocalPlayerEmote(), Terraria.Player.maxBuffs, Terraria.Main.myPlayer, Terraria.Main.remixWorld, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.TryToResetHungerToNeutral(), and Terraria.Player.UpdateBuffs().