TModLoader: Terraria.Player.ChooseAmmo
ChooseAmmo()
Item Terraria.Player.ChooseAmmo (Item weapon) inline
Attempts to select an ammo item stack from this player's inventory to shoot with the given weapon.
Parameters
weapon The weapon for which this call should try to find ammo.
Returns
Null if no suitable ammo is found; otherwise, returns the first ammo item found.
    {
        Item item = null;
        bool flag = false;
        if (weapon.useAmmo == AmmoID.Coin)
        {
            for (int i = 0; i < 4; i++)
            {
                int num = 50 + i;
                if (inventory[num].stack > 0 && ItemLoader.CanChooseAmmo(weapon, inventory[i], this))
                {
                    item = inventory[num];
                    flag = true;
                    break;
                }
            }
        }
        for (int j = 54; j < 58; j++)
        {
            if (inventory[j].stack > 0 && ItemLoader.CanChooseAmmo(weapon, inventory[j], this))
            {
                item = inventory[j];
                flag = true;
                break;
            }
        }
        if (!flag)
        {
            for (int k = 0; k < 54; k++)
            {
                if (inventory[k].stack > 0 && ItemLoader.CanChooseAmmo(weapon, inventory[k], this))
                {
                    item = inventory[k];
                    break;
                }
            }
        }
        return item;
    }
References Terraria.ModLoader.ItemLoader.CanChooseAmmo(), Terraria.ID.AmmoID.Coin, and Terraria.Player.inventory.
Referenced by Terraria.Player.HasAmmo(), and Terraria.Player.PickAmmo().