TModLoader: Terraria.Player.TeleportationPotion
TeleportationPotion()
void Terraria.Player.TeleportationPotion () inline
    {
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        bool canSpawn = false;
        int teleportStartX = 100;
        int teleportRangeX = Main.maxTilesX - 200;
        int teleportStartY = 100;
        int underworldLayer = Main.UnderworldLayer;
        Vector2 vector = CheckForGoodTeleportationSpot(ref canSpawn, teleportStartX, teleportRangeX, teleportStartY, underworldLayer, new RandomTeleportationAttemptSettings
        {
            avoidLava = true,
            avoidHurtTiles = true,
            maximumFallDistanceFromOrignalPoint = 100,
            attemptsBeforeGivingUp = 1000
        });
        if (canSpawn)
        {
            Vector2 newPos = vector;
            Teleport(newPos, 2);
            velocity = Vector2.Zero;
            if (Main.netMode == 2)
            {
                RemoteClient.CheckSection(whoAmI, position);
                NetMessage.SendData(65, -1, -1, null, 0, whoAmI, newPos.X, newPos.Y, 2);
            }
        }
        else
        {
            Vector2 newPos2 = position;
            Teleport(newPos2, 2);
            velocity = Vector2.Zero;
            if (Main.netMode == 2)
            {
                RemoteClient.CheckSection(whoAmI, position);
                NetMessage.SendData(65, -1, -1, null, 0, whoAmI, newPos2.X, newPos2.Y, 2, 1);
            }
        }
    }
References Terraria.Player.CheckForGoodTeleportationSpot(), Terraria.RemoteClient.CheckSection(), Terraria.Main.netMode, Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.Player.Teleport(), Terraria.Main.UnderworldLayer, Terraria.Entity.velocity, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ItemCheck_Inner().