TModLoader: Terraria.Player.TryBouncingBlocks
TryBouncingBlocks()
void Terraria.Player.TryBouncingBlocks (bool Falling) inline private
    {
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_0169: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_0222: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        //IL_022e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0233: Unknown result type (might be due to invalid IL or missing references)
        //IL_0236: Unknown result type (might be due to invalid IL or missing references)
        //IL_023b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        bool num7 = !wet && !shimmering && (velocity.Y >= 5f || velocity.Y <= -5f);
        bool flag = false;
        bool flag2 = false;
        float num2 = 1f;
        if (!num7)
        {
            return;
        }
        bool flag3 = false;
        int num3 = 0;
        foreach (Point touchedTile in TouchedTiles)
        {
            Tile tile = Main.tile[touchedTile.X, touchedTile.Y];
            if (tile != null && tile.active() && tile.nactive() && (flag || Main.tileBouncy[tile.type]))
            {
                flag3 = true;
                num3 = touchedTile.Y;
                break;
            }
        }
        if (!flag3)
        {
            return;
        }
        velocity.Y *= -0.8f;
        if (controlJump)
        {
            velocity.Y = MathHelper.Clamp(velocity.Y, -13f, 13f);
        }
        position.Y = num3 * 16 - ((velocity.Y < 0f) ? height : (-16));
        FloorVisuals(Falling);
        if (flag2)
        {
            Vector2 vector = (fullRotation - (float)Math.PI / 2f).ToRotationVector2();
            if (vector.Y > 0f)
            {
                vector.Y *= -1f;
            }
            vector.Y = vector.Y * 0.5f + -0.5f;
            float num4 = 0f - vector.Y;
            if (num4 < 0f)
            {
                num4 = 0f;
            }
            float num5 = num4 * 1.5f + 1f;
            float value = Math.Abs(velocity.Y) * num5 * num2;
            value = MathHelper.Clamp(value, 2f, 16f);
            velocity = vector * value;
            float num6 = 20f;
            Vector2 vector2 = base.Center + (fullRotation + (float)Math.PI / 2f).ToRotationVector2() * num6;
            vector2 = base.Bottom;
            ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.Keybrand, new ParticleOrchestraSettings
            {
                PositionInWorld = vector2
            }, whoAmI);
        }
        velocity.Y = MathHelper.Clamp(velocity.Y, -20f, 20f);
        if (velocity.Y * gravDir < 0f)
        {
            fallStart = (int)position.Y / 16;
        }
    }
References Terraria.Tile.active(), Terraria.Player.controlJump, Terraria.Player.fallStart, Terraria.Player.FloorVisuals(), Terraria.Player.fullRotation, Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Tile.nactive(), Terraria.Entity.position, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Player.shimmering, Terraria.Main.tile, Terraria.Main.tileBouncy, Terraria.Player.TouchedTiles, Terraria.Tile.type, Terraria.Entity.velocity, Terraria.Entity.wet, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.DryCollision(), and Terraria.Player.Update().