TModLoader: Terraria.Player.FindItemInInventoryOrOpenVoidBag
FindItemInInventoryOrOpenVoidBag()
int Terraria.Player.FindItemInInventoryOrOpenVoidBag (int type, out bool inVoidBag) inline
    {
        inVoidBag = false;
        int num = FindItem(type);
        if (num == -1 && useVoidBag())
        {
            num = FindItem(type, bank4.item);
            if (num == -1)
            {
                return -1;
            }
            inVoidBag = true;
        }
        return num;
    }
References Terraria.Player.bank4, Terraria.Player.FindItem(), Terraria.Chest.item, and Terraria.Player.useVoidBag().
Referenced by Terraria.Main.TryFreeingElderSlime().