TModLoader: Terraria.Player.ItemCheck_UseShimmerPermanentItems
ItemCheck_UseShimmerPermanentItems()
void Terraria.Player.ItemCheck_UseShimmerPermanentItems (Item sItem) inline private
Definition at line 45121 of file Player.cs.
    {
        if (sItem.type == 5337 && itemAnimation > 0 && !usedAegisCrystal && ItemTimeIsZero)
        {
            ApplyItemTime(sItem);
            usedAegisCrystal = true;
            NetMessage.SendData(4, -1, -1, null, whoAmI);
        }
        if (sItem.type == 5338 && itemAnimation > 0 && !usedAegisFruit && ItemTimeIsZero)
        {
            ApplyItemTime(sItem);
            usedAegisFruit = true;
            NetMessage.SendData(4, -1, -1, null, whoAmI);
        }
        if (sItem.type == 5339 && itemAnimation > 0 && !usedArcaneCrystal && ItemTimeIsZero)
        {
            ApplyItemTime(sItem);
            usedArcaneCrystal = true;
            NetMessage.SendData(4, -1, -1, null, whoAmI);
        }
        if (sItem.type == 5340 && itemAnimation > 0 && !usedGalaxyPearl && ItemTimeIsZero)
        {
            ApplyItemTime(sItem);
            usedGalaxyPearl = true;
            NetMessage.SendData(4, -1, -1, null, whoAmI);
        }
        if (sItem.type == 5341 && itemAnimation > 0 && !usedGummyWorm && ItemTimeIsZero)
        {
            ApplyItemTime(sItem);
            usedGummyWorm = true;
            NetMessage.SendData(4, -1, -1, null, whoAmI);
        }
        if (sItem.type == 5342 && itemAnimation > 0 && !usedAmbrosia && ItemTimeIsZero)
        {
            ApplyItemTime(sItem);
            usedAmbrosia = true;
            NetMessage.SendData(4, -1, -1, null, whoAmI);
        }
    }
References Terraria.Player.ApplyItemTime(), Terraria.Player.itemAnimation, Terraria.Player.ItemTimeIsZero, Terraria.NetMessage.SendData(), Terraria.Player.usedAegisCrystal, Terraria.Player.usedAegisFruit, Terraria.Player.usedAmbrosia, Terraria.Player.usedArcaneCrystal, Terraria.Player.usedGalaxyPearl, Terraria.Player.usedGummyWorm, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode().