TModLoader: Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform
PlaceThing_Tiles_PlaceIt_SpinSmartPlatform()
void Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform () inline private
    {
        if (inventory[selectedItem].createTile < 0 || !TileID.Sets.Platforms[inventory[selectedItem].createTile] || !Main.SmartCursorIsUsed)
        {
            return;
        }
        int num = tileTargetX;
        int num4 = tileTargetY;
        int num5 = -1;
        int num6 = 0;
        int num7 = 0;
        bool flag = true;
        for (int i = -1; i < 2; i++)
        {
            for (int j = -1; j < 2; j++)
            {
                if ((i != 0 || j != 0) && TileID.Sets.Platforms[Main.tile[num + i, num4 + j].type])
                {
                    flag = false;
                }
            }
        }
        if (flag)
        {
            return;
        }
        Tile tile = Main.tile[num - 1, num4 - 1];
        if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() != 2)
        {
            num6++;
        }
        tile = Main.tile[num - 1, num4 + 1];
        if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() != 1)
        {
            num7++;
        }
        tile = Main.tile[num + 1, num4 - 1];
        if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() != 1)
        {
            num7++;
        }
        tile = Main.tile[num + 1, num4 + 1];
        if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() != 2)
        {
            num6++;
        }
        tile = Main.tile[num - 1, num4];
        if (WorldGen.SolidTile(tile))
        {
            num6++;
            if (TileID.Sets.Platforms[tile.type] && tile.slope() == 0)
            {
                num6++;
            }
        }
        tile = Main.tile[num + 1, num4];
        if (WorldGen.SolidTile(tile))
        {
            num7++;
            if (TileID.Sets.Platforms[tile.type] && tile.slope() == 0)
            {
                num7++;
            }
        }
        if (num6 > num7)
        {
            num5 = 1;
        }
        else if (num7 > num6)
        {
            num5 = 2;
        }
        tile = Main.tile[num - 1, num4];
        if (tile.active() && TileID.Sets.Platforms[tile.type])
        {
            num5 = 0;
        }
        tile = Main.tile[num + 1, num4];
        if (tile.active() && TileID.Sets.Platforms[tile.type])
        {
            num5 = 0;
        }
        int num8 = 0;
        int num9 = 0;
        if (num5 != -1)
        {
            WorldGen.SlopeTile(num, num4, num5, noEffects: true);
            int num10 = Main.tile[num, num4].slope();
            if (Main.netMode == 1)
            {
                NetMessage.SendData(17, -1, -1, null, 14, tileTargetX, tileTargetY, num10);
            }
            if (num5 == 1)
            {
                num8 = -1;
                num9 = -1;
            }
            else
            {
                num8 = 1;
                num9 = -1;
            }
            tile = Main.tile[num + num8, num4 + num9];
            if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() == 0 && (!Main.tile[num + num8 + num8, num4 + num9].active() || !TileID.Sets.Platforms[Main.tile[num + num8 + num8, num4 + num9].type] || !Main.tile[num + num8 + num8, num4 + num9].halfBrick()))
            {
                WorldGen.SlopeTile(num + num8, num4 + num9, num5);
                num10 = tile.slope();
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 14, num + num8, num4 + num9, num10);
                }
            }
            if (num5 == 1)
            {
                num8 = 1;
                num9 = 1;
            }
            else
            {
                num8 = -1;
                num9 = 1;
            }
            tile = Main.tile[num + num8, num4 + num9];
            if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() == 0 && WorldGen.PlatformProperSides(num + num8, num4 + num9, acceptNonOpposing: true) <= 0)
            {
                WorldGen.SlopeTile(num + num8, num4 + num9, num5);
                num10 = tile.slope();
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 14, num + num8, num4 + num9, num10);
                }
            }
            return;
        }
        num5 = 0;
        int num11 = 0;
        num8 = -1;
        tile = Main.tile[num + num8, num4];
        if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() != 0)
        {
            int num2 = (tile.slope() == 1).ToDirectionInt() * num8;
            num5 = ((num2 != -1) ? tile.slope() : 0);
            bool flag2 = true;
            if (Main.tile[num + num8 * 2, num4 + num2].active() && TileID.Sets.Platforms[Main.tile[num + num8 * 2, num4].type] && num5 == Main.tile[num + num8 * 2, num4 + num2].slope())
            {
                flag2 = false;
            }
            if (Main.tile[num, num4 - num2].active() && TileID.Sets.Platforms[Main.tile[num, num4 - num2].type] && tile.slope() == Main.tile[num, num4 - num2].slope())
            {
                flag2 = false;
            }
            if (flag2)
            {
                WorldGen.SlopeTile(num + num8, num4, num5);
                num11 = tile.slope();
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 14, num + num8, num4, num11);
                }
            }
        }
        num8 = 1;
        num9 = 0;
        tile = Main.tile[num + num8, num4 + num9];
        if (tile.active() && TileID.Sets.Platforms[tile.type] && tile.slope() != 0)
        {
            int num3 = (tile.slope() == 1).ToDirectionInt() * num8;
            num5 = ((num3 != -1) ? tile.slope() : 0);
            bool flag3 = true;
            if (Main.tile[num + num8 * 2, num4 + num3].active() && TileID.Sets.Platforms[Main.tile[num + num8 * 2, num4].type] && num5 == Main.tile[num + num8 * 2, num4 + num3].slope())
            {
                flag3 = false;
            }
            if (Main.tile[num, num4 - num3].active() && TileID.Sets.Platforms[Main.tile[num, num4 - num3].type] && tile.slope() == Main.tile[num, num4 - num3].slope())
            {
                flag3 = false;
            }
            if (flag3)
            {
                WorldGen.SlopeTile(num + num8, num4, num5);
                num11 = tile.slope();
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 14, num + num8, num4, num11);
                }
            }
        }
        if (num6 != num7 || WorldGen.PlatformProperSides(num, num4) != 0)
        {
            return;
        }
        tile = Main.tile[num, num4 + 1];
        if (tile.active() && !tile.halfBrick() && tile.slope() == 0 && Main.tileSolid[tile.type])
        {
            num5 = ((direction != 1) ? 1 : 2);
            WorldGen.SlopeTile(num, num4, num5);
            num11 = Main.tile[num, num4].slope();
            if (Main.netMode == 1)
            {
                NetMessage.SendData(17, -1, -1, null, 14, tileTargetX, tileTargetY, num11);
            }
        }
    }
References Terraria.Tile.active(), Terraria.Item.createTile, Terraria.Entity.direction, Terraria.Tile.halfBrick(), Terraria.Player.inventory, Terraria.Main.netMode, Terraria.WorldGen.PlatformProperSides(), Terraria.ID.TileID.Sets.Platforms, Terraria.Player.selectedItem, Terraria.NetMessage.SendData(), Terraria.Tile.slope(), Terraria.WorldGen.SlopeTile(), Terraria.Main.SmartCursorIsUsed, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, and Terraria.Tile.type.
Referenced by Terraria.Player.PlaceThing_Tiles_PlaceIt().