TModLoader: Terraria.Player.DropFromItem
DropFromItem()
void Terraria.Player.DropFromItem (int itemType) inline
Definition at line 58207 of file Player.cs.
    {
        DropAttemptInfo dropAttemptInfo = default(DropAttemptInfo);
        dropAttemptInfo.player = this;
        dropAttemptInfo.item = itemType;
        dropAttemptInfo.IsExpertMode = Main.expertMode;
        dropAttemptInfo.IsMasterMode = Main.masterMode;
        dropAttemptInfo.IsInSimulation = false;
        dropAttemptInfo.rng = Main.rand;
        DropAttemptInfo info = dropAttemptInfo;
        Main.ItemDropSolver.TryDropping(info);
    }
References Terraria.Main.expertMode, Terraria.Main.ItemDropSolver, Terraria.Main.masterMode, Terraria.Main.rand, and Terraria.GameContent.ItemDropRules.ItemDropResolver.TryDropping().
Referenced by Terraria.Player.OpenBossBag(), Terraria.Player.OpenCanofWorms(), Terraria.Player.OpenFishingCrate(), Terraria.Player.OpenGoodieBag(), Terraria.Player.OpenHerbBag(), Terraria.Player.OpenLegacyPresent(), Terraria.Player.OpenLockBox(), Terraria.Player.OpenOyster(), Terraria.Player.OpenPresent(), Terraria.Player.OpenShadowLockbox(), and Terraria.UI.ItemSlot.TryOpenContainer().