TModLoader: Terraria.Player.TryReplantingTree
TryReplantingTree()
void Terraria.Player.TryReplantingTree (int x, int y) inline private
    {
        int type = 20;
        int style = 0;
        PlantLoader.CheckAndInjectModSapling(x, y, ref type, ref style);
        if (!TileObject.CanPlace(tileTargetX, tileTargetY, type, style, direction, out var objectData))
        {
            return;
        }
        bool num = TileObject.Place(objectData);
        WorldGen.SquareTileFrame(tileTargetX, tileTargetY);
        if (num)
        {
            TileObjectData.CallPostPlacementPlayerHook(tileTargetX, tileTargetY, type, style, direction, objectData.alternate, objectData);
            if (Main.netMode == 1)
            {
                NetMessage.SendObjectPlacement(-1, tileTargetX, tileTargetY, objectData.type, objectData.style, objectData.alternate, objectData.random, direction);
            }
        }
    }
References Terraria.ObjectData.TileObjectData.CallPostPlacementPlayerHook(), Terraria.TileObject.CanPlace(), Terraria.ModLoader.PlantLoader.CheckAndInjectModSapling(), Terraria.Entity.direction, Terraria.Main.netMode, Terraria.TileObject.Place(), Terraria.NetMessage.SendObjectPlacement(), Terraria.WorldGen.SquareTileFrame(), Terraria.Player.tileTargetX, and Terraria.Player.tileTargetY.
Referenced by Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool().