TModLoader: Terraria.Player.InInteractionRange
InInteractionRange()
bool Terraria.Player.InInteractionRange (int interactX, int interactY, TileReachCheckSettings settings) inline
    {
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        int num = (int)(((double)position.X + (double)width * 0.5) / 16.0);
        int num2 = (int)(((double)position.Y + (double)height * 0.5) / 16.0);
        Tile tile = Main.tile[interactX, interactY];
        settings.GetRanges(this, out var x, out var y);
        if (tile.type == 597)
        {
            if (interactX < num)
            {
                interactX += 2;
            }
            if (interactY < num2)
            {
                interactY += 3;
            }
            Point point = position.ToTileCoordinates();
            Point point2 = base.BottomRight.ToTileCoordinates();
            if (point2.X >= interactX - x + 1 && point.X <= interactX + x - 1 && point2.Y >= interactY - y + 2)
            {
                return point.Y <= interactY + y - 1;
            }
            return false;
        }
        if (tile.type == 475)
        {
            if (num >= interactX - x - 1 && num <= interactX + x + 2 && num2 >= interactY - y - 1)
            {
                return num2 <= interactY + y + 2;
            }
            return false;
        }
        if (tile.type == 470)
        {
            if (num >= interactX - x - 1 && num <= interactX + x + 1 && num2 >= interactY - y - 1)
            {
                return num2 <= interactY + y + 2;
            }
            return false;
        }
        if (num >= interactX - x && num <= interactX + x + 1 && num2 >= interactY - y)
        {
            return num2 <= interactY + y + 1;
        }
        return false;
    }
References Terraria.Entity.height, Terraria.Entity.position, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Entity.width.
Referenced by Terraria.GameContent.TeleportPylonsSystem.HandleTeleportRequest(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.OnPlayerUpdate(), and Terraria.GameContent.Tile_Entities.TEHatRack.OnPlayerUpdate().