TModLoader: Terraria.Player.ItemCheck_CheckFishingBobbers
ItemCheck_CheckFishingBobbers()
bool Terraria.Player.ItemCheck_CheckFishingBobbers (bool canUse) inline private
Definition at line 53081 of file Player.cs.
    {
        for (int i = 0; i < 1000; i++)
        {
            Projectile projectile = Main.projectile[i];
            if (!projectile.active || projectile.owner != whoAmI || !projectile.bobber)
            {
                continue;
            }
            canUse = false;
            if (whoAmI != Main.myPlayer || projectile.ai[0] != 0f)
            {
                continue;
            }
            projectile.ai[0] = 1f;
            float num = -10f;
            if (projectile.wet && projectile.velocity.Y > num)
            {
                projectile.velocity.Y = num;
            }
            projectile.netUpdate2 = true;
            if (projectile.ai[1] < 0f && projectile.localAI[1] != 0f)
            {
                ItemCheck_CheckFishingBobber_PickAndConsumeBait(projectile, out var pullTheBobber, out var baitTypeUsed);
                if (pullTheBobber)
                {
                    ItemCheck_CheckFishingBobber_PullBobber(projectile, baitTypeUsed);
                }
            }
        }
        return canUse;
    }
References Terraria.Entity.active, Terraria.Projectile.ai, Terraria.Projectile.bobber, Terraria.Player.ItemCheck_CheckFishingBobber_PickAndConsumeBait(), Terraria.Player.ItemCheck_CheckFishingBobber_PullBobber(), Terraria.Projectile.localAI, Terraria.Main.myPlayer, Terraria.Projectile.owner, Terraria.Main.projectile, Terraria.Entity.velocity, Terraria.Entity.wet, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ItemCheck_CheckCanUse().