TModLoader: Terraria.Player.PlaceThing_Walls_FillEmptySpace
PlaceThing_Walls_FillEmptySpace()
void Terraria.Player.PlaceThing_Walls_FillEmptySpace () inline private
    {
        if (inventory[selectedItem].stack <= 1)
        {
            return;
        }
        int createWall = inventory[selectedItem].createWall;
        for (int i = 0; i < 4; i++)
        {
            int num = tileTargetX;
            int num2 = tileTargetY;
            if (i == 0)
            {
                num--;
            }
            if (i == 1)
            {
                num++;
            }
            if (i == 2)
            {
                num2--;
            }
            if (i == 3)
            {
                num2++;
            }
            if (Main.tile[num, num2].wall != 0)
            {
                continue;
            }
            int num3 = 0;
            for (int j = 0; j < 4; j++)
            {
                int num4 = num;
                int num5 = num2;
                if (j == 0)
                {
                    num4--;
                }
                if (j == 1)
                {
                    num4++;
                }
                if (j == 2)
                {
                    num5--;
                }
                if (j == 3)
                {
                    num5++;
                }
                if (Main.tile[num4, num5].wall == createWall)
                {
                    num3++;
                }
            }
            if (num3 != 4)
            {
                continue;
            }
            WorldGen.PlaceWall(num, num2, createWall);
            if (Main.tile[num, num2].wall == createWall)
            {
                if (ItemLoader.ConsumeItem(inventory[selectedItem], this))
                {
                    inventory[selectedItem].stack--;
                }
                if (inventory[selectedItem].stack == 0)
                {
                    inventory[selectedItem].SetDefaults();
                }
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 3, num, num2, createWall);
                }
                if (autoPaint && builderAccStatus[3] == 0)
                {
                    TryPainting(num, num2, paintingAWall: true, applyItemAnimation: false);
                }
            }
        }
    }
References Terraria.Player.autoPaint, Terraria.Player.builderAccStatus, Terraria.ModLoader.ItemLoader.ConsumeItem(), Terraria.Item.createWall, Terraria.Player.inventory, Terraria.Main.netMode, Terraria.WorldGen.PlaceWall(), Terraria.Player.selectedItem, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, Terraria.Main.tile, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, and Terraria.Player.TryPainting().
Referenced by Terraria.Player.PlaceThing_Walls().