TModLoader: Terraria.Player.OnHurt_Part2
OnHurt_Part2()
void Terraria.Player.OnHurt_Part2 (HurtInfo info) inline private
    {
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        PlayerDeathReason damageSource = info.DamageSource;
        if (ConsumeSolarFlare() && whoAmI == Main.myPlayer)
        {
            IEntitySource spawnSource = GetProjectileSource_SetBonus(1);
            Entity entity = null;
            if (damageSource.TryGetCausingEntity(out entity))
            {
                spawnSource = GetProjectileSource_OnHurt(entity, 1);
            }
            int num4 = Projectile.NewProjectile(spawnSource, base.Center.X, base.Center.Y, 0f, 0f, 608, (int)GetTotalDamage(DamageClass.Melee).ApplyTo(150f), 15f, Main.myPlayer);
            Main.projectile[num4].netUpdate = true;
            Main.projectile[num4].Kill();
        }
        if (beetleDefense && beetleOrbs > 0)
        {
            beetleOrbs--;
            for (int i = 0; i < maxBuffs; i++)
            {
                if (buffType[i] >= 95 && buffType[i] <= 97)
                {
                    DelBuff(i);
                }
            }
            if (beetleOrbs > 0)
            {
                AddBuff(95 + beetleOrbs - 1, 5, quiet: false);
            }
            beetleCounter = 0f;
        }
        if (magicCuffs)
        {
            int num5 = info.SourceDamage;
            statMana += num5;
            if (statMana > statManaMax2)
            {
                statMana = statManaMax2;
            }
            ManaEffect(num5);
        }
        if (!defendedByPaladin || whoAmI == Main.myPlayer || !Main.player[Main.myPlayer].hasPaladinShield)
        {
            return;
        }
        Player player = Main.player[Main.myPlayer];
        if (player.team != team || team == 0)
        {
            return;
        }
        float num6 = player.Distance(base.Center);
        bool flag3 = num6 < 800f;
        if (flag3)
        {
            for (int j = 0; j < 255; j++)
            {
                if (j != Main.myPlayer && Main.player[j].active && !Main.player[j].dead && !Main.player[j].immune && Main.player[j].hasPaladinShield && Main.player[j].team == team && (float)Main.player[j].statLife > (float)Main.player[j].statLifeMax2 * 0.25f)
                {
                    float num7 = Main.player[j].Distance(base.Center);
                    if (num6 > num7 || (num6 == num7 && j < Main.myPlayer))
                    {
                        flag3 = false;
                        break;
                    }
                }
            }
        }
        if (flag3)
        {
            int damage = info.Damage / 3;
            player.Hurt(PlayerDeathReason.LegacyEmpty(), damage, 0);
        }
    }
References Terraria.Player.AddBuff(), Terraria.ModLoader.StatModifier.ApplyTo(), Terraria.Player.beetleCounter, Terraria.Player.beetleDefense, Terraria.Player.beetleOrbs, Terraria.Player.buffType, Terraria.Player.ConsumeSolarFlare(), Terraria.Player.defendedByPaladin, Terraria.Player.DelBuff(), Terraria.Entity.Distance(), Terraria.Player.GetProjectileSource_OnHurt(), Terraria.Player.GetProjectileSource_SetBonus(), Terraria.Player.GetTotalDamage(), Terraria.Player.Hurt(), Terraria.DataStructures.PlayerDeathReason.LegacyEmpty(), Terraria.Player.magicCuffs, Terraria.Player.ManaEffect(), Terraria.Player.maxBuffs, Terraria.ModLoader.DamageClass.Melee, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Main.player, Terraria.Main.projectile, Terraria.Player.statMana, Terraria.Player.statManaMax2, Terraria.Player.team, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.Hurt().