TModLoader: Terraria.Player.UpdateDyes
UpdateDyes()
void Terraria.Player.UpdateDyes () inline
    {
        cShieldFallback = -1;
        cHead = (cBody = (cLegs = (cHandOn = (cHandOff = (cBack = (cFront = (cShoe = (cWaist = (cShield = (cNeck = (cFace = (cFaceHead = (cFaceFlower = (cBalloon = (cBalloon = (cWings = (cCarpet = (cFloatingTube = (cBackpack = (cTail = 0))))))))))))))))))));
        cGrapple = (cMount = (cMinecart = (cPet = (cLight = (cYorai = (cPortableStool = (cUnicornHorn = (cAngelHalo = (cBeard = (cMinion = (cLeinShampoo = (cFlameWaker = 0))))))))))));
        skinDyePacked = 0;
        cHead = dye[0].dye;
        cBody = dye[1].dye;
        cLegs = dye[2].dye;
        if (wearsRobe)
        {
            cLegs = cBody;
        }
        cPet = miscDyes[0].dye;
        cLight = miscDyes[1].dye;
        cMinecart = miscDyes[2].dye;
        cMount = miscDyes[3].dye;
        cGrapple = miscDyes[4].dye;
        for (int i = 0; i < 20; i++)
        {
            if (IsItemSlotUnlockedAndUsable(i))
            {
                int num = i % 10;
                UpdateItemDye(i < 10, hideVisibleAccessory[num], armor[i], dye[num]);
            }
            if (i == 9)
            {
                AccessorySlotLoader.ModSlotPlayer(this).UpdateDyes(socialSlots: false);
            }
            if (i == 19)
            {
                AccessorySlotLoader.ModSlotPlayer(this).UpdateDyes(socialSlots: true);
            }
        }
        PlayerLoader.UpdateDyes(this);
        cYorai = cPet;
    }
References Terraria.Player.armor, Terraria.Player.cAngelHalo, Terraria.Player.cBack, Terraria.Player.cBackpack, Terraria.Player.cBalloon, Terraria.Player.cBeard, Terraria.Player.cBody, Terraria.Player.cCarpet, Terraria.Player.cFace, Terraria.Player.cFaceFlower, Terraria.Player.cFaceHead, Terraria.Player.cFlameWaker, Terraria.Player.cFloatingTube, Terraria.Player.cFront, Terraria.Player.cGrapple, Terraria.Player.cHandOff, Terraria.Player.cHandOn, Terraria.Player.cHead, Terraria.Player.cLegs, Terraria.Player.cLeinShampoo, Terraria.Player.cLight, Terraria.Player.cMinecart, Terraria.Player.cMinion, Terraria.Player.cMount, Terraria.Player.cNeck, Terraria.Player.cPet, Terraria.Player.cPortableStool, Terraria.Player.cShield, Terraria.Player.cShieldFallback, Terraria.Player.cShoe, Terraria.Player.cTail, Terraria.Player.cUnicornHorn, Terraria.Player.cWaist, Terraria.Player.cWings, Terraria.Player.cYorai, Terraria.Item.dye, Terraria.Player.dye, Terraria.Player.hideVisibleAccessory, Terraria.Player.IsItemSlotUnlockedAndUsable(), Terraria.Player.miscDyes, Terraria.ModLoader.AccessorySlotLoader.ModSlotPlayer(), Terraria.Player.skinDyePacked, Terraria.ModLoader.Default.ModAccessorySlotPlayer.UpdateDyes(), Terraria.ModLoader.PlayerLoader.UpdateDyes(), Terraria.Player.UpdateItemDye(), and Terraria.Player.wearsRobe.
Referenced by Terraria.GameContent.Animations.Segments.PlayerSegment.Draw(), Terraria.Main.DrawSuperSpecialProjectiles(), Terraria.GameContent.UI.Elements.UICharacter.Update(), and Terraria.Player.Update().