TModLoader: Terraria.Player.IsAmmoFreeThisShot
IsAmmoFreeThisShot()
bool Terraria.Player.IsAmmoFreeThisShot (Item weapon, Item ammo, int projToShoot) inline
Determines whether or not the given ammunition should be conserved, based on the given weapon as wielded by this player.
Parameters
weapon The weapon attempting to consume the ammo.
ammo The ammo attempting to be conserved (i.e. not consumed).
projToShoot The projectile that should be shot by the given weapon/ammo combination.
Returns
True if the ammo should be conserved on the given shot; false otherwise.
Definition at line 54222 of file Player.cs.
    {
        if (!CombinedHooks.CanConsumeAmmo(this, weapon, ammo))
        {
            return true;
        }
        if (weapon.consumeAmmoOnFirstShotOnly && !ItemAnimationJustStarted)
        {
            return true;
        }
        if (weapon.consumeAmmoOnLastShotOnly)
        {
            int useTime = CombinedHooks.TotalUseTime(weapon.useTime, this, weapon);
            if (itemAnimation > useTime && (!weapon.useLimitPerAnimation.HasValue || ItemUsesThisAnimation != weapon.useLimitPerAnimation - 1))
            {
                return true;
            }
        }
        bool flag2 = false;
        if (weapon.type == 3475 && Main.rand.Next(3) != 0)
        {
            flag2 = true;
        }
        if (weapon.type == 3930 && Main.rand.Next(2) == 0)
        {
            flag2 = true;
        }
        if (weapon.type == 3540 && Main.rand.Next(3) != 0)
        {
            flag2 = true;
        }
        if (weapon.type == 5134 && Main.rand.Next(3) == 0)
        {
            flag2 = true;
        }
        if (magicQuiver && AmmoID.Sets.IsArrow[weapon.useAmmo] && Main.rand.Next(5) == 0)
        {
            flag2 = true;
        }
        if (ammoBox && Main.rand.Next(5) == 0)
        {
            flag2 = true;
        }
        if (ammoPotion && Main.rand.Next(5) == 0)
        {
            flag2 = true;
        }
        if (weapon.type == 1782 && Main.rand.Next(3) == 0)
        {
            flag2 = true;
        }
        if (weapon.type == 98 && Main.rand.Next(3) == 0)
        {
            flag2 = true;
        }
        if (weapon.type == 2270 && Main.rand.Next(2) == 0)
        {
            flag2 = true;
        }
        if (weapon.type == 533 && Main.rand.Next(2) == 0)
        {
            flag2 = true;
        }
        if (weapon.type == 1929 && Main.rand.Next(2) == 0)
        {
            flag2 = true;
        }
        if (weapon.type == 1553 && Main.rand.Next(3) != 0)
        {
            flag2 = true;
        }
        if (huntressAmmoCost90 && Main.rand.Next(10) == 0)
        {
            flag2 = true;
        }
        if (chloroAmmoCost80 && Main.rand.Next(5) == 0)
        {
            flag2 = true;
        }
        if (ammoCost80 && Main.rand.Next(5) == 0)
        {
            flag2 = true;
        }
        if (ammoCost75 && Main.rand.Next(4) == 0)
        {
            flag2 = true;
        }
        if (ammo.CountsAsClass(DamageClass.Throwing))
        {
            if (ThrownCost50 && Main.rand.Next(100) < 50)
            {
                flag2 = true;
            }
            if (ThrownCost33 && Main.rand.Next(100) < 33)
            {
                flag2 = true;
            }
        }
        if (Main.remixWorld && weapon.type == 1319 && Main.rand.Next(2) == 0)
        {
            flag2 = true;
        }
        return flag2;
    }
References Terraria.Player.ammoBox, Terraria.Player.ammoCost75, Terraria.Player.ammoCost80, Terraria.Player.ammoPotion, Terraria.ModLoader.CombinedHooks.CanConsumeAmmo(), Terraria.Player.chloroAmmoCost80, Terraria.Item.CountsAsClass(), Terraria.Player.huntressAmmoCost90, Terraria.ID.AmmoID.Sets.IsArrow, Terraria.Player.itemAnimation, Terraria.Player.ItemAnimationJustStarted, Terraria.Player.ItemUsesThisAnimation, Terraria.Player.magicQuiver, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.ModLoader.DamageClass.Throwing, Terraria.Player.ThrownCost33, Terraria.Player.ThrownCost50, and Terraria.ModLoader.CombinedHooks.TotalUseTime().
Referenced by Terraria.Player.PickAmmo().