TModLoader: Terraria.Player.LaunchMinecartHook
LaunchMinecartHook()
void Terraria.Player.LaunchMinecartHook (int myX, int myY) inline private
Definition at line 31735 of file Player.cs.
    {
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)Main.mouseX + Main.screenPosition.X, (float)Main.mouseY + Main.screenPosition.Y);
        ((Vector2)(ref vector))._002Ector((float)(myX * 16 + 8), (float)(myY * 16 + 8));
        if (direction > 0)
        {
            minecartLeft = false;
        }
        else
        {
            minecartLeft = true;
        }
        RemoveAllGrapplingHooks();
        Projectile.NewProjectile(GetProjectileSource_TileInteraction(myX, myY), vector.X, vector.Y, 0f, 0f, 403, 0, 0f, whoAmI);
        releaseHook = false;
    }
References Terraria.Entity.direction, Terraria.Player.GetProjectileSource_TileInteraction(), Terraria.Player.minecartLeft, Terraria.Main.mouseY, Terraria.Projectile.NewProjectile(), Terraria.Player.releaseHook, Terraria.Player.RemoveAllGrapplingHooks(), Terraria.Main.screenPosition, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.QuickMinecart(), Terraria.Player.QuickMinecartSnap(), and Terraria.Player.TileInteractionsUse().