TModLoader: Terraria.Player.ShouldDrawWingsThatAreAlwaysAnimated
ShouldDrawWingsThatAreAlwaysAnimated()
bool Terraria.Player.ShouldDrawWingsThatAreAlwaysAnimated () inline
    {
        if ((velocity.Y != 0f || grappling[0] != -1) && (!wet || !ShouldFloatInWater))
        {
            return !mount.Active;
        }
        return false;
    }
References Terraria.Mount.Active, Terraria.Player.grappling, Terraria.Player.mount, Terraria.Player.ShouldFloatInWater, Terraria.Entity.velocity, and Terraria.Entity.wet.
Referenced by Terraria.Player.PlayerFrame(), Terraria.Player.Update(), and Terraria.Player.WingFrame().