TModLoader: Terraria.Player.UpdateMinionTarget
UpdateMinionTarget()
void Terraria.Player.UpdateMinionTarget () inline
Definition at line 58049 of file Player.cs.
    {
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        if (whoAmI != Main.myPlayer)
        {
            return;
        }
        if (Distance(MinionRestTargetPoint) > 1000f)
        {
            MinionRestTargetPoint = Vector2.Zero;
        }
        if (MinionAttackTargetNPC != -1 && (!Main.npc[MinionAttackTargetNPC].CanBeChasedBy(this) || Main.npc[MinionAttackTargetNPC].Hitbox.Distance(base.Center) > 3000f))
        {
            MinionAttackTargetNPC = -1;
        }
        if (stardustGuardian && HasMinionRestTarget)
        {
            Vector2 minionRestTargetPoint = MinionRestTargetPoint;
            float num = (float)miscCounter / 150f;
            float num2 = (float)Math.PI * 2f / 3f;
            for (int i = 0; i < 3; i++)
            {
                int num3 = Dust.NewDust(minionRestTargetPoint, 0, 0, 135, 0f, 0f, 100, default(Color), 1.5f);
                Main.dust[num3].noGravity = true;
                Main.dust[num3].velocity = Vector2.Zero;
                Main.dust[num3].noLight = true;
                Main.dust[num3].position = minionRestTargetPoint + (num * ((float)Math.PI * 2f) + num2 * (float)i).ToRotationVector2() * 4f;
                Main.dust[num3].shader = GameShaders.Armor.GetSecondaryShader(cPet, this);
            }
        }
    }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.cPet, Terraria.Entity.Distance(), Terraria.Main.dust, Terraria.Player.HasMinionRestTarget, Terraria.Player.MinionAttackTargetNPC, Terraria.Player.MinionRestTargetPoint, Terraria.Player.miscCounter, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Main.npc, Terraria.Player.stardustGuardian, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.Update().