TModLoader: Terraria.Player.ApplyNPCOnHitEffects
ApplyNPCOnHitEffects()
void Terraria.Player.ApplyNPCOnHitEffects (Item sItem, Rectangle itemRectangle, int damage, float knockBack, int npcIndex, int dmgRandomized, int dmgDone) inline private
Definition at line 43706 of file Player.cs.
    {
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        //IL_031d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0323: Unknown result type (might be due to invalid IL or missing references)
        //IL_032d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_03df: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0402: Unknown result type (might be due to invalid IL or missing references)
        //IL_0404: Unknown result type (might be due to invalid IL or missing references)
        //IL_0409: Unknown result type (might be due to invalid IL or missing references)
        //IL_040d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0412: Unknown result type (might be due to invalid IL or missing references)
        //IL_0417: Unknown result type (might be due to invalid IL or missing references)
        //IL_0418: Unknown result type (might be due to invalid IL or missing references)
        //IL_041a: Unknown result type (might be due to invalid IL or missing references)
        //IL_042c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0431: Unknown result type (might be due to invalid IL or missing references)
        //IL_043b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0440: Unknown result type (might be due to invalid IL or missing references)
        //IL_0480: Unknown result type (might be due to invalid IL or missing references)
        //IL_048d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0493: Unknown result type (might be due to invalid IL or missing references)
        //IL_0495: Unknown result type (might be due to invalid IL or missing references)
        //IL_049a: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04db: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0504: Unknown result type (might be due to invalid IL or missing references)
        //IL_050d: Unknown result type (might be due to invalid IL or missing references)
        //IL_050f: Unknown result type (might be due to invalid IL or missing references)
        bool flag = !Main.npc[npcIndex].immortal;
        if (sItem.type == 3211)
        {
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector((float)(direction * 100 + Main.rand.Next(-25, 26)), (float)Main.rand.Next(-75, 76));
            ((Vector2)(ref vector)).Normalize();
            vector *= (float)Main.rand.Next(30, 41) * 0.1f;
            Vector2 vector2 = default(Vector2);
            ((Vector2)(ref vector2))._002Ector((float)(itemRectangle.X + Main.rand.Next(itemRectangle.Width)), (float)(itemRectangle.Y + Main.rand.Next(itemRectangle.Height)));
            vector2 = (vector2 + Main.npc[npcIndex].Center * 2f) / 3f;
            Projectile.NewProjectile(GetProjectileSource_Item(sItem), vector2.X, vector2.Y, vector.X, vector.Y, 524, (int)((double)damage * 0.5), knockBack * 0.7f, whoAmI);
        }
        if (beetleOffense && flag)
        {
            beetleCounter += dmgDone;
            beetleCountdown = 0;
        }
        if (meleeEnchant == 7)
        {
            Projectile.NewProjectile(GetProjectileSource_Misc(8), Main.npc[npcIndex].Center.X, Main.npc[npcIndex].Center.Y, Main.npc[npcIndex].velocity.X, Main.npc[npcIndex].velocity.Y, 289, 0, 0f, whoAmI);
        }
        if (sItem.type == 3106)
        {
            stealth = 1f;
            if (Main.netMode == 1)
            {
                NetMessage.SendData(84, -1, -1, null, whoAmI);
            }
        }
        if (sItem.type == 5094)
        {
            TentacleSpike_TrySpiking(Main.npc[npcIndex], sItem, damage, knockBack);
        }
        if (sItem.type == 795)
        {
            BloodButcherer_TryButchering(Main.npc[npcIndex], sItem, damage, knockBack);
        }
        if (sItem.type == 121)
        {
            Volcano_TrySpawningVolcano(Main.npc[npcIndex], sItem, (int)((float)damage * 0.75f), knockBack, itemRectangle);
        }
        if (sItem.type == 5097)
        {
            BatBat_TryLifeLeeching(Main.npc[npcIndex]);
        }
        if (sItem.type == 1123 && flag)
        {
            int num = Main.rand.Next(1, 4);
            if (strongBees && Main.rand.Next(3) == 0)
            {
                num++;
            }
            for (int i = 0; i < num; i++)
            {
                float num4 = (float)(direction * 2) + (float)Main.rand.Next(-35, 36) * 0.02f;
                float num5 = (float)Main.rand.Next(-35, 36) * 0.02f;
                num4 *= 0.2f;
                num5 *= 0.2f;
                int num6 = Projectile.NewProjectile(GetProjectileSource_Item(sItem), itemRectangle.X + itemRectangle.Width / 2, itemRectangle.Y + itemRectangle.Height / 2, num4, num5, beeType(), beeDamage(dmgRandomized / 3), beeKB(0f), whoAmI);
                Main.projectile[num6].melee = true;
            }
        }
        if (sItem.type == 155 && flag && _spawnMuramasaCut)
        {
            _spawnMuramasaCut = false;
            int num7 = Main.rand.Next(1, 4);
            num7 = 1;
            for (int j = 0; j < num7; j++)
            {
                NPC nPC = Main.npc[npcIndex];
                Rectangle hitbox = nPC.Hitbox;
                ((Rectangle)(ref hitbox)).Inflate(30, 16);
                hitbox.Y -= 8;
                Vector2 vector3 = Main.rand.NextVector2FromRectangle(hitbox);
                Vector2 val = ((Rectangle)(ref hitbox)).Center.ToVector2();
                Vector2 spinningpoint = (val - vector3).SafeNormalize(new Vector2((float)direction, gravDir)) * 8f;
                Main.rand.NextFloat();
                float num8 = (float)(Main.rand.Next(2) * 2 - 1) * ((float)Math.PI / 5f + (float)Math.PI * 4f / 5f * Main.rand.NextFloat());
                num8 *= 0.5f;
                spinningpoint = spinningpoint.RotatedBy(0.7853981852531433);
                int num9 = 3;
                int num10 = 10 * num9;
                int num11 = 5;
                int num2 = num11 * num9;
                vector3 = val;
                for (int k = 0; k < num2; k++)
                {
                    vector3 -= spinningpoint;
                    spinningpoint = spinningpoint.RotatedBy((0f - num8) / (float)num10);
                }
                vector3 += nPC.velocity * (float)num11;
                Projectile.NewProjectile(GetProjectileSource_Item(sItem), vector3, spinningpoint, 977, (int)((float)dmgRandomized * 0.5f), 0f, whoAmI, num8);
            }
        }
        if (Main.npc[npcIndex].value > 0f && hasLuckyCoin && Main.rand.Next(5) == 0)
        {
            int type = 71;
            if (Main.rand.Next(10) == 0)
            {
                type = 72;
            }
            if (Main.rand.Next(100) == 0)
            {
                type = 73;
            }
            int num3 = Item.NewItem(GetItemSource_OnHit(Main.npc[npcIndex], 2), (int)Main.npc[npcIndex].position.X, (int)Main.npc[npcIndex].position.Y, Main.npc[npcIndex].width, Main.npc[npcIndex].height, type);
            Main.item[num3].stack = Main.rand.Next(1, 11);
            Main.item[num3].velocity.Y = (float)Main.rand.Next(-20, 1) * 0.2f;
            Main.item[num3].velocity.X = (float)Main.rand.Next(10, 31) * 0.2f * (float)direction;
            Main.item[num3].timeLeftInWhichTheItemCannotBeTakenByEnemies = 60;
            if (Main.netMode == 1)
            {
                NetMessage.SendData(148, -1, -1, null, num3);
            }
        }
    }
References Terraria.Player._spawnMuramasaCut, Terraria.Player.BatBat_TryLifeLeeching(), Terraria.Player.beeDamage(), Terraria.Player.beeKB(), Terraria.Player.beetleCountdown, Terraria.Player.beetleCounter, Terraria.Player.beetleOffense, Terraria.Player.beeType(), Terraria.Player.BloodButcherer_TryButchering(), Terraria.Entity.Center, Terraria.Entity.direction, Terraria.Player.GetItemSource_OnHit(), Terraria.Player.GetProjectileSource_Item(), Terraria.Player.GetProjectileSource_Misc(), Terraria.Player.gravDir, Terraria.Player.hasLuckyCoin, Terraria.Main.item, Terraria.Player.meleeEnchant, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.Main.projectile, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Player.stealth, Terraria.Player.strongBees, Terraria.Player.TentacleSpike_TrySpiking(), Terraria.Player.Volcano_TrySpawningVolcano(), and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ProcessHitAgainstNPC().