TModLoader: Terraria.Player.ItemCheck_MinionAltFeatureUse
ItemCheck_MinionAltFeatureUse()
void Terraria.Player.ItemCheck_MinionAltFeatureUse (Item sItem, bool cShoot) inline private
    {
        if (sItem.shoot > 0 && ProjectileID.Sets.MinionTargettingFeature[sItem.shoot] && altFunctionUse == 2 && cShoot && ItemTimeIsZero)
        {
            ApplyItemTime(sItem);
            if (whoAmI == Main.myPlayer)
            {
                MinionNPCTargetAim(doNotDisableIfTheTargetIsTheSame: false);
            }
        }
    }
References Terraria.Player.altFunctionUse, Terraria.Player.ApplyItemTime(), Terraria.Player.ItemTimeIsZero, Terraria.Player.MinionNPCTargetAim(), Terraria.ID.ProjectileID.Sets.MinionTargettingFeature, Terraria.Main.myPlayer, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode().