TModLoader: Terraria.Player.PlaceThing_ItemInExtractinator
PlaceThing_ItemInExtractinator()
void Terraria.Player.PlaceThing_ItemInExtractinator (ref ItemCheckContext context) inline private
Definition at line 40373 of file Player.cs.
    {
        Tile tile = Main.tile[tileTargetX, tileTargetY];
        Item item = inventory[selectedItem];
        if (!tile.active() || !(position.X / 16f - (float)tileRangeX - (float)item.tileBoost - (float)blockRange <= (float)tileTargetX) || !((position.X + (float)width) / 16f + (float)tileRangeX + (float)item.tileBoost - 1f + (float)blockRange >= (float)tileTargetX) || !(position.Y / 16f - (float)tileRangeY - (float)item.tileBoost - (float)blockRange <= (float)tileTargetY) || !((position.Y + (float)height) / 16f + (float)tileRangeY + (float)item.tileBoost - 2f + (float)blockRange >= (float)tileTargetY) || !ItemTimeIsZero || itemAnimation <= 0 || !controlUseItem)
        {
            return;
        }
        float num = 1f;
        if (tile.type == 642)
        {
            num *= 0.33f;
        }
        ItemTrader itemTrader = TryGettingItemTraderFromBlock(tile);
        if (itemTrader != null && itemTrader.TryGetTradeOption(item, out var option))
        {
            SoundEngine.PlaySound(7);
            ApplyItemTime(item, num);
            context.SkipItemConsumption = true;
            item.stack -= option.TakingItemStack;
            if (item.stack <= 0)
            {
                item.TurnToAir();
            }
            DropItemFromExtractinator(option.GivingITemType, option.GivingItemStack);
        }
        else if (ItemID.Sets.ExtractinatorMode[item.type] >= 0 && (tile.type == 219 || tile.type == 642))
        {
            ApplyItemTime(item, num);
            SoundEngine.PlaySound(7);
            int extractType = ItemID.Sets.ExtractinatorMode[item.type];
            ExtractinatorUse(extractType, tile.type);
        }
    }
References Terraria.Tile.active(), Terraria.Player.ApplyItemTime(), Terraria.Player.blockRange, Terraria.Player.controlUseItem, Terraria.Player.DropItemFromExtractinator(), Terraria.ID.ItemID.Sets.ExtractinatorMode, Terraria.Player.ExtractinatorUse(), Terraria.Entity.height, Terraria.Player.inventory, Terraria.Player.itemAnimation, Terraria.Player.ItemTimeIsZero, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Player.selectedItem, Terraria.Item.stack, Terraria.Main.tile, Terraria.Item.tileBoost, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Player.TryGettingItemTraderFromBlock(), Terraria.Item.TurnToAir(), Terraria.Item.type, Terraria.Tile.type, and Terraria.Entity.width.
Referenced by Terraria.Player.PlaceThing().