TModLoader: Terraria.Player.PutItemInInventoryFromItemUsage
PutItemInInventoryFromItemUsage()
void Terraria.Player.PutItemInInventoryFromItemUsage (int type, int theSelectedItem = -1) inline
    {
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        for (int i = 0; i < 58; i++)
        {
            Item item = inventory[i];
            if (item.stack > 0 && item.type == type && item.stack < item.maxStack)
            {
                item.stack++;
                return;
            }
        }
        if (theSelectedItem >= 0 && (inventory[theSelectedItem].type == 0 || inventory[theSelectedItem].stack <= 0))
        {
            inventory[theSelectedItem].SetDefaults(type);
            return;
        }
        Item item2 = new Item();
        item2.SetDefaults(type);
        if (GetItem(whoAmI, item2, GetItemSettings.ItemCreatedFromItemUsage).stack > 0)
        {
            Item item3 = item2;
            if (theSelectedItem != -1)
            {
                item3 = inventory[theSelectedItem];
            }
            int number = Item.NewItem(new EntitySource_ItemUse(this, item3), (int)position.X, (int)position.Y, width, height, type, 1, noBroadcast: false, 0, noGrabDelay: true);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number, 1f);
            }
        }
        else
        {
            item2.position.X = base.Center.X - (float)(item2.width / 2);
            item2.position.Y = base.Center.Y - (float)(item2.height / 2);
            item2.active = true;
            PopupText.NewText(PopupTextContext.RegularItemPickup, item2, 0);
        }
    }
References Terraria.Player.GetItem(), Terraria.Entity.height, Terraria.Player.inventory, Terraria.GetItemSettings.ItemCreatedFromItemUsage, Terraria.Item.maxStack, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.PopupText.NewText(), Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, Terraria.Item.type, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.ItemCheck_UseBuckets().