TModLoader: Terraria.Player.DamageTileWithShovel
DamageTileWithShovel()
void Terraria.Player.DamageTileWithShovel (Player user, Item item, int x, int y) inline private
Definition at line 45295 of file Player.cs.
    {
        Tile tileSafely = Framing.GetTileSafely(x, y);
        if (TileID.Sets.CanBeDugByShovel[tileSafely.type])
        {
            int pickPower = 30;
            if (tileSafely.active() && (TileID.Sets.Conversion.Grass[tileSafely.type] || TileID.Sets.Conversion.JungleGrass[tileSafely.type] || tileSafely.type == 70 || tileSafely.type == 633))
            {
                PickTile(x, y, 100);
            }
            PickTile(x, y, pickPower);
        }
    }
References Terraria.ID.TileID.Sets.CanBeDugByShovel, Terraria.Framing.GetTileSafely(), Terraria.ID.TileID.Sets.Conversion.Grass, Terraria.ID.TileID.Sets.Conversion.JungleGrass, and Terraria.Player.PickTile().
Referenced by Terraria.Player.UseShovel().