TModLoader: Terraria.Player.ApplyDamageToNPC
ApplyDamageToNPC()
void Terraria.Player.ApplyDamageToNPC (NPC npc, int damage, float knockback, int direction, bool crit = false, DamageClass? damageType = null, bool damageVariation = false) inline
Deals damage to an NPC (and syncs the hit in multiplayer).
The damage will be affected by modifiers, armor pen, enemy resistances etc.
Will not apply damage class modifiers/knockback. Use M:Terraria.Player.GetTotalDamage``1 to adjust the damage before calling if necessary.
Will apply damage class based armor penetration.
Will exit early with no effect if M:Terraria.ModLoader.PlayerLoader.CanHitNPC(Terraria.Player,Terraria.NPC) returns false.
Parameters
npc The NPC to strike
damage The damage to deal to the NPC, before modifications, defense, resistances etc
knockback The amount of knockback to apply
direction The hit direction of the resulting strike (1 or -1)
crit Whether or not the strike is a crit
damageType Defaults to P:Terraria.ModLoader.DamageClass.Default
damageVariation Whether to apply damage variation. Defaults to false.
    {
        if (PlayerLoader.CanHitNPC(this, npc))
        {
            NPC.HitModifiers modifiers = npc.GetIncomingStrikeModifiers(damageType ?? DamageClass.Default, direction);
            PlayerLoader.ModifyHitNPC(this, npc, ref modifiers);
            ApplyBannerOffenseBuff(npc, ref modifiers);
            modifiers.ArmorPenetration += GetTotalArmorPenetration(damageType ?? DamageClass.Generic);
            StrikeNPCDirect(npc, modifiers.ToHitInfo(damage, crit, knockback, damageVariation, luck));
        }
    }
References Terraria.Player.ApplyBannerOffenseBuff(), Terraria.ModLoader.PlayerLoader.CanHitNPC(), Terraria.ModLoader.DamageClass.Default, Terraria.Entity.direction, Terraria.ModLoader.DamageClass.Generic, Terraria.NPC.GetIncomingStrikeModifiers(), Terraria.Player.GetTotalArmorPenetration(), Terraria.Player.luck, Terraria.ModLoader.PlayerLoader.ModifyHitNPC(), and Terraria.Player.StrikeNPCDirect().
Referenced by Terraria.Player.CollideWithNPCs(), Terraria.Player.DashMovement(), Terraria.Player.JumpMovement(), Terraria.Player.Update(), Terraria.Player.Update_NPCCollision(), and Terraria.Player.UpdateBuffs().