TModLoader: Terraria.Player.DropCoins
DropCoins()
long Terraria.Player.DropCoins () inline
    {
        IEntitySource itemSource_Death = GetItemSource_Death();
        long num = 0L;
        for (int i = 0; i < 59; i++)
        {
            if (inventory[i].IsACoin)
            {
                int num2 = Item.NewItem(itemSource_Death, (int)position.X, (int)position.Y, width, height, inventory[i].type);
                int num3 = inventory[i].stack / 2;
                if (Main.expertMode)
                {
                    num3 = (int)((double)inventory[i].stack * 0.25);
                }
                if (Main.masterMode)
                {
                    num3 = 0;
                }
                num3 = inventory[i].stack - num3;
                inventory[i].stack -= num3;
                if (inventory[i].type == 71)
                {
                    num += num3;
                }
                if (inventory[i].type == 72)
                {
                    num += (long)num3 * 100L;
                }
                if (inventory[i].type == 73)
                {
                    num += (long)num3 * 10000L;
                }
                if (inventory[i].type == 74)
                {
                    num += (long)num3 * 1000000L;
                }
                if (inventory[i].stack <= 0)
                {
                    inventory[i] = new Item();
                }
                Main.item[num2].stack = num3;
                Main.item[num2].velocity.Y = (float)Main.rand.Next(-20, 1) * 0.2f;
                Main.item[num2].velocity.X = (float)Main.rand.Next(-20, 21) * 0.2f;
                Main.item[num2].noGrabDelay = 100;
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, num2);
                }
                if (i == 58)
                {
                    Main.mouseItem = inventory[i].Clone();
                }
            }
        }
        lostCoins = num;
        lostCoinString = Main.ValueToCoins(lostCoins);
        return num;
    }
References Terraria.Item.Clone(), Terraria.Main.expertMode, Terraria.Player.GetItemSource_Death(), Terraria.Entity.height, Terraria.Player.inventory, Terraria.Main.item, Terraria.Player.lostCoins, Terraria.Player.lostCoinString, Terraria.Main.masterMode, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Item.noGrabDelay, Terraria.Entity.position, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Item.stack, Terraria.Item.type, Terraria.Main.ValueToCoins(), Terraria.Entity.velocity, and Terraria.Entity.width.
Referenced by Terraria.Player.KillMe().