TModLoader: Terraria.Player.GetProjectileSource_Item
GetProjectileSource_Item()
IEntitySource Terraria.Player.GetProjectileSource_Item (Item item) inline package
Definition at line 7831 of file Player.cs.
    {
        return GetSource_ItemUse(item);
    }
References Terraria.Player.GetSource_ItemUse().
Referenced by Terraria.Player.ApplyNPCOnHitEffects(), Terraria.Player.BloodButcherer_TryButchering(), Terraria.Player.HorsemansBlade_SpawnPumpkin(), Terraria.Player.ItemCheck_EmitHammushProjectiles(), Terraria.Player.ItemCheck_MeleeHitPVP(), Terraria.Player.QuickGrapple(), Terraria.Player.TentacleSpike_TrySpiking(), Terraria.Player.UpdateBuffs(), and Terraria.Player.Volcano_TrySpawningVolcano().