TModLoader: Terraria.Player.UpdateTeleportVisuals
UpdateTeleportVisuals()
void Terraria.Player.UpdateTeleportVisuals () inline
    {
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0290: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_0238: Unknown result type (might be due to invalid IL or missing references)
        //IL_023e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_0256: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bb: Unknown result type (might be due to invalid IL or missing references)
        if (!(teleportTime > 0f))
        {
            return;
        }
        if (teleportStyle == 0)
        {
            if ((float)Main.rand.Next(100) <= 100f * teleportTime * 2f)
            {
                int num = Dust.NewDust(new Vector2((float)getRect().X, (float)getRect().Y), getRect().Width, getRect().Height, 159);
                Main.dust[num].scale = teleportTime * 1.5f;
                Main.dust[num].noGravity = true;
                Dust obj = Main.dust[num];
                obj.velocity *= 1.1f;
            }
        }
        else if (teleportStyle == 1)
        {
            if ((float)Main.rand.Next(100) <= 100f * teleportTime)
            {
                int num2 = Dust.NewDust(new Vector2((float)getRect().X, (float)getRect().Y), getRect().Width, getRect().Height, 164);
                Main.dust[num2].scale = teleportTime * 1.5f;
                Main.dust[num2].noGravity = true;
                Dust obj2 = Main.dust[num2];
                obj2.velocity *= 1.1f;
            }
        }
        else if (teleportStyle == 2)
        {
            teleportTime = 0.005f;
        }
        else if (teleportStyle == 3)
        {
            teleportTime = 0.005f;
        }
        else if (teleportStyle == 4)
        {
            teleportTime -= 0.02f;
            if ((float)Main.rand.Next(100) <= 100f * teleportTime)
            {
                Dust obj3 = Main.dust[Dust.NewDust(position, width, height, 263)];
                obj3.color = PortalHelper.GetPortalColor(lastPortalColorIndex);
                obj3.noLight = true;
                obj3.noGravity = true;
                obj3.scale = 1.2f;
                obj3.fadeIn = 0.4f;
            }
        }
        else if (teleportStyle == 9)
        {
            Rectangle hitbox = base.Hitbox;
            ((Rectangle)(ref hitbox)).Inflate(5, 5);
            if ((float)Main.rand.Next(100) <= 100f * teleportTime)
            {
                TeleportPylonsSystem.SpawnInWorldDust(lastTeleportPylonStyleUsed, hitbox);
            }
        }
        teleportTime -= 0.005f;
    }
References Terraria.Main.dust, Terraria.GameContent.PortalHelper.GetPortalColor(), Terraria.Player.getRect(), Terraria.Entity.height, Terraria.Player.lastPortalColorIndex, Terraria.Player.lastTeleportPylonStyleUsed, Terraria.Dust.NewDust(), Terraria.Entity.position, Terraria.Main.rand, Terraria.GameContent.TeleportPylonsSystem.SpawnInWorldDust(), Terraria.Player.teleportStyle, Terraria.Player.teleportTime, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().