TModLoader: Terraria.Player.dropItemCheck
dropItemCheck()
void Terraria.Player.dropItemCheck () inline
Definition at line 5457 of file Player.cs.
    {
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        if (!Main.playerInventory)
        {
            noThrow = 0;
        }
        if (noThrow > 0)
        {
            noThrow--;
        }
        GetItemSettings getItemInDropItemCheck = GetItemSettings.GetItemInDropItemCheck;
        if (!Main.InGuideCraftMenu && Main.guideItem.type > 0)
        {
            Main.guideItem.position = base.Center;
            Item item = GetItem(whoAmI, Main.guideItem, getItemInDropItemCheck);
            if (item.stack > 0)
            {
                int num = Item.NewItem(new EntitySource_OverfullInventory(this), position, width, height, item, noBroadcast: false, noGrabDelay: true);
                Main.item[num].newAndShiny = false;
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, num, 1f);
                }
            }
            Main.guideItem = new Item();
        }
        if (!Main.InReforgeMenu && Main.reforgeItem.type > 0)
        {
            Main.reforgeItem.position = base.Center;
            Item item2 = GetItem(whoAmI, Main.reforgeItem, getItemInDropItemCheck);
            if (item2.stack > 0)
            {
                int num2 = Item.NewItem(new EntitySource_OverfullInventory(this), position, width, height, item2, noBroadcast: false, noGrabDelay: true);
                Main.item[num2].newAndShiny = false;
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, num2, 1f);
                }
            }
            Main.reforgeItem = new Item();
        }
        if (Main.myPlayer == whoAmI)
        {
            inventory[58] = Main.mouseItem.Clone();
        }
        bool flag = true;
        if (Main.mouseItem.type > 0 && Main.mouseItem.stack > 0)
        {
            if (!Main.gamePaused)
            {
                tileTargetX = (int)(((float)Main.mouseX + Main.screenPosition.X) / 16f);
                tileTargetY = (int)(((float)Main.mouseY + Main.screenPosition.Y) / 16f);
                if (gravDir == -1f)
                {
                    tileTargetY = (int)((Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY) / 16f);
                }
            }
            if (selectedItem != 58)
            {
                oldSelectItem = selectedItem;
            }
            selectedItem = 58;
            flag = false;
        }
        if (flag && selectedItem == 58 && ItemTimeIsZero && itemAnimation == 0)
        {
            selectedItem = oldSelectItem;
        }
        if (Main.mouseItem.type > 0 && !Main.playerInventory)
        {
            Main.mouseItem.position = base.Center;
            Item item3 = GetItem(whoAmI, Main.mouseItem, getItemInDropItemCheck);
            if (item3.stack > 0)
            {
                int num3 = Item.NewItem(new EntitySource_OverfullInventory(this), (int)position.X, (int)position.Y, width, height, item3.type, item3.stack, noBroadcast: false, Main.mouseItem.prefix, noGrabDelay: true);
                Main.item[num3] = item3.Clone();
                Main.item[num3].newAndShiny = false;
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, num3, 1f);
                }
            }
            Main.mouseItem = new Item();
            inventory[58] = new Item();
            Recipe.FindRecipes();
        }
        if (((controlThrow && releaseThrow && !inventory[selectedItem].favorited && inventory[selectedItem].type > 0 && !Main.drawingPlayerChat) || (((Main.mouseRight && !mouseInterface && Main.mouseRightRelease) || !Main.playerInventory) && Main.mouseItem.type > 0 && Main.mouseItem.stack > 0)) && noThrow <= 0)
        {
            DropSelectedItem();
        }
        if (Main.gamePaused && selectedItem == 58)
        {
            selectedItem = oldSelectItem;
        }
    }
References Terraria.Player.controlThrow, Terraria.Main.drawingPlayerChat, Terraria.Player.DropSelectedItem(), Terraria.Recipe.FindRecipes(), Terraria.Main.gamePaused, Terraria.Player.GetItem(), Terraria.GetItemSettings.GetItemInDropItemCheck, Terraria.Player.gravDir, Terraria.Main.guideItem, Terraria.Entity.height, Terraria.Main.InGuideCraftMenu, Terraria.Main.InReforgeMenu, Terraria.Player.inventory, Terraria.Main.item, Terraria.Player.itemAnimation, Terraria.Player.ItemTimeIsZero, Terraria.Player.mouseInterface, Terraria.Main.mouseItem, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Player.noThrow, Terraria.Player.oldSelectItem, Terraria.Main.playerInventory, Terraria.Entity.position, Terraria.Main.reforgeItem, Terraria.Player.releaseThrow, Terraria.Main.screenPosition, Terraria.Player.selectedItem, Terraria.NetMessage.SendData(), Terraria.Item.stack, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().