TModLoader: Terraria.Player.GetPreferredGolfBallToUse
GetPreferredGolfBallToUse()
void Terraria.Player.GetPreferredGolfBallToUse (out int projType) inline
Definition at line 50346 of file Player.cs.
    {
        projType = 721;
        Item item = inventory[selectedItem];
        if (!item.IsAir && item.shoot > 0 && ProjectileID.Sets.IsAGolfBall[item.shoot])
        {
            projType = item.shoot;
        }
        else
        {
            if (LoaderManager.Get<AccessorySlotLoader>().PreferredGolfBall(ref projType))
            {
                return;
            }
            for (int num = 19; num >= 0; num--)
            {
                if (IsItemSlotUnlockedAndUsable(num))
                {
                    _ = num % 10;
                    Item item2 = armor[num];
                    if (!item2.IsAir && item2.shoot > 0 && ProjectileID.Sets.IsAGolfBall[item2.shoot])
                    {
                        projType = item2.shoot;
                        return;
                    }
                }
            }
            for (int i = 0; i < 50; i++)
            {
                Item item3 = inventory[i];
                if (!item3.IsAir && item3.shoot > 0 && ProjectileID.Sets.IsAGolfBall[item3.shoot])
                {
                    projType = item3.shoot;
                    break;
                }
            }
        }
    }
References Terraria.Player.armor, Terraria.Player.inventory, Terraria.ID.ProjectileID.Sets.IsAGolfBall, Terraria.Item.IsAir, Terraria.Player.IsItemSlotUnlockedAndUsable(), Terraria.ModLoader.AccessorySlotLoader.PreferredGolfBall(), Terraria.Player.selectedItem, and Terraria.Item.shoot.
Referenced by Terraria.Player.TileInteractionsUse(), and Terraria.Player.TryPlacingAGolfBallNearANearbyTee().