TModLoader: Terraria.Player.SpawnHallucination
SpawnHallucination()
void Terraria.Player.SpawnHallucination (Item item) inline private
    {
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        if (whoAmI != Main.myPlayer)
        {
            return;
        }
        insanityShadowCooldown = Utils.Clamp(insanityShadowCooldown - 1, 0, 100);
        if (insanityShadowCooldown > 0)
        {
            return;
        }
        insanityShadowCooldown = Main.rand.Next(20, 101);
        float num = 500f;
        int damage = 18;
        _hallucinationCandidates.Clear();
        for (int i = 0; i < 200; i++)
        {
            NPC nPC = Main.npc[i];
            if (nPC.CanBeChasedBy(this) && !(Distance(nPC.Center) > num) && Collision.CanHitLine(position, width, height, nPC.position, nPC.width, nPC.height))
            {
                _hallucinationCandidates.Add(nPC);
            }
        }
        if (_hallucinationCandidates.Count != 0)
        {
            Projectile.RandomizeInsanityShadowFor(Main.rand.NextFromCollection(_hallucinationCandidates), isHostile: false, out var spawnposition, out var spawnvelocity, out var ai, out var ai2);
            Projectile.NewProjectile(new EntitySource_ItemUse(this, item), spawnposition, spawnvelocity, 964, damage, 0f, whoAmI, ai, ai2);
        }
    }
References Terraria.Player._hallucinationCandidates, Terraria.Collision.CanHitLine(), Terraria.Entity.Distance(), Terraria.Entity.height, Terraria.Player.insanityShadowCooldown, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Entity.position, Terraria.Main.rand, Terraria.Projectile.RandomizeInsanityShadowFor(), Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.GrantArmorBenefits().