TModLoader: Terraria.Player.ShootFromCannon
ShootFromCannon()
void Terraria.Player.ShootFromCannon (int x, int y) inline private
    {
        int num = 0;
        int num2 = Main.tile[x, y].frameX / 72;
        int type = inventory[selectedItem].type;
        if (num2 == 0 && type == 929)
        {
            num = 1;
        }
        else if (num2 == 1 && type == 1338)
        {
            num = 2;
        }
        else if (num2 == 2 && type == 1345)
        {
            num = 3;
        }
        if (num <= 0 || (num == 2 && !WorldGen.BunnyCannonCanFire()))
        {
            return;
        }
        cursorItemIconEnabled = true;
        if (ItemTimeIsZero && itemAnimation > 0 && controlUseItem)
        {
            int num3 = Main.tile[x, y].frameX / 18;
            int num4 = 0;
            int num5 = 0;
            while (num3 >= 4)
            {
                num4++;
                num3 -= 4;
            }
            num3 = x - num3;
            int num6;
            for (num6 = Main.tile[x, y].frameY / 18; num6 >= 3; num6 -= 3)
            {
                num5++;
            }
            num6 = y - num6;
            ApplyItemTime(inventory[selectedItem]);
            WorldGen.ShootFromCannon(num3, num6, num5, num, inventory[selectedItem].damage, 8f, Main.myPlayer, fromWire: false);
        }
    }
References Terraria.Player.ApplyItemTime(), Terraria.WorldGen.BunnyCannonCanFire(), Terraria.Player.controlUseItem, Terraria.Player.cursorItemIconEnabled, Terraria.Player.inventory, Terraria.Player.itemAnimation, Terraria.Player.ItemTimeIsZero, Terraria.Main.myPlayer, Terraria.Player.selectedItem, Terraria.WorldGen.ShootFromCannon(), Terraria.Main.tile, and Terraria.Item.type.
Referenced by Terraria.Player.PlaceThing_CannonBall().