TModLoader: Terraria.Player.UpdateHairDyeDust
UpdateHairDyeDust()
void Terraria.Player.UpdateHairDyeDust () inline
Definition at line 22594 of file Player.cs.
    {
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0225: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0348: Unknown result type (might be due to invalid IL or missing references)
        //IL_034e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0358: Unknown result type (might be due to invalid IL or missing references)
        //IL_035d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0362: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode != 2 && !Main.gamePaused && !dead && !ghost && !stoned && !frozen && hairDye == ContentSamples.CommonlyUsedContentSamples.TeamDyeShaderIndex)
        {
            if (Main.rand.Next(45) == 0)
            {
                int type = Main.rand.Next(139, 143);
                int num = Dust.NewDust(position, width, 8, type, 0f, 0f, 0, default(Color), 1.2f);
                Main.dust[num].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num].velocity.X += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num].velocity.Y -= 1f;
                Main.dust[num].scale *= 0.7f + (float)Main.rand.Next(-30, 31) * 0.01f;
                Dust obj = Main.dust[num];
                obj.velocity += velocity * 0.2f;
            }
            if (Main.rand.Next(225) == 0)
            {
                int type2 = Main.rand.Next(276, 283);
                int num2 = Gore.NewGore(new Vector2(position.X + (float)Main.rand.Next(width), position.Y + (float)Main.rand.Next(8)), velocity, type2);
                Main.gore[num2].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num2].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num2].scale *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                Main.gore[num2].velocity.X += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num2].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num2].velocity.Y -= 1f;
                Gore obj2 = Main.gore[num2];
                obj2.velocity += velocity * 0.2f;
            }
        }
    }
References Terraria.Player.dead, Terraria.Main.dust, Terraria.Player.frozen, Terraria.Main.gamePaused, Terraria.Player.ghost, Terraria.Main.gore, Terraria.Player.hairDye, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Player.stoned, Terraria.ID.ContentSamples.CommonlyUsedContentSamples.TeamDyeShaderIndex, Terraria.Entity.velocity, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().