TModLoader: Terraria.Player.Spawn_GetPositionAtWorldSpawn
Spawn_GetPositionAtWorldSpawn()
bool Terraria.Player.Spawn_GetPositionAtWorldSpawn (ref int floorX, ref int floorY) inline
Definition at line 36687 of file Player.cs.
    {
        int spawnTileX = Main.spawnTileX;
        int num = Main.spawnTileY;
        if (!Spawn_IsAreaAValidWorldSpawn(spawnTileX, num))
        {
            bool flag = false;
            if (!flag)
            {
                for (int i = 0; i < 30; i++)
                {
                    if (Spawn_IsAreaAValidWorldSpawn(spawnTileX, num - i))
                    {
                        num -= i;
                        flag = true;
                        break;
                    }
                }
            }
            if (!flag)
            {
                for (int j = 0; j < 30; j++)
                {
                    if (Spawn_IsAreaAValidWorldSpawn(spawnTileX, num - j))
                    {
                        num -= j;
                        flag = true;
                        break;
                    }
                }
            }
            if (flag)
            {
                floorX = spawnTileX;
                floorY = num;
                return true;
            }
            return false;
        }
        num = Spawn_DescendFromDefaultSpace(spawnTileX, num);
        floorX = spawnTileX;
        floorY = num;
        return false;
    }
References Terraria.Player.Spawn_DescendFromDefaultSpace(), Terraria.Player.Spawn_IsAreaAValidWorldSpawn(), Terraria.Main.spawnTileX, and Terraria.Main.spawnTileY.
Referenced by Terraria.Player.Shellphone_Spawn(), and Terraria.Player.Spawn_SetPositionAtWorldSpawn().