TModLoader: Terraria.Player.TryFindingShimmerFreeSpot
TryFindingShimmerFreeSpot()
Vector2? Terraria.Player.TryFindingShimmerFreeSpot () inline private
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        Point point = base.Top.ToTileCoordinates();
        int num = 60;
        Vector2? result = null;
        bool allowSolidTop = true;
        for (int i = 1; i < num; i += 2)
        {
            Vector2? vector = ShimmerHelper.FindSpotWithoutShimmer(this, point.X, point.Y, i, allowSolidTop);
            if (vector.HasValue)
            {
                result = vector.Value;
                break;
            }
        }
        FindSpawn();
        if (!CheckSpawn(SpawnX, SpawnY))
        {
            SpawnX = -1;
            SpawnY = -1;
        }
        if (!result.HasValue && SpawnX != -1 && SpawnY != -1)
        {
            for (int j = 1; j < num; j += 2)
            {
                Vector2? vector2 = ShimmerHelper.FindSpotWithoutShimmer(this, SpawnX, SpawnY, j, allowSolidTop);
                if (vector2.HasValue)
                {
                    result = vector2.Value;
                    break;
                }
            }
        }
        if (!result.HasValue)
        {
            for (int k = 1; k < num; k += 2)
            {
                Vector2? vector3 = ShimmerHelper.FindSpotWithoutShimmer(this, Main.spawnTileX, Main.spawnTileY, k, allowSolidTop);
                if (vector3.HasValue)
                {
                    result = vector3.Value;
                    break;
                }
            }
        }
        return result;
    }
References Terraria.Player.CheckSpawn(), Terraria.Player.FindSpawn(), Terraria.GameContent.ShimmerHelper.FindSpotWithoutShimmer(), Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, Terraria.Player.SpawnX, and Terraria.Player.SpawnY.
Referenced by Terraria.Player.ShimmerUnstuck().