TModLoader: Terraria.Player.ItemCheck_ManageRightClickFeatures_ShieldRaise
ItemCheck_ManageRightClickFeatures_ShieldRaise()
void Terraria.Player.ItemCheck_ManageRightClickFeatures_ShieldRaise (bool theGeneralCheck) inline
Definition at line 29377 of file Player.cs.
    {
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0113: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        bool mouseRight = PlayerInput.Triggers.JustPressed.MouseRight;
        if (whoAmI != Main.myPlayer)
        {
            mouseRight = shieldRaised;
            theGeneralCheck = shieldRaised;
        }
        bool shouldGuard = false;
        bool flag = inventory[selectedItem].type == 3823 || inventory[selectedItem].type == 4760;
        if (theGeneralCheck && flag && hasRaisableShield && !mount.Active && (itemAnimation == 0 || mouseRight))
        {
            shouldGuard = true;
        }
        if (shield_parry_cooldown > 0)
        {
            shield_parry_cooldown--;
            if (shield_parry_cooldown == 0)
            {
                SoundEngine.PlaySound(25, base.Center);
                for (int i = 0; i < 10; i++)
                {
                    int num = Dust.NewDust(base.Center + new Vector2((float)(direction * 6 + ((direction == -1) ? (-10) : 0)), -14f), 10, 16, 45, 0f, 0f, 255, new Color(255, 100, 0, 127), (float)Main.rand.Next(10, 16) * 0.1f);
                    Main.dust[num].noLight = true;
                    Main.dust[num].noGravity = true;
                    Dust obj = Main.dust[num];
                    obj.velocity *= 0.5f;
                }
            }
        }
        if (shieldParryTimeLeft > 0 && ++shieldParryTimeLeft > 20)
        {
            shieldParryTimeLeft = 0;
        }
        TryTogglingShield(shouldGuard);
    }
References Terraria.Mount.Active, Terraria.Entity.direction, Terraria.Main.dust, Terraria.Player.hasRaisableShield, Terraria.Player.inventory, Terraria.Player.itemAnimation, Terraria.Player.mount, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Player.selectedItem, Terraria.Player.shield_parry_cooldown, Terraria.Player.shieldParryTimeLeft, Terraria.Player.shieldRaised, Terraria.GameInput.PlayerInput.Triggers, Terraria.Player.TryTogglingShield(), Terraria.Item.type, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ItemCheck_ManageRightClickFeatures().