TModLoader: Terraria.Player.SporeSac
SporeSac()
void Terraria.Player.SporeSac (Item sourceItem) inline
Definition at line 41568 of file Player.cs.
    {
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_0118: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_0335: Unknown result type (might be due to invalid IL or missing references)
        //IL_033c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
        int damage = 70;
        float knockBack = 1.5f;
        if (Main.rand.Next(15) != 0)
        {
            return;
        }
        int num = 0;
        for (int i = 0; i < 1000; i++)
        {
            if (Main.projectile[i].active && Main.projectile[i].owner == whoAmI && (Main.projectile[i].type == 567 || Main.projectile[i].type == 568))
            {
                num++;
            }
        }
        if (Main.rand.Next(15) < num || num >= 10)
        {
            return;
        }
        int num2 = 50;
        int num3 = 24;
        int num4 = 90;
        for (int j = 0; j < num2; j++)
        {
            int num5 = Main.rand.Next(200 - j * 2, 400 + j * 2);
            Vector2 center = base.Center;
            center.X += Main.rand.Next(-num5, num5 + 1);
            center.Y += Main.rand.Next(-num5, num5 + 1);
            if (Collision.SolidCollision(center, num3, num3) || Collision.WetCollision(center, num3, num3))
            {
                continue;
            }
            center.X += num3 / 2;
            center.Y += num3 / 2;
            if (!Collision.CanHit(new Vector2(base.Center.X, position.Y), 1, 1, center, 1, 1) && !Collision.CanHit(new Vector2(base.Center.X, position.Y - 50f), 1, 1, center, 1, 1))
            {
                continue;
            }
            int num6 = (int)center.X / 16;
            int num7 = (int)center.Y / 16;
            bool flag = false;
            if (Main.rand.Next(3) == 0 && Main.tile[num6, num7] != null && Main.tile[num6, num7].wall > 0)
            {
                flag = true;
            }
            else
            {
                center.X -= num4 / 2;
                center.Y -= num4 / 2;
                if (Collision.SolidCollision(center, num4, num4))
                {
                    center.X += num4 / 2;
                    center.Y += num4 / 2;
                    flag = true;
                }
                else if (Main.tile[num6, num7] != null && Main.tile[num6, num7].active() && Main.tile[num6, num7].type == 19)
                {
                    flag = true;
                }
            }
            if (!flag)
            {
                continue;
            }
            for (int k = 0; k < 1000; k++)
            {
                if (Main.projectile[k].active && Main.projectile[k].owner == whoAmI && Main.projectile[k].aiStyle == 105)
                {
                    Vector2 val = center - Main.projectile[k].Center;
                    if (((Vector2)(ref val)).Length() < 48f)
                    {
                        flag = false;
                        break;
                    }
                }
            }
            if (flag && Main.myPlayer == whoAmI)
            {
                Projectile.NewProjectile(GetProjectileSource_Accessory(sourceItem), center.X, center.Y, 0f, 0f, 567 + Main.rand.Next(2), damage, knockBack, whoAmI);
                break;
            }
        }
    }
References Terraria.Entity.active, Terraria.Projectile.aiStyle, Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Player.GetProjectileSource_Accessory(), Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Projectile.owner, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Collision.SolidCollision(), Terraria.Main.tile, Terraria.Projectile.type, Terraria.Collision.WetCollision(), and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ApplyEquipFunctional().