TModLoader: Terraria.Player.SmartSelect_PickToolForStrategy
SmartSelect_PickToolForStrategy()
void Terraria.Player.SmartSelect_PickToolForStrategy (int tX, int tY, int toolStrategy, bool wetTile) inline private
Definition at line 15850 of file Player.cs.
    {
        for (int i = 0; i < 50; i++)
        {
            int type = inventory[i].type;
            switch (toolStrategy)
            {
            case 0:
                if (ItemID.Sets.Torches[type])
                {
                    SmartSelect_SelectItem(i);
                    return;
                }
                if (ItemID.Sets.Glowsticks[type])
                {
                    SmartSelect_SelectItem(i);
                }
                break;
            case 1:
                if (inventory[i].hammer > 0)
                {
                    SmartSelect_SelectItem(i);
                    return;
                }
                break;
            case 2:
                if (inventory[i].axe > 0)
                {
                    SmartSelect_SelectItem(i);
                    return;
                }
                break;
            case 3:
                if (inventory[i].pick > 0)
                {
                    SmartSelect_SelectItem(i);
                    return;
                }
                break;
            case 4:
                if (inventory[i].type != 930 && ItemID.Sets.Torches[type] && !ItemID.Sets.WaterTorches[type] && !ItemID.Sets.Glowsticks[type])
                {
                    if (nonTorch == -1)
                    {
                        nonTorch = selectedItem;
                    }
                    if (inventory[selectedItem].createTile < 0 || !TileID.Sets.Torch[inventory[selectedItem].createTile])
                    {
                        selectedItem = i;
                    }
                    break;
                }
                if (ItemID.Sets.Glowsticks[type] && wetTile)
                {
                    SmartSelect_SelectItem(i);
                    return;
                }
                if (type == 930 && wetTile)
                {
                    bool flag = false;
                    for (int num = 57; num >= 0; num--)
                    {
                        if (inventory[num].ammo == inventory[i].useAmmo && inventory[num].stack > 0)
{
                            flag = true;
                            break;
                        }
                    }
                    if (!flag && !ItemLoader.NeedsAmmo(inventory[i], this))
                    {
                        flag = true;
                    }
                    if (flag)
                    {
                        SmartSelect_SelectItem(i);
                        return;
                    }
                }
                else if (ItemID.Sets.WaterTorches[type])
                {
                    SmartSelect_SelectItem(i);
                    return;
                }
                break;
            case 5:
            {
                if (ItemID.Sets.Torches[type])
                {
                    if (nonTorch == -1)
                    {
                        nonTorch = selectedItem;
                    }
                    if (inventory[selectedItem].createTile < 0 || !TileID.Sets.Torch[inventory[selectedItem].createTile])
                    {
                        selectedItem = i;
                    }
                    break;
                }
                int thisType = type;
                switch (thisType)
                {
                case 930:
                {
                    bool flag2 = false;
                    for (int num2 = 57; num2 >= 0; num2--)
                    {
                        if (inventory[num2].ammo == inventory[i].useAmmo && inventory[num2].stack > 0)
{
                            flag2 = true;
                            break;
                        }
                    }
                    if (flag2)
                    {
                        SmartSelect_SelectItem(i);
                        return;
                    }
                    goto end_IL_0016;
                }
                default:
                    if (!ItemID.Sets.Glowsticks[thisType])
                    {
                        goto end_IL_0016;
                    }
                    break;
                case 282:
                case 286:
                case 3002:
                case 3112:
                case 4776:
                    break;
                }
                SmartSelect_SelectItem(i);
                return;
            }
            case 6:
            {
                int num3 = Main.tile[tX, tY].frameX / 72;
                int num4 = -1;
                switch (num3)
                {
                case 0:
                    num4 = 929;
                    break;
                case 1:
                    num4 = 1338;
                    break;
                case 2:
                    num4 = 1345;
                    break;
                }
                if (type == num4)
                {
                    SmartSelect_SelectItem(i);
                    return;
                }
                break;
            }
            case 7:
            {
                ItemTrader itemTrader = TryGettingItemTraderFromBlock(Main.tile[tX, tY]);
                if (itemTrader != null && itemTrader.TryGetTradeOption(inventory[i], out var _))
                {
                    SmartSelect_SelectItem(i);
                    return;
                }
                if (ItemID.Sets.ExtractinatorMode[type] >= 0)
                {
                    SmartSelect_SelectItem(i);
                    return;
                }
                break;
            }
            case 8:
                {
                    if (ItemID.Sets.IsPaintScraper[type])
                    {
                        SmartSelect_SelectItem(i);
                        return;
                    }
                    break;
                }
                end_IL_0016:
                break;
            }
        }
    }
References Terraria.Item.createTile, Terraria.ID.ItemID.Sets.ExtractinatorMode, Terraria.ID.ItemID.Sets.Glowsticks, Terraria.Player.inventory, Terraria.ID.ItemID.Sets.IsPaintScraper, Terraria.ModLoader.ItemLoader.NeedsAmmo(), Terraria.Player.nonTorch, Terraria.Player.selectedItem, Terraria.Player.SmartSelect_SelectItem(), Terraria.Main.tile, Terraria.ID.TileID.Sets.Torch, Terraria.ID.ItemID.Sets.Torches, Terraria.Player.TryGettingItemTraderFromBlock(), Terraria.Item.type, and Terraria.ID.ItemID.Sets.WaterTorches.
Referenced by Terraria.Player.SmartSelectLookup().