TModLoader: Terraria.Player.ItemCheck_ApplyHoldStyle_Inner
ItemCheck_ApplyHoldStyle_Inner()
void Terraria.Player.ItemCheck_ApplyHoldStyle_Inner (float mountOffset, Item sItem, Rectangle heldItemFrame) inline private
Definition at line 51042 of file Player.cs.
    {
        //IL_0cbc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c78: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0385: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e11: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e21: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e26: Unknown result type (might be due to invalid IL or missing references)
        //IL_0601: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0efc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d58: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0767: Unknown result type (might be due to invalid IL or missing references)
        //IL_0788: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_081e: Unknown result type (might be due to invalid IL or missing references)
        //IL_084c: Unknown result type (might be due to invalid IL or missing references)
        //IL_086c: Unknown result type (might be due to invalid IL or missing references)
        //IL_025b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0272: Unknown result type (might be due to invalid IL or missing references)
        //IL_0278: Unknown result type (might be due to invalid IL or missing references)
        //IL_089b: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0313: Unknown result type (might be due to invalid IL or missing references)
        //IL_031d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0322: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0912: Unknown result type (might be due to invalid IL or missing references)
        //IL_0917: Unknown result type (might be due to invalid IL or missing references)
        //IL_091e: Unknown result type (might be due to invalid IL or missing references)
        //IL_092c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0932: Unknown result type (might be due to invalid IL or missing references)
        //IL_0954: Unknown result type (might be due to invalid IL or missing references)
        //IL_0963: Unknown result type (might be due to invalid IL or missing references)
        //IL_0968: Unknown result type (might be due to invalid IL or missing references)
        //IL_096d: Unknown result type (might be due to invalid IL or missing references)
        if (isPettingAnimal)
        {
            int num10 = miscCounter % 14 / 7;
            CompositeArmStretchAmount stretch = CompositeArmStretchAmount.ThreeQuarters;
            if (num10 == 1)
            {
                stretch = CompositeArmStretchAmount.Full;
            }
            float num2 = 0.3f;
            if (isTheAnimalBeingPetSmall)
            {
                num2 = 0.2f;
            }
            SetCompositeArmBack(enabled: true, stretch, (float)Math.PI * -2f * num2 * (float)direction);
        }
        if (!CanVisuallyHoldItem(sItem))
        {
            return;
        }
        if (sItem.holdStyle == 1 && !pulley)
        {
            if (Main.dedServ)
            {
                itemLocation.X = position.X + (float)width * 0.5f + 20f * (float)direction;
            }
            else if (sItem.type == 930)
            {
                itemLocation.X = position.X + (float)(width / 2) * 0.5f - 12f - (float)(2 * direction);
                float x = position.X + (float)(width / 2) + (float)(38 * direction);
                if (direction == 1)
                {
                    x -= 10f;
                }
                float y = MountedCenter.Y - 4f * gravDir;
                if (gravDir == -1f)
                {
                    y -= 8f;
                }
                RotateRelativePoint(ref x, ref y);
                int num3 = 0;
                for (int i = 54; i < 58; i++)
                {
                    if (inventory[i].stack > 0 && inventory[i].ammo == 931)
                    {
                        num3 = inventory[i].type;
                        break;
                    }
                }
                if (num3 == 0)
                {
                    for (int j = 0; j < 54; j++)
                    {
                        if (inventory[j].stack > 0 && inventory[j].ammo == 931)
{
                            num3 = inventory[j].type;
                            break;
                        }
                    }
                }
                switch (num3)
                {
                case 931:
                    num3 = 127;
                    break;
                case 1614:
                    num3 = 187;
                    break;
                case 5377:
                    num3 = 169;
                    break;
                case 5378:
                    num3 = 75;
                    break;
                case 5379:
                    num3 = 66;
                    break;
                case 5380:
                    num3 = 310;
                    break;
                }
                if (num3 > 0)
                {
                    int num4 = Dust.NewDust(new Vector2(x, y + gfxOffY), 6, 6, num3, 0f, 0f, 100, default(Color), 1.6f);
                    Main.dust[num4].noGravity = true;
                    Main.dust[num4].velocity.Y -= 4f * gravDir;
                    if (num3 == 66)
                    {
                        Main.dust[num4].color = Main.hslToRgb(Main.GlobalTimeWrappedHourly * 0.6f % 1f, 1f, 0.5f);
                        Main.dust[num4].scale *= 0.5f;
                        Dust obj = Main.dust[num4];
                        obj.velocity *= 0.75f;
                    }
                }
            }
            else if (sItem.type == 968)
            {
                itemLocation.X = position.X + (float)width * 0.5f + (float)(8 * direction);
                if (whoAmI == Main.myPlayer)
                {
                    int num5 = (int)(itemLocation.X + (float)heldItemFrame.Width * 0.8f * (float)direction) / 16;
                    int num6 = (int)(itemLocation.Y + mountOffset + (float)(heldItemFrame.Height / 2)) / 16;
                    if (Main.tile[num5, num6] == null)
                    {
                        Main.tile[num5, num6] = default(Tile);
                    }
                    if (Main.tile[num5, num6].active() && TileID.Sets.Campfire[Main.tile[num5, num6].type] && Main.tile[num5, num6].frameY < 54)
                    {
                        miscTimer++;
                        if (Main.rand.Next(5) == 0)
{
                            miscTimer++;
                        }
                        if (miscTimer > 900)
{
                            miscTimer = 0;
                            sItem.SetDefaults(969);
                            if (selectedItem == 58)
{
                                Main.mouseItem.SetDefaults(969);
                            }
                            for (int k = 0; k < 58; k++)
{
                                if (inventory[k].type == sItem.type && k != selectedItem && inventory[k].stack < inventory[k].maxStack)
{
                                    SoundEngine.PlaySound(7);
                                    inventory[k].stack++;
                                    sItem.SetDefaults();
                                    if (selectedItem == 58)
{
                                        Main.mouseItem.SetDefaults();
                                    }
                                }
                            }
                        }
                    }
                    else
                    {
                        miscTimer = 0;
                    }
                }
            }
            else if (sItem.type == 856)
            {
                itemLocation.X = position.X + (float)width * 0.5f + (float)(4 * direction);
            }
            else if (sItem.fishingPole > 0)
            {
                itemLocation.X = position.X + (float)width * 0.5f + (float)heldItemFrame.Width * 0.18f * (float)direction;
            }
            else
            {
                itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f + 2f) * (float)direction;
                if (sItem.type == 282 || sItem.type == 286 || sItem.type == 3112 || sItem.type == 4776)
                {
                    itemLocation.X -= direction * 2;
                    itemLocation.Y += 4f;
                }
                else if (sItem.type == 3002)
                {
                    itemLocation.X -= 4 * direction;
                    itemLocation.Y += 2f;
                }
            }
            itemLocation.Y = position.Y + 24f + mountOffset;
            if (sItem.type == 856)
            {
                itemLocation.Y = position.Y + 34f + mountOffset;
            }
            if (sItem.type == 930)
            {
                itemLocation.Y = position.Y + 9f + mountOffset;
            }
            if (sItem.fishingPole > 0)
            {
                itemLocation.Y += 4f;
            }
            else if (sItem.type == 3476)
            {
                itemLocation.X = base.Center.X + (float)(14 * direction);
                itemLocation.Y = MountedCenter.Y;
            }
            else if (sItem.type == 3779)
            {
                itemLocation.X = base.Center.X + (float)(6 * direction);
                itemLocation.Y = MountedCenter.Y + 6f;
            }
            else if (sItem.type == 4952)
            {
                itemLocation.X = base.Center.X + (float)(2 * direction);
                itemLocation.Y = MountedCenter.Y + 26f;
            }
            else if (sItem.type == 353)
            {
                itemLocation.X = base.Center.X + (float)(6 * direction);
                itemLocation.Y = MountedCenter.Y + 11f;
            }
            else if (ItemID.Sets.IsFood[sItem.type])
            {
                itemLocation.X = base.Center.X + (float)(4 * direction);
                itemLocation.Y = MountedCenter.Y + (float)(heldItemFrame.Height / 2);
            }
            else if (sItem.type == 4049 && Main.rand.Next(4) == 0)
            {
                Dust dust = Dust.NewDustPerfect(base.Center + new Vector2((float)(direction * 23), gravDir * 6f), 31, Vector2.Zero, 127, default(Color), 0.7f);
                dust.noGravity = true;
                dust.velocity = Main.rand.NextVector2Circular(1f, 1f) + new Vector2(0f, -1f);
            }
            itemRotation = 0f;
            if (gravDir == -1f)
            {
                itemRotation = 0f - itemRotation;
                itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y) + mountOffset;
                if (sItem.type == 930)
                {
                    itemLocation.Y -= 24f;
                }
            }
        }
        else if (sItem.holdStyle == 2 && !pulley)
        {
            if (sItem.type == 946 || sItem.type == 4707)
            {
                itemRotation = 0f;
                itemLocation.X = position.X + (float)width * 0.5f - (float)(16 * direction);
                itemLocation.Y = position.Y + 22f + mountOffset;
                fallStart = (int)(position.Y / 16f);
                if (gravDir == -1f)
                {
                    itemRotation = 0f - itemRotation;
                    itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
                    if (velocity.Y < -2f && !controlDown)
                    {
                        velocity.Y = -2f;
                    }
                }
                else if (velocity.Y > 2f && !controlDown)
                {
                    velocity.Y = 2f;
                }
            }
            else
            {
                itemLocation.X = position.X + (float)width * 0.5f + (float)(6 * direction);
                itemLocation.Y = position.Y + 16f + mountOffset;
                itemRotation = 0.79f * (float)(-direction);
                if (gravDir == -1f)
                {
                    itemRotation = 0f - itemRotation;
                    itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
                }
            }
        }
        else if (sItem.holdStyle == 3 && !pulley)
        {
            if (!Main.dedServ)
            {
                itemLocation.X = position.X + (float)width * 0.5f - (float)heldItemFrame.Width * 0.5f - (float)(direction * 2);
                itemLocation.Y = MountedCenter.Y - (float)heldItemFrame.Height * 0.5f;
                itemRotation = 0f;
            }
        }
        else if (sItem.holdStyle == 4)
        {
            if (!Main.dedServ)
            {
                float num7 = Utils.ToRotation(new Vector2((float)(10 * direction), 10f)) + (float)Math.PI / 4f;
                itemRotation = num7;
                if (direction == -1)
                {
                    itemRotation += (float)Math.PI / 2f;
                }
                CompositeArmStretchAmount stretch2 = CompositeArmStretchAmount.Full;
                CompositeArmStretchAmount stretch3 = CompositeArmStretchAmount.ThreeQuarters;
                float num8 = -(float)Math.PI / 10f;
                if (direction == -1)
                {
                    num8 *= -1f;
                }
                float num9 = itemRotation - (float)Math.PI / 4f + (float)Math.PI;
                if (direction == 1)
                {
                    num9 += (float)Math.PI / 2f;
                }
                float rotation = num9 + num8;
                float rotation2 = num9 - num8;
                Vector2 vector = (num9 + (float)Math.PI / 2f).ToRotationVector2() * 2f;
                itemLocation = MountedCenter.Floor() + vector;
                SetCompositeArmFront(enabled: true, stretch2, rotation);
                SetCompositeArmBack(enabled: true, stretch3, rotation2);
                FlipItemLocationAndRotationForGravity();
            }
        }
        else if (sItem.holdStyle == 5 && !pulley)
        {
            if (!Main.dedServ)
            {
                itemRotation = 0f;
                itemLocation.X = base.Center.X - (float)(8 * direction);
                itemLocation.Y = position.Y + 40f + mountOffset;
                Vector2 vector2 = Main.OffsetsPlayerHeadgear[bodyFrame.Y / 56];
                itemLocation += vector2;
                CompositeArmStretchAmount stretch4 = CompositeArmStretchAmount.Quarter;
                SetCompositeArmBack(enabled: true, stretch4, -(float)Math.PI / 4f * (float)direction);
                CompositeArmStretchAmount stretch5 = CompositeArmStretchAmount.Full;
                SetCompositeArmFront(enabled: true, stretch5, -0.39269912f * (float)direction);
                FlipItemLocationAndRotationForGravity();
            }
        }
        else if (sItem.holdStyle == 6 && !pulley && !Main.dedServ)
        {
            itemRotation = 0f;
            itemLocation.X = base.Center.X + (float)(8 * direction);
            itemLocation.Y = position.Y + 40f + mountOffset - 2f;
            Vector2 vector3 = Main.OffsetsPlayerHeadgear[bodyFrame.Y / 56];
            itemLocation += vector3;
            CompositeArmStretchAmount stretch6 = CompositeArmStretchAmount.ThreeQuarters;
            SetCompositeArmBack(enabled: true, stretch6, (float)Math.PI * -3f / 5f * (float)direction);
            FlipItemLocationAndRotationForGravity();
        }
    }
References Terraria.ID.TileID.Sets.Campfire, Terraria.Player.CanVisuallyHoldItem(), Terraria.Player.controlDown, Terraria.Main.dedServ, Terraria.Entity.direction, Terraria.Main.dust, Terraria.Player.fallStart, Terraria.Player.FlipItemLocationAndRotationForGravity(), Terraria.Player.gfxOffY, Terraria.Main.GlobalTimeWrappedHourly, Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Main.hslToRgb(), Terraria.Player.inventory, Terraria.ID.ItemID.Sets.IsFood, Terraria.Player.isPettingAnimal, Terraria.Player.isTheAnimalBeingPetSmall, Terraria.Player.itemLocation, Terraria.Player.itemRotation, Terraria.Item.maxStack, Terraria.Player.miscCounter, Terraria.Player.miscTimer, Terraria.Player.MountedCenter, Terraria.Main.mouseItem, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Main.OffsetsPlayerHeadgear, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Player.pulley, Terraria.Main.rand, Terraria.Player.RotateRelativePoint(), Terraria.Player.selectedItem, Terraria.Player.SetCompositeArmBack(), Terraria.Player.SetCompositeArmFront(), Terraria.Item.stack, Terraria.Main.tile, Terraria.Utils.ToRotation(), Terraria.Item.type, Terraria.Entity.velocity, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.ItemCheck_ApplyHoldStyle().