TModLoader: Terraria.Player.QuickStackAllChests
QuickStackAllChests()
void Terraria.Player.QuickStackAllChests () inline
Definition at line 21144 of file Player.cs.
    {
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_041e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_050e: Unknown result type (might be due to invalid IL or missing references)
        if (HasLockedInventory())
        {
            return;
        }
        List<int> nearbyContainerProjectilesList = GetNearbyContainerProjectilesList();
        for (int i = 0; i < nearbyContainerProjectilesList.Count; i++)
        {
            Projectile projectile = Main.projectile[nearbyContainerProjectilesList[i]];
            if (projectile.TryGetContainerIndex(out var containerIndex))
            {
                ContainerTransferContext context = ContainerTransferContext.FromProjectile(projectile);
                int num = chest;
                chest = containerIndex;
                ChestUI.QuickStack(context);
                if (useVoidBag())
                {
                    ChestUI.QuickStack(context, voidStack: true);
                }
                chest = num;
            }
        }
        int num2 = 39;
        int num3 = (int)(base.Center.X / 16f);
        int num4 = (int)(base.Center.Y / 16f);
        for (int j = num3 - num2; j <= num3 + num2; j++)
        {
            if (j < 0 || j >= Main.maxTilesX)
            {
                continue;
            }
            for (int k = num4 - num2; k <= num4 + num2; k++)
            {
                if (k < 0 || k >= Main.maxTilesY)
                {
                    continue;
                }
                int num5 = 0;
                if (Main.tile[j, k].type == 29)
                {
                    num5 = -2;
                }
                else if (Main.tile[j, k].type == 97)
                {
                    num5 = -3;
                }
                else if (Main.tile[j, k].type == 463)
                {
                    num5 = -4;
                }
                else if (Main.tile[j, k].type == 491)
                {
                    num5 = -5;
                }
                if (num5 >= 0)
                {
                    continue;
                }
                Vector2 val = new Vector2((float)(j * 16 + 8), (float)(k * 16 + 8)) - base.Center;
                if (((Vector2)(ref val)).Length() < 600f)
                {
                    ContainerTransferContext context2 = ContainerTransferContext.FromBlockPosition(j, k);
                    int num6 = chest;
                    chest = num5;
                    ChestUI.QuickStack(context2);
                    if (useVoidBag())
                    {
                        ChestUI.QuickStack(context2, voidStack: true);
                    }
                    chest = num6;
                }
            }
        }
        if (Main.netMode == 1)
        {
            for (int l = 10; l < 50; l++)
            {
                if (inventory[l].type > 0 && inventory[l].stack > 0 && !inventory[l].favorited && !inventory[l].IsACoin)
                {
                    NetMessage.SendData(5, -1, -1, null, whoAmI, PlayerItemSlotID.Inventory0 + l, inventory[l].prefix);
                    NetMessage.SendData(85, -1, -1, null, PlayerItemSlotID.Inventory0 + l);
                    inventoryChestStack[l] = true;
                }
            }
            if (!useVoidBag())
            {
                return;
            }
            for (int m = 0; m < 40; m++)
            {
                if (bank4.item[m].type > 0 && bank4.item[m].stack > 0 && !bank4.item[m].favorited && !bank4.item[m].IsACoin)
                {
                    NetMessage.SendData(5, -1, -1, null, whoAmI, PlayerItemSlotID.Bank4_0 + m, bank4.item[m].prefix);
                    NetMessage.SendData(85, -1, -1, null, PlayerItemSlotID.Bank4_0 + m);
                    disableVoidBag = m;
                }
            }
            return;
        }
        for (int n = 10; n < 50; n++)
        {
            if (inventory[n].type > 0 && inventory[n].stack > 0 && !inventory[n].favorited && !inventory[n].IsACoin)
            {
                int type = inventory[n].type;
                _ = inventory[n].stack;
                inventory[n] = Chest.PutItemInNearbyChest(inventory[n], base.Center);
                if (inventory[n].type == type)
                {
                    _ = inventory[n].stack;
                }
            }
        }
        if (!useVoidBag())
        {
            return;
        }
        for (int num7 = 0; num7 < 40; num7++)
        {
            if (bank4.item[num7].type > 0 && bank4.item[num7].stack > 0 && !bank4.item[num7].favorited && !bank4.item[num7].IsACoin)
            {
                int type2 = bank4.item[num7].type;
                _ = bank4.item[num7].stack;
                bank4.item[num7] = Chest.PutItemInNearbyChest(bank4.item[num7], base.Center);
                if (bank4.item[num7].type == type2)
                {
                    _ = bank4.item[num7].stack;
                }
            }
        }
    }
References Terraria.Player.bank4, Terraria.ID.PlayerItemSlotID.Bank4_0, Terraria.Player.chest, Terraria.Player.disableVoidBag, Terraria.Item.favorited, Terraria.DataStructures.ContainerTransferContext.FromBlockPosition(), Terraria.DataStructures.ContainerTransferContext.FromProjectile(), Terraria.Player.GetNearbyContainerProjectilesList(), Terraria.Player.HasLockedInventory(), Terraria.Player.inventory, Terraria.ID.PlayerItemSlotID.Inventory0, Terraria.Player.inventoryChestStack, Terraria.Item.IsACoin, Terraria.Chest.item, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Item.prefix, Terraria.Main.projectile, Terraria.Chest.PutItemInNearbyChest(), Terraria.UI.ChestUI.QuickStack(), Terraria.NetMessage.SendData(), Terraria.Item.stack, Terraria.Main.tile, Terraria.Projectile.TryGetContainerIndex(), Terraria.Item.type, Terraria.Player.useVoidBag(), and Terraria.Entity.whoAmI.