TModLoader: Terraria.Player.Spawn_IsAreaAValidWorldSpawn
Spawn_IsAreaAValidWorldSpawn()
bool Terraria.Player.Spawn_IsAreaAValidWorldSpawn (int floorX, int floorY) inline private
    {
        for (int i = floorX - 1; i < floorX + 2; i++)
        {
            for (int j = floorY - 3; j < floorY; j++)
            {
                if (Main.tile[i, j] != null)
                {
                    if (Main.tile[i, j].nactive() && Main.tileSolid[Main.tile[i, j].type] && !Main.tileSolidTop[Main.tile[i, j].type])
                    {
                        return false;
                    }
                    if (Main.tile[i, j].liquid > 0)
                    {
                        return false;
                    }
                }
            }
        }
        return true;
    }
References Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Main.tileSolidTop.
Referenced by Terraria.Player.Shellphone_Spawn(), Terraria.Player.Spawn_GetPositionAtWorldSpawn(), and Terraria.Player.Spawn_SetPositionAtWorldSpawn().