TModLoader: Terraria.Player.ItemCheck_ReleaseCritter
ItemCheck_ReleaseCritter()
void Terraria.Player.ItemCheck_ReleaseCritter (Item sItem) inline private
Definition at line 43213 of file Player.cs.
    {
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        if (sItem.makeNPC == 614)
        {
            ApplyItemTime(sItem);
            NPC.ReleaseNPC((int)base.Center.X, (int)base.Bottom.Y, sItem.makeNPC, sItem.placeStyle, whoAmI);
        }
        else if (position.X / 16f - (float)tileRangeX - (float)sItem.tileBoost <= (float)tileTargetX && (position.X + (float)width) / 16f + (float)tileRangeX + (float)sItem.tileBoost - 1f >= (float)tileTargetX && position.Y / 16f - (float)tileRangeY - (float)sItem.tileBoost <= (float)tileTargetY && (position.Y + (float)height) / 16f + (float)tileRangeY + (float)sItem.tileBoost - 2f >= (float)tileTargetY)
        {
            int num = Main.mouseX + (int)Main.screenPosition.X;
            int num2 = Main.mouseY + (int)Main.screenPosition.Y;
            int i2 = num / 16;
            int i = num2 / 16;
            if (!WorldGen.SolidTile(i2, i))
            {
                ApplyItemTime(sItem);
                NPC.ReleaseNPC(num, num2, sItem.makeNPC, sItem.placeStyle, whoAmI);
            }
        }
    }
References Terraria.Player.ApplyItemTime(), Terraria.Entity.height, Terraria.Entity.position, Terraria.NPC.ReleaseNPC(), Terraria.Main.screenPosition, Terraria.WorldGen.SolidTile(), Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode().