TModLoader: Terraria.Player.WingFrame
WingFrame()
void Terraria.Player.WingFrame (bool wingFlap, bool isCustomWings = false) inline
Definition at line 27316 of file Player.cs.
    {
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07de: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0803: Unknown result type (might be due to invalid IL or missing references)
        //IL_0828: Unknown result type (might be due to invalid IL or missing references)
        //IL_082d: Unknown result type (might be due to invalid IL or missing references)
        //IL_082f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0834: Unknown result type (might be due to invalid IL or missing references)
        //IL_083e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0843: Unknown result type (might be due to invalid IL or missing references)
        //IL_084d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0852: Unknown result type (might be due to invalid IL or missing references)
        //IL_1003: Unknown result type (might be due to invalid IL or missing references)
        //IL_1008: Unknown result type (might be due to invalid IL or missing references)
        //IL_1021: Unknown result type (might be due to invalid IL or missing references)
        //IL_1026: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c06: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c38: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c41: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c48: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c82: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c92: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0903: Unknown result type (might be due to invalid IL or missing references)
        //IL_0908: Unknown result type (might be due to invalid IL or missing references)
        //IL_090d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0915: Unknown result type (might be due to invalid IL or missing references)
        //IL_092d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0952: Unknown result type (might be due to invalid IL or missing references)
        //IL_0957: Unknown result type (might be due to invalid IL or missing references)
        //IL_0959: Unknown result type (might be due to invalid IL or missing references)
        //IL_095e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0967: Unknown result type (might be due to invalid IL or missing references)
        //IL_096d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0972: Unknown result type (might be due to invalid IL or missing references)
        //IL_098a: Unknown result type (might be due to invalid IL or missing references)
        //IL_098f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0994: Unknown result type (might be due to invalid IL or missing references)
        //IL_099e: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_09bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_13bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_13c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f09: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f22: Unknown result type (might be due to invalid IL or missing references)
        //IL_13e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_13e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_13f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_13fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1403: Unknown result type (might be due to invalid IL or missing references)
        //IL_105e: Unknown result type (might be due to invalid IL or missing references)
        //IL_108c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f79: Unknown result type (might be due to invalid IL or missing references)
        //IL_1423: Unknown result type (might be due to invalid IL or missing references)
        //IL_1428: Unknown result type (might be due to invalid IL or missing references)
        //IL_142a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1439: Unknown result type (might be due to invalid IL or missing references)
        //IL_1450: Unknown result type (might be due to invalid IL or missing references)
        //IL_1456: Unknown result type (might be due to invalid IL or missing references)
        //IL_1458: Unknown result type (might be due to invalid IL or missing references)
        //IL_145d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1462: Unknown result type (might be due to invalid IL or missing references)
        //IL_1465: Unknown result type (might be due to invalid IL or missing references)
        //IL_146a: Unknown result type (might be due to invalid IL or missing references)
        //IL_146c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1471: Unknown result type (might be due to invalid IL or missing references)
        //IL_1473: Unknown result type (might be due to invalid IL or missing references)
        //IL_147a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1483: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_1505: Unknown result type (might be due to invalid IL or missing references)
        //IL_1507: Unknown result type (might be due to invalid IL or missing references)
        //IL_150c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1511: Unknown result type (might be due to invalid IL or missing references)
        //IL_1514: Unknown result type (might be due to invalid IL or missing references)
        //IL_1519: Unknown result type (might be due to invalid IL or missing references)
        //IL_151b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1520: Unknown result type (might be due to invalid IL or missing references)
        //IL_1522: Unknown result type (might be due to invalid IL or missing references)
        //IL_1529: Unknown result type (might be due to invalid IL or missing references)
        //IL_1532: Unknown result type (might be due to invalid IL or missing references)
        //IL_1581: Unknown result type (might be due to invalid IL or missing references)
        //IL_1586: Unknown result type (might be due to invalid IL or missing references)
        //IL_1588: Unknown result type (might be due to invalid IL or missing references)
        //IL_1597: Unknown result type (might be due to invalid IL or missing references)
        //IL_15ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_15b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_15b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_15bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_15ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_15cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_15e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1408: Unknown result type (might be due to invalid IL or missing references)
        //IL_1412: Unknown result type (might be due to invalid IL or missing references)
        //IL_1417: Unknown result type (might be due to invalid IL or missing references)
        //IL_1114: Unknown result type (might be due to invalid IL or missing references)
        //IL_1119: Unknown result type (might be due to invalid IL or missing references)
        //IL_11be: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1760: Unknown result type (might be due to invalid IL or missing references)
        //IL_1778: Unknown result type (might be due to invalid IL or missing references)
        //IL_177e: Unknown result type (might be due to invalid IL or missing references)
        //IL_17b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_17bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_17c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1288: Unknown result type (might be due to invalid IL or missing references)
        //IL_128d: Unknown result type (might be due to invalid IL or missing references)
        bool flag = wingsLogic != wings;
        if (wings == 4)
        {
            if (wingFlap || jump > 0)
            {
                rocketDelay2--;
                if (rocketDelay2 <= 0)
                {
                    SoundEngine.PlaySound(in SoundID.Item13, position);
                    rocketDelay2 = 60;
                }
                int num = 2;
                if (TryingToHoverUp)
                {
                    num = 4;
                }
                for (int i = 0; i < num; i++)
                {
                    int type = 6;
                    if (head == 41)
                    {
                        _ = body;
                    }
                    float scale = 1.75f;
                    int alpha = 100;
                    float x = position.X + (float)(width / 2) + 16f;
                    if (direction > 0)
                    {
                        x = position.X + (float)(width / 2) - 26f;
                    }
                    float num12 = position.Y + (float)height - 18f;
                    if (i == 1 || i == 3)
                    {
                        x = position.X + (float)(width / 2) + 8f;
                        if (direction > 0)
{
                            x = position.X + (float)(width / 2) - 20f;
                        }
                        num12 += 6f;
                    }
                    if (i > 1)
                    {
                        num12 += velocity.Y;
                    }
                    int num23 = Dust.NewDust(new Vector2(x, num12), 8, 8, type, 0f, 0f, alpha, default(Color), scale);
                    Main.dust[num23].velocity.X *= 0.1f;
                    Main.dust[num23].velocity.Y = Main.dust[num23].velocity.Y * 1f + 2f * gravDir - velocity.Y * 0.3f;
                    Main.dust[num23].noGravity = true;
                    Main.dust[num23].noLightEmittence = flag;
                    Main.dust[num23].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                    if (num == 4)
                    {
                        Main.dust[num23].velocity.Y += 6f;
                    }
                }
                wingFrameCounter++;
                if (wingFrameCounter > 4)
                {
                    wingFrame++;
                    wingFrameCounter = 0;
                    if (wingFrame >= 3)
                    {
                        wingFrame = 0;
                    }
                }
            }
            else if (!controlJump || velocity.Y == 0f)
            {
                wingFrame = 3;
            }
            return;
        }
        if (wings == 28 && ShouldDrawWingsThatAreAlwaysAnimated())
        {
            if (!flag && velocity.Y != 0f)
            {
                Lighting.AddLight(base.Bottom, 0.3f, 0.1f, 0.4f);
            }
            return;
        }
        if (wings == 22)
        {
            if (!controlJump)
            {
                wingFrame = 0;
                wingFrameCounter = 0;
            }
            else if (wingTime > 0f)
            {
                if (TryingToHoverDown)
                {
                    if (velocity.X != 0f)
                    {
                        wingFrameCounter++;
                        int num26 = 2;
                        if (wingFrameCounter < num26)
{
                            wingFrame = 1;
                            return;
                        }
                        if (wingFrameCounter < num26 * 2)
{
                            wingFrame = 2;
                            return;
                        }
                        if (wingFrameCounter < num26 * 3)
{
                            wingFrame = 3;
                            return;
                        }
                        if (wingFrameCounter < num26 * 4 - 1)
{
                            wingFrame = 2;
                            return;
                        }
                        wingFrame = 2;
                        wingFrameCounter = 0;
                    }
                    else
                    {
                        wingFrameCounter++;
                        int num27 = 6;
                        if (wingFrameCounter < num27)
{
                            wingFrame = 4;
                            return;
                        }
                        if (wingFrameCounter < num27 * 2)
{
                            wingFrame = 5;
                            return;
                        }
                        if (wingFrameCounter < num27 * 3 - 1)
{
                            wingFrame = 4;
                            return;
                        }
                        wingFrame = 4;
                        wingFrameCounter = 0;
                    }
                }
                else
                {
                    wingFrameCounter++;
                    int num28 = 2;
                    if (wingFrameCounter < num28)
                    {
                        wingFrame = 4;
                        return;
                    }
                    if (wingFrameCounter < num28 * 2)
                    {
                        wingFrame = 5;
                        return;
                    }
                    if (wingFrameCounter < num28 * 3)
                    {
                        wingFrame = 6;
                        return;
                    }
                    if (wingFrameCounter < num28 * 4 - 1)
                    {
                        wingFrame = 5;
                        return;
                    }
                    wingFrame = 5;
                    wingFrameCounter = 0;
                }
            }
            else
            {
                wingFrameCounter++;
                int num29 = 6;
                if (wingFrameCounter < num29)
                {
                    wingFrame = 4;
                    return;
                }
                if (wingFrameCounter < num29 * 2)
                {
                    wingFrame = 5;
                    return;
                }
                if (wingFrameCounter < num29 * 3 - 1)
                {
                    wingFrame = 4;
                    return;
                }
                wingFrame = 4;
                wingFrameCounter = 0;
            }
            return;
        }
        if (wings == 12)
        {
            if (wingFlap || jump > 0)
            {
                wingFrameCounter++;
                int num30 = 5;
                if (wingFrameCounter < num30)
                {
                    wingFrame = 1;
                    return;
                }
                if (wingFrameCounter < num30 * 2)
                {
                    wingFrame = 2;
                    return;
                }
                if (wingFrameCounter < num30 * 3)
                {
                    wingFrame = 3;
                    return;
                }
                if (wingFrameCounter < num30 * 4 - 1)
                {
                    wingFrame = 2;
                    return;
                }
                wingFrame = 2;
                wingFrameCounter = 0;
            }
            else if (velocity.Y != 0f)
            {
                wingFrame = 2;
            }
            else
            {
                wingFrame = 0;
            }
            return;
        }
        if (wings == 24)
        {
            if (wingFlap || jump > 0)
            {
                wingFrameCounter++;
                int num31 = 1;
                if (wingFrameCounter < num31)
                {
                    wingFrame = 1;
                    return;
                }
                if (wingFrameCounter < num31 * 2)
                {
                    wingFrame = 2;
                    return;
                }
                if (wingFrameCounter < num31 * 3)
                {
                    wingFrame = 3;
                    return;
                }
                wingFrame = 2;
                if (wingFrameCounter >= num31 * 4 - 1)
                {
                    wingFrameCounter = 0;
                }
            }
            else if (velocity.Y != 0f)
            {
                if (controlJump)
                {
                    wingFrameCounter++;
                    int num2 = 3;
                    if (wingFrameCounter < num2)
                    {
                        wingFrame = 1;
                        return;
                    }
                    if (wingFrameCounter < num2 * 2)
                    {
                        wingFrame = 2;
                        return;
                    }
                    if (wingFrameCounter < num2 * 3)
                    {
                        wingFrame = 3;
                        return;
                    }
                    wingFrame = 2;
                    if (wingFrameCounter >= num2 * 4 - 1)
                    {
                        wingFrameCounter = 0;
                    }
                }
                else if (wingTime == 0f)
                {
                    wingFrame = 0;
                }
                else
                {
                    wingFrame = 1;
                }
            }
            else
            {
                wingFrame = 0;
            }
            return;
        }
        if (wings == 30)
        {
            bool flag2 = false;
            if (wingFlap || jump > 0)
            {
                wingFrameCounter++;
                int num3 = 2;
                if (wingFrameCounter >= num3 * 3)
                {
                    wingFrameCounter = 0;
                }
                wingFrame = 1 + wingFrameCounter / num3;
                flag2 = true;
            }
            else if (velocity.Y != 0f)
            {
                if (controlJump)
                {
                    wingFrameCounter++;
                    int num4 = 2;
                    if (wingFrameCounter >= num4 * 3)
                    {
                        wingFrameCounter = 0;
                    }
                    wingFrame = 1 + wingFrameCounter / num4;
                    flag2 = true;
                }
                else if (wingTime == 0f)
                {
                    wingFrame = 0;
                }
                else
                {
                    wingFrame = 0;
                }
            }
            else
            {
                wingFrame = 0;
            }
            if (!flag2)
            {
                return;
            }
            for (int j = 0; j < 4; j++)
            {
                if (Main.rand.Next(4) == 0)
                {
                    Vector2 vector = (-0.74539816f + (float)Math.PI / 8f * (float)j + 0.03f * (float)j).ToRotationVector2() * new Vector2((float)(-direction * 20), 20f);
                    Dust dust = Main.dust[Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100, Color.White, 0.8f)];
                    dust.noGravity = true;
                    dust.noLightEmittence = flag;
                    dust.position = base.Center + vector;
                    dust.velocity = DirectionTo(dust.position) * 2f;
                    if (Main.rand.Next(10) != 0)
                    {
                        dust.customData = this;
                    }
                    else
                    {
                        dust.fadeIn = 0.5f;
                    }
                    dust.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                }
            }
            for (int k = 0; k < 4; k++)
            {
                if (Main.rand.Next(8) == 0)
                {
                    Vector2 vector2 = (-0.7053982f + (float)Math.PI / 8f * (float)k + 0.03f * (float)k).ToRotationVector2() * new Vector2((float)(direction * 20), 24f) + new Vector2((float)(-direction) * 16f, 0f);
                    Dust dust2 = Main.dust[Dust.NewDust(base.Center, 0, 0, 229, 0f, 0f, 100, Color.White, 0.5f)];
                    dust2.noGravity = true;
                    dust2.noLightEmittence = flag;
                    dust2.position = base.Center + vector2;
                    dust2.velocity = Vector2.Normalize(dust2.position - base.Center - new Vector2((float)(-direction) * 16f, 0f)) * 2f;
                    dust2.position += dust2.velocity * 5f;
                    if (Main.rand.Next(10) != 0)
                    {
                        dust2.customData = this;
                    }
                    else
                    {
                        dust2.fadeIn = 0.5f;
                    }
                    dust2.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                }
            }
            return;
        }
        if (wings == 34 && ShouldDrawWingsThatAreAlwaysAnimated())
        {
            if (wingFlap || jump > 0)
            {
                wingFrameCounter++;
                int num5 = 4;
                if (wingFrameCounter >= num5 * 6)
                {
                    wingFrameCounter = 0;
                }
                wingFrame = wingFrameCounter / num5;
            }
            else if (velocity.Y != 0f)
            {
                if (controlJump)
                {
                    wingFrameCounter++;
                    int num6 = 9;
                    if (wingFrameCounter >= num6 * 6)
                    {
                        wingFrameCounter = 0;
                    }
                    wingFrame = wingFrameCounter / num6;
                }
                else
                {
                    wingFrameCounter++;
                    int num7 = 6;
                    if (wingFrameCounter >= num7 * 6)
                    {
                        wingFrameCounter = 0;
                    }
                    wingFrame = wingFrameCounter / num7;
                }
            }
            else
            {
                wingFrameCounter++;
                int num8 = 4;
                if (wingFrameCounter >= num8 * 6)
                {
                    wingFrameCounter = 0;
                }
                wingFrame = wingFrameCounter / num8;
            }
            return;
        }
        if (wings == 45 && ShouldDrawWingsThatAreAlwaysAnimated())
        {
            if (wingTime > 0f)
            {
                rocketDelay2--;
                if (rocketDelay2 <= 0)
                {
                    SoundEngine.PlaySound(in SoundID.Item24, position);
                    rocketDelay2 = 30;
                }
            }
            if (velocity.Y == 0f)
            {
                wingFrameCounter = 0;
                wingFrame = 0;
            }
            else
            {
                wingFrameCounter++;
                int num9 = 3;
                if (wingTime == 0f)
                {
                    num9 = 5;
                }
                if (wingFrameCounter >= num9 * 6)
                {
                    wingFrameCounter = 0;
                }
                wingFrame = wingFrameCounter / num9;
            }
            if (Main.netMode != 2 && Main.rand.Next(8) == 0)
            {
                Rectangle r = Utils.CenteredRectangle(Main.ReverseGravitySupport(base.Bottom - Main.screenPosition) + Main.screenPosition, new Vector2(40f, 24f));
                Dust dust4 = Dust.NewDustDirect(r.TopLeft(), r.Width, r.Height, 43, 0f, 0f, 0, Color.White * 0.5f, 0.2f);
                dust4.fadeIn = 0.4f;
                dust4.velocity += velocity;
                dust4.velocity *= 0.35f;
                dust4.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
            }
            return;
        }
        if (wings == 44 && ShouldDrawWingsThatAreAlwaysAnimated())
        {
            int num10 = 5;
            if (wingFlap || jump > 0)
            {
                wingFrameCounter++;
                if (wingFrameCounter >= num10 * 6)
                {
                    wingFrameCounter = 0;
                }
                wingFrame = 1 + wingFrameCounter / num10;
            }
            else if (velocity.Y != 0f)
            {
                if (controlJump)
                {
                    wingFrame = 2;
                }
                else if (ShouldFloatInWater && wet)
                {
                    wingFrame = 0;
                }
                else
                {
                    wingFrame = 3;
                }
            }
            else
            {
                wingFrameCounter++;
                if (wingFrameCounter >= num10 * 6)
                {
                    wingFrameCounter = 0;
                }
                wingFrame = 1 + wingFrameCounter / num10;
            }
            return;
        }
        if (wings == 39 && ShouldDrawWingsThatAreAlwaysAnimated())
        {
            if (wingFlap || jump > 0)
            {
                wingFrameCounter++;
                int num11 = 4;
                if (wingFrameCounter >= num11 * 6)
                {
                    wingFrameCounter = 0;
                }
                wingFrame = wingFrameCounter / num11;
            }
            else if (velocity.Y != 0f)
            {
                if (controlJump)
                {
                    wingFrameCounter++;
                    int num13 = 9;
                    if (wingFrameCounter >= num13 * 6)
                    {
                        wingFrameCounter = 0;
                    }
                    wingFrame = wingFrameCounter / num13;
                }
                else
                {
                    wingFrameCounter++;
                    int num14 = 6;
                    if (wingFrameCounter >= num14 * 6)
                    {
                        wingFrameCounter = 0;
                    }
                    wingFrame = wingFrameCounter / num14;
                }
            }
            else
            {
                wingFrameCounter++;
                int num15 = 4;
                if (wingFrameCounter >= num15 * 6)
                {
                    wingFrameCounter = 0;
                }
                wingFrame = wingFrameCounter / num15;
            }
            int num16 = 1;
            if (wingFrame == 3)
            {
                num16 = 5;
            }
            if (velocity.Y == 0f)
            {
                num16 = 0;
            }
            Rectangle r2 = Utils.CenteredRectangle((gravDir == 1f) ? (base.Bottom + new Vector2(0f, -10f)) : (base.Top + new Vector2(0f, 10f)), new Vector2(50f, 20f));
            for (int l = 0; l < num16; l++)
            {
                Dust dust5 = Dust.NewDustDirect(r2.TopLeft(), r2.Width, r2.Height, 31, 0f, 0f, 0, Color.Black);
                dust5.scale = 0.7f;
                dust5.velocity *= 0.4f;
                dust5.velocity.Y += gravDir * 0.5f;
                dust5.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
            }
            return;
        }
        if (wings == 33)
        {
            bool flag3 = false;
            if (wingFlap || jump > 0)
            {
                flag3 = true;
            }
            else if (velocity.Y != 0f && controlJump)
            {
                flag3 = true;
            }
            if (!flag3)
            {
                return;
            }
            Color newColor = Main.hslToRgb(Main.rgbToHsl(eyeColor).X, 1f, 0.5f);
            int num17 = ((direction != 1) ? (-4) : 0);
            int num18 = ((gravDir == 1f) ? height : 0);
            for (int m = 0; m < 2; m++)
            {
                Dust dust3 = Main.dust[Dust.NewDust(position, width, height, 182, velocity.X, velocity.Y, 127, newColor)];
                dust3.noGravity = true;
                dust3.fadeIn = 1f;
                dust3.scale = 1f;
                dust3.noLight = true;
                dust3.noLightEmittence = flag;
                dust3.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                switch (m)
                {
                case 0:
                    dust3.position = new Vector2(position.X + (float)num17, position.Y + (float)num18);
                    dust3.velocity.X = dust3.velocity.X * 1f - 2f - velocity.X * 0.3f;
                    dust3.velocity.Y = dust3.velocity.Y * 1f + 2f * gravDir - velocity.Y * 0.3f;
                    break;
                case 1:
                    dust3.position = new Vector2(position.X + (float)width + (float)num17, position.Y + (float)num18);
                    dust3.velocity.X = dust3.velocity.X * 1f + 2f - velocity.X * 0.3f;
                    dust3.velocity.Y = dust3.velocity.Y * 1f + 2f * gravDir - velocity.Y * 0.3f;
                    break;
                }
                if (dust3.dustIndex != 6000)
                {
                    Dust dust6 = Dust.CloneDust(dust3);
                    dust6.scale *= 0.65f;
                    dust6.fadeIn *= 0.65f;
                    dust6.color = new Color(255, 255, 255, 255);
                    dust3.noLight = true;
                    dust3.noLightEmittence = flag;
                    dust3.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                }
            }
            return;
        }
        if (wings == 38)
        {
            bool flag4 = false;
            if (wingFlap || jump > 0)
            {
                wingFrameCounter++;
                if (wingFrameCounter >= 32)
                {
                    wingFrameCounter = 0;
                }
                wingFrame = 1 + wingFrameCounter / 8;
                if (wingFrame == 4)
                {
                    wingFrame = 2;
                }
                flag4 = true;
            }
            else if (velocity.Y != 0f)
            {
                if (controlJump)
                {
                    wingFrameCounter++;
                    if (wingFrameCounter >= 32)
                    {
                        wingFrameCounter = 0;
                    }
                    wingFrame = 1 + wingFrameCounter / 8;
                    if (wingFrame == 4)
                    {
                        wingFrame = 2;
                    }
                    flag4 = true;
                }
                else
                {
                    wingFrame = 0;
                }
            }
            else
            {
                wingFrame = 0;
            }
            if (!flag4)
            {
                return;
            }
            Vector2 vector3 = default(Vector2);
            ((Vector2)(ref vector3))._002Ector((float)direction, gravDir);
            Vector2 value = velocity * 0.5f;
            int type2 = 267;
            int num19 = miscCounter * direction;
            for (int n = 0; n < 3; n++)
            {
                Vector2 vector4 = Vector2.Zero;
                switch (n)
                {
                case 1:
                    vector4 = velocity * -0.33f;
                    break;
                case 2:
                    vector4 = velocity * -0.66f;
                    break;
                }
                Vector2 vector5 = new Vector2(-39f, 6f) * vector3 + Utils.RotatedBy(new Vector2(2f, 0f), (float)num19 / -15f * ((float)Math.PI * 2f));
                Dust dust7 = Dust.NewDustPerfect(base.Center + vector5 + vector4, type2, value, 0, underShirtColor);
                dust7.noGravity = true;
                dust7.noLight = true;
                dust7.noLightEmittence = flag;
                dust7.scale = 0.47f;
                dust7.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                vector5 = new Vector2(-23f, 2f) * vector3 + Utils.RotatedBy(new Vector2(2f, 0f), (float)num19 / -15f * ((float)Math.PI * 2f));
                Dust dust8 = Dust.NewDustPerfect(base.Center + vector5 + vector4, type2, value, 0, underShirtColor);
                dust8.noGravity = true;
                dust8.noLight = true;
                dust8.noLightEmittence = flag;
                dust8.scale = 0.35f;
                dust8.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                vector5 = new Vector2(-31f, -6f) * vector3 + Utils.RotatedBy(new Vector2(2f, 0f), (float)num19 / -20f * ((float)Math.PI * 2f));
                Dust dust9 = Dust.NewDustPerfect(base.Center + vector5 + vector4, type2, value, 0, underShirtColor);
                dust9.noGravity = true;
                dust9.noLight = true;
                dust9.noLightEmittence = flag;
                dust9.scale = 0.49f;
                dust9.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
            }
            return;
        }
        int num20 = 4;
        int num21 = 4;
        int num22 = 0;
        if (wings == 43)
        {
            num21 = 7;
            num22 = 1;
            num20 = 3;
        }
        if (isCustomWings)
        {
            return;
        }
        if (wings == 32)
        {
            num20 = 3;
        }
        if (wingFlap || jump > 0)
        {
            wingFrameCounter++;
            if (wingFrameCounter > num20)
            {
                wingFrame++;
                wingFrameCounter = 0;
                if (wingFrame >= num21)
                {
                    wingFrame = num22;
                }
            }
        }
        else if (velocity.Y != 0f)
        {
            wingFrame = 1;
            if (wings == 32)
            {
                wingFrame = 3;
            }
            if (wings == 43)
            {
                wingFrame = 2;
                if (ShouldFloatInWater && wet)
                {
                    wingFrame = 0;
                }
            }
            if (wings == 29 && Main.rand.Next(5) == 0)
            {
                int num24 = 4;
                if (direction == 1)
                {
                    num24 = -40;
                }
                int num25 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num24, position.Y + (float)(height / 2) - 15f), 30, 30, 6, 0f, 0f, 100, default(Color), 2.4f);
                Main.dust[num25].noGravity = true;
                Main.dust[num25].noLightEmittence = flag;
                Dust obj = Main.dust[num25];
                obj.velocity *= 0.3f;
                if (Main.rand.Next(10) == 0)
                {
                    Main.dust[num25].fadeIn = 2f;
                }
                Main.dust[num25].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
            }
        }
        else
        {
            wingFrame = 0;
        }
    }
References Terraria.Lighting.AddLight(), Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.body, Terraria.Utils.CenteredRectangle(), Terraria.Dust.CloneDust(), Terraria.Player.controlJump, Terraria.Player.cWings, Terraria.Entity.direction, Terraria.Entity.DirectionTo(), Terraria.Main.dust, Terraria.Player.eyeColor, Terraria.Player.gravDir, Terraria.Player.head, Terraria.Entity.height, Terraria.Main.hslToRgb(), Terraria.ID.SoundID.Item13, Terraria.ID.SoundID.Item24, Terraria.Player.jump, Terraria.Player.miscCounter, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Dust.position, Terraria.Entity.position, Terraria.Main.rand, Terraria.Main.ReverseGravitySupport(), Terraria.Main.rgbToHsl(), Terraria.Player.rocketDelay2, Terraria.Utils.RotatedBy(), Terraria.Main.screenPosition, Terraria.Player.ShouldDrawWingsThatAreAlwaysAnimated(), Terraria.Player.ShouldFloatInWater, Terraria.Player.TryingToHoverDown, Terraria.Player.TryingToHoverUp, Terraria.Player.underShirtColor, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Entity.width, Terraria.Player.wingFrame, Terraria.Player.wingFrameCounter, Terraria.Player.wings, Terraria.Player.wingsLogic, and Terraria.Player.wingTime.
Referenced by Terraria.Player.Update(), and Terraria.GameContent.UI.Elements.UICharacter.UpdateAnim().