TModLoader: Terraria.Player.RemoveAllGrapplingHooks
RemoveAllGrapplingHooks()
void Terraria.Player.RemoveAllGrapplingHooks () inline
    {
        ClearGrapplingBlacklist();
        grappling[0] = -1;
        grapCount = 0;
        for (int i = 0; i < 1000; i++)
        {
            if (Main.projectile[i].active && Main.projectile[i].owner == whoAmI && Main.projectile[i].aiStyle == 7)
            {
                Main.projectile[i].Kill();
            }
        }
    }
References Terraria.Entity.active, Terraria.Projectile.aiStyle, Terraria.Player.ClearGrapplingBlacklist(), Terraria.Player.grapCount, Terraria.Player.grappling, Terraria.Projectile.Kill(), Terraria.Projectile.owner, Terraria.Main.projectile, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.DoPotionOfReturnTeleportationAndSetTheComebackPoint(), Terraria.Player.GrappleMovement(), Terraria.Player.ItemCheck_Inner(), Terraria.Player.LaunchMinecartHook(), Terraria.Player.PetAnimal(), Terraria.GameContent.PlayerSittingHelper.SitDown(), Terraria.GameContent.PlayerSleepingHelper.StartSleeping(), Terraria.Player.Teleport(), and Terraria.Player.UpdateBuffs().