TModLoader: Terraria.Player.UpdateTorchLuck_ConsumeCountersAndCalculate
UpdateTorchLuck_ConsumeCountersAndCalculate()
void Terraria.Player.UpdateTorchLuck_ConsumeCountersAndCalculate () inline private
    {
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        luckyTorchCounter = 0;
        torchLuck = 0f;
        _nextTorchLuckCheckCenter = base.Center;
        if (inventory[selectedItem].createTile == 4 && inventory[selectedItem].placeStyle < TorchID.Count)
        {
            nearbyTorch[inventory[selectedItem].placeStyle] = true;
        }
        ModTile modTile = TileLoader.GetTile(inventory[selectedItem].createTile);
        if (modTile != null && TileID.Sets.Torch[modTile.Type])
        {
            NearbyModTorch.Add(modTile.Type);
        }
        float num = 0f;
        float num2 = 0f;
        if (!ZoneDungeon && !ZoneLihzhardTemple)
        {
            if (nearbyTorch[9])
            {
                if (ZoneSnow)
                {
                    num2 += 1f;
                }
                else
                {
                    num += 1f;
                }
            }
            if (nearbyTorch[16])
            {
                if (ZoneDesert)
                {
                    num2 += 1f;
                }
                else
                {
                    num += 1f;
                }
            }
            if (nearbyTorch[17])
            {
                if (WorldGen.oceanDepths((int)base.Center.X / 16, (int)base.Center.Y / 16))
                {
                    num2 += 1f;
                }
                else if (dryCoralTorch)
                {
                    num += 1f;
                }
            }
            if (nearbyTorch[21])
            {
                if (ZoneJungle)
                {
                    num2 += 1f;
                }
                else
                {
                    num += 1f;
                }
            }
            if (nearbyTorch[22])
            {
                if (ZoneGlowshroom)
                {
                    num2 += 1f;
                }
                else
                {
                    num += 1f;
                }
            }
            if (nearbyTorch[18])
            {
                if (ZoneCorrupt)
                {
                    num2 += 1f;
                }
                else
                {
                    num += 1f;
                }
            }
            if (nearbyTorch[8] && ZoneCorrupt)
            {
                num2 += 1f;
            }
            if (nearbyTorch[19])
            {
                if (ZoneCrimson)
                {
                    num2 += 1f;
                }
                else
                {
                    num += 1f;
                }
            }
            if (nearbyTorch[11] && ZoneCrimson)
            {
                num2 += 1f;
            }
            if (nearbyTorch[20])
            {
                if (ZoneHallow)
                {
                    num2 += 1f;
                }
                else
                {
                    num += 1f;
                }
            }
            if (nearbyTorch[13] && !ZoneSnow && !ZoneDesert && !ZoneCorrupt && !ZoneCrimson && !ZoneHallow && !ZoneJungle)
            {
                num2 += 0.5f;
            }
            if (nearbyTorch[0])
            {
                if (ZoneSnow)
                {
                    num += 2f;
                }
                else if (ZoneDesert || ZoneCorrupt || ZoneCrimson || ZoneHallow)
                {
                    num += 0.5f;
                }
            }
        }
        TileLoader.ModifyTorchLuck(this, ref num2, ref num);
        if (num2 >= 1f)
        {
            torchLuck += 1f;
        }
        else if (num2 > 0f)
        {
            torchLuck += 0.5f;
        }
        if (num >= 2f)
        {
            torchLuck += -1.5f;
        }
        else if (num >= 1f)
        {
            torchLuck += -1f;
        }
        else if (num > 0f)
        {
            torchLuck += -0.5f;
        }
        dryCoralTorch = false;
        for (int i = 0; i < TorchID.Count; i++)
        {
            nearbyTorch[i] = false;
        }
        NearbyModTorch.Clear();
        if (torchLuck < 0f)
        {
            torchLuck = 0f;
        }
        if (torchGodCooldown <= 0 && !unlockedBiomeTorches && nearbyTorches > 100 && !happyFunTorchTime && (double)position.Y > Main.worldSurface * 16.0)
        {
            bool flag = false;
            for (int j = 0; j < inventory.Length; j++)
            {
                if (inventory[j].type == 5043)
                {
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                happyFunTorchTime = true;
                numberOfTorchAttacksMade = 0;
            }
        }
        nearbyTorches = 0;
    }
References Terraria.Player._nextTorchLuckCheckCenter, Terraria.ID.TorchID.Count, Terraria.Player.dryCoralTorch, Terraria.ModLoader.TileLoader.GetTile(), Terraria.Player.happyFunTorchTime, Terraria.Player.inventory, Terraria.Player.luckyTorchCounter, Terraria.ModLoader.TileLoader.ModifyTorchLuck(), Terraria.Player.NearbyModTorch, Terraria.Player.nearbyTorch, Terraria.Player.nearbyTorches, Terraria.Player.numberOfTorchAttacksMade, Terraria.WorldGen.oceanDepths(), Terraria.Item.placeStyle, Terraria.Entity.position, Terraria.Player.selectedItem, Terraria.ID.TileID.Sets.Torch, Terraria.Player.torchLuck, Terraria.Main.worldSurface, Terraria.Player.ZoneCorrupt, Terraria.Player.ZoneCrimson, Terraria.Player.ZoneDesert, Terraria.Player.ZoneDungeon, Terraria.Player.ZoneGlowshroom, Terraria.Player.ZoneHallow, Terraria.Player.ZoneJungle, Terraria.Player.ZoneLihzhardTemple, and Terraria.Player.ZoneSnow.
Referenced by Terraria.Player.TryRecalculatingTorchLuck().