TModLoader: Terraria.Player.GetDyeTraderReward
GetDyeTraderReward()
void Terraria.Player.GetDyeTraderReward (NPC dyeTrader) inline
Definition at line 57634 of file Player.cs.
    {
        //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        int num = -1;
        EntitySource_Gift source = new EntitySource_Gift(dyeTrader);
        List<int> list = new List<int>
        {
            3560, 3028, 3041, 3040, 3025, 3190, 3027, 3026, 3554, 3553,
            3555, 2872, 3534, 2871
        };
        if (Main.hardMode)
        {
            list.Add(3039);
            list.Add(3038);
            list.Add(3598);
            list.Add(3597);
            list.Add(3600);
            list.Add(3042);
            list.Add(3533);
            list.Add(3561);
            if (NPC.downedMechBossAny)
            {
                list.Add(2883);
                list.Add(2869);
                list.Add(2873);
                list.Add(2870);
            }
            if (NPC.downedPlantBoss)
            {
                list.Add(2878);
                list.Add(2879);
                list.Add(2884);
                list.Add(2885);
            }
            if (NPC.downedMartians)
            {
                list.Add(2864);
                list.Add(3556);
            }
            if (NPC.downedMoonlord)
            {
                list.Add(3024);
            }
        }
        PlayerLoader.GetDyeTraderReward(this, list);
        num = list[Main.rand.Next(list.Count)];
        Item item = new Item();
        item.SetDefaults(num);
        item.stack = 6;
        item.position = base.Center;
        Item item2 = GetItem(whoAmI, item, GetItemSettings.NPCEntityToPlayerInventorySettings);
        if (item2.stack > 0)
        {
            int number = Item.NewItem(source, (int)position.X, (int)position.Y, width, height, item2.type, item2.stack, noBroadcast: false, 0, noGrabDelay: true);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, number, 1f);
            }
        }
    }
References Terraria.NPC.downedMartians, Terraria.NPC.downedMechBossAny, Terraria.NPC.downedMoonlord, Terraria.NPC.downedPlantBoss, Terraria.ModLoader.PlayerLoader.GetDyeTraderReward(), Terraria.Player.GetItem(), Terraria.Main.hardMode, Terraria.Entity.height, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.GetItemSettings.NPCEntityToPlayerInventorySettings, Terraria.Entity.position, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Entity.whoAmI, and Terraria.Entity.width.