TModLoader: Terraria.Player.ItemCheck_CheckCanUse
ItemCheck_CheckCanUse()
bool Terraria.Player.ItemCheck_CheckCanUse (Item sItem) inline private
Definition at line 52757 of file Player.cs.
    {
        if (sItem.IsAir || !CombinedHooks.CanUseItem(this, sItem))
        {
            return false;
        }
        int num = whoAmI;
        bool flag = true;
        int num2 = (int)((float)Main.mouseX + Main.screenPosition.X) / 16;
        int num3 = (int)((float)Main.mouseY + Main.screenPosition.Y) / 16;
        if (gravDir == -1f)
        {
            num3 = (int)(Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY) / 16;
        }
        if (sItem.type == 3335 && (extraAccessory || !Main.expertMode))
        {
            flag = false;
        }
        if (pulley && sItem.fishingPole > 0)
        {
            flag = false;
        }
        if (pulley && ItemID.Sets.IsAKite[sItem.type])
        {
            flag = false;
        }
        if (sItem.type == 3611 && (WiresUI.Settings.ToolMode & (WiresUI.Settings.MultiToolMode.Red | WiresUI.Settings.MultiToolMode.Green | WiresUI.Settings.MultiToolMode.Blue | WiresUI.Settings.MultiToolMode.Yellow | WiresUI.Settings.MultiToolMode.Actuator)) == 0)
        {
            flag = false;
        }
        if (sItem.type == 5451 && ownedProjectileCounts[1020] > 0)
        {
            flag = false;
        }
        if ((sItem.type == 3611 || sItem.type == 3625) && wireOperationsCooldown > 0)
        {
            flag = false;
        }
        if (!CheckDD2CrystalPaymentLock(sItem))
        {
            flag = false;
        }
        if (sItem.shoot > -1 && ProjectileID.Sets.IsADD2Turret[sItem.shoot] && !downedDD2EventAnyDifficulty && !DD2Event.Ongoing)
        {
            flag = false;
        }
        int pushYUp;
        if (sItem.shoot > -1 && ProjectileID.Sets.IsADD2Turret[sItem.shoot] && DD2Event.Ongoing && num == Main.myPlayer)
        {
            FindSentryRestingSpot(sItem.shoot, out var worldX, out var worldY, out pushYUp);
            if (WouldSpotOverlapWithSentry(worldX, worldY, sItem.shoot == 688 || sItem.shoot == 689 || sItem.shoot == 690))
            {
                flag = false;
            }
        }
        if (sItem.shoot > -1 && ProjectileID.Sets.IsADD2Turret[sItem.shoot] && num == Main.myPlayer)
        {
            FindSentryRestingSpot(sItem.shoot, out var worldX2, out var worldY2, out pushYUp);
            worldX2 /= 16;
            worldY2 /= 16;
            worldY2--;
            if (sItem.shoot == 688 || sItem.shoot == 689 || sItem.shoot == 690)
            {
                if (Collision.SolidTiles(worldX2, worldX2, worldY2 - 2, worldY2))
                {
                    flag = false;
                }
            }
            else if (WorldGen.SolidTile(worldX2, worldY2))
            {
                flag = false;
            }
        }
        if (wet && (sItem.shoot == 85 || sItem.shoot == 15 || sItem.shoot == 34))
        {
            flag = false;
        }
        if (sItem.makeNPC > 0 && !NPC.CanReleaseNPCs(whoAmI))
        {
            flag = false;
        }
        if (whoAmI == Main.myPlayer && sItem.type == 603 && !Main.runningCollectorsEdition)
        {
            flag = false;
        }
        if (sItem.type == 1071 || sItem.type == 1072)
        {
            bool flag2 = false;
            for (int i = 0; i < 58; i++)
            {
                if (inventory[i].PaintOrCoating)
                {
                    flag2 = true;
                    break;
                }
            }
            if (!flag2)
            {
                flag = false;
            }
        }
        if (noItems)
        {
            flag = false;
        }
        if (sItem.tileWand > 0)
        {
            int tileWand = sItem.tileWand;
            flag = false;
            for (int j = 0; j < 58; j++)
            {
                if (tileWand == inventory[j].type && inventory[j].stack > 0)
                {
                    flag = true;
                    break;
                }
            }
        }
        if (sItem.shoot == 6 || sItem.shoot == 19 || sItem.shoot == 33 || sItem.shoot == 52 || sItem.shoot == 113 || sItem.shoot == 320 || sItem.shoot == 333 || sItem.shoot == 383 || sItem.shoot == 491 || sItem.shoot == 867 || sItem.shoot == 902 || sItem.shoot == 866)
        {
            for (int k = 0; k < 1000; k++)
            {
                if (Main.projectile[k].active && Main.projectile[k].owner == Main.myPlayer && Main.projectile[k].type == sItem.shoot)
                {
                    flag = false;
                }
            }
        }
        if (sItem.shoot == 106)
        {
            int num4 = 0;
            for (int l = 0; l < 1000; l++)
            {
                if (Main.projectile[l].active && Main.projectile[l].owner == Main.myPlayer && Main.projectile[l].type == sItem.shoot)
                {
                    num4++;
                }
            }
            if (num4 >= 6)
            {
                flag = false;
            }
        }
        if (sItem.shoot == 272)
        {
            int num5 = 0;
            for (int m = 0; m < 1000; m++)
            {
                if (Main.projectile[m].active && Main.projectile[m].owner == Main.myPlayer && Main.projectile[m].type == sItem.shoot)
                {
                    num5++;
                }
            }
            if (num5 >= 10)
            {
                flag = false;
            }
        }
        if (sItem.shoot == 1000)
        {
            int num6 = 0;
            for (int n = 0; n < 1000; n++)
            {
                if (Main.projectile[n].active && Main.projectile[n].owner == Main.myPlayer && Main.projectile[n].type == sItem.shoot)
                {
                    num6++;
                }
            }
            if (num6 >= 3)
            {
                flag = false;
            }
        }
        if (sItem.shoot == 13 || sItem.shoot == 32 || (sItem.shoot >= 230 && sItem.shoot <= 235) || sItem.shoot == 315 || sItem.shoot == 331 || sItem.shoot == 372)
        {
            for (int num7 = 0; num7 < 1000; num7++)
            {
                if (Main.projectile[num7].active && Main.projectile[num7].owner == Main.myPlayer && Main.projectile[num7].type == sItem.shoot && Main.projectile[num7].ai[0] != 2f)
                {
                    flag = false;
                }
            }
        }
        if (sItem.shoot == 332)
        {
            int num8 = 0;
            for (int num9 = 0; num9 < 1000; num9++)
            {
                if (Main.projectile[num9].active && Main.projectile[num9].owner == Main.myPlayer && Main.projectile[num9].type == sItem.shoot && Main.projectile[num9].ai[0] != 2f)
                {
                    num8++;
                }
            }
            if (num8 >= 3)
            {
                flag = false;
            }
        }
        if (sItem.potion && potionDelay > 0)
        {
            flag = false;
        }
        if (sItem.mana > 0 && silence)
        {
            flag = false;
        }
        if (sItem.mana > 0 && flag)
        {
            flag = ItemCheck_PayMana(sItem, flag);
        }
        if (sItem.type == 43 && Main.IsItDay())
        {
            flag = false;
        }
        if (sItem.type == 544 && Main.IsItDay())
        {
            flag = false;
        }
        if (sItem.type == 556 && Main.IsItDay())
        {
            flag = false;
        }
        if (sItem.type == 557 && Main.IsItDay())
        {
            flag = false;
        }
        if (sItem.type == 70 && !ZoneCorrupt)
        {
            flag = false;
        }
        if (sItem.type == 1133 && !ZoneJungle)
        {
            flag = false;
        }
        if (sItem.type == 5120 && !ZoneSnow)
        {
            flag = false;
        }
        if (sItem.type == 1844 && (Main.dayTime || Main.pumpkinMoon || Main.snowMoon || DD2Event.Ongoing))
        {
            flag = false;
        }
        if (sItem.type == 1958 && (Main.dayTime || Main.pumpkinMoon || Main.snowMoon || DD2Event.Ongoing))
        {
            flag = false;
        }
        if (sItem.type == 2767 && (!Main.dayTime || Main.eclipse || !Main.hardMode))
        {
            flag = false;
        }
        if (sItem.type == 4271 && (Main.dayTime || Main.bloodMoon))
        {
            flag = false;
        }
        if (sItem.type == 3601 && (!NPC.downedGolemBoss || !Main.hardMode || NPC.AnyDanger() || NPC.AnyoneNearCultists()))
        {
            flag = false;
        }
        if (!SummonItemCheck(sItem))
        {
            flag = false;
        }
        if (sItem.shoot == 17 && flag && num == Main.myPlayer && !ItemCheck_IsValidDirtRodTarget(Main.tile[num2, num3]))
        {
            flag = false;
        }
        if (sItem.chlorophyteExtractinatorConsumable && flag && num == Main.myPlayer)
        {
            Tile tile = Main.tile[num2, num3];
            if (!tile.active() || (tile.type != 642 && tile.type != 219))
            {
                flag = false;
            }
        }
        if (sItem.fishingPole > 0)
        {
            flag = ItemCheck_CheckFishingBobbers(flag);
        }
        if (ItemID.Sets.HasAProjectileThatHasAUsabilityCheck[sItem.type])
        {
            flag = ItemCheck_CheckUsabilityOfProjectiles(flag);
        }
        if (sItem.shoot == 17 && flag && num == Main.myPlayer)
        {
            if (ItemCheck_IsValidDirtRodTarget(Main.tile[num2, num3]))
            {
                WorldGen.KillTile(num2, num3, fail: false, effectOnly: false, noItem: true);
                if (!Main.tile[num2, num3].active())
                {
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(17, -1, -1, null, 4, num2, num3);
                    }
                }
                else
                {
                    flag = false;
                }
            }
            else
            {
                flag = false;
            }
        }
        if (flag)
        {
            flag = HasAmmo(sItem, flag);
        }
        return flag;
    }
References Terraria.Entity.active, Terraria.Tile.active(), Terraria.Projectile.ai, Terraria.NPC.AnyDanger(), Terraria.NPC.AnyoneNearCultists(), Terraria.Main.bloodMoon, Terraria.NPC.CanReleaseNPCs(), Terraria.ModLoader.CombinedHooks.CanUseItem(), Terraria.Player.CheckDD2CrystalPaymentLock(), Terraria.Main.dayTime, Terraria.Player.downedDD2EventAnyDifficulty, Terraria.NPC.downedGolemBoss, Terraria.Main.eclipse, Terraria.Main.expertMode, Terraria.Player.extraAccessory, Terraria.Player.FindSentryRestingSpot(), Terraria.Player.gravDir, Terraria.Main.hardMode, Terraria.Player.HasAmmo(), Terraria.ID.ItemID.Sets.HasAProjectileThatHasAUsabilityCheck, Terraria.Player.inventory, Terraria.ID.ProjectileID.Sets.IsADD2Turret, Terraria.ID.ItemID.Sets.IsAKite, Terraria.Main.IsItDay(), Terraria.Player.ItemCheck_CheckFishingBobbers(), Terraria.Player.ItemCheck_CheckUsabilityOfProjectiles(), Terraria.Player.ItemCheck_IsValidDirtRodTarget(), Terraria.Player.ItemCheck_PayMana(), Terraria.WorldGen.KillTile(), Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Player.noItems, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Player.ownedProjectileCounts, Terraria.Projectile.owner, Terraria.Player.potionDelay, Terraria.Main.projectile, Terraria.Player.pulley, Terraria.Main.pumpkinMoon, Terraria.Main.runningCollectorsEdition, Terraria.Main.screenPosition, Terraria.NetMessage.SendData(), Terraria.Player.silence, Terraria.Main.snowMoon, Terraria.WorldGen.SolidTile(), Terraria.Collision.SolidTiles(), Terraria.Player.SummonItemCheck(), Terraria.Main.tile, Terraria.GameContent.UI.WiresUI.Settings.ToolMode, Terraria.Projectile.type, Terraria.Tile.type, Terraria.Entity.wet, Terraria.Entity.whoAmI, Terraria.Player.wireOperationsCooldown, Terraria.Player.WouldSpotOverlapWithSentry(), Terraria.Player.ZoneCorrupt, Terraria.Player.ZoneJungle, and Terraria.Player.ZoneSnow.
Referenced by Terraria.Player.ItemCheck_Inner(), Terraria.Player.QuickBuff(), Terraria.Player.QuickGrapple(), Terraria.Player.QuickHeal(), Terraria.Player.QuickMana(), and Terraria.Player.QuickMount().