TModLoader: Terraria.Player.WingAirVisuals
WingAirVisuals()
void Terraria.Player.WingAirVisuals () inline private
Definition at line 28279 of file Player.cs.
    {
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0160: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01de: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_0290: Unknown result type (might be due to invalid IL or missing references)
        //IL_0296: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_035a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0376: Unknown result type (might be due to invalid IL or missing references)
        //IL_037c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0392: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04df: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0505: Unknown result type (might be due to invalid IL or missing references)
        //IL_0537: Unknown result type (might be due to invalid IL or missing references)
        //IL_0541: Unknown result type (might be due to invalid IL or missing references)
        //IL_0546: Unknown result type (might be due to invalid IL or missing references)
        //IL_0554: Unknown result type (might be due to invalid IL or missing references)
        //IL_055a: Unknown result type (might be due to invalid IL or missing references)
        //IL_055f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0564: Unknown result type (might be due to invalid IL or missing references)
        //IL_0422: Unknown result type (might be due to invalid IL or missing references)
        //IL_0442: Unknown result type (might be due to invalid IL or missing references)
        //IL_0448: Unknown result type (might be due to invalid IL or missing references)
        //IL_046c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0476: Unknown result type (might be due to invalid IL or missing references)
        //IL_047b: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_070c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0712: Unknown result type (might be due to invalid IL or missing references)
        //IL_0732: Unknown result type (might be due to invalid IL or missing references)
        //IL_073c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0741: Unknown result type (might be due to invalid IL or missing references)
        //IL_0749: Unknown result type (might be due to invalid IL or missing references)
        //IL_074f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0759: Unknown result type (might be due to invalid IL or missing references)
        //IL_075e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0763: Unknown result type (might be due to invalid IL or missing references)
        //IL_0796: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_095d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0975: Unknown result type (might be due to invalid IL or missing references)
        //IL_097b: Unknown result type (might be due to invalid IL or missing references)
        //IL_099f: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_05eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_060d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0613: Unknown result type (might be due to invalid IL or missing references)
        //IL_0645: Unknown result type (might be due to invalid IL or missing references)
        //IL_064f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0654: Unknown result type (might be due to invalid IL or missing references)
        //IL_0662: Unknown result type (might be due to invalid IL or missing references)
        //IL_0668: Unknown result type (might be due to invalid IL or missing references)
        //IL_066d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0672: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a63: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0abb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b36: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b86: Unknown result type (might be due to invalid IL or missing references)
        //IL_081a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0852: Unknown result type (might be due to invalid IL or missing references)
        //IL_0858: Unknown result type (might be due to invalid IL or missing references)
        //IL_0878: Unknown result type (might be due to invalid IL or missing references)
        //IL_0882: Unknown result type (might be due to invalid IL or missing references)
        //IL_0887: Unknown result type (might be due to invalid IL or missing references)
        //IL_088f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0895: Unknown result type (might be due to invalid IL or missing references)
        //IL_089f: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c41: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d53: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d62: Unknown result type (might be due to invalid IL or missing references)
        bool noLightEmittence = wingsLogic != wings;
        if (wings == 10 && Main.rand.Next(2) == 0)
        {
            int num = 4;
            if (direction == 1)
            {
                num = -40;
            }
            int num12 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num, position.Y + (float)(height / 2) - 15f), 30, 30, 76, 0f, 0f, 50, default(Color), 0.6f);
            Main.dust[num12].fadeIn = 1.1f;
            Main.dust[num12].noGravity = true;
            Main.dust[num12].noLight = true;
            Dust obj = Main.dust[num12];
            obj.velocity *= 0.3f;
            Main.dust[num12].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
        }
        if (wings == 34 && Main.rand.Next(2) == 0)
        {
            int num17 = 4;
            if (direction == 1)
            {
                num17 = -40;
            }
            int num18 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num17, position.Y + (float)(height / 2) - 15f), 30, 30, 261, 0f, 0f, 50, default(Color), 0.6f);
            Main.dust[num18].fadeIn = 1.1f;
            Main.dust[num18].noGravity = true;
            Main.dust[num18].noLight = true;
            Main.dust[num18].noLightEmittence = noLightEmittence;
            Dust obj2 = Main.dust[num18];
            obj2.velocity *= 0.3f;
            Main.dust[num18].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
        }
        _ = wings;
        _ = wings;
        if (wings == 9 && Main.rand.Next(2) == 0)
        {
            int num19 = 4;
            if (direction == 1)
            {
                num19 = -40;
            }
            int num20 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num19, position.Y + (float)(height / 2) - 15f), 30, 30, 6, 0f, 0f, 200, default(Color), 2f);
            Main.dust[num20].noGravity = true;
            Main.dust[num20].noLightEmittence = noLightEmittence;
            Dust obj3 = Main.dust[num20];
            obj3.velocity *= 0.3f;
            Main.dust[num20].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
        }
        if (wings == 6 && Main.rand.Next(4) == 0)
        {
            int num21 = 4;
            if (direction == 1)
            {
                num21 = -40;
            }
            int num22 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num21, position.Y + (float)(height / 2) - 15f), 30, 30, 55, 0f, 0f, 200);
            Dust obj4 = Main.dust[num22];
            obj4.velocity *= 0.3f;
            Main.dust[num22].noLightEmittence = noLightEmittence;
            Main.dust[num22].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
        }
        if (wings == 5 && Main.rand.Next(3) == 0)
        {
            int num23 = 6;
            if (direction == 1)
            {
                num23 = -30;
            }
            int num2 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num23, position.Y), 18, height, 58, 0f, 0f, 255, default(Color), 1.2f);
            Main.dust[num2].noLightEmittence = noLightEmittence;
            Dust obj5 = Main.dust[num2];
            obj5.velocity *= 0.3f;
            Main.dust[num2].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
        }
        if (wings == 26)
        {
            int num3 = 6;
            if (direction == 1)
            {
                num3 = -30;
            }
            int num4 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num3, position.Y), 18, height, 217, 0f, 0f, 100, default(Color), 1.4f);
            Main.dust[num4].noGravity = true;
            Main.dust[num4].noLight = true;
            Dust obj6 = Main.dust[num4];
            obj6.velocity /= 4f;
            Dust obj7 = Main.dust[num4];
            obj7.velocity -= velocity;
            Main.dust[num4].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
            if (Main.rand.Next(2) == 0)
            {
                num3 = -24;
                if (direction == 1)
                {
                    num3 = 12;
                }
                float num5 = position.Y;
                if (gravDir == -1f)
                {
                    num5 += (float)(height / 2);
                }
                num4 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num3, num5), 12, height / 2, 217, 0f, 0f, 100, default(Color), 1.4f);
                Main.dust[num4].noGravity = true;
                Main.dust[num4].noLight = true;
                Dust obj8 = Main.dust[num4];
                obj8.velocity /= 4f;
                Dust obj9 = Main.dust[num4];
                obj9.velocity -= velocity;
                Main.dust[num4].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
            }
        }
        if (wings == 37)
        {
            int num6 = 6;
            if (direction == 1)
            {
                num6 = -30;
            }
            Dust dust = Dust.NewDustDirect(new Vector2(position.X + (float)(width / 2) + (float)num6, position.Y), 24, height, Utils.SelectRandom<int>(Main.rand, 31, 31, 31), 0f, 0f, 100);
            dust.noGravity = true;
            dust.noLight = true;
            Dust dust2 = dust;
            dust2.velocity /= 4f;
            Dust dust3 = dust;
            dust3.velocity -= velocity / 2f;
            dust.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
            if (dust.type == 55)
            {
                dust.noGravity = true;
                Dust dust4 = dust;
                dust4.velocity *= 2f;
                dust.color = Color.Red;
            }
            if (Main.rand.Next(3) == 0)
            {
                num6 = -24;
                if (direction == 1)
                {
                    num6 = 12;
                }
                float num7 = position.Y;
                if (gravDir == -1f)
                {
                    num7 += (float)(height / 2);
                }
                dust = Dust.NewDustDirect(new Vector2(position.X + (float)(width / 2) + (float)num6, num7), 16, height / 2, Utils.SelectRandom<int>(Main.rand, 31, 31, 31), 0f, 0f, 100);
                dust.noGravity = true;
                dust.noLight = true;
                Dust dust5 = dust;
                dust5.velocity /= 4f;
                Dust dust6 = dust;
                dust6.velocity -= velocity / 2f;
                dust.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
                if (dust.type == 55)
                {
                    dust.noGravity = true;
                    Dust dust7 = dust;
                    dust7.velocity *= 2f;
                    dust.color = Color.Red;
                }
            }
        }
        if (wings == 29 && Main.rand.Next(3) == 0)
        {
            int num8 = 4;
            if (direction == 1)
            {
                num8 = -40;
            }
            int num9 = Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num8, position.Y + (float)(height / 2) - 15f), 30, 30, 6, 0f, 0f, 100, default(Color), 2.4f);
            Main.dust[num9].noGravity = true;
            Dust obj10 = Main.dust[num9];
            obj10.velocity *= 0.3f;
            Main.dust[num9].noLightEmittence = noLightEmittence;
            if (Main.rand.Next(10) == 0)
            {
                Main.dust[num9].fadeIn = 2f;
            }
            Main.dust[num9].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
        }
        if (wings != 31)
        {
            return;
        }
        if (Main.rand.Next(6) == 0)
        {
            int num10 = 4;
            if (direction == 1)
            {
                num10 = -40;
            }
            Dust obj11 = Main.dust[Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num10, position.Y + (float)(height / 2) - 15f), 30, 30, 86)];
            obj11.noGravity = true;
            obj11.scale = 1f;
            obj11.fadeIn = 1.2f;
            obj11.velocity *= 0.2f;
            obj11.noLight = true;
            obj11.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
        }
        if (Main.rand.Next(3) == 0)
        {
            int num11 = 4;
            if (direction == 1)
            {
                num11 = -40;
            }
            Dust obj12 = Main.dust[Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num11, position.Y + (float)(height / 2) - 15f), 30, 30, 240)];
            obj12.noGravity = true;
            obj12.scale = 1.2f;
            obj12.velocity *= 0.2f;
            obj12.alpha = 200;
            obj12.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
        }
        if (Main.rand.Next(2) != 0)
        {
            return;
        }
        if (Main.rand.Next(6) == 0)
        {
            int num14 = -24;
            if (direction == 1)
            {
                num14 = 12;
            }
            float num15 = position.Y;
            if (gravDir == -1f)
            {
                num15 += (float)(height / 2);
            }
            Dust obj13 = Main.dust[Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num14, num15), 12, height / 2, 86)];
            obj13.noGravity = true;
            obj13.scale = 1f;
            obj13.fadeIn = 1.2f;
            obj13.velocity *= 0.2f;
            obj13.noLight = true;
            obj13.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
        }
        if (Main.rand.Next(3) == 0)
        {
            int num13 = -24;
            if (direction == 1)
            {
                num13 = 12;
            }
            float num16 = position.Y;
            if (gravDir == -1f)
            {
                num16 += (float)(height / 2);
            }
            Dust obj14 = Main.dust[Dust.NewDust(new Vector2(position.X + (float)(width / 2) + (float)num13, num16), 12, height / 2, 240)];
            obj14.noGravity = true;
            obj14.scale = 1.2f;
            obj14.velocity *= 0.2f;
            obj14.alpha = 200;
            obj14.shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
        }
    }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.cWings, Terraria.Entity.direction, Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Dust.noLightEmittence, Terraria.Entity.position, Terraria.Main.rand, Terraria.Dust.shader, Terraria.Dust.type, Terraria.Entity.velocity, Terraria.Entity.width, Terraria.Player.wings, and Terraria.Player.wingsLogic.
Referenced by Terraria.Player.Update().