TModLoader: Terraria.Player.Hurt
Hurt() [2/4]
double Terraria.Player.Hurt (PlayerDeathReason damageSource, int Damage, int hitDirection, bool pvp, bool quiet, bool Crit, int cooldownCounter, bool dodgeable = true, float armorPenetration = 0f) inline package
    {
        return Hurt(damageSource, Damage, hitDirection, pvp, quiet, cooldownCounter, dodgeable, armorPenetration);
    }
References Terraria.Player.armorPenetration, Terraria.GameContent.Damage, and Terraria.Player.Hurt().
Referenced by Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Player.ApplyTouchDamage(), Terraria.Projectile.BombsHurtPlayers(), Terraria.NPC.CheckCatchNPC(), Terraria.Projectile.Damage(), Terraria.MessageBuffer.GetData(), Terraria.Player.Hurt(), Terraria.Player.Hurt(), Terraria.Player.Hurt(), Terraria.Player.ItemCheck_MeleeHitPVP(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.Player.OnHurt_Part2(), Terraria.Player.TakeDamageFromJellyfish(), Terraria.Player.Update(), Terraria.GameContent.DontStarveDarknessDamageDealer.Update(), Terraria.Player.Update_NPCCollision(), Terraria.Player.UpdateBuffs(), and Terraria.Player.WOFTongue().