TModLoader: Terraria.Player.ApplyLifeAndOrMana
ApplyLifeAndOrMana()
void Terraria.Player.ApplyLifeAndOrMana (Item item) inline private
Definition at line 52702 of file Player.cs.
    {
        int num = GetHealLife(item, quickHeal: true);
        int healMana = GetHealMana(item, quickHeal: true);
        if (item.type == 3001)
        {
            int healLife = item.healLife;
            int num2 = 120;
            num = Main.rand.Next(healLife, num2 + 1);
            if (Main.myPlayer == whoAmI)
            {
                float num3 = Main.rand.NextFloat();
                int num4 = 0;
                if (num3 <= 0.1f)
                {
                    num4 = 240;
                }
                else if (num3 <= 0.3f)
                {
                    num4 = 120;
                }
                else if (num3 <= 0.6f)
                {
                    num4 = 60;
                }
                if (num4 > 0)
                {
                    SetImmuneTimeForAllTypes(num4);
                }
            }
        }
        statLife += num;
        statMana += healMana;
        if (statLife > statLifeMax2)
        {
            statLife = statLifeMax2;
        }
        if (statMana > statManaMax2)
        {
            statMana = statManaMax2;
        }
        if (num > 0 && Main.myPlayer == whoAmI)
        {
            HealEffect(num);
        }
        if (healMana > 0)
        {
            AddBuff(94, manaSickTime);
            if (Main.myPlayer == whoAmI)
            {
                ManaEffect(healMana);
            }
        }
    }
References Terraria.Player.AddBuff(), Terraria.Player.GetHealLife(), Terraria.Player.GetHealMana(), Terraria.Player.HealEffect(), Terraria.Item.healLife, Terraria.Player.ManaEffect(), Terraria.Player.manaSickTime, Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Player.SetImmuneTimeForAllTypes(), Terraria.Player.statLife, Terraria.Player.statLifeMax2, Terraria.Player.statMana, Terraria.Player.statManaMax2, Terraria.Item.type, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ItemCheck_Inner(), Terraria.Player.QuickHeal(), and Terraria.Player.QuickMana().