TModLoader: Terraria.Player.PlaceThing_Tiles_PlaceIt
PlaceThing_Tiles_PlaceIt()
TileObject Terraria.Player.PlaceThing_Tiles_PlaceIt (bool newObjectType, TileObject data, int tileToCreate) inline private
    {
        int num = inventory[selectedItem].placeStyle;
        if (!newObjectType)
        {
            num = PlaceThing_Tiles_PlaceIt_GetLegacyTileStyle(num);
        }
        int[,] typeCaches = PlaceThing_Tiles_GetAutoAccessoryCache();
        bool forced = false;
        bool flag;
        if (newObjectType)
        {
            flag = TileObject.Place(data);
            WorldGen.SquareTileFrame(tileTargetX, tileTargetY);
            if (Main.netMode != 1 || !TileID.Sets.IsAContainer[tileToCreate])
            {
                SoundEngine.PlaySound(0, tileTargetX * 16, tileTargetY * 16);
            }
        }
        else
        {
            if (UsingBiomeTorches && tileToCreate == 4 && num == 0)
            {
                BiomeTorchPlaceStyle(ref tileToCreate, ref num);
            }
            flag = WorldGen.PlaceTile(tileTargetX, tileTargetY, tileToCreate, mute: false, forced, whoAmI, num);
        }
        if (flag)
        {
            ApplyItemTime(inventory[selectedItem], tileSpeed);
            if (newObjectType)
            {
                TileObjectData.CallPostPlacementPlayerHook(tileTargetX, tileTargetY, tileToCreate, num, direction, data.alternate, data);
                if (Main.netMode == 1 && !Main.tileContainer[tileToCreate] && tileToCreate != 423)
                {
                    NetMessage.SendObjectPlacement(-1, tileTargetX, tileTargetY, data.type, data.style, data.alternate, data.random, direction);
                }
            }
            else
            {
                NetMessage.SendData(17, -1, -1, null, 1, tileTargetX, tileTargetY, tileToCreate, num);
                PlaceThing_Tiles_PlaceIt_SpinChairs();
                PlaceThing_Tiles_PlaceIt_SpinBedsAndBaths();
            }
            PlaceThing_Tiles_PlaceIt_AdjustPlants();
            PlaceThing_Tiles_PlaceIt_SpinTraps();
            PlaceThing_Tiles_PlaceIt_TriggerLogicLamp();
            PlaceThing_Tiles_PlaceIt_SpinSmartPlatform();
            PlaceThing_Tiles_PlaceIt_ConsumeFlexibleWandMaterial();
            PlaceThing_Tiles_PlaceIt_UnslopeForSolids();
            PlaceThing_Tiles_PlaceIt_KillGrassForSolids();
            PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(typeCaches, tileToCreate);
            if (PlayerInput.UsingGamepad && ItemID.Sets.SingleUseInGamepad[inventory[selectedItem].type] && Main.myPlayer == whoAmI && !Main.SmartCursorIsUsed)
            {
                Main.blockMouse = true;
            }
            TileLoader.PlaceInWorld(tileTargetX, tileTargetY, inventory[selectedItem]);
        }
        return data;
    }
References Terraria.TileObject.alternate, Terraria.Player.ApplyItemTime(), Terraria.Player.BiomeTorchPlaceStyle(), Terraria.ObjectData.TileObjectData.CallPostPlacementPlayerHook(), Terraria.Entity.direction, Terraria.Player.inventory, Terraria.ID.TileID.Sets.IsAContainer, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.TileObject.Place(), Terraria.ModLoader.TileLoader.PlaceInWorld(), Terraria.Item.placeStyle, Terraria.Player.PlaceThing_Tiles_GetAutoAccessoryCache(), Terraria.Player.PlaceThing_Tiles_PlaceIt_AdjustPlants(), Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(), Terraria.Player.PlaceThing_Tiles_PlaceIt_ConsumeFlexibleWandMaterial(), Terraria.Player.PlaceThing_Tiles_PlaceIt_GetLegacyTileStyle(), Terraria.Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids(), Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinBedsAndBaths(), Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinChairs(), Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform(), Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinTraps(), Terraria.Player.PlaceThing_Tiles_PlaceIt_TriggerLogicLamp(), Terraria.Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids(), Terraria.WorldGen.PlaceTile(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.TileObject.random, Terraria.Player.selectedItem, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendObjectPlacement(), Terraria.ID.ItemID.Sets.SingleUseInGamepad, Terraria.Main.SmartCursorIsUsed, Terraria.WorldGen.SquareTileFrame(), Terraria.TileObject.style, Terraria.Main.tileContainer, Terraria.Player.tileSpeed, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Item.type, Terraria.TileObject.type, Terraria.Player.UsingBiomeTorches, Terraria.GameInput.PlayerInput.UsingGamepad, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.PlaceThing_Tiles().