TModLoader: Terraria.Player.ItemCheck_MeleeHitPVP
ItemCheck_MeleeHitPVP()
void Terraria.Player.ItemCheck_MeleeHitPVP (Item sItem, Rectangle itemRectangle, int damage, float knockBack) inline private
    {
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_019f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0348: Unknown result type (might be due to invalid IL or missing references)
        //IL_034e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0358: Unknown result type (might be due to invalid IL or missing references)
        //IL_035e: Unknown result type (might be due to invalid IL or missing references)
        if (!hostile)
        {
            return;
        }
        Vector2 vector = default(Vector2);
        Vector2 vector2 = default(Vector2);
        for (int i = 0; i < 255; i++)
        {
            Player player = Main.player[i];
            if (i == whoAmI || !player.active || !player.hostile || player.immune || player.dead || (team != 0 && team == player.team) || !((Rectangle)(ref itemRectangle)).Intersects(player.Hitbox) || !CanHit(player) || !CombinedHooks.CanHitPvp(this, sItem, player))
            {
                continue;
            }
            bool flag = false;
            int num = Main.DamageVar(damage, luck);
            StatusToPlayerPvP(sItem.type, i);
            OnHit(player.Center.X, player.Center.Y, player);
            PlayerDeathReason playerDeathReason = PlayerDeathReason.ByPlayerItem(whoAmI, sItem);
            int num2 = (int)player.Hurt(playerDeathReason, num, direction, pvp: true, quiet: false, flag, -1);
            if (inventory[selectedItem].type == 3211)
            {
                ((Vector2)(ref vector))._002Ector((float)(direction * 100 + Main.rand.Next(-25, 26)), (float)Main.rand.Next(-75, 76));
                ((Vector2)(ref vector)).Normalize();
                vector *= (float)Main.rand.Next(30, 41) * 0.1f;
                ((Vector2)(ref vector2))._002Ector((float)(itemRectangle.X + Main.rand.Next(itemRectangle.Width)), (float)(itemRectangle.Y + Main.rand.Next(itemRectangle.Height)));
                vector2 = (vector2 + player.Center * 2f) / 3f;
                Projectile.NewProjectile(GetProjectileSource_Item(HeldItem), vector2.X, vector2.Y, vector.X, vector.Y, 524, (int)((double)damage * 0.7), knockBack * 0.7f, whoAmI);
            }
            if (sItem.type == 5097)
            {
                BatBat_TryLifeLeeching(player);
            }
            if (beetleOffense)
            {
                beetleCounter += num2;
                beetleCountdown = 0;
            }
            if (meleeEnchant == 7)
            {
                Projectile.NewProjectile(GetProjectileSource_Misc(8), player.Center.X, player.Center.Y, player.velocity.X, player.velocity.Y, 289, 0, 0f, whoAmI);
            }
            if (sItem.type == 1123)
            {
                int num3 = Main.rand.Next(1, 4);
                if (strongBees && Main.rand.Next(3) == 0)
                {
                    num3++;
                }
                for (int j = 0; j < num3; j++)
                {
                    float num4 = (float)(direction * 2) + (float)Main.rand.Next(-35, 36) * 0.02f;
                    float num5 = (float)Main.rand.Next(-35, 36) * 0.02f;
                    num4 *= 0.2f;
                    num5 *= 0.2f;
                    int num6 = Projectile.NewProjectile(GetProjectileSource_Item(sItem), itemRectangle.X + itemRectangle.Width / 2, itemRectangle.Y + itemRectangle.Height / 2, num4, num5, beeType(), beeDamage(num / 3), beeKB(0f), whoAmI);
                    Main.projectile[num6].melee = true;
                }
            }
            if (inventory[selectedItem].type == 3106)
            {
                stealth = 1f;
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(84, -1, -1, null, whoAmI);
                }
            }
            if (Main.netMode != 0)
            {
                NetMessage.SendPlayerHurt(i, playerDeathReason, num, direction, flag, pvp: true, -1);
            }
            ApplyAttackCooldown();
        }
    }
References Terraria.Entity.active, Terraria.Player.ApplyAttackCooldown(), Terraria.Player.BatBat_TryLifeLeeching(), Terraria.Player.beeDamage(), Terraria.Player.beeKB(), Terraria.Player.beetleCountdown, Terraria.Player.beetleCounter, Terraria.Player.beetleOffense, Terraria.Player.beeType(), Terraria.DataStructures.PlayerDeathReason.ByPlayerItem(), Terraria.Player.CanHit(), Terraria.ModLoader.CombinedHooks.CanHitPvp(), Terraria.Entity.Center, Terraria.Main.DamageVar(), Terraria.Player.dead, Terraria.Entity.direction, Terraria.Player.GetProjectileSource_Item(), Terraria.Player.GetProjectileSource_Misc(), Terraria.Player.HeldItem, Terraria.Entity.Hitbox, Terraria.Player.hostile, Terraria.Player.Hurt(), Terraria.Player.immune, Terraria.Player.inventory, Terraria.Player.luck, Terraria.Player.meleeEnchant, Terraria.Main.netMode, Terraria.Projectile.NewProjectile(), Terraria.Player.OnHit(), Terraria.Main.player, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Player.selectedItem, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendPlayerHurt(), Terraria.Player.StatusToPlayerPvP(), Terraria.Player.stealth, Terraria.Player.strongBees, Terraria.Player.team, Terraria.Entity.velocity, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode().