TModLoader: Terraria.Player.QuickMinecart
QuickMinecart()
void Terraria.Player.QuickMinecart () inline private
Definition at line 6343 of file Player.cs.
    {
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0126: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0176: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_019b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        int num = 0;
        int value5 = (int)(position.X / 16f) - tileRangeX - num + 1;
        int value2 = (int)((position.X + (float)width) / 16f) + tileRangeX + num - 1;
        int value3 = (int)(position.Y / 16f) - tileRangeY - num + 1;
        int value4 = (int)((position.Y + (float)height) / 16f) + tileRangeY + num - 2;
        int num2 = Utils.Clamp(value5, 10, Main.maxTilesX - 10);
        value2 = Utils.Clamp(value2, 10, Main.maxTilesX - 10);
        value3 = Utils.Clamp(value3, 10, Main.maxTilesY - 10);
        List<Point> list = Collision.GetTilesIn(BottomRight: new Vector2((float)(value2 + 1), (float)(Utils.Clamp(value4, 10, Main.maxTilesY - 10) + 1)) * 16f, TopLeft: new Vector2((float)num2, (float)value3) * 16f);
        if (list.Count <= 0)
        {
            return;
        }
        Point? point = null;
        _ = base.Hitbox;
        for (int i = 0; i < list.Count; i++)
        {
            Point point2 = list[i];
            Tile tileSafely = Framing.GetTileSafely(point2.X, point2.Y);
            if (tileSafely.active() && tileSafely.type == 314)
            {
                Vector2 vector = list[i].ToVector2() * 16f + new Vector2(8f);
                if (!point.HasValue || (Distance(vector) < Distance(point.Value.ToVector2() * 16f + new Vector2(8f)) && Collision.CanHitLine(base.Center, 0, 0, vector, 0, 0)))
                {
                    point = list[i];
                }
            }
        }
        if (point.HasValue)
        {
            LaunchMinecartHook(point.Value.X, point.Value.Y);
        }
    }
References Terraria.Entity.BottomRight, Terraria.Collision.CanHitLine(), Terraria.Entity.Distance(), Terraria.Framing.GetTileSafely(), Terraria.Collision.GetTilesIn(), Terraria.Entity.height, Terraria.Player.LaunchMinecartHook(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Entity.position, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Entity.TopLeft, and Terraria.Entity.width.
Referenced by Terraria.Player.QuickMount().