TModLoader: Terraria.Player.GetFileData
GetFileData()
static PlayerFileData Terraria.Player.GetFileData (string file, bool cloudSave) inline static
Definition at line 56521 of file Player.cs.
    {
        if (file == null || (cloudSave && SocialAPI.Cloud == null))
        {
            return null;
        }
        PlayerFileData playerFileData = LoadPlayer(file, cloudSave);
        if (playerFileData.Player != null)
        {
            if (playerFileData.Player.loadStatus != 0 && playerFileData.Player.loadStatus != 1)
            {
                CustomModDataException customDataFail = playerFileData.customDataFail;
                if (FileUtilities.Exists(file + ".bak", cloudSave))
                {
                    FileUtilities.Move(file + ".bak", file, cloudSave);
                    PlayerIO.LoadBackup(file, cloudSave);
                }
                playerFileData = LoadPlayer(file, cloudSave);
                if (playerFileData.Player == null)
                {
                    return null;
                }
                playerFileData.customDataFail = customDataFail;
            }
            return playerFileData;
        }
        return null;
    }
References Terraria.Social.SocialAPI.Cloud, Terraria.Utilities.FileUtilities.Exists(), Terraria.ModLoader.IO.PlayerIO.LoadBackup(), Terraria.Player.LoadPlayer(), and Terraria.Utilities.FileUtilities.Move().
Referenced by Terraria.Main.AutoJoin(), Terraria.GameContent.UI.States.UICharacterSelect.LoadMigratablePlayers(), Terraria.Main.LoadPlayers(), Terraria.ModLoader.ModNet.NetReload(), and Terraria.GameContent.UI.Elements.UIWorldListItem.PlayReload().