TModLoader: Terraria.Player.FigureOutWhatToPlace
FigureOutWhatToPlace()
void Terraria.Player.FigureOutWhatToPlace (Tile targetTile, Item sItem, out int tileToCreate, out int previewPlaceStyle, out bool? overrideCanPlace, out int? forcedRandom) inline private
    {
        tileToCreate = sItem.createTile;
        previewPlaceStyle = sItem.placeStyle;
        overrideCanPlace = null;
        forcedRandom = null;
        if (UsingBiomeTorches && tileToCreate == 215 && previewPlaceStyle == 0)
        {
            BiomeCampfirePlaceStyle(ref tileToCreate, ref previewPlaceStyle);
        }
        if (targetTile != null && targetTile.active())
        {
            ushort type = targetTile.type;
            if (tileToCreate == 23 && type == 59)
            {
                tileToCreate = 661;
            }
            if (tileToCreate == 199 && type == 59)
            {
                tileToCreate = 662;
            }
        }
        if (!ModifyFlexibleWandPlacementInfo(ref tileToCreate, ref previewPlaceStyle, ref forcedRandom))
        {
            overrideCanPlace = false;
        }
    }
References Terraria.Player.BiomeCampfirePlaceStyle(), Terraria.Player.ModifyFlexibleWandPlacementInfo(), and Terraria.Player.UsingBiomeTorches.
Referenced by Terraria.Player.PlaceThing_Tiles(), and Terraria.Player.UpdatePlacementPreview().