TModLoader: Terraria.Player.ItemCheck_PlayInstruments
ItemCheck_PlayInstruments()
void Terraria.Player.ItemCheck_PlayInstruments (Item sItem) inline private
    {
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0181: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_05df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_030b: Unknown result type (might be due to invalid IL or missing references)
        //IL_042a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0443: Unknown result type (might be due to invalid IL or missing references)
        //IL_0469: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_052f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0548: Unknown result type (might be due to invalid IL or missing references)
        //IL_056e: Unknown result type (might be due to invalid IL or missing references)
        //IL_038e: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06be: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e4: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
        float num30 = (float)Main.mouseX + Main.screenPosition.X - vector.X;
        float num18 = (float)Main.mouseY + Main.screenPosition.Y - vector.Y;
        float num25 = (float)Math.Sqrt(num30 * num30 + num18 * num18);
        float num26 = (float)Main.screenHeight / Main.GameViewMatrix.Zoom.Y;
        num25 /= num26 / 2f;
        if (num25 > 1f)
        {
            num25 = 1f;
        }
        musicDist = num25;
        if (itemAnimation > 0 && ItemTimeIsZero && (sItem.type == 508 || sItem.type == 507))
        {
            ApplyItemTime(sItem);
            Vector2 vector2 = default(Vector2);
            ((Vector2)(ref vector2))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
            float num31 = (float)Main.mouseX + Main.screenPosition.X - vector2.X;
            float num27 = (float)Main.mouseY + Main.screenPosition.Y - vector2.Y;
            float num28 = (float)Math.Sqrt(num31 * num31 + num27 * num27);
            float num29 = (float)Main.screenHeight / Main.GameViewMatrix.Zoom.Y;
            num28 /= num29 / 2f;
            if (num28 > 1f)
            {
                num28 = 1f;
            }
            num28 = num28 * 2f - 1f;
            if (num28 < -1f)
            {
                num28 = -1f;
            }
            if (num28 > 1f)
            {
                num28 = 1f;
            }
            num28 = (float)Math.Round(num28 * (float)musicNotes);
            num28 = (Main.musicPitch = num28 / (float)musicNotes);
            SoundStyle type = SoundID.Item26;
            if (sItem.type == 507)
            {
                type = SoundID.Item35;
            }
            SoundEngine.PlaySound(in type, position);
            NetMessage.SendData(58, -1, -1, null, whoAmI, num28);
        }
        if (itemAnimation <= 0 || mouseInterface)
        {
            return;
        }
        if (Main.mouseLeft && Main.mouseLeftRelease)
        {
            if (sItem.type == 1305)
            {
                Vector2 vector3 = default(Vector2);
                ((Vector2)(ref vector3))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                float num32 = (float)Main.mouseX + Main.screenPosition.X - vector3.X;
                float num10 = (float)Main.mouseY + Main.screenPosition.Y - vector3.Y;
                float num11 = (float)Math.Sqrt(num32 * num32 + num10 * num10);
                float num12 = (float)Main.screenHeight / Main.GameViewMatrix.Zoom.Y;
                num11 /= num12 / 2f;
                if (num11 > 1f)
                {
                    num11 = 1f;
                }
                num11 = num11 * 2f - 1f;
                if (num11 < -1f)
                {
                    num11 = -1f;
                }
                if (num11 > 1f)
                {
                    num11 = 1f;
                }
                num11 = (float)Math.Round(num11 * (float)musicNotes);
                num11 = (Main.musicPitch = num11 / (float)musicNotes);
                SoundEngine.PlaySound(in SoundID.Item47, position);
                NetMessage.SendData(58, -1, -1, null, whoAmI, num11);
            }
            else if (sItem.type == 4057 || sItem.type == 4372)
            {
                Vector2 vector4 = default(Vector2);
                ((Vector2)(ref vector4))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
                float num33 = (float)Main.mouseX + Main.screenPosition.X - vector4.X;
                float num13 = (float)Main.mouseY + Main.screenPosition.Y - vector4.Y;
                float num14 = (float)Math.Sqrt(num33 * num33 + num13 * num13);
                float num15 = (float)Main.screenHeight / Main.GameViewMatrix.Zoom.Y;
                num14 /= num15 / 2f;
                if (num14 > 1f)
                {
                    num14 = 1f;
                }
                PlayGuitarChord(num14);
                NetMessage.SendData(58, -1, -1, null, whoAmI, num14);
            }
        }
        if (sItem.type == 4715 && ((Main.mouseLeft && Main.mouseLeftRelease) | ItemAnimationJustStarted))
        {
            Vector2 vector5 = default(Vector2);
            ((Vector2)(ref vector5))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
            float num34 = (float)Main.mouseX + Main.screenPosition.X - vector5.X;
            float num16 = (float)Main.mouseY + Main.screenPosition.Y - vector5.Y;
            float num17 = (float)Math.Sqrt(num34 * num34 + num16 * num16);
            float num19 = (float)Main.screenHeight / Main.GameViewMatrix.Zoom.Y;
            num17 /= num19 / 2f;
            if (num17 > 1f)
            {
                num17 = 1f;
            }
            PlayGuitarChord(num17);
            NetMessage.SendData(58, -1, -1, null, whoAmI, num17);
        }
        if (sItem.type != 4673)
        {
            return;
        }
        int num20 = (int)base.Center.X / 16;
        int num21 = (int)base.Center.Y / 16;
        if (WorldGen.InWorld(num20, num21) && Main.tile[num20, num21] != null && Main.tile[num20, num21].type == 486 && ((Main.mouseLeft && Main.mouseLeftRelease) || (Main.mouseRight && Main.mouseRightRelease)))
        {
            Vector2 vector6 = default(Vector2);
            ((Vector2)(ref vector6))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
            float num35 = (float)Main.mouseX + Main.screenPosition.X - vector6.X;
            float num22 = (float)Main.mouseY + Main.screenPosition.Y - vector6.Y;
            float num23 = (float)Math.Sqrt(num35 * num35 + num22 * num22);
            float num24 = (float)Main.screenHeight / Main.GameViewMatrix.Zoom.Y;
            num23 /= num24 / 2f;
            if (num23 > 1f)
            {
                num23 = 1f;
            }
            PlayDrums(num23);
            NetMessage.SendData(58, -1, -1, null, whoAmI, num23);
        }
    }
References Terraria.Player.ApplyItemTime(), Terraria.Main.GameViewMatrix, Terraria.Entity.height, Terraria.WorldGen.InWorld(), Terraria.ID.SoundID.Item26, Terraria.ID.SoundID.Item35, Terraria.ID.SoundID.Item47, Terraria.Player.itemAnimation, Terraria.Player.ItemAnimationJustStarted, Terraria.Player.ItemTimeIsZero, Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Player.musicDist, Terraria.Player.musicNotes, Terraria.Player.PlayDrums(), Terraria.Player.PlayGuitarChord(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode().