TModLoader: Terraria.Player.PlaceThing_Tiles
PlaceThing_Tiles()
void Terraria.Player.PlaceThing_Tiles () inline private
Definition at line 38516 of file Player.cs.
    {
        Item item = inventory[selectedItem];
        int tileToCreate = item.createTile;
        if (tileToCreate < 0 || !(position.X / 16f - (float)tileRangeX - (float)item.tileBoost - (float)blockRange <= (float)tileTargetX) || !((position.X + (float)width) / 16f + (float)tileRangeX + (float)item.tileBoost - 1f + (float)blockRange >= (float)tileTargetX) || !(position.Y / 16f - (float)tileRangeY - (float)item.tileBoost - (float)blockRange <= (float)tileTargetY) || !((position.Y + (float)height) / 16f + (float)tileRangeY + (float)item.tileBoost - 2f + (float)blockRange >= (float)tileTargetY))
        {
            return;
        }
        cursorItemIconEnabled = true;
        bool flag = PlaceThing_Tiles_CheckLavaBlocking();
        bool canUse = true;
        canUse = PlaceThing_Tiles_CheckGamepadTorchUsability(canUse);
        canUse = PlaceThing_Tiles_CheckWandUsability(canUse);
        canUse = PlaceThing_Tiles_CheckRopeUsability(canUse);
        canUse = PlaceThing_Tiles_CheckFlexibleWand(canUse);
        if (TileReplacementEnabled)
        {
            canUse = PlaceThing_TryReplacingTiles(canUse);
        }
        Tile tile = Main.tile[tileTargetX, tileTargetY];
        if (tile.active())
        {
            if (tileToCreate == 23 && tile.type == 59)
            {
                tileToCreate = 661;
            }
            if (tileToCreate == 199 && tile.type == 59)
            {
                tileToCreate = 662;
            }
        }
        if (canUse && ((!tile.active() && !flag) || (Main.tileCut[tile.type] && tile.type != 484) || (tile.type >= 373 && tile.type <= 375) || tile.type == 461 || tileToCreate == 199 || tileToCreate == 23 || tileToCreate == 662 || tileToCreate == 661 || tileToCreate == 2 || tileToCreate == 109 || tileToCreate == 60 || tileToCreate == 70 || tileToCreate == 633 || Main.tileMoss[tileToCreate] || TileID.Sets.BreakableWhenPlacing[tile.type]) && ItemTimeIsZero && itemAnimation > 0 && controlUseItem)
        {
            bool canPlace = false;
            bool newObjectType = false;
            bool? overrideCanPlace = null;
            int? forcedRandom = null;
            TileObject objectData = default(TileObject);
            FigureOutWhatToPlace(tile, item, out tileToCreate, out var previewPlaceStyle, out overrideCanPlace, out forcedRandom);
            PlantLoader.CheckAndInjectModSapling(tileTargetX, tileTargetY, ref tileToCreate, ref previewPlaceStyle);
            if (overrideCanPlace.HasValue)
            {
                canPlace = overrideCanPlace.Value;
            }
            else if (TileObjectData.CustomPlace(tileToCreate, previewPlaceStyle) && tileToCreate != 82 && tileToCreate != 227)
            {
                newObjectType = true;
                canPlace = TileObject.CanPlace(tileTargetX, tileTargetY, (ushort)tileToCreate, previewPlaceStyle, direction, out objectData, onlyCheck: false, forcedRandom);
                PlaceThing_Tiles_BlockPlacementIfOverPlayers(ref canPlace, ref objectData);
                PlaceThing_Tiles_BlockPlacementForRepeatedPigronatas(ref canPlace, ref objectData);
                PlaceThing_Tiles_BlockPlacementForRepeatedPumpkins(ref canPlace, ref objectData);
                PlaceThing_Tiles_BlockPlacementForRepeatedCoralAndBeachPiles(ref canPlace, ref objectData);
            }
            else
            {
                canPlace = PlaceThing_Tiles_BlockPlacementForAssortedThings(canPlace);
            }
            if (canPlace)
            {
                PlaceThing_Tiles_PlaceIt(newObjectType, objectData, tileToCreate);
            }
        }
    }
References Terraria.Tile.active(), Terraria.Player.blockRange, Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.TileObject.CanPlace(), Terraria.ModLoader.PlantLoader.CheckAndInjectModSapling(), Terraria.Player.controlUseItem, Terraria.Item.createTile, Terraria.Player.cursorItemIconEnabled, Terraria.ObjectData.TileObjectData.CustomPlace(), Terraria.Entity.direction, Terraria.Player.FigureOutWhatToPlace(), Terraria.Entity.height, Terraria.Player.inventory, Terraria.Player.itemAnimation, Terraria.Player.ItemTimeIsZero, Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForRepeatedCoralAndBeachPiles(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForRepeatedPigronatas(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForRepeatedPumpkins(), Terraria.Player.PlaceThing_Tiles_BlockPlacementIfOverPlayers(), Terraria.Player.PlaceThing_Tiles_CheckFlexibleWand(), Terraria.Player.PlaceThing_Tiles_CheckGamepadTorchUsability(), Terraria.Player.PlaceThing_Tiles_CheckLavaBlocking(), Terraria.Player.PlaceThing_Tiles_CheckRopeUsability(), Terraria.Player.PlaceThing_Tiles_CheckWandUsability(), Terraria.Player.PlaceThing_Tiles_PlaceIt(), Terraria.Player.PlaceThing_TryReplacingTiles(), Terraria.Entity.position, Terraria.Player.selectedItem, Terraria.Main.tile, Terraria.Item.tileBoost, Terraria.Main.tileCut, Terraria.Main.tileMoss, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Player.TileReplacementEnabled, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Tile.type, and Terraria.Entity.width.
Referenced by Terraria.Player.PlaceThing().