TModLoader: Terraria.Player.BiomeTorchPlaceStyle
BiomeTorchPlaceStyle()
int Terraria.Player.BiomeTorchPlaceStyle (ref int type, ref int style) inline
Definition at line 38940 of file Player.cs.
    {
        if (!UsingBiomeTorches || style != 0)
        {
            return style;
        }
        if (ZoneShimmer)
        {
            style = 23;
        }
        else if (ZoneLihzhardTemple)
        {
            style = 21;
        }
        else if (ZoneDungeon)
        {
            style = 13;
        }
        else if (position.Y > (float)(Main.UnderworldLayer * 16))
        {
            style = 7;
        }
        else if (ZoneHallow)
        {
            style = 20;
        }
        else if (ZoneCorrupt)
        {
            style = 18;
        }
        else if (ZoneCrimson)
        {
            style = 19;
        }
        else if (ZoneSnow)
        {
            style = 9;
        }
        else if (ZoneGlowshroom)
        {
            style = 22;
        }
        else if (ZoneJungle)
        {
            style = 21;
        }
        else if ((ZoneDesert && (double)position.Y < Main.worldSurface * 16.0) || ZoneUndergroundDesert)
        {
            style = 16;
        }
        else if (ZoneDesert && Main.remixWorld)
        {
            style = 16;
        }
        if (CurrentSceneEffect.biomeTorchItemType.value > -1)
        {
            Item item = ContentSamples.ItemsByType[CurrentSceneEffect.biomeTorchItemType.value];
            type = item.createTile;
            style = item.placeStyle;
        }
        return style;
    }
References Terraria.Item.createTile, Terraria.Player.CurrentSceneEffect, Terraria.ID.ContentSamples.ItemsByType, Terraria.Item.placeStyle, Terraria.Entity.position, Terraria.Main.remixWorld, Terraria.Main.UnderworldLayer, Terraria.Player.UsingBiomeTorches, Terraria.Main.worldSurface, Terraria.Player.ZoneCorrupt, Terraria.Player.ZoneCrimson, Terraria.Player.ZoneDesert, Terraria.Player.ZoneDungeon, Terraria.Player.ZoneGlowshroom, Terraria.Player.ZoneHallow, Terraria.Player.ZoneJungle, Terraria.Player.ZoneLihzhardTemple, Terraria.Player.ZoneShimmer, Terraria.Player.ZoneSnow, and Terraria.Player.ZoneUndergroundDesert.
Referenced by Terraria.Player.PlaceThing_Tiles_PlaceIt(), Terraria.Player.PlaceThing_TryReplacingTiles(), and Terraria.Player.PlaceThing_ValidTileForReplacement().