TModLoader: Terraria.Player.QuickMount_GetItemToUse
QuickMount_GetItemToUse()
Item Terraria.Player.QuickMount_GetItemToUse () inline
Definition at line 6465 of file Player.cs.
    {
        Item item = null;
        bool equippedMountSufficient = false;
        if (item == null && miscEquips[3].mountType != -1 && !MountID.Sets.Cart[miscEquips[3].mountType])
        {
            equippedMountSufficient = true;
        }
        if (equippedMountSufficient && CombinedHooks.CanUseItem(this, miscEquips[3]))
        {
            item = miscEquips[3];
        }
        if (item == null)
        {
            for (int i = 0; i < 58; i++)
            {
                if (inventory[i].mountType != -1 && !MountID.Sets.Cart[inventory[i].mountType] && CombinedHooks.CanUseItem(this, inventory[i]))
                {
                    item = inventory[i];
                    break;
                }
            }
        }
        return item;
    }
References Terraria.ModLoader.CombinedHooks.CanUseItem(), Terraria.ID.MountID.Sets.Cart, Terraria.Player.inventory, Terraria.Player.miscEquips, and Terraria.Item.mountType.
Referenced by Terraria.Player.QuickMount(), and Terraria.GameContent.ChromaHotkeyPainter.Step_Mount().