TModLoader: Terraria.Player.StatusFromNPC
StatusFromNPC()
void Terraria.Player.StatusFromNPC (NPC npc) inline
    {
        if (Main.expertMode && ((npc.type == 266 && Main.rand.Next(3) == 0) || npc.type == 267))
        {
            int num = Main.rand.Next(9);
            if (num == 2 || num == 4)
            {
                num = Main.rand.Next(9);
            }
            float num2 = (float)Main.rand.Next(75, 150) * 0.01f;
            switch (num)
            {
            case 0:
                AddBuff(20, (int)(60f * num2 * 3.5f));
                break;
            case 1:
                AddBuff(22, (int)(60f * num2 * 2f));
                break;
            case 2:
                AddBuff(23, (int)(60f * num2 * 0.5f));
                break;
            case 3:
                AddBuff(30, (int)(60f * num2 * 5f));
                break;
            case 4:
                AddBuff(31, (int)(60f * num2 * 1f));
                break;
            case 5:
                AddBuff(32, (int)(60f * num2 * 3.5f));
                break;
            case 6:
                AddBuff(33, (int)(60f * num2 * 7.5f));
                break;
            case 7:
                AddBuff(35, (int)(60f * num2 * 1f));
                break;
            case 8:
                AddBuff(36, (int)((double)(60f * num2) * 6.5));
                break;
            }
        }
        if (npc.type == 530 || npc.type == 531)
        {
            AddBuff(70, Main.rand.Next(240, 241));
        }
        if (npc.type == 159 || npc.type == 158)
        {
            AddBuff(30, Main.rand.Next(300, 600));
        }
        if (npc.type == 525)
        {
            AddBuff(39, 240);
        }
        if (npc.type == 526)
        {
            AddBuff(69, 420);
        }
        if (npc.type == 527)
        {
            AddBuff(31, 840);
        }
        if (Main.expertMode && (npc.type == 49 || npc.type == 93 || npc.type == 51 || npc.type == 152 || npc.type == 634) && Main.rand.Next(10) == 0)
        {
            AddBuff(148, Main.rand.Next(1800, 5400));
        }
        if (Main.expertMode && npc.type == 222)
        {
            AddBuff(20, Main.rand.Next(60, 240));
        }
        if (Main.expertMode && (npc.type == 210 || npc.type == 211))
        {
            AddBuff(20, Main.rand.Next(60, 180));
        }
        if (Main.expertMode && npc.type == 35)
        {
            AddBuff(30, Main.rand.Next(180, 300));
        }
        if (Main.expertMode && npc.type == 36 && Main.rand.Next(2) == 0)
        {
            AddBuff(32, Main.rand.Next(30, 60));
        }
        if (npc.type >= 269 && npc.type <= 272)
        {
            if (Main.rand.Next(3) == 0)
            {
                AddBuff(30, 600);
            }
            else if (Main.rand.Next(3) == 0)
            {
                AddBuff(32, 300);
            }
        }
        if (npc.type >= 273 && npc.type <= 276 && Main.rand.Next(2) == 0)
        {
            AddBuff(36, 600);
        }
        if (npc.type >= 277 && npc.type <= 280)
        {
            AddBuff(24, 600);
        }
        if (npc.type == 371)
        {
            AddBuff(103, 60 * Main.rand.Next(3, 8));
        }
        if (npc.type == 370 && Main.expertMode)
        {
            int num3 = Utils.SelectRandom<int>(Main.rand, 0, 148, 30);
            if (num3 != 0)
            {
                AddBuff(num3, 60 * Main.rand.Next(3, 11));
            }
        }
        if (((npc.type == 1 && npc.netID == -6) || npc.type == 81 || npc.type == 79 || npc.type == 183 || npc.type == 630) && Main.rand.Next(4) == 0)
        {
            AddBuff(22, 900);
        }
        if ((npc.type == 23 || npc.type == 25) && Main.rand.Next(3) == 0)
        {
            AddBuff(24, 420);
        }
        if ((npc.type == 34 || npc.type == 83 || npc.type == 84 || npc.type == 179 || npc.type == 289) && Main.rand.Next(3) == 0)
        {
            AddBuff(23, 240);
        }
        if ((npc.type == 104 || npc.type == 102) && Main.rand.Next(8) == 0)
        {
            AddBuff(30, 2700);
        }
        if (npc.type == 75 && Main.rand.Next(10) == 0)
        {
            AddBuff(35, 420);
        }
        if ((npc.type == 163 || npc.type == 238 || npc.type == 236 || npc.type == 237) && Main.rand.Next(10) == 0)
        {
            AddBuff(70, 240);
        }
        if ((npc.type == 79 || npc.type == 103 || npc.type == 630) && Main.rand.Next(5) == 0)
        {
            AddBuff(35, 420);
        }
        if ((npc.type == 75 || npc.type == 78 || npc.type == 82) && Main.rand.Next(8) == 0)
        {
            AddBuff(32, 900);
        }
        if ((npc.type == 93 || npc.type == 109 || npc.type == 80) && Main.rand.Next(14) == 0)
        {
            AddBuff(31, 300);
        }
        if (npc.type >= 305 && npc.type <= 314 && Main.rand.Next(10) == 0)
        {
            AddBuff(33, 3600);
        }
        if (npc.type == 77 && Main.rand.Next(6) == 0)
        {
            AddBuff(36, 7200);
        }
        if (npc.type == 112 && Main.rand.Next(20) == 0)
        {
            AddBuff(33, 18000);
        }
        if (npc.type == 182 && Main.rand.Next(25) == 0)
        {
            AddBuff(33, 7200);
        }
        if (npc.type == 141 && Main.rand.Next(2) == 0)
        {
            AddBuff(20, 600);
        }
        if (npc.type == 147 && !frozen && Main.rand.Next(12) == 0)
        {
            AddBuff(46, 600);
        }
        if (npc.type == 150)
        {
            if (Main.rand.Next(2) == 0)
            {
                AddBuff(46, 900);
            }
            if (!frozen && Main.rand.Next(35) == 0)
            {
                AddBuff(47, 60);
            }
            else if (!frozen && Main.expertMode && Main.rand.Next(35) == 0)
            {
                AddBuff(47, 60);
            }
        }
        if (npc.type == 184)
        {
            AddBuff(46, 1200);
            if (!frozen && Main.rand.Next(15) == 0)
            {
                AddBuff(47, 60);
            }
            else if (!frozen && Main.expertMode && Main.rand.Next(25) == 0)
            {
                AddBuff(47, 60);
            }
        }
    }
References Terraria.Player.AddBuff(), Terraria.Main.expertMode, Terraria.Player.frozen, Terraria.NPC.netID, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, and Terraria.NPC.type.
Referenced by Terraria.Player.Update_NPCCollision().