TModLoader: Terraria.Player.DoCoins
DoCoins()
void Terraria.Player.DoCoins (int i) inline
Definition at line 38062 of file Player.cs.
    {
        if (inventory[i].stack != 100 || (inventory[i].type != 71 && inventory[i].type != 72 && inventory[i].type != 73))
        {
            return;
        }
        inventory[i].SetDefaults(inventory[i].type + 1);
        for (int j = 0; j < 54; j++)
        {
            if (inventory[j].IsTheSameAs(inventory[i]) && j != i && inventory[j].type == inventory[i].type && inventory[j].stack < inventory[j].maxStack)
            {
                inventory[j].stack++;
                inventory[i].SetDefaults();
                inventory[i].active = false;
                inventory[i].TurnToAir();
                DoCoins(j);
            }
        }
    }
References Terraria.Entity.active, Terraria.Player.DoCoins(), Terraria.Player.inventory, Terraria.Item.SetDefaults(), Terraria.Item.stack, and Terraria.Item.TurnToAir().
Referenced by Terraria.Player.DoCoins(), Terraria.Player.FillAmmo(), Terraria.Player.GetItem_FillEmptyInventorySlot(), Terraria.Player.GetItem_FillEmptyInventorySlot_VoidBag(), Terraria.Player.GetItem_FillIntoOccupiedSlot(), and Terraria.Player.SellItem().