TModLoader: Terraria.Player.UpdateManaRegen
UpdateManaRegen()
void Terraria.Player.UpdateManaRegen () inline
Definition at line 17767 of file Player.cs.
    {
        //IL_0256: Unknown result type (might be due to invalid IL or missing references)
        //IL_027a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0280: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d2: Unknown result type (might be due to invalid IL or missing references)
        if (nebulaLevelMana > 0)
        {
            int num = 6;
            nebulaManaCounter += nebulaLevelMana;
            if (nebulaManaCounter >= num)
            {
                nebulaManaCounter -= num;
                statMana++;
                if (statMana >= statManaMax2)
                {
                    statMana = statManaMax2;
                }
            }
        }
        else
        {
            nebulaManaCounter = 0;
        }
        if (manaRegenDelay > 0f)
        {
            manaRegenDelay -= 1f;
            manaRegenDelay -= manaRegenDelayBonus;
            if (IsStandingStillForSpecialEffects || grappling[0] >= 0 || manaRegenBuff)
            {
                manaRegenDelay -= 1f;
            }
            if (usedArcaneCrystal)
            {
                manaRegenDelay -= 0.05f;
            }
        }
        if (manaRegenBuff && manaRegenDelay > 20f)
        {
            manaRegenDelay = 20f;
        }
        if (manaRegenDelay <= 0f)
        {
            manaRegenDelay = 0f;
            manaRegen = statManaMax2 / 3 + 1 + manaRegenBonus;
            if (IsStandingStillForSpecialEffects || grappling[0] >= 0 || manaRegenBuff)
            {
                manaRegen += statManaMax2 / 3;
            }
            if (usedArcaneCrystal)
            {
                manaRegen += statManaMax2 / 50;
            }
            float num2 = (float)statMana / (float)statManaMax2 * 0.8f + 0.2f;
            if (manaRegenBuff)
            {
                num2 = 1f;
            }
            manaRegen = (int)((double)((float)manaRegen * num2) * 1.15);
        }
        else
        {
            manaRegen = 0;
        }
        manaRegenCount += manaRegen;
        while (manaRegenCount >= 120)
        {
            bool flag = false;
            manaRegenCount -= 120;
            if (statMana < statManaMax2)
            {
                statMana++;
                flag = true;
            }
            if (statMana < statManaMax2)
            {
                continue;
            }
            if (whoAmI == Main.myPlayer && flag)
            {
                SoundEngine.PlaySound(25);
                for (int i = 0; i < 5; i++)
                {
                    int num3 = Dust.NewDust(position, width, height, 45, 0f, 0f, 255, default(Color), (float)Main.rand.Next(20, 26) * 0.1f);
                    Main.dust[num3].noLight = true;
                    Main.dust[num3].noGravity = true;
                    Dust obj = Main.dust[num3];
                    obj.velocity *= 0.5f;
                }
            }
            statMana = statManaMax2;
        }
    }
References Terraria.Main.dust, Terraria.Player.grappling, Terraria.Entity.height, Terraria.Player.IsStandingStillForSpecialEffects, Terraria.Player.manaRegen, Terraria.Player.manaRegenBonus, Terraria.Player.manaRegenBuff, Terraria.Player.manaRegenCount, Terraria.Player.manaRegenDelay, Terraria.Player.manaRegenDelayBonus, Terraria.Main.myPlayer, Terraria.Player.nebulaLevelMana, Terraria.Player.nebulaManaCounter, Terraria.Dust.NewDust(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Player.statMana, Terraria.Player.statManaMax2, Terraria.Player.usedArcaneCrystal, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().