TModLoader: Terraria.Player.clientClone
clientClone()
Player Terraria.Player.clientClone () inline
    {
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        using (new Item.DisableCloneMethod("Item.Clone is bad for performance, and should not be called during Player.clientClone or ModPlayer.CopyClientStateTo. Use Item.CopyNetStateTo instead"))
        {
            Player player = _clientClone ?? (_clientClone = new Player());
            player.zone1 = zone1;
            player.zone2 = zone2;
            player.zone3 = zone3;
            player.zone4 = zone4;
            player.zone5 = zone5;
            player.voidVaultInfo = voidVaultInfo;
            player.luck = luck;
            BiomeLoader.CopyCustomBiomesTo(this, player);
            player.extraAccessory = extraAccessory;
            player.MinionRestTargetPoint = MinionRestTargetPoint;
            player.MinionAttackTargetNPC = MinionAttackTargetNPC;
            player.direction = direction;
            player.selectedItem = selectedItem;
            player.controlUp = controlUp;
            player.controlDown = controlDown;
            player.controlLeft = controlLeft;
            player.controlRight = controlRight;
            player.controlJump = controlJump;
            player.controlUseItem = controlUseItem;
            player.controlDownHold = controlDownHold;
            player.isOperatingAnotherEntity = isOperatingAnotherEntity;
            player.autoReuseAllWeapons = autoReuseAllWeapons;
            player.statLife = statLife;
            player.statLifeMax = statLifeMax;
            player.statMana = statMana;
            player.statManaMax = statManaMax;
            player.position.X = position.X;
            player.tileEntityAnchor = tileEntityAnchor;
            player.chest = chest;
            player.talkNPC = talkNPC;
            player.piggyBankProjTracker = piggyBankProjTracker;
            player.voidLensChest = voidLensChest;
            player.hideVisibleAccessory = hideVisibleAccessory;
            player.hideMisc = hideMisc;
            player.shieldRaised = shieldRaised;
            for (int i = 0; i < 59; i++)
            {
                inventory[i].CopyNetStateTo(player.inventory[i]);
                if (i < armor.Length)
                {
                    armor[i].CopyNetStateTo(player.armor[i]);
                }
                if (i < dye.Length)
                {
                    dye[i].CopyNetStateTo(player.dye[i]);
                }
                if (i < miscEquips.Length)
                {
                    miscEquips[i].CopyNetStateTo(player.miscEquips[i]);
                }
                if (i < miscDyes.Length)
                {
                    miscDyes[i].CopyNetStateTo(player.miscDyes[i]);
                }
                if (i < bank.item.Length)
                {
                    bank.item[i].CopyNetStateTo(player.bank.item[i]);
                }
                if (i < bank2.item.Length)
                {
                    bank2.item[i].CopyNetStateTo(player.bank2.item[i]);
                }
                if (i < bank3.item.Length)
                {
                    bank3.item[i].CopyNetStateTo(player.bank3.item[i]);
                }
                if (i < bank4.item.Length)
                {
                    bank4.item[i].CopyNetStateTo(player.bank4.item[i]);
                }
            }
            CloneLoadouts(player);
            trashItem.CopyNetStateTo(player.trashItem);
            for (int j = 0; j < maxBuffs; j++)
            {
                player.buffType[j] = buffType[j];
                player.buffTime[j] = buffTime[j];
            }
            DpadRadial.CopyTo(player.DpadRadial);
            CircularRadial.CopyTo(player.CircularRadial);
            PlayerLoader.CopyClientState(this, player);
            return player;
        }
    }
References Terraria.Player.Player(), Terraria.Player._clientClone, Terraria.Player.armor, Terraria.Player.autoReuseAllWeapons, Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Player.buffTime, Terraria.Player.buffType, Terraria.Player.chest, Terraria.Player.CircularRadial, Terraria.Player.CloneLoadouts(), Terraria.Player.controlDown, Terraria.Player.controlDownHold, Terraria.Player.controlJump, Terraria.Player.controlLeft, Terraria.Player.controlRight, Terraria.Player.controlUp, Terraria.Player.controlUseItem, Terraria.ModLoader.PlayerLoader.CopyClientState(), Terraria.ModLoader.BiomeLoader.CopyCustomBiomesTo(), Terraria.Item.CopyNetStateTo(), Terraria.Player.SelectionRadial.CopyTo(), Terraria.Entity.direction, Terraria.Player.DpadRadial, Terraria.Player.dye, Terraria.Player.extraAccessory, Terraria.Player.hideMisc, Terraria.Player.hideVisibleAccessory, Terraria.Player.inventory, Terraria.Player.isOperatingAnotherEntity, Terraria.Chest.item, Terraria.Player.luck, Terraria.Player.maxBuffs, Terraria.Player.MinionAttackTargetNPC, Terraria.Player.MinionRestTargetPoint, Terraria.Player.miscDyes, Terraria.Player.miscEquips, Terraria.Player.piggyBankProjTracker, Terraria.Entity.position, Terraria.Player.selectedItem, Terraria.Player.shieldRaised, Terraria.Player.statLife, Terraria.Player.statLifeMax, Terraria.Player.statMana, Terraria.Player.statManaMax, Terraria.Player.talkNPC, Terraria.Player.tileEntityAnchor, Terraria.Player.trashItem, Terraria.Player.voidLensChest, Terraria.Player.voidVaultInfo, Terraria.Player.zone1, Terraria.Player.zone2, Terraria.Player.zone3, Terraria.Player.zone4, and Terraria.Player.zone5.