TModLoader: Terraria.Player.BatBat_TryLifeLeeching
BatBat_TryLifeLeeching()
void Terraria.Player.BatBat_TryLifeLeeching (Entity entity) inline private
    {
        if (_batbatCanHeal && statLife < statLifeMax2 && (!(entity is NPC nPC) || nPC.HittableForOnHitRewards()))
        {
            _batbatCanHeal = false;
            Heal(1);
        }
    }
References Terraria.Player._batbatCanHeal, Terraria.Player.Heal(), Terraria.Player.statLife, and Terraria.Player.statLifeMax2.
Referenced by Terraria.Player.ApplyNPCOnHitEffects(), and Terraria.Player.ItemCheck_MeleeHitPVP().