TModLoader: Terraria.Player.HasItem
HasItem() [1/2]
bool Terraria.Player.HasItem (int type) inline
Checks if the player has the specified item in their F:Terraria.Player.inventory.
Does not check Void Bag.
Use M:Terraria.Player.CountItem(System.Int32,System.Int32) instead to count the total amount if needed.
Parameters
type The item type to count
Returns
True if the player has the item
Definition at line 56568 of file Player.cs.
    {
        for (int i = 0; i < 58; i++)
        {
            if (type == inventory[i].type && inventory[i].stack > 0)
            {
                return true;
            }
        }
        return false;
    }
References Terraria.Player.inventory.
Referenced by Terraria.Player.GetItem(), Terraria.Player.HasItemInAnyInventory(), Terraria.Player.HasItemInInventoryOrOpenVoidBag(), Terraria.Player.ItemSpace(), Terraria.Player.TileInteractionsMouseOver(), Terraria.Player.TileInteractionsUse(), and Terraria.Player.Update().