TModLoader: Terraria.Player.StickyMovement
StickyMovement()
void Terraria.Player.StickyMovement () inline
Definition at line 20822 of file Player.cs.
    {
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0510: Unknown result type (might be due to invalid IL or missing references)
        //IL_051a: Unknown result type (might be due to invalid IL or missing references)
        //IL_051f: Unknown result type (might be due to invalid IL or missing references)
        //IL_040c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0427: Unknown result type (might be due to invalid IL or missing references)
        //IL_042d: Unknown result type (might be due to invalid IL or missing references)
        //IL_046b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0475: Unknown result type (might be due to invalid IL or missing references)
        //IL_047a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0673: Unknown result type (might be due to invalid IL or missing references)
        //IL_068e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0694: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_062a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0634: Unknown result type (might be due to invalid IL or missing references)
        //IL_0639: Unknown result type (might be due to invalid IL or missing references)
        //IL_0831: Unknown result type (might be due to invalid IL or missing references)
        //IL_084c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0852: Unknown result type (might be due to invalid IL or missing references)
        //IL_0890: Unknown result type (might be due to invalid IL or missing references)
        //IL_089a: Unknown result type (might be due to invalid IL or missing references)
        //IL_089f: Unknown result type (might be due to invalid IL or missing references)
        //IL_078d: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fb: Unknown result type (might be due to invalid IL or missing references)
        if (shimmering)
        {
            return;
        }
        bool flag = false;
        if (mount.Type > 0 && MountID.Sets.Cart[mount.Type] && Math.Abs(velocity.X) > 5f)
        {
            flag = true;
        }
        int num = width / 2;
        int num3 = height / 2;
        new Vector2(position.X + (float)(width / 2) - (float)(num / 2), position.Y + (float)(height / 2) - (float)(num3 / 2));
        Vector2 vector = Collision.StickyTiles(position, velocity, width, height);
        if (vector.Y != -1f && vector.X != -1f)
        {
            int num4 = (int)vector.X;
            int num5 = (int)vector.Y;
            int type = Main.tile[num4, num5].type;
            if (whoAmI == Main.myPlayer && type == 51 && (velocity.X != 0f || velocity.Y != 0f))
            {
                stickyBreak++;
                if (stickyBreak > Main.rand.Next(20, 100) || flag)
                {
                    stickyBreak = 0;
                    WorldGen.KillTile(num4, num5);
                    if (Main.netMode == 1 && !Main.tile[num4, num5].active() && Main.netMode == 1)
                    {
                        NetMessage.SendData(17, -1, -1, null, 0, num4, num5);
                    }
                }
            }
            if (flag)
            {
                return;
            }
            fallStart = (int)(position.Y / 16f);
            if (type != 229)
            {
                jump = 0;
            }
            if (velocity.X > 1f)
            {
                velocity.X = 1f;
            }
            if (velocity.X < -1f)
            {
                velocity.X = -1f;
            }
            if ((double)velocity.X > 0.75 || (double)velocity.X < -0.75)
            {
                velocity.X *= 0.85f;
            }
            else
            {
                velocity.X *= 0.6f;
            }
            if (gravDir == -1f)
            {
                if (velocity.Y < -1f)
                {
                    velocity.Y = -1f;
                }
                if (velocity.Y > 5f)
                {
                    velocity.Y = 5f;
                }
                if (velocity.Y > 0f)
                {
                    velocity.Y *= 0.96f;
                }
                else
                {
                    velocity.Y *= 0.3f;
                }
            }
            else
            {
                if (velocity.Y > 1f)
                {
                    velocity.Y = 1f;
                }
                if (velocity.Y < -5f)
                {
                    velocity.Y = -5f;
                }
                if (velocity.Y < 0f)
                {
                    velocity.Y *= 0.96f;
                }
                else
                {
                    velocity.Y *= 0.3f;
                }
            }
            if (type != 229 || Main.rand.Next(5) != 0 || (!((double)velocity.Y > 0.15) && !(velocity.Y < 0f)))
            {
                return;
            }
            if ((float)(num4 * 16) < position.X + (float)(width / 2))
            {
                int num6 = Dust.NewDust(new Vector2(position.X - 4f, (float)(num5 * 16)), 4, 16, 153, 0f, 0f, 50);
                Main.dust[num6].scale += (float)Main.rand.Next(0, 6) * 0.1f;
                Dust obj = Main.dust[num6];
                obj.velocity *= 0.1f;
                Main.dust[num6].noGravity = true;
            }
            else
            {
                int num7 = Dust.NewDust(new Vector2(position.X + (float)width - 2f, (float)(num5 * 16)), 4, 16, 153, 0f, 0f, 50);
                Main.dust[num7].scale += (float)Main.rand.Next(0, 6) * 0.1f;
                Dust obj2 = Main.dust[num7];
                obj2.velocity *= 0.1f;
                Main.dust[num7].noGravity = true;
            }
            if (Main.tile[num4, num5 + 1] != null && Main.tile[num4, num5 + 1].type == 229 && position.Y + (float)height > (float)((num5 + 1) * 16))
            {
                if ((float)(num4 * 16) < position.X + (float)(width / 2))
                {
                    int num8 = Dust.NewDust(new Vector2(position.X - 4f, (float)(num5 * 16 + 16)), 4, 16, 153, 0f, 0f, 50);
                    Main.dust[num8].scale += (float)Main.rand.Next(0, 6) * 0.1f;
                    Dust obj3 = Main.dust[num8];
                    obj3.velocity *= 0.1f;
                    Main.dust[num8].noGravity = true;
                }
                else
                {
                    int num9 = Dust.NewDust(new Vector2(position.X + (float)width - 2f, (float)(num5 * 16 + 16)), 4, 16, 153, 0f, 0f, 50);
                    Main.dust[num9].scale += (float)Main.rand.Next(0, 6) * 0.1f;
                    Dust obj4 = Main.dust[num9];
                    obj4.velocity *= 0.1f;
                    Main.dust[num9].noGravity = true;
                }
            }
            if (Main.tile[num4, num5 + 2] != null && Main.tile[num4, num5 + 2].type == 229 && position.Y + (float)height > (float)((num5 + 2) * 16))
            {
                if ((float)(num4 * 16) < position.X + (float)(width / 2))
                {
                    int num10 = Dust.NewDust(new Vector2(position.X - 4f, (float)(num5 * 16 + 32)), 4, 16, 153, 0f, 0f, 50);
                    Main.dust[num10].scale += (float)Main.rand.Next(0, 6) * 0.1f;
                    Dust obj5 = Main.dust[num10];
                    obj5.velocity *= 0.1f;
                    Main.dust[num10].noGravity = true;
                }
                else
                {
                    int num2 = Dust.NewDust(new Vector2(position.X + (float)width - 2f, (float)(num5 * 16 + 32)), 4, 16, 153, 0f, 0f, 50);
                    Main.dust[num2].scale += (float)Main.rand.Next(0, 6) * 0.1f;
                    Dust obj6 = Main.dust[num2];
                    obj6.velocity *= 0.1f;
                    Main.dust[num2].noGravity = true;
                }
            }
        }
        else
        {
            stickyBreak = 0;
        }
    }
References Terraria.ID.MountID.Sets.Cart, Terraria.Main.dust, Terraria.Player.fallStart, Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Player.jump, Terraria.WorldGen.KillTile(), Terraria.Player.mount, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Entity.position, Terraria.Main.rand, Terraria.Dust.scale, Terraria.NetMessage.SendData(), Terraria.Player.shimmering, Terraria.Player.stickyBreak, Terraria.Collision.StickyTiles(), Terraria.Main.tile, Terraria.Mount.Type, Terraria.Entity.velocity, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().