TModLoader: Terraria.Player.OnHit_Inner
OnHit_Inner()
void Terraria.Player.OnHit_Inner (float x, float y, Entity victim) inline private
    {
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_024f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0401: Unknown result type (might be due to invalid IL or missing references)
        //IL_0454: Unknown result type (might be due to invalid IL or missing references)
        //IL_0460: Unknown result type (might be due to invalid IL or missing references)
        //IL_0466: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_048b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0493: Unknown result type (might be due to invalid IL or missing references)
        //IL_0498: Unknown result type (might be due to invalid IL or missing references)
        bool flag = victim is NPC && (((NPC)victim).type == 488 || ((NPC)victim).SpawnedFromStatue);
        if (titaniumStormCooldown > 0)
        {
            flag = true;
        }
        if (victim is NPC)
        {
            Main.BigBossProgressBar.TryTracking(victim.whoAmI);
        }
        if (onHitTitaniumStorm && !flag)
        {
            titaniumStormCooldown = 10;
            AddBuff(306, 600);
            if (ownedProjectileCounts[908] < 7)
            {
                ownedProjectileCounts[908]++;
                Projectile.NewProjectile(GetProjectileSource_OnHit(victim, 4), base.Center, Vector2.Zero, 908, 50, 15f, whoAmI);
            }
        }
        if (onHitDodge && shadowDodgeTimer == 0)
        {
            AddBuff(59, 1800);
        }
        if (onHitRegen)
        {
            AddBuff(58, 300);
        }
        if (stardustMinion && victim is NPC)
        {
            for (int i = 0; i < 1000; i++)
            {
                Projectile projectile = Main.projectile[i];
                if (projectile.active && projectile.owner == whoAmI && projectile.type == 613 && !(projectile.localAI[1] > 0f) && Main.rand.Next(2) == 0)
                {
                    Vector2 vector = new Vector2(x, y) - projectile.Center;
                    if (((Vector2)(ref vector)).Length() > 0f)
                    {
                        ((Vector2)(ref vector)).Normalize();
                    }
                    vector *= 20f;
                    Projectile.NewProjectile(Entity.InheritSource(projectile), projectile.Center.X, projectile.Center.Y, vector.X, vector.Y, 614, projectile.damage / 3, 0f, projectile.owner, 0f, victim.whoAmI);
                    projectile.localAI[1] = 30 + Main.rand.Next(4) * 10;
                }
            }
        }
        if (onHitPetal && petalTimer == 0)
        {
            petalTimer = 20;
            _ = position;
            _ = width / 2;
            int num20 = direction;
            float num12 = Main.screenPosition.X;
            if (num20 < 0)
            {
                num12 += (float)Main.screenWidth;
            }
            float y2 = Main.screenPosition.Y;
            y2 += (float)Main.rand.Next(Main.screenHeight);
            Vector2 vector2 = default(Vector2);
            ((Vector2)(ref vector2))._002Ector(num12, y2);
            float num13 = x - vector2.X;
            float num14 = y - vector2.Y;
            num13 += (float)Main.rand.Next(-50, 51) * 0.1f;
            num14 += (float)Main.rand.Next(-50, 51) * 0.1f;
            float num15 = (float)Math.Sqrt(num13 * num13 + num14 * num14);
            num15 = 24f / num15;
            num13 *= num15;
            num14 *= num15;
            Projectile.NewProjectile(GetProjectileSource_OnHit(victim, 5), num12, y2, num13, num14, 221, 36, 0f, whoAmI);
        }
        if (!crystalLeaf || petalTimer != 0)
        {
            return;
        }
        Vector2 vector3 = default(Vector2);
        for (int j = 0; j < 1000; j++)
        {
            if (Main.projectile[j].owner != whoAmI || Main.projectile[j].type != 226)
            {
                continue;
            }
            petalTimer = 50;
            float num16 = 12f;
            ((Vector2)(ref vector3))._002Ector(Main.projectile[j].position.X + (float)width * 0.5f, Main.projectile[j].position.Y + (float)height * 0.5f);
            float num17 = x - vector3.X;
            float num18 = y - vector3.Y;
            float num19 = (float)Math.Sqrt(num17 * num17 + num18 * num18);
            int num10 = 180;
            float num11 = num16 * (float)num10;
            if (!(num19 >= num11))
            {
                num19 = num16 / num19;
                num17 *= num19;
                num18 *= num19;
                Utils.ChaseResults chaseResults = Utils.GetChaseResults(Main.projectile[j].Center, num16 * (float)num10, victim.Center, victim.velocity);
                if (chaseResults.InterceptionHappens && chaseResults.InterceptionTime <= 180f)
                {
                    Vector2 val = chaseResults.ChaserVelocity / (float)num10;
                    num17 = val.X;
                    num18 = val.Y;
                }
                Projectile.NewProjectile(GetProjectileSource_SetBonus(6), Main.projectile[j].Center.X - 4f, Main.projectile[j].Center.Y, num17, num18, 227, crystalLeafDamage, crystalLeafKB, whoAmI);
                break;
            }
        }
    }
References Terraria.Entity.active, Terraria.Player.AddBuff(), Terraria.Main.BigBossProgressBar, Terraria.Entity.Center, Terraria.Player.crystalLeaf, Terraria.Player.crystalLeafDamage, Terraria.Player.crystalLeafKB, Terraria.Entity.direction, Terraria.Utils.GetChaseResults(), Terraria.Player.GetProjectileSource_OnHit(), Terraria.Player.GetProjectileSource_SetBonus(), Terraria.Entity.height, Terraria.Entity.InheritSource(), Terraria.Projectile.localAI, Terraria.Projectile.NewProjectile(), Terraria.Enums.NPC, Terraria.Player.onHitDodge, Terraria.Player.onHitPetal, Terraria.Player.onHitRegen, Terraria.Player.onHitTitaniumStorm, Terraria.Player.ownedProjectileCounts, Terraria.Projectile.owner, Terraria.Player.petalTimer, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Player.shadowDodgeTimer, Terraria.Player.stardustMinion, Terraria.Player.titaniumStormCooldown, Terraria.Projectile.type, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.OnHit().