TModLoader: Terraria.Player.QuickBuff
QuickBuff()
void Terraria.Player.QuickBuff () inline
    {
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        if (cursed || CCed || dead)
        {
            return;
        }
        SoundStyle? legacySoundStyle = null;
        if (CountBuffs() == maxBuffs)
        {
            return;
        }
        Item item = QuickBuff_PickBestFoodItem();
        if (item != null && ItemCheck_CheckCanUse(item))
        {
            legacySoundStyle = item.UseSound;
            int num = item.buffTime;
            if (num == 0)
            {
                num = 3600;
            }
            ItemLoader.UseItem(item, this);
            AddBuff(item.buffType, num);
            if (item.consumable && ItemLoader.ConsumeItem(item, this))
            {
                item.stack--;
                if (item.stack <= 0)
                {
                    item.TurnToAir();
                }
            }
        }
        if (CountBuffs() != maxBuffs)
        {
            int num2 = 58;
            if (useVoidBag())
            {
                num2 = 98;
            }
            for (int i = 0; i < num2; i++)
            {
                Item item2 = ((i >= 58) ? bank4.item[i - 58] : inventory[i]);
                if (item2.stack <= 0 || item2.type <= 0 || item2.buffType <= 0 || item2.summon || !ItemCheck_CheckCanUse(item2))
                {
                    continue;
                }
                int num3 = item2.buffType;
                bool flag = CombinedHooks.CanUseItem(this, item2) && QuickBuff_ShouldBotherUsingThisBuff(num3);
                if (item2.mana > 0 && flag)
                {
                    if (CheckMana(item2, -1, pay: true, blockQuickMana: true))
                    {
                        manaRegenDelay = (int)maxRegenDelay;
                    }
                    else
                    {
                        flag = false;
                    }
                }
                if (whoAmI == Main.myPlayer && item2.type == 603 && !Main.runningCollectorsEdition)
                {
                    flag = false;
                }
                if (num3 == 27)
                {
                    num3 = Main.rand.Next(3);
                    if (num3 == 0)
                    {
                        num3 = 27;
                    }
                    if (num3 == 1)
                    {
                        num3 = 101;
                    }
                    if (num3 == 2)
                    {
                        num3 = 102;
                    }
                }
                if (!flag)
                {
                    continue;
                }
                ItemLoader.UseItem(item2, this);
                legacySoundStyle = item2.UseSound;
                int num4 = item2.buffTime;
                if (num4 == 0)
                {
                    num4 = 3600;
                }
                AddBuff(num3, num4);
                if (item2.consumable && ItemLoader.ConsumeItem(item2, this))
                {
                    item2.stack--;
                    if (item2.stack <= 0)
                    {
                        item2.TurnToAir();
                    }
                }
                if (CountBuffs() == maxBuffs)
                {
                    break;
                }
            }
        }
        if (legacySoundStyle.HasValue)
        {
            SoundEngine.PlaySound(legacySoundStyle, position);
            Recipe.FindRecipes();
        }
    }
References Terraria.Player.AddBuff(), Terraria.Player.bank4, Terraria.Item.buffTime, Terraria.Item.buffType, Terraria.ModLoader.CombinedHooks.CanUseItem(), Terraria.Player.CCed, Terraria.Player.CheckMana(), Terraria.Item.consumable, Terraria.ModLoader.ItemLoader.ConsumeItem(), Terraria.Player.CountBuffs(), Terraria.Player.cursed, Terraria.Player.dead, Terraria.Recipe.FindRecipes(), Terraria.Player.inventory, Terraria.Chest.item, Terraria.Player.ItemCheck_CheckCanUse(), Terraria.Player.manaRegenDelay, Terraria.Player.maxBuffs, Terraria.Player.maxRegenDelay, Terraria.Main.myPlayer, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Player.QuickBuff_PickBestFoodItem(), Terraria.Player.QuickBuff_ShouldBotherUsingThisBuff(), Terraria.Main.rand, Terraria.Main.runningCollectorsEdition, Terraria.Item.stack, Terraria.Item.TurnToAir(), Terraria.ModLoader.ItemLoader.UseItem(), Terraria.Item.UseSound, Terraria.Player.useVoidBag(), and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.Update().