TModLoader: Terraria.Player.TryToPoop
TryToPoop()
void Terraria.Player.TryToPoop () inline private
Definition at line 17248 of file Player.cs.
    {
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        if (whoAmI != Main.myPlayer || !wellFed)
        {
            return;
        }
        int maxValue = 600;
        if (Main.rand.Next(maxValue) != 0)
        {
            return;
        }
        int num = 3;
        int num2 = FindBuffIndex(207);
        if (num2 == -1)
        {
            num = 2;
            num2 = FindBuffIndex(206);
        }
        if (num2 == -1)
        {
            num = 1;
            num2 = FindBuffIndex(26);
        }
        if (num2 != -1)
        {
            int num4 = buffTime[num2];
            DelBuff(num2);
            int stack = Utils.Clamp(num4 / 3600 * num, num, 999);
            Vector2 mountedCenter = MountedCenter;
            ParticleOrchestrator.RequestParticleSpawn(clientOnly: false, ParticleOrchestraType.Digestion, new ParticleOrchestraSettings
            {
                PositionInWorld = mountedCenter,
                MovementVector = new Vector2((float)(-direction), 0f)
            }, whoAmI);
            int num3 = Item.NewItem(GetItemSource_Misc(9), mountedCenter, Vector2.Zero, 5395, stack, noBroadcast: false, 0, noGrabDelay: true);
            if (Main.netMode == 0)
            {
                Main.item[num3].noGrabDelay = 100;
            }
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, num3);
            }
        }
    }
References Terraria.Player.buffTime, Terraria.Player.DelBuff(), Terraria.Entity.direction, Terraria.Player.FindBuffIndex(), Terraria.Player.GetItemSource_Misc(), Terraria.Main.item, Terraria.Player.MountedCenter, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.NetMessage.SendData(), Terraria.Player.wellFed, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.UpdateLifeRegen().