TModLoader: Terraria.Player.ApplyEquipFunctional
ApplyEquipFunctional()
void Terraria.Player.ApplyEquipFunctional (Item currentItem, bool hideVisual) inline
    {
        //IL_04a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0503: Unknown result type (might be due to invalid IL or missing references)
        //IL_0509: Unknown result type (might be due to invalid IL or missing references)
        //IL_149e: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_1530: Unknown result type (might be due to invalid IL or missing references)
        //IL_153f: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_15df: Unknown result type (might be due to invalid IL or missing references)
        //IL_156a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1579: Unknown result type (might be due to invalid IL or missing references)
        //IL_160a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1619: Unknown result type (might be due to invalid IL or missing references)
        //IL_20a6: Unknown result type (might be due to invalid IL or missing references)
        int itemSlot = 0;
        bool[] hideVisibleAccessory = new bool[1] { hideVisual };
        if ((currentItem.expertOnly && !Main.expertMode) || (currentItem.masterOnly && !Main.masterMode))
        {
            return;
        }
        if (currentItem.type == 3810 || currentItem.type == 3809 || currentItem.type == 3812 || currentItem.type == 3811)
        {
            dd2Accessory = true;
        }
        if (!hideVisibleAccessory[itemSlot])
        {
            UpdateBootVisualEffects(currentItem);
            UpdateFishingBobber(currentItem);
        }
        switch (currentItem.type)
        {
        case 4056:
            chiselSpeed = true;
            break;
        case 3990:
            accRunSpeed = 6f;
            autoJump = true;
            jumpSpeedBoost += 1.6f;
            extraFall += 10;
            break;
        case 3991:
            manaFlower = true;
            manaCost -= 0.08f;
            aggro -= 400;
            break;
        case 3992:
            kbGlove = true;
            autoReuseGlove = true;
            meleeScaleGlove = true;
            meleeSpeed += 0.12f;
            aggro += 400;
            break;
        case 3993:
            accRunSpeed = 6f;
            rocketBoots = (vanityRocketBoots = 2);
            break;
        case 4055:
            accRunSpeed = 6f;
            desertBoots = true;
            break;
        case 3994:
            autoJump = true;
            jumpSpeedBoost += 1.6f;
            extraFall += 10;
            accFlipper = true;
            break;
        case 3995:
            autoJump = true;
            jumpSpeedBoost += 1.6f;
            extraFall += 10;
            accFlipper = true;
            spikedBoots += 2;
            break;
        case 3996:
            autoJump = true;
            jumpSpeedBoost += 1.6f;
            extraFall += 10;
            spikedBoots += 2;
            break;
        case 3998:
            aggro += 400;
            break;
        case 4038:
            fireWalk = true;
            break;
        case 4003:
            fireWalk = true;
            lavaRose = true;
            break;
        case 4000:
            manaFlower = true;
            manaCost -= 0.08f;
            manaMagnet = true;
            break;
        case 4001:
            manaFlower = true;
            manaCost -= 0.08f;
            starCloakItem = currentItem;
            starCloakItem_manaCloakOverrideItem = currentItem;
            break;
        case 4002:
            magicQuiver = true;
            arrowDamageAdditiveStack += 0.1f;
            hasMoltenQuiver = true;
            break;
        case 4004:
            fireWalk = true;
            lavaRose = true;
            break;
        case 3999:
            fireWalk = true;
            break;
        case 4005:
            rangedCrit += 10f;
            rangedDamage += 0.1f;
            aggro -= 400;
            break;
        case 4006:
            aggro -= 400;
            magicQuiver = true;
            arrowDamageAdditiveStack += 0.1f;
            break;
        case 4007:
            honeyCombItem = currentItem;
            armorPenetration += 5f;
            break;
        case 4341:
        case 5126:
            portableStoolInfo.SetStats(26, 26, 26);
            break;
        case 4409:
            CanSeeInvisibleBlocks = true;
            break;
        case 5010:
            treasureMagnet = true;
            break;
        case 3245:
            boneGloveItem = currentItem;
            break;
        case 5107:
            hasMagiluminescence = true;
            MountedCenter.ToTileCoordinates();
            DelegateMethods.v3_1 = new Vector3(0.9f, 0.8f, 0.5f);
            Utils.PlotTileLine(base.Center, base.Center + velocity * 6f, 20f, DelegateMethods.CastLightOpen);
            Utils.PlotTileLine(base.Left, base.Right, 20f, DelegateMethods.CastLightOpen);
            break;
        }
        if (currentItem.type == 3015)
        {
            aggro -= 400;
            allDamage += 0.05f;
            allCrit += 5f;
        }
        if (currentItem.type == 3016)
        {
            aggro += 400;
        }
        if (currentItem.type == 2373)
        {
            accFishingLine = true;
        }
        if (currentItem.type == 2374)
        {
            fishingSkill += 10;
        }
        if (currentItem.type == 5139 || currentItem.type == 5144 || currentItem.type == 5142 || currentItem.type == 5141 || currentItem.type == 5146 || currentItem.type == 5140 || currentItem.type == 5145 || currentItem.type == 5143)
        {
            accFishingBobber = true;
        }
        if (currentItem.type == 2375)
        {
            accTackleBox = true;
        }
        if (currentItem.type == 4881)
        {
            accLavaFishing = true;
        }
        if (currentItem.type == 3721)
        {
            accFishingLine = true;
            accTackleBox = true;
            fishingSkill += 10;
        }
        if (currentItem.type == 5064)
        {
            accFishingLine = true;
            accTackleBox = true;
            fishingSkill += 10;
            accLavaFishing = true;
        }
        if (currentItem.type == 3090)
        {
            npcTypeNoAggro[1] = true;
            npcTypeNoAggro[16] = true;
            npcTypeNoAggro[59] = true;
            npcTypeNoAggro[71] = true;
            npcTypeNoAggro[81] = true;
            npcTypeNoAggro[138] = true;
            npcTypeNoAggro[121] = true;
            npcTypeNoAggro[122] = true;
            npcTypeNoAggro[141] = true;
            npcTypeNoAggro[147] = true;
            npcTypeNoAggro[183] = true;
            npcTypeNoAggro[184] = true;
            npcTypeNoAggro[204] = true;
            npcTypeNoAggro[225] = true;
            npcTypeNoAggro[244] = true;
            npcTypeNoAggro[302] = true;
            npcTypeNoAggro[333] = true;
            npcTypeNoAggro[335] = true;
            npcTypeNoAggro[334] = true;
            npcTypeNoAggro[336] = true;
            npcTypeNoAggro[537] = true;
            npcTypeNoAggro[676] = true;
            npcTypeNoAggro[667] = true;
        }
        if (currentItem.stringColor > 0)
        {
            yoyoString = true;
        }
        if (currentItem.type == 3366)
        {
            counterWeight = 556 + Main.rand.Next(6);
            yoyoGlove = true;
            yoyoString = true;
        }
        if (currentItem.type >= 3309 && currentItem.type <= 3314)
        {
            counterWeight = 556 + currentItem.type - 3309;
        }
        if (currentItem.type == 3334)
        {
            yoyoGlove = true;
        }
        if (currentItem.type == 3337)
        {
            shinyStone = true;
        }
        if (currentItem.type == 4989)
        {
            empressBrooch = true;
            moveSpeed += 0.075f;
        }
        if (currentItem.type == 3336)
        {
            SporeSac(currentItem);
            sporeSac = true;
        }
        if (currentItem.type == 4987)
        {
            VolatileGelatin(currentItem);
            volatileGelatin = true;
        }
        switch (currentItem.type)
        {
        case 3538:
            stardustMonolithShader = true;
            break;
        case 3537:
            nebulaMonolithShader = true;
            break;
        case 3536:
            vortexMonolithShader = true;
            break;
        case 3539:
            solarMonolithShader = true;
            break;
        case 4318:
            moonLordMonolithShader = true;
            break;
        case 4054:
            bloodMoonMonolithShader = true;
            break;
        case 5345:
            CanSeeInvisibleBlocks = true;
            break;
        case 5347:
            shimmerMonolithShader = true;
            break;
        }
        if (currentItem.type == 5113)
        {
            dontStarveShader = !dontStarveShader;
        }
        if (currentItem.type == 2423)
        {
            autoJump = true;
            jumpSpeedBoost += 1.6f;
            extraFall += 10;
        }
        if (currentItem.type == 857)
        {
            hasJumpOption_Sandstorm = true;
        }
        if (currentItem.type == 983)
        {
            hasJumpOption_Sandstorm = true;
            jumpBoost = true;
        }
        if (currentItem.type == 987)
        {
            hasJumpOption_Blizzard = true;
        }
        if (currentItem.type == 1163)
        {
            hasJumpOption_Blizzard = true;
            jumpBoost = true;
        }
        if (currentItem.type == 1724)
        {
            hasJumpOption_Fart = true;
        }
        if (currentItem.type == 1863)
        {
            hasJumpOption_Fart = true;
            jumpBoost = true;
        }
        if (currentItem.type == 1164)
        {
            hasJumpOption_Cloud = true;
            hasJumpOption_Sandstorm = true;
            hasJumpOption_Blizzard = true;
            jumpBoost = true;
        }
        if (currentItem.type == 5331)
        {
            hasJumpOption_Cloud = true;
            hasJumpOption_Sandstorm = true;
            hasJumpOption_Blizzard = true;
            jumpBoost = true;
            noFallDmg = true;
            hasLuck_LuckyHorseshoe = true;
        }
        if (currentItem.type == 1250)
        {
            jumpBoost = true;
            hasJumpOption_Cloud = true;
            noFallDmg = true;
            hasLuck_LuckyHorseshoe = true;
        }
        if (currentItem.type == 1252)
        {
            hasJumpOption_Sandstorm = true;
            jumpBoost = true;
            noFallDmg = true;
            hasLuck_LuckyHorseshoe = true;
        }
        if (currentItem.type == 1251)
        {
            hasJumpOption_Blizzard = true;
            jumpBoost = true;
            noFallDmg = true;
            hasLuck_LuckyHorseshoe = true;
        }
        if (currentItem.type == 3250)
        {
            hasJumpOption_Fart = true;
            jumpBoost = true;
            noFallDmg = true;
            hasLuck_LuckyHorseshoe = true;
        }
        if (currentItem.type == 3252)
        {
            hasJumpOption_Sail = true;
            jumpBoost = true;
            noFallDmg = true;
            hasLuck_LuckyHorseshoe = true;
        }
        if (currentItem.type == 3251)
        {
            jumpBoost = true;
            honeyCombItem = currentItem;
            noFallDmg = true;
            hasLuck_LuckyHorseshoe = true;
        }
        if (currentItem.type == 1249)
        {
            jumpBoost = true;
            honeyCombItem = currentItem;
        }
        if (currentItem.type == 3241)
        {
            jumpBoost = true;
            hasJumpOption_Sail = true;
        }
        if ((currentItem.type == 1253 || currentItem.type == 3997) && (double)statLife <= (double)statLifeMax2 * 0.5)
        {
            AddBuff(62, 5);
        }
        if (currentItem.type == 1290)
        {
            panic = true;
        }
        if ((currentItem.type == 1300 || currentItem.type == 1858 || currentItem.type == 4005) && (inventory[selectedItem].useAmmo == AmmoID.Bullet || inventory[selectedItem].useAmmo == AmmoID.CandyCorn || inventory[selectedItem].useAmmo == AmmoID.Stake || inventory[selectedItem].useAmmo == 23 || inventory[selectedItem].useAmmo == AmmoID.Solution))
        {
            scope = true;
        }
        if (currentItem.type == 1858)
        {
            rangedCrit += 10f;
            rangedDamage += 0.1f;
        }
        if (currentItem.type == 1301)
        {
            allDamage += 0.1f;
            allCrit += 8f;
        }
        if (currentItem.type == 111)
        {
            statManaMax2 += 20;
        }
        if (currentItem.type == 982)
        {
            statManaMax2 += 20;
            manaRegenDelayBonus += 1f;
            manaRegenBonus += 25;
        }
        if (currentItem.type == 1595)
        {
            statManaMax2 += 20;
            magicCuffs = true;
        }
        if (currentItem.type == 2219)
        {
            manaMagnet = true;
        }
        if (currentItem.type == 2220)
        {
            manaMagnet = true;
            magicDamage += 0.15f;
        }
        if (currentItem.type == 2221)
        {
            manaMagnet = true;
            statManaMax2 += 20;
            magicCuffs = true;
        }
        if (whoAmI == Main.myPlayer && currentItem.type == 1923)
        {
            tileRangeX++;
            tileRangeY++;
        }
        if (currentItem.type == 1247)
        {
            starCloakItem = currentItem;
            honeyCombItem = currentItem;
            starCloakItem_beeCloakOverrideItem = currentItem;
        }
        if (currentItem.type == 1248)
        {
            allCrit += 10f;
        }
        if (currentItem.type == 854)
        {
            discountEquipped = true;
        }
        if (currentItem.type == 855)
        {
            hasLuckyCoin = true;
            hasLuck_LuckyCoin = true;
        }
        if (currentItem.type == 3033)
        {
            goldRing = true;
        }
        if (currentItem.type == 3034)
        {
            goldRing = true;
            hasLuckyCoin = true;
            hasLuck_LuckyCoin = true;
        }
        if (currentItem.type == 3035)
        {
            goldRing = true;
            hasLuckyCoin = true;
            hasLuck_LuckyCoin = true;
            discountEquipped = true;
        }
        if (currentItem.type == 53)
        {
            hasJumpOption_Cloud = true;
        }
        if (currentItem.type == 3201)
        {
            hasJumpOption_Sail = true;
        }
        if (currentItem.type == 54)
        {
            accRunSpeed = 6f;
        }
        if (currentItem.type == 3068)
        {
            cordage = true;
        }
        if (currentItem.type == 1579)
        {
            accRunSpeed = 6f;
        }
        if (currentItem.type == 3200)
        {
            accRunSpeed = 6f;
        }
        if (currentItem.type == 128)
        {
            rocketBoots = (vanityRocketBoots = 1);
        }
        if (currentItem.type == 156)
        {
            noKnockback = true;
        }
        if (currentItem.type == 158)
        {
            noFallDmg = true;
            hasLuck_LuckyHorseshoe = true;
        }
        if (currentItem.type == 934)
        {
            carpet = true;
        }
        if (currentItem.type == 953)
        {
            spikedBoots++;
        }
        if (currentItem.type == 975)
        {
            spikedBoots++;
        }
        if (currentItem.type == 976)
        {
            spikedBoots += 2;
        }
        if (currentItem.type == 977)
        {
            dashType = 1;
        }
        if (currentItem.type == 3097)
        {
            dashType = 2;
        }
        if (currentItem.type == 963)
        {
            blackBelt = true;
        }
        if (currentItem.type == 984)
        {
            blackBelt = true;
            dashType = 1;
            spikedBoots = 2;
        }
        if (currentItem.type == 1131)
        {
            gravControl2 = true;
        }
        if (currentItem.type == 1132)
        {
            honeyCombItem = currentItem;
        }
        if (currentItem.type == 1578)
        {
            honeyCombItem = currentItem;
            panic = true;
        }
        if (currentItem.type == 3224)
        {
            endurance += 0.17f;
        }
        if (currentItem.type == 3223)
        {
            brainOfConfusionItem = currentItem;
        }
        if (currentItem.type == 950)
        {
            iceSkate = true;
        }
        if (currentItem.type == 159)
        {
            jumpBoost = true;
        }
        if (currentItem.type == 3225)
        {
            jumpBoost = true;
        }
        if (currentItem.type == 187)
        {
            accFlipper = true;
        }
        if (currentItem.type == 211)
        {
            autoReuseGlove = true;
            meleeSpeed += 0.12f;
        }
        if (currentItem.type == 223)
        {
            manaCost -= 0.06f;
        }
        if (currentItem.type == 285)
        {
            moveSpeed += 0.05f;
        }
        if (currentItem.type == 212)
        {
            moveSpeed += 0.1f;
        }
        if (currentItem.type == 267)
        {
            killGuide = true;
        }
        if (currentItem.type == 1307)
        {
            killClothier = true;
        }
        if (currentItem.type == 193)
        {
            fireWalk = true;
        }
        if (currentItem.type == 861)
        {
            accMerman = true;
            wolfAcc = true;
            if (hideVisibleAccessory[itemSlot])
            {
                hideMerman = true;
                hideWolf = true;
            }
        }
        if (currentItem.type == 862)
        {
            starCloakItem = currentItem;
            longInvince = true;
            starCloakItem_starVeilOverrideItem = currentItem;
        }
        if (currentItem.type == 860)
        {
            pStone = true;
        }
        if (currentItem.type == 863)
        {
            waterWalk2 = true;
        }
        if (currentItem.type == 907)
        {
            waterWalk2 = true;
            fireWalk = true;
        }
        if (currentItem.type == 5044)
        {
            hasCreditsSceneMusicBox = true;
        }
        if (currentItem.type == 908 || currentItem.type == 5000)
        {
            waterWalk = true;
            fireWalk = true;
            lavaMax += 420;
            lavaRose = true;
        }
        if ((!mount.Active || mount.Type != 47) && !hideVisibleAccessory[itemSlot] && (currentItem.type == 4822 || currentItem.type == 4874))
        {
            DoBootsEffect(DoBootsEffect_PlaceFlamesOnTile);
        }
        if (currentItem.type == 906 || currentItem.type == 4038 || currentItem.type == 3999 || currentItem.type == 4003)
        {
            lavaMax += 420;
        }
        if (currentItem.type == 485)
        {
            wolfAcc = true;
            if (hideVisibleAccessory[itemSlot])
            {
                hideWolf = true;
            }
        }
        if (currentItem.type == 486)
        {
            rulerLine = true;
        }
        if (currentItem.type == 2799)
        {
            rulerGrid = true;
        }
        if (currentItem.type == 394)
        {
            accFlipper = true;
            accDivingHelm = true;
        }
        if (currentItem.type == 396)
        {
            noFallDmg = true;
            fireWalk = true;
            hasLuck_LuckyHorseshoe = true;
        }
        if (currentItem.type == 397)
        {
            noKnockback = true;
            fireWalk = true;
        }
        if (currentItem.type == 399)
        {
            jumpBoost = true;
            hasJumpOption_Cloud = true;
        }
        if (currentItem.type == 405)
        {
            accRunSpeed = 6f;
            rocketBoots = (vanityRocketBoots = 2);
        }
        if (currentItem.type == 1303)
        {
            if (!wet)
            {
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.225f, 0.05f, 0.15f);
            }
            if (wet)
            {
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 1.8f, 0.4f, 1.2f);
            }
        }
        if (currentItem.type == 1860)
        {
            accFlipper = true;
            accDivingHelm = true;
            if (!wet)
            {
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.225f, 0.05f, 0.15f);
            }
            if (wet)
            {
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 1.8f, 0.4f, 1.2f);
            }
        }
        if (currentItem.type == 1861)
        {
            arcticDivingGear = true;
            accFlipper = true;
            accDivingHelm = true;
            iceSkate = true;
            if (!wet)
            {
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.05f, 0.15f, 0.225f);
            }
            if (wet)
            {
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.4f, 1.2f, 1.8f);
            }
        }
        if (currentItem.type == 2214)
        {
            equippedAnyTileSpeedAcc = true;
        }
        if (currentItem.type == 2215)
        {
            equippedAnyTileRangeAcc = true;
        }
        if (currentItem.type == 2216)
        {
            autoPaint = true;
        }
        if (currentItem.type == 2217)
        {
            equippedAnyWallSpeedAcc = true;
        }
        if (currentItem.type == 3061)
        {
            equippedAnyWallSpeedAcc = true;
            equippedAnyTileSpeedAcc = true;
            autoPaint = true;
            equippedAnyTileRangeAcc = true;
        }
        if (currentItem.type == 5126)
        {
            equippedAnyWallSpeedAcc = true;
            equippedAnyTileSpeedAcc = true;
            autoPaint = true;
            equippedAnyTileRangeAcc = true;
            treasureMagnet = true;
            chiselSpeed = true;
        }
        if (currentItem.type == 3624)
        {
            autoActuator = true;
        }
        if (currentItem.type == 897)
        {
            kbGlove = true;
            autoReuseGlove = true;
            meleeScaleGlove = true;
            meleeSpeed += 0.12f;
        }
        if (currentItem.type == 1343)
        {
            kbGlove = true;
            autoReuseGlove = true;
            meleeScaleGlove = true;
            meleeSpeed += 0.12f;
            meleeDamage += 0.12f;
            magmaStone = true;
        }
        if (currentItem.type == 1167)
        {
            minionKB += 2f;
            minionDamage += 0.15f;
        }
        if (currentItem.type == 1864)
        {
            minionKB += 2f;
            minionDamage += 0.15f;
            maxMinions++;
        }
        if (currentItem.type == 1845)
        {
            minionDamage += 0.1f;
            maxMinions++;
        }
        if (currentItem.type == 1321)
        {
            magicQuiver = true;
            arrowDamageAdditiveStack += 0.1f;
        }
        if (currentItem.type == 1322)
        {
            magmaStone = true;
        }
        if (currentItem.type == 1323)
        {
            lavaRose = true;
        }
        if (currentItem.type == 3333)
        {
            strongBees = true;
        }
        if (currentItem.type == 938 || currentItem.type == 3997 || currentItem.type == 3998)
        {
            noKnockback = true;
            if ((float)statLife > (float)statLifeMax2 * 0.25f)
            {
                hasPaladinShield = true;
                if (whoAmI != Main.myPlayer && miscCounter % 10 == 0)
                {
                    int myPlayer = Main.myPlayer;
                    if (Main.player[myPlayer].team == team && team != 0)
                    {
                        float num4 = position.X - Main.player[myPlayer].position.X;
                        float num2 = position.Y - Main.player[myPlayer].position.Y;
                        if ((float)Math.Sqrt(num4 * num4 + num2 * num2) < 800f)
{
                            Main.player[myPlayer].AddBuff(43, 20);
                        }
                    }
                }
            }
        }
        if (currentItem.type == 936)
        {
            kbGlove = true;
            autoReuseGlove = true;
            meleeScaleGlove = true;
            meleeSpeed += 0.12f;
            meleeDamage += 0.12f;
        }
        if (currentItem.type == 898)
        {
            accRunSpeed = 6.75f;
            rocketBoots = (vanityRocketBoots = 2);
            moveSpeed += 0.08f;
        }
        if (currentItem.type == 1862)
        {
            accRunSpeed = 6.75f;
            rocketBoots = (vanityRocketBoots = 3);
            moveSpeed += 0.08f;
            iceSkate = true;
        }
        if (currentItem.type == 5000)
        {
            accRunSpeed = 6.75f;
            rocketBoots = (vanityRocketBoots = 4);
            moveSpeed += 0.08f;
            iceSkate = true;
        }
        if (currentItem.type == 4874)
        {
            accRunSpeed = 6f;
            rocketBoots = (vanityRocketBoots = 5);
        }
        if (currentItem.type == 3110)
        {
            accMerman = true;
            wolfAcc = true;
            if (hideVisibleAccessory[itemSlot])
            {
                hideMerman = true;
                hideWolf = true;
            }
        }
        if (currentItem.type == 1865 || currentItem.type == 3110)
        {
            skyStoneEffects = true;
        }
        if (currentItem.type == 899 && Main.dayTime)
        {
            skyStoneEffects = true;
        }
        if (currentItem.type == 900 && (!Main.dayTime || Main.eclipse))
        {
            skyStoneEffects = true;
        }
        if (currentItem.type == 407)
        {
            blockRange++;
        }
        if (currentItem.type == 489)
        {
            magicDamage += 0.15f;
        }
        if (currentItem.type == 490)
        {
            meleeDamage += 0.15f;
        }
        if (currentItem.type == 491)
        {
            rangedDamage += 0.15f;
        }
        if (currentItem.type == 2998)
        {
            minionDamage += 0.15f;
        }
        if (currentItem.type == 935)
        {
            allDamage += 0.12f;
        }
        if (currentItem.wingSlot != -1)
        {
            wingTimeMax = GetWingStats(currentItem.wingSlot).FlyTime;
        }
        if (currentItem.wingSlot == 26)
        {
            ignoreWater = true;
        }
        if (currentItem.type == 5452)
        {
            remoteVisionForDrone = true;
        }
        if (currentItem.type == 885)
        {
            buffImmune[30] = true;
        }
        if (currentItem.type == 886)
        {
            buffImmune[36] = true;
        }
        if (currentItem.type == 887)
        {
            buffImmune[20] = true;
        }
        if (currentItem.type == 888)
        {
            buffImmune[22] = true;
        }
        if (currentItem.type == 889)
        {
            buffImmune[32] = true;
        }
        if (currentItem.type == 890)
        {
            buffImmune[35] = true;
        }
        if (currentItem.type == 891)
        {
            buffImmune[23] = true;
        }
        if (currentItem.type == 892)
        {
            buffImmune[33] = true;
        }
        if (currentItem.type == 893)
        {
            buffImmune[31] = true;
        }
        if (currentItem.type == 3781)
        {
            buffImmune[156] = true;
        }
        if (currentItem.type == 901)
        {
            buffImmune[33] = true;
            buffImmune[36] = true;
        }
        if (currentItem.type == 902)
        {
            buffImmune[30] = true;
            buffImmune[20] = true;
        }
        if (currentItem.type == 903)
        {
            buffImmune[32] = true;
            buffImmune[31] = true;
        }
        if (currentItem.type == 904)
        {
            buffImmune[35] = true;
            buffImmune[23] = true;
        }
        if (currentItem.type == 5354)
        {
            buffImmune[22] = true;
            buffImmune[156] = true;
        }
        if (currentItem.type == 5355 && !controlDownHold)
        {
            shimmerImmune = true;
        }
        if (currentItem.type == 1921)
        {
            buffImmune[46] = true;
            buffImmune[47] = true;
        }
        if (currentItem.type == 1612)
        {
            buffImmune[33] = true;
            buffImmune[36] = true;
            buffImmune[30] = true;
            buffImmune[20] = true;
            buffImmune[32] = true;
            buffImmune[31] = true;
            buffImmune[35] = true;
            buffImmune[23] = true;
            buffImmune[22] = true;
            buffImmune[156] = true;
        }
        if (currentItem.type == 1613)
        {
            buffImmune[46] = true;
            noKnockback = true;
            fireWalk = true;
            buffImmune[33] = true;
            buffImmune[36] = true;
            buffImmune[30] = true;
            buffImmune[20] = true;
            buffImmune[32] = true;
            buffImmune[31] = true;
            buffImmune[35] = true;
            buffImmune[23] = true;
            buffImmune[22] = true;
            buffImmune[156] = true;
        }
        if (currentItem.type == 497)
        {
            accMerman = true;
            if (hideVisibleAccessory[itemSlot])
            {
                hideMerman = true;
            }
        }
        if (currentItem.type == 535)
        {
            pStone = true;
        }
        if (currentItem.type == 536)
        {
            kbGlove = true;
            meleeScaleGlove = true;
        }
        if (currentItem.type == 532)
        {
            starCloakItem = currentItem;
        }
        if (currentItem.type == 554)
        {
            longInvince = true;
        }
        if (currentItem.type == 555)
        {
            manaFlower = true;
            manaCost -= 0.08f;
        }
        if (currentItem.wingSlot > 0)
        {
            if (!hideVisibleAccessory[itemSlot] || (velocity.Y != 0f && !mount.Active))
            {
                wings = currentItem.wingSlot;
            }
            wingsLogic = currentItem.wingSlot;
            equippedWings = currentItem;
        }
        ItemLoader.UpdateAccessory(currentItem, this, hideVisual);
        if (Main.myPlayer != whoAmI)
        {
            return;
        }
        if (currentItem.type == 5104 || currentItem.type == 5105)
        {
            ApplyWilsonBeard(currentItem);
        }
        else if (currentItem.type == 576 && Main.rand.Next(540) == 0 && Main.curMusic > 0)
        {
            SoundEngine.PlaySound(in SoundID.Item166, base.Center);
            int num3 = -1;
            if (Main.curMusic == 1)
            {
                num3 = 0;
            }
            if (Main.curMusic == 2)
            {
                num3 = 1;
            }
            if (Main.curMusic == 3)
            {
                num3 = 2;
            }
            if (Main.curMusic == 4)
            {
                num3 = 4;
            }
            if (Main.curMusic == 5)
            {
                num3 = 5;
            }
            if (Main.curMusic == 6)
            {
                num3 = 3;
            }
            if (Main.curMusic == 7)
            {
                num3 = 6;
            }
            if (Main.curMusic == 8)
            {
                num3 = 7;
            }
            if (Main.curMusic == 9)
            {
                num3 = 9;
            }
            if (Main.curMusic == 10)
            {
                num3 = 8;
            }
            if (Main.curMusic == 11)
            {
                num3 = 11;
            }
            if (Main.curMusic == 12)
            {
                num3 = 10;
            }
            if (Main.curMusic == 13)
            {
                num3 = 12;
            }
            int modMusicBoxType;
            if (Main.curMusic == 28)
            {
                currentItem.SetDefaults(1963);
            }
            else if (Main.curMusic == 29)
            {
                currentItem.SetDefaults(1610);
            }
            else if (Main.curMusic == 30)
            {
                currentItem.SetDefaults(1963);
            }
            else if (Main.curMusic == 31)
            {
                currentItem.SetDefaults(1964);
            }
            else if (Main.curMusic == 32)
            {
                currentItem.SetDefaults(1965);
            }
            else if (Main.curMusic == 33)
            {
                currentItem.SetDefaults(2742);
            }
            else if (Main.curMusic == 34)
            {
                currentItem.SetDefaults(3370);
            }
            else if (Main.curMusic == 35)
            {
                currentItem.SetDefaults(3236);
            }
            else if (Main.curMusic == 36)
            {
                currentItem.SetDefaults(3237);
            }
            else if (Main.curMusic == 37)
            {
                currentItem.SetDefaults(3235);
            }
            else if (Main.curMusic == 38)
            {
                currentItem.SetDefaults(3044);
            }
            else if (Main.curMusic == 39)
            {
                currentItem.SetDefaults(3371);
            }
            else if (Main.curMusic == 40)
            {
                currentItem.SetDefaults(3796);
            }
            else if (Main.curMusic == 41)
            {
                currentItem.SetDefaults(3869);
            }
            else if (Main.curMusic == 42)
            {
                currentItem.SetDefaults(4079);
            }
            else if (Main.curMusic == 43)
            {
                currentItem.SetDefaults(4077);
            }
            else if (Main.curMusic == 44)
            {
                currentItem.SetDefaults(4082);
            }
            else if (Main.curMusic == 46)
            {
                currentItem.SetDefaults(4080);
            }
            else if (Main.curMusic == 47)
            {
                currentItem.SetDefaults(4081);
            }
            else if (Main.curMusic == 48)
            {
                currentItem.SetDefaults(4078);
            }
            else if (Main.curMusic == 49)
            {
                currentItem.SetDefaults(4237);
            }
            else if (Main.curMusic == 51)
            {
                currentItem.SetDefaults(4356);
            }
            else if (Main.curMusic == 52)
            {
                currentItem.SetDefaults(4357);
            }
            else if (Main.curMusic == 53)
            {
                currentItem.SetDefaults(4358);
            }
            else if (Main.curMusic == 54)
            {
                currentItem.SetDefaults(4421);
            }
            else if (Main.curMusic == 55)
            {
                currentItem.SetDefaults(4606);
            }
            else if (Main.curMusic == 56)
            {
                currentItem.SetDefaults(4979);
            }
            else if (Main.curMusic == 57)
            {
                currentItem.SetDefaults(4985);
            }
            else if (Main.curMusic == 58)
            {
                currentItem.SetDefaults(4990);
            }
            else if (Main.curMusic == 59)
            {
                currentItem.SetDefaults(4991);
            }
            else if (Main.curMusic == 60)
            {
                currentItem.SetDefaults(4992);
            }
            else if (Main.curMusic == 61)
            {
                currentItem.SetDefaults(5006);
            }
            else if (Main.curMusic == 62)
            {
                currentItem.SetDefaults(5014);
            }
            else if (Main.curMusic == 63)
            {
                currentItem.SetDefaults(5015);
            }
            else if (Main.curMusic == 64)
            {
                currentItem.SetDefaults(5016);
            }
            else if (Main.curMusic == 65)
            {
                currentItem.SetDefaults(5017);
            }
            else if (Main.curMusic == 66)
            {
                currentItem.SetDefaults(5018);
            }
            else if (Main.curMusic == 67)
            {
                currentItem.SetDefaults(5019);
            }
            else if (Main.curMusic == 68)
            {
                currentItem.SetDefaults(5020);
            }
            else if (Main.curMusic == 69)
            {
                currentItem.SetDefaults(5021);
            }
            else if (Main.curMusic == 70)
            {
                currentItem.SetDefaults(5022);
            }
            else if (Main.curMusic == 71)
            {
                currentItem.SetDefaults(5023);
            }
            else if (Main.curMusic == 72)
            {
                currentItem.SetDefaults(5024);
            }
            else if (Main.curMusic == 73)
            {
                currentItem.SetDefaults(5025);
            }
            else if (Main.curMusic == 74)
            {
                currentItem.SetDefaults(5026);
            }
            else if (Main.curMusic == 75)
            {
                currentItem.SetDefaults(5027);
            }
            else if (Main.curMusic == 76)
            {
                currentItem.SetDefaults(5028);
            }
            else if (Main.curMusic == 77)
            {
                currentItem.SetDefaults(5029);
            }
            else if (Main.curMusic == 78)
            {
                currentItem.SetDefaults(5030);
            }
            else if (Main.curMusic == 79)
            {
                currentItem.SetDefaults(5031);
            }
            else if (Main.curMusic == 80)
            {
                currentItem.SetDefaults(5032);
            }
            else if (Main.curMusic == 81)
            {
                currentItem.SetDefaults(5033);
            }
            else if (Main.curMusic == 82)
            {
                currentItem.SetDefaults(5034);
            }
            else if (Main.curMusic == 83)
            {
                currentItem.SetDefaults(5035);
            }
            else if (Main.curMusic == 84)
            {
                currentItem.SetDefaults(5036);
            }
            else if (Main.curMusic == 85)
            {
                currentItem.SetDefaults(5037);
            }
            else if (Main.curMusic == 86)
            {
                currentItem.SetDefaults(5038);
            }
            else if (Main.curMusic == 87)
            {
                currentItem.SetDefaults(5039);
            }
            else if (Main.curMusic == 88)
            {
                currentItem.SetDefaults(5040);
            }
            else if (Main.curMusic == 89)
            {
                currentItem.SetDefaults(5044);
            }
            else if (Main.curMusic == 90)
            {
                currentItem.SetDefaults(5112);
            }
            else if (Main.curMusic == 91)
            {
                currentItem.SetDefaults(5362);
            }
            else if (Main.curMusic > 13 && Main.curMusic < Main.maxMusic)
            {
                currentItem.SetDefaults(1596 + Main.curMusic - 14);
            }
            else if (num3 != -1 && Main.curMusic < Main.maxMusic)
            {
                currentItem.SetDefaults(num3 + 562);
            }
            else if (MusicLoader.musicToItem.TryGetValue(Main.curMusic, out modMusicBoxType))
            {
                currentItem.SetDefaults(modMusicBoxType);
            }
        }
        ApplyMusicBox(currentItem);
    }
References Terraria.Player.accDivingHelm, Terraria.Player.accFishingBobber, Terraria.Player.accFishingLine, Terraria.Player.accFlipper, Terraria.Player.accLavaFishing, Terraria.Player.accMerman, Terraria.Player.accRunSpeed, Terraria.Player.accTackleBox, Terraria.Mount.Active, Terraria.Player.AddBuff(), Terraria.Lighting.AddLight(), Terraria.Player.aggro, Terraria.Player.allCrit, Terraria.Player.allDamage, Terraria.Player.ApplyMusicBox(), Terraria.Player.ApplyWilsonBeard(), Terraria.Player.arcticDivingGear, Terraria.Player.armorPenetration, Terraria.Player.arrowDamageAdditiveStack, Terraria.Player.autoActuator, Terraria.Player.autoJump, Terraria.Player.autoPaint, Terraria.Player.autoReuseGlove, Terraria.Player.blackBelt, Terraria.Player.blockRange, Terraria.Player.bloodMoonMonolithShader, Terraria.Player.boneGloveItem, Terraria.Player.brainOfConfusionItem, Terraria.Player.buffImmune, Terraria.ID.AmmoID.Bullet, Terraria.ID.AmmoID.CandyCorn, Terraria.Player.CanSeeInvisibleBlocks, Terraria.Player.carpet, Terraria.DelegateMethods.CastLightOpen(), Terraria.Player.chiselSpeed, Terraria.Player.controlDownHold, Terraria.Player.cordage, Terraria.Player.counterWeight, Terraria.Main.curMusic, Terraria.Player.dashType, Terraria.Main.dayTime, Terraria.Player.dd2Accessory, Terraria.Player.desertBoots, Terraria.Player.discountEquipped, Terraria.Player.DoBootsEffect(), Terraria.Player.DoBootsEffect_PlaceFlamesOnTile(), Terraria.Player.dontStarveShader, Terraria.Main.eclipse, Terraria.Player.empressBrooch, Terraria.Player.endurance, Terraria.Player.equippedAnyTileRangeAcc, Terraria.Player.equippedAnyTileSpeedAcc, Terraria.Player.equippedAnyWallSpeedAcc, Terraria.Player.equippedWings, Terraria.Main.expertMode, Terraria.Player.extraFall, Terraria.Player.fireWalk, Terraria.Player.fishingSkill, Terraria.DataStructures.WingStats.FlyTime, Terraria.Player.GetWingStats(), Terraria.Player.goldRing, Terraria.Player.gravControl2, Terraria.Player.hasCreditsSceneMusicBox, Terraria.Player.hasJumpOption_Blizzard, Terraria.Player.hasJumpOption_Cloud, Terraria.Player.hasJumpOption_Fart, Terraria.Player.hasJumpOption_Sail, Terraria.Player.hasJumpOption_Sandstorm, Terraria.Player.hasLuck_LuckyCoin, Terraria.Player.hasLuck_LuckyHorseshoe, Terraria.Player.hasLuckyCoin, Terraria.Player.hasMagiluminescence, Terraria.Player.hasMoltenQuiver, Terraria.Player.hasPaladinShield, Terraria.Player.hideMerman, Terraria.Player.hideVisibleAccessory, Terraria.Player.hideWolf, Terraria.Player.honeyCombItem, Terraria.Player.iceSkate, Terraria.Player.ignoreWater, Terraria.Player.inventory, Terraria.ID.SoundID.Item166, Terraria.Player.jumpBoost, Terraria.Player.jumpSpeedBoost, Terraria.Player.kbGlove, Terraria.Player.killClothier, Terraria.Player.killGuide, Terraria.Player.lavaMax, Terraria.Player.lavaRose, Terraria.Player.longInvince, Terraria.Player.magicCuffs, Terraria.Player.magicDamage, Terraria.Player.magicQuiver, Terraria.Player.magmaStone, Terraria.Player.manaCost, Terraria.Player.manaFlower, Terraria.Player.manaMagnet, Terraria.Player.manaRegenBonus, Terraria.Player.manaRegenDelayBonus, Terraria.Main.masterMode, Terraria.Player.maxMinions, Terraria.Main.maxMusic, Terraria.Player.meleeDamage, Terraria.Player.meleeScaleGlove, Terraria.Player.meleeSpeed, Terraria.Player.minionDamage, Terraria.Player.minionKB, Terraria.Player.miscCounter, Terraria.Player.moonLordMonolithShader, Terraria.Player.mount, Terraria.Player.MountedCenter, Terraria.Player.moveSpeed, Terraria.ModLoader.MusicLoader.musicToItem, Terraria.Main.myPlayer, Terraria.Player.nebulaMonolithShader, Terraria.Player.noFallDmg, Terraria.Player.noKnockback, Terraria.Player.npcTypeNoAggro, Terraria.Player.panic, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Utils.PlotTileLine(), Terraria.Player.portableStoolInfo, Terraria.Player.pStone, Terraria.Main.rand, Terraria.Player.rangedCrit, Terraria.Player.rangedDamage, Terraria.Player.remoteVisionForDrone, Terraria.Player.rocketBoots, Terraria.Player.rulerGrid, Terraria.Player.rulerLine, Terraria.Player.scope, Terraria.Player.selectedItem, Terraria.DataStructures.PortableStoolUsage.SetStats(), Terraria.Player.shimmerImmune, Terraria.Player.shimmerMonolithShader, Terraria.Player.shinyStone, Terraria.Player.skyStoneEffects, Terraria.Player.solarMonolithShader, Terraria.ID.AmmoID.Solution, Terraria.Player.spikedBoots, Terraria.Player.sporeSac, Terraria.Player.SporeSac(), Terraria.ID.AmmoID.Stake, Terraria.Player.starCloakItem, Terraria.Player.starCloakItem_beeCloakOverrideItem, Terraria.Player.starCloakItem_manaCloakOverrideItem, Terraria.Player.starCloakItem_starVeilOverrideItem, Terraria.Player.stardustMonolithShader, Terraria.Player.statLife, Terraria.Player.statLifeMax2, Terraria.Player.statManaMax2, Terraria.Player.strongBees, Terraria.Player.team, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Player.treasureMagnet, Terraria.Mount.Type, Terraria.ModLoader.ItemLoader.UpdateAccessory(), Terraria.Player.UpdateBootVisualEffects(), Terraria.Player.UpdateFishingBobber(), Terraria.Item.useAmmo, Terraria.Player.vanityRocketBoots, Terraria.Entity.velocity, Terraria.Player.volatileGelatin, Terraria.Player.VolatileGelatin(), Terraria.Player.vortexMonolithShader, Terraria.Player.waterWalk, Terraria.Player.waterWalk2, Terraria.Entity.wet, Terraria.Entity.whoAmI, Terraria.Player.wings, Terraria.Player.wingsLogic, Terraria.Player.wingTimeMax, Terraria.Player.wolfAcc, Terraria.Player.yoyoGlove, and Terraria.Player.yoyoString.
Referenced by Terraria.ModLoader.ModAccessorySlot.ApplyEquipEffects(), and Terraria.Player.UpdateEquips().