TModLoader: Terraria.Player.ClearMiningCacheAt
ClearMiningCacheAt()
void Terraria.Player.ClearMiningCacheAt (int x, int y, int hitTileCacheType) inline private
    {
        hitReplace.TryClearingAndPruning(x, y, 1);
        hitTile.TryClearingAndPruning(x, y, 1);
    }
References Terraria.Player.hitReplace, Terraria.Player.hitTile, and Terraria.HitTile.TryClearingAndPruning().
Referenced by Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.Player.PickTile(), Terraria.Player.PickWall(), and Terraria.Player.PlaceThing_TryReplacingTiles().