TModLoader: Terraria.Player.ItemCheck_UseTeleportRod
ItemCheck_UseTeleportRod()
void Terraria.Player.ItemCheck_UseTeleportRod (Item sItem) inline private
    {
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        if (Main.myPlayer != whoAmI || (sItem.type != 1326 && sItem.type != 5335) || itemAnimation <= 0 || !ItemTimeIsZero)
        {
            return;
        }
        ApplyItemTime(sItem);
        Vector2 pointPoisition = default(Vector2);
        pointPoisition.X = (float)Main.mouseX + Main.screenPosition.X;
        if (gravDir == 1f)
        {
            pointPoisition.Y = (float)Main.mouseY + Main.screenPosition.Y - (float)height;
        }
        else
        {
            pointPoisition.Y = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY;
        }
        pointPoisition.X -= width / 2;
        LimitPointToPlayerReachableArea(ref pointPoisition);
        if (!(pointPoisition.X > 50f) || !(pointPoisition.X < (float)(Main.maxTilesX * 16 - 50)) || !(pointPoisition.Y > 50f) || !(pointPoisition.Y < (float)(Main.maxTilesY * 16 - 50)))
        {
            return;
        }
        int num = (int)(pointPoisition.X / 16f);
        int num2 = (int)(pointPoisition.Y / 16f);
        if ((Main.tile[num, num2].wall == 87 && !NPC.downedPlantBoss && (Main.remixWorld || (double)num2 > Main.worldSurface)) || Collision.SolidCollision(pointPoisition, width, height))
        {
            return;
        }
        Teleport(pointPoisition, 1);
        NetMessage.SendData(65, -1, -1, null, 0, whoAmI, pointPoisition.X, pointPoisition.Y, 1);
        if (sItem.type != 1326)
        {
            return;
        }
        if (chaosState)
        {
            statLife -= statLifeMax2 / 7;
            PlayerDeathReason damageSource = PlayerDeathReason.ByOther(13);
            if (Main.rand.Next(2) == 0)
            {
                damageSource = PlayerDeathReason.ByOther(Male ? 14 : 15);
            }
            if (statLife <= 0)
            {
                KillMe(damageSource, 1.0, 0);
            }
            lifeRegenCount = 0;
            lifeRegenTime = 0f;
        }
        AddBuff(88, 360);
    }
References Terraria.Player.AddBuff(), Terraria.Player.ApplyItemTime(), Terraria.DataStructures.PlayerDeathReason.ByOther(), Terraria.Player.chaosState, Terraria.NPC.downedPlantBoss, Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Player.itemAnimation, Terraria.Player.ItemTimeIsZero, Terraria.Player.KillMe(), Terraria.Player.lifeRegenCount, Terraria.Player.lifeRegenTime, Terraria.Player.LimitPointToPlayerReachableArea(), Terraria.Player.Male, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.NetMessage.SendData(), Terraria.Collision.SolidCollision(), Terraria.Player.statLife, Terraria.Player.statLifeMax2, Terraria.Player.Teleport(), Terraria.Main.tile, Terraria.Entity.whoAmI, Terraria.Entity.width, and Terraria.Main.worldSurface.
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode().