TModLoader: Terraria.Player.DashMovement
DashMovement()
void Terraria.Player.DashMovement () inline
Definition at line 19204 of file Player.cs.
    {
        //IL_0cde: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d25: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d42: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d55: Unknown result type (might be due to invalid IL or missing references)
        //IL_0629: Unknown result type (might be due to invalid IL or missing references)
        //IL_0646: Unknown result type (might be due to invalid IL or missing references)
        //IL_064c: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1053: Unknown result type (might be due to invalid IL or missing references)
        //IL_1088: Unknown result type (might be due to invalid IL or missing references)
        //IL_108d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1092: Unknown result type (might be due to invalid IL or missing references)
        //IL_1097: Unknown result type (might be due to invalid IL or missing references)
        //IL_109a: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_10bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d63: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0827: Unknown result type (might be due to invalid IL or missing references)
        //IL_0849: Unknown result type (might be due to invalid IL or missing references)
        //IL_084f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0866: Unknown result type (might be due to invalid IL or missing references)
        //IL_0870: Unknown result type (might be due to invalid IL or missing references)
        //IL_0875: Unknown result type (might be due to invalid IL or missing references)
        //IL_0757: Unknown result type (might be due to invalid IL or missing references)
        //IL_0774: Unknown result type (might be due to invalid IL or missing references)
        //IL_077a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0701: Unknown result type (might be due to invalid IL or missing references)
        //IL_071d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0723: Unknown result type (might be due to invalid IL or missing references)
        //IL_0663: Unknown result type (might be due to invalid IL or missing references)
        //IL_066d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0672: Unknown result type (might be due to invalid IL or missing references)
        //IL_1246: Unknown result type (might be due to invalid IL or missing references)
        //IL_127b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1280: Unknown result type (might be due to invalid IL or missing references)
        //IL_1285: Unknown result type (might be due to invalid IL or missing references)
        //IL_128a: Unknown result type (might be due to invalid IL or missing references)
        //IL_128d: Unknown result type (might be due to invalid IL or missing references)
        //IL_12a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_12aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_12af: Unknown result type (might be due to invalid IL or missing references)
        //IL_12b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_12b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_12bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_10d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_10df: Unknown result type (might be due to invalid IL or missing references)
        //IL_145d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1492: Unknown result type (might be due to invalid IL or missing references)
        //IL_1497: Unknown result type (might be due to invalid IL or missing references)
        //IL_149c: Unknown result type (might be due to invalid IL or missing references)
        //IL_14a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_14a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_14bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_14c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_14c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_14cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_14cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_094e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0974: Unknown result type (might be due to invalid IL or missing references)
        //IL_097a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0991: Unknown result type (might be due to invalid IL or missing references)
        //IL_099b: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0791: Unknown result type (might be due to invalid IL or missing references)
        //IL_079b: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_12cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_12d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e41: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e46: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ebd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f87: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f94: Unknown result type (might be due to invalid IL or missing references)
        //IL_1007: Unknown result type (might be due to invalid IL or missing references)
        //IL_1011: Unknown result type (might be due to invalid IL or missing references)
        //IL_1016: Unknown result type (might be due to invalid IL or missing references)
        //IL_0adc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a86: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0399: Unknown result type (might be due to invalid IL or missing references)
        //IL_039e: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_112e: Unknown result type (might be due to invalid IL or missing references)
        //IL_114f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1155: Unknown result type (might be due to invalid IL or missing references)
        //IL_11b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_11be: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b20: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b25: Unknown result type (might be due to invalid IL or missing references)
        //IL_1319: Unknown result type (might be due to invalid IL or missing references)
        //IL_1339: Unknown result type (might be due to invalid IL or missing references)
        //IL_133f: Unknown result type (might be due to invalid IL or missing references)
        //IL_139e: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_13ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_154d: Unknown result type (might be due to invalid IL or missing references)
        //IL_156e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1574: Unknown result type (might be due to invalid IL or missing references)
        //IL_15db: Unknown result type (might be due to invalid IL or missing references)
        //IL_15e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_15ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_15ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0490: Unknown result type (might be due to invalid IL or missing references)
        //IL_049b: Unknown result type (might be due to invalid IL or missing references)
        if (dashDelay == 0)
        {
            dash = dashType;
        }
        if (dash == 0)
        {
            dashTime = 0;
            dashDelay = 0;
        }
        if (dash == 2 && eocDash > 0)
        {
            if (eocHit < 0)
            {
                Rectangle rectangle = default(Rectangle);
                ((Rectangle)(ref rectangle))._002Ector((int)((double)position.X + (double)velocity.X * 0.5 - 4.0), (int)((double)position.Y + (double)velocity.Y * 0.5 - 4.0), width + 8, height + 8);
                for (int i = 0; i < 200; i++)
                {
                    NPC nPC = Main.npc[i];
                    if (!nPC.active || nPC.dontTakeDamage || nPC.friendly || (nPC.aiStyle == 112 && !(nPC.ai[2] <= 1f)) || !CanNPCBeHitByPlayerOrPlayerProjectile(nPC))
                    {
                        continue;
                    }
                    Rectangle rect = nPC.getRect();
                    if (((Rectangle)(ref rectangle)).Intersects(rect) && (nPC.noTileCollide || CanHit(nPC)))
                    {
                        float num = GetTotalDamage(DamageClass.Melee).ApplyTo(30f);
                        float num12 = GetTotalKnockback(DamageClass.Melee).ApplyTo(9f);
                        bool crit = false;
                        if ((float)Main.rand.Next(100) < GetTotalCritChance(DamageClass.Melee))
{
                            crit = true;
                        }
                        int num21 = direction;
                        if (velocity.X < 0f)
{
                            num21 = -1;
                        }
                        if (velocity.X > 0f)
{
                            num21 = 1;
                        }
                        if (whoAmI == Main.myPlayer)
{
                            ApplyDamageToNPC(nPC, (int)num, num12, num21, crit, DamageClass.Melee);
                        }
                        eocDash = 10;
                        dashDelay = 30;
                        velocity.X = -num21 * 9;
                        velocity.Y = -4f;
                        GiveImmuneTimeForCollisionAttack(4);
                        eocHit = i;
                    }
                }
            }
            else if ((!controlLeft || !(velocity.X < 0f)) && (!controlRight || !(velocity.X > 0f)))
            {
                velocity.X *= 0.95f;
            }
        }
        if (dash == 3 && dashDelay < 0 && whoAmI == Main.myPlayer)
        {
            Rectangle rectangle2 = default(Rectangle);
            ((Rectangle)(ref rectangle2))._002Ector((int)((double)position.X + (double)velocity.X * 0.5 - 4.0), (int)((double)position.Y + (double)velocity.Y * 0.5 - 4.0), width + 8, height + 8);
            for (int j = 0; j < 200; j++)
            {
                NPC nPC2 = Main.npc[j];
                if (!nPC2.active || nPC2.dontTakeDamage || nPC2.friendly || nPC2.immune[whoAmI] > 0 || (nPC2.aiStyle == 112 && !(nPC2.ai[2] <= 1f)) || !CanNPCBeHitByPlayerOrPlayerProjectile(nPC2))
                {
                    continue;
                }
                Rectangle rect2 = nPC2.getRect();
                if (((Rectangle)(ref rectangle2)).Intersects(rect2) && (nPC2.noTileCollide || CanHit(nPC2)))
                {
                    if (!solarDashConsumedFlare)
                    {
                        solarDashConsumedFlare = true;
                        ConsumeSolarFlare();
                    }
                    float num22 = GetTotalDamage(DamageClass.Melee).ApplyTo(150f);
                    float num23 = GetTotalKnockback(DamageClass.Melee).ApplyTo(9f);
                    bool crit2 = false;
                    if ((float)Main.rand.Next(100) < GetTotalCritChance(DamageClass.Melee))
                    {
                        crit2 = true;
                    }
                    int num24 = direction;
                    if (velocity.X < 0f)
                    {
                        num24 = -1;
                    }
                    if (velocity.X > 0f)
                    {
                        num24 = 1;
                    }
                    if (whoAmI == Main.myPlayer)
                    {
                        ApplyDamageToNPC(nPC2, (int)num22, num23, num24, crit2, DamageClass.Melee);
                        int num25 = Projectile.NewProjectile(GetProjectileSource_OnHit(nPC2, 2), base.Center.X, base.Center.Y, 0f, 0f, 608, (int)num22, 15f, Main.myPlayer);
                        Main.projectile[num25].Kill();
                    }
                    nPC2.immune[whoAmI] = 6;
                    GiveImmuneTimeForCollisionAttack(4);
                }
            }
        }
        if (dashDelay > 0)
        {
            if (eocDash > 0)
            {
                eocDash--;
            }
            if (eocDash == 0)
            {
                eocHit = -1;
            }
            dashDelay--;
        }
        else if (dashDelay < 0)
        {
            StopVanityActions();
            float num26 = 12f;
            float num27 = 0.992f;
            float num2 = Math.Max(accRunSpeed, maxRunSpeed);
            float num3 = 0.96f;
            int num4 = 20;
            if (dash == 1)
            {
                for (int k = 0; k < 2; k++)
                {
                    int num5 = ((velocity.Y != 0f) ? Dust.NewDust(new Vector2(position.X, position.Y + (float)(height / 2) - 8f), width, 16, 31, 0f, 0f, 100, default(Color), 1.4f) : Dust.NewDust(new Vector2(position.X, position.Y + (float)height - 4f), width, 8, 31, 0f, 0f, 100, default(Color), 1.4f));
                    Dust obj = Main.dust[num5];
                    obj.velocity *= 0.1f;
                    Main.dust[num5].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                }
            }
            else if (dash == 2)
            {
                for (int l = 0; l < 0; l++)
                {
                    int num6 = ((velocity.Y != 0f) ? Dust.NewDust(new Vector2(position.X, position.Y + (float)(height / 2) - 8f), width, 16, 31, 0f, 0f, 100, default(Color), 1.4f) : Dust.NewDust(new Vector2(position.X, position.Y + (float)height - 4f), width, 8, 31, 0f, 0f, 100, default(Color), 1.4f));
                    Dust obj2 = Main.dust[num6];
                    obj2.velocity *= 0.1f;
                    Main.dust[num6].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                }
                num27 = 0.985f;
                num3 = 0.94f;
                num4 = 30;
            }
            else if (dash == 3)
            {
                for (int m = 0; m < 4; m++)
                {
                    int num7 = Dust.NewDust(new Vector2(position.X, position.Y + 4f), width, height - 8, 6, 0f, 0f, 100, default(Color), 1.7f);
                    Dust obj3 = Main.dust[num7];
                    obj3.velocity *= 0.1f;
                    Main.dust[num7].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                    Main.dust[num7].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                    Main.dust[num7].noGravity = true;
                    if (Main.rand.Next(2) == 0)
                    {
                        Main.dust[num7].fadeIn = 0.5f;
                    }
                }
                num26 = 14f;
                num27 = 0.985f;
                num3 = 0.94f;
                num4 = 20;
            }
            else if (dash == 4)
            {
                for (int n = 0; n < 2; n++)
                {
                    int num8 = Dust.NewDust(new Vector2(position.X, position.Y + 4f), width, height - 8, 229, 0f, 0f, 100, default(Color), 1.2f);
                    Dust obj4 = Main.dust[num8];
                    obj4.velocity *= 0.1f;
                    Main.dust[num8].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                    Main.dust[num8].noGravity = true;
                    if (Main.rand.Next(2) == 0)
                    {
                        Main.dust[num8].fadeIn = 0.3f;
                    }
                }
                num27 = 0.985f;
                num3 = 0.94f;
                num4 = 20;
            }
            if (dash == 5)
            {
                for (int num9 = 0; num9 < 2; num9++)
                {
                    int type = Main.rand.NextFromList(new short[3] { 68, 69, 70 });
                    int num10 = ((velocity.Y != 0f) ? Dust.NewDust(new Vector2(position.X, position.Y + (float)(height / 2) - 8f), width, 16, type, 0f, 0f, 100) : Dust.NewDust(new Vector2(position.X, position.Y + (float)height - 4f), width, 8, type, 0f, 0f, 100));
                    Dust obj5 = Main.dust[num10];
                    obj5.velocity *= 0.2f;
                    Main.dust[num10].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                    Main.dust[num10].fadeIn = 0.5f + (float)Main.rand.Next(20) * 0.01f;
                    Main.dust[num10].noGravity = true;
                    Main.dust[num10].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                }
            }
            if (dash <= 0)
            {
                return;
            }
            doorHelper.AllowOpeningDoorsByVelocityAloneForATime(num4 * 3);
            vortexStealthActive = false;
            if (velocity.X > num26 || velocity.X < 0f - num26)
            {
                velocity.X *= num27;
                return;
            }
            if (velocity.X > num2 || velocity.X < 0f - num2)
            {
                velocity.X *= num3;
                return;
            }
            dashDelay = num4;
            if (velocity.X < 0f)
            {
                velocity.X = 0f - num2;
            }
            else if (velocity.X > 0f)
            {
                velocity.X = num2;
            }
        }
        else
        {
            if (dash <= 0 || mount.Active)
            {
                return;
            }
            if (dash == 1)
            {
                DoCommonDashHandle(out var dir, out var dashing);
                if (dashing)
                {
                    velocity.X = 16.9f * (float)dir;
                    Point point = (base.Center + new Vector2((float)(dir * width / 2 + 2), gravDir * (float)(-height) / 2f + gravDir * 2f)).ToTileCoordinates();
                    Point point2 = (base.Center + new Vector2((float)(dir * width / 2 + 2), 0f)).ToTileCoordinates();
                    if (WorldGen.SolidOrSlopedTile(point.X, point.Y) || WorldGen.SolidOrSlopedTile(point2.X, point2.Y))
                    {
                        velocity.X /= 2f;
                    }
                    dashDelay = -1;
                    for (int num11 = 0; num11 < 20; num11++)
                    {
                        int num13 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 2f);
                        Main.dust[num13].position.X += Main.rand.Next(-5, 6);
                        Main.dust[num13].position.Y += Main.rand.Next(-5, 6);
                        Dust obj6 = Main.dust[num13];
                        obj6.velocity *= 0.2f;
                        Main.dust[num13].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                    }
                    int num14 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 34f), default(Vector2), Main.rand.Next(61, 64));
                    Main.gore[num14].velocity.X = (float)Main.rand.Next(-50, 51) * 0.01f;
                    Main.gore[num14].velocity.Y = (float)Main.rand.Next(-50, 51) * 0.01f;
                    Gore obj7 = Main.gore[num14];
                    obj7.velocity *= 0.4f;
                    num14 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 14f), default(Vector2), Main.rand.Next(61, 64));
                    Main.gore[num14].velocity.X = (float)Main.rand.Next(-50, 51) * 0.01f;
                    Main.gore[num14].velocity.Y = (float)Main.rand.Next(-50, 51) * 0.01f;
                    Gore obj8 = Main.gore[num14];
                    obj8.velocity *= 0.4f;
                }
            }
            else if (dash == 2)
            {
                DoCommonDashHandle(out var dir2, out var dashing2);
                if (dashing2)
                {
                    velocity.X = 14.5f * (float)dir2;
                    Point point3 = (base.Center + new Vector2((float)(dir2 * width / 2 + 2), gravDir * (float)(-height) / 2f + gravDir * 2f)).ToTileCoordinates();
                    Point point4 = (base.Center + new Vector2((float)(dir2 * width / 2 + 2), 0f)).ToTileCoordinates();
                    if (WorldGen.SolidOrSlopedTile(point3.X, point3.Y) || WorldGen.SolidOrSlopedTile(point4.X, point4.Y))
                    {
                        velocity.X /= 2f;
                    }
                    dashDelay = -1;
                    eocDash = 15;
                    for (int num15 = 0; num15 < 0; num15++)
                    {
                        int num16 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 2f);
                        Main.dust[num16].position.X += Main.rand.Next(-5, 6);
                        Main.dust[num16].position.Y += Main.rand.Next(-5, 6);
                        Dust obj9 = Main.dust[num16];
                        obj9.velocity *= 0.2f;
                        Main.dust[num16].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                    }
                }
            }
            else if (dash == 3)
            {
                DoCommonDashHandle(out var dir3, out var dashing3, SolarDashStart);
                if (dashing3)
                {
                    velocity.X = 21.9f * (float)dir3;
                    Point point5 = (base.Center + new Vector2((float)(dir3 * width / 2 + 2), gravDir * (float)(-height) / 2f + gravDir * 2f)).ToTileCoordinates();
                    Point point6 = (base.Center + new Vector2((float)(dir3 * width / 2 + 2), 0f)).ToTileCoordinates();
                    if (WorldGen.SolidOrSlopedTile(point5.X, point5.Y) || WorldGen.SolidOrSlopedTile(point6.X, point6.Y))
                    {
                        velocity.X /= 2f;
                    }
                    dashDelay = -1;
                    for (int num17 = 0; num17 < 20; num17++)
                    {
                        int num18 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 6, 0f, 0f, 100, default(Color), 2f);
                        Main.dust[num18].position.X += Main.rand.Next(-5, 6);
                        Main.dust[num18].position.Y += Main.rand.Next(-5, 6);
                        Dust obj10 = Main.dust[num18];
                        obj10.velocity *= 0.2f;
                        Main.dust[num18].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                        Main.dust[num18].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                        Main.dust[num18].noGravity = true;
                        Main.dust[num18].fadeIn = 0.5f;
                    }
                }
            }
            if (dash != 5)
            {
                return;
            }
            DoCommonDashHandle(out var dir4, out var dashing4);
            if (dashing4)
            {
                velocity.X = 16.9f * (float)dir4;
                Point point7 = (base.Center + new Vector2((float)(dir4 * width / 2 + 2), gravDir * (float)(-height) / 2f + gravDir * 2f)).ToTileCoordinates();
                Point point8 = (base.Center + new Vector2((float)(dir4 * width / 2 + 2), 0f)).ToTileCoordinates();
                if (WorldGen.SolidOrSlopedTile(point7.X, point7.Y) || WorldGen.SolidOrSlopedTile(point8.X, point8.Y))
                {
                    velocity.X /= 2f;
                }
                dashDelay = -1;
                for (int num19 = 0; num19 < 20; num19++)
                {
                    int type2 = Main.rand.NextFromList(new short[3] { 68, 69, 70 });
                    int num20 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, type2, 0f, 0f, 100, default(Color), 1.5f);
                    Main.dust[num20].position.X += Main.rand.Next(-5, 6);
                    Main.dust[num20].position.Y += Main.rand.Next(-5, 6);
                    Main.dust[num20].velocity = DirectionTo(Main.dust[num20].position) * 2f;
                    Main.dust[num20].scale *= 1f + (float)Main.rand.Next(20) * 0.01f;
                    Main.dust[num20].fadeIn = 0.5f + (float)Main.rand.Next(20) * 0.01f;
                    Main.dust[num20].noGravity = true;
                    Main.dust[num20].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                }
            }
        }
    }
References Terraria.Player.accRunSpeed, Terraria.Mount.Active, Terraria.GameContent.DoorOpeningHelper.AllowOpeningDoorsByVelocityAloneForATime(), Terraria.Player.ApplyDamageToNPC(), Terraria.ModLoader.StatModifier.ApplyTo(), Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.ArmorSetDye(), Terraria.Player.CanHit(), Terraria.Player.CanNPCBeHitByPlayerOrPlayerProjectile(), Terraria.Player.ConsumeSolarFlare(), Terraria.Player.controlLeft, Terraria.Player.controlRight, Terraria.Player.dash, Terraria.Player.dashDelay, Terraria.Player.dashTime, Terraria.Player.dashType, Terraria.Entity.direction, Terraria.Entity.DirectionTo(), Terraria.Player.DoCommonDashHandle(), Terraria.Player.doorHelper, Terraria.Main.dust, Terraria.Player.eocDash, Terraria.Player.eocHit, Terraria.Player.GetProjectileSource_OnHit(), Terraria.Player.GetTotalCritChance(), Terraria.Player.GetTotalDamage(), Terraria.Player.GetTotalKnockback(), Terraria.Player.GiveImmuneTimeForCollisionAttack(), Terraria.Main.gore, Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Player.maxRunSpeed, Terraria.ModLoader.DamageClass.Melee, Terraria.Player.mount, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Player.solarDashConsumedFlare, Terraria.Player.SolarDashStart(), Terraria.WorldGen.SolidOrSlopedTile(), Terraria.Player.StopVanityActions(), Terraria.Entity.velocity, Terraria.Player.vortexStealthActive, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().