TModLoader: Terraria.Player.PurgeDD2EnergyCrystals
PurgeDD2EnergyCrystals()
void Terraria.Player.PurgeDD2EnergyCrystals () inline private
Definition at line 29149 of file Player.cs.
    {
        if (trashItem.type == 3822)
        {
            trashItem.TurnToAir();
        }
        if (Main.myPlayer == whoAmI && Main.mouseItem.type == 3822)
        {
            Main.mouseItem.TurnToAir();
        }
        for (int i = 0; i < 59; i++)
        {
            Item item = inventory[i];
            if (item.stack > 0 && item.type == 3822)
            {
                item.TurnToAir();
            }
        }
        if (this.chest == -2)
        {
            Chest chest = bank;
            for (int j = 0; j < 40; j++)
            {
                if (chest.item[j].stack > 0 && chest.item[j].type == 3822)
                {
                    chest.item[j].TurnToAir();
                }
            }
        }
        if (this.chest == -4)
        {
            Chest chest2 = bank3;
            for (int k = 0; k < 40; k++)
            {
                if (chest2.item[k].stack > 0 && chest2.item[k].type == 3822)
                {
                    chest2.item[k].TurnToAir();
                }
            }
        }
        if (this.chest == -5)
        {
            Chest chest3 = bank4;
            for (int l = 0; l < 40; l++)
            {
                if (chest3.item[l].stack > 0 && chest3.item[l].type == 3822)
                {
                    chest3.item[l].TurnToAir();
                }
            }
        }
        if (this.chest == -3)
        {
            Chest chest4 = bank2;
            for (int m = 0; m < 40; m++)
            {
                if (chest4.item[m].stack > 0 && chest4.item[m].type == 3822)
                {
                    chest4.item[m].TurnToAir();
                }
            }
        }
        if (this.chest <= -1)
        {
            return;
        }
        Chest chest5 = Main.chest[this.chest];
        for (int n = 0; n < 40; n++)
        {
            if (chest5.item[n].stack > 0 && chest5.item[n].type == 3822)
            {
                chest5.item[n].TurnToAir();
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(32, -1, -1, null, this.chest, n);
                }
            }
        }
    }
References Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Main.chest, Terraria.Player.chest, Terraria.Player.inventory, Terraria.Chest.item, Terraria.Main.mouseItem, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.Item.stack, Terraria.Player.trashItem, Terraria.Item.TurnToAir(), Terraria.Item.type, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.Update().