TModLoader: Terraria.Player.Spawn_SetPositionAtWorldSpawn
Spawn_SetPositionAtWorldSpawn()
void Terraria.Player.Spawn_SetPositionAtWorldSpawn () inline private
    {
        int floorX = Main.spawnTileX;
        int floorY = Main.spawnTileY;
        bool num = Spawn_GetPositionAtWorldSpawn(ref floorX, ref floorY);
        Spawn_SetPosition(floorX, floorY);
        if (num && !Spawn_IsAreaAValidWorldSpawn(floorX, floorY))
        {
            Spawn_ForceClearArea(floorX, floorY);
        }
    }
References Terraria.Player.Spawn_ForceClearArea(), Terraria.Player.Spawn_GetPositionAtWorldSpawn(), Terraria.Player.Spawn_IsAreaAValidWorldSpawn(), Terraria.Player.Spawn_SetPosition(), Terraria.Main.spawnTileX, and Terraria.Main.spawnTileY.
Referenced by Terraria.Player.Spawn().