TModLoader: Terraria.Player.ItemCheck_EmitHeldItemLight
ItemCheck_EmitHeldItemLight()
void Terraria.Player.ItemCheck_EmitHeldItemLight (Item sItem) inline private
Definition at line 50437 of file Player.cs.
    {
        //IL_0738: Unknown result type (might be due to invalid IL or missing references)
        //IL_073f: Unknown result type (might be due to invalid IL or missing references)
        //IL_066a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0680: Unknown result type (might be due to invalid IL or missing references)
        //IL_0686: Unknown result type (might be due to invalid IL or missing references)
        //IL_060b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0612: Unknown result type (might be due to invalid IL or missing references)
        //IL_053d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0553: Unknown result type (might be due to invalid IL or missing references)
        //IL_0559: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0704: Unknown result type (might be due to invalid IL or missing references)
        //IL_058b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0595: Unknown result type (might be due to invalid IL or missing references)
        //IL_059a: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d78: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d30: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d37: Unknown result type (might be due to invalid IL or missing references)
        //IL_09dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_090a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0924: Unknown result type (might be due to invalid IL or missing references)
        //IL_092a: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0390: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_033a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0341: Unknown result type (might be due to invalid IL or missing references)
        //IL_022a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f03: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ebb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a95: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aaf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab5: Unknown result type (might be due to invalid IL or missing references)
        //IL_095c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0966: Unknown result type (might be due to invalid IL or missing references)
        //IL_096b: Unknown result type (might be due to invalid IL or missing references)
        //IL_099c: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_082b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0835: Unknown result type (might be due to invalid IL or missing references)
        //IL_083a: Unknown result type (might be due to invalid IL or missing references)
        //IL_086b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0872: Unknown result type (might be due to invalid IL or missing references)
        //IL_0877: Unknown result type (might be due to invalid IL or missing references)
        //IL_03df: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_041f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0426: Unknown result type (might be due to invalid IL or missing references)
        //IL_042b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        //IL_0283: Unknown result type (might be due to invalid IL or missing references)
        //IL_0288: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c58: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b33: Unknown result type (might be due to invalid IL or missing references)
        //IL_044d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0452: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_1121: Unknown result type (might be due to invalid IL or missing references)
        //IL_1128: Unknown result type (might be due to invalid IL or missing references)
        //IL_112d: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_10be: Unknown result type (might be due to invalid IL or missing references)
        //IL_1066: Unknown result type (might be due to invalid IL or missing references)
        //IL_106d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f45: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_11fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1202: Unknown result type (might be due to invalid IL or missing references)
        //IL_1207: Unknown result type (might be due to invalid IL or missing references)
        //IL_1184: Unknown result type (might be due to invalid IL or missing references)
        //IL_1189: Unknown result type (might be due to invalid IL or missing references)
        //IL_118a: Unknown result type (might be due to invalid IL or missing references)
        //IL_118f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1191: Unknown result type (might be due to invalid IL or missing references)
        //IL_1193: Unknown result type (might be due to invalid IL or missing references)
        //IL_1198: Unknown result type (might be due to invalid IL or missing references)
        //IL_119a: Unknown result type (might be due to invalid IL or missing references)
        //IL_119c: Unknown result type (might be due to invalid IL or missing references)
        //IL_11a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_11b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_11b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1167: Unknown result type (might be due to invalid IL or missing references)
        //IL_116e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1173: Unknown result type (might be due to invalid IL or missing references)
        //IL_1326: Unknown result type (might be due to invalid IL or missing references)
        //IL_1340: Unknown result type (might be due to invalid IL or missing references)
        //IL_1345: Unknown result type (might be due to invalid IL or missing references)
        //IL_134a: Unknown result type (might be due to invalid IL or missing references)
        //IL_135a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1364: Unknown result type (might be due to invalid IL or missing references)
        //IL_1369: Unknown result type (might be due to invalid IL or missing references)
        //IL_136b: Unknown result type (might be due to invalid IL or missing references)
        //IL_136e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1373: Unknown result type (might be due to invalid IL or missing references)
        //IL_1374: Unknown result type (might be due to invalid IL or missing references)
        //IL_1375: Unknown result type (might be due to invalid IL or missing references)
        //IL_1217: Unknown result type (might be due to invalid IL or missing references)
        //IL_1238: Unknown result type (might be due to invalid IL or missing references)
        //IL_123e: Unknown result type (might be due to invalid IL or missing references)
        //IL_124f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1251: Unknown result type (might be due to invalid IL or missing references)
        //IL_1259: Unknown result type (might be due to invalid IL or missing references)
        //IL_1263: Unknown result type (might be due to invalid IL or missing references)
        //IL_1268: Unknown result type (might be due to invalid IL or missing references)
        //IL_1284: Unknown result type (might be due to invalid IL or missing references)
        //IL_128a: Unknown result type (might be due to invalid IL or missing references)
        //IL_128f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1294: Unknown result type (might be due to invalid IL or missing references)
        //IL_139b: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_13ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_13cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_13dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_13de: Unknown result type (might be due to invalid IL or missing references)
        //IL_12a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_12bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_12c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_12c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_13ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_13ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_13f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_13fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1403: Unknown result type (might be due to invalid IL or missing references)
        Vector2? handPosition = HandPosition;
        if (((ItemID.Sets.Torches[sItem.type] && !wet) || ItemID.Sets.WaterTorches[BiomeTorchHoldStyle(sItem.type)]) && !pulley && !happyFunTorchTime)
        {
            float R = 1f;
            float G = 0.95f;
            float B = 0.8f;
            int num = 0;
            int num4 = BiomeTorchHoldStyle(sItem.type);
            if (num4 >= ItemID.Count)
            {
                ItemLoader.GetItem(num4).HoldItem(this);
            }
            else
            {
                if (num4 == 523)
                {
                    num = 8;
                }
                else if (num4 == 974)
                {
                    num = 9;
                }
                else if (num4 == 1245)
                {
                    num = 10;
                }
                else if (num4 == 1333)
                {
                    num = 11;
                }
                else if (num4 == 2274)
                {
                    num = 12;
                }
                else if (num4 == 3004)
                {
                    num = 13;
                }
                else if (num4 == 3045)
                {
                    num = 14;
                }
                else if (num4 == 3114)
                {
                    num = 15;
                }
                else if (num4 == 4383)
                {
                    num = 16;
                }
                else if (num4 == 4384)
                {
                    num = 17;
                }
                else if (num4 == 4385)
                {
                    num = 18;
                }
                else if (num4 == 4386)
                {
                    num = 19;
                }
                else if (num4 == 4387)
                {
                    num = 20;
                }
                else if (num4 == 4388)
                {
                    num = 21;
                }
                else if (num4 == 5293)
                {
                    num = 22;
                }
                else if (num4 == 5353)
                {
                    num = 23;
                }
                else if (num4 >= 427)
                {
                    num = num4 - 426;
                }
                num = (int)MathHelper.Clamp((float)num, 0f, (float)(TorchID.Count - 1));
                TorchID.TorchColor(num, out R, out G, out B);
                int num5 = TorchID.Dust[num];
                int maxValue = 30;
                if (itemAnimation > 0)
                {
                    maxValue = 7;
                }
                if (direction == -1)
                {
                    if (Main.rand.Next(maxValue) == 0)
                    {
                        int num6 = Dust.NewDust(new Vector2(itemLocation.X - 16f, itemLocation.Y - 14f * gravDir), 4, 4, num5, 0f, 0f, 100);
                        if (Main.rand.Next(3) != 0)
{
                            Main.dust[num6].noGravity = true;
                        }
                        Dust obj = Main.dust[num6];
                        obj.velocity *= 0.3f;
                        Main.dust[num6].velocity.Y -= 1.5f;
                        Main.dust[num6].position = RotatedRelativePoint(Main.dust[num6].position);
                        if (num5 == 66)
{
                            Main.dust[num6].color = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                            Main.dust[num6].noGravity = true;
                        }
                    }
                    Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 12f + velocity.X, itemLocation.Y - 14f + velocity.Y)), R, G, B);
                }
                else
                {
                    if (Main.rand.Next(maxValue) == 0)
                    {
                        int num7 = Dust.NewDust(new Vector2(itemLocation.X + 6f, itemLocation.Y - 14f * gravDir), 4, 4, num5, 0f, 0f, 100);
                        if (Main.rand.Next(3) != 0)
{
                            Main.dust[num7].noGravity = true;
                        }
                        Dust obj2 = Main.dust[num7];
                        obj2.velocity *= 0.3f;
                        Main.dust[num7].velocity.Y -= 1.5f;
                        Main.dust[num7].position = RotatedRelativePoint(Main.dust[num7].position);
                        if (num5 == 66)
{
                            Main.dust[num7].color = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                            Main.dust[num7].noGravity = true;
                        }
                    }
                    Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 12f + velocity.X, itemLocation.Y - 14f + velocity.Y)), R, G, B);
                }
            }
        }
        if ((sItem.type == 105 || sItem.type == 713) && !wet && !pulley)
        {
            int maxValue2 = 20;
            if (itemAnimation > 0)
            {
                maxValue2 = 7;
            }
            if (direction == -1)
            {
                if (Main.rand.Next(maxValue2) == 0)
                {
                    int num8 = Dust.NewDust(new Vector2(itemLocation.X - 12f, itemLocation.Y - 20f * gravDir), 4, 4, 6, 0f, 0f, 100);
                    if (Main.rand.Next(3) != 0)
                    {
                        Main.dust[num8].noGravity = true;
                    }
                    Dust obj3 = Main.dust[num8];
                    obj3.velocity *= 0.3f;
                    Main.dust[num8].velocity.Y -= 1.5f;
                    Main.dust[num8].position = RotatedRelativePoint(Main.dust[num8].position);
                }
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), 1f, 0.95f, 0.8f);
            }
            else
            {
                if (Main.rand.Next(maxValue2) == 0)
                {
                    int num9 = Dust.NewDust(new Vector2(itemLocation.X + 4f, itemLocation.Y - 20f * gravDir), 4, 4, 6, 0f, 0f, 100);
                    if (Main.rand.Next(3) != 0)
                    {
                        Main.dust[num9].noGravity = true;
                    }
                    Dust obj4 = Main.dust[num9];
                    obj4.velocity *= 0.3f;
                    Main.dust[num9].velocity.Y -= 1.5f;
                    Main.dust[num9].position = RotatedRelativePoint(Main.dust[num9].position);
                }
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), 1f, 0.95f, 0.8f);
            }
        }
        else if (sItem.type == 148 && !wet && !pulley)
        {
            int maxValue3 = 10;
            if (itemAnimation > 0)
            {
                maxValue3 = 7;
            }
            if (direction == -1)
            {
                if (Main.rand.Next(maxValue3) == 0)
                {
                    int num10 = Dust.NewDust(new Vector2(itemLocation.X - 12f, itemLocation.Y - 20f * gravDir), 4, 4, 172, 0f, 0f, 100);
                    if (Main.rand.Next(3) != 0)
                    {
                        Main.dust[num10].noGravity = true;
                    }
                    Dust obj5 = Main.dust[num10];
                    obj5.velocity *= 0.3f;
                    Main.dust[num10].velocity.Y -= 1.5f;
                    Main.dust[num10].position = RotatedRelativePoint(Main.dust[num10].position);
                }
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), 0f, 0.5f, 1f);
            }
            else
            {
                if (Main.rand.Next(maxValue3) == 0)
                {
                    int num11 = Dust.NewDust(new Vector2(itemLocation.X + 4f, itemLocation.Y - 20f * gravDir), 4, 4, 172, 0f, 0f, 100);
                    if (Main.rand.Next(3) != 0)
                    {
                        Main.dust[num11].noGravity = true;
                    }
                    Dust obj6 = Main.dust[num11];
                    obj6.velocity *= 0.3f;
                    Main.dust[num11].velocity.Y -= 1.5f;
                    Main.dust[num11].position = RotatedRelativePoint(Main.dust[num11].position);
                }
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), 0f, 0.5f, 1f);
            }
        }
        else if (sItem.type == 3117 && !wet && !pulley)
        {
            itemLocation.X -= direction * 4;
            int maxValue4 = 10;
            if (itemAnimation > 0)
            {
                maxValue4 = 7;
            }
            if (direction == -1)
            {
                if (Main.rand.Next(maxValue4) == 0)
                {
                    int num2 = Dust.NewDust(new Vector2(itemLocation.X - 10f, itemLocation.Y - 20f * gravDir), 4, 4, 242, 0f, 0f, 100);
                    if (Main.rand.Next(3) != 0)
                    {
                        Main.dust[num2].noGravity = true;
                    }
                    Dust obj7 = Main.dust[num2];
                    obj7.velocity *= 0.3f;
                    Main.dust[num2].velocity.Y -= 1.5f;
                    Main.dust[num2].position = RotatedRelativePoint(Main.dust[num2].position);
                }
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), 0.9f, 0.1f, 0.75f);
            }
            else
            {
                if (Main.rand.Next(maxValue4) == 0)
                {
                    int num3 = Dust.NewDust(new Vector2(itemLocation.X + 6f, itemLocation.Y - 20f * gravDir), 4, 4, 242, 0f, 0f, 100);
                    if (Main.rand.Next(3) != 0)
                    {
                        Main.dust[num3].noGravity = true;
                    }
                    Dust obj8 = Main.dust[num3];
                    obj8.velocity *= 0.3f;
                    Main.dust[num3].velocity.Y -= 1.5f;
                    Main.dust[num3].position = RotatedRelativePoint(Main.dust[num3].position);
                }
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), 0.9f, 0.1f, 0.75f);
            }
        }
        else if (sItem.type == 5322 && !wet && !pulley)
        {
            float r = 0.2f;
            float g = 0.3f;
            float b = 0.32f;
            if (direction == -1)
            {
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), r, g, b);
            }
            else
            {
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), r, g, b);
            }
        }
        if (sItem.type == 282 && !pulley)
        {
            if (direction == -1)
            {
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), 0.7f, 1f, 0.8f);
            }
            else
            {
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), 0.7f, 1f, 0.8f);
            }
        }
        if (sItem.type == 3002 && !pulley)
        {
            float r2 = 1.05f;
            float g2 = 0.95f;
            float b2 = 0.55f;
            if (direction == -1)
            {
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), r2, g2, b2);
            }
            else
            {
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), r2, g2, b2);
            }
            spelunkerTimer++;
            if (spelunkerTimer >= 10)
            {
                spelunkerTimer = 0;
                Main.instance.SpelunkerProjectileHelper.AddSpotToCheck(base.Center);
            }
        }
        if (sItem.type == 286 && !pulley)
        {
            if (direction == -1)
            {
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), 0.7f, 0.8f, 1f);
            }
            else
            {
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), 0.7f, 0.8f, 1f);
            }
        }
        if (sItem.type == 3112 && !pulley)
        {
            if (direction == -1)
            {
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f)), 1f, 0.6f, 0.85f);
            }
            else
            {
                Lighting.AddLight(RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f)), 1f, 0.6f, 0.85f);
            }
        }
        if (sItem.type == 4776 && !pulley)
        {
            Vector2 vec = RotatedRelativePoint(new Vector2(itemLocation.X + 6f + velocity.X, itemLocation.Y - 14f));
            if (direction == -1)
            {
                vec = RotatedRelativePoint(new Vector2(itemLocation.X - 16f + velocity.X, itemLocation.Y - 14f));
            }
            Vector3 rgb = (DelegateMethods.v3_1 = new Vector3(0.9f, 0.35f, 1f));
            Point p = vec.ToTileCoordinates();
            DelegateMethods.v2_1 = p.ToVector2();
            DelegateMethods.f_1 = 4.5f;
            Utils.PlotTileArea(p.X, p.Y, DelegateMethods.SpreadLightOpen_StopForSolids);
            Lighting.AddLight(vec, rgb);
        }
        if (sItem.type == 3542 && handPosition.HasValue)
        {
            Vector2 vector = handPosition.Value - velocity;
            for (int i = 0; i < 4; i++)
            {
                Dust dust = Main.dust[Dust.NewDust(base.Center, 0, 0, 242, direction * 2, 0f, 150, default(Color), 1.3f)];
                dust.position = vector;
                dust.velocity *= 0f;
                dust.noGravity = true;
                dust.fadeIn = 1f;
                dust.velocity += velocity;
                if (Main.rand.Next(2) == 0)
                {
                    dust.position += Utils.RandomVector2(Main.rand, -4f, 4f);
                    dust.scale += Main.rand.NextFloat();
                    if (Main.rand.Next(2) == 0)
                    {
                        dust.customData = this;
                    }
                }
            }
        }
        if (sItem.type != 4952 || pulley || isPettingAnimal)
        {
            return;
        }
        Vector2 pos = itemLocation + new Vector2((float)(8 * direction), -10f * gravDir);
        Vector3 rgb2 = new Vector3(1f, 0.7f, 0.8f) * 1.3f;
        Vector2 vector2 = RotatedRelativePoint(pos);
        Lighting.AddLight(vector2, rgb2);
        if (Main.rand.Next(40) == 0)
        {
            Vector2 vector3 = Main.rand.NextVector2Circular(4f, 4f);
            Dust dust2 = Dust.NewDustPerfect(vector2 + vector3, 43, Vector2.Zero, 254, new Color(255, 255, 0, 255), 0.3f);
            if (vector3 != Vector2.Zero)
            {
                dust2.velocity = vector2.DirectionTo(dust2.position) * 0.2f;
            }
            dust2.fadeIn = 0.3f;
            dust2.noLightEmittence = true;
            dust2.customData = this;
        }
    }
References Terraria.Lighting.AddLight(), Terraria.Player.BiomeTorchHoldStyle(), Terraria.ID.ItemID.Count, Terraria.ID.TorchID.Count, Terraria.Entity.direction, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.ID.TorchID.Dust, Terraria.Main.dust, Terraria.ModLoader.ItemLoader.GetItem(), Terraria.Player.gravDir, Terraria.Player.HandPosition, Terraria.Player.happyFunTorchTime, Terraria.Main.instance, Terraria.Player.isPettingAnimal, Terraria.Player.itemAnimation, Terraria.Player.itemLocation, Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Utils.PlotTileArea(), Terraria.Player.pulley, Terraria.Main.rand, Terraria.Utils.RandomVector2(), Terraria.Player.RotatedRelativePoint(), Terraria.Player.spelunkerTimer, Terraria.DelegateMethods.SpreadLightOpen_StopForSolids(), Terraria.ID.TorchID.TorchColor(), Terraria.ID.ItemID.Sets.Torches, Terraria.Entity.velocity, Terraria.ID.ItemID.Sets.WaterTorches, and Terraria.Entity.wet.
Referenced by Terraria.Player.ItemCheck_Inner().