TModLoader: Terraria.Player.GetTotalArmorPenetration
GetTotalArmorPenetration()
float Terraria.Player.GetTotalArmorPenetration (DamageClass damageClass) inline
Definition at line 58453 of file Player.cs.
    {
        float stat = damageData[damageClass.Type].armorPen;
        for (int i = 0; i < damageData.Length; i++)
        {
            if (i != damageClass.Type)
            {
                StatInheritanceData inheritanceData = damageClass.GetModifierInheritance(DamageClassLoader.DamageClasses[i]);
                stat += damageData[i].armorPen * inheritanceData.armorPenInheritance;
            }
        }
        return stat;
    }
References Terraria.ModLoader.DamageClassData.armorPen, Terraria.ModLoader.DamageClassLoader.DamageClasses, and Terraria.Player.damageData.
Referenced by Terraria.Player.ApplyDamageToNPC(), Terraria.Player.GetTotalArmorPenetration< T >(), Terraria.Player.GetWeaponArmorPenetration(), and Terraria.Projectile.Update().