TModLoader: Terraria.Player.DropSelectedItem
DropSelectedItem() [2/2]
void Terraria.Player.DropSelectedItem (int slot, ref Item theItemWeDrop) inline
Definition at line 5573 of file Player.cs.
    {
        //IL_00da: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        bool flag = false;
        if (theItemWeDrop.favorited)
        {
            theItemWeDrop = GetItem(whoAmI, theItemWeDrop, GetItemSettings.GetItemInDropItemCheck);
            if (slot == 58)
            {
                Main.mouseItem = theItemWeDrop;
            }
            Recipe.FindRecipes();
            if (theItemWeDrop.type == 0)
            {
                flag = true;
            }
        }
        if (!flag)
        {
            Item item = new Item();
            if (((Main.mouseRight && !mouseInterface && Main.mouseRightRelease) || !Main.playerInventory) && Main.mouseItem.type > 0 && Main.mouseItem.stack > 0)
            {
                item = theItemWeDrop;
                theItemWeDrop = Main.mouseItem;
                delayUseItem = true;
                controlUseItem = false;
            }
            if (whoAmI == Main.myPlayer && theItemWeDrop.type == 5095)
            {
                LucyAxeMessage.Create(LucyAxeMessage.MessageSource.ThrownAway, base.Top, new Vector2((float)(direction * 7), -2f));
            }
            int num = Item.NewItem(GetItemSource_Misc(4), position, width, height, theItemWeDrop);
            theItemWeDrop.position = Main.item[num].position;
            Main.item[num] = theItemWeDrop;
            theItemWeDrop = new Item();
            if (slot == 58)
            {
                Main.mouseItem = new Item();
            }
            Item item2 = Main.item[num];
            if (Main.netMode == 0)
            {
                item2.noGrabDelay = 100;
            }
            item2.velocity.Y = -2f;
            item2.velocity.X = (float)(4 * direction) + velocity.X;
            item2.favorited = false;
            item2.newAndShiny = false;
            if (((Main.mouseRight && !mouseInterface) || !Main.playerInventory) && Main.mouseItem.type > 0)
            {
                theItemWeDrop = item;
                Main.mouseItem = new Item();
            }
            else
            {
                SetItemAnimation(10);
                JustDroppedAnItem = true;
                DropSelectedItem_InterruptActionsThatUseAnimations();
            }
            Recipe.FindRecipes();
            if (Main.netMode == 1)
            {
                NetMessage.SendData(21, -1, -1, null, num);
            }
        }
    }
References Terraria.Player.controlUseItem, Terraria.GameContent.LucyAxeMessage.Create(), Terraria.Player.delayUseItem, Terraria.Entity.direction, Terraria.Player.DropSelectedItem_InterruptActionsThatUseAnimations(), Terraria.Recipe.FindRecipes(), Terraria.Player.GetItem(), Terraria.GetItemSettings.GetItemInDropItemCheck, Terraria.Player.GetItemSource_Misc(), Terraria.Entity.height, Terraria.Main.item, Terraria.Player.JustDroppedAnItem, Terraria.Player.mouseInterface, Terraria.Main.mouseItem, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Main.playerInventory, Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.Player.SetItemAnimation(), Terraria.Entity.velocity, Terraria.Entity.whoAmI, and Terraria.Entity.width.