TModLoader: Terraria.Player.GetWeaponDamage
GetWeaponDamage()
int Terraria.Player.GetWeaponDamage (Item sItem, bool forTooltip = false) inline
    {
        StatModifier modifier = GetTotalDamage(sItem.DamageType);
        if (AmmoID.Sets.IsArrow[sItem.useAmmo])
        {
            modifier = modifier.CombineWith(arrowDamage);
        }
        if (AmmoID.Sets.IsBullet[sItem.useAmmo])
        {
            modifier = modifier.CombineWith(bulletDamage);
        }
        if (AmmoID.Sets.IsSpecialist[sItem.useAmmo] || ItemID.Sets.IsRangedSpecialistWeapon[sItem.type])
        {
            modifier = modifier.CombineWith(specialistDamage);
        }
        CombinedHooks.ModifyWeaponDamage(this, sItem, ref modifier);
        float baseDamage = sItem.damage;
        if (forTooltip)
        {
            baseDamage *= ItemID.Sets.ToolTipDamageMultiplier[sItem.type];
        }
        return Math.Max(0, (int)(modifier.ApplyTo(baseDamage) + 5E-06f));
    }
References Terraria.Player.arrowDamage, Terraria.Player.bulletDamage, Terraria.Player.GetTotalDamage(), Terraria.ID.AmmoID.Sets.IsArrow, Terraria.ID.AmmoID.Sets.IsBullet, Terraria.ID.ItemID.Sets.IsRangedSpecialistWeapon, Terraria.ID.AmmoID.Sets.IsSpecialist, Terraria.ModLoader.CombinedHooks.ModifyWeaponDamage(), Terraria.Player.specialistDamage, and Terraria.ID.ItemID.Sets.ToolTipDamageMultiplier.
Referenced by Terraria.Projectile.AI_075(), Terraria.Player.ItemCheck_Inner(), Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo(), and Terraria.Player.PickAmmo().