TModLoader: Terraria.Player.GrabItems
GrabItems()
void Terraria.Player.GrabItems (int i) inline private
Definition at line 33598 of file Player.cs.
    {
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        for (int j = 0; j < 400; j++)
        {
            Item item = Main.item[j];
            if (!item.active || item.shimmerTime != 0f || item.noGrabDelay != 0 || item.playerIndexTheItemIsReservedFor != i || !CanAcceptItemIntoInventory(item) || (item.shimmered && !((double)((Vector2)(ref item.velocity)).Length() < 0.2)) || !ItemLoader.CanPickup(item, this))
            {
                continue;
            }
            int itemGrabRange = GetItemGrabRange(item);
            Rectangle hitbox = item.Hitbox;
            Rectangle val = base.Hitbox;
            if (((Rectangle)(ref val)).Intersects(hitbox))
            {
                if (i != Main.myPlayer || (inventory[selectedItem].type == 0 && itemAnimation > 0))
                {
                    continue;
                }
                if (!CombinedHooks.OnPickup(Main.item[j], this))
                {
                    Main.item[j] = new Item();
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(21, -1, -1, null, j);
                    }
                }
                else
                {
                    item = PickupItem(i, j, item);
                }
                continue;
            }
            val = new Rectangle((int)position.X - itemGrabRange, (int)position.Y - itemGrabRange, width + itemGrabRange * 2, height + itemGrabRange * 2);
            if (!((Rectangle)(ref val)).Intersects(hitbox))
            {
                continue;
            }
            ItemSpaceStatus status = ItemSpace(item);
            if (!CanPullItem(item, status))
            {
                continue;
            }
            item.shimmered = false;
            item.beingGrabbed = true;
            bool flag = false;
            if (difficulty == 3 && CreativePowerManager.Instance.GetPower<CreativePowers.FarPlacementRangePower>().IsEnabledForPlayer(whoAmI))
            {
                flag = true;
            }
            if (!ItemLoader.GrabStyle(item, this))
            {
                if (flag)
                {
                    PullItem_Pickup(item, 7f, 1);
                }
                else if (manaMagnet && (item.type == 184 || item.type == 1735 || item.type == 1868))
                {
                    PullItem_Pickup(item, 12f, 5);
                }
                else if (lifeMagnet && (item.type == 58 || item.type == 1734 || item.type == 1867))
                {
                    PullItem_Pickup(item, 15f, 5);
                }
                else if (ItemID.Sets.NebulaPickup[item.type])
                {
                    PullItem_Pickup(item, 12f, 5);
                }
                else if (status.ItemIsGoingToVoidVault)
                {
                    PullItem_ToVoidVault(item);
                }
                else if (goldRing && item.IsACoin)
                {
                    PullItem_Pickup(item, 12f, 5);
                }
                else
                {
                    PullItem_Common(item, 0.75f);
                }
            }
        }
    }
References Terraria.Entity.active, Terraria.Player.CanAcceptItemIntoInventory(), Terraria.ModLoader.ItemLoader.CanPickup(), Terraria.Player.CanPullItem(), Terraria.Player.difficulty, Terraria.Player.GetItemGrabRange(), Terraria.Player.goldRing, Terraria.ModLoader.ItemLoader.GrabStyle(), Terraria.Entity.height, Terraria.Entity.Hitbox, Terraria.GameContent.Creative.CreativePowerManager.Instance, Terraria.Player.inventory, Terraria.Item.IsACoin, Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.IsEnabledForPlayer(), Terraria.Main.item, Terraria.Player.itemAnimation, Terraria.Player.ItemSpaceStatus.ItemIsGoingToVoidVault, Terraria.Player.ItemSpace(), Terraria.Player.lifeMagnet, Terraria.Player.manaMagnet, Terraria.Main.myPlayer, Terraria.ID.ItemID.Sets.NebulaPickup, Terraria.Main.netMode, Terraria.Item.noGrabDelay, Terraria.ModLoader.CombinedHooks.OnPickup(), Terraria.Player.PickupItem(), Terraria.Item.playerIndexTheItemIsReservedFor, Terraria.Entity.position, Terraria.Player.PullItem_Common(), Terraria.Player.PullItem_Pickup(), Terraria.Player.PullItem_ToVoidVault(), Terraria.Player.selectedItem, Terraria.NetMessage.SendData(), Terraria.Item.shimmered, Terraria.Item.shimmerTime, Terraria.Item.type, Terraria.Entity.velocity, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().