TModLoader: Terraria.Player.QuickSpawnItem
QuickSpawnItem() [1/2]
int Terraria.Player.QuickSpawnItem (IEntitySource source, int item, int stack = 1) inline
Spawns an item into the world at this players position. This is a simpler alternative to M:Terraria.Item.NewItem(Terraria.DataStructures.IEntitySource,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Int32,System.Boolean,System.Int32,System.Boolean,System.Boolean). This method can be called from multiplayer client code without necessitating manually syncing the item.
Use M:Terraria.Player.QuickSpawnItem(Terraria.DataStructures.IEntitySource,Terraria.Item,System.Int32) if a specific instance of an Item needs to be spawned into the world to preserve modded data.
Parameters
source
item
stack
Returns
The index of the item within F:Terraria.Main.item
Definition at line 7384 of file Player.cs.
    {
        int number = Item.NewItem(source, (int)position.X, (int)position.Y, width, height, item, stack, noBroadcast: false, -1);
        if (Main.netMode == 1)
        {
            NetMessage.SendData(21, -1, -1, null, number, 1f);
        }
        return number;
    }
References Terraria.Entity.height, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Entity.position, Terraria.NetMessage.SendData(), and Terraria.Entity.width.
Referenced by Terraria.Player.ItemCheck_UseMinecartPowerUp(), Terraria.Player.QuickSpawnItemDirect(), Terraria.Player.TryGettingDevArmor(), and Terraria.ModLoader.Default.ModLoaderMod.TryGettingPatreonOrDevArmor().