TModLoader: Terraria.Player.ItemCheck_OwnerOnlyCode
ItemCheck_OwnerOnlyCode()
void Terraria.Player.ItemCheck_OwnerOnlyCode (ref ItemCheckContext context, Item sItem, int weaponDamage, Rectangle heldItemFrame) inline private
    {
        //IL_04a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_040a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0411: Unknown result type (might be due to invalid IL or missing references)
        //IL_0418: Unknown result type (might be due to invalid IL or missing references)
        //IL_041f: Unknown result type (might be due to invalid IL or missing references)
        //IL_050d: Unknown result type (might be due to invalid IL or missing references)
        //IL_04df: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_053f: Unknown result type (might be due to invalid IL or missing references)
        //IL_054a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0556: Unknown result type (might be due to invalid IL or missing references)
        //IL_0568: Unknown result type (might be due to invalid IL or missing references)
        bool flag = true;
        int type = sItem.type;
        if ((type == 65 || type == 676 || type == 723 || type == 724 || type == 757 || type == 674 || type == 675 || type == 989 || type == 1226 || type == 1227) && !ItemAnimationJustStarted)
        {
            flag = false;
        }
        if (type == 5097 && ItemAnimationJustStarted)
        {
            _batbatCanHeal = true;
        }
        if (type == 5094 && ItemAnimationJustStarted)
        {
            _spawnTentacleSpikes = true;
        }
        if (type == 795 && ItemAnimationJustStarted)
        {
            _spawnBloodButcherer = true;
        }
        if (type == 121 && ItemAnimationJustStarted)
        {
            _spawnVolcanoExplosion = true;
        }
        if (type == 155 && ItemAnimationJustStarted)
        {
            _spawnMuramasaCut = true;
        }
        if (type == 3852 && altFunctionUse == 2 && !ItemAnimationJustStarted)
        {
            flag = false;
        }
        if (type == 5451 && ownedProjectileCounts[1020] > 0)
        {
            flag = false;
        }
        if (sItem.useLimitPerAnimation.HasValue && ItemUsesThisAnimation >= sItem.useLimitPerAnimation.Value)
        {
            flag = false;
        }
        ItemCheck_TurretAltFeatureUse(sItem, flag);
        ItemCheck_MinionAltFeatureUse(sItem, flag);
        bool flag2 = itemAnimation > 0 && ItemTimeIsZero && flag;
        if (sItem.shootsEveryUse)
        {
            flag2 = ItemAnimationJustStarted;
        }
        if (sItem.shoot > 0 && flag2)
        {
            ItemCheck_Shoot(whoAmI, sItem, weaponDamage);
        }
        if (whoAmI != Main.myPlayer)
        {
            return;
        }
        ItemCheck_UseWiringTools(sItem);
        ItemCheck_UseLawnMower(sItem);
        ItemCheck_PlayInstruments(sItem);
        ItemCheck_UseBuckets(sItem);
        if (!channel)
        {
            toolTime = itemTime;
        }
        else
        {
            toolTime--;
            if (toolTime < 0)
            {
                toolTime = CombinedHooks.TotalUseTime(sItem.useTime, this, sItem);
            }
        }
        ItemCheck_TryDestroyingDrones(sItem);
        ItemCheck_UseMiningTools(sItem);
        ItemCheck_UseTeleportRod(sItem);
        ItemCheck_UseLifeCrystal(sItem);
        ItemCheck_UseLifeFruit(sItem);
        ItemCheck_UseManaCrystal(sItem);
        ItemCheck_UseDemonHeart(sItem);
        ItemCheck_UseMinecartPowerUp(sItem);
        ItemCheck_UseTorchGodsFavor(sItem);
        ItemCheck_UseArtisanLoaf(sItem);
        ItemCheck_UseEventItems(sItem);
        ItemCheck_UseBossSpawners(whoAmI, sItem);
        ItemCheck_UseCombatBook(sItem);
        ItemCheck_UsePeddlersSatchel(sItem);
        ItemCheck_UsePetLicenses(sItem);
        ItemCheck_UseShimmerPermanentItems(sItem);
        if (sItem.type == 4095 && itemAnimation == 2)
        {
            Main.LocalGolfState.ResetGolfBall();
        }
        PlaceThing(ref context);
        if (sItem.makeNPC > 0)
        {
            if (!Main.GamepadDisableCursorItemIcon && position.X / 16f - (float)tileRangeX - (float)sItem.tileBoost <= (float)tileTargetX && (position.X + (float)width) / 16f + (float)tileRangeX + (float)sItem.tileBoost - 1f >= (float)tileTargetX && position.Y / 16f - (float)tileRangeY - (float)sItem.tileBoost <= (float)tileTargetY && (position.Y + (float)height) / 16f + (float)tileRangeY + (float)sItem.tileBoost - 2f >= (float)tileTargetY)
            {
                cursorItemIconEnabled = true;
                Main.ItemIconCacheUpdate(sItem.type);
            }
            if (ItemTimeIsZero && itemAnimation > 0 && controlUseItem)
            {
                ItemCheck_ReleaseCritter(sItem);
            }
        }
        if (boneGloveItem != null && !boneGloveItem.IsAir && boneGloveTimer == 0 && itemAnimation > 0 && sItem.damage > 0)
        {
            boneGloveTimer = 60;
            Vector2 center = base.Center;
            Vector2 vector = DirectionTo(ApplyRangeCompensation(0.2f, center, Main.MouseWorld)) * 10f;
            Projectile.NewProjectile(GetProjectileSource_Accessory(boneGloveItem), center.X, center.Y, vector.X, vector.Y, 532, 25, 5f, whoAmI);
        }
        if (((sItem.damage < 0 || sItem.type <= 0 || sItem.noMelee) && sItem.type != 1450 && !ItemID.Sets.CatchingTool[sItem.type] && sItem.type != 3542 && sItem.type != 3779) || itemAnimation <= 0)
        {
            return;
        }
        ItemCheck_GetMeleeHitbox(sItem, heldItemFrame, out var dontAttack, out var itemRectangle);
        if (!dontAttack)
        {
            itemRectangle = ItemCheck_EmitUseVisuals(sItem, itemRectangle);
            if (Main.myPlayer == whoAmI && ItemID.Sets.CatchingTool[sItem.type])
            {
                itemRectangle = ItemCheck_CatchCritters(sItem, itemRectangle);
            }
            if (sItem.type == 3183 || sItem.type == 4821)
            {
                bool[] shouldIgnore = ItemCheck_GetTileCutIgnoreList(sItem);
                ItemCheck_CutTiles(sItem, itemRectangle, shouldIgnore);
            }
            if (sItem.damage > 0)
            {
                UpdateMeleeHitCooldowns();
                float knockBack = GetWeaponKnockback(sItem, sItem.knockBack);
                bool[] shouldIgnore2 = ItemCheck_GetTileCutIgnoreList(sItem);
                ItemCheck_CutTiles(sItem, itemRectangle, shouldIgnore2);
                ItemCheck_MeleeHitNPCs(sItem, itemRectangle, weaponDamage, knockBack);
                ItemCheck_MeleeHitPVP(sItem, itemRectangle, weaponDamage, knockBack);
                ItemCheck_EmitHammushProjectiles(whoAmI, sItem, itemRectangle, weaponDamage);
            }
        }
    }
References Terraria.Player._batbatCanHeal, Terraria.Player._spawnBloodButcherer, Terraria.Player._spawnMuramasaCut, Terraria.Player._spawnTentacleSpikes, Terraria.Player._spawnVolcanoExplosion, Terraria.Player.altFunctionUse, Terraria.Player.ApplyRangeCompensation(), Terraria.Player.boneGloveItem, Terraria.Player.boneGloveTimer, Terraria.ID.ItemID.Sets.CatchingTool, Terraria.Player.channel, Terraria.Player.controlUseItem, Terraria.Player.cursorItemIconEnabled, Terraria.Entity.DirectionTo(), Terraria.Main.GamepadDisableCursorItemIcon, Terraria.Player.GetProjectileSource_Accessory(), Terraria.Player.GetWeaponKnockback(), Terraria.Entity.height, Terraria.Item.IsAir, Terraria.Player.itemAnimation, Terraria.Player.ItemAnimationJustStarted, Terraria.Player.ItemCheck_CatchCritters(), Terraria.Player.ItemCheck_CutTiles(), Terraria.Player.ItemCheck_EmitHammushProjectiles(), Terraria.Player.ItemCheck_EmitUseVisuals(), Terraria.Player.ItemCheck_GetMeleeHitbox(), Terraria.Player.ItemCheck_GetTileCutIgnoreList(), Terraria.Player.ItemCheck_MeleeHitNPCs(), Terraria.Player.ItemCheck_MeleeHitPVP(), Terraria.Player.ItemCheck_MinionAltFeatureUse(), Terraria.Player.ItemCheck_PlayInstruments(), Terraria.Player.ItemCheck_ReleaseCritter(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_TryDestroyingDrones(), Terraria.Player.ItemCheck_TurretAltFeatureUse(), Terraria.Player.ItemCheck_UseArtisanLoaf(), Terraria.Player.ItemCheck_UseBossSpawners(), Terraria.Player.ItemCheck_UseBuckets(), Terraria.Player.ItemCheck_UseCombatBook(), Terraria.Player.ItemCheck_UseDemonHeart(), Terraria.Player.ItemCheck_UseEventItems(), Terraria.Player.ItemCheck_UseLawnMower(), Terraria.Player.ItemCheck_UseLifeCrystal(), Terraria.Player.ItemCheck_UseLifeFruit(), Terraria.Player.ItemCheck_UseManaCrystal(), Terraria.Player.ItemCheck_UseMinecartPowerUp(), Terraria.Player.ItemCheck_UseMiningTools(), Terraria.Player.ItemCheck_UsePeddlersSatchel(), Terraria.Player.ItemCheck_UsePetLicenses(), Terraria.Player.ItemCheck_UseShimmerPermanentItems(), Terraria.Player.ItemCheck_UseTeleportRod(), Terraria.Player.ItemCheck_UseTorchGodsFavor(), Terraria.Player.ItemCheck_UseWiringTools(), Terraria.Main.ItemIconCacheUpdate(), Terraria.Player.itemTime, Terraria.Player.ItemTimeIsZero, Terraria.Player.ItemUsesThisAnimation, Terraria.Main.LocalGolfState, Terraria.Main.MouseWorld, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Player.ownedProjectileCounts, Terraria.Player.PlaceThing(), Terraria.Entity.position, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Player.toolTime, Terraria.ModLoader.CombinedHooks.TotalUseTime(), Terraria.Player.UpdateMeleeHitCooldowns(), Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.ItemCheck_Inner().