TModLoader: Terraria.Player.ItemCheck_EmitDrinkParticles
ItemCheck_EmitDrinkParticles()
void Terraria.Player.ItemCheck_EmitDrinkParticles (Item sItem) inline private
    {
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        if (itemAnimation < 1)
        {
            return;
        }
        Color[] array = ItemID.Sets.DrinkParticleColors[sItem.type];
        if (array != null && array.Length != 0)
        {
            Vector2? mouthPosition = MouthPosition;
            if (mouthPosition.HasValue)
            {
                Vector2 val = mouthPosition.Value + Main.rand.NextVector2Square(-4f, 4f);
                Vector2 spinningpoint = default(Vector2);
                ((Vector2)(ref spinningpoint))._002Ector((float)direction * 0.1f, (0f - gravDir) * 0.1f);
                Dust.NewDustPerfect(val, 284, 1.3f * spinningpoint.RotatedBy(-(float)Math.PI / 5f * Main.rand.NextFloatDirection()), 0, array[Main.rand.Next(array.Length)] * 0.7f, 0.8f + 0.2f * Main.rand.NextFloat()).fadeIn = 0f;
            }
        }
    }
References Terraria.Entity.direction, Terraria.ID.ItemID.Sets.DrinkParticleColors, Terraria.Player.gravDir, Terraria.Player.itemAnimation, Terraria.Player.MouthPosition, Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), and Terraria.Main.rand.
Referenced by Terraria.Player.ItemCheck_Inner().