TModLoader: Terraria.Player.ItemCheck_UseBuckets
ItemCheck_UseBuckets()
void Terraria.Player.ItemCheck_UseBuckets (Item sItem) inline private
    {
        if (((sItem.type < 205 || sItem.type > 207) && sItem.type != 1128 && sItem.type != 3031 && sItem.type != 3032 && sItem.type != 4820 && sItem.type != 4872 && sItem.type != 5302 && sItem.type != 5303 && sItem.type != 5304 && sItem.type != 5364) || noBuilding || !(position.X / 16f - (float)tileRangeX - (float)sItem.tileBoost <= (float)tileTargetX) || !((position.X + (float)width) / 16f + (float)tileRangeX + (float)sItem.tileBoost - 1f >= (float)tileTargetX) || !(position.Y / 16f - (float)tileRangeY - (float)sItem.tileBoost <= (float)tileTargetY) || !((position.Y + (float)height) / 16f + (float)tileRangeY + (float)sItem.tileBoost - 2f >= (float)tileTargetY))
        {
            return;
        }
        if (!Main.GamepadDisableCursorItemIcon)
        {
            cursorItemIconEnabled = true;
            Main.ItemIconCacheUpdate(sItem.type);
        }
        if (!ItemTimeIsZero || itemAnimation <= 0 || !controlUseItem)
        {
            return;
        }
        Tile tile;
        if (sItem.type == 205)
        {
            tile = Main.tile[tileTargetX, tileTargetY];
            if (!tile.shimmer())
            {
                goto IL_027d;
            }
        }
        if (sItem.type == 3032)
        {
            tile = Main.tile[tileTargetX, tileTargetY];
            if (tile.liquidType() == 0)
            {
                goto IL_027d;
            }
        }
        if (sItem.type == 3032)
        {
            tile = Main.tile[tileTargetX, tileTargetY];
            if (tile.shimmer())
            {
                goto IL_027d;
            }
        }
        if (sItem.type == 4872)
        {
            tile = Main.tile[tileTargetX, tileTargetY];
            if (tile.lava())
            {
                goto IL_027d;
            }
        }
        if (sItem.type == 5303)
        {
            tile = Main.tile[tileTargetX, tileTargetY];
            if (tile.honey())
            {
                goto IL_027d;
            }
        }
        if (sItem.type != 5304)
        {
            tile = Main.tile[tileTargetX, tileTargetY];
            if (tile.liquid >= 200)
            {
                return;
            }
            tile = Main.tile[tileTargetX, tileTargetY];
            if (tile.nactive())
            {
                bool[] tileSolid = Main.tileSolid;
                tile = Main.tile[tileTargetX, tileTargetY];
                if (tileSolid[tile.type])
                {
                    bool[] tileSolidTop = Main.tileSolidTop;
                    tile = Main.tile[tileTargetX, tileTargetY];
                    if (!tileSolidTop[tile.type])
                    {
                        tile = Main.tile[tileTargetX, tileTargetY];
                        if (tile.type != 546)
{
                            return;
                        }
                    }
                }
            }
            if (sItem.type == 207 || sItem.type == 4820)
            {
                tile = Main.tile[tileTargetX, tileTargetY];
                if (tile.liquid != 0)
                {
                    tile = Main.tile[tileTargetX, tileTargetY];
                    if (tile.liquidType() != 1)
                    {
                        return;
                    }
                }
                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                tile = Main.tile[tileTargetX, tileTargetY];
                tile.liquidType(1);
                tile = Main.tile[tileTargetX, tileTargetY];
                tile.liquid = byte.MaxValue;
                WorldGen.SquareTileFrame(tileTargetX, tileTargetY);
                if (sItem.type != 4820)
                {
                    sItem.stack--;
                    PutItemInInventoryFromItemUsage(205, selectedItem);
                }
                ApplyItemTime(sItem);
                if (Main.netMode == 1)
                {
                    NetMessage.sendWater(tileTargetX, tileTargetY);
                }
            }
            else if (sItem.type == 206 || sItem.type == 3031)
            {
                tile = Main.tile[tileTargetX, tileTargetY];
                if (tile.liquid != 0)
                {
                    tile = Main.tile[tileTargetX, tileTargetY];
                    if (tile.liquidType() != 0)
                    {
                        return;
                    }
                }
                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                tile = Main.tile[tileTargetX, tileTargetY];
                tile.liquidType(0);
                tile = Main.tile[tileTargetX, tileTargetY];
                tile.liquid = byte.MaxValue;
                WorldGen.SquareTileFrame(tileTargetX, tileTargetY);
                if (sItem.type != 3031)
                {
                    sItem.stack--;
                    PutItemInInventoryFromItemUsage(205, selectedItem);
                }
                ApplyItemTime(sItem);
                if (Main.netMode == 1)
                {
                    NetMessage.sendWater(tileTargetX, tileTargetY);
                }
            }
            else if (sItem.type == 1128 || sItem.type == 5302)
            {
                tile = Main.tile[tileTargetX, tileTargetY];
                if (tile.liquid != 0)
                {
                    tile = Main.tile[tileTargetX, tileTargetY];
                    if (tile.liquidType() != 2)
                    {
                        return;
                    }
                }
                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                tile = Main.tile[tileTargetX, tileTargetY];
                tile.liquidType(2);
                tile = Main.tile[tileTargetX, tileTargetY];
                tile.liquid = byte.MaxValue;
                WorldGen.SquareTileFrame(tileTargetX, tileTargetY);
                if (sItem.type != 5302)
                {
                    sItem.stack--;
                    PutItemInInventoryFromItemUsage(205, selectedItem);
                }
                ApplyItemTime(sItem);
                if (Main.netMode == 1)
                {
                    NetMessage.sendWater(tileTargetX, tileTargetY);
                }
            }
            else
            {
                if (sItem.type != 5364)
                {
                    return;
                }
                tile = Main.tile[tileTargetX, tileTargetY];
                if (tile.liquid != 0)
                {
                    tile = Main.tile[tileTargetX, tileTargetY];
                    if (tile.liquidType() != 3)
                    {
                        return;
                    }
                }
                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                tile = Main.tile[tileTargetX, tileTargetY];
                tile.liquidType(3);
                tile = Main.tile[tileTargetX, tileTargetY];
                tile.liquid = byte.MaxValue;
                WorldGen.SquareTileFrame(tileTargetX, tileTargetY);
                ApplyItemTime(sItem);
                if (Main.netMode == 1)
                {
                    NetMessage.sendWater(tileTargetX, tileTargetY);
                }
            }
            return;
        }
        goto IL_027d;
        IL_027d:
        tile = Main.tile[tileTargetX, tileTargetY];
        int num = tile.liquidType();
        int num2 = 0;
        for (int i = tileTargetX - 1; i <= tileTargetX + 1; i++)
        {
            for (int j = tileTargetY - 1; j <= tileTargetY + 1; j++)
            {
                tile = Main.tile[i, j];
                if (tile.liquidType() == num)
                {
                    int num5 = num2;
                    tile = Main.tile[i, j];
                    num2 = num5 + tile.liquid;
                }
            }
        }
        tile = Main.tile[tileTargetX, tileTargetY];
        if (tile.liquid <= 0 || (num2 <= 100 && sItem.type != 3032 && sItem.type != 4872 && sItem.type != 5303 && sItem.type != 5304))
        {
            return;
        }
        tile = Main.tile[tileTargetX, tileTargetY];
        int liquidType = tile.liquidType();
        if (sItem.type != 3032 && sItem.type != 4872 && sItem.type != 5303 && sItem.type != 5304)
        {
            tile = Main.tile[tileTargetX, tileTargetY];
            if (tile.honey() && sItem.type == 205)
            {
                sItem.stack--;
                PutItemInInventoryFromItemUsage(1128, selectedItem);
            }
            else
            {
                tile = Main.tile[tileTargetX, tileTargetY];
                if (tile.lava() && sItem.type == 205)
                {
                    sItem.stack--;
                    PutItemInInventoryFromItemUsage(207, selectedItem);
                }
                else
                {
                    tile = Main.tile[tileTargetX, tileTargetY];
                    if (tile.shimmer() && sItem.type == 205)
                    {
                        return;
                    }
                    sItem.stack--;
                    PutItemInInventoryFromItemUsage(206, selectedItem);
                }
            }
        }
        SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
        ApplyItemTime(sItem);
        tile = Main.tile[tileTargetX, tileTargetY];
        int num3 = tile.liquid;
        tile = Main.tile[tileTargetX, tileTargetY];
        tile.liquid = 0;
        tile = Main.tile[tileTargetX, tileTargetY];
        tile.lava(lava: false);
        tile = Main.tile[tileTargetX, tileTargetY];
        tile.honey(honey: false);
        WorldGen.SquareTileFrame(tileTargetX, tileTargetY, resetFrame: false);
        if (Main.netMode == 1)
        {
            NetMessage.sendWater(tileTargetX, tileTargetY);
        }
        else
        {
            Liquid.AddWater(tileTargetX, tileTargetY);
        }
        if (num3 >= 255)
        {
            return;
        }
        for (int k = tileTargetX - 1; k <= tileTargetX + 1; k++)
        {
            for (int l = tileTargetY - 1; l <= tileTargetY + 1; l++)
            {
                if (k == tileTargetX && l == tileTargetY)
                {
                    continue;
                }
                tile = Main.tile[k, l];
                if (tile.liquid <= 0)
                {
                    continue;
                }
                tile = Main.tile[k, l];
                if (tile.liquidType() == num)
                {
                    tile = Main.tile[k, l];
                    int num4 = tile.liquid;
                    if (num4 + num3 > 255)
                    {
                        num4 = 255 - num3;
                    }
                    num3 += num4;
                    tile = Main.tile[k, l];
                    tile.liquid -= (byte)num4;
                    tile = Main.tile[k, l];
                    tile.liquidType(liquidType);
                    tile = Main.tile[k, l];
                    if (tile.liquid == 0)
                    {
                        tile = Main.tile[k, l];
                        tile.lava(lava: false);
                        tile = Main.tile[k, l];
                        tile.honey(honey: false);
                    }
                    WorldGen.SquareTileFrame(k, l, resetFrame: false);
                    if (Main.netMode == 1)
                    {
                        NetMessage.sendWater(k, l);
                    }
                    else
                    {
                        Liquid.AddWater(k, l);
                    }
                }
            }
        }
    }
References Terraria.Liquid.AddWater(), Terraria.Player.ApplyItemTime(), Terraria.Player.controlUseItem, Terraria.Player.cursorItemIconEnabled, Terraria.Main.GamepadDisableCursorItemIcon, Terraria.Entity.height, Terraria.Player.honey, Terraria.Tile.honey(), Terraria.Player.itemAnimation, Terraria.Main.ItemIconCacheUpdate(), Terraria.Player.ItemTimeIsZero, Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Player.noBuilding, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Player.PutItemInInventoryFromItemUsage(), Terraria.Player.selectedItem, Terraria.NetMessage.sendWater(), Terraria.Tile.shimmer(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Tile.type, and Terraria.Entity.width.
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode().