TModLoader: Terraria.Player.GetGrapplingForces
GetGrapplingForces()
void Terraria.Player.GetGrapplingForces (Vector2 fromPosition, out int? preferredPlayerDirectionToSet, out float preferedPlayerVelocityX, out float preferedPlayerVelocityY) inline private
Definition at line 20611 of file Player.cs.
    {
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0363: Unknown result type (might be due to invalid IL or missing references)
        //IL_0364: Unknown result type (might be due to invalid IL or missing references)
        //IL_0368: Unknown result type (might be due to invalid IL or missing references)
        //IL_0375: Unknown result type (might be due to invalid IL or missing references)
        //IL_0113: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01de: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_020c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_0137: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_023c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_0225: Unknown result type (might be due to invalid IL or missing references)
        //IL_022c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0164: Unknown result type (might be due to invalid IL or missing references)
        //IL_0169: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0280: Unknown result type (might be due to invalid IL or missing references)
        //IL_0288: Unknown result type (might be due to invalid IL or missing references)
        float num = 0f;
        float num3 = 0f;
        preferredPlayerDirectionToSet = null;
        int num4 = 0;
        Vector2 vector = default(Vector2);
        for (int i = 0; i < grapCount; i++)
        {
            Projectile projectile = Main.projectile[grappling[i]];
            if (projectile.ai[0] != 2f || projectile.position.HasNaNs())
            {
                continue;
            }
            int type = projectile.type;
            int num11;
            if (projectile.ModProjectile != null)
            {
                num11 = ((projectile.ModProjectile.AIType > 0) ? 1 : 0);
                if (num11 != 0)
                {
                    projectile.type = projectile.ModProjectile.AIType;
                }
            }
            else
            {
                num11 = 0;
            }
            num += projectile.position.X + (float)(projectile.width / 2);
            num3 += projectile.position.Y + (float)(projectile.height / 2);
            num4++;
            if (projectile.type == 446)
            {
                ((Vector2)(ref vector))._002Ector((float)(controlRight.ToInt() - controlLeft.ToInt()), (float)(controlDown.ToInt() - controlUp.ToInt()) * gravDir);
                if (vector != Vector2.Zero)
                {
                    ((Vector2)(ref vector)).Normalize();
                }
                vector *= 100f;
                Vector2 vec = Vector2.Normalize(base.Center - projectile.Center + vector);
                if (vec.HasNaNs())
                {
                    vec = -Vector2.UnitY;
                }
                float num5 = 200f;
                num += vec.X * num5;
                num3 += vec.Y * num5;
            }
            else if (projectile.type == 652)
            {
                Vector2 vector2 = Utils.SafeNormalize(new Vector2((float)(controlRight.ToInt() - controlLeft.ToInt()), (float)(controlDown.ToInt() - controlUp.ToInt()) * gravDir), Vector2.Zero);
                Vector2 vector3 = projectile.Center - base.Center;
                Vector2 vector4 = vector3.SafeNormalize(Vector2.Zero);
                Vector2 value = Vector2.Zero;
                if (vector2 != Vector2.Zero)
                {
                    value = vector4 * Vector2.Dot(vector4, vector2);
                }
                float num6 = 6f;
                if (Vector2.Dot(value, vector3) < 0f && ((Vector2)(ref vector3)).Length() >= 600f)
                {
                    num6 = 0f;
                }
                num += 0f - vector3.X + value.X * num6;
                num3 += 0f - vector3.Y + value.Y * num6;
            }
            else if (projectile.type == 865)
            {
                Vector2 vector5 = (projectile.rotation - (float)Math.PI / 2f).ToRotationVector2().SafeNormalize(Vector2.UnitY);
                Vector2 vector6 = -vector5 * 28f;
                num += vector6.X;
                num3 += vector6.Y;
                if (vector5.X != 0f)
                {
                    preferredPlayerDirectionToSet = Math.Sign(vector5.X);
                }
            }
            if (num11 != 0)
            {
                projectile.type = type;
            }
            ProjectileLoader.GrappleTargetPoint(projectile, this, ref num, ref num3);
        }
        if (num4 == 0)
        {
            preferedPlayerVelocityX = velocity.X;
            preferedPlayerVelocityY = velocity.Y;
            return;
        }
        float num7 = num / (float)num4;
        float num8 = num3 / (float)num4;
        preferedPlayerVelocityX = num7 - fromPosition.X;
        preferedPlayerVelocityY = num8 - fromPosition.Y;
        float num9 = (float)Math.Sqrt(preferedPlayerVelocityX * preferedPlayerVelocityX + preferedPlayerVelocityY * preferedPlayerVelocityY);
        float num10 = 11f;
        if (Main.projectile[grappling[0]].type == 315)
        {
            num10 = 14f;
        }
        if (Main.projectile[grappling[0]].type == 487)
        {
            num10 = 12f;
        }
        if (Main.projectile[grappling[0]].type >= 646 && Main.projectile[grappling[0]].type <= 649)
        {
            num10 = 16f;
        }
        ProjectileLoader.GrapplePullSpeed(Main.projectile[grappling[0]], this, ref num10);
        float num2 = num9;
        num2 = ((!(num9 > num10)) ? 1f : (num10 / num9));
        preferedPlayerVelocityX *= num2;
        preferedPlayerVelocityY *= num2;
    }
References Terraria.Projectile.ai, Terraria.ModLoader.ModProjectile.AIType, Terraria.Entity.Center, Terraria.Player.controlDown, Terraria.Player.controlLeft, Terraria.Player.controlRight, Terraria.Player.controlUp, Terraria.Player.grapCount, Terraria.ModLoader.ProjectileLoader.GrapplePullSpeed(), Terraria.ModLoader.ProjectileLoader.GrappleTargetPoint(), Terraria.Player.grappling, Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Projectile.ModProjectile, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Utils.SafeNormalize(), Terraria.Projectile.type, Terraria.Entity.velocity, and Terraria.Entity.width.
Referenced by Terraria.Player.GrappleMovement().