TModLoader: Terraria.Player.HorizontalMovement
HorizontalMovement()
void Terraria.Player.HorizontalMovement () inline
    {
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_040f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0414: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1193: Unknown result type (might be due to invalid IL or missing references)
        //IL_1198: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_045e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0464: Unknown result type (might be due to invalid IL or missing references)
        //IL_046e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0473: Unknown result type (might be due to invalid IL or missing references)
        //IL_124a: Unknown result type (might be due to invalid IL or missing references)
        //IL_124f: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_10bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0979: Unknown result type (might be due to invalid IL or missing references)
        //IL_0807: Unknown result type (might be due to invalid IL or missing references)
        //IL_080d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0817: Unknown result type (might be due to invalid IL or missing references)
        //IL_081c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0556: Unknown result type (might be due to invalid IL or missing references)
        //IL_055c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0566: Unknown result type (might be due to invalid IL or missing references)
        //IL_056b: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1301: Unknown result type (might be due to invalid IL or missing references)
        //IL_1306: Unknown result type (might be due to invalid IL or missing references)
        //IL_12a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0905: Unknown result type (might be due to invalid IL or missing references)
        //IL_090f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0914: Unknown result type (might be due to invalid IL or missing references)
        //IL_0851: Unknown result type (might be due to invalid IL or missing references)
        //IL_0857: Unknown result type (might be due to invalid IL or missing references)
        //IL_0861: Unknown result type (might be due to invalid IL or missing references)
        //IL_0866: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_13bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_135d: Unknown result type (might be due to invalid IL or missing references)
        //IL_094c: Unknown result type (might be due to invalid IL or missing references)
        //IL_089e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1415: Unknown result type (might be due to invalid IL or missing references)
        //IL_112c: Unknown result type (might be due to invalid IL or missing references)
        if (chilled)
        {
            accRunSpeed = maxRunSpeed;
        }
        bool flag = (itemAnimation == 0 || inventory[selectedItem].useTurn) && mount.AllowDirectionChange;
        bool flag2 = controlLeft || controlRight;
        float num = (accRunSpeed + maxRunSpeed) / 2f;
        float num2 = 0f;
        bool flag3 = false;
        if (flag2 && mount.Active && mount.Type == 43 && velocity.Y == 0f && !controlJump)
        {
            SoundEngine.PlaySound(in SoundID.Item168, base.Center);
            float num3 = jumpSpeed * gravDir * 0.5f;
            if (num3 < 2f)
            {
                num3 = 2f;
            }
            num3 += 0.01f;
            velocity.Y = 0f - num3;
            jump = jumpHeight;
            fullRotation = 0f;
            return;
        }
        if (windPushed && !isLockedToATile && !(mount.Active && velocity.Y == 0f && flag2))
        {
            num2 = (float)Math.Sign(Main.windSpeedCurrent) * 0.06f;
            if (Math.Abs(Main.windSpeedCurrent) > 0.5f)
            {
                num2 *= 1.37f;
            }
            if (velocity.Y != 0f)
            {
                num2 *= 1.5f;
            }
            if (flag2)
            {
                num2 *= 0.8f;
                float num4 = 0.072f;
                num2 = MathHelper.Clamp(num2, 0f - num4, num4);
            }
            flag3 = true;
            if (Math.Sign(direction) != Math.Sign(num2))
            {
                num -= Math.Abs(num2) * 40f;
            }
        }
        if (trackBoost != 0f)
        {
            velocity.X += trackBoost;
            trackBoost = 0f;
            if (velocity.X < 0f)
            {
                if (velocity.X < 0f - maxRunSpeed)
                {
                    velocity.X = 0f - maxRunSpeed;
                }
            }
            else if (velocity.X > maxRunSpeed)
            {
                velocity.X = maxRunSpeed;
            }
        }
        if (controlLeft && velocity.X > 0f - maxRunSpeed)
        {
            if (!mount.Active || !mount.Cart || velocity.Y == 0f)
            {
                if (velocity.X > runSlowdown)
                {
                    velocity.X -= runSlowdown;
                }
                velocity.X -= runAcceleration;
            }
            if (onWrongGround)
            {
                if (velocity.X < 0f - runSlowdown)
                {
                    velocity.X += runSlowdown;
                }
                else
                {
                    velocity.X = 0f;
                }
            }
            if (mount.Active && mount.Cart && !onWrongGround)
            {
                if (velocity.X < 0f && flag)
                {
                    direction = -1;
                }
                else if (itemAnimation <= 0 && velocity.Y == 0f)
                {
                    SoundEngine.PlaySound(SoundID.Item55, (int)position.X + width / 2, (int)position.Y + height / 2);
                    DelegateMethods.Minecart.rotation = fullRotation;
                    DelegateMethods.Minecart.rotationOrigin = fullRotationOrigin;
                    if ((double)Math.Abs(velocity.X) > (double)maxRunSpeed * 0.66)
                    {
                        if (Main.rand.Next(2) == 0)
{
                            Minecart.WheelSparks(mount.Delegations.MinecartDust, position + velocity * 0.66f, width, height, 1);
                        }
                        if (Main.rand.Next(2) == 0)
{
                            Minecart.WheelSparks(mount.Delegations.MinecartDust, position + velocity * 0.33f, width, height, 1);
                        }
                        if (Main.rand.Next(2) == 0)
{
                            Minecart.WheelSparks(mount.Delegations.MinecartDust, position, width, height, 1);
                        }
                    }
                    else if ((double)Math.Abs(velocity.X) > (double)maxRunSpeed * 0.33)
                    {
                        if (Main.rand.Next(3) != 0)
{
                            Minecart.WheelSparks(mount.Delegations.MinecartDust, position + velocity * 0.5f, width, height, 1);
                        }
                        if (Main.rand.Next(3) != 0)
{
                            Minecart.WheelSparks(mount.Delegations.MinecartDust, position, width, height, 1);
                        }
                    }
                    else
                    {
                        Minecart.WheelSparks(mount.Delegations.MinecartDust, position, width, height, 1);
                    }
                }
            }
            else if (!sandStorm && (itemAnimation == 0 || inventory[selectedItem].useTurn) && mount.AllowDirectionChange)
            {
                direction = -1;
            }
        }
        else if (controlRight && velocity.X < maxRunSpeed)
        {
            if (!mount.Active || !mount.Cart || velocity.Y == 0f)
            {
                if (velocity.X < 0f - runSlowdown)
                {
                    velocity.X += runSlowdown;
                }
                velocity.X += runAcceleration;
            }
            if (onWrongGround)
            {
                if (velocity.X > runSlowdown)
                {
                    velocity.X -= runSlowdown;
                }
                else
                {
                    velocity.X = 0f;
                }
            }
            if (mount.Active && mount.Cart && !onWrongGround)
            {
                if (velocity.X > 0f && flag)
                {
                    direction = 1;
                }
                else if (itemAnimation <= 0 && velocity.Y == 0f)
                {
                    SoundEngine.PlaySound(SoundID.Item55, (int)position.X + width / 2, (int)position.Y + height / 2);
                    DelegateMethods.Minecart.rotation = fullRotation;
                    DelegateMethods.Minecart.rotationOrigin = fullRotationOrigin;
                    if ((double)Math.Abs(velocity.X) > (double)maxRunSpeed * 0.66)
                    {
                        if (Main.rand.Next(2) == 0)
{
                            Minecart.WheelSparks(mount.Delegations.MinecartDust, position + velocity * 0.66f, width, height, 1);
                        }
                        if (Main.rand.Next(2) == 0)
{
                            Minecart.WheelSparks(mount.Delegations.MinecartDust, position + velocity * 0.33f, width, height, 1);
                        }
                        if (Main.rand.Next(2) == 0)
{
                            Minecart.WheelSparks(mount.Delegations.MinecartDust, position, width, height, 1);
                        }
                    }
                    else if ((double)Math.Abs(velocity.X) > (double)maxRunSpeed * 0.33)
                    {
                        if (Main.rand.Next(3) != 0)
{
                            Minecart.WheelSparks(mount.Delegations.MinecartDust, position + velocity * 0.5f, width, height, 1);
                        }
                        if (Main.rand.Next(3) != 0)
{
                            Minecart.WheelSparks(mount.Delegations.MinecartDust, position, width, height, 1);
                        }
                    }
                    else
                    {
                        Minecart.WheelSparks(mount.Delegations.MinecartDust, position, width, height, 1);
                    }
                }
            }
            else if (!sandStorm && (itemAnimation == 0 || inventory[selectedItem].useTurn) && mount.AllowDirectionChange)
            {
                direction = 1;
            }
        }
        else if (controlLeft && velocity.X > 0f - accRunSpeed && dashDelay >= 0)
        {
            if (mount.Active && mount.Cart)
            {
                if (velocity.X < 0f)
                {
                    direction = -1;
                }
            }
            else if ((itemAnimation == 0 || inventory[selectedItem].useTurn) && mount.AllowDirectionChange)
            {
                direction = -1;
            }
            if (velocity.Y == 0f || wingsLogic > 0 || mount.CanFly())
            {
                if (velocity.X > runSlowdown)
                {
                    velocity.X -= runSlowdown;
                }
                velocity.X -= runAcceleration * 0.2f;
                if (wingsLogic > 0)
                {
                    velocity.X -= runAcceleration * 0.2f;
                }
            }
            if (onWrongGround)
            {
                if (velocity.X < runSlowdown)
                {
                    velocity.X += runSlowdown;
                }
                else
                {
                    velocity.X = 0f;
                }
            }
            if (velocity.X < 0f - num && velocity.Y == 0f && !mount.Active)
            {
                SpawnFastRunParticles();
            }
        }
        else if (controlRight && velocity.X < accRunSpeed && dashDelay >= 0)
        {
            if (mount.Active && mount.Cart)
            {
                if (velocity.X > 0f)
                {
                    direction = -1;
                }
            }
            else if ((itemAnimation == 0 || inventory[selectedItem].useTurn) && mount.AllowDirectionChange)
            {
                direction = 1;
            }
            if (velocity.Y == 0f || wingsLogic > 0 || mount.CanFly())
            {
                if (velocity.X < 0f - runSlowdown)
                {
                    velocity.X += runSlowdown;
                }
                velocity.X += runAcceleration * 0.2f;
                if (wingsLogic > 0)
                {
                    velocity.X += runAcceleration * 0.2f;
                }
            }
            if (onWrongGround)
            {
                if (velocity.X > runSlowdown)
                {
                    velocity.X -= runSlowdown;
                }
                else
                {
                    velocity.X = 0f;
                }
            }
            if (velocity.X > num && velocity.Y == 0f && !mount.Active)
            {
                SpawnFastRunParticles();
            }
        }
        else if (mount.Active && mount.Cart && Math.Abs(velocity.X) >= 1f)
        {
            if (onWrongGround)
            {
                if (velocity.X > 0f)
                {
                    if (velocity.X > runSlowdown)
                    {
                        velocity.X -= runSlowdown;
                    }
                    else
                    {
                        velocity.X = 0f;
                    }
                }
                else if (velocity.X < 0f)
                {
                    if (velocity.X < 0f - runSlowdown)
                    {
                        velocity.X += runSlowdown;
                    }
                    else
                    {
                        velocity.X = 0f;
                    }
                }
            }
            if (velocity.X > maxRunSpeed)
            {
                velocity.X = maxRunSpeed;
            }
            if (velocity.X < 0f - maxRunSpeed)
            {
                velocity.X = 0f - maxRunSpeed;
            }
        }
        else if (velocity.Y == 0f)
        {
            if (velocity.X > runSlowdown)
            {
                velocity.X -= runSlowdown;
            }
            else if (velocity.X < 0f - runSlowdown)
            {
                velocity.X += runSlowdown;
            }
            else
            {
                velocity.X = 0f;
            }
        }
        else if (!PortalPhysicsEnabled)
        {
            if ((double)velocity.X > (double)runSlowdown * 0.5)
            {
                velocity.X -= runSlowdown * 0.5f;
            }
            else if ((double)velocity.X < (double)(0f - runSlowdown) * 0.5)
            {
                velocity.X += runSlowdown * 0.5f;
            }
            else
            {
                velocity.X = 0f;
            }
        }
        if (flag3)
        {
            if (num2 < 0f && velocity.X > num2)
            {
                velocity.X += num2;
                if (velocity.X < num2)
                {
                    velocity.X = num2;
                }
            }
            if (num2 > 0f && velocity.X < num2)
            {
                velocity.X += num2;
                if (velocity.X > num2)
                {
                    velocity.X = num2;
                }
            }
        }
        bool flag4 = mount.Type == 40 || mount.Type == 41 || mount.Type == 42;
        if (mount.Active && (mount.Type == 10 || mount.Type == 47 || flag4) && Math.Abs(velocity.X) > mount.DashSpeed - mount.RunSpeed / 2f)
        {
            Rectangle rect = getRect();
            if (direction == 1)
            {
                ((Rectangle)(ref rect)).Offset(width - 1, 0);
            }
            rect.Width = 2;
            ((Rectangle)(ref rect)).Inflate(6, 12);
            int num5 = 60;
            if (flag4)
            {
                num5 = 30;
            }
            float damage = GetTotalDamage(DamageClass.Summon).ApplyTo(num5);
            float knockback = 10f;
            if (flag4)
            {
                knockback = 7f;
            }
            int nPCImmuneTime = 30;
            int playerImmuneTime = 6;
            CollideWithNPCs(rect, damage, knockback, nPCImmuneTime, playerImmuneTime, DamageClass.Summon);
        }
        if (mount.Active && mount.Type == 44 && Math.Abs(velocity.X) > mount.DashSpeed - mount.RunSpeed / 4f)
        {
            Rectangle rect2 = getRect();
            if (direction == 1)
            {
                ((Rectangle)(ref rect2)).Offset(width - 1, 0);
            }
            rect2.Width = 2;
            ((Rectangle)(ref rect2)).Inflate(6, 12);
            float damage2 = GetTotalDamage(DamageClass.Summon).ApplyTo(100f);
            float knockback2 = 12f;
            int nPCImmuneTime2 = 30;
            int playerImmuneTime2 = 6;
            CollideWithNPCs(rect2, damage2, knockback2, nPCImmuneTime2, playerImmuneTime2, DamageClass.Summon);
        }
        if (mount.Active && mount.Type == 45 && Math.Abs(velocity.X) > mount.DashSpeed * 0.9f)
        {
            Rectangle rect3 = getRect();
            if (direction == 1)
            {
                ((Rectangle)(ref rect3)).Offset(width - 1, 0);
            }
            rect3.Width = 2;
            ((Rectangle)(ref rect3)).Inflate(6, 12);
            float damage3 = GetTotalDamage(DamageClass.Summon).ApplyTo(120f);
            float knockback3 = 12f;
            int nPCImmuneTime3 = 30;
            int playerImmuneTime3 = 6;
            CollideWithNPCs(rect3, damage3, knockback3, nPCImmuneTime3, playerImmuneTime3, DamageClass.Summon);
        }
        if (mount.Active && mount.Type == 14 && Math.Abs(velocity.X) > mount.RunSpeed / 2f)
        {
            Rectangle rect4 = getRect();
            if (direction == 1)
            {
                ((Rectangle)(ref rect4)).Offset(width - 1, 0);
            }
            rect4.Width = 2;
            ((Rectangle)(ref rect4)).Inflate(6, 12);
            float damage4 = GetTotalDamage(DamageClass.Summon).ApplyTo(90f);
            float knockback4 = 10f;
            int nPCImmuneTime4 = 30;
            int playerImmuneTime4 = 6;
            CollideWithNPCs(rect4, damage4, knockback4, nPCImmuneTime4, playerImmuneTime4, DamageClass.Summon);
        }
        if (mount.Active && mount.Type == 17 && Math.Abs(velocity.X) > mount.RunSpeed / 2f)
        {
            Rectangle rect5 = getRect();
            if (direction == 1)
            {
                ((Rectangle)(ref rect5)).Offset(width - 1, 0);
            }
            rect5.Width = 2;
            ((Rectangle)(ref rect5)).Inflate(6, 12);
            float damage5 = GetTotalDamage(DamageClass.Summon).ApplyTo(40f);
            float knockback5 = 10f;
            int nPCImmuneTime5 = 30;
            int playerImmuneTime5 = 12;
            CollideWithNPCs(rect5, damage5, knockback5, nPCImmuneTime5, playerImmuneTime5, DamageClass.Summon);
        }
        TryUsingDiggerCart();
        if (HeldItem.type == 4049 && whoAmI == Main.myPlayer)
        {
            MowTheLawn();
        }
    }
References Terraria.Player.accRunSpeed, Terraria.Mount.Active, Terraria.Mount.AllowDirectionChange, Terraria.ModLoader.StatModifier.ApplyTo(), Terraria.Mount.CanFly(), Terraria.Mount.Cart, Terraria.Player.chilled, Terraria.Player.CollideWithNPCs(), Terraria.Player.controlJump, Terraria.Player.controlLeft, Terraria.Player.controlRight, Terraria.Player.dashDelay, Terraria.Mount.DashSpeed, Terraria.Mount.Delegations, Terraria.Entity.direction, Terraria.Player.fullRotation, Terraria.Player.fullRotationOrigin, Terraria.Player.getRect(), Terraria.Player.GetTotalDamage(), Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Player.HeldItem, Terraria.Player.inventory, Terraria.Player.isLockedToATile, Terraria.ID.SoundID.Item168, Terraria.ID.SoundID.Item55, Terraria.Player.itemAnimation, Terraria.Player.jump, Terraria.Player.jumpHeight, Terraria.Player.jumpSpeed, Terraria.Player.maxRunSpeed, Terraria.Mount.MountDelegatesData.MinecartDust, Terraria.Player.mount, Terraria.Player.MowTheLawn(), Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Player.onWrongGround, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.PortalPhysicsEnabled, Terraria.Entity.position, Terraria.Main.rand, Terraria.Player.runAcceleration, Terraria.Player.runSlowdown, Terraria.Mount.RunSpeed, Terraria.Player.sandStorm, Terraria.Player.selectedItem, Terraria.Player.SpawnFastRunParticles(), Terraria.ModLoader.DamageClass.Summon, Terraria.Player.trackBoost, Terraria.Player.TryUsingDiggerCart(), Terraria.Item.type, Terraria.Mount.Type, Terraria.Item.useTurn, Terraria.Entity.velocity, Terraria.Minecart.WheelSparks(), Terraria.Entity.whoAmI, Terraria.Entity.width, Terraria.Player.windPushed, Terraria.Main.windSpeedCurrent, and Terraria.Player.wingsLogic.
Referenced by Terraria.Player.Update().