TModLoader: Terraria.Player.SpawnMinionOnCursor
SpawnMinionOnCursor()
int Terraria.Player.SpawnMinionOnCursor (IEntitySource projectileSource, int ownerIndex, int minionProjectileId, int originalDamageNotScaledByMinionDamage, float KnockBack, Vector2 offsetFromCursor = default(Vector2), Vector2 velocityOnSpawn = default(Vector2)) inline
Definition at line 50101 of file Player.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        Vector2 pointPoisition = Main.MouseWorld;
        pointPoisition += offsetFromCursor;
        LimitPointToPlayerReachableArea(ref pointPoisition);
        float ai = 0f;
        if (projectileSource is EntitySource_ItemUse entitySource_ItemUse)
        {
            switch (entitySource_ItemUse.Item.type)
            {
            case 1157:
                ai = 60f;
                break;
            case 2364:
            case 2365:
            case 2535:
            case 2621:
            case 2749:
            case 3474:
                ai = 1f;
                break;
            }
        }
        int num = Projectile.NewProjectile(projectileSource, pointPoisition, velocityOnSpawn, minionProjectileId, originalDamageNotScaledByMinionDamage, KnockBack, ownerIndex, 0f, ai);
        Main.projectile[num].originalDamage = originalDamageNotScaledByMinionDamage;
        return num;
    }
References Terraria.Player.LimitPointToPlayerReachableArea(), Terraria.Main.MouseWorld, Terraria.Projectile.NewProjectile(), Terraria.Projectile.originalDamage, and Terraria.Main.projectile.
Referenced by Terraria.Player.ItemCheck_Shoot().