TModLoader: Terraria.Player.CheckCrackedBrickBreak
CheckCrackedBrickBreak()
void Terraria.Player.CheckCrackedBrickBreak () inline
    {
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0174: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0181: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0244: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        if (shimmering)
        {
            return;
        }
        bool flag = false;
        if ((float)Main.rand.Next(2, 12) < Math.Abs(velocity.X))
        {
            flag = true;
        }
        if ((float)Main.rand.Next(2, 12) < velocity.Y)
        {
            flag = true;
        }
        if (flag && velocity.Y < 1f)
        {
            Point point = (base.Bottom + Vector2.UnitY).ToTileCoordinates();
            Point point2 = (base.BottomLeft + Vector2.UnitY).ToTileCoordinates();
            Point point3 = (base.BottomRight + Vector2.UnitY).ToTileCoordinates();
            if ((WorldGen.SolidTileAllowBottomSlope(point.X, point.Y) && !TileID.Sets.CrackedBricks[Main.tile[point.X, point.Y].type]) || (WorldGen.SolidTileAllowBottomSlope(point2.X, point2.Y) && !TileID.Sets.CrackedBricks[Main.tile[point2.X, point2.Y].type]) || (WorldGen.SolidTileAllowBottomSlope(point3.X, point3.Y) && !TileID.Sets.CrackedBricks[Main.tile[point3.X, point3.Y].type]))
            {
                flag = false;
            }
        }
        if (!flag)
        {
            return;
        }
        Vector2 vector = position + velocity;
        flag = false;
        int num = (int)(vector.X / 16f);
        int num2 = (int)((vector.X + (float)width) / 16f);
        int num3 = (int)((position.Y + (float)height + 1f) / 16f);
        Rectangle rect = getRect();
        ((Rectangle)(ref rect)).Inflate(1, 1);
        for (int i = num; i <= num2; i++)
        {
            for (int j = num3; j <= num3 + 1 && Main.tile[i, j] != null; j++)
            {
                if (!Main.tile[i, j].nactive() || WorldGen.SolidTile(i, j - 1) || !TileID.Sets.CrackedBricks[Main.tile[i, j].type])
                {
                    continue;
                }
                Rectangle val = new Rectangle(i * 16, j * 16, 16, 16);
                if (((Rectangle)(ref val)).Intersects(rect))
                {
                    flag = true;
                    if (velocity.Y > 1f)
                    {
                        velocity.Y = 1f;
                    }
                    NetMessage.SendData(13, -1, -1, null, whoAmI);
                }
            }
        }
        if (!flag)
        {
            return;
        }
        num = (int)((vector.X - 16f - 8f) / 16f);
        num2 = (int)((vector.X + (float)width + 16f + 8f) / 16f);
        for (int k = num; k <= num2; k++)
        {
            for (int l = num3; l <= num3 + 2; l++)
            {
                if (Main.tile[k, l].nactive() && !WorldGen.SolidTile(k, l - 1) && TileID.Sets.CrackedBricks[Main.tile[k, l].type])
                {
                    WorldGen.KillTile(k, l);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(17, -1, -1, null, 20, k, l);
                    }
                }
            }
        }
    }
References Terraria.ID.TileID.Sets.CrackedBricks, Terraria.Player.getRect(), Terraria.Entity.height, Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Player.shimmering, Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.Main.tile, Terraria.Entity.velocity, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().