TModLoader: Terraria.Player.BuffHandle_SpawnPetIfNeeded
BuffHandle_SpawnPetIfNeeded()
void Terraria.Player.BuffHandle_SpawnPetIfNeeded (ref bool petBool, int petProjID, int buffIndex) inline
    {
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        petBool = true;
        bool flag = true;
        if (ownedProjectileCounts[petProjID] > 0)
        {
            flag = false;
        }
        Vector2 center = base.Center;
        if (buffType[buffIndex] == 341)
        {
            float num = 10f;
            center = ((petProjID != 934) ? (center - new Vector2(num * (float)direction, 0f)) : (center + new Vector2(num * (float)direction, 0f)));
        }
        if (flag && whoAmI == Main.myPlayer)
        {
            Projectile.NewProjectile(GetProjectileSource_Buff(buffIndex), center.X, center.Y, 0f, 0f, petProjID, 0, 0f, whoAmI);
        }
    }
References Terraria.Player.buffType, Terraria.Entity.direction, Terraria.Player.GetProjectileSource_Buff(), Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Player.ownedProjectileCounts, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.BuffHandle_SpawnPetIfNeededAndSetTime().