TModLoader: Terraria.Player.CheckForGoodTeleportationSpot
CheckForGoodTeleportationSpot()
Vector2 Terraria.Player.CheckForGoodTeleportationSpot (ref bool canSpawn, int teleportStartX, int teleportRangeX, int teleportStartY, int teleportRangeY, RandomTeleportationAttemptSettings settings) inline
    {
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_053a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0271: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_020d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0413: Unknown result type (might be due to invalid IL or missing references)
        //IL_041d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0422: Unknown result type (might be due to invalid IL or missing references)
        //IL_0424: Unknown result type (might be due to invalid IL or missing references)
        //IL_0426: Unknown result type (might be due to invalid IL or missing references)
        //IL_0428: Unknown result type (might be due to invalid IL or missing references)
        //IL_042d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0444: Unknown result type (might be due to invalid IL or missing references)
        //IL_0449: Unknown result type (might be due to invalid IL or missing references)
        //IL_0455: Unknown result type (might be due to invalid IL or missing references)
        //IL_045a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0464: Unknown result type (might be due to invalid IL or missing references)
        //IL_0469: Unknown result type (might be due to invalid IL or missing references)
        //IL_046b: Unknown result type (might be due to invalid IL or missing references)
        //IL_046d: Unknown result type (might be due to invalid IL or missing references)
        //IL_046f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0474: Unknown result type (might be due to invalid IL or missing references)
        //IL_048b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0490: Unknown result type (might be due to invalid IL or missing references)
        //IL_049c: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_04af: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04db: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0511: Unknown result type (might be due to invalid IL or missing references)
        //IL_0516: Unknown result type (might be due to invalid IL or missing references)
        int num = 0;
        int num2 = 0;
        int num3 = 0;
        int num4 = width;
        Vector2 vector = new Vector2((float)num2, (float)num3) * 16f + new Vector2((float)(-num4 / 2 + 8), (float)(-height));
        while (!canSpawn && num < settings.attemptsBeforeGivingUp)
        {
            num++;
            num2 = teleportStartX + Main.rand.Next(teleportRangeX);
            num3 = teleportStartY + Main.rand.Next(teleportRangeY);
            int num5 = 5;
            num2 = (int)MathHelper.Clamp((float)num2, (float)num5, (float)(Main.maxTilesX - num5));
            num3 = (int)MathHelper.Clamp((float)num3, (float)num5, (float)(Main.maxTilesY - num5));
            vector = new Vector2((float)num2, (float)num3) * 16f + new Vector2((float)(-num4 / 2 + 8), (float)(-height));
            if (Collision.SolidCollision(vector, num4, height))
            {
                continue;
            }
            if (Main.tile[num2, num3] == null)
            {
                Main.tile[num2, num3] = default(Tile);
            }
            if ((settings.avoidWalls && Main.tile[num2, num3].wall > 0) || (Main.tile[num2, num3].wall == 87 && (double)num3 > Main.worldSurface && !NPC.downedPlantBoss) || (Main.wallDungeon[Main.tile[num2, num3].wall] && (double)num3 > Main.worldSurface && !NPC.downedBoss3))
            {
                continue;
            }
            int num6 = 0;
            while (num6 < settings.maximumFallDistanceFromOrignalPoint)
            {
                if (Main.tile[num2, num3 + num6] == null)
                {
                    Main.tile[num2, num3 + num6] = default(Tile);
                }
                Tile tile = Main.tile[num2, num3 + num6];
                vector = new Vector2((float)num2, (float)(num3 + num6)) * 16f + new Vector2((float)(-num4 / 2 + 8), (float)(-height));
                Collision.SlopeCollision(vector, velocity, num4, height, gravDir);
                if (!Collision.SolidCollision(vector, num4, height))
                {
                    num6++;
                    continue;
                }
                if (tile.active() && !tile.inActive() && Main.tileSolid[tile.type])
                {
                    break;
                }
                num6++;
            }
            vector.Y -= 16f;
            int i = (int)vector.X / 16;
            int j = (int)vector.Y / 16;
            int num7 = (int)(vector.X + (float)num4 * 0.5f) / 16;
            int j2 = (int)(vector.Y + (float)height) / 16;
            Tile tileSafely = Framing.GetTileSafely(i, j);
            Tile tileSafely2 = Framing.GetTileSafely(num7, j2);
            if (settings.avoidAnyLiquid && tileSafely2.liquid > 0)
            {
                continue;
            }
            if (settings.mostlySolidFloor)
            {
                Tile tileSafely3 = Framing.GetTileSafely(num7 - 1, j2);
                Tile tileSafely4 = Framing.GetTileSafely(num7 + 1, j2);
                if (!tileSafely3.active() || tileSafely3.inActive() || !Main.tileSolid[tileSafely3.type] || Main.tileSolidTop[tileSafely3.type] || !tileSafely4.active() || tileSafely4.inActive() || !Main.tileSolid[tileSafely4.type] || Main.tileSolidTop[tileSafely4.type])
                {
                    continue;
                }
            }
            if ((settings.avoidWalls && tileSafely.wall > 0) || (settings.avoidAnyLiquid && Collision.WetCollision(vector, num4, height)) || (settings.avoidLava && Collision.LavaCollision(vector, num4, height)) || (settings.avoidHurtTiles && Collision.AnyHurtingTiles(vector, num4, height)) || Collision.SolidCollision(vector, num4, height) || num6 >= settings.maximumFallDistanceFromOrignalPoint - 1)
            {
                continue;
            }
            Vector2 vector2 = Vector2.UnitX * 16f;
            if (Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: false, fall2: false, (int)gravDir) != vector2)
            {
                continue;
            }
            vector2 = -Vector2.UnitX * 16f;
            if (Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: false, fall2: false, (int)gravDir) != vector2)
            {
                continue;
            }
            vector2 = Vector2.UnitY * 16f;
            if (!(Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: false, fall2: false, (int)gravDir) != vector2))
            {
                vector2 = -Vector2.UnitY * 16f;
                if (!(Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: false, fall2: false, (int)gravDir) != vector2))
                {
                    canSpawn = true;
                    num3 += num6;
                    break;
                }
            }
        }
        return vector;
    }
References Terraria.Tile.active(), Terraria.Collision.AnyHurtingTiles(), Terraria.NPC.downedBoss3, Terraria.NPC.downedPlantBoss, Terraria.Framing.GetTileSafely(), Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Tile.inActive(), Terraria.Collision.LavaCollision(), Terraria.Main.rand, Terraria.Collision.SlopeCollision(), Terraria.Collision.SolidCollision(), Terraria.Main.tile, Terraria.Collision.TileCollision(), Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Terraria.Entity.velocity, Terraria.Main.wallDungeon, Terraria.Collision.WetCollision(), Terraria.Entity.width, and Terraria.Main.worldSurface.
Referenced by Terraria.Player.DemonConch(), and Terraria.Player.TeleportationPotion().