TModLoader: Terraria.Player.GetAnglerReward
GetAnglerReward()
void Terraria.Player.GetAnglerReward (NPC angler, int questItemType) inline
Definition at line 57224 of file Player.cs.
    {
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        EntitySource_Gift source = new EntitySource_Gift(angler);
        int questsDone = anglerQuestsFinished;
        float anglerRewardRarityMultiplier = GetAnglerRewardRarityMultiplier(questsDone);
        anglerRewardRarityMultiplier *= (float)(currentShoppingSettings.PriceAdjustment + 1.0) / 2f;
        List<Item> rewardItems = new List<Item>();
        GetItemSettings anglerRewardSettings = GetItemSettings.NPCEntityToPlayerInventorySettings;
        GetAnglerReward_MainReward(rewardItems, source, questsDone, anglerRewardRarityMultiplier, questItemType, ref anglerRewardSettings);
        GetAnglerReward_Decoration(rewardItems, source, questsDone, anglerRewardRarityMultiplier, ref anglerRewardSettings);
        GetAnglerReward_Money(rewardItems, source, questsDone, anglerRewardRarityMultiplier, ref anglerRewardSettings);
        GetAnglerReward_Bait(rewardItems, source, questsDone, anglerRewardRarityMultiplier, ref anglerRewardSettings);
        PlayerLoader.AnglerQuestReward(this, anglerRewardRarityMultiplier, rewardItems);
        foreach (Item rewardItem in rewardItems)
        {
            rewardItem.position = base.Center;
            Item getItem = GetItem(whoAmI, rewardItem, GetItemSettings.NPCEntityToPlayerInventorySettings);
            if (getItem.stack > 0)
            {
                int number = Item.NewItem(source, (int)position.X, (int)position.Y, width, height, getItem.type, getItem.stack, noBroadcast: false, 0, noGrabDelay: true);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number, 1f);
                }
            }
        }
    }
References Terraria.ModLoader.PlayerLoader.AnglerQuestReward(), Terraria.Player.anglerQuestsFinished, Terraria.Player.currentShoppingSettings, Terraria.Player.GetAnglerReward_Bait(), Terraria.Player.GetAnglerReward_Decoration(), Terraria.Player.GetAnglerReward_MainReward(), Terraria.Player.GetAnglerReward_Money(), Terraria.Player.GetAnglerRewardRarityMultiplier(), Terraria.Player.GetItem(), Terraria.Entity.height, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.GetItemSettings.NPCEntityToPlayerInventorySettings, Terraria.Entity.position, Terraria.ShoppingSettings.PriceAdjustment, Terraria.NetMessage.SendData(), Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Main.GUIChatDrawInner().