TModLoader: Terraria.Player.UpdateStormTigerStatus
UpdateStormTigerStatus()
void Terraria.Player.UpdateStormTigerStatus () inline private
Definition at line 10279 of file Player.cs.
    {
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e0: Unknown result type (might be due to invalid IL or missing references)
        int num = GetDesiredStormTigerMinionRank() switch
        {
            1 => 833,
            2 => 834,
            3 => 835,
            _ => -1,
        };
        bool flag = false;
        if (num == -1)
        {
            flag = true;
        }
        for (int i = 0; i < ProjectileID.Sets.StormTigerIds.Length; i++)
        {
            int num2 = ProjectileID.Sets.StormTigerIds[i];
            if (num2 != num && ownedProjectileCounts[num2] >= 1)
            {
                flag = true;
                break;
            }
        }
        if (flag)
        {
            for (int j = 0; j < 1000; j++)
            {
                Projectile projectile = Main.projectile[j];
                if (projectile.active && projectile.owner == whoAmI && projectile.type != num && ProjectileID.Sets.StormTiger[projectile.type])
                {
                    projectile.Kill();
                }
            }
        }
        else if (ownedProjectileCounts[num] < 1)
        {
            int num3 = Projectile.NewProjectile(GetProjectileSource_Misc(13), base.Center, Vector2.Zero, num, 0, 0f, whoAmI, 0f, 1f);
            Main.projectile[num3].localAI[0] = 60f;
        }
    }
References Terraria.Entity.active, Terraria.Player.GetDesiredStormTigerMinionRank(), Terraria.Player.GetProjectileSource_Misc(), Terraria.Projectile.Kill(), Terraria.Projectile.NewProjectile(), Terraria.Player.ownedProjectileCounts, Terraria.Projectile.owner, Terraria.Main.projectile, Terraria.ID.ProjectileID.Sets.StormTiger, Terraria.ID.ProjectileID.Sets.StormTigerIds, Terraria.Projectile.type, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.UpdateBuffs().