TModLoader: Terraria.Player.GetFarthestSpawnPositionOnLine
GetFarthestSpawnPositionOnLine()
Vector2 Terraria.Player.GetFarthestSpawnPositionOnLine (Vector2 startPos, float speedX, float speedY) inline
Definition at line 50046 of file Player.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        Vector2 pointPoisition = Main.ReverseGravitySupport(Main.MouseScreen) + Main.screenPosition;
        LimitPointToPlayerReachableArea(ref pointPoisition);
        int num = 0;
        Vector2 val = new Vector2(speedX, speedY);
        float num2 = ((Vector2)(ref val)).Length();
        val = pointPoisition - startPos;
        float num3 = ((Vector2)(ref val)).Length();
        Vector2 center = base.Center;
        center.X += direction * 16;
        while (Collision.CanHitLine(center, 0, 0, startPos, 0, 0))
        {
            num++;
            startPos.X += speedX;
            startPos.Y += speedY;
            val = startPos - pointPoisition;
            if (((Vector2)(ref val)).Length() < 20f + Math.Abs(speedX) + Math.Abs(speedY))
            {
                startPos = pointPoisition;
                break;
            }
            if (num2 * (float)num >= num3)
            {
                startPos = pointPoisition;
                break;
            }
        }
        return startPos;
    }
References Terraria.Collision.CanHitLine(), Terraria.Entity.direction, Terraria.Player.LimitPointToPlayerReachableArea(), Terraria.Main.MouseScreen, Terraria.Main.ReverseGravitySupport(), and Terraria.Main.screenPosition.
Referenced by Terraria.Player.ItemCheck_Shoot().