TModLoader: Terraria.Player.ResetEffects
ResetEffects()
void Terraria.Player.ResetEffects () inline
Definition at line 16711 of file Player.cs.
    {
        if (extraAccessory && (Main.expertMode || Main.gameMenu))
        {
            extraAccessorySlots = 1;
        }
        else
        {
            extraAccessorySlots = 0;
        }
        if (shimmering)
        {
            shimmerTransparency += 0.015f;
            if (shimmerTransparency > 0.8f)
            {
                shimmerTransparency = 0.8f;
            }
        }
        else if (shimmerTransparency > 0f)
        {
            if (shimmerTransparency == 0.8f)
            {
                SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 3);
            }
            shimmerTransparency -= 0.015f;
            if (shimmerTransparency < 0f)
            {
                shimmerTransparency = 0f;
            }
        }
        shimmering = false;
        fairyBoots = false;
        hellfireTreads = false;
        moonLordLegs = false;
        flowerBoots = false;
        arcticDivingGear = false;
        noBuilding = false;
        strongBees = false;
        ashWoodBonus = false;
        shroomiteStealth = false;
        statDefense = DefenseStat.Default;
        DefenseEffectiveness = MultipliableFloat.One * VanillaBaseDefenseEffectiveness();
        accWatch = 0;
        accCompass = 0;
        accDepthMeter = 0;
        accDivingHelm = false;
        canFloatInWater = false;
        lifeRegen = 0;
        manaCost = 1f;
        hasFootball = false;
        drawingFootball = false;
        minionKB = 0f;
        moveSpeed = 1f;
        boneArmor = false;
        honey = false;
        frostArmor = false;
        rocketBoots = 0;
        vanityRocketBoots = 0;
        fireWalk = false;
        noKnockback = false;
        jumpBoost = false;
        frogLegJumpBoost = false;
        skyStoneEffects = false;
        noFallDmg = false;
        spawnMax = false;
        spaceGun = false;
        killGuide = false;
        killClothier = false;
        lavaImmune = false;
        gills = false;
        slowFall = false;
        findTreasure = false;
        biomeSight = false;
        invis = false;
        nightVision = false;
        enemySpawns = false;
        hasTitaniumStormBuff = false;
        thorns = 0f;
        aggro = 0;
        waterWalk = false;
        waterWalk2 = false;
        detectCreature = false;
        gravControl = false;
        if (forcedGravity > 0)
        {
            forcedGravity--;
        }
        honeyCombItem = null;
        gravControl2 = false;
        PlayerLoader.ModifyMaxStats(this);
        statLifeMax2 = statLifeMax;
        statManaMax2 = statManaMax;
        chloroAmmoCost80 = false;
        huntressAmmoCost90 = false;
        ammoCost80 = false;
        ammoCost75 = false;
        ThrownCost50 = false;
        ThrownCost33 = false;
        ThrownVelocity = 1f;
        manaRegenBuff = false;
        hasCreditsSceneMusicBox = false;
        arrowDamage = StatModifier.Default;
        bulletDamage = StatModifier.Default;
        specialistDamage = StatModifier.Default;
        coolWhipBuff = false;
        yoraiz0rEye = 0;
        yoraiz0rDarkness = false;
        hasFloatingTube = false;
        hasUnicornHorn = false;
        hasAngelHalo = false;
        hasRainbowCursor = false;
        leinforsHair = false;
        overrideFishingBobber = -1;
        suspiciouslookingTentacle = false;
        crimsonHeart = false;
        lightOrb = false;
        blueFairy = false;
        redFairy = false;
        greenFairy = false;
        wisp = false;
        bunny = false;
        turtle = false;
        eater = false;
        trident = false;
        skeletron = false;
        hornet = false;
        zephyrfish = false;
        tiki = false;
        lizard = false;
        parrot = false;
        sapling = false;
        cSapling = false;
        truffle = false;
        yoyoGlove = false;
        counterWeight = 0;
        stringColor = 0;
        yoyoString = false;
        shadowDodge = false;
        palladiumRegen = false;
        chaosState = false;
        onHitDodge = false;
        onHitRegen = false;
        onHitPetal = false;
        iceBarrier = false;
        onHitTitaniumStorm = false;
        maxMinions = 1;
        maxTurrets = 1;
        ammoBox = false;
        ammoPotion = false;
        penguin = false;
        sporeSac = false;
        shinyStone = false;
        empressBrooch = false;
        volatileGelatin = false;
        hasMagiluminescence = false;
        shadowArmor = false;
        if (Main.dontStarveWorld && Main.remixWorld)
        {
            dontStarveShader = false;
        }
        else
        {
            dontStarveShader = Main.dontStarveWorld;
        }
        eyebrellaCloud = false;
        stardustMonolithShader = false;
        nebulaMonolithShader = false;
        vortexMonolithShader = false;
        solarMonolithShader = false;
        moonLordMonolithShader = false;
        bloodMoonMonolithShader = false;
        shimmerMonolithShader = false;
        dd2Accessory = false;
        magicLantern = false;
        rabid = false;
        sunflower = false;
        wellFed = false;
        inferno = false;
        manaMagnet = false;
        lifeMagnet = false;
        treasureMagnet = false;
        chiselSpeed = false;
        lifeForce = false;
        dangerSense = false;
        endurance = 0f;
        whipRangeMultiplier = 1f;
        calmed = false;
        beetleOrbs = 0;
        beetleBuff = false;
        miniMinotaur = false;
        goldRing = false;
        solarShields = 0;
        GoingDownWithGrapple = false;
        fishingSkill = 0;
        cratePotion = false;
        sonarPotion = false;
        accTackleBox = false;
        accFishingBobber = false;
        accFishingLine = false;
        accLavaFishing = false;
        accFishFinder = false;
        accWeatherRadio = false;
        accThirdEye = false;
        InfoAccMechShowWires = false;
        accJarOfSouls = false;
        accCalendar = false;
        accStopwatch = false;
        accOreFinder = false;
        accCritterGuide = false;
        accDreamCatcher = false;
        wallSpeed = 1f;
        tileSpeed = 1f;
        autoPaint = false;
        autoActuator = false;
        petFlagKingSlimePet = false;
        petFlagEyeOfCthulhuPet = false;
        petFlagEaterOfWorldsPet = false;
        petFlagBrainOfCthulhuPet = false;
        petFlagSkeletronPet = false;
        petFlagQueenBeePet = false;
        petFlagDestroyerPet = false;
        petFlagTwinsPet = false;
        petFlagSkeletronPrimePet = false;
        petFlagPlanteraPet = false;
        petFlagGolemPet = false;
        petFlagDukeFishronPet = false;
        petFlagLunaticCultistPet = false;
        petFlagMoonLordPet = false;
        petFlagFairyQueenPet = false;
        petFlagPumpkingPet = false;
        petFlagEverscreamPet = false;
        petFlagIceQueenPet = false;
        petFlagMartianPet = false;
        petFlagDD2OgrePet = false;
        petFlagDD2BetsyPet = false;
        petFlagQueenSlimePet = false;
        petFlagVoltBunny = false;
        petFlagShadowMimic = false;
        petFlagBabyWerewolf = false;
        petFlagDynamiteKitten = false;
        petFlagPlantero = false;
        petFlagBabyRedPanda = false;
        petFlagLilHarpy = false;
        petFlagFennecFox = false;
        petFlagGlitteryButterfly = false;
        petFlagBabyImp = false;
        petFlagBabyShark = false;
        petFlagUpbeatStar = false;
        petFlagDD2Gato = false;
        petFlagDD2Dragon = false;
        petFlagDD2Ghost = false;
        petFlagBerniePet = false;
        petFlagGlommerPet = false;
        petFlagDeerclopsPet = false;
        petFlagPigPet = false;
        petFlagChesterPet = false;
        petFlagJunimoPet = false;
        petFlagBlueChickenPet = false;
        petFlagSpiffo = false;
        petFlagCaveling = false;
        petFlagDirtiestBlock = false;
        companionCube = false;
        petFlagSugarGlider = false;
        babyFaceMonster = false;
        manaSick = false;
        puppy = false;
        grinch = false;
        blackCat = false;
        spider = false;
        squashling = false;
        magicCuffs = false;
        coldDash = false;
        desertDash = false;
        desertBoots = false;
        sailDash = false;
        cordage = false;
        magicQuiver = false;
        shimmerImmune = false;
        hasMoltenQuiver = false;
        magmaStone = false;
        hasRaisableShield = false;
        lavaRose = false;
        eyeSpring = false;
        snowman = false;
        scope = false;
        panic = false;
        brainOfConfusionItem = null;
        dino = false;
        crystalLeaf = false;
        pygmy = false;
        raven = false;
        slime = false;
        hornetMinion = false;
        impMinion = false;
        twinsMinion = false;
        spiderMinion = false;
        pirateMinion = false;
        sharknadoMinion = false;
        stardustMinion = false;
        batsOfLight = false;
        babyBird = false;
        stormTiger = false;
        flinxMinion = false;
        abigailMinion = false;
        smolstar = false;
        empressBlade = false;
        stardustGuardian = false;
        stardustDragon = false;
        UFOMinion = false;
        DeadlySphereMinion = false;
        chilled = false;
        tipsy = false;
        dazed = false;
        frozen = false;
        stoned = false;
        webbed = false;
        ichor = false;
        manaRegenBonus = 0;
        manaRegenDelayBonus = 0f;
        carpet = false;
        iceSkate = false;
        dashType = 0;
        spikedBoots = 0;
        blackBelt = false;
        lavaMax = 0;
        archery = false;
        poisoned = false;
        venom = false;
        blind = false;
        blackout = false;
        onFire = false;
        dripping = false;
        hungry = false;
        heartyMeal = false;
        starving = false;
        drippingSlime = false;
        drippingSparkleSlime = false;
        burned = false;
        suffocating = false;
        onFire2 = false;
        onFire3 = false;
        onFrostBurn = false;
        onFrostBurn2 = false;
        frostBurn = false;
        noItems = false;
        cursed = false;
        blockRange = 0;
        pickSpeed = 1f;
        wereWolf = false;
        rulerGrid = false;
        rulerLine = true;
        bleed = false;
        confused = false;
        witheredArmor = false;
        witheredWeapon = false;
        parryDamageBuff = false;
        slowOgreSpit = false;
        wings = 0;
        wingsLogic = 0;
        equippedWings = null;
        wingTimeMax = 0;
        brokenArmor = false;
        silence = false;
        slow = false;
        gross = false;
        tongued = false;
        kbGlove = false;
        autoReuseGlove = false;
        meleeScaleGlove = false;
        remoteVisionForDrone = false;
        kbBuff = false;
        starCloakItem = null;
        starCloakItem_manaCloakOverrideItem = null;
        starCloakItem_starVeilOverrideItem = null;
        starCloakItem_beeCloakOverrideItem = null;
        longInvince = false;
        pStone = false;
        manaFlower = false;
        crimsonRegen = false;
        ghostHeal = false;
        ghostHurt = false;
        turtleArmor = false;
        turtleThorns = false;
        cactusThorns = false;
        spiderArmor = false;
        anglerSetSpawnReduction = false;
        loveStruck = false;
        stinky = false;
        dryadWard = false;
        resistCold = false;
        electrified = false;
        moonLeech = false;
        headcovered = false;
        vortexDebuff = false;
        windPushed = false;
        ballistaPanic = false;
        vampireFrog = false;
        CanSeeInvisibleBlocks = false;
        setVortex = (setNebula = (setStardust = false));
        setForbidden = false;
        setHuntressT3 = false;
        setSquireT3 = false;
        setMonkT3 = false;
        setApprenticeT3 = false;
        setHuntressT2 = false;
        setSquireT2 = false;
        setMonkT2 = false;
        setApprenticeT2 = false;
        setForbiddenCooldownLocked = false;
        nebulaLevelDamage = (nebulaLevelLife = (nebulaLevelMana = 0));
        ignoreWater = false;
        meleeEnchant = 0;
        discountEquipped = false;
        hasLuckyCoin = false;
        boneGloveItem = null;
        hasLuck_LuckyCoin = false;
        hasLuck_LuckyHorseshoe = false;
        blockExtraJumps = false;
        ExtraJumpLoader.ResetEnableFlags(this);
        defendedByPaladin = false;
        hasPaladinShield = false;
        hasLucyTheAxe = false;
        preventAllItemPickups = false;
        dontHurtCritters = false;
        dontHurtNature = false;
        portableStoolInfo.Reset();
        ResizeHitbox();
        autoJump = false;
        justJumped = false;
        jumpSpeedBoost = 0f;
        extraFall = 0;
        creativeGodMode = false;
        if (phantasmTime > 0)
        {
            phantasmTime--;
        }
        if (brainOfConfusionDodgeAnimationCounter > 0)
        {
            brainOfConfusionDodgeAnimationCounter--;
        }
        if (wireOperationsCooldown > 0)
        {
            wireOperationsCooldown--;
        }
        if (releaseUseItem)
        {
            ActuationRodLock = false;
        }
        for (int i = 0; i < npcTypeNoAggro.Length; i++)
        {
            npcTypeNoAggro[i] = false;
        }
        ResetProjectileCaches();
        if (whoAmI == Main.myPlayer && !isDisplayDollOrInanimate)
        {
            equipmentBasedLuckBonus = 0f;
            luckPotion = 0;
            tileRangeX = 5;
            tileRangeY = 4;
            if (Main.GameModeInfo.IsJourneyMode)
            {
                CreativePowers.FarPlacementRangePower power = CreativePowerManager.Instance.GetPower<CreativePowers.FarPlacementRangePower>();
                if (power.GetIsUnlocked() && power.IsEnabledForPlayer(whoAmI))
                {
                    tileRangeX *= 2;
                    tileRangeY *= 2;
                    tileRangeX += 8;
                    tileRangeY += 8;
                }
            }
        }
        ResetDamageClassData();
        mount.CheckMountBuff(this);
        PlayerLoader.ResetEffects(this);
        PlayerLoader.ResetInfoAccessories(this);
    }
References Terraria.Player.abigailMinion, Terraria.Player.accCalendar, Terraria.Player.accCompass, Terraria.Player.accCritterGuide, Terraria.Player.accDepthMeter, Terraria.Player.accDivingHelm, Terraria.Player.accDreamCatcher, Terraria.Player.accFishFinder, Terraria.Player.accFishingBobber, Terraria.Player.accFishingLine, Terraria.Player.accJarOfSouls, Terraria.Player.accLavaFishing, Terraria.Player.accOreFinder, Terraria.Player.accStopwatch, Terraria.Player.accTackleBox, Terraria.Player.accThirdEye, Terraria.Player.accWatch, Terraria.Player.accWeatherRadio, Terraria.Player.ActuationRodLock, Terraria.Player.aggro, Terraria.Player.ammoBox, Terraria.Player.ammoCost75, Terraria.Player.ammoCost80, Terraria.Player.ammoPotion, Terraria.Player.anglerSetSpawnReduction, Terraria.Player.archery, Terraria.Player.arcticDivingGear, Terraria.Player.arrowDamage, Terraria.Player.ashWoodBonus, Terraria.Player.autoActuator, Terraria.Player.autoJump, Terraria.Player.autoPaint, Terraria.Player.autoReuseGlove, Terraria.Player.babyBird, Terraria.Player.babyFaceMonster, Terraria.Player.ballistaPanic, Terraria.Player.batsOfLight, Terraria.Player.beetleBuff, Terraria.Player.beetleOrbs, Terraria.Player.biomeSight, Terraria.Player.blackBelt, Terraria.Player.blackCat, Terraria.Player.blackout, Terraria.Player.bleed, Terraria.Player.blind, Terraria.Player.blockExtraJumps, Terraria.Player.blockRange, Terraria.Player.bloodMoonMonolithShader, Terraria.Player.blueFairy, Terraria.Player.boneArmor, Terraria.Player.boneGloveItem, Terraria.Player.brainOfConfusionDodgeAnimationCounter, Terraria.Player.brainOfConfusionItem, Terraria.Player.brokenArmor, Terraria.Player.bulletDamage, Terraria.Player.bunny, Terraria.Player.burned, Terraria.Player.cactusThorns, Terraria.Player.calmed, Terraria.Player.canFloatInWater, Terraria.Player.CanSeeInvisibleBlocks, Terraria.Player.carpet, Terraria.Player.chaosState, Terraria.Mount.CheckMountBuff(), Terraria.Player.chilled, Terraria.Player.chiselSpeed, Terraria.Player.chloroAmmoCost80, Terraria.Player.coldDash, Terraria.Player.companionCube, Terraria.Player.confused, Terraria.Player.coolWhipBuff, Terraria.Player.cordage, Terraria.Player.counterWeight, Terraria.Player.cratePotion, Terraria.Player.creativeGodMode, Terraria.Player.crimsonHeart, Terraria.Player.crimsonRegen, Terraria.Player.crystalLeaf, Terraria.Player.cSapling, Terraria.Player.cursed, Terraria.Player.dangerSense, Terraria.Player.dashType, Terraria.Player.dazed, Terraria.Player.dd2Accessory, Terraria.Player.DeadlySphereMinion, Terraria.ModLoader.StatModifier.Default, Terraria.Player.DefenseStat.Default, Terraria.Player.defendedByPaladin, Terraria.Player.DefenseEffectiveness, Terraria.Player.desertBoots, Terraria.Player.desertDash, Terraria.Player.detectCreature, Terraria.Player.dino, Terraria.Player.discountEquipped, Terraria.Player.dontHurtCritters, Terraria.Player.dontHurtNature, Terraria.Player.dontStarveShader, Terraria.Main.dontStarveWorld, Terraria.Player.drawingFootball, Terraria.Player.dripping, Terraria.Player.drippingSlime, Terraria.Player.drippingSparkleSlime, Terraria.Player.dryadWard, Terraria.Player.eater, Terraria.Player.electrified, Terraria.Player.empressBlade, Terraria.Player.empressBrooch, Terraria.Player.endurance, Terraria.Player.enemySpawns, Terraria.Player.equipmentBasedLuckBonus, Terraria.Player.equippedWings, Terraria.Main.expertMode, Terraria.Player.extraAccessory, Terraria.Player.extraAccessorySlots, Terraria.Player.extraFall, Terraria.Player.eyebrellaCloud, Terraria.Player.eyeSpring, Terraria.Player.fairyBoots, Terraria.Player.findTreasure, Terraria.Player.fireWalk, Terraria.Player.fishingSkill, Terraria.Player.flinxMinion, Terraria.Player.flowerBoots, Terraria.Player.forcedGravity, Terraria.Player.frogLegJumpBoost, Terraria.Player.frostArmor, Terraria.Player.frostBurn, Terraria.Player.frozen, Terraria.Main.gameMenu, Terraria.Main.GameModeInfo, Terraria.Player.ghostHeal, Terraria.Player.ghostHurt, Terraria.Player.gills, Terraria.Player.GoingDownWithGrapple, Terraria.Player.goldRing, Terraria.Player.gravControl, Terraria.Player.gravControl2, Terraria.Player.greenFairy, Terraria.Player.grinch, Terraria.Player.gross, Terraria.Player.hasAngelHalo, Terraria.Player.hasCreditsSceneMusicBox, Terraria.Player.hasFloatingTube, Terraria.Player.hasFootball, Terraria.Player.hasLuck_LuckyCoin, Terraria.Player.hasLuck_LuckyHorseshoe, Terraria.Player.hasLuckyCoin, Terraria.Player.hasLucyTheAxe, Terraria.Player.hasMagiluminescence, Terraria.Player.hasMoltenQuiver, Terraria.Player.hasPaladinShield, Terraria.Player.hasRainbowCursor, Terraria.Player.hasRaisableShield, Terraria.Player.hasTitaniumStormBuff, Terraria.Player.hasUnicornHorn, Terraria.Player.headcovered, Terraria.Player.heartyMeal, Terraria.Player.hellfireTreads, Terraria.Player.honey, Terraria.Player.honeyCombItem, Terraria.Player.hornet, Terraria.Player.hornetMinion, Terraria.Player.hungry, Terraria.Player.huntressAmmoCost90, Terraria.Player.iceBarrier, Terraria.Player.iceSkate, Terraria.Player.ichor, Terraria.Player.ignoreWater, Terraria.Player.impMinion, Terraria.Player.inferno, Terraria.Player.InfoAccMechShowWires, Terraria.GameContent.Creative.CreativePowerManager.Instance, Terraria.Player.invis, Terraria.Player.isDisplayDollOrInanimate, Terraria.Player.jumpBoost, Terraria.Player.jumpSpeedBoost, Terraria.Player.justJumped, Terraria.Player.kbBuff, Terraria.Player.kbGlove, Terraria.Player.killClothier, Terraria.Player.killGuide, Terraria.Player.lavaImmune, Terraria.Player.lavaMax, Terraria.Player.lavaRose, Terraria.Player.leinforsHair, Terraria.Player.lifeForce, Terraria.Player.lifeMagnet, Terraria.Player.lifeRegen, Terraria.Player.lightOrb, Terraria.Player.lizard, Terraria.Player.longInvince, Terraria.Player.loveStruck, Terraria.Player.luckPotion, Terraria.Player.magicCuffs, Terraria.Player.magicLantern, Terraria.Player.magicQuiver, Terraria.Player.magmaStone, Terraria.Player.manaCost, Terraria.Player.manaFlower, Terraria.Player.manaMagnet, Terraria.Player.manaRegenBonus, Terraria.Player.manaRegenBuff, Terraria.Player.manaRegenDelayBonus, Terraria.Player.manaSick, Terraria.Player.maxMinions, Terraria.Player.maxTurrets, Terraria.Player.meleeEnchant, Terraria.Player.meleeScaleGlove, Terraria.Player.miniMinotaur, Terraria.Player.minionKB, Terraria.ModLoader.PlayerLoader.ModifyMaxStats(), Terraria.Player.moonLeech, Terraria.Player.moonLordLegs, Terraria.Player.moonLordMonolithShader, Terraria.Player.mount, Terraria.Player.moveSpeed, Terraria.Main.myPlayer, Terraria.Player.nebulaLevelDamage, Terraria.Player.nebulaLevelLife, Terraria.Player.nebulaLevelMana, Terraria.Player.nebulaMonolithShader, Terraria.Player.nightVision, Terraria.Player.noBuilding, Terraria.Player.noFallDmg, Terraria.Player.noItems, Terraria.Player.noKnockback, Terraria.Player.npcTypeNoAggro, Terraria.Player.onFire, Terraria.Player.onFire2, Terraria.Player.onFire3, Terraria.Player.onFrostBurn, Terraria.Player.onFrostBurn2, Terraria.Player.onHitDodge, Terraria.Player.onHitPetal, Terraria.Player.onHitRegen, Terraria.Player.onHitTitaniumStorm, Terraria.Player.overrideFishingBobber, Terraria.Player.palladiumRegen, Terraria.Player.panic, Terraria.Player.parrot, Terraria.Player.parryDamageBuff, Terraria.Player.penguin, Terraria.Player.petFlagBabyImp, Terraria.Player.petFlagBabyRedPanda, Terraria.Player.petFlagBabyShark, Terraria.Player.petFlagBabyWerewolf, Terraria.Player.petFlagBerniePet, Terraria.Player.petFlagBlueChickenPet, Terraria.Player.petFlagBrainOfCthulhuPet, Terraria.Player.petFlagCaveling, Terraria.Player.petFlagChesterPet, Terraria.Player.petFlagDD2BetsyPet, Terraria.Player.petFlagDD2Dragon, Terraria.Player.petFlagDD2Gato, Terraria.Player.petFlagDD2Ghost, Terraria.Player.petFlagDD2OgrePet, Terraria.Player.petFlagDeerclopsPet, Terraria.Player.petFlagDestroyerPet, Terraria.Player.petFlagDirtiestBlock, Terraria.Player.petFlagDukeFishronPet, Terraria.Player.petFlagDynamiteKitten, Terraria.Player.petFlagEaterOfWorldsPet, Terraria.Player.petFlagEverscreamPet, Terraria.Player.petFlagEyeOfCthulhuPet, Terraria.Player.petFlagFairyQueenPet, Terraria.Player.petFlagFennecFox, Terraria.Player.petFlagGlitteryButterfly, Terraria.Player.petFlagGlommerPet, Terraria.Player.petFlagGolemPet, Terraria.Player.petFlagIceQueenPet, Terraria.Player.petFlagJunimoPet, Terraria.Player.petFlagKingSlimePet, Terraria.Player.petFlagLilHarpy, Terraria.Player.petFlagLunaticCultistPet, Terraria.Player.petFlagMartianPet, Terraria.Player.petFlagMoonLordPet, Terraria.Player.petFlagPigPet, Terraria.Player.petFlagPlanteraPet, Terraria.Player.petFlagPlantero, Terraria.Player.petFlagPumpkingPet, Terraria.Player.petFlagQueenBeePet, Terraria.Player.petFlagQueenSlimePet, Terraria.Player.petFlagShadowMimic, Terraria.Player.petFlagSkeletronPet, Terraria.Player.petFlagSkeletronPrimePet, Terraria.Player.petFlagSpiffo, Terraria.Player.petFlagSugarGlider, Terraria.Player.petFlagTwinsPet, Terraria.Player.petFlagUpbeatStar, Terraria.Player.petFlagVoltBunny, Terraria.Player.phantasmTime, Terraria.Player.pickSpeed, Terraria.Player.pirateMinion, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.poisoned, Terraria.Player.portableStoolInfo, Terraria.Entity.position, Terraria.Player.preventAllItemPickups, Terraria.Player.pStone, Terraria.Player.puppy, Terraria.Player.pygmy, Terraria.Player.rabid, Terraria.Player.raven, Terraria.Player.redFairy, Terraria.Player.releaseUseItem, Terraria.Main.remixWorld, Terraria.Player.remoteVisionForDrone, Terraria.DataStructures.PortableStoolUsage.Reset(), Terraria.Player.ResetDamageClassData(), Terraria.ModLoader.PlayerLoader.ResetEffects(), Terraria.ModLoader.ExtraJumpLoader.ResetEnableFlags(), Terraria.ModLoader.PlayerLoader.ResetInfoAccessories(), Terraria.Player.ResetProjectileCaches(), Terraria.Player.resistCold, Terraria.Player.ResizeHitbox(), Terraria.Player.rocketBoots, Terraria.Player.rulerGrid, Terraria.Player.rulerLine, Terraria.Player.sailDash, Terraria.Player.sapling, Terraria.Player.scope, Terraria.Player.setApprenticeT2, Terraria.Player.setApprenticeT3, Terraria.Player.setForbidden, Terraria.Player.setForbiddenCooldownLocked, Terraria.Player.setHuntressT2, Terraria.Player.setHuntressT3, Terraria.Player.setMonkT2, Terraria.Player.setMonkT3, Terraria.Player.setNebula, Terraria.Player.setSquireT2, Terraria.Player.setSquireT3, Terraria.Player.setStardust, Terraria.Player.setVortex, Terraria.Player.shadowArmor, Terraria.Player.shadowDodge, Terraria.Player.sharknadoMinion, Terraria.Player.shimmerImmune, Terraria.Player.shimmering, Terraria.Player.shimmerMonolithShader, Terraria.Player.shimmerTransparency, Terraria.Player.shinyStone, Terraria.Player.shroomiteStealth, Terraria.Player.silence, Terraria.Player.skeletron, Terraria.Player.skyStoneEffects, Terraria.Player.slime, Terraria.Player.slow, Terraria.Player.slowFall, Terraria.Player.slowOgreSpit, Terraria.Player.smolstar, Terraria.Player.snowman, Terraria.Player.solarMonolithShader, Terraria.Player.solarShields, Terraria.Player.sonarPotion, Terraria.Player.spaceGun, Terraria.Player.spawnMax, Terraria.Player.specialistDamage, Terraria.Player.spider, Terraria.Player.spiderArmor, Terraria.Player.spiderMinion, Terraria.Player.spikedBoots, Terraria.Player.sporeSac, Terraria.Player.squashling, Terraria.Player.starCloakItem, Terraria.Player.starCloakItem_beeCloakOverrideItem, Terraria.Player.starCloakItem_manaCloakOverrideItem, Terraria.Player.starCloakItem_starVeilOverrideItem, Terraria.Player.stardustDragon, Terraria.Player.stardustGuardian, Terraria.Player.stardustMinion, Terraria.Player.stardustMonolithShader, Terraria.Player.starving, Terraria.Player.statDefense, Terraria.Player.statLifeMax, Terraria.Player.statLifeMax2, Terraria.Player.statManaMax, Terraria.Player.statManaMax2, Terraria.Player.stinky, Terraria.Player.stoned, Terraria.Player.stormTiger, Terraria.Player.stringColor, Terraria.Player.strongBees, Terraria.Player.suffocating, Terraria.Player.sunflower, Terraria.Player.suspiciouslookingTentacle, Terraria.Player.thorns, Terraria.Player.ThrownCost33, Terraria.Player.ThrownCost50, Terraria.Player.ThrownVelocity, Terraria.Player.tiki, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Player.tileSpeed, Terraria.Player.tipsy, Terraria.Player.tongued, Terraria.Player.treasureMagnet, Terraria.Player.trident, Terraria.Player.truffle, Terraria.Player.turtle, Terraria.Player.turtleArmor, Terraria.Player.turtleThorns, Terraria.Player.twinsMinion, Terraria.Player.UFOMinion, Terraria.Player.vampireFrog, Terraria.Player.VanillaBaseDefenseEffectiveness(), Terraria.Player.vanityRocketBoots, Terraria.Player.venom, Terraria.Player.volatileGelatin, Terraria.Player.vortexDebuff, Terraria.Player.vortexMonolithShader, Terraria.Player.wallSpeed, Terraria.Player.waterWalk, Terraria.Player.waterWalk2, Terraria.Player.webbed, Terraria.Player.wellFed, Terraria.Player.wereWolf, Terraria.Player.whipRangeMultiplier, Terraria.Entity.whoAmI, Terraria.Player.windPushed, Terraria.Player.wings, Terraria.Player.wingsLogic, Terraria.Player.wingTimeMax, Terraria.Player.wireOperationsCooldown, Terraria.Player.wisp, Terraria.Player.witheredArmor, Terraria.Player.witheredWeapon, Terraria.Player.yoraiz0rDarkness, Terraria.Player.yoraiz0rEye, Terraria.Player.yoyoGlove, Terraria.Player.yoyoString, and Terraria.Player.zephyrfish.
Referenced by Terraria.GameContent.Animations.Segments.PlayerSegment.Draw(), Terraria.GameContent.UI.Elements.UICharacter.Update(), and Terraria.Player.Update().