TModLoader: Terraria.Player.HoneyCollision
HoneyCollision()
void Terraria.Player.HoneyCollision (bool fallThrough, bool ignorePlats) inline
Definition at line 21612 of file Player.cs.
    {
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        int num = ((!onTrack) ? height : (height - 20));
        Vector2 vector = velocity;
        velocity = Collision.TileCollision(position, velocity, width, num, fallThrough, ignorePlats, (int)gravDir);
        Vector2 vector2 = velocity * 0.25f;
        if (velocity.X != vector.X)
        {
            vector2.X = velocity.X;
        }
        if (velocity.Y != vector.Y)
        {
            vector2.Y = velocity.Y;
        }
        position += vector2;
        TryFloatingInFluid();
    }
References Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Player.onTrack, Terraria.Entity.position, Terraria.Collision.TileCollision(), Terraria.Player.TryFloatingInFluid(), Terraria.Entity.velocity, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().