TModLoader: Terraria.Player.GetAdjustedItemScale
GetAdjustedItemScale()
float Terraria.Player.GetAdjustedItemScale (Item item) inline
Used to determine what the overall scale of an item should be.
M:Terraria.ModLoader.CombinedHooks.ModifyItemScale(Terraria.Player,Terraria.Item,System.Single@) is called here.
Parameters
item The item to fetch the adjusted scale of.
Returns
The final scale of the item, after the Titan Glove effect and all modded calculations.
Definition at line 41782 of file Player.cs.
    {
        float scale = item.scale;
        if (item.melee)
        {
            ApplyMeleeScale(ref scale);
        }
        CombinedHooks.ModifyItemScale(this, item, ref scale);
        return scale;
    }
References Terraria.Player.ApplyMeleeScale(), Terraria.Item.melee, Terraria.ModLoader.CombinedHooks.ModifyItemScale(), and Terraria.Item.scale.
Referenced by Terraria.Player.ItemCheck_ApplyUseStyle_Inner(), Terraria.Player.ItemCheck_EmitUseVisuals(), Terraria.Player.ItemCheck_GetMeleeHitbox(), Terraria.Player.ItemCheck_Shoot(), and Terraria.Player.ProcessHitAgainstNPC().