TModLoader: Terraria.Player.ItemCheck_CheckFishingBobber_PullBobber
ItemCheck_CheckFishingBobber_PullBobber()
void Terraria.Player.ItemCheck_CheckFishingBobber_PullBobber (Projectile bobber, int baitTypeUsed) inline private
    {
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        if (baitTypeUsed == 2673)
        {
            if (Main.netMode != 1)
            {
                NPC.SpawnOnPlayer(whoAmI, 370);
            }
            else
            {
                NetMessage.SendData(61, -1, -1, null, whoAmI, 370f);
            }
            bobber.ai[0] = 2f;
        }
        else if (bobber.localAI[1] < 0f)
        {
            Point point = default(Point);
            ((Point)(ref point))._002Ector((int)bobber.position.X, (int)bobber.position.Y);
            int num = (int)(0f - bobber.localAI[1]);
            if (num == 618)
            {
                point.Y += 64;
            }
            if (Main.netMode == 1)
            {
                NetMessage.SendData(130, -1, -1, null, point.X / 16, point.Y / 16, num);
            }
            else
            {
                if (num == 682)
                {
                    NPC.unlockedSlimeRedSpawn = true;
                }
                NPC.NewNPC(new EntitySource_FishedOut(this), point.X, point.Y, num);
                bobber.ai[0] = 2f;
                WorldGen.CheckAchievement_RealEstateAndTownSlimes();
            }
        }
        else if (Main.rand.Next(7) == 0 && !accFishingLine)
        {
            bobber.ai[0] = 2f;
        }
        else
        {
            bobber.ai[1] = bobber.localAI[1];
        }
        bobber.netUpdate = true;
    }
References Terraria.Player.accFishingLine, Terraria.Projectile.ai, Terraria.WorldGen.CheckAchievement_RealEstateAndTownSlimes(), Terraria.Projectile.localAI, Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.NPC.SpawnOnPlayer(), and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ItemCheck_CheckFishingBobbers().