TModLoader: Terraria.Player.ItemCheck_EmitUseVisuals
ItemCheck_EmitUseVisuals()
Rectangle Terraria.Player.ItemCheck_EmitUseVisuals (Item sItem, Rectangle itemRectangle) inline private
Definition at line 44093 of file Player.cs.
    {
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_0198: Unknown result type (might be due to invalid IL or missing references)
        //IL_019f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0302: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_026a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0271: Unknown result type (might be due to invalid IL or missing references)
        //IL_0276: Unknown result type (might be due to invalid IL or missing references)
        //IL_027c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0299: Unknown result type (might be due to invalid IL or missing references)
        //IL_029f: Unknown result type (might be due to invalid IL or missing references)
        //IL_036d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0374: Unknown result type (might be due to invalid IL or missing references)
        //IL_037b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0380: Unknown result type (might be due to invalid IL or missing references)
        //IL_0386: Unknown result type (might be due to invalid IL or missing references)
        //IL_039f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0472: Unknown result type (might be due to invalid IL or missing references)
        //IL_0479: Unknown result type (might be due to invalid IL or missing references)
        //IL_0480: Unknown result type (might be due to invalid IL or missing references)
        //IL_0485: Unknown result type (might be due to invalid IL or missing references)
        //IL_048b: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03da: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_040c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0412: Unknown result type (might be due to invalid IL or missing references)
        //IL_056b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0572: Unknown result type (might be due to invalid IL or missing references)
        //IL_0579: Unknown result type (might be due to invalid IL or missing references)
        //IL_057e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0584: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0502: Unknown result type (might be due to invalid IL or missing references)
        //IL_0508: Unknown result type (might be due to invalid IL or missing references)
        //IL_0521: Unknown result type (might be due to invalid IL or missing references)
        //IL_052b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0530: Unknown result type (might be due to invalid IL or missing references)
        //IL_053e: Unknown result type (might be due to invalid IL or missing references)
        //IL_054f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0554: Unknown result type (might be due to invalid IL or missing references)
        //IL_0559: Unknown result type (might be due to invalid IL or missing references)
        //IL_042c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0433: Unknown result type (might be due to invalid IL or missing references)
        //IL_043a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0441: Unknown result type (might be due to invalid IL or missing references)
        //IL_0447: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0602: Unknown result type (might be due to invalid IL or missing references)
        //IL_0609: Unknown result type (might be due to invalid IL or missing references)
        //IL_060e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0614: Unknown result type (might be due to invalid IL or missing references)
        //IL_064a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0650: Unknown result type (might be due to invalid IL or missing references)
        //IL_072d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0734: Unknown result type (might be due to invalid IL or missing references)
        //IL_073b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0740: Unknown result type (might be due to invalid IL or missing references)
        //IL_0746: Unknown result type (might be due to invalid IL or missing references)
        //IL_077d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0783: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0802: Unknown result type (might be due to invalid IL or missing references)
        //IL_0808: Unknown result type (might be due to invalid IL or missing references)
        //IL_082c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0836: Unknown result type (might be due to invalid IL or missing references)
        //IL_083b: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0900: Unknown result type (might be due to invalid IL or missing references)
        //IL_0905: Unknown result type (might be due to invalid IL or missing references)
        //IL_090b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0922: Unknown result type (might be due to invalid IL or missing references)
        //IL_0954: Unknown result type (might be due to invalid IL or missing references)
        //IL_0959: Unknown result type (might be due to invalid IL or missing references)
        //IL_0975: Unknown result type (might be due to invalid IL or missing references)
        //IL_097f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0984: Unknown result type (might be due to invalid IL or missing references)
        //IL_0860: Unknown result type (might be due to invalid IL or missing references)
        //IL_0867: Unknown result type (might be due to invalid IL or missing references)
        //IL_086e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0873: Unknown result type (might be due to invalid IL or missing references)
        //IL_0879: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08db: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0996: Unknown result type (might be due to invalid IL or missing references)
        //IL_0997: Unknown result type (might be due to invalid IL or missing references)
        //IL_099c: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a40: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a46: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a84: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0caa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d65: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d73: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d78: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b36: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b40: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b55: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b90: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bfa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c45: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c56: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_19bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_19c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1069: Unknown result type (might be due to invalid IL or missing references)
        //IL_1070: Unknown result type (might be due to invalid IL or missing references)
        //IL_1077: Unknown result type (might be due to invalid IL or missing references)
        //IL_107c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1082: Unknown result type (might be due to invalid IL or missing references)
        //IL_10bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_10e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_10f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_10f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1914: Unknown result type (might be due to invalid IL or missing references)
        //IL_191b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1922: Unknown result type (might be due to invalid IL or missing references)
        //IL_1927: Unknown result type (might be due to invalid IL or missing references)
        //IL_192d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1964: Unknown result type (might be due to invalid IL or missing references)
        //IL_196a: Unknown result type (might be due to invalid IL or missing references)
        //IL_115f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1166: Unknown result type (might be due to invalid IL or missing references)
        //IL_116d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1172: Unknown result type (might be due to invalid IL or missing references)
        //IL_1178: Unknown result type (might be due to invalid IL or missing references)
        //IL_1191: Unknown result type (might be due to invalid IL or missing references)
        //IL_1197: Unknown result type (might be due to invalid IL or missing references)
        //IL_11cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_11dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1202: Unknown result type (might be due to invalid IL or missing references)
        //IL_1209: Unknown result type (might be due to invalid IL or missing references)
        //IL_1210: Unknown result type (might be due to invalid IL or missing references)
        //IL_1215: Unknown result type (might be due to invalid IL or missing references)
        //IL_121b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1253: Unknown result type (might be due to invalid IL or missing references)
        //IL_1259: Unknown result type (might be due to invalid IL or missing references)
        //IL_127d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1287: Unknown result type (might be due to invalid IL or missing references)
        //IL_128c: Unknown result type (might be due to invalid IL or missing references)
        //IL_12cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_12d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_12db: Unknown result type (might be due to invalid IL or missing references)
        //IL_12e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_12e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_131d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1323: Unknown result type (might be due to invalid IL or missing references)
        //IL_1347: Unknown result type (might be due to invalid IL or missing references)
        //IL_1351: Unknown result type (might be due to invalid IL or missing references)
        //IL_1356: Unknown result type (might be due to invalid IL or missing references)
        //IL_139a: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_13ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_13eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_13f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1463: Unknown result type (might be due to invalid IL or missing references)
        //IL_146a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1471: Unknown result type (might be due to invalid IL or missing references)
        //IL_1476: Unknown result type (might be due to invalid IL or missing references)
        //IL_147c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1495: Unknown result type (might be due to invalid IL or missing references)
        //IL_149b: Unknown result type (might be due to invalid IL or missing references)
        //IL_150f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1516: Unknown result type (might be due to invalid IL or missing references)
        //IL_151d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1522: Unknown result type (might be due to invalid IL or missing references)
        //IL_1528: Unknown result type (might be due to invalid IL or missing references)
        //IL_1541: Unknown result type (might be due to invalid IL or missing references)
        //IL_1547: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_15e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_15e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_15eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_160c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1612: Unknown result type (might be due to invalid IL or missing references)
        //IL_1859: Unknown result type (might be due to invalid IL or missing references)
        //IL_1860: Unknown result type (might be due to invalid IL or missing references)
        //IL_1867: Unknown result type (might be due to invalid IL or missing references)
        //IL_186c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1872: Unknown result type (might be due to invalid IL or missing references)
        //IL_1888: Unknown result type (might be due to invalid IL or missing references)
        //IL_188e: Unknown result type (might be due to invalid IL or missing references)
        //IL_18c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_18ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_18d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_172d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1734: Unknown result type (might be due to invalid IL or missing references)
        //IL_173b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1741: Unknown result type (might be due to invalid IL or missing references)
        if (sItem.type == 989 && Main.rand.Next(5) == 0)
        {
            int num30 = Main.rand.Next(3);
            int num = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, num30 switch
            {
                0 => 15,
                1 => 57,
                _ => 58,
            }, direction * 2, 0f, 150, default(Color), 1.3f);
            Dust obj = Main.dust[num];
            obj.velocity *= 0.2f;
        }
        if (sItem.type == 2880 && Main.rand.Next(2) == 0)
        {
            int type2 = Utils.SelectRandom<int>(Main.rand, 226, 229);
            int num12 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, type2, direction * 2, 0f, 150);
            Dust obj2 = Main.dust[num12];
            obj2.velocity *= 0.2f;
            Main.dust[num12].noGravity = true;
        }
        if ((sItem.type == 44 || sItem.type == 45 || sItem.type == 103 || sItem.type == 104) && Main.rand.Next(15) == 0)
        {
            Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 14, direction * 2, 0f, 150, default(Color), 1.3f);
        }
        if (sItem.type == 46 && Main.rand.Next(15) == 0)
        {
            Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 14, direction * 2, 0f, 150, default(Color), 1.3f);
        }
        if (sItem.type == 273 || sItem.type == 675)
        {
            if (Main.rand.Next(5) == 0)
            {
                Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 14, direction * 2, 0f, 150, default(Color), 1.4f);
            }
            int num23 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 27, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.2f);
            Main.dust[num23].noGravity = true;
            Main.dust[num23].velocity.X /= 2f;
            Main.dust[num23].velocity.Y /= 2f;
        }
        if (sItem.type == 723 && Main.rand.Next(2) == 0)
        {
            int num24 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 64, 0f, 0f, 150, default(Color), 1.2f);
            Main.dust[num24].noGravity = true;
        }
        if (sItem.type == 65)
        {
            if (Main.rand.Next(5) == 0)
            {
                Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 58, 0f, 0f, 150, default(Color), 1.2f);
            }
            if (Main.rand.Next(10) == 0)
            {
                Gore.NewGore(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), default(Vector2), Main.rand.Next(16, 18));
            }
        }
        if (sItem.type == 3065)
        {
            int num25 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 58, 0f, 0f, 150, default(Color), 1.2f);
            Dust obj3 = Main.dust[num25];
            obj3.velocity *= 0.5f;
            if (Main.rand.Next(8) == 0)
            {
                int num26 = Gore.NewGore(new Vector2((float)((Rectangle)(ref itemRectangle)).Center.X, (float)((Rectangle)(ref itemRectangle)).Center.Y), default(Vector2), 16);
                Gore obj4 = Main.gore[num26];
                obj4.velocity *= 0.5f;
                Gore obj5 = Main.gore[num26];
                obj5.velocity += new Vector2((float)direction, 0f);
            }
        }
        if (sItem.type == 190)
        {
            int num27 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 40, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 0, default(Color), 1.2f);
            Main.dust[num27].noGravity = true;
        }
        else if (sItem.type == 213 || sItem.type == 5295)
        {
            int num28 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 3, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 0, default(Color), 1.2f);
            Main.dust[num28].noGravity = true;
        }
        if (sItem.type == 121)
        {
            for (int i = 0; i < 2; i++)
            {
                GetPointOnSwungItemPath(70f, 70f, 0.2f + 0.8f * Main.rand.NextFloat(), GetAdjustedItemScale(sItem), out var location, out var outwardDirection);
                Vector2 vector = outwardDirection.RotatedBy((float)Math.PI / 2f * (float)direction * gravDir);
                Dust.NewDustPerfect(location, 6, vector * 4f, 100, default(Color), 2.5f).noGravity = true;
            }
        }
        if (sItem.type == 122 || sItem.type == 217)
        {
            int num29 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 6, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.9f);
            Main.dust[num29].noGravity = true;
        }
        if (sItem.type == 155)
        {
            int num2 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 172, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 0.9f);
            Main.dust[num2].noGravity = true;
            Dust obj6 = Main.dust[num2];
            obj6.velocity *= 0.1f;
        }
        if (sItem.type == 676 && Main.rand.Next(3) == 0)
        {
            int num3 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 67, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 90, default(Color), 1.5f);
            Main.dust[num3].noGravity = true;
            Dust obj7 = Main.dust[num3];
            obj7.velocity *= 0.2f;
        }
        if (sItem.type == 3063)
        {
            int num4 = Dust.NewDust(itemRectangle.TopLeft(), itemRectangle.Width, itemRectangle.Height, 66, 0f, 0f, 150, Color.Transparent, 0.85f);
            Main.dust[num4].color = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f);
            Main.dust[num4].noGravity = true;
            Dust obj8 = Main.dust[num4];
            obj8.velocity /= 2f;
        }
        if (sItem.type == 3823)
        {
            Dust dust = Dust.NewDustDirect(itemRectangle.TopLeft(), itemRectangle.Width, itemRectangle.Height, 6, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, Color.Transparent, 0.7f);
            dust.noGravity = true;
            dust.velocity *= 2f;
            dust.fadeIn = 0.9f;
        }
        if (sItem.type == 724 && Main.rand.Next(5) == 0)
        {
            int num5 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 67, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 90, default(Color), 1.5f);
            Main.dust[num5].noGravity = true;
            Dust obj9 = Main.dust[num5];
            obj9.velocity *= 0.2f;
        }
        if (sItem.type >= 795 && sItem.type <= 802)
        {
            for (int j = 0; j < 2; j++)
            {
                GetPointOnSwungItemPath(60f, 60f, 0.2f + 0.8f * Main.rand.NextFloat(), GetAdjustedItemScale(sItem), out var location2, out var outwardDirection2);
                Vector2 vector2 = outwardDirection2.RotatedBy((float)Math.PI / 2f * (float)direction * gravDir);
                Dust.NewDustPerfect(location2, 5, vector2 * 2f, 100, default(Color), 0.7f + Main.rand.NextFloat() * 0.6f);
                if (Main.rand.Next(20) == 0)
                {
                    int num6 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 115, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 140, default(Color), 0.7f);
                    Main.dust[num6].position = location2;
                    Main.dust[num6].fadeIn = 1.2f;
                    Main.dust[num6].noGravity = true;
                    Dust obj10 = Main.dust[num6];
                    obj10.velocity *= 0.25f;
                    Dust obj11 = Main.dust[num6];
                    obj11.velocity += vector2 * 5f;
                }
            }
        }
        if (sItem.type == 367)
        {
            int num7 = 0;
            if (Main.rand.Next(3) == 0)
            {
                num7 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 57, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.1f);
                Main.dust[num7].noGravity = true;
                Main.dust[num7].velocity.X /= 2f;
                Main.dust[num7].velocity.Y /= 2f;
                Main.dust[num7].velocity.X += direction * 2;
            }
            if (Main.rand.Next(4) == 0)
            {
                num7 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 43, 0f, 0f, 254, default(Color), 0.3f);
                Dust obj12 = Main.dust[num7];
                obj12.velocity *= 0f;
            }
        }
        else if (sItem.type != 368)
        {
            _ = sItem.type;
        }
        if (sItem.type == 4258 || sItem.type == 4259 || (sItem.type >= 198 && sItem.type <= 203) || (sItem.type >= 3764 && sItem.type <= 3769))
        {
            float num8 = 0.5f;
            float num9 = 0.5f;
            float num10 = 0.5f;
            if (sItem.type == 198 || sItem.type == 3764)
            {
                num8 *= 0.1f;
                num9 *= 0.5f;
                num10 *= 1.2f;
            }
            else if (sItem.type == 199 || sItem.type == 3765)
            {
                num8 *= 1f;
                num9 *= 0.2f;
                num10 *= 0.1f;
            }
            else if (sItem.type == 200 || sItem.type == 3766)
            {
                num8 *= 0.1f;
                num9 *= 1f;
                num10 *= 0.2f;
            }
            else if (sItem.type == 201 || sItem.type == 3767)
            {
                num8 *= 0.8f;
                num9 *= 0.1f;
                num10 *= 1f;
            }
            else if (sItem.type == 202 || sItem.type == 3768)
            {
                num8 *= 0.8f;
                num9 *= 0.9f;
                num10 *= 1f;
            }
            else if (sItem.type == 203 || sItem.type == 3769)
            {
                num8 *= 0.8f;
                num9 *= 0.8f;
                num10 *= 0f;
            }
            else if (sItem.type == 4258 || sItem.type == 4259)
            {
                num8 *= 0.9f;
                num9 *= 0.5f;
                num10 *= 0f;
            }
            Lighting.AddLight((int)((itemLocation.X + 6f + velocity.X) / 16f), (int)((itemLocation.Y - 14f) / 16f), num8, num9, num10);
        }
        if (frostBurn && sItem.melee && !sItem.noMelee && !sItem.noUseGraphic && Main.rand.Next(2) == 0)
        {
            int num11 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 135, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 2.5f);
            Main.dust[num11].noGravity = true;
            Dust obj13 = Main.dust[num11];
            obj13.velocity *= 0.7f;
            Main.dust[num11].velocity.Y -= 0.5f;
        }
        if (sItem.melee && !sItem.noMelee && !sItem.noUseGraphic && meleeEnchant > 0)
        {
            if (meleeEnchant == 1)
            {
                if (Main.rand.Next(3) == 0)
                {
                    int num13 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 171, 0f, 0f, 100);
                    Main.dust[num13].noGravity = true;
                    Main.dust[num13].fadeIn = 1.5f;
                    Dust obj14 = Main.dust[num13];
                    obj14.velocity *= 0.25f;
                }
            }
            else if (meleeEnchant == 2)
            {
                if (Main.rand.Next(2) == 0)
                {
                    int num14 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 75, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 2.5f);
                    Main.dust[num14].noGravity = true;
                    Dust obj15 = Main.dust[num14];
                    obj15.velocity *= 0.7f;
                    Main.dust[num14].velocity.Y -= 0.5f;
                }
            }
            else if (meleeEnchant == 3)
            {
                if (Main.rand.Next(2) == 0)
                {
                    int num15 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 6, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 2.5f);
                    Main.dust[num15].noGravity = true;
                    Dust obj16 = Main.dust[num15];
                    obj16.velocity *= 0.7f;
                    Main.dust[num15].velocity.Y -= 0.5f;
                }
            }
            else if (meleeEnchant == 4)
            {
                int num16 = 0;
                if (Main.rand.Next(2) == 0)
                {
                    num16 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 57, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 1.1f);
                    Main.dust[num16].noGravity = true;
                    Main.dust[num16].velocity.X /= 2f;
                    Main.dust[num16].velocity.Y /= 2f;
                }
            }
            else if (meleeEnchant == 5)
            {
                if (Main.rand.Next(2) == 0)
                {
                    int num17 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 169, 0f, 0f, 100);
                    Main.dust[num17].velocity.X += direction;
                    Main.dust[num17].velocity.Y += 0.2f;
                    Main.dust[num17].noGravity = true;
                }
            }
            else if (meleeEnchant == 6)
            {
                if (Main.rand.Next(2) == 0)
                {
                    int num18 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 135, 0f, 0f, 100);
                    Main.dust[num18].velocity.X += direction;
                    Main.dust[num18].velocity.Y += 0.2f;
                    Main.dust[num18].noGravity = true;
                }
            }
            else if (meleeEnchant == 7)
            {
                if (Main.rand.Next(20) == 0)
                {
                    int type3 = Main.rand.Next(139, 143);
                    int num19 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, type3, velocity.X, velocity.Y, 0, default(Color), 1.2f);
                    Main.dust[num19].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                    Main.dust[num19].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                    Main.dust[num19].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                    Main.dust[num19].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
                    Main.dust[num19].scale *= 1f + (float)Main.rand.Next(-30, 31) * 0.01f;
                }
                if (Main.rand.Next(40) == 0)
                {
                    int type4 = Main.rand.Next(276, 283);
                    int num20 = Gore.NewGore(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), velocity, type4);
                    Main.gore[num20].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                    Main.gore[num20].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                    Main.gore[num20].scale *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                    Main.gore[num20].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                    Main.gore[num20].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
                }
            }
            else if (meleeEnchant == 8 && Main.rand.Next(4) == 0)
            {
                int num21 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 46, 0f, 0f, 100);
                Main.dust[num21].noGravity = true;
                Main.dust[num21].fadeIn = 1.5f;
                Dust obj17 = Main.dust[num21];
                obj17.velocity *= 0.25f;
            }
        }
        if (magmaStone && sItem.melee && !sItem.noMelee && !sItem.noUseGraphic && Main.rand.Next(3) != 0)
        {
            int num22 = Dust.NewDust(new Vector2((float)itemRectangle.X, (float)itemRectangle.Y), itemRectangle.Width, itemRectangle.Height, 6, velocity.X * 0.2f + (float)(direction * 3), velocity.Y * 0.2f, 100, default(Color), 2.5f);
            Main.dust[num22].noGravity = true;
            Main.dust[num22].velocity.X *= 2f;
            Main.dust[num22].velocity.Y *= 2f;
        }
        CombinedHooks.MeleeEffects(this, sItem, itemRectangle);
        return itemRectangle;
    }
References Terraria.Lighting.AddLight(), Terraria.Entity.Center, Terraria.Dust.color, Terraria.Entity.direction, Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Player.frostBurn, Terraria.Player.GetAdjustedItemScale(), Terraria.Player.GetPointOnSwungItemPath(), Terraria.Main.gore, Terraria.Player.gravDir, Terraria.Main.hslToRgb(), Terraria.Player.itemLocation, Terraria.Player.magmaStone, Terraria.ModLoader.CombinedHooks.MeleeEffects(), Terraria.Player.meleeEnchant, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Gore.NewGore(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.position, Terraria.Main.rand, Terraria.Dust.scale, Terraria.Gore.scale, Terraria.Dust.velocity, Terraria.Entity.velocity, and Terraria.Gore.velocity.
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode().