TModLoader: Terraria.Player.ItemCheck_CutTiles
ItemCheck_CutTiles()
void Terraria.Player.ItemCheck_CutTiles (Item sItem, Rectangle itemRectangle, bool[] shouldIgnore) inline private
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        int minX = itemRectangle.X / 16;
        int maxX = (itemRectangle.X + itemRectangle.Width) / 16 + 1;
        int minY = itemRectangle.Y / 16;
        int maxY = (itemRectangle.Y + itemRectangle.Height) / 16 + 1;
        Utils.ClampWithinWorld(ref minX, ref minY, ref maxX, ref maxY);
        for (int i = minX; i < maxX; i++)
        {
            for (int j = minY; j < maxY; j++)
            {
                if (Main.tile[i, j] == null || !Main.tileCut[Main.tile[i, j].type] || shouldIgnore[Main.tile[i, j].type] || !WorldGen.CanCutTile(i, j, TileCuttingContext.AttackMelee))
                {
                    continue;
                }
                if (sItem.type == 1786)
                {
                    ushort type = Main.tile[i, j].type;
                    WorldGen.KillTile(i, j);
                    if (!Main.tile[i, j].active())
                    {
                        int num = 0;
                        switch (type)
{
                        case 3:
                        case 24:
                        case 61:
                        case 110:
                        case 201:
                        case 529:
                        case 637:
                            num = Main.rand.Next(1, 3);
                            break;
                        case 73:
                        case 74:
                        case 113:
                            num = Main.rand.Next(2, 5);
                            break;
                        }
                        if (num > 0)
{
                            int number = Item.NewItem(new EntitySource_ItemUse(this, sItem), i * 16, j * 16, 16, 16, 1727, num);
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(21, -1, -1, null, number, 1f);
                            }
                        }
                    }
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(17, -1, -1, null, 0, i, j);
                    }
                }
                else
                {
                    WorldGen.KillTile(i, j);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(17, -1, -1, null, 0, i, j);
                    }
                }
            }
        }
    }
References Terraria.WorldGen.CanCutTile(), Terraria.Utils.ClampWithinWorld(), Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Main.tile, and Terraria.Main.tileCut.
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode(), and Terraria.Player.MowTheLawn().