TModLoader: Terraria.Player.GetItem
GetItem()
Item Terraria.Player.GetItem (int plr, Item newItem, GetItemSettings settings) inline
    {
        bool isACoin = newItem.IsACoin;
        Item item = newItem;
        int num = 50;
        if (newItem.noGrabDelay > 0)
        {
            return item;
        }
        int num2 = 0;
        if (newItem.uniqueStack && HasItem(newItem.type))
        {
            return item;
        }
        if (isACoin)
        {
            num2 = -4;
            num = 54;
        }
        if (item.FitsAmmoSlot())
        {
            item = FillAmmo(plr, item, settings);
            if (item.type == 0 || item.stack == 0)
            {
                return new Item();
            }
        }
        for (int i = num2; i < 50; i++)
        {
            int num3 = i;
            if (num3 < 0)
            {
                num3 = 54 + i;
            }
            if (GetItem_FillIntoOccupiedSlot(plr, newItem, settings, item, num3))
            {
                return new Item();
            }
        }
        if (!isACoin && newItem.useStyle != 0)
        {
            for (int j = 0; j < 10; j++)
            {
                if (GetItem_FillEmptyInventorySlot(plr, newItem, settings, item, j))
                {
                    return new Item();
                }
            }
        }
        if (newItem.favorited)
        {
            for (int k = 0; k < num; k++)
            {
                if (GetItem_FillEmptyInventorySlot(plr, newItem, settings, item, k))
                {
                    return new Item();
                }
            }
        }
        else
        {
            for (int num4 = num - 1; num4 >= 0; num4--)
            {
                if (GetItem_FillEmptyInventorySlot(plr, newItem, settings, item, num4))
                {
                    return new Item();
                }
            }
        }
        if (settings.CanGoIntoVoidVault && IsVoidVaultEnabled && CanVoidVaultAccept(newItem) && GetItem_VoidVault(plr, bank4.item, newItem, settings, item))
        {
            return new Item();
        }
        return item;
    }
References Terraria.Player.bank4, Terraria.Player.CanVoidVaultAccept(), Terraria.Player.FillAmmo(), Terraria.Item.FitsAmmoSlot(), Terraria.Player.GetItem_FillEmptyInventorySlot(), Terraria.Player.GetItem_FillIntoOccupiedSlot(), Terraria.Player.GetItem_VoidVault(), Terraria.Player.HasItem(), Terraria.Player.IsVoidVaultEnabled, Terraria.Chest.item, Terraria.Item.stack, and Terraria.Item.type.
Referenced by Terraria.Lang.BartenderHelpText(), Terraria.GameContent.Creative.CreativeUI.CloseMenu(), Terraria.Player.dropItemCheck(), Terraria.Player.DropSelectedItem(), Terraria.Player.GetAnglerReward(), Terraria.Player.GetDyeTraderReward(), Terraria.Initializers.UILinksInitializer.Load(), Terraria.UI.ChestUI.LootAll(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.OverrideItemSlotLeftClick(), Terraria.GameContent.Tile_Entities.TEHatRack.OverrideItemSlotLeftClick(), Terraria.UI.ItemSlot.OverrideLeftClick(), Terraria.Player.PickupItem(), Terraria.Player.PutItemInInventoryFromItemUsage(), Terraria.GameContent.Creative.CreativeUI.SacrificeItem(), Terraria.GameContent.Creative.CreativeUI.ToggleMenu(), and Terraria.Main.TryAllowingToCraftRecipe().