TModLoader: Terraria.Player.StatusToNPC
StatusToNPC()
void Terraria.Player.StatusToNPC (int type, int i) inline
Definition at line 6831 of file Player.cs.
    {
        if (meleeEnchant > 0)
        {
            if (meleeEnchant == 1)
            {
                Main.npc[i].AddBuff(70, 60 * Main.rand.Next(5, 10));
            }
            if (meleeEnchant == 2)
            {
                Main.npc[i].AddBuff(39, 60 * Main.rand.Next(3, 7));
            }
            if (meleeEnchant == 3)
            {
                Main.npc[i].AddBuff(24, 60 * Main.rand.Next(3, 7));
            }
            if (meleeEnchant == 5)
            {
                Main.npc[i].AddBuff(69, 60 * Main.rand.Next(10, 20));
            }
            if (meleeEnchant == 6)
            {
                Main.npc[i].AddBuff(31, 60 * Main.rand.Next(1, 4));
            }
            if (meleeEnchant == 8)
            {
                Main.npc[i].AddBuff(20, 60 * Main.rand.Next(5, 10));
            }
            if (meleeEnchant == 4)
            {
                Main.npc[i].AddBuff(72, 120);
            }
        }
        if (frostBurn)
        {
            Main.npc[i].AddBuff(324, 60 * Main.rand.Next(5, 15));
        }
        if (magmaStone)
        {
            if (Main.rand.Next(4) == 0)
            {
                Main.npc[i].AddBuff(323, 360);
            }
            else if (Main.rand.Next(2) == 0)
            {
                Main.npc[i].AddBuff(323, 240);
            }
            else
            {
                Main.npc[i].AddBuff(323, 120);
            }
        }
        if (type == 3211)
        {
            Main.npc[i].AddBuff(69, 60 * Main.rand.Next(5, 10));
        }
        if (type == 5129)
        {
            Main.npc[i].AddBuff(120, 300);
        }
        switch (type)
        {
        case 121:
            if (Main.rand.Next(2) == 0)
            {
                Main.npc[i].AddBuff(24, 180);
            }
            break;
        case 3823:
            if (Main.rand.Next(4) == 0)
            {
                Main.npc[i].AddBuff(323, 300);
            }
            break;
        case 5382:
            if (Main.rand.Next(3) == 0)
            {
                Main.npc[i].AddBuff(323, 300);
            }
            break;
        case 122:
            if (Main.rand.Next(10) == 0)
            {
                Main.npc[i].AddBuff(24, 180);
            }
            break;
        case 190:
            if (Main.rand.Next(4) == 0)
            {
                Main.npc[i].AddBuff(20, 420);
            }
            break;
        case 217:
            if (Main.rand.Next(5) == 0)
            {
                Main.npc[i].AddBuff(24, 180);
            }
            break;
        case 1123:
            if (Main.rand.Next(10) != 0)
            {
                Main.npc[i].AddBuff(31, 120);
            }
            break;
        }
    }
References Terraria.NPC.AddBuff(), Terraria.Player.frostBurn, Terraria.Player.magmaStone, Terraria.Player.meleeEnchant, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, and Terraria.Main.rand.
Referenced by Terraria.Player.ProcessHitAgainstNPC().