TModLoader: Terraria.Player.Player
Player()
Terraria.Player.Player () inline
Definition at line 56716 of file Player.cs.
    {
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_0239: Unknown result type (might be due to invalid IL or missing references)
        //IL_0385: Unknown result type (might be due to invalid IL or missing references)
        //IL_038a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0482: Unknown result type (might be due to invalid IL or missing references)
        //IL_0487: Unknown result type (might be due to invalid IL or missing references)
        //IL_0496: Unknown result type (might be due to invalid IL or missing references)
        //IL_049b: Unknown result type (might be due to invalid IL or missing references)
        //IL_04aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_04af: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04da: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0509: Unknown result type (might be due to invalid IL or missing references)
        //IL_050e: Unknown result type (might be due to invalid IL or missing references)
        //IL_051d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0522: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bf: Unknown result type (might be due to invalid IL or missing references)
        ResetDamageClassData();
        buffType = new int[maxBuffs];
        buffTime = new int[maxBuffs];
        buffImmune = new bool[BuffLoader.BuffCount];
        ownedProjectileCounts = new int[ProjectileLoader.ProjectileCount];
        npcTypeNoAggro = new bool[NPCLoader.NPCCount];
        PlayerLoader.SetupPlayer(this);
        LoaderManager.Get<BiomeLoader>().SetupPlayer(this);
        width = 20;
        height = 42;
        name = string.Empty;
        bodyFrame.Width = 40;
        bodyFrame.Height = 56;
        legFrame.Width = 40;
        legFrame.Height = 56;
        tileEntityAnchor.Clear();
        doorHelper = new DoorOpeningHelper();
        for (int i = 0; i < 59; i++)
        {
            if (i < armor.Length)
            {
                armor[i] = new Item();
            }
            inventory[i] = new Item();
        }
        for (int j = 0; j < 40; j++)
        {
            bank.item[j] = new Item();
            bank2.item[j] = new Item();
            bank3.item[j] = new Item();
            bank4.item[j] = new Item();
        }
        for (int k = 0; k < dye.Length; k++)
        {
            dye[k] = new Item();
        }
        for (int l = 0; l < miscEquips.Length; l++)
        {
            miscEquips[l] = new Item();
        }
        for (int m = 0; m < miscDyes.Length; m++)
        {
            miscDyes[m] = new Item();
        }
        trashItem = new Item();
        lastVisualizedSelectedItem = new Item();
        grappling[0] = -1;
        statManaMax = 20;
        extraAccessory = false;
        ateArtisanBread = false;
        usedAegisCrystal = false;
        usedAegisFruit = false;
        usedArcaneCrystal = false;
        usedGalaxyPearl = false;
        usedGummyWorm = false;
        usedAmbrosia = false;
        PlayerLoader.ModifyMaxStats(this);
        for (int n = 0; n < adjTile.Length; n++)
        {
            adjTile[n] = false;
            oldAdjTile[n] = false;
        }
        hitTile = new HitTile();
        hitReplace = new HitTile();
        mount = new Mount();
        talkNPC = -1;
        piggyBankProjTracker.Clear();
        voidLensChest.Clear();
        creativeTracker = new CreativeUnlocksTracker();
        builderAccStatus[0] = 1;
    }
References Terraria.Player.adjTile, Terraria.Player.armor, Terraria.Player.ateArtisanBread, Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.ModLoader.BuffLoader.BuffCount, Terraria.Player.buffImmune, Terraria.Player.buffTime, Terraria.Player.buffType, Terraria.Player.builderAccStatus, Terraria.DataStructures.PlayerInteractionAnchor.Clear(), Terraria.DataStructures.TrackedProjectileReference.Clear(), Terraria.Player.creativeTracker, Terraria.Player.doorHelper, Terraria.Player.dye, Terraria.Player.extraAccessory, Terraria.Player.grappling, Terraria.Entity.height, Terraria.Player.hitReplace, Terraria.Player.hitTile, Terraria.Player.inventory, Terraria.Chest.item, Terraria.Player.lastVisualizedSelectedItem, Terraria.Player.maxBuffs, Terraria.Player.miscDyes, Terraria.Player.miscEquips, Terraria.ModLoader.PlayerLoader.ModifyMaxStats(), Terraria.Player.mount, Terraria.Player.name, Terraria.ModLoader.NPCLoader.NPCCount, Terraria.Player.npcTypeNoAggro, Terraria.Player.oldAdjTile, Terraria.Player.ownedProjectileCounts, Terraria.Player.piggyBankProjTracker, Terraria.ModLoader.ProjectileLoader.ProjectileCount, Terraria.Player.ResetDamageClassData(), Terraria.ModLoader.PlayerLoader.SetupPlayer(), Terraria.Player.statManaMax, Terraria.Player.talkNPC, Terraria.Player.tileEntityAnchor, Terraria.Player.trashItem, Terraria.Player.usedAegisCrystal, Terraria.Player.usedAegisFruit, Terraria.Player.usedAmbrosia, Terraria.Player.usedArcaneCrystal, Terraria.Player.usedGalaxyPearl, Terraria.Player.usedGummyWorm, Terraria.Player.voidLensChest, and Terraria.Entity.width.
Referenced by Terraria.Player.clientClone(), Terraria.Player.LoadPlayer(), and Terraria.Player.SerializedClone().