TModLoader: Terraria.Player.CollideWithNPCs
CollideWithNPCs()
int Terraria.Player.CollideWithNPCs (Rectangle myRect, float Damage, float Knockback, int NPCImmuneTime, int PlayerImmuneTime, DamageClass? damageType = null) inline
    {
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        int num = 0;
        for (int i = 0; i < 200; i++)
        {
            NPC nPC = Main.npc[i];
            if (!nPC.active || nPC.dontTakeDamage || nPC.friendly || nPC.immune[whoAmI] != 0 || !CanNPCBeHitByPlayerOrPlayerProjectile(nPC))
            {
                continue;
            }
            Rectangle rect = nPC.getRect();
            if (((Rectangle)(ref myRect)).Intersects(rect) && (nPC.noTileCollide || Collision.CanHit(position, width, height, nPC.position, nPC.width, nPC.height)))
            {
                int num2 = direction;
                if (velocity.X < 0f)
                {
                    num2 = -1;
                }
                if (velocity.X > 0f)
                {
                    num2 = 1;
                }
                if (whoAmI == Main.myPlayer)
                {
                    ApplyDamageToNPC(nPC, (int)Damage, Knockback, num2, crit: false, damageType);
                }
                nPC.immune[whoAmI] = NPCImmuneTime;
                GiveImmuneTimeForCollisionAttack(PlayerImmuneTime);
                num++;
                break;
            }
        }
        return num;
    }
References Terraria.Player.ApplyDamageToNPC(), Terraria.Collision.CanHit(), Terraria.Player.CanNPCBeHitByPlayerOrPlayerProjectile(), Terraria.GameContent.Damage, Terraria.Entity.direction, Terraria.Player.GiveImmuneTimeForCollisionAttack(), Terraria.Entity.height, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Entity.position, Terraria.Entity.velocity, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.HorizontalMovement(), and Terraria.Player.MowTheLawn().