TModLoader: Terraria.Player.Update_NPCCollision
Update_NPCCollision()
void Terraria.Player.Update_NPCCollision () inline
    {
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_019b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03df: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        if (creativeGodMode)
        {
            return;
        }
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector((int)position.X, (int)position.Y, width, height);
        Rectangle npcRect = default(Rectangle);
        for (int i = 0; i < 200; i++)
        {
            if (!Main.npc[i].active || Main.npc[i].friendly || Main.npc[i].damage <= 0)
            {
                continue;
            }
            int specialHitSetter = -1;
            switch (Main.npc[i].type)
            {
            case 396:
            case 397:
            case 398:
            case 400:
            case 401:
                specialHitSetter = 1;
                break;
            case 636:
                specialHitSetter = 1;
                if (Main.npc[i].ai[0] == 0f || Main.npc[i].ai[0] == 10f)
                {
                    continue;
                }
                break;
            }
            if (!CombinedHooks.CanNPCHitPlayer(Main.npc[i], this, ref specialHitSetter) || (specialHitSetter == -1 && immune) || (dash == 2 && i == eocHit && eocDash > 0) || npcTypeNoAggro[Main.npc[i].type])
            {
                continue;
            }
            float damageMultiplier = 1f;
            NPC obj = Main.npc[i];
            obj.position += Main.npc[i].netOffset;
            ((Rectangle)(ref npcRect))._002Ector((int)Main.npc[i].position.X, (int)Main.npc[i].position.Y, Main.npc[i].width, Main.npc[i].height);
            NPC.GetMeleeCollisionData(rectangle, i, ref specialHitSetter, ref damageMultiplier, ref npcRect);
            if (((Rectangle)(ref rectangle)).Intersects(npcRect))
            {
                if (npcTypeNoAggro[Main.npc[i].type])
                {
                    continue;
                }
                bool flag = true;
                bool flag2 = false;
                bool num6 = CanParryAgainst(rectangle, npcRect, Main.npc[i].velocity);
                float num2 = thorns;
                float knockback = 10f;
                if (turtleThorns)
                {
                    num2 = 2f;
                }
                if (num6)
                {
                    num2 = 2f;
                    knockback = 5f;
                    flag = false;
                    flag2 = true;
                }
                int num3 = -1;
                if (Main.npc[i].position.X + (float)(Main.npc[i].width / 2) < position.X + (float)(width / 2))
                {
                    num3 = 1;
                }
                int num4 = Main.DamageVar((float)Main.npc[i].damage * damageMultiplier, 0f - luck);
                bool flag3 = !immune;
                if (specialHitSetter >= 0)
                {
                    flag3 = hurtCooldowns[specialHitSetter] == 0;
                }
                if (whoAmI == Main.myPlayer && num2 > 0f && flag3 && !Main.npc[i].dontTakeDamage)
                {
                    int num5 = (int)((float)num4 * num2);
                    if (num5 > 1000)
                    {
                        num5 = 1000;
                    }
                    ApplyDamageToNPC(Main.npc[i], num5, knockback, -num3);
                }
                if (whoAmI == Main.myPlayer && cactusThorns && flag3 && !Main.npc[i].dontTakeDamage)
                {
                    int damage = 15;
                    if (Main.masterMode)
                    {
                        damage = 45;
                    }
                    else if (Main.expertMode)
                    {
                        damage = 30;
                    }
                    ApplyDamageToNPC(Main.npc[i], damage, knockback, -num3);
                }
                if (flag && Hurt(dodgeable: Main.npc[i].IsDamageDodgeable(), damageSource: PlayerDeathReason.ByNPC(i), Damage: num4, hitDirection: num3, pvp: false, quiet: false, Crit: false, cooldownCounter: specialHitSetter) > 0.0 && !dead && !flag2)
                {
                    StatusFromNPC(Main.npc[i]);
                }
                if (num6)
                {
                    GiveImmuneTimeForCollisionAttack(longInvince ? 60 : 30);
                    AddBuff(198, 300, quiet: false);
                }
            }
            NPC obj2 = Main.npc[i];
            obj2.position -= Main.npc[i].netOffset;
        }
    }
References Terraria.Player.AddBuff(), Terraria.Player.ApplyDamageToNPC(), Terraria.DataStructures.PlayerDeathReason.ByNPC(), Terraria.Player.cactusThorns, Terraria.ModLoader.CombinedHooks.CanNPCHitPlayer(), Terraria.Player.CanParryAgainst(), Terraria.Player.creativeGodMode, Terraria.GameContent.Damage, Terraria.Main.DamageVar(), Terraria.Player.dash, Terraria.Player.dead, Terraria.Player.eocDash, Terraria.Player.eocHit, Terraria.Main.expertMode, Terraria.NPC.GetMeleeCollisionData(), Terraria.Player.GiveImmuneTimeForCollisionAttack(), Terraria.Entity.height, Terraria.Player.Hurt(), Terraria.Player.hurtCooldowns, Terraria.Player.immune, Terraria.Player.longInvince, Terraria.Player.luck, Terraria.Main.masterMode, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Player.npcTypeNoAggro, Terraria.Entity.position, Terraria.Player.StatusFromNPC(), Terraria.Player.thorns, Terraria.Player.turtleThorns, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().