TModLoader: Terraria.Player.MowTheLawn
MowTheLawn()
void Terraria.Player.MowTheLawn () inline private
    {
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00da: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0169: Unknown result type (might be due to invalid IL or missing references)
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0236: Unknown result type (might be due to invalid IL or missing references)
        //IL_0240: Unknown result type (might be due to invalid IL or missing references)
        //IL_0246: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_026b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        if (miscCounter % 2 != 0 || velocity.Y != 0f || grappling[0] != -1 || itemAnimation < 1)
        {
            return;
        }
        Vector2 vector = base.Center + new Vector2((float)(direction * 38), (float)(height / 2 + 4) * gravDir);
        float num = 1f - (float)itemAnimation / (float)itemAnimationMax;
        num *= 2f;
        num = ((!(num < 1f)) ? (num - 1f) : (1f - num));
        Vector2 val = vector + new Vector2((float)(direction * -16), gravDir * -4f);
        Vector2 value2 = vector + new Vector2((float)(direction * -6), gravDir * -4f);
        Dust dust = Dust.NewDustDirect(Vector2.Lerp(val, value2, num), 0, 0, 31, 0f, (0f - gravDir) * 0.25f, 127);
        dust.scale = 0.9f;
        dust.position -= new Vector2(4f);
        if (dust.velocity.Y > 0f)
        {
            dust.velocity.Y *= -1f;
        }
        dust.velocity *= 0.25f;
        Rectangle rectangle = Utils.CenteredRectangle(vector, new Vector2(8f, 20f));
        if (velocity.X * (float)direction > 0f || velocity.Y * gravDir > 0f)
        {
            Rectangle myRect = rectangle;
            myRect.Height -= 4;
            myRect.Y += 2;
            float damage = 8f;
            float knockback = 2f;
            int nPCImmuneTime = 12;
            int playerImmuneTime = 6;
            CollideWithNPCs(myRect, damage, knockback, nPCImmuneTime, playerImmuneTime);
        }
        rectangle.X -= direction * 10;
        if (whoAmI == Main.myPlayer)
        {
            bool[] shouldIgnore = ItemCheck_GetTileCutIgnoreList(HeldItem);
            ItemCheck_CutTiles(HeldItem, rectangle, shouldIgnore);
            MowGrassTile(vector);
            if (!WorldGen.SolidTile(Framing.GetTileSafely(vector.ToTileCoordinates())))
            {
                MowGrassTile(vector + new Vector2(0f, 16f * gravDir));
            }
        }
    }
References Terraria.Utils.CenteredRectangle(), Terraria.Player.CollideWithNPCs(), Terraria.Entity.direction, Terraria.Framing.GetTileSafely(), Terraria.Player.grappling, Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Player.HeldItem, Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, Terraria.Player.ItemCheck_CutTiles(), Terraria.Player.ItemCheck_GetTileCutIgnoreList(), Terraria.Player.miscCounter, Terraria.Player.MowGrassTile(), Terraria.Main.myPlayer, Terraria.Dust.NewDustDirect(), Terraria.WorldGen.SolidTile(), Terraria.Dust.velocity, Terraria.Entity.velocity, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.HorizontalMovement().