TModLoader: Terraria.Player.UpdateEquips
UpdateEquips()
void Terraria.Player.UpdateEquips (int i) inline
Definition at line 10957 of file Player.cs.
    {
        if (inventory[selectedItem].type == 277 && (!mount.Active || !mount.Cart))
        {
            trident = true;
        }
        bool flag = false;
        for (int j = 0; j < 58; j++)
        {
            int type = inventory[j].type;
            ItemLoader.UpdateInventory(inventory[j], this);
            RefreshInfoAccsFromItemType(inventory[j]);
            RefreshMechanicalAccsFromItemType(type);
            if (type == 4743)
            {
                hasFootball = true;
            }
            if (type == 4131)
            {
                flag = true;
            }
        }
        if (inventory[58].type == 4743)
        {
            hasFootball = true;
        }
        for (int k = 0; k < 10; k++)
        {
            Item item = armor[k];
            if (!item.IsAir && IsItemSlotUnlockedAndUsable(k) && (!item.expertOnly || Main.expertMode) && UpdateEquips_CanItemGrantBenefits(k, item))
            {
                if (item.accessory)
                {
                    GrantPrefixBenefits(item);
                }
                GrantArmorBenefits(item);
            }
        }
        if (flag)
        {
            for (int l = 0; l < 40; l++)
            {
                int type2 = bank4.item[l].type;
                if (ItemID.Sets.WorksInVoidBag[type2])
                {
                    ItemLoader.UpdateInventory(bank4.item[l], this);
                    RefreshInfoAccsFromItemType(bank4.item[l]);
                    RefreshMechanicalAccsFromItemType(type2);
                }
            }
        }
        equippedAnyWallSpeedAcc = false;
        equippedAnyTileSpeedAcc = false;
        equippedAnyTileRangeAcc = false;
        if (whoAmI == Main.myPlayer)
        {
            Main.musicBoxNotModifiedByVolume = -1;
        }
        for (int m = 3; m < 10; m++)
        {
            if (IsItemSlotUnlockedAndUsable(m))
            {
                ApplyEquipFunctional(armor[m], hideVisibleAccessory[m]);
            }
        }
        PlayerLoader.UpdateEquips(this);
        if (kbGlove)
        {
            GetKnockback(DamageClass.Melee) *= 2f;
        }
        if (accFishingBobber)
        {
            fishingSkill += 10;
        }
        if (skyStoneEffects)
        {
            lifeRegen += 2;
            statDefense += 4;
            meleeSpeed += 0.1f;
            allDamage += 0.1f;
            allCrit += 2f;
            pickSpeed -= 0.15f;
            minionKB += 0.5f;
        }
        if (dd2Accessory)
        {
            minionDamage += 0.1f;
            maxTurrets++;
        }
        for (int num = 13; num < 20; num++)
        {
            if (IsItemSlotUnlockedAndUsable(num))
            {
                ApplyEquipVanity(num, armor[num]);
            }
        }
        if (wet && ShouldFloatInWater)
        {
            accFlipper = true;
        }
        if (whoAmI == Main.myPlayer && Main.SceneMetrics.HasClock && accWatch < 3)
        {
            accWatch++;
        }
        if (equippedAnyTileSpeedAcc && inventory[selectedItem].createTile != 4)
        {
            tileSpeed += 0.5f;
        }
        if (chiselSpeed)
        {
            pickSpeed -= 0.25f;
        }
        if (equippedAnyWallSpeedAcc)
        {
            wallSpeed += 0.5f;
        }
        if (equippedAnyTileRangeAcc && whoAmI == Main.myPlayer)
        {
            tileRangeX += 3;
            tileRangeY += 2;
        }
        if (!accThirdEye)
        {
            accThirdEyeCounter = 0;
        }
        RefreshInfoAccsFromTeamPlayers();
        if (whoAmI == Main.myPlayer && hasLuck_LuckyHorseshoe)
        {
            equipmentBasedLuckBonus += 0.05f;
        }
        if (whoAmI == Main.myPlayer && hasLuck_LuckyCoin)
        {
            equipmentBasedLuckBonus += 0.05f;
        }
        if (!accDreamCatcher && dpsStarted)
        {
            dpsStarted = false;
            dpsEnd = DateTime.Now;
        }
        if (HeldItem.type == 4760 && ownedProjectileCounts[866] < 1)
        {
            hasRaisableShield = true;
        }
        int num2 = 0;
        int num3 = 10 + num2;
        if (armor[num2].type == 5101 || armor[num3].type == 5101)
        {
            DoEyebrellaRainEffect();
            eyebrellaCloud = true;
        }
        if (lastEquipmentBasedLuckBonus != equipmentBasedLuckBonus)
        {
            lastEquipmentBasedLuckBonus = equipmentBasedLuckBonus;
            luckNeedsSync = true;
        }
    }
References Terraria.Player.accDreamCatcher, Terraria.Item.accessory, Terraria.Player.accFishingBobber, Terraria.Player.accFlipper, Terraria.Player.accThirdEye, Terraria.Player.accThirdEyeCounter, Terraria.Player.accWatch, Terraria.Mount.Active, Terraria.Player.allCrit, Terraria.Player.allDamage, Terraria.Player.ApplyEquipFunctional(), Terraria.Player.ApplyEquipVanity(), Terraria.Player.armor, Terraria.Player.bank4, Terraria.Mount.Cart, Terraria.Player.chiselSpeed, Terraria.Player.dd2Accessory, Terraria.Player.DoEyebrellaRainEffect(), Terraria.Player.dpsEnd, Terraria.Player.dpsStarted, Terraria.Player.equipmentBasedLuckBonus, Terraria.Player.equippedAnyTileRangeAcc, Terraria.Player.equippedAnyTileSpeedAcc, Terraria.Player.equippedAnyWallSpeedAcc, Terraria.Main.expertMode, Terraria.Item.expertOnly, Terraria.Player.eyebrellaCloud, Terraria.Player.fishingSkill, Terraria.Player.GetKnockback(), Terraria.Player.GrantArmorBenefits(), Terraria.Player.GrantPrefixBenefits(), Terraria.Player.hasFootball, Terraria.Player.hasLuck_LuckyCoin, Terraria.Player.hasLuck_LuckyHorseshoe, Terraria.Player.hasRaisableShield, Terraria.Player.HeldItem, Terraria.Player.hideVisibleAccessory, Terraria.Player.inventory, Terraria.Item.IsAir, Terraria.Player.IsItemSlotUnlockedAndUsable(), Terraria.Chest.item, Terraria.Player.kbGlove, Terraria.Player.lastEquipmentBasedLuckBonus, Terraria.Player.lifeRegen, Terraria.Player.luckNeedsSync, Terraria.Player.maxTurrets, Terraria.ModLoader.DamageClass.Melee, Terraria.Player.meleeSpeed, Terraria.Player.minionDamage, Terraria.Player.minionKB, Terraria.Player.mount, Terraria.Main.myPlayer, Terraria.Player.ownedProjectileCounts, Terraria.Player.pickSpeed, Terraria.Player.RefreshInfoAccsFromItemType(), Terraria.Player.RefreshInfoAccsFromTeamPlayers(), Terraria.Player.RefreshMechanicalAccsFromItemType(), Terraria.Main.SceneMetrics, Terraria.Player.selectedItem, Terraria.Player.ShouldFloatInWater, Terraria.Player.skyStoneEffects, Terraria.Player.statDefense, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Player.tileSpeed, Terraria.Player.trident, Terraria.Item.type, Terraria.ModLoader.PlayerLoader.UpdateEquips(), Terraria.Player.UpdateEquips_CanItemGrantBenefits(), Terraria.ModLoader.ItemLoader.UpdateInventory(), Terraria.Player.wallSpeed, Terraria.Entity.wet, Terraria.Entity.whoAmI, and Terraria.ID.ItemID.Sets.WorksInVoidBag.
Referenced by Terraria.Player.Update().