TModLoader: Terraria.Player.ApplyPaint
ApplyPaint()
void Terraria.Player.ApplyPaint (int x, int y, bool paintingAWall, bool applyItemAnimation, Item targetItem) inline private
Definition at line 40707 of file Player.cs.
    {
        byte paint = targetItem.paint;
        if (paintingAWall)
        {
            if (Main.tile[x, y].wallColor() != paint && WorldGen.paintWall(x, y, paint, broadCast: true))
            {
                if (ItemLoader.ConsumeItem(targetItem, this))
                {
                    targetItem.stack--;
                }
                if (targetItem.stack <= 0)
                {
                    targetItem.SetDefaults();
                }
                if (applyItemAnimation)
                {
                    ApplyItemTime(inventory[selectedItem], wallSpeed);
                }
            }
        }
        else if (Main.tile[x, y].color() != paint && WorldGen.paintTile(x, y, paint, broadCast: true))
        {
            if (ItemLoader.ConsumeItem(targetItem, this))
            {
                targetItem.stack--;
            }
            if (targetItem.stack <= 0)
            {
                targetItem.SetDefaults();
            }
            if (applyItemAnimation)
            {
                ApplyItemTime(inventory[selectedItem], tileSpeed);
            }
        }
    }
References Terraria.Player.ApplyItemTime(), Terraria.ModLoader.ItemLoader.ConsumeItem(), Terraria.Player.inventory, Terraria.WorldGen.paintTile(), Terraria.WorldGen.paintWall(), Terraria.Player.selectedItem, Terraria.Main.tile, Terraria.Player.tileSpeed, and Terraria.Player.wallSpeed.
Referenced by Terraria.Player.TryPainting().