TModLoader: Terraria.Player.PickAmmo
PickAmmo() [1/2]
void Terraria.Player.PickAmmo (Item sItem, ref int projToShoot, ref float speed, ref bool canShoot, ref int totalDamage, ref float KnockBack, out int usedAmmoItemId, bool dontConsume = false) inline package
Definition at line 54079 of file Player.cs.
    {
        usedAmmoItemId = 0;
        Item item = ChooseAmmo(sItem);
        canShoot = item != null;
        bool shootWithNoAmmo = false;
        if (!canShoot && !ItemLoader.NeedsAmmo(sItem, this))
        {
            item = ContentSamples.ItemsByType[sItem.useAmmo];
            if (item.ammo == sItem.useAmmo)
            {
                shootWithNoAmmo = (canShoot = true);
            }
        }
        if (!canShoot)
        {
            return;
        }
        usedAmmoItemId = item.type;
        StatModifier ammoDamage = GetTotalDamage(item.DamageType);
        if (AmmoID.Sets.IsArrow[item.ammo])
        {
            ammoDamage = ammoDamage.CombineWith(arrowDamage);
        }
        if (AmmoID.Sets.IsBullet[item.ammo])
        {
            ammoDamage = ammoDamage.CombineWith(bulletDamage);
        }
        if (AmmoID.Sets.IsSpecialist[item.ammo])
        {
            ammoDamage = ammoDamage.CombineWith(specialistDamage);
        }
        ammoDamage.Base = 0f;
        ammoDamage.Flat = totalDamage;
        ref float Damage = ref ammoDamage.Flat;
        int pickedProjectileId = -1;
        if (PickAmmo_TryFindingSpecificMatches(sItem.type, item.type, out pickedProjectileId))
        {
            projToShoot = pickedProjectileId;
        }
        else if (sItem.type == 1946)
        {
            projToShoot = 338 + item.type - 771;
        }
        else if (sItem.type == 3930)
        {
            projToShoot = 715 + item.type - AmmoID.Rocket;
        }
        else if (sItem.useAmmo == AmmoID.Rocket)
        {
            projToShoot += item.shoot;
        }
        else if (sItem.useAmmo == AmmoID.Solution)
        {
            projToShoot += item.shoot;
        }
        else if (item.shoot > 0)
        {
            projToShoot = item.shoot;
        }
        if (sItem.type == 3019 && projToShoot == 1)
        {
            projToShoot = 485;
        }
        if (sItem.type == 3052)
        {
            projToShoot = 495;
        }
        if (sItem.type == 4953 && projToShoot == 1)
        {
            projToShoot = 932;
        }
        if (sItem.type == 4381)
        {
            projToShoot = 819;
        }
        if (sItem.type == 4058 && projToShoot == 474)
        {
            projToShoot = 117;
        }
        if (projToShoot == 42)
        {
            if (item.type == 370)
            {
                projToShoot = 65;
                Damage += 5f;
            }
            else if (item.type == 408)
            {
                projToShoot = 68;
                Damage += 5f;
            }
            else if (item.type == 1246)
            {
                projToShoot = 354;
                Damage += 5f;
            }
        }
        if (inventory[selectedItem].type == 2888 && projToShoot == 1)
        {
            projToShoot = 469;
        }
        if (hasMoltenQuiver && projToShoot == 1)
        {
            projToShoot = 2;
            Damage += 2f;
        }
        speed += item.shootSpeed;
        if (magicQuiver && (sItem.useAmmo == AmmoID.Arrow || sItem.useAmmo == AmmoID.Stake))
        {
            KnockBack *= 1.1f;
            speed *= 1.1f;
        }
        if ((sItem.useAmmo == AmmoID.Arrow || sItem.useAmmo == AmmoID.Stake) && archery && speed < 20f)
        {
            speed *= 1.2f;
            if (speed > 20f)
            {
                speed = 20f;
            }
        }
        KnockBack += item.knockBack;
        ItemLoader.PickAmmo(sItem, item, this, ref projToShoot, ref speed, ref ammoDamage, ref KnockBack);
        totalDamage = (int)(ammoDamage.ApplyTo(item.damage) + 5E-06f);
        if (!dontConsume && !shootWithNoAmmo && item.consumable && !IsAmmoFreeThisShot(sItem, item, projToShoot))
        {
            CombinedHooks.OnConsumeAmmo(this, sItem, item);
            item.stack--;
            if (item.stack <= 0)
            {
                item.active = false;
                item.TurnToAir();
            }
        }
    }
References Terraria.Item.ammo, Terraria.Player.archery, Terraria.ID.AmmoID.Arrow, Terraria.Player.arrowDamage, Terraria.Player.bulletDamage, Terraria.Player.ChooseAmmo(), Terraria.Item.consumable, Terraria.GameContent.Damage, Terraria.Item.damage, Terraria.Item.DamageType, Terraria.Player.GetTotalDamage(), Terraria.Player.hasMoltenQuiver, Terraria.Player.inventory, Terraria.Player.IsAmmoFreeThisShot(), Terraria.ID.AmmoID.Sets.IsArrow, Terraria.ID.AmmoID.Sets.IsBullet, Terraria.ID.AmmoID.Sets.IsSpecialist, Terraria.ID.ContentSamples.ItemsByType, Terraria.Item.knockBack, Terraria.Player.magicQuiver, Terraria.ModLoader.ItemLoader.NeedsAmmo(), Terraria.ModLoader.CombinedHooks.OnConsumeAmmo(), Terraria.ModLoader.ItemLoader.PickAmmo(), Terraria.Player.PickAmmo_TryFindingSpecificMatches(), Terraria.ID.AmmoID.Rocket, Terraria.Player.selectedItem, Terraria.Item.shoot, Terraria.Item.shootSpeed, Terraria.ID.AmmoID.Solution, Terraria.Player.specialistDamage, Terraria.Item.stack, Terraria.ID.AmmoID.Stake, Terraria.Item.TurnToAir(), and Terraria.Item.type.