TModLoader: Terraria.Player.RotatedRelativePoint
RotatedRelativePoint()
Vector2 Terraria.Player.RotatedRelativePoint (Vector2 pos, bool reverseRotation = false, bool addGfxOffY = true) inline
Takes an input position and returns the position adjusted to the players visual rotation and offset. This accounts for the player being shifted up or down and rotated while riding a mount, sitting in a chair, and sleeping.
Parameters
pos
reverseRotation
addGfxOffY
Returns
    {
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        float num = (reverseRotation ? (0f - fullRotation) : fullRotation);
        if (sleeping.isSleeping)
        {
            num = 0f;
        }
        Vector2 vector = base.Bottom + new Vector2(0f, gfxOffY);
        int num2 = mount.PlayerOffset / 2 + 4;
        Vector2 vector2 = new Vector2(0f, (float)(-num2)) + Utils.RotatedBy(new Vector2(0f, (float)num2), num);
        if (addGfxOffY)
        {
            pos.Y += gfxOffY;
        }
        pos = vector + (pos - vector).RotatedBy(num) + vector2;
        if (sleeping.isSleeping)
        {
            sleeping.GetSleepingOffsetInfo(this, out var posOffset);
            pos += posOffset;
        }
        if (sitting.isSitting)
        {
            sitting.GetSittingOffsetInfo(this, out var posOffset2, out var seatAdjustment);
            pos += posOffset2 + new Vector2(0f, seatAdjustment);
        }
        return pos;
    }
References Terraria.Player.fullRotation, Terraria.GameContent.PlayerSittingHelper.GetSittingOffsetInfo(), Terraria.GameContent.PlayerSleepingHelper.GetSleepingOffsetInfo(), Terraria.Player.gfxOffY, Terraria.GameContent.PlayerSittingHelper.isSitting, Terraria.GameContent.PlayerSleepingHelper.isSleeping, Terraria.Utils.RotatedBy(), Terraria.Player.sitting, and Terraria.Player.sleeping.
Referenced by Terraria.Projectile.AI_019_Spears(), Terraria.Projectile.AI_019_Spears_Old(), Terraria.Projectile.AI_075(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.AI_142_MonkStaffT2And3(), Terraria.Projectile.AI_158_GetHomeLocation(), Terraria.Projectile.AI_160_Kites(), Terraria.Projectile.AI_161_RapierStabs(), Terraria.Projectile.AI_190_NightsEdge(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.Main.DrawProj_DrawNormalProjs(), Terraria.Main.DrawProj_FishingLine(), Terraria.Main.DrawProj_Spear(), Terraria.Projectile.FishingCheck(), Terraria.Main.GetPlayerArmPosition(), Terraria.Player.GetPointOnSwungItemPath(), Terraria.Player.ItemCheck_EmitHeldItemLight(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.RotateRelativePoint(), Terraria.Player.TryUsingDiggerCart(), and Terraria.DelegateMethods.Mount.WolfMouthPosition().