TModLoader: Terraria.Player.ItemCheck_StartActualUse
ItemCheck_StartActualUse()
void Terraria.Player.ItemCheck_StartActualUse (Item sItem) inline private
    {
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        bool flag = sItem.type == 4711;
        if (sItem.pick > 0 || sItem.axe > 0 || sItem.hammer > 0 || flag)
        {
            toolTime = 1;
        }
        if (grappling[0] > -1 || sItem.useTurnOnAnimationStart)
        {
            pulley = false;
            pulleyDir = 1;
            if (controlRight)
            {
                direction = 1;
            }
            else if (controlLeft)
            {
                direction = -1;
            }
        }
        StartChanneling(sItem);
        attackCD = 0;
        ResetMeleeHitCooldowns();
        ApplyItemAnimation(sItem);
        bool flag2 = ItemID.Sets.SkipsInitialUseSound[sItem.type];
        if (sItem.UseSound.HasValue && !flag2)
        {
            SoundEngine.PlaySound(sItem.UseSound, base.Center);
        }
    }
References Terraria.Player.ApplyItemAnimation(), Terraria.Player.attackCD, Terraria.Player.controlLeft, Terraria.Player.controlRight, Terraria.Entity.direction, Terraria.Player.grappling, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.pulley, Terraria.Player.pulleyDir, Terraria.Player.ResetMeleeHitCooldowns(), Terraria.ID.ItemID.Sets.SkipsInitialUseSound, Terraria.Player.StartChanneling(), and Terraria.Player.toolTime.
Referenced by Terraria.Player.ItemCheck_Inner().