TModLoader: Terraria.Player.CheckMana
CheckMana() [2/2]
bool Terraria.Player.CheckMana (Item item, int amount = -1, bool pay = false, bool blockQuickMana = false) inline
Determines if this player has enough mana to use an item.
If the player doesn't have enough mana and blockQuickMana is false, the player will activate any missing mana effects they have and try again.
The pay parameter can be used to consume the mana amount.
Parameters
item The item to use.
amount The amount of mana needed. If -1, calculate using M:Terraria.Player.GetManaCost(Terraria.Item).
pay If true, actually use the mana requested.
blockQuickMana If true, prevent on missing mana effects like the Mana Flower from activating if the player doesn't have enough mana.
Returns
true if the player has enough mana to use the item, false otherwise.
Definition at line 58647 of file Player.cs.
    {
        if (amount <= -1)
        {
            amount = GetManaCost(item);
        }
        if (statMana >= amount)
        {
            if (pay)
            {
                CombinedHooks.OnConsumeMana(this, item, amount);
                statMana -= amount;
            }
            return true;
        }
        if (blockQuickMana)
        {
            return false;
        }
        CombinedHooks.OnMissingMana(this, item, amount);
        if (statMana < amount && manaFlower)
        {
            QuickMana();
        }
        if (statMana >= amount)
        {
            if (pay)
            {
                CombinedHooks.OnConsumeMana(this, item, amount);
                statMana -= amount;
            }
            return true;
        }
        return false;
    }
References Terraria.Player.GetManaCost(), Terraria.Player.manaFlower, Terraria.ModLoader.CombinedHooks.OnConsumeMana(), Terraria.ModLoader.CombinedHooks.OnMissingMana(), Terraria.Player.QuickMana(), and Terraria.Player.statMana.