TModLoader: Terraria.Player.AdjTiles
AdjTiles()
void Terraria.Player.AdjTiles () inline
Definition at line 34464 of file Player.cs.
    {
        int num = 4;
        int num2 = 3;
        if (ateArtisanBread)
        {
            num += 4;
            num2 += 4;
        }
        for (int i = 0; i < adjTile.Length; i++)
        {
            oldAdjTile[i] = adjTile[i];
            adjTile[i] = false;
        }
        oldAdjWater = adjWater;
        adjWater = false;
        oldAdjHoney = adjHoney;
        adjHoney = false;
        oldAdjLava = adjLava;
        adjLava = false;
        oldAdjShimmer = adjShimmer;
        adjShimmer = false;
        alchemyTable = false;
        int num3 = (int)((position.X + (float)(width / 2)) / 16f);
        int num4 = (int)((position.Y + (float)height) / 16f);
        for (int j = num3 - num; j <= num3 + num; j++)
        {
            for (int k = num4 - num2; k < num4 + num2; k++)
            {
                if (Main.tile[j, k].active())
                {
                    adjTile[Main.tile[j, k].type] = true;
                    switch (Main.tile[j, k].type)
                    {
                    case 77:
                    case 302:
                        adjTile[17] = true;
                        break;
                    case 133:
                        adjTile[17] = true;
                        adjTile[77] = true;
                        break;
                    case 134:
                        adjTile[16] = true;
                        break;
                    case 354:
                    case 469:
                    case 487:
                        adjTile[14] = true;
                        break;
                    case 355:
                        adjTile[13] = true;
                        adjTile[14] = true;
                        alchemyTable = true;
                        break;
                    }
                    TileLoader.AdjTiles(this, Main.tile[j, k].type);
                }
                if ((Main.tile[j, k].liquid > 200 && Main.tile[j, k].liquidType() == 0) || TileID.Sets.CountsAsWaterSource[Main.tile[j, k].type])
                {
                    adjWater = true;
                }
                if ((Main.tile[j, k].liquid > 200 && Main.tile[j, k].liquidType() == 2) || TileID.Sets.CountsAsHoneySource[Main.tile[j, k].type])
                {
                    adjHoney = true;
                }
                if ((Main.tile[j, k].liquid > 200 && Main.tile[j, k].liquidType() == 1) || TileID.Sets.CountsAsLavaSource[Main.tile[j, k].type])
                {
                    adjLava = true;
                }
                if ((Main.tile[j, k].liquid > 200 && Main.tile[j, k].liquidType() == 3) || TileID.Sets.CountsAsShimmerSource[Main.tile[j, k].type])
                {
                    adjShimmer = true;
                }
            }
        }
        if (!Main.playerInventory)
        {
            return;
        }
        bool flag = false;
        for (int l = 0; l < adjTile.Length; l++)
        {
            if (oldAdjTile[l] != adjTile[l])
            {
                flag = true;
                break;
            }
        }
        if (adjWater != oldAdjWater)
        {
            flag = true;
        }
        if (adjHoney != oldAdjHoney)
        {
            flag = true;
        }
        if (adjLava != oldAdjLava)
        {
            flag = true;
        }
        if (adjShimmer != oldAdjShimmer)
        {
            flag = true;
        }
        if (flag)
        {
            Recipe.FindRecipes();
        }
    }
References Terraria.Player.adjHoney, Terraria.Player.adjLava, Terraria.Player.adjShimmer, Terraria.Player.adjTile, Terraria.ModLoader.TileLoader.AdjTiles(), Terraria.Player.adjWater, Terraria.Player.alchemyTable, Terraria.Player.ateArtisanBread, Terraria.ID.TileID.Sets.CountsAsHoneySource, Terraria.ID.TileID.Sets.CountsAsLavaSource, Terraria.ID.TileID.Sets.CountsAsShimmerSource, Terraria.ID.TileID.Sets.CountsAsWaterSource, Terraria.Recipe.FindRecipes(), Terraria.Entity.height, Terraria.Player.oldAdjHoney, Terraria.Player.oldAdjLava, Terraria.Player.oldAdjShimmer, Terraria.Player.oldAdjTile, Terraria.Player.oldAdjWater, Terraria.Main.playerInventory, Terraria.Entity.position, Terraria.Main.tile, and Terraria.Entity.width.
Referenced by Terraria.Main.DoUpdate_WhilePaused(), and Terraria.Player.Update().