TModLoader: Terraria.Player.VolatileGelatin
VolatileGelatin()
void Terraria.Player.VolatileGelatin (Item sourceItem) inline
Definition at line 41672 of file Player.cs.
    {
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        if (Main.myPlayer != whoAmI)
        {
            return;
        }
        volatileGelatinCounter++;
        if (volatileGelatinCounter <= 40)
        {
            return;
        }
        volatileGelatinCounter = 0;
        int damage = 65;
        float knockBack = 7f;
        float num = 640f;
        NPC nPC = null;
        for (int i = 0; i < 200; i++)
        {
            NPC nPC2 = Main.npc[i];
            if (nPC2 != null && nPC2.active && nPC2.CanBeChasedBy(this) && Collision.CanHit(this, nPC2))
            {
                float num2 = Vector2.Distance(nPC2.Center, base.Center);
                if (num2 < num)
                {
                    num = num2;
                    nPC = nPC2;
                }
            }
        }
        if (nPC != null)
        {
            Vector2 v = nPC.Center - base.Center;
            v = v.SafeNormalize(Vector2.Zero) * 12f;
            v.Y -= 1.3f;
            Projectile.NewProjectile(GetProjectileSource_Accessory(sourceItem), base.Center.X, base.Center.Y, v.X, v.Y, 937, damage, knockBack, whoAmI);
        }
    }
References Terraria.Collision.CanHit(), Terraria.Player.GetProjectileSource_Accessory(), Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.Player.volatileGelatinCounter, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ApplyEquipFunctional().