TModLoader: Terraria.Player.PickupItem
PickupItem()
Item Terraria.Player.PickupItem (int playerIndex, int worldItemArrayIndex, Item itemToPickUp) inline private
    {
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        if (ItemID.Sets.NebulaPickup[itemToPickUp.type])
        {
            SoundEngine.PlaySound(7, (int)position.X, (int)position.Y);
            int num = itemToPickUp.buffType;
            itemToPickUp = new Item();
            if (Main.netMode == 1)
            {
                NetMessage.SendData(102, -1, -1, null, playerIndex, num, base.Center.X, base.Center.Y);
            }
            else
            {
                NebulaLevelup(num);
            }
        }
        if (itemToPickUp.type == 58 || itemToPickUp.type == 1734 || itemToPickUp.type == 1867)
        {
            SoundEngine.PlaySound(7, (int)position.X, (int)position.Y);
            Heal(20);
            itemToPickUp = new Item();
        }
        else if (itemToPickUp.type == 184 || itemToPickUp.type == 1735 || itemToPickUp.type == 1868)
        {
            SoundEngine.PlaySound(7, (int)position.X, (int)position.Y);
            statMana += 100;
            if (Main.myPlayer == whoAmI)
            {
                ManaEffect(100);
            }
            if (statMana > statManaMax2)
            {
                statMana = statManaMax2;
            }
            itemToPickUp = new Item();
        }
        else if (itemToPickUp.type == 4143)
        {
            SoundEngine.PlaySound(7, (int)position.X, (int)position.Y);
            statMana += 50;
            if (Main.myPlayer == whoAmI)
            {
                ManaEffect(50);
            }
            if (statMana > statManaMax2)
            {
                statMana = statManaMax2;
            }
            itemToPickUp = new Item();
        }
        else
        {
            itemToPickUp = GetItem(playerIndex, itemToPickUp, GetItemSettings.PickupItemFromWorld);
        }
        Main.item[worldItemArrayIndex] = itemToPickUp;
        if (Main.netMode == 1)
        {
            NetMessage.SendData(21, -1, -1, null, worldItemArrayIndex);
        }
        return itemToPickUp;
    }
References Terraria.Player.GetItem(), Terraria.Player.Heal(), Terraria.Main.item, Terraria.Player.ManaEffect(), Terraria.Main.myPlayer, Terraria.Player.NebulaLevelup(), Terraria.ID.ItemID.Sets.NebulaPickup, Terraria.Main.netMode, Terraria.GetItemSettings.PickupItemFromWorld, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.Player.statMana, Terraria.Player.statManaMax2, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.GrabItems().