TModLoader: Terraria.Player.UpdatePlacementPreview
UpdatePlacementPreview()
void Terraria.Player.UpdatePlacementPreview (Item sItem) inline private
Definition at line 42642 of file Player.cs.
    {
        if (Main.myPlayer == whoAmI && itemAnimation == 0)
        {
            Tile targetTile = Main.tile[tileTargetX, tileTargetY];
            FigureOutWhatToPlace(targetTile, sItem, out var tileToCreate, out var previewPlaceStyle, out var overrideCanPlace, out var forcedRandom);
            PlantLoader.CheckAndInjectModSapling(tileTargetX, tileTargetY, ref tileToCreate, ref previewPlaceStyle);
            if ((!overrideCanPlace.HasValue || overrideCanPlace.Value) && TileObjectData.CustomPlace(tileToCreate, previewPlaceStyle))
            {
                TileObject.CanPlace(tileTargetX, tileTargetY, tileToCreate, previewPlaceStyle, direction, out var _, onlyCheck: true, forcedRandom);
            }
        }
    }
References Terraria.TileObject.CanPlace(), Terraria.ModLoader.PlantLoader.CheckAndInjectModSapling(), Terraria.ObjectData.TileObjectData.CustomPlace(), Terraria.Entity.direction, Terraria.Player.FigureOutWhatToPlace(), Terraria.Player.itemAnimation, Terraria.Main.myPlayer, Terraria.Main.tile, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ItemCheck_Inner().