TModLoader: Terraria.Player.ExtractinatorUse
ExtractinatorUse()
void Terraria.Player.ExtractinatorUse (int extractType, int extractinatorBlockType) inline private
    {
        int num = 5000;
        int num2 = 25;
        int num3 = 50;
        int num4 = -1;
        int num5 = -1;
        int num6 = -1;
        int num7 = 1;
        switch (extractType)
        {
        case 3347:
            num /= 3;
            num2 *= 2;
            num3 = 20;
            num4 = 10;
            break;
        case 2337:
            num = -1;
            num2 = -1;
            num3 = -1;
            num4 = -1;
            num5 = 1;
            num7 = -1;
            break;
        case 4354:
            num = -1;
            num2 = -1;
            num3 = -1;
            num4 = -1;
            num5 = -1;
            num7 = -1;
            num6 = 1;
            break;
        }
        int num8 = -1;
        int num9 = 1;
        if (num4 != -1 && Main.rand.Next(num4) == 0)
        {
            num8 = 3380;
            if (Main.rand.Next(5) == 0)
            {
                num9 += Main.rand.Next(2);
            }
            if (Main.rand.Next(10) == 0)
            {
                num9 += Main.rand.Next(3);
            }
            if (Main.rand.Next(15) == 0)
            {
                num9 += Main.rand.Next(4);
            }
        }
        else if (num7 != -1 && Main.rand.Next(2) == 0)
        {
            if (Main.rand.Next(12000) == 0)
            {
                num8 = 74;
                if (Main.rand.Next(14) == 0)
                {
                    num9 += Main.rand.Next(0, 2);
                }
                if (Main.rand.Next(14) == 0)
                {
                    num9 += Main.rand.Next(0, 2);
                }
                if (Main.rand.Next(14) == 0)
                {
                    num9 += Main.rand.Next(0, 2);
                }
            }
            else if (Main.rand.Next(800) == 0)
            {
                num8 = 73;
                if (Main.rand.Next(6) == 0)
                {
                    num9 += Main.rand.Next(1, 21);
                }
                if (Main.rand.Next(6) == 0)
                {
                    num9 += Main.rand.Next(1, 21);
                }
                if (Main.rand.Next(6) == 0)
                {
                    num9 += Main.rand.Next(1, 21);
                }
                if (Main.rand.Next(6) == 0)
                {
                    num9 += Main.rand.Next(1, 21);
                }
                if (Main.rand.Next(6) == 0)
                {
                    num9 += Main.rand.Next(1, 20);
                }
            }
            else if (Main.rand.Next(60) == 0)
            {
                num8 = 72;
                if (Main.rand.Next(4) == 0)
                {
                    num9 += Main.rand.Next(5, 26);
                }
                if (Main.rand.Next(4) == 0)
                {
                    num9 += Main.rand.Next(5, 26);
                }
                if (Main.rand.Next(4) == 0)
                {
                    num9 += Main.rand.Next(5, 26);
                }
                if (Main.rand.Next(4) == 0)
                {
                    num9 += Main.rand.Next(5, 25);
                }
            }
            else
            {
                num8 = 71;
                if (Main.rand.Next(3) == 0)
                {
                    num9 += Main.rand.Next(10, 26);
                }
                if (Main.rand.Next(3) == 0)
                {
                    num9 += Main.rand.Next(10, 26);
                }
                if (Main.rand.Next(3) == 0)
                {
                    num9 += Main.rand.Next(10, 26);
                }
                if (Main.rand.Next(3) == 0)
                {
                    num9 += Main.rand.Next(10, 25);
                }
            }
        }
        else if (num != -1 && Main.rand.Next(num) == 0)
        {
            num8 = 1242;
        }
        else if (num5 != -1)
        {
            num8 = ((Main.rand.Next(4) != 1) ? 2674 : ((Main.rand.Next(3) != 1) ? 2006 : ((Main.rand.Next(3) == 1) ? 2675 : 2002)));
        }
        else if (num6 != -1 && extractinatorBlockType == 642)
        {
            num8 = ((Main.rand.Next(10) == 1) ? (Main.rand.Next(5) switch
            {
                0 => 4354,
                1 => 4389,
                2 => 4377,
                3 => 5127,
                _ => 4378,
            }) : (Main.rand.Next(5) switch
            {
                0 => 4349,
                1 => 4350,
                2 => 4351,
                3 => 4352,
                _ => 4353,
            }));
        }
        else if (num6 != -1)
        {
            num8 = Main.rand.Next(5) switch
            {
                0 => 4349,
                1 => 4350,
                2 => 4351,
                3 => 4352,
                _ => 4353,
            };
        }
        else if (num2 != -1 && Main.rand.Next(num2) == 0)
        {
            num8 = Main.rand.Next(6) switch
            {
                0 => 181,
                1 => 180,
                2 => 177,
                3 => 179,
                4 => 178,
                _ => 182,
            };
            if (Main.rand.Next(20) == 0)
            {
                num9 += Main.rand.Next(0, 2);
            }
            if (Main.rand.Next(30) == 0)
            {
                num9 += Main.rand.Next(0, 3);
            }
            if (Main.rand.Next(40) == 0)
            {
                num9 += Main.rand.Next(0, 4);
            }
            if (Main.rand.Next(50) == 0)
            {
                num9 += Main.rand.Next(0, 5);
            }
            if (Main.rand.Next(60) == 0)
            {
                num9 += Main.rand.Next(0, 6);
            }
        }
        else if (num3 != -1 && Main.rand.Next(num3) == 0)
        {
            num8 = 999;
            if (Main.rand.Next(20) == 0)
            {
                num9 += Main.rand.Next(0, 2);
            }
            if (Main.rand.Next(30) == 0)
            {
                num9 += Main.rand.Next(0, 3);
            }
            if (Main.rand.Next(40) == 0)
            {
                num9 += Main.rand.Next(0, 4);
            }
            if (Main.rand.Next(50) == 0)
            {
                num9 += Main.rand.Next(0, 5);
            }
            if (Main.rand.Next(60) == 0)
            {
                num9 += Main.rand.Next(0, 6);
            }
        }
        else if (Main.rand.Next(3) == 0)
        {
            if (Main.rand.Next(5000) == 0)
            {
                num8 = 74;
                if (Main.rand.Next(10) == 0)
                {
                    num9 += Main.rand.Next(0, 3);
                }
                if (Main.rand.Next(10) == 0)
                {
                    num9 += Main.rand.Next(0, 3);
                }
                if (Main.rand.Next(10) == 0)
                {
                    num9 += Main.rand.Next(0, 3);
                }
                if (Main.rand.Next(10) == 0)
                {
                    num9 += Main.rand.Next(0, 3);
                }
                if (Main.rand.Next(10) == 0)
                {
                    num9 += Main.rand.Next(0, 3);
                }
            }
            else if (Main.rand.Next(400) == 0)
            {
                num8 = 73;
                if (Main.rand.Next(5) == 0)
                {
                    num9 += Main.rand.Next(1, 21);
                }
                if (Main.rand.Next(5) == 0)
                {
                    num9 += Main.rand.Next(1, 21);
                }
                if (Main.rand.Next(5) == 0)
                {
                    num9 += Main.rand.Next(1, 21);
                }
                if (Main.rand.Next(5) == 0)
                {
                    num9 += Main.rand.Next(1, 21);
                }
                if (Main.rand.Next(5) == 0)
                {
                    num9 += Main.rand.Next(1, 20);
                }
            }
            else if (Main.rand.Next(30) == 0)
            {
                num8 = 72;
                if (Main.rand.Next(3) == 0)
                {
                    num9 += Main.rand.Next(5, 26);
                }
                if (Main.rand.Next(3) == 0)
                {
                    num9 += Main.rand.Next(5, 26);
                }
                if (Main.rand.Next(3) == 0)
                {
                    num9 += Main.rand.Next(5, 26);
                }
                if (Main.rand.Next(3) == 0)
                {
                    num9 += Main.rand.Next(5, 25);
                }
            }
            else
            {
                num8 = 71;
                if (Main.rand.Next(2) == 0)
                {
                    num9 += Main.rand.Next(10, 26);
                }
                if (Main.rand.Next(2) == 0)
                {
                    num9 += Main.rand.Next(10, 26);
                }
                if (Main.rand.Next(2) == 0)
                {
                    num9 += Main.rand.Next(10, 26);
                }
                if (Main.rand.Next(2) == 0)
                {
                    num9 += Main.rand.Next(10, 25);
                }
            }
        }
        else if (extractinatorBlockType == 642)
        {
            num8 = Main.rand.Next(14) switch
            {
                0 => 12,
                1 => 11,
                2 => 14,
                3 => 13,
                4 => 699,
                5 => 700,
                6 => 701,
                7 => 702,
                8 => 364,
                9 => 1104,
                10 => 365,
                11 => 1105,
                12 => 366,
                _ => 1106,
            };
            if (Main.rand.Next(20) == 0)
            {
                num9 += Main.rand.Next(0, 2);
            }
            if (Main.rand.Next(30) == 0)
            {
                num9 += Main.rand.Next(0, 3);
            }
            if (Main.rand.Next(40) == 0)
            {
                num9 += Main.rand.Next(0, 4);
            }
            if (Main.rand.Next(50) == 0)
            {
                num9 += Main.rand.Next(0, 5);
            }
            if (Main.rand.Next(60) == 0)
            {
                num9 += Main.rand.Next(0, 6);
            }
        }
        else
        {
            num8 = Main.rand.Next(8) switch
            {
                0 => 12,
                1 => 11,
                2 => 14,
                3 => 13,
                4 => 699,
                5 => 700,
                6 => 701,
                _ => 702,
            };
            if (Main.rand.Next(20) == 0)
            {
                num9 += Main.rand.Next(0, 2);
            }
            if (Main.rand.Next(30) == 0)
            {
                num9 += Main.rand.Next(0, 3);
            }
            if (Main.rand.Next(40) == 0)
            {
                num9 += Main.rand.Next(0, 4);
            }
            if (Main.rand.Next(50) == 0)
            {
                num9 += Main.rand.Next(0, 5);
            }
            if (Main.rand.Next(60) == 0)
            {
                num9 += Main.rand.Next(0, 6);
            }
        }
        ItemLoader.ExtractinatorUse(ref num8, ref num9, extractType, extractinatorBlockType);
        if (num8 > 0)
        {
            DropItemFromExtractinator(num8, num9);
        }
    }
References Terraria.Player.DropItemFromExtractinator(), Terraria.ModLoader.ItemLoader.ExtractinatorUse(), and Terraria.Main.rand.
Referenced by Terraria.Player.PlaceThing_ItemInExtractinator().