TModLoader: Terraria.Player.GetHelmetDrawOffset
GetHelmetDrawOffset()
Vector2 Terraria.Player.GetHelmetDrawOffset () inline
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0107: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        Vector2 headOffset = Vector2.Zero;
        if (head == 270)
        {
            headOffset = new Vector2(-10f, 0f) * Directions;
            if (direction == -1)
            {
                headOffset.X -= 2f;
            }
        }
        else if (head == 268)
        {
            headOffset = new Vector2(0f, -6f) * Directions;
        }
        else if (head == 222)
        {
            float y = 0f;
            if (hair == 15 || hair == 76 || hair == 108)
            {
                y = 4f;
            }
            headOffset = new Vector2(0f, y) * Directions;
        }
        else if (head == 272)
        {
            if (hair == 15 || hair == 76 || hair == 108)
            {
                headOffset = new Vector2(0f, 4f) * Directions;
            }
        }
        else if (head == 275)
        {
            headOffset = new Vector2(0f, -4f) * Directions;
        }
        return GetHelmetOffsetAddonFromFaceHead(headOffset);
    }
References Terraria.Entity.direction, Terraria.Player.Directions, Terraria.Player.GetHelmetOffsetAddonFromFaceHead(), Terraria.Player.hair, and Terraria.Player.head.
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup_End(), and Terraria.DataStructures.PlayerDrawSet.HeadOnlySetup().