TModLoader: Terraria.Player.SlopeDownMovement
SlopeDownMovement()
void Terraria.Player.SlopeDownMovement () inline
Definition at line 21547 of file Player.cs.
    {
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        sloping = false;
        if (!mount.Active || mount.Type != 48)
        {
            float y = velocity.Y;
            Vector4 vector = Collision.WalkDownSlope(position, velocity, width, height, gravity * gravDir);
            position.X = vector.X;
            position.Y = vector.Y;
            velocity.X = vector.Z;
            velocity.Y = vector.W;
            if (velocity.Y != y)
            {
                sloping = true;
            }
        }
    }
References Terraria.Mount.Active, Terraria.Player.gravDir, Terraria.Player.gravity, Terraria.Entity.height, Terraria.Player.mount, Terraria.Entity.position, Terraria.Player.sloping, Terraria.Mount.Type, Terraria.Entity.velocity, Terraria.Collision.WalkDownSlope(), and Terraria.Entity.width.
Referenced by Terraria.Player.DryCollision(), and Terraria.Player.Update().