TModLoader: Terraria.Player.TorchAttack
TorchAttack()
void Terraria.Player.TorchAttack () inline private
Definition at line 16277 of file Player.cs.
    {
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_0350: Unknown result type (might be due to invalid IL or missing references)
        //IL_0355: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_036e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0372: Unknown result type (might be due to invalid IL or missing references)
        //IL_0377: Unknown result type (might be due to invalid IL or missing references)
        //IL_0381: Unknown result type (might be due to invalid IL or missing references)
        //IL_0383: Unknown result type (might be due to invalid IL or missing references)
        if (whoAmI != Main.myPlayer)
        {
            return;
        }
        if ((double)position.Y < Main.worldSurface * 16.0)
        {
            EndOngoingTorchGodEvent();
            return;
        }
        AddBuff(80, 2);
        torchFunTimer++;
        if (torchFunTimer <= 20)
        {
            return;
        }
        torchFunTimer = 0;
        int num = 0;
        int num4 = 100;
        int value5 = (int)base.Center.X / 16 - num4;
        int value2 = (int)base.Center.X / 16 + num4;
        int value3 = (int)base.Center.Y / 16 - num4;
        int value4 = (int)base.Center.Y / 16 + num4;
        int num11 = Utils.Clamp(value5, 10, Main.maxTilesX - 10);
        value2 = Utils.Clamp(value2, 10, Main.maxTilesX - 10);
        value3 = Utils.Clamp(value3, 10, Main.maxTilesY - 10);
        value4 = Utils.Clamp(value4, 10, Main.maxTilesY - 10);
        for (int i = num11; i <= value2; i++)
        {
            for (int j = value3; j <= value4; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile != null && (tile.active() & (tile.type == 4)) && tile.frameX < 66)
                {
                    _torchAttackPosX[num] = i;
                    _torchAttackPosY[num] = j;
                    num++;
                    if (num >= _torchAttackPosX.Length)
                    {
                        break;
                    }
                }
            }
            if (num >= _torchAttackPosX.Length)
            {
                break;
            }
        }
        if (num == 0 || numberOfTorchAttacksMade >= maxTorchAttacks)
        {
            RelightTorches();
            happyFunTorchTime = false;
            if (Main.netMode == 1)
            {
                NetMessage.SendData(4, -1, -1, null, whoAmI);
            }
            if (numberOfTorchAttacksMade >= 95)
            {
                int number = Item.NewItem(GetItemSource_Misc(6), (int)position.X, (int)position.Y, width, height, 5043);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, number, 1f);
                }
            }
        }
        else
        {
            if (num <= 0)
            {
                return;
            }
            int num5 = Main.rand.Next(num);
            int num6 = _torchAttackPosX[num5];
            int num7 = _torchAttackPosY[num5];
            Tile tile2 = Main.tile[num6, num7];
            if (tile2.type != 4)
            {
                return;
            }
            tile2 = Main.tile[num6, num7];
            if (tile2.frameX < 66)
            {
                float num8 = 8f;
                int num9 = 20;
                if (num9 < 10)
                {
                    num9 = 10;
                }
                tile2 = Main.tile[num6, num7];
                int num10 = (int)MathHelper.Clamp((float)(tile2.frameY / 22), 0f, (float)(TorchID.Count - 1));
                num10 = TorchID.Dust[num10];
                tile2 = Main.tile[num6, num7];
                tile2.frameX += 66;
                unlitTorchX[numberOfTorchAttacksMade] = num6;
                unlitTorchY[numberOfTorchAttacksMade] = num7;
                numberOfTorchAttacksMade++;
                NetMessage.SendTileSquare(-1, num6, num7);
                Vector2 vector = default(Vector2);
                ((Vector2)(ref vector))._002Ector((float)(num6 * 16 + 8), (float)(num7 * 16));
                Vector2 vector2 = base.Center - vector;
                float num2 = ((Vector2)(ref vector2)).Length();
                ((Vector2)(ref vector2)).Normalize();
                vector2 *= num8;
                int num3 = Projectile.NewProjectile(GetProjectileSource_Misc(10), vector, vector2, 949, num9, 1f, whoAmI, num10, num2);
                Main.projectile[num3].ai[0] = num10;
                Main.projectile[num3].ai[1] = num2;
                Main.projectile[num3].netUpdate = true;
                if ((num == 1 && numberOfTorchAttacksMade >= 95) || numberOfTorchAttacksMade >= maxTorchAttacks)
                {
                    torchFunTimer = -180;
                }
            }
        }
    }
References Terraria.Player._torchAttackPosX, Terraria.Player._torchAttackPosY, Terraria.Tile.active(), Terraria.Player.AddBuff(), Terraria.ID.TorchID.Dust, Terraria.Player.EndOngoingTorchGodEvent(), Terraria.Tile.frameX, Terraria.Player.GetItemSource_Misc(), Terraria.Player.GetProjectileSource_Misc(), Terraria.Player.happyFunTorchTime, Terraria.Entity.height, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Player.maxTorchAttacks, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Projectile.NewProjectile(), Terraria.Player.numberOfTorchAttacksMade, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Player.RelightTorches(), Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.Main.tile, Terraria.Player.torchFunTimer, Terraria.Tile.type, Terraria.Player.unlitTorchX, Terraria.Player.unlitTorchY, Terraria.Entity.whoAmI, Terraria.Entity.width, and Terraria.Main.worldSurface.
Referenced by Terraria.Player.TryRecalculatingTorchLuck().