TModLoader: Terraria.Player.QuickSpawnClonedItem
QuickSpawnClonedItem()
int Terraria.Player.QuickSpawnClonedItem (IEntitySource source, Item item, int stack = 1) inline
Will spawn an item like M:Terraria.Player.QuickSpawnItem(Terraria.DataStructures.IEntitySource,System.Int32,System.Int32), but clones it (handy when you need to retain item infos)
Parameters
source The spawn context
item The item you want to be cloned
stack The stack to give the item. Note that this will override maxStack if it's higher.
    {
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        int index = Item.NewItem(source, getRect(), item);
        Main.item[index].stack = stack;
        if (Main.netMode == 1)
        {
            NetMessage.SendData(21, -1, -1, null, index, 1f);
        }
        return index;
    }
References Terraria.Player.getRect(), Terraria.Main.item, Terraria.Main.netMode, Terraria.Item.NewItem(), and Terraria.NetMessage.SendData().
Referenced by Terraria.Player.QuickSpawnClonedItemDirect(), Terraria.Player.QuickSpawnItem(), and Terraria.Player.QuickSpawnItemDirect().