TModLoader: Terraria.Player.RefreshInfoAccs
RefreshInfoAccs()
void Terraria.Player.RefreshInfoAccs () inline
    {
        bool flag = false;
        accWatch = 0;
        accCompass = 0;
        accDepthMeter = 0;
        accFishFinder = false;
        accWeatherRadio = false;
        accCalendar = false;
        accThirdEye = false;
        accJarOfSouls = false;
        accCritterGuide = false;
        accStopwatch = false;
        accOreFinder = false;
        accDreamCatcher = false;
        PlayerLoader.ResetInfoAccessories(this);
        for (int i = 0; i < 58; i++)
        {
            int type4 = inventory[i].type;
            RefreshInfoAccsFromItemType(inventory[i]);
            if (type4 == 4131)
            {
                flag = true;
            }
        }
        for (int j = 0; j < 10; j++)
        {
            _ = armor[j].type;
            RefreshInfoAccsFromItemType(armor[j]);
        }
        if (flag)
        {
            for (int k = 0; k < 40; k++)
            {
                int type3 = bank4.item[k].type;
                if (type3 < 0 || ItemID.Sets.WorksInVoidBag[type3])
                {
                    RefreshInfoAccsFromItemType(bank4.item[k]);
                }
            }
        }
        RefreshInfoAccsFromTeamPlayers();
    }
References Terraria.Player.accCalendar, Terraria.Player.accCompass, Terraria.Player.accCritterGuide, Terraria.Player.accDepthMeter, Terraria.Player.accDreamCatcher, Terraria.Player.accFishFinder, Terraria.Player.accJarOfSouls, Terraria.Player.accOreFinder, Terraria.Player.accStopwatch, Terraria.Player.accThirdEye, Terraria.Player.accWatch, Terraria.Player.accWeatherRadio, Terraria.Player.armor, Terraria.Player.bank4, Terraria.Player.inventory, Terraria.Chest.item, Terraria.Player.RefreshInfoAccsFromItemType(), Terraria.Player.RefreshInfoAccsFromTeamPlayers(), Terraria.ModLoader.PlayerLoader.ResetInfoAccessories(), Terraria.Item.type, and Terraria.ID.ItemID.Sets.WorksInVoidBag.