TModLoader: Terraria.Player.DropItems
DropItems()
void Terraria.Player.DropItems () inline
    {
        IEntitySource itemSource_Death = GetItemSource_Death();
        List<Item> startInventory = PlayerLoader.GetStartingItems(this, from item in DropItems_GetDefaults()
            where !item.IsAir
            select item, mediumCoreDeath: true);
        Dictionary<int, int> startCounts = new Dictionary<int, int>();
        foreach (Item item2 in startInventory)
        {
            if (!startCounts.ContainsKey(item2.netID))
            {
                startCounts[item2.netID] = 0;
            }
            startCounts[item2.netID] += item2.stack;
        }
        startCounts[ModContent.ItemType<StartBag>()] = 1;
        AccessorySlotLoader.ModSlotPlayer(this).DropItems(itemSource_Death);
        for (int i = 0; i < 59; i++)
        {
            if (inventory[i].stack > 0)
            {
                int type2 = inventory[i].type;
                Item itemToDrop = inventory[i];
                if (startCounts.TryGetValue(type2, out var startCount))
                {
                    int j = Math.Min(itemToDrop.stack, startCount);
                    itemToDrop.stack -= j;
                    startCounts[type2] -= j;
                }
                if (itemToDrop.stack > 0)
                {
                    TryDroppingSingleItem(itemSource_Death, itemToDrop);
                }
            }
            inventory[i].TurnToAir();
            if (i < armor.Length)
            {
                TryDroppingSingleItem(itemSource_Death, armor[i]);
            }
            if (i < dye.Length)
            {
                TryDroppingSingleItem(itemSource_Death, dye[i]);
            }
            if (i < miscEquips.Length)
            {
                TryDroppingSingleItem(itemSource_Death, miscEquips[i]);
            }
            if (i < miscDyes.Length)
            {
                TryDroppingSingleItem(itemSource_Death, miscDyes[i]);
            }
        }
        EquipmentLoadout[] loadouts = Loadouts;
        for (int type = 0; type < loadouts.Length; type++)
        {
            loadouts[type].TryDroppingItems(this, itemSource_Death);
        }
        DropItems_End(startInventory);
    }
References Terraria.Player.armor, Terraria.ModLoader.Default.ModAccessorySlotPlayer.DropItems(), Terraria.Player.DropItems_End(), Terraria.Player.DropItems_GetDefaults(), Terraria.Player.dye, Terraria.Player.GetItemSource_Death(), Terraria.ModLoader.PlayerLoader.GetStartingItems(), Terraria.Player.inventory, Terraria.Player.Loadouts, Terraria.Player.miscDyes, Terraria.Player.miscEquips, Terraria.ModLoader.AccessorySlotLoader.ModSlotPlayer(), Terraria.Player.TryDroppingSingleItem(), Terraria.Item.TurnToAir(), and Terraria.Item.type.
Referenced by Terraria.Player.KillMe().