TModLoader: Terraria.Player.ItemCheck_ApplyPetBuffs
ItemCheck_ApplyPetBuffs()
void Terraria.Player.ItemCheck_ApplyPetBuffs (Item sItem) inline private
Definition at line 53683 of file Player.cs.
    {
        if (whoAmI == Main.myPlayer && sItem.type == 603 && Main.runningCollectorsEdition)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 669)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 115)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 3060)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 3628)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 3062)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 3577)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 425)
        {
            int num = Main.rand.Next(3);
            if (num == 0)
            {
                num = 27;
            }
            if (num == 1)
            {
                num = 101;
            }
            if (num == 2)
            {
                num = 102;
            }
            for (int i = 0; i < maxBuffs; i++)
            {
                if (buffType[i] == 27 || buffType[i] == 101 || buffType[i] == 102)
                {
                    DelBuff(i);
                    i--;
                }
            }
            AddBuff(num, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 753)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 994)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1169)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1170)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1171)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1172)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1180)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1181)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1182)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1183)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1242)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1157)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1309)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1311)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1837)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1312)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1798)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1799)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1802)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1810)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1927)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 1959)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 2364)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 2365)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 3043)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer && sItem.type == 2420)
        {
            AddBuff(sItem.buffType, 3600);
        }
        if (whoAmI == Main.myPlayer)
        {
            switch (sItem.type)
            {
            case 2535:
            case 2551:
            case 2584:
            case 2587:
            case 2621:
            case 2749:
            case 3249:
            case 3474:
            case 3531:
            case 4269:
            case 4273:
            case 4281:
            case 4607:
            case 4758:
            case 5005:
            case 5069:
            case 5114:
                AddBuff(sItem.buffType, 3600);
                break;
            }
        }
        if (whoAmI == Main.myPlayer)
        {
            switch (sItem.type)
            {
            case 3855:
            case 3856:
            case 3857:
            case 4365:
            case 4366:
            case 4425:
            case 4550:
            case 4551:
            case 4603:
            case 4604:
            case 4605:
            case 4701:
            case 4735:
            case 4736:
            case 4737:
            case 4777:
            case 4797:
            case 4798:
            case 4799:
            case 4800:
            case 4801:
            case 4802:
            case 4803:
            case 4804:
            case 4805:
            case 4806:
            case 4807:
            case 4808:
            case 4809:
            case 4810:
            case 4811:
            case 4812:
            case 4813:
            case 4814:
            case 4815:
            case 4816:
            case 4817:
            case 4960:
            case 5088:
            case 5089:
            case 5090:
            case 5091:
            case 5098:
            case 5131:
            case 5276:
            case 5297:
            case 5332:
            case 5333:
            case 5400:
                AddBuff(sItem.buffType, 3600);
                break;
            }
        }
    }
References Terraria.Player.AddBuff(), Terraria.Player.buffType, Terraria.Player.DelBuff(), Terraria.Player.maxBuffs, Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Main.runningCollectorsEdition, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ItemCheck_Inner().