TModLoader: Terraria.Player.UpdateLifeRegen
UpdateLifeRegen()
void Terraria.Player.UpdateLifeRegen () inline
    {
        //IL_0a81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a86: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0800: Unknown result type (might be due to invalid IL or missing references)
        //IL_0805: Unknown result type (might be due to invalid IL or missing references)
        //IL_0848: Unknown result type (might be due to invalid IL or missing references)
        //IL_085f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0864: Unknown result type (might be due to invalid IL or missing references)
        //IL_086e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0870: Unknown result type (might be due to invalid IL or missing references)
        //IL_087c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0883: Unknown result type (might be due to invalid IL or missing references)
        //IL_0888: Unknown result type (might be due to invalid IL or missing references)
        //IL_0893: Unknown result type (might be due to invalid IL or missing references)
        //IL_0898: Unknown result type (might be due to invalid IL or missing references)
        //IL_089a: Unknown result type (might be due to invalid IL or missing references)
        //IL_089f: Unknown result type (might be due to invalid IL or missing references)
        //IL_08eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_090e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0914: Unknown result type (might be due to invalid IL or missing references)
        //IL_0939: Unknown result type (might be due to invalid IL or missing references)
        //IL_0943: Unknown result type (might be due to invalid IL or missing references)
        //IL_0948: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c41: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c46: Unknown result type (might be due to invalid IL or missing references)
        //IL_0caa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0caf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba3: Unknown result type (might be due to invalid IL or missing references)
        bool flag = false;
        if (shinyStone && IsStandingStillForSpecialEffects && itemAnimation == 0)
        {
            flag = true;
        }
        if (poisoned)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegenTime = 0f;
            lifeRegen -= 4;
        }
        if (venom)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegenTime = 0f;
            lifeRegen -= 30;
        }
        if (onFire)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegenTime = 0f;
            lifeRegen -= 8;
        }
        if (onFire3)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegenTime = 0f;
            lifeRegen -= 8;
        }
        if (onFrostBurn)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegenTime = 0f;
            lifeRegen -= 16;
        }
        if (onFrostBurn2)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegenTime = 0f;
            lifeRegen -= 16;
        }
        if (onFire2)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegenTime = 0f;
            lifeRegen -= 24;
        }
        if (burned)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegenTime = 0f;
            lifeRegen -= 60;
            moveSpeed *= 0.5f;
        }
        if (suffocating)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegenTime = 0f;
            lifeRegen -= 40;
        }
        if (electrified)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegenTime = 0f;
            lifeRegen -= 8;
            if (controlLeft || controlRight)
            {
                lifeRegen -= 32;
            }
        }
        if (tongued && Main.expertMode)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            lifeRegenTime = 0f;
            lifeRegen -= 100;
        }
        PlayerLoader.UpdateBadLifeRegen(this);
        if (honey && lifeRegen < 0)
        {
            lifeRegen += 4;
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
        }
        if (lifeRegen < 0 && nebulaLevelLife > 0)
        {
            lifeRegen = 0;
        }
        if (flag && lifeRegen < 0)
        {
            lifeRegen /= 2;
        }
        lifeRegenTime += 1f;
        if (usedAegisCrystal)
        {
            lifeRegenTime += 0.2f;
        }
        if (crimsonRegen)
        {
            lifeRegenTime += 1f;
        }
        if (soulDrain > 0)
        {
            lifeRegenTime += 2f;
        }
        if (flag)
        {
            if (lifeRegenTime > 90f && lifeRegenTime < 1800f)
            {
                lifeRegenTime = 1800f;
            }
            lifeRegenTime += 4f;
            lifeRegen += 4;
        }
        if (honey)
        {
            lifeRegenTime += 2f;
            lifeRegen += 2;
        }
        if (starving)
        {
            if (lifeRegen > 0)
            {
                lifeRegen = 0;
            }
            if (lifeRegenCount > 0)
            {
                lifeRegenCount = 0;
            }
            if (lifeRegenTime > 0f)
            {
                lifeRegenTime = 0f;
            }
            int num = 3000;
            int num7 = 120 * statLifeMax2 / num;
            if (num7 < 4)
            {
                num7 = 4;
            }
            lifeRegen = -num7;
        }
        if (soulDrain > 0)
        {
            int num8 = (5 + soulDrain) / 2;
            lifeRegenTime += num8;
            lifeRegen += num8;
        }
        if (heartyMeal)
        {
            int num9 = 6;
            lifeRegen += num9;
        }
        if (whoAmI == Main.myPlayer && Main.SceneMetrics.HasCampfire)
        {
            lifeRegen++;
        }
        if (whoAmI == Main.myPlayer && Main.SceneMetrics.HasHeartLantern)
        {
            lifeRegen += 2;
        }
        PlayerLoader.UpdateLifeRegen(this);
        if (bleed)
        {
            lifeRegenTime = 0f;
        }
        float num10 = 0f;
        if (lifeRegenTime >= 300f)
        {
            num10 += 1f;
        }
        if (lifeRegenTime >= 600f)
        {
            num10 += 1f;
        }
        if (lifeRegenTime >= 900f)
        {
            num10 += 1f;
        }
        if (lifeRegenTime >= 1200f)
        {
            num10 += 1f;
        }
        if (lifeRegenTime >= 1500f)
        {
            num10 += 1f;
        }
        if (lifeRegenTime >= 1800f)
        {
            num10 += 1f;
        }
        if (lifeRegenTime >= 2400f)
        {
            num10 += 1f;
        }
        if (lifeRegenTime >= 3000f)
        {
            num10 += 1f;
        }
        if (flag)
        {
            float num11 = lifeRegenTime - 3000f;
            num11 /= 300f;
            if (num11 > 0f)
            {
                if (num11 > 30f)
                {
                    num11 = 30f;
                }
                num10 += num11;
            }
        }
        else if (lifeRegenTime >= 3600f)
        {
            num10 += 1f;
            lifeRegenTime = 3600f;
        }
        if (sitting.isSitting || sleeping.isSleeping)
        {
            lifeRegenTime += 3f;
            num10 *= 1.3f;
        }
        if (sitting.isSitting && sitting.details.IsAToilet)
        {
            TryToPoop();
        }
        num10 = ((velocity.X != 0f && grappling[0] <= 0) ? (num10 * 0.5f) : (num10 * 1.25f));
        if (crimsonRegen)
        {
            num10 *= 1.5f;
        }
        if (shinyStone)
        {
            num10 *= 1.1f;
        }
        if (whoAmI == Main.myPlayer && Main.SceneMetrics.HasCampfire)
        {
            num10 *= 1.1f;
        }
        if (Main.expertMode && !wellFed)
        {
            num10 = ((!shinyStone) ? (num10 / 2f) : (num10 * 0.75f));
        }
        if (rabid)
        {
            num10 = ((!shinyStone) ? (num10 / 2f) : (num10 * 0.75f));
        }
        PlayerLoader.NaturalLifeRegen(this, ref num10);
        float num12 = (float)statLifeMax2 / 400f * 0.85f + 0.15f;
        num10 *= num12;
        lifeRegen += (int)Math.Round(num10);
        lifeRegenCount += lifeRegen;
        if (palladiumRegen)
        {
            lifeRegenCount += 4;
        }
        if (flag && lifeRegen > 0 && statLife < statLifeMax2)
        {
            lifeRegenCount++;
            if (flag && ((float)Main.rand.Next(30000) < lifeRegenTime || Main.rand.Next(30) == 0))
            {
                int num13 = Dust.NewDust(position, width, height, 55, 0f, 0f, 200, default(Color), 0.5f);
                Main.dust[num13].noGravity = true;
                Dust obj = Main.dust[num13];
                obj.velocity *= 0.75f;
                Main.dust[num13].fadeIn = 1.3f;
                Vector2 vector = default(Vector2);
                ((Vector2)(ref vector))._002Ector((float)Main.rand.Next(-100, 101), (float)Main.rand.Next(-100, 101));
                ((Vector2)(ref vector)).Normalize();
                vector *= (float)Main.rand.Next(50, 100) * 0.04f;
                Main.dust[num13].velocity = vector;
                ((Vector2)(ref vector)).Normalize();
                vector *= 34f;
                Main.dust[num13].position = base.Center - vector;
            }
        }
        while (lifeRegenCount >= 120)
        {
            lifeRegenCount -= 120;
            if (statLife < statLifeMax2)
            {
                statLife++;
                if (crimsonRegen)
                {
                    for (int i = 0; i < 10; i++)
                    {
                        int num14 = Dust.NewDust(position, width, height, 5, 0f, 0f, 175, default(Color), 1.75f);
                        Main.dust[num14].noGravity = true;
                        Dust obj2 = Main.dust[num14];
                        obj2.velocity *= 0.75f;
                        int num2 = Main.rand.Next(-40, 41);
                        int num3 = Main.rand.Next(-40, 41);
                        Main.dust[num14].position.X += num2;
                        Main.dust[num14].position.Y += num3;
                        Main.dust[num14].velocity.X = (float)(-num2) * 0.075f;
                        Main.dust[num14].velocity.Y = (float)(-num3) * 0.075f;
                    }
                }
            }
            if (statLife > statLifeMax2)
            {
                statLife = statLifeMax2;
            }
        }
        if (burned || suffocating || (tongued && Main.expertMode))
        {
            while (lifeRegenCount <= -600)
            {
                lifeRegenCount += 600;
                statLife -= 5;
                CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegen, 5, dramatic: false, dot: true);
                if (statLife <= 0 && whoAmI == Main.myPlayer)
                {
                    if (suffocating)
                    {
                        KillMe(PlayerDeathReason.ByOther(7), 10.0, 0);
                    }
                    else if (tongued)
                    {
                        KillMe(PlayerDeathReason.ByOther(12), 10.0, 0);
                    }
                    else
                    {
                        KillMe(PlayerDeathReason.ByOther(8), 10.0, 0);
                    }
                }
            }
            return;
        }
        if (starving)
        {
            int num4 = statLifeMax2 / 50;
            if (num4 < 2)
            {
                num4 = 2;
            }
            int num5 = ((ZoneDesert || ZoneSnow) ? (num4 * 2) : num4);
            int num6 = 120 * num4;
            while (lifeRegenCount <= -num6)
            {
                lifeRegenCount += num6;
                statLife -= num5;
                CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegen, num5, dramatic: false, dot: true);
                if (statLife <= 0 && whoAmI == Main.myPlayer)
                {
                    KillMe(PlayerDeathReason.ByOther(18), 10.0, 0);
                }
            }
            return;
        }
        while (lifeRegenCount <= -120)
        {
            if (lifeRegenCount <= -480)
            {
                lifeRegenCount += 480;
                statLife -= 4;
                CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegen, 4, dramatic: false, dot: true);
            }
            else if (lifeRegenCount <= -360)
            {
                lifeRegenCount += 360;
                statLife -= 3;
                CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegen, 3, dramatic: false, dot: true);
            }
            else if (lifeRegenCount <= -240)
            {
                lifeRegenCount += 240;
                statLife -= 2;
                CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegen, 2, dramatic: false, dot: true);
            }
            else
            {
                lifeRegenCount += 120;
                statLife--;
                CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), CombatText.LifeRegen, 1, dramatic: false, dot: true);
            }
            if (statLife <= 0 && whoAmI == Main.myPlayer)
            {
                if (poisoned || venom)
                {
                    KillMe(PlayerDeathReason.ByOther(9), 10.0, 0);
                }
                else if (electrified)
                {
                    KillMe(PlayerDeathReason.ByOther(10), 10.0, 0);
                }
                else
                {
                    KillMe(PlayerDeathReason.ByOther(8), 10.0, 0);
                }
            }
        }
    }
References Terraria.Player.bleed, Terraria.Player.burned, Terraria.DataStructures.PlayerDeathReason.ByOther(), Terraria.Player.controlLeft, Terraria.Player.controlRight, Terraria.Player.crimsonRegen, Terraria.GameContent.PlayerSittingHelper.details, Terraria.Main.dust, Terraria.Player.electrified, Terraria.Main.expertMode, Terraria.Player.grappling, Terraria.Player.heartyMeal, Terraria.Entity.height, Terraria.Player.honey, Terraria.GameContent.ExtraSeatInfo.IsAToilet, Terraria.GameContent.PlayerSittingHelper.isSitting, Terraria.GameContent.PlayerSleepingHelper.isSleeping, Terraria.Player.IsStandingStillForSpecialEffects, Terraria.Player.itemAnimation, Terraria.Player.KillMe(), Terraria.CombatText.LifeRegen, Terraria.Player.lifeRegen, Terraria.Player.lifeRegenCount, Terraria.Player.lifeRegenTime, Terraria.Player.moveSpeed, Terraria.Main.myPlayer, Terraria.ModLoader.PlayerLoader.NaturalLifeRegen(), Terraria.Dust.NewDust(), Terraria.CombatText.NewText(), Terraria.Player.onFire, Terraria.Player.onFire2, Terraria.Player.onFire3, Terraria.Player.onFrostBurn, Terraria.Player.onFrostBurn2, Terraria.Player.palladiumRegen, Terraria.Player.poisoned, Terraria.Entity.position, Terraria.Player.rabid, Terraria.Main.rand, Terraria.Main.SceneMetrics, Terraria.Player.shinyStone, Terraria.Player.sitting, Terraria.Player.sleeping, Terraria.Player.soulDrain, Terraria.Player.starving, Terraria.Player.statLife, Terraria.Player.statLifeMax2, Terraria.Player.suffocating, Terraria.Player.tongued, Terraria.Player.TryToPoop(), Terraria.ModLoader.PlayerLoader.UpdateBadLifeRegen(), Terraria.ModLoader.PlayerLoader.UpdateLifeRegen(), Terraria.Player.usedAegisCrystal, Terraria.Player.venom, Terraria.Player.wellFed, Terraria.Entity.whoAmI, Terraria.Entity.width, Terraria.Player.ZoneDesert, and Terraria.Player.ZoneSnow.
Referenced by Terraria.Player.Update().