TModLoader: Terraria.Player.BloodButcherer_TryButchering
BloodButcherer_TryButchering()
void Terraria.Player.BloodButcherer_TryButchering (NPC npc, Item sItem, float damage, float knockBack) inline private
    {
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        if (_spawnBloodButcherer && Main.myPlayer == whoAmI && (npc == null || npc.CanBeChasedBy(this)))
        {
            Vector2 v = npc.Center - MountedCenter;
            v = v.SafeNormalize(Vector2.Zero);
            Vector2 vector = npc.Hitbox.ClosestPointInRect(MountedCenter) + v;
            Vector2 spinningpoint = (npc.Center - vector) * 0.8f;
            spinningpoint = spinningpoint.RotatedBy(Main.rand.NextFloatDirection() * (float)Math.PI * 0.25f);
            int num = Projectile.NewProjectile(GetProjectileSource_Item(sItem), vector.X, vector.Y, spinningpoint.X, spinningpoint.Y, 975, (int)damage, knockBack, whoAmI, 1f, npc.whoAmI);
            Main.projectile[num].StatusNPC(npc.whoAmI);
            Projectile.KillOldestJavelin(num, 975, npc.whoAmI, _bloodButchererMax5);
            _spawnBloodButcherer = false;
        }
    }
References Terraria.Player._bloodButchererMax5, Terraria.Player._spawnBloodButcherer, Terraria.NPC.CanBeChasedBy(), Terraria.Player.GetProjectileSource_Item(), Terraria.Entity.Hitbox, Terraria.Projectile.KillOldestJavelin(), Terraria.Player.MountedCenter, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Main.projectile, Terraria.Main.rand, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ApplyNPCOnHitEffects().