TModLoader: Terraria.Player.ItemCheck_ApplyUseStyle_Inner
ItemCheck_ApplyUseStyle_Inner()
void Terraria.Player.ItemCheck_ApplyUseStyle_Inner (float mountOffset, Item sItem, Rectangle heldItemFrame) inline private
Definition at line 51562 of file Player.cs.
    {
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_090d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0931: Unknown result type (might be due to invalid IL or missing references)
        //IL_0936: Unknown result type (might be due to invalid IL or missing references)
        //IL_093b: Unknown result type (might be due to invalid IL or missing references)
        //IL_097c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0990: Unknown result type (might be due to invalid IL or missing references)
        //IL_0995: Unknown result type (might be due to invalid IL or missing references)
        //IL_099c: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09be: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0761: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a05: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a44: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a49: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_049b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0318: Unknown result type (might be due to invalid IL or missing references)
        //IL_0208: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ced: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cfa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cff: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0329: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b66: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_033a: Unknown result type (might be due to invalid IL or missing references)
        //IL_022a: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_034b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1054: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04df: Unknown result type (might be due to invalid IL or missing references)
        //IL_1315: Unknown result type (might be due to invalid IL or missing references)
        //IL_1335: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ddf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1371: Unknown result type (might be due to invalid IL or missing references)
        //IL_137b: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1221: Unknown result type (might be due to invalid IL or missing references)
        //IL_1272: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c49: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c93: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c98: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ca1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ca3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ca8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1554: Unknown result type (might be due to invalid IL or missing references)
        //IL_1578: Unknown result type (might be due to invalid IL or missing references)
        //IL_1582: Unknown result type (might be due to invalid IL or missing references)
        //IL_13e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_15ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_15b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_15cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_15de: Unknown result type (might be due to invalid IL or missing references)
        //IL_15e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_15f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_15f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0557: Unknown result type (might be due to invalid IL or missing references)
        //IL_057c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_18c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_18ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_14f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_14fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_1501: Unknown result type (might be due to invalid IL or missing references)
        //IL_150c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1513: Unknown result type (might be due to invalid IL or missing references)
        //IL_151f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1524: Unknown result type (might be due to invalid IL or missing references)
        //IL_1529: Unknown result type (might be due to invalid IL or missing references)
        //IL_152e: Unknown result type (might be due to invalid IL or missing references)
        //IL_161c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1621: Unknown result type (might be due to invalid IL or missing references)
        //IL_1623: Unknown result type (might be due to invalid IL or missing references)
        //IL_1637: Unknown result type (might be due to invalid IL or missing references)
        //IL_164d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1650: Unknown result type (might be due to invalid IL or missing references)
        //IL_1655: Unknown result type (might be due to invalid IL or missing references)
        //IL_1669: Unknown result type (might be due to invalid IL or missing references)
        //IL_166e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1673: Unknown result type (might be due to invalid IL or missing references)
        //IL_16cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_16d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_16d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_16dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_058d: Unknown result type (might be due to invalid IL or missing references)
        //IL_040a: Unknown result type (might be due to invalid IL or missing references)
        //IL_063c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0641: Unknown result type (might be due to invalid IL or missing references)
        //IL_0643: Unknown result type (might be due to invalid IL or missing references)
        //IL_0648: Unknown result type (might be due to invalid IL or missing references)
        //IL_064d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0652: Unknown result type (might be due to invalid IL or missing references)
        //IL_20c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2111: Unknown result type (might be due to invalid IL or missing references)
        //IL_2116: Unknown result type (might be due to invalid IL or missing references)
        //IL_211a: Unknown result type (might be due to invalid IL or missing references)
        //IL_211f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2121: Unknown result type (might be due to invalid IL or missing references)
        //IL_2126: Unknown result type (might be due to invalid IL or missing references)
        //IL_1818: Unknown result type (might be due to invalid IL or missing references)
        //IL_14b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_14b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_174c: Unknown result type (might be due to invalid IL or missing references)
        //IL_174e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1755: Unknown result type (might be due to invalid IL or missing references)
        //IL_175c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1770: Unknown result type (might be due to invalid IL or missing references)
        //IL_1775: Unknown result type (might be due to invalid IL or missing references)
        //IL_177b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1780: Unknown result type (might be due to invalid IL or missing references)
        //IL_1785: Unknown result type (might be due to invalid IL or missing references)
        //IL_1729: Unknown result type (might be due to invalid IL or missing references)
        //IL_172e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f49: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f53: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f79: Unknown result type (might be due to invalid IL or missing references)
        //IL_059e: Unknown result type (might be due to invalid IL or missing references)
        //IL_191f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ace: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ad3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ad5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ada: Unknown result type (might be due to invalid IL or missing references)
        //IL_1adf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bdb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bee: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bf3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bf7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bfc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bfe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c03: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c08: Unknown result type (might be due to invalid IL or missing references)
        //IL_19c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_19cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_19d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_19d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_19d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_19db: Unknown result type (might be due to invalid IL or missing references)
        //IL_19e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_19e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ddd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1de5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1df7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dfc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e06: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e10: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e12: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e28: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e35: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e56: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e60: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e65: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e94: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ec1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ec7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ec9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ee4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ef3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ef8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f13: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f39: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f55: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f64: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f69: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fa7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fda: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fdc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ff7: Unknown result type (might be due to invalid IL or missing references)
        //IL_2006: Unknown result type (might be due to invalid IL or missing references)
        //IL_200b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2026: Unknown result type (might be due to invalid IL or missing references)
        //IL_2042: Unknown result type (might be due to invalid IL or missing references)
        //IL_204c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2051: Unknown result type (might be due to invalid IL or missing references)
        //IL_2061: Unknown result type (might be due to invalid IL or missing references)
        //IL_2068: Unknown result type (might be due to invalid IL or missing references)
        //IL_2072: Unknown result type (might be due to invalid IL or missing references)
        //IL_2077: Unknown result type (might be due to invalid IL or missing references)
        //IL_207c: Unknown result type (might be due to invalid IL or missing references)
        if (Main.dedServ)
        {
            return;
        }
        if (sItem.useStyle == 1)
        {
            if (sItem.type > -1 && Item.claw[sItem.type])
            {
                if ((double)itemAnimation < (double)itemAnimationMax * 0.333)
                {
                    float num = 10f;
                    itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - num) * (float)direction;
                    itemLocation.Y = position.Y + 26f + mountOffset;
                }
                else if ((double)itemAnimation < (double)itemAnimationMax * 0.666)
                {
                    float num12 = 8f;
                    itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - num12) * (float)direction;
                    num12 = 24f;
                    itemLocation.Y = position.Y + num12 + mountOffset;
                }
                else
                {
                    float num23 = 6f;
                    itemLocation.X = position.X + (float)width * 0.5f - ((float)heldItemFrame.Width * 0.5f - num23) * (float)direction;
                    num23 = 20f;
                    itemLocation.Y = position.Y + num23 + mountOffset;
                }
                itemRotation = ((float)itemAnimation / (float)itemAnimationMax - 0.5f) * (float)(-direction) * 3.5f - (float)direction * 0.3f;
            }
            else
            {
                Vector2 zero = Vector2.Zero;
                if ((double)itemAnimation < (double)itemAnimationMax * 0.333)
                {
                    float num33 = 10f;
                    if (heldItemFrame.Width > 32)
                    {
                        num33 = 14f;
                    }
                    if (heldItemFrame.Width >= 52)
                    {
                        num33 = 24f;
                    }
                    if (heldItemFrame.Width >= 64)
                    {
                        num33 = 28f;
                    }
                    if (heldItemFrame.Width >= 92)
                    {
                        num33 = 38f;
                    }
                    if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
                    {
                        num33 += 8f;
                    }
                    if (sItem.type == 671)
                    {
                        num33 += 12f;
                    }
                    itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - num33) * (float)direction;
                    itemLocation.Y = position.Y + 24f + mountOffset;
                    ((Vector2)(ref zero))._002Ector(-4f, 1f);
                }
                else if ((double)itemAnimation < (double)itemAnimationMax * 0.666)
                {
                    float num35 = 10f;
                    if (heldItemFrame.Width > 32)
                    {
                        num35 = 18f;
                    }
                    if (heldItemFrame.Width >= 52)
                    {
                        num35 = 24f;
                    }
                    if (heldItemFrame.Width >= 64)
                    {
                        num35 = 28f;
                    }
                    if (heldItemFrame.Width >= 92)
                    {
                        num35 = 38f;
                    }
                    if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
                    {
                        num35 += 4f;
                    }
                    if (sItem.type == 671)
                    {
                        num35 += 6f;
                    }
                    itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - num35) * (float)direction;
                    num35 = 10f;
                    if (heldItemFrame.Height > 32)
                    {
                        num35 = 8f;
                    }
                    if (heldItemFrame.Height > 52)
                    {
                        num35 = 12f;
                    }
                    if (heldItemFrame.Height > 64)
                    {
                        num35 = 14f;
                    }
                    if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
                    {
                        num35 += 4f;
                    }
                    if (sItem.type == 671)
                    {
                        num35 += 10f;
                    }
                    itemLocation.Y = position.Y + num35 + mountOffset;
                    ((Vector2)(ref zero))._002Ector(-6f, -4f);
                }
                else
                {
                    float num36 = 6f;
                    if (heldItemFrame.Width > 32)
                    {
                        num36 = 14f;
                    }
                    if (heldItemFrame.Width >= 48)
                    {
                        num36 = 18f;
                    }
                    if (heldItemFrame.Width >= 52)
                    {
                        num36 = 24f;
                    }
                    if (heldItemFrame.Width >= 64)
                    {
                        num36 = 28f;
                    }
                    if (heldItemFrame.Width >= 92)
                    {
                        num36 = 38f;
                    }
                    if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
                    {
                        num36 += 4f;
                    }
                    if (sItem.type == 671)
                    {
                        num36 += 8f;
                    }
                    itemLocation.X = position.X + (float)width * 0.5f - ((float)heldItemFrame.Width * 0.5f - num36) * (float)direction;
                    num36 = 10f;
                    if (heldItemFrame.Height > 32)
                    {
                        num36 = 10f;
                    }
                    if (heldItemFrame.Height > 52)
                    {
                        num36 = 12f;
                    }
                    if (heldItemFrame.Height > 64)
                    {
                        num36 = 14f;
                    }
                    if (sItem.type == 2330 || sItem.type == 2320 || sItem.type == 2341)
                    {
                        num36 += 4f;
                    }
                    if (sItem.type == 671)
                    {
                        num36 += 8f;
                    }
                    itemLocation.Y = position.Y + num36 + mountOffset;
                    ((Vector2)(ref zero))._002Ector(4f, -2f);
                }
                if (sItem.type > -1 && ItemID.Sets.UsesBetterMeleeItemLocation[sItem.type])
                {
                    itemLocation += zero * Directions;
                }
                itemRotation = ((float)itemAnimation / (float)itemAnimationMax - 0.5f) * (float)(-direction) * 3.5f - (float)direction * 0.3f;
            }
            if (gravDir == -1f)
            {
                itemRotation = 0f - itemRotation;
                itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
            }
        }
        else if (sItem.useStyle == 7)
        {
            itemRotation = (float)itemAnimation / (float)itemAnimationMax * (float)direction * 2f + -1.4f * (float)direction;
            if ((double)itemAnimation < (double)itemAnimationMax * 0.5)
            {
                itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - itemRotation * 12f * (float)direction) * (float)direction;
                itemLocation.Y = position.Y + 38f + itemRotation * (float)direction * 4f + mountOffset;
            }
            else
            {
                itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - itemRotation * 16f * (float)direction) * (float)direction;
                itemLocation.Y = position.Y + 38f + itemRotation * (float)direction + mountOffset;
            }
            if (gravDir == -1f)
            {
                itemRotation = 0f - itemRotation;
                itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
            }
        }
        else if (sItem.useStyle == 9)
        {
            float num37 = (float)itemAnimation / (float)itemAnimationMax;
            float t = 1f - num37;
            t = Utils.GetLerpValue(0f, 0.7f, t, clamped: true);
            itemRotation = t * (float)(-direction) * 2f + 0.7f * (float)direction;
            itemLocation = MountedCenter + new Vector2((float)(direction * 10) * ((float)itemAnimation / (float)itemAnimationMax), 0f);
            float num38 = 8f;
            float num39 = 7f;
            float num2 = (float)Math.PI * 2f / 5f;
            float num3 = (0f - num2) * 0.5f + (1f - t) * num2;
            num3 += (float)Math.PI / 10f;
            Vector2 vector = base.Center + new Vector2((float)direction * num38, 0f) + num3.ToRotationVector2() * num39 * new Vector2((float)direction, 1f);
            itemLocation = vector;
            float num4 = num3 - (float)Math.PI / 2f;
            if (direction == -1)
            {
                num4 = 0f - num4;
            }
            SetCompositeArmFront(enabled: true, CompositeArmStretchAmount.Full, num4);
            itemLocation = GetFrontHandPosition(CompositeArmStretchAmount.Full, num4);
            itemLocation -= MountedCenter;
            itemLocation *= MathHelper.Lerp(1.5f, 1.2f, t);
            itemLocation += MountedCenter;
            itemLocation.X += (float)direction * MathHelper.Lerp(8f, 2f, t);
            if (gravDir == -1f)
            {
                itemRotation = 0f - itemRotation;
                itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
            }
        }
        else if (sItem.useStyle == 6)
        {
            float num5 = 1f - (float)itemAnimation / (float)itemAnimationMax;
            num5 *= 6f;
            if (num5 > 1f)
            {
                num5 = 1f;
            }
            itemRotation = (1f - num5) * (float)direction * 2f - 1.4f * (float)direction;
            if (num5 >= 0.5f)
            {
                itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - itemRotation * 12f * (float)direction) * (float)direction;
                itemLocation.Y = position.Y + 38f + itemRotation * (float)direction * 4f + mountOffset;
            }
            else
            {
                itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - itemRotation * 16f * (float)direction) * (float)direction;
                itemLocation.Y = position.Y + 38f + itemRotation * (float)direction + mountOffset;
            }
            if (gravDir == -1f)
            {
                itemRotation = 0f - itemRotation;
                itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
            }
        }
        else if (sItem.useStyle == 2)
        {
            itemLocation = MountedCenter + Utils.RotatedBy(new Vector2((float)(10 * direction), -10f), itemRotation + (float)Math.PI / 4f * (float)direction);
            float num6 = 1f - (float)itemAnimation / (float)itemAnimationMax;
            CompositeArmStretchAmount compositeArmStretchAmount = CompositeArmStretchAmount.Full;
            if (num6 > 0.25f && num6 <= 0.5f)
            {
                compositeArmStretchAmount = CompositeArmStretchAmount.ThreeQuarters;
            }
            if (num6 > 0.5f && num6 <= 0.75f)
            {
                compositeArmStretchAmount = CompositeArmStretchAmount.Quarter;
            }
            if (num6 > 0.75f && num6 <= 1f)
            {
                compositeArmStretchAmount = CompositeArmStretchAmount.None;
            }
            SetCompositeArmFront(enabled: true, compositeArmStretchAmount, -(float)Math.PI / 2f * (float)direction);
            SetCompositeArmBack(enabled: true, compositeArmStretchAmount, -(float)Math.PI / 2f * (float)direction);
            int num7 = 8;
            switch (compositeArmStretchAmount)
            {
            case CompositeArmStretchAmount.Full:
                num7 = 8;
                break;
            case CompositeArmStretchAmount.ThreeQuarters:
                num7 = 6;
                break;
            case CompositeArmStretchAmount.Quarter:
                num7 = 4;
                break;
            case CompositeArmStretchAmount.None:
                num7 = 2;
                break;
            }
            itemLocation = MountedCenter + new Vector2((float)((num7 + 10 - heldItemFrame.Width / 2) * direction), (float)(heldItemFrame.Height / 2 - 4));
            if (gravDir == -1f)
            {
                itemRotation = 0f - itemRotation;
                itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
            }
        }
        else if (sItem.useStyle == 11)
        {
            float num8 = 1f - (float)itemAnimation / (float)itemAnimationMax;
            num8 *= 2f;
            CompositeArmStretchAmount compositeArmStretchAmount2 = CompositeArmStretchAmount.Full;
            if (num8 > 0.25f && num8 <= 0.5f)
            {
                compositeArmStretchAmount2 = CompositeArmStretchAmount.ThreeQuarters;
            }
            if (num8 > 0.5f && num8 <= 0.75f)
            {
                compositeArmStretchAmount2 = CompositeArmStretchAmount.Quarter;
            }
            if (num8 > 0.75f && num8 <= 1.25f)
            {
                compositeArmStretchAmount2 = CompositeArmStretchAmount.None;
            }
            if (num8 > 1.25f && num8 <= 1.5f)
            {
                compositeArmStretchAmount2 = CompositeArmStretchAmount.Quarter;
            }
            if (num8 > 1.5f && num8 <= 1.75f)
            {
                compositeArmStretchAmount2 = CompositeArmStretchAmount.ThreeQuarters;
            }
            if (num8 > 1.75f && num8 <= 2f)
            {
                compositeArmStretchAmount2 = CompositeArmStretchAmount.Full;
            }
            SetCompositeArmFront(enabled: true, compositeArmStretchAmount2, -(float)Math.PI / 4f * (float)direction);
            SetCompositeArmBack(enabled: true, CompositeArmStretchAmount.Full, -(float)Math.PI / 16f);
            int num9 = 8;
            switch (compositeArmStretchAmount2)
            {
            case CompositeArmStretchAmount.Full:
                num9 = 8;
                break;
            case CompositeArmStretchAmount.ThreeQuarters:
                num9 = 6;
                break;
            case CompositeArmStretchAmount.Quarter:
                num9 = 4;
                break;
            case CompositeArmStretchAmount.None:
                num9 = 2;
                break;
            }
            itemLocation = MountedCenter + new Vector2((float)((num9 + 22 - heldItemFrame.Width / 2) * direction), (float)(heldItemFrame.Height / 2 - 8));
            if (gravDir == -1f)
            {
                itemRotation = 0f - itemRotation;
                itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
            }
        }
        else if (sItem.useStyle == 3)
        {
            if ((double)itemAnimation > (double)itemAnimationMax * 0.666)
            {
                itemLocation.X = -1000f;
                itemLocation.Y = -1000f;
                itemRotation = -1.3f * (float)direction;
            }
            else
            {
                itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 4f) * (float)direction;
                itemLocation.Y = position.Y + 24f + mountOffset;
                float num10 = (float)itemAnimation / (float)itemAnimationMax * (float)heldItemFrame.Width * (float)direction * GetAdjustedItemScale(sItem) * 1.2f - (float)(10 * direction);
                if (num10 > -4f && direction == -1)
                {
                    num10 = -8f;
                }
                if (num10 < 4f && direction == 1)
                {
                    num10 = 8f;
                }
                itemLocation.X -= num10;
                itemRotation = 0.8f * (float)direction;
                if (sItem.type == 946 || sItem.type == 4707)
                {
                    itemLocation.X -= 6 * direction;
                }
            }
            if (gravDir == -1f)
            {
                itemRotation = 0f - itemRotation;
                itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
            }
        }
        else if (sItem.useStyle == 4)
        {
            int num11 = 0;
            int num13 = 0;
            if (sItem.type == 3601)
            {
                num11 = 10;
            }
            if (sItem.type == 5114)
            {
                num11 = 10;
                num13 = -2;
            }
            if (sItem.type == 5120)
            {
                num11 = 10;
            }
            itemRotation = 0f;
            itemLocation.X = position.X + (float)width * 0.5f + ((float)heldItemFrame.Width * 0.5f - 9f - itemRotation * 14f * (float)direction - 4f - (float)num11) * (float)direction;
            itemLocation.Y = position.Y + (float)heldItemFrame.Height * 0.5f + 4f + mountOffset + (float)num13;
            if (gravDir == -1f)
            {
                itemRotation = 0f - itemRotation;
                itemLocation.Y = position.Y + (float)height + (position.Y - itemLocation.Y);
            }
        }
        else if (sItem.useStyle == 5)
        {
            if (sItem.type == 3779)
            {
                itemRotation = 0f;
                itemLocation.X = base.Center.X + (float)(6 * direction);
                itemLocation.Y = MountedCenter.Y + 6f;
            }
            else if (sItem.type == 4262)
            {
                itemRotation = 0f;
                itemLocation.X = base.Center.X + (float)(-heldItemFrame.Width) * 0.5f + (float)(direction * -6);
                itemLocation.Y = MountedCenter.Y - 6f;
                if (Main.rand.Next(20) == 0)
                {
                    int num14 = Main.rand.Next(570, 573);
                    Vector2 vector4 = default(Vector2);
                    ((Vector2)(ref vector4))._002Ector(base.Center.X + (float)(direction * 30) - 6f, itemLocation.Y - 30f);
                    Vector2 vector5 = default(Vector2);
                    ((Vector2)(ref vector5))._002Ector(Main.WindForVisuals * 2f + (float)direction * 0.3f, -0.5f);
                    vector5.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                    vector5.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                    if (num14 == 572)
                    {
                        vector4.X -= 8f;
                    }
                    if (num14 == 571)
                    {
                        vector4.X -= 4f;
                    }
                    Gore.NewGore(vector4, vector5, num14, 0.8f);
                }
            }
            else if (Item.staff[sItem.type])
            {
                float num15 = 6f;
                if (sItem.type == 3476)
                {
                    num15 = 14f;
                }
                itemLocation = MountedCenter;
                itemLocation += (itemRotation.ToRotationVector2() * num15 * (float)direction).Floor();
            }
            else
            {
                itemLocation.X = position.X + (float)width * 0.5f - (float)heldItemFrame.Width * 0.5f - (float)(direction * 2);
                itemLocation.Y = MountedCenter.Y - (float)heldItemFrame.Height * 0.5f;
            }
            if (sItem.type != 5065)
            {
                return;
            }
            _ = itemRotation;
            Vector2 vector6 = itemLocation + itemRotation.ToRotationVector2() * 38f * (float)direction;
            Vector2 vector7 = itemRotation.ToRotationVector2() * 5f * (float)direction;
            if (itemAnimation % 2 == 0)
            {
                Color newColor = Main.hslToRgb(0.92f, 1f, 0.5f);
                int num16 = Dust.NewDust(vector6, 0, 0, 267, 0f, 0f, 0, newColor);
                Main.dust[num16].position = vector6 - velocity + Main.rand.NextVector2Circular(10f, 10f);
                Main.dust[num16].noGravity = true;
                Main.dust[num16].scale = 0.3f;
                Main.dust[num16].fadeIn = Main.rand.NextFloat() * 1.2f;
                Main.dust[num16].velocity = Main.rand.NextVector2Circular(1f, 1f) + velocity;
                if (num16 != 6000)
                {
                    Dust dust5 = Dust.CloneDust(num16);
                    dust5.scale /= 2f;
                    dust5.fadeIn *= 0.85f;
                    dust5.color = new Color(255, 255, 255, 255);
                }
            }
            if (itemAnimation % 4 == 0)
            {
                ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.PrincessWeapon, new ParticleOrchestraSettings
                {
                    PositionInWorld = vector6,
                    MovementVector = vector7 * 0.1f + Main.rand.NextVector2Circular(2f, 2f) + velocity
                }, whoAmI);
            }
        }
        else if (sItem.useStyle == 13)
        {
            int useAnimation = itemAnimationMax;
            if (itemTimeMax != 0)
            {
                useAnimation = itemTimeMax;
            }
            if (useAnimation == 0)
            {
                useAnimation = sItem.useAnimation;
            }
            float num17 = 1f - (float)(itemAnimation % useAnimation) / (float)useAnimation;
            CompositeArmStretchAmount stretch = CompositeArmStretchAmount.Quarter;
            if (num17 > 0.33f && num17 <= 0.66f)
            {
                stretch = CompositeArmStretchAmount.ThreeQuarters;
            }
            if (num17 > 0.66f && num17 <= 1f)
            {
                stretch = CompositeArmStretchAmount.Full;
            }
            float rotation = itemRotation * Directions.Y - (float)Math.PI / 2f * (float)direction;
            SetCompositeArmFront(enabled: true, stretch, rotation);
        }
        else if (sItem.useStyle == 8)
        {
            Projectile projectile = null;
            if (ownedProjectileCounts[722] > 0)
            {
                for (int i = 0; i < 1000; i++)
                {
                    Projectile projectile2 = Main.projectile[i];
                    if (projectile2.active && projectile2.owner == whoAmI && projectile2.type == 722)
                    {
                        projectile = projectile2;
                        break;
                    }
                }
            }
            float num18 = 1f;
            if (projectile != null)
            {
                num18 = MathHelper.Lerp(0.6f, 1f, Utils.GetLerpValue(0f, 800f, Vector2.Distance(MountedCenter, projectile.Center), clamped: true));
            }
            num18 = 1f;
            if (itemAnimation >= sItem.useAnimation - 1 && itemAnimation <= sItem.useAnimation)
            {
                float num19 = Utils.ToRotation(new Vector2((float)(10 * direction), 10f)) + (float)Math.PI / 4f;
                itemRotation = num19;
                if (direction == -1)
                {
                    itemRotation += (float)Math.PI / 2f;
                }
                _ = (float)itemAnimation / (float)itemAnimationMax;
                CompositeArmStretchAmount stretch2 = CompositeArmStretchAmount.Full;
                CompositeArmStretchAmount stretch3 = CompositeArmStretchAmount.ThreeQuarters;
                float num20 = -(float)Math.PI / 10f;
                if (direction == -1)
                {
                    num20 *= -1f;
                }
                float num21 = itemRotation - (float)Math.PI / 4f + (float)Math.PI;
                if (direction == 1)
                {
                    num21 += (float)Math.PI / 2f;
                }
                float rotation2 = num21 + num20;
                float rotation3 = num21 - num20;
                Vector2 vector8 = (num21 + (float)Math.PI / 2f).ToRotationVector2() * -2f;
                itemLocation = (MountedCenter + vector8).Floor();
                SetCompositeArmFront(enabled: true, stretch2, rotation2);
                SetCompositeArmBack(enabled: true, stretch3, rotation3);
            }
            else if (itemAnimation > sItem.useAnimation)
            {
                float num22 = 0f - Utils.GetLerpValue(itemAnimationMax, itemAnimationMax * 5, itemAnimation, clamped: true);
                num22 *= num18;
                CompositeArmStretchAmount stretch4 = CompositeArmStretchAmount.Full;
                CompositeArmStretchAmount stretch5 = CompositeArmStretchAmount.ThreeQuarters;
                float num24 = -(float)Math.PI / 10f;
                num24 *= 0f - num22;
                itemRotation = (float)Math.PI / 2f * (float)(-direction) + (float)Math.PI + (float)Math.PI * num22 * (float)(-direction);
                float num40 = -(float)Math.PI / 5f * (float)direction;
                if (direction < 1)
                {
                    num24 *= -1f;
                }
                float rotation4 = num40 + num24;
                float rotation5 = num40 - num24;
                Vector2 vector9 = default(Vector2);
                ((Vector2)(ref vector9))._002Ector((float)(10 * direction), num22 * -6f);
                itemLocation = (MountedCenter + vector9).Floor();
                SetCompositeArmFront(enabled: true, stretch4, rotation4);
                SetCompositeArmBack(enabled: true, stretch5, rotation5);
            }
            else
            {
                float num25 = 1f - (float)itemAnimation / (float)itemAnimationMax;
                CompositeArmStretchAmount stretch6 = CompositeArmStretchAmount.Full;
                CompositeArmStretchAmount stretch7 = CompositeArmStretchAmount.ThreeQuarters;
                if (num25 > 0.6f)
                {
                    stretch7 = CompositeArmStretchAmount.Quarter;
                }
                float num26 = -(float)Math.PI / 10f;
                if (direction == -1)
                {
                    num26 *= -1f;
                }
                num26 *= 1f - num25 * 2.2f;
                itemRotation = (num25 * (float)Math.PI * 1.6f + -(float)Math.PI / 2f) * num18 * (float)(-direction) + (float)Math.PI;
                float num27 = (num25 * (float)Math.PI * 0.6f + (float)Math.PI * 2f / 5f) * (float)(-direction) + (float)Math.PI - (float)Math.PI / 4f + (float)Math.PI;
                if (direction == 1)
                {
                    num27 += (float)Math.PI / 2f;
                }
                float rotation6 = num27 + num26;
                float rotation7 = num27 - num26;
                Vector2 vector10 = (num27 + (float)Math.PI / 2f).ToRotationVector2() * (-5f * (1f - num25));
                itemLocation = (MountedCenter + vector10).Floor();
                SetCompositeArmFront(enabled: true, stretch6, rotation6);
                SetCompositeArmBack(enabled: true, stretch7, rotation7);
            }
            FlipItemLocationAndRotationForGravity();
        }
        else if (sItem.useStyle == 12)
        {
            itemRotation = 0f;
            itemLocation.X = MountedCenter.X - (float)(8 * direction);
            itemLocation.Y = position.Y + 40f + mountOffset;
            Vector2 vector11 = Main.OffsetsPlayerHeadgear[bodyFrame.Y / 56];
            itemLocation += vector11;
            float num28 = itemAnimationMax;
            if (num28 == 0f)
            {
                num28 = sItem.useAnimation;
            }
            float num29 = 1f - (float)itemAnimation / num28;
            num29 *= 2f;
            float num30 = (float)Math.Cos(num29 * (float)Math.PI) * 0.2f;
            CompositeArmStretchAmount compositeArmStretchAmount3 = CompositeArmStretchAmount.Full;
            if (num29 > 0.25f && num29 <= 0.5f)
            {
                compositeArmStretchAmount3 = CompositeArmStretchAmount.ThreeQuarters;
            }
            if (num29 > 0.5f && num29 <= 0.75f)
            {
                compositeArmStretchAmount3 = CompositeArmStretchAmount.Quarter;
            }
            if (num29 > 0.75f && num29 <= 1.25f)
            {
                compositeArmStretchAmount3 = CompositeArmStretchAmount.None;
            }
            if (num29 > 1.25f && num29 <= 1.5f)
            {
                compositeArmStretchAmount3 = CompositeArmStretchAmount.Quarter;
            }
            if (num29 > 1.5f && num29 <= 1.75f)
            {
                compositeArmStretchAmount3 = CompositeArmStretchAmount.ThreeQuarters;
            }
            if (num29 > 1.75f && num29 <= 2f)
            {
                compositeArmStretchAmount3 = CompositeArmStretchAmount.Full;
            }
            SetCompositeArmFront(enabled: true, compositeArmStretchAmount3, (-(float)Math.PI / 4f + num30) * (float)direction);
            CompositeArmStretchAmount stretch8 = CompositeArmStretchAmount.Quarter;
            SetCompositeArmBack(enabled: true, stretch8, (-(float)Math.PI / 4f - num30 * 0.5f) * (float)direction);
            FlipItemLocationAndRotationForGravity();
            if (sItem.type != 4715 || compositeArmStretchAmount3 != CompositeArmStretchAmount.ThreeQuarters)
            {
                return;
            }
            Vector2 vector2 = itemLocation + new Vector2((float)heldItemFrame.Width, (float)(-heldItemFrame.Height)) * new Vector2((float)direction, gravDir) * 0.3f;
            Dust dust6 = Dust.NewDustPerfect(vector2, 228, Main.rand.NextVector2CircularEdge(1f, 1f));
            dust6.noGravity = true;
            dust6.noLight = true;
            dust6.velocity *= 2f;
            float num31 = 0.5f;
            for (float num32 = 0f; num32 < 1f; num32 += 0.5f)
            {
                if (Main.rand.Next(3) == 0)
                {
                    Dust dust3 = Dust.NewDustPerfect(vector2, 278, Vector2.UnitY.RotatedBy(num32 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * num31 - num31 * 0.5f + (float)Math.PI / 2f) * (2f + Main.rand.NextFloat() * 1f), 150, Color.Lerp(Color.White, Color.HotPink, Main.rand.NextFloat() * 0.5f + 0.5f), 0.45f);
                    dust3.noGravity = true;
                    dust3.velocity *= 0.5f;
                    dust3.customData = this;
                    dust3.position += dust3.velocity * 6f;
                }
            }
            for (float num34 = 0f; num34 < 1f; num34 += 0.5f)
            {
                if (Main.rand.Next(3) == 0)
                {
                    Dust dust4 = Dust.NewDustPerfect(vector2, 278, Vector2.UnitY.RotatedBy(num34 * ((float)Math.PI * 2f) + Main.rand.NextFloat() * num31 - num31 * 0.5f + (float)Math.PI / 2f) * (0.5f + Main.rand.NextFloat() * 1f), 150, Color.Lerp(Color.White, Color.Gold, Main.rand.NextFloat() * 0.5f + 0.5f), 0.45f);
                    dust4.noGravity = true;
                    dust4.velocity *= 0.5f;
                    dust4.customData = this;
                    dust4.position += dust4.velocity * 6f;
                }
            }
        }
        else if (sItem.useStyle == 14 && !Main.dedServ)
        {
            itemRotation = 0f;
            itemLocation.X = base.Center.X + (float)(6 * direction);
            itemLocation.Y = position.Y + 40f + mountOffset - 8f;
            Vector2 vector3 = Main.OffsetsPlayerHeadgear[bodyFrame.Y / 56];
            itemLocation += vector3;
            CompositeArmStretchAmount stretch9 = CompositeArmStretchAmount.Full;
            SetCompositeArmBack(enabled: true, stretch9, (float)Math.PI * -3f / 4f * (float)direction);
            FlipItemLocationAndRotationForGravity();
        }
    }
References Terraria.Entity.Center, Terraria.Item.claw, Terraria.Dust.CloneDust(), Terraria.Main.dedServ, Terraria.Entity.direction, Terraria.Player.Directions, Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Player.FlipItemLocationAndRotationForGravity(), Terraria.Player.GetAdjustedItemScale(), Terraria.Player.GetFrontHandPosition(), Terraria.Utils.GetLerpValue(), Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Main.hslToRgb(), Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, Terraria.Player.itemLocation, Terraria.Player.itemRotation, Terraria.Player.itemTimeMax, Terraria.Player.MountedCenter, Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Gore.NewGore(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.OffsetsPlayerHeadgear, Terraria.Player.ownedProjectileCounts, Terraria.Dust.position, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Utils.RotatedBy(), Terraria.Dust.scale, Terraria.Player.SetCompositeArmBack(), Terraria.Player.SetCompositeArmFront(), Terraria.Item.staff, Terraria.Utils.ToRotation(), Terraria.ID.ItemID.Sets.UsesBetterMeleeItemLocation, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Entity.whoAmI, Terraria.Entity.width, and Terraria.Main.WindForVisuals.
Referenced by Terraria.Player.ItemCheck_ApplyUseStyle().