TModLoader: Terraria.Player.SlopingCollision
SlopingCollision()
void Terraria.Player.SlopingCollision (bool fallThrough, bool ignorePlats) inline
    {
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        if (ignorePlats || controlDown || grappling[0] >= 0 || gravDir == -1f)
        {
            stairFall = true;
        }
        Vector4 vector = Collision.SlopeCollision(position, velocity, width, height, gravity, stairFall);
        if (Collision.stairFall)
        {
            stairFall = true;
        }
        else if (!fallThrough)
        {
            stairFall = false;
        }
        if (Collision.stair && Math.Abs(vector.Y - position.Y) > 8f + Math.Abs(velocity.X))
        {
            gfxOffY -= vector.Y - position.Y;
            stepSpeed = 4f;
        }
        _ = velocity;
        position.X = vector.X;
        position.Y = vector.Y;
        velocity.X = vector.Z;
        velocity.Y = vector.W;
        if (gravDir == -1f && velocity.Y == 0.0101f)
        {
            velocity.Y = 0f;
        }
    }
References Terraria.Player.controlDown, Terraria.Player.gfxOffY, Terraria.Player.grappling, Terraria.Player.gravDir, Terraria.Player.gravity, Terraria.Entity.height, Terraria.Entity.position, Terraria.Collision.SlopeCollision(), Terraria.Collision.stair, Terraria.Collision.stairFall, Terraria.Player.stairFall, Terraria.Player.stepSpeed, Terraria.Entity.velocity, and Terraria.Entity.width.
Referenced by Terraria.Player.DryCollision(), and Terraria.Player.Update().