TModLoader: Terraria.Player.PickTile
PickTile()
void Terraria.Player.PickTile (int x, int y, int pickPower) inline
    {
        int num = hitTile.HitObject(x, y, 1);
        Tile tile = Main.tile[x, y];
        if (tile.type == 504)
        {
            return;
        }
        int num2 = GetPickaxeDamage(x, y, pickPower, num, tile);
        if (!WorldGen.CanKillTile(x, y))
        {
            num2 = 0;
        }
        if (Main.getGoodWorld)
        {
            num2 *= 2;
        }
        if (DoesPickTargetTransformOnKill(hitTile, num2, x, y, pickPower, num, tile))
        {
            num2 = 0;
        }
        if (hitTile.AddDamage(num, num2) >= 100)
        {
            AchievementsHelper.CurrentlyMining = true;
            ClearMiningCacheAt(x, y, 1);
            if (Main.netMode == 1 && Main.tileContainer[Main.tile[x, y].type])
            {
                if (Main.tile[x, y].type == 470 || Main.tile[x, y].type == 475)
                {
                    NetMessage.SendData(17, -1, -1, null, 20, x, y);
                }
                else
                {
                    WorldGen.KillTile(x, y, fail: true);
                    NetMessage.SendData(17, -1, -1, null, 0, x, y, 1f);
                }
                if (Main.tile[x, y].type == 21 || (Main.tile[x, y].type < TileID.Count && TileID.Sets.BasicChest[Main.tile[x, y].type]))
                {
                    NetMessage.SendData(34, -1, -1, null, 1, x, y);
                }
                if (Main.tile[x, y].type == 467)
                {
                    NetMessage.SendData(34, -1, -1, null, 5, x, y);
                }
                if (Main.tile[x, y].type == 88)
                {
                    NetMessage.SendData(34, -1, -1, null, 3, x, y);
                }
                if (Main.tile[x, y].type >= TileID.Count)
                {
                    if (TileID.Sets.BasicChest[Main.tile[x, y].type])
                    {
                        NetMessage.SendData(34, -1, -1, null, 101, x, y, 0f, 0, Main.tile[x, y].type);
                    }
                    if (TileID.Sets.BasicDresser[Main.tile[x, y].type])
                    {
                        NetMessage.SendData(34, -1, -1, null, 103, x, y, 0f, 0, Main.tile[x, y].type);
                    }
                }
            }
            else
            {
                bool flag = Main.tile[x, y].active();
                WorldGen.KillTile(x, y);
                if (!Main.dedServ && flag && !Main.tile[x, y].active())
                {
                    AchievementsHelper.HandleMining();
                }
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, x, y);
                }
            }
            AchievementsHelper.CurrentlyMining = false;
        }
        else
        {
            WorldGen.KillTile(x, y, fail: true);
            if (Main.netMode == 1)
            {
                NetMessage.SendData(17, -1, -1, null, 0, x, y, 1f);
                NetMessage.SendData(125, -1, -1, null, Main.myPlayer, x, y, num2);
            }
        }
        if (num2 != 0)
        {
            hitTile.Prune();
        }
    }
References Terraria.HitTile.AddDamage(), Terraria.ID.TileID.Sets.BasicChest, Terraria.ID.TileID.Sets.BasicDresser, Terraria.WorldGen.CanKillTile(), Terraria.Player.ClearMiningCacheAt(), Terraria.ID.TileID.Count, Terraria.Main.dedServ, Terraria.Player.DoesPickTargetTransformOnKill(), Terraria.Main.getGoodWorld, Terraria.Player.GetPickaxeDamage(), Terraria.GameContent.Achievements.AchievementsHelper.HandleMining(), Terraria.HitTile.HitObject(), Terraria.Player.hitTile, Terraria.WorldGen.KillTile(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.HitTile.Prune(), Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Main.tileContainer, and Terraria.Tile.type.
Referenced by Terraria.Player.DamageTileWithShovel(), and Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool().