TModLoader: Terraria.Player.GetPickaxeDamage
GetPickaxeDamage()
int Terraria.Player.GetPickaxeDamage (int x, int y, int pickPower, int hitBufferIndex, Tile tileTarget) inline private
    {
        int num = 0;
        if (Main.tileNoFail[tileTarget.type])
        {
            num = 100;
        }
        ModTile modTile = TileLoader.GetTile(tileTarget.type);
        num = ((modTile == null) ? ((Main.tileDungeon[tileTarget.type] || tileTarget.type == 25 || tileTarget.type == 58 || tileTarget.type == 117 || tileTarget.type == 203) ? (num + pickPower / 2) : ((tileTarget.type != 85) ? ((tileTarget.type != 48 && tileTarget.type != 232) ? ((tileTarget.type == 226) ? (num + pickPower / 4) : ((tileTarget.type != 107 && tileTarget.type != 221) ? ((tileTarget.type != 108 && tileTarget.type != 222) ? ((tileTarget.type == 111 || tileTarget.type == 223) ? (num + pickPower / 4) : ((tileTarget.type != 211) ? (num + pickPower) : (num + pickPower / 5))) : (num + pickPower / 3)) : (num + pickPower / 2))) : (num + pickPower * 2)) : ((!Main.getGoodWorld) ? (num + pickPower / 3) : (num + pickPower / 4)))) : (num + (int)((float)pickPower / modTile.MineResist)));
        if (tileTarget.type == 211 && pickPower < 200)
        {
            num = 0;
        }
        if ((tileTarget.type == 25 || tileTarget.type == 203) && pickPower < 65)
        {
            num = 0;
        }
        else if (tileTarget.type == 117 && pickPower < 65)
        {
            num = 0;
        }
        else if (tileTarget.type == 37 && pickPower < 50)
        {
            num = 0;
        }
        else if ((tileTarget.type == 22 || tileTarget.type == 204) && (double)y > Main.worldSurface && pickPower < 55)
        {
            num = 0;
        }
        else if (tileTarget.type == 56 && pickPower < 55)
        {
            num = 0;
        }
        else if (tileTarget.type == 77 && pickPower < 65 && y >= Main.UnderworldLayer)
        {
            num = 0;
        }
        else if (tileTarget.type == 58 && pickPower < 65)
        {
            num = 0;
        }
        else if ((tileTarget.type == 226 || tileTarget.type == 237) && pickPower < 210)
        {
            num = 0;
        }
        else if (tileTarget.type == 137 && pickPower < 210)
        {
            if ((uint)(tileTarget.frameY / 18 - 1) <= 3u)
            {
                num = 0;
            }
        }
        else if (Main.tileDungeon[tileTarget.type] && pickPower < 100 && (double)y > Main.worldSurface)
        {
            if ((double)x < (double)Main.maxTilesX * 0.35 || (double)x > (double)Main.maxTilesX * 0.65)
            {
                num = 0;
            }
        }
        else if (tileTarget.type == 107 && pickPower < 100)
        {
            num = 0;
        }
        else if (tileTarget.type == 108 && pickPower < 110)
        {
            num = 0;
        }
        else if (tileTarget.type == 111 && pickPower < 150)
        {
            num = 0;
        }
        else if (tileTarget.type == 221 && pickPower < 100)
        {
            num = 0;
        }
        else if (tileTarget.type == 222 && pickPower < 110)
        {
            num = 0;
        }
        else if (tileTarget.type == 223 && pickPower < 150)
        {
            num = 0;
        }
        else
        {
            TileLoader.PickPowerCheck(tileTarget, pickPower, ref num);
        }
        if (tileTarget.type == 147 || tileTarget.type == 0 || tileTarget.type == 40 || tileTarget.type == 53 || tileTarget.type == 57 || tileTarget.type == 59 || tileTarget.type == 123 || tileTarget.type == 224 || tileTarget.type == 397)
        {
            num += pickPower;
        }
        if (tileTarget.type == 404)
        {
            num += 5;
        }
        if (tileTarget.type == 165 || Main.tileRope[tileTarget.type] || tileTarget.type == 199)
        {
            num = 100;
        }
        if (tileTarget.type == 128 || tileTarget.type == 269)
        {
            if (tileTarget.frameX == 18 || tileTarget.frameX == 54)
            {
                x--;
                tileTarget = Main.tile[x, y];
                hitTile.UpdatePosition(hitBufferIndex, x, y);
            }
            if (tileTarget.frameX >= 100)
            {
                num = 0;
                Main.blockMouse = true;
            }
        }
        if (tileTarget.type == 334)
        {
            if (tileTarget.frameY == 0)
            {
                y++;
                tileTarget = Main.tile[x, y];
                hitTile.UpdatePosition(hitBufferIndex, x, y);
            }
            if (tileTarget.frameY == 36)
            {
                y--;
                tileTarget = Main.tile[x, y];
                hitTile.UpdatePosition(hitBufferIndex, x, y);
            }
            int frameX = tileTarget.frameX;
            bool flag = frameX >= 5000;
            bool flag2 = false;
            if (!flag)
            {
                int num2 = frameX / 18;
                num2 %= 3;
                x -= num2;
                tileTarget = Main.tile[x, y];
                if (tileTarget.frameX >= 5000)
                {
                    flag = true;
                }
            }
            if (flag)
            {
                frameX = tileTarget.frameX;
                int num3 = 0;
                while (frameX >= 5000)
                {
                    frameX -= 5000;
                    num3++;
                }
                if (num3 != 0)
                {
                    flag2 = true;
                }
            }
            if (flag2)
            {
                num = 0;
                Main.blockMouse = true;
            }
        }
        return num;
    }
References Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Main.getGoodWorld, Terraria.ModLoader.TileLoader.GetTile(), Terraria.Player.hitTile, Terraria.Main.maxTilesX, Terraria.ModLoader.TileLoader.PickPowerCheck(), Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Main.tileNoFail, Terraria.Main.tileRope, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.HitTile.UpdatePosition(), and Terraria.Main.worldSurface.
Referenced by Terraria.Player.HasEnoughPickPowerToHurtTile(), Terraria.Player.PickTile(), and Terraria.Player.PlaceThing_TryReplacingTiles().