TModLoader: Terraria.Player.ItemCheck_EmitHammushProjectiles
ItemCheck_EmitHammushProjectiles()
void Terraria.Player.ItemCheck_EmitHammushProjectiles (int i, Item sItem, Rectangle itemRectangle, int damage) inline private
    {
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0217: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        if (sItem.type != 787)
        {
            return;
        }
        int num = itemAnimationMax;
        if (itemAnimation != (int)((double)num * 0.1) && itemAnimation != (int)((double)num * 0.3) && itemAnimation != (int)((double)num * 0.5) && itemAnimation != (int)((double)num * 0.7) && itemAnimation != (int)((double)num * 0.9))
        {
            return;
        }
        float num2 = 0f;
        float num3 = 0f;
        float num4 = 0f;
        float num5 = 0f;
        if (itemAnimation == (int)((double)num * 0.9))
        {
            num2 = -7f;
        }
        if (itemAnimation == (int)((double)num * 0.7))
        {
            num2 = -6f;
            num3 = 2f;
        }
        if (itemAnimation == (int)((double)num * 0.5))
        {
            num2 = -4f;
            num3 = 4f;
        }
        if (itemAnimation == (int)((double)num * 0.3))
        {
            num2 = -2f;
            num3 = 6f;
        }
        if (itemAnimation == (int)((double)num * 0.1))
        {
            num3 = 7f;
        }
        if (itemAnimation == (int)((double)num * 0.7))
        {
            num5 = 26f;
        }
        if (itemAnimation == (int)((double)num * 0.3))
        {
            num5 -= 4f;
            num4 -= 20f;
        }
        if (itemAnimation == (int)((double)num * 0.1))
        {
            num4 += 6f;
        }
        if (direction == -1)
        {
            if (itemAnimation == (int)((double)num * 0.9))
            {
                num5 -= 8f;
            }
            if (itemAnimation == (int)((double)num * 0.7))
            {
                num5 -= 6f;
            }
        }
        num2 *= 1.5f;
        num3 *= 1.5f;
        num5 *= (float)direction;
        num4 *= gravDir;
        Projectile.NewProjectile(GetProjectileSource_Item(sItem), (float)(itemRectangle.X + itemRectangle.Width / 2) + num5, (float)(itemRectangle.Y + itemRectangle.Height / 2) + num4, (float)direction * num3, num2 * gravDir, 131, damage / 2, 0f, i);
    }
References Terraria.Entity.direction, Terraria.Player.GetProjectileSource_Item(), Terraria.Player.gravDir, Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, and Terraria.Projectile.NewProjectile().
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode().