TModLoader: Terraria.Player.CommandForbiddenStorm
CommandForbiddenStorm()
void Terraria.Player.CommandForbiddenStorm () inline
Definition at line 57792 of file Player.cs.
    {
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0160: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_0198: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0325: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        List<int> list = new List<int>();
        for (int i = 0; i < 1000; i++)
        {
            Projectile projectile = Main.projectile[i];
            if (projectile.active && projectile.type == 656 && projectile.owner == whoAmI)
            {
                list.Add(i);
            }
        }
        bool flag = StrayMethods.CanSpawnSandstormFriendly(MinionRestTargetPoint, 30, 30);
        bool num5 = MinionRestTargetPoint == Vector2.Zero;
        Vector2 center = base.Center;
        Vector2 endPoint = MinionRestTargetPoint;
        if (num5)
        {
            endPoint = center;
        }
        int samplesToTake = 10;
        float samplingWidth = 60f;
        Collision.AimingLaserScan(center, endPoint, samplingWidth, samplesToTake, out var vectorTowardsTarget, out var samples);
        bool flag2 = false;
        float[] array = samples;
        for (int j = 0; j < array.Length; j++)
        {
            if (Math.Abs(array[j] - ((Vector2)(ref vectorTowardsTarget)).Length()) < 10f)
            {
                flag2 = true;
                break;
            }
        }
        float num2 = 0f;
        for (int k = 0; k < samples.Length; k++)
        {
            if (samples[k] > num2)
            {
                num2 = samples[k];
            }
        }
        if (list.Count <= 1)
        {
            Vector2 vector = center + vectorTowardsTarget.SafeNormalize(Vector2.Zero) * num2;
            Vector2 vector2 = vector - center;
            if (((Vector2)(ref vector2)).Length() > 0f)
            {
                for (float num3 = 0f; num3 < ((Vector2)(ref vector2)).Length(); num3 += 15f)
                {
                    Vector2 vector3 = center + vector2 * (num3 / ((Vector2)(ref vector2)).Length());
                    Dust obj = Main.dust[Dust.NewDust(vector3, 0, 0, 269)];
                    obj.position = vector3;
                    obj.fadeIn = 0.5f;
                    obj.scale = 0.7f;
                    obj.velocity *= 0.4f;
                    obj.noLight = true;
                }
            }
            for (float num4 = 0f; num4 < (float)Math.PI * 2f; num4 += (float)Math.PI / 15f)
            {
                Dust obj2 = Main.dust[Dust.NewDust(vector, 0, 0, 269)];
                obj2.position = vector;
                obj2.fadeIn = 1f;
                obj2.scale = 0.3f;
                obj2.noLight = true;
            }
        }
        flag &= list.Count <= 1;
        flag = flag && flag2;
        if (flag)
        {
            flag = CheckMana(20, pay: true);
            if (flag)
            {
                manaRegenDelay = (int)maxRegenDelay;
            }
        }
        if (!flag)
        {
            return;
        }
        foreach (int item in list)
        {
            Projectile projectile2 = Main.projectile[item];
            if (!(projectile2.ai[0] >= 780f))
            {
                projectile2.ai[0] = 780f + projectile2.ai[0] % 60f;
                projectile2.netUpdate = true;
            }
        }
        int damage = (int)GetTotalDamage(DamageClass.MagicSummonHybrid).ApplyTo(20f);
        IEntitySource projectileSource_SetBonus = GetProjectileSource_SetBonus(3);
        _ = Main.projectile[Projectile.NewProjectile(projectileSource_SetBonus, MinionRestTargetPoint, Vector2.Zero, 656, damage, 0f, Main.myPlayer)];
    }
References Terraria.Entity.active, Terraria.Collision.AimingLaserScan(), Terraria.ModLoader.StatModifier.ApplyTo(), Terraria.StrayMethods.CanSpawnSandstormFriendly(), Terraria.Player.CheckMana(), Terraria.Main.dust, Terraria.Player.GetProjectileSource_SetBonus(), Terraria.Player.GetTotalDamage(), Terraria.ModLoader.DamageClass.MagicSummonHybrid, Terraria.Player.manaRegenDelay, Terraria.Player.maxRegenDelay, Terraria.Player.MinionRestTargetPoint, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Projectile.NewProjectile(), Terraria.Projectile.owner, Terraria.Main.projectile, Terraria.Projectile.type, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.KeyDoubleTap().