TModLoader: Terraria.Player.ItemCheck_UseArtisanLoaf
ItemCheck_UseArtisanLoaf()
void Terraria.Player.ItemCheck_UseArtisanLoaf (Item sItem) inline private
Definition at line 44949 of file Player.cs.
    {
        if (sItem.type == 5326 && itemAnimation > 0 && !ateArtisanBread && ItemTimeIsZero)
        {
            ApplyItemTime(sItem);
            ateArtisanBread = true;
            NetMessage.SendData(4, -1, -1, null, whoAmI);
        }
    }
References Terraria.Player.ApplyItemTime(), Terraria.Player.ateArtisanBread, Terraria.Player.itemAnimation, Terraria.Player.ItemTimeIsZero, Terraria.NetMessage.SendData(), and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode().