TModLoader: Terraria.Player.SpawnFastRunParticles
SpawnFastRunParticles()
void Terraria.Player.SpawnFastRunParticles () inline private
Definition at line 18580 of file Player.cs.
    {
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0381: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0240: Unknown result type (might be due to invalid IL or missing references)
        //IL_0246: Unknown result type (might be due to invalid IL or missing references)
        //IL_0327: Unknown result type (might be due to invalid IL or missing references)
        //IL_033c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0341: Unknown result type (might be due to invalid IL or missing references)
        //IL_0811: Unknown result type (might be due to invalid IL or missing references)
        //IL_084d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0853: Unknown result type (might be due to invalid IL or missing references)
        //IL_070b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0746: Unknown result type (might be due to invalid IL or missing references)
        //IL_074c: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0451: Unknown result type (might be due to invalid IL or missing references)
        //IL_046e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0474: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0639: Unknown result type (might be due to invalid IL or missing references)
        //IL_063f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0652: Unknown result type (might be due to invalid IL or missing references)
        //IL_065c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0661: Unknown result type (might be due to invalid IL or missing references)
        //IL_0534: Unknown result type (might be due to invalid IL or missing references)
        //IL_053e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0543: Unknown result type (might be due to invalid IL or missing references)
        //IL_0674: Unknown result type (might be due to invalid IL or missing references)
        //IL_0681: Unknown result type (might be due to invalid IL or missing references)
        //IL_0686: Unknown result type (might be due to invalid IL or missing references)
        //IL_068b: Unknown result type (might be due to invalid IL or missing references)
        int num = 0;
        if (gravDir == -1f)
        {
            num -= height;
        }
        if (runSoundDelay == 0 && velocity.Y == 0f)
        {
            SoundEngine.PlaySound(hermesStepSound.Style, position);
            runSoundDelay = hermesStepSound.IntendedCooldown;
        }
        if (wings == 3)
        {
            int num2 = Dust.NewDust(new Vector2(position.X - 4f, position.Y + (float)height + (float)num), width + 8, 4, 186, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 50, default(Color), 1.5f);
            Dust obj = Main.dust[num2];
            obj.velocity *= 0.025f;
            Main.dust[num2].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
            num2 = Dust.NewDust(new Vector2(position.X - 4f, position.Y + (float)height + (float)num), width + 8, 4, 186, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 50, default(Color), 1.5f);
            Dust obj2 = Main.dust[num2];
            obj2.velocity *= 0.2f;
            Main.dust[num2].shader = GameShaders.Armor.GetSecondaryShader(cWings, this);
        }
        else if (sailDash)
        {
            Vector2 vector = default(Vector2);
            for (int i = 0; i < 4; i++)
            {
                int num3 = Dust.NewDust(new Vector2(position.X - 4f, position.Y), width + 8, height, 253, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 100, default(Color), 1.5f);
                Main.dust[num3].noGravity = true;
                Main.dust[num3].velocity.X = Main.dust[num3].velocity.X * 0.2f;
                Main.dust[num3].velocity.Y = Main.dust[num3].velocity.Y * 0.2f;
                Main.dust[num3].shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
                Main.dust[num3].scale += (float)Main.rand.Next(-5, 3) * 0.1f;
                ((Vector2)(ref vector))._002Ector((float)Main.rand.Next(-100, 101), (float)Main.rand.Next(-100, 101));
                ((Vector2)(ref vector)).Normalize();
                vector *= (float)Main.rand.Next(81) * 0.1f;
            }
        }
        else if (desertDash)
        {
            Dust dust = Dust.NewDustDirect(new Vector2(position.X - 4f, position.Y + (float)height + (float)num), width + 8, 4, 32, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f);
            dust.velocity *= 0.2f;
            dust.velocity.Y -= gravDir * 2f;
            dust.shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
        }
        else if (coldDash)
        {
            for (int j = 0; j < 2; j++)
            {
                int num4 = ((j != 0) ? Dust.NewDust(new Vector2(position.X + (float)(width / 2), position.Y + (float)height + gfxOffY), width / 2, 6, 76, 0f, 0f, 0, default(Color), 1.35f) : Dust.NewDust(new Vector2(position.X, position.Y + (float)height + gfxOffY), width / 2, 6, 76, 0f, 0f, 0, default(Color), 1.35f));
                Main.dust[num4].scale *= 1f + (float)Main.rand.Next(20, 40) * 0.01f;
                Main.dust[num4].noGravity = true;
                Main.dust[num4].noLight = true;
                Dust obj3 = Main.dust[num4];
                obj3.velocity *= 0.001f;
                Main.dust[num4].velocity.Y -= 0.003f;
                Main.dust[num4].shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
            }
        }
        else if (fairyBoots)
        {
            int type = Main.rand.NextFromList(new short[6] { 61, 61, 61, 242, 64, 63 });
            int alpha = 0;
            for (int k = 1; k < 3; k++)
            {
                float scale = 1.5f;
                if (k == 2)
                {
                    scale = 1f;
                }
                int num5 = Dust.NewDust(new Vector2(position.X - 4f, position.Y + (float)height + (float)num), width + 8, 4, type, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, alpha, default(Color), scale);
                Dust obj4 = Main.dust[num5];
                obj4.velocity *= 1.5f;
                if (k == 2)
                {
                    Dust obj5 = Main.dust[num5];
                    obj5.position += Main.dust[num5].velocity;
                }
                Main.dust[num5].noGravity = true;
                Main.dust[num5].noLightEmittence = true;
                Main.dust[num5].shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
            }
        }
        else if (hellfireTreads)
        {
            int num6 = Dust.NewDust(new Vector2(position.X - 4f, position.Y + (float)height + (float)num), width + 8, 4, 6, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 50, default(Color), 2f);
            Main.dust[num6].velocity.X = Main.dust[num6].velocity.X * 0.2f;
            Main.dust[num6].velocity.Y = -1.5f - Main.rand.NextFloat() * 0.5f;
            Main.dust[num6].fadeIn = 0.5f;
            Main.dust[num6].noGravity = true;
            Main.dust[num6].shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
        }
        else
        {
            int num7 = Dust.NewDust(new Vector2(position.X - 4f, position.Y + (float)height + (float)num), width + 8, 4, 16, (0f - velocity.X) * 0.5f, velocity.Y * 0.5f, 50, default(Color), 1.5f);
            Main.dust[num7].velocity.X = Main.dust[num7].velocity.X * 0.2f;
            Main.dust[num7].velocity.Y = Main.dust[num7].velocity.Y * 0.2f;
            Main.dust[num7].shader = GameShaders.Armor.GetSecondaryShader(cShoe, this);
        }
    }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.coldDash, Terraria.Player.cShoe, Terraria.Player.cWings, Terraria.Player.desertDash, Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Player.fairyBoots, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.Player.gfxOffY, Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Player.hellfireTreads, Terraria.Player.hermesStepSound, Terraria.DataStructures.SoundPlaySet.IntendedCooldown, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Dust.noLightEmittence, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Player.runSoundDelay, Terraria.Player.sailDash, Terraria.Dust.scale, Terraria.Dust.shader, Terraria.DataStructures.SoundPlaySet.Style, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Entity.width, and Terraria.Player.wings.
Referenced by Terraria.Player.HorizontalMovement().