TModLoader: Terraria.Player.ItemCheck_UseLawnMower
ItemCheck_UseLawnMower()
void Terraria.Player.ItemCheck_UseLawnMower (Item sItem) inline private
Definition at line 46888 of file Player.cs.
    {
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        if (sItem.type == 4049 && position.X / 16f - (float)tileRangeX - (float)sItem.tileBoost - (float)blockRange <= (float)tileTargetX && (position.X + (float)width) / 16f + (float)tileRangeX + (float)sItem.tileBoost - 1f + (float)blockRange >= (float)tileTargetX && position.Y / 16f - (float)tileRangeY - (float)sItem.tileBoost - (float)blockRange <= (float)tileTargetY && (position.Y + (float)height) / 16f + (float)tileRangeY + (float)sItem.tileBoost - 2f + (float)blockRange >= (float)tileTargetY && itemAnimation > 0 && ItemTimeIsZero && controlUseItem)
        {
            MowGrassTile(Utils.ToWorldCoordinates(new Point(tileTargetX, tileTargetY), 8f, 8f));
            ApplyItemTime(sItem);
        }
    }
References Terraria.Player.ApplyItemTime(), Terraria.Player.blockRange, Terraria.Player.controlUseItem, Terraria.Entity.height, Terraria.Player.itemAnimation, Terraria.Player.ItemTimeIsZero, Terraria.Player.MowGrassTile(), Terraria.Entity.position, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Utils.ToWorldCoordinates(), and Terraria.Entity.width.
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode().