TModLoader: Terraria.Player.ConsumeSolarFlare
ConsumeSolarFlare()
bool Terraria.Player.ConsumeSolarFlare () inline
Definition at line 57731 of file Player.cs.
    {
        if (setSolar && solarShields > 0)
        {
            solarShields--;
            for (int i = 0; i < maxBuffs; i++)
            {
                if (buffType[i] >= 170 && buffType[i] <= 172)
                {
                    DelBuff(i);
                }
            }
            if (solarShields > 0 && whoAmI == Main.myPlayer)
            {
                AddBuff(170 + solarShields - 1, 5, quiet: false);
            }
            solarCounter = 0;
            return true;
        }
        return false;
    }
References Terraria.Player.AddBuff(), Terraria.Player.buffType, Terraria.Player.DelBuff(), Terraria.Player.maxBuffs, Terraria.Main.myPlayer, Terraria.Player.setSolar, Terraria.Player.solarCounter, Terraria.Player.solarShields, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.DashMovement(), and Terraria.Player.OnHurt_Part2().