TModLoader: Terraria.Player.QuickGrapple
QuickGrapple()
void Terraria.Player.QuickGrapple () inline
Definition at line 6533 of file Player.cs.
    {
        //IL_0451: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0822: Unknown result type (might be due to invalid IL or missing references)
        //IL_0894: Unknown result type (might be due to invalid IL or missing references)
        //IL_089b: Unknown result type (might be due to invalid IL or missing references)
        if (frozen || tongued || webbed || stoned || dead)
        {
            return;
        }
        if (PlayerInput.GrappleAndInteractAreShared)
        {
            if (Main.HoveringOverAnNPC || Main.SmartInteractShowingGenuine || Main.SmartInteractShowingFake || (_quickGrappleCooldown > 0 && !Main.mapFullscreen) || (WiresUI.Settings.DrawToolModeUI && PlayerInput.UsingGamepad))
            {
                return;
            }
            bool num32 = controlUseTile;
            bool flag = releaseUseTile;
            if (!num32 && !flag)
            {
                return;
            }
            Tile tileSafely = Framing.GetTileSafely(tileTargetX, tileTargetY);
            if ((tileSafely.active() && (tileSafely.type == 4 || tileSafely.type == 33 || tileSafely.type == 372 || tileSafely.type == 174 || tileSafely.type == 646 || tileSafely.type == 49)) || (inventory[selectedItem].type == 3384 && PlayerInput.UsingGamepad))
            {
                return;
            }
        }
        if (noItems)
        {
            return;
        }
        if (mount.Active)
        {
            mount.Dismount(this);
        }
        Item item = QuickGrapple_GetItemToUse();
        if (item == null || !ItemCheck_CheckCanUse(item))
        {
            return;
        }
        bool? flag3 = ProjectileLoader.CanUseGrapple(item.shoot, this);
        if (flag3.HasValue)
        {
            if (!flag3.GetValueOrDefault())
            {
                item = null;
            }
        }
        else if (item.shoot == 73)
        {
            int num20 = 0;
            for (int i = 0; i < 1000; i++)
            {
                if (Main.projectile[i].active && Main.projectile[i].owner == Main.myPlayer && (Main.projectile[i].type == 73 || Main.projectile[i].type == 74))
                {
                    num20++;
                }
            }
            if (num20 > 1)
            {
                item = null;
            }
        }
        else if (item.shoot == 165)
        {
            int num25 = 0;
            for (int j = 0; j < 1000; j++)
            {
                if (Main.projectile[j].active && Main.projectile[j].owner == Main.myPlayer && Main.projectile[j].type == 165)
                {
                    num25++;
                }
            }
            if (num25 > 8)
            {
                item = null;
            }
        }
        else if (item.shoot == 372)
        {
            int num26 = 0;
            for (int k = 0; k < 1000; k++)
            {
                if (Main.projectile[k].active && Main.projectile[k].owner == Main.myPlayer && Main.projectile[k].type == 372)
                {
                    num26++;
                }
            }
            if (num26 > 2)
            {
                item = null;
            }
        }
        else if (item.shoot == 652)
        {
            int num27 = 0;
            for (int l = 0; l < 1000; l++)
            {
                if (Main.projectile[l].active && Main.projectile[l].owner == Main.myPlayer && Main.projectile[l].type == 652)
                {
                    num27++;
                }
            }
            if (num27 > 1)
            {
                item = null;
            }
        }
        else if (item.type == 3572)
        {
            int num28 = 0;
            bool flag2 = false;
            for (int m = 0; m < 1000; m++)
            {
                if (Main.projectile[m].active && Main.projectile[m].owner == Main.myPlayer && Main.projectile[m].type >= 646 && Main.projectile[m].type <= 649)
                {
                    num28++;
                    if (Main.projectile[m].ai[0] == 2f)
                    {
                        flag2 = true;
                    }
                }
            }
            if (num28 > 4 || (!flag2 && num28 > 3))
            {
                item = null;
            }
        }
        else
        {
            for (int n = 0; n < 1000; n++)
            {
                if (Main.projectile[n].active && Main.projectile[n].owner == Main.myPlayer && Main.projectile[n].type == item.shoot && Main.projectile[n].ai[0] != 2f)
                {
                    item = null;
                    break;
                }
            }
        }
        if (item == null)
        {
            return;
        }
        UpdateBlacklistedTilesForGrappling();
        SoundEngine.PlaySound(item.UseSound, position);
        if (Main.netMode == 1 && whoAmI == Main.myPlayer)
        {
            NetMessage.SendData(51, -1, -1, null, whoAmI, 2f);
        }
        int num29 = item.shoot;
        float shootSpeed = item.shootSpeed;
        int damage = item.damage;
        float knockBack = item.knockBack;
        if (ProjectileID.Sets.SingleGrappleHook[num29])
        {
            grappling[0] = -1;
            grapCount = 0;
            for (int num30 = 0; num30 < 1000; num30++)
            {
                if (Main.projectile[num30].active && Main.projectile[num30].owner == whoAmI && ProjectileID.Sets.SingleGrappleHook[Main.projectile[num30].type])
                {
                    Main.projectile[num30].Kill();
                }
            }
        }
        if (num29 == 256)
        {
            int num31 = 0;
            int num10 = -1;
            int num11 = 100000;
            for (int num12 = 0; num12 < 1000; num12++)
            {
                if (Main.projectile[num12].active && Main.projectile[num12].owner == whoAmI && Main.projectile[num12].type == 256)
                {
                    num31++;
                    if (Main.projectile[num12].timeLeft < num11)
                    {
                        num10 = num12;
                        num11 = Main.projectile[num12].timeLeft;
                    }
                }
            }
            if (num31 > 1)
            {
                Main.projectile[num10].Kill();
            }
        }
        if (num29 == 652)
        {
            int num13 = 0;
            int num14 = -1;
            int num15 = 100000;
            for (int num16 = 0; num16 < 1000; num16++)
            {
                if (Main.projectile[num16].active && Main.projectile[num16].owner == whoAmI && Main.projectile[num16].type == 652)
                {
                    num13++;
                    if (Main.projectile[num16].timeLeft < num15)
                    {
                        num14 = num16;
                        num15 = Main.projectile[num16].timeLeft;
                    }
                }
            }
            if (num13 > 1)
            {
                Main.projectile[num14].Kill();
            }
        }
        if (num29 == 73)
        {
            for (int num17 = 0; num17 < 1000; num17++)
            {
                if (Main.projectile[num17].active && Main.projectile[num17].owner == whoAmI && Main.projectile[num17].type == 73)
                {
                    num29 = 74;
                }
            }
        }
        if (item.type == 3572)
        {
            int num18 = -1;
            int num19 = -1;
            for (int num21 = 0; num21 < 1000; num21++)
            {
                Projectile projectile = Main.projectile[num21];
                if (projectile.active && projectile.owner == whoAmI && projectile.type >= 646 && projectile.type <= 649 && (num19 == -1 || num19 < projectile.timeLeft))
                {
                    num18 = projectile.type;
                    num19 = projectile.timeLeft;
                }
            }
            switch (num18)
            {
            case 646:
                num29 = 647;
                break;
            case 647:
                num29 = 648;
                break;
            case 648:
                num29 = 649;
                break;
            case -1:
            case 649:
                num29 = 646;
                break;
            }
        }
        ProjectileLoader.UseGrapple(this, ref num29);
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
        float num22 = (float)Main.mouseX + Main.screenPosition.X - vector.X;
        float num23 = (float)Main.mouseY + Main.screenPosition.Y - vector.Y;
        if (gravDir == -1f)
        {
            num23 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - vector.Y;
        }
        float num24 = (float)Math.Sqrt(num22 * num22 + num23 * num23);
        if ((float.IsNaN(num22) && float.IsNaN(num23)) || (num22 == 0f && num23 == 0f))
        {
            num22 = direction;
            num23 = 0f;
            num24 = shootSpeed;
        }
        else
        {
            num24 = shootSpeed / num24;
        }
        num22 *= num24;
        num23 *= num24;
        Projectile.NewProjectile(GetProjectileSource_Item(item), vector.X, vector.Y, num22, num23, num29, damage, knockBack, whoAmI);
    }
References Terraria.Player._quickGrappleCooldown, Terraria.Entity.active, Terraria.Mount.Active, Terraria.ModLoader.ProjectileLoader.CanUseGrapple(), Terraria.Player.controlUseTile, Terraria.Item.damage, Terraria.Player.dead, Terraria.Entity.direction, Terraria.Mount.Dismount(), Terraria.GameContent.UI.WiresUI.Settings.DrawToolModeUI, Terraria.Player.frozen, Terraria.Player.GetProjectileSource_Item(), Terraria.Framing.GetTileSafely(), Terraria.Player.grapCount, Terraria.GameInput.PlayerInput.GrappleAndInteractAreShared, Terraria.Player.grappling, Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Main.HoveringOverAnNPC, Terraria.Player.inventory, Terraria.Player.ItemCheck_CheckCanUse(), Terraria.Item.knockBack, Terraria.Main.mapFullscreen, Terraria.Player.mount, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.NewProjectile(), Terraria.Player.noItems, Terraria.Projectile.owner, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.projectile, Terraria.Player.QuickGrapple_GetItemToUse(), Terraria.Player.releaseUseTile, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Player.selectedItem, Terraria.NetMessage.SendData(), Terraria.Item.shoot, Terraria.Item.shootSpeed, Terraria.ID.ProjectileID.Sets.SingleGrappleHook, Terraria.Main.SmartInteractShowingFake, Terraria.Main.SmartInteractShowingGenuine, Terraria.Player.stoned, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Projectile.timeLeft, Terraria.Player.tongued, Terraria.Item.type, Terraria.Projectile.type, Terraria.Player.UpdateBlacklistedTilesForGrappling(), Terraria.ModLoader.ProjectileLoader.UseGrapple(), Terraria.Item.UseSound, Terraria.GameInput.PlayerInput.UsingGamepad, Terraria.Player.webbed, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().