TModLoader: Terraria.Player.HandleBeingInChestRange
HandleBeingInChestRange()
void Terraria.Player.HandleBeingInChestRange () inline private
    {
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0107: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_025a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_026a: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        if (chest != -1)
        {
            if (chest != -2)
            {
                piggyBankProjTracker.Clear();
            }
            if (chest != -5)
            {
                voidLensChest.Clear();
            }
            bool flag = false;
            int projectileLocalIndex = piggyBankProjTracker.ProjectileLocalIndex;
            if (projectileLocalIndex >= 0)
            {
                flag = true;
                if (!Main.projectile[projectileLocalIndex].active || (Main.projectile[projectileLocalIndex].type != 525 && Main.projectile[projectileLocalIndex].type != 960))
                {
                    Main.PlayInteractiveProjectileOpenCloseSound(Main.projectile[projectileLocalIndex].type, open: false);
                    chest = -1;
                    Recipe.FindRecipes();
                }
                else
                {
                    int num = (int)(((double)position.X + (double)width * 0.5) / 16.0);
                    int num2 = (int)(((double)position.Y + (double)height * 0.5) / 16.0);
                    Vector2 vector = Main.projectile[projectileLocalIndex].Hitbox.ClosestPointInRect(base.Center);
                    chestX = (int)vector.X / 16;
                    chestY = (int)vector.Y / 16;
                    if (num < chestX - tileRangeX || num > chestX + tileRangeX + 1 || num2 < chestY - tileRangeY || num2 > chestY + tileRangeY + 1)
                    {
                        if (chest != -1)
{
                            Main.PlayInteractiveProjectileOpenCloseSound(Main.projectile[projectileLocalIndex].type, open: false);
                        }
                        chest = -1;
                        Recipe.FindRecipes();
                    }
                }
            }
            int projectileLocalIndex2 = voidLensChest.ProjectileLocalIndex;
            if (projectileLocalIndex2 >= 0)
            {
                flag = true;
                if (!Main.projectile[projectileLocalIndex2].active || Main.projectile[projectileLocalIndex2].type != 734)
                {
                    SoundEngine.PlaySound(in SoundID.Item130);
                    chest = -1;
                    Recipe.FindRecipes();
                }
                else
                {
                    int num3 = (int)(((double)position.X + (double)width * 0.5) / 16.0);
                    int num4 = (int)(((double)position.Y + (double)height * 0.5) / 16.0);
                    Vector2 vector2 = Main.projectile[projectileLocalIndex2].Hitbox.ClosestPointInRect(base.Center);
                    chestX = (int)vector2.X / 16;
                    chestY = (int)vector2.Y / 16;
                    if (num3 < chestX - tileRangeX || num3 > chestX + tileRangeX + 1 || num4 < chestY - tileRangeY || num4 > chestY + tileRangeY + 1)
                    {
                        if (chest != -1)
{
                            SoundEngine.PlaySound(in SoundID.Item130);
                        }
                        chest = -1;
                        Recipe.FindRecipes();
                    }
                }
            }
            if (flag)
            {
                return;
            }
            if (!IsInInteractionRangeToMultiTileHitbox(chestX, chestY))
            {
                if (chest != -1)
                {
                    SoundEngine.PlaySound(11);
                }
                chest = -1;
                Recipe.FindRecipes();
            }
            else if (!Main.tile[chestX, chestY].active())
            {
                SoundEngine.PlaySound(11);
                chest = -1;
                Recipe.FindRecipes();
            }
        }
        else
        {
            piggyBankProjTracker.Clear();
            voidLensChest.Clear();
        }
    }
References Terraria.Player.chest, Terraria.Player.chestX, Terraria.Player.chestY, Terraria.DataStructures.TrackedProjectileReference.Clear(), Terraria.Recipe.FindRecipes(), Terraria.Entity.height, Terraria.Player.IsInInteractionRangeToMultiTileHitbox(), Terraria.ID.SoundID.Item130, Terraria.Player.piggyBankProjTracker, Terraria.Main.PlayInteractiveProjectileOpenCloseSound(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.projectile, Terraria.DataStructures.TrackedProjectileReference.ProjectileLocalIndex, Terraria.Main.tile, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.Player.voidLensChest, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().