TModLoader: Terraria.Player.GetHurtTile
GetHurtTile()
Collision.HurtTile Terraria.Player.GetHurtTile () inline private
Definition at line 26803 of file Player.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        Collision.HurtTile result = Collision.HurtTiles(position, width, (!mount.Active || !mount.Cart) ? height : (height - 16), this);
        if (result.type >= 0)
        {
            return result;
        }
        foreach (Point touchedTile in TouchedTiles)
        {
            Tile tile = Main.tile[touchedTile.X, touchedTile.Y];
            if (tile != null && tile.active() && tile.nactive() && !TileID.Sets.Suffocate[tile.type] && Collision.CanTileHurt(tile.type, touchedTile.X, touchedTile.Y, this))
            {
                Collision.HurtTile result2 = default(Collision.HurtTile);
                result2.type = tile.type;
                result2.x = touchedTile.X;
                result2.y = touchedTile.Y;
                return result2;
            }
        }
        return result;
    }
References Terraria.Mount.Active, Terraria.Tile.active(), Terraria.Collision.CanTileHurt(), Terraria.Mount.Cart, Terraria.Entity.height, Terraria.Collision.HurtTiles(), Terraria.Player.mount, Terraria.Tile.nactive(), Terraria.Entity.position, Terraria.ID.TileID.Sets.Suffocate, Terraria.Main.tile, Terraria.Player.TouchedTiles, Terraria.Tile.type, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().