TModLoader: Terraria.Player.ItemSpaceForCofveve
ItemSpaceForCofveve()
bool Terraria.Player.ItemSpaceForCofveve (Item newItem) inline
Definition at line 38014 of file Player.cs.
    {
        if (!IsVoidVaultEnabled)
        {
            return false;
        }
        if (!CanVoidVaultAccept(newItem))
        {
            return false;
        }
        Item[] item = bank4.item;
        for (int i = 0; i < item.Length; i++)
        {
            if (CanItemSlotAccept(item[i], newItem))
            {
                return true;
            }
        }
        return false;
    }
References Terraria.Player.bank4, Terraria.Player.CanItemSlotAccept(), Terraria.Player.CanVoidVaultAccept(), Terraria.Player.IsVoidVaultEnabled, and Terraria.Chest.item.
Referenced by Terraria.Player.ItemSpace().