TModLoader: Terraria.Player.OnHurt_Part3
OnHurt_Part3()
void Terraria.Player.OnHurt_Part3 (HurtInfo info) inline private
    {
        //IL_0169: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        double num13 = info.Damage;
        if (brainOfConfusionItem == null || brainOfConfusionItem.IsAir || Main.myPlayer != whoAmI)
        {
            return;
        }
        for (int num14 = 0; num14 < 200; num14++)
        {
            if (!Main.npc[num14].active || Main.npc[num14].friendly)
            {
                continue;
            }
            int num10 = 300;
            num10 += (int)num13 * 2;
            if (Main.rand.Next(500) < num10)
            {
                Vector2 val = Main.npc[num14].Center - base.Center;
                float num15 = ((Vector2)(ref val)).Length();
                float num11 = Main.rand.Next(200 + (int)num13 / 2, 301 + (int)num13 * 2);
                if (num11 > 500f)
                {
                    num11 = 500f + (num11 - 500f) * 0.75f;
                }
                if (num11 > 700f)
                {
                    num11 = 700f + (num11 - 700f) * 0.5f;
                }
                if (num11 > 900f)
                {
                    num11 = 900f + (num11 - 900f) * 0.25f;
                }
                if (num15 < num11)
                {
                    float num12 = Main.rand.Next(90 + (int)num13 / 3, 300 + (int)num13 / 2);
                    Main.npc[num14].AddBuff(31, (int)num12);
                }
            }
        }
        Projectile.NewProjectile(GetSource_Accessory_OnHurt(brainOfConfusionItem, info.DamageSource), base.Center.X + (float)Main.rand.Next(-40, 40), base.Center.Y - (float)Main.rand.Next(20, 60), velocity.X * 0.3f, velocity.Y * 0.3f, 565, 0, 0f, whoAmI);
    }
References Terraria.Player.brainOfConfusionItem, Terraria.Player.GetSource_Accessory_OnHurt(), Terraria.Item.IsAir, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.Main.rand, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.Hurt().