TModLoader: Terraria.Player.CloneLoadouts
CloneLoadouts()
void Terraria.Player.CloneLoadouts (Player clonePlayer) inline private
Definition at line 55200 of file Player.cs.
    {
        Item[] array = armor;
        Item[] array2 = clonePlayer.armor;
        for (int i = 0; i < array.Length; i++)
        {
            array[i].CopyNetStateTo(array2[i]);
        }
        array = dye;
        array2 = clonePlayer.dye;
        for (int j = 0; j < array.Length; j++)
        {
            array[j].CopyNetStateTo(array2[j]);
        }
        for (int k = 0; k < Loadouts.Length; k++)
        {
            array = Loadouts[k].Armor;
            array2 = clonePlayer.Loadouts[k].Armor;
            for (int l = 0; l < array.Length; l++)
            {
                array[l].CopyNetStateTo(array2[l]);
            }
            array = Loadouts[k].Dye;
            array2 = clonePlayer.Loadouts[k].Dye;
            for (int m = 0; m < array.Length; m++)
            {
                array[m].CopyNetStateTo(array2[m]);
            }
        }
    }
References Terraria.EquipmentLoadout.Armor, Terraria.Player.armor, Terraria.Item.CopyNetStateTo(), Terraria.EquipmentLoadout.Dye, Terraria.Player.dye, and Terraria.Player.Loadouts.
Referenced by Terraria.Player.clientClone(), and Terraria.Player.TrySwitchingLoadout().