TModLoader: Terraria.Player.MinionRestTargetAim
MinionRestTargetAim()
void Terraria.Player.MinionRestTargetAim () inline
Definition at line 57979 of file Player.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_0201: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_0212: Unknown result type (might be due to invalid IL or missing references)
        Vector2 mouseWorld = Main.MouseWorld;
        float y = mouseWorld.Y;
        int num = (int)mouseWorld.X / 16;
        int num2 = (int)y / 16;
        int num3 = 0;
        if (Main.tile[num, num2].nactive() && Main.tileSolid[Main.tile[num, num2].type] && !Main.tileSolidTop[Main.tile[num, num2].type])
        {
            int num4 = 0;
            int num5 = 0;
            while (num5 > -20 && num2 + num5 > 1)
            {
                int num6 = num2 + num5;
                if (Main.tile[num, num6].nactive() && Main.tileSolid[Main.tile[num, num6].type] && !Main.tileSolidTop[Main.tile[num, num6].type])
                {
                    num4 = num5;
                    num5--;
                    continue;
                }
                num4 = num5;
                break;
            }
            int num7 = 0;
            for (int i = 0; i < 20 && num2 + i < Main.maxTilesY; i++)
            {
                int num8 = num2 + i;
                if (Main.tile[num, num8].nactive() && Main.tileSolid[Main.tile[num, num8].type] && !Main.tileSolidTop[Main.tile[num, num8].type])
                {
                    num7 = i;
                    continue;
                }
                num7 = i;
                break;
            }
            num3 = ((num7 <= -num4) ? (num7 + 3) : (num4 - 2));
        }
        int num9 = num2 + num3;
        bool flag = false;
        for (int j = num9; j < num9 + 5; j++)
        {
            if (WorldGen.SolidTileAllowBottomSlope(num, j))
            {
                flag = true;
            }
        }
        while (!flag)
        {
            num9++;
            for (int k = num9; k < num9 + 5; k++)
            {
                if (WorldGen.SolidTileAllowBottomSlope(num, k))
                {
                    flag = true;
                }
            }
        }
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)(num * 16 + 8), (float)(num9 * 16));
        if (Distance(vector) <= 1000f)
        {
            MinionRestTargetPoint = vector;
        }
    }
References Terraria.Entity.Distance(), Terraria.Main.maxTilesY, Terraria.Player.MinionRestTargetPoint, Terraria.Main.MouseWorld, Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Main.tileSolidTop.
Referenced by Terraria.Player.KeyDoubleTap().