TModLoader: Terraria.Player.TryFloatingInFluid
TryFloatingInFluid()
void Terraria.Player.TryFloatingInFluid () inline private
Definition at line 21678 of file Player.cs.
    {
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        if (!ShouldFloatInWater)
        {
            return;
        }
        if (whoAmI == Main.myPlayer && sitting.isSitting)
        {
            sitting.SitUp(this);
        }
        if (Collision.GetWaterLine(base.Center.ToTileCoordinates(), out var waterLineHeight))
        {
            float num = base.Center.Y;
            if (mount.Active && mount.Type == 37)
            {
                num -= 6f;
            }
            float num2 = num + 8f;
            if (num2 + velocity.Y < waterLineHeight)
            {
                return;
            }
            if (num > waterLineHeight)
            {
                velocity.Y -= 0.4f;
                if (velocity.Y < -6f)
                {
                    velocity.Y = -6f;
                }
                return;
            }
            velocity.Y = waterLineHeight - num2;
            if (velocity.Y < -3f)
            {
                velocity.Y = -3f;
            }
            if (velocity.Y == 0f)
            {
                velocity.Y = float.Epsilon;
            }
        }
        else
        {
            velocity.Y -= 0.4f;
        }
    }
References Terraria.Mount.Active, Terraria.Collision.GetWaterLine(), Terraria.GameContent.PlayerSittingHelper.isSitting, Terraria.Player.mount, Terraria.Main.myPlayer, Terraria.Player.ShouldFloatInWater, Terraria.Player.sitting, Terraria.GameContent.PlayerSittingHelper.SitUp(), Terraria.Mount.Type, Terraria.Entity.velocity, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.HoneyCollision(), Terraria.Player.ShimmerCollision(), and Terraria.Player.WaterCollision().