TModLoader: Terraria.Player.TileInteractionsUse
TileInteractionsUse()
void Terraria.Player.TileInteractionsUse (int myX, int myY) inline private
    {
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0738: Unknown result type (might be due to invalid IL or missing references)
        //IL_11bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1207: Unknown result type (might be due to invalid IL or missing references)
        //IL_1253: Unknown result type (might be due to invalid IL or missing references)
        //IL_129f: Unknown result type (might be due to invalid IL or missing references)
        //IL_12eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1334: Unknown result type (might be due to invalid IL or missing references)
        //IL_138f: Unknown result type (might be due to invalid IL or missing references)
        //IL_13ea: Unknown result type (might be due to invalid IL or missing references)
        if (WiresUI.Open || ownedProjectileCounts[651] > 0)
        {
            return;
        }
        bool flag = releaseUseTile;
        if (!tileInteractAttempted)
        {
            return;
        }
        bool flag10 = false;
        Tile tile4 = Main.tile[myX, myY];
        if (tile4.type == 212 && snowBallLauncherInteractionCooldown <= 0)
        {
            flag10 = true;
            snowBallLauncherInteractionCooldown = 7;
            SoundEngine.PlaySound(in SoundID.Item11, position);
            tile4 = Main.tile[myX, myY];
            int num = tile4.frameX / 18;
            int num12 = 0;
            while (num >= 3)
            {
                num12++;
                num -= 3;
            }
            num = myX - num;
            tile4 = Main.tile[myX, myY];
            int num23;
            for (num23 = tile4.frameY / 18; num23 >= 3; num23 -= 3)
            {
            }
            num23 = myY - num23;
            float num73 = 12f + (float)Main.rand.Next(450) * 0.01f;
            float num43 = Main.rand.Next(85, 105);
            float num74 = Main.rand.Next(-35, 11);
            int type = 166;
            int damage = 35;
            float knockBack = 3.5f;
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector((float)((num + 2) * 16 - 8), (float)((num23 + 2) * 16 - 8 - 4));
            if (num12 == 0)
            {
                num43 *= -1f;
                vector.X -= 14f;
                vector.X -= 2f;
            }
            else
            {
                vector.X += 14f;
            }
            float num63 = num43;
            float num71 = num74;
            float num72 = (float)Math.Sqrt(num63 * num63 + num71 * num71);
            num72 = num73 / num72;
            num63 *= num72;
            num71 *= num72;
            int num2 = Projectile.NewProjectile(GetProjectileSource_TileInteraction(num, num23), vector.X, vector.Y, num63, num71, type, damage, knockBack, Main.myPlayer, -Main.rand.Next(0, 16));
            Main.projectile[num2].originatedFromActivableTile = true;
        }
        if (flag)
        {
            tile4 = Main.tile[myX, myY];
            if (tile4.type != 132)
            {
                tile4 = Main.tile[myX, myY];
                if (tile4.type != 136)
                {
                    tile4 = Main.tile[myX, myY];
                    if (tile4.type != 144)
                    {
                        tile4 = Main.tile[myX, myY];
                        if (tile4.type == 597)
{
                            flag10 = true;
                            TryOpeningFullscreenMap();
                        }
                        else
{
                            tile4 = Main.tile[myX, myY];
                            if (tile4.type != 441)
{
                                tile4 = Main.tile[myX, myY];
                                if (tile4.type != 468)
{
                                    tile4 = Main.tile[myX, myY];
                                    if (tile4.type == 139 || TileLoader.IsModMusicBox(Main.tile[myX, myY]))
{
                                        flag10 = true;
                                        SoundEngine.PlaySound(28, myX * 16, myY * 16, 0);
                                        WorldGen.SwitchMB(myX, myY);
                                    }
                                    else
{
                                        tile4 = Main.tile[myX, myY];
                                        if (tile4.type == 215)
{
                                            flag10 = true;
                                            SoundEngine.PlaySound(28, myX * 16, myY * 16, 0);
                                            tile4 = Main.tile[myX, myY];
                                            int num5 = tile4.frameX % 54 / 18;
                                            tile4 = Main.tile[myX, myY];
                                            int num6 = tile4.frameY % 36 / 18;
                                            int num7 = myX - num5;
                                            int num8 = myY - num6;
                                            int num9 = 36;
                                            tile4 = Main.tile[num7, num8];
                                            if (tile4.frameY >= 36)
{
                                                num9 = -36;
                                            }
                                            for (int i = num7; i < num7 + 3; i++)
{
                                                for (int j = num8; j < num8 + 2; j++)
{
                                                    tile4 = Main.tile[i, j];
                                                    ref short frameY = ref tile4.frameY;
                                                    tile4 = Main.tile[i, j];
                                                    frameY = (short)(tile4.frameY + num9);
                                                }
                                            }
                                            NetMessage.SendTileSquare(-1, num7, num8, 3, 2);
                                        }
                                        else
{
                                            tile4 = Main.tile[myX, myY];
                                            if (tile4.type == 207)
{
                                                flag10 = true;
                                                SoundEngine.PlaySound(28, myX * 16, myY * 16, 0);
                                                WorldGen.SwitchFountain(myX, myY);
                                            }
                                            else
{
                                                tile4 = Main.tile[myX, myY];
                                                if (tile4.type != 410)
{
                                                    tile4 = Main.tile[myX, myY];
                                                    if (tile4.type != 480)
{
                                                        tile4 = Main.tile[myX, myY];
                                                        if (tile4.type != 509)
{
                                                            tile4 = Main.tile[myX, myY];
                                                            if (tile4.type != 657)
{
                                                                tile4 = Main.tile[myX, myY];
                                                                if (tile4.type != 658)
{
                                                                    tile4 = Main.tile[myX, myY];
                                                                    if (tile4.type == 455)
{
                                                                        flag10 = true;
                                                                        SoundEngine.PlaySound(28, myX * 16, myY * 16, 0);
                                                                        GamepadEnableGrappleCooldown();
                                                                        BirthdayParty.ToggleManualParty();
                                                                    }
                                                                    else
{
                                                                        tile4 = Main.tile[myX, myY];
                                                                        if (tile4.type == 216)
{
                                                                            flag10 = true;
                                                                            WorldGen.LaunchRocket(myX, myY, fromWiring: false);
                                                                        }
                                                                        else
{
                                                                            tile4 = Main.tile[myX, myY];
                                                                            if (tile4.type != 386)
{
                                                                                tile4 = Main.tile[myX, myY];
                                                                                if (tile4.type != 387)
{
                                                                                    tile4 = Main.tile[myX, myY];
                                                                                    if (tile4.type != 388)
{
                                                                                        tile4 = Main.tile[myX, myY];
                                                                                        if (tile4.type != 389)
{
                                                                                            tile4 = Main.tile[myX, myY];
                                                                                            if (tile4.type != 15)
{
                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                if (tile4.type != 497)
{
                                                                                                    tile4 = Main.tile[myX, myY];
                                                                                                    if (tile4.type != 89)
{
                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                        if (tile4.type != 102)
{
                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                            if (tile4.type != 487)
{
                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                if (tile4.type == 335)
{
                                                                                                                    flag10 = true;
                                                                                                                    WorldGen.LaunchRocketSmall(myX, myY, fromWiring: false);
                                                                                                                }
                                                                                                                else
{
                                                                                                                    tile4 = Main.tile[myX, myY];
                                                                                                                    if (tile4.type == 411)
{
                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                        if (tile4.frameX < 36)
{
                                                                                                                            flag10 = true;
                                                                                                                            Wiring.HitSwitch(myX, myY);
                                                                                                                            NetMessage.SendData(59, -1, -1, null, myX, myY);
                                                                                                                            goto IL_295e;
                                                                                                                        }
                                                                                                                    }
                                                                                                                    tile4 = Main.tile[myX, myY];
                                                                                                                    if (tile4.type == 494)
{
                                                                                                                        flag10 = true;
                                                                                                                        for (int k = 0; k < 1000; k++)
{
                                                                                                                            if (ProjectileID.Sets.IsAGolfBall[Main.projectile[k].type] && Main.projectile[k].owner == whoAmI)
{
                                                                                                                                Main.projectile[k].Kill();
                                                                                                                            }
                                                                                                                        }
                                                                                                                        GetPreferredGolfBallToUse(out var projType);
                                                                                                                        Projectile.NewProjectile(GetProjectileSource_TileInteraction(myX, myY), (float)(myX * 16) + 8.5f, myY * 16 + 6, 0f, 0f, projType, 0, 0f, whoAmI, 0f, -1f);
                                                                                                                    }
                                                                                                                    else
{
                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                        if (tile4.type == 338)
{
                                                                                                                            flag10 = true;
                                                                                                                            int num11 = myY;
                                                                                                                            tile4 = Main.tile[myX, num11];
                                                                                                                            if (tile4.frameY == 18)
{
                                                                                                                                num11--;
                                                                                                                            }
                                                                                                                            bool flag13 = false;
                                                                                                                            for (int l = 0; l < 1000; l++)
{
                                                                                                                                if (Main.projectile[l].active && Main.projectile[l].aiStyle == 73 && Main.projectile[l].ai[0] == (float)myX && Main.projectile[l].ai[1] == (float)num11)
{
                                                                                                                                    flag13 = true;
                                                                                                                                    break;
                                                                                                                                }
                                                                                                                            }
                                                                                                                            if (!flag13)
{
                                                                                                                                int num13 = Projectile.NewProjectile(GetProjectileSource_TileInteraction(myX, num11), myX * 16 + 8, num11 * 16 + 2, 0f, 0f, 419 + Main.rand.Next(4), 0, 0f, whoAmI, myX, num11);
                                                                                                                                Main.projectile[num13].originatedFromActivableTile = true;
                                                                                                                            }
                                                                                                                        }
                                                                                                                        else
{
                                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                                            if (tile4.type != 33)
{
                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                if (tile4.type != 49)
{
                                                                                                                                    tile4 = Main.tile[myX, myY];
                                                                                                                                    if (tile4.type != 372)
{
                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                        if (tile4.type != 174)
{
                                                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                                                            if (tile4.type != 646)
{
                                                                                                                                                bool[] torch = TileID.Sets.Torch;
                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                if (!torch[tile4.type])
{
                                                                                                                                                    tile4 = Main.tile[myX, myY];
                                                                                                                                                    if (tile4.type != 13)
{
                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                        if (tile4.type == 50)
{
                                                                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                                                                            if (tile4.frameX == 90)
{
                                                                                                                                                                goto IL_0c62;
                                                                                                                                                            }
                                                                                                                                                        }
                                                                                                                                                        bool[] canDropFromRightClick = TileID.Sets.CanDropFromRightClick;
                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                        if (!canDropFromRightClick[tile4.type])
{
                                                                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                                                                            if (tile4.type == 466)
{
                                                                                                                                                                flag10 = true;
                                                                                                                                                                GamepadEnableGrappleCooldown();
                                                                                                                                                                int num15 = myY;
                                                                                                                                                                Tile tileSafely = Framing.GetTileSafely(myX, myY);
                                                                                                                                                                if (tileSafely.frameY == 0)
{
                                                                                                                                                                    num15 += 3;
                                                                                                                                                                }
                                                                                                                                                                if (tileSafely.frameY == 18)
{
                                                                                                                                                                    num15 += 2;
                                                                                                                                                                }
                                                                                                                                                                if (tileSafely.frameY == 36)
{
                                                                                                                                                                    num15++;
                                                                                                                                                                }
                                                                                                                                                                if (DD2Event.Ongoing)
{
                                                                                                                                                                    DD2Event.RequestToSkipWaitTime(myX, myY);
                                                                                                                                                                }
                                                                                                                                                                else
{
                                                                                                                                                                    bool flag14 = !DD2Event.Ongoing && !NPC.AnyNPCs(548) && !Main.pumpkinMoon && !Main.snowMoon;
                                                                                                                                                                    if (flag14)
{
                                                                                                                                                                        flag14 = HasItem(3828);
                                                                                                                                                                    }
                                                                                                                                                                    if (flag14)
{
                                                                                                                                                                        flag14 = !DD2Event.WouldFailSpawningHere(myX, num15);
                                                                                                                                                                        if (!flag14)
{
                                                                                                                                                                            DD2Event.FailureMessage(-1);
                                                                                                                                                                        }
                                                                                                                                                                    }
                                                                                                                                                                    if (flag14)
{
                                                                                                                                                                        flag14 = ConsumeItem(3828, reverseOrder: true);
                                                                                                                                                                    }
                                                                                                                                                                    if (flag14)
{
                                                                                                                                                                        DD2Event.SummonCrystal(myX, num15, whoAmI);
                                                                                                                                                                    }
                                                                                                                                                                }
                                                                                                                                                            }
                                                                                                                                                            else
{
                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                if (tile4.type == 334)
{
                                                                                                                                                                    flag10 = true;
                                                                                                                                                                    if (ItemFitsWeaponRack(inventory[selectedItem]))
{
                                                                                                                                                                        GamepadEnableGrappleCooldown();
                                                                                                                                                                        PlaceWeapon(myX, myY);
                                                                                                                                                                    }
                                                                                                                                                                    else
{
                                                                                                                                                                        int num16 = myX;
                                                                                                                                                                        int num17 = myY;
                                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                                        if (tile4.frameY == 0)
{
                                                                                                                                                                            num17++;
                                                                                                                                                                        }
                                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                                        if (tile4.frameY == 36)
{
                                                                                                                                                                            num17--;
                                                                                                                                                                        }
                                                                                                                                                                        tile4 = Main.tile[myX, num17];
                                                                                                                                                                        int frameX = tile4.frameX;
                                                                                                                                                                        tile4 = Main.tile[myX, num17];
                                                                                                                                                                        int num18 = tile4.frameX;
                                                                                                                                                                        int num19 = 0;
                                                                                                                                                                        while (num18 >= 5000)
{
                                                                                                                                                                            num18 -= 5000;
                                                                                                                                                                            num19++;
                                                                                                                                                                        }
                                                                                                                                                                        if (num19 != 0)
{
                                                                                                                                                                            num18 = (num19 - 1) * 18;
                                                                                                                                                                        }
                                                                                                                                                                        num18 %= 54;
                                                                                                                                                                        if (num18 == 18)
{
                                                                                                                                                                            tile4 = Main.tile[myX - 1, num17];
                                                                                                                                                                            frameX = tile4.frameX;
                                                                                                                                                                            num16--;
                                                                                                                                                                        }
                                                                                                                                                                        if (num18 == 36)
{
                                                                                                                                                                            tile4 = Main.tile[myX - 2, num17];
                                                                                                                                                                            frameX = tile4.frameX;
                                                                                                                                                                            num16 -= 2;
                                                                                                                                                                        }
                                                                                                                                                                        if (frameX >= 5000)
{
                                                                                                                                                                            GamepadEnableGrappleCooldown();
                                                                                                                                                                            WorldGen.KillTile(myX, num17, fail: true);
                                                                                                                                                                            if (Main.netMode == 1)
{
                                                                                                                                                                                NetMessage.SendData(17, -1, -1, null, 0, myX, num17, 1f);
                                                                                                                                                                            }
                                                                                                                                                                        }
                                                                                                                                                                    }
                                                                                                                                                                }
                                                                                                                                                                else
{
                                                                                                                                                                    tile4 = Main.tile[myX, myY];
                                                                                                                                                                    if (tile4.type == 440)
{
                                                                                                                                                                        flag10 = true;
                                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                                        int num20 = tile4.frameX / 54;
                                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                                        int num21 = tile4.frameY / 54;
                                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                                        _ = tile4.frameX % 54 / 18;
                                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                                        _ = tile4.frameY % 54 / 18;
                                                                                                                                                                        int num22 = -1;
                                                                                                                                                                        switch (num20)
{
                                                                                                                                                                        case 0:
                                                                                                                                                                            num22 = 1526;
                                                                                                                                                                            break;
                                                                                                                                                                        case 1:
                                                                                                                                                                            num22 = 1524;
                                                                                                                                                                            break;
                                                                                                                                                                        case 2:
                                                                                                                                                                            num22 = 1525;
                                                                                                                                                                            break;
                                                                                                                                                                        case 3:
                                                                                                                                                                            num22 = 1523;
                                                                                                                                                                            break;
                                                                                                                                                                        case 4:
                                                                                                                                                                            num22 = 1522;
                                                                                                                                                                            break;
                                                                                                                                                                        case 5:
                                                                                                                                                                            num22 = 1527;
                                                                                                                                                                            break;
                                                                                                                                                                        case 6:
                                                                                                                                                                            num22 = 3643;
                                                                                                                                                                            break;
                                                                                                                                                                        }
                                                                                                                                                                        if (num22 != -1)
{
                                                                                                                                                                            if (num21 == 0 && HasItem(num22) && selectedItem != 58)
{
                                                                                                                                                                                GamepadEnableGrappleCooldown();
                                                                                                                                                                                if (Main.netMode != 1)
{
                                                                                                                                                                                    ConsumeItem(num22);
                                                                                                                                                                                    WorldGen.ToggleGemLock(myX, myY, on: true);
                                                                                                                                                                                }
                                                                                                                                                                                else
{
                                                                                                                                                                                    ConsumeItem(num22);
                                                                                                                                                                                    NetMessage.SendData(105, -1, -1, null, myX, myY, 1f);
                                                                                                                                                                                }
                                                                                                                                                                            }
                                                                                                                                                                            else if (num21 == 1)
{
                                                                                                                                                                                GamepadEnableGrappleCooldown();
                                                                                                                                                                                if (Main.netMode != 1)
{
                                                                                                                                                                                    WorldGen.ToggleGemLock(myX, myY, on: false);
                                                                                                                                                                                }
                                                                                                                                                                                else
{
                                                                                                                                                                                    NetMessage.SendData(105, -1, -1, null, myX, myY);
                                                                                                                                                                                }
                                                                                                                                                                            }
                                                                                                                                                                        }
                                                                                                                                                                    }
                                                                                                                                                                    else
{
                                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                                        if (tile4.type == 395)
{
                                                                                                                                                                            flag10 = true;
                                                                                                                                                                            TEItemFrame.OnPlayerInteraction(this, myX, myY);
                                                                                                                                                                        }
                                                                                                                                                                        else
{
                                                                                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                                                                                            if (tile4.type == 520)
{
                                                                                                                                                                                flag10 = true;
                                                                                                                                                                                TEFoodPlatter.OnPlayerInteraction(this, myX, myY);
                                                                                                                                                                            }
                                                                                                                                                                            else
{
                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                if (tile4.type == 471)
{
                                                                                                                                                                                    flag10 = true;
                                                                                                                                                                                    TEWeaponsRack.OnPlayerInteraction(this, myX, myY);
                                                                                                                                                                                }
                                                                                                                                                                                else
{
                                                                                                                                                                                    tile4 = Main.tile[myX, myY];
                                                                                                                                                                                    if (tile4.type == 470)
{
                                                                                                                                                                                        flag10 = true;
                                                                                                                                                                                        TEDisplayDoll.OnPlayerInteraction(this, myX, myY);
                                                                                                                                                                                    }
                                                                                                                                                                                    else
{
                                                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                                                        if (tile4.type == 475)
{
                                                                                                                                                                                            flag10 = true;
                                                                                                                                                                                            TEHatRack.OnPlayerInteraction(this, myX, myY);
                                                                                                                                                                                        }
                                                                                                                                                                                        else
{
                                                                                                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                                                                                                            if (tile4.type == 125)
{
                                                                                                                                                                                                flag10 = true;
                                                                                                                                                                                                AddBuff(29, 108000);
                                                                                                                                                                                                SoundEngine.PlaySound(in SoundID.Item4, position);
                                                                                                                                                                                            }
                                                                                                                                                                                            else
{
                                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                if (tile4.type == 621)
{
                                                                                                                                                                                                    flag10 = true;
                                                                                                                                                                                                    AddBuff(192, 7200);
                                                                                                                                                                                                    SoundEngine.PlaySound(in SoundID.Item2, position);
                                                                                                                                                                                                }
                                                                                                                                                                                                else
{
                                                                                                                                                                                                    tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                    if (tile4.type == 464)
{
                                                                                                                                                                                                        flag10 = true;
                                                                                                                                                                                                        AddBuff(348, 108000);
                                                                                                                                                                                                        SoundEngine.PlaySound(in SoundID.Item4, position);
                                                                                                                                                                                                    }
                                                                                                                                                                                                    else
{
                                                                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                        if (tile4.type == 377)
{
                                                                                                                                                                                                            flag10 = true;
                                                                                                                                                                                                            AddBuff(159, 108000);
                                                                                                                                                                                                            SoundEngine.PlaySound(in SoundID.Item37, position);
                                                                                                                                                                                                        }
                                                                                                                                                                                                        else
{
                                                                                                                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                            if (tile4.type == 354)
{
                                                                                                                                                                                                                flag10 = true;
                                                                                                                                                                                                                AddBuff(150, 108000);
                                                                                                                                                                                                                SoundEngine.PlaySound(in SoundID.Item4, position);
                                                                                                                                                                                                            }
                                                                                                                                                                                                            else
{
                                                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                if (tile4.type == 287)
{
                                                                                                                                                                                                                    flag10 = true;
                                                                                                                                                                                                                    AddBuff(93, 108000);
                                                                                                                                                                                                                    SoundEngine.PlaySound(in SoundID.Item149, position);
                                                                                                                                                                                                                }
                                                                                                                                                                                                                else
{
                                                                                                                                                                                                                    tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                    if (tile4.type == 356)
{
                                                                                                                                                                                                                        flag10 = true;
                                                                                                                                                                                                                        if (!Main.fastForwardTimeToDawn && (Main.netMode == 1 || Main.sundialCooldown == 0))
{
                                                                                                                                                                                                                            Main.Sundialing();
                                                                                                                                                                                                                            SoundEngine.PlaySound(in SoundID.Item4, position);
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                    else
{
                                                                                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                        if (tile4.type == 663)
{
                                                                                                                                                                                                                            flag10 = true;
                                                                                                                                                                                                                            if (!Main.fastForwardTimeToDusk && (Main.netMode == 1 || Main.moondialCooldown == 0))
{
                                                                                                                                                                                                                                Main.Moondialing();
                                                                                                                                                                                                                                SoundEngine.PlaySound(in SoundID.Item4, position);
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                        else
{
                                                                                                                                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                            if (tile4.type == 79)
{
                                                                                                                                                                                                                                flag10 = true;
                                                                                                                                                                                                                                int num24 = myX;
                                                                                                                                                                                                                                int num25 = myY;
                                                                                                                                                                                                                                int num75 = num24;
                                                                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                num24 = num75 + tile4.frameX / 18 * -1;
                                                                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                if (tile4.frameX >= 72)
{
                                                                                                                                                                                                                                    num24 += 4;
                                                                                                                                                                                                                                    num24++;
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                else
{
                                                                                                                                                                                                                                    num24 += 2;
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                int num26 = tile4.frameY / 18;
                                                                                                                                                                                                                                int num27 = 0;
                                                                                                                                                                                                                                while (num26 > 1)
{
                                                                                                                                                                                                                                    num26 -= 2;
                                                                                                                                                                                                                                    num27++;
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                num25 -= num26;
                                                                                                                                                                                                                                num25 += 2;
                                                                                                                                                                                                                                if (!IsHoveringOverABottomSideOfABed(myX, myY))
{
                                                                                                                                                                                                                                    if (IsWithinSnappngRangeToTile(myX, myY, 96))
{
                                                                                                                                                                                                                                        flag10 = true;
                                                                                                                                                                                                                                        GamepadEnableGrappleCooldown();
                                                                                                                                                                                                                                        sleeping.StartSleeping(this, myX, myY);
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                else
{
                                                                                                                                                                                                                                    FindSpawn();
                                                                                                                                                                                                                                    if (SpawnX == num24 && SpawnY == num25)
{
                                                                                                                                                                                                                                        RemoveSpawn();
                                                                                                                                                                                                                                        Main.NewText(Language.GetTextValue("Game.SpawnPointRemoved"), byte.MaxValue, 240, 20);
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                    else if (CheckSpawn(num24, num25))
{
                                                                                                                                                                                                                                        ChangeSpawn(num24, num25);
                                                                                                                                                                                                                                        Main.NewText(Language.GetTextValue("Game.SpawnPointSet"), byte.MaxValue, 240, 20);
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                            else
{
                                                                                                                                                                                                                                bool[] tileSign = Main.tileSign;
                                                                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                if (tileSign[tile4.type])
{
                                                                                                                                                                                                                                    flag10 = true;
                                                                                                                                                                                                                                    bool flag15 = true;
                                                                                                                                                                                                                                    if (sign >= 0 && Sign.ReadSign(myX, myY, CreateIfMissing: false) == sign)
{
                                                                                                                                                                                                                                        sign = -1;
                                                                                                                                                                                                                                        Main.npcChatText = "";
                                                                                                                                                                                                                                        Main.editSign = false;
                                                                                                                                                                                                                                        SoundEngine.PlaySound(11);
                                                                                                                                                                                                                                        flag15 = false;
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                    if (flag15)
{
                                                                                                                                                                                                                                        if (Main.netMode == 0)
{
                                                                                                                                                                                                                                            SetTalkNPC(-1);
                                                                                                                                                                                                                                            Main.npcChatCornerItem = 0;
                                                                                                                                                                                                                                            Main.playerInventory = false;
                                                                                                                                                                                                                                            Main.editSign = false;
                                                                                                                                                                                                                                            int num28 = Sign.ReadSign(myX, myY);
                                                                                                                                                                                                                                            if (num28 < 0)
{
                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                            SoundEngine.PlaySound(10);
                                                                                                                                                                                                                                            sign = num28;
                                                                                                                                                                                                                                            Main.npcChatText = Main.sign[num28].text;
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        else
{
                                                                                                                                                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                            int num29 = tile4.frameX / 18;
                                                                                                                                                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                            int num30 = tile4.frameY / 18;
                                                                                                                                                                                                                                            while (num29 > 1)
{
                                                                                                                                                                                                                                                num29 -= 2;
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                            int num31 = myX - num29;
                                                                                                                                                                                                                                            int num32 = myY - num30;
                                                                                                                                                                                                                                            bool[] tileSign2 = Main.tileSign;
                                                                                                                                                                                                                                            tile4 = Main.tile[num31, num32];
                                                                                                                                                                                                                                            if (tileSign2[tile4.type])
{
                                                                                                                                                                                                                                                NetMessage.SendData(46, -1, -1, null, num31, num32);
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                else
{
                                                                                                                                                                                                                                    tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                    if (tile4.type == 104)
{
                                                                                                                                                                                                                                        flag10 = true;
                                                                                                                                                                                                                                        string textValue = Language.GetTextValue("GameUI.TimeAtMorning");
                                                                                                                                                                                                                                        double num33 = Main.time;
                                                                                                                                                                                                                                        if (!Main.dayTime)
{
                                                                                                                                                                                                                                            num33 += 54000.0;
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        num33 = num33 / 86400.0 * 24.0;
                                                                                                                                                                                                                                        double num34 = 7.5;
                                                                                                                                                                                                                                        num33 = num33 - num34 - 12.0;
                                                                                                                                                                                                                                        if (num33 < 0.0)
{
                                                                                                                                                                                                                                            num33 += 24.0;
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        if (num33 >= 12.0)
{
                                                                                                                                                                                                                                            textValue = Language.GetTextValue("GameUI.TimePastMorning");
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        int num35 = (int)num33;
                                                                                                                                                                                                                                        double num76 = (int)((num33 - (double)num35) * 60.0);
                                                                                                                                                                                                                                        string text = string.Concat(num76);
                                                                                                                                                                                                                                        if (num76 < 10.0)
{
                                                                                                                                                                                                                                            text = "0" + text;
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        if (num35 > 12)
{
                                                                                                                                                                                                                                            num35 -= 12;
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        if (num35 == 0)
{
                                                                                                                                                                                                                                            num35 = 12;
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        Main.NewText(Language.GetTextValue("Game.Time", num35 + ":" + text + " " + textValue), byte.MaxValue, 240, 20);
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                    else
{
                                                                                                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                        if (tile4.type == 237)
{
                                                                                                                                                                                                                                            flag10 = true;
                                                                                                                                                                                                                                            bool flag16 = false;
                                                                                                                                                                                                                                            if (!NPC.AnyNPCs(245) && Main.hardMode && NPC.downedPlantBoss)
{
                                                                                                                                                                                                                                                for (int m = 0; m < 58; m++)
{
                                                                                                                                                                                                                                                    if (inventory[m].type == 1293)
{
                                                                                                                                                                                                                                                        if (ItemLoader.ConsumeItem(inventory[m], this))
{
                                                                                                                                                                                                                                                            inventory[m].stack--;
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        if (inventory[m].stack <= 0)
{
                                                                                                                                                                                                                                                            inventory[m].SetDefaults();
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        flag16 = true;
                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                            if (flag16)
{
                                                                                                                                                                                                                                                SoundEngine.PlaySound(15, (int)position.X, (int)position.Y, 0);
                                                                                                                                                                                                                                                if (Main.netMode != 1)
{
                                                                                                                                                                                                                                                    NPC.SpawnOnPlayer(whoAmI, 245);
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                else
{
                                                                                                                                                                                                                                                    NetMessage.SendData(61, -1, -1, null, whoAmI, 245f);
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        else if (TileLoader.IsClosedDoor(Main.tile[myX, myY]))
{
                                                                                                                                                                                                                                            flag10 = true;
                                                                                                                                                                                                                                            if (WorldGen.IsLockedDoor(myX, myY))
{
                                                                                                                                                                                                                                                int num36 = 1141;
                                                                                                                                                                                                                                                bool flag17 = false;
                                                                                                                                                                                                                                                for (int n = 0; n < 58; n++)
{
                                                                                                                                                                                                                                                    if (inventory[n].type == num36 && inventory[n].stack > 0)
{
                                                                                                                                                                                                                                                        flag17 = true;
                                                                                                                                                                                                                                                        if (ItemLoader.ConsumeItem(inventory[n], this))
{
                                                                                                                                                                                                                                                            inventory[n].stack--;
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        if (inventory[n].stack <= 0)
{
                                                                                                                                                                                                                                                            inventory[n] = new Item();
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        WorldGen.UnlockDoor(myX, myY);
                                                                                                                                                                                                                                                        if (Main.netMode == 1)
{
                                                                                                                                                                                                                                                            NetMessage.SendData(52, -1, -1, null, whoAmI, 2f, myX, myY);
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                if (!flag17 && useVoidBag())
{
                                                                                                                                                                                                                                                    for (int num37 = 0; num37 < 40; num37++)
{
                                                                                                                                                                                                                                                        if (bank4.item[num37].type == num36 && bank4.item[num37].stack > 0)
{
                                                                                                                                                                                                                                                            bank4.item[num37].stack--;
                                                                                                                                                                                                                                                            if (bank4.item[num37].stack <= 0)
{
                                                                                                                                                                                                                                                                bank4.item[num37] = new Item();
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                            WorldGen.UnlockDoor(myX, myY);
                                                                                                                                                                                                                                                            if (Main.netMode == 1)
{
                                                                                                                                                                                                                                                                NetMessage.SendData(52, -1, -1, null, whoAmI, 2f, myX, myY);
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                            else
{
                                                                                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                int originalClosedDoorType = tile4.type;
                                                                                                                                                                                                                                                WorldGen.OpenDoor(myX, myY, direction);
                                                                                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                if (tile4.type != originalClosedDoorType)
{
                                                                                                                                                                                                                                                    NetMessage.SendData(19, -1, -1, null, 0, myX, myY, direction);
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                else
{
                                                                                                                                                                                                                                                    WorldGen.OpenDoor(myX, myY, -direction);
                                                                                                                                                                                                                                                    tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                    if (tile4.type != originalClosedDoorType)
{
                                                                                                                                                                                                                                                        NetMessage.SendData(19, -1, -1, null, 0, myX, myY, -direction);
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        else if (TileLoader.CloseDoorID(Main.tile[myX, myY]) >= 0)
{
                                                                                                                                                                                                                                            flag10 = true;
                                                                                                                                                                                                                                            if (WorldGen.CloseDoor(myX, myY))
{
                                                                                                                                                                                                                                                NetMessage.SendData(19, -1, -1, null, 1, myX, myY, direction);
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        else
{
                                                                                                                                                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                            if (tile4.type == 88)
{
                                                                                                                                                                                                                                                flag10 = true;
                                                                                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                int num38 = tile4.frameX / 18;
                                                                                                                                                                                                                                                num38 %= 3;
                                                                                                                                                                                                                                                num38 = myX - num38;
                                                                                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                int num39 = myY - tile4.frameY / 18;
                                                                                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                if (tile4.frameY == 0)
{
                                                                                                                                                                                                                                                    Main.CancelClothesWindow(quiet: true);
                                                                                                                                                                                                                                                    Main.mouseRightRelease = false;
                                                                                                                                                                                                                                                    CloseSign();
                                                                                                                                                                                                                                                    SetTalkNPC(-1);
                                                                                                                                                                                                                                                    Main.npcChatCornerItem = 0;
                                                                                                                                                                                                                                                    Main.npcChatText = "";
                                                                                                                                                                                                                                                    if (Main.editChest)
{
                                                                                                                                                                                                                                                        SoundEngine.PlaySound(12);
                                                                                                                                                                                                                                                        Main.editChest = false;
                                                                                                                                                                                                                                                        Main.npcChatText = string.Empty;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    if (editedChestName)
{
                                                                                                                                                                                                                                                        NetMessage.SendData(33, -1, -1, NetworkText.FromLiteral(Main.chest[chest].name), chest, 1f);
                                                                                                                                                                                                                                                        editedChestName = false;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    if (Main.netMode == 1)
{
                                                                                                                                                                                                                                                        if (num38 == chestX && num39 == chestY && chest != -1)
{
                                                                                                                                                                                                                                                            chest = -1;
                                                                                                                                                                                                                                                            Recipe.FindRecipes();
                                                                                                                                                                                                                                                            SoundEngine.PlaySound(11);
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        else
{
                                                                                                                                                                                                                                                            NetMessage.SendData(31, -1, -1, null, num38, num39);
                                                                                                                                                                                                                                                            Main.stackSplit = 600;
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    else
{
                                                                                                                                                                                                                                                        piggyBankProjTracker.Clear();
                                                                                                                                                                                                                                                        voidLensChest.Clear();
                                                                                                                                                                                                                                                        int num40 = Chest.FindChest(num38, num39);
                                                                                                                                                                                                                                                        if (num40 != -1)
{
                                                                                                                                                                                                                                                            Main.stackSplit = 600;
                                                                                                                                                                                                                                                            if (num40 == chest)
{
                                                                                                                                                                                                                                                                chest = -1;
                                                                                                                                                                                                                                                                Recipe.FindRecipes();
                                                                                                                                                                                                                                                                SoundEngine.PlaySound(11);
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                            else if (num40 != chest && chest == -1)
{
                                                                                                                                                                                                                                                                OpenChest(num38, num39, num40);
                                                                                                                                                                                                                                                                SoundEngine.PlaySound(10);
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                            else
{
                                                                                                                                                                                                                                                                OpenChest(num38, num39, num40);
                                                                                                                                                                                                                                                                SoundEngine.PlaySound(12);
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                            Recipe.FindRecipes();
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                else
{
                                                                                                                                                                                                                                                    Main.playerInventory = false;
                                                                                                                                                                                                                                                    chest = -1;
                                                                                                                                                                                                                                                    Recipe.FindRecipes();
                                                                                                                                                                                                                                                    SetTalkNPC(-1);
                                                                                                                                                                                                                                                    Main.npcChatCornerItem = 0;
                                                                                                                                                                                                                                                    Main.npcChatText = "";
                                                                                                                                                                                                                                                    Main.interactedDresserTopLeftX = num38;
                                                                                                                                                                                                                                                    Main.interactedDresserTopLeftY = num39;
                                                                                                                                                                                                                                                    Main.OpenClothesWindow();
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                            else
{
                                                                                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                if (tile4.type == 209)
{
                                                                                                                                                                                                                                                    flag10 = true;
                                                                                                                                                                                                                                                    Tile tile2 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                    int num41 = tile2.frameX % 72 / 18;
                                                                                                                                                                                                                                                    int num42 = tile2.frameY % 54 / 18;
                                                                                                                                                                                                                                                    int num44 = myX - num41;
                                                                                                                                                                                                                                                    int num45 = myY - num42;
                                                                                                                                                                                                                                                    int num46 = tile2.frameY / 54;
                                                                                                                                                                                                                                                    int num47 = tile2.frameX / 72;
                                                                                                                                                                                                                                                    int num48 = -1;
                                                                                                                                                                                                                                                    if (num41 == 1 || num41 == 2)
{
                                                                                                                                                                                                                                                        num48 = num42;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    int num49 = 0;
                                                                                                                                                                                                                                                    if (num41 == 3 || (num41 == 2 && num47 != 3 && num47 != 4))
{
                                                                                                                                                                                                                                                        num49 = -54;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    if (num41 == 0 || (num41 == 1 && num47 != 3 && num47 != 4))
{
                                                                                                                                                                                                                                                        num49 = 54;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    if (num46 >= 8 && num49 > 0)
{
                                                                                                                                                                                                                                                        num49 = 0;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    if (num46 == 0 && num49 < 0)
{
                                                                                                                                                                                                                                                        num49 = 0;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    bool flag2 = false;
                                                                                                                                                                                                                                                    if (num49 != 0)
{
                                                                                                                                                                                                                                                        for (int num50 = num44; num50 < num44 + 4; num50++)
{
                                                                                                                                                                                                                                                            for (int num51 = num45; num51 < num45 + 3; num51++)
{
                                                                                                                                                                                                                                                                tile4 = Main.tile[num50, num51];
                                                                                                                                                                                                                                                                ref short frameY2 = ref tile4.frameY;
                                                                                                                                                                                                                                                                tile4 = Main.tile[num50, num51];
                                                                                                                                                                                                                                                                frameY2 = (short)(tile4.frameY + num49);
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        flag2 = true;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    if ((num47 == 3 || num47 == 4) && (num48 == 1 || num48 == 0))
{
                                                                                                                                                                                                                                                        num49 = ((num47 == 3) ? 72 : (-72));
                                                                                                                                                                                                                                                        for (int num52 = num44; num52 < num44 + 4; num52++)
{
                                                                                                                                                                                                                                                            for (int num53 = num45; num53 < num45 + 3; num53++)
{
                                                                                                                                                                                                                                                                tile4 = Main.tile[num52, num53];
                                                                                                                                                                                                                                                                ref short frameX2 = ref tile4.frameX;
                                                                                                                                                                                                                                                                tile4 = Main.tile[num52, num53];
                                                                                                                                                                                                                                                                frameX2 = (short)(tile4.frameX + num49);
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        flag2 = true;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    if (flag2)
{
                                                                                                                                                                                                                                                        NetMessage.SendTileSquare(-1, num44, num45, 4, 3);
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    if (num48 != -1)
{
                                                                                                                                                                                                                                                        bool flag3 = false;
                                                                                                                                                                                                                                                        if ((num47 == 3 || num47 == 4) && num48 == 2)
{
                                                                                                                                                                                                                                                            flag3 = true;
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        if (flag3)
{
                                                                                                                                                                                                                                                            WorldGen.ShootFromCannon(num44, num45, num46, num47 + 1, 0, 0f, whoAmI, fromWire: false);
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                else
{
                                                                                                                                                                                                                                                    tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                    if (tile4.type != 510)
{
                                                                                                                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                        if (tile4.type != 511)
{
                                                                                                                                                                                                                                                            bool[] basicChest = TileID.Sets.BasicChest;
                                                                                                                                                                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                            if (basicChest[tile4.type])
{
                                                                                                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                                if (tile4.type < TileID.Count)
{
                                                                                                                                                                                                                                                                    goto IL_224c;
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                            if (tile4.type != 29)
{
                                                                                                                                                                                                                                                                tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                                if (tile4.type != 97)
{
                                                                                                                                                                                                                                                                    tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                                    if (tile4.type != 463)
{
                                                                                                                                                                                                                                                                        tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                                        if (tile4.type != 491)
{
                                                                                                                                                                                                                                                                            tile4 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                                            if (tile4.type == 314 && gravDir == 1f)
{
                                                                                                                                                                                                                                                                                flag10 = true;
                                                                                                                                                                                                                                                                                bool flag9 = true;
                                                                                                                                                                                                                                                                                if (mount.Active)
{
                                                                                                                                                                                                                                                                                    if (mount.Cart)
{
                                                                                                                                                                                                                                                                                        flag9 = false;
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                    else
{
                                                                                                                                                                                                                                                                                        mount.Dismount(this);
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                if (flag9)
{
                                                                                                                                                                                                                                                                                    LaunchMinecartHook(myX, myY);
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                            goto IL_295e;
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                            goto IL_224c;
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    flag10 = true;
                                                                                                                                                                                                                                                    Tile tile3 = Main.tile[myX, myY];
                                                                                                                                                                                                                                                    int num54 = tile3.frameX % 36 / 18;
                                                                                                                                                                                                                                                    int num55 = tile3.frameY % 36 / 18;
                                                                                                                                                                                                                                                    int num56 = myX - num54;
                                                                                                                                                                                                                                                    int num57 = myY - num55;
                                                                                                                                                                                                                                                    int num77 = tile3.frameY / 36;
                                                                                                                                                                                                                                                    _ = tile3.frameX / 36;
                                                                                                                                                                                                                                                    int num58 = 0;
                                                                                                                                                                                                                                                    if (num54 == 0)
{
                                                                                                                                                                                                                                                        num58 = -36;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    if (num54 == 1)
{
                                                                                                                                                                                                                                                        num58 = 36;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    if (num77 >= 7 && num58 > 0)
{
                                                                                                                                                                                                                                                        num58 = -252;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    if (num77 == 0 && num58 < 0)
{
                                                                                                                                                                                                                                                        num58 = 252;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    bool flag4 = false;
                                                                                                                                                                                                                                                    if (num58 != 0)
{
                                                                                                                                                                                                                                                        for (int num59 = num56; num59 < num56 + 2; num59++)
{
                                                                                                                                                                                                                                                            for (int num60 = num57; num60 < num57 + 2; num60++)
{
                                                                                                                                                                                                                                                                tile4 = Main.tile[num59, num60];
                                                                                                                                                                                                                                                                ref short frameY3 = ref tile4.frameY;
                                                                                                                                                                                                                                                                tile4 = Main.tile[num59, num60];
                                                                                                                                                                                                                                                                frameY3 = (short)(tile4.frameY + num58);
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        flag4 = true;
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                    if (flag4)
{
                                                                                                                                                                                                                                                        NetMessage.SendTileSquare(-1, num56, num57, 2, 2);
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                }
                                                                                                                                                                                                            }
                                                                                                                                                                                                        }
                                                                                                                                                                                                    }
                                                                                                                                                                                                }
                                                                                                                                                                                            }
                                                                                                                                                                                        }
                                                                                                                                                                                    }
                                                                                                                                                                                }
                                                                                                                                                                            }
                                                                                                                                                                        }
                                                                                                                                                                    }
                                                                                                                                                                }
                                                                                                                                                            }
                                                                                                                                                            goto IL_295e;
                                                                                                                                                        }
                                                                                                                                                    }
                                                                                                                                                }
                                                                                                                                                goto IL_0c62;
                                                                                                                                            }
                                                                                                                                        }
                                                                                                                                    }
                                                                                                                                }
                                                                                                                            }
                                                                                                                            short num14 = 18;
                                                                                                                            Tile tile = Main.tile[myX, myY];
                                                                                                                            if (tile.frameX > 0)
{
                                                                                                                                num14 = -18;
                                                                                                                            }
                                                                                                                            tile.frameX += num14;
                                                                                                                            NetMessage.SendTileSquare(-1, myX, myY);
                                                                                                                            flag10 = true;
                                                                                                                            GamepadEnableGrappleCooldown();
                                                                                                                        }
                                                                                                                    }
                                                                                                                }
                                                                                                                goto IL_295e;
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                    if (IsWithinSnappngRangeToTile(myX, myY, 40))
{
                                                                                                        flag10 = true;
                                                                                                        GamepadEnableGrappleCooldown();
                                                                                                        sitting.SitDown(this, myX, myY);
                                                                                                    }
                                                                                                    goto IL_295e;
                                                                                                }
                                                                                            }
                                                                                            if (IsWithinSnappngRangeToTile(myX, myY, 40))
{
                                                                                                flag10 = true;
                                                                                                GamepadEnableGrappleCooldown();
                                                                                                sitting.SitDown(this, myX, myY);
                                                                                            }
                                                                                            goto IL_295e;
                                                                                        }
                                                                                    }
                                                                                    flag10 = true;
                                                                                    tile4 = Main.tile[myX, myY];
                                                                                    bool flag12 = tile4.type == 389;
                                                                                    if (WorldGen.ShiftTallGate(myX, myY, flag12))
{
                                                                                        NetMessage.SendData(19, -1, -1, null, 4 + flag12.ToInt(), myX, myY);
                                                                                    }
                                                                                    goto IL_295e;
                                                                                }
                                                                            }
                                                                            flag10 = true;
                                                                            tile4 = Main.tile[myX, myY];
                                                                            bool flag11 = tile4.type == 387;
                                                                            int num10 = WorldGen.ShiftTrapdoor(myX, myY, (float)(myY * 16) > base.Center.Y).ToInt();
                                                                            if (num10 == 0)
{
                                                                                num10 = -WorldGen.ShiftTrapdoor(myX, myY, (float)(myY * 16) <= base.Center.Y).ToInt();
                                                                            }
                                                                            if (num10 != 0)
{
                                                                                NetMessage.SendData(19, -1, -1, null, 2 + (!flag11).ToInt(), myX, myY, num10 * Math.Sign((float)(myY * 16) - base.Center.Y));
                                                                            }
                                                                        }
                                                                    }
                                                                    goto IL_295e;
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                                flag10 = true;
                                                SoundEngine.PlaySound(28, myX * 16, myY * 16, 0);
                                                GamepadEnableGrappleCooldown();
                                                WorldGen.SwitchMonolith(myX, myY);
                                            }
                                        }
                                    }
                                    goto IL_295e;
                                }
                            }
                            flag10 = true;
                            tile4 = Main.tile[myX, myY];
                            int num3;
                            for (num3 = tile4.frameX / 18; num3 > 1; num3 -= 2)
{
                            }
                            num3 = myX - num3;
                            tile4 = Main.tile[myX, myY];
                            int num4 = myY - tile4.frameY / 18;
                            tile4 = Main.tile[myX, myY];
                            Animation.NewTemporaryAnimation(2, tile4.type, num3, num4);
                            tile4 = Main.tile[myX, myY];
                            NetMessage.SendTemporaryAnimation(-1, 2, tile4.type, num3, num4);
                            Wiring.HitSwitch(myX, myY);
                            NetMessage.SendData(59, -1, -1, null, myX, myY);
                        }
                        goto IL_295e;
                    }
                }
            }
            flag10 = true;
            Wiring.HitSwitch(myX, myY);
            NetMessage.SendData(59, -1, -1, null, myX, myY);
            goto IL_295e;
        }
        goto IL_2969;
        IL_295e:
        if (TileLoader.RightClick(myX, myY))
        {
            flag10 = true;
        }
        goto IL_2969;
        IL_224c:
        flag10 = true;
        Main.mouseRightRelease = false;
        int num61 = 0;
        tile4 = Main.tile[myX, myY];
        int num62;
        for (num62 = tile4.frameX / 18; num62 > 1; num62 -= 2)
        {
        }
        num62 = myX - num62;
        tile4 = Main.tile[myX, myY];
        int num64 = myY - tile4.frameY / 18;
        tile4 = Main.tile[myX, myY];
        if (tile4.type == 29)
        {
            num61 = 1;
        }
        else
        {
            tile4 = Main.tile[myX, myY];
            if (tile4.type == 97)
            {
                num61 = 2;
            }
            else
            {
                tile4 = Main.tile[myX, myY];
                if (tile4.type == 463)
                {
                    num61 = 3;
                    tile4 = Main.tile[myX, myY];
                    num62 = ((tile4.frameX != 36) ? (num62 + 1) : (num62 - 1));
                    num64 += 2;
                }
                else
                {
                    tile4 = Main.tile[myX, myY];
                    if (tile4.type == 491)
                    {
                        num61 = 4;
                        tile4 = Main.tile[myX, myY];
                        num62 = ((tile4.frameX != 36) ? (num62 + 1) : (num62 - 1));
                        num64 += 2;
                    }
                }
            }
        }
        CloseSign();
        SetTalkNPC(-1);
        Main.npcChatCornerItem = 0;
        Main.npcChatText = "";
        if (Main.editChest)
        {
            SoundEngine.PlaySound(12);
            Main.editChest = false;
            Main.npcChatText = string.Empty;
        }
        if (editedChestName)
        {
            NetMessage.SendData(33, -1, -1, NetworkText.FromLiteral(Main.chest[chest].name), chest, 1f);
            editedChestName = false;
        }
        bool flag5 = Chest.IsLocked(num62, num64);
        if (Main.netMode == 1 && num61 == 0 && !flag5)
        {
            if (num62 == chestX && num64 == chestY && chest != -1)
            {
                chest = -1;
                Recipe.FindRecipes();
                SoundEngine.PlaySound(11);
            }
            else
            {
                if (WorldGen.IsChestRigged(num62, num64))
                {
                    _framesLeftEligibleForDeadmansChestDeathAchievement = 600;
                }
                NetMessage.SendData(31, -1, -1, null, num62, num64);
                Main.stackSplit = 600;
            }
        }
        else
        {
            int num65 = -1;
            switch (num61)
            {
            case 1:
                num65 = -2;
                break;
            case 2:
                num65 = -3;
                break;
            case 3:
                num65 = -4;
                break;
            case 4:
                if (disableVoidBag < 0)
                {
                    num65 = -5;
                }
                break;
            default:
            {
                bool flag6 = false;
                if (Chest.IsLocked(num62, num64))
                {
                    tile4 = Main.tile[num62, num64];
                    int type2 = tile4.type;
                    int num66 = 327;
                    switch (type2)
                    {
                    case 21:
                        tile4 = Main.tile[num62, num64];
                        if (tile4.frameX >= 144)
{
                            tile4 = Main.tile[num62, num64];
                            if (tile4.frameX <= 178)
{
                                num66 = 329;
                            }
                        }
                        tile4 = Main.tile[num62, num64];
                        if (tile4.frameX < 828)
{
                            break;
                        }
                        tile4 = Main.tile[num62, num64];
                        if (tile4.frameX <= 1006)
{
                            tile4 = Main.tile[num62, num64];
                            int num67 = tile4.frameX / 18;
                            int num68 = 0;
                            while (num67 >= 2)
{
                                num67 -= 2;
                                num68++;
                            }
                            num68 -= 23;
                            num66 = 1533 + num68;
                        }
                        break;
                    case 467:
                        tile4 = Main.tile[num62, num64];
                        if (tile4.frameX / 36 == 13)
{
                            num66 = 4714;
                        }
                        break;
                    }
                    flag6 = true;
                    bool flag7 = false;
                    bool flag8 = num66 != 329;
                    for (int num69 = 0; num69 < 58; num69++)
                    {
                        if (inventory[num69].type != num66 || inventory[num69].stack <= 0 || !Chest.Unlock(num62, num64))
{
                            continue;
                        }
                        flag7 = true;
                        if (flag8)
{
                            if (ItemLoader.ConsumeItem(inventory[num69], this))
{
                                inventory[num69].stack--;
                            }
                            if (inventory[num69].stack <= 0)
{
                                inventory[num69] = new Item();
                            }
                        }
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(52, -1, -1, null, whoAmI, 1f, num62, num64);
                        }
                    }
                    if (!flag7 && useVoidBag())
                    {
                        for (int num70 = 0; num70 < 40; num70++)
{
                            if (bank4.item[num70].type != num66 || bank4.item[num70].stack <= 0 || !Chest.Unlock(num62, num64))
{
                                continue;
                            }
                            if (num66 != 329)
{
                                bank4.item[num70].stack--;
                                if (bank4.item[num70].stack <= 0)
{
                                    bank4.item[num70] = new Item();
                                }
                            }
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(52, -1, -1, null, whoAmI, 1f, num62, num64);
                            }
                        }
                    }
                }
                if (!flag6)
                {
                    num65 = Chest.FindChest(num62, num64);
                }
                break;
            }
            }
            if (num65 != -1)
            {
                Main.stackSplit = 600;
                bool num78 = WorldGen.IsChestRigged(num62, num64);
                if (num65 == chest)
                {
                    chest = -1;
                    SoundEngine.PlaySound(11);
                }
                else if (num65 != chest && chest == -1)
                {
                    OpenChest(num62, num64, num65);
                    SoundEngine.PlaySound(10);
                    tile4 = Main.tile[num62, num64];
                    if (tile4.frameX >= 36)
                    {
                        tile4 = Main.tile[num62, num64];
                        if (tile4.frameX < 72)
{
                            AchievementsHelper.HandleSpecialEvent(this, 16);
                        }
                    }
                }
                else
                {
                    OpenChest(num62, num64, num65);
                    SoundEngine.PlaySound(12);
                }
                if (num78)
                {
                    Wiring.HitSwitch(myX, myY);
                    NetMessage.SendData(59, -1, -1, null, myX, myY);
                    _framesLeftEligibleForDeadmansChestDeathAchievement = 600;
                }
                Recipe.FindRecipes();
            }
        }
        goto IL_295e;
        IL_2969:
        if (flag10)
        {
            tileInteractionHappened = true;
        }
        return;
        IL_0c62:
        WorldGen.KillTile(myX, myY);
        if (Main.netMode == 1)
        {
            NetMessage.SendData(17, -1, -1, null, 0, myX, myY);
        }
        flag10 = true;
        GamepadEnableGrappleCooldown();
        goto IL_295e;
    }
References Terraria.Player._framesLeftEligibleForDeadmansChestDeathAchievement, Terraria.Mount.Active, Terraria.Player.AddBuff(), Terraria.NPC.AnyNPCs(), Terraria.Player.bank4, Terraria.ID.TileID.Sets.BasicChest, Terraria.Main.CancelClothesWindow(), Terraria.ID.TileID.Sets.CanDropFromRightClick, Terraria.Mount.Cart, Terraria.Player.ChangeSpawn(), Terraria.Player.CheckSpawn(), Terraria.Main.chest, Terraria.Player.chest, Terraria.Player.chestX, Terraria.Player.chestY, Terraria.DataStructures.TrackedProjectileReference.Clear(), Terraria.WorldGen.CloseDoor(), Terraria.ModLoader.TileLoader.CloseDoorID(), Terraria.Player.CloseSign(), Terraria.Player.ConsumeItem(), Terraria.ModLoader.ItemLoader.ConsumeItem(), Terraria.ID.TileID.Count, Terraria.Main.dayTime, Terraria.Entity.direction, Terraria.Player.disableVoidBag, Terraria.Mount.Dismount(), Terraria.NPC.downedPlantBoss, Terraria.Main.editChest, Terraria.Player.editedChestName, Terraria.GameContent.Events.DD2Event.FailureMessage(), Terraria.Main.fastForwardTimeToDawn, Terraria.Main.fastForwardTimeToDusk, Terraria.Chest.FindChest(), Terraria.Recipe.FindRecipes(), Terraria.Player.FindSpawn(), Terraria.Tile.frameX, Terraria.Localization.NetworkText.FromLiteral(), Terraria.Player.GamepadEnableGrappleCooldown(), Terraria.Player.GetPreferredGolfBallToUse(), Terraria.Player.GetProjectileSource_TileInteraction(), Terraria.Localization.Language.GetTextValue(), Terraria.Framing.GetTileSafely(), Terraria.Player.gravDir, Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Player.HasItem(), Terraria.Wiring.HitSwitch(), Terraria.Player.inventory, Terraria.ID.ProjectileID.Sets.IsAGolfBall, Terraria.WorldGen.IsChestRigged(), Terraria.ModLoader.TileLoader.IsClosedDoor(), Terraria.Player.IsHoveringOverABottomSideOfABed(), Terraria.Chest.IsLocked(), Terraria.WorldGen.IsLockedDoor(), Terraria.ModLoader.TileLoader.IsModMusicBox(), Terraria.Player.IsWithinSnappngRangeToTile(), Terraria.Chest.item, Terraria.ID.SoundID.Item11, Terraria.ID.SoundID.Item149, Terraria.ID.SoundID.Item2, Terraria.ID.SoundID.Item37, Terraria.ID.SoundID.Item4, Terraria.Player.ItemFitsWeaponRack(), Terraria.WorldGen.KillTile(), Terraria.Player.LaunchMinecartHook(), Terraria.WorldGen.LaunchRocket(), Terraria.WorldGen.LaunchRocketSmall(), Terraria.Main.moondialCooldown, Terraria.Main.Moondialing(), Terraria.Player.mount, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.NewProjectile(), Terraria.Animation.NewTemporaryAnimation(), Terraria.Main.NewText(), Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.GameContent.Tile_Entities.TEDisplayDoll.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEHatRack.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEItemFrame.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.OnPlayerInteraction(), Terraria.GameContent.UI.WiresUI.Open, Terraria.Player.OpenChest(), Terraria.Main.OpenClothesWindow(), Terraria.WorldGen.OpenDoor(), Terraria.Player.ownedProjectileCounts, Terraria.Player.piggyBankProjTracker, Terraria.Player.PlaceWeapon(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Sign.ReadSign(), Terraria.Player.releaseUseTile, Terraria.Player.RemoveSpawn(), Terraria.GameContent.Events.DD2Event.RequestToSkipWaitTime(), Terraria.ModLoader.TileLoader.RightClick(), Terraria.Player.selectedItem, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTemporaryAnimation(), Terraria.NetMessage.SendTileSquare(), Terraria.Item.SetDefaults(), Terraria.Player.SetTalkNPC(), Terraria.WorldGen.ShiftTallGate(), Terraria.WorldGen.ShiftTrapdoor(), Terraria.WorldGen.ShootFromCannon(), Terraria.Main.sign, Terraria.Player.sign, Terraria.GameContent.PlayerSittingHelper.SitDown(), Terraria.Player.sitting, Terraria.Player.sleeping, Terraria.Player.snowBallLauncherInteractionCooldown, Terraria.Main.snowMoon, Terraria.NPC.SpawnOnPlayer(), Terraria.Player.SpawnX, Terraria.Player.SpawnY, Terraria.Item.stack, Terraria.GameContent.PlayerSleepingHelper.StartSleeping(), Terraria.GameContent.Events.DD2Event.SummonCrystal(), Terraria.Main.sundialCooldown, Terraria.Main.Sundialing(), Terraria.WorldGen.SwitchFountain(), Terraria.WorldGen.SwitchMB(), Terraria.WorldGen.SwitchMonolith(), Terraria.Main.tile, Terraria.Player.tileInteractAttempted, Terraria.Player.tileInteractionHappened, Terraria.Main.tileSign, Terraria.Main.time, Terraria.WorldGen.ToggleGemLock(), Terraria.GameContent.Events.BirthdayParty.ToggleManualParty(), Terraria.ID.TileID.Sets.Torch, Terraria.Player.TryOpeningFullscreenMap(), Terraria.Item.type, Terraria.Chest.Unlock(), Terraria.WorldGen.UnlockDoor(), Terraria.Player.useVoidBag(), Terraria.Player.voidLensChest, Terraria.Entity.whoAmI, and Terraria.GameContent.Events.DD2Event.WouldFailSpawningHere().
Referenced by Terraria.Player.TileInteractionsCheck().