TModLoader: Terraria.Player.ItemCheck_GetMeleeHitbox
ItemCheck_GetMeleeHitbox()
void Terraria.Player.ItemCheck_GetMeleeHitbox (Item sItem, Rectangle heldItemFrame, out bool dontAttack, out Rectangle itemRectangle) inline private
    {
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0598: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0434: Unknown result type (might be due to invalid IL or missing references)
        //IL_043b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0441: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05db: Unknown result type (might be due to invalid IL or missing references)
        //IL_05eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0605: Unknown result type (might be due to invalid IL or missing references)
        //IL_0607: Unknown result type (might be due to invalid IL or missing references)
        //IL_0611: Unknown result type (might be due to invalid IL or missing references)
        //IL_0616: Unknown result type (might be due to invalid IL or missing references)
        //IL_062e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0634: Unknown result type (might be due to invalid IL or missing references)
        //IL_0649: Unknown result type (might be due to invalid IL or missing references)
        //IL_064b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0668: Unknown result type (might be due to invalid IL or missing references)
        //IL_066d: Unknown result type (might be due to invalid IL or missing references)
        //IL_047b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0482: Unknown result type (might be due to invalid IL or missing references)
        //IL_0488: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0505: Unknown result type (might be due to invalid IL or missing references)
        //IL_050c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0512: Unknown result type (might be due to invalid IL or missing references)
        dontAttack = false;
        itemRectangle = new Rectangle((int)itemLocation.X, (int)itemLocation.Y, 32, 32);
        if (!Main.dedServ)
        {
            int num = heldItemFrame.Width;
            int num2 = heldItemFrame.Height;
            switch (sItem.type)
            {
            case 5094:
                num -= 10;
                num2 -= 10;
                break;
            case 5095:
                num -= 10;
                num2 -= 10;
                break;
            case 5096:
                num -= 12;
                num2 -= 12;
                break;
            case 5097:
                num -= 8;
                num2 -= 8;
                break;
            }
            itemRectangle = new Rectangle((int)itemLocation.X, (int)itemLocation.Y, num, num2);
        }
        float adjustedItemScale = GetAdjustedItemScale(sItem);
        itemRectangle.Width = (int)((float)itemRectangle.Width * adjustedItemScale);
        itemRectangle.Height = (int)((float)itemRectangle.Height * adjustedItemScale);
        if (direction == -1)
        {
            itemRectangle.X -= itemRectangle.Width;
        }
        if (gravDir == 1f)
        {
            itemRectangle.Y -= itemRectangle.Height;
        }
        if (sItem.useStyle == 1)
        {
            if ((double)itemAnimation < (double)itemAnimationMax * 0.333)
            {
                if (direction == -1)
                {
                    itemRectangle.X -= (int)((double)itemRectangle.Width * 1.4 - (double)itemRectangle.Width);
                }
                itemRectangle.Width = (int)((double)itemRectangle.Width * 1.4);
                itemRectangle.Y += (int)((double)itemRectangle.Height * 0.5 * (double)gravDir);
                itemRectangle.Height = (int)((double)itemRectangle.Height * 1.1);
            }
            else if (!((double)itemAnimation < (double)itemAnimationMax * 0.666))
            {
                if (direction == 1)
                {
                    itemRectangle.X -= (int)((double)itemRectangle.Width * 1.2);
                }
                itemRectangle.Width *= 2;
                itemRectangle.Y -= (int)(((double)itemRectangle.Height * 1.4 - (double)itemRectangle.Height) * (double)gravDir);
                itemRectangle.Height = (int)((double)itemRectangle.Height * 1.4);
            }
        }
        else if (sItem.useStyle == 3)
        {
            if ((double)itemAnimation > (double)itemAnimationMax * 0.666)
            {
                dontAttack = true;
            }
            else
            {
                if (direction == -1)
                {
                    itemRectangle.X -= (int)((double)itemRectangle.Width * 1.4 - (double)itemRectangle.Width);
                }
                itemRectangle.Width = (int)((double)itemRectangle.Width * 1.4);
                itemRectangle.Y += (int)((double)itemRectangle.Height * 0.6);
                itemRectangle.Height = (int)((double)itemRectangle.Height * 0.6);
                if (sItem.type == 946 || sItem.type == 4707)
                {
                    itemRectangle.Height += 14;
                    itemRectangle.Width -= 10;
                    if (direction == -1)
                    {
                        itemRectangle.X += 10;
                    }
                }
            }
        }
        ItemLoader.UseItemHitbox(sItem, this, ref itemRectangle, ref dontAttack);
        if (sItem.type == 1450 && Main.rand.Next(3) == 0)
        {
            int num3 = -1;
            float x = itemRectangle.X + Main.rand.Next(itemRectangle.Width);
            float y = itemRectangle.Y + Main.rand.Next(itemRectangle.Height);
            if (Main.rand.Next(500) == 0)
            {
                num3 = Gore.NewGore(new Vector2(x, y), default(Vector2), 415, (float)Main.rand.Next(51, 101) * 0.01f);
            }
            else if (Main.rand.Next(250) == 0)
            {
                num3 = Gore.NewGore(new Vector2(x, y), default(Vector2), 414, (float)Main.rand.Next(51, 101) * 0.01f);
            }
            else if (Main.rand.Next(80) == 0)
            {
                num3 = Gore.NewGore(new Vector2(x, y), default(Vector2), 413, (float)Main.rand.Next(51, 101) * 0.01f);
            }
            else if (Main.rand.Next(10) == 0)
            {
                num3 = Gore.NewGore(new Vector2(x, y), default(Vector2), 412, (float)Main.rand.Next(51, 101) * 0.01f);
            }
            else if (Main.rand.Next(3) == 0)
            {
                num3 = Gore.NewGore(new Vector2(x, y), default(Vector2), 411, (float)Main.rand.Next(51, 101) * 0.01f);
            }
            if (num3 >= 0)
            {
                Main.gore[num3].velocity.X += direction * 2;
                Main.gore[num3].velocity.Y *= 0.3f;
            }
        }
        if (sItem.type == 3542)
        {
            dontAttack = true;
        }
        if (sItem.type == 3779)
        {
            dontAttack = true;
            Vector2 vector = itemLocation + new Vector2((float)(direction * 30), -8f);
            Vector2 vector2 = vector - position;
            for (float num4 = 0f; num4 < 1f; num4 += 0.2f)
            {
                Vector2 vector3 = Vector2.Lerp(oldPosition + vector2 + new Vector2(0f, gfxOffY), vector, num4);
                Dust obj = Main.dust[Dust.NewDust(vector - Vector2.One * 8f, 16, 16, 27, 0f, -2f)];
                obj.noGravity = true;
                obj.position = vector3;
                obj.velocity = new Vector2(0f, (0f - gravDir) * 2f);
                obj.scale = 1.2f;
                obj.alpha = 200;
            }
        }
    }
References Terraria.Main.dedServ, Terraria.Entity.direction, Terraria.Main.dust, Terraria.Player.GetAdjustedItemScale(), Terraria.Player.gfxOffY, Terraria.Main.gore, Terraria.Player.gravDir, Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, Terraria.Player.itemLocation, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Entity.oldPosition, Terraria.Entity.position, Terraria.Main.rand, and Terraria.ModLoader.ItemLoader.UseItemHitbox().
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode().