TModLoader: Terraria.Player.DelBuff
DelBuff()
void Terraria.Player.DelBuff (int b) inline
Removes the buff at the provided index in F:Terraria.Player.buffType and F:Terraria.Player.buffTime and shuffles the remaining buff indexes down to fill the gap. Use M:Terraria.Player.ClearBuff(System.Int32) if you only know the T:Terraria.ID.BuffID.
Parameters
b The index in F:Terraria.Player.buffType of the buff to remove.
Definition at line 5868 of file Player.cs.
    {
        buffTime[b] = 0;
        buffType[b] = 0;
        int num = 0;
        for (int i = 0; i < maxBuffs - 1; i++)
        {
            if (buffTime[i] != 0 && buffType[i] != 0)
            {
                if (num < i)
                {
                    buffTime[num] = buffTime[i];
                    buffType[num] = buffType[i];
                    buffTime[i] = 0;
                    buffType[i] = 0;
                }
                num++;
            }
        }
    }
References Terraria.Player.buffTime, Terraria.Player.buffType, and Terraria.Player.maxBuffs.
Referenced by Terraria.Player.AddBuff(), Terraria.Player.AddBuff_ActuallyTryToAddTheBuff(), Terraria.Player.AddBuff_RemoveOldMeleeBuffsOfMatchingType(), Terraria.Player.AddBuff_RemoveOldPetBuffsOfMatchingType(), Terraria.Player.ClearBuff(), Terraria.Player.ConsumeSolarFlare(), Terraria.Player.ItemCheck_ApplyPetBuffs(), Terraria.Player.NebulaLevelup(), Terraria.Player.OnHurt_Part1(), Terraria.Player.OnHurt_Part2(), Terraria.Player.ShadowDodge(), Terraria.Player.TryToPoop(), Terraria.Player.Update(), Terraria.Player.UpdateArmorSets(), and Terraria.Player.UpdateBuffs().