TModLoader: Terraria.Player.UpdateLuckFactors
UpdateLuckFactors()
void Terraria.Player.UpdateLuckFactors () inline
    {
        UpdateLadyBugLuckTime();
        UpdateCoinLuck();
        if (whoAmI == Main.myPlayer)
        {
            float num = torchLuck;
            TryRecalculatingTorchLuck();
            if (torchLuck != num)
            {
                luckNeedsSync = true;
            }
        }
    }
References Terraria.Player.luckNeedsSync, Terraria.Main.myPlayer, Terraria.Player.torchLuck, Terraria.Player.TryRecalculatingTorchLuck(), Terraria.Player.UpdateCoinLuck(), Terraria.Player.UpdateLadyBugLuckTime(), and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.UpdateLuck().