TModLoader: Terraria.Player.UpdateBootVisualEffects
UpdateBootVisualEffects()
void Terraria.Player.UpdateBootVisualEffects (Item item) inline private
Definition at line 35693 of file Player.cs.
    {
        switch (item.type)
        {
        case 128:
            vanityRocketBoots = 1;
            break;
        case 54:
            CancelAllBootRunVisualEffects();
            break;
        case 405:
        case 898:
            CancelAllBootRunVisualEffects();
            vanityRocketBoots = 2;
            break;
        case 4874:
            CancelAllBootRunVisualEffects();
            vanityRocketBoots = 5;
            hellfireTreads = true;
            break;
        case 1862:
            CancelAllBootRunVisualEffects();
            vanityRocketBoots = 3;
            break;
        case 5000:
            CancelAllBootRunVisualEffects();
            vanityRocketBoots = 4;
            break;
        case 3200:
        case 3990:
            CancelAllBootRunVisualEffects();
            sailDash = true;
            break;
        case 1579:
            CancelAllBootRunVisualEffects();
            coldDash = true;
            break;
        case 4055:
            CancelAllBootRunVisualEffects();
            desertDash = true;
            break;
        case 3993:
            CancelAllBootRunVisualEffects();
            fairyBoots = true;
            vanityRocketBoots = 2;
            break;
        }
    }
References Terraria.Player.CancelAllBootRunVisualEffects(), Terraria.Player.coldDash, Terraria.Player.desertDash, Terraria.Player.fairyBoots, Terraria.Player.hellfireTreads, Terraria.Player.sailDash, Terraria.Item.type, and Terraria.Player.vanityRocketBoots.
Referenced by Terraria.Player.ApplyEquipFunctional(), and Terraria.Player.ApplyEquipVanity().