TModLoader: Terraria.Player.MagicConch
MagicConch()
void Terraria.Player.MagicConch () inline
    {
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_0176: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_0113: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_0118: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        bool flag = position.X / 16f < (float)(Main.maxTilesX / 2);
        bool flag2 = false;
        int num = 50;
        int num2 = 50;
        int num3 = WorldGen.beachDistance - num - num2;
        if (flag)
        {
            num3 = Main.maxTilesX - num3 - 1 - num2;
        }
        else
        {
            num3 -= num2 / 2;
        }
        _ = (float)Main.maxTilesY / 1200f;
        _ = (float)Main.maxTilesY / 1200f;
        new RandomTeleportationAttemptSettings
        {
            avoidAnyLiquid = true,
            avoidHurtTiles = true,
            attemptsBeforeGivingUp = 1000,
            maximumFallDistanceFromOrignalPoint = 300
        };
        Vector2 vector = Vector2.Zero;
        int num4 = flag.ToDirectionInt();
        int startX = (flag ? (Main.maxTilesX - 50) : 50);
        flag2 = true;
        if (!TeleportHelpers.RequestMagicConchTeleportPosition(this, -num4, startX, out var landingPoint))
        {
            flag2 = false;
            startX = ((!flag) ? (Main.maxTilesX - 50) : 50);
            if (TeleportHelpers.RequestMagicConchTeleportPosition(this, num4, startX, out landingPoint))
            {
                flag2 = true;
            }
        }
        if (flag2)
        {
            vector = landingPoint.ToWorldCoordinates(8f, 16f) - new Vector2((float)(width / 2), (float)height);
        }
        if (flag2)
        {
            Vector2 newPos = vector;
            Teleport(newPos, 5);
            velocity = Vector2.Zero;
            if (Main.netMode == 2)
            {
                RemoteClient.CheckSection(whoAmI, position);
                NetMessage.SendData(65, -1, -1, null, 0, whoAmI, newPos.X, newPos.Y, 5);
            }
        }
        else
        {
            Vector2 newPos2 = position;
            Teleport(newPos2, 5);
            velocity = Vector2.Zero;
            if (Main.netMode == 2)
            {
                RemoteClient.CheckSection(whoAmI, position);
                NetMessage.SendData(65, -1, -1, null, 0, whoAmI, newPos2.X, newPos2.Y, 5, 1);
            }
        }
    }
References Terraria.RemoteClient.CheckSection(), Terraria.Entity.height, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Entity.position, Terraria.GameContent.TeleportHelpers.RequestMagicConchTeleportPosition(), Terraria.NetMessage.SendData(), Terraria.Player.Teleport(), Terraria.Entity.velocity, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Player.ItemCheck_Inner().