TModLoader: Terraria.Player.Spawn
Spawn()
void Terraria.Player.Spawn (PlayerSpawnContext context) inline
Definition at line 36486 of file Player.cs.
    {
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0118: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0340: Unknown result type (might be due to invalid IL or missing references)
        //IL_0356: Unknown result type (might be due to invalid IL or missing references)
        //IL_035b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0397: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        Main.LocalPlayer.creativeInterface = false;
        _funkytownAchievementCheckCooldown = 100;
        bool flag = false;
        if (context == PlayerSpawnContext.SpawningIntoWorld)
        {
            if (Main.netMode == 0 && unlockedBiomeTorches)
            {
                NPC nPC = new NPC();
                nPC.SetDefaults(664);
                Main.BestiaryTracker.Kills.RegisterKill(nPC);
            }
            if (dead)
            {
                AdjustRespawnTimerForWorldJoining(this);
                if (dead)
                {
                    flag = true;
                }
            }
        }
        StopVanityActions();
        if (whoAmI == Main.myPlayer)
        {
            Main.NotifyOfEvent(GameNotificationType.SpawnOrDeath);
        }
        if (whoAmI == Main.myPlayer)
        {
            if (Main.mapTime < 5)
            {
                Main.mapTime = 5;
            }
            Main.instantBGTransitionCounter = 10;
            FindSpawn();
            if (!CheckSpawn(SpawnX, SpawnY))
            {
                SpawnX = -1;
                SpawnY = -1;
            }
            Main.maxQ = true;
            NPC.ResetNetOffsets();
        }
        if (Main.netMode == 1 && whoAmI == Main.myPlayer)
        {
            NetMessage.SendData(12, -1, -1, null, Main.myPlayer, (int)(byte)context);
        }
        headPosition = Vector2.Zero;
        bodyPosition = Vector2.Zero;
        legPosition = Vector2.Zero;
        headRotation = 0f;
        bodyRotation = 0f;
        legRotation = 0f;
        rabbitOrderFrame.Reset();
        lavaTime = lavaMax;
        if (!flag)
        {
            if (statLife <= 0)
            {
                int num = statLifeMax2 / 2;
                statLife = 100;
                if (num > statLife)
                {
                    statLife = num;
                }
                breath = breathMax;
                if (spawnMax)
                {
                    statLife = statLifeMax2;
                    statMana = statManaMax2;
                }
            }
            immune = true;
            if (dead)
            {
                PlayerLoader.OnRespawn(this);
            }
            dead = false;
            immuneTime = 0;
        }
        active = true;
        Vector2 value = position;
        if (SpawnX >= 0 && SpawnY >= 0)
        {
            _ = SpawnX;
            _ = SpawnY;
            Spawn_SetPosition(SpawnX, SpawnY);
        }
        else
        {
            Spawn_SetPositionAtWorldSpawn();
        }
        wet = false;
        wetCount = 0;
        lavaWet = false;
        fallStart = (int)(position.Y / 16f);
        fallStart2 = fallStart;
        velocity.X = 0f;
        velocity.Y = 0f;
        ResetAdvancedShadows();
        for (int i = 0; i < 3; i++)
        {
            UpdateSocialShadow();
        }
        oldPosition = position + BlehOldPositionFixer;
        SetTalkNPC(-1);
        if (whoAmI == Main.myPlayer)
        {
            Main.npcChatCornerItem = 0;
        }
        if (!flag)
        {
            if (pvpDeath)
            {
                pvpDeath = false;
                immuneTime = 300;
                statLife = statLifeMax;
            }
            else if (context == PlayerSpawnContext.ReviveFromDeath)
            {
                immuneTime = 180;
            }
            else
            {
                immuneTime = 60;
            }
            if (immuneTime > 0 && !hostile)
            {
                immuneNoBlink = true;
            }
        }
        if (whoAmI == Main.myPlayer)
        {
            float num2 = Vector2.Distance(value, position);
            Vector2 val = new Vector2((float)Main.screenWidth, (float)Main.screenHeight);
            bool flag2 = num2 < ((Vector2)(ref val)).Length() / 2f + 100f;
            if (flag2)
            {
                Main.SetCameraLerp(0.1f, 0);
                flag2 = true;
            }
            else
            {
                Main.BlackFadeIn = 255;
                Lighting.Clear();
                Main.screenLastPosition = Main.screenPosition;
                Main.instantBGTransitionCounter = 10;
            }
            if (!flag2)
            {
                Main.renderNow = true;
            }
            if (Main.netMode == 1)
            {
                Netplay.AddCurrentServerToRecentList();
            }
            if (!flag2)
            {
                Main.screenPosition.X = position.X + (float)(width / 2) - (float)(Main.screenWidth / 2);
                Main.screenPosition.Y = position.Y + (float)(height / 2) - (float)(Main.screenHeight / 2);
                ForceUpdateBiomes();
            }
        }
        if (flag)
        {
            immuneAlpha = 255;
        }
        UpdateGraveyard(now: true);
        if (whoAmI == Main.myPlayer && context == PlayerSpawnContext.ReviveFromDeath && difficulty == 3)
        {
            AutoFinchStaff();
        }
        if (whoAmI == Main.myPlayer && context == PlayerSpawnContext.SpawningIntoWorld)
        {
            Main.ReleaseHostAndPlayProcess();
            RefreshItems();
            SetPlayerDataToOutOfClassFields();
            Main.LocalGolfState.SetScoreTime();
            Main.ActivePlayerFileData.StartPlayTimer();
            Hooks.EnterWorld(whoAmI);
        }
    }
References Terraria.Player._funkytownAchievementCheckCooldown, Terraria.Entity.active, Terraria.Main.ActivePlayerFileData, Terraria.Netplay.AddCurrentServerToRecentList(), Terraria.Player.AdjustRespawnTimerForWorldJoining(), Terraria.Player.AutoFinchStaff(), Terraria.Main.BestiaryTracker, Terraria.Player.BlehOldPositionFixer, Terraria.Player.bodyPosition, Terraria.Player.bodyRotation, Terraria.Player.breath, Terraria.Player.breathMax, Terraria.Player.CheckSpawn(), Terraria.Lighting.Clear(), Terraria.Player.dead, Terraria.Player.difficulty, Terraria.Player.Hooks.EnterWorld(), Terraria.Player.fallStart, Terraria.Player.fallStart2, Terraria.Player.FindSpawn(), Terraria.Player.ForceUpdateBiomes(), Terraria.Player.headPosition, Terraria.Player.headRotation, Terraria.Entity.height, Terraria.Player.hostile, Terraria.Player.immune, Terraria.Player.immuneAlpha, Terraria.Player.immuneNoBlink, Terraria.Player.immuneTime, Terraria.Player.lavaMax, Terraria.Player.lavaTime, Terraria.Entity.lavaWet, Terraria.Player.legPosition, Terraria.Player.legRotation, Terraria.Main.LocalGolfState, Terraria.Main.mapTime, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.NotifyOfEvent(), Terraria.Entity.oldPosition, Terraria.ModLoader.PlayerLoader.OnRespawn(), Terraria.Entity.position, Terraria.Player.pvpDeath, Terraria.Player.rabbitOrderFrame, Terraria.Player.RefreshItems(), Terraria.Main.ReleaseHostAndPlayProcess(), Terraria.Player.RabbitOrderFrameHelper.Reset(), Terraria.Player.ResetAdvancedShadows(), Terraria.NPC.ResetNetOffsets(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.NetMessage.SendData(), Terraria.Main.SetCameraLerp(), Terraria.Player.SetPlayerDataToOutOfClassFields(), Terraria.GameContent.Golf.GolfState.SetScoreTime(), Terraria.Player.SetTalkNPC(), Terraria.Player.Spawn_SetPosition(), Terraria.Player.Spawn_SetPositionAtWorldSpawn(), Terraria.Player.spawnMax, Terraria.Player.SpawnX, Terraria.Player.SpawnY, Terraria.IO.PlayerFileData.StartPlayTimer(), Terraria.Player.statLife, Terraria.Player.statLifeMax, Terraria.Player.statLifeMax2, Terraria.Player.statMana, Terraria.Player.statManaMax2, Terraria.Player.StopVanityActions(), Terraria.Player.unlockedBiomeTorches, Terraria.Player.UpdateGraveyard(), Terraria.Player.UpdateSocialShadow(), Terraria.Entity.wet, Terraria.Entity.wetCount, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.DoPotionOfReturnTeleportationAndSetTheComebackPoint(), Terraria.WorldGen.FinishPlayWorld(), Terraria.MessageBuffer.GetData(), Terraria.Main.Initialize_AlmostEverything(), Terraria.Player.ItemCheck_Inner(), and Terraria.Player.UpdateDead().