TModLoader: Terraria.Player.ItemCheck_TurretAltFeatureUse
ItemCheck_TurretAltFeatureUse()
void Terraria.Player.ItemCheck_TurretAltFeatureUse (Item sItem, bool cShoot) inline private
Definition at line 50397 of file Player.cs.
    {
        if (sItem.shoot <= 0 || !ProjectileID.Sets.TurretFeature[sItem.shoot] || altFunctionUse != 2 || !cShoot || !ItemTimeIsZero)
        {
            return;
        }
        ApplyItemTime(sItem);
        if (whoAmI != Main.myPlayer)
        {
            return;
        }
        for (int i = 0; i < 1000; i++)
        {
            Projectile projectile = Main.projectile[i];
            if (projectile.active && projectile.owner == Main.myPlayer && ProjectileID.Sets.TurretFeature[projectile.type])
            {
                projectile.Kill();
            }
        }
    }
References Terraria.Entity.active, Terraria.Player.altFunctionUse, Terraria.Player.ApplyItemTime(), Terraria.Player.ItemTimeIsZero, Terraria.Projectile.Kill(), Terraria.Main.myPlayer, Terraria.Projectile.owner, Terraria.Main.projectile, Terraria.ID.ProjectileID.Sets.TurretFeature, Terraria.Projectile.type, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode().