TModLoader: Terraria.Player.DoBootsEffect_PlaceFlamesOnTile
DoBootsEffect_PlaceFlamesOnTile()
bool Terraria.Player.DoBootsEffect_PlaceFlamesOnTile (int X, int Y) inline
Definition at line 12017 of file Player.cs.
    {
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        Tile tile = Main.tile[X, Y + 1];
        if (tile == null || !tile.active() || tile.liquid > 0 || !WorldGen.SolidTileAllowBottomSlope(X, Y + 1))
        {
            return false;
        }
        ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.FlameWaders, new ParticleOrchestraSettings
        {
            PositionInWorld = new Vector2((float)(X * 16 + 8), (float)(Y * 16 + 16))
        }, whoAmI);
        return true;
    }
References Terraria.Tile.active(), Terraria.Tile.liquid, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.Main.tile, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ApplyEquipFunctional(), and Terraria.Player.ApplyEquipVanity().