TModLoader: Terraria.Player.SavePlayer
SavePlayer()
static void Terraria.Player.SavePlayer (PlayerFileData playerFile, bool skipMapSave = false) inline static
Definition at line 55357 of file Player.cs.
    {
        try
        {
            Main.Achievements.Save();
            InternalSaveMap(playerFile.IsCloudSave);
            if (!Main.ServerSideCharacter)
            {
                FileUtilities.ProtectedInvoke(delegate
                {
                    InternalSavePlayerFile(playerFile);
                });
            }
        }
        catch (Exception exception)
        {
            FancyErrorPrinter.ShowFileSavingFailError(exception, playerFile.Path);
            if (!Main.gameMenu)
            {
                WorldGen.SaveAndQuit();
            }
            Utils.ShowFancyErrorMessage($"{Language.GetTextValue("tModLoader.PlayerSaveFail")}\n\n{exception}", Main.menuMode);
            throw;
        }
    }
References Terraria.Main.Achievements, Terraria.Main.gameMenu, Terraria.Player.InternalSaveMap(), Terraria.Player.InternalSavePlayerFile(), Terraria.Main.menuMode, Terraria.Utilities.FileUtilities.ProtectedInvoke(), Terraria.WorldGen.SaveAndQuit(), Terraria.Main.ServerSideCharacter, Terraria.Utils.ShowFancyErrorMessage(), and Terraria.UI.FancyErrorPrinter.ShowFileSavingFailError().
Referenced by Terraria.IO.PlayerFileData.CreateAndSave(), Terraria.Netplay.InnerClientLoop(), Terraria.IO.PlayerFileData.Rename(), Terraria.WorldGen.SaveAndQuitCallBack(), and Terraria.WorldGen.saveToonWhilePlayingCallBack().