TModLoader: Terraria.Player.Hurt
Hurt() [1/4]
void Terraria.Player.Hurt (HurtInfo info, bool quiet = false) inline
Definition at line 37317 of file Player.cs.
    {
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0312: Unknown result type (might be due to invalid IL or missing references)
        //IL_0331: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0825: Unknown result type (might be due to invalid IL or missing references)
        //IL_082b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0846: Unknown result type (might be due to invalid IL or missing references)
        //IL_0877: Unknown result type (might be due to invalid IL or missing references)
        //IL_087d: Unknown result type (might be due to invalid IL or missing references)
        //IL_091a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0947: Unknown result type (might be due to invalid IL or missing references)
        //IL_094d: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_077e: Unknown result type (might be due to invalid IL or missing references)
        //IL_075d: Unknown result type (might be due to invalid IL or missing references)
        PlayerDeathReason damageSource = info.DamageSource;
        int hitDirection = info.HitDirection;
        int cooldownCounter = info.CooldownCounter;
        bool pvp = info.PvP;
        double num20 = info.Damage;
        bool Crit = false;
        bool flag2 = cooldownCounter == 2;
        if (Main.netMode == 1 && whoAmI == Main.myPlayer && !quiet)
        {
            if (info.Knockback != 0f && hitDirection != 0 && (!mount.Active || !mount.Cart))
            {
                NetMessage.SendData(13, -1, -1, null, whoAmI);
            }
            NetMessage.SendData(16, -1, -1, null, whoAmI);
            NetMessage.SendPlayerHurt(whoAmI, info);
        }
        PlayerLoader.OnHurt(this, info);
        OnHurt_Part1(info);
        OnHurt_Part2(info);
        OnHurt_Part3(info);
        Color color = (Crit ? CombatText.DamagedFriendlyCrit : CombatText.DamagedFriendly);
        CombatText.NewText(new Rectangle((int)position.X, (int)position.Y, width, height), color, (int)num20, Crit);
        statLife -= (int)num20;
        switch (cooldownCounter)
        {
        case -1:
        {
            immune = true;
            int num14 = 0;
            num14 = (pvp ? 8 : ((num20 == 1.0) ? (longInvince ? 40 : 20) : (longInvince ? 80 : 40)));
            immuneTime = num14;
            break;
        }
        case 0:
            if (num20 == 1.0)
            {
                hurtCooldowns[cooldownCounter] = (longInvince ? 40 : 20);
            }
            else
            {
                hurtCooldowns[cooldownCounter] = (longInvince ? 80 : 40);
            }
            break;
        case 1:
        case 3:
        case 4:
            if (num20 == 1.0)
            {
                hurtCooldowns[cooldownCounter] = (longInvince ? 40 : 20);
            }
            else
            {
                hurtCooldowns[cooldownCounter] = (longInvince ? 80 : 40);
            }
            break;
        }
        lifeRegenTime = 0f;
        int? sourceProjectileType = damageSource.SourceProjectileType;
        if (sourceProjectileType.HasValue && ProjectileID.Sets.DismountsPlayersOnHit.IndexInRange(sourceProjectileType.Value) && ProjectileID.Sets.DismountsPlayersOnHit[sourceProjectileType.Value])
        {
            mount.Dismount(this);
        }
        if (whoAmI == Main.myPlayer)
        {
            if (starCloakItem != null && !starCloakItem.IsAir && (cooldownCounter == -1 || cooldownCounter == 1))
            {
                Vector2 vector = default(Vector2);
                for (int num15 = 0; num15 < 3; num15++)
                {
                    float x = position.X + (float)Main.rand.Next(-400, 400);
                    float y = position.Y - (float)Main.rand.Next(500, 800);
                    ((Vector2)(ref vector))._002Ector(x, y);
                    float num16 = position.X + (float)(width / 2) - vector.X;
                    float num17 = position.Y + (float)(height / 2) - vector.Y;
                    num16 += (float)Main.rand.Next(-100, 101);
                    float num18 = (float)Math.Sqrt(num16 * num16 + num17 * num17);
                    num18 = 23f / num18;
                    num16 *= num18;
                    num17 *= num18;
                    int type = 726;
                    Item item = starCloakItem;
                    if (starCloakItem_starVeilOverrideItem != null)
                    {
                        item = starCloakItem_starVeilOverrideItem;
                        type = 725;
                    }
                    if (starCloakItem_beeCloakOverrideItem != null)
                    {
                        item = starCloakItem_beeCloakOverrideItem;
                        type = 724;
                    }
                    if (starCloakItem_manaCloakOverrideItem != null)
                    {
                        item = starCloakItem_manaCloakOverrideItem;
                        type = 723;
                    }
                    int num19 = 75;
                    if (Main.masterMode)
                    {
                        num19 *= 3;
                    }
                    else if (Main.expertMode)
                    {
                        num19 *= 2;
                    }
                    Projectile.NewProjectile(GetSource_Accessory_OnHurt(item, info.DamageSource), x, y, num16, num17, type, num19, 5f, whoAmI, 0f, position.Y);
                }
            }
            if (honeyCombItem != null && !honeyCombItem.IsAir)
            {
                int num21 = 1;
                if (Main.rand.Next(3) == 0)
                {
                    num21++;
                }
                if (Main.rand.Next(3) == 0)
                {
                    num21++;
                }
                if (strongBees && Main.rand.Next(3) == 0)
                {
                    num21++;
                }
                float num22 = 13f;
                if (strongBees)
                {
                    num22 = 18f;
                }
                if (Main.masterMode)
                {
                    num22 *= 2f;
                }
                else if (Main.expertMode)
                {
                    num22 *= 1.5f;
                }
                IEntitySource projectileSource_Accessory = GetSource_Accessory_OnHurt(honeyCombItem, info.DamageSource);
                for (int num23 = 0; num23 < num21; num23++)
                {
                    float speedX = (float)Main.rand.Next(-35, 36) * 0.02f;
                    float speedY = (float)Main.rand.Next(-35, 36) * 0.02f;
                    Projectile.NewProjectile(projectileSource_Accessory, position.X, position.Y, speedX, speedY, beeType(), beeDamage((int)num22), beeKB(0f), Main.myPlayer);
                }
                AddBuff(48, 300);
            }
        }
        StopVanityActions();
        if (info.Knockback != 0f && hitDirection != 0 && (!mount.Active || !mount.Cart))
        {
            velocity.X = info.Knockback * (float)hitDirection;
            velocity.Y = info.Knockback * -7f / 9f;
            fallStart = (int)(position.Y / 16f);
        }
        if (!info.SoundDisabled)
        {
            if (stoned)
            {
                SoundEngine.PlaySound(0, (int)position.X, (int)position.Y);
            }
            else if (mount.Active && mount.Type == 52)
            {
                SoundEngine.PlaySound(3, (int)position.X, (int)position.Y, 6);
            }
            else if ((wereWolf || forceWerewolf) && !hideWolf)
            {
                SoundEngine.PlaySound(3, (int)position.X, (int)position.Y, 6);
            }
            else if (frostArmor)
            {
                SoundEngine.PlaySound(in SoundID.Item27, position);
            }
            else if (boneArmor)
            {
                SoundEngine.PlaySound(3, (int)position.X, (int)position.Y, 2);
            }
            else if (Main.dontStarveWorld && !Main.remixWorld)
            {
                SoundStyle style = (Male ? SoundID.DSTMaleHurt : SoundID.DSTFemaleHurt);
                SoundEngine.PlaySound(in style, position);
            }
            else
            {
                SoundEngine.PlaySound(Male ? 1 : 20, position);
            }
        }
        eyeHelper.BlinkBecausePlayerGotHurt();
        if (statLife > 0)
        {
            if (!info.DustDisabled)
            {
                double num24 = num20 / (double)statLifeMax2 * 100.0;
                float num25 = 2 * hitDirection;
                float num26 = 0f;
                if (flag2)
                {
                    num24 *= 12.0;
                    num26 = 6f;
                }
                for (int num27 = 0; (double)num27 < num24; num27++)
                {
                    if (stoned)
                    {
                        Dust.NewDust(position, width, height, 1, num25 + (float)hitDirection * num26 * Main.rand.NextFloat(), -2f);
                    }
                    else if (frostArmor)
                    {
                        int num28 = Dust.NewDust(position, width, height, 135, num25 + (float)hitDirection * num26 * Main.rand.NextFloat(), -2f);
                        Main.dust[num28].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                    }
                    else if (boneArmor)
                    {
                        int num29 = Dust.NewDust(position, width, height, 26, num25 + (float)hitDirection * num26 * Main.rand.NextFloat(), -2f);
                        Main.dust[num29].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                    }
                    else
                    {
                        Dust.NewDust(position, width, height, 5, num25 + (float)hitDirection * num26 * Main.rand.NextFloat(), -2f);
                    }
                }
            }
            PlayerLoader.PostHurt(this, info);
        }
        else
        {
            statLife = 0;
            if (whoAmI == Main.myPlayer)
            {
                KillMe(damageSource, num20, hitDirection, pvp);
            }
        }
    }
References Terraria.Mount.Active, Terraria.Player.AddBuff(), Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.ArmorSetDye(), Terraria.Player.beeDamage(), Terraria.Player.beeKB(), Terraria.Player.beeType(), Terraria.GameContent.PlayerEyeHelper.BlinkBecausePlayerGotHurt(), Terraria.Player.boneArmor, Terraria.Mount.Cart, Terraria.CombatText.DamagedFriendly, Terraria.Mount.Dismount(), Terraria.ID.ProjectileID.Sets.DismountsPlayersOnHit, Terraria.Main.dontStarveWorld, Terraria.ID.SoundID.DSTFemaleHurt, Terraria.Main.dust, Terraria.Main.expertMode, Terraria.Player.eyeHelper, Terraria.Player.fallStart, Terraria.Player.forceWerewolf, Terraria.Player.frostArmor, Terraria.Player.GetSource_Accessory_OnHurt(), Terraria.Entity.height, Terraria.Player.hideWolf, Terraria.Player.honeyCombItem, Terraria.Player.hurtCooldowns, Terraria.Player.immune, Terraria.Player.immuneTime, Terraria.Item.IsAir, Terraria.ID.SoundID.Item27, Terraria.Player.KillMe(), Terraria.Player.lifeRegenTime, Terraria.Player.longInvince, Terraria.Player.Male, Terraria.Main.masterMode, Terraria.Player.mount, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Projectile.NewProjectile(), Terraria.CombatText.NewText(), Terraria.ModLoader.PlayerLoader.OnHurt(), Terraria.Player.OnHurt_Part1(), Terraria.Player.OnHurt_Part2(), Terraria.Player.OnHurt_Part3(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.ModLoader.PlayerLoader.PostHurt(), Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendPlayerHurt(), Terraria.Player.starCloakItem, Terraria.Player.starCloakItem_beeCloakOverrideItem, Terraria.Player.starCloakItem_manaCloakOverrideItem, Terraria.Player.starCloakItem_starVeilOverrideItem, Terraria.Player.statLife, Terraria.Player.statLifeMax2, Terraria.Player.stoned, Terraria.Player.StopVanityActions(), Terraria.Player.strongBees, Terraria.Mount.Type, Terraria.Player.wereWolf, Terraria.Entity.whoAmI, and Terraria.Entity.width.