TModLoader: Terraria.Player.FindSpawn
FindSpawn()
void Terraria.Player.FindSpawn () inline
Definition at line 55276 of file Player.cs.
    {
        for (int i = 0; i < 200; i++)
        {
            if (spN[i] == null)
            {
                SpawnX = -1;
                SpawnY = -1;
                break;
            }
            if (spN[i] == Main.worldName && spI[i] == Main.worldID)
            {
                SpawnX = spX[i];
                SpawnY = spY[i];
                break;
            }
        }
    }
References Terraria.Player.SpawnX, Terraria.Player.SpawnY, Terraria.Player.spI, Terraria.Player.spN, Terraria.Player.spX, Terraria.Player.spY, Terraria.Main.worldID, and Terraria.Main.worldName.
Referenced by Terraria.Player.ChangeSpawn(), Terraria.Player.Spawn(), Terraria.Player.TileInteractionsUse(), and Terraria.Player.TryFindingShimmerFreeSpot().