TModLoader: Terraria.Player.GetPointOnSwungItemPath
GetPointOnSwungItemPath()
void Terraria.Player.GetPointOnSwungItemPath (float spriteWidth, float spriteHeight, float normalizedPointOnPath, float itemScale, out Vector2 location, out Vector2 outwardDirection) inline private
    {
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        float num = (float)Math.Sqrt(spriteWidth * spriteWidth + spriteHeight * spriteHeight);
        float num2 = (float)(direction == 1).ToInt() * ((float)Math.PI / 2f);
        if (gravDir == -1f)
        {
            num2 += (float)Math.PI / 2f * (float)direction;
        }
        outwardDirection = itemRotation.ToRotationVector2().RotatedBy(3.926991f + num2);
        location = RotatedRelativePoint(itemLocation + outwardDirection * num * normalizedPointOnPath * itemScale);
    }
References Terraria.Entity.direction, Terraria.Player.gravDir, Terraria.Player.itemLocation, Terraria.Player.itemRotation, and Terraria.Player.RotatedRelativePoint().
Referenced by Terraria.Player.ItemCheck_EmitUseVisuals(), and Terraria.Player.ProcessHitAgainstNPC().