TModLoader: Terraria.Player.TakeUnityPotion
TakeUnityPotion()
void Terraria.Player.TakeUnityPotion () inline
    {
        for (int i = 0; i < 58; i++)
        {
            if (inventory[i].type == 2997 && inventory[i].stack > 0)
            {
                if (ItemLoader.ConsumeItem(inventory[i], this))
                {
                    inventory[i].stack--;
                }
                if (inventory[i].stack <= 0)
                {
                    inventory[i].SetDefaults();
                }
                return;
            }
        }
        if (!useVoidBag())
        {
            return;
        }
        for (int j = 0; j < 40; j++)
        {
            if (bank4.item[j].type == 2997 && bank4.item[j].stack > 0)
            {
                if (ItemLoader.ConsumeItem(bank4.item[j], this))
                {
                    bank4.item[j].stack--;
                }
                if (bank4.item[j].stack <= 0)
                {
                    bank4.item[j].SetDefaults();
                }
                break;
            }
        }
    }
References Terraria.Player.bank4, Terraria.ModLoader.ItemLoader.ConsumeItem(), Terraria.Player.inventory, Terraria.Chest.item, Terraria.Item.SetDefaults(), Terraria.Item.stack, Terraria.Item.type, and Terraria.Player.useVoidBag().
Referenced by Terraria.Main.DrawMap().