TModLoader: Terraria.Player.UpdatePet
UpdatePet()
void Terraria.Player.UpdatePet (int i) inline
Definition at line 15644 of file Player.cs.
    {
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        if (i == Main.myPlayer && miscEquips[0].buffType >= 1 && miscEquips[0].stack >= 1)
        {
            int num = miscEquips[0].buffType;
            if ((Main.vanityPet[num] || Main.lightPet[num]) && !hideMisc[0] && (miscEquips[0].type != 603 || Main.runningCollectorsEdition) && FindBuffIndex(num) == -1)
            {
                AddBuff(num, 3600);
                SoundEngine.PlaySound(miscEquips[0].UseSound, position);
            }
        }
    }
References Terraria.Player.AddBuff(), Terraria.Item.buffType, Terraria.Player.FindBuffIndex(), Terraria.Player.hideMisc, Terraria.Main.lightPet, Terraria.Player.miscEquips, Terraria.Main.myPlayer, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.runningCollectorsEdition, Terraria.Item.stack, Terraria.Item.type, and Terraria.Main.vanityPet.
Referenced by Terraria.Player.Update().