TModLoader: Terraria.Player.NinjaDodge
NinjaDodge()
void Terraria.Player.NinjaDodge () inline
Definition at line 36862 of file Player.cs.
    {
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_0230: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_0277: Unknown result type (might be due to invalid IL or missing references)
        //IL_027d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0309: Unknown result type (might be due to invalid IL or missing references)
        //IL_0313: Unknown result type (might be due to invalid IL or missing references)
        //IL_0318: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_035a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0360: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0436: Unknown result type (might be due to invalid IL or missing references)
        //IL_043d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0443: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04de: Unknown result type (might be due to invalid IL or missing references)
        //IL_0519: Unknown result type (might be due to invalid IL or missing references)
        //IL_0520: Unknown result type (might be due to invalid IL or missing references)
        //IL_0526: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c1: Unknown result type (might be due to invalid IL or missing references)
        SetImmuneTimeForAllTypes(longInvince ? 120 : 80);
        for (int i = 0; i < 100; i++)
        {
            int num = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 31, 0f, 0f, 100, default(Color), 2f);
            Main.dust[num].position.X += Main.rand.Next(-20, 21);
            Main.dust[num].position.Y += Main.rand.Next(-20, 21);
            Dust obj = Main.dust[num];
            obj.velocity *= 0.4f;
            Main.dust[num].scale *= 1f + (float)Main.rand.Next(40) * 0.01f;
            Main.dust[num].shader = GameShaders.Armor.GetSecondaryShader(cWaist, this);
            if (Main.rand.Next(2) == 0)
            {
                Main.dust[num].scale *= 1f + (float)Main.rand.Next(40) * 0.01f;
                Main.dust[num].noGravity = true;
            }
        }
        int num2 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
        Main.gore[num2].scale = 1.5f;
        Main.gore[num2].velocity.X = (float)Main.rand.Next(-50, 51) * 0.01f;
        Main.gore[num2].velocity.Y = (float)Main.rand.Next(-50, 51) * 0.01f;
        Gore obj2 = Main.gore[num2];
        obj2.velocity *= 0.4f;
        num2 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
        Main.gore[num2].scale = 1.5f;
        Main.gore[num2].velocity.X = 1.5f + (float)Main.rand.Next(-50, 51) * 0.01f;
        Main.gore[num2].velocity.Y = 1.5f + (float)Main.rand.Next(-50, 51) * 0.01f;
        Gore obj3 = Main.gore[num2];
        obj3.velocity *= 0.4f;
        num2 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
        Main.gore[num2].scale = 1.5f;
        Main.gore[num2].velocity.X = -1.5f - (float)Main.rand.Next(-50, 51) * 0.01f;
        Main.gore[num2].velocity.Y = 1.5f + (float)Main.rand.Next(-50, 51) * 0.01f;
        Gore obj4 = Main.gore[num2];
        obj4.velocity *= 0.4f;
        num2 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
        Main.gore[num2].scale = 1.5f;
        Main.gore[num2].velocity.X = 1.5f + (float)Main.rand.Next(-50, 51) * 0.01f;
        Main.gore[num2].velocity.Y = -1.5f - (float)Main.rand.Next(-50, 51) * 0.01f;
        Gore obj5 = Main.gore[num2];
        obj5.velocity *= 0.4f;
        num2 = Gore.NewGore(new Vector2(position.X + (float)(width / 2) - 24f, position.Y + (float)(height / 2) - 24f), default(Vector2), Main.rand.Next(61, 64));
        Main.gore[num2].scale = 1.5f;
        Main.gore[num2].velocity.X = -1.5f - (float)Main.rand.Next(-50, 51) * 0.01f;
        Main.gore[num2].velocity.Y = -1.5f - (float)Main.rand.Next(-50, 51) * 0.01f;
        Gore obj6 = Main.gore[num2];
        obj6.velocity *= 0.4f;
        if (whoAmI == Main.myPlayer)
        {
            NetMessage.SendData(62, -1, -1, null, whoAmI, 1f);
        }
    }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.cWaist, Terraria.Main.dust, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.Main.gore, Terraria.Entity.height, Terraria.Player.longInvince, Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.position, Terraria.Entity.position, Terraria.Main.rand, Terraria.Dust.scale, Terraria.Gore.scale, Terraria.NetMessage.SendData(), Terraria.Player.SetImmuneTimeForAllTypes(), Terraria.Dust.shader, Terraria.Gore.velocity, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Player.Hurt().