TModLoader: Terraria.Player.ItemCheck_Shoot
ItemCheck_Shoot()
void Terraria.Player.ItemCheck_Shoot (int i, Item sItem, int weaponDamage) inline private
    {
        //IL_0297: Unknown result type (might be due to invalid IL or missing references)
        //IL_029e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02da: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0326: Unknown result type (might be due to invalid IL or missing references)
        //IL_0328: Unknown result type (might be due to invalid IL or missing references)
        //IL_033b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0311: Unknown result type (might be due to invalid IL or missing references)
        //IL_031f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0324: Unknown result type (might be due to invalid IL or missing references)
        //IL_0425: Unknown result type (might be due to invalid IL or missing references)
        //IL_0427: Unknown result type (might be due to invalid IL or missing references)
        //IL_0429: Unknown result type (might be due to invalid IL or missing references)
        //IL_042b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0456: Unknown result type (might be due to invalid IL or missing references)
        //IL_0458: Unknown result type (might be due to invalid IL or missing references)
        //IL_045a: Unknown result type (might be due to invalid IL or missing references)
        //IL_045f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0474: Unknown result type (might be due to invalid IL or missing references)
        //IL_047a: Unknown result type (might be due to invalid IL or missing references)
        //IL_047c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0486: Unknown result type (might be due to invalid IL or missing references)
        //IL_048b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0490: Unknown result type (might be due to invalid IL or missing references)
        //IL_043e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0440: Unknown result type (might be due to invalid IL or missing references)
        //IL_0442: Unknown result type (might be due to invalid IL or missing references)
        //IL_0447: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0610: Unknown result type (might be due to invalid IL or missing references)
        //IL_05da: Unknown result type (might be due to invalid IL or missing references)
        //IL_05dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_074e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0755: Unknown result type (might be due to invalid IL or missing references)
        //IL_075b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0765: Unknown result type (might be due to invalid IL or missing references)
        //IL_076a: Unknown result type (might be due to invalid IL or missing references)
        //IL_079d: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0778: Unknown result type (might be due to invalid IL or missing references)
        //IL_077e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0788: Unknown result type (might be due to invalid IL or missing references)
        //IL_078d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0792: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0808: Unknown result type (might be due to invalid IL or missing references)
        //IL_0813: Unknown result type (might be due to invalid IL or missing references)
        //IL_0818: Unknown result type (might be due to invalid IL or missing references)
        //IL_0822: Unknown result type (might be due to invalid IL or missing references)
        //IL_0828: Unknown result type (might be due to invalid IL or missing references)
        //IL_082a: Unknown result type (might be due to invalid IL or missing references)
        //IL_082f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0834: Unknown result type (might be due to invalid IL or missing references)
        //IL_0836: Unknown result type (might be due to invalid IL or missing references)
        //IL_083a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0840: Unknown result type (might be due to invalid IL or missing references)
        //IL_084a: Unknown result type (might be due to invalid IL or missing references)
        //IL_084f: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07da: Unknown result type (might be due to invalid IL or missing references)
        //IL_07dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_089e: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_085d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0863: Unknown result type (might be due to invalid IL or missing references)
        //IL_086d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0872: Unknown result type (might be due to invalid IL or missing references)
        //IL_0877: Unknown result type (might be due to invalid IL or missing references)
        //IL_091a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0923: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c31: Unknown result type (might be due to invalid IL or missing references)
        //IL_0966: Unknown result type (might be due to invalid IL or missing references)
        //IL_0986: Unknown result type (might be due to invalid IL or missing references)
        //IL_099a: Unknown result type (might be due to invalid IL or missing references)
        //IL_09aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a70: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a80: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d53: Unknown result type (might be due to invalid IL or missing references)
        //IL_12bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_12c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1330: Unknown result type (might be due to invalid IL or missing references)
        //IL_1337: Unknown result type (might be due to invalid IL or missing references)
        //IL_10d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_10fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_114c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1167: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1404: Unknown result type (might be due to invalid IL or missing references)
        //IL_1407: Unknown result type (might be due to invalid IL or missing references)
        //IL_140c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1411: Unknown result type (might be due to invalid IL or missing references)
        //IL_1226: Unknown result type (might be due to invalid IL or missing references)
        //IL_122d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1000: Unknown result type (might be due to invalid IL or missing references)
        //IL_1007: Unknown result type (might be due to invalid IL or missing references)
        //IL_1425: Unknown result type (might be due to invalid IL or missing references)
        //IL_16a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_16a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_16ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_1739: Unknown result type (might be due to invalid IL or missing references)
        //IL_173d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1742: Unknown result type (might be due to invalid IL or missing references)
        //IL_1744: Unknown result type (might be due to invalid IL or missing references)
        //IL_174d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1758: Unknown result type (might be due to invalid IL or missing references)
        //IL_175f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1770: Unknown result type (might be due to invalid IL or missing references)
        //IL_1777: Unknown result type (might be due to invalid IL or missing references)
        //IL_14f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_14fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1500: Unknown result type (might be due to invalid IL or missing references)
        //IL_179e: Unknown result type (might be due to invalid IL or missing references)
        //IL_17a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_17ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_17b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_17bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_17bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_17c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_17c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_17c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1544: Unknown result type (might be due to invalid IL or missing references)
        //IL_154c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1551: Unknown result type (might be due to invalid IL or missing references)
        //IL_1532: Unknown result type (might be due to invalid IL or missing references)
        //IL_1534: Unknown result type (might be due to invalid IL or missing references)
        //IL_1536: Unknown result type (might be due to invalid IL or missing references)
        //IL_153b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1458: Unknown result type (might be due to invalid IL or missing references)
        //IL_145f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1444: Unknown result type (might be due to invalid IL or missing references)
        //IL_144b: Unknown result type (might be due to invalid IL or missing references)
        //IL_17e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_17de: Unknown result type (might be due to invalid IL or missing references)
        //IL_1488: Unknown result type (might be due to invalid IL or missing references)
        //IL_148f: Unknown result type (might be due to invalid IL or missing references)
        //IL_19fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a05: Unknown result type (might be due to invalid IL or missing references)
        //IL_1971: Unknown result type (might be due to invalid IL or missing references)
        //IL_1978: Unknown result type (might be due to invalid IL or missing references)
        //IL_15bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_15cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_183d: Unknown result type (might be due to invalid IL or missing references)
        //IL_185c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1862: Unknown result type (might be due to invalid IL or missing references)
        //IL_1864: Unknown result type (might be due to invalid IL or missing references)
        //IL_186b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1870: Unknown result type (might be due to invalid IL or missing references)
        //IL_1874: Unknown result type (might be due to invalid IL or missing references)
        //IL_187b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1882: Unknown result type (might be due to invalid IL or missing references)
        //IL_1889: Unknown result type (might be due to invalid IL or missing references)
        //IL_1aba: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ad3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bb4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bbc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c25: Unknown result type (might be due to invalid IL or missing references)
        //IL_20fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_2100: Unknown result type (might be due to invalid IL or missing references)
        //IL_2105: Unknown result type (might be due to invalid IL or missing references)
        //IL_2107: Unknown result type (might be due to invalid IL or missing references)
        //IL_210c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2110: Unknown result type (might be due to invalid IL or missing references)
        //IL_2112: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d91: Unknown result type (might be due to invalid IL or missing references)
        //IL_1da8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1db0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dfe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c54: Unknown result type (might be due to invalid IL or missing references)
        //IL_2140: Unknown result type (might be due to invalid IL or missing references)
        //IL_2151: Unknown result type (might be due to invalid IL or missing references)
        //IL_2156: Unknown result type (might be due to invalid IL or missing references)
        //IL_215b: Unknown result type (might be due to invalid IL or missing references)
        //IL_215d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2169: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fa8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fbf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_2015: Unknown result type (might be due to invalid IL or missing references)
        //IL_2030: Unknown result type (might be due to invalid IL or missing references)
        //IL_203c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_22c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_22c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_22ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_22d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_22d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_22d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_22d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_217c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cdf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ce6: Unknown result type (might be due to invalid IL or missing references)
        //IL_23cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_23d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2095: Unknown result type (might be due to invalid IL or missing references)
        //IL_209f: Unknown result type (might be due to invalid IL or missing references)
        //IL_20a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_20a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_20af: Unknown result type (might be due to invalid IL or missing references)
        //IL_20b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_20bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ed3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1eda: Unknown result type (might be due to invalid IL or missing references)
        //IL_243d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2444: Unknown result type (might be due to invalid IL or missing references)
        //IL_2303: Unknown result type (might be due to invalid IL or missing references)
        //IL_230d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2313: Unknown result type (might be due to invalid IL or missing references)
        //IL_2315: Unknown result type (might be due to invalid IL or missing references)
        //IL_231a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2197: Unknown result type (might be due to invalid IL or missing references)
        //IL_21ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_21bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_21c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_21d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_21d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_21db: Unknown result type (might be due to invalid IL or missing references)
        //IL_21e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_21e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_24b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_24bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_232d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2334: Unknown result type (might be due to invalid IL or missing references)
        //IL_233c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2343: Unknown result type (might be due to invalid IL or missing references)
        //IL_2320: Unknown result type (might be due to invalid IL or missing references)
        //IL_2322: Unknown result type (might be due to invalid IL or missing references)
        //IL_2324: Unknown result type (might be due to invalid IL or missing references)
        //IL_2329: Unknown result type (might be due to invalid IL or missing references)
        //IL_2200: Unknown result type (might be due to invalid IL or missing references)
        //IL_252f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2536: Unknown result type (might be due to invalid IL or missing references)
        //IL_2221: Unknown result type (might be due to invalid IL or missing references)
        //IL_2224: Unknown result type (might be due to invalid IL or missing references)
        //IL_2229: Unknown result type (might be due to invalid IL or missing references)
        //IL_222b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2234: Unknown result type (might be due to invalid IL or missing references)
        //IL_225d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2264: Unknown result type (might be due to invalid IL or missing references)
        //IL_2575: Unknown result type (might be due to invalid IL or missing references)
        //IL_257c: Unknown result type (might be due to invalid IL or missing references)
        //IL_27c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_27db: Unknown result type (might be due to invalid IL or missing references)
        //IL_27e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_27e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_27e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_2922: Unknown result type (might be due to invalid IL or missing references)
        //IL_2929: Unknown result type (might be due to invalid IL or missing references)
        //IL_292e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2930: Unknown result type (might be due to invalid IL or missing references)
        //IL_2934: Unknown result type (might be due to invalid IL or missing references)
        //IL_2936: Unknown result type (might be due to invalid IL or missing references)
        //IL_2938: Unknown result type (might be due to invalid IL or missing references)
        //IL_2824: Unknown result type (might be due to invalid IL or missing references)
        //IL_283f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2844: Unknown result type (might be due to invalid IL or missing references)
        //IL_2849: Unknown result type (might be due to invalid IL or missing references)
        //IL_284b: Unknown result type (might be due to invalid IL or missing references)
        //IL_284d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2852: Unknown result type (might be due to invalid IL or missing references)
        //IL_2859: Unknown result type (might be due to invalid IL or missing references)
        //IL_2860: Unknown result type (might be due to invalid IL or missing references)
        //IL_25db: Unknown result type (might be due to invalid IL or missing references)
        //IL_25e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_25e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_297d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2987: Unknown result type (might be due to invalid IL or missing references)
        //IL_298d: Unknown result type (might be due to invalid IL or missing references)
        //IL_298f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2994: Unknown result type (might be due to invalid IL or missing references)
        //IL_28bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_28c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_28c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_28d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ba6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bad: Unknown result type (might be due to invalid IL or missing references)
        //IL_29a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_29a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_29aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_29ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_29ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_29b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_29b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_29b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_29b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_29be: Unknown result type (might be due to invalid IL or missing references)
        //IL_29c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_29c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_29cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_29d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_29d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_29df: Unknown result type (might be due to invalid IL or missing references)
        //IL_29e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_29e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_29ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_29f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_29f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_29fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a09: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2998: Unknown result type (might be due to invalid IL or missing references)
        //IL_299a: Unknown result type (might be due to invalid IL or missing references)
        //IL_299c: Unknown result type (might be due to invalid IL or missing references)
        //IL_29a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_25f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_25fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_2614: Unknown result type (might be due to invalid IL or missing references)
        //IL_2619: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ce3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ce8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cf2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d03: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d08: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d10: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d12: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d31: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d36: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d38: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d41: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d46: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d55: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d65: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d73: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b53: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a51: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a54: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a59: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a27: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a29: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a36: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a40: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a45: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_262a: Unknown result type (might be due to invalid IL or missing references)
        //IL_263b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2642: Unknown result type (might be due to invalid IL or missing references)
        //IL_2db7: Unknown result type (might be due to invalid IL or missing references)
        //IL_2dbc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bef: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bf1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bf3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bf8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c13: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c15: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c24: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c33: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c38: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c41: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c48: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c58: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c97: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_266d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f34: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e02: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e05: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2de5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2dec: Unknown result type (might be due to invalid IL or missing references)
        //IL_2df6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2dfb: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e00: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ac3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ac5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a88: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aa4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aa6: Unknown result type (might be due to invalid IL or missing references)
        //IL_28b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_28b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_26b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_316c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3172: Unknown result type (might be due to invalid IL or missing references)
        //IL_3176: Unknown result type (might be due to invalid IL or missing references)
        //IL_317c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f80: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f85: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f60: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f67: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f71: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f76: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e72: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e77: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e79: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e13: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e24: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e29: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2683: Unknown result type (might be due to invalid IL or missing references)
        //IL_319c: Unknown result type (might be due to invalid IL or missing references)
        //IL_31a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_31a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_31ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e95: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e87: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e93: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e52: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e55: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e61: Unknown result type (might be due to invalid IL or missing references)
        //IL_31cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_31d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_31d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_31dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ecb: Unknown result type (might be due to invalid IL or missing references)
        //IL_2eda: Unknown result type (might be due to invalid IL or missing references)
        //IL_2edf: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ee3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2eea: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ef1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ef8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f05: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_26a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_30a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_30ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_30b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_30c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_30c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fcc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2748: Unknown result type (might be due to invalid IL or missing references)
        //IL_2755: Unknown result type (might be due to invalid IL or missing references)
        //IL_2778: Unknown result type (might be due to invalid IL or missing references)
        //IL_302a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3034: Unknown result type (might be due to invalid IL or missing references)
        //IL_3039: Unknown result type (might be due to invalid IL or missing references)
        //IL_303b: Unknown result type (might be due to invalid IL or missing references)
        //IL_303d: Unknown result type (might be due to invalid IL or missing references)
        //IL_3041: Unknown result type (might be due to invalid IL or missing references)
        //IL_3046: Unknown result type (might be due to invalid IL or missing references)
        //IL_304b: Unknown result type (might be due to invalid IL or missing references)
        //IL_304d: Unknown result type (might be due to invalid IL or missing references)
        //IL_304f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3054: Unknown result type (might be due to invalid IL or missing references)
        //IL_3059: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fe6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ff5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ffa: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ffd: Unknown result type (might be due to invalid IL or missing references)
        //IL_3002: Unknown result type (might be due to invalid IL or missing references)
        //IL_3004: Unknown result type (might be due to invalid IL or missing references)
        //IL_3009: Unknown result type (might be due to invalid IL or missing references)
        //IL_3455: Unknown result type (might be due to invalid IL or missing references)
        //IL_345c: Unknown result type (might be due to invalid IL or missing references)
        //IL_30cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_30cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_30d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_30d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_30d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_30df: Unknown result type (might be due to invalid IL or missing references)
        //IL_30e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_30e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_30ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_30fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_30fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_3102: Unknown result type (might be due to invalid IL or missing references)
        //IL_3104: Unknown result type (might be due to invalid IL or missing references)
        //IL_3106: Unknown result type (might be due to invalid IL or missing references)
        //IL_3108: Unknown result type (might be due to invalid IL or missing references)
        //IL_310d: Unknown result type (might be due to invalid IL or missing references)
        //IL_312c: Unknown result type (might be due to invalid IL or missing references)
        //IL_312e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3380: Unknown result type (might be due to invalid IL or missing references)
        //IL_3389: Unknown result type (might be due to invalid IL or missing references)
        //IL_34e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_34eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_32a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_32ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_3814: Unknown result type (might be due to invalid IL or missing references)
        //IL_381b: Unknown result type (might be due to invalid IL or missing references)
        //IL_35ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_35f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b15: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3bb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_3bb7: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c41: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a57: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3966: Unknown result type (might be due to invalid IL or missing references)
        //IL_396d: Unknown result type (might be due to invalid IL or missing references)
        //IL_3cc3: Unknown result type (might be due to invalid IL or missing references)
        //IL_3cca: Unknown result type (might be due to invalid IL or missing references)
        //IL_3e70: Unknown result type (might be due to invalid IL or missing references)
        //IL_3e87: Unknown result type (might be due to invalid IL or missing references)
        //IL_3e8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ed0: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ed7: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ede: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ee5: Unknown result type (might be due to invalid IL or missing references)
        //IL_3d4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3d53: Unknown result type (might be due to invalid IL or missing references)
        //IL_3dd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ddc: Unknown result type (might be due to invalid IL or missing references)
        //IL_4029: Unknown result type (might be due to invalid IL or missing references)
        //IL_402f: Unknown result type (might be due to invalid IL or missing references)
        //IL_4033: Unknown result type (might be due to invalid IL or missing references)
        //IL_4039: Unknown result type (might be due to invalid IL or missing references)
        //IL_406e: Unknown result type (might be due to invalid IL or missing references)
        //IL_4074: Unknown result type (might be due to invalid IL or missing references)
        //IL_4078: Unknown result type (might be due to invalid IL or missing references)
        //IL_407e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fcf: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_40ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_40b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_40b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_40bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_40ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_40f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_40fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_40ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_4104: Unknown result type (might be due to invalid IL or missing references)
        //IL_410e: Unknown result type (might be due to invalid IL or missing references)
        //IL_4110: Unknown result type (might be due to invalid IL or missing references)
        //IL_4118: Unknown result type (might be due to invalid IL or missing references)
        //IL_4125: Unknown result type (might be due to invalid IL or missing references)
        //IL_412b: Unknown result type (might be due to invalid IL or missing references)
        //IL_412d: Unknown result type (might be due to invalid IL or missing references)
        //IL_4132: Unknown result type (might be due to invalid IL or missing references)
        //IL_413e: Unknown result type (might be due to invalid IL or missing references)
        //IL_4140: Unknown result type (might be due to invalid IL or missing references)
        //IL_4167: Unknown result type (might be due to invalid IL or missing references)
        //IL_416d: Unknown result type (might be due to invalid IL or missing references)
        //IL_4171: Unknown result type (might be due to invalid IL or missing references)
        //IL_4177: Unknown result type (might be due to invalid IL or missing references)
        //IL_41bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_41c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_41c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_41cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_41ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_41f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_41f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_41ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_4253: Unknown result type (might be due to invalid IL or missing references)
        //IL_4259: Unknown result type (might be due to invalid IL or missing references)
        //IL_425d: Unknown result type (might be due to invalid IL or missing references)
        //IL_4263: Unknown result type (might be due to invalid IL or missing references)
        //IL_46e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_46e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_46ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_46f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_43a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_43ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_43da: Unknown result type (might be due to invalid IL or missing references)
        //IL_43e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_4412: Unknown result type (might be due to invalid IL or missing references)
        //IL_4419: Unknown result type (might be due to invalid IL or missing references)
        //IL_444a: Unknown result type (might be due to invalid IL or missing references)
        //IL_4451: Unknown result type (might be due to invalid IL or missing references)
        //IL_4531: Unknown result type (might be due to invalid IL or missing references)
        //IL_4538: Unknown result type (might be due to invalid IL or missing references)
        //IL_4569: Unknown result type (might be due to invalid IL or missing references)
        //IL_4570: Unknown result type (might be due to invalid IL or missing references)
        //IL_4891: Unknown result type (might be due to invalid IL or missing references)
        //IL_4897: Unknown result type (might be due to invalid IL or missing references)
        //IL_489c: Unknown result type (might be due to invalid IL or missing references)
        //IL_48a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_48a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_48ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_48f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_490b: Unknown result type (might be due to invalid IL or missing references)
        //IL_497a: Unknown result type (might be due to invalid IL or missing references)
        //IL_498b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4c21: Unknown result type (might be due to invalid IL or missing references)
        //IL_4c28: Unknown result type (might be due to invalid IL or missing references)
        //IL_4c2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_4c3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_4942: Unknown result type (might be due to invalid IL or missing references)
        //IL_4944: Unknown result type (might be due to invalid IL or missing references)
        //IL_494a: Unknown result type (might be due to invalid IL or missing references)
        //IL_494f: Unknown result type (might be due to invalid IL or missing references)
        //IL_499d: Unknown result type (might be due to invalid IL or missing references)
        //IL_49ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_4853: Unknown result type (might be due to invalid IL or missing references)
        //IL_485a: Unknown result type (might be due to invalid IL or missing references)
        //IL_4bb7: Unknown result type (might be due to invalid IL or missing references)
        //IL_4bbe: Unknown result type (might be due to invalid IL or missing references)
        //IL_496f: Unknown result type (might be due to invalid IL or missing references)
        //IL_4975: Unknown result type (might be due to invalid IL or missing references)
        //IL_4e25: Unknown result type (might be due to invalid IL or missing references)
        //IL_4e27: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cbe: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cd0: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cd7: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cdc: Unknown result type (might be due to invalid IL or missing references)
        //IL_4ce1: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cfd: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f36: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f41: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f46: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f52: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f57: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f61: Unknown result type (might be due to invalid IL or missing references)
        //IL_4eed: Unknown result type (might be due to invalid IL or missing references)
        //IL_4eef: Unknown result type (might be due to invalid IL or missing references)
        //IL_4e70: Unknown result type (might be due to invalid IL or missing references)
        //IL_4e7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4e80: Unknown result type (might be due to invalid IL or missing references)
        //IL_4eb4: Unknown result type (might be due to invalid IL or missing references)
        //IL_4eb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d33: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d38: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d97: Unknown result type (might be due to invalid IL or missing references)
        //IL_4da2: Unknown result type (might be due to invalid IL or missing references)
        //IL_4da7: Unknown result type (might be due to invalid IL or missing references)
        //IL_4dc4: Unknown result type (might be due to invalid IL or missing references)
        //IL_4dc6: Unknown result type (might be due to invalid IL or missing references)
        //IL_5021: Unknown result type (might be due to invalid IL or missing references)
        //IL_5026: Unknown result type (might be due to invalid IL or missing references)
        //IL_5030: Unknown result type (might be due to invalid IL or missing references)
        //IL_503b: Unknown result type (might be due to invalid IL or missing references)
        //IL_5040: Unknown result type (might be due to invalid IL or missing references)
        //IL_5046: Unknown result type (might be due to invalid IL or missing references)
        //IL_504a: Unknown result type (might be due to invalid IL or missing references)
        //IL_504c: Unknown result type (might be due to invalid IL or missing references)
        //IL_5052: Unknown result type (might be due to invalid IL or missing references)
        //IL_507e: Unknown result type (might be due to invalid IL or missing references)
        //IL_5089: Unknown result type (might be due to invalid IL or missing references)
        //IL_508e: Unknown result type (might be due to invalid IL or missing references)
        //IL_5094: Unknown result type (might be due to invalid IL or missing references)
        //IL_509a: Unknown result type (might be due to invalid IL or missing references)
        //IL_509f: Unknown result type (might be due to invalid IL or missing references)
        //IL_50a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_50a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_5060: Unknown result type (might be due to invalid IL or missing references)
        //IL_5062: Unknown result type (might be due to invalid IL or missing references)
        //IL_5068: Unknown result type (might be due to invalid IL or missing references)
        //IL_506d: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f92: Unknown result type (might be due to invalid IL or missing references)
        //IL_4f9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_4fa8: Unknown result type (might be due to invalid IL or missing references)
        //IL_4fad: Unknown result type (might be due to invalid IL or missing references)
        //IL_4fc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_4fc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_4fca: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d72: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d87: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_4d91: Unknown result type (might be due to invalid IL or missing references)
        //IL_4b3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_4b5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_4b66: Unknown result type (might be due to invalid IL or missing references)
        //IL_53cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_53d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_53f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_53f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_53fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_5183: Unknown result type (might be due to invalid IL or missing references)
        //IL_5187: Unknown result type (might be due to invalid IL or missing references)
        //IL_518d: Unknown result type (might be due to invalid IL or missing references)
        //IL_519b: Unknown result type (might be due to invalid IL or missing references)
        //IL_51a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_51a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_51ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_51b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_51fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_520c: Unknown result type (might be due to invalid IL or missing references)
        //IL_5212: Unknown result type (might be due to invalid IL or missing references)
        //IL_5214: Unknown result type (might be due to invalid IL or missing references)
        //IL_522f: Unknown result type (might be due to invalid IL or missing references)
        //IL_5234: Unknown result type (might be due to invalid IL or missing references)
        //IL_523c: Unknown result type (might be due to invalid IL or missing references)
        //IL_5243: Unknown result type (might be due to invalid IL or missing references)
        //IL_524a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5255: Unknown result type (might be due to invalid IL or missing references)
        //IL_50ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_50d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_50d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_50e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_50ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_50f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_5108: Unknown result type (might be due to invalid IL or missing references)
        //IL_510e: Unknown result type (might be due to invalid IL or missing references)
        //IL_5110: Unknown result type (might be due to invalid IL or missing references)
        //IL_52ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_52af: Unknown result type (might be due to invalid IL or missing references)
        //IL_52b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_52c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_52c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_52cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_52d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_52da: Unknown result type (might be due to invalid IL or missing references)
        //IL_531a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5328: Unknown result type (might be due to invalid IL or missing references)
        //IL_532e: Unknown result type (might be due to invalid IL or missing references)
        //IL_5330: Unknown result type (might be due to invalid IL or missing references)
        //IL_534b: Unknown result type (might be due to invalid IL or missing references)
        //IL_5350: Unknown result type (might be due to invalid IL or missing references)
        //IL_5358: Unknown result type (might be due to invalid IL or missing references)
        //IL_535a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5365: Unknown result type (might be due to invalid IL or missing references)
        //IL_536a: Unknown result type (might be due to invalid IL or missing references)
        //IL_536f: Unknown result type (might be due to invalid IL or missing references)
        //IL_570a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5710: Unknown result type (might be due to invalid IL or missing references)
        //IL_5410: Unknown result type (might be due to invalid IL or missing references)
        //IL_5418: Unknown result type (might be due to invalid IL or missing references)
        //IL_5438: Unknown result type (might be due to invalid IL or missing references)
        //IL_543d: Unknown result type (might be due to invalid IL or missing references)
        //IL_5442: Unknown result type (might be due to invalid IL or missing references)
        //IL_5448: Unknown result type (might be due to invalid IL or missing references)
        //IL_544c: Unknown result type (might be due to invalid IL or missing references)
        //IL_5452: Unknown result type (might be due to invalid IL or missing references)
        //IL_5458: Unknown result type (might be due to invalid IL or missing references)
        //IL_545a: Unknown result type (might be due to invalid IL or missing references)
        //IL_545f: Unknown result type (might be due to invalid IL or missing references)
        //IL_5464: Unknown result type (might be due to invalid IL or missing references)
        //IL_546e: Unknown result type (might be due to invalid IL or missing references)
        //IL_5473: Unknown result type (might be due to invalid IL or missing references)
        //IL_54b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_54b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_54bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_54c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_54cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_54d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_54d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_54dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_54e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_54e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_54ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_54f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_54f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_54fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_5504: Unknown result type (might be due to invalid IL or missing references)
        //IL_550a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5515: Unknown result type (might be due to invalid IL or missing references)
        //IL_551a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5522: Unknown result type (might be due to invalid IL or missing references)
        //IL_5528: Unknown result type (might be due to invalid IL or missing references)
        //IL_5582: Unknown result type (might be due to invalid IL or missing references)
        //IL_5584: Unknown result type (might be due to invalid IL or missing references)
        //IL_558a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5590: Unknown result type (might be due to invalid IL or missing references)
        //IL_5595: Unknown result type (might be due to invalid IL or missing references)
        //IL_55ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_55c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_55c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_55d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_55db: Unknown result type (might be due to invalid IL or missing references)
        //IL_55e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_5602: Unknown result type (might be due to invalid IL or missing references)
        //IL_5604: Unknown result type (might be due to invalid IL or missing references)
        //IL_560a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5610: Unknown result type (might be due to invalid IL or missing references)
        //IL_5615: Unknown result type (might be due to invalid IL or missing references)
        //IL_5640: Unknown result type (might be due to invalid IL or missing references)
        //IL_5646: Unknown result type (might be due to invalid IL or missing references)
        //IL_5648: Unknown result type (might be due to invalid IL or missing references)
        //IL_5657: Unknown result type (might be due to invalid IL or missing references)
        //IL_5661: Unknown result type (might be due to invalid IL or missing references)
        //IL_5666: Unknown result type (might be due to invalid IL or missing references)
        //IL_56a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_56a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_56aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_56b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_56bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_56c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_5751: Unknown result type (might be due to invalid IL or missing references)
        //IL_5756: Unknown result type (might be due to invalid IL or missing references)
        //IL_575b: Unknown result type (might be due to invalid IL or missing references)
        //IL_5779: Unknown result type (might be due to invalid IL or missing references)
        //IL_577f: Unknown result type (might be due to invalid IL or missing references)
        //IL_5781: Unknown result type (might be due to invalid IL or missing references)
        //IL_5786: Unknown result type (might be due to invalid IL or missing references)
        //IL_578d: Unknown result type (might be due to invalid IL or missing references)
        //IL_579c: Unknown result type (might be due to invalid IL or missing references)
        //IL_57a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_57a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_57ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_57b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_57bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_57c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_57c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_57cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_590f: Unknown result type (might be due to invalid IL or missing references)
        //IL_5920: Unknown result type (might be due to invalid IL or missing references)
        //IL_594f: Unknown result type (might be due to invalid IL or missing references)
        //IL_5958: Unknown result type (might be due to invalid IL or missing references)
        //IL_5835: Unknown result type (might be due to invalid IL or missing references)
        //IL_584a: Unknown result type (might be due to invalid IL or missing references)
        //IL_584f: Unknown result type (might be due to invalid IL or missing references)
        //IL_5854: Unknown result type (might be due to invalid IL or missing references)
        //IL_57fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_5823: Unknown result type (might be due to invalid IL or missing references)
        //IL_5828: Unknown result type (might be due to invalid IL or missing references)
        //IL_582d: Unknown result type (might be due to invalid IL or missing references)
        //IL_59c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_59d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_5a45: Unknown result type (might be due to invalid IL or missing references)
        //IL_5a56: Unknown result type (might be due to invalid IL or missing references)
        //IL_588e: Unknown result type (might be due to invalid IL or missing references)
        //IL_5894: Unknown result type (might be due to invalid IL or missing references)
        //IL_589f: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ac5: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ad6: Unknown result type (might be due to invalid IL or missing references)
        //IL_5b09: Unknown result type (might be due to invalid IL or missing references)
        //IL_5b12: Unknown result type (might be due to invalid IL or missing references)
        //IL_5b81: Unknown result type (might be due to invalid IL or missing references)
        //IL_5b92: Unknown result type (might be due to invalid IL or missing references)
        //IL_5bc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_5bd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_5c44: Unknown result type (might be due to invalid IL or missing references)
        //IL_5c55: Unknown result type (might be due to invalid IL or missing references)
        //IL_5c88: Unknown result type (might be due to invalid IL or missing references)
        //IL_5c91: Unknown result type (might be due to invalid IL or missing references)
        //IL_5c9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_5cf9: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d08: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d13: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d18: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d24: Unknown result type (might be due to invalid IL or missing references)
        //IL_6060: Unknown result type (might be due to invalid IL or missing references)
        //IL_6067: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d77: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d91: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d96: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d65: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_60ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_60b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_5d9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dc3: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dc9: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dce: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dde: Unknown result type (might be due to invalid IL or missing references)
        //IL_5de4: Unknown result type (might be due to invalid IL or missing references)
        //IL_5dea: Unknown result type (might be due to invalid IL or missing references)
        //IL_5def: Unknown result type (might be due to invalid IL or missing references)
        //IL_60f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_60ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e85: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e90: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e95: Unknown result type (might be due to invalid IL or missing references)
        //IL_5e9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ea1: Unknown result type (might be due to invalid IL or missing references)
        //IL_61db: Unknown result type (might be due to invalid IL or missing references)
        //IL_61e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f18: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f29: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f34: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f55: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f57: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f62: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f67: Unknown result type (might be due to invalid IL or missing references)
        //IL_619e: Unknown result type (might be due to invalid IL or missing references)
        //IL_61a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f87: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f92: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f97: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ebe: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ec4: Unknown result type (might be due to invalid IL or missing references)
        //IL_5eca: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ecf: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ed5: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ee4: Unknown result type (might be due to invalid IL or missing references)
        //IL_5eea: Unknown result type (might be due to invalid IL or missing references)
        //IL_5eec: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ef1: Unknown result type (might be due to invalid IL or missing references)
        //IL_6392: Unknown result type (might be due to invalid IL or missing references)
        //IL_6399: Unknown result type (might be due to invalid IL or missing references)
        //IL_63a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_63b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_63b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ff8: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ffe: Unknown result type (might be due to invalid IL or missing references)
        //IL_5fc0: Unknown result type (might be due to invalid IL or missing references)
        //IL_5fe3: Unknown result type (might be due to invalid IL or missing references)
        //IL_5fe9: Unknown result type (might be due to invalid IL or missing references)
        //IL_5feb: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ff0: Unknown result type (might be due to invalid IL or missing references)
        //IL_63e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_63e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_63c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_63d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_63d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_63dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_627d: Unknown result type (might be due to invalid IL or missing references)
        //IL_628b: Unknown result type (might be due to invalid IL or missing references)
        //IL_62a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_62a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_62a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_62ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_62b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_62bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_62c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_62c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_62d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_649c: Unknown result type (might be due to invalid IL or missing references)
        //IL_64a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_644c: Unknown result type (might be due to invalid IL or missing references)
        //IL_6454: Unknown result type (might be due to invalid IL or missing references)
        //IL_66f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_66fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_6701: Unknown result type (might be due to invalid IL or missing references)
        //IL_6707: Unknown result type (might be due to invalid IL or missing references)
        //IL_670d: Unknown result type (might be due to invalid IL or missing references)
        //IL_6713: Unknown result type (might be due to invalid IL or missing references)
        //IL_6715: Unknown result type (might be due to invalid IL or missing references)
        //IL_671b: Unknown result type (might be due to invalid IL or missing references)
        //IL_672a: Unknown result type (might be due to invalid IL or missing references)
        //IL_672f: Unknown result type (might be due to invalid IL or missing references)
        //IL_6734: Unknown result type (might be due to invalid IL or missing references)
        //IL_67cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_67d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_675d: Unknown result type (might be due to invalid IL or missing references)
        //IL_6768: Unknown result type (might be due to invalid IL or missing references)
        //IL_6809: Unknown result type (might be due to invalid IL or missing references)
        //IL_6810: Unknown result type (might be due to invalid IL or missing references)
        //IL_6785: Unknown result type (might be due to invalid IL or missing references)
        //IL_6787: Unknown result type (might be due to invalid IL or missing references)
        //IL_6798: Unknown result type (might be due to invalid IL or missing references)
        //IL_6771: Unknown result type (might be due to invalid IL or missing references)
        //IL_6777: Unknown result type (might be due to invalid IL or missing references)
        //IL_6876: Unknown result type (might be due to invalid IL or missing references)
        //IL_687d: Unknown result type (might be due to invalid IL or missing references)
        //IL_6846: Unknown result type (might be due to invalid IL or missing references)
        //IL_684d: Unknown result type (might be due to invalid IL or missing references)
        //IL_673c: Unknown result type (might be due to invalid IL or missing references)
        //IL_6742: Unknown result type (might be due to invalid IL or missing references)
        //IL_674d: Unknown result type (might be due to invalid IL or missing references)
        //IL_6752: Unknown result type (might be due to invalid IL or missing references)
        //IL_6757: Unknown result type (might be due to invalid IL or missing references)
        if (!CombinedHooks.CanShoot(this, sItem))
        {
            return;
        }
        int projToShoot = sItem.shoot;
        float speed = sItem.shootSpeed;
        int damage = sItem.damage;
        if (sItem.melee && !ProjectileID.Sets.NoMeleeSpeedVelocityScaling[projToShoot])
        {
            speed /= inverseMeleeSpeed;
        }
        if (sItem.CountsAsClass(DamageClass.Throwing) && speed < 16f)
        {
            speed *= ThrownVelocity;
            if (speed > 16f)
            {
                speed = 16f;
            }
        }
        bool canShoot = false;
        int Damage = weaponDamage;
        float KnockBack = sItem.knockBack;
        int usedAmmoItemId = 0;
        if (sItem.useAmmo > 0)
        {
            PickAmmo(sItem, ref projToShoot, ref speed, ref canShoot, ref Damage, ref KnockBack, out usedAmmoItemId, ItemID.Sets.gunProj[sItem.type]);
        }
        else
        {
            canShoot = true;
        }
        if (ItemID.Sets.gunProj[sItem.type])
        {
            KnockBack = sItem.knockBack;
            Damage = weaponDamage;
            speed = sItem.shootSpeed;
        }
        if (sItem.IsACoin)
        {
            canShoot = false;
        }
        if (sItem.type == 1254 && projToShoot == 14)
        {
            projToShoot = 242;
        }
        if (sItem.type == 1255 && projToShoot == 14)
        {
            projToShoot = 242;
        }
        if (sItem.type == 1265 && projToShoot == 14)
        {
            projToShoot = 242;
        }
        if (sItem.type == 3542)
        {
            if (Main.rand.Next(100) < 20)
            {
                projToShoot++;
                Damage *= 3;
            }
            else
            {
                speed -= 1f;
            }
        }
        if (sItem.type == 1928)
        {
            Damage = (int)((float)Damage * 1f);
        }
        if (sItem.type == 3063)
        {
            Damage = (int)((float)Damage * 1.25f);
        }
        if (sItem.type == 1306)
        {
            Damage = (int)((double)Damage * 0.67);
        }
        if (sItem.type == 1227)
        {
            Damage = (int)((double)Damage * 0.7);
        }
        if (!canShoot)
        {
            return;
        }
        if (whoAmI != Main.myPlayer)
        {
            ApplyItemTime(sItem);
            return;
        }
        KnockBack = GetWeaponKnockback(sItem, KnockBack);
        IEntitySource projectileSource_Item_WithPotentialAmmo = GetProjectileSource_Item_WithPotentialAmmo(sItem, usedAmmoItemId);
        if (projToShoot == 228)
        {
            KnockBack = 0f;
        }
        if (projToShoot == 1 && sItem.type == 120)
        {
            projToShoot = 2;
        }
        if (sItem.type == 682)
        {
            projToShoot = 117;
        }
        if (sItem.type == 725)
        {
            projToShoot = 120;
        }
        if (sItem.type == 2796)
        {
            projToShoot = 442;
        }
        if (sItem.type == 2223)
        {
            projToShoot = 357;
        }
        if (sItem.type == 5117)
        {
            projToShoot = 968;
        }
        if (sItem.fishingPole > 0 && overrideFishingBobber > -1)
        {
            projToShoot = overrideFishingBobber;
        }
        ApplyItemTime(sItem);
        Vector2 pointPoisition = RotatedRelativePoint(MountedCenter);
        bool flag = true;
        _ = sItem.type;
        if (!sItem.ChangePlayerDirectionOnShoot)
        {
            flag = false;
        }
        Vector2 unitX = Vector2.UnitX;
        double radians = fullRotation;
        Vector2 val = default(Vector2);
        Vector2 val2 = unitX.RotatedBy(radians, val);
        Vector2 vector = Main.MouseWorld - pointPoisition;
        Vector2 v = itemRotation.ToRotationVector2() * (float)direction;
        if (sItem.type == 3852 && !ItemAnimationJustStarted)
        {
            vector = (v.ToRotation() + fullRotation).ToRotationVector2();
        }
        if (vector != Vector2.Zero)
        {
            ((Vector2)(ref vector)).Normalize();
        }
        float num = Vector2.Dot(val2, vector);
        if (flag)
        {
            if (num > 0f)
            {
                ChangeDir(1);
            }
            else
            {
                ChangeDir(-1);
            }
        }
        if (sItem.type == 3094 || sItem.type == 3378 || sItem.type == 3543)
        {
            pointPoisition.Y = base.position.Y + (float)(height / 3);
        }
        if (sItem.type == 5117)
        {
            pointPoisition.Y = base.position.Y + (float)(height / 3);
        }
        if (sItem.type == 517)
        {
            pointPoisition.X += (float)Main.rand.Next(-3, 4) * 3.5f;
            pointPoisition.Y += (float)Main.rand.Next(-3, 4) * 3.5f;
        }
        if (sItem.type == 2611)
        {
            Vector2 vector12 = vector;
            if (vector12 != Vector2.Zero)
            {
                ((Vector2)(ref vector12)).Normalize();
            }
            pointPoisition += vector12;
        }
        if (sItem.type == 3827)
        {
            Vector2 val3 = pointPoisition;
            Vector2 spinningpoint3 = vector.SafeNormalize(Vector2.Zero);
            double radians2 = (float)direction * (-(float)Math.PI / 2f);
            val = default(Vector2);
            pointPoisition = val3 + spinningpoint3.RotatedBy(radians2, val) * 24f;
        }
        if (projToShoot == 9)
        {
            ((Vector2)(ref pointPoisition))._002Ector(base.position.X + (float)width * 0.5f + (float)(Main.rand.Next(201) * -direction) + ((float)Main.mouseX + Main.screenPosition.X - base.position.X), MountedCenter.Y - 600f);
            KnockBack = 0f;
            Damage = (int)((float)Damage * 1.5f);
        }
        if (sItem.type == 986 || sItem.type == 281)
        {
            pointPoisition.X += 6 * direction;
            pointPoisition.Y -= 6f * gravDir;
        }
        if (sItem.type == 3007)
        {
            pointPoisition.X -= 4 * direction;
            pointPoisition.Y -= 2f * gravDir;
        }
        float num102 = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X;
        float num113 = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y;
        if (sItem.type == 3852 && !ItemAnimationJustStarted)
        {
            Vector2 val4 = vector;
            num102 = val4.X;
            num113 = val4.Y;
        }
        if (gravDir == -1f)
        {
            num113 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - pointPoisition.Y;
        }
        float num124 = (float)Math.Sqrt(num102 * num102 + num113 * num113);
        float num135 = num124;
        if ((float.IsNaN(num102) && float.IsNaN(num113)) || (num102 == 0f && num113 == 0f))
        {
            num102 = direction;
            num113 = 0f;
            num124 = speed;
        }
        else
        {
            num124 = speed / num124;
        }
        if (sItem.type == 1929 || sItem.type == 2270)
        {
            num102 += (float)Main.rand.Next(-50, 51) * 0.03f / num124;
            num113 += (float)Main.rand.Next(-50, 51) * 0.03f / num124;
        }
        num102 *= num124;
        num113 *= num124;
        if (projToShoot == 250)
        {
            for (int j = 0; j < 1000; j++)
            {
                if (Main.projectile[j].active && Main.projectile[j].owner == whoAmI && (Main.projectile[j].type == 250 || Main.projectile[j].type == 251))
                {
                    Main.projectile[j].Kill();
                }
            }
        }
        if (projToShoot == 12 && Collision.CanHitLine(base.Center, 0, 0, pointPoisition + new Vector2(num102, num113) * 4f, 0, 0))
        {
            pointPoisition += new Vector2(num102, num113) * 3f;
        }
        if (projToShoot == 728 && !Collision.CanHitLine(base.Center, 0, 0, pointPoisition + new Vector2(num102, num113) * 2f, 0, 0))
        {
            Vector2 vector33 = new Vector2(num102, num113) * 0.25f;
            pointPoisition = base.Center - vector33;
        }
        if (projToShoot == 85)
        {
            Vector2 val5 = pointPoisition;
            Vector2 spinningpoint4 = new Vector2(0f, -6f * (float)direction * Directions.Y);
            double radians3 = vector.ToRotation();
            val = default(Vector2);
            pointPoisition = val5 + Utils.RotatedBy(spinningpoint4, radians3, val);
            if (Collision.CanHitLine(pointPoisition, 0, 0, pointPoisition + new Vector2(num102, num113) * 5f, 0, 0))
            {
                pointPoisition += new Vector2(num102, num113) * 4f;
            }
        }
        if (projToShoot == 802 || projToShoot == 842)
        {
            Vector2 v2 = default(Vector2);
            ((Vector2)(ref v2))._002Ector(num102, num113);
            float num146 = (float)Math.PI / 4f;
            Vector2 spinningpoint5 = v2.SafeNormalize(Vector2.Zero);
            double radians4 = num146 * (Main.rand.NextFloat() - 0.5f);
            val = default(Vector2);
            Vector2 val6 = spinningpoint5.RotatedBy(radians4, val) * (((Vector2)(ref v2)).Length() - Main.rand.NextFloatDirection() * 0.7f);
            num102 = val6.X;
            num113 = val6.Y;
        }
        if (projToShoot == 17)
        {
            pointPoisition.X = (float)Main.mouseX + Main.screenPosition.X;
            pointPoisition.Y = (float)Main.mouseY + Main.screenPosition.Y;
            if (gravDir == -1f)
            {
                pointPoisition.Y = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY;
            }
            LimitPointToPlayerReachableArea(ref pointPoisition);
        }
        Vector2 velocity = default(Vector2);
        ((Vector2)(ref velocity))._002Ector(num102, num113);
        CombinedHooks.ModifyShootStats(this, sItem, ref pointPoisition, ref velocity, ref projToShoot, ref Damage, ref KnockBack);
        num102 = velocity.X;
        num113 = velocity.Y;
        if (sItem.useStyle == 5)
        {
            if (sItem.type == 3029)
            {
                Vector2 vector54 = default(Vector2);
                ((Vector2)(ref vector54))._002Ector(num102, num113);
                vector54.X = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X;
                vector54.Y = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y - 1000f;
                itemRotation = (float)Math.Atan2(vector54.Y * (float)direction, vector54.X * (float)direction);
                NetMessage.SendData(13, -1, -1, null, whoAmI);
                NetMessage.SendData(41, -1, -1, null, whoAmI);
            }
            else if (sItem.type == 4381)
            {
                Vector2 vector56 = default(Vector2);
                ((Vector2)(ref vector56))._002Ector(num102, num113);
                vector56.X = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X;
                vector56.Y = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y - 1000f;
                itemRotation = (float)Math.Atan2(vector56.Y * (float)direction, vector56.X * (float)direction);
                NetMessage.SendData(13, -1, -1, null, whoAmI);
                NetMessage.SendData(41, -1, -1, null, whoAmI);
            }
            else if (sItem.type == 3779)
            {
                itemRotation = 0f;
                NetMessage.SendData(13, -1, -1, null, whoAmI);
                NetMessage.SendData(41, -1, -1, null, whoAmI);
            }
            else
            {
                itemRotation = (float)Math.Atan2(num113 * (float)direction, num102 * (float)direction) - fullRotation;
                NetMessage.SendData(13, -1, -1, null, whoAmI);
                NetMessage.SendData(41, -1, -1, null, whoAmI);
            }
        }
        if (sItem.useStyle == 13)
        {
            itemRotation = (float)Math.Atan2(num113 * (float)direction, num102 * (float)direction) - fullRotation;
            NetMessage.SendData(13, -1, -1, null, whoAmI);
            NetMessage.SendData(41, -1, -1, null, whoAmI);
        }
        if (!CombinedHooks.Shoot(this, sItem, (EntitySource_ItemUse_WithAmmo)projectileSource_Item_WithPotentialAmmo, pointPoisition, velocity, projToShoot, Damage, KnockBack))
        {
            return;
        }
        if (projToShoot == 76)
        {
            projToShoot += Main.rand.Next(3);
            float num156 = (float)Main.screenHeight / Main.GameViewMatrix.Zoom.Y;
            num135 /= num156 / 2f;
            if (num135 > 1f)
            {
                num135 = 1f;
            }
            float num167 = num102 + (float)Main.rand.Next(-40, 41) * 0.01f;
            float num178 = num113 + (float)Main.rand.Next(-40, 41) * 0.01f;
            num167 *= num135 + 0.25f;
            num178 *= num135 + 0.25f;
            int num2 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num167, num178, projToShoot, Damage, KnockBack, i);
            Main.projectile[num2].ai[1] = 1f;
            num135 = num135 * 2f - 1f;
            if (num135 < -1f)
            {
                num135 = -1f;
            }
            if (num135 > 1f)
            {
                num135 = 1f;
            }
            num135 = (float)Math.Round(num135 * (float)musicNotes);
            num135 /= (float)musicNotes;
            Main.projectile[num2].ai[0] = num135;
            NetMessage.SendData(27, -1, -1, null, num2);
        }
        else if (sItem.type == 3029)
        {
            int num12 = 3;
            if (projToShoot == 91 || projToShoot == 4 || projToShoot == 5 || projToShoot == 41)
            {
                if (Main.rand.Next(3) == 0)
                {
                    num12--;
                }
            }
            else if (Main.rand.Next(3) == 0)
            {
                num12++;
            }
            for (int k = 0; k < num12; k++)
            {
                ((Vector2)(ref pointPoisition))._002Ector(base.position.X + (float)width * 0.5f + (float)(Main.rand.Next(201) * -direction) + ((float)Main.mouseX + Main.screenPosition.X - base.position.X), MountedCenter.Y - 600f);
                pointPoisition.X = (pointPoisition.X * 10f + base.Center.X) / 11f + (float)Main.rand.Next(-100, 101);
                pointPoisition.Y -= 150 * k;
                num102 = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X;
                num113 = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y;
                if (num113 < 0f)
                {
                    num113 *= -1f;
                }
                if (num113 < 20f)
                {
                    num113 = 20f;
                }
                num124 = (float)Math.Sqrt(num102 * num102 + num113 * num113);
                num124 = speed / num124;
                num102 *= num124;
                num113 *= num124;
                float num23 = num102 + (float)Main.rand.Next(-40, 41) * 0.03f;
                float speedY = num113 + (float)Main.rand.Next(-40, 41) * 0.03f;
                num23 *= (float)Main.rand.Next(75, 150) * 0.01f;
                pointPoisition.X += Main.rand.Next(-50, 51);
                int num34 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num23, speedY, projToShoot, Damage, KnockBack, i);
                Main.projectile[num34].noDropItem = true;
            }
        }
        else if (sItem.type == 4381)
        {
            int num45 = Main.rand.Next(1, 3);
            if (Main.rand.Next(3) == 0)
            {
                num45++;
            }
            for (int l = 0; l < num45; l++)
            {
                ((Vector2)(ref pointPoisition))._002Ector(base.position.X + (float)width * 0.5f + (float)(Main.rand.Next(61) * -direction) + ((float)Main.mouseX + Main.screenPosition.X - base.position.X), MountedCenter.Y - 600f);
                pointPoisition.X = (pointPoisition.X * 10f + base.Center.X) / 11f + (float)Main.rand.Next(-30, 31);
                pointPoisition.Y -= 150f * Main.rand.NextFloat();
                num102 = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X;
                num113 = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y;
                if (num113 < 0f)
                {
                    num113 *= -1f;
                }
                if (num113 < 20f)
                {
                    num113 = 20f;
                }
                num124 = (float)Math.Sqrt(num102 * num102 + num113 * num113);
                num124 = speed / num124;
                num102 *= num124;
                num113 *= num124;
                float num56 = num102 + (float)Main.rand.Next(-20, 21) * 0.03f;
                float speedY3 = num113 + (float)Main.rand.Next(-40, 41) * 0.03f;
                num56 *= (float)Main.rand.Next(55, 80) * 0.01f;
                pointPoisition.X += Main.rand.Next(-50, 51);
                int num67 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num56, speedY3, projToShoot, Damage, KnockBack, i);
                Main.projectile[num67].noDropItem = true;
            }
        }
        else if (sItem.type == 98 || sItem.type == 533)
        {
            float speedX = num102 + (float)Main.rand.Next(-40, 41) * 0.01f;
            float speedY4 = num113 + (float)Main.rand.Next(-40, 41) * 0.01f;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX, speedY4, projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 1319)
        {
            float speedX2 = num102 + (float)Main.rand.Next(-40, 41) * 0.02f;
            float speedY5 = num113 + (float)Main.rand.Next(-40, 41) * 0.02f;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX2, speedY5, projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 3107)
        {
            float speedX3 = num102 + (float)Main.rand.Next(-40, 41) * 0.02f;
            float speedY6 = num113 + (float)Main.rand.Next(-40, 41) * 0.02f;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX3, speedY6, projToShoot, Damage, KnockBack, i);
        }
        else if (ProjectileID.Sets.IsAGolfBall[projToShoot])
        {
            Vector2 vector57 = default(Vector2);
            ((Vector2)(ref vector57))._002Ector((float)Main.mouseX + Main.screenPosition.X, (float)Main.mouseY + Main.screenPosition.Y);
            Vector2 vector58 = vector57 - base.Center;
            bool flag2 = false;
            if (((Vector2)(ref vector58)).Length() < 100f)
            {
                flag2 = TryPlacingAGolfBallNearANearbyTee(vector57);
            }
            if (!flag2)
            {
                if (((Vector2)(ref vector58)).Length() > 100f || !Collision.CanHit(base.Center, 1, 1, vector57, 1, 1))
                {
                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot, Damage, KnockBack, i);
                }
                else
                {
                    Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector57.X, vector57.Y, 0f, 0f, projToShoot, Damage, KnockBack, i);
                }
            }
        }
        else if (sItem.type == 3053)
        {
            bool flag3 = false;
            if (itemAnimation <= sItem.useTime + 1)
            {
                flag3 = true;
            }
            Vector2 vector2 = default(Vector2);
            ((Vector2)(ref vector2))._002Ector(num102, num113);
            ((Vector2)(ref vector2)).Normalize();
            vector2 *= 4f;
            if (!flag3)
            {
                Vector2 vector3 = default(Vector2);
                ((Vector2)(ref vector3))._002Ector((float)Main.rand.Next(-100, 101), (float)Main.rand.Next(-100, 101));
                ((Vector2)(ref vector3)).Normalize();
                vector2 += vector3;
            }
            ((Vector2)(ref vector2)).Normalize();
            vector2 *= sItem.shootSpeed;
            float num77 = (float)Main.rand.Next(10, 80) * 0.001f;
            if (Main.rand.Next(2) == 0)
            {
                num77 *= -1f;
            }
            float num87 = (float)Main.rand.Next(10, 80) * 0.001f;
            if (Main.rand.Next(2) == 0)
            {
                num87 *= -1f;
            }
            if (flag3)
            {
                num87 = (num77 = 0f);
            }
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector2.X, vector2.Y, projToShoot, Damage, KnockBack, i, num87, num77);
        }
        else if (sItem.type == 3019)
        {
            Vector2 vector4 = default(Vector2);
            ((Vector2)(ref vector4))._002Ector(num102, num113);
            float num98 = ((Vector2)(ref vector4)).Length();
            vector4.X += (float)Main.rand.Next(-100, 101) * 0.01f * num98 * 0.15f;
            vector4.Y += (float)Main.rand.Next(-100, 101) * 0.01f * num98 * 0.15f;
            float num103 = num102 + (float)Main.rand.Next(-40, 41) * 0.03f;
            float num104 = num113 + (float)Main.rand.Next(-40, 41) * 0.03f;
            ((Vector2)(ref vector4)).Normalize();
            vector4 *= num98;
            num103 *= (float)Main.rand.Next(50, 150) * 0.01f;
            num104 *= (float)Main.rand.Next(50, 150) * 0.01f;
            Vector2 vector5 = default(Vector2);
            ((Vector2)(ref vector5))._002Ector(num103, num104);
            vector5.X += (float)Main.rand.Next(-100, 101) * 0.025f;
            vector5.Y += (float)Main.rand.Next(-100, 101) * 0.025f;
            ((Vector2)(ref vector5)).Normalize();
            vector5 *= num98;
            num103 = vector5.X;
            num104 = vector5.Y;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num103, num104, projToShoot, Damage, KnockBack, i, vector4.X, vector4.Y);
        }
        else if (sItem.type == 2797)
        {
            Vector2 vector6 = Vector2.Normalize(new Vector2(num102, num113)) * 40f * sItem.scale;
            if (Collision.CanHit(pointPoisition, 0, 0, pointPoisition + vector6, 0, 0))
            {
                pointPoisition += vector6;
            }
            float ai = Utils.ToRotation(new Vector2(num102, num113));
            float num105 = (float)Math.PI * 2f / 3f;
            int num106 = Main.rand.Next(4, 5);
            if (Main.rand.Next(4) == 0)
            {
                num106++;
            }
            for (int m = 0; m < num106; m++)
            {
                float num107 = (float)Main.rand.NextDouble() * 0.2f + 0.05f;
                Vector2 spinningpoint6 = new Vector2(num102, num113);
                double radians5 = num105 * (float)Main.rand.NextDouble() - num105 / 2f;
                val = default(Vector2);
                Vector2 vector7 = Utils.RotatedBy(spinningpoint6, radians5, val) * num107;
                int num108 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector7.X, vector7.Y, 444, Damage, KnockBack, i, ai);
                Main.projectile[num108].localAI[0] = projToShoot;
                Main.projectile[num108].localAI[1] = speed;
            }
        }
        else if (sItem.type == 2270)
        {
            float num109 = num102 + (float)Main.rand.Next(-40, 41) * 0.05f;
            float num110 = num113 + (float)Main.rand.Next(-40, 41) * 0.05f;
            if (Main.rand.Next(3) == 0)
            {
                num109 *= 1f + (float)Main.rand.Next(-30, 31) * 0.02f;
                num110 *= 1f + (float)Main.rand.Next(-30, 31) * 0.02f;
            }
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num109, num110, projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 5117)
        {
            float speedX4 = num102 + (float)Main.rand.Next(-15, 16) * 0.075f;
            float speedY7 = num113 + (float)Main.rand.Next(-15, 16) * 0.075f;
            int num111 = Main.rand.Next(Main.projFrames[sItem.shoot]);
            int damage2 = Damage;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX4, speedY7, projToShoot, damage2, KnockBack, i, 0f, num111);
        }
        else if (sItem.type == 1930)
        {
            int num112 = 2 + Main.rand.Next(3);
            for (int n = 0; n < num112; n++)
            {
                float num114 = num102;
                float num115 = num113;
                float num116 = 0.025f * (float)n;
                num114 += (float)Main.rand.Next(-35, 36) * num116;
                num115 += (float)Main.rand.Next(-35, 36) * num116;
                num124 = (float)Math.Sqrt(num114 * num114 + num115 * num115);
                num124 = speed / num124;
                num114 *= num124;
                num115 *= num124;
                float x = pointPoisition.X + num102 * (float)(num112 - n) * 1.75f;
                float y = pointPoisition.Y + num113 * (float)(num112 - n) * 1.75f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, x, y, num114, num115, projToShoot, Damage, KnockBack, i, Main.rand.Next(0, 10 * (n + 1)));
            }
        }
        else if (sItem.type == 1931)
        {
            int num117 = 2;
            for (int num118 = 0; num118 < num117; num118++)
            {
                ((Vector2)(ref pointPoisition))._002Ector(base.position.X + (float)width * 0.5f + (float)(Main.rand.Next(201) * -direction) + ((float)Main.mouseX + Main.screenPosition.X - base.position.X), MountedCenter.Y - 600f);
                pointPoisition.X = (pointPoisition.X + base.Center.X) / 2f + (float)Main.rand.Next(-200, 201);
                pointPoisition.Y -= 100 * num118;
                num102 = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X;
                num113 = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y;
                if (gravDir == -1f)
                {
                    num113 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - pointPoisition.Y;
                }
                if (num113 < 0f)
                {
                    num113 *= -1f;
                }
                if (num113 < 20f)
                {
                    num113 = 20f;
                }
                num124 = (float)Math.Sqrt(num102 * num102 + num113 * num113);
                num124 = speed / num124;
                num102 *= num124;
                num113 *= num124;
                float speedX5 = num102 + (float)Main.rand.Next(-40, 41) * 0.02f;
                float speedY8 = num113 + (float)Main.rand.Next(-40, 41) * 0.02f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX5, speedY8, projToShoot, Damage, KnockBack, i, 0f, Main.rand.Next(5));
            }
        }
        else if (sItem.type == 2750)
        {
            int num119 = 1;
            for (int num120 = 0; num120 < num119; num120++)
            {
                ((Vector2)(ref pointPoisition))._002Ector(base.position.X + (float)width * 0.5f + (float)(Main.rand.Next(201) * -direction) + ((float)Main.mouseX + Main.screenPosition.X - base.position.X), MountedCenter.Y - 600f);
                pointPoisition.X = (pointPoisition.X + base.Center.X) / 2f + (float)Main.rand.Next(-200, 201);
                pointPoisition.Y -= 100 * num120;
                num102 = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X + (float)Main.rand.Next(-40, 41) * 0.03f;
                num113 = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y;
                if (gravDir == -1f)
                {
                    num113 = Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY - pointPoisition.Y;
                }
                if (num113 < 0f)
                {
                    num113 *= -1f;
                }
                if (num113 < 20f)
                {
                    num113 = 20f;
                }
                num124 = (float)Math.Sqrt(num102 * num102 + num113 * num113);
                num124 = speed / num124;
                num102 *= num124;
                num113 *= num124;
                float num121 = num102;
                float num122 = num113 + (float)Main.rand.Next(-40, 41) * 0.02f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num121 * 0.75f, num122 * 0.75f, projToShoot + Main.rand.Next(3), Damage, KnockBack, i, 0f, 0.5f + (float)Main.rand.NextDouble() * 0.3f);
            }
        }
        else if (sItem.type == 3570)
        {
            int num123 = 3;
            for (int num125 = 0; num125 < num123; num125++)
            {
                ((Vector2)(ref pointPoisition))._002Ector(base.position.X + (float)width * 0.5f + (float)(Main.rand.Next(201) * -direction) + ((float)Main.mouseX + Main.screenPosition.X - base.position.X), MountedCenter.Y - 600f);
                pointPoisition.X = (pointPoisition.X + base.Center.X) / 2f + (float)Main.rand.Next(-200, 201);
                pointPoisition.Y -= 100 * num125;
                num102 = (float)Main.mouseX + Main.screenPosition.X - pointPoisition.X;
                num113 = (float)Main.mouseY + Main.screenPosition.Y - pointPoisition.Y;
                float ai2 = num113 + pointPoisition.Y;
                if (num113 < 0f)
                {
                    num113 *= -1f;
                }
                if (num113 < 20f)
                {
                    num113 = 20f;
                }
                num124 = (float)Math.Sqrt(num102 * num102 + num113 * num113);
                num124 = speed / num124;
                num102 *= num124;
                num113 *= num124;
                Vector2 vector8 = new Vector2(num102, num113) / 2f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector8.X, vector8.Y, projToShoot, Damage, KnockBack, i, 0f, ai2);
            }
        }
        else if (sItem.type == 5065)
        {
            Vector2 farthestSpawnPositionOnLine = GetFarthestSpawnPositionOnLine(pointPoisition, num102, num113);
            Vector2 zero = Vector2.Zero;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, farthestSpawnPositionOnLine, zero, projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 3065)
        {
            Vector2 vector9 = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY);
            float num126 = vector9.Y;
            if (num126 > base.Center.Y - 200f)
            {
                num126 = base.Center.Y - 200f;
            }
            for (int num127 = 0; num127 < 3; num127++)
            {
                pointPoisition = base.Center + new Vector2((float)(-Main.rand.Next(0, 401) * direction), -600f);
                pointPoisition.Y -= 100 * num127;
                Vector2 vector10 = vector9 - pointPoisition;
                if (vector10.Y < 0f)
                {
                    vector10.Y *= -1f;
                }
                if (vector10.Y < 20f)
                {
                    vector10.Y = 20f;
                }
                ((Vector2)(ref vector10)).Normalize();
                vector10 *= speed;
                num102 = vector10.X;
                num113 = vector10.Y;
                float speedX6 = num102;
                float speedY9 = num113 + (float)Main.rand.Next(-40, 41) * 0.02f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX6, speedY9, projToShoot, Damage, KnockBack, i, 0f, num126);
            }
        }
        else if (sItem.type == 2624)
        {
            float num128 = (float)Math.PI / 10f;
            int num129 = 5;
            Vector2 vector11 = default(Vector2);
            ((Vector2)(ref vector11))._002Ector(num102, num113);
            ((Vector2)(ref vector11)).Normalize();
            vector11 *= 40f;
            bool flag4 = Collision.CanHit(pointPoisition, 0, 0, pointPoisition + vector11, 0, 0);
            for (int num130 = 0; num130 < num129; num130++)
            {
                float num131 = (float)num130 - ((float)num129 - 1f) / 2f;
                Vector2 spinningpoint7 = vector11;
                double radians6 = num128 * num131;
                val = default(Vector2);
                Vector2 vector13 = spinningpoint7.RotatedBy(radians6, val);
                if (!flag4)
                {
                    vector13 -= vector11;
                }
                int num132 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X + vector13.X, pointPoisition.Y + vector13.Y, num102, num113, projToShoot, Damage, KnockBack, i);
                Main.projectile[num132].noDropItem = true;
            }
        }
        else if (sItem.type == 1929)
        {
            float speedX7 = num102 + (float)Main.rand.Next(-40, 41) * 0.03f;
            float speedY10 = num113 + (float)Main.rand.Next(-40, 41) * 0.03f;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX7, speedY10, projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 1553)
        {
            float speedX8 = num102 + (float)Main.rand.Next(-40, 41) * 0.005f;
            float speedY2 = num113 + (float)Main.rand.Next(-40, 41) * 0.005f;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, speedX8, speedY2, projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 518)
        {
            float num133 = num102;
            float num134 = num113;
            num133 += (float)Main.rand.Next(-40, 41) * 0.04f;
            num134 += (float)Main.rand.Next(-40, 41) * 0.04f;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num133, num134, projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 1265)
        {
            float num136 = num102;
            float num137 = num113;
            num136 += (float)Main.rand.Next(-30, 31) * 0.03f;
            num137 += (float)Main.rand.Next(-30, 31) * 0.03f;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num136, num137, projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 4262)
        {
            float num138 = 2.6666667f;
            _ = base.Bottom;
            _ = (int)base.Bottom.X / 16;
            int num139 = 4;
            float num140 = Math.Abs((float)Main.mouseX + Main.screenPosition.X - base.position.X) / 16f;
            if (direction < 0)
            {
                num140 += 1f;
            }
            num139 = (int)num140;
            if (num139 > 15)
            {
                num139 = 15;
            }
            Point point = base.Center.ToTileCoordinates();
            int maxDistance = 31;
            for (int num141 = num139; num141 >= 0; num141--)
            {
                if (Collision.CanHitLine(base.Center, 1, 1, base.Center + new Vector2((float)(16 * num141 * direction), 0f), 1, 1) && WorldUtils.Find(new Point(point.X + direction * num141, point.Y), Searches.Chain(new Searches.Down(maxDistance), new Terraria.WorldBuilding.Conditions.MysticSnake()), out var result))
                {
                    int num142 = result.Y;
                    while (Main.tile[result.X, num142 - 1].active())
                    {
                        num142--;
                        if (Main.tile[result.X, num142 - 1] == null || num142 < 10 || result.Y - num142 > 7)
{
                            num142 = -1;
                            break;
                        }
                    }
                    if (num142 >= 10)
                    {
                        result.Y = num142;
                        for (int num143 = 0; num143 < 1000; num143++)
{
                            Projectile projectile = Main.projectile[num143];
                            if (projectile.active && projectile.owner == whoAmI && projectile.type == projToShoot)
{
                                if (projectile.ai[1] == 2f)
{
                                    projectile.timeLeft = 4;
                                }
                                else
{
                                    projectile.Kill();
                                }
                            }
                        }
                        Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, result.X * 16 + 8, result.Y * 16 + 8 - 16, 0f, 0f - num138, projToShoot, Damage, KnockBack, i, result.Y * 16 + 8 - 16);
                        break;
                    }
                }
            }
        }
        else if (sItem.type == 4952)
        {
            Vector2 vector14 = Main.rand.NextVector2Circular(1f, 1f) + Main.rand.NextVector2CircularEdge(3f, 3f);
            if (vector14.Y > 0f)
            {
                vector14.Y *= -1f;
            }
            float num144 = (float)itemAnimation / (float)itemAnimationMax * 0.66f + miscCounterNormalized;
            pointPoisition = MountedCenter + new Vector2((float)(direction * 15), gravDir * 3f);
            Point point2 = pointPoisition.ToTileCoordinates();
            Tile tile = Main.tile[point2.X, point2.Y];
            if (tile != null && tile.nactive() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type] && !TileID.Sets.Platforms[tile.type])
            {
                pointPoisition = MountedCenter;
            }
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector14.X, vector14.Y, projToShoot, Damage, KnockBack, i, -1f, num144 % 1f);
        }
        else if (sItem.type == 4953)
        {
            float num145 = (float)Math.PI / 10f;
            int num147 = 5;
            Vector2 vector15 = default(Vector2);
            ((Vector2)(ref vector15))._002Ector(num102, num113);
            ((Vector2)(ref vector15)).Normalize();
            vector15 *= 40f;
            bool num189 = Collision.CanHit(pointPoisition, 0, 0, pointPoisition + vector15, 0, 0);
            int num148 = (itemAnimationMax - itemAnimation) / 2;
            int num149 = num148;
            if (direction == 1)
            {
                num149 = 4 - num148;
            }
            float num150 = (float)num149 - ((float)num147 - 1f) / 2f;
            Vector2 spinningpoint8 = vector15;
            double radians7 = num145 * num150;
            val = default(Vector2);
            Vector2 vector16 = spinningpoint8.RotatedBy(radians7, val);
            if (!num189)
            {
                vector16 -= vector15;
            }
            Vector2 mouseWorld = Main.MouseWorld;
            Vector2 origin = pointPoisition + vector16;
            Vector2 vector17 = origin.DirectionTo(mouseWorld).SafeNormalize(-Vector2.UnitY);
            Vector2 value2 = base.Center.DirectionTo(base.Center + new Vector2(num102, num113)).SafeNormalize(-Vector2.UnitY);
            float lerpValue = Utils.GetLerpValue(100f, 40f, mouseWorld.Distance(base.Center), clamped: true);
            if (lerpValue > 0f)
            {
                vector17 = Vector2.Lerp(vector17, value2, lerpValue).SafeNormalize(Utils.SafeNormalize(new Vector2(num102, num113), -Vector2.UnitY));
            }
            Vector2 v3 = vector17 * speed;
            if (num148 == 2)
            {
                projToShoot = 932;
                Damage *= 2;
            }
            if (projToShoot == 932)
            {
                float ai3 = miscCounterNormalized * 12f % 1f;
                v3 = v3.SafeNormalize(Vector2.Zero) * (speed * 2f);
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, origin, v3, projToShoot, Damage, KnockBack, i, 0f, ai3);
            }
            else
            {
                int num151 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, origin, v3, projToShoot, Damage, KnockBack, i);
                Main.projectile[num151].noDropItem = true;
            }
        }
        else if (sItem.type == 534)
        {
            int num152 = Main.rand.Next(4, 6);
            for (int num153 = 0; num153 < num152; num153++)
            {
                float num154 = num102;
                float num155 = num113;
                num154 += (float)Main.rand.Next(-40, 41) * 0.05f;
                num155 += (float)Main.rand.Next(-40, 41) * 0.05f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num154, num155, projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 4703)
        {
            float num157 = (float)Math.PI / 2f;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot, Damage, KnockBack, i);
            Vector2 v4 = default(Vector2);
            for (int num158 = 0; num158 < 7; num158++)
            {
                ((Vector2)(ref v4))._002Ector(num102, num113);
                float num159 = ((Vector2)(ref v4)).Length();
                Vector2 val7 = v4;
                Vector2 spinningpoint9 = v4.SafeNormalize(Vector2.Zero);
                double radians8 = num157 * Main.rand.NextFloat();
                val = default(Vector2);
                v4 = val7 + spinningpoint9.RotatedBy(radians8, val) * Main.rand.NextFloatDirection() * 5f;
                v4 = v4.SafeNormalize(Vector2.Zero) * num159;
                float x2 = v4.X;
                float y2 = v4.Y;
                x2 += (float)Main.rand.Next(-40, 41) * 0.05f;
                y2 += (float)Main.rand.Next(-40, 41) * 0.05f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, x2, y2, projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 4270)
        {
            Vector2 pointPoisition2 = Main.MouseWorld;
            LimitPointToPlayerReachableArea(ref pointPoisition2);
            Vector2 vector18 = pointPoisition2 + Main.rand.NextVector2Circular(8f, 8f);
            Vector2 vector19 = FindSharpTearsSpot(vector18).ToWorldCoordinates(Main.rand.Next(17), Main.rand.Next(17));
            Vector2 vector20 = (vector18 - vector19).SafeNormalize(-Vector2.UnitY) * 16f;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector19.X, vector19.Y, vector20.X, vector20.Y, projToShoot, Damage, KnockBack, i, 0f, Main.rand.NextFloat() * 0.5f + 0.6f);
        }
        else if (sItem.type == 4715)
        {
            Vector2 vector21 = Main.MouseWorld;
            List<NPC> validTargets;
            bool sparkleGuitarTarget3 = GetSparkleGuitarTarget(out validTargets);
            if (sparkleGuitarTarget3)
            {
                NPC nPC = validTargets[Main.rand.Next(validTargets.Count)];
                vector21 = nPC.Center + nPC.velocity * 20f;
            }
            Vector2 vector22 = vector21 - base.Center;
            if (!sparkleGuitarTarget3)
            {
                vector21 += Main.rand.NextVector2Circular(24f, 24f);
                if (((Vector2)(ref vector22)).Length() > 700f)
                {
                    vector22 *= 700f / ((Vector2)(ref vector22)).Length();
                    vector21 = base.Center + vector22;
                }
            }
            Vector2 vector23 = Main.rand.NextVector2CircularEdge(1f, 1f);
            if (vector23.Y > 0f)
            {
                vector23 *= -1f;
            }
            if (Math.Abs(vector23.Y) < 0.5f)
            {
                vector23.Y = (0f - Main.rand.NextFloat()) * 0.5f - 0.5f;
            }
            vector23 *= ((Vector2)(ref vector22)).Length() * 2f;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector23.X, vector23.Y, projToShoot, Damage, KnockBack, i, vector21.X, vector21.Y);
        }
        else if (sItem.type == 4722)
        {
            Vector2 vector24 = Main.MouseWorld;
            List<NPC> validTargets2;
            bool sparkleGuitarTarget2 = GetSparkleGuitarTarget(out validTargets2);
            if (sparkleGuitarTarget2)
            {
                NPC nPC2 = validTargets2[Main.rand.Next(validTargets2.Count)];
                vector24 = nPC2.Center + nPC2.velocity * 20f;
            }
            Vector2 vector25 = vector24 - base.Center;
            Vector2 vector26 = Main.rand.NextVector2CircularEdge(1f, 1f);
            float num160 = 1f;
            int num161 = 1;
            Vector2 vector28 = default(Vector2);
            for (int num162 = 0; num162 < num161; num162++)
            {
                if (!sparkleGuitarTarget2)
                {
                    vector24 += Main.rand.NextVector2Circular(24f, 24f);
                    if (((Vector2)(ref vector25)).Length() > 700f)
                    {
                        vector25 *= 700f / ((Vector2)(ref vector25)).Length();
                        vector24 = base.Center + vector25;
                    }
                    float num163 = Utils.GetLerpValue(0f, 6f, ((Vector2)(ref velocity)).Length(), clamped: true) * 0.8f;
                    vector26 *= 1f - num163;
                    vector26 += velocity * num163;
                    vector26 = vector26.SafeNormalize(Vector2.UnitX);
                }
                float num164 = 60f;
                float num165 = Main.rand.NextFloatDirection() * (float)Math.PI * (1f / num164) * 0.5f * num160;
                float num166 = num164 / 2f;
                float num168 = 12f + Main.rand.NextFloat() * 2f;
                Vector2 vector27 = vector26 * num168;
                ((Vector2)(ref vector28))._002Ector(0f, 0f);
                Vector2 vector29 = vector27;
                for (int num169 = 0; (float)num169 < num166; num169++)
                {
                    vector28 += vector29;
                    Vector2 spinningpoint10 = vector29;
                    double radians9 = num165;
                    val = default(Vector2);
                    vector29 = spinningpoint10.RotatedBy(radians9, val);
                }
                Vector2 vector30 = -vector28;
                Vector2 vector31 = vector24 + vector30;
                float lerpValue2 = Utils.GetLerpValue(itemAnimationMax, 0f, itemAnimation, clamped: true);
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector31, vector27, projToShoot, Damage, KnockBack, i, num165, lerpValue2);
            }
        }
        else if (sItem.type == 4607)
        {
            int minionProjectileId = projToShoot;
            float knockBack = KnockBack;
            val = default(Vector2);
            Vector2 offsetFromCursor = val;
            val = default(Vector2);
            SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, minionProjectileId, damage, knockBack, offsetFromCursor, val);
        }
        else if (sItem.type == 5069)
        {
            int minionProjectileId2 = projToShoot;
            float knockBack2 = KnockBack;
            val = default(Vector2);
            Vector2 offsetFromCursor2 = val;
            val = default(Vector2);
            SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, minionProjectileId2, damage, knockBack2, offsetFromCursor2, val);
        }
        else if (sItem.type == 5114)
        {
            int minionProjectileId3 = projToShoot;
            float knockBack3 = KnockBack;
            val = default(Vector2);
            Vector2 offsetFromCursor3 = val;
            val = default(Vector2);
            SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, minionProjectileId3, damage, knockBack3, offsetFromCursor3, val);
        }
        else if (sItem.type == 2188)
        {
            int num170 = 4;
            if (Main.rand.Next(3) == 0)
            {
                num170++;
            }
            if (Main.rand.Next(4) == 0)
            {
                num170++;
            }
            if (Main.rand.Next(5) == 0)
            {
                num170++;
            }
            for (int num171 = 0; num171 < num170; num171++)
            {
                float num172 = num102;
                float num173 = num113;
                float num174 = 0.05f * (float)num171;
                num172 += (float)Main.rand.Next(-35, 36) * num174;
                num173 += (float)Main.rand.Next(-35, 36) * num174;
                num124 = (float)Math.Sqrt(num172 * num172 + num173 * num173);
                num124 = speed / num124;
                num172 *= num124;
                num173 *= num124;
                float x3 = pointPoisition.X;
                float y3 = pointPoisition.Y;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, x3, y3, num172, num173, projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 1308)
        {
            int num175 = 3;
            if (Main.rand.Next(3) == 0)
            {
                num175++;
            }
            for (int num176 = 0; num176 < num175; num176++)
            {
                float num177 = num102;
                float num179 = num113;
                float num180 = 0.05f * (float)num176;
                num177 += (float)Main.rand.Next(-35, 36) * num180;
                num179 += (float)Main.rand.Next(-35, 36) * num180;
                num124 = (float)Math.Sqrt(num177 * num177 + num179 * num179);
                num124 = speed / num124;
                num177 *= num124;
                num179 *= num124;
                float x4 = pointPoisition.X;
                float y4 = pointPoisition.Y;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, x4, y4, num177, num179, projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 1258)
        {
            float num181 = num102;
            float num182 = num113;
            num181 += (float)Main.rand.Next(-40, 41) * 0.01f;
            num182 += (float)Main.rand.Next(-40, 41) * 0.01f;
            pointPoisition.X += (float)Main.rand.Next(-40, 41) * 0.05f;
            pointPoisition.Y += (float)Main.rand.Next(-45, 36) * 0.05f;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num181, num182, projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 964)
        {
            int num183 = Main.rand.Next(3, 5);
            for (int num184 = 0; num184 < num183; num184++)
            {
                float num185 = num102;
                float num186 = num113;
                num185 += (float)Main.rand.Next(-35, 36) * 0.04f;
                num186 += (float)Main.rand.Next(-35, 36) * 0.04f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num185, num186, projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 1569)
        {
            int num187 = 4;
            if (Main.rand.Next(2) == 0)
            {
                num187++;
            }
            if (Main.rand.Next(4) == 0)
            {
                num187++;
            }
            if (Main.rand.Next(8) == 0)
            {
                num187++;
            }
            if (Main.rand.Next(16) == 0)
            {
                num187++;
            }
            for (int num188 = 0; num188 < num187; num188++)
            {
                float num3 = num102;
                float num4 = num113;
                float num5 = 0.05f * (float)num188;
                num3 += (float)Main.rand.Next(-35, 36) * num5;
                num4 += (float)Main.rand.Next(-35, 36) * num5;
                num124 = (float)Math.Sqrt(num3 * num3 + num4 * num4);
                num124 = speed / num124;
                num3 *= num124;
                num4 *= num124;
                float x5 = pointPoisition.X;
                float y5 = pointPoisition.Y;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, x5, y5, num3, num4, projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 1572 || sItem.type == 2366 || sItem.type == 3571 || sItem.type == 3569 || sItem.type == 5119)
        {
            bool num190 = sItem.type == 3571 || sItem.type == 3569;
            int num6 = (int)((float)Main.mouseX + Main.screenPosition.X) / 16;
            int num7 = (int)((float)Main.mouseY + Main.screenPosition.Y) / 16;
            if (gravDir == -1f)
            {
                num7 = (int)(Main.screenPosition.Y + (float)Main.screenHeight - (float)Main.mouseY) / 16;
            }
            if (!num190)
            {
                for (; num7 < Main.maxTilesY - 10 && Main.tile[num6, num7] != null && !WorldGen.SolidTile2(num6, num7) && Main.tile[num6 - 1, num7] != null && !WorldGen.SolidTile2(num6 - 1, num7) && Main.tile[num6 + 1, num7] != null && !WorldGen.SolidTile2(num6 + 1, num7); num7++)
                {
                }
                num7--;
            }
            int num8 = 0;
            switch (sItem.type)
            {
            case 1572:
                num8 = 60;
                break;
            case 5119:
                num8 = 90;
                break;
            }
            int num9 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, (float)Main.mouseX + Main.screenPosition.X, num7 * 16 - 24, 0f, 15f, projToShoot, Damage, KnockBack, i, num8);
            Main.projectile[num9].originalDamage = damage;
            UpdateMaxTurrets();
        }
        else if (sItem.type == 1244 || sItem.type == 1256)
        {
            int num10 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot, Damage, KnockBack, i);
            Main.projectile[num10].ai[0] = (float)Main.mouseX + Main.screenPosition.X;
            Main.projectile[num10].ai[1] = (float)Main.mouseY + Main.screenPosition.Y;
        }
        else if (sItem.type == 1229)
        {
            int num11 = 2;
            if (Main.rand.Next(3) == 0)
            {
                num11++;
            }
            for (int num13 = 0; num13 < num11; num13++)
            {
                float num14 = num102;
                float num15 = num113;
                if (num13 > 0)
                {
                    num14 += (float)Main.rand.Next(-35, 36) * 0.04f;
                    num15 += (float)Main.rand.Next(-35, 36) * 0.04f;
                }
                if (num13 > 1)
                {
                    num14 += (float)Main.rand.Next(-35, 36) * 0.04f;
                    num15 += (float)Main.rand.Next(-35, 36) * 0.04f;
                }
                if (num13 > 2)
                {
                    num14 += (float)Main.rand.Next(-35, 36) * 0.04f;
                    num15 += (float)Main.rand.Next(-35, 36) * 0.04f;
                }
                int num16 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num14, num15, projToShoot, Damage, KnockBack, i);
                Main.projectile[num16].noDropItem = true;
            }
        }
        else if (sItem.type == 1121)
        {
            int num17 = Main.rand.Next(1, 4);
            if (Main.rand.Next(6) == 0)
            {
                num17++;
            }
            if (Main.rand.Next(6) == 0)
            {
                num17++;
            }
            if (strongBees && Main.rand.Next(3) == 0)
            {
                num17++;
            }
            for (int num18 = 0; num18 < num17; num18++)
            {
                float num19 = num102;
                float num20 = num113;
                num19 += (float)Main.rand.Next(-35, 36) * 0.02f;
                num20 += (float)Main.rand.Next(-35, 36) * 0.02f;
                int num21 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num19, num20, beeType(), beeDamage(Damage), beeKB(KnockBack), i);
                Main.projectile[num21].magic = true;
            }
        }
        else if (sItem.type == 1155)
        {
            int num22 = Main.rand.Next(2, 5);
            for (int num24 = 0; num24 < num22; num24++)
            {
                float num25 = num102;
                float num26 = num113;
                num25 += (float)Main.rand.Next(-35, 36) * 0.02f;
                num26 += (float)Main.rand.Next(-35, 36) * 0.02f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num25, num26, projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 1801)
        {
            int num27 = Main.rand.Next(2, 4);
            for (int num28 = 0; num28 < num27; num28++)
            {
                float num29 = num102;
                float num30 = num113;
                num29 += (float)Main.rand.Next(-35, 36) * 0.05f;
                num30 += (float)Main.rand.Next(-35, 36) * 0.05f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num29, num30, projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 679)
        {
            for (int num31 = 0; num31 < 6; num31++)
            {
                float num32 = num102;
                float num33 = num113;
                num32 += (float)Main.rand.Next(-40, 41) * 0.05f;
                num33 += (float)Main.rand.Next(-40, 41) * 0.05f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num32, num33, projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 1156)
        {
            for (int num35 = 0; num35 < 3; num35++)
            {
                float num36 = num102;
                float num37 = num113;
                num36 += (float)Main.rand.Next(-40, 41) * 0.05f;
                num37 += (float)Main.rand.Next(-40, 41) * 0.05f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num36, num37, projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 4682)
        {
            for (int num38 = 0; num38 < 3; num38++)
            {
                float num39 = num102;
                float num40 = num113;
                num39 += (float)Main.rand.Next(-20, 21) * 0.1f;
                num40 += (float)Main.rand.Next(-20, 21) * 0.1f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num39, num40, projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 2623)
        {
            for (int num41 = 0; num41 < 3; num41++)
            {
                float num42 = num102;
                float num43 = num113;
                num42 += (float)Main.rand.Next(-40, 41) * 0.1f;
                num43 += (float)Main.rand.Next(-40, 41) * 0.1f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num42, num43, projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 3210)
        {
            Vector2 vector32 = default(Vector2);
            ((Vector2)(ref vector32))._002Ector(num102, num113);
            vector32.X += (float)Main.rand.Next(-30, 31) * 0.04f;
            vector32.Y += (float)Main.rand.Next(-30, 31) * 0.03f;
            ((Vector2)(ref vector32)).Normalize();
            vector32 *= (float)Main.rand.Next(70, 91) * 0.1f;
            vector32.X += (float)Main.rand.Next(-30, 31) * 0.04f;
            vector32.Y += (float)Main.rand.Next(-30, 31) * 0.03f;
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector32.X, vector32.Y, projToShoot, Damage, KnockBack, i, Main.rand.Next(20));
        }
        else if (sItem.type == 434)
        {
            float num44 = num102;
            float num46 = num113;
            if (itemAnimation < 5)
            {
                num44 += (float)Main.rand.Next(-40, 41) * 0.01f;
                num46 += (float)Main.rand.Next(-40, 41) * 0.01f;
                num44 *= 1.1f;
                num46 *= 1.1f;
            }
            else if (itemAnimation < 10)
            {
                num44 += (float)Main.rand.Next(-20, 21) * 0.01f;
                num46 += (float)Main.rand.Next(-20, 21) * 0.01f;
                num44 *= 1.05f;
                num46 *= 1.05f;
            }
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num44, num46, projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 1157)
        {
            projToShoot = Main.rand.Next(191, 195);
            int minionProjectileId4 = projToShoot;
            float knockBack4 = KnockBack;
            val = default(Vector2);
            Vector2 offsetFromCursor4 = val;
            val = default(Vector2);
            int num47 = SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, minionProjectileId4, damage, knockBack4, offsetFromCursor4, val);
            Main.projectile[num47].localAI[0] = 30f;
        }
        else if (sItem.type == 1802)
        {
            int minionProjectileId5 = projToShoot;
            float knockBack5 = KnockBack;
            val = default(Vector2);
            Vector2 offsetFromCursor5 = val;
            val = default(Vector2);
            SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, minionProjectileId5, damage, knockBack5, offsetFromCursor5, val);
        }
        else if (sItem.type == 2364 || sItem.type == 2365)
        {
            int minionProjectileId6 = projToShoot;
            float knockBack6 = KnockBack;
            val = default(Vector2);
            Vector2 offsetFromCursor6 = val;
            val = default(Vector2);
            SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, minionProjectileId6, damage, knockBack6, offsetFromCursor6, val);
        }
        else if (sItem.type == 2535)
        {
            num102 = 0f;
            num113 = 0f;
            Vector2 spinningpoint = default(Vector2);
            ((Vector2)(ref spinningpoint))._002Ector(num102, num113);
            Vector2 spinningpoint11 = spinningpoint;
            val = default(Vector2);
            spinningpoint = spinningpoint11.RotatedBy(1.5707963705062866, val);
            SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot, damage, KnockBack, spinningpoint, spinningpoint);
            Vector2 spinningpoint12 = spinningpoint;
            val = default(Vector2);
            spinningpoint = spinningpoint12.RotatedBy(-3.1415927410125732, val);
            SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, projToShoot + 1, damage, KnockBack, spinningpoint, spinningpoint);
        }
        else if (sItem.type == 2551)
        {
            int minionProjectileId7 = projToShoot + nextCycledSpiderMinionType;
            float knockBack7 = KnockBack;
            val = default(Vector2);
            Vector2 offsetFromCursor7 = val;
            val = default(Vector2);
            SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, minionProjectileId7, damage, knockBack7, offsetFromCursor7, val);
            nextCycledSpiderMinionType++;
            nextCycledSpiderMinionType %= 3;
        }
        else if (sItem.type == 2584)
        {
            int minionProjectileId8 = projToShoot + Main.rand.Next(3);
            float knockBack8 = KnockBack;
            val = default(Vector2);
            Vector2 offsetFromCursor8 = val;
            val = default(Vector2);
            SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, minionProjectileId8, damage, knockBack8, offsetFromCursor8, val);
        }
        else if (sItem.type == 2621)
        {
            int minionProjectileId9 = projToShoot;
            float knockBack9 = KnockBack;
            val = default(Vector2);
            Vector2 offsetFromCursor9 = val;
            val = default(Vector2);
            SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, minionProjectileId9, damage, knockBack9, offsetFromCursor9, val);
        }
        else if (sItem.type == 2749 || sItem.type == 3249 || sItem.type == 3474 || sItem.type == 4273 || sItem.type == 4281)
        {
            int minionProjectileId10 = projToShoot;
            float knockBack10 = KnockBack;
            val = default(Vector2);
            Vector2 offsetFromCursor10 = val;
            val = default(Vector2);
            SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, minionProjectileId10, damage, knockBack10, offsetFromCursor10, val);
        }
        else if (sItem.type == 3531)
        {
            int num48 = -1;
            int num49 = -1;
            for (int num50 = 0; num50 < 1000; num50++)
            {
                if (Main.projectile[num50].active && Main.projectile[num50].owner == Main.myPlayer)
                {
                    if (num48 == -1 && Main.projectile[num50].type == 625)
                    {
                        num48 = num50;
                    }
                    if (num49 == -1 && Main.projectile[num50].type == 628)
                    {
                        num49 = num50;
                    }
                    if (num48 != -1 && num49 != -1)
                    {
                        break;
                    }
                }
            }
            if (num48 == -1 && num49 == -1)
            {
                num102 = 0f;
                num113 = 0f;
                pointPoisition.X = (float)Main.mouseX + Main.screenPosition.X;
                pointPoisition.Y = (float)Main.mouseY + Main.screenPosition.Y;
                int num51 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot, Damage, KnockBack, i);
                int num52 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot + 1, Damage, KnockBack, i, num51);
                int num53 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot + 2, Damage, KnockBack, i, num52);
                int num54 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot + 3, Damage, KnockBack, i, num53);
                Main.projectile[num52].localAI[1] = num53;
                Main.projectile[num53].localAI[1] = num54;
                Main.projectile[num51].originalDamage = damage;
                Main.projectile[num52].originalDamage = damage;
                Main.projectile[num53].originalDamage = damage;
                Main.projectile[num54].originalDamage = damage;
            }
            else if (num48 != -1 && num49 != -1)
            {
                int num55 = (int)Main.projectile[num49].ai[0];
                int num57 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot + 1, Damage, KnockBack, i, num55);
                int num58 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot + 2, Damage, KnockBack, i, num57);
                Main.projectile[num57].localAI[1] = num58;
                Main.projectile[num57].netUpdate = true;
                Main.projectile[num57].ai[1] = 1f;
                Main.projectile[num58].localAI[1] = num49;
                Main.projectile[num58].netUpdate = true;
                Main.projectile[num58].ai[1] = 1f;
                Main.projectile[num49].ai[0] = num58;
                Main.projectile[num49].netUpdate = true;
                Main.projectile[num49].ai[1] = 1f;
                Main.projectile[num57].originalDamage = damage;
                Main.projectile[num58].originalDamage = damage;
                Main.projectile[num49].originalDamage = damage;
            }
        }
        else if (sItem.type == 1309 || sItem.type == 4758 || sItem.type == 4269 || sItem.type == 5005)
        {
            int minionProjectileId11 = projToShoot;
            float knockBack11 = KnockBack;
            val = default(Vector2);
            Vector2 offsetFromCursor11 = val;
            val = default(Vector2);
            SpawnMinionOnCursor(projectileSource_Item_WithPotentialAmmo, i, minionProjectileId11, damage, knockBack11, offsetFromCursor11, val);
        }
        else if (sItem.shoot > 0 && (Main.projPet[sItem.shoot] || sItem.shoot == 72 || sItem.shoot == 18 || sItem.shoot == 500 || sItem.shoot == 650) && !sItem.summon)
        {
            for (int num59 = 0; num59 < 1000; num59++)
            {
                Projectile projectile2 = Main.projectile[num59];
                if (projectile2.active && projectile2.owner == whoAmI)
                {
                    if (sItem.shoot == 72 && (projectile2.type == 72 || projectile2.type == 86 || projectile2.type == 87))
                    {
                        projectile2.Kill();
                    }
                    else if (sItem.type == 5131 && (projectile2.type == 881 || projectile2.type == 934))
                    {
                        projectile2.Kill();
                    }
                    else if (sItem.shoot == projectile2.type)
                    {
                        projectile2.Kill();
                    }
                }
            }
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot, 0, 0f, i);
        }
        else if (sItem.type == 3006)
        {
            pointPoisition = GetFarthestSpawnPositionOnLine(pointPoisition, num102, num113);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, 0f, 0f, projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 3014)
        {
            Vector2 pointPoisition3 = default(Vector2);
            pointPoisition3.X = Main.MouseWorld.X;
            pointPoisition3.Y = Main.MouseWorld.Y;
            LimitPointToPlayerReachableArea(ref pointPoisition3);
            while (Collision.CanHitLine(base.position, width, height, pointPoisition, 1, 1))
            {
                pointPoisition.X += num102;
                pointPoisition.Y += num113;
                val = pointPoisition - pointPoisition3;
                if (((Vector2)(ref val)).Length() < 20f + Math.Abs(num102) + Math.Abs(num113))
                {
                    pointPoisition = pointPoisition3;
                    break;
                }
            }
            bool flag5 = false;
            int num60 = (int)pointPoisition.Y / 16;
            int num61 = (int)pointPoisition.X / 16;
            int num62;
            for (num62 = num60; num60 < Main.maxTilesY - 10 && num60 - num62 < 30 && !WorldGen.SolidTile(num61, num60) && !TileID.Sets.Platforms[Main.tile[num61, num60].type]; num60++)
            {
            }
            if (!WorldGen.SolidTile(num61, num60) && !TileID.Sets.Platforms[Main.tile[num61, num60].type])
            {
                flag5 = true;
            }
            float num63 = num60 * 16;
            num60 = num62;
            while (num60 > 10 && num62 - num60 < 30 && !WorldGen.SolidTile(num61, num60))
            {
                num60--;
            }
            float num64 = num60 * 16 + 16;
            float num65 = num63 - num64;
            int num66 = 15;
            if (num65 > (float)(16 * num66))
            {
                num65 = 16 * num66;
            }
            num64 = num63 - num65;
            pointPoisition.X = (int)(pointPoisition.X / 16f) * 16;
            if (!flag5)
            {
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, 0f, 0f, projToShoot, Damage, KnockBack, i, num64, num65);
            }
        }
        else if (sItem.type == 3384)
        {
            int num68 = ((altFunctionUse == 2) ? 1 : 0);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot, Damage, KnockBack, i, 0f, num68);
        }
        else if (sItem.type == 3473)
        {
            float ai4 = (Main.rand.NextFloat() - 0.5f) * ((float)Math.PI / 4f);
            Vector2 vector34 = default(Vector2);
            ((Vector2)(ref vector34))._002Ector(num102, num113);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector34.X, vector34.Y, projToShoot, Damage, KnockBack, i, 0f, ai4);
        }
        else if (sItem.type == 4956)
        {
            int num69 = (itemAnimationMax - itemAnimation) / itemTime;
            Vector2 vector35 = default(Vector2);
            ((Vector2)(ref vector35))._002Ector(num102, num113);
            int num70 = FinalFractalHelper.GetRandomProfileIndex();
            if (num69 == 0)
            {
                num70 = 4956;
            }
            Vector2 pointPoisition4 = Main.MouseWorld;
            LimitPointToPlayerReachableArea(ref pointPoisition4);
            Vector2 vector36 = pointPoisition4 - MountedCenter;
            if (num69 == 1 || num69 == 2)
            {
                int npcTargetIndex;
                bool zenithTarget = GetZenithTarget(pointPoisition4, 400f, out npcTargetIndex);
                if (zenithTarget)
                {
                    vector36 = Main.npc[npcTargetIndex].Center - MountedCenter;
                }
                bool flag6 = num69 == 2;
                if (num69 == 1 && !zenithTarget)
                {
                    flag6 = true;
                }
                if (flag6)
                {
                    vector36 += Main.rand.NextVector2Circular(150f, 150f);
                }
            }
            vector35 = vector36 / 2f;
            float ai5 = Main.rand.Next(-100, 101);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, vector35, projToShoot, Damage, KnockBack, i, ai5, num70);
        }
        else if (sItem.type == 3836)
        {
            float ai6 = Main.rand.NextFloat() * speed * 0.75f * (float)direction;
            ((Vector2)(ref val))._002Ector(num102, num113);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, val, projToShoot, Damage, KnockBack, i, ai6);
        }
        else if (sItem.type == 3858)
        {
            bool num191 = altFunctionUse == 2;
            Vector2 vector37 = default(Vector2);
            ((Vector2)(ref vector37))._002Ector(num102, num113);
            if (num191)
            {
                vector37 *= 1.5f;
                float ai7 = (0.3f + 0.7f * Main.rand.NextFloat()) * speed * 1.75f * (float)direction;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, vector37, 708, (int)((float)Damage * 0.5f), KnockBack + 4f, i, ai7);
            }
            else
            {
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, vector37, projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 3859)
        {
            Vector2 vector38 = default(Vector2);
            ((Vector2)(ref vector38))._002Ector(num102, num113);
            projToShoot = 710;
            vector38 *= 0.8f;
            Vector2 vector39 = vector38.SafeNormalize(-Vector2.UnitY);
            float num71 = (float)Math.PI / 180f * (float)(-direction);
            for (float num72 = -2.5f; num72 < 3f; num72 += 1f)
            {
                Vector2 val8 = pointPoisition;
                Vector2 spinningpoint13 = vector38 + vector39 * num72 * 0.5f;
                double radians10 = num72 * num71;
                val = default(Vector2);
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, val8, spinningpoint13.RotatedBy(radians10, val), projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 3870)
        {
            Vector2 vector40 = Vector2.Normalize(new Vector2(num102, num113)) * 40f * sItem.scale;
            if (Collision.CanHit(pointPoisition, 0, 0, pointPoisition + vector40, 0, 0))
            {
                pointPoisition += vector40;
            }
            Vector2 vector41 = default(Vector2);
            ((Vector2)(ref vector41))._002Ector(num102, num113);
            vector41 *= 0.8f;
            Vector2 vector42 = vector41.SafeNormalize(-Vector2.UnitY);
            float num73 = (float)Math.PI / 180f * (float)(-direction);
            for (int num74 = 0; num74 <= 2; num74++)
            {
                Vector2 val9 = pointPoisition;
                Vector2 spinningpoint14 = vector41 + vector42 * (float)num74 * 1f;
                double radians11 = (float)num74 * num73;
                val = default(Vector2);
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, val9, spinningpoint14.RotatedBy(radians11, val), projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 3542)
        {
            float num75 = (Main.rand.NextFloat() - 0.5f) * ((float)Math.PI / 4f) * 0.7f;
            for (int num76 = 0; num76 < 10; num76++)
            {
                Vector2 position = pointPoisition;
                Vector2 val10 = pointPoisition;
                Vector2 spinningpoint15 = new Vector2(num102, num113);
                double radians12 = num75;
                val = default(Vector2);
                if (Collision.CanHit(position, 0, 0, val10 + Utils.RotatedBy(spinningpoint15, radians12, val) * 100f, 0, 0))
                {
                    break;
                }
                num75 = (Main.rand.NextFloat() - 0.5f) * ((float)Math.PI / 4f) * 0.7f;
            }
            Vector2 spinningpoint16 = new Vector2(num102, num113);
            double radians13 = num75;
            val = default(Vector2);
            Vector2 vector43 = Utils.RotatedBy(spinningpoint16, radians13, val) * (0.95f + Main.rand.NextFloat() * 0.3f);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, vector43.X, vector43.Y, projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 3779)
        {
            float num78 = Main.rand.NextFloat() * ((float)Math.PI * 2f);
            for (int num79 = 0; num79 < 10; num79++)
            {
                Vector2 position2 = pointPoisition;
                Vector2 val11 = pointPoisition;
                Vector2 spinningpoint17 = new Vector2(num102, num113);
                double radians14 = num78;
                val = default(Vector2);
                if (Collision.CanHit(position2, 0, 0, val11 + Utils.RotatedBy(spinningpoint17, radians14, val) * 100f, 0, 0))
                {
                    break;
                }
                num78 = Main.rand.NextFloat() * ((float)Math.PI * 2f);
            }
            Vector2 spinningpoint18 = new Vector2(num102, num113);
            double radians15 = num78;
            val = default(Vector2);
            Vector2 vector44 = Utils.RotatedBy(spinningpoint18, radians15, val) * (0.95f + Main.rand.NextFloat() * 0.3f);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition + vector44 * 30f, Vector2.Zero, projToShoot, Damage, KnockBack, i, -2f);
        }
        else if (sItem.type == 3787)
        {
            float f = Main.rand.NextFloat() * ((float)Math.PI * 2f);
            float value3 = 20f;
            float value4 = 60f;
            Vector2 vector45 = pointPoisition + f.ToRotationVector2() * MathHelper.Lerp(value3, value4, Main.rand.NextFloat());
            for (int num80 = 0; num80 < 50; num80++)
            {
                vector45 = pointPoisition + f.ToRotationVector2() * MathHelper.Lerp(value3, value4, Main.rand.NextFloat());
                if (Collision.CanHit(pointPoisition, 0, 0, vector45 + (vector45 - pointPoisition).SafeNormalize(Vector2.UnitX) * 8f, 0, 0))
                {
                    break;
                }
                f = Main.rand.NextFloat() * ((float)Math.PI * 2f);
            }
            Vector2 v5 = Main.MouseWorld - vector45;
            Vector2 vector46 = Utils.SafeNormalize(new Vector2(num102, num113), Vector2.UnitY) * speed;
            v5 = v5.SafeNormalize(vector46) * speed;
            v5 = Vector2.Lerp(v5, vector46, 0.25f);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector45, v5, projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 3788)
        {
            Vector2 vector47 = default(Vector2);
            ((Vector2)(ref vector47))._002Ector(num102, num113);
            float num81 = (float)Math.PI / 4f;
            for (int num82 = 0; num82 < 2; num82++)
            {
                Vector2 val12 = pointPoisition;
                Vector2 val13 = vector47;
                Vector2 spinningpoint19 = vector47.SafeNormalize(Vector2.Zero);
                double radians16 = num81 * (Main.rand.NextFloat() * 0.5f + 0.5f);
                val = default(Vector2);
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, val12, val13 + spinningpoint19.RotatedBy(radians16, val) * Main.rand.NextFloatDirection() * 2f, projToShoot, Damage, KnockBack, i);
                Vector2 val14 = pointPoisition;
                Vector2 val15 = vector47;
                Vector2 spinningpoint20 = vector47.SafeNormalize(Vector2.Zero);
                double radians17 = (0f - num81) * (Main.rand.NextFloat() * 0.5f + 0.5f);
                val = default(Vector2);
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, val14, val15 + spinningpoint20.RotatedBy(radians17, val) * Main.rand.NextFloatDirection() * 2f, projToShoot, Damage, KnockBack, i);
            }
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, vector47.SafeNormalize(Vector2.UnitX * (float)direction) * (speed * 1.3f), 661, Damage * 2, KnockBack, i);
        }
        else if (sItem.type == 4463 || sItem.type == 486)
        {
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, new Vector2(num102, num113), projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 46)
        {
            Vector2 spinningpoint21 = Utils.SafeNormalize(new Vector2((float)direction, gravDir * 4f), Vector2.UnitY);
            double radians18 = (float)Math.PI * 2f * Main.rand.NextFloatDirection() * 0.05f;
            val = default(Vector2);
            Vector2 vector48 = spinningpoint21.RotatedBy(radians18, val);
            Vector2 searchCenter = MountedCenter + new Vector2(70f, -40f) * Directions + vector48 * -10f;
            if (GetZenithTarget(searchCenter, 50f, out var npcTargetIndex2))
            {
                NPC nPC3 = Main.npc[npcTargetIndex2];
                searchCenter = nPC3.Center + Main.rand.NextVector2Circular(nPC3.width / 2, nPC3.height / 2);
            }
            else
            {
                searchCenter += Main.rand.NextVector2Circular(20f, 20f);
            }
            float ai8 = 1f;
            if ((float)Main.rand.Next(100) < meleeCrit)
            {
                ai8 = 2f;
                Damage *= 2;
            }
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, searchCenter, vector48 * 0.001f, projToShoot, (int)((double)Damage * 0.5), KnockBack, i, ai8);
            NetMessage.SendData(13, -1, -1, null, whoAmI);
        }
        else if (sItem.type == 273)
        {
            float adjustedItemScale = GetAdjustedItemScale(sItem);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2((float)direction, 0f), projToShoot, Damage, KnockBack, i, (float)direction * gravDir, itemAnimationMax, adjustedItemScale);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2(num102, num113), projToShoot, Damage, KnockBack, i, (float)direction * gravDir * 0.1f, 30f, adjustedItemScale);
            NetMessage.SendData(13, -1, -1, null, whoAmI);
        }
        else if (sItem.type == 368)
        {
            float adjustedItemScale2 = GetAdjustedItemScale(sItem);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2((float)direction, 0f), projToShoot, Damage, KnockBack, i, (float)direction * gravDir, itemAnimationMax, adjustedItemScale2);
            NetMessage.SendData(13, -1, -1, null, whoAmI);
        }
        else if (sItem.type == 1826)
        {
            float adjustedItemScale3 = GetAdjustedItemScale(sItem);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2((float)direction, 0f), projToShoot, Damage, KnockBack, i, (float)direction * gravDir, itemAnimationMax, adjustedItemScale3);
            NetMessage.SendData(13, -1, -1, null, whoAmI);
        }
        else if (sItem.type == 675)
        {
            float adjustedItemScale4 = GetAdjustedItemScale(sItem);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2((float)direction, 0f), 972, Damage, KnockBack, i, (float)direction * gravDir, itemAnimationMax, adjustedItemScale4);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2(num102, num113), projToShoot, Damage / 2, KnockBack, i, (float)direction * gravDir, 32f, adjustedItemScale4);
            NetMessage.SendData(13, -1, -1, null, whoAmI);
        }
        else if (sItem.type == 674)
        {
            float adjustedItemScale5 = GetAdjustedItemScale(sItem);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2((float)direction, 0f), projToShoot, Damage, KnockBack, i, (float)direction * gravDir, itemAnimationMax, adjustedItemScale5);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2((float)direction, 0f), 982, 0, KnockBack, i, (float)direction * gravDir, itemAnimationMax, adjustedItemScale5);
            NetMessage.SendData(13, -1, -1, null, whoAmI);
        }
        else if (sItem.type == 757)
        {
            float adjustedItemScale6 = GetAdjustedItemScale(sItem);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2((float)direction, 0f), 984, Damage, KnockBack, i, (float)direction * gravDir, itemAnimationMax, adjustedItemScale6);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, MountedCenter, new Vector2(num102, num113) * 5f, projToShoot, Damage, KnockBack, i, (float)direction * gravDir, 18f, adjustedItemScale6);
            NetMessage.SendData(13, -1, -1, null, whoAmI);
        }
        else if (sItem.type == 190)
        {
            Vector2 vector49 = MountedCenter + new Vector2(70f, -40f) * Directions;
            int npcTargetIndex3;
            bool zenithTarget2 = GetZenithTarget(vector49, 150f, out npcTargetIndex3);
            if (zenithTarget2)
            {
                NPC nPC4 = Main.npc[npcTargetIndex3];
                vector49 = Main.rand.NextVector2FromRectangle(nPC4.Hitbox);
            }
            else
            {
                vector49 += Main.rand.NextVector2Circular(20f, 20f);
            }
            Vector2 vector50 = base.Center + new Vector2(Main.rand.NextFloatDirection() * (float)width / 2f, (float)(height / 2)) * Directions;
            Vector2 v6 = vector49 - vector50;
            float num192 = ((float)Math.PI + (float)Math.PI * 2f * Main.rand.NextFloat() * 1.5f) * ((float)(-direction) * gravDir);
            int num83 = 60;
            float num84 = num192 / (float)num83;
            float num85 = 16f;
            float num86 = ((Vector2)(ref v6)).Length();
            if (Math.Abs(num84) >= 0.17f)
            {
                num84 *= 0.7f;
            }
            _ = direction;
            _ = gravDir;
            Vector2 vector51 = Vector2.UnitX * num85;
            Vector2 v7 = vector51;
            int num88 = 0;
            while (((Vector2)(ref v7)).Length() < num86 && num88 < num83)
            {
                num88++;
                v7 += vector51;
                Vector2 spinningpoint22 = vector51;
                double radians19 = num84;
                val = default(Vector2);
                vector51 = spinningpoint22.RotatedBy(radians19, val);
            }
            float num89 = v7.ToRotation();
            Vector2 spinningpoint23 = v6.SafeNormalize(Vector2.UnitY);
            double radians20 = 0f - num89 - num84;
            val = default(Vector2);
            Vector2 spinningpoint2 = spinningpoint23.RotatedBy(radians20, val) * num85;
            if (num88 == num83)
            {
                spinningpoint2 = new Vector2((float)direction, 0f) * num85;
            }
            if (!zenithTarget2)
            {
                vector50.Y -= gravDir * 24f;
                Vector2 spinningpoint24 = spinningpoint2;
                double radians21 = (float)direction * gravDir * ((float)Math.PI * 2f) * 0.14f;
                val = default(Vector2);
                spinningpoint2 = spinningpoint24.RotatedBy(radians21, val);
            }
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector50, spinningpoint2, projToShoot, (int)((double)Damage * 0.25), KnockBack, i, num84, num88);
            NetMessage.SendData(13, -1, -1, null, whoAmI);
        }
        else if (sItem.type == 3475)
        {
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, 615, Damage, KnockBack, i, 5 * Main.rand.Next(0, 20));
        }
        else if (sItem.type == 3930)
        {
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, 714, Damage, KnockBack, i, 5 * Main.rand.Next(0, 20));
        }
        else if (sItem.type == 3540)
        {
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, 630, Damage, KnockBack, i);
        }
        else if (sItem.type == 5451)
        {
            for (int num90 = 0; num90 < 1000; num90++)
            {
                Projectile projectile3 = Main.projectile[num90];
                if (projectile3.type == projToShoot && projectile3.owner == whoAmI)
                {
                    projectile3.Kill();
                }
            }
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot, Damage, KnockBack, i);
        }
        else if (sItem.type == 3854)
        {
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, 705, Damage, KnockBack, i);
        }
        else if (sItem.type == 3546)
        {
            for (int num91 = 0; num91 < 2; num91++)
            {
                float num92 = num102;
                float num93 = num113;
                num92 += (float)Main.rand.Next(-40, 41) * 0.05f;
                num93 += (float)Main.rand.Next(-40, 41) * 0.05f;
                Vector2 val16 = pointPoisition;
                Vector2 spinningpoint25 = new Vector2(num92, num93);
                double radians22 = -(float)Math.PI / 2f * (float)direction;
                val = default(Vector2);
                Vector2 vector52 = val16 + Vector2.Normalize(Utils.RotatedBy(spinningpoint25, radians22, val)) * 6f;
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, vector52.X, vector52.Y, num92, num93, 167 + Main.rand.Next(4), Damage, KnockBack, i, 0f, 1f);
            }
        }
        else if (sItem.type == 3350)
        {
            float num94 = num102;
            float num95 = num113;
            num94 += (float)Main.rand.Next(-1, 2) * 0.5f;
            num95 += (float)Main.rand.Next(-1, 2) * 0.5f;
            if (Collision.CanHitLine(base.Center, 0, 0, pointPoisition + new Vector2(num94, num95) * 2f, 0, 0))
            {
                pointPoisition += new Vector2(num94, num95);
            }
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y - gravDir * 4f, num94, num95, projToShoot, Damage, KnockBack, i, 0f, (float)Main.rand.Next(12) / 6f);
        }
        else if (sItem.type == 3852)
        {
            if (altFunctionUse == 2)
            {
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, base.Bottom.Y - 100f, (float)direction * speed, 0f, 704, (int)((float)Damage * 1.75f), KnockBack, i);
            }
            else
            {
                Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot, Damage, KnockBack, i);
            }
        }
        else if (sItem.type == 3818 || sItem.type == 3819 || sItem.type == 3820 || sItem.type == 3824 || sItem.type == 3825 || sItem.type == 3826 || sItem.type == 3829 || sItem.type == 3830 || sItem.type == 3831 || sItem.type == 3832 || sItem.type == 3833 || sItem.type == 3834)
        {
            PayDD2CrystalsBeforeUse(sItem);
            FindSentryRestingSpot(sItem.shoot, out var worldX, out var worldY, out var pushYUp);
            int num96 = 0;
            int num97 = 0;
            int num99 = 0;
            switch (sItem.type)
            {
            case 3824:
            case 3825:
            case 3826:
                num96 = 1;
                num97 = Projectile.GetBallistraShotDelay(this);
                break;
            case 3832:
            case 3833:
            case 3834:
                num99 = Projectile.GetExplosiveTrapCooldown(this);
                break;
            case 3818:
                num96 = 1;
                num97 = 80;
                break;
            case 3819:
                num96 = 1;
                num97 = 70;
                break;
            case 3820:
                num96 = 1;
                num97 = 60;
                break;
            }
            int num100 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, worldX, worldY - pushYUp, 0f, 0f, projToShoot, Damage, KnockBack, i, num96, num97);
            Main.projectile[num100].originalDamage = damage;
            Main.projectile[num100].localAI[0] = num99;
            UpdateMaxTurrets();
        }
        else if (sItem.type == 65)
        {
            Vector2 vector53 = default(Vector2);
            ((Vector2)(ref vector53))._002Ector(num102, num113);
            new Vector2(100f, 0f);
            Vector2 mouseWorld2 = Main.MouseWorld;
            Vector2 vec = mouseWorld2;
            Vector2 vector55 = (pointPoisition - mouseWorld2).SafeNormalize(new Vector2(0f, -1f));
            while (vec.Y > pointPoisition.Y && WorldGen.SolidTile(vec.ToTileCoordinates()))
            {
                vec += vector55 * 16f;
            }
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition, vector53, projToShoot, Damage, KnockBack, i, 0f, vec.Y);
        }
        else if (sItem.type == 4923)
        {
            float adjustedItemScale7 = GetAdjustedItemScale(sItem);
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot, Damage, KnockBack, i, 0f, adjustedItemScale7);
        }
        else if (sItem.type == 1910)
        {
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot, Damage, KnockBack, i, 1f);
        }
        else if (sItem.type == 5134)
        {
            Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot, Damage, KnockBack, i, 0f, 1f);
        }
        else
        {
            int num101 = Projectile.NewProjectile(projectileSource_Item_WithPotentialAmmo, pointPoisition.X, pointPoisition.Y, num102, num113, projToShoot, Damage, KnockBack, i);
            if (sItem.type == 726)
            {
                Main.projectile[num101].magic = true;
            }
            if (sItem.type == 724 || sItem.type == 676)
            {
                Main.projectile[num101].melee = true;
            }
            if (projToShoot == 80)
            {
                Main.projectile[num101].ai[0] = tileTargetX;
                Main.projectile[num101].ai[1] = tileTargetY;
            }
            if (sItem.type == 760)
            {
                DestroyOldestProximityMinesOverMinesCap(20);
            }
            if (projToShoot == 442)
            {
                Main.projectile[num101].ai[0] = tileTargetX;
                Main.projectile[num101].ai[1] = tileTargetY;
            }
            if (projToShoot == 826)
            {
                Main.projectile[num101].ai[1] = Main.rand.Next(3);
            }
            if (sItem.type == 949)
            {
                Main.projectile[num101].ai[1] = 1f;
            }
            if (Main.projectile[num101].aiStyle == 99)
            {
                AchievementsHelper.HandleSpecialEvent(this, 7);
            }
            if (Main.projectile[num101].aiStyle == 160 && Main.IsItAHappyWindyDay)
            {
                AchievementsHelper.HandleSpecialEvent(this, 17);
            }
            NetMessage.SendData(13, -1, -1, null, whoAmI);
        }
    }
References Terraria.Entity.active, Terraria.Projectile.ai, Terraria.Projectile.aiStyle, Terraria.Player.altFunctionUse, Terraria.Player.ApplyItemTime(), Terraria.Player.beeDamage(), Terraria.Player.beeKB(), Terraria.Player.beeType(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.ModLoader.CombinedHooks.CanShoot(), Terraria.Entity.Center, Terraria.WorldBuilding.Searches.Chain(), Terraria.Player.ChangeDir(), Terraria.GameContent.Damage, Terraria.Player.DestroyOldestProximityMinesOverMinesCap(), Terraria.Entity.direction, Terraria.Player.Directions, Terraria.WorldBuilding.WorldUtils.Find(), Terraria.Player.FindSentryRestingSpot(), Terraria.Player.FindSharpTearsSpot(), Terraria.Player.fullRotation, Terraria.Main.GameViewMatrix, Terraria.Player.GetAdjustedItemScale(), Terraria.Projectile.GetBallistraShotDelay(), Terraria.Projectile.GetExplosiveTrapCooldown(), Terraria.Player.GetFarthestSpawnPositionOnLine(), Terraria.Utils.GetLerpValue(), Terraria.Player.GetProjectileSource_Item_WithPotentialAmmo(), Terraria.Graphics.FinalFractalHelper.GetRandomProfileIndex(), Terraria.Player.GetSparkleGuitarTarget(), Terraria.Player.GetWeaponKnockback(), Terraria.Player.GetZenithTarget(), Terraria.Player.gravDir, Terraria.ID.ItemID.Sets.gunProj, Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Entity.height, Terraria.Player.inverseMeleeSpeed, Terraria.ID.ProjectileID.Sets.IsAGolfBall, Terraria.Main.IsItAHappyWindyDay, Terraria.Player.itemAnimation, Terraria.Player.ItemAnimationJustStarted, Terraria.Player.itemAnimationMax, Terraria.Player.itemRotation, Terraria.Player.itemTime, Terraria.Projectile.Kill(), Terraria.Player.LimitPointToPlayerReachableArea(), Terraria.Projectile.localAI, Terraria.Projectile.magic, Terraria.Projectile.melee, Terraria.Player.meleeCrit, Terraria.Player.miscCounterNormalized, Terraria.ModLoader.CombinedHooks.ModifyShootStats(), Terraria.Player.MountedCenter, Terraria.Main.MouseWorld, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Player.musicNotes, Terraria.Main.myPlayer, Terraria.Tile.nactive(), Terraria.Projectile.netUpdate, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Player.nextCycledSpiderMinionType, Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.Projectile.noDropItem, Terraria.ID.ProjectileID.Sets.NoMeleeSpeedVelocityScaling, Terraria.Main.npc, Terraria.Projectile.originalDamage, Terraria.Player.overrideFishingBobber, Terraria.Projectile.owner, Terraria.Player.PayDD2CrystalsBeforeUse(), Terraria.Player.PickAmmo(), Terraria.ID.TileID.Sets.Platforms, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.projFrames, Terraria.Main.projPet, Terraria.Main.rand, Terraria.Utils.RotatedBy(), Terraria.Player.RotatedRelativePoint(), Terraria.Utils.SafeNormalize(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.NetMessage.SendData(), Terraria.ModLoader.CombinedHooks.Shoot(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile2(), Terraria.Player.SpawnMinionOnCursor(), Terraria.Player.strongBees, Terraria.ModLoader.DamageClass.Throwing, Terraria.Player.ThrownVelocity, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Utils.ToRotation(), Terraria.Player.TryPlacingAGolfBallNearANearbyTee(), Terraria.Projectile.type, Terraria.Tile.type, Terraria.Player.UpdateMaxTurrets(), Terraria.Entity.velocity, Terraria.Entity.whoAmI, Terraria.Entity.width, and Terraria.Graphics.SpriteViewMatrix.Zoom.
Referenced by Terraria.Player.ItemCheck_OwnerOnlyCode().