TModLoader: Terraria.Player.GetItemGrabRange
GetItemGrabRange()
int Terraria.Player.GetItemGrabRange (Item item) inline
Fetches the range at which the given item begins to gravitate towards the player.
This range, referred to as item grab range, is measured in pixels.
Parameters
item The item whose grab range is being evaluated.
Returns
The item grab range of the player, in pixels.
Definition at line 33847 of file Player.cs.
    {
        int num = defaultItemGrabRange;
        if (goldRing && item.IsACoin)
        {
            num += Item.coinGrabRange;
        }
        if (manaMagnet && (item.type == 184 || item.type == 1735 || item.type == 1868))
        {
            num += Item.manaGrabRange;
        }
        if (item.type == 4143)
        {
            num += Item.manaGrabRange;
        }
        if (lifeMagnet && (item.type == 58 || item.type == 1734 || item.type == 1867))
        {
            num += Item.lifeGrabRange;
        }
        if (treasureMagnet)
        {
            num += Item.treasureGrabRange;
        }
        if (item.type == 3822)
        {
            num += 50;
        }
        if (ItemID.Sets.NebulaPickup[item.type])
        {
            num += 100;
        }
        if (difficulty == 3 && CreativePowerManager.Instance.GetPower<CreativePowers.FarPlacementRangePower>().IsEnabledForPlayer(whoAmI))
        {
            num += 240;
        }
        ItemLoader.GrabRange(item, this, ref num);
        return num;
    }
References Terraria.Item.coinGrabRange, Terraria.Player.defaultItemGrabRange, Terraria.Player.difficulty, Terraria.Player.goldRing, Terraria.ModLoader.ItemLoader.GrabRange(), Terraria.GameContent.Creative.CreativePowerManager.Instance, Terraria.Item.IsACoin, Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.IsEnabledForPlayer(), Terraria.Item.lifeGrabRange, Terraria.Player.lifeMagnet, Terraria.Item.manaGrabRange, Terraria.Player.manaMagnet, Terraria.ID.ItemID.Sets.NebulaPickup, Terraria.Item.treasureGrabRange, Terraria.Player.treasureMagnet, Terraria.Item.type, and Terraria.Entity.whoAmI.
Referenced by Terraria.Item.FindOwner(), and Terraria.Player.GrabItems().