TModLoader: Terraria.Player.GrantArmorBenefits
GrantArmorBenefits()
void Terraria.Player.GrantArmorBenefits (Item armorPiece) inline
Definition at line 11114 of file Player.cs.
    {
        int type = armorPiece.type;
        RefreshInfoAccsFromItemType(armorPiece);
        RefreshMechanicalAccsFromItemType(type);
        if (armorPiece.type == 3017 || armorPiece.type == 3993)
        {
            flowerBoots = true;
            if (whoAmI == Main.myPlayer)
            {
                DoBootsEffect(DoBootsEffect_PlaceFlowersOnTile);
            }
        }
        if (armorPiece.type == 5001)
        {
            moveSpeed += 0.25f;
            moonLordLegs = true;
        }
        statDefense += armorPiece.defense;
        lifeRegen += armorPiece.lifeRegen;
        if (armorPiece.shieldSlot > 0)
        {
            hasRaisableShield = true;
        }
        switch (armorPiece.type)
        {
        case 3797:
            maxTurrets++;
            manaCost -= 0.1f;
            magicDamage += 0.1f;
            break;
        case 3798:
            magicDamage += 0.1f;
            minionDamage += 0.2f;
            break;
        case 3799:
            minionDamage += 0.1f;
            magicCrit += 20f;
            moveSpeed += 0.2f;
            break;
        case 3800:
            maxTurrets++;
            lifeRegen += 4;
            break;
        case 3801:
            meleeDamage += 0.15f;
            minionDamage += 0.15f;
            break;
        case 3802:
            minionDamage += 0.15f;
            meleeCrit += 15f;
            moveSpeed += 0.15f;
            break;
        case 3806:
            maxTurrets++;
            meleeSpeed += 0.2f;
            break;
        case 3807:
            meleeDamage += 0.2f;
            minionDamage += 0.2f;
            break;
        case 3808:
            minionDamage += 0.1f;
            meleeCrit += 15f;
            moveSpeed += 0.2f;
            break;
        case 3803:
            maxTurrets++;
            rangedCrit += 10f;
            break;
        case 3804:
            rangedDamage += 0.2f;
            minionDamage += 0.2f;
            huntressAmmoCost90 = true;
            break;
        case 3805:
            minionDamage += 0.1f;
            moveSpeed += 0.2f;
            break;
        case 3871:
            maxTurrets += 2;
            meleeDamage += 0.1f;
            minionDamage += 0.1f;
            break;
        case 3872:
            minionDamage += 0.3f;
            lifeRegen += 8;
            break;
        case 3873:
            minionDamage += 0.2f;
            meleeCrit += 20f;
            moveSpeed += 0.2f;
            break;
        case 3874:
            maxTurrets += 2;
            magicDamage += 0.15f;
            minionDamage += 0.15f;
            break;
        case 3875:
            minionDamage += 0.25f;
            magicDamage += 0.1f;
            manaCost -= 0.15f;
            break;
        case 3876:
            minionDamage += 0.2f;
            magicCrit += 25f;
            moveSpeed += 0.2f;
            break;
        case 3877:
            maxTurrets += 2;
            minionDamage += 0.1f;
            rangedCrit += 10f;
            break;
        case 3878:
            minionDamage += 0.25f;
            rangedDamage += 0.25f;
            ammoCost80 = true;
            break;
        case 3879:
            minionDamage += 0.25f;
            rangedCrit += 10f;
            moveSpeed += 0.2f;
            break;
        case 3880:
            maxTurrets += 2;
            minionDamage += 0.2f;
            meleeDamage += 0.2f;
            break;
        case 3881:
            meleeSpeed += 0.2f;
            meleeCrit += 5f;
            minionDamage += 0.2f;
            break;
        case 3882:
            minionDamage += 0.2f;
            meleeCrit += 20f;
            moveSpeed += 0.3f;
            break;
        }
        if (armorPiece.type == 5100)
        {
            SpawnHallucination(armorPiece);
        }
        if (armorPiece.type == 268)
        {
            accDivingHelm = true;
        }
        if (armorPiece.type == 238)
        {
            magicDamage += 0.05f;
            if (Main.tenthAnniversaryWorld)
            {
                maxMinions++;
            }
        }
        if (armorPiece.type == 3770)
        {
            slowFall = true;
        }
        if (armorPiece.type == 4404)
        {
            canFloatInWater = true;
        }
        if (armorPiece.type == 3776)
        {
            magicDamage += 0.15f;
            minionDamage += 0.15f;
        }
        if (armorPiece.type == 3777)
        {
            statManaMax2 += 40;
            minionDamage += 0.1f;
            maxMinions++;
        }
        if (armorPiece.type == 3778)
        {
            statManaMax2 += 40;
            magicDamage += 0.1f;
            maxMinions++;
        }
        if (armorPiece.type == 3212)
        {
            armorPenetration += 5f;
        }
        if (armorPiece.type == 2277)
        {
            allDamage += 0.05f;
            allCrit += 5f;
            meleeSpeed += 0.1f;
            moveSpeed += 0.1f;
        }
        if (armorPiece.type == 2279)
        {
            magicDamage += 0.06f;
            magicCrit += 6f;
            manaCost -= 0.1f;
        }
        if (armorPiece.type == 3109 || armorPiece.type == 4008)
        {
            nightVision = true;
        }
        if (armorPiece.type == 256 || armorPiece.type == 257 || armorPiece.type == 258)
        {
            allCrit += 3f;
        }
        if (armorPiece.type == 3374)
        {
            rangedCrit += 4f;
        }
        if (armorPiece.type == 3375)
        {
            rangedDamage += 0.05f;
        }
        if (armorPiece.type == 3376)
        {
            rangedCrit += 4f;
        }
        if (armorPiece.type == 151 || armorPiece.type == 959 || armorPiece.type == 152 || armorPiece.type == 153)
        {
            rangedDamage += 0.05f;
        }
        if (armorPiece.type == 2275)
        {
            magicDamage += 0.06f;
            magicCrit += 6f;
        }
        if (armorPiece.type == 123 || armorPiece.type == 124 || armorPiece.type == 125)
        {
            magicDamage += 0.09f;
        }
        if (armorPiece.type == 228 || armorPiece.type == 960)
        {
            statManaMax2 += 40;
            magicCrit += 6f;
        }
        if (armorPiece.type == 229 || armorPiece.type == 961)
        {
            statManaMax2 += 20;
            magicDamage += 0.06f;
        }
        if (armorPiece.type == 230 || armorPiece.type == 962)
        {
            statManaMax2 += 20;
            magicCrit += 6f;
        }
        if (armorPiece.type == 100 || armorPiece.type == 101 || armorPiece.type == 102)
        {
            allCrit += 5f;
        }
        if (armorPiece.type == 956 || armorPiece.type == 957 || armorPiece.type == 958)
        {
            allCrit += 5f;
        }
        if (armorPiece.type == 792 || armorPiece.type == 793 || armorPiece.type == 794)
        {
            allDamage += 0.03f;
        }
        if (armorPiece.type == 231)
        {
            meleeCrit += 7f;
        }
        if (armorPiece.type == 232)
        {
            meleeDamage += 0.07f;
        }
        if (armorPiece.type == 233)
        {
            meleeSpeed += 0.07f;
        }
        if (armorPiece.type == 371)
        {
            magicCrit += 9f;
            magicDamage += 0.1f;
            statManaMax2 += 40;
        }
        if (armorPiece.type == 372)
        {
            moveSpeed += 0.1f;
            meleeDamage += 0.15f;
        }
        if (armorPiece.type == 373)
        {
            rangedDamage += 0.1f;
            rangedCrit += 10f;
        }
        if (armorPiece.type == 374)
        {
            allCrit += 5f;
        }
        if (armorPiece.type == 375)
        {
            allDamage += 0.03f;
            moveSpeed += 0.1f;
        }
        if (armorPiece.type == 376)
        {
            magicDamage += 0.15f;
            statManaMax2 += 60;
        }
        if (armorPiece.type == 377)
        {
            meleeCrit += 8f;
            meleeDamage += 0.1f;
        }
        if (armorPiece.type == 378)
        {
            rangedDamage += 0.12f;
            rangedCrit += 7f;
        }
        if (armorPiece.type == 379)
        {
            allDamage += 0.07f;
        }
        if (armorPiece.type == 380)
        {
            allCrit += 10f;
        }
        if (armorPiece.type >= 2367 && armorPiece.type <= 2369)
        {
            fishingSkill += 5;
        }
        if (armorPiece.type == 400)
        {
            magicDamage += 0.12f;
            magicCrit += 12f;
            statManaMax2 += 80;
        }
        if (armorPiece.type == 401)
        {
            meleeCrit += 7f;
            meleeDamage += 0.14f;
        }
        if (armorPiece.type == 402)
        {
            rangedDamage += 0.14f;
            rangedCrit += 10f;
        }
        if (armorPiece.type == 403)
        {
            allDamage += 0.08f;
        }
        if (armorPiece.type == 404)
        {
            allCrit += 7f;
            moveSpeed += 0.05f;
        }
        if (armorPiece.type == 1205)
        {
            meleeDamage += 0.12f;
            meleeSpeed += 0.12f;
        }
        if (armorPiece.type == 1206)
        {
            rangedDamage += 0.09f;
            rangedCrit += 9f;
        }
        if (armorPiece.type == 1207)
        {
            magicDamage += 0.09f;
            magicCrit += 9f;
            statManaMax2 += 60;
        }
        if (armorPiece.type == 1208)
        {
            allDamage += 0.03f;
            allCrit += 2f;
        }
        if (armorPiece.type == 1209)
        {
            allDamage += 0.02f;
            allCrit += 1f;
        }
        if (armorPiece.type == 1210)
        {
            meleeDamage += 0.11f;
            meleeSpeed += 0.11f;
            moveSpeed += 0.07f;
        }
        if (armorPiece.type == 1211)
        {
            rangedCrit += 15f;
            moveSpeed += 0.08f;
        }
        if (armorPiece.type == 1212)
        {
            magicCrit += 18f;
            statManaMax2 += 80;
        }
        if (armorPiece.type == 1213)
        {
            allCrit += 6f;
        }
        if (armorPiece.type == 1214)
        {
            moveSpeed += 0.11f;
            allDamage += 0.08f;
        }
        if (armorPiece.type == 1215)
        {
            meleeDamage += 0.09f;
            meleeCrit += 9f;
            meleeSpeed += 0.09f;
        }
        if (armorPiece.type == 1216)
        {
            rangedDamage += 0.16f;
            rangedCrit += 7f;
        }
        if (armorPiece.type == 1217)
        {
            magicDamage += 0.16f;
            magicCrit += 7f;
            statManaMax2 += 100;
        }
        if (armorPiece.type == 1218)
        {
            allDamage += 0.04f;
            allCrit += 3f;
        }
        if (armorPiece.type == 1219)
        {
            allDamage += 0.03f;
            allCrit += 3f;
            moveSpeed += 0.06f;
        }
        if (armorPiece.type == 558 || armorPiece.type == 4898)
        {
            magicDamage += 0.12f;
            magicCrit += 12f;
            statManaMax2 += 100;
        }
        if (armorPiece.type == 559 || armorPiece.type == 4896)
        {
            meleeCrit += 10f;
            meleeDamage += 0.1f;
            meleeSpeed += 0.1f;
        }
        if (armorPiece.type == 553 || armorPiece.type == 4897)
        {
            rangedDamage += 0.15f;
            rangedCrit += 8f;
        }
        if (armorPiece.type == 4873 || armorPiece.type == 4899)
        {
            minionDamage += 0.1f;
            maxMinions++;
        }
        if (armorPiece.type == 551 || armorPiece.type == 4900)
        {
            allCrit += 7f;
        }
        if (armorPiece.type == 552 || armorPiece.type == 4901)
        {
            allDamage += 0.07f;
            moveSpeed += 0.08f;
        }
        if (armorPiece.type == 4982)
        {
            allCrit += 5f;
            manaCost -= 0.1f;
        }
        if (armorPiece.type == 4983)
        {
            allDamage += 0.05f;
            huntressAmmoCost90 = true;
        }
        if (armorPiece.type == 4984)
        {
            meleeSpeed += 0.1f;
            moveSpeed += 0.2f;
        }
        if (armorPiece.type == 1001)
        {
            meleeDamage += 0.16f;
            meleeCrit += 6f;
        }
        if (armorPiece.type == 1002)
        {
            rangedDamage += 0.16f;
            chloroAmmoCost80 = true;
        }
        if (armorPiece.type == 1003)
        {
            statManaMax2 += 80;
            manaCost -= 0.17f;
            magicDamage += 0.16f;
        }
        if (armorPiece.type == 1004)
        {
            allDamage += 0.05f;
            allCrit += 7f;
        }
        if (armorPiece.type == 1005)
        {
            allCrit += 8f;
            moveSpeed += 0.05f;
        }
        if (armorPiece.type == 2189)
        {
            statManaMax2 += 60;
            manaCost -= 0.13f;
            magicDamage += 0.1f;
            magicCrit += 10f;
        }
        if (armorPiece.type == 1504)
        {
            magicDamage += 0.07f;
            magicCrit += 7f;
        }
        if (armorPiece.type == 1505)
        {
            magicDamage += 0.08f;
            moveSpeed += 0.08f;
        }
        if (armorPiece.type == 1546)
        {
            rangedCrit += 5f;
            arrowDamage *= 1.15f;
        }
        if (armorPiece.type == 1547)
        {
            rangedCrit += 5f;
            bulletDamage *= 1.15f;
        }
        if (armorPiece.type == 1548)
        {
            rangedCrit += 5f;
            specialistDamage *= 1.15f;
        }
        if (armorPiece.type == 1549)
        {
            rangedCrit += 13f;
            rangedDamage += 0.13f;
            ammoCost80 = true;
        }
        if (armorPiece.type == 1550)
        {
            rangedCrit += 7f;
            moveSpeed += 0.12f;
        }
        if (armorPiece.type == 1282)
        {
            statManaMax2 += 20;
            manaCost -= 0.05f;
        }
        if (armorPiece.type == 1283)
        {
            statManaMax2 += 40;
            manaCost -= 0.07f;
        }
        if (armorPiece.type == 1284)
        {
            statManaMax2 += 40;
            manaCost -= 0.09f;
        }
        if (armorPiece.type == 1285)
        {
            statManaMax2 += 60;
            manaCost -= 0.11f;
        }
        if (armorPiece.type == 1286 || armorPiece.type == 4256)
        {
            statManaMax2 += 60;
            manaCost -= 0.13f;
        }
        if (armorPiece.type == 1287)
        {
            statManaMax2 += 80;
            manaCost -= 0.15f;
        }
        if (armorPiece.type == 1316 || armorPiece.type == 1317 || armorPiece.type == 1318)
        {
            aggro += 250;
        }
        if (armorPiece.type == 1316)
        {
            meleeDamage += 0.06f;
        }
        if (armorPiece.type == 1317)
        {
            meleeDamage += 0.08f;
            meleeCrit += 8f;
        }
        if (armorPiece.type == 1318)
        {
            meleeCrit += 4f;
        }
        if (armorPiece.type == 2199 || armorPiece.type == 2202)
        {
            aggro += 250;
        }
        if (armorPiece.type == 2201)
        {
            aggro += 400;
        }
        if (armorPiece.type == 2199)
        {
            meleeDamage += 0.06f;
        }
        if (armorPiece.type == 2200)
        {
            meleeDamage += 0.08f;
            meleeCrit += 8f;
            meleeSpeed += 0.06f;
            moveSpeed += 0.06f;
        }
        if (armorPiece.type == 2201)
        {
            meleeDamage += 0.05f;
            meleeCrit += 5f;
        }
        if (armorPiece.type == 2202)
        {
            meleeSpeed += 0.06f;
            moveSpeed += 0.06f;
        }
        if (armorPiece.type == 684)
        {
            rangedDamage += 0.16f;
            meleeDamage += 0.16f;
        }
        if (armorPiece.type == 685)
        {
            meleeCrit += 11f;
            rangedCrit += 11f;
        }
        if (armorPiece.type == 686)
        {
            moveSpeed += 0.08f;
            meleeSpeed += 0.1f;
        }
        if (armorPiece.type == 5068)
        {
            maxMinions++;
            minionDamage += 0.05f;
        }
        if (armorPiece.type == 2361)
        {
            maxMinions++;
            minionDamage += 0.04f;
        }
        if (armorPiece.type == 2362)
        {
            maxMinions++;
            minionDamage += 0.04f;
        }
        if (armorPiece.type == 2363)
        {
            minionDamage += 0.05f;
        }
        if (armorPiece.type == 3266)
        {
            minionDamage += 0.08f;
        }
        if (armorPiece.type == 3267)
        {
            maxMinions++;
        }
        if (armorPiece.type == 3268)
        {
            minionDamage += 0.08f;
        }
        if (armorPiece.type == 410)
        {
            pickSpeed -= 0.1f;
        }
        if (armorPiece.type == 411)
        {
            pickSpeed -= 0.1f;
        }
        if (armorPiece.type >= 1158 && armorPiece.type <= 1161)
        {
            maxMinions++;
        }
        if (armorPiece.type == 1159)
        {
            whipRangeMultiplier += 0.1f;
        }
        if (armorPiece.type >= 1159 && armorPiece.type <= 1161)
        {
            minionDamage += 0.1f;
        }
        if (armorPiece.type >= 2370 && armorPiece.type <= 2371)
        {
            minionDamage += 0.05f;
            maxMinions++;
        }
        if (armorPiece.type == 2372)
        {
            minionDamage += 0.06f;
            maxMinions++;
        }
        if (armorPiece.type == 3381)
        {
            maxMinions++;
            maxTurrets++;
            minionDamage += 0.22f;
        }
        if (armorPiece.type == 3382 || armorPiece.type == 3383)
        {
            maxMinions += 2;
            whipRangeMultiplier += 0.15f;
            minionDamage += 0.22f;
        }
        if (armorPiece.type == 2763)
        {
            aggro += 300;
            meleeCrit += 26f;
            lifeRegen += 2;
        }
        if (armorPiece.type == 2764)
        {
            aggro += 300;
            meleeDamage += 0.29f;
            lifeRegen += 2;
        }
        if (armorPiece.type == 2765)
        {
            aggro += 300;
            meleeSpeed += 0.15f;
            moveSpeed += 0.15f;
            lifeRegen += 2;
        }
        if (armorPiece.type == 2757)
        {
            rangedCrit += 7f;
            rangedDamage += 0.16f;
        }
        if (armorPiece.type == 2758)
        {
            ammoCost75 = true;
            rangedCrit += 12f;
            rangedDamage += 0.12f;
        }
        if (armorPiece.type == 2759)
        {
            rangedCrit += 8f;
            rangedDamage += 0.08f;
            moveSpeed += 0.1f;
        }
        if (armorPiece.type == 2760)
        {
            statManaMax2 += 60;
            manaCost -= 0.15f;
            magicCrit += 7f;
            magicDamage += 0.07f;
        }
        if (armorPiece.type == 2761)
        {
            magicDamage += 0.09f;
            magicCrit += 9f;
        }
        if (armorPiece.type == 2762)
        {
            moveSpeed += 0.1f;
            magicDamage += 0.1f;
        }
        if (armorPiece.type == 1832)
        {
            maxMinions++;
            minionDamage += 0.11f;
        }
        if (armorPiece.type == 1833)
        {
            maxMinions += 2;
            minionDamage += 0.11f;
        }
        if (armorPiece.type == 1834)
        {
            moveSpeed += 0.2f;
            maxMinions++;
            minionDamage += 0.11f;
        }
        ItemLoader.UpdateEquip(armorPiece, this);
    }
References Terraria.Player.accDivingHelm, Terraria.Player.aggro, Terraria.Player.allCrit, Terraria.Player.allDamage, Terraria.Player.ammoCost75, Terraria.Player.ammoCost80, Terraria.Player.armorPenetration, Terraria.Player.arrowDamage, Terraria.Player.bulletDamage, Terraria.Player.canFloatInWater, Terraria.Player.chloroAmmoCost80, Terraria.Player.DoBootsEffect(), Terraria.Player.DoBootsEffect_PlaceFlowersOnTile(), Terraria.Player.fishingSkill, Terraria.Player.flowerBoots, Terraria.Player.hasRaisableShield, Terraria.Player.huntressAmmoCost90, Terraria.Player.lifeRegen, Terraria.Player.magicCrit, Terraria.Player.magicDamage, Terraria.Player.manaCost, Terraria.Player.maxMinions, Terraria.Player.maxTurrets, Terraria.Player.meleeCrit, Terraria.Player.meleeDamage, Terraria.Player.meleeSpeed, Terraria.Player.minionDamage, Terraria.Player.moonLordLegs, Terraria.Player.moveSpeed, Terraria.Main.myPlayer, Terraria.Player.nightVision, Terraria.Player.pickSpeed, Terraria.Player.rangedCrit, Terraria.Player.rangedDamage, Terraria.Player.RefreshInfoAccsFromItemType(), Terraria.Player.RefreshMechanicalAccsFromItemType(), Terraria.Player.slowFall, Terraria.Player.SpawnHallucination(), Terraria.Player.specialistDamage, Terraria.Player.statDefense, Terraria.Player.statManaMax2, Terraria.Main.tenthAnniversaryWorld, Terraria.ModLoader.ItemLoader.UpdateEquip(), Terraria.Player.whipRangeMultiplier, and Terraria.Entity.whoAmI.
Referenced by Terraria.ModLoader.ModAccessorySlot.ApplyEquipEffects(), and Terraria.Player.UpdateEquips().