TModLoader: Terraria.Player.TentacleSpike_TrySpiking
TentacleSpike_TrySpiking()
void Terraria.Player.TentacleSpike_TrySpiking (NPC npc, Item sItem, float damage, float knockBack) inline private
Definition at line 43353 of file Player.cs.
    {
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        if (_spawnTentacleSpikes && Main.myPlayer == whoAmI && (npc == null || npc.CanBeChasedBy(this)))
        {
            Vector2 v = npc.Center - MountedCenter;
            v = v.SafeNormalize(Vector2.Zero);
            Vector2 vector = npc.Hitbox.ClosestPointInRect(MountedCenter) + v;
            Vector2 vector2 = (npc.Center - vector) * 0.8f;
            int num = Projectile.NewProjectile(GetProjectileSource_Item(sItem), vector.X, vector.Y, vector2.X, vector2.Y, 971, (int)damage, knockBack, whoAmI, 1f, npc.whoAmI);
            Main.projectile[num].StatusNPC(npc.whoAmI);
            Projectile.KillOldestJavelin(num, 971, npc.whoAmI, _tentacleSpikesMax5);
            _spawnTentacleSpikes = false;
        }
    }
References Terraria.Player._spawnTentacleSpikes, Terraria.Player._tentacleSpikesMax5, Terraria.NPC.CanBeChasedBy(), Terraria.Player.GetProjectileSource_Item(), Terraria.Entity.Hitbox, Terraria.Projectile.KillOldestJavelin(), Terraria.Player.MountedCenter, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Main.projectile, Terraria.Projectile.StatusNPC(), and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ApplyNPCOnHitEffects().