TModLoader: Terraria.Player.UpdateJumpHeight
UpdateJumpHeight()
void Terraria.Player.UpdateJumpHeight () inline
Definition at line 17863 of file Player.cs.
    {
        if (mount.Active)
        {
            jumpHeight = mount.JumpHeight(this, velocity.X);
            jumpSpeed = mount.JumpSpeed(this, velocity.X);
        }
        else
        {
            if (jumpBoost)
            {
                jumpHeight = 20;
                jumpSpeed = 6.51f;
            }
            if (empressBrooch)
            {
                jumpSpeedBoost += 1.8f;
            }
            if (frogLegJumpBoost)
            {
                jumpSpeedBoost += 2.4f;
                extraFall += 15;
            }
            if (moonLordLegs)
            {
                jumpSpeedBoost += 1.8f;
                extraFall += 10;
                jumpHeight++;
            }
            if (wereWolf)
            {
                jumpHeight += 2;
                jumpSpeed += 0.2f;
            }
            if (portableStoolInfo.IsInUse)
            {
                jumpHeight += 5;
            }
            jumpSpeed += jumpSpeedBoost;
        }
        if (sticky)
        {
            jumpHeight /= 10;
            jumpSpeed /= 5f;
        }
        if (dazed)
        {
            jumpHeight /= 5;
            jumpSpeed /= 2f;
        }
    }
References Terraria.Mount.Active, Terraria.Player.dazed, Terraria.Player.empressBrooch, Terraria.Player.extraFall, Terraria.Player.frogLegJumpBoost, Terraria.DataStructures.PortableStoolUsage.IsInUse, Terraria.Player.jumpBoost, Terraria.Mount.JumpHeight(), Terraria.Player.jumpHeight, Terraria.Mount.JumpSpeed(), Terraria.Player.jumpSpeed, Terraria.Player.jumpSpeedBoost, Terraria.Player.moonLordLegs, Terraria.Player.mount, Terraria.Player.portableStoolInfo, Terraria.Player.sticky, Terraria.Entity.velocity, and Terraria.Player.wereWolf.
Referenced by Terraria.Player.Update().