TModLoader: Terraria.Player.GetHairColor
GetHairColor()
Color Terraria.Player.GetHairColor (bool useLighting = true) inline
Definition at line 56550 of file Player.cs.
    {
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        Color color = Lighting.GetColor((int)((double)position.X + (double)width * 0.5) / 16, (int)(((double)position.Y + (double)height * 0.25) / 16.0));
        return GameShaders.Hair.GetColor(hairDye, this, useLighting ? color : Color.White);
    }
References Terraria.Lighting.GetColor(), Terraria.Graphics.Shaders.GameShaders.Hair, Terraria.Player.hairDye, Terraria.Entity.height, Terraria.Entity.position, and Terraria.Entity.width.
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup_2(), and Terraria.DataStructures.PlayerDrawSet.HeadOnlySetup().