TModLoader: Terraria.Player.GiveImmuneTimeForCollisionAttack
GiveImmuneTimeForCollisionAttack()
void Terraria.Player.GiveImmuneTimeForCollisionAttack (int time) inline
    {
        if (_timeSinceLastImmuneGet <= 20)
        {
            _immuneStrikes++;
        }
        else
        {
            _immuneStrikes = 1;
        }
        _timeSinceLastImmuneGet = 0;
        if (_immuneStrikes < 3 && (!immune || immuneTime <= time))
        {
            immune = true;
            immuneNoBlink = true;
            immuneTime = time;
        }
    }
References Terraria.Player._immuneStrikes, Terraria.Player._timeSinceLastImmuneGet, Terraria.Player.immune, Terraria.Player.immuneNoBlink, and Terraria.Player.immuneTime.
Referenced by Terraria.Player.CollideWithNPCs(), Terraria.Player.DashMovement(), Terraria.Player.JumpMovement(), and Terraria.Player.Update_NPCCollision().