TModLoader: Terraria.Player.UpdateBiomes
UpdateBiomes()
void Terraria.Player.UpdateBiomes () inline
Definition at line 14801 of file Player.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_13ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_13bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_13d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_13dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_13f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_13fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0410: Unknown result type (might be due to invalid IL or missing references)
        //IL_041e: Unknown result type (might be due to invalid IL or missing references)
        //IL_043f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0460: Unknown result type (might be due to invalid IL or missing references)
        //IL_0466: Unknown result type (might be due to invalid IL or missing references)
        //IL_047e: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_049f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0533: Unknown result type (might be due to invalid IL or missing references)
        //IL_0538: Unknown result type (might be due to invalid IL or missing references)
        //IL_053a: Unknown result type (might be due to invalid IL or missing references)
        //IL_053f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0541: Unknown result type (might be due to invalid IL or missing references)
        //IL_0546: Unknown result type (might be due to invalid IL or missing references)
        //IL_0548: Unknown result type (might be due to invalid IL or missing references)
        //IL_054d: Unknown result type (might be due to invalid IL or missing references)
        //IL_054f: Unknown result type (might be due to invalid IL or missing references)
        //IL_058c: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05af: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0624: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0600: Unknown result type (might be due to invalid IL or missing references)
        //IL_0816: Unknown result type (might be due to invalid IL or missing references)
        //IL_0823: Unknown result type (might be due to invalid IL or missing references)
        //IL_0670: Unknown result type (might be due to invalid IL or missing references)
        //IL_0647: Unknown result type (might be due to invalid IL or missing references)
        //IL_064c: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0690: Unknown result type (might be due to invalid IL or missing references)
        //IL_0695: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06db: Unknown result type (might be due to invalid IL or missing references)
        //IL_0978: Unknown result type (might be due to invalid IL or missing references)
        //IL_0995: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a49: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a55: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a76: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b25: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b90: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b63: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c42: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c48: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dbf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dfe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1003: Unknown result type (might be due to invalid IL or missing references)
        //IL_1005: Unknown result type (might be due to invalid IL or missing references)
        //IL_100c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1014: Unknown result type (might be due to invalid IL or missing references)
        Point point = base.Center.ToTileCoordinates();
        ZoneDungeon = false;
        if (Main.SceneMetrics.DungeonTileCount >= 250 && (double)base.Center.Y > Main.worldSurface * 16.0)
        {
            int num = (int)base.Center.X / 16;
            int num12 = (int)base.Center.Y / 16;
            if (Main.tile[num, num12] != null && Main.wallDungeon[Main.tile[num, num12].wall])
            {
                ZoneDungeon = true;
            }
        }
        ZoneLihzhardTemple = false;
        int num15 = (int)base.Center.X / 16;
        int num16 = (int)base.Center.Y / 16;
        if (Main.tile[num15, num16] != null && Main.tile[num15, num16].wall == 87)
        {
            ZoneLihzhardTemple = true;
        }
        Tile tileSafely = Framing.GetTileSafely(base.Center);
        if (tileSafely != null)
        {
            behindBackWall = tileSafely.wall > 0;
        }
        if (behindBackWall && ZoneDesert && (double)base.Center.Y > Main.worldSurface)
        {
            if (WallID.Sets.Conversion.Sandstone[tileSafely.wall] || WallID.Sets.Conversion.HardenedSand[tileSafely.wall])
            {
                ZoneUndergroundDesert = true;
            }
        }
        else
        {
            ZoneUndergroundDesert = false;
        }
        if (behindBackWall && (tileSafely.wall == 184 || tileSafely.wall == 180))
        {
            ZoneGranite = true;
        }
        else
        {
            ZoneGranite = false;
        }
        if (behindBackWall && (tileSafely.wall == 183 || tileSafely.wall == 178))
        {
            ZoneMarble = true;
        }
        else
        {
            ZoneMarble = false;
        }
        if (behindBackWall && (tileSafely.wall == 108 || tileSafely.wall == 86))
        {
            ZoneHive = true;
        }
        else
        {
            ZoneHive = false;
        }
        if (behindBackWall && tileSafely.wall >= 48 && tileSafely.wall <= 53)
        {
            ZoneGemCave = true;
        }
        else
        {
            ZoneGemCave = false;
        }
        bool flag = (double)(Main.screenPosition.Y / 16f) > Main.worldSurface + 50.0 && Main.screenPosition.Y / 16f < (float)(Main.maxTilesY - 330 - 100);
        ZoneShimmer = Main.SceneMetrics.EnoughTilesForShimmer && flag;
        ZoneCorrupt = Main.SceneMetrics.EnoughTilesForCorruption;
        ZoneCrimson = Main.SceneMetrics.EnoughTilesForCrimson;
        ZoneHallow = Main.SceneMetrics.EnoughTilesForHallow;
        ZoneJungle = Main.SceneMetrics.EnoughTilesForJungle && position.Y / 16f < (float)Main.UnderworldLayer;
        ZoneSnow = Main.SceneMetrics.EnoughTilesForSnow;
        ZoneDesert = Main.SceneMetrics.EnoughTilesForDesert;
        ZoneGlowshroom = Main.SceneMetrics.EnoughTilesForGlowingMushroom;
        ZoneMeteor = Main.SceneMetrics.EnoughTilesForMeteor;
        ZoneWaterCandle = Main.SceneMetrics.WaterCandleCount > 0;
        ZonePeaceCandle = Main.SceneMetrics.PeaceCandleCount > 0;
        ZoneShadowCandle = Main.SceneMetrics.ShadowCandleCount > 0;
        ZoneGraveyard = Main.SceneMetrics.EnoughTilesForGraveyard;
        UpdateGraveyard();
        if (HasGardenGnomeNearby != Main.SceneMetrics.HasGardenGnome)
        {
            luckNeedsSync = true;
            HasGardenGnomeNearby = Main.SceneMetrics.HasGardenGnome;
        }
        ZoneUnderworldHeight = point.Y > Main.UnderworldLayer;
        ZoneRockLayerHeight = point.Y <= Main.UnderworldLayer && (double)point.Y > Main.rockLayer;
        ZoneDirtLayerHeight = (double)point.Y <= Main.rockLayer && (double)point.Y > Main.worldSurface;
        ZoneOverworldHeight = (double)point.Y <= Main.worldSurface && (double)point.Y > Main.worldSurface * 0.3499999940395355;
        ZoneSkyHeight = (double)point.Y <= Main.worldSurface * 0.3499999940395355;
        ZoneBeach = WorldGen.oceanDepths(point.X, point.Y);
        ZoneRain = Main.raining && (double)point.Y <= Main.worldSurface;
        if (Main.remixWorld)
        {
            ZoneSandstorm = (double)point.Y >= Main.rockLayer && ZoneDesert && !ZoneBeach && Sandstorm.Happening;
        }
        else
        {
            ZoneSandstorm = (double)point.Y <= Main.worldSurface && ZoneDesert && !ZoneBeach && Sandstorm.Happening;
        }
        bool flag9 = (ZoneTowerStardust = false);
        bool flag3 = flag9;
        flag9 = (ZoneTowerNebula = flag3);
        bool flag4 = flag9;
        flag9 = (ZoneTowerVortex = flag4);
        bool zoneTowerSolar = flag9;
        ZoneTowerSolar = zoneTowerSolar;
        ZoneOldOneArmy = false;
        Vector2 vector = Vector2.Zero;
        Vector2 vector2 = Vector2.Zero;
        Vector2 vector3 = Vector2.Zero;
        Vector2 vector4 = Vector2.Zero;
        _ = Vector2.Zero;
        for (int i = 0; i < 200; i++)
        {
            if (!Main.npc[i].active)
            {
                continue;
            }
            if (Main.npc[i].type == 493)
            {
                if (Distance(Main.npc[i].Center) <= 4000f)
                {
                    ZoneTowerStardust = true;
                    vector4 = Main.npc[i].Center;
                }
            }
            else if (Main.npc[i].type == 507)
            {
                if (Distance(Main.npc[i].Center) <= 4000f)
                {
                    ZoneTowerNebula = true;
                    vector3 = Main.npc[i].Center;
                }
            }
            else if (Main.npc[i].type == 422)
            {
                if (Distance(Main.npc[i].Center) <= 4000f)
                {
                    ZoneTowerVortex = true;
                    vector2 = Main.npc[i].Center;
                }
            }
            else if (Main.npc[i].type == 517)
            {
                if (Distance(Main.npc[i].Center) <= 4000f)
                {
                    ZoneTowerSolar = true;
                    vector = Main.npc[i].Center;
                }
            }
            else if (Main.npc[i].type == 549 && Distance(Main.npc[i].Center) <= 4000f)
            {
                ZoneOldOneArmy = true;
                vector = Main.npc[i].Center;
            }
        }
        float num17 = 1f;
        float num18 = 1f;
        float num19 = Main.shimmerAlpha;
        if (CanSeeShimmerEffects())
        {
            num17 *= 1f;
            num18 *= 0.7f;
            if (num19 < 1f)
            {
                num19 += 0.025f;
                if (num19 > 1f)
                {
                    num19 = 1f;
                }
            }
            if (num19 >= 0.5f)
            {
                Main.shimmerDarken = MathHelper.Clamp(Main.shimmerDarken + 0.025f, 0f, 1f);
                Main.shimmerBrightenDelay = 4f;
            }
        }
        else if (num19 > 0f)
        {
            Main.shimmerDarken = MathHelper.Clamp(Main.shimmerDarken - 0.05f, 0f, 1f);
            if (Main.shimmerDarken == 0f && Main.shimmerBrightenDelay > 0f)
            {
                Main.shimmerBrightenDelay -= 1f;
            }
            if (Main.shimmerBrightenDelay == 0f)
            {
                num19 -= 0.05f;
            }
            if (num19 < 0f)
            {
                num19 = 0f;
            }
        }
        Main.shimmerAlpha = num19;
        if (Main.getGoodWorld)
        {
            bool flag5 = false;
            int num20 = NPC.FindFirstNPC(245);
            if (num20 >= 0 && Vector2.Distance(base.Center, Main.npc[num20].Center) < 2000f)
            {
                flag5 = true;
            }
            if (flag5)
            {
                num17 *= 0.6f;
                num18 *= 0.6f;
            }
            else if (ZoneLihzhardTemple)
            {
                num17 *= 0.88f;
                num18 *= 0.88f;
            }
            else if (ZoneDungeon)
            {
                num17 *= 0.94f;
                num18 *= 0.94f;
            }
        }
        if (num17 != airLightDecay)
        {
            if (airLightDecay >= num17)
            {
                airLightDecay -= 0.005f;
                if (airLightDecay < num17)
                {
                    airLightDecay = num17;
                }
            }
            else
            {
                airLightDecay += 0.005f;
                if (airLightDecay > num17)
                {
                    airLightDecay = num17;
                }
            }
        }
        if (num18 != solidLightDecay)
        {
            if (solidLightDecay >= num18)
            {
                solidLightDecay -= 0.005f;
                if (solidLightDecay < num18)
                {
                    solidLightDecay = num18;
                }
            }
            else
            {
                solidLightDecay += 0.005f;
                if (solidLightDecay > num18)
                {
                    solidLightDecay = num18;
                }
            }
        }
        bool flag6 = ZoneRain && ZoneSnow;
        if (Main.remixWorld)
        {
            flag6 = (double)(position.Y / 16f) > Main.worldSurface && Main.raining && ZoneSnow;
        }
        bool flag7 = point.Y > Main.maxTilesY - 320;
        bool flag2 = ZoneOverworldHeight && (point.X < 380 || point.X > Main.maxTilesX - 380);
        LoaderManager.Get<BiomeLoader>().UpdateBiomes(this);
        ManageSpecialBiomeVisuals("Stardust", ZoneTowerStardust, vector4 - new Vector2(0f, 10f));
        ManageSpecialBiomeVisuals("Nebula", ZoneTowerNebula, vector3 - new Vector2(0f, 10f));
        ManageSpecialBiomeVisuals("Vortex", ZoneTowerVortex, vector2 - new Vector2(0f, 10f));
        ManageSpecialBiomeVisuals("Solar", ZoneTowerSolar, vector - new Vector2(0f, 10f));
        ManageSpecialBiomeVisuals("MoonLord", NPC.AnyNPCs(398));
        ManageSpecialBiomeVisuals("BloodMoon", Main.bloodMoon || Main.SceneMetrics.BloodMoonMonolith || bloodMoonMonolithShader);
        ManageSpecialBiomeVisuals("Blizzard", Main.UseStormEffects && flag6);
        ManageSpecialBiomeVisuals("HeatDistortion", Main.UseHeatDistortion && (flag7 || ((double)point.Y < Main.worldSurface && ZoneDesert && !flag2 && !Main.raining && !Filters.Scene["Sandstorm"].IsActive())));
        if (Main.GraveyardVisualIntensity > 0f)
        {
            if (!Filters.Scene["Graveyard"].IsActive())
            {
                Filters.Scene.Activate("Graveyard", default(Vector2));
            }
            else
            {
                Filters.Scene["Graveyard"].GetShader().UseTargetPosition(base.Center);
                float progress = MathHelper.Lerp(0f, 0.75f, Main.GraveyardVisualIntensity);
                Filters.Scene["Graveyard"].GetShader().UseProgress(progress);
                Filters.Scene["Graveyard"].GetShader().UseIntensity(1.2f);
            }
        }
        else if (Filters.Scene["Graveyard"].IsActive())
        {
            Filters.Scene.Deactivate("Graveyard");
        }
        if (!Filters.Scene["Sepia"].IsActive() && dontStarveShader)
        {
            Filters.Scene.Activate("Sepia", default(Vector2));
        }
        else if (Filters.Scene["Sepia"].IsActive() && !dontStarveShader)
        {
            Filters.Scene.Deactivate("Sepia");
        }
        if (!Filters.Scene["WaterDistortion"].IsActive() && Main.WaveQuality > 0)
        {
            Filters.Scene.Activate("WaterDistortion", default(Vector2));
        }
        else if (Filters.Scene["WaterDistortion"].IsActive() && Main.WaveQuality == 0)
        {
            Filters.Scene.Deactivate("WaterDistortion");
        }
        if (Filters.Scene["WaterDistortion"].IsActive())
        {
            float num21 = (float)Main.maxTilesX * 0.5f - Math.Abs((float)point.X - (float)Main.maxTilesX * 0.5f);
            float num2 = 1f;
            float num3 = Math.Abs(Main.windSpeedCurrent);
            num2 += num3 * 1.25f;
            float num4 = MathHelper.Clamp(Main.maxRaining, 0f, 1f);
            num2 += num4 * 1.25f;
            float num5 = 0f - (MathHelper.Clamp((num21 - 380f) / 100f, 0f, 1f) * 0.5f - 0.25f);
            num2 += num5;
            float num6 = 1f - MathHelper.Clamp(3f * ((float)((double)point.Y - Main.worldSurface) / (float)(Main.rockLayer - Main.worldSurface)), 0f, 1f);
            num2 *= num6;
            float num7 = 0.9f - MathHelper.Clamp((float)(Main.maxTilesY - point.Y - 200) / 300f, 0f, 1f) * 0.9f;
            num2 += num7;
            num2 += (1f - num6) * 0.75f;
            num2 = MathHelper.Clamp(num2, 0f, 2.5f);
            Filters.Scene["WaterDistortion"].GetShader().UseIntensity(num2);
        }
        if (flag7)
        {
            float val = (float)(point.Y - (Main.maxTilesY - 320)) / 120f;
            val = Math.Min(1f, val) * 2f;
            Filters.Scene["HeatDistortion"].GetShader().UseIntensity(val);
        }
        _shaderObstructionInternalValue = Utils.Clamp(_shaderObstructionInternalValue + (float)behindBackWall.ToDirectionInt() * -0.005f, -0.1f, 1.1f);
        _stormShaderObstruction = Utils.Clamp(_shaderObstructionInternalValue, 0f, 1f);
        if (Filters.Scene["Sandstorm"].IsActive())
        {
            Filters.Scene["Sandstorm"].GetShader().UseIntensity(_stormShaderObstruction * 0.4f * Math.Min(1f, Sandstorm.Severity));
            Filters.Scene["Sandstorm"].GetShader().UseOpacity(Math.Min(1f, Sandstorm.Severity * 1.5f) * _stormShaderObstruction);
            ((SimpleOverlay)Overlays.Scene["Sandstorm"]).GetShader().UseOpacity(Math.Min(1f, Sandstorm.Severity * 1.5f) * (1f - _stormShaderObstruction));
        }
        else if (ZoneDesert && !flag2 && !Main.raining && !flag7)
        {
            Vector3 vector5 = ((Color)(ref Main.tileColor)).ToVector3();
            float num8 = (vector5.X + vector5.Y + vector5.Z) / 3f;
            float num9 = _stormShaderObstruction * 4f * Math.Max(0f, 0.5f - Main.cloudAlpha) * num8;
            Filters.Scene["HeatDistortion"].GetShader().UseIntensity(num9);
            if (num9 <= 0f)
            {
                Filters.Scene["HeatDistortion"].IsHidden = true;
            }
            else
            {
                Filters.Scene["HeatDistortion"].IsHidden = false;
            }
        }
        if (!disabledBlizzardGraphic)
        {
            try
            {
                if (flag6)
                {
                    float cloudAlpha = Main.cloudAlpha;
                    if (Main.remixWorld)
                    {
                        Main.cloudAlpha = 0.4f;
                    }
                    bool value = NPC.IsADeerclopsNearScreen();
                    _deerclopsBlizzardSmoothedEffect = MathHelper.Clamp(_deerclopsBlizzardSmoothedEffect + (float)value.ToDirectionInt() * 0.0033333334f, 0f, 1f);
                    float num10 = Math.Min(1f, Main.cloudAlpha * 2f) * _stormShaderObstruction;
                    float num11 = _stormShaderObstruction * 0.4f * Math.Min(1f, Main.cloudAlpha * 2f) * 0.9f + 0.1f;
                    num11 = MathHelper.Lerp(num11, num11 * 0.5f, _deerclopsBlizzardSmoothedEffect);
                    num10 = MathHelper.Lerp(num10, num10 * 0.5f, _deerclopsBlizzardSmoothedEffect);
                    Filters.Scene["Blizzard"].GetShader().UseIntensity(num11);
                    Filters.Scene["Blizzard"].GetShader().UseOpacity(num10);
                    ((SimpleOverlay)Overlays.Scene["Blizzard"]).GetShader().UseOpacity(1f - num10);
                    if (Main.remixWorld)
                    {
                        Main.cloudAlpha = cloudAlpha;
                    }
                }
            }
            catch
            {
                disabledBlizzardGraphic = true;
            }
        }
        if (!disabledBlizzardSound)
        {
            try
            {
                if (flag6)
                {
                    ActiveSound? activeSound5 = SoundEngine.GetActiveSound(_strongBlizzardSound);
                    ActiveSound activeSound2 = SoundEngine.GetActiveSound(_insideBlizzardSound);
                    if (activeSound5 == null)
                    {
                        _strongBlizzardSound = SoundEngine.PlayTrackedSound(in SoundID.BlizzardStrongLoop);
                    }
                    if (activeSound2 == null)
                    {
                        _insideBlizzardSound = SoundEngine.PlayTrackedSound(in SoundID.BlizzardInsideBuildingLoop);
                    }
                    SoundEngine.GetActiveSound(_strongBlizzardSound);
                    activeSound2 = SoundEngine.GetActiveSound(_insideBlizzardSound);
                }
                if (flag6)
                {
                    _blizzardSoundVolume = Math.Min(_blizzardSoundVolume + 0.01f, 1f);
                }
                else
                {
                    _blizzardSoundVolume = Math.Max(_blizzardSoundVolume - 0.01f, 0f);
                }
                float num13 = Math.Min(1f, Main.cloudAlpha * 2f) * _stormShaderObstruction;
                ActiveSound activeSound3 = SoundEngine.GetActiveSound(_strongBlizzardSound);
                ActiveSound activeSound4 = SoundEngine.GetActiveSound(_insideBlizzardSound);
                if (_blizzardSoundVolume > 0f)
                {
                    if (activeSound3 == null)
                    {
                        _strongBlizzardSound = SoundEngine.PlayTrackedSound(in SoundID.BlizzardStrongLoop);
                        activeSound3 = SoundEngine.GetActiveSound(_strongBlizzardSound);
                    }
                    activeSound3.Volume = num13 * _blizzardSoundVolume;
                    if (activeSound4 == null)
                    {
                        _insideBlizzardSound = SoundEngine.PlayTrackedSound(in SoundID.BlizzardInsideBuildingLoop);
                        activeSound4 = SoundEngine.GetActiveSound(_insideBlizzardSound);
                    }
                    activeSound4.Volume = (1f - num13) * _blizzardSoundVolume;
                }
                else
                {
                    if (activeSound3 != null)
                    {
                        activeSound3.Volume = 0f;
                    }
                    else
                    {
                        _strongBlizzardSound = SlotId.Invalid;
                    }
                    if (activeSound4 != null)
                    {
                        activeSound4.Volume = 0f;
                    }
                    else
                    {
                        _insideBlizzardSound = SlotId.Invalid;
                    }
                }
            }
            catch
            {
                disabledBlizzardSound = true;
            }
        }
        ZonePurity = InZonePurity();
        if (!dead)
        {
            Point point2 = base.Center.ToTileCoordinates();
            if (WorldGen.InWorld(point2.X, point2.Y, 1))
            {
                int num14 = 0;
                if (Main.tile[point2.X, point2.Y] != null)
                {
                    num14 = Main.tile[point2.X, point2.Y].wall;
                }
                switch (num14)
                {
                case 86:
                    AchievementsHelper.HandleSpecialEvent(this, 12);
                    break;
                case 62:
                    AchievementsHelper.HandleSpecialEvent(this, 13);
                    break;
                }
            }
            if (_funkytownAchievementCheckCooldown > 0)
            {
                _funkytownAchievementCheckCooldown--;
            }
            if (Main.specialSeedWorld)
            {
                AchievementsHelper.HandleSpecialEvent(this, 26);
            }
            if (position.Y / 16f > (float)Main.UnderworldLayer)
            {
                AchievementsHelper.HandleSpecialEvent(this, 14);
            }
            else if (_funkytownAchievementCheckCooldown == 0 && (double)(position.Y / 16f) < Main.worldSurface && ZoneGlowshroom)
            {
                AchievementsHelper.HandleSpecialEvent(this, 15);
            }
            else if (_funkytownAchievementCheckCooldown == 0 && ZoneGraveyard)
            {
                AchievementsHelper.HandleSpecialEvent(this, 18);
            }
        }
        else
        {
            _funkytownAchievementCheckCooldown = 100;
        }
        LoaderManager.Get<SceneEffectLoader>().UpdateSceneEffect(this);
    }
References Terraria.Player._blizzardSoundVolume, Terraria.Player._deerclopsBlizzardSmoothedEffect, Terraria.Player._funkytownAchievementCheckCooldown, Terraria.Player._insideBlizzardSound, Terraria.Player._shaderObstructionInternalValue, Terraria.Player._stormShaderObstruction, Terraria.Player._strongBlizzardSound, Terraria.Graphics.Effects.EffectManager< T >.Activate(), Terraria.Entity.active, Terraria.Player.airLightDecay, Terraria.NPC.AnyNPCs(), Terraria.Player.behindBackWall, Terraria.ID.SoundID.BlizzardInsideBuildingLoop, Terraria.ID.SoundID.BlizzardStrongLoop, Terraria.Main.bloodMoon, Terraria.SceneMetrics.BloodMoonMonolith, Terraria.Player.bloodMoonMonolithShader, Terraria.Player.CanSeeShimmerEffects(), Terraria.Entity.Center, Terraria.Main.cloudAlpha, Terraria.Graphics.Effects.EffectManager< T >.Deactivate(), Terraria.Player.dead, Terraria.Player.disabledBlizzardGraphic, Terraria.Player.disabledBlizzardSound, Terraria.Entity.Distance(), Terraria.Player.dontStarveShader, Terraria.SceneMetrics.DungeonTileCount, Terraria.SceneMetrics.EnoughTilesForCorruption, Terraria.SceneMetrics.EnoughTilesForCrimson, Terraria.SceneMetrics.EnoughTilesForDesert, Terraria.SceneMetrics.EnoughTilesForGlowingMushroom, Terraria.SceneMetrics.EnoughTilesForGraveyard, Terraria.SceneMetrics.EnoughTilesForHallow, Terraria.SceneMetrics.EnoughTilesForMeteor, Terraria.SceneMetrics.EnoughTilesForSnow, Terraria.NPC.FindFirstNPC(), Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.Main.getGoodWorld, Terraria.Framing.GetTileSafely(), Terraria.Main.GraveyardVisualIntensity, Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.GameContent.Events.Sandstorm.Happening, Terraria.ID.WallID.Sets.Conversion.HardenedSand, Terraria.SceneMetrics.HasGardenGnome, Terraria.Player.HasGardenGnomeNearby, Terraria.WorldGen.InWorld(), Terraria.Player.InZonePurity(), Terraria.NPC.IsADeerclopsNearScreen(), Terraria.Player.luckNeedsSync, Terraria.Player.ManageSpecialBiomeVisuals(), Terraria.Main.maxRaining, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.npc, Terraria.WorldGen.oceanDepths(), Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.Entity.position, Terraria.Main.raining, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.ID.WallID.Sets.Conversion.Sandstone, Terraria.Graphics.Effects.Filters.Scene, Terraria.Graphics.Effects.Overlays.Scene, Terraria.Main.SceneMetrics, Terraria.Main.screenPosition, Terraria.GameContent.Events.Sandstorm.Severity, Terraria.Main.shimmerAlpha, Terraria.Main.shimmerBrightenDelay, Terraria.Main.shimmerDarken, Terraria.Player.solidLightDecay, Terraria.Main.specialSeedWorld, Terraria.Main.tile, Terraria.Main.tileColor, Terraria.NPC.type, Terraria.Main.UnderworldLayer, Terraria.Player.UpdateBiomes(), Terraria.Player.UpdateGraveyard(), Terraria.Main.UseHeatDistortion, Terraria.Main.UseStormEffects, Terraria.Main.wallDungeon, Terraria.Main.WaveQuality, Terraria.Main.windSpeedCurrent, Terraria.Main.worldSurface, Terraria.Player.ZoneBeach, Terraria.Player.ZoneCorrupt, Terraria.Player.ZoneCrimson, Terraria.Player.ZoneDesert, Terraria.Player.ZoneDirtLayerHeight, Terraria.Player.ZoneDungeon, Terraria.Player.ZoneGemCave, Terraria.Player.ZoneGlowshroom, Terraria.Player.ZoneGranite, Terraria.Player.ZoneGraveyard, Terraria.Player.ZoneHallow, Terraria.Player.ZoneHive, Terraria.Player.ZoneJungle, Terraria.Player.ZoneLihzhardTemple, Terraria.Player.ZoneMarble, Terraria.Player.ZoneMeteor, Terraria.Player.ZoneOldOneArmy, Terraria.Player.ZoneOverworldHeight, Terraria.Player.ZonePeaceCandle, Terraria.Player.ZonePurity, Terraria.Player.ZoneRain, Terraria.Player.ZoneRockLayerHeight, Terraria.Player.ZoneSandstorm, Terraria.Player.ZoneShadowCandle, Terraria.Player.ZoneShimmer, Terraria.Player.ZoneSkyHeight, Terraria.Player.ZoneSnow, Terraria.Player.ZoneTowerNebula, Terraria.Player.ZoneTowerSolar, Terraria.Player.ZoneTowerStardust, Terraria.Player.ZoneTowerVortex, Terraria.Player.ZoneUndergroundDesert, Terraria.Player.ZoneUnderworldHeight, and Terraria.Player.ZoneWaterCandle.
Referenced by Terraria.Player.ForceUpdateBiomes(), Terraria.Player.Update(), and Terraria.Player.UpdateBiomes().