TModLoader: Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate
PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate()
void Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate (int typeCaches[,], int tileToCreate) inline private
    {
        if (!autoPaint && !autoActuator)
        {
            return;
        }
        int num = 0;
        int num2 = 0;
        int num3 = 11;
        int num4 = 11;
        bool flag = TileID.Sets.Platforms[Main.tile[tileTargetX, tileTargetY].type];
        bool flag2 = TileID.Sets.Platforms[Main.tile[tileTargetX, tileTargetY].type] && TileID.Sets.Platforms[tileToCreate];
        if (!Main.tileFrameImportant[Main.tile[tileTargetX, tileTargetY].type] || flag)
        {
            num = (num2 = 5);
            num3 = (num4 = 6);
        }
        for (int i = num; i < num3; i++)
        {
            for (int j = num2; j < num4; j++)
            {
                int num5 = tileTargetX - 5 + i;
                int num6 = tileTargetY - 5 + j;
                if ((!Main.tile[num5, num6].active() && typeCaches[i, j] == -1) || (Main.tile[num5, num6].active() && !flag2 && (typeCaches[i, j] == Main.tile[num5, num6].type || Main.tile[num5, num6].type != tileToCreate)))
                {
                    continue;
                }
                if (autoPaint && builderAccStatus[3] == 0)
                {
                    TryPainting(num5, num6, paintingAWall: false, applyItemAnimation: false);
                }
                if (!autoActuator || builderAccStatus[2] != 0)
                {
                    continue;
                }
                bool flag3 = Main.tileSolid[Main.tile[num5, num6].type] && !TileID.Sets.NotReallySolid[Main.tile[num5, num6].type];
                ushort type = Main.tile[num5, num6].type;
                if (type == 314 || (uint)(type - 386) <= 3u)
                {
                    flag3 = false;
                }
                if (!flag3)
                {
                    continue;
                }
                int num7 = FindItem(849);
                if (num7 > -1 && WorldGen.PlaceActuator(num5, num6))
                {
                    NetMessage.SendData(17, -1, -1, null, 8, num5, num6);
                    if (ItemLoader.ConsumeItem(inventory[num7], this))
                    {
                        inventory[num7].stack--;
                    }
                    if (inventory[num7].stack <= 0)
                    {
                        inventory[num7].SetDefaults();
                    }
                }
            }
        }
    }
References Terraria.Player.autoActuator, Terraria.Player.autoPaint, Terraria.Player.builderAccStatus, Terraria.ModLoader.ItemLoader.ConsumeItem(), Terraria.Player.FindItem(), Terraria.Player.inventory, Terraria.ID.TileID.Sets.NotReallySolid, Terraria.WorldGen.PlaceActuator(), Terraria.ID.TileID.Sets.Platforms, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, Terraria.Main.tile, Terraria.Main.tileFrameImportant, Terraria.Main.tileSolid, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, and Terraria.Player.TryPainting().
Referenced by Terraria.Player.PlaceThing_Tiles_PlaceIt(), and Terraria.Player.PlaceThing_TryReplacingTiles().