TModLoader: Terraria.Player.GetProjectileSource_OnHurt
GetProjectileSource_OnHurt()
IEntitySource Terraria.Player.GetProjectileSource_OnHurt (Entity attacker, int projectileSourceId) inline package
Definition at line 7861 of file Player.cs.
    {
        return GetSource_OnHurt(attacker, ProjectileSourceID.ToContextString(projectileSourceId));
    }
References Terraria.Player.GetSource_OnHurt(), and Terraria.ID.ProjectileSourceID.ToContextString().
Referenced by Terraria.Player.OnHurt_Part2().