TModLoader: Terraria.Player.PlayerFrame
PlayerFrame()
void Terraria.Player.PlayerFrame () inline
    {
        //IL_1635: Unknown result type (might be due to invalid IL or missing references)
        //IL_16ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_0714: Unknown result type (might be due to invalid IL or missing references)
        //IL_0719: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d83: Unknown result type (might be due to invalid IL or missing references)
        //IL_0950: Unknown result type (might be due to invalid IL or missing references)
        //IL_095f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0893: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0901: Unknown result type (might be due to invalid IL or missing references)
        //IL_0906: Unknown result type (might be due to invalid IL or missing references)
        //IL_074a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0759: Unknown result type (might be due to invalid IL or missing references)
        //IL_075e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0763: Unknown result type (might be due to invalid IL or missing references)
        //IL_076a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0781: Unknown result type (might be due to invalid IL or missing references)
        //IL_0787: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a91: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ebc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d58: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a62: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_09eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a15: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a11: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0afd: Unknown result type (might be due to invalid IL or missing references)
        //IL_18b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_18db: Unknown result type (might be due to invalid IL or missing references)
        //IL_190f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1915: Unknown result type (might be due to invalid IL or missing references)
        //IL_192c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1936: Unknown result type (might be due to invalid IL or missing references)
        //IL_193b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1753: Unknown result type (might be due to invalid IL or missing references)
        //IL_177c: Unknown result type (might be due to invalid IL or missing references)
        //IL_17b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_17b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_17cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_17dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_195f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1988: Unknown result type (might be due to invalid IL or missing references)
        //IL_19bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_19c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_19d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_19e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_19e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1800: Unknown result type (might be due to invalid IL or missing references)
        //IL_1829: Unknown result type (might be due to invalid IL or missing references)
        //IL_185d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1863: Unknown result type (might be due to invalid IL or missing references)
        //IL_187a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1884: Unknown result type (might be due to invalid IL or missing references)
        //IL_1889: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c11: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e83: Unknown result type (might be due to invalid IL or missing references)
        //IL_10fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_111f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1125: Unknown result type (might be due to invalid IL or missing references)
        //IL_114e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1158: Unknown result type (might be due to invalid IL or missing references)
        //IL_115d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d03: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d29: Unknown result type (might be due to invalid IL or missing references)
        //IL_267b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fce: Unknown result type (might be due to invalid IL or missing references)
        //IL_1291: Unknown result type (might be due to invalid IL or missing references)
        //IL_12b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_12b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_12e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_12eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_12f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_27f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_27fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_2929: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c25: Unknown result type (might be due to invalid IL or missing references)
        //IL_2968: Unknown result type (might be due to invalid IL or missing references)
        //IL_1390: Unknown result type (might be due to invalid IL or missing references)
        //IL_13ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_13e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_13f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_13f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1518: Unknown result type (might be due to invalid IL or missing references)
        //IL_1535: Unknown result type (might be due to invalid IL or missing references)
        //IL_153b: Unknown result type (might be due to invalid IL or missing references)
        //IL_14b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_14db: Unknown result type (might be due to invalid IL or missing references)
        //IL_159d: Unknown result type (might be due to invalid IL or missing references)
        //IL_15a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_15ac: Unknown result type (might be due to invalid IL or missing references)
        if (swimTime > 0)
        {
            swimTime--;
            if (!wet)
            {
                swimTime = 0;
            }
        }
        head = armor[0].headSlot;
        body = armor[1].bodySlot;
        legs = armor[2].legSlot;
        if (armor[10].headSlot >= 0)
        {
            head = armor[10].headSlot;
        }
        if (armor[11].bodySlot >= 0)
        {
            body = armor[11].bodySlot;
        }
        if (armor[12].legSlot >= 0)
        {
            legs = armor[12].legSlot;
        }
        if (!dead)
        {
            UpdateVisibleAccessories();
        }
        wearsRobe = false;
        bool somethingSpecial = false;
        SetMatchRequest request = default(SetMatchRequest);
        request.Head = head;
        request.Body = body;
        request.Legs = legs;
        request.Male = Male;
        request.ArmorSlotRequested = 1;
        int num = SetMatch(request, ref wearsRobe);
        if (num != -1)
        {
            legs = num;
        }
        request = default(SetMatchRequest);
        request.Head = head;
        request.Body = body;
        request.Legs = legs;
        request.Male = Male;
        request.ArmorSlotRequested = 2;
        num = SetMatch(request, ref somethingSpecial);
        if (num != -1)
        {
            legs = num;
        }
        request = default(SetMatchRequest);
        request.Head = head;
        request.Body = body;
        request.Legs = legs;
        request.Male = Male;
        request.ArmorSlotRequested = 0;
        num = SetMatch(request, ref somethingSpecial);
        if (num != -1)
        {
            head = num;
        }
        if (body == 93)
        {
            shield = 0;
            handoff = 0;
        }
        if (body > 0 && ArmorIDs.Body.Sets.DisableHandOnAndOffAccDraw[body])
        {
            handon = 0;
            handoff = 0;
        }
        if (body > 0 && waist > 0 && ArmorIDs.Body.Sets.DisableBeltAccDraw[body] && ArmorIDs.Waist.Sets.IsABelt[waist])
        {
            waist = 0;
        }
        if (!dead && body >= 0)
        {
            int b = (Male ? ArmorIDs.Body.Sets.IncludedCapeBack : ArmorIDs.Body.Sets.IncludedCapeBackFemale)[body];
            if (b != -1)
            {
                if (ArmorIDs.Back.Sets.DrawInBackpackLayer[b])
                {
                    backpack = b;
                    cBackpack = cBody;
                }
                else if (ArmorIDs.Back.Sets.DrawInTailLayer[b])
                {
                    tail = b;
                    cTail = cBody;
                }
                else if (back == -1)
                {
                    back = b;
                    cBack = cBody;
                }
            }
            int b2 = ArmorIDs.Body.Sets.IncludedCapeFront[body];
            if (b2 != -1 && front == -1)
            {
                front = b2;
                cFront = cBody;
            }
            ArmorIDs.Body.Sets.IncludeCapeFrontAndBackInfo includeCapeFrontAndBackInfo = ArmorIDs.Body.Sets.IncludeCapeFrontAndBack[body];
            if (!includeCapeFrontAndBackInfo.Invalid && back == -1 && front == -1)
            {
                front = includeCapeFrontAndBackInfo.frontCape;
                cFront = cBody;
                int backCape = includeCapeFrontAndBackInfo.backCape;
                if (ArmorIDs.Back.Sets.DrawInBackpackLayer[backCape])
                {
                    backpack = backCape;
                    cBackpack = cBody;
                }
                else if (ArmorIDs.Back.Sets.DrawInTailLayer[backCape])
                {
                    tail = backCape;
                    cTail = cBody;
                }
                else if (!sitting.isSitting)
                {
                    back = backCape;
                    cBack = cBody;
                }
            }
        }
        if (legs == 67)
        {
            shoe = 0;
        }
        if (legs == 140)
        {
            shoe = 0;
        }
        bool flag = false;
        if ((wereWolf || forceWerewolf) && !hideWolf)
        {
            legs = 20;
            body = 21;
            head = 38;
            flag = true;
        }
        bool flag2 = wet && !lavaWet && (!mount.Active || !mount.IsConsideredASlimeMount);
        if (merman || forceMerman)
        {
            if (!hideMerman)
            {
                head = 39;
                legs = 21;
                body = 22;
                flag = true;
            }
            if (flag2)
            {
                wings = 0;
            }
        }
        socialShadowRocketBoots = false;
        socialIgnoreLight = false;
        socialGhost = false;
        armorEffectDrawShadow = false;
        armorEffectDrawShadowSubtle = false;
        armorEffectDrawOutlines = false;
        armorEffectDrawShadowLokis = false;
        armorEffectDrawShadowBasilisk = false;
        armorEffectDrawOutlinesForbidden = false;
        armorEffectDrawShadowEOCShield = false;
        if (!isDisplayDollOrInanimate)
        {
            if (head == 101 && body == 66 && legs == 55)
            {
                socialGhost = true;
            }
            if (head == 156 && body == 66 && legs == 55)
            {
                socialGhost = true;
            }
            SetArmorEffectVisuals(this);
        }
        hermesStepSound.Style = SoundID.Run;
        hermesStepSound.IntendedCooldown = 9;
        if (head == 99 && body == 65 && legs == 54)
        {
            turtleArmor = true;
        }
        if (head == 162 && body == 170 && legs == 105)
        {
            spiderArmor = true;
        }
        ApplyArmorSoundAndDustChanges();
        if (legs == 140)
        {
            hermesStepSound.Style = SoundID.Item24;
            hermesStepSound.IntendedCooldown = 6;
        }
        if (flag)
        {
            face = -1;
            faceFlower = -1;
            faceHead = -1;
        }
        ItemLoader.PreUpdateVanitySet(this);
        if (head > 0 && face > 0)
        {
            if (ArmorIDs.Face.Sets.OverrideHelmet[face])
            {
                head = -1;
                faceHead = -1;
            }
            else if (!ArmorIDs.Face.Sets.DrawInFaceUnderHairLayer[face])
            {
                face = -1;
            }
        }
        if (head > 0 && faceHead > 0 && ArmorIDs.Head.Sets.UseAltFaceHeadDraw[head])
        {
            int b3 = ArmorIDs.Face.Sets.AltFaceHead[faceHead];
            if (b3 > 0)
            {
                faceHead = b3;
            }
        }
        if (webbed || frozen || stoned || (Main.gamePaused && !Main.gameMenu))
        {
            return;
        }
        if (head == 267 && body == 236 && (legs == 219 || legs == 220) && miscCounter % 15 == 0 && Main.rand.Next(3) == 0)
        {
            Vector2 center = base.Center;
            float num12 = 1f + Main.rand.NextFloat() * 0.5f;
            if (Main.rand.Next(2) == 0)
            {
                num12 *= -1f;
            }
            center += new Vector2(num12 * -25f, -8f);
            Dust obj = Main.dust[Dust.NewDust(center, 2, 2, 304, 0f, 0f, 100)];
            obj.rotation = Main.rand.NextFloat() * ((float)Math.PI * 2f);
            obj.alpha = 254;
            obj.velocity.X = num12 * 0.2f;
            obj.noGravity = true;
            obj.customData = this;
            obj.shader = GameShaders.Armor.GetSecondaryShader(cBody, this);
        }
        CombinedHooks.PlayerFrameEffects(this);
        if (!isDisplayDollOrInanimate)
        {
            if (((body == 68 && legs == 57 && head == 106) || (body == 74 && legs == 63 && head == 106)) && Main.rand.Next(10) == 0)
            {
                int num16 = Dust.NewDust(new Vector2(position.X - velocity.X * 2f, position.Y - 2f - velocity.Y * 2f), width, height, 43, 0f, 0f, 100, new Color(255, 0, 255), 0.3f);
                Main.dust[num16].fadeIn = 0.8f;
                Main.dust[num16].noGravity = true;
                Dust obj2 = Main.dust[num16];
                obj2.velocity *= 2f;
                Main.dust[num16].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
            }
            if (wings == 27 && wingsLogic == wings)
            {
                float num17 = 0.4f * stealth;
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, num17, num17 * 0.9f, num17 * 0.2f);
            }
            if (head == 5 && body == 5 && legs == 5)
            {
                socialShadowRocketBoots = true;
            }
            if (head == 5 && body == 5 && legs == 5 && Main.rand.Next(10) == 0)
            {
                int num18 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 14, 0f, 0f, 200, default(Color), 1.2f);
                Main.dust[num18].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
            }
            if (head == 76 && body == 49 && legs == 45)
            {
                socialShadowRocketBoots = true;
            }
            if (head == 74 && body == 48 && legs == 44)
            {
                socialShadowRocketBoots = true;
            }
            if (head == 74 && body == 48 && legs == 44 && Main.rand.Next(10) == 0)
            {
                int num19 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 14, 0f, 0f, 200, default(Color), 1.2f);
                Main.dust[num19].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
            }
            if (head == 57 && body == 37 && legs == 35)
            {
                int maxValue = 10;
                if (Math.Abs(velocity.X) + Math.Abs(velocity.Y) > 1f)
                {
                    maxValue = 2;
                }
                if (Main.rand.Next(maxValue) == 0)
                {
                    int num20 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, 115, 0f, 0f, 140, default(Color), 0.75f);
                    Main.dust[num20].noGravity = true;
                    Main.dust[num20].fadeIn = 1.5f;
                    Dust obj3 = Main.dust[num20];
                    obj3.velocity *= 0.3f;
                    Dust obj4 = Main.dust[num20];
                    obj4.velocity += velocity * 0.2f;
                    Main.dust[num20].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                }
            }
            if (head == 6 && body == 6 && legs == 6 && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > 1f && !rocketFrame)
            {
                for (int i = 0; i < 2; i++)
                {
                    int num21 = Dust.NewDust(new Vector2(position.X - velocity.X * 2f, position.Y - 2f - velocity.Y * 2f), width, height, 6, 0f, 0f, 100, default(Color), 2f);
                    Main.dust[num21].noGravity = true;
                    Main.dust[num21].noLight = true;
                    Main.dust[num21].velocity.X -= velocity.X * 0.5f;
                    Main.dust[num21].velocity.Y -= velocity.Y * 0.5f;
                    Main.dust[num21].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                }
            }
            if (head == 8 && body == 8 && legs == 8 && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > 1f)
            {
                int num22 = Dust.NewDust(new Vector2(position.X - velocity.X * 2f, position.Y - 2f - velocity.Y * 2f), width, height, 40, 0f, 0f, 50, default(Color), 1.4f);
                Main.dust[num22].noGravity = true;
                Main.dust[num22].velocity.X = velocity.X * 0.25f;
                Main.dust[num22].velocity.Y = velocity.Y * 0.25f;
                Main.dust[num22].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
            }
            if (head == 9 && body == 9 && legs == 9 && Math.Abs(velocity.X) + Math.Abs(velocity.Y) > 1f && !rocketFrame)
            {
                for (int j = 0; j < 2; j++)
                {
                    int num2 = Dust.NewDust(new Vector2(position.X - velocity.X * 2f, position.Y - 2f - velocity.Y * 2f), width, height, 6, 0f, 0f, 100, default(Color), 2f);
                    Main.dust[num2].noGravity = true;
                    Main.dust[num2].noLight = true;
                    Main.dust[num2].velocity.X -= velocity.X * 0.5f;
                    Main.dust[num2].velocity.Y -= velocity.Y * 0.5f;
                    Main.dust[num2].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                }
            }
            if (body == 18 && legs == 17 && (head == 32 || head == 33 || head == 34) && Main.rand.Next(10) == 0)
            {
                int num3 = Dust.NewDust(new Vector2(position.X - velocity.X * 2f, position.Y - 2f - velocity.Y * 2f), width, height, 43, 0f, 0f, 100, default(Color), 0.3f);
                Main.dust[num3].fadeIn = 0.8f;
                Dust obj5 = Main.dust[num3];
                obj5.velocity *= 0f;
                Main.dust[num3].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
            }
            if ((body == 24 || body == 229) && (legs == 23 || legs == 212) && (head == 43 || head == 41 || head == 42 || head == 254 || head == 255 || head == 256 || head == 257 || head == 258) && velocity.X != 0f && velocity.Y != 0f && Main.rand.Next(10) == 0)
            {
                int num4 = Dust.NewDust(new Vector2(position.X - velocity.X * 2f, position.Y - 2f - velocity.Y * 2f), width, height, 43, 0f, 0f, 100, default(Color), 0.3f);
                Main.dust[num4].fadeIn = 0.8f;
                Dust obj6 = Main.dust[num4];
                obj6.velocity *= 0f;
                Main.dust[num4].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
            }
            if (body == 36 && head == 56 && velocity.X != 0f && velocity.Y == 0f)
            {
                for (int k = 0; k < 2; k++)
                {
                    int num5 = Dust.NewDust(new Vector2(position.X, position.Y + (float)((gravDir == 1f) ? (height - 2) : (-4))), width, 6, 106, 0f, 0f, 100, default(Color), 0.1f);
                    Main.dust[num5].fadeIn = 1f;
                    Main.dust[num5].noGravity = true;
                    Dust obj7 = Main.dust[num5];
                    obj7.velocity *= 0.2f;
                    Main.dust[num5].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                }
            }
            if (body == 27 && head == 46 && legs == 26 && velocity.X != 0f && velocity.Y == 0f && miscCounter % 2 == 0)
            {
                for (int l = 0; l < 2; l++)
                {
                    int num6 = ((l != 0) ? Dust.NewDust(new Vector2(position.X + (float)(width / 2), position.Y + (float)height + gfxOffY), width / 2, 6, 76, 0f, 0f, 0, default(Color), 1.35f) : Dust.NewDust(new Vector2(position.X, position.Y + (float)height + gfxOffY), width / 2, 6, 76, 0f, 0f, 0, default(Color), 1.35f));
                    Main.dust[num6].scale *= 1f + (float)Main.rand.Next(20, 40) * 0.01f;
                    Main.dust[num6].noGravity = true;
                    Main.dust[num6].noLight = true;
                    Dust obj8 = Main.dust[num6];
                    obj8.velocity *= 0.001f;
                    Main.dust[num6].velocity.Y -= 0.003f;
                    Main.dust[num6].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                }
            }
        }
        drawingFootball = false;
        if (ShouldDrawFootball())
        {
            SetCompositeArmBack(enabled: true, CompositeArmStretchAmount.Full, (float)Math.PI / 10f * (float)direction * -1f);
            drawingFootball = true;
        }
        Item.GetDrawHitbox(HeldItem.type, this);
        bool flag3 = CanVisuallyHoldItem(HeldItem);
        bool flag4 = HeldItem.useStyle != 14;
        ItemLoader.UpdateVanitySet(this);
        if (mount.Active)
        {
            legFrameCounter = 0.0;
            legFrame.Y = legFrame.Height * 6;
            if (mount.Type == 23 || mount.Type == 45 || mount.Type == 48)
            {
                ref Rectangle reference = ref legFrame;
                _ = legFrame;
                reference.Y = 0;
            }
            if (velocity.Y != 0f)
            {
                if (mount.FlyTime > 0 && jump == 0 && controlJump && !mount.CanHover())
                {
                    if (mount.Type == 0)
                    {
                        if (direction > 0)
{
                            if (Main.rand.Next(4) == 0)
{
                                int num7 = Dust.NewDust(new Vector2(base.Center.X - 22f, position.Y + (float)height - 6f), 20, 10, 64, velocity.X * 0.25f, velocity.Y * 0.25f, 255);
                                Dust obj9 = Main.dust[num7];
                                obj9.velocity *= 0.1f;
                                Main.dust[num7].noLight = true;
                            }
                            if (Main.rand.Next(4) == 0)
{
                                int num8 = Dust.NewDust(new Vector2(base.Center.X + 12f, position.Y + (float)height - 6f), 20, 10, 64, velocity.X * 0.25f, velocity.Y * 0.25f, 255);
                                Dust obj10 = Main.dust[num8];
                                obj10.velocity *= 0.1f;
                                Main.dust[num8].noLight = true;
                            }
                        }
                        else
{
                            if (Main.rand.Next(4) == 0)
{
                                int num9 = Dust.NewDust(new Vector2(base.Center.X - 32f, position.Y + (float)height - 6f), 20, 10, 64, velocity.X * 0.25f, velocity.Y * 0.25f, 255);
                                Dust obj11 = Main.dust[num9];
                                obj11.velocity *= 0.1f;
                                Main.dust[num9].noLight = true;
                            }
                            if (Main.rand.Next(4) == 0)
{
                                int num10 = Dust.NewDust(new Vector2(base.Center.X + 2f, position.Y + (float)height - 6f), 20, 10, 64, velocity.X * 0.25f, velocity.Y * 0.25f, 255);
                                Dust obj12 = Main.dust[num10];
                                obj12.velocity *= 0.1f;
                                Main.dust[num10].noLight = true;
                            }
                        }
                    }
                    mount.TryBeginningFlight(this, 3);
                    mount.UpdateFrame(this, 3, velocity);
                    mount.TryLanding(this);
                }
                else if (wet)
                {
                    mount.UpdateFrame(this, 4, velocity);
                }
                else
                {
                    mount.TryBeginningFlight(this, 2);
                    mount.UpdateFrame(this, 2, velocity);
                    mount.TryLanding(this);
                }
            }
            else
            {
                mount.UpdateFrame(this, mount.GetIntendedGroundedFrame(this), velocity);
            }
        }
        else if (legs != 140)
        {
            if (swimTime > 0)
            {
                legFrameCounter += 2.0;
                while (legFrameCounter > 8.0)
                {
                    legFrameCounter -= 8.0;
                    legFrame.Y += legFrame.Height;
                }
                if (legFrame.Y < legFrame.Height * 7)
                {
                    legFrame.Y = legFrame.Height * 19;
                }
                else if (legFrame.Y > legFrame.Height * 19)
                {
                    legFrame.Y = legFrame.Height * 7;
                }
            }
            else if (velocity.Y != 0f || grappling[0] > -1)
            {
                legFrameCounter = 0.0;
                legFrame.Y = legFrame.Height * 5;
                if ((wings == 22 || wings == 28 || wings == 45) && ShouldDrawWingsThatAreAlwaysAnimated())
                {
                    legFrame.Y = 0;
                }
            }
            else if (velocity.X != 0f)
            {
                if ((slippy || slippy2 || windPushed) && !controlLeft && !controlRight)
                {
                    legFrameCounter = 0.0;
                    ref Rectangle reference2 = ref legFrame;
                    _ = legFrame;
                    reference2.Y = 0;
                }
                else
                {
                    legFrameCounter += (double)Math.Abs(velocity.X) * 1.3;
                    while (legFrameCounter > 8.0)
                    {
                        legFrameCounter -= 8.0;
                        legFrame.Y += legFrame.Height;
                    }
                    if (legFrame.Y < legFrame.Height * 7)
                    {
                        legFrame.Y = legFrame.Height * 19;
                    }
                    else if (legFrame.Y > legFrame.Height * 19)
                    {
                        legFrame.Y = legFrame.Height * 7;
                    }
                }
            }
            else
            {
                legFrameCounter = 0.0;
                ref Rectangle reference3 = ref legFrame;
                _ = legFrame;
                reference3.Y = 0;
            }
        }
        if (carpetFrame >= 0)
        {
            legFrameCounter = 0.0;
            ref Rectangle reference4 = ref legFrame;
            _ = legFrame;
            reference4.Y = 0;
        }
        if (sandStorm)
        {
            if (grappling[0] >= 0)
            {
                sandStorm = false;
            }
            if (miscCounter % 4 == 0 && itemAnimation == 0)
            {
                ChangeDir(direction * -1);
                if (inventory[selectedItem].holdStyle == 2)
                {
                    if (inventory[selectedItem].type == 946 || inventory[selectedItem].type == 4707)
                    {
                        itemLocation.X = position.X + (float)width * 0.5f - (float)(16 * direction);
                    }
                    if (inventory[selectedItem].type == 186)
                    {
                        itemLocation.X = position.X + (float)width * 0.5f + (float)(6 * direction);
                        itemRotation = 0.79f * (float)(-direction);
                    }
                }
            }
            legFrameCounter = 0.0;
            ref Rectangle reference5 = ref legFrame;
            _ = legFrame;
            reference5.Y = 0;
        }
        else if (itemAnimation > 0 && inventory[selectedItem].useStyle != 10 && flag4)
        {
            if (inventory[selectedItem].useStyle == 1 || inventory[selectedItem].type == 0)
            {
                if ((double)itemAnimation < (double)itemAnimationMax * 0.333)
                {
                    bodyFrame.Y = bodyFrame.Height * 3;
                }
                else if ((double)itemAnimation < (double)itemAnimationMax * 0.666)
                {
                    bodyFrame.Y = bodyFrame.Height * 2;
                }
                else
                {
                    bodyFrame.Y = bodyFrame.Height;
                }
            }
            else if (inventory[selectedItem].useStyle == 7)
            {
                if ((double)itemAnimation > (double)itemAnimationMax * 0.5)
                {
                    bodyFrame.Y = bodyFrame.Height * 3;
                }
                else
                {
                    bodyFrame.Y = bodyFrame.Height * 2;
                }
            }
            else if (inventory[selectedItem].useStyle == 2)
            {
                bodyFrame.Y = bodyFrame.Height * 3;
            }
            else if (inventory[selectedItem].useStyle == 11)
            {
                if ((double)itemAnimation > (double)itemAnimationMax * 0.5)
                {
                    bodyFrame.Y = bodyFrame.Height * 4;
                }
                else if ((double)itemAnimation > (double)itemAnimationMax * 0.15)
                {
                    bodyFrame.Y = bodyFrame.Height * 3;
                }
                else
                {
                    bodyFrame.Y = bodyFrame.Height * 2;
                }
            }
            else if (inventory[selectedItem].useStyle == 9)
            {
                bodyFrame.Y = 0;
            }
            else if (inventory[selectedItem].useStyle == 6)
            {
                float num11 = 1f - (float)itemAnimation / (float)itemAnimationMax;
                num11 *= 6f;
                if (num11 > 1f)
                {
                    num11 = 1f;
                }
                if (num11 >= 0.5f)
                {
                    bodyFrame.Y = bodyFrame.Height * 3;
                }
                else
                {
                    bodyFrame.Y = bodyFrame.Height * 2;
                }
            }
            else if (inventory[selectedItem].useStyle == 3)
            {
                if ((double)itemAnimation > (double)itemAnimationMax * 0.666)
                {
                    bodyFrame.Y = bodyFrame.Height * 3;
                }
                else
                {
                    bodyFrame.Y = bodyFrame.Height * 3;
                }
            }
            else if (inventory[selectedItem].useStyle == 4)
            {
                bodyFrame.Y = bodyFrame.Height * 2;
            }
            else if (inventory[selectedItem].useStyle == 8)
            {
                bodyFrame.Y = 0;
            }
            else if (inventory[selectedItem].useStyle == 12)
            {
                bodyFrame.Y = bodyFrame.Height * 3;
            }
            else if (inventory[selectedItem].useStyle == 13)
            {
                if ((double)itemAnimation < (double)itemAnimationMax * 0.333)
                {
                    bodyFrame.Y = bodyFrame.Height * 3;
                }
                else if ((double)itemAnimation < (double)itemAnimationMax * 0.666)
                {
                    bodyFrame.Y = bodyFrame.Height * 2;
                }
                else
                {
                    bodyFrame.Y = bodyFrame.Height;
                }
            }
            else if (inventory[selectedItem].useStyle == 5)
            {
                if (inventory[selectedItem].type == 281 || inventory[selectedItem].type == 986)
                {
                    bodyFrame.Y = bodyFrame.Height * 2;
                }
                else
                {
                    float num23 = itemRotation * (float)direction;
                    bodyFrame.Y = bodyFrame.Height * 3;
                    if ((double)num23 < -0.75)
                    {
                        bodyFrame.Y = bodyFrame.Height * 2;
                        if (gravDir == -1f)
{
                            bodyFrame.Y = bodyFrame.Height * 4;
                        }
                    }
                    if ((double)num23 > 0.6)
                    {
                        bodyFrame.Y = bodyFrame.Height * 4;
                        if (gravDir == -1f)
{
                            bodyFrame.Y = bodyFrame.Height * 2;
                        }
                    }
                }
            }
            ItemLoader.UseItemFrame(inventory[selectedItem], this);
        }
        else if (pulley)
        {
            if (pulleyDir == 2)
            {
                bodyFrame.Y = bodyFrame.Height;
            }
            else
            {
                bodyFrame.Y = bodyFrame.Height * 2;
            }
        }
        else if (flag3 && inventory[selectedItem].holdStyle == 1 && (!wet || !inventory[selectedItem].noWet || ItemID.Sets.WaterTorches[BiomeTorchHoldStyle(inventory[selectedItem].type)]) && (!happyFunTorchTime || inventory[selectedItem].createTile != 4))
        {
            bodyFrame.Y = bodyFrame.Height * 3;
        }
        else if (flag3 && inventory[selectedItem].holdStyle == 2 && (!wet || !inventory[selectedItem].noWet))
        {
            bodyFrame.Y = bodyFrame.Height * 2;
        }
        else if (flag3 && inventory[selectedItem].holdStyle == 3)
        {
            bodyFrame.Y = bodyFrame.Height * 3;
        }
        else if (flag3 && inventory[selectedItem].holdStyle == 5)
        {
            bodyFrame.Y = bodyFrame.Height * 3;
        }
        else if (flag3 && inventory[selectedItem].holdStyle == 7)
        {
            bodyFrame.Y = bodyFrame.Height * 11;
        }
        else if (flag3 && inventory[selectedItem].holdStyle == 4 && velocity.Y == 0f && gravDir == 1f)
        {
            ref Rectangle reference6 = ref bodyFrame;
            _ = bodyFrame;
            reference6.Y = 0;
        }
        else if (shieldRaised)
        {
            bodyFrame.Y = bodyFrame.Height * 10;
        }
        else if (mount.Active)
        {
            bodyFrameCounter = 0.0;
            bodyFrame.Y = bodyFrame.Height * mount.BodyFrame;
        }
        else if (grappling[0] >= 0)
        {
            sandStorm = false;
            CancelAllJumpVisualEffects();
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector(position.X + (float)width * 0.5f, position.Y + (float)height * 0.5f);
            float num13 = 0f;
            float num14 = 0f;
            for (int m = 0; m < grapCount; m++)
            {
                num13 += Main.projectile[grappling[m]].position.X + (float)(Main.projectile[grappling[m]].width / 2);
                num14 += Main.projectile[grappling[m]].position.Y + (float)(Main.projectile[grappling[m]].height / 2);
            }
            num13 /= (float)grapCount;
            num14 /= (float)grapCount;
            num13 -= vector.X;
            num14 -= vector.Y;
            if (num14 < 0f && Math.Abs(num14) > Math.Abs(num13))
            {
                bodyFrame.Y = bodyFrame.Height * 2;
                if (gravDir == -1f)
                {
                    bodyFrame.Y = bodyFrame.Height * 4;
                }
            }
            else if (num14 > 0f && Math.Abs(num14) > Math.Abs(num13))
            {
                bodyFrame.Y = bodyFrame.Height * 4;
                if (gravDir == -1f)
                {
                    bodyFrame.Y = bodyFrame.Height * 2;
                }
            }
            else
            {
                bodyFrame.Y = bodyFrame.Height * 3;
            }
        }
        else if (wet && ShouldFloatInWater)
        {
            bodyFrame.Y = bodyFrame.Height * 10;
        }
        else if (swimTime > 0)
        {
            if (swimTime > 20)
            {
                ref Rectangle reference7 = ref bodyFrame;
                _ = bodyFrame;
                reference7.Y = 0;
            }
            else if (swimTime > 10)
            {
                bodyFrame.Y = bodyFrame.Height * 5;
            }
            else
            {
                ref Rectangle reference8 = ref bodyFrame;
                _ = bodyFrame;
                reference8.Y = 0;
            }
        }
        else if (velocity.Y != 0f)
        {
            if (sliding)
            {
                bodyFrame.Y = bodyFrame.Height * 3;
            }
            else if (sandStorm || carpetFrame >= 0)
            {
                bodyFrame.Y = bodyFrame.Height * 6;
            }
            else if (eocDash > 0)
            {
                bodyFrame.Y = bodyFrame.Height * 6;
            }
            else if (wings > 0)
            {
                if (wings == 22 || wings == 28 || wings == 45)
                {
                    bodyFrame.Y = 0;
                }
                else if (velocity.Y > 0f)
                {
                    if (controlJump)
                    {
                        bodyFrame.Y = bodyFrame.Height * 6;
                    }
                    else
                    {
                        bodyFrame.Y = bodyFrame.Height * 5;
                    }
                }
                else
                {
                    bodyFrame.Y = bodyFrame.Height * 6;
                }
            }
            else
            {
                bodyFrame.Y = bodyFrame.Height * 5;
            }
            bodyFrameCounter = 0.0;
        }
        else if (velocity.X != 0f)
        {
            if (legs == 140)
            {
                bodyFrameCounter += Math.Abs(velocity.X) * 0.5f;
                while (bodyFrameCounter > 8.0)
                {
                    bodyFrameCounter -= 8.0;
                    bodyFrame.Y += bodyFrame.Height;
                }
                if (bodyFrame.Y < bodyFrame.Height * 7)
                {
                    bodyFrame.Y = bodyFrame.Height * 19;
                }
                else if (bodyFrame.Y > bodyFrame.Height * 19)
                {
                    bodyFrame.Y = bodyFrame.Height * 7;
                }
            }
            else
            {
                bodyFrameCounter += (double)Math.Abs(velocity.X) * 1.5;
                bodyFrame.Y = legFrame.Y;
            }
        }
        else
        {
            bodyFrameCounter = 0.0;
            ref Rectangle reference9 = ref bodyFrame;
            _ = bodyFrame;
            reference9.Y = 0;
        }
        if (flag3 && itemAnimation <= 0)
        {
            ItemLoader.HoldItemFrame(inventory[selectedItem], this);
        }
        if (legs == 140)
        {
            legFrameCounter = 0.0;
            legFrame.Y = legFrame.Height * (velocity.Y != 0f).ToInt();
            int num15 = bodyFrame.Y / bodyFrame.Height;
            if (Main.OffsetsPlayerHeadgear[num15].Y == 0f)
            {
                legFrame.Y = legFrame.Height * 7;
            }
            if (wings == 22 || wings == 28)
            {
                legFrame.Y = 0;
            }
        }
        if (legs == 217 && (sitting.isSitting || sleeping.isSleeping))
        {
            legFrameCounter = 0.0;
            legFrame.Y = legFrame.Height * 5;
        }
        if (head == 259 && !skipAnimatingValuesInPlayerFrame)
        {
            rabbitOrderFrame.Update();
        }
    }
References Terraria.Mount.Active, Terraria.Lighting.AddLight(), Terraria.ID.ArmorIDs.Face.Sets.AltFaceHead, Terraria.Player.ApplyArmorSoundAndDustChanges(), Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.armor, Terraria.Player.armorEffectDrawOutlines, Terraria.Player.armorEffectDrawOutlinesForbidden, Terraria.Player.armorEffectDrawShadow, Terraria.Player.armorEffectDrawShadowBasilisk, Terraria.Player.armorEffectDrawShadowEOCShield, Terraria.Player.armorEffectDrawShadowLokis, Terraria.Player.armorEffectDrawShadowSubtle, Terraria.Player.ArmorSetDye(), Terraria.Player.back, Terraria.Player.backpack, Terraria.Player.BiomeTorchHoldStyle(), Terraria.Player.body, Terraria.Mount.BodyFrame, Terraria.Player.bodyFrame, Terraria.Player.bodyFrameCounter, Terraria.Item.bodySlot, Terraria.Player.CancelAllJumpVisualEffects(), Terraria.Mount.CanHover(), Terraria.Player.CanVisuallyHoldItem(), Terraria.Player.carpetFrame, Terraria.Player.cBack, Terraria.Player.cBackpack, Terraria.Player.cBody, Terraria.Player.cFront, Terraria.Player.ChangeDir(), Terraria.Player.controlJump, Terraria.Player.controlLeft, Terraria.Player.controlRight, Terraria.Player.cTail, Terraria.Player.dead, Terraria.Entity.direction, Terraria.ID.ArmorIDs.Body.Sets.DisableBeltAccDraw, Terraria.ID.ArmorIDs.Body.Sets.DisableHandOnAndOffAccDraw, Terraria.ID.ArmorIDs.Back.Sets.DrawInBackpackLayer, Terraria.ID.ArmorIDs.Face.Sets.DrawInFaceUnderHairLayer, Terraria.Player.drawingFootball, Terraria.ID.ArmorIDs.Back.Sets.DrawInTailLayer, Terraria.Main.dust, Terraria.Player.eocDash, Terraria.Player.face, Terraria.Player.faceFlower, Terraria.Player.faceHead, Terraria.Mount.FlyTime, Terraria.Player.forceMerman, Terraria.Player.forceWerewolf, Terraria.Player.front, Terraria.Player.frozen, Terraria.Main.gameMenu, Terraria.Main.gamePaused, Terraria.Item.GetDrawHitbox(), Terraria.Mount.GetIntendedGroundedFrame(), Terraria.Player.gfxOffY, Terraria.Player.grapCount, Terraria.Player.grappling, Terraria.Player.gravDir, Terraria.Player.handoff, Terraria.Player.handon, Terraria.Player.happyFunTorchTime, Terraria.Player.head, Terraria.Item.headSlot, Terraria.Entity.height, Terraria.Player.HeldItem, Terraria.Player.hideMerman, Terraria.Player.hideWolf, Terraria.ModLoader.ItemLoader.HoldItemFrame(), Terraria.ID.ArmorIDs.Body.Sets.IncludeCapeFrontAndBack, Terraria.ID.ArmorIDs.Body.Sets.IncludedCapeBackFemale, Terraria.ID.ArmorIDs.Body.Sets.IncludedCapeFront, Terraria.Player.inventory, Terraria.ID.ArmorIDs.Waist.Sets.IsABelt, Terraria.Mount.IsConsideredASlimeMount, Terraria.Player.isDisplayDollOrInanimate, Terraria.GameContent.PlayerSittingHelper.isSitting, Terraria.GameContent.PlayerSleepingHelper.isSleeping, Terraria.ID.SoundID.Item24, Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, Terraria.Player.itemRotation, Terraria.Player.jump, Terraria.Entity.lavaWet, Terraria.Player.legFrame, Terraria.Player.legFrameCounter, Terraria.Player.legs, Terraria.Item.legSlot, Terraria.Player.Male, Terraria.Player.merman, Terraria.Player.miscCounter, Terraria.Player.mount, Terraria.Dust.NewDust(), Terraria.Main.OffsetsPlayerHeadgear, Terraria.ID.ArmorIDs.Face.Sets.OverrideHelmet, Terraria.ModLoader.CombinedHooks.PlayerFrameEffects(), Terraria.Entity.position, Terraria.ModLoader.ItemLoader.PreUpdateVanitySet(), Terraria.Main.projectile, Terraria.Player.pulley, Terraria.Player.pulleyDir, Terraria.Player.rabbitOrderFrame, Terraria.Main.rand, Terraria.Player.rocketFrame, Terraria.ID.SoundID.Run, Terraria.Player.sandStorm, Terraria.Player.selectedItem, Terraria.Player.SetArmorEffectVisuals(), Terraria.Player.SetCompositeArmBack(), Terraria.Player.SetMatch(), Terraria.Player.shield, Terraria.Player.shieldRaised, Terraria.Player.shoe, Terraria.Player.ShouldDrawFootball(), Terraria.Player.ShouldDrawWingsThatAreAlwaysAnimated(), Terraria.Player.ShouldFloatInWater, Terraria.Player.sitting, Terraria.Player.skipAnimatingValuesInPlayerFrame, Terraria.Player.sleeping, Terraria.Player.sliding, Terraria.Player.slippy, Terraria.Player.slippy2, Terraria.Player.socialGhost, Terraria.Player.socialIgnoreLight, Terraria.Player.socialShadowRocketBoots, Terraria.Player.spiderArmor, Terraria.Player.stealth, Terraria.Player.stoned, Terraria.Player.swimTime, Terraria.Player.tail, Terraria.Mount.TryBeginningFlight(), Terraria.Mount.TryLanding(), Terraria.Player.turtleArmor, Terraria.Item.type, Terraria.Mount.Type, Terraria.Player.RabbitOrderFrameHelper.Update(), Terraria.Mount.UpdateFrame(), Terraria.ModLoader.ItemLoader.UpdateVanitySet(), Terraria.Player.UpdateVisibleAccessories(), Terraria.ID.ArmorIDs.Head.Sets.UseAltFaceHeadDraw, Terraria.ModLoader.ItemLoader.UseItemFrame(), Terraria.Entity.velocity, Terraria.Player.waist, Terraria.ID.ItemID.Sets.WaterTorches, Terraria.Player.wearsRobe, Terraria.Player.webbed, Terraria.Player.wereWolf, Terraria.Entity.wet, Terraria.Entity.width, Terraria.Player.windPushed, Terraria.Player.wings, and Terraria.Player.wingsLogic.
Referenced by Terraria.GameContent.UI.Elements.UICharacter.UICharacter(), Terraria.GameContent.Animations.Segments.PlayerSegment.Draw(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerFull(), Terraria.Player.LoadPlayer(), Terraria.GameContent.UI.Elements.UICharacter.Update(), and Terraria.Player.Update().