TModLoader: Terraria.Player.Deserialize
Deserialize() [2/2]
static void Terraria.Player.Deserialize (PlayerFileData data, Player newPlayer, BinaryReader fileIO, TagCompound modData, int release, out bool gotToReadName) inline static private
    {
        //IL_0326: Unknown result type (might be due to invalid IL or missing references)
        //IL_032b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0332: Unknown result type (might be due to invalid IL or missing references)
        //IL_0337: Unknown result type (might be due to invalid IL or missing references)
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_034a: Unknown result type (might be due to invalid IL or missing references)
        //IL_034f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0356: Unknown result type (might be due to invalid IL or missing references)
        //IL_035b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0362: Unknown result type (might be due to invalid IL or missing references)
        //IL_0367: Unknown result type (might be due to invalid IL or missing references)
        //IL_036e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0373: Unknown result type (might be due to invalid IL or missing references)
        //IL_0384: Unknown result type (might be due to invalid IL or missing references)
        //IL_0389: Unknown result type (might be due to invalid IL or missing references)
        //IL_039a: Unknown result type (might be due to invalid IL or missing references)
        //IL_039f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0408: Unknown result type (might be due to invalid IL or missing references)
        //IL_040d: Unknown result type (might be due to invalid IL or missing references)
        gotToReadName = false;
        newPlayer.name = fileIO.ReadString();
        gotToReadName = true;
        if (release >= 10)
        {
            if (release >= 17)
            {
                newPlayer.difficulty = fileIO.ReadByte();
            }
            else if (fileIO.ReadBoolean())
            {
                newPlayer.difficulty = 2;
            }
        }
        if (release >= 138)
        {
            data.SetPlayTime(new TimeSpan(fileIO.ReadInt64()));
        }
        else
        {
            data.SetPlayTime(TimeSpan.Zero);
        }
        newPlayer.hair = fileIO.ReadInt32();
        if (release >= 82)
        {
            newPlayer.hairDye = fileIO.ReadByte();
        }
        if (release >= 124)
        {
            BitsByte bitsByte = fileIO.ReadByte();
            for (int i = 0; i < 8; i++)
            {
                newPlayer.hideVisibleAccessory[i] = bitsByte[i];
            }
            bitsByte = fileIO.ReadByte();
            for (int j = 0; j < 2; j++)
            {
                newPlayer.hideVisibleAccessory[j + 8] = bitsByte[j];
            }
        }
        else if (release >= 83)
        {
            BitsByte bitsByte2 = fileIO.ReadByte();
            for (int k = 0; k < 8; k++)
            {
                newPlayer.hideVisibleAccessory[k] = bitsByte2[k];
            }
        }
        if (release >= 119)
        {
            newPlayer.hideMisc = fileIO.ReadByte();
        }
        if (release <= 17)
        {
            if (newPlayer.hair == 5 || newPlayer.hair == 6 || newPlayer.hair == 9 || newPlayer.hair == 11)
            {
                newPlayer.Male = false;
            }
            else
            {
                newPlayer.Male = true;
            }
        }
        else if (release < 107)
        {
            newPlayer.Male = fileIO.ReadBoolean();
        }
        else
        {
            newPlayer.skinVariant = fileIO.ReadByte();
        }
        if (release < 161 && newPlayer.skinVariant == 7)
        {
            newPlayer.skinVariant = 9;
        }
        newPlayer.statLife = fileIO.ReadInt32();
        newPlayer.statLifeMax = fileIO.ReadInt32();
        if (newPlayer.statLifeMax > 500)
        {
            newPlayer.statLifeMax = 500;
        }
        newPlayer.statMana = fileIO.ReadInt32();
        newPlayer.statManaMax = fileIO.ReadInt32();
        if (newPlayer.statManaMax > 200)
        {
            newPlayer.statManaMax = 200;
        }
        newPlayer.ConsumedLifeCrystals = (newPlayer.statLifeMax - 100) / 20;
        newPlayer.ConsumedLifeFruit = (newPlayer.statLifeMax - 400) / 5;
        newPlayer.ConsumedManaCrystals = (newPlayer.statManaMax - 20) / 20;
        if (release >= 125)
        {
            newPlayer.extraAccessory = fileIO.ReadBoolean();
        }
        if (release >= 229)
        {
            newPlayer.unlockedBiomeTorches = fileIO.ReadBoolean();
            newPlayer.UsingBiomeTorches = fileIO.ReadBoolean();
            if (release >= 256)
            {
                newPlayer.ateArtisanBread = fileIO.ReadBoolean();
            }
            if (release >= 260)
            {
                newPlayer.usedAegisCrystal = fileIO.ReadBoolean();
                newPlayer.usedAegisFruit = fileIO.ReadBoolean();
                newPlayer.usedArcaneCrystal = fileIO.ReadBoolean();
                newPlayer.usedGalaxyPearl = fileIO.ReadBoolean();
                newPlayer.usedGummyWorm = fileIO.ReadBoolean();
                newPlayer.usedAmbrosia = fileIO.ReadBoolean();
            }
        }
        if (release >= 182)
        {
            newPlayer.downedDD2EventAnyDifficulty = fileIO.ReadBoolean();
        }
        if (release >= 128)
        {
            newPlayer.taxMoney = fileIO.ReadInt32();
        }
        if (release >= 254)
        {
            newPlayer.numberOfDeathsPVE = fileIO.ReadInt32();
        }
        if (release >= 254)
        {
            newPlayer.numberOfDeathsPVP = fileIO.ReadInt32();
        }
        newPlayer.hairColor = fileIO.ReadRGB();
        newPlayer.skinColor = fileIO.ReadRGB();
        newPlayer.eyeColor = fileIO.ReadRGB();
        newPlayer.shirtColor = fileIO.ReadRGB();
        newPlayer.underShirtColor = fileIO.ReadRGB();
        newPlayer.pantsColor = fileIO.ReadRGB();
        newPlayer.shoeColor = fileIO.ReadRGB();
        Main.player[Main.myPlayer].hairColor = newPlayer.hairColor;
        Main.player[Main.myPlayer].skinColor = newPlayer.skinColor;
        Main.player[Main.myPlayer].eyeColor = newPlayer.eyeColor;
        Main.player[Main.myPlayer].shirtColor = newPlayer.shirtColor;
        Main.player[Main.myPlayer].underShirtColor = newPlayer.underShirtColor;
        Main.player[Main.myPlayer].pantsColor = newPlayer.pantsColor;
        Main.player[Main.myPlayer].shoeColor = newPlayer.shoeColor;
        if (release >= 38)
        {
            if (release < 124)
            {
                int num = 11;
                if (release >= 81)
                {
                    num = 16;
                }
                for (int l = 0; l < num; l++)
                {
                    int num12 = l;
                    if (num12 >= 8)
                    {
                        num12 += 2;
                    }
                    newPlayer.armor[num12].netDefaults(fileIO.ReadInt32());
                    newPlayer.armor[num12].Prefix(fileIO.ReadByte());
                }
            }
            else
            {
                int num23 = 20;
                for (int m = 0; m < num23; m++)
                {
                    newPlayer.armor[m].netDefaults(fileIO.ReadInt32());
                    newPlayer.armor[m].Prefix(fileIO.ReadByte());
                }
            }
            if (release >= 47)
            {
                int num32 = 3;
                if (release >= 81)
                {
                    num32 = 8;
                }
                if (release >= 124)
                {
                    num32 = 10;
                }
                for (int n = 0; n < num32; n++)
                {
                    int num33 = n;
                    newPlayer.dye[num33].netDefaults(fileIO.ReadInt32());
                    newPlayer.dye[num33].Prefix(fileIO.ReadByte());
                }
            }
            if (release >= 58)
            {
                for (int num34 = 0; num34 < 58; num34++)
                {
                    int num35 = fileIO.ReadInt32();
                    if (num35 >= ItemID.Count)
                    {
                        newPlayer.inventory[num34].netDefaults(0);
                        fileIO.ReadInt32();
                        fileIO.ReadByte();
                        if (release >= 114)
{
                            fileIO.ReadBoolean();
                        }
                    }
                    else
                    {
                        newPlayer.inventory[num34].netDefaults(num35);
                        newPlayer.inventory[num34].stack = fileIO.ReadInt32();
                        newPlayer.inventory[num34].Prefix(fileIO.ReadByte());
                        if (release >= 114)
{
                            newPlayer.inventory[num34].favorited = fileIO.ReadBoolean();
                        }
                    }
                }
            }
            else
            {
                for (int num36 = 0; num36 < 48; num36++)
                {
                    int num37 = fileIO.ReadInt32();
                    if (num37 >= ItemID.Count)
                    {
                        newPlayer.inventory[num36].netDefaults(0);
                        fileIO.ReadInt32();
                        fileIO.ReadByte();
                    }
                    else
                    {
                        newPlayer.inventory[num36].netDefaults(num37);
                        newPlayer.inventory[num36].stack = fileIO.ReadInt32();
                        newPlayer.inventory[num36].Prefix(fileIO.ReadByte());
                    }
                }
            }
            if (release >= 117)
            {
                if (release < 136)
                {
                    for (int num2 = 0; num2 < 5; num2++)
                    {
                        if (num2 != 1)
{
                            int num3 = fileIO.ReadInt32();
                            if (num3 >= ItemID.Count)
{
                                newPlayer.miscEquips[num2].netDefaults(0);
                                fileIO.ReadByte();
                            }
                            else
{
                                newPlayer.miscEquips[num2].netDefaults(num3);
                                newPlayer.miscEquips[num2].Prefix(fileIO.ReadByte());
                            }
                            num3 = fileIO.ReadInt32();
                            if (num3 >= ItemID.Count)
{
                                newPlayer.miscDyes[num2].netDefaults(0);
                                fileIO.ReadByte();
                            }
                            else
{
                                newPlayer.miscDyes[num2].netDefaults(num3);
                                newPlayer.miscDyes[num2].Prefix(fileIO.ReadByte());
                            }
                        }
                    }
                }
                else
                {
                    for (int num4 = 0; num4 < 5; num4++)
                    {
                        int num5 = fileIO.ReadInt32();
                        if (num5 >= ItemID.Count)
{
                            newPlayer.miscEquips[num4].netDefaults(0);
                            fileIO.ReadByte();
                        }
                        else
{
                            newPlayer.miscEquips[num4].netDefaults(num5);
                            newPlayer.miscEquips[num4].Prefix(fileIO.ReadByte());
                        }
                        num5 = fileIO.ReadInt32();
                        if (num5 >= ItemID.Count)
{
                            newPlayer.miscDyes[num4].netDefaults(0);
                            fileIO.ReadByte();
                        }
                        else
{
                            newPlayer.miscDyes[num4].netDefaults(num5);
                            newPlayer.miscDyes[num4].Prefix(fileIO.ReadByte());
                        }
                    }
                }
            }
            if (release >= 58)
            {
                for (int num6 = 0; num6 < 40; num6++)
                {
                    newPlayer.bank.item[num6].netDefaults(fileIO.ReadInt32());
                    newPlayer.bank.item[num6].stack = fileIO.ReadInt32();
                    newPlayer.bank.item[num6].Prefix(fileIO.ReadByte());
                }
                for (int num7 = 0; num7 < 40; num7++)
                {
                    newPlayer.bank2.item[num7].netDefaults(fileIO.ReadInt32());
                    newPlayer.bank2.item[num7].stack = fileIO.ReadInt32();
                    newPlayer.bank2.item[num7].Prefix(fileIO.ReadByte());
                }
            }
            else
            {
                for (int num8 = 0; num8 < 20; num8++)
                {
                    newPlayer.bank.item[num8].netDefaults(fileIO.ReadInt32());
                    newPlayer.bank.item[num8].stack = fileIO.ReadInt32();
                    newPlayer.bank.item[num8].Prefix(fileIO.ReadByte());
                }
                for (int num9 = 0; num9 < 20; num9++)
                {
                    newPlayer.bank2.item[num9].netDefaults(fileIO.ReadInt32());
                    newPlayer.bank2.item[num9].stack = fileIO.ReadInt32();
                    newPlayer.bank2.item[num9].Prefix(fileIO.ReadByte());
                }
            }
            if (release >= 182)
            {
                for (int num10 = 0; num10 < 40; num10++)
                {
                    newPlayer.bank3.item[num10].netDefaults(fileIO.ReadInt32());
                    newPlayer.bank3.item[num10].stack = fileIO.ReadInt32();
                    newPlayer.bank3.item[num10].Prefix(fileIO.ReadByte());
                }
            }
            if (release >= 198)
            {
                for (int num11 = 0; num11 < 40; num11++)
                {
                    newPlayer.bank4.item[num11].netDefaults(fileIO.ReadInt32());
                    newPlayer.bank4.item[num11].stack = fileIO.ReadInt32();
                    newPlayer.bank4.item[num11].Prefix(fileIO.ReadByte());
                    if (release >= 255)
                    {
                        newPlayer.bank4.item[num11].favorited = fileIO.ReadBoolean();
                    }
                }
            }
            if (release >= 199)
            {
                newPlayer.voidVaultInfo = fileIO.ReadByte();
            }
        }
        else
        {
            for (int num13 = 0; num13 < 8; num13++)
            {
                newPlayer.armor[num13].SetDefaults(ItemID.FromLegacyName(fileIO.ReadString(), release));
                if (release >= 36)
                {
                    newPlayer.armor[num13].Prefix(fileIO.ReadByte());
                }
            }
            if (release >= 6)
            {
                for (int num14 = 8; num14 < 11; num14++)
                {
                    newPlayer.armor[num14].SetDefaults(ItemID.FromLegacyName(fileIO.ReadString(), release));
                    if (release >= 36)
                    {
                        newPlayer.armor[num14].Prefix(fileIO.ReadByte());
                    }
                }
            }
            for (int num15 = 0; num15 < 44; num15++)
            {
                newPlayer.inventory[num15].SetDefaults(ItemID.FromLegacyName(fileIO.ReadString(), release));
                newPlayer.inventory[num15].stack = fileIO.ReadInt32();
                if (release >= 36)
                {
                    newPlayer.inventory[num15].Prefix(fileIO.ReadByte());
                }
            }
            if (release >= 15)
            {
                for (int num16 = 44; num16 < 48; num16++)
                {
                    newPlayer.inventory[num16].SetDefaults(ItemID.FromLegacyName(fileIO.ReadString(), release));
                    newPlayer.inventory[num16].stack = fileIO.ReadInt32();
                    if (release >= 36)
                    {
                        newPlayer.inventory[num16].Prefix(fileIO.ReadByte());
                    }
                }
            }
            for (int num17 = 0; num17 < 20; num17++)
            {
                newPlayer.bank.item[num17].SetDefaults(ItemID.FromLegacyName(fileIO.ReadString(), release));
                newPlayer.bank.item[num17].stack = fileIO.ReadInt32();
                if (release >= 36)
                {
                    newPlayer.bank.item[num17].Prefix(fileIO.ReadByte());
                }
            }
            if (release >= 20)
            {
                for (int num18 = 0; num18 < 20; num18++)
                {
                    newPlayer.bank2.item[num18].SetDefaults(ItemID.FromLegacyName(fileIO.ReadString(), release));
                    newPlayer.bank2.item[num18].stack = fileIO.ReadInt32();
                    if (release >= 36)
                    {
                        newPlayer.bank2.item[num18].Prefix(fileIO.ReadByte());
                    }
                }
            }
        }
        if (release < 58)
        {
            for (int num19 = 40; num19 < 48; num19++)
            {
                newPlayer.inventory[num19 + 10] = newPlayer.inventory[num19].Clone();
                newPlayer.inventory[num19].SetDefaults();
            }
        }
        if (release >= 11)
        {
            int num20 = 22;
            if (release < 74)
            {
                num20 = 10;
            }
            if (release >= 252)
            {
                num20 = 44;
            }
            for (int num21 = 0; num21 < num20; num21++)
            {
                newPlayer.buffType[num21] = fileIO.ReadInt32();
                newPlayer.buffTime[num21] = fileIO.ReadInt32();
                if (newPlayer.buffType[num21] == 0)
                {
                    num21--;
                    num20--;
                }
            }
        }
        for (int num22 = 0; num22 < 200; num22++)
        {
            int num24 = fileIO.ReadInt32();
            if (num24 == -1)
            {
                break;
            }
            newPlayer.spX[num22] = num24;
            newPlayer.spY[num22] = fileIO.ReadInt32();
            newPlayer.spI[num22] = fileIO.ReadInt32();
            newPlayer.spN[num22] = fileIO.ReadString();
        }
        if (release >= 16)
        {
            newPlayer.hbLocked = fileIO.ReadBoolean();
        }
        if (release >= 115)
        {
            int num25 = 13;
            for (int num26 = 0; num26 < num25; num26++)
            {
                newPlayer.hideInfo[num26] = fileIO.ReadBoolean();
            }
        }
        if (release >= 98)
        {
            newPlayer.anglerQuestsFinished = fileIO.ReadInt32();
        }
        if (release >= 162)
        {
            for (int num27 = 0; num27 < 4; num27++)
            {
                newPlayer.DpadRadial.Bindings[num27] = fileIO.ReadInt32();
            }
        }
        if (release >= 164)
        {
            int num28 = 8;
            if (release >= 167)
            {
                num28 = 10;
            }
            if (release >= 197)
            {
                num28 = 11;
            }
            if (release >= 230)
            {
                num28 = 12;
            }
            for (int num29 = 0; num29 < num28; num29++)
            {
                newPlayer.builderAccStatus[num29] = fileIO.ReadInt32();
            }
            if (release < 210)
            {
                newPlayer.builderAccStatus[0] = 1;
            }
            if (release < 249)
            {
                bool flag = false;
                for (int num30 = 0; num30 < 58; num30++)
                {
                    if (newPlayer.inventory[num30].type == 3611)
                    {
                        flag = true;
                        break;
                    }
                }
                if (flag)
                {
                    newPlayer.builderAccStatus[1] = 1;
                }
            }
        }
        if (release >= 181)
        {
            newPlayer.bartenderQuestLog = fileIO.ReadInt32();
        }
        if (release >= 200)
        {
            newPlayer.dead = fileIO.ReadBoolean();
            if (newPlayer.dead)
            {
                newPlayer.respawnTimer = Utils.Clamp(fileIO.ReadInt32(), 0, 60000);
            }
        }
        newPlayer.lastTimePlayerWasSaved = 0L;
        if (release >= 202)
        {
            newPlayer.lastTimePlayerWasSaved = fileIO.ReadInt64();
        }
        else
        {
            newPlayer.lastTimePlayerWasSaved = DateTime.UtcNow.ToBinary();
        }
        if (release >= 206)
        {
            newPlayer.golferScoreAccumulated = fileIO.ReadInt32();
        }
        if (release >= 218)
        {
            newPlayer.creativeTracker.Load(fileIO, release);
        }
        if (release >= 214)
        {
            newPlayer.LoadTemporaryItemSlotContents(fileIO);
        }
        newPlayer.savedPerPlayerFieldsThatArentInThePlayerClass = new SavedPlayerDataWithAnnoyingRules();
        CreativePowerManager.Instance.ResetDataForNewPlayer(newPlayer);
        if (release >= 220)
        {
            CreativePowerManager.Instance.LoadToPlayer(newPlayer, fileIO, release);
        }
        if (release >= 253)
        {
            BitsByte bitsByte3 = fileIO.ReadByte();
            newPlayer.unlockedSuperCart = bitsByte3[0];
            newPlayer.enabledSuperCart = bitsByte3[1];
        }
        else
        {
            newPlayer.unlockedSuperCart = newPlayer.HasItemInAnyInventory(3353);
        }
        if (release >= 262)
        {
            int value = fileIO.ReadInt32();
            newPlayer.CurrentLoadoutIndex = Utils.Clamp(value, 0, newPlayer.Loadouts.Length - 1);
            for (int num31 = 0; num31 < newPlayer.Loadouts.Length; num31++)
            {
                newPlayer.Loadouts[num31].Deserialize(fileIO, release);
            }
        }
        if (modData != null)
        {
            PlayerIO.Load(newPlayer, modData);
        }
        LoadPlayer_LastMinuteFixes(newPlayer);
    }
References Terraria.ID.ItemID.Count, Terraria.Player.eyeColor, Terraria.ID.ItemID.FromLegacyName(), Terraria.Player.hairColor, Terraria.GameContent.Creative.CreativePowerManager.Instance, Terraria.ModLoader.IO.PlayerIO.Load(), Terraria.Player.LoadPlayer_LastMinuteFixes(), Terraria.Main.myPlayer, Terraria.Player.pantsColor, Terraria.Main.player, Terraria.IO.PlayerFileData.SetPlayTime(), Terraria.Player.shirtColor, Terraria.Player.shoeColor, Terraria.Player.skinColor, and Terraria.Player.underShirtColor.