TModLoader: Terraria.Player.WingAirLogicTweaks
WingAirLogicTweaks()
void Terraria.Player.WingAirLogicTweaks () inline private
Definition at line 27111 of file Player.cs.
    {
        if (wingsLogic < 1)
        {
            return;
        }
        WingStats wingStats = GetWingStats(wingsLogic);
        bool flag = TryingToHoverDown && controlJump && wingTime > 0f;
        if (wingStats.HasDownHoverStats && flag)
        {
            if (wingStats.DownHoverSpeedOverride != -1f)
            {
                accRunSpeed = wingStats.DownHoverSpeedOverride;
            }
            runAcceleration *= wingStats.DownHoverAccelerationMult;
        }
        else
        {
            if (wingStats.AccRunSpeedOverride != -1f && wingStats.AccRunSpeedOverride > accRunSpeed)
            {
                accRunSpeed = wingStats.AccRunSpeedOverride;
            }
            runAcceleration *= wingStats.AccRunAccelerationMult;
        }
        if (wingsLogic == 45 && (float)timeSinceLastDashStarted >= 60f)
        {
            runSlowdown *= 6f;
        }
        ItemLoader.HorizontalWingSpeeds(this);
    }
References Terraria.Player.accRunSpeed, Terraria.Player.controlJump, Terraria.Player.GetWingStats(), Terraria.ModLoader.ItemLoader.HorizontalWingSpeeds(), Terraria.Player.runAcceleration, Terraria.Player.runSlowdown, Terraria.Player.timeSinceLastDashStarted, Terraria.Player.TryingToHoverDown, Terraria.Player.wingsLogic, and Terraria.Player.wingTime.
Referenced by Terraria.Player.Update().