TModLoader: Terraria.Player.GetManaCost
GetManaCost()
int Terraria.Player.GetManaCost (Item item) inline
Calculates the mana needed to use the given item.
Parameters
item The item to check.
Returns
The amount of mana needed to use item . Cannot be less than 0.
Definition at line 58616 of file Player.cs.
    {
        float reduce = manaCost;
        float mult = 1f;
        if (spaceGun && ItemID.Sets.IsSpaceGun[item.type])
        {
            mult = 0f;
        }
        if (item.type == 3852 && altFunctionUse == 2)
        {
            mult = 2f;
        }
        CombinedHooks.ModifyManaCost(this, item, ref reduce, ref mult);
        int mana = (int)((float)item.mana * reduce * mult);
        if (mana < 0)
        {
            return 0;
        }
        return mana;
    }
References Terraria.Player.altFunctionUse, Terraria.ID.ItemID.Sets.IsSpaceGun, Terraria.Player.manaCost, Terraria.ModLoader.CombinedHooks.ModifyManaCost(), Terraria.Player.spaceGun, and Terraria.Item.type.
Referenced by Terraria.Player.CheckMana(), and Terraria.Player.ItemCheck_ApplyManaRegenDelay().