TModLoader: Terraria.Player.Yoraiz0rEye
Yoraiz0rEye()
void Terraria.Player.Yoraiz0rEye () inline
Definition at line 10448 of file Player.cs.
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        //IL_0283: Unknown result type (might be due to invalid IL or missing references)
        //IL_0288: Unknown result type (might be due to invalid IL or missing references)
        //IL_028d: Unknown result type (might be due to invalid IL or missing references)
        //IL_028f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0299: Unknown result type (might be due to invalid IL or missing references)
        //IL_029e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0217: Unknown result type (might be due to invalid IL or missing references)
        //IL_0225: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_0243: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_026a: Unknown result type (might be due to invalid IL or missing references)
        //IL_042a: Unknown result type (might be due to invalid IL or missing references)
        //IL_042c: Unknown result type (might be due to invalid IL or missing references)
        //IL_043a: Unknown result type (might be due to invalid IL or missing references)
        //IL_043c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_037e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0397: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0408: Unknown result type (might be due to invalid IL or missing references)
        //IL_040e: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03da: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0468: Unknown result type (might be due to invalid IL or missing references)
        //IL_0481: Unknown result type (might be due to invalid IL or missing references)
        //IL_0487: Unknown result type (might be due to invalid IL or missing references)
        //IL_0495: Unknown result type (might be due to invalid IL or missing references)
        //IL_0497: Unknown result type (might be due to invalid IL or missing references)
        //IL_049f: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b6: Unknown result type (might be due to invalid IL or missing references)
        int num = 0;
        num += bodyFrame.Y / 56;
        if (num >= Main.OffsetsPlayerHeadgear.Length)
        {
            num = 0;
        }
        Vector2 vector = Main.OffsetsPlayerHeadgear[num];
        vector *= Directions;
        Vector2 vector2 = new Vector2((float)(width / 2), (float)(height / 2)) + vector + (MountedCenter - base.Center);
        sitting.GetSittingOffsetInfo(this, out var posOffset, out var seatAdjustment);
        vector2 += posOffset + new Vector2(0f, seatAdjustment);
        if (face == 19)
        {
            vector2.Y -= 5f * gravDir;
        }
        if (head == 276)
        {
            vector2.X += 2.5f * (float)direction;
        }
        if (mount.Active && mount.Type == 52)
        {
            vector2.X += 14f * (float)direction;
            vector2.Y -= 2f * gravDir;
        }
        float y = -11.5f * gravDir;
        Vector2 vector3 = new Vector2((float)(3 * direction - ((direction == 1) ? 1 : 0)), y) + Vector2.UnitY * gfxOffY + vector2;
        Vector2 vector4 = new Vector2((float)(3 * shadowDirection[1] - ((direction == 1) ? 1 : 0)), y) + vector2;
        Vector2 vector5 = Vector2.Zero;
        if (mount.Active && mount.Cart)
        {
            int num2 = Math.Sign(velocity.X);
            if (num2 == 0)
            {
                num2 = direction;
            }
            vector5 = Utils.RotatedBy(new Vector2(MathHelper.Lerp(0f, -8f, fullRotation / ((float)Math.PI / 4f)), MathHelper.Lerp(0f, 2f, Math.Abs(fullRotation / ((float)Math.PI / 4f)))), fullRotation);
            if (num2 == Math.Sign(fullRotation))
            {
                vector5 *= MathHelper.Lerp(1f, 0.6f, Math.Abs(fullRotation / ((float)Math.PI / 4f)));
            }
        }
        if (fullRotation != 0f)
        {
            vector3 = vector3.RotatedBy(fullRotation, fullRotationOrigin);
            vector4 = vector4.RotatedBy(fullRotation, fullRotationOrigin);
        }
        float num3 = 0f;
        Vector2 vector6 = position + vector3 + vector5;
        Vector2 vector7 = oldPosition + vector4 + vector5;
        vector7.Y -= num3 / 2f;
        vector6.Y -= num3 / 2f;
        float num4 = 1f;
        switch (yoraiz0rEye % 10)
        {
        case 1:
            return;
        case 2:
            num4 = 0.5f;
            break;
        case 3:
            num4 = 0.625f;
            break;
        case 4:
            num4 = 0.75f;
            break;
        case 5:
            num4 = 0.875f;
            break;
        case 6:
            num4 = 1f;
            break;
        case 7:
            num4 = 1.1f;
            break;
        }
        Color newColor;
        if (yoraiz0rEye < 7)
        {
            newColor = Main.hslToRgb(Main.rgbToHsl(eyeColor).X, 1f, 0.5f);
            DelegateMethods.v3_1 = ((Color)(ref newColor)).ToVector3() * 0.5f * num4;
            if (velocity != Vector2.Zero)
            {
                Utils.PlotTileLine(base.Center, base.Center + velocity * 2f, 4f, DelegateMethods.CastLightOpen);
            }
            else
            {
                Utils.PlotTileLine(base.Left, base.Right, 4f, DelegateMethods.CastLightOpen);
            }
        }
        int num5 = (int)Vector2.Distance(vector6, vector7) / 3 + 1;
        if (Vector2.Distance(vector6, vector7) % 3f != 0f)
        {
            num5++;
        }
        for (float num6 = 1f; num6 <= (float)num5; num6 += 1f)
        {
            Dust[] dust = Main.dust;
            Vector2 center = base.Center;
            newColor = default(Color);
            Dust obj = dust[Dust.NewDust(center, 0, 0, 182, 0f, 0f, 0, newColor)];
            obj.position = Vector2.Lerp(vector7, vector6, num6 / (float)num5);
            obj.noGravity = true;
            obj.velocity = Vector2.Zero;
            obj.customData = this;
            obj.scale = num4;
            obj.shader = GameShaders.Armor.GetSecondaryShader(cYorai, this);
        }
    }
References Terraria.Mount.Active, Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Mount.Cart, Terraria.DelegateMethods.CastLightOpen(), Terraria.Player.cYorai, Terraria.Entity.direction, Terraria.Player.Directions, Terraria.Main.dust, Terraria.Player.eyeColor, Terraria.Player.face, Terraria.Player.fullRotation, Terraria.Player.fullRotationOrigin, Terraria.GameContent.PlayerSittingHelper.GetSittingOffsetInfo(), Terraria.Player.gfxOffY, Terraria.Player.gravDir, Terraria.Player.head, Terraria.Entity.height, Terraria.Main.hslToRgb(), Terraria.Player.mount, Terraria.Player.MountedCenter, Terraria.Dust.NewDust(), Terraria.Main.OffsetsPlayerHeadgear, Terraria.Entity.oldPosition, Terraria.Utils.PlotTileLine(), Terraria.Entity.position, Terraria.Main.rgbToHsl(), Terraria.Utils.RotatedBy(), Terraria.Player.shadowDirection, Terraria.Player.sitting, Terraria.Mount.Type, Terraria.Entity.velocity, Terraria.Entity.width, and Terraria.Player.yoraiz0rEye.
Referenced by Terraria.Player.Update().