TModLoader: Terraria.Player.LimitPointToPlayerReachableArea
LimitPointToPlayerReachableArea()
void Terraria.Player.LimitPointToPlayerReachableArea (ref Vector2 pointPoisition) inline
Definition at line 45170 of file Player.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        Vector2 center = base.Center;
        Vector2 val = pointPoisition - center;
        float num = Math.Abs(val.X);
        float num2 = Math.Abs(val.Y);
        float num3 = 1f;
        if (num > 960f)
        {
            float num4 = 960f / num;
            if (num3 > num4)
            {
                num3 = num4;
            }
        }
        if (num2 > 600f)
        {
            float num5 = 600f / num2;
            if (num3 > num5)
            {
                num3 = num5;
            }
        }
        Vector2 vector2 = val * num3;
        pointPoisition = center + vector2;
    }
Referenced by Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Player.FindSentryRestingSpot(), Terraria.Player.GetFarthestSpawnPositionOnLine(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_UseTeleportRod(), and Terraria.Player.SpawnMinionOnCursor().