TModLoader: Terraria.Player.MakeFloorDust
MakeFloorDust()
void Terraria.Player.MakeFloorDust (bool Falling, int type, int paintColor) inline private
Definition at line 22127 of file Player.cs.
    {
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0322: Unknown result type (might be due to invalid IL or missing references)
        //IL_0431: Unknown result type (might be due to invalid IL or missing references)
        //IL_044b: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0701: Unknown result type (might be due to invalid IL or missing references)
        //IL_061b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0625: Unknown result type (might be due to invalid IL or missing references)
        //IL_062a: Unknown result type (might be due to invalid IL or missing references)
        if (type == 659 || type == 667)
        {
            bool flag = true;
            if (!Falling)
            {
                float num = Math.Abs(velocity.X) / 3f;
                if ((float)Main.rand.Next(100) > num * 50f)
                {
                    flag = false;
                }
            }
            if (!flag)
            {
                return;
            }
            Vector2 positionInWorld = new Vector2(position.X, position.Y + (float)height - 2f) + new Vector2((float)width * Main.rand.NextFloat(), 6f * Main.rand.NextFloat());
            Vector2 movementVector = Main.rand.NextVector2Circular(0.8f, 0.8f);
            if (movementVector.Y > 0f)
            {
                movementVector.Y *= -1f;
            }
            ParticleOrchestrator.RequestParticleSpawn(clientOnly: true, ParticleOrchestraType.ShimmerBlock, new ParticleOrchestraSettings
            {
                PositionInWorld = positionInWorld,
                MovementVector = movementVector
            }, whoAmI);
        }
        if (!TileLoader.HasWalkDust(type) && type != 147 && type != 25 && type != 53 && type != 189 && type != 0 && type != 123 && type != 57 && type != 112 && type != 116 && type != 196 && type != 193 && type != 195 && type != 197 && type != 199 && type != 229 && type != 234 && type != 371 && type != 460 && type != 666)
        {
            return;
        }
        int num2 = 1;
        if (Falling)
        {
            num2 = 20;
            if (type == 666)
            {
                SoundEngine.PlaySound(SoundID.Item177, (int)base.Center.X, (int)base.Bottom.Y);
            }
        }
        for (int i = 0; i < num2; i++)
        {
            bool flag2 = true;
            int num3 = 76;
            if (type == 666)
            {
                if (paintColor != 0)
                {
                    break;
                }
                num3 = 322;
            }
            if (type == 53)
            {
                num3 = 32;
            }
            if (type == 189)
            {
                num3 = 16;
            }
            if (type == 0)
            {
                num3 = 0;
            }
            if (type == 123)
            {
                num3 = 53;
            }
            if (type == 57)
            {
                num3 = 36;
            }
            if (type == 112)
            {
                num3 = 14;
            }
            if (type == 234)
            {
                num3 = 122;
            }
            if (type == 116)
            {
                num3 = 51;
            }
            if (type == 196)
            {
                num3 = 108;
            }
            if (type == 193)
            {
                num3 = 4;
            }
            if (type == 195 || type == 199)
            {
                num3 = 5;
            }
            if (type == 197)
            {
                num3 = 4;
            }
            if (type == 229)
            {
                num3 = 153;
            }
            if (type == 371)
            {
                num3 = 243;
            }
            if (type == 460)
            {
                num3 = 108;
            }
            if (type == 25)
            {
                num3 = 37;
            }
            if (num3 == 32 && Main.rand.Next(2) == 0)
            {
                flag2 = false;
            }
            if (num3 == 14 && Main.rand.Next(2) == 0)
            {
                flag2 = false;
            }
            if (num3 == 51 && Main.rand.Next(2) == 0)
            {
                flag2 = false;
            }
            if (num3 == 36 && Main.rand.Next(2) == 0)
            {
                flag2 = false;
            }
            if (num3 == 0 && Main.rand.Next(3) != 0)
            {
                flag2 = false;
            }
            if (num3 == 53 && Main.rand.Next(3) != 0)
            {
                flag2 = false;
            }
            Color newColor = default(Color);
            if (type == 193)
            {
                ((Color)(ref newColor))._002Ector(30, 100, 255, 100);
            }
            if (type == 197)
            {
                ((Color)(ref newColor))._002Ector(97, 200, 255, 100);
            }
            if (type == 460)
            {
                ((Color)(ref newColor))._002Ector(100, 150, 130, 100);
            }
            TileLoader.WalkDust(type, ref num3, ref flag2, ref newColor);
            if (!Falling)
            {
                float num4 = Math.Abs(velocity.X) / 3f;
                if ((float)Main.rand.Next(100) > num4 * 100f)
                {
                    flag2 = false;
                }
            }
            if (!flag2)
            {
                continue;
            }
            float num5 = velocity.X;
            if (num5 > 6f)
            {
                num5 = 6f;
            }
            if (num5 < -6f)
            {
                num5 = -6f;
            }
            if (!(velocity.X != 0f || Falling))
            {
                continue;
            }
            int num6 = Dust.NewDust(new Vector2(position.X, position.Y + (float)height - 2f), width, 6, num3, 0f, 0f, 50, newColor);
            if (gravDir == -1f)
            {
                Main.dust[num6].position.Y -= height + 4;
            }
            if (num3 == 76)
            {
                Main.dust[num6].scale += (float)Main.rand.Next(3) * 0.1f;
                Main.dust[num6].noLight = true;
            }
            if (num3 == 16 || num3 == 108 || num3 == 153)
            {
                Main.dust[num6].scale += (float)Main.rand.Next(6) * 0.1f;
            }
            if (num3 == 37)
            {
                Main.dust[num6].scale += 0.25f;
                Main.dust[num6].alpha = 50;
            }
            if (num3 == 5)
            {
                Main.dust[num6].scale += (float)Main.rand.Next(2, 8) * 0.1f;
            }
            Main.dust[num6].noGravity = true;
            if (num3 == 322)
            {
                if (Main.rand.Next(4) == 0)
                {
                    Main.dust[num6].noGravity = false;
                    Main.dust[num6].scale *= 1.1f;
                }
                else
                {
                    Main.dust[num6].scale *= 1.2f;
                }
            }
            if (num2 > 1)
            {
                Main.dust[num6].velocity.X *= 1.2f;
                Main.dust[num6].velocity.Y *= 0.8f;
                Main.dust[num6].velocity.Y -= 1f;
                Dust obj = Main.dust[num6];
                obj.velocity *= 0.8f;
                Main.dust[num6].scale += (float)Main.rand.Next(3) * 0.1f;
                Main.dust[num6].velocity.X = (Main.dust[num6].position.X - (position.X + (float)(width / 2))) * 0.2f;
                if (Main.dust[num6].velocity.Y > 0f)
                {
                    Main.dust[num6].velocity.Y *= -1f;
                }
                Main.dust[num6].velocity.X += num5 * 0.3f;
            }
            else
            {
                Dust obj2 = Main.dust[num6];
                obj2.velocity *= 0.2f;
            }
            Main.dust[num6].position.X -= num5 * 1f;
            if (gravDir == -1f)
            {
                Main.dust[num6].velocity.Y *= -1f;
            }
        }
    }
References Terraria.Dust.alpha, Terraria.Main.dust, Terraria.Player.gravDir, Terraria.ModLoader.TileLoader.HasWalkDust(), Terraria.Entity.height, Terraria.ID.SoundID.Item177, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Dust.position, Terraria.Entity.position, Terraria.Main.rand, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Dust.scale, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.ModLoader.TileLoader.WalkDust(), Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.FloorVisuals().