TModLoader: Terraria.Player.TryRecalculatingTorchLuck
TryRecalculatingTorchLuck()
void Terraria.Player.TryRecalculatingTorchLuck () inline private
Definition at line 16173 of file Player.cs.
    {
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        if (happyFunTorchTime)
        {
            luckyTorchCounter = 0;
            TorchAttack();
            return;
        }
        if (torchGodCooldown > 0)
        {
            torchGodCooldown--;
        }
        Vector2 nextTorchLuckCheckCenter = _nextTorchLuckCheckCenter;
        if (((double)nextTorchLuckCheckCenter.Y < Main.worldSurface * 16.0) | dead)
        {
            UpdateTorchLuck_ConsumeCountersAndCalculate();
            return;
        }
        int num = 1;
        int num2 = 40;
        int num3 = (int)nextTorchLuckCheckCenter.Y / 16 - num2;
        int value = (int)nextTorchLuckCheckCenter.X / 16 - num2;
        int value2 = (int)nextTorchLuckCheckCenter.X / 16 + num2;
        value = Utils.Clamp(value, 10, Main.maxTilesX - 10);
        value2 = Utils.Clamp(value2, 10, Main.maxTilesX - 10);
        for (int i = 0; i < num; i++)
        {
            int num4 = num3 + i + luckyTorchCounter * num;
            if (num4 < 10 || num4 > Main.maxTilesY - 10)
            {
                continue;
            }
            for (int j = value; j <= value2; j++)
            {
                Tile tile = Main.tile[j, num4];
                if (tile == null)
                {
                    return;
                }
                if (tile.type >= TileID.Count)
                {
                    if (tile.active() && TileID.Sets.Torch[tile.type])
                    {
                        NearbyModTorch.Add(tile.type);
                    }
                }
                else
                {
                    if (!tile.active() || tile.type != 4 || tile.frameX < 0 || tile.frameY < 0)
                    {
                        continue;
                    }
                    if (tile.frameX < 66)
                    {
                        nearbyTorches++;
                    }
                    int num5 = tile.frameY / 22;
                    if (num5 < TorchID.Count)
                    {
                        nearbyTorch[num5] = true;
                        if (num5 == 17 && (tile.liquid == 0 || tile.liquidType() != 0))
{
                            dryCoralTorch = true;
                        }
                    }
                }
            }
            if (num4 >= (int)nextTorchLuckCheckCenter.Y / 16 + num2)
            {
                UpdateTorchLuck_ConsumeCountersAndCalculate();
                return;
            }
        }
        luckyTorchCounter++;
    }
References Terraria.Player._nextTorchLuckCheckCenter, Terraria.Tile.active(), Terraria.ID.TileID.Count, Terraria.ID.TorchID.Count, Terraria.Player.dead, Terraria.Player.dryCoralTorch, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Player.happyFunTorchTime, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Player.luckyTorchCounter, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Player.NearbyModTorch, Terraria.Player.nearbyTorch, Terraria.Player.nearbyTorches, Terraria.Main.tile, Terraria.ID.TileID.Sets.Torch, Terraria.Player.TorchAttack(), Terraria.Player.torchGodCooldown, Terraria.Tile.type, Terraria.Player.UpdateTorchLuck_ConsumeCountersAndCalculate(), and Terraria.Main.worldSurface.
Referenced by Terraria.Player.UpdateLuckFactors().