TModLoader: Terraria.Player.TileInteractionsMouseOver_Containers
TileInteractionsMouseOver_Containers()
void Terraria.Player.TileInteractionsMouseOver_Containers (int myX, int myY) inline private
    {
        LocalizedText[] array = Lang.chestType;
        int[] array2 = Chest.chestTypeToIcon;
        Tile tile = Main.tile[myX, myY];
        if (tile.type == 467)
        {
            array = Lang.chestType2;
            array2 = Chest.chestTypeToIcon2;
        }
        int num = myX;
        int num2 = myY;
        if (tile.frameX % 36 != 0)
        {
            num--;
        }
        if (tile.frameY % 36 != 0)
        {
            num2--;
        }
        int num3 = Chest.FindChest(num, num2);
        cursorItemIconID = -1;
        if (num3 < 0)
        {
            cursorItemIconText = array[0].Value;
        }
        else
        {
            if (Main.chest[num3].name != "")
            {
                cursorItemIconText = Main.chest[num3].name;
            }
            else
            {
                cursorItemIconText = array[tile.frameX / 36].Value;
            }
            if (cursorItemIconText == array[tile.frameX / 36].Value)
            {
                cursorItemIconID = array2[tile.frameX / 36];
                cursorItemIconText = "";
            }
        }
        if (cursorItemIconID == 3988)
        {
            cursorItemIconID = 306;
        }
        noThrow = 2;
        cursorItemIconEnabled = true;
    }
References Terraria.Main.chest, Terraria.Lang.chestType, Terraria.Lang.chestType2, Terraria.Chest.chestTypeToIcon, Terraria.Chest.chestTypeToIcon2, Terraria.Player.cursorItemIconEnabled, Terraria.Player.cursorItemIconID, Terraria.Player.cursorItemIconText, Terraria.Chest.FindChest(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Chest.name, Terraria.Player.noThrow, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Player.TileInteractionsCheckLongDistance(), and Terraria.Player.TileInteractionsMouseOver().