TModLoader: Terraria.Player.OnHurt_Part1
OnHurt_Part1()
void Terraria.Player.OnHurt_Part1 (HurtInfo info) inline private
    {
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        int hitDirection = info.HitDirection;
        if (whoAmI == Main.myPlayer && panic)
        {
            AddBuff(63, 480);
        }
        if (whoAmI == Main.myPlayer && setSquireT2)
        {
            AddBuff(205, 300);
        }
        stealth = 1f;
        if (Main.netMode == 1)
        {
            NetMessage.SendData(84, -1, -1, null, whoAmI);
        }
        if (whoAmI == Main.myPlayer)
        {
            Main.NotifyOfEvent(GameNotificationType.Damage);
            if (hasFootball)
            {
                for (int i = 0; i < 59; i++)
                {
                    if (inventory[i].stack > 0 && inventory[i].type == 4743)
                    {
                        Projectile.NewProjectile(GetProjectileSource_Misc(12), base.Center, new Vector2((float)(-hitDirection * 4), -6f), 861, 0, 0f, whoAmI, 0f, 1f);
                        inventory[i].SetDefaults();
                        if (i == 58)
{
                            Main.mouseItem = new Item();
                        }
                    }
                }
            }
        }
        if (inventory[selectedItem].type == 4790 || inventory[selectedItem].type == 4788 || inventory[selectedItem].type == 4789)
        {
            for (int j = 0; j < 1000; j++)
            {
                if (Main.projectile[j].active && Main.projectile[j].owner == whoAmI && (Main.projectile[j].type == 879 || Main.projectile[j].type == 877 || Main.projectile[j].type == 878))
                {
                    Main.projectile[j].active = false;
                }
            }
        }
        if (channel && inventory[selectedItem].InterruptChannelOnHurt)
        {
            channel = false;
        }
        if (itemAnimation > 0 && inventory[selectedItem].StopAnimationOnHurt)
        {
            channel = false;
            itemAnimation = 0;
            itemAnimationMax = 0;
        }
        if (!invis)
        {
            return;
        }
        for (int k = 0; k < maxBuffs; k++)
        {
            if (buffType[k] == 10)
            {
                DelBuff(k);
            }
        }
    }
References Terraria.Player.AddBuff(), Terraria.Player.buffType, Terraria.Player.channel, Terraria.Player.DelBuff(), Terraria.Player.GetProjectileSource_Misc(), Terraria.Player.hasFootball, Terraria.Player.inventory, Terraria.Player.invis, Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, Terraria.Player.maxBuffs, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.NewProjectile(), Terraria.Main.NotifyOfEvent(), Terraria.Player.panic, Terraria.Main.projectile, Terraria.Player.selectedItem, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Player.setSquireT2, Terraria.Player.stealth, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.Hurt().