TModLoader: Terraria.Player.GetHealLife
GetHealLife()
int Terraria.Player.GetHealLife (Item item, bool quickHeal = false) inline
    {
        int healValue = item.healLife;
        ItemLoader.GetHealLife(item, this, quickHeal, ref healValue);
        PlayerLoader.GetHealLife(this, item, quickHeal, ref healValue);
        if (healValue <= 0)
        {
            return 0;
        }
        return healValue;
    }
References Terraria.ModLoader.ItemLoader.GetHealLife(), Terraria.ModLoader.PlayerLoader.GetHealLife(), and Terraria.Item.healLife.
Referenced by Terraria.Player.ApplyLifeAndOrMana(), and Terraria.Player.QuickHeal_GetItemToUse().