TModLoader: Terraria.Player.DoBootsEffect
DoBootsEffect()
void Terraria.Player.DoBootsEffect (Utils::TileActionAttempt theEffectMethod) inline
Definition at line 12006 of file Player.cs.
    {
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        if (miscCounter % 2 == 0 && velocity.Y == 0f && grappling[0] == -1 && velocity.X != 0f)
        {
            int x = (int)base.Center.X / 16;
            int y = (int)(position.Y + (float)height - 1f) / 16;
            theEffectMethod(x, y);
        }
    }
References Terraria.Player.grappling, Terraria.Entity.height, Terraria.Player.miscCounter, Terraria.Entity.position, and Terraria.Entity.velocity.
Referenced by Terraria.Player.ApplyEquipFunctional(), Terraria.Player.ApplyEquipVanity(), and Terraria.Player.GrantArmorBenefits().