TModLoader: Terraria.Player.ConsumeItem
ConsumeItem()
bool Terraria.Player.ConsumeItem (int type, bool reverseOrder = false, bool includeVoidBag = false) inline
Use to consume a single item. The item does not have to be F:Terraria.Item.consumable.
Attempts to reduce the F:Terraria.Item.stack of the first T:Terraria.Item found in the F:Terraria.Player.inventory by 1.
Respects M:Terraria.ModLoader.ItemLoader.ConsumeItem(Terraria.Item,Terraria.Player), so the item won't necessarily be consumed.
To consume multiple of the item, first check M:Terraria.Player.CountItem(System.Int32,System.Int32) to ensure that there are enough of the item, then use a for loop to call this method many times.
Parameters
type The item type to consume
reverseOrder If true, the search for the item will start at the end of the player inventory
includeVoidBag If true, the void bag, if open, will also be considered for finding an item to consume
Returns
True if the item was found and attempted to be consumed
    {
        int num = 0;
        int num2 = 58;
        int num3 = 1;
        if (reverseOrder)
        {
            num = 57;
            num2 = -1;
            num3 = -1;
        }
        for (int i = num; i != num2; i += num3)
        {
            if (inventory[i].stack > 0 && inventory[i].type == type)
            {
                if (ItemLoader.ConsumeItem(inventory[i], this))
                {
                    inventory[i].stack--;
                }
                if (inventory[i].stack <= 0)
                {
                    inventory[i].SetDefaults();
                }
                return true;
            }
        }
        if (includeVoidBag && useVoidBag())
        {
            int num4 = FindItem(type, bank4.item);
            if (num4 == -1)
            {
                return false;
            }
            Item item = bank4.item[num4];
            item.stack--;
            if (item.stack <= 0)
            {
                item.TurnToAir();
            }
            return true;
        }
        return false;
    }
References Terraria.Player.bank4, Terraria.ModLoader.ItemLoader.ConsumeItem(), Terraria.Player.FindItem(), Terraria.Player.inventory, Terraria.Chest.item, Terraria.Item.SetDefaults(), Terraria.Item.stack, Terraria.Item.TurnToAir(), and Terraria.Player.useVoidBag().
Referenced by Terraria.Main.GUIChatDrawInner(), Terraria.Wiring.MassWireOperation(), Terraria.Player.PayDD2CrystalsBeforeUse(), Terraria.Player.TileInteractionsUse(), and Terraria.UI.ItemSlot.TryOpenContainer().