TModLoader: Terraria.Player.MowGrassTile
MowGrassTile()
void Terraria.Player.MowGrassTile (Vector2 thePos) inline private
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        Point point = thePos.ToTileCoordinates();
        Tile tile = Main.tile[point.X, point.Y];
        if (tile == null || !WorldGen.CanKillTile(point.X, point.Y, WorldGen.SpecialKillTileContext.MowingTheGrass))
        {
            return;
        }
        ushort num = 0;
        switch (tile.type)
        {
        case 2:
            num = 477;
            break;
        case 109:
            num = 492;
            break;
        }
        if (num != 0)
        {
            int num2 = WorldGen.KillTile_GetTileDustAmount(fail: true, tile, point.X, point.Y);
            for (int i = 0; i < num2; i++)
            {
                WorldGen.KillTile_MakeTileDust(point.X, point.Y, tile);
            }
            tile.type = num;
            if (Main.netMode == 1)
            {
                NetMessage.SendTileSquare(-1, point.X, point.Y);
            }
        }
    }
References Terraria.WorldGen.CanKillTile(), Terraria.WorldGen.KillTile_GetTileDustAmount(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.Main.netMode, Terraria.NetMessage.SendTileSquare(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.Player.ItemCheck_UseLawnMower(), and Terraria.Player.MowTheLawn().