TModLoader: Terraria.Player.DryCollision
DryCollision()
void Terraria.Player.DryCollision (bool fallThrough, bool ignorePlats) inline
    {
        //IL_0396: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_040d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0412: Unknown result type (might be due to invalid IL or missing references)
        //IL_0418: Unknown result type (might be due to invalid IL or missing references)
        //IL_043e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0444: Unknown result type (might be due to invalid IL or missing references)
        //IL_0449: Unknown result type (might be due to invalid IL or missing references)
        //IL_044e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        //IL_038e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0102: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_0269: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0280: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0302: Unknown result type (might be due to invalid IL or missing references)
        //IL_0307: Unknown result type (might be due to invalid IL or missing references)
        //IL_0309: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0316: Unknown result type (might be due to invalid IL or missing references)
        //IL_0328: Unknown result type (might be due to invalid IL or missing references)
        //IL_0341: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_0371: Unknown result type (might be due to invalid IL or missing references)
        //IL_0376: Unknown result type (might be due to invalid IL or missing references)
        //IL_0378: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_037b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0380: Unknown result type (might be due to invalid IL or missing references)
        int num = ((!onTrack) ? height : (height - 10));
        if (((Vector2)(ref velocity)).Length() > 16f)
        {
            Vector2 val = Collision.TileCollision(position, velocity, width, num, fallThrough, ignorePlats, (int)gravDir);
            float num2 = ((Vector2)(ref velocity)).Length();
            Vector2 vector2 = Vector2.Normalize(velocity);
            if (val.Y == 0f)
            {
                vector2.Y = 0f;
            }
            Vector2 zero = Vector2.Zero;
            bool flag = mount.Type == 7 || mount.Type == 8 || mount.Type == 12 || mount.Type == 44 || mount.Type == 49;
            _ = Vector2.Zero;
            while (num2 > 0f)
            {
                float num3 = num2;
                if (num3 > 16f)
                {
                    num3 = 16f;
                }
                num2 -= num3;
                Vector2 vector3 = vector2 * num3;
                velocity = vector3;
                SlopeDownMovement();
                vector3 = velocity;
                if (velocity.Y == gravity && (!mount.Active || (!mount.Cart && mount.Type != 48 && !flag)))
                {
                    Collision.StepDown(ref position, ref vector3, width, height, ref stepSpeed, ref gfxOffY, (int)gravDir, waterWalk || waterWalk2);
                }
                if (gravDir == -1f)
                {
                    if ((carpetFrame != -1 || velocity.Y <= gravity) && !controlUp)
                    {
                        Collision.StepUp(ref position, ref vector3, width, height, ref stepSpeed, ref gfxOffY, (int)gravDir, controlUp);
                    }
                }
                else if (flag || ((carpetFrame != -1 || velocity.Y >= gravity) && !controlDown && !mount.Cart))
                {
                    Collision.StepUp(ref position, ref vector3, width, height, ref stepSpeed, ref gfxOffY, (int)gravDir, controlUp);
                }
                Vector2 vector4 = Collision.TileCollision(position, vector3, width, num, fallThrough, ignorePlats, (int)gravDir);
                if (Collision.up && gravDir == 1f)
                {
                    jump = 0;
                }
                if (waterWalk || waterWalk2)
                {
                    Vector2 val2 = velocity;
                    vector4 = Collision.WaterCollision(position, vector4, width, height, fallThrough, fall2: false, waterWalk);
                    if (val2 != velocity)
                    {
                        fallStart = (int)(position.Y / 16f);
                    }
                }
                position += vector4;
                bool falling = false;
                if (vector4.Y > gravity)
                {
                    falling = true;
                }
                if (vector4.Y < 0f - gravity)
                {
                    falling = true;
                }
                velocity = vector4;
                UpdateTouchingTiles();
                TryBouncingBlocks(falling);
                TryLandingOnDetonator();
                SlopingCollision(fallThrough, ignorePlats);
                Collision.StepConveyorBelt(this, gravDir);
                vector4 = velocity;
                zero += vector4;
            }
            velocity = zero;
            return;
        }
        velocity = Collision.TileCollision(position, velocity, width, num, fallThrough, ignorePlats, (int)gravDir);
        if (Collision.up && gravDir == 1f)
        {
            jump = 0;
        }
        if (waterWalk || waterWalk2)
        {
            Vector2 val3 = velocity;
            velocity = Collision.WaterCollision(position, velocity, width, height, fallThrough, fall2: false, waterWalk);
            if (val3 != velocity)
            {
                fallStart = (int)(position.Y / 16f);
            }
        }
        position += velocity;
    }
References Terraria.Mount.Active, Terraria.Player.carpetFrame, Terraria.Mount.Cart, Terraria.Player.controlDown, Terraria.Player.controlUp, Terraria.Player.fallStart, Terraria.Player.gfxOffY, Terraria.Player.gravDir, Terraria.Player.gravity, Terraria.Entity.height, Terraria.Player.jump, Terraria.Player.mount, Terraria.Player.onTrack, Terraria.Entity.position, Terraria.Player.SlopeDownMovement(), Terraria.Player.SlopingCollision(), Terraria.Collision.StepConveyorBelt(), Terraria.Collision.StepDown(), Terraria.Player.stepSpeed, Terraria.Collision.StepUp(), Terraria.Collision.TileCollision(), Terraria.Player.TryBouncingBlocks(), Terraria.Player.TryLandingOnDetonator(), Terraria.Mount.Type, Terraria.Collision.up, Terraria.Player.UpdateTouchingTiles(), Terraria.Entity.velocity, Terraria.Collision.WaterCollision(), Terraria.Player.waterWalk, Terraria.Player.waterWalk2, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().