TModLoader: Terraria.Player.GrappleMovement
GrappleMovement()
void Terraria.Player.GrappleMovement () inline
Definition at line 20439 of file Player.cs.
    {
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_0244: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_0272: Unknown result type (might be due to invalid IL or missing references)
        //IL_0367: Unknown result type (might be due to invalid IL or missing references)
        //IL_037c: Unknown result type (might be due to invalid IL or missing references)
        //IL_037e: Unknown result type (might be due to invalid IL or missing references)
        //IL_038f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0394: Unknown result type (might be due to invalid IL or missing references)
        //IL_03be: Unknown result type (might be due to invalid IL or missing references)
        if (grappling[0] < 0)
        {
            return;
        }
        StopVanityActions();
        if (Main.myPlayer == whoAmI && mount.Active)
        {
            mount.Dismount(this);
        }
        canCarpet = true;
        carpetFrame = -1;
        wingFrame = 1;
        if (velocity.Y == 0f || (wet && (double)velocity.Y > -0.02 && (double)velocity.Y < 0.02))
        {
            wingFrame = 0;
        }
        if (wings == 4)
        {
            wingFrame = 3;
        }
        if (wings == 30)
        {
            wingFrame = 0;
        }
        RefreshMovementAbilities();
        rocketFrame = false;
        canRocket = false;
        rocketRelease = false;
        fallStart = (int)(position.Y / 16f);
        int num = -1;
        for (int i = 0; i < grapCount; i++)
        {
            if (Main.projectile[grappling[i]].type == 403)
            {
                num = i;
            }
        }
        GetGrapplingForces(base.Center, out var preferredPlayerDirectionToSet, out var preferedPlayerVelocityX, out var preferedPlayerVelocityY);
        if (preferedPlayerVelocityY > 0f)
        {
            GoingDownWithGrapple = true;
        }
        velocity.X = preferedPlayerVelocityX;
        velocity.Y = preferedPlayerVelocityY;
        if (num != -1)
        {
            Projectile projectile = Main.projectile[grappling[num]];
            if (projectile.position.X < position.X + (float)width && projectile.position.X + (float)projectile.width >= position.X && projectile.position.Y < position.Y + (float)height && projectile.position.Y + (float)projectile.height >= position.Y)
            {
                int num2 = (int)(projectile.position.X + (float)(projectile.width / 2)) / 16;
                int num3 = (int)(projectile.position.Y + (float)(projectile.height / 2)) / 16;
                velocity = Vector2.Zero;
                if (Main.tile[num2, num3].type == 314)
                {
                    Vector2 Position = default(Vector2);
                    Position.X = projectile.position.X + (float)(projectile.width / 2) - (float)(width / 2);
                    Position.Y = projectile.position.Y + (float)(projectile.height / 2) - (float)(height / 2);
                    RemoveAllGrapplingHooks();
                    int num4 = 13;
                    if (miscEquips[2].stack > 0 && miscEquips[2].mountType >= 0 && MountID.Sets.Cart[miscEquips[2].mountType] && (!miscEquips[2].expertOnly || Main.expertMode) && (!miscEquips[2].masterOnly || Main.masterMode))
                    {
                        num4 = miscEquips[2].mountType;
                    }
                    int num5 = height + Mount.GetHeightBoost(num4);
                    if (Minecart.GetOnTrack(num2, num3, ref Position, width, num5) && !Collision.SolidCollision(Position, width, num5 - 20))
                    {
                        position = Position;
                        DelegateMethods.Minecart.rotation = fullRotation;
                        DelegateMethods.Minecart.rotationOrigin = fullRotationOrigin;
                        mount.SetMount(num4, this, minecartLeft);
                        Minecart.WheelSparks(mount.Delegations.MinecartDust, position, width, height, 25);
                    }
                }
            }
        }
        if (itemAnimation == 0)
        {
            if (velocity.X == 0f && preferredPlayerDirectionToSet.HasValue)
            {
                ChangeDir(preferredPlayerDirectionToSet.Value);
            }
            if (velocity.X > 0f)
            {
                ChangeDir(1);
            }
            if (velocity.X < 0f)
            {
                ChangeDir(-1);
            }
        }
        if (controlJump)
        {
            if (releaseJump)
            {
                if ((velocity.Y == 0f || (wet && (double)velocity.Y > -0.02 && (double)velocity.Y < 0.02)) && !controlDown)
                {
                    velocity.Y = 0f - jumpSpeed;
                    jump = jumpHeight / 2;
                    releaseJump = false;
                }
                else
                {
                    velocity.Y += 0.01f;
                    releaseJump = false;
                }
                RefreshDoubleJumps();
                RemoveAllGrapplingHooks();
            }
        }
        else
        {
            releaseJump = true;
        }
    }
References Terraria.Mount.Active, Terraria.Player.canCarpet, Terraria.Player.canRocket, Terraria.Player.carpetFrame, Terraria.ID.MountID.Sets.Cart, Terraria.Player.ChangeDir(), Terraria.Player.controlDown, Terraria.Player.controlJump, Terraria.Mount.Delegations, Terraria.Mount.Dismount(), Terraria.Main.expertMode, Terraria.Item.expertOnly, Terraria.Player.fallStart, Terraria.Player.fullRotation, Terraria.Player.fullRotationOrigin, Terraria.Player.GetGrapplingForces(), Terraria.Mount.GetHeightBoost(), Terraria.Minecart.GetOnTrack(), Terraria.Player.GoingDownWithGrapple, Terraria.Player.grapCount, Terraria.Player.grappling, Terraria.Entity.height, Terraria.Player.itemAnimation, Terraria.Player.jump, Terraria.Player.jumpHeight, Terraria.Player.jumpSpeed, Terraria.Main.masterMode, Terraria.Item.masterOnly, Terraria.Mount.MountDelegatesData.MinecartDust, Terraria.Player.minecartLeft, Terraria.Player.miscEquips, Terraria.Player.mount, Terraria.Item.mountType, Terraria.Main.myPlayer, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Player.RefreshDoubleJumps(), Terraria.Player.RefreshMovementAbilities(), Terraria.Player.releaseJump, Terraria.Player.RemoveAllGrapplingHooks(), Terraria.Player.rocketFrame, Terraria.Player.rocketRelease, Terraria.Mount.SetMount(), Terraria.Collision.SolidCollision(), Terraria.Player.StopVanityActions(), Terraria.Main.tile, Terraria.Projectile.type, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Minecart.WheelSparks(), Terraria.Entity.whoAmI, Terraria.Entity.width, Terraria.Player.wingFrame, and Terraria.Player.wings.
Referenced by Terraria.Player.Update().