TModLoader: Terraria.Player.PayCurrency
PayCurrency()
bool Terraria.Player.PayCurrency (long price, int customCurrency = -1) inline
Definition at line 34155 of file Player.cs.
    {
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_025a: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0320: Unknown result type (might be due to invalid IL or missing references)
        if (customCurrency != -1)
        {
            return CustomCurrencyManager.PayCurrency(this, price, customCurrency);
        }
        List<Item[]> list = new List<Item[]>();
        Dictionary<int, List<int>> dictionary = new Dictionary<int, List<int>>();
        List<Point> list2 = new List<Point>();
        List<Point> list3 = new List<Point>();
        List<Point> list4 = new List<Point>();
        List<Point> list5 = new List<Point>();
        List<Point> list6 = new List<Point>();
        List<Point> list7 = new List<Point>();
        list.Add(inventory);
        list.Add(bank.item);
        list.Add(bank2.item);
        list.Add(bank3.item);
        list.Add(bank4.item);
        for (int i = 0; i < list.Count; i++)
        {
            dictionary[i] = new List<int>();
        }
        dictionary[0] = new List<int> { 58, 57, 56, 55, 54 };
        for (int j = 0; j < list.Count; j++)
        {
            for (int k = 0; k < list[j].Length; k++)
            {
                if (!dictionary[j].Contains(k) && list[j][k].IsACoin)
                {
                    list3.Add(new Point(j, k));
                }
            }
        }
        int num12 = 0;
        for (int num13 = list[num12].Length - 1; num13 >= 0; num13--)
        {
            if (!dictionary[num12].Contains(num13) && (list[num12][num13].type == 0 || list[num12][num13].stack == 0))
            {
                list2.Add(new Point(num12, num13));
            }
        }
        num12 = 1;
        for (int num14 = list[num12].Length - 1; num14 >= 0; num14--)
        {
            if (!dictionary[num12].Contains(num14) && (list[num12][num14].type == 0 || list[num12][num14].stack == 0))
            {
                list4.Add(new Point(num12, num14));
            }
        }
        num12 = 2;
        for (int num15 = list[num12].Length - 1; num15 >= 0; num15--)
        {
            if (!dictionary[num12].Contains(num15) && (list[num12][num15].type == 0 || list[num12][num15].stack == 0))
            {
                list5.Add(new Point(num12, num15));
            }
        }
        num12 = 3;
        for (int num10 = list[num12].Length - 1; num10 >= 0; num10--)
        {
            if (!dictionary[num12].Contains(num10) && (list[num12][num10].type == 0 || list[num12][num10].stack == 0))
            {
                list6.Add(new Point(num12, num10));
            }
        }
        num12 = 4;
        for (int num11 = list[num12].Length - 1; num11 >= 0; num11--)
        {
            if (!dictionary[num12].Contains(num11) && (list[num12][num11].type == 0 || list[num12][num11].stack == 0))
            {
                list7.Add(new Point(num12, num11));
            }
        }
        if (TryPurchasing(price, list, list3, list2, list4, list5, list6, list7))
        {
            return false;
        }
        return true;
    }
References Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Player.inventory, Terraria.Chest.item, Terraria.GameContent.UI.CustomCurrencyManager.PayCurrency(), and Terraria.Player.TryPurchasing().
Referenced by Terraria.Player.BuyItem().