TModLoader: Terraria.Player.GrantPrefixBenefits
GrantPrefixBenefits()
void Terraria.Player.GrantPrefixBenefits (Item item) inline
Definition at line 11890 of file Player.cs.
    {
        if (item.prefix == 62)
        {
            ++statDefense;
        }
        if (item.prefix == 63)
        {
            statDefense += 2;
        }
        if (item.prefix == 64)
        {
            statDefense += 3;
        }
        if (item.prefix == 65)
        {
            statDefense += 4;
        }
        if (item.prefix == 66)
        {
            statManaMax2 += 20;
        }
        if (item.prefix == 67)
        {
            allCrit += 2f;
        }
        if (item.prefix == 68)
        {
            allCrit += 4f;
        }
        if (item.prefix == 69)
        {
            allDamage += 0.01f;
        }
        if (item.prefix == 70)
        {
            allDamage += 0.02f;
        }
        if (item.prefix == 71)
        {
            allDamage += 0.03f;
        }
        if (item.prefix == 72)
        {
            allDamage += 0.04f;
        }
        if (item.prefix == 73)
        {
            moveSpeed += 0.01f;
        }
        if (item.prefix == 74)
        {
            moveSpeed += 0.02f;
        }
        if (item.prefix == 75)
        {
            moveSpeed += 0.03f;
        }
        if (item.prefix == 76)
        {
            moveSpeed += 0.04f;
        }
        if (item.prefix == 77)
        {
            meleeSpeed += 0.01f;
        }
        if (item.prefix == 78)
        {
            meleeSpeed += 0.02f;
        }
        if (item.prefix == 79)
        {
            meleeSpeed += 0.03f;
        }
        if (item.prefix == 80)
        {
            meleeSpeed += 0.04f;
        }
        PrefixLoader.ApplyAccessoryEffects(this, item);
    }
References Terraria.Player.allCrit, Terraria.Player.allDamage, Terraria.ModLoader.PrefixLoader.ApplyAccessoryEffects(), Terraria.Player.meleeSpeed, Terraria.Player.moveSpeed, Terraria.Item.prefix, Terraria.Player.statDefense, and Terraria.Player.statManaMax2.
Referenced by Terraria.ModLoader.ModAccessorySlot.ApplyEquipEffects(), and Terraria.Player.UpdateEquips().