TModLoader: Terraria.Player.Volcano_TrySpawningVolcano
Volcano_TrySpawningVolcano()
void Terraria.Player.Volcano_TrySpawningVolcano (NPC npc, Item sItem, float damage, float knockBack, Rectangle itemRectangle) inline private
Definition at line 43338 of file Player.cs.
    {
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        if (_spawnVolcanoExplosion && Main.myPlayer == whoAmI && (npc == null || npc.HittableForOnHitRewards()))
        {
            Vector2 center = npc.Center;
            int num = 2;
            Projectile.NewProjectile(GetProjectileSource_Item(sItem), center.X, center.Y, 0f, -1f * gravDir, 978, (int)damage, knockBack, whoAmI, 0f, num);
            _spawnVolcanoExplosion = false;
        }
    }
References Terraria.Player._spawnVolcanoExplosion, Terraria.Entity.Center, Terraria.Player.GetProjectileSource_Item(), Terraria.Player.gravDir, Terraria.NPC.HittableForOnHitRewards(), Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ApplyNPCOnHitEffects().