TModLoader: Terraria.Player.DoEyebrellaRainEffect
DoEyebrellaRainEffect()
void Terraria.Player.DoEyebrellaRainEffect () inline private
Definition at line 12198 of file Player.cs.
    {
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode == 2 || Main.dedServ || Main.rand.Next(4) != 0)
        {
            return;
        }
        Vector2 vector = MountedCenter - new Vector2(0f, (float)height * 0.5f) + new Vector2((-0.5f + Main.rand.NextFloat()) * (float)(width + 18), -30f);
        int num = (int)(vector.X / 16f);
        int num2 = (int)(vector.Y / 16f);
        if (WorldGen.InWorld(num, num2))
        {
            Tile tile = Main.tile[num, num2];
            if (tile != null && !WorldGen.SolidTile3(tile) && tile.liquid <= 0)
            {
                Vector2 val = default(Vector2);
                ((Vector2)(ref val))._002Ector(Main.windSpeedCurrent * 3f, 9f);
                Rain.NewRainForced(vector, val);
            }
        }
    }
References Terraria.Main.dedServ, Terraria.Entity.height, Terraria.WorldGen.InWorld(), Terraria.Player.MountedCenter, Terraria.Main.netMode, Terraria.Rain.NewRainForced(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.WorldGen.SolidTile3(), Terraria.Main.tile, Terraria.Entity.width, and Terraria.Main.windSpeedCurrent.
Referenced by Terraria.Player.UpdateEquips().