TModLoader: Terraria.Player.Teleport
Teleport()
void Terraria.Player.Teleport (Vector2 newPos, int Style = 0, int extraInfo = 0) inline
    {
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_0248: Unknown result type (might be due to invalid IL or missing references)
        //IL_024e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0253: Unknown result type (might be due to invalid IL or missing references)
        //IL_0258: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        try
        {
            _funkytownAchievementCheckCooldown = 100;
            environmentBuffImmunityTimer = 4;
            if (Style != 10)
            {
                RemoveAllGrapplingHooks();
            }
            StopVanityActions();
            if (shimmering || shimmerWet)
            {
                shimmering = false;
                shimmerWet = false;
                wet = false;
                ClearBuff(353);
            }
            int extraInfo2 = 0;
            if (Style == 4)
            {
                extraInfo2 = lastPortalColorIndex;
            }
            if (Style == 9)
            {
                lastTeleportPylonStyleUsed = extraInfo;
                extraInfo2 = lastTeleportPylonStyleUsed;
            }
            float num = MathHelper.Clamp(1f - teleportTime * 0.99f, 0.01f, 1f);
            Vector2 otherPosition = position;
            Main.TeleportEffect(getRect(), Style, extraInfo2, num, TeleportationSide.Entry, newPos);
            float num2 = Vector2.Distance(position, newPos);
            PressurePlateHelper.UpdatePlayerPosition(this);
            position = newPos;
            if (Style == 8)
            {
                SoundEngine.PlaySound(in SoundID.Item6, otherPosition);
                SoundEngine.PlaySound(in SoundID.Item6, newPos);
            }
            fallStart = (int)(position.Y / 16f);
            if (whoAmI == Main.myPlayer)
            {
                bool flag = false;
                Vector2 val = new Vector2((float)Main.screenWidth, (float)Main.screenHeight);
                if (num2 < ((Vector2)(ref val)).Length() / 2f + 100f)
                {
                    int time = 0;
                    if (Style == 1)
                    {
                        time = 10;
                    }
                    Main.SetCameraLerp(0.1f, time);
                    flag = true;
                }
                else
                {
                    NPC.ResetNetOffsets();
                    Main.BlackFadeIn = 255;
                    Lighting.Clear();
                    Main.screenLastPosition = Main.screenPosition;
                    Main.screenPosition.X = position.X + (float)(width / 2) - (float)(Main.screenWidth / 2);
                    Main.screenPosition.Y = position.Y + (float)(height / 2) - (float)(Main.screenHeight / 2);
                    Main.instantBGTransitionCounter = 10;
                    ForceUpdateBiomes();
                }
                if (num > 0.1f || !flag || Style != 0)
                {
                    if (Main.mapTime < 5)
                    {
                        Main.mapTime = 5;
                    }
                    Main.maxQ = true;
                    Main.renderNow = true;
                }
            }
            if (Style == 4)
            {
                lastPortalColorIndex = extraInfo;
                extraInfo2 = lastPortalColorIndex;
                portalPhysicsFlag = true;
                gravity = 0f;
            }
            PressurePlateHelper.UpdatePlayerPosition(this);
            ResetAdvancedShadows();
            for (int i = 0; i < 3; i++)
            {
                UpdateSocialShadow();
            }
            oldPosition = position + BlehOldPositionFixer;
            Main.TeleportEffect(getRect(), Style, extraInfo2, num, TeleportationSide.Exit, otherPosition);
            teleportTime = 1f;
            teleportStyle = Style;
        }
        catch
        {
        }
    }
References Terraria.Player._funkytownAchievementCheckCooldown, Terraria.Player.BlehOldPositionFixer, Terraria.Lighting.Clear(), Terraria.Player.ClearBuff(), Terraria.Player.environmentBuffImmunityTimer, Terraria.Player.fallStart, Terraria.Player.ForceUpdateBiomes(), Terraria.Player.getRect(), Terraria.Player.gravity, Terraria.Entity.height, Terraria.ID.SoundID.Item6, Terraria.Player.lastPortalColorIndex, Terraria.Player.lastTeleportPylonStyleUsed, Terraria.Main.mapTime, Terraria.Main.myPlayer, Terraria.Entity.oldPosition, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.portalPhysicsFlag, Terraria.Entity.position, Terraria.Player.RemoveAllGrapplingHooks(), Terraria.Player.ResetAdvancedShadows(), Terraria.NPC.ResetNetOffsets(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.SetCameraLerp(), Terraria.Player.shimmering, Terraria.Entity.shimmerWet, Terraria.Player.StopVanityActions(), Terraria.Main.TeleportEffect(), Terraria.Player.teleportStyle, Terraria.Player.teleportTime, Terraria.GameContent.PressurePlateHelper.UpdatePlayerPosition(), Terraria.Player.UpdateSocialShadow(), Terraria.Entity.wet, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.DemonConch(), Terraria.Player.DoPotionOfReturnReturnToOriginalUsePosition(), Terraria.Player.DoQueenSlimeHookTeleport(), Terraria.GameContent.TeleportPylonsSystem.HandleTeleportRequest(), Terraria.Player.ItemCheck_UseTeleportRod(), Terraria.Player.MagicConch(), Terraria.Player.Shellphone_Spawn(), Terraria.Player.ShimmerUnstuck(), Terraria.Player.TeleportationPotion(), Terraria.GameContent.PortalHelper.TryGoingThroughPortals(), and Terraria.Player.UnityTeleport().