TModLoader: Terraria.Player.GetItem_FillIntoOccupiedSlot
GetItem_FillIntoOccupiedSlot()
bool Terraria.Player.GetItem_FillIntoOccupiedSlot (int plr, Item newItem, GetItemSettings settings, Item returnItem, int i) inline private
Definition at line 38273 of file Player.cs.
    {
        if (inventory[i].type > 0 && inventory[i].stack < inventory[i].maxStack && returnItem.IsTheSameAs(inventory[i]))
        {
            if (!ItemLoader.TryStackItems(inventory[i], returnItem, out var numTransfered))
            {
                return false;
            }
            if (newItem.IsACoin)
            {
                SoundEngine.PlaySound(38, (int)position.X, (int)position.Y);
            }
            else
            {
                SoundEngine.PlaySound(7, (int)position.X, (int)position.Y);
            }
            if (!settings.NoText)
            {
                PopupText.NewText(PopupTextContext.RegularItemPickup, newItem, numTransfered, noStack: false, settings.LongText);
            }
            DoCoins(i);
            if (plr == Main.myPlayer)
            {
                Recipe.FindRecipes();
            }
            AchievementsHelper.NotifyItemPickup(this, returnItem);
            settings.HandlePostAction(inventory[i]);
            if (returnItem.stack <= 0)
            {
                return true;
            }
        }
        return false;
    }
References Terraria.Player.DoCoins(), Terraria.Recipe.FindRecipes(), Terraria.Player.inventory, Terraria.Main.myPlayer, Terraria.PopupText.NewText(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemPickup(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, and Terraria.ModLoader.ItemLoader.TryStackItems().
Referenced by Terraria.Player.GetItem().