TModLoader: Terraria.Player.HorsemansBlade_SpawnPumpkin
HorsemansBlade_SpawnPumpkin()
void Terraria.Player.HorsemansBlade_SpawnPumpkin (int npcIndex, int dmg, float kb) inline
Definition at line 41246 of file Player.cs.
    {
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        Vector2 center = Main.npc[npcIndex].Center;
        int logicCheckScreenHeight = Main.LogicCheckScreenHeight;
        int logicCheckScreenWidth = Main.LogicCheckScreenWidth;
        int num = Main.rand.Next(100, 300);
        int num2 = Main.rand.Next(100, 300);
        num = ((Main.rand.Next(2) != 0) ? (num + (logicCheckScreenWidth / 2 - num)) : (num - (logicCheckScreenWidth / 2 + num)));
        num2 = ((Main.rand.Next(2) != 0) ? (num2 + (logicCheckScreenHeight / 2 - num2)) : (num2 - (logicCheckScreenHeight / 2 + num2)));
        num += (int)position.X;
        num2 += (int)position.Y;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)num, (float)num2);
        float num3 = center.X - vector.X;
        float num4 = center.Y - vector.Y;
        float num5 = (float)Math.Sqrt(num3 * num3 + num4 * num4);
        num5 = 8f / num5;
        num3 *= num5;
        num4 *= num5;
        Projectile.NewProjectile(GetProjectileSource_Item(HeldItem), num, num2, num3, num4, 321, dmg, kb, whoAmI, npcIndex);
    }
References Terraria.Entity.Center, Terraria.Player.GetProjectileSource_Item(), Terraria.Player.HeldItem, Terraria.Main.LogicCheckScreenHeight, Terraria.Main.LogicCheckScreenWidth, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Entity.position, Terraria.Main.rand, and Terraria.Entity.whoAmI.
Referenced by Terraria.Projectile.Damage().