TModLoader: Terraria.Player.ItemCheck_Inner
ItemCheck_Inner()
void Terraria.Player.ItemCheck_Inner () inline private
    {
        //IL_0486: Unknown result type (might be due to invalid IL or missing references)
        //IL_048b: Unknown result type (might be due to invalid IL or missing references)
        //IL_05da: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0614: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09de: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b38: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ccf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b58: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b76: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a63: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d05: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a95: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0abf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e72: Unknown result type (might be due to invalid IL or missing references)
        //IL_11b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e96: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec8: Unknown result type (might be due to invalid IL or missing references)
        //IL_125a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1003: Unknown result type (might be due to invalid IL or missing references)
        //IL_100d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1012: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_120b: Unknown result type (might be due to invalid IL or missing references)
        //IL_121c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1226: Unknown result type (might be due to invalid IL or missing references)
        //IL_122b: Unknown result type (might be due to invalid IL or missing references)
        //IL_105c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1096: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_150c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1512: Unknown result type (might be due to invalid IL or missing references)
        //IL_1514: Unknown result type (might be due to invalid IL or missing references)
        //IL_1519: Unknown result type (might be due to invalid IL or missing references)
        //IL_1275: Unknown result type (might be due to invalid IL or missing references)
        //IL_12af: Unknown result type (might be due to invalid IL or missing references)
        //IL_12c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_12cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_1121: Unknown result type (might be due to invalid IL or missing references)
        //IL_1132: Unknown result type (might be due to invalid IL or missing references)
        //IL_113c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1141: Unknown result type (might be due to invalid IL or missing references)
        //IL_155a: Unknown result type (might be due to invalid IL or missing references)
        //IL_157e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1581: Unknown result type (might be due to invalid IL or missing references)
        //IL_1586: Unknown result type (might be due to invalid IL or missing references)
        //IL_158b: Unknown result type (might be due to invalid IL or missing references)
        //IL_158d: Unknown result type (might be due to invalid IL or missing references)
        //IL_15a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_15a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_15bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_15bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_15da: Unknown result type (might be due to invalid IL or missing references)
        //IL_15df: Unknown result type (might be due to invalid IL or missing references)
        //IL_12fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1320: Unknown result type (might be due to invalid IL or missing references)
        //IL_1331: Unknown result type (might be due to invalid IL or missing references)
        //IL_133b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1340: Unknown result type (might be due to invalid IL or missing references)
        if (CCed)
        {
            channel = false;
            itemAnimation = (itemAnimationMax = 0);
            return;
        }
        float heightOffsetHitboxCenter = HeightOffsetHitboxCenter;
        Item item = inventory[selectedItem];
        ItemCheckContext context = default(ItemCheckContext);
        bool flag = false;
        if (Main.myPlayer == whoAmI)
        {
            if (PlayerInput.ShouldFastUseItem)
            {
                controlUseItem = true;
                flag = true;
            }
            if (!cursorItemIconEnabled && item.stack > 0 && item.fishingPole > 0)
            {
                Fishing_GetBait(out var bait);
                if (bait != null)
                {
                    cursorItemIconEnabled = true;
                    cursorItemIconID = bait.type;
                    cursorItemIconPush = 6;
                }
            }
            if (!cursorItemIconEnabled && item.stack > 0 && (item.type == 779 || item.type == 5134))
            {
                for (int i = 54; i < 58; i++)
                {
                    if (inventory[i].ammo == item.useAmmo && inventory[i].stack > 0)
                    {
                        cursorItemIconEnabled = true;
                        cursorItemIconID = inventory[i].type;
                        cursorItemIconPush = 10;
                        break;
                    }
                }
                if (!cursorItemIconEnabled)
                {
                    for (int j = 0; j < 54; j++)
                    {
                        if (inventory[j].ammo == item.useAmmo && inventory[j].stack > 0)
{
                            cursorItemIconEnabled = true;
                            cursorItemIconID = inventory[j].type;
                            cursorItemIconPush = 10;
                            break;
                        }
                    }
                }
            }
        }
        if (itemAnimation > 0)
        {
            itemAnimation--;
            if (itemAnimation == 0 && whoAmI == Main.myPlayer)
            {
                PlayerInput.TryEndingFastUse();
            }
        }
        if (itemTime > 0)
        {
            itemTime--;
            if (ItemTimeIsZero && whoAmI == Main.myPlayer && !JustDroppedAnItem)
            {
                int type = item.type;
                if (type == 65 || type == 724 || type == 989 || type == 1226)
                {
                    EmitMaxManaEffect();
                }
            }
        }
        if (itemAnimation == 0 && reuseDelay == 0 && (!controlUseItem || selectItemOnNextUse))
        {
            selectItemOnNextUse = false;
            int oldSelect = selectedItem;
            SmartSelectLookup();
            if (selectedItem != oldSelect)
            {
                item = inventory[selectedItem];
                releaseUseItem = true;
                itemTime = (itemTimeMax = 0);
            }
        }
        ItemCheck_HandleMount();
        int weaponDamage = GetWeaponDamage(item);
        ItemCheck_HandleMPItemAnimation(item);
        ItemCheck_HackHoldStyles(item);
        if (itemAnimation < 0)
        {
            itemAnimation = 0;
        }
        if (itemTime < 0)
        {
            itemTime = 0;
        }
        if (itemAnimation == 0 && reuseDelay > 0)
        {
            ApplyReuseDelay();
        }
        UpdatePlacementPreview(item);
        if (itemAnimation == 0 && altFunctionUse == 2)
        {
            altFunctionUse = 0;
        }
        bool flag2 = true;
        if (gravDir == -1f && GolfHelper.IsPlayerHoldingClub(this))
        {
            flag2 = false;
        }
        if (flag2 && controlUseItem && releaseUseItem && itemAnimation == 0 && item.useStyle != 0)
        {
            if (altFunctionUse == 1)
            {
                altFunctionUse = 2;
            }
            if (item.shoot == 0)
            {
                itemRotation = 0f;
            }
            bool flag3 = ItemCheck_CheckCanUse(item);
            if (item.potion && flag3)
            {
                ApplyPotionDelay(item);
            }
            if (item.mana > 0 && flag3 && whoAmI == Main.myPlayer && item.buffType != 0 && item.buffTime != 0)
            {
                AddBuff(item.buffType, item.buffTime);
            }
            if (item.shoot <= 0 || !ProjectileID.Sets.MinionTargettingFeature[item.shoot] || altFunctionUse != 2)
            {
                ItemCheck_ApplyPetBuffs(item);
            }
            if (whoAmI == Main.myPlayer && gravDir == 1f && item.mountType != -1 && mount.CanMount(item.mountType, this))
            {
                mount.SetMount(item.mountType, this);
            }
            if ((item.shoot <= 0 || !ProjectileID.Sets.MinionTargettingFeature[item.shoot] || altFunctionUse != 2) && flag3 && whoAmI == Main.myPlayer && item.shoot >= 0 && (ProjectileID.Sets.LightPet[item.shoot] || Main.projPet[item.shoot]))
            {
                FreeUpPetsAndMinions(item);
            }
            if (flag3)
            {
                ItemCheck_StartActualUse(item);
            }
        }
        bool flag4 = controlUseItem;
        if (mount.Active && mount.Type == 8)
        {
            flag4 = controlUseItem || controlUseTile;
        }
        if (!flag4)
        {
            channel = false;
        }
        Item item2 = ((itemAnimation > 0) ? lastVisualizedSelectedItem : item);
        Rectangle drawHitbox = Item.GetDrawHitbox(item2.type, this);
        compositeFrontArm.enabled = false;
        compositeBackArm.enabled = false;
        if (itemAnimation > 0)
        {
            if (item.mana > 0)
            {
                ItemCheck_ApplyManaRegenDelay(item);
            }
            if (Main.dedServ)
            {
                itemHeight = item.height;
                itemWidth = item.width;
            }
            else
            {
                itemHeight = drawHitbox.Height;
                itemWidth = drawHitbox.Width;
            }
        }
        releaseUseItem = !controlUseItem;
        ItemLoader.HoldItem(item, this);
        if (itemAnimation > 0)
        {
            ItemCheck_ApplyUseStyle(heightOffsetHitboxCenter, item2, drawHitbox);
        }
        else
        {
            ItemCheck_ApplyHoldStyle(heightOffsetHitboxCenter, item2, drawHitbox);
        }
        if (!JustDroppedAnItem)
        {
            ItemCheck_EmitHeldItemLight(item);
            ItemCheck_EmitFoodParticles(item);
            ItemCheck_EmitDrinkParticles(item);
            _ = whoAmI;
            _ = Main.myPlayer;
            ItemCheck_OwnerOnlyCode(ref context, item, weaponDamage, drawHitbox);
            if (ItemTimeIsZero && itemAnimation > 0)
            {
                if (ItemLoader.UseItem(item, this) == true)
                {
                    ApplyItemTime(item, 1f, false);
                }
                if (item.hairDye >= 0)
                {
                    ApplyItemTime(item);
                    if (whoAmI == Main.myPlayer)
                    {
                        hairDye = item.hairDye;
                        NetMessage.SendData(4, -1, -1, null, whoAmI);
                    }
                }
                if (item.healLife > 0 || item.healMana > 0)
                {
                    ApplyLifeAndOrMana(item);
                    ApplyItemTime(item);
                    if (Main.myPlayer == whoAmI && item.type == 126 && breath == 0)
                    {
                        AchievementsHelper.HandleSpecialEvent(this, 25);
                    }
                }
                if (item.buffType > 0)
                {
                    if (whoAmI == Main.myPlayer && item.buffType != 90 && item.buffType != 27)
                    {
                        AddBuff(item.buffType, item.buffTime);
                    }
                    ApplyItemTime(item);
                }
                if (item.type == 678)
                {
                    if (Main.getGoodWorld)
                    {
                        ApplyItemTime(item);
                        if (whoAmI == Main.myPlayer)
{
                            for (int k = 0; k < 3; k++)
{
                                int type2 = 0;
                                int timeToAdd = 108000;
                                switch (Main.rand.Next(18))
{
                                case 0:
                                    type2 = 16;
                                    break;
                                case 1:
                                    type2 = 111;
                                    break;
                                case 2:
                                    type2 = 114;
                                    break;
                                case 3:
                                    type2 = 8;
                                    break;
                                case 4:
                                    type2 = 105;
                                    break;
                                case 5:
                                    type2 = 17;
                                    break;
                                case 6:
                                    type2 = 116;
                                    break;
                                case 7:
                                    type2 = 5;
                                    break;
                                case 8:
                                    type2 = 113;
                                    break;
                                case 9:
                                    type2 = 7;
                                    break;
                                case 10:
                                    type2 = 6;
                                    break;
                                case 11:
                                    type2 = 104;
                                    break;
                                case 12:
                                    type2 = 115;
                                    break;
                                case 13:
                                    type2 = 2;
                                    break;
                                case 14:
                                    type2 = 9;
                                    break;
                                case 15:
                                    type2 = 3;
                                    break;
                                case 16:
                                    type2 = 117;
                                    break;
                                case 17:
                                    type2 = 1;
                                    break;
                                }
                                AddBuff(type2, timeToAdd);
                            }
                        }
                    }
                    else
                    {
                        ApplyItemTime(item);
                        if (whoAmI == Main.myPlayer)
{
                            AddBuff(20, 216000);
                            AddBuff(22, 216000);
                            AddBuff(23, 216000);
                            AddBuff(24, 216000);
                            AddBuff(30, 216000);
                            AddBuff(31, 216000);
                            AddBuff(32, 216000);
                            AddBuff(33, 216000);
                            AddBuff(35, 216000);
                            AddBuff(36, 216000);
                            AddBuff(68, 216000);
                        }
                    }
                }
            }
            if ((item.type == 50 || item.type == 3124 || item.type == 3199 || item.type == 5358) && itemAnimation > 0)
            {
                if (Main.rand.Next(2) == 0)
                {
                    Dust.NewDust(position, width, height, 15, 0f, 0f, 150, default(Color), 1.1f);
                }
                if (ItemTimeIsZero)
                {
                    ApplyItemTime(item);
                }
                else if (itemTime == itemTimeMax / 2)
                {
                    for (int l = 0; l < 70; l++)
                    {
                        Dust.NewDust(position, width, height, 15, velocity.X * 0.5f, velocity.Y * 0.5f, 150, default(Color), 1.5f);
                    }
                    RemoveAllGrapplingHooks();
                    Spawn(PlayerSpawnContext.RecallFromItem);
                    for (int m = 0; m < 70; m++)
                    {
                        Dust.NewDust(position, width, height, 15, 0f, 0f, 150, default(Color), 1.5f);
                    }
                }
            }
            if ((item.type == 4263 || item.type == 5360) && itemAnimation > 0)
            {
                Vector2 vector = Vector2.UnitY.RotatedBy((float)itemAnimation * ((float)Math.PI * 2f) / 30f) * new Vector2(15f, 0f);
                for (int n = 0; n < 2; n++)
                {
                    if (Main.rand.Next(3) == 0)
                    {
                        Dust dust = Dust.NewDustPerfect(base.Bottom + vector, Dust.dustWater());
                        dust.velocity.Y *= 0f;
                        dust.velocity.Y -= 4.5f;
                        dust.velocity.X *= 1.5f;
                        dust.scale = 0.8f;
                        dust.alpha = 130;
                        dust.noGravity = true;
                        dust.fadeIn = 1.1f;
                    }
                }
                if (ItemTimeIsZero)
                {
                    ApplyItemTime(item);
                }
                else if (itemTime == item.useTime / 2)
                {
                    if (Main.netMode == 0)
                    {
                        MagicConch();
                    }
                    else if (Main.netMode == 1 && whoAmI == Main.myPlayer)
                    {
                        NetMessage.SendData(73, -1, -1, null, 1);
                    }
                }
            }
            if ((item.type == 4819 || item.type == 5361) && itemAnimation > 0)
            {
                Vector2 vector2 = Vector2.UnitY.RotatedBy((float)itemAnimation * ((float)Math.PI * 2f) / 30f) * new Vector2(15f, 0f);
                for (int num = 0; num < 2; num++)
                {
                    if (Main.rand.Next(3) == 0)
                    {
                        Dust dust2 = Dust.NewDustPerfect(base.Bottom + vector2, 35);
                        dust2.velocity.Y *= 0f;
                        dust2.velocity.Y -= 4.5f;
                        dust2.velocity.X *= 1.5f;
                        dust2.scale = 0.8f;
                        dust2.alpha = 130;
                        dust2.noGravity = true;
                        dust2.fadeIn = 1.1f;
                    }
                }
                if (ItemTimeIsZero)
                {
                    ApplyItemTime(item);
                }
                else if (itemTime == item.useTime / 2)
                {
                    if (Main.netMode == 0)
                    {
                        DemonConch();
                    }
                    else if (Main.netMode == 1 && whoAmI == Main.myPlayer)
                    {
                        NetMessage.SendData(73, -1, -1, null, 2);
                    }
                }
            }
            if (item.type == 5359 && itemAnimation > 0)
            {
                if (Main.rand.Next(2) == 0)
                {
                    int num8 = Main.rand.Next(4);
                    Color color = Color.Green;
                    switch (num8)
                    {
                    case 0:
                    case 1:
                        ((Color)(ref color))._002Ector(100, 255, 100);
                        break;
                    case 2:
                        color = Color.Yellow;
                        break;
                    case 3:
                        color = Color.White;
                        break;
                    }
                    Dust dust3 = Dust.NewDustPerfect(Main.rand.NextVector2FromRectangle(base.Hitbox), 267);
                    dust3.noGravity = true;
                    dust3.color = color;
                    dust3.velocity *= 2f;
                    dust3.scale = 0.8f + Main.rand.NextFloat() * 0.6f;
                }
                if (ItemTimeIsZero)
                {
                    ApplyItemTime(item);
                }
                else if (itemTime == item.useTime / 2)
                {
                    if (Main.netMode == 0)
                    {
                        Shellphone_Spawn();
                    }
                    else if (Main.netMode == 1 && whoAmI == Main.myPlayer)
                    {
                        NetMessage.SendData(73, -1, -1, null, 3);
                    }
                }
            }
            if (item.type == 2350 && itemAnimation > 0)
            {
                if (ItemTimeIsZero)
                {
                    ApplyItemTime(item);
                    SoundEngine.PlaySound(in SoundID.Item3, position);
                    for (int num9 = 0; num9 < 10; num9++)
                    {
                        Dust obj = Main.dust[Dust.NewDust(position, width, height, 15, velocity.X * 0.2f, velocity.Y * 0.2f, 150, Color.Cyan, 1.2f)];
                        obj.velocity *= 0.5f;
                    }
                }
                else if (itemTime == 20)
                {
                    SoundEngine.PlaySound(HeldItem.UseSound, position);
                    for (int num10 = 0; num10 < 70; num10++)
                    {
                        Dust obj2 = Main.dust[Dust.NewDust(position, width, height, 15, velocity.X * 0.2f, velocity.Y * 0.2f, 150, Color.Cyan, 1.2f)];
                        obj2.velocity *= 0.5f;
                    }
                    RemoveAllGrapplingHooks();
                    bool flag5 = immune;
                    int num11 = immuneTime;
                    Spawn(PlayerSpawnContext.RecallFromItem);
                    immune = flag5;
                    immuneTime = num11;
                    for (int num12 = 0; num12 < 70; num12++)
                    {
                        Dust obj3 = Main.dust[Dust.NewDust(position, width, height, 15, 0f, 0f, 150, Color.Cyan, 1.2f)];
                        obj3.velocity *= 0.5f;
                    }
                    if (ItemLoader.ConsumeItem(item, this) && item.stack > 0)
                    {
                        item.stack--;
                    }
                }
            }
            if (item.type == 4870 && itemAnimation > 0)
            {
                if (ItemTimeIsZero)
                {
                    ApplyItemTime(item);
                    SoundEngine.PlaySound(in SoundID.Item3, position);
                    for (int num13 = 0; num13 < 10; num13++)
                    {
                        Dust obj4 = Main.dust[Dust.NewDust(position, width, height, 15, velocity.X * 0.2f, velocity.Y * 0.2f, 150, Color.Cyan, 1.2f)];
                        obj4.velocity *= 0.5f;
                    }
                }
                else if (itemTime == 20)
                {
                    SoundEngine.PlaySound(HeldItem.UseSound, position);
                    for (int num14 = 0; num14 < 70; num14++)
                    {
                        Dust obj5 = Main.dust[Dust.NewDust(position, width, height, 15, velocity.X * 0.2f, velocity.Y * 0.2f, 150, Color.Cyan, 1.2f)];
                        obj5.velocity *= 0.5f;
                    }
                    if (whoAmI == Main.myPlayer)
                    {
                        DoPotionOfReturnTeleportationAndSetTheComebackPoint();
                    }
                    for (int num15 = 0; num15 < 70; num15++)
                    {
                        Dust obj6 = Main.dust[Dust.NewDust(position, width, height, 15, 0f, 0f, 150, Color.Cyan, 1.2f)];
                        obj6.velocity *= 0.5f;
                    }
                    if (ItemLoader.ConsumeItem(item, this) && item.stack > 0)
                    {
                        item.stack--;
                    }
                }
            }
            if (item.type == 2351 && itemAnimation > 0)
            {
                if (ItemTimeIsZero)
                {
                    ApplyItemTime(item);
                }
                else if (itemTime == 2)
                {
                    if (Main.netMode == 0)
                    {
                        TeleportationPotion();
                    }
                    else if (Main.netMode == 1 && whoAmI == Main.myPlayer)
                    {
                        NetMessage.SendData(73);
                    }
                    if (ItemLoader.ConsumeItem(item, this) && item.stack > 0)
                    {
                        item.stack--;
                    }
                }
            }
            if (item.type == 2756 && itemAnimation > 0)
            {
                if (ItemTimeIsZero)
                {
                    ApplyItemTime(item);
                }
                else if (itemTime == 2)
                {
                    if (whoAmI == Main.myPlayer)
                    {
                        Male = !Male;
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(4, -1, -1, null, whoAmI);
                        }
                    }
                    if (ItemLoader.ConsumeItem(item, this) && item.stack > 0)
                    {
                        item.stack--;
                    }
                }
                else
                {
                    float num2 = itemTimeMax;
                    num2 = (num2 - (float)itemTime) / num2;
                    float num3 = 44f;
                    float num4 = (float)Math.PI * 3f;
                    Vector2 vector3 = Utils.RotatedBy(new Vector2(15f, 0f), num4 * num2);
                    vector3.X *= direction;
                    Vector2 vector4 = default(Vector2);
                    for (int num5 = 0; num5 < 2; num5++)
                    {
                        int type3 = 221;
                        if (num5 == 1)
{
                            vector3.X *= -1f;
                            type3 = 219;
                        }
                        ((Vector2)(ref vector4))._002Ector(vector3.X, num3 * (1f - num2) - num3 + (float)(height / 2));
                        vector4 += base.Center;
                        int num6 = Dust.NewDust(vector4, 0, 0, type3, 0f, 0f, 100);
                        Main.dust[num6].position = vector4;
                        Main.dust[num6].noGravity = true;
                        Main.dust[num6].velocity = Vector2.Zero;
                        Main.dust[num6].scale = 1.3f;
                        Main.dust[num6].customData = this;
                    }
                }
            }
            if (whoAmI == Main.myPlayer)
            {
                if ((itemTimeMax != 0 && itemTime == itemTimeMax) | (!item.IsAir && item.IsNotTheSameAs(lastVisualizedSelectedItem)))
                {
                    lastVisualizedSelectedItem = item.Clone();
                }
            }
            else
            {
                lastVisualizedSelectedItem = item.Clone();
            }
            if (whoAmI == Main.myPlayer)
            {
                if (!dontConsumeWand && itemTimeMax != 0 && itemTime == itemTimeMax && item.tileWand > 0)
                {
                    int tileWand = item.tileWand;
                    for (int num7 = 0; num7 < 58; num7++)
                    {
                        if (tileWand == inventory[num7].type && inventory[num7].stack > 0)
{
                            if (ItemLoader.ConsumeItem(inventory[num7], this))
{
                                inventory[num7].stack--;
                            }
                            if (inventory[num7].stack <= 0)
{
                                inventory[num7] = new Item();
                            }
                            break;
                        }
                    }
                }
                if (itemTimeMax != 0 && itemTime == itemTimeMax && item.consumable && !context.SkipItemConsumption)
                {
                    bool flag6 = true;
                    if (item.ranged)
                    {
                        if (huntressAmmoCost90 && Main.rand.Next(10) == 0)
{
                            flag6 = false;
                        }
                        if (chloroAmmoCost80 && Main.rand.Next(5) == 0)
{
                            flag6 = false;
                        }
                        if (ammoCost80 && Main.rand.Next(5) == 0)
{
                            flag6 = false;
                        }
                        if (ammoCost75 && Main.rand.Next(4) == 0)
{
                            flag6 = false;
                        }
                    }
                    if (item.CountsAsClass(DamageClass.Throwing))
                    {
                        if (ThrownCost50 && Main.rand.Next(100) < 50)
{
                            flag6 = false;
                        }
                        if (ThrownCost33 && Main.rand.Next(100) < 33)
{
                            flag6 = false;
                        }
                    }
                    if (item.IsACoin)
                    {
                        flag6 = true;
                    }
                    bool? flag7 = ItemID.Sets.ForceConsumption[item.type];
                    if (flag7.HasValue)
                    {
                        flag6 = flag7.Value;
                    }
                    if (flag6 && ItemLoader.ConsumeItem(item, this))
                    {
                        if (item.stack > 0)
{
                            item.stack--;
                        }
                        if (item.stack <= 0)
{
                            itemTime = itemAnimation;
                            Main.blockMouse = true;
                        }
                    }
                }
                if (item.stack <= 0 && itemAnimation == 0)
                {
                    inventory[selectedItem] = new Item();
                }
                if (selectedItem == 58 && itemAnimation != 0)
                {
                    Main.mouseItem = item.Clone();
                }
            }
        }
        if (itemAnimation == 0)
        {
            JustDroppedAnItem = false;
        }
        if (whoAmI == Main.myPlayer && flag)
        {
            PlayerInput.TryEndingFastUse();
        }
    }
References Terraria.Mount.Active, Terraria.Player.AddBuff(), Terraria.Player.altFunctionUse, Terraria.Player.ammoCost75, Terraria.Player.ammoCost80, Terraria.Player.ApplyItemTime(), Terraria.Player.ApplyLifeAndOrMana(), Terraria.Player.ApplyPotionDelay(), Terraria.Player.ApplyReuseDelay(), Terraria.Player.breath, Terraria.Item.buffTime, Terraria.Item.buffType, Terraria.Mount.CanMount(), Terraria.Player.CCed, Terraria.Player.channel, Terraria.Player.chloroAmmoCost80, Terraria.Item.Clone(), Terraria.Item.consumable, Terraria.ModLoader.ItemLoader.ConsumeItem(), Terraria.Player.controlUseItem, Terraria.Player.controlUseTile, Terraria.Item.CountsAsClass(), Terraria.Player.cursorItemIconEnabled, Terraria.Player.cursorItemIconID, Terraria.Player.cursorItemIconPush, Terraria.Main.dedServ, Terraria.Player.DemonConch(), Terraria.Entity.direction, Terraria.Player.dontConsumeWand, Terraria.Player.DoPotionOfReturnTeleportationAndSetTheComebackPoint(), Terraria.Main.dust, Terraria.Dust.dustWater(), Terraria.Player.EmitMaxManaEffect(), Terraria.Player.Fishing_GetBait(), Terraria.Item.fishingPole, Terraria.ID.ItemID.Sets.ForceConsumption, Terraria.Player.FreeUpPetsAndMinions(), Terraria.Item.GetDrawHitbox(), Terraria.Main.getGoodWorld, Terraria.Player.GetWeaponDamage(), Terraria.Player.gravDir, Terraria.Item.hairDye, Terraria.Player.hairDye, Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Item.healLife, Terraria.Item.healMana, Terraria.Entity.height, Terraria.Player.HeightOffsetHitboxCenter, Terraria.Player.HeldItem, Terraria.ModLoader.ItemLoader.HoldItem(), Terraria.Player.huntressAmmoCost90, Terraria.Player.immune, Terraria.Player.immuneTime, Terraria.Player.inventory, Terraria.Item.IsACoin, Terraria.Item.IsNotTheSameAs(), Terraria.GameContent.Golf.GolfHelper.IsPlayerHoldingClub(), Terraria.ID.SoundID.Item3, Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, Terraria.Player.ItemCheck_ApplyHoldStyle(), Terraria.Player.ItemCheck_ApplyManaRegenDelay(), Terraria.Player.ItemCheck_ApplyPetBuffs(), Terraria.Player.ItemCheck_ApplyUseStyle(), Terraria.Player.ItemCheck_CheckCanUse(), Terraria.Player.ItemCheck_EmitDrinkParticles(), Terraria.Player.ItemCheck_EmitFoodParticles(), Terraria.Player.ItemCheck_EmitHeldItemLight(), Terraria.Player.ItemCheck_HackHoldStyles(), Terraria.Player.ItemCheck_HandleMount(), Terraria.Player.ItemCheck_HandleMPItemAnimation(), Terraria.Player.ItemCheck_OwnerOnlyCode(), Terraria.Player.ItemCheck_StartActualUse(), Terraria.Player.itemHeight, Terraria.Player.itemRotation, Terraria.Player.itemTime, Terraria.Player.ItemTimeIsZero, Terraria.Player.itemTimeMax, Terraria.Player.itemWidth, Terraria.Player.JustDroppedAnItem, Terraria.Player.lastVisualizedSelectedItem, Terraria.ID.ProjectileID.Sets.LightPet, Terraria.Player.MagicConch(), Terraria.Player.Male, Terraria.Item.mana, Terraria.ID.ProjectileID.Sets.MinionTargettingFeature, Terraria.Player.mount, Terraria.Item.mountType, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Item.potion, Terraria.Main.projPet, Terraria.Main.rand, Terraria.Item.ranged, Terraria.Player.releaseUseItem, Terraria.Player.RemoveAllGrapplingHooks(), Terraria.Player.reuseDelay, Terraria.Utils.RotatedBy(), Terraria.Player.selectedItem, Terraria.Player.selectItemOnNextUse, Terraria.NetMessage.SendData(), Terraria.Mount.SetMount(), Terraria.Player.Shellphone_Spawn(), Terraria.Item.shoot, Terraria.GameInput.PlayerInput.ShouldFastUseItem, Terraria.Player.SmartSelectLookup(), Terraria.Player.Spawn(), Terraria.Item.stack, Terraria.Player.TeleportationPotion(), Terraria.ModLoader.DamageClass.Throwing, Terraria.Player.ThrownCost33, Terraria.Player.ThrownCost50, Terraria.Item.tileWand, Terraria.GameInput.PlayerInput.TryEndingFastUse(), Terraria.Item.type, Terraria.Mount.Type, Terraria.Player.UpdatePlacementPreview(), Terraria.Item.useAmmo, Terraria.ModLoader.ItemLoader.UseItem(), Terraria.Item.UseSound, Terraria.Item.useStyle, Terraria.Item.useTime, Terraria.Entity.velocity, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.ItemCheck().