TModLoader: Terraria.Player.RefreshInfoAccsFromTeamPlayers
RefreshInfoAccsFromTeamPlayers()
void Terraria.Player.RefreshInfoAccsFromTeamPlayers () inline
Definition at line 10723 of file Player.cs.
    {
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode != 1 || whoAmI != Main.myPlayer)
        {
            return;
        }
        for (int i = 0; i < 255; i++)
        {
            if (i == whoAmI || !Main.player[i].active || Main.player[i].dead || Main.player[i].team != team || Main.player[i].team == 0)
            {
                continue;
            }
            int num = 800;
            Vector2 val = Main.player[i].Center - base.Center;
            if (((Vector2)(ref val)).Length() < (float)num)
            {
                if (Main.player[i].accWatch > accWatch)
                {
                    accWatch = Main.player[i].accWatch;
                }
                if (Main.player[i].accCompass > accCompass)
                {
                    accCompass = Main.player[i].accCompass;
                }
                if (Main.player[i].accDepthMeter > accDepthMeter)
                {
                    accDepthMeter = Main.player[i].accDepthMeter;
                }
                if (Main.player[i].accFishFinder)
                {
                    accFishFinder = true;
                }
                if (Main.player[i].accWeatherRadio)
                {
                    accWeatherRadio = true;
                }
                if (Main.player[i].accThirdEye)
                {
                    accThirdEye = true;
                }
                if (Main.player[i].accJarOfSouls)
                {
                    accJarOfSouls = true;
                }
                if (Main.player[i].accCalendar)
                {
                    accCalendar = true;
                }
                if (Main.player[i].accStopwatch)
                {
                    accStopwatch = true;
                }
                if (Main.player[i].accOreFinder)
                {
                    accOreFinder = true;
                }
                if (Main.player[i].accCritterGuide)
                {
                    accCritterGuide = true;
                }
                if (Main.player[i].accDreamCatcher)
                {
                    accDreamCatcher = true;
                }
                if (Main.player[i].hasLuck_LuckyHorseshoe)
                {
                    hasLuck_LuckyHorseshoe = true;
                }
                if (Main.player[i].hasLuck_LuckyCoin)
                {
                    hasLuck_LuckyCoin = true;
                }
                PlayerLoader.RefreshInfoAccessoriesFromTeamPlayers(this, Main.player[i]);
            }
        }
    }
References Terraria.Player.accCalendar, Terraria.Player.accCompass, Terraria.Player.accCritterGuide, Terraria.Player.accDepthMeter, Terraria.Player.accDreamCatcher, Terraria.Player.accFishFinder, Terraria.Player.accJarOfSouls, Terraria.Player.accOreFinder, Terraria.Player.accStopwatch, Terraria.Player.accThirdEye, Terraria.Player.accWatch, Terraria.Player.accWeatherRadio, Terraria.Player.hasLuck_LuckyCoin, Terraria.Player.hasLuck_LuckyHorseshoe, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.ModLoader.PlayerLoader.RefreshInfoAccessoriesFromTeamPlayers(), Terraria.Player.team, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.RefreshInfoAccs(), and Terraria.Player.UpdateEquips().