TModLoader: Terraria.Player.ApplyItemTime
ApplyItemTime()
void Terraria.Player.ApplyItemTime (Item sItem, float multiplier = 1f, bool? callUseItem = null) inline
    {
        if (!(callUseItem ?? ItemTimeIsZero) || ItemLoader.UseItem(sItem, this) != false)
        {
            SetItemTime(CombinedHooks.TotalUseTime((float)sItem.useTime * multiplier, this, sItem));
            ItemUsesThisAnimation++;
        }
    }
References Terraria.Player.ItemTimeIsZero, Terraria.Player.ItemUsesThisAnimation, Terraria.Player.SetItemTime(), Terraria.ModLoader.CombinedHooks.TotalUseTime(), and Terraria.ModLoader.ItemLoader.UseItem().
Referenced by Terraria.Player.ApplyCoating(), Terraria.Player.ApplyPaint(), Terraria.Player.ItemCheck_Inner(), Terraria.Player.ItemCheck_MinionAltFeatureUse(), Terraria.Player.ItemCheck_PlayInstruments(), Terraria.Player.ItemCheck_ReleaseCritter(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_TurretAltFeatureUse(), Terraria.Player.ItemCheck_UseArtisanLoaf(), Terraria.Player.ItemCheck_UseBossSpawners(), Terraria.Player.ItemCheck_UseBuckets(), Terraria.Player.ItemCheck_UseCombatBook(), Terraria.Player.ItemCheck_UseDemonHeart(), Terraria.Player.ItemCheck_UseEventItems(), Terraria.Player.ItemCheck_UseLawnMower(), Terraria.Player.ItemCheck_UseLifeCrystal(), Terraria.Player.ItemCheck_UseLifeFruit(), Terraria.Player.ItemCheck_UseManaCrystal(), Terraria.Player.ItemCheck_UseMinecartPowerUp(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.Player.ItemCheck_UsePeddlersSatchel(), Terraria.Player.ItemCheck_UseShimmerPermanentItems(), Terraria.Player.ItemCheck_UseTeleportRod(), Terraria.Player.ItemCheck_UseTorchGodsFavor(), Terraria.Player.ItemCheck_UseWiringTools(), Terraria.Player.LicenseOrExchangePet(), Terraria.Player.PlaceThing_ItemInExtractinator(), Terraria.Player.PlaceThing_PaintScrapper_LongMoss(), Terraria.Player.PlaceThing_PaintScrapper_TryScrapping(), Terraria.Player.PlaceThing_Tiles_PlaceIt(), Terraria.Player.PlaceThing_TryReplacingTiles(), Terraria.Player.PlaceThing_TryReplacingWalls(), Terraria.Player.PlaceThing_Walls(), Terraria.Player.PlaceThing_XMasTreeTops(), Terraria.Player.ShootFromCannon(), and Terraria.Player.UseShovel().