TModLoader: Terraria.Player.IsInTileInteractionRange
IsInTileInteractionRange()
bool Terraria.Player.IsInTileInteractionRange (int targetX, int targetY, TileReachCheckSettings settings) inline
    {
        settings.GetRanges(this, out var x, out var y);
        if (position.X / 16f - (float)x <= (float)targetX && (position.X + (float)width) / 16f + (float)x - 1f >= (float)targetX && position.Y / 16f - (float)y <= (float)targetY)
        {
            return (position.Y + (float)height) / 16f + (float)y - 2f >= (float)targetY;
        }
        return false;
    }
References Terraria.Entity.height, Terraria.Entity.position, and Terraria.Entity.width.
Referenced by Terraria.GameContent.ObjectInteractions.AHoverInteractionChecker.AttemptInteraction(), Terraria.Player.GetNearbyContainerProjectilesList(), Terraria.Player.IsProjectileInteractibleAndInInteractionRange(), Terraria.Player.LookForTileInteractions(), and Terraria.Player.TryInteractingWithMinecartTrackInNearbyArea().