TModLoader: Terraria.Player.StatusToPlayerPvP
StatusToPlayerPvP()
void Terraria.Player.StatusToPlayerPvP (int type, int i) inline
    {
        if (meleeEnchant > 0)
        {
            if (meleeEnchant == 1)
            {
                Main.player[i].AddBuff(70, 60 * Main.rand.Next(5, 10), quiet: false);
            }
            if (meleeEnchant == 2)
            {
                Main.player[i].AddBuff(39, 60 * Main.rand.Next(3, 7), quiet: false);
            }
            if (meleeEnchant == 3)
            {
                Main.player[i].AddBuff(24, 60 * Main.rand.Next(3, 7), quiet: false);
            }
            if (meleeEnchant == 5)
            {
                Main.player[i].AddBuff(69, 60 * Main.rand.Next(10, 20), quiet: false);
            }
            if (meleeEnchant == 6)
            {
                Main.player[i].AddBuff(31, 60 * Main.rand.Next(1, 4), quiet: false);
            }
            if (meleeEnchant == 8)
            {
                Main.player[i].AddBuff(20, 60 * Main.rand.Next(5, 10), quiet: false);
            }
        }
        if (frostBurn)
        {
            Main.player[i].AddBuff(324, 60 * Main.rand.Next(1, 8), quiet: false);
        }
        if (magmaStone)
        {
            if (Main.rand.Next(7) == 0)
            {
                Main.player[i].AddBuff(323, 360, quiet: false);
            }
            else if (Main.rand.Next(3) == 0)
            {
                Main.player[i].AddBuff(323, 120, quiet: false);
            }
            else
            {
                Main.player[i].AddBuff(323, 60, quiet: false);
            }
        }
        if (type == 5129)
        {
            Main.player[i].AddBuff(120, 300, quiet: false);
        }
        switch (type)
        {
        case 121:
            if (Main.rand.Next(2) == 0)
            {
                Main.player[i].AddBuff(24, 180, quiet: false);
            }
            break;
        case 3823:
            if (Main.rand.Next(4) == 0)
            {
                Main.player[i].AddBuff(323, 300, quiet: false);
            }
            break;
        case 5382:
            if (Main.rand.Next(3) == 0)
            {
                Main.player[i].AddBuff(323, 300, quiet: false);
            }
            break;
        case 122:
            if (Main.rand.Next(10) == 0)
            {
                Main.player[i].AddBuff(24, 180, quiet: false);
            }
            break;
        case 190:
            if (Main.rand.Next(4) == 0)
            {
                Main.player[i].AddBuff(20, 420, quiet: false);
            }
            break;
        case 217:
            if (Main.rand.Next(5) == 0)
            {
                Main.player[i].AddBuff(24, 180, quiet: false);
            }
            break;
        case 1123:
            if (Main.rand.Next(9) != 0)
            {
                Main.player[i].AddBuff(31, 120, quiet: false);
            }
            break;
        }
    }
References Terraria.Player.AddBuff(), Terraria.Player.frostBurn, Terraria.Player.magmaStone, Terraria.Player.meleeEnchant, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, and Terraria.Main.rand.
Referenced by Terraria.Player.ItemCheck_MeleeHitPVP().