TModLoader: Terraria.Player.PlaceThing_TryReplacingTiles
PlaceThing_TryReplacingTiles()
bool Terraria.Player.PlaceThing_TryReplacingTiles (bool canUse) inline private
Definition at line 38632 of file Player.cs.
    {
        bool flag = PlaceThing_ValidTileForReplacement();
        if (flag)
        {
            TileObject.objectPreview.Reset();
        }
        if (controlUseItem && canUse && Main.tile[tileTargetX, tileTargetY].active() && itemAnimation > 0 && ItemTimeIsZero && flag)
        {
            Item bestPickaxe = GetBestPickaxe();
            if (bestPickaxe == null)
            {
                return false;
            }
            Tile tile = Main.tile[tileTargetX, tileTargetY];
            _ = ref tile.type;
            int num = hitReplace.HitObject(tileTargetX, tileTargetY, 1);
            int pickaxeDamage = GetPickaxeDamage(tileTargetX, tileTargetY, bestPickaxe.pick, num, tile);
            if (pickaxeDamage == 0)
            {
                return false;
            }
            if (!WorldGen.IsTileReplacable(tileTargetX, tileTargetY))
            {
                return false;
            }
            if (!TileLoader.CanReplace(tileTargetX, tileTargetY, tile.type, HeldItem.createTile))
            {
                return false;
            }
            if (!TileLoader.CanPlace(tileTargetX, tileTargetY, HeldItem.createTile))
            {
                return false;
            }
            if (hitReplace.AddDamage(num, pickaxeDamage) < 100)
            {
                int num2 = WorldGen.KillTile_GetTileDustAmount(fail: true, tile, tileTargetX, tileTargetY);
                for (int i = 0; i < num2; i++)
                {
                    WorldGen.KillTile_MakeTileDust(tileTargetX, tileTargetY, tile);
                }
                WorldGen.KillTile_PlaySounds(tileTargetX, tileTargetY, fail: true, tile);
                if (HeldItem.consumable)
                {
                    HeldItem.stack++;
                }
                dontConsumeWand = true;
                ApplyItemTime(bestPickaxe, pickSpeed);
                SetItemAnimation((int)((float)bestPickaxe.useTime * pickSpeed));
                return false;
            }
            ClearMiningCacheAt(tileTargetX, tileTargetY, 1);
            int[,] typeCaches = PlaceThing_Tiles_GetAutoAccessoryCache();
            int num3 = HeldItem.createTile;
            int num4 = HeldItem.placeStyle;
            if (UsingBiomeTorches && num3 == 4)
            {
                BiomeTorchPlaceStyle(ref num3, ref num4);
            }
            if (UsingBiomeTorches && num3 == 215)
            {
                BiomeCampfirePlaceStyle(ref num3, ref num4);
            }
            if (WorldGen.ReplaceTile(tileTargetX, tileTargetY, (ushort)num3, num4))
            {
                canUse = false;
                NetMessage.SendData(17, -1, -1, null, 21, tileTargetX, tileTargetY, num3, num4);
                ApplyItemTime(HeldItem);
                SetItemAnimation(HeldItem.useAnimation);
                PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(typeCaches, num3);
            }
        }
        return canUse;
    }
References Terraria.HitTile.AddDamage(), Terraria.Player.ApplyItemTime(), Terraria.Player.BiomeCampfirePlaceStyle(), Terraria.Player.BiomeTorchPlaceStyle(), Terraria.ModLoader.TileLoader.CanPlace(), Terraria.ModLoader.TileLoader.CanReplace(), Terraria.Player.ClearMiningCacheAt(), Terraria.Item.consumable, Terraria.Player.controlUseItem, Terraria.Item.createTile, Terraria.Player.dontConsumeWand, Terraria.Player.GetBestPickaxe(), Terraria.Player.GetPickaxeDamage(), Terraria.Player.HeldItem, Terraria.HitTile.HitObject(), Terraria.Player.hitReplace, Terraria.WorldGen.IsTileReplacable(), Terraria.Player.itemAnimation, Terraria.Player.ItemTimeIsZero, Terraria.WorldGen.KillTile_GetTileDustAmount(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.WorldGen.KillTile_PlaySounds(), Terraria.TileObject.objectPreview, Terraria.Player.pickSpeed, Terraria.Item.placeStyle, Terraria.Player.PlaceThing_Tiles_GetAutoAccessoryCache(), Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(), Terraria.Player.PlaceThing_ValidTileForReplacement(), Terraria.WorldGen.ReplaceTile(), Terraria.NetMessage.SendData(), Terraria.Player.SetItemAnimation(), Terraria.Item.stack, Terraria.Main.tile, Terraria.Player.tileTargetX, Terraria.Player.tileTargetY, Terraria.Tile.type, Terraria.Item.useAnimation, and Terraria.Player.UsingBiomeTorches.
Referenced by Terraria.Player.PlaceThing_Tiles().