TModLoader: Terraria.Player.UseHealthMaxIncreasingItem
UseHealthMaxIncreasingItem()
void Terraria.Player.UseHealthMaxIncreasingItem (int increase) inline
    {
        if (increase < 0)
        {
            increase = 0;
        }
        statLifeMax += increase;
        statLifeMax2 += increase;
        statLife += increase;
        if (Main.myPlayer == whoAmI)
        {
            HealEffect(increase);
        }
    }
References Terraria.Player.HealEffect(), Terraria.Main.myPlayer, Terraria.Player.statLife, Terraria.Player.statLifeMax, Terraria.Player.statLifeMax2, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.ItemCheck_UseLifeCrystal(), and Terraria.Player.ItemCheck_UseLifeFruit().