TModLoader: Terraria.Player.UpdateArmorSets
UpdateArmorSets()
void Terraria.Player.UpdateArmorSets (int i) inline
    {
        //IL_0767: Unknown result type (might be due to invalid IL or missing references)
        //IL_0774: Unknown result type (might be due to invalid IL or missing references)
        //IL_0779: Unknown result type (might be due to invalid IL or missing references)
        //IL_077e: Unknown result type (might be due to invalid IL or missing references)
        //IL_09bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_09cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0999: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_168d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1692: Unknown result type (might be due to invalid IL or missing references)
        //IL_16b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_16c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_16ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_16cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_16f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1703: Unknown result type (might be due to invalid IL or missing references)
        //IL_1708: Unknown result type (might be due to invalid IL or missing references)
        //IL_15df: Unknown result type (might be due to invalid IL or missing references)
        //IL_15ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_1605: Unknown result type (might be due to invalid IL or missing references)
        //IL_1631: Unknown result type (might be due to invalid IL or missing references)
        //IL_163b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1640: Unknown result type (might be due to invalid IL or missing references)
        //IL_1750: Unknown result type (might be due to invalid IL or missing references)
        //IL_175a: Unknown result type (might be due to invalid IL or missing references)
        //IL_175f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1769: Unknown result type (might be due to invalid IL or missing references)
        //IL_176e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a01: Unknown result type (might be due to invalid IL or missing references)
        //IL_1930: Unknown result type (might be due to invalid IL or missing references)
        //IL_193b: Unknown result type (might be due to invalid IL or missing references)
        setBonus = "";
        if (body == 67 && legs == 56 && head >= 103 && head <= 105)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Shroomite");
            shroomiteStealth = true;
        }
        if ((head == 52 && body == 32 && legs == 31) || (head == 53 && body == 33 && legs == 32) || (head == 54 && body == 34 && legs == 33) || (head == 55 && body == 35 && legs == 34) || (head == 71 && body == 47 && legs == 43) || (head == 166 && body == 173 && legs == 108) || (head == 167 && body == 174 && legs == 109))
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Wood");
            ++statDefense;
        }
        if (head == 278 && body == 246 && legs == 234)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.AshWood");
            ashWoodBonus = true;
        }
        if ((head == 1 && body == 1 && legs == 1) || ((head == 72 || head == 2) && body == 2 && legs == 2) || (head == 47 && body == 28 && legs == 27))
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.MetalTier1");
            statDefense += 2;
        }
        if ((head == 3 && body == 3 && legs == 3) || ((head == 73 || head == 4) && body == 4 && legs == 4) || (head == 48 && body == 29 && legs == 28) || (head == 49 && body == 30 && legs == 29))
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.MetalTier2");
            statDefense += 3;
        }
        if (head == 50 && body == 31 && legs == 30)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Platinum");
            statDefense += 4;
        }
        if (head == 112 && body == 75 && legs == 64)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Pumpkin");
            allDamage += 0.1f;
        }
        if (head == 180 && body == 182 && legs == 122)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Gladiator");
            noKnockback = true;
        }
        if (head == 22 && body == 14 && legs == 14)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Ninja");
            moveSpeed += 0.2f;
        }
        if (head == 188 && body == 189 && legs == 129)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Fossil");
            ammoCost80 = true;
        }
        if ((head == 75 || head == 7) && body == 7 && legs == 7)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Bone");
            rangedCrit += 10f;
        }
        if (head == 157 && body == 105 && legs == 98)
        {
            int num = 0;
            setBonus = Language.GetTextValue("ArmorSetBonus.BeetleDamage");
            beetleOffense = true;
            beetleCounter -= 3f;
            beetleCounter -= beetleCountdown / 20;
            beetleCountdown++;
            if (beetleCounter < 0f)
            {
                beetleCounter = 0f;
            }
            int num10 = 400;
            int num11 = 1200;
            int num12 = 3600;
            if (beetleCounter > (float)(num10 + num11 + num12 + num11))
            {
                beetleCounter = num10 + num11 + num12 + num11;
            }
            if (beetleCounter > (float)(num10 + num11 + num12))
            {
                AddBuff(100, 5, quiet: false);
                num = 3;
            }
            else if (beetleCounter > (float)(num10 + num11))
            {
                AddBuff(99, 5, quiet: false);
                num = 2;
            }
            else if (beetleCounter > (float)num10)
            {
                AddBuff(98, 5, quiet: false);
                num = 1;
            }
            if (num < beetleOrbs)
            {
                beetleCountdown = 0;
            }
            else if (num > beetleOrbs)
            {
                beetleCounter += 200f;
            }
            if (num != beetleOrbs && beetleOrbs > 0)
            {
                for (int j = 0; j < maxBuffs; j++)
                {
                    if (buffType[j] >= 98 && buffType[j] <= 100 && buffType[j] != 97 + num)
                    {
                        DelBuff(j);
                    }
                }
            }
        }
        else if (head == 157 && body == 106 && legs == 98)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.BeetleDefense");
            beetleDefense = true;
            beetleCounter += 1f;
            int num13 = 180;
            if (beetleCounter >= (float)num13)
            {
                if (beetleOrbs > 0 && beetleOrbs < 3)
                {
                    for (int k = 0; k < maxBuffs; k++)
                    {
                        if (buffType[k] >= 95 && buffType[k] <= 96)
{
                            DelBuff(k);
                        }
                    }
                }
                if (beetleOrbs < 3)
                {
                    AddBuff(95 + beetleOrbs, 5, quiet: false);
                    beetleCounter = 0f;
                }
                else
                {
                    beetleCounter = num13;
                }
            }
        }
        if (!beetleDefense && !beetleOffense)
        {
            beetleCounter = 0f;
        }
        else
        {
            beetleFrameCounter++;
            if (beetleFrameCounter >= 1)
            {
                beetleFrameCounter = 0;
                beetleFrame++;
                if (beetleFrame > 2)
                {
                    beetleFrame = 0;
                }
            }
            for (int l = beetleOrbs; l < 3; l++)
            {
                beetlePos[l].X = 0f;
                beetlePos[l].Y = 0f;
            }
            for (int m = 0; m < beetleOrbs; m++)
            {
                ref Vector2 reference = ref beetlePos[m];
                reference += beetleVel[m];
                beetleVel[m].X += (float)Main.rand.Next(-100, 101) * 0.005f;
                beetleVel[m].Y += (float)Main.rand.Next(-100, 101) * 0.005f;
                float x = beetlePos[m].X;
                float y = beetlePos[m].Y;
                float num14 = (float)Math.Sqrt(x * x + y * y);
                if (num14 > 100f)
                {
                    num14 = 20f / num14;
                    x *= 0f - num14;
                    y *= 0f - num14;
                    int num15 = 10;
                    beetleVel[m].X = (beetleVel[m].X * (float)(num15 - 1) + x) / (float)num15;
                    beetleVel[m].Y = (beetleVel[m].Y * (float)(num15 - 1) + y) / (float)num15;
                }
                else if (num14 > 30f)
                {
                    num14 = 10f / num14;
                    x *= 0f - num14;
                    y *= 0f - num14;
                    int num16 = 20;
                    beetleVel[m].X = (beetleVel[m].X * (float)(num16 - 1) + x) / (float)num16;
                    beetleVel[m].Y = (beetleVel[m].Y * (float)(num16 - 1) + y) / (float)num16;
                }
                x = beetleVel[m].X;
                y = beetleVel[m].Y;
                num14 = (float)Math.Sqrt(x * x + y * y);
                if (num14 > 2f)
                {
                    ref Vector2 reference2 = ref beetleVel[m];
                    reference2 *= 0.9f;
                }
                ref Vector2 reference3 = ref beetlePos[m];
                reference3 -= velocity * 0.25f;
            }
        }
        if (head == 14 && ((body >= 58 && body <= 63) || body == 167 || body == 213))
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Wizard");
            magicCrit += 10f;
        }
        if (head == 159 && ((body >= 58 && body <= 63) || body == 167 || body == 213))
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.MagicHat");
            statManaMax2 += 60;
        }
        if ((head == 5 || head == 74) && (body == 5 || body == 48) && (legs == 5 || legs == 44))
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.ShadowScale");
            shadowArmor = true;
        }
        if (head == 57 && body == 37 && legs == 35)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Crimson");
            crimsonRegen = true;
        }
        if (head == 101 && body == 66 && legs == 55)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.SpectreHealing");
            ghostHeal = true;
            magicDamage -= 0.4f;
        }
        if (head == 156 && body == 66 && legs == 55)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.SpectreDamage");
            ghostHurt = true;
        }
        if (head == 6 && body == 6 && legs == 6)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Meteor");
            spaceGun = true;
        }
        if (head == 46 && body == 27 && legs == 26)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Frost");
            frostBurn = true;
            meleeDamage += 0.1f;
            rangedDamage += 0.1f;
        }
        if ((head == 76 || head == 8) && (body == 49 || body == 8) && (legs == 45 || legs == 8))
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Jungle");
            manaCost -= 0.16f;
        }
        if (head == 9 && body == 9 && legs == 9)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Molten");
            meleeDamage += 0.1f;
            buffImmune[24] = true;
        }
        if ((head == 58 || head == 77) && (body == 38 || body == 50) && (legs == 36 || legs == 46))
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Snow");
            buffImmune[46] = true;
            buffImmune[47] = true;
        }
        if (head == 11 && body == 20 && legs == 19)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Mining");
            pickSpeed -= 0.1f;
        }
        if (head == 216 && body == 20 && legs == 19)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Mining");
            pickSpeed -= 0.1f;
        }
        if (head == 78 && body == 51 && legs == 47)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.ChlorophyteMelee");
            AddBuff(60, 18000);
            endurance += 0.05f;
        }
        else if ((head == 80 || head == 79) && body == 51 && legs == 47)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Chlorophyte");
            AddBuff(60, 18000);
        }
        else if (crystalLeaf)
        {
            for (int n = 0; n < maxBuffs; n++)
            {
                if (buffType[n] == 60)
                {
                    DelBuff(n);
                }
            }
        }
        if (head == 161 && body == 169 && legs == 104)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Angler");
            anglerSetSpawnReduction = true;
        }
        if (head == 70 && body == 46 && legs == 42)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Cactus");
            cactusThorns = true;
        }
        if (head == 99 && body == 65 && legs == 54)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Turtle");
            endurance += 0.15f;
            thorns = 1f;
            turtleThorns = true;
        }
        if (body == 17 && legs == 16)
        {
            if (head == 29)
            {
                setBonus = Language.GetTextValue("ArmorSetBonus.CobaltCaster");
                manaCost -= 0.14f;
            }
            else if (head == 30)
            {
                setBonus = Language.GetTextValue("ArmorSetBonus.CobaltMelee");
                meleeSpeed += 0.15f;
            }
            else if (head == 31)
            {
                setBonus = Language.GetTextValue("ArmorSetBonus.CobaltRanged");
                ammoCost80 = true;
            }
        }
        if (body == 18 && legs == 17)
        {
            if (head == 32)
            {
                setBonus = Language.GetTextValue("ArmorSetBonus.MythrilCaster");
                manaCost -= 0.17f;
            }
            else if (head == 33)
            {
                setBonus = Language.GetTextValue("ArmorSetBonus.MythrilMelee");
                meleeCrit += 10f;
            }
            else if (head == 34)
            {
                setBonus = Language.GetTextValue("ArmorSetBonus.MythrilRanged");
                ammoCost80 = true;
            }
        }
        if (body == 19 && legs == 18)
        {
            if (head == 35)
            {
                setBonus = Language.GetTextValue("ArmorSetBonus.AdamantiteCaster");
                manaCost -= 0.19f;
            }
            else if (head == 36)
            {
                setBonus = Language.GetTextValue("ArmorSetBonus.AdamantiteMelee");
                meleeSpeed += 0.2f;
                moveSpeed += 0.2f;
            }
            else if (head == 37)
            {
                setBonus = Language.GetTextValue("ArmorSetBonus.AdamantiteRanged");
                ammoCost75 = true;
            }
        }
        if (body == 54 && legs == 49 && (head == 83 || head == 84 || head == 85))
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Palladium");
            onHitRegen = true;
        }
        if (body == 55 && legs == 50 && (head == 86 || head == 87 || head == 88))
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Orichalcum");
            onHitPetal = true;
        }
        if (body == 56 && legs == 51)
        {
            bool flag = false;
            if (head == 91)
            {
                setBonus = Language.GetTextValue("ArmorSetBonus.Titanium");
                flag = true;
            }
            else if (head == 89)
            {
                setBonus = Language.GetTextValue("ArmorSetBonus.Titanium");
                flag = true;
            }
            else if (head == 90)
            {
                setBonus = Language.GetTextValue("ArmorSetBonus.Titanium");
                flag = true;
            }
            if (flag)
            {
                onHitTitaniumStorm = true;
            }
        }
        if ((body == 24 || body == 229) && (legs == 23 || legs == 212) && (head == 42 || head == 41 || head == 43 || head == 254 || head == 257 || head == 256 || head == 255 || head == 258))
        {
            if (head == 254 || head == 258)
            {
                setBonus = Language.GetTextValue("ArmorSetBonus.HallowedSummoner");
                maxMinions += 2;
            }
            else
            {
                setBonus = Language.GetTextValue("ArmorSetBonus.Hallowed");
            }
            onHitDodge = true;
        }
        if (head == 261 && body == 230 && legs == 213)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.CrystalNinja");
            allDamage += 0.1f;
            allCrit += 10f;
            dashType = 5;
        }
        if (head == 82 && body == 53 && legs == 48)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Tiki");
            maxMinions++;
            whipRangeMultiplier += 0.2f;
        }
        if (head == 134 && body == 95 && legs == 79)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Spooky");
            minionDamage += 0.25f;
        }
        if (head == 160 && body == 168 && legs == 103)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Bee");
            minionDamage += 0.1f;
            if (itemAnimation > 0 && inventory[selectedItem].type == 1121)
            {
                AchievementsHelper.HandleSpecialEvent(this, 3);
            }
        }
        if (head == 162 && body == 170 && legs == 105)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Spider");
            minionDamage += 0.12f;
        }
        if (head == 171 && body == 177 && legs == 112)
        {
            endurance += 0.12f;
            setSolar = true;
            setBonus = Language.GetTextValue("ArmorSetBonus.Solar");
            solarCounter++;
            int num17 = 180;
            if (solarCounter >= num17)
            {
                if (solarShields > 0 && solarShields < 3)
                {
                    for (int num2 = 0; num2 < maxBuffs; num2++)
                    {
                        if (buffType[num2] >= 170 && buffType[num2] <= 171)
{
                            DelBuff(num2);
                        }
                    }
                }
                if (solarShields < 3)
                {
                    AddBuff(170 + solarShields, 5, quiet: false);
                    for (int num3 = 0; num3 < 16; num3++)
                    {
                        Dust obj = Main.dust[Dust.NewDust(position, width, height, 6, 0f, 0f, 100)];
                        obj.noGravity = true;
                        obj.scale = 1.7f;
                        obj.fadeIn = 0.5f;
                        obj.velocity *= 5f;
                        obj.shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                    }
                    solarCounter = 0;
                }
                else
                {
                    solarCounter = num17;
                }
            }
            for (int num4 = solarShields; num4 < 3; num4++)
            {
                solarShieldPos[num4] = Vector2.Zero;
            }
            for (int num5 = 0; num5 < solarShields; num5++)
            {
                ref Vector2 reference4 = ref solarShieldPos[num5];
                reference4 += solarShieldVel[num5];
                Vector2 vector = ((float)miscCounter / 100f * ((float)Math.PI * 2f) + (float)num5 * ((float)Math.PI * 2f / (float)solarShields)).ToRotationVector2() * 6f;
                vector.X = direction * 20;
                if (mount.Active && mount.Type == 52)
                {
                    vector.X = direction * 50;
                }
                solarShieldVel[num5] = (vector - solarShieldPos[num5]) * 0.2f;
            }
            if (dashDelay >= 0)
            {
                solarDashing = false;
                solarDashConsumedFlare = false;
            }
            bool flag2 = solarDashing && dashDelay < 0;
            if (solarShields > 0 || flag2)
            {
                dashType = 3;
            }
        }
        else
        {
            solarCounter = 0;
        }
        if (head == 169 && body == 175 && legs == 110)
        {
            setVortex = true;
            setBonus = Language.GetTextValue("ArmorSetBonus.Vortex", Language.GetTextValue(Main.ReversedUpDownArmorSetBonuses ? "Key.UP" : "Key.DOWN"));
        }
        else
        {
            vortexStealthActive = false;
        }
        if (head == 170 && body == 176 && legs == 111)
        {
            if (nebulaCD > 0)
            {
                nebulaCD--;
            }
            setNebula = true;
            setBonus = Language.GetTextValue("ArmorSetBonus.Nebula");
        }
        if (head == 189 && body == 190 && legs == 130)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Stardust", Language.GetTextValue(Main.ReversedUpDownArmorSetBonuses ? "Key.UP" : "Key.DOWN"));
            setStardust = true;
            if (whoAmI == Main.myPlayer)
            {
                if (FindBuffIndex(187) == -1)
                {
                    AddBuff(187, 3600);
                }
                if (ownedProjectileCounts[623] < 1)
                {
                    int num6 = 10;
                    int num7 = 30;
                    int num8 = Projectile.NewProjectile(GetProjectileSource_SetBonus(7), base.Center.X, base.Center.Y, 0f, -1f, 623, num7, num6, Main.myPlayer);
                    Main.projectile[num8].originalDamage = num7;
                }
            }
        }
        else if (FindBuffIndex(187) != -1)
        {
            DelBuff(FindBuffIndex(187));
        }
        if (head == 200 && body == 198 && legs == 142)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.Forbidden", Language.GetTextValue(Main.ReversedUpDownArmorSetBonuses ? "Key.UP" : "Key.DOWN"));
            setForbidden = true;
            UpdateForbiddenSetLock();
            Lighting.AddLight(base.Center, 0.8f, 0.7f, 0.2f);
        }
        if (head == 204 && body == 201 && legs == 145)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.SquireTier2");
            setSquireT2 = true;
            maxTurrets++;
        }
        if (head == 203 && body == 200 && legs == 144)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.ApprenticeTier2");
            setApprenticeT2 = true;
            maxTurrets++;
        }
        if (head == 205 && body == 202 && (legs == 147 || legs == 146))
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.HuntressTier2");
            setHuntressT2 = true;
            maxTurrets++;
        }
        if (head == 206 && body == 203 && legs == 148)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.MonkTier2");
            setMonkT2 = true;
            maxTurrets++;
        }
        if (head == 210 && body == 204 && legs == 152)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.SquireTier3");
            setSquireT3 = true;
            setSquireT2 = true;
            maxTurrets++;
        }
        if (head == 211 && body == 205 && legs == 153)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.ApprenticeTier3");
            setApprenticeT3 = true;
            setApprenticeT2 = true;
            maxTurrets++;
        }
        if (head == 212 && body == 206 && (legs == 154 || legs == 155))
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.HuntressTier3");
            setHuntressT3 = true;
            setHuntressT2 = true;
            maxTurrets++;
        }
        if (head == 213 && body == 207 && legs == 156)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.MonkTier3");
            setMonkT3 = true;
            setMonkT2 = true;
            maxTurrets++;
        }
        if (head == 185 && body == 187 && legs == 127)
        {
            setBonus = Language.GetTextValue("ArmorSetBonus.ObsidianOutlaw");
            minionDamage += 0.15f;
            whipRangeMultiplier += 0.3f;
            float num9 = 1.15f;
            summonerWeaponSpeedBonus += num9 - 1f;
        }
        ApplyArmorSoundAndDustChanges();
        ItemLoader.UpdateArmorSet(this, armor[0], armor[1], armor[2]);
    }
References Terraria.Mount.Active, Terraria.Player.AddBuff(), Terraria.Lighting.AddLight(), Terraria.Player.allCrit, Terraria.Player.allDamage, Terraria.Player.ammoCost75, Terraria.Player.ammoCost80, Terraria.Player.anglerSetSpawnReduction, Terraria.Player.ApplyArmorSoundAndDustChanges(), Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.armor, Terraria.Player.ArmorSetDye(), Terraria.Player.ashWoodBonus, Terraria.Player.beetleCountdown, Terraria.Player.beetleCounter, Terraria.Player.beetleDefense, Terraria.Player.beetleFrame, Terraria.Player.beetleFrameCounter, Terraria.Player.beetleOffense, Terraria.Player.beetleOrbs, Terraria.Player.beetlePos, Terraria.Player.beetleVel, Terraria.Player.body, Terraria.Player.buffImmune, Terraria.Player.buffType, Terraria.Player.cactusThorns, Terraria.Player.crimsonRegen, Terraria.Player.crystalLeaf, Terraria.Player.dashDelay, Terraria.Player.dashType, Terraria.Player.DelBuff(), Terraria.Entity.direction, Terraria.Main.dust, Terraria.Player.endurance, Terraria.Player.FindBuffIndex(), Terraria.Player.frostBurn, Terraria.Player.GetProjectileSource_SetBonus(), Terraria.Localization.Language.GetTextValue(), Terraria.Player.ghostHeal, Terraria.Player.ghostHurt, Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Player.head, Terraria.Entity.height, Terraria.Player.inventory, Terraria.Player.itemAnimation, Terraria.Player.legs, Terraria.Player.magicCrit, Terraria.Player.magicDamage, Terraria.Player.manaCost, Terraria.Player.maxBuffs, Terraria.Player.maxMinions, Terraria.Player.maxTurrets, Terraria.Player.meleeCrit, Terraria.Player.meleeDamage, Terraria.Player.meleeSpeed, Terraria.Player.minionDamage, Terraria.Player.miscCounter, Terraria.Player.mount, Terraria.Player.moveSpeed, Terraria.Main.myPlayer, Terraria.Player.nebulaCD, Terraria.Dust.NewDust(), Terraria.Projectile.NewProjectile(), Terraria.Player.noKnockback, Terraria.Player.onHitDodge, Terraria.Player.onHitPetal, Terraria.Player.onHitRegen, Terraria.Player.onHitTitaniumStorm, Terraria.Player.ownedProjectileCounts, Terraria.Player.pickSpeed, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.rand, Terraria.Player.rangedCrit, Terraria.Player.rangedDamage, Terraria.Main.ReversedUpDownArmorSetBonuses, Terraria.Player.selectedItem, Terraria.Player.setApprenticeT2, Terraria.Player.setApprenticeT3, Terraria.Player.setBonus, Terraria.Player.setForbidden, Terraria.Player.setHuntressT2, Terraria.Player.setHuntressT3, Terraria.Player.setMonkT2, Terraria.Player.setMonkT3, Terraria.Player.setNebula, Terraria.Player.setSolar, Terraria.Player.setSquireT2, Terraria.Player.setSquireT3, Terraria.Player.setStardust, Terraria.Player.setVortex, Terraria.Player.shadowArmor, Terraria.Player.shroomiteStealth, Terraria.Player.solarCounter, Terraria.Player.solarDashConsumedFlare, Terraria.Player.solarDashing, Terraria.Player.solarShieldPos, Terraria.Player.solarShields, Terraria.Player.solarShieldVel, Terraria.Player.spaceGun, Terraria.Player.statDefense, Terraria.Player.statManaMax2, Terraria.Player.summonerWeaponSpeedBonus, Terraria.Player.thorns, Terraria.Player.turtleThorns, Terraria.Mount.Type, Terraria.ModLoader.ItemLoader.UpdateArmorSet(), Terraria.Player.UpdateForbiddenSetLock(), Terraria.Entity.velocity, Terraria.Player.vortexStealthActive, Terraria.Player.whipRangeMultiplier, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.Update().