TModLoader: Terraria.Player.KillMe
KillMe()
void Terraria.Player.KillMe (PlayerDeathReason damageSource, double dmg, int hitDirection, bool pvp = false) inline
    {
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_034e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0568: Unknown result type (might be due to invalid IL or missing references)
        //IL_0577: Unknown result type (might be due to invalid IL or missing references)
        //IL_0998: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0806: Unknown result type (might be due to invalid IL or missing references)
        //IL_080c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0827: Unknown result type (might be due to invalid IL or missing references)
        //IL_0849: Unknown result type (might be due to invalid IL or missing references)
        //IL_084f: Unknown result type (might be due to invalid IL or missing references)
        //IL_08dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0901: Unknown result type (might be due to invalid IL or missing references)
        //IL_0889: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ae: Unknown result type (might be due to invalid IL or missing references)
        if (creativeGodMode || dead)
        {
            return;
        }
        StopVanityActions();
        bool playSound = true;
        bool genGore = true;
        if (!PlayerLoader.PreKill(this, dmg, hitDirection, pvp, ref playSound, ref genGore, ref damageSource))
        {
            return;
        }
        if (pvp)
        {
            pvpDeath = true;
        }
        if (trapDebuffSource)
        {
            AchievementsHelper.HandleSpecialEvent(this, 4);
        }
        if (Main.myPlayer == whoAmI && _framesLeftEligibleForDeadmansChestDeathAchievement > 0)
        {
            AchievementsHelper.HandleSpecialEvent(this, 23);
        }
        if (whoAmI == Main.myPlayer)
        {
            Main.NotifyOfEvent(GameNotificationType.SpawnOrDeath);
        }
        if (pvpDeath)
        {
            numberOfDeathsPVP++;
        }
        else
        {
            numberOfDeathsPVE++;
        }
        lastDeathPostion = base.Center;
        lastDeathTime = DateTime.Now;
        showLastDeath = true;
        bool overFlowing;
        long coinsOwned = Utils.CoinsCount(out overFlowing, inventory);
        if (Main.myPlayer == whoAmI)
        {
            lostCoins = coinsOwned;
            lostCoinString = Main.ValueToCoins(lostCoins);
        }
        if (Main.myPlayer == whoAmI)
        {
            EndOngoingTorchGodEvent();
        }
        if (Main.myPlayer == whoAmI)
        {
            Main.mapFullscreen = false;
        }
        if (Main.myPlayer == whoAmI)
        {
            trashItem.SetDefaults();
            if (difficulty == 0 || difficulty == 3)
            {
                for (int i = 0; i < 59; i++)
                {
                    if (inventory[i].stack > 0 && ((inventory[i].type >= 1522 && inventory[i].type <= 1527) || inventory[i].type == 3643))
                    {
                        int num = Item.NewItem(GetItemSource_Death(), (int)position.X, (int)position.Y, width, height, inventory[i].type);
                        Main.item[num].netDefaults(inventory[i].netID);
                        Main.item[num].Prefix(inventory[i].prefix);
                        Main.item[num].stack = inventory[i].stack;
                        Main.item[num].velocity.Y = (float)Main.rand.Next(-20, 1) * 0.2f;
                        Main.item[num].velocity.X = (float)Main.rand.Next(-20, 21) * 0.2f;
                        Main.item[num].noGrabDelay = 100;
                        Main.item[num].favorited = false;
                        Main.item[num].newAndShiny = false;
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(21, -1, -1, null, num);
                        }
                        inventory[i].SetDefaults();
                    }
                }
            }
            else if (difficulty == 1)
            {
                DropItems();
            }
            else if (difficulty == 2)
            {
                DropItems();
                KillMeForGood();
            }
        }
        if (playSound)
        {
            if (Main.dontStarveWorld || Main.tenthAnniversaryWorld)
            {
                SoundStyle style = (Male ? SoundID.DSTMaleHurt : SoundID.DSTFemaleHurt);
                SoundEngine.PlaySound(in style, position);
            }
            else
            {
                SoundEngine.PlaySound(5, (int)position.X, (int)position.Y);
            }
        }
        if (Main.tenthAnniversaryWorld)
        {
            for (int j = 0; j < 85; j++)
            {
                int type = Main.rand.Next(139, 143);
                int num2 = Dust.NewDust(new Vector2(position.X, position.Y), width, height, type, 0f, -10f, 0, default(Color), 1.2f);
                Main.dust[num2].velocity.X += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num2].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num2].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num2].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.dust[num2].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                Main.dust[num2].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
                Main.dust[num2].scale *= 1f + (float)Main.rand.Next(-30, 31) * 0.01f;
            }
            for (int k = 0; k < 40; k++)
            {
                int type2 = Main.rand.Next(276, 283);
                int num3 = Gore.NewGore(position, new Vector2(0f, -10f), type2);
                Main.gore[num3].velocity.X += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num3].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num3].velocity.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num3].velocity.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.01f;
                Main.gore[num3].scale *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                Main.gore[num3].velocity.X += (float)Main.rand.Next(-50, 51) * 0.05f;
                Main.gore[num3].velocity.Y += (float)Main.rand.Next(-50, 51) * 0.05f;
            }
        }
        headVelocity.Y = (float)Main.rand.Next(-40, -10) * 0.1f;
        bodyVelocity.Y = (float)Main.rand.Next(-40, -10) * 0.1f;
        legVelocity.Y = (float)Main.rand.Next(-40, -10) * 0.1f;
        headVelocity.X = (float)Main.rand.Next(-20, 21) * 0.1f + (float)(2 * hitDirection);
        bodyVelocity.X = (float)Main.rand.Next(-20, 21) * 0.1f + (float)(2 * hitDirection);
        legVelocity.X = (float)Main.rand.Next(-20, 21) * 0.1f + (float)(2 * hitDirection);
        if (stoned || !genGore)
        {
            headPosition = Vector2.Zero;
            bodyPosition = Vector2.Zero;
            legPosition = Vector2.Zero;
        }
        if (genGore)
        {
            for (int l = 0; l < 100; l++)
            {
                if (stoned)
                {
                    Dust.NewDust(position, width, height, 1, 2 * hitDirection, -2f);
                }
                else if (frostArmor)
                {
                    int num4 = Dust.NewDust(position, width, height, 135, 2 * hitDirection, -2f);
                    Main.dust[num4].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                }
                else if (boneArmor)
                {
                    int num5 = Dust.NewDust(position, width, height, 26, 2 * hitDirection, -2f);
                    Main.dust[num5].shader = GameShaders.Armor.GetSecondaryShader(ArmorSetDye(), this);
                }
                else
                {
                    Dust.NewDust(position, width, height, 5, 2 * hitDirection, -2f);
                }
            }
        }
        mount.Dismount(this);
        dead = true;
        respawnTimer = GetRespawnTime(pvp);
        PlayerLoader.Kill(this, dmg, hitDirection, pvp, damageSource);
        immuneAlpha = 0;
        if (!ChildSafety.Disabled)
        {
            immuneAlpha = 255;
        }
        palladiumRegen = false;
        iceBarrier = false;
        crystalLeaf = false;
        NetworkText deathText = damageSource.GetDeathText(name);
        if (Main.netMode == 2)
        {
            ChatHelper.BroadcastChatMessage(deathText, new Color(225, 25, 25));
        }
        else if (Main.netMode == 0)
        {
            Main.NewText(deathText.ToString(), 225, 25, 25);
        }
        if (Main.netMode == 1 && whoAmI == Main.myPlayer)
        {
            NetMessage.SendPlayerDeath(whoAmI, damageSource, (int)dmg, hitDirection, pvp);
        }
        if (whoAmI == Main.myPlayer && (difficulty == 0 || difficulty == 3))
        {
            if (!pvp)
            {
                DropCoins();
            }
            else
            {
                lostCoins = 0L;
                lostCoinString = Main.ValueToCoins(lostCoins);
            }
        }
        DropTombstone(coinsOwned, deathText, hitDirection);
        if (whoAmI != Main.myPlayer)
        {
            return;
        }
        try
        {
            WorldGen.saveToonWhilePlaying();
        }
        catch
        {
        }
    }
References Terraria.Player._framesLeftEligibleForDeadmansChestDeathAchievement, Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.ArmorSetDye(), Terraria.Player.bodyPosition, Terraria.Player.boneArmor, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Utils.CoinsCount(), Terraria.Player.creativeGodMode, Terraria.Player.crystalLeaf, Terraria.Player.dead, Terraria.Player.difficulty, Terraria.GameContent.ChildSafety.Disabled, Terraria.Mount.Dismount(), Terraria.Main.dontStarveWorld, Terraria.Player.DropCoins(), Terraria.Player.DropItems(), Terraria.Player.DropTombstone(), Terraria.ID.SoundID.DSTFemaleHurt, Terraria.Main.dust, Terraria.Player.EndOngoingTorchGodEvent(), Terraria.Player.frostArmor, Terraria.Player.GetItemSource_Death(), Terraria.Player.GetRespawnTime(), Terraria.Main.gore, Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.Player.headPosition, Terraria.Entity.height, Terraria.Player.iceBarrier, Terraria.Player.immuneAlpha, Terraria.Player.inventory, Terraria.Main.item, Terraria.ModLoader.PlayerLoader.Kill(), Terraria.Player.KillMeForGood(), Terraria.Player.lastDeathPostion, Terraria.Player.lastDeathTime, Terraria.Player.legPosition, Terraria.Player.lostCoins, Terraria.Player.lostCoinString, Terraria.Player.Male, Terraria.Player.mount, Terraria.Main.myPlayer, Terraria.Player.name, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Item.NewItem(), Terraria.Main.NewText(), Terraria.Main.NotifyOfEvent(), Terraria.Player.numberOfDeathsPVE, Terraria.Player.numberOfDeathsPVP, Terraria.Player.palladiumRegen, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.ModLoader.PlayerLoader.PreKill(), Terraria.Player.pvpDeath, Terraria.Main.rand, Terraria.Player.respawnTimer, Terraria.WorldGen.saveToonWhilePlaying(), Terraria.NetMessage.SendData(), Terraria.NetMessage.SendPlayerDeath(), Terraria.Item.SetDefaults(), Terraria.Player.showLastDeath, Terraria.Item.stack, Terraria.Player.stoned, Terraria.Player.StopVanityActions(), Terraria.Main.tenthAnniversaryWorld, Terraria.Player.trapDebuffSource, Terraria.Player.trashItem, Terraria.Item.type, Terraria.Main.ValueToCoins(), Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Player.BordersMovement(), Terraria.Player.CheckDrowning(), Terraria.Player.Hurt(), Terraria.Player.ItemCheck_UseTeleportRod(), Terraria.Player.UpdateLifeRegen(), and Terraria.Player.WOFTongue().