TModLoader: Terraria.Player.Counterweight
Counterweight()
void Terraria.Player.Counterweight (Vector2 hitPos, int dmg, float kb) inline
    {
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_012e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        if (!yoyoGlove && counterWeight <= 0)
        {
            return;
        }
        int num = -1;
        int num2 = 0;
        int num3 = 0;
        for (int i = 0; i < 1000; i++)
        {
            if (Main.projectile[i].active && Main.projectile[i].owner == whoAmI)
            {
                if (Main.projectile[i].counterweight)
                {
                    num3++;
                }
                else if (Main.projectile[i].aiStyle == 99)
                {
                    num2++;
                    num = i;
                }
            }
        }
        if (yoyoGlove && num2 < 2)
        {
            if (num >= 0)
            {
                Vector2 vector = hitPos - base.Center;
                ((Vector2)(ref vector)).Normalize();
                vector *= 16f;
                Projectile.NewProjectile(Entity.InheritSource(Main.projectile[num]), base.Center.X, base.Center.Y, vector.X, vector.Y, Main.projectile[num].type, Main.projectile[num].damage, Main.projectile[num].knockBack, whoAmI, 1f);
            }
        }
        else if (num3 < num2)
        {
            Vector2 vector2 = hitPos - base.Center;
            ((Vector2)(ref vector2)).Normalize();
            vector2 *= 16f;
            float knockBack = (kb + 6f) / 2f;
            IEntitySource spawnSource = Entity.InheritSource(Main.projectile[num]);
            if (num3 > 0)
            {
                Projectile.NewProjectile(spawnSource, base.Center.X, base.Center.Y, vector2.X, vector2.Y, counterWeight, (int)((double)dmg * 0.8), knockBack, whoAmI, 1f);
            }
            else
            {
                Projectile.NewProjectile(spawnSource, base.Center.X, base.Center.Y, vector2.X, vector2.Y, counterWeight, (int)((double)dmg * 0.8), knockBack, whoAmI);
            }
        }
    }
References Terraria.Entity.active, Terraria.Projectile.aiStyle, Terraria.Player.counterWeight, Terraria.Projectile.counterweight, Terraria.Projectile.damage, Terraria.Entity.InheritSource(), Terraria.Projectile.knockBack, Terraria.Projectile.NewProjectile(), Terraria.Projectile.owner, Terraria.Main.projectile, Terraria.Projectile.type, Terraria.Entity.whoAmI, and Terraria.Player.yoyoGlove.
Referenced by Terraria.Projectile.Damage().