TModLoader: Terraria.GameContent.Golf.FancyGolfPredictionLine.Draw
Draw()
void Terraria.GameContent.Golf.FancyGolfPredictionLine.Draw (Camera camera, SpriteBatch spriteBatch, float chargeProgress) inline
    {
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        _drawer.Begin(camera.GameViewMatrix.TransformationMatrix);
        _ = _positions.Count;
        Texture2D value = TextureAssets.Extra[33].Value;
        Vector2 val = new Vector2(3.5f, 3.5f);
        Vector2 origin = value.Size() / 2f;
        Vector2 vector2 = val - camera.UnscaledPosition;
        float num = 0f;
        float num2 = 0f;
        for (int i = 0; i < _positions.Count - 1; i++)
        {
            GetSectionLength(i, out var length, out var _);
            if (length != 0f)
            {
                for (; num < num2 + length; num += 4f)
                {
                    float num3 = (num - num2) / length + (float)i;
                    Vector2 position = GetPosition((num - num2) / length + (float)i);
                    Color color = GetColor2(num3);
                    color *= MathHelper.Clamp(2f - 2f * num3 / (float)(_positions.Count - 1), 0f, 1f);
                    spriteBatch.Draw(value, position + vector2, (Rectangle?)null, color, 0f, origin, GetScale(num), (SpriteEffects)0, 0f);
                }
                num2 += length;
            }
        }
        _drawer.End();
    }
References Terraria.GameContent.Golf.FancyGolfPredictionLine._drawer, Terraria.GameContent.Golf.FancyGolfPredictionLine._positions, Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.Golf.FancyGolfPredictionLine.GetColor2(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetPosition(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetScale(), and Terraria.GameContent.Golf.FancyGolfPredictionLine.GetSectionLength().
Referenced by Terraria.GameContent.Golf.GolfHelper.DrawPredictionLine().