TModLoader: Terraria.ModLoader.BossBarLoader.HandleStyle
HandleStyle()
static void Terraria.ModLoader.BossBarLoader.HandleStyle () inline static package
Checks if the style was changed and applies it, saves the config if required.
Definition at line 121 of file BossBarLoader.cs.
    {
        if (switchToStyle != null && switchToStyle != CurrentStyle)
        {
            CurrentStyle.OnDeselected();
            CurrentStyle = switchToStyle;
            CurrentStyle.OnSelected();
        }
        switchToStyle = null;
        if (!styleLoading && CurrentStyle.FullName != lastSelectedStyle)
        {
            lastSelectedStyle = CurrentStyle.FullName;
            Main.SaveSettings();
        }
    }
References Terraria.ModLoader.BossBarLoader.CurrentStyle, Terraria.ModLoader.ModType< TEntity, TModType >.FullName, Terraria.ModLoader.BossBarLoader.lastSelectedStyle, Terraria.ModLoader.ModBossBarStyle.OnDeselected(), Terraria.ModLoader.ModBossBarStyle.OnSelected(), Terraria.Main.SaveSettings(), Terraria.ModLoader.BossBarLoader.styleLoading, and Terraria.ModLoader.BossBarLoader.switchToStyle.
Referenced by Terraria.Main.UpdateUIStates().