TModLoader: Terraria.ModLoader.BossBarLoader.DrawFancyBar_TML
DrawFancyBar_TML()
static void Terraria.ModLoader.BossBarLoader.DrawFancyBar_TML (SpriteBatch spriteBatch, BossBarDrawParams drawParams) inline static
Draws a healthbar with fixed barTexture dimensions (516x348) where the effective bar top left starts at 32x24, and is 456x22 big.
The icon top left starts at 4x20, and is 26x28 big
Frame 0 contains the frame (outline)
Frame 1 contains the 2 pixel wide strip for the tip of the bar itself
Frame 2 contains the 2 pixel wide strip for the bar itself, stretches out
Frame 3 contains the background
Frame 4 contains the 2 pixel wide strip for the tip of the bar itself (optional shield)
Frame 5 contains the 2 pixel wide strip for the bar itself, stretches out (optional shield)
Supply your own textures if you need a different shape/color, otherwise you can make your own method to draw it
Parameters
spriteBatch The spriteBatch that is drawn on
drawParams The draw parameters for the boss bar
Definition at line 255 of file BossBarLoader.cs.
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_019f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_0209: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0212: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_0245: Unknown result type (might be due to invalid IL or missing references)
        //IL_024a: Unknown result type (might be due to invalid IL or missing references)
        //IL_024e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        //IL_0257: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_0272: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0283: Unknown result type (might be due to invalid IL or missing references)
        //IL_0288: Unknown result type (might be due to invalid IL or missing references)
        //IL_028f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0296: Unknown result type (might be due to invalid IL or missing references)
        //IL_0332: Unknown result type (might be due to invalid IL or missing references)
        //IL_0337: Unknown result type (might be due to invalid IL or missing references)
        //IL_033b: Unknown result type (might be due to invalid IL or missing references)
        //IL_033d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0344: Unknown result type (might be due to invalid IL or missing references)
        //IL_034e: Unknown result type (might be due to invalid IL or missing references)
        //IL_036d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0383: Unknown result type (might be due to invalid IL or missing references)
        //IL_038a: Unknown result type (might be due to invalid IL or missing references)
        //IL_038f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0394: Unknown result type (might be due to invalid IL or missing references)
        //IL_0398: Unknown result type (might be due to invalid IL or missing references)
        //IL_039a: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0302: Unknown result type (might be due to invalid IL or missing references)
        //IL_0307: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0315: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        BossBarDrawParams bossBarDrawParams = drawParams;
        var (barTexture, center, iconTexture, iconFrame, iconColor, life, lifeMax, shield, shieldMax, iconScale, showText, textOffset) = (BossBarDrawParams)(ref bossBarDrawParams);
        Point barSize = default(Point);
        ((Point)(ref barSize))._002Ector(456, 22);
        Point topLeftOffset = default(Point);
        ((Point)(ref topLeftOffset))._002Ector(32, 24);
        int frameCount = 6;
        Rectangle bgFrame = barTexture.Frame(1, frameCount, 0, 3);
        Color bgColor = Color.White * 0.2f;
        int scale = (int)((float)barSize.X * life / lifeMax);
        scale -= scale % 2;
        Rectangle barFrame = barTexture.Frame(1, frameCount, 0, 2);
        barFrame.X += topLeftOffset.X;
        barFrame.Y += topLeftOffset.Y;
        barFrame.Width = 2;
        barFrame.Height = barSize.Y;
        Rectangle tipFrame = barTexture.Frame(1, frameCount, 0, 1);
        tipFrame.X += topLeftOffset.X;
        tipFrame.Y += topLeftOffset.Y;
        tipFrame.Width = 2;
        tipFrame.Height = barSize.Y;
        int shieldScale = (int)((float)barSize.X * shield / shieldMax);
        shieldScale -= shieldScale % 2;
        Rectangle barShieldFrame = barTexture.Frame(1, frameCount, 0, 5);
        barShieldFrame.X += topLeftOffset.X;
        barShieldFrame.Y += topLeftOffset.Y;
        barShieldFrame.Width = 2;
        barShieldFrame.Height = barSize.Y;
        Rectangle tipShieldFrame = barTexture.Frame(1, frameCount, 0, 4);
        tipShieldFrame.X += topLeftOffset.X;
        tipShieldFrame.Y += topLeftOffset.Y;
        tipShieldFrame.Width = 2;
        tipShieldFrame.Height = barSize.Y;
        Rectangle barPosition = Utils.CenteredRectangle(center, barSize.ToVector2());
        Vector2 barTopLeft = barPosition.TopLeft();
        Vector2 topLeft = barTopLeft - topLeftOffset.ToVector2();
        spriteBatch.Draw(barTexture, topLeft, (Rectangle?)bgFrame, bgColor, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
        Vector2 stretchScale = default(Vector2);
        ((Vector2)(ref stretchScale))._002Ector((float)(scale / barFrame.Width), 1f);
        Color barColor = Color.White;
        spriteBatch.Draw(barTexture, barTopLeft, (Rectangle?)barFrame, barColor, 0f, Vector2.Zero, stretchScale, (SpriteEffects)0, 0f);
        spriteBatch.Draw(barTexture, barTopLeft + new Vector2((float)(scale - 2), 0f), (Rectangle?)tipFrame, barColor, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
        if (shield > 0f)
        {
            ((Vector2)(ref stretchScale))._002Ector((float)(shieldScale / barFrame.Width), 1f);
            spriteBatch.Draw(barTexture, barTopLeft, (Rectangle?)barShieldFrame, barColor, 0f, Vector2.Zero, stretchScale, (SpriteEffects)0, 0f);
            spriteBatch.Draw(barTexture, barTopLeft + new Vector2((float)(shieldScale - 2), 0f), (Rectangle?)tipShieldFrame, barColor, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
        }
        Rectangle frameFrame = barTexture.Frame(1, frameCount);
        spriteBatch.Draw(barTexture, topLeft, (Rectangle?)frameFrame, Color.White, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
        Vector2 val7 = new Vector2(4f, 20f);
        Vector2 iconSize = default(Vector2);
        ((Vector2)(ref iconSize))._002Ector(26f, 28f);
        Vector2 iconPos = val7 + iconSize / 2f;
        spriteBatch.Draw(iconTexture, topLeft + iconPos, (Rectangle?)iconFrame, iconColor, 0f, iconFrame.Size() / 2f, iconScale, (SpriteEffects)0, 0f);
        if (BigProgressBarSystem.ShowText && showText)
        {
            if (shield > 0f)
            {
                BigProgressBarHelper.DrawHealthText(spriteBatch, barPosition, textOffset, shield, shieldMax);
            }
            else
            {
                BigProgressBarHelper.DrawHealthText(spriteBatch, barPosition, textOffset, life, lifeMax);
            }
        }
    }
References Terraria.Utils.CenteredRectangle(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawHealthText(), and Terraria.GameContent.UI.BigProgressBar.BigProgressBarSystem.ShowText.
Referenced by Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar().