TModLoader: Terraria.ModLoader.BossBarLoader.InsertMenu
InsertMenu()
static string Terraria.ModLoader.BossBarLoader.InsertMenu (out Action onClick) inline static package
Inserts the boss bar style select option into the main and in-game menu under the "Interface" category.
    {
        string styleText = null;
        ModBossBarStyle pendingBossBarStyle = null;
        foreach (ModBossBarStyle bossBarStyle in bossBarStyles)
        {
            if (bossBarStyle == CurrentStyle)
            {
                styleText = bossBarStyle.DisplayName;
                break;
            }
            pendingBossBarStyle = bossBarStyle;
        }
        if (pendingBossBarStyle == null)
        {
            pendingBossBarStyle = bossBarStyles.Last();
        }
        if (styleText == null || bossBarStyles.Count == 1)
        {
            styleText = Language.GetTextValue("tModLoader.BossBarStyleNoOptions");
        }
        onClick = delegate
        {
            SwitchBossBarStyle(pendingBossBarStyle);
        };
        return Language.GetTextValue("tModLoader.BossBarStyle", styleText);
    }
References Terraria.ModLoader.BossBarLoader.bossBarStyles, Terraria.ModLoader.BossBarLoader.CurrentStyle, Terraria.Localization.Language.GetTextValue(), and Terraria.ModLoader.BossBarLoader.SwitchBossBarStyle().
Referenced by Terraria.Main.DrawMenu().