TModLoader: Terraria.ModLoader.GlobalBackgroundStyleLoader.ResizeAndFillArrays
ResizeAndFillArrays()
static void Terraria.ModLoader.GlobalBackgroundStyleLoader.ResizeAndFillArrays (bool unloading = false) inline static package
Definition at line 24 of file GlobalBackgroundStyleLoader.cs.
    {
        ModLoader.BuildGlobalHook<GlobalBackgroundStyle, DelegateChooseUndergroundBackgroundStyle>(ref HookChooseUndergroundBackgroundStyle, globalBackgroundStyles, (GlobalBackgroundStyle g) => g.ChooseUndergroundBackgroundStyle);
        ModLoader.BuildGlobalHook<GlobalBackgroundStyle, DelegateChooseSurfaceBackgroundStyle>(ref HookChooseSurfaceBackgroundStyle, globalBackgroundStyles, (GlobalBackgroundStyle g) => g.ChooseSurfaceBackgroundStyle);
        ModLoader.BuildGlobalHook<GlobalBackgroundStyle, Action<int, int[]>>(ref HookFillUndergroundTextureArray, globalBackgroundStyles, (GlobalBackgroundStyle g) => g.FillUndergroundTextureArray);
        ModLoader.BuildGlobalHook<GlobalBackgroundStyle, Action<int, float[], float>>(ref HookModifyFarSurfaceFades, globalBackgroundStyles, (GlobalBackgroundStyle g) => g.ModifyFarSurfaceFades);
        if (!unloading)
        {
            loaded = true;
        }
    }
References Terraria.ModLoader.GlobalBackgroundStyleLoader.DelegateChooseSurfaceBackgroundStyle(), Terraria.ModLoader.GlobalBackgroundStyleLoader.DelegateChooseUndergroundBackgroundStyle(), Terraria.ModLoader.GlobalBackgroundStyleLoader.globalBackgroundStyles, Terraria.ModLoader.GlobalBackgroundStyleLoader.HookChooseSurfaceBackgroundStyle, Terraria.ModLoader.GlobalBackgroundStyleLoader.HookChooseUndergroundBackgroundStyle, Terraria.ModLoader.GlobalBackgroundStyleLoader.HookFillUndergroundTextureArray, Terraria.ModLoader.GlobalBackgroundStyleLoader.HookModifyFarSurfaceFades, and Terraria.ModLoader.GlobalBackgroundStyleLoader.loaded.
Referenced by Terraria.ModLoader.ModContent.ResizeArrays().