TModLoader: Terraria.GameContent.UI.EmoteBubble.Draw
Draw()
void Terraria.GameContent.UI.EmoteBubble.Draw (SpriteBatch sb) inline private
    {
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_0176: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_019f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_0220: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        Texture2D value = TextureAssets.Extra[48].Value;
        SpriteEffects effect = (SpriteEffects)0;
        Vector2 position = GetPosition(out effect);
        position = position.Floor();
        bool flag = lifeTime < 6 || lifeTimeStart - lifeTime < 6;
        Rectangle value2 = value.Frame(8, EMOTE_SHEET_VERTICAL_FRAMES, (!flag) ? 1 : 0);
        Vector2 origin = default(Vector2);
        ((Vector2)(ref origin))._002Ector((float)(value2.Width / 2), (float)value2.Height);
        if (Main.player[Main.myPlayer].gravDir == -1f)
        {
            origin.Y = 0f;
            effect = (SpriteEffects)(effect | 2);
            position = Main.ReverseGravitySupport(position);
        }
        Rectangle emoteFrame = (Rectangle)((emote >= 0 && emote < EmoteID.Count) ? value.Frame(8, 39, emote * 2 % 8 + frame, 1 + emote / 4) : new Rectangle(0, 0, 34, 28));
        if (emote == -1)
        {
            position += new Vector2((float)(((Enum)effect).HasFlag((Enum)(object)(SpriteEffects)1) ? 1 : (-1)), (float)(-emoteFrame.Height + 3));
        }
        else
        {
            if (ModEmoteBubble != null)
            {
                value = ModContent.Request<Texture2D>(ModEmoteBubble.Texture).Value;
                emoteFrame = (Rectangle)(((_003F?)EmoteBubbleLoader.GetFrame(this)) ?? value.Frame(2, 1, frame));
            }
            if (!EmoteBubbleLoader.PreDraw(this, sb, value, position, emoteFrame, origin, effect))
            {
                EmoteBubbleLoader.PostDraw(this, sb, value, position, emoteFrame, origin, effect);
                return;
            }
        }
        sb.Draw(TextureAssets.Extra[48].Value, position, (Rectangle?)value2, Color.White, 0f, origin, 1f, effect, 0f);
        if (flag)
        {
            return;
        }
        if (emote >= 0)
        {
            if ((emote == 87 || emote == 89) && ((Enum)effect).HasFlag((Enum)(object)(SpriteEffects)1))
            {
                effect = (SpriteEffects)(effect & -2);
                position.X += 4f;
            }
            sb.Draw(value, position, (Rectangle?)emoteFrame, Color.White, 0f, origin, 1f, effect, 0f);
        }
        else if (emote == -1)
        {
            value = TextureAssets.NpcHead[metadata].Value;
            float num = 1f;
            if ((float)value.Width / 22f > 1f)
            {
                num = 22f / (float)value.Width;
            }
            if ((float)value.Height / 16f > 1f / num)
            {
                num = 16f / (float)value.Height;
            }
            sb.Draw(value, position, (Rectangle?)null, Color.White, 0f, new Vector2((float)(value.Width / 2), 0f), num, effect, 0f);
        }
        EmoteBubbleLoader.PostDraw(this, sb, value, position, emoteFrame, origin, effect);
    }
References Terraria.GameContent.UI.EmoteID.Count, Terraria.GameContent.UI.EmoteBubble.emote, Terraria.GameContent.UI.EmoteBubble.EMOTE_SHEET_VERTICAL_FRAMES, Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.UI.EmoteBubble.frame, Terraria.ModLoader.EmoteBubbleLoader.GetFrame(), Terraria.GameContent.UI.EmoteBubble.GetPosition(), Terraria.Player.gravDir, Terraria.GameContent.UI.EmoteBubble.lifeTime, Terraria.GameContent.UI.EmoteBubble.lifeTimeStart, Terraria.GameContent.UI.EmoteBubble.metadata, Terraria.Main.myPlayer, Terraria.GameContent.TextureAssets.NpcHead, Terraria.Main.player, Terraria.ModLoader.EmoteBubbleLoader.PostDraw(), Terraria.ModLoader.EmoteBubbleLoader.PreDraw(), Terraria.Main.ReverseGravitySupport(), and Terraria.ModLoader.ModEmoteBubble.Texture.