TModLoader: Terraria.GameContent.UI.EmoteBubble.NewBubble
NewBubble()
static int Terraria.GameContent.UI.EmoteBubble.NewBubble (int emoticon, WorldUIAnchor bubbleAnchor, int time) inline static
Use this method to spawn a emote bubble.
Parameters
emoticon The emote ID of the emote that will spawn.
bubbleAnchor The T:Terraria.GameContent.UI.WorldUIAnchor instance for the emote. You can use
new WorldUIAnchor(Entity)
to get the instance.
time How long this emote remains.
Returns
The P:Terraria.GameContent.UI.EmoteBubble.WhoAmI of this emote
Definition at line 181 of file EmoteBubble.cs.
    {
        if (Main.netMode == 1)
        {
            return -1;
        }
        EmoteBubble emoteBubble = new EmoteBubble(emoticon, bubbleAnchor, time);
        emoteBubble.ID = AssignNewID();
        byID[emoteBubble.ID] = emoteBubble;
        if (Main.netMode == 2)
        {
            Tuple<int, int> tuple = SerializeNetAnchor(bubbleAnchor);
            NetMessage.SendData(91, -1, -1, null, emoteBubble.ID, tuple.Item1, tuple.Item2, time, emoticon);
        }
        OnBubbleChange(emoteBubble.ID);
        EmoteBubbleLoader.OnSpawn(emoteBubble);
        return emoteBubble.ID;
    }
References Terraria.GameContent.UI.EmoteBubble.AssignNewID(), Terraria.GameContent.UI.EmoteBubble.byID, Terraria.Main.netMode, Terraria.GameContent.UI.EmoteBubble.OnBubbleChange(), Terraria.ModLoader.EmoteBubbleLoader.OnSpawn(), Terraria.NetMessage.SendData(), and Terraria.GameContent.UI.EmoteBubble.SerializeNetAnchor().
Referenced by Terraria.Cinematics.DD2Film.DryadAlertEmote(), Terraria.Cinematics.DD2Film.DryadConfusedEmote(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.UI.EmoteBubble.MakeLocalPlayerEmote(), Terraria.GameContent.UI.EmoteBubble.MakePlayerEmote(), Terraria.Chat.Commands.EmojiCommand.ProcessOutgoingMessage(), Terraria.Chat.Commands.RockPaperScissorsCommand.ProcessOutgoingMessage(), and Terraria.NPC.VanillaFindFrame().