TModLoader: Terraria.GameContent.UI.EmoteBubble.PickNPCEmote
PickNPCEmote()
void Terraria.GameContent.UI.EmoteBubble.PickNPCEmote (WorldUIAnchor other = null) inline
Definition at line 468 of file EmoteBubble.cs.
    {
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        Player plr = Main.player[Player.FindClosest(((NPC)anchor.entity).Center, 0, 0)];
        List<int> list = new List<int>();
        bool flag = false;
        for (int i = 0; i < 200; i++)
        {
            if (Main.npc[i].active && Main.npc[i].boss)
            {
                flag = true;
            }
        }
        if (!flag)
        {
            if (Main.rand.Next(3) == 0)
            {
                ProbeTownNPCs(list);
            }
            if (Main.rand.Next(3) == 0)
            {
                ProbeEmotions(list);
            }
            if (Main.rand.Next(3) == 0)
            {
                ProbeBiomes(list, plr);
            }
            if (Main.rand.Next(2) == 0)
            {
                ProbeCritters(list);
            }
            if (Main.rand.Next(2) == 0)
            {
                ProbeItems(list, plr);
            }
            if (Main.rand.Next(5) == 0)
            {
                ProbeBosses(list);
            }
            if (Main.rand.Next(2) == 0)
            {
                ProbeDebuffs(list, plr);
            }
            if (Main.rand.Next(2) == 0)
            {
                ProbeEvents(list);
            }
            if (Main.rand.Next(2) == 0)
            {
                ProbeWeather(list, plr);
            }
            ProbeExceptions(list, plr, other);
        }
        else
        {
            ProbeCombat(list);
        }
        if (other == null)
        {
            other = new WorldUIAnchor();
        }
        int? modPickedEmote = NPCLoader.PickEmote((NPC)anchor.entity, plr, list, other);
        if (modPickedEmote == -1)
        {
            emote = -1;
        }
        else if (modPickedEmote.HasValue)
        {
            emote = modPickedEmote.Value;
        }
        else if (list.Count > 0)
        {
            emote = list[Main.rand.Next(list.Count)];
        }
    }
References Terraria.Entity.active, Terraria.GameContent.UI.EmoteBubble.anchor, Terraria.NPC.boss, Terraria.GameContent.UI.EmoteBubble.emote, Terraria.GameContent.UI.WorldUIAnchor.entity, Terraria.Player.FindClosest(), Terraria.Main.npc, Terraria.ModLoader.NPCLoader.PickEmote(), Terraria.Main.player, Terraria.GameContent.UI.EmoteBubble.ProbeBiomes(), Terraria.GameContent.UI.EmoteBubble.ProbeBosses(), Terraria.GameContent.UI.EmoteBubble.ProbeCombat(), Terraria.GameContent.UI.EmoteBubble.ProbeCritters(), Terraria.GameContent.UI.EmoteBubble.ProbeDebuffs(), Terraria.GameContent.UI.EmoteBubble.ProbeEmotions(), Terraria.GameContent.UI.EmoteBubble.ProbeEvents(), Terraria.GameContent.UI.EmoteBubble.ProbeExceptions(), Terraria.GameContent.UI.EmoteBubble.ProbeItems(), Terraria.GameContent.UI.EmoteBubble.ProbeTownNPCs(), Terraria.GameContent.UI.EmoteBubble.ProbeWeather(), and Terraria.Main.rand.