TModLoader: Terraria.GameContent.UI.EmoteBubble.NewBubbleNPC
NewBubbleNPC()
static int Terraria.GameContent.UI.EmoteBubble.NewBubbleNPC (WorldUIAnchor bubbleAnchor, int time, WorldUIAnchor other = null) inline static
Use this method to make NPCs use a random emote based on the pick emote table.
Parameters
bubbleAnchor The T:Terraria.GameContent.UI.WorldUIAnchor instance for the emote. You can use
new WorldUIAnchor(NPC)
to get the instance.
time How long this emote remains.
other The T:Terraria.GameContent.UI.WorldUIAnchor instance from the other side of the conversation.
Returns
The P:Terraria.GameContent.UI.EmoteBubble.WhoAmI of this emote
Definition at line 207 of file EmoteBubble.cs.
    {
        if (Main.netMode == 1)
        {
            return -1;
        }
        EmoteBubble emoteBubble = new EmoteBubble(0, bubbleAnchor, time);
        emoteBubble.PickNPCEmote(other);
        if (emoteBubble.emote < 0)
        {
            return -1;
        }
        emoteBubble.ID = AssignNewID();
        byID[emoteBubble.ID] = emoteBubble;
        if (Main.netMode == 2)
        {
            Tuple<int, int> tuple = SerializeNetAnchor(bubbleAnchor);
            NetMessage.SendData(91, -1, -1, null, emoteBubble.ID, tuple.Item1, tuple.Item2, time, emoteBubble.emote, emoteBubble.metadata);
        }
        EmoteBubbleLoader.OnSpawn(emoteBubble);
        return emoteBubble.ID;
    }
References Terraria.GameContent.UI.EmoteBubble.EmoteBubble(), Terraria.GameContent.UI.EmoteBubble.AssignNewID(), Terraria.GameContent.UI.EmoteBubble.byID, Terraria.Main.netMode, Terraria.ModLoader.EmoteBubbleLoader.OnSpawn(), Terraria.NetMessage.SendData(), and Terraria.GameContent.UI.EmoteBubble.SerializeNetAnchor().
Referenced by Terraria.NPC.VanillaFindFrame().