TModLoader: Terraria.GameContent.Items.ItemVariants.ItemVariants
ItemVariants()
static Terraria.GameContent.Items.ItemVariants.ItemVariants () inline static private
    {
        _variants = new List<VariantEntry>[ItemID.Count];
        StrongerVariant = new ItemVariant(Language.GetText("ItemVariant.Stronger"));
        WeakerVariant = new ItemVariant(Language.GetText("ItemVariant.Weaker"));
        RebalancedVariant = new ItemVariant(Language.GetText("ItemVariant.Rebalanced"));
        EnabledVariant = new ItemVariant(Language.GetText("ItemVariant.Enabled"));
        DisabledBossSummonVariant = new ItemVariant(Language.GetText("ItemVariant.DisabledBossSummon"));
        RemixWorld = Condition.RemixWorld;
        GetGoodWorld = Condition.ForTheWorthyWorld;
        EverythingWorld = Condition.ZenithWorld;
        AddVariant(112, StrongerVariant, RemixWorld);
        AddVariant(157, StrongerVariant, RemixWorld);
        AddVariant(1319, StrongerVariant, RemixWorld);
        AddVariant(1325, StrongerVariant, RemixWorld);
        AddVariant(2273, StrongerVariant, RemixWorld);
        AddVariant(3069, StrongerVariant, RemixWorld);
        AddVariant(5147, StrongerVariant, RemixWorld);
        AddVariant(517, WeakerVariant, RemixWorld);
        AddVariant(671, WeakerVariant, RemixWorld);
        AddVariant(683, WeakerVariant, RemixWorld);
        AddVariant(725, WeakerVariant, RemixWorld);
        AddVariant(1314, WeakerVariant, RemixWorld);
        AddVariant(2623, WeakerVariant, RemixWorld);
        AddVariant(5279, WeakerVariant, RemixWorld);
        AddVariant(5280, WeakerVariant, RemixWorld);
        AddVariant(5281, WeakerVariant, RemixWorld);
        AddVariant(5282, WeakerVariant, RemixWorld);
        AddVariant(5283, WeakerVariant, RemixWorld);
        AddVariant(5284, WeakerVariant, RemixWorld);
        AddVariant(197, RebalancedVariant, GetGoodWorld);
        AddVariant(4060, RebalancedVariant, GetGoodWorld);
        AddVariant(556, DisabledBossSummonVariant, EverythingWorld);
        AddVariant(557, DisabledBossSummonVariant, EverythingWorld);
        AddVariant(544, DisabledBossSummonVariant, EverythingWorld);
        AddVariant(5334, EnabledVariant, EverythingWorld);
    }
References Terraria.GameContent.Items.ItemVariants._variants, Terraria.GameContent.Items.ItemVariants.AddVariant(), Terraria.Condition(), Terraria.ID.ItemID.Count, Terraria.GameContent.Items.ItemVariants.DisabledBossSummonVariant, Terraria.GameContent.Items.ItemVariants.EnabledVariant, Terraria.GameContent.Items.ItemVariants.EverythingWorld, Terraria.GameContent.Items.ItemVariants.GetGoodWorld, Terraria.Localization.Language.GetText(), Terraria.GameContent.Items.ItemVariants.RebalancedVariant, Terraria.GameContent.Items.ItemVariants.RemixWorld, Terraria.GameContent.Items.ItemVariants.StrongerVariant, and Terraria.GameContent.Items.ItemVariants.WeakerVariant.