TModLoader: Terraria.ModLoader.ModProjectile.SetupContent
SetupContent()
override void Terraria.ModLoader.ModProjectile.SetupContent () inline sealed virtual
If you make a new ModType, seal this override, and call M:Terraria.ModLoader.ModType.SetStaticDefaults in it.
Reimplemented from Terraria.ModLoader.ModType< Projectile, ModProjectile >.
Definition at line 71 of file ModProjectile.cs.
    {
        ProjectileLoader.SetDefaults(Projectile, createModProjectile: false);
        AutoStaticDefaults();
        SetStaticDefaults();
        ProjectileID.Search.Add(base.FullName, Type);
    }
References Terraria.ModLoader.ModProjectile.AutoStaticDefaults(), Terraria.ID.ProjectileID.Search, Terraria.ModLoader.ProjectileLoader.SetDefaults(), and Terraria.ModLoader.ModType< Projectile, ModProjectile >.SetStaticDefaults().