TModLoader: Terraria.ModLoader.TileLoader.GetItemDrops
GetItemDrops()
static void Terraria.ModLoader.TileLoader.GetItemDrops (int x, int y, Tile tileCache, bool includeLargeObjectDrops = false, bool includeAllModdedLargeObjectDrops = false) inline static
    {
        ModTile modTile = GetTile(tileCache.TileType);
        if (modTile == null)
        {
            return;
        }
        bool needDrops = false;
        TileObjectData tileData = TileObjectData.GetTileData(tileCache.TileType, 0);
        if (tileData == null)
        {
            needDrops = true;
        }
        else if (tileData.Width == 1 && tileData.Height == 1)
        {
            needDrops = !includeAllModdedLargeObjectDrops;
        }
        else if (includeAllModdedLargeObjectDrops)
        {
            needDrops = true;
        }
        else if (includeLargeObjectDrops && (TileID.Sets.BasicChest[tileCache.type] || TileID.Sets.BasicDresser[tileCache.type] || TileID.Sets.Campfire[tileCache.type]))
        {
            needDrops = true;
        }
        if (!needDrops)
        {
            return;
        }
        IEnumerable<Item> itemDrops = modTile.GetItemDrops(x, y);
        if (itemDrops == null)
        {
            return;
        }
        foreach (Item item in itemDrops)
        {
            item.Prefix(-1);
            int num = Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 16, 16, item);
            Main.item[num].TryCombiningIntoNearbyItems(num);
        }
    }
References Terraria.ID.TileID.Sets.BasicChest, Terraria.ID.TileID.Sets.BasicDresser, Terraria.ID.TileID.Sets.Campfire, Terraria.WorldGen.GetItemSource_FromTileBreak(), Terraria.ModLoader.TileLoader.GetTile(), Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.Main.item, Terraria.Item.NewItem(), Terraria.Item.Prefix(), Terraria.Tile.TileType, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.KillTile_DropItems().