TModLoader: Terraria.ModLoader.TileLoader.GetItemDropFromTypeAndStyle
GetItemDropFromTypeAndStyle()
static int Terraria.ModLoader.TileLoader.GetItemDropFromTypeAndStyle (int type, int style = 0) inline static
Retrieves the item type that would drop from a tile of the specified type and style. This method is only reliable for modded tile types. This method can be used in M:Terraria.ModLoader.ModTile.GetItemDrops(System.Int32,System.Int32) for tiles that have custom tile style logic. If the specified style is not found, a fallback item will be returned if one has been registered through M:Terraria.ModLoader.ModTile.RegisterItemDrop(System.Int32,System.Int32[]) usage.
Modders querying modded tile drops should use M:Terraria.ModLoader.ModTile.GetItemDrops(System.Int32,System.Int32) directly rather that use this method so that custom drop logic is accounted for.
A return of 0 indicates that no item would drop from the tile.
Parameters
type
style
Returns
    {
        if (tileTypeAndTileStyleToItemType.TryGetValue((type, style), out var value) || tileTypeAndTileStyleToItemType.TryGetValue((type, -1), out value))
        {
            return value;
        }
        return 0;
    }
References Terraria.ModLoader.TileLoader.tileTypeAndTileStyleToItemType.
Referenced by Terraria.MessageBuffer.GetData(), Terraria.ModLoader.ModTile.GetItemDrops(), and Terraria.ModLoader.ModPylon.GetNPCShopEntry().