TModLoader: Terraria.ModLoader.TileLoader.GetTile
GetTile()
static ModTile Terraria.ModLoader.TileLoader.GetTile (int type) inline static
Gets the ModTile instance with the given type. If no ModTile with the given type exists, returns null.
Parameters
type The type of the ModTile
Returns
The ModTile instance in the tiles array, null if not found.
Definition at line 155 of file TileLoader.cs.
    {
        if (type < TileID.Count || type >= TileCount)
        {
            return null;
        }
        return tiles[type - TileID.Count];
    }
References Terraria.ID.TileID.Count, Terraria.ModLoader.TileLoader.TileCount, and Terraria.ModLoader.TileLoader.tiles.
Referenced by Terraria.ModLoader.MusicLoader.AddMusicBox(), Terraria.ModLoader.TileLoader.AdjTiles(), Terraria.ModLoader.TileLoader.AutoSelect(), Terraria.ModLoader.TileLoader.CanExplode(), Terraria.ModLoader.TileLoader.CanKillTile(), Terraria.ModLoader.TileLoader.CanPlace(), Terraria.ModLoader.TileLoader.CanReplace(), Terraria.ModLoader.TileLoader.ChangeWaterfallStyle(), Terraria.ModLoader.TileLoader.CloseDoorID(), Terraria.ModLoader.Default.LegacyUnloadedTilesSystem.ConvertTile(), Terraria.ModLoader.TileLoader.CreateDust(), Terraria.ModLoader.TileLoader.DefaultContainerName(), Terraria.ModLoader.TileLoader.DrawEffects(), Terraria.ModLoader.TileLoader.Drop(), Terraria.ModLoader.TileLoader.DropCritterChance(), Terraria.ModLoader.TileLoader.FloorVisuals(), Terraria.ModLoader.TileLoader.GetItemDrops(), Terraria.ModLoader.Default.TEModdedPylon.GetModPylonFromCoords(), Terraria.ModLoader.ModContent.GetModTile(), Terraria.Player.GetPickaxeDamage(), Terraria.ModLoader.TileLoader.HasSmartInteract(), Terraria.ModLoader.TileLoader.HasWalkDust(), Terraria.ModLoader.TileLoader.HitWire(), Terraria.ModLoader.TileLoader.IsClosedDoor(), Terraria.ModLoader.TileLoader.IsLockedChest(), Terraria.ModLoader.TileLoader.IsTileBiomeSightable(), Terraria.ModLoader.TileLoader.IsTileDangerous(), Terraria.ModLoader.TileLoader.IsTileSpelunkable(), Terraria.ModLoader.Default.UnloadedTileEntity.IsTileValidForEntity(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.ModLoader.TileLoader.KillMultiTile(), Terraria.ModLoader.TileLoader.KillSound(), Terraria.ModLoader.TileLoader.KillTile(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.ModLoader.TileLoader.LockChest(), Terraria.ModLoader.TileLoader.ModifyLight(), Terraria.ModLoader.TileLoader.ModifySittingTargetInfo(), Terraria.ModLoader.TileLoader.ModifySleepingTargetInfo(), Terraria.ModLoader.TileLoader.ModifySmartInteractCoords(), Terraria.ModLoader.TileLoader.ModifyTorchLuck(), Terraria.ModLoader.MapLoader.ModMapOption(), Terraria.ModLoader.TileLoader.MouseOver(), Terraria.ModLoader.TileLoader.MouseOverFar(), Terraria.ModLoader.TileLoader.NearbyEffects(), Terraria.ModLoader.TileLoader.NumDust(), Terraria.ModLoader.TileLoader.OpenDoorID(), Terraria.ModLoader.TileLoader.PickPowerCheck(), Terraria.ModLoader.TileLoader.PlaceInWorld(), Terraria.ModLoader.Default.TEModdedPylon.PlacementPreviewHook_CheckIfCanPlace(), Terraria.ModLoader.TileLoader.PostDraw(), Terraria.ModLoader.TileLoader.PreDraw(), Terraria.ModLoader.TileLoader.RandomUpdate(), Terraria.ModLoader.TileLoader.RightClick(), Terraria.ModLoader.TileLoader.SetAnimationFrame(), Terraria.ModLoader.TileLoader.SetDrawPositions(), Terraria.ModLoader.TileLoader.SetSpriteEffects(), Terraria.ModLoader.TileLoader.Slope(), Terraria.ModLoader.TileLoader.SpecialDraw(), Terraria.ModLoader.TileLoader.TileFrame(), Terraria.ModLoader.TileLoader.UnlockChest(), Terraria.Player.UpdateTorchLuck_ConsumeCountersAndCalculate(), Terraria.ModLoader.TileLoader.WalkDust(), and Terraria.ModLoader.IO.MapIO.WriteModMap().