TModLoader: Terraria.ModLoader.TileLoader.Drop
Drop()
static bool Terraria.ModLoader.TileLoader.Drop (int i, int j, int type, bool includeLargeObjectDrops = true) inline static
    {
        bool isLarge = false;
        if (Main.tileFrameImportant[type])
        {
            TileObjectData tileData = TileObjectData.GetTileData(type, 0);
            if (tileData != null)
            {
                if (tileData.Width != 1 || tileData.Height != 1)
                {
                    isLarge = true;
                }
            }
            else if (TileID.Sets.IsMultitile[type])
            {
                isLarge = true;
            }
        }
        if (!includeLargeObjectDrops && isLarge)
        {
            return true;
        }
        _ = Main.tile[i, j];
        bool dropItem = GetTile(type)?.CanDrop(i, j) ?? true;
        Func<int, int, int, bool>[] hookCanDrop = HookCanDrop;
        foreach (Func<int, int, int, bool> hook in hookCanDrop)
        {
            dropItem &= hook(i, j, type);
        }
        if (!dropItem)
        {
            return false;
        }
        Action<int, int, int>[] hookDrop = HookDrop;
        for (int k = 0; k < hookDrop.Length; k++)
        {
            hookDrop[k](i, j, type);
        }
        return true;
    }
References Terraria.ModLoader.ModTile.CanDrop(), Terraria.ModLoader.TileLoader.GetTile(), Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.ModLoader.TileLoader.HookCanDrop, Terraria.ModLoader.TileLoader.HookDrop, Terraria.ID.TileID.Sets.IsMultitile, Terraria.Main.tile, and Terraria.Main.tileFrameImportant.
Referenced by Terraria.WorldGen.Check1x2(), Terraria.WorldGen.Check1x2Top(), Terraria.WorldGen.Check1xX(), Terraria.WorldGen.Check2x1(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.Check2x2Style(), Terraria.WorldGen.Check2x3Wall(), Terraria.WorldGen.Check2x5(), Terraria.WorldGen.Check2xX(), Terraria.WorldGen.Check3x1(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.Check3x2Wall(), Terraria.WorldGen.Check3x3(), Terraria.WorldGen.Check3x3Wall(), Terraria.WorldGen.Check3x4(), Terraria.WorldGen.Check3x5(), Terraria.WorldGen.Check3x6(), Terraria.WorldGen.Check4x2(), Terraria.WorldGen.Check4x3Wall(), Terraria.WorldGen.Check5x4(), Terraria.WorldGen.Check6x3(), Terraria.WorldGen.Check6x4Wall(), Terraria.WorldGen.CheckBanner(), Terraria.WorldGen.CheckCannon(), Terraria.WorldGen.CheckChand(), Terraria.WorldGen.CheckChest(), Terraria.WorldGen.CheckDoorClosed(), Terraria.WorldGen.CheckDoorOpen(), Terraria.WorldGen.CheckGnome(), Terraria.WorldGen.CheckJunglePlant(), Terraria.WorldGen.CheckMan(), Terraria.WorldGen.CheckMB(), Terraria.WorldGen.CheckOrb(), Terraria.WorldGen.CheckPot(), Terraria.WorldGen.CheckSign(), Terraria.WorldGen.CheckSunflower(), Terraria.WorldGen.CheckSuper(), Terraria.WorldGen.CheckTallGate(), Terraria.WorldGen.CheckTrapDoor(), Terraria.WorldGen.CheckWeaponsRack(), Terraria.WorldGen.CheckWoman(), Terraria.WorldGen.CheckXmasTree(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEHatRack.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Framing_CheckTile(), and Terraria.WorldGen.KillTile_DropItems().