TModLoader: Terraria.ModLoader.TileLoader.ModifyLight
ModifyLight()
static void Terraria.ModLoader.TileLoader.ModifyLight (int i, int j, int type, ref float r, ref float g, ref float b) inline static
    {
        if (Main.tileLighted[type])
        {
            GetTile(type)?.ModifyLight(i, j, ref r, ref g, ref b);
            DelegateModifyLight[] hookModifyLight = HookModifyLight;
            for (int k = 0; k < hookModifyLight.Length; k++)
            {
                hookModifyLight[k](i, j, type, ref r, ref g, ref b);
            }
        }
    }
References Terraria.ModLoader.TileLoader.DelegateModifyLight(), Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.TileLoader.HookModifyLight, Terraria.ModLoader.ModBlockType.ModifyLight(), and Terraria.Main.tileLighted.
Referenced by Terraria.Graphics.Light.TileLightScanner.ApplyTileLight().