TModLoader: Terraria.ModLoader.TileLoader.ResizeArrays
ResizeArrays()
static void Terraria.ModLoader.TileLoader.ResizeArrays (bool unloading = false) inline static package
    {
        Array.Resize(ref TextureAssets.Tile, nextTile);
        Array.Resize(ref TextureAssets.HighlightMask, nextTile);
        LoaderUtils.ResetStaticMembers(typeof(TileID));
        Array.Resize(ref Main.SceneMetrics._tileCounts, nextTile);
        Array.Resize(ref Main.PylonSystem._sceneMetrics._tileCounts, nextTile);
        Array.Resize(ref Main.tileLighted, nextTile);
        Array.Resize(ref Main.tileMergeDirt, nextTile);
        Array.Resize(ref Main.tileCut, nextTile);
        Array.Resize(ref Main.tileAlch, nextTile);
        Array.Resize(ref Main.tileShine, nextTile);
        Array.Resize(ref Main.tileShine2, nextTile);
        Array.Resize(ref Main.tileStone, nextTile);
        Array.Resize(ref Main.tileAxe, nextTile);
        Array.Resize(ref Main.tileHammer, nextTile);
        Array.Resize(ref Main.tileWaterDeath, nextTile);
        Array.Resize(ref Main.tileLavaDeath, nextTile);
        Array.Resize(ref Main.tileTable, nextTile);
        Array.Resize(ref Main.tileBlockLight, nextTile);
        Array.Resize(ref Main.tileNoSunLight, nextTile);
        Array.Resize(ref Main.tileDungeon, nextTile);
        Array.Resize(ref Main.tileSpelunker, nextTile);
        Array.Resize(ref Main.tileSolidTop, nextTile);
        Array.Resize(ref Main.tileSolid, nextTile);
        Array.Resize(ref Main.tileBouncy, nextTile);
        Array.Resize(ref Main.tileLargeFrames, nextTile);
        Array.Resize(ref Main.tileRope, nextTile);
        Array.Resize(ref Main.tileBrick, nextTile);
        Array.Resize(ref Main.tileMoss, nextTile);
        Array.Resize(ref Main.tileNoAttach, nextTile);
        Array.Resize(ref Main.tileNoFail, nextTile);
        Array.Resize(ref Main.tileObsidianKill, nextTile);
        Array.Resize(ref Main.tileFrameImportant, nextTile);
        Array.Resize(ref Main.tilePile, nextTile);
        Array.Resize(ref Main.tileBlendAll, nextTile);
        Array.Resize(ref Main.tileContainer, nextTile);
        Array.Resize(ref Main.tileSign, nextTile);
        Array.Resize(ref Main.tileSand, nextTile);
        Array.Resize(ref Main.tileFlame, nextTile);
        Array.Resize(ref Main.tileFrame, nextTile);
        Array.Resize(ref Main.tileFrameCounter, nextTile);
        Array.Resize(ref Main.tileMerge, nextTile);
        Array.Resize(ref Main.tileOreFinderPriority, nextTile);
        Array.Resize(ref Main.tileGlowMask, nextTile);
        Array.Resize(ref Main.tileCracked, nextTile);
        Array.Resize(ref WorldGen.tileCounts, nextTile);
        Array.Resize(ref WorldGen.houseTile, nextTile);
        Array.Resize(ref CorruptionPitBiome.ValidTiles, nextTile);
        Array.Resize(ref TileMaterials.MaterialsByTileId, nextTile);
        Array.Resize(ref HouseUtils.BlacklistedTiles, nextTile);
        Array.Resize(ref HouseUtils.BeelistedTiles, nextTile);
        for (int i = 0; i < nextTile; i++)
        {
            Array.Resize(ref Main.tileMerge[i], nextTile);
        }
        for (int j = TileID.Count; j < nextTile; j++)
        {
            Main.tileGlowMask[j] = -1;
            TileMaterials.MaterialsByTileId[j] = TileMaterials._materialsByName["Default"];
        }
        while (TileObjectData._data.Count < nextTile)
        {
            TileObjectData._data.Add(null);
        }
        ModLoader.BuildGlobalHook<GlobalTile, Func<int, int, int, bool, bool>>(ref HookKillSound, globalTiles, (GlobalTile g) => g.KillSound);
        ModLoader.BuildGlobalHook<GlobalTile, DelegateNumDust>(ref HookNumDust, globalTiles, (GlobalTile g) => g.NumDust);
        ModLoader.BuildGlobalHook<GlobalTile, DelegateCreateDust>(ref HookCreateDust, globalTiles, (GlobalTile g) => g.CreateDust);
        ModLoader.BuildGlobalHook<GlobalTile, DelegateDropCritterChance>(ref HookDropCritterChance, globalTiles, (GlobalTile g) => g.DropCritterChance);
        ModLoader.BuildGlobalHook<GlobalTile, Func<int, int, int, bool>>(ref HookCanDrop, globalTiles, (GlobalTile g) => g.CanDrop);
        ModLoader.BuildGlobalHook<GlobalTile, Action<int, int, int>>(ref HookDrop, globalTiles, (GlobalTile g) => g.Drop);
        ModLoader.BuildGlobalHook<GlobalTile, DelegateCanKillTile>(ref HookCanKillTile, globalTiles, (GlobalTile g) => g.CanKillTile);
        ModLoader.BuildGlobalHook<GlobalTile, DelegateKillTile>(ref HookKillTile, globalTiles, (GlobalTile g) => g.KillTile);
        ModLoader.BuildGlobalHook<GlobalTile, Func<int, int, int, bool>>(ref HookCanExplode, globalTiles, (GlobalTile g) => g.CanExplode);
        ModLoader.BuildGlobalHook<GlobalTile, Action<int, int, int, bool>>(ref HookNearbyEffects, globalTiles, (GlobalTile g) => g.NearbyEffects);
        ModLoader.BuildGlobalHook<GlobalTile, DelegateModifyLight>(ref HookModifyLight, globalTiles, (GlobalTile g) => g.ModifyLight);
        ModLoader.BuildGlobalHook<GlobalTile, Func<int, int, int, Player, bool?>>(ref HookIsTileDangerous, globalTiles, (GlobalTile g) => g.IsTileDangerous);
        ModLoader.BuildGlobalHook<GlobalTile, DelegateIsTileBiomeSightable>(ref HookIsTileBiomeSightable, globalTiles, (GlobalTile g) => g.IsTileBiomeSightable);
        ModLoader.BuildGlobalHook<GlobalTile, Func<int, int, int, bool?>>(ref HookIsTileSpelunkable, globalTiles, (GlobalTile g) => g.IsTileSpelunkable);
        ModLoader.BuildGlobalHook<GlobalTile, DelegateSetSpriteEffects>(ref HookSetSpriteEffects, globalTiles, (GlobalTile g) => g.SetSpriteEffects);
        ModLoader.BuildGlobalHook<GlobalTile, Action>(ref HookAnimateTile, globalTiles, (GlobalTile g) => g.AnimateTile);
        ModLoader.BuildGlobalHook<GlobalTile, Func<int, int, int, SpriteBatch, bool>>(ref HookPreDraw, globalTiles, (GlobalTile g) => g.PreDraw);
        ModLoader.BuildGlobalHook<GlobalTile, DelegateDrawEffects>(ref HookDrawEffects, globalTiles, (GlobalTile g) => g.DrawEffects);
        ModLoader.BuildGlobalHook<GlobalTile, Action<int, int, int, SpriteBatch>>(ref HookPostDraw, globalTiles, (GlobalTile g) => g.PostDraw);
        ModLoader.BuildGlobalHook<GlobalTile, Action<int, int, int, SpriteBatch>>(ref HookSpecialDraw, globalTiles, (GlobalTile g) => g.SpecialDraw);
        ModLoader.BuildGlobalHook<GlobalTile, Action<int, int, int>>(ref HookRandomUpdate, globalTiles, (GlobalTile g) => g.RandomUpdate);
        ModLoader.BuildGlobalHook<GlobalTile, DelegateTileFrame>(ref HookTileFrame, globalTiles, (GlobalTile g) => g.TileFrame);
        ModLoader.BuildGlobalHook<GlobalTile, Func<int, int, int, bool>>(ref HookCanPlace, globalTiles, (GlobalTile g) => g.CanPlace);
        ModLoader.BuildGlobalHook<GlobalTile, Func<int, int, int, int, bool>>(ref HookCanReplace, globalTiles, (GlobalTile g) => g.CanReplace);
        ModLoader.BuildGlobalHook<GlobalTile, Func<int, int[]>>(ref HookAdjTiles, globalTiles, (GlobalTile g) => g.AdjTiles);
        ModLoader.BuildGlobalHook<GlobalTile, Action<int, int, int>>(ref HookRightClick, globalTiles, (GlobalTile g) => g.RightClick);
        ModLoader.BuildGlobalHook<GlobalTile, Action<int, int, int>>(ref HookMouseOver, globalTiles, (GlobalTile g) => g.MouseOver);
        ModLoader.BuildGlobalHook<GlobalTile, Action<int, int, int>>(ref HookMouseOverFar, globalTiles, (GlobalTile g) => g.MouseOverFar);
        ModLoader.BuildGlobalHook<GlobalTile, Func<int, int, int, Item, bool>>(ref HookAutoSelect, globalTiles, (GlobalTile g) => g.AutoSelect);
        ModLoader.BuildGlobalHook<GlobalTile, Func<int, int, int, bool>>(ref HookPreHitWire, globalTiles, (GlobalTile g) => g.PreHitWire);
        ModLoader.BuildGlobalHook<GlobalTile, Action<int, int, int>>(ref HookHitWire, globalTiles, (GlobalTile g) => g.HitWire);
        ModLoader.BuildGlobalHook<GlobalTile, Func<int, int, int, bool>>(ref HookSlope, globalTiles, (GlobalTile g) => g.Slope);
        ModLoader.BuildGlobalHook<GlobalTile, Action<int, Player>>(ref HookFloorVisuals, globalTiles, (GlobalTile g) => g.FloorVisuals);
        ModLoader.BuildGlobalHook<GlobalTile, DelegateChangeWaterfallStyle>(ref HookChangeWaterfallStyle, globalTiles, (GlobalTile g) => g.ChangeWaterfallStyle);
        ModLoader.BuildGlobalHook<GlobalTile, Action<int, int, int, Item>>(ref HookPlaceInWorld, globalTiles, (GlobalTile g) => g.PlaceInWorld);
        ModLoader.BuildGlobalHook<GlobalTile, Action>(ref HookPostSetupTileMerge, globalTiles, (GlobalTile g) => g.PostSetupTileMerge);
        if (!unloading)
        {
            loaded = true;
        }
    }
References Terraria.ObjectData.TileObjectData._data, Terraria.GameContent.Metadata.TileMaterials._materialsByName, Terraria.GameContent.TeleportPylonsSystem._sceneMetrics, Terraria.SceneMetrics._tileCounts, Terraria.GameContent.Biomes.CaveHouse.HouseUtils.BeelistedTiles, Terraria.GameContent.Biomes.CaveHouse.HouseUtils.BlacklistedTiles, Terraria.ID.TileID.Count, Terraria.ModLoader.TileLoader.DelegateCanKillTile(), Terraria.ModLoader.TileLoader.DelegateChangeWaterfallStyle(), Terraria.ModLoader.TileLoader.DelegateCreateDust(), Terraria.ModLoader.TileLoader.DelegateDrawEffects(), Terraria.ModLoader.TileLoader.DelegateDropCritterChance(), Terraria.ModLoader.TileLoader.DelegateIsTileBiomeSightable(), Terraria.ModLoader.TileLoader.DelegateKillTile(), Terraria.ModLoader.TileLoader.DelegateModifyLight(), Terraria.ModLoader.TileLoader.DelegateNumDust(), Terraria.ModLoader.TileLoader.DelegateSetSpriteEffects(), Terraria.ModLoader.TileLoader.DelegateTileFrame(), Terraria.ModLoader.TileLoader.globalTiles, Terraria.GameContent.TextureAssets.HighlightMask, Terraria.ModLoader.TileLoader.HookAdjTiles, Terraria.ModLoader.TileLoader.HookAnimateTile, Terraria.ModLoader.TileLoader.HookAutoSelect, Terraria.ModLoader.TileLoader.HookCanDrop, Terraria.ModLoader.TileLoader.HookCanExplode, Terraria.ModLoader.TileLoader.HookCanKillTile, Terraria.ModLoader.TileLoader.HookCanPlace, Terraria.ModLoader.TileLoader.HookCanReplace, Terraria.ModLoader.TileLoader.HookChangeWaterfallStyle, Terraria.ModLoader.TileLoader.HookCreateDust, Terraria.ModLoader.TileLoader.HookDrawEffects, Terraria.ModLoader.TileLoader.HookDrop, Terraria.ModLoader.TileLoader.HookDropCritterChance, Terraria.ModLoader.TileLoader.HookFloorVisuals, Terraria.ModLoader.TileLoader.HookHitWire, Terraria.ModLoader.TileLoader.HookIsTileBiomeSightable, Terraria.ModLoader.TileLoader.HookIsTileDangerous, Terraria.ModLoader.TileLoader.HookIsTileSpelunkable, Terraria.ModLoader.TileLoader.HookKillSound, Terraria.ModLoader.TileLoader.HookKillTile, Terraria.ModLoader.TileLoader.HookModifyLight, Terraria.ModLoader.TileLoader.HookMouseOver, Terraria.ModLoader.TileLoader.HookMouseOverFar, Terraria.ModLoader.TileLoader.HookNearbyEffects, Terraria.ModLoader.TileLoader.HookNumDust, Terraria.ModLoader.TileLoader.HookPlaceInWorld, Terraria.ModLoader.TileLoader.HookPostDraw, Terraria.ModLoader.TileLoader.HookPostSetupTileMerge, Terraria.ModLoader.TileLoader.HookPreDraw, Terraria.ModLoader.TileLoader.HookPreHitWire, Terraria.ModLoader.TileLoader.HookRandomUpdate, Terraria.ModLoader.TileLoader.HookRightClick, Terraria.ModLoader.TileLoader.HookSetSpriteEffects, Terraria.ModLoader.TileLoader.HookSlope, Terraria.ModLoader.TileLoader.HookSpecialDraw, Terraria.ModLoader.TileLoader.HookTileFrame, Terraria.WorldGen.houseTile, Terraria.ModLoader.TileLoader.loaded, Terraria.GameContent.Metadata.TileMaterials.MaterialsByTileId, Terraria.ModLoader.TileLoader.nextTile, Terraria.Main.PylonSystem, Terraria.ModLoader.Core.LoaderUtils.ResetStaticMembers(), Terraria.Main.SceneMetrics, Terraria.GameContent.TextureAssets.Tile, Terraria.Main.tileAlch, Terraria.Main.tileAxe, Terraria.Main.tileBlendAll, Terraria.Main.tileBlockLight, Terraria.Main.tileBouncy, Terraria.Main.tileBrick, Terraria.Main.tileContainer, Terraria.WorldGen.tileCounts, Terraria.Main.tileCracked, Terraria.Main.tileCut, Terraria.Main.tileDungeon, Terraria.Main.tileFlame, Terraria.Main.tileFrame, Terraria.Main.tileFrameCounter, Terraria.Main.tileFrameImportant, Terraria.Main.tileGlowMask, Terraria.Main.tileHammer, Terraria.Main.tileLargeFrames, Terraria.Main.tileLavaDeath, Terraria.Main.tileLighted, Terraria.Main.tileMerge, Terraria.Main.tileMergeDirt, Terraria.Main.tileMoss, Terraria.Main.tileNoAttach, Terraria.Main.tileNoFail, Terraria.Main.tileNoSunLight, Terraria.Main.tileObsidianKill, Terraria.Main.tileOreFinderPriority, Terraria.Main.tilePile, Terraria.Main.tileRope, Terraria.Main.tileSand, Terraria.Main.tileShine, Terraria.Main.tileShine2, Terraria.Main.tileSign, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Main.tileSpelunker, Terraria.Main.tileStone, Terraria.Main.tileTable, Terraria.Main.tileWaterDeath, and Terraria.GameContent.Biomes.CorruptionPitBiome.ValidTiles.
Referenced by Terraria.ModLoader.ModContent.ResizeArrays().