TModLoader: Terraria.ModLoader.TileLoader.IsClosedDoor
IsClosedDoor() [2/2]
static bool Terraria.ModLoader.TileLoader.IsClosedDoor (Tile tile) inline static
    {
        return IsClosedDoor(tile.type);
    }
References Terraria.ModLoader.TileLoader.IsClosedDoor(), and Terraria.Tile.type.
Referenced by Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.WorldGen.CanPoundTile(), Terraria.HitTile.DrawFreshAnimations(), Terraria.Main.DrawTileCracks(), Terraria.ModLoader.TileLoader.IsClosedDoor(), Terraria.Main.SetupAllBlockMerge(), Terraria.Player.TileInteractionsUse(), and Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryCloseDoor().