TModLoader: Terraria.ModLoader.TileLoader.SetDrawPositions
SetDrawPositions()
static void Terraria.ModLoader.TileLoader.SetDrawPositions (int i, int j, ref int width, ref int offsetY, ref int height, ref short tileFrameX, ref short tileFrameY) inline static
    {
        Tile tile = Main.tile[i, j];
        if (tile.type < TileID.Count)
        {
            return;
        }
        TileObjectData tileData = TileObjectData.GetTileData(tile.type, 0);
        if (tileData != null)
        {
            int partY = 0;
            for (int remainingFrameY = tile.frameY % tileData.CoordinateFullHeight; partY < tileData.Height && remainingFrameY - tileData.CoordinateHeights[partY] + tileData.CoordinatePadding >= 0; partY++)
            {
                remainingFrameY -= tileData.CoordinateHeights[partY] + tileData.CoordinatePadding;
            }
            width = tileData.CoordinateWidth;
            offsetY = tileData.DrawYOffset;
            height = tileData.CoordinateHeights[partY];
        }
        GetTile(tile.type).SetDrawPositions(i, j, ref width, ref offsetY, ref height, ref tileFrameX, ref tileFrameY);
    }
References Terraria.ID.TileID.Count, Terraria.Tile.frameY, Terraria.ModLoader.TileLoader.GetTile(), Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData().