TModLoader: Terraria.ModLoader.TileLoader.CheckModTile
CheckModTile()
static void Terraria.ModLoader.TileLoader.CheckModTile (int i, int j, int type) inline static
    {
        if (type <= TileID.Count || WorldGen.destroyObject)
        {
            return;
        }
        TileObjectData tileData = TileObjectData.GetTileData(type, 0);
        if (tileData == null)
        {
            return;
        }
        int frameX = Main.tile[i, j].frameX;
        int frameY = Main.tile[i, j].frameY;
        int subX = frameX / tileData.CoordinateFullWidth;
        int subY = frameY / tileData.CoordinateFullHeight;
        int wrap = tileData.StyleWrapLimit;
        if (wrap == 0)
        {
            wrap = 1;
        }
        int num = (tileData.StyleHorizontal ? (subY * wrap + subX) : (subX * wrap + subY));
        int style = num / tileData.StyleMultiplier;
        int alternate = num % tileData.StyleMultiplier;
        for (int k = 0; k < tileData.AlternatesCount; k++)
        {
            if (alternate >= tileData.Alternates[k].Style && alternate <= tileData.Alternates[k].Style + tileData.RandomStyleRange)
            {
                alternate = k;
                break;
            }
        }
        tileData = TileObjectData.GetTileData(type, style, alternate + 1);
        int partFrameX = frameX % tileData.CoordinateFullWidth;
        int partFrameY = frameY % tileData.CoordinateFullHeight;
        int partX = partFrameX / (tileData.CoordinateWidth + tileData.CoordinatePadding);
        int partY = 0;
        for (int remainingFrameY = partFrameY; partY < tileData.Height && remainingFrameY - tileData.CoordinateHeights[partY] + tileData.CoordinatePadding >= 0; partY++)
        {
            remainingFrameY -= tileData.CoordinateHeights[partY] + tileData.CoordinatePadding;
        }
        int originalI = i;
        int originalJ = j;
        i -= partX;
        j -= partY;
        int originX = i + tileData.Origin.X;
        int originY = j + tileData.Origin.Y;
        bool partiallyDestroyed = false;
        for (int x3 = i; x3 < i + tileData.Width; x3++)
        {
            for (int y3 = j; y3 < j + tileData.Height; y3++)
            {
                if (!Main.tile[x3, y3].active() || Main.tile[x3, y3].type != type)
                {
                    partiallyDestroyed = true;
                    break;
                }
            }
            if (partiallyDestroyed)
            {
                break;
            }
        }
        if (partiallyDestroyed || !TileObject.CanPlace(originX, originY, type, style, 0, out var _, onlyCheck: true, null, checkStay: true))
        {
            WorldGen.destroyObject = true;
            if (tileData.Width != 1 || tileData.Height != 1)
            {
                WorldGen.KillTile_DropItems(originalI, originalJ, Main.tile[originalI, originalJ], includeLargeObjectDrops: true, includeAllModdedLargeObjectDrops: true);
            }
            for (int x2 = i; x2 < i + tileData.Width; x2++)
            {
                for (int y2 = j; y2 < j + tileData.Height; y2++)
                {
                    if (Main.tile[x2, y2].type == type && Main.tile[x2, y2].active())
                    {
                        WorldGen.KillTile(x2, y2);
                    }
                }
            }
            KillMultiTile(i, j, frameX - partFrameX, frameY - partFrameY, type);
            WorldGen.destroyObject = false;
            for (int x = i - 1; x < i + tileData.Width + 2; x++)
            {
                for (int y = j - 1; y < j + tileData.Height + 2; y++)
                {
                    WorldGen.TileFrame(x, y);
                }
            }
        }
        TileObject.objectPreview.Active = false;
    }
References Terraria.TileObject.CanPlace(), Terraria.ID.TileID.Count, Terraria.WorldGen.destroyObject, Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.ModLoader.TileLoader.KillMultiTile(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillTile_DropItems(), Terraria.Main.tile, and Terraria.WorldGen.TileFrame().
Referenced by Terraria.WorldGen.TileFrame().