TModLoader: Terraria.ModLoader.TileLoader.ModifySmartInteractCoords
ModifySmartInteractCoords()
static void Terraria.ModLoader.TileLoader.ModifySmartInteractCoords (int type, ref int width, ref int height, ref int frameWidth, ref int frameHeight, ref int extraY) inline static
Definition at line 471 of file TileLoader.cs.
    {
        ModTile modTile = GetTile(type);
        if (modTile != null)
        {
            TileObjectData data = TileObjectData.GetTileData(type, 0);
            if (data != null)
            {
                width = data.Width;
                height = data.Height;
                frameWidth = data.CoordinateWidth + data.CoordinatePadding;
                frameHeight = data.CoordinateHeights[0] + data.CoordinatePadding;
                extraY = data.CoordinateFullHeight % frameHeight;
                modTile.ModifySmartInteractCoords(ref width, ref height, ref frameWidth, ref frameHeight, ref extraY);
            }
        }
    }
References Terraria.ObjectData.TileObjectData.CoordinateHeights, Terraria.ObjectData.TileObjectData.CoordinatePadding, Terraria.ModLoader.TileLoader.GetTile(), Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.ObjectData.TileObjectData.Height, and Terraria.ObjectData.TileObjectData.Width.
Referenced by Terraria.GameContent.ObjectInteractions.TileSmartInteractCandidateProvider.ProvideCandidate().