TModLoader: Terraria.ModLoader.TileLoader.SaplingGrowthType
SaplingGrowthType()
static bool Terraria.ModLoader.TileLoader.SaplingGrowthType (int soilType, ref int saplingType, ref int style) inline static
Definition at line 1169 of file TileLoader.cs.
    {
        int originalType = saplingType;
        int originalStyle = style;
        ModTree treeGrown = PlantLoader.Get<ModTree>(5, soilType);
        if (treeGrown == null)
        {
            ModPalmTree palmGrown = PlantLoader.Get<ModPalmTree>(323, soilType);
            if (palmGrown == null)
            {
                return false;
            }
            saplingType = palmGrown.SaplingGrowthType(ref style);
        }
        else
        {
            saplingType = treeGrown.SaplingGrowthType(ref style);
        }
        if (TileID.Sets.TreeSapling[saplingType])
        {
            return true;
        }
        saplingType = originalType;
        style = originalStyle;
        return false;
    }
References Terraria.ID.TileID.Sets.TreeSapling.
Referenced by Terraria.WorldGen.Check1x2(), Terraria.ModLoader.PlantLoader.CheckAndInjectModSapling(), and Terraria.WorldGen.PlaceTile().