TModLoader: Terraria.IO.PlayerFileData.MoveToLocal
MoveToLocal()
override void Terraria.IO.PlayerFileData.MoveToLocal () inline
Definition at line 105 of file PlayerFileData.cs.
    {
        if (!base.IsCloudSave || SocialAPI.Cloud == null)
        {
            return;
        }
        string playerPathFromName = Main.GetPlayerPathFromName(Name, cloudSave: false);
        if (!FileUtilities.MoveToLocal(base.Path, playerPathFromName))
        {
            return;
        }
        PlayerIO.MoveToLocal(base.Path, playerPathFromName);
        string fileName = GetFileName(includeExtension: false);
        string mapPath = System.IO.Path.Combine(Main.CloudPlayerPath, fileName);
        foreach (string item in (from path in SocialAPI.Cloud.GetFiles().ToList()
            where MapBelongsToPath(mapPath, path)
            select path).ToList())
        {
            string localPath = System.IO.Path.Combine(Main.PlayerPath, fileName, FileUtilities.GetFileName(item));
            FileUtilities.MoveToLocal(item, localPath);
        }
        Main.CloudFavoritesData.ClearEntry(this);
        _isCloudSave = false;
        _path = playerPathFromName;
        Main.LocalFavoriteData.SaveFavorite(this);
    }
References Terraria.IO.FileData._isCloudSave, Terraria.IO.FileData._path, Terraria.Social.SocialAPI.Cloud, Terraria.Main.CloudFavoritesData, Terraria.Main.CloudPlayerPath, Terraria.IO.FileData.GetFileName(), Terraria.Utilities.FileUtilities.GetFileName(), Terraria.Main.GetPlayerPathFromName(), Terraria.Main.LocalFavoriteData, Terraria.IO.PlayerFileData.MapBelongsToPath(), Terraria.ModLoader.IO.PlayerIO.MoveToLocal(), Terraria.Utilities.FileUtilities.MoveToLocal(), Terraria.IO.FileData.Name, and Terraria.Main.PlayerPath.
Referenced by Terraria.GameContent.UI.Elements.UICharacterListItem.CloudButtonClick().