TModLoader: Terraria.ModLoader.MountLoader.UpdateEffects
UpdateEffects()
static void Terraria.ModLoader.MountLoader.UpdateEffects (Player mountedPlayer) inline static package
    {
        if (IsModMount(Mount.mounts[mountedPlayer.mount.Type]))
        {
            GetMount(mountedPlayer.mount.Type).UpdateEffects(mountedPlayer);
        }
    }
References Terraria.ModLoader.MountLoader.GetMount(), Terraria.ModLoader.MountLoader.IsModMount(), Terraria.Mount.mounts, and Terraria.ModLoader.ModMount.UpdateEffects().
Referenced by Terraria.Mount.UpdateEffects().