TModLoader: Terraria.ModLoader.MountLoader.GetMount
GetMount()
static ModMount Terraria.ModLoader.MountLoader.GetMount (int type) inline static
Gets the ModMount instance corresponding to the given type. Returns null if no ModMount has the given type.
Parameters
type The type of the mount.
Returns
Null if not found, otherwise the ModMount associated with the mount.
    {
        if (mountDatas.ContainsKey(type))
        {
            return mountDatas[type];
        }
        return null;
    }
References Terraria.ModLoader.MountLoader.mountDatas.
Referenced by Terraria.ModLoader.ModContent.GetModMount(), Terraria.ModLoader.MountLoader.UpdateEffects(), and Terraria.ModLoader.MountLoader.UpdateFrame().