TModLoader: Terraria.ModLoader.UI.UIInfoMessage.Show
Show()
void Terraria.ModLoader.UI.UIInfoMessage.Show (string message, int gotoMenu, UIState gotoState = null, string altButtonText = "", Action altButtonAction = null, string okButtonText = null) inline package
Definition at line 174 of file UIInfoMessage.cs.
    {
        if (!Program.IsMainThread)
        {
            Main.QueueMainThreadAction(delegate
            {
                Show(message, gotoMenu, gotoState, altButtonText, altButtonAction, okButtonText);
            });
            return;
        }
        _message = message;
        _gotoMenu = gotoMenu;
        _gotoState = gotoState;
        _altText = altButtonText;
        _altAction = altButtonAction;
        _okText = okButtonText;
        Main.menuMode = 10013;
        Main.MenuUI.SetState(null);
    }
References Terraria.ModLoader.UI.UIInfoMessage._altAction, Terraria.ModLoader.UI.UIInfoMessage._altText, Terraria.ModLoader.UI.UIInfoMessage._gotoMenu, Terraria.ModLoader.UI.UIInfoMessage._gotoState, Terraria.ModLoader.UI.UIInfoMessage._message, Terraria.ModLoader.UI.UIInfoMessage._okText, Terraria.Program.IsMainThread, Terraria.Main.MenuUI, Terraria.Main.QueueMainThreadAction(), and Terraria.ModLoader.UI.UIInfoMessage.Show().
Referenced by Terraria.ModLoader.UI.UIInfoMessage.Show().