TModLoader: Terraria.ModLoader.UI.UIInfoMessage.OnInitialize
OnInitialize()
override void Terraria.ModLoader.UI.UIInfoMessage.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 36 of file UIInfoMessage.cs.
    {
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0282: Unknown result type (might be due to invalid IL or missing references)
        //IL_0288: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0291: Unknown result type (might be due to invalid IL or missing references)
        //IL_0294: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        _area = new UIElement
        {
            Width =
            {
                Percent = 0.8f
            },
            Top =
            {
                Pixels = 200f
            },
            Height =
            {
                Pixels = -240f,
                Percent = 1f
            },
            HAlign = 0.5f
        };
        UIPanel uIPanel = new UIPanel
        {
            Width =
            {
                Percent = 1f
            },
            Height =
            {
                Pixels = -110f,
                Percent = 1f
            },
            BackgroundColor = UICommon.MainPanelBackground
        };
        _area.Append(uIPanel);
        _messageBox = new UIMessageBox(string.Empty)
        {
            Width =
            {
                Pixels = -25f,
                Percent = 1f
            },
            Height =
            {
                Percent = 1f
            }
        };
        uIPanel.Append(_messageBox);
        UIScrollbar uIScrollbar = new UIScrollbar
        {
            Height =
            {
                Pixels = -12f,
                Percent = 1f
            },
            VAlign = 0.5f,
            HAlign = 1f
        }.WithView(100f, 1000f);
        uIPanel.Append(uIScrollbar);
        _messageBox.SetScrollbar(uIScrollbar);
        _button = new UITextPanel<string>(Language.GetTextValue("tModLoader.OK"), 0.7f, large: true)
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.5f
            },
            Height =
            {
                Pixels = 50f
            },
            Left =
            {
                Percent = 0.25f
            },
            VAlign = 1f,
            Top =
            {
                Pixels = -30f
            }
        }.WithFadedMouseOver();
        _button.OnLeftClick += OKClick;
        _area.Append(_button);
        _buttonAlt = new UITextPanel<string>("???", 0.7f, large: true)
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.5f
            },
            Height =
            {
                Pixels = 50f
            },
            Left =
            {
                Percent = 0.5f
            },
            VAlign = 1f,
            Top =
            {
                Pixels = -30f
            }
        }.WithFadedMouseOver();
        _buttonAlt.OnLeftClick += AltClick;
        _area.Append(_buttonAlt);
        Append(_area);
    }
References Terraria.ModLoader.UI.UIInfoMessage._area, Terraria.ModLoader.UI.UIInfoMessage._button, Terraria.ModLoader.UI.UIInfoMessage._buttonAlt, Terraria.ModLoader.UI.UIInfoMessage._messageBox, Terraria.ModLoader.UI.UIInfoMessage.AltClick(), Terraria.UI.UIElement.Append(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.ModLoader.UI.UIInfoMessage.OKClick(), Terraria.ModLoader.UI.UIMessageBox.SetScrollbar(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.