TModLoader: Terraria.ModLoader.Config.UI.UIModConfig.HandleHeader
HandleHeader()
static void Terraria.ModLoader.Config.UI.UIModConfig.HandleHeader (UIElement parent, ref int top, ref int order, PropertyFieldWrapper variable) inline static
    {
        HeaderAttribute header = ConfigManager.GetLocalizedHeader(variable.MemberInfo);
        if (header != null)
        {
            PropertyFieldWrapper wrapper = new PropertyFieldWrapper(typeof(HeaderAttribute).GetProperty("Header"));
            WrapIt(parent, ref top, wrapper, header, order++);
        }
    }
References Terraria.ModLoader.Config.ConfigManager.GetLocalizedHeader(), and Terraria.ModLoader.Config.UI.UIModConfig.WrapIt().
Referenced by Terraria.ModLoader.Config.UI.UIModConfig.MakeSeparateListPanel(), Terraria.ModLoader.Config.UI.UIModConfig.OnActivate(), and Terraria.ModLoader.Config.UI.ObjectElement.SetupList().