TModLoader: Terraria.ModLoader.Config.UI.UIModConfig.OnInitialize
OnInitialize()
override void Terraria.ModLoader.Config.UI.UIModConfig.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
    {
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0407: Unknown result type (might be due to invalid IL or missing references)
        //IL_040c: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_051c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0522: Unknown result type (might be due to invalid IL or missing references)
        //IL_0525: Unknown result type (might be due to invalid IL or missing references)
        //IL_052b: Unknown result type (might be due to invalid IL or missing references)
        //IL_052e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0534: Unknown result type (might be due to invalid IL or missing references)
        //IL_0537: Unknown result type (might be due to invalid IL or missing references)
        //IL_053d: Unknown result type (might be due to invalid IL or missing references)
        //IL_05dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_067f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0685: Unknown result type (might be due to invalid IL or missing references)
        //IL_0688: Unknown result type (might be due to invalid IL or missing references)
        //IL_068e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0691: Unknown result type (might be due to invalid IL or missing references)
        //IL_0697: Unknown result type (might be due to invalid IL or missing references)
        //IL_069a: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0731: Unknown result type (might be due to invalid IL or missing references)
        //IL_0737: Unknown result type (might be due to invalid IL or missing references)
        //IL_073a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0740: Unknown result type (might be due to invalid IL or missing references)
        //IL_0743: Unknown result type (might be due to invalid IL or missing references)
        //IL_0749: Unknown result type (might be due to invalid IL or missing references)
        //IL_074c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0752: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_081a: Unknown result type (might be due to invalid IL or missing references)
        //IL_081f: Unknown result type (might be due to invalid IL or missing references)
        uIElement = new UIElement();
        uIElement.Width.Set(0f, 0.8f);
        uIElement.MaxWidth.Set(600f, 0f);
        uIElement.Top.Set(160f, 0f);
        uIElement.Height.Set(-180f, 1f);
        uIElement.HAlign = 0.5f;
        uIPanel = new UIPanel();
        uIPanel.Width.Set(0f, 1f);
        uIPanel.Height.Set(-140f, 1f);
        uIPanel.Top.Set(30f, 0f);
        uIPanel.BackgroundColor = UICommon.MainPanelBackground;
        uIElement.Append(uIPanel);
        UIPanel textBoxBackground = new UIPanel();
        textBoxBackground.SetPadding(0f);
        filterTextField = new UIFocusInputTextField(Language.GetTextValue("tModLoader.ModConfigFilterOptions"));
        textBoxBackground.Top.Set(2f, 0f);
        textBoxBackground.Left.Set(-190f, 1f);
        textBoxBackground.Width.Set(180f, 0f);
        textBoxBackground.Height.Set(30f, 0f);
        uIElement.Append(textBoxBackground);
        filterTextField.SetText("");
        filterTextField.Top.Set(5f, 0f);
        filterTextField.Left.Set(10f, 0f);
        filterTextField.Width.Set(-20f, 1f);
        filterTextField.Height.Set(20f, 0f);
        filterTextField.OnTextChange += delegate
        {
            updateNeeded = true;
        };
        filterTextField.OnRightClick += delegate
        {
            filterTextField.SetText("");
        };
        textBoxBackground.Append(filterTextField);
        message = new UITextPanel<string>(Language.GetTextValue("tModLoader.ModConfigNotification"));
        message.Width.Set(-80f, 1f);
        message.Height.Set(20f, 0f);
        message.HAlign = 0.5f;
        message.VAlign = 1f;
        message.Top.Set(-65f, 0f);
        uIElement.Append(message);
        mainConfigList = new UIList();
        mainConfigList.Width.Set(-25f, 1f);
        mainConfigList.Height.Set(0f, 1f);
        mainConfigList.ListPadding = 5f;
        uIPanel.Append(mainConfigList);
        configPanelStack.Push(uIPanel);
        uIScrollbar = new UIScrollbar();
        uIScrollbar.SetView(100f, 1000f);
        uIScrollbar.Height.Set(0f, 1f);
        uIScrollbar.HAlign = 1f;
        uIPanel.Append(uIScrollbar);
        mainConfigList.SetScrollbar(uIScrollbar);
        headerTextPanel = new UITextPanel<string>(Language.GetTextValue("tModLoader.ModConfigModConfig"), 0.8f, large: true);
        headerTextPanel.HAlign = 0.5f;
        headerTextPanel.Top.Set(-50f, 0f);
        headerTextPanel.SetPadding(15f);
        headerTextPanel.BackgroundColor = UICommon.DefaultUIBlue;
        uIElement.Append(headerTextPanel);
        previousConfigButton = new UITextPanel<string>("<");
        previousConfigButton.Width.Set(25f, 0f);
        previousConfigButton.Height.Set(25f, 0f);
        previousConfigButton.VAlign = 1f;
        previousConfigButton.Top.Set(-65f, 0f);
        previousConfigButton.HAlign = 0f;
        previousConfigButton.WithFadedMouseOver();
        previousConfigButton.OnLeftClick += PreviousConfig;
        nextConfigButton = new UITextPanel<string>(">");
        nextConfigButton.CopyStyle(previousConfigButton);
        nextConfigButton.WithFadedMouseOver();
        nextConfigButton.HAlign = 1f;
        nextConfigButton.OnLeftClick += NextConfig;
        saveConfigButton = new UITextPanel<string>(Language.GetTextValue("tModLoader.ModConfigSaveConfig"));
        saveConfigButton.Width.Set(-10f, 0.25f);
        saveConfigButton.Height.Set(25f, 0f);
        saveConfigButton.Top.Set(-20f, 0f);
        saveConfigButton.WithFadedMouseOver();
        saveConfigButton.HAlign = 0.33f;
        saveConfigButton.VAlign = 1f;
        saveConfigButton.OnLeftClick += SaveConfig;
        backButton = new UITextPanel<string>(Language.GetTextValue("tModLoader.ModConfigBack"));
        backButton.CopyStyle(saveConfigButton);
        backButton.HAlign = 0f;
        backButton.WithFadedMouseOver();
        backButton.OnMouseOver += delegate
        {
            //IL_000e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0013: Unknown result type (might be due to invalid IL or missing references)
            if (pendingChanges)
            {
                backButton.BackgroundColor = Color.Red;
            }
        };
        backButton.OnMouseOut += delegate
        {
            //IL_000e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0018: Unknown result type (might be due to invalid IL or missing references)
            //IL_001d: Unknown result type (might be due to invalid IL or missing references)
            if (pendingChanges)
            {
                backButton.BackgroundColor = Color.Red * 0.7f;
            }
        };
        backButton.OnLeftClick += BackClick;
        uIElement.Append(backButton);
        revertConfigButton = new UITextPanel<string>(Language.GetTextValue("tModLoader.ModConfigRevertChanges"));
        revertConfigButton.CopyStyle(saveConfigButton);
        revertConfigButton.WithFadedMouseOver();
        revertConfigButton.HAlign = 0.66f;
        revertConfigButton.OnLeftClick += RevertConfig;
        restoreDefaultsConfigButton = new UITextPanel<string>(Language.GetTextValue("tModLoader.ModConfigRestoreDefaults"));
        restoreDefaultsConfigButton.CopyStyle(saveConfigButton);
        restoreDefaultsConfigButton.WithFadedMouseOver();
        restoreDefaultsConfigButton.HAlign = 1f;
        restoreDefaultsConfigButton.OnLeftClick += RestoreDefaults;
        uIElement.Append(restoreDefaultsConfigButton);
        uIPanel.BackgroundColor = UICommon.MainPanelBackground;
        Append(uIElement);
    }
References Terraria.UI.UIElement.UIElement(), Terraria.UI.UIElement.Append(), Terraria.ModLoader.Config.UI.UIModConfig.backButton, Terraria.ModLoader.Config.UI.UIModConfig.BackClick(), Terraria.ModLoader.Config.UI.UIModConfig.configPanelStack, Terraria.ModLoader.UI.UICommon.DefaultUIBlue, Terraria.ModLoader.Config.UI.UIModConfig.filterTextField, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.Config.UI.UIModConfig.headerTextPanel, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.ModLoader.Config.UI.UIModConfig.mainConfigList, Terraria.ModLoader.UI.UICommon.MainPanelBackground, Terraria.UI.UIElement.MaxWidth, Terraria.ModLoader.Config.UI.UIModConfig.message, Terraria.ModLoader.Config.UI.UIModConfig.NextConfig(), Terraria.ModLoader.Config.UI.UIModConfig.nextConfigButton, Terraria.ModLoader.Config.UI.UIModConfig.pendingChanges, Terraria.ModLoader.Config.UI.UIModConfig.PreviousConfig(), Terraria.ModLoader.Config.UI.UIModConfig.previousConfigButton, Terraria.ModLoader.Config.UI.UIModConfig.RestoreDefaults(), Terraria.ModLoader.Config.UI.UIModConfig.restoreDefaultsConfigButton, Terraria.ModLoader.Config.UI.UIModConfig.RevertConfig(), Terraria.ModLoader.Config.UI.UIModConfig.revertConfigButton, Terraria.ModLoader.Config.UI.UIModConfig.SaveConfig(), Terraria.ModLoader.Config.UI.UIModConfig.saveConfigButton, Terraria.UI.StyleDimension.Set(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.ModLoader.UI.UIFocusInputTextField.SetText(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.UI.UIElement.Top, Terraria.ModLoader.Config.UI.UIModConfig.uIElement, Terraria.ModLoader.Config.UI.UIModConfig.uIPanel, Terraria.ModLoader.Config.UI.UIModConfig.uIScrollbar, Terraria.ModLoader.Config.UI.UIModConfig.updateNeeded, and Terraria.UI.UIElement.Width.