TModLoader: Terraria.ModLoader.Config.UI.UIModConfig.NextConfig
NextConfig()
void Terraria.ModLoader.Config.UI.UIModConfig.NextConfig (UIMouseEvent evt, UIElement listeningElement) inline private
    {
        SoundEngine.PlaySound(in SoundID.MenuOpen);
        int index = sortedModConfigs.IndexOf(modConfig);
        modConfig = sortedModConfigs[(index + 1 <= sortedModConfigs.Count) ? (index + 1) : 0];
        DoMenuModeState();
    }
References Terraria.ModLoader.Config.UI.UIModConfig.DoMenuModeState(), Terraria.ID.SoundID.MenuOpen, Terraria.ModLoader.Config.UI.UIModConfig.modConfig, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.ModLoader.Config.UI.UIModConfig.sortedModConfigs.
Referenced by Terraria.ModLoader.Config.UI.UIModConfig.OnInitialize().