TModLoader: Terraria.ModLoader.Config.UI.UIModConfig.WrapIt
WrapIt()
static Tuple< UIElement, UIElement > Terraria.ModLoader.Config.UI.UIModConfig.WrapIt (UIElement parent, ref int top, PropertyFieldWrapper memberInfo, object item, int order, object list = null, Type arrayType = null, int index = -1) inline static
    {
        Type type = memberInfo.Type;
        if (arrayType != null)
        {
            type = arrayType;
        }
        CustomModConfigItemAttribute customUI = ConfigManager.GetCustomAttributeFromMemberThenMemberType<CustomModConfigItemAttribute>(memberInfo, null, null);
        UIElement e;
        if (customUI != null)
        {
            Type customUIType = customUI.Type;
            if (typeof(ConfigElement).IsAssignableFrom(customUIType))
            {
                ConstructorInfo ctor = customUIType.GetConstructor(Array.Empty<Type>());
                e = ((!(ctor != null)) ? new UIText(customUIType.Name + " specified via CustomModConfigItem for " + memberInfo.Name + " does not have an empty constructor.") : (ctor.Invoke(new object[0]) as UIElement));
            }
            else
            {
                e = new UIText(customUIType.Name + " specified via CustomModConfigItem for " + memberInfo.Name + " does not inherit from ConfigElement.");
            }
        }
        else if (item.GetType() == typeof(HeaderAttribute))
        {
            e = new HeaderElement((string)memberInfo.GetValue(item));
        }
        else if (type == typeof(ItemDefinition))
        {
            e = new ItemDefinitionElement();
        }
        else if (type == typeof(ProjectileDefinition))
        {
            e = new ProjectileDefinitionElement();
        }
        else if (type == typeof(NPCDefinition))
        {
            e = new NPCDefinitionElement();
        }
        else if (type == typeof(PrefixDefinition))
        {
            e = new PrefixDefinitionElement();
        }
        else if (type == typeof(BuffDefinition))
        {
            e = new BuffDefinitionElement();
        }
        else if (type == typeof(Color))
        {
            e = new ColorElement();
        }
        else if (type == typeof(Vector2))
        {
            e = new Vector2Element();
        }
        else if (type == typeof(bool))
        {
            e = new BooleanElement();
        }
        else if (type == typeof(float))
        {
            e = new FloatElement();
        }
        else if (type == typeof(byte))
        {
            e = new ByteElement();
        }
        else if (type == typeof(uint))
        {
            e = new UIntElement();
        }
        else if (type == typeof(int))
        {
            e = ((ConfigManager.GetCustomAttributeFromMemberThenMemberType<SliderAttribute>(memberInfo, item, list) == null) ? ((ConfigElement)new IntInputElement()) : ((ConfigElement)new IntRangeElement()));
        }
        else if (type == typeof(string))
        {
            e = ((ConfigManager.GetCustomAttributeFromMemberThenMemberType<OptionStringsAttribute>(memberInfo, item, list) == null) ? ((ConfigElement)new StringInputElement()) : ((ConfigElement)new StringOptionElement()));
        }
        else if (type.IsEnum)
        {
            e = ((list == null) ? ((UIElement)new EnumElement()) : ((UIElement)new UIText(memberInfo.Name + " not handled yet (" + type.Name + ").")));
        }
        else if (type.IsArray)
        {
            e = new ArrayElement();
        }
        else if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>))
        {
            e = new ListElement();
        }
        else if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(HashSet<>))
        {
            e = new SetElement();
        }
        else if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(Dictionary<, >))
        {
            e = new DictionaryElement();
        }
        else if (type.IsClass)
        {
            e = new ObjectElement();
        }
        else if (type.IsValueType && !type.IsPrimitive)
        {
            e = new UIText(memberInfo.Name + " not handled yet (" + type.Name + ") Structs need special UI.");
            e.Height.Pixels += 6f;
            e.Left.Pixels += 4f;
        }
        else
        {
            e = new UIText(memberInfo.Name + " not handled yet (" + type.Name + ")");
            e.Top.Pixels += 6f;
            e.Left.Pixels += 4f;
        }
        if (e != null)
        {
            if (e is ConfigElement configElement)
            {
                configElement.Bind(memberInfo, item, (IList)list, index);
                configElement.OnBind();
            }
            e.Recalculate();
            int elementHeight = (int)e.GetOuterDimensions().Height;
            UIElement container = GetContainer(e, (index == -1) ? order : index);
            container.Height.Pixels = elementHeight;
            if (parent is UIList uiList)
            {
                uiList.Add(container);
                uiList.GetTotalHeight();
            }
            else
            {
                container.Top.Pixels = top;
                container.Width.Pixels = -20f;
                container.Left.Pixels = 20f;
                top += elementHeight + 4;
                parent.Append(container);
                parent.Height.Set(top, 0f);
            }
            Tuple<UIElement, UIElement> tuple = new Tuple<UIElement, UIElement>(container, e);
            if (parent == Interface.modConfig.mainConfigList)
            {
                Interface.modConfig.mainConfigItems.Add(tuple);
            }
            return tuple;
        }
        return null;
    }
References Terraria.UI.UIElement.UIElement(), Terraria.ModLoader.Config.UI.UIModConfig.GetContainer(), Terraria.ModLoader.Config.UI.PropertyFieldWrapper.GetValue(), Terraria.ModLoader.UI.Interface.modConfig, Terraria.ModLoader.Config.UI.PropertyFieldWrapper.Name, and Terraria.ModLoader.Config.UI.PropertyFieldWrapper.Type.
Referenced by Terraria.ModLoader.Config.UI.UIModConfig.HandleHeader(), Terraria.ModLoader.Config.UI.UIModConfig.MakeSeparateListPanel(), Terraria.ModLoader.Config.UI.UIModConfig.OnActivate(), Terraria.ModLoader.Config.UI.ColorElement.OnBind(), Terraria.ModLoader.Config.UI.Vector2Element.OnBind(), Terraria.ModLoader.Config.UI.ArrayElement.SetupList(), Terraria.ModLoader.Config.UI.DictionaryElement.SetupList(), Terraria.ModLoader.Config.UI.ListElement.SetupList(), Terraria.ModLoader.Config.UI.ObjectElement.SetupList(), Terraria.ModLoader.Config.UI.SetElement.SetupList(), and Terraria.ModLoader.Config.ConfigManager.WrapIt().