TModLoader: Terraria.ModLoader.Config.UI.UIModConfig.SaveConfig
SaveConfig()
void Terraria.ModLoader.Config.UI.UIModConfig.SaveConfig (UIMouseEvent evt, UIElement listeningElement) inline private
    {
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        if (Main.gameMenu)
        {
            SoundEngine.PlaySound(in SoundID.MenuOpen);
            ConfigManager.Save(pendingConfig);
            ConfigManager.Load(modConfig);
        }
        else
        {
            if (pendingConfig.Mode == ConfigScope.ServerSide && Main.netMode == 1)
            {
                SetMessage(Language.GetTextValue("tModLoader.ModConfigAskingServerToAcceptChanges"), Color.Yellow);
                ModPacket modPacket = new ModPacket(249);
                modPacket.Write(pendingConfig.Mod.Name);
                modPacket.Write(pendingConfig.Name);
                string json = JsonConvert.SerializeObject((object)pendingConfig, ConfigManager.serializerSettingsCompact);
                modPacket.Write(json);
                modPacket.Send();
                return;
            }
            if (ConfigManager.GetLoadTimeConfig(modConfig.Mod, modConfig.Name).NeedsReload(pendingConfig))
            {
                SoundEngine.PlaySound(in SoundID.MenuClose);
                SetMessage(Language.GetTextValue("tModLoader.ModConfigCantSaveBecauseChangesWouldRequireAReload"), Color.Red);
                return;
            }
            SoundEngine.PlaySound(in SoundID.MenuOpen);
            ConfigManager.Save(pendingConfig);
            ConfigManager.Load(modConfig);
            modConfig.OnChanged();
        }
        DoMenuModeState();
    }
References Terraria.ModLoader.Config.UI.UIModConfig.DoMenuModeState(), Terraria.Main.gameMenu, Terraria.ModLoader.Config.ConfigManager.GetLoadTimeConfig(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.Config.ConfigManager.Load(), Terraria.ID.SoundID.MenuClose, Terraria.ID.SoundID.MenuOpen, Terraria.ModLoader.Config.ModConfig.Mod, Terraria.ModLoader.Config.UI.UIModConfig.modConfig, Terraria.ModLoader.Config.ModConfig.Mode, Terraria.ModLoader.Config.ModConfig.Name, Terraria.ModLoader.Mod.Name, Terraria.ModLoader.Config.ModConfig.NeedsReload(), Terraria.Main.netMode, Terraria.ModLoader.Config.ModConfig.OnChanged(), Terraria.ModLoader.Config.UI.UIModConfig.pendingConfig, Terraria.Audio.SoundEngine.PlaySound(), Terraria.ModLoader.Config.ConfigManager.Save(), Terraria.ModLoader.Config.ConfigManager.serializerSettingsCompact, and Terraria.ModLoader.Config.UI.UIModConfig.SetMessage().
Referenced by Terraria.ModLoader.Config.UI.UIModConfig.OnInitialize().