TModLoader: Terraria.ModLoader.Config.UI.UIModConfig.MakeSeparateListPanel
MakeSeparateListPanel()
static UIPanel Terraria.ModLoader.Config.UI.UIModConfig.MakeSeparateListPanel (object item, object subitem, PropertyFieldWrapper memberInfo, IList array, int index, Func< string > AbridgedTextDisplayFunction) inline static package
    {
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_0237: Unknown result type (might be due to invalid IL or missing references)
        UIPanel uIPanel = new UIPanel();
        uIPanel.CopyStyle(Interface.modConfig.uIPanel);
        uIPanel.BackgroundColor = UICommon.MainPanelBackground;
        BackgroundColorAttribute bca = ConfigManager.GetCustomAttributeFromMemberThenMemberType<BackgroundColorAttribute>(memberInfo, subitem, null);
        if (bca != null)
        {
            uIPanel.BackgroundColor = bca.Color;
        }
        UIList separateList = new UIList();
        separateList.CopyStyle(Interface.modConfig.mainConfigList);
        separateList.Height.Set(-40f, 1f);
        separateList.Top.Set(40f, 0f);
        uIPanel.Append(separateList);
        int top = 0;
        UIScrollbar uIScrollbar = new UIScrollbar();
        uIScrollbar.SetView(100f, 1000f);
        uIScrollbar.Height.Set(-40f, 1f);
        uIScrollbar.Top.Set(40f, 0f);
        uIScrollbar.HAlign = 1f;
        uIPanel.Append(uIScrollbar);
        separateList.SetScrollbar(uIScrollbar);
        string name = ConfigManager.GetLocalizedLabel(memberInfo);
        if (index != -1)
        {
            name = name + " #" + (index + 1);
        }
        Interface.modConfig.subPageStack.Push(name);
        name = string.Join(" > ", Interface.modConfig.subPageStack.Reverse());
        UITextPanel<string> heading = new UITextPanel<string>(name);
        heading.HAlign = 0f;
        heading.Top.Set(-6f, 0f);
        heading.Height.Set(40f, 0f);
        uIPanel.Append(heading);
        UITextPanel<string> back = new UITextPanel<string>(Language.GetTextValue("tModLoader.ModConfigBack"))
        {
            HAlign = 1f
        };
        back.Width.Set(50f, 0f);
        back.Top.Set(-6f, 0f);
        back.OnLeftClick += delegate
        {
            Interface.modConfig.uIElement.RemoveChild(uIPanel);
            Interface.modConfig.configPanelStack.Pop();
            Interface.modConfig.uIElement.Append(Interface.modConfig.configPanelStack.Peek());
        };
        back.WithFadedMouseOver();
        uIPanel.Append(back);
        int order = 0;
        if (array != null)
        {
            _ = memberInfo.Type.GetGenericArguments()[0].GetMethod("ToString", new Type[0]).DeclaringType != typeof(object);
        }
        else
        {
            _ = memberInfo.Type.GetMethod("ToString", new Type[0]).DeclaringType != typeof(object);
        }
        if (AbridgedTextDisplayFunction != null)
        {
            UITextPanel<FuncStringWrapper> display = new UITextPanel<FuncStringWrapper>(new FuncStringWrapper(AbridgedTextDisplayFunction))
            {
                DrawPanel = true
            };
            display.Recalculate();
            UIElement container = GetContainer(display, order++);
            container.Height.Pixels = (int)display.GetOuterDimensions().Height;
            separateList.Add(container);
        }
        foreach (PropertyFieldWrapper variable in ConfigManager.GetFieldsAndProperties(subitem))
        {
            if (!Attribute.IsDefined(variable.MemberInfo, typeof(JsonIgnoreAttribute)) || Attribute.IsDefined(variable.MemberInfo, typeof(ShowDespiteJsonIgnoreAttribute)))
            {
                HandleHeader(separateList, ref top, ref order, variable);
                WrapIt(separateList, ref top, variable, subitem, order++);
            }
        }
        Interface.modConfig.subPageStack.Pop();
        return uIPanel;
    }
References Terraria.UI.UIElement.Append(), Terraria.UI.UIElement.CopyStyle(), Terraria.ModLoader.Config.UI.UIModConfig.GetContainer(), Terraria.ModLoader.Config.ConfigManager.GetFieldsAndProperties(), Terraria.ModLoader.Config.ConfigManager.GetLocalizedLabel(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.HAlign, Terraria.ModLoader.Config.UI.UIModConfig.HandleHeader(), Terraria.UI.UIElement.Height, Terraria.ModLoader.UI.UICommon.MainPanelBackground, Terraria.ModLoader.UI.Interface.modConfig, Terraria.UI.StyleDimension.Set(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.UI.UIElement.Top, Terraria.ModLoader.Config.UI.PropertyFieldWrapper.Type, Terraria.ModLoader.Config.UI.UIModConfig.uIPanel, Terraria.ModLoader.Config.UI.UIModConfig.uIScrollbar, and Terraria.ModLoader.Config.UI.UIModConfig.WrapIt().
Referenced by Terraria.ModLoader.Config.UI.ObjectElement.SetupList().