TModLoader: Terraria.ModLoader.Config.UI.UIModConfig.OnActivate
OnActivate()
override void Terraria.ModLoader.Config.UI.UIModConfig.OnActivate () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 445 of file UIModConfig.cs.
    {
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        filterTextField.SetText("");
        updateNeeded = false;
        SetMessage("", Color.White);
        string configDisplayName = modConfig.DisplayName.Value;
        headerTextPanel.SetText(string.IsNullOrEmpty(configDisplayName) ? modConfig.Mod.DisplayName : (modConfig.Mod.DisplayName + ": " + configDisplayName));
        pendingConfig = ConfigManager.GeneratePopulatedClone(modConfig);
        pendingChanges = pendingRevertDefaults;
        if (pendingRevertDefaults)
        {
            pendingRevertDefaults = false;
            ConfigManager.Reset(pendingConfig);
            pendingChangesUIUpdate = true;
        }
        int num = sortedModConfigs.IndexOf(modConfig);
        int count = sortedModConfigs.Count;
        backButton.BackgroundColor = UICommon.DefaultUIBlueMouseOver;
        uIElement.RemoveChild(saveConfigButton);
        uIElement.RemoveChild(revertConfigButton);
        uIElement.RemoveChild(previousConfigButton);
        uIElement.RemoveChild(nextConfigButton);
        if (num + 1 < count)
        {
            uIElement.Append(nextConfigButton);
        }
        if (num - 1 >= 0)
        {
            uIElement.Append(previousConfigButton);
        }
        uIElement.RemoveChild(configPanelStack.Peek());
        uIElement.Append(uIPanel);
        mainConfigItems.Clear();
        mainConfigList.Clear();
        configPanelStack.Clear();
        configPanelStack.Push(uIPanel);
        subPageStack.Clear();
        int top = 0;
        uIPanel.BackgroundColor = UICommon.MainPanelBackground;
        BackgroundColorAttribute backgroundColorAttribute = (BackgroundColorAttribute)Attribute.GetCustomAttribute(pendingConfig.GetType(), typeof(BackgroundColorAttribute));
        if (backgroundColorAttribute != null)
        {
            uIPanel.BackgroundColor = backgroundColorAttribute.Color;
        }
        int order = 0;
        foreach (PropertyFieldWrapper variable in ConfigManager.GetFieldsAndProperties(pendingConfig))
        {
            if ((!variable.IsProperty || !(variable.Name == "Mode")) && (!Attribute.IsDefined(variable.MemberInfo, typeof(JsonIgnoreAttribute)) || Attribute.IsDefined(variable.MemberInfo, typeof(ShowDespiteJsonIgnoreAttribute))))
            {
                HandleHeader(mainConfigList, ref top, ref order, variable);
                WrapIt(mainConfigList, ref top, variable, pendingConfig, order++);
            }
        }
    }
References Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.ModLoader.Config.UI.UIModConfig.configPanelStack, Terraria.ModLoader.UI.UICommon.DefaultUIBlueMouseOver, Terraria.ModLoader.Config.ModConfig.DisplayName, Terraria.ModLoader.Mod.DisplayName, Terraria.ModLoader.Config.UI.UIModConfig.filterTextField, Terraria.ModLoader.Config.ConfigManager.GeneratePopulatedClone(), Terraria.ModLoader.Config.ConfigManager.GetFieldsAndProperties(), Terraria.ModLoader.Config.UI.UIModConfig.HandleHeader(), Terraria.ModLoader.Config.UI.UIModConfig.headerTextPanel, Terraria.ModLoader.Config.UI.UIModConfig.mainConfigItems, Terraria.ModLoader.Config.UI.UIModConfig.mainConfigList, Terraria.ModLoader.UI.UICommon.MainPanelBackground, Terraria.ModLoader.Config.ModConfig.Mod, Terraria.ModLoader.Config.UI.UIModConfig.modConfig, Terraria.ModLoader.Config.UI.UIModConfig.nextConfigButton, Terraria.ModLoader.Config.UI.UIModConfig.pendingChanges, Terraria.ModLoader.Config.UI.UIModConfig.pendingChangesUIUpdate, Terraria.ModLoader.Config.UI.UIModConfig.pendingConfig, Terraria.ModLoader.Config.UI.UIModConfig.pendingRevertDefaults, Terraria.ModLoader.Config.UI.UIModConfig.previousConfigButton, Terraria.UI.UIElement.RemoveChild(), Terraria.ModLoader.Config.ConfigManager.Reset(), Terraria.ModLoader.Config.UI.UIModConfig.revertConfigButton, Terraria.ModLoader.Config.UI.UIModConfig.saveConfigButton, Terraria.ModLoader.Config.UI.UIModConfig.SetMessage(), Terraria.ModLoader.UI.UIFocusInputTextField.SetText(), Terraria.GameContent.UI.Elements.UITextPanel< T >.SetText(), Terraria.ModLoader.Config.UI.UIModConfig.sortedModConfigs, Terraria.ModLoader.Config.UI.UIModConfig.subPageStack, Terraria.ModLoader.Config.UI.UIModConfig.uIElement, Terraria.ModLoader.Config.UI.UIModConfig.uIPanel, Terraria.ModLoader.Config.UI.UIModConfig.updateNeeded, and Terraria.ModLoader.Config.UI.UIModConfig.WrapIt().