TModLoader: Terraria.ModLoader.Config.UI.UIModConfig.Update
Update()
override void Terraria.ModLoader.Config.UI.UIModConfig.Update (GameTime gameTime) inline virtual
Reimplemented from Terraria.UI.UIElement.
    {
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        base.Update(gameTime);
        UpdateCount++;
        if (pendingChangesUIUpdate)
        {
            uIElement.Append(saveConfigButton);
            uIElement.Append(revertConfigButton);
            backButton.BackgroundColor = Color.Red * 0.7f;
            pendingChangesUIUpdate = false;
        }
        if (netUpdate)
        {
            DoMenuModeState();
            netUpdate = false;
        }
        if (updateNeeded)
        {
            updateNeeded = false;
            mainConfigList.Clear();
            mainConfigList.AddRange(from item in mainConfigItems
                where !(item.Item2 is ConfigElement configElement) || configElement.TextDisplayFunction().IndexOf(filterTextField.CurrentString, StringComparison.OrdinalIgnoreCase) != -1
                select item into x
                select x.Item1);
            Recalculate();
        }
    }
References Terraria.GameContent.UI.Elements.UIList.AddRange(), Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.ModLoader.UI.UIFocusInputTextField.CurrentString, Terraria.ModLoader.Config.UI.UIModConfig.DoMenuModeState(), Terraria.ModLoader.Config.UI.UIModConfig.filterTextField, Terraria.ModLoader.Config.UI.UIModConfig.mainConfigItems, Terraria.ModLoader.Config.UI.UIModConfig.mainConfigList, Terraria.ModLoader.Config.UI.UIModConfig.netUpdate, Terraria.ModLoader.Config.UI.UIModConfig.pendingChangesUIUpdate, Terraria.UI.UIElement.Recalculate(), Terraria.ModLoader.Config.UI.UIModConfig.revertConfigButton, Terraria.ModLoader.Config.UI.UIModConfig.saveConfigButton, Terraria.ModLoader.Config.UI.UIModConfig.uIElement, Terraria.ModLoader.Config.UI.UIModConfig.UpdateCount, and Terraria.ModLoader.Config.UI.UIModConfig.updateNeeded.