TModLoader: Terraria.ModLoader.Core.Cloning.ComputeInfo
ComputeInfo()
static TypeCloningInfo Terraria.ModLoader.Core.Cloning.ComputeInfo (Type type, MethodInfo cloneMethod) inline static private
    {
        TypeCloningInfo info = new TypeCloningInfo
        {
            type = type,
            overridesClone = (LoaderUtils.GetDerivedDefinition(type, cloneMethod).DeclaringType == type),
            fieldsWhichMightNeedDeepCloning = (from f in type.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic)
                where f.DeclaringType == type && !IsCloneByReference(f)
                select f).ToArray()
        };
        if (!info.overridesClone)
        {
            info.baseTypeInfo = GetOrComputeInfo(type.BaseType, cloneMethod);
        }
        typeInfos[type] = info;
        return info;
    }
References Terraria.ModLoader.Core.LoaderUtils.GetDerivedDefinition(), Terraria.ModLoader.Core.Cloning.GetOrComputeInfo(), Terraria.ModLoader.Core.Cloning.IsCloneByReference(), and Terraria.ModLoader.Core.Cloning.typeInfos.
Referenced by Terraria.ModLoader.Core.Cloning.GetOrComputeInfo(), and Terraria.ModLoader.Core.Cloning.IsCloneable< T, F >().