TModLoader: Terraria.GameContent.TreeTopsInfo.RandomizeTreeStyleBasedOnWorldPosition
RandomizeTreeStyleBasedOnWorldPosition()
void Terraria.GameContent.TreeTopsInfo.RandomizeTreeStyleBasedOnWorldPosition (UnifiedRandom rand, Vector2 worldPosition) inline
    {
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        Point pt = default(Point);
        ((Point)(ref pt))._002Ector((int)(worldPosition.X / 16f), (int)(worldPosition.Y / 16f) + 1);
        Tile tileSafely = Framing.GetTileSafely(pt);
        if (tileSafely.active())
        {
            int num = -1;
            if (tileSafely.type == 70)
            {
                num = 11;
            }
            else if (tileSafely.type == 53 && WorldGen.oceanDepths(pt.X, pt.Y))
            {
                num = 10;
            }
            else if (tileSafely.type == 23)
            {
                num = 4;
            }
            else if (tileSafely.type == 199)
            {
                num = 8;
            }
            else if (tileSafely.type == 109 || tileSafely.type == 492)
            {
                num = 7;
            }
            else if (tileSafely.type == 53)
            {
                num = 9;
            }
            else if (tileSafely.type == 147)
            {
                num = 6;
            }
            else if (tileSafely.type == 60)
            {
                num = 5;
            }
            else if (tileSafely.type == 633)
            {
                num = 12;
            }
            else if (tileSafely.type == 2 || tileSafely.type == 477)
            {
                num = ((pt.X >= Main.treeX[0]) ? ((pt.X < Main.treeX[1]) ? 1 : ((pt.X >= Main.treeX[2]) ? 3 : 2)) : 0);
            }
            if (num > -1)
            {
                RandomizeTreeStyle(rand, num);
            }
        }
    }
References Terraria.Framing.GetTileSafely(), Terraria.WorldGen.oceanDepths(), Terraria.GameContent.TreeTopsInfo.RandomizeTreeStyle(), and Terraria.Main.treeX.