TModLoader: Terraria.ModLoader.ModNet.ReceiveMod
ReceiveMod()
static void Terraria.ModLoader.ModNet.ReceiveMod (BinaryReader reader) inline static package
Definition at line 394 of file ModNet.cs.
    {
        if (downloadingMod == null)
        {
            return;
        }
        try
        {
            if (downloadingFile == null)
            {
                Interface.progress.Show(reader.ReadString(), 0, CancelDownload);
                if (ModLoader.TryGetMod(downloadingMod.name, out var mod))
                {
                    mod.Close();
                }
                downloadingLength = reader.ReadInt64();
                Logging.tML.Debug((object)$"Downloading: {downloadingMod.name} {downloadingLength}bytes");
                downloadingFile = new FileStream(downloadingMod.path, FileMode.Create);
                return;
            }
            byte[] bytes = reader.ReadBytes((int)Math.Min(downloadingLength - downloadingFile.Position, 16384L));
            downloadingFile.Write(bytes, 0, bytes.Length);
            Interface.progress.Progress = (float)downloadingFile.Position / (float)downloadingLength;
            if (downloadingFile.Position == downloadingLength)
            {
                downloadingFile.Close();
                TmodFile mod2 = new TmodFile(downloadingMod.path);
                using (mod2.Open())
                {
                }
                if (!downloadingMod.Matches(mod2))
                {
                    throw new Exception(Language.GetTextValue("tModLoader.MPErrorModHashMismatch"));
                }
                if (downloadingMod.signed && onlyDownloadSignedMods && !mod2.ValidModBrowserSignature)
                {
                    throw new Exception(Language.GetTextValue("tModLoader.MPErrorModNotSigned"));
                }
                ModLoader.EnableMod(mod2.Name);
                if (downloadQueue.Count > 0)
                {
                    DownloadNextMod();
                }
                else
                {
                    OnModsDownloaded(needsReload: true);
                }
            }
        }
        catch (Exception e)
        {
            try
            {
                downloadingFile?.Close();
                File.Delete(downloadingMod.path);
            }
            catch (Exception exc2)
            {
                Logging.tML.Error((object)"Unknown error during mod sync", exc2);
            }
            string msg = Language.GetTextValue("tModLoader.MPErrorModDownloadError", downloadingMod.name);
            Logging.tML.Error((object)msg, e);
            Interface.errorMessage.Show(msg + e, 0);
            Netplay.Disconnect = true;
            downloadingMod = null;
        }
    }
References Terraria.ModLoader.ModNet.CancelDownload(), Terraria.ModLoader.ModNet.downloadingFile, Terraria.ModLoader.ModNet.downloadingLength, Terraria.ModLoader.ModNet.downloadingMod, Terraria.ModLoader.ModNet.DownloadNextMod(), Terraria.ModLoader.ModNet.downloadQueue, Terraria.ModLoader.ModLoader.EnableMod(), Terraria.ModLoader.UI.Interface.errorMessage, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.ModNet.ModHeader.Matches(), Terraria.ModLoader.ModNet.ModHeader.name, Terraria.ModLoader.ModNet.onlyDownloadSignedMods, Terraria.ModLoader.ModNet.OnModsDownloaded(), Terraria.ModLoader.ModNet.ModHeader.path, Terraria.ModLoader.UI.Interface.progress, Terraria.ModLoader.UI.UIProgress.Show(), Terraria.ModLoader.UI.UIErrorMessage.Show(), Terraria.ModLoader.ModNet.ModHeader.signed, Terraria.ModLoader.Logging.tML, and Terraria.ModLoader.ModLoader.TryGetMod().
Referenced by Terraria.MessageBuffer.GetData().