TModLoader: Terraria.ModLoader.ModNet.SyncMods
SyncMods()
static void Terraria.ModLoader.ModNet.SyncMods (int clientIndex) inline static package
    {
        ModPacket p = new ModPacket(251);
        p.Write(AllowVanillaClients);
        List<Mod> syncMods = ModLoader.Mods.Where((Mod mod) => mod.Side == ModSide.Both).ToList();
        AddNoSyncDeps(syncMods);
        p.Write(syncMods.Count);
        foreach (Mod mod2 in syncMods)
        {
            p.Write(mod2.Name);
            p.Write(mod2.Version.ToString());
            p.Write(mod2.File.Hash);
            p.Write(mod2.File.ValidModBrowserSignature);
            SendServerConfigs(p, mod2);
        }
        p.Send(clientIndex);
    }
References Terraria.ModLoader.ModNet.AddNoSyncDeps(), Terraria.ModLoader.ModNet.AllowVanillaClients, Terraria.ModLoader.ModLoader.Mods, Terraria.ModLoader.ModNet.SendServerConfigs(), and Terraria.ModLoader.Mod.Side.
Referenced by Terraria.MessageBuffer.GetData().