TModLoader: Terraria.ModLoader.ModNet.SetModNetDiagnosticsUI
SetModNetDiagnosticsUI()
static void Terraria.ModLoader.ModNet.SetModNetDiagnosticsUI (IEnumerable< Mod > mods) inline static package
Definition at line 588 of file ModNet.cs.
    {
        INetDiagnosticsUI modNetDiagnosticsUI;
        if (!Main.dedServ)
        {
            INetDiagnosticsUI netDiagnosticsUI = new UIModNetDiagnostics(mods);
            modNetDiagnosticsUI = netDiagnosticsUI;
        }
        else
        {
            INetDiagnosticsUI netDiagnosticsUI = new EmptyDiagnosticsUI();
            modNetDiagnosticsUI = netDiagnosticsUI;
        }
        ModNetDiagnosticsUI = modNetDiagnosticsUI;
    }
References Terraria.Main.dedServ, and Terraria.ModLoader.ModNet.ModNetDiagnosticsUI.
Referenced by Terraria.ModLoader.ModContent.Load(), Terraria.ModLoader.ModNet.ReadNetIDs(), and Terraria.ModLoader.ModNet.Unload().