TModLoader: Terraria.ModLoader.ModNet.LogSend
LogSend()
static void Terraria.ModLoader.ModNet.LogSend (int toClient, int ignoreClient, string s, int len) inline static
Definition at line 713 of file ModNet.cs.
    {
        if (DetailedLogging)
        {
            s += $", {len}";
            if (ignoreClient != -1)
            {
                s += $", ignore: {ignoreClient}";
            }
            Debug(toClient, s);
        }
    }
References Terraria.ModLoader.ModNet.Debug(), and Terraria.ModLoader.ModNet.DetailedLogging.
Referenced by Terraria.Net.NetManager.LogSend(), Terraria.ModLoader.ModPacket.Send(), and Terraria.NetMessage.SendData().