TModLoader: Terraria.ModLoader.ModNet.HandleModPacket
HandleModPacket()
static void Terraria.ModLoader.ModNet.HandleModPacket (BinaryReader reader, int whoAmI, int length) inline static package
Definition at line 560 of file ModNet.cs.
    {
        if (netMods == null)
        {
            ReadNetIDs(reader);
            return;
        }
        short id = ((NetModCount < 256) ? reader.ReadByte() : reader.ReadInt16());
        int start = (int)reader.BaseStream.Position;
        int actualLength = length - 1 - ((NetModCount < 256) ? 1 : 2);
        try
        {
            ReadUnderflowBypass = false;
            GetMod(id)?.HandlePacket(reader, whoAmI);
            if (!ReadUnderflowBypass && reader.BaseStream.Position - start != actualLength)
            {
                throw new IOException($"Read underflow {reader.BaseStream.Position - start} of {actualLength} bytes caused by {GetMod(id).Name} in HandlePacket");
            }
        }
        catch
        {
        }
        if (Main.netMode == 1 && id >= 0)
        {
            ModNetDiagnosticsUI.CountReadMessage(id, length);
        }
    }
References Terraria.UI.INetDiagnosticsUI.CountReadMessage(), Terraria.ModLoader.ModNet.GetMod(), Terraria.ModLoader.Mod.HandlePacket(), Terraria.ModLoader.ModNet.ModNetDiagnosticsUI, Terraria.ModLoader.ModNet.NetModCount, Terraria.Main.netMode, Terraria.ModLoader.ModNet.netMods, Terraria.ModLoader.ModNet.ReadNetIDs(), and Terraria.ModLoader.ModNet.ReadUnderflowBypass.
Referenced by Terraria.MessageBuffer.GetData().