TModLoader: Terraria.ModLoader.ModNet.SyncClientMods
SyncClientMods() [2/2]
static bool Terraria.ModLoader.ModNet.SyncClientMods (BinaryReader reader, out bool needsReload) inline static package
Definition at line 264 of file ModNet.cs.
    {
        AllowVanillaClients = reader.ReadBoolean();
        Logging.tML.Info((object)$"Server reports AllowVanillaClients set to {AllowVanillaClients}");
        Main.statusText = Language.GetTextValue("tModLoader.MPSyncingMods");
        Mod[] clientMods = ModLoader.Mods;
        LocalMod[] modFiles = ModOrganizer.FindMods();
        needsReload = false;
        downloadQueue.Clear();
        pendingConfigs.Clear();
        List<ModHeader> syncList = new List<ModHeader>();
        HashSet<string> syncSet = new HashSet<string>();
        List<ModHeader> blockedList = new List<ModHeader>();
        int j = reader.ReadInt32();
        for (int i = 0; i < j; i++)
        {
            ModHeader header = new ModHeader(reader.ReadString(), new Version(reader.ReadString()), reader.ReadBytes(20), reader.ReadBoolean());
            syncList.Add(header);
            syncSet.Add(header.name);
            int configCount = reader.ReadInt32();
            for (int c = 0; c < configCount; c++)
            {
                pendingConfigs.Add(new NetConfig(header.name, reader.ReadString(), reader.ReadString()));
            }
            Mod clientMod = clientMods.SingleOrDefault((Mod m) => m.Name == header.name);
            if (clientMod != null && header.Matches(clientMod.File))
            {
                continue;
            }
            needsReload = true;
            LocalMod[] localVersions = modFiles.Where((LocalMod m) => m.Name == header.name).ToArray();
            LocalMod matching = Array.Find(localVersions, (LocalMod mod) => header.Matches(mod.modFile));
            if (matching != null)
            {
                matching.Enabled = true;
                continue;
            }
            if (localVersions.Length != 0)
            {
                header.path = localVersions[0].modFile.path;
            }
            if (downloadModsFromServers && (header.signed || !onlyDownloadSignedMods))
            {
                downloadQueue.Enqueue(header);
            }
            else
            {
                blockedList.Add(header);
            }
        }
        Logging.tML.Debug((object)("Server mods: " + string.Join(", ", syncList)));
        Logging.tML.Debug((object)("Download queue: " + string.Join(", ", downloadQueue)));
        if (pendingConfigs.Any())
        {
            Logging.tML.Debug((object)("Configs:\n\t\t" + string.Join("\n\t\t", pendingConfigs)));
        }
        Mod[] array = clientMods;
        foreach (Mod mod2 in array)
        {
            if (mod2.Side == ModSide.Both && !syncSet.Contains(mod2.Name))
            {
                ModLoader.DisableMod(mod2.Name);
                needsReload = true;
            }
        }
        if (blockedList.Count > 0)
        {
            string msg = Language.GetTextValue("tModLoader.MPServerModsCantDownload");
            msg += (downloadModsFromServers ? Language.GetTextValue("tModLoader.MPServerModsCantDownloadReasonSigned") : Language.GetTextValue("tModLoader.MPServerModsCantDownloadReasonAutomaticDownloadDisabled"));
            msg = msg + ".\n" + Language.GetTextValue("tModLoader.MPServerModsCantDownloadChangeSettingsHint") + "\n";
            foreach (ModHeader item in blockedList)
            {
                msg = msg + "\n    " + item;
            }
            Logging.tML.Warn((object)msg);
            Interface.errorMessage.Show(msg, 0);
            return false;
        }
        if (!needsReload)
        {
            foreach (NetConfig pendingConfig in pendingConfigs)
            {
                JsonConvert.PopulateObject(pendingConfig.json, (object)ConfigManager.GetConfig(pendingConfig), ConfigManager.serializerSettingsCompact);
            }
            if (ConfigManager.AnyModNeedsReload())
            {
                needsReload = true;
            }
            else
            {
                foreach (NetConfig pendingConfig2 in pendingConfigs)
                {
                    ConfigManager.GetConfig(pendingConfig2).OnChanged();
                }
            }
        }
        return true;
    }
References Terraria.ModLoader.ModNet.AllowVanillaClients, Terraria.ModLoader.Config.ConfigManager.AnyModNeedsReload(), Terraria.ModLoader.ModLoader.DisableMod(), Terraria.ModLoader.ModNet.downloadModsFromServers, Terraria.ModLoader.ModNet.downloadQueue, Terraria.ModLoader.UI.Interface.errorMessage, Terraria.ModLoader.Core.ModOrganizer.FindMods(), Terraria.ModLoader.Config.ConfigManager.GetConfig(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.ModNet.NetConfig.json, Terraria.ModLoader.ModNet.ModHeader.Matches(), Terraria.ModLoader.Core.LocalMod.modFile, Terraria.ModLoader.ModLoader.Mods, Terraria.ModLoader.ModNet.ModHeader.name, Terraria.ModLoader.ModNet.onlyDownloadSignedMods, Terraria.ModLoader.ModNet.pendingConfigs, Terraria.ModLoader.Config.ConfigManager.serializerSettingsCompact, Terraria.ModLoader.ModNet.ModHeader.signed, and Terraria.ModLoader.Logging.tML.