TModLoader: Terraria.ModLoader.ModNet.Log
Log() [1/3]
static void Terraria.ModLoader.ModNet.Log (int whoAmI, string s) inline static
Definition at line 650 of file ModNet.cs.
    {
        Log(Identifier(whoAmI) + s);
    }
References Terraria.ModLoader.ModNet.Identifier(), and Terraria.ModLoader.ModNet.Log().
Referenced by Terraria.Net.Sockets.SocialSocket.Close(), Terraria.Net.Sockets.TcpSocket.Close(), Terraria.ModLoader.ModNet.Log(), Terraria.ModLoader.ModNet.Log(), and Terraria.RemoteClient.SetPendingTermination().