TModLoader: Terraria.ModLoader.ModNet.Identifier
Identifier() [1/2]
static string Terraria.ModLoader.ModNet.Identifier (int whoAmI) inline static private
Definition at line 618 of file ModNet.cs.
    {
        if (!Main.dedServ)
        {
            return "";
        }
        if (whoAmI >= 0 && whoAmI < 256)
        {
            RemoteClient client = Netplay.Clients[whoAmI];
            return $"[{whoAmI}][{client.Socket?.GetRemoteAddress()?.GetFriendlyName()} ({client.Name})] ";
        }
        if (whoAmI == -1)
        {
            return "[*] ";
        }
        return $"[{whoAmI}] ";
    }
References Terraria.Netplay.Clients, and Terraria.Main.dedServ.
Referenced by Terraria.ModLoader.ModNet.Debug(), Terraria.ModLoader.ModNet.Debug(), Terraria.ModLoader.ModNet.Error(), Terraria.ModLoader.ModNet.Error(), Terraria.ModLoader.ModNet.Identifier(), Terraria.ModLoader.ModNet.Log(), Terraria.ModLoader.ModNet.Log(), Terraria.ModLoader.ModNet.Warn(), and Terraria.ModLoader.ModNet.Warn().