TModLoader: Terraria.ModLoader.UI.UICreateMod.OKClick
OKClick()
void Terraria.ModLoader.UI.UICreateMod.OKClick (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 294 of file UICreateMod.cs.
    {
        try
        {
            string modNameTrimmed = _modName.CurrentString.Trim();
            string basicSwordTrimmed = _basicSword.CurrentString.Trim();
            string sourceFolder = Path.Combine(ModCompile.ModSourcePath, modNameTrimmed);
            CodeDomProvider provider = CodeDomProvider.CreateProvider("C#");
            if (Directory.Exists(sourceFolder))
            {
                _messagePanel.SetText("Folder already exists");
                return;
            }
            if (!provider.IsValidIdentifier(modNameTrimmed))
            {
                _messagePanel.SetText("ModName is invalid C# identifier. Remove spaces.");
                return;
            }
            if (modNameTrimmed.Equals("Mod", StringComparison.InvariantCultureIgnoreCase) || modNameTrimmed.Equals("ModLoader", StringComparison.InvariantCultureIgnoreCase) || modNameTrimmed.Equals("tModLoader", StringComparison.InvariantCultureIgnoreCase))
            {
                _messagePanel.SetText("ModName is a reserved mod name. Choose a different name.");
                return;
            }
            if (!string.IsNullOrEmpty(basicSwordTrimmed) && !provider.IsValidIdentifier(basicSwordTrimmed))
            {
                _messagePanel.SetText("BasicSword is invalid C# identifier. Remove spaces.");
                return;
            }
            if (string.IsNullOrWhiteSpace(_modDiplayName.CurrentString))
            {
                _messagePanel.SetText("DisplayName can't be empty");
                return;
            }
            if (string.IsNullOrWhiteSpace(_modAuthor.CurrentString))
            {
                _messagePanel.SetText("Author can't be empty");
                return;
            }
            Directory.CreateDirectory(sourceFolder);
            File.WriteAllText(Path.Combine(sourceFolder, "build.txt"), GetModBuild());
            File.WriteAllText(Path.Combine(sourceFolder, "description.txt"), GetModDescription());
            using (Stream stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("Terraria.ModLoader.Default.iconTemplate.png"))
            {
                using FileStream fs = File.OpenWrite(Path.Combine(sourceFolder, "icon.png"));
                stream.CopyTo(fs);
            }
            File.WriteAllText(Path.Combine(sourceFolder, modNameTrimmed + ".cs"), GetModClass(modNameTrimmed));
            File.WriteAllText(Path.Combine(sourceFolder, modNameTrimmed + ".csproj"), GetModCsproj(modNameTrimmed));
            string text = Path.Combine(sourceFolder, "Properties");
            Directory.CreateDirectory(text);
            File.WriteAllText(Path.Combine(text, "launchSettings.json"), GetLaunchSettings());
            if (!string.IsNullOrEmpty(basicSwordTrimmed))
            {
                string text2 = Path.Combine(sourceFolder, "Items");
                Directory.CreateDirectory(text2);
                File.WriteAllText(Path.Combine(text2, basicSwordTrimmed + ".cs"), GetBasicSword(modNameTrimmed, basicSwordTrimmed));
                File.WriteAllBytes(Path.Combine(text2, basicSwordTrimmed + ".png"), ExampleSwordPNG);
            }
            string text3 = Path.Combine(sourceFolder, "Localization");
            Directory.CreateDirectory(text3);
            File.WriteAllText(Path.Combine(text3, "en-US_Mods." + modNameTrimmed + ".hjson"), GetLocalizationFile(modNameTrimmed, basicSwordTrimmed));
            Utils.OpenFolder(sourceFolder);
            SoundEngine.PlaySound(in SoundID.MenuOpen);
            Main.menuMode = 10001;
        }
        catch (Exception e)
        {
            Logging.tML.Error((object)e);
            _messagePanel.SetText("There was an issue. Check client.log");
        }
    }
References Terraria.ModLoader.UI.UICreateMod._basicSword, Terraria.ModLoader.UI.UICreateMod._messagePanel, Terraria.ModLoader.UI.UICreateMod._modAuthor, Terraria.ModLoader.UI.UICreateMod._modDiplayName, Terraria.ModLoader.UI.UICreateMod._modName, Terraria.ModLoader.UI.UIFocusInputTextField.CurrentString, Terraria.ModLoader.UI.UICreateMod.ExampleSwordPNG, Terraria.ModLoader.UI.UICreateMod.GetBasicSword(), Terraria.ModLoader.UI.UICreateMod.GetLaunchSettings(), Terraria.ModLoader.UI.UICreateMod.GetLocalizationFile(), Terraria.ModLoader.UI.UICreateMod.GetModBuild(), Terraria.ModLoader.UI.UICreateMod.GetModClass(), Terraria.ModLoader.UI.UICreateMod.GetModCsproj(), Terraria.ModLoader.UI.UICreateMod.GetModDescription(), Terraria.ID.SoundID.MenuOpen, Terraria.ModLoader.Core.ModCompile.ModSourcePath, Terraria.Utils.OpenFolder(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.Elements.UITextPanel< T >.SetText(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.ModLoader.UI.UICreateMod.OnInitialize().