TModLoader: Terraria.ModLoader.UI.UICreateMod.OnInitialize
OnInitialize()
override void Terraria.ModLoader.UI.UICreateMod.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
    {
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_025b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0261: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_026b: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        //IL_027f: Unknown result type (might be due to invalid IL or missing references)
        _baseElement = new UIElement
        {
            Width =
            {
                Percent = 0.8f
            },
            MaxWidth = UICommon.MaxPanelWidth,
            Top =
            {
                Pixels = 220f
            },
            Height =
            {
                Pixels = -220f,
                Percent = 1f
            },
            HAlign = 0.5f
        };
        Append(_baseElement);
        UIPanel mainPanel = new UIPanel
        {
            Width =
            {
                Percent = 1f
            },
            Height =
            {
                Pixels = -110f,
                Percent = 1f
            },
            BackgroundColor = UICommon.MainPanelBackground,
            PaddingTop = 0f
        };
        _baseElement.Append(mainPanel);
        UITextPanel<string> uITextPanel = new UITextPanel<string>(Language.GetTextValue("tModLoader.MSCreateMod"), 0.8f, large: true)
        {
            HAlign = 0.5f,
            Top =
            {
                Pixels = -35f
            },
            BackgroundColor = UICommon.DefaultUIBlue
        }.WithPadding(15f);
        _baseElement.Append(uITextPanel);
        _messagePanel = new UITextPanel<string>(Language.GetTextValue(""))
        {
            Width =
            {
                Percent = 1f
            },
            Height =
            {
                Pixels = 25f
            },
            VAlign = 1f,
            Top =
            {
                Pixels = -20f
            }
        };
        UITextPanel<string> buttonBack = new UITextPanel<string>(Language.GetTextValue("UI.Back"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.5f
            },
            Height =
            {
                Pixels = 25f
            },
            VAlign = 1f,
            Top =
            {
                Pixels = -65f
            }
        }.WithFadedMouseOver();
        buttonBack.OnLeftClick += BackClick;
        _baseElement.Append(buttonBack);
        UITextPanel<string> buttonCreate = new UITextPanel<string>(Language.GetTextValue("LegacyMenu.28"));
        buttonCreate.CopyStyle(buttonBack);
        buttonCreate.HAlign = 1f;
        buttonCreate.WithFadedMouseOver();
        buttonCreate.OnLeftClick += OKClick;
        _baseElement.Append(buttonCreate);
        float top = 16f;
        _modName = createAndAppendTextInputWithLabel("ModName (no spaces)", "Type here");
        _modName.OnTextChange += delegate
        {
            _modName.SetText(_modName.CurrentString.Replace(" ", ""));
        };
        _modDiplayName = createAndAppendTextInputWithLabel("Mod DisplayName", "Type here");
        _modAuthor = createAndAppendTextInputWithLabel("Mod Author", "Type here");
        _basicSword = createAndAppendTextInputWithLabel("BasicSword (no spaces)", "Leave Blank to Skip");
        _modName.OnTab += delegate
        {
            _modDiplayName.Focused = true;
        };
        _modDiplayName.OnTab += delegate
        {
            _modAuthor.Focused = true;
        };
        _modAuthor.OnTab += delegate
        {
            _basicSword.Focused = true;
        };
        _basicSword.OnTab += delegate
        {
            _modName.Focused = true;
        };
        UIFocusInputTextField createAndAppendTextInputWithLabel(string label, string hint)
        {
            UIPanel panel = new UIPanel();
            panel.SetPadding(0f);
            panel.Width.Set(0f, 1f);
            panel.Height.Set(40f, 0f);
            panel.Top.Set(top, 0f);
            top += 46f;
            UIText modNameText = new UIText(label)
            {
                Left =
                {
                    Pixels = 10f
                },
                Top =
                {
                    Pixels = 10f
                }
            };
            panel.Append(modNameText);
            UIPanel textBoxBackground = new UIPanel();
            textBoxBackground.SetPadding(0f);
            textBoxBackground.Top.Set(6f, 0f);
            textBoxBackground.Left.Set(0f, 0.5f);
            textBoxBackground.Width.Set(0f, 0.5f);
            textBoxBackground.Height.Set(30f, 0f);
            panel.Append(textBoxBackground);
            UIFocusInputTextField uIInputTextField = new UIFocusInputTextField(hint)
            {
                UnfocusOnTab = true
            };
            uIInputTextField.Top.Set(5f, 0f);
            uIInputTextField.Left.Set(10f, 0f);
            uIInputTextField.Width.Set(-20f, 1f);
            uIInputTextField.Height.Set(20f, 0f);
            textBoxBackground.Append(uIInputTextField);
            mainPanel.Append(panel);
            return uIInputTextField;
        }
    }
References Terraria.ModLoader.UI.UICreateMod._baseElement, Terraria.ModLoader.UI.UICreateMod._basicSword, Terraria.ModLoader.UI.UICreateMod._messagePanel, Terraria.ModLoader.UI.UICreateMod._modAuthor, Terraria.ModLoader.UI.UICreateMod._modDiplayName, Terraria.ModLoader.UI.UICreateMod._modName, Terraria.UI.UIElement.Append(), Terraria.ModLoader.UI.UICreateMod.BackClick(), Terraria.ModLoader.UI.UIFocusInputTextField.CurrentString, Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.ModLoader.UI.UICommon.MainPanelBackground, Terraria.ModLoader.UI.UICommon.MaxPanelWidth, Terraria.UI.UIElement.MaxWidth, Terraria.ModLoader.UI.UICreateMod.OKClick(), Terraria.UI.UIElement.PaddingTop, Terraria.ModLoader.UI.UIFocusInputTextField.SetText(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.