TModLoader: Terraria.Collision.IsWorldPointSolid
IsWorldPointSolid()
static bool Terraria.Collision.IsWorldPointSolid (Vector2 pos, bool treatPlatformsAsNonSolid = false) inline static
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
        Point point = pos.ToTileCoordinates();
        if (!WorldGen.InWorld(point.X, point.Y, 1))
        {
            return false;
        }
        Tile tile = Main.tile[point.X, point.Y];
        if (tile == null || !tile.active() || tile.inActive() || !Main.tileSolid[tile.type])
        {
            return false;
        }
        if (treatPlatformsAsNonSolid && tile.type > 0 && (TileID.Sets.Platforms[tile.type] || tile.type == 380))
        {
            return false;
        }
        int num = tile.blockType();
        switch (num)
        {
        case 0:
            if (pos.X >= (float)(point.X * 16) && pos.X <= (float)(point.X * 16 + 16) && pos.Y >= (float)(point.Y * 16))
            {
                return pos.Y <= (float)(point.Y * 16 + 16);
            }
            return false;
        case 1:
            if (pos.X >= (float)(point.X * 16) && pos.X <= (float)(point.X * 16 + 16) && pos.Y >= (float)(point.Y * 16 + 8))
            {
                return pos.Y <= (float)(point.Y * 16 + 16);
            }
            return false;
        case 2:
        case 3:
        case 4:
        case 5:
        {
            if (pos.X < (float)(point.X * 16) && pos.X > (float)(point.X * 16 + 16) && pos.Y < (float)(point.Y * 16) && pos.Y > (float)(point.Y * 16 + 16))
            {
                return false;
            }
            float num2 = pos.X % 16f;
            float num3 = pos.Y % 16f;
            switch (num)
            {
            case 3:
                return num2 + num3 >= 16f;
            case 2:
                return num3 >= num2;
            case 5:
                return num3 <= num2;
            case 4:
                return num2 + num3 <= 16f;
            }
            break;
        }
        }
        return false;
    }
References Terraria.Tile.active(), Terraria.Tile.blockType(), Terraria.Tile.inActive(), Terraria.WorldGen.InWorld(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Tile.type.