TModLoader: Terraria.Collision.AdvancedTileCollision
AdvancedTileCollision()
static Vector2 Terraria.Collision.AdvancedTileCollision (bool[] forcedIgnoredTiles, Vector2 Position, Vector2 Velocity, int Width, int Height, bool fallThrough = false, bool fall2 = false, int gravDir = 1) inline static
    {
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0602: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_019d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0311: Unknown result type (might be due to invalid IL or missing references)
        //IL_031b: Unknown result type (might be due to invalid IL or missing references)
        //IL_028d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0297: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_0238: Unknown result type (might be due to invalid IL or missing references)
        //IL_0244: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_049c: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_035a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0340: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0575: Unknown result type (might be due to invalid IL or missing references)
        //IL_057b: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_038c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0393: Unknown result type (might be due to invalid IL or missing references)
        //IL_046b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0472: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0547: Unknown result type (might be due to invalid IL or missing references)
        //IL_0554: Unknown result type (might be due to invalid IL or missing references)
        //IL_048c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0568: Unknown result type (might be due to invalid IL or missing references)
        up = false;
        down = false;
        Vector2 result = Velocity;
        Vector2 vector2 = Position + Velocity;
        int value5 = (int)(Position.X / 16f) - 1;
        int value2 = (int)((Position.X + (float)Width) / 16f) + 2;
        int value3 = (int)(Position.Y / 16f) - 1;
        int value4 = (int)((Position.Y + (float)Height) / 16f) + 2;
        int num = -1;
        int num2 = -1;
        int num3 = -1;
        int num4 = -1;
        int num7 = Utils.Clamp(value5, 0, Main.maxTilesX - 1);
        value2 = Utils.Clamp(value2, 0, Main.maxTilesX - 1);
        value3 = Utils.Clamp(value3, 0, Main.maxTilesY - 1);
        value4 = Utils.Clamp(value4, 0, Main.maxTilesY - 1);
        float num5 = (value4 + 3) * 16;
        Vector2 vector3 = default(Vector2);
        for (int i = num7; i < value2; i++)
        {
            for (int j = value3; j < value4; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile == null || !tile.active() || tile.inActive() || forcedIgnoredTiles[tile.type] || (!Main.tileSolid[tile.type] && (!Main.tileSolidTop[tile.type] || tile.frameY != 0)))
                {
                    continue;
                }
                vector3.X = i * 16;
                vector3.Y = j * 16;
                int num6 = 16;
                if (tile.halfBrick())
                {
                    vector3.Y += 8f;
                    num6 -= 8;
                }
                if (!(vector2.X + (float)Width > vector3.X) || !(vector2.X < vector3.X + 16f) || !(vector2.Y + (float)Height > vector3.Y) || !(vector2.Y < vector3.Y + (float)num6))
                {
                    continue;
                }
                bool flag = false;
                bool flag2 = false;
                if (tile.slope() > 2)
                {
                    if (tile.slope() == 3 && Position.Y + Math.Abs(Velocity.X) >= vector3.Y && Position.X >= vector3.X)
                    {
                        flag2 = true;
                    }
                    if (tile.slope() == 4 && Position.Y + Math.Abs(Velocity.X) >= vector3.Y && Position.X + (float)Width <= vector3.X + 16f)
                    {
                        flag2 = true;
                    }
                }
                else if (tile.slope() > 0)
                {
                    flag = true;
                    if (tile.slope() == 1 && Position.Y + (float)Height - Math.Abs(Velocity.X) <= vector3.Y + (float)num6 && Position.X >= vector3.X)
                    {
                        flag2 = true;
                    }
                    if (tile.slope() == 2 && Position.Y + (float)Height - Math.Abs(Velocity.X) <= vector3.Y + (float)num6 && Position.X + (float)Width <= vector3.X + 16f)
                    {
                        flag2 = true;
                    }
                }
                if (flag2)
                {
                    continue;
                }
                if (Position.Y + (float)Height <= vector3.Y)
                {
                    down = true;
                    if ((!(Main.tileSolidTop[tile.type] && fallThrough) || !(Velocity.Y <= 1f || fall2)) && num5 > vector3.Y)
                    {
                        num3 = i;
                        num4 = j;
                        if (num6 < 16)
{
                            num4++;
                        }
                        if (num3 != num && !flag)
{
                            result.Y = vector3.Y - (Position.Y + (float)Height) + ((gravDir == -1) ? (-0.01f) : 0f);
                            num5 = vector3.Y;
                        }
                    }
                }
                else if (Position.X + (float)Width <= vector3.X && !Main.tileSolidTop[tile.type])
                {
                    if (Main.tile[i - 1, j] == null)
                    {
                        Main.tile[i - 1, j] = default(Tile);
                    }
                    if (Main.tile[i - 1, j].slope() != 2 && Main.tile[i - 1, j].slope() != 4)
                    {
                        num = i;
                        num2 = j;
                        if (num2 != num4)
{
                            result.X = vector3.X - (Position.X + (float)Width);
                        }
                        if (num3 == num)
{
                            result.Y = Velocity.Y;
                        }
                    }
                }
                else if (Position.X >= vector3.X + 16f && !Main.tileSolidTop[tile.type])
                {
                    if (Main.tile[i + 1, j] == null)
                    {
                        Main.tile[i + 1, j] = default(Tile);
                    }
                    if (Main.tile[i + 1, j].slope() != 1 && Main.tile[i + 1, j].slope() != 3)
                    {
                        num = i;
                        num2 = j;
                        if (num2 != num4)
{
                            result.X = vector3.X + 16f - Position.X;
                        }
                        if (num3 == num)
{
                            result.Y = Velocity.Y;
                        }
                    }
                }
                else if (Position.Y >= vector3.Y + (float)num6 && !Main.tileSolidTop[tile.type])
                {
                    up = true;
                    num3 = i;
                    num4 = j;
                    result.Y = vector3.Y + (float)num6 - Position.Y + ((gravDir == 1) ? 0.01f : 0f);
                    if (num4 == num2)
                    {
                        result.X = Velocity.X;
                    }
                }
            }
        }
        return result;
    }
References Terraria.Tile.active(), Terraria.Collision.down, Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, and Terraria.Collision.up.
Referenced by Terraria.NPC.Collision_MoveSandshark().