TModLoader: Terraria.Collision.StepDown
StepDown()
static void Terraria.Collision.StepDown (ref Vector2 position, ref Vector2 velocity, int width, int height, ref float stepSpeed, ref float gfxOffY, int gravDir = 1, bool waterWalk = false) inline static
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = position;
        vector.X += velocity.X;
        vector.Y = (float)Math.Floor((vector.Y + (float)height) / 16f) * 16f - (float)height;
        bool flag = false;
        int num19 = (int)(vector.X / 16f);
        int num11 = (int)((vector.X + (float)width) / 16f);
        int num12 = (int)((vector.Y + (float)height + 4f) / 16f);
        int num13 = height / 16 + ((height % 16 != 0) ? 1 : 0);
        float num14 = (num12 + num13) * 16;
        float num15 = Main.bottomWorld / 16f - 42f;
        for (int i = num19; i <= num11; i++)
        {
            for (int j = num12; j <= num12 + 1; j++)
            {
                if (!WorldGen.InWorld(i, j, 1))
                {
                    continue;
                }
                if (Main.tile[i, j] == null)
                {
                    Main.tile[i, j] = default(Tile);
                }
                if (Main.tile[i, j - 1] == null)
                {
                    Main.tile[i, j - 1] = default(Tile);
                }
                if (waterWalk && Main.tile[i, j].liquid > 0 && Main.tile[i, j - 1].liquid == 0)
                {
                    int num16 = Main.tile[i, j].liquid / 32 * 2 + 2;
                    int num17 = j * 16 + 16 - num16;
                    Rectangle val = new Rectangle(i * 16, j * 16 - 17, 16, 16);
                    if (((Rectangle)(ref val)).Intersects(new Rectangle((int)position.X, (int)position.Y, width, height)) && (float)num17 < num14)
                    {
                        num14 = num17;
                    }
                }
                if ((float)j >= num15 || (Main.tile[i, j].nactive() && (Main.tileSolid[Main.tile[i, j].type] || Main.tileSolidTop[Main.tile[i, j].type])))
                {
                    int num18 = j * 16;
                    if (Main.tile[i, j].halfBrick())
                    {
                        num18 += 8;
                    }
                    if (Utils.FloatIntersect(i * 16, j * 16 - 17, 16f, 16f, position.X, position.Y, width, height) && (float)num18 < num14)
                    {
                        num14 = num18;
                    }
                }
            }
        }
        float num10 = num14 - (position.Y + (float)height);
        if (num10 > 7f && num10 < 17f && !flag)
        {
            stepSpeed = 1.5f;
            if (num10 > 9f)
            {
                stepSpeed = 2.5f;
            }
            gfxOffY += position.Y + (float)height - num14;
            position.Y = num14 - (float)height;
        }
    }
References Terraria.Utils.FloatIntersect(), Terraria.WorldGen.InWorld(), Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Main.tileSolidTop.
Referenced by Terraria.NPC.AI_007_TownEntities(), Terraria.Player.DryCollision(), and Terraria.Player.Update().