TModLoader: Terraria.Collision.WetCollision
WetCollision()
static bool Terraria.Collision.WetCollision (Vector2 Position, int Width, int Height) inline static
Definition at line 1685 of file Collision.cs.
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0304: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        honey = false;
        shimmer = false;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(Position.X + (float)(Width / 2), Position.Y + (float)(Height / 2));
        int num = 10;
        int num2 = Height / 2;
        if (num > Width)
        {
            num = Width;
        }
        if (num2 > Height)
        {
            num2 = Height;
        }
        ((Vector2)(ref vector))._002Ector(vector.X - (float)(num / 2), vector.Y - (float)(num2 / 2));
        int value5 = (int)(Position.X / 16f) - 1;
        int value2 = (int)((Position.X + (float)Width) / 16f) + 2;
        int value3 = (int)(Position.Y / 16f) - 1;
        int value4 = (int)((Position.Y + (float)Height) / 16f) + 2;
        int num6 = Utils.Clamp(value5, 0, Main.maxTilesX - 1);
        value2 = Utils.Clamp(value2, 0, Main.maxTilesX - 1);
        value3 = Utils.Clamp(value3, 0, Main.maxTilesY - 1);
        value4 = Utils.Clamp(value4, 0, Main.maxTilesY - 1);
        Vector2 vector2 = default(Vector2);
        for (int i = num6; i < value2; i++)
        {
            for (int j = value3; j < value4; j++)
            {
                if (Main.tile[i, j] == null)
                {
                    continue;
                }
                if (Main.tile[i, j].liquid > 0)
                {
                    vector2.X = i * 16;
                    vector2.Y = j * 16;
                    int num3 = 16;
                    float num4 = 256 - Main.tile[i, j].liquid;
                    num4 /= 32f;
                    vector2.Y += num4 * 2f;
                    num3 -= (int)(num4 * 2f);
                    if (vector.X + (float)num > vector2.X && vector.X < vector2.X + 16f && vector.Y + (float)num2 > vector2.Y && vector.Y < vector2.Y + (float)num3)
                    {
                        if (Main.tile[i, j].honey())
{
                            honey = true;
                        }
                        if (Main.tile[i, j].shimmer())
{
                            shimmer = true;
                        }
                        return true;
                    }
                }
                else
                {
                    if (!Main.tile[i, j].active() || Main.tile[i, j].slope() == 0 || j <= 0 || Main.tile[i, j - 1] == null || Main.tile[i, j - 1].liquid <= 0)
                    {
                        continue;
                    }
                    vector2.X = i * 16;
                    vector2.Y = j * 16;
                    int num5 = 16;
                    if (vector.X + (float)num > vector2.X && vector.X < vector2.X + 16f && vector.Y + (float)num2 > vector2.Y && vector.Y < vector2.Y + (float)num5)
                    {
                        if (Main.tile[i, j - 1].honey())
{
                            honey = true;
                        }
                        else if (Main.tile[i, j - 1].shimmer())
{
                            shimmer = true;
                        }
                        return true;
                    }
                }
            }
        }
        return false;
    }
References Terraria.Collision.honey, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Collision.shimmer, and Terraria.Main.tile.
Referenced by Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Player.CheckForGoodTeleportationSpot(), Terraria.NPC.Collision_WaterCollision(), Terraria.GameContent.Shaders.WaterShaderData.DrawWaves(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.ShimmerHelper.IsSpotShimmerFree(), Terraria.Item.MoveInWorld(), Terraria.Dust.NewDust(), Terraria.Item.NewItem_Inner(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.Player.ShimmerUnstuck(), Terraria.Player.SporeSac(), Terraria.Gore.Update(), Terraria.Rain.Update(), Terraria.Player.Update(), Terraria.Projectile.Update(), Terraria.Dust.UpdateDust(), and Terraria.NPC.UpdateNPC_Inner().