TModLoader: Terraria.Collision.TileCollision
TileCollision()
static Vector2 Terraria.Collision.TileCollision (Vector2 Position, Vector2 Velocity, int Width, int Height, bool fallThrough = false, bool fall2 = false, int gravDir = 1) inline static
    {
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_0269: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0328: Unknown result type (might be due to invalid IL or missing references)
        //IL_0331: Unknown result type (might be due to invalid IL or missing references)
        //IL_033d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_047a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0483: Unknown result type (might be due to invalid IL or missing references)
        //IL_0376: Unknown result type (might be due to invalid IL or missing references)
        //IL_037f: Unknown result type (might be due to invalid IL or missing references)
        //IL_038b: Unknown result type (might be due to invalid IL or missing references)
        //IL_034a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0350: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_056d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0573: Unknown result type (might be due to invalid IL or missing references)
        //IL_0412: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0398: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0659: Unknown result type (might be due to invalid IL or missing references)
        //IL_065f: Unknown result type (might be due to invalid IL or missing references)
        //IL_069c: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_053c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0543: Unknown result type (might be due to invalid IL or missing references)
        //IL_0444: Unknown result type (might be due to invalid IL or missing references)
        //IL_044b: Unknown result type (might be due to invalid IL or missing references)
        //IL_055d: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0628: Unknown result type (might be due to invalid IL or missing references)
        //IL_0635: Unknown result type (might be due to invalid IL or missing references)
        //IL_046c: Unknown result type (might be due to invalid IL or missing references)
        //IL_064c: Unknown result type (might be due to invalid IL or missing references)
        up = false;
        down = false;
        Vector2 result = Velocity;
        Vector2 vector2 = Position + Velocity;
        int value5 = (int)(Position.X / 16f) - 1;
        int value2 = (int)((Position.X + (float)Width) / 16f) + 2;
        int value3 = (int)(Position.Y / 16f) - 1;
        int value4 = (int)((Position.Y + (float)Height) / 16f) + 2;
        int num = -1;
        int num2 = -1;
        int num3 = -1;
        int num4 = -1;
        int num7 = Utils.Clamp(value5, 0, Main.maxTilesX - 1);
        value2 = Utils.Clamp(value2, 0, Main.maxTilesX - 1);
        value3 = Utils.Clamp(value3, 0, Main.maxTilesY - 1);
        value4 = Utils.Clamp(value4, 0, Main.maxTilesY - 1);
        float num5 = (value4 + 3) * 16;
        Vector2 vector3 = default(Vector2);
        for (int i = num7; i < value2; i++)
        {
            for (int j = value3; j < value4; j++)
            {
                if (Main.tile[i, j] == null || !Main.tile[i, j].active() || Main.tile[i, j].inActive() || (!Main.tileSolid[Main.tile[i, j].type] && (!Main.tileSolidTop[Main.tile[i, j].type] || Main.tile[i, j].frameY != 0)))
                {
                    continue;
                }
                vector3.X = i * 16;
                vector3.Y = j * 16;
                int num6 = 16;
                if (Main.tile[i, j].halfBrick())
                {
                    vector3.Y += 8f;
                    num6 -= 8;
                }
                if (!(vector2.X + (float)Width > vector3.X) || !(vector2.X < vector3.X + 16f) || !(vector2.Y + (float)Height > vector3.Y) || !(vector2.Y < vector3.Y + (float)num6))
                {
                    continue;
                }
                bool flag = false;
                bool flag2 = false;
                if (Main.tile[i, j].slope() > 2)
                {
                    if (Main.tile[i, j].slope() == 3 && Position.Y + Math.Abs(Velocity.X) >= vector3.Y && Position.X >= vector3.X)
                    {
                        flag2 = true;
                    }
                    if (Main.tile[i, j].slope() == 4 && Position.Y + Math.Abs(Velocity.X) >= vector3.Y && Position.X + (float)Width <= vector3.X + 16f)
                    {
                        flag2 = true;
                    }
                }
                else if (Main.tile[i, j].slope() > 0)
                {
                    flag = true;
                    if (Main.tile[i, j].slope() == 1 && Position.Y + (float)Height - Math.Abs(Velocity.X) <= vector3.Y + (float)num6 && Position.X >= vector3.X)
                    {
                        flag2 = true;
                    }
                    if (Main.tile[i, j].slope() == 2 && Position.Y + (float)Height - Math.Abs(Velocity.X) <= vector3.Y + (float)num6 && Position.X + (float)Width <= vector3.X + 16f)
                    {
                        flag2 = true;
                    }
                }
                if (flag2)
                {
                    continue;
                }
                if (Position.Y + (float)Height <= vector3.Y)
                {
                    down = true;
                    if ((!(Main.tileSolidTop[Main.tile[i, j].type] && fallThrough) || !(Velocity.Y <= 1f || fall2)) && num5 > vector3.Y)
                    {
                        num3 = i;
                        num4 = j;
                        if (num6 < 16)
{
                            num4++;
                        }
                        if (num3 != num && !flag)
{
                            result.Y = vector3.Y - (Position.Y + (float)Height) + ((gravDir == -1) ? (-0.01f) : 0f);
                            num5 = vector3.Y;
                        }
                    }
                }
                else if (Position.X + (float)Width <= vector3.X && !Main.tileSolidTop[Main.tile[i, j].type])
                {
                    if (i >= 1 && Main.tile[i - 1, j] == null)
                    {
                        Main.tile[i - 1, j] = default(Tile);
                    }
                    if (i < 1 || (Main.tile[i - 1, j].slope() != 2 && Main.tile[i - 1, j].slope() != 4))
                    {
                        num = i;
                        num2 = j;
                        if (num2 != num4)
{
                            result.X = vector3.X - (Position.X + (float)Width);
                        }
                        if (num3 == num)
{
                            result.Y = Velocity.Y;
                        }
                    }
                }
                else if (Position.X >= vector3.X + 16f && !Main.tileSolidTop[Main.tile[i, j].type])
                {
                    if (Main.tile[i + 1, j] == null)
                    {
                        Main.tile[i + 1, j] = default(Tile);
                    }
                    if (Main.tile[i + 1, j].slope() != 1 && Main.tile[i + 1, j].slope() != 3)
                    {
                        num = i;
                        num2 = j;
                        if (num2 != num4)
{
                            result.X = vector3.X + 16f - Position.X;
                        }
                        if (num3 == num)
{
                            result.Y = Velocity.Y;
                        }
                    }
                }
                else if (Position.Y >= vector3.Y + (float)num6 && !Main.tileSolidTop[Main.tile[i, j].type])
                {
                    up = true;
                    num3 = i;
                    num4 = j;
                    result.Y = vector3.Y + (float)num6 - Position.Y + ((gravDir == 1) ? 0.01f : 0f);
                    if (num4 == num2)
                    {
                        result.X = Velocity.X;
                    }
                }
            }
        }
        return result;
    }
References Terraria.Collision.down, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Collision.up.
Referenced by Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_195_JimsDrone(), Terraria.Player.CanSnapToPosition(), Terraria.Player.CheckForGoodTeleportationSpot(), Terraria.NPC.Collision_MoveNormal(), Terraria.NPC.Collision_MoveSolarSroller(), Terraria.NPC.Collision_MoveStardustCell(), Terraria.Player.DoQueenSlimeHookTeleport(), Terraria.Player.DryCollision(), Terraria.Collision.FindCollisionDirection(), Terraria.Collision.FindCollisionTile(), Terraria.Gore.Gore_UpdateLeaf(), Terraria.Gore.Gore_UpdateSail(), Terraria.Projectile.HandleMovement(), Terraria.Player.HoneyCollision(), Terraria.Mount.Hover(), Terraria.Collision.IsClearSpotTest(), Terraria.GameContent.TeleportHelpers.IsInSolidTilesExtended(), Terraria.Item.MoveInWorld(), Terraria.Player.ShimmerCollision(), Terraria.Collision.SlopeCollision(), Terraria.Collision.StepConveyorBelt(), Terraria.Mount.TryBeginningFlight(), Terraria.GameContent.PortalHelper.TryGoingThroughPortals(), Terraria.Mount.TryLanding(), Terraria.Gore.Update(), and Terraria.Player.WaterCollision().