TModLoader: Terraria.Collision.DrownCollision
DrownCollision()
static bool Terraria.Collision.DrownCollision (Vector2 Position, int Width, int Height, float gravDir = -1f, bool includeSlopes = false) inline static
Definition at line 1444 of file Collision.cs.
    {
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_020d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_023d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0243: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(Position.X + (float)(Width / 2), Position.Y + (float)(Height / 2));
        int num = 10;
        int num2 = 12;
        if (num > Width)
        {
            num = Width;
        }
        if (num2 > Height)
        {
            num2 = Height;
        }
        ((Vector2)(ref vector))._002Ector(vector.X - (float)(num / 2), Position.Y + -2f);
        if (gravDir == -1f)
        {
            vector.Y += Height / 2 - 6;
        }
        int value5 = (int)(Position.X / 16f) - 1;
        int value2 = (int)((Position.X + (float)Width) / 16f) + 2;
        int value3 = (int)(Position.Y / 16f) - 1;
        int value4 = (int)((Position.Y + (float)Height) / 16f) + 2;
        int num6 = Utils.Clamp(value5, 0, Main.maxTilesX - 1);
        value2 = Utils.Clamp(value2, 0, Main.maxTilesX - 1);
        value3 = Utils.Clamp(value3, 0, Main.maxTilesY - 1);
        value4 = Utils.Clamp(value4, 0, Main.maxTilesY - 1);
        int num3 = ((gravDir == 1f) ? value3 : (value4 - 1));
        Vector2 vector2 = default(Vector2);
        for (int i = num6; i < value2; i++)
        {
            for (int j = value3; j < value4; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile != null && tile.liquid > 0 && !tile.lava() && !tile.shimmer() && (j != num3 || !tile.active() || !Main.tileSolid[tile.type] || Main.tileSolidTop[tile.type] || (includeSlopes && tile.blockType() != 0)))
                {
                    vector2.X = i * 16;
                    vector2.Y = j * 16;
                    int num4 = 16;
                    float num5 = 256 - Main.tile[i, j].liquid;
                    num5 /= 32f;
                    vector2.Y += num5 * 2f;
                    num4 -= (int)(num5 * 2f);
                    if (vector.X + (float)num > vector2.X && vector.X < vector2.X + 16f && vector.Y + (float)num2 > vector2.Y && vector.Y < vector2.Y + (float)num4)
                    {
                        return true;
                    }
                }
            }
        }
        return false;
    }
References Terraria.Tile.active(), Terraria.Tile.blockType(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.shimmer(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_007_TownEntities_GetWalkPrediction(), Terraria.NPC.CheckDrowning(), and Terraria.Player.CheckDrowning().