TModLoader: Terraria.Collision.SolidCollision
SolidCollision() [2/2]
static bool Terraria.Collision.SolidCollision (Vector2 Position, int Width, int Height, bool acceptTopSurfaces) inline static
Definition at line 3125 of file Collision.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0164: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        int value5 = (int)(Position.X / 16f) - 1;
        int value2 = (int)((Position.X + (float)Width) / 16f) + 2;
        int value3 = (int)(Position.Y / 16f) - 1;
        int value4 = (int)((Position.Y + (float)Height) / 16f) + 2;
        int num3 = Utils.Clamp(value5, 0, Main.maxTilesX - 1);
        value2 = Utils.Clamp(value2, 0, Main.maxTilesX - 1);
        value3 = Utils.Clamp(value3, 0, Main.maxTilesY - 1);
        value4 = Utils.Clamp(value4, 0, Main.maxTilesY - 1);
        Vector2 vector = default(Vector2);
        for (int i = num3; i < value2; i++)
        {
            for (int j = value3; j < value4; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile == null || !tile.active() || tile.inActive())
                {
                    continue;
                }
                bool flag = Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type];
                if (acceptTopSurfaces)
                {
                    flag |= Main.tileSolidTop[tile.type] && tile.frameY == 0;
                }
                if (flag)
                {
                    vector.X = i * 16;
                    vector.Y = j * 16;
                    int num2 = 16;
                    if (tile.halfBrick())
                    {
                        vector.Y += 8f;
                        num2 -= 8;
                    }
                    if (Position.X + (float)Width > vector.X && Position.X < vector.X + 16f && Position.Y + (float)Height > vector.Y && Position.Y < vector.Y + (float)num2)
                    {
                        return true;
                    }
                }
            }
        }
        return false;
    }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.