TModLoader: Terraria.Collision.SolidCollision
SolidCollision() [1/2]
static bool Terraria.Collision.SolidCollision (Vector2 Position, int Width, int Height) inline static
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_019f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        int value5 = (int)(Position.X / 16f) - 1;
        int value2 = (int)((Position.X + (float)Width) / 16f) + 2;
        int value3 = (int)(Position.Y / 16f) - 1;
        int value4 = (int)((Position.Y + (float)Height) / 16f) + 2;
        int num3 = Utils.Clamp(value5, 0, Main.maxTilesX - 1);
        value2 = Utils.Clamp(value2, 0, Main.maxTilesX - 1);
        value3 = Utils.Clamp(value3, 0, Main.maxTilesY - 1);
        value4 = Utils.Clamp(value4, 0, Main.maxTilesY - 1);
        Vector2 vector = default(Vector2);
        for (int i = num3; i < value2; i++)
        {
            for (int j = value3; j < value4; j++)
            {
                if (Main.tile[i, j] != null && !Main.tile[i, j].inActive() && Main.tile[i, j].active() && Main.tileSolid[Main.tile[i, j].type] && !Main.tileSolidTop[Main.tile[i, j].type])
                {
                    vector.X = i * 16;
                    vector.Y = j * 16;
                    int num2 = 16;
                    if (Main.tile[i, j].halfBrick())
                    {
                        vector.Y += 8f;
                        num2 -= 8;
                    }
                    if (Position.X + (float)Width > vector.X && Position.X < vector.X + 16f && Position.Y + (float)Height > vector.Y && Position.Y < vector.Y + (float)num2)
                    {
                        return true;
                    }
                }
            }
        }
        return false;
    }
References Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Main.tileSolidTop.
Referenced by Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_002_FloatingEye(), Terraria.NPC.AI_003_Fighters(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_062(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_067_TigerSpecialAttack(), Terraria.NPC.AI_069_DukeFishron(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_123_Deerclops_Movement(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_158_BabyBird(), Terraria.Player.CanMoveForwardOnRope(), Terraria.Player.CanSnapToPosition(), Terraria.Player.ChangeDir(), Terraria.Player.CheckForGoodTeleportationSpot(), Terraria.Player.FindPulley(), Terraria.Player.GrappleMovement(), Terraria.GameContent.TeleportHelpers.IsInSolidTilesExtended(), Terraria.GameContent.ShimmerHelper.IsSpotShimmerFree(), Terraria.Player.ItemCheck_UseTeleportRod(), Terraria.Player.SporeSac(), Terraria.Gore.Update(), Terraria.Rain.Update(), Terraria.Player.Update(), Terraria.Dust.UpdateDust(), Terraria.WorldGen.UpdateWorld_Inner(), and Terraria.NPC.VanillaAI_Inner().