TModLoader: Terraria.Collision.CheckAABBvAABBCollision
CheckAABBvAABBCollision()
static bool Terraria.Collision.CheckAABBvAABBCollision (Vector2 position1, Vector2 dimensions1, Vector2 position2, Vector2 dimensions2) inline static
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        if (position1.X < position2.X + dimensions2.X && position1.Y < position2.Y + dimensions2.Y && position1.X + dimensions1.X > position2.X)
        {
            return position1.Y + dimensions1.Y > position2.Y;
        }
        return false;
    }
Referenced by Terraria.Collision.CheckAABBvLineCollision(), Terraria.GameContent.UI.Elements.UIList.UIInnerList.DrawChildren(), Terraria.ModLoader.UI.Elements.UIGrid.UIInnerList.DrawChildren(), Terraria.Main.DrawPageIcons(), and Terraria.GameContent.Shaders.WaterShaderData.DrawWaves().