TModLoader: Terraria.Collision.HurtTiles
HurtTiles()
static HurtTile Terraria.Collision.HurtTiles (Vector2 Position, int Width, int Height, Player player) inline static
Definition at line 3596 of file Collision.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        int num = (int)(Position.X / 16f) - 1;
        int num2 = (int)((Position.X + (float)Width) / 16f) + 2;
        int num3 = (int)(Position.Y / 16f) - 1;
        int num4 = (int)((Position.Y + (float)Height) / 16f) + 2;
        if (num < 0)
        {
            num = 0;
        }
        if (num2 > Main.maxTilesX)
        {
            num2 = Main.maxTilesX;
        }
        if (num3 < 0)
        {
            num3 = 0;
        }
        if (num4 > Main.maxTilesY)
        {
            num4 = Main.maxTilesY;
        }
        Vector2 vector = default(Vector2);
        HurtTile result;
        for (int i = num; i < num2; i++)
        {
            for (int j = num3; j < num4; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile == null || tile.inActive() || !tile.active())
                {
                    continue;
                }
                vector.X = i * 16;
                vector.Y = j * 16;
                int num5 = 16;
                if (tile.halfBrick())
                {
                    vector.Y += 8f;
                    num5 -= 8;
                }
                int num6 = 0;
                if (TileID.Sets.Suffocate[tile.type])
                {
                    num6 = 2;
                }
                if (Position.X + (float)Width - (float)num6 < vector.X || Position.X + (float)num6 > vector.X + 16f || Position.Y + (float)Height - (float)num6 < vector.Y - 0.5f || Position.Y + (float)num6 > vector.Y + (float)num5 + 0.5f || !CanTileHurt(tile.type, i, j, player))
                {
                    continue;
                }
                if (tile.slope() > 0)
                {
                    if (num6 > 0)
                    {
                        continue;
                    }
                    int num7 = 0;
                    if (tile.rightSlope() && Position.X > vector.X)
                    {
                        num7++;
                    }
                    if (tile.leftSlope() && Position.X + (float)Width < vector.X + 16f)
                    {
                        num7++;
                    }
                    if (tile.bottomSlope() && Position.Y > vector.Y)
                    {
                        num7++;
                    }
                    if (tile.topSlope() && Position.Y + (float)Height < vector.Y + (float)num5)
                    {
                        num7++;
                    }
                    if (num7 == 2)
                    {
                        continue;
                    }
                }
                result = default(HurtTile);
                result.type = tile.type;
                result.x = i;
                result.y = j;
                return result;
            }
        }
        result = default(HurtTile);
        result.type = -1;
        return result;
    }
References Terraria.Tile.active(), Terraria.Tile.bottomSlope(), Terraria.Collision.CanTileHurt(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.Tile.leftSlope(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.rightSlope(), Terraria.Tile.slope(), Terraria.ID.TileID.Sets.Suffocate, Terraria.Main.tile, Terraria.Tile.topSlope(), and Terraria.Tile.type.
Referenced by Terraria.Collision.AnyHurtingTiles(), and Terraria.Player.GetHurtTile().