TModLoader: Terraria.Collision.SwitchTiles
SwitchTiles()
static bool Terraria.Collision.SwitchTiles (Vector2 Position, int Width, int Height, Vector2 oldPosition, int objType) inline static
Definition at line 3728 of file Collision.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0287: Unknown result type (might be due to invalid IL or missing references)
        //IL_0293: Unknown result type (might be due to invalid IL or missing references)
        //IL_0299: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0217: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0236: Unknown result type (might be due to invalid IL or missing references)
        //IL_023c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0308: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_031d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0326: Unknown result type (might be due to invalid IL or missing references)
        //IL_032f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0336: Unknown result type (might be due to invalid IL or missing references)
        int num = (int)(Position.X / 16f) - 1;
        int num2 = (int)((Position.X + (float)Width) / 16f) + 2;
        int num3 = (int)(Position.Y / 16f) - 1;
        int num4 = (int)((Position.Y + (float)Height) / 16f) + 2;
        if (num < 0)
        {
            num = 0;
        }
        if (num2 > Main.maxTilesX)
        {
            num2 = Main.maxTilesX;
        }
        if (num3 < 0)
        {
            num3 = 0;
        }
        if (num4 > Main.maxTilesY)
        {
            num4 = Main.maxTilesY;
        }
        Vector2 vector = default(Vector2);
        for (int i = num; i < num2; i++)
        {
            for (int j = num3; j < num4; j++)
            {
                if (Main.tile[i, j] == null)
                {
                    continue;
                }
                int type = Main.tile[i, j].type;
                if (!Main.tile[i, j].active() || (type != 135 && type != 210 && type != 443 && type != 442))
                {
                    continue;
                }
                vector.X = i * 16;
                vector.Y = j * 16 + 12;
                bool flag = false;
                if (type == 442)
                {
                    if (objType == 4)
                    {
                        float r1StartX = 0f;
                        float r1StartY = 0f;
                        float r1Width = 0f;
                        float r1Height = 0f;
                        switch (Main.tile[i, j].frameX / 22)
{
                        case 0:
                            r1StartX = i * 16;
                            r1StartY = j * 16 + 16 - 10;
                            r1Width = 16f;
                            r1Height = 10f;
                            break;
                        case 1:
                            r1StartX = i * 16;
                            r1StartY = j * 16;
                            r1Width = 16f;
                            r1Height = 10f;
                            break;
                        case 2:
                            r1StartX = i * 16;
                            r1StartY = j * 16;
                            r1Width = 10f;
                            r1Height = 16f;
                            break;
                        case 3:
                            r1StartX = i * 16 + 16 - 10;
                            r1StartY = j * 16;
                            r1Width = 10f;
                            r1Height = 16f;
                            break;
                        }
                        if (Utils.FloatIntersect(r1StartX, r1StartY, r1Width, r1Height, Position.X, Position.Y, Width, Height) && !Utils.FloatIntersect(r1StartX, r1StartY, r1Width, r1Height, oldPosition.X, oldPosition.Y, Width, Height))
{
                            Wiring.HitSwitch(i, j);
                            NetMessage.SendData(59, -1, -1, null, i, j);
                            return true;
                        }
                    }
                    flag = true;
                }
                if (flag || !(Position.X + (float)Width > vector.X) || !(Position.X < vector.X + 16f) || !(Position.Y + (float)Height > vector.Y) || !((double)Position.Y < (double)vector.Y + 4.01))
                {
                    continue;
                }
                if (type == 210)
                {
                    WorldGen.ExplodeMine(i, j, fromWiring: false);
                }
                else
                {
                    if (oldPosition.X + (float)Width > vector.X && oldPosition.X < vector.X + 16f && oldPosition.Y + (float)Height > vector.Y && (double)oldPosition.Y < (double)vector.Y + 16.01)
                    {
                        continue;
                    }
                    if (type == 443)
                    {
                        if (objType == 1)
{
                            Wiring.HitSwitch(i, j);
                            NetMessage.SendData(59, -1, -1, null, i, j);
                        }
                        continue;
                    }
                    int num5 = Main.tile[i, j].frameY / 18;
                    bool flag2 = true;
                    if ((num5 == 4 || num5 == 2 || num5 == 3 || num5 == 6 || num5 == 7) && objType != 1)
                    {
                        flag2 = false;
                    }
                    if (num5 == 5 && (objType == 1 || objType == 4))
                    {
                        flag2 = false;
                    }
                    if (!flag2)
                    {
                        continue;
                    }
                    Wiring.HitSwitch(i, j);
                    NetMessage.SendData(59, -1, -1, null, i, j);
                    if (num5 == 7)
                    {
                        WorldGen.KillTile(i, j);
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(17, -1, -1, null, 0, i, j);
                        }
                    }
                    return true;
                }
            }
        }
        return false;
    }
References Terraria.WorldGen.ExplodeMine(), Terraria.Utils.FloatIntersect(), Terraria.Wiring.HitSwitch(), Terraria.WorldGen.KillTile(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.NetMessage.SendData(), and Terraria.Main.tile.
Referenced by Terraria.Projectile.AI_149_GolfBall(), Terraria.Projectile.HandleMovement(), Terraria.Player.Update(), Terraria.Projectile.Update(), and Terraria.NPC.UpdateNPC_Inner().