TModLoader: Terraria.Collision.HitTiles
HitTiles()
static void Terraria.Collision.HitTiles (Vector2 Position, Vector2 Velocity, int Width, int Height) inline static
Definition at line 3526 of file Collision.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0198: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = Position + Velocity;
        int num = (int)(Position.X / 16f) - 1;
        int num2 = (int)((Position.X + (float)Width) / 16f) + 2;
        int num3 = (int)(Position.Y / 16f) - 1;
        int num4 = (int)((Position.Y + (float)Height) / 16f) + 2;
        if (num < 0)
        {
            num = 0;
        }
        if (num2 > Main.maxTilesX)
        {
            num2 = Main.maxTilesX;
        }
        if (num3 < 0)
        {
            num3 = 0;
        }
        if (num4 > Main.maxTilesY)
        {
            num4 = Main.maxTilesY;
        }
        Vector2 vector2 = default(Vector2);
        for (int i = num; i < num2; i++)
        {
            for (int j = num3; j < num4; j++)
            {
                if (Main.tile[i, j] != null && !Main.tile[i, j].inActive() && Main.tile[i, j].active() && (Main.tileSolid[Main.tile[i, j].type] || (Main.tileSolidTop[Main.tile[i, j].type] && Main.tile[i, j].frameY == 0)))
                {
                    vector2.X = i * 16;
                    vector2.Y = j * 16;
                    int num5 = 16;
                    if (Main.tile[i, j].halfBrick())
                    {
                        vector2.Y += 8f;
                        num5 -= 8;
                    }
                    if (vector.X + (float)Width >= vector2.X && vector.X <= vector2.X + 16f && vector.Y + (float)Height >= vector2.Y && vector.Y <= vector2.Y + (float)num5)
                    {
                        WorldGen.KillTile(i, j, fail: true, effectOnly: true);
                    }
                }
            }
        }
    }
References Terraria.WorldGen.KillTile(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Main.tileSolidTop.
Referenced by Terraria.Projectile.AI_015_HandleMovementCollision(), Terraria.Projectile.AI_015_HandleMovementCollision_Old(), Terraria.Projectile.HandleMovement(), and Terraria.Projectile.Kill().