TModLoader: Terraria.Collision.AnyCollisionWithSpecificTiles
AnyCollisionWithSpecificTiles()
static Vector2 Terraria.Collision.AnyCollisionWithSpecificTiles (Vector2 Position, Vector2 Velocity, int Width, int Height, bool[] tilesWeCanCollideWithByType, bool evenActuated = false) inline static
Definition at line 3241 of file Collision.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_0003: Unknown result type (might be due to invalid IL or missing references)
        //IL_0004: Unknown result type (might be due to invalid IL or missing references)
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        //IL_0313: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0176: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_022f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0292: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0264: Unknown result type (might be due to invalid IL or missing references)
        //IL_0271: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        Vector2 result = Velocity;
        Vector2 vector2 = Position + Velocity;
        int num = (int)(Position.X / 16f) - 1;
        int num2 = (int)((Position.X + (float)Width) / 16f) + 2;
        int num3 = (int)(Position.Y / 16f) - 1;
        int num4 = (int)((Position.Y + (float)Height) / 16f) + 2;
        int num5 = -1;
        int num6 = -1;
        int num7 = -1;
        int num8 = -1;
        if (num < 0)
        {
            num = 0;
        }
        if (num2 > Main.maxTilesX)
        {
            num2 = Main.maxTilesX;
        }
        if (num3 < 0)
        {
            num3 = 0;
        }
        if (num4 > Main.maxTilesY)
        {
            num4 = Main.maxTilesY;
        }
        Vector2 vector3 = default(Vector2);
        for (int i = num; i < num2; i++)
        {
            for (int j = num3; j < num4; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile == null || !tile.active() || (!evenActuated && tile.inActive()) || !tilesWeCanCollideWithByType[tile.type])
                {
                    continue;
                }
                vector3.X = i * 16;
                vector3.Y = j * 16;
                int num9 = 16;
                if (tile.halfBrick())
                {
                    vector3.Y += 8f;
                    num9 -= 8;
                }
                if (!(vector2.X + (float)Width > vector3.X) || !(vector2.X < vector3.X + 16f) || !(vector2.Y + (float)Height > vector3.Y) || !(vector2.Y < vector3.Y + (float)num9))
                {
                    continue;
                }
                if (Position.Y + (float)Height <= vector3.Y)
                {
                    num7 = i;
                    num8 = j;
                    if (num7 != num5)
                    {
                        result.Y = vector3.Y - (Position.Y + (float)Height);
                    }
                }
                else if (Position.X + (float)Width <= vector3.X && !Main.tileSolidTop[tile.type])
                {
                    num5 = i;
                    num6 = j;
                    if (num6 != num8)
                    {
                        result.X = vector3.X - (Position.X + (float)Width);
                    }
                    if (num7 == num5)
                    {
                        result.Y = Velocity.Y;
                    }
                }
                else if (Position.X >= vector3.X + 16f && !Main.tileSolidTop[tile.type])
                {
                    num5 = i;
                    num6 = j;
                    if (num6 != num8)
                    {
                        result.X = vector3.X + 16f - Position.X;
                    }
                    if (num7 == num5)
                    {
                        result.Y = Velocity.Y;
                    }
                }
                else if (Position.Y >= vector3.Y + (float)num9 && !Main.tileSolidTop[tile.type])
                {
                    num7 = i;
                    num8 = j;
                    result.Y = vector3.Y + (float)num9 - Position.Y + 0.01f;
                    if (num8 == num6)
                    {
                        result.X = Velocity.X + 0.01f;
                    }
                }
            }
        }
        return result;
    }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.Projectile.HandleMovement().