TModLoader: Terraria.Collision.StepConveyorBelt
StepConveyorBelt()
static void Terraria.Collision.StepConveyorBelt (Entity entity, float gravDir) inline static
    {
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_046d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0472: Unknown result type (might be due to invalid IL or missing references)
        //IL_047c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0481: Unknown result type (might be due to invalid IL or missing references)
        //IL_0484: Unknown result type (might be due to invalid IL or missing references)
        //IL_0489: Unknown result type (might be due to invalid IL or missing references)
        //IL_049b: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_022c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0242: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02de: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0371: Unknown result type (might be due to invalid IL or missing references)
        //IL_0376: Unknown result type (might be due to invalid IL or missing references)
        //IL_0378: Unknown result type (might be due to invalid IL or missing references)
        //IL_037e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0383: Unknown result type (might be due to invalid IL or missing references)
        //IL_038a: Unknown result type (might be due to invalid IL or missing references)
        //IL_038f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0394: Unknown result type (might be due to invalid IL or missing references)
        //IL_0396: Unknown result type (might be due to invalid IL or missing references)
        //IL_0322: Unknown result type (might be due to invalid IL or missing references)
        //IL_0300: Unknown result type (might be due to invalid IL or missing references)
        //IL_0340: Unknown result type (might be due to invalid IL or missing references)
        Player player = null;
        if (entity is Player)
        {
            player = (Player)entity;
            if (Math.Abs(player.gfxOffY) > 2f || player.grapCount > 0 || player.pulley)
            {
                return;
            }
            entity.height -= 5;
            entity.position.Y += 5f;
        }
        int num = 0;
        int num2 = 0;
        bool flag = false;
        int num3 = (int)entity.position.Y + entity.height;
        Rectangle hitbox = entity.Hitbox;
        ((Rectangle)(ref hitbox)).Inflate(2, 2);
        _ = entity.TopLeft;
        _ = entity.TopRight;
        _ = entity.BottomLeft;
        _ = entity.BottomRight;
        List<Point> cacheForConveyorBelts = _cacheForConveyorBelts;
        cacheForConveyorBelts.Clear();
        GetEntityEdgeTiles(cacheForConveyorBelts, entity, left: false, right: false);
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(0.0001f);
        Vector2 lineStart = default(Vector2);
        Vector2 lineStart2 = default(Vector2);
        Vector2 lineEnd = default(Vector2);
        Vector2 lineEnd2 = default(Vector2);
        for (int i = 0; i < cacheForConveyorBelts.Count; i++)
        {
            Point point = cacheForConveyorBelts[i];
            if (!WorldGen.InWorld(point.X, point.Y) || (player != null && player.onTrack && point.Y < num3))
            {
                continue;
            }
            Tile tile = Main.tile[point.X, point.Y];
            if (tile == null || !tile.active() || !tile.nactive())
            {
                continue;
            }
            int num4 = TileID.Sets.ConveyorDirection[tile.type];
            if (num4 == 0)
            {
                continue;
            }
            lineStart.X = (lineStart2.X = point.X * 16);
            lineEnd.X = (lineEnd2.X = point.X * 16 + 16);
            switch (tile.slope())
            {
            case 1:
                lineStart2.Y = point.Y * 16;
                lineEnd2.Y = (lineEnd.Y = (lineStart.Y = point.Y * 16 + 16));
                break;
            case 2:
                lineEnd2.Y = point.Y * 16;
                lineStart2.Y = (lineEnd.Y = (lineStart.Y = point.Y * 16 + 16));
                break;
            case 3:
                lineEnd.Y = (lineStart2.Y = (lineEnd2.Y = point.Y * 16));
                lineStart.Y = point.Y * 16 + 16;
                break;
            case 4:
                lineStart.Y = (lineStart2.Y = (lineEnd2.Y = point.Y * 16));
                lineEnd.Y = point.Y * 16 + 16;
                break;
            default:
                if (tile.halfBrick())
                {
                    lineStart2.Y = (lineEnd2.Y = point.Y * 16 + 8);
                }
                else
                {
                    lineStart2.Y = (lineEnd2.Y = point.Y * 16);
                }
                lineStart.Y = (lineEnd.Y = point.Y * 16 + 16);
                break;
            }
            int num5 = 0;
            if (!TileID.Sets.Platforms[tile.type] && CheckAABBvLineCollision2(entity.position - vector, entity.Size + vector * 2f, lineStart, lineEnd))
            {
                num5--;
            }
            if (CheckAABBvLineCollision2(entity.position - vector, entity.Size + vector * 2f, lineStart2, lineEnd2))
            {
                num5++;
            }
            if (num5 != 0)
            {
                flag = true;
                num += num4 * num5 * (int)gravDir;
                if (tile.leftSlope())
                {
                    num2 += (int)gravDir * -num4;
                }
                if (tile.rightSlope())
                {
                    num2 -= (int)gravDir * -num4;
                }
            }
        }
        if (entity is Player)
        {
            entity.height += 5;
            entity.position.Y -= 5f;
        }
        if (flag && num != 0)
        {
            num = Math.Sign(num);
            num2 = Math.Sign(num2);
            Vector2 velocity = Vector2.Normalize(new Vector2((float)num * gravDir, (float)num2)) * 2.5f;
            Vector2 vector2 = TileCollision(entity.position, velocity, entity.width, entity.height, fallThrough: false, fall2: false, (int)gravDir);
            entity.position += vector2;
            Vector2 velocity2 = default(Vector2);
            ((Vector2)(ref velocity2))._002Ector(0f, 2.5f * gravDir);
            vector2 = TileCollision(entity.position, velocity2, entity.width, entity.height, fallThrough: false, fall2: false, (int)gravDir);
            entity.position += vector2;
        }
    }
References Terraria.Collision._cacheForConveyorBelts, Terraria.Tile.active(), Terraria.Entity.BottomLeft, Terraria.Entity.BottomRight, Terraria.Collision.CheckAABBvLineCollision2(), Terraria.ID.TileID.Sets.ConveyorDirection, Terraria.Collision.GetEntityEdgeTiles(), Terraria.Player.gfxOffY, Terraria.Tile.halfBrick(), Terraria.Entity.height, Terraria.Entity.Hitbox, Terraria.WorldGen.InWorld(), Terraria.Tile.leftSlope(), Terraria.Tile.nactive(), Terraria.ID.TileID.Sets.Platforms, Terraria.Entity.position, Terraria.Player.pulley, Terraria.Tile.rightSlope(), Terraria.Entity.Size, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Collision.TileCollision(), Terraria.Entity.TopLeft, Terraria.Entity.TopRight, Terraria.Tile.type, and Terraria.Entity.width.
Referenced by Terraria.Player.DryCollision(), Terraria.Item.MoveInWorld(), Terraria.Player.Update(), and Terraria.NPC.UpdateCollision().