TModLoader: Terraria.Collision.GetTilesIn
GetTilesIn()
static List< Point > Terraria.Collision.GetTilesIn (Vector2 TopLeft, Vector2 BottomRight) inline static
Definition at line 4704 of file Collision.cs.
    {
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        List<Point> list = new List<Point>();
        Point val = TopLeft.ToTileCoordinates();
        Point point2 = BottomRight.ToTileCoordinates();
        int num = Utils.Clamp(val.X, 0, Main.maxTilesX - 1);
        int num2 = Utils.Clamp(val.Y, 0, Main.maxTilesY - 1);
        int num3 = Utils.Clamp(point2.X, 0, Main.maxTilesX - 1);
        int num4 = Utils.Clamp(point2.Y, 0, Main.maxTilesY - 1);
        for (int i = num; i <= num3; i++)
        {
            for (int j = num2; j <= num4; j++)
            {
                if (Main.tile[i, j] != null)
                {
                    list.Add(new Point(i, j));
                }
            }
        }
        return list;
    }
References Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, and Terraria.Main.tile.
Referenced by Terraria.Player.QuickMinecart(), Terraria.Player.QuickMinecartSnap(), Terraria.GameContent.Drawing.WindGrid.ScanPlayer(), and Terraria.GameContent.PressurePlateHelper.UpdatePlayerPosition().