TModLoader: Terraria.Collision.LavaCollision
LavaCollision()
static bool Terraria.Collision.LavaCollision (Vector2 Position, int Width, int Height) inline static
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0164: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_0181: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        int value5 = (int)(Position.X / 16f) - 1;
        int value2 = (int)((Position.X + (float)Width) / 16f) + 2;
        int value3 = (int)(Position.Y / 16f) - 1;
        int value4 = (int)((Position.Y + (float)Height) / 16f) + 2;
        int num4 = Utils.Clamp(value5, 0, Main.maxTilesX - 1);
        value2 = Utils.Clamp(value2, 0, Main.maxTilesX - 1);
        value3 = Utils.Clamp(value3, 0, Main.maxTilesY - 1);
        value4 = Utils.Clamp(value4, 0, Main.maxTilesY - 1);
        Vector2 vector = default(Vector2);
        for (int i = num4; i < value2; i++)
        {
            for (int j = value3; j < value4; j++)
            {
                if (Main.tile[i, j] != null && Main.tile[i, j].liquid > 0 && Main.tile[i, j].lava())
                {
                    vector.X = i * 16;
                    vector.Y = j * 16;
                    int num2 = 16;
                    float num3 = 256 - Main.tile[i, j].liquid;
                    num3 /= 32f;
                    vector.Y += num3 * 2f;
                    num2 -= (int)(num3 * 2f);
                    if (Position.X + (float)Width > vector.X && Position.X < vector.X + 16f && Position.Y + (float)Height > vector.Y && Position.Y < vector.Y + (float)num2)
                    {
                        return true;
                    }
                }
            }
        }
        return false;
    }
References Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, and Terraria.Main.tile.
Referenced by Terraria.Projectile.AI_152_SuperStarSlash(), Terraria.Player.CheckForGoodTeleportationSpot(), Terraria.NPC.Collision_LavaCollision(), Terraria.NPC.DoDeathEvents(), Terraria.GameContent.Shaders.WaterShaderData.DrawWaves(), Terraria.GameContent.TeleportHelpers.IsInSolidTilesExtended(), Terraria.Item.MoveInWorld(), Terraria.Player.Update(), and Terraria.Projectile.Update().