TModLoader: Terraria.Collision.SlopeCollision
SlopeCollision()
static Vector4 Terraria.Collision.SlopeCollision (Vector2 Position, Vector2 Velocity, int Width, int Height, float gravity = 0f, bool fall = false) inline static
Definition at line 1976 of file Collision.cs.
    {
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_06bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_06bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06be: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_06da: Unknown result type (might be due to invalid IL or missing references)
        //IL_0753: Unknown result type (might be due to invalid IL or missing references)
        //IL_075a: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07db: Unknown result type (might be due to invalid IL or missing references)
        //IL_0763: Unknown result type (might be due to invalid IL or missing references)
        //IL_076a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0776: Unknown result type (might be due to invalid IL or missing references)
        //IL_077c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0710: Unknown result type (might be due to invalid IL or missing references)
        //IL_0790: Unknown result type (might be due to invalid IL or missing references)
        //IL_0725: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        //IL_025b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0364: Unknown result type (might be due to invalid IL or missing references)
        //IL_036d: Unknown result type (might be due to invalid IL or missing references)
        //IL_026c: Unknown result type (might be due to invalid IL or missing references)
        //IL_027a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_037f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0391: Unknown result type (might be due to invalid IL or missing references)
        //IL_039a: Unknown result type (might be due to invalid IL or missing references)
        //IL_02af: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_048a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0490: Unknown result type (might be due to invalid IL or missing references)
        //IL_040e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0414: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0499: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0429: Unknown result type (might be due to invalid IL or missing references)
        //IL_0436: Unknown result type (might be due to invalid IL or missing references)
        //IL_0442: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_050a: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0453: Unknown result type (might be due to invalid IL or missing references)
        //IL_0461: Unknown result type (might be due to invalid IL or missing references)
        //IL_0469: Unknown result type (might be due to invalid IL or missing references)
        //IL_0522: Unknown result type (might be due to invalid IL or missing references)
        //IL_052b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0628: Unknown result type (might be due to invalid IL or missing references)
        //IL_0634: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0607: Unknown result type (might be due to invalid IL or missing references)
        //IL_0613: Unknown result type (might be due to invalid IL or missing references)
        //IL_053a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0541: Unknown result type (might be due to invalid IL or missing references)
        //IL_0550: Unknown result type (might be due to invalid IL or missing references)
        //IL_0682: Unknown result type (might be due to invalid IL or missing references)
        //IL_059e: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b4: Unknown result type (might be due to invalid IL or missing references)
        stair = false;
        stairFall = false;
        bool[] array = new bool[5];
        float y = Position.Y;
        float y2 = Position.Y;
        sloping = false;
        Vector2 vector2 = Position;
        Vector2 vector3 = Velocity;
        int value5 = (int)(Position.X / 16f) - 1;
        int value2 = (int)((Position.X + (float)Width) / 16f) + 2;
        int value3 = (int)(Position.Y / 16f) - 1;
        int value4 = (int)((Position.Y + (float)Height) / 16f) + 2;
        int num19 = Utils.Clamp(value5, 0, Main.maxTilesX - 1);
        value2 = Utils.Clamp(value2, 0, Main.maxTilesX - 1);
        value3 = Utils.Clamp(value3, 0, Main.maxTilesY - 1);
        value4 = Utils.Clamp(value4, 0, Main.maxTilesY - 1);
        Vector2 vector4 = default(Vector2);
        for (int i = num19; i < value2; i++)
        {
            for (int j = value3; j < value4; j++)
            {
                if (Main.tile[i, j] == null || !Main.tile[i, j].active() || Main.tile[i, j].inActive() || (!Main.tileSolid[Main.tile[i, j].type] && (!Main.tileSolidTop[Main.tile[i, j].type] || Main.tile[i, j].frameY != 0)))
                {
                    continue;
                }
                vector4.X = i * 16;
                vector4.Y = j * 16;
                int num11 = 16;
                if (Main.tile[i, j].halfBrick())
                {
                    vector4.Y += 8f;
                    num11 -= 8;
                }
                if (!(Position.X + (float)Width > vector4.X) || !(Position.X < vector4.X + 16f) || !(Position.Y + (float)Height > vector4.Y) || !(Position.Y < vector4.Y + (float)num11))
                {
                    continue;
                }
                bool flag = true;
                if (TileID.Sets.Platforms[Main.tile[i, j].type])
                {
                    if (Velocity.Y < 0f)
                    {
                        flag = false;
                    }
                    if (Position.Y + (float)Height < (float)(j * 16) || Position.Y + (float)Height - (1f + Math.Abs(Velocity.X)) > (float)(j * 16 + 16))
                    {
                        flag = false;
                    }
                    if (((Main.tile[i, j].slope() == 1 && Velocity.X >= 0f) || (Main.tile[i, j].slope() == 2 && Velocity.X <= 0f)) && (Position.Y + (float)Height) / 16f - 1f == (float)j)
                    {
                        flag = false;
                    }
                }
                if (!flag)
                {
                    continue;
                }
                bool flag2 = false;
                if (fall && TileID.Sets.Platforms[Main.tile[i, j].type])
                {
                    flag2 = true;
                }
                int num12 = Main.tile[i, j].slope();
                vector4.X = i * 16;
                vector4.Y = j * 16;
                if (!(Position.X + (float)Width > vector4.X) || !(Position.X < vector4.X + 16f) || !(Position.Y + (float)Height > vector4.Y) || !(Position.Y < vector4.Y + 16f))
                {
                    continue;
                }
                float num13 = 0f;
                if (num12 == 3 || num12 == 4)
                {
                    if (num12 == 3)
                    {
                        num13 = Position.X - vector4.X;
                    }
                    if (num12 == 4)
                    {
                        num13 = vector4.X + 16f - (Position.X + (float)Width);
                    }
                    if (num13 >= 0f)
                    {
                        if (Position.Y <= vector4.Y + 16f - num13)
{
                            float num14 = vector4.Y + 16f - Position.Y - num13;
                            if (Position.Y + num14 > y2)
{
                                vector2.Y = Position.Y + num14;
                                y2 = vector2.Y;
                                if (vector3.Y < 0.0101f)
{
                                    vector3.Y = 0.0101f;
                                }
                                array[num12] = true;
                            }
                        }
                    }
                    else if (Position.Y > vector4.Y)
                    {
                        float num15 = vector4.Y + 16f;
                        if (vector2.Y < num15)
{
                            vector2.Y = num15;
                            if (vector3.Y < 0.0101f)
{
                                vector3.Y = 0.0101f;
                            }
                        }
                    }
                }
                if (num12 != 1 && num12 != 2)
                {
                    continue;
                }
                if (num12 == 1)
                {
                    num13 = Position.X - vector4.X;
                }
                if (num12 == 2)
                {
                    num13 = vector4.X + 16f - (Position.X + (float)Width);
                }
                if (num13 >= 0f)
                {
                    if (!(Position.Y + (float)Height >= vector4.Y + num13))
                    {
                        continue;
                    }
                    float num16 = vector4.Y - (Position.Y + (float)Height) + num13;
                    if (!(Position.Y + num16 < y))
                    {
                        continue;
                    }
                    if (flag2)
                    {
                        stairFall = true;
                        continue;
                    }
                    if (TileID.Sets.Platforms[Main.tile[i, j].type])
                    {
                        stair = true;
                    }
                    else
                    {
                        stair = false;
                    }
                    vector2.Y = Position.Y + num16;
                    y = vector2.Y;
                    if (vector3.Y > 0f)
                    {
                        vector3.Y = 0f;
                    }
                    array[num12] = true;
                    continue;
                }
                if (TileID.Sets.Platforms[Main.tile[i, j].type] && !(Position.Y + (float)Height - 4f - Math.Abs(Velocity.X) <= vector4.Y))
                {
                    if (flag2)
                    {
                        stairFall = true;
                    }
                    continue;
                }
                float num17 = vector4.Y - (float)Height;
                if (!(vector2.Y > num17))
                {
                    continue;
                }
                if (flag2)
                {
                    stairFall = true;
                    continue;
                }
                if (TileID.Sets.Platforms[Main.tile[i, j].type])
                {
                    stair = true;
                }
                else
                {
                    stair = false;
                }
                vector2.Y = num17;
                if (vector3.Y > 0f)
                {
                    vector3.Y = 0f;
                }
            }
        }
        Vector2 velocity = vector2 - Position;
        Vector2 vector5 = TileCollision(Position, velocity, Width, Height);
        if (vector5.Y > velocity.Y)
        {
            float num18 = velocity.Y - vector5.Y;
            vector2.Y = Position.Y + vector5.Y;
            if (array[1])
            {
                vector2.X = Position.X - num18;
            }
            if (array[2])
            {
                vector2.X = Position.X + num18;
            }
            vector3.X = 0f;
            vector3.Y = 0f;
            up = false;
        }
        else if (vector5.Y < velocity.Y)
        {
            float num10 = vector5.Y - velocity.Y;
            vector2.Y = Position.Y + vector5.Y;
            if (array[3])
            {
                vector2.X = Position.X - num10;
            }
            if (array[4])
            {
                vector2.X = Position.X + num10;
            }
            vector3.X = 0f;
            vector3.Y = 0f;
        }
        return new Vector4(vector2, vector3.X, vector3.Y);
    }
References Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.ID.TileID.Sets.Platforms, Terraria.Collision.sloping, Terraria.Collision.stair, Terraria.Collision.stairFall, Terraria.Main.tile, Terraria.Collision.TileCollision(), Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Collision.up.
Referenced by Terraria.Player.CheckForGoodTeleportationSpot(), Terraria.NPC.Collision_MoveSlopesAndStairFall(), Terraria.NPC.Collision_MoveSnailOnSlopes(), Terraria.Collision.FindCollisionTile(), Terraria.Gore.Gore_UpdateLeaf(), Terraria.Projectile.HandleMovement(), Terraria.Collision.IsClearSpotTest(), Terraria.Item.MoveInWorld(), Terraria.Player.SlopingCollision(), Terraria.Gore.Update(), and Terraria.Projectile.UpdatePosition().