TModLoader: Terraria.Collision.IsClearSpotTest
IsClearSpotTest()
static bool Terraria.Collision.IsClearSpotTest (Vector2 position, float testMagnitude, int Width, int Height, bool fallThrough = false, bool fall2 = false, int gravDir = 1, bool checkCardinals = true, bool checkSlopes = false) inline static
    {
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00de: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        //IL_0198: Unknown result type (might be due to invalid IL or missing references)
        if (checkCardinals)
        {
            Vector2 vector2 = Vector2.UnitX * testMagnitude;
            if (TileCollision(position - vector2, vector2, Width, Height, fallThrough, fall2, gravDir) != vector2)
            {
                return false;
            }
            vector2 = -Vector2.UnitX * testMagnitude;
            if (TileCollision(position - vector2, vector2, Width, Height, fallThrough, fall2, gravDir) != vector2)
            {
                return false;
            }
            vector2 = Vector2.UnitY * testMagnitude;
            if (TileCollision(position - vector2, vector2, Width, Height, fallThrough, fall2, gravDir) != vector2)
            {
                return false;
            }
            vector2 = -Vector2.UnitY * testMagnitude;
            if (TileCollision(position - vector2, vector2, Width, Height, fallThrough, fall2, gravDir) != vector2)
            {
                return false;
            }
        }
        if (checkSlopes)
        {
            Vector2 vector = Vector2.UnitX * testMagnitude;
            Vector4 vector3 = default(Vector4);
            ((Vector4)(ref vector3))._002Ector(position, testMagnitude, 0f);
            if (SlopeCollision(position, vector, Width, Height, gravDir, fallThrough) != vector3)
            {
                return false;
            }
            vector = -Vector2.UnitX * testMagnitude;
            ((Vector4)(ref vector3))._002Ector(position, 0f - testMagnitude, 0f);
            if (SlopeCollision(position, vector, Width, Height, gravDir, fallThrough) != vector3)
            {
                return false;
            }
            vector = Vector2.UnitY * testMagnitude;
            ((Vector4)(ref vector3))._002Ector(position, 0f, testMagnitude);
            if (SlopeCollision(position, vector, Width, Height, gravDir, fallThrough) != vector3)
            {
                return false;
            }
            vector = -Vector2.UnitY * testMagnitude;
            ((Vector4)(ref vector3))._002Ector(position, 0f, 0f - testMagnitude);
            if (SlopeCollision(position, vector, Width, Height, gravDir, fallThrough) != vector3)
            {
                return false;
            }
        }
        return true;
    }
References Terraria.Collision.SlopeCollision(), and Terraria.Collision.TileCollision().
Referenced by Terraria.Player.CanFitSpace(), and Terraria.Player.UpdateTouchingTiles().