TModLoader: Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.AddSearchBar
AddSearchBar()
void Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.AddSearchBar (UIElement searchArea) inline private
Definition at line 631 of file UICreativeInfiniteItemsDisplay.cs.
    {
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        UIImageButton uIImageButton = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Search"))
        {
            VAlign = 0.5f,
            HAlign = 0f
        };
        uIImageButton.OnLeftClick += Click_SearchArea;
        uIImageButton.SetHoverImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Search_Border"));
        uIImageButton.SetVisibility(1f, 1f);
        uIImageButton.SetSnapPoint("CreativeInfinitesSearch", 0);
        searchArea.Append(uIImageButton);
        UIPanel obj = new UIPanel
        {
            Width = new StyleDimension(0f - uIImageButton.Width.Pixels - 3f, 1f),
            Height = new StyleDimension(0f, 1f),
            VAlign = 0.5f,
            HAlign = 1f
        };
        UIPanel uIPanel2 = obj;
        _searchBoxPanel = obj;
        UIPanel uIPanel = uIPanel2;
        uIPanel.BackgroundColor = new Color(35, 40, 83);
        uIPanel.BorderColor = new Color(35, 40, 83);
        uIPanel.SetPadding(0f);
        searchArea.Append(uIPanel);
        UISearchBar obj2 = new UISearchBar(Language.GetText("UI.PlayerNameSlot"), 0.8f)
        {
            Width = new StyleDimension(0f, 1f),
            Height = new StyleDimension(0f, 1f),
            HAlign = 0f,
            VAlign = 0.5f,
            Left = new StyleDimension(0f, 0f),
            IgnoresMouseInteraction = true
        };
        UISearchBar uISearchBar2 = obj2;
        _searchBar = obj2;
        UISearchBar uISearchBar = uISearchBar2;
        uIPanel.OnLeftClick += Click_SearchArea;
        uISearchBar.OnContentsChanged += OnSearchContentsChanged;
        uIPanel.Append(uISearchBar);
        uISearchBar.OnStartTakingInput += OnStartTakingInput;
        uISearchBar.OnEndTakingInput += OnEndTakingInput;
        uISearchBar.OnNeedingVirtualKeyboard += OpenVirtualKeyboardWhenNeeded;
        uISearchBar.OnCanceledTakingInput += OnCanceledInput;
        UIImageButton uIImageButton2 = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/SearchCancel"))
        {
            HAlign = 1f,
            VAlign = 0.5f,
            Left = new StyleDimension(-2f, 0f)
        };
        uIImageButton2.OnMouseOver += searchCancelButton_OnMouseOver;
        uIImageButton2.OnLeftClick += searchCancelButton_OnClick;
        uIPanel.Append(uIImageButton2);
    }
References Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._searchBar, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._searchBoxPanel, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.Click_SearchArea(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.OnCanceledInput(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.OnEndTakingInput(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.OnSearchContentsChanged(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.OnStartTakingInput(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.OpenVirtualKeyboardWhenNeeded(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.searchCancelButton_OnClick(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.searchCancelButton_OnMouseOver(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildInfinitesMenuContents().