TModLoader: Terraria.UI.ItemSorting.RefillItemStack
RefillItemStack()
static void Terraria.UI.ItemSorting.RefillItemStack (Item[] inv, Item itemToRefill, int loopStartIndex, int loopEndIndex) inline static private
Definition at line 1414 of file ItemSorting.cs.
    {
        int num = itemToRefill.maxStack - itemToRefill.stack;
        if (num <= 0)
        {
            return;
        }
        for (int i = loopStartIndex; i < loopEndIndex; i++)
        {
            Item item = inv[i];
            if (item.stack >= 1 && item.type == itemToRefill.type && ItemLoader.TryStackItems(itemToRefill, inv[i], out var numTransfered))
            {
                num -= numTransfered;
                if (item.stack <= 0)
                {
                    item.TurnToAir();
                }
                if (num <= 0)
                {
                    break;
                }
            }
        }
    }
References Terraria.Item.stack, Terraria.ModLoader.ItemLoader.TryStackItems(), Terraria.Item.TurnToAir(), and Terraria.Item.type.
Referenced by Terraria.UI.ItemSorting.ClearAmmoSlotSpaces(), and Terraria.UI.ItemSorting.FillAmmoFromInventory().