TModLoader: Terraria.Mount.UpdateEffects
UpdateEffects()
void Terraria.Mount.UpdateEffects (Player mountedPlayer) inline
Definition at line 4633 of file Mount.cs.
    {
        //IL_0c10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c25: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c36: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c45: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c75: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c79: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c85: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0caa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ccb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ccd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ccf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e30: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e45: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e60: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e83: Unknown result type (might be due to invalid IL or missing references)
        //IL_046c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0471: Unknown result type (might be due to invalid IL or missing references)
        //IL_0473: Unknown result type (might be due to invalid IL or missing references)
        //IL_0475: Unknown result type (might be due to invalid IL or missing references)
        //IL_071c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0721: Unknown result type (might be due to invalid IL or missing references)
        //IL_0725: Unknown result type (might be due to invalid IL or missing references)
        //IL_072a: Unknown result type (might be due to invalid IL or missing references)
        //IL_072c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0733: Unknown result type (might be due to invalid IL or missing references)
        //IL_0738: Unknown result type (might be due to invalid IL or missing references)
        //IL_073b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0740: Unknown result type (might be due to invalid IL or missing references)
        //IL_074c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0756: Unknown result type (might be due to invalid IL or missing references)
        //IL_075b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0761: Unknown result type (might be due to invalid IL or missing references)
        //IL_076b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0770: Unknown result type (might be due to invalid IL or missing references)
        //IL_0775: Unknown result type (might be due to invalid IL or missing references)
        //IL_077a: Unknown result type (might be due to invalid IL or missing references)
        //IL_077c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0783: Unknown result type (might be due to invalid IL or missing references)
        //IL_0272: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_029f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0902: Unknown result type (might be due to invalid IL or missing references)
        //IL_0909: Unknown result type (might be due to invalid IL or missing references)
        //IL_0916: Unknown result type (might be due to invalid IL or missing references)
        //IL_091b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0922: Unknown result type (might be due to invalid IL or missing references)
        //IL_0929: Unknown result type (might be due to invalid IL or missing references)
        //IL_0936: Unknown result type (might be due to invalid IL or missing references)
        //IL_093b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0942: Unknown result type (might be due to invalid IL or missing references)
        //IL_0949: Unknown result type (might be due to invalid IL or missing references)
        //IL_0956: Unknown result type (might be due to invalid IL or missing references)
        //IL_095b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0962: Unknown result type (might be due to invalid IL or missing references)
        //IL_0969: Unknown result type (might be due to invalid IL or missing references)
        //IL_0976: Unknown result type (might be due to invalid IL or missing references)
        //IL_097b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0982: Unknown result type (might be due to invalid IL or missing references)
        //IL_0989: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0792: Unknown result type (might be due to invalid IL or missing references)
        //IL_0799: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_0207: Unknown result type (might be due to invalid IL or missing references)
        //IL_020c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_021b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d17: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d19: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_04af: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09db: Unknown result type (might be due to invalid IL or missing references)
        //IL_09dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a35: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0845: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dfd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a75: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a83: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aaa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aaf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0abd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0abf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0324: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_0338: Unknown result type (might be due to invalid IL or missing references)
        //IL_0342: Unknown result type (might be due to invalid IL or missing references)
        //IL_0347: Unknown result type (might be due to invalid IL or missing references)
        //IL_0349: Unknown result type (might be due to invalid IL or missing references)
        //IL_0354: Unknown result type (might be due to invalid IL or missing references)
        //IL_035a: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0361: Unknown result type (might be due to invalid IL or missing references)
        //IL_0363: Unknown result type (might be due to invalid IL or missing references)
        //IL_0365: Unknown result type (might be due to invalid IL or missing references)
        //IL_0367: Unknown result type (might be due to invalid IL or missing references)
        //IL_036e: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bda: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0528: Unknown result type (might be due to invalid IL or missing references)
        //IL_052e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b45: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0551: Unknown result type (might be due to invalid IL or missing references)
        //IL_0556: Unknown result type (might be due to invalid IL or missing references)
        mountedPlayer.autoJump = AutoJump;
        _shouldSuperCart = MountID.Sets.Cart[_type] && mountedPlayer.UsingSuperCart;
        MountLoader.UpdateEffects(mountedPlayer);
        if (_shouldSuperCart)
        {
            CastSuperCartLaser(mountedPlayer);
            float num = 1f + Math.Abs(mountedPlayer.velocity.X) / RunSpeed * 2.5f;
            mountedPlayer.statDefense += (int)(2f * num);
        }
        Color newColor;
        switch (_type)
        {
        case 23:
        {
            Vector2 pos3 = mountedPlayer.Center + GetWitchBroomTrinketOriginOffset(mountedPlayer) + (GetWitchBroomTrinketRotation(mountedPlayer) + (float)Math.PI / 2f).ToRotationVector2() * 11f;
            Vector3 rgb = new Vector3(1f, 0.75f, 0.5f) * 0.85f;
            Vector2 vector3 = mountedPlayer.RotatedRelativePoint(pos3);
            Lighting.AddLight(vector3, rgb);
            if (Main.rand.Next(45) == 0)
            {
                Vector2 vector4 = Main.rand.NextVector2Circular(4f, 4f);
                Dust dust2 = Dust.NewDustPerfect(vector3 + vector4, 43, Vector2.Zero, 254, new Color(255, 255, 0, 255), 0.3f);
                if (vector4 != Vector2.Zero)
                {
                    dust2.velocity = vector3.DirectionTo(dust2.position) * 0.2f;
                }
                dust2.fadeIn = 0.3f;
                dust2.noLightEmittence = true;
                dust2.customData = mountedPlayer;
                dust2.shader = GameShaders.Armor.GetSecondaryShader(mountedPlayer.cMount, mountedPlayer);
            }
            float num5 = 0.1f;
            num5 += ((Vector2)(ref mountedPlayer.velocity)).Length() / 30f;
            Vector2 pos4 = mountedPlayer.Center + new Vector2(18f - 20f * Main.rand.NextFloat() * (float)mountedPlayer.direction, 12f);
            Vector2 pos5 = mountedPlayer.Center + new Vector2((float)(52 * mountedPlayer.direction), -6f);
            pos4 = mountedPlayer.RotatedRelativePoint(pos4);
            pos5 = mountedPlayer.RotatedRelativePoint(pos5);
            if (!(Main.rand.NextFloat() <= num5))
            {
                break;
            }
            float num6 = Main.rand.NextFloat();
            for (float num7 = 0f; num7 < 1f; num7 += 0.125f)
            {
                if (Main.rand.Next(15) == 0)
                {
                    Vector2 spinningpoint = ((float)Math.PI * 2f * num7 + num6).ToRotationVector2() * new Vector2(0.5f, 1f) * 4f;
                    spinningpoint = spinningpoint.RotatedBy(mountedPlayer.fullRotation);
                    Dust dust3 = Dust.NewDustPerfect(pos4 + spinningpoint, 43, Vector2.Zero, 254, new Color(255, 255, 0, 255), 0.3f);
                    dust3.velocity = spinningpoint * 0.025f + pos5.DirectionTo(dust3.position) * 0.5f;
                    dust3.fadeIn = 0.3f;
                    dust3.noLightEmittence = true;
                    dust3.shader = GameShaders.Armor.GetSecondaryShader(mountedPlayer.cMount, mountedPlayer);
                }
            }
            break;
        }
        case 25:
            DoGemMinecartEffect(mountedPlayer, 86);
            break;
        case 26:
            DoGemMinecartEffect(mountedPlayer, 87);
            break;
        case 27:
            DoGemMinecartEffect(mountedPlayer, 88);
            break;
        case 28:
            DoGemMinecartEffect(mountedPlayer, 89);
            break;
        case 29:
            DoGemMinecartEffect(mountedPlayer, 90);
            break;
        case 30:
            DoGemMinecartEffect(mountedPlayer, 91);
            break;
        case 31:
            DoGemMinecartEffect(mountedPlayer, 262);
            break;
        case 9:
        case 46:
        {
            if (_type == 46)
            {
                mountedPlayer.hasJumpOption_Santank = true;
            }
            Vector2 center = mountedPlayer.Center;
            Vector2 vector2 = center;
            bool flag = false;
            float num15 = 1500f;
            float num2 = 850f;
            for (int i = 0; i < 200; i++)
            {
                NPC nPC = Main.npc[i];
                if (!nPC.CanBeChasedBy(this))
                {
                    continue;
                }
                Vector2 v = nPC.Center - center;
                float num3 = ((Vector2)(ref v)).Length();
                if (num3 < num2 && ((Vector2.Distance(vector2, center) > num3 && num3 < num15) || !flag))
                {
                    bool flag2 = true;
                    float num4 = Math.Abs(v.ToRotation());
                    if (mountedPlayer.direction == 1 && (double)num4 > 1.047197594907988)
                    {
                        flag2 = false;
                    }
                    else if (mountedPlayer.direction == -1 && (double)num4 < 2.0943951461045853)
                    {
                        flag2 = false;
                    }
                    if (Collision.CanHitLine(center, 0, 0, nPC.position, nPC.width, nPC.height) && flag2)
                    {
                        num15 = num3;
                        vector2 = nPC.Center;
                        flag = true;
                    }
                }
            }
            if (flag)
            {
                bool flag3 = _abilityCooldown == 0;
                if (_type == 46)
                {
                    flag3 = _abilityCooldown % 10 == 0;
                }
                if (flag3 && mountedPlayer.whoAmI == Main.myPlayer)
                {
                    AimAbility(mountedPlayer, vector2);
                    if (_abilityCooldown == 0)
                    {
                        StopAbilityCharge();
                    }
                    UseAbility(mountedPlayer, vector2, toggleOn: false);
                }
                else
                {
                    AimAbility(mountedPlayer, vector2);
                    _abilityCharging = true;
                }
            }
            else
            {
                _abilityCharging = false;
                ResetHeadPosition();
            }
            break;
        }
        case 10:
            mountedPlayer.hasJumpOption_Unicorn = true;
            if (Math.Abs(mountedPlayer.velocity.X) > mountedPlayer.mount.DashSpeed - mountedPlayer.mount.RunSpeed / 2f)
            {
                mountedPlayer.noKnockback = true;
            }
            if (mountedPlayer.itemAnimation > 0 && mountedPlayer.inventory[mountedPlayer.selectedItem].type == 1260)
            {
                AchievementsHelper.HandleSpecialEvent(mountedPlayer, 5);
            }
            break;
        case 47:
            mountedPlayer.hasJumpOption_WallOfFleshGoat = true;
            if (Math.Abs(mountedPlayer.velocity.X) > mountedPlayer.mount.DashSpeed - mountedPlayer.mount.RunSpeed / 2f)
            {
                mountedPlayer.noKnockback = true;
            }
            break;
        case 14:
            mountedPlayer.hasJumpOption_Basilisk = true;
            if (Math.Abs(mountedPlayer.velocity.X) > mountedPlayer.mount.DashSpeed - mountedPlayer.mount.RunSpeed / 2f)
            {
                mountedPlayer.noKnockback = true;
            }
            break;
        case 40:
        case 41:
        case 42:
            if (Math.Abs(mountedPlayer.velocity.X) > mountedPlayer.mount.DashSpeed - mountedPlayer.mount.RunSpeed / 2f)
            {
                mountedPlayer.noKnockback = true;
            }
            break;
        case 12:
            if (mountedPlayer.MountFishronSpecial)
            {
                newColor = Colors.CurrentLiquidColor;
                Vector3 vector12 = ((Color)(ref newColor)).ToVector3();
                vector12 *= 0.4f;
                Point point = (mountedPlayer.Center + Vector2.UnitX * (float)mountedPlayer.direction * 20f + mountedPlayer.velocity * 10f).ToTileCoordinates();
                if (!WorldGen.SolidTile(point.X, point.Y))
                {
                    Lighting.AddLight(point.X, point.Y, vector12.X, vector12.Y, vector12.Z);
                }
                else
                {
                    Lighting.AddLight(mountedPlayer.Center + Vector2.UnitX * (float)mountedPlayer.direction * 20f, vector12.X, vector12.Y, vector12.Z);
                }
                mountedPlayer.allDamage += 0.15f;
            }
            if (mountedPlayer.statLife <= mountedPlayer.statLifeMax2 / 2)
            {
                mountedPlayer.MountFishronSpecialCounter = 60f;
            }
            if (mountedPlayer.wet || (Main.raining && WorldGen.InAPlaceWithWind(mountedPlayer.position, mountedPlayer.width, mountedPlayer.height)))
            {
                mountedPlayer.MountFishronSpecialCounter = 420f;
            }
            break;
        case 8:
            if (mountedPlayer.ownedProjectileCounts[453] < 1)
            {
                _abilityActive = false;
            }
            break;
        case 11:
        {
            Vector3 vector7 = default(Vector3);
            ((Vector3)(ref vector7))._002Ector(0.4f, 0.12f, 0.15f);
            float num10 = 1f + Math.Abs(mountedPlayer.velocity.X) / RunSpeed * 2.5f;
            int num11 = Math.Sign(mountedPlayer.velocity.X);
            if (num11 == 0)
            {
                num11 = mountedPlayer.direction;
            }
            if (Main.netMode == 2)
            {
                break;
            }
            vector7 *= num10;
            Lighting.AddLight(mountedPlayer.Center, vector7.X, vector7.Y, vector7.Z);
            Lighting.AddLight(mountedPlayer.Top, vector7.X, vector7.Y, vector7.Z);
            Lighting.AddLight(mountedPlayer.Bottom, vector7.X, vector7.Y, vector7.Z);
            Lighting.AddLight(mountedPlayer.Left, vector7.X, vector7.Y, vector7.Z);
            Lighting.AddLight(mountedPlayer.Right, vector7.X, vector7.Y, vector7.Z);
            float num12 = -24f;
            if (mountedPlayer.direction != num11)
            {
                num12 = -22f;
            }
            if (num11 == -1)
            {
                num12 += 1f;
            }
            Vector2 vector8 = Utils.RotatedBy(new Vector2(num12 * (float)num11, -19f), mountedPlayer.fullRotation);
            Vector2 vector9 = Utils.RotatedBy(new Vector2(MathHelper.Lerp(0f, -8f, mountedPlayer.fullRotation / ((float)Math.PI / 4f)), MathHelper.Lerp(0f, 2f, Math.Abs(mountedPlayer.fullRotation / ((float)Math.PI / 4f)))), mountedPlayer.fullRotation);
            if (num11 == Math.Sign(mountedPlayer.fullRotation))
            {
                vector9 *= MathHelper.Lerp(1f, 0.6f, Math.Abs(mountedPlayer.fullRotation / ((float)Math.PI / 4f)));
            }
            Vector2 vector10 = mountedPlayer.Bottom + vector8 + vector9;
            Vector2 vector11 = mountedPlayer.oldPosition + mountedPlayer.Size * new Vector2(0.5f, 1f) + vector8 + vector9;
            if (Vector2.Distance(vector10, vector11) > 3f)
            {
                int num13 = (int)Vector2.Distance(vector10, vector11) / 3;
                if (Vector2.Distance(vector10, vector11) % 3f != 0f)
                {
                    num13++;
                }
                for (float num14 = 1f; num14 <= (float)num13; num14 += 1f)
                {
                    Dust[] dust4 = Main.dust;
                    Vector2 center2 = mountedPlayer.Center;
                    newColor = default(Color);
                    Dust obj = dust4[Dust.NewDust(center2, 0, 0, 182, 0f, 0f, 0, newColor)];
                    obj.position = Vector2.Lerp(vector11, vector10, num14 / (float)num13);
                    obj.noGravity = true;
                    obj.velocity = Vector2.Zero;
                    obj.customData = mountedPlayer;
                    obj.shader = GameShaders.Armor.GetSecondaryShader(mountedPlayer.cMinecart, mountedPlayer);
                }
            }
            else
            {
                Dust[] dust5 = Main.dust;
                Vector2 center3 = mountedPlayer.Center;
                newColor = default(Color);
                Dust obj2 = dust5[Dust.NewDust(center3, 0, 0, 182, 0f, 0f, 0, newColor)];
                obj2.position = vector10;
                obj2.noGravity = true;
                obj2.velocity = Vector2.Zero;
                obj2.customData = mountedPlayer;
                obj2.shader = GameShaders.Armor.GetSecondaryShader(mountedPlayer.cMinecart, mountedPlayer);
            }
            break;
        }
        case 22:
        {
            mountedPlayer.lavaMax += 420;
            Vector2 vector = mountedPlayer.Center + new Vector2(20f, 10f) * mountedPlayer.Directions;
            Vector2 pos = vector + mountedPlayer.velocity;
            Vector2 pos2 = vector + new Vector2(-1f, -0.5f) * mountedPlayer.Directions;
            vector = mountedPlayer.RotatedRelativePoint(vector);
            pos = mountedPlayer.RotatedRelativePoint(pos);
            pos2 = mountedPlayer.RotatedRelativePoint(pos2);
            Vector2 value = mountedPlayer.shadowPos[2] - mountedPlayer.position + vector;
            Vector2 vector5 = pos - vector;
            vector += vector5;
            value += vector5;
            Vector2 vector6 = pos - pos2;
            float num8 = MathHelper.Clamp(((Vector2)(ref mountedPlayer.velocity)).Length() / 5f, 0f, 1f);
            for (float num9 = 0f; num9 <= 1f; num9 += 0.1f)
            {
                if (!(Main.rand.NextFloat() < num8))
                {
                    Vector2 position = Vector2.Lerp(value, vector, num9);
                    Vector2? velocity = Main.rand.NextVector2Circular(0.5f, 0.5f) * num8;
                    newColor = default(Color);
                    Dust dust = Dust.NewDustPerfect(position, 65, velocity, 0, newColor);
                    dust.scale = 0.6f;
                    dust.fadeIn = 0f;
                    dust.customData = mountedPlayer;
                    dust.velocity *= -1f;
                    dust.noGravity = true;
                    dust.velocity -= vector6;
                    dust.shader = GameShaders.Armor.GetSecondaryShader(mountedPlayer.cMinecart, mountedPlayer);
                    if (Main.rand.Next(10) == 0)
                    {
                        dust.fadeIn = 1.3f;
                        dust.velocity = Main.rand.NextVector2Circular(3f, 3f) * num8;
                    }
                }
            }
            break;
        }
        case 16:
            mountedPlayer.ignoreWater = true;
            break;
        case 24:
            DelegateMethods.v3_1 = new Vector3(0.1f, 0.3f, 1f) * 0.4f;
            Utils.PlotTileLine(mountedPlayer.MountedCenter, mountedPlayer.MountedCenter + mountedPlayer.velocity * 6f, 40f, DelegateMethods.CastLightOpen);
            Utils.PlotTileLine(mountedPlayer.Left, mountedPlayer.Right, 40f, DelegateMethods.CastLightOpen);
            break;
        case 36:
            DoSteamMinecartEffect(mountedPlayer, 303);
            break;
        case 32:
            DoExhaustMinecartEffect(mountedPlayer, 31);
            break;
        case 34:
            DoConfettiMinecartEffect(mountedPlayer);
            break;
        case 37:
            mountedPlayer.canFloatInWater = true;
            mountedPlayer.accFlipper = true;
            break;
        case 13:
        case 15:
        case 17:
        case 18:
        case 19:
        case 20:
        case 21:
        case 33:
        case 35:
        case 38:
        case 39:
        case 43:
        case 44:
        case 45:
            break;
        }
    }
References Terraria.Mount._abilityActive, Terraria.Mount._abilityCharging, Terraria.Mount._abilityCooldown, Terraria.Mount._shouldSuperCart, Terraria.Mount._type, Terraria.Lighting.AddLight(), Terraria.Mount.AimAbility(), Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Mount.AutoJump, Terraria.Collision.CanHitLine(), Terraria.ID.MountID.Sets.Cart, Terraria.DelegateMethods.CastLightOpen(), Terraria.Mount.CastSuperCartLaser(), Terraria.ID.Colors.CurrentLiquidColor, Terraria.Mount.DoConfettiMinecartEffect(), Terraria.Mount.DoExhaustMinecartEffect(), Terraria.Mount.DoGemMinecartEffect(), Terraria.Mount.DoSteamMinecartEffect(), Terraria.Main.dust, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.Mount.GetWitchBroomTrinketOriginOffset(), Terraria.Mount.GetWitchBroomTrinketRotation(), Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.WorldGen.InAPlaceWithWind(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Main.npc, Terraria.Utils.PlotTileLine(), Terraria.Main.raining, Terraria.Main.rand, Terraria.Mount.ResetHeadPosition(), Terraria.Utils.RotatedBy(), Terraria.Mount.RunSpeed, Terraria.WorldGen.SolidTile(), Terraria.Mount.StopAbilityCharge(), Terraria.ModLoader.MountLoader.UpdateEffects(), and Terraria.Mount.UseAbility().
Referenced by Terraria.Player.Update().