TModLoader: Terraria.Mount.UseAbility
UseAbility()
void Terraria.Mount.UseAbility (Player mountedPlayer, Vector2 mousePosition, bool toggleOn) inline
Definition at line 2819 of file Mount.cs.
    {
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_029b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_030b: Unknown result type (might be due to invalid IL or missing references)
        //IL_030d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0312: Unknown result type (might be due to invalid IL or missing references)
        //IL_0314: Unknown result type (might be due to invalid IL or missing references)
        //IL_0316: Unknown result type (might be due to invalid IL or missing references)
        //IL_031b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0320: Unknown result type (might be due to invalid IL or missing references)
        //IL_0322: Unknown result type (might be due to invalid IL or missing references)
        //IL_0329: Unknown result type (might be due to invalid IL or missing references)
        //IL_032e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        //IL_033b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0340: Unknown result type (might be due to invalid IL or missing references)
        //IL_0349: Unknown result type (might be due to invalid IL or missing references)
        //IL_0350: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_035e: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_022a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_0282: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0169: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        switch (_type)
        {
        case 9:
        {
            if (Main.myPlayer != mountedPlayer.whoAmI)
            {
                break;
            }
            int type2 = 606;
            mousePosition = ClampToDeadZone(mountedPlayer, mousePosition);
            Vector2 vector5 = default(Vector2);
            vector5.X = mountedPlayer.position.X + (float)(mountedPlayer.width / 2);
            vector5.Y = mountedPlayer.position.Y + (float)mountedPlayer.height;
            int num3 = (_frameExtra - 6) * 2;
            Vector2 vector6 = default(Vector2);
            for (int i = 0; i < 2; i++)
            {
                vector6.Y = vector5.Y + scutlixEyePositions[num3 + i].Y + (float)_data.yOffset;
                if (mountedPlayer.direction == -1)
                {
                    vector6.X = vector5.X - scutlixEyePositions[num3 + i].X - (float)_data.xOffset;
                }
                else
                {
                    vector6.X = vector5.X + scutlixEyePositions[num3 + i].X + (float)_data.xOffset;
                }
                Vector2 vector7 = mousePosition - vector6;
                ((Vector2)(ref vector7)).Normalize();
                vector7 *= 14f;
                int damage3 = 150;
                vector6 += vector7;
                Projectile.NewProjectile(GetProjectileSpawnSource(mountedPlayer), vector6.X, vector6.Y, vector7.X, vector7.Y, type2, damage3, 0f, Main.myPlayer);
            }
            break;
        }
        case 46:
            if (Main.myPlayer == mountedPlayer.whoAmI)
            {
                SoundStyle style;
                if (_abilityCooldown <= 10)
                {
                    int damage = 120;
                    Vector2 vector = mountedPlayer.Center + new Vector2((float)(mountedPlayer.width * -mountedPlayer.direction), 26f);
                    Vector2 vector2 = Utils.RotatedByRandom(new Vector2(0f, -4f), 0.10000000149011612);
                    Projectile.NewProjectile(GetProjectileSpawnSource(mountedPlayer), vector.X, vector.Y, vector2.X, vector2.Y, 930, damage, 0f, Main.myPlayer);
                    style = SoundID.Item89 with
                    {
                        Volume = SoundID.Item89.Volume * 0.2f
                    };
                    SoundEngine.PlaySound(in style, vector);
                }
                int type = 14;
                int damage2 = 100;
                mousePosition = ClampToDeadZone(mountedPlayer, mousePosition);
                Vector2 vector3 = default(Vector2);
                vector3.X = mountedPlayer.position.X + (float)(mountedPlayer.width / 2);
                vector3.Y = mountedPlayer.position.Y + (float)mountedPlayer.height;
                Vector2 vector4 = default(Vector2);
                ((Vector2)(ref vector4))._002Ector(vector3.X + (float)(mountedPlayer.width * mountedPlayer.direction), vector3.Y - 12f);
                Vector2 v = mousePosition - vector4;
                v = v.SafeNormalize(Vector2.Zero);
                v *= 12f;
                v = v.RotatedByRandom(0.20000000298023224);
                Projectile.NewProjectile(GetProjectileSpawnSource(mountedPlayer), vector4.X, vector4.Y, v.X, v.Y, type, damage2, 0f, Main.myPlayer);
                style = SoundID.Item11 with
                {
                    Volume = SoundID.Item11.Volume * 0.2f
                };
                SoundEngine.PlaySound(in style, vector4);
            }
            break;
        case 8:
            if (Main.myPlayer == mountedPlayer.whoAmI)
            {
                if (!toggleOn)
                {
                    _abilityActive = false;
                }
                else if (!_abilityActive)
                {
                    if (mountedPlayer.whoAmI == Main.myPlayer)
                    {
                        float num = Main.screenPosition.X + (float)Main.mouseX;
                        float num2 = Main.screenPosition.Y + (float)Main.mouseY;
                        float ai = num - mountedPlayer.position.X;
                        float ai2 = num2 - mountedPlayer.position.Y;
                        Projectile.NewProjectile(GetProjectileSpawnSource(mountedPlayer), num, num2, 0f, 0f, 453, 0, 0f, mountedPlayer.whoAmI, ai, ai2);
                    }
                    _abilityActive = true;
                }
            }
            else
            {
                _abilityActive = toggleOn;
            }
            break;
        }
    }
References Terraria.Mount._abilityActive, Terraria.Mount._abilityCooldown, Terraria.Mount._data, Terraria.Mount._frameExtra, Terraria.Mount._type, Terraria.Mount.ClampToDeadZone(), Terraria.Mount.GetProjectileSpawnSource(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Utils.RotatedByRandom(), Terraria.Mount.scutlixEyePositions, Terraria.Mount.MountData.xOffset, and Terraria.Mount.MountData.yOffset.
Referenced by Terraria.Player.ItemCheck_HandleMount(), and Terraria.Mount.UpdateEffects().