TModLoader: Terraria.Mount.UseDrill
UseDrill()
void Terraria.Mount.UseDrill (Player mountedPlayer) inline
    {
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_035a: Unknown result type (might be due to invalid IL or missing references)
        //IL_035f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0201: Unknown result type (might be due to invalid IL or missing references)
        //IL_0208: Unknown result type (might be due to invalid IL or missing references)
        //IL_0212: Unknown result type (might be due to invalid IL or missing references)
        //IL_0218: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f0: Unknown result type (might be due to invalid IL or missing references)
        if (_type != 8 || !_abilityActive)
        {
            return;
        }
        DrillMountData drillMountData = (DrillMountData)_mountSpecificData;
        bool flag = mountedPlayer.whoAmI == Main.myPlayer;
        if (mountedPlayer.controlUseItem)
        {
            Vector2 vector = default(Vector2);
            Vector2 vector2 = default(Vector2);
            for (int i = 0; i < amountOfBeamsAtOnce; i++)
            {
                if (drillMountData.beamCooldown != 0)
                {
                    break;
                }
                for (int j = 0; j < drillMountData.beams.Length; j++)
                {
                    DrillBeam drillBeam = drillMountData.beams[j];
                    if (drillBeam.cooldown != 0)
                    {
                        continue;
                    }
                    Point16 point = DrillSmartCursor_Blocks(mountedPlayer, drillMountData);
                    if (point == Point16.NegativeOne)
                    {
                        continue;
                    }
                    drillBeam.curTileTarget = point;
                    int pickPower = drillPickPower;
                    if (flag)
                    {
                        bool flag2 = true;
                        if (WorldGen.InWorld(point.X, point.Y) && Main.tile[point.X, point.Y] != null && Main.tile[point.X, point.Y].type == 26 && !Main.hardMode)
{
                            flag2 = false;
                            mountedPlayer.Hurt(PlayerDeathReason.ByOther(4), mountedPlayer.statLife / 2, -mountedPlayer.direction);
                        }
                        if (mountedPlayer.noBuilding)
{
                            flag2 = false;
                        }
                        if (flag2)
{
                            mountedPlayer.PickTile(point.X, point.Y, pickPower);
                        }
                    }
                    ((Vector2)(ref vector))._002Ector((float)(point.X << 4) + 8f, (float)(point.Y << 4) + 8f);
                    float num = (vector - mountedPlayer.Center).ToRotation();
                    for (int k = 0; k < 2; k++)
                    {
                        float num2 = num + ((Main.rand.Next(2) == 1) ? (-1f) : 1f) * ((float)Math.PI / 2f);
                        float num3 = (float)Main.rand.NextDouble() * 2f + 2f;
                        ((Vector2)(ref vector2))._002Ector((float)Math.Cos(num2) * num3, (float)Math.Sin(num2) * num3);
                        int num4 = Dust.NewDust(vector, 0, 0, 230, vector2.X, vector2.Y);
                        Main.dust[num4].noGravity = true;
                        Main.dust[num4].customData = mountedPlayer;
                    }
                    if (flag)
                    {
                        Tile.SmoothSlope(point.X, point.Y, applyToNeighbors: true, sync: true);
                    }
                    drillBeam.cooldown = drillPickTime;
                    drillBeam.lastPurpose = 0;
                    break;
                }
            }
        }
        if (!mountedPlayer.controlUseTile)
        {
            return;
        }
        Vector2 vector3 = default(Vector2);
        Vector2 vector4 = default(Vector2);
        for (int l = 0; l < amountOfBeamsAtOnce; l++)
        {
            if (drillMountData.beamCooldown != 0)
            {
                break;
            }
            for (int m = 0; m < drillMountData.beams.Length; m++)
            {
                DrillBeam drillBeam2 = drillMountData.beams[m];
                if (drillBeam2.cooldown != 0)
                {
                    continue;
                }
                Point16 point2 = DrillSmartCursor_Walls(mountedPlayer, drillMountData);
                if (point2 == Point16.NegativeOne)
                {
                    continue;
                }
                drillBeam2.curTileTarget = point2;
                int damage = drillPickPower;
                if (flag)
                {
                    bool flag3 = true;
                    if (mountedPlayer.noBuilding)
                    {
                        flag3 = false;
                    }
                    if (flag3)
                    {
                        mountedPlayer.PickWall(point2.X, point2.Y, damage);
                    }
                }
                ((Vector2)(ref vector3))._002Ector((float)(point2.X << 4) + 8f, (float)(point2.Y << 4) + 8f);
                float num5 = (vector3 - mountedPlayer.Center).ToRotation();
                for (int n = 0; n < 2; n++)
                {
                    float num6 = num5 + ((Main.rand.Next(2) == 1) ? (-1f) : 1f) * ((float)Math.PI / 2f);
                    float num7 = (float)Main.rand.NextDouble() * 2f + 2f;
                    ((Vector2)(ref vector4))._002Ector((float)Math.Cos(num6) * num7, (float)Math.Sin(num6) * num7);
                    int num8 = Dust.NewDust(vector3, 0, 0, 230, vector4.X, vector4.Y);
                    Main.dust[num8].noGravity = true;
                    Main.dust[num8].customData = mountedPlayer;
                }
                drillBeam2.cooldown = drillPickTime;
                drillBeam2.lastPurpose = 1;
                break;
            }
        }
    }
References Terraria.Mount._abilityActive, Terraria.Mount._mountSpecificData, Terraria.Mount._type, Terraria.Mount.amountOfBeamsAtOnce, Terraria.DataStructures.PlayerDeathReason.ByOther(), Terraria.Mount.drillPickPower, Terraria.Mount.drillPickTime, Terraria.Mount.DrillSmartCursor_Blocks(), Terraria.Mount.DrillSmartCursor_Walls(), Terraria.Main.dust, Terraria.Main.hardMode, Terraria.WorldGen.InWorld(), Terraria.Main.myPlayer, Terraria.DataStructures.Point16.NegativeOne, Terraria.Dust.NewDust(), Terraria.Main.rand, Terraria.Tile.SmoothSlope(), Terraria.Main.tile, Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.Player.Update().