TModLoader: Terraria.Mount.CastSuperCartLaser
CastSuperCartLaser()
void Terraria.Mount.CastSuperCartLaser (Player mountedPlayer) inline private
    {
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        int num = Math.Sign(mountedPlayer.velocity.X);
        if (num == 0)
        {
            num = mountedPlayer.direction;
        }
        if (mountedPlayer.whoAmI != Main.myPlayer || mountedPlayer.velocity.X == 0f)
        {
            return;
        }
        Vector2 minecartMechPoint = GetMinecartMechPoint(mountedPlayer, 20, -19);
        int damage = 60;
        int num2 = 0;
        float num3 = 0f;
        for (int i = 0; i < 200; i++)
        {
            NPC nPC = Main.npc[i];
            if (nPC.active && nPC.immune[mountedPlayer.whoAmI] <= 0 && !nPC.dontTakeDamage && nPC.Distance(minecartMechPoint) < 300f && nPC.CanBeChasedBy(mountedPlayer) && Collision.CanHitLine(nPC.position, nPC.width, nPC.height, minecartMechPoint, 0, 0) && Math.Abs(MathHelper.WrapAngle(MathHelper.WrapAngle(nPC.AngleFrom(minecartMechPoint)) - MathHelper.WrapAngle((mountedPlayer.fullRotation + (float)num == -1f) ? ((float)Math.PI) : 0f))) < (float)Math.PI / 4f)
            {
                minecartMechPoint = GetMinecartMechPoint(mountedPlayer, -20, -39);
                Vector2 v = nPC.position + nPC.Size * Utils.RandomVector2(Main.rand, 0f, 1f) - minecartMechPoint;
                num3 += v.ToRotation();
                num2++;
                int num4 = Projectile.NewProjectile(GetProjectileSpawnSource(mountedPlayer), minecartMechPoint.X, minecartMechPoint.Y, v.X, v.Y, 591, 0, 0f, mountedPlayer.whoAmI, mountedPlayer.whoAmI);
                Main.projectile[num4].Center = nPC.Center;
                Main.projectile[num4].damage = damage;
                Main.projectile[num4].Damage();
                Main.projectile[num4].damage = 0;
                Main.projectile[num4].Center = minecartMechPoint;
            }
        }
    }
References Terraria.Collision.CanHitLine(), Terraria.Entity.Center, Terraria.Projectile.damage, Terraria.Projectile.Damage(), Terraria.Mount.GetMinecartMechPoint(), Terraria.Mount.GetProjectileSpawnSource(), Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.Main.projectile, Terraria.Main.rand, and Terraria.Utils.RandomVector2().
Referenced by Terraria.Mount.UpdateEffects().