TModLoader: Terraria.Mount.EmitGolfCartWheelDust
EmitGolfCartWheelDust()
static void Terraria.Mount.EmitGolfCartWheelDust (Player mountedPlayer, Vector2 legSpot) inline static private
Definition at line 4369 of file Mount.cs.
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00de: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        if (Main.rand.Next(5) != 0)
        {
            return;
        }
        Point p = (legSpot + new Vector2(0f, mountedPlayer.gravDir * 2f)).ToTileCoordinates();
        if (!WorldGen.InWorld(p.X, p.Y, 10))
        {
            return;
        }
        Tile tileSafely = Framing.GetTileSafely(p.X, p.Y);
        if (WorldGen.SolidTile(p))
        {
            int num = WorldGen.KillTile_GetTileDustAmount(fail: true, tileSafely, p.X, p.Y);
            if (num > 1)
            {
                num = 1;
            }
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector((float)(-mountedPlayer.direction), (0f - mountedPlayer.gravDir) * 1f);
            for (int i = 0; i < num; i++)
            {
                Dust obj = Main.dust[WorldGen.KillTile_MakeTileDust(p.X, p.Y, tileSafely)];
                obj.velocity *= 0.2f;
                obj.velocity += vector;
                obj.position = legSpot;
                obj.scale *= 0.8f;
                obj.fadeIn *= 0.8f;
            }
        }
    }
References Terraria.Main.dust, Terraria.Framing.GetTileSafely(), Terraria.WorldGen.InWorld(), Terraria.WorldGen.KillTile_GetTileDustAmount(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.Main.rand, and Terraria.WorldGen.SolidTile().
Referenced by Terraria.Mount.UpdateFrame_GolfCart().