TModLoader: Terraria.Mount.DrillSmartCursor_Blocks
DrillSmartCursor_Blocks()
Point16 Terraria.Mount.DrillSmartCursor_Blocks (Player mountedPlayer, DrillMountData data) inline private
Definition at line 2713 of file Mount.cs.
    {
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        Vector2 val = ((mountedPlayer.whoAmI != Main.myPlayer) ? data.crosshairPosition : (Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY)));
        Vector2 center = mountedPlayer.Center;
        Vector2 vector2 = val - center;
        float num = ((Vector2)(ref vector2)).Length();
        if (num > 224f)
        {
            num = 224f;
        }
        num += 32f;
        ((Vector2)(ref vector2)).Normalize();
        Vector2 end = center + vector2 * num;
        Point16 tilePoint = new Point16(-1, -1);
        if (!Utils.PlotTileLine(center, end, 65.6f, delegate(int x, int y)
        {
            tilePoint = new Point16(x, y);
            for (int i = 0; i < data.beams.Length; i++)
            {
                if (data.beams[i].curTileTarget == tilePoint && data.beams[i].lastPurpose == 0)
                {
                    return true;
                }
            }
            if (!WorldGen.CanKillTile(x, y))
            {
                return true;
            }
            return (Main.tile[x, y] == null || Main.tile[x, y].inActive() || !Main.tile[x, y].active()) ? true : false;
        }))
        {
            return tilePoint;
        }
        return new Point16(-1, -1);
    }
References Terraria.Mount.DrillMountData.beams, Terraria.WorldGen.CanKillTile(), Terraria.Mount.DrillMountData.crosshairPosition, Terraria.Mount.DrillBeam.curTileTarget, Terraria.Mount.DrillBeam.lastPurpose, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Utils.PlotTileLine(), and Terraria.Main.tile.
Referenced by Terraria.Mount.UseDrill().