TModLoader: Terraria.Mount.UpdateFrame_GolfCart
UpdateFrame_GolfCart()
void Terraria.Mount.UpdateFrame_GolfCart (Player mountedPlayer, int state, Vector2 velocity) inline private
    {
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_0158: Unknown result type (might be due to invalid IL or missing references)
        if (state != 2)
        {
            if (_frameExtraCounter != 0f || _frameExtra != 0)
            {
                if (_frameExtraCounter == -1f)
                {
                    _frameExtraCounter = 0f;
                    _frameExtra = 1;
                }
                if ((_frameExtraCounter += 1f) >= 6f)
                {
                    _frameExtraCounter = 0f;
                    if (_frameExtra > 0)
                    {
                        _frameExtra--;
                    }
                }
            }
            else
            {
                _frameExtra = 0;
                _frameExtraCounter = 0f;
            }
        }
        else if (velocity.Y >= 0f)
        {
            if (_frameExtra < 1)
            {
                _frameExtra = 1;
            }
            if (_frameExtra == 2)
            {
                _frameExtraCounter = -1f;
            }
            else if ((_frameExtraCounter += 1f) >= 6f)
            {
                _frameExtraCounter = 0f;
                if (_frameExtra < 2)
                {
                    _frameExtra++;
                }
            }
        }
        if (state != 2 && state != 0 && state != 3 && state != 4)
        {
            EmitGolfCartWheelDust(mountedPlayer, mountedPlayer.Bottom + new Vector2((float)(mountedPlayer.direction * -20), 0f));
            EmitGolfCartWheelDust(mountedPlayer, mountedPlayer.Bottom + new Vector2((float)(mountedPlayer.direction * 20), 0f));
        }
        EmitGolfCartlight(mountedPlayer.Bottom + new Vector2((float)(mountedPlayer.direction * 40), -20f), mountedPlayer.direction);
    }
References Terraria.Mount._frameExtra, Terraria.Mount._frameExtraCounter, Terraria.Mount.EmitGolfCartlight(), and Terraria.Mount.EmitGolfCartWheelDust().
Referenced by Terraria.Mount.UpdateFrame().