TModLoader: Terraria.Mount.SetMount
SetMount()
void Terraria.Mount.SetMount (int m, Player mountedPlayer, bool faceLeft = false) inline
Definition at line 6395 of file Mount.cs.
    {
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        if (_type == m || m <= -1 || m >= mounts.Length || (m == 5 && mountedPlayer.wet))
        {
            return;
        }
        if (_active)
        {
            mountedPlayer.ClearBuff(_data.buff);
            if (Cart)
            {
                mountedPlayer.ClearBuff(_data.extraBuff);
                mountedPlayer.cartFlip = false;
                mountedPlayer.lastBoost = Vector2.Zero;
            }
            mountedPlayer.fullRotation = 0f;
            mountedPlayer.fullRotationOrigin = Vector2.Zero;
            _mountSpecificData = null;
        }
        else
        {
            _active = true;
        }
        _flyTime = 0;
        _type = m;
        _data = mounts[m];
        _fatigueMax = _data.fatigueMax;
        if (Cart && !faceLeft && !Directional)
        {
            mountedPlayer.AddBuff(_data.extraBuff, 3600);
            _flipDraw = true;
        }
        else
        {
            mountedPlayer.AddBuff(_data.buff, 3600);
            _flipDraw = false;
        }
        if (_type == 44)
        {
            mountedPlayer.velocity *= 0.2f;
            mountedPlayer.dash = 0;
            mountedPlayer.dashType = 0;
            mountedPlayer.dashDelay = 0;
            mountedPlayer.dashTime = 0;
        }
        if (_type == 9 && _abilityCooldown < 20)
        {
            _abilityCooldown = 20;
        }
        if (_type == 46 && _abilityCooldown < 40)
        {
            _abilityCooldown = 40;
        }
        mountedPlayer.position.Y += mountedPlayer.height;
        for (int i = 0; i < mountedPlayer.shadowPos.Length; i++)
        {
            mountedPlayer.shadowPos[i].Y += mountedPlayer.height;
        }
        mountedPlayer.height = 42 + _data.heightBoost;
        mountedPlayer.position.Y -= mountedPlayer.height;
        for (int j = 0; j < mountedPlayer.shadowPos.Length; j++)
        {
            mountedPlayer.shadowPos[j].Y -= mountedPlayer.height;
        }
        mountedPlayer.ResetAdvancedShadows();
        if (_type == 7 || _type == 8)
        {
            mountedPlayer.fullRotationOrigin = new Vector2((float)(mountedPlayer.width / 2), (float)(mountedPlayer.height / 2));
        }
        if (_type == 8)
        {
            _mountSpecificData = new DrillMountData();
        }
        if (_type == 35)
        {
            _mountSpecificData = new ExtraFrameMountData();
        }
        bool skipDust = false;
        MountLoader.SetMount(this, mountedPlayer, ref skipDust);
        if (!skipDust)
        {
            DoSpawnDust(mountedPlayer, isDismounting: false);
        }
        if (mountedPlayer.whoAmI == Main.myPlayer)
        {
            NetMessage.SendData(13, -1, -1, null, mountedPlayer.whoAmI);
        }
    }
References Terraria.Mount._abilityCooldown, Terraria.Mount._active, Terraria.Mount._data, Terraria.Mount._fatigueMax, Terraria.Mount._flipDraw, Terraria.Mount._flyTime, Terraria.Mount._mountSpecificData, Terraria.Mount._type, Terraria.Mount.MountData.buff, Terraria.Mount.Cart, Terraria.Mount.Directional, Terraria.Mount.DoSpawnDust(), Terraria.Mount.MountData.extraBuff, Terraria.Mount.MountData.fatigueMax, Terraria.Mount.MountData.heightBoost, Terraria.Mount.mounts, Terraria.Main.myPlayer, Terraria.NetMessage.SendData(), and Terraria.ModLoader.MountLoader.SetMount().
Referenced by Terraria.Player.GrappleMovement(), Terraria.Player.ItemCheck_Inner(), Terraria.Player.QuickMount(), and Terraria.Player.UpdateBuffs().