TModLoader: Terraria.Mount.AimAbility
AimAbility()
bool Terraria.Mount.AimAbility (Player mountedPlayer, Vector2 mousePosition) inline
    {
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_0443: Unknown result type (might be due to invalid IL or missing references)
        //IL_0444: Unknown result type (might be due to invalid IL or missing references)
        //IL_044a: Unknown result type (might be due to invalid IL or missing references)
        //IL_044f: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0381: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03da: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_0202: Unknown result type (might be due to invalid IL or missing references)
        //IL_0262: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        _aiming = true;
        MountLoader.AimAbility(this, mountedPlayer, mousePosition);
        switch (_type)
        {
        case 9:
        {
            int frameExtra2 = _frameExtra;
            int direction2 = mountedPlayer.direction;
            float num4 = MathHelper.ToDegrees((ClampToDeadZone(mountedPlayer, mousePosition) - mountedPlayer.Center).ToRotation());
            if (num4 > 90f)
            {
                mountedPlayer.direction = -1;
                num4 = 180f - num4;
            }
            else if (num4 < -90f)
            {
                mountedPlayer.direction = -1;
                num4 = -180f - num4;
            }
            else
            {
                mountedPlayer.direction = 1;
            }
            if ((mountedPlayer.direction > 0 && mountedPlayer.velocity.X < 0f) || (mountedPlayer.direction < 0 && mountedPlayer.velocity.X > 0f))
            {
                _flipDraw = true;
            }
            else
            {
                _flipDraw = false;
            }
            if (num4 >= 0f)
            {
                if ((double)num4 < 22.5)
                {
                    _frameExtra = 8;
                }
                else if ((double)num4 < 67.5)
                {
                    _frameExtra = 9;
                }
                else if ((double)num4 < 112.5)
                {
                    _frameExtra = 10;
                }
            }
            else if ((double)num4 > -22.5)
            {
                _frameExtra = 8;
            }
            else if ((double)num4 > -67.5)
            {
                _frameExtra = 7;
            }
            else if ((double)num4 > -112.5)
            {
                _frameExtra = 6;
            }
            float abilityCharge = AbilityCharge;
            if (abilityCharge > 0f)
            {
                Vector2 vector = default(Vector2);
                vector.X = mountedPlayer.position.X + (float)(mountedPlayer.width / 2);
                vector.Y = mountedPlayer.position.Y + (float)mountedPlayer.height;
                int num5 = (_frameExtra - 6) * 2;
                Vector2 vector2 = default(Vector2);
                for (int i = 0; i < 2; i++)
                {
                    vector2.Y = vector.Y + scutlixEyePositions[num5 + i].Y;
                    if (mountedPlayer.direction == -1)
                    {
                        vector2.X = vector.X - scutlixEyePositions[num5 + i].X - (float)_data.xOffset;
                    }
                    else
                    {
                        vector2.X = vector.X + scutlixEyePositions[num5 + i].X + (float)_data.xOffset;
                    }
                    Lighting.AddLight((int)(vector2.X / 16f), (int)(vector2.Y / 16f), 1f * abilityCharge, 0f, 0f);
                }
            }
            if (_frameExtra == frameExtra2)
            {
                return mountedPlayer.direction != direction2;
            }
            return true;
        }
        case 46:
        {
            int frameExtra = _frameExtra;
            int direction = mountedPlayer.direction;
            float num3 = MathHelper.ToDegrees((ClampToDeadZone(mountedPlayer, mousePosition) - mountedPlayer.Center).ToRotation());
            if (num3 > 90f)
            {
                mountedPlayer.direction = -1;
                num3 = 180f - num3;
            }
            else if (num3 < -90f)
            {
                mountedPlayer.direction = -1;
                num3 = -180f - num3;
            }
            else
            {
                mountedPlayer.direction = 1;
            }
            if ((mountedPlayer.direction > 0 && mountedPlayer.velocity.X < 0f) || (mountedPlayer.direction < 0 && mountedPlayer.velocity.X > 0f))
            {
                _flipDraw = true;
            }
            else
            {
                _flipDraw = false;
            }
            if (AbilityCharge > 0f)
            {
                Vector2 vector3 = default(Vector2);
                vector3.X = mountedPlayer.position.X + (float)(mountedPlayer.width / 2);
                vector3.Y = mountedPlayer.position.Y + (float)mountedPlayer.height;
                Vector2 vector4 = default(Vector2);
                for (int j = 0; j < 2; j++)
                {
                    ((Vector2)(ref vector4))._002Ector(vector3.X + (float)(mountedPlayer.width * mountedPlayer.direction), vector3.Y - 12f);
                    Lighting.AddLight((int)(vector4.X / 16f), (int)(vector4.Y / 16f), 0.7f, 0.4f, 0.4f);
                }
            }
            if (_frameExtra == frameExtra)
            {
                return mountedPlayer.direction != direction;
            }
            return true;
        }
        case 8:
        {
            Vector2 v = ClampToDeadZone(mountedPlayer, mousePosition) - mountedPlayer.Center;
            DrillMountData drillMountData = (DrillMountData)_mountSpecificData;
            float num = v.ToRotation();
            if (num < 0f)
            {
                num += (float)Math.PI * 2f;
            }
            drillMountData.diodeRotationTarget = num;
            float num2 = drillMountData.diodeRotation % ((float)Math.PI * 2f);
            if (num2 < 0f)
            {
                num2 += (float)Math.PI * 2f;
            }
            if (num2 < num)
            {
                if (num - num2 > (float)Math.PI)
                {
                    num2 += (float)Math.PI * 2f;
                }
            }
            else if (num2 - num > (float)Math.PI)
            {
                num2 -= (float)Math.PI * 2f;
            }
            drillMountData.diodeRotation = num2;
            drillMountData.crosshairPosition = mousePosition;
            return true;
        }
        default:
            return false;
        }
    }
References Terraria.Mount._aiming, Terraria.Mount._data, Terraria.Mount._flipDraw, Terraria.Mount._frameExtra, Terraria.Mount._mountSpecificData, Terraria.Mount._type, Terraria.Mount.AbilityCharge, Terraria.Lighting.AddLight(), Terraria.ModLoader.MountLoader.AimAbility(), Terraria.Mount.ClampToDeadZone(), Terraria.Mount.scutlixEyePositions, and Terraria.Mount.MountData.xOffset.
Referenced by Terraria.Mount.UpdateEffects().