TModLoader: Terraria.Mount.Draw
Draw()
void Terraria.Mount.Draw (List< DrawData > playerDrawData, int drawType, Player drawPlayer, Vector2 Position, Color drawColor, SpriteEffects playerEffect, float shadow) inline
    {
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_0181: Unknown result type (might be due to invalid IL or missing references)
        //IL_0315: Unknown result type (might be due to invalid IL or missing references)
        //IL_031a: Unknown result type (might be due to invalid IL or missing references)
        //IL_031c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0323: Unknown result type (might be due to invalid IL or missing references)
        //IL_0499: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_041e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0423: Unknown result type (might be due to invalid IL or missing references)
        //IL_0476: Unknown result type (might be due to invalid IL or missing references)
        //IL_0481: Unknown result type (might be due to invalid IL or missing references)
        //IL_048e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0493: Unknown result type (might be due to invalid IL or missing references)
        //IL_057a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0584: Unknown result type (might be due to invalid IL or missing references)
        //IL_0589: Unknown result type (might be due to invalid IL or missing references)
        //IL_0512: Unknown result type (might be due to invalid IL or missing references)
        //IL_0517: Unknown result type (might be due to invalid IL or missing references)
        //IL_0434: Unknown result type (might be due to invalid IL or missing references)
        //IL_044d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0452: Unknown result type (might be due to invalid IL or missing references)
        //IL_0544: Unknown result type (might be due to invalid IL or missing references)
        //IL_0549: Unknown result type (might be due to invalid IL or missing references)
        //IL_054b: Unknown result type (might be due to invalid IL or missing references)
        //IL_054d: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0569: Unknown result type (might be due to invalid IL or missing references)
        //IL_056d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0572: Unknown result type (might be due to invalid IL or missing references)
        //IL_0559: Unknown result type (might be due to invalid IL or missing references)
        //IL_055e: Unknown result type (might be due to invalid IL or missing references)
        //IL_062a: Unknown result type (might be due to invalid IL or missing references)
        //IL_064f: Unknown result type (might be due to invalid IL or missing references)
        //IL_063f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0653: Unknown result type (might be due to invalid IL or missing references)
        //IL_0655: Unknown result type (might be due to invalid IL or missing references)
        //IL_0682: Unknown result type (might be due to invalid IL or missing references)
        //IL_0685: Unknown result type (might be due to invalid IL or missing references)
        //IL_067e: Unknown result type (might be due to invalid IL or missing references)
        //IL_075e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0686: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_090d: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a08: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a13: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_094e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0953: Unknown result type (might be due to invalid IL or missing references)
        //IL_0959: Unknown result type (might be due to invalid IL or missing references)
        //IL_095b: Unknown result type (might be due to invalid IL or missing references)
        //IL_095d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0962: Unknown result type (might be due to invalid IL or missing references)
        //IL_0969: Unknown result type (might be due to invalid IL or missing references)
        //IL_096d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0971: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08db: Unknown result type (might be due to invalid IL or missing references)
        //IL_08df: Unknown result type (might be due to invalid IL or missing references)
        //IL_0710: Unknown result type (might be due to invalid IL or missing references)
        //IL_0712: Unknown result type (might be due to invalid IL or missing references)
        //IL_0719: Unknown result type (might be due to invalid IL or missing references)
        //IL_071d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0721: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ced: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d14: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d19: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d42: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d49: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d82: Unknown result type (might be due to invalid IL or missing references)
        //IL_0daf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ddb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eaf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e29: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e31: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a95: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0acc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c84: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c17: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f35: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f31: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f53: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f58: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f63: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f96: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fac: Unknown result type (might be due to invalid IL or missing references)
        if (playerDrawData == null)
        {
            return;
        }
        Texture2D texture2D2;
        Texture2D texture2D;
        switch (drawType)
        {
        case 0:
            texture2D = _data.backTexture.Value;
            texture2D2 = _data.backTextureGlow.Value;
            break;
        case 1:
            texture2D = _data.backTextureExtra.Value;
            texture2D2 = _data.backTextureExtraGlow.Value;
            break;
        case 2:
            if (_type == 0 && _idleTime >= _idleTimeNext)
            {
                return;
            }
            texture2D = _data.frontTexture.Value;
            texture2D2 = _data.frontTextureGlow.Value;
            break;
        case 3:
            texture2D = _data.frontTextureExtra.Value;
            texture2D2 = _data.frontTextureExtraGlow.Value;
            break;
        default:
            texture2D = null;
            texture2D2 = null;
            break;
        }
        int type = _type;
        if (type == 50 && texture2D != null && texture2D != Asset<Texture2D>.DefaultValue)
        {
            PlayerQueenSlimeMountTextureContent queenSlimeMount = TextureAssets.RenderTargets.QueenSlimeMount;
            queenSlimeMount.Request();
            if (queenSlimeMount.IsReady)
            {
                texture2D = (Texture2D)(object)queenSlimeMount.GetTarget();
            }
        }
        if (texture2D == null)
        {
            return;
        }
        type = _type;
        if ((type == 0 || type == 9) && drawType == 3 && shadow != 0f)
        {
            return;
        }
        int num = XOffset;
        int num6 = YOffset + PlayerOffset;
        if (drawPlayer.direction <= 0 && (!Cart || !Directional))
        {
            num *= -1;
        }
        Position.X = (int)(Position.X - Main.screenPosition.X + (float)(drawPlayer.width / 2) + (float)num);
        Position.Y = (int)(Position.Y - Main.screenPosition.Y + (float)(drawPlayer.height / 2) + (float)num6);
        int num7 = 0;
        bool flag = true;
        int num8 = _data.totalFrames;
        int num9 = _data.textureHeight;
        switch (_type)
        {
        case 23:
            num7 = _frame;
            break;
        case 9:
            num7 = drawType switch
            {
                0 => _frame,
                2 => _frameExtra,
                3 => _frameExtra,
                _ => 0,
            };
            break;
        case 46:
            num7 = drawType switch
            {
                2 => _frame,
                3 => _frameExtra,
                _ => 0,
            };
            break;
        case 5:
            num7 = drawType switch
            {
                0 => _frame,
                1 => _frameExtra,
                _ => 0,
            };
            break;
        case 17:
            num9 = texture2D.Height;
            switch (drawType)
            {
            case 0:
                num7 = _frame;
                num8 = 4;
                break;
            case 1:
                num7 = _frameExtra;
                num8 = 4;
                break;
            default:
                num7 = 0;
                break;
            }
            break;
        case 52:
            if (drawType == 3)
            {
                if (drawPlayer.itemAnimation > 0)
                {
                    Rectangle bodyFrame = drawPlayer.bodyFrame;
                    int num10 = bodyFrame.Y / bodyFrame.Height;
                    int useStyle = drawPlayer.lastVisualizedSelectedItem.useStyle;
                    num7 = Utils.Clamp(num10, 1, 4);
                    if (num7 == 3 || num10 == 0 || useStyle == 13)
                    {
                        num7 = _frame;
                    }
                    if (useStyle == 12 && drawPlayer.itemAnimation > drawPlayer.itemAnimationMax / 2)
                    {
                        num7 = 3;
                    }
                }
                else
                {
                    _ = drawPlayer.lastVisualizedSelectedItem.holdStyle;
                    num7 = _frame;
                }
            }
            else
            {
                num7 = _frame;
            }
            break;
        case 39:
            num9 = texture2D.Height;
            switch (drawType)
            {
            case 2:
                num7 = _frame;
                num8 = 3;
                break;
            case 3:
                num7 = _frameExtra;
                num8 = 6;
                break;
            default:
                num7 = 0;
                break;
            }
            break;
        default:
            num7 = _frame;
            break;
        }
        int num11 = num9 / num8;
        Rectangle value = default(Rectangle);
        ((Rectangle)(ref value))._002Ector(0, num11 * num7, _data.textureWidth, num11);
        if (flag)
        {
            value.Height -= 2;
        }
        switch (_type)
        {
        case 0:
            if (drawType == 3)
            {
                drawColor = Color.White;
            }
            break;
        case 9:
            if (drawType == 3)
            {
                if (_abilityCharge == 0)
                {
                    return;
                }
                drawColor = Color.Multiply(Color.White, (float)_abilityCharge / (float)_data.abilityChargeMax);
                ((Color)(ref drawColor)).A = 0;
            }
            break;
        case 7:
            if (drawType == 3)
            {
                drawColor = new Color(250, 250, 250, 255) * drawPlayer.stealth * (1f - shadow);
            }
            break;
        }
        Color color = default(Color);
        ((Color)(ref color))._002Ector(((Color)(ref drawColor)).ToVector4() * 0.25f + new Vector4(0.75f));
        switch (_type)
        {
        case 45:
            if (drawType == 2)
            {
                ((Color)(ref color))._002Ector(150, 110, 110, 100);
            }
            break;
        case 11:
            if (drawType == 2)
            {
                color = Color.White;
                ((Color)(ref color)).A = 127;
            }
            break;
        case 12:
            if (drawType == 0)
            {
                float num12 = MathHelper.Clamp(drawPlayer.MountFishronSpecialCounter / 60f, 0f, 1f);
                color = Colors.CurrentLiquidColor;
                if (color == Color.Transparent)
                {
                    color = Color.White;
                }
                ((Color)(ref color)).A = 127;
                color *= num12;
            }
            break;
        case 24:
            if (drawType == 2)
            {
                color = Color.SkyBlue * 0.5f;
                ((Color)(ref color)).A = 20;
            }
            break;
        }
        float num13 = 0f;
        switch (_type)
        {
        case 8:
        {
            DrillMountData drillMountData = (DrillMountData)_mountSpecificData;
            switch (drawType)
            {
            case 0:
                num13 = drillMountData.outerRingRotation - num13;
                break;
            case 3:
                num13 = drillMountData.diodeRotation - num13 - drawPlayer.fullRotation;
                break;
            }
            break;
        }
        case 7:
            num13 = drawPlayer.fullRotation;
            break;
        }
        Vector2 origin = Origin;
        type = _type;
        float scale = 1f;
        SpriteEffects spriteEffects;
        switch (_type)
        {
        case 7:
            spriteEffects = (SpriteEffects)0;
            break;
        case 8:
            spriteEffects = (SpriteEffects)((drawPlayer.direction == 1 && drawType == 2) ? 1 : 0);
            break;
        case 6:
        case 13:
            spriteEffects = (SpriteEffects)(_flipDraw ? 1 : 0);
            break;
        default:
            spriteEffects = playerEffect;
            break;
        }
        if (MountID.Sets.FacePlayersVelocity[_type])
        {
            spriteEffects = (SpriteEffects)((Math.Sign(drawPlayer.velocity.X) == -drawPlayer.direction) ? (playerEffect ^ 1) : playerEffect);
        }
        switch (_type)
        {
        case 50:
            if (drawType == 0)
            {
                Vector2 position = Position + new Vector2(0f, (float)(8 - PlayerOffset + 20));
                Rectangle value6 = default(Rectangle);
                ((Rectangle)(ref value6))._002Ector(0, num11 * _frameExtra, _data.textureWidth, num11);
                if (flag)
                {
                    value6.Height -= 2;
                }
                DrawData item7 = new DrawData(TextureAssets.Extra[207].Value, position, value6, drawColor, num13, origin, scale, spriteEffects);
                item7.shader = currentShader;
                playerDrawData.Add(item7);
            }
            break;
        case 35:
        {
            if (drawType != 2)
            {
                break;
            }
            ExtraFrameMountData extraFrameMountData = (ExtraFrameMountData)_mountSpecificData;
            int num3 = -36;
            if (((Enum)spriteEffects).HasFlag((Enum)(object)(SpriteEffects)1))
            {
                num3 *= -1;
            }
            Vector2 vector2 = default(Vector2);
            ((Vector2)(ref vector2))._002Ector((float)num3, -26f);
            if (shadow == 0f)
            {
                if (Math.Abs(drawPlayer.velocity.X) > 1f)
                {
                    extraFrameMountData.frameCounter += Math.Min(2f, Math.Abs(drawPlayer.velocity.X * 0.4f));
                    while (extraFrameMountData.frameCounter > 6f)
                    {
                        extraFrameMountData.frameCounter -= 6f;
                        extraFrameMountData.frame++;
                        if ((extraFrameMountData.frame > 2 && extraFrameMountData.frame < 5) || extraFrameMountData.frame > 7)
{
                            extraFrameMountData.frame = 0;
                        }
                    }
                }
                else
                {
                    extraFrameMountData.frameCounter += 1f;
                    while (extraFrameMountData.frameCounter > 6f)
                    {
                        extraFrameMountData.frameCounter -= 6f;
                        extraFrameMountData.frame++;
                        if (extraFrameMountData.frame > 5)
{
                            extraFrameMountData.frame = 5;
                        }
                    }
                }
            }
            Texture2D value4 = TextureAssets.Extra[142].Value;
            Rectangle value5 = value4.Frame(1, 8, 0, extraFrameMountData.frame);
            if (flag)
            {
                value5.Height -= 2;
            }
            DrawData item9 = new DrawData(value4, Position + vector2, value5, drawColor, num13, origin, scale, spriteEffects);
            item9.shader = currentShader;
            playerDrawData.Add(item9);
            break;
        }
        case 38:
            if (drawType == 0)
            {
                int num2 = 0;
                if (((Enum)spriteEffects).HasFlag((Enum)(object)(SpriteEffects)1))
                {
                    num2 = 22;
                }
                Vector2 vector = default(Vector2);
                ((Vector2)(ref vector))._002Ector((float)num2, -10f);
                Texture2D value2 = TextureAssets.Extra[151].Value;
                Rectangle value3 = value2.Frame();
                DrawData item8 = new DrawData(value2, Position + vector, value3, drawColor, num13, origin, scale, spriteEffects);
                item8.shader = currentShader;
                playerDrawData.Add(item8);
            }
            break;
        }
        if (MountLoader.Draw(this, playerDrawData, drawType, drawPlayer, ref texture2D, ref texture2D2, ref Position, ref value, ref drawColor, ref color, ref num13, ref spriteEffects, ref origin, ref scale, shadow))
        {
            DrawData item6 = new DrawData(texture2D, Position, value, drawColor, num13, origin, scale, spriteEffects);
            item6.shader = currentShader;
            playerDrawData.Add(item6);
            if (texture2D2 != null)
            {
                item6 = new DrawData(texture2D2, Position, value, color * ((float)(int)((Color)(ref drawColor)).A / 255f), num13, origin, scale, spriteEffects);
                item6.shader = currentShader;
            }
            playerDrawData.Add(item6);
        }
        switch (_type)
        {
        case 50:
            if (drawType == 0)
            {
                texture2D = TextureAssets.Extra[205].Value;
                DrawData item3 = new DrawData(texture2D, Position, value, drawColor, num13, origin, scale, spriteEffects);
                item3.shader = currentShader;
                playerDrawData.Add(item3);
                Vector2 position3 = Position + new Vector2(0f, (float)(8 - PlayerOffset + 20));
                Rectangle value8 = default(Rectangle);
                ((Rectangle)(ref value8))._002Ector(0, num11 * _frameExtra, _data.textureWidth, num11);
                if (flag)
                {
                    value8.Height -= 2;
                }
                texture2D = TextureAssets.Extra[206].Value;
                item3 = new DrawData(texture2D, position3, value8, drawColor, num13, origin, scale, spriteEffects);
                item3.shader = currentShader;
                playerDrawData.Add(item3);
            }
            break;
        case 45:
        {
            if (drawType != 0 || shadow != 0f)
            {
                break;
            }
            if (Math.Abs(drawPlayer.velocity.X) > DashSpeed * 0.9f)
            {
                ((Color)(ref color))._002Ector(255, 220, 220, 200);
                scale = 1.1f;
            }
            for (int k = 0; k < 2; k++)
            {
                Vector2 position2 = Position + new Vector2((float)Main.rand.Next(-10, 11) * 0.1f, (float)Main.rand.Next(-10, 11) * 0.1f);
                ((Rectangle)(ref value))._002Ector(0, num11 * 3, _data.textureWidth, num11);
                if (flag)
                {
                    value.Height -= 2;
                }
                DrawData item4 = new DrawData(texture2D2, position2, value, color, num13, origin, scale, spriteEffects);
                item4.shader = currentShader;
                playerDrawData.Add(item4);
            }
            break;
        }
        case 17:
            if (drawType == 1 && ShouldGolfCartEmitLight())
            {
                ((Rectangle)(ref value))._002Ector(0, num11 * 3, _data.textureWidth, num11);
                if (flag)
                {
                    value.Height -= 2;
                }
                drawColor = Color.White * 1f;
                ((Color)(ref drawColor)).A = 0;
                DrawData item = new DrawData(texture2D, Position, value, drawColor, num13, origin, scale, spriteEffects);
                item.shader = currentShader;
                playerDrawData.Add(item);
            }
            break;
        case 23:
            if (drawType == 0)
            {
                texture2D = TextureAssets.Extra[114].Value;
                value = texture2D.Frame(2);
                int width = value.Width;
                value.Width -= 2;
                float witchBroomTrinketRotation = GetWitchBroomTrinketRotation(drawPlayer);
                Vector2 vector6 = Position + GetWitchBroomTrinketOriginOffset(drawPlayer);
                num13 = witchBroomTrinketRotation;
                ((Vector2)(ref origin))._002Ector((float)(value.Width / 2), 0f);
                DrawData item5 = new DrawData(texture2D, vector6.Floor(), value, drawColor, num13, origin, scale, spriteEffects);
                item5.shader = currentShader;
                playerDrawData.Add(item5);
                Color color3 = default(Color);
                ((Color)(ref color3))._002Ector(new Vector3(0.9f, 0.85f, 0f));
                ((Color)(ref color3)).A = (byte)(((Color)(ref color3)).A / 2);
                float num5 = ((float)drawPlayer.miscCounter / 75f * ((float)Math.PI * 2f)).ToRotationVector2().X * 1f;
                Color color4 = new Color(80, 70, 40, 0) * (num5 / 8f + 0.5f) * 0.8f;
                value.X += width;
                for (int l = 0; l < 4; l++)
                {
                    item5 = new DrawData(texture2D, (vector6 + ((float)l * ((float)Math.PI / 2f)).ToRotationVector2() * num5).Floor(), value, color4, num13, origin, scale, spriteEffects);
                    item5.shader = currentShader;
                    playerDrawData.Add(item5);
                }
            }
            break;
        case 8:
        {
            if (drawType != 3)
            {
                break;
            }
            DrillMountData drillMountData2 = (DrillMountData)_mountSpecificData;
            Rectangle value7 = default(Rectangle);
            ((Rectangle)(ref value7))._002Ector(0, 0, 1, 1);
            Vector2 spinningpoint = drillDiodePoint1;
            double radians = drillMountData2.diodeRotation;
            Vector2 val = default(Vector2);
            Vector2 vector3 = spinningpoint.RotatedBy(radians, val);
            Vector2 spinningpoint2 = drillDiodePoint2;
            double radians2 = drillMountData2.diodeRotation;
            val = default(Vector2);
            Vector2 vector4 = spinningpoint2.RotatedBy(radians2, val);
            for (int i = 0; i < drillMountData2.beams.Length; i++)
            {
                DrillBeam drillBeam = drillMountData2.beams[i];
                if (drillBeam.curTileTarget == Point16.NegativeOne)
                {
                    continue;
                }
                for (int j = 0; j < 2; j++)
                {
                    Vector2 val2 = new Vector2((float)(drillBeam.curTileTarget.X * 16 + 8), (float)(drillBeam.curTileTarget.Y * 16 + 8)) - Main.screenPosition - Position;
                    Vector2 vector5;
                    Color color2;
                    if (j == 0)
                    {
                        vector5 = vector3;
                        color2 = Color.CornflowerBlue;
                    }
                    else
                    {
                        vector5 = vector4;
                        color2 = Color.LightGreen;
                    }
                    ((Color)(ref color2)).A = 128;
                    color2 *= 0.5f;
                    Vector2 v = val2 - vector5;
                    float num4 = v.ToRotation();
                    float y = ((Vector2)(ref v)).Length();
                    ((Vector2)(ref val))._002Ector(2f, y);
                    DrawData item2 = new DrawData(TextureAssets.MagicPixel.Value, vector5 + Position, value7, color2, num4 - (float)Math.PI / 2f, Vector2.Zero, val, (SpriteEffects)0);
                    item2.ignorePlayerRotation = true;
                    item2.shader = currentShader;
                    playerDrawData.Add(item2);
                }
            }
            break;
        }
        }
    }
References Terraria.Mount._abilityCharge, Terraria.Mount._data, Terraria.Mount._flipDraw, Terraria.Mount._frame, Terraria.Mount._frameExtra, Terraria.Mount._idleTime, Terraria.Mount._idleTimeNext, Terraria.Mount._mountSpecificData, Terraria.Mount._type, Terraria.Mount.MountData.abilityChargeMax, Terraria.Mount.MountData.backTexture, Terraria.Mount.MountData.backTextureExtra, Terraria.Mount.MountData.backTextureExtraGlow, Terraria.Mount.MountData.backTextureGlow, Terraria.Player.bodyFrame, Terraria.Mount.Cart, Terraria.ID.Colors.CurrentLiquidColor, Terraria.Mount.currentShader, Terraria.Mount.DashSpeed, Terraria.Entity.direction, Terraria.Mount.Directional, Terraria.ModLoader.MountLoader.Draw(), Terraria.Mount.drillDiodePoint1, Terraria.Mount.drillDiodePoint2, Terraria.GameContent.TextureAssets.Extra, Terraria.ID.MountID.Sets.FacePlayersVelocity, Terraria.Mount.MountData.frontTexture, Terraria.Mount.MountData.frontTextureExtra, Terraria.Mount.MountData.frontTextureExtraGlow, Terraria.Mount.MountData.frontTextureGlow, Terraria.Player.fullRotation, Terraria.Mount.GetWitchBroomTrinketOriginOffset(), Terraria.Mount.GetWitchBroomTrinketRotation(), Terraria.Item.holdStyle, Terraria.Player.itemAnimation, Terraria.Player.itemAnimationMax, Terraria.Player.lastVisualizedSelectedItem, Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Player.miscCounter, Terraria.Player.MountFishronSpecialCounter, Terraria.DataStructures.Point16.NegativeOne, Terraria.Mount.Origin, Terraria.Mount.PlayerOffset, Terraria.GameContent.TextureAssets.RenderTargets.QueenSlimeMount, Terraria.Main.rand, Terraria.Main.screenPosition, Terraria.Mount.ShouldGolfCartEmitLight(), Terraria.Mount.MountData.textureHeight, Terraria.Mount.MountData.textureWidth, Terraria.Mount.MountData.totalFrames, Terraria.Item.useStyle, Terraria.Entity.velocity, Terraria.Mount.XOffset, and Terraria.Mount.YOffset.