TModLoader: Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea
DrawInNotificationsArea()
void Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea (SpriteBatch spriteBatch, Rectangle area, ref int gamepadPointLocalIndexTouse) inline
Implements Terraria.UI.IInGameNotification.
        {
            //IL_0028: Unknown result type (might be due to invalid IL or missing references)
            //IL_004d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0052: Unknown result type (might be due to invalid IL or missing references)
            //IL_0055: Unknown result type (might be due to invalid IL or missing references)
            //IL_0056: Unknown result type (might be due to invalid IL or missing references)
            //IL_0085: Unknown result type (might be due to invalid IL or missing references)
            //IL_008f: Unknown result type (might be due to invalid IL or missing references)
            //IL_006b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0075: Unknown result type (might be due to invalid IL or missing references)
            //IL_0094: Unknown result type (might be due to invalid IL or missing references)
            //IL_0096: Unknown result type (might be due to invalid IL or missing references)
            //IL_0097: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
            //IL_011b: Unknown result type (might be due to invalid IL or missing references)
            //IL_012c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0131: Unknown result type (might be due to invalid IL or missing references)
            //IL_0138: Unknown result type (might be due to invalid IL or missing references)
            //IL_013d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0142: Unknown result type (might be due to invalid IL or missing references)
            //IL_0146: Unknown result type (might be due to invalid IL or missing references)
            //IL_0147: Unknown result type (might be due to invalid IL or missing references)
            //IL_0156: Unknown result type (might be due to invalid IL or missing references)
            //IL_0162: Unknown result type (might be due to invalid IL or missing references)
            //IL_0177: Unknown result type (might be due to invalid IL or missing references)
            //IL_018b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0192: Unknown result type (might be due to invalid IL or missing references)
            //IL_0197: Unknown result type (might be due to invalid IL or missing references)
            //IL_0209: Unknown result type (might be due to invalid IL or missing references)
            //IL_021a: Unknown result type (might be due to invalid IL or missing references)
            //IL_021f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0226: Unknown result type (might be due to invalid IL or missing references)
            //IL_022b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0230: Unknown result type (might be due to invalid IL or missing references)
            //IL_0234: Unknown result type (might be due to invalid IL or missing references)
            //IL_0235: Unknown result type (might be due to invalid IL or missing references)
            //IL_0244: Unknown result type (might be due to invalid IL or missing references)
            //IL_0250: Unknown result type (might be due to invalid IL or missing references)
            //IL_0265: Unknown result type (might be due to invalid IL or missing references)
            //IL_0279: Unknown result type (might be due to invalid IL or missing references)
            //IL_0280: Unknown result type (might be due to invalid IL or missing references)
            //IL_0285: Unknown result type (might be due to invalid IL or missing references)
            //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
            //IL_02d6: Unknown result type (might be due to invalid IL or missing references)
            //IL_02e8: Unknown result type (might be due to invalid IL or missing references)
            string userWrapperText = _request.GetUserWrapperText();
            string text = _request.UserDisplayName;
            Utils.TrimTextIfNeeded(ref text, FontAssets.MouseText.Value, 0.9f, area.Width / 4);
            string text2 = Utils.FormatWith(userWrapperText, new
            {
                DisplayName = text,
                FullId = _request.UserFullIdentifier
            });
            Vector2 mouseScreen = Main.MouseScreen;
            Color c = (((Rectangle)(ref area)).Contains(mouseScreen.ToPoint()) ? (new Color(64, 109, 164) * 0.75f) : (new Color(64, 109, 164) * 0.5f));
            Utils.DrawInvBG(spriteBatch, area, c);
            Vector2 pos = default(Vector2);
            ((Vector2)(ref pos))._002Ector((float)((Rectangle)(ref area)).Left, (float)((Rectangle)(ref area)).Center.Y);
            pos.X += 32f;
            Texture2D value = Main.Assets.Request<Texture2D>("Images/UI/ButtonPlay").Value;
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector((float)(((Rectangle)(ref area)).Left + 7), MathHelper.Lerp((float)((Rectangle)(ref area)).Top, (float)((Rectangle)(ref area)).Bottom, 0.5f) - (float)(value.Height / 2) - 1f);
            Rectangle val = Utils.CenteredRectangle(vector + new Vector2((float)(value.Width / 2), 0f), value.Size());
            bool flag = ((Rectangle)(ref val)).Contains(mouseScreen.ToPoint());
            spriteBatch.Draw(value, vector, (Rectangle?)null, Color.White * (flag ? 1f : 0.5f), 0f, new Vector2(0f, 0.5f) * value.Size(), 1f, (SpriteEffects)0, 0f);
            if (flag)
            {
                OnMouseOver();
            }
            value = Main.Assets.Request<Texture2D>("Images/UI/ButtonDelete").Value;
            ((Vector2)(ref vector))._002Ector((float)(((Rectangle)(ref area)).Left + 7), MathHelper.Lerp((float)((Rectangle)(ref area)).Top, (float)((Rectangle)(ref area)).Bottom, 0.5f) + (float)(value.Height / 2) + 1f);
            val = Utils.CenteredRectangle(vector + new Vector2((float)(value.Width / 2), 0f), value.Size());
            flag = ((Rectangle)(ref val)).Contains(mouseScreen.ToPoint());
            spriteBatch.Draw(value, vector, (Rectangle?)null, Color.White * (flag ? 1f : 0.5f), 0f, new Vector2(0f, 0.5f) * value.Size(), 1f, (SpriteEffects)0, 0f);
            if (flag)
            {
                OnMouseOver(reject: true);
            }
            pos.X += 6f;
            Color color = default(Color);
            ((Color)(ref color))._002Ector((int)Main.mouseTextColor, (int)Main.mouseTextColor, Main.mouseTextColor / 5, (int)Main.mouseTextColor);
            Utils.DrawBorderString(spriteBatch, text2, pos, color, 0.9f, 0f, 0.4f);
        }
References Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup._request, Terraria.Main.Assets, Terraria.Utils.CenteredRectangle(), Terraria.Utils.DrawBorderString(), Terraria.Utils.DrawInvBG(), Terraria.Utils.FormatWith(), Terraria.Social.Base.UserJoinToServerRequest.GetUserWrapperText(), Terraria.Main.MouseScreen, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.OnMouseOver(), Terraria.Utils.TrimTextIfNeeded(), and Terraria.Social.Base.UserJoinToServerRequest.UserDisplayName.