TModLoader: Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame
DrawInGame()
void Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame (SpriteBatch spriteBatch, Vector2 bottomAnchorPosition) inline
Implements Terraria.UI.IInGameNotification.
Definition at line 264 of file InGamePopups.cs.
        {
            //IL_0056: Unknown result type (might be due to invalid IL or missing references)
            //IL_0065: Unknown result type (might be due to invalid IL or missing references)
            //IL_006a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0070: Unknown result type (might be due to invalid IL or missing references)
            //IL_0075: Unknown result type (might be due to invalid IL or missing references)
            //IL_0076: Unknown result type (might be due to invalid IL or missing references)
            //IL_0081: Unknown result type (might be due to invalid IL or missing references)
            //IL_008e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0093: Unknown result type (might be due to invalid IL or missing references)
            //IL_0098: Unknown result type (might be due to invalid IL or missing references)
            //IL_0099: Unknown result type (might be due to invalid IL or missing references)
            //IL_009e: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
            //IL_00da: Unknown result type (might be due to invalid IL or missing references)
            //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
            //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
            //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
            //IL_0101: Unknown result type (might be due to invalid IL or missing references)
            //IL_0173: Unknown result type (might be due to invalid IL or missing references)
            //IL_0184: Unknown result type (might be due to invalid IL or missing references)
            //IL_0189: Unknown result type (might be due to invalid IL or missing references)
            //IL_0190: Unknown result type (might be due to invalid IL or missing references)
            //IL_0195: Unknown result type (might be due to invalid IL or missing references)
            //IL_019a: Unknown result type (might be due to invalid IL or missing references)
            //IL_019e: Unknown result type (might be due to invalid IL or missing references)
            //IL_01a0: Unknown result type (might be due to invalid IL or missing references)
            //IL_01af: Unknown result type (might be due to invalid IL or missing references)
            //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
            //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e4: Unknown result type (might be due to invalid IL or missing references)
            //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
            //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
            //IL_0262: Unknown result type (might be due to invalid IL or missing references)
            //IL_0273: Unknown result type (might be due to invalid IL or missing references)
            //IL_0278: Unknown result type (might be due to invalid IL or missing references)
            //IL_027f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0284: Unknown result type (might be due to invalid IL or missing references)
            //IL_0289: Unknown result type (might be due to invalid IL or missing references)
            //IL_028d: Unknown result type (might be due to invalid IL or missing references)
            //IL_028f: Unknown result type (might be due to invalid IL or missing references)
            //IL_029e: Unknown result type (might be due to invalid IL or missing references)
            //IL_02aa: Unknown result type (might be due to invalid IL or missing references)
            //IL_02bf: Unknown result type (might be due to invalid IL or missing references)
            //IL_02d3: Unknown result type (might be due to invalid IL or missing references)
            //IL_02da: Unknown result type (might be due to invalid IL or missing references)
            //IL_02df: Unknown result type (might be due to invalid IL or missing references)
            //IL_0315: Unknown result type (might be due to invalid IL or missing references)
            //IL_031b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0320: Unknown result type (might be due to invalid IL or missing references)
            //IL_0326: Unknown result type (might be due to invalid IL or missing references)
            //IL_032b: Unknown result type (might be due to invalid IL or missing references)
            //IL_033a: Unknown result type (might be due to invalid IL or missing references)
            //IL_033f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0344: Unknown result type (might be due to invalid IL or missing references)
            //IL_0358: Unknown result type (might be due to invalid IL or missing references)
            float opacity = Opacity;
            if (opacity > 0f)
            {
                string text = Utils.FormatWith(_request.GetUserWrapperText(), new
                {
                    DisplayName = _request.UserDisplayName,
                    FullId = _request.UserFullIdentifier
                });
                float num = Scale * 1.1f;
                Vector2 size = (FontAssets.ItemStack.Value.MeasureString(text) + new Vector2(58f, 10f)) * num;
                Rectangle r = Utils.CenteredRectangle(bottomAnchorPosition + new Vector2(0f, (0f - size.Y) * 0.5f), size);
                Vector2 mouseScreen = Main.MouseScreen;
                Color c = (((Rectangle)(ref r)).Contains(mouseScreen.ToPoint()) ? (new Color(64, 109, 164) * 0.75f) : (new Color(64, 109, 164) * 0.5f));
                Utils.DrawInvBG(spriteBatch, r, c);
                Vector2 vector = default(Vector2);
                ((Vector2)(ref vector))._002Ector((float)((Rectangle)(ref r)).Left, (float)((Rectangle)(ref r)).Center.Y);
                vector.X += 32f;
                Texture2D value = Main.Assets.Request<Texture2D>("Images/UI/ButtonPlay").Value;
                Vector2 vector2 = default(Vector2);
                ((Vector2)(ref vector2))._002Ector((float)(((Rectangle)(ref r)).Left + 7), MathHelper.Lerp((float)((Rectangle)(ref r)).Top, (float)((Rectangle)(ref r)).Bottom, 0.5f) - (float)(value.Height / 2) - 1f);
                Rectangle val = Utils.CenteredRectangle(vector2 + new Vector2((float)(value.Width / 2), 0f), value.Size());
                bool flag = ((Rectangle)(ref val)).Contains(mouseScreen.ToPoint());
                spriteBatch.Draw(value, vector2, (Rectangle?)null, Color.White * (flag ? 1f : 0.5f), 0f, new Vector2(0f, 0.5f) * value.Size(), 1f, (SpriteEffects)0, 0f);
                if (flag)
                {
                    OnMouseOver();
                }
                value = Main.Assets.Request<Texture2D>("Images/UI/ButtonDelete").Value;
                ((Vector2)(ref vector2))._002Ector((float)(((Rectangle)(ref r)).Left + 7), MathHelper.Lerp((float)((Rectangle)(ref r)).Top, (float)((Rectangle)(ref r)).Bottom, 0.5f) + (float)(value.Height / 2) + 1f);
                val = Utils.CenteredRectangle(vector2 + new Vector2((float)(value.Width / 2), 0f), value.Size());
                flag = ((Rectangle)(ref val)).Contains(mouseScreen.ToPoint());
                spriteBatch.Draw(value, vector2, (Rectangle?)null, Color.White * (flag ? 1f : 0.5f), 0f, new Vector2(0f, 0.5f) * value.Size(), 1f, (SpriteEffects)0, 0f);
                if (flag)
                {
                    OnMouseOver(reject: true);
                }
                Color color = new Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, Main.mouseTextColor / 5, (int)Main.mouseTextColor) * opacity;
                Utils.DrawBorderString(spriteBatch, text, ((Rectangle)(ref r)).Center.ToVector2() + new Vector2(10f, 0f), color, num * 0.9f, 0.5f, 0.4f);
            }
        }
References Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup._request, Terraria.Main.Assets, Terraria.Utils.CenteredRectangle(), Terraria.Utils.DrawBorderString(), Terraria.Utils.DrawInvBG(), Terraria.Utils.FormatWith(), Terraria.Social.Base.UserJoinToServerRequest.GetUserWrapperText(), Terraria.GameContent.FontAssets.ItemStack, Terraria.Main.MouseScreen, Terraria.Main.mouseTextColor, Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.OnMouseOver(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.Opacity, and Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.Scale.