TModLoader: Terraria.GameContent.Creative.CreativeUI.SacrificeItem
SacrificeItem() [3/3]
static ItemSacrificeResult Terraria.GameContent.Creative.CreativeUI.SacrificeItem (ref Item item, out int amountWeSacrificed, bool returnRemainderToPlayer = false) inline static
    {
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        int amountNeededTotal = 0;
        int amountWeHave = 0;
        amountWeSacrificed = 0;
        if (!ItemLoader.CanResearch(item))
        {
            return ItemSacrificeResult.CannotSacrifice;
        }
        if (!Main.LocalPlayerCreativeTracker.ItemSacrifices.TryGetSacrificeNumbers(item.type, out amountWeHave, out amountNeededTotal))
        {
            return ItemSacrificeResult.CannotSacrifice;
        }
        int num = Utils.Clamp(amountNeededTotal - amountWeHave, 0, amountNeededTotal);
        if (num == 0)
        {
            return ItemSacrificeResult.CannotSacrifice;
        }
        int num2 = Math.Min(num, item.stack);
        if (!Main.ServerSideCharacter)
        {
            Main.LocalPlayerCreativeTracker.ItemSacrifices.RegisterItemSacrifice(item.type, num2);
        }
        else
        {
            NetPacket packet = NetCreativeUnlocksPlayerReportModule.SerializeSacrificeRequest(item.type, num2);
            NetManager.Instance.SendToServerOrLoopback(packet);
        }
        bool num3 = num2 == num;
        ItemLoader.OnResearched(item, num3);
        item.stack -= num2;
        if (item.stack <= 0)
        {
            item.TurnToAir();
        }
        amountWeSacrificed = num2;
        Main.CreativeMenu.RefreshAvailableInfiniteItemsList();
        if (item.stack > 0 && returnRemainderToPlayer)
        {
            item.position.X = Main.player[Main.myPlayer].Center.X - (float)(item.width / 2);
            item.position.Y = Main.player[Main.myPlayer].Center.Y - (float)(item.height / 2);
            item = Main.LocalPlayer.GetItem(Main.myPlayer, item, GetItemSettings.InventoryUIToInventorySettings);
        }
        if (!num3)
        {
            return ItemSacrificeResult.SacrificedButNotDone;
        }
        return ItemSacrificeResult.SacrificedAndDone;
    }
References Terraria.ModLoader.ItemLoader.CanResearch(), Terraria.Main.CreativeMenu, Terraria.Net.NetManager.Instance, Terraria.GetItemSettings.InventoryUIToInventorySettings, Terraria.Main.LocalPlayer, Terraria.Main.LocalPlayerCreativeTracker, Terraria.Main.myPlayer, Terraria.ModLoader.ItemLoader.OnResearched(), Terraria.Main.player, Terraria.GameContent.NetModules.NetCreativeUnlocksPlayerReportModule.SerializeSacrificeRequest(), and Terraria.Main.ServerSideCharacter.