TModLoader: Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.UpdateInstallState
UpdateInstallState()
void Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.UpdateInstallState () inline package
Definition at line 84 of file ModDownloadItem.cs.
    {
        Installed = Interface.modBrowser.SocialBackend.IsItemInstalled(ModName);
        NeedUpdate = Installed != null && Interface.modBrowser.SocialBackend.DoesItemNeedUpdate(PublishId, Installed, Version);
        AppNeedRestartToReinstall = Installed == null && Interface.modBrowser.SocialBackend.DoesAppNeedRestartToReinstallItem(PublishId);
    }
References Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.AppNeedRestartToReinstall, Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.Installed, Terraria.ModLoader.UI.Interface.modBrowser, Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.ModName, Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.NeedUpdate, and Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.PublishId.
Referenced by Terraria.ModLoader.UI.ModBrowser.UIModBrowser.CheckIfAnyModUpdateIsAvailable(), Terraria.Social.Steam.WorkshopBrowserModule.DownloadItem(), Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.NeedsInstallOrUpdate(), and Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.QueryItemsSynchronously().