TModLoader: Terraria.ModLoader.MapLoader.ModMapOption
ModMapOption()
static void Terraria.ModLoader.MapLoader.ModMapOption (ref ushort mapType, int i, int j) inline static package
Definition at line 109 of file MapLoader.cs.
    {
        if (entryToTile.ContainsKey(mapType))
        {
            ModTile tile = TileLoader.GetTile(entryToTile[mapType]);
            ushort option = tile.GetMapOption(i, j);
            if (option < 0 || option >= modTileOptions(tile.Type))
            {
                throw new ArgumentOutOfRangeException("Bad map option for tile " + tile.Name + " from mod " + tile.Mod.Name);
            }
            mapType += option;
        }
        else if (entryToWall.ContainsKey(mapType))
        {
            ModWall wall = WallLoader.GetWall(entryToWall[mapType]);
            ushort option2 = wall.GetMapOption(i, j);
            if (option2 < 0 || option2 >= modWallOptions(wall.Type))
            {
                throw new ArgumentOutOfRangeException("Bad map option for wall " + wall.Name + " from mod " + wall.Mod.Name);
            }
            mapType += option2;
        }
    }
References Terraria.ModLoader.MapLoader.entryToTile, Terraria.ModLoader.MapLoader.entryToWall, Terraria.ModLoader.ModBlockType.GetMapOption(), Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.WallLoader.GetWall(), Terraria.ModLoader.ModType< TEntity, TModType >.Mod, Terraria.ModLoader.MapLoader.modTileOptions(), Terraria.ModLoader.MapLoader.modWallOptions(), Terraria.ModLoader.Mod.Name, Terraria.ModLoader.ModType< TEntity, TModType >.Name, and Terraria.ModLoader.ModBlockType.Type.
Referenced by Terraria.Map.MapHelper.CreateMapTile().