TModLoader: Terraria.MonoLaunch.Main
Main()
static void Terraria.MonoLaunch.Main (string[] args) inline static private
Definition at line 43 of file MonoLaunch.cs.
    {
        int i = Array.IndexOf(args, "-tModPorter");
        if (i >= 0)
        {
            Program.Main(args.Skip(i + 1).ToArray()).GetAwaiter().GetResult();
            return;
        }
        Thread.CurrentThread.Name = "Entry Thread";
        NativeLibraries.SetNativeLibraryPath(NativesDir);
        AssemblyLoadContext.Default.ResolvingUnmanagedDll += ResolveNativeLibrary;
        Environment.SetEnvironmentVariable("FNA_WORKAROUND_WINDOW_RESIZABLE", "1");
        if (File.Exists("cli-argsConfig.txt"))
        {
            args = args.Concat(File.ReadAllLines("cli-argsConfig.txt").SelectMany((string a) => a.Split(" ", 2))).ToArray();
        }
        if (File.Exists("env-argsConfig.txt"))
        {
            foreach (string[] environmentVar in from text in File.ReadAllLines("env-argsConfig.txt")
                select text.Split("=") into envVar
                where envVar.Length == 2
                select envVar)
            {
                Environment.SetEnvironmentVariable(environmentVar[0], environmentVar[1]);
            }
        }
        Action LocalLaunchGame = delegate
        {
            Main_End(args);
        };
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            new Thread(LocalLaunchGame.Invoke).Start();
            Thread.CurrentThread.IsBackground = true;
        }
        else
        {
            LocalLaunchGame();
        }
    }
References Terraria.ModLoader.Environment, Terraria.MonoLaunch.Main_End(), Terraria.MonoLaunch.NativesDir, Terraria.MonoLaunch.ResolveNativeLibrary(), and Terraria.ModLoader.Engine.NativeLibraries.SetNativeLibraryPath().