TModLoader: Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar
DrawFancyBar() [2/2]
static void Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar (SpriteBatch spriteBatch, float lifeAmount, float lifeMax, Texture2D barIconTexture, Rectangle barIconFrame, float shieldCurrent, float shieldMax) inline static
    {
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_012e: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_021a: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_023d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0248: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_025c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0261: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_027a: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0280: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        //IL_0287: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        //IL_028e: Unknown result type (might be due to invalid IL or missing references)
        //IL_028f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0294: Unknown result type (might be due to invalid IL or missing references)
        //IL_0299: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        //IL_029f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0303: Unknown result type (might be due to invalid IL or missing references)
        //IL_0305: Unknown result type (might be due to invalid IL or missing references)
        //IL_0314: Unknown result type (might be due to invalid IL or missing references)
        //IL_0319: Unknown result type (might be due to invalid IL or missing references)
        //IL_031e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0325: Unknown result type (might be due to invalid IL or missing references)
        //IL_032f: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0414: Unknown result type (might be due to invalid IL or missing references)
        //IL_0419: Unknown result type (might be due to invalid IL or missing references)
        //IL_041b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0425: Unknown result type (might be due to invalid IL or missing references)
        //IL_042a: Unknown result type (might be due to invalid IL or missing references)
        //IL_042f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0433: Unknown result type (might be due to invalid IL or missing references)
        //IL_0435: Unknown result type (might be due to invalid IL or missing references)
        //IL_0437: Unknown result type (might be due to invalid IL or missing references)
        //IL_043c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0443: Unknown result type (might be due to invalid IL or missing references)
        //IL_044d: Unknown result type (might be due to invalid IL or missing references)
        //IL_044f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0459: Unknown result type (might be due to invalid IL or missing references)
        //IL_0352: Unknown result type (might be due to invalid IL or missing references)
        //IL_0354: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_0360: Unknown result type (might be due to invalid IL or missing references)
        //IL_036a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0371: Unknown result type (might be due to invalid IL or missing references)
        //IL_037f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0391: Unknown result type (might be due to invalid IL or missing references)
        //IL_0393: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_048c: Unknown result type (might be due to invalid IL or missing references)
        //IL_047f: Unknown result type (might be due to invalid IL or missing references)
        Texture2D value = Main.Assets.Request<Texture2D>("Images/UI/UI_BossBar").Value;
        if (BossBarLoader.drawingInfo.HasValue)
        {
            BigProgressBarInfo info = BossBarLoader.drawingInfo.Value;
            BossBarLoader.drawingInfo = null;
            Vector2 barCenter = Main.ScreenSize.ToVector2() * new Vector2(0.5f, 1f) + new Vector2(0f, -50f);
            Color iconColor = Color.White;
            float iconScale = 1f;
            BossBarDrawParams drawParams = new BossBarDrawParams(value, barCenter, barIconTexture, barIconFrame, iconColor, lifeAmount, lifeMax, shieldCurrent, shieldMax, iconScale, info.showText, Vector2.Zero);
            if (BossBarLoader.PreDraw(spriteBatch, info, ref drawParams))
            {
                BossBarLoader.DrawFancyBar_TML(spriteBatch, drawParams);
            }
            BossBarLoader.PostDraw(spriteBatch, info, drawParams);
            return;
        }
        Point p = default(Point);
        ((Point)(ref p))._002Ector(456, 22);
        Point p2 = default(Point);
        ((Point)(ref p2))._002Ector(32, 24);
        int verticalFrames = 6;
        Rectangle value2 = value.Frame(1, verticalFrames, 0, 3);
        Color color = Color.White * 0.2f;
        float num = lifeAmount / lifeMax;
        int num2 = (int)((float)p.X * num);
        num2 -= num2 % 2;
        Rectangle value3 = value.Frame(1, verticalFrames, 0, 2);
        value3.X += p2.X;
        value3.Y += p2.Y;
        value3.Width = 2;
        value3.Height = p.Y;
        Rectangle value4 = value.Frame(1, verticalFrames, 0, 1);
        value4.X += p2.X;
        value4.Y += p2.Y;
        value4.Width = 2;
        value4.Height = p.Y;
        float num3 = shieldCurrent / shieldMax;
        int num4 = (int)((float)p.X * num3);
        num4 -= num4 % 2;
        Rectangle value5 = value.Frame(1, verticalFrames, 0, 5);
        value5.X += p2.X;
        value5.Y += p2.Y;
        value5.Width = 2;
        value5.Height = p.Y;
        Rectangle value6 = value.Frame(1, verticalFrames, 0, 4);
        value6.X += p2.X;
        value6.Y += p2.Y;
        value6.Width = 2;
        value6.Height = p.Y;
        Rectangle rectangle = Utils.CenteredRectangle(Main.ScreenSize.ToVector2() * new Vector2(0.5f, 1f) + new Vector2(0f, -50f), p.ToVector2());
        Vector2 vector = rectangle.TopLeft() - p2.ToVector2();
        spriteBatch.Draw(value, vector, (Rectangle?)value2, color, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
        spriteBatch.Draw(value, rectangle.TopLeft(), (Rectangle?)value3, Color.White, 0f, Vector2.Zero, new Vector2((float)(num2 / value3.Width), 1f), (SpriteEffects)0, 0f);
        spriteBatch.Draw(value, rectangle.TopLeft() + new Vector2((float)(num2 - 2), 0f), (Rectangle?)value4, Color.White, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
        if (!(shieldMax <= 0f))
        {
            spriteBatch.Draw(value, rectangle.TopLeft(), (Rectangle?)value5, Color.White, 0f, Vector2.Zero, new Vector2((float)(num4 / value5.Width), 1f), (SpriteEffects)0, 0f);
            spriteBatch.Draw(value, rectangle.TopLeft() + new Vector2((float)(num4 - 2), 0f), (Rectangle?)value6, Color.White, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
        }
        Rectangle value7 = value.Frame(1, verticalFrames);
        spriteBatch.Draw(value, vector, (Rectangle?)value7, Color.White, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
        Vector2 vector2 = new Vector2(4f, 20f) + barIconFrame.Size() / 2f;
        spriteBatch.Draw(barIconTexture, vector + vector2, (Rectangle?)barIconFrame, Color.White, 0f, barIconFrame.Size() / 2f, 1f, (SpriteEffects)0, 0f);
        if (BigProgressBarSystem.ShowText)
        {
            if (shieldCurrent > 0f)
            {
                DrawHealthText(spriteBatch, rectangle, shieldCurrent, shieldMax);
            }
            else
            {
                DrawHealthText(spriteBatch, rectangle, lifeAmount, lifeMax);
            }
        }
    }
References Terraria.Main.Assets, Terraria.Utils.CenteredRectangle(), Terraria.ModLoader.BossBarLoader.DrawFancyBar_TML(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawHealthText(), Terraria.ModLoader.BossBarLoader.drawingInfo, Terraria.ModLoader.BossBarLoader.PostDraw(), Terraria.ModLoader.BossBarLoader.PreDraw(), Terraria.Main.ScreenSize, and Terraria.GameContent.UI.BigProgressBar.BigProgressBarSystem.ShowText.