TModLoader: Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar
DrawFancyBar() [1/2]
static void Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar (SpriteBatch spriteBatch, float lifeAmount, float lifeMax, Texture2D barIconTexture, Rectangle barIconFrame) inline static
Definition at line 54 of file BigProgressBarHelper.cs.
    {
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0174: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_021e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0222: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_0254: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0272: Unknown result type (might be due to invalid IL or missing references)
        //IL_0277: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_027d: Unknown result type (might be due to invalid IL or missing references)
        //IL_027f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0295: Unknown result type (might be due to invalid IL or missing references)
        //IL_0297: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        if (BossBarLoader.drawingInfo.HasValue)
        {
            DrawFancyBar(spriteBatch, lifeAmount, lifeMax, barIconTexture, barIconFrame, 0f, 0f);
            return;
        }
        Texture2D value = Main.Assets.Request<Texture2D>("Images/UI/UI_BossBar").Value;
        Point p = default(Point);
        ((Point)(ref p))._002Ector(456, 22);
        Point p2 = default(Point);
        ((Point)(ref p2))._002Ector(32, 24);
        int verticalFrames = 6;
        Rectangle value2 = value.Frame(1, verticalFrames, 0, 3);
        Color color = Color.White * 0.2f;
        float num = lifeAmount / lifeMax;
        int num2 = (int)((float)p.X * num);
        num2 -= num2 % 2;
        Rectangle value3 = value.Frame(1, verticalFrames, 0, 2);
        value3.X += p2.X;
        value3.Y += p2.Y;
        value3.Width = 2;
        value3.Height = p.Y;
        Rectangle value4 = value.Frame(1, verticalFrames, 0, 1);
        value4.X += p2.X;
        value4.Y += p2.Y;
        value4.Width = 2;
        value4.Height = p.Y;
        Rectangle rectangle = Utils.CenteredRectangle(Main.ScreenSize.ToVector2() * new Vector2(0.5f, 1f) + new Vector2(0f, -50f), p.ToVector2());
        Vector2 vector = rectangle.TopLeft() - p2.ToVector2();
        spriteBatch.Draw(value, vector, (Rectangle?)value2, color, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
        spriteBatch.Draw(value, rectangle.TopLeft(), (Rectangle?)value3, Color.White, 0f, Vector2.Zero, new Vector2((float)(num2 / value3.Width), 1f), (SpriteEffects)0, 0f);
        spriteBatch.Draw(value, rectangle.TopLeft() + new Vector2((float)(num2 - 2), 0f), (Rectangle?)value4, Color.White, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
        Rectangle value5 = value.Frame(1, verticalFrames);
        spriteBatch.Draw(value, vector, (Rectangle?)value5, Color.White, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
        Vector2 vector2 = new Vector2(4f, 20f) + new Vector2(26f, 28f) / 2f;
        spriteBatch.Draw(barIconTexture, vector + vector2, (Rectangle?)barIconFrame, Color.White, 0f, barIconFrame.Size() / 2f, 1f, (SpriteEffects)0, 0f);
        if (BigProgressBarSystem.ShowText)
        {
            DrawHealthText(spriteBatch, rectangle, lifeAmount, lifeMax);
        }
    }
References Terraria.Main.Assets, Terraria.Utils.CenteredRectangle(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawHealthText(), Terraria.ModLoader.BossBarLoader.drawingInfo, Terraria.Main.ScreenSize, and Terraria.GameContent.UI.BigProgressBar.BigProgressBarSystem.ShowText.
Referenced by Terraria.GameContent.UI.BigProgressBar.BrainOfCthuluBigProgressBar.Draw(), Terraria.GameContent.UI.BigProgressBar.CommonBossBigProgressBar.Draw(), Terraria.GameContent.UI.BigProgressBar.DeerclopsBigProgressBar.Draw(), Terraria.GameContent.UI.BigProgressBar.EaterOfWorldsProgressBar.Draw(), Terraria.GameContent.UI.BigProgressBar.GolemHeadProgressBar.Draw(), Terraria.GameContent.UI.BigProgressBar.LunarPillarBigProgessBar.Draw(), Terraria.GameContent.UI.BigProgressBar.MartianSaucerBigProgressBar.Draw(), Terraria.GameContent.UI.BigProgressBar.MoonLordProgressBar.Draw(), Terraria.GameContent.UI.BigProgressBar.PirateShipBigProgressBar.Draw(), Terraria.GameContent.UI.BigProgressBar.TwinsBigProgressBar.Draw(), Terraria.ModLoader.ModBossBar.Draw(), and Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar().