TModLoader: Terraria.GameContent.UI.States.UIWorldCreation.AddWorldDifficultyOptions
AddWorldDifficultyOptions()
void Terraria.GameContent.UI.States.UIWorldCreation.AddWorldDifficultyOptions (UIElement container, float accumualtedHeight, MouseEvent clickEvent, string tagGroup, float usableWidthPercent) inline private
    {
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        WorldDifficultyId[] array = new WorldDifficultyId[4]
        {
            WorldDifficultyId.Creative,
            WorldDifficultyId.Normal,
            WorldDifficultyId.Expert,
            WorldDifficultyId.Master
        };
        LocalizedText[] array2 = new LocalizedText[4]
        {
            Language.GetText("UI.Creative"),
            Language.GetText("UI.Normal"),
            Language.GetText("UI.Expert"),
            Language.GetText("UI.Master")
        };
        LocalizedText[] array3 = new LocalizedText[4]
        {
            Language.GetText("UI.WorldDescriptionCreative"),
            Language.GetText("UI.WorldDescriptionNormal"),
            Language.GetText("UI.WorldDescriptionExpert"),
            Language.GetText("UI.WorldDescriptionMaster")
        };
        Color[] array4 = (Color[])(object)new Color[4]
        {
            Main.creativeModeColor,
            Color.White,
            Main.mcColor,
            Main.hcColor
        };
        string[] array5 = new string[4] { "Images/UI/WorldCreation/IconDifficultyCreative", "Images/UI/WorldCreation/IconDifficultyNormal", "Images/UI/WorldCreation/IconDifficultyExpert", "Images/UI/WorldCreation/IconDifficultyMaster" };
        GroupOptionButton<WorldDifficultyId>[] array6 = new GroupOptionButton<WorldDifficultyId>[array.Length];
        for (int i = 0; i < array6.Length; i++)
        {
            GroupOptionButton<WorldDifficultyId> groupOptionButton = new GroupOptionButton<WorldDifficultyId>(array[i], array2[i], array3[i], array4[i], array5[i], 1f, 1f, 16f);
            groupOptionButton.Width = StyleDimension.FromPixelsAndPercent(-1 * (array6.Length - 1), 1f / (float)array6.Length * usableWidthPercent);
            groupOptionButton.Left = StyleDimension.FromPercent(1f - usableWidthPercent);
            groupOptionButton.HAlign = (float)i / (float)(array6.Length - 1);
            groupOptionButton.Top.Set(accumualtedHeight, 0f);
            groupOptionButton.OnLeftMouseDown += clickEvent;
            groupOptionButton.OnMouseOver += ShowOptionDescription;
            groupOptionButton.OnMouseOut += ClearOptionDescription;
            groupOptionButton.SetSnapPoint(tagGroup, i);
            container.Append(groupOptionButton);
            array6[i] = groupOptionButton;
        }
        _difficultyButtons = array6;
    }
References Terraria.GameContent.UI.States.UIWorldCreation._difficultyButtons, Terraria.GameContent.UI.States.UIWorldCreation.ClearOptionDescription(), Terraria.Main.creativeModeColor, Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.Main.mcColor, and Terraria.GameContent.UI.States.UIWorldCreation.ShowOptionDescription().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu().