TModLoader: Terraria.GameContent.UI.States.UIWorldCreation.AddWorldEvilOptions
AddWorldEvilOptions()
void Terraria.GameContent.UI.States.UIWorldCreation.AddWorldEvilOptions (UIElement container, float accumualtedHeight, MouseEvent clickEvent, string tagGroup, float usableWidthPercent) inline private
Definition at line 409 of file UIWorldCreation.cs.
    {
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        WorldEvilId[] array = new WorldEvilId[3]
        {
            WorldEvilId.Random,
            WorldEvilId.Corruption,
            WorldEvilId.Crimson
        };
        LocalizedText[] array2 = new LocalizedText[3]
        {
            Lang.misc[103],
            Lang.misc[101],
            Lang.misc[102]
        };
        LocalizedText[] array3 = new LocalizedText[3]
        {
            Language.GetText("UI.WorldDescriptionEvilRandom"),
            Language.GetText("UI.WorldDescriptionEvilCorrupt"),
            Language.GetText("UI.WorldDescriptionEvilCrimson")
        };
        Color[] array4 = (Color[])(object)new Color[3]
        {
            Color.White,
            Color.MediumPurple,
            Color.IndianRed
        };
        string[] array5 = new string[3] { "Images/UI/WorldCreation/IconEvilRandom", "Images/UI/WorldCreation/IconEvilCorruption", "Images/UI/WorldCreation/IconEvilCrimson" };
        GroupOptionButton<WorldEvilId>[] array6 = new GroupOptionButton<WorldEvilId>[array.Length];
        for (int i = 0; i < array6.Length; i++)
        {
            GroupOptionButton<WorldEvilId> groupOptionButton = new GroupOptionButton<WorldEvilId>(array[i], array2[i], array3[i], array4[i], array5[i], 1f, 1f, 16f);
            groupOptionButton.Width = StyleDimension.FromPixelsAndPercent(-4 * (array6.Length - 1), 1f / (float)array6.Length * usableWidthPercent);
            groupOptionButton.Left = StyleDimension.FromPercent(1f - usableWidthPercent);
            groupOptionButton.HAlign = (float)i / (float)(array6.Length - 1);
            groupOptionButton.Top.Set(accumualtedHeight, 0f);
            groupOptionButton.OnLeftMouseDown += clickEvent;
            groupOptionButton.OnMouseOver += ShowOptionDescription;
            groupOptionButton.OnMouseOut += ClearOptionDescription;
            groupOptionButton.SetSnapPoint(tagGroup, i);
            container.Append(groupOptionButton);
            array6[i] = groupOptionButton;
        }
        _evilButtons = array6;
    }
References Terraria.GameContent.UI.States.UIWorldCreation._evilButtons, Terraria.GameContent.UI.States.UIWorldCreation.ClearOptionDescription(), Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.Lang.misc, and Terraria.GameContent.UI.States.UIWorldCreation.ShowOptionDescription().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu().