TModLoader: Terraria.GameContent.UI.States.UIWorldCreation.ProcessSeed
ProcessSeed()
void Terraria.GameContent.UI.States.UIWorldCreation.ProcessSeed (out string processedSeed) inline private
    {
        processedSeed = _optionSeed;
        ProcessSpecialWorldSeeds(processedSeed);
        string[] array = _optionSeed.Split('.');
        if (array.Length != 4)
        {
            return;
        }
        if (int.TryParse(array[0], out var result))
        {
            switch (result)
            {
            case 1:
                _optionSize = WorldSizeId.Small;
                break;
            case 2:
                _optionSize = WorldSizeId.Medium;
                break;
            case 3:
                _optionSize = WorldSizeId.Large;
                break;
            }
        }
        if (int.TryParse(array[1], out result))
        {
            switch (result)
            {
            case 1:
                _optionDifficulty = WorldDifficultyId.Normal;
                break;
            case 2:
                _optionDifficulty = WorldDifficultyId.Expert;
                break;
            case 3:
                _optionDifficulty = WorldDifficultyId.Master;
                break;
            case 4:
                _optionDifficulty = WorldDifficultyId.Creative;
                break;
            }
        }
        if (int.TryParse(array[2], out result))
        {
            switch (result)
            {
            case 1:
                _optionEvil = WorldEvilId.Corruption;
                break;
            case 2:
                _optionEvil = WorldEvilId.Crimson;
                break;
            }
        }
        processedSeed = array[3];
    }
References Terraria.GameContent.UI.States.UIWorldCreation._optionDifficulty, Terraria.GameContent.UI.States.UIWorldCreation._optionEvil, Terraria.GameContent.UI.States.UIWorldCreation._optionSeed, Terraria.GameContent.UI.States.UIWorldCreation._optionSize, and Terraria.GameContent.UI.States.UIWorldCreation.ProcessSpecialWorldSeeds().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.FinishCreatingWorld(), and Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingSeed().