TModLoader: Terraria.GameContent.UI.States.UIWorldCreation.SetDefaultOptions
SetDefaultOptions()
void Terraria.GameContent.UI.States.UIWorldCreation.SetDefaultOptions () inline private
Definition at line 229 of file UIWorldCreation.cs.
    {
        AssignRandomWorldName();
        AssignRandomWorldSeed();
        UpdateInputFields();
        GroupOptionButton<WorldSizeId>[] sizeButtons = _sizeButtons;
        for (int l = 0; l < sizeButtons.Length; l++)
        {
            sizeButtons[l].SetCurrentOption(WorldSizeId.Medium);
        }
        _optionSize = WorldSizeId.Medium;
        if (Main.ActivePlayerFileData.Player.difficulty == 3)
        {
            GroupOptionButton<WorldDifficultyId>[] difficultyButtons = _difficultyButtons;
            for (int j = 0; j < difficultyButtons.Length; j++)
            {
                difficultyButtons[j].SetCurrentOption(WorldDifficultyId.Creative);
            }
            _optionDifficulty = WorldDifficultyId.Creative;
            UpdatePreviewPlate();
        }
        else
        {
            GroupOptionButton<WorldDifficultyId>[] difficultyButtons2 = _difficultyButtons;
            for (int k = 0; k < difficultyButtons2.Length; k++)
            {
                difficultyButtons2[k].SetCurrentOption(WorldDifficultyId.Normal);
            }
        }
        GroupOptionButton<WorldEvilId>[] evilButtons = _evilButtons;
        for (int i = 0; i < evilButtons.Length; i++)
        {
            evilButtons[i].SetCurrentOption(WorldEvilId.Random);
        }
    }
References Terraria.GameContent.UI.States.UIWorldCreation._difficultyButtons, Terraria.GameContent.UI.States.UIWorldCreation._evilButtons, Terraria.GameContent.UI.States.UIWorldCreation._optionDifficulty, Terraria.GameContent.UI.States.UIWorldCreation._optionSize, Terraria.GameContent.UI.States.UIWorldCreation._sizeButtons, Terraria.Main.ActivePlayerFileData, Terraria.GameContent.UI.States.UIWorldCreation.AssignRandomWorldName(), Terraria.GameContent.UI.States.UIWorldCreation.AssignRandomWorldSeed(), Terraria.Player.difficulty, Terraria.IO.PlayerFileData.Player, Terraria.GameContent.UI.States.UIWorldCreation.UpdateInputFields(), and Terraria.GameContent.UI.States.UIWorldCreation.UpdatePreviewPlate().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu().