TModLoader: Terraria.GameContent.UI.States.UIWorldCreation.AssignRandomWorldName
AssignRandomWorldName()
void Terraria.GameContent.UI.States.UIWorldCreation.AssignRandomWorldName () inline private
Definition at line 867 of file UIWorldCreation.cs.
    {
        do
        {
            LocalizedText localizedText = Language.SelectRandom(Lang.CreateDialogFilter("RandomWorldName_Composition."));
            LocalizedText localizedText4 = Language.SelectRandom(Lang.CreateDialogFilter("RandomWorldName_Adjective."));
            LocalizedText localizedText2 = Language.SelectRandom(Lang.CreateDialogFilter("RandomWorldName_Location."));
            LocalizedText localizedText3 = Language.SelectRandom(Lang.CreateDialogFilter("RandomWorldName_Noun."));
            var obj = new
            {
                Adjective = localizedText4.Value,
                Location = localizedText2.Value,
                Noun = localizedText3.Value
            };
            _optionwWorldName = localizedText.FormatWith(obj);
            if (Main.rand.Next(10000) == 0)
            {
                _optionwWorldName = Language.GetTextValue("SpecialWorldName.TheConstant");
            }
        }
        while (_optionwWorldName.Length > 27);
    }
References Terraria.GameContent.UI.States.UIWorldCreation._optionwWorldName, Terraria.Lang.CreateDialogFilter(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.rand, and Terraria.Localization.Language.SelectRandom().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.ClickRandomizeName(), and Terraria.GameContent.UI.States.UIWorldCreation.SetDefaultOptions().