TModLoader: Terraria.GameContent.FlexibleTileWand.Reload
Reload()
static void Terraria.GameContent.FlexibleTileWand.Reload () inline static
Definition at line 216 of file FlexibleTileWand.cs.
    {
        RubblePlacementSmall = CreateRubblePlacerSmall();
        RubblePlacementMedium = CreateRubblePlacerMedium();
        RubblePlacementLarge = CreateRubblePlacerLarge();
    }
References Terraria.GameContent.FlexibleTileWand.CreateRubblePlacerLarge(), Terraria.GameContent.FlexibleTileWand.CreateRubblePlacerMedium(), Terraria.GameContent.FlexibleTileWand.CreateRubblePlacerSmall(), Terraria.GameContent.FlexibleTileWand.RubblePlacementLarge, Terraria.GameContent.FlexibleTileWand.RubblePlacementMedium, and Terraria.GameContent.FlexibleTileWand.RubblePlacementSmall.
Referenced by Terraria.ModLoader.ItemLoader.Unload().