TModLoader: Terraria.GameContent.UI.Elements.UIWorldListItem.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIWorldListItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.GameContent.UI.Elements.UIPanel.
    {
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0164: Unknown result type (might be due to invalid IL or missing references)
        //IL_0176: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0206: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_0225: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0257: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02db: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fa: Unknown result type (might be due to invalid IL or missing references)
        base.DrawSelf(spriteBatch);
        CalculatedStyle innerDimensions = GetInnerDimensions();
        CalculatedStyle dimensions = _worldIcon.GetDimensions();
        float num = dimensions.X + dimensions.Width;
        Color color = (_data.IsValid ? Color.White : Color.Gray);
        string worldName = _data.GetWorldName(allowCropping: true);
        Utils.DrawBorderString(spriteBatch, worldName, new Vector2(num + 6f, dimensions.Y - 2f), color);
        spriteBatch.Draw(_dividerTexture.Value, new Vector2(num, innerDimensions.Y + 21f), (Rectangle?)null, Color.White, 0f, Vector2.Zero, new Vector2((GetDimensions().X + GetDimensions().Width - num) / 8f, 1f), (SpriteEffects)0, 0f);
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(num + 6f, innerDimensions.Y + 29f);
        float num2 = 100f;
        DrawPanel(spriteBatch, vector, num2);
        GetDifficulty(out var expertText, out var gameModeColor);
        float x = FontAssets.MouseText.Value.MeasureString(expertText).X;
        float x2 = num2 * 0.5f - x * 0.5f;
        Utils.DrawBorderString(spriteBatch, expertText, vector + new Vector2(x2, 3f), gameModeColor);
        vector.X += num2 + 5f;
        float num3 = 150f;
        if (!GameCulture.FromCultureName(GameCulture.CultureName.English).IsActive)
        {
            num3 += 40f;
        }
        DrawPanel(spriteBatch, vector, num3);
        string textValue = Language.GetTextValue("UI.WorldSizeFormat", _data.WorldSizeName);
        float x3 = FontAssets.MouseText.Value.MeasureString(textValue).X;
        float x4 = num3 * 0.5f - x3 * 0.5f;
        Utils.DrawBorderString(spriteBatch, textValue, vector + new Vector2(x4, 3f), Color.White);
        vector.X += num3 + 5f;
        float num4 = innerDimensions.X + innerDimensions.Width - vector.X;
        DrawPanel(spriteBatch, vector, num4);
        string arg = ((!GameCulture.FromCultureName(GameCulture.CultureName.English).IsActive) ? _data.CreationTime.ToShortDateString() : _data.CreationTime.ToString("d MMMM yyyy"));
        string textValue2 = Language.GetTextValue("UI.WorldCreatedFormat", arg);
        float x5 = FontAssets.MouseText.Value.MeasureString(textValue2).X;
        float x6 = num4 * 0.5f - x5 * 0.5f;
        Utils.DrawBorderString(spriteBatch, textValue2, vector + new Vector2(x6, 3f), Color.White);
        vector.X += num4 + 5f;
    }
References Terraria.GameContent.UI.Elements.AWorldListItem._data, Terraria.GameContent.UI.Elements.UIWorldListItem._dividerTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._worldIcon, Terraria.IO.WorldFileData.CreationTime, Terraria.Utils.DrawBorderString(), Terraria.GameContent.UI.Elements.UIWorldListItem.DrawPanel(), Terraria.Localization.GameCulture.FromCultureName(), Terraria.GameContent.UI.Elements.AWorldListItem.GetDifficulty(), Terraria.UI.UIElement.GetDimensions(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.Localization.Language.GetTextValue(), Terraria.IO.WorldFileData.GetWorldName(), Terraria.GameContent.FontAssets.MouseText, Terraria.UI.UIElement.Width, and Terraria.IO.WorldFileData.WorldSizeName.