TModLoader: Terraria.ModLoader.ModTypeLookup.RegisterWithName
RegisterWithName()
static void Terraria.ModLoader.ModTypeLookup< T >.RegisterWithName (T instance, string name, string fullName) inline static private
Definition at line 54 of file ModTypeLookup.cs.
    {
        if (dict.ContainsKey(fullName))
        {
            throw new Exception(Language.GetTextValue("tModLoader.LoadErrorDuplicateName", typeof(T).Name, fullName));
        }
        dict[fullName] = instance;
        string modName = instance.Mod?.Name ?? "Terraria";
        if (!tieredDict.TryGetValue(modName, out var subDictionary))
        {
            subDictionary = (tieredDict[modName] = new Dictionary<string, T>());
        }
        subDictionary[name] = instance;
    }
References Terraria.ModLoader.ModTypeLookup< T >.dict, Terraria.Localization.Language.GetTextValue(), and Terraria.ModLoader.ModTypeLookup< T >.tieredDict.
Referenced by Terraria.ModLoader.ModTypeLookup< T >.Register(), and Terraria.ModLoader.ModTypeLookup< T >.RegisterLegacyNames().