TModLoader: Terraria.GameContent.UI.Elements.UIWorldListItem.PlayGame
PlayGame()
void Terraria.GameContent.UI.Elements.UIWorldListItem.PlayGame (UIMouseEvent evt, UIElement listeningElement) inline private
    {
        if (!_data.IsValid || listeningElement != evt.Target || TryMovingToRejectionMenuIfNeeded(_data.GameMode))
        {
            return;
        }
        _data.SetAsActive();
        SoundEngine.PlaySound(10);
        Main.clrInput();
        Main.GetInputText("");
        if (Main.menuMultiplayer && SocialAPI.Network != null)
        {
            Main.menuMode = 889;
        }
        else if (Main.menuMultiplayer)
        {
            Main.menuMode = 30;
        }
        else
        {
            Main.menuMode = 10;
        }
        if (!Main.menuMultiplayer)
        {
            ConfigManager.LoadAll();
            if (ConfigManager.AnyModNeedsReload())
            {
                Terraria.ModLoader.ModLoader.OnSuccessfulLoad = (Action)Delegate.Combine(Terraria.ModLoader.ModLoader.OnSuccessfulLoad, PlayReload());
                Terraria.ModLoader.ModLoader.Reload();
            }
            else
            {
                ConfigManager.OnChangedAll();
                WorldGen.playWorld();
            }
        }
    }
References Terraria.GameContent.UI.Elements.AWorldListItem._data, Terraria.ModLoader.Config.ConfigManager.AnyModNeedsReload(), Terraria.Main.clrInput(), Terraria.IO.WorldFileData.GameMode, Terraria.Main.GetInputText(), Terraria.IO.WorldFileData.IsValid, Terraria.ModLoader.Config.ConfigManager.LoadAll(), Terraria.Main.menuMultiplayer, Terraria.Social.SocialAPI.Network, Terraria.ModLoader.Config.ConfigManager.OnChangedAll(), Terraria.ModLoader.ModLoader.OnSuccessfulLoad, Terraria.GameContent.UI.Elements.UIWorldListItem.PlayReload(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.WorldGen.playWorld(), Terraria.ModLoader.ModLoader.Reload(), Terraria.IO.WorldFileData.SetAsActive(), and Terraria.GameContent.UI.Elements.UIWorldListItem.TryMovingToRejectionMenuIfNeeded().
Referenced by Terraria.GameContent.UI.Elements.UIWorldListItem.UIWorldListItem().