TModLoader: Terraria.ModLoader.ModTypeLookup.Register
Register()
static void Terraria.ModLoader.ModTypeLookup< T >.Register (T instance) inline static
Registers the instance towards lookup via M:Terraria.ModLoader.ModContent.Find``1(System.String) and similar methods.
Should only be called once per instance. Registers legacy names specified via T:Terraria.ModLoader.LegacyNameAttribute on the instance's type automatically.
    {
        RegisterWithName(instance, instance.Name, instance.FullName);
        RegisterLegacyNames(instance, LegacyNameAttribute.GetLegacyNamesOfType(instance.GetType()).ToArray());
    }
References Terraria.ModLoader.LegacyNameAttribute.GetLegacyNamesOfType(), Terraria.ModLoader.ModTypeLookup< T >.RegisterLegacyNames(), and Terraria.ModLoader.ModTypeLookup< T >.RegisterWithName().