TModLoader: Terraria.ModLoader.BackupIO.Player.WriteArchive
WriteArchive()
static void Terraria.ModLoader.BackupIO.Player.WriteArchive (ZipFile zip, bool isCloudSave, string path) inline static private
Write the archive. Writes the .plr and .tplr files, then writes the player directory.
Definition at line 61 of file BackupIO.cs.
        {
            if (FileUtilities.Exists(path, isCloudSave))
            {
                zip.AddZipEntry(path, isCloudSave);
            }
            path = Path.ChangeExtension(path, ".tplr");
            if (FileUtilities.Exists(path, isCloudSave))
            {
                zip.AddZipEntry(path, isCloudSave);
            }
            if (isCloudSave)
            {
                WriteCloudFiles(zip, path);
            }
            else
            {
                WriteLocalFiles(zip, path);
            }
        }
References Terraria.Utilities.FileUtilities.Exists(), Terraria.ModLoader.BackupIO.Player.WriteCloudFiles(), and Terraria.ModLoader.BackupIO.Player.WriteLocalFiles().
Referenced by Terraria.ModLoader.BackupIO.Player.ArchivePlayer().