TModLoader: Terraria.GameContent.Events.DD2Event.Difficulty_3_SpawnMonsterFromGate
Difficulty_3_SpawnMonsterFromGate()
static void Terraria.GameContent.Events.DD2Event.Difficulty_3_SpawnMonsterFromGate (Vector2 gateBottom) inline static private
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        int x = (int)gateBottom.X;
        int y = (int)gateBottom.Y;
        int num = 60;
        int num2 = 7;
        if (NPC.waveNumber > 1)
        {
            num2 = 9;
        }
        if (NPC.waveNumber > 3)
        {
            num2 = 12;
        }
        if (NPC.waveNumber > 5)
        {
            num2 = 15;
        }
        int num3 = 7;
        if (NPC.waveNumber > 4)
        {
            num3 = 10;
        }
        int num4 = 2;
        if (NPC.waveNumber > 5)
        {
            num4 = 3;
        }
        int num5 = 12;
        if (NPC.waveNumber > 3)
        {
            num5 = 18;
        }
        int num6 = 4;
        if (NPC.waveNumber > 5)
        {
            num6 = 6;
        }
        int num7 = 4;
        for (int i = 1; i < Main.CurrentFrameFlags.ActivePlayersCount; i++)
        {
            num = (int)((double)num * 1.3);
            num2 = (int)((double)num2 * 1.3);
            num5 = (int)((double)num * 1.3);
            num6 = (int)((double)num * 1.35);
            num7 = (int)((double)num7 * 1.3);
        }
        int num8 = 200;
        int num9 = 200;
        switch (NPC.waveNumber)
        {
        case 1:
            if (Main.rand.Next(18) == 0 && NPC.CountNPCS(563) < num2)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 563);
            }
            else if (NPC.CountNPCS(554) < num)
            {
                if (Main.rand.Next(7) == 0)
                {
                    num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 557);
                }
                num9 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 554);
            }
            break;
        case 2:
            if (Main.rand.Next(3) == 0 && NPC.CountNPCS(578) < num7)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 578);
            }
            else if (Main.rand.Next(7) == 0 && NPC.CountNPCS(563) < num2)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 563);
            }
            else if (Main.rand.Next(3) == 0 && NPC.CountNPCS(573) < num5)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 573);
            }
            else if (NPC.CountNPCS(554) < num)
            {
                if (Main.rand.Next(4) == 0)
                {
                    num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 557);
                }
                num9 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 554);
            }
            break;
        case 3:
            if (Main.rand.Next(13) == 0 && NPC.CountNPCS(571) < num6)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 571);
            }
            else if (Main.rand.Next(7) == 0 && NPC.CountNPCS(573) < num5)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 573);
            }
            else if (Main.rand.Next(10) == 0 && NPC.CountNPCS(560) < num3)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 560);
            }
            else if (Main.rand.Next(8) == 0 && NPC.CountNPCS(563) < num2)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 563);
            }
            else if (NPC.CountNPCS(554) + NPC.CountNPCS(557) < num)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 554);
            }
            break;
        case 4:
            if (Main.rand.Next(24) == 0 && !NPC.AnyNPCs(565))
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 565);
            }
            else if (Main.rand.Next(12) == 0 && NPC.CountNPCS(571) < num6)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 571);
            }
            else if (Main.rand.Next(15) == 0 && NPC.CountNPCS(560) < num3)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 560);
            }
            else if (Main.rand.Next(7) == 0 && NPC.CountNPCS(563) < num2)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 563);
            }
            else if (Main.rand.Next(5) == 0 && NPC.CountNPCS(573) + NPC.CountNPCS(575) < num5)
            {
                num8 = ((Main.rand.Next(3) == 0) ? NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 575) : NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 573));
            }
            else if (NPC.CountNPCS(554) < num)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 554);
            }
            break;
        case 5:
            if (Main.rand.Next(20) == 0 && !NPC.AnyNPCs(577))
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 577);
            }
            else if (Main.rand.Next(17) == 0 && NPC.CountNPCS(569) < num4)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 569);
            }
            else if (Main.rand.Next(8) == 0 && NPC.CountNPCS(571) < num6)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 571);
            }
            else if (Main.rand.Next(7) == 0 && NPC.CountNPCS(573) + NPC.CountNPCS(575) < num5)
            {
                num8 = ((Main.rand.Next(4) == 0) ? NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 575) : NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 573));
            }
            else if (NPC.CountNPCS(554) + NPC.CountNPCS(557) < num)
            {
                if (Main.rand.Next(3) == 0)
                {
                    num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 557);
                }
                num9 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 554);
            }
            break;
        case 6:
            if (Main.rand.Next(20) == 0 && !NPC.AnyNPCs(577))
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 577);
            }
            else if (Main.rand.Next(20) == 0 && !NPC.AnyNPCs(565))
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 565);
            }
            else if (Main.rand.Next(12) == 0 && NPC.CountNPCS(571) < num6)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 571);
            }
            else if (Main.rand.Next(25) == 0 && NPC.CountNPCS(569) < num4)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 569);
            }
            if (Main.rand.Next(7) == 0 && NPC.CountNPCS(578) < num7)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 578);
            }
            else if (Main.rand.Next(7) == 0 && NPC.CountNPCS(573) + NPC.CountNPCS(575) < num5)
            {
                num8 = ((Main.rand.Next(3) == 0) ? NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 575) : NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 573));
            }
            else if (Main.rand.Next(5) == 0 && NPC.CountNPCS(563) < num2)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 563);
            }
            else if (NPC.CountNPCS(554) + NPC.CountNPCS(557) < num)
            {
                if (Main.rand.Next(3) == 0)
                {
                    num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 557);
                }
                num9 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 554);
            }
            break;
        case 7:
            if (Main.rand.Next(20) == 0 && NPC.CountNPCS(571) < num6)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 571);
            }
            else if (Main.rand.Next(17) == 0 && NPC.CountNPCS(569) < num4)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 569);
            }
            else if (Main.rand.Next(10) == 0 && NPC.CountNPCS(563) < num2)
            {
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 563);
            }
            else if (NPC.CountNPCS(554) + NPC.CountNPCS(557) < num)
            {
                if (Main.rand.Next(5) == 0)
                {
                    num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 557);
                }
                num9 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 554);
            }
            break;
        default:
            num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 554);
            break;
        }
        if (Main.netMode == 2 && num8 < 200)
        {
            NetMessage.SendData(23, -1, -1, null, num8);
        }
        if (Main.netMode == 2 && num9 < 200)
        {
            NetMessage.SendData(23, -1, -1, null, num9);
        }
    }
References Terraria.Main.CurrentFrameFlags.ActivePlayersCount, Terraria.NPC.AnyNPCs(), Terraria.NPC.CountNPCS(), Terraria.GameContent.Events.DD2Event.GetSpawnSource_OldOnesArmy(), Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.rand, Terraria.NetMessage.SendData(), and Terraria.NPC.waveNumber.
Referenced by Terraria.GameContent.Events.DD2Event.SpawnMonsterFromGate().