TModLoader: Terraria.GameContent.Events.DD2Event.Difficulty_1_SpawnMonsterFromGate
Difficulty_1_SpawnMonsterFromGate()
static void Terraria.GameContent.Events.DD2Event.Difficulty_1_SpawnMonsterFromGate (Vector2 gateBottom) inline static private
Definition at line 1074 of file DD2Event.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        int x = (int)gateBottom.X;
        int y = (int)gateBottom.Y;
        int num = 50;
        int num2 = 6;
        if (NPC.waveNumber > 4)
        {
            num2 = 12;
        }
        else if (NPC.waveNumber > 3)
        {
            num2 = 8;
        }
        int num3 = 6;
        if (NPC.waveNumber > 4)
        {
            num3 = 8;
        }
        for (int i = 1; i < Main.CurrentFrameFlags.ActivePlayersCount; i++)
        {
            num = (int)((double)num * 1.3);
            num2 = (int)((double)num2 * 1.3);
            num3 = (int)((double)num3 * 1.3);
        }
        int num4 = 200;
        switch (NPC.waveNumber)
        {
        case 1:
            if (NPC.CountNPCS(552) + NPC.CountNPCS(555) < num)
            {
                num4 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 552);
            }
            break;
        case 2:
            if (NPC.CountNPCS(552) + NPC.CountNPCS(555) < num)
            {
                num4 = ((Main.rand.Next(7) != 0) ? NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 552) : NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 555));
            }
            break;
        case 3:
            if (Main.rand.Next(6) == 0 && NPC.CountNPCS(561) < num2)
            {
                num4 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 561);
            }
            else if (NPC.CountNPCS(552) + NPC.CountNPCS(555) < num)
            {
                num4 = ((Main.rand.Next(5) != 0) ? NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 552) : NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 555));
            }
            break;
        case 4:
            if (Main.rand.Next(12) == 0 && NPC.CountNPCS(558) < num3)
            {
                num4 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 558);
            }
            else if (Main.rand.Next(5) == 0 && NPC.CountNPCS(561) < num2)
            {
                num4 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 561);
            }
            else if (NPC.CountNPCS(552) + NPC.CountNPCS(555) < num)
            {
                num4 = ((Main.rand.Next(5) != 0) ? NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 552) : NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 555));
            }
            break;
        case 5:
        {
            GetInvasionStatus(out var _, out var requiredKillCount, out var currentKillCount);
            if ((float)currentKillCount > (float)requiredKillCount * 0.5f && !NPC.AnyNPCs(564))
            {
                num4 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 564);
            }
            if (Main.rand.Next(10) == 0 && NPC.CountNPCS(558) < num3)
            {
                num4 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 558);
            }
            else if (Main.rand.Next(4) == 0 && NPC.CountNPCS(561) < num2)
            {
                num4 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 561);
            }
            else if (NPC.CountNPCS(552) + NPC.CountNPCS(555) < num)
            {
                num4 = ((Main.rand.Next(4) != 0) ? NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 552) : NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 555));
            }
            break;
        }
        default:
            num4 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 552);
            break;
        }
        if (Main.netMode == 2 && num4 < 200)
        {
            NetMessage.SendData(23, -1, -1, null, num4);
        }
    }
References Terraria.Main.CurrentFrameFlags.ActivePlayersCount, Terraria.NPC.AnyNPCs(), Terraria.NPC.CountNPCS(), Terraria.GameContent.Events.DD2Event.GetInvasionStatus(), Terraria.GameContent.Events.DD2Event.GetSpawnSource_OldOnesArmy(), Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.rand, Terraria.NetMessage.SendData(), and Terraria.NPC.waveNumber.
Referenced by Terraria.GameContent.Events.DD2Event.SpawnMonsterFromGate().