TModLoader: Terraria.GameContent.Events.DD2Event.Difficulty_2_SpawnMonsterFromGate
Difficulty_2_SpawnMonsterFromGate()
static void Terraria.GameContent.Events.DD2Event.Difficulty_2_SpawnMonsterFromGate (Vector2 gateBottom) inline static private
Definition at line 1290 of file DD2Event.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        int x = (int)gateBottom.X;
        int y = (int)gateBottom.Y;
        int num = 50;
        int num2 = 5;
        if (NPC.waveNumber > 1)
        {
            num2 = 8;
        }
        if (NPC.waveNumber > 3)
        {
            num2 = 10;
        }
        if (NPC.waveNumber > 5)
        {
            num2 = 12;
        }
        int num3 = 5;
        if (NPC.waveNumber > 4)
        {
            num3 = 7;
        }
        int num4 = 2;
        int num5 = 8;
        if (NPC.waveNumber > 3)
        {
            num5 = 12;
        }
        int num6 = 3;
        if (NPC.waveNumber > 5)
        {
            num6 = 5;
        }
        for (int i = 1; i < Main.CurrentFrameFlags.ActivePlayersCount; i++)
        {
            num = (int)((double)num * 1.3);
            num2 = (int)((double)num2 * 1.3);
            num5 = (int)((double)num * 1.3);
            num6 = (int)((double)num * 1.35);
        }
        int num7 = 200;
        int num8 = 200;
        switch (NPC.waveNumber)
        {
        case 1:
            if (Main.rand.Next(20) == 0 && NPC.CountNPCS(562) < num2)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 562);
            }
            else if (NPC.CountNPCS(553) < num)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 553);
            }
            break;
        case 2:
            if (Main.rand.Next(3) == 0 && NPC.CountNPCS(572) < num5)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 572);
            }
            else if (Main.rand.Next(8) == 0 && NPC.CountNPCS(562) < num2)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 562);
            }
            else if (NPC.CountNPCS(553) < num)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 553);
            }
            break;
        case 3:
            if (Main.rand.Next(7) == 0 && NPC.CountNPCS(572) < num5)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 572);
            }
            else if (Main.rand.Next(10) == 0 && NPC.CountNPCS(559) < num3)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 559);
            }
            else if (Main.rand.Next(8) == 0 && NPC.CountNPCS(562) < num2)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 562);
            }
            else if (NPC.CountNPCS(553) + NPC.CountNPCS(556) < num)
            {
                if (Main.rand.Next(4) == 0)
                {
                    num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 556);
                }
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 553);
            }
            break;
        case 4:
            if (Main.rand.Next(10) == 0 && NPC.CountNPCS(570) < num6)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 570);
            }
            else if (Main.rand.Next(12) == 0 && NPC.CountNPCS(559) < num3)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 559);
            }
            else if (Main.rand.Next(6) == 0 && NPC.CountNPCS(562) < num2)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 562);
            }
            else if (Main.rand.Next(3) == 0 && NPC.CountNPCS(572) < num5)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 572);
            }
            else if (NPC.CountNPCS(553) < num)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 553);
            }
            break;
        case 5:
            if (Main.rand.Next(7) == 0 && NPC.CountNPCS(570) < num6)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 570);
            }
            else if (Main.rand.Next(10) == 0 && NPC.CountNPCS(559) < num3)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 559);
            }
            else if (Main.rand.Next(4) == 0 && NPC.CountNPCS(572) + NPC.CountNPCS(574) < num5)
            {
                num7 = ((Main.rand.Next(2) != 0) ? NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 574) : NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 572));
            }
            else if (NPC.CountNPCS(553) + NPC.CountNPCS(556) < num)
            {
                if (Main.rand.Next(3) == 0)
                {
                    num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 556);
                }
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 553);
            }
            break;
        case 6:
            if (Main.rand.Next(7) == 0 && NPC.CountNPCS(570) < num6)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 570);
            }
            else if (Main.rand.Next(17) == 0 && NPC.CountNPCS(568) < num4)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 568);
            }
            else if (Main.rand.Next(5) == 0 && NPC.CountNPCS(572) + NPC.CountNPCS(574) < num5)
            {
                num7 = ((Main.rand.Next(2) == 0) ? NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 574) : NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 572));
            }
            else if (Main.rand.Next(9) == 0 && NPC.CountNPCS(559) < num3)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 559);
            }
            else if (Main.rand.Next(3) == 0 && NPC.CountNPCS(562) < num2)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 562);
            }
            else if (NPC.CountNPCS(553) + NPC.CountNPCS(556) < num)
            {
                if (Main.rand.Next(3) != 0)
                {
                    num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 556);
                }
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 553);
            }
            break;
        case 7:
        {
            GetInvasionStatus(out var _, out var requiredKillCount, out var currentKillCount);
            if ((float)currentKillCount > (float)requiredKillCount * 0.1f && !NPC.AnyNPCs(576))
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 576);
            }
            else if (Main.rand.Next(7) == 0 && NPC.CountNPCS(570) < num6)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 570);
            }
            else if (Main.rand.Next(17) == 0 && NPC.CountNPCS(568) < num4)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 568);
            }
            else if (Main.rand.Next(7) == 0 && NPC.CountNPCS(572) + NPC.CountNPCS(574) < num5)
            {
                num7 = ((Main.rand.Next(3) == 0) ? NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 574) : NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 572));
            }
            else if (Main.rand.Next(11) == 0 && NPC.CountNPCS(559) < num3)
            {
                num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 559);
            }
            else if (NPC.CountNPCS(553) + NPC.CountNPCS(556) < num)
            {
                if (Main.rand.Next(2) == 0)
                {
                    num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 556);
                }
                num8 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 553);
            }
            break;
        }
        default:
            num7 = NPC.NewNPC(GetSpawnSource_OldOnesArmy(), x, y, 553);
            break;
        }
        if (Main.netMode == 2 && num7 < 200)
        {
            NetMessage.SendData(23, -1, -1, null, num7);
        }
        if (Main.netMode == 2 && num8 < 200)
        {
            NetMessage.SendData(23, -1, -1, null, num8);
        }
    }
References Terraria.Main.CurrentFrameFlags.ActivePlayersCount, Terraria.NPC.AnyNPCs(), Terraria.NPC.CountNPCS(), Terraria.GameContent.Events.DD2Event.GetInvasionStatus(), Terraria.GameContent.Events.DD2Event.GetSpawnSource_OldOnesArmy(), Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.rand, Terraria.NetMessage.SendData(), and Terraria.NPC.waveNumber.
Referenced by Terraria.GameContent.Events.DD2Event.SpawnMonsterFromGate().