TModLoader: Terraria.GameContent.Events.DD2Event.CheckProgress
CheckProgress()
static void Terraria.GameContent.Events.DD2Event.CheckProgress (int slainMonsterID) inline static
    {
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode == 1 || !Ongoing || LostThisRun || WonThisRun || EnemySpawningIsOnHold)
        {
            return;
        }
        GetInvasionStatus(out var currentWave, out var requiredKillCount, out var currentKillCount);
        float num = GetMonsterPointsWorth(slainMonsterID);
        float waveKills = NPC.waveKills;
        NPC.waveKills += num;
        NPC.totalInvasionPoints += num;
        currentKillCount += (int)num;
        bool flag = false;
        int num2 = currentWave;
        if (NPC.waveKills >= (float)requiredKillCount && requiredKillCount != 0)
        {
            NPC.waveKills = 0f;
            NPC.waveNumber++;
            flag = true;
            GetInvasionStatus(out currentWave, out requiredKillCount, out currentKillCount, currentlyInCheckProgress: true);
            if (WonThisRun)
            {
                if ((float)currentKillCount != waveKills && num != 0f)
                {
                    if (Main.netMode != 1)
                    {
                        Main.ReportInvasionProgress(currentKillCount, requiredKillCount, 3, currentWave);
                    }
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(78, -1, -1, null, Main.invasionProgress, Main.invasionProgressMax, 3f, currentWave);
                    }
                }
                return;
            }
            int num3 = currentWave;
            string key = "DungeonDefenders2.WaveComplete";
            if (num3 == 2)
            {
                key = "DungeonDefenders2.WaveCompleteFirst";
            }
            WorldGen.BroadcastText(NetworkText.FromKey(key), INFO_NEW_WAVE_COLOR);
            SetEnemySpawningOnHold(1800);
            if (OngoingDifficulty == 1)
            {
                if (num3 == 5)
                {
                    DropMedals(1);
                }
                if (num3 == 4)
                {
                    DropMedals(1);
                }
            }
            if (OngoingDifficulty == 2)
            {
                if (num3 == 7)
                {
                    DropMedals(6);
                }
                if (num3 == 6)
                {
                    DropMedals(3);
                }
                if (num3 == 5)
                {
                    DropMedals(1);
                }
            }
            if (OngoingDifficulty == 3)
            {
                if (num3 == 7)
                {
                    DropMedals(25);
                }
                if (num3 == 6)
                {
                    DropMedals(11);
                }
                if (num3 == 5)
                {
                    DropMedals(3);
                }
                if (num3 == 4)
                {
                    DropMedals(1);
                }
            }
        }
        if ((float)currentKillCount == waveKills)
        {
            return;
        }
        if (flag)
        {
            int num4 = 1;
            int num5 = 1;
            if (Main.netMode != 1)
            {
                Main.ReportInvasionProgress(num4, num5, 3, num2);
            }
            if (Main.netMode == 2)
            {
                NetMessage.SendData(78, -1, -1, null, num4, num5, 3f, num2);
            }
        }
        else
        {
            if (Main.netMode != 1)
            {
                Main.ReportInvasionProgress(currentKillCount, requiredKillCount, 3, currentWave);
            }
            if (Main.netMode == 2)
            {
                NetMessage.SendData(78, -1, -1, null, Main.invasionProgress, Main.invasionProgressMax, 3f, currentWave);
            }
        }
    }
References Terraria.WorldGen.BroadcastText(), Terraria.GameContent.Events.DD2Event.DropMedals(), Terraria.GameContent.Events.DD2Event.EnemySpawningIsOnHold, Terraria.Localization.NetworkText.FromKey(), Terraria.GameContent.Events.DD2Event.GetInvasionStatus(), Terraria.GameContent.Events.DD2Event.GetMonsterPointsWorth(), Terraria.GameContent.Events.DD2Event.INFO_NEW_WAVE_COLOR, Terraria.Main.invasionProgress, Terraria.Main.invasionProgressMax, Terraria.GameContent.Events.DD2Event.LostThisRun, Terraria.Main.netMode, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.GameContent.Events.DD2Event.OngoingDifficulty, Terraria.Main.ReportInvasionProgress(), Terraria.NetMessage.SendData(), Terraria.GameContent.Events.DD2Event.SetEnemySpawningOnHold(), Terraria.NPC.waveKills, Terraria.NPC.waveNumber, and Terraria.GameContent.Events.DD2Event.WonThisRun.
Referenced by Terraria.NPC.checkDead(), and Terraria.NPC.VanillaHitEffect().