TModLoader: Terraria.GameContent.UI.States.UICreativePowersMenu.CategoryButton_OnUpdate_DisplayTooltips
CategoryButton_OnUpdate_DisplayTooltips()
static void Terraria.GameContent.UI.States.UICreativePowersMenu.CategoryButton_OnUpdate_DisplayTooltips (UIElement affectedElement, string categoryNameKey) inline static private
Definition at line 216 of file UICreativePowersMenu.cs.
    {
        GroupOptionButton<int> groupOptionButton = affectedElement as GroupOptionButton<int>;
        if (affectedElement.IsMouseHovering)
        {
            string originalText = Language.GetTextValue(groupOptionButton.IsSelected ? (categoryNameKey + "Opened") : (categoryNameKey + "Closed"));
            CreativePowersHelper.AddDescriptionIfNeeded(ref originalText, categoryNameKey);
            Main.instance.MouseTextNoOverride(originalText, 0, 0);
        }
    }
References Terraria.GameContent.Creative.CreativePowersHelper.AddDescriptionIfNeeded(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.instance, and Terraria.Main.MouseTextNoOverride().
Referenced by Terraria.GameContent.UI.States.UICreativePowersMenu.itemsWindowButton_OnUpdate(), Terraria.GameContent.UI.States.UICreativePowersMenu.personalCategoryButton_OnUpdate(), Terraria.GameContent.UI.States.UICreativePowersMenu.researchWindowButton_OnUpdate(), Terraria.GameContent.UI.States.UICreativePowersMenu.timeCategoryButton_OnUpdate(), and Terraria.GameContent.UI.States.UICreativePowersMenu.weatherCategoryButton_OnUpdate().