TModLoader: Terraria.Graphics.Renderers.FlameParticle.Draw
Draw()
override void Terraria.Graphics.Renderers.FlameParticle.Draw (ref ParticleRendererSettings settings, SpriteBatch spritebatch) inline
Implements Terraria.Graphics.Renderers.IParticle.
Definition at line 57 of file FlameParticle.cs.
    {
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        Color color = new Color(120, 120, 120, 60) * Utils.GetLerpValue(1f, FadeOutNormalizedTime, _timeSinceSpawn / _timeTolive, clamped: true);
        Vector2 vector = settings.AnchorPosition + LocalPosition;
        ulong seed = Main.TileFrameSeed ^ (((ulong)LocalPosition.X << 32) | (uint)LocalPosition.Y);
        Player player = Main.player[_indexOfPlayerWhoSpawnedThis];
        for (int i = 0; i < 4; i++)
        {
            Vector2 position = vector + new Vector2((float)Utils.RandomInt(ref seed, -2, 3), (float)Utils.RandomInt(ref seed, -2, 3)) * Scale;
            DrawData drawData = new DrawData(_texture.Value, position, _frame, color, Rotation, _origin, Scale, (SpriteEffects)0);
            drawData.shader = _packedShaderIndex;
            DrawData cdd = drawData;
            PlayerDrawHelper.SetShaderForData(player, 0, ref cdd);
            cdd.Draw(spritebatch);
        }
        Main.pixelShader.CurrentTechnique.Passes[0].Apply();
    }
References Terraria.Graphics.Renderers.ABasicParticle._frame, Terraria.Graphics.Renderers.FlameParticle._indexOfPlayerWhoSpawnedThis, Terraria.Graphics.Renderers.ABasicParticle._origin, Terraria.Graphics.Renderers.FlameParticle._packedShaderIndex, Terraria.Graphics.Renderers.ABasicParticle._texture, Terraria.Graphics.Renderers.FlameParticle._timeSinceSpawn, Terraria.Graphics.Renderers.FlameParticle._timeTolive, Terraria.Graphics.Renderers.FlameParticle.FadeOutNormalizedTime, Terraria.Utils.GetLerpValue(), Terraria.Graphics.Renderers.ABasicParticle.LocalPosition, Terraria.Main.pixelShader, Terraria.Main.player, Terraria.Utils.RandomInt(), Terraria.Graphics.Renderers.ABasicParticle.Rotation, Terraria.Graphics.Renderers.ABasicParticle.Scale, and Terraria.DataStructures.PlayerDrawHelper.SetShaderForData().