TModLoader: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterPresent
RegisterPresent()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterPresent () inline private
Definition at line 2132 of file ItemDropDatabase.cs.
    {
        IItemDropRule snowGlobeRule = ItemDropRule.ByCondition(new Conditions.IsHardmode(), 602, 15);
        IItemDropRule redRyderRule = ItemDropRule.NotScalingWithLuck(1870, 150);
        redRyderRule.OnSuccess(ItemDropRule.NotScalingWithLuck(97, 1, 30, 60));
        IItemDropRule mrsClauseRule = ItemDropRule.NotScalingWithLuck(1932);
        mrsClauseRule.OnSuccess(ItemDropRule.NotScalingWithLuck(1933));
        mrsClauseRule.OnSuccess(ItemDropRule.NotScalingWithLuck(1934));
        IItemDropRule parkaRule = ItemDropRule.NotScalingWithLuck(1935);
        parkaRule.OnSuccess(ItemDropRule.NotScalingWithLuck(1936));
        parkaRule.OnSuccess(ItemDropRule.NotScalingWithLuck(1937));
        IItemDropRule treeRule = ItemDropRule.NotScalingWithLuck(1940);
        treeRule.OnSuccess(ItemDropRule.NotScalingWithLuck(1941));
        treeRule.OnSuccess(ItemDropRule.NotScalingWithLuck(1942));
        IItemDropRule[] vanityRules = new IItemDropRule[5]
        {
            mrsClauseRule,
            parkaRule,
            treeRule,
            ItemDropRule.NotScalingWithLuck(1938),
            ItemDropRule.NotScalingWithLuck(1939)
        };
        IItemDropRule vanityRule = new OneFromRulesRule(15, vanityRules);
        IItemDropRule foodRule = ItemDropRule.OneFromOptionsNotScalingWithLuck(7, 1911, 1919, 1920);
        IItemDropRule blockRule = new OneFromRulesRule(1, ItemDropRule.Common(1872, 1, 20, 49), ItemDropRule.Common(586, 1, 20, 49), ItemDropRule.Common(591, 1, 20, 49));
        IItemDropRule[] rules = new IItemDropRule[17]
        {
            snowGlobeRule,
            ItemDropRule.NotScalingWithLuck(1922, 30),
            ItemDropRule.NotScalingWithLuck(1927, 400),
            redRyderRule,
            ItemDropRule.NotScalingWithLuck(1909, 150),
            ItemDropRule.NotScalingWithLuck(1917, 150),
            ItemDropRule.NotScalingWithLuck(1915, 150),
            ItemDropRule.NotScalingWithLuck(1918, 150),
            ItemDropRule.NotScalingWithLuck(1921, 150),
            ItemDropRule.NotScalingWithLuck(1923, 300),
            ItemDropRule.NotScalingWithLuck(1907, 40),
            ItemDropRule.NotScalingWithLuck(1908, 10),
            vanityRule,
            foodRule,
            ItemDropRule.NotScalingWithLuck(1912, 8, 1, 3),
            ItemDropRule.NotScalingWithLuck(1913, 9, 20, 40),
            blockRule
        };
        RegisterToItem(1869, new SequentialRulesNotScalingWithLuckRule(1, rules));
    }
References Terraria.GameContent.ItemDropRules.ItemDropRule.ByCondition(), Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), Terraria.GameContent.ItemDropRules.ItemDropRule.NotScalingWithLuck(), Terraria.GameContent.ItemDropRules.ItemDropRule.OneFromOptionsNotScalingWithLuck(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToItem().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate().