TModLoader: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterGoodieBag
RegisterGoodieBag()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterGoodieBag () inline private
    {
        IItemDropRule[] paintings = new IItemDropRule[5]
        {
            ItemDropRule.NotScalingWithLuck(1846),
            ItemDropRule.NotScalingWithLuck(1847),
            ItemDropRule.NotScalingWithLuck(1848),
            ItemDropRule.NotScalingWithLuck(1849),
            ItemDropRule.NotScalingWithLuck(1850)
        };
        IItemDropRule catSet = ItemDropRule.NotScalingWithLuck(1749);
        catSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1750));
        catSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1751));
        IItemDropRule creeperSet = ItemDropRule.NotScalingWithLuck(1746);
        creeperSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1747));
        creeperSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1748));
        IItemDropRule ghostSet = ItemDropRule.NotScalingWithLuck(1752);
        ghostSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1753));
        IItemDropRule leprechaunSet = ItemDropRule.NotScalingWithLuck(1767);
        leprechaunSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1768));
        leprechaunSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1769));
        IItemDropRule pixieSet = ItemDropRule.NotScalingWithLuck(1770);
        pixieSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1771));
        IItemDropRule princessSet = ItemDropRule.NotScalingWithLuck(1772);
        princessSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1773));
        IItemDropRule pumpkinSet = ItemDropRule.NotScalingWithLuck(1754);
        pumpkinSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1755));
        pumpkinSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1756));
        IItemDropRule robotSet = ItemDropRule.NotScalingWithLuck(1757);
        robotSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1758));
        robotSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1759));
        IItemDropRule unicornSet = ItemDropRule.NotScalingWithLuck(1760);
        unicornSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1761));
        unicornSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1762));
        IItemDropRule vampireSet = ItemDropRule.NotScalingWithLuck(1763);
        vampireSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1764));
        vampireSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1765));
        IItemDropRule witchSet = ItemDropRule.NotScalingWithLuck(1766);
        witchSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1775));
        witchSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1776));
        IItemDropRule aintTypingThatSet = ItemDropRule.NotScalingWithLuck(1777);
        aintTypingThatSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1778));
        IItemDropRule karateTortoiseSet = ItemDropRule.NotScalingWithLuck(1779);
        karateTortoiseSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1780));
        karateTortoiseSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1781));
        IItemDropRule reaperSet = ItemDropRule.NotScalingWithLuck(1819);
        reaperSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1820));
        IItemDropRule foxSet = ItemDropRule.NotScalingWithLuck(1821);
        foxSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1822));
        foxSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1823));
        IItemDropRule spaceCreatureSet = ItemDropRule.NotScalingWithLuck(1838);
        spaceCreatureSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1839));
        spaceCreatureSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1840));
        IItemDropRule wolfSet = ItemDropRule.NotScalingWithLuck(1841);
        wolfSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1842));
        wolfSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1843));
        IItemDropRule treasureHunterSet = ItemDropRule.NotScalingWithLuck(1851);
        treasureHunterSet.OnSuccess(ItemDropRule.NotScalingWithLuck(1852));
        IItemDropRule[] vanitySets = new IItemDropRule[19]
        {
            catSet,
            creeperSet,
            ghostSet,
            leprechaunSet,
            pixieSet,
            princessSet,
            pumpkinSet,
            robotSet,
            unicornSet,
            vampireSet,
            witchSet,
            aintTypingThatSet,
            karateTortoiseSet,
            reaperSet,
            foxSet,
            ItemDropRule.NotScalingWithLuck(1824),
            spaceCreatureSet,
            wolfSet,
            treasureHunterSet
        };
        IItemDropRule[] rules = new IItemDropRule[5]
        {
            ItemDropRule.NotScalingWithLuck(1810, 150),
            ItemDropRule.NotScalingWithLuck(1800, 150),
            ItemDropRule.NotScalingWithLuck(1809, 4, 10, 40),
            new OneFromRulesRule(10, paintings),
            new OneFromRulesRule(1, vanitySets)
        };
        RegisterToItem(1774, new SequentialRulesNotScalingWithLuckRule(1, rules));
    }
References Terraria.GameContent.ItemDropRules.ItemDropRule.NotScalingWithLuck(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToItem().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate().