TModLoader: Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate
Populate()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate () inline
    {
        PrepareNPCNetIDsByTypeDictionary();
        RegisterGlobalRules();
        RegisterFoodDrops();
        RegisterWeirdRules();
        RegisterTownNPCDrops();
        RegisterDD2EventDrops();
        RegisterMiscDrops();
        RegisterHardmodeFeathers();
        RegisterYoyos();
        RegisterStatusImmunityItems();
        RegisterPirateDrops();
        RegisterBloodMoonFishingEnemies();
        RegisterMartianDrops();
        RegisterBossTrophies();
        RegisterBosses();
        RegisterHardmodeDungeonDrops();
        RegisterMimic();
        RegisterEclipse();
        RegisterBloodMoonFishing();
        RegisterBossBags();
        RegisterCrateDrops();
        RegisterObsidianLockbox();
        RegisterLockbox();
        RegisterHerbBag();
        RegisterGoodieBag();
        RegisterPresent();
        RegisterCanOfWorms();
        RegisterOyster();
        RegisterCapricorns();
        NPCLoader.ModifyGlobalLoot(new GlobalLoot(this));
        foreach (KeyValuePair<int, NPC> pair2 in ContentSamples.NpcsByNetId)
        {
            NPCLoader.ModifyNPCLoot(pair2.Value, new NPCLoot(pair2.Key, this));
        }
        foreach (KeyValuePair<int, Item> pair in ContentSamples.ItemsByType)
        {
            ItemLoader.ModifyItemLoot(pair.Value, new ItemLoot(pair.Key, this));
        }
        TrimDuplicateRulesForNegativeIDs();
    }
References Terraria.ID.ContentSamples.ItemsByType, Terraria.ModLoader.NPCLoader.ModifyGlobalLoot(), Terraria.ModLoader.ItemLoader.ModifyItemLoot(), Terraria.ModLoader.NPCLoader.ModifyNPCLoot(), Terraria.ID.ContentSamples.NpcsByNetId, Terraria.GameContent.ItemDropRules.ItemDropDatabase.PrepareNPCNetIDsByTypeDictionary(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBloodMoonFishing(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBloodMoonFishingEnemies(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBossBags(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBosses(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBossTrophies(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterCanOfWorms(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterCapricorns(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterCrateDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterDD2EventDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterEclipse(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterFoodDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterGlobalRules(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterGoodieBag(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterHardmodeDungeonDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterHardmodeFeathers(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterHerbBag(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterLockbox(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterMartianDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterMimic(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterMiscDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterObsidianLockbox(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterOyster(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterPirateDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterPresent(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterStatusImmunityItems(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterTownNPCDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterWeirdRules(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterYoyos(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.TrimDuplicateRulesForNegativeIDs().
Referenced by Terraria.Main.Initialize_AlmostEverything(), and Terraria.ModLoader.ModContent.SetupBestiary().