TModLoader: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToItem
RegisterToItem()
IItemDropRule Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToItem (int type, IItemDropRule entry) inline
    {
        RegisterToItemId(type, entry);
        if (type > 0 && _itemIdsByType.TryGetValue(type, out var value))
        {
            for (int i = 0; i < value.Count; i++)
            {
                RegisterToItemId(value[i], entry);
            }
        }
        return entry;
    }
References Terraria.GameContent.ItemDropRules.ItemDropDatabase._itemIdsByType, and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToItemId().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBossBags(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterCanOfWorms(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterCapricorns(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterCrateDrops(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterGoodieBag(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterHerbBag(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterLockbox(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterObsidianLockbox(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterOyster(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterPresent(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToMultipleItems().