TModLoader: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBossBags
RegisterBossBags()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterBossBags () inline private
Definition at line 1245 of file ItemDropDatabase.cs.
    {
        short item = 4957;
        RegisterToItem(item, ItemDropRule.Common(4987));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(4986, 1, 25, 74));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(4959, 7));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(4981, 2));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(4980, 2));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(4758, 3));
        RegisterToItem(item, ItemDropRule.FewFromOptionsNotScalingWithLuckWithX(2, 1, 1, 4982, 4983, 4984));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(657));
        item = 4782;
        RegisterToItem(item, ItemDropRule.Common(4989));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(4784, 7));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(4823, 10));
        RegisterToItem(item, ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 4923, 4952, 4953, 4914));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(4778, 4));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(4715, 20));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(5075, 20));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(636));
        item = 3318;
        RegisterToItem(item, ItemDropRule.Common(3090));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2493, 7));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2430, 2));
        RegisterToItem(item, ItemDropRule.FewFromOptionsNotScalingWithLuckWithX(2, 1, 1, 256, 257, 258));
        RegisterToItem(item, ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 2610, 2585));
        RegisterToItem(item, ItemDropRule.Common(998));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(50));
        item = 3328;
        RegisterToItem(item, ItemDropRule.Common(3336));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2109, 7));
        RegisterToItem(item, ItemDropRule.Common(1141));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(1182, 15));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(1305, 20));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(1157, 2));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(3021, 10));
        IItemDropRule itemDropRuleGrenadeLauncher = ItemDropRule.Common(758);
        itemDropRuleGrenadeLauncher.OnSuccess(ItemDropRule.Common(771, 1, 50, 149), hideLootReport: true);
        RegisterToItem(item, new OneFromRulesRule(1, itemDropRuleGrenadeLauncher, ItemDropRule.Common(1255), ItemDropRule.Common(788), ItemDropRule.Common(1178), ItemDropRule.Common(1259), ItemDropRule.Common(1155), ItemDropRule.Common(3018)));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(262));
        item = 3327;
        RegisterToItem(item, ItemDropRule.Common(3356));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2107, 7));
        RegisterToItem(item, ItemDropRule.Common(547, 1, 25, 40));
        RegisterToItem(item, ItemDropRule.Common(1225, 1, 20, 35));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(127));
        item = 3325;
        RegisterToItem(item, ItemDropRule.Common(3355));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2113, 7));
        RegisterToItem(item, ItemDropRule.Common(548, 1, 25, 40));
        RegisterToItem(item, ItemDropRule.Common(1225, 1, 20, 35));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(134));
        item = 3326;
        RegisterToItem(item, ItemDropRule.Common(3354));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2106, 7));
        RegisterToItem(item, ItemDropRule.Common(549, 1, 25, 40));
        RegisterToItem(item, ItemDropRule.Common(1225, 1, 20, 35));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(125));
        item = 3319;
        Conditions.IsCrimson conditionIsCrimson = new Conditions.IsCrimson();
        Conditions.IsCorruption conditionIsCorruption = new Conditions.IsCorruption();
        RegisterToItem(item, ItemDropRule.Common(3097));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2112, 7));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(1299, 30));
        RegisterToItem(item, ItemDropRule.ByCondition(conditionIsCrimson, 880, 1, 30, 87));
        RegisterToItem(item, ItemDropRule.ByCondition(conditionIsCrimson, 2171, 1, 1, 3));
        RegisterToItem(item, ItemDropRule.ByCondition(conditionIsCorruption, 47, 1, 20, 49));
        RegisterToItem(item, ItemDropRule.ByCondition(conditionIsCorruption, 56, 1, 30, 87));
        RegisterToItem(item, ItemDropRule.ByCondition(conditionIsCorruption, 59, 1, 1, 3));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(4));
        item = 3321;
        Conditions.NotMasterMode conditionIsNotMaster = new Conditions.NotMasterMode();
        Conditions.IsMasterMode conditionIsMaster = new Conditions.IsMasterMode();
        RegisterToItem(item, ItemDropRule.Common(3223));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2104, 7));
        RegisterToItem(item, ItemDropRule.ByCondition(conditionIsNotMaster, 880, 1, 80, 110));
        RegisterToItem(item, ItemDropRule.ByCondition(conditionIsNotMaster, 1329, 1, 20, 40));
        RegisterToItem(item, ItemDropRule.ByCondition(conditionIsMaster, 880, 1, 110, 135));
        RegisterToItem(item, ItemDropRule.ByCondition(conditionIsMaster, 1329, 1, 30, 50));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(3060, 20));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(266));
        item = 3320;
        RegisterToItem(item, ItemDropRule.Common(3224));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2111, 7));
        RegisterToItem(item, ItemDropRule.ByCondition(conditionIsNotMaster, 56, 1, 80, 110));
        RegisterToItem(item, ItemDropRule.ByCondition(conditionIsNotMaster, 86, 1, 20, 40));
        RegisterToItem(item, ItemDropRule.ByCondition(conditionIsMaster, 56, 1, 110, 135));
        RegisterToItem(item, ItemDropRule.ByCondition(conditionIsMaster, 86, 1, 30, 50));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(994, 20));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(13));
        item = 5111;
        RegisterToItem(item, ItemDropRule.Common(5100));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(5109, 7));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(5385, 14));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(5098, 3));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(5101, 3));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(5113, 3));
        RegisterToItem(item, ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 5117, 5118, 5119, 5095));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(668));
        item = 3322;
        RegisterToItem(item, ItemDropRule.Common(3333));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2108, 7));
        RegisterToItem(item, ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 1121, 1123, 2888));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(1132, 3));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(1170, 9));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2502, 9));
        RegisterToItem(item, ItemDropRule.Common(1129));
        RegisterToItem(item, ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 842, 843, 844));
        RegisterToItem(item, ItemDropRule.Common(1130, 1, 10, 29));
        RegisterToItem(item, ItemDropRule.Common(2431, 1, 17, 29));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(222));
        item = 3323;
        RegisterToItem(item, ItemDropRule.Common(3245));
        RegisterToItem(item, ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 1281, 1273, 1313));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(35));
        item = 3324;
        RegisterToItem(item, ItemDropRule.ByCondition(new Conditions.NotUsedDemonHeart(), 3335));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2105, 7));
        RegisterToItem(item, ItemDropRule.Common(367));
        RegisterToItem(item, ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 2998, 489, 490, 491));
        RegisterToItem(item, ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 514, 426, 434, 4912));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(113));
        item = 3331;
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(3372, 7));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(439));
        item = 3332;
        RegisterToItem(item, ItemDropRule.Common(1131));
        RegisterToItem(item, ItemDropRule.Common(3577));
        RegisterToItem(item, ItemDropRule.Common(4954));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(3373, 7));
        RegisterToItem(item, ItemDropRule.Common(3460, 1, 90, 110));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(4469, 10));
        RegisterToItem(item, ItemDropRule.ByCondition(new Conditions.NoPortalGun(), 3384));
        RegisterToItem(item, new FromOptionsWithoutRepeatsDropRule(2, 3063, 3389, 3065, 1553, 3930, 3541, 3570, 3571, 3569));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(398));
        item = 3860;
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(3863, 7));
        RegisterToItem(item, ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 3827, 3859, 3870, 3858));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(3883, 4));
        RegisterToItem(item, ItemDropRule.Common(3817, 1, 30, 49));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(551));
        item = 3329;
        RegisterToItem(item, ItemDropRule.Common(3337));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2110, 7));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(1294, 3));
        IItemDropRule itemDropRuleStynger = ItemDropRule.Common(1258);
        itemDropRuleStynger.OnSuccess(ItemDropRule.Common(1261, 1, 60, 99), hideLootReport: true);
        RegisterToItem(item, new OneFromRulesRule(1, itemDropRuleStynger, ItemDropRule.Common(1122), ItemDropRule.Common(899), ItemDropRule.Common(1248), ItemDropRule.Common(1295), ItemDropRule.Common(1296), ItemDropRule.Common(1297)));
        RegisterToItem(item, ItemDropRule.Common(2218, 1, 18, 23));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(245));
        item = 3330;
        RegisterToItem(item, ItemDropRule.Common(3367));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2588, 7));
        RegisterToItem(item, ItemDropRule.NotScalingWithLuck(2609, 10));
        RegisterToItem(item, new LeadingConditionRule(new Conditions.NotRemixSeed())).OnSuccess(ItemDropRule.OneFromOptions(1, 2611, 2624, 2622, 2621, 2623));
        RegisterToItem(item, new LeadingConditionRule(new Conditions.RemixSeed())).OnSuccess(ItemDropRule.OneFromOptions(1, 2611, 2624, 2622, 2621, 157));
        RegisterToItem(item, ItemDropRule.CoinsBasedOnNPCValue(370));
    }
References Terraria.GameContent.ItemDropRules.ItemDropRule.ByCondition(), Terraria.GameContent.ItemDropRules.ItemDropRule.CoinsBasedOnNPCValue(), Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), Terraria.GameContent.ItemDropRules.ItemDropRule.FewFromOptionsNotScalingWithLuckWithX(), Terraria.GameContent.ItemDropRules.ItemDropRule.NotScalingWithLuck(), Terraria.GameContent.ItemDropRules.ItemDropRule.OneFromOptions(), Terraria.GameContent.ItemDropRules.ItemDropRule.OneFromOptionsNotScalingWithLuck(), and Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToItem().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate().