TModLoader: Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterCrateDrops
RegisterCrateDrops()
void Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterCrateDrops () inline private
    {
        IItemDropRule[] themed = new IItemDropRule[3]
        {
            ItemDropRule.NotScalingWithLuck(3200, 40),
            ItemDropRule.NotScalingWithLuck(3201, 40),
            ItemDropRule.NotScalingWithLuck(997, 50)
        };
        IItemDropRule[] hardmodeThemed = new IItemDropRule[4]
        {
            ItemDropRule.ByCondition(new Conditions.IsHardmode(), 3064, 200),
            ItemDropRule.NotScalingWithLuck(3200, 40),
            ItemDropRule.NotScalingWithLuck(3201, 40),
            ItemDropRule.NotScalingWithLuck(2424, 25)
        };
        IItemDropRule[] coin = new IItemDropRule[2]
        {
            ItemDropRule.NotScalingWithLuck(73, 3, 1, 5),
            ItemDropRule.NotScalingWithLuck(72, 1, 20, 90)
        };
        IItemDropRule[] ores = new IItemDropRule[4]
        {
            ItemDropRule.NotScalingWithLuck(12, 1, 4, 15),
            ItemDropRule.NotScalingWithLuck(699, 1, 4, 15),
            ItemDropRule.NotScalingWithLuck(11, 1, 4, 15),
            ItemDropRule.NotScalingWithLuck(700, 1, 4, 15)
        };
        IItemDropRule[] hardmodeOres = new IItemDropRule[2]
        {
            ItemDropRule.NotScalingWithLuck(364, 1, 4, 15),
            ItemDropRule.NotScalingWithLuck(1104, 1, 4, 15)
        };
        IItemDropRule[] bars = new IItemDropRule[4]
        {
            ItemDropRule.NotScalingWithLuck(20, 1, 2, 5),
            ItemDropRule.NotScalingWithLuck(703, 1, 2, 5),
            ItemDropRule.NotScalingWithLuck(22, 1, 2, 5),
            ItemDropRule.NotScalingWithLuck(704, 1, 2, 5)
        };
        IItemDropRule[] hardmodeBars = new IItemDropRule[2]
        {
            ItemDropRule.NotScalingWithLuck(381, 1, 2, 3),
            ItemDropRule.NotScalingWithLuck(1184, 1, 2, 3)
        };
        IItemDropRule[] potions = new IItemDropRule[10]
        {
            ItemDropRule.NotScalingWithLuck(288, 1, 1, 3),
            ItemDropRule.NotScalingWithLuck(290, 1, 1, 3),
            ItemDropRule.NotScalingWithLuck(292, 1, 1, 3),
            ItemDropRule.NotScalingWithLuck(299, 1, 1, 3),
            ItemDropRule.NotScalingWithLuck(298, 1, 1, 3),
            ItemDropRule.NotScalingWithLuck(304, 1, 1, 3),
            ItemDropRule.NotScalingWithLuck(291, 1, 1, 3),
            ItemDropRule.NotScalingWithLuck(2322, 1, 1, 3),
            ItemDropRule.NotScalingWithLuck(2323, 1, 1, 3),
            ItemDropRule.NotScalingWithLuck(2329, 1, 1, 3)
        };
        IItemDropRule[] extraPotions = new IItemDropRule[2]
        {
            ItemDropRule.NotScalingWithLuck(28, 1, 5, 15),
            ItemDropRule.NotScalingWithLuck(110, 1, 5, 15)
        };
        IItemDropRule[] extraBait = new IItemDropRule[2]
        {
            ItemDropRule.NotScalingWithLuck(2675, 3, 1, 4),
            ItemDropRule.NotScalingWithLuck(2674, 1, 1, 4)
        };
        IItemDropRule bc_surfaceLoot = ItemDropRule.OneFromOptionsNotScalingWithLuck(20, 285, 953, 4341, 3068, 3084);
        IItemDropRule[] woodenCrateDrop = new IItemDropRule[5]
        {
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, themed),
            bc_surfaceLoot,
            ItemDropRule.SequentialRulesNotScalingWithLuck(7, coin),
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, new OneFromRulesRule(7, ores), new OneFromRulesRule(8, bars)),
            new OneFromRulesRule(7, potions)
        };
        IItemDropRule[] pearlwoodCrateDrop = new IItemDropRule[5]
        {
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, hardmodeThemed),
            bc_surfaceLoot,
            ItemDropRule.SequentialRulesNotScalingWithLuck(7, coin),
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, ItemDropRule.SequentialRulesNotScalingWithLuck(7, new OneFromRulesRule(2, hardmodeOres), new OneFromRulesRule(1, ores)), ItemDropRule.SequentialRulesNotScalingWithLuck(8, new OneFromRulesRule(2, hardmodeBars), new OneFromRulesRule(1, bars))),
            new OneFromRulesRule(7, potions)
        };
        RegisterToItem(2334, ItemDropRule.AlwaysAtleastOneSuccess(woodenCrateDrop));
        RegisterToItem(3979, ItemDropRule.AlwaysAtleastOneSuccess(pearlwoodCrateDrop));
        RegisterToMultipleItems(new OneFromRulesRule(3, extraPotions), 2334, 3979);
        RegisterToMultipleItems(ItemDropRule.SequentialRulesNotScalingWithLuck(3, extraBait), 2334, 3979);
        themed = new IItemDropRule[5]
        {
            ItemDropRule.NotScalingWithLuck(2501, 25),
            ItemDropRule.NotScalingWithLuck(2587, 20),
            ItemDropRule.NotScalingWithLuck(2608, 15),
            ItemDropRule.NotScalingWithLuck(3200, 20),
            ItemDropRule.NotScalingWithLuck(3201, 20)
        };
        hardmodeThemed = new IItemDropRule[6]
        {
            ItemDropRule.ByCondition(new Conditions.IsHardmode(), 3064, 60),
            ItemDropRule.NotScalingWithLuck(2501, 25),
            ItemDropRule.NotScalingWithLuck(2587, 20),
            ItemDropRule.NotScalingWithLuck(2608, 15),
            ItemDropRule.NotScalingWithLuck(3200, 20),
            ItemDropRule.NotScalingWithLuck(3201, 20)
        };
        ores = new IItemDropRule[6]
        {
            ItemDropRule.NotScalingWithLuck(12, 1, 12, 21),
            ItemDropRule.NotScalingWithLuck(699, 1, 12, 21),
            ItemDropRule.NotScalingWithLuck(11, 1, 12, 21),
            ItemDropRule.NotScalingWithLuck(700, 1, 12, 21),
            ItemDropRule.NotScalingWithLuck(14, 1, 12, 21),
            ItemDropRule.NotScalingWithLuck(701, 1, 12, 21)
        };
        hardmodeOres = new IItemDropRule[4]
        {
            ItemDropRule.NotScalingWithLuck(364, 1, 12, 21),
            ItemDropRule.NotScalingWithLuck(1104, 1, 12, 21),
            ItemDropRule.NotScalingWithLuck(365, 1, 12, 21),
            ItemDropRule.NotScalingWithLuck(1105, 1, 12, 21)
        };
        bars = new IItemDropRule[6]
        {
            ItemDropRule.NotScalingWithLuck(20, 1, 4, 7),
            ItemDropRule.NotScalingWithLuck(703, 1, 4, 7),
            ItemDropRule.NotScalingWithLuck(22, 1, 4, 7),
            ItemDropRule.NotScalingWithLuck(704, 1, 4, 7),
            ItemDropRule.NotScalingWithLuck(21, 1, 4, 7),
            ItemDropRule.NotScalingWithLuck(705, 1, 4, 7)
        };
        hardmodeBars = new IItemDropRule[4]
        {
            ItemDropRule.NotScalingWithLuck(381, 1, 3, 7),
            ItemDropRule.NotScalingWithLuck(1184, 1, 3, 7),
            ItemDropRule.NotScalingWithLuck(382, 1, 3, 7),
            ItemDropRule.NotScalingWithLuck(1191, 1, 3, 7)
        };
        potions = new IItemDropRule[8]
        {
            ItemDropRule.NotScalingWithLuck(288, 1, 2, 4),
            ItemDropRule.NotScalingWithLuck(296, 1, 2, 4),
            ItemDropRule.NotScalingWithLuck(304, 1, 2, 4),
            ItemDropRule.NotScalingWithLuck(305, 1, 2, 4),
            ItemDropRule.NotScalingWithLuck(2322, 1, 2, 4),
            ItemDropRule.NotScalingWithLuck(2323, 1, 2, 4),
            ItemDropRule.NotScalingWithLuck(2324, 1, 2, 4),
            ItemDropRule.NotScalingWithLuck(2327, 1, 2, 4)
        };
        extraPotions = new IItemDropRule[2]
        {
            ItemDropRule.NotScalingWithLuck(188, 1, 5, 15),
            ItemDropRule.NotScalingWithLuck(189, 1, 5, 15)
        };
        extraBait = new IItemDropRule[2]
        {
            ItemDropRule.NotScalingWithLuck(2676, 3, 2, 4),
            ItemDropRule.NotScalingWithLuck(2675, 1, 2, 4)
        };
        IItemDropRule[] ironCrate = new IItemDropRule[4]
        {
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, themed),
            ItemDropRule.NotScalingWithLuck(73, 4, 5, 10),
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, new OneFromRulesRule(6, ores), new OneFromRulesRule(4, bars)),
            new OneFromRulesRule(4, potions)
        };
        IItemDropRule[] mythrilCrate = new IItemDropRule[4]
        {
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, hardmodeThemed),
            ItemDropRule.NotScalingWithLuck(73, 4, 5, 10),
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, ItemDropRule.SequentialRulesNotScalingWithLuck(6, new OneFromRulesRule(2, hardmodeOres), new OneFromRulesRule(1, ores)), ItemDropRule.SequentialRulesNotScalingWithLuck(4, new OneFromRulesRule(3, 2, hardmodeBars), new OneFromRulesRule(1, bars))),
            new OneFromRulesRule(4, potions)
        };
        RegisterToItem(2335, ItemDropRule.AlwaysAtleastOneSuccess(ironCrate));
        RegisterToItem(3980, ItemDropRule.AlwaysAtleastOneSuccess(mythrilCrate));
        RegisterToMultipleItems(new OneFromRulesRule(2, extraPotions), 2335, 3980);
        RegisterToMultipleItems(ItemDropRule.SequentialRulesNotScalingWithLuck(2, extraBait), 2335, 3980);
        themed = new IItemDropRule[2]
        {
            ItemDropRule.NotScalingWithLuck(29, 8),
            ItemDropRule.NotScalingWithLuck(2491, 10)
        };
        hardmodeThemed = new IItemDropRule[3]
        {
            ItemDropRule.ByCondition(new Conditions.IsHardmode(), 3064, 20),
            ItemDropRule.NotScalingWithLuck(29, 8),
            ItemDropRule.NotScalingWithLuck(2491, 10)
        };
        ores = new IItemDropRule[4]
        {
            ItemDropRule.NotScalingWithLuck(14, 1, 25, 34),
            ItemDropRule.NotScalingWithLuck(701, 1, 25, 34),
            ItemDropRule.NotScalingWithLuck(13, 1, 25, 34),
            ItemDropRule.NotScalingWithLuck(702, 1, 25, 34)
        };
        hardmodeOres = new IItemDropRule[4]
        {
            ItemDropRule.NotScalingWithLuck(365, 1, 25, 34),
            ItemDropRule.NotScalingWithLuck(1105, 1, 25, 34),
            ItemDropRule.NotScalingWithLuck(366, 1, 25, 34),
            ItemDropRule.NotScalingWithLuck(1106, 1, 25, 34)
        };
        bars = new IItemDropRule[4]
        {
            ItemDropRule.NotScalingWithLuck(21, 1, 8, 11),
            ItemDropRule.NotScalingWithLuck(705, 1, 8, 11),
            ItemDropRule.NotScalingWithLuck(19, 1, 8, 11),
            ItemDropRule.NotScalingWithLuck(706, 1, 8, 11)
        };
        hardmodeBars = new IItemDropRule[4]
        {
            ItemDropRule.NotScalingWithLuck(382, 1, 8, 11),
            ItemDropRule.NotScalingWithLuck(1191, 1, 8, 11),
            ItemDropRule.NotScalingWithLuck(391, 1, 8, 11),
            ItemDropRule.NotScalingWithLuck(1198, 1, 8, 11)
        };
        potions = new IItemDropRule[5]
        {
            ItemDropRule.NotScalingWithLuck(288, 1, 2, 5),
            ItemDropRule.NotScalingWithLuck(296, 1, 2, 5),
            ItemDropRule.NotScalingWithLuck(305, 1, 2, 5),
            ItemDropRule.NotScalingWithLuck(2322, 1, 2, 5),
            ItemDropRule.NotScalingWithLuck(2323, 1, 2, 5)
        };
        extraPotions = new IItemDropRule[2]
        {
            ItemDropRule.NotScalingWithLuck(188, 1, 5, 20),
            ItemDropRule.NotScalingWithLuck(189, 1, 5, 20)
        };
        IItemDropRule[] goldCrate = new IItemDropRule[5]
        {
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, themed),
            ItemDropRule.NotScalingWithLuck(73, 3, 8, 20),
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, new OneFromRulesRule(5, ores), new OneFromRulesRule(3, 2, bars)),
            new OneFromRulesRule(3, potions),
            ItemDropRule.NotScalingWithLuck(989, 30)
        };
        IItemDropRule[] titaniumCrate = new IItemDropRule[5]
        {
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, hardmodeThemed),
            ItemDropRule.NotScalingWithLuck(73, 3, 8, 20),
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, ItemDropRule.SequentialRulesNotScalingWithLuck(5, new OneFromRulesRule(2, hardmodeOres), new OneFromRulesRule(1, ores)), ItemDropRule.SequentialRulesNotScalingWithLuckWithNumerator(3, 2, new OneFromRulesRule(3, 2, hardmodeBars), new OneFromRulesRule(1, bars))),
            new OneFromRulesRule(3, potions),
            ItemDropRule.NotScalingWithLuck(989, 15)
        };
        RegisterToItem(2336, ItemDropRule.AlwaysAtleastOneSuccess(goldCrate));
        RegisterToItem(3981, ItemDropRule.AlwaysAtleastOneSuccess(titaniumCrate));
        RegisterToMultipleItems(new OneFromRulesRule(2, extraPotions), 2336, 3981);
        RegisterToMultipleItems(new CommonDrop(2676, 3, 3, 7, 2), 2336, 3981);
        IItemDropRule[] bc_jungle = new IItemDropRule[2]
        {
            ItemDropRule.NotScalingWithLuck(3017, 20),
            ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 212, 964, 211, 213, 2292)
        };
        IItemDropRule bc_bamboo = ItemDropRule.NotScalingWithLuck(4564, 3, 20, 50);
        IItemDropRule bc_seaweed = ItemDropRule.NotScalingWithLuck(753, 20);
        IItemDropRule bc_sky = ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 158, 2219, 65, 159);
        IItemDropRule bc_cloud = ItemDropRule.NotScalingWithLuck(751, 2, 50, 100);
        IItemDropRule bc_fledgeWings = ItemDropRule.NotScalingWithLuck(4978, 40);
        IItemDropRule bc_skyPaintings = ItemDropRule.OneFromOptionsNotScalingWithLuck(2, 5226, 5254, 5238, 5258, 5255, 5388);
        IItemDropRule bc_son = ItemDropRule.NotScalingWithLuck(521, 2, 2, 5);
        IItemDropRule bc_corrupt = ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 162, 111, 96, 115, 64);
        IItemDropRule bc_crimson = ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 800, 802, 1256, 1290, 3062);
        IItemDropRule bc_cursed = ItemDropRule.NotScalingWithLuck(522, 2, 2, 5);
        IItemDropRule bc_ichor = ItemDropRule.NotScalingWithLuck(1332, 2, 2, 5);
        IItemDropRule bc_sol = ItemDropRule.NotScalingWithLuck(520, 2, 2, 5);
        IItemDropRule bc_shard = ItemDropRule.NotScalingWithLuck(502, 2, 4, 10);
        IItemDropRule bc_lockbox = ItemDropRule.Common(3085);
        IItemDropRule bc_book = ItemDropRule.NotScalingWithLuck(149, 2, 5, 15);
        IItemDropRule ruleSnowballCannonIceBow = ItemDropRule.ByCondition(new Conditions.NotRemixSeed(), 1319);
        ruleSnowballCannonIceBow.OnFailedConditions(ItemDropRule.NotScalingWithLuck(725), hideLootReport: true);
        IItemDropRule[] bc_iceList = new IItemDropRule[6]
        {
            ItemDropRule.NotScalingWithLuck(670),
            ItemDropRule.NotScalingWithLuck(724),
            ItemDropRule.NotScalingWithLuck(950),
            ruleSnowballCannonIceBow,
            ItemDropRule.NotScalingWithLuck(987),
            ItemDropRule.NotScalingWithLuck(1579)
        };
        IItemDropRule bc_ice = new OneFromRulesRule(1, bc_iceList);
        IItemDropRule bc_fish = ItemDropRule.NotScalingWithLuck(669, 20);
        IItemDropRule bc_scarab = ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 4056, 4442, 4055, 4061, 4062, 4276, 4262, 4263);
        IItemDropRule bc_bomb = ItemDropRule.NotScalingWithLuck(4423, 4, 4, 6);
        IItemDropRule bc_fossil = ItemDropRule.NotScalingWithLuck(3380, 4, 10, 16);
        IItemDropRule bc_sandstormBottle = ItemDropRule.NotScalingWithLuck(857, 35);
        IItemDropRule[] bc_lava = new IItemDropRule[2]
        {
            ItemDropRule.NotScalingWithLuck(906, 20),
            ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 4822, 4828, 4880, 4881, 4868)
        };
        IItemDropRule bc_pot = ItemDropRule.NotScalingWithLuck(4858, 4, 2, 2);
        IItemDropRule bc_obsi = ItemDropRule.Common(4879);
        IItemDropRule bc_wet = ItemDropRule.NotScalingWithLuck(4824, 3, 7, 10);
        IItemDropRule bc_plant = ItemDropRule.OneFromOptionsNotScalingWithLuck(2, 4902, 4903, 4904, 4905, 4906);
        IItemDropRule bc_ornate = ItemDropRule.NotScalingWithLuck(4737, 20);
        IItemDropRule bc_hellcart = ItemDropRule.NotScalingWithLuck(4443, 20);
        IItemDropRule bc_cake = ItemDropRule.NotScalingWithLuck(4551, 20);
        IItemDropRule[] bc_sea = new IItemDropRule[2]
        {
            ItemDropRule.NotScalingWithLuck(863, 10),
            ItemDropRule.OneFromOptionsNotScalingWithLuck(1, 186, 4404, 277, 187)
        };
        IItemDropRule bc_pile = ItemDropRule.NotScalingWithLuck(4090, 3, 20, 50);
        IItemDropRule bc_sharkbait = ItemDropRule.NotScalingWithLuck(4425, 10);
        IItemDropRule bc_sand = ItemDropRule.NotScalingWithLuck(4460, 10);
        IItemDropRule bc_goldCoin = ItemDropRule.NotScalingWithLuck(73, 4, 5, 12);
        ores = new IItemDropRule[8]
        {
            ItemDropRule.NotScalingWithLuck(12, 1, 20, 35),
            ItemDropRule.NotScalingWithLuck(699, 1, 20, 35),
            ItemDropRule.NotScalingWithLuck(11, 1, 20, 35),
            ItemDropRule.NotScalingWithLuck(700, 1, 20, 35),
            ItemDropRule.NotScalingWithLuck(14, 1, 20, 35),
            ItemDropRule.NotScalingWithLuck(701, 1, 20, 35),
            ItemDropRule.NotScalingWithLuck(13, 1, 20, 35),
            ItemDropRule.NotScalingWithLuck(702, 1, 20, 35)
        };
        hardmodeOres = new IItemDropRule[6]
        {
            ItemDropRule.NotScalingWithLuck(364, 1, 20, 35),
            ItemDropRule.NotScalingWithLuck(1104, 1, 20, 35),
            ItemDropRule.NotScalingWithLuck(365, 1, 20, 35),
            ItemDropRule.NotScalingWithLuck(1105, 1, 20, 35),
            ItemDropRule.NotScalingWithLuck(366, 1, 20, 35),
            ItemDropRule.NotScalingWithLuck(1106, 1, 20, 35)
        };
        bars = new IItemDropRule[6]
        {
            ItemDropRule.NotScalingWithLuck(22, 1, 6, 16),
            ItemDropRule.NotScalingWithLuck(704, 1, 6, 16),
            ItemDropRule.NotScalingWithLuck(21, 1, 6, 16),
            ItemDropRule.NotScalingWithLuck(705, 1, 6, 16),
            ItemDropRule.NotScalingWithLuck(19, 1, 6, 16),
            ItemDropRule.NotScalingWithLuck(706, 1, 6, 16)
        };
        hardmodeBars = new IItemDropRule[6]
        {
            ItemDropRule.NotScalingWithLuck(381, 1, 5, 16),
            ItemDropRule.NotScalingWithLuck(1184, 1, 5, 16),
            ItemDropRule.NotScalingWithLuck(382, 1, 5, 16),
            ItemDropRule.NotScalingWithLuck(1191, 1, 5, 16),
            ItemDropRule.NotScalingWithLuck(391, 1, 5, 16),
            ItemDropRule.NotScalingWithLuck(1198, 1, 5, 16)
        };
        potions = new IItemDropRule[6]
        {
            ItemDropRule.NotScalingWithLuck(288, 1, 2, 4),
            ItemDropRule.NotScalingWithLuck(296, 1, 2, 4),
            ItemDropRule.NotScalingWithLuck(304, 1, 2, 4),
            ItemDropRule.NotScalingWithLuck(305, 1, 2, 4),
            ItemDropRule.NotScalingWithLuck(2322, 1, 2, 4),
            ItemDropRule.NotScalingWithLuck(2323, 1, 2, 4)
        };
        extraPotions = new IItemDropRule[2]
        {
            ItemDropRule.NotScalingWithLuck(188, 1, 5, 17),
            ItemDropRule.NotScalingWithLuck(189, 1, 5, 17)
        };
        extraBait = new IItemDropRule[2]
        {
            ItemDropRule.NotScalingWithLuck(2676, 3, 2, 6),
            ItemDropRule.NotScalingWithLuck(2675, 1, 2, 6)
        };
        IItemDropRule hardmodeBiomeCrateOres = ItemDropRule.SequentialRulesNotScalingWithLuck(7, new OneFromRulesRule(2, hardmodeOres), new OneFromRulesRule(1, ores));
        IItemDropRule hardmodeBiomeCrateBars = ItemDropRule.SequentialRulesNotScalingWithLuck(4, new OneFromRulesRule(3, 2, hardmodeBars), new OneFromRulesRule(1, bars));
        IItemDropRule[] jungle = new IItemDropRule[7]
        {
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, bc_jungle),
            bc_goldCoin,
            new OneFromRulesRule(7, ores),
            new OneFromRulesRule(4, bars),
            new OneFromRulesRule(3, potions),
            bc_bamboo,
            bc_seaweed
        };
        IItemDropRule[] bramble = new IItemDropRule[7]
        {
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, bc_jungle),
            bc_goldCoin,
            hardmodeBiomeCrateOres,
            hardmodeBiomeCrateBars,
            new OneFromRulesRule(3, potions),
            bc_bamboo,
            bc_seaweed
        };
        IItemDropRule[] sky = new IItemDropRule[8]
        {
            bc_sky,
            bc_fledgeWings,
            bc_cloud,
            bc_skyPaintings,
            bc_goldCoin,
            new OneFromRulesRule(7, ores),
            new OneFromRulesRule(4, bars),
            new OneFromRulesRule(3, potions)
        };
        IItemDropRule[] azure = new IItemDropRule[8]
        {
            bc_sky,
            bc_fledgeWings,
            bc_cloud,
            bc_skyPaintings,
            bc_goldCoin,
            hardmodeBiomeCrateOres,
            hardmodeBiomeCrateBars,
            new OneFromRulesRule(3, potions)
        };
        IItemDropRule[] corrupt = new IItemDropRule[5]
        {
            bc_corrupt,
            bc_goldCoin,
            new OneFromRulesRule(7, ores),
            new OneFromRulesRule(4, bars),
            new OneFromRulesRule(3, potions)
        };
        IItemDropRule[] defiled = new IItemDropRule[7]
        {
            bc_corrupt,
            bc_goldCoin,
            hardmodeBiomeCrateOres,
            hardmodeBiomeCrateBars,
            new OneFromRulesRule(3, potions),
            bc_son,
            bc_cursed
        };
        IItemDropRule[] crimson = new IItemDropRule[5]
        {
            bc_crimson,
            bc_goldCoin,
            new OneFromRulesRule(7, ores),
            new OneFromRulesRule(4, bars),
            new OneFromRulesRule(3, potions)
        };
        IItemDropRule[] hematic = new IItemDropRule[7]
        {
            bc_crimson,
            bc_goldCoin,
            hardmodeBiomeCrateOres,
            hardmodeBiomeCrateBars,
            new OneFromRulesRule(3, potions),
            bc_son,
            bc_ichor
        };
        IItemDropRule[] hallowed = new IItemDropRule[4]
        {
            bc_goldCoin,
            new OneFromRulesRule(7, ores),
            new OneFromRulesRule(4, bars),
            new OneFromRulesRule(3, potions)
        };
        IItemDropRule[] divine = new IItemDropRule[6]
        {
            bc_goldCoin,
            hardmodeBiomeCrateOres,
            hardmodeBiomeCrateBars,
            new OneFromRulesRule(3, potions),
            bc_sol,
            bc_shard
        };
        IItemDropRule[] dungeon = new IItemDropRule[6]
        {
            bc_lockbox,
            bc_book,
            bc_goldCoin,
            hardmodeBiomeCrateOres,
            hardmodeBiomeCrateBars,
            new OneFromRulesRule(3, potions)
        };
        IItemDropRule[] stockade = new IItemDropRule[6]
        {
            bc_lockbox,
            bc_book,
            bc_goldCoin,
            hardmodeBiomeCrateOres,
            hardmodeBiomeCrateBars,
            new OneFromRulesRule(3, potions)
        };
        IItemDropRule[] frozen = new IItemDropRule[6]
        {
            bc_ice,
            bc_goldCoin,
            new OneFromRulesRule(7, ores),
            new OneFromRulesRule(4, bars),
            new OneFromRulesRule(3, potions),
            bc_fish
        };
        IItemDropRule[] boreal = new IItemDropRule[6]
        {
            bc_ice,
            bc_goldCoin,
            hardmodeBiomeCrateOres,
            hardmodeBiomeCrateBars,
            new OneFromRulesRule(3, potions),
            bc_fish
        };
        IItemDropRule[] oasis = new IItemDropRule[8]
        {
            bc_scarab,
            bc_bomb,
            bc_sandstormBottle,
            bc_goldCoin,
            bc_fossil,
            new OneFromRulesRule(7, ores),
            new OneFromRulesRule(4, bars),
            new OneFromRulesRule(3, potions)
        };
        IItemDropRule[] mirage = new IItemDropRule[8]
        {
            bc_scarab,
            bc_bomb,
            bc_sandstormBottle,
            bc_goldCoin,
            bc_fossil,
            hardmodeBiomeCrateOres,
            hardmodeBiomeCrateBars,
            new OneFromRulesRule(3, potions)
        };
        IItemDropRule[] obsidian = new IItemDropRule[12]
        {
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, bc_lava),
            bc_pot,
            bc_obsi,
            bc_wet,
            bc_plant,
            bc_hellcart,
            bc_goldCoin,
            new OneFromRulesRule(7, ores),
            new OneFromRulesRule(4, bars),
            new OneFromRulesRule(3, potions),
            bc_ornate,
            bc_cake
        };
        IItemDropRule[] hellstone = new IItemDropRule[12]
        {
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, bc_lava),
            bc_pot,
            bc_obsi,
            bc_wet,
            bc_plant,
            bc_hellcart,
            bc_goldCoin,
            hardmodeBiomeCrateOres,
            hardmodeBiomeCrateBars,
            new OneFromRulesRule(3, potions),
            bc_ornate,
            bc_cake
        };
        IItemDropRule[] ocean = new IItemDropRule[8]
        {
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, bc_sea),
            bc_sharkbait,
            bc_goldCoin,
            new OneFromRulesRule(7, ores),
            new OneFromRulesRule(4, bars),
            new OneFromRulesRule(3, potions),
            bc_pile,
            bc_sand
        };
        IItemDropRule[] seaside = new IItemDropRule[8]
        {
            ItemDropRule.SequentialRulesNotScalingWithLuck(1, bc_sea),
            bc_sharkbait,
            bc_goldCoin,
            hardmodeBiomeCrateOres,
            hardmodeBiomeCrateBars,
            new OneFromRulesRule(3, potions),
            bc_pile,
            bc_sand
        };
        RegisterToItem(3208, ItemDropRule.AlwaysAtleastOneSuccess(jungle));
        RegisterToItem(3987, ItemDropRule.AlwaysAtleastOneSuccess(bramble));
        RegisterToItem(3206, ItemDropRule.AlwaysAtleastOneSuccess(sky));
        RegisterToItem(3985, ItemDropRule.AlwaysAtleastOneSuccess(azure));
        RegisterToItem(3203, ItemDropRule.AlwaysAtleastOneSuccess(corrupt));
        RegisterToItem(3982, ItemDropRule.AlwaysAtleastOneSuccess(defiled));
        RegisterToItem(3204, ItemDropRule.AlwaysAtleastOneSuccess(crimson));
        RegisterToItem(3983, ItemDropRule.AlwaysAtleastOneSuccess(hematic));
        RegisterToItem(3207, ItemDropRule.AlwaysAtleastOneSuccess(hallowed));
        RegisterToItem(3986, ItemDropRule.AlwaysAtleastOneSuccess(divine));
        RegisterToItem(3205, ItemDropRule.AlwaysAtleastOneSuccess(dungeon));
        RegisterToItem(3984, ItemDropRule.AlwaysAtleastOneSuccess(stockade));
        RegisterToItem(4405, ItemDropRule.AlwaysAtleastOneSuccess(frozen));
        RegisterToItem(4406, ItemDropRule.AlwaysAtleastOneSuccess(boreal));
        RegisterToItem(4407, ItemDropRule.AlwaysAtleastOneSuccess(oasis));
        RegisterToItem(4408, ItemDropRule.AlwaysAtleastOneSuccess(mirage));
        RegisterToItem(4877, ItemDropRule.AlwaysAtleastOneSuccess(obsidian));
        RegisterToItem(4878, ItemDropRule.AlwaysAtleastOneSuccess(hellstone));
        RegisterToItem(5002, ItemDropRule.AlwaysAtleastOneSuccess(ocean));
        RegisterToItem(5003, ItemDropRule.AlwaysAtleastOneSuccess(seaside));
        int[] allCrates = new int[20]
        {
            3208, 3987, 3206, 3985, 3203, 3982, 3204, 3983, 3207, 3986,
            3205, 3984, 4405, 4406, 4407, 4408, 4877, 4878, 5002, 5003
        };
        RegisterToMultipleItems(new OneFromRulesRule(2, extraPotions), allCrates);
        RegisterToMultipleItems(ItemDropRule.SequentialRulesNotScalingWithLuck(2, extraBait), allCrates);
    }
References Terraria.GameContent.ItemDropRules.ItemDropRule.AlwaysAtleastOneSuccess(), Terraria.GameContent.ItemDropRules.ItemDropRule.ByCondition(), Terraria.GameContent.ItemDropRules.ItemDropRule.Common(), Terraria.GameContent.ItemDropRules.ItemDropRule.NotScalingWithLuck(), Terraria.GameContent.ItemDropRules.ItemDropRule.OneFromOptionsNotScalingWithLuck(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToItem(), Terraria.GameContent.ItemDropRules.ItemDropDatabase.RegisterToMultipleItems(), Terraria.GameContent.ItemDropRules.ItemDropRule.SequentialRulesNotScalingWithLuck(), and Terraria.GameContent.ItemDropRules.ItemDropRule.SequentialRulesNotScalingWithLuckWithNumerator().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate().