TModLoader: Terraria.Item.Prefix
Prefix()
bool Terraria.Item.Prefix (int prefixWeWant) inline
Attempts to apply a prefix to this T:Terraria.Item.
Parameters
prefixWeWant
If prefixWeWant == 0, do nothing.
If prefixWeWant == -1, then a random prefix is rolled, with a 25% chance to not roll a prefix and an additional 66% chance to void any prefixes in the F:Terraria.ID.PrefixID.Sets.ReducedNaturalChance set. This is used for chest loot, starting equipment, etc.
If prefixWeWant == -2, then a random prefix is rolled, with no chance to not roll a prefix. This is used for the Goblin Tinkerer.
If prefixWeWant == -3, then this method simple checks if this item can receive prefixes.
Otherwise, attempt to apply the given T:Terraria.ID.PrefixID to this item.
Returns
false if:
prefixWeWant is 0
M:Terraria.Item.CanHavePrefixes returns false
M:Terraria.Item.CanApplyPrefix(System.Int32) returns false
prefixWeWant == -1 and F:Terraria.Item.maxStack > 1
M:Terraria.ModLoader.ItemLoader.PrefixChance(Terraria.Item,System.Int32,Terraria.Utilities.UnifiedRandom) returns false
prefixWeWant == -1 or -2 or -3 and M:Terraria.ModLoader.PrefixLoader.Roll(Terraria.Item,Terraria.Utilities.UnifiedRandom,System.Int32@,System.Boolean) returns false.
Otherwise, return true.
    {
        if (!WorldGen.gen && Main.rand == null)
        {
            Main.rand = new UnifiedRandom();
        }
        if (prefixWeWant == 0)
        {
            return false;
        }
        if (!CanHavePrefixes())
        {
            return false;
        }
        if (prefixWeWant > 0 && !CanApplyPrefix(prefixWeWant))
        {
            return false;
        }
        if (prefixWeWant == -1 && maxStack > 1)
        {
            return false;
        }
        UnifiedRandom unifiedRandom = (WorldGen.gen ? WorldGen.genRand : Main.rand);
        bool? applyPrefixOverride = ItemLoader.PrefixChance(this, prefixWeWant, unifiedRandom);
        if ((!applyPrefixOverride) ?? false)
        {
            return false;
        }
        int rolledPrefix = prefixWeWant;
        float dmg = 1f;
        float kb = 1f;
        float spd = 1f;
        float size = 1f;
        float shtspd = 1f;
        float mcst = 1f;
        int crt = 0;
        bool flag = true;
        while (flag)
        {
            flag = false;
            if (((!applyPrefixOverride) ?? true) && rolledPrefix == -1 && unifiedRandom.Next(4) == 0)
            {
                return true;
            }
            if (prefixWeWant < -1)
            {
                rolledPrefix = -1;
            }
            int num2;
            if (prefixWeWant == -3)
            {
                return PrefixLoader.Roll(this, unifiedRandom, out num2, justCheck: true);
            }
            if ((rolledPrefix == -1 || rolledPrefix == -2 || rolledPrefix == -3) && !RollAPrefix(unifiedRandom, ref rolledPrefix))
            {
                return false;
            }
            switch (prefixWeWant)
            {
            case -3:
                return true;
            case -1:
                if (((!applyPrefixOverride) ?? true) && PrefixID.Sets.ReducedNaturalChance[rolledPrefix] && unifiedRandom.Next(3) != 0)
                {
                    return true;
                }
                break;
            }
            if (!TryGetPrefixStatMultipliersForItem(rolledPrefix, out dmg, out kb, out spd, out size, out shtspd, out mcst, out crt))
            {
                flag = true;
                rolledPrefix = -1;
            }
            if (prefixWeWant == -2 && rolledPrefix == 0)
            {
                rolledPrefix = -1;
                flag = true;
            }
        }
        UndoItemAnimationCompensations();
        damage = (int)Math.Round((float)damage * dmg);
        useAnimation = (int)Math.Round((float)useAnimation * spd);
        useTime = (int)Math.Round((float)useTime * spd);
        reuseDelay = (int)Math.Round((float)reuseDelay * spd);
        mana = (int)Math.Round((float)mana * mcst);
        knockBack *= kb;
        scale *= size;
        shootSpeed *= shtspd;
        crit += crt;
        if (rolledPrefix >= PrefixID.Count)
        {
            PrefixLoader.GetPrefix(rolledPrefix)?.Apply(this);
        }
        ApplyItemAnimationCompensationsToVanillaItems();
        float num = 1f * dmg * (2f - spd) * (2f - mcst) * size * kb * shtspd * (1f + (float)crt * 0.02f);
        if (rolledPrefix == 62 || rolledPrefix == 69 || rolledPrefix == 73 || rolledPrefix == 77)
        {
            num *= 1.05f;
        }
        if (rolledPrefix == 63 || rolledPrefix == 70 || rolledPrefix == 74 || rolledPrefix == 78 || rolledPrefix == 67)
        {
            num *= 1.1f;
        }
        if (rolledPrefix == 64 || rolledPrefix == 71 || rolledPrefix == 75 || rolledPrefix == 79 || rolledPrefix == 66)
        {
            num *= 1.15f;
        }
        if (rolledPrefix == 65 || rolledPrefix == 72 || rolledPrefix == 76 || rolledPrefix == 80 || rolledPrefix == 68)
        {
            num *= 1.2f;
        }
        if (rolledPrefix >= PrefixID.Count)
        {
            PrefixLoader.GetPrefix(rolledPrefix)?.ModifyValue(ref num);
        }
        int baseRarity = rare;
        if ((double)num >= 1.2)
        {
            rare += 2;
        }
        else if ((double)num >= 1.05)
        {
            rare++;
        }
        else if ((double)num <= 0.8)
        {
            rare -= 2;
        }
        else if ((double)num <= 0.95)
        {
            rare--;
        }
        if (baseRarity >= 12)
        {
            rare = RarityLoader.GetRarity(baseRarity).GetPrefixedRarity(rare - baseRarity, num);
        }
        else if (rare > 11)
        {
            rare = 11;
        }
        if (rare > -11)
        {
            if (rare < -1)
            {
                rare = -1;
            }
            if (rare > RarityLoader.RarityCount - 1)
            {
                rare = RarityLoader.RarityCount - 1;
            }
        }
        num *= num;
        value = (int)((float)value * num);
        prefix = rolledPrefix;
        return true;
    }
References Terraria.ModLoader.ModPrefix.Apply(), Terraria.Item.ApplyItemAnimationCompensationsToVanillaItems(), Terraria.Item.CanApplyPrefix(), Terraria.Item.CanHavePrefixes(), Terraria.ID.PrefixID.Count, Terraria.Item.crit, Terraria.Item.damage, Terraria.WorldGen.gen, Terraria.ModLoader.PrefixLoader.GetPrefix(), Terraria.ModLoader.ModRarity.GetPrefixedRarity(), Terraria.ModLoader.RarityLoader.GetRarity(), Terraria.Item.knockBack, Terraria.Item.mana, Terraria.Item.maxStack, Terraria.ModLoader.ModPrefix.ModifyValue(), Terraria.Item.prefix, Terraria.ModLoader.ItemLoader.PrefixChance(), Terraria.Main.rand, Terraria.Item.rare, Terraria.ModLoader.RarityLoader.RarityCount, Terraria.ID.PrefixID.Sets.ReducedNaturalChance, Terraria.Item.reuseDelay, Terraria.ModLoader.PrefixLoader.Roll(), Terraria.Item.RollAPrefix(), Terraria.Item.scale, Terraria.Item.shootSpeed, Terraria.Item.TryGetPrefixStatMultipliersForItem(), Terraria.Item.UndoItemAnimationCompensations(), Terraria.Item.useAnimation, Terraria.Item.useTime, and Terraria.Item.value.
Referenced by Terraria.Item.Item(), Terraria.WorldGen.AddBuriedChest(), Terraria.Item.DeserializeFrom(), Terraria.Main.DrawInventory(), Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy(), Terraria.Player.DropItems_GetDefaults(), Terraria.MessageBuffer.GetData(), Terraria.UI.ItemSlot.GetGamepadInstructions(), Terraria.ModLoader.TileLoader.GetItemDrops(), Terraria.Player.KillMe(), Terraria.WorldGen.KillTile(), Terraria.ModLoader.IO.ItemIO.Load(), Terraria.IO.WorldFile.LoadChests(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.Item.NewItem_Inner(), Terraria.UI.ItemSlot.OverrideHover(), Terraria.GameContent.UI.Chat.ItemTagHandler.Parse(), Terraria.WorldGen.PrefixItemFromOptions(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEHatRack.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEItemFrame.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.ReadExtraData(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadItem(), Terraria.GameContent.Tile_Entities.TEHatRack.ReadItem(), and Terraria.ModLoader.IO.ItemIO.Receive().