TModLoader: Terraria.Item.GetShimmered
GetShimmered()
void Terraria.Item.GetShimmered () inline private
    {
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_06eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_071d: Unknown result type (might be due to invalid IL or missing references)
        //IL_072a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0707: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0301: Unknown result type (might be due to invalid IL or missing references)
        //IL_0306: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05db: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e0: Unknown result type (might be due to invalid IL or missing references)
        int shimmerEquivalentType = GetShimmerEquivalentType();
        int decraftingRecipeIndex = ShimmerTransforms.GetDecraftingRecipeIndex(shimmerEquivalentType);
        if (ItemID.Sets.CoinLuckValue[shimmerEquivalentType] > 0)
        {
            stack *= ItemID.Sets.CoinLuckValue[shimmerEquivalentType];
            Main.player[Main.myPlayer].AddCoinLuck(base.Center, stack);
            NetMessage.SendData(146, -1, -1, null, 1, (int)base.Center.X, (int)base.Center.Y, stack);
            type = 0;
            stack = 0;
        }
        else if (shimmerEquivalentType == 1326 && NPC.downedMoonlord)
        {
            int num = stack;
            SetDefaults(5335);
            stack = num;
            shimmered = true;
        }
        else if (shimmerEquivalentType == 779 && NPC.downedMoonlord)
        {
            int num12 = stack;
            SetDefaults(5134);
            stack = num12;
            shimmered = true;
        }
        else if (shimmerEquivalentType == 3031 && NPC.downedMoonlord)
        {
            int num13 = stack;
            SetDefaults(5364);
            stack = num13;
            shimmered = true;
        }
        else if (shimmerEquivalentType == 5364 && NPC.downedMoonlord)
        {
            int num14 = stack;
            SetDefaults(3031);
            stack = num14;
            shimmered = true;
        }
        else if (shimmerEquivalentType == 3461)
        {
            short num15 = 3461;
            num15 = Main.GetMoonPhase() switch
            {
                MoonPhase.QuarterAtRight => 5407,
                MoonPhase.HalfAtRight => 5405,
                MoonPhase.ThreeQuartersAtRight => 5404,
                MoonPhase.Full => 5408,
                MoonPhase.ThreeQuartersAtLeft => 5401,
                MoonPhase.HalfAtLeft => 5403,
                MoonPhase.QuarterAtLeft => 5402,
                _ => 5406,
            };
            int num16 = stack;
            SetDefaults(num15);
            stack = num16;
            shimmered = true;
        }
        else if (createTile == 139)
        {
            int num17 = stack;
            SetDefaults(576);
            stack = num17;
            shimmered = true;
        }
        else if (ItemID.Sets.ShimmerTransformToItem[shimmerEquivalentType] > 0)
        {
            int num18 = stack;
            SetDefaults(ItemID.Sets.ShimmerTransformToItem[shimmerEquivalentType]);
            stack = num18;
            shimmered = true;
        }
        else if (type == 4986)
        {
            if (NPC.unlockedSlimeRainbowSpawn)
            {
                return;
            }
            NPC.unlockedSlimeRainbowSpawn = true;
            NetMessage.SendData(7);
            int num19 = NPC.NewNPC(GetNPCSource_FromThis(), (int)base.Center.X + 4, (int)base.Center.Y, 681);
            if (num19 >= 0)
            {
                NPC obj = Main.npc[num19];
                obj.velocity = velocity;
                obj.netUpdate = true;
                obj.shimmerTransparency = 1f;
                NetMessage.SendData(146, -1, -1, null, 2, num19);
            }
            WorldGen.CheckAchievement_RealEstateAndTownSlimes();
            stack--;
            if (stack <= 0)
            {
                type = 0;
            }
        }
        else if (makeNPC > 0)
        {
            int num2 = 50;
            int highestNPCSlotIndexWeWillPick = 200;
            int num3 = NPC.GetAvailableAmountOfNPCsToSpawnUpToSlot(stack, highestNPCSlotIndexWeWillPick);
            while (num2 > 0 && num3 > 0 && stack > 0)
            {
                num2--;
                num3--;
                stack--;
                int num4 = -1;
                num4 = ((NPCID.Sets.ShimmerTransformToNPC[makeNPC] < 0) ? NPC.ReleaseNPC((int)base.Center.X, (int)base.Bottom.Y, makeNPC, placeStyle, Main.myPlayer) : NPC.ReleaseNPC((int)base.Center.X, (int)base.Bottom.Y, NPCID.Sets.ShimmerTransformToNPC[makeNPC], 0, Main.myPlayer));
                if (num4 >= 0)
                {
                    Main.npc[num4].shimmerTransparency = 1f;
                    NetMessage.SendData(146, -1, -1, null, 2, num4);
                }
            }
            shimmered = true;
            if (stack <= 0)
            {
                type = 0;
            }
        }
        else if (decraftingRecipeIndex >= 0)
        {
            int num5 = FindDecraftAmount();
            Recipe recipe = Main.recipe[decraftingRecipeIndex];
            int num6 = 0;
            bool flag = recipe.requiredItem.Count > 1;
            IEnumerable<Item> enumerable = recipe.requiredItem;
            if (recipe.customShimmerResults != null)
            {
                enumerable = recipe.customShimmerResults;
            }
            int num7 = 0;
            foreach (Item item2 in enumerable)
            {
                if (item2.type <= 0)
                {
                    break;
                }
                num7++;
                int num8 = num5 * item2.stack;
                if (recipe.alchemy)
                {
                    for (int num9 = num8; num9 > 0; num9--)
                    {
                        if (Main.rand.Next(3) == 0)
{
                            num8--;
                        }
                    }
                }
                while (num8 > 0)
                {
                    int num10 = num8;
                    if (num10 > 9999)
                    {
                        num10 = 9999;
                    }
                    num8 -= num10;
                    int num11 = NewItem(GetItemSource_Misc(8), (int)position.X, (int)position.Y, width, height, item2.type);
                    Item item = Main.item[num11];
                    item.stack = num10;
                    item.shimmerTime = 1f;
                    item.shimmered = true;
                    item.shimmerWet = true;
                    item.wet = true;
                    item.velocity *= 0.1f;
                    item.playerIndexTheItemIsReservedFor = Main.myPlayer;
                    if (flag)
                    {
                        item.velocity.X = 1f * (float)num7;
                        item.velocity.X *= 1f + (float)num7 * 0.05f;
                        if (num6 % 2 == 0)
{
                            item.velocity.X *= -1f;
                        }
                    }
                    NetMessage.SendData(145, -1, -1, null, num11, 1f);
                }
            }
            stack -= num5 * recipe.createItem.stack;
            if (stack <= 0)
            {
                stack = 0;
                type = 0;
            }
        }
        if (stack > 0)
        {
            shimmerTime = 1f;
        }
        else
        {
            shimmerTime = 0f;
        }
        shimmerWet = true;
        wet = true;
        velocity *= 0.1f;
        if (Main.netMode == 0)
        {
            ShimmerEffect(base.Center);
        }
        else
        {
            NetMessage.SendData(146, -1, -1, null, 0, (int)base.Center.X, (int)base.Center.Y);
            NetMessage.SendData(145, -1, -1, null, whoAmI, 1f);
        }
        AchievementsHelper.NotifyProgressionEvent(27);
        if (stack == 0)
        {
            makeNPC = -1;
            active = false;
        }
    }
References Terraria.Entity.active, Terraria.Player.AddCoinLuck(), Terraria.WorldGen.CheckAchievement_RealEstateAndTownSlimes(), Terraria.ID.ItemID.Sets.CoinLuckValue, Terraria.Item.createTile, Terraria.Recipe.customShimmerResults, Terraria.NPC.downedMoonlord, Terraria.Item.FindDecraftAmount(), Terraria.NPC.GetAvailableAmountOfNPCsToSpawnUpToSlot(), Terraria.GameContent.ShimmerTransforms.GetDecraftingRecipeIndex(), Terraria.Item.GetItemSource_Misc(), Terraria.Main.GetMoonPhase(), Terraria.Item.GetNPCSource_FromThis(), Terraria.Item.GetShimmerEquivalentType(), Terraria.Entity.height, Terraria.Main.item, Terraria.Item.makeNPC, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Main.npc, Terraria.Item.placeStyle, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.rand, Terraria.Main.recipe, Terraria.NPC.ReleaseNPC(), Terraria.Recipe.requiredItem, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.shimmered, Terraria.Item.ShimmerEffect(), Terraria.Item.shimmerTime, Terraria.ID.ItemID.Sets.ShimmerTransformToItem, Terraria.ID.NPCID.Sets.ShimmerTransformToNPC, Terraria.NPC.shimmerTransparency, Terraria.Entity.shimmerWet, Terraria.Item.stack, Terraria.Item.type, Terraria.NPC.unlockedSlimeRainbowSpawn, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Item.Shimmering().