TModLoader: Terraria.Item.DespawnIfMeetingConditions
DespawnIfMeetingConditions()
void Terraria.Item.DespawnIfMeetingConditions (int i) inline private
Definition at line 50176 of file Item.cs.
    {
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_0230: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_026b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_027a: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        if (type == 75 && Main.dayTime && !Main.remixWorld && !shimmered && !beingGrabbed)
        {
            for (int j = 0; j < 10; j++)
            {
                Dust.NewDust(position, width, height, 15, velocity.X, velocity.Y, 150, default(Color), 1.2f);
            }
            for (int k = 0; k < 3; k++)
            {
                Gore.NewGore(position, new Vector2(velocity.X, velocity.Y), Main.rand.Next(16, 18));
            }
            active = false;
            type = 0;
            stack = 0;
            if (Main.netMode == 2)
            {
                NetMessage.SendData(21, -1, -1, null, i);
            }
        }
        if (type == 4143 && timeSinceItemSpawned > 300)
        {
            for (int l = 0; l < 20; l++)
            {
                Dust.NewDust(position, width, height, 15, velocity.X, velocity.Y, 150, Color.Lerp(Color.CornflowerBlue, Color.Indigo, Main.rand.NextFloat()), 1.2f);
            }
            active = false;
            type = 0;
            stack = 0;
            if (Main.netMode == 2)
            {
                NetMessage.SendData(21, -1, -1, null, i);
            }
        }
        if (type == 3822 && !DD2Event.Ongoing)
        {
            int num = Main.rand.Next(18, 24);
            for (int m = 0; m < num; m++)
            {
                int num2 = Dust.NewDust(base.Center, 0, 0, 61, 0f, 0f, 0, default(Color), 1.7f);
                Dust obj = Main.dust[num2];
                obj.velocity *= 8f;
                Main.dust[num2].velocity.Y -= 1f;
                Main.dust[num2].position = Vector2.Lerp(Main.dust[num2].position, base.Center, 0.5f);
                Main.dust[num2].noGravity = true;
                Main.dust[num2].noLight = true;
            }
            active = false;
            type = 0;
            stack = 0;
            if (Main.netMode == 2)
            {
                NetMessage.SendData(21, -1, -1, null, i);
            }
        }
    }
References Terraria.Entity.active, Terraria.Item.beingGrabbed, Terraria.Main.dayTime, Terraria.Main.dust, Terraria.Entity.height, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Entity.position, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.NetMessage.SendData(), Terraria.Item.shimmered, Terraria.Item.stack, Terraria.Item.timeSinceItemSpawned, Terraria.Item.type, Terraria.Entity.velocity, and Terraria.Entity.width.
Referenced by Terraria.Item.UpdateItem().