TModLoader: Terraria.Item.BannerToItem
BannerToItem()
static int Terraria.Item.BannerToItem (int banner) inline static
Converts a banner ID into the equivalent item type (F:Terraria.Item.type).
Parameters
banner The banner ID to convert.
Returns
The item type associated with the given banner ID.
This method will return the wrong item type if banner is not a valid banner ID.
You can get the banner ID of an NPC using M:Terraria.Item.NPCtoBanner(System.Int32).
Definition at line 2094 of file Item.cs.
    {
        if (NPCLoader.bannerToItem.TryGetValue(banner, out var result))
        {
            return result;
        }
        if (banner == 289)
        {
            return 5352;
        }
        if (banner >= 276)
        {
            return 4965 + banner - 276;
        }
        if (banner >= 274)
        {
            return 4687 + banner - 274;
        }
        if (banner == 273)
        {
            return 4602;
        }
        if (banner >= 267)
        {
            return 4541 + banner - 267;
        }
        if (banner >= 257)
        {
            return 3837 + banner - 257;
        }
        if (banner >= 252)
        {
            return 3789 + banner - 252;
        }
        if (banner == 251)
        {
            return 3780;
        }
        if (banner >= 249)
        {
            return 3593 + banner - 249;
        }
        if (banner >= 186)
        {
            return 3390 + banner - 186;
        }
        if (banner >= 88)
        {
            return 2897 + banner - 88;
        }
        return 1615 + banner - 1;
    }
References Terraria.ModLoader.NPCLoader.bannerToItem.
Referenced by Terraria.Player.ApplyBannerDefenseBuff(), Terraria.Player.ApplyBannerOffenseBuff(), Terraria.NPC.CountKillForBannersAndDropThem(), Terraria.GameContent.Bestiary.CommonEnemyUICollectionInfoProvider.GetKillCountNeeded(), and Terraria.SceneMetrics.ScanAndExportToMain().