TModLoader: Terraria.Item.SetDefaults
SetDefaults() [1/2]
void Terraria.Item.SetDefaults (int Type, bool noMatCheck = false, ItemVariant variant = null) inline
    {
        if (Type < 0)
        {
            netDefaults(Type);
            return;
        }
        if (Main.netMode == 1 || Main.netMode == 2)
        {
            playerIndexTheItemIsReservedFor = 255;
        }
        else
        {
            playerIndexTheItemIsReservedFor = Main.myPlayer;
        }
        ResetStats(Type);
        if (variant == null)
        {
            variant = ItemVariants.SelectVariant(Type);
        }
        else if (!ItemVariants.HasVariant(Type, variant))
        {
            variant = null;
        }
        Variant = variant;
        if (type == 0)
        {
            netID = 0;
            stack = 0;
        }
        else if (ItemID.Sets.IsFood[type])
        {
            SetFoodDefaults(type);
        }
        else if (type <= 1000)
        {
            SetDefaults1(type);
        }
        else if (type <= 2001)
        {
            SetDefaults2(type);
        }
        else if (type <= 3000)
        {
            SetDefaults3(type);
        }
        else if (type <= 3989)
        {
            SetDefaults4(type);
        }
        else
        {
            SetDefaults5(type);
        }
        ApplyItemAnimationCompensationsToVanillaItems();
        RestoreMeleeSpeedBehaviorOnVanillaItems();
        if (type < ItemID.Count && rare == -13)
        {
            master = true;
        }
        dye = GameShaders.Armor.GetShaderIdFromItemId(type);
        if (hairDye != 0)
        {
            hairDye = GameShaders.Hair.GetShaderIdFromItemId(type);
        }
        if (type == 2015)
        {
            value = sellPrice(0, 0, 5);
        }
        if (type == 2016)
        {
            value = sellPrice(0, 0, 7, 50);
        }
        if (type == 2017)
        {
            value = sellPrice(0, 0, 7, 50);
        }
        if (type == 5212)
        {
            value = sellPrice(0, 0, 7, 50);
        }
        if (type == 5300)
        {
            value = sellPrice(0, 0, 7, 50);
        }
        if (type == 5311)
        {
            value = sellPrice(0, 0, 7, 50);
        }
        if (type == 5312)
        {
            value = sellPrice(0, 0, 7, 50);
        }
        if (type == 5313)
        {
            value = sellPrice(0, 0, 7, 50);
        }
        if (type == 2019)
        {
            value = sellPrice(0, 0, 5);
        }
        if (type == 2018)
        {
            value = sellPrice(0, 0, 5);
        }
        if (type == 3563)
        {
            value = sellPrice(0, 0, 5);
        }
        if (type == 261)
        {
            value = sellPrice(0, 0, 7, 50);
        }
        if (type == 2205)
        {
            value = sellPrice(0, 0, 12, 50);
        }
        if (type == 2123)
        {
            value = sellPrice(0, 0, 7, 50);
        }
        if (type == 2122)
        {
            value = sellPrice(0, 0, 7, 50);
        }
        if (type == 2003)
        {
            value = sellPrice(0, 0, 10);
        }
        if (type == 2156)
        {
            value = sellPrice(0, 0, 15);
        }
        if (type == 2157)
        {
            value = sellPrice(0, 0, 15);
        }
        if (type == 2121)
        {
            value = sellPrice(0, 0, 10);
        }
        if (type == 1992)
        {
            value = sellPrice(0, 0, 3);
        }
        if (type == 2004)
        {
            value = sellPrice(0, 0, 5);
        }
        if (type == 2002)
        {
            value = sellPrice(0, 0, 5);
        }
        if (type == 2740)
        {
            value = sellPrice(0, 0, 2, 50);
        }
        if (type == 2006)
        {
            value = sellPrice(0, 0, 10);
        }
        if (type == 3191)
        {
            value = sellPrice(0, 0, 20);
        }
        if (type == 3192)
        {
            value = sellPrice(0, 0, 2, 50);
        }
        if (type == 3193)
        {
            value = sellPrice(0, 0, 5);
        }
        if (type == 3194)
        {
            value = sellPrice(0, 0, 10);
        }
        if (type == 2007)
        {
            value = sellPrice(0, 0, 50);
        }
        if (type == 2673)
        {
            value = sellPrice(0, 10);
        }
        if (bait > 0)
        {
            if (bait >= 50)
            {
                rare = 3;
            }
            else if (bait >= 30)
            {
                rare = 2;
            }
            else if (bait >= 15)
            {
                rare = 1;
            }
        }
        if (type >= 1994 && type <= 2001)
        {
            int num = type - 1994;
            if (num == 0)
            {
                value = sellPrice(0, 0, 5);
            }
            if (num == 4)
            {
                value = sellPrice(0, 0, 10);
            }
            if (num == 6)
            {
                value = sellPrice(0, 0, 15);
            }
            if (num == 3)
            {
                value = sellPrice(0, 0, 20);
            }
            if (num == 7)
            {
                value = sellPrice(0, 0, 30);
            }
            if (num == 2)
            {
                value = sellPrice(0, 0, 40);
            }
            if (num == 1)
            {
                value = sellPrice(0, 0, 75);
            }
            if (num == 5)
            {
                value = sellPrice(0, 1);
            }
        }
        if (type == 2663 || type == 1720 || type == 2137 || type == 2155 || type == 2151 || type == 1704 || type == 2143 || type == 1710 || type == 2238 || type == 2133 || type == 2147 || type == 2405 || type == 1716 || type == 1705)
        {
            value = sellPrice(0, 2);
        }
        if (Main.projHook[shoot])
        {
            useStyle = 0;
            useTime = 0;
            useAnimation = 0;
        }
        if (ItemID.Sets.IsDrill[type] || ItemID.Sets.IsChainsaw[type] || type == 1262)
        {
            useTime = (int)((double)useTime * 0.6);
            if (useTime < 1)
            {
                useTime = 1;
            }
            useAnimation = (int)((double)useAnimation * 0.6);
            if (useAnimation < 1)
            {
                useAnimation = 1;
            }
            tileBoost--;
        }
        if (ItemID.Sets.IsFood[type])
        {
            holdStyle = 1;
        }
        if (type >= 1803 && type <= 1807)
        {
            SetDefaults(1533 + type - 1803);
        }
        if (dye > 0)
        {
            maxStack = CommonMaxStack;
        }
        if (createTile == 19)
        {
            maxStack = CommonMaxStack;
        }
        netID = type;
        ItemLoader.SetDefaults(this);
        if (!noMatCheck)
        {
            material = ItemID.Sets.IsAMaterial[type];
        }
        RebuildTooltip();
        if (type > 0 && ItemID.Sets.Deprecated[type])
        {
            TurnToAir();
        }
    }
References Terraria.Item.ApplyItemAnimationCompensationsToVanillaItems(), Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Item.bait, Terraria.Item.CommonMaxStack, Terraria.ID.ItemID.Count, Terraria.Item.createTile, Terraria.ID.ItemID.Sets.Deprecated, Terraria.Item.dye, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetShaderIdFromItemId(), Terraria.Graphics.Shaders.HairShaderDataSet.GetShaderIdFromItemId(), Terraria.Graphics.Shaders.GameShaders.Hair, Terraria.Item.hairDye, Terraria.GameContent.Items.ItemVariants.HasVariant(), Terraria.Item.holdStyle, Terraria.ID.ItemID.Sets.IsAMaterial, Terraria.ID.ItemID.Sets.IsChainsaw, Terraria.ID.ItemID.Sets.IsDrill, Terraria.ID.ItemID.Sets.IsFood, Terraria.Item.master, Terraria.Item.material, Terraria.Item.maxStack, Terraria.Main.myPlayer, Terraria.Item.netDefaults(), Terraria.Item.netID, Terraria.Main.netMode, Terraria.Item.playerIndexTheItemIsReservedFor, Terraria.Main.projHook, Terraria.Item.rare, Terraria.Item.RebuildTooltip(), Terraria.Item.ResetStats(), Terraria.Item.RestoreMeleeSpeedBehaviorOnVanillaItems(), Terraria.GameContent.Items.ItemVariants.SelectVariant(), Terraria.Item.sellPrice(), Terraria.Item.SetDefaults(), Terraria.ModLoader.ItemLoader.SetDefaults(), Terraria.Item.SetDefaults1(), Terraria.Item.SetDefaults2(), Terraria.Item.SetDefaults3(), Terraria.Item.SetDefaults4(), Terraria.Item.SetDefaults5(), Terraria.Item.SetFoodDefaults(), Terraria.Item.shoot, Terraria.Item.stack, Terraria.Item.tileBoost, Terraria.Item.TurnToAir(), Terraria.Item.type, Terraria.Item.Type, Terraria.Item.useAnimation, Terraria.Item.useStyle, Terraria.Item.useTime, Terraria.Item.value, and Terraria.Item.Variant.