TModLoader: Terraria.Item.GetPickedUpByMonsters_Money
GetPickedUpByMonsters_Money()
void Terraria.Item.GetPickedUpByMonsters_Money (int i) inline private
    {
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector((int)position.X, (int)position.Y, width, height);
        Rectangle rectangle2 = default(Rectangle);
        for (int j = 0; j < 200; j++)
        {
            NPC nPC = Main.npc[j];
            if (!nPC.active || nPC.lifeMax <= 5 || nPC.friendly || nPC.immortal || nPC.dontTakeDamage || NPCID.Sets.CantTakeLunchMoney[nPC.type])
            {
                continue;
            }
            float num = stack;
            float num2 = 1f;
            if (type == 72)
            {
                num2 = 100f;
            }
            if (type == 73)
            {
                num2 = 10000f;
            }
            if (type == 74)
            {
                num2 = 1000000f;
            }
            num *= num2;
            float num3 = nPC.extraValue;
            int num4 = nPC.realLife;
            if (num4 >= 0 && Main.npc[num4].active)
            {
                num3 = Main.npc[num4].extraValue;
            }
            else
            {
                num4 = -1;
            }
            if (!(num3 < num) || !(num3 + num < 999000000f))
            {
                continue;
            }
            ((Rectangle)(ref rectangle2))._002Ector((int)nPC.position.X, (int)nPC.position.Y, nPC.width, nPC.height);
            if (((Rectangle)(ref rectangle)).Intersects(rectangle2))
            {
                float num5 = (float)Main.rand.Next(50, 76) * 0.01f;
                if (type == 71)
                {
                    num5 += (float)Main.rand.Next(51) * 0.01f;
                }
                if (type == 72)
                {
                    num5 += (float)Main.rand.Next(26) * 0.01f;
                }
                if (num5 > 1f)
                {
                    num5 = 1f;
                }
                int num6 = (int)((float)stack * num5);
                if (num6 < 1)
                {
                    num6 = 1;
                }
                if (num6 > stack)
                {
                    num6 = stack;
                }
                stack -= num6;
                int num7 = (int)((float)num6 * num2);
                int number = j;
                if (num4 >= 0)
                {
                    number = num4;
                }
                nPC.extraValue += num7;
                if (Main.netMode == 0)
                {
                    nPC.moneyPing(position);
                }
                else
                {
                    NetMessage.SendData(92, -1, -1, null, number, num7, position.X, position.Y);
                }
                if (stack <= 0)
                {
                    SetDefaults();
                    active = false;
                }
                NetMessage.SendData(21, -1, -1, null, i);
            }
        }
    }
References Terraria.Entity.active, Terraria.ID.NPCID.Sets.CantTakeLunchMoney, Terraria.Entity.height, Terraria.Main.netMode, Terraria.Main.npc, Terraria.Entity.position, Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, Terraria.Item.type, and Terraria.Entity.width.
Referenced by Terraria.Item.UpdateItem().