TModLoader: Terraria.Item.CombineWithNearbyItems
CombineWithNearbyItems()
void Terraria.Item.CombineWithNearbyItems (int myItemIndex) inline private
    {
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        if (!CanCombineStackInWorld() || stack >= maxStack)
        {
            return;
        }
        for (int i = myItemIndex + 1; i < 400; i++)
        {
            Item item = Main.item[i];
            if (!item.active || item.type != type || item.shimmered != shimmered || item.stack <= 0 || item.playerIndexTheItemIsReservedFor != playerIndexTheItemIsReservedFor)
            {
                continue;
            }
            float num3 = Math.Abs(position.X + (float)(width / 2) - (item.position.X + (float)(item.width / 2))) + Math.Abs(position.Y + (float)(height / 2) - (item.position.Y + (float)(item.height / 2)));
            int num2 = 30;
            if ((double)numberOfNewItems > 40.0)
            {
                num2 *= 2;
            }
            if ((double)numberOfNewItems > 80.0)
            {
                num2 *= 2;
            }
            if ((double)numberOfNewItems > 120.0)
            {
                num2 *= 2;
            }
            if ((double)numberOfNewItems > 160.0)
            {
                num2 *= 2;
            }
            if ((double)numberOfNewItems > 200.0)
            {
                num2 *= 2;
            }
            if ((double)numberOfNewItems > 240.0)
            {
                num2 *= 2;
            }
            if (num3 < (float)num2 && ItemLoader.CanStack(this, item) && ItemLoader.CanStackInWorld(this, item))
            {
                position = (position + item.position) / 2f;
                velocity = (velocity + item.velocity) / 2f;
                ItemLoader.StackItems(this, item, out var _);
                if (item.stack <= 0)
                {
                    item.SetDefaults();
                    item.active = false;
                }
                if (Main.netMode != 0 && playerIndexTheItemIsReservedFor == Main.myPlayer)
                {
                    NetMessage.SendData(21, -1, -1, null, myItemIndex);
                    NetMessage.SendData(21, -1, -1, null, i);
                }
            }
        }
    }
References Terraria.Entity.active, Terraria.Item.CanCombineStackInWorld(), Terraria.ModLoader.ItemLoader.CanStack(), Terraria.ModLoader.ItemLoader.CanStackInWorld(), Terraria.Entity.height, Terraria.Main.item, Terraria.Item.maxStack, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.numberOfNewItems, Terraria.Item.playerIndexTheItemIsReservedFor, Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.shimmered, Terraria.Item.stack, Terraria.ModLoader.ItemLoader.StackItems(), Terraria.Item.type, Terraria.Entity.velocity, and Terraria.Entity.width.
Referenced by Terraria.Item.TryCombiningIntoNearbyItems().