TModLoader: Terraria.Item.GetPrefixCategory
GetPrefixCategory()
PrefixCategory? Terraria.Item.GetPrefixCategory () inline
Determines the T:Terraria.ModLoader.PrefixCategory of this T:Terraria.Item.
Returns
The T:Terraria.ModLoader.PrefixCategory of this T:Terraria.Item or null if this T:Terraria.Item doesn't have a category.
    {
        if (PrefixLegacy.ItemSets.SwordsHammersAxesPicks[type] || ItemLoader.MeleePrefix(this))
        {
            return PrefixCategory.Melee;
        }
        if (PrefixLegacy.ItemSets.GunsBows[type] || ItemLoader.RangedPrefix(this))
        {
            return PrefixCategory.Ranged;
        }
        if (PrefixLegacy.ItemSets.MagicAndSummon[type] || ItemLoader.MagicPrefix(this))
        {
            return PrefixCategory.Magic;
        }
        if (PrefixLegacy.ItemSets.SpearsMacesChainsawsDrillsPunchCannon[type] || PrefixLegacy.ItemSets.BoomerangsChakrams[type] || PrefixLegacy.ItemSets.ItemsThatCanHaveLegendary2[type] || ItemLoader.WeaponPrefix(this))
        {
            return PrefixCategory.AnyWeapon;
        }
        if (IsAPrefixableAccessory())
        {
            return PrefixCategory.Accessory;
        }
        return null;
    }
References Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.BoomerangsChakrams, Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.GunsBows, Terraria.Item.IsAPrefixableAccessory(), Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.ItemsThatCanHaveLegendary2, Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.MagicAndSummon, Terraria.ModLoader.ItemLoader.MagicPrefix(), Terraria.ModLoader.ItemLoader.MeleePrefix(), Terraria.ModLoader.ItemLoader.RangedPrefix(), Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.SpearsMacesChainsawsDrillsPunchCannon, Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.SwordsHammersAxesPicks, Terraria.Item.type, and Terraria.ModLoader.ItemLoader.WeaponPrefix().
Referenced by Terraria.ModLoader.PrefixLoader.CanRoll(), and Terraria.ModLoader.PrefixLoader.Roll().