TModLoader: Terraria.Item.ShimmerEffect
ShimmerEffect()
static void Terraria.Item.ShimmerEffect (Vector2 shimmerPositon) inline static
Definition at line 49878 of file Item.cs.
    {
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00de: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        SoundEngine.PlaySound(SoundID.Item176, (int)shimmerPositon.X, (int)shimmerPositon.Y);
        for (int i = 0; i < 20; i++)
        {
            int num = Dust.NewDust(shimmerPositon, 1, 1, 309);
            Main.dust[num].scale *= 1.2f;
            switch (Main.rand.Next(6))
            {
            case 0:
                Main.dust[num].color = new Color(255, 255, 210);
                break;
            case 1:
                Main.dust[num].color = new Color(190, 245, 255);
                break;
            case 2:
                Main.dust[num].color = new Color(255, 150, 255);
                break;
            default:
                Main.dust[num].color = new Color(190, 175, 255);
                break;
            }
        }
    }
References Terraria.Main.dust, Terraria.ID.SoundID.Item176, Terraria.Dust.NewDust(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.rand.
Referenced by Terraria.MessageBuffer.GetData(), Terraria.Item.GetShimmered(), and Terraria.NPC.GetShimmered().