TModLoader: Terraria.Item.DropCache
DropCache()
static void Terraria.Item.DropCache (IEntitySource reason, Vector2 pos, Vector2 spread, int t, bool stopCaching = true) inline static
Drops a cache previously created using M:Terraria.Item.StartCachingType(System.Int32).
If no cache of t exists, nothing happens.
Parameters
reason The source of the dropped cache.
pos The position to drop the cache in world coordinates.
spread The random spread of the dropped items in world coordinates.
t The item type (F:Terraria.Item.type) to drop.
stopCaching If true, then t will no longer be cached, allowing future drops to spawn as normal.
Definition at line 1198 of file Item.cs.
    {
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        if (cachedItemSpawnsByType[t] == -1)
        {
            return;
        }
        int num = cachedItemSpawnsByType[t];
        cachedItemSpawnsByType[t] = (stopCaching ? (-1) : 0);
        Item item = new Item();
        item.SetDefaults(t);
        while (num > 0)
        {
            int num2 = item.maxStack;
            if (num < num2)
            {
                num2 = num;
            }
            NewItem(reason, (int)pos.X, (int)pos.Y, (int)spread.X, (int)spread.Y, t, num2);
            num -= num2;
        }
    }
References Terraria.Item.Item(), Terraria.Item.cachedItemSpawnsByType, Terraria.Item.maxStack, Terraria.Item.NewItem(), and Terraria.Item.SetDefaults().
Referenced by Terraria.Wiring.MassWireOperationInner().