TModLoader: Terraria.Item.TurnToAir
TurnToAir()
void Terraria.Item.TurnToAir (bool fullReset = false) inline
Definition at line 51791 of file Item.cs.
    {
        if (fullReset)
        {
            SetDefaults();
            return;
        }
        type = 0;
        stack = 0;
        prefix = 0;
        netID = 0;
        dye = 0;
        shoot = 0;
        mountType = -1;
        ModItem = null;
        _globals = null;
    }
References Terraria.Item._globals, Terraria.Item.dye, Terraria.Item.mountType, Terraria.Item.netID, Terraria.Item.prefix, Terraria.Item.SetDefaults(), Terraria.Item.shoot, Terraria.Item.stack, and Terraria.Item.type.
Referenced by Terraria.GameContent.Events.DD2Event.ClearAllDD2EnergyCrystalsInChests(), Terraria.Player.ClearPlayerTempInfo(), Terraria.GameContent.MinecartDiggerHelper.ConsumeATrackItem(), Terraria.Recipe.ConsumeForCraft(), Terraria.Player.ConsumeItem(), Terraria.Item.DeserializeFrom(), Terraria.Player.DoCoins(), Terraria.Player.DropItems(), Terraria.Player.DropItems_End(), Terraria.Player.PickAmmo(), Terraria.Player.PlaceThing_ItemInExtractinator(), Terraria.Player.PlayDroppedItemAnimation(), Terraria.Player.PurgeDD2EnergyCrystals(), Terraria.Player.QuickBuff(), Terraria.Player.QuickHeal(), Terraria.Player.QuickMana(), Terraria.UI.ItemSorting.RefillItemStack(), Terraria.GameContent.Creative.CreativeUI.Reset(), Terraria.Item.SetDefaults(), Terraria.UI.ItemSorting.SortCoins(), Terraria.ModLoader.ItemLoader.TransferWithLimit(), Terraria.Main.TryFreeingElderSlime(), and Terraria.Player.Update().