TModLoader: Terraria.Item.UpdateItem_VisualEffects
UpdateItem_VisualEffects()
void Terraria.Item.UpdateItem_VisualEffects () inline private
    {
        //IL_06bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0706: Unknown result type (might be due to invalid IL or missing references)
        //IL_0710: Unknown result type (might be due to invalid IL or missing references)
        //IL_0729: Unknown result type (might be due to invalid IL or missing references)
        //IL_073d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0747: Unknown result type (might be due to invalid IL or missing references)
        //IL_0760: Unknown result type (might be due to invalid IL or missing references)
        //IL_0774: Unknown result type (might be due to invalid IL or missing references)
        //IL_077e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0820: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1747: Unknown result type (might be due to invalid IL or missing references)
        //IL_1832: Unknown result type (might be due to invalid IL or missing references)
        //IL_1841: Unknown result type (might be due to invalid IL or missing references)
        //IL_1872: Unknown result type (might be due to invalid IL or missing references)
        //IL_1881: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d32: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d37: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d55: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d70: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d75: Unknown result type (might be due to invalid IL or missing references)
        //IL_1da0: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dae: Unknown result type (might be due to invalid IL or missing references)
        //IL_1db4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e65: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ea9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1eae: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ed9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ee7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1eed: Unknown result type (might be due to invalid IL or missing references)
        if (type == 5043)
        {
            float num = (float)Main.rand.Next(90, 111) * 0.01f;
            num *= (Main.essScale + 0.5f) / 2f;
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.25f * num, 0.25f * num, 0.25f * num);
        }
        else if (type == 3191)
        {
            float num9 = (float)Main.rand.Next(90, 111) * 0.01f;
            num9 *= (Main.essScale + 0.5f) / 2f;
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.3f * num9, 0.1f * num9, 0.25f * num9);
        }
        else if (type == 520 || type == 3454)
        {
            float num10 = (float)Main.rand.Next(90, 111) * 0.01f;
            num10 *= Main.essScale;
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.5f * num10, 0.1f * num10, 0.25f * num10);
        }
        else if (type == 521 || type == 3455)
        {
            float num11 = (float)Main.rand.Next(90, 111) * 0.01f;
            num11 *= Main.essScale;
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.25f * num11, 0.1f * num11, 0.5f * num11);
        }
        else if (type == 547 || type == 3453)
        {
            float num12 = (float)Main.rand.Next(90, 111) * 0.01f;
            num12 *= Main.essScale;
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.5f * num12, 0.3f * num12, 0.05f * num12);
        }
        else if (type == 548)
        {
            float num13 = (float)Main.rand.Next(90, 111) * 0.01f;
            num13 *= Main.essScale;
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.1f * num13, 0.1f * num13, 0.6f * num13);
        }
        else if (type == 575)
        {
            float num14 = (float)Main.rand.Next(90, 111) * 0.01f;
            num14 *= Main.essScale;
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.1f * num14, 0.3f * num14, 0.5f * num14);
        }
        else if (type == 549)
        {
            float num15 = (float)Main.rand.Next(90, 111) * 0.01f;
            num15 *= Main.essScale;
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.1f * num15, 0.5f * num15, 0.2f * num15);
        }
        else if (type == 58 || type == 1734 || type == 1867)
        {
            float num16 = (float)Main.rand.Next(90, 111) * 0.01f;
            num16 *= Main.essScale * 0.5f;
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.5f * num16, 0.1f * num16, 0.1f * num16);
        }
        else if (type == 184 || type == 1735 || type == 1868 || type == 4143)
        {
            float num2 = (float)Main.rand.Next(90, 111) * 0.01f;
            num2 *= Main.essScale * 0.5f;
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.1f * num2, 0.1f * num2, 0.5f * num2);
        }
        else if (type == 522)
        {
            float num3 = (float)Main.rand.Next(90, 111) * 0.01f;
            num3 *= Main.essScale * 0.2f;
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.5f * num3, 1f * num3, 0.1f * num3);
        }
        else if (type == 1332)
        {
            float num4 = (float)Main.rand.Next(90, 111) * 0.01f;
            num4 *= Main.essScale * 0.2f;
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1f * num4, 1f * num4, 0.1f * num4);
        }
        else if (type == 3456)
        {
            Lighting.AddLight(base.Center, new Vector3(0.2f, 0.4f, 0.5f) * Main.essScale);
        }
        else if (type == 3457)
        {
            Lighting.AddLight(base.Center, new Vector3(0.4f, 0.2f, 0.5f) * Main.essScale);
        }
        else if (type == 3458)
        {
            Lighting.AddLight(base.Center, new Vector3(0.5f, 0.4f, 0.2f) * Main.essScale);
        }
        else if (type == 3459)
        {
            Lighting.AddLight(base.Center, new Vector3(0.2f, 0.2f, 0.5f) * Main.essScale);
        }
        else if (type == 501)
        {
            if (Main.rand.Next(6) == 0)
            {
                int num5 = Dust.NewDust(position, width, height, 55, 0f, 0f, 200, color);
                Dust obj = Main.dust[num5];
                obj.velocity *= 0.3f;
                Main.dust[num5].scale *= 0.5f;
            }
        }
        else if (type == 3822)
        {
            Lighting.AddLight(base.Center, 0.1f, 0.3f, 0.1f);
        }
        else if (type == 1970)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.75f, 0f, 0.75f);
        }
        else if (type == 1972)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0f, 0f, 0.75f);
        }
        else if (type == 1971)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.75f, 0.75f, 0f);
        }
        else if (type == 1973)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0f, 0.75f, 0f);
        }
        else if (type == 1974)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.75f, 0f, 0f);
        }
        else if (type == 1975)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.75f, 0.75f, 0.75f);
        }
        else if (type == 1976)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.75f, 0.375f, 0f);
        }
        else if (type == 2679)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.6f, 0f, 0.6f);
        }
        else if (type == 2687)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0f, 0f, 0.6f);
        }
        else if (type == 2689)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.6f, 0.6f, 0f);
        }
        else if (type == 2683)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0f, 0.6f, 0f);
        }
        else if (type == 2685)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.6f, 0f, 0f);
        }
        else if (type == 2681)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.6f, 0.6f, 0.6f);
        }
        else if (type == 2677)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.6f, 0.375f, 0f);
        }
        else if (type == 105)
        {
            if (!wet)
            {
                Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1f, 0.95f, 0.8f);
            }
        }
        else if (type == 2701)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.7f, 0.65f, 0.55f);
        }
        else if (createTile == 4)
        {
            int torchID = placeStyle;
            if ((!wet && ItemID.Sets.Torches[type]) || ItemID.Sets.WaterTorches[type])
            {
                Lighting.AddLight(base.Center, torchID);
            }
        }
        else if (type == 3114)
        {
            if (!wet)
            {
                Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1f, 0f, 1f);
            }
        }
        else if (type == 1245)
        {
            if (!wet)
            {
                Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1f, 0.5f, 0f);
            }
        }
        else if (type == 433)
        {
            if (!wet)
            {
                Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.5f * Main.demonTorch + 1f * (1f - Main.demonTorch), 0.3f, 1f * Main.demonTorch + 0.5f * (1f - Main.demonTorch));
            }
        }
        else if (type == 523)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.85f, 1.2f, 0.7f);
        }
        else if (type == 974)
        {
            if (!wet)
            {
                Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.75f, 0.85f, 1.4f);
            }
        }
        else if (type == 1333)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1.25f, 1.25f, 0.7f);
        }
        else if (type == 4383)
        {
            if (!wet)
            {
                Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1.4f, 0.85f, 0.55f);
            }
        }
        else if (type == 5293)
        {
            if (!wet)
            {
                Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.25f, 0.65f, 1f);
            }
        }
        else if (type == 5353)
        {
            if (!wet)
            {
                Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.81f, 0.72f, 1f);
            }
        }
        else if (type == 4384)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.25f, 1.3f, 0.8f);
        }
        else if (type == 3045)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), (float)Main.DiscoR / 255f, (float)Main.DiscoG / 255f, (float)Main.DiscoB / 255f);
        }
        else if (type == 3004)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.95f, 0.65f, 1.3f);
        }
        else if (type == 2274)
        {
            float r = 0.75f;
            float g = 1.3499999f;
            float b = 1.5f;
            if (!wet)
            {
                Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), r, g, b);
            }
        }
        else if (type >= 427 && type <= 432)
        {
            if (!wet)
            {
                float r2 = 0f;
                float g2 = 0f;
                float b2 = 0f;
                int num17 = type - 426;
                if (num17 == 1)
                {
                    r2 = 0.1f;
                    g2 = 0.2f;
                    b2 = 1.1f;
                }
                if (num17 == 2)
                {
                    r2 = 1f;
                    g2 = 0.1f;
                    b2 = 0.1f;
                }
                if (num17 == 3)
                {
                    r2 = 0f;
                    g2 = 1f;
                    b2 = 0.1f;
                }
                if (num17 == 4)
                {
                    r2 = 0.9f;
                    g2 = 0f;
                    b2 = 0.9f;
                }
                if (num17 == 5)
                {
                    r2 = 1.3f;
                    g2 = 1.3f;
                    b2 = 1.3f;
                }
                if (num17 == 6)
                {
                    r2 = 0.9f;
                    g2 = 0.9f;
                    b2 = 0f;
                }
                Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), r2, g2, b2);
            }
        }
        else if (type == 2777 || type == 2778 || type == 2779 || type == 2780 || type == 2781 || type == 2760 || type == 2761 || type == 2762 || type == 3524)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.4f, 0.16f, 0.36f);
        }
        else if (type == 2772 || type == 2773 || type == 2774 || type == 2775 || type == 2776 || type == 2757 || type == 2758 || type == 2759 || type == 3523)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0f, 0.36f, 0.4f);
        }
        else if (type == 2782 || type == 2783 || type == 2784 || type == 2785 || type == 2786 || type == 2763 || type == 2764 || type == 2765 || type == 3522)
        {
            Lighting.AddLight((int)((position.X + (float)(width / 2)) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.5f, 0.25f, 0.05f);
        }
        else if (type == 3462 || type == 3463 || type == 3464 || type == 3465 || type == 3466 || type == 3381 || type == 3382 || type == 3383 || type == 3525)
        {
            Lighting.AddLight(base.Center, 0.3f, 0.3f, 0.2f);
        }
        else if (type == 41)
        {
            if (!wet)
            {
                Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1f, 0.75f, 0.55f);
            }
        }
        else if (type == 988)
        {
            if (!wet)
            {
                Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.35f, 0.65f, 1f);
            }
        }
        else if (type == 1326)
        {
            Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 1f, 0.1f, 0.8f);
        }
        else if (type == 5335)
        {
            Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.85f, 0.1f, 0.8f);
        }
        else if (type >= 5140 && type <= 5146)
        {
            float num6 = 1f;
            float num7 = 1f;
            float num8 = 1f;
            switch (type)
            {
            case 5140:
                num6 *= 0.9f;
                num7 *= 0.8f;
                num8 *= 0.1f;
                break;
            case 5141:
                num6 *= 0.25f;
                num7 *= 0.1f;
                num8 *= 0f;
                break;
            case 5142:
                num6 *= 0f;
                num7 *= 0.25f;
                num8 *= 0f;
                break;
            case 5143:
                num6 *= 0f;
                num7 *= 0.16f;
                num8 *= 0.34f;
                break;
            case 5144:
                num6 *= 0.3f;
                num7 *= 0f;
                num8 *= 0.17f;
                break;
            case 5145:
                num6 *= 0.3f;
                num7 *= 0f;
                num8 *= 0.35f;
                break;
            case 5146:
                num6 *= (float)Main.DiscoR / 255f;
                num7 *= (float)Main.DiscoG / 255f;
                num8 *= (float)Main.DiscoB / 255f;
                break;
            }
            Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), num6, num7, num8);
        }
        else if (type == 282)
        {
            Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.7f, 1f, 0.8f);
        }
        else if (type == 286)
        {
            Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.7f, 0.8f, 1f);
        }
        else if (type == 3112)
        {
            Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1f, 0.6f, 0.85f);
        }
        else if (type == 4776)
        {
            Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.7f, 0f, 1f);
        }
        else if (type == 3002)
        {
            Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 1.05f, 0.95f, 0.55f);
        }
        else if (type == 331)
        {
            Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.55f, 0.75f, 0.6f);
        }
        else if (type == 183)
        {
            Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.15f, 0.45f, 0.9f);
        }
        else if (type == 75)
        {
            Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.8f, 0.7f, 0.1f);
            if (timeSinceItemSpawned % 12 == 0)
            {
                Dust dust = Dust.NewDustPerfect(base.Center + new Vector2(0f, (float)height * 0.2f) + Main.rand.NextVector2CircularEdge(width, (float)height * 0.6f) * (0.3f + Main.rand.NextFloat() * 0.5f), 228, (Vector2?)new Vector2(0f, (0f - Main.rand.NextFloat()) * 0.3f - 1.5f), 127, default(Color), 1f);
                dust.scale = 0.5f;
                dust.fadeIn = 1.1f;
                dust.noGravity = true;
                dust.noLight = true;
            }
        }
        else if (ItemID.Sets.BossBag[type])
        {
            Lighting.AddLight((int)((position.X + (float)width) / 16f), (int)((position.Y + (float)(height / 2)) / 16f), 0.4f, 0.4f, 0.4f);
            if (timeSinceItemSpawned % 12 == 0)
            {
                Dust dust2 = Dust.NewDustPerfect(base.Center + new Vector2(0f, (float)height * -0.1f) + Main.rand.NextVector2CircularEdge((float)width * 0.6f, (float)height * 0.6f) * (0.3f + Main.rand.NextFloat() * 0.5f), 279, (Vector2?)new Vector2(0f, (0f - Main.rand.NextFloat()) * 0.3f - 1.5f), 127, default(Color), 1f);
                dust2.scale = 0.5f;
                dust2.fadeIn = 1.1f;
                dust2.noGravity = true;
                dust2.noLight = true;
                dust2.alpha = 0;
            }
        }
    }
References Terraria.Lighting.AddLight(), Terraria.ID.ItemID.Sets.BossBag, Terraria.Item.color, Terraria.Item.createTile, Terraria.Main.demonTorch, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.Main.dust, Terraria.Main.essScale, Terraria.Entity.height, Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Item.placeStyle, Terraria.Entity.position, Terraria.Main.rand, Terraria.Dust.scale, Terraria.Item.timeSinceItemSpawned, Terraria.ID.ItemID.Sets.Torches, Terraria.Item.type, Terraria.ID.ItemID.Sets.WaterTorches, Terraria.Entity.wet, and Terraria.Entity.width.
Referenced by Terraria.Item.UpdateItem().