TModLoader: Terraria.Item.UpdateItem
UpdateItem()
void Terraria.Item.UpdateItem (int i) inline
Definition at line 49933 of file Item.cs.
    {
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_0358: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0297: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0307: Unknown result type (might be due to invalid IL or missing references)
        //IL_030c: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_032f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0648: Unknown result type (might be due to invalid IL or missing references)
        //IL_064e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0653: Unknown result type (might be due to invalid IL or missing references)
        //IL_0658: Unknown result type (might be due to invalid IL or missing references)
        //IL_0634: Unknown result type (might be due to invalid IL or missing references)
        //IL_0639: Unknown result type (might be due to invalid IL or missing references)
        //IL_063a: Unknown result type (might be due to invalid IL or missing references)
        //IL_063f: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0352: Unknown result type (might be due to invalid IL or missing references)
        whoAmI = i;
        if (Main.timeItemSlotCannotBeReusedFor[i] > 0)
        {
            if (Main.netMode == 2)
            {
                Main.timeItemSlotCannotBeReusedFor[i]--;
                return;
            }
            Main.timeItemSlotCannotBeReusedFor[i] = 0;
        }
        if (!active)
        {
            return;
        }
        if (instanced)
        {
            if (Main.netMode == 2)
            {
                active = false;
                return;
            }
            keepTime = 6000;
            ownTime = 0;
            noGrabDelay = 0;
            playerIndexTheItemIsReservedFor = Main.myPlayer;
        }
        if (Main.netMode == 0)
        {
            playerIndexTheItemIsReservedFor = Main.myPlayer;
        }
        float gravity = 0.1f;
        float maxFallSpeed = 7f;
        if (Main.netMode == 1)
        {
            int num = (int)(position.X + (float)(width / 2)) / 16;
            int num2 = (int)(position.Y + (float)(height / 2)) / 16;
            if (num >= 0 && num2 >= 0 && num < Main.maxTilesX && num2 < Main.maxTilesY && !Main.sectionManager.TileLoaded(num, num2))
            {
                gravity = 0f;
                velocity.X = 0f;
                velocity.Y = 0f;
            }
        }
        Vector2 wetVelocity = velocity * 0.5f;
        if (shimmerWet)
        {
            gravity = 0.065f;
            maxFallSpeed = 4f;
            wetVelocity = velocity * 0.375f;
        }
        else if (honeyWet)
        {
            gravity = 0.05f;
            maxFallSpeed = 3f;
            wetVelocity = velocity * 0.25f;
        }
        else if (wet)
        {
            gravity = 0.08f;
            maxFallSpeed = 5f;
        }
        if (ownTime > 0)
        {
            ownTime--;
        }
        else
        {
            ownIgnore = -1;
        }
        if (keepTime > 0)
        {
            keepTime--;
        }
        if (!beingGrabbed)
        {
            if (shimmered)
            {
                if (Main.rand.Next(30) == 0)
                {
                    int num3 = Dust.NewDust(position, width, height, 309);
                    Main.dust[num3].position.X += Main.rand.Next(-8, 5);
                    Main.dust[num3].position.Y += Main.rand.Next(-8, 5);
                    Main.dust[num3].scale *= 1.1f;
                    Dust obj = Main.dust[num3];
                    obj.velocity *= 0.3f;
                    switch (Main.rand.Next(6))
                    {
                    case 0:
                        Main.dust[num3].color = new Color(255, 255, 210);
                        break;
                    case 1:
                        Main.dust[num3].color = new Color(190, 245, 255);
                        break;
                    case 2:
                        Main.dust[num3].color = new Color(255, 150, 255);
                        break;
                    default:
                        Main.dust[num3].color = new Color(190, 175, 255);
                        break;
                    }
                }
                Lighting.AddLight(base.Center, (1f - shimmerTime) * 0.8f, (1f - shimmerTime) * 0.8f, (1f - shimmerTime) * 0.8f);
                gravity = 0f;
                if (shimmerWet)
                {
                    if (velocity.Y > -4f)
                    {
                        velocity.Y -= 0.05f;
                    }
                }
                else
                {
                    int num4 = 2;
                    int num5 = (int)(base.Center.X / 16f);
                    int num6 = (int)(base.Center.Y / 16f);
                    bool flag = false;
                    for (int j = num6; j < num6 + num4; j++)
                    {
                        if (WorldGen.InWorld(num5, j) && Main.tile[num5, j] != null && Main.tile[num5, j].shimmer() && Main.tile[num5, j].liquid > 0)
{
                            flag = true;
                            break;
                        }
                    }
                    if (flag)
                    {
                        if (velocity.Y > -4f)
{
                            velocity.Y -= 0.05f;
                        }
                    }
                    else
                    {
                        velocity.Y *= 0.9f;
                    }
                }
            }
            if (shimmerWet && !shimmered)
            {
                Shimmering();
            }
            else if (shimmerTime > 0f)
            {
                shimmerTime -= 0.01f;
                if (shimmerTime < 0f)
                {
                    shimmerTime = 0f;
                }
            }
            if (shimmerTime == 0f)
            {
                TryCombiningIntoNearbyItems(i);
            }
            if (timeLeftInWhichTheItemCannotBeTakenByEnemies > 0)
            {
                timeLeftInWhichTheItemCannotBeTakenByEnemies--;
            }
            if (timeLeftInWhichTheItemCannotBeTakenByEnemies == 0 && Main.netMode != 2 && playerIndexTheItemIsReservedFor == Main.myPlayer)
            {
                GetPickedUpByMonsters_Special(i);
                if (Main.expertMode && IsACoin)
                {
                    GetPickedUpByMonsters_Money(i);
                }
            }
            MoveInWorld(gravity, maxFallSpeed, ref wetVelocity, i);
            if (lavaWet)
            {
                CheckLavaDeath(i);
            }
            DespawnIfMeetingConditions(i);
        }
        else
        {
            beingGrabbed = false;
        }
        UpdateItem_VisualEffects();
        if (timeSinceItemSpawned < 2147483547)
        {
            int num7 = ItemID.Sets.ItemSpawnDecaySpeed[type];
            timeSinceItemSpawned += num7;
        }
        ItemLoader.PostUpdate(this);
        if (Main.netMode == 2 && playerIndexTheItemIsReservedFor != Main.myPlayer)
        {
            timeSinceTheItemHasBeenReservedForSomeone++;
            if (timeSinceTheItemHasBeenReservedForSomeone >= 300)
            {
                timeSinceTheItemHasBeenReservedForSomeone = 0;
                NetMessage.SendData(39, playerIndexTheItemIsReservedFor, -1, null, i);
                playerIndexTheItemIsReservedFor = 255;
            }
        }
        if (wet)
        {
            position += wetVelocity;
        }
        else
        {
            position += velocity;
        }
        if (noGrabDelay > 0)
        {
            noGrabDelay--;
        }
    }
References Terraria.Entity.active, Terraria.Lighting.AddLight(), Terraria.Item.beingGrabbed, Terraria.Item.CheckLavaDeath(), Terraria.Item.DespawnIfMeetingConditions(), Terraria.Main.dust, Terraria.Main.expertMode, Terraria.Item.GetPickedUpByMonsters_Money(), Terraria.Item.GetPickedUpByMonsters_Special(), Terraria.Entity.height, Terraria.Entity.honeyWet, Terraria.Item.instanced, Terraria.WorldGen.InWorld(), Terraria.Item.IsACoin, Terraria.ID.ItemID.Sets.ItemSpawnDecaySpeed, Terraria.Item.keepTime, Terraria.Entity.lavaWet, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Item.MoveInWorld(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Item.noGrabDelay, Terraria.Item.ownIgnore, Terraria.Item.ownTime, Terraria.Item.playerIndexTheItemIsReservedFor, Terraria.Entity.position, Terraria.ModLoader.ItemLoader.PostUpdate(), Terraria.Main.rand, Terraria.Main.sectionManager, Terraria.NetMessage.SendData(), Terraria.Item.shimmered, Terraria.Item.Shimmering(), Terraria.Item.shimmerTime, Terraria.Entity.shimmerWet, Terraria.Main.tile, Terraria.Main.timeItemSlotCannotBeReusedFor, Terraria.Item.timeLeftInWhichTheItemCannotBeTakenByEnemies, Terraria.Item.timeSinceItemSpawned, Terraria.Item.timeSinceTheItemHasBeenReservedForSomeone, Terraria.Item.TryCombiningIntoNearbyItems(), Terraria.Item.type, Terraria.Item.UpdateItem_VisualEffects(), Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Entity.whoAmI, and Terraria.Entity.width.