TModLoader: Terraria.Item.DeserializeFrom
DeserializeFrom()
void Terraria.Item.DeserializeFrom (BinaryReader reader, ItemSerializationContext context) inline
Definition at line 51837 of file Item.cs.
    {
        if (context == ItemSerializationContext.SavingAndLoading)
        {
            netDefaults(reader.ReadInt32());
            stack = reader.ReadInt32();
            Prefix(reader.ReadByte());
        }
        if (type >= ItemLoader.ItemCount)
        {
            TurnToAir();
        }
    }
References Terraria.ModLoader.ItemLoader.ItemCount, Terraria.Item.netDefaults(), Terraria.Item.Prefix(), Terraria.Item.stack, Terraria.Item.TurnToAir(), and Terraria.Item.type.
Referenced by Terraria.EquipmentLoadout.Deserialize(), and Terraria.Player.LoadTemporaryItemSlotContents().