TModLoader: Terraria.Item.NewItem
NewItem() [7/10]
static int Terraria.Item.NewItem (IEntitySource source, Vector2 pos, Vector2 randomBox, int Type, int Stack = 1, bool noBroadcast = false, int prefixGiven = 0, bool noGrabDelay = false, bool reverseLookup = false) inline static
This particular overload uses two Vector2 to determine the actual spawn position.
Returns
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        return NewItem(source, (int)pos.X, (int)pos.Y, (int)randomBox.X, (int)randomBox.Y, Type, Stack, noBroadcast, prefixGiven, noGrabDelay, reverseLookup);
    }
References Terraria.Item.NewItem(), Terraria.Item.noGrabDelay, and Terraria.Item.Type.
Referenced by Terraria.Projectile.AI_061_FishingBobber_GiveItemToPlayer(), Terraria.Projectile.AI_192_JuminoAnimation(), Terraria.NPC.AI_87_BigMimic_ShootItem(), Terraria.Player.ApplyNPCOnHitEffects(), Terraria.Lang.BartenderHelpText(), Terraria.NPC.CatchNPC(), Terraria.WorldGen.Check1x2(), Terraria.WorldGen.Check1x2Top(), Terraria.WorldGen.Check1xX(), Terraria.WorldGen.Check2x1(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.Check2x2Style(), Terraria.WorldGen.Check2x3Wall(), Terraria.WorldGen.Check2x5(), Terraria.WorldGen.Check2xX(), Terraria.WorldGen.Check3x1(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.Check3x2Wall(), Terraria.WorldGen.Check3x3(), Terraria.WorldGen.Check3x3Wall(), Terraria.WorldGen.Check3x4(), Terraria.WorldGen.Check3x5(), Terraria.WorldGen.Check3x6(), Terraria.WorldGen.Check4x2(), Terraria.WorldGen.Check4x3Wall(), Terraria.WorldGen.Check5x4(), Terraria.WorldGen.Check6x3(), Terraria.WorldGen.Check6x4Wall(), Terraria.WorldGen.CheckBanner(), Terraria.WorldGen.CheckCannon(), Terraria.WorldGen.CheckChand(), Terraria.WorldGen.CheckChest(), Terraria.WorldGen.CheckGnome(), Terraria.WorldGen.CheckJunglePlant(), Terraria.WorldGen.CheckMan(), Terraria.WorldGen.CheckMB(), Terraria.WorldGen.CheckOrb(), Terraria.WorldGen.CheckSign(), Terraria.WorldGen.CheckSunflower(), Terraria.WorldGen.CheckSuper(), Terraria.WorldGen.CheckTallGate(), Terraria.WorldGen.CheckTrapDoor(), Terraria.WorldGen.CheckWeaponsRack(), Terraria.WorldGen.CheckWoman(), Terraria.WorldGen.CheckXmasTree(), Terraria.NPC.CountKillForBannersAndDropThem(), Terraria.Projectile.Damage(), Terraria.NPC.DoDeathEvents(), Terraria.NPC.DoDeathEvents_DropBossPotionsAndHearts(), Terraria.Item.DropCache(), Terraria.Player.DropCoins(), Terraria.WorldGen.DropDoorItem(), Terraria.Projectile.DropGeodeLoot(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.DropItem(), Terraria.GameContent.Tile_Entities.TEItemFrame.DropItem(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.DropItem(), Terraria.Player.DropItem(), Terraria.GameContent.ItemDropRules.CommonCode.DropItem(), Terraria.Player.dropItemCheck(), Terraria.GameContent.ItemDropRules.CommonCode.DropItemForEachInteractingPlayerOnThePlayer(), Terraria.Player.DropItemFromExtractinator(), Terraria.NPC.DropItemInstanced(), Terraria.GameContent.ItemDropRules.CommonCode.DropItemLocalPerClientAndSetNPCMoneyTo0(), Terraria.Player.DropSelectedItem(), Terraria.GameContent.Events.DD2Event.DropStarterCrystals(), Terraria.WorldGen.dropXmasTree(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEHatRack.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Framing_CheckTile(), Terraria.Player.GetAnglerReward(), Terraria.MessageBuffer.GetData(), Terraria.Player.GetDyeTraderReward(), Terraria.ModLoader.TileLoader.GetItemDrops(), Terraria.Item.GetShimmered(), Terraria.NPC.GetShimmered(), Terraria.Main.GUIChatDrawInner(), Terraria.Player.ItemCheck_CutTiles(), Terraria.Projectile.Kill(), Terraria.WorldGen.KillActuator(), Terraria.Player.KillMe(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillTile_DropItems(), Terraria.WorldGen.KillWall_DropItems(), Terraria.WorldGen.KillWire(), Terraria.WorldGen.KillWire2(), Terraria.WorldGen.KillWire3(), Terraria.WorldGen.KillWire4(), Terraria.Item.NewItem(), Terraria.Item.NewItem(), Terraria.Item.NewItem(), Terraria.Item.NewItem(), Terraria.Item.NewItem(), Terraria.Item.NewItem(), Terraria.Item.NewItem(), Terraria.Item.NewItem(), Terraria.NPC.NPCLoot_DropCommonLifeAndMana(), Terraria.NPC.NPCLoot_DropHeals(), Terraria.NPC.NPCLoot_DropMoney(), Terraria.Player.PlaceThing_PaintScrapper_LongMoss(), Terraria.Player.PutItemInInventoryFromItemUsage(), Terraria.Player.QuickSpawnClonedItem(), Terraria.Player.QuickSpawnItem(), Terraria.ModLoader.Default.StartBag.RightClick(), Terraria.WorldGen.ShakeTree(), Terraria.WorldGen.SpawnThingsFromPot(), Terraria.WorldGen.ToggleGemLock(), Terraria.Player.TorchAttack(), Terraria.Player.TryDroppingSingleItem(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.TryPlacing(), Terraria.GameContent.Tile_Entities.TEItemFrame.TryPlacing(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.TryPlacing(), Terraria.Player.TryToPoop(), Terraria.Player.Update(), and Terraria.Projectile.UseGasTrapInChest().