TModLoader: Terraria.Item.BannerToNPC
BannerToNPC()
static int Terraria.Item.BannerToNPC (int i) inline static
Converts a banner ID into the equivalent NPC type (F:Terraria.NPC.type).
Parameters
i The banner ID to convert.
Returns
The NPC type associated with the given banner ID, or F:Terraria.ID.NPCID.None for an invalid banner ID.
Definition at line 2905 of file Item.cs.
    {
        switch (i)
        {
        case 1:
            return 102;
        case 2:
            return 250;
        case 3:
            return 257;
        case 4:
            return 69;
        case 5:
            return 157;
        case 6:
            return 77;
        case 7:
            return 49;
        case 8:
            return 74;
        case 9:
            return 163;
        case 10:
            return 241;
        case 11:
            return 242;
        case 12:
            return 239;
        case 13:
            return 39;
        case 14:
            return 46;
        case 15:
            return 120;
        case 16:
            return 85;
        case 17:
            return 109;
        case 18:
            return 47;
        case 19:
            return 57;
        case 20:
            return 67;
        case 21:
            return 173;
        case 22:
            return 179;
        case 23:
            return 83;
        case 24:
            return 62;
        case 25:
            return 2;
        case 26:
            return 177;
        case 27:
            return 6;
        case 28:
            return 84;
        case 29:
            return 161;
        case 30:
            return 181;
        case 31:
            return 182;
        case 32:
            return 224;
        case 33:
            return 226;
        case 34:
            return 162;
        case 35:
            return 259;
        case 36:
            return 256;
        case 37:
            return 122;
        case 38:
            return 27;
        case 39:
            return 29;
        case 40:
            return 26;
        case 41:
            return 73;
        case 42:
            return 28;
        case 43:
            return 55;
        case 44:
            return 48;
        case 45:
            return 60;
        case 46:
            return 174;
        case 47:
            return 42;
        case 48:
            return 169;
        case 49:
            return 206;
        case 50:
            return 24;
        case 51:
            return 63;
        case 52:
            return 236;
        case 53:
            return 199;
        case 54:
            return 43;
        case 55:
            return 23;
        case 56:
            return 205;
        case 57:
            return 78;
        case 58:
            return 258;
        case 59:
            return 252;
        case 60:
            return 170;
        case 61:
            return 58;
        case 62:
            return 212;
        case 63:
            return 75;
        case 64:
            return 223;
        case 65:
            return 253;
        case 66:
            return 65;
        case 67:
            return 21;
        case 68:
            return 32;
        case 69:
            return 1;
        case 70:
            return 185;
        case 71:
            return 164;
        case 72:
            return 254;
        case 73:
            return 166;
        case 74:
            return 153;
        case 75:
            return 141;
        case 76:
            return 225;
        case 77:
            return 86;
        case 78:
            return 158;
        case 79:
            return 61;
        case 80:
            return 196;
        case 81:
            return 104;
        case 82:
            return 155;
        case 83:
            return 98;
        case 84:
            return 10;
        case 85:
            return 82;
        case 86:
            return 87;
        case 87:
            return 3;
        case 88:
            return 175;
        case 89:
            return 197;
        case 91:
            return 273;
        case 92:
            return 379;
        case 93:
            return 438;
        case 95:
            return 287;
        case 96:
            return 101;
        case 97:
            return 217;
        case 98:
            return 168;
        case 99:
            return 81;
        case 100:
            return 94;
        case 101:
            return 183;
        case 102:
            return 34;
        case 103:
            return 218;
        case 104:
            return 7;
        case 105:
            return 285;
        case 106:
            return 52;
        case 107:
            return 71;
        case 108:
            return 288;
        case 109:
            return 350;
        case 110:
            return 347;
        case 111:
            return 251;
        case 112:
            return 352;
        case 113:
            return 316;
        case 114:
            return 93;
        case 115:
            return 289;
        case 116:
            return 152;
        case 117:
            return 342;
        case 118:
            return 111;
        case 120:
            return 315;
        case 121:
            return 277;
        case 122:
            return 329;
        case 123:
            return 304;
        case 124:
            return 150;
        case 125:
            return 243;
        case 126:
            return 147;
        case 127:
            return 268;
        case 128:
            return 137;
        case 129:
            return 138;
        case 130:
            return 51;
        case 132:
            return 351;
        case 133:
            return 219;
        case 134:
            return 151;
        case 135:
            return 59;
        case 136:
            return 381;
        case 137:
            return 388;
        case 138:
            return 386;
        case 139:
            return 389;
        case 140:
            return 385;
        case 141:
            return 383;
        case 142:
            return 382;
        case 143:
            return 390;
        case 144:
            return 387;
        case 145:
            return 144;
        case 146:
            return 16;
        case 147:
            return 283;
        case 148:
            return 348;
        case 149:
            return 290;
        case 150:
            return 148;
        case 151:
            return -4;
        case 152:
            return 330;
        case 153:
            return 140;
        case 154:
            return 341;
        case 156:
            return 281;
        case 157:
            return 244;
        case 158:
            return 301;
        case 160:
            return 172;
        case 161:
            return 269;
        case 162:
            return 305;
        case 163:
            return 391;
        case 164:
            return 110;
        case 165:
            return 293;
        case 166:
            return 291;
        case 167:
            return 121;
        case 168:
            return 56;
        case 169:
            return 145;
        case 170:
            return 143;
        case 171:
            return 184;
        case 172:
            return 204;
        case 173:
            return 326;
        case 174:
            return 221;
        case 175:
            return 292;
        case 176:
            return 53;
        case 177:
            return 45;
        case 178:
            return 44;
        case 179:
            return 167;
        case 180:
            return 380;
        case 184:
            return 343;
        case 185:
            return 338;
        case 90:
            return -6;
        case 119:
            return -3;
        case 131:
            return -10;
        case 155:
            return -7;
        case 159:
            return -8;
        case 183:
            return -9;
        case 186:
            return 471;
        case 187:
            return 498;
        case 188:
            return 496;
        case 189:
            return 494;
        case 190:
            return 462;
        case 191:
            return 461;
        case 192:
            return 468;
        case 193:
            return 477;
        case 195:
            return 469;
        case 196:
            return 460;
        case 197:
            return 466;
        case 198:
            return 467;
        case 199:
            return 463;
        case 201:
            return 480;
        case 202:
            return 481;
        case 203:
            return 483;
        case 204:
            return 482;
        case 205:
            return 489;
        case 206:
            return 490;
        case 207:
            return 513;
        case 208:
            return 510;
        case 209:
            return 581;
        case 210:
            return 580;
        case 211:
            return 524;
        case 212:
            return 529;
        case 213:
            return 533;
        case 214:
            return 532;
        case 215:
            return 530;
        case 216:
            return 411;
        case 217:
            return 402;
        case 218:
            return 407;
        case 219:
            return 409;
        case 220:
            return 406;
        case 221:
            return 405;
        case 222:
            return 418;
        case 223:
            return 417;
        case 224:
            return 412;
        case 225:
            return 416;
        case 226:
            return 415;
        case 227:
            return 419;
        case 228:
            return 424;
        case 229:
            return 421;
        case 230:
            return 420;
        case 231:
            return 423;
        case 232:
            return 428;
        case 233:
            return 426;
        case 234:
            return 427;
        case 235:
            return 429;
        case 236:
            return 425;
        case 237:
            return 216;
        case 238:
            return 214;
        case 239:
            return 213;
        case 240:
            return 215;
        case 241:
            return 520;
        case 242:
            return 156;
        case 243:
            return 64;
        case 244:
            return 103;
        case 245:
            return 79;
        case 246:
            return 80;
        case 247:
            return 31;
        case 248:
            return 154;
        case 249:
            return 537;
        case 250:
            return 220;
        case 251:
            return 541;
        case 252:
            return 542;
        case 253:
            return 543;
        case 254:
            return 544;
        case 255:
            return 545;
        case 256:
            return 546;
        case 257:
            return 555;
        case 258:
            return 552;
        case 259:
            return 566;
        case 260:
            return 570;
        case 261:
            return 574;
        case 262:
            return 572;
        case 263:
            return 568;
        case 264:
            return 558;
        case 265:
            return 561;
        case 266:
            return 578;
        case 267:
            return 536;
        case 268:
            return 586;
        case 269:
            return 587;
        case 270:
            return 619;
        case 271:
            return 621;
        case 272:
            return 620;
        case 273:
            return 618;
        case 274:
            return 628;
        case 275:
            return 624;
        case 276:
            return 631;
        case 277:
            return 630;
        case 278:
            return 635;
        case 279:
            return 634;
        case 280:
            return 582;
        case 281:
            return 464;
        case 282:
            return 465;
        case 283:
            return 470;
        case 284:
            return 473;
        case 285:
            return 474;
        case 286:
            return 475;
        case 287:
            return 176;
        case 288:
            return 133;
        case 289:
            return 676;
        default:
            if (i >= NPCID.Count)
            {
                return i;
            }
            return 0;
        }
    }
References Terraria.ID.NPCID.Count.
Referenced by Terraria.NPC.CountKillForBannersAndDropThem(), Terraria.Main.DrawInfoAccs(), and Terraria.Main.MouseText_DrawBuffTooltip().