TModLoader: Terraria.Item.Clone
Clone()
Item Terraria.Item.Clone () inline
Definition at line 51739 of file Item.cs.
    {
        if (cloningDisabled != null)
        {
            throw new Exception(cloningDisabled);
        }
        Item newItem = (Item)MemberwiseClone();
        newItem.ModItem = ModItem?.Clone(newItem);
        newItem._globals = _globals?.Select((GlobalItem g) => g?.Clone(this, newItem)).ToArray();
        return newItem;
    }
References Terraria.Item.Item(), Terraria.Item._globals, Terraria.ModLoader.ModType< TEntity, TModType >.Clone(), and Terraria.Item.cloningDisabled.
Referenced by Terraria.UI.ItemSlot.AccessorySwap(), Terraria.UI.ItemSlot.ArmorSwap(), Terraria.Recipe.Clone(), Terraria.Recipe.ConsumeForCraft(), Terraria.Item.DeepClone(), Terraria.UI.ChestUI.DepositAll(), Terraria.Main.DrawInventory(), Terraria.Player.DropCoins(), Terraria.Player.dropItemCheck(), Terraria.UI.ItemSlot.DyeSwap(), Terraria.UI.ItemSlot.EquipSwap(), Terraria.ModLoader.NPCShop.FillShop(), Terraria.ModLoader.NPCShop.FillShop(), Terraria.Main.HoverOverCraftingItemButton(), Terraria.Player.ItemCheck_Inner(), Terraria.Player.ItemCheckWrapped(), Terraria.UI.ItemSlot.ModSlotDyeSwap(), Terraria.GameContent.UI.Chat.ItemTagHandler.ItemSnippet.OnHover(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEItemFrame.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.PlaceItemInFrame(), Terraria.Player.PlaceWeapon(), Terraria.Chest.PutItemInNearbyChest(), Terraria.Player.SellItem(), Terraria.Player.SetPlayerDataToOutOfClassFields(), and Terraria.ModLoader.ItemLoader.TransferWithLimit().