TModLoader: Terraria.Item.CanHavePrefixes
CanHavePrefixes()
bool Terraria.Item.CanHavePrefixes () inline
Determines if this T:Terraria.Item can receive prefixes.
Returns
true if this T:Terraria.Item is allowed to receive prefixes, false otherwise.
    {
        if (type != 0 && ItemID.Sets.CanGetPrefixes[type] && (maxStack == 1 || AllowReforgeForStackableItem) && ammo == 0)
        {
            if (damage <= 0)
            {
                return IsAPrefixableAccessory();
            }
            return true;
        }
        return false;
    }
References Terraria.Item.AllowReforgeForStackableItem, Terraria.Item.ammo, Terraria.ID.ItemID.Sets.CanGetPrefixes, Terraria.Item.damage, Terraria.Item.IsAPrefixableAccessory(), Terraria.Item.maxStack, and Terraria.Item.type.
Referenced by Terraria.Item.CanRollPrefix(), and Terraria.Item.Prefix().