TModLoader: Terraria.Item.DefaultToGolfBall
DefaultToGolfBall()
void Terraria.Item.DefaultToGolfBall (int projid) inline
This method sets a variety of Item values common to golf ball items.
Specifically:
shoot = projid ; useStyle = F:Terraria.ID.ItemUseStyleID.Swing; shootSpeed = 12f; width = 18; height = 20; maxStack = 1; UseSound = F:Terraria.ID.SoundID.Item1; useAnimation = 15; useTime = 15; noUseGraphic = true; noMelee = true; accessory = true; SetShopValues(ItemRarityColor.Green2, buyPrice(0, 1)); hasVanityEffects = true;
Parameters
projid
Definition at line 39708 of file Item.cs.
    {
        shoot = projid;
        useStyle = 1;
        shootSpeed = 12f;
        width = 18;
        height = 20;
        maxStack = 1;
        UseSound = SoundID.Item1;
        useAnimation = 15;
        useTime = 15;
        noUseGraphic = true;
        noMelee = true;
        value = 0;
        accessory = true;
        SetShopValues(ItemRarityColor.Green2, buyPrice(0, 1));
        hasVanityEffects = true;
    }
References Terraria.Item.accessory, Terraria.Item.buyPrice(), Terraria.Item.hasVanityEffects, Terraria.Entity.height, Terraria.ID.SoundID.Item1, Terraria.Item.maxStack, Terraria.Item.noMelee, Terraria.Item.noUseGraphic, Terraria.Item.SetShopValues(), Terraria.Item.shoot, Terraria.Item.shootSpeed, Terraria.Item.useAnimation, Terraria.Item.UseSound, Terraria.Item.useStyle, Terraria.Item.useTime, Terraria.Item.value, and Terraria.Entity.width.
Referenced by Terraria.Item.SetDefaults4(), and Terraria.Item.SetDefaults5().