TModLoader: Terraria.Item.MoveInWorld
MoveInWorld()
void Terraria.Item.MoveInWorld (float gravity, float maxFallSpeed, ref Vector2 wetVelocity, int i) inline private
Definition at line 50360 of file Item.cs.
    {
        //IL_03f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0415: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0174: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_025b: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f68: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f80: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f87: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ecb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0efa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0887: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04af: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c90: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0abb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ade: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0772: Unknown result type (might be due to invalid IL or missing references)
        //IL_0794: Unknown result type (might be due to invalid IL or missing references)
        //IL_079a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0665: Unknown result type (might be due to invalid IL or missing references)
        //IL_0687: Unknown result type (might be due to invalid IL or missing references)
        //IL_068d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0574: Unknown result type (might be due to invalid IL or missing references)
        //IL_0579: Unknown result type (might be due to invalid IL or missing references)
        //IL_0597: Unknown result type (might be due to invalid IL or missing references)
        //IL_059c: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b06: Unknown result type (might be due to invalid IL or missing references)
        //IL_05dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e2: Unknown result type (might be due to invalid IL or missing references)
        ItemLoader.Update(this, ref gravity, ref maxFallSpeed);
        if (!shimmered && ItemID.Sets.ItemNoGravity[type])
        {
            velocity.X *= 0.95f;
            if ((double)velocity.X < 0.1 && (double)velocity.X > -0.1)
            {
                velocity.X = 0f;
            }
            velocity.Y *= 0.95f;
            if ((double)velocity.Y < 0.1 && (double)velocity.Y > -0.1)
            {
                velocity.Y = 0f;
            }
        }
        else
        {
            bool flag = false;
            if (shimmered && active)
            {
                int num = 50;
                for (int j = 0; j < 400; j++)
                {
                    if (i == j || !Main.item[j].active || !Main.item[j].shimmered)
                    {
                        continue;
                    }
                    if (num-- <= 0)
                    {
                        break;
                    }
                    float num9 = (width + Main.item[j].width) / 2;
                    if (!(Math.Abs(base.Center.X - Main.item[j].Center.X) <= num9) || !(Math.Abs(base.Center.Y - Main.item[j].Center.Y) <= num9))
                    {
                        continue;
                    }
                    flag = true;
                    float num10 = Vector2.Distance(base.Center, Main.item[j].Center);
                    num9 /= num10;
                    if (num9 > 10f)
                    {
                        num9 = 10f;
                    }
                    if (base.Center.X < Main.item[j].Center.X)
                    {
                        if (velocity.X > -3f * num9)
{
                            velocity.X -= 0.1f * num9;
                        }
                        if (Main.item[j].velocity.X < 3f)
{
                            Main.item[j].velocity.X += 0.1f * num9;
                        }
                    }
                    else if (base.Center.X > Main.item[j].Center.X)
                    {
                        if (velocity.X < 3f * num9)
{
                            velocity.X += 0.1f * num9;
                        }
                        if (Main.item[j].velocity.X > -3f)
{
                            Main.item[j].velocity.X -= 0.1f * num9;
                        }
                    }
                    else if (i < j)
                    {
                        if (velocity.X > -3f * num9)
{
                            velocity.X -= 0.1f * num9;
                        }
                        if (Main.item[j].velocity.X < 3f * num9)
{
                            Main.item[j].velocity.X += 0.1f * num9;
                        }
                    }
                }
            }
            velocity.Y += gravity;
            if (velocity.Y > maxFallSpeed)
            {
                velocity.Y = maxFallSpeed;
            }
            velocity.X *= 0.95f;
            if ((double)velocity.X < 0.1 && (double)velocity.X > -0.1)
            {
                velocity.X = 0f;
            }
            if (flag)
            {
                velocity.X *= 0.8f;
            }
        }
        bool flag2 = Collision.LavaCollision(position, width, height);
        if (flag2)
        {
            lavaWet = true;
        }
        bool num16 = Collision.WetCollision(position, width, height);
        if (Collision.honey)
        {
            honeyWet = true;
        }
        if (Collision.shimmer)
        {
            shimmerWet = true;
        }
        if (num16)
        {
            if (!wet)
            {
                if (wetCount == 0)
                {
                    wetCount = 20;
                    if (!flag2)
                    {
                        if (shimmerWet)
{
                            for (int k = 0; k < 10; k++)
{
                                int num11 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 308);
                                Main.dust[num11].velocity.Y -= 4f;
                                Main.dust[num11].velocity.X *= 2.5f;
                                Main.dust[num11].scale = 0.8f;
                                Main.dust[num11].noGravity = true;
                                switch (Main.rand.Next(6))
{
                                case 0:
                                    Main.dust[num11].color = new Color(255, 255, 210);
                                    break;
                                case 1:
                                    Main.dust[num11].color = new Color(190, 245, 255);
                                    break;
                                case 2:
                                    Main.dust[num11].color = new Color(255, 150, 255);
                                    break;
                                default:
                                    Main.dust[num11].color = new Color(190, 175, 255);
                                    break;
                                }
                            }
                            SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 4);
                        }
                        else if (honeyWet)
{
                            for (int l = 0; l < 5; l++)
{
                                int num12 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 152);
                                Main.dust[num12].velocity.Y -= 1f;
                                Main.dust[num12].velocity.X *= 2.5f;
                                Main.dust[num12].scale = 1.3f;
                                Main.dust[num12].alpha = 100;
                                Main.dust[num12].noGravity = true;
                            }
                            SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                        }
                        else
{
                            for (int m = 0; m < 10; m++)
{
                                int num13 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, Dust.dustWater());
                                Main.dust[num13].velocity.Y -= 4f;
                                Main.dust[num13].velocity.X *= 2.5f;
                                Main.dust[num13].scale *= 0.8f;
                                Main.dust[num13].alpha = 100;
                                Main.dust[num13].noGravity = true;
                            }
                            SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                        }
                    }
                    else
                    {
                        for (int n = 0; n < 5; n++)
{
                            int num14 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 35);
                            Main.dust[num14].velocity.Y -= 1.5f;
                            Main.dust[num14].velocity.X *= 2.5f;
                            Main.dust[num14].scale = 1.3f;
                            Main.dust[num14].alpha = 100;
                            Main.dust[num14].noGravity = true;
                        }
                        SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                    }
                }
                wet = true;
            }
        }
        else if (wet)
        {
            wet = false;
            if (wetCount == 0)
            {
                wetCount = 20;
                if (!lavaWet)
                {
                    if (shimmerWet)
                    {
                        for (int num15 = 0; num15 < 10; num15++)
{
                            int num2 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 308);
                            Main.dust[num2].velocity.Y -= 4f;
                            Main.dust[num2].velocity.X *= 2.5f;
                            Main.dust[num2].scale = 0.8f;
                            Main.dust[num2].noGravity = true;
                            switch (Main.rand.Next(6))
{
                            case 0:
                                Main.dust[num2].color = new Color(255, 255, 210);
                                break;
                            case 1:
                                Main.dust[num2].color = new Color(190, 245, 255);
                                break;
                            case 2:
                                Main.dust[num2].color = new Color(255, 150, 255);
                                break;
                            default:
                                Main.dust[num2].color = new Color(190, 175, 255);
                                break;
                            }
                        }
                        SoundEngine.PlaySound(19, (int)position.X, (int)position.Y, 5);
                    }
                    else if (honeyWet)
                    {
                        for (int num3 = 0; num3 < 5; num3++)
{
                            int num4 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 152);
                            Main.dust[num4].velocity.Y -= 1f;
                            Main.dust[num4].velocity.X *= 2.5f;
                            Main.dust[num4].scale = 1.3f;
                            Main.dust[num4].alpha = 100;
                            Main.dust[num4].noGravity = true;
                        }
                        SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                    }
                    else
                    {
                        for (int num5 = 0; num5 < 10; num5++)
{
                            int num6 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2)), width + 12, 24, Dust.dustWater());
                            Main.dust[num6].velocity.Y -= 4f;
                            Main.dust[num6].velocity.X *= 2.5f;
                            Main.dust[num6].scale *= 0.8f;
                            Main.dust[num6].alpha = 100;
                            Main.dust[num6].noGravity = true;
                        }
                        SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                    }
                }
                else
                {
                    for (int num7 = 0; num7 < 5; num7++)
                    {
                        int num8 = Dust.NewDust(new Vector2(position.X - 6f, position.Y + (float)(height / 2) - 8f), width + 12, 24, 35);
                        Main.dust[num8].velocity.Y -= 1.5f;
                        Main.dust[num8].velocity.X *= 2.5f;
                        Main.dust[num8].scale = 1.3f;
                        Main.dust[num8].alpha = 100;
                        Main.dust[num8].noGravity = true;
                    }
                    SoundEngine.PlaySound(19, (int)position.X, (int)position.Y);
                }
            }
        }
        if (!wet)
        {
            lavaWet = false;
            honeyWet = false;
            shimmerWet = false;
        }
        if (wetCount > 0)
        {
            wetCount--;
        }
        if (wet)
        {
            if (wet)
            {
                Vector2 vector = velocity;
                velocity = Collision.TileCollision(position, velocity, width, height);
                if (velocity.X != vector.X)
                {
                    wetVelocity.X = velocity.X;
                }
                if (velocity.Y != vector.Y)
                {
                    wetVelocity.Y = velocity.Y;
                }
            }
        }
        else
        {
            velocity = Collision.TileCollision(position, velocity, width, height);
        }
        Vector4 vector2 = Collision.SlopeCollision(position, velocity, width, height, gravity);
        position.X = vector2.X;
        position.Y = vector2.Y;
        velocity.X = vector2.Z;
        velocity.Y = vector2.W;
        Collision.StepConveyorBelt(this, 1f);
    }
References Terraria.Entity.active, Terraria.Dust.alpha, Terraria.Entity.Center, Terraria.Dust.color, Terraria.Main.dust, Terraria.Dust.dustWater(), Terraria.Entity.height, Terraria.Collision.honey, Terraria.Entity.honeyWet, Terraria.Main.item, Terraria.ID.ItemID.Sets.ItemNoGravity, Terraria.Collision.LavaCollision(), Terraria.Entity.lavaWet, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Dust.scale, Terraria.Collision.shimmer, Terraria.Item.shimmered, Terraria.Entity.shimmerWet, Terraria.Collision.SlopeCollision(), Terraria.Collision.StepConveyorBelt(), Terraria.Collision.TileCollision(), Terraria.Item.type, Terraria.ModLoader.ItemLoader.Update(), Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Collision.WetCollision(), Terraria.Entity.wetCount, and Terraria.Entity.width.
Referenced by Terraria.Item.UpdateItem().