TModLoader: Terraria.Item.DefaultToFood
DefaultToFood()
void Terraria.Item.DefaultToFood (int newwidth, int newheight, int foodbuff, int foodbuffduration, bool useGulpSound = false, int animationTime = 17) inline
This method sets a variety of Item values common to food items.
Specifically:
UseSound = useGulpSound ? Item3 : Item2; useStyle = useGulpSound ? F:Terraria.ID.ItemUseStyleID.DrinkLiquid : F:Terraria.ID.ItemUseStyleID.EatFood; useTurn = true; useAnimation = useTime = animationTime; maxStack = F:Terraria.Item.CommonMaxStack; consumable = true; buffType = foodbuff ; buffTime = foodbuffduration ; rare = F:Terraria.ID.ItemRarityID.Blue; value = 20 silver;
Parameters
newwidth
newheight
foodbuff
foodbuffduration
useGulpSound If true, the gulp sound is set, otherwise the crunch sound is set
animationTime
Definition at line 48673 of file Item.cs.
    {
        if (useGulpSound)
        {
            UseSound = SoundID.Item3;
        }
        else
        {
            UseSound = SoundID.Item2;
        }
        if (useGulpSound)
        {
            useStyle = 9;
        }
        else
        {
            useStyle = 2;
        }
        useTurn = true;
        useAnimation = (useTime = animationTime);
        maxStack = CommonMaxStack;
        consumable = true;
        width = newwidth;
        height = newheight;
        buffType = foodbuff;
        buffTime = foodbuffduration;
        rare = 1;
        value = buyPrice(0, 0, 20);
    }
References Terraria.Item.buffTime, Terraria.Item.buffType, Terraria.Item.buyPrice(), Terraria.Item.CommonMaxStack, Terraria.Item.consumable, Terraria.Entity.height, Terraria.ID.SoundID.Item2, Terraria.ID.SoundID.Item3, Terraria.Item.maxStack, Terraria.Item.rare, Terraria.Item.useAnimation, Terraria.Item.UseSound, Terraria.Item.useStyle, Terraria.Item.useTime, Terraria.Item.useTurn, Terraria.Item.value, and Terraria.Entity.width.
Referenced by Terraria.Item.SetDefaults5(), and Terraria.Item.SetFoodDefaults().