TModLoader: Terraria.Item.CheckLavaDeath
CheckLavaDeath()
void Terraria.Item.CheckLavaDeath (int i) inline private
Definition at line 50280 of file Item.cs.
    {
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        if (type == 267)
        {
            if (Main.netMode == 1)
            {
                return;
            }
            int num = stack;
            active = false;
            type = 0;
            stack = 0;
            bool flag = false;
            for (int j = 0; j < 200; j++)
            {
                if (Main.npc[j].active && Main.npc[j].type == 22)
                {
                    int num2 = -Main.npc[j].direction;
                    if (Main.npc[j].IsNPCValidForBestiaryKillCredit())
                    {
                        Main.BestiaryTracker.Kills.RegisterKill(Main.npc[j]);
                    }
                    Main.npc[j].StrikeNPCNoInteraction(9999, 10f, -num2);
                    num--;
                    flag = true;
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(28, -1, -1, null, j, 9999f, 10f, -num2);
                    }
                    NPC.SpawnWOF(position);
                }
            }
            if (flag)
            {
                List<int> list = new List<int>();
                for (int k = 0; k < 200; k++)
                {
                    if (num <= 0)
                    {
                        break;
                    }
                    NPC nPC = Main.npc[k];
                    if (nPC.active && nPC.isLikeATownNPC)
                    {
                        list.Add(k);
                    }
                }
                while (num > 0 && list.Count > 0)
                {
                    int index = Main.rand.Next(list.Count);
                    int num3 = list[index];
                    list.RemoveAt(index);
                    int num4 = -Main.npc[num3].direction;
                    if (Main.npc[num3].IsNPCValidForBestiaryKillCredit())
                    {
                        Main.BestiaryTracker.Kills.RegisterKill(Main.npc[num3]);
                    }
                    Main.npc[num3].StrikeNPCNoInteraction(9999, 10f, -num4);
                    num--;
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(28, -1, -1, null, num3, 9999f, 10f, -num4);
                    }
                }
            }
            NetMessage.SendData(21, -1, -1, null, i);
        }
        else if (playerIndexTheItemIsReservedFor == Main.myPlayer && rare == 0 && type >= 0 && !ItemID.Sets.IsLavaImmuneRegardlessOfRarity[type])
        {
            active = false;
            type = 0;
            stack = 0;
            if (Main.netMode != 0)
            {
                NetMessage.SendData(21, -1, -1, null, i);
            }
        }
    }
References Terraria.Entity.active, Terraria.Main.BestiaryTracker, Terraria.Entity.direction, Terraria.ID.ItemID.Sets.IsLavaImmuneRegardlessOfRarity, Terraria.NPC.IsNPCValidForBestiaryKillCredit(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Item.playerIndexTheItemIsReservedFor, Terraria.Entity.position, Terraria.Main.rand, Terraria.Item.rare, Terraria.NetMessage.SendData(), Terraria.NPC.SpawnWOF(), Terraria.Item.stack, Terraria.NPC.StrikeNPCNoInteraction(), Terraria.Item.type, and Terraria.NPC.type.
Referenced by Terraria.Item.UpdateItem().