TModLoader: Terraria.Item.NewItem_Inner
NewItem_Inner()
static int Terraria.Item.NewItem_Inner (IEntitySource source, int X, int Y, int Width, int Height, Item itemToClone, int Type, int Stack = 1, bool noBroadcast = false, int pfix = 0, bool noGrabDelay = false, bool reverseLookup = false) inline static private
Definition at line 51522 of file Item.cs.
    {
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0222: Unknown result type (might be due to invalid IL or missing references)
        //IL_022c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        if (WorldGen.gen)
        {
            return 0;
        }
        if (Main.rand == null)
        {
            Main.rand = new UnifiedRandom();
        }
        if (NPCLoader.blockLoot.Contains(Type) || newItemDisabled)
        {
            return Main.maxItems;
        }
        if (Main.tenthAnniversaryWorld)
        {
            if (Type == 58)
            {
                Type = Main.rand.NextFromList(new short[3] { 1734, 1867, 58 });
            }
            if (Type == 184)
            {
                Type = Main.rand.NextFromList(new short[3] { 1735, 1868, 184 });
            }
        }
        if (Main.halloween)
        {
            if (Type == 58)
            {
                Type = 1734;
            }
            if (Type == 184)
            {
                Type = 1735;
            }
        }
        if (Main.xMas)
        {
            if (Type == 58)
            {
                Type = 1867;
            }
            if (Type == 184)
            {
                Type = 1868;
            }
        }
        if (itemToClone == null && Type > 0 && cachedItemSpawnsByType[Type] != -1)
        {
            cachedItemSpawnsByType[Type] += Stack;
            return 400;
        }
        Main.item[400] = new Item();
        int num = 400;
        if (Main.netMode != 1)
        {
            num = PickAnItemSlotToSpawnItemOn(reverseLookup, num);
        }
        Main.timeItemSlotCannotBeReusedFor[num] = 0;
        Main.item[num] = new Item();
        Item item = Main.item[num];
        if (itemToClone != null)
        {
            Main.item[num] = itemToClone.Clone();
            item = Main.item[num];
            Type = itemToClone.type;
        }
        else
        {
            item.SetDefaults(Type);
            item.Prefix(pfix);
            item.stack = Stack;
        }
        item.position.X = X + Width / 2 - item.width / 2;
        item.position.Y = Y + Height / 2 - item.height / 2;
        item.wet = Collision.WetCollision(item.position, item.width, item.height);
        item.velocity.X = (float)Main.rand.Next(-30, 31) * 0.1f;
        item.velocity.Y = (float)Main.rand.Next(-40, -15) * 0.1f;
        if (Type == 859 || Type == 4743)
        {
            Item item2 = item;
            item2.velocity *= 0f;
        }
        if (Type == 520 || Type == 521 || (item.type >= 0 && ItemID.Sets.NebulaPickup[item.type]))
        {
            item.velocity.X = (float)Main.rand.Next(-30, 31) * 0.1f;
            item.velocity.Y = (float)Main.rand.Next(-30, 31) * 0.1f;
        }
        item.active = true;
        item.timeSinceItemSpawned = ItemID.Sets.OverflowProtectionTimeOffset[item.type];
        numberOfNewItems++;
        if (ItemSlot.Options.HighlightNewItems && item.type >= 0 && !ItemID.Sets.NeverAppearsAsNewInInventory[item.type])
        {
            item.newAndShiny = true;
        }
        ItemLoader.OnSpawn(item, source);
        if (Main.netMode == 2 && !noBroadcast)
        {
            NetMessage.SendData(21, -1, -1, null, num, noGrabDelay.ToInt());
        }
        else if (Main.netMode == 0)
        {
            item.playerIndexTheItemIsReservedFor = Main.myPlayer;
        }
        return num;
    }
References Terraria.Item.Item(), Terraria.ModLoader.NPCLoader.blockLoot, Terraria.Item.cachedItemSpawnsByType, Terraria.WorldGen.gen, Terraria.Main.halloween, Terraria.Entity.height, Terraria.UI.ItemSlot.Options.HighlightNewItems, Terraria.Main.item, Terraria.Main.maxItems, Terraria.Main.myPlayer, Terraria.ID.ItemID.Sets.NebulaPickup, Terraria.Main.netMode, Terraria.ID.ItemID.Sets.NeverAppearsAsNewInInventory, Terraria.Item.newItemDisabled, Terraria.Item.noGrabDelay, Terraria.Item.numberOfNewItems, Terraria.ModLoader.ItemLoader.OnSpawn(), Terraria.ID.ItemID.Sets.OverflowProtectionTimeOffset, Terraria.Item.PickAnItemSlotToSpawnItemOn(), Terraria.Entity.position, Terraria.Item.Prefix(), Terraria.Main.rand, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Main.tenthAnniversaryWorld, Terraria.Main.timeItemSlotCannotBeReusedFor, Terraria.Item.type, Terraria.Item.Type, Terraria.Collision.WetCollision(), Terraria.Entity.width, and Terraria.Main.xMas.
Referenced by Terraria.Item.NewItem(), and Terraria.Item.NewItem().