TModLoader: Terraria.ModLoader.Default.HelpCommand.Action
Action()
override void Terraria.ModLoader.Default.HelpCommand.Action (CommandCaller caller, string input, string[] args) inline
    {
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        if (args.Length != 0)
        {
            if (!CommandLoader.GetCommand(caller, args[0], out var mc))
            {
                throw new UsageException("Unknown command: " + args[0], Color.Red);
            }
            if (mc != null)
            {
                caller.Reply(mc.Usage);
                if (!string.IsNullOrEmpty(mc.Description))
                {
                    caller.Reply(mc.Description);
                }
            }
            return;
        }
        List<Tuple<string, string>> help = CommandLoader.GetHelp(caller.CommandType);
        caller.Reply(caller.CommandType.ToString() + " Commands:", Color.Yellow);
        foreach (Tuple<string, string> entry in help)
        {
            caller.Reply(entry.Item1 + "   " + entry.Item2);
        }
        if (Main.netMode == 1)
        {
            ChatHelper.SendChatMessageFromClient(new ChatMessage(input));
        }
    }
References Terraria.ModLoader.CommandLoader.GetCommand(), Terraria.ModLoader.CommandLoader.GetHelp(), Terraria.Main.netMode, and Terraria.Chat.ChatHelper.SendChatMessageFromClient().