TModLoader: Terraria.ModLoader.UI.DownloadManager.DownloadFile.HandleResponse
HandleResponse()
DownloadFile Terraria.ModLoader.UI.DownloadManager.DownloadFile.HandleResponse (WebResponse response, CancellationToken token) inline private
Definition at line 83 of file DownloadFile.cs.
    {
        long contentLength = response.ContentLength;
        if (contentLength < 0)
        {
            string txt = "Could not get a proper content length for DownloadFile[" + DisplayText + "]";
            Logging.tML.Error((object)txt);
            throw new Exception(txt);
        }
        string _downloadPath = $"{new FileInfo(FilePath).Directory.FullName}{Path.DirectorySeparatorChar}{DateTime.Now.Ticks}{".tmp"}";
        _fileStream = new FileStream(_downloadPath, FileMode.Create);
        Stream responseStream = response.GetResponseStream();
        int currentIndex = 0;
        byte[] buf = new byte[1048576];
        try
        {
            int r;
            while ((r = responseStream.Read(buf, 0, buf.Length)) > 0)
            {
                token.ThrowIfCancellationRequested();
                _fileStream.Write(buf, 0, r);
                currentIndex += r;
                this.OnUpdateProgress?.Invoke((float)((double)currentIndex / (double)contentLength), currentIndex, response.ContentLength);
            }
        }
        catch (OperationCanceledException e2)
        {
            AbortDownload(_downloadPath);
            Logging.tML.Info((object)("DownloadFile[" + DisplayText + "] operation was cancelled"), (Exception)e2);
        }
        catch (Exception e)
        {
            AbortDownload(_downloadPath);
            Logging.tML.Info((object)"Unknown error", e);
        }
        if (!_aborted)
        {
            _fileStream?.Close();
            PreCopy();
            File.Copy(_downloadPath, FilePath, overwrite: true);
            File.Delete(_downloadPath);
            this.OnComplete?.Invoke();
        }
        return this;
    }
References Terraria.ModLoader.UI.DownloadManager.DownloadFile._aborted, Terraria.ModLoader.UI.DownloadManager.DownloadFile._fileStream, Terraria.ModLoader.UI.DownloadManager.DownloadFile.AbortDownload(), Terraria.ModLoader.UI.DownloadManager.DownloadFile.DisplayText, Terraria.ModLoader.UI.DownloadManager.DownloadFile.FilePath, Terraria.ModLoader.UI.DownloadManager.DownloadFile.PreCopy(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.ModLoader.UI.DownloadManager.DownloadFile.Download().