TModLoader: Terraria.ModLoader.UI.DownloadManager.DownloadFile.Download
Download()
Task< DownloadFile > Terraria.ModLoader.UI.DownloadManager.DownloadFile.Download (CancellationToken token, ProgressUpdated updateProgressAction = null) inline
Definition at line 61 of file DownloadFile.cs.
    {
        SetupDownloadRequest();
        if (updateProgressAction != null)
        {
            this.OnUpdateProgress = updateProgressAction;
        }
        return Task.Factory.FromAsync(Request.BeginGetResponse, (IAsyncResult asyncResult) => Request.EndGetResponse(asyncResult), null).ContinueWith((Task<WebResponse> t) => HandleResponse(t.Result, token), token);
    }
References Terraria.ModLoader.UI.DownloadManager.DownloadFile.HandleResponse(), Terraria.ModLoader.UI.DownloadManager.DownloadFile.Request, and Terraria.ModLoader.UI.DownloadManager.DownloadFile.SetupDownloadRequest().
Referenced by Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress.DownloadMods().