TModLoader: Terraria.ModLoader.UI.UICommon.DrawHoverStringInBounds
DrawHoverStringInBounds()
static void Terraria.ModLoader.UI.UICommon.DrawHoverStringInBounds (SpriteBatch spriteBatch, string text, Rectangle? bounds = null) inline static
    {
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        if (!bounds.HasValue)
        {
            bounds = new Rectangle(0, 0, Main.screenWidth, Main.screenHeight);
        }
        Vector2 stringSize = ChatManager.GetStringSize(FontAssets.MouseText.Value, text, Vector2.One);
        Vector2 vector = Main.MouseScreen + new Vector2(16f);
        float x = vector.X;
        Rectangle value = bounds.Value;
        vector.X = Math.Min(x, (float)((Rectangle)(ref value)).Right - stringSize.X - 16f);
        float y = vector.Y;
        value = bounds.Value;
        vector.Y = Math.Min(y, (float)((Rectangle)(ref value)).Bottom - stringSize.Y - 16f);
        Color color = default(Color);
        ((Color)(ref color))._002Ector((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, 255);
        ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, text, vector, color, 0f, Vector2.Zero, Vector2.One);
    }
References Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.screenHeight, and Terraria.Main.screenWidth.
Referenced by Terraria.ModLoader.UI.ModBrowser.UIModBrowser.Draw(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.Draw(), Terraria.ModLoader.UI.UIModInfo.Draw(), Terraria.ModLoader.UI.UIModItem.Draw(), Terraria.ModLoader.UI.UIModPackItem.Draw(), Terraria.ModLoader.UI.UIMods.Draw(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.DrawChildren(), Terraria.ModLoader.UI.UIModSourceItem.DrawChildren(), Terraria.ModLoader.UI.UIHoverImage.DrawSelf(), and Terraria.ModLoader.UI.UIModItem.DrawSelf().