TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawRisingVineStrip
DrawRisingVineStrip()
void Terraria.GameContent.Drawing.TileDrawing.DrawRisingVineStrip (Vector2 screenPosition, Vector2 offSet, int x, int startY) inline private
Definition at line 10826 of file TileDrawing.cs.
    {
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0174: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_020c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        int num = 0;
        int num2 = 0;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)(x * 16 + 8), (float)(startY * 16 + 16 + 2));
        float amount = Math.Abs(Main.WindForVisuals) / 1.2f;
        amount = MathHelper.Lerp(0.2f, 1f, amount);
        float num3 = -0.08f * amount;
        float windCycle = GetWindCycle(x, startY, _vineWindCounter);
        float num4 = 0f;
        float num5 = 0f;
        for (int num6 = startY; num6 > 10; num6--)
        {
            Tile tile = Main.tile[x, num6];
            if (tile != null)
            {
                ushort type = tile.type;
                if (!tile.active() || !TileID.Sets.ReverseVineThreads[type])
                {
                    break;
                }
                num++;
                if (num2 >= 5)
                {
                    num3 += 0.0075f * amount;
                }
                if (num2 >= 2)
                {
                    num3 += 0.0025f;
                }
                if (WallID.Sets.AllowsWind[tile.wall] && (double)num6 < Main.worldSurface)
                {
                    num2++;
                }
                float windGridPush = GetWindGridPush(x, num6, 40, -0.004f);
                num4 = ((windGridPush != 0f || num5 == 0f) ? (num4 - windGridPush) : (num4 * -0.78f));
                num5 = windGridPush;
                short tileFrameX = tile.frameX;
                short tileFrameY = tile.frameY;
                Color color = Lighting.GetColor(x, num6);
                GetTileDrawData(x, num6, tile, type, ref tileFrameX, ref tileFrameY, out var tileWidth, out var tileHeight, out var tileTop, out var halfBrickHeight, out var addFrX, out var addFrY, out var tileSpriteEffect, out var _, out var _, out var _);
                Vector2 position = new Vector2((float)(-(int)screenPosition.X), (float)(-(int)screenPosition.Y)) + offSet + vector;
                float num7 = (float)num2 * (0f - num3) * windCycle + num4;
                Texture2D tileDrawTexture = GetTileDrawTexture(tile, x, num6);
                if (tileDrawTexture == null)
                {
                    break;
                }
                if (IsVisible(tile))
                {
                    Main.spriteBatch.Draw(tileDrawTexture, position, (Rectangle?)new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight), color, num7, new Vector2((float)(tileWidth / 2), (float)(halfBrickHeight - tileTop + tileHeight)), 1f, tileSpriteEffect, 0f);
                }
                vector += (num7 - (float)Math.PI / 2f).ToRotationVector2() * 16f;
            }
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._vineWindCounter, Terraria.Tile.active(), Terraria.ID.WallID.Sets.AllowsWind, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Lighting.GetColor(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.GameContent.Drawing.TileDrawing.GetWindCycle(), Terraria.GameContent.Drawing.TileDrawing.GetWindGridPush(), Terraria.GameContent.Drawing.TileDrawing.IsVisible(), Terraria.ID.TileID.Sets.ReverseVineThreads, Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.WindForVisuals, and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawReverseVines().