TModLoader: Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf_Sideways
EmitLivingTreeLeaf_Sideways()
void Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf_Sideways (int x, int y, int leafGoreType) inline
Emits a single living tree leaf or other gore instance directly to the side of the target tile, dependent on wind direction.
Parameters
x The X coordinate of the target tile.
y The Y coordinate of the target tile.
leafGoreType The numerical ID of the leaf or other gore instance that should be spawned.
    {
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        int num = 0;
        if (Main.WindForVisuals > 0.2f)
        {
            num = 1;
        }
        else if (Main.WindForVisuals < -0.2f)
        {
            num = -1;
        }
        Tile tile = Main.tile[x + num, y];
        if (!WorldGen.SolidTile(tile) && tile.liquid <= 0)
        {
            int num2 = 0;
            if (num == -1)
            {
                num2 = -10;
            }
            Gore.NewGorePerfect(new Vector2((float)(x * 16 + 8 + 4 * num + num2), (float)(y * 16 + 8)), Vector2.Zero, leafGoreType).Frame.CurrentColumn = Main.tile[x, y].color();
        }
    }
References Terraria.DataStructures.SpriteFrame.CurrentColumn, Terraria.Gore.Frame, Terraria.Tile.liquid, Terraria.Gore.NewGorePerfect(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, and Terraria.Main.WindForVisuals.
Referenced by Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf().