TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile
DrawSingleTile()
void Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile (TileDrawInfo drawData, bool solidLayer, int waterStyleOverride, Vector2 screenPosition, Vector2 screenOffset, int tileX, int tileY) inline private
    {
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0372: Unknown result type (might be due to invalid IL or missing references)
        //IL_0377: Unknown result type (might be due to invalid IL or missing references)
        //IL_050a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0533: Unknown result type (might be due to invalid IL or missing references)
        //IL_0538: Unknown result type (might be due to invalid IL or missing references)
        //IL_053d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0314: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0349: Unknown result type (might be due to invalid IL or missing references)
        //IL_034e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0706: Unknown result type (might be due to invalid IL or missing references)
        //IL_070b: Unknown result type (might be due to invalid IL or missing references)
        //IL_070d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0712: Unknown result type (might be due to invalid IL or missing references)
        //IL_072f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0734: Unknown result type (might be due to invalid IL or missing references)
        //IL_0747: Unknown result type (might be due to invalid IL or missing references)
        //IL_074d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0752: Unknown result type (might be due to invalid IL or missing references)
        //IL_0757: Unknown result type (might be due to invalid IL or missing references)
        //IL_042d: Unknown result type (might be due to invalid IL or missing references)
        //IL_042f: Unknown result type (might be due to invalid IL or missing references)
        //IL_043d: Unknown result type (might be due to invalid IL or missing references)
        //IL_045a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0494: Unknown result type (might be due to invalid IL or missing references)
        //IL_049e: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_062b: Unknown result type (might be due to invalid IL or missing references)
        //IL_063d: Unknown result type (might be due to invalid IL or missing references)
        //IL_064a: Unknown result type (might be due to invalid IL or missing references)
        //IL_064f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0651: Unknown result type (might be due to invalid IL or missing references)
        //IL_0660: Unknown result type (might be due to invalid IL or missing references)
        //IL_066e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0678: Unknown result type (might be due to invalid IL or missing references)
        //IL_0683: Unknown result type (might be due to invalid IL or missing references)
        //IL_086c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0876: Unknown result type (might be due to invalid IL or missing references)
        //IL_087b: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_08db: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aaa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_160f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1632: Unknown result type (might be due to invalid IL or missing references)
        //IL_1643: Unknown result type (might be due to invalid IL or missing references)
        //IL_1648: Unknown result type (might be due to invalid IL or missing references)
        //IL_164a: Unknown result type (might be due to invalid IL or missing references)
        //IL_164f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_16e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_170b: Unknown result type (might be due to invalid IL or missing references)
        //IL_171f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1724: Unknown result type (might be due to invalid IL or missing references)
        //IL_1726: Unknown result type (might be due to invalid IL or missing references)
        //IL_172b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1731: Unknown result type (might be due to invalid IL or missing references)
        //IL_1737: Unknown result type (might be due to invalid IL or missing references)
        //IL_1742: Unknown result type (might be due to invalid IL or missing references)
        //IL_166e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1671: Unknown result type (might be due to invalid IL or missing references)
        //IL_167c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1686: Unknown result type (might be due to invalid IL or missing references)
        //IL_1691: Unknown result type (might be due to invalid IL or missing references)
        //IL_165f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1661: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cbc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c94: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d79: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e80: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d44: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d25: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ead: Unknown result type (might be due to invalid IL or missing references)
        //IL_0edb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dbc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fcf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f83: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f94: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d08: Unknown result type (might be due to invalid IL or missing references)
        //IL_1012: Unknown result type (might be due to invalid IL or missing references)
        //IL_1014: Unknown result type (might be due to invalid IL or missing references)
        //IL_101b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1022: Unknown result type (might be due to invalid IL or missing references)
        //IL_102d: Unknown result type (might be due to invalid IL or missing references)
        //IL_142d: Unknown result type (might be due to invalid IL or missing references)
        //IL_144d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1457: Unknown result type (might be due to invalid IL or missing references)
        //IL_145e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1469: Unknown result type (might be due to invalid IL or missing references)
        //IL_1514: Unknown result type (might be due to invalid IL or missing references)
        //IL_1522: Unknown result type (might be due to invalid IL or missing references)
        //IL_1527: Unknown result type (might be due to invalid IL or missing references)
        //IL_1550: Unknown result type (might be due to invalid IL or missing references)
        //IL_155a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1561: Unknown result type (might be due to invalid IL or missing references)
        //IL_156c: Unknown result type (might be due to invalid IL or missing references)
        //IL_15a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_15aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_15af: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_15de: Unknown result type (might be due to invalid IL or missing references)
        //IL_15e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_15f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_1206: Unknown result type (might be due to invalid IL or missing references)
        //IL_1211: Unknown result type (might be due to invalid IL or missing references)
        //IL_13cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_13d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_13dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_13e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_13e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_13ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_13fa: Unknown result type (might be due to invalid IL or missing references)
        drawData.tileCache = Main.tile[tileX, tileY];
        drawData.typeCache = drawData.tileCache.type;
        drawData.tileFrameX = drawData.tileCache.frameX;
        drawData.tileFrameY = drawData.tileCache.frameY;
        drawData.tileLight = Lighting.GetColor(tileX, tileY);
        if (drawData.tileCache.liquid > 0 && drawData.tileCache.type == 518)
        {
            return;
        }
        GetTileDrawData(tileX, tileY, drawData.tileCache, drawData.typeCache, ref drawData.tileFrameX, ref drawData.tileFrameY, out drawData.tileWidth, out drawData.tileHeight, out drawData.tileTop, out drawData.halfBrickHeight, out drawData.addFrX, out drawData.addFrY, out drawData.tileSpriteEffect, out drawData.glowTexture, out drawData.glowSourceRect, out drawData.glowColor);
        drawData.drawTexture = GetTileDrawTexture(drawData.tileCache, tileX, tileY);
        Texture2D highlightTexture = null;
        Rectangle empty = Rectangle.Empty;
        Color highlightColor = Color.Transparent;
        if (TileID.Sets.HasOutlines[drawData.typeCache])
        {
            GetTileOutlineInfo(tileX, tileY, drawData.typeCache, ref drawData.tileLight, ref highlightTexture, ref highlightColor);
        }
        if (_localPlayer.dangerSense && IsTileDangerous(tileX, tileY, _localPlayer, drawData.tileCache, drawData.typeCache))
        {
            if (((Color)(ref drawData.tileLight)).R < byte.MaxValue)
            {
                ((Color)(ref drawData.tileLight)).R = byte.MaxValue;
            }
            if (((Color)(ref drawData.tileLight)).G < 50)
            {
                ((Color)(ref drawData.tileLight)).G = 50;
            }
            if (((Color)(ref drawData.tileLight)).B < 50)
            {
                ((Color)(ref drawData.tileLight)).B = 50;
            }
            if (_isActiveAndNotPaused && _rand.Next(30) == 0)
            {
                int num = Dust.NewDust(new Vector2((float)(tileX * 16), (float)(tileY * 16)), 16, 16, 60, 0f, 0f, 100, default(Color), 0.3f);
                _dust[num].fadeIn = 1f;
                Dust obj = _dust[num];
                obj.velocity *= 0.1f;
                _dust[num].noLight = true;
                _dust[num].noGravity = true;
            }
        }
        if (_localPlayer.findTreasure && Main.IsTileSpelunkable(tileX, tileY, drawData.typeCache, drawData.tileFrameX, drawData.tileFrameY))
        {
            if (((Color)(ref drawData.tileLight)).R < 200)
            {
                ((Color)(ref drawData.tileLight)).R = 200;
            }
            if (((Color)(ref drawData.tileLight)).G < 170)
            {
                ((Color)(ref drawData.tileLight)).G = 170;
            }
            if (_isActiveAndNotPaused && _rand.Next(60) == 0)
            {
                int num12 = Dust.NewDust(new Vector2((float)(tileX * 16), (float)(tileY * 16)), 16, 16, 204, 0f, 0f, 150, default(Color), 0.3f);
                _dust[num12].fadeIn = 1f;
                Dust obj2 = _dust[num12];
                obj2.velocity *= 0.1f;
                _dust[num12].noLight = true;
            }
        }
        if (_localPlayer.biomeSight)
        {
            Color sightColor = Color.White;
            if (Main.IsTileBiomeSightable(tileX, tileY, drawData.typeCache, drawData.tileFrameX, drawData.tileFrameY, ref sightColor))
            {
                if (((Color)(ref drawData.tileLight)).R < ((Color)(ref sightColor)).R)
                {
                    ((Color)(ref drawData.tileLight)).R = ((Color)(ref sightColor)).R;
                }
                if (((Color)(ref drawData.tileLight)).G < ((Color)(ref sightColor)).G)
                {
                    ((Color)(ref drawData.tileLight)).G = ((Color)(ref sightColor)).G;
                }
                if (((Color)(ref drawData.tileLight)).B < ((Color)(ref sightColor)).B)
                {
                    ((Color)(ref drawData.tileLight)).B = ((Color)(ref sightColor)).B;
                }
                if (_isActiveAndNotPaused && _rand.Next(480) == 0)
                {
                    Color newColor = sightColor;
                    int num14 = Dust.NewDust(new Vector2((float)(tileX * 16), (float)(tileY * 16)), 16, 16, 267, 0f, 0f, 150, newColor, 0.3f);
                    _dust[num14].noGravity = true;
                    _dust[num14].fadeIn = 1f;
                    Dust obj3 = _dust[num14];
                    obj3.velocity *= 0.1f;
                    _dust[num14].noLightEmittence = true;
                }
            }
        }
        if (_isActiveAndNotPaused)
        {
            if (!Lighting.UpdateEveryFrame || new FastRandom(Main.TileFrameSeed).WithModifier(tileX, tileY).Next(4) == 0)
            {
                DrawTiles_EmitParticles(tileY, tileX, drawData.tileCache, drawData.typeCache, drawData.tileFrameX, drawData.tileFrameY, drawData.tileLight);
            }
            drawData.tileLight = DrawTiles_GetLightOverride(tileY, tileX, drawData.tileCache, drawData.typeCache, drawData.tileFrameX, drawData.tileFrameY, drawData.tileLight);
        }
        bool flag = false;
        if (((Color)(ref drawData.tileLight)).R >= 1 || ((Color)(ref drawData.tileLight)).G >= 1 || ((Color)(ref drawData.tileLight)).B >= 1)
        {
            flag = true;
        }
        if (drawData.tileCache.wall > 0 && (drawData.tileCache.wall == 318 || drawData.tileCache.fullbrightWall()))
        {
            flag = true;
        }
        flag &= IsVisible(drawData.tileCache);
        CacheSpecialDraws_Part1(tileX, tileY, drawData.typeCache, drawData.tileFrameX, drawData.tileFrameY, !flag);
        CacheSpecialDraws_Part2(tileX, tileY, drawData, !flag);
        if (drawData.typeCache == 72 && drawData.tileFrameX >= 36)
        {
            int num15 = 0;
            if (drawData.tileFrameY == 18)
            {
                num15 = 1;
            }
            else if (drawData.tileFrameY == 36)
            {
                num15 = 2;
            }
            Main.spriteBatch.Draw(TextureAssets.ShroomCap.Value, new Vector2((float)(tileX * 16 - (int)screenPosition.X - 22), (float)(tileY * 16 - (int)screenPosition.Y - 26)) + screenOffset, (Rectangle?)new Rectangle(num15 * 62, 0, 60, 42), Lighting.GetColor(tileX, tileY), 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
        }
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY, drawData.tileWidth, drawData.tileHeight - drawData.halfBrickHeight);
        Vector2 vector = new Vector2((float)(tileX * 16 - (int)screenPosition.X) - ((float)drawData.tileWidth - 16f) / 2f, (float)(tileY * 16 - (int)screenPosition.Y + drawData.tileTop + drawData.halfBrickHeight)) + screenOffset;
        TileLoader.DrawEffects(tileX, tileY, drawData.typeCache, Main.spriteBatch, ref drawData);
        if (!flag)
        {
            return;
        }
        drawData.colorTint = Color.White;
        drawData.finalColor = GetFinalLight(drawData.tileCache, drawData.typeCache, drawData.tileLight, drawData.colorTint);
        switch (drawData.typeCache)
        {
        case 136:
            switch (drawData.tileFrameX / 18)
            {
            case 1:
                vector.X += -2f;
                break;
            case 2:
                vector.X += 2f;
                break;
            }
            break;
        case 442:
            if (drawData.tileFrameX / 22 == 3)
            {
                vector.X += 2f;
            }
            break;
        case 51:
            drawData.finalColor = drawData.tileLight * 0.5f;
            break;
        case 160:
        case 692:
        {
            Color color = default(Color);
            ((Color)(ref color))._002Ector(Main.DiscoR, Main.DiscoG, Main.DiscoB, 255);
            if (drawData.tileCache.inActive())
            {
                color = drawData.tileCache.actColor(color);
            }
            drawData.finalColor = color;
            break;
        }
        case 129:
        {
            drawData.finalColor = new Color(255, 255, 255, 100);
            int num17 = 2;
            if (drawData.tileFrameX >= 324)
            {
                drawData.finalColor = Color.Transparent;
            }
            if (drawData.tileFrameY < 36)
            {
                vector.Y += num17 * (drawData.tileFrameY == 0).ToDirectionInt();
            }
            else
            {
                vector.X += num17 * (drawData.tileFrameY == 36).ToDirectionInt();
            }
            break;
        }
        case 272:
        {
            int num16 = Main.tileFrame[drawData.typeCache];
            num16 += tileX % 2;
            num16 += tileY % 2;
            num16 += tileX % 3;
            num16 += tileY % 3;
            num16 %= 2;
            num16 *= 90;
            drawData.addFrY += num16;
            rectangle.Y += num16;
            break;
        }
        case 80:
        {
            WorldGen.GetCactusType(tileX, tileY, drawData.tileFrameX, drawData.tileFrameY, out var evil, out var good, out var crimson);
            if (evil)
            {
                rectangle.Y += 54;
            }
            if (good)
            {
                rectangle.Y += 108;
            }
            if (crimson)
            {
                rectangle.Y += 162;
            }
            break;
        }
        case 83:
            drawData.drawTexture = GetTileDrawTexture(drawData.tileCache, tileX, tileY);
            break;
        case 323:
            if (drawData.tileCache.frameX <= 132 && drawData.tileCache.frameX >= 88)
            {
                return;
            }
            vector.X += drawData.tileCache.frameY;
            break;
        case 114:
            if (drawData.tileFrameY > 0)
            {
                rectangle.Height += 2;
            }
            break;
        }
        if (drawData.typeCache == 314)
        {
            DrawTile_MinecartTrack(screenPosition, screenOffset, tileX, tileY, drawData);
        }
        else if (drawData.typeCache == 171)
        {
            DrawXmasTree(screenPosition, screenOffset, tileX, tileY, drawData);
        }
        else
        {
            DrawBasicTile(screenPosition, screenOffset, tileX, tileY, drawData, rectangle, vector);
        }
        if (Main.tileGlowMask[drawData.tileCache.type] != -1)
        {
            short num18 = Main.tileGlowMask[drawData.tileCache.type];
            if (TextureAssets.GlowMask.IndexInRange(num18))
            {
                drawData.drawTexture = TextureAssets.GlowMask[num18].Value;
            }
            double num19 = Main.timeForVisualEffects * 0.08;
            Color color2 = Color.White;
            bool flag2 = false;
            switch (drawData.tileCache.type)
            {
            case 633:
                color2 = Color.Lerp(Color.White, drawData.finalColor, 0.75f);
                break;
            case 659:
            case 667:
                color2 = LiquidRenderer.GetShimmerGlitterColor(top: true, tileX, tileY);
                break;
            case 350:
                ((Color)(ref color2))._002Ector(new Vector4((float)((0.0 - Math.Cos(((int)(num19 / 6.283) % 3 == 1) ? num19 : 0.0)) * 0.2 + 0.2)));
                break;
            case 381:
            case 517:
            case 687:
                color2 = _lavaMossGlow;
                break;
            case 534:
            case 535:
            case 689:
                color2 = _kryptonMossGlow;
                break;
            case 536:
            case 537:
            case 690:
                color2 = _xenonMossGlow;
                break;
            case 539:
            case 540:
            case 688:
                color2 = _argonMossGlow;
                break;
            case 625:
            case 626:
            case 691:
                color2 = _violetMossGlow;
                break;
            case 627:
            case 628:
            case 692:
                ((Color)(ref color2))._002Ector(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                break;
            case 370:
            case 390:
                color2 = _meteorGlow;
                break;
            case 391:
                ((Color)(ref color2))._002Ector(250, 250, 250, 200);
                break;
            case 209:
                color2 = PortalHelper.GetPortalColor(Main.myPlayer, (drawData.tileCache.frameX >= 288) ? 1 : 0);
                break;
            case 429:
            case 445:
                drawData.drawTexture = GetTileDrawTexture(drawData.tileCache, tileX, tileY);
                drawData.addFrY = 18;
                break;
            case 129:
            {
                if (drawData.tileFrameX < 324)
                {
                    flag2 = true;
                    break;
                }
                drawData.drawTexture = GetTileDrawTexture(drawData.tileCache, tileX, tileY);
                color2 = Main.hslToRgb(0.7f + (float)Math.Sin((float)Math.PI * 2f * Main.GlobalTimeWrappedHourly * 0.16f + (float)tileX * 0.3f + (float)tileY * 0.7f) * 0.16f, 1f, 0.5f);
                ((Color)(ref color2)).A = (byte)(((Color)(ref color2)).A / 2);
                color2 *= 0.3f;
                int num2 = 72;
                for (float num3 = 0f; num3 < (float)Math.PI * 2f; num3 += (float)Math.PI / 2f)
                {
                    Main.spriteBatch.Draw(drawData.drawTexture, vector + num3.ToRotationVector2() * 2f, (Rectangle?)new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY + num2, drawData.tileWidth, drawData.tileHeight), color2, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
                }
                ((Color)(ref color2))._002Ector(255, 255, 255, 100);
                break;
            }
            }
            if (!flag2)
            {
                if (drawData.tileCache.slope() == 0 && !drawData.tileCache.halfBrick())
                {
                    Main.spriteBatch.Draw(drawData.drawTexture, vector, (Rectangle?)new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY, drawData.tileWidth, drawData.tileHeight), color2, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
                }
                else if (drawData.tileCache.halfBrick())
                {
                    Main.spriteBatch.Draw(drawData.drawTexture, vector, (Rectangle?)rectangle, color2, 0f, _zero, 1f, (SpriteEffects)0, 0f);
                }
                else if (TileID.Sets.Platforms[drawData.tileCache.type])
                {
                    Main.spriteBatch.Draw(drawData.drawTexture, vector, (Rectangle?)rectangle, color2, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                    if (drawData.tileCache.slope() == 1 && Main.tile[tileX + 1, tileY + 1].active() && Main.tileSolid[Main.tile[tileX + 1, tileY + 1].type] && Main.tile[tileX + 1, tileY + 1].slope() != 2 && !Main.tile[tileX + 1, tileY + 1].halfBrick() && (!Main.tile[tileX, tileY + 1].active() || (Main.tile[tileX, tileY + 1].blockType() != 0 && Main.tile[tileX, tileY + 1].blockType() != 5) || (!TileID.Sets.BlocksStairs[Main.tile[tileX, tileY + 1].type] && !TileID.Sets.BlocksStairsAbove[Main.tile[tileX, tileY + 1].type])))
                    {
                        Rectangle value = default(Rectangle);
                        ((Rectangle)(ref value))._002Ector(198, (int)drawData.tileFrameY, 16, 16);
                        if (TileID.Sets.Platforms[Main.tile[tileX + 1, tileY + 1].type] && Main.tile[tileX + 1, tileY + 1].slope() == 0)
{
                            value.X = 324;
                        }
                        Main.spriteBatch.Draw(drawData.drawTexture, vector + new Vector2(0f, 16f), (Rectangle?)value, color2, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                    }
                    else if (drawData.tileCache.slope() == 2 && Main.tile[tileX - 1, tileY + 1].active() && Main.tileSolid[Main.tile[tileX - 1, tileY + 1].type] && Main.tile[tileX - 1, tileY + 1].slope() != 1 && !Main.tile[tileX - 1, tileY + 1].halfBrick() && (!Main.tile[tileX, tileY + 1].active() || (Main.tile[tileX, tileY + 1].blockType() != 0 && Main.tile[tileX, tileY + 1].blockType() != 4) || (!TileID.Sets.BlocksStairs[Main.tile[tileX, tileY + 1].type] && !TileID.Sets.BlocksStairsAbove[Main.tile[tileX, tileY + 1].type])))
                    {
                        Rectangle value2 = default(Rectangle);
                        ((Rectangle)(ref value2))._002Ector(162, (int)drawData.tileFrameY, 16, 16);
                        if (TileID.Sets.Platforms[Main.tile[tileX - 1, tileY + 1].type] && Main.tile[tileX - 1, tileY + 1].slope() == 0)
{
                            value2.X = 306;
                        }
                        Main.spriteBatch.Draw(drawData.drawTexture, vector + new Vector2(0f, 16f), (Rectangle?)value2, color2, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                    }
                }
                else if (TileID.Sets.HasSlopeFrames[drawData.tileCache.type])
                {
                    Main.spriteBatch.Draw(drawData.drawTexture, vector, (Rectangle?)new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY, 16, 16), color2, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                }
                else
                {
                    int num4 = drawData.tileCache.slope();
                    int num5 = 2;
                    for (int i = 0; i < 8; i++)
                    {
                        int num6 = i * -2;
                        int num7 = 16 - i * 2;
                        int num8 = 16 - num7;
                        int num9;
                        switch (num4)
{
                        case 1:
                            num6 = 0;
                            num9 = i * 2;
                            num7 = 14 - i * 2;
                            num8 = 0;
                            break;
                        case 2:
                            num6 = 0;
                            num9 = 16 - i * 2 - 2;
                            num7 = 14 - i * 2;
                            num8 = 0;
                            break;
                        case 3:
                            num9 = i * 2;
                            break;
                        default:
                            num9 = 16 - i * 2 - 2;
                            break;
                        }
                        Main.spriteBatch.Draw(drawData.drawTexture, vector + new Vector2((float)num9, (float)(i * num5 + num6)), (Rectangle?)new Rectangle(drawData.tileFrameX + drawData.addFrX + num9, drawData.tileFrameY + drawData.addFrY + num8, num5, num7), color2, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                    }
                    int num10 = ((num4 <= 2) ? 14 : 0);
                    Main.spriteBatch.Draw(drawData.drawTexture, vector + new Vector2(0f, (float)num10), (Rectangle?)new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY + num10, 16, 2), color2, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                }
            }
        }
        if (drawData.glowTexture != null)
        {
            Vector2 position = new Vector2((float)(tileX * 16 - (int)screenPosition.X) - ((float)drawData.tileWidth - 16f) / 2f, (float)(tileY * 16 - (int)screenPosition.Y + drawData.tileTop)) + screenOffset;
            if (TileID.Sets.Platforms[drawData.typeCache])
            {
                position = vector;
            }
            Main.spriteBatch.Draw(drawData.glowTexture, position, (Rectangle?)drawData.glowSourceRect, drawData.glowColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
        }
        if (highlightTexture != null)
        {
            ((Rectangle)(ref empty))._002Ector(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY, drawData.tileWidth, drawData.tileHeight);
            int num11 = 0;
            int num13 = 0;
            Main.spriteBatch.Draw(highlightTexture, new Vector2((float)(tileX * 16 - (int)screenPosition.X) - ((float)drawData.tileWidth - 16f) / 2f + (float)num11, (float)(tileY * 16 - (int)screenPosition.Y + drawData.tileTop + num13)) + screenOffset, (Rectangle?)empty, highlightColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._argonMossGlow, Terraria.GameContent.Drawing.TileDrawing._dust, Terraria.GameContent.Drawing.TileDrawing._isActiveAndNotPaused, Terraria.GameContent.Drawing.TileDrawing._kryptonMossGlow, Terraria.GameContent.Drawing.TileDrawing._lavaMossGlow, Terraria.GameContent.Drawing.TileDrawing._localPlayer, Terraria.GameContent.Drawing.TileDrawing._meteorGlow, Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.GameContent.Drawing.TileDrawing._violetMossGlow, Terraria.GameContent.Drawing.TileDrawing._xenonMossGlow, Terraria.GameContent.Drawing.TileDrawing._zero, Terraria.Player.biomeSight, Terraria.ID.TileID.Sets.BlocksStairs, Terraria.ID.TileID.Sets.BlocksStairsAbove, Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part1(), Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part2(), Terraria.Player.dangerSense, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), Terraria.ModLoader.TileLoader.DrawEffects(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_MinecartTrack(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_GetLightOverride(), Terraria.GameContent.Drawing.TileDrawing.DrawXmasTree(), Terraria.Dust.fadeIn, Terraria.Player.findTreasure, Terraria.WorldGen.GetCactusType(), Terraria.Lighting.GetColor(), Terraria.GameContent.Drawing.TileDrawing.GetFinalLight(), Terraria.GameContent.PortalHelper.GetPortalColor(), Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerGlitterColor(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.GameContent.Drawing.TileDrawing.GetTileOutlineInfo(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.TextureAssets.GlowMask, Terraria.ID.TileID.Sets.HasOutlines, Terraria.ID.TileID.Sets.HasSlopeFrames, Terraria.Main.hslToRgb(), Terraria.Main.IsTileBiomeSightable(), Terraria.GameContent.Drawing.TileDrawing.IsTileDangerous(), Terraria.Main.IsTileSpelunkable(), Terraria.GameContent.Drawing.TileDrawing.IsVisible(), Terraria.Main.myPlayer, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.FastRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Dust.noLightEmittence, Terraria.ID.TileID.Sets.Platforms, Terraria.GameContent.TextureAssets.ShroomCap, Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Main.tileFrame, Terraria.Main.TileFrameSeed, Terraria.Main.tileGlowMask, Terraria.Main.tileSolid, Terraria.Lighting.UpdateEveryFrame, and Terraria.Utilities.FastRandom.WithModifier().
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw().