TModLoader: Terraria.GameContent.Drawing.TileDrawing.GetFinalLight
GetFinalLight() [1/2]
static Color Terraria.GameContent.Drawing.TileDrawing.GetFinalLight (Tile tileCache, ushort typeCache, Color tileLight, Color tint) inline static private
Definition at line 5091 of file TileDrawing.cs.
    {
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        int num = (int)((float)(((Color)(ref tileLight)).R * ((Color)(ref tint)).R) / 255f);
        int num2 = (int)((float)(((Color)(ref tileLight)).G * ((Color)(ref tint)).G) / 255f);
        int num3 = (int)((float)(((Color)(ref tileLight)).B * ((Color)(ref tint)).B) / 255f);
        if (num > 255)
        {
            num = 255;
        }
        if (num2 > 255)
        {
            num2 = 255;
        }
        if (num3 > 255)
        {
            num3 = 255;
        }
        num3 <<= 16;
        num2 <<= 8;
        ((Color)(ref tileLight)).PackedValue = (uint)(num | num2 | num3) | 0xFF000000u;
        if (tileCache.fullbrightBlock())
        {
            tileLight = Color.White;
        }
        if (tileCache.inActive())
        {
            tileLight = tileCache.actColor(tileLight);
        }
        else if (ShouldTileShine(typeCache, tileCache.frameX))
        {
            tileLight = Main.shine(tileLight, typeCache);
        }
        return tileLight;
    }
References Terraria.Tile.actColor(), Terraria.Tile.frameX, Terraria.Tile.fullbrightBlock(), Terraria.Tile.inActive(), Terraria.Main.shine(), and Terraria.GameContent.Drawing.TileDrawing.ShouldTileShine().
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile_SlicedBlock(), and Terraria.GameContent.Drawing.TileDrawing.DrawTile_MinecartTrack().