TModLoader: Terraria.GameContent.Drawing.TileDrawing.EmitTreeLeaves
EmitTreeLeaves()
void Terraria.GameContent.Drawing.TileDrawing.EmitTreeLeaves (int tilePosX, int tilePosY, int grassPosX, int grassPosY) inline private
Definition at line 8796 of file TileDrawing.cs.
    {
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_021a: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_0245: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_0253: Unknown result type (might be due to invalid IL or missing references)
        //IL_0261: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        if (!_isActiveAndNotPaused)
        {
            return;
        }
        int treeHeight = grassPosY - tilePosY;
        Tile tile = Main.tile[tilePosX, tilePosY];
        if (tile.liquid > 0)
        {
            return;
        }
        WorldGen.GetTreeLeaf(tilePosX, tile, Main.tile[grassPosX, grassPosY], ref treeHeight, out var _, out var passStyle);
        int num;
        switch (passStyle)
        {
        case -1:
        case 912:
        case 913:
        case 1278:
            return;
        default:
            num = ((passStyle >= 1113 && passStyle <= 1121) ? 1 : 0);
            break;
        case 917:
        case 918:
        case 919:
        case 920:
        case 921:
        case 922:
        case 923:
        case 924:
        case 925:
            num = 1;
            break;
        }
        bool flag = (byte)num != 0;
        int num2 = _leafFrequency;
        bool flag2 = tilePosX - grassPosX != 0;
        if (flag)
        {
            num2 /= 2;
        }
        if (!WorldGen.DoesWindBlowAtThisHeight(tilePosY))
        {
            num2 = 10000;
        }
        if (flag2)
        {
            num2 *= 3;
        }
        if (_rand.Next(num2) != 0)
        {
            return;
        }
        int num3 = 2;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)(tilePosX * 16 + 8), (float)(tilePosY * 16 + 8));
        if (flag2)
        {
            int num4 = tilePosX - grassPosX;
            vector.X += num4 * 12;
            int num5 = 0;
            if (tile.frameY == 220)
            {
                num5 = 1;
            }
            else if (tile.frameY == 242)
            {
                num5 = 2;
            }
            if (tile.frameX == 66)
            {
                switch (num5)
                {
                case 0:
                    vector += new Vector2(0f, -6f);
                    break;
                case 1:
                    vector += new Vector2(0f, -6f);
                    break;
                case 2:
                    vector += new Vector2(0f, 8f);
                    break;
                }
            }
            else
            {
                switch (num5)
                {
                case 0:
                    vector += new Vector2(0f, 4f);
                    break;
                case 1:
                    vector += new Vector2(2f, -6f);
                    break;
                case 2:
                    vector += new Vector2(6f, -6f);
                    break;
                }
            }
        }
        else
        {
            vector += new Vector2(-16f, -16f);
            if (flag)
            {
                vector.Y -= Main.rand.Next(0, 28) * 4;
            }
        }
        if (!WorldGen.SolidTile(vector.ToTileCoordinates()))
        {
            Gore.NewGoreDirect(vector, Utils.RandomVector2(Main.rand, -num3, num3), passStyle, 0.7f + Main.rand.NextFloat() * 0.6f).Frame.CurrentColumn = Main.tile[tilePosX, tilePosY].color();
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._isActiveAndNotPaused, Terraria.GameContent.Drawing.TileDrawing._leafFrequency, Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.WorldGen.DoesWindBlowAtThisHeight(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetTreeLeaf(), Terraria.Tile.liquid, Terraria.Gore.NewGoreDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Utils.RandomVector2(), Terraria.WorldGen.SolidTile(), and Terraria.Main.tile.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawTrees().