TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile
DrawBasicTile()
void Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile (Vector2 screenPosition, Vector2 screenOffset, int tileX, int tileY, TileDrawInfo drawData, Rectangle normalTileRect, Vector2 normalTilePosition) inline private
    {
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_0510: Unknown result type (might be due to invalid IL or missing references)
        //IL_0534: Unknown result type (might be due to invalid IL or missing references)
        //IL_0540: Unknown result type (might be due to invalid IL or missing references)
        //IL_054a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0556: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1003: Unknown result type (might be due to invalid IL or missing references)
        //IL_100f: Unknown result type (might be due to invalid IL or missing references)
        //IL_101f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0def: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dfb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ebc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ecb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ecd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0edf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f09: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f12: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f87: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f93: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_060d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0612: Unknown result type (might be due to invalid IL or missing references)
        //IL_063f: Unknown result type (might be due to invalid IL or missing references)
        //IL_064b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0655: Unknown result type (might be due to invalid IL or missing references)
        //IL_0661: Unknown result type (might be due to invalid IL or missing references)
        //IL_0696: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_06da: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07df: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0811: Unknown result type (might be due to invalid IL or missing references)
        //IL_081d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0827: Unknown result type (might be due to invalid IL or missing references)
        //IL_0833: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0945: Unknown result type (might be due to invalid IL or missing references)
        //IL_0951: Unknown result type (might be due to invalid IL or missing references)
        //IL_0956: Unknown result type (might be due to invalid IL or missing references)
        //IL_0983: Unknown result type (might be due to invalid IL or missing references)
        //IL_098f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0999: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_09cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a06: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a12: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a68: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04df: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c11: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c59: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0acf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0adb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c79: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c85: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb9: Unknown result type (might be due to invalid IL or missing references)
        Tile tile;
        if (TileID.Sets.Platforms[drawData.typeCache] && WorldGen.IsRope(tileX, tileY) && Main.tile[tileX, tileY - 1] != null)
        {
            tile = Main.tile[tileX, tileY - 1];
            _ = ref tile.type;
            int y = (tileY + tileX) % 3 * 18;
            Texture2D tileDrawTexture = GetTileDrawTexture(Main.tile[tileX, tileY - 1], tileX, tileY);
            if (tileDrawTexture != null)
            {
                Main.spriteBatch.Draw(tileDrawTexture, new Vector2((float)(tileX * 16 - (int)screenPosition.X), (float)(tileY * 16 - (int)screenPosition.Y)) + screenOffset, (Rectangle?)new Rectangle(90, y, 16, 16), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
            }
        }
        if (drawData.tileCache.slope() > 0)
        {
            if (TileID.Sets.Platforms[drawData.tileCache.type])
            {
                Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, (Rectangle?)normalTileRect, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                if (drawData.tileCache.slope() == 1)
                {
                    tile = Main.tile[tileX + 1, tileY + 1];
                    if (tile.active())
                    {
                        bool[] tileSolid = Main.tileSolid;
                        tile = Main.tile[tileX + 1, tileY + 1];
                        if (tileSolid[tile.type])
{
                            tile = Main.tile[tileX + 1, tileY + 1];
                            if (tile.slope() != 2)
{
                                tile = Main.tile[tileX + 1, tileY + 1];
                                if (!tile.halfBrick())
{
                                    tile = Main.tile[tileX, tileY + 1];
                                    if (!tile.active())
{
                                        goto IL_0269;
                                    }
                                    tile = Main.tile[tileX, tileY + 1];
                                    if (tile.blockType() != 0)
{
                                        tile = Main.tile[tileX, tileY + 1];
                                        if (tile.blockType() != 5)
{
                                            goto IL_0269;
                                        }
                                    }
                                    bool[] blocksStairs = TileID.Sets.BlocksStairs;
                                    tile = Main.tile[tileX, tileY + 1];
                                    if (!blocksStairs[tile.type])
{
                                        bool[] blocksStairsAbove = TileID.Sets.BlocksStairsAbove;
                                        tile = Main.tile[tileX, tileY + 1];
                                        if (!blocksStairsAbove[tile.type])
{
                                            goto IL_0269;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                if (drawData.tileCache.slope() != 2)
                {
                    return;
                }
                tile = Main.tile[tileX - 1, tileY + 1];
                if (!tile.active())
                {
                    return;
                }
                bool[] tileSolid2 = Main.tileSolid;
                tile = Main.tile[tileX - 1, tileY + 1];
                if (!tileSolid2[tile.type])
                {
                    return;
                }
                tile = Main.tile[tileX - 1, tileY + 1];
                if (tile.slope() == 1)
                {
                    return;
                }
                tile = Main.tile[tileX - 1, tileY + 1];
                if (tile.halfBrick())
                {
                    return;
                }
                tile = Main.tile[tileX, tileY + 1];
                if (tile.active())
                {
                    tile = Main.tile[tileX, tileY + 1];
                    if (tile.blockType() != 0)
                    {
                        tile = Main.tile[tileX, tileY + 1];
                        if (tile.blockType() != 4)
{
                            goto IL_043e;
                        }
                    }
                    bool[] blocksStairs2 = TileID.Sets.BlocksStairs;
                    tile = Main.tile[tileX, tileY + 1];
                    if (blocksStairs2[tile.type])
                    {
                        return;
                    }
                    bool[] blocksStairsAbove2 = TileID.Sets.BlocksStairsAbove;
                    tile = Main.tile[tileX, tileY + 1];
                    if (blocksStairsAbove2[tile.type])
                    {
                        return;
                    }
                }
                goto IL_043e;
            }
            if (TileID.Sets.HasSlopeFrames[drawData.tileCache.type])
            {
                Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, (Rectangle?)new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY, 16, 16), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                return;
            }
            int num = drawData.tileCache.slope();
            int num3 = 2;
            for (int i = 0; i < 8; i++)
            {
                int num4 = i * -2;
                int num5 = 16 - i * 2;
                int num6 = 16 - num5;
                int num7;
                switch (num)
                {
                case 1:
                    num4 = 0;
                    num7 = i * 2;
                    num5 = 14 - i * 2;
                    num6 = 0;
                    break;
                case 2:
                    num4 = 0;
                    num7 = 16 - i * 2 - 2;
                    num5 = 14 - i * 2;
                    num6 = 0;
                    break;
                case 3:
                    num7 = i * 2;
                    break;
                default:
                    num7 = 16 - i * 2 - 2;
                    break;
                }
                Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2((float)num7, (float)(i * num3 + num4)), (Rectangle?)new Rectangle(drawData.tileFrameX + drawData.addFrX + num7, drawData.tileFrameY + drawData.addFrY + num6, num3, num5), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
            }
            int num8 = ((num <= 2) ? 14 : 0);
            Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(0f, (float)num8), (Rectangle?)new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY + num8, 16, 2), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
            return;
        }
        if (!TileID.Sets.Platforms[drawData.typeCache] && !TileID.Sets.IgnoresNearbyHalfbricksWhenDrawn[drawData.typeCache] && _tileSolid[drawData.typeCache] && !TileID.Sets.NotReallySolid[drawData.typeCache] && !drawData.tileCache.halfBrick())
        {
            tile = Main.tile[tileX - 1, tileY];
            if (!tile.halfBrick())
            {
                tile = Main.tile[tileX + 1, tileY];
                if (!tile.halfBrick())
                {
                    goto IL_0cc9;
                }
            }
            tile = Main.tile[tileX - 1, tileY];
            if (tile.halfBrick())
            {
                tile = Main.tile[tileX + 1, tileY];
                if (tile.halfBrick())
                {
                    Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(0f, 8f), (Rectangle?)new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.addFrY + drawData.tileFrameY + 8, drawData.tileWidth, 8), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                    Rectangle value3 = default(Rectangle);
                    ((Rectangle)(ref value3))._002Ector(126 + drawData.addFrX, drawData.addFrY, 16, 8);
                    tile = Main.tile[tileX, tileY - 1];
                    if (tile.active())
                    {
                        tile = Main.tile[tileX, tileY - 1];
                        if (!tile.bottomSlope())
{
                            tile = Main.tile[tileX, tileY - 1];
                            if (tile.type == drawData.typeCache)
{
                                ((Rectangle)(ref value3))._002Ector(90 + drawData.addFrX, drawData.addFrY, 16, 8);
                            }
                        }
                    }
                    Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, (Rectangle?)value3, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                    return;
                }
            }
            tile = Main.tile[tileX - 1, tileY];
            if (tile.halfBrick())
            {
                int num9 = 4;
                if (TileID.Sets.AllBlocksWithSmoothBordersToResolveHalfBlockIssue[drawData.typeCache])
                {
                    num9 = 2;
                }
                Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(0f, 8f), (Rectangle?)new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.addFrY + drawData.tileFrameY + 8, drawData.tileWidth, 8), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2((float)num9, 0f), (Rectangle?)new Rectangle(drawData.tileFrameX + num9 + drawData.addFrX, drawData.addFrY + drawData.tileFrameY, drawData.tileWidth - num9, drawData.tileHeight), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, (Rectangle?)new Rectangle(144 + drawData.addFrX, drawData.addFrY, num9, 8), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                if (num9 == 2)
                {
                    Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, (Rectangle?)new Rectangle(148 + drawData.addFrX, drawData.addFrY, 2, 2), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                }
                return;
            }
            tile = Main.tile[tileX + 1, tileY];
            if (tile.halfBrick())
            {
                int num10 = 4;
                if (TileID.Sets.AllBlocksWithSmoothBordersToResolveHalfBlockIssue[drawData.typeCache])
                {
                    num10 = 2;
                }
                Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(0f, 8f), (Rectangle?)new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.addFrY + drawData.tileFrameY + 8, drawData.tileWidth, 8), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, (Rectangle?)new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.addFrY + drawData.tileFrameY, drawData.tileWidth - num10, drawData.tileHeight), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2((float)(16 - num10), 0f), (Rectangle?)new Rectangle(144 + (16 - num10), 0, num10, 8), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                if (num10 == 2)
                {
                    Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(14f, 0f), (Rectangle?)new Rectangle(156, 0, 2, 2), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                }
            }
            return;
        }
        goto IL_0cc9;
        IL_043e:
        Rectangle value2 = default(Rectangle);
        ((Rectangle)(ref value2))._002Ector(162, (int)drawData.tileFrameY, 16, 16);
        bool[] platforms = TileID.Sets.Platforms;
        tile = Main.tile[tileX - 1, tileY + 1];
        if (platforms[tile.type])
        {
            tile = Main.tile[tileX - 1, tileY + 1];
            if (tile.slope() == 0)
            {
                value2.X = 306;
            }
        }
        Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(0f, 16f), (Rectangle?)value2, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
        return;
        IL_0e81:
        if (TileID.Sets.CritterCageLidStyle[drawData.typeCache] >= 0)
        {
            int num2 = TileID.Sets.CritterCageLidStyle[drawData.typeCache];
            if ((num2 < 3 && normalTileRect.Y % 54 == 0) || (num2 >= 3 && normalTileRect.Y % 36 == 0))
            {
                Vector2 position = normalTilePosition;
                position.Y += 8f;
                Rectangle value4 = normalTileRect;
                value4.Y += 8;
                value4.Height -= 8;
                Main.spriteBatch.Draw(drawData.drawTexture, position, (Rectangle?)value4, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
                position = normalTilePosition;
                position.Y -= 2f;
                value4 = normalTileRect;
                value4.Y = 0;
                value4.Height = 10;
                Main.spriteBatch.Draw(TextureAssets.CageTop[num2].Value, position, (Rectangle?)value4, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
            }
            else
            {
                Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, (Rectangle?)normalTileRect, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
            }
        }
        else
        {
            Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, (Rectangle?)normalTileRect, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
        }
        goto IL_101e;
        IL_0269:
        Rectangle value = default(Rectangle);
        ((Rectangle)(ref value))._002Ector(198, (int)drawData.tileFrameY, 16, 16);
        bool[] platforms2 = TileID.Sets.Platforms;
        tile = Main.tile[tileX + 1, tileY + 1];
        if (platforms2[tile.type])
        {
            tile = Main.tile[tileX + 1, tileY + 1];
            if (tile.slope() == 0)
            {
                value.X = 324;
            }
        }
        Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(0f, 16f), (Rectangle?)value, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
        return;
        IL_0cc9:
        if (Lighting.NotRetro && _tileSolid[drawData.typeCache] && !drawData.tileCache.halfBrick() && !TileID.Sets.DontDrawTileSliced[drawData.tileCache.type])
        {
            DrawSingleTile_SlicedBlock(normalTilePosition, tileX, tileY, drawData);
            return;
        }
        if (drawData.halfBrickHeight != 8)
        {
            goto IL_0e81;
        }
        tile = Main.tile[tileX, tileY + 1];
        if (tile.active())
        {
            bool[] tileSolid3 = _tileSolid;
            tile = Main.tile[tileX, tileY + 1];
            if (tileSolid3[tile.type])
            {
                tile = Main.tile[tileX, tileY + 1];
                if (!tile.halfBrick())
                {
                    goto IL_0e81;
                }
            }
        }
        if (TileID.Sets.Platforms[drawData.typeCache])
        {
            Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, (Rectangle?)normalTileRect, drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
        }
        else
        {
            Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, (Rectangle?)normalTileRect.Modified(0, 0, 0, -4), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
            Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition + new Vector2(0f, 4f), (Rectangle?)new Rectangle(144 + drawData.addFrX, 66 + drawData.addFrY, drawData.tileWidth, 4), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
        }
        goto IL_101e;
        IL_101e:
        DrawSingleTile_Flames(screenPosition, screenOffset, tileX, tileY, drawData);
    }
References Terraria.GameContent.Drawing.TileDrawing._tileSolid, Terraria.GameContent.Drawing.TileDrawing._zero, Terraria.Tile.active(), Terraria.ID.TileID.Sets.AllBlocksWithSmoothBordersToResolveHalfBlockIssue, Terraria.ID.TileID.Sets.BlocksStairs, Terraria.ID.TileID.Sets.BlocksStairsAbove, Terraria.Tile.blockType(), Terraria.Tile.bottomSlope(), Terraria.GameContent.TextureAssets.CageTop, Terraria.ID.TileID.Sets.CritterCageLidStyle, Terraria.ID.TileID.Sets.DontDrawTileSliced, Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile_Flames(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile_SlicedBlock(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.Tile.halfBrick(), Terraria.ID.TileID.Sets.HasSlopeFrames, Terraria.ID.TileID.Sets.IgnoresNearbyHalfbricksWhenDrawn, Terraria.WorldGen.IsRope(), Terraria.ID.TileID.Sets.NotReallySolid, Terraria.Lighting.NotRetro, Terraria.ID.TileID.Sets.Platforms, Terraria.Tile.slope(), Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile().