TModLoader: Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part1
CacheSpecialDraws_Part1()
void Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part1 (int tileX, int tileY, int tileType, int drawDataTileFrameX, int drawDataTileFrameY, bool skipDraw) inline private
    {
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0107: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0206: Unknown result type (might be due to invalid IL or missing references)
        //IL_0208: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        if (tileType == 395)
        {
            Point point = default(Point);
            ((Point)(ref point))._002Ector(tileX, tileY);
            if (drawDataTileFrameX % 36 != 0)
            {
                point.X--;
            }
            if (drawDataTileFrameY % 36 != 0)
            {
                point.Y--;
            }
            if (!_itemFrameTileEntityPositions.ContainsKey(point))
            {
                _itemFrameTileEntityPositions[point] = TEItemFrame.Find(point.X, point.Y);
                if (_itemFrameTileEntityPositions[point] != -1)
                {
                    AddSpecialLegacyPoint(point);
                }
            }
        }
        if (tileType == 520)
        {
            Point point2 = default(Point);
            ((Point)(ref point2))._002Ector(tileX, tileY);
            if (!_foodPlatterTileEntityPositions.ContainsKey(point2))
            {
                _foodPlatterTileEntityPositions[point2] = TEFoodPlatter.Find(point2.X, point2.Y);
                if (_foodPlatterTileEntityPositions[point2] != -1)
                {
                    AddSpecialLegacyPoint(point2);
                }
            }
        }
        if (tileType == 471)
        {
            Point point3 = default(Point);
            ((Point)(ref point3))._002Ector(tileX, tileY);
            point3.X -= drawDataTileFrameX % 54 / 18;
            point3.Y -= drawDataTileFrameY % 54 / 18;
            if (!_weaponRackTileEntityPositions.ContainsKey(point3))
            {
                _weaponRackTileEntityPositions[point3] = TEWeaponsRack.Find(point3.X, point3.Y);
                if (_weaponRackTileEntityPositions[point3] != -1)
                {
                    AddSpecialLegacyPoint(point3);
                }
            }
        }
        if (tileType == 470)
        {
            Point point4 = default(Point);
            ((Point)(ref point4))._002Ector(tileX, tileY);
            point4.X -= drawDataTileFrameX % 36 / 18;
            point4.Y -= drawDataTileFrameY % 54 / 18;
            if (!_displayDollTileEntityPositions.ContainsKey(point4))
            {
                _displayDollTileEntityPositions[point4] = TEDisplayDoll.Find(point4.X, point4.Y);
                if (_displayDollTileEntityPositions[point4] != -1)
                {
                    AddSpecialLegacyPoint(point4);
                }
            }
        }
        if (tileType == 475)
        {
            Point point5 = default(Point);
            ((Point)(ref point5))._002Ector(tileX, tileY);
            point5.X -= drawDataTileFrameX % 54 / 18;
            point5.Y -= drawDataTileFrameY % 72 / 18;
            if (!_hatRackTileEntityPositions.ContainsKey(point5))
            {
                _hatRackTileEntityPositions[point5] = TEHatRack.Find(point5.X, point5.Y);
                if (_hatRackTileEntityPositions[point5] != -1)
                {
                    AddSpecialLegacyPoint(point5);
                }
            }
        }
        if (tileType == 412 && drawDataTileFrameX == 0 && drawDataTileFrameY == 0)
        {
            AddSpecialLegacyPoint(tileX, tileY);
        }
        if (tileType == 620 && drawDataTileFrameX == 0 && drawDataTileFrameY == 0)
        {
            AddSpecialLegacyPoint(tileX, tileY);
        }
        if (tileType == 237 && drawDataTileFrameX == 18 && drawDataTileFrameY == 0)
        {
            AddSpecialLegacyPoint(tileX, tileY);
        }
        if (skipDraw)
        {
            return;
        }
        switch (tileType)
        {
        case 323:
            if (drawDataTileFrameX <= 132 && drawDataTileFrameX >= 88)
            {
                AddSpecialPoint(tileX, tileY, TileCounterType.Tree);
            }
            break;
        case 5:
        case 583:
        case 584:
        case 585:
        case 586:
        case 587:
        case 588:
        case 589:
        case 596:
        case 616:
        case 634:
            if (drawDataTileFrameY >= 198 && drawDataTileFrameX >= 22)
            {
                AddSpecialPoint(tileX, tileY, TileCounterType.Tree);
            }
            break;
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._displayDollTileEntityPositions, Terraria.GameContent.Drawing.TileDrawing._foodPlatterTileEntityPositions, Terraria.GameContent.Drawing.TileDrawing._hatRackTileEntityPositions, Terraria.GameContent.Drawing.TileDrawing._itemFrameTileEntityPositions, Terraria.GameContent.Drawing.TileDrawing._weaponRackTileEntityPositions, Terraria.GameContent.Drawing.TileDrawing.AddSpecialLegacyPoint(), Terraria.GameContent.Drawing.TileDrawing.AddSpecialPoint(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Find(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.Find(), Terraria.GameContent.Tile_Entities.TEHatRack.Find(), Terraria.GameContent.Tile_Entities.TEItemFrame.Find(), and Terraria.GameContent.Tile_Entities.TEWeaponsRack.Find().
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile().