TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawMasterTrophies
DrawMasterTrophies()
void Terraria.GameContent.Drawing.TileDrawing.DrawMasterTrophies () inline private
    {
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0146: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        int num = 11;
        int num2 = _specialsCount[num];
        for (int i = 0; i < num2; i++)
        {
            Point p = _specialPositions[num][i];
            Tile tile = Main.tile[p.X, p.Y];
            if (tile != null && tile.active())
            {
                Texture2D value = TextureAssets.Extra[198].Value;
                int frameY = tile.frameX / 54;
                bool num6 = tile.frameY / 72 != 0;
                int horizontalFrames = 1;
                int verticalFrames = 28;
                Rectangle rectangle = value.Frame(horizontalFrames, verticalFrames, 0, frameY);
                Vector2 origin = rectangle.Size() / 2f;
                Vector2 val = p.ToWorldCoordinates(24f, 64f);
                float num3 = (float)Math.Sin(Main.GlobalTimeWrappedHourly * ((float)Math.PI * 2f) / 5f);
                Vector2 vector2 = val + new Vector2(0f, -40f) + new Vector2(0f, num3 * 4f);
                Color color = Lighting.GetColor(p.X, p.Y);
                SpriteEffects effects = (SpriteEffects)(num6 ? 1 : 0);
                Main.spriteBatch.Draw(value, vector2 - Main.screenPosition, (Rectangle?)rectangle, color, 0f, origin, 1f, effects, 0f);
                float num4 = (float)Math.Sin(Main.GlobalTimeWrappedHourly * ((float)Math.PI * 2f) / 2f) * 0.3f + 0.7f;
                Color color2 = color;
                ((Color)(ref color2)).A = 0;
                color2 = color2 * 0.1f * num4;
                for (float num5 = 0f; num5 < 1f; num5 += 1f / 6f)
                {
                    Main.spriteBatch.Draw(value, vector2 - Main.screenPosition + ((float)Math.PI * 2f * num5).ToRotationVector2() * (6f + num3 * 2f), (Rectangle?)rectangle, color2, 0f, origin, 1f, effects, 0f);
                }
            }
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._specialPositions, Terraria.GameContent.Drawing.TileDrawing._specialsCount, Terraria.Tile.active(), Terraria.GameContent.TextureAssets.Extra, Terraria.Lighting.GetColor(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, and Terraria.Main.tile.
Referenced by Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles().