TModLoader: Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture
GetTileDrawTexture() [2/2]
Texture2D Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture (Tile tile, int tileX, int tileY, int paintOverride) inline
    {
        Texture2D result = TextureAssets.Tile[tile.type].Value;
        int tileStyle = 0;
        int num = tile.type;
        switch (tile.type)
        {
        case 5:
            tileStyle = GetTreeBiome(tileX, tileY, tile.frameX, tile.frameY);
            break;
        case 323:
            tileStyle = GetPalmTreeBiome(tileX, tileY);
            break;
        case 83:
            if (IsAlchemyPlantHarvestable(tile.frameX / 18))
            {
                num = 84;
            }
            Main.instance.LoadTiles(num);
            break;
        case 80:
        case 227:
        {
            WorldGen.GetCactusType(tileX, tileY, tile.frameX, tile.frameY, out var sandType);
            if (!TileLoader.CanGrowModCactus(sandType))
            {
                break;
            }
            if (num == 80)
            {
                tileStyle = sandType + 1;
            }
            else if (tile.frameX == 204 || tile.frameX == 202)
            {
                Asset<Texture2D> asset = PlantLoader.GetCactusFruitTexture(sandType);
                if (asset != null)
                {
                    return asset.Value;
                }
            }
            break;
        }
        }
        Texture2D texture2D = _paintSystem.TryGetTileAndRequestIfNotReady(num, tileStyle, paintOverride);
        if (texture2D != null)
        {
            result = texture2D;
        }
        return result;
    }
References Terraria.GameContent.Drawing.TileDrawing._paintSystem, Terraria.ModLoader.TileLoader.CanGrowModCactus(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.ModLoader.PlantLoader.GetCactusFruitTexture(), Terraria.WorldGen.GetCactusType(), Terraria.GameContent.Drawing.TileDrawing.GetPalmTreeBiome(), Terraria.GameContent.Drawing.TileDrawing.GetTreeBiome(), Terraria.Main.instance, Terraria.GameContent.Drawing.TileDrawing.IsAlchemyPlantHarvestable(), Terraria.Main.LoadTiles(), Terraria.GameContent.TextureAssets.Tile, Terraria.GameContent.TilePaintSystemV2.TryGetTileAndRequestIfNotReady(), and Terraria.Tile.type.