TModLoader: Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf
EmitLivingTreeLeaf()
void Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf (int i, int j, int leafGoreType) inline
Emits a single living tree leaf or other gore instance directly below the target tile.
With a 50% chance, also emits a second leaf or other gore instance directly to the side of the target tile, dependent on wind direction.
Used by vanilla's two types of Living Trees, from which this method and its two submethods get their collective name.
Parameters
i The X coordinate of the target tile.
j The Y coordinate of the target tile.
leafGoreType The numerical ID of the leaf or other gore instance that should be spawned.
    {
        EmitLivingTreeLeaf_Below(i, j, leafGoreType);
        if (_rand.Next(2) == 0)
        {
            EmitLivingTreeLeaf_Sideways(i, j, leafGoreType);
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf_Below(), Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf_Sideways(), and Terraria.Utilities.UnifiedRandom.Next().
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles().