TModLoader: Terraria.GameContent.Drawing.TileDrawing.EmitAlchemyHerbParticles
EmitAlchemyHerbParticles()
void Terraria.GameContent.Drawing.TileDrawing.EmitAlchemyHerbParticles (int j, int i, int style) inline private
    {
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0366: Unknown result type (might be due to invalid IL or missing references)
        //IL_0380: Unknown result type (might be due to invalid IL or missing references)
        //IL_0397: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        Color newColor = default(Color);
        if (style == 0 && _rand.Next(100) == 0)
        {
            Vector2 position = new Vector2((float)(i * 16), (float)(j * 16 - 4));
            newColor = default(Color);
            int num = Dust.NewDust(position, 16, 16, 19, 0f, 0f, 160, newColor, 0.1f);
            _dust[num].velocity.X /= 2f;
            _dust[num].velocity.Y /= 2f;
            _dust[num].noGravity = true;
            _dust[num].fadeIn = 1f;
        }
        if (style == 1 && _rand.Next(100) == 0)
        {
            Vector2 position2 = new Vector2((float)(i * 16), (float)(j * 16));
            newColor = default(Color);
            Dust.NewDust(position2, 16, 16, 41, 0f, 0f, 250, newColor, 0.8f);
        }
        if (style == 3)
        {
            if (_rand.Next(200) == 0)
            {
                Vector2 position3 = new Vector2((float)(i * 16), (float)(j * 16));
                newColor = default(Color);
                int num2 = Dust.NewDust(position3, 16, 16, 14, 0f, 0f, 100, newColor, 0.2f);
                _dust[num2].fadeIn = 1.2f;
            }
            if (_rand.Next(75) == 0)
            {
                Vector2 position4 = new Vector2((float)(i * 16), (float)(j * 16));
                newColor = default(Color);
                int num3 = Dust.NewDust(position4, 16, 16, 27, 0f, 0f, 100, newColor);
                _dust[num3].velocity.X /= 2f;
                _dust[num3].velocity.Y /= 2f;
            }
        }
        if (style == 4 && _rand.Next(150) == 0)
        {
            Vector2 position5 = new Vector2((float)(i * 16), (float)(j * 16));
            newColor = default(Color);
            int num4 = Dust.NewDust(position5, 16, 8, 16, 0f, 0f, 0, newColor);
            _dust[num4].velocity.X /= 3f;
            _dust[num4].velocity.Y /= 3f;
            _dust[num4].velocity.Y -= 0.7f;
            _dust[num4].alpha = 50;
            _dust[num4].scale *= 0.1f;
            _dust[num4].fadeIn = 0.9f;
            _dust[num4].noGravity = true;
        }
        if (style == 5 && _rand.Next(40) == 0)
        {
            Vector2 position6 = new Vector2((float)(i * 16), (float)(j * 16 - 6));
            newColor = default(Color);
            int num5 = Dust.NewDust(position6, 16, 16, 6, 0f, 0f, 0, newColor, 1.5f);
            _dust[num5].velocity.Y -= 2f;
            _dust[num5].noGravity = true;
        }
        if (style == 6 && _rand.Next(30) == 0)
        {
            ((Color)(ref newColor))._002Ector(50, 255, 255, 255);
            int num6 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 43, 0f, 0f, 254, newColor, 0.5f);
            Dust obj = _dust[num6];
            obj.velocity *= 0f;
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._dust, Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.Dust.alpha, Terraria.Dust.fadeIn, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.scale, and Terraria.Dust.velocity.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles().