TModLoader: Terraria.GameContent.Drawing.TileDrawing.GetTileOutlineInfo
GetTileOutlineInfo()
void Terraria.GameContent.Drawing.TileDrawing.GetTileOutlineInfo (int x, int y, ushort typeCache, ref Color tileLight, ref Texture2D highlightTexture, ref Color highlightColor) inline
    {
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        if (Main.InSmartCursorHighlightArea(x, y, out var actuallySelected))
        {
            int num = (((Color)(ref tileLight)).R + ((Color)(ref tileLight)).G + ((Color)(ref tileLight)).B) / 3;
            if (num > 10)
            {
                highlightTexture = TextureAssets.HighlightMask[typeCache].Value;
                highlightColor = Colors.GetSelectionGlowColor(actuallySelected, num);
            }
        }
    }
References Terraria.ID.Colors.GetSelectionGlowColor(), Terraria.GameContent.TextureAssets.HighlightMask, and Terraria.Main.InSmartCursorHighlightArea().
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile().