TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy
DrawSpecialTilesLegacy()
void Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy (Vector2 screenPosition, Vector2 offSet) inline private
Definition at line 8944 of file TileDrawing.cs.
    {
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_0369: Unknown result type (might be due to invalid IL or missing references)
        //IL_0375: Unknown result type (might be due to invalid IL or missing references)
        //IL_037a: Unknown result type (might be due to invalid IL or missing references)
        //IL_037b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0380: Unknown result type (might be due to invalid IL or missing references)
        //IL_0384: Unknown result type (might be due to invalid IL or missing references)
        //IL_0389: Unknown result type (might be due to invalid IL or missing references)
        //IL_0394: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0572: Unknown result type (might be due to invalid IL or missing references)
        //IL_057b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0741: Unknown result type (might be due to invalid IL or missing references)
        //IL_074e: Unknown result type (might be due to invalid IL or missing references)
        //IL_075a: Unknown result type (might be due to invalid IL or missing references)
        //IL_075f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0760: Unknown result type (might be due to invalid IL or missing references)
        //IL_076e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0778: Unknown result type (might be due to invalid IL or missing references)
        //IL_0782: Unknown result type (might be due to invalid IL or missing references)
        //IL_078c: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_042a: Unknown result type (might be due to invalid IL or missing references)
        //IL_041b: Unknown result type (might be due to invalid IL or missing references)
        //IL_087f: Unknown result type (might be due to invalid IL or missing references)
        //IL_088c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0898: Unknown result type (might be due to invalid IL or missing references)
        //IL_089d: Unknown result type (might be due to invalid IL or missing references)
        //IL_089e: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_042f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0431: Unknown result type (might be due to invalid IL or missing references)
        //IL_043a: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05db: Unknown result type (might be due to invalid IL or missing references)
        //IL_05dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_05df: Unknown result type (might be due to invalid IL or missing references)
        //IL_0606: Unknown result type (might be due to invalid IL or missing references)
        //IL_0616: Unknown result type (might be due to invalid IL or missing references)
        //IL_0622: Unknown result type (might be due to invalid IL or missing references)
        //IL_0627: Unknown result type (might be due to invalid IL or missing references)
        //IL_0628: Unknown result type (might be due to invalid IL or missing references)
        //IL_062d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0634: Unknown result type (might be due to invalid IL or missing references)
        //IL_0645: Unknown result type (might be due to invalid IL or missing references)
        //IL_064c: Unknown result type (might be due to invalid IL or missing references)
        //IL_065a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0661: Unknown result type (might be due to invalid IL or missing references)
        //IL_0667: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_091e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0923: Unknown result type (might be due to invalid IL or missing references)
        //IL_0928: Unknown result type (might be due to invalid IL or missing references)
        //IL_092a: Unknown result type (might be due to invalid IL or missing references)
        //IL_093a: Unknown result type (might be due to invalid IL or missing references)
        //IL_093f: Unknown result type (might be due to invalid IL or missing references)
        //IL_094c: Unknown result type (might be due to invalid IL or missing references)
        //IL_095b: Unknown result type (might be due to invalid IL or missing references)
        //IL_096c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0971: Unknown result type (might be due to invalid IL or missing references)
        //IL_0976: Unknown result type (might be due to invalid IL or missing references)
        //IL_097f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0981: Unknown result type (might be due to invalid IL or missing references)
        //IL_0988: Unknown result type (might be due to invalid IL or missing references)
        //IL_098f: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_09bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_067b: Unknown result type (might be due to invalid IL or missing references)
        //IL_068b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0697: Unknown result type (might be due to invalid IL or missing references)
        //IL_069c: Unknown result type (might be due to invalid IL or missing references)
        //IL_069d: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0458: Unknown result type (might be due to invalid IL or missing references)
        //IL_045c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0461: Unknown result type (might be due to invalid IL or missing references)
        //IL_0463: Unknown result type (might be due to invalid IL or missing references)
        //IL_0465: Unknown result type (might be due to invalid IL or missing references)
        //IL_0485: Unknown result type (might be due to invalid IL or missing references)
        //IL_0494: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0502: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0512: Unknown result type (might be due to invalid IL or missing references)
        //IL_0514: Unknown result type (might be due to invalid IL or missing references)
        //IL_051d: Unknown result type (might be due to invalid IL or missing references)
        //IL_051f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0529: Unknown result type (might be due to invalid IL or missing references)
        //IL_052d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0240: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_027f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_028d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0248: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0306: Unknown result type (might be due to invalid IL or missing references)
        //IL_0308: Unknown result type (might be due to invalid IL or missing references)
        //IL_031c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0323: Unknown result type (might be due to invalid IL or missing references)
        Vector2 origin = default(Vector2);
        Color color5 = default(Color);
        Rectangle value7 = default(Rectangle);
        for (int i = 0; i < _specialTilesCount; i++)
        {
            int num = _specialTileX[i];
            int num10 = _specialTileY[i];
            Tile tile = Main.tile[num, num10];
            ushort type = tile.type;
            short frameX = tile.frameX;
            short frameY = tile.frameY;
            if (type == 237)
            {
                Main.spriteBatch.Draw(TextureAssets.SunOrb.Value, new Vector2((float)(num * 16 - (int)screenPosition.X) + 8f, (float)(num10 * 16 - (int)screenPosition.Y - 36)) + offSet, (Rectangle?)new Rectangle(0, 0, TextureAssets.SunOrb.Width(), TextureAssets.SunOrb.Height()), new Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, 0), Main.sunCircle, new Vector2((float)(TextureAssets.SunOrb.Width() / 2), (float)(TextureAssets.SunOrb.Height() / 2)), 1f, (SpriteEffects)0, 0f);
            }
            if (type == 334 && frameX >= 5000)
            {
                _ = frameY / 18;
                int num11 = frameX;
                int num12 = 0;
                int num13 = num11 % 5000;
                num13 -= 100;
                while (num11 >= 5000)
                {
                    num12++;
                    num11 -= 5000;
                }
                int frameX2 = Main.tile[num + 1, num10].frameX;
                frameX2 = ((frameX2 < 25000) ? (frameX2 - 10000) : (frameX2 - 25000));
                Item item = new Item();
                item.netDefaults(num13);
                item.Prefix(frameX2);
                Main.instance.LoadItem(item.type);
                Texture2D value = TextureAssets.Item[item.type].Value;
                Rectangle value2 = ((Main.itemAnimations[item.type] == null) ? value.Frame() : Main.itemAnimations[item.type].GetFrame(value));
                int width = value2.Width;
                int height = value2.Height;
                float num14 = 1f;
                if (width > 40 || height > 40)
                {
                    num14 = ((width <= height) ? (40f / (float)height) : (40f / (float)width));
                }
                num14 *= item.scale;
                SpriteEffects effects = (SpriteEffects)0;
                if (num12 >= 3)
                {
                    effects = (SpriteEffects)1;
                }
                Color color = Lighting.GetColor(num, num10);
                Main.spriteBatch.Draw(value, new Vector2((float)(num * 16 - (int)screenPosition.X + 24), (float)(num10 * 16 - (int)screenPosition.Y + 8)) + offSet, (Rectangle?)value2, Lighting.GetColor(num, num10), 0f, new Vector2((float)(width / 2), (float)(height / 2)), num14, effects, 0f);
                if (item.color != default(Color))
                {
                    Main.spriteBatch.Draw(value, new Vector2((float)(num * 16 - (int)screenPosition.X + 24), (float)(num10 * 16 - (int)screenPosition.Y + 8)) + offSet, (Rectangle?)value2, item.GetColor(color), 0f, new Vector2((float)(width / 2), (float)(height / 2)), num14, effects, 0f);
                }
            }
            if (type == 395)
            {
                Item item2 = ((TEItemFrame)TileEntity.ByPosition[new Point16(num, num10)]).item;
                Vector2 screenPositionForItemCenter = new Vector2((float)(num * 16 - (int)screenPosition.X + 16), (float)(num10 * 16 - (int)screenPosition.Y + 16)) + offSet;
                Color color2 = Lighting.GetColor(num, num10);
                ItemSlot.DrawItemIcon(item2, 31, Main.spriteBatch, screenPositionForItemCenter, item2.scale, 20f, color2);
            }
            if (type == 520)
            {
                Item item3 = ((TEFoodPlatter)TileEntity.ByPosition[new Point16(num, num10)]).item;
                if (!item3.IsAir)
                {
                    Main.instance.LoadItem(item3.type);
                    Texture2D value3 = TextureAssets.Item[item3.type].Value;
                    Rectangle value4 = ((!ItemID.Sets.IsFood[item3.type]) ? value3.Frame() : value3.Frame(1, 3, 0, 2));
                    int width2 = value4.Width;
                    int height2 = value4.Height;
                    float num15 = 1f;
                    SpriteEffects effects2 = (SpriteEffects)(tile.frameX == 0);
                    Color color3 = Lighting.GetColor(num, num10);
                    Color currentColor = color3;
                    float scale = 1f;
                    ItemSlot.GetItemLight(ref currentColor, ref scale, item3);
                    num15 *= scale;
                    Vector2 position = new Vector2((float)(num * 16 - (int)screenPosition.X + 8), (float)(num10 * 16 - (int)screenPosition.Y + 16)) + offSet;
                    position.Y += 2f;
                    ((Vector2)(ref origin))._002Ector((float)(width2 / 2), (float)height2);
                    Main.spriteBatch.Draw(value3, position, (Rectangle?)value4, currentColor, 0f, origin, num15, effects2, 0f);
                    if (item3.color != default(Color))
                    {
                        Main.spriteBatch.Draw(value3, position, (Rectangle?)value4, item3.GetColor(color3), 0f, origin, num15, effects2, 0f);
                    }
                }
            }
            if (type == 471)
            {
                Item item4 = (TileEntity.ByPosition[new Point16(num, num10)] as TEWeaponsRack).item;
                Main.GetItemDrawFrame(item4.type, out var itemTexture, out var itemFrame);
                int width3 = itemFrame.Width;
                int height3 = itemFrame.Height;
                float num16 = 1f;
                float num17 = 40f;
                if ((float)width3 > num17 || (float)height3 > num17)
                {
                    num16 = ((width3 <= height3) ? (num17 / (float)height3) : (num17 / (float)width3));
                }
                num16 *= item4.scale;
                SpriteEffects effects3 = (SpriteEffects)1;
                if (tile.frameX < 54)
                {
                    effects3 = (SpriteEffects)0;
                }
                Color color4 = Lighting.GetColor(num, num10);
                Color currentColor2 = color4;
                float scale2 = 1f;
                ItemSlot.GetItemLight(ref currentColor2, ref scale2, item4);
                num16 *= scale2;
                Main.spriteBatch.Draw(itemTexture, new Vector2((float)(num * 16 - (int)screenPosition.X + 24), (float)(num10 * 16 - (int)screenPosition.Y + 24)) + offSet, (Rectangle?)itemFrame, currentColor2, 0f, new Vector2((float)(width3 / 2), (float)(height3 / 2)), num16, effects3, 0f);
                if (item4.color != default(Color))
                {
                    Main.spriteBatch.Draw(itemTexture, new Vector2((float)(num * 16 - (int)screenPosition.X + 24), (float)(num10 * 16 - (int)screenPosition.Y + 24)) + offSet, (Rectangle?)itemFrame, item4.GetColor(color4), 0f, new Vector2((float)(width3 / 2), (float)(height3 / 2)), num16, effects3, 0f);
                }
            }
            if (type == 412)
            {
                Texture2D value5 = TextureAssets.GlowMask[202].Value;
                int num2 = Main.tileFrame[type] / 60;
                int frameY2 = (num2 + 1) % 4;
                float num3 = (float)(Main.tileFrame[type] % 60) / 60f;
                ((Color)(ref color5))._002Ector(255, 255, 255, 255);
                Main.spriteBatch.Draw(value5, new Vector2((float)(num * 16 - (int)screenPosition.X), (float)(num10 * 16 - (int)screenPosition.Y + 10)) + offSet, (Rectangle?)value5.Frame(1, 4, 0, num2), color5 * (1f - num3), 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
                Main.spriteBatch.Draw(value5, new Vector2((float)(num * 16 - (int)screenPosition.X), (float)(num10 * 16 - (int)screenPosition.Y + 10)) + offSet, (Rectangle?)value5.Frame(1, 4, 0, frameY2), color5 * num3, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
            }
            if (type == 620)
            {
                Texture2D value6 = TextureAssets.Extra[202].Value;
                _ = (float)(Main.tileFrame[type] % 60) / 60f;
                int num4 = 2;
                Main.critterCage = true;
                int waterAnimalCageFrame = GetWaterAnimalCageFrame(num, num10, frameX, frameY);
                int num5 = 8;
                int num6 = Main.butterflyCageFrame[num5, waterAnimalCageFrame];
                int num7 = 6;
                float num8 = 1f;
                ((Rectangle)(ref value7))._002Ector(0, 34 * num6, 32, 32);
                Vector2 vector = new Vector2((float)(num * 16 - (int)screenPosition.X), (float)(num10 * 16 - (int)screenPosition.Y + num4)) + offSet;
                Main.spriteBatch.Draw(value6, vector, (Rectangle?)value7, new Color(255, 255, 255, 255), 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
                for (int j = 0; j < num7; j++)
                {
                    Color color6 = Utils.MultiplyRGBA(new Color(127, 127, 127, 0), Main.hslToRgb((Main.GlobalTimeWrappedHourly + (float)j / (float)num7) % 1f, 1f, 0.5f));
                    color6 *= 1f - num8 * 0.5f;
                    ((Color)(ref color6)).A = 0;
                    int num9 = 2;
                    Vector2 position2 = vector + ((float)j / (float)num7 * ((float)Math.PI * 2f)).ToRotationVector2() * ((float)num9 * num8 + 2f);
                    Main.spriteBatch.Draw(value6, position2, (Rectangle?)value7, color6, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
                }
                Main.spriteBatch.Draw(value6, vector, (Rectangle?)value7, new Color(255, 255, 255, 0) * 0.1f, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
            }
            TileLoader.SpecialDraw(type, num, num10, Main.spriteBatch);
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._specialTilesCount, Terraria.GameContent.Drawing.TileDrawing._specialTileX, Terraria.GameContent.Drawing.TileDrawing._specialTileY, Terraria.Main.butterflyCageFrame, Terraria.DataStructures.TileEntity.ByPosition, Terraria.Item.color, Terraria.UI.ItemSlot.DrawItemIcon(), Terraria.GameContent.TextureAssets.Extra, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Item.GetColor(), Terraria.Lighting.GetColor(), Terraria.DataStructures.DrawAnimation.GetFrame(), Terraria.Main.GetItemDrawFrame(), Terraria.UI.ItemSlot.GetItemLight(), Terraria.GameContent.Drawing.TileDrawing.GetWaterAnimalCageFrame(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.TextureAssets.GlowMask, Terraria.Main.hslToRgb(), Terraria.Main.instance, Terraria.ID.ItemID.Sets.IsFood, Terraria.GameContent.TextureAssets.Item, Terraria.Main.itemAnimations, Terraria.Main.LoadItem(), Terraria.Main.mouseTextColor, Terraria.Utils.MultiplyRGBA(), Terraria.Item.netDefaults(), Terraria.Item.Prefix(), Terraria.Item.scale, Terraria.ModLoader.TileLoader.SpecialDraw(), Terraria.Main.spriteBatch, Terraria.Main.sunCircle, Terraria.GameContent.TextureAssets.SunOrb, Terraria.Main.tile, Terraria.Main.tileFrame, Terraria.Item.type, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw().