TModLoader: Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part2
CacheSpecialDraws_Part2()
void Terraria.GameContent.Drawing.TileDrawing.CacheSpecialDraws_Part2 (int tileX, int tileY, TileDrawInfo drawData, bool skipDraw) inline private
    {
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_019f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        if (TileID.Sets.BasicChest[drawData.typeCache])
        {
            Point key = default(Point);
            ((Point)(ref key))._002Ector(tileX, tileY);
            if (drawData.tileFrameX % 36 != 0)
            {
                key.X--;
            }
            if (drawData.tileFrameY % 36 != 0)
            {
                key.Y--;
            }
            if (!_chestPositions.ContainsKey(key))
            {
                _chestPositions[key] = Chest.FindChest(key.X, key.Y);
            }
            int num = drawData.tileFrameX / 18;
            int num6 = drawData.tileFrameY / 18;
            int num2 = drawData.tileFrameX / 36;
            int num3 = num * 18;
            drawData.addFrX = num3 - drawData.tileFrameX;
            int num4 = num6 * 18;
            if (_chestPositions[key] != -1)
            {
                int frame = Main.chest[_chestPositions[key]].frame;
                if (frame == 1)
                {
                    num4 += 38;
                }
                if (frame == 2)
                {
                    num4 += 76;
                }
            }
            drawData.addFrY = num4 - drawData.tileFrameY;
            if (num6 != 0)
            {
                drawData.tileHeight = 18;
            }
            if (drawData.typeCache == 21 && (num2 == 48 || num2 == 49))
            {
                drawData.glowSourceRect = new Rectangle(16 * (num % 2), drawData.tileFrameY + drawData.addFrY, drawData.tileWidth, drawData.tileHeight);
            }
        }
        if (drawData.typeCache != 378)
        {
            return;
        }
        Point key2 = default(Point);
        ((Point)(ref key2))._002Ector(tileX, tileY);
        if (drawData.tileFrameX % 36 != 0)
        {
            key2.X--;
        }
        if (drawData.tileFrameY % 54 != 0)
        {
            key2.Y -= drawData.tileFrameY / 18;
        }
        if (!_trainingDummyTileEntityPositions.ContainsKey(key2))
        {
            _trainingDummyTileEntityPositions[key2] = TETrainingDummy.Find(key2.X, key2.Y);
        }
        if (_trainingDummyTileEntityPositions[key2] != -1)
        {
            int npc = ((TETrainingDummy)TileEntity.ByID[_trainingDummyTileEntityPositions[key2]]).npc;
            if (npc != -1)
            {
                int num5 = Main.npc[npc].frame.Y / 55;
                num5 *= 54;
                num5 += drawData.tileFrameY;
                drawData.addFrY = num5 - drawData.tileFrameY;
            }
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._chestPositions, Terraria.GameContent.Drawing.TileDrawing._trainingDummyTileEntityPositions, Terraria.ID.TileID.Sets.BasicChest, Terraria.DataStructures.TileEntity.ByID, Terraria.Main.chest, Terraria.GameContent.Tile_Entities.TETrainingDummy.Find(), Terraria.Chest.FindChest(), and Terraria.Main.npc.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile().