TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile
DrawTile_LiquidBehindTile()
void Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile (bool solidLayer, bool inFrontOfPlayers, int waterStyleOverride, Vector2 screenPosition, Vector2 screenOffset, int tileX, int tileY, Tile tileCache) inline private
Definition at line 4499 of file TileDrawing.cs.
    {
        //IL_05cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05da: Unknown result type (might be due to invalid IL or missing references)
        //IL_05df: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0702: Unknown result type (might be due to invalid IL or missing references)
        //IL_0707: Unknown result type (might be due to invalid IL or missing references)
        //IL_0714: Unknown result type (might be due to invalid IL or missing references)
        //IL_071b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0720: Unknown result type (might be due to invalid IL or missing references)
        //IL_079d: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07db: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f4: Unknown result type (might be due to invalid IL or missing references)
        Tile tile = Main.tile[tileX + 1, tileY];
        Tile tile2 = Main.tile[tileX - 1, tileY];
        Tile tile3 = Main.tile[tileX, tileY - 1];
        Tile tile4 = Main.tile[tileX, tileY + 1];
        if (tile == null)
        {
            tile = (Main.tile[tileX + 1, tileY] = default(Tile));
        }
        if (tile2 == null)
        {
            tile2 = (Main.tile[tileX - 1, tileY] = default(Tile));
        }
        if (tile3 == null)
        {
            tile3 = (Main.tile[tileX, tileY - 1] = default(Tile));
        }
        if (tile4 == null)
        {
            tile4 = (Main.tile[tileX, tileY + 1] = default(Tile));
        }
        if (!tileCache.active() || tileCache.inActive() || _tileSolidTop[tileCache.type] || (tileCache.halfBrick() && (tile2.liquid > 160 || tile.liquid > 160) && Main.instance.waterfallManager.CheckForWaterfall(tileX, tileY)) || (TileID.Sets.BlocksWaterDrawingBehindSelf[tileCache.type] && tileCache.slope() == 0))
        {
            return;
        }
        int num = 0;
        bool flag = false;
        bool flag2 = false;
        bool flag3 = false;
        bool flag4 = false;
        bool flag5 = false;
        int num2 = 0;
        bool flag6 = false;
        int num3 = tileCache.slope();
        int num4 = tileCache.blockType();
        if (tileCache.type == 546 && tileCache.liquid > 0)
        {
            flag5 = true;
            flag4 = true;
            flag = true;
            flag2 = true;
            switch (tileCache.liquidType())
            {
            case 0:
                flag6 = true;
                break;
            case 1:
                num2 = 1;
                break;
            case 2:
                num2 = 11;
                break;
            case 3:
                num2 = 14;
                break;
            }
            num = tileCache.liquid;
        }
        else
        {
            if (tileCache.liquid > 0 && num4 != 0 && (num4 != 1 || tileCache.liquid > 160))
            {
                flag5 = true;
                switch (tileCache.liquidType())
                {
                case 0:
                    flag6 = true;
                    break;
                case 1:
                    num2 = 1;
                    break;
                case 2:
                    num2 = 11;
                    break;
                case 3:
                    num2 = 14;
                    break;
                }
                if (tileCache.liquid > num)
                {
                    num = tileCache.liquid;
                }
            }
            if (tile2.liquid > 0 && num3 != 1 && num3 != 3)
            {
                flag = true;
                switch (tile2.liquidType())
                {
                case 0:
                    flag6 = true;
                    break;
                case 1:
                    num2 = 1;
                    break;
                case 2:
                    num2 = 11;
                    break;
                case 3:
                    num2 = 14;
                    break;
                }
                if (tile2.liquid > num)
                {
                    num = tile2.liquid;
                }
            }
            if (tile.liquid > 0 && num3 != 2 && num3 != 4)
            {
                flag2 = true;
                switch (tile.liquidType())
                {
                case 0:
                    flag6 = true;
                    break;
                case 1:
                    num2 = 1;
                    break;
                case 2:
                    num2 = 11;
                    break;
                case 3:
                    num2 = 14;
                    break;
                }
                if (tile.liquid > num)
                {
                    num = tile.liquid;
                }
            }
            if (tile3.liquid > 0 && num3 != 3 && num3 != 4)
            {
                flag3 = true;
                switch (tile3.liquidType())
                {
                case 0:
                    flag6 = true;
                    break;
                case 1:
                    num2 = 1;
                    break;
                case 2:
                    num2 = 11;
                    break;
                case 3:
                    num2 = 14;
                    break;
                }
            }
            if (tile4.liquid > 0 && num3 != 1 && num3 != 2)
            {
                if (tile4.liquid > 240)
                {
                    flag4 = true;
                }
                switch (tile4.liquidType())
                {
                case 0:
                    flag6 = true;
                    break;
                case 1:
                    num2 = 1;
                    break;
                case 2:
                    num2 = 11;
                    break;
                case 3:
                    num2 = 14;
                    break;
                }
            }
        }
        if (!flag3 && !flag4 && !flag && !flag2 && !flag5)
        {
            return;
        }
        if (waterStyleOverride != -1)
        {
            Main.waterStyle = waterStyleOverride;
        }
        if (num2 == 0)
        {
            num2 = Main.waterStyle;
        }
        Lighting.GetCornerColors(tileX, tileY, out var vertices);
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)(tileX * 16), (float)(tileY * 16));
        Rectangle liquidSize = default(Rectangle);
        ((Rectangle)(ref liquidSize))._002Ector(0, 4, 16, 16);
        if (flag4 && (flag || flag2))
        {
            flag = true;
            flag2 = true;
        }
        if (tileCache.active() && (Main.tileSolidTop[tileCache.type] || !Main.tileSolid[tileCache.type]))
        {
            return;
        }
        if ((!flag3 || !(flag || flag2)) && !(flag4 && flag3))
        {
            if (flag3)
            {
                ((Rectangle)(ref liquidSize))._002Ector(0, 4, 16, 4);
                if (tileCache.halfBrick() || tileCache.slope() != 0)
                {
                    ((Rectangle)(ref liquidSize))._002Ector(0, 4, 16, 12);
                }
            }
            else if (flag4 && !flag && !flag2)
            {
                ((Vector2)(ref vector))._002Ector((float)(tileX * 16), (float)(tileY * 16 + 12));
                ((Rectangle)(ref liquidSize))._002Ector(0, 4, 16, 4);
            }
            else
            {
                float num8 = (float)(256 - num) / 32f;
                int y = 4;
                if (tile3.liquid == 0 && (num4 != 0 || !WorldGen.SolidTile(tileX, tileY - 1)))
                {
                    y = 0;
                }
                int num5 = (int)num8 * 2;
                if (tileCache.slope() != 0)
                {
                    ((Vector2)(ref vector))._002Ector((float)(tileX * 16), (float)(tileY * 16 + num5));
                    ((Rectangle)(ref liquidSize))._002Ector(0, num5, 16, 16 - num5);
                }
                else if ((flag && flag2) || tileCache.halfBrick())
                {
                    ((Vector2)(ref vector))._002Ector((float)(tileX * 16), (float)(tileY * 16 + num5));
                    ((Rectangle)(ref liquidSize))._002Ector(0, y, 16, 16 - num5);
                }
                else if (flag)
                {
                    ((Vector2)(ref vector))._002Ector((float)(tileX * 16), (float)(tileY * 16 + num5));
                    ((Rectangle)(ref liquidSize))._002Ector(0, y, 4, 16 - num5);
                }
                else
                {
                    ((Vector2)(ref vector))._002Ector((float)(tileX * 16 + 12), (float)(tileY * 16 + num5));
                    ((Rectangle)(ref liquidSize))._002Ector(0, y, 4, 16 - num5);
                }
            }
        }
        Vector2 position = vector - screenPosition + screenOffset;
        float num6 = 0.5f;
        switch (num2)
        {
        case 1:
            num6 = 1f;
            break;
        case 11:
            num6 = Math.Max(num6 * 1.7f, 1f);
            break;
        }
        if ((double)tileY <= Main.worldSurface || num6 > 1f)
        {
            num6 = 1f;
            if (tileCache.wall == 21)
            {
                num6 = 0.9f;
            }
            else if (tileCache.wall > 0)
            {
                num6 = 0.6f;
            }
        }
        if (tileCache.halfBrick() && tile3.liquid > 0 && tileCache.wall > 0)
        {
            num6 = 0f;
        }
        if (num3 == 4 && tile2.liquid == 0 && !WorldGen.SolidTile(tileX - 1, tileY))
        {
            num6 = 0f;
        }
        if (num3 == 3 && tile.liquid == 0 && !WorldGen.SolidTile(tileX + 1, tileY))
        {
            num6 = 0f;
        }
        ref Color bottomLeftColor = ref vertices.BottomLeftColor;
        bottomLeftColor *= num6;
        ref Color bottomRightColor = ref vertices.BottomRightColor;
        bottomRightColor *= num6;
        ref Color topLeftColor = ref vertices.TopLeftColor;
        topLeftColor *= num6;
        ref Color topRightColor = ref vertices.TopRightColor;
        topRightColor *= num6;
        bool flag7 = false;
        if (flag6)
        {
            for (int i = 0; i < LoaderManager.Get<WaterStylesLoader>().TotalCount; i++)
            {
                if (Main.IsLiquidStyleWater(i) && Main.liquidAlpha[i] > 0f && i != num2)
                {
                    DrawPartialLiquid(!solidLayer, tileCache, ref position, ref liquidSize, i, ref vertices);
                    flag7 = true;
                    break;
                }
            }
        }
        VertexColors colors = vertices;
        float num7 = (flag7 ? Main.liquidAlpha[num2] : 1f);
        ref Color bottomLeftColor2 = ref colors.BottomLeftColor;
        bottomLeftColor2 *= num7;
        ref Color bottomRightColor2 = ref colors.BottomRightColor;
        bottomRightColor2 *= num7;
        ref Color topLeftColor2 = ref colors.TopLeftColor;
        topLeftColor2 *= num7;
        ref Color topRightColor2 = ref colors.TopRightColor;
        topRightColor2 *= num7;
        if (num2 == 14)
        {
            LiquidRenderer.SetShimmerVertexColors(ref colors, solidLayer ? 0.75f : 1f, tileX, tileY);
        }
        DrawPartialLiquid(!solidLayer, tileCache, ref position, ref liquidSize, num2, ref colors);
    }
References Terraria.GameContent.Drawing.TileDrawing._tileSolidTop, Terraria.Tile.active(), Terraria.ID.TileID.Sets.BlocksWaterDrawingBehindSelf, Terraria.Tile.blockType(), Terraria.GameContent.Drawing.TileDrawing.DrawPartialLiquid(), Terraria.Lighting.GetCornerColors(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.Main.instance, Terraria.Main.IsLiquidStyleWater(), Terraria.Tile.liquid, Terraria.Main.liquidAlpha, Terraria.Tile.liquidType(), Terraria.GameContent.Liquid.LiquidRenderer.SetShimmerVertexColors(), Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.waterStyle.
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw(), and Terraria.GameContent.Drawing.TileDrawing.DrawLiquidBehindTiles().