TModLoader: Terraria.GameContent.Drawing.TileDrawing.IsTileDangerous
IsTileDangerous() [1/2]
static bool Terraria.GameContent.Drawing.TileDrawing.IsTileDangerous (int tileX, int tileY, Player localPlayer, Tile tileCache, ushort typeCache) inline static package
    {
        bool flag = typeCache == 135 || typeCache == 137 || TileID.Sets.Boulders[typeCache] || typeCache == 141 || typeCache == 210 || typeCache == 442 || typeCache == 443 || typeCache == 444 || typeCache == 411 || typeCache == 485 || typeCache == 85 || typeCache == 654 || (typeCache == 314 && Minecart.IsPressurePlate(tileCache));
        flag |= Main.getGoodWorld && typeCache == 230;
        flag |= Main.dontStarveWorld && typeCache == 80;
        if (tileCache.slope() == 0 && !tileCache.inActive())
        {
            flag = flag || typeCache == 32 || typeCache == 69 || typeCache == 48 || typeCache == 232 || typeCache == 352 || typeCache == 483 || typeCache == 482 || typeCache == 481 || typeCache == 51 || typeCache == 229;
            if (!localPlayer.fireWalk)
            {
                flag = flag || typeCache == 37 || typeCache == 58 || typeCache == 76;
            }
            if (!localPlayer.iceSkate)
            {
                flag = flag || typeCache == 162;
            }
        }
        return TileLoader.IsTileDangerous(tileX, tileY, typeCache, localPlayer) ?? flag;
    }
References Terraria.ID.TileID.Sets.Boulders, Terraria.Tile.inActive(), Terraria.Minecart.IsPressurePlate(), Terraria.ModLoader.TileLoader.IsTileDangerous(), and Terraria.Tile.slope().
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawAnimatedTile_AdjustForVisionChangers(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), and Terraria.GameContent.Drawing.TileDrawing.IsTileDangerous().