TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawGrass
DrawGrass()
void Terraria.GameContent.Drawing.TileDrawing.DrawGrass () inline private
    {
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_0228: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_024a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0254: Unknown result type (might be due to invalid IL or missing references)
        //IL_026b: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_028c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0296: Unknown result type (might be due to invalid IL or missing references)
        Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
        Vector2 zero = Vector2.Zero;
        int num = 3;
        int num2 = _specialsCount[num];
        for (int i = 0; i < num2; i++)
        {
            Point val = _specialPositions[num][i];
            int x = val.X;
            int y = val.Y;
            Tile tile = Main.tile[x, y];
            if (tile == null || !tile.active() || !IsVisible(tile))
            {
                continue;
            }
            ushort type = tile.type;
            short tileFrameX = tile.frameX;
            short tileFrameY = tile.frameY;
            GetTileDrawData(x, y, tile, type, ref tileFrameX, ref tileFrameY, out var tileWidth, out var tileHeight, out var tileTop, out var halfBrickHeight, out var addFrX, out var addFrY, out var tileSpriteEffect, out var glowTexture, out var glowSourceRect, out var glowColor);
            bool flag = _rand.Next(4) == 0;
            Color tileLight = Lighting.GetColor(x, y);
            DrawAnimatedTile_AdjustForVisionChangers(x, y, tile, type, tileFrameX, tileFrameY, ref tileLight, flag);
            tileLight = DrawTiles_GetLightOverride(y, x, tile, type, tileFrameX, tileFrameY, tileLight);
            if (_isActiveAndNotPaused && flag)
            {
                DrawTiles_EmitParticles(y, x, tile, type, tileFrameX, tileFrameY, tileLight);
            }
            if (type == 83 && IsAlchemyPlantHarvestable(tileFrameX / 18))
            {
                type = 84;
                Main.instance.LoadTiles(type);
            }
            Vector2 position = new Vector2((float)(x * 16 - (int)unscaledPosition.X + 8), (float)(y * 16 - (int)unscaledPosition.Y + 16)) + zero;
            _ = _grassWindCounter;
            float num3 = GetWindCycle(x, y, _grassWindCounter);
            if (!WallID.Sets.AllowsWind[tile.wall])
            {
                num3 = 0f;
            }
            if (!InAPlaceWithWind(x, y, 1, 1))
            {
                num3 = 0f;
            }
            num3 += GetWindGridPush(x, y, 20, 0.35f);
            position.X += num3 * 1f;
            position.Y += Math.Abs(num3) * 1f;
            Texture2D tileDrawTexture = GetTileDrawTexture(tile, x, y);
            if (tileDrawTexture != null)
            {
                Main.spriteBatch.Draw(tileDrawTexture, position, (Rectangle?)new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight), tileLight, num3 * 0.1f, new Vector2((float)(tileWidth / 2), (float)(16 - halfBrickHeight - tileTop)), 1f, tileSpriteEffect, 0f);
                if (glowTexture != null)
                {
                    Main.spriteBatch.Draw(glowTexture, position, (Rectangle?)glowSourceRect, glowColor, num3 * 0.1f, new Vector2((float)(tileWidth / 2), (float)(16 - halfBrickHeight - tileTop)), 1f, tileSpriteEffect, 0f);
                }
            }
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._grassWindCounter, Terraria.GameContent.Drawing.TileDrawing._isActiveAndNotPaused, Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.GameContent.Drawing.TileDrawing._specialPositions, Terraria.GameContent.Drawing.TileDrawing._specialsCount, Terraria.Tile.active(), Terraria.ID.WallID.Sets.AllowsWind, Terraria.Main.Camera, Terraria.GameContent.Drawing.TileDrawing.DrawAnimatedTile_AdjustForVisionChangers(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_GetLightOverride(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Lighting.GetColor(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.GameContent.Drawing.TileDrawing.GetWindCycle(), Terraria.GameContent.Drawing.TileDrawing.GetWindGridPush(), Terraria.GameContent.Drawing.TileDrawing.InAPlaceWithWind(), Terraria.Main.instance, Terraria.GameContent.Drawing.TileDrawing.IsAlchemyPlantHarvestable(), Terraria.GameContent.Drawing.TileDrawing.IsVisible(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles().