TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawTrees
DrawTrees()
void Terraria.GameContent.Drawing.TileDrawing.DrawTrees () inline private
Definition at line 9297 of file TileDrawing.cs.
    {
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0282: Unknown result type (might be due to invalid IL or missing references)
        //IL_0292: Unknown result type (might be due to invalid IL or missing references)
        //IL_029e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04da: Unknown result type (might be due to invalid IL or missing references)
        //IL_04df: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0962: Unknown result type (might be due to invalid IL or missing references)
        //IL_097b: Unknown result type (might be due to invalid IL or missing references)
        //IL_098a: Unknown result type (might be due to invalid IL or missing references)
        //IL_098f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0990: Unknown result type (might be due to invalid IL or missing references)
        //IL_0995: Unknown result type (might be due to invalid IL or missing references)
        //IL_0318: Unknown result type (might be due to invalid IL or missing references)
        //IL_0326: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_030f: Unknown result type (might be due to invalid IL or missing references)
        //IL_046c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0471: Unknown result type (might be due to invalid IL or missing references)
        //IL_0729: Unknown result type (might be due to invalid IL or missing references)
        //IL_072e: Unknown result type (might be due to invalid IL or missing references)
        //IL_072f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0734: Unknown result type (might be due to invalid IL or missing references)
        //IL_0739: Unknown result type (might be due to invalid IL or missing references)
        //IL_073a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0749: Unknown result type (might be due to invalid IL or missing references)
        //IL_074e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0753: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0372: Unknown result type (might be due to invalid IL or missing references)
        //IL_0377: Unknown result type (might be due to invalid IL or missing references)
        //IL_0380: Unknown result type (might be due to invalid IL or missing references)
        //IL_038e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0398: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_054f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0554: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a29: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_056d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0579: Unknown result type (might be due to invalid IL or missing references)
        //IL_0583: Unknown result type (might be due to invalid IL or missing references)
        //IL_0594: Unknown result type (might be due to invalid IL or missing references)
        //IL_055f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0564: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_081a: Unknown result type (might be due to invalid IL or missing references)
        //IL_081f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0828: Unknown result type (might be due to invalid IL or missing references)
        //IL_0835: Unknown result type (might be due to invalid IL or missing references)
        //IL_083f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0850: Unknown result type (might be due to invalid IL or missing references)
        Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
        Vector2 zero = Vector2.Zero;
        int num = 0;
        int num12 = _specialsCount[num];
        float num15 = 0.08f;
        float num16 = 0.06f;
        for (int i = 0; i < num12; i++)
        {
            Point val = _specialPositions[num][i];
            int x = val.X;
            int y = val.Y;
            Tile tile = Main.tile[x, y];
            if (tile == null || !tile.active())
            {
                continue;
            }
            ushort type = tile.type;
            short frameX = tile.frameX;
            short frameY = tile.frameY;
            bool flag = tile.wall > 0;
            WorldGen.GetTreeFoliageDataMethod getTreeFoliageDataMethod = null;
            try
            {
                bool flag2 = false;
                switch (type)
                {
                case 5:
                    flag2 = true;
                    getTreeFoliageDataMethod = WorldGen.GetCommonTreeFoliageData;
                    break;
                case 583:
                case 584:
                case 585:
                case 586:
                case 587:
                case 588:
                case 589:
                    flag2 = true;
                    getTreeFoliageDataMethod = WorldGen.GetGemTreeFoliageData;
                    break;
                case 596:
                case 616:
                    flag2 = true;
                    getTreeFoliageDataMethod = WorldGen.GetVanityTreeFoliageData;
                    break;
                case 634:
                    flag2 = true;
                    getTreeFoliageDataMethod = WorldGen.GetAshTreeFoliageData;
                    break;
                }
                if (flag2 && frameY >= 198 && frameX >= 22)
                {
                    int treeFrame = WorldGen.GetTreeFrame(tile);
                    int topTextureFrameWidth4;
                    int topTextureFrameHeight4;
                    switch (frameX)
                    {
                    case 22:
                    {
                        int treeStyle3 = 0;
                        int topTextureFrameWidth3 = 80;
                        int topTextureFrameHeight3 = 80;
                        int num5 = 0;
                        int grassPosX = x + num5;
                        int floorY3 = y;
                        if (!getTreeFoliageDataMethod(x, y, num5, ref treeFrame, ref treeStyle3, out floorY3, out topTextureFrameWidth3, out topTextureFrameHeight3))
{
                            continue;
                        }
                        EmitTreeLeaves(x, y, grassPosX, floorY3);
                        if (treeStyle3 == 14)
{
                            float num6 = (float)_rand.Next(28, 42) * 0.005f;
                            num6 += (float)(270 - Main.mouseTextColor) / 1000f;
                            if (tile.color() == 0)
{
                                Lighting.AddLight(x, y, 0.1f, 0.2f + num6 / 2f, 0.7f + num6);
                            }
                            else
{
                                Color color5 = WorldGen.paintColor(tile.color());
                                float r3 = (float)(int)((Color)(ref color5)).R / 255f;
                                float g3 = (float)(int)((Color)(ref color5)).G / 255f;
                                float b3 = (float)(int)((Color)(ref color5)).B / 255f;
                                Lighting.AddLight(x, y, r3, g3, b3);
                            }
                        }
                        byte tileColor3 = tile.color();
                        Texture2D treeTopTexture = GetTreeTopTexture(treeStyle3, 0, tileColor3);
                        Vector2 vector = (vector = new Vector2((float)(x * 16 - (int)unscaledPosition.X + 8), (float)(y * 16 - (int)unscaledPosition.Y + 16)) + zero);
                        float num7 = 0f;
                        if (!flag)
{
                            num7 = GetWindCycle(x, y, _treeWindCounter);
                        }
                        vector.X += num7 * 2f;
                        vector.Y += Math.Abs(num7) * 2f;
                        Color color6 = Lighting.GetColor(x, y);
                        if (tile.fullbrightBlock())
{
                            color6 = Color.White;
                        }
                        Main.spriteBatch.Draw(treeTopTexture, vector, (Rectangle?)new Rectangle(treeFrame * (topTextureFrameWidth3 + 2), 0, topTextureFrameWidth3, topTextureFrameHeight3), color6, num7 * num15, new Vector2((float)(topTextureFrameWidth3 / 2), (float)topTextureFrameHeight3), 1f, (SpriteEffects)0, 0f);
                        if (type == 634)
{
                            Texture2D value3 = TextureAssets.GlowMask[316].Value;
                            Color white3 = Color.White;
                            Main.spriteBatch.Draw(value3, vector, (Rectangle?)new Rectangle(treeFrame * (topTextureFrameWidth3 + 2), 0, topTextureFrameWidth3, topTextureFrameHeight3), white3, num7 * num15, new Vector2((float)(topTextureFrameWidth3 / 2), (float)topTextureFrameHeight3), 1f, (SpriteEffects)0, 0f);
                        }
                        break;
                    }
                    case 44:
                    {
                        int treeStyle2 = 0;
                        int num21 = x;
                        int floorY2 = y;
                        int num2 = 1;
                        if (!getTreeFoliageDataMethod(x, y, num2, ref treeFrame, ref treeStyle2, out floorY2, out topTextureFrameWidth4, out topTextureFrameHeight4))
{
                            continue;
                        }
                        EmitTreeLeaves(x, y, num21 + num2, floorY2);
                        if (treeStyle2 == 14)
{
                            float num3 = (float)_rand.Next(28, 42) * 0.005f;
                            num3 += (float)(270 - Main.mouseTextColor) / 1000f;
                            if (tile.color() == 0)
{
                                Lighting.AddLight(x, y, 0.1f, 0.2f + num3 / 2f, 0.7f + num3);
                            }
                            else
{
                                Color color3 = WorldGen.paintColor(tile.color());
                                float r2 = (float)(int)((Color)(ref color3)).R / 255f;
                                float g2 = (float)(int)((Color)(ref color3)).G / 255f;
                                float b2 = (float)(int)((Color)(ref color3)).B / 255f;
                                Lighting.AddLight(x, y, r2, g2, b2);
                            }
                        }
                        byte tileColor2 = tile.color();
                        Texture2D treeBranchTexture2 = GetTreeBranchTexture(treeStyle2, 0, tileColor2);
                        Vector2 position2 = new Vector2((float)(x * 16), (float)(y * 16)) - unscaledPosition.Floor() + zero + new Vector2(16f, 12f);
                        float num4 = 0f;
                        if (!flag)
{
                            num4 = GetWindCycle(x, y, _treeWindCounter);
                        }
                        if (num4 > 0f)
{
                            position2.X += num4;
                        }
                        position2.X += Math.Abs(num4) * 2f;
                        Color color4 = Lighting.GetColor(x, y);
                        if (tile.fullbrightBlock())
{
                            color4 = Color.White;
                        }
                        Main.spriteBatch.Draw(treeBranchTexture2, position2, (Rectangle?)new Rectangle(0, treeFrame * 42, 40, 40), color4, num4 * num16, new Vector2(40f, 24f), 1f, (SpriteEffects)0, 0f);
                        if (type == 634)
{
                            Texture2D value2 = TextureAssets.GlowMask[317].Value;
                            Color white2 = Color.White;
                            Main.spriteBatch.Draw(value2, position2, (Rectangle?)new Rectangle(0, treeFrame * 42, 40, 40), white2, num4 * num16, new Vector2(40f, 24f), 1f, (SpriteEffects)0, 0f);
                        }
                        break;
                    }
                    case 66:
                    {
                        int treeStyle = 0;
                        int num17 = x;
                        int floorY = y;
                        int num18 = -1;
                        if (!getTreeFoliageDataMethod(x, y, num18, ref treeFrame, ref treeStyle, out floorY, out topTextureFrameHeight4, out topTextureFrameWidth4))
{
                            continue;
                        }
                        EmitTreeLeaves(x, y, num17 + num18, floorY);
                        if (treeStyle == 14)
{
                            float num19 = (float)_rand.Next(28, 42) * 0.005f;
                            num19 += (float)(270 - Main.mouseTextColor) / 1000f;
                            if (tile.color() == 0)
{
                                Lighting.AddLight(x, y, 0.1f, 0.2f + num19 / 2f, 0.7f + num19);
                            }
                            else
{
                                Color color = WorldGen.paintColor(tile.color());
                                float r = (float)(int)((Color)(ref color)).R / 255f;
                                float g = (float)(int)((Color)(ref color)).G / 255f;
                                float b = (float)(int)((Color)(ref color)).B / 255f;
                                Lighting.AddLight(x, y, r, g, b);
                            }
                        }
                        byte tileColor = tile.color();
                        Texture2D treeBranchTexture = GetTreeBranchTexture(treeStyle, 0, tileColor);
                        Vector2 position = new Vector2((float)(x * 16), (float)(y * 16)) - unscaledPosition.Floor() + zero + new Vector2(0f, 18f);
                        float num20 = 0f;
                        if (!flag)
{
                            num20 = GetWindCycle(x, y, _treeWindCounter);
                        }
                        if (num20 < 0f)
{
                            position.X += num20;
                        }
                        position.X -= Math.Abs(num20) * 2f;
                        Color color2 = Lighting.GetColor(x, y);
                        if (tile.fullbrightBlock())
{
                            color2 = Color.White;
                        }
                        Main.spriteBatch.Draw(treeBranchTexture, position, (Rectangle?)new Rectangle(42, treeFrame * 42, 40, 40), color2, num20 * num16, new Vector2(0f, 30f), 1f, (SpriteEffects)0, 0f);
                        if (type == 634)
{
                            Texture2D value = TextureAssets.GlowMask[317].Value;
                            Color white = Color.White;
                            Main.spriteBatch.Draw(value, position, (Rectangle?)new Rectangle(42, treeFrame * 42, 40, 40), white, num20 * num16, new Vector2(0f, 30f), 1f, (SpriteEffects)0, 0f);
                        }
                        break;
                    }
                    }
                }
                if (type != 323 || frameX < 88 || frameX > 132)
                {
                    continue;
                }
                int num8 = 0;
                switch (frameX)
                {
                case 110:
                    num8 = 1;
                    break;
                case 132:
                    num8 = 2;
                    break;
                }
                int treeTextureIndex = 15;
                int num9 = 80;
                int num10 = 80;
                int num11 = 32;
                int num13 = 0;
                int palmTreeBiome = GetPalmTreeBiome(x, y);
                int y2 = palmTreeBiome * 82;
                if (palmTreeBiome >= 4 && palmTreeBiome <= 7)
                {
                    treeTextureIndex = 21;
                    num9 = 114;
                    num10 = 98;
                    y2 = (palmTreeBiome - 4) * 98;
                    num11 = 48;
                    num13 = 2;
                }
                if (Math.Abs(palmTreeBiome) >= 8)
                {
                    y2 = 0;
                    if (palmTreeBiome < 0)
                    {
                        num9 = 114;
                        num10 = 98;
                        num11 = 48;
                        num13 = 2;
                    }
                    treeTextureIndex = Math.Abs(palmTreeBiome) - 8;
                    treeTextureIndex *= -2;
                    if (palmTreeBiome < 0)
                    {
                        treeTextureIndex--;
                    }
                }
                int frameY2 = Main.tile[x, y].frameY;
                byte tileColor4 = tile.color();
                Texture2D treeTopTexture2 = GetTreeTopTexture(treeTextureIndex, palmTreeBiome, tileColor4);
                Vector2 position3 = new Vector2((float)(x * 16 - (int)unscaledPosition.X - num11 + frameY2 + num9 / 2), (float)(y * 16 - (int)unscaledPosition.Y + 16 + num13)) + zero;
                float num14 = 0f;
                if (!flag)
                {
                    num14 = GetWindCycle(x, y, _treeWindCounter);
                }
                position3.X += num14 * 2f;
                position3.Y += Math.Abs(num14) * 2f;
                Color color7 = Lighting.GetColor(x, y);
                if (tile.fullbrightBlock())
                {
                    color7 = Color.White;
                }
                Main.spriteBatch.Draw(treeTopTexture2, position3, (Rectangle?)new Rectangle(num8 * (num9 + 2), y2, num9, num10), color7, num14 * num15, new Vector2((float)(num9 / 2), (float)num10), 1f, (SpriteEffects)0, 0f);
            }
            catch
            {
            }
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.GameContent.Drawing.TileDrawing._specialPositions, Terraria.GameContent.Drawing.TileDrawing._specialsCount, Terraria.GameContent.Drawing.TileDrawing._treeWindCounter, Terraria.Tile.active(), Terraria.Lighting.AddLight(), Terraria.Main.Camera, Terraria.Tile.color(), Terraria.GameContent.Drawing.TileDrawing.EmitTreeLeaves(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.fullbrightBlock(), Terraria.WorldGen.GetAshTreeFoliageData(), Terraria.Lighting.GetColor(), Terraria.WorldGen.GetCommonTreeFoliageData(), Terraria.WorldGen.GetGemTreeFoliageData(), Terraria.GameContent.Drawing.TileDrawing.GetPalmTreeBiome(), Terraria.GameContent.Drawing.TileDrawing.GetTreeBranchTexture(), Terraria.WorldGen.GetTreeFrame(), Terraria.GameContent.Drawing.TileDrawing.GetTreeTopTexture(), Terraria.WorldGen.GetVanityTreeFoliageData(), Terraria.GameContent.Drawing.TileDrawing.GetWindCycle(), Terraria.GameContent.TextureAssets.GlowMask, Terraria.Main.mouseTextColor, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.paintColor(), Terraria.Main.spriteBatch, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles().