TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind
DrawMultiTileGrassInWind()
void Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind (Vector2 screenPosition, Vector2 offSet, int topLeftX, int topLeftY, int sizeX, int sizeY) inline private
    {
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0237: Unknown result type (might be due to invalid IL or missing references)
        //IL_023c: Unknown result type (might be due to invalid IL or missing references)
        //IL_023d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0242: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_031a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0322: Unknown result type (might be due to invalid IL or missing references)
        //IL_0329: Unknown result type (might be due to invalid IL or missing references)
        //IL_0340: Unknown result type (might be due to invalid IL or missing references)
        //IL_0346: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0352: Unknown result type (might be due to invalid IL or missing references)
        //IL_0368: Unknown result type (might be due to invalid IL or missing references)
        //IL_0372: Unknown result type (might be due to invalid IL or missing references)
        //IL_037a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0381: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0269: Unknown result type (might be due to invalid IL or missing references)
        //IL_026c: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        float windCycle = GetWindCycle(topLeftX, topLeftY, _sunflowerWindCounter);
        new Vector2((float)(sizeX * 16) * 0.5f, (float)(sizeY * 16));
        Vector2 vector = new Vector2((float)(topLeftX * 16 - (int)screenPosition.X) + (float)sizeX * 16f * 0.5f, (float)(topLeftY * 16 - (int)screenPosition.Y + 16 * sizeY)) + offSet;
        float num = 0.07f;
        int type = Main.tile[topLeftX, topLeftY].type;
        Texture2D texture2D = null;
        Color color = Color.Transparent;
        bool flag = InAPlaceWithWind(topLeftX, topLeftY, sizeX, sizeY);
        switch (type)
        {
        case 27:
            texture2D = TextureAssets.Flames[14].Value;
            color = Color.White;
            break;
        case 519:
            flag = InAPlaceWithWind(topLeftX, topLeftY, sizeX, 1);
            break;
        default:
            num = 0.15f;
            break;
        case 521:
        case 522:
        case 523:
        case 524:
        case 525:
        case 526:
        case 527:
            num = 0f;
            flag = false;
            break;
        }
        Vector2 vector3 = default(Vector2);
        for (int i = topLeftX; i < topLeftX + sizeX; i++)
        {
            for (int j = topLeftY; j < topLeftY + sizeY; j++)
            {
                Tile tile = Main.tile[i, j];
                ushort type2 = tile.type;
                if (type2 != type || !IsVisible(tile))
                {
                    continue;
                }
                Math.Abs(((float)(i - topLeftX) + 0.5f) / (float)sizeX - 0.5f);
                short tileFrameX = tile.frameX;
                short tileFrameY = tile.frameY;
                float num2 = 1f - (float)(j - topLeftY + 1) / (float)sizeY;
                if (num2 == 0f)
                {
                    num2 = 0.1f;
                }
                if (!flag)
                {
                    num2 = 0f;
                }
                GetTileDrawData(i, j, tile, type2, ref tileFrameX, ref tileFrameY, out var tileWidth, out var tileHeight, out var tileTop, out var halfBrickHeight, out var addFrX, out var addFrY, out var tileSpriteEffect, out var _, out var _, out var _);
                bool flag2 = _rand.Next(4) == 0;
                Color tileLight = Lighting.GetColor(i, j);
                DrawAnimatedTile_AdjustForVisionChangers(i, j, tile, type2, tileFrameX, tileFrameY, ref tileLight, flag2);
                tileLight = DrawTiles_GetLightOverride(j, i, tile, type2, tileFrameX, tileFrameY, tileLight);
                if (_isActiveAndNotPaused && flag2)
                {
                    DrawTiles_EmitParticles(j, i, tile, type2, tileFrameX, tileFrameY, tileLight);
                }
                Vector2 vector2 = new Vector2((float)(i * 16 - (int)screenPosition.X), (float)(j * 16 - (int)screenPosition.Y + tileTop)) + offSet;
                if (tile.type == 493 && tile.frameY == 0)
                {
                    if (Main.WindForVisuals >= 0f)
                    {
                        tileSpriteEffect = (SpriteEffects)(tileSpriteEffect ^ 1);
                    }
                    if (!((Enum)tileSpriteEffect).HasFlag((Enum)(object)(SpriteEffects)1))
                    {
                        vector2.X -= 6f;
                    }
                    else
                    {
                        vector2.X += 6f;
                    }
                }
                ((Vector2)(ref vector3))._002Ector(windCycle * 1f, Math.Abs(windCycle) * 2f * num2);
                Vector2 origin = vector - vector2;
                Texture2D tileDrawTexture = GetTileDrawTexture(tile, i, j);
                if (tileDrawTexture != null)
                {
                    Main.spriteBatch.Draw(tileDrawTexture, vector + new Vector2(0f, vector3.Y), (Rectangle?)new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight), tileLight, windCycle * num * num2, origin, 1f, tileSpriteEffect, 0f);
                    if (texture2D != null)
                    {
                        Main.spriteBatch.Draw(texture2D, vector + new Vector2(0f, vector3.Y), (Rectangle?)new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight), color, windCycle * num * num2, origin, 1f, tileSpriteEffect, 0f);
                    }
                }
            }
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._isActiveAndNotPaused, Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.GameContent.Drawing.TileDrawing._sunflowerWindCounter, Terraria.GameContent.Drawing.TileDrawing.DrawAnimatedTile_AdjustForVisionChangers(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_GetLightOverride(), Terraria.GameContent.TextureAssets.Flames, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Lighting.GetColor(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.GameContent.Drawing.TileDrawing.GetWindCycle(), Terraria.GameContent.Drawing.TileDrawing.InAPlaceWithWind(), Terraria.GameContent.Drawing.TileDrawing.IsVisible(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Main.WindForVisuals.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrass().