TModLoader: Terraria.GameContent.Drawing.TileDrawing.PreparePaintForTilesOnScreen
PreparePaintForTilesOnScreen()
void Terraria.GameContent.Drawing.TileDrawing.PreparePaintForTilesOnScreen () inline
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        if (Main.GameUpdateCount % 6 == 0)
        {
            Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector((float)Main.offScreenRange, (float)Main.offScreenRange);
            if (Main.drawToScreen)
            {
                vector = Vector2.Zero;
            }
            GetScreenDrawArea(unscaledPosition, vector + (Main.Camera.UnscaledPosition - Main.Camera.ScaledPosition), out var firstTileX, out var lastTileX, out var firstTileY, out var lastTileY);
            PrepareForAreaDrawing(firstTileX, lastTileX, firstTileY, lastTileY, prepareLazily: true);
        }
    }
References Terraria.Main.Camera, Terraria.Main.drawToScreen, Terraria.Main.GameUpdateCount, Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea(), Terraria.Main.offScreenRange, Terraria.GameContent.Drawing.TileDrawing.PrepareForAreaDrawing(), Terraria.Graphics.Camera.ScaledPosition, and Terraria.Graphics.Camera.UnscaledPosition.
Referenced by Terraria.Main.DoDraw().