TModLoader: Terraria.GameContent.Drawing.TileDrawing.EmitLiquidDrops
EmitLiquidDrops()
void Terraria.GameContent.Drawing.TileDrawing.EmitLiquidDrops (int j, int i, Tile tileCache, ushort typeCache) inline private
Definition at line 8559 of file TileDrawing.cs.
    {
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0273: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        //IL_0290: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_029f: Unknown result type (might be due to invalid IL or missing references)
        int num = 60;
        switch (typeCache)
        {
        case 374:
            num = 120;
            break;
        case 375:
            num = 180;
            break;
        case 461:
            num = 180;
            break;
        }
        if (tileCache.liquid != 0 || _rand.Next(num * 2) != 0)
        {
            return;
        }
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector(i * 16, j * 16, 16, 16);
        rectangle.X -= 34;
        rectangle.Width += 68;
        rectangle.Y -= 100;
        rectangle.Height = 400;
        Rectangle value = default(Rectangle);
        for (int k = 0; k < 600; k++)
        {
            if (_gore[k].active && ((_gore[k].type >= 706 && _gore[k].type <= 717) || _gore[k].type == 943 || _gore[k].type == 1147 || (_gore[k].type >= 1160 && _gore[k].type <= 1162)))
            {
                ((Rectangle)(ref value))._002Ector((int)_gore[k].position.X, (int)_gore[k].position.Y, 16, 16);
                if (((Rectangle)(ref rectangle)).Intersects(value))
                {
                    return;
                }
            }
        }
        Vector2 position = new Vector2((float)(i * 16), (float)(j * 16));
        int type = 706;
        if (Main.waterStyle == 14)
        {
            type = 706;
        }
        else if (Main.waterStyle == 13)
        {
            type = 706;
        }
        else if (Main.waterStyle == 12)
        {
            type = 1147;
        }
        else if (Main.waterStyle >= 15)
        {
            type = LoaderManager.Get<WaterStylesLoader>().Get(Main.waterStyle).GetDropletGore();
        }
        else if (Main.waterStyle > 1)
        {
            type = 706 + Main.waterStyle - 1;
        }
        if (typeCache == 374)
        {
            type = 716;
        }
        if (typeCache == 375)
        {
            type = 717;
        }
        if (typeCache == 461)
        {
            type = 943;
            if (Main.player[Main.myPlayer].ZoneCorrupt)
            {
                type = 1160;
            }
            if (Main.player[Main.myPlayer].ZoneCrimson)
            {
                type = 1161;
            }
            if (Main.player[Main.myPlayer].ZoneHallow)
            {
                type = 1162;
            }
        }
        int num2 = Gore.NewGore(position, default(Vector2), type);
        Gore obj = _gore[num2];
        obj.velocity *= 0f;
    }
References Terraria.GameContent.Drawing.TileDrawing._gore, Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.Tile.liquid, Terraria.Main.myPlayer, Terraria.Gore.NewGore(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Gore.position, Terraria.Gore.type, Terraria.Main.waterStyle, Terraria.Player.ZoneCorrupt, Terraria.Player.ZoneCrimson, and Terraria.Player.ZoneHallow.
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw().