TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawAnimatedTile_AdjustForVisionChangers
DrawAnimatedTile_AdjustForVisionChangers()
void Terraria.GameContent.Drawing.TileDrawing.DrawAnimatedTile_AdjustForVisionChangers (int i, int j, Tile tileCache, ushort typeCache, short tileFrameX, short tileFrameY, ref Color tileLight, bool canDoDust) inline private
Definition at line 9931 of file TileDrawing.cs.
    {
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_0208: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_029b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0308: Unknown result type (might be due to invalid IL or missing references)
        //IL_030d: Unknown result type (might be due to invalid IL or missing references)
        if (_localPlayer.dangerSense && IsTileDangerous(i, j, _localPlayer, tileCache, typeCache))
        {
            if (((Color)(ref tileLight)).R < byte.MaxValue)
            {
                ((Color)(ref tileLight)).R = byte.MaxValue;
            }
            if (((Color)(ref tileLight)).G < 50)
            {
                ((Color)(ref tileLight)).G = 50;
            }
            if (((Color)(ref tileLight)).B < 50)
            {
                ((Color)(ref tileLight)).B = 50;
            }
            if (_isActiveAndNotPaused && canDoDust && _rand.Next(30) == 0)
            {
                int num = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 60, 0f, 0f, 100, default(Color), 0.3f);
                _dust[num].fadeIn = 1f;
                Dust obj = _dust[num];
                obj.velocity *= 0.1f;
                _dust[num].noLight = true;
                _dust[num].noGravity = true;
            }
        }
        if (_localPlayer.findTreasure && Main.IsTileSpelunkable(i, j, typeCache, tileFrameX, tileFrameY))
        {
            if (((Color)(ref tileLight)).R < 200)
            {
                ((Color)(ref tileLight)).R = 200;
            }
            if (((Color)(ref tileLight)).G < 170)
            {
                ((Color)(ref tileLight)).G = 170;
            }
            if (_isActiveAndNotPaused && _rand.Next(60) == 0 && canDoDust)
            {
                int num2 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 204, 0f, 0f, 150, default(Color), 0.3f);
                _dust[num2].fadeIn = 1f;
                Dust obj2 = _dust[num2];
                obj2.velocity *= 0.1f;
                _dust[num2].noLight = true;
            }
        }
        if (!_localPlayer.biomeSight)
        {
            return;
        }
        Color sightColor = Color.White;
        if (Main.IsTileBiomeSightable(i, j, typeCache, tileFrameX, tileFrameY, ref sightColor))
        {
            if (((Color)(ref tileLight)).R < ((Color)(ref sightColor)).R)
            {
                ((Color)(ref tileLight)).R = ((Color)(ref sightColor)).R;
            }
            if (((Color)(ref tileLight)).G < ((Color)(ref sightColor)).G)
            {
                ((Color)(ref tileLight)).G = ((Color)(ref sightColor)).G;
            }
            if (((Color)(ref tileLight)).B < ((Color)(ref sightColor)).B)
            {
                ((Color)(ref tileLight)).B = ((Color)(ref sightColor)).B;
            }
            if (_isActiveAndNotPaused && canDoDust && _rand.Next(480) == 0)
            {
                Color newColor = sightColor;
                int num3 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 267, 0f, 0f, 150, newColor, 0.3f);
                _dust[num3].noGravity = true;
                _dust[num3].fadeIn = 1f;
                Dust obj3 = _dust[num3];
                obj3.velocity *= 0.1f;
                _dust[num3].noLightEmittence = true;
            }
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._dust, Terraria.GameContent.Drawing.TileDrawing._isActiveAndNotPaused, Terraria.GameContent.Drawing.TileDrawing._localPlayer, Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.Player.biomeSight, Terraria.Player.dangerSense, Terraria.Dust.fadeIn, Terraria.Player.findTreasure, Terraria.Main.IsTileBiomeSightable(), Terraria.GameContent.Drawing.TileDrawing.IsTileDangerous(), Terraria.Main.IsTileSpelunkable(), Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLight, and Terraria.Dust.noLightEmittence.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), and Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind().