TModLoader: Terraria.GameContent.Drawing.TileDrawing.MakeExtraPreparations
MakeExtraPreparations()
void Terraria.GameContent.Drawing.TileDrawing.MakeExtraPreparations (Tile tile, int x, int y, int tileStyle) inline private
Definition at line 304 of file TileDrawing.cs.
    {
        switch (tile.type)
        {
        case 5:
        {
            int treeFrame2 = 0;
            int floorY2 = 0;
            int topTextureFrameWidth2 = 0;
            int topTextureFrameHeight2 = 0;
            int treeStyle2 = 0;
            int xoffset2 = (tile.frameX == 44).ToInt() - (tile.frameX == 66).ToInt();
            if (WorldGen.GetCommonTreeFoliageData(x, y, xoffset2, ref treeFrame2, ref treeStyle2, out floorY2, out topTextureFrameWidth2, out topTextureFrameHeight2))
            {
                TilePaintSystemV2.TreeFoliageVariantKey treeFoliageVariantKey3 = default(TilePaintSystemV2.TreeFoliageVariantKey);
                treeFoliageVariantKey3.TextureIndex = treeStyle2;
                treeFoliageVariantKey3.PaintColor = tile.color();
                TilePaintSystemV2.TreeFoliageVariantKey lookupKey3 = treeFoliageVariantKey3;
                _paintSystem.RequestTreeTop(ref lookupKey3);
                _paintSystem.RequestTreeBranch(ref lookupKey3);
            }
            break;
        }
        case 583:
        case 584:
        case 585:
        case 586:
        case 587:
        case 588:
        case 589:
        {
            int treeFrame3 = 0;
            int floorY3 = 0;
            int topTextureFrameWidth3 = 0;
            int topTextureFrameHeight3 = 0;
            int treeStyle3 = 0;
            int xoffset3 = (tile.frameX == 44).ToInt() - (tile.frameX == 66).ToInt();
            if (WorldGen.GetGemTreeFoliageData(x, y, xoffset3, ref treeFrame3, ref treeStyle3, out floorY3, out topTextureFrameWidth3, out topTextureFrameHeight3))
            {
                TilePaintSystemV2.TreeFoliageVariantKey treeFoliageVariantKey = default(TilePaintSystemV2.TreeFoliageVariantKey);
                treeFoliageVariantKey.TextureIndex = treeStyle3;
                treeFoliageVariantKey.PaintColor = tile.color();
                TilePaintSystemV2.TreeFoliageVariantKey lookupKey4 = treeFoliageVariantKey;
                _paintSystem.RequestTreeTop(ref lookupKey4);
                _paintSystem.RequestTreeBranch(ref lookupKey4);
            }
            break;
        }
        case 596:
        case 616:
        {
            int treeFrame = 0;
            int floorY = 0;
            int topTextureFrameWidth = 0;
            int topTextureFrameHeight = 0;
            int treeStyle = 0;
            int xoffset = (tile.frameX == 44).ToInt() - (tile.frameX == 66).ToInt();
            if (WorldGen.GetVanityTreeFoliageData(x, y, xoffset, ref treeFrame, ref treeStyle, out floorY, out topTextureFrameWidth, out topTextureFrameHeight))
            {
                TilePaintSystemV2.TreeFoliageVariantKey treeFoliageVariantKey5 = default(TilePaintSystemV2.TreeFoliageVariantKey);
                treeFoliageVariantKey5.TextureIndex = treeStyle;
                treeFoliageVariantKey5.PaintColor = tile.color();
                TilePaintSystemV2.TreeFoliageVariantKey lookupKey2 = treeFoliageVariantKey5;
                _paintSystem.RequestTreeTop(ref lookupKey2);
                _paintSystem.RequestTreeBranch(ref lookupKey2);
            }
            break;
        }
        case 634:
        {
            int treeFrame4 = 0;
            int floorY4 = 0;
            int topTextureFrameWidth4 = 0;
            int topTextureFrameHeight4 = 0;
            int treeStyle4 = 0;
            int xoffset4 = (tile.frameX == 44).ToInt() - (tile.frameX == 66).ToInt();
            if (WorldGen.GetAshTreeFoliageData(x, y, xoffset4, ref treeFrame4, ref treeStyle4, out floorY4, out topTextureFrameWidth4, out topTextureFrameHeight4))
            {
                TilePaintSystemV2.TreeFoliageVariantKey treeFoliageVariantKey4 = default(TilePaintSystemV2.TreeFoliageVariantKey);
                treeFoliageVariantKey4.TextureIndex = treeStyle4;
                treeFoliageVariantKey4.PaintColor = tile.color();
                TilePaintSystemV2.TreeFoliageVariantKey lookupKey5 = treeFoliageVariantKey4;
                _paintSystem.RequestTreeTop(ref lookupKey5);
                _paintSystem.RequestTreeBranch(ref lookupKey5);
            }
            break;
        }
        case 323:
        {
            int textureIndex = 15;
            bool isOcean = false;
            if (x >= WorldGen.beachDistance && x <= Main.maxTilesX - WorldGen.beachDistance)
            {
                isOcean = true;
            }
            if (isOcean)
            {
                textureIndex = 21;
            }
            if (Math.Abs(tileStyle) >= 8)
            {
                textureIndex = Math.Abs(tileStyle) - 8;
                textureIndex *= -2;
                if (!isOcean)
                {
                    textureIndex--;
                }
            }
            TilePaintSystemV2.TreeFoliageVariantKey treeFoliageVariantKey2 = default(TilePaintSystemV2.TreeFoliageVariantKey);
            treeFoliageVariantKey2.TextureIndex = textureIndex;
            treeFoliageVariantKey2.PaintColor = tile.color();
            TilePaintSystemV2.TreeFoliageVariantKey lookupKey = treeFoliageVariantKey2;
            _paintSystem.RequestTreeTop(ref lookupKey);
            _paintSystem.RequestTreeBranch(ref lookupKey);
            break;
        }
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._paintSystem, Terraria.WorldGen.beachDistance, Terraria.Tile.color(), Terraria.WorldGen.GetAshTreeFoliageData(), Terraria.WorldGen.GetCommonTreeFoliageData(), Terraria.WorldGen.GetGemTreeFoliageData(), Terraria.WorldGen.GetVanityTreeFoliageData(), Terraria.Main.maxTilesX, Terraria.GameContent.TilePaintSystemV2.RequestTreeBranch(), Terraria.GameContent.TilePaintSystemV2.RequestTreeTop(), and Terraria.Tile.type.
Referenced by Terraria.GameContent.Drawing.TileDrawing.PrepareForAreaDrawing().