TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass
DrawAnyDirectionalGrass()
void Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass () inline private
    {
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0102: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_014b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03db: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_040c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0416: Unknown result type (might be due to invalid IL or missing references)
        //IL_0420: Unknown result type (might be due to invalid IL or missing references)
        //IL_0427: Unknown result type (might be due to invalid IL or missing references)
        Vector2 unscaledPosition = Main.Camera.UnscaledPosition;
        Vector2 zero = Vector2.Zero;
        int num = 12;
        int num2 = _specialsCount[num];
        Vector2 origin = default(Vector2);
        for (int i = 0; i < num2; i++)
        {
            Point val = _specialPositions[num][i];
            int x = val.X;
            int y = val.Y;
            Tile tile = Main.tile[x, y];
            if (tile == null || !tile.active() || !IsVisible(tile))
            {
                continue;
            }
            ushort type = tile.type;
            short tileFrameX = tile.frameX;
            short tileFrameY = tile.frameY;
            GetTileDrawData(x, y, tile, type, ref tileFrameX, ref tileFrameY, out var tileWidth, out var tileHeight, out var tileTop, out var halfBrickHeight, out var addFrX, out var addFrY, out var tileSpriteEffect, out var glowTexture, out var _, out var glowColor);
            bool flag = _rand.Next(4) == 0;
            Color tileLight = Lighting.GetColor(x, y);
            DrawAnimatedTile_AdjustForVisionChangers(x, y, tile, type, tileFrameX, tileFrameY, ref tileLight, flag);
            tileLight = DrawTiles_GetLightOverride(y, x, tile, type, tileFrameX, tileFrameY, tileLight);
            if (_isActiveAndNotPaused && flag)
            {
                DrawTiles_EmitParticles(y, x, tile, type, tileFrameX, tileFrameY, tileLight);
            }
            if (type == 83 && IsAlchemyPlantHarvestable(tileFrameX / 18))
            {
                type = 84;
                Main.instance.LoadTiles(type);
            }
            Vector2 position = new Vector2((float)(x * 16 - (int)unscaledPosition.X), (float)(y * 16 - (int)unscaledPosition.Y)) + zero;
            _ = _grassWindCounter;
            float num3 = GetWindCycle(x, y, _grassWindCounter);
            if (!WallID.Sets.AllowsWind[tile.wall])
            {
                num3 = 0f;
            }
            if (!InAPlaceWithWind(x, y, 1, 1))
            {
                num3 = 0f;
            }
            GetWindGridPush2Axis(x, y, 20, 0.35f, out var pushX, out var pushY);
            int num4 = 1;
            int num5 = 0;
            ((Vector2)(ref origin))._002Ector((float)(tileWidth / 2), (float)(16 - halfBrickHeight - tileTop));
            switch (tileFrameY / 54)
            {
            case 0:
                num4 = 1;
                num5 = 0;
                ((Vector2)(ref origin))._002Ector((float)(tileWidth / 2), (float)(16 - halfBrickHeight - tileTop));
                position.X += 8f;
                position.Y += 16f;
                position.X += num3;
                position.Y += Math.Abs(num3);
                break;
            case 1:
                num3 *= -1f;
                num4 = -1;
                num5 = 0;
                ((Vector2)(ref origin))._002Ector((float)(tileWidth / 2), (float)(-tileTop));
                position.X += 8f;
                position.X += 0f - num3;
                position.Y += 0f - Math.Abs(num3);
                break;
            case 2:
                num4 = 0;
                num5 = 1;
                ((Vector2)(ref origin))._002Ector(2f, (float)((16 - halfBrickHeight - tileTop) / 2));
                position.Y += 8f;
                position.Y += num3;
                position.X += 0f - Math.Abs(num3);
                break;
            case 3:
                num3 *= -1f;
                num4 = 0;
                num5 = -1;
                ((Vector2)(ref origin))._002Ector(14f, (float)((16 - halfBrickHeight - tileTop) / 2));
                position.X += 16f;
                position.Y += 8f;
                position.Y += 0f - num3;
                position.X += Math.Abs(num3);
                break;
            }
            num3 += pushX * (float)num4 + pushY * (float)num5;
            Texture2D tileDrawTexture = GetTileDrawTexture(tile, x, y);
            if (tileDrawTexture != null)
            {
                Main.spriteBatch.Draw(tileDrawTexture, position, (Rectangle?)new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight), tileLight, num3 * 0.1f, origin, 1f, tileSpriteEffect, 0f);
                if (glowTexture != null)
                {
                    Main.spriteBatch.Draw(glowTexture, position, (Rectangle?)new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight), glowColor, num3 * 0.1f, origin, 1f, tileSpriteEffect, 0f);
                }
            }
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._grassWindCounter, Terraria.GameContent.Drawing.TileDrawing._isActiveAndNotPaused, Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.GameContent.Drawing.TileDrawing._specialPositions, Terraria.GameContent.Drawing.TileDrawing._specialsCount, Terraria.Tile.active(), Terraria.ID.WallID.Sets.AllowsWind, Terraria.Main.Camera, Terraria.GameContent.Drawing.TileDrawing.DrawAnimatedTile_AdjustForVisionChangers(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_GetLightOverride(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Lighting.GetColor(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.GameContent.Drawing.TileDrawing.GetWindCycle(), Terraria.GameContent.Drawing.TileDrawing.GetWindGridPush2Axis(), Terraria.GameContent.Drawing.TileDrawing.InAPlaceWithWind(), Terraria.Main.instance, Terraria.GameContent.Drawing.TileDrawing.IsAlchemyPlantHarvestable(), Terraria.GameContent.Drawing.TileDrawing.IsVisible(), Terraria.Main.LoadTiles(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Tile.type, Terraria.Graphics.Camera.UnscaledPosition, and Terraria.Tile.wall.
Referenced by Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles().