TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile_SlicedBlock
DrawSingleTile_SlicedBlock()
void Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile_SlicedBlock (Vector2 normalTilePosition, int tileX, int tileY, TileDrawInfo drawData) inline private
    {
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0218: Unknown result type (might be due to invalid IL or missing references)
        //IL_0244: Unknown result type (might be due to invalid IL or missing references)
        //IL_024a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_025f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02af: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_062b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0637: Unknown result type (might be due to invalid IL or missing references)
        //IL_0641: Unknown result type (might be due to invalid IL or missing references)
        //IL_064d: Unknown result type (might be due to invalid IL or missing references)
        //IL_032b: Unknown result type (might be due to invalid IL or missing references)
        //IL_032d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_0339: Unknown result type (might be due to invalid IL or missing references)
        //IL_0341: Unknown result type (might be due to invalid IL or missing references)
        //IL_0465: Unknown result type (might be due to invalid IL or missing references)
        //IL_0488: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0533: Unknown result type (might be due to invalid IL or missing references)
        //IL_0542: Unknown result type (might be due to invalid IL or missing references)
        //IL_0551: Unknown result type (might be due to invalid IL or missing references)
        //IL_05be: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d4: Unknown result type (might be due to invalid IL or missing references)
        Color color = default(Color);
        Vector2 origin = default(Vector2);
        Rectangle value = default(Rectangle);
        Vector3 tileLight = default(Vector3);
        Vector2 position = default(Vector2);
        if (((Color)(ref drawData.tileLight)).R > ((Color)(ref _highQualityLightingRequirement)).R || ((Color)(ref drawData.tileLight)).G > ((Color)(ref _highQualityLightingRequirement)).G || ((Color)(ref drawData.tileLight)).B > ((Color)(ref _highQualityLightingRequirement)).B)
        {
            Vector3[] slices = drawData.colorSlices;
            Lighting.GetColor9Slice(tileX, tileY, ref slices);
            Vector3 vector = ((Color)(ref drawData.tileLight)).ToVector3();
            Vector3 tint = ((Color)(ref drawData.colorTint)).ToVector3();
            if (drawData.tileCache.fullbrightBlock())
            {
                slices = _glowPaintColorSlices;
            }
            for (int i = 0; i < 9; i++)
            {
                value.X = 0;
                value.Y = 0;
                value.Width = 4;
                value.Height = 4;
                switch (i)
                {
                case 1:
                    value.Width = 8;
                    value.X = 4;
                    break;
                case 2:
                    value.X = 12;
                    break;
                case 3:
                    value.Height = 8;
                    value.Y = 4;
                    break;
                case 4:
                    value.Width = 8;
                    value.Height = 8;
                    value.X = 4;
                    value.Y = 4;
                    break;
                case 5:
                    value.X = 12;
                    value.Y = 4;
                    value.Height = 8;
                    break;
                case 6:
                    value.Y = 12;
                    break;
                case 7:
                    value.Width = 8;
                    value.Height = 4;
                    value.X = 4;
                    value.Y = 12;
                    break;
                case 8:
                    value.X = 12;
                    value.Y = 12;
                    break;
                }
                tileLight.X = (slices[i].X + vector.X) * 0.5f;
                tileLight.Y = (slices[i].Y + vector.Y) * 0.5f;
                tileLight.Z = (slices[i].Z + vector.Z) * 0.5f;
                GetFinalLight(drawData.tileCache, drawData.typeCache, ref tileLight, ref tint);
                position.X = normalTilePosition.X + (float)value.X;
                position.Y = normalTilePosition.Y + (float)value.Y;
                value.X += drawData.tileFrameX + drawData.addFrX;
                value.Y += drawData.tileFrameY + drawData.addFrY;
                int num = (int)(tileLight.X * 255f);
                int num2 = (int)(tileLight.Y * 255f);
                int num3 = (int)(tileLight.Z * 255f);
                if (num > 255)
                {
                    num = 255;
                }
                if (num2 > 255)
                {
                    num2 = 255;
                }
                if (num3 > 255)
                {
                    num3 = 255;
                }
                num3 <<= 16;
                num2 <<= 8;
                ((Color)(ref color)).PackedValue = (uint)(num | num2 | num3) | 0xFF000000u;
                Main.spriteBatch.Draw(drawData.drawTexture, position, (Rectangle?)value, color, 0f, origin, 1f, drawData.tileSpriteEffect, 0f);
            }
        }
        else if (((Color)(ref drawData.tileLight)).R > ((Color)(ref _mediumQualityLightingRequirement)).R || ((Color)(ref drawData.tileLight)).G > ((Color)(ref _mediumQualityLightingRequirement)).G || ((Color)(ref drawData.tileLight)).B > ((Color)(ref _mediumQualityLightingRequirement)).B)
        {
            Vector3[] slices2 = drawData.colorSlices;
            Lighting.GetColor4Slice(tileX, tileY, ref slices2);
            Vector3 vector2 = ((Color)(ref drawData.tileLight)).ToVector3();
            Vector3 tint2 = ((Color)(ref drawData.colorTint)).ToVector3();
            if (drawData.tileCache.fullbrightBlock())
            {
                slices2 = _glowPaintColorSlices;
            }
            value.Width = 8;
            value.Height = 8;
            for (int j = 0; j < 4; j++)
            {
                value.X = 0;
                value.Y = 0;
                switch (j)
                {
                case 1:
                    value.X = 8;
                    break;
                case 2:
                    value.Y = 8;
                    break;
                case 3:
                    value.X = 8;
                    value.Y = 8;
                    break;
                }
                tileLight.X = (slices2[j].X + vector2.X) * 0.5f;
                tileLight.Y = (slices2[j].Y + vector2.Y) * 0.5f;
                tileLight.Z = (slices2[j].Z + vector2.Z) * 0.5f;
                GetFinalLight(drawData.tileCache, drawData.typeCache, ref tileLight, ref tint2);
                position.X = normalTilePosition.X + (float)value.X;
                position.Y = normalTilePosition.Y + (float)value.Y;
                value.X += drawData.tileFrameX + drawData.addFrX;
                value.Y += drawData.tileFrameY + drawData.addFrY;
                int num4 = (int)(tileLight.X * 255f);
                int num5 = (int)(tileLight.Y * 255f);
                int num6 = (int)(tileLight.Z * 255f);
                if (num4 > 255)
                {
                    num4 = 255;
                }
                if (num5 > 255)
                {
                    num5 = 255;
                }
                if (num6 > 255)
                {
                    num6 = 255;
                }
                num6 <<= 16;
                num5 <<= 8;
                ((Color)(ref color)).PackedValue = (uint)(num4 | num5 | num6) | 0xFF000000u;
                Main.spriteBatch.Draw(drawData.drawTexture, position, (Rectangle?)value, color, 0f, origin, 1f, drawData.tileSpriteEffect, 0f);
            }
        }
        else
        {
            Main.spriteBatch.Draw(drawData.drawTexture, normalTilePosition, (Rectangle?)new Rectangle(drawData.tileFrameX + drawData.addFrX, drawData.tileFrameY + drawData.addFrY, drawData.tileWidth, drawData.tileHeight), drawData.finalColor, 0f, _zero, 1f, drawData.tileSpriteEffect, 0f);
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._glowPaintColorSlices, Terraria.GameContent.Drawing.TileDrawing._highQualityLightingRequirement, Terraria.GameContent.Drawing.TileDrawing._mediumQualityLightingRequirement, Terraria.GameContent.Drawing.TileDrawing._zero, Terraria.Lighting.GetColor4Slice(), Terraria.Lighting.GetColor9Slice(), Terraria.GameContent.Drawing.TileDrawing.GetFinalLight(), and Terraria.Main.spriteBatch.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile().