TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons
DrawTeleportationPylons()
void Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons () inline private
Definition at line 10173 of file TileDrawing.cs.
    {
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00da: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0140: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_019b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        //IL_0230: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_016f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0176: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_024e: Unknown result type (might be due to invalid IL or missing references)
        //IL_025b: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0273: Unknown result type (might be due to invalid IL or missing references)
        //IL_0278: Unknown result type (might be due to invalid IL or missing references)
        //IL_027f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0286: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0307: Unknown result type (might be due to invalid IL or missing references)
        //IL_0309: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0313: Unknown result type (might be due to invalid IL or missing references)
        //IL_031a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0321: Unknown result type (might be due to invalid IL or missing references)
        int num = 10;
        int num2 = _specialsCount[num];
        for (int i = 0; i < num2; i++)
        {
            Point p = _specialPositions[num][i];
            Tile tile = Main.tile[p.X, p.Y];
            if (tile == null || !tile.active())
            {
                continue;
            }
            Texture2D value = TextureAssets.Extra[181].Value;
            int num3 = tile.frameX / 54;
            int num4 = 3;
            int horizontalFrames = num4 + 9;
            int verticalFrames = 8;
            int frameY = (Main.tileFrameCounter[597] + p.X + p.Y) % 64 / 8;
            Rectangle rectangle = value.Frame(horizontalFrames, verticalFrames, num4 + num3, frameY);
            Rectangle value2 = value.Frame(horizontalFrames, verticalFrames, 2, frameY);
            value.Frame(horizontalFrames, verticalFrames, 0, frameY);
            Vector2 origin = rectangle.Size() / 2f;
            Vector2 val = p.ToWorldCoordinates(24f, 64f);
            float num5 = (float)Math.Sin(Main.GlobalTimeWrappedHourly * ((float)Math.PI * 2f) / 5f);
            Vector2 vector2 = val + new Vector2(0f, -40f) + new Vector2(0f, num5 * 4f);
            bool flag = _rand.Next(4) == 0;
            if (_isActiveAndNotPaused && flag && _rand.Next(10) == 0)
            {
                Rectangle dustBox = Utils.CenteredRectangle(vector2, rectangle.Size());
                TeleportPylonsSystem.SpawnInWorldDust(num3, dustBox);
            }
            Color color = Lighting.GetColor(p.X, p.Y);
            color = Color.Lerp(color, Color.White, 0.8f);
            Main.spriteBatch.Draw(value, vector2 - Main.screenPosition, (Rectangle?)rectangle, color * 0.7f, 0f, origin, 1f, (SpriteEffects)0, 0f);
            float num6 = (float)Math.Sin(Main.GlobalTimeWrappedHourly * ((float)Math.PI * 2f) / 1f) * 0.2f + 0.8f;
            Color color2 = new Color(255, 255, 255, 0) * 0.1f * num6;
            for (float num7 = 0f; num7 < 1f; num7 += 1f / 6f)
            {
                Main.spriteBatch.Draw(value, vector2 - Main.screenPosition + ((float)Math.PI * 2f * num7).ToRotationVector2() * (6f + num5 * 2f), (Rectangle?)rectangle, color2, 0f, origin, 1f, (SpriteEffects)0, 0f);
            }
            int num8 = 0;
            if (Main.InSmartCursorHighlightArea(p.X, p.Y, out var actuallySelected))
            {
                num8 = 1;
                if (actuallySelected)
                {
                    num8 = 2;
                }
            }
            if (num8 != 0)
            {
                int num9 = (((Color)(ref color)).R + ((Color)(ref color)).G + ((Color)(ref color)).B) / 3;
                if (num9 > 10)
                {
                    Color selectionGlowColor = Colors.GetSelectionGlowColor(num8 == 2, num9);
                    Main.spriteBatch.Draw(value, vector2 - Main.screenPosition, (Rectangle?)value2, selectionGlowColor, 0f, origin, 1f, (SpriteEffects)0, 0f);
                }
            }
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._isActiveAndNotPaused, Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.GameContent.Drawing.TileDrawing._specialPositions, Terraria.GameContent.Drawing.TileDrawing._specialsCount, Terraria.Tile.active(), Terraria.Utils.CenteredRectangle(), Terraria.GameContent.TextureAssets.Extra, Terraria.Lighting.GetColor(), Terraria.ID.Colors.GetSelectionGlowColor(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.InSmartCursorHighlightArea(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.screenPosition, Terraria.GameContent.TeleportPylonsSystem.SpawnInWorldDust(), Terraria.Main.spriteBatch, Terraria.Main.tile, and Terraria.Main.tileFrameCounter.
Referenced by Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles().