TModLoader: Terraria.GameContent.Drawing.TileDrawing.IsVisible
IsVisible()
static bool Terraria.GameContent.Drawing.TileDrawing.IsVisible (Tile tile) inline static
Returns true if the tile is visible.
Tiles painted with Echo Coating as well as the Echo Platform, Echo Block, and Ghostly Stinkbug Blocker tiles will all be invisible unless the player has Echo Sight (Nearby active Echo Chamber tile or wearing Spectre Goggles)
Parameters
tile
Returns
Definition at line 1479 of file TileDrawing.cs.
    {
        bool flag = tile.invisibleBlock();
        switch (tile.type)
        {
        case 19:
            if (tile.frameY / 18 == 48)
            {
                flag = true;
            }
            break;
        case 541:
        case 631:
            flag = true;
            break;
        }
        if (flag)
        {
            return Main.instance.TilesRenderer._shouldShowInvisibleBlocks;
        }
        return true;
    }
References Terraria.Tile.frameY, Terraria.Main.instance, Terraria.Tile.invisibleBlock(), Terraria.Main.TilesRenderer, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawRisingVineStrip(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), and Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip().