TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawTile_MinecartTrack
DrawTile_MinecartTrack()
void Terraria.GameContent.Drawing.TileDrawing.DrawTile_MinecartTrack (Vector2 screenPosition, Vector2 screenOffset, int tileX, int tileY, TileDrawInfo drawData) inline private
Definition at line 4360 of file TileDrawing.cs.
    {
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0202: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_021a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0220: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0269: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0277: Unknown result type (might be due to invalid IL or missing references)
        //IL_0283: Unknown result type (might be due to invalid IL or missing references)
        //IL_028f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0295: Unknown result type (might be due to invalid IL or missing references)
        //IL_029e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02db: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_0319: Unknown result type (might be due to invalid IL or missing references)
        //IL_0340: Unknown result type (might be due to invalid IL or missing references)
        //IL_0350: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_035e: Unknown result type (might be due to invalid IL or missing references)
        //IL_035f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0371: Unknown result type (might be due to invalid IL or missing references)
        //IL_037d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0389: Unknown result type (might be due to invalid IL or missing references)
        //IL_038f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0398: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0404: Unknown result type (might be due to invalid IL or missing references)
        //IL_040a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0413: Unknown result type (might be due to invalid IL or missing references)
        //IL_0440: Unknown result type (might be due to invalid IL or missing references)
        //IL_0450: Unknown result type (might be due to invalid IL or missing references)
        //IL_0459: Unknown result type (might be due to invalid IL or missing references)
        //IL_045e: Unknown result type (might be due to invalid IL or missing references)
        //IL_045f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0467: Unknown result type (might be due to invalid IL or missing references)
        //IL_0473: Unknown result type (might be due to invalid IL or missing references)
        //IL_047f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0485: Unknown result type (might be due to invalid IL or missing references)
        //IL_048e: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04da: Unknown result type (might be due to invalid IL or missing references)
        //IL_04db: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0501: Unknown result type (might be due to invalid IL or missing references)
        //IL_050a: Unknown result type (might be due to invalid IL or missing references)
        drawData.tileLight = GetFinalLight(drawData.tileCache, drawData.typeCache, drawData.tileLight, drawData.colorTint);
        Minecart.TrackColors(tileX, tileY, drawData.tileCache, out var frontColor, out var backColor);
        drawData.drawTexture = GetTileDrawTexture(drawData.tileCache, tileX, tileY, frontColor);
        Texture2D tileDrawTexture = GetTileDrawTexture(drawData.tileCache, tileX, tileY, backColor);
        if (WorldGen.IsRope(tileX, tileY) && Main.tile[tileX, tileY - 1] != null)
        {
            _ = ref Main.tile[tileX, tileY - 1].type;
            int y = (tileY + tileX) % 3 * 18;
            Texture2D tileDrawTexture2 = GetTileDrawTexture(Main.tile[tileX, tileY - 1], tileX, tileY);
            Main.spriteBatch.Draw(tileDrawTexture2, new Vector2((float)(tileX * 16 - (int)screenPosition.X), (float)(tileY * 16 - (int)screenPosition.Y)) + screenOffset, (Rectangle?)new Rectangle(90, y, 16, 16), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
        }
        drawData.tileCache.frameNumber();
        if (drawData.tileFrameY != -1)
        {
            Main.spriteBatch.Draw(tileDrawTexture, new Vector2((float)(tileX * 16 - (int)screenPosition.X), (float)(tileY * 16 - (int)screenPosition.Y)) + screenOffset, (Rectangle?)Minecart.GetSourceRect(drawData.tileFrameY, Main.tileFrame[314]), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
        }
        Main.spriteBatch.Draw(drawData.drawTexture, new Vector2((float)(tileX * 16 - (int)screenPosition.X), (float)(tileY * 16 - (int)screenPosition.Y)) + screenOffset, (Rectangle?)Minecart.GetSourceRect(drawData.tileFrameX, Main.tileFrame[314]), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
        if (Minecart.DrawLeftDecoration(drawData.tileFrameY))
        {
            Main.spriteBatch.Draw(tileDrawTexture, new Vector2((float)(tileX * 16 - (int)screenPosition.X), (float)((tileY + 1) * 16 - (int)screenPosition.Y)) + screenOffset, (Rectangle?)Minecart.GetSourceRect(36), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
        }
        if (Minecart.DrawLeftDecoration(drawData.tileFrameX))
        {
            Main.spriteBatch.Draw(drawData.drawTexture, new Vector2((float)(tileX * 16 - (int)screenPosition.X), (float)((tileY + 1) * 16 - (int)screenPosition.Y)) + screenOffset, (Rectangle?)Minecart.GetSourceRect(36), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
        }
        if (Minecart.DrawRightDecoration(drawData.tileFrameY))
        {
            Main.spriteBatch.Draw(tileDrawTexture, new Vector2((float)(tileX * 16 - (int)screenPosition.X), (float)((tileY + 1) * 16 - (int)screenPosition.Y)) + screenOffset, (Rectangle?)Minecart.GetSourceRect(37, Main.tileFrame[314]), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
        }
        if (Minecart.DrawRightDecoration(drawData.tileFrameX))
        {
            Main.spriteBatch.Draw(drawData.drawTexture, new Vector2((float)(tileX * 16 - (int)screenPosition.X), (float)((tileY + 1) * 16 - (int)screenPosition.Y)) + screenOffset, (Rectangle?)Minecart.GetSourceRect(37), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
        }
        if (Minecart.DrawBumper(drawData.tileFrameX))
        {
            Main.spriteBatch.Draw(drawData.drawTexture, new Vector2((float)(tileX * 16 - (int)screenPosition.X), (float)((tileY - 1) * 16 - (int)screenPosition.Y)) + screenOffset, (Rectangle?)Minecart.GetSourceRect(39), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
        }
        else if (Minecart.DrawBouncyBumper(drawData.tileFrameX))
        {
            Main.spriteBatch.Draw(drawData.drawTexture, new Vector2((float)(tileX * 16 - (int)screenPosition.X), (float)((tileY - 1) * 16 - (int)screenPosition.Y)) + screenOffset, (Rectangle?)Minecart.GetSourceRect(38), drawData.tileLight, 0f, default(Vector2), 1f, drawData.tileSpriteEffect, 0f);
        }
    }
References Terraria.Minecart.DrawBouncyBumper(), Terraria.Minecart.DrawBumper(), Terraria.Minecart.DrawLeftDecoration(), Terraria.Minecart.DrawRightDecoration(), Terraria.GameContent.Drawing.TileDrawing.GetFinalLight(), Terraria.Minecart.GetSourceRect(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.WorldGen.IsRope(), Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Main.tileFrame, and Terraria.Minecart.TrackColors().
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile().