TModLoader: Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip
DrawVineStrip()
void Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip (Vector2 screenPosition, Vector2 offSet, int x, int startY) inline private
Definition at line 10687 of file TileDrawing.cs.
    {
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0198: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0327: Unknown result type (might be due to invalid IL or missing references)
        //IL_033a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0344: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_035d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0374: Unknown result type (might be due to invalid IL or missing references)
        //IL_0376: Unknown result type (might be due to invalid IL or missing references)
        //IL_037d: Unknown result type (might be due to invalid IL or missing references)
        //IL_038c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0396: Unknown result type (might be due to invalid IL or missing references)
        //IL_0277: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        //IL_0286: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ec: Unknown result type (might be due to invalid IL or missing references)
        int num = 0;
        int num2 = 0;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)(x * 16 + 8), (float)(startY * 16 - 2));
        float amount = Math.Abs(Main.WindForVisuals) / 1.2f;
        amount = MathHelper.Lerp(0.2f, 1f, amount);
        float num3 = -0.08f * amount;
        float windCycle = GetWindCycle(x, startY, _vineWindCounter);
        float num4 = 0f;
        float num5 = 0f;
        for (int i = startY; i < Main.maxTilesY - 10; i++)
        {
            Tile tile = Main.tile[x, i];
            if (tile == null)
            {
                continue;
            }
            ushort type = tile.type;
            if (!tile.active() || !TileID.Sets.VineThreads[type])
            {
                break;
            }
            num++;
            if (num2 >= 5)
            {
                num3 += 0.0075f * amount;
            }
            if (num2 >= 2)
            {
                num3 += 0.0025f;
            }
            if (Main.remixWorld)
            {
                if (WallID.Sets.AllowsWind[tile.wall] && (double)i > Main.worldSurface)
                {
                    num2++;
                }
            }
            else if (WallID.Sets.AllowsWind[tile.wall] && (double)i < Main.worldSurface)
            {
                num2++;
            }
            float windGridPush = GetWindGridPush(x, i, 20, 0.01f);
            num4 = ((windGridPush != 0f || num5 == 0f) ? (num4 - windGridPush) : (num4 * -0.78f));
            num5 = windGridPush;
            short tileFrameX = tile.frameX;
            short tileFrameY = tile.frameY;
            Color color = Lighting.GetColor(x, i);
            GetTileDrawData(x, i, tile, type, ref tileFrameX, ref tileFrameY, out var tileWidth, out var tileHeight, out var tileTop, out var halfBrickHeight, out var addFrX, out var addFrY, out var tileSpriteEffect, out var glowTexture, out var glowSourceRect, out var glowColor);
            Vector2 position = new Vector2((float)(-(int)screenPosition.X), (float)(-(int)screenPosition.Y)) + offSet + vector;
            if (tile.fullbrightBlock())
            {
                color = Color.White;
            }
            float num6 = (float)num2 * num3 * windCycle + num4;
            if (_localPlayer.biomeSight)
            {
                Color sightColor = Color.White;
                if (Main.IsTileBiomeSightable(x, i, type, tileFrameX, tileFrameY, ref sightColor))
                {
                    if (((Color)(ref color)).R < ((Color)(ref sightColor)).R)
                    {
                        ((Color)(ref color)).R = ((Color)(ref sightColor)).R;
                    }
                    if (((Color)(ref color)).G < ((Color)(ref sightColor)).G)
                    {
                        ((Color)(ref color)).G = ((Color)(ref sightColor)).G;
                    }
                    if (((Color)(ref color)).B < ((Color)(ref sightColor)).B)
                    {
                        ((Color)(ref color)).B = ((Color)(ref sightColor)).B;
                    }
                    if (_isActiveAndNotPaused && _rand.Next(480) == 0)
                    {
                        Color newColor = sightColor;
                        int num7 = Dust.NewDust(new Vector2((float)(x * 16), (float)(i * 16)), 16, 16, 267, 0f, 0f, 150, newColor, 0.3f);
                        _dust[num7].noGravity = true;
                        _dust[num7].fadeIn = 1f;
                        Dust obj = _dust[num7];
                        obj.velocity *= 0.1f;
                        _dust[num7].noLightEmittence = true;
                    }
                }
            }
            Texture2D tileDrawTexture = GetTileDrawTexture(tile, x, i);
            if (tileDrawTexture == null)
            {
                break;
            }
            if (IsVisible(tile))
            {
                Main.spriteBatch.Draw(tileDrawTexture, position, (Rectangle?)new Rectangle(tileFrameX + addFrX, tileFrameY + addFrY, tileWidth, tileHeight - halfBrickHeight), color, num6, new Vector2((float)(tileWidth / 2), (float)(halfBrickHeight - tileTop)), 1f, tileSpriteEffect, 0f);
                if (glowTexture != null)
                {
                    Main.spriteBatch.Draw(glowTexture, position, (Rectangle?)glowSourceRect, glowColor, num6, new Vector2((float)(tileWidth / 2), (float)(halfBrickHeight - tileTop)), 1f, tileSpriteEffect, 0f);
                }
            }
            vector += (num6 + (float)Math.PI / 2f).ToRotationVector2() * 16f;
        }
    }
References Terraria.GameContent.Drawing.TileDrawing._dust, Terraria.GameContent.Drawing.TileDrawing._isActiveAndNotPaused, Terraria.GameContent.Drawing.TileDrawing._localPlayer, Terraria.GameContent.Drawing.TileDrawing._rand, Terraria.GameContent.Drawing.TileDrawing._vineWindCounter, Terraria.Tile.active(), Terraria.ID.WallID.Sets.AllowsWind, Terraria.Player.biomeSight, Terraria.Dust.fadeIn, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.fullbrightBlock(), Terraria.Lighting.GetColor(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.GameContent.Drawing.TileDrawing.GetWindCycle(), Terraria.GameContent.Drawing.TileDrawing.GetWindGridPush(), Terraria.Main.IsTileBiomeSightable(), Terraria.GameContent.Drawing.TileDrawing.IsVisible(), Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLightEmittence, Terraria.Main.remixWorld, Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Tile.type, Terraria.ID.TileID.Sets.VineThreads, Terraria.Tile.wall, Terraria.Main.WindForVisuals, and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawVines().