TModLoader: Terraria.ModLoader.UI.UIProgress.OnInitialize
OnInitialize()
override void Terraria.ModLoader.UI.UIProgress.OnInitialize () inline virtual inherited
Reimplemented from Terraria.UI.UIElement.
    {
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        _progressBar = new UIProgressBar
        {
            Width =
            {
                Percent = 0.8f
            },
            MaxWidth = UICommon.MaxPanelWidth,
            Height =
            {
                Pixels = 150f
            },
            HAlign = 0.5f,
            VAlign = 0.5f,
            Top =
            {
                Pixels = 10f
            }
        };
        Append(_progressBar);
        _cancelButton = new UITextPanel<LocalizedText>(Language.GetText("UI.Cancel"), 0.75f, large: true)
        {
            VAlign = 0.5f,
            HAlign = 0.5f,
            Top =
            {
                Pixels = 170f
            }
        }.WithFadedMouseOver();
        _cancelButton.OnLeftClick += CancelClick;
        Append(_cancelButton);
        subProgress = new UIText("", 0.5f, large: true)
        {
            Top =
            {
                Pixels = 65f
            },
            HAlign = 0.5f,
            VAlign = 0.5f
        };
        Append(subProgress);
    }
References Terraria.ModLoader.UI.UIProgress._cancelButton, Terraria.ModLoader.UI.UIProgress._progressBar, Terraria.UI.UIElement.Append(), Terraria.ModLoader.UI.UIProgress.CancelClick(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.ModLoader.UI.UICommon.MaxPanelWidth, Terraria.UI.UIElement.MaxWidth, Terraria.ModLoader.UI.UIProgress.subProgress, Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.