TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.ElderSlimeEffect
ElderSlimeEffect()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.ElderSlimeEffect (ParticleOrchestraSettings settings) inline static private
    {
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        for (int i = 0; i < 30; i++)
        {
            Dust dust = Dust.NewDustPerfect(settings.PositionInWorld + Main.rand.NextVector2Circular(20f, 20f), 43, (settings.MovementVector * 0.75f + Main.rand.NextVector2Circular(6f, 6f)) * Main.rand.NextFloat(), 26, Color.Lerp(Main.OurFavoriteColor, Color.White, Main.rand.NextFloat()), 1f + Main.rand.NextFloat() * 1.4f);
            dust.fadeIn = 1.5f;
            if (dust.velocity.Y > 0f && Main.rand.Next(2) == 0)
            {
                dust.velocity.Y *= -1f;
            }
            dust.noGravity = true;
        }
        for (int j = 0; j < 8; j++)
        {
            Gore gore = Gore.NewGoreDirect(settings.PositionInWorld + Utils.RandomVector2(Main.rand, -30f, 30f) * new Vector2(0.5f, 1f), Vector2.Zero, 61 + Main.rand.Next(3));
            gore.velocity *= 0.5f;
        }
    }
References Terraria.Dust.NewDustPerfect(), Terraria.Gore.NewGoreDirect(), Terraria.Main.OurFavoriteColor, Terraria.Main.rand, Terraria.Utils.RandomVector2(), and Terraria.Dust.velocity.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TownSlimeTransform().