TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StardustPunch
Spawn_StardustPunch()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StardustPunch (ParticleOrchestraSettings settings) inline static private
    {
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00de: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_016f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0174: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_0218: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_023b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0240: Unknown result type (might be due to invalid IL or missing references)
        //IL_02aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_02af: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0301: Unknown result type (might be due to invalid IL or missing references)
        //IL_0307: Unknown result type (might be due to invalid IL or missing references)
        //IL_0322: Unknown result type (might be due to invalid IL or missing references)
        //IL_032c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0331: Unknown result type (might be due to invalid IL or missing references)
        //IL_0336: Unknown result type (might be due to invalid IL or missing references)
        //IL_0375: Unknown result type (might be due to invalid IL or missing references)
        //IL_0389: Unknown result type (might be due to invalid IL or missing references)
        //IL_038e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0393: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e5: Unknown result type (might be due to invalid IL or missing references)
        float num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
        float num2 = 1f;
        Vector2 vector2 = default(Vector2);
        for (float num3 = 0f; num3 < 1f; num3 += 1f / num2)
        {
            Vector2 vector = settings.MovementVector * (0.3f + Main.rand.NextFloat() * 0.35f);
            ((Vector2)(ref vector2))._002Ector(Main.rand.NextFloat() * 0.4f + 0.4f);
            float f = num + Main.rand.NextFloat() * ((float)Math.PI * 2f);
            float rotation = (float)Math.PI / 2f;
            Vector2 vector3 = 0.1f * vector2;
            float num4 = 60f;
            Vector2 vector4 = Main.rand.NextVector2Circular(8f, 8f) * vector2;
            PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
            prettySparkleParticle.Velocity = f.ToRotationVector2() * vector3 + vector;
            prettySparkleParticle.AccelerationPerFrame = f.ToRotationVector2() * -(vector3 / num4) - vector * 1f / 60f;
            prettySparkleParticle.ColorTint = Main.hslToRgb((0.6f + Main.rand.NextFloat() * 0.05f) % 1f, 1f, 0.4f + Main.rand.NextFloat() * 0.25f);
            ((Color)(ref prettySparkleParticle.ColorTint)).A = 0;
            prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector4;
            prettySparkleParticle.Rotation = rotation;
            prettySparkleParticle.Scale = vector2;
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
            prettySparkleParticle = _poolPrettySparkle.RequestParticle();
            prettySparkleParticle.Velocity = f.ToRotationVector2() * vector3 + vector;
            prettySparkleParticle.AccelerationPerFrame = f.ToRotationVector2() * -(vector3 / num4) - vector * 1f / 30f;
            prettySparkleParticle.ColorTint = new Color(255, 255, 255, 0);
            prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector4;
            prettySparkleParticle.Rotation = rotation;
            prettySparkleParticle.Scale = vector2 * 0.6f;
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
        }
        for (int i = 0; i < 2; i++)
        {
            Color newColor = Main.hslToRgb((0.59f + Main.rand.NextFloat() * 0.05f) % 1f, 1f, 0.4f + Main.rand.NextFloat() * 0.25f);
            int num5 = Dust.NewDust(settings.PositionInWorld, 0, 0, 267, 0f, 0f, 0, newColor);
            Main.dust[num5].velocity = Main.rand.NextVector2Circular(2f, 2f);
            Dust obj = Main.dust[num5];
            obj.velocity += settings.MovementVector * (0.5f + 0.5f * Main.rand.NextFloat()) * 1.4f;
            Main.dust[num5].noGravity = true;
            Main.dust[num5].scale = 0.6f + Main.rand.NextFloat() * 2f;
            Dust obj2 = Main.dust[num5];
            obj2.position += Main.rand.NextVector2Circular(16f, 16f);
            if (num5 != 6000)
            {
                Dust dust = Dust.CloneDust(num5);
                dust.scale /= 2f;
                dust.fadeIn *= 0.75f;
                dust.color = new Color(255, 255, 255, 255);
            }
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Dust.CloneDust(), Terraria.Main.dust, Terraria.Main.hslToRgb(), Terraria.Dust.NewDust(), Terraria.Main.ParticleSystem_World_OverPlayers, and Terraria.Main.rand.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().