TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowRodHit
Spawn_RainbowRodHit()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowRodHit (ParticleOrchestraSettings settings) inline static private
Definition at line 2392 of file ParticleOrchestrator.cs.
    {
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01de: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_021a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0222: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        //IL_022e: Unknown result type (might be due to invalid IL or missing references)
        //IL_023e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0245: Unknown result type (might be due to invalid IL or missing references)
        //IL_024a: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0307: Unknown result type (might be due to invalid IL or missing references)
        //IL_030d: Unknown result type (might be due to invalid IL or missing references)
        //IL_031c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0326: Unknown result type (might be due to invalid IL or missing references)
        //IL_032b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d6: Unknown result type (might be due to invalid IL or missing references)
        float num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
        float num2 = 6f;
        float num3 = Main.rand.NextFloat();
        Vector2 vector2 = default(Vector2);
        for (float num4 = 0f; num4 < 1f; num4 += 1f / num2)
        {
            Vector2 vector = settings.MovementVector * Main.rand.NextFloatDirection() * 0.15f;
            ((Vector2)(ref vector2))._002Ector(Main.rand.NextFloat() * 0.4f + 0.4f);
            float f = num + Main.rand.NextFloat() * ((float)Math.PI * 2f);
            float rotation = (float)Math.PI / 2f;
            Vector2 vector3 = 1.5f * vector2;
            float num5 = 60f;
            Vector2 vector4 = Main.rand.NextVector2Circular(8f, 8f) * vector2;
            PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
            prettySparkleParticle.Velocity = f.ToRotationVector2() * vector3 + vector;
            prettySparkleParticle.AccelerationPerFrame = f.ToRotationVector2() * -(vector3 / num5) - vector * 1f / 60f;
            prettySparkleParticle.ColorTint = Main.hslToRgb((num3 + Main.rand.NextFloat() * 0.33f) % 1f, 1f, 0.4f + Main.rand.NextFloat() * 0.25f);
            ((Color)(ref prettySparkleParticle.ColorTint)).A = 0;
            prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector4;
            prettySparkleParticle.Rotation = rotation;
            prettySparkleParticle.Scale = vector2;
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
            prettySparkleParticle = _poolPrettySparkle.RequestParticle();
            prettySparkleParticle.Velocity = f.ToRotationVector2() * vector3 + vector;
            prettySparkleParticle.AccelerationPerFrame = f.ToRotationVector2() * -(vector3 / num5) - vector * 1f / 60f;
            prettySparkleParticle.ColorTint = new Color(255, 255, 255, 0);
            prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector4;
            prettySparkleParticle.Rotation = rotation;
            prettySparkleParticle.Scale = vector2 * 0.6f;
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
        }
        for (int i = 0; i < 12; i++)
        {
            Color newColor = Main.hslToRgb((num3 + Main.rand.NextFloat() * 0.12f) % 1f, 1f, 0.4f + Main.rand.NextFloat() * 0.25f);
            int num6 = Dust.NewDust(settings.PositionInWorld, 0, 0, 267, 0f, 0f, 0, newColor);
            Main.dust[num6].velocity = Main.rand.NextVector2Circular(1f, 1f);
            Dust obj = Main.dust[num6];
            obj.velocity += settings.MovementVector * Main.rand.NextFloatDirection() * 0.5f;
            Main.dust[num6].noGravity = true;
            Main.dust[num6].scale = 0.6f + Main.rand.NextFloat() * 0.9f;
            Main.dust[num6].fadeIn = 0.7f + Main.rand.NextFloat() * 0.8f;
            if (num6 != 6000)
            {
                Dust dust = Dust.CloneDust(num6);
                dust.scale /= 2f;
                dust.fadeIn *= 0.75f;
                dust.color = new Color(255, 255, 255, 255);
            }
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Dust.CloneDust(), Terraria.Main.dust, Terraria.Main.hslToRgb(), Terraria.Dust.NewDust(), Terraria.Main.ParticleSystem_World_OverPlayers, and Terraria.Main.rand.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().