TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerArrow
Spawn_ShimmerArrow()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerArrow (ParticleOrchestraSettings settings) inline static private
Definition at line 622 of file ParticleOrchestrator.cs.
    {
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0164: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0201: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_0207: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0214: Unknown result type (might be due to invalid IL or missing references)
        //IL_021b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_019a: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_0253: Unknown result type (might be due to invalid IL or missing references)
        //IL_0258: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_02af: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0314: Unknown result type (might be due to invalid IL or missing references)
        //IL_031e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0339: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0341: Unknown result type (might be due to invalid IL or missing references)
        //IL_0350: Unknown result type (might be due to invalid IL or missing references)
        //IL_035d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0363: Unknown result type (might be due to invalid IL or missing references)
        //IL_038c: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0393: Unknown result type (might be due to invalid IL or missing references)
        //IL_039d: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03be: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0410: Unknown result type (might be due to invalid IL or missing references)
        //IL_0411: Unknown result type (might be due to invalid IL or missing references)
        float num = 20f;
        for (int i = 0; i < 2; i++)
        {
            float num2 = (float)Math.PI * 2f * Main.rand.NextFloatDirection() * 0.05f;
            Color color = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f);
            ((Color)(ref color)).A = (byte)(((Color)(ref color)).A / 2);
            Color value = color;
            ((Color)(ref value)).A = byte.MaxValue;
            value = Color.Lerp(value, Color.White, 0.5f);
            for (float num3 = 0f; num3 < 4f; num3 += 1f)
            {
                PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
                Vector2 vector = ((float)Math.PI / 2f * num3 + num2).ToRotationVector2() * 4f;
                prettySparkleParticle.ColorTint = color;
                prettySparkleParticle.LocalPosition = settings.PositionInWorld;
                prettySparkleParticle.Rotation = vector.ToRotation();
                prettySparkleParticle.Scale = new Vector2((num3 % 2f == 0f) ? 2f : 4f, 0.5f) * 1.1f;
                prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
                prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
                prettySparkleParticle.TimeToLive = num;
                prettySparkleParticle.FadeOutEnd = num;
                prettySparkleParticle.FadeInEnd = num / 2f;
                prettySparkleParticle.FadeOutStart = num / 2f;
                prettySparkleParticle.AdditiveAmount = 0.35f;
                prettySparkleParticle.Velocity = -vector * 0.2f;
                prettySparkleParticle.DrawVerticalAxis = false;
                if (num3 % 2f == 1f)
                {
                    prettySparkleParticle.Scale *= 0.9f;
                    prettySparkleParticle.Velocity *= 0.9f;
                }
                Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
            }
            for (float num4 = 0f; num4 < 4f; num4 += 1f)
            {
                PrettySparkleParticle prettySparkleParticle2 = _poolPrettySparkle.RequestParticle();
                Vector2 vector2 = ((float)Math.PI / 2f * num4 + num2).ToRotationVector2() * 4f;
                prettySparkleParticle2.ColorTint = value;
                prettySparkleParticle2.LocalPosition = settings.PositionInWorld;
                prettySparkleParticle2.Rotation = vector2.ToRotation();
                prettySparkleParticle2.Scale = new Vector2((num4 % 2f == 0f) ? 2f : 4f, 0.5f) * 0.7f;
                prettySparkleParticle2.FadeInNormalizedTime = 5E-06f;
                prettySparkleParticle2.FadeOutNormalizedTime = 0.95f;
                prettySparkleParticle2.TimeToLive = num;
                prettySparkleParticle2.FadeOutEnd = num;
                prettySparkleParticle2.FadeInEnd = num / 2f;
                prettySparkleParticle2.FadeOutStart = num / 2f;
                prettySparkleParticle2.Velocity = vector2 * 0.2f;
                prettySparkleParticle2.DrawVerticalAxis = false;
                if (num4 % 2f == 1f)
                {
                    prettySparkleParticle2.Scale *= 1.2f;
                    prettySparkleParticle2.Velocity *= 1.2f;
                }
                Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle2);
                if (i == 0)
                {
                    for (int j = 0; j < 1; j++)
                    {
                        Dust dust = Dust.NewDustPerfect(settings.PositionInWorld, 306, vector2.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                        dust.noGravity = true;
                        dust.scale = 1.4f;
                        dust.fadeIn = 1.2f;
                        dust.color = color;
                        Dust dust2 = Dust.NewDustPerfect(settings.PositionInWorld, 306, -vector2.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                        dust2.noGravity = true;
                        dust2.scale = 1.4f;
                        dust2.fadeIn = 1.2f;
                        dust2.color = color;
                    }
                }
            }
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Main.hslToRgb(), Terraria.Dust.NewDustPerfect(), Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Main.rand, and Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle().
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().