TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_GasTrap
Spawn_GasTrap()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_GasTrap (ParticleOrchestraSettings settings) inline static private
Definition at line 1132 of file ParticleOrchestrator.cs.
    {
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0160: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        SoundEngine.PlaySound(in SoundID.Item16, settings.PositionInWorld);
        Vector2 movementVector = settings.MovementVector;
        int num = 12;
        int num2 = 10;
        float num3 = 5f;
        float num4 = 2.5f;
        Color lightColorTint = default(Color);
        ((Color)(ref lightColorTint))._002Ector(0.2f, 0.4f, 0.15f);
        Vector2 positionInWorld = settings.PositionInWorld;
        float num5 = (float)Math.PI / 20f;
        float num6 = (float)Math.PI / 15f;
        for (int i = 0; i < num; i++)
        {
            Vector2 spinninpoint = movementVector + Utils.RotatedBy(new Vector2(num3 + Main.rand.NextFloat() * 1f, 0f), (float)i / (float)num * ((float)Math.PI * 2f), Vector2.Zero);
            spinninpoint = spinninpoint.RotatedByRandom(num5);
            GasParticle gasParticle = _poolGas.RequestParticle();
            gasParticle.AccelerationPerFrame = Vector2.Zero;
            gasParticle.Velocity = spinninpoint;
            gasParticle.ColorTint = Color.White;
            gasParticle.LightColorTint = lightColorTint;
            gasParticle.LocalPosition = positionInWorld + spinninpoint;
            gasParticle.TimeToLive = 50 + Main.rand.Next(20);
            gasParticle.InitialScale = 1f + Main.rand.NextFloat() * 0.35f;
            Main.ParticleSystem_World_BehindPlayers.Add(gasParticle);
        }
        for (int j = 0; j < num2; j++)
        {
            Vector2 spinninpoint2 = Utils.RotatedBy(new Vector2(num4 + Main.rand.NextFloat() * 1.45f, 0f), (float)j / (float)num2 * ((float)Math.PI * 2f), Vector2.Zero);
            spinninpoint2 = spinninpoint2.RotatedByRandom(num6);
            if (j % 2 == 0)
            {
                spinninpoint2 *= 0.5f;
            }
            GasParticle gasParticle2 = _poolGas.RequestParticle();
            gasParticle2.AccelerationPerFrame = Vector2.Zero;
            gasParticle2.Velocity = spinninpoint2;
            gasParticle2.ColorTint = Color.White;
            gasParticle2.LightColorTint = lightColorTint;
            gasParticle2.LocalPosition = positionInWorld;
            gasParticle2.TimeToLive = 80 + Main.rand.Next(30);
            gasParticle2.InitialScale = 1f + Main.rand.NextFloat() * 0.5f;
            Main.ParticleSystem_World_BehindPlayers.Add(gasParticle2);
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolGas, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.ID.SoundID.Item16, Terraria.Main.ParticleSystem_World_BehindPlayers, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), and Terraria.Utils.RotatedBy().
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().