TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LoadOutChange
Spawn_LoadOutChange()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LoadOutChange (ParticleOrchestraSettings settings) inline static private
    {
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[settings.IndexOfPlayerWhoInvokedThis];
        if (player.active)
        {
            Rectangle hitbox = player.Hitbox;
            int num = 6;
            hitbox.Height -= num;
            if (player.gravDir == 1f)
            {
                hitbox.Y += num;
            }
            for (int i = 0; i < 40; i++)
            {
                Dust dust = Dust.NewDustPerfect(Main.rand.NextVector2FromRectangle(hitbox), 16, null, 120, default(Color), Main.rand.NextFloat() * 0.8f + 0.8f);
                dust.velocity = Utils.RotatedBy(new Vector2(0f, (float)(-hitbox.Height) * Main.rand.NextFloat() * 0.04f), Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.1f);
                dust.velocity += player.velocity * 2f * Main.rand.NextFloat();
                dust.noGravity = true;
                dust.noLight = (dust.noLightEmittence = true);
            }
            for (int j = 0; j < 5; j++)
            {
                Dust dust2 = Dust.NewDustPerfect(Main.rand.NextVector2FromRectangle(hitbox), 43, null, 254, Main.hslToRgb(Main.rand.NextFloat(), 0.3f, 0.8f), Main.rand.NextFloat() * 0.8f + 0.8f);
                dust2.velocity = Utils.RotatedBy(new Vector2(0f, (float)(-hitbox.Height) * Main.rand.NextFloat() * 0.04f), Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.1f);
                dust2.velocity += player.velocity * 2f * Main.rand.NextFloat();
                dust2.noGravity = true;
                dust2.noLight = (dust2.noLightEmittence = true);
            }
        }
    }
References Terraria.Entity.active, Terraria.Player.gravDir, Terraria.Entity.Hitbox, Terraria.Main.hslToRgb(), Terraria.Dust.NewDustPerfect(), Terraria.Main.player, Terraria.Main.rand, and Terraria.Utils.RotatedBy().
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().