TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsHammer
Spawn_PaladinsHammer()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsHammer (ParticleOrchestraSettings settings) inline static private
    {
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0126: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_019b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0295: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0302: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        //IL_0344: Unknown result type (might be due to invalid IL or missing references)
        //IL_0349: Unknown result type (might be due to invalid IL or missing references)
        //IL_034e: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0361: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b3: Unknown result type (might be due to invalid IL or missing references)
        float num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
        float num2 = 1f;
        Vector2 vector2 = default(Vector2);
        for (float num3 = 0f; num3 < 1f; num3 += 1f / num2)
        {
            float num4 = 0.6f + Main.rand.NextFloat() * 0.35f;
            Vector2 vector = settings.MovementVector * num4;
            ((Vector2)(ref vector2))._002Ector(Main.rand.NextFloat() * 0.4f + 0.2f);
            float f = num + Main.rand.NextFloat() * ((float)Math.PI * 2f);
            float rotation = (float)Math.PI / 2f;
            _ = 0.1f * vector2;
            Vector2 vector3 = Main.rand.NextVector2Circular(12f, 12f) * vector2;
            PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
            prettySparkleParticle.AccelerationPerFrame = -vector * 1f / 30f;
            prettySparkleParticle.Velocity = vector + f.ToRotationVector2() * 2f * num4;
            prettySparkleParticle.ColorTint = new Color(1f, 0.8f, 0.4f, 0f);
            prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector3;
            prettySparkleParticle.Rotation = rotation;
            prettySparkleParticle.Scale = vector2;
            prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
            prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
            prettySparkleParticle.TimeToLive = 40f;
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
            prettySparkleParticle = _poolPrettySparkle.RequestParticle();
            prettySparkleParticle.AccelerationPerFrame = -vector * 1f / 30f;
            prettySparkleParticle.Velocity = vector * 0.8f + f.ToRotationVector2() * 2f;
            prettySparkleParticle.ColorTint = new Color(255, 255, 255, 0);
            prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector3;
            prettySparkleParticle.Rotation = rotation;
            prettySparkleParticle.Scale = vector2 * 0.6f;
            prettySparkleParticle.FadeInNormalizedTime = 0.1f;
            prettySparkleParticle.FadeOutNormalizedTime = 0.9f;
            prettySparkleParticle.TimeToLive = 60f;
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
        }
        Color newColor = default(Color);
        for (int i = 0; i < 2; i++)
        {
            ((Color)(ref newColor))._002Ector(1f, 0.7f, 0.3f, 0f);
            int num5 = Dust.NewDust(settings.PositionInWorld, 0, 0, 267, 0f, 0f, 0, newColor);
            Main.dust[num5].velocity = Main.rand.NextVector2Circular(2f, 2f);
            Dust obj = Main.dust[num5];
            obj.velocity += settings.MovementVector * (0.5f + 0.5f * Main.rand.NextFloat()) * 1.4f;
            Main.dust[num5].noGravity = true;
            Main.dust[num5].scale = 0.1f;
            Dust obj2 = Main.dust[num5];
            obj2.position += Main.rand.NextVector2Circular(16f, 16f);
            Main.dust[num5].velocity = settings.MovementVector;
            if (num5 != 6000)
            {
                Dust dust = Dust.CloneDust(num5);
                dust.scale /= 2f;
                dust.fadeIn *= 0.75f;
                dust.color = new Color(255, 255, 255, 255);
            }
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Dust.CloneDust(), Terraria.Main.dust, Terraria.Dust.NewDust(), Terraria.Main.ParticleSystem_World_OverPlayers, and Terraria.Main.rand.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().