TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerBlock
Spawn_ShimmerBlock()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerBlock (ParticleOrchestraSettings settings) inline static private
    {
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        FadingParticle fadingParticle = _poolFading.RequestParticle();
        fadingParticle.SetBasicInfo(TextureAssets.Star[0], null, settings.MovementVector, settings.PositionInWorld);
        float num = 45f;
        fadingParticle.SetTypeInfo(num);
        fadingParticle.AccelerationPerFrame = settings.MovementVector / num;
        fadingParticle.ColorTint = Main.hslToRgb(Main.rand.NextFloat(), 0.75f, 0.8f);
        ((Color)(ref fadingParticle.ColorTint)).A = 30;
        fadingParticle.FadeInNormalizedTime = 0.5f;
        fadingParticle.FadeOutNormalizedTime = 0.5f;
        fadingParticle.Rotation = Main.rand.NextFloat() * ((float)Math.PI * 2f);
        fadingParticle.Scale = Vector2.One * (0.5f + 0.5f * Main.rand.NextFloat());
        Main.ParticleSystem_World_OverPlayers.Add(fadingParticle);
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolFading, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Main.hslToRgb(), Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), and Terraria.GameContent.TextureAssets.Star.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().