TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningHit
Spawn_BlackLightningHit()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningHit (ParticleOrchestraSettings settings) inline static private
    {
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_0137: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_022c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        float num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
        float num2 = 7f;
        float num3 = 0.7f;
        int num4 = 916;
        Main.instance.LoadProjectile(num4);
        Color value = default(Color);
        ((Color)(ref value))._002Ector(255, 255, 255, 255);
        Color indigo = Color.Indigo;
        ((Color)(ref indigo)).A = 0;
        Color colorTint = default(Color);
        for (float num5 = 0f; num5 < 1f; num5 += 1f / num2)
        {
            float num6 = (float)Math.PI * 2f * num5 + num + Main.rand.NextFloatDirection() * 0.25f;
            float num7 = Main.rand.NextFloat() * 4f + 0.1f;
            Vector2 vector = Main.rand.NextVector2Circular(12f, 12f) * num3;
            Color.Lerp(Color.Lerp(Color.Black, indigo, Main.rand.NextFloat() * 0.5f), value, Main.rand.NextFloat() * 0.6f);
            ((Color)(ref colorTint))._002Ector(0, 0, 0, 255);
            int num8 = Main.rand.Next(4);
            if (num8 == 1)
            {
                colorTint = Color.Lerp(new Color(106, 90, 205, 127), Color.Black, 0.1f + 0.7f * Main.rand.NextFloat());
            }
            if (num8 == 2)
            {
                colorTint = Color.Lerp(new Color(106, 90, 205, 60), Color.Black, 0.1f + 0.8f * Main.rand.NextFloat());
            }
            RandomizedFrameParticle randomizedFrameParticle = _poolRandomizedFrame.RequestParticle();
            randomizedFrameParticle.SetBasicInfo(TextureAssets.Projectile[num4], null, Vector2.Zero, vector);
            randomizedFrameParticle.SetTypeInfo(Main.projFrames[num4], 2, 24f);
            randomizedFrameParticle.Velocity = num6.ToRotationVector2() * num7 * new Vector2(1f, 0.5f);
            randomizedFrameParticle.ColorTint = colorTint;
            randomizedFrameParticle.LocalPosition = settings.PositionInWorld + vector;
            randomizedFrameParticle.Rotation = num6;
            randomizedFrameParticle.Scale = Vector2.One;
            randomizedFrameParticle.FadeInNormalizedTime = 0.01f;
            randomizedFrameParticle.FadeOutNormalizedTime = 0.5f;
            randomizedFrameParticle.ScaleVelocity = new Vector2(0.05f);
            Main.ParticleSystem_World_OverPlayers.Add(randomizedFrameParticle);
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolRandomizedFrame, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Main.instance, Terraria.Main.LoadProjectile(), Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.projFrames, Terraria.Main.rand, and Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle().
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().