TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPCSend
Spawn_ShimmerTownNPCSend()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPCSend (ParticleOrchestraSettings settings) inline static private
Definition at line 208 of file ParticleOrchestrator.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        Rectangle rect = Utils.CenteredRectangle(settings.PositionInWorld, new Vector2(30f, 60f));
        for (float num = 0f; num < 20f; num += 1f)
        {
            PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
            int num2 = Main.rand.Next(20, 40);
            prettySparkleParticle.ColorTint = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f, 0);
            prettySparkleParticle.LocalPosition = Main.rand.NextVector2FromRectangle(rect);
            prettySparkleParticle.Rotation = (float)Math.PI / 2f;
            prettySparkleParticle.Scale = new Vector2(1f + Main.rand.NextFloat() * 2f, 0.7f + Main.rand.NextFloat() * 0.7f);
            prettySparkleParticle.Velocity = new Vector2(0f, -1f);
            prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
            prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
            prettySparkleParticle.TimeToLive = num2;
            prettySparkleParticle.FadeOutEnd = num2;
            prettySparkleParticle.FadeInEnd = num2 / 2;
            prettySparkleParticle.FadeOutStart = num2 / 2;
            prettySparkleParticle.AdditiveAmount = 0.35f;
            prettySparkleParticle.DrawVerticalAxis = false;
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
            PrettySparkleParticle prettySparkleParticle2 = _poolPrettySparkle.RequestParticle();
            prettySparkleParticle2.ColorTint = new Color(255, 255, 255, 0);
            prettySparkleParticle2.LocalPosition = Main.rand.NextVector2FromRectangle(rect);
            prettySparkleParticle2.Rotation = (float)Math.PI / 2f;
            prettySparkleParticle2.Scale = prettySparkleParticle.Scale * 0.5f;
            prettySparkleParticle2.Velocity = new Vector2(0f, -1f);
            prettySparkleParticle2.FadeInNormalizedTime = 5E-06f;
            prettySparkleParticle2.FadeOutNormalizedTime = 0.95f;
            prettySparkleParticle2.TimeToLive = num2;
            prettySparkleParticle2.FadeOutEnd = num2;
            prettySparkleParticle2.FadeInEnd = num2 / 2;
            prettySparkleParticle2.FadeOutStart = num2 / 2;
            prettySparkleParticle2.AdditiveAmount = 1f;
            prettySparkleParticle2.DrawVerticalAxis = false;
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle2);
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Utils.CenteredRectangle(), Terraria.Main.hslToRgb(), Terraria.Main.ParticleSystem_World_OverPlayers, and Terraria.Main.rand.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().