TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StellarTune
Spawn_StellarTune()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StellarTune (ParticleOrchestraSettings settings) inline static private
    {
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        float num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
        float num2 = 5f;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(0.7f);
        for (float num3 = 0f; num3 < 1f; num3 += 1f / num2)
        {
            float num4 = (float)Math.PI * 2f * num3 + num + Main.rand.NextFloatDirection() * 0.25f;
            Vector2 vector2 = 1.5f * vector;
            float num5 = 60f;
            Vector2 vector3 = Main.rand.NextVector2Circular(12f, 12f) * vector;
            Color colorTint = Color.Lerp(Color.Gold, Color.HotPink, Main.rand.NextFloat());
            if (Main.rand.Next(2) == 0)
            {
                colorTint = Color.Lerp(Color.Violet, Color.HotPink, Main.rand.NextFloat());
            }
            PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
            prettySparkleParticle.Velocity = num4.ToRotationVector2() * vector2;
            prettySparkleParticle.AccelerationPerFrame = num4.ToRotationVector2() * -(vector2 / num5);
            prettySparkleParticle.ColorTint = colorTint;
            prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector3;
            prettySparkleParticle.Rotation = num4;
            prettySparkleParticle.Scale = vector * (Main.rand.NextFloat() * 0.8f + 0.2f);
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
        }
        num2 = 1f;
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Main.rand, and Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle().
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().