TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPC
Spawn_ShimmerTownNPC()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPC (ParticleOrchestraSettings settings) inline static private
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_020d: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_0237: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_031a: Unknown result type (might be due to invalid IL or missing references)
        //IL_031f: Unknown result type (might be due to invalid IL or missing references)
        //IL_033d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0342: Unknown result type (might be due to invalid IL or missing references)
        Rectangle rectangle = Utils.CenteredRectangle(settings.PositionInWorld, new Vector2(30f, 60f));
        for (float num = 0f; num < 20f; num += 1f)
        {
            PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
            int num2 = Main.rand.Next(20, 40);
            prettySparkleParticle.ColorTint = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f, 0);
            prettySparkleParticle.LocalPosition = Main.rand.NextVector2FromRectangle(rectangle);
            prettySparkleParticle.Rotation = (float)Math.PI / 2f;
            prettySparkleParticle.Scale = new Vector2(1f + Main.rand.NextFloat() * 2f, 0.7f + Main.rand.NextFloat() * 0.7f);
            prettySparkleParticle.Velocity = new Vector2(0f, -1f);
            prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
            prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
            prettySparkleParticle.TimeToLive = num2;
            prettySparkleParticle.FadeOutEnd = num2;
            prettySparkleParticle.FadeInEnd = num2 / 2;
            prettySparkleParticle.FadeOutStart = num2 / 2;
            prettySparkleParticle.AdditiveAmount = 0.35f;
            prettySparkleParticle.DrawVerticalAxis = false;
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
            PrettySparkleParticle prettySparkleParticle2 = _poolPrettySparkle.RequestParticle();
            prettySparkleParticle2.ColorTint = new Color(255, 255, 255, 0);
            prettySparkleParticle2.LocalPosition = Main.rand.NextVector2FromRectangle(rectangle);
            prettySparkleParticle2.Rotation = (float)Math.PI / 2f;
            prettySparkleParticle2.Scale = prettySparkleParticle.Scale * 0.5f;
            prettySparkleParticle2.Velocity = new Vector2(0f, -1f);
            prettySparkleParticle2.FadeInNormalizedTime = 5E-06f;
            prettySparkleParticle2.FadeOutNormalizedTime = 0.95f;
            prettySparkleParticle2.TimeToLive = num2;
            prettySparkleParticle2.FadeOutEnd = num2;
            prettySparkleParticle2.FadeInEnd = num2 / 2;
            prettySparkleParticle2.FadeOutStart = num2 / 2;
            prettySparkleParticle2.AdditiveAmount = 1f;
            prettySparkleParticle2.DrawVerticalAxis = false;
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle2);
        }
        for (int i = 0; i < 20; i++)
        {
            int num3 = Dust.NewDust(rectangle.TopLeft(), rectangle.Width, rectangle.Height, 308);
            Main.dust[num3].velocity.Y -= 8f;
            Main.dust[num3].velocity.X *= 0.5f;
            Main.dust[num3].scale = 0.8f;
            Main.dust[num3].noGravity = true;
            switch (Main.rand.Next(6))
            {
            case 0:
                Main.dust[num3].color = new Color(255, 255, 210);
                break;
            case 1:
                Main.dust[num3].color = new Color(190, 245, 255);
                break;
            case 2:
                Main.dust[num3].color = new Color(255, 150, 255);
                break;
            default:
                Main.dust[num3].color = new Color(190, 175, 255);
                break;
            }
        }
        SoundEngine.PlaySound(in SoundID.Item29, settings.PositionInWorld);
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Utils.CenteredRectangle(), Terraria.Main.dust, Terraria.Main.hslToRgb(), Terraria.ID.SoundID.Item29, Terraria.Dust.NewDust(), Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.rand.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().