TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FlameWaders
Spawn_FlameWaders()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FlameWaders (ParticleOrchestraSettings settings) inline static private
Definition at line 2917 of file ParticleOrchestrator.cs.
    {
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_016f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        float num = 60f;
        for (int i = -1; i <= 1; i++)
        {
            int num2 = Main.rand.NextFromList(new short[3] { 326, 327, 328 });
            Main.instance.LoadProjectile(num2);
            Player player = Main.player[settings.IndexOfPlayerWhoInvokedThis];
            float num3 = Main.rand.NextFloat() * 0.9f + 0.1f;
            Vector2 vector = settings.PositionInWorld + new Vector2((float)i * 5.3333335f, 0f);
            FlameParticle flameParticle = _poolFlame.RequestParticle();
            flameParticle.SetBasicInfo(TextureAssets.Projectile[num2], null, Vector2.Zero, vector);
            flameParticle.SetTypeInfo(num, settings.IndexOfPlayerWhoInvokedThis, player.cFlameWaker);
            flameParticle.FadeOutNormalizedTime = 0.4f;
            flameParticle.ScaleAcceleration = Vector2.One * num3 * (-1f / 60f) / num;
            flameParticle.Scale = Vector2.One * num3;
            Main.ParticleSystem_World_BehindPlayers.Add(flameParticle);
            if (Main.rand.Next(16) == 0)
            {
                Dust dust = Dust.NewDustDirect(vector, 4, 4, 6, 0f, 0f, 100);
                if (Main.rand.Next(2) == 0)
                {
                    dust.noGravity = true;
                    dust.fadeIn = 1.15f;
                }
                else
                {
                    dust.scale = 0.6f;
                }
                dust.velocity *= 0.6f;
                dust.velocity.Y -= 1.2f;
                dust.noLight = true;
                dust.position.Y -= 4f;
                dust.shader = GameShaders.Armor.GetSecondaryShader(player.cFlameWaker, player);
            }
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolFlame, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.cFlameWaker, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), Terraria.Main.instance, Terraria.Main.LoadProjectile(), Terraria.Dust.NewDustDirect(), Terraria.Main.ParticleSystem_World_BehindPlayers, Terraria.Main.player, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.rand, and Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle().
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().