TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_AshTreeShake
Spawn_AshTreeShake()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_AshTreeShake (ParticleOrchestraSettings settings) inline static private
Definition at line 1436 of file ParticleOrchestrator.cs.
    {
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_0169: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01de: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        //IL_0268: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_027a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0281: Unknown result type (might be due to invalid IL or missing references)
        //IL_0299: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0302: Unknown result type (might be due to invalid IL or missing references)
        //IL_030c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0311: Unknown result type (might be due to invalid IL or missing references)
        //IL_0316: Unknown result type (might be due to invalid IL or missing references)
        //IL_031d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0324: Unknown result type (might be due to invalid IL or missing references)
        //IL_0329: Unknown result type (might be due to invalid IL or missing references)
        //IL_0342: Unknown result type (might be due to invalid IL or missing references)
        //IL_034c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0351: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_0363: Unknown result type (might be due to invalid IL or missing references)
        //IL_0368: Unknown result type (might be due to invalid IL or missing references)
        //IL_0370: Unknown result type (might be due to invalid IL or missing references)
        //IL_0377: Unknown result type (might be due to invalid IL or missing references)
        //IL_0381: Unknown result type (might be due to invalid IL or missing references)
        //IL_0386: Unknown result type (might be due to invalid IL or missing references)
        //IL_038b: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_040e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0414: Unknown result type (might be due to invalid IL or missing references)
        //IL_042f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0435: Unknown result type (might be due to invalid IL or missing references)
        //IL_0437: Unknown result type (might be due to invalid IL or missing references)
        //IL_043c: Unknown result type (might be due to invalid IL or missing references)
        //IL_044b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0458: Unknown result type (might be due to invalid IL or missing references)
        //IL_045e: Unknown result type (might be due to invalid IL or missing references)
        float num = 10f + 20f * Main.rand.NextFloat();
        float num2 = -(float)Math.PI / 4f;
        float num3 = 0.2f + 0.4f * Main.rand.NextFloat();
        Color colorTint = Main.hslToRgb(Main.rand.NextFloat() * 0.1f + 0.06f, 1f, 0.5f);
        ((Color)(ref colorTint)).A = (byte)(((Color)(ref colorTint)).A / 2);
        colorTint *= Main.rand.NextFloat() * 0.3f + 0.7f;
        for (float num4 = 0f; num4 < 2f; num4 += 1f)
        {
            PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
            Vector2 vector = ((float)Math.PI / 4f + (float)Math.PI * num4 + num2).ToRotationVector2() * 4f;
            prettySparkleParticle.ColorTint = colorTint;
            prettySparkleParticle.LocalPosition = settings.PositionInWorld;
            prettySparkleParticle.Rotation = vector.ToRotation();
            prettySparkleParticle.Scale = new Vector2(4f, 1f) * 1.1f * num3;
            prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
            prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
            prettySparkleParticle.TimeToLive = num;
            prettySparkleParticle.FadeOutEnd = num;
            prettySparkleParticle.FadeInEnd = num / 2f;
            prettySparkleParticle.FadeOutStart = num / 2f;
            prettySparkleParticle.AdditiveAmount = 0.35f;
            prettySparkleParticle.LocalPosition -= vector * num * 0.25f;
            prettySparkleParticle.Velocity = vector * 0.05f;
            prettySparkleParticle.DrawVerticalAxis = false;
            if (num4 == 1f)
            {
                prettySparkleParticle.Scale *= 1.5f;
                prettySparkleParticle.Velocity *= 1.5f;
                prettySparkleParticle.LocalPosition -= prettySparkleParticle.Velocity * 4f;
            }
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
        }
        for (float num5 = 0f; num5 < 2f; num5 += 1f)
        {
            PrettySparkleParticle prettySparkleParticle2 = _poolPrettySparkle.RequestParticle();
            Vector2 vector2 = ((float)Math.PI / 4f + (float)Math.PI * num5 + num2).ToRotationVector2() * 4f;
            prettySparkleParticle2.ColorTint = new Color(1f, 0.4f, 0.2f, 1f);
            prettySparkleParticle2.LocalPosition = settings.PositionInWorld;
            prettySparkleParticle2.Rotation = vector2.ToRotation();
            prettySparkleParticle2.Scale = new Vector2(4f, 1f) * 0.7f * num3;
            prettySparkleParticle2.FadeInNormalizedTime = 5E-06f;
            prettySparkleParticle2.FadeOutNormalizedTime = 0.95f;
            prettySparkleParticle2.TimeToLive = num;
            prettySparkleParticle2.FadeOutEnd = num;
            prettySparkleParticle2.FadeInEnd = num / 2f;
            prettySparkleParticle2.FadeOutStart = num / 2f;
            prettySparkleParticle2.LocalPosition -= vector2 * num * 0.25f;
            prettySparkleParticle2.Velocity = vector2 * 0.05f;
            prettySparkleParticle2.DrawVerticalAxis = false;
            if (num5 == 1f)
            {
                prettySparkleParticle2.Scale *= 1.5f;
                prettySparkleParticle2.Velocity *= 1.5f;
                prettySparkleParticle2.LocalPosition -= prettySparkleParticle2.Velocity * 4f;
            }
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle2);
            for (int i = 0; i < 1; i++)
            {
                Dust dust = Dust.NewDustPerfect(settings.PositionInWorld, 6, vector2.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                dust.noGravity = true;
                dust.scale = 1.4f;
                Dust dust2 = Dust.NewDustPerfect(settings.PositionInWorld, 6, -vector2.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                dust2.noGravity = true;
                dust2.scale = 1.4f;
            }
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Main.hslToRgb(), Terraria.Dust.NewDustPerfect(), Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Main.rand, and Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle().
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().