TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Keybrand
Spawn_Keybrand()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Keybrand (ParticleOrchestraSettings settings) inline static private
Definition at line 2743 of file ParticleOrchestrator.cs.
    {
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_0181: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0202: Unknown result type (might be due to invalid IL or missing references)
        //IL_0207: Unknown result type (might be due to invalid IL or missing references)
        //IL_021e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_0225: Unknown result type (might be due to invalid IL or missing references)
        //IL_022a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0233: Unknown result type (might be due to invalid IL or missing references)
        //IL_0238: Unknown result type (might be due to invalid IL or missing references)
        //IL_023c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_0246: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_0254: Unknown result type (might be due to invalid IL or missing references)
        //IL_025c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_0268: Unknown result type (might be due to invalid IL or missing references)
        //IL_026a: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_0277: Unknown result type (might be due to invalid IL or missing references)
        //IL_0281: Unknown result type (might be due to invalid IL or missing references)
        //IL_0286: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_028d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0292: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02da: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_0352: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_0371: Unknown result type (might be due to invalid IL or missing references)
        //IL_0376: Unknown result type (might be due to invalid IL or missing references)
        //IL_0377: Unknown result type (might be due to invalid IL or missing references)
        //IL_037c: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0392: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03db: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_041f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0424: Unknown result type (might be due to invalid IL or missing references)
        //IL_0425: Unknown result type (might be due to invalid IL or missing references)
        //IL_042a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0431: Unknown result type (might be due to invalid IL or missing references)
        //IL_0438: Unknown result type (might be due to invalid IL or missing references)
        //IL_0442: Unknown result type (might be due to invalid IL or missing references)
        //IL_0447: Unknown result type (might be due to invalid IL or missing references)
        //IL_044e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0455: Unknown result type (might be due to invalid IL or missing references)
        //IL_045f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0464: Unknown result type (might be due to invalid IL or missing references)
        float num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
        float num3 = 3f;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(0.7f);
        for (float num4 = 0f; num4 < 1f; num4 += 1f / num3)
        {
            float num5 = (float)Math.PI * 2f * num4 + num + Main.rand.NextFloatDirection() * 0.1f;
            Vector2 vector2 = 1.5f * vector;
            float num6 = 60f;
            Vector2 vector3 = Main.rand.NextVector2Circular(4f, 4f) * vector;
            PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
            prettySparkleParticle.Velocity = num5.ToRotationVector2() * vector2;
            prettySparkleParticle.AccelerationPerFrame = num5.ToRotationVector2() * -(vector2 / num6);
            prettySparkleParticle.ColorTint = Color.Lerp(Color.Gold, Color.OrangeRed, Main.rand.NextFloat());
            prettySparkleParticle.LocalPosition = settings.PositionInWorld + vector3;
            prettySparkleParticle.Rotation = num5;
            prettySparkleParticle.Scale = vector * 0.8f;
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
        }
        num += 1f / num3 / 2f * ((float)Math.PI * 2f);
        num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
        for (float num7 = 0f; num7 < 1f; num7 += 1f / num3)
        {
            float num8 = (float)Math.PI * 2f * num7 + num + Main.rand.NextFloatDirection() * 0.1f;
            Vector2 vector4 = 1f * vector;
            float num9 = 30f;
            Color value = Color.Lerp(Color.Gold, Color.OrangeRed, Main.rand.NextFloat());
            value = Color.Lerp(Color.White, value, 0.5f);
            ((Color)(ref value)).A = 0;
            Vector2 vector5 = Main.rand.NextVector2Circular(4f, 4f) * vector;
            FadingParticle fadingParticle = _poolFading.RequestParticle();
            fadingParticle.SetBasicInfo(TextureAssets.Extra[98], null, Vector2.Zero, Vector2.Zero);
            fadingParticle.SetTypeInfo(num9);
            fadingParticle.Velocity = num8.ToRotationVector2() * vector4;
            fadingParticle.AccelerationPerFrame = num8.ToRotationVector2() * -(vector4 / num9);
            fadingParticle.ColorTint = value;
            fadingParticle.LocalPosition = settings.PositionInWorld + num8.ToRotationVector2() * vector4 * vector * num9 * 0.2f + vector5;
            fadingParticle.Rotation = num8 + (float)Math.PI / 2f;
            fadingParticle.FadeInNormalizedTime = 0.3f;
            fadingParticle.FadeOutNormalizedTime = 0.4f;
            fadingParticle.Scale = new Vector2(0.5f, 1.2f) * 0.8f * vector;
            Main.ParticleSystem_World_OverPlayers.Add(fadingParticle);
        }
        num3 = 1f;
        num = Main.rand.NextFloat() * ((float)Math.PI * 2f);
        for (float num10 = 0f; num10 < 1f; num10 += 1f / num3)
        {
            float num2 = (float)Math.PI * 2f * num10 + num;
            float typeInfo = 30f;
            Color colorTint = Color.Lerp(Color.CornflowerBlue, Color.White, Main.rand.NextFloat());
            ((Color)(ref colorTint)).A = 127;
            Vector2 vector6 = Main.rand.NextVector2Circular(4f, 4f) * vector;
            Vector2 vector7 = Main.rand.NextVector2Square(0.7f, 1.3f);
            FadingParticle fadingParticle2 = _poolFading.RequestParticle();
            fadingParticle2.SetBasicInfo(TextureAssets.Extra[174], null, Vector2.Zero, Vector2.Zero);
            fadingParticle2.SetTypeInfo(typeInfo);
            fadingParticle2.ColorTint = colorTint;
            fadingParticle2.LocalPosition = settings.PositionInWorld + vector6;
            fadingParticle2.Rotation = num2 + (float)Math.PI / 2f;
            fadingParticle2.FadeInNormalizedTime = 0.1f;
            fadingParticle2.FadeOutNormalizedTime = 0.4f;
            fadingParticle2.Scale = new Vector2(0.1f, 0.1f) * vector;
            fadingParticle2.ScaleVelocity = vector7 * 1f / 60f;
            fadingParticle2.ScaleAcceleration = vector7 * (-1f / 60f) / 60f;
            Main.ParticleSystem_World_OverPlayers.Add(fadingParticle2);
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolFading, Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.GameContent.TextureAssets.Extra, Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Main.rand, and Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle().
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().