TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TrueExcalibur
Spawn_TrueExcalibur()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_TrueExcalibur (ParticleOrchestraSettings settings) inline static private
Definition at line 1225 of file ParticleOrchestrator.cs.
    {
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        //IL_033a: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0364: Unknown result type (might be due to invalid IL or missing references)
        //IL_0369: Unknown result type (might be due to invalid IL or missing references)
        //IL_0370: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0225: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_023c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_024f: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0277: Unknown result type (might be due to invalid IL or missing references)
        //IL_0292: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_029f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_039e: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0404: Unknown result type (might be due to invalid IL or missing references)
        //IL_0406: Unknown result type (might be due to invalid IL or missing references)
        //IL_0410: Unknown result type (might be due to invalid IL or missing references)
        //IL_0415: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0434: Unknown result type (might be due to invalid IL or missing references)
        //IL_043e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0443: Unknown result type (might be due to invalid IL or missing references)
        //IL_044b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0455: Unknown result type (might be due to invalid IL or missing references)
        //IL_045a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0511: Unknown result type (might be due to invalid IL or missing references)
        //IL_051b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0520: Unknown result type (might be due to invalid IL or missing references)
        //IL_056b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0572: Unknown result type (might be due to invalid IL or missing references)
        //IL_0577: Unknown result type (might be due to invalid IL or missing references)
        //IL_0596: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_060b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0611: Unknown result type (might be due to invalid IL or missing references)
        //IL_0613: Unknown result type (might be due to invalid IL or missing references)
        //IL_0622: Unknown result type (might be due to invalid IL or missing references)
        //IL_062f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0635: Unknown result type (might be due to invalid IL or missing references)
        //IL_0653: Unknown result type (might be due to invalid IL or missing references)
        //IL_065d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0678: Unknown result type (might be due to invalid IL or missing references)
        //IL_067e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0680: Unknown result type (might be due to invalid IL or missing references)
        //IL_0685: Unknown result type (might be due to invalid IL or missing references)
        //IL_0694: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a7: Unknown result type (might be due to invalid IL or missing references)
        float num = 36f;
        float num2 = (float)Math.PI / 4f;
        for (float num3 = 0f; num3 < 2f; num3 += 1f)
        {
            PrettySparkleParticle prettySparkleParticle = _poolPrettySparkle.RequestParticle();
            Vector2 v = ((float)Math.PI / 2f * num3 + num2).ToRotationVector2() * 4f;
            prettySparkleParticle.ColorTint = new Color(1f, 0f, 0.3f, 1f);
            prettySparkleParticle.LocalPosition = settings.PositionInWorld;
            prettySparkleParticle.Rotation = v.ToRotation();
            prettySparkleParticle.Scale = new Vector2(5f, 0.5f) * 1.1f;
            prettySparkleParticle.FadeInNormalizedTime = 5E-06f;
            prettySparkleParticle.FadeOutNormalizedTime = 0.95f;
            prettySparkleParticle.TimeToLive = num;
            prettySparkleParticle.FadeOutEnd = num;
            prettySparkleParticle.FadeInEnd = num / 2f;
            prettySparkleParticle.FadeOutStart = num / 2f;
            prettySparkleParticle.AdditiveAmount = 0.35f;
            prettySparkleParticle.DrawVerticalAxis = false;
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle);
        }
        for (float num4 = 0f; num4 < 2f; num4 += 1f)
        {
            PrettySparkleParticle prettySparkleParticle2 = _poolPrettySparkle.RequestParticle();
            Vector2 vector = ((float)Math.PI / 2f * num4 + num2).ToRotationVector2() * 4f;
            prettySparkleParticle2.ColorTint = new Color(1f, 0.5f, 0.8f, 1f);
            prettySparkleParticle2.LocalPosition = settings.PositionInWorld;
            prettySparkleParticle2.Rotation = vector.ToRotation();
            prettySparkleParticle2.Scale = new Vector2(3f, 0.5f) * 0.7f;
            prettySparkleParticle2.FadeInNormalizedTime = 5E-06f;
            prettySparkleParticle2.FadeOutNormalizedTime = 0.95f;
            prettySparkleParticle2.TimeToLive = num;
            prettySparkleParticle2.FadeOutEnd = num;
            prettySparkleParticle2.FadeInEnd = num / 2f;
            prettySparkleParticle2.FadeOutStart = num / 2f;
            prettySparkleParticle2.DrawVerticalAxis = false;
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle2);
            for (int i = 0; i < 1; i++)
            {
                if (Main.rand.Next(2) != 0)
                {
                    Dust dust = Dust.NewDustPerfect(settings.PositionInWorld, 242, vector.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                    dust.noGravity = true;
                    dust.scale = 1.4f;
                    Dust dust2 = Dust.NewDustPerfect(settings.PositionInWorld, 242, -vector.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                    dust2.noGravity = true;
                    dust2.scale = 1.4f;
                }
            }
        }
        num = 30f;
        num2 = 0f;
        for (float num5 = 0f; num5 < 4f; num5 += 1f)
        {
            PrettySparkleParticle prettySparkleParticle3 = _poolPrettySparkle.RequestParticle();
            Vector2 vector2 = ((float)Math.PI / 2f * num5 + num2).ToRotationVector2() * 4f;
            prettySparkleParticle3.ColorTint = new Color(0.9f, 0.85f, 0.4f, 0.5f);
            prettySparkleParticle3.LocalPosition = settings.PositionInWorld;
            prettySparkleParticle3.Rotation = vector2.ToRotation();
            prettySparkleParticle3.Scale = new Vector2((num5 % 2f == 0f) ? 2f : 4f, 0.5f) * 1.1f;
            prettySparkleParticle3.FadeInNormalizedTime = 5E-06f;
            prettySparkleParticle3.FadeOutNormalizedTime = 0.95f;
            prettySparkleParticle3.TimeToLive = num;
            prettySparkleParticle3.FadeOutEnd = num;
            prettySparkleParticle3.FadeInEnd = num / 2f;
            prettySparkleParticle3.FadeOutStart = num / 2f;
            prettySparkleParticle3.AdditiveAmount = 0.35f;
            prettySparkleParticle3.Velocity = -vector2 * 0.2f;
            prettySparkleParticle3.DrawVerticalAxis = false;
            if (num5 % 2f == 1f)
            {
                prettySparkleParticle3.Scale *= 1.5f;
                prettySparkleParticle3.Velocity *= 1.5f;
            }
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle3);
        }
        for (float num6 = 0f; num6 < 4f; num6 += 1f)
        {
            PrettySparkleParticle prettySparkleParticle4 = _poolPrettySparkle.RequestParticle();
            Vector2 vector3 = ((float)Math.PI / 2f * num6 + num2).ToRotationVector2() * 4f;
            prettySparkleParticle4.ColorTint = new Color(1f, 1f, 0.2f, 1f);
            prettySparkleParticle4.LocalPosition = settings.PositionInWorld;
            prettySparkleParticle4.Rotation = vector3.ToRotation();
            prettySparkleParticle4.Scale = new Vector2((num6 % 2f == 0f) ? 2f : 4f, 0.5f) * 0.7f;
            prettySparkleParticle4.FadeInNormalizedTime = 5E-06f;
            prettySparkleParticle4.FadeOutNormalizedTime = 0.95f;
            prettySparkleParticle4.TimeToLive = num;
            prettySparkleParticle4.FadeOutEnd = num;
            prettySparkleParticle4.FadeInEnd = num / 2f;
            prettySparkleParticle4.FadeOutStart = num / 2f;
            prettySparkleParticle4.Velocity = vector3 * 0.2f;
            prettySparkleParticle4.DrawVerticalAxis = false;
            if (num6 % 2f == 1f)
            {
                prettySparkleParticle4.Scale *= 1.5f;
                prettySparkleParticle4.Velocity *= 1.5f;
            }
            Main.ParticleSystem_World_OverPlayers.Add(prettySparkleParticle4);
            for (int j = 0; j < 1; j++)
            {
                if (Main.rand.Next(2) != 0)
                {
                    Dust dust3 = Dust.NewDustPerfect(settings.PositionInWorld, 169, vector3.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                    dust3.noGravity = true;
                    dust3.scale = 1.4f;
                    Dust dust4 = Dust.NewDustPerfect(settings.PositionInWorld, 169, -vector3.RotatedBy(Main.rand.NextFloatDirection() * ((float)Math.PI * 2f) * 0.025f) * Main.rand.NextFloat());
                    dust4.noGravity = true;
                    dust4.scale = 1.4f;
                }
            }
        }
    }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolPrettySparkle, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.Dust.NewDustPerfect(), Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Main.rand, and Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle().
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().