TModLoader: Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Digestion
Spawn_Digestion()
static void Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Digestion (ParticleOrchestraSettings settings) inline static private
Definition at line 383 of file ParticleOrchestrator.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        Vector2 positionInWorld = settings.PositionInWorld;
        int num = ((settings.MovementVector.X < 0f) ? 1 : (-1));
        int num2 = Main.rand.Next(4);
        for (int i = 0; i < 3 + num2; i++)
        {
            int num3 = Dust.NewDust(positionInWorld + Vector2.UnitX * (float)(-num) * 8f - Vector2.One * 5f + Vector2.UnitY * 8f, 3, 6, 216, -num, 1f);
            Dust obj = Main.dust[num3];
            obj.velocity /= 2f;
            Main.dust[num3].scale = 0.8f;
        }
        if (Main.rand.Next(30) == 0)
        {
            int num4 = Gore.NewGore(positionInWorld + Vector2.UnitX * (float)(-num) * 8f, Vector2.Zero, Main.rand.Next(580, 583));
            Gore obj2 = Main.gore[num4];
            obj2.velocity /= 2f;
            Main.gore[num4].velocity.Y = Math.Abs(Main.gore[num4].velocity.Y);
            Main.gore[num4].velocity.X = (0f - Math.Abs(Main.gore[num4].velocity.X)) * (float)num;
        }
        SoundEngine.PlaySound(in SoundID.Item16, settings.PositionInWorld);
    }
References Terraria.Main.dust, Terraria.Main.gore, Terraria.ID.SoundID.Item16, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Dust.scale, and Terraria.Gore.velocity.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnParticlesDirect().