TModLoader: Terraria.ModLoader.UI.UIUpdateMessage.OnInitialize
OnInitialize()
override void Terraria.ModLoader.UI.UIUpdateMessage.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 31 of file UIUpdateMessage.cs.
    {
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0118: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_0207: Unknown result type (might be due to invalid IL or missing references)
        //IL_020d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        _area = new UIElement
        {
            Width =
            {
                Percent = 0.8f
            },
            Top =
            {
                Pixels = 200f
            },
            Height =
            {
                Pixels = -240f,
                Percent = 1f
            },
            HAlign = 0.5f
        };
        _message.Width.Percent = 1f;
        _message.Height.Percent = 0.8f;
        _message.HAlign = 0.5f;
        _area.Append(_message);
        UITextPanel<string> button = new UITextPanel<string>("Ignore", 0.7f, large: true)
        {
            Width =
            {
                Pixels = -10f,
                Percent = 1f / 3f
            },
            Height =
            {
                Pixels = 50f
            },
            VAlign = 1f,
            Top =
            {
                Pixels = -30f
            }
        };
        button.WithFadedMouseOver();
        button.OnLeftClick += IgnoreClick;
        _area.Append(button);
        UITextPanel<string> button2 = new UITextPanel<string>("Download", 0.7f, large: true);
        button2.CopyStyle(button);
        button2.HAlign = 0.5f;
        button2.WithFadedMouseOver();
        button2.OnLeftClick += OpenURL;
        _area.Append(button2);
        if (Platform.IsWindows && SocialAPI.Mode != SocialMode.Steam)
        {
            _autoUpdateButton = new UITextPanel<string>("Auto Update", 0.7f, large: true);
            _autoUpdateButton.CopyStyle(button);
            _autoUpdateButton.HAlign = 1f;
            _autoUpdateButton.WithFadedMouseOver();
            _autoUpdateButton.OnLeftClick += AutoUpdate;
        }
        Append(_area);
    }
References Terraria.ModLoader.UI.UIUpdateMessage._area, Terraria.ModLoader.UI.UIUpdateMessage._autoUpdateButton, Terraria.ModLoader.UI.UIUpdateMessage._message, Terraria.UI.UIElement.Append(), Terraria.ModLoader.UI.UIUpdateMessage.AutoUpdate(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.ModLoader.UI.UIUpdateMessage.IgnoreClick(), Terraria.Social.SocialAPI.Mode, Terraria.ModLoader.UI.UIUpdateMessage.OpenURL(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.