TModLoader: Terraria.ModLoader.AccessorySlotLoader.DrawVisibility
DrawVisibility()
bool Terraria.ModLoader.AccessorySlotLoader.DrawVisibility (ref bool visbility, int context, int xLoc, int yLoc, out int xLoc2, out int yLoc2, out Texture2D value4) inline package
Is run in AccessorySlotLoader.Draw. Creates & sets up Hide Visibility Button.
    {
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        yLoc2 = yLoc - 2;
        xLoc2 = xLoc - 58 + 64 + 28;
        value4 = TextureAssets.InventoryTickOn.Value;
        if (visbility)
        {
            value4 = TextureAssets.InventoryTickOff.Value;
        }
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector(xLoc2, yLoc2, value4.Width, value4.Height);
        int num45 = 0;
        bool skipCheck = false;
        if (((Rectangle)(ref rectangle)).Contains(new Point(Main.mouseX, Main.mouseY)) && !PlayerInput.IgnoreMouseInterface)
        {
            skipCheck = true;
            Player.mouseInterface = true;
            if (Main.mouseLeft && Main.mouseLeftRelease)
            {
                visbility = !visbility;
                SoundEngine.PlaySound(12);
                if (Main.netMode == 1 && context > 0)
                {
                    NetMessage.SendData(4, -1, -1, null, Player.whoAmI);
                }
            }
            num45 = ((!visbility) ? 1 : 2);
        }
        if (num45 > 0)
        {
            Main.HoverItem = new Item();
            Main.hoverItemName = Lang.inter[58 + num45].Value;
        }
        return skipCheck;
    }
References Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Lang.inter, Terraria.GameContent.TextureAssets.InventoryTickOff, Terraria.GameContent.TextureAssets.InventoryTickOn, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.netMode, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), Terraria.Localization.LocalizedText.Value, and Terraria.Entity.whoAmI.
Referenced by Terraria.ModLoader.AccessorySlotLoader.Draw().