TModLoader: Terraria.ModLoader.AccessorySlotLoader.DrawScrollbar
DrawScrollbar()
void Terraria.ModLoader.AccessorySlotLoader.DrawScrollbar (int accessoryPerColumn, int slotsToRender, int scrollIncrement) inline package
    {
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        int xLoc = Main.screenWidth - 64 - 28;
        int chkMax = (int)((float)DrawVerticalAlignment + (float)((accessoryPerColumn + 3) * 56) * Main.inventoryScale) + 4;
        int chkMin = (int)((float)DrawVerticalAlignment + 168f * Main.inventoryScale) + 4;
        UIScrollbar uIScrollbar = new UIScrollbar();
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector(xLoc + 47 + 6, chkMin, 5, chkMax - chkMin);
        uIScrollbar.DrawBar(Main.spriteBatch, Main.Assets.Request<Texture2D>("Images/UI/Scrollbar").Value, rectangle, Color.White);
        int barSize = (chkMax - chkMin) / (scrollIncrement + 1);
        ((Rectangle)(ref rectangle))._002Ector(xLoc + 47 + 5, chkMin + ModSlotPlayer(Player).scrollbarSlotPosition * barSize, 3, barSize);
        uIScrollbar.DrawBar(Main.spriteBatch, Main.Assets.Request<Texture2D>("Images/UI/ScrollbarInner").Value, rectangle, Color.White);
        ((Rectangle)(ref rectangle))._002Ector(xLoc - 94, chkMin, 141, chkMax - chkMin);
        if (((Rectangle)(ref rectangle)).Contains(new Point(Main.mouseX, Main.mouseY)) && !PlayerInput.IgnoreMouseInterface)
        {
            PlayerInput.LockVanillaMouseScroll("ModLoader/Acc");
            int scrollDelta = ModSlotPlayer(Player).scrollbarSlotPosition + PlayerInput.ScrollWheelDelta / 120;
            scrollDelta = Math.Min(scrollDelta, scrollIncrement);
            scrollDelta = Math.Max(scrollDelta, 0);
            ModSlotPlayer(Player).scrollbarSlotPosition = scrollDelta;
            PlayerInput.ScrollWheelDelta = 0;
        }
    }
References Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UIScrollbar.DrawBar(), Terraria.ModLoader.AccessorySlotLoader.DrawVerticalAlignment, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.inventoryScale, Terraria.GameInput.PlayerInput.LockVanillaMouseScroll(), Terraria.ModLoader.AccessorySlotLoader.ModSlotPlayer(), Terraria.Main.mouseX, Terraria.Main.mouseY, and Terraria.Main.spriteBatch.
Referenced by Terraria.ModLoader.AccessorySlotLoader.DrawAccSlots().