TModLoader: Terraria.ModLoader.AccessorySlotLoader.DrawSlot
DrawSlot()
void Terraria.ModLoader.AccessorySlotLoader.DrawSlot (Item[] items, int context, int slot, bool flag3, int xLoc, int yLoc, bool skipCheck = false) inline package
Is run in AccessorySlotLoader.Draw. Generates a significant amount of functionality for the slot, despite being named drawing because vanilla. At the end, calls this.DrawRedirect to enable custom drawing.
Definition at line 395 of file AccessorySlotLoader.cs.
    {
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        bool flag4 = flag3 && !Main.mouseItem.IsAir;
        int xLoc2 = xLoc - 47 * slotDrawLoopCounter++;
        bool isHovered = false;
        if (!skipCheck && Main.mouseX >= xLoc2 && (float)Main.mouseX <= (float)xLoc2 + (float)TextureAssets.InventoryBack.Width() * Main.inventoryScale && Main.mouseY >= yLoc && (float)Main.mouseY <= (float)yLoc + (float)TextureAssets.InventoryBack.Height() * Main.inventoryScale && !PlayerInput.IgnoreMouseInterface)
        {
            isHovered = true;
            Player.mouseInterface = true;
            Main.armorHide = true;
            ItemSlot.OverrideHover(items, Math.Abs(context), slot);
            if (!flag4)
            {
                if (Math.Abs(context) == 12)
                {
                    if (Main.mouseRightRelease && Main.mouseRight)
                    {
                        ItemSlot.RightClick(items, context, slot);
                    }
                    ItemSlot.LeftClick(items, context, slot);
                }
                else if (Math.Abs(context) == 11)
                {
                    ItemSlot.LeftClick(items, context, slot);
                    ItemSlot.RightClick(items, context, slot);
                }
                else if (Math.Abs(context) == 10)
                {
                    ItemSlot.LeftClick(items, context, slot);
                }
            }
            ItemSlot.MouseHover(items, Math.Abs(context), slot);
            if (context < 0)
            {
                OnHover(slot, context);
            }
        }
        DrawRedirect(items, context, slot, new Vector2((float)xLoc2, (float)yLoc), isHovered);
    }
References Terraria.ModLoader.AccessorySlotLoader.DrawRedirect(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.Main.inventoryScale, Terraria.Item.IsAir, Terraria.UI.ItemSlot.LeftClick(), Terraria.UI.ItemSlot.MouseHover(), Terraria.Main.mouseItem, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.ModLoader.AccessorySlotLoader.OnHover(), Terraria.UI.ItemSlot.OverrideHover(), Terraria.UI.ItemSlot.RightClick(), and Terraria.ModLoader.AccessorySlotLoader.slotDrawLoopCounter.
Referenced by Terraria.ModLoader.AccessorySlotLoader.Draw().