TModLoader: Terraria.ModLoader.AccessorySlotLoader.Draw
Draw()
bool Terraria.ModLoader.AccessorySlotLoader.Draw (int skip, bool modded, int slot, Color color) inline
Draws Vanilla and Modded Accessory Slots.
    {
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_026a: Unknown result type (might be due to invalid IL or missing references)
        //IL_026c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_0253: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        bool flag4 = false;
        bool flag3;
        if (modded)
        {
            flag3 = !ModdedIsItemSlotUnlockedAndUsable(slot, Player);
            flag4 = !ModdedCanSlotBeShown(slot);
        }
        else
        {
            flag3 = !Player.IsItemSlotUnlockedAndUsable(slot);
            switch (slot)
            {
            case 8:
                flag4 = slot == 8 && !Player.CanDemonHeartAccessoryBeShown();
                break;
            case 9:
                flag4 = !Player.CanMasterModeAccessoryBeShown();
                break;
            }
        }
        if ((flag4 && flag3) || (modded && IsHidden(slot)))
        {
            return false;
        }
        Main.inventoryBack = (Color)(flag3 ? new Color(80, 80, 80, 80) : color);
        slotDrawLoopCounter = 0;
        int yLoc = 0;
        int xLoc = 0;
        bool customLoc = false;
        if (modded)
        {
            ModAccessorySlot mAccSlot = Get(slot);
            customLoc = mAccSlot.CustomLocation.HasValue;
            if (!customLoc && Main.EquipPage != 0)
            {
                Main.inventoryBack = color;
                return false;
            }
            if (customLoc)
            {
                xLoc = (int)(mAccSlot.CustomLocation?.X).Value;
                yLoc = (int)(mAccSlot.CustomLocation?.Y).Value;
            }
            else if (!SetDrawLocation(slot + Player.dye.Length - 3, skip, ref xLoc, ref yLoc))
            {
                Main.inventoryBack = color;
                return true;
            }
            ModAccessorySlot modAccessorySlot = Get(slot);
            if (modAccessorySlot.DrawFunctionalSlot)
            {
                DrawSlot(skipCheck: DrawVisibility(ref ModSlotPlayer(Player).exHideAccessory[slot], -10, xLoc, yLoc, out var xLoc2, out var yLoc2, out var value4), items: ModSlotPlayer(Player).exAccessorySlot, context: -10, slot: slot, flag3: flag3, xLoc: xLoc, yLoc: yLoc);
                Main.spriteBatch.Draw(value4, new Vector2((float)xLoc2, (float)yLoc2), Color.White * 0.7f);
            }
            if (modAccessorySlot.DrawVanitySlot)
            {
                DrawSlot(ModSlotPlayer(Player).exAccessorySlot, -11, slot + ModSlotPlayer(Player).SlotCount, flag3, xLoc, yLoc);
            }
            if (modAccessorySlot.DrawDyeSlot)
            {
                DrawSlot(ModSlotPlayer(Player).exDyesAccessory, -12, slot, flag3, xLoc, yLoc);
            }
        }
        else
        {
            if (!customLoc && Main.EquipPage != 0)
            {
                Main.inventoryBack = color;
                return false;
            }
            if (!SetDrawLocation(slot - 3, skip, ref xLoc, ref yLoc))
            {
                Main.inventoryBack = color;
                return true;
            }
            int xLoc3;
            int yLoc3;
            Texture2D value5;
            bool skipMouse = DrawVisibility(ref Player.hideVisibleAccessory[slot], 10, xLoc, yLoc, out xLoc3, out yLoc3, out value5);
            DrawSlot(Player.armor, 10, slot, flag3, xLoc, yLoc, skipMouse);
            Main.spriteBatch.Draw(value5, new Vector2((float)xLoc3, (float)yLoc3), Color.White * 0.7f);
            DrawSlot(Player.armor, 11, slot + Player.dye.Length, flag3, xLoc, yLoc);
            DrawSlot(Player.dye, 12, slot, flag3, xLoc, yLoc);
        }
        Main.inventoryBack = color;
        return !customLoc;
    }
References Terraria.Player.armor, Terraria.Player.CanDemonHeartAccessoryBeShown(), Terraria.Player.CanMasterModeAccessoryBeShown(), Terraria.ModLoader.AccessorySlotLoader.DrawSlot(), Terraria.ModLoader.AccessorySlotLoader.DrawVisibility(), Terraria.Player.dye, Terraria.Main.EquipPage, Terraria.ModLoader.AccessorySlotLoader.Get(), Terraria.Player.hideVisibleAccessory, Terraria.ModLoader.AccessorySlotLoader.IsHidden(), Terraria.Player.IsItemSlotUnlockedAndUsable(), Terraria.ModLoader.AccessorySlotLoader.ModdedCanSlotBeShown(), Terraria.ModLoader.AccessorySlotLoader.ModdedIsItemSlotUnlockedAndUsable(), Terraria.ModLoader.AccessorySlotLoader.ModSlotPlayer(), Terraria.ModLoader.AccessorySlotLoader.SetDrawLocation(), Terraria.ModLoader.AccessorySlotLoader.slotDrawLoopCounter, and Terraria.Main.spriteBatch.
Referenced by Terraria.ModLoader.AccessorySlotLoader.DrawAccSlots().