TModLoader: Terraria.ModLoader.AccessorySlotLoader.ModifyDefaultSwapSlot
ModifyDefaultSwapSlot()
void Terraria.ModLoader.AccessorySlotLoader.ModifyDefaultSwapSlot (Item item, ref int accSlotToSwapTo) inline
After checking for empty slots in ItemSlot.AccessorySwap, this allows for changing what the target slot will be if the accessory isn't already equipped. DOES NOT affect vanilla behavior of swapping items like for like where existing in a slot.
    {
        for (int num = ModSlotPlayer(Player).SlotCount - 1; num >= 0; num--)
        {
            if (ModdedIsItemSlotUnlockedAndUsable(num, Player) && Get(num).ModifyDefaultSwapSlot(item, accSlotToSwapTo))
            {
                accSlotToSwapTo = num + 20;
            }
        }
    }
References Terraria.ModLoader.AccessorySlotLoader.Get(), Terraria.ModLoader.AccessorySlotLoader.ModdedIsItemSlotUnlockedAndUsable(), Terraria.ModLoader.AccessorySlotLoader.ModifyDefaultSwapSlot(), and Terraria.ModLoader.AccessorySlotLoader.ModSlotPlayer().
Referenced by Terraria.ModLoader.AccessorySlotLoader.ModifyDefaultSwapSlot().