TModLoader: Terraria.ModLoader.AccessorySlotLoader.SetDrawLocation
SetDrawLocation()
bool Terraria.ModLoader.AccessorySlotLoader.SetDrawLocation (int trueSlot, int skip, ref int xLoc, ref int yLoc) inline package
Applies Xloc and Yloc data for the slot, based on ModAccessorySlotPlayer.scrollSlots.
    {
        int accessoryPerColumn = GetAccessorySlotPerColumn();
        int xColumn = trueSlot / accessoryPerColumn;
        int yRow = trueSlot % accessoryPerColumn;
        if (ModSlotPlayer(Player).scrollSlots)
        {
            int row = yRow + xColumn * accessoryPerColumn - ModSlotPlayer(Player).scrollbarSlotPosition - skip;
            yLoc = (int)((float)DrawVerticalAlignment + (float)((row + 3) * 56) * Main.inventoryScale) + 4;
            int chkMin = (int)((float)DrawVerticalAlignment + 168f * Main.inventoryScale) + 4;
            int chkMax = (int)((float)DrawVerticalAlignment + (float)((accessoryPerColumn - 1 + 3) * 56) * Main.inventoryScale) + 4;
            if (yLoc > chkMax || yLoc < chkMin)
            {
                return false;
            }
            xLoc = Main.screenWidth - 64 - 28;
        }
        else
        {
            int row2 = yRow;
            int tempSlot = trueSlot;
            int col = xColumn;
            if (skip > 0)
            {
                tempSlot -= skip;
                row2 = tempSlot % accessoryPerColumn;
                col = tempSlot / accessoryPerColumn;
            }
            yLoc = (int)((float)DrawVerticalAlignment + (float)((row2 + 3) * 56) * Main.inventoryScale) + 4;
            if (col > 0)
            {
                xLoc = Main.screenWidth - 64 - 28 - 141 * col - 50;
            }
            else
            {
                xLoc = Main.screenWidth - 64 - 28 - 141 * col;
            }
        }
        return true;
    }
References Terraria.ModLoader.AccessorySlotLoader.DrawVerticalAlignment, Terraria.ModLoader.AccessorySlotLoader.GetAccessorySlotPerColumn(), Terraria.Main.inventoryScale, and Terraria.ModLoader.AccessorySlotLoader.ModSlotPlayer().
Referenced by Terraria.ModLoader.AccessorySlotLoader.Draw().