TModLoader: Terraria.ModLoader.Engine.LogArchiver.ArchiveLogs
ArchiveLogs()
static void Terraria.ModLoader.Engine.LogArchiver.ArchiveLogs () inline static package
Attempt archiving logs.
Definition at line 28 of file LogArchiver.cs.
    {
        SetupLogDirs();
        MoveZipsToArchiveDir();
        Archive();
        DeleteOldArchives();
    }
References Terraria.ModLoader.Engine.LogArchiver.Archive(), Terraria.ModLoader.Engine.LogArchiver.DeleteOldArchives(), Terraria.ModLoader.Engine.LogArchiver.MoveZipsToArchiveDir(), and Terraria.ModLoader.Engine.LogArchiver.SetupLogDirs().
Referenced by Terraria.ModLoader.Logging.LogStartup().