TModLoader: Terraria.ModLoader.AccessorySlotLoader.DrawScrollSwitch
DrawScrollSwitch()
void Terraria.ModLoader.AccessorySlotLoader.DrawScrollSwitch () inline package
    {
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        Texture2D value4 = TextureAssets.InventoryTickOn.Value;
        if (ModSlotPlayer(Player).scrollSlots)
        {
            value4 = TextureAssets.InventoryTickOff.Value;
        }
        int xLoc2 = Main.screenWidth - 64 - 28 + 47 + 9;
        int yLoc2 = (int)((float)DrawVerticalAlignment + 168f * Main.inventoryScale) - 10;
        Main.spriteBatch.Draw(value4, new Vector2((float)xLoc2, (float)yLoc2), Color.White * 0.7f);
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector(xLoc2, yLoc2, value4.Width, value4.Height);
        if (((Rectangle)(ref rectangle)).Contains(new Point(Main.mouseX, Main.mouseY)) && !PlayerInput.IgnoreMouseInterface)
        {
            Main.LocalPlayer.mouseInterface = true;
            if (Main.mouseLeft && Main.mouseLeftRelease)
            {
                ModSlotPlayer(Player).scrollSlots = !ModSlotPlayer(Player).scrollSlots;
                SoundEngine.PlaySound(12);
            }
            int num45 = (ModSlotPlayer(Player).scrollSlots ? 1 : 0);
            Main.HoverItem = new Item();
            Main.hoverItemName = scrollStackLang[num45];
        }
    }
References Terraria.ModLoader.AccessorySlotLoader.DrawVerticalAlignment, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.inventoryScale, Terraria.GameContent.TextureAssets.InventoryTickOff, Terraria.GameContent.TextureAssets.InventoryTickOn, Terraria.ModLoader.AccessorySlotLoader.ModSlotPlayer(), Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Audio.SoundEngine.PlaySound(), Terraria.ModLoader.Default.ModAccessorySlotPlayer.scrollSlots, Terraria.ModLoader.AccessorySlotLoader.scrollStackLang, and Terraria.Main.spriteBatch.
Referenced by Terraria.ModLoader.AccessorySlotLoader.DrawAccSlots().