TModLoader: Terraria.Audio.ActiveSound.Update
Update()
void Terraria.Audio.ActiveSound.Update () inline
    {
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        if (Sound == null)
        {
            return;
        }
        if (!Program.IsMainThread)
        {
            RunOnMainThreadAndWait(Update);
        }
        else
        {
            if (Sound.IsDisposed)
            {
                return;
            }
            SoundUpdateCallback? callback = Callback;
            if (callback != null && !callback(this))
            {
                Sound.Stop(true);
                return;
            }
            Vector2 value = Main.screenPosition + new Vector2((float)(Main.screenWidth / 2), (float)(Main.screenHeight / 2));
            float num = 1f;
            if (Position.HasValue)
            {
                float value2 = (Position.Value.X - value.X) / ((float)Main.screenWidth * 0.5f);
                value2 = MathHelper.Clamp(value2, -1f, 1f);
                Sound.Pan = value2;
                float num2 = Vector2.Distance(Position.Value, value);
                num = 1f - num2 / ((float)Main.screenWidth * 1.5f);
            }
            num *= Style.Volume * Volume;
            switch (Style.Type)
            {
            case SoundType.Sound:
                num *= Main.soundVolume;
                break;
            case SoundType.Ambient:
                num *= Main.ambientVolume;
                if (Main.gameInactive)
                {
                    num = 0f;
                }
                break;
            case SoundType.Music:
                num *= Main.musicVolume;
                break;
            }
            num = MathHelper.Clamp(num, 0f, 1f);
            Sound.Volume = num;
            Sound.Pitch = Pitch;
        }
    }
References Terraria.Main.ambientVolume, Terraria.Audio.ActiveSound.Callback, Terraria.Main.gameInactive, Terraria.Program.IsMainThread, Terraria.Main.musicVolume, Terraria.Audio.ActiveSound.Pitch, Terraria.Audio.ActiveSound.Position, Terraria.Audio.ActiveSound.RunOnMainThreadAndWait(), Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Audio.ActiveSound.Sound, Terraria.Audio.SoundUpdateCallback(), Terraria.Main.soundVolume, Terraria.Audio.ActiveSound.Style, Terraria.Audio.SoundStyle.Type, Terraria.Audio.ActiveSound.Update(), and Terraria.Audio.ActiveSound.Volume.
Referenced by Terraria.Audio.ActiveSound.Play(), and Terraria.Audio.ActiveSound.Update().