TModLoader: Terraria.Audio.ActiveSound.Stop
Stop()
void Terraria.Audio.ActiveSound.Stop () inline
Definition at line 63 of file ActiveSound.cs.
    {
        if (!Program.IsMainThread)
        {
            RunOnMainThreadAndWait(Stop);
        }
        else if (Sound != null)
        {
            Sound.Stop();
        }
    }
References Terraria.Program.IsMainThread, Terraria.Audio.ActiveSound.RunOnMainThreadAndWait(), Terraria.Audio.ActiveSound.Sound, and Terraria.Audio.ActiveSound.Stop().
Referenced by Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.Projectile.Kill(), and Terraria.Audio.ActiveSound.Stop().