TModLoader: Terraria.Lighting.GetCornerColors
GetCornerColors()
static void Terraria.Lighting.GetCornerColors (int centerX, int centerY, out VertexColors vertices, float scale = 1f) inline static
Definition at line 432 of file Lighting.cs.
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_023f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0245: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0254: Unknown result type (might be due to invalid IL or missing references)
        //IL_0261: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0276: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0301: Unknown result type (might be due to invalid IL or missing references)
        //IL_0309: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_031d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0323: Unknown result type (might be due to invalid IL or missing references)
        //IL_032b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0332: Unknown result type (might be due to invalid IL or missing references)
        vertices = default(VertexColors);
        Vector3 color = _activeEngine.GetColor(centerX, centerY);
        Vector3 color9 = _activeEngine.GetColor(centerX, centerY - 1);
        Vector3 color2 = _activeEngine.GetColor(centerX, centerY + 1);
        Vector3 color3 = _activeEngine.GetColor(centerX - 1, centerY);
        Vector3 color4 = _activeEngine.GetColor(centerX + 1, centerY);
        Vector3 color5 = _activeEngine.GetColor(centerX - 1, centerY - 1);
        Vector3 color6 = _activeEngine.GetColor(centerX + 1, centerY - 1);
        Vector3 color7 = _activeEngine.GetColor(centerX - 1, centerY + 1);
        Vector3 color8 = _activeEngine.GetColor(centerX + 1, centerY + 1);
        float num = GlobalBrightness * scale * 63.75f;
        int num2 = (int)((color9.X + color5.X + color3.X + color.X) * num);
        int num3 = (int)((color9.Y + color5.Y + color3.Y + color.Y) * num);
        int num4 = (int)((color9.Z + color5.Z + color3.Z + color.Z) * num);
        if (num2 > 255)
        {
            num2 = 255;
        }
        if (num3 > 255)
        {
            num3 = 255;
        }
        if (num4 > 255)
        {
            num4 = 255;
        }
        num3 <<= 8;
        num4 <<= 16;
        ((Color)(ref vertices.TopLeftColor)).PackedValue = (uint)(num2 | num3 | num4) | 0xFF000000u;
        num2 = (int)((color9.X + color6.X + color4.X + color.X) * num);
        num3 = (int)((color9.Y + color6.Y + color4.Y + color.Y) * num);
        num4 = (int)((color9.Z + color6.Z + color4.Z + color.Z) * num);
        if (num2 > 255)
        {
            num2 = 255;
        }
        if (num3 > 255)
        {
            num3 = 255;
        }
        if (num4 > 255)
        {
            num4 = 255;
        }
        num3 <<= 8;
        num4 <<= 16;
        ((Color)(ref vertices.TopRightColor)).PackedValue = (uint)(num2 | num3 | num4) | 0xFF000000u;
        num2 = (int)((color2.X + color7.X + color3.X + color.X) * num);
        num3 = (int)((color2.Y + color7.Y + color3.Y + color.Y) * num);
        num4 = (int)((color2.Z + color7.Z + color3.Z + color.Z) * num);
        if (num2 > 255)
        {
            num2 = 255;
        }
        if (num3 > 255)
        {
            num3 = 255;
        }
        if (num4 > 255)
        {
            num4 = 255;
        }
        num3 <<= 8;
        num4 <<= 16;
        ((Color)(ref vertices.BottomLeftColor)).PackedValue = (uint)(num2 | num3 | num4) | 0xFF000000u;
        num2 = (int)((color2.X + color8.X + color4.X + color.X) * num);
        num3 = (int)((color2.Y + color8.Y + color4.Y + color.Y) * num);
        num4 = (int)((color2.Z + color8.Z + color4.Z + color.Z) * num);
        if (num2 > 255)
        {
            num2 = 255;
        }
        if (num3 > 255)
        {
            num3 = 255;
        }
        if (num4 > 255)
        {
            num4 = 255;
        }
        num3 <<= 8;
        num4 <<= 16;
        ((Color)(ref vertices.BottomRightColor)).PackedValue = (uint)(num2 | num3 | num4) | 0xFF000000u;
    }
References Terraria.Lighting._activeEngine, Terraria.Graphics.Light.Color, and Terraria.Lighting.GlobalBrightness.
Referenced by Terraria.Main.DrawBackground(), Terraria.GameContent.Liquid.LiquidRenderer.DrawNormalLiquids(), Terraria.GameContent.Liquid.LiquidRenderer.DrawShimmer(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), Terraria.GameContent.Drawing.WallDrawing.DrawWalls(), Terraria.WaterfallManager.DrawWaterfall(), and Terraria.Main.OldDrawBackground().