TModLoader: Terraria.Lighting.GetColor4Slice
GetColor4Slice() [1/2]
static void Terraria.Lighting.GetColor4Slice (int centerX, int centerY, ref Color[] slices) inline static
    {
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_012e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_0158: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_024e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_0278: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_023f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0370: Unknown result type (might be due to invalid IL or missing references)
        //IL_0385: Unknown result type (might be due to invalid IL or missing references)
        //IL_039a: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_030b: Unknown result type (might be due to invalid IL or missing references)
        //IL_03eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0361: Unknown result type (might be due to invalid IL or missing references)
        //IL_048e: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0403: Unknown result type (might be due to invalid IL or missing references)
        //IL_0418: Unknown result type (might be due to invalid IL or missing references)
        //IL_042d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0509: Unknown result type (might be due to invalid IL or missing references)
        //IL_050e: Unknown result type (might be due to invalid IL or missing references)
        //IL_047e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0483: Unknown result type (might be due to invalid IL or missing references)
        Vector3 color = _activeEngine.GetColor(centerX, centerY - 1);
        Vector3 color2 = _activeEngine.GetColor(centerX, centerY + 1);
        Vector3 color3 = _activeEngine.GetColor(centerX - 1, centerY);
        Vector3 color4 = _activeEngine.GetColor(centerX + 1, centerY);
        float num37 = color.X + color.Y + color.Z;
        float num20 = color2.X + color2.Y + color2.Z;
        float num30 = color4.X + color4.Y + color4.Z;
        float num31 = color3.X + color3.Y + color3.Z;
        if (num37 >= num31)
        {
            int num32 = (int)(255f * color3.X * GlobalBrightness);
            int num33 = (int)(255f * color3.Y * GlobalBrightness);
            int num34 = (int)(255f * color3.Z * GlobalBrightness);
            if (num32 > 255)
            {
                num32 = 255;
            }
            if (num33 > 255)
            {
                num33 = 255;
            }
            if (num34 > 255)
            {
                num34 = 255;
            }
            slices[0] = new Color((int)(byte)num32, (int)(byte)num33, (int)(byte)num34, 255);
        }
        else
        {
            int num35 = (int)(255f * color.X * GlobalBrightness);
            int num36 = (int)(255f * color.Y * GlobalBrightness);
            int num10 = (int)(255f * color.Z * GlobalBrightness);
            if (num35 > 255)
            {
                num35 = 255;
            }
            if (num36 > 255)
            {
                num36 = 255;
            }
            if (num10 > 255)
            {
                num10 = 255;
            }
            slices[0] = new Color((int)(byte)num35, (int)(byte)num36, (int)(byte)num10, 255);
        }
        if (num37 >= num30)
        {
            int num11 = (int)(255f * color4.X * GlobalBrightness);
            int num12 = (int)(255f * color4.Y * GlobalBrightness);
            int num13 = (int)(255f * color4.Z * GlobalBrightness);
            if (num11 > 255)
            {
                num11 = 255;
            }
            if (num12 > 255)
            {
                num12 = 255;
            }
            if (num13 > 255)
            {
                num13 = 255;
            }
            slices[1] = new Color((int)(byte)num11, (int)(byte)num12, (int)(byte)num13, 255);
        }
        else
        {
            int num14 = (int)(255f * color.X * GlobalBrightness);
            int num15 = (int)(255f * color.Y * GlobalBrightness);
            int num16 = (int)(255f * color.Z * GlobalBrightness);
            if (num14 > 255)
            {
                num14 = 255;
            }
            if (num15 > 255)
            {
                num15 = 255;
            }
            if (num16 > 255)
            {
                num16 = 255;
            }
            slices[1] = new Color((int)(byte)num14, (int)(byte)num15, (int)(byte)num16, 255);
        }
        if (num20 >= num31)
        {
            int num17 = (int)(255f * color3.X * GlobalBrightness);
            int num18 = (int)(255f * color3.Y * GlobalBrightness);
            int num19 = (int)(255f * color3.Z * GlobalBrightness);
            if (num17 > 255)
            {
                num17 = 255;
            }
            if (num18 > 255)
            {
                num18 = 255;
            }
            if (num19 > 255)
            {
                num19 = 255;
            }
            slices[2] = new Color((int)(byte)num17, (int)(byte)num18, (int)(byte)num19, 255);
        }
        else
        {
            int num21 = (int)(255f * color2.X * GlobalBrightness);
            int num22 = (int)(255f * color2.Y * GlobalBrightness);
            int num23 = (int)(255f * color2.Z * GlobalBrightness);
            if (num21 > 255)
            {
                num21 = 255;
            }
            if (num22 > 255)
            {
                num22 = 255;
            }
            if (num23 > 255)
            {
                num23 = 255;
            }
            slices[2] = new Color((int)(byte)num21, (int)(byte)num22, (int)(byte)num23, 255);
        }
        if (num20 >= num30)
        {
            int num24 = (int)(255f * color4.X * GlobalBrightness);
            int num25 = (int)(255f * color4.Y * GlobalBrightness);
            int num26 = (int)(255f * color4.Z * GlobalBrightness);
            if (num24 > 255)
            {
                num24 = 255;
            }
            if (num25 > 255)
            {
                num25 = 255;
            }
            if (num26 > 255)
            {
                num26 = 255;
            }
            slices[3] = new Color((int)(byte)num24, (int)(byte)num25, (int)(byte)num26, 255);
        }
        else
        {
            int num27 = (int)(255f * color2.X * GlobalBrightness);
            int num28 = (int)(255f * color2.Y * GlobalBrightness);
            int num29 = (int)(255f * color2.Z * GlobalBrightness);
            if (num27 > 255)
            {
                num27 = 255;
            }
            if (num28 > 255)
            {
                num28 = 255;
            }
            if (num29 > 255)
            {
                num29 = 255;
            }
            slices[3] = new Color((int)(byte)num27, (int)(byte)num28, (int)(byte)num29, 255);
        }
    }
References Terraria.Lighting._activeEngine, Terraria.Graphics.Light.Color, and Terraria.Lighting.GlobalBrightness.
Referenced by Terraria.Main.DrawBackground(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile_SlicedBlock(), and Terraria.Main.OldDrawBackground().