TModLoader: Terraria.Framing.WallFrame
WallFrame()
static void Terraria.Framing.WallFrame (int i, int j, bool resetFrame = false) inline static
Definition at line 335 of file Framing.cs.
    {
        if (WorldGen.SkipFramingBecauseOfGen || i <= 0 || j <= 0 || i >= Main.maxTilesX - 1 || j >= Main.maxTilesY - 1 || Main.tile[i, j] == null)
        {
            return;
        }
        if (Main.tile[i, j].wall >= WallLoader.WallCount)
        {
            Main.tile[i, j].wall = 0;
        }
        WorldGen.UpdateMapTile(i, j);
        Tile tile = Main.tile[i, j];
        if (tile.wall == 0)
        {
            tile.wallColor(0);
            tile.ClearWallPaintAndCoating();
            return;
        }
        int num = 0;
        bool flag = Main.ShouldShowInvisibleWalls();
        if (j - 1 >= 0)
        {
            Tile tile5 = Main.tile[i, j - 1];
            if (tile5 != null && (tile5.wall > 0 || (tile5.active() && TileID.Sets.WallsMergeWith[tile5.type])) && (flag || !tile5.invisibleWall()))
            {
                num = 1;
            }
        }
        if (i - 1 >= 0)
        {
            Tile tile4 = Main.tile[i - 1, j];
            if (tile4 != null && (tile4.wall > 0 || (tile4.active() && TileID.Sets.WallsMergeWith[tile4.type])) && (flag || !tile4.invisibleWall()))
            {
                num |= 2;
            }
        }
        if (i + 1 <= Main.maxTilesX - 1)
        {
            Tile tile3 = Main.tile[i + 1, j];
            if (tile3 != null && (tile3.wall > 0 || (tile3.active() && TileID.Sets.WallsMergeWith[tile3.type])) && (flag || !tile3.invisibleWall()))
            {
                num |= 4;
            }
        }
        if (j + 1 <= Main.maxTilesY - 1)
        {
            Tile tile2 = Main.tile[i, j + 1];
            if (tile2 != null && (tile2.wall > 0 || (tile2.active() && TileID.Sets.WallsMergeWith[tile2.type])) && (flag || !tile2.invisibleWall()))
            {
                num |= 8;
            }
        }
        int num2 = 0;
        if (Main.wallLargeFrames[tile.wall] == 1)
        {
            num2 = phlebasTileFrameNumberLookup[j % 4][i % 3] - 1;
        }
        else if (Main.wallLargeFrames[tile.wall] == 2)
        {
            num2 = lazureTileFrameNumberLookup[i % 2][j % 2] - 1;
        }
        else if (resetFrame)
        {
            num2 = WorldGen.genRand.Next(0, 3);
            if (tile.wall == 21 && WorldGen.genRand.Next(2) == 0)
            {
                num2 = 2;
            }
        }
        else
        {
            num2 = tile.wallFrameNumber();
        }
        if (num == 15)
        {
            num += centerWallFrameLookup[i % 3][j % 3];
        }
        if (WallLoader.WallFrame(i, j, tile.wall, resetFrame, ref num, ref num2))
        {
            tile.wallFrameNumber((byte)num2);
            Point16 point = wallFrameLookup[num][num2];
            tile.wallFrameX(point.X);
            tile.wallFrameY(point.Y);
        }
    }
References Terraria.Framing.centerWallFrameLookup, Terraria.Tile.ClearWallPaintAndCoating(), Terraria.WorldGen.genRand, Terraria.Framing.lazureTileFrameNumberLookup, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Framing.phlebasTileFrameNumberLookup, Terraria.Main.ShouldShowInvisibleWalls(), Terraria.WorldGen.SkipFramingBecauseOfGen, Terraria.Main.tile, Terraria.WorldGen.UpdateMapTile(), Terraria.Tile.wall, Terraria.Tile.wallColor(), Terraria.ModLoader.WallLoader.WallCount, Terraria.ModLoader.WallLoader.WallFrame(), Terraria.Framing.wallFrameLookup, Terraria.Tile.wallFrameNumber(), Terraria.Tile.wallFrameX(), Terraria.Tile.wallFrameY(), Terraria.Main.wallLargeFrames, Terraria.ID.TileID.Sets.WallsMergeWith, Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.WorldGen.EveryTileFrame(), Terraria.WorldGen.RangeFrame(), Terraria.WorldGen.Reframe(), and Terraria.WorldGen.SquareWallFrame().