TModLoader: Terraria.ModLoader.Core.LoaderUtils.MustOverrideTogether
MustOverrideTogether()
static void Terraria.ModLoader.Core.LoaderUtils.MustOverrideTogether (Type type, params MethodInfo[] methods) inline static private
Definition at line 129 of file LoaderUtils.cs.
    {
        Type type2 = type;
        int c = methods.Count((MethodInfo m) => HasOverride(type2, m));
        if (c > 0 && c < methods.Length)
        {
            throw new Exception($"{type2} must override all of ({string.Join('/', methods.Select((MethodInfo m) => m.Name))}) or none");
        }
    }
References Terraria.ModLoader.Core.LoaderUtils.HasOverride().
Referenced by Terraria.ModLoader.Core.LoaderUtils.MustOverrideTogether< T >(), Terraria.ModLoader.GlobalItem.ValidateType(), Terraria.ModLoader.GlobalNPC.ValidateType(), Terraria.ModLoader.GlobalProjectile.ValidateType(), Terraria.ModLoader.ModPlayer.ValidateType(), and Terraria.ModLoader.ModSystem.ValidateType().