TModLoader: Terraria.ModLoader.IO.TagPrinter.WriteValue
WriteValue()
void Terraria.ModLoader.IO.TagPrinter.WriteValue (object elem) inline private
Definition at line 116 of file TagPrinter.cs.
    {
        if (elem is byte)
        {
            sb.Append((byte)elem);
        }
        else if (elem is short)
        {
            sb.Append((short)elem);
        }
        else if (elem is int)
        {
            sb.Append((int)elem);
        }
        else if (elem is long)
        {
            sb.Append((long)elem);
        }
        else if (elem is float)
        {
            sb.Append((float)elem);
        }
        else if (elem is double)
        {
            sb.Append((double)elem);
        }
        else if (elem is string)
        {
            sb.Append('"').Append((string)elem).Append('"');
        }
        else if (elem is byte[])
        {
            sb.Append('[').Append(string.Join(", ", (byte[])elem)).Append(']');
        }
        else if (elem is int[])
        {
            sb.Append('[').Append(string.Join(", ", (int[])elem)).Append(']');
        }
        else if (elem is TagCompound)
        {
            TagCompound tag = (TagCompound)elem;
            WriteList('{', '}', multiline: true, tag, WriteEntry);
        }
        else
        {
            if (!(elem is IList))
            {
                return;
            }
            Type type = elem.GetType().GetGenericArguments()[0];
            WriteList('[', ']', type == typeof(string) || type == typeof(TagCompound) || typeof(IList).IsAssignableFrom(type), ((IList)elem).Cast<object>(), delegate(object o)
            {
                if (type == typeof(IList))
                {
                    sb.Append(TypeString(o.GetType().GetGenericArguments()[0])).Append(' ');
                }
                WriteValue(o);
            });
        }
    }
References Terraria.ModLoader.IO.TagPrinter.sb, Terraria.ModLoader.IO.TagPrinter.TypeString(), Terraria.ModLoader.IO.TagPrinter.WriteEntry(), and Terraria.ModLoader.IO.TagPrinter.WriteValue().
Referenced by Terraria.ModLoader.IO.TagPrinter.WriteEntry(), and Terraria.ModLoader.IO.TagPrinter.WriteValue().