TModLoader: Terraria.ModLoader.IO.TagPrinter.WriteEntry
WriteEntry()
void Terraria.ModLoader.IO.TagPrinter.WriteEntry (KeyValuePair< string, object > entry) inline private
    {
        if (entry.Value == null)
        {
            sb.Append('"').Append(entry.Key).Append("\" = null");
            return;
        }
        Type type = entry.Value.GetType();
        bool isList = entry.Value is IList && !(entry.Value is Array);
        sb.Append(TypeString(isList ? type.GetGenericArguments()[0] : type));
        sb.Append(" \"").Append(entry.Key).Append("\" ");
        if (type != typeof(TagCompound) && !isList)
        {
            sb.Append("= ");
        }
        WriteValue(entry.Value);
    }
References Terraria.ModLoader.IO.TagPrinter.sb, Terraria.ModLoader.IO.TagPrinter.TypeString(), and Terraria.ModLoader.IO.TagPrinter.WriteValue().
Referenced by Terraria.ModLoader.IO.TagPrinter.WriteValue().