TModLoader: Terraria.GameContent.TilePaintSystemV2.TileRenderTargetHolder.Prepare
Prepare()
override void Terraria.GameContent.TilePaintSystemV2.TileRenderTargetHolder.Prepare () inline
        {
            Asset<Texture2D> asset;
            if (PlantLoader.plantIdToStyleLimit.TryGetValue(Key.TileType, out var val) && val <= Math.Abs(Key.TileStyle))
            {
                int lookup = Math.Abs(Key.TileStyle) - val;
                asset = PlantLoader.GetTexture(Key.TileType, lookup);
            }
            else
            {
                Main.instance.LoadTiles(Key.TileType);
                asset = TextureAssets.Tile[Key.TileType];
            }
            asset.Wait?.Invoke();
            PrepareTextureIfNecessary(asset.Value);
        }
References Terraria.ModLoader.PlantLoader.GetTexture(), Terraria.Main.instance, Terraria.GameContent.TilePaintSystemV2.TileRenderTargetHolder.Key, Terraria.Main.LoadTiles(), Terraria.ModLoader.PlantLoader.plantIdToStyleLimit, Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.PrepareTextureIfNecessary(), Terraria.GameContent.TextureAssets.Tile, Terraria.GameContent.TilePaintSystemV2.TileVariationkey.TileStyle, and Terraria.GameContent.TilePaintSystemV2.TileVariationkey.TileType.