TModLoader: Terraria.GameContent.UI.States.UIWorldSelect.AddAutomaticWorldMigrationButtons
AddAutomaticWorldMigrationButtons()
void Terraria.GameContent.UI.States.UIWorldSelect.AddAutomaticWorldMigrationButtons () inline private
Definition at line 538 of file UIWorldSelect.cs.
    {
        string vanillaWorldsPath = Path.Combine(Platform.Get<IPathService>().GetStoragePath("Terraria"), "Worlds");
        if (!Directory.Exists(vanillaWorldsPath) || !Directory.GetFiles(vanillaWorldsPath, "*.wld").Any())
        {
            return;
        }
        UIPanel autoMigrateButton = new UIPanel();
        autoMigrateButton.Width.Set(0f, 1f);
        autoMigrateButton.Height.Set(50f, 0f);
        UIText migrateText = new UIText((!_currentlyMigratingFiles) ? Language.GetText("tModLoader.MigrateWorldsText") : Language.GetText("tModLoader.MigratingWorldsText"));
        autoMigrateButton.OnLeftClick += delegate
        {
            if (!_currentlyMigratingFiles)
            {
                _currentlyMigratingFiles = true;
                migrateText.SetText(Language.GetText("tModLoader.MigratingWorldsText"));
                Task.Factory.StartNew(delegate
                {
                    ExecuteAutomaticWorldMigration(vanillaWorldsPath);
                }, TaskCreationOptions.PreferFairness);
            }
        };
        autoMigrateButton.Append(migrateText);
        _worldList.Add(autoMigrateButton);
        UIText noWorldsMessage = new UIText(Language.GetTextValue("tModLoader.MigrateWorldsMessage", Program.SaveFolderName));
        noWorldsMessage.Width.Set(0f, 1f);
        noWorldsMessage.Height.Set(300f, 0f);
        noWorldsMessage.MarginTop = 20f;
        noWorldsMessage.OnLeftClick += delegate
        {
            Utils.OpenFolder(Main.WorldPath);
            Utils.OpenFolder(vanillaWorldsPath);
        };
        _worldList.Add(noWorldsMessage);
    }
References Terraria.GameContent.UI.States.UIWorldSelect._currentlyMigratingFiles, Terraria.GameContent.UI.States.UIWorldSelect._worldList, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.States.UIWorldSelect.ExecuteAutomaticWorldMigration(), Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), Terraria.Utils.OpenFolder(), Terraria.Program.SaveFolderName, and Terraria.Main.WorldPath.
Referenced by Terraria.GameContent.UI.States.UIWorldSelect.UpdateWorldsList().