TModLoader: Terraria.GameContent.UI.States.UIWorldSelect.OnInitialize
OnInitialize()
override void Terraria.GameContent.UI.States.UIWorldSelect.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 48 of file UIWorldSelect.cs.
    {
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
        UIElement uIElement = new UIElement();
        uIElement.Width.Set(0f, 0.8f);
        uIElement.MaxWidth.Set(650f, 0f);
        uIElement.Top.Set(220f, 0f);
        uIElement.Height.Set(-220f, 1f);
        uIElement.HAlign = 0.5f;
        UIPanel uIPanel = new UIPanel();
        uIPanel.Width.Set(0f, 1f);
        uIPanel.Height.Set(-110f, 1f);
        uIPanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
        uIElement.Append(uIPanel);
        _containerPanel = uIPanel;
        _worldList = new UIList();
        _worldList.Width.Set(0f, 1f);
        _worldList.Height.Set(0f, 1f);
        _worldList.ListPadding = 5f;
        uIPanel.Append(_worldList);
        _scrollbar = new UIScrollbar();
        _scrollbar.SetView(100f, 1000f);
        _scrollbar.Height.Set(0f, 1f);
        _scrollbar.HAlign = 1f;
        _worldList.SetScrollbar(_scrollbar);
        UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.SelectWorld"), 0.8f, large: true);
        uITextPanel.HAlign = 0.5f;
        uITextPanel.Top.Set(-40f, 0f);
        uITextPanel.SetPadding(15f);
        uITextPanel.BackgroundColor = new Color(73, 94, 171);
        uIElement.Append(uITextPanel);
        UITextPanel<LocalizedText> uITextPanel2 = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true);
        uITextPanel2.Width.Set(-10f, 0.5f);
        uITextPanel2.Height.Set(50f, 0f);
        uITextPanel2.VAlign = 1f;
        uITextPanel2.HAlign = 0f;
        uITextPanel2.Top.Set(-45f, 0f);
        uITextPanel2.OnMouseOver += FadedMouseOver;
        uITextPanel2.OnMouseOut += FadedMouseOut;
        uITextPanel2.OnLeftClick += GoBackClick;
        uIElement.Append(uITextPanel2);
        _backPanel = uITextPanel2;
        UITextPanel<LocalizedText> uITextPanel3 = new UITextPanel<LocalizedText>(Language.GetText("UI.New"), 0.7f, large: true);
        uITextPanel3.CopyStyle(uITextPanel2);
        uITextPanel3.HAlign = 1f;
        uITextPanel3.OnMouseOver += FadedMouseOver;
        uITextPanel3.OnMouseOut += FadedMouseOut;
        uITextPanel3.OnLeftClick += NewWorldClick;
        uIElement.Append(uITextPanel3);
        _newPanel = uITextPanel3;
        Append(uIElement);
    }
References Terraria.UI.UIElement.UIElement(), Terraria.GameContent.UI.States.UIWorldSelect._backPanel, Terraria.GameContent.UI.States.UIWorldSelect._containerPanel, Terraria.GameContent.UI.States.UIWorldSelect._newPanel, Terraria.GameContent.UI.States.UIWorldSelect._scrollbar, Terraria.GameContent.UI.States.UIWorldSelect._worldList, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UIWorldSelect.FadedMouseOut(), Terraria.GameContent.UI.States.UIWorldSelect.FadedMouseOver(), Terraria.Localization.Language.GetText(), Terraria.GameContent.UI.States.UIWorldSelect.GoBackClick(), Terraria.UI.UIElement.Height, Terraria.UI.UIElement.MaxWidth, Terraria.GameContent.UI.States.UIWorldSelect.NewWorldClick(), Terraria.UI.StyleDimension.Set(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.UI.UIElement.Top, and Terraria.UI.UIElement.Width.