TModLoader: Terraria.GameContent.UI.States.UIWorldSelect.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIWorldSelect.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
    {
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        UILinkPointNavigator.Shortcuts.BackButtonCommand = 2;
        int num = 3000;
        Rectangle val = _backPanel.GetInnerDimensions().ToRectangle();
        UILinkPointNavigator.SetPosition(num, ((Rectangle)(ref val)).Center.ToVector2());
        int iD = num + 1;
        val = _newPanel.GetInnerDimensions().ToRectangle();
        UILinkPointNavigator.SetPosition(iD, ((Rectangle)(ref val)).Center.ToVector2());
        int num2 = num;
        UILinkPoint uILinkPoint = UILinkPointNavigator.Points[num2];
        uILinkPoint.Unlink();
        uILinkPoint.Right = num2 + 1;
        num2 = num + 1;
        uILinkPoint = UILinkPointNavigator.Points[num2];
        uILinkPoint.Unlink();
        uILinkPoint.Left = num2 - 1;
        float num3 = 1f / Main.UIScale;
        Rectangle clippingRectangle = _containerPanel.GetClippingRectangle(spriteBatch);
        Vector2 minimum = clippingRectangle.TopLeft() * num3;
        Vector2 maximum = clippingRectangle.BottomRight() * num3;
        List<SnapPoint> snapPoints = GetSnapPoints();
        for (int i = 0; i < snapPoints.Count; i++)
        {
            if (!snapPoints[i].Position.Between(minimum, maximum))
            {
                snapPoints.Remove(snapPoints[i]);
                i--;
            }
        }
        SnapPoint[,] array = new SnapPoint[_worldList.Count, 6];
        foreach (SnapPoint item in snapPoints.Where((SnapPoint a) => a.Name == "Play"))
        {
            array[item.Id, 0] = item;
        }
        foreach (SnapPoint item2 in snapPoints.Where((SnapPoint a) => a.Name == "Favorite"))
        {
            array[item2.Id, 1] = item2;
        }
        foreach (SnapPoint item3 in snapPoints.Where((SnapPoint a) => a.Name == "Cloud"))
        {
            array[item3.Id, 2] = item3;
        }
        foreach (SnapPoint item4 in snapPoints.Where((SnapPoint a) => a.Name == "Seed"))
        {
            array[item4.Id, 3] = item4;
        }
        foreach (SnapPoint item5 in snapPoints.Where((SnapPoint a) => a.Name == "Rename"))
        {
            array[item5.Id, 4] = item5;
        }
        foreach (SnapPoint item6 in snapPoints.Where((SnapPoint a) => a.Name == "Delete"))
        {
            array[item6.Id, 5] = item6;
        }
        num2 = num + 2;
        int[] array2 = new int[_worldList.Count];
        for (int j = 0; j < array2.Length; j++)
        {
            array2[j] = -1;
        }
        for (int k = 0; k < array.GetLength(1); k++)
        {
            int num4 = -1;
            for (int l = 0; l < array.GetLength(0); l++)
            {
                if (array[l, k] != null)
                {
                    uILinkPoint = UILinkPointNavigator.Points[num2];
                    uILinkPoint.Unlink();
                    UILinkPointNavigator.SetPosition(num2, array[l, k].Position);
                    if (num4 != -1)
                    {
                        uILinkPoint.Up = num4;
                        UILinkPointNavigator.Points[num4].Down = num2;
                    }
                    if (array2[l] != -1)
                    {
                        uILinkPoint.Left = array2[l];
                        UILinkPointNavigator.Points[array2[l]].Right = num2;
                    }
                    uILinkPoint.Down = num;
                    if (k == 0)
                    {
                        UILinkPointNavigator.Points[num].Up = (UILinkPointNavigator.Points[num + 1].Up = num2);
                    }
                    num4 = num2;
                    array2[l] = num2;
                    UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX = num2;
                    num2++;
                }
            }
        }
        if (PlayerInput.UsingGamepadUI && _worldList.Count == 0 && UILinkPointNavigator.CurrentPoint > 3001)
        {
            UILinkPointNavigator.ChangePoint(3001);
        }
    }
References Terraria.GameContent.UI.States.UIWorldSelect._backPanel, Terraria.GameContent.UI.States.UIWorldSelect._containerPanel, Terraria.GameContent.UI.States.UIWorldSelect._newPanel, Terraria.GameContent.UI.States.UIWorldSelect._worldList, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), Terraria.GameContent.UI.Elements.UIList.Count, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Terraria.UI.UIElement.GetClippingRectangle(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.UIScale, and Terraria.GameInput.PlayerInput.UsingGamepadUI.
Referenced by Terraria.GameContent.UI.States.UIWorldSelect.Draw().