TModLoader: Terraria.GameContent.UI.States.UIWorldSelect.LoadMigratableWorlds
LoadMigratableWorlds()
void Terraria.GameContent.UI.States.UIWorldSelect.LoadMigratableWorlds () inline private
Definition at line 386 of file UIWorldSelect.cs.
    {
        _migrationPanel = new UIExpandablePanel();
        _worldList.Add(_migrationPanel);
        UIText playerMigrationPanelTitle = new UIText(Language.GetTextValue("tModLoader.MigrateIndividualWorldsHeader"));
        playerMigrationPanelTitle.Top.Set(4f, 0f);
        _migrationPanel.Append(playerMigrationPanelTitle);
        NestedUIList migrateWorldList = new NestedUIList();
        migrateWorldList.Width.Set(-22f, 1f);
        migrateWorldList.Left.Set(0f, 0f);
        migrateWorldList.Top.Set(30f, 0f);
        migrateWorldList.MinHeight.Set(300f, 0f);
        migrateWorldList.ListPadding = 5f;
        _migrationPanel.VisibleWhenExpanded.Add(migrateWorldList);
        UIScrollbar scrollbar = new UIScrollbar();
        scrollbar.SetView(100f, 1000f);
        scrollbar.Height.Set(-42f, 1f);
        scrollbar.Top.Set(36f, 0f);
        scrollbar.Left.Pixels -= 0f;
        scrollbar.HAlign = 1f;
        migrateWorldList.SetScrollbar(scrollbar);
        _migrationPanel.VisibleWhenExpanded.Add(scrollbar);
        (string, string, int)[] otherPaths = FileUtilities.GetAlternateSavePathFiles("Worlds");
        int currentStabilityLevel = BuildInfo.Purpose switch
        {
            BuildInfo.BuildPurpose.Stable => 1,
            BuildInfo.BuildPurpose.Preview => 2,
            _ => 3,
        };
        (string, string, int)[] array = otherPaths;
        for (int j = 0; j < array.Length; j++)
        {
            var (otherSaveFolderPath, message, stabilityLevel) = array[j];
            if (stabilityLevel == currentStabilityLevel || !Directory.Exists(otherSaveFolderPath))
            {
                continue;
            }
            string[] files = Directory.GetFiles(otherSaveFolderPath, "*.wld");
            int num2 = Math.Min(1000, files.Length);
            for (int i = 0; i < num2; i++)
            {
                string worldInThisWorldsPath = Path.Combine(Main.WorldPath, Path.GetFileName(files[i]));
                if (File.Exists(worldInThisWorldsPath) && File.GetLastWriteTime(worldInThisWorldsPath) == File.GetLastWriteTime(files[i]))
                {
                    continue;
                }
                WorldFileData fileData = WorldFile.GetAllMetadata(files[i], cloudSave: false);
                if (fileData == null)
                {
                    continue;
                }
                UIPanel migrateIndividualWorldPanel = new UIPanel();
                migrateIndividualWorldPanel.Width.Set(0f, 1f);
                migrateIndividualWorldPanel.Height.Set(50f, 0f);
                float left = 0f;
                if (stabilityLevel > currentStabilityLevel)
                {
                    UIHoverImage warningImage2 = new UIHoverImage(UICommon.ButtonErrorTexture, Language.GetTextValue("tModLoader.WorldFromNewerTModMightNotWork"))
                    {
                        Left =
{
                            Pixels = left
                        },
                        Top =
{
                            Pixels = 3f
                        }
                    };
                    migrateIndividualWorldPanel.Append(warningImage2);
                    left += warningImage2.Width.Pixels + 6f;
                }
                WorldFileData worldWithSameName = Main.WorldList.FirstOrDefault((WorldFileData x) => x.Name == fileData.Name);
                if (worldWithSameName != null)
                {
                    UIHoverImage warningImage = new UIHoverImage(UICommon.ButtonExclamationTexture, Language.GetTextValue("tModLoader.WorldWithThisNameExistsWillBeOverwritten"))
                    {
                        Left =
{
                            Pixels = left
                        },
                        Top =
{
                            Pixels = 3f
                        }
                    };
                    migrateIndividualWorldPanel.Append(warningImage);
                    left += warningImage.Width.Pixels + 6f;
                    if (File.GetLastWriteTime(worldWithSameName.Path) > File.GetLastWriteTime(files[i]))
                    {
                        warningImage = new UIHoverImage(UICommon.ButtonExclamationTexture, Language.GetTextValue("tModLoader.ExistingWorldPlayedMoreRecently"))
{
                            Left =
{
                                Pixels = left
                            },
                            Top =
{
                                Pixels = 3f
                            }
                        };
                        migrateIndividualWorldPanel.Append(warningImage);
                        left += warningImage.Width.Pixels + 6f;
                    }
                }
                UIText migrateIndividualWorldText = new UIText(string.Format(message, fileData.Name));
                migrateIndividualWorldText.Width.Set(0f - left, 1f);
                migrateIndividualWorldText.Left.Set(left, 0f);
                migrateIndividualWorldText.Height.Set(0f, 1f);
                migrateIndividualWorldText.OnLeftClick += delegate
                {
                    if (!_currentlyMigratingFiles)
                    {
                        _currentlyMigratingFiles = true;
                        migrateIndividualWorldText.SetText(Language.GetText("tModLoader.MigratingWorldsText"));
                        Task.Factory.StartNew(delegate
{
                            ExecuteIndividualWorldMigration(fileData, otherSaveFolderPath);
                        }, TaskCreationOptions.PreferFairness);
                    }
                };
                migrateIndividualWorldPanel.Append(migrateIndividualWorldText);
                migrateWorldList.Add(migrateIndividualWorldPanel);
            }
        }
    }
References Terraria.GameContent.UI.States.UIWorldSelect._currentlyMigratingFiles, Terraria.GameContent.UI.States.UIWorldSelect._migrationPanel, Terraria.GameContent.UI.States.UIWorldSelect._worldList, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.UI.UIElement.Append(), Terraria.ModLoader.UI.UICommon.ButtonErrorTexture, Terraria.ModLoader.UI.UICommon.ButtonExclamationTexture, Terraria.GameContent.UI.States.UIWorldSelect.ExecuteIndividualWorldMigration(), Terraria.IO.WorldFile.GetAllMetadata(), Terraria.Utilities.FileUtilities.GetAlternateSavePathFiles(), Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.Left, Terraria.IO.FileData.Name, Terraria.UI.UIElement.Top, Terraria.ModLoader.UI.UIExpandablePanel.VisibleWhenExpanded, Terraria.Main.WorldList, and Terraria.Main.WorldPath.
Referenced by Terraria.GameContent.UI.States.UIWorldSelect.OnActivate().