TModLoader: Terraria.GameContent.Events.CultistRitual.CheckFloor
CheckFloor()
static bool Terraria.GameContent.Events.CultistRitual.CheckFloor (Vector2 Center, out Point[] spawnPoints) inline static
    {
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        Point[] array = (Point[])(object)new Point[4];
        int num = 0;
        Point point = Center.ToTileCoordinates();
        for (int i = -5; i <= 5; i += 2)
        {
            if (i == -1 || i == 1)
            {
                continue;
            }
            for (int j = -5; j < 12; j++)
            {
                int num2 = point.X + i * 2;
                int num3 = point.Y + j;
                if ((WorldGen.SolidTile(num2, num3) || TileID.Sets.Platforms[Framing.GetTileSafely(num2, num3).type]) && (!Collision.SolidTiles(num2 - 1, num2 + 1, num3 - 3, num3 - 1) || (!Collision.SolidTiles(num2, num2, num3 - 3, num3 - 1) && !Collision.SolidTiles(num2 + 1, num2 + 1, num3 - 3, num3 - 2) && !Collision.SolidTiles(num2 - 1, num2 - 1, num3 - 3, num3 - 2))))
                {
                    array[num++] = new Point(num2, num3);
                    break;
                }
            }
        }
        if (num != 4)
        {
            spawnPoints = null;
            return false;
        }
        spawnPoints = array;
        return true;
    }
References Terraria.Framing.GetTileSafely(), Terraria.ID.TileID.Sets.Platforms, Terraria.WorldGen.SolidTile(), Terraria.Collision.SolidTiles(), and Terraria.Tile.type.
Referenced by Terraria.GameContent.Events.CultistRitual.CheckRitual(), and Terraria.NPC.VanillaAI_Inner().