TModLoader: Terraria.GameContent.UI.States.UIVirtualKeyboard.SetKeyState
SetKeyState()
void Terraria.GameContent.UI.States.UIVirtualKeyboard.SetKeyState (KeyState keyState) inline
    {
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        UITextPanel<object> uITextPanel = null;
        switch (_keyState)
        {
        case KeyState.Shift:
            uITextPanel = _shiftButton;
            break;
        case KeyState.Symbol:
            uITextPanel = _symbolButton;
            break;
        }
        if (uITextPanel != null)
        {
            if (uITextPanel.IsMouseHovering)
            {
                uITextPanel.BackgroundColor = new Color(73, 94, 171);
            }
            else
            {
                uITextPanel.BackgroundColor = new Color(63, 82, 151) * 0.7f;
            }
        }
        string text = null;
        UITextPanel<object> uITextPanel2 = null;
        switch (keyState)
        {
        case KeyState.Default:
            text = "1234567890qwertyuiopasdfghjkl'zxcvbnm,.?";
            break;
        case KeyState.Shift:
            text = "1234567890QWERTYUIOPASDFGHJKL'ZXCVBNM,.?";
            uITextPanel2 = _shiftButton;
            break;
        case KeyState.Symbol:
            text = "1234567890!@#$%^&*()-_+=/\\{}[]<>;:\"`|~£¥";
            uITextPanel2 = _symbolButton;
            break;
        }
        for (int i = 0; i < text.Length; i++)
        {
            _keyList[i].SetText(text[i].ToString());
        }
        _keyState = keyState;
        if (uITextPanel2 != null)
        {
            uITextPanel2.BackgroundColor = new Color(93, 114, 191);
        }
    }
References Terraria.GameContent.UI.States.UIVirtualKeyboard._keyList, Terraria.GameContent.UI.States.UIVirtualKeyboard._keyState, Terraria.GameContent.UI.States.UIVirtualKeyboard._shiftButton, Terraria.GameContent.UI.States.UIVirtualKeyboard._symbolButton, and Terraria.GameContent.UI.Elements.UITextPanel< T >.SetText().
Referenced by Terraria.GameContent.UI.States.UIVirtualKeyboard.UIVirtualKeyboard(), Terraria.GameContent.UI.States.UIVirtualKeyboard.CycleSymbols(), Terraria.GameContent.UI.States.UIVirtualKeyboard.TypeText(), and Terraria.GameContent.UI.States.UIVirtualKeyboard.Write().