TModLoader: Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
    {
        //IL_0222: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_023e: Unknown result type (might be due to invalid IL or missing references)
        //IL_037a: Unknown result type (might be due to invalid IL or missing references)
        //IL_037f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0385: Unknown result type (might be due to invalid IL or missing references)
        //IL_0395: Unknown result type (might be due to invalid IL or missing references)
        //IL_039a: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03df: Unknown result type (might be due to invalid IL or missing references)
        if (Main.gameMenu)
        {
            if (ShouldShowKeyboard())
            {
                outerLayer2.Remove();
                if (!Elements.Contains(outerLayer1))
                {
                    Append(outerLayer1);
                }
                outerLayer1.Activate();
                outerLayer2.Deactivate();
                Recalculate();
                RecalculateChildren();
                if (_labelHeight != 0f)
                {
                    _textBox.Top.Pixels = _textBoxHeight;
                    _label.Top.Pixels = _labelHeight;
                    _textBox.Recalculate();
                    _label.Recalculate();
                    _labelHeight = (_textBoxHeight = 0f);
                    UserInterface.ActiveInstance.ResetLasts();
                }
            }
            else
            {
                outerLayer1.Remove();
                if (!Elements.Contains(outerLayer2))
                {
                    Append(outerLayer2);
                }
                outerLayer2.Activate();
                outerLayer1.Deactivate();
                Recalculate();
                RecalculateChildren();
                if (_textBoxHeight == 0f)
                {
                    _textBoxHeight = _textBox.Top.Pixels;
                    _labelHeight = _label.Top.Pixels;
                    _textBox.Top.Pixels += 50f;
                    _label.Top.Pixels += 50f;
                    _textBox.Recalculate();
                    _label.Recalculate();
                    UserInterface.ActiveInstance.ResetLasts();
                }
            }
        }
        if (!Main.editSign && _edittingSign)
        {
            IngameFancyUI.Close();
            return;
        }
        if (!Main.editChest && _edittingChest)
        {
            IngameFancyUI.Close();
            return;
        }
        base.DrawSelf(spriteBatch);
        UpdateOffsetDown();
        OffsetDown = 0;
        ShouldHideText = false;
        SetupGamepadPoints(spriteBatch);
        PlayerInput.WritingText = true;
        Main.instance.HandleIME();
        float num = Main.screenWidth / 2;
        Rectangle val = _textBox.GetDimensions().ToRectangle();
        Vector2 position = default(Vector2);
        ((Vector2)(ref position))._002Ector(num, (float)(((Rectangle)(ref val)).Bottom + 32));
        Main.instance.DrawWindowsIMEPanel(position, 0.5f);
        string text = Main.GetInputText(Text, _edittingSign);
        if (_edittingSign && Main.inputTextEnter)
        {
            text += "\n";
        }
        else
        {
            if (_edittingChest && Main.inputTextEnter)
            {
                ChestUI.RenameChestSubmit(Main.player[Main.myPlayer]);
                IngameFancyUI.Close();
                return;
            }
            if (Main.inputTextEnter && CanSubmit)
            {
                Submit();
            }
            else if (_edittingChest && Main.player[Main.myPlayer].chest < 0)
            {
                ChestUI.RenameChestCancel();
            }
            else if (Main.inputTextEscape && TryEscapingMenu())
            {
                return;
            }
        }
        if (IngameFancyUI.CanShowVirtualKeyboard(_keyboardContext))
        {
            if (text != Text)
            {
                if (CustomTextValidationForUpdate == null || CustomTextValidationForUpdate(text))
                {
                    Text = text;
                }
                else
                {
                    SoundEngine.PlaySound(11);
                }
            }
            if (_edittingSign)
            {
                CopyTextToSign();
            }
            if (_edittingChest)
            {
                CopyTextToChest();
            }
        }
        byte b = (byte)((255 + ((Color)(ref Main.tileColor)).R * 2) / 3);
        Color value = default(Color);
        ((Color)(ref value))._002Ector((int)b, (int)b, (int)b, 255);
        _textBox.TextColor = Color.Lerp(Color.White, value, 0.2f);
        _label.TextColor = Color.Lerp(Color.White, value, 0.2f);
        float num2 = Main.screenWidth / 2;
        val = _textBox.GetDimensions().ToRectangle();
        ((Vector2)(ref position))._002Ector(num2, (float)(((Rectangle)(ref val)).Bottom + 32));
        Main.instance.DrawWindowsIMEPanel(position, 0.5f);
    }
References Terraria.GameContent.UI.States.UIVirtualKeyboard._edittingChest, Terraria.GameContent.UI.States.UIVirtualKeyboard._edittingSign, Terraria.GameContent.UI.States.UIVirtualKeyboard._keyboardContext, Terraria.GameContent.UI.States.UIVirtualKeyboard._label, Terraria.GameContent.UI.States.UIVirtualKeyboard._labelHeight, Terraria.GameContent.UI.States.UIVirtualKeyboard._textBox, Terraria.GameContent.UI.States.UIVirtualKeyboard._textBoxHeight, Terraria.UI.UIElement.Activate(), Terraria.UI.UserInterface.ActiveInstance, Terraria.UI.UIElement.Append(), Terraria.UI.IngameFancyUI.CanShowVirtualKeyboard(), Terraria.GameContent.UI.States.UIVirtualKeyboard.CanSubmit, Terraria.Player.chest, Terraria.UI.IngameFancyUI.Close(), Terraria.GameContent.UI.States.UIVirtualKeyboard.CopyTextToChest(), Terraria.GameContent.UI.States.UIVirtualKeyboard.CopyTextToSign(), Terraria.GameContent.UI.States.UIVirtualKeyboard.CustomTextValidationForUpdate, Terraria.UI.UIElement.Deactivate(), Terraria.Main.DrawWindowsIMEPanel(), Terraria.Main.editChest, Terraria.Main.editSign, Terraria.UI.UIElement.Elements, Terraria.Main.gameMenu, Terraria.Main.GetInputText(), Terraria.Main.HandleIME(), Terraria.Main.inputTextEnter, Terraria.Main.inputTextEscape, Terraria.Main.instance, Terraria.Main.myPlayer, Terraria.GameContent.UI.States.UIVirtualKeyboard.OffsetDown, Terraria.GameContent.UI.States.UIVirtualKeyboard.outerLayer1, Terraria.GameContent.UI.States.UIVirtualKeyboard.outerLayer2, Terraria.UI.StyleDimension.Pixels, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.Elements.UIText.Recalculate(), Terraria.GameContent.UI.Elements.UITextPanel< T >.Recalculate(), Terraria.UI.UIElement.Recalculate(), Terraria.UI.UIElement.RecalculateChildren(), Terraria.UI.UIElement.Remove(), Terraria.UI.ChestUI.RenameChestCancel(), Terraria.UI.ChestUI.RenameChestSubmit(), Terraria.UI.UserInterface.ResetLasts(), Terraria.GameContent.UI.States.UIVirtualKeyboard.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIVirtualKeyboard.ShouldHideText, Terraria.GameContent.UI.States.UIVirtualKeyboard.ShouldShowKeyboard(), Terraria.GameContent.UI.States.UIVirtualKeyboard.Submit(), Terraria.GameContent.UI.States.UIVirtualKeyboard.Text, Terraria.Main.tileColor, Terraria.UI.UIElement.Top, Terraria.GameContent.UI.States.UIVirtualKeyboard.TryEscapingMenu(), and Terraria.GameContent.UI.States.UIVirtualKeyboard.UpdateOffsetDown().