TModLoader: Terraria.ModLoader.IO.WorldIO.ReadWorldHeader
ReadWorldHeader()
static void Terraria.ModLoader.IO.WorldIO.ReadWorldHeader (WorldFileData data) inline static package
    {
        string path = Path.ChangeExtension(data.Path, ".twld");
        bool isCloudSave = data.IsCloudSave;
        if (!FileUtilities.Exists(path, isCloudSave))
        {
            return;
        }
        try
        {
            using Stream stream = (isCloudSave ? ((Stream)new MemoryStream(SocialAPI.Cloud.Read(path))) : ((Stream)new FileStream(path, FileMode.Open)));
            using BinaryReader reader = new BigEndianReader(new GZipStream(stream, CompressionMode.Decompress));
            if (reader.ReadByte() != 10)
            {
                throw new IOException("Root tag not a TagCompound");
            }
            TagIO.ReadTagImpl(8, reader);
            if (reader.ReadByte() == 10 && !((string)TagIO.ReadTagImpl(8, reader) != "0header"))
            {
                LoadWorldHeader(data, (TagCompound)TagIO.ReadTagImpl(10, reader));
            }
        }
        catch (Exception ex)
        {
            Logging.tML.Warn((object)$"Error reading .twld header from: {path} (IsCloudSave={isCloudSave})", ex);
        }
    }
References Terraria.Social.SocialAPI.Cloud, Terraria.Utilities.FileUtilities.Exists(), Terraria.IO.FileData.IsCloudSave, Terraria.ModLoader.IO.WorldIO.LoadWorldHeader(), Terraria.IO.FileData.Path, Terraria.ModLoader.IO.TagIO.ReadTagImpl(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.IO.WorldFile.GetAllMetadata().