TModLoader: Terraria.ModLoader.IO.WorldIO.SaveHeader
SaveHeader()
static TagCompound Terraria.ModLoader.IO.WorldIO.SaveHeader () inline static private
    {
        return new TagCompound
        {
            ["modHeaders"] = SaveModHeaders(),
            ["usedMods"] = SaveUsedMods(),
            ["usedModPack"] = SaveUsedModPack(),
            ["generatedWithMods"] = SaveGeneratedWithMods()
        };
    }
References Terraria.ModLoader.IO.WorldIO.SaveGeneratedWithMods(), Terraria.ModLoader.IO.WorldIO.SaveModHeaders(), Terraria.ModLoader.IO.WorldIO.SaveUsedModPack(), and Terraria.ModLoader.IO.WorldIO.SaveUsedMods().
Referenced by Terraria.ModLoader.IO.WorldIO.Save().