TModLoader: Terraria.ModLoader.IO.WorldIO.LoadNPCs
LoadNPCs()
static void Terraria.ModLoader.IO.WorldIO.LoadNPCs (IList< TagCompound > list) inline static package
Definition at line 207 of file WorldIO.cs.
    {
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        if (list == null)
        {
            return;
        }
        int nextFreeNPC = 0;
        foreach (TagCompound tag in list)
        {
            NPC npc = null;
            for (; nextFreeNPC < Main.maxNPCs && Main.npc[nextFreeNPC].active; nextFreeNPC++)
            {
            }
            if (tag.GetString("mod") == "Terraria")
            {
                int npcId = NPCID.Search.GetId(tag.GetString("name"));
                float x = tag.GetFloat("x");
                float y = tag.GetFloat("y");
                int index;
                for (index = 0; index < Main.maxNPCs; index++)
                {
                    npc = Main.npc[index];
                    if (npc.active && npc.type == npcId && npc.position.X == x && npc.position.Y == y)
                    {
                        break;
                    }
                }
                if (index == Main.maxNPCs)
                {
                    if (nextFreeNPC == Main.maxNPCs)
                    {
                        ModContent.GetInstance<UnloadedSystem>().unloadedNPCs.Add(tag);
                        continue;
                    }
                    npc = Main.npc[nextFreeNPC];
                    npc.SetDefaults(npcId);
                    npc.position = new Vector2(x, y);
                }
            }
            else
            {
                if (!ModContent.TryFind<ModNPC>(tag.GetString("mod"), tag.GetString("name"), out var modNpc))
                {
                    ModContent.GetInstance<UnloadedSystem>().unloadedNPCs.Add(tag);
                    continue;
                }
                if (nextFreeNPC == Main.maxNPCs)
                {
                    ModContent.GetInstance<UnloadedSystem>().unloadedNPCs.Add(tag);
                    continue;
                }
                npc = Main.npc[nextFreeNPC];
                npc.SetDefaults(modNpc.Type);
                npc.position.X = tag.GetFloat("x");
                npc.position.Y = tag.GetFloat("y");
                if (npc.townNPC)
                {
                    npc.GivenName = tag.GetString("displayName");
                    npc.homeless = tag.GetBool("homeless");
                    npc.homeTileX = tag.GetInt("homeTileX");
                    npc.homeTileY = tag.GetInt("homeTileY");
                    NPC.ShimmeredTownNPCs[modNpc.Type] = tag.GetBool("isShimmered");
                    npc.townNpcVariationIndex = tag.GetInt("npcTownVariationIndex");
                }
                if (tag.ContainsKey("data"))
                {
                    npc.ModNPC.LoadData((TagCompound)tag["data"]);
                }
            }
            LoadGlobals(npc, tag.GetList<TagCompound>("globalData"));
        }
    }
References Terraria.Entity.active, Terraria.ModLoader.IO.WorldIO.LoadGlobals(), Terraria.Main.maxNPCs, Terraria.NPC.ModNPC, Terraria.Main.npc, Terraria.Entity.position, Terraria.ID.NPCID.Search, Terraria.NPC.SetDefaults(), Terraria.NPC.ShimmeredTownNPCs, Terraria.NPC.townNPC, and Terraria.NPC.type.
Referenced by Terraria.ModLoader.IO.WorldIO.Load(), and Terraria.ModLoader.Default.UnloadedSystem.LoadWorldData().