TModLoader: Terraria.ModLoader.IO.WorldIO.Load
Load()
static void Terraria.ModLoader.IO.WorldIO.Load (string path, bool isCloudSave) inline static package
Definition at line 50 of file WorldIO.cs.
    {
        customDataFail = null;
        path = Path.ChangeExtension(path, ".twld");
        if (FileUtilities.Exists(path, isCloudSave))
        {
            byte[] buf = FileUtilities.ReadAllBytes(path, isCloudSave);
            if (buf[0] != 31 || buf[1] != 139)
            {
                throw new IOException(Path.GetFileName(path) + ":: File Corrupted during Last Save Step. Aborting... ERROR: Missing NBT Header");
            }
            TagCompound tag = TagIO.FromStream(buf.ToMemoryStream());
            TileIO.LoadBasics(tag.GetCompound("tiles"));
            TileIO.LoadContainers(tag.GetCompound("containers"));
            LoadNPCs(tag.GetList<TagCompound>("npcs"));
            try
            {
                TileIO.LoadTileEntities(tag.GetList<TagCompound>("tileEntities"));
            }
            catch (CustomModDataException ex)
            {
                customDataFail = ex;
                throw;
            }
            LoadChestInventory(tag.GetList<TagCompound>("chests"));
            LoadNPCKillCounts(tag.GetList<TagCompound>("killCounts"));
            LoadNPCBestiaryKills(tag.GetList<TagCompound>("bestiaryKills"));
            LoadNPCBestiarySights(tag.GetList<TagCompound>("bestiarySights"));
            LoadNPCBestiaryChats(tag.GetList<TagCompound>("bestiaryChats"));
            LoadAnglerQuest(tag.GetCompound("anglerQuest"));
            LoadTownManager(tag.GetList<TagCompound>("townManager"));
            try
            {
                LoadModData(tag.GetList<TagCompound>("modData"));
            }
            catch (CustomModDataException ex2)
            {
                customDataFail = ex2;
                throw;
            }
            LoadAlteredVanillaFields(tag.GetCompound("alteredVanillaFields"));
        }
    }
References Terraria.ModLoader.IO.WorldIO.customDataFail, Terraria.Utilities.FileUtilities.Exists(), Terraria.ModLoader.IO.TagIO.FromStream(), Terraria.ModLoader.IO.WorldIO.LoadAlteredVanillaFields(), Terraria.ModLoader.IO.WorldIO.LoadAnglerQuest(), Terraria.ModLoader.IO.TileIO.LoadBasics(), Terraria.ModLoader.IO.WorldIO.LoadChestInventory(), Terraria.ModLoader.IO.TileIO.LoadContainers(), Terraria.ModLoader.IO.WorldIO.LoadModData(), Terraria.ModLoader.IO.WorldIO.LoadNPCBestiaryChats(), Terraria.ModLoader.IO.WorldIO.LoadNPCBestiaryKills(), Terraria.ModLoader.IO.WorldIO.LoadNPCBestiarySights(), Terraria.ModLoader.IO.WorldIO.LoadNPCKillCounts(), Terraria.ModLoader.IO.WorldIO.LoadNPCs(), Terraria.ModLoader.IO.TileIO.LoadTileEntities(), Terraria.ModLoader.IO.WorldIO.LoadTownManager(), and Terraria.Utilities.FileUtilities.ReadAllBytes().
Referenced by Terraria.IO.WorldFile.LoadWorld().