TModLoader: Terraria.ModLoader.IO.WorldIO.Save
Save()
static void Terraria.ModLoader.IO.WorldIO.Save (string path, bool isCloudSave) inline static package
Definition at line 23 of file WorldIO.cs.
    {
        path = Path.ChangeExtension(path, ".twld");
        if (FileUtilities.Exists(path, isCloudSave))
        {
            FileUtilities.Copy(path, path + ".bak", isCloudSave);
        }
        TagCompound tag = new TagCompound
        {
            ["0header"] = SaveHeader(),
            ["chests"] = SaveChestInventory(),
            ["tiles"] = TileIO.SaveBasics(),
            ["containers"] = TileIO.SaveContainers(),
            ["npcs"] = SaveNPCs(),
            ["tileEntities"] = TileIO.SaveTileEntities(),
            ["killCounts"] = SaveNPCKillCounts(),
            ["bestiaryKills"] = SaveNPCBestiaryKills(),
            ["bestiarySights"] = SaveNPCBestiarySights(),
            ["bestiaryChats"] = SaveNPCBestiaryChats(),
            ["anglerQuest"] = SaveAnglerQuest(),
            ["townManager"] = SaveTownManager(),
            ["modData"] = SaveModData(),
            ["alteredVanillaFields"] = SaveAlteredVanillaFields()
        };
        FileUtilities.WriteTagCompound(path, isCloudSave, tag);
    }
References Terraria.Utilities.FileUtilities.Copy(), Terraria.Utilities.FileUtilities.Exists(), Terraria.ModLoader.IO.WorldIO.SaveAlteredVanillaFields(), Terraria.ModLoader.IO.WorldIO.SaveAnglerQuest(), Terraria.ModLoader.IO.TileIO.SaveBasics(), Terraria.ModLoader.IO.WorldIO.SaveChestInventory(), Terraria.ModLoader.IO.TileIO.SaveContainers(), Terraria.ModLoader.IO.WorldIO.SaveHeader(), Terraria.ModLoader.IO.WorldIO.SaveModData(), Terraria.ModLoader.IO.WorldIO.SaveNPCBestiaryChats(), Terraria.ModLoader.IO.WorldIO.SaveNPCBestiaryKills(), Terraria.ModLoader.IO.WorldIO.SaveNPCBestiarySights(), Terraria.ModLoader.IO.WorldIO.SaveNPCKillCounts(), Terraria.ModLoader.IO.WorldIO.SaveNPCs(), Terraria.ModLoader.IO.TileIO.SaveTileEntities(), Terraria.ModLoader.IO.WorldIO.SaveTownManager(), and Terraria.Utilities.FileUtilities.WriteTagCompound().
Referenced by Terraria.IO.WorldFile.InternalSaveWorld().