TModLoader: Terraria.ModLoader.IO.WorldIO.SaveNPCs
SaveNPCs()
static List< TagCompound > Terraria.ModLoader.IO.WorldIO.SaveNPCs () inline static package
Definition at line 130 of file WorldIO.cs.
    {
        List<TagCompound> list = new List<TagCompound>();
        TagCompound data = new TagCompound();
        for (int index = 0; index < Main.maxNPCs; index++)
        {
            NPC npc = Main.npc[index];
            if (!npc.active || !NPCLoader.SavesAndLoads(npc))
            {
                continue;
            }
            List<TagCompound> globalData = new List<TagCompound>();
            EntityGlobalsEnumerator<GlobalNPC> enumerator = NPCLoader.HookSaveData.Enumerate(npc).GetEnumerator();
            while (enumerator.MoveNext())
            {
                GlobalNPC g = enumerator.Current;
                if (g is UnloadedGlobalNPC unloadedGlobalNPC)
                {
                    globalData.AddRange(unloadedGlobalNPC.data);
                    continue;
                }
                g.SaveData(npc, data);
                if (data.Count != 0)
                {
                    globalData.Add(new TagCompound
                    {
                        ["mod"] = g.Mod.Name,
                        ["name"] = g.Name,
                        ["data"] = data
                    });
                    data = new TagCompound();
                }
            }
            TagCompound tag;
            if (NPCLoader.IsModNPC(npc))
            {
                npc.ModNPC.SaveData(data);
                tag = new TagCompound
                {
                    ["mod"] = npc.ModNPC.Mod.Name,
                    ["name"] = npc.ModNPC.Name
                };
                if (data.Count != 0)
                {
                    tag["data"] = data;
                    data = new TagCompound();
                }
                if (npc.townNPC)
                {
                    tag["displayName"] = npc.GivenName;
                    tag["homeless"] = npc.homeless;
                    tag["homeTileX"] = npc.homeTileX;
                    tag["homeTileY"] = npc.homeTileY;
                    tag["isShimmered"] = NPC.ShimmeredTownNPCs[npc.type];
                    tag["npcTownVariationIndex"] = npc.townNpcVariationIndex;
                }
            }
            else
            {
                if (globalData.Count == 0)
                {
                    continue;
                }
                tag = new TagCompound
                {
                    ["mod"] = "Terraria",
                    ["name"] = NPCID.Search.GetName(npc.type)
                };
            }
            tag["x"] = npc.position.X;
            tag["y"] = npc.position.Y;
            tag["globalData"] = globalData;
            list.Add(tag);
        }
        return list;
    }
References Terraria.Entity.active, Terraria.ModLoader.IO.TagCompound.Count, Terraria.NPC.GivenName, Terraria.NPC.homeless, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Terraria.ModLoader.NPCLoader.HookSaveData, Terraria.ModLoader.NPCLoader.IsModNPC(), Terraria.Main.maxNPCs, Terraria.NPC.ModNPC, Terraria.Main.npc, Terraria.Entity.position, Terraria.ModLoader.NPCLoader.SavesAndLoads(), Terraria.ID.NPCID.Search, Terraria.NPC.ShimmeredTownNPCs, Terraria.NPC.townNPC, Terraria.NPC.townNpcVariationIndex, and Terraria.NPC.type.
Referenced by Terraria.ModLoader.IO.WorldIO.Save().