TModLoader: Terraria.Social.Steam.WorkshopHelper.PublishMod
PublishMod()
static void Terraria.Social.Steam.WorkshopHelper.PublishMod (LocalMod mod, string iconPath) inline static package
Definition at line 1158 of file WorkshopHelper.cs.
    {
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        TmodFile modFile = mod.modFile;
        BuildProperties bp = mod.properties;
        if (bp.buildVersion != modFile.TModLoaderVersion)
        {
            throw new WebException(Language.GetTextValue("tModLoader.OutdatedModCantPublishError"));
        }
        string changeLogFile = Path.Combine(ModCompile.ModSourcePath, modFile.Name, "changelog.txt");
        string changeLog = ((!File.Exists(changeLogFile)) ? "" : File.ReadAllText(changeLogFile));
        string workshopDescFile = Path.Combine(ModCompile.ModSourcePath, modFile.Name, "description_workshop.txt");
        string workshopDesc = ((!File.Exists(workshopDescFile)) ? bp.description : File.ReadAllText(workshopDescFile));
        NameValueCollection values = new NameValueCollection
        {
            { "displayname", bp.displayName },
            {
                "displaynameclean",
                string.Join("", from x in ChatManager.ParseMessage(bp.displayName, Color.White)
                    where x.GetType() == typeof(TextSnippet)
                    select x.Text)
            },
            { "name", modFile.Name },
            {
                "version",
                $"{bp.version}"
            },
            { "author", bp.author },
            { "homepage", bp.homepage },
            { "description", workshopDesc },
            { "iconpath", iconPath },
            {
                "sourcesfolder",
                Path.Combine(ModCompile.ModSourcePath, modFile.Name)
            },
            {
                "modloaderversion",
                $"{modFile.TModLoaderVersion}"
            },
            {
                "modreferences",
                string.Join(", ", bp.modReferences.Select((BuildProperties.ModReference x) => x.mod))
            },
            {
                "modside",
                bp.side.ToFriendlyString()
            },
            { "changelog", changeLog }
        };
        if (string.IsNullOrWhiteSpace(values["author"]))
        {
            throw new WebException("You need to specify an author in build.txt");
        }
        if (string.IsNullOrWhiteSpace(values["version"]))
        {
            throw new WebException("You need to specify a version in build.txt");
        }
        if (!Main.dedServ)
        {
            Main.MenuUI.SetState(new WorkshopPublishInfoStateForMods(Interface.modSources, modFile, values));
            return;
        }
        SocialAPI.LoadSteam();
        WorkshopItemPublishSettings publishSetttings = new WorkshopItemPublishSettings
        {
            Publicity = WorkshopItemPublicSettingId.Public,
            UsedTags = Array.Empty<WorkshopTagOption>(),
            PreviewImagePath = iconPath
        };
        SteamedWraps.SteamClient = true;
        SocialAPI.Workshop.PublishMod(modFile, values, publishSetttings);
    }
References Terraria.Main.dedServ, Terraria.Localization.Language.GetTextValue(), Terraria.Social.SocialAPI.LoadSteam(), Terraria.Main.MenuUI, Terraria.ModLoader.Core.LocalMod.modFile, Terraria.ModLoader.Core.ModCompile.ModSourcePath, Terraria.ModLoader.UI.Interface.modSources, Terraria.ModLoader.Core.TmodFile.Name, Terraria.UI.Chat.ChatManager.ParseMessage(), Terraria.ModLoader.Core.LocalMod.properties, Terraria.ModLoader.Core.TmodFile.TModLoaderVersion, and Terraria.Social.SocialAPI.Workshop.
Referenced by Terraria.ModLoader.UI.UIModSourceItem.PublishMod(), and Terraria.ModLoader.UI.UIModSourceItem.PublishModCommandLine().