TModLoader: Terraria.Social.Steam.WorkshopHelper.GetPublishIdLocal
GetPublishIdLocal()
static bool Terraria.Social.Steam.WorkshopHelper.GetPublishIdLocal (TmodFile modFile, out ulong publishId) inline static package
Definition at line 1080 of file WorkshopHelper.cs.
    {
        publishId = 0uL;
        if (modFile == null || !ModOrganizer.TryReadManifest(ModOrganizer.GetParentDir(modFile.path), out var info))
        {
            return false;
        }
        publishId = info.workshopEntryId;
        return true;
    }
References Terraria.ModLoader.Core.ModOrganizer.GetParentDir(), Terraria.ModLoader.Core.TmodFile.path, and Terraria.ModLoader.Core.ModOrganizer.TryReadManifest().
Referenced by Terraria.Social.Steam.SteamedWraps.BeginPlaytimeTracking(), Terraria.Social.Steam.WorkshopBrowserModule.GetModIdFromLocalFiles(), and Terraria.ModLoader.UI.UIModInfo.Show().