TModLoader: Terraria.Social.Steam.WorkshopHelper.TryGetPublishIdByInternalName
TryGetPublishIdByInternalName()
static bool Terraria.Social.Steam.WorkshopHelper.TryGetPublishIdByInternalName (QueryParameters query, out List< string > modIds) inline static package
    {
        modIds = new List<string>();
        if (!TryGetModDownloadItemsByInternalName(query, out var items))
        {
            return false;
        }
        for (int i = 0; i < query.searchModSlugs.Length; i++)
        {
            if (items[i] == null)
            {
                Logging.tML.Info((object)("Unable to find the PublishID for " + query.searchModSlugs[i]));
                modIds.Add("0");
            }
            else
            {
                modIds.Add(items[i].PublishId.m_ModPubId);
            }
        }
        return true;
    }
References Terraria.ModLoader.Logging.tML, and Terraria.Social.Steam.WorkshopHelper.TryGetModDownloadItemsByInternalName().
Referenced by Terraria.ModLoader.UI.UIModPackItem.GetModPackBrowserIds(), and Terraria.Social.Steam.WorkshopSocialModule.TryCalculateWorkshopDeps().