TModLoader: Terraria.Social.Steam.WorkshopHelper.GetWorkshopFolder
GetWorkshopFolder()
static string Terraria.Social.Steam.WorkshopHelper.GetWorkshopFolder (AppId_t app) inline static
Definition at line 1039 of file WorkshopHelper.cs.
    {
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        if (Program.LaunchParameters.TryGetValue("-steamworkshopfolder", out var workshopLocCustom))
        {
            if (Directory.Exists(workshopLocCustom))
            {
                return workshopLocCustom;
            }
            Logging.tML.Warn((object)("-steamworkshopfolder path not found: " + workshopLocCustom));
        }
        string steamClientPath = null;
        if (SteamedWraps.SteamClient)
        {
            SteamApps.GetAppInstallDir(app, ref steamClientPath, 1000u);
        }
        if (steamClientPath == null)
        {
            steamClientPath = ".";
        }
        steamClientPath = Path.Combine(steamClientPath, "..", "..", "workshop");
        if (SteamedWraps.SteamClient || (!SteamedWraps.SteamAvailable && !Program.LaunchParameters.ContainsKey("-nosteam") && Directory.Exists(steamClientPath)))
        {
            return steamClientPath;
        }
        return Path.Combine("steamapps", "workshop");
    }
References Terraria.Program.LaunchParameters, Terraria.Social.Steam.SteamedWraps.SteamAvailable, Terraria.Social.Steam.SteamedWraps.SteamClient, and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.Social.Steam.WorkshopBrowserModule.EnsureInstallationComplete(), Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.GetListOfSubscribedItemsPaths(), and Terraria.Social.SocialAPI.Initialize().