TModLoader: Terraria.ModLoader.IO.TileIO.ReadContainers
ReadContainers()
static void Terraria.ModLoader.IO.TileIO.ReadContainers (BinaryReader reader) inline static package
    {
        byte[] flags = new byte[1];
        reader.Read(flags, 0, reader.ReadByte());
        if ((flags[0] & 1) == 1)
        {
            ContainerTables tables = ContainerTables.Create();
            int count = reader.ReadUInt16();
            for (int k = 0; k < count; k++)
            {
                tables.headSlots[reader.ReadUInt16()] = (ModContent.TryFind<ModItem>(reader.ReadString(), reader.ReadString(), out var item3) ? item3.Item.headSlot : 0);
            }
            count = reader.ReadUInt16();
            for (int j = 0; j < count; j++)
            {
                tables.bodySlots[reader.ReadUInt16()] = (ModContent.TryFind<ModItem>(reader.ReadString(), reader.ReadString(), out var item2) ? item2.Item.bodySlot : 0);
            }
            count = reader.ReadUInt16();
            for (int i = 0; i < count; i++)
            {
                tables.legSlots[reader.ReadUInt16()] = (ModContent.TryFind<ModItem>(reader.ReadString(), reader.ReadString(), out var item) ? item.Item.legSlot : 0);
            }
            ReadContainerData(reader, tables);
        }
    }
References Terraria.ModLoader.IO.TileIO.ContainerTables.Create(), Terraria.ModLoader.ModItem.Item, Terraria.Item.legSlot, and Terraria.ModLoader.IO.TileIO.ReadContainerData().
Referenced by Terraria.ModLoader.IO.TileIO.LoadContainers().