TModLoader: Terraria.ModLoader.IO.TileIO.SaveContainers
SaveContainers()
static TagCompound Terraria.ModLoader.IO.TileIO.SaveContainers () inline static package
    {
        MemoryStream ms = new MemoryStream();
        BinaryWriter writer = new BinaryWriter(ms);
        byte[] flags = new byte[1];
        byte numFlags = 0;
        ISet<int> headSlots = new HashSet<int>();
        ISet<int> bodySlots = new HashSet<int>();
        ISet<int> legSlots = new HashSet<int>();
        for (int i = 0; i < Main.maxTilesX; i++)
        {
            for (int j = 0; j < Main.maxTilesY; j++)
            {
                Tile tile = Main.tile[i, j];
                if (!tile.active() || (tile.type != 128 && tile.type != 269))
                {
                    continue;
                }
                int slot4 = tile.frameX / 100;
                int position = tile.frameY / 18;
                if (HasModArmor(slot4, position))
                {
                    switch (position)
                    {
                    case 0:
                        headSlots.Add(slot4);
                        break;
                    case 1:
                        bodySlots.Add(slot4);
                        break;
                    case 2:
                        legSlots.Add(slot4);
                        break;
                    }
                    flags[0] |= 1;
                    numFlags = 1;
                }
            }
        }
        int tileEntity = 0;
        List<TagCompound> itemFrames = new List<TagCompound>();
        foreach (KeyValuePair<int, TileEntity> entity in TileEntity.ByID)
        {
            if (entity.Value is TEItemFrame itemFrame)
            {
                List<TagCompound> globalData = ItemIO.SaveGlobals(itemFrame.item);
                if (globalData != null || ItemLoader.NeedsModSaving(itemFrame.item))
                {
                    itemFrames.Add(new TagCompound
                    {
                        ["id"] = tileEntity,
                        ["item"] = ItemIO.Save(itemFrame.item, globalData)
                    });
                    numFlags = 1;
                }
            }
            if (!(entity.Value is ModTileEntity))
            {
                tileEntity++;
            }
        }
        if (numFlags == 0)
        {
            return null;
        }
        writer.Write(numFlags);
        writer.Write(flags, 0, numFlags);
        if ((flags[0] & 1) == 1)
        {
            writer.Write((ushort)headSlots.Count);
            foreach (int slot3 in headSlots)
            {
                writer.Write((ushort)slot3);
                ModItem item3 = ItemLoader.GetItem(EquipLoader.slotToId[EquipType.Head][slot3]);
                writer.Write(item3.Mod.Name);
                writer.Write(item3.Name);
            }
            writer.Write((ushort)bodySlots.Count);
            foreach (int slot2 in bodySlots)
            {
                writer.Write((ushort)slot2);
                ModItem item2 = ItemLoader.GetItem(EquipLoader.slotToId[EquipType.Body][slot2]);
                writer.Write(item2.Mod.Name);
                writer.Write(item2.Name);
            }
            writer.Write((ushort)legSlots.Count);
            foreach (int slot in legSlots)
            {
                writer.Write((ushort)slot);
                ModItem item = ItemLoader.GetItem(EquipLoader.slotToId[EquipType.Legs][slot]);
                writer.Write(item.Mod.Name);
                writer.Write(item.Name);
            }
            WriteContainerData(writer);
        }
        TagCompound tag = new TagCompound();
        tag.Set("data", ms.ToArray());
        if (itemFrames.Count > 0)
        {
            tag.Set("itemFrames", itemFrames);
        }
        return tag;
    }
References Terraria.Tile.active(), Terraria.DataStructures.TileEntity.ByID, Terraria.ModLoader.ItemLoader.GetItem(), Terraria.ModLoader.IO.TileIO.HasModArmor(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.ModLoader.ModType< TEntity, TModType >.Mod, Terraria.ModLoader.Mod.Name, Terraria.ModLoader.ModType< TEntity, TModType >.Name, Terraria.ModLoader.ItemLoader.NeedsModSaving(), Terraria.ModLoader.IO.ItemIO.Save(), Terraria.ModLoader.IO.ItemIO.SaveGlobals(), Terraria.ModLoader.EquipLoader.slotToId, Terraria.Main.tile, Terraria.Tile.type, and Terraria.ModLoader.IO.TileIO.WriteContainerData().
Referenced by Terraria.ModLoader.IO.WorldIO.Save().