TModLoader: Terraria.ModLoader.IO.TileIO.Tiles
Tiles
TileIOImpl Terraria.ModLoader.IO.TileIO.Tiles = new TileIOImpl() static package
Definition at line 294 of file TileIO.cs.
Referenced by Terraria.ModLoader.TileLoader.CanGrowModCactus(), Terraria.ModLoader.IO.TileIO.ClearWorld(), Terraria.ModLoader.Default.LegacyUnloadedTilesSystem.ConvertTiles(), Terraria.ModLoader.IO.TileIO.LoadBasics(), Terraria.ModLoader.Default.UnloadedTile.MouseOver(), Terraria.ModLoader.IO.TileIO.ResetUnloadedTypes(), Terraria.ModLoader.IO.TileIO.SaveBasics(), Terraria.ModLoader.Default.UnloadedChest.SetStaticDefaults(), Terraria.ModLoader.Default.UnloadedDresser.SetStaticDefaults(), Terraria.ModLoader.Default.UnloadedNonSolidTile.SetStaticDefaults(), Terraria.ModLoader.Default.UnloadedSemiSolidTile.SetStaticDefaults(), Terraria.ModLoader.Default.UnloadedSolidTile.SetStaticDefaults(), and Terraria.ModLoader.Default.UnloadedSupremeFurniture.SetStaticDefaults().