TModLoader: Terraria.ModLoader.IO.TileIO.HasModArmor
HasModArmor()
static bool Terraria.ModLoader.IO.TileIO.HasModArmor (int slot, int position) inline static private
    {
        return position switch
        {
            0 => slot >= ArmorIDs.Head.Count,
            1 => slot >= ArmorIDs.Body.Count,
            2 => slot >= ArmorIDs.Legs.Count,
            _ => false,
        };
    }
References Terraria.ID.ArmorIDs.Head.Count, Terraria.ID.ArmorIDs.Body.Count, and Terraria.ID.ArmorIDs.Legs.Count.
Referenced by Terraria.ModLoader.IO.TileIO.SaveContainers(), Terraria.ModLoader.IO.TileIO.VanillaSaveFrames(), and Terraria.ModLoader.IO.TileIO.WriteContainerData().