TModLoader: Terraria.ModLoader.IO.TileIO.ReadTileData
ReadTileData()
static void Terraria.ModLoader.IO.TileIO.ReadTileData (BinaryReader reader, TileEntry[] tileEntriesLookup, WallEntry[] wallEntriesLookup, out List< PosData< ushort > > wallPosMapList, out List< PosData< ushort > > tilePosMapList) inline static package
Definition at line 574 of file TileIO.cs.
    {
        int i = 0;
        int j = 0;
        bool nextModTile = false;
        tilePosMapList = new List<PosData<ushort>>();
        wallPosMapList = new List<PosData<ushort>>();
        do
        {
            if (!nextModTile)
            {
                byte skip;
                for (skip = reader.ReadByte(); skip == byte.MaxValue; skip = reader.ReadByte())
                {
                    for (byte l = 0; l < byte.MaxValue; l++)
                    {
                        if (!NextLocation(ref i, ref j))
{
                            return;
                        }
                    }
                }
                for (byte k = 0; k < skip; k++)
                {
                    if (!NextLocation(ref i, ref j))
                    {
                        return;
                    }
                }
            }
            else
            {
                nextModTile = false;
            }
            ReadModTile(ref i, ref j, reader, ref nextModTile, tilePosMapList, wallPosMapList, tileEntriesLookup, wallEntriesLookup);
        }
        while (NextLocation(ref i, ref j));
    }
References Terraria.ModLoader.IO.TileIO.NextLocation(), and Terraria.ModLoader.IO.TileIO.ReadModTile().
Referenced by Terraria.ModLoader.IO.TileIO.LoadLegacy().