TModLoader: Terraria.ModLoader.IO.TileIO.ReadModTile
ReadModTile()
static void Terraria.ModLoader.IO.TileIO.ReadModTile (ref int i, ref int j, BinaryReader reader, ref bool nextModTile, List< PosData< ushort > > wallPosMapList, List< PosData< ushort > > tilePosMapList, TileEntry[] tileEntriesLookup, WallEntry[] wallEntriesLookup) inline static package
Definition at line 613 of file TileIO.cs.
    {
        byte flags = reader.ReadByte();
        Tile tile = Main.tile[i, j];
        if ((flags & 1) == 1)
        {
            tile.active(active: true);
            ushort saveType = reader.ReadUInt16();
            TileEntry tEntry = tileEntriesLookup[saveType];
            tile.type = tEntry.loadedType;
            if (tEntry.frameImportant)
            {
                if ((flags & 2) == 2)
                {
                    tile.frameX = reader.ReadInt16();
                }
                else
                {
                    tile.frameX = reader.ReadByte();
                }
                if ((flags & 4) == 4)
                {
                    tile.frameY = reader.ReadInt16();
                }
                else
                {
                    tile.frameY = reader.ReadByte();
                }
            }
            else
            {
                tile.frameX = -1;
                tile.frameY = -1;
            }
            if ((flags & 8) == 8)
            {
                tile.color(reader.ReadByte());
            }
            if (tEntry.IsUnloaded)
            {
                tilePosMapList.Add(new PosData<ushort>(PosData.CoordsToPos(i, j), tEntry.type));
            }
            WorldGen.tileCounts[tile.type] += ((!((double)j <= Main.worldSurface)) ? 1 : 5);
        }
        if ((flags & 0x10) == 16)
        {
            ushort saveType = reader.ReadUInt16();
            WallEntry wEntry = wallEntriesLookup[saveType];
            tile.wall = wEntry.loadedType;
            if (wEntry.IsUnloaded)
            {
                wallPosMapList.Add(new PosData<ushort>(PosData.CoordsToPos(i, j), wEntry.type));
            }
            if ((flags & 0x20) == 32)
            {
                tile.wallColor(reader.ReadByte());
            }
        }
        if ((flags & 0x40) == 64)
        {
            byte sameCount = reader.ReadByte();
            for (byte k = 0; k < sameCount; k++)
            {
                NextLocation(ref i, ref j);
                Main.tile[i, j].CopyFrom(tile);
                WorldGen.tileCounts[tile.type] += ((!((double)j <= Main.worldSurface)) ? 1 : 5);
            }
        }
        if ((flags & 0x80) == 128)
        {
            nextModTile = true;
        }
    }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.ModLoader.PosData< T >.CoordsToPos(), Terraria.ModLoader.IO.TileIO.NextLocation(), Terraria.Main.tile, Terraria.WorldGen.tileCounts, Terraria.Tile.type, Terraria.Tile.wallColor(), and Terraria.Main.worldSurface.
Referenced by Terraria.ModLoader.IO.TileIO.ReadTileData().