TModLoader: Terraria.ModLoader.IO.TileIO.WriteContainerData
WriteContainerData()
static void Terraria.ModLoader.IO.TileIO.WriteContainerData (BinaryWriter writer) inline static package
    {
        for (int i = 0; i < Main.maxTilesX; i++)
        {
            for (int j = 0; j < Main.maxTilesY; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile.active() && (tile.type == 128 || tile.type == 269))
                {
                    int slot = tile.frameX / 100;
                    int frameX = tile.frameX % 100;
                    int position = tile.frameY / 18;
                    if (HasModArmor(slot, position) && frameX % 36 == 0)
                    {
                        writer.Write(i);
                        writer.Write(j);
                        writer.Write((byte)position);
                        writer.Write((ushort)slot);
                    }
                }
            }
        }
        writer.Write(-1);
    }
References Terraria.Tile.active(), Terraria.ModLoader.IO.TileIO.HasModArmor(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.ModLoader.IO.TileIO.SaveContainers().