TModLoader: Terraria.ModLoader.IO.TileIO.LoadTileEntities
LoadTileEntities()
static void Terraria.ModLoader.IO.TileIO.LoadTileEntities (IList< TagCompound > list) inline static package
Definition at line 735 of file TileIO.cs.
    {
        foreach (TagCompound tag in list)
        {
            string modName = tag.GetString("mod");
            string name = tag.GetString("name");
            Point16 point = new Point16(tag.GetShort("X"), tag.GetShort("Y"));
            ModTileEntity baseModTileEntity = null;
            bool foundTE = true;
            TileEntity tileEntity;
            if (modName != "Terraria")
            {
                if (!ModContent.TryFind<ModTileEntity>(modName, name, out baseModTileEntity))
                {
                    foundTE = false;
                    baseModTileEntity = ModContent.GetInstance<UnloadedTileEntity>();
                }
                tileEntity = ModTileEntity.ConstructFromBase(baseModTileEntity);
                tileEntity.type = (byte)baseModTileEntity.Type;
                tileEntity.Position = point;
                if (!foundTE)
                {
                    (tileEntity as UnloadedTileEntity)?.SetData(tag);
                }
            }
            else if (!TileEntity.ByPosition.TryGetValue(point, out tileEntity))
            {
                continue;
            }
            if (tag.ContainsKey("data"))
            {
                try
                {
                    if (foundTE)
                    {
                        tileEntity.LoadData(tag.GetCompound("data"));
                    }
                    if (tileEntity is UnloadedTileEntity unloadedTE && unloadedTE.TryRestore(out var restoredTE))
                    {
                        tileEntity = restoredTE;
                    }
                }
                catch (Exception e)
                {
                    throw new CustomModDataException((tileEntity as ModTileEntity)?.Mod, "Error in reading " + name + " tile entity data for " + modName, e);
                }
            }
            if (baseModTileEntity != null && tileEntity.IsTileValidForEntity(tileEntity.Position.X, tileEntity.Position.Y))
            {
                tileEntity.ID = TileEntity.AssignNewID();
                TileEntity.ByID[tileEntity.ID] = tileEntity;
                if (TileEntity.ByPosition.TryGetValue(tileEntity.Position, out var other))
                {
                    TileEntity.ByID.Remove(other.ID);
                }
                TileEntity.ByPosition[tileEntity.Position] = tileEntity;
            }
        }
    }
References Terraria.DataStructures.TileEntity.AssignNewID(), Terraria.DataStructures.TileEntity.ByID, Terraria.DataStructures.TileEntity.ByPosition, and Terraria.ModLoader.ModTileEntity.ConstructFromBase().
Referenced by Terraria.ModLoader.IO.WorldIO.Load().