TModLoader: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_SkinComposite_BackArmShirt
DrawPlayer_12_SkinComposite_BackArmShirt()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_SkinComposite_BackArmShirt (ref PlayerDrawSet drawinfo) inline static
    {
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_0534: Unknown result type (might be due to invalid IL or missing references)
        //IL_0536: Unknown result type (might be due to invalid IL or missing references)
        //IL_0541: Unknown result type (might be due to invalid IL or missing references)
        //IL_0548: Unknown result type (might be due to invalid IL or missing references)
        //IL_0550: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0605: Unknown result type (might be due to invalid IL or missing references)
        //IL_061e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0626: Unknown result type (might be due to invalid IL or missing references)
        //IL_0485: Unknown result type (might be due to invalid IL or missing references)
        //IL_0487: Unknown result type (might be due to invalid IL or missing references)
        //IL_0492: Unknown result type (might be due to invalid IL or missing references)
        //IL_0499: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04da: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_034a: Unknown result type (might be due to invalid IL or missing references)
        //IL_034c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_035e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0366: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0309: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_031b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0207: Unknown result type (might be due to invalid IL or missing references)
        //IL_0209: Unknown result type (might be due to invalid IL or missing references)
        //IL_0214: Unknown result type (might be due to invalid IL or missing references)
        //IL_021b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_0420: Unknown result type (might be due to invalid IL or missing references)
        //IL_0422: Unknown result type (might be due to invalid IL or missing references)
        //IL_042d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0434: Unknown result type (might be due to invalid IL or missing references)
        //IL_043c: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0282: Unknown result type (might be due to invalid IL or missing references)
        //IL_028a: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2((float)(drawinfo.drawPlayer.bodyFrame.Width / 2), (float)(drawinfo.drawPlayer.bodyFrame.Height / 2));
        Vector2 vector2 = Main.OffsetsPlayerHeadgear[drawinfo.drawPlayer.bodyFrame.Y / drawinfo.drawPlayer.bodyFrame.Height];
        vector2.Y -= 2f;
        vector += vector2 * (float)(-((Enum)drawinfo.playerEffect).HasFlag((Enum)(object)(SpriteEffects)2).ToDirectionInt());
        vector.Y += drawinfo.torsoOffset;
        float bodyRotation = drawinfo.drawPlayer.bodyRotation;
        Vector2 vector3 = vector;
        Vector2 position = vector;
        Vector2 bodyVect = drawinfo.bodyVect;
        Vector2 compositeOffset_BackArm = GetCompositeOffset_BackArm(ref drawinfo);
        vector3 += compositeOffset_BackArm;
        position += drawinfo.backShoulderOffset;
        bodyVect += compositeOffset_BackArm;
        float rotation = bodyRotation + drawinfo.compositeBackArmRotation;
        bool flag = !drawinfo.drawPlayer.invis;
        bool flag2 = !drawinfo.drawPlayer.invis;
        bool flag3 = drawinfo.drawPlayer.body > 0;
        bool flag4 = !drawinfo.hidesTopSkin;
        bool flag5 = false;
        if (flag3)
        {
            flag &= drawinfo.missingHand;
            if (flag2 && drawinfo.missingArm)
            {
                if (flag4)
                {
                    drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 7].Value, vector3, drawinfo.compBackArmFrame, drawinfo.colorBodySkin, rotation, bodyVect, 1f, drawinfo.playerEffect)
                    {
                        shader = drawinfo.skinDyePacked
                    });
                }
                if (!flag5 && flag4)
                {
                    drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 5].Value, vector3, drawinfo.compBackArmFrame, drawinfo.colorBodySkin, rotation, bodyVect, 1f, drawinfo.playerEffect)
                    {
                        shader = drawinfo.skinDyePacked
                    });
                    flag5 = true;
                }
                flag2 = false;
            }
            if (!drawinfo.drawPlayer.invis || IsArmorDrawnWhenInvisible(drawinfo.drawPlayer.body))
            {
                Texture2D value = TextureAssets.ArmorBodyComposite[drawinfo.drawPlayer.body].Value;
                if (!drawinfo.hideCompositeShoulders)
                {
                    DrawCompositeArmorPiece(ref drawinfo, CompositePlayerDrawContext.BackShoulder, new DrawData(value, position, drawinfo.compBackShoulderFrame, drawinfo.colorArmorBody, bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect)
                    {
                        shader = drawinfo.cBody
                    });
                }
                DrawPlayer_12_1_BalloonFronts(ref drawinfo);
                DrawCompositeArmorPiece(ref drawinfo, CompositePlayerDrawContext.BackArm, new DrawData(value, vector3, drawinfo.compBackArmFrame, drawinfo.colorArmorBody, rotation, bodyVect, 1f, drawinfo.playerEffect)
                {
                    shader = drawinfo.cBody
                });
            }
        }
        if (flag)
        {
            if (flag4)
            {
                if (flag2)
                {
                    drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 7].Value, vector3, drawinfo.compBackArmFrame, drawinfo.colorBodySkin, rotation, bodyVect, 1f, drawinfo.playerEffect)
                    {
                        shader = drawinfo.skinDyePacked
                    });
                }
                if (!flag5 && flag4)
                {
                    drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 5].Value, vector3, drawinfo.compBackArmFrame, drawinfo.colorBodySkin, rotation, bodyVect, 1f, drawinfo.playerEffect)
                    {
                        shader = drawinfo.skinDyePacked
                    });
                    flag5 = true;
                }
            }
            if (!flag3)
            {
                drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 8].Value, vector3, drawinfo.compBackArmFrame, drawinfo.colorUnderShirt, rotation, bodyVect, 1f, drawinfo.playerEffect));
                DrawPlayer_12_1_BalloonFronts(ref drawinfo);
                drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 13].Value, vector3, drawinfo.compBackArmFrame, drawinfo.colorShirt, rotation, bodyVect, 1f, drawinfo.playerEffect));
            }
        }
        if (drawinfo.drawPlayer.handoff > 0)
        {
            Texture2D value2 = TextureAssets.AccHandsOffComposite[drawinfo.drawPlayer.handoff].Value;
            DrawCompositeArmorPiece(ref drawinfo, CompositePlayerDrawContext.BackArmAccessory, new DrawData(value2, vector3, drawinfo.compBackArmFrame, drawinfo.colorArmorBody, rotation, bodyVect, 1f, drawinfo.playerEffect)
            {
                shader = drawinfo.cHandOff
            });
        }
        if (drawinfo.drawPlayer.drawingFootball)
        {
            Main.instance.LoadProjectile(861);
            Texture2D value3 = TextureAssets.Projectile[861].Value;
            Rectangle rectangle = value3.Frame(1, 4);
            Vector2 origin = rectangle.Size() / 2f;
            Vector2 position2 = vector3 + new Vector2((float)(drawinfo.drawPlayer.direction * -2), drawinfo.drawPlayer.gravDir * 4f);
            drawinfo.DrawDataCache.Add(new DrawData(value3, position2, rectangle, drawinfo.colorArmorBody, bodyRotation + (float)Math.PI / 4f * (float)drawinfo.drawPlayer.direction, origin, 0.8f, drawinfo.playerEffect));
        }
    }
References Terraria.GameContent.TextureAssets.AccHandsOffComposite, Terraria.GameContent.TextureAssets.ArmorBodyComposite, Terraria.DataStructures.PlayerDrawLayers.DrawCompositeArmorPiece(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_1_BalloonFronts(), Terraria.DataStructures.PlayerDrawLayers.GetCompositeOffset_BackArm(), Terraria.Main.instance, Terraria.DataStructures.PlayerDrawLayers.IsArmorDrawnWhenInvisible(), Terraria.Main.LoadProjectile(), Terraria.Main.OffsetsPlayerHeadgear, Terraria.GameContent.TextureAssets.Players, Terraria.GameContent.TextureAssets.Projectile, and Terraria.Main.screenPosition.
Referenced by Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin_Composite().