TModLoader: Terraria.DataStructures.PlayerDrawLayers.DrawSittingLegs
DrawSittingLegs()
static void Terraria.DataStructures.PlayerDrawLayers.DrawSittingLegs (ref PlayerDrawSet drawinfo, Texture2D textureToDraw, Color matchingColor, int shaderIndex = 0, bool glowmask = false) inline static private
Definition at line 2743 of file PlayerDrawLayers.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        //IL_029e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02af: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02de: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_0390: Unknown result type (might be due to invalid IL or missing references)
        //IL_0392: Unknown result type (might be due to invalid IL or missing references)
        //IL_0399: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b1: Unknown result type (might be due to invalid IL or missing references)
        Vector2 legsOffset = drawinfo.legsOffset;
        Vector2 vector = new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.legFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.legFrame.Height + 4f)) + drawinfo.drawPlayer.legPosition + drawinfo.legVect;
        Rectangle legFrame = drawinfo.drawPlayer.legFrame;
        vector.Y -= 2f;
        vector.Y += drawinfo.seatYOffset;
        vector += legsOffset;
        int num = 2;
        int num2 = 42;
        int num3 = 2;
        int num4 = 2;
        int num5 = 0;
        int num6 = 0;
        int num7 = 0;
        bool flag = drawinfo.drawPlayer.legs == 101 || drawinfo.drawPlayer.legs == 102 || drawinfo.drawPlayer.legs == 118 || drawinfo.drawPlayer.legs == 99;
        if (drawinfo.drawPlayer.wearsRobe && !flag)
        {
            num = 0;
            num4 = 0;
            num2 = 6;
            vector.Y += 4f;
            legFrame.Y = legFrame.Height * 5;
        }
        switch (drawinfo.drawPlayer.legs)
        {
        case 214:
        case 215:
        case 216:
            num = -6;
            num4 = 2;
            num5 = 2;
            num3 = 4;
            num2 = 6;
            legFrame = drawinfo.drawPlayer.legFrame;
            vector.Y += 2f;
            break;
        case 106:
        case 143:
        case 226:
            num = 0;
            num4 = 0;
            num2 = 6;
            vector.Y += 4f;
            legFrame.Y = legFrame.Height * 5;
            break;
        case 132:
            num = -2;
            num7 = 2;
            break;
        case 193:
        case 194:
            if (drawinfo.drawPlayer.body == 218)
            {
                num = -2;
                num7 = 2;
                vector.Y += 2f;
            }
            break;
        case 210:
            if (glowmask)
            {
                Vector2 vector2 = default(Vector2);
                ((Vector2)(ref vector2))._002Ector((float)Main.rand.Next(-10, 10) * 0.125f, (float)Main.rand.Next(-10, 10) * 0.125f);
                vector += vector2;
            }
            break;
        }
        for (int num8 = num3; num8 >= 0; num8--)
        {
            Vector2 position = vector + new Vector2((float)num, 2f) * new Vector2((float)drawinfo.drawPlayer.direction, 1f);
            Rectangle value = legFrame;
            value.Y += num8 * 2;
            value.Y += num2;
            value.Height -= num2;
            value.Height -= num8 * 2;
            if (num8 != num3)
            {
                value.Height = 2;
            }
            position.X += drawinfo.drawPlayer.direction * num4 * num8 + num6 * drawinfo.drawPlayer.direction;
            if (num8 != 0)
            {
                position.X += num7 * drawinfo.drawPlayer.direction;
            }
            position.Y += num2;
            position.Y += num5;
            DrawData item = new DrawData(textureToDraw, position, value, matchingColor, drawinfo.drawPlayer.legRotation, drawinfo.legVect, 1f, drawinfo.playerEffect);
            item.shader = shaderIndex;
            drawinfo.DrawDataCache.Add(item);
        }
    }
References Terraria.Main.rand, and Terraria.Main.screenPosition.
Referenced by Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_Skin_Composite(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_13_Leggings(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_14_Shoes(), and Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_15_SkinLongCoat().