TModLoader: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem
DrawPlayer_27_HeldItem()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem (ref PlayerDrawSet drawinfo) inline static
Definition at line 5005 of file PlayerDrawLayers.cs.
    {
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0253: Unknown result type (might be due to invalid IL or missing references)
        //IL_0258: Unknown result type (might be due to invalid IL or missing references)
        //IL_0271: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0283: Unknown result type (might be due to invalid IL or missing references)
        //IL_0288: Unknown result type (might be due to invalid IL or missing references)
        //IL_028d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0397: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0500: Unknown result type (might be due to invalid IL or missing references)
        //IL_0505: Unknown result type (might be due to invalid IL or missing references)
        //IL_050a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0446: Unknown result type (might be due to invalid IL or missing references)
        //IL_0451: Unknown result type (might be due to invalid IL or missing references)
        //IL_0456: Unknown result type (might be due to invalid IL or missing references)
        //IL_045b: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0468: Unknown result type (might be due to invalid IL or missing references)
        //IL_046d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0498: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0420: Unknown result type (might be due to invalid IL or missing references)
        //IL_042b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0430: Unknown result type (might be due to invalid IL or missing references)
        //IL_0435: Unknown result type (might be due to invalid IL or missing references)
        //IL_0595: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_056b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0570: Unknown result type (might be due to invalid IL or missing references)
        //IL_0575: Unknown result type (might be due to invalid IL or missing references)
        //IL_0577: Unknown result type (might be due to invalid IL or missing references)
        //IL_0579: Unknown result type (might be due to invalid IL or missing references)
        //IL_0583: Unknown result type (might be due to invalid IL or missing references)
        //IL_0588: Unknown result type (might be due to invalid IL or missing references)
        //IL_067b: Unknown result type (might be due to invalid IL or missing references)
        //IL_067d: Unknown result type (might be due to invalid IL or missing references)
        //IL_067f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0684: Unknown result type (might be due to invalid IL or missing references)
        //IL_0666: Unknown result type (might be due to invalid IL or missing references)
        //IL_066e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0642: Unknown result type (might be due to invalid IL or missing references)
        //IL_0644: Unknown result type (might be due to invalid IL or missing references)
        //IL_0649: Unknown result type (might be due to invalid IL or missing references)
        //IL_064b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0650: Unknown result type (might be due to invalid IL or missing references)
        //IL_0635: Unknown result type (might be due to invalid IL or missing references)
        //IL_0753: Unknown result type (might be due to invalid IL or missing references)
        //IL_074a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0733: Unknown result type (might be due to invalid IL or missing references)
        //IL_072a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0805: Unknown result type (might be due to invalid IL or missing references)
        //IL_080a: Unknown result type (might be due to invalid IL or missing references)
        //IL_080e: Unknown result type (might be due to invalid IL or missing references)
        //IL_082e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0830: Unknown result type (might be due to invalid IL or missing references)
        //IL_083a: Unknown result type (might be due to invalid IL or missing references)
        //IL_083f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0846: Unknown result type (might be due to invalid IL or missing references)
        //IL_084b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0850: Unknown result type (might be due to invalid IL or missing references)
        //IL_0855: Unknown result type (might be due to invalid IL or missing references)
        //IL_0857: Unknown result type (might be due to invalid IL or missing references)
        //IL_085c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0861: Unknown result type (might be due to invalid IL or missing references)
        //IL_086a: Unknown result type (might be due to invalid IL or missing references)
        //IL_086f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0888: Unknown result type (might be due to invalid IL or missing references)
        //IL_088d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0892: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08de: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0910: Unknown result type (might be due to invalid IL or missing references)
        //IL_091a: Unknown result type (might be due to invalid IL or missing references)
        //IL_092a: Unknown result type (might be due to invalid IL or missing references)
        //IL_092e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a45: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a70: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0abb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ade: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0971: Unknown result type (might be due to invalid IL or missing references)
        //IL_0976: Unknown result type (might be due to invalid IL or missing references)
        //IL_097a: Unknown result type (might be due to invalid IL or missing references)
        //IL_099a: Unknown result type (might be due to invalid IL or missing references)
        //IL_09bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_09fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a09: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a19: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b21: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b35: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b46: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b53: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bda: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bee: Unknown result type (might be due to invalid IL or missing references)
        //IL_1511: Unknown result type (might be due to invalid IL or missing references)
        //IL_1513: Unknown result type (might be due to invalid IL or missing references)
        //IL_151c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1521: Unknown result type (might be due to invalid IL or missing references)
        //IL_1528: Unknown result type (might be due to invalid IL or missing references)
        //IL_152c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1549: Unknown result type (might be due to invalid IL or missing references)
        //IL_1550: Unknown result type (might be due to invalid IL or missing references)
        //IL_1556: Unknown result type (might be due to invalid IL or missing references)
        //IL_1424: Unknown result type (might be due to invalid IL or missing references)
        //IL_1426: Unknown result type (might be due to invalid IL or missing references)
        //IL_142f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1434: Unknown result type (might be due to invalid IL or missing references)
        //IL_143b: Unknown result type (might be due to invalid IL or missing references)
        //IL_143f: Unknown result type (might be due to invalid IL or missing references)
        //IL_145c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1463: Unknown result type (might be due to invalid IL or missing references)
        //IL_1469: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c58: Unknown result type (might be due to invalid IL or missing references)
        //IL_1562: Unknown result type (might be due to invalid IL or missing references)
        //IL_1564: Unknown result type (might be due to invalid IL or missing references)
        //IL_156d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1572: Unknown result type (might be due to invalid IL or missing references)
        //IL_1579: Unknown result type (might be due to invalid IL or missing references)
        //IL_157d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1475: Unknown result type (might be due to invalid IL or missing references)
        //IL_1477: Unknown result type (might be due to invalid IL or missing references)
        //IL_1480: Unknown result type (might be due to invalid IL or missing references)
        //IL_1485: Unknown result type (might be due to invalid IL or missing references)
        //IL_148c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1490: Unknown result type (might be due to invalid IL or missing references)
        //IL_106e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1078: Unknown result type (might be due to invalid IL or missing references)
        //IL_1093: Unknown result type (might be due to invalid IL or missing references)
        //IL_1098: Unknown result type (might be due to invalid IL or missing references)
        //IL_109a: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0faf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fcb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffb: Unknown result type (might be due to invalid IL or missing references)
        //IL_101b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1023: Unknown result type (might be due to invalid IL or missing references)
        //IL_102d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1032: Unknown result type (might be due to invalid IL or missing references)
        //IL_103b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1040: Unknown result type (might be due to invalid IL or missing references)
        //IL_1047: Unknown result type (might be due to invalid IL or missing references)
        //IL_104b: Unknown result type (might be due to invalid IL or missing references)
        //IL_15b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_15b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_15be: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_14c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_14f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_110a: Unknown result type (might be due to invalid IL or missing references)
        //IL_112a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1134: Unknown result type (might be due to invalid IL or missing references)
        //IL_1139: Unknown result type (might be due to invalid IL or missing references)
        //IL_1142: Unknown result type (might be due to invalid IL or missing references)
        //IL_1147: Unknown result type (might be due to invalid IL or missing references)
        //IL_1157: Unknown result type (might be due to invalid IL or missing references)
        //IL_115b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1178: Unknown result type (might be due to invalid IL or missing references)
        //IL_117f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1185: Unknown result type (might be due to invalid IL or missing references)
        //IL_10d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_10e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cdd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cec: Unknown result type (might be due to invalid IL or missing references)
        //IL_11aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_11fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_124c: Unknown result type (might be due to invalid IL or missing references)
        //IL_126c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1276: Unknown result type (might be due to invalid IL or missing references)
        //IL_127b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1297: Unknown result type (might be due to invalid IL or missing references)
        //IL_12a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d36: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d41: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d46: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d59: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d66: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_130c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1325: Unknown result type (might be due to invalid IL or missing references)
        //IL_132f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1334: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e55: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e63: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e68: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e73: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ded: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dfc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dcc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db5: Unknown result type (might be due to invalid IL or missing references)
        //IL_136a: Unknown result type (might be due to invalid IL or missing references)
        //IL_138a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1394: Unknown result type (might be due to invalid IL or missing references)
        //IL_13ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_13c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_13d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_13d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f12: Unknown result type (might be due to invalid IL or missing references)
        //IL_1742: Unknown result type (might be due to invalid IL or missing references)
        //IL_1751: Unknown result type (might be due to invalid IL or missing references)
        //IL_175d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1762: Unknown result type (might be due to invalid IL or missing references)
        //IL_1769: Unknown result type (might be due to invalid IL or missing references)
        //IL_176d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1771: Unknown result type (might be due to invalid IL or missing references)
        if (drawinfo.drawPlayer.JustDroppedAnItem)
        {
            return;
        }
        if (drawinfo.drawPlayer.heldProj >= 0 && drawinfo.shadow == 0f && !drawinfo.heldProjOverHand)
        {
            drawinfo.projectileDrawPosition = drawinfo.DrawDataCache.Count;
        }
        Item heldItem = drawinfo.heldItem;
        int num = heldItem.type;
        if (drawinfo.drawPlayer.UsingBiomeTorches)
        {
            switch (num)
            {
            case 8:
                num = drawinfo.drawPlayer.BiomeTorchHoldStyle(num);
                break;
            case 966:
                num = drawinfo.drawPlayer.BiomeCampfireHoldStyle(num);
                break;
            }
        }
        float adjustedItemScale = drawinfo.drawPlayer.GetAdjustedItemScale(heldItem);
        Main.instance.LoadItem(num);
        Texture2D value = TextureAssets.Item[num].Value;
        Vector2 position = default(Vector2);
        ((Vector2)(ref position))._002Ector((float)(int)(drawinfo.ItemLocation.X - Main.screenPosition.X), (float)(int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y));
        Rectangle itemDrawFrame = drawinfo.drawPlayer.GetItemDrawFrame(num);
        drawinfo.itemColor = Lighting.GetColor((int)((double)drawinfo.Position.X + (double)drawinfo.drawPlayer.width * 0.5) / 16, (int)(((double)drawinfo.Position.Y + (double)drawinfo.drawPlayer.height * 0.5) / 16.0));
        if (num == 678)
        {
            drawinfo.itemColor = Color.White;
        }
        if (drawinfo.drawPlayer.shroomiteStealth && heldItem.ranged)
        {
            float num12 = drawinfo.drawPlayer.stealth;
            if ((double)num12 < 0.03)
            {
                num12 = 0.03f;
            }
            float num13 = (1f + num12 * 10f) / 11f;
            drawinfo.itemColor = new Color((int)(byte)((float)(int)((Color)(ref drawinfo.itemColor)).R * num12), (int)(byte)((float)(int)((Color)(ref drawinfo.itemColor)).G * num12), (int)(byte)((float)(int)((Color)(ref drawinfo.itemColor)).B * num13), (int)(byte)((float)(int)((Color)(ref drawinfo.itemColor)).A * num12));
        }
        if (drawinfo.drawPlayer.setVortex && heldItem.ranged)
        {
            float num14 = drawinfo.drawPlayer.stealth;
            if ((double)num14 < 0.03)
            {
                num14 = 0.03f;
            }
            _ = (1f + num14 * 10f) / 11f;
            drawinfo.itemColor = drawinfo.itemColor.MultiplyRGBA(new Color(Vector4.Lerp(Vector4.One, new Vector4(0f, 0.12f, 0.16f, 0f), 1f - num14)));
        }
        bool flag = drawinfo.drawPlayer.itemAnimation > 0 && heldItem.useStyle != 0;
        bool flag2 = heldItem.holdStyle != 0 && !drawinfo.drawPlayer.pulley;
        if (!drawinfo.drawPlayer.CanVisuallyHoldItem(heldItem))
        {
            flag2 = false;
        }
        if (drawinfo.shadow != 0f || drawinfo.drawPlayer.frozen || !(flag || flag2) || num <= 0 || drawinfo.drawPlayer.dead || heldItem.noUseGraphic || (drawinfo.drawPlayer.wet && heldItem.noWet && !ItemID.Sets.WaterTorches[num]) || (drawinfo.drawPlayer.happyFunTorchTime && drawinfo.drawPlayer.inventory[drawinfo.drawPlayer.selectedItem].createTile == 4 && drawinfo.drawPlayer.itemAnimation == 0))
        {
            return;
        }
        _ = drawinfo.drawPlayer.name;
        Color color = default(Color);
        ((Color)(ref color))._002Ector(250, 250, 250, heldItem.alpha);
        Vector2 vector = Vector2.Zero;
        switch (num)
        {
        case 104:
        case 5094:
        case 5095:
            vector = new Vector2(4f, -4f) * drawinfo.drawPlayer.Directions;
            break;
        case 426:
        case 797:
        case 1506:
        case 5096:
        case 5097:
            vector = new Vector2(6f, -6f) * drawinfo.drawPlayer.Directions;
            break;
        case 46:
        {
            Vector3 val = ((Color)(ref drawinfo.itemColor)).ToVector3();
            float amount = Utils.Remap(((Vector3)(ref val)).Length() / 1.731f, 0.3f, 0.5f, 1f, 0f);
            color = Color.Lerp(Color.Transparent, new Color(255, 255, 255, 127) * 0.7f, amount);
            break;
        }
        case 204:
            vector = new Vector2(4f, -6f) * drawinfo.drawPlayer.Directions;
            break;
        case 3349:
            vector = new Vector2(2f, -2f) * drawinfo.drawPlayer.Directions;
            break;
        }
        if (num == 3823)
        {
            ((Vector2)(ref vector))._002Ector((float)(7 * drawinfo.drawPlayer.direction), -7f * drawinfo.drawPlayer.gravDir);
        }
        if (num == 3827)
        {
            ((Vector2)(ref vector))._002Ector((float)(13 * drawinfo.drawPlayer.direction), -13f * drawinfo.drawPlayer.gravDir);
            color = heldItem.GetAlpha(drawinfo.itemColor);
            color = Color.Lerp(color, Color.White, 0.6f);
            ((Color)(ref color)).A = 66;
        }
        Vector2 origin = default(Vector2);
        ((Vector2)(ref origin))._002Ector((float)itemDrawFrame.Width * 0.5f - (float)itemDrawFrame.Width * 0.5f * (float)drawinfo.drawPlayer.direction, (float)itemDrawFrame.Height);
        if (heldItem.useStyle == 9 && drawinfo.drawPlayer.itemAnimation > 0)
        {
            Vector2 vector3 = default(Vector2);
            ((Vector2)(ref vector3))._002Ector(0.5f, 0.4f);
            if (heldItem.type == 5009 || heldItem.type == 5042)
            {
                ((Vector2)(ref vector3))._002Ector(0.26f, 0.5f);
                if (drawinfo.drawPlayer.direction == -1)
                {
                    vector3.X = 1f - vector3.X;
                }
            }
            origin = itemDrawFrame.Size() * vector3;
        }
        if (drawinfo.drawPlayer.gravDir == -1f)
        {
            origin.Y = (float)itemDrawFrame.Height - origin.Y;
        }
        origin += vector;
        float num15 = drawinfo.drawPlayer.itemRotation;
        if (heldItem.useStyle == 8)
        {
            ref float x = ref position.X;
            float num16 = x;
            _ = drawinfo.drawPlayer.direction;
            x = num16 - 0f;
            num15 -= (float)Math.PI / 2f * (float)drawinfo.drawPlayer.direction;
            origin.Y = 2f;
            origin.X += 2 * drawinfo.drawPlayer.direction;
        }
        if (num == 425 || num == 507)
        {
            if (drawinfo.drawPlayer.gravDir == 1f)
            {
                if (drawinfo.drawPlayer.direction == 1)
                {
                    drawinfo.itemEffect = (SpriteEffects)2;
                }
                else
                {
                    drawinfo.itemEffect = (SpriteEffects)3;
                }
            }
            else if (drawinfo.drawPlayer.direction == 1)
            {
                drawinfo.itemEffect = (SpriteEffects)0;
            }
            else
            {
                drawinfo.itemEffect = (SpriteEffects)1;
            }
        }
        if ((num == 946 || num == 4707) && num15 != 0f)
        {
            position.Y -= 22f * drawinfo.drawPlayer.gravDir;
            num15 = -1.57f * (float)(-drawinfo.drawPlayer.direction) * drawinfo.drawPlayer.gravDir;
        }
        ItemSlot.GetItemLight(ref drawinfo.itemColor, heldItem);
        DrawData item;
        switch (num)
        {
        case 3476:
        {
            Texture2D value3 = TextureAssets.Extra[64].Value;
            Rectangle rectangle2 = value3.Frame(1, 9, 0, drawinfo.drawPlayer.miscCounter % 54 / 6);
            Vector2 vector5 = default(Vector2);
            ((Vector2)(ref vector5))._002Ector((float)(rectangle2.Width / 2 * drawinfo.drawPlayer.direction), 0f);
            Vector2 origin3 = rectangle2.Size() / 2f;
            item = new DrawData(value3, (drawinfo.ItemLocation - Main.screenPosition + vector5).Floor(), rectangle2, heldItem.GetAlpha(drawinfo.itemColor).MultiplyRGBA(new Color(new Vector4(0.5f, 0.5f, 0.5f, 0.8f))), drawinfo.drawPlayer.itemRotation, origin3, adjustedItemScale, drawinfo.itemEffect);
            drawinfo.DrawDataCache.Add(item);
            value3 = TextureAssets.GlowMask[195].Value;
            item = new DrawData(value3, (drawinfo.ItemLocation - Main.screenPosition + vector5).Floor(), rectangle2, new Color(250, 250, 250, heldItem.alpha) * 0.5f, drawinfo.drawPlayer.itemRotation, origin3, adjustedItemScale, drawinfo.itemEffect);
            drawinfo.DrawDataCache.Add(item);
            return;
        }
        case 4049:
        {
            Texture2D value2 = TextureAssets.Extra[92].Value;
            Rectangle rectangle = value2.Frame(1, 4, 0, drawinfo.drawPlayer.miscCounter % 20 / 5);
            Vector2 vector4 = default(Vector2);
            ((Vector2)(ref vector4))._002Ector((float)(rectangle.Width / 2 * drawinfo.drawPlayer.direction), 0f);
            vector4 += new Vector2((float)(-10 * drawinfo.drawPlayer.direction), 8f * drawinfo.drawPlayer.gravDir);
            Vector2 origin2 = rectangle.Size() / 2f;
            item = new DrawData(value2, (drawinfo.ItemLocation - Main.screenPosition + vector4).Floor(), rectangle, heldItem.GetAlpha(drawinfo.itemColor), drawinfo.drawPlayer.itemRotation, origin2, adjustedItemScale, drawinfo.itemEffect);
            drawinfo.DrawDataCache.Add(item);
            return;
        }
        case 3779:
        {
            Texture2D texture2D = value;
            Rectangle rectangle3 = texture2D.Frame();
            Vector2 vector6 = default(Vector2);
            ((Vector2)(ref vector6))._002Ector((float)(rectangle3.Width / 2 * drawinfo.drawPlayer.direction), 0f);
            Vector2 origin4 = rectangle3.Size() / 2f;
            float num17 = ((float)drawinfo.drawPlayer.miscCounter / 75f * ((float)Math.PI * 2f)).ToRotationVector2().X * 1f + 0f;
            Color color2 = new Color(120, 40, 222, 0) * (num17 / 2f * 0.3f + 0.85f) * 0.5f;
            num17 = 2f;
            for (float num18 = 0f; num18 < 4f; num18 += 1f)
            {
                item = new DrawData(TextureAssets.GlowMask[218].Value, (drawinfo.ItemLocation - Main.screenPosition + vector6).Floor() + (num18 * ((float)Math.PI / 2f)).ToRotationVector2() * num17, rectangle3, color2, drawinfo.drawPlayer.itemRotation, origin4, adjustedItemScale, drawinfo.itemEffect);
                drawinfo.DrawDataCache.Add(item);
            }
            item = new DrawData(texture2D, (drawinfo.ItemLocation - Main.screenPosition + vector6).Floor(), rectangle3, heldItem.GetAlpha(drawinfo.itemColor).MultiplyRGBA(new Color(new Vector4(0.5f, 0.5f, 0.5f, 0.8f))), drawinfo.drawPlayer.itemRotation, origin4, adjustedItemScale, drawinfo.itemEffect);
            drawinfo.DrawDataCache.Add(item);
            return;
        }
        }
        if (heldItem.useStyle == 5)
        {
            if (Item.staff[num])
            {
                float num19 = drawinfo.drawPlayer.itemRotation + 0.785f * (float)drawinfo.drawPlayer.direction;
                float num2 = 0f;
                float num3 = 0f;
                Vector2 origin5 = default(Vector2);
                ((Vector2)(ref origin5))._002Ector(0f, (float)itemDrawFrame.Height);
                if (num == 3210)
                {
                    num2 = 8 * -drawinfo.drawPlayer.direction;
                    num3 = 2 * (int)drawinfo.drawPlayer.gravDir;
                }
                if (num == 3870)
                {
                    Vector2 val2 = (drawinfo.drawPlayer.itemRotation + (float)Math.PI / 4f * (float)drawinfo.drawPlayer.direction).ToRotationVector2() * new Vector2((float)(-drawinfo.drawPlayer.direction) * 1.5f, drawinfo.drawPlayer.gravDir) * 3f;
                    num2 = (int)val2.X;
                    num3 = (int)val2.Y;
                }
                if (num == 3787)
                {
                    num3 = (int)((float)(8 * (int)drawinfo.drawPlayer.gravDir) * (float)Math.Cos(num19));
                }
                if (num == 3209)
                {
                    Vector2 val3 = (new Vector2(-8f, 0f) * drawinfo.drawPlayer.Directions).RotatedBy(drawinfo.drawPlayer.itemRotation);
                    num2 = val3.X;
                    num3 = val3.Y;
                }
                if (drawinfo.drawPlayer.gravDir == -1f)
                {
                    if (drawinfo.drawPlayer.direction == -1)
                    {
                        num19 += 1.57f;
                        ((Vector2)(ref origin5))._002Ector((float)itemDrawFrame.Width, 0f);
                        num2 -= (float)itemDrawFrame.Width;
                    }
                    else
                    {
                        num19 -= 1.57f;
                        origin5 = Vector2.Zero;
                    }
                }
                else if (drawinfo.drawPlayer.direction == -1)
                {
                    ((Vector2)(ref origin5))._002Ector((float)itemDrawFrame.Width, (float)itemDrawFrame.Height);
                    num2 -= (float)itemDrawFrame.Width;
                }
                ItemLoader.HoldoutOrigin(drawinfo.drawPlayer, ref origin5);
                item = new DrawData(value, new Vector2((float)(int)(drawinfo.ItemLocation.X - Main.screenPosition.X + origin5.X + num2), (float)(int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y + num3)), itemDrawFrame, heldItem.GetAlpha(drawinfo.itemColor), num19, origin5, adjustedItemScale, drawinfo.itemEffect);
                drawinfo.DrawDataCache.Add(item);
                if (num == 3870)
                {
                    item = new DrawData(TextureAssets.GlowMask[238].Value, new Vector2((float)(int)(drawinfo.ItemLocation.X - Main.screenPosition.X + origin5.X + num2), (float)(int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y + num3)), itemDrawFrame, new Color(255, 255, 255, 127), num19, origin5, adjustedItemScale, drawinfo.itemEffect);
                    drawinfo.DrawDataCache.Add(item);
                }
                return;
            }
            if (num == 5118)
            {
                float rotation = drawinfo.drawPlayer.itemRotation + 1.57f * (float)drawinfo.drawPlayer.direction;
                Vector2 vector7 = default(Vector2);
                ((Vector2)(ref vector7))._002Ector((float)itemDrawFrame.Width * 0.5f, (float)itemDrawFrame.Height * 0.5f);
                Vector2 origin6 = default(Vector2);
                ((Vector2)(ref origin6))._002Ector((float)itemDrawFrame.Width * 0.5f, (float)itemDrawFrame.Height);
                Vector2 spinningpoint = new Vector2(10f, 4f) * drawinfo.drawPlayer.Directions;
                spinningpoint = spinningpoint.RotatedBy(drawinfo.drawPlayer.itemRotation);
                item = new DrawData(value, new Vector2((float)(int)(drawinfo.ItemLocation.X - Main.screenPosition.X + vector7.X + spinningpoint.X), (float)(int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y + vector7.Y + spinningpoint.Y)), itemDrawFrame, heldItem.GetAlpha(drawinfo.itemColor), rotation, origin6, adjustedItemScale, drawinfo.itemEffect);
                drawinfo.DrawDataCache.Add(item);
                return;
            }
            int num4 = 10;
            Vector2 vector8 = default(Vector2);
            ((Vector2)(ref vector8))._002Ector((float)(itemDrawFrame.Width / 2), (float)(itemDrawFrame.Height / 2));
            Vector2 vector2 = Main.DrawPlayerItemPos(drawinfo.drawPlayer.gravDir, num);
            num4 = (int)vector2.X;
            vector8.Y = vector2.Y;
            Vector2 origin7 = default(Vector2);
            ((Vector2)(ref origin7))._002Ector((float)(-num4), (float)(itemDrawFrame.Height / 2));
            if (drawinfo.drawPlayer.direction == -1)
            {
                ((Vector2)(ref origin7))._002Ector((float)(itemDrawFrame.Width + num4), (float)(itemDrawFrame.Height / 2));
            }
            item = new DrawData(value, new Vector2((float)(int)(drawinfo.ItemLocation.X - Main.screenPosition.X + vector8.X), (float)(int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y + vector8.Y)), itemDrawFrame, heldItem.GetAlpha(drawinfo.itemColor), drawinfo.drawPlayer.itemRotation, origin7, adjustedItemScale, drawinfo.itemEffect);
            drawinfo.DrawDataCache.Add(item);
            if (heldItem.color != default(Color))
            {
                item = new DrawData(value, new Vector2((float)(int)(drawinfo.ItemLocation.X - Main.screenPosition.X + vector8.X), (float)(int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y + vector8.Y)), itemDrawFrame, heldItem.GetColor(drawinfo.itemColor), drawinfo.drawPlayer.itemRotation, origin7, adjustedItemScale, drawinfo.itemEffect);
                drawinfo.DrawDataCache.Add(item);
            }
            if (heldItem.glowMask != -1)
            {
                item = new DrawData(TextureAssets.GlowMask[heldItem.glowMask].Value, new Vector2((float)(int)(drawinfo.ItemLocation.X - Main.screenPosition.X + vector8.X), (float)(int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y + vector8.Y)), itemDrawFrame, new Color(250, 250, 250, heldItem.alpha), drawinfo.drawPlayer.itemRotation, origin7, adjustedItemScale, drawinfo.itemEffect);
                drawinfo.DrawDataCache.Add(item);
            }
            if (num == 3788)
            {
                float num5 = ((float)drawinfo.drawPlayer.miscCounter / 75f * ((float)Math.PI * 2f)).ToRotationVector2().X * 1f + 0f;
                Color color3 = new Color(80, 40, 252, 0) * (num5 / 2f * 0.3f + 0.85f) * 0.5f;
                for (float num6 = 0f; num6 < 4f; num6 += 1f)
                {
                    item = new DrawData(TextureAssets.GlowMask[220].Value, new Vector2((float)(int)(drawinfo.ItemLocation.X - Main.screenPosition.X + vector8.X), (float)(int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y + vector8.Y)) + (num6 * ((float)Math.PI / 2f) + drawinfo.drawPlayer.itemRotation).ToRotationVector2() * num5, null, color3, drawinfo.drawPlayer.itemRotation, origin7, adjustedItemScale, drawinfo.itemEffect);
                    drawinfo.DrawDataCache.Add(item);
                }
            }
            return;
        }
        if (drawinfo.drawPlayer.gravDir == -1f)
        {
            item = new DrawData(value, position, itemDrawFrame, heldItem.GetAlpha(drawinfo.itemColor), num15, origin, adjustedItemScale, drawinfo.itemEffect);
            drawinfo.DrawDataCache.Add(item);
            if (heldItem.color != default(Color))
            {
                item = new DrawData(value, position, itemDrawFrame, heldItem.GetColor(drawinfo.itemColor), num15, origin, adjustedItemScale, drawinfo.itemEffect);
                drawinfo.DrawDataCache.Add(item);
            }
            if (heldItem.glowMask != -1)
            {
                item = new DrawData(TextureAssets.GlowMask[heldItem.glowMask].Value, position, itemDrawFrame, new Color(250, 250, 250, heldItem.alpha), num15, origin, adjustedItemScale, drawinfo.itemEffect);
                drawinfo.DrawDataCache.Add(item);
            }
            return;
        }
        item = new DrawData(value, position, itemDrawFrame, heldItem.GetAlpha(drawinfo.itemColor), num15, origin, adjustedItemScale, drawinfo.itemEffect);
        drawinfo.DrawDataCache.Add(item);
        if (heldItem.color != default(Color))
        {
            item = new DrawData(value, position, itemDrawFrame, heldItem.GetColor(drawinfo.itemColor), num15, origin, adjustedItemScale, drawinfo.itemEffect);
            drawinfo.DrawDataCache.Add(item);
        }
        if (heldItem.glowMask != -1)
        {
            item = new DrawData(TextureAssets.GlowMask[heldItem.glowMask].Value, position, itemDrawFrame, color, num15, origin, adjustedItemScale, drawinfo.itemEffect);
            drawinfo.DrawDataCache.Add(item);
        }
        if (!heldItem.flame || drawinfo.shadow != 0f)
        {
            return;
        }
        try
        {
            Main.instance.LoadItemFlames(num);
            if (TextureAssets.ItemFlame[num].IsLoaded)
            {
                Color color4 = default(Color);
                ((Color)(ref color4))._002Ector(100, 100, 100, 0);
                int num7 = 7;
                float num8 = 1f;
                float num9 = 0f;
                switch (num)
                {
                case 3045:
                    ((Color)(ref color4))._002Ector(Main.DiscoR, Main.DiscoG, Main.DiscoB, 0);
                    break;
                case 5293:
                    ((Color)(ref color4))._002Ector(50, 50, 100, 20);
                    break;
                case 5353:
                    ((Color)(ref color4))._002Ector(255, 255, 255, 200);
                    break;
                case 4952:
                    num7 = 3;
                    num8 = 0.6f;
                    ((Color)(ref color4))._002Ector(50, 50, 50, 0);
                    break;
                case 5322:
                    ((Color)(ref color4))._002Ector(100, 100, 100, 150);
                    num9 = -2 * drawinfo.drawPlayer.direction;
                    break;
                }
                for (int i = 0; i < num7; i++)
                {
                    float num10 = drawinfo.drawPlayer.itemFlamePos[i].X * adjustedItemScale * num8;
                    float num11 = drawinfo.drawPlayer.itemFlamePos[i].Y * adjustedItemScale * num8;
                    item = new DrawData(TextureAssets.ItemFlame[num].Value, new Vector2((float)(int)(position.X + num10 + num9), (float)(int)(position.Y + num11)), itemDrawFrame, color4, num15, origin, adjustedItemScale, drawinfo.itemEffect);
                    drawinfo.DrawDataCache.Add(item);
                }
            }
        }
        catch
        {
        }
    }
References Terraria.Item.alpha, Terraria.Item.color, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.Main.DrawPlayerItemPos(), Terraria.GameContent.TextureAssets.Extra, Terraria.Item.flame, Terraria.Item.GetAlpha(), Terraria.Item.GetColor(), Terraria.Lighting.GetColor(), Terraria.UI.ItemSlot.GetItemLight(), Terraria.GameContent.TextureAssets.GlowMask, Terraria.Item.glowMask, Terraria.ModLoader.ItemLoader.HoldoutOrigin(), Terraria.Main.instance, Terraria.GameContent.TextureAssets.Item, Terraria.GameContent.TextureAssets.ItemFlame, Terraria.Item.ranged, Terraria.Utils.Remap(), Terraria.Main.screenPosition, Terraria.Item.staff, Terraria.Item.type, Terraria.Item.useStyle, and Terraria.ID.ItemID.Sets.WaterTorches.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().