TModLoader: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_30_BladedGlove
DrawPlayer_30_BladedGlove()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_30_BladedGlove (ref PlayerDrawSet drawinfo) inline static
Definition at line 6121 of file PlayerDrawLayers.cs.
    {
        //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0238: Unknown result type (might be due to invalid IL or missing references)
        //IL_024a: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_016f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0181: Unknown result type (might be due to invalid IL or missing references)
        Item heldItem = drawinfo.heldItem;
        if (heldItem.type <= -1 || !Item.claw[heldItem.type] || drawinfo.shadow != 0f)
        {
            return;
        }
        Main.instance.LoadItem(heldItem.type);
        Asset<Texture2D> asset = TextureAssets.Item[heldItem.type];
        if (!drawinfo.drawPlayer.frozen && (drawinfo.drawPlayer.itemAnimation > 0 || (heldItem.holdStyle != 0 && !drawinfo.drawPlayer.pulley)) && heldItem.type > 0 && !drawinfo.drawPlayer.dead && !heldItem.noUseGraphic && (!drawinfo.drawPlayer.wet || !heldItem.noWet))
        {
            if (drawinfo.drawPlayer.gravDir == -1f)
            {
                DrawData item = new DrawData(asset.Value, new Vector2((float)(int)(drawinfo.ItemLocation.X - Main.screenPosition.X), (float)(int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y)), (Rectangle?)new Rectangle(0, 0, asset.Width(), asset.Height()), heldItem.GetAlpha(drawinfo.itemColor), drawinfo.drawPlayer.itemRotation, new Vector2((float)asset.Width() * 0.5f - (float)asset.Width() * 0.5f * (float)drawinfo.drawPlayer.direction, 0f), drawinfo.drawPlayer.GetAdjustedItemScale(heldItem), drawinfo.itemEffect, 0f);
                drawinfo.DrawDataCache.Add(item);
            }
            else
            {
                DrawData item2 = new DrawData(asset.Value, new Vector2((float)(int)(drawinfo.ItemLocation.X - Main.screenPosition.X), (float)(int)(drawinfo.ItemLocation.Y - Main.screenPosition.Y)), (Rectangle?)new Rectangle(0, 0, asset.Width(), asset.Height()), heldItem.GetAlpha(drawinfo.itemColor), drawinfo.drawPlayer.itemRotation, new Vector2((float)asset.Width() * 0.5f - (float)asset.Width() * 0.5f * (float)drawinfo.drawPlayer.direction, (float)asset.Height()), drawinfo.drawPlayer.GetAdjustedItemScale(heldItem), drawinfo.itemEffect, 0f);
                drawinfo.DrawDataCache.Add(item2);
            }
        }
    }
References Terraria.Item.claw, Terraria.Item.GetAlpha(), Terraria.Item.holdStyle, Terraria.Main.instance, Terraria.GameContent.TextureAssets.Item, Terraria.Main.LoadItem(), Terraria.Item.noUseGraphic, Terraria.Item.noWet, Terraria.Main.screenPosition, and Terraria.Item.type.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().