TModLoader: Terraria.DataStructures.PlayerDrawLayers.DrawCompositeArmorPiece
DrawCompositeArmorPiece()
static void Terraria.DataStructures.PlayerDrawLayers.DrawCompositeArmorPiece (ref PlayerDrawSet drawinfo, CompositePlayerDrawContext context, DrawData data) inline static
    {
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0269: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        //IL_028e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_030c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0314: Unknown result type (might be due to invalid IL or missing references)
        //IL_031f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        //IL_033b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0198: Unknown result type (might be due to invalid IL or missing references)
        //IL_019a: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03da: Unknown result type (might be due to invalid IL or missing references)
        //IL_03df: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0425: Unknown result type (might be due to invalid IL or missing references)
        //IL_0427: Unknown result type (might be due to invalid IL or missing references)
        drawinfo.DrawDataCache.Add(data);
        switch (context)
        {
        case CompositePlayerDrawContext.BackShoulder:
        case CompositePlayerDrawContext.BackArm:
        case CompositePlayerDrawContext.FrontArm:
        case CompositePlayerDrawContext.FrontShoulder:
        {
            if (((Color)(ref drawinfo.armGlowColor)).PackedValue == 0)
            {
                break;
            }
            DrawData item2 = data;
            item2.color = drawinfo.armGlowColor;
            Rectangle value2 = item2.sourceRect.Value;
            value2.Y += 224;
            item2.sourceRect = value2;
            if (drawinfo.drawPlayer.body == 227)
            {
                Vector2 position2 = item2.position;
                Vector2 vector2 = default(Vector2);
                for (int j = 0; j < 2; j++)
                {
                    ((Vector2)(ref vector2))._002Ector((float)Main.rand.Next(-10, 10) * 0.125f, (float)Main.rand.Next(-10, 10) * 0.125f);
                    item2.position = position2 + vector2;
                    if (j == 0)
                    {
                        drawinfo.DrawDataCache.Add(item2);
                    }
                }
            }
            drawinfo.DrawDataCache.Add(item2);
            break;
        }
        case CompositePlayerDrawContext.Torso:
        {
            if (((Color)(ref drawinfo.bodyGlowColor)).PackedValue == 0)
            {
                break;
            }
            DrawData item = data;
            item.color = drawinfo.bodyGlowColor;
            Rectangle value = item.sourceRect.Value;
            value.Y += 224;
            item.sourceRect = value;
            if (drawinfo.drawPlayer.body == 227)
            {
                Vector2 position = item.position;
                Vector2 vector = default(Vector2);
                for (int i = 0; i < 2; i++)
                {
                    ((Vector2)(ref vector))._002Ector((float)Main.rand.Next(-10, 10) * 0.125f, (float)Main.rand.Next(-10, 10) * 0.125f);
                    item.position = position + vector;
                    if (i == 0)
                    {
                        drawinfo.DrawDataCache.Add(item);
                    }
                }
            }
            drawinfo.DrawDataCache.Add(item);
            break;
        }
        }
        if (context == CompositePlayerDrawContext.FrontShoulder && drawinfo.drawPlayer.head == 269)
        {
            Vector2 position3 = drawinfo.helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect;
            DrawData item3 = new DrawData(TextureAssets.Extra[214].Value, position3, drawinfo.drawPlayer.bodyFrame, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
            item3.shader = drawinfo.cHead;
            drawinfo.DrawDataCache.Add(item3);
            item3 = new DrawData(TextureAssets.GlowMask[308].Value, position3, drawinfo.drawPlayer.bodyFrame, drawinfo.headGlowColor, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
            item3.shader = drawinfo.cHead;
            drawinfo.DrawDataCache.Add(item3);
        }
        if (context == CompositePlayerDrawContext.FrontArm && drawinfo.drawPlayer.body == 205)
        {
            Color color = default(Color);
            ((Color)(ref color))._002Ector(100, 100, 100, 0);
            ulong seed = (ulong)(drawinfo.drawPlayer.miscCounter / 4);
            int num = 4;
            for (int k = 0; k < num; k++)
            {
                float num2 = (float)Utils.RandomInt(ref seed, -10, 11) * 0.2f;
                float num3 = (float)Utils.RandomInt(ref seed, -10, 1) * 0.15f;
                DrawData item4 = data;
                Rectangle value3 = item4.sourceRect.Value;
                value3.Y += 224;
                item4.sourceRect = value3;
                item4.position.X += num2;
                item4.position.Y += num3;
                item4.color = color;
                drawinfo.DrawDataCache.Add(item4);
            }
        }
    }
References Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.TextureAssets.GlowMask, Terraria.DataStructures.DrawData.position, Terraria.Main.rand, Terraria.Utils.RandomInt(), Terraria.Main.screenPosition, and Terraria.DataStructures.DrawData.sourceRect.
Referenced by Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_SkinComposite_BackArmShirt(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_17_TorsoComposite(), and Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_28_ArmOverItemComposite().