TModLoader: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head
DrawPlayer_21_Head()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head (ref PlayerDrawSet drawinfo) inline static
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_021a: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_022a: Unknown result type (might be due to invalid IL or missing references)
        //IL_022f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0245: Unknown result type (might be due to invalid IL or missing references)
        //IL_024f: Unknown result type (might be due to invalid IL or missing references)
        //IL_025d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0268: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0444: Unknown result type (might be due to invalid IL or missing references)
        //IL_0449: Unknown result type (might be due to invalid IL or missing references)
        //IL_0454: Unknown result type (might be due to invalid IL or missing references)
        //IL_0459: Unknown result type (might be due to invalid IL or missing references)
        //IL_045f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0464: Unknown result type (might be due to invalid IL or missing references)
        //IL_0469: Unknown result type (might be due to invalid IL or missing references)
        //IL_0471: Unknown result type (might be due to invalid IL or missing references)
        //IL_0482: Unknown result type (might be due to invalid IL or missing references)
        //IL_048d: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0542: Unknown result type (might be due to invalid IL or missing references)
        //IL_0547: Unknown result type (might be due to invalid IL or missing references)
        //IL_0552: Unknown result type (might be due to invalid IL or missing references)
        //IL_0557: Unknown result type (might be due to invalid IL or missing references)
        //IL_055d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0562: Unknown result type (might be due to invalid IL or missing references)
        //IL_0567: Unknown result type (might be due to invalid IL or missing references)
        //IL_056f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0580: Unknown result type (might be due to invalid IL or missing references)
        //IL_058b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0332: Unknown result type (might be due to invalid IL or missing references)
        //IL_0335: Unknown result type (might be due to invalid IL or missing references)
        //IL_0340: Unknown result type (might be due to invalid IL or missing references)
        //IL_0351: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07de: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0824: Unknown result type (might be due to invalid IL or missing references)
        //IL_0829: Unknown result type (might be due to invalid IL or missing references)
        //IL_082e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0619: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_064b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0650: Unknown result type (might be due to invalid IL or missing references)
        //IL_1785: Unknown result type (might be due to invalid IL or missing references)
        //IL_1790: Unknown result type (might be due to invalid IL or missing references)
        //IL_1795: Unknown result type (might be due to invalid IL or missing references)
        //IL_179b: Unknown result type (might be due to invalid IL or missing references)
        //IL_17a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_17ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_17b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_17c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_15b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_15bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_15be: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0866: Unknown result type (might be due to invalid IL or missing references)
        //IL_0877: Unknown result type (might be due to invalid IL or missing references)
        //IL_087d: Unknown result type (might be due to invalid IL or missing references)
        //IL_087f: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0723: Unknown result type (might be due to invalid IL or missing references)
        //IL_0728: Unknown result type (might be due to invalid IL or missing references)
        //IL_0733: Unknown result type (might be due to invalid IL or missing references)
        //IL_0738: Unknown result type (might be due to invalid IL or missing references)
        //IL_073e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0743: Unknown result type (might be due to invalid IL or missing references)
        //IL_0748: Unknown result type (might be due to invalid IL or missing references)
        //IL_074f: Unknown result type (might be due to invalid IL or missing references)
        //IL_075c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0764: Unknown result type (might be due to invalid IL or missing references)
        //IL_15f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1672: Unknown result type (might be due to invalid IL or missing references)
        //IL_1677: Unknown result type (might be due to invalid IL or missing references)
        //IL_1682: Unknown result type (might be due to invalid IL or missing references)
        //IL_1687: Unknown result type (might be due to invalid IL or missing references)
        //IL_168d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1692: Unknown result type (might be due to invalid IL or missing references)
        //IL_169d: Unknown result type (might be due to invalid IL or missing references)
        //IL_16a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_16b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_16c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_15de: Unknown result type (might be due to invalid IL or missing references)
        //IL_1528: Unknown result type (might be due to invalid IL or missing references)
        //IL_152b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1536: Unknown result type (might be due to invalid IL or missing references)
        //IL_1547: Unknown result type (might be due to invalid IL or missing references)
        //IL_1552: Unknown result type (might be due to invalid IL or missing references)
        //IL_0950: Unknown result type (might be due to invalid IL or missing references)
        //IL_0953: Unknown result type (might be due to invalid IL or missing references)
        //IL_095e: Unknown result type (might be due to invalid IL or missing references)
        //IL_096f: Unknown result type (might be due to invalid IL or missing references)
        //IL_097a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0683: Unknown result type (might be due to invalid IL or missing references)
        //IL_067b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a25: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1aa3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1aae: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ab3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ab9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1abe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ae7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1af8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b03: Unknown result type (might be due to invalid IL or missing references)
        //IL_182a: Unknown result type (might be due to invalid IL or missing references)
        //IL_182f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0688: Unknown result type (might be due to invalid IL or missing references)
        //IL_186c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1881: Unknown result type (might be due to invalid IL or missing references)
        //IL_1892: Unknown result type (might be due to invalid IL or missing references)
        //IL_1897: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d85: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d92: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c53: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c63: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c69: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c73: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c75: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c80: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c98: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ca3: Unknown result type (might be due to invalid IL or missing references)
        //IL_18cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_18e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_18e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_18fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_1973: Unknown result type (might be due to invalid IL or missing references)
        //IL_1978: Unknown result type (might be due to invalid IL or missing references)
        //IL_1983: Unknown result type (might be due to invalid IL or missing references)
        //IL_1988: Unknown result type (might be due to invalid IL or missing references)
        //IL_198e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1993: Unknown result type (might be due to invalid IL or missing references)
        //IL_19be: Unknown result type (might be due to invalid IL or missing references)
        //IL_19c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_19c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_19cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_19dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_19e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_189f: Unknown result type (might be due to invalid IL or missing references)
        //IL_18b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_18c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_18cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a31: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0afe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b09: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b14: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b30: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e30: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ebe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ece: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e09: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c96: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d19: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d2b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d43: Unknown result type (might be due to invalid IL or missing references)
        //IL_126c: Unknown result type (might be due to invalid IL or missing references)
        //IL_12e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_12f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_12fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_1300: Unknown result type (might be due to invalid IL or missing references)
        //IL_1305: Unknown result type (might be due to invalid IL or missing references)
        //IL_130a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1312: Unknown result type (might be due to invalid IL or missing references)
        //IL_1322: Unknown result type (might be due to invalid IL or missing references)
        //IL_132a: Unknown result type (might be due to invalid IL or missing references)
        //IL_13cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1446: Unknown result type (might be due to invalid IL or missing references)
        //IL_144b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1456: Unknown result type (might be due to invalid IL or missing references)
        //IL_145b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1461: Unknown result type (might be due to invalid IL or missing references)
        //IL_1466: Unknown result type (might be due to invalid IL or missing references)
        //IL_146f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1474: Unknown result type (might be due to invalid IL or missing references)
        //IL_147f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1489: Unknown result type (might be due to invalid IL or missing references)
        //IL_1497: Unknown result type (might be due to invalid IL or missing references)
        //IL_14a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f86: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0faa: Unknown result type (might be due to invalid IL or missing references)
        //IL_113e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1143: Unknown result type (might be due to invalid IL or missing references)
        //IL_1144: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_11dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_11fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1203: Unknown result type (might be due to invalid IL or missing references)
        //IL_1213: Unknown result type (might be due to invalid IL or missing references)
        //IL_121b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fff: Unknown result type (might be due to invalid IL or missing references)
        //IL_1005: Unknown result type (might be due to invalid IL or missing references)
        //IL_1007: Unknown result type (might be due to invalid IL or missing references)
        //IL_1008: Unknown result type (might be due to invalid IL or missing references)
        //IL_1085: Unknown result type (might be due to invalid IL or missing references)
        //IL_108a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1095: Unknown result type (might be due to invalid IL or missing references)
        //IL_109a: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_10aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ce: Unknown result type (might be due to invalid IL or missing references)
        Vector2 helmetOffset = drawinfo.helmetOffset;
        DrawPlayer_21_Head_TheFace(ref drawinfo);
        bool flag = drawinfo.drawPlayer.head >= 0 && ArmorIDs.Head.Sets.IsTallHat[drawinfo.drawPlayer.head];
        bool flag2 = drawinfo.drawPlayer.head == 28;
        bool flag3 = drawinfo.drawPlayer.head == 39 || drawinfo.drawPlayer.head == 38;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)(-drawinfo.drawPlayer.bodyFrame.Width / 2 + drawinfo.drawPlayer.width / 2), (float)(drawinfo.drawPlayer.height - drawinfo.drawPlayer.bodyFrame.Height + 4));
        Vector2 position = (drawinfo.Position - Main.screenPosition + vector).Floor() + drawinfo.drawPlayer.headPosition + drawinfo.headVect;
        if (((Enum)drawinfo.playerEffect).HasFlag((Enum)(object)(SpriteEffects)2))
        {
            int num = drawinfo.drawPlayer.bodyFrame.Height - drawinfo.hairFrontFrame.Height;
            position.Y += num;
        }
        position += drawinfo.hairOffset;
        if (drawinfo.fullHair)
        {
            Color color = drawinfo.colorArmorHead;
            int shader = drawinfo.cHead;
            if (ArmorIDs.Head.Sets.UseSkinColor[drawinfo.drawPlayer.head])
            {
                color = ((!drawinfo.drawPlayer.isDisplayDollOrInanimate) ? drawinfo.colorHead : drawinfo.colorDisplayDollSkin);
                shader = drawinfo.skinDyePacked;
            }
            DrawData item12 = new DrawData(TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, drawinfo.drawPlayer.bodyFrame, color, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
            item12.shader = shader;
            drawinfo.DrawDataCache.Add(item12);
            if (!drawinfo.drawPlayer.invis)
            {
                item12 = new DrawData(TextureAssets.PlayerHair[drawinfo.drawPlayer.hair].Value, position, drawinfo.hairFrontFrame, drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                item12.shader = drawinfo.hairDyePacked;
                drawinfo.DrawDataCache.Add(item12);
            }
        }
        if (drawinfo.hatHair && !drawinfo.drawPlayer.invis)
        {
            DrawData item13 = new DrawData(TextureAssets.PlayerHairAlt[drawinfo.drawPlayer.hair].Value, position, drawinfo.hairFrontFrame, drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
            item13.shader = drawinfo.hairDyePacked;
            drawinfo.DrawDataCache.Add(item13);
        }
        if (drawinfo.drawPlayer.head == 270)
        {
            Rectangle bodyFrame = drawinfo.drawPlayer.bodyFrame;
            bodyFrame.Width += 2;
            DrawData item5 = new DrawData(TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, bodyFrame, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
            item5.shader = drawinfo.cHead;
            drawinfo.DrawDataCache.Add(item5);
            item5 = new DrawData(TextureAssets.GlowMask[drawinfo.headGlowMask].Value, helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, bodyFrame, drawinfo.headGlowColor, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
            item5.shader = drawinfo.cHead;
            drawinfo.DrawDataCache.Add(item5);
        }
        else if (flag)
        {
            Rectangle bodyFrame2 = drawinfo.drawPlayer.bodyFrame;
            Vector2 headVect = drawinfo.headVect;
            if (drawinfo.drawPlayer.gravDir == 1f)
            {
                if (bodyFrame2.Y != 0)
                {
                    bodyFrame2.Y -= 2;
                    headVect.Y += 2f;
                }
                bodyFrame2.Height -= 8;
            }
            else if (bodyFrame2.Y != 0)
            {
                bodyFrame2.Y -= 2;
                headVect.Y -= 10f;
                bodyFrame2.Height -= 8;
            }
            Color color2 = drawinfo.colorArmorHead;
            int shader2 = drawinfo.cHead;
            if (ArmorIDs.Head.Sets.UseSkinColor[drawinfo.drawPlayer.head])
            {
                color2 = ((!drawinfo.drawPlayer.isDisplayDollOrInanimate) ? drawinfo.colorHead : drawinfo.colorDisplayDollSkin);
                shader2 = drawinfo.skinDyePacked;
            }
            DrawData item6 = new DrawData(TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, bodyFrame2, color2, drawinfo.drawPlayer.headRotation, headVect, 1f, drawinfo.playerEffect);
            item6.shader = shader2;
            drawinfo.DrawDataCache.Add(item6);
        }
        else if (drawinfo.drawPlayer.head == 259)
        {
            int verticalFrames = 27;
            Texture2D value = TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value;
            Rectangle rectangle = value.Frame(1, verticalFrames, 0, drawinfo.drawPlayer.rabbitOrderFrame.DisplayFrame);
            Vector2 origin = rectangle.Size() / 2f;
            int num12 = drawinfo.drawPlayer.babyBird.ToInt();
            Vector2 vector2 = DrawPlayer_21_Head_GetSpecialHatDrawPosition(ref drawinfo, ref helmetOffset, new Vector2((float)(1 + num12 * 2), (float)(-26 + drawinfo.drawPlayer.babyBird.ToInt() * -6)));
            int hatStacks3 = GetHatStacks(ref drawinfo, 4955);
            float num14 = (float)Math.PI / 60f;
            float num15 = num14 * drawinfo.drawPlayer.position.X % ((float)Math.PI * 2f);
            for (int num16 = hatStacks3 - 1; num16 >= 0; num16--)
            {
                float x = Vector2.UnitY.RotatedBy(num15 + num14 * (float)num16).X * ((float)num16 / 30f) * 2f - (float)(num16 * 2 * drawinfo.drawPlayer.direction);
                DrawData item8 = new DrawData(value, vector2 + new Vector2(x, (float)(num16 * -14) * drawinfo.drawPlayer.gravDir), rectangle, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, origin, 1f, drawinfo.playerEffect);
                item8.shader = drawinfo.cHead;
                drawinfo.DrawDataCache.Add(item8);
            }
            if (!drawinfo.drawPlayer.invis)
            {
                DrawData item7 = new DrawData(TextureAssets.PlayerHair[drawinfo.drawPlayer.hair].Value, position, drawinfo.hairFrontFrame, drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                item7.shader = drawinfo.hairDyePacked;
                drawinfo.DrawDataCache.Add(item7);
            }
        }
        else if (drawinfo.drawPlayer.head > 0 && !flag2)
        {
            if (!(drawinfo.drawPlayer.invis && flag3))
            {
                if (drawinfo.drawPlayer.head == 13)
                {
                    int hatStacks2 = GetHatStacks(ref drawinfo, 205);
                    float num17 = (float)Math.PI / 60f;
                    float num18 = num17 * drawinfo.drawPlayer.position.X % ((float)Math.PI * 2f);
                    for (int i = 0; i < hatStacks2; i++)
                    {
                        float num19 = Vector2.UnitY.RotatedBy(num18 + num17 * (float)i).X * ((float)i / 30f) * 2f;
                        DrawData item9 = new DrawData(TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)) + num19, (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f - (float)(4 * i))) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, drawinfo.drawPlayer.bodyFrame, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                        item9.shader = drawinfo.cHead;
                        drawinfo.DrawDataCache.Add(item9);
                    }
                }
                else if (drawinfo.drawPlayer.head == 265)
                {
                    int verticalFrames2 = 6;
                    Texture2D value2 = TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value;
                    Rectangle rectangle2 = value2.Frame(1, verticalFrames2, 0, drawinfo.drawPlayer.rabbitOrderFrame.DisplayFrame);
                    Vector2 origin2 = rectangle2.Size() / 2f;
                    Vector2 vector3 = DrawPlayer_21_Head_GetSpecialHatDrawPosition(ref drawinfo, ref helmetOffset, new Vector2(0f, -9f));
                    int hatStacks4 = GetHatStacks(ref drawinfo, 5004);
                    float num20 = (float)Math.PI / 60f;
                    float num2 = num20 * drawinfo.drawPlayer.position.X % ((float)Math.PI * 2f);
                    int num3 = hatStacks4 * 4 + 2;
                    int num4 = 0;
                    bool flag4 = (Main.GlobalTimeWrappedHourly + 180f) % 600f < 60f;
                    for (int num5 = num3 - 1; num5 >= 0; num5--)
                    {
                        int num6 = 0;
                        if (num5 == num3 - 1)
{
                            rectangle2.Y = 0;
                            num6 = 2;
                        }
                        else if (num5 == 0)
{
                            rectangle2.Y = rectangle2.Height * 5;
                        }
                        else
{
                            rectangle2.Y = rectangle2.Height * (num4++ % 4 + 1);
                        }
                        if (!(rectangle2.Y == rectangle2.Height * 3 && flag4))
{
                            float x2 = Vector2.UnitY.RotatedBy(num2 + num20 * (float)num5).X * ((float)num5 / 10f) * 4f - (float)num5 * 0.1f * (float)drawinfo.drawPlayer.direction;
                            DrawData item10 = new DrawData(value2, vector3 + new Vector2(x2, (float)(num5 * -4 + num6) * drawinfo.drawPlayer.gravDir), rectangle2, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, origin2, 1f, drawinfo.playerEffect);
                            item10.shader = drawinfo.cHead;
                            drawinfo.DrawDataCache.Add(item10);
                        }
                    }
                }
                else
                {
                    Rectangle bodyFrame3 = drawinfo.drawPlayer.bodyFrame;
                    Vector2 headVect2 = drawinfo.headVect;
                    if (drawinfo.drawPlayer.gravDir == 1f)
                    {
                        bodyFrame3.Height -= 4;
                    }
                    else
                    {
                        headVect2.Y -= 4f;
                        bodyFrame3.Height -= 4;
                    }
                    Color color3 = drawinfo.colorArmorHead;
                    int shader3 = drawinfo.cHead;
                    if (ArmorIDs.Head.Sets.UseSkinColor[drawinfo.drawPlayer.head])
                    {
                        color3 = ((!drawinfo.drawPlayer.isDisplayDollOrInanimate) ? drawinfo.colorHead : drawinfo.colorDisplayDollSkin);
                        shader3 = drawinfo.skinDyePacked;
                    }
                    DrawData item11 = new DrawData(TextureAssets.ArmorHead[drawinfo.drawPlayer.head].Value, helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, bodyFrame3, color3, drawinfo.drawPlayer.headRotation, headVect2, 1f, drawinfo.playerEffect);
                    item11.shader = shader3;
                    drawinfo.DrawDataCache.Add(item11);
                    if (drawinfo.headGlowMask != -1)
                    {
                        if (drawinfo.headGlowMask == 309)
{
                            int num7 = DrawPlayer_Head_GetTVScreen(drawinfo.drawPlayer);
                            if (num7 != 0)
{
                                int num8 = 0;
                                num8 += drawinfo.drawPlayer.bodyFrame.Y / 56;
                                if (num8 >= Main.OffsetsPlayerHeadgear.Length)
{
                                    num8 = 0;
                                }
                                Vector2 vector4 = Main.OffsetsPlayerHeadgear[num8];
                                vector4.Y -= 2f;
                                vector4 *= (float)(-((Enum)drawinfo.playerEffect).HasFlag((Enum)(object)(SpriteEffects)2).ToDirectionInt());
                                Texture2D value3 = TextureAssets.GlowMask[drawinfo.headGlowMask].Value;
                                int frameY = drawinfo.drawPlayer.miscCounter % 20 / 5;
                                if (num7 == 5)
{
                                    frameY = 0;
                                    if (drawinfo.drawPlayer.eyeHelper.EyeFrameToShow > 0)
{
                                        frameY = 2;
                                    }
                                }
                                Rectangle value4 = value3.Frame(6, 4, num7, frameY, -2);
                                item11 = new DrawData(value3, vector4 + helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, value4, drawinfo.headGlowColor, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                                item11.shader = drawinfo.cHead;
                                drawinfo.DrawDataCache.Add(item11);
                            }
                        }
                        else if (drawinfo.headGlowMask == 273)
{
                            for (int j = 0; j < 2; j++)
{
                                Vector2 position2 = new Vector2((float)Main.rand.Next(-10, 10) * 0.125f, (float)Main.rand.Next(-10, 10) * 0.125f) + helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect;
                                item11 = new DrawData(TextureAssets.GlowMask[drawinfo.headGlowMask].Value, position2, bodyFrame3, drawinfo.headGlowColor, drawinfo.drawPlayer.headRotation, headVect2, 1f, drawinfo.playerEffect);
                                item11.shader = drawinfo.cHead;
                                drawinfo.DrawDataCache.Add(item11);
                            }
                        }
                        else
{
                            item11 = new DrawData(TextureAssets.GlowMask[drawinfo.headGlowMask].Value, helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, bodyFrame3, drawinfo.headGlowColor, drawinfo.drawPlayer.headRotation, headVect2, 1f, drawinfo.playerEffect);
                            item11.shader = drawinfo.cHead;
                            drawinfo.DrawDataCache.Add(item11);
                        }
                    }
                    if (drawinfo.drawPlayer.head == 211)
                    {
                        Color color4 = default(Color);
                        ((Color)(ref color4))._002Ector(100, 100, 100, 0);
                        ulong seed = (ulong)(drawinfo.drawPlayer.miscCounter / 4 + 100);
                        int num9 = 4;
                        for (int k = 0; k < num9; k++)
{
                            float x3 = (float)Utils.RandomInt(ref seed, -10, 11) * 0.2f;
                            float y = (float)Utils.RandomInt(ref seed, -14, 1) * 0.15f;
                            item11 = new DrawData(TextureAssets.GlowMask[241].Value, helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect + new Vector2(x3, y), drawinfo.drawPlayer.bodyFrame, color4, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                            item11.shader = drawinfo.cHead;
                            drawinfo.DrawDataCache.Add(item11);
                        }
                    }
                }
            }
        }
        else if (!drawinfo.drawPlayer.invis && (drawinfo.drawPlayer.face < 0 || !ArmorIDs.Face.Sets.PreventHairDraw[drawinfo.drawPlayer.face]))
        {
            DrawData item14 = new DrawData(TextureAssets.PlayerHair[drawinfo.drawPlayer.hair].Value, position, drawinfo.hairFrontFrame, drawinfo.colorHair, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
            item14.shader = drawinfo.hairDyePacked;
            drawinfo.DrawDataCache.Add(item14);
        }
        if (drawinfo.drawPlayer.beard > 0 && (drawinfo.drawPlayer.head < 0 || !ArmorIDs.Head.Sets.PreventBeardDraw[drawinfo.drawPlayer.head]))
        {
            Vector2 beardDrawOffsetFromHelmet = drawinfo.drawPlayer.GetBeardDrawOffsetFromHelmet();
            Color color5 = drawinfo.colorArmorHead;
            if (ArmorIDs.Beard.Sets.UseHairColor[drawinfo.drawPlayer.beard])
            {
                color5 = drawinfo.colorHair;
            }
            DrawData item4 = new DrawData(TextureAssets.AccBeard[drawinfo.drawPlayer.beard].Value, beardDrawOffsetFromHelmet + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, drawinfo.drawPlayer.bodyFrame, color5, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
            item4.shader = drawinfo.cBeard;
            drawinfo.DrawDataCache.Add(item4);
        }
        if (drawinfo.drawPlayer.head == 205)
        {
            DrawData drawData = new DrawData(TextureAssets.Extra[77].Value, new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, drawinfo.drawPlayer.bodyFrame, drawinfo.colorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
            drawData.shader = drawinfo.skinDyePacked;
            DrawData item3 = drawData;
            drawinfo.DrawDataCache.Add(item3);
        }
        if (drawinfo.drawPlayer.head == 214 && !drawinfo.drawPlayer.invis)
        {
            Rectangle bodyFrame4 = drawinfo.drawPlayer.bodyFrame;
            bodyFrame4.Y = 0;
            float num10 = (float)drawinfo.drawPlayer.miscCounter / 300f;
            Color color6 = default(Color);
            ((Color)(ref color6))._002Ector(0, 0, 0, 0);
            float num11 = 0.8f;
            float num13 = 0.9f;
            if (num10 >= num11)
            {
                color6 = Color.Lerp(Color.Transparent, new Color(200, 200, 200, 0), Utils.GetLerpValue(num11, num13, num10, clamped: true));
            }
            if (num10 >= num13)
            {
                color6 = Color.Lerp(Color.Transparent, new Color(200, 200, 200, 0), Utils.GetLerpValue(1f, num13, num10, clamped: true));
            }
            color6 *= drawinfo.stealth * (1f - drawinfo.shadow);
            DrawData item2 = new DrawData(TextureAssets.Extra[90].Value, helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect - Main.OffsetsPlayerHeadgear[drawinfo.drawPlayer.bodyFrame.Y / drawinfo.drawPlayer.bodyFrame.Height], bodyFrame4, color6, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
            drawinfo.DrawDataCache.Add(item2);
        }
        if (drawinfo.drawPlayer.head == 137)
        {
            DrawData item = new DrawData(TextureAssets.JackHat.Value, helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect, drawinfo.drawPlayer.bodyFrame, new Color(255, 255, 255, 255), drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
            drawinfo.DrawDataCache.Add(item);
            Color color7 = default(Color);
            Vector2 vector5 = default(Vector2);
            for (int l = 0; l < 7; l++)
            {
                ((Color)(ref color7))._002Ector(110 - l * 10, 110 - l * 10, 110 - l * 10, 110 - l * 10);
                ((Vector2)(ref vector5))._002Ector((float)Main.rand.Next(-10, 11) * 0.2f, (float)Main.rand.Next(-10, 11) * 0.2f);
                vector5.X = drawinfo.drawPlayer.itemFlamePos[l].X;
                vector5.Y = drawinfo.drawPlayer.itemFlamePos[l].Y;
                vector5 *= 0.5f;
                item = new DrawData(TextureAssets.JackHat.Value, helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect + vector5, drawinfo.drawPlayer.bodyFrame, color7, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                drawinfo.DrawDataCache.Add(item);
            }
        }
    }
References Terraria.GameContent.TextureAssets.AccBeard, Terraria.GameContent.TextureAssets.ArmorHead, Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head_GetSpecialHatDrawPosition(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head_TheFace(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_Head_GetTVScreen(), Terraria.GameContent.TextureAssets.Extra, Terraria.DataStructures.PlayerDrawLayers.GetHatStacks(), Terraria.Utils.GetLerpValue(), Terraria.GameContent.TextureAssets.GlowMask, Terraria.ID.ArmorIDs.Head.Sets.IsTallHat, Terraria.GameContent.TextureAssets.JackHat, Terraria.Main.OffsetsPlayerHeadgear, Terraria.GameContent.TextureAssets.PlayerHair, Terraria.GameContent.TextureAssets.PlayerHairAlt, Terraria.ID.ArmorIDs.Head.Sets.PreventBeardDraw, Terraria.ID.ArmorIDs.Face.Sets.PreventHairDraw, Terraria.Main.rand, Terraria.Utils.RandomInt(), Terraria.Main.screenPosition, Terraria.ID.ArmorIDs.Beard.Sets.UseHairColor, and Terraria.ID.ArmorIDs.Head.Sets.UseSkinColor.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().