TModLoader: Terraria.DataStructures.PlayerDrawLayers.Torso
Torso
readonly PlayerDrawLayer Terraria.DataStructures.PlayerDrawLayers.Torso = new VanillaPlayerDrawLayer("Torso", DrawPlayer_17_Torso, TorsoGroup) static
Draws the player's body armor or shirts.
Definition at line 97 of file PlayerDrawLayers.cs.
Referenced by Terraria.ModLoader.Default.Developer.Jofairden.JofairdenBodyGlow.GetDefaultPosition(), Terraria.ModLoader.Default.Developer.Jofairden.JofairdenBodyShader.GetDefaultPosition(), and Terraria.ModLoader.Default.Developer.Jofairden.JofairdenHeadShader.GetDefaultPosition().