TModLoader: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_38_EyebrellaCloud
DrawPlayer_38_EyebrellaCloud()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_38_EyebrellaCloud (ref PlayerDrawSet drawinfo) inline static
    {
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_0228: Unknown result type (might be due to invalid IL or missing references)
        //IL_022e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_019b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        if (drawinfo.drawPlayer.eyebrellaCloud && drawinfo.shadow == 0f)
        {
            Texture2D value = TextureAssets.Projectile[238].Value;
            int frameY = drawinfo.drawPlayer.miscCounter % 18 / 6;
            Rectangle value2 = value.Frame(1, 6, 0, frameY);
            Vector2 origin = default(Vector2);
            ((Vector2)(ref origin))._002Ector((float)(value2.Width / 2), (float)(value2.Height / 2));
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector(0f, -70f);
            Vector2 vector2 = drawinfo.drawPlayer.MountedCenter - new Vector2(0f, (float)drawinfo.drawPlayer.height * 0.5f) + vector - Main.screenPosition;
            Color color = Lighting.GetColor((drawinfo.drawPlayer.Top + new Vector2(0f, -30f)).ToTileCoordinates());
            int num = 170;
            int g;
            int b;
            int r = (g = (b = num));
            if (((Color)(ref color)).R < num)
            {
                r = ((Color)(ref color)).R;
            }
            if (((Color)(ref color)).G < num)
            {
                g = ((Color)(ref color)).G;
            }
            if (((Color)(ref color)).B < num)
            {
                b = ((Color)(ref color)).B;
            }
            Color color2 = default(Color);
            ((Color)(ref color2))._002Ector(r, g, b, 100);
            float num2 = (float)(drawinfo.drawPlayer.miscCounter % 50) / 50f;
            float num3 = 3f;
            DrawData item;
            for (int i = 0; i < 2; i++)
            {
                Vector2 vector3 = Utils.RotatedBy(new Vector2((i == 0) ? (0f - num3) : num3, 0f), num2 * ((float)Math.PI * 2f) * ((i == 0) ? 1f : (-1f)));
                item = new DrawData(value, vector2 + vector3, value2, color2 * 0.65f, 0f, origin, 1f, (SpriteEffects)((drawinfo.drawPlayer.gravDir == -1f) ? 2 : 0));
                item.shader = drawinfo.cHead;
                item.ignorePlayerRotation = true;
                drawinfo.DrawDataCache.Add(item);
            }
            item = new DrawData(value, vector2, value2, color2, 0f, origin, 1f, (SpriteEffects)((drawinfo.drawPlayer.gravDir == -1f) ? 2 : 0));
            item.shader = drawinfo.cHead;
            item.ignorePlayerRotation = true;
            drawinfo.DrawDataCache.Add(item);
        }
    }
References Terraria.Lighting.GetColor(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Utils.RotatedBy(), and Terraria.Main.screenPosition.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().