TModLoader: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_28_ArmOverItemComposite
DrawPlayer_28_ArmOverItemComposite()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_28_ArmOverItemComposite (ref PlayerDrawSet drawinfo) inline static
Definition at line 5867 of file PlayerDrawLayers.cs.
    {
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_0169: Unknown result type (might be due to invalid IL or missing references)
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_087c: Unknown result type (might be due to invalid IL or missing references)
        //IL_087e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0889: Unknown result type (might be due to invalid IL or missing references)
        //IL_088f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0897: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0501: Unknown result type (might be due to invalid IL or missing references)
        //IL_0509: Unknown result type (might be due to invalid IL or missing references)
        //IL_0539: Unknown result type (might be due to invalid IL or missing references)
        //IL_053c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0547: Unknown result type (might be due to invalid IL or missing references)
        //IL_054d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0555: Unknown result type (might be due to invalid IL or missing references)
        //IL_0445: Unknown result type (might be due to invalid IL or missing references)
        //IL_0448: Unknown result type (might be due to invalid IL or missing references)
        //IL_0453: Unknown result type (might be due to invalid IL or missing references)
        //IL_0459: Unknown result type (might be due to invalid IL or missing references)
        //IL_0461: Unknown result type (might be due to invalid IL or missing references)
        //IL_077c: Unknown result type (might be due to invalid IL or missing references)
        //IL_077e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0789: Unknown result type (might be due to invalid IL or missing references)
        //IL_078f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0797: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07db: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0813: Unknown result type (might be due to invalid IL or missing references)
        //IL_0815: Unknown result type (might be due to invalid IL or missing references)
        //IL_0820: Unknown result type (might be due to invalid IL or missing references)
        //IL_0826: Unknown result type (might be due to invalid IL or missing references)
        //IL_082e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0722: Unknown result type (might be due to invalid IL or missing references)
        //IL_0724: Unknown result type (might be due to invalid IL or missing references)
        //IL_072f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0735: Unknown result type (might be due to invalid IL or missing references)
        //IL_073d: Unknown result type (might be due to invalid IL or missing references)
        //IL_057f: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0601: Unknown result type (might be due to invalid IL or missing references)
        //IL_060c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0611: Unknown result type (might be due to invalid IL or missing references)
        //IL_0617: Unknown result type (might be due to invalid IL or missing references)
        //IL_061c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0621: Unknown result type (might be due to invalid IL or missing references)
        //IL_0635: Unknown result type (might be due to invalid IL or missing references)
        //IL_063d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0648: Unknown result type (might be due to invalid IL or missing references)
        //IL_0659: Unknown result type (might be due to invalid IL or missing references)
        //IL_0664: Unknown result type (might be due to invalid IL or missing references)
        //IL_069f: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_02af: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03be: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0366: Unknown result type (might be due to invalid IL or missing references)
        //IL_0369: Unknown result type (might be due to invalid IL or missing references)
        //IL_0374: Unknown result type (might be due to invalid IL or missing references)
        //IL_037a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0382: Unknown result type (might be due to invalid IL or missing references)
        //IL_0314: Unknown result type (might be due to invalid IL or missing references)
        //IL_0316: Unknown result type (might be due to invalid IL or missing references)
        //IL_0321: Unknown result type (might be due to invalid IL or missing references)
        //IL_0327: Unknown result type (might be due to invalid IL or missing references)
        //IL_032f: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2((float)(drawinfo.drawPlayer.bodyFrame.Width / 2), (float)(drawinfo.drawPlayer.bodyFrame.Height / 2));
        Vector2 vector2 = Main.OffsetsPlayerHeadgear[drawinfo.drawPlayer.bodyFrame.Y / drawinfo.drawPlayer.bodyFrame.Height];
        vector2.Y -= 2f;
        vector += vector2 * (float)(-((Enum)drawinfo.playerEffect).HasFlag((Enum)(object)(SpriteEffects)2).ToDirectionInt());
        float bodyRotation = drawinfo.drawPlayer.bodyRotation;
        float rotation = drawinfo.drawPlayer.bodyRotation + drawinfo.compositeFrontArmRotation;
        Vector2 bodyVect = drawinfo.bodyVect;
        Vector2 compositeOffset_FrontArm = GetCompositeOffset_FrontArm(ref drawinfo);
        bodyVect += compositeOffset_FrontArm;
        vector += compositeOffset_FrontArm;
        Vector2 position = vector + drawinfo.frontShoulderOffset;
        if (drawinfo.compFrontArmFrame.X / drawinfo.compFrontArmFrame.Width >= 7)
        {
            vector += new Vector2((float)((!((Enum)drawinfo.playerEffect).HasFlag((Enum)(object)(SpriteEffects)1)) ? 1 : (-1)), (float)((!((Enum)drawinfo.playerEffect).HasFlag((Enum)(object)(SpriteEffects)2)) ? 1 : (-1)));
        }
        _ = drawinfo.drawPlayer.invis;
        bool num5 = drawinfo.drawPlayer.body > 0;
        int num2 = (drawinfo.compShoulderOverFrontArm ? 1 : 0);
        int num3 = ((!drawinfo.compShoulderOverFrontArm) ? 1 : 0);
        int num4 = ((!drawinfo.compShoulderOverFrontArm) ? 1 : 0);
        bool flag = !drawinfo.hidesTopSkin;
        if (num5)
        {
            if (!drawinfo.drawPlayer.invis || IsArmorDrawnWhenInvisible(drawinfo.drawPlayer.body))
            {
                Texture2D value = TextureAssets.ArmorBodyComposite[drawinfo.drawPlayer.body].Value;
                for (int i = 0; i < 2; i++)
                {
                    if (!drawinfo.drawPlayer.invis && i == num4 && flag)
                    {
                        if (drawinfo.missingArm)
{
                            drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 7].Value, vector, drawinfo.compFrontArmFrame, drawinfo.colorBodySkin, rotation, bodyVect, 1f, drawinfo.playerEffect)
{
                                shader = drawinfo.skinDyePacked
                            });
                        }
                        if (drawinfo.missingHand)
{
                            drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 9].Value, vector, drawinfo.compFrontArmFrame, drawinfo.colorBodySkin, rotation, bodyVect, 1f, drawinfo.playerEffect)
{
                                shader = drawinfo.skinDyePacked
                            });
                        }
                    }
                    if (i == num2 && !drawinfo.hideCompositeShoulders)
                    {
                        DrawCompositeArmorPiece(ref drawinfo, CompositePlayerDrawContext.FrontShoulder, new DrawData(value, position, drawinfo.compFrontShoulderFrame, drawinfo.colorArmorBody, bodyRotation, bodyVect, 1f, drawinfo.playerEffect)
{
                            shader = drawinfo.cBody
                        });
                    }
                    if (i == num3)
                    {
                        DrawCompositeArmorPiece(ref drawinfo, CompositePlayerDrawContext.FrontArm, new DrawData(value, vector, drawinfo.compFrontArmFrame, drawinfo.colorArmorBody, rotation, bodyVect, 1f, drawinfo.playerEffect)
{
                            shader = drawinfo.cBody
                        });
                    }
                }
            }
        }
        else if (!drawinfo.drawPlayer.invis)
        {
            for (int j = 0; j < 2; j++)
            {
                if (j == num2)
                {
                    if (flag)
                    {
                        drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 7].Value, position, drawinfo.compFrontShoulderFrame, drawinfo.colorBodySkin, bodyRotation, bodyVect, 1f, drawinfo.playerEffect)
{
                            shader = drawinfo.skinDyePacked
                        });
                    }
                    drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 8].Value, position, drawinfo.compFrontShoulderFrame, drawinfo.colorUnderShirt, bodyRotation, bodyVect, 1f, drawinfo.playerEffect));
                    drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 13].Value, position, drawinfo.compFrontShoulderFrame, drawinfo.colorShirt, bodyRotation, bodyVect, 1f, drawinfo.playerEffect));
                    drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 6].Value, position, drawinfo.compFrontShoulderFrame, drawinfo.colorShirt, bodyRotation, bodyVect, 1f, drawinfo.playerEffect));
                    if (drawinfo.drawPlayer.head == 269)
                    {
                        Vector2 position2 = drawinfo.helmetOffset + new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.headPosition + drawinfo.headVect;
                        DrawData item = new DrawData(TextureAssets.Extra[214].Value, position2, drawinfo.drawPlayer.bodyFrame, drawinfo.colorArmorHead, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                        item.shader = drawinfo.cHead;
                        drawinfo.DrawDataCache.Add(item);
                        item = new DrawData(TextureAssets.GlowMask[308].Value, position2, drawinfo.drawPlayer.bodyFrame, drawinfo.headGlowColor, drawinfo.drawPlayer.headRotation, drawinfo.headVect, 1f, drawinfo.playerEffect);
                        item.shader = drawinfo.cHead;
                        drawinfo.DrawDataCache.Add(item);
                    }
                }
                if (j == num3)
                {
                    if (flag)
                    {
                        drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 7].Value, vector, drawinfo.compFrontArmFrame, drawinfo.colorBodySkin, rotation, bodyVect, 1f, drawinfo.playerEffect)
{
                            shader = drawinfo.skinDyePacked
                        });
                    }
                    drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 8].Value, vector, drawinfo.compFrontArmFrame, drawinfo.colorUnderShirt, rotation, bodyVect, 1f, drawinfo.playerEffect));
                    drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 13].Value, vector, drawinfo.compFrontArmFrame, drawinfo.colorShirt, rotation, bodyVect, 1f, drawinfo.playerEffect));
                    drawinfo.DrawDataCache.Add(new DrawData(TextureAssets.Players[drawinfo.skinVar, 6].Value, vector, drawinfo.compFrontArmFrame, drawinfo.colorShirt, rotation, bodyVect, 1f, drawinfo.playerEffect));
                }
            }
        }
        if (drawinfo.drawPlayer.handon > 0)
        {
            Texture2D value2 = TextureAssets.AccHandsOnComposite[drawinfo.drawPlayer.handon].Value;
            DrawCompositeArmorPiece(ref drawinfo, CompositePlayerDrawContext.FrontArmAccessory, new DrawData(value2, vector, drawinfo.compFrontArmFrame, drawinfo.colorArmorBody, rotation, bodyVect, 1f, drawinfo.playerEffect)
            {
                shader = drawinfo.cHandOn
            });
        }
    }
References Terraria.GameContent.TextureAssets.AccHandsOnComposite, Terraria.GameContent.TextureAssets.ArmorBodyComposite, Terraria.DataStructures.PlayerDrawLayers.DrawCompositeArmorPiece(), Terraria.GameContent.TextureAssets.Extra, Terraria.DataStructures.PlayerDrawLayers.GetCompositeOffset_FrontArm(), Terraria.GameContent.TextureAssets.GlowMask, Terraria.DataStructures.PlayerDrawLayers.IsArmorDrawnWhenInvisible(), Terraria.Main.OffsetsPlayerHeadgear, Terraria.GameContent.TextureAssets.Players, and Terraria.Main.screenPosition.
Referenced by Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_28_ArmOverItem().