TModLoader: Terraria.ModLoader.UI.UIMemoryBar.RecalculateMemory
RecalculateMemory()
void Terraria.ModLoader.UI.UIMemoryBar.RecalculateMemory () inline private
    {
        //IL_02c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        _memoryBarItems.Clear();
        _maxMemory = GetTotalMemory();
        long availableMemory = _maxMemory;
        long totalModMemory = 0L;
        int i = 0;
        foreach (KeyValuePair<string, ModMemoryUsage> entry in MemoryTracking.modMemoryUsageEstimates.OrderBy((KeyValuePair<string, ModMemoryUsage> v) => -v.Value.total))
        {
            string modName = entry.Key;
            ModMemoryUsage usage = entry.Value;
            if (usage.total > 0 && !(modName == "tModLoader"))
            {
                totalModMemory += usage.total;
                StringBuilder sb = new StringBuilder();
                sb.Append(ModLoader.GetMod(modName).DisplayName);
                StringBuilder stringBuilder = sb;
                StringBuilder stringBuilder2 = stringBuilder;
                StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(1, 1, stringBuilder);
                handler.AppendLiteral("\n");
                handler.AppendFormatted(Language.GetTextValue("tModLoader.LastLoadRamUsage", SizeSuffix(usage.total)));
                stringBuilder2.Append(ref handler);
                if (usage.managed > 0)
                {
                    stringBuilder = sb;
                    StringBuilder stringBuilder3 = stringBuilder;
                    handler = new StringBuilder.AppendInterpolatedStringHandler(2, 1, stringBuilder);
                    handler.AppendLiteral("\n ");
                    handler.AppendFormatted(Language.GetTextValue("tModLoader.ManagedMemory", SizeSuffix(usage.managed)));
                    stringBuilder3.Append(ref handler);
                }
                if (usage.managed > 0)
                {
                    stringBuilder = sb;
                    StringBuilder stringBuilder4 = stringBuilder;
                    handler = new StringBuilder.AppendInterpolatedStringHandler(2, 1, stringBuilder);
                    handler.AppendLiteral("\n ");
                    handler.AppendFormatted(Language.GetTextValue("tModLoader.CodeMemory", SizeSuffix(usage.code)));
                    stringBuilder4.Append(ref handler);
                }
                if (usage.sounds > 0)
                {
                    stringBuilder = sb;
                    StringBuilder stringBuilder5 = stringBuilder;
                    handler = new StringBuilder.AppendInterpolatedStringHandler(2, 1, stringBuilder);
                    handler.AppendLiteral("\n ");
                    handler.AppendFormatted(Language.GetTextValue("tModLoader.SoundMemory", SizeSuffix(usage.sounds)));
                    stringBuilder5.Append(ref handler);
                }
                if (usage.textures > 0)
                {
                    stringBuilder = sb;
                    StringBuilder stringBuilder6 = stringBuilder;
                    handler = new StringBuilder.AppendInterpolatedStringHandler(2, 1, stringBuilder);
                    handler.AppendLiteral("\n ");
                    handler.AppendFormatted(Language.GetTextValue("tModLoader.TextureMemory", SizeSuffix(usage.textures)));
                    stringBuilder6.Append(ref handler);
                }
                _memoryBarItems.Add(new MemoryBarItem(sb.ToString(), usage.total, _colors[i++ % _colors.Length]));
            }
        }
        long allocatedMemory = Process.GetCurrentProcess().WorkingSet64;
        long nonModMemory = allocatedMemory - totalModMemory;
        _memoryBarItems.Add(new MemoryBarItem(Language.GetTextValue("tModLoader.TerrariaMemory", SizeSuffix(nonModMemory)) + "\n " + Language.GetTextValue("tModLoader.TotalMemory", SizeSuffix(allocatedMemory)), nonModMemory, Color.DeepSkyBlue));
        long remainingMemory = availableMemory - allocatedMemory;
        _memoryBarItems.Add(new MemoryBarItem(Language.GetTextValue("tModLoader.AvailableMemory", SizeSuffix(remainingMemory)) + "\n " + Language.GetTextValue("tModLoader.TotalMemory", SizeSuffix(availableMemory)), remainingMemory, Color.Gray));
        RecalculateMemoryNeeded = false;
    }
References Terraria.ModLoader.UI.UIMemoryBar._colors, Terraria.ModLoader.UI.UIMemoryBar._maxMemory, Terraria.ModLoader.UI.UIMemoryBar._memoryBarItems, Terraria.ModLoader.Mod.DisplayName, Terraria.ModLoader.ModLoader.GetMod(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.UIMemoryBar.GetTotalMemory(), Terraria.ModLoader.Core.MemoryTracking.modMemoryUsageEstimates, Terraria.ModLoader.UI.UIMemoryBar.RecalculateMemoryNeeded, and Terraria.ModLoader.UI.UIMemoryBar.SizeSuffix().
Referenced by Terraria.ModLoader.UI.UIMemoryBar.OnActivate().