TModLoader: Terraria.ModLoader.UI.UIMemoryBar.DrawSelf
DrawSelf()
override void Terraria.ModLoader.UI.UIMemoryBar.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 67 of file UIMemoryBar.cs.
    {
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        if (RecalculateMemoryNeeded)
        {
            return;
        }
        Rectangle rectangle = GetInnerDimensions().ToRectangle();
        Point mouse = default(Point);
        ((Point)(ref mouse))._002Ector(Main.mouseX, Main.mouseY);
        int xOffset = 0;
        bool drawHover = false;
        MemoryBarItem hoverData = null;
        Rectangle drawArea = default(Rectangle);
        for (int i = 0; i < _memoryBarItems.Count; i++)
        {
            MemoryBarItem memoryBarData = _memoryBarItems[i];
            int width = (int)((float)rectangle.Width * ((float)memoryBarData.Memory / (float)_maxMemory));
            if (i == _memoryBarItems.Count - 1)
            {
                width = ((Rectangle)(ref rectangle)).Right - xOffset - rectangle.X;
            }
            ((Rectangle)(ref drawArea))._002Ector(rectangle.X + xOffset, rectangle.Y, width, rectangle.Height);
            xOffset += width;
            Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, drawArea, memoryBarData.DrawColor);
            if (!drawHover && ((Rectangle)(ref drawArea)).Contains(mouse))
            {
                drawHover = true;
                hoverData = memoryBarData;
            }
        }
        if (drawHover && hoverData != null)
        {
            UICommon.TooltipMouseText(hoverData.Tooltip);
        }
    }
References Terraria.ModLoader.UI.UIMemoryBar._maxMemory, Terraria.ModLoader.UI.UIMemoryBar._memoryBarItems, Terraria.UI.UIElement.GetInnerDimensions(), Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.ModLoader.UI.UIMemoryBar.RecalculateMemoryNeeded, Terraria.Main.spriteBatch, Terraria.ModLoader.UI.UICommon.TooltipMouseText(), and Terraria.UI.CalculatedStyle.ToRectangle().