TModLoader: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_RenderAllLayers
DrawPlayer_RenderAllLayers()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_RenderAllLayers (ref PlayerDrawSet drawinfo) inline static
Definition at line 6859 of file PlayerDrawLayers.cs.
    {
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        List<DrawData> drawDataCache = drawinfo.DrawDataCache;
        if (spriteBuffer == null)
        {
            spriteBuffer = new SpriteDrawBuffer(Main.graphics.GraphicsDevice, 200);
        }
        else
        {
            spriteBuffer.CheckGraphicsDevice(Main.graphics.GraphicsDevice);
        }
        foreach (DrawData item in drawDataCache)
        {
            if (item.texture != null)
            {
                item.Draw(spriteBuffer);
            }
        }
        spriteBuffer.UploadAndBind();
        DrawData cdd = default(DrawData);
        int num = 0;
        for (int i = 0; i <= drawDataCache.Count; i++)
        {
            if (drawinfo.projectileDrawPosition == i)
            {
                if (cdd.shader != 0)
                {
                    Main.pixelShader.CurrentTechnique.Passes[0].Apply();
                }
                spriteBuffer.Unbind();
                DrawHeldProj(drawinfo, Main.projectile[drawinfo.drawPlayer.heldProj]);
                spriteBuffer.Bind();
            }
            if (i != drawDataCache.Count)
            {
                cdd = drawDataCache[i];
                if (!cdd.sourceRect.HasValue)
                {
                    cdd.sourceRect = cdd.texture.Frame();
                }
                PlayerDrawHelper.SetShaderForData(drawinfo.drawPlayer, drawinfo.cHead, ref cdd);
                if (cdd.texture != null)
                {
                    spriteBuffer.DrawSingle(num++);
                }
            }
        }
        spriteBuffer.Unbind();
        Main.pixelShader.CurrentTechnique.Passes[0].Apply();
    }
References Terraria.DataStructures.DrawData.Draw(), Terraria.DataStructures.PlayerDrawLayers.DrawHeldProj(), Terraria.Main.graphics, Terraria.Main.pixelShader, Terraria.Main.projectile, Terraria.DataStructures.PlayerDrawHelper.SetShaderForData(), Terraria.DataStructures.PlayerDrawLayers.spriteBuffer, and Terraria.DataStructures.DrawData.texture.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerInternal().