TModLoader: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_14_Shoes
DrawPlayer_14_Shoes()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_14_Shoes (ref PlayerDrawSet drawinfo) inline static
Definition at line 2871 of file PlayerDrawLayers.cs.
    {
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0126: Unknown result type (might be due to invalid IL or missing references)
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        if (drawinfo.drawPlayer.shoe <= 0 || ShouldOverrideLegs_CheckPants(ref drawinfo))
        {
            return;
        }
        int num = drawinfo.cShoe;
        if (drawinfo.drawPlayer.shoe == 22 || drawinfo.drawPlayer.shoe == 23)
        {
            num = drawinfo.cFlameWaker;
        }
        if (drawinfo.isSitting)
        {
            DrawSittingLegs(ref drawinfo, TextureAssets.AccShoes[drawinfo.drawPlayer.shoe].Value, drawinfo.colorArmorLegs, num);
            return;
        }
        DrawData item = new DrawData(TextureAssets.AccShoes[drawinfo.drawPlayer.shoe].Value, new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.legFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.legFrame.Height + 4f)) + drawinfo.drawPlayer.legPosition + drawinfo.legVect, drawinfo.drawPlayer.legFrame, drawinfo.colorArmorLegs, drawinfo.drawPlayer.legRotation, drawinfo.legVect, 1f, drawinfo.playerEffect);
        item.shader = num;
        drawinfo.DrawDataCache.Add(item);
        if (drawinfo.drawPlayer.shoe == 25 || drawinfo.drawPlayer.shoe == 26)
        {
            DrawPlayer_14_2_GlassSlipperSparkles(ref drawinfo);
        }
    }
References Terraria.GameContent.TextureAssets.AccShoes, Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_14_2_GlassSlipperSparkles(), Terraria.DataStructures.PlayerDrawLayers.DrawSittingLegs(), Terraria.Main.screenPosition, and Terraria.DataStructures.PlayerDrawLayers.ShouldOverrideLegs_CheckPants().
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().