TModLoader: Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_28_ArmOverItem
DrawPlayer_28_ArmOverItem()
static void Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_28_ArmOverItem (ref PlayerDrawSet drawinfo) inline static
    {
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0790: Unknown result type (might be due to invalid IL or missing references)
        //IL_079b: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07db: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0802: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_090a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0915: Unknown result type (might be due to invalid IL or missing references)
        //IL_0926: Unknown result type (might be due to invalid IL or missing references)
        //IL_0931: Unknown result type (might be due to invalid IL or missing references)
        //IL_09de: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a19: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a29: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a45: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a50: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03af: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03df: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0401: Unknown result type (might be due to invalid IL or missing references)
        //IL_040c: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0508: Unknown result type (might be due to invalid IL or missing references)
        //IL_050d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0512: Unknown result type (might be due to invalid IL or missing references)
        //IL_0519: Unknown result type (might be due to invalid IL or missing references)
        //IL_052a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0535: Unknown result type (might be due to invalid IL or missing references)
        //IL_0276: Unknown result type (might be due to invalid IL or missing references)
        //IL_0281: Unknown result type (might be due to invalid IL or missing references)
        //IL_0286: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_019f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_064e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0659: Unknown result type (might be due to invalid IL or missing references)
        //IL_065e: Unknown result type (might be due to invalid IL or missing references)
        //IL_068f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0694: Unknown result type (might be due to invalid IL or missing references)
        //IL_0699: Unknown result type (might be due to invalid IL or missing references)
        //IL_069f: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b8: Unknown result type (might be due to invalid IL or missing references)
        if (drawinfo.usesCompositeTorso)
        {
            DrawPlayer_28_ArmOverItemComposite(ref drawinfo);
        }
        else if (drawinfo.drawPlayer.body > 0)
        {
            Rectangle bodyFrame = drawinfo.drawPlayer.bodyFrame;
            int num = drawinfo.armorAdjust;
            bodyFrame.X += num;
            bodyFrame.Width -= num;
            if (drawinfo.drawPlayer.direction == -1)
            {
                num = 0;
            }
            if (drawinfo.drawPlayer.invis && (drawinfo.drawPlayer.body == 21 || drawinfo.drawPlayer.body == 22))
            {
                return;
            }
            DrawData item;
            if (drawinfo.missingHand && !drawinfo.drawPlayer.invis)
            {
                _ = drawinfo.drawPlayer.body;
                DrawData drawData;
                if (drawinfo.missingArm)
                {
                    drawData = new DrawData(TextureAssets.Players[drawinfo.skinVar, 7].Value, new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2((float)(drawinfo.drawPlayer.bodyFrame.Width / 2), (float)(drawinfo.drawPlayer.bodyFrame.Height / 2)), drawinfo.drawPlayer.bodyFrame, drawinfo.colorBodySkin, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
                    drawData.shader = drawinfo.skinDyePacked;
                    item = drawData;
                    drawinfo.DrawDataCache.Add(item);
                }
                drawData = new DrawData(TextureAssets.Players[drawinfo.skinVar, 9].Value, new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2((float)(drawinfo.drawPlayer.bodyFrame.Width / 2), (float)(drawinfo.drawPlayer.bodyFrame.Height / 2)), drawinfo.drawPlayer.bodyFrame, drawinfo.colorBodySkin, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
                drawData.shader = drawinfo.skinDyePacked;
                item = drawData;
                drawinfo.DrawDataCache.Add(item);
            }
            item = new DrawData(TextureAssets.ArmorArm[drawinfo.drawPlayer.body].Value, new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)) + num), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2((float)(drawinfo.drawPlayer.bodyFrame.Width / 2), (float)(drawinfo.drawPlayer.bodyFrame.Height / 2)), bodyFrame, drawinfo.colorArmorBody, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
            item.shader = drawinfo.cBody;
            drawinfo.DrawDataCache.Add(item);
            if (drawinfo.armGlowMask != -1)
            {
                item = new DrawData(TextureAssets.GlowMask[drawinfo.armGlowMask].Value, new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)) + num), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2((float)(drawinfo.drawPlayer.bodyFrame.Width / 2), (float)(drawinfo.drawPlayer.bodyFrame.Height / 2)), bodyFrame, drawinfo.armGlowColor, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
                item.shader = drawinfo.cBody;
                drawinfo.DrawDataCache.Add(item);
            }
            if (drawinfo.drawPlayer.body == 205)
            {
                Color color = default(Color);
                ((Color)(ref color))._002Ector(100, 100, 100, 0);
                ulong seed = (ulong)(drawinfo.drawPlayer.miscCounter / 4);
                int num2 = 4;
                for (int i = 0; i < num2; i++)
                {
                    float num3 = (float)Utils.RandomInt(ref seed, -10, 11) * 0.2f;
                    float num4 = (float)Utils.RandomInt(ref seed, -10, 1) * 0.15f;
                    item = new DrawData(TextureAssets.GlowMask[240].Value, new Vector2((float)((int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)) + num), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2((float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + num3, (float)(drawinfo.drawPlayer.bodyFrame.Height / 2) + num4), bodyFrame, color, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
                    item.shader = drawinfo.cBody;
                    drawinfo.DrawDataCache.Add(item);
                }
            }
        }
        else if (!drawinfo.drawPlayer.invis)
        {
            DrawData drawData2 = new DrawData(TextureAssets.Players[drawinfo.skinVar, 7].Value, new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2((float)(drawinfo.drawPlayer.bodyFrame.Width / 2), (float)(drawinfo.drawPlayer.bodyFrame.Height / 2)), drawinfo.drawPlayer.bodyFrame, drawinfo.colorBodySkin, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
            drawData2.shader = drawinfo.skinDyePacked;
            DrawData item2 = drawData2;
            drawinfo.DrawDataCache.Add(item2);
            item2 = new DrawData(TextureAssets.Players[drawinfo.skinVar, 8].Value, new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2((float)(drawinfo.drawPlayer.bodyFrame.Width / 2), (float)(drawinfo.drawPlayer.bodyFrame.Height / 2)), drawinfo.drawPlayer.bodyFrame, drawinfo.colorUnderShirt, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
            drawinfo.DrawDataCache.Add(item2);
            item2 = new DrawData(TextureAssets.Players[drawinfo.skinVar, 13].Value, new Vector2((float)(int)(drawinfo.Position.X - Main.screenPosition.X - (float)(drawinfo.drawPlayer.bodyFrame.Width / 2) + (float)(drawinfo.drawPlayer.width / 2)), (float)(int)(drawinfo.Position.Y - Main.screenPosition.Y + (float)drawinfo.drawPlayer.height - (float)drawinfo.drawPlayer.bodyFrame.Height + 4f)) + drawinfo.drawPlayer.bodyPosition + new Vector2((float)(drawinfo.drawPlayer.bodyFrame.Width / 2), (float)(drawinfo.drawPlayer.bodyFrame.Height / 2)), drawinfo.drawPlayer.bodyFrame, drawinfo.colorShirt, drawinfo.drawPlayer.bodyRotation, drawinfo.bodyVect, 1f, drawinfo.playerEffect);
            drawinfo.DrawDataCache.Add(item2);
        }
    }
References Terraria.GameContent.TextureAssets.ArmorArm, Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_28_ArmOverItemComposite(), Terraria.GameContent.TextureAssets.GlowMask, Terraria.GameContent.TextureAssets.Players, Terraria.Utils.RandomInt(), and Terraria.Main.screenPosition.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayer_UseNormalLayers().