TModLoader: Terraria.ModLoader.UI.UIMods.items
items
readonly List<UIModItem> Terraria.ModLoader.UI.UIMods.items = new List<UIModItem>() private
Definition at line 34 of file UIMods.cs.
Referenced by Terraria.ModLoader.UI.UIMods.BackClick(), Terraria.ModLoader.UI.UIMods.DisableAll(), Terraria.ModLoader.UI.UIMods.EnableAll(), Terraria.ModLoader.UI.UIMods.FindUIModItem(), Terraria.ModLoader.UI.UIMods.OnActivate(), Terraria.ModLoader.UI.UIMods.Populate(), Terraria.ModLoader.UI.UIMods.ReloadMods(), and Terraria.ModLoader.UI.UIMods.Update().