TModLoader: Terraria.ModLoader.UI.UIMods.DisableAll
DisableAll()
void Terraria.ModLoader.UI.UIMods.DisableAll (UIMouseEvent evt, UIElement listeningElement) inline private
    {
        SoundEngine.PlaySound(12);
        foreach (UIModItem item in items)
        {
            item.Disable();
        }
    }
References Terraria.ModLoader.UI.UIModItem.Disable(), Terraria.ModLoader.UI.UIMods.items, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.ModLoader.UI.UIMods.OnInitialize().