TModLoader: Terraria.ModLoader.UI.UIMods.OnActivate
OnActivate()
override void Terraria.ModLoader.UI.UIMods.OnActivate () inline virtual
Reimplemented from Terraria.UI.UIElement.
    {
        _cts = new CancellationTokenSource();
        Main.clrInput();
        modList.Clear();
        items.Clear();
        loading = true;
        uIPanel.Append(uiLoader);
        ConfigManager.LoadAll();
        Populate();
        UpdateTopRowButtons();
    }
References Terraria.ModLoader.UI.UIMods._cts, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.Main.clrInput(), Terraria.ModLoader.UI.UIMods.items, Terraria.ModLoader.Config.ConfigManager.LoadAll(), Terraria.ModLoader.UI.UIMods.loading, Terraria.ModLoader.UI.UIMods.modList, Terraria.ModLoader.UI.UIMods.Populate(), Terraria.ModLoader.UI.UIMods.uiLoader, Terraria.ModLoader.UI.UIMods.uIPanel, and Terraria.ModLoader.UI.UIMods.UpdateTopRowButtons().