TModLoader: Terraria.ModLoader.UI.UIMods.Update
Update()
override void Terraria.ModLoader.UI.UIMods.Update (GameTime gameTime) inline virtual
Reimplemented from Terraria.UI.UIElement.
    {
        base.Update(gameTime);
        if (needToRemoveLoading)
        {
            needToRemoveLoading = false;
            uIPanel.RemoveChild(uiLoader);
        }
        if (!updateNeeded)
        {
            return;
        }
        updateNeeded = false;
        filter = filterTextBox.Text;
        modList.Clear();
        UIModsFilterResults filterResults = new UIModsFilterResults();
        List<UIModItem> visibleItems = items.Where((UIModItem item) => item.PassFilters(filterResults)).ToList();
        if (filterResults.AnyFiltered)
        {
            UIPanel panel = new UIPanel();
            panel.Width.Set(0f, 1f);
            modList.Add(panel);
            List<string> filterMessages = new List<string>();
            if (filterResults.filteredByEnabled > 0)
            {
                filterMessages.Add(Language.GetTextValue("tModLoader.ModsXModsFilteredByEnabled", filterResults.filteredByEnabled));
            }
            if (filterResults.filteredByModSide > 0)
            {
                filterMessages.Add(Language.GetTextValue("tModLoader.ModsXModsFilteredByModSide", filterResults.filteredByModSide));
            }
            if (filterResults.filteredBySearch > 0)
            {
                filterMessages.Add(Language.GetTextValue("tModLoader.ModsXModsFilteredBySearch", filterResults.filteredBySearch));
            }
            UIText text = new UIText(string.Join("\n", filterMessages));
            text.Width.Set(0f, 1f);
            text.IsWrapped = true;
            text.WrappedTextBottomPadding = 0f;
            text.TextOriginX = 0f;
            text.Recalculate();
            panel.Append(text);
            panel.Height.Set(text.MinHeight.Pixels + panel.PaddingTop, 0f);
        }
        modList.AddRange(visibleItems);
        Recalculate();
        modList.ViewPosition = modListViewPosition;
    }
References Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.Elements.UIList.AddRange(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.ModLoader.UI.UIMods.filter, Terraria.ModLoader.UI.UIMods.filterTextBox, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.UIMods.items, Terraria.UI.UIElement.MinHeight, Terraria.ModLoader.UI.UIMods.modList, Terraria.ModLoader.UI.UIMods.modListViewPosition, Terraria.ModLoader.UI.UIMods.needToRemoveLoading, Terraria.ModLoader.UI.UIModItem.PassFilters(), Terraria.UI.StyleDimension.Pixels, Terraria.GameContent.UI.Elements.UIText.Recalculate(), Terraria.UI.UIElement.Recalculate(), Terraria.UI.UIElement.RemoveChild(), Terraria.UI.StyleDimension.Set(), Terraria.ModLoader.UI.UIInputTextField.Text, Terraria.ModLoader.UI.UIMods.uiLoader, Terraria.ModLoader.UI.UIMods.uIPanel, Terraria.ModLoader.UI.UIMods.updateNeeded, and Terraria.UI.UIElement.Width.