TModLoader: Terraria.ModLoader.UI.UIMods.OnInitialize
OnInitialize()
override void Terraria.ModLoader.UI.UIMods.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
    {
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02db: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_035b: Unknown result type (might be due to invalid IL or missing references)
        //IL_037d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0383: Unknown result type (might be due to invalid IL or missing references)
        //IL_0387: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0391: Unknown result type (might be due to invalid IL or missing references)
        //IL_0397: Unknown result type (might be due to invalid IL or missing references)
        //IL_039b: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_042f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0435: Unknown result type (might be due to invalid IL or missing references)
        //IL_0439: Unknown result type (might be due to invalid IL or missing references)
        //IL_043f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0443: Unknown result type (might be due to invalid IL or missing references)
        //IL_0449: Unknown result type (might be due to invalid IL or missing references)
        //IL_044d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0453: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0505: Unknown result type (might be due to invalid IL or missing references)
        //IL_057d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0583: Unknown result type (might be due to invalid IL or missing references)
        //IL_0587: Unknown result type (might be due to invalid IL or missing references)
        //IL_058d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0591: Unknown result type (might be due to invalid IL or missing references)
        //IL_0597: Unknown result type (might be due to invalid IL or missing references)
        //IL_059b: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0952: Unknown result type (might be due to invalid IL or missing references)
        //IL_0958: Unknown result type (might be due to invalid IL or missing references)
        //IL_095c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0962: Unknown result type (might be due to invalid IL or missing references)
        //IL_0966: Unknown result type (might be due to invalid IL or missing references)
        //IL_096c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0970: Unknown result type (might be due to invalid IL or missing references)
        //IL_0976: Unknown result type (might be due to invalid IL or missing references)
        uIElement = new UIElement
        {
            Width =
            {
                Percent = 0.8f
            },
            MaxWidth = UICommon.MaxPanelWidth,
            Top =
            {
                Pixels = 220f
            },
            Height =
            {
                Pixels = -220f,
                Percent = 1f
            },
            HAlign = 0.5f
        };
        uIPanel = new UIPanel
        {
            Width =
            {
                Percent = 1f
            },
            Height =
            {
                Pixels = -110f,
                Percent = 1f
            },
            BackgroundColor = UICommon.MainPanelBackground,
            PaddingTop = 0f
        };
        uIElement.Append(uIPanel);
        uiLoader = new UILoaderAnimatedImage(0.5f, 0.5f);
        modList = new UIList
        {
            Width =
            {
                Pixels = -25f,
                Percent = 1f
            },
            Height =
            {
                Pixels = (ModLoader.showMemoryEstimates ? (-72) : (-50)),
                Percent = 1f
            },
            Top =
            {
                Pixels = (ModLoader.showMemoryEstimates ? 72 : 50)
            },
            ListPadding = 5f
        };
        uIPanel.Append(modList);
        if (ModLoader.showMemoryEstimates)
        {
            UIMemoryBar ramUsage = new UIMemoryBar
            {
                Top =
                {
                    Pixels = 45f
                }
            };
            ramUsage.Width.Pixels = -25f;
            uIPanel.Append(ramUsage);
        }
        UIScrollbar uIScrollbar = new UIScrollbar
        {
            Height =
            {
                Pixels = (ModLoader.showMemoryEstimates ? (-72) : (-50)),
                Percent = 1f
            },
            Top =
            {
                Pixels = (ModLoader.showMemoryEstimates ? 72 : 50)
            },
            HAlign = 1f
        }.WithView(100f, 1000f);
        uIPanel.Append(uIScrollbar);
        modList.SetScrollbar(uIScrollbar);
        UITextPanel<LocalizedText> uIHeaderTexTPanel = new UITextPanel<LocalizedText>(Language.GetText("tModLoader.ModsModsList"), 0.8f, large: true)
        {
            HAlign = 0.5f,
            Top =
            {
                Pixels = -35f
            },
            BackgroundColor = UICommon.DefaultUIBlue
        }.WithPadding(15f);
        uIElement.Append(uIHeaderTexTPanel);
        buttonEA = new UIAutoScaleTextTextPanel<LocalizedText>(Language.GetText("tModLoader.ModsEnableAll"))
        {
            TextColor = Color.Green,
            Width = new StyleDimension(-10f, 1f / 3f),
            Height =
            {
                Pixels = 40f
            },
            VAlign = 1f,
            Top =
            {
                Pixels = -65f
            }
        }.WithFadedMouseOver();
        buttonEA.OnLeftClick += EnableAll;
        uIElement.Append(buttonEA);
        buttonDA = new UIAutoScaleTextTextPanel<LocalizedText>(Language.GetText("tModLoader.ModsDisableAll"));
        buttonDA.CopyStyle(buttonEA);
        buttonDA.TextColor = Color.Red;
        buttonDA.HAlign = 0.5f;
        buttonDA.WithFadedMouseOver();
        buttonDA.OnLeftClick += DisableAll;
        uIElement.Append(buttonDA);
        buttonRM = new UIAutoScaleTextTextPanel<LocalizedText>(Language.GetText("tModLoader.ModsForceReload"));
        buttonRM.CopyStyle(buttonEA);
        buttonRM.Width = new StyleDimension(-10f, 1f / 3f);
        buttonRM.HAlign = 1f;
        buttonRM.WithFadedMouseOver();
        buttonRM.OnLeftClick += ReloadMods;
        uIElement.Append(buttonRM);
        UpdateTopRowButtons();
        buttonB = new UIAutoScaleTextTextPanel<LocalizedText>(Language.GetText("UI.Back"))
        {
            Width = new StyleDimension(-10f, 1f / 3f),
            Height =
            {
                Pixels = 40f
            },
            VAlign = 1f,
            Top =
            {
                Pixels = -20f
            }
        }.WithFadedMouseOver();
        buttonB.OnLeftClick += BackClick;
        uIElement.Append(buttonB);
        buttonOMF = new UIAutoScaleTextTextPanel<LocalizedText>(Language.GetText("tModLoader.ModsOpenModsFolders"));
        buttonOMF.CopyStyle(buttonB);
        buttonOMF.HAlign = 0.5f;
        buttonOMF.WithFadedMouseOver();
        buttonOMF.OnLeftClick += OpenModsFolder;
        uIElement.Append(buttonOMF);
        Asset<Texture2D> texture = UICommon.ModBrowserIconsTexture;
        UIElement upperMenuContainer = new UIElement
        {
            Width =
            {
                Percent = 1f
            },
            Height =
            {
                Pixels = 32f
            },
            Top =
            {
                Pixels = 10f
            }
        };
        for (int i = 0; i < 3; i++)
        {
            UICycleImage toggleImage;
            switch (i)
            {
            case 0:
                toggleImage = new UICycleImage(texture, 3, 32, 32, 102, 0);
                toggleImage.SetCurrentState((int)sortMode);
                toggleImage.OnLeftClick += delegate
                {
                    sortMode = sortMode.NextEnum();
                    updateNeeded = true;
                };
                toggleImage.OnRightClick += delegate
                {
                    sortMode = sortMode.PreviousEnum();
                    updateNeeded = true;
                };
                break;
            case 1:
                toggleImage = new UICycleImage(texture, 3, 32, 32, 136, 0);
                toggleImage.SetCurrentState((int)enabledFilterMode);
                toggleImage.OnLeftClick += delegate
                {
                    enabledFilterMode = enabledFilterMode.NextEnum();
                    updateNeeded = true;
                };
                toggleImage.OnRightClick += delegate
                {
                    enabledFilterMode = enabledFilterMode.PreviousEnum();
                    updateNeeded = true;
                };
                break;
            default:
                toggleImage = new UICycleImage(texture, 5, 32, 32, 170, 0);
                toggleImage.SetCurrentState((int)modSideFilterMode);
                toggleImage.OnLeftClick += delegate
                {
                    modSideFilterMode = modSideFilterMode.NextEnum();
                    updateNeeded = true;
                };
                toggleImage.OnRightClick += delegate
                {
                    modSideFilterMode = modSideFilterMode.PreviousEnum();
                    updateNeeded = true;
                };
                break;
            }
            toggleImage.Left.Pixels = i * 36 + 8;
            _categoryButtons.Add(toggleImage);
            upperMenuContainer.Append(toggleImage);
        }
        UIPanel filterTextBoxBackground = new UIPanel
        {
            Top =
            {
                Percent = 0f
            },
            Left =
            {
                Pixels = -185f,
                Percent = 1f
            },
            Width =
            {
                Pixels = 150f
            },
            Height =
            {
                Pixels = 40f
            }
        };
        filterTextBoxBackground.SetPadding(0f);
        filterTextBoxBackground.OnRightClick += ClearSearchField;
        upperMenuContainer.Append(filterTextBoxBackground);
        filterTextBox = new UIInputTextField(Language.GetTextValue("tModLoader.ModsTypeToSearch"))
        {
            Top =
            {
                Pixels = 5f
            },
            Height =
            {
                Percent = 1f
            },
            Width =
            {
                Percent = 1f
            },
            Left =
            {
                Pixels = 5f
            },
            VAlign = 0.5f
        };
        filterTextBox.OnTextChange += delegate
        {
            updateNeeded = true;
        };
        filterTextBoxBackground.Append(filterTextBox);
        UIImageButton clearSearchButton = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/SearchCancel"))
        {
            HAlign = 1f,
            VAlign = 0.5f,
            Left = new StyleDimension(-2f, 0f)
        };
        clearSearchButton.OnLeftClick += ClearSearchField;
        filterTextBoxBackground.Append(clearSearchButton);
        SearchFilterToggle = new UICycleImage(texture, 2, 32, 32, 68, 0)
        {
            Left =
            {
                Pixels = 545f
            }
        };
        SearchFilterToggle.SetCurrentState((int)searchFilterMode);
        SearchFilterToggle.OnLeftClick += delegate
        {
            searchFilterMode = searchFilterMode.NextEnum();
            updateNeeded = true;
        };
        SearchFilterToggle.OnRightClick += delegate
        {
            searchFilterMode = searchFilterMode.PreviousEnum();
            updateNeeded = true;
        };
        _categoryButtons.Add(SearchFilterToggle);
        upperMenuContainer.Append(SearchFilterToggle);
        buttonCL = new UIAutoScaleTextTextPanel<LocalizedText>(Language.GetText("tModLoader.ModConfiguration"));
        buttonCL.CopyStyle(buttonOMF);
        buttonCL.HAlign = 1f;
        buttonCL.WithFadedMouseOver();
        buttonCL.OnLeftClick += GotoModConfigList;
        uIElement.Append(buttonCL);
        uIPanel.Append(upperMenuContainer);
        Append(uIElement);
    }
References Terraria.ModLoader.UI.UIMods._categoryButtons, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.ModLoader.UI.UIMods.BackClick(), Terraria.ModLoader.UI.UIMods.buttonB, Terraria.ModLoader.UI.UIMods.buttonCL, Terraria.ModLoader.UI.UIMods.buttonDA, Terraria.ModLoader.UI.UIMods.buttonEA, Terraria.ModLoader.UI.UIMods.buttonOMF, Terraria.ModLoader.UI.UIMods.buttonRM, Terraria.ModLoader.UI.UIMods.ClearSearchField(), Terraria.ModLoader.UI.UIMods.DisableAll(), Terraria.ModLoader.UI.UIMods.EnableAll(), Terraria.ModLoader.UI.UIMods.enabledFilterMode, Terraria.ModLoader.UI.UIMods.filterTextBox, Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.UIMods.GotoModConfigList(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.ModLoader.UI.UICommon.MainPanelBackground, Terraria.ModLoader.UI.UICommon.MaxPanelWidth, Terraria.UI.UIElement.MaxWidth, Terraria.ModLoader.UI.UICommon.ModBrowserIconsTexture, Terraria.ModLoader.UI.UIMods.modList, Terraria.ModLoader.UI.UIMods.modSideFilterMode, Terraria.ModLoader.UI.UIMods.OpenModsFolder(), Terraria.UI.UIElement.PaddingTop, Terraria.ModLoader.UI.UIMods.ReloadMods(), Terraria.ModLoader.UI.UIMods.searchFilterMode, Terraria.ModLoader.UI.UIMods.SearchFilterToggle, Terraria.ModLoader.UI.UICycleImage.SetCurrentState(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.ModLoader.ModLoader.showMemoryEstimates, Terraria.ModLoader.UI.UIMods.sortMode, Terraria.UI.UIElement.Top, Terraria.ModLoader.UI.UIMods.uIElement, Terraria.ModLoader.UI.UIMods.uiLoader, Terraria.ModLoader.UI.UIMods.uIPanel, Terraria.ModLoader.UI.UIMods.updateNeeded, Terraria.ModLoader.UI.UIMods.UpdateTopRowButtons(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.