TModLoader: Terraria.Entity.InheritSource
InheritSource()
static ? IEntitySource Terraria.Entity.InheritSource (Entity entity) inline static inherited
    {
        if (entity == null)
        {
            return GetSource_None();
        }
        return entity.GetSource_FromThis();
    }
References Terraria.Entity.GetSource_FromThis(), and Terraria.Entity.GetSource_None().
Referenced by Terraria.GameContent.PortalHelper.AddPortal(), Terraria.Player.Counterweight(), and Terraria.Player.OnHit_Inner().