TModLoader: Terraria.Entity.Distance
Distance()
float Terraria.Entity.Distance (Vector2 Other) inline inherited
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        return Vector2.Distance(Center, Other);
    }
References Terraria.Entity.Center.
Referenced by Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_114_Dragonflies(), Terraria.NPC.AI_115_LadyBugs(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_120_HallowBoss_DashTo(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.NPC.AI_123_Deerclops(), Terraria.NPC.AI_123_Deerclops_Movement(), Terraria.NPC.AI_123_Deerclops_TryMakingSpike_FindBestY(), Terraria.Projectile.AI_158_BabyBird(), Terraria.Projectile.AI_169_Smolstars(), Terraria.NPC.BloodNautilus_CallForHelp(), Terraria.NPC.Boss_CanShootExtraAt(), Terraria.Projectile.CanHitWithMeleeWeapon(), Terraria.Projectile.CanHitWithOwnBody(), Terraria.GameContent.UI.EmoteBubble.CheckForNPCsToReactToEmoteBubble(), Terraria.Main.DrawInterface_14_EntityHealthBars(), Terraria.NPC.GetFairyTreasureCoords(), Terraria.NPC.GetNPCLocation(), Terraria.Projectile.ghostHeal(), Terraria.Projectile.HandleMovement(), Terraria.Wiring.HitWireSingle(), Terraria.Player.MinionRestTargetAim(), Terraria.Player.OnHurt_Part2(), Terraria.Utilities.NPCUtils.SearchFilters.OnlyPlayersInCertainDistance(), Terraria.Player.QuickMinecart(), Terraria.Player.QuickMinecartSnap(), Terraria.NPC.ShouldRunAway(), Terraria.WorldGen.SpawnFallingBlockProjectile(), Terraria.Player.SpawnHallucination(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.Projectile.SummonMonkGhast(), Terraria.GameContent.Events.MoonlordDeathDrama.Update(), Terraria.GameContent.Events.ScreenDarkness.Update(), Terraria.Projectile.Update(), Terraria.Player.UpdateBiomes(), Terraria.Player.UpdateMinionTarget(), and Terraria.NPC.VanillaAI_Inner().