TModLoader: Terraria.ModLoader.CombinedHooks.CanUseItem
CanUseItem()
static bool Terraria.ModLoader.CombinedHooks.CanUseItem (Player player, Item item) inline static
    {
        if (PlayerLoader.CanUseItem(player, item))
        {
            return ItemLoader.CanUseItem(item, player);
        }
        return false;
    }
References Terraria.ModLoader.ItemLoader.CanUseItem(), and Terraria.ModLoader.PlayerLoader.CanUseItem().
Referenced by Terraria.Player.ItemCheck_CheckCanUse(), Terraria.Player.QuickBuff(), Terraria.Player.QuickHeal_GetItemToUse(), and Terraria.Player.QuickMount_GetItemToUse().