TModLoader: Terraria.ModLoader.CombinedHooks.TotalUseTimeMultiplier
TotalUseTimeMultiplier()
static float Terraria.ModLoader.CombinedHooks.TotalUseTimeMultiplier (Player player, Item item) inline static
Definition at line 274 of file CombinedHooks.cs.
    {
        float useTimeMult = PlayerLoader.UseTimeMultiplier(player, item) * ItemLoader.UseTimeMultiplier(item, player);
        if (!item.attackSpeedOnlyAffectsWeaponAnimation)
        {
            useTimeMult /= TotalUseSpeedMultiplier(player, item);
        }
        return useTimeMult;
    }
References Terraria.Item.attackSpeedOnlyAffectsWeaponAnimation, Terraria.ModLoader.CombinedHooks.TotalUseSpeedMultiplier(), Terraria.ModLoader.ItemLoader.UseTimeMultiplier(), and Terraria.ModLoader.PlayerLoader.UseTimeMultiplier().
Referenced by Terraria.ModLoader.CombinedHooks.TotalUseTime().