TModLoader: Terraria.ModLoader.CombinedHooks.CanPlayerMeleeAttackCollideWithNPC
CanPlayerMeleeAttackCollideWithNPC()
static ? bool Terraria.ModLoader.CombinedHooks.CanPlayerMeleeAttackCollideWithNPC (Player player, Item item, Rectangle meleeAttackHitbox, NPC target) inline static
Definition at line 244 of file CombinedHooks.cs.
    {
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        bool? ret = null;
        if (Update(PlayerLoader.CanMeleeAttackCollideWithNPC(player, item, meleeAttackHitbox, target)) && Update(ItemLoader.CanMeleeAttackCollideWithNPC(item, meleeAttackHitbox, player, target)))
        {
            Update(NPCLoader.CanCollideWithPlayerMeleeAttack(target, player, item, meleeAttackHitbox));
        }
        else
            _ = 0;
        return ret;
        bool Update(bool? b)
        {
            return !((!(ret ?? (ret = b))) ?? false);
        }
    }
References Terraria.ModLoader.NPCLoader.CanCollideWithPlayerMeleeAttack(), Terraria.ModLoader.ItemLoader.CanMeleeAttackCollideWithNPC(), and Terraria.ModLoader.PlayerLoader.CanMeleeAttackCollideWithNPC().
Referenced by Terraria.Player.ProcessHitAgainstNPC().