TModLoader: Terraria.ModLoader.CombinedHooks.ModifyHitByProjectile
ModifyHitByProjectile()
static void Terraria.ModLoader.CombinedHooks.ModifyHitByProjectile (Player player, Projectile projectile, ref Player::HurtModifiers modifiers) inline static
    {
        ProjectileLoader.ModifyHitPlayer(projectile, player, ref modifiers);
        PlayerLoader.ModifyHitByProjectile(player, projectile, ref modifiers);
        player.ApplyBannerDefenseBuff(projectile.bannerIdToRespondTo, ref modifiers);
        if (player.resistCold && projectile.coldDamage)
        {
            modifiers.IncomingDamageMultiplier *= 0.7f;
        }
        if (projectile.reflected || ProjectileID.Sets.PlayerHurtDamageIgnoresDifficultyScaling[projectile.type])
        {
            return;
        }
        float damageMult = Main.GameModeInfo.EnemyDamageMultiplier;
        if (Main.GameModeInfo.IsJourneyMode)
        {
            CreativePowers.DifficultySliderPower power = CreativePowerManager.Instance.GetPower<CreativePowers.DifficultySliderPower>();
            if (power.GetIsUnlocked())
            {
                damageMult = power.StrengthMultiplierToGiveNPCs;
            }
        }
        modifiers.SourceDamage *= damageMult;
    }
References Terraria.Player.ApplyBannerDefenseBuff(), Terraria.Projectile.bannerIdToRespondTo, Terraria.Projectile.coldDamage, Terraria.DataStructures.GameModeData.EnemyDamageMultiplier, Terraria.Main.GameModeInfo, Terraria.GameContent.Creative.CreativePowerManager.Instance, Terraria.DataStructures.GameModeData.IsJourneyMode, Terraria.ModLoader.PlayerLoader.ModifyHitByProjectile(), Terraria.ModLoader.ProjectileLoader.ModifyHitPlayer(), Terraria.ID.ProjectileID.Sets.PlayerHurtDamageIgnoresDifficultyScaling, Terraria.Projectile.reflected, Terraria.Player.resistCold, and Terraria.Projectile.type.
Referenced by Terraria.ModLoader.PlayerLoader.ModifyHurt().