TModLoader: Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceSupportBeams
PlaceSupportBeams()
void Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceSupportBeams () inline private inherited
Definition at line 413 of file HouseBuilder.cs.
    {
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        foreach (Rectangle item in CreateSupportBeamList())
        {
            if (item.Height > 1 && _tiles[item.X, item.Y - 1].type != 19)
            {
                WorldUtils.Gen(new Point(item.X, item.Y), new Shapes.Rectangle(item.Width, item.Height), Actions.Chain(new Actions.SetTileKeepWall(BeamType), new Actions.SetFrames(frameNeighbors: true)));
                Tile tile = _tiles[item.X, item.Y + item.Height];
                tile.slope(0);
                tile.halfBrick(halfBrick: false);
            }
        }
    }
References Terraria.GameContent.Biomes.CaveHouse.HouseBuilder._tiles, Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.BeamType, Terraria.WorldBuilding.Actions.Chain(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.CreateSupportBeamList(), Terraria.WorldBuilding.WorldUtils.Gen(), Terraria.Tile.halfBrick(), and Terraria.Tile.slope().
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Place().