TModLoader: Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceBiomeSpecificTool
PlaceBiomeSpecificTool()
void Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceBiomeSpecificTool (HouseBuilderContext context) inline private inherited
    {
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0181: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_0258: Unknown result type (might be due to invalid IL or missing references)
        //IL_025f: Unknown result type (might be due to invalid IL or missing references)
        if (Type == HouseType.Jungle && context.SharpenerCount < _random.Next(2, 5))
        {
            bool flag = false;
            foreach (Rectangle room in Rooms)
            {
                int num = room.Height - 2 + room.Y;
                for (int i = 0; i < 10; i++)
                {
                    int num2 = _random.Next(2, room.Width - 2) + room.X;
                    WorldGen.PlaceTile(num2, num, 377, mute: true, forced: true);
                    if (flag = _tiles[num2, num].active() && _tiles[num2, num].type == 377)
                    {
                        break;
                    }
                }
                if (flag)
                {
                    break;
                }
                for (int j = room.X + 2; j <= room.X + room.Width - 2; j++)
                {
                    if (flag = WorldGen.PlaceTile(j, num, 377, mute: true, forced: true))
                    {
                        break;
                    }
                }
                if (flag)
                {
                    break;
                }
            }
            if (flag)
            {
                context.SharpenerCount++;
            }
        }
        if (Type != HouseType.Desert || context.ExtractinatorCount >= _random.Next(2, 5))
        {
            return;
        }
        bool flag2 = false;
        foreach (Rectangle room2 in Rooms)
        {
            int num3 = room2.Height - 2 + room2.Y;
            for (int k = 0; k < 10; k++)
            {
                int num4 = _random.Next(2, room2.Width - 2) + room2.X;
                WorldGen.PlaceTile(num4, num3, 219, mute: true, forced: true);
                if (flag2 = _tiles[num4, num3].active() && _tiles[num4, num3].type == 219)
                {
                    break;
                }
            }
            if (flag2)
            {
                break;
            }
            for (int l = room2.X + 2; l <= room2.X + room2.Width - 2; l++)
            {
                if (flag2 = WorldGen.PlaceTile(l, num3, 219, mute: true, forced: true))
                {
                    break;
                }
            }
            if (flag2)
            {
                break;
            }
        }
        if (flag2)
        {
            context.ExtractinatorCount++;
        }
    }
References Terraria.GameContent.Biomes.CaveHouse.HouseBuilder._random, Terraria.GameContent.Biomes.CaveHouse.HouseBuilder._tiles, Terraria.GameContent.Biomes.CaveHouse.HouseBuilderContext.ExtractinatorCount, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Rooms, and Terraria.GameContent.Biomes.CaveHouse.HouseBuilderContext.SharpenerCount.
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Place().