TModLoader: Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.CreateSupportBeamList
CreateSupportBeamList()
List< Rectangle > Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.CreateSupportBeamList () inline private inherited
    {
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        //IL_019f: Unknown result type (might be due to invalid IL or missing references)
        List<Rectangle> list = new List<Rectangle>();
        int num = Rooms.Min((Rectangle room) => ((Rectangle)(ref room)).Left);
        int num2 = Rooms.Max((Rectangle room) => ((Rectangle)(ref room)).Right) - 1;
        int num3 = 6;
        while (num3 > 4 && (num2 - num) % num3 != 0)
        {
            num3--;
        }
        for (int i = num; i <= num2; i += num3)
        {
            for (int j = 0; j < Rooms.Count; j++)
            {
                Rectangle rectangle = Rooms[j];
                if (i < rectangle.X || i >= rectangle.X + rectangle.Width)
                {
                    continue;
                }
                int num4 = rectangle.Y + rectangle.Height;
                int num5 = 50;
                for (int k = j + 1; k < Rooms.Count; k++)
                {
                    if (i >= Rooms[k].X && i < Rooms[k].X + Rooms[k].Width)
                    {
                        num5 = Math.Min(num5, Rooms[k].Y - num4);
                    }
                }
                if (num5 > 0)
                {
                    Point result;
                    bool flag = WorldUtils.Find(new Point(i, num4), Searches.Chain(new Searches.Down(num5), new Conditions.IsSolid()), out result);
                    if (num5 < 50)
                    {
                        flag = true;
                        ((Point)(ref result))._002Ector(i, num4 + num5);
                    }
                    if (flag)
                    {
                        list.Add(new Rectangle(i, num4, 1, result.Y - num4));
                    }
                }
            }
        }
        return list;
    }
References Terraria.WorldBuilding.Searches.Chain(), Terraria.WorldBuilding.WorldUtils.Find(), and Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Rooms.
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceSupportBeams().