TModLoader: Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceBiomeSpecificPriorityTool
PlaceBiomeSpecificPriorityTool()
void Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceBiomeSpecificPriorityTool (HouseBuilderContext context) inline private inherited
    {
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0113: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_0181: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        if (Type != HouseType.Desert || GenVars.extraBastStatueCount >= GenVars.extraBastStatueCountMax)
        {
            return;
        }
        bool flag = false;
        foreach (Rectangle room in Rooms)
        {
            int num = room.Height - 2 + room.Y;
            if (WorldGen.remixWorldGen && (double)num > Main.rockLayer)
            {
                return;
            }
            for (int i = 0; i < 10; i++)
            {
                int num2 = _random.Next(2, room.Width - 2) + room.X;
                WorldGen.PlaceTile(num2, num, 506, mute: true, forced: true);
                if (flag = _tiles[num2, num].active() && _tiles[num2, num].type == 506)
                {
                    break;
                }
            }
            if (flag)
            {
                break;
            }
            for (int j = room.X + 2; j <= room.X + room.Width - 2; j++)
            {
                if (flag = WorldGen.PlaceTile(j, num, 506, mute: true, forced: true))
                {
                    break;
                }
            }
            if (flag)
            {
                break;
            }
        }
        if (!flag)
        {
            foreach (Rectangle room2 in Rooms)
            {
                int num3 = room2.Y - 1;
                for (int k = 0; k < 10; k++)
                {
                    int num4 = _random.Next(2, room2.Width - 2) + room2.X;
                    WorldGen.PlaceTile(num4, num3, 506, mute: true, forced: true);
                    if (flag = _tiles[num4, num3].active() && _tiles[num4, num3].type == 506)
                    {
                        break;
                    }
                }
                if (flag)
                {
                    break;
                }
                for (int l = room2.X + 2; l <= room2.X + room2.Width - 2; l++)
                {
                    if (flag = WorldGen.PlaceTile(l, num3, 506, mute: true, forced: true))
                    {
                        break;
                    }
                }
                if (flag)
                {
                    break;
                }
            }
        }
        if (flag)
        {
            GenVars.extraBastStatueCount++;
        }
    }
References Terraria.GameContent.Biomes.CaveHouse.HouseBuilder._random, Terraria.GameContent.Biomes.CaveHouse.HouseBuilder._tiles, Terraria.WorldBuilding.GenVars.extraBastStatueCount, Terraria.WorldBuilding.GenVars.extraBastStatueCountMax, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.remixWorldGen, Terraria.Main.rockLayer, and Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Rooms.
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Place().