TModLoader: Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceChests
PlaceChests()
void Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceChests () inline private inherited
    {
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_0242: Unknown result type (might be due to invalid IL or missing references)
        //IL_0256: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00da: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        if (_random.NextDouble() > ChestChance)
        {
            return;
        }
        bool flag = false;
        foreach (Rectangle room in Rooms)
        {
            int num = room.Height - 1 + room.Y;
            bool num4 = num > (int)Main.worldSurface;
            ushort chestTileType = (ushort)((num4 && UsesContainers2) ? 467u : 21u);
            int style = (num4 ? ChestStyle : 0);
            for (int i = 0; i < 10; i++)
            {
                if (flag = WorldGen.AddBuriedChest(_random.Next(2, room.Width - 2) + room.X, num, 0, notNearOtherChests: false, style, trySlope: false, chestTileType))
                {
                    break;
                }
            }
            if (flag)
            {
                break;
            }
            for (int j = room.X + 2; j <= room.X + room.Width - 2; j++)
            {
                if (flag = WorldGen.AddBuriedChest(j, num, 0, notNearOtherChests: false, style, trySlope: false, chestTileType))
                {
                    break;
                }
            }
            if (flag)
            {
                break;
            }
        }
        if (!flag)
        {
            foreach (Rectangle room2 in Rooms)
            {
                int num2 = room2.Y - 1;
                bool num5 = num2 > (int)Main.worldSurface;
                ushort chestTileType2 = (ushort)((num5 && UsesContainers2) ? 467u : 21u);
                int style2 = (num5 ? ChestStyle : 0);
                for (int k = 0; k < 10; k++)
                {
                    if (flag = WorldGen.AddBuriedChest(_random.Next(2, room2.Width - 2) + room2.X, num2, 0, notNearOtherChests: false, style2, trySlope: false, chestTileType2))
                    {
                        break;
                    }
                }
                if (flag)
                {
                    break;
                }
                for (int l = room2.X + 2; l <= room2.X + room2.Width - 2; l++)
                {
                    if (flag = WorldGen.AddBuriedChest(l, num2, 0, notNearOtherChests: false, style2, trySlope: false, chestTileType2))
                    {
                        break;
                    }
                }
                if (flag)
                {
                    break;
                }
            }
        }
        if (flag)
        {
            return;
        }
        for (int m = 0; m < 1000; m++)
        {
            int i2 = _random.Next(Rooms[0].X - 30, Rooms[0].X + 30);
            int num3 = _random.Next(Rooms[0].Y - 30, Rooms[0].Y + 30);
            bool num6 = num3 > (int)Main.worldSurface;
            ushort chestTileType3 = (ushort)((num6 && UsesContainers2) ? 467u : 21u);
            int style3 = (num6 ? ChestStyle : 0);
            if (flag = WorldGen.AddBuriedChest(i2, num3, 0, notNearOtherChests: false, style3, trySlope: false, chestTileType3))
            {
                break;
            }
        }
    }
References Terraria.GameContent.Biomes.CaveHouse.HouseBuilder._random, Terraria.WorldGen.AddBuriedChest(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.ChestChance, Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.ChestStyle, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Rooms, Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.UsesContainers2, and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.Place().
ml>