TModLoader: Terraria.ModLoader.UI.UIModItem.DrawSelf
DrawSelf()
override void Terraria.ModLoader.UI.UIModItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.GameContent.UI.Elements.UIPanel.
Definition at line 478 of file UIModItem.cs.
    {
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01be: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        base.DrawSelf(spriteBatch);
        CalculatedStyle innerDimensions = GetInnerDimensions();
        Vector2 drawPos = default(Vector2);
        ((Vector2)(ref drawPos))._002Ector(innerDimensions.X + 5f + (float)_modIconAdjust, innerDimensions.Y + 30f);
        spriteBatch.Draw(UICommon.DividerTexture.Value, drawPos, (Rectangle?)null, Color.White, 0f, Vector2.Zero, new Vector2((innerDimensions.Width - 10f - (float)_modIconAdjust) / 8f, 1f), (SpriteEffects)0, 0f);
        ((Vector2)(ref drawPos))._002Ector(innerDimensions.X + 10f + (float)_modIconAdjust, innerDimensions.Y + 45f);
        if (_mod.properties.side != ModSide.Server && (_mod.Enabled != _loaded || _configChangesRequireReload))
        {
            drawPos += new Vector2(_uiModStateText.Width.Pixels + left2ndLine, 0f);
            Utils.DrawBorderString(spriteBatch, _configChangesRequireReload ? Language.GetTextValue("tModLoader.ModReloadForced") : Language.GetTextValue("tModLoader.ModReloadRequired"), drawPos, Color.White);
        }
        if (_mod.properties.side == ModSide.Server)
        {
            drawPos += new Vector2(90f, -2f);
            spriteBatch.Draw(UICommon.ModBrowserIconsTexture.Value, drawPos, (Rectangle?)new Rectangle(170, 102, 32, 32), Color.White, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
            Rectangle val = new Rectangle((int)drawPos.X, (int)drawPos.Y, 32, 32);
            if (((Rectangle)(ref val)).Contains(Main.MouseScreen.ToPoint()))
            {
                UICommon.DrawHoverStringInBounds(spriteBatch, Language.GetTextValue("tModLoader.ModIsServerSide"));
            }
        }
        UIImage moreInfoButton = _moreInfoButton;
        if (moreInfoButton != null && moreInfoButton.IsMouseHovering)
        {
            _tooltip = Language.GetTextValue("tModLoader.ModsMoreInfo");
            return;
        }
        UIImage deleteModButton = _deleteModButton;
        if (deleteModButton != null && deleteModButton.IsMouseHovering)
        {
            _tooltip = Language.GetTextValue("UI.Delete");
            return;
        }
        UIText modName = _modName;
        if (modName != null && modName.IsMouseHovering)
        {
            LocalMod mod = _mod;
            if (mod != null && mod.properties.author.Length > 0)
            {
                _tooltip = Language.GetTextValue("tModLoader.ModsByline", _mod.properties.author);
                return;
            }
        }
        UIModStateText uiModStateText = _uiModStateText;
        if (uiModStateText != null && uiModStateText.IsMouseHovering)
        {
            _tooltip = ToggleModStateText;
            return;
        }
        UIImage configButton = _configButton;
        if (configButton != null && configButton.IsMouseHovering)
        {
            _tooltip = Language.GetTextValue("tModLoader.ModsOpenConfig");
            return;
        }
        UIImageFramed uIImageFramed = updatedModDot;
        if (uIImageFramed != null && uIImageFramed.IsMouseHovering)
        {
            if (previousVersionHint == null)
            {
                _tooltip = Language.GetTextValue("tModLoader.ModAddedSinceLastLaunchMessage");
            }
            else
            {
                _tooltip = Language.GetTextValue("tModLoader.ModUpdatedSinceLastLaunchMessage", previousVersionHint);
            }
            return;
        }
        UIAutoScaleTextTextPanel<string> uIAutoScaleTextTextPanel = tMLUpdateRequired;
        if (uIAutoScaleTextTextPanel != null && uIAutoScaleTextTextPanel.IsMouseHovering)
        {
            _tooltip = Language.GetTextValue("tModLoader.SwitchVersionInfoButton");
            return;
        }
        UIImage modReferenceIcon = _modReferenceIcon;
        if (modReferenceIcon != null && modReferenceIcon.IsMouseHovering)
        {
            string refs2 = string.Join(", ", _mod.properties.modReferences);
            _tooltip = Language.GetTextValue("tModLoader.ModDependencyTooltip", refs2);
            return;
        }
        UIImage translationModIcon = _translationModIcon;
        if (translationModIcon != null && translationModIcon.IsMouseHovering)
        {
            string refs = string.Join(", ", _mod.properties.RefNames(includeWeak: true));
            _tooltip = Language.GetTextValue("tModLoader.TranslationModTooltip", refs);
        }
    }
References Terraria.ModLoader.UI.UIModItem._configButton, Terraria.ModLoader.UI.UIModItem._configChangesRequireReload, Terraria.ModLoader.UI.UIModItem._deleteModButton, Terraria.ModLoader.UI.UIModItem._loaded, Terraria.ModLoader.UI.UIModItem._mod, Terraria.ModLoader.UI.UIModItem._modIconAdjust, Terraria.ModLoader.UI.UIModItem._modName, Terraria.ModLoader.UI.UIModItem._modReferenceIcon, Terraria.ModLoader.UI.UIModItem._moreInfoButton, Terraria.ModLoader.UI.UIModItem._tooltip, Terraria.ModLoader.UI.UIModItem._translationModIcon, Terraria.ModLoader.UI.UIModItem._uiModStateText, Terraria.ModLoader.UI.UICommon.DividerTexture, Terraria.Utils.DrawBorderString(), Terraria.ModLoader.UI.UICommon.DrawHoverStringInBounds(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.IsMouseHovering, Terraria.ModLoader.UI.UIModItem.left2ndLine, Terraria.ModLoader.UI.UICommon.ModBrowserIconsTexture, Terraria.Main.MouseScreen, Terraria.UI.StyleDimension.Pixels, Terraria.ModLoader.UI.UIModItem.previousVersionHint, Terraria.ModLoader.Core.LocalMod.properties, Terraria.ModLoader.UI.UIModItem.tMLUpdateRequired, Terraria.ModLoader.UI.UIModItem.ToggleModStateText, Terraria.ModLoader.UI.UIModItem.updatedModDot, and Terraria.UI.UIElement.Width.