TModLoader: Terraria.ModLoader.UI.UIModItem.QuickModDelete
QuickModDelete()
void Terraria.ModLoader.UI.UIModItem.QuickModDelete (UIMouseEvent evt, UIElement listeningElement) inline private
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_012e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0230: Unknown result type (might be due to invalid IL or missing references)
        //IL_0236: Unknown result type (might be due to invalid IL or missing references)
        //IL_0239: Unknown result type (might be due to invalid IL or missing references)
        //IL_023f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0242: Unknown result type (might be due to invalid IL or missing references)
        //IL_0248: Unknown result type (might be due to invalid IL or missing references)
        if (!Main.keyState.PressingShift())
        {
            SoundEngine.PlaySound(10);
            _blockInput = new UIImage(TextureAssets.Extra[190])
            {
                Width =
                {
                    Percent = 1f
                },
                Height =
                {
                    Percent = 1f
                },
                Color = new Color(0, 0, 0, 0),
                ScaleToFit = true
            };
            _blockInput.OnLeftMouseDown += CloseDialog;
            Interface.modsMenu.Append(_blockInput);
            _deleteModDialog = new UIPanel
            {
                Width =
                {
                    Percent = 0.3f
                },
                Height =
                {
                    Percent = 0.3f
                },
                HAlign = 0.5f,
                VAlign = 0.5f,
                BackgroundColor = new Color(63, 82, 151),
                BorderColor = Color.Black
            };
            _deleteModDialog.SetPadding(6f);
            Interface.modsMenu.Append(_deleteModDialog);
            _dialogYesButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("LegacyMenu.104"))
            {
                TextColor = Color.White,
                Width = new StyleDimension(-10f, 1f / 3f),
                Height =
                {
                    Pixels = 40f
                },
                VAlign = 0.85f,
                HAlign = 0.15f
            }.WithFadedMouseOver();
            _dialogYesButton.OnLeftClick += DeleteMod;
            _deleteModDialog.Append(_dialogYesButton);
            _dialogNoButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("LegacyMenu.105"))
            {
                TextColor = Color.White,
                Width = new StyleDimension(-10f, 1f / 3f),
                Height =
                {
                    Pixels = 40f
                },
                VAlign = 0.85f,
                HAlign = 0.85f
            }.WithFadedMouseOver();
            _dialogNoButton.OnLeftClick += CloseDialog;
            _deleteModDialog.Append(_dialogNoButton);
            _dialogText = new UIText(Language.GetTextValue("tModLoader.DeleteModConfirm"))
            {
                Width =
                {
                    Percent = 0.75f
                },
                HAlign = 0.5f,
                VAlign = 0.3f,
                IsWrapped = true
            };
            _deleteModDialog.Append(_dialogText);
        }
        else
        {
            DeleteMod(evt, listeningElement);
        }
    }
References Terraria.ModLoader.UI.UIModItem._blockInput, Terraria.ModLoader.UI.UIModItem._deleteModDialog, Terraria.ModLoader.UI.UIModItem._dialogNoButton, Terraria.ModLoader.UI.UIModItem._dialogText, Terraria.ModLoader.UI.UIModItem._dialogYesButton, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIPanel.BackgroundColor, Terraria.GameContent.UI.Elements.UIPanel.BorderColor, Terraria.ModLoader.UI.UIModItem.CloseDialog(), Terraria.ModLoader.UI.UIModItem.DeleteMod(), Terraria.GameContent.TextureAssets.Extra, Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.Main.keyState, Terraria.ModLoader.UI.Interface.modsMenu, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.ModLoader.UI.UIModItem.OnInitialize().