TModLoader: Terraria.ModLoader.UI.UIModItem.OnInitialize
OnInitialize()
override void Terraria.ModLoader.UI.UIModItem.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 124 of file UIModItem.cs.
    {
        //IL_0209: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0304: Unknown result type (might be due to invalid IL or missing references)
        //IL_0308: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0320: Unknown result type (might be due to invalid IL or missing references)
        //IL_0327: Unknown result type (might be due to invalid IL or missing references)
        //IL_032c: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0803: Unknown result type (might be due to invalid IL or missing references)
        //IL_0808: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0abb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b18: Unknown result type (might be due to invalid IL or missing references)
        base.OnInitialize();
        string text = _mod.DisplayName + " v" + _mod.modFile.Version;
        Asset<Texture2D> modIcon = Main.Assets.Request<Texture2D>("Images/UI/DefaultResourcePackIcon", AssetRequestMode.ImmediateLoad);
        _modIconAdjust += 85;
        if (_mod.modFile.HasFile("icon.png"))
        {
            try
            {
                using (_mod.modFile.Open())
                {
                    using Stream s = _mod.modFile.GetStream("icon.png");
                    Asset<Texture2D> iconTexture = Main.Assets.CreateUntracked<Texture2D>(s, ".png");
                    if (iconTexture.Width() == 80 && iconTexture.Height() == 80)
                    {
                        modIcon = iconTexture;
                    }
                }
            }
            catch (Exception e2)
            {
                Logging.tML.Error((object)"Unknown error", e2);
            }
        }
        _modIcon = new UIImage(modIcon)
        {
            Left =
            {
                Percent = 0f
            },
            Top =
            {
                Percent = 0f
            },
            Width =
            {
                Pixels = 80f
            },
            Height =
            {
                Pixels = 80f
            },
            ScaleToFit = true
        };
        Append(_modIcon);
        _modName = new UIText(text)
        {
            Left = new StyleDimension(_modIconAdjust, 0f),
            Top =
            {
                Pixels = 5f
            }
        };
        Append(_modName);
        _uiModStateText = new UIModStateText(_mod.Enabled)
        {
            Top =
            {
                Pixels = 40f
            },
            Left =
            {
                Pixels = _modIconAdjust
            }
        };
        _uiModStateText.OnLeftClick += ToggleEnabled;
        string updateVersion = null;
        string updateURL = "https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#beta-branches";
        Color updateColor = Color.Orange;
        if (BuildInfo.tMLVersion.MajorMinorBuild() < _mod.tModLoaderVersion.MajorMinorBuild())
        {
            updateVersion = $"v{_mod.tModLoaderVersion}";
            if (_mod.tModLoaderVersion.MajorMinor() > BuildInfo.stableVersion)
            {
                updateVersion = "Preview " + updateVersion;
            }
        }
        if (!CheckIfPublishedForThisBrowserVersion(out var modBrowserVersion))
        {
            updateVersion = $"{modBrowserVersion} v{_mod.tModLoaderVersion}";
            updateColor = Color.Yellow;
        }
        if (updateVersion != null)
        {
            tMLUpdateRequired = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.MBRequiresTMLUpdate", updateVersion)).WithFadedMouseOver(updateColor, updateColor * 0.7f);
            tMLUpdateRequired.BackgroundColor = updateColor * 0.7f;
            tMLUpdateRequired.Top.Pixels = 40f;
            tMLUpdateRequired.Width.Pixels = 280f;
            tMLUpdateRequired.Height.Pixels = 36f;
            tMLUpdateRequired.Left.Pixels += _uiModStateText.Width.Pixels + _uiModStateText.Left.Pixels + 5f;
            tMLUpdateRequired.OnLeftClick += delegate
            {
                Utils.OpenToURL(updateURL);
            };
            Append(tMLUpdateRequired);
        }
        else
        {
            Append(_uiModStateText);
        }
        int bottomRightRowOffset = -36;
        _moreInfoButton = new UIImage(UICommon.ButtonModInfoTexture)
        {
            Width =
            {
                Pixels = 36f
            },
            Height =
            {
                Pixels = 36f
            },
            Left =
            {
                Pixels = bottomRightRowOffset,
                Precent = 1f
            },
            Top =
            {
                Pixels = 40f
            }
        };
        _moreInfoButton.OnLeftClick += ShowMoreInfo;
        Append(_moreInfoButton);
        if (ModLoader.TryGetMod(ModName, out var loadedMod) && ConfigManager.Configs.ContainsKey(loadedMod))
        {
            bottomRightRowOffset -= 36;
            _configButton = new UIImage(UICommon.ButtonModConfigTexture)
            {
                Width =
                {
                    Pixels = 36f
                },
                Height =
                {
                    Pixels = 36f
                },
                Left =
                {
                    Pixels = (float)bottomRightRowOffset - 5f,
                    Precent = 1f
                },
                Top =
                {
                    Pixels = 40f
                }
            };
            _configButton.OnLeftClick += OpenConfig;
            Append(_configButton);
            if (ConfigManager.ModNeedsReload(loadedMod))
            {
                _configChangesRequireReload = true;
            }
        }
        _modReferences = _mod.properties.modReferences.Select((BuildProperties.ModReference x) => x.mod).ToArray();
        if (_modReferences.Length != 0 && !_mod.Enabled)
        {
            Asset<Texture2D> icon2 = UICommon.ButtonExclamationTexture;
            _modReferenceIcon = new UIImage(icon2)
            {
                Left = new StyleDimension(_uiModStateText.Left.Pixels + _uiModStateText.Width.Pixels + 5f + left2ndLine, 0f),
                Top =
                {
                    Pixels = 42.5f
                }
            };
            left2ndLine += 28f;
            Append(_modReferenceIcon);
        }
        if (_mod.properties.RefNames(includeWeak: true).Any() && _mod.properties.translationMod)
        {
            Asset<Texture2D> icon = UICommon.ButtonTranslationModTexture;
            _translationModIcon = new UIImage(icon)
            {
                Left = new StyleDimension(_uiModStateText.Left.Pixels + _uiModStateText.Width.Pixels + 5f + left2ndLine, 0f),
                Top =
                {
                    Pixels = 42.5f
                }
            };
            left2ndLine += 28f;
            Append(_translationModIcon);
        }
        if (BuildInfo.IsDev && ModCompile.DeveloperMode && ModLoader.IsUnloadedModStillAlive(ModName))
        {
            _keyImage = new UIHoverImage(UICommon.ButtonErrorTexture, Language.GetTextValue("tModLoader.ModDidNotFullyUnloadWarning"))
            {
                Left =
                {
                    Pixels = (float)_modIconAdjust + 5f
                },
                Top =
                {
                    Pixels = 3f
                }
            };
            Append(_keyImage);
            _modName.Left.Pixels += _keyImage.Width.Pixels + 10f;
            _modName.Recalculate();
        }
        if (ModOrganizer.CheckStableBuildOnPreview(_mod))
        {
            _keyImage = new UIHoverImage(Main.Assets.Request<Texture2D>(TextureAssets.Item[3999].Name), Language.GetTextValue("tModLoader.ModStableOnPreviewWarning"))
            {
                Left =
                {
                    Pixels = 4f,
                    Percent = 0.2f
                },
                Top =
                {
                    Pixels = 0f,
                    Percent = 0.5f
                }
            };
            Append(_keyImage);
        }
        if (_mod.modFile.path.StartsWith(ModLoader.ModPath))
        {
            BackgroundColor = Color.MediumPurple * 0.7f;
            modFromLocalModFolder = true;
        }
        else
        {
            UIImage steamIcon = new UIImage(TextureAssets.Extra[243])
            {
                Left =
                {
                    Pixels = -22f,
                    Percent = 1f
                }
            };
            Append(steamIcon);
        }
        if (loadedMod != null)
        {
            _loaded = true;
            int[] values = new int[6]
            {
                loadedMod.GetContent<ModItem>().Count(),
                loadedMod.GetContent<ModNPC>().Count(),
                loadedMod.GetContent<ModTile>().Count(),
                loadedMod.GetContent<ModWall>().Count(),
                loadedMod.GetContent<ModBuff>().Count(),
                loadedMod.GetContent<ModMount>().Count()
            };
            string[] localizationKeys = new string[6] { "ModsXItems", "ModsXNPCs", "ModsXTiles", "ModsXWalls", "ModsXBuffs", "ModsXMounts" };
            int xOffset = -40;
            for (int i = 0; i < values.Length; i++)
            {
                if (values[i] > 0)
                {
                    _keyImage = new UIHoverImage(Main.Assets.Request<Texture2D>(TextureAssets.InfoIcon[i].Name), Language.GetTextValue("tModLoader." + localizationKeys[i], values[i]))
                    {
                        Left =
{
                            Pixels = xOffset,
                            Percent = 1f
                        }
                    };
                    Append(_keyImage);
                    xOffset -= 18;
                }
            }
        }
        base.OnLeftDoubleClick += delegate(UIMouseEvent e, UIElement el)
        {
            if (e.Target.GetType() != typeof(UIModStateText))
            {
                _uiModStateText.LeftClick(e);
            }
        };
        if (!_loaded)
        {
            bottomRightRowOffset -= 36;
            _deleteModButton = new UIImage(TextureAssets.Trash)
            {
                Width =
                {
                    Pixels = 36f
                },
                Height =
                {
                    Pixels = 36f
                },
                Left =
                {
                    Pixels = (float)bottomRightRowOffset - 5f,
                    Precent = 1f
                },
                Top =
                {
                    Pixels = 42.5f
                }
            };
            _deleteModButton.OnLeftClick += QuickModDelete;
            Append(_deleteModButton);
        }
        (string, Version) oldModVersionData = ModOrganizer.modsThatUpdatedSinceLastLaunch.FirstOrDefault(((string ModName, Version previousVersion) x) => x.ModName == ModName);
        (string, Version) tuple = oldModVersionData;
        if (tuple.Item1 != null || tuple.Item2 != null)
        {
            previousVersionHint = oldModVersionData.Item2;
            Asset<Texture2D> toggleImage = Main.Assets.Request<Texture2D>("Images/UI/Settings_Toggle");
            UIImageFramed uIImageFramed = new UIImageFramed(toggleImage, toggleImage.Frame(2, 1, 1));
            ref StyleDimension left = ref uIImageFramed.Left;
            Rectangle val = _modName.GetInnerDimensions().ToRectangle();
            left.Pixels = ((Rectangle)(ref val)).Right + 8;
            uIImageFramed.Left.Percent = 0f;
            uIImageFramed.Top.Pixels = 5f;
            uIImageFramed.Top.Percent = 0f;
            uIImageFramed.Color = (Color)((previousVersionHint == null) ? Color.Green : new Color(6, 95, 212));
            updatedModDot = uIImageFramed;
            Append(updatedModDot);
        }
    }
References Terraria.ModLoader.UI.UIModItem._configButton, Terraria.ModLoader.UI.UIModItem._configChangesRequireReload, Terraria.ModLoader.UI.UIModItem._deleteModButton, Terraria.ModLoader.UI.UIModItem._keyImage, Terraria.ModLoader.UI.UIModItem._loaded, Terraria.ModLoader.UI.UIModItem._mod, Terraria.ModLoader.UI.UIModItem._modIcon, Terraria.ModLoader.UI.UIModItem._modIconAdjust, Terraria.ModLoader.UI.UIModItem._modName, Terraria.ModLoader.UI.UIModItem._modReferenceIcon, Terraria.ModLoader.UI.UIModItem._modReferences, Terraria.ModLoader.UI.UIModItem._moreInfoButton, Terraria.ModLoader.UI.UIModItem._translationModIcon, Terraria.ModLoader.UI.UIModItem._uiModStateText, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UIPanel.BackgroundColor, Terraria.ModLoader.UI.UICommon.ButtonErrorTexture, Terraria.ModLoader.UI.UICommon.ButtonExclamationTexture, Terraria.ModLoader.UI.UICommon.ButtonModConfigTexture, Terraria.ModLoader.UI.UICommon.ButtonModInfoTexture, Terraria.ModLoader.UI.UICommon.ButtonTranslationModTexture, Terraria.ModLoader.UI.UIModItem.CheckIfPublishedForThisBrowserVersion(), Terraria.ModLoader.Core.ModOrganizer.CheckStableBuildOnPreview(), Terraria.ModLoader.Config.ConfigManager.Configs, Terraria.Count, Terraria.ModLoader.Core.ModCompile.DeveloperMode, Terraria.GameContent.TextureAssets.Extra, Terraria.UI.UIElement.GetInnerDimensions(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.Height, Terraria.GameContent.TextureAssets.InfoIcon, Terraria.ModLoader.BuildInfo.IsDev, Terraria.ModLoader.ModLoader.IsUnloadedModStillAlive(), Terraria.GameContent.TextureAssets.Item, Terraria.UI.UIElement.Left, Terraria.ModLoader.UI.UIModItem.left2ndLine, Terraria.UI.UIElement.LeftClick(), Terraria.ModLoader.UI.UIModItem.modFromLocalModFolder, Terraria.ModLoader.UI.UIModItem.ModName, Terraria.ModLoader.Config.ConfigManager.ModNeedsReload(), Terraria.ModLoader.ModLoader.ModPath, Terraria.ModLoader.Core.ModOrganizer.modsThatUpdatedSinceLastLaunch, Terraria.ModLoader.UI.UIModItem.OpenConfig(), Terraria.Utils.OpenToURL(), Terraria.UI.StyleDimension.Pixels, Terraria.ModLoader.UI.UIModItem.previousVersionHint, Terraria.ModLoader.UI.UIModItem.QuickModDelete(), Terraria.GameContent.UI.Elements.UIText.Recalculate(), Terraria.ModLoader.UI.UIModItem.ShowMoreInfo(), Terraria.ModLoader.BuildInfo.stableVersion, Terraria.ModLoader.Logging.tML, Terraria.ModLoader.UI.UIModItem.tMLUpdateRequired, Terraria.ModLoader.BuildInfo.tMLVersion, Terraria.ModLoader.UI.UIModItem.ToggleEnabled(), Terraria.UI.UIElement.Top, Terraria.UI.CalculatedStyle.ToRectangle(), Terraria.GameContent.TextureAssets.Trash, Terraria.ModLoader.ModLoader.TryGetMod(), Terraria.ModLoader.UI.UIModItem.updatedModDot, and Terraria.UI.UIElement.Width.