TModLoader: Terraria.Social.SocialAPI.Initialize
Initialize()
static void Terraria.Social.SocialAPI.Initialize (SocialMode? mode = null) inline static
Definition at line 40 of file SocialAPI.cs.
    {
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        if (!mode.HasValue)
        {
            mode = SocialMode.None;
            if (!Main.dedServ && !SteamedWraps.FamilyShared)
            {
                if (InstallVerifier.DistributionPlatform == DistributionPlatform.Steam)
                {
                    mode = SocialMode.Steam;
                }
            }
            else if (Program.LaunchParameters.ContainsKey("-steam"))
            {
                mode = SocialMode.Steam;
            }
        }
        _mode = mode.Value;
        _modules = new List<ISocialModule>();
        JoinRequests = new ServerJoinRequestsManager();
        Main.OnTickForInternalCodeOnly += JoinRequests.Update;
        switch (Mode)
        {
        case SocialMode.Steam:
            LoadSteam();
            break;
        case SocialMode.WeGame:
            LoadWeGame();
            break;
        }
        SteamedWraps.Initialize();
        Logging.tML.Info((object)("Current 1281930 Workshop Folder Directory: " + WorkshopHelper.GetWorkshopFolder(Terraria.ModLoader.Engine.Steam.TMLAppID_t)));
    }
References Terraria.Social.SocialAPI._mode, Terraria.Social.SocialAPI._modules, Terraria.Main.dedServ, Terraria.ModLoader.Engine.InstallVerifier.DistributionPlatform, Terraria.Social.Steam.SteamedWraps.FamilyShared, Terraria.Social.Steam.WorkshopHelper.GetWorkshopFolder(), Terraria.Social.Steam.SteamedWraps.Initialize(), Terraria.Social.SocialAPI.JoinRequests, Terraria.Program.LaunchParameters, Terraria.Social.SocialAPI.LoadSteam(), Terraria.Social.SocialAPI.LoadWeGame(), Terraria.Social.SocialAPI.Mode, Terraria.ModLoader.Logging.tML, Terraria.ModLoader.Engine.Steam.TMLAppID_t, and Terraria.Social.Base.ServerJoinRequestsManager.Update().
Referenced by Terraria.Program.RunGame().