TModLoader: Terraria.Social.SocialAPI.LoadSteam
LoadSteam()
static void Terraria.Social.SocialAPI.LoadSteam () inline static package
    {
        if (_steamAPILoaded)
        {
            return;
        }
        LoadModule<Terraria.Social.Steam.CoreSocialModule>();
        Friends = LoadModule<Terraria.Social.Steam.FriendsSocialModule>();
        Cloud = LoadModule<Terraria.Social.Steam.CloudSocialModule>();
        Overlay = LoadModule<Terraria.Social.Steam.OverlaySocialModule>();
        Workshop = LoadModule<Terraria.Social.Steam.WorkshopSocialModule>();
        Platform = LoadModule<Terraria.Social.Steam.PlatformSocialModule>();
        if (Main.dedServ)
        {
            Network = LoadModule<Terraria.Social.Steam.NetServerSocialModule>();
        }
        else
        {
            Network = LoadModule<Terraria.Social.Steam.NetClientSocialModule>();
        }
        foreach (ISocialModule module in _modules)
        {
            module.Initialize();
        }
        _steamAPILoaded = true;
        Terraria.ModLoader.Engine.Steam.PostInit();
    }
References Terraria.Social.SocialAPI._modules, Terraria.Social.SocialAPI._steamAPILoaded, Terraria.Main.dedServ, Terraria.Social.SocialAPI.Friends, Terraria.Social.SocialAPI.Network, Terraria.Social.SocialAPI.Overlay, Terraria.Social.SocialAPI.Platform, Terraria.ModLoader.Engine.Steam.PostInit(), and Terraria.Social.SocialAPI.Workshop.
Referenced by Terraria.Social.SocialAPI.Initialize(), and Terraria.Social.Steam.WorkshopHelper.PublishMod().