TModLoader: Terraria.Net.NetManager.LogSend
LogSend()
void Terraria.Net.NetManager.LogSend (NetPacket packet, int toClient = -1, int ignoreClient = -1) inline private
Definition at line 163 of file NetManager.cs.
    {
        if (ModNet.DetailedLogging)
        {
            ModNet.LogSend(toClient, ignoreClient, "NetPacket " + _modules[packet.Id].GetType().Name, packet.Length);
        }
    }
References Terraria.Net.NetManager._modules, Terraria.ModLoader.ModNet.DetailedLogging, and Terraria.ModLoader.ModNet.LogSend().
Referenced by Terraria.Net.NetManager.Broadcast(), Terraria.Net.NetManager.Broadcast(), Terraria.Net.NetManager.SendToClient(), and Terraria.Net.NetManager.SendToServer().