TModLoader: Terraria.GameContent.SmartCursorHelper.Step_Hammers
Step_Hammers()
static void Terraria.GameContent.SmartCursorHelper.Step_Hammers (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
    {
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_058f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0599: Unknown result type (might be due to invalid IL or missing references)
        //IL_059e: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b3: Unknown result type (might be due to invalid IL or missing references)
        int width = providedInfo.player.width;
        int height = providedInfo.player.height;
        if (providedInfo.item.hammer > 0 && focusedX == -1 && focusedY == -1)
        {
            Vector2 vector = providedInfo.mouse - providedInfo.Center;
            int num = Math.Sign(vector.X);
            int num10 = Math.Sign(vector.Y);
            if (Math.Abs(vector.X) > Math.Abs(vector.Y) * 3f)
            {
                num10 = 0;
                providedInfo.mouse.Y = providedInfo.Center.Y;
            }
            if (Math.Abs(vector.Y) > Math.Abs(vector.X) * 3f)
            {
                num = 0;
                providedInfo.mouse.X = providedInfo.Center.X;
            }
            _ = (int)providedInfo.Center.X / 16;
            _ = (int)providedInfo.Center.Y / 16;
            _points.Clear();
            _endpoints.Clear();
            int num11 = 1;
            if (num10 == -1 && num != 0)
            {
                num11 = -1;
            }
            int num12 = (int)((providedInfo.position.X + (float)(width / 2) + (float)((width / 2 - 1) * num)) / 16f);
            int num13 = (int)(((double)providedInfo.position.Y + 0.1) / 16.0);
            if (num11 == -1)
            {
                num13 = (int)((providedInfo.position.Y + (float)height - 1f) / 16f);
            }
            int num14 = width / 16 + ((width % 16 != 0) ? 1 : 0);
            int num15 = height / 16 + ((height % 16 != 0) ? 1 : 0);
            if (num != 0)
            {
                for (int i = 0; i < num15; i++)
                {
                    if (Main.tile[num12, num13 + i * num11] != null)
                    {
                        _points.Add(new Tuple<int, int>(num12, num13 + i * num11));
                    }
                }
            }
            if (num10 != 0)
            {
                for (int j = 0; j < num14; j++)
                {
                    if (Main.tile[(int)(providedInfo.position.X / 16f) + j, num13] != null)
                    {
                        _points.Add(new Tuple<int, int>((int)(providedInfo.position.X / 16f) + j, num13));
                    }
                }
            }
            int num16 = (int)((providedInfo.mouse.X + (float)((width / 2 - 1) * num)) / 16f);
            int num17 = (int)(((double)providedInfo.mouse.Y + 0.1 - (double)(height / 2 + 1)) / 16.0);
            if (num11 == -1)
            {
                num17 = (int)((providedInfo.mouse.Y + (float)(height / 2) - 1f) / 16f);
            }
            if (providedInfo.player.gravDir == -1f && num10 == 0)
            {
                num17++;
            }
            if (num17 < 10)
            {
                num17 = 10;
            }
            if (num17 > Main.maxTilesY - 10)
            {
                num17 = Main.maxTilesY - 10;
            }
            int num2 = width / 16 + ((width % 16 != 0) ? 1 : 0);
            int num3 = height / 16 + ((height % 16 != 0) ? 1 : 0);
            if (num != 0)
            {
                for (int k = 0; k < num3; k++)
                {
                    if (Main.tile[num16, num17 + k * num11] != null)
                    {
                        _endpoints.Add(new Tuple<int, int>(num16, num17 + k * num11));
                    }
                }
            }
            if (num10 != 0)
            {
                for (int l = 0; l < num2; l++)
                {
                    if (Main.tile[(int)((providedInfo.mouse.X - (float)(width / 2)) / 16f) + l, num17] != null)
                    {
                        _endpoints.Add(new Tuple<int, int>((int)((providedInfo.mouse.X - (float)(width / 2)) / 16f) + l, num17));
                    }
                }
            }
            _targets.Clear();
            while (_points.Count > 0)
            {
                Tuple<int, int> tuple = _points[0];
                Tuple<int, int> tuple2 = _endpoints[0];
                Tuple<int, int> tuple3 = Collision.TupleHitLineWall(tuple.Item1, tuple.Item2, tuple2.Item1, tuple2.Item2);
                if (tuple3.Item1 == -1 || tuple3.Item2 == -1)
                {
                    _points.Remove(tuple);
                    _endpoints.Remove(tuple2);
                    continue;
                }
                if (tuple3.Item1 != tuple2.Item1 || tuple3.Item2 != tuple2.Item2)
                {
                    _targets.Add(tuple3);
                }
                _ = Main.tile[tuple3.Item1, tuple3.Item2];
                if (Collision.HitWallSubstep(tuple3.Item1, tuple3.Item2))
                {
                    _targets.Add(tuple3);
                }
                _points.Remove(tuple);
                _endpoints.Remove(tuple2);
            }
            if (_targets.Count > 0)
            {
                float num4 = -1f;
                Tuple<int, int> tuple4 = null;
                for (int m = 0; m < _targets.Count; m++)
                {
                    if (!Main.tile[_targets[m].Item1, _targets[m].Item2].active() || Main.tile[_targets[m].Item1, _targets[m].Item2].type != 26)
                    {
                        float num5 = Vector2.Distance(new Vector2((float)_targets[m].Item1, (float)_targets[m].Item2) * 16f + Vector2.One * 8f, providedInfo.Center);
                        if (num4 == -1f || num5 < num4)
{
                            num4 = num5;
                            tuple4 = _targets[m];
                        }
                    }
                }
                if (tuple4 != null && Collision.InTileBounds(tuple4.Item1, tuple4.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
                {
                    providedInfo.player.poundRelease = false;
                    focusedX = tuple4.Item1;
                    focusedY = tuple4.Item2;
                }
            }
            _targets.Clear();
            _points.Clear();
            _endpoints.Clear();
        }
        if (providedInfo.item.hammer <= 0 || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        _targets.Clear();
        for (int n = providedInfo.reachableStartX; n <= providedInfo.reachableEndX; n++)
        {
            for (int num6 = providedInfo.reachableStartY; num6 <= providedInfo.reachableEndY; num6++)
            {
                if (Main.tile[n, num6].wall > 0 && Collision.HitWallSubstep(n, num6))
                {
                    _targets.Add(new Tuple<int, int>(n, num6));
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num7 = -1f;
            Tuple<int, int> tuple5 = null;
            for (int num8 = 0; num8 < _targets.Count; num8++)
            {
                if (!Main.tile[_targets[num8].Item1, _targets[num8].Item2].active() || Main.tile[_targets[num8].Item1, _targets[num8].Item2].type != 26)
                {
                    float num9 = Vector2.Distance(new Vector2((float)_targets[num8].Item1, (float)_targets[num8].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                    if (num7 == -1f || num9 < num7)
                    {
                        num7 = num9;
                        tuple5 = _targets[num8];
                    }
                }
            }
            if (tuple5 != null && Collision.InTileBounds(tuple5.Item1, tuple5.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
            {
                providedInfo.player.poundRelease = false;
                focusedX = tuple5.Item1;
                focusedY = tuple5.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._endpoints, Terraria.GameContent.SmartCursorHelper._points, Terraria.GameContent.SmartCursorHelper._targets, Terraria.Collision.HitWallSubstep(), Terraria.Collision.InTileBounds(), Terraria.Main.maxTilesY, Terraria.Main.tile, and Terraria.Collision.TupleHitLineWall().
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().