TModLoader: Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids
Step_Pickaxe_MineSolids()
static void Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids (Player player, SmartCursorUsageInfo providedInfo, List< Tuple< int, int > > grappleTargets, ref int focusedX, ref int focusedY) inline static private
Definition at line 2450 of file SmartCursorHelper.cs.
    {
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0630: Unknown result type (might be due to invalid IL or missing references)
        //IL_0631: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0805: Unknown result type (might be due to invalid IL or missing references)
        //IL_080a: Unknown result type (might be due to invalid IL or missing references)
        //IL_080f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0687: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06be: Unknown result type (might be due to invalid IL or missing references)
        //IL_0726: Unknown result type (might be due to invalid IL or missing references)
        int width = player.width;
        int height = player.height;
        int direction = player.direction;
        Vector2 center = player.Center;
        Vector2 position = player.position;
        float gravDir = player.gravDir;
        int whoAmI = player.whoAmI;
        if (providedInfo.item.pick <= 0 || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        if (PlayerInput.UsingGamepad)
        {
            Vector2 navigatorDirections = PlayerInput.Triggers.Current.GetNavigatorDirections();
            Vector2 gamepadThumbstickLeft = PlayerInput.GamepadThumbstickLeft;
            Vector2 gamepadThumbstickRight = PlayerInput.GamepadThumbstickRight;
            if (navigatorDirections == Vector2.Zero && ((Vector2)(ref gamepadThumbstickLeft)).Length() < 0.05f && ((Vector2)(ref gamepadThumbstickRight)).Length() < 0.05f)
            {
                providedInfo.mouse = center + new Vector2((float)(direction * 1000), 0f);
            }
        }
        Vector2 vector = providedInfo.mouse - center;
        int num = Math.Sign(vector.X);
        int num12 = Math.Sign(vector.Y);
        if (Math.Abs(vector.X) > Math.Abs(vector.Y) * 3f)
        {
            num12 = 0;
            providedInfo.mouse.Y = center.Y;
        }
        if (Math.Abs(vector.Y) > Math.Abs(vector.X) * 3f)
        {
            num = 0;
            providedInfo.mouse.X = center.X;
        }
        _ = (int)center.X / 16;
        _ = (int)center.Y / 16;
        _points.Clear();
        _endpoints.Clear();
        int num13 = 1;
        if (num12 == -1 && num != 0)
        {
            num13 = -1;
        }
        int num14 = (int)((position.X + (float)(width / 2) + (float)((width / 2 - 1) * num)) / 16f);
        int num15 = (int)(((double)position.Y + 0.1) / 16.0);
        if (num13 == -1)
        {
            num15 = (int)((position.Y + (float)height - 1f) / 16f);
        }
        int num16 = width / 16 + ((width % 16 != 0) ? 1 : 0);
        int num17 = height / 16 + ((height % 16 != 0) ? 1 : 0);
        if (num != 0)
        {
            for (int i = 0; i < num17; i++)
            {
                if (Main.tile[num14, num15 + i * num13] != null)
                {
                    _points.Add(new Tuple<int, int>(num14, num15 + i * num13));
                }
            }
        }
        if (num12 != 0)
        {
            for (int j = 0; j < num16; j++)
            {
                if (Main.tile[(int)(position.X / 16f) + j, num15] != null)
                {
                    _points.Add(new Tuple<int, int>((int)(position.X / 16f) + j, num15));
                }
            }
        }
        int num18 = (int)((providedInfo.mouse.X + (float)((width / 2 - 1) * num)) / 16f);
        int num19 = (int)(((double)providedInfo.mouse.Y + 0.1 - (double)(height / 2 + 1)) / 16.0);
        if (num13 == -1)
        {
            num19 = (int)((providedInfo.mouse.Y + (float)(height / 2) - 1f) / 16f);
        }
        if (gravDir == -1f && num12 == 0)
        {
            num19++;
        }
        if (num19 < 10)
        {
            num19 = 10;
        }
        if (num19 > Main.maxTilesY - 10)
        {
            num19 = Main.maxTilesY - 10;
        }
        int num2 = width / 16 + ((width % 16 != 0) ? 1 : 0);
        int num3 = height / 16 + ((height % 16 != 0) ? 1 : 0);
        if (WorldGen.InWorld(num18, num19, 40))
        {
            if (num != 0)
            {
                for (int k = 0; k < num3; k++)
                {
                    if (Main.tile[num18, num19 + k * num13] != null)
                    {
                        _endpoints.Add(new Tuple<int, int>(num18, num19 + k * num13));
                    }
                }
            }
            if (num12 != 0)
            {
                for (int l = 0; l < num2; l++)
                {
                    if (Main.tile[(int)((providedInfo.mouse.X - (float)(width / 2)) / 16f) + l, num19] != null)
                    {
                        _endpoints.Add(new Tuple<int, int>((int)((providedInfo.mouse.X - (float)(width / 2)) / 16f) + l, num19));
                    }
                }
            }
        }
        _targets.Clear();
        while (_points.Count > 0 && _endpoints.Count > 0)
        {
            Tuple<int, int> tuple = _points[0];
            Tuple<int, int> tuple2 = _endpoints[0];
            if (!Collision.TupleHitLine(tuple.Item1, tuple.Item2, tuple2.Item1, tuple2.Item2, num * (int)gravDir, -num12 * (int)gravDir, grappleTargets, out var col))
            {
                _points.Remove(tuple);
                _endpoints.Remove(tuple2);
                continue;
            }
            if (col.Item1 != tuple2.Item1 || col.Item2 != tuple2.Item2)
            {
                _targets.Add(col);
            }
            Tile tile = Main.tile[col.Item1, col.Item2];
            if (!tile.inActive() && tile.active() && Main.tileSolid[tile.type] && !Main.tileSolidTop[tile.type] && !grappleTargets.Contains(col))
            {
                _targets.Add(col);
            }
            _points.Remove(tuple);
            _endpoints.Remove(tuple2);
        }
        _toRemove.Clear();
        for (int m = 0; m < _targets.Count; m++)
        {
            if (!WorldGen.CanKillTile(_targets[m].Item1, _targets[m].Item2))
            {
                _toRemove.Add(_targets[m]);
            }
        }
        for (int n = 0; n < _toRemove.Count; n++)
        {
            _targets.Remove(_toRemove[n]);
        }
        _toRemove.Clear();
        if (_targets.Count > 0)
        {
            float num4 = -1f;
            Tuple<int, int> tuple3 = _targets[0];
            Vector2 value = center;
            if (Main.netMode == 1)
            {
                int num5 = 0;
                int num6 = 0;
                int num7 = 0;
                for (int num8 = 0; num8 < whoAmI; num8++)
                {
                    Player player2 = Main.player[num8];
                    if (player2.active && !player2.dead && player2.HeldItem.pick > 0 && player2.itemAnimation > 0)
                    {
                        if (player.Distance(player2.Center) <= 8f)
{
                            num5++;
                        }
                        if (player.Distance(player2.Center) <= 80f && Math.Abs(player2.Center.Y - center.Y) <= 12f)
{
                            num6++;
                        }
                    }
                }
                for (int num9 = whoAmI + 1; num9 < 255; num9++)
                {
                    Player player3 = Main.player[num9];
                    if (player3.active && !player3.dead && player3.HeldItem.pick > 0 && player3.itemAnimation > 0 && player.Distance(player3.Center) <= 8f)
                    {
                        num7++;
                    }
                }
                if (num5 > 0)
                {
                    if (num5 % 2 == 1)
                    {
                        value.X += 12f;
                    }
                    else
                    {
                        value.X -= 12f;
                    }
                    if (num6 % 2 == 1)
                    {
                        value.Y -= 12f;
                    }
                }
                if (num7 > 0 && num5 == 0)
                {
                    if (num7 % 2 == 1)
                    {
                        value.X -= 12f;
                    }
                    else
                    {
                        value.X += 12f;
                    }
                }
            }
            for (int num10 = 0; num10 < _targets.Count; num10++)
            {
                float num11 = Vector2.Distance(new Vector2((float)_targets[num10].Item1, (float)_targets[num10].Item2) * 16f + Vector2.One * 8f, value);
                if (num4 == -1f || num11 < num4)
                {
                    num4 = num11;
                    tuple3 = _targets[num10];
                }
            }
            if (Collision.InTileBounds(tuple3.Item1, tuple3.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
            {
                focusedX = tuple3.Item1;
                focusedY = tuple3.Item2;
            }
        }
        _points.Clear();
        _endpoints.Clear();
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._endpoints, Terraria.GameContent.SmartCursorHelper._points, Terraria.GameContent.SmartCursorHelper._targets, Terraria.GameContent.SmartCursorHelper._toRemove, Terraria.Tile.active(), Terraria.WorldGen.CanKillTile(), Terraria.Entity.Center, Terraria.GameInput.TriggersPack.Current, Terraria.Entity.direction, Terraria.Entity.Distance(), Terraria.GameInput.PlayerInput.GamepadThumbstickLeft, Terraria.GameInput.PlayerInput.GamepadThumbstickRight, Terraria.GameInput.TriggersSet.GetNavigatorDirections(), Terraria.Player.gravDir, Terraria.Entity.height, Terraria.Tile.inActive(), Terraria.Collision.InTileBounds(), Terraria.WorldGen.InWorld(), Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.GameInput.PlayerInput.Triggers, Terraria.Collision.TupleHitLine(), Terraria.Tile.type, Terraria.GameInput.PlayerInput.UsingGamepad, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().