TModLoader: Terraria.GameContent.SmartCursorHelper.Step_MinecartTracks
Step_MinecartTracks()
static void Terraria.GameContent.SmartCursorHelper.Step_MinecartTracks (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 1200 of file SmartCursorHelper.cs.
    {
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0afc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b06: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b11: Unknown result type (might be due to invalid IL or missing references)
        //IL_0721: Unknown result type (might be due to invalid IL or missing references)
        //IL_072b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0730: Unknown result type (might be due to invalid IL or missing references)
        //IL_073a: Unknown result type (might be due to invalid IL or missing references)
        //IL_073f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0745: Unknown result type (might be due to invalid IL or missing references)
        if ((providedInfo.item.type == 2340 || providedInfo.item.type == 2739) && focusedX == -1 && focusedY == -1)
        {
            _targets.Clear();
            Vector2 val = (Main.MouseWorld - providedInfo.Center).SafeNormalize(Vector2.UnitY);
            float num7 = Vector2.Dot(val, -Vector2.UnitY);
            bool flag = num7 >= 0.5f;
            bool flag7 = num7 <= -0.5f;
            float num8 = Vector2.Dot(val, Vector2.UnitX);
            bool flag8 = num8 >= 0.5f;
            bool flag9 = num8 <= -0.5f;
            bool flag10 = flag && flag9;
            bool flag11 = flag && flag8;
            bool flag12 = flag7 && flag9;
            bool flag13 = flag7 && flag8;
            if (flag10)
            {
                flag9 = false;
            }
            if (flag11)
            {
                flag8 = false;
            }
            if (flag12)
            {
                flag9 = false;
            }
            if (flag13)
            {
                flag8 = false;
            }
            bool flag14 = false;
            if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].active() && Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].type == 314)
            {
                flag14 = true;
            }
            if (!flag14)
            {
                for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
                {
                    for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                    {
                        Tile tile = Main.tile[i, j];
                        if (tile.active() && tile.type == 314)
{
                            bool flag2 = Main.tile[i + 1, j + 1].active() && Main.tile[i + 1, j + 1].type == 314;
                            bool flag3 = Main.tile[i + 1, j - 1].active() && Main.tile[i + 1, j - 1].type == 314;
                            bool flag4 = Main.tile[i - 1, j + 1].active() && Main.tile[i - 1, j + 1].type == 314;
                            bool flag5 = Main.tile[i - 1, j - 1].active() && Main.tile[i - 1, j - 1].type == 314;
                            if (flag10 && (!Main.tile[i - 1, j - 1].active() || Main.tileCut[Main.tile[i - 1, j - 1].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[i - 1, j - 1].type]) && !(!flag2 && flag3) && !flag4)
{
                                _targets.Add(new Tuple<int, int>(i - 1, j - 1));
                            }
                            if (flag9 && (!Main.tile[i - 1, j].active() || Main.tileCut[Main.tile[i - 1, j].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[i - 1, j].type]))
{
                                _targets.Add(new Tuple<int, int>(i - 1, j));
                            }
                            if (flag12 && (!Main.tile[i - 1, j + 1].active() || Main.tileCut[Main.tile[i - 1, j + 1].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[i - 1, j + 1].type]) && !(!flag3 && flag2) && !flag5)
{
                                _targets.Add(new Tuple<int, int>(i - 1, j + 1));
                            }
                            if (flag11 && (!Main.tile[i + 1, j - 1].active() || Main.tileCut[Main.tile[i + 1, j - 1].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[i + 1, j - 1].type]) && !(!flag4 && flag5) && !flag2)
{
                                _targets.Add(new Tuple<int, int>(i + 1, j - 1));
                            }
                            if (flag8 && (!Main.tile[i + 1, j].active() || Main.tileCut[Main.tile[i + 1, j].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[i + 1, j].type]))
{
                                _targets.Add(new Tuple<int, int>(i + 1, j));
                            }
                            if (flag13 && (!Main.tile[i + 1, j + 1].active() || Main.tileCut[Main.tile[i + 1, j + 1].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[i + 1, j + 1].type]) && !(!flag5 && flag4) && !flag3)
{
                                _targets.Add(new Tuple<int, int>(i + 1, j + 1));
                            }
                        }
                    }
                }
            }
            if (_targets.Count > 0)
            {
                float num3 = -1f;
                Tuple<int, int> tuple = _targets[0];
                for (int k = 0; k < _targets.Count; k++)
                {
                    if ((!Main.tile[_targets[k].Item1, _targets[k].Item2 - 1].active() || Main.tile[_targets[k].Item1, _targets[k].Item2 - 1].type != 314) && (!Main.tile[_targets[k].Item1, _targets[k].Item2 + 1].active() || Main.tile[_targets[k].Item1, _targets[k].Item2 + 1].type != 314))
                    {
                        float num4 = Vector2.Distance(new Vector2((float)_targets[k].Item1, (float)_targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                        if (num3 == -1f || num4 < num3)
{
                            num3 = num4;
                            tuple = _targets[k];
                        }
                    }
                }
                if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY) && num3 != -1f)
                {
                    focusedX = tuple.Item1;
                    focusedY = tuple.Item2;
                }
            }
            _targets.Clear();
        }
        if (providedInfo.item.type != 2492 || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        _targets.Clear();
        bool flag6 = false;
        if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].active() && Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].type == 314)
        {
            flag6 = true;
        }
        if (!flag6)
        {
            for (int l = providedInfo.reachableStartX; l <= providedInfo.reachableEndX; l++)
            {
                for (int m = providedInfo.reachableStartY; m <= providedInfo.reachableEndY; m++)
                {
                    Tile tile2 = Main.tile[l, m];
                    if (tile2.active() && tile2.type == 314)
                    {
                        if (!Main.tile[l - 1, m].active() || Main.tileCut[Main.tile[l - 1, m].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[l - 1, m].type])
{
                            _targets.Add(new Tuple<int, int>(l - 1, m));
                        }
                        if (!Main.tile[l + 1, m].active() || Main.tileCut[Main.tile[l + 1, m].type] || TileID.Sets.BreakableWhenPlacing[Main.tile[l + 1, m].type])
{
                            _targets.Add(new Tuple<int, int>(l + 1, m));
                        }
                    }
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num5 = -1f;
            Tuple<int, int> tuple2 = _targets[0];
            for (int n = 0; n < _targets.Count; n++)
            {
                if ((!Main.tile[_targets[n].Item1, _targets[n].Item2 - 1].active() || Main.tile[_targets[n].Item1, _targets[n].Item2 - 1].type != 314) && (!Main.tile[_targets[n].Item1, _targets[n].Item2 + 1].active() || Main.tile[_targets[n].Item1, _targets[n].Item2 + 1].type != 314))
                {
                    float num6 = Vector2.Distance(new Vector2((float)_targets[n].Item1, (float)_targets[n].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                    if (num5 == -1f || num6 < num5)
                    {
                        num5 = num6;
                        tuple2 = _targets[n];
                    }
                }
            }
            if (Collision.InTileBounds(tuple2.Item1, tuple2.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY) && num5 != -1f)
            {
                focusedX = tuple2.Item1;
                focusedY = tuple2.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.Collision.InTileBounds(), Terraria.Main.tile, and Terraria.Main.tileCut.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().