TModLoader: Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling
Step_BlocksFilling()
static void Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling (SmartCursorUsageInfo providedInfo, ref int fX, ref int fY) inline static private
    {
        //IL_0397: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ca: Unknown result type (might be due to invalid IL or missing references)
        if (!Player.SmartCursorSettings.SmartBlocksEnabled)
        {
            return;
        }
        int type = providedInfo.item.type;
        if (type < 0)
        {
            return;
        }
        int reachableStartX = providedInfo.reachableStartX;
        int reachableStartY = providedInfo.reachableStartY;
        int reachableEndX = providedInfo.reachableEndX;
        int reachableEndY = providedInfo.reachableEndY;
        int screenTargetX = providedInfo.screenTargetX;
        int screenTargetY = providedInfo.screenTargetY;
        if (Player.SmartCursorSettings.SmartBlocksEnabled || providedInfo.item.createTile <= -1 || type == 213 || type == 5295 || ItemID.Sets.GrassSeeds[type] || !Main.tileSolid[providedInfo.item.createTile] || Main.tileSolidTop[providedInfo.item.createTile] || Main.tileFrameImportant[providedInfo.item.createTile] || fX != -1 || fY != -1)
        {
            return;
        }
        _targets.Clear();
        bool flag = false;
        if (Main.tile[screenTargetX, screenTargetY].active())
        {
            flag = true;
        }
        if (!Collision.InTileBounds(screenTargetX, screenTargetY, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
        {
            flag = true;
        }
        if (!flag)
        {
            for (int i = reachableStartX; i <= reachableEndX; i++)
            {
                for (int j = reachableStartY; j <= reachableEndY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (!tile.active() || Main.tileCut[tile.type] || TileID.Sets.BreakableWhenPlacing[tile.type])
                    {
                        int num = 0;
                        if (Main.tile[i - 1, j].active() && Main.tileSolid[Main.tile[i - 1, j].type] && !Main.tileSolidTop[Main.tile[i - 1, j].type])
{
                            num++;
                        }
                        if (Main.tile[i + 1, j].active() && Main.tileSolid[Main.tile[i + 1, j].type] && !Main.tileSolidTop[Main.tile[i + 1, j].type])
{
                            num++;
                        }
                        if (Main.tile[i, j - 1].active() && Main.tileSolid[Main.tile[i, j - 1].type] && !Main.tileSolidTop[Main.tile[i, j - 1].type])
{
                            num++;
                        }
                        if (Main.tile[i, j + 1].active() && Main.tileSolid[Main.tile[i, j + 1].type] && !Main.tileSolidTop[Main.tile[i, j + 1].type])
{
                            num++;
                        }
                        if (num >= 2)
{
                            _targets.Add(new Tuple<int, int>(i, j));
                        }
                    }
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num2 = -1f;
            float num3 = float.PositiveInfinity;
            Tuple<int, int> tuple = _targets[0];
            for (int k = 0; k < _targets.Count; k++)
            {
                if (Collision.EmptyTile(_targets[k].Item1, _targets[k].Item2, ignoreTiles: true))
                {
                    Vector2 vector = new Vector2((float)_targets[k].Item1, (float)_targets[k].Item2) * 16f + Vector2.One * 8f - providedInfo.mouse;
                    bool flag2 = false;
                    float num4 = Math.Abs(vector.X);
                    float num5 = ((Vector2)(ref vector)).Length();
                    if (num4 < num3)
                    {
                        flag2 = true;
                    }
                    if (num4 == num3 && (num2 == -1f || num5 < num2))
                    {
                        flag2 = true;
                    }
                    if (flag2)
                    {
                        num2 = num5;
                        num3 = num4;
                        tuple = _targets[k];
                    }
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, reachableStartX, reachableStartY, reachableEndX, reachableEndY) && num2 != -1f)
            {
                fX = tuple.Item1;
                fY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.Collision.EmptyTile(), Terraria.ID.ItemID.Sets.GrassSeeds, Terraria.Collision.InTileBounds(), Terraria.Player.SmartCursorSettings.SmartBlocksEnabled, Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Main.tileFrameImportant, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().