TModLoader: Terraria.GameContent.SmartCursorHelper.Step_Walls
Step_Walls()
static void Terraria.GameContent.SmartCursorHelper.Step_Walls (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 1125 of file SmartCursorHelper.cs.
    {
        //IL_023c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0246: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0255: Unknown result type (might be due to invalid IL or missing references)
        //IL_025a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        int width = providedInfo.player.width;
        int height = providedInfo.player.height;
        if (providedInfo.item.createWall <= 0 || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        _targets.Clear();
        for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
        {
            for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile.wall == 0 && (!tile.active() || !Main.tileSolid[tile.type] || Main.tileSolidTop[tile.type]) && Collision.CanHitWithCheck(providedInfo.position, width, height, new Vector2((float)i, (float)j) * 16f, 16, 16, DelegateMethods.NotDoorStand))
                {
                    bool flag = false;
                    if (Main.tile[i - 1, j].active() || Main.tile[i - 1, j].wall > 0)
                    {
                        flag = true;
                    }
                    if (Main.tile[i + 1, j].active() || Main.tile[i + 1, j].wall > 0)
                    {
                        flag = true;
                    }
                    if (Main.tile[i, j - 1].active() || Main.tile[i, j - 1].wall > 0)
                    {
                        flag = true;
                    }
                    if (Main.tile[i, j + 1].active() || Main.tile[i, j + 1].wall > 0)
                    {
                        flag = true;
                    }
                    if (WorldGen.IsOpenDoorAnchorFrame(i, j))
                    {
                        flag = false;
                    }
                    if (flag)
                    {
                        _targets.Add(new Tuple<int, int>(i, j));
                    }
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int k = 0; k < _targets.Count; k++)
            {
                float num2 = Vector2.Distance(new Vector2((float)_targets[k].Item1, (float)_targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num == -1f || num2 < num)
                {
                    num = num2;
                    tuple = _targets[k];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), Terraria.Collision.CanHitWithCheck(), Terraria.Collision.InTileBounds(), Terraria.WorldGen.IsOpenDoorAnchorFrame(), Terraria.DelegateMethods.NotDoorStand(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().