TModLoader: Terraria.GameContent.SmartCursorHelper.Step_Boulders
Step_Boulders()
static void Terraria.GameContent.SmartCursorHelper.Step_Boulders (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 885 of file SmartCursorHelper.cs.
    {
        //IL_0256: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_027a: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b7: Unknown result type (might be due to invalid IL or missing references)
        if (providedInfo.item.createTile <= -1 || !TileID.Sets.Boulders[providedInfo.item.createTile] || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        _targets.Clear();
        Rectangle value = default(Rectangle);
        for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
        {
            for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
            {
                Tile tile = Main.tile[i, j + 1];
                Tile tile2 = Main.tile[i + 1, j + 1];
                bool flag = true;
                if (!tile2.nactive() || !tile.nactive())
                {
                    flag = false;
                }
                if (tile2.slope() > 0 || tile.slope() > 0 || tile2.halfBrick() || tile.halfBrick())
                {
                    flag = false;
                }
                if ((!Main.tileSolid[tile2.type] && !Main.tileTable[tile2.type]) || (!Main.tileSolid[tile.type] && !Main.tileTable[tile.type]))
                {
                    flag = false;
                }
                if (Main.tileNoAttach[tile2.type] || Main.tileNoAttach[tile.type])
                {
                    flag = false;
                }
                for (int k = i; k <= i + 1; k++)
                {
                    for (int l = j - 1; l <= j; l++)
                    {
                        Tile tile3 = Main.tile[k, l];
                        if (tile3.active() && !Main.tileCut[tile3.type])
{
                            flag = false;
                        }
                    }
                }
                int x = i * 16;
                int y = j * 16 - 16;
                int width = 32;
                int height = 32;
                ((Rectangle)(ref value))._002Ector(x, y, width, height);
                for (int m = 0; m < 255; m++)
                {
                    Player player = Main.player[m];
                    if (player.active && !player.dead)
                    {
                        Rectangle hitbox = player.Hitbox;
                        if (((Rectangle)(ref hitbox)).Intersects(value))
{
                            flag = false;
                            break;
                        }
                    }
                }
                if (flag)
                {
                    _targets.Add(new Tuple<int, int>(i, j));
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int n = 0; n < _targets.Count; n++)
            {
                float num2 = Vector2.Distance(new Vector2((float)_targets[n].Item1, (float)_targets[n].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num == -1f || num2 < num)
                {
                    num = num2;
                    tuple = _targets[n];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Entity.active, Terraria.ID.TileID.Sets.Boulders, Terraria.Player.dead, Terraria.Tile.halfBrick(), Terraria.Entity.Hitbox, Terraria.Collision.InTileBounds(), Terraria.Tile.nactive(), Terraria.Main.player, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Main.tileNoAttach, Terraria.Main.tileSolid, Terraria.Main.tileTable, and Terraria.Tile.type.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().