TModLoader: Terraria.GameContent.SmartCursorHelper.Step_GrassSeeds
Step_GrassSeeds()
static void Terraria.GameContent.SmartCursorHelper.Step_GrassSeeds (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
Definition at line 243 of file SmartCursorHelper.cs.
    {
        //IL_024a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0254: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_0268: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        if (focusedX > -1 || focusedY > -1)
        {
            return;
        }
        int type = providedInfo.item.type;
        if (type < 0 || !ItemID.Sets.GrassSeeds[type])
        {
            return;
        }
        _targets.Clear();
        for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
        {
            for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
            {
                Tile tile = Main.tile[i, j];
                bool flag = !Main.tile[i - 1, j].active() || !Main.tile[i, j + 1].active() || !Main.tile[i + 1, j].active() || !Main.tile[i, j - 1].active();
                bool flag2 = !Main.tile[i - 1, j - 1].active() || !Main.tile[i - 1, j + 1].active() || !Main.tile[i + 1, j + 1].active() || !Main.tile[i + 1, j - 1].active();
                if (tile.active() && !tile.inActive() && (flag || flag2))
                {
                    bool flag3 = false;
                    switch (type)
                    {
                    default:
                        flag3 = tile.type == 0;
                        break;
                    case 59:
                    case 2171:
                        flag3 = tile.type == 0 || tile.type == 59;
                        break;
                    case 194:
                    case 195:
                        flag3 = tile.type == 59;
                        break;
                    case 5214:
                        flag3 = tile.type == 57;
                        break;
                    }
                    if (flag3)
                    {
                        _targets.Add(new Tuple<int, int>(i, j));
                    }
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int k = 0; k < _targets.Count; k++)
            {
                float num2 = Vector2.Distance(new Vector2((float)_targets[k].Item1, (float)_targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num == -1f || num2 < num)
                {
                    num = num2;
                    tuple = _targets[k];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), Terraria.ID.ItemID.Sets.GrassSeeds, Terraria.Tile.inActive(), Terraria.Collision.InTileBounds(), and Terraria.Main.tile.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().