TModLoader: Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineShinies
Step_Pickaxe_MineShinies()
static void Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineShinies (SmartCursorUsageInfo providedInfo, ref int fX, ref int fY) inline static private
Definition at line 2364 of file SmartCursorHelper.cs.
    {
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        //IL_0233: Unknown result type (might be due to invalid IL or missing references)
        //IL_0238: Unknown result type (might be due to invalid IL or missing references)
        //IL_0242: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        int reachableStartX = providedInfo.reachableStartX;
        int reachableStartY = providedInfo.reachableStartY;
        int reachableEndX = providedInfo.reachableEndX;
        int reachableEndY = providedInfo.reachableEndY;
        _ = providedInfo.screenTargetX;
        _ = providedInfo.screenTargetY;
        Item item = providedInfo.item;
        Vector2 mouse = providedInfo.mouse;
        if (item.pick <= 0 || fX != -1 || fY != -1)
        {
            return;
        }
        _targets.Clear();
        if (item.type != 1333 && item.type != 523)
        {
            _ = item.type;
        }
        int num = 0;
        for (int i = reachableStartX; i <= reachableEndX; i++)
        {
            for (int j = reachableStartY; j <= reachableEndY; j++)
            {
                Tile tile = Main.tile[i, j];
                _ = Main.tile[i - 1, j];
                _ = Main.tile[i + 1, j];
                _ = Main.tile[i, j + 1];
                if (!tile.active())
                {
                    continue;
                }
                int num2 = (num2 = TileID.Sets.SmartCursorPickaxePriorityOverride[tile.type]);
                if (num2 > 0)
                {
                    if (num < num2)
                    {
                        num = num2;
                    }
                    _targets.Add(new Tuple<int, int>(i, j));
                }
            }
        }
        _targets2.Clear();
        foreach (Tuple<int, int> item2 in _targets2)
        {
            Tile tile2 = Main.tile[item2.Item1, item2.Item2];
            if (TileID.Sets.SmartCursorPickaxePriorityOverride[tile2.type] < num)
            {
                _targets2.Add(item2);
            }
        }
        foreach (Tuple<int, int> item3 in _targets2)
        {
            _targets.Remove(item3);
        }
        if (_targets.Count > 0)
        {
            float num3 = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int k = 0; k < _targets.Count; k++)
            {
                float num4 = Vector2.Distance(new Vector2((float)_targets[k].Item1, (float)_targets[k].Item2) * 16f + Vector2.One * 8f, mouse);
                if (num3 == -1f || num4 < num3)
                {
                    num3 = num4;
                    tuple = _targets[k];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
            {
                fX = tuple.Item1;
                fY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.GameContent.SmartCursorHelper._targets2, Terraria.Tile.active(), Terraria.Collision.InTileBounds(), Terraria.Item.pick, Terraria.ID.TileID.Sets.SmartCursorPickaxePriorityOverride, Terraria.Main.tile, Terraria.Item.type, and Terraria.Tile.type.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().