TModLoader: Terraria.GameContent.SmartCursorHelper.Step_Platforms
Step_Platforms()
static void Terraria.GameContent.SmartCursorHelper.Step_Platforms (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
    {
        //IL_036f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_037e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0388: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0393: Unknown result type (might be due to invalid IL or missing references)
        if (providedInfo.item.createTile < 0 || !TileID.Sets.Platforms[providedInfo.item.createTile] || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        _targets.Clear();
        bool flag = false;
        if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].active() && TileID.Sets.Platforms[Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].type])
        {
            flag = true;
        }
        if (!flag)
        {
            for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
            {
                for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile.active() && TileID.Sets.Platforms[tile.type])
                    {
                        byte num6 = tile.slope();
                        if (num6 != 2 && !Main.tile[i - 1, j - 1].active())
{
                            _targets.Add(new Tuple<int, int>(i - 1, j - 1));
                        }
                        if (!Main.tile[i - 1, j].active())
{
                            _targets.Add(new Tuple<int, int>(i - 1, j));
                        }
                        if (num6 != 1 && !Main.tile[i - 1, j + 1].active())
{
                            _targets.Add(new Tuple<int, int>(i - 1, j + 1));
                        }
                        if (num6 != 1 && !Main.tile[i + 1, j - 1].active())
{
                            _targets.Add(new Tuple<int, int>(i + 1, j - 1));
                        }
                        if (!Main.tile[i + 1, j].active())
{
                            _targets.Add(new Tuple<int, int>(i + 1, j));
                        }
                        if (num6 != 2 && !Main.tile[i + 1, j + 1].active())
{
                            _targets.Add(new Tuple<int, int>(i + 1, j + 1));
                        }
                    }
                    if (!tile.active())
                    {
                        int num2 = 0;
                        int num3 = 0;
                        num2 = 0;
                        num3 = 1;
                        Tile tile2 = Main.tile[i + num2, j + num3];
                        if (tile2.active() && Main.tileSolid[tile2.type] && !Main.tileSolidTop[tile2.type])
{
                            _targets.Add(new Tuple<int, int>(i, j));
                        }
                        num2 = -1;
                        num3 = 0;
                        tile2 = Main.tile[i + num2, j + num3];
                        if (tile2.active() && Main.tileSolid[tile2.type] && !Main.tileSolidTop[tile2.type])
{
                            _targets.Add(new Tuple<int, int>(i, j));
                        }
                        num2 = 1;
                        num3 = 0;
                        tile2 = Main.tile[i + num2, j + num3];
                        if (tile2.active() && Main.tileSolid[tile2.type] && !Main.tileSolidTop[tile2.type])
{
                            _targets.Add(new Tuple<int, int>(i, j));
                        }
                    }
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num4 = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int k = 0; k < _targets.Count; k++)
            {
                float num5 = Vector2.Distance(new Vector2((float)_targets[k].Item1, (float)_targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num4 == -1f || num5 < num4)
                {
                    num4 = num5;
                    tuple = _targets[k];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), Terraria.Collision.InTileBounds(), Terraria.ID.TileID.Sets.Platforms, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().