TModLoader: Terraria.GameContent.SmartCursorHelper.Step_WireCutter
Step_WireCutter()
static void Terraria.GameContent.SmartCursorHelper.Step_WireCutter (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
    {
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        if (providedInfo.item.type != 510 || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        _targets.Clear();
        for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
        {
            for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile.wire() || tile.wire2() || tile.wire3() || tile.wire4() || tile.actuator())
                {
                    _targets.Add(new Tuple<int, int>(i, j));
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int k = 0; k < _targets.Count; k++)
            {
                float num2 = Vector2.Distance(new Vector2((float)_targets[k].Item1, (float)_targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num == -1f || num2 < num)
                {
                    num = num2;
                    tuple = _targets[k];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.actuator(), Terraria.Collision.InTileBounds(), Terraria.Main.tile, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), and Terraria.Tile.wire4().
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().