TModLoader: Terraria.GameContent.SmartCursorHelper.Step_Acorns
Step_Acorns()
static void Terraria.GameContent.SmartCursorHelper.Step_Acorns (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
    {
        //IL_0558: Unknown result type (might be due to invalid IL or missing references)
        //IL_0562: Unknown result type (might be due to invalid IL or missing references)
        //IL_0567: Unknown result type (might be due to invalid IL or missing references)
        //IL_0571: Unknown result type (might be due to invalid IL or missing references)
        //IL_0576: Unknown result type (might be due to invalid IL or missing references)
        //IL_057c: Unknown result type (might be due to invalid IL or missing references)
        if (providedInfo.item.type != 27 || focusedX != -1 || focusedY != -1 || providedInfo.reachableStartY <= 20)
        {
            return;
        }
        _targets.Clear();
        for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
        {
            for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
            {
                Tile tile = Main.tile[i, j];
                Tile tile3 = Main.tile[i, j - 1];
                Tile tile4 = Main.tile[i, j + 1];
                Tile tile5 = Main.tile[i - 1, j];
                Tile tile6 = Main.tile[i + 1, j];
                Tile tile7 = Main.tile[i - 2, j];
                Tile tile8 = Main.tile[i + 2, j];
                Tile tile9 = Main.tile[i - 3, j];
                Tile tile10 = Main.tile[i + 3, j];
                if ((tile.active() && !Main.tileCut[tile.type] && !TileID.Sets.BreakableWhenPlacing[tile.type]) || (tile3.active() && !Main.tileCut[tile3.type] && !TileID.Sets.BreakableWhenPlacing[tile3.type]) || (tile5.active() && TileID.Sets.CommonSapling[tile5.type]) || (tile6.active() && TileID.Sets.CommonSapling[tile6.type]) || (tile7.active() && TileID.Sets.CommonSapling[tile7.type]) || (tile8.active() && TileID.Sets.CommonSapling[tile8.type]) || (tile9.active() && TileID.Sets.CommonSapling[tile9.type]) || (tile10.active() && TileID.Sets.CommonSapling[tile10.type]) || !tile4.active() || !WorldGen.SolidTile2(tile4))
                {
                    continue;
                }
                bool tileTypeValid = false;
                switch (tile4.type)
                {
                case 60:
                    if (WorldGen.EmptyTileCheck(i - 2, i + 2, j - 20, j, 20))
                    {
                        _targets.Add(new Tuple<int, int>(i, j));
                    }
                    continue;
                case 2:
                case 23:
                case 53:
                case 109:
                case 112:
                case 116:
                case 147:
                case 199:
                case 234:
                case 477:
                case 492:
                case 633:
                case 661:
                case 662:
                    tileTypeValid = true;
                    break;
                }
                if (!tileTypeValid)
                {
                    tileTypeValid = TileLoader.CanGrowModTree(tile4.type) || TileLoader.CanGrowModPalmTree(tile4.type);
                }
                if (tileTypeValid && tile5.liquid == 0 && tile.liquid == 0 && tile6.liquid == 0 && WorldGen.EmptyTileCheck(i - 2, i + 2, j - 20, j, 20))
                {
                    _targets.Add(new Tuple<int, int>(i, j));
                }
            }
        }
        _toRemove.Clear();
        for (int k = 0; k < _targets.Count; k++)
        {
            bool flag = false;
            for (int l = -1; l < 2; l += 2)
            {
                Tile tile2 = Main.tile[_targets[k].Item1 + l, _targets[k].Item2 + 1];
                if (!tile2.active())
                {
                    continue;
                }
                if (TileLoader.CanGrowModTree(tile2.type) || TileLoader.CanGrowModPalmTree(tile2.type))
                {
                    flag = true;
                    continue;
                }
                switch (tile2.type)
                {
                case 2:
                case 23:
                case 53:
                case 60:
                case 109:
                case 112:
                case 116:
                case 147:
                case 199:
                case 234:
                case 477:
                case 492:
                case 633:
                case 661:
                case 662:
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                _toRemove.Add(_targets[k]);
            }
        }
        for (int m = 0; m < _toRemove.Count; m++)
        {
            _targets.Remove(_toRemove[m]);
        }
        _toRemove.Clear();
        if (_targets.Count > 0)
        {
            float num = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int n = 0; n < _targets.Count; n++)
            {
                float num2 = Vector2.Distance(new Vector2((float)_targets[n].Item1, (float)_targets[n].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num == -1f || num2 < num)
                {
                    num = num2;
                    tuple = _targets[n];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.GameContent.SmartCursorHelper._toRemove, Terraria.Tile.active(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.ModLoader.TileLoader.CanGrowModPalmTree(), Terraria.ModLoader.TileLoader.CanGrowModTree(), Terraria.ID.TileID.Sets.CommonSapling, Terraria.WorldGen.EmptyTileCheck(), Terraria.Collision.InTileBounds(), Terraria.Tile.liquid, Terraria.WorldGen.SolidTile2(), Terraria.Main.tile, Terraria.Main.tileCut, and Terraria.Tile.type.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().