TModLoader: Terraria.GameContent.SmartCursorHelper.Step_Torch
Step_Torch()
static void Terraria.GameContent.SmartCursorHelper.Step_Torch (SmartCursorUsageInfo providedInfo, ref int fX, ref int fY) inline static private
    {
        //IL_0459: Unknown result type (might be due to invalid IL or missing references)
        //IL_0463: Unknown result type (might be due to invalid IL or missing references)
        //IL_0468: Unknown result type (might be due to invalid IL or missing references)
        //IL_0472: Unknown result type (might be due to invalid IL or missing references)
        //IL_0477: Unknown result type (might be due to invalid IL or missing references)
        //IL_047d: Unknown result type (might be due to invalid IL or missing references)
        int reachableStartX = providedInfo.reachableStartX;
        int reachableStartY = providedInfo.reachableStartY;
        int reachableEndX = providedInfo.reachableEndX;
        int reachableEndY = providedInfo.reachableEndY;
        _ = providedInfo.screenTargetX;
        _ = providedInfo.screenTargetY;
        if (providedInfo.item.createTile < 0 || !TileID.Sets.Torch[providedInfo.item.createTile] || fX != -1 || fY != -1)
        {
            return;
        }
        _targets.Clear();
        bool flag = !ItemID.Sets.WaterTorches[providedInfo.player.BiomeTorchHoldStyle(providedInfo.item.type)];
        for (int i = reachableStartX; i <= reachableEndX; i++)
        {
            for (int j = reachableStartY; j <= reachableEndY; j++)
            {
                Tile tile = Main.tile[i, j];
                Tile tile2 = Main.tile[i - 1, j];
                Tile tile3 = Main.tile[i + 1, j];
                Tile tile4 = Main.tile[i, j + 1];
                if (tile.active() && !TileID.Sets.BreakableWhenPlacing[tile.type] && (!Main.tileCut[tile.type] || tile.type == 82 || tile.type == 83))
                {
                    continue;
                }
                bool flag2 = false;
                for (int k = i - 8; k <= i + 8; k++)
                {
                    for (int l = j - 8; l <= j + 8; l++)
                    {
                        if (Main.tile[k, l] != null && TileID.Sets.Torch[Main.tile[k, l].type])
{
                            flag2 = true;
                            break;
                        }
                    }
                    if (flag2)
                    {
                        break;
                    }
                }
                if (!flag2 && (!flag || tile.liquid <= 0) && (tile.wall > 0 || (tile2.active() && (tile2.slope() == 0 || tile2.slope() % 2 != 1) && ((Main.tileSolid[tile2.type] && !Main.tileNoAttach[tile2.type] && !Main.tileSolidTop[tile2.type] && !TileID.Sets.NotReallySolid[tile2.type]) || TileID.Sets.IsBeam[tile2.type] || (WorldGen.IsTreeType(tile2.type) && WorldGen.IsTreeType(Main.tile[i - 1, j - 1].type) && WorldGen.IsTreeType(Main.tile[i - 1, j + 1].type)))) || (tile3.active() && (tile3.slope() == 0 || tile3.slope() % 2 != 0) && ((Main.tileSolid[tile3.type] && !Main.tileNoAttach[tile3.type] && !Main.tileSolidTop[tile3.type] && !TileID.Sets.NotReallySolid[tile3.type]) || TileID.Sets.IsBeam[tile3.type] || (WorldGen.IsTreeType(tile3.type) && WorldGen.IsTreeType(Main.tile[i + 1, j - 1].type) && WorldGen.IsTreeType(Main.tile[i + 1, j + 1].type)))) || (tile4.active() && Main.tileSolid[tile4.type] && !Main.tileNoAttach[tile4.type] && (!Main.tileSolidTop[tile4.type] || (TileID.Sets.Platforms[tile4.type] && tile4.slope() == 0)) && !TileID.Sets.NotReallySolid[tile4.type] && !tile4.halfBrick() && tile4.slope() == 0)) && !TileID.Sets.Torch[tile.type])
                {
                    _targets.Add(new Tuple<int, int>(i, j));
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int m = 0; m < _targets.Count; m++)
            {
                float num2 = Vector2.Distance(new Vector2((float)_targets[m].Item1, (float)_targets[m].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                if (num == -1f || num2 < num)
                {
                    num = num2;
                    tuple = _targets[m];
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, reachableStartX, reachableStartY, reachableEndX, reachableEndY))
            {
                fX = tuple.Item1;
                fY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.Collision.InTileBounds(), Terraria.ID.TileID.Sets.IsBeam, Terraria.WorldGen.IsTreeType(), Terraria.Tile.liquid, Terraria.ID.TileID.Sets.NotReallySolid, Terraria.ID.TileID.Sets.Platforms, Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Main.tileNoAttach, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.ID.TileID.Sets.Torch, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.ID.ItemID.Sets.WaterTorches.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().