TModLoader: Terraria.GameContent.SmartCursorHelper.Step_ClayPots
Step_ClayPots()
static void Terraria.GameContent.SmartCursorHelper.Step_ClayPots (SmartCursorUsageInfo providedInfo, ref int focusedX, ref int focusedY) inline static private
    {
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        if (providedInfo.item.createTile != 78 || focusedX != -1 || focusedY != -1)
        {
            return;
        }
        _targets.Clear();
        bool flag = false;
        if (Main.tile[providedInfo.screenTargetX, providedInfo.screenTargetY].active())
        {
            flag = true;
        }
        if (!Collision.InTileBounds(providedInfo.screenTargetX, providedInfo.screenTargetY, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY))
        {
            flag = true;
        }
        if (!flag)
        {
            for (int i = providedInfo.reachableStartX; i <= providedInfo.reachableEndX; i++)
            {
                for (int j = providedInfo.reachableStartY; j <= providedInfo.reachableEndY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    Tile tile2 = Main.tile[i, j + 1];
                    if ((!tile.active() || Main.tileCut[tile.type] || TileID.Sets.BreakableWhenPlacing[tile.type]) && tile2.nactive() && !tile2.halfBrick() && tile2.slope() == 0 && Main.tileSolid[tile2.type])
                    {
                        _targets.Add(new Tuple<int, int>(i, j));
                    }
                }
            }
        }
        if (_targets.Count > 0)
        {
            float num = -1f;
            Tuple<int, int> tuple = _targets[0];
            for (int k = 0; k < _targets.Count; k++)
            {
                if (Collision.EmptyTile(_targets[k].Item1, _targets[k].Item2, ignoreTiles: true))
                {
                    float num2 = Vector2.Distance(new Vector2((float)_targets[k].Item1, (float)_targets[k].Item2) * 16f + Vector2.One * 8f, providedInfo.mouse);
                    if (num == -1f || num2 < num)
                    {
                        num = num2;
                        tuple = _targets[k];
                    }
                }
            }
            if (Collision.InTileBounds(tuple.Item1, tuple.Item2, providedInfo.reachableStartX, providedInfo.reachableStartY, providedInfo.reachableEndX, providedInfo.reachableEndY) && num != -1f)
            {
                focusedX = tuple.Item1;
                focusedY = tuple.Item2;
            }
        }
        _targets.Clear();
    }
References Terraria.GameContent.SmartCursorHelper._targets, Terraria.Tile.active(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.Collision.EmptyTile(), Terraria.Collision.InTileBounds(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.GameContent.SmartCursorHelper.SmartCursorLookup().