TModLoader: Terraria.ModLoader.ModType.Load
Load() [2/2]
void ILoadable. Terraria.ModLoader.ModType< TEntity, TModType >.Load (Mod mod) inline private inherited
Called when loading the type.
Parameters
mod The mod instance associated with this type.
Implements Terraria.ModLoader.ILoadable.
    {
        if (!LoaderUtils.IsValidated(GetType()))
        {
            ValidateType();
        }
        Mod = mod;
        InitTemplateInstance();
        Load();
        Register();
    }
References Terraria.ModLoader.ModType< TEntity, TModType >.InitTemplateInstance(), Terraria.ModLoader.Core.LoaderUtils.IsValidated(), Terraria.ModLoader.ModType< TEntity, TModType >.Load(), Terraria.ModLoader.ModType< TEntity, TModType >.Register(), and Terraria.ModLoader.ModType< TEntity, TModType >.ValidateType().