TModLoader: Terraria.ModLoader.ModType.SetStaticDefaults
SetStaticDefaults()
virtual void Terraria.ModLoader.ModType< TEntity, TModType >.SetStaticDefaults () inline virtual inherited
Allows you to modify the properties after initial loading has completed.
Reimplemented from Terraria.ModLoader.ModType< TEntity >.
Reimplemented in Terraria.ModLoader.Default.Developer.DeveloperItem, Terraria.ModLoader.Default.Patreon.AetherBreaker_Wings, Terraria.ModLoader.Default.Patreon.Coolmike5000_Wings, Terraria.ModLoader.Default.Patreon.dinidini_Body, Terraria.ModLoader.Default.Patreon.dinidini_Legs, Terraria.ModLoader.Default.Patreon.dinidini_Wings, Terraria.ModLoader.Default.Patreon.dschosen_Wings, Terraria.ModLoader.Default.Patreon.Frosty_Hat, Terraria.ModLoader.Default.Patreon.Glory_Legs, Terraria.ModLoader.Default.Patreon.Linus_Wings, Terraria.ModLoader.Default.Patreon.Mayne_Wings, Terraria.ModLoader.Default.Patreon.PatreonItem, Terraria.ModLoader.Default.Patreon.POCKETS_Wings, Terraria.ModLoader.Default.Patreon.Polyblank_Body, Terraria.ModLoader.Default.Patreon.Remeus_Body, Terraria.ModLoader.Default.Patreon.Remeus_Legs, Terraria.ModLoader.Default.Patreon.Saethar_Wings, Terraria.ModLoader.Default.Patreon.Sailing_Squid_Wings, Terraria.ModLoader.Default.Patreon.Tantamount_Body, Terraria.ModLoader.Default.Patreon.Tantamount_Head, Terraria.ModLoader.Default.Patreon.Tantamount_Wings, Terraria.ModLoader.Default.Patreon.toplayz_Body, Terraria.ModLoader.Default.Patreon.toplayz_Legs, Terraria.ModLoader.Default.Patreon.xAqult_Body, Terraria.ModLoader.Default.Patreon.xAqult_Head, Terraria.ModLoader.Default.Patreon.xAqult_Lens, Terraria.ModLoader.Default.Patreon.xAqult_Wings, Terraria.ModLoader.Default.Patreon.Zeph_Wings, Terraria.ModLoader.Default.UnloadedChest, Terraria.ModLoader.Default.UnloadedDresser, Terraria.ModLoader.Default.UnloadedItem, Terraria.ModLoader.Default.UnloadedNonSolidTile, Terraria.ModLoader.Default.UnloadedSemiSolidTile, Terraria.ModLoader.Default.UnloadedSolidTile, Terraria.ModLoader.Default.UnloadedSupremeFurniture, Terraria.ModLoader.Default.UnloadedWall, Terraria.ModLoader.ModBiome, Terraria.ModLoader.ModBlockType, Terraria.ModLoader.ModBuff, Terraria.ModLoader.ModDust, Terraria.ModLoader.ModMount, and Terraria.ModLoader.ModType< TEntity, TModType >.
Definition at line 72 of file ModType.cs.
    {
    }
Referenced by Terraria.ModLoader.IO.TagSerializer< T, S >.SetupContent(), Terraria.ModLoader.BuilderToggle.SetupContent(), Terraria.ModLoader.DamageClass.SetupContent(), Terraria.ModLoader.ExtraJump.SetupContent(), Terraria.ModLoader.GlobalBackgroundStyle.SetupContent(), Terraria.ModLoader.GlobalBossBar.SetupContent(), Terraria.ModLoader.GlobalBuff.SetupContent(), Terraria.ModLoader.GlobalInfoDisplay.SetupContent(), Terraria.ModLoader.GlobalPylon.SetupContent(), Terraria.ModLoader.GlobalTile.SetupContent(), Terraria.ModLoader.GlobalWall.SetupContent(), Terraria.ModLoader.InfoDisplay.SetupContent(), Terraria.ModLoader.ModBossBar.SetupContent(), Terraria.ModLoader.ModBossBarStyle.SetupContent(), Terraria.ModLoader.ModCommand.SetupContent(), Terraria.ModLoader.ModGore.SetupContent(), Terraria.ModLoader.ModHair.SetupContent(), Terraria.ModLoader.ModMenu.SetupContent(), Terraria.ModLoader.ModPrefix.SetupContent(), Terraria.ModLoader.ModRarity.SetupContent(), Terraria.ModLoader.ModResourceDisplaySet.SetupContent(), Terraria.ModLoader.ModResourceOverlay.SetupContent(), Terraria.ModLoader.ModSurfaceBackgroundStyle.SetupContent(), Terraria.ModLoader.ModSystem.SetupContent(), Terraria.ModLoader.ModUndergroundBackgroundStyle.SetupContent(), Terraria.ModLoader.ModWaterfallStyle.SetupContent(), Terraria.ModLoader.ModWaterStyle.SetupContent(), and Terraria.ModLoader.PlayerDrawLayer.SetupContent().