TModLoader: Terraria.ModLoader.Default.UnloadedSystem.LoadWorldData
LoadWorldData()
override void Terraria.ModLoader.Default.UnloadedSystem.LoadWorldData (TagCompound tag) inline virtual
Allows you to load custom data you have saved for this system in the currently loading world.
Try to write defensive loading code that won't crash if something's missing.
Parameters
tag The TagCompound to load data from.
Reimplemented from Terraria.ModLoader.ModSystem.
Definition at line 47 of file UnloadedSystem.cs.
    {
        WorldIO.LoadModData(tag.GetList<TagCompound>("list"));
        WorldIO.LoadNPCs(tag.GetList<TagCompound>("unloadedNPCs"));
        WorldIO.LoadNPCKillCounts(tag.GetList<TagCompound>("unloadedKillCounts"));
        WorldIO.LoadNPCBestiaryKills(tag.GetList<TagCompound>("unloadedBestiaryKills"));
        WorldIO.LoadNPCBestiarySights(tag.GetList<TagCompound>("unloadedBestiarySights"));
        WorldIO.LoadNPCBestiaryChats(tag.GetList<TagCompound>("unloadedBestiaryChats"));
    }
References Terraria.ModLoader.IO.WorldIO.LoadModData(), Terraria.ModLoader.IO.WorldIO.LoadNPCBestiaryChats(), Terraria.ModLoader.IO.WorldIO.LoadNPCBestiaryKills(), Terraria.ModLoader.IO.WorldIO.LoadNPCBestiarySights(), Terraria.ModLoader.IO.WorldIO.LoadNPCKillCounts(), and Terraria.ModLoader.IO.WorldIO.LoadNPCs().