TModLoader: Terraria.Graphics.Effects.FilterManager.EndCapture
EndCapture()
void Terraria.Graphics.Effects.FilterManager.EndCapture (RenderTarget2D finalTexture, RenderTarget2D screenTarget1, RenderTarget2D screenTarget2, Color clearColor) inline
Definition at line 137 of file FilterManager.cs.
    {
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0164: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_012e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        if (!_captureThisFrame)
        {
            return;
        }
        LinkedListNode<Filter> linkedListNode = _activeFilters.First;
        _ = _activeFilters.Count;
        Filter filter = null;
        RenderTarget2D renderTarget2D = null;
        RenderTarget2D renderTarget2D2 = screenTarget1;
        GraphicsDevice graphicsDevice = ((Game)Main.instance).GraphicsDevice;
        int num = 0;
        if (Main.player[Main.myPlayer].gravDir == -1f)
        {
            renderTarget2D = screenTarget2;
            graphicsDevice.SetRenderTarget(renderTarget2D);
            graphicsDevice.Clear(clearColor);
            Main.spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.Default, RasterizerState.CullNone, (Effect)null, Matrix.Invert(Main.GameViewMatrix.EffectMatrix));
            Main.spriteBatch.Draw((Texture2D)(object)renderTarget2D2, Vector2.Zero, Color.White);
            Main.spriteBatch.End();
            renderTarget2D2 = screenTarget2;
        }
        while (linkedListNode != null)
        {
            Filter value = linkedListNode.Value;
            LinkedListNode<Filter>? next = linkedListNode.Next;
            if (value.Priority >= _priorityThreshold)
            {
                num++;
                if (num > _activeFilterCount - _filterLimit && value.IsVisible())
                {
                    if (filter != null)
                    {
                        renderTarget2D = ((renderTarget2D2 != screenTarget1) ? screenTarget1 : screenTarget2);
                        graphicsDevice.SetRenderTarget(renderTarget2D);
                        graphicsDevice.Clear(clearColor);
                        Main.spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend);
                        filter.Apply();
                        Main.spriteBatch.Draw((Texture2D)(object)renderTarget2D2, Vector2.Zero, Main.ColorOfTheSkies);
                        Main.spriteBatch.End();
                        renderTarget2D2 = ((renderTarget2D2 != screenTarget1) ? screenTarget1 : screenTarget2);
                    }
                    filter = value;
                }
            }
            linkedListNode = next;
        }
        graphicsDevice.SetRenderTarget(finalTexture);
        graphicsDevice.Clear(clearColor);
        if (Main.player[Main.myPlayer].gravDir == -1f)
        {
            Main.spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.Default, RasterizerState.CullNone, (Effect)null, Main.GameViewMatrix.EffectMatrix);
        }
        else
        {
            Main.spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend);
        }
        if (filter != null)
        {
            filter.Apply();
            Main.spriteBatch.Draw((Texture2D)(object)renderTarget2D2, Vector2.Zero, Main.ColorOfTheSkies);
        }
        else
        {
            Main.spriteBatch.Draw((Texture2D)(object)renderTarget2D2, Vector2.Zero, Color.White);
        }
        Main.spriteBatch.End();
        for (int i = 0; i < 8; i++)
        {
            graphicsDevice.Textures[i] = null;
        }
        if (this.OnPostDraw != null)
        {
            this.OnPostDraw();
        }
    }
References Terraria.Graphics.Effects.FilterManager._activeFilterCount, Terraria.Graphics.Effects.FilterManager._activeFilters, Terraria.Graphics.Effects.FilterManager._captureThisFrame, Terraria.Graphics.Effects.FilterManager._filterLimit, Terraria.Graphics.Effects.FilterManager._priorityThreshold, Terraria.Graphics.Effects.Filter.Apply(), Terraria.Main.ColorOfTheSkies, Terraria.Main.GameViewMatrix, Terraria.Player.gravDir, Terraria.Main.instance, Terraria.Graphics.Effects.Filter.IsVisible(), Terraria.Main.myPlayer, Terraria.Graphics.Effects.FilterManager.OnPostDraw, Terraria.Main.player, Terraria.Graphics.Effects.GameEffect.Priority, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DoDraw(), and Terraria.Graphics.Capture.CaptureCamera.DrawTick().