TModLoader: Terraria.ModLoader.PosData.CoordsToPos
CoordsToPos()
static int Terraria.ModLoader.PosData< T >.CoordsToPos (int x, int y) inline static
Gets a Position ID based on the x,y position. If using in an order sensitive case, see NextLocation.
Parameters
x
y
Returns
Definition at line 140 of file PosData.cs.
    {
        return x * Main.maxTilesY + y;
    }
Referenced by Terraria.ModLoader.PosData< T >.OrderedSparseLookupBuilder.Add(), Terraria.ModLoader.PosData< T >.FindIndex< T >(), Terraria.ModLoader.PosData< T >.OrderedSparseLookupReader.Get(), Terraria.ModLoader.PosData< T >.Lookup< T >(), Terraria.ModLoader.PosData< T >.LookupExact< T >(), Terraria.ModLoader.PosData< T >.NearbySearchOrderedPosMap< T >(), and Terraria.ModLoader.IO.TileIO.ReadModTile().