TModLoader: Terraria.Social.Base.SocialBrowserModule.DirectQueryItems
DirectQueryItems()
List< ModDownloadItem > Terraria.Social.Base.SocialBrowserModule.DirectQueryItems (QueryParameters queryParams, out List< string > missingMods)
Implemented in Terraria.Social.Steam.WorkshopBrowserModule.
Referenced by Terraria.Social.Base.SocialBrowserModule.DirectQueryInstalledMDItems(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadModsAndReturnToBrowser(), and Terraria.Social.Base.SocialBrowserModule.GetDependenciesRecursive().