TModLoader: Terraria.ModLoader.UI.UIModNetDiagnostics.Draw
Draw()
void Terraria.ModLoader.UI.UIModNetDiagnostics.Draw (SpriteBatch spriteBatch) inline
Implements Terraria.UI.INetDiagnosticsUI.
    {
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        int count = CounterByModNetId.Length;
        int numCols = (count - 1) / 50;
        int x = 190;
        int xBuf = x + 10;
        int y = 110;
        int yBuf = y + 10;
        int width = 232;
        width += (int)(FirstColumnWidth + fontAsset.Value.MeasureString(HighestFoundSentBytes.ToString()).X * 0.7f);
        int widthBuf = width + 10;
        int lineHeight = 13;
        Vector2 modPos = default(Vector2);
        for (int i = 0; i <= numCols; i++)
        {
            int lineCountInCol = ((i == numCols) ? (1 + (count - 1) % 50) : 50);
            int heightBuf = lineHeight * (lineCountInCol + 2) + 10;
            Utils.DrawInvBG(spriteBatch, x + widthBuf * i, y, width, heightBuf);
            ((Vector2)(ref modPos))._002Ector((float)(xBuf + widthBuf * i), (float)yBuf);
            Vector2 headerPos = modPos + new Vector2(FirstColumnWidth, 0f);
            DrawText(spriteBatch, "Received(#, Bytes)       Sent(#, Bytes)", headerPos, Color.White);
            DrawText(spriteBatch, "Mod", modPos, Color.White);
        }
        Vector2 position = default(Vector2);
        for (int j = 0; j < count; j++)
        {
            int colNum = j / 50;
            int lineNum = j - colNum * 50;
            position.X = xBuf + colNum * widthBuf;
            position.Y = yBuf + lineHeight + lineNum * lineHeight;
            DrawCounter(spriteBatch, CounterByModNetId[j], Mods[j].Name, position);
        }
    }
References Terraria.ModLoader.UI.UIModNetDiagnostics.CounterByModNetId, Terraria.ModLoader.UI.UIModNetDiagnostics.DrawCounter(), Terraria.Utils.DrawInvBG(), Terraria.ModLoader.UI.UIModNetDiagnostics.DrawText(), Terraria.ModLoader.UI.UIModNetDiagnostics.FirstColumnWidth, Terraria.ModLoader.UI.UIModNetDiagnostics.fontAsset, Terraria.ModLoader.UI.UIModNetDiagnostics.HighestFoundSentBytes, and Terraria.ModLoader.UI.UIModNetDiagnostics.Mods.