TModLoader: Terraria.WorldGen.KillTile_GetTreeDrops
KillTile_GetTreeDrops()
static void Terraria.WorldGen.KillTile_GetTreeDrops (int i, int j, Tile tileCache, ref bool bonusWood, ref int dropItem, ref int secondaryItem) inline static private
    {
        //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
        if (tileCache.frameX >= 22 && tileCache.frameY >= 198)
        {
            if (Main.netMode != 1)
            {
                if (genRand.Next(2) == 0)
                {
                    int k;
                    for (k = j; Main.tile[i, k] != null && (!Main.tile[i, k].active() || !Main.tileSolid[Main.tile[i, k].type] || Main.tileSolidTop[Main.tile[i, k].type]); k++)
                    {
                    }
                    if (Main.tile[i, k] != null)
                    {
                        Tile tile = Main.tile[i, k];
                        bool vanillaResult = false;
                        if (tile.type == 2 || tile.type == 109 || tile.type == 477 || tile.type == 492 || tile.type == 147 || tile.type == 199 || tile.type == 23 || tile.type == 633)
{
                            vanillaResult = true;
                        }
                        if (vanillaResult || TileLoader.CanDropAcorn(tile.type))
{
                            dropItem = 9;
                            secondaryItem = 27;
                        }
                        else
{
                            dropItem = 9;
                        }
                    }
                }
                else
                {
                    dropItem = 9;
                }
            }
        }
        else
        {
            dropItem = 9;
        }
        if (dropItem != 9)
        {
            return;
        }
        GetTreeBottom(i, j, out var x, out var y);
        if (Main.tile[x, y].active())
        {
            switch (Main.tile[x, y].type)
            {
            case 633:
                dropItem = 5215;
                break;
            case 23:
            case 661:
                dropItem = 619;
                break;
            case 199:
            case 662:
                dropItem = 911;
                break;
            case 60:
                dropItem = 620;
                break;
            case 109:
            case 492:
                dropItem = 621;
                break;
            case 70:
                if (genRand.Next(2) == 0)
                {
                    dropItem = 183;
                }
                else
                {
                    dropItem = 0;
                }
                break;
            case 147:
                dropItem = 2503;
                break;
            }
            TileLoader.DropTreeWood(Main.tile[x, y].type, ref dropItem);
        }
        int num = Player.FindClosest(new Vector2((float)(x * 16), (float)(y * 16)), 16, 16);
        int axe = Main.player[num].inventory[Main.player[num].selectedItem].axe;
        if (genRand.Next(100) < axe || Main.rand.Next(3) == 0)
        {
            bonusWood = true;
        }
    }
References Terraria.ModLoader.TileLoader.CanDropAcorn(), Terraria.ModLoader.TileLoader.DropTreeWood(), Terraria.Player.FindClosest(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Main.netMode, Terraria.Main.player, Terraria.Main.rand, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.