TModLoader: Terraria.WorldGen.GrowPalmTree
GrowPalmTree()
static bool Terraria.WorldGen.GrowPalmTree (int i, int y) inline static
Definition at line 19876 of file WorldGen.cs.
    {
        int num = y;
        if (!InWorld(i, y))
        {
            return false;
        }
        while (TileID.Sets.TreeSapling[Main.tile[i, num].type])
        {
            num++;
            if (Main.tile[i, num] == null)
            {
                return false;
            }
        }
        Tile tile = Main.tile[i, num];
        Tile tile2 = Main.tile[i, num - 1];
        byte color = 0;
        if (Main.tenthAnniversaryWorld && !gen)
        {
            color = (byte)genRand.Next(1, 13);
        }
        tile.slope();
        tile.halfBrick();
        if (!tile.active() || tile.halfBrick() || tile.slope() != 0)
        {
            return false;
        }
        if (tile2.wall != 0 || tile2.liquid != 0)
        {
            return false;
        }
        bool vanillaCanGrow = true;
        if (tile.type != 53 && tile.type != 234 && tile.type != 116 && tile.type != 112)
        {
            vanillaCanGrow = false;
        }
        if (!vanillaCanGrow && !TileLoader.CanGrowModPalmTree(tile.type))
        {
            return false;
        }
        if (!EmptyTileCheck(i, i, num - 2, num - 1, 20))
        {
            return false;
        }
        if (!EmptyTileCheck(i - 1, i + 1, num - 30, num - 3, 20))
        {
            return false;
        }
        int num2 = genRand.Next(10, 21);
        int num3 = genRand.Next(-8, 9);
        num3 *= 2;
        short num4 = 0;
        for (int j = 0; j < num2; j++)
        {
            tile = Main.tile[i, num - 1 - j];
            if (j == 0)
            {
                tile.active(active: true);
                tile.type = 323;
                tile.frameX = 66;
                tile.frameY = 0;
                tile.color(color);
                continue;
            }
            if (j == num2 - 1)
            {
                tile.active(active: true);
                tile.type = 323;
                tile.frameX = (short)(22 * genRand.Next(4, 7));
                tile.frameY = num4;
                tile.color(color);
                continue;
            }
            if (num4 != num3)
            {
                double num5 = (double)j / (double)num2;
                if (!(num5 < 0.25))
                {
                    if ((!(num5 < 0.5) || genRand.Next(13) != 0) && (!(num5 < 0.7) || genRand.Next(9) != 0) && num5 < 0.95)
                    {
                        genRand.Next(5);
                    }
                    short num6 = (short)Math.Sign(num3);
                    num4 += (short)(num6 * 2);
                }
            }
            tile.active(active: true);
            tile.type = 323;
            tile.frameX = (short)(22 * genRand.Next(0, 3));
            tile.frameY = num4;
            tile.color(color);
        }
        RangeFrame(i - 2, num - num2 - 1, i + 2, num + 1);
        NetMessage.SendTileSquare(-1, i, num - num2, 1, num2);
        return true;
    }
References Terraria.Tile.active(), Terraria.ModLoader.TileLoader.CanGrowModPalmTree(), Terraria.Tile.color(), Terraria.Tile.halfBrick(), Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.ID.TileID.Sets.TreeSapling, and Terraria.Tile.type.