TModLoader: Terraria.WorldGen.GenerateWorld_RunTasksAndFinish
GenerateWorld_RunTasksAndFinish()
static void Terraria.WorldGen.GenerateWorld_RunTasksAndFinish (int seed, Stopwatch generationStopwatch, GenerationProgress customProgressObject) inline static private
Definition at line 17820 of file WorldGen.cs.
    {
        SystemLoader.ModifyWorldGenTasks(_generator._passes, ref _generator._totalLoadWeight);
        _generator.GenerateWorld(customProgressObject);
        ConsumePostGenActions(GenVars.structures);
        SystemLoader.PostWorldGen();
        Main.WorldFileMetadata = FileMetadata.FromCurrentSettings(FileType.World);
        Main.ActiveWorldFileData.modVersionsDuringWorldGen = Terraria.ModLoader.ModLoader.Mods.ToDictionary((Mod x) => x.Name, (Mod x) => x.Version);
        Main.NotifyOfEvent(GameNotificationType.WorldGen);
        drunkWorldGenText = false;
        BackupIO.archiveLock = true;
        generationStopwatch.Stop();
        Logging.tML.Info((object)$"Generation of {Main.maxTilesX}x{Main.maxTilesY} {(crimson ? "Crimson" : "Corruption")} world with seed {seed} completed in {generationStopwatch.Elapsed:m'm 's's 'fff'ms'}");
    }
References Terraria.WorldBuilding.WorldGenerator._passes, Terraria.WorldBuilding.WorldGenerator._totalLoadWeight, Terraria.Enums.Corruption, Terraria.Enums.Crimson, Terraria.IO.FileMetadata.FromCurrentSettings(), Terraria.WorldBuilding.WorldGenerator.GenerateWorld(), Terraria.ModLoader.SystemLoader.ModifyWorldGenTasks(), Terraria.ModLoader.ModLoader.Mods, Terraria.ModLoader.Mod.Name, Terraria.Main.NotifyOfEvent(), Terraria.ModLoader.SystemLoader.PostWorldGen(), Terraria.WorldBuilding.GenVars.structures, Terraria.ModLoader.Logging.tML, and Terraria.ModLoader.Mod.Version.
Referenced by Terraria.WorldGen.GenerateWorld().