TModLoader: Terraria.WorldGen.Check2x2
Check2x2()
static void Terraria.WorldGen.Check2x2 (int i, int j, int type) inline static
    {
        if (destroyObject)
        {
            return;
        }
        bool flag = false;
        int num = 0;
        Tile tile = Main.tile[i, j];
        int num9 = tile.frameX / 18 * -1;
        if (num9 < -1)
        {
            num9 += 2;
            num = 36;
        }
        num9 += i;
        int num10 = ((type == 172) ? 38 : 36);
        tile = Main.tile[i, j];
        int num11 = tile.frameY;
        int num12 = 0;
        while (num11 >= num10)
        {
            num11 -= num10;
            num12++;
        }
        int num13 = j - num11 / 18;
        int num14 = 0;
        if (type == 652)
        {
            tile = Main.tile[i, j];
            num14 = tile.frameX / 36;
            tile = Main.tile[i, j];
            num9 = tile.frameX % 36 / 18 * -1 + i;
            num = num14 * 36;
        }
        for (int k = num9; k < num9 + 2; k++)
        {
            for (int l = num13; l < num13 + 2; l++)
            {
                Tile tileSafely = Framing.GetTileSafely(k, l);
                if (!tileSafely.active() || tileSafely.type != type || tileSafely.frameX != (k - num9) * 18 + num || tileSafely.frameY != (l - num13) * 18 + num12 * num10)
                {
                    flag = true;
                    break;
                }
            }
            if (type == 95 || type == 126)
            {
                Framing.GetTileSafely(k, num13 - 1);
                tile = Main.tile[k, num13 - 1];
                if (tile.active())
                {
                    bool[] tileSolid = Main.tileSolid;
                    tile = Main.tile[k, num13 - 1];
                    if (tileSolid[tile.type])
                    {
                        bool[] tileSolidTop = Main.tileSolidTop;
                        tile = Main.tile[k, num13 - 1];
                        if (!tileSolidTop[tile.type])
{
                            continue;
                        }
                    }
                }
                flag = true;
            }
            else if (!TileID.Sets.Boulders[type] && type != 132)
            {
                Tile tileSafely2 = Framing.GetTileSafely(k, num13 + 2);
                if (!tileSafely2.active() || (!Main.tileSolid[tileSafely2.type] && !Main.tileTable[tileSafely2.type]))
                {
                    flag = true;
                }
                if (tileSafely2.halfBrick())
                {
                    flag = true;
                }
            }
        }
        bool flag2;
        ushort type5;
        if (TileID.Sets.Boulders[type])
        {
            if (Main.tile[num9, num13 - 1] == null)
            {
                tile = (Main.tile[num9, num13 - 1] = default(Tile));
            }
            if (Main.tile[num9 + 1, num13 - 1] == null)
            {
                tile = (Main.tile[num9 + 1, num13 - 1] = default(Tile));
            }
            tile = Main.tile[num9, num13 - 1];
            ushort type2 = tile.type;
            tile = Main.tile[num9 + 1, num13 - 1];
            ushort type3 = tile.type;
            if (!TileID.Sets.BasicChest[type2] && !TileID.Sets.BasicChest[type3] && !TileID.Sets.BasicDresser[type2] && !TileID.Sets.BasicDresser[type3] && !TileID.Sets.BasicChestFake[type2] && !TileID.Sets.BasicChestFake[type3] && type2 != 470 && type3 != 470 && type2 != 475 && type3 != 475 && !SolidTileAllowBottomSlope(num9, num13 + 2) && !SolidTileAllowBottomSlope(num9 + 1, num13 + 2))
            {
                flag = true;
            }
        }
        else if (type == 132)
        {
            flag = false;
            tile = Main.tile[i, j];
            num13 = tile.frameY / 18 * -1;
            num13 += j;
            num = 0;
            tile = Main.tile[i, j];
            num9 = tile.frameX / 18 * -1;
            while (num9 < -1)
            {
                num9 += 2;
                num += 36;
            }
            num9 += i;
            for (int m = num9; m < num9 + 2; m++)
            {
                for (int n = num13; n < num13 + 2; n++)
                {
                    if (Main.tile[m, n] == null)
                    {
                        tile = (Main.tile[m, n] = default(Tile));
                    }
                    tile = Main.tile[m, n];
                    if (tile.active())
                    {
                        tile = Main.tile[m, n];
                        if (tile.type == type)
{
                            tile = Main.tile[m, n];
                            if (tile.frameX == (m - num9) * 18 + num)
{
                                tile = Main.tile[m, n];
                                if (tile.frameY == (n - num13) * 18)
{
                                    continue;
                                }
                            }
                        }
                    }
                    flag = true;
                }
            }
            if (Main.tile[num9, num13 + 2] == null)
            {
                tile = (Main.tile[num9, num13 + 2] = default(Tile));
            }
            if (Main.tile[num9 + 1, num13 + 2] == null)
            {
                tile = (Main.tile[num9 + 1, num13 + 2] = default(Tile));
            }
            flag2 = false;
            tile = Main.tile[num9, num13 + 2];
            ushort type4 = tile.type;
            tile = Main.tile[num9 + 1, num13 + 2];
            type5 = tile.type;
            tile = Main.tile[num9, num13 + 2];
            if (tile.active() && (Main.tileSolid[type4] || Main.tileSolidTop[type4]))
            {
                tile = Main.tile[num9, num13 + 2];
                if (!tile.halfBrick())
                {
                    tile = Main.tile[num9, num13 + 2];
                    if (tile.slope() != 0)
                    {
                        tile = Main.tile[num9, num13 + 2];
                        if (!tile.bottomSlope())
{
                            goto IL_05b4;
                        }
                    }
                    goto IL_05b7;
                }
            }
            goto IL_05b4;
        }
        goto IL_0753;
        IL_05b4:
        flag2 = true;
        goto IL_05b7;
        IL_063e:
        if (flag2)
        {
            tile = Main.tile[num9, num13];
            if (tile.wall >= 1)
            {
                tile = Main.tile[num9 + 1, num13];
                if (tile.wall >= 1)
                {
                    tile = Main.tile[num9, num13 + 1];
                    if (tile.wall >= 1)
                    {
                        tile = Main.tile[num9 + 1, num13 + 1];
                        if (tile.wall >= 1)
{
                            if (num < 72)
{
                                for (int num15 = num9; num15 < num9 + 2; num15++)
{
                                    for (int num16 = num13; num16 < num13 + 2; num16++)
{
                                        tile = Main.tile[num15, num16];
                                        tile.frameX += 72;
                                    }
                                }
                            }
                            goto IL_0753;
                        }
                    }
                }
            }
            flag = true;
        }
        else if (num >= 72)
        {
            for (int num2 = num9; num2 < num9 + 2; num2++)
            {
                for (int num3 = num13; num3 < num13 + 2; num3++)
                {
                    tile = Main.tile[num2, num3];
                    tile.frameX -= 72;
                }
            }
        }
        goto IL_0753;
        IL_063b:
        flag2 = true;
        goto IL_063e;
        IL_05b7:
        tile = Main.tile[num9 + 1, num13 + 2];
        if (tile.active() && (Main.tileSolid[type5] || Main.tileSolidTop[type5]))
        {
            tile = Main.tile[num9 + 1, num13 + 2];
            if (!tile.halfBrick())
            {
                tile = Main.tile[num9 + 1, num13 + 2];
                if (tile.slope() != 0)
                {
                    tile = Main.tile[num9 + 1, num13 + 2];
                    if (!tile.bottomSlope())
                    {
                        goto IL_063b;
                    }
                }
                goto IL_063e;
            }
        }
        goto IL_063b;
        IL_0753:
        if (!flag)
        {
            return;
        }
        destroyObject = true;
        bool drop = TileLoader.Drop(i, j, type);
        for (int num4 = num9; num4 < num9 + 2; num4++)
        {
            for (int num5 = num13; num5 < num13 + 2; num5++)
            {
                tile = Main.tile[num4, num5];
                if (tile.type == type)
                {
                    tile = Main.tile[num4, num5];
                    if (tile.active())
                    {
                        KillTile(num4, num5);
                    }
                }
            }
        }
        using (new Item.DisableNewItemMethod(!drop))
        {
            int num6 = 0;
            switch (type)
            {
            case 521:
                num6 = 4327;
                break;
            case 522:
                num6 = 4328;
                break;
            case 523:
                num6 = 4329;
                break;
            case 524:
                num6 = 4330;
                break;
            case 525:
                num6 = 4331;
                break;
            case 526:
                num6 = 4332;
                break;
            case 527:
                num6 = 4333;
                break;
            case 564:
                num6 = 4553;
                break;
            case 565:
                num6 = 4552;
                break;
            case 594:
                num6 = 4869;
                break;
            case 621:
                num6 = 3750;
                break;
            case 622:
                num6 = 5008;
                break;
            }
            if (type == 598)
            {
                num6 = 4880;
            }
            if (type == 360)
            {
                num6 = 3072;
            }
            if (type == 580)
            {
                num6 = 4846;
            }
            if (type == 620)
            {
                num6 = 4964;
            }
            if (type == 505)
            {
                num6 = 4275;
            }
            if (type == 543)
            {
                num6 = 4398;
            }
            if (type == 568)
            {
                num6 = 4655;
            }
            if (type == 569)
            {
                num6 = 4656;
            }
            if (type == 570)
            {
                num6 = 4657;
            }
            if (type >= 288 && type <= 295)
            {
                num6 = 2178 + type - 288;
            }
            if (type >= 316 && type <= 318)
            {
                num6 = 2439 + type - 316;
            }
            if (type == 85)
            {
                num6 = 321;
            }
            if (type == 94)
            {
                num6 = 352;
            }
            if (type == 95)
            {
                num6 = 344;
            }
            if (type == 96)
            {
                num6 = 345;
            }
            if (type == 97)
            {
                num6 = 346;
            }
            if (type == 98)
            {
                num6 = 347;
            }
            if (type == 99)
            {
                num6 = 348;
            }
            if (type == 335)
            {
                num6 = 2700;
            }
            if (type == 411)
            {
                num6 = 3545;
            }
            if (type == 652)
            {
                num6 = ((num14 < 3) ? 195 : ((num14 >= 6) ? 331 : 62));
            }
            if (type == 100)
            {
                switch (num12)
                {
                case 0:
                    num6 = 349;
                    break;
                case 1:
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    num6 = 2092 + num12 - 1;
                    break;
                case 13:
                case 14:
                case 15:
                case 16:
                    num6 = 2149 + num12 - 13;
                    break;
                default:
                    switch (num12)
                    {
                    case 17:
                        num6 = 2227;
                        break;
                    case 18:
                        num6 = 2522;
                        break;
                    case 19:
                        num6 = 2541;
                        break;
                    case 20:
                        num6 = 2555;
                        break;
                    case 21:
                        num6 = 2570;
                        break;
                    case 22:
                        num6 = 2664;
                        break;
                    case 23:
                        num6 = 2665;
                        break;
                    case 24:
                        num6 = 2666;
                        break;
                    case 25:
                        num6 = 2667;
                        break;
                    case 26:
                        num6 = 2668;
                        break;
                    case 27:
                        num6 = 2825;
                        break;
                    case 28:
                        num6 = 3168;
                        break;
                    case 29:
                        num6 = 3170;
                        break;
                    case 30:
                        num6 = 3169;
                        break;
                    case 31:
                        num6 = 3893;
                        break;
                    case 32:
                        num6 = 3935;
                        break;
                    case 33:
                        num6 = 3961;
                        break;
                    case 34:
                        num6 = 4149;
                        break;
                    case 35:
                        num6 = 4170;
                        break;
                    case 36:
                        num6 = 4191;
                        break;
                    case 37:
                        num6 = 4212;
                        break;
                    case 38:
                        num6 = 4302;
                        break;
                    case 39:
                        num6 = 4570;
                        break;
                    case 40:
                        num6 = 5152;
                        break;
                    case 41:
                        num6 = 5173;
                        break;
                    case 42:
                        num6 = 5194;
                        break;
                    }
                    break;
                }
            }
            if (type == 173)
            {
                num6 = 714;
            }
            if (type == 125)
            {
                num6 = 487;
            }
            if (type == 287)
            {
                num6 = 2177;
            }
            if (type == 126)
            {
                num6 = 488;
            }
            if (type == 132)
            {
                num6 = 513;
            }
            if (type == 142)
            {
                num6 = 581;
            }
            if (type == 143)
            {
                num6 = 582;
            }
            if (type == 282)
            {
                num6 = 250;
            }
            if (type == 319)
            {
                num6 = 2490;
            }
            if (type == 490)
            {
                num6 = 4075;
            }
            if (type == 172)
            {
                num6 = 2827 + num12;
                switch (num12)
                {
                case 29:
                    num6 = 3147;
                    break;
                case 30:
                    num6 = 3149;
                    break;
                case 31:
                    num6 = 3148;
                    break;
                case 32:
                    num6 = 3896;
                    break;
                case 33:
                    num6 = 3946;
                    break;
                case 34:
                    num6 = 3972;
                    break;
                case 35:
                    num6 = 4160;
                    break;
                case 36:
                    num6 = 4181;
                    break;
                case 37:
                    num6 = 4202;
                    break;
                case 38:
                    num6 = 4223;
                    break;
                case 39:
                    num6 = 4312;
                    break;
                case 40:
                    num6 = 4581;
                    break;
                case 41:
                    num6 = 5163;
                    break;
                case 42:
                    num6 = 5184;
                    break;
                case 43:
                    num6 = 5205;
                    break;
                }
            }
            if (num6 != 0)
            {
                Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, num6);
            }
            if (!gen && Main.netMode != 1)
            {
                switch (type)
                {
                case 138:
                    Projectile.NewProjectile(GetProjectileSource_TileBreak(num9, num13), (float)(num9 * 16) + 15.5f, num13 * 16 + 16, 0f, 0f, 99, 70, 10f, Main.myPlayer);
                    break;
                case 484:
                    Projectile.NewProjectile(GetProjectileSource_TileBreak(num9, num13), (float)(num9 * 16) + 15.5f, num13 * 16 + 16, 0f, 0f, 727, 35, 10f, Main.myPlayer);
                    break;
                case 654:
                    Projectile.NewProjectile(GetProjectileSource_TileBreak(num9, num13), num9 * 16 + 8, num13 * 16 + 8, 0f, 0f, 1002, 400, 10f, Main.myPlayer);
                    break;
                case 664:
                    Projectile.NewProjectile(GetProjectileSource_TileBreak(num9, num13), (float)(num9 * 16) + 15.5f, num13 * 16 + 16, 0f, 0f, 1013, 70, 10f, Main.myPlayer);
                    break;
                case 665:
                    Projectile.NewProjectile(GetProjectileSource_TileBreak(num9, num13), (float)(num9 * 16) + 15.5f, num13 * 16 + 16, 0f, 0f, 1014, 70, 10f, Main.myPlayer);
                    break;
                }
            }
            destroyObject = false;
            for (int num7 = num9 - 1; num7 < num9 + 3; num7++)
            {
                for (int num8 = num13 - 1; num8 < num13 + 3; num8++)
                {
                    TileFrame(num7, num8);
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.BasicChest, Terraria.ID.TileID.Sets.BasicChestFake, Terraria.ID.TileID.Sets.BasicDresser, Terraria.Tile.bottomSlope(), Terraria.ID.TileID.Sets.Boulders, Terraria.ModLoader.TileLoader.Drop(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Framing.GetTileSafely(), Terraria.Tile.halfBrick(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Projectile.NewProjectile(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Main.tileTable, Terraria.Tile.type, and Terraria.Tile.wall.