TModLoader: Terraria.WorldGen.PlaceOasis
PlaceOasis()
static bool Terraria.WorldGen.PlaceOasis (int X, int Y) inline static
Definition at line 7517 of file WorldGen.cs.
    {
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_092e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0933: Unknown result type (might be due to invalid IL or missing references)
        int i = Y;
        if (!Main.tile[X, i].active() && Main.tile[X, i].wall == 0)
        {
            for (; !Main.tile[X, i].active() && Main.tile[X, i].wall == 0 && (double)i <= Main.worldSurface; i++)
            {
            }
            if ((double)i > Main.worldSurface - 10.0)
            {
                return false;
            }
            if (Main.tile[X, i].type != 53)
            {
                return false;
            }
            int num = 350;
            for (int j = 0; j < GenVars.numOasis; j++)
            {
                if (Vector2D.Distance(GenVars.oasisPosition[j].ToVector2D(), new Vector2D(X, i)) < (double)num)
                {
                    return false;
                }
            }
            int num11 = genRand.Next(45, 61);
            int oasisHeight = GenVars.oasisHeight;
            int num20 = num11 + 50;
            int num21 = 4;
            for (int k = X - num20; k <= X + num20; k++)
            {
                for (int l = i - oasisHeight; l <= i + oasisHeight + num21; l++)
                {
                    Tile tile = Main.tile[k, l];
                    if (tile.active())
                    {
                        if (Main.tileSolid[tile.type])
{
                            if ((tile.type == 151 || tile.type == 397) && Math.Abs(k - X) < num11 && Math.Abs(l - i) < oasisHeight / 2)
{
                                return false;
                            }
                            if (tile.type != 53)
{
                                return false;
                            }
                        }
                    }
                    else if ((tile.liquid > 0 || tile.wall > 0) && Math.Abs(k - X) < num11 && Math.Abs(l - i) < oasisHeight / 2)
                    {
                        return false;
                    }
                }
                if (k > X - num11 / 2 && k < X - num11 / 2)
                {
                    if (Main.tile[k, i - 6].active())
                    {
                        return false;
                    }
                    if (!Main.tile[k, i + 1].active())
                    {
                        return false;
                    }
                }
            }
            int num22 = 5;
            int num23 = i;
            while (!Main.tile[X - num11, i + num22].active() || Main.tile[X - num11, i + num22].wall != 0 || !Main.tile[X + num11, i + num22].active() || Main.tile[X + num11, i + num22].wall != 0)
            {
                i++;
                if (i - num23 > 20)
                {
                    break;
                }
            }
            int num24 = num11 / 2;
            int num25 = X - num11 * 3;
            int num26 = X + num11 * 3;
            int num2 = i - oasisHeight * 4;
            int num3 = i + oasisHeight * 3;
            if (num25 < 0)
            {
                num25 = 0;
            }
            if (num26 > Main.maxTilesX)
            {
                num26 = Main.maxTilesX;
            }
            if (num2 < 0)
            {
                num2 = 0;
            }
            if (num3 > Main.maxTilesY)
            {
                num3 = Main.maxTilesY;
            }
            for (int m = num25; m < num26; m++)
            {
                for (int n = num2; n < num3; n++)
                {
                    double num4 = (double)Math.Abs(m - X) * 0.7;
                    double num5 = (double)Math.Abs(n - i) * 1.35;
                    double num27 = Math.Sqrt(num4 * num4 + num5 * num5);
                    double num6 = (double)num24 * (0.53 + genRand.NextDouble() * 0.04);
                    double num7 = (double)Math.Abs(m - X) / (double)(num26 - X);
                    num7 = 1.0 - num7;
                    num7 *= 2.3;
                    num7 *= num7;
                    num7 *= num7;
                    if (num27 < num6)
                    {
                        if (n == i + 1)
{
                            Main.tile[m, n].liquid = 127;
                        }
                        else if (n > i + 1)
{
                            Main.tile[m, n].liquid = byte.MaxValue;
                        }
                        Main.tile[m, n].lava(lava: false);
                        Main.tile[m, n].active(active: false);
                    }
                    else if (n < i && num4 < num6 + (double)(Math.Abs(n - i) * 3) * num7)
                    {
                        if (Main.tile[m, n].type == 53)
{
                            Main.tile[m, n].active(active: false);
                        }
                    }
                    else if (n >= i && num4 < num6 + (double)Math.Abs(n - i) * num7 && Main.tile[m, n].wall == 0)
                    {
                        if (Main.tile[m, n].active() && Main.tileSolid[Main.tile[m, n].type] && !Main.tileSolidTop[Main.tile[m, n].type])
{
                            Main.tile[m, n].slope(0);
                            Main.tile[m, n].halfBrick(halfBrick: false);
                            continue;
                        }
                        Main.tile[m, n].active(active: true);
                        Main.tile[m, n].type = 53;
                        Main.tile[m, n].slope(0);
                        Main.tile[m, n].halfBrick(halfBrick: false);
                    }
                }
            }
            int num8 = 50;
            num25 = X - num11 * 2;
            num26 = X + num11 * 2;
            num3 = i + oasisHeight * 2;
            for (int num9 = num25; num9 < num26; num9++)
            {
                for (int num10 = num3; num10 >= i; num10--)
                {
                    double num28 = (double)Math.Abs(num9 - X) * 0.7;
                    double num12 = (double)Math.Abs(num10 - i) * 1.35;
                    double num29 = Math.Sqrt(num28 * num28 + num12 * num12);
                    double num13 = (double)num24 * 0.5700000000000001;
                    if (num29 > num13)
                    {
                        bool flag = false;
                        if (!Main.tile[num9, num10].active() && Main.tile[num9, num10].wall == 0)
{
                            int num14 = -1;
                            int num15 = -1;
                            for (int num16 = num9; num16 <= num9 + num8 && Main.tile[num16, num10 + 1].active() && Main.tileSolid[Main.tile[num16, num10 + 1].type] && Main.tile[num16, num10].wall <= 0; num16++)
{
                                if (Main.tile[num16, num10].active() && Main.tileSolid[Main.tile[num16, num10].type])
{
                                    if (Main.tile[num16, num10].type == 53)
{
                                        flag = true;
                                    }
                                    num15 = num16;
                                    break;
                                }
                                if (Main.tile[num16, num10].active())
{
                                    break;
                                }
                            }
                            int num17 = num9;
                            while (num17 >= num9 - num8 && Main.tile[num17, num10 + 1].active() && Main.tileSolid[Main.tile[num17, num10 + 1].type] && Main.tile[num17, num10].wall <= 0)
{
                                if (Main.tile[num17, num10].active() && Main.tileSolid[Main.tile[num17, num10].type])
{
                                    if (Main.tile[num17, num10].type == 53)
{
                                        flag = true;
                                    }
                                    num14 = num17;
                                    break;
                                }
                                if (Main.tile[num17, num10].active())
{
                                    break;
                                }
                                num17--;
                            }
                            flag = true;
                            if (num14 > -1 && num15 > -1 && flag)
{
                                int num18 = 0;
                                for (int num19 = num14 + 1; num19 < num15; num19++)
{
                                    if (num15 - num14 > 5 && genRand.Next(5) == 0)
{
                                        num18 = genRand.Next(5, 10);
                                    }
                                    Main.tile[num19, num10].active(active: true);
                                    Main.tile[num19, num10].type = 53;
                                    if (num18 > 0)
{
                                        num18--;
                                        Main.tile[num19, num10 - 1].active(active: true);
                                        Main.tile[num19, num10 - 1].type = 53;
                                    }
                                }
                            }
                        }
                    }
                }
            }
            if (GenVars.numOasis < GenVars.maxOasis)
            {
                GenVars.oasisPosition[GenVars.numOasis] = new Point(X, i);
                GenVars.oasisWidth[GenVars.numOasis] = num11;
                GenVars.numOasis++;
            }
            return true;
        }
        return false;
    }
References Terraria.Tile.active(), Terraria.WorldGen.genRand, Terraria.Tile.liquid, Terraria.WorldBuilding.GenVars.maxOasis, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.WorldBuilding.GenVars.numOasis, Terraria.WorldBuilding.GenVars.oasisHeight, Terraria.WorldBuilding.GenVars.oasisPosition, Terraria.WorldBuilding.GenVars.oasisWidth, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.worldSurface.