TModLoader: Terraria.WorldGen.PaintThePurityGrass
PaintThePurityGrass()
static void Terraria.WorldGen.PaintThePurityGrass (byte tilePaintColor, byte wallPaintColor) inline static private
Definition at line 18075 of file WorldGen.cs.
    {
        for (int i = 0; i < Main.maxTilesX; i++)
        {
            for (int j = 0; j < Main.maxTilesY; j++)
            {
                Tile tile = Main.tile[i, j];
                if (tile.active())
                {
                    if (tile.type == 2)
                    {
                        tile.color(tilePaintColor);
                    }
                    else if (tile.type == 185 || tile.type == 186 || tile.type == 187)
                    {
                        Tile tile2 = tile;
                        int num = j;
                        while (num < Main.maxTilesY - 20 && (tile2.type == 185 || tile2.type == 186 || tile2.type == 187 || tile2.type == 3 || tile2.type == 73))
{
                            tile2 = Main.tile[i, ++num];
                        }
                        if (tile2.type == 2)
{
                            tile.color(tilePaintColor);
                        }
                    }
                }
                if (tile.wall == 66 || tile.wall == 63)
                {
                    tile.wallColor(wallPaintColor);
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Tile.wallColor().