TModLoader: Terraria.WorldGen.mayanTrap
mayanTrap()
static bool Terraria.WorldGen.mayanTrap (int x2, int y2) inline static
Definition at line 4967 of file WorldGen.cs.
    {
        int num = 1;
        if (genRand.Next(3) == 0)
        {
            num = 0;
        }
        int num12 = y2;
        while (!SolidOrSlopedTile(x2, num12))
        {
            num12++;
            if (num12 >= Main.maxTilesY - 300)
            {
                return false;
            }
        }
        Tile tile = Main.tile[x2, num12];
        if (tile.type != 232)
        {
            tile = Main.tile[x2, num12];
            if (tile.type != 10)
            {
                num12--;
                tile = Main.tile[x2, num12];
                if (tile.liquid > 0)
                {
                    tile = Main.tile[x2, num12];
                    if (tile.lava())
                    {
                        return false;
                    }
                }
                if (num == -1 && genRand.Next(20) == 0)
                {
                    num = 2;
                }
                else if (num == -1)
                {
                    num = genRand.Next(2);
                }
                tile = Main.tile[x2, num12];
                if (!tile.nactive())
                {
                    tile = Main.tile[x2 - 1, num12];
                    if (!tile.nactive())
                    {
                        tile = Main.tile[x2 + 1, num12];
                        if (!tile.nactive())
{
                            tile = Main.tile[x2, num12 - 1];
                            if (!tile.nactive())
{
                                tile = Main.tile[x2 - 1, num12 - 1];
                                if (!tile.nactive())
{
                                    tile = Main.tile[x2 + 1, num12 - 1];
                                    if (!tile.nactive())
{
                                        tile = Main.tile[x2, num12 - 2];
                                        if (!tile.nactive())
{
                                            tile = Main.tile[x2 - 1, num12 - 2];
                                            if (!tile.nactive())
{
                                                tile = Main.tile[x2 + 1, num12 - 2];
                                                if (!tile.nactive())
{
                                                    tile = Main.tile[x2, num12 + 1];
                                                    if (tile.type == 10)
{
                                                        return false;
                                                    }
                                                    tile = Main.tile[x2, num12 + 1];
                                                    if (tile.type == 48)
{
                                                        return false;
                                                    }
                                                    tile = Main.tile[x2, num12 + 1];
                                                    if (tile.type == 232)
{
                                                        return false;
                                                    }
                                                    int num5;
                                                    int num6;
                                                    int num7;
                                                    bool flag;
                                                    bool flag2;
                                                    int num10;
                                                    int num4;
                                                    int num11;
                                                    int num23;
                                                    int style2;
                                                    int num13;
                                                    int num14;
                                                    int num15;
                                                    int num16;
                                                    switch (num)
{
                                                    case 0:
{
                                                        num4 = x2;
                                                        num5 = num12;
                                                        num5 -= genRand.Next(3);
                                                        while (InWorld(num4, num5, 5) && !SolidOrSlopedTile(num4, num5))
{
                                                            num4--;
                                                        }
                                                        num6 = num4;
                                                        for (num4 = x2; InWorld(num4, num5, 5) && !SolidOrSlopedTile(num4, num5); num4++)
{
                                                        }
                                                        num7 = num4;
                                                        int num8 = x2 - num6;
                                                        int num9 = num7 - x2;
                                                        flag = false;
                                                        flag2 = false;
                                                        if (num8 > 5 && num8 < 50)
{
                                                            flag = true;
                                                        }
                                                        if (num9 > 5 && num9 < 50)
{
                                                            flag2 = true;
                                                        }
                                                        if (flag && !SolidOrSlopedTile(num6, num5 + 1))
{
                                                            flag = false;
                                                        }
                                                        if (flag2 && !SolidOrSlopedTile(num7, num5 + 1))
{
                                                            flag2 = false;
                                                        }
                                                        if (flag)
{
                                                            tile = Main.tile[num6, num5];
                                                            if (tile.type != 10)
{
                                                                tile = Main.tile[num6, num5];
                                                                if (tile.type != 48)
{
                                                                    tile = Main.tile[num6, num5 + 1];
                                                                    if (tile.type != 10)
{
                                                                        tile = Main.tile[num6, num5 + 1];
                                                                        if (tile.type != 48)
{
                                                                            goto IL_0338;
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                            flag = false;
                                                        }
                                                        goto IL_0338;
                                                    }
                                                    case 1:
{
                                                        int num17 = num12;
                                                        while (!SolidOrSlopedTile(x2, num17))
{
                                                            num17--;
                                                            if ((double)num17 < Main.worldSurface)
{
                                                                return false;
                                                            }
                                                        }
                                                        int num18 = Math.Abs(num17 - num12);
                                                        if (num18 < 3)
{
                                                            return false;
                                                        }
                                                        int num19 = genRand.Next(3);
                                                        tile = Main.tile[x2, num12];
                                                        if (tile.wire())
{
                                                            num19 = 0;
                                                        }
                                                        tile = Main.tile[x2, num12];
                                                        if (tile.wire2())
{
                                                            num19 = 1;
                                                        }
                                                        tile = Main.tile[x2, num12];
                                                        if (tile.wire3())
{
                                                            num19 = 2;
                                                        }
                                                        int style = 3;
                                                        if (num18 < 16 && genRand.Next(3) != 0)
{
                                                            style = 4;
                                                        }
                                                        tile = Main.tile[x2, num17];
                                                        if (tile.type == 135)
{
                                                            return false;
                                                        }
                                                        tile = Main.tile[x2, num17];
                                                        if (tile.type == 137)
{
                                                            return false;
                                                        }
                                                        tile = Main.tile[x2, num17];
                                                        if (tile.type == 232)
{
                                                            return false;
                                                        }
                                                        tile = Main.tile[x2, num17];
                                                        if (tile.type == 237)
{
                                                            return false;
                                                        }
                                                        tile = Main.tile[x2, num17];
                                                        if (tile.type == 10)
{
                                                            return false;
                                                        }
                                                        tile = Main.tile[x2, num17];
                                                        if (tile.wall != 87)
{
                                                            return false;
                                                        }
                                                        PlaceTile(x2, num12, 135, mute: true, forced: true, -1, 6);
                                                        PlaceTile(x2, num17, 137, mute: true, forced: true, -1, style);
                                                        for (int i = 0; i < 2; i++)
{
                                                            int num20 = genRand.Next(1, 5);
                                                            int num21 = x2;
                                                            int num22 = -1;
                                                            if (i == 1)
{
                                                                num22 = 1;
                                                            }
                                                            while (num20 > 0)
{
                                                                num20--;
                                                                num21 += num22;
                                                                if (!SolidTile(num21, num17 - 1) || SolidOrSlopedTile(num21, num17 + 1))
{
                                                                    break;
                                                                }
                                                                PlaceTile(num21, num17, 137, mute: true, forced: true, -1, style);
                                                                switch (num19)
{
                                                                case 0:
                                                                    tile = Main.tile[num21, num17];
                                                                    tile.wire(wire: true);
                                                                    break;
                                                                case 1:
                                                                    tile = Main.tile[num21, num17];
                                                                    tile.wire2(wire2: true);
                                                                    break;
                                                                case 2:
                                                                    tile = Main.tile[num21, num17];
                                                                    tile.wire3(wire3: true);
                                                                    break;
                                                                }
                                                            }
                                                        }
                                                        int num2 = x2;
                                                        int num3 = num12;
                                                        while (num2 != x2 || num3 != num17)
{
                                                            switch (num19)
{
                                                            case 0:
                                                                tile = Main.tile[num2, num3];
                                                                tile.wire(wire: true);
                                                                break;
                                                            case 1:
                                                                tile = Main.tile[num2, num3];
                                                                tile.wire2(wire2: true);
                                                                break;
                                                            case 2:
                                                                tile = Main.tile[num2, num3];
                                                                tile.wire3(wire3: true);
                                                                break;
                                                            }
                                                            if (num2 > x2)
{
                                                                num2--;
                                                            }
                                                            if (num2 < x2)
{
                                                                num2++;
                                                            }
                                                            switch (num19)
{
                                                            case 0:
                                                                tile = Main.tile[num2, num3];
                                                                tile.wire(wire: true);
                                                                break;
                                                            case 1:
                                                                tile = Main.tile[num2, num3];
                                                                tile.wire2(wire2: true);
                                                                break;
                                                            case 2:
                                                                tile = Main.tile[num2, num3];
                                                                tile.wire3(wire3: true);
                                                                break;
                                                            }
                                                            if (num3 > num17)
{
                                                                num3--;
                                                            }
                                                            if (num3 < num17)
{
                                                                num3++;
                                                            }
                                                            switch (num19)
{
                                                            case 0:
                                                                tile = Main.tile[num2, num3];
                                                                tile.wire(wire: true);
                                                                break;
                                                            case 1:
                                                                tile = Main.tile[num2, num3];
                                                                tile.wire2(wire2: true);
                                                                break;
                                                            case 2:
                                                                tile = Main.tile[num2, num3];
                                                                tile.wire3(wire3: true);
                                                                break;
                                                            }
                                                        }
                                                        return true;
                                                    }
                                                    default:
{
                                                            return false;
                                                        }
                                                        IL_03af:
                                                        num10 = 0;
                                                        if (flag && flag2)
{
                                                            num10 = 1;
                                                            num4 = num6;
                                                            if (genRand.Next(2) == 0)
{
                                                                num4 = num7;
                                                                num10 = -1;
                                                            }
                                                        }
                                                        else if (flag2)
{
                                                            num4 = num7;
                                                            num10 = -1;
                                                        }
                                                        else
{
                                                            if (!flag)
{
                                                                return false;
                                                            }
                                                            num4 = num6;
                                                            num10 = 1;
                                                        }
                                                        tile = Main.tile[num4, num5];
                                                        if (tile.wall != 87)
{
                                                            return false;
                                                        }
                                                        tile = Main.tile[num4, num5];
                                                        if (tile.type == 190)
{
                                                            return false;
                                                        }
                                                        tile = Main.tile[num4, num5];
                                                        if (tile.type == 135)
{
                                                            return false;
                                                        }
                                                        tile = Main.tile[num4, num5];
                                                        if (tile.type == 137)
{
                                                            return false;
                                                        }
                                                        tile = Main.tile[num4, num5];
                                                        if (tile.type == 232)
{
                                                            return false;
                                                        }
                                                        tile = Main.tile[num4, num5];
                                                        if (tile.type == 237)
{
                                                            return false;
                                                        }
                                                        tile = Main.tile[num4, num5];
                                                        if (tile.type == 10)
{
                                                            return false;
                                                        }
                                                        PlaceTile(x2, num12, 135, mute: true, forced: true, -1, 6);
                                                        KillTile(num4, num5);
                                                        num11 = genRand.Next(3);
                                                        tile = Main.tile[x2, num12];
                                                        if (tile.wire())
{
                                                            num11 = 0;
                                                        }
                                                        tile = Main.tile[x2, num12];
                                                        if (tile.wire2())
{
                                                            num11 = 1;
                                                        }
                                                        tile = Main.tile[x2, num12];
                                                        if (tile.wire3())
{
                                                            num11 = 2;
                                                        }
                                                        num23 = Math.Abs(num4 - x2);
                                                        style2 = 1;
                                                        if (num23 < 10 && genRand.Next(3) != 0)
{
                                                            style2 = 2;
                                                        }
                                                        PlaceTile(num4, num5, 137, mute: true, forced: true, -1, style2);
                                                        if (num10 == 1)
{
                                                            tile = Main.tile[num4, num5];
                                                            tile.frameX += 18;
                                                        }
                                                        num13 = genRand.Next(5);
                                                        num14 = num5;
                                                        while (num13 > 0)
{
                                                            num13--;
                                                            num14--;
                                                            if (!SolidTile(num4, num14) || !SolidTile(num4 - num10, num14) || SolidOrSlopedTile(num4 + num10, num14))
{
                                                                break;
                                                            }
                                                            PlaceTile(num4, num14, 137, mute: true, forced: true, -1, style2);
                                                            if (num10 == 1)
{
                                                                tile = Main.tile[num4, num14];
                                                                tile.frameX += 18;
                                                            }
                                                            switch (num11)
{
                                                            case 0:
                                                                tile = Main.tile[num4, num14];
                                                                tile.wire(wire: true);
                                                                break;
                                                            case 1:
                                                                tile = Main.tile[num4, num14];
                                                                tile.wire2(wire2: true);
                                                                break;
                                                            case 2:
                                                                tile = Main.tile[num4, num14];
                                                                tile.wire3(wire3: true);
                                                                break;
                                                            }
                                                        }
                                                        num15 = x2;
                                                        num16 = num12;
                                                        while (num15 != num4 || num16 != num5)
{
                                                            switch (num11)
{
                                                            case 0:
                                                                tile = Main.tile[num15, num16];
                                                                tile.wire(wire: true);
                                                                break;
                                                            case 1:
                                                                tile = Main.tile[num15, num16];
                                                                tile.wire2(wire2: true);
                                                                break;
                                                            case 2:
                                                                tile = Main.tile[num15, num16];
                                                                tile.wire3(wire3: true);
                                                                break;
                                                            }
                                                            if (num15 > num4)
{
                                                                num15--;
                                                            }
                                                            if (num15 < num4)
{
                                                                num15++;
                                                            }
                                                            switch (num11)
{
                                                            case 0:
                                                                tile = Main.tile[num15, num16];
                                                                tile.wire(wire: true);
                                                                break;
                                                            case 1:
                                                                tile = Main.tile[num15, num16];
                                                                tile.wire2(wire2: true);
                                                                break;
                                                            case 2:
                                                                tile = Main.tile[num15, num16];
                                                                tile.wire3(wire3: true);
                                                                break;
                                                            }
                                                            if (num16 > num5)
{
                                                                num16--;
                                                            }
                                                            if (num16 < num5)
{
                                                                num16++;
                                                            }
                                                            switch (num11)
{
                                                            case 0:
                                                                tile = Main.tile[num15, num16];
                                                                tile.wire(wire: true);
                                                                break;
                                                            case 1:
                                                                tile = Main.tile[num15, num16];
                                                                tile.wire2(wire2: true);
                                                                break;
                                                            case 2:
                                                                tile = Main.tile[num15, num16];
                                                                tile.wire3(wire3: true);
                                                                break;
                                                            }
                                                        }
                                                        return true;
                                                        IL_0338:
                                                        if (flag2)
{
                                                            tile = Main.tile[num7, num5];
                                                            if (tile.type != 10)
{
                                                                tile = Main.tile[num7, num5];
                                                                if (tile.type != 48)
{
                                                                    tile = Main.tile[num7, num5 + 1];
                                                                    if (tile.type != 10)
{
                                                                        tile = Main.tile[num7, num5 + 1];
                                                                        if (tile.type != 48)
{
                                                                            goto IL_03af;
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                            flag2 = false;
                                                        }
                                                        goto IL_03af;
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                return false;
            }
        }
        return false;
    }
References Terraria.WorldGen.genRand, Terraria.WorldGen.InWorld(), Terraria.WorldGen.KillTile(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.SolidOrSlopedTile(), Terraria.Enums.SolidTile, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), and Terraria.Main.worldSurface.