TModLoader: Terraria.WorldGen.MineHouse
MineHouse()
static void Terraria.WorldGen.MineHouse (int i, int j) inline static
    {
        if (i < 50 || i > Main.maxTilesX - 50 || j < 50 || j > Main.maxTilesY - 50)
        {
            return;
        }
        int num = genRand.Next(6, 12);
        int num12 = genRand.Next(3, 6);
        int num23 = genRand.Next(15, 30);
        int num34 = genRand.Next(15, 30);
        if (SolidTile(i, j))
        {
            return;
        }
        Tile tile = Main.tile[i, j];
        if (tile.wall > 0)
        {
            return;
        }
        int num44 = j - num;
        int num55 = j + num12;
        for (int k = 0; k < 2; k++)
        {
            bool flag = true;
            int num66 = i;
            int num71 = j;
            int num72 = -1;
            int num2 = num23;
            if (k == 1)
            {
                num72 = 1;
                num2 = num34;
                num66++;
            }
            while (flag)
            {
                if (num71 - num < num44)
                {
                    num44 = num71 - num;
                }
                if (num71 + num12 > num55)
                {
                    num55 = num71 + num12;
                }
                for (int l = 0; l < 2; l++)
                {
                    int num3 = num71;
                    bool flag2 = true;
                    int num4 = num;
                    int num5 = -1;
                    if (l == 1)
                    {
                        num3++;
                        num4 = num12;
                        num5 = 1;
                    }
                    while (flag2)
                    {
                        if (num66 != i)
{
                            tile = Main.tile[num66 - num72, num3];
                            if (tile.wall != 27)
{
                                if (!SolidTile(num66 - num72, num3))
{
                                    tile = Main.tile[num66 - num72, num3];
                                    if (tile.active())
{
                                        tile = Main.tile[num66 - num72, num3];
                                        if (!tile.halfBrick())
{
                                            tile = Main.tile[num66 - num72, num3];
                                            if (tile.slope() == 0)
{
                                                goto IL_01c7;
                                            }
                                        }
                                    }
                                }
                                tile = Main.tile[num66 - num72, num3];
                                tile.active(active: true);
                                tile = Main.tile[num66 - num72, num3];
                                tile.type = 30;
                            }
                        }
                        goto IL_01c7;
                        IL_03a4:
                        num3 += num5;
                        num4--;
                        if (num4 <= 0)
{
                            tile = Main.tile[num66, num3];
                            if (!tile.active())
{
                                tile = Main.tile[num66, num3];
                                tile.active(active: true);
                                tile = Main.tile[num66, num3];
                                tile.type = 30;
                            }
                            flag2 = false;
                        }
                        continue;
                        IL_0227:
                        if (!SolidTile(num66 + 1, num3))
{
                            tile = Main.tile[num66 + 1, num3];
                            if (!tile.halfBrick())
{
                                tile = Main.tile[num66 + 1, num3];
                                if (tile.slope() == 0)
{
                                    goto IL_0287;
                                }
                            }
                        }
                        tile = Main.tile[num66 + 1, num3];
                        tile.type = 30;
                        goto IL_0287;
                        IL_01c7:
                        if (!SolidTile(num66 - 1, num3))
{
                            tile = Main.tile[num66 - 1, num3];
                            if (!tile.halfBrick())
{
                                tile = Main.tile[num66 - 1, num3];
                                if (tile.slope() == 0)
{
                                    goto IL_0227;
                                }
                            }
                        }
                        tile = Main.tile[num66 - 1, num3];
                        tile.type = 30;
                        goto IL_0227;
                        IL_0287:
                        if (!SolidTile(num66, num3))
{
                            tile = Main.tile[num66, num3];
                            if (!tile.halfBrick())
{
                                tile = Main.tile[num66, num3];
                                if (tile.slope() == 0)
{
                                    tile = Main.tile[num66, num3];
                                    tile.wall = 27;
                                    tile = Main.tile[num66, num3];
                                    tile.liquid = 0;
                                    tile = Main.tile[num66, num3];
                                    tile.lava(lava: false);
                                    goto IL_03a4;
                                }
                            }
                        }
                        int num6 = 0;
                        if (SolidTile(num66 - 1, num3))
{
                            num6++;
                        }
                        if (SolidTile(num66 + 1, num3))
{
                            num6++;
                        }
                        if (SolidTile(num66, num3 - 1))
{
                            num6++;
                        }
                        if (SolidTile(num66, num3 + 1))
{
                            num6++;
                        }
                        if (num6 < 2)
{
                            tile = Main.tile[num66, num3];
                            tile.active(active: false);
                        }
                        else
{
                            flag2 = false;
                            tile = Main.tile[num66, num3];
                            tile.type = 30;
                        }
                        goto IL_03a4;
                    }
                }
                num2--;
                num66 += num72;
                if (SolidTile(num66, num71))
                {
                    int num7 = 0;
                    int num8 = 0;
                    int num9 = num71;
                    bool flag3 = true;
                    while (flag3)
                    {
                        num9--;
                        num7++;
                        if (SolidTile(num66 - num72, num9))
{
                            num7 = 999;
                            flag3 = false;
                        }
                        else if (!SolidTile(num66, num9))
{
                            flag3 = false;
                        }
                    }
                    num9 = num71;
                    flag3 = true;
                    while (flag3)
                    {
                        num9++;
                        num8++;
                        if (SolidTile(num66 - num72, num9))
{
                            num8 = 999;
                            flag3 = false;
                        }
                        else if (!SolidTile(num66, num9))
{
                            flag3 = false;
                        }
                    }
                    if (num8 <= num7)
                    {
                        if (num8 > num12)
{
                            num2 = 0;
                        }
                        else
{
                            num71 += num8 + 1;
                        }
                    }
                    else if (num7 > num)
                    {
                        num2 = 0;
                    }
                    else
                    {
                        num71 -= num7 + 1;
                    }
                }
                if (num2 <= 0)
                {
                    flag = false;
                }
            }
        }
        int num10 = i - num23 - 1;
        int num11 = i + num34 + 2;
        int num13 = num44 - 1;
        int num14 = num55 + 2;
        for (int m = num10; m < num11; m++)
        {
            for (int n = num13; n < num14; n++)
            {
                tile = Main.tile[m, n];
                if (tile.wall == 27)
                {
                    tile = Main.tile[m, n];
                    if (!tile.active())
                    {
                        tile = Main.tile[m - 1, n];
                        if (tile.wall != 27 && m < i && !SolidTile(m - 1, n))
{
                            PlaceTile(m, n, 30, mute: true);
                            tile = Main.tile[m, n];
                            tile.wall = 0;
                        }
                        tile = Main.tile[m + 1, n];
                        if (tile.wall != 27 && m > i && !SolidTile(m + 1, n))
{
                            PlaceTile(m, n, 30, mute: true);
                            tile = Main.tile[m, n];
                            tile.wall = 0;
                        }
                        for (int num15 = m - 1; num15 <= m + 1; num15++)
{
                            for (int num16 = n - 1; num16 <= n + 1; num16++)
{
                                if (SolidTile(num15, num16))
{
                                    tile = Main.tile[num15, num16];
                                    tile.type = 30;
                                }
                            }
                        }
                    }
                }
                tile = Main.tile[m, n];
                if (tile.type != 30)
                {
                    continue;
                }
                tile = Main.tile[m - 1, n];
                if (tile.wall != 27)
                {
                    continue;
                }
                tile = Main.tile[m + 1, n];
                if (tile.wall != 27)
                {
                    continue;
                }
                tile = Main.tile[m, n - 1];
                if (tile.wall != 27)
                {
                    tile = Main.tile[m, n - 1];
                    if (!tile.active())
                    {
                        continue;
                    }
                }
                tile = Main.tile[m, n + 1];
                if (tile.wall != 27)
                {
                    tile = Main.tile[m, n + 1];
                    if (!tile.active())
                    {
                        continue;
                    }
                }
                tile = Main.tile[m, n];
                tile.active(active: false);
                tile = Main.tile[m, n];
                tile.wall = 27;
            }
        }
        for (int num17 = num10; num17 < num11; num17++)
        {
            for (int num18 = num13; num18 < num14; num18++)
            {
                tile = Main.tile[num17, num18];
                if (tile.type != 30)
                {
                    continue;
                }
                tile = Main.tile[num17 - 1, num18];
                if (tile.wall == 27)
                {
                    tile = Main.tile[num17 + 1, num18];
                    if (tile.wall == 27)
                    {
                        tile = Main.tile[num17 - 1, num18];
                        if (!tile.active())
{
                            tile = Main.tile[num17 + 1, num18];
                            if (!tile.active())
{
                                tile = Main.tile[num17, num18];
                                tile.active(active: false);
                                tile = Main.tile[num17, num18];
                                tile.wall = 27;
                            }
                        }
                    }
                }
                bool[] basicChest = TileID.Sets.BasicChest;
                tile = Main.tile[num17, num18 - 1];
                if (!basicChest[tile.type])
                {
                    tile = Main.tile[num17 - 1, num18];
                    if (tile.wall == 27)
                    {
                        tile = Main.tile[num17 + 1, num18];
                        if (tile.type == 30)
{
                            tile = Main.tile[num17 + 2, num18];
                            if (tile.wall == 27)
{
                                tile = Main.tile[num17 - 1, num18];
                                if (!tile.active())
{
                                    tile = Main.tile[num17 + 2, num18];
                                    if (!tile.active())
{
                                        tile = Main.tile[num17, num18];
                                        tile.active(active: false);
                                        tile = Main.tile[num17, num18];
                                        tile.wall = 27;
                                        tile = Main.tile[num17 + 1, num18];
                                        tile.active(active: false);
                                        tile = Main.tile[num17 + 1, num18];
                                        tile.wall = 27;
                                    }
                                }
                            }
                        }
                    }
                }
                tile = Main.tile[num17, num18 - 1];
                if (tile.wall != 27)
                {
                    continue;
                }
                tile = Main.tile[num17, num18 + 1];
                if (tile.wall != 27)
                {
                    continue;
                }
                tile = Main.tile[num17, num18 - 1];
                if (!tile.active())
                {
                    tile = Main.tile[num17, num18 + 1];
                    if (!tile.active())
                    {
                        tile = Main.tile[num17, num18];
                        tile.active(active: false);
                        tile = Main.tile[num17, num18];
                        tile.wall = 27;
                    }
                }
            }
        }
        for (int num19 = num10; num19 < num11; num19++)
        {
            for (int num20 = num14; num20 > num13; num20--)
            {
                bool flag4 = false;
                tile = Main.tile[num19, num20];
                if (tile.active())
                {
                    tile = Main.tile[num19, num20];
                    if (tile.type == 30)
                    {
                        int num21 = -1;
                        for (int num22 = 0; num22 < 2; num22++)
{
                            if (!SolidTile(num19 + num21, num20))
{
                                tile = Main.tile[num19 + num21, num20];
                                if (tile.wall == 0)
{
                                    int num24 = 0;
                                    int num25 = num20;
                                    int num26 = num20;
                                    while (true)
{
                                        tile = Main.tile[num19, num25];
                                        if (!tile.active())
{
                                            break;
                                        }
                                        tile = Main.tile[num19, num25];
                                        if (tile.type != 30 || SolidTile(num19 + num21, num25))
{
                                            break;
                                        }
                                        tile = Main.tile[num19 + num21, num25];
                                        if (tile.wall != 0)
{
                                            break;
                                        }
                                        num25--;
                                        num24++;
                                    }
                                    num25++;
                                    int num27 = num25 + 1;
                                    if (num24 > 4)
{
                                        if (genRand.Next(2) == 0)
{
                                            num25 = num26 - 1;
                                            bool flag5 = true;
                                            for (int num28 = num19 - 2; num28 <= num19 + 2; num28++)
{
                                                for (int num29 = num25 - 2; num29 <= num25; num29++)
{
                                                    if (num28 != num19)
{
                                                        tile = Main.tile[num28, num29];
                                                        if (tile.active())
{
                                                            flag5 = false;
                                                        }
                                                    }
                                                }
                                            }
                                            if (flag5)
{
                                                tile = Main.tile[num19, num25];
                                                tile.active(active: false);
                                                tile = Main.tile[num19, num25 - 1];
                                                tile.active(active: false);
                                                tile = Main.tile[num19, num25 - 2];
                                                tile.active(active: false);
                                                PlaceTile(num19, num25, 10, mute: true);
                                                flag4 = true;
                                            }
                                        }
                                        if (!flag4)
{
                                            for (int num30 = num27; num30 < num26; num30++)
{
                                                tile = Main.tile[num19, num30];
                                                tile.type = 124;
                                            }
                                        }
                                    }
                                }
                            }
                            num21 = 1;
                        }
                    }
                }
                if (flag4)
                {
                    break;
                }
            }
        }
        int num31 = genRand.Next(1, 2);
        if (genRand.Next(4) == 0)
        {
            num31 = 0;
        }
        if (genRand.Next(6) == 0)
        {
            num31++;
        }
        if (genRand.Next(10) == 0)
        {
            num31++;
        }
        for (int num32 = 0; num32 < num31; num32++)
        {
            int num33 = 0;
            int num35 = genRand.Next(num10, num11);
            int num36 = genRand.Next(num13, num14);
            while (true)
            {
                bool[] wallHouse = Main.wallHouse;
                tile = Main.tile[num35, num36];
                if (wallHouse[tile.wall])
                {
                    tile = Main.tile[num35, num36];
                    if (!tile.active())
                    {
                        break;
                    }
                }
                num33++;
                if (num33 > 1000)
                {
                    break;
                }
                num35 = genRand.Next(num10, num11);
                num36 = genRand.Next(num13, num14);
            }
            if (num33 > 1000)
            {
                break;
            }
            int num37 = num35;
            int num38 = num35;
            int num39 = num36;
            int num40 = num36;
            int num41 = 0;
            for (int num42 = 0; num42 < 2; num42++)
            {
                num37 = num35;
                num38 = num35;
                while (true)
                {
                    tile = Main.tile[num37, num36];
                    if (tile.active())
                    {
                        break;
                    }
                    bool[] wallHouse2 = Main.wallHouse;
                    tile = Main.tile[num37, num36];
                    if (!wallHouse2[tile.wall])
                    {
                        break;
                    }
                    num37--;
                }
                num37++;
                while (true)
                {
                    tile = Main.tile[num38, num36];
                    if (tile.active())
                    {
                        break;
                    }
                    bool[] wallHouse3 = Main.wallHouse;
                    tile = Main.tile[num38, num36];
                    if (!wallHouse3[tile.wall])
                    {
                        break;
                    }
                    num38++;
                }
                num38--;
                i = (num37 + num38) / 2;
                num39 = num36;
                num40 = num36;
                while (true)
                {
                    tile = Main.tile[num35, num39];
                    if (tile.active())
                    {
                        break;
                    }
                    bool[] wallHouse4 = Main.wallHouse;
                    tile = Main.tile[num35, num39];
                    if (!wallHouse4[tile.wall])
                    {
                        break;
                    }
                    num39--;
                }
                num39++;
                while (true)
                {
                    tile = Main.tile[num35, num40];
                    if (tile.active())
                    {
                        break;
                    }
                    bool[] wallHouse5 = Main.wallHouse;
                    tile = Main.tile[num35, num40];
                    if (!wallHouse5[tile.wall])
                    {
                        break;
                    }
                    num40++;
                }
                num40--;
                num36 = (num39 + num40) / 2;
            }
            num37 = num35;
            num38 = num35;
            while (true)
            {
                tile = Main.tile[num37, num36];
                if (tile.active())
                {
                    break;
                }
                tile = Main.tile[num37, num36 - 1];
                if (tile.active())
                {
                    break;
                }
                tile = Main.tile[num37, num36 + 1];
                if (tile.active())
                {
                    break;
                }
                num37--;
            }
            num37++;
            while (true)
            {
                tile = Main.tile[num38, num36];
                if (tile.active())
                {
                    break;
                }
                tile = Main.tile[num38, num36 - 1];
                if (tile.active())
                {
                    break;
                }
                tile = Main.tile[num38, num36 + 1];
                if (tile.active())
                {
                    break;
                }
                num38++;
            }
            num38--;
            num39 = num36;
            num40 = num36;
            while (true)
            {
                tile = Main.tile[num35, num39];
                if (tile.active())
                {
                    break;
                }
                tile = Main.tile[num35 - 1, num39];
                if (tile.active())
                {
                    break;
                }
                tile = Main.tile[num35 + 1, num39];
                if (tile.active())
                {
                    break;
                }
                num39--;
            }
            num39++;
            while (true)
            {
                tile = Main.tile[num35, num40];
                if (tile.active())
                {
                    break;
                }
                tile = Main.tile[num35 - 1, num40];
                if (tile.active())
                {
                    break;
                }
                tile = Main.tile[num35 + 1, num40];
                if (tile.active())
                {
                    break;
                }
                num40++;
            }
            num40--;
            num35 = (num37 + num38) / 2;
            num36 = (num39 + num40) / 2;
            int num73 = num38 - num37;
            num41 = num40 - num39;
            if (num73 <= 7 || num41 <= 5)
            {
                continue;
            }
            int num43 = 0;
            if (nearPicture2(i, num36))
            {
                num43 = -1;
            }
            if (num43 == 0)
            {
                PaintingEntry paintingEntry = RandHousePicture();
                if (!nearPicture(num35, num36))
                {
                    PlaceTile(num35, num36, paintingEntry.tileType, mute: true, forced: false, -1, paintingEntry.style);
                }
            }
        }
        int num45;
        for (num45 = num10; num45 < num11; num45++)
        {
            bool flag6 = true;
            for (int num46 = num13; num46 < num14; num46++)
            {
                for (int num47 = num45 - 3; num47 <= num45 + 3; num47++)
                {
                    tile = Main.tile[num47, num46];
                    if (!tile.active())
                    {
                        continue;
                    }
                    if (SolidTile(num47, num46))
                    {
                        tile = Main.tile[num47, num46];
                        if (tile.type != 10)
{
                            continue;
                        }
                    }
                    flag6 = false;
                }
            }
            if (flag6)
            {
                for (int num48 = num13; num48 < num14; num48++)
                {
                    tile = Main.tile[num45, num48];
                    if (tile.wall == 27)
                    {
                        tile = Main.tile[num45, num48];
                        if (!tile.active())
{
                            PlaceTile(num45, num48, 124, mute: true);
                        }
                    }
                }
            }
            num45 += genRand.Next(4);
        }
        for (int num49 = 0; num49 < 4; num49++)
        {
            int num50 = genRand.Next(num10 + 2, num11 - 1);
            int num51 = genRand.Next(num13 + 2, num14 - 1);
            while (true)
            {
                tile = Main.tile[num50, num51];
                if (tile.wall != 27)
                {
                    num50 = genRand.Next(num10 + 2, num11 - 1);
                    num51 = genRand.Next(num13 + 2, num14 - 1);
                    continue;
                }
                break;
            }
            while (true)
            {
                tile = Main.tile[num50, num51];
                if (tile.active())
                {
                    num51--;
                    continue;
                }
                break;
            }
            while (true)
            {
                tile = Main.tile[num50, num51];
                if (tile.active())
                {
                    break;
                }
                num51++;
            }
            num51--;
            tile = Main.tile[num50, num51];
            if (tile.wall != 27)
            {
                continue;
            }
            if (genRand.Next(3) == 0)
            {
                int num52 = genRand.Next(9);
                if (num52 == 0)
                {
                    num52 = 14;
                }
                if (num52 == 1)
                {
                    num52 = 16;
                }
                if (num52 == 2)
                {
                    num52 = 18;
                }
                if (num52 == 3)
                {
                    num52 = 86;
                }
                if (num52 == 4)
                {
                    num52 = 87;
                }
                if (num52 == 5)
                {
                    num52 = 94;
                }
                if (num52 == 6)
                {
                    num52 = 101;
                }
                if (num52 == 7)
                {
                    num52 = 104;
                }
                if (num52 == 8)
                {
                    num52 = 106;
                }
                PlaceTile(num50, num51, num52, mute: true);
            }
            else if (GenVars.statueList != null)
            {
                int num53 = genRand.Next(2, GenVars.statueList.Length);
                PlaceTile(num50, num51, GenVars.statueList[num53].X, mute: true, forced: true, -1, GenVars.statueList[num53].Y);
            }
        }
        for (int num54 = 0; num54 < 40; num54++)
        {
            int num56 = genRand.Next(num10 + 2, num11 - 1);
            int num57 = genRand.Next(num13 + 2, num14 - 1);
            while (true)
            {
                tile = Main.tile[num56, num57];
                if (tile.wall != 27)
                {
                    num56 = genRand.Next(num10 + 2, num11 - 1);
                    num57 = genRand.Next(num13 + 2, num14 - 1);
                    continue;
                }
                break;
            }
            while (true)
            {
                tile = Main.tile[num56, num57];
                if (tile.active())
                {
                    num57--;
                    continue;
                }
                break;
            }
            while (true)
            {
                tile = Main.tile[num56, num57];
                if (tile.active())
                {
                    break;
                }
                num57++;
            }
            num57--;
            tile = Main.tile[num56, num57];
            if (tile.wall == 27 && genRand.Next(2) == 0)
            {
                int style = genRand.Next(22, 26);
                PlaceTile(num56, num57, 186, mute: true, forced: false, -1, style);
            }
        }
        for (int num58 = 0; num58 < 20; num58++)
        {
            int num59 = genRand.Next(num10 + 2, num11 - 1);
            int num60 = genRand.Next(num13 + 2, num14 - 1);
            while (true)
            {
                tile = Main.tile[num59, num60];
                if (tile.wall != 27)
                {
                    num59 = genRand.Next(num10 + 2, num11 - 1);
                    num60 = genRand.Next(num13 + 2, num14 - 1);
                    continue;
                }
                break;
            }
            while (true)
            {
                tile = Main.tile[num59, num60];
                if (tile.active())
                {
                    num60--;
                    continue;
                }
                break;
            }
            while (true)
            {
                tile = Main.tile[num59, num60];
                if (tile.active())
                {
                    break;
                }
                num60++;
            }
            num60--;
            tile = Main.tile[num59, num60];
            if (tile.wall == 27 && genRand.Next(2) == 0)
            {
                int x = genRand.Next(31, 34);
                PlaceSmallPile(num59, num60, x, 1, 185);
            }
        }
        for (int num61 = 0; num61 < 15; num61++)
        {
            int num62 = genRand.Next(num10 + 2, num11 - 1);
            int num63 = genRand.Next(num13 + 2, num14 - 1);
            while (true)
            {
                tile = Main.tile[num62, num63];
                if (tile.wall != 27)
                {
                    num62 = genRand.Next(num10 + 2, num11 - 1);
                    num63 = genRand.Next(num13 + 2, num14 - 1);
                    continue;
                }
                break;
            }
            while (true)
            {
                tile = Main.tile[num62, num63];
                if (tile.active())
                {
                    num63--;
                    continue;
                }
                break;
            }
            while (num63 > 0)
            {
                tile = Main.tile[num62, num63 - 1];
                if (tile.active())
                {
                    break;
                }
                num63--;
            }
            tile = Main.tile[num62, num63];
            if (tile.wall != 27)
            {
                continue;
            }
            int num64 = 4;
            int style2 = 0;
            if (genRand.Next(10) < 9)
            {
                num64 = -1;
            }
            else
            {
                num64 = 34;
                style2 = genRand.Next(6);
            }
            if (num64 <= 0)
            {
                continue;
            }
            PlaceTile(num62, num63, num64, mute: true, forced: false, -1, style2);
            tile = Main.tile[num62, num63];
            if (tile.type != num64)
            {
                continue;
            }
            if (num64 == 4)
            {
                tile = Main.tile[num62, num63];
                tile.frameX += 54;
                continue;
            }
            int num65 = num62;
            int num67 = num63;
            tile = Main.tile[num65, num67];
            num63 = num67 - tile.frameY % 54 / 18;
            tile = Main.tile[num65, num67];
            num62 = tile.frameX / 18;
            if (num62 > 2)
            {
                num62 -= 3;
            }
            num62 = num65 - num62;
            short num68 = 54;
            tile = Main.tile[num62, num63];
            if (tile.frameX > 0)
            {
                num68 = -54;
            }
            for (int num69 = num62; num69 < num62 + 3; num69++)
            {
                for (int num70 = num63; num70 < num63 + 3; num70++)
                {
                    tile = Main.tile[num69, num70];
                    tile.frameX += num68;
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.BasicChest, Terraria.Tile.halfBrick(), Terraria.Tile.lava(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.slope(), Terraria.Enums.SolidTile, Terraria.WorldBuilding.GenVars.statueList, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.wallHouse.