TModLoader: Terraria.WorldGen.do_worldGenCallBack
do_worldGenCallBack()
static void Terraria.WorldGen.do_worldGenCallBack (object threadContext) inline static
    {
        SoundEngine.PlaySound(10);
        clearWorld();
        GenerateWorld(Main.ActiveWorldFileData.Seed, threadContext as GenerationProgress);
        WorldFile.SaveWorld(Main.ActiveWorldFileData.IsCloudSave, resetTime: true);
        BackupIO.archiveLock = false;
        if (Main.menuMode == 10 || Main.menuMode == 888)
        {
            Main.menuMode = 6;
        }
        SoundEngine.PlaySound(10);
        generatingWorld = false;
    }
References Terraria.Main.ActiveWorldFileData, Terraria.WorldGen.clearWorld(), Terraria.WorldGen.GenerateWorld(), Terraria.WorldGen.generatingWorld, Terraria.IO.FileData.IsCloudSave, Terraria.Main.menuMode, Terraria.Audio.SoundEngine.PlaySound(), Terraria.IO.WorldFile.SaveWorld(), and Terraria.IO.WorldFileData.Seed.
Referenced by Terraria.WorldGen.worldGenCallback().