TModLoader: Terraria.WorldGen.Check3x2
Check3x2()
static void Terraria.WorldGen.Check3x2 (int i, int j, int type) inline static
    {
        if (destroyObject)
        {
            return;
        }
        bool flag = false;
        bool flag2 = false;
        int num = j;
        Tile tile5;
        if (Main.tile[i, j] == null)
        {
            tile5 = (Main.tile[i, j] = default(Tile));
        }
        int num9 = 36;
        tile5 = Main.tile[i, j];
        int num10 = tile5.frameY / num9;
        tile5 = Main.tile[i, j];
        int num11 = tile5.frameY % num9;
        num -= num11 / 18;
        tile5 = Main.tile[i, j];
        int num12 = tile5.frameX / 18;
        int num13 = 0;
        while (num12 > 2)
        {
            num12 -= 3;
            num13++;
        }
        num12 = i - num12;
        int num14 = num13 * 54;
        if (type == 14 && num13 == 25)
        {
            flag2 = true;
        }
        int num15 = num + 2;
        if (flag2)
        {
            num15--;
        }
        for (int k = num12; k < num12 + 3; k++)
        {
            for (int l = num; l < num15; l++)
            {
                if (Main.tile[k, l] == null)
                {
                    tile5 = (Main.tile[k, l] = default(Tile));
                }
                tile5 = Main.tile[k, l];
                if (tile5.active())
                {
                    tile5 = Main.tile[k, l];
                    if (tile5.type == type)
                    {
                        tile5 = Main.tile[k, l];
                        if (tile5.frameX == (k - num12) * 18 + num14)
{
                            tile5 = Main.tile[k, l];
                            if (tile5.frameY == (l - num) * 18 + num10 * 36)
{
                                continue;
                            }
                        }
                    }
                }
                flag = true;
            }
            if (type == 285 || type == 286 || type == 298 || type == 299 || type == 310 || type == 339 || type == 538 || (type >= 361 && type <= 364) || type == 532 || type == 544 || type == 533 || type == 555 || type == 556 || type == 582 || type == 619 || type == 629)
            {
                if (!SolidTileAllowBottomSlope(k, num15))
                {
                    if (!(Main.tile[k, num15] == null))
                    {
                        tile5 = Main.tile[k, num15];
                        if (tile5.nactive())
{
                            bool[] tileSolidTop = Main.tileSolidTop;
                            tile5 = Main.tile[k, num15];
                            if (tileSolidTop[tile5.type])
{
                                tile5 = Main.tile[k, num15];
                                if (tile5.frameY == 0)
{
                                    goto IL_0490;
                                }
                            }
                        }
                    }
                    if (!(Main.tile[k, num15] == null))
                    {
                        tile5 = Main.tile[k, num15];
                        if (tile5.active())
{
                            bool[] platforms = TileID.Sets.Platforms;
                            tile5 = Main.tile[k, num15];
                            if (platforms[tile5.type])
{
                                goto IL_0490;
                            }
                        }
                    }
                    flag = true;
                }
            }
            else
            {
                switch (type)
                {
                case 488:
                {
                    int num16 = 0;
                    if (Main.tile[k, num15] != null)
                    {
                        tile5 = Main.tile[k, num15];
                        if (tile5.active())
{
                            tile5 = Main.tile[k, num15];
                            num16 = tile5.type;
                        }
                    }
                    if (num16 != 2 && num16 != 477 && num16 != 109 && num16 != 492)
                    {
                        flag = true;
                    }
                    break;
                }
                case 26:
                {
                    Tile tile2 = Main.tile[k, num15];
                    if (!SolidTileAllowBottomSlope(k, num15) || (tile2 != null && tile2.active() && TileID.Sets.Boulders[tile2.type]))
                    {
                        flag = true;
                    }
                    break;
                }
                case 186:
                {
                    if (!SolidTileAllowBottomSlope(k, num15))
                    {
                        flag = true;
                        break;
                    }
                    Tile tile = Main.tile[k, num15];
                    if (tile == null || !tile.active())
                    {
                        break;
                    }
                    switch (num13)
                    {
                    case 26:
                    case 27:
                    case 28:
                    case 29:
                    case 30:
                    case 31:
                        if (!TileID.Sets.Snow[tile.type] && !TileID.Sets.Conversion.Ice[tile.type] && tile.type != 162 && tile.type != 224)
{
                            flag = true;
                        }
                        break;
                    case 32:
                    case 33:
                    case 34:
                        if (!TileID.Sets.Mud[tile.type] && tile.type != 70)
{
                            flag = true;
                        }
                        break;
                    }
                    break;
                }
                }
            }
            goto IL_0490;
            IL_0490:
            if (type == 187)
            {
                if (!SolidTileAllowBottomSlope(k, num15))
                {
                    flag = true;
                }
                else
                {
                    Tile tile3 = Main.tile[k, num15];
                    if (!(tile3 == null) && tile3.active())
                    {
                        switch (num13)
{
                        case 0:
                        case 1:
                        case 2:
                        case 3:
                        case 4:
                        case 5:
                            if (!TileID.Sets.Mud[tile3.type] && tile3.type != 60 && tile3.type != 226)
{
                                flag = true;
                            }
                            break;
                        case 6:
                        case 7:
                        case 8:
                            if (tile3.type != 57 && tile3.type != 58 && tile3.type != 75 && tile3.type != 76)
{
                                flag = true;
                            }
                            break;
                        case 29:
                        case 30:
                        case 31:
                        case 32:
                        case 33:
                        case 34:
                            if (!TileID.Sets.Conversion.Sand[tile3.type] && !TileID.Sets.Conversion.HardenedSand[tile3.type] && !TileID.Sets.Conversion.Sandstone[tile3.type])
{
                                flag = true;
                            }
                            break;
                        }
                    }
                }
            }
            else if (!SolidTileAllowBottomSlope(k, num15))
            {
                flag = true;
            }
        }
        if (type == 187 && Main.tile[num12, num] != null)
        {
            tile5 = Main.tile[num12, num];
            if (tile5.frameX >= 756)
            {
                tile5 = Main.tile[num12, num];
                if (tile5.frameX <= 900)
                {
                    tile5 = Main.tile[num12, num + 2];
                    if (tile5.type != 2)
                    {
                        tile5 = Main.tile[num12 + 1, num + 2];
                        if (tile5.type != 2)
{
                            tile5 = Main.tile[num12 + 2, num + 2];
                            if (tile5.type != 2)
{
                                tile5 = Main.tile[num12, num + 2];
                                if (tile5.type != 477)
{
                                    tile5 = Main.tile[num12 + 1, num + 2];
                                    if (tile5.type != 477)
{
                                        tile5 = Main.tile[num12 + 2, num + 2];
                                        if (tile5.type != 477)
{
                                            tile5 = Main.tile[num12, num + 2];
                                            if (tile5.type != 492)
{
                                                tile5 = Main.tile[num12 + 1, num + 2];
                                                if (tile5.type != 492)
{
                                                    tile5 = Main.tile[num12 + 2, num + 2];
                                                    if (tile5.type != 492)
{
                                                        tile5 = Main.tile[num12, num];
                                                        tile5.frameX -= 378;
                                                        tile5 = Main.tile[num12 + 1, num];
                                                        tile5.frameX -= 378;
                                                        tile5 = Main.tile[num12 + 2, num];
                                                        tile5.frameX -= 378;
                                                        tile5 = Main.tile[num12, num + 1];
                                                        tile5.frameX -= 378;
                                                        tile5 = Main.tile[num12 + 1, num + 1];
                                                        tile5.frameX -= 378;
                                                        tile5 = Main.tile[num12 + 2, num + 1];
                                                        tile5.frameX -= 378;
                                                        tile5 = Main.tile[num12, num];
                                                        tile5.type = 186;
                                                        tile5 = Main.tile[num12 + 1, num];
                                                        tile5.type = 186;
                                                        tile5 = Main.tile[num12 + 2, num];
                                                        tile5.type = 186;
                                                        tile5 = Main.tile[num12, num + 1];
                                                        tile5.type = 186;
                                                        tile5 = Main.tile[num12 + 1, num + 1];
                                                        tile5.type = 186;
                                                        tile5 = Main.tile[num12 + 2, num + 1];
                                                        tile5.type = 186;
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        if (flag && type == 488 && gen)
        {
            for (int m = num12; m < num12 + 3; m++)
            {
                for (int n = num; n < num + 2; n++)
                {
                    tile5 = Main.tile[m, n];
                    tile5.active(active: true);
                    tile5 = Main.tile[m, n];
                    tile5.type = 488;
                    tile5 = Main.tile[m, n];
                    tile5.frameX = (short)((m - num12) * 18);
                    tile5 = Main.tile[m, n];
                    tile5.frameY = (short)((n - num) * 18);
                }
                tile5 = Main.tile[m, num + 2];
                tile5.active(active: true);
                tile5 = Main.tile[m, num + 2];
                tile5.type = 2;
                tile5 = Main.tile[m, num + 2];
                tile5.slope(0);
                tile5 = Main.tile[m, num + 2];
                tile5.halfBrick(halfBrick: false);
            }
            flag = false;
        }
        if (!flag)
        {
            return;
        }
        tile5 = Main.tile[i, j];
        int frameX = tile5.frameX;
        destroyObject = true;
        num15 = num + 3;
        if (flag2)
        {
            num15--;
        }
        bool drop = TileLoader.Drop(i, j, type);
        for (int num2 = num12; num2 < num12 + 3; num2++)
        {
            for (int num3 = num; num3 < num + 3; num3++)
            {
                if (Main.tile[num2, num3] == null)
                {
                    tile5 = (Main.tile[num2, num3] = default(Tile));
                }
                tile5 = Main.tile[num2, num3];
                if (tile5.type == type)
                {
                    tile5 = Main.tile[num2, num3];
                    if (tile5.active())
                    {
                        KillTile(num2, num3);
                    }
                }
            }
        }
        using (new Item.DisableNewItemMethod(!drop))
        {
            if (type == 14)
            {
                int type2 = ((num13 >= 1 && num13 <= 3) ? (637 + num13) : ((num13 >= 15 && num13 <= 20) ? (1698 + num13) : ((num13 >= 4 && num13 <= 7) ? (823 + num13) : (num13 switch
                {
                    8 => 917,
                    9 => 1144,
                    10 => 1397,
                    11 => 1400,
                    12 => 1403,
                    13 => 1460,
                    14 => 1510,
                    23 => 1926,
                    21 => 1794,
                    22 => 1816,
                    24 => 2248,
                    25 => 2259,
                    26 => 2532,
                    27 => 2550,
                    28 => 677,
                    29 => 2583,
                    30 => 2743,
                    31 => 2824,
                    32 => 3153,
                    33 => 3155,
                    34 => 3154,
                    _ => 32,
                }))));
                Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, type2);
            }
            switch (type)
            {
            case 469:
            {
                int type4 = 3920;
                if (num13 == 1)
                {
                    type4 = 3948;
                }
                if (num13 == 2)
                {
                    type4 = 3974;
                }
                if (num13 == 3)
                {
                    type4 = 4162;
                }
                if (num13 == 4)
                {
                    type4 = 4183;
                }
                if (num13 == 5)
                {
                    type4 = 4204;
                }
                if (num13 == 6)
                {
                    type4 = 4225;
                }
                if (num13 == 7)
                {
                    type4 = 4314;
                }
                if (num13 == 8)
                {
                    type4 = 4583;
                }
                if (num13 == 9)
                {
                    type4 = 5165;
                }
                if (num13 == 10)
                {
                    type4 = 5186;
                }
                if (num13 == 11)
                {
                    type4 = 5207;
                }
                Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, type4);
                break;
            }
            case 114:
                Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 398);
                break;
            case 26:
                if (!noTileActions && !IsGeneratingHardMode)
                {
                    SmashAltar(i, j);
                }
                break;
            case 298:
                Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2190);
                break;
            case 299:
                Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2191);
                break;
            case 361:
            case 362:
            case 363:
            case 364:
                Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3073 + type - 361);
                break;
            default:
                if (type >= 391 && type <= 394)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 48, 32, 3254 + type - 391);
                    break;
                }
                switch (type)
                {
                case 285:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2174);
                    break;
                case 286:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2175);
                    break;
                case 582:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4850);
                    break;
                case 619:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4963);
                    break;
                case 310:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2207);
                    break;
                case 339:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2741);
                    break;
                case 538:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4380);
                    break;
                case 544:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4399);
                    break;
                case 532:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4364);
                    break;
                case 533:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4376);
                    break;
                case 555:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4475);
                    break;
                case 556:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4476);
                    break;
                case 629:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5133);
                    break;
                case 217:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 995);
                    break;
                case 218:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 996);
                    break;
                case 219:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 997);
                    break;
                case 642:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5296);
                    break;
                case 220:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 998);
                    break;
                case 377:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3198);
                    break;
                case 228:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1120);
                    break;
                case 405:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3364);
                    break;
                case 486:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4063);
                    break;
                case 488:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 9, genRand.Next(10, 21));
                    break;
                case 215:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, GetCampfireItemDrop(num13));
                    break;
                case 244:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1449);
                    break;
                case 647:
                {
                    int num5 = 0;
                    if (num13 < 7)
                    {
                        num5 = 154;
                    }
                    else if (num13 < 13)
                    {
                        num5 = 3;
                    }
                    else if (num13 < 16)
                    {
                        num5 = 3;
                    }
                    else if (num13 < 18)
                    {
                        num5 = 71;
                    }
                    else if (num13 < 20)
                    {
                        num5 = 72;
                    }
                    else if (num13 < 22)
                    {
                        num5 = 73;
                    }
                    else if (num13 < 26)
                    {
                        num5 = 9;
                    }
                    else if (num13 < 32)
                    {
                        num5 = 593;
                    }
                    else if (num13 < 35)
                    {
                        num5 = 183;
                    }
                    if (num5 != 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, num5);
                    }
                    break;
                }
                case 648:
                {
                    num13 += num10 * 35;
                    int num4 = 0;
                    if (num13 < 6)
                    {
                        num4 = 195;
                    }
                    else if (num13 < 9)
                    {
                        num4 = 174;
                    }
                    else if (num13 < 14)
                    {
                        num4 = 150;
                    }
                    else if (num13 < 17)
                    {
                        num4 = 3;
                    }
                    else if (num13 < 18)
                    {
                        num4 = 989;
                    }
                    else if (num13 < 21)
                    {
                        num4 = 1101;
                    }
                    else if (num13 < 29)
                    {
                        num4 = 9;
                    }
                    else if (num13 < 35)
                    {
                        num4 = 3271;
                    }
                    else if (num13 < 41)
                    {
                        num4 = 3086;
                    }
                    else if (num13 < 47)
                    {
                        num4 = 3081;
                    }
                    else if (num13 < 52)
                    {
                        num4 = 62;
                    }
                    else if (num13 < 55)
                    {
                        num4 = 154;
                    }
                    if (num4 != 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, num4);
                    }
                    break;
                }
                case 651:
                {
                    int num6 = 0;
                    num6 = ((num13 < 3) ? 195 : ((num13 >= 6) ? 331 : 62));
                    if (num6 != 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, num6);
                    }
                    break;
                }
                case 17:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 33);
                    break;
                case 77:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 221);
                    break;
                case 86:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 332);
                    break;
                case 237:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1292);
                    break;
                case 87:
                {
                    int type3;
                    if (num13 >= 1 && num13 <= 3)
                    {
                        type3 = 640 + num13;
                    }
                    else
                    {
                        switch (num13)
{
                        case 4:
                            type3 = 919;
                            break;
                        case 5:
                        case 6:
                        case 7:
                            type3 = 2245 + num13 - 5;
                            break;
                        case 8:
                        case 9:
                        case 10:
                            type3 = 2254 + num13 - 8;
                            break;
                        default:
                            type3 = ((num13 >= 11 && num13 <= 20) ? (2376 + num13 - 11) : (num13 switch
{
                                21 => 2531,
                                22 => 2548,
                                23 => 2565,
                                24 => 2580,
                                25 => 2671,
                                26 => 2821,
                                27 => 3141,
                                28 => 3143,
                                29 => 3142,
                                30 => 3915,
                                31 => 3916,
                                32 => 3944,
                                33 => 3971,
                                34 => 4158,
                                35 => 4179,
                                36 => 4200,
                                37 => 4221,
                                38 => 4310,
                                39 => 4579,
                                40 => 5161,
                                41 => 5182,
                                42 => 5203,
                                _ => 333,
                            }));
                            break;
                        }
                    }
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, type3);
                    break;
                }
                case 88:
                {
                    int dresserItemDrop = GetDresserItemDrop(num13);
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, dresserItemDrop);
                    break;
                }
                case 89:
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, GetItemDrop_Benches(num13));
                    break;
                case 133:
                    if (frameX >= 54)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1221);
                    }
                    else
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 524);
                    }
                    break;
                case 186:
                    if (frameX < 864)
                    {
                        break;
                    }
                    if (frameX <= 954)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(20, 100));
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(30, 100));
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(40, 100));
                        if (genRand.Next(3) != 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(20, 100));
                        }
                        if (genRand.Next(3) != 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(30, 100));
                        }
                        if (genRand.Next(3) != 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(40, 100));
                        }
                        if (genRand.Next(2) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(20, 100));
                        }
                        if (genRand.Next(2) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(30, 100));
                        }
                        if (genRand.Next(2) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(40, 100));
                        }
                        if (genRand.Next(3) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(20, 100));
                        }
                        if (genRand.Next(3) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(30, 100));
                        }
                        if (genRand.Next(3) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(40, 100));
                        }
                        if (genRand.Next(4) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(20, 100));
                        }
                        if (genRand.Next(4) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(30, 100));
                        }
                        if (genRand.Next(4) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(40, 100));
                        }
                        if (genRand.Next(5) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(20, 100));
                        }
                        if (genRand.Next(5) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(30, 100));
                        }
                        if (genRand.Next(5) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 71, genRand.Next(40, 100));
                        }
                    }
                    else if (frameX <= 1062)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 72, genRand.Next(10, 100));
                        if (genRand.Next(2) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 72, genRand.Next(20, 100));
                        }
                        if (genRand.Next(3) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 72, genRand.Next(30, 100));
                        }
                        if (genRand.Next(4) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 72, genRand.Next(40, 100));
                        }
                        if (genRand.Next(5) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 72, genRand.Next(50, 100));
                        }
                    }
                    else if (frameX <= 1170)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 73, genRand.Next(1, 7));
                        if (genRand.Next(2) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 73, genRand.Next(2, 7));
                        }
                        if (genRand.Next(3) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 73, genRand.Next(3, 7));
                        }
                        if (genRand.Next(4) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 73, genRand.Next(4, 7));
                        }
                        if (genRand.Next(5) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 73, genRand.Next(5, 7));
                        }
                    }
                    break;
                case 187:
                    if (frameX >= 918 && frameX <= 970)
                    {
                        if (Main.rand.Next(50) == 0)
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4144);
                        }
                        else
{
                            Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 989);
                        }
                    }
                    break;
                }
                break;
            }
            destroyObject = false;
            for (int num7 = num12 - 1; num7 < num12 + 4; num7++)
            {
                for (int num8 = num - 1; num8 < num + 4; num8++)
                {
                    TileFrame(num7, num8);
                }
            }
            if (type == 488)
            {
                mysticLogsEvent.FallenLogDestroyed();
            }
        }
    }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Boulders, Terraria.ModLoader.TileLoader.Drop(), Terraria.GameContent.Events.MysticLogFairiesEvent.FallenLogDestroyed(), Terraria.ID.TileID.Sets.Conversion.HardenedSand, Terraria.ID.TileID.Sets.Conversion.Ice, Terraria.ID.TileID.Sets.Mud, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.rand, Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.ID.TileID.Sets.Conversion.Sandstone, Terraria.ID.TileID.Sets.Snow, Terraria.Main.tile, Terraria.Main.tileSolidTop, and Terraria.Tile.type.