TModLoader: Terraria.WorldGen.FinishPlayWorld
FinishPlayWorld()
static void Terraria.WorldGen.FinishPlayWorld () inline static package
Definition at line 3666 of file WorldGen.cs.
    {
        Main.player[Main.myPlayer].Spawn(PlayerSpawnContext.SpawningIntoWorld);
        _lastSeed = Main.ActiveWorldFileData.Seed;
        WorldFile.SetOngoingToTemps();
        SoundEngine.PlaySound(11);
        Main.resetClouds = true;
        noMapUpdate = false;
    }
References Terraria.WorldGen._lastSeed, Terraria.Main.ActiveWorldFileData, Terraria.Main.myPlayer, Terraria.WorldGen.noMapUpdate, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.IO.WorldFileData.Seed, Terraria.IO.WorldFile.SetOngoingToTemps(), and Terraria.Player.Spawn().
Referenced by Terraria.WorldGen.playWorldCallBack().