TModLoader: Terraria.WorldGen.coatingColors
coatingColors()
static List< Color > Terraria.WorldGen.coatingColors (Tile tile, bool block) inline static
    {
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        _coatingColors.Clear();
        if (tile == null)
        {
            return _coatingColors;
        }
        if ((block && tile.fullbrightBlock()) || (!block && tile.fullbrightWall()))
        {
            _coatingColors.Add(coatingColor(1));
        }
        if ((block && tile.invisibleBlock()) || (!block && tile.invisibleWall()))
        {
            _coatingColors.Add(coatingColor(2));
        }
        return _coatingColors;
    }
References Terraria.Tile.fullbrightBlock(), Terraria.Tile.fullbrightWall(), Terraria.Tile.invisibleBlock(), and Terraria.Tile.invisibleWall().