TModLoader: Terraria.WorldGen.GrowCactus
GrowCactus()
static void Terraria.WorldGen.GrowCactus (int i, int j) inline static
    {
        int num = j;
        int num5 = i;
        Tile tile = Main.tile[i, j];
        if (!tile.nactive())
        {
            return;
        }
        tile = Main.tile[i, j];
        if (tile.halfBrick())
        {
            return;
        }
        if (!gen)
        {
            tile = Main.tile[i, j];
            if (tile.slope() != 0)
            {
                return;
            }
        }
        tile = Main.tile[i, j - 1];
        if (tile.liquid > 0)
        {
            return;
        }
        tile = Main.tile[i, j];
        if (tile.type != 53)
        {
            tile = Main.tile[i, j];
            if (tile.type != 80)
            {
                tile = Main.tile[i, j];
                if (tile.type != 234)
                {
                    tile = Main.tile[i, j];
                    if (tile.type != 112)
                    {
                        tile = Main.tile[i, j];
                        if (tile.type != 116)
{
                            return;
                        }
                    }
                }
            }
        }
        int num6 = 0;
        for (int k = i - cactusWaterWidth; k < i + cactusWaterWidth; k++)
        {
            for (int l = j - cactusWaterHeight; l < j + cactusWaterHeight; l++)
            {
                int num13 = num6;
                tile = Main.tile[k, l];
                num6 = num13 + tile.liquid;
            }
        }
        if ((!Main.remixWorld || !((double)j > Main.worldSurface)) && num6 / 255 > cactusWaterLimit)
        {
            return;
        }
        tile = Main.tile[i, j];
        if (tile.type != 53)
        {
            tile = Main.tile[i, j];
            if (tile.type != 112)
            {
                tile = Main.tile[i, j];
                if (tile.type != 116)
                {
                    tile = Main.tile[i, j];
                    if (tile.type != 234)
                    {
                        tile = Main.tile[i, j];
                        if (!TileLoader.CanGrowModCactus(tile.type))
{
                            tile = Main.tile[i, j];
                            if (tile.type != 80)
{
                                return;
                            }
                            while (true)
{
                                tile = Main.tile[num5, num];
                                if (!tile.active())
{
                                    break;
                                }
                                tile = Main.tile[num5, num];
                                if (tile.type != 80)
{
                                    break;
                                }
                                num++;
                                tile = Main.tile[num5, num];
                                if (tile.active())
{
                                    tile = Main.tile[num5, num];
                                    if (tile.type == 80)
{
                                        continue;
                                    }
                                }
                                tile = Main.tile[num5 - 1, num];
                                if (tile.active())
{
                                    tile = Main.tile[num5 - 1, num];
                                    if (tile.type == 80)
{
                                        tile = Main.tile[num5 - 1, num - 1];
                                        if (tile.active())
{
                                            tile = Main.tile[num5 - 1, num - 1];
                                            if (tile.type == 80 && num5 >= i)
{
                                                num5--;
                                            }
                                        }
                                    }
                                }
                                tile = Main.tile[num5 + 1, num];
                                if (!tile.active())
{
                                    continue;
                                }
                                tile = Main.tile[num5 + 1, num];
                                if (tile.type != 80)
{
                                    continue;
                                }
                                tile = Main.tile[num5 + 1, num - 1];
                                if (tile.active())
{
                                    tile = Main.tile[num5 + 1, num - 1];
                                    if (tile.type == 80 && num5 <= i)
{
                                        num5++;
                                    }
                                }
                            }
                            num--;
                            int num9 = num - j;
                            int num10 = i - num5;
                            num5 = i - num10;
                            num = j;
                            int num11 = 11 - num9;
                            int num12 = 0;
                            for (int num2 = num5 - 2; num2 <= num5 + 2; num2++)
{
                                for (int num3 = num - num11; num3 <= num + num9; num3++)
{
                                    tile = Main.tile[num2, num3];
                                    if (tile.active())
{
                                        tile = Main.tile[num2, num3];
                                        if (tile.type == 80)
{
                                            num12++;
                                        }
                                    }
                                }
                            }
                            if (Main.drunkWorld)
{
                                if (num12 >= genRand.Next(11, 20))
{
                                    return;
                                }
                            }
                            else if (num12 >= genRand.Next(11, 13))
{
                                return;
                            }
                            num5 = i;
                            num = j;
                            if (num10 == 0)
{
                                if (num9 == 0)
{
                                    tile = Main.tile[num5, num - 1];
                                    if (!tile.active())
{
                                        tile = Main.tile[num5, num - 1];
                                        tile.active(active: true);
                                        tile = Main.tile[num5, num - 1];
                                        tile.type = 80;
                                        SquareTileFrame(num5, num - 1);
                                        if (Main.netMode == 2)
{
                                            NetMessage.SendTileSquare(-1, num5, num - 1);
                                        }
                                    }
                                    return;
                                }
                                bool flag = false;
                                bool flag2 = false;
                                tile = Main.tile[num5, num - 1];
                                if (tile.active())
{
                                    tile = Main.tile[num5, num - 1];
                                    if (tile.type == 80)
{
                                        tile = Main.tile[num5 - 1, num];
                                        if (!tile.active())
{
                                            tile = Main.tile[num5 - 2, num + 1];
                                            if (!tile.active())
{
                                                tile = Main.tile[num5 - 1, num - 1];
                                                if (!tile.active())
{
                                                    tile = Main.tile[num5 - 1, num + 1];
                                                    if (!tile.active())
{
                                                        tile = Main.tile[num5 - 2, num];
                                                        if (!tile.active())
{
                                                            flag = true;
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                        tile = Main.tile[num5 + 1, num];
                                        if (!tile.active())
{
                                            tile = Main.tile[num5 + 2, num + 1];
                                            if (!tile.active())
{
                                                tile = Main.tile[num5 + 1, num - 1];
                                                if (!tile.active())
{
                                                    tile = Main.tile[num5 + 1, num + 1];
                                                    if (!tile.active())
{
                                                        tile = Main.tile[num5 + 2, num];
                                                        if (!tile.active())
{
                                                            flag2 = true;
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                                int num4 = genRand.Next(3);
                                if (num4 == 0 && flag)
{
                                    tile = Main.tile[num5 - 1, num];
                                    tile.active(active: true);
                                    tile = Main.tile[num5 - 1, num];
                                    tile.type = 80;
                                    SquareTileFrame(num5 - 1, num);
                                    if (Main.netMode == 2)
{
                                        NetMessage.SendTileSquare(-1, num5 - 1, num);
                                    }
                                }
                                else if (num4 == 1 && flag2)
{
                                    tile = Main.tile[num5 + 1, num];
                                    tile.active(active: true);
                                    tile = Main.tile[num5 + 1, num];
                                    tile.type = 80;
                                    SquareTileFrame(num5 + 1, num);
                                    if (Main.netMode == 2)
{
                                        NetMessage.SendTileSquare(-1, num5 + 1, num);
                                    }
                                }
                                else
{
                                    if (num9 >= genRand.Next(2, 8))
{
                                        return;
                                    }
                                    tile = Main.tile[num5 - 1, num - 1];
                                    if (tile.active())
{
                                        tile = Main.tile[num5 - 1, num - 1];
                                        _ = ref tile.type;
                                    }
                                    tile = Main.tile[num5 + 1, num - 1];
                                    if (tile.active())
{
                                        tile = Main.tile[num5 + 1, num - 1];
                                        if (tile.type == 80)
{
                                            return;
                                        }
                                    }
                                    tile = Main.tile[num5, num - 1];
                                    if (!tile.active())
{
                                        tile = Main.tile[num5, num - 1];
                                        tile.active(active: true);
                                        tile = Main.tile[num5, num - 1];
                                        tile.type = 80;
                                        SquareTileFrame(num5, num - 1);
                                        if (Main.netMode == 2)
{
                                            NetMessage.SendTileSquare(-1, num5, num - 1);
                                        }
                                    }
                                }
                                return;
                            }
                            tile = Main.tile[num5, num - 1];
                            if (tile.active())
{
                                return;
                            }
                            tile = Main.tile[num5, num - 2];
                            if (tile.active())
{
                                return;
                            }
                            tile = Main.tile[num5 + num10, num - 1];
                            if (tile.active())
{
                                return;
                            }
                            tile = Main.tile[num5 - num10, num - 1];
                            if (!tile.active())
{
                                return;
                            }
                            tile = Main.tile[num5 - num10, num - 1];
                            if (tile.type == 80)
{
                                tile = Main.tile[num5, num - 1];
                                tile.active(active: true);
                                tile = Main.tile[num5, num - 1];
                                tile.type = 80;
                                SquareTileFrame(num5, num - 1);
                                if (Main.netMode == 2)
{
                                    NetMessage.SendTileSquare(-1, num5, num - 1);
                                }
                            }
                            return;
                        }
                    }
                }
            }
        }
        tile = Main.tile[i, j - 1];
        if (tile.active())
        {
            return;
        }
        tile = Main.tile[i - 1, j - 1];
        if (tile.active())
        {
            return;
        }
        tile = Main.tile[i + 1, j - 1];
        if (tile.active())
        {
            return;
        }
        int num7 = 0;
        int num8 = 0;
        for (int m = i - 6; m <= i + 6; m++)
        {
            for (int n = j - 3; n <= j + 1; n++)
            {
                try
                {
                    tile = Main.tile[m, n];
                    if (!tile.active())
                    {
                        continue;
                    }
                    tile = Main.tile[m, n];
                    if (tile.type == 80)
                    {
                        num7++;
                        if (num7 >= 4)
{
                            return;
                        }
                    }
                    tile = Main.tile[m, n];
                    if (tile.type == 53)
                    {
                        goto IL_032c;
                    }
                    tile = Main.tile[m, n];
                    if (tile.type == 112)
                    {
                        goto IL_032c;
                    }
                    tile = Main.tile[m, n];
                    if (tile.type == 116)
                    {
                        goto IL_032c;
                    }
                    tile = Main.tile[m, n];
                    if (tile.type == 234)
                    {
                        goto IL_032c;
                    }
                    tile = Main.tile[m, n];
                    if (TileLoader.CanGrowModCactus(tile.type))
                    {
                        goto IL_032c;
                    }
                    goto end_IL_0257;
                    IL_032c:
                    num8++;
                    end_IL_0257:;
                }
                catch
                {
                }
            }
        }
        if (num8 > 10)
        {
            if (gen && genRand.Next(2) == 0)
            {
                tile = Main.tile[i, j];
                tile.slope(0);
            }
            tile = Main.tile[i, j - 1];
            tile.active(active: true);
            tile = Main.tile[i, j - 1];
            tile.type = 80;
            if (Main.netMode == 2)
            {
                NetMessage.SendTileSquare(-1, i, j - 1);
            }
            SquareTileFrame(num5, num - 1);
        }
    }
References Terraria.Tile.active(), Terraria.ModLoader.TileLoader.CanGrowModCactus(), Terraria.Main.drunkWorld, Terraria.Tile.halfBrick(), Terraria.Tile.liquid, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Main.remixWorld, Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Main.worldSurface.