TModLoader: Terraria.WorldGen.SaveAndQuitCallBack
SaveAndQuitCallBack()
static void Terraria.WorldGen.SaveAndQuitCallBack (object threadContext) inline static
    {
        int netMode = Main.netMode;
        Main.ambientWaterfallStrength = 0f;
        Main.ambientLavafallStrength = 0f;
        if (netMode == 0)
        {
            WorldFile.CacheSaveTime();
        }
        Main.invasionProgress = -1;
        Main.invasionProgressDisplayLeft = 0;
        Main.invasionProgressAlpha = 0f;
        Main.invasionProgressIcon = 0;
        Main.menuMode = 10;
        Main.gameMenu = true;
        SoundEngine.StopTrackedSounds();
        try
        {
            SoundEngine.PlaySound(11);
        }
        catch
        {
        }
        CaptureInterface.ResetFocus();
        Main.ActivePlayerFileData.StopPlayTimer();
        Player.SavePlayer(Main.ActivePlayerFileData);
        Player.ClearPlayerTempInfo();
        Rain.ClearRain();
        if (netMode == 0)
        {
            WorldFile.SaveWorld();
            SoundEngine.PlaySound(10);
        }
        else
        {
            Netplay.Disconnect = true;
            Main.netMode = 0;
        }
        SystemLoader.OnWorldUnload();
        Main.fastForwardTimeToDawn = false;
        Main.fastForwardTimeToDusk = false;
        Main.UpdateTimeRate();
        Main.menuMode = 0;
        if (threadContext != null)
        {
            ((Action)threadContext)();
        }
    }
References Terraria.Main.ActivePlayerFileData, Terraria.IO.WorldFile.CacheSaveTime(), Terraria.Player.ClearPlayerTempInfo(), Terraria.Rain.ClearRain(), Terraria.Main.netMode, Terraria.ModLoader.SystemLoader.OnWorldUnload(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Graphics.Capture.CaptureInterface.ResetFocus(), Terraria.Player.SavePlayer(), Terraria.IO.WorldFile.SaveWorld(), Terraria.Audio.SoundEngine.StopTrackedSounds(), and Terraria.Main.UpdateTimeRate().
Referenced by Terraria.WorldGen.SaveAndQuit().