TModLoader: Terraria.WorldGen.playWorldCallBack
playWorldCallBack()
static void Terraria.WorldGen.playWorldCallBack (object threadContext) inline static
Definition at line 3550 of file WorldGen.cs.
    {
        Logging.Terraria.InfoFormat("Loading World: {0}, IsCloud={1}, Width: {2}, Height: {3}, Evil: {4}, GameMode: {5}", new object[6]
        {
            Main.ActiveWorldFileData.Name,
            Main.ActiveWorldFileData.IsCloudSave,
            Main.ActiveWorldFileData.WorldSizeX,
            Main.ActiveWorldFileData.WorldSizeY,
            Main.ActiveWorldFileData.HasCrimson.ToInt(),
            Main.ActiveWorldFileData.GameMode
        });
        if (Main.rand == null)
        {
            Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
        }
        for (int i = 0; i < 255; i++)
        {
            if (i != Main.myPlayer)
            {
                Main.player[i].active = false;
            }
        }
        noMapUpdate = true;
        Main.ToggleGameplayUpdates(state: false);
        WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
        if (loadFailed || !loadSuccess)
        {
            WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
            if (loadFailed || !loadSuccess)
            {
                bool isCloudSave = Main.ActiveWorldFileData.IsCloudSave;
                if (FileUtilities.Exists(Main.worldPathName + ".bak", isCloudSave))
                {
                    worldBackup = true;
                }
                else
                {
                    worldBackup = false;
                }
                if (!Main.dedServ)
                {
                    if (worldBackup)
                    {
                        Main.menuMode = 200;
                    }
                    else
                    {
                        Main.menuMode = 201;
                    }
                    return;
                }
                if (!worldBackup)
                {
                    string message = Language.GetTextValue("Error.LoadFailedNoBackup");
                    if (WorldIO.customDataFail != null)
                    {
                        message = WorldIO.customDataFail.modName + " " + message;
                        message = message + "\n" + WorldIO.customDataFail.InnerException;
                    }
                    Console.WriteLine(message);
                    return;
                }
                FileUtilities.Copy(Main.worldPathName, Main.worldPathName + ".bad", isCloudSave);
                FileUtilities.Copy(Main.worldPathName + ".bak", Main.worldPathName, isCloudSave);
                FileUtilities.Delete(Main.worldPathName + ".bak", isCloudSave);
                WorldIO.LoadDedServBackup(Main.worldPathName, isCloudSave);
                WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
                if (loadFailed || !loadSuccess)
                {
                    WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
                    if (loadFailed || !loadSuccess)
                    {
                        FileUtilities.Copy(Main.worldPathName, Main.worldPathName + ".bak", isCloudSave);
                        FileUtilities.Copy(Main.worldPathName + ".bad", Main.worldPathName, isCloudSave);
                        FileUtilities.Delete(Main.worldPathName + ".bad", isCloudSave);
                        WorldIO.RevertDedServBackup(Main.worldPathName, isCloudSave);
                        string message2 = Language.GetTextValue("Error.LoadFailed");
                        if (WorldIO.customDataFail != null)
{
                            message2 = $"{WorldIO.customDataFail.modName} {message2}\r\n{WorldIO.customDataFail.InnerException}";
                        }
                        Console.WriteLine(message2);
                        return;
                    }
                }
            }
        }
        if (Main.mapEnabled)
        {
            Main.Map.Load();
        }
        if (Main.netMode != 2)
        {
            Main.sectionManager.SetAllSectionsLoaded();
        }
        while (Main.loadMapLock)
        {
            float num = (float)Main.loadMapLastX / (float)Main.maxTilesX;
            Main.statusText = Lang.gen[68].Value + " " + (int)(num * 100f + 1f) + "%";
            Thread.Sleep(0);
            if (!Main.mapEnabled)
            {
                break;
            }
        }
        if (Main.gameMenu)
        {
            Main.gameMenu = false;
        }
        if (Main.netMode == 0 && Main.anglerWhoFinishedToday.Contains(Main.player[Main.myPlayer].name))
        {
            Main.anglerQuestFinished = true;
        }
        Main.QueueMainThreadAction(FinishPlayWorld);
    }
References Terraria.Main.ActiveWorldFileData, Terraria.Main.anglerWhoFinishedToday, Terraria.ModLoader.Console, Terraria.Utilities.FileUtilities.Copy(), Terraria.ModLoader.IO.WorldIO.customDataFail, Terraria.Main.dedServ, Terraria.Utilities.FileUtilities.Delete(), Terraria.Utilities.FileUtilities.Exists(), Terraria.WorldGen.FinishPlayWorld(), Terraria.Main.gameMenu, Terraria.Lang.gen, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.IO.WorldIO.LoadDedServBackup(), Terraria.WorldGen.loadFailed, Terraria.Main.loadMapLastX, Terraria.Main.loadMapLock, Terraria.WorldGen.loadSuccess, Terraria.IO.WorldFile.LoadWorld(), Terraria.Main.Map, Terraria.Main.mapEnabled, Terraria.Main.maxTilesX, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.WorldGen.noMapUpdate, Terraria.Main.player, Terraria.Main.QueueMainThreadAction(), Terraria.Main.rand, Terraria.ModLoader.IO.WorldIO.RevertDedServBackup(), Terraria.Main.sectionManager, Terraria.ModLoader.Logging.Terraria, Terraria.Main.ToggleGameplayUpdates(), Terraria.WorldGen.worldBackup, and Terraria.Main.worldPathName.
Referenced by Terraria.WorldGen.playWorld().