TModLoader: Terraria.WorldGen.CheckPot
CheckPot()
static void Terraria.WorldGen.CheckPot (int i, int j, int type = 28) inline static
    {
        //IL_02b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0305: Unknown result type (might be due to invalid IL or missing references)
        //IL_030c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0312: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        //IL_0337: Unknown result type (might be due to invalid IL or missing references)
        //IL_033d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_0360: Unknown result type (might be due to invalid IL or missing references)
        //IL_0366: Unknown result type (might be due to invalid IL or missing references)
        //IL_0382: Unknown result type (might be due to invalid IL or missing references)
        //IL_0389: Unknown result type (might be due to invalid IL or missing references)
        //IL_038f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0402: Unknown result type (might be due to invalid IL or missing references)
        //IL_0409: Unknown result type (might be due to invalid IL or missing references)
        //IL_040f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0430: Unknown result type (might be due to invalid IL or missing references)
        //IL_0437: Unknown result type (might be due to invalid IL or missing references)
        //IL_043d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0459: Unknown result type (might be due to invalid IL or missing references)
        //IL_0460: Unknown result type (might be due to invalid IL or missing references)
        //IL_0466: Unknown result type (might be due to invalid IL or missing references)
        //IL_0482: Unknown result type (might be due to invalid IL or missing references)
        //IL_0489: Unknown result type (might be due to invalid IL or missing references)
        //IL_048f: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0512: Unknown result type (might be due to invalid IL or missing references)
        //IL_0519: Unknown result type (might be due to invalid IL or missing references)
        //IL_051f: Unknown result type (might be due to invalid IL or missing references)
        //IL_053b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0542: Unknown result type (might be due to invalid IL or missing references)
        //IL_0548: Unknown result type (might be due to invalid IL or missing references)
        //IL_0575: Unknown result type (might be due to invalid IL or missing references)
        //IL_057c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0582: Unknown result type (might be due to invalid IL or missing references)
        //IL_059e: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05df: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0601: Unknown result type (might be due to invalid IL or missing references)
        //IL_0608: Unknown result type (might be due to invalid IL or missing references)
        //IL_060e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0668: Unknown result type (might be due to invalid IL or missing references)
        //IL_066f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0675: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0721: Unknown result type (might be due to invalid IL or missing references)
        //IL_0728: Unknown result type (might be due to invalid IL or missing references)
        //IL_072e: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07df: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0802: Unknown result type (might be due to invalid IL or missing references)
        //IL_0808: Unknown result type (might be due to invalid IL or missing references)
        //IL_0824: Unknown result type (might be due to invalid IL or missing references)
        //IL_082b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0831: Unknown result type (might be due to invalid IL or missing references)
        //IL_077d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0784: Unknown result type (might be due to invalid IL or missing references)
        //IL_078a: Unknown result type (might be due to invalid IL or missing references)
        if (destroyObject)
        {
            return;
        }
        bool flag = false;
        int num = 0;
        int num2 = j;
        for (num += Main.tile[i, j].frameX / 18; num > 1; num -= 2)
        {
        }
        num *= -1;
        num += i;
        int num3 = Main.tile[i, j].frameY / 18;
        int num4 = 0;
        while (num3 > 1)
        {
            num3 -= 2;
            num4++;
        }
        num2 -= num3;
        for (int k = num; k < num + 2; k++)
        {
            for (int l = num2; l < num2 + 2; l++)
            {
                if (Main.tile[k, l] == null)
                {
                    Main.tile[k, l] = default(Tile);
                }
                int num5;
                for (num5 = Main.tile[k, l].frameX / 18; num5 > 1; num5 -= 2)
                {
                }
                if (!Main.tile[k, l].active() || Main.tile[k, l].type != type || num5 != k - num || Main.tile[k, l].frameY != (l - num2) * 18 + num4 * 36)
                {
                    flag = true;
                }
            }
            if (Main.tile[k, num2 + 2] == null)
            {
                Main.tile[k, num2 + 2] = default(Tile);
            }
            if (!SolidTile2(k, num2 + 2))
            {
                flag = true;
            }
        }
        if (!flag)
        {
            return;
        }
        destroyObject = true;
        if (num4 >= 7 && num4 <= 9)
        {
            SoundEngine.PlaySound(6, i * 16, j * 16);
        }
        else if (num4 >= 16 && num4 <= 24)
        {
            SoundEngine.PlaySound(4, i * 16, j * 16);
        }
        else
        {
            SoundEngine.PlaySound(13, i * 16, j * 16);
        }
        bool drop = TileLoader.Drop(i, j, type);
        for (int m = num; m < num + 2; m++)
        {
            for (int n = num2; n < num2 + 2; n++)
            {
                if (Main.tile[m, n].type == type && Main.tile[m, n].active())
                {
                    KillTile(m, n);
                }
            }
        }
        using (new Item.DisableNewItemMethod(!drop))
        {
            switch (num4)
            {
            case 0:
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 51);
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 52);
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 53);
                break;
            case 1:
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 166);
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 167);
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 168);
                break;
            case 2:
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 169);
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 170);
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 171);
                break;
            case 3:
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 172);
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 173);
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 174);
                break;
            case 4:
            case 5:
            case 6:
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 197);
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 198);
                break;
            case 7:
            case 8:
            case 9:
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 199);
                Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 200);
                break;
            default:
                if (num4 >= 10 && num4 <= 12)
                {
                    Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 201);
                    Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 202);
                }
                else if (num4 >= 13 && num4 <= 15)
                {
                    Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 203);
                    Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 204);
                }
                else
                {
                    if ((num4 >= 16 && num4 <= 18) || (num4 >= 19 && num4 <= 21) || (num4 >= 22 && num4 <= 24))
                    {
                        break;
                    }
                    if (num4 >= 25 && num4 <= 27)
                    {
                        Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), genRand.Next(217, 220));
                        Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), genRand.Next(217, 220));
                    }
                    else if (num4 >= 28 && num4 <= 30)
                    {
                        Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), genRand.Next(315, 317));
                        Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), genRand.Next(315, 317));
                    }
                    else if (num4 >= 31 && num4 <= 33)
                    {
                        int num6 = genRand.Next(2, 5);
                        for (int num7 = 0; num7 < num6; num7++)
{
                            Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 698 + genRand.Next(6));
                        }
                    }
                    else if (num4 >= 34 && num4 <= 36)
                    {
                        Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 1122);
                        Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 1123);
                        Gore.NewGore(new Vector2((float)(i * 16), (float)(j * 16)), default(Vector2), 1124);
                    }
                }
                break;
            }
            if (Main.netMode != 1 && type != 653)
            {
                SpawnThingsFromPot(i, j, num, num2, num4);
            }
            destroyObject = false;
        }
    }
References Terraria.ModLoader.TileLoader.Drop(), Terraria.Main.netMode, Terraria.Gore.NewGore(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.tile.