TModLoader: Terraria.WorldGen.CheckJunglePlant
CheckJunglePlant()
static void Terraria.WorldGen.CheckJunglePlant (int i, int j, int type) inline static
Definition at line 41009 of file WorldGen.cs.
    {
        if (destroyObject)
        {
            return;
        }
        Tile tile = Main.tile[i, j];
        if (tile.frameY < 36)
        {
            tile = Main.tile[i, j];
            if (tile.type != 236)
            {
                tile = Main.tile[i, j];
                if (tile.type != 238)
                {
                    bool flag2 = false;
                    int num3 = j;
                    int num19 = num3;
                    tile = Main.tile[i, j];
                    num3 = num19 + tile.frameY / 18 * -1;
                    tile = Main.tile[i, j];
                    int num4 = tile.frameX / 18;
                    int num5 = 0;
                    while (num4 > 2)
                    {
                        num4 -= 3;
                        num5++;
                    }
                    num4 = i - num4;
                    int num6 = num5 * 54;
                    for (int num7 = num4; num7 < num4 + 3; num7++)
                    {
                        for (int num8 = num3; num8 < num3 + 2; num8++)
{
                            if (Main.tile[num7, num8] == null)
{
                                tile = (Main.tile[num7, num8] = default(Tile));
                            }
                            tile = Main.tile[num7, num8];
                            if (tile.active())
{
                                tile = Main.tile[num7, num8];
                                if (tile.type == type)
{
                                    tile = Main.tile[num7, num8];
                                    if (tile.frameX == (num7 - num4) * 18 + num6)
{
                                        tile = Main.tile[num7, num8];
                                        if (tile.frameY == (num8 - num3) * 18)
{
                                            continue;
                                        }
                                    }
                                }
                            }
                            flag2 = true;
                        }
                        if (Main.tile[num7, num3 + 2] == null)
{
                            tile = (Main.tile[num7, num3 + 2] = default(Tile));
                        }
                        if (SolidTile(num7, num3 + 2))
{
                            tile = Main.tile[num7, num3 + 2];
                            if (tile.type == 60)
{
                                continue;
                            }
                        }
                        flag2 = true;
                    }
                    if (!flag2)
                    {
                        return;
                    }
                    tile = Main.tile[i, j];
                    _ = ref tile.frameX;
                    destroyObject = true;
                    TileLoader.Drop(i, j, type);
                    for (int num9 = num4; num9 < num4 + 3; num9++)
                    {
                        for (int num10 = num3; num10 < num3 + 3; num10++)
{
                            if (Main.tile[num9, num10] == null)
{
                                tile = (Main.tile[num9, num10] = default(Tile));
                            }
                            tile = Main.tile[num9, num10];
                            if (tile.type == type)
{
                                tile = Main.tile[num9, num10];
                                if (tile.active())
{
                                    KillTile(num9, num10);
                                }
                            }
                        }
                    }
                    destroyObject = false;
                    return;
                }
            }
        }
        bool flag = false;
        tile = Main.tile[i, j];
        int num = tile.frameX / 18;
        int num11 = 0;
        while (num > 1)
        {
            num -= 2;
            num11++;
        }
        num = i - num;
        int num12 = 36;
        if (type == 236 || type == 238)
        {
            num12 = 0;
        }
        tile = Main.tile[i, j];
        int num13;
        for (num13 = tile.frameY / 18; num13 > 1; num13 -= 2)
        {
        }
        num13 = j - num13;
        int num14 = num11 * 36;
        for (int k = num; k < num + 2; k++)
        {
            for (int l = num13; l < num13 + 2; l++)
            {
                if (Main.tile[k, l] == null)
                {
                    tile = (Main.tile[k, l] = default(Tile));
                }
                tile = Main.tile[k, l];
                if (tile.active())
                {
                    tile = Main.tile[k, l];
                    if (tile.type == type)
                    {
                        tile = Main.tile[k, l];
                        if (tile.frameX == (k - num) * 18 + num14)
{
                            tile = Main.tile[k, l];
                            if (tile.frameY == (l - num13) * 18 + num12)
{
                                continue;
                            }
                        }
                    }
                }
                flag = true;
            }
            if (Main.tile[k, num13 + 2] == null)
            {
                tile = (Main.tile[k, num13 + 2] = default(Tile));
            }
            if (SolidTile(k, num13 + 2))
            {
                tile = Main.tile[k, num13 + 2];
                if (tile.type == 60)
                {
                    continue;
                }
            }
            flag = true;
        }
        if (!flag)
        {
            return;
        }
        if (type == 238)
        {
            float num15 = i * 16;
            float num16 = j * 16;
            float num17 = -1f;
            int plr = 0;
            for (int m = 0; m < 255; m++)
            {
                float num18 = Math.Abs(Main.player[m].position.X - num15) + Math.Abs(Main.player[m].position.Y - num16);
                if (num18 < num17 || num17 == -1f)
                {
                    plr = m;
                    num17 = num18;
                }
            }
            if (num17 / 16f < 50f)
            {
                NPC.SpawnOnPlayer(plr, 262);
            }
        }
        using (new Item.DisableNewItemMethod(!TileLoader.Drop(i, j, type)))
        {
            if (type == 236)
            {
                Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1291);
            }
            tile = Main.tile[i, j];
            _ = ref tile.frameX;
            destroyObject = true;
            for (int n = num; n < num + 2; n++)
            {
                for (int num2 = num13; num2 < num13 + 2; num2++)
                {
                    if (Main.tile[n, num2] == null)
                    {
                        tile = (Main.tile[n, num2] = default(Tile));
                    }
                    tile = Main.tile[n, num2];
                    if (tile.type == type)
                    {
                        tile = Main.tile[n, num2];
                        if (tile.active())
{
                            KillTile(n, num2);
                        }
                    }
                }
            }
            destroyObject = false;
        }
    }
References Terraria.Tile.active(), Terraria.ModLoader.TileLoader.Drop(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Item.NewItem(), Terraria.Main.player, Terraria.Enums.SolidTile, Terraria.NPC.SpawnOnPlayer(), Terraria.Main.tile, and Terraria.Tile.type.