TModLoader: Terraria.WorldGen.GrowCatTail
GrowCatTail()
static void Terraria.WorldGen.GrowCatTail (int x, int j) inline static
Definition at line 53133 of file WorldGen.cs.
    {
        if (Main.netMode == 1)
        {
            return;
        }
        int num = j;
        Tile tile;
        while (true)
        {
            tile = Main.tile[x, num];
            if (tile.liquid <= 0 || num <= 50)
            {
                break;
            }
            num--;
        }
        num++;
        int i = num;
        while (true)
        {
            tile = Main.tile[x, i];
            if (tile.active())
            {
                bool[] tileSolid = Main.tileSolid;
                tile = Main.tile[x, i];
                if (tileSolid[tile.type])
                {
                    bool[] tileSolidTop = Main.tileSolidTop;
                    tile = Main.tile[x, i];
                    if (!tileSolidTop[tile.type])
                    {
                        break;
                    }
                }
            }
            if (i >= Main.maxTilesY - 50)
            {
                break;
            }
            i++;
        }
        num = i - 1;
        while (true)
        {
            tile = Main.tile[x, num];
            if (!tile.active())
            {
                break;
            }
            tile = Main.tile[x, num];
            if (tile.type != 519)
            {
                break;
            }
            num--;
        }
        num++;
        tile = Main.tile[x, num];
        if (tile.frameX == 90)
        {
            tile = Main.tile[x, num - 1];
            if (tile.active())
            {
                bool[] tileCut = Main.tileCut;
                tile = Main.tile[x, num - 1];
                if (tileCut[tile.type])
                {
                    KillTile(x, num - 1);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(17, -1, -1, null, 0, x, num - 1);
                    }
                }
            }
        }
        tile = Main.tile[x, num - 1];
        if (tile.active())
        {
            return;
        }
        tile = Main.tile[x, num];
        if (tile.frameX == 0)
        {
            tile = Main.tile[x, num];
            tile.frameX = 18;
            SquareTileFrame(x, num);
            if (Main.netMode == 2)
            {
                NetMessage.SendTileSquare(-1, x, num);
            }
        }
        else
        {
            tile = Main.tile[x, num];
            if (tile.frameX == 18)
            {
                tile = Main.tile[x, num];
                tile.frameX = (short)(18 * genRand.Next(2, 5));
                tile = Main.tile[x, num - 1];
                tile.active(active: true);
                tile = Main.tile[x, num - 1];
                tile.type = 519;
                tile = Main.tile[x, num - 1];
                tile.frameX = 90;
                tile = Main.tile[x, num - 1];
                ref short frameY = ref tile.frameY;
                tile = Main.tile[x, num];
                frameY = tile.frameY;
                tile = Main.tile[x, num - 1];
                tile.halfBrick(halfBrick: false);
                tile = Main.tile[x, num - 1];
                tile.slope(0);
                tile = Main.tile[x, num - 1];
                tile.CopyPaintAndCoating(Main.tile[x, num]);
                SquareTileFrame(x, num);
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, x, num);
                }
            }
            else
            {
                tile = Main.tile[x, num];
                if (tile.frameX == 90)
                {
                    tile = Main.tile[x, num - 1];
                    if (tile.liquid == 0)
                    {
                        tile = Main.tile[x, num - 2];
                        if (!tile.active())
{
                            tile = Main.tile[x, num];
                            if (tile.liquid <= 0)
{
                                tile = Main.tile[x, num + 1];
                                if (tile.liquid <= 0)
{
                                    tile = Main.tile[x, num + 2];
                                    if (tile.liquid <= 0)
{
                                        goto IL_0482;
                                    }
                                }
                            }
                            if (genRand.Next(3) == 0)
{
                                tile = Main.tile[x, num];
                                tile.frameX = 108;
                                tile = Main.tile[x, num - 1];
                                tile.active(active: true);
                                tile = Main.tile[x, num - 1];
                                tile.type = 519;
                                tile = Main.tile[x, num - 1];
                                tile.frameX = 90;
                                tile = Main.tile[x, num - 1];
                                ref short frameY2 = ref tile.frameY;
                                tile = Main.tile[x, num];
                                frameY2 = tile.frameY;
                                tile = Main.tile[x, num - 1];
                                tile.halfBrick(halfBrick: false);
                                tile = Main.tile[x, num - 1];
                                tile.slope(0);
                                tile = Main.tile[x, num - 1];
                                tile.CopyPaintAndCoating(Main.tile[x, num]);
                                SquareTileFrame(x, num);
                                goto IL_0670;
                            }
                        }
                        goto IL_0482;
                    }
                    tile = Main.tile[x, num];
                    tile.frameX = 108;
                    tile = Main.tile[x, num - 1];
                    tile.active(active: true);
                    tile = Main.tile[x, num - 1];
                    tile.type = 519;
                    tile = Main.tile[x, num - 1];
                    tile.frameX = 90;
                    tile = Main.tile[x, num - 1];
                    ref short frameY3 = ref tile.frameY;
                    tile = Main.tile[x, num];
                    frameY3 = tile.frameY;
                    tile = Main.tile[x, num - 1];
                    tile.halfBrick(halfBrick: false);
                    tile = Main.tile[x, num - 1];
                    tile.slope(0);
                    tile = Main.tile[x, num - 1];
                    tile.CopyPaintAndCoating(Main.tile[x, num]);
                    SquareTileFrame(x, num);
                }
            }
        }
        goto IL_0670;
        IL_0670:
        SquareTileFrame(x, num - 1, resetFrame: false);
        if (Main.netMode == 2)
        {
            NetMessage.SendTileSquare(-1, x, num - 1, 1, 2);
        }
        return;
        IL_0482:
        int num2 = genRand.Next(3);
        tile = Main.tile[x, num];
        tile.frameX = (short)(126 + num2 * 18);
        tile = Main.tile[x, num - 1];
        tile.active(active: true);
        tile = Main.tile[x, num - 1];
        tile.type = 519;
        tile = Main.tile[x, num - 1];
        tile.frameX = (short)(180 + num2 * 18);
        tile = Main.tile[x, num - 1];
        ref short frameY4 = ref tile.frameY;
        tile = Main.tile[x, num];
        frameY4 = tile.frameY;
        tile = Main.tile[x, num - 1];
        tile.halfBrick(halfBrick: false);
        tile = Main.tile[x, num - 1];
        tile.slope(0);
        tile = Main.tile[x, num - 1];
        tile.CopyPaintAndCoating(Main.tile[x, num]);
        SquareTileFrame(x, num);
        goto IL_0670;
    }
References Terraria.Tile.active(), Terraria.Tile.CopyPaintAndCoating(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.halfBrick(), Terraria.Tile.liquid, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.