TModLoader: Terraria.WorldGen.CheckLilyPad
CheckLilyPad()
static void Terraria.WorldGen.CheckLilyPad (int x, int y) inline static
Definition at line 53474 of file WorldGen.cs.
    {
        if (Main.netMode == 1)
        {
            return;
        }
        Tile tile = Main.tile[x, y];
        if (tile.liquidType() != 0)
        {
            KillTile(x, y);
            if (Main.netMode == 2)
            {
                NetMessage.SendData(17, -1, -1, null, 0, x, y);
            }
            return;
        }
        int num = y;
        while (true)
        {
            tile = Main.tile[x, num];
            if (tile.active())
            {
                bool[] tileSolid = Main.tileSolid;
                tile = Main.tile[x, num];
                if (tileSolid[tile.type])
                {
                    bool[] tileSolidTop = Main.tileSolidTop;
                    tile = Main.tile[x, num];
                    if (!tileSolidTop[tile.type])
                    {
                        break;
                    }
                }
            }
            if (num >= Main.maxTilesY - 50)
            {
                break;
            }
            num++;
            if (Main.tile[x, num] == null)
            {
                return;
            }
        }
        tile = Main.tile[x, num];
        int type = tile.type;
        int num2 = -1;
        if (type == 2 || type == 477)
        {
            num2 = 0;
        }
        if (type == 109 || type == 109 || type == 116)
        {
            num2 = 18;
        }
        if (type == 60)
        {
            num2 = 36;
        }
        if (num2 >= 0)
        {
            int num3 = num2;
            tile = Main.tile[x, y];
            if (num3 != tile.frameY)
            {
                tile = Main.tile[x, y];
                tile.frameY = (short)num2;
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, x, y);
                }
            }
            tile = Main.tile[x, y - 1];
            if (tile.liquid > 0)
            {
                tile = Main.tile[x, y - 1];
                if (!tile.active())
                {
                    tile = Main.tile[x, y - 1];
                    tile.active(active: true);
                    tile = Main.tile[x, y - 1];
                    tile.type = 518;
                    tile = Main.tile[x, y - 1];
                    ref short frameX = ref tile.frameX;
                    tile = Main.tile[x, y];
                    frameX = tile.frameX;
                    tile = Main.tile[x, y - 1];
                    ref short frameY = ref tile.frameY;
                    tile = Main.tile[x, y];
                    frameY = tile.frameY;
                    tile = Main.tile[x, y - 1];
                    tile.halfBrick(halfBrick: false);
                    tile = Main.tile[x, y - 1];
                    tile.slope(0);
                    tile = Main.tile[x, y];
                    tile.active(active: false);
                    tile = Main.tile[x, y];
                    tile.type = 0;
                    SquareTileFrame(x, y - 1, resetFrame: false);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, x, y - 1, 1, 2);
                    }
                    return;
                }
            }
            tile = Main.tile[x, y];
            if (tile.liquid != 0)
            {
                return;
            }
            Tile tileSafely = Framing.GetTileSafely(x, y + 1);
            if (!tileSafely.active())
            {
                tile = Main.tile[x, y + 1];
                tile.active(active: true);
                tile = Main.tile[x, y + 1];
                tile.type = 518;
                tile = Main.tile[x, y + 1];
                ref short frameX2 = ref tile.frameX;
                tile = Main.tile[x, y];
                frameX2 = tile.frameX;
                tile = Main.tile[x, y + 1];
                ref short frameY2 = ref tile.frameY;
                tile = Main.tile[x, y];
                frameY2 = tile.frameY;
                tile = Main.tile[x, y + 1];
                tile.halfBrick(halfBrick: false);
                tile = Main.tile[x, y + 1];
                tile.slope(0);
                tile = Main.tile[x, y];
                tile.active(active: false);
                tile = Main.tile[x, y];
                tile.type = 0;
                SquareTileFrame(x, y + 1, resetFrame: false);
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, x, y, 1, 2);
                }
            }
            else if (tileSafely.active() && !TileID.Sets.Platforms[tileSafely.type] && (!Main.tileSolid[tileSafely.type] || Main.tileSolidTop[tileSafely.type]))
            {
                KillTile(x, y);
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, x, y);
                }
            }
        }
        else
        {
            KillTile(x, y);
            if (Main.netMode == 2)
            {
                NetMessage.SendData(17, -1, -1, null, 0, x, y);
            }
        }
    }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Framing.GetTileSafely(), Terraria.Tile.halfBrick(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.ID.TileID.Sets.Platforms, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.Liquid.DelWater().