TModLoader: Terraria.WorldGen.TileFrame
TileFrame()
static void Terraria.WorldGen.TileFrame (int i, int j, bool resetFrame = false, bool noBreak = false) inline static
    {
        //IL_5f3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_5f4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1150: Unknown result type (might be due to invalid IL or missing references)
        //IL_7616: Unknown result type (might be due to invalid IL or missing references)
        //IL_7620: Unknown result type (might be due to invalid IL or missing references)
        //IL_7e87: Unknown result type (might be due to invalid IL or missing references)
        //IL_751f: Unknown result type (might be due to invalid IL or missing references)
        //IL_7e91: Unknown result type (might be due to invalid IL or missing references)
        //IL_7529: Unknown result type (might be due to invalid IL or missing references)
        //IL_7f21: Unknown result type (might be due to invalid IL or missing references)
        //IL_7f31: Unknown result type (might be due to invalid IL or missing references)
        //IL_817e: Unknown result type (might be due to invalid IL or missing references)
        //IL_8189: Unknown result type (might be due to invalid IL or missing references)
        //IL_16c7: Unknown result type (might be due to invalid IL or missing references)
        bool addToList = false;
        try
        {
            if (i > 5 && j > 5 && i < Main.maxTilesX - 5 && j < Main.maxTilesY - 5 && Main.tile[i, j] != null)
            {
                if (SkipFramingBecauseOfGen && !Main.tileFrameImportant[Main.tile[i, j].type])
                {
                    return;
                }
                addToList = UpdateMapTile(i, j);
                Tile tile = Main.tile[i, j];
                if (!tile.active())
                {
                    tile.halfBrick(halfBrick: false);
                    tile.ClearBlockPaintAndCoating();
                    tile.slope(0);
                }
                if (tile.liquid > 0 && Main.netMode != 1 && !noLiquidCheck)
                {
                    Liquid.AddWater(i, j);
                }
                if (tile.active())
                {
                    if (!TileLoader.TileFrame(i, j, tile.type, ref resetFrame, ref noBreak) || (noBreak && Main.tileFrameImportant[tile.type] && !TileID.Sets.Torch[tile.type]))
                    {
                        return;
                    }
                    int num = tile.type;
                    if (Main.tileStone[num])
                    {
                        num = 1;
                    }
                    int frameX = tile.frameX;
                    int frameY = tile.frameY;
                    Rectangle rectangle = default(Rectangle);
                    ((Rectangle)(ref rectangle))._002Ector(-1, -1, 0, 0);
                    int num43;
                    if (Main.tileFrameImportant[tile.type])
                    {
                        num43 = num;
                        switch (num43)
{
                        case 518:
                            CheckLilyPad(i, j);
                            return;
                        case 519:
                            CheckCatTail(i, j);
                            return;
                        case 549:
                            CheckUnderwaterPlant(549, i, j);
                            return;
                        case 571:
                            CheckBamboo(i, j);
                            return;
                        }
                        if (!TileID.Sets.Torch[num])
{
                            switch (num43)
{
                            case 442:
                                CheckProjectilePressurePad(i, j);
                                break;
                            case 136:
{
                                Tile tile3 = Main.tile[i, j - 1];
                                Tile tile17 = Main.tile[i, j + 1];
                                Tile tile24 = Main.tile[i - 1, j];
                                Tile tile31 = Main.tile[i + 1, j];
                                Tile tile35 = Main.tile[i - 1, j + 1];
                                Tile tile38 = Main.tile[i + 1, j + 1];
                                Tile tile41 = Main.tile[i - 1, j - 1];
                                Tile tile44 = Main.tile[i + 1, j - 1];
                                int num13 = -1;
                                int num14 = -1;
                                int num15 = -1;
                                int tree = -1;
                                int tree2 = -1;
                                int tree3 = -1;
                                int tree4 = -1;
                                if (tile3 != null && tile3.nactive())
{
                                    _ = ref tile3.type;
                                }
                                if (tile17 != null && tile17.nactive() && !tile17.halfBrick() && !tile17.topSlope())
{
                                    num13 = tile17.type;
                                }
                                if (tile24 != null && tile24.nactive())
{
                                    num14 = tile24.type;
                                }
                                if (tile31 != null && tile31.nactive())
{
                                    num15 = tile31.type;
                                }
                                if (tile35 != null && tile35.nactive())
{
                                    tree = tile35.type;
                                }
                                if (tile38 != null && tile38.nactive())
{
                                    tree2 = tile38.type;
                                }
                                if (tile41 != null && tile41.nactive())
{
                                    tree3 = tile41.type;
                                }
                                if (tile44 != null && tile44.nactive())
{
                                    tree4 = tile44.type;
                                }
                                if (num13 >= 0 && Main.tileSolid[num13] && !Main.tileNoAttach[num13] && tile17 != null && !tile17.halfBrick() && (tile17.slope() == 0 || tile17.bottomSlope()))
{
                                    tile.frameX = 0;
                                }
                                else if ((num14 >= 0 && Main.tileSolid[num14] && !Main.tileNoAttach[num14] && tile24 != null && (tile24.leftSlope() || tile24.slope() == 0) && !tile24.halfBrick()) || (num14 >= 0 && TileID.Sets.IsBeam[num14]) || (IsTreeType(num14) && IsTreeType(tree3) && IsTreeType(tree)))
{
                                    tile.frameX = 18;
                                }
                                else if ((num15 >= 0 && Main.tileSolid[num15] && !Main.tileNoAttach[num15] && tile31 != null && (tile31.rightSlope() || tile31.slope() == 0) && !tile31.halfBrick()) || (num15 >= 0 && TileID.Sets.IsBeam[num15]) || (IsTreeType(num15) && IsTreeType(tree4) && IsTreeType(tree2)))
{
                                    tile.frameX = 36;
                                }
                                else if (tile.wall > 0)
{
                                    tile.frameX = 54;
                                }
                                else
{
                                    KillTile(i, j);
                                }
                                break;
                            }
                            case 129:
                            case 149:
{
                                Tile tile9 = Main.tile[i, j - 1];
                                Tile tile18 = Main.tile[i, j + 1];
                                Tile tile25 = Main.tile[i - 1, j];
                                Tile tile32 = Main.tile[i + 1, j];
                                int num16 = -1;
                                int num17 = -1;
                                int num18 = -1;
                                int num19 = -1;
                                if (tile9 != null && tile9.nactive() && !tile9.bottomSlope())
{
                                    num17 = tile9.type;
                                }
                                if (tile18 != null && tile18.nactive() && !tile18.halfBrick() && !tile18.topSlope())
{
                                    num16 = tile18.type;
                                }
                                if (tile25 != null && tile25.nactive() && !tile32.rightSlope())
{
                                    num18 = tile25.type;
                                }
                                if (tile32 != null && tile32.nactive() && !tile32.leftSlope())
{
                                    num19 = tile32.type;
                                }
                                if (num16 >= 0 && Main.tileSolid[num16] && !Main.tileSolidTop[num16])
{
                                    tile.frameY = 0;
                                }
                                else if (num18 >= 0 && Main.tileSolid[num18] && !Main.tileSolidTop[num18])
{
                                    tile.frameY = 54;
                                }
                                else if (num19 >= 0 && Main.tileSolid[num19] && !Main.tileSolidTop[num19])
{
                                    tile.frameY = 36;
                                }
                                else if (num17 >= 0 && Main.tileSolid[num17] && !Main.tileSolidTop[num17])
{
                                    tile.frameY = 18;
                                }
                                else
{
                                    KillTile(i, j);
                                }
                                break;
                            }
                            default:
                                if (num != 461)
{
                                    switch (num)
{
                                    case 178:
{
                                        Tile tile6 = Main.tile[i, j - 1];
                                        Tile tile14 = Main.tile[i, j + 1];
                                        Tile tile22 = Main.tile[i - 1, j];
                                        Tile tile29 = Main.tile[i + 1, j];
                                        int num7 = -1;
                                        int num8 = -1;
                                        int num9 = -1;
                                        int num10 = -1;
                                        if (tile6 != null && tile6.nactive() && !tile6.bottomSlope())
{
                                            num8 = tile6.type;
                                        }
                                        if (tile14 != null && tile14.nactive() && !tile14.halfBrick() && !tile14.topSlope())
{
                                            num7 = tile14.type;
                                        }
                                        if (tile22 != null && tile22.nactive() && !tile22.halfBrick() && !tile22.rightSlope())
{
                                            num9 = tile22.type;
                                        }
                                        if (tile29 != null && tile29.nactive() && !tile29.halfBrick() && !tile29.leftSlope())
{
                                            num10 = tile29.type;
                                        }
                                        if (num9 == 10)
{
                                            num9 = -1;
                                        }
                                        if (num10 == 10)
{
                                            num10 = -1;
                                        }
                                        short num11 = (short)(genRand.Next(3) * 18);
                                        if (num7 >= 0 && Main.tileSolid[num7] && !Main.tileSolidTop[num7])
{
                                            if (tile.frameY < 0 || tile.frameY > 36)
{
                                                tile.frameY = num11;
                                            }
                                        }
                                        else if (num9 >= 0 && Main.tileSolid[num9] && !Main.tileSolidTop[num9])
{
                                            if (tile.frameY < 108 || tile.frameY > 54)
{
                                                tile.frameY = (short)(108 + num11);
                                            }
                                        }
                                        else if (num10 >= 0 && Main.tileSolid[num10] && !Main.tileSolidTop[num10])
{
                                            if (tile.frameY < 162 || tile.frameY > 198)
{
                                                tile.frameY = (short)(162 + num11);
                                            }
                                        }
                                        else if (num8 >= 0 && Main.tileSolid[num8] && !Main.tileSolidTop[num8])
{
                                            if (tile.frameY < 54 || tile.frameY > 90)
{
                                                tile.frameY = (short)(54 + num11);
                                            }
                                        }
                                        else
{
                                            KillTile(i, j);
                                        }
                                        break;
                                    }
                                    case 184:
{
                                        Tile tile7 = Main.tile[i, j - 1];
                                        Tile tile15 = Main.tile[i, j + 1];
                                        Tile tile23 = Main.tile[i - 1, j];
                                        Tile tile30 = Main.tile[i + 1, j];
                                        int num2 = -1;
                                        int num3 = -1;
                                        int num4 = -1;
                                        int num5 = -1;
                                        if (tile7 != null && tile7.active() && !tile7.bottomSlope())
{
                                            num3 = tile7.type;
                                        }
                                        if (tile15 != null && tile15.active() && !tile15.halfBrick() && !tile15.topSlope())
{
                                            num2 = tile15.type;
                                        }
                                        if (tile23 != null && tile23.active())
{
                                            num4 = tile23.type;
                                        }
                                        if (tile30 != null && tile30.active())
{
                                            num5 = tile30.type;
                                        }
                                        short num6 = (short)(genRand.Next(3) * 18);
                                        if (num2 >= 0 && GetTileMossColor(num2) != -1)
{
                                            tile.frameX = (short)(22 * GetTileMossColor(num2));
                                            if (tile.frameY < 0 || tile.frameY > 36)
{
                                                tile.frameY = num6;
                                            }
                                        }
                                        else if (num3 >= 0 && GetTileMossColor(num3) != -1)
{
                                            tile.frameX = (short)(22 * GetTileMossColor(num3));
                                            if (tile.frameY < 54 || tile.frameY > 90)
{
                                                tile.frameY = (short)(54 + num6);
                                            }
                                        }
                                        else if (num4 >= 0 && GetTileMossColor(num4) != -1)
{
                                            tile.frameX = (short)(22 * GetTileMossColor(num4));
                                            if (tile.frameY < 108 || tile.frameY > 144)
{
                                                tile.frameY = (short)(108 + num6);
                                            }
                                        }
                                        else if (num5 >= 0 && GetTileMossColor(num5) != -1)
{
                                            tile.frameX = (short)(22 * GetTileMossColor(num5));
                                            if (tile.frameY < 162 || tile.frameY > 198)
{
                                                tile.frameY = (short)(162 + num6);
                                            }
                                        }
                                        else
{
                                            KillTile(i, j);
                                        }
                                        break;
                                    }
                                    case 529:
{
                                        if (!SolidTileAllowBottomSlope(i, j + 1))
{
                                            KillTile(i, j);
                                            break;
                                        }
                                        Tile tile16 = Main.tile[i, j + 1];
                                        _ = Main.tile[i, j].frameY / 34;
                                        if (tile16 == null || !tile16.active() || (tile16.type >= 0 && !TileID.Sets.Conversion.Sand[tile16.type]))
{
                                            KillTile(i, j);
                                        }
                                        break;
                                    }
                                    case 3:
                                    case 24:
                                    case 61:
                                    case 71:
                                    case 73:
                                    case 74:
                                    case 110:
                                    case 113:
                                    case 201:
                                    case 637:
                                        PlantCheck(i, j);
                                        break;
                                    case 227:
                                        CheckDye(i, j);
                                        break;
                                    case 579:
                                        CheckRockGolemHead(i, j);
                                        break;
                                    case 12:
                                    case 31:
                                    case 639:
                                        CheckOrb(i, j, num);
                                        break;
                                    case 165:
                                        CheckTight(i, j);
                                        break;
                                    case 324:
                                        if (!SolidTileAllowBottomSlope(i, j + 1))
{
                                            KillTile(i, j);
                                        }
                                        break;
                                    case 235:
                                        Check3x1(i, j, num);
                                        break;
                                    case 185:
                                        CheckPile(i, j);
                                        break;
                                    default:
                                        if (num != 296 && num != 297 && num != 309 && num != 358 && num != 359 && num != 413 && num != 414 && num != 542 && num != 550 && num != 551 && num != 553 && num != 554 && num != 558 && num != 559 && num != 599 && num != 600 && num != 601 && num != 602 && num != 603 && num != 604 && num != 605 && num != 606 && num != 607 && num != 608 && num != 609 && num != 610 && num != 611 && num != 612 && num != 632 && num != 640 && num != 643 && num != 644 && num != 645)
{
                                            if (num == 10)
{
                                                CheckDoorClosed(i, j, tile, num);
                                                break;
                                            }
                                            if (num == 11)
{
                                                CheckDoorOpen(i, j, tile);
                                                break;
                                            }
                                            if (num == 314)
{
                                                Minecart.FrameTrack(i, j, pound: false);
                                                Tile tile2 = Main.tile[i, j - 1];
                                                Tile tile11 = Main.tile[i, j + 1];
                                                if (tile2 != null && tile2.type >= 0 && Main.tileRope[tile2.type])
{
                                                    TileFrame(i, j - 1);
                                                }
                                                if (tile11 != null && tile11.type >= 0 && Main.tileRope[tile11.type])
{
                                                    TileFrame(i, j + 1);
                                                }
                                                break;
                                            }
                                            if (num == 380)
{
                                                Tile tile20 = Main.tile[i - 1, j];
                                                if (tile20 == null)
{
                                                    break;
                                                }
                                                Tile tile27 = Main.tile[i + 1, j];
                                                if (!(tile27 == null) && !(Main.tile[i - 1, j + 1] == null) && !(Main.tile[i + 1, j + 1] == null) && !(Main.tile[i - 1, j - 1] == null) && Main.tile[i + 1, j - 1] != null)
{
                                                    int num12 = -1;
                                                    int num23 = -1;
                                                    if (tile20 != null && tile20.active())
{
                                                        num23 = (Main.tileStone[tile20.type] ? 1 : tile20.type);
                                                    }
                                                    if (tile27 != null && tile27.active())
{
                                                        num12 = (Main.tileStone[tile27.type] ? 1 : tile27.type);
                                                    }
                                                    if (num12 >= 0 && !Main.tileSolid[num12])
{
                                                        num12 = -1;
                                                    }
                                                    if (num23 >= 0 && !Main.tileSolid[num23])
{
                                                        num23 = -1;
                                                    }
                                                    if (num23 == num && num12 == num)
{
                                                        rectangle.X = 18;
                                                    }
                                                    else if (num23 == num && num12 != num)
{
                                                        rectangle.X = 36;
                                                    }
                                                    else if (num23 != num && num12 == num)
{
                                                        rectangle.X = 0;
                                                    }
                                                    else
{
                                                        rectangle.X = 54;
                                                    }
                                                    tile.frameX = (short)rectangle.X;
                                                }
                                                break;
                                            }
                                            if (num >= 0 && TileID.Sets.Platforms[num])
{
                                                Tile tile21 = Main.tile[i - 1, j];
                                                if (tile21 == null)
{
                                                    break;
                                                }
                                                Tile tile28 = Main.tile[i + 1, j];
                                                if (tile28 == null)
{
                                                    break;
                                                }
                                                Tile tile34 = Main.tile[i - 1, j + 1];
                                                if (tile34 == null)
{
                                                    break;
                                                }
                                                Tile tile37 = Main.tile[i + 1, j + 1];
                                                if (tile37 == null)
{
                                                    break;
                                                }
                                                Tile tile40 = Main.tile[i - 1, j - 1];
                                                if (tile40 == null)
{
                                                    break;
                                                }
                                                Tile tile43 = Main.tile[i + 1, j - 1];
                                                if (tile43 == null)
{
                                                    break;
                                                }
                                                int num31 = -1;
                                                int num38 = -1;
                                                if (tile21 != null && tile21.active())
{
                                                    num38 = (Main.tileStone[tile21.type] ? 1 : ((!TileID.Sets.Platforms[tile21.type]) ? tile21.type : num));
                                                }
                                                if (tile28 != null && tile28.active())
{
                                                    num31 = (Main.tileStone[tile28.type] ? 1 : ((!TileID.Sets.Platforms[tile28.type]) ? tile28.type : num));
                                                }
                                                if (num31 >= 0 && !Main.tileSolid[num31])
{
                                                    num31 = -1;
                                                }
                                                if (num38 >= 0 && !Main.tileSolid[num38])
{
                                                    num38 = -1;
                                                }
                                                if (num38 == num && tile21.halfBrick() != tile.halfBrick())
{
                                                    num38 = -1;
                                                }
                                                if (num31 == num && tile28.halfBrick() != tile.halfBrick())
{
                                                    num31 = -1;
                                                }
                                                if (num38 != -1 && num38 != num && tile.halfBrick())
{
                                                    num38 = -1;
                                                }
                                                if (num31 != -1 && num31 != num && tile.halfBrick())
{
                                                    num31 = -1;
                                                }
                                                if (num38 == -1 && tile40.active() && tile40.type == num && tile40.slope() == 1)
{
                                                    num38 = num;
                                                }
                                                if (num31 == -1 && tile43.active() && tile43.type == num && tile43.slope() == 2)
{
                                                    num31 = num;
                                                }
                                                if (num38 == num && tile21.slope() == 2 && num31 != num)
{
                                                    num31 = -1;
                                                }
                                                if (num31 == num && tile28.slope() == 1 && num38 != num)
{
                                                    num38 = -1;
                                                }
                                                if (tile.slope() == 1)
{
                                                    if (TileID.Sets.Platforms[tile28.type] && tile28.slope() == 0 && !tile28.halfBrick())
{
                                                        rectangle.X = 468;
                                                    }
                                                    else if (!tile37.active() && (!TileID.Sets.Platforms[tile37.type] || tile37.slope() == 2))
{
                                                        if (!tile21.active() && (!TileID.Sets.Platforms[tile40.type] || tile40.slope() != 1))
{
                                                            rectangle.X = 432;
                                                        }
                                                        else
{
                                                            rectangle.X = 360;
                                                        }
                                                    }
                                                    else if (!tile21.active() && (!TileID.Sets.Platforms[tile40.type] || tile40.slope() != 1))
{
                                                        rectangle.X = 396;
                                                    }
                                                    else
{
                                                        rectangle.X = 180;
                                                    }
                                                }
                                                else if (tile.slope() == 2)
{
                                                    if (TileID.Sets.Platforms[tile21.type] && tile21.slope() == 0 && !tile21.halfBrick())
{
                                                        rectangle.X = 450;
                                                    }
                                                    else if (!tile34.active() && (!TileID.Sets.Platforms[tile34.type] || tile34.slope() == 1))
{
                                                        if (!tile28.active() && (!TileID.Sets.Platforms[tile43.type] || tile43.slope() != 2))
{
                                                            rectangle.X = 414;
                                                        }
                                                        else
{
                                                            rectangle.X = 342;
                                                        }
                                                    }
                                                    else if (!tile28.active() && (!TileID.Sets.Platforms[tile43.type] || tile43.slope() != 2))
{
                                                        rectangle.X = 378;
                                                    }
                                                    else
{
                                                        rectangle.X = 144;
                                                    }
                                                }
                                                else if (num38 == num && num31 == num)
{
                                                    if (tile21.slope() == 2 && tile28.slope() == 1)
{
                                                        rectangle.X = 252;
                                                    }
                                                    else if (tile21.slope() == 2)
{
                                                        rectangle.X = 216;
                                                    }
                                                    else if (tile28.slope() == 1)
{
                                                        rectangle.X = 234;
                                                    }
                                                    else
{
                                                        rectangle.X = 0;
                                                    }
                                                }
                                                else if (num38 == num && num31 == -1)
{
                                                    if (tile21.slope() == 2)
{
                                                        rectangle.X = 270;
                                                    }
                                                    else
{
                                                        rectangle.X = 18;
                                                    }
                                                }
                                                else if (num38 == -1 && num31 == num)
{
                                                    if (tile28.slope() == 1)
{
                                                        rectangle.X = 288;
                                                    }
                                                    else
{
                                                        rectangle.X = 36;
                                                    }
                                                }
                                                else if (num38 != num && num31 == num)
{
                                                    rectangle.X = 54;
                                                }
                                                else if (num38 == num && num31 != num)
{
                                                    rectangle.X = 72;
                                                }
                                                else if (num38 != num && num38 != -1 && num31 == -1)
{
                                                    rectangle.X = 108;
                                                }
                                                else if (num38 == -1 && num31 != num && num31 != -1)
{
                                                    rectangle.X = 126;
                                                }
                                                else
{
                                                    rectangle.X = 90;
                                                }
                                                tile.frameX = (short)rectangle.X;
                                                if (Main.tile[i, j - 1] != null && Main.tileRope[Main.tile[i, j - 1].type])
{
                                                    TileFrame(i, j - 1);
                                                }
                                                if (Main.tile[i, j + 1] != null && Main.tileRope[Main.tile[i, j + 1].type])
{
                                                    TileFrame(i, j + 1);
                                                }
                                                break;
                                            }
                                            switch (num)
{
                                            case 233:
                                            case 236:
                                            case 238:
                                                CheckJunglePlant(i, j, num);
                                                return;
                                            case 530:
                                                CheckOasisPlant(i, j);
                                                return;
                                            case 240:
                                            case 440:
                                                Check3x3Wall(i, j);
                                                return;
                                            case 245:
                                                Check2x3Wall(i, j);
                                                return;
                                            case 246:
                                                Check3x2Wall(i, j);
                                                return;
                                            case 241:
                                                Check4x3Wall(i, j);
                                                return;
                                            case 242:
                                                Check6x4Wall(i, j);
                                                return;
                                            case 464:
                                            case 466:
                                                Check5x4(i, j, num);
                                                return;
                                            case 334:
                                                CheckWeaponsRack(i, j);
                                                return;
                                            case 471:
                                                TEWeaponsRack.Framing_CheckTile(i, j);
                                                return;
                                            case 34:
                                            case 454:
                                                CheckChand(i, j, num);
                                                return;
                                            case 547:
                                            case 623:
                                                Check2x5(i, j, num);
                                                return;
                                            case 548:
                                            case 614:
                                                Check3x6(i, j, num);
                                                return;
                                            case 613:
                                                Check3x5(i, j, num);
                                                return;
                                            default:
{
                                                if (num == 354 || num == 406 || num == 412 || num == 355 || num == 452 || num == 455 || num == 491 || num == 499 || num == 642)
{
                                                    break;
                                                }
                                                int num44 = num;
                                                if (num44 != 15 && !TileID.Sets.TreeSapling[num])
{
                                                    switch (num44)
{
                                                    case 216:
                                                    case 338:
                                                    case 390:
                                                    case 493:
                                                    case 497:
                                                    case 590:
                                                    case 595:
                                                    case 615:
                                                        break;
                                                    default:
                                                        if (num < 391 || num > 394)
{
                                                            switch (num)
{
                                                            case 36:
                                                            case 135:
                                                            case 141:
                                                            case 144:
                                                            case 210:
                                                            case 239:
                                                            case 428:
                                                            case 593:
                                                            case 624:
                                                            case 650:
                                                            case 656:
                                                                Check1x1(i, j, num);
                                                                return;
                                                            case 476:
                                                                CheckGolf1x1(i, j, num);
                                                                return;
                                                            case 494:
                                                                CheckGolf1x1(i, j, num);
                                                                return;
                                                            case 419:
                                                            case 420:
                                                            case 423:
                                                            case 424:
                                                            case 429:
                                                            case 445:
                                                                CheckLogicTiles(i, j, num);
                                                                return;
                                                            case 16:
                                                            case 18:
                                                            case 29:
                                                            case 103:
                                                            case 134:
                                                            case 462:
                                                            case 649:
                                                                Check2x1(i, j, (ushort)num);
                                                                return;
                                                            case 13:
                                                            case 33:
                                                            case 49:
                                                            case 50:
                                                            case 78:
                                                            case 174:
                                                            case 372:
                                                            case 646:
                                                                CheckOnTable1x1(i, j, num);
                                                                return;
                                                            default:
                                                                if (TileID.Sets.BasicChest[num] && num < TileID.Count)
{
                                                                    CheckChest(i, j, num);
                                                                    return;
                                                                }
                                                                switch (num)
{
                                                                case 128:
                                                                    CheckMan(i, j);
                                                                    return;
                                                                case 269:
                                                                    CheckWoman(i, j);
                                                                    return;
                                                                case 470:
                                                                    TEDisplayDoll.Framing_CheckTile(i, j);
                                                                    return;
                                                                case 475:
                                                                    TEHatRack.Framing_CheckTile(i, j);
                                                                    return;
                                                                case 597:
                                                                    TETeleportationPylon.Framing_CheckTile(i, j);
                                                                    return;
                                                                case 27:
                                                                    CheckSunflower(i, j);
                                                                    return;
                                                                case 28:
                                                                case 653:
                                                                    CheckPot(i, j, num);
                                                                    return;
                                                                case 171:
                                                                    CheckXmasTree(i, j);
                                                                    return;
                                                                default:
                                                                    if ((TileID.Sets.BasicChestFake[num] || num == 457) && num < TileID.Count)
{
                                                                        break;
                                                                    }
                                                                    switch (num)
{
                                                                    case 335:
                                                                    case 411:
                                                                    case 490:
                                                                    case 564:
                                                                    case 565:
                                                                    case 594:
                                                                        Check2x2(i, j, num);
                                                                        return;
                                                                    default:
                                                                        if (num >= 316 && num <= 318)
{
                                                                            break;
                                                                        }
                                                                        switch (num)
{
                                                                        case 376:
                                                                        case 443:
                                                                        case 444:
                                                                        case 485:
                                                                            CheckSuper(i, j, num);
                                                                            return;
                                                                        case 91:
                                                                            CheckBanner(i, j, (byte)num);
                                                                            return;
                                                                        case 35:
                                                                        case 139:
                                                                            CheckMB(i, j, (byte)num);
                                                                            return;
                                                                        case 386:
                                                                        case 387:
                                                                            CheckTrapDoor(i, j, num);
                                                                            return;
                                                                        case 388:
                                                                        case 389:
                                                                            CheckTallGate(i, j, num);
                                                                            return;
                                                                        case 92:
                                                                        case 93:
                                                                        case 453:
                                                                            Check1xX(i, j, (short)num);
                                                                            return;
                                                                        case 104:
                                                                        case 105:
                                                                        case 207:
                                                                        case 320:
                                                                        case 337:
                                                                        case 349:
                                                                        case 356:
                                                                        case 378:
                                                                        case 410:
                                                                        case 456:
                                                                        case 465:
                                                                        case 480:
                                                                        case 489:
                                                                        case 506:
                                                                        case 509:
                                                                        case 531:
                                                                        case 545:
                                                                        case 560:
                                                                        case 591:
                                                                        case 592:
                                                                        case 657:
                                                                        case 658:
                                                                        case 663:
                                                                            Check2xX(i, j, (ushort)num);
                                                                            return;
                                                                        case 101:
                                                                        case 102:
                                                                        case 463:
                                                                        case 617:
                                                                            Check3x4(i, j, num);
                                                                            return;
                                                                        case 42:
                                                                        case 270:
                                                                        case 271:
                                                                        case 572:
                                                                        case 581:
                                                                        case 660:
                                                                            Check1x2Top(i, j, (ushort)num);
                                                                            return;
                                                                        case 55:
                                                                        case 85:
                                                                        case 395:
                                                                        case 425:
                                                                        case 510:
                                                                        case 511:
                                                                        case 573:
                                                                            CheckSign(i, j, (ushort)num);
                                                                            return;
                                                                        case 520:
                                                                            CheckFoodPlatter(i, j, (ushort)num);
                                                                            return;
                                                                        case 209:
                                                                            CheckCannon(i, j, num);
                                                                            return;
                                                                        case 79:
                                                                        case 90:
                                                                        case 487:
                                                                            Check4x2(i, j, num);
                                                                            return;
                                                                        case 94:
                                                                        case 95:
                                                                        case 97:
                                                                        case 98:
                                                                        case 99:
                                                                        case 100:
                                                                        case 125:
                                                                        case 126:
                                                                        case 173:
                                                                        case 282:
                                                                        case 287:
                                                                        case 319:
                                                                        case 621:
                                                                        case 622:
                                                                            Check2x2(i, j, num);
                                                                            return;
                                                                        case 96:
                                                                            Check2x2Style(i, j, num);
                                                                            return;
                                                                        case 81:
{
                                                                            Tile tile5 = Main.tile[i, j - 1];
                                                                            Tile tile13 = Main.tile[i, j + 1];
                                                                            _ = Main.tile[i - 1, j];
                                                                            _ = Main.tile[i + 1, j];
                                                                            int num41 = -1;
                                                                            int num42 = -1;
                                                                            if (tile5 != null && tile5.active())
{
                                                                                num42 = tile5.type;
                                                                            }
                                                                            if (tile13 != null && tile13.active())
{
                                                                                num41 = tile13.type;
                                                                            }
                                                                            if (num42 != -1)
{
                                                                                KillTile(i, j);
                                                                            }
                                                                            else if (num41 < 0 || !Main.tileSolid[num41] || (tile13 != null && (tile13.halfBrick() || tile13.topSlope())))
{
                                                                                KillTile(i, j);
                                                                            }
                                                                            return;
                                                                        }
                                                                        default:
                                                                            if (Main.tileAlch[num])
{
                                                                                CheckAlch(i, j);
                                                                                return;
                                                                            }
                                                                            switch (num)
{
                                                                            case 72:
{
                                                                                Tile tile4 = Main.tile[i, j - 1];
                                                                                Tile tile12 = Main.tile[i, j + 1];
                                                                                int num39 = -1;
                                                                                int num40 = -1;
                                                                                if (tile4 != null && tile4.active())
{
                                                                                    num40 = tile4.type;
                                                                                }
                                                                                if (tile12 != null && tile12.active())
{
                                                                                    num39 = tile12.type;
                                                                                }
                                                                                if (num39 != num && num39 != 70)
{
                                                                                    KillTile(i, j);
                                                                                }
                                                                                else if (num40 != num && tile.frameX == 0)
{
                                                                                    tile.frameNumber((byte)genRand.Next(3));
                                                                                    if (tile.frameNumber() == 0)
{
                                                                                        tile.frameX = 18;
                                                                                        tile.frameY = 0;
                                                                                    }
                                                                                    if (tile.frameNumber() == 1)
{
                                                                                        tile.frameX = 18;
                                                                                        tile.frameY = 18;
                                                                                    }
                                                                                    if (tile.frameNumber() == 2)
{
                                                                                        tile.frameX = 18;
                                                                                        tile.frameY = 36;
                                                                                    }
                                                                                }
                                                                                break;
                                                                            }
                                                                            case 5:
                                                                                CheckTree(i, j);
                                                                                break;
                                                                            case 583:
                                                                            case 584:
                                                                            case 585:
                                                                            case 586:
                                                                            case 587:
                                                                            case 588:
                                                                            case 589:
                                                                                CheckTreeWithSettings(i, j, new CheckTreeSettings
{
                                                                                    IsGroundValid = GemTreeGroundTest
                                                                                });
                                                                                break;
                                                                            case 596:
                                                                                CheckTreeWithSettings(i, j, new CheckTreeSettings
{
                                                                                    IsGroundValid = VanityTreeGroundTest
                                                                                });
                                                                                break;
                                                                            case 616:
                                                                                CheckTreeWithSettings(i, j, new CheckTreeSettings
{
                                                                                    IsGroundValid = VanityTreeGroundTest
                                                                                });
                                                                                break;
                                                                            case 634:
                                                                                CheckTreeWithSettings(i, j, new CheckTreeSettings
{
                                                                                    IsGroundValid = AshTreeGroundTest
                                                                                });
                                                                                break;
                                                                            case 323:
                                                                                CheckPalmTree(i, j);
                                                                                break;
                                                                            case 567:
                                                                                CheckGnome(i, j);
                                                                                break;
                                                                            case 630:
                                                                            case 631:
                                                                                CheckStinkbugBlocker(i, j);
                                                                                break;
                                                                            }
                                                                            TileLoader.CheckModTile(i, j, num);
                                                                            return;
                                                                        case 172:
                                                                        case 360:
                                                                        case 505:
                                                                        case 521:
                                                                        case 522:
                                                                        case 523:
                                                                        case 524:
                                                                        case 525:
                                                                        case 526:
                                                                        case 527:
                                                                        case 543:
                                                                        case 568:
                                                                        case 569:
                                                                        case 570:
                                                                        case 580:
                                                                        case 598:
                                                                        case 620:
                                                                        case 652:
                                                                        case 654:
                                                                            break;
                                                                        }
                                                                        break;
                                                                    case 132:
                                                                    case 138:
                                                                    case 142:
                                                                    case 143:
                                                                    case 288:
                                                                    case 289:
                                                                    case 290:
                                                                    case 291:
                                                                    case 292:
                                                                    case 293:
                                                                    case 294:
                                                                    case 295:
                                                                    case 484:
                                                                    case 664:
                                                                    case 665:
                                                                        break;
                                                                    }
                                                                    Check2x2(i, j, num);
                                                                    return;
                                                                case 254:
                                                                    break;
                                                                }
                                                                Check2x2Style(i, j, num);
                                                                return;
                                                            case 405:
                                                            case 486:
                                                            case 488:
                                                            case 532:
                                                            case 533:
                                                            case 544:
                                                            case 552:
                                                            case 555:
                                                            case 556:
                                                            case 582:
                                                            case 619:
                                                            case 629:
                                                            case 647:
                                                            case 648:
                                                            case 651:
                                                                break;
                                                            }
                                                        }
                                                        goto case 14;
                                                    case 14:
                                                    case 17:
                                                    case 26:
                                                    case 77:
                                                    case 86:
                                                    case 87:
                                                    case 88:
                                                    case 89:
                                                    case 114:
                                                    case 133:
                                                    case 186:
                                                    case 187:
                                                    case 215:
                                                    case 217:
                                                    case 218:
                                                    case 237:
                                                    case 244:
                                                    case 285:
                                                    case 286:
                                                    case 298:
                                                    case 299:
                                                    case 310:
                                                    case 339:
                                                    case 361:
                                                    case 362:
                                                    case 363:
                                                    case 364:
                                                    case 377:
                                                    case 469:
                                                    case 538:
                                                        Check3x2(i, j, (ushort)num);
                                                        return;
                                                    }
                                                }
                                                Check1x2(i, j, (ushort)num);
                                                return;
                                            }
                                            case 106:
                                            case 212:
                                            case 219:
                                            case 220:
                                            case 228:
                                            case 231:
                                            case 243:
                                            case 247:
                                            case 283:
                                            case 300:
                                            case 301:
                                            case 302:
                                            case 303:
                                            case 304:
                                            case 305:
                                            case 306:
                                            case 307:
                                            case 308:
                                                break;
                                            }
                                            Check3x3(i, j, (ushort)num);
                                            break;
                                        }
                                        goto case 275;
                                    case 275:
                                    case 276:
                                    case 277:
                                    case 278:
                                    case 279:
                                    case 280:
                                    case 281:
                                        Check6x3(i, j, num);
                                        break;
                                    }
                                    break;
                                }
                                goto case 373;
                            case 373:
                            case 374:
                            case 375:
{
                                Tile tile8 = Main.tile[i, j - 1];
                                if (tile8 == null || !tile8.active() || tile8.bottomSlope() || !Main.tileSolid[tile8.type] || Main.tileSolidTop[tile8.type])
{
                                    KillTile(i, j);
                                }
                                break;
                            }
                            }
                        }
                        else
{
                            CheckTorch(i, j);
                        }
                        return;
                    }
                    if ((num >= 255 && num <= 268) || num == 385 || (uint)(num - 446) <= 2u)
                    {
                        Framing.SelfFrame8Way(i, j, tile, resetFrame);
                        return;
                    }
                    Tile tile10 = Main.tile[i, j - 1];
                    Tile tile19 = Main.tile[i, j + 1];
                    Tile tile26 = Main.tile[i - 1, j];
                    Tile tile33 = Main.tile[i + 1, j];
                    Tile tile36 = Main.tile[i - 1, j + 1];
                    Tile tile39 = Main.tile[i + 1, j + 1];
                    Tile tile42 = Main.tile[i - 1, j - 1];
                    Tile tile45 = Main.tile[i + 1, j - 1];
                    int upLeft = -1;
                    int up = -1;
                    int upRight = -1;
                    int left = -1;
                    int right = -1;
                    int downLeft = -1;
                    int down = -1;
                    int downRight = -1;
                    if (tile26 != null && tile26.active())
                    {
                        left = (Main.tileStone[tile26.type] ? 1 : tile26.type);
                        if (tile26.slope() == 1 || tile26.slope() == 3)
{
                            left = -1;
                        }
                    }
                    if (tile33 != null && tile33.active())
                    {
                        right = (Main.tileStone[tile33.type] ? 1 : tile33.type);
                        if (tile33.slope() == 2 || tile33.slope() == 4)
{
                            right = -1;
                        }
                    }
                    if (tile10 != null && tile10.active())
                    {
                        up = (Main.tileStone[tile10.type] ? 1 : tile10.type);
                        if (tile10.slope() == 3 || tile10.slope() == 4)
{
                            up = -1;
                        }
                    }
                    if (tile19 != null && tile19.active())
                    {
                        down = (Main.tileStone[tile19.type] ? 1 : tile19.type);
                        if (tile19.slope() == 1 || tile19.slope() == 2)
{
                            down = -1;
                        }
                    }
                    if (tile42 != null && tile42.active())
                    {
                        upLeft = (Main.tileStone[tile42.type] ? 1 : tile42.type);
                    }
                    if (tile45 != null && tile45.active())
                    {
                        upRight = (Main.tileStone[tile45.type] ? 1 : tile45.type);
                    }
                    if (tile36 != null && tile36.active())
                    {
                        downLeft = (Main.tileStone[tile36.type] ? 1 : tile36.type);
                    }
                    if (tile39 != null && tile39.active())
                    {
                        downRight = (Main.tileStone[tile39.type] ? 1 : tile39.type);
                    }
                    if (tile.slope() == 2)
                    {
                        up = -1;
                        left = -1;
                    }
                    if (tile.slope() == 1)
                    {
                        up = -1;
                        right = -1;
                    }
                    if (tile.slope() == 4)
                    {
                        down = -1;
                        left = -1;
                    }
                    if (tile.slope() == 3)
                    {
                        down = -1;
                        right = -1;
                    }
                    if (num == 668)
                    {
                        num = 0;
                    }
                    TileMergeAttempt(0, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    num43 = num;
                    if (TileID.Sets.Snow[num])
                    {
                        TileMergeAttempt(num, Main.tileBrick, TileID.Sets.Ices, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    }
                    else if (!TileID.Sets.Ices[num])
                    {
                        if (num43 == 162)
{
                            TileMergeAttempt(num, Main.tileBrick, TileID.Sets.IcesSnow, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        }
                        else if (Main.tileBrick[num])
{
                            int num44 = num;
                            if (!TileID.Sets.GrassSpecial[num])
{
                                if (num44 == 633)
{
                                    TileMergeAttempt(num, Main.tileBrick, TileID.Sets.Ash, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                }
                                else
{
                                    TileMergeAttempt(num, Main.tileBrick, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                }
                            }
                            else
{
                                TileMergeAttempt(num, Main.tileBrick, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                            }
                        }
                        else if (Main.tilePile[num])
{
                            TileMergeAttempt(num, Main.tilePile, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        }
                    }
                    else
                    {
                        TileMergeAttempt(num, Main.tileBrick, TileID.Sets.Snow, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    }
                    if ((TileID.Sets.Stone[num] || Main.tileMoss[num]) && down == 165)
                    {
                        if (tile19 != null && tile19.frameY == 72)
{
                            down = num;
                        }
                        else if (tile19 != null && tile19.frameY == 0)
{
                            down = num;
                        }
                    }
                    if ((TileID.Sets.Stone[num] || Main.tileMoss[num]) && up == 165)
                    {
                        if (tile10 != null && tile10.frameY == 90)
{
                            up = num;
                        }
                        else if (tile10 != null && tile10.frameY == 54)
{
                            up = num;
                        }
                    }
                    if (num == 225)
                    {
                        if (down == 165)
{
                            down = num;
                        }
                        if (up == 165)
{
                            up = num;
                        }
                    }
                    if ((TileID.Sets.Ices[num] || num == 147) && down == 165)
                    {
                        down = num;
                    }
                    if ((tile.slope() == 1 || tile.slope() == 2) && down > -1 && !TileID.Sets.Platforms[down])
                    {
                        down = num;
                    }
                    if (up > -1 && tile10 != null && (tile10.slope() == 1 || tile10.slope() == 2) && !TileID.Sets.Platforms[up])
                    {
                        up = num;
                    }
                    if ((tile.slope() == 3 || tile.slope() == 4) && up > -1 && !TileID.Sets.Platforms[up])
                    {
                        up = num;
                    }
                    if (down > -1 && tile19 != null && (tile19.slope() == 3 || tile19.slope() == 4) && !TileID.Sets.Platforms[down])
                    {
                        down = num;
                    }
                    if (num == 124)
                    {
                        if (up > -1 && Main.tileSolid[up] && !TileID.Sets.Platforms[up])
{
                            up = num;
                        }
                        if (down > -1 && Main.tileSolid[down] && !TileID.Sets.Platforms[down])
{
                            down = num;
                        }
                    }
                    if (up > -1 && tile10 != null && tile10.halfBrick() && !TileID.Sets.Platforms[up])
                    {
                        up = num;
                    }
                    if (left > -1 && tile26 != null && tile26.halfBrick())
                    {
                        if (tile.halfBrick())
{
                            left = num;
                        }
                        else if (tile26.type != num)
{
                            left = -1;
                        }
                    }
                    if (right > -1 && tile33 != null && tile33.halfBrick())
                    {
                        if (tile.halfBrick())
{
                            right = num;
                        }
                        else if (tile33.type != num)
{
                            right = -1;
                        }
                    }
                    if (tile.halfBrick())
                    {
                        if (left != num)
{
                            left = -1;
                        }
                        if (right != num)
{
                            right = -1;
                        }
                        up = -1;
                    }
                    if (tile19 != null && tile19.halfBrick())
                    {
                        down = -1;
                    }
                    if (!Main.tileSolid[num])
                    {
                        switch (num)
{
                        case 49:
                            CheckOnTable1x1(i, j, (byte)num);
                            return;
                        case 80:
                            CactusFrame(i, j);
                            return;
                        }
                    }
                    mergeUp = false;
                    mergeDown = false;
                    mergeLeft = false;
                    mergeRight = false;
                    int num20 = 0;
                    if (resetFrame)
                    {
                        num20 = genRand.Next(0, 3);
                        tile.frameNumber((byte)num20);
                    }
                    else
                    {
                        num20 = tile.frameNumber();
                    }
                    if (Main.tileLargeFrames[num] == 1)
                    {
                        int num21 = j % 4;
                        int num22 = i % 3;
                        num20 = (new int[4, 3]
{
                            { 2, 4, 2 },
                            { 1, 3, 1 },
                            { 2, 2, 4 },
                            { 1, 1, 3 }
                        })[num21, num22] - 1;
                    }
                    if (Main.tileLargeFrames[num] == 2)
                    {
                        int num45 = i % 2;
                        int num24 = j % 2;
                        num20 = num45 + num24 * 2;
                    }
                    if (!Main.tileRope[num] && TileID.Sets.BlockMergesWithMergeAllBlock[num])
                    {
                        TileMergeAttempt(num, Main.tileBlendAll, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    }
                    if (Main.tileBlendAll[num])
                    {
                        TileMergeAttempt(num, TileID.Sets.BlockMergesWithMergeAllBlock, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    }
                    if (TileID.Sets.ForcedDirtMerging[num])
                    {
                        TileMergeAttempt(num, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    }
                    if (TileID.Sets.Dirt[num])
                    {
                        if (up > -1 && Main.tileMergeDirt[up])
{
                            TileFrame(i, j - 1);
                            if (mergeDown)
{
                                up = num;
                            }
                        }
                        else if (up >= 0 && TileID.Sets.Snow[up])
{
                            TileFrame(i, j - 1);
                            if (mergeDown)
{
                                up = num;
                            }
                        }
                        if (down > -1 && Main.tileMergeDirt[down])
{
                            TileFrame(i, j + 1);
                            if (mergeUp)
{
                                down = num;
                            }
                        }
                        else if (down >= 0 && TileID.Sets.Snow[down])
{
                            TileFrame(i, j + 1);
                            if (mergeUp)
{
                                down = num;
                            }
                        }
                        if (left > -1 && Main.tileMergeDirt[left])
{
                            TileFrame(i - 1, j);
                            if (mergeRight)
{
                                left = num;
                            }
                        }
                        else if (left >= 0 && TileID.Sets.Snow[left])
{
                            TileFrame(i - 1, j);
                            if (mergeRight)
{
                                left = num;
                            }
                        }
                        if (right > -1 && Main.tileMergeDirt[right])
{
                            TileFrame(i + 1, j);
                            if (mergeLeft)
{
                                right = num;
                            }
                        }
                        else if (right == 147)
{
                            TileFrame(i + 1, j);
                            if (mergeLeft)
{
                                right = num;
                            }
                        }
                        bool[] mergesWithDirtInASpecialWay = TileID.Sets.Conversion.MergesWithDirtInASpecialWay;
                        if (up > -1 && mergesWithDirtInASpecialWay[up])
{
                            up = num;
                        }
                        if (down > -1 && mergesWithDirtInASpecialWay[down])
{
                            down = num;
                        }
                        if (left > -1 && mergesWithDirtInASpecialWay[left])
{
                            left = num;
                        }
                        if (right > -1 && mergesWithDirtInASpecialWay[right])
{
                            right = num;
                        }
                        if (upLeft > -1 && Main.tileMergeDirt[upLeft])
{
                            upLeft = num;
                        }
                        else if (upLeft > -1 && mergesWithDirtInASpecialWay[upLeft])
{
                            upLeft = num;
                        }
                        if (upRight > -1 && Main.tileMergeDirt[upRight])
{
                            upRight = num;
                        }
                        else if (upRight > -1 && mergesWithDirtInASpecialWay[upRight])
{
                            upRight = num;
                        }
                        if (downLeft > -1 && Main.tileMergeDirt[downLeft])
{
                            downLeft = num;
                        }
                        else if (downLeft > -1 && mergesWithDirtInASpecialWay[downLeft])
{
                            downLeft = num;
                        }
                        if (downRight > -1 && Main.tileMergeDirt[downRight])
{
                            downRight = num;
                        }
                        else if (downRight > -1 && mergesWithDirtInASpecialWay[downRight])
{
                            downRight = num;
                        }
                        TileMergeAttempt(0, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        TileMergeAttempt(-2, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        TileMergeAttempt(0, 191, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        if (up > -1 && TileID.Sets.ForcedDirtMerging[up])
{
                            up = num;
                        }
                        if (down > -1 && TileID.Sets.ForcedDirtMerging[down])
{
                            down = num;
                        }
                        if (left > -1 && TileID.Sets.ForcedDirtMerging[left])
{
                            left = num;
                        }
                        if (right > -1 && TileID.Sets.ForcedDirtMerging[right])
{
                            right = num;
                        }
                        if (upLeft > -1 && TileID.Sets.ForcedDirtMerging[upLeft])
{
                            upLeft = num;
                        }
                        if (upRight > -1 && TileID.Sets.ForcedDirtMerging[upRight])
{
                            upRight = num;
                        }
                        if (downLeft > -1 && TileID.Sets.ForcedDirtMerging[downLeft])
{
                            downLeft = num;
                        }
                        if (downRight > -1 && TileID.Sets.ForcedDirtMerging[downRight])
{
                            downRight = num;
                        }
                    }
                    else if (Main.tileRope[num])
                    {
                        if (num != 504 && up != num && IsRope(i, j - 1))
{
                            up = num;
                        }
                        if (down != num && IsRope(i, j + 1))
{
                            down = num;
                        }
                        if (num != 504 && up > -1 && Main.tileSolid[up] && !Main.tileSolidTop[up])
{
                            up = num;
                        }
                        if (down > -1 && Main.tileSolid[down])
{
                            down = num;
                        }
                        if (num != 504 && up != num)
{
                            if (left > -1 && Main.tileSolid[left])
{
                                left = num;
                            }
                            if (right > -1 && Main.tileSolid[right])
{
                                right = num;
                            }
                        }
                    }
                    else
                    {
                        switch (num)
{
                        case 53:
                            TileMergeAttemptFrametest(i, j, num, 397, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                            TileMergeAttemptFrametest(i, j, num, 396, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                            break;
                        case 234:
                            TileMergeAttemptFrametest(i, j, num, 399, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                            TileMergeAttemptFrametest(i, j, num, 401, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                            break;
                        case 112:
                            TileMergeAttemptFrametest(i, j, num, 398, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                            TileMergeAttemptFrametest(i, j, num, 400, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                            break;
                        case 116:
                            TileMergeAttemptFrametest(i, j, num, 402, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                            TileMergeAttemptFrametest(i, j, num, 403, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                            break;
                        }
                    }
                    if (Main.tileMergeDirt[num])
                    {
                        TileMergeAttempt(-2, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        if (num == 1)
{
                            if ((double)j > Main.rockLayer)
{
                                TileMergeAttemptFrametest(i, j, num, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                            }
                            TileMergeAttemptFrametest(i, j, num, TileID.Sets.Ash, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        }
                    }
                    else
                    {
                        num43 = num;
                        if (!TileID.Sets.HellSpecial[num])
{
                            if (num43 == 57)
{
                                TileMergeAttempt(-2, 1, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                TileMergeAttempt(num, 633, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                TileMergeAttemptFrametest(i, j, num, TileID.Sets.HellSpecial, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                            }
                            else if (!TileID.Sets.Mud[num])
{
                                switch (num43)
{
                                case 211:
                                    TileMergeAttempt(59, 60, ref up, ref down, ref left, ref right);
                                    TileMergeAttempt(-2, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                    break;
                                case 225:
                                case 226:
                                    TileMergeAttempt(-2, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                    break;
                                case 60:
                                    TileMergeAttempt(59, 211, ref up, ref down, ref left, ref right);
                                    break;
                                case 189:
                                    TileMergeAttemptFrametest(i, j, num, TileID.Sets.MergesWithClouds, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                    break;
                                case 196:
                                    TileMergeAttempt(-2, 189, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                    TileMergeAttempt(num, 460, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                    break;
                                case 460:
                                    TileMergeAttempt(-2, 189, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                    TileMergeAttempt(num, 196, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                    break;
                                default:
                                    if (TileID.Sets.Snow[num])
{
                                        TileMergeAttemptFrametest(i, j, num, TileID.Sets.IcesSlush, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                    }
                                    else if (!TileID.Sets.IcesSlush[num])
{
                                        switch (num43)
{
                                        case 162:
                                            TileMergeAttempt(-2, TileID.Sets.IcesSnow, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 32:
                                            if (down == 23)
{
                                                down = num;
                                            }
                                            break;
                                        case 352:
                                            if (down == 199)
{
                                                down = num;
                                            }
                                            break;
                                        case 69:
                                            if (down == 60)
{
                                                down = num;
                                            }
                                            break;
                                        case 655:
                                            if (down == 60)
{
                                                down = num;
                                            }
                                            break;
                                        case 51:
                                            TileMergeAttempt(num, TileID.Sets.AllTiles, Main.tileNoAttach, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 192:
                                            TileMergeAttemptFrametest(i, j, num, 191, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 191:
                                            TileMergeAttempt(-2, 192, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            TileMergeAttempt(num, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 384:
                                            TileMergeAttemptFrametest(i, j, num, 383, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 383:
                                            TileMergeAttempt(-2, 384, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            TileMergeAttempt(num, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 407:
                                            TileMergeAttempt(-2, 404, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 404:
                                            TileMergeAttempt(-2, 396, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            TileMergeAttemptFrametest(i, j, num, 407, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 397:
                                            TileMergeAttempt(-2, 53, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            TileMergeAttemptFrametest(i, j, num, 396, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 396:
                                            TileMergeAttempt(-2, 397, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            TileMergeAttempt(-2, 53, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            TileMergeAttemptFrametest(i, j, num, 404, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 398:
                                            TileMergeAttempt(-2, 112, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            TileMergeAttemptFrametest(i, j, num, 400, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 400:
                                            TileMergeAttempt(-2, 398, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            TileMergeAttempt(-2, 112, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 399:
                                            TileMergeAttempt(-2, 234, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            TileMergeAttemptFrametest(i, j, num, 401, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 401:
                                            TileMergeAttempt(-2, 399, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            TileMergeAttempt(-2, 234, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 402:
                                            TileMergeAttempt(-2, 116, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            TileMergeAttemptFrametest(i, j, num, 403, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        case 403:
                                            TileMergeAttempt(-2, 402, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            TileMergeAttempt(-2, 116, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                            break;
                                        }
                                    }
                                    else
{
                                        TileMergeAttempt(-2, 147, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                    }
                                    break;
                                }
                            }
                            else
{
                                if ((double)j > Main.rockLayer)
{
                                    TileMergeAttempt(-2, 1, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                }
                                TileMergeAttempt(num, TileID.Sets.GrassSpecial, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                TileMergeAttemptFrametest(i, j, num, TileID.Sets.JungleSpecial, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                if ((double)j < Main.rockLayer)
{
                                    TileMergeAttemptFrametest(i, j, num, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                }
                                else
{
                                    TileMergeAttempt(num, TileID.Sets.Dirt, ref up, ref down, ref left, ref right);
                                }
                            }
                        }
                        else
{
                            TileMergeAttempt(-2, TileID.Sets.Ash, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        }
                    }
                    if (num == 0)
                    {
                        TileMergeAttempt(num, Main.tileMoss, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        TileMergeAttempt(num, TileID.Sets.tileMossBrick, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    }
                    else if (Main.tileMoss[num] || TileID.Sets.tileMossBrick[num])
                    {
                        TileMergeAttempt(num, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    }
                    else if (Main.tileStone[num] || num == 1)
                    {
                        TileMergeAttempt(num, Main.tileMoss, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    }
                    else if (num == 38)
                    {
                        TileMergeAttempt(num, TileID.Sets.tileMossBrick, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    }
                    if (TileID.Sets.Conversion.Grass[num])
                    {
                        TileMergeAttempt(num, TileID.Sets.Ore, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    }
                    else if (TileID.Sets.Ore[num])
                    {
                        TileMergeAttempt(num, TileID.Sets.Conversion.Grass, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    }
                    if (num >= 0 && TileID.Sets.Mud[num])
                    {
                        TileMergeAttempt(num, TileID.Sets.OreMergesWithMud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    }
                    else if (TileID.Sets.OreMergesWithMud[num])
                    {
                        TileMergeAttempt(num, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    }
                    bool flag = false;
                    TileMergeCullCache tileMergeCullCache = default(TileMergeCullCache);
                    if (!Main.ShouldShowInvisibleWalls())
                    {
                        bool flag10 = tile.invisibleBlock();
                        tileMergeCullCache.CullTop |= tile10 != null && tile10.invisibleBlock() != flag10;
                        tileMergeCullCache.CullBottom |= tile19 != null && tile19.invisibleBlock() != flag10;
                        tileMergeCullCache.CullLeft |= tile26 != null && tile26.invisibleBlock() != flag10;
                        tileMergeCullCache.CullRight |= tile33 != null && tile33.invisibleBlock() != flag10;
                        tileMergeCullCache.CullTopLeft |= tile42 != null && tile42.invisibleBlock() != flag10;
                        tileMergeCullCache.CullTopRight |= tile45 != null && tile45.invisibleBlock() != flag10;
                        tileMergeCullCache.CullBottomLeft |= tile36 != null && tile36.invisibleBlock() != flag10;
                        tileMergeCullCache.CullBottomRight |= tile39 != null && tile39.invisibleBlock() != flag10;
                    }
                    if (TileID.Sets.Grass[num] || TileID.Sets.GrassSpecial[num] || Main.tileMoss[num] || TileID.Sets.NeedsGrassFraming[num] || TileID.Sets.tileMossBrick[num])
                    {
                        flag = true;
                        TileMergeAttemptWeird(num, -1, Main.tileSolid, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        int num25 = TileID.Sets.NeedsGrassFramingDirt[num];
                        if (TileID.Sets.GrassSpecial[num])
{
                            num25 = 59;
                        }
                        else if (Main.tileMoss[num])
{
                            num25 = 1;
                        }
                        else if (TileID.Sets.tileMossBrick[num])
{
                            num25 = 38;
                        }
                        else
{
                            switch (num)
{
                            case 2:
                            case 477:
                                TileMergeAttempt(num25, 23, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                break;
                            case 23:
                                TileMergeAttempt(num25, 2, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                                break;
                            }
                        }
                        tileMergeCullCache.Cull(ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        if (up != num && up != num25 && (down == num || down == num25))
{
                            if (left == num25 && right == num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 0;
                                    rectangle.Y = 198;
                                    break;
                                case 1:
                                    rectangle.X = 18;
                                    rectangle.Y = 198;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 198;
                                    break;
                                }
                            }
                            else if (left == num && right == num25)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 198;
                                    break;
                                case 1:
                                    rectangle.X = 72;
                                    rectangle.Y = 198;
                                    break;
                                default:
                                    rectangle.X = 90;
                                    rectangle.Y = 198;
                                    break;
                                }
                            }
                        }
                        else if (down != num && down != num25 && (up == num || up == num25))
{
                            if (left == num25 && right == num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 0;
                                    rectangle.Y = 216;
                                    break;
                                case 1:
                                    rectangle.X = 18;
                                    rectangle.Y = 216;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 216;
                                    break;
                                }
                            }
                            else if (left == num && right == num25)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 216;
                                    break;
                                case 1:
                                    rectangle.X = 72;
                                    rectangle.Y = 216;
                                    break;
                                default:
                                    rectangle.X = 90;
                                    rectangle.Y = 216;
                                    break;
                                }
                            }
                        }
                        else if (left != num && left != num25 && (right == num || right == num25))
{
                            if (up == num25 && down == num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 72;
                                    rectangle.Y = 144;
                                    break;
                                case 1:
                                    rectangle.X = 72;
                                    rectangle.Y = 162;
                                    break;
                                default:
                                    rectangle.X = 72;
                                    rectangle.Y = 180;
                                    break;
                                }
                            }
                            else if (down == num && up == num25)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 72;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 72;
                                    rectangle.Y = 108;
                                    break;
                                default:
                                    rectangle.X = 72;
                                    rectangle.Y = 126;
                                    break;
                                }
                            }
                        }
                        else if (right != num && right != num25 && (left == num || left == num25))
{
                            if (up == num25 && down == num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 90;
                                    rectangle.Y = 144;
                                    break;
                                case 1:
                                    rectangle.X = 90;
                                    rectangle.Y = 162;
                                    break;
                                default:
                                    rectangle.X = 90;
                                    rectangle.Y = 180;
                                    break;
                                }
                            }
                            else if (down == num && right == up)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 90;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 90;
                                    rectangle.Y = 108;
                                    break;
                                default:
                                    rectangle.X = 90;
                                    rectangle.Y = 126;
                                    break;
                                }
                            }
                        }
                        else if (up == num && down == num && left == num && right == num)
{
                            if (upLeft != num && upRight != num && downLeft != num && downRight != num)
{
                                if (downRight == num25)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 108;
                                        rectangle.Y = 324;
                                        break;
                                    case 1:
                                        rectangle.X = 126;
                                        rectangle.Y = 324;
                                        break;
                                    default:
                                        rectangle.X = 144;
                                        rectangle.Y = 324;
                                        break;
                                    }
                                }
                                else if (upRight == num25)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 108;
                                        rectangle.Y = 342;
                                        break;
                                    case 1:
                                        rectangle.X = 126;
                                        rectangle.Y = 342;
                                        break;
                                    default:
                                        rectangle.X = 144;
                                        rectangle.Y = 342;
                                        break;
                                    }
                                }
                                else if (downLeft == num25)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 108;
                                        rectangle.Y = 360;
                                        break;
                                    case 1:
                                        rectangle.X = 126;
                                        rectangle.Y = 360;
                                        break;
                                    default:
                                        rectangle.X = 144;
                                        rectangle.Y = 360;
                                        break;
                                    }
                                }
                                else if (upLeft == num25)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 108;
                                        rectangle.Y = 378;
                                        break;
                                    case 1:
                                        rectangle.X = 126;
                                        rectangle.Y = 378;
                                        break;
                                    default:
                                        rectangle.X = 144;
                                        rectangle.Y = 378;
                                        break;
                                    }
                                }
                                else
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 144;
                                        rectangle.Y = 234;
                                        break;
                                    case 1:
                                        rectangle.X = 198;
                                        rectangle.Y = 234;
                                        break;
                                    default:
                                        rectangle.X = 252;
                                        rectangle.Y = 234;
                                        break;
                                    }
                                }
                            }
                            else if (upLeft != num && downRight != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 36;
                                    rectangle.Y = 306;
                                    break;
                                case 1:
                                    rectangle.X = 54;
                                    rectangle.Y = 306;
                                    break;
                                default:
                                    rectangle.X = 72;
                                    rectangle.Y = 306;
                                    break;
                                }
                            }
                            else if (upRight != num && downLeft != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 90;
                                    rectangle.Y = 306;
                                    break;
                                case 1:
                                    rectangle.X = 108;
                                    rectangle.Y = 306;
                                    break;
                                default:
                                    rectangle.X = 126;
                                    rectangle.Y = 306;
                                    break;
                                }
                            }
                            else if (upLeft != num && upRight == num && downLeft == num && downRight == num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 108;
                                    break;
                                case 1:
                                    rectangle.X = 54;
                                    rectangle.Y = 144;
                                    break;
                                default:
                                    rectangle.X = 54;
                                    rectangle.Y = 180;
                                    break;
                                }
                            }
                            else if (upLeft == num && upRight != num && downLeft == num && downRight == num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 36;
                                    rectangle.Y = 108;
                                    break;
                                case 1:
                                    rectangle.X = 36;
                                    rectangle.Y = 144;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 180;
                                    break;
                                }
                            }
                            else if (upLeft == num && upRight == num && downLeft != num && downRight == num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 54;
                                    rectangle.Y = 126;
                                    break;
                                default:
                                    rectangle.X = 54;
                                    rectangle.Y = 162;
                                    break;
                                }
                            }
                            else if (upLeft == num && upRight == num && downLeft == num && downRight != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 36;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 36;
                                    rectangle.Y = 126;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 162;
                                    break;
                                }
                            }
                        }
                        else if (up == num && down == num25 && left == num && right == num && upLeft == -1 && upRight == -1)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 108;
                                rectangle.Y = 18;
                                break;
                            case 1:
                                rectangle.X = 126;
                                rectangle.Y = 18;
                                break;
                            default:
                                rectangle.X = 144;
                                rectangle.Y = 18;
                                break;
                            }
                        }
                        else if (up == num25 && down == num && left == num && right == num && downLeft == -1 && downRight == -1)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 108;
                                rectangle.Y = 36;
                                break;
                            case 1:
                                rectangle.X = 126;
                                rectangle.Y = 36;
                                break;
                            default:
                                rectangle.X = 144;
                                rectangle.Y = 36;
                                break;
                            }
                        }
                        else if (up == num && down == num && left == num25 && right == num && upRight == -1 && downRight == -1)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 198;
                                rectangle.Y = 0;
                                break;
                            case 1:
                                rectangle.X = 198;
                                rectangle.Y = 18;
                                break;
                            default:
                                rectangle.X = 198;
                                rectangle.Y = 36;
                                break;
                            }
                        }
                        else if (up == num && down == num && left == num && right == num25 && upLeft == -1 && downLeft == -1)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 180;
                                rectangle.Y = 0;
                                break;
                            case 1:
                                rectangle.X = 180;
                                rectangle.Y = 18;
                                break;
                            default:
                                rectangle.X = 180;
                                rectangle.Y = 36;
                                break;
                            }
                        }
                        else if (up == num && down == num25 && left == num && right == num)
{
                            if (upRight != -1)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 108;
                                    break;
                                case 1:
                                    rectangle.X = 54;
                                    rectangle.Y = 144;
                                    break;
                                default:
                                    rectangle.X = 54;
                                    rectangle.Y = 180;
                                    break;
                                }
                            }
                            else if (upLeft != -1)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 36;
                                    rectangle.Y = 108;
                                    break;
                                case 1:
                                    rectangle.X = 36;
                                    rectangle.Y = 144;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 180;
                                    break;
                                }
                            }
                        }
                        else if (up == num25 && down == num && left == num && right == num)
{
                            if (downRight != -1)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 54;
                                    rectangle.Y = 126;
                                    break;
                                default:
                                    rectangle.X = 54;
                                    rectangle.Y = 162;
                                    break;
                                }
                            }
                            else if (downLeft != -1)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 36;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 36;
                                    rectangle.Y = 126;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 162;
                                    break;
                                }
                            }
                        }
                        else if (up == num && down == num && left == num && right == num25)
{
                            if (upLeft != -1)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 54;
                                    rectangle.Y = 126;
                                    break;
                                default:
                                    rectangle.X = 54;
                                    rectangle.Y = 162;
                                    break;
                                }
                            }
                            else if (downLeft != -1)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 108;
                                    break;
                                case 1:
                                    rectangle.X = 54;
                                    rectangle.Y = 144;
                                    break;
                                default:
                                    rectangle.X = 54;
                                    rectangle.Y = 180;
                                    break;
                                }
                            }
                        }
                        else if (up == num && down == num && left == num25 && right == num)
{
                            if (upRight != -1)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 36;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 36;
                                    rectangle.Y = 126;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 162;
                                    break;
                                }
                            }
                            else if (downRight != -1)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 36;
                                    rectangle.Y = 108;
                                    break;
                                case 1:
                                    rectangle.X = 36;
                                    rectangle.Y = 144;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 180;
                                    break;
                                }
                            }
                        }
                        else if ((up == num25 && down == num && left == num && right == num) || (up == num && down == num25 && left == num && right == num) || (up == num && down == num && left == num25 && right == num) || (up == num && down == num && left == num && right == num25))
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 18;
                                rectangle.Y = 18;
                                break;
                            case 1:
                                rectangle.X = 36;
                                rectangle.Y = 18;
                                break;
                            default:
                                rectangle.X = 54;
                                rectangle.Y = 18;
                                break;
                            }
                        }
                        if ((up == num || up == num25) && (down == num || down == num25) && (left == num || left == num25) && (right == num || right == num25))
{
                            if (upLeft != num && upLeft != num25 && (upRight == num || upRight == num25) && (downLeft == num || downLeft == num25) && (downRight == num || downRight == num25))
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 108;
                                    break;
                                case 1:
                                    rectangle.X = 54;
                                    rectangle.Y = 144;
                                    break;
                                default:
                                    rectangle.X = 54;
                                    rectangle.Y = 180;
                                    break;
                                }
                            }
                            else if (upRight != num && upRight != num25 && (upLeft == num || upLeft == num25) && (downLeft == num || downLeft == num25) && (downRight == num || downRight == num25))
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 36;
                                    rectangle.Y = 108;
                                    break;
                                case 1:
                                    rectangle.X = 36;
                                    rectangle.Y = 144;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 180;
                                    break;
                                }
                            }
                            else if (downLeft != num && downLeft != num25 && (upLeft == num || upLeft == num25) && (upRight == num || upRight == num25) && (downRight == num || downRight == num25))
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 54;
                                    rectangle.Y = 126;
                                    break;
                                default:
                                    rectangle.X = 54;
                                    rectangle.Y = 162;
                                    break;
                                }
                            }
                            else if (downRight != num && downRight != num25 && (upLeft == num || upLeft == num25) && (downLeft == num || downLeft == num25) && (upRight == num || upRight == num25))
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 36;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 36;
                                    rectangle.Y = 126;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 162;
                                    break;
                                }
                            }
                        }
                        if (up != num25 && up != num && down == num && left != num25 && left != num && right == num && downRight != num25 && downRight != num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 90;
                                rectangle.Y = 270;
                                break;
                            case 1:
                                rectangle.X = 108;
                                rectangle.Y = 270;
                                break;
                            default:
                                rectangle.X = 126;
                                rectangle.Y = 270;
                                break;
                            }
                        }
                        else if (up != num25 && up != num && down == num && left == num && right != num25 && right != num && downLeft != num25 && downLeft != num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 144;
                                rectangle.Y = 270;
                                break;
                            case 1:
                                rectangle.X = 162;
                                rectangle.Y = 270;
                                break;
                            default:
                                rectangle.X = 180;
                                rectangle.Y = 270;
                                break;
                            }
                        }
                        else if (down != num25 && down != num && up == num && left != num25 && left != num && right == num && upRight != num25 && upRight != num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 90;
                                rectangle.Y = 288;
                                break;
                            case 1:
                                rectangle.X = 108;
                                rectangle.Y = 288;
                                break;
                            default:
                                rectangle.X = 126;
                                rectangle.Y = 288;
                                break;
                            }
                        }
                        else if (down != num25 && down != num && up == num && left == num && right != num25 && right != num && upLeft != num25 && upLeft != num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 144;
                                rectangle.Y = 288;
                                break;
                            case 1:
                                rectangle.X = 162;
                                rectangle.Y = 288;
                                break;
                            default:
                                rectangle.X = 180;
                                rectangle.Y = 288;
                                break;
                            }
                        }
                        else if (up != num && up != num25 && down == num && left == num && right == num && downLeft != num && downLeft != num25 && downRight != num && downRight != num25)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 144;
                                rectangle.Y = 216;
                                break;
                            case 1:
                                rectangle.X = 198;
                                rectangle.Y = 216;
                                break;
                            default:
                                rectangle.X = 252;
                                rectangle.Y = 216;
                                break;
                            }
                        }
                        else if (down != num && down != num25 && up == num && left == num && right == num && upLeft != num && upLeft != num25 && upRight != num && upRight != num25)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 144;
                                rectangle.Y = 252;
                                break;
                            case 1:
                                rectangle.X = 198;
                                rectangle.Y = 252;
                                break;
                            default:
                                rectangle.X = 252;
                                rectangle.Y = 252;
                                break;
                            }
                        }
                        else if (left != num && left != num25 && down == num && up == num && right == num && upRight != num && upRight != num25 && downRight != num && downRight != num25)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 126;
                                rectangle.Y = 234;
                                break;
                            case 1:
                                rectangle.X = 180;
                                rectangle.Y = 234;
                                break;
                            default:
                                rectangle.X = 234;
                                rectangle.Y = 234;
                                break;
                            }
                        }
                        else if (right != num && right != num25 && down == num && up == num && left == num && upLeft != num && upLeft != num25 && downLeft != num && downLeft != num25)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 162;
                                rectangle.Y = 234;
                                break;
                            case 1:
                                rectangle.X = 216;
                                rectangle.Y = 234;
                                break;
                            default:
                                rectangle.X = 270;
                                rectangle.Y = 234;
                                break;
                            }
                        }
                        else if (up != num25 && up != num && (down == num25 || down == num) && left == num25 && right == num25)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 36;
                                rectangle.Y = 270;
                                break;
                            case 1:
                                rectangle.X = 54;
                                rectangle.Y = 270;
                                break;
                            default:
                                rectangle.X = 72;
                                rectangle.Y = 270;
                                break;
                            }
                        }
                        else if (down != num25 && down != num && (up == num25 || up == num) && left == num25 && right == num25)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 36;
                                rectangle.Y = 288;
                                break;
                            case 1:
                                rectangle.X = 54;
                                rectangle.Y = 288;
                                break;
                            default:
                                rectangle.X = 72;
                                rectangle.Y = 288;
                                break;
                            }
                        }
                        else if (left != num25 && left != num && (right == num25 || right == num) && up == num25 && down == num25)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 0;
                                rectangle.Y = 270;
                                break;
                            case 1:
                                rectangle.X = 0;
                                rectangle.Y = 288;
                                break;
                            default:
                                rectangle.X = 0;
                                rectangle.Y = 306;
                                break;
                            }
                        }
                        else if (right != num25 && right != num && (left == num25 || left == num) && up == num25 && down == num25)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 18;
                                rectangle.Y = 270;
                                break;
                            case 1:
                                rectangle.X = 18;
                                rectangle.Y = 288;
                                break;
                            default:
                                rectangle.X = 18;
                                rectangle.Y = 306;
                                break;
                            }
                        }
                        else if (up == num && down == num25 && left == num25 && right == num25)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 198;
                                rectangle.Y = 288;
                                break;
                            case 1:
                                rectangle.X = 216;
                                rectangle.Y = 288;
                                break;
                            default:
                                rectangle.X = 234;
                                rectangle.Y = 288;
                                break;
                            }
                        }
                        else if (up == num25 && down == num && left == num25 && right == num25)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 198;
                                rectangle.Y = 270;
                                break;
                            case 1:
                                rectangle.X = 216;
                                rectangle.Y = 270;
                                break;
                            default:
                                rectangle.X = 234;
                                rectangle.Y = 270;
                                break;
                            }
                        }
                        else if (up == num25 && down == num25 && left == num && right == num25)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 198;
                                rectangle.Y = 306;
                                break;
                            case 1:
                                rectangle.X = 216;
                                rectangle.Y = 306;
                                break;
                            default:
                                rectangle.X = 234;
                                rectangle.Y = 306;
                                break;
                            }
                        }
                        else if (up == num25 && down == num25 && left == num25 && right == num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 144;
                                rectangle.Y = 306;
                                break;
                            case 1:
                                rectangle.X = 162;
                                rectangle.Y = 306;
                                break;
                            default:
                                rectangle.X = 180;
                                rectangle.Y = 306;
                                break;
                            }
                        }
                        if (up != num && up != num25 && down == num && left == num && right == num)
{
                            if ((downLeft == num25 || downLeft == num) && downRight != num25 && downRight != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 0;
                                    rectangle.Y = 324;
                                    break;
                                case 1:
                                    rectangle.X = 18;
                                    rectangle.Y = 324;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 324;
                                    break;
                                }
                            }
                            else if ((downRight == num25 || downRight == num) && downLeft != num25 && downLeft != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 324;
                                    break;
                                case 1:
                                    rectangle.X = 72;
                                    rectangle.Y = 324;
                                    break;
                                default:
                                    rectangle.X = 90;
                                    rectangle.Y = 324;
                                    break;
                                }
                            }
                        }
                        else if (down != num && down != num25 && up == num && left == num && right == num)
{
                            if ((upLeft == num25 || upLeft == num) && upRight != num25 && upRight != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 0;
                                    rectangle.Y = 342;
                                    break;
                                case 1:
                                    rectangle.X = 18;
                                    rectangle.Y = 342;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 342;
                                    break;
                                }
                            }
                            else if ((upRight == num25 || upRight == num) && upLeft != num25 && upLeft != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 342;
                                    break;
                                case 1:
                                    rectangle.X = 72;
                                    rectangle.Y = 342;
                                    break;
                                default:
                                    rectangle.X = 90;
                                    rectangle.Y = 342;
                                    break;
                                }
                            }
                        }
                        else if (left != num && left != num25 && up == num && down == num && right == num)
{
                            if ((upRight == num25 || upRight == num) && downRight != num25 && downRight != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 360;
                                    break;
                                case 1:
                                    rectangle.X = 72;
                                    rectangle.Y = 360;
                                    break;
                                default:
                                    rectangle.X = 90;
                                    rectangle.Y = 360;
                                    break;
                                }
                            }
                            else if ((downRight == num25 || downRight == num) && upRight != num25 && upRight != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 0;
                                    rectangle.Y = 360;
                                    break;
                                case 1:
                                    rectangle.X = 18;
                                    rectangle.Y = 360;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 360;
                                    break;
                                }
                            }
                        }
                        else if (right != num && right != num25 && up == num && down == num && left == num)
{
                            if ((upLeft == num25 || upLeft == num) && downLeft != num25 && downLeft != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 0;
                                    rectangle.Y = 378;
                                    break;
                                case 1:
                                    rectangle.X = 18;
                                    rectangle.Y = 378;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 378;
                                    break;
                                }
                            }
                            else if ((downLeft == num25 || downLeft == num) && upLeft != num25 && upLeft != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 378;
                                    break;
                                case 1:
                                    rectangle.X = 72;
                                    rectangle.Y = 378;
                                    break;
                                default:
                                    rectangle.X = 90;
                                    rectangle.Y = 378;
                                    break;
                                }
                            }
                        }
                        if ((up == num || up == num25) && (down == num || down == num25) && (left == num || left == num25) && (right == num || right == num25) && upLeft != -1 && upRight != -1 && downLeft != -1 && downRight != -1)
{
                            if ((i + j) % 2 == 1)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 108;
                                    rectangle.Y = 198;
                                    break;
                                case 1:
                                    rectangle.X = 126;
                                    rectangle.Y = 198;
                                    break;
                                default:
                                    rectangle.X = 144;
                                    rectangle.Y = 198;
                                    break;
                                }
                            }
                            else
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 18;
                                    rectangle.Y = 18;
                                    break;
                                case 1:
                                    rectangle.X = 36;
                                    rectangle.Y = 18;
                                    break;
                                default:
                                    rectangle.X = 54;
                                    rectangle.Y = 18;
                                    break;
                                }
                            }
                        }
                        if (num25 >= 0 && TileID.Sets.Dirt[num25])
{
                            TileMergeAttempt(-2, TileID.Sets.Dirt, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        }
                        else if (num25 >= 0 && TileID.Sets.Mud[num25])
{
                            TileMergeAttempt(-2, TileID.Sets.Mud, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        }
                        else
{
                            TileMergeAttempt(-2, num25, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        }
                        tileMergeCullCache.Cull(ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    }
                    TileMergeAttempt(num, Main.tileMerge[num], ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                    if (rectangle.X == -1 && rectangle.Y == -1 && (Main.tileMergeDirt[num] || (num > -1 && TileID.Sets.ChecksForMerge[num])))
                    {
                        if (!flag)
{
                            flag = true;
                            TileMergeAttemptWeird(num, -1, Main.tileSolid, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        }
                        if (up > -1 && up != num)
{
                            up = -1;
                        }
                        if (down > -1 && down != num)
{
                            down = -1;
                        }
                        if (left > -1 && left != num)
{
                            left = -1;
                        }
                        if (right > -1 && right != num)
{
                            right = -1;
                        }
                        tileMergeCullCache.Cull(ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        if (up != -1 && down != -1 && left != -1 && right != -1)
{
                            if (up == -2 && down == num && left == num && right == num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 144;
                                    rectangle.Y = 108;
                                    break;
                                case 1:
                                    rectangle.X = 162;
                                    rectangle.Y = 108;
                                    break;
                                default:
                                    rectangle.X = 180;
                                    rectangle.Y = 108;
                                    break;
                                }
                                mergeUp = true;
                            }
                            else if (up == num && down == -2 && left == num && right == num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 144;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 162;
                                    rectangle.Y = 90;
                                    break;
                                default:
                                    rectangle.X = 180;
                                    rectangle.Y = 90;
                                    break;
                                }
                                mergeDown = true;
                            }
                            else if (up == num && down == num && left == -2 && right == num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 162;
                                    rectangle.Y = 126;
                                    break;
                                case 1:
                                    rectangle.X = 162;
                                    rectangle.Y = 144;
                                    break;
                                default:
                                    rectangle.X = 162;
                                    rectangle.Y = 162;
                                    break;
                                }
                                mergeLeft = true;
                            }
                            else if (up == num && down == num && left == num && right == -2)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 144;
                                    rectangle.Y = 126;
                                    break;
                                case 1:
                                    rectangle.X = 144;
                                    rectangle.Y = 144;
                                    break;
                                default:
                                    rectangle.X = 144;
                                    rectangle.Y = 162;
                                    break;
                                }
                                mergeRight = true;
                            }
                            else if (up == -2 && down == num && left == -2 && right == num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 36;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 36;
                                    rectangle.Y = 126;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 162;
                                    break;
                                }
                                mergeUp = true;
                                mergeLeft = true;
                            }
                            else if (up == -2 && down == num && left == num && right == -2)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 54;
                                    rectangle.Y = 126;
                                    break;
                                default:
                                    rectangle.X = 54;
                                    rectangle.Y = 162;
                                    break;
                                }
                                mergeUp = true;
                                mergeRight = true;
                            }
                            else if (up == num && down == -2 && left == -2 && right == num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 36;
                                    rectangle.Y = 108;
                                    break;
                                case 1:
                                    rectangle.X = 36;
                                    rectangle.Y = 144;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 180;
                                    break;
                                }
                                mergeDown = true;
                                mergeLeft = true;
                            }
                            else if (up == num && down == -2 && left == num && right == -2)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 108;
                                    break;
                                case 1:
                                    rectangle.X = 54;
                                    rectangle.Y = 144;
                                    break;
                                default:
                                    rectangle.X = 54;
                                    rectangle.Y = 180;
                                    break;
                                }
                                mergeDown = true;
                                mergeRight = true;
                            }
                            else if (up == num && down == num && left == -2 && right == -2)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 180;
                                    rectangle.Y = 126;
                                    break;
                                case 1:
                                    rectangle.X = 180;
                                    rectangle.Y = 144;
                                    break;
                                default:
                                    rectangle.X = 180;
                                    rectangle.Y = 162;
                                    break;
                                }
                                mergeLeft = true;
                                mergeRight = true;
                            }
                            else if (up == -2 && down == -2 && left == num && right == num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 144;
                                    rectangle.Y = 180;
                                    break;
                                case 1:
                                    rectangle.X = 162;
                                    rectangle.Y = 180;
                                    break;
                                default:
                                    rectangle.X = 180;
                                    rectangle.Y = 180;
                                    break;
                                }
                                mergeUp = true;
                                mergeDown = true;
                            }
                            else if (up == -2 && down == num && left == -2 && right == -2)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 198;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 198;
                                    rectangle.Y = 108;
                                    break;
                                default:
                                    rectangle.X = 198;
                                    rectangle.Y = 126;
                                    break;
                                }
                                mergeUp = true;
                                mergeLeft = true;
                                mergeRight = true;
                            }
                            else if (up == num && down == -2 && left == -2 && right == -2)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 198;
                                    rectangle.Y = 144;
                                    break;
                                case 1:
                                    rectangle.X = 198;
                                    rectangle.Y = 162;
                                    break;
                                default:
                                    rectangle.X = 198;
                                    rectangle.Y = 180;
                                    break;
                                }
                                mergeDown = true;
                                mergeLeft = true;
                                mergeRight = true;
                            }
                            else if (up == -2 && down == -2 && left == num && right == -2)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 216;
                                    rectangle.Y = 144;
                                    break;
                                case 1:
                                    rectangle.X = 216;
                                    rectangle.Y = 162;
                                    break;
                                default:
                                    rectangle.X = 216;
                                    rectangle.Y = 180;
                                    break;
                                }
                                mergeUp = true;
                                mergeDown = true;
                                mergeRight = true;
                            }
                            else if (up == -2 && down == -2 && left == -2 && right == num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 216;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 216;
                                    rectangle.Y = 108;
                                    break;
                                default:
                                    rectangle.X = 216;
                                    rectangle.Y = 126;
                                    break;
                                }
                                mergeUp = true;
                                mergeDown = true;
                                mergeLeft = true;
                            }
                            else if (up == -2 && down == -2 && left == -2 && right == -2)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 108;
                                    rectangle.Y = 198;
                                    break;
                                case 1:
                                    rectangle.X = 126;
                                    rectangle.Y = 198;
                                    break;
                                default:
                                    rectangle.X = 144;
                                    rectangle.Y = 198;
                                    break;
                                }
                                mergeUp = true;
                                mergeDown = true;
                                mergeLeft = true;
                                mergeRight = true;
                            }
                            else if (up == num && down == num && left == num && right == num)
{
                                if (upLeft == -2)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 18;
                                        rectangle.Y = 108;
                                        break;
                                    case 1:
                                        rectangle.X = 18;
                                        rectangle.Y = 144;
                                        break;
                                    default:
                                        rectangle.X = 18;
                                        rectangle.Y = 180;
                                        break;
                                    }
                                }
                                if (upRight == -2)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 0;
                                        rectangle.Y = 108;
                                        break;
                                    case 1:
                                        rectangle.X = 0;
                                        rectangle.Y = 144;
                                        break;
                                    default:
                                        rectangle.X = 0;
                                        rectangle.Y = 180;
                                        break;
                                    }
                                }
                                if (downLeft == -2)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 18;
                                        rectangle.Y = 90;
                                        break;
                                    case 1:
                                        rectangle.X = 18;
                                        rectangle.Y = 126;
                                        break;
                                    default:
                                        rectangle.X = 18;
                                        rectangle.Y = 162;
                                        break;
                                    }
                                }
                                if (downRight == -2)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 0;
                                        rectangle.Y = 90;
                                        break;
                                    case 1:
                                        rectangle.X = 0;
                                        rectangle.Y = 126;
                                        break;
                                    default:
                                        rectangle.X = 0;
                                        rectangle.Y = 162;
                                        break;
                                    }
                                }
                            }
                        }
                        else
{
                            if (!TileID.Sets.Grass[num] && !TileID.Sets.GrassSpecial[num])
{
                                if (up == -1 && down == -2 && left == num && right == num)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 234;
                                        rectangle.Y = 0;
                                        break;
                                    case 1:
                                        rectangle.X = 252;
                                        rectangle.Y = 0;
                                        break;
                                    default:
                                        rectangle.X = 270;
                                        rectangle.Y = 0;
                                        break;
                                    }
                                    mergeDown = true;
                                }
                                else if (up == -2 && down == -1 && left == num && right == num)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 234;
                                        rectangle.Y = 18;
                                        break;
                                    case 1:
                                        rectangle.X = 252;
                                        rectangle.Y = 18;
                                        break;
                                    default:
                                        rectangle.X = 270;
                                        rectangle.Y = 18;
                                        break;
                                    }
                                    mergeUp = true;
                                }
                                else if (up == num && down == num && left == -1 && right == -2)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 234;
                                        rectangle.Y = 36;
                                        break;
                                    case 1:
                                        rectangle.X = 252;
                                        rectangle.Y = 36;
                                        break;
                                    default:
                                        rectangle.X = 270;
                                        rectangle.Y = 36;
                                        break;
                                    }
                                    mergeRight = true;
                                }
                                else if (up == num && down == num && left == -2 && right == -1)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 234;
                                        rectangle.Y = 54;
                                        break;
                                    case 1:
                                        rectangle.X = 252;
                                        rectangle.Y = 54;
                                        break;
                                    default:
                                        rectangle.X = 270;
                                        rectangle.Y = 54;
                                        break;
                                    }
                                    mergeLeft = true;
                                }
                            }
                            if (up != -1 && down != -1 && left == -1 && right == num)
{
                                if (up == -2 && down == num)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 72;
                                        rectangle.Y = 144;
                                        break;
                                    case 1:
                                        rectangle.X = 72;
                                        rectangle.Y = 162;
                                        break;
                                    default:
                                        rectangle.X = 72;
                                        rectangle.Y = 180;
                                        break;
                                    }
                                    mergeUp = true;
                                }
                                else if (down == -2 && up == num)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 72;
                                        rectangle.Y = 90;
                                        break;
                                    case 1:
                                        rectangle.X = 72;
                                        rectangle.Y = 108;
                                        break;
                                    default:
                                        rectangle.X = 72;
                                        rectangle.Y = 126;
                                        break;
                                    }
                                    mergeDown = true;
                                }
                            }
                            else if (up != -1 && down != -1 && left == num && right == -1)
{
                                if (up == -2 && down == num)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 90;
                                        rectangle.Y = 144;
                                        break;
                                    case 1:
                                        rectangle.X = 90;
                                        rectangle.Y = 162;
                                        break;
                                    default:
                                        rectangle.X = 90;
                                        rectangle.Y = 180;
                                        break;
                                    }
                                    mergeUp = true;
                                }
                                else if (down == -2 && up == num)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 90;
                                        rectangle.Y = 90;
                                        break;
                                    case 1:
                                        rectangle.X = 90;
                                        rectangle.Y = 108;
                                        break;
                                    default:
                                        rectangle.X = 90;
                                        rectangle.Y = 126;
                                        break;
                                    }
                                    mergeDown = true;
                                }
                            }
                            else if (up == -1 && down == num && left != -1 && right != -1)
{
                                if (left == -2 && right == num)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 0;
                                        rectangle.Y = 198;
                                        break;
                                    case 1:
                                        rectangle.X = 18;
                                        rectangle.Y = 198;
                                        break;
                                    default:
                                        rectangle.X = 36;
                                        rectangle.Y = 198;
                                        break;
                                    }
                                    mergeLeft = true;
                                }
                                else if (right == -2 && left == num)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 54;
                                        rectangle.Y = 198;
                                        break;
                                    case 1:
                                        rectangle.X = 72;
                                        rectangle.Y = 198;
                                        break;
                                    default:
                                        rectangle.X = 90;
                                        rectangle.Y = 198;
                                        break;
                                    }
                                    mergeRight = true;
                                }
                            }
                            else if (up == num && down == -1 && left != -1 && right != -1)
{
                                if (left == -2 && right == num)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 0;
                                        rectangle.Y = 216;
                                        break;
                                    case 1:
                                        rectangle.X = 18;
                                        rectangle.Y = 216;
                                        break;
                                    default:
                                        rectangle.X = 36;
                                        rectangle.Y = 216;
                                        break;
                                    }
                                    mergeLeft = true;
                                }
                                else if (right == -2 && left == num)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 54;
                                        rectangle.Y = 216;
                                        break;
                                    case 1:
                                        rectangle.X = 72;
                                        rectangle.Y = 216;
                                        break;
                                    default:
                                        rectangle.X = 90;
                                        rectangle.Y = 216;
                                        break;
                                    }
                                    mergeRight = true;
                                }
                            }
                            else if (up != -1 && down != -1 && left == -1 && right == -1)
{
                                if (up == -2 && down == -2)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 108;
                                        rectangle.Y = 216;
                                        break;
                                    case 1:
                                        rectangle.X = 108;
                                        rectangle.Y = 234;
                                        break;
                                    default:
                                        rectangle.X = 108;
                                        rectangle.Y = 252;
                                        break;
                                    }
                                    mergeUp = true;
                                    mergeDown = true;
                                }
                                else if (up == -2)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 126;
                                        rectangle.Y = 144;
                                        break;
                                    case 1:
                                        rectangle.X = 126;
                                        rectangle.Y = 162;
                                        break;
                                    default:
                                        rectangle.X = 126;
                                        rectangle.Y = 180;
                                        break;
                                    }
                                    mergeUp = true;
                                }
                                else if (down == -2)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 126;
                                        rectangle.Y = 90;
                                        break;
                                    case 1:
                                        rectangle.X = 126;
                                        rectangle.Y = 108;
                                        break;
                                    default:
                                        rectangle.X = 126;
                                        rectangle.Y = 126;
                                        break;
                                    }
                                    mergeDown = true;
                                }
                            }
                            else if (up == -1 && down == -1 && left != -1 && right != -1)
{
                                if (left == -2 && right == -2)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 162;
                                        rectangle.Y = 198;
                                        break;
                                    case 1:
                                        rectangle.X = 180;
                                        rectangle.Y = 198;
                                        break;
                                    default:
                                        rectangle.X = 198;
                                        rectangle.Y = 198;
                                        break;
                                    }
                                    mergeLeft = true;
                                    mergeRight = true;
                                }
                                else if (left == -2)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 0;
                                        rectangle.Y = 252;
                                        break;
                                    case 1:
                                        rectangle.X = 18;
                                        rectangle.Y = 252;
                                        break;
                                    default:
                                        rectangle.X = 36;
                                        rectangle.Y = 252;
                                        break;
                                    }
                                    mergeLeft = true;
                                }
                                else if (right == -2)
{
                                    switch (num20)
{
                                    case 0:
                                        rectangle.X = 54;
                                        rectangle.Y = 252;
                                        break;
                                    case 1:
                                        rectangle.X = 72;
                                        rectangle.Y = 252;
                                        break;
                                    default:
                                        rectangle.X = 90;
                                        rectangle.Y = 252;
                                        break;
                                    }
                                    mergeRight = true;
                                }
                            }
                            else if (up == -2 && down == -1 && left == -1 && right == -1)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 108;
                                    rectangle.Y = 144;
                                    break;
                                case 1:
                                    rectangle.X = 108;
                                    rectangle.Y = 162;
                                    break;
                                default:
                                    rectangle.X = 108;
                                    rectangle.Y = 180;
                                    break;
                                }
                                mergeUp = true;
                            }
                            else if (up == -1 && down == -2 && left == -1 && right == -1)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 108;
                                    rectangle.Y = 90;
                                    break;
                                case 1:
                                    rectangle.X = 108;
                                    rectangle.Y = 108;
                                    break;
                                default:
                                    rectangle.X = 108;
                                    rectangle.Y = 126;
                                    break;
                                }
                                mergeDown = true;
                            }
                            else if (up == -1 && down == -1 && left == -2 && right == -1)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 0;
                                    rectangle.Y = 234;
                                    break;
                                case 1:
                                    rectangle.X = 18;
                                    rectangle.Y = 234;
                                    break;
                                default:
                                    rectangle.X = 36;
                                    rectangle.Y = 234;
                                    break;
                                }
                                mergeLeft = true;
                            }
                            else if (up == -1 && down == -1 && left == -1 && right == -2)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 54;
                                    rectangle.Y = 234;
                                    break;
                                case 1:
                                    rectangle.X = 72;
                                    rectangle.Y = 234;
                                    break;
                                default:
                                    rectangle.X = 90;
                                    rectangle.Y = 234;
                                    break;
                                }
                                mergeRight = true;
                            }
                        }
                    }
                    int num26 = tile.blockType();
                    if (TileID.Sets.HasSlopeFrames[num])
                    {
                        if (num26 == 0)
{
                            bool flag11 = num == up && tile10 != null && tile10.topSlope();
                            bool flag12 = num == left && tile26 != null && tile26.leftSlope();
                            bool flag13 = num == right && tile33 != null && tile33.rightSlope();
                            bool flag14 = num == down && tile19 != null && tile19.bottomSlope();
                            int num27 = 0;
                            int num28 = 0;
                            if (flag11.ToInt() + flag12.ToInt() + flag13.ToInt() + flag14.ToInt() > 2)
{
                                int num29 = (tile10 != null && tile10.slope() == 1).ToInt() + (tile33 != null && tile33.slope() == 1).ToInt() + (tile19 != null && tile19.slope() == 4).ToInt() + (tile26 != null && tile26.slope() == 4).ToInt();
                                int num30 = (tile10 != null && tile10.slope() == 2).ToInt() + (tile33 != null && tile33.slope() == 3).ToInt() + (tile19 != null && tile19.slope() == 3).ToInt() + (tile26 != null && tile26.slope() == 2).ToInt();
                                if (num29 == num30)
{
                                    num27 = 2;
                                    num28 = 4;
                                }
                                else if (num29 > num30)
{
                                    bool num46 = num == upLeft && tile42 != null && tile42.slope() == 0;
                                    bool flag15 = num == downRight && tile39 != null && tile39.slope() == 0;
                                    if (num46 && flag15)
{
                                        num28 = 4;
                                    }
                                    else if (flag15)
{
                                        num27 = 6;
                                    }
                                    else
{
                                        num27 = 7;
                                        num28 = 1;
                                    }
                                }
                                else
{
                                    bool num47 = num == upRight && tile45 != null && tile45.slope() == 0;
                                    bool flag16 = num == downLeft && tile36 != null && tile36.slope() == 0;
                                    if (num47 && flag16)
{
                                        num28 = 4;
                                        num27 = 1;
                                    }
                                    else if (flag16)
{
                                        num27 = 7;
                                    }
                                    else
{
                                        num27 = 6;
                                        num28 = 1;
                                    }
                                }
                                rectangle.X = (18 + num27) * 18;
                                rectangle.Y = num28 * 18;
                            }
                            else
{
                                if (flag11 && flag12 && num == down && num == right)
{
                                    num28 = 2;
                                }
                                else if (flag11 && flag13 && num == down && num == left)
{
                                    num27 = 1;
                                    num28 = 2;
                                }
                                else if (flag13 && flag14 && num == up && num == left)
{
                                    num27 = 1;
                                    num28 = 3;
                                }
                                else if (flag14 && flag12 && num == up && num == right)
{
                                    num28 = 3;
                                }
                                if (num27 != 0 || num28 != 0)
{
                                    rectangle.X = (18 + num27) * 18;
                                    rectangle.Y = num28 * 18;
                                }
                            }
                        }
                        if (num26 >= 2 && (rectangle.X < 0 || rectangle.Y < 0))
{
                            int num32 = -1;
                            int num33 = -1;
                            int num34 = -1;
                            int num35 = 0;
                            int num36 = 0;
                            switch (num26)
{
                            case 2:
                                num32 = left;
                                num33 = down;
                                num34 = downLeft;
                                num35++;
                                break;
                            case 3:
                                num32 = right;
                                num33 = down;
                                num34 = downRight;
                                break;
                            case 4:
                                num32 = left;
                                num33 = up;
                                num34 = upLeft;
                                num35++;
                                num36++;
                                break;
                            case 5:
                                num32 = right;
                                num33 = up;
                                num34 = upRight;
                                num36++;
                                break;
                            }
                            if (num != num32 || num != num33 || num != num34)
{
                                if (num == num32 && num == num33)
{
                                    num35 += 2;
                                }
                                else if (num == num32)
{
                                    num35 += 4;
                                }
                                else if (num == num33)
{
                                    num35 += 4;
                                    num36 += 2;
                                }
                                else
{
                                    num35 += 2;
                                    num36 += 2;
                                }
                            }
                            rectangle.X = (18 + num35) * 18;
                            rectangle.Y = num36 * 18;
                        }
                    }
                    if (rectangle.X < 0 || rectangle.Y < 0)
                    {
                        if (!flag)
{
                            flag = true;
                            TileMergeAttemptWeird(num, -1, Main.tileSolid, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                            tileMergeCullCache.Cull(ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        }
                        if (TileID.Sets.Grass[num] || TileID.Sets.GrassSpecial[num] || Main.tileMoss[num] || TileID.Sets.tileMossBrick[num])
{
                            TileMergeAttempt(num, -2, ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                            tileMergeCullCache.Cull(ref up, ref down, ref left, ref right, ref upLeft, ref upRight, ref downLeft, ref downRight);
                        }
                        if (up == num && down == num && left == num && right == num)
{
                            if (upLeft != num && upRight != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 108;
                                    rectangle.Y = 18;
                                    break;
                                case 1:
                                    rectangle.X = 126;
                                    rectangle.Y = 18;
                                    break;
                                default:
                                    rectangle.X = 144;
                                    rectangle.Y = 18;
                                    break;
                                }
                            }
                            else if (downLeft != num && downRight != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 108;
                                    rectangle.Y = 36;
                                    break;
                                case 1:
                                    rectangle.X = 126;
                                    rectangle.Y = 36;
                                    break;
                                default:
                                    rectangle.X = 144;
                                    rectangle.Y = 36;
                                    break;
                                }
                            }
                            else if (upLeft != num && downLeft != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 180;
                                    rectangle.Y = 0;
                                    break;
                                case 1:
                                    rectangle.X = 180;
                                    rectangle.Y = 18;
                                    break;
                                default:
                                    rectangle.X = 180;
                                    rectangle.Y = 36;
                                    break;
                                }
                            }
                            else if (upRight != num && downRight != num)
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 198;
                                    rectangle.Y = 0;
                                    break;
                                case 1:
                                    rectangle.X = 198;
                                    rectangle.Y = 18;
                                    break;
                                default:
                                    rectangle.X = 198;
                                    rectangle.Y = 36;
                                    break;
                                }
                            }
                            else
{
                                switch (num20)
{
                                case 0:
                                    rectangle.X = 18;
                                    rectangle.Y = 18;
                                    break;
                                case 1:
                                    rectangle.X = 36;
                                    rectangle.Y = 18;
                                    break;
                                default:
                                    rectangle.X = 54;
                                    rectangle.Y = 18;
                                    break;
                                }
                            }
                        }
                        else if (up != num && down == num && left == num && right == num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 18;
                                rectangle.Y = 0;
                                break;
                            case 1:
                                rectangle.X = 36;
                                rectangle.Y = 0;
                                break;
                            default:
                                rectangle.X = 54;
                                rectangle.Y = 0;
                                break;
                            }
                        }
                        else if (up == num && down != num && left == num && right == num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 18;
                                rectangle.Y = 36;
                                break;
                            case 1:
                                rectangle.X = 36;
                                rectangle.Y = 36;
                                break;
                            default:
                                rectangle.X = 54;
                                rectangle.Y = 36;
                                break;
                            }
                        }
                        else if (up == num && down == num && left != num && right == num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 0;
                                rectangle.Y = 0;
                                break;
                            case 1:
                                rectangle.X = 0;
                                rectangle.Y = 18;
                                break;
                            default:
                                rectangle.X = 0;
                                rectangle.Y = 36;
                                break;
                            }
                        }
                        else if (up == num && down == num && left == num && right != num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 72;
                                rectangle.Y = 0;
                                break;
                            case 1:
                                rectangle.X = 72;
                                rectangle.Y = 18;
                                break;
                            default:
                                rectangle.X = 72;
                                rectangle.Y = 36;
                                break;
                            }
                        }
                        else if (up != num && down == num && left != num && right == num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 0;
                                rectangle.Y = 54;
                                break;
                            case 1:
                                rectangle.X = 36;
                                rectangle.Y = 54;
                                break;
                            default:
                                rectangle.X = 72;
                                rectangle.Y = 54;
                                break;
                            }
                        }
                        else if (up != num && down == num && left == num && right != num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 18;
                                rectangle.Y = 54;
                                break;
                            case 1:
                                rectangle.X = 54;
                                rectangle.Y = 54;
                                break;
                            default:
                                rectangle.X = 90;
                                rectangle.Y = 54;
                                break;
                            }
                        }
                        else if (up == num && down != num && left != num && right == num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 0;
                                rectangle.Y = 72;
                                break;
                            case 1:
                                rectangle.X = 36;
                                rectangle.Y = 72;
                                break;
                            default:
                                rectangle.X = 72;
                                rectangle.Y = 72;
                                break;
                            }
                        }
                        else if (up == num && down != num && left == num && right != num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 18;
                                rectangle.Y = 72;
                                break;
                            case 1:
                                rectangle.X = 54;
                                rectangle.Y = 72;
                                break;
                            default:
                                rectangle.X = 90;
                                rectangle.Y = 72;
                                break;
                            }
                        }
                        else if (up == num && down == num && left != num && right != num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 90;
                                rectangle.Y = 0;
                                break;
                            case 1:
                                rectangle.X = 90;
                                rectangle.Y = 18;
                                break;
                            default:
                                rectangle.X = 90;
                                rectangle.Y = 36;
                                break;
                            }
                        }
                        else if (up != num && down != num && left == num && right == num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 108;
                                rectangle.Y = 72;
                                break;
                            case 1:
                                rectangle.X = 126;
                                rectangle.Y = 72;
                                break;
                            default:
                                rectangle.X = 144;
                                rectangle.Y = 72;
                                break;
                            }
                        }
                        else if (up != num && down == num && left != num && right != num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 108;
                                rectangle.Y = 0;
                                break;
                            case 1:
                                rectangle.X = 126;
                                rectangle.Y = 0;
                                break;
                            default:
                                rectangle.X = 144;
                                rectangle.Y = 0;
                                break;
                            }
                        }
                        else if (up == num && down != num && left != num && right != num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 108;
                                rectangle.Y = 54;
                                break;
                            case 1:
                                rectangle.X = 126;
                                rectangle.Y = 54;
                                break;
                            default:
                                rectangle.X = 144;
                                rectangle.Y = 54;
                                break;
                            }
                        }
                        else if (up != num && down != num && left != num && right == num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 162;
                                rectangle.Y = 0;
                                break;
                            case 1:
                                rectangle.X = 162;
                                rectangle.Y = 18;
                                break;
                            default:
                                rectangle.X = 162;
                                rectangle.Y = 36;
                                break;
                            }
                        }
                        else if (up != num && down != num && left == num && right != num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 216;
                                rectangle.Y = 0;
                                break;
                            case 1:
                                rectangle.X = 216;
                                rectangle.Y = 18;
                                break;
                            default:
                                rectangle.X = 216;
                                rectangle.Y = 36;
                                break;
                            }
                        }
                        else if (up != num && down != num && left != num && right != num)
{
                            switch (num20)
{
                            case 0:
                                rectangle.X = 162;
                                rectangle.Y = 54;
                                break;
                            case 1:
                                rectangle.X = 180;
                                rectangle.Y = 54;
                                break;
                            default:
                                rectangle.X = 198;
                                rectangle.Y = 54;
                                break;
                            }
                        }
                    }
                    if (rectangle.X <= -1 || rectangle.Y <= -1)
                    {
                        if (num20 <= 0)
{
                            rectangle.X = 18;
                            rectangle.Y = 18;
                        }
                        else if (num20 == 1)
{
                            rectangle.X = 36;
                            rectangle.Y = 18;
                        }
                        if (num20 >= 2)
{
                            rectangle.X = 54;
                            rectangle.Y = 18;
                        }
                    }
                    if (Main.tileLargeFrames[num] == 1 && num20 == 3)
                    {
                        rectangle.Y += 90;
                    }
                    if (Main.tileLargeFrames[num] == 2 && num20 == 3)
                    {
                        rectangle.Y += 90;
                    }
                    tile.frameX = (short)rectangle.X;
                    tile.frameY = (short)rectangle.Y;
                    if (TileID.Sets.IsVine[num])
                    {
                        up = ((tile10 == null) ? num : ((!tile10.nactive()) ? (-1) : ((!tile10.bottomSlope()) ? tile10.type : (-1))));
                        if (num != up)
{
                            bool num48 = up == 60 || up == 62;
                            bool num49 = up == 109 || up == 115;
                            bool flag17 = up == 23 || up == 636 || up == 661;
                            bool flag2 = up == 199 || up == 205 || up == 662;
                            bool flag3 = up == 2 || up == 52;
                            bool flag4 = up == 382;
                            bool num50 = up == 70 || up == 528;
                            bool num51 = up == 633 || up == 638;
                            ushort num37 = 0;
                            if (num51)
{
                                num37 = 638;
                            }
                            if (num50)
{
                                num37 = 528;
                            }
                            if (num49)
{
                                num37 = 115;
                            }
                            if (num48)
{
                                num37 = 62;
                            }
                            if (flag17)
{
                                num37 = 636;
                            }
                            if (flag2)
{
                                num37 = 205;
                            }
                            if (flag3 && num != 382)
{
                                num37 = 52;
                            }
                            if (flag4)
{
                                num37 = 382;
                            }
                            if (num37 != 0 && num37 != num)
{
                                tile.type = num37;
                                SquareTileFrame(i, j);
                                return;
                            }
                        }
                        if (up != num)
{
                            bool flag5 = false;
                            if (up == -1)
{
                                flag5 = true;
                            }
                            if (num == 52 && up != 2 && up != 192)
{
                                flag5 = true;
                            }
                            if (num == 382 && up != 2 && up != 192)
{
                                flag5 = true;
                            }
                            if (num == 62 && up != 60)
{
                                flag5 = true;
                            }
                            if (num == 115 && up != 109)
{
                                flag5 = true;
                            }
                            if (num == 528 && up != 70)
{
                                flag5 = true;
                            }
                            if (num == 636 && up != 23 && up != 661)
{
                                flag5 = true;
                            }
                            if (num == 205 && up != 199 && up != 662)
{
                                flag5 = true;
                            }
                            if (num == 638 && up != 633)
{
                                flag5 = true;
                            }
                            if (flag5)
{
                                KillTile(i, j);
                            }
                        }
                    }
                    bool flag6 = false;
                    if (!noTileActions && tile.active() && TileID.Sets.Falling[num])
                    {
                        SpawnFallingBlockProjectile(i, j, tile, tile10, tile19, num);
                    }
                    if ((rectangle.X != frameX && rectangle.Y != frameY && frameX >= 0 && frameY >= 0) || flag6)
                    {
                        tileReframeCount++;
                        if (tileReframeCount < 25)
{
                            bool num52 = mergeUp;
                            bool flag7 = mergeDown;
                            bool flag8 = mergeLeft;
                            bool flag9 = mergeRight;
                            TileFrame(i - 1, j);
                            TileFrame(i + 1, j);
                            TileFrame(i, j - 1);
                            TileFrame(i, j + 1);
                            mergeUp = num52;
                            mergeDown = flag7;
                            mergeLeft = flag8;
                            mergeRight = flag9;
                        }
                        tileReframeCount--;
                    }
                }
            }
        }
        catch
        {
        }
        if (i > 0 && j > 0)
        {
            UpdateMapTile(i, j, addToList);
        }
    }
References Terraria.Tile.active(), Terraria.Liquid.AddWater(), Terraria.ID.TileID.Sets.AllTiles, Terraria.ID.TileID.Sets.Ash, Terraria.ID.TileID.Sets.BasicChest, Terraria.ID.TileID.Sets.BasicChestFake, Terraria.ID.TileID.Sets.BlockMergesWithMergeAllBlock, Terraria.Tile.blockType(), Terraria.ModLoader.TileLoader.CheckModTile(), Terraria.ID.TileID.Sets.ChecksForMerge, Terraria.Tile.ClearBlockPaintAndCoating(), Terraria.ID.TileID.Count, Terraria.ID.TileID.Sets.Dirt, Terraria.ID.TileID.Sets.Falling, Terraria.ID.TileID.Sets.ForcedDirtMerging, Terraria.Tile.frameNumber(), Terraria.Minecart.FrameTrack(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.GameContent.Tile_Entities.TEDisplayDoll.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEHatRack.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Framing_CheckTile(), Terraria.ID.TileID.Sets.Conversion.Grass, Terraria.ID.TileID.Sets.Grass, Terraria.ID.TileID.Sets.GrassSpecial, Terraria.Tile.halfBrick(), Terraria.ID.TileID.Sets.HasSlopeFrames, Terraria.ID.TileID.Sets.HellSpecial, Terraria.ID.TileID.Sets.Ices, Terraria.ID.TileID.Sets.IcesSlush, Terraria.ID.TileID.Sets.IcesSnow, Terraria.Tile.invisibleBlock(), Terraria.ID.TileID.Sets.IsBeam, Terraria.ID.TileID.Sets.IsVine, Terraria.ID.TileID.Sets.JungleSpecial, Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.ID.TileID.Sets.MergesWithClouds, Terraria.ID.TileID.Sets.Conversion.MergesWithDirtInASpecialWay, Terraria.ID.TileID.Sets.Mud, Terraria.ID.TileID.Sets.NeedsGrassFraming, Terraria.ID.TileID.Sets.NeedsGrassFramingDirt, Terraria.Main.netMode, Terraria.ID.TileID.Sets.Ore, Terraria.ID.TileID.Sets.OreMergesWithMud, Terraria.ID.TileID.Sets.Platforms, Terraria.Main.rockLayer, Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.Framing.SelfFrame8Way(), Terraria.Main.ShouldShowInvisibleWalls(), Terraria.Tile.slope(), Terraria.ID.TileID.Sets.Snow, Terraria.ID.TileID.Sets.Stone, Terraria.Main.tile, Terraria.Main.tileAlch, Terraria.Main.tileBlendAll, Terraria.Main.tileBrick, Terraria.ModLoader.TileLoader.TileFrame(), Terraria.Main.tileFrameImportant, Terraria.Main.tileLargeFrames, Terraria.Main.tileMerge, Terraria.Main.tileMergeDirt, Terraria.Main.tileMoss, Terraria.ID.TileID.Sets.tileMossBrick, Terraria.Main.tileNoAttach, Terraria.Main.tilePile, Terraria.Main.tileRope, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Main.tileStone, Terraria.ID.TileID.Sets.Torch, Terraria.ID.TileID.Sets.TreeSapling, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceBoulderTrap(), Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceDartTrap(), Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceExplosive(), Terraria.ModLoader.TileLoader.CheckModTile(), Terraria.WorldBuilding.WorldUtils.ClearTile(), Terraria.WorldBuilding.TileFont.DrawChar(), Terraria.Wiring.HitSwitch(), Terraria.WorldBuilding.TileFont.HLineLabel(), Terraria.WorldBuilding.WorldUtils.TileFrame(), and Terraria.WorldBuilding.TileFont.VLineLabel().