TModLoader: Terraria.WorldGen.AddGenPasses
AddGenPasses()
static void Terraria.WorldGen.AddGenPasses () inline static package
    {
        AddGenerationPass("Reset", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_0090: Unknown result type (might be due to invalid IL or missing references)
            //IL_0095: Unknown result type (might be due to invalid IL or missing references)
            //IL_009a: Unknown result type (might be due to invalid IL or missing references)
            //IL_009f: Unknown result type (might be due to invalid IL or missing references)
            if (genRand.Next(2) == 0)
            {
                GenVars.crimsonLeft = false;
            }
            else
            {
                GenVars.crimsonLeft = true;
            }
            GenVars.numOceanCaveTreasure = 0;
            GenVars.skipDesertTileCheck = false;
            growGrassUnderground = false;
            gen = true;
            Liquid.ReInit();
            noTileActions = true;
            progress.Message = "";
            SetupStatueList();
            RandomizeWeather();
            Main.cloudAlpha = 0f;
            Main.maxRaining = 0f;
            Main.raining = false;
            heartCount = 0;
            GenVars.extraBastStatueCount = 0;
            GenVars.extraBastStatueCountMax = 2;
            Main.checkXMas();
            Main.checkHalloween();
            ResetGenerator();
            GenVars.UndergroundDesertLocation = Rectangle.Empty;
            GenVars.UndergroundDesertHiveLocation = Rectangle.Empty;
            GenVars.numLarva = 0;
            List<int> list3 = new List<int> { 274, 220, 112, 218, 3019 };
            if (remixWorldGen)
            {
                list3 = new List<int> { 274, 220, 683, 218, 3019 };
            }
            List<int> list4 = new List<int>();
            while (list3.Count > 0)
            {
                int index = genRand.Next(list3.Count);
                int item = list3[index];
                list4.Add(item);
                list3.RemoveAt(index);
            }
            GenVars.hellChestItem = list4.ToArray();
            int num1064 = 86400;
            Main.slimeRainTime = -genRand.Next(num1064 * 2, num1064 * 3);
            Main.cloudBGActive = -genRand.Next(8640, 86400);
            skipFramingDuringGen = false;
            SavedOreTiers.Copper = 7;
            SavedOreTiers.Iron = 6;
            SavedOreTiers.Silver = 9;
            SavedOreTiers.Gold = 8;
            GenVars.copperBar = 20;
            GenVars.ironBar = 22;
            GenVars.silverBar = 21;
            GenVars.goldBar = 19;
            if (genRand.Next(2) == 0)
            {
                GenVars.copper = 166;
                GenVars.copperBar = 703;
                SavedOreTiers.Copper = 166;
            }
            if ((!dontStarveWorldGen || drunkWorldGen) && genRand.Next(2) == 0)
            {
                GenVars.iron = 167;
                GenVars.ironBar = 704;
                SavedOreTiers.Iron = 167;
            }
            if (genRand.Next(2) == 0)
            {
                GenVars.silver = 168;
                GenVars.silverBar = 705;
                SavedOreTiers.Silver = 168;
            }
            if ((!dontStarveWorldGen || drunkWorldGen) && genRand.Next(2) == 0)
            {
                GenVars.gold = 169;
                GenVars.goldBar = 706;
                SavedOreTiers.Gold = 169;
            }
            crimson = genRand.Next(2) == 0;
            if (WorldGenParam_Evil == 0)
            {
                crimson = false;
            }
            if (WorldGenParam_Evil == 1)
            {
                crimson = true;
            }
            if (GenVars.jungleHut == 0)
            {
                GenVars.jungleHut = 119;
            }
            else if (GenVars.jungleHut == 1)
            {
                GenVars.jungleHut = 120;
            }
            else if (GenVars.jungleHut == 2)
            {
                GenVars.jungleHut = 158;
            }
            else if (GenVars.jungleHut == 3)
            {
                GenVars.jungleHut = 175;
            }
            else if (GenVars.jungleHut == 4)
            {
                GenVars.jungleHut = 45;
            }
            Main.worldID = genRand.Next(int.MaxValue);
            RandomizeTreeStyle();
            RandomizeCaveBackgrounds();
            RandomizeBackgrounds(genRand);
            RandomizeMoonState(genRand);
            TreeTops.CopyExistingWorldInfoForWorldGeneration();
            GenVars.dungeonSide = ((genRand.Next(2) != 0) ? 1 : (-1));
            if (remixWorldGen)
            {
                if (GenVars.dungeonSide == -1)
                {
                    double num1065 = 1.0 - (double)genRand.Next(20, 35) * 0.01;
                    GenVars.jungleOriginX = (int)((double)Main.maxTilesX * num1065);
                }
                else
                {
                    double num1066 = (double)genRand.Next(20, 35) * 0.01;
                    GenVars.jungleOriginX = (int)((double)Main.maxTilesX * num1066);
                }
            }
            else
            {
                int minValue3 = 15;
                int maxValue12 = 30;
                if (tenthAnniversaryWorldGen && !remixWorldGen)
                {
                    minValue3 = 25;
                    maxValue12 = 35;
                }
                if (GenVars.dungeonSide == -1)
                {
                    double num1067 = 1.0 - (double)genRand.Next(minValue3, maxValue12) * 0.01;
                    GenVars.jungleOriginX = (int)((double)Main.maxTilesX * num1067);
                }
                else
                {
                    double num1068 = (double)genRand.Next(minValue3, maxValue12) * 0.01;
                    GenVars.jungleOriginX = (int)((double)Main.maxTilesX * num1068);
                }
            }
            int num1069 = genRand.Next(Main.maxTilesX);
            if (drunkWorldGen)
            {
                GenVars.dungeonSide *= -1;
            }
            if (GenVars.dungeonSide == 1)
            {
                while ((double)num1069 < (double)Main.maxTilesX * 0.6 || (double)num1069 > (double)Main.maxTilesX * 0.75)
                {
                    num1069 = genRand.Next(Main.maxTilesX);
                }
            }
            else
            {
                while ((double)num1069 < (double)Main.maxTilesX * 0.25 || (double)num1069 > (double)Main.maxTilesX * 0.4)
                {
                    num1069 = genRand.Next(Main.maxTilesX);
                }
            }
            if (drunkWorldGen)
            {
                GenVars.dungeonSide *= -1;
            }
            int num1070 = genRand.Next(50, 90);
            double num1071 = (double)Main.maxTilesX / 4200.0;
            num1070 += (int)((double)genRand.Next(20, 40) * num1071);
            num1070 += (int)((double)genRand.Next(20, 40) * num1071);
            int num1072 = num1069 - num1070;
            num1070 = genRand.Next(50, 90);
            num1070 += (int)((double)genRand.Next(20, 40) * num1071);
            num1070 += (int)((double)genRand.Next(20, 40) * num1071);
            int num1073 = num1069 + num1070;
            if (num1072 < 0)
            {
                num1072 = 0;
            }
            if (num1073 > Main.maxTilesX)
            {
                num1073 = Main.maxTilesX;
            }
            GenVars.snowOriginLeft = num1072;
            GenVars.snowOriginRight = num1073;
            GenVars.leftBeachEnd = genRand.Next(GenVars.beachSandRandomCenter - GenVars.beachSandRandomWidthRange, GenVars.beachSandRandomCenter + GenVars.beachSandRandomWidthRange);
            if (tenthAnniversaryWorldGen && !remixWorldGen)
            {
                GenVars.leftBeachEnd = GenVars.beachSandRandomCenter + GenVars.beachSandRandomWidthRange;
            }
            if (GenVars.dungeonSide == 1)
            {
                GenVars.leftBeachEnd += GenVars.beachSandDungeonExtraWidth;
            }
            else
            {
                GenVars.leftBeachEnd += GenVars.beachSandJungleExtraWidth;
            }
            GenVars.rightBeachStart = Main.maxTilesX - genRand.Next(GenVars.beachSandRandomCenter - GenVars.beachSandRandomWidthRange, GenVars.beachSandRandomCenter + GenVars.beachSandRandomWidthRange);
            if (tenthAnniversaryWorldGen && !remixWorldGen)
            {
                GenVars.rightBeachStart = Main.maxTilesX - (GenVars.beachSandRandomCenter + GenVars.beachSandRandomWidthRange);
            }
            if (GenVars.dungeonSide == -1)
            {
                GenVars.rightBeachStart -= GenVars.beachSandDungeonExtraWidth;
            }
            else
            {
                GenVars.rightBeachStart -= GenVars.beachSandJungleExtraWidth;
            }
            int num1074 = 50;
            if (GenVars.dungeonSide == -1)
            {
                GenVars.dungeonLocation = genRand.Next(GenVars.leftBeachEnd + num1074, (int)((double)Main.maxTilesX * 0.2));
            }
            else
            {
                GenVars.dungeonLocation = genRand.Next((int)((double)Main.maxTilesX * 0.8), GenVars.rightBeachStart - num1074);
            }
            int num1075 = 0;
            if (Main.maxTilesX >= 8400)
            {
                num1075 = 2;
            }
            else if (Main.maxTilesX >= 6400)
            {
                num1075 = 1;
            }
            GenVars.extraBastStatueCountMax = 2 + num1075;
            Main.tileSolid[659] = false;
        });
        AddGenerationPass(new TerrainPass());
        AddGenerationPass("Dunes", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_008f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0094: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
            //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
            //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
            //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
            //IL_0155: Unknown result type (might be due to invalid IL or missing references)
            //IL_0107: Unknown result type (might be due to invalid IL or missing references)
            //IL_0174: Unknown result type (might be due to invalid IL or missing references)
            //IL_0181: Unknown result type (might be due to invalid IL or missing references)
            progress.Message = Lang.gen[1].Value;
            int random9 = passConfig.Get<WorldGenRange>("Count").GetRandom(genRand);
            double num1058 = passConfig.Get<double>("ChanceOfPyramid");
            if (drunkWorldGen)
            {
                num1058 = 1.0;
            }
            double num1059 = (double)Main.maxTilesX / 4200.0;
            GenVars.PyrX = new int[random9 + 3];
            GenVars.PyrY = new int[random9 + 3];
            DunesBiome dunesBiome = GenVars.configuration.CreateBiome<DunesBiome>();
            for (int num1060 = 0; num1060 < random9; num1060++)
            {
                progress.Set((double)num1060 / (double)random9);
                Point val7 = Point.Zero;
                bool flag62 = false;
                int num1061 = 0;
                while (!flag62)
                {
                    val7 = RandomWorldPoint(0, 500, 0, 500);
                    bool flag63 = Math.Abs(val7.X - GenVars.jungleOriginX) < (int)(600.0 * num1059);
                    bool flag64 = Math.Abs(val7.X - Main.maxTilesX / 2) < 300;
                    bool flag65 = val7.X > GenVars.snowOriginLeft - 300 && val7.X < GenVars.snowOriginRight + 300;
                    num1061++;
                    if (num1061 >= Main.maxTilesX)
                    {
                        flag63 = false;
                    }
                    if (num1061 >= Main.maxTilesX * 2)
                    {
                        flag65 = false;
                    }
                    flag62 = !(flag63 || flag64 || flag65);
                }
                dunesBiome.Place(val7, GenVars.structures);
                if (genRand.NextDouble() <= num1058)
                {
                    int num1062 = genRand.Next(val7.X - 200, val7.X + 200);
                    for (int num1063 = 0; num1063 < Main.maxTilesY; num1063++)
                    {
                        if (Main.tile[num1062, num1063].active())
{
                            GenVars.PyrX[GenVars.numPyr] = num1062;
                            GenVars.PyrY[GenVars.numPyr] = num1063 + 20;
                            GenVars.numPyr++;
                            break;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Ocean Sand", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Language.GetTextValue("WorldGeneration.OceanSand");
            for (int num1047 = 0; num1047 < 3; num1047++)
            {
                progress.Set((double)num1047 / 3.0);
                int num1048 = genRand.Next(Main.maxTilesX);
                while ((double)num1048 > (double)Main.maxTilesX * 0.4 && (double)num1048 < (double)Main.maxTilesX * 0.6)
                {
                    num1048 = genRand.Next(Main.maxTilesX);
                }
                int num1049 = genRand.Next(35, 90);
                if (num1047 == 1)
                {
                    double num1050 = (double)Main.maxTilesX / 4200.0;
                    num1049 += (int)((double)genRand.Next(20, 40) * num1050);
                }
                if (genRand.Next(3) == 0)
                {
                    num1049 *= 2;
                }
                if (num1047 == 1)
                {
                    num1049 *= 2;
                }
                int num1051 = num1048 - num1049;
                num1049 = genRand.Next(35, 90);
                if (genRand.Next(3) == 0)
                {
                    num1049 *= 2;
                }
                if (num1047 == 1)
                {
                    num1049 *= 2;
                }
                int num1052 = num1048 + num1049;
                if (num1051 < 0)
                {
                    num1051 = 0;
                }
                if (num1052 > Main.maxTilesX)
                {
                    num1052 = Main.maxTilesX;
                }
                if (num1047 == 0)
                {
                    num1051 = 0;
                    num1052 = GenVars.leftBeachEnd;
                }
                else if (num1047 == 2)
                {
                    num1051 = GenVars.rightBeachStart;
                    num1052 = Main.maxTilesX;
                }
                else if (num1047 == 1)
                {
                    continue;
                }
                int num1053 = genRand.Next(50, 100);
                for (int num1054 = num1051; num1054 < num1052; num1054++)
                {
                    if (genRand.Next(2) == 0)
                    {
                        num1053 += genRand.Next(-1, 2);
                        if (num1053 < 50)
{
                            num1053 = 50;
                        }
                        if (num1053 > 200)
{
                            num1053 = 200;
                        }
                    }
                    for (int num1055 = 0; (double)num1055 < (Main.worldSurface + Main.rockLayer) / 2.0; num1055++)
                    {
                        if (Main.tile[num1054, num1055].active())
{
                            if (num1054 == (num1051 + num1052) / 2 && genRand.Next(6) == 0)
{
                                GenVars.PyrX[GenVars.numPyr] = num1054;
                                GenVars.PyrY[GenVars.numPyr] = num1055;
                                GenVars.numPyr++;
                            }
                            int num1056 = num1053;
                            if (num1054 - num1051 < num1056)
{
                                num1056 = num1054 - num1051;
                            }
                            if (num1052 - num1054 < num1056)
{
                                num1056 = num1052 - num1054;
                            }
                            num1056 += genRand.Next(5);
                            for (int num1057 = num1055; num1057 < num1055 + num1056; num1057++)
{
                                if (num1054 > num1051 + genRand.Next(5) && num1054 < num1052 - genRand.Next(5))
{
                                    Main.tile[num1054, num1057].type = 53;
                                }
                            }
                            break;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Sand Patches", delegate
        {
            int num1042 = (int)((double)Main.maxTilesX * 0.013);
            if (remixWorldGen)
            {
                num1042 /= 4;
            }
            for (int num1043 = 0; num1043 < num1042; num1043++)
            {
                int num1044 = genRand.Next(0, Main.maxTilesX);
                int num1045 = genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                if (remixWorldGen)
                {
                    num1045 = genRand.Next((int)Main.rockLayer - 100, Main.maxTilesY - 350);
                }
                while ((double)num1044 > (double)Main.maxTilesX * 0.46 && (double)num1044 < (double)Main.maxTilesX * 0.54 && (double)num1045 < Main.worldSurface + 150.0)
                {
                    num1044 = genRand.Next(0, Main.maxTilesX);
                    num1045 = genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                }
                int num1046 = genRand.Next(15, 70);
                int steps2 = genRand.Next(20, 130);
                TileRunner(num1044, num1045, num1046, steps2, 53);
            }
        });
        AddGenerationPass("Tunnels", delegate
        {
            int num1036 = (int)((double)Main.maxTilesX * 0.0015);
            if (remixWorldGen)
            {
                num1036 = (int)((double)num1036 * 1.5);
            }
            for (int num1037 = 0; num1037 < num1036; num1037++)
            {
                if (GenVars.numTunnels >= GenVars.maxTunnels - 1)
                {
                    break;
                }
                int[] array = new int[10];
                int[] array2 = new int[10];
                int num1038 = genRand.Next(450, Main.maxTilesX - 450);
                if (!remixWorldGen)
                {
                    if (tenthAnniversaryWorldGen)
                    {
                        num1038 = genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                    }
                    else
                    {
                        while ((double)num1038 > (double)Main.maxTilesX * 0.4 && (double)num1038 < (double)Main.maxTilesX * 0.6)
{
                            num1038 = genRand.Next(450, Main.maxTilesX - 450);
                        }
                    }
                }
                int num1039 = 0;
                bool flag61;
                do
                {
                    flag61 = false;
                    for (int num1040 = 0; num1040 < 10; num1040++)
                    {
                        for (num1038 %= Main.maxTilesX; !Main.tile[num1038, num1039].active(); num1039++)
{
                        }
                        if (Main.tile[num1038, num1039].type == 53)
{
                            flag61 = true;
                        }
                        array[num1040] = num1038;
                        array2[num1040] = num1039 - genRand.Next(11, 16);
                        num1038 += genRand.Next(5, 11);
                    }
                }
                while (flag61);
                GenVars.tunnelX[GenVars.numTunnels] = array[5];
                GenVars.numTunnels++;
                for (int num1041 = 0; num1041 < 10; num1041++)
                {
                    TileRunner(array[num1041], array2[num1041], genRand.Next(5, 8), genRand.Next(6, 9), 0, addTile: true, -2.0, -0.3);
                    TileRunner(array[num1041], array2[num1041], genRand.Next(5, 8), genRand.Next(6, 9), 0, addTile: true, 2.0, -0.3);
                }
            }
        });
        AddGenerationPass("Mount Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            GenVars.numMCaves = 0;
            progress.Message = Lang.gen[2].Value;
            int num1028 = (int)((double)Main.maxTilesX * 0.001);
            if (remixWorldGen)
            {
                num1028 = (int)((double)num1028 * 1.5);
            }
            for (int num1029 = 0; num1029 < num1028; num1029++)
            {
                progress.Set((double)num1029 / (double)num1028);
                int num1030 = 0;
                bool flag59 = false;
                bool flag60 = false;
                int num1031 = genRand.Next((int)((double)Main.maxTilesX * 0.25), (int)((double)Main.maxTilesX * 0.75));
                while (!flag60)
                {
                    flag60 = true;
                    if (!remixWorldGen)
                    {
                        while (num1031 > Main.maxTilesX / 2 - 90 && num1031 < Main.maxTilesX / 2 + 90)
{
                            num1031 = genRand.Next((int)((double)Main.maxTilesX * 0.25), (int)((double)Main.maxTilesX * 0.75));
                        }
                    }
                    for (int num1032 = 0; num1032 < GenVars.numMCaves; num1032++)
                    {
                        if (Math.Abs(num1031 - GenVars.mCaveX[num1032]) < 100)
{
                            num1030++;
                            flag60 = false;
                            break;
                        }
                    }
                    if (num1030 >= Main.maxTilesX / 5)
                    {
                        flag59 = true;
                        break;
                    }
                }
                if (!flag59)
                {
                    for (int num1033 = 0; (double)num1033 < Main.worldSurface; num1033++)
                    {
                        if (Main.tile[num1031, num1033].active())
{
                            for (int num1034 = num1031 - 50; num1034 < num1031 + 50; num1034++)
{
                                for (int num1035 = num1033 - 25; num1035 < num1033 + 25; num1035++)
{
                                    if (Main.tile[num1034, num1035].active() && (Main.tile[num1034, num1035].type == 53 || Main.tile[num1034, num1035].type == 151 || Main.tile[num1034, num1035].type == 274))
{
                                        flag59 = true;
                                    }
                                }
                            }
                            if (!flag59)
{
                                Mountinater(num1031, num1033);
                                GenVars.mCaveX[GenVars.numMCaves] = num1031;
                                GenVars.mCaveY[GenVars.numMCaves] = num1033;
                                GenVars.numMCaves++;
                                break;
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Dirt Wall Backgrounds", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[3].Value;
            int num1024 = 0;
            for (int num1025 = 1; num1025 < Main.maxTilesX - 1; num1025++)
            {
                ushort num1026 = 2;
                double value20 = (double)num1025 / (double)Main.maxTilesX;
                progress.Set(value20);
                bool flag58 = false;
                num1024 += genRand.Next(-1, 2);
                if (num1024 < 0)
                {
                    num1024 = 0;
                }
                if (num1024 > 10)
                {
                    num1024 = 10;
                }
                for (int num1027 = 0; (double)num1027 < Main.worldSurface + 10.0 && !((double)num1027 > Main.worldSurface + (double)num1024); num1027++)
                {
                    if (Main.tile[num1025, num1027].active())
                    {
                        num1026 = (ushort)((Main.tile[num1025, num1027].type != 147) ? 2u : 40u);
                    }
                    if (flag58 && Main.tile[num1025, num1027].wall != 64)
                    {
                        Main.tile[num1025, num1027].wall = num1026;
                    }
                    if (Main.tile[num1025, num1027].active() && Main.tile[num1025 - 1, num1027].active() && Main.tile[num1025 + 1, num1027].active() && Main.tile[num1025, num1027 + 1].active() && Main.tile[num1025 - 1, num1027 + 1].active() && Main.tile[num1025 + 1, num1027 + 1].active())
                    {
                        flag58 = true;
                    }
                }
            }
        });
        AddGenerationPass("Rocks In Dirt", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[4].Value;
            double num1018 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.00015;
            for (int num1019 = 0; (double)num1019 < num1018; num1019++)
            {
                TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next(0, (int)GenVars.worldSurfaceLow + 1), genRand.Next(4, 15), genRand.Next(5, 40), 1);
            }
            progress.Set(0.34);
            num1018 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.0002;
            for (int num1020 = 0; (double)num1020 < num1018; num1020++)
            {
                int num1021 = genRand.Next(0, Main.maxTilesX);
                int num1022 = genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh + 1);
                if (!Main.tile[num1021, num1022 - 10].active())
                {
                    num1022 = genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh + 1);
                }
                TileRunner(num1021, num1022, genRand.Next(4, 10), genRand.Next(5, 30), 1);
            }
            progress.Set(0.67);
            num1018 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.0045;
            for (int num1023 = 0; (double)num1023 < num1018; num1023++)
            {
                TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh + 1), genRand.Next(2, 7), genRand.Next(2, 23), 1);
            }
        });
        AddGenerationPass("Dirt In Rocks", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[5].Value;
            double num1014 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.005;
            for (int num1015 = 0; (double)num1015 < num1014; num1015++)
            {
                progress.Set((double)num1015 / num1014);
                TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(2, 6), genRand.Next(2, 40), 0);
            }
            if (remixWorldGen)
            {
                for (int num1016 = 0; num1016 < Main.maxTilesX; num1016++)
                {
                    for (int num1017 = (int)Main.worldSurface + genRand.Next(-1, 3); num1017 < Main.maxTilesY; num1017++)
                    {
                        if (Main.tile[num1016, num1017].active())
{
                            if (Main.tile[num1016, num1017].type == 0)
{
                                Main.tile[num1016, num1017].type = 1;
                            }
                            else if (Main.tile[num1016, num1017].type == 1)
{
                                Main.tile[num1016, num1017].type = 0;
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Clay", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[6].Value;
            for (int num1007 = 0; num1007 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2E-05); num1007++)
            {
                TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next(0, (int)GenVars.worldSurfaceLow), genRand.Next(4, 14), genRand.Next(10, 50), 40);
            }
            progress.Set(0.25);
            if (remixWorldGen)
            {
                for (int num1008 = 0; num1008 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 7E-05); num1008++)
                {
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayer - 25, Main.maxTilesY - 350), genRand.Next(8, 15), genRand.Next(5, 50), 40);
                }
            }
            else
            {
                for (int num1009 = 0; num1009 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 5E-05); num1009++)
                {
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh + 1), genRand.Next(8, 14), genRand.Next(15, 45), 40);
                }
                progress.Set(0.5);
                for (int num1010 = 0; num1010 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2E-05); num1010++)
                {
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh + 1), genRand.Next(8, 15), genRand.Next(5, 50), 40);
                }
            }
            progress.Set(0.75);
            for (int num1011 = 5; num1011 < Main.maxTilesX - 5; num1011++)
            {
                for (int num1012 = 1; (double)num1012 < Main.worldSurface - 1.0; num1012++)
                {
                    if (Main.tile[num1011, num1012].active())
                    {
                        for (int num1013 = num1012; num1013 < num1012 + 5; num1013++)
{
                            if (Main.tile[num1011, num1013].type == 40)
{
                                Main.tile[num1011, num1013].type = 0;
                            }
                        }
                        break;
                    }
                }
            }
        });
        AddGenerationPass("Small Holes", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[7].Value;
            double worldSurfaceHigh2 = GenVars.worldSurfaceHigh;
            for (int num1002 = 0; num1002 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0015); num1002++)
            {
                double value19 = (double)num1002 / ((double)(Main.maxTilesX * Main.maxTilesY) * 0.0015);
                progress.Set(value19);
                int type13 = -1;
                if (genRand.Next(5) == 0)
                {
                    type13 = -2;
                }
                int num1003 = genRand.Next(0, Main.maxTilesX);
                int num1004 = genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                if (!remixWorldGen && tenthAnniversaryWorldGen)
                {
                    while ((double)num1003 < (double)Main.maxTilesX * 0.2 && (double)num1003 > (double)Main.maxTilesX * 0.8 && (double)num1004 < GenVars.worldSurface)
                    {
                        num1003 = genRand.Next(0, Main.maxTilesX);
                        num1004 = genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                    }
                }
                else
                {
                    while (((num1003 < GenVars.smallHolesBeachAvoidance || num1003 > Main.maxTilesX - GenVars.smallHolesBeachAvoidance) && (double)num1004 < worldSurfaceHigh2) || ((double)num1003 > (double)Main.maxTilesX * 0.45 && (double)num1003 < (double)Main.maxTilesX * 0.55 && (double)num1004 < GenVars.worldSurface))
                    {
                        num1003 = genRand.Next(0, Main.maxTilesX);
                        num1004 = genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                    }
                }
                int num1005 = genRand.Next(2, 5);
                int num1006 = genRand.Next(2, 20);
                if (remixWorldGen && (double)num1004 > Main.rockLayer)
                {
                    num1005 = (int)((double)num1005 * 0.8);
                    num1006 = (int)((double)num1006 * 0.9);
                }
                TileRunner(num1003, num1004, num1005, num1006, type13);
                num1003 = genRand.Next(0, Main.maxTilesX);
                num1004 = genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                while (((num1003 < GenVars.smallHolesBeachAvoidance || num1003 > Main.maxTilesX - GenVars.smallHolesBeachAvoidance) && (double)num1004 < worldSurfaceHigh2) || ((double)num1003 > (double)Main.maxTilesX * 0.45 && (double)num1003 < (double)Main.maxTilesX * 0.55 && (double)num1004 < GenVars.worldSurface))
                {
                    num1003 = genRand.Next(0, Main.maxTilesX);
                    num1004 = genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                }
                num1005 = genRand.Next(8, 15);
                num1006 = genRand.Next(7, 30);
                if (remixWorldGen && (double)num1004 > Main.rockLayer)
                {
                    num1005 = (int)((double)num1005 * 0.7);
                    num1006 = (int)((double)num1006 * 0.9);
                }
                TileRunner(num1003, num1004, num1005, num1006, type13);
            }
        });
        AddGenerationPass("Dirt Layer Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[8].Value;
            double worldSurfaceHigh = GenVars.worldSurfaceHigh;
            int num996 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 3E-05);
            if (remixWorldGen)
            {
                num996 *= 2;
            }
            for (int num997 = 0; num997 < num996; num997++)
            {
                double value18 = (double)num997 / (double)num996;
                progress.Set(value18);
                if (GenVars.rockLayerHigh <= (double)Main.maxTilesY)
                {
                    int type12 = -1;
                    if (genRand.Next(6) == 0)
                    {
                        type12 = -2;
                    }
                    int num998 = genRand.Next(0, Main.maxTilesX);
                    int num999 = genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.rockLayerHigh + 1);
                    while (((num998 < GenVars.smallHolesBeachAvoidance || num998 > Main.maxTilesX - GenVars.smallHolesBeachAvoidance) && (double)num999 < worldSurfaceHigh) || ((double)num998 >= (double)Main.maxTilesX * 0.45 && (double)num998 <= (double)Main.maxTilesX * 0.55 && (double)num999 < Main.worldSurface))
                    {
                        num998 = genRand.Next(0, Main.maxTilesX);
                        num999 = genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.rockLayerHigh + 1);
                    }
                    int num1000 = genRand.Next(5, 15);
                    int num1001 = genRand.Next(30, 200);
                    if (remixWorldGen)
                    {
                        num1000 = (int)((double)num1000 * 1.1);
                        num1001 = (int)((double)num1001 * 1.9);
                    }
                    TileRunner(num998, num999, num1000, num1001, type12);
                }
            }
        });
        AddGenerationPass("Rock Layer Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[9].Value;
            int num988 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00013);
            if (remixWorldGen)
            {
                num988 = (int)((double)num988 * 1.1);
            }
            for (int num989 = 0; num989 < num988; num989++)
            {
                double value17 = (double)num989 / (double)num988;
                progress.Set(value17);
                if (GenVars.rockLayerHigh <= (double)Main.maxTilesY)
                {
                    int type10 = -1;
                    if (genRand.Next(10) == 0)
                    {
                        type10 = -2;
                    }
                    int num990 = genRand.Next(6, 20);
                    int num991 = genRand.Next(50, 300);
                    if (remixWorldGen)
                    {
                        num990 = (int)((double)num990 * 0.7);
                        num991 = (int)((double)num991 * 0.7);
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerHigh, Main.maxTilesY), num990, num991, type10);
                }
            }
            if (remixWorldGen)
            {
                num988 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00013 * 0.4);
                for (int num992 = 0; num992 < num988; num992++)
                {
                    if (GenVars.rockLayerHigh <= (double)Main.maxTilesY)
                    {
                        int type11 = -1;
                        if (genRand.Next(10) == 0)
{
                            type11 = -2;
                        }
                        int num993 = genRand.Next(7, 26);
                        int steps = genRand.Next(50, 200);
                        double num994 = (double)genRand.Next(100, 221) * 0.1;
                        double num995 = (double)genRand.Next(-10, 11) * 0.02;
                        int i5 = genRand.Next(0, Main.maxTilesX);
                        int j7 = genRand.Next((int)GenVars.rockLayerHigh, Main.maxTilesY);
                        TileRunner(i5, j7, num993, steps, type11, addTile: false, num994, num995, noYChange: true);
                        TileRunner(i5, j7, num993, steps, type11, addTile: false, 0.0 - num994, 0.0 - num995, noYChange: true);
                    }
                }
            }
        });
        AddGenerationPass("Surface Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[10].Value;
            int num969 = (int)((double)Main.maxTilesX * 0.002);
            int num970 = (int)((double)Main.maxTilesX * 0.0007);
            int num971 = (int)((double)Main.maxTilesX * 0.0003);
            if (remixWorldGen)
            {
                num969 *= 3;
                num970 *= 3;
                num971 *= 3;
            }
            for (int num972 = 0; num972 < num969; num972++)
            {
                int num973 = genRand.Next(0, Main.maxTilesX);
                while (((double)num973 > (double)Main.maxTilesX * 0.45 && (double)num973 < (double)Main.maxTilesX * 0.55) || num973 < GenVars.leftBeachEnd + 20 || num973 > GenVars.rightBeachStart - 20)
                {
                    num973 = genRand.Next(0, Main.maxTilesX);
                }
                for (int num974 = 0; (double)num974 < GenVars.worldSurfaceHigh; num974++)
                {
                    if (Main.tile[num973, num974].active())
                    {
                        TileRunner(num973, num974, genRand.Next(3, 6), genRand.Next(5, 50), -1, addTile: false, (double)genRand.Next(-10, 11) * 0.1, 1.0);
                        break;
                    }
                }
            }
            progress.Set(0.2);
            for (int num975 = 0; num975 < num970; num975++)
            {
                int num976 = genRand.Next(0, Main.maxTilesX);
                while (((double)num976 > (double)Main.maxTilesX * 0.43 && (double)num976 < (double)Main.maxTilesX * 0.5700000000000001) || num976 < GenVars.leftBeachEnd + 20 || num976 > GenVars.rightBeachStart - 20)
                {
                    num976 = genRand.Next(0, Main.maxTilesX);
                }
                for (int num977 = 0; (double)num977 < GenVars.worldSurfaceHigh; num977++)
                {
                    if (Main.tile[num976, num977].active())
                    {
                        TileRunner(num976, num977, genRand.Next(10, 15), genRand.Next(50, 130), -1, addTile: false, (double)genRand.Next(-10, 11) * 0.1, 2.0);
                        break;
                    }
                }
            }
            progress.Set(0.4);
            for (int num978 = 0; num978 < num971; num978++)
            {
                int num979 = genRand.Next(0, Main.maxTilesX);
                while (((double)num979 > (double)Main.maxTilesX * 0.4 && (double)num979 < (double)Main.maxTilesX * 0.6) || num979 < GenVars.leftBeachEnd + 20 || num979 > GenVars.rightBeachStart - 20)
                {
                    num979 = genRand.Next(0, Main.maxTilesX);
                }
                for (int num980 = 0; (double)num980 < GenVars.worldSurfaceHigh; num980++)
                {
                    if (Main.tile[num979, num980].active())
                    {
                        TileRunner(num979, num980, genRand.Next(12, 25), genRand.Next(150, 500), -1, addTile: false, (double)genRand.Next(-10, 11) * 0.1, 4.0);
                        TileRunner(num979, num980, genRand.Next(8, 17), genRand.Next(60, 200), -1, addTile: false, (double)genRand.Next(-10, 11) * 0.1, 2.0);
                        TileRunner(num979, num980, genRand.Next(5, 13), genRand.Next(40, 170), -1, addTile: false, (double)genRand.Next(-10, 11) * 0.1, 2.0);
                        break;
                    }
                }
            }
            progress.Set(0.6);
            for (int num981 = 0; num981 < (int)((double)Main.maxTilesX * 0.0004); num981++)
            {
                int num982 = genRand.Next(0, Main.maxTilesX);
                while (((double)num982 > (double)Main.maxTilesX * 0.4 && (double)num982 < (double)Main.maxTilesX * 0.6) || num982 < GenVars.leftBeachEnd + 20 || num982 > GenVars.rightBeachStart - 20)
                {
                    num982 = genRand.Next(0, Main.maxTilesX);
                }
                for (int num983 = 0; (double)num983 < GenVars.worldSurfaceHigh; num983++)
                {
                    if (Main.tile[num982, num983].active())
                    {
                        TileRunner(num982, num983, genRand.Next(7, 12), genRand.Next(150, 250), -1, addTile: false, 0.0, 1.0, noYChange: true);
                        break;
                    }
                }
            }
            progress.Set(0.8);
            double num984 = (double)Main.maxTilesX / 4200.0;
            for (int num985 = 0; (double)num985 < 5.0 * num984; num985++)
            {
                try
                {
                    int num986 = (int)Main.rockLayer;
                    int num987 = Main.maxTilesY - 400;
                    if (num986 >= num987)
                    {
                        num986 = num987 - 1;
                    }
                    Caverer(genRand.Next(GenVars.surfaceCavesBeachAvoidance2, Main.maxTilesX - GenVars.surfaceCavesBeachAvoidance2), genRand.Next(num986, num987));
                }
                catch
                {
                }
            }
        });
        AddGenerationPass("Wavy Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (dontStarveWorldGen)
            {
                progress.Message = Language.GetTextValue("WorldGeneration.WavyCaves");
                double num960 = (double)Main.maxTilesX / 4200.0;
                num960 *= num960;
                int num961 = (int)(35.0 * num960);
                if (Main.remixWorld)
                {
                    num961 /= 3;
                }
                int num962 = 0;
                int num963 = 80;
                for (int num964 = 0; num964 < num961; num964++)
                {
                    double num965 = (double)num964 / (double)(num961 - 1);
                    progress.Set(num965);
                    int num966 = genRand.Next((int)Main.worldSurface + 100, Main.UnderworldLayer - 100);
                    int num967 = 0;
                    while (Math.Abs(num966 - num962) < num963)
                    {
                        num967++;
                        if (num967 > 100)
{
                            break;
                        }
                        num966 = genRand.Next((int)Main.worldSurface + 100, Main.UnderworldLayer - 100);
                    }
                    num962 = num966;
                    int num968 = 80;
                    int startX = num968 + (int)((double)(Main.maxTilesX - num968 * 2) * num965);
                    try
                    {
                        WavyCaverer(startX, num966, 12 + genRand.Next(3, 6), 0.25 + genRand.NextDouble(), genRand.Next(300, 500), -1);
                    }
                    catch
                    {
                    }
                }
            }
        });
        AddGenerationPass("Generate Ice Biome", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[56].Value;
            GenVars.snowTop = (int)Main.worldSurface;
            int num952 = GenVars.lavaLine - genRand.Next(160, 200);
            int num953 = GenVars.lavaLine;
            if (remixWorldGen)
            {
                num953 = Main.maxTilesY - 250;
                num952 = num953 - genRand.Next(160, 200);
            }
            int num954 = GenVars.snowOriginLeft;
            int num955 = GenVars.snowOriginRight;
            int num956 = 10;
            for (int num957 = 0; num957 <= num953 - 140; num957++)
            {
                progress.Set((double)num957 / (double)(num953 - 140));
                num954 += genRand.Next(-4, 4);
                num955 += genRand.Next(-3, 5);
                if (num957 > 0)
                {
                    num954 = (num954 + GenVars.snowMinX[num957 - 1]) / 2;
                    num955 = (num955 + GenVars.snowMaxX[num957 - 1]) / 2;
                }
                if (GenVars.dungeonSide > 0)
                {
                    if (genRand.Next(4) == 0)
                    {
                        num954++;
                        num955++;
                    }
                }
                else if (genRand.Next(4) == 0)
                {
                    num954--;
                    num955--;
                }
                GenVars.snowMinX[num957] = num954;
                GenVars.snowMaxX[num957] = num955;
                for (int num958 = num954; num958 < num955; num958++)
                {
                    if (num957 < num952)
                    {
                        if (Main.tile[num958, num957].wall == 2)
{
                            Main.tile[num958, num957].wall = 40;
                        }
                        switch (Main.tile[num958, num957].type)
{
                        case 0:
                        case 2:
                        case 23:
                        case 40:
                        case 53:
                            Main.tile[num958, num957].type = 147;
                            break;
                        case 1:
                            Main.tile[num958, num957].type = 161;
                            break;
                        }
                    }
                    else
                    {
                        num956 += genRand.Next(-3, 4);
                        if (genRand.Next(3) == 0)
{
                            num956 += genRand.Next(-4, 5);
                            if (genRand.Next(3) == 0)
{
                                num956 += genRand.Next(-6, 7);
                            }
                        }
                        if (num956 < 0)
{
                            num956 = genRand.Next(3);
                        }
                        else if (num956 > 50)
{
                            num956 = 50 - genRand.Next(3);
                        }
                        for (int num959 = num957; num959 < num957 + num956; num959++)
{
                            if (Main.tile[num958, num959].wall == 2)
{
                                Main.tile[num958, num959].wall = 40;
                            }
                            switch (Main.tile[num958, num959].type)
{
                            case 0:
                            case 2:
                            case 23:
                            case 40:
                            case 53:
                                Main.tile[num958, num959].type = 147;
                                break;
                            case 1:
                                Main.tile[num958, num959].type = 161;
                                break;
                            }
                        }
                    }
                }
                if (GenVars.snowBottom < num957)
                {
                    GenVars.snowBottom = num957;
                }
            }
        });
        AddGenerationPass("Grass", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            double num948 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.002;
            for (int num949 = 0; (double)num949 < num948; num949++)
            {
                progress.Set((double)num949 / num948);
                int num950 = genRand.Next(1, Main.maxTilesX - 1);
                int num951 = genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh);
                if (num951 >= Main.maxTilesY)
                {
                    num951 = Main.maxTilesY - 2;
                }
                if (Main.tile[num950 - 1, num951].active() && Main.tile[num950 - 1, num951].type == 0 && Main.tile[num950 + 1, num951].active() && Main.tile[num950 + 1, num951].type == 0 && Main.tile[num950, num951 - 1].active() && Main.tile[num950, num951 - 1].type == 0 && Main.tile[num950, num951 + 1].active() && Main.tile[num950, num951 + 1].type == 0)
                {
                    Main.tile[num950, num951].active(active: true);
                    Main.tile[num950, num951].type = 2;
                }
                num950 = genRand.Next(1, Main.maxTilesX - 1);
                num951 = genRand.Next(0, (int)GenVars.worldSurfaceLow);
                if (num951 >= Main.maxTilesY)
                {
                    num951 = Main.maxTilesY - 2;
                }
                if (Main.tile[num950 - 1, num951].active() && Main.tile[num950 - 1, num951].type == 0 && Main.tile[num950 + 1, num951].active() && Main.tile[num950 + 1, num951].type == 0 && Main.tile[num950, num951 - 1].active() && Main.tile[num950, num951 - 1].type == 0 && Main.tile[num950, num951 + 1].active() && Main.tile[num950, num951 + 1].type == 0)
                {
                    Main.tile[num950, num951].active(active: true);
                    Main.tile[num950, num951].type = 2;
                }
            }
        });
        AddGenerationPass(new JunglePass());
        AddGenerationPass("Mud Caves To Grass", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[77].Value;
            NotTheBees();
            for (int num943 = 0; num943 < Main.maxTilesX; num943++)
            {
                for (int num944 = 0; num944 < Main.maxTilesY; num944++)
                {
                    if (Main.tile[num943, num944].active())
                    {
                        grassSpread = 0;
                        SpreadGrass(num943, num944, 59, 60);
                    }
                    progress.Set(0.2 * ((double)(num943 * Main.maxTilesY + num944) / (double)(Main.maxTilesX * Main.maxTilesY)));
                }
            }
            SmallConsecutivesFound = 0;
            SmallConsecutivesEliminated = 0;
            double num945 = Main.maxTilesX - 20;
            for (int num946 = 10; num946 < Main.maxTilesX - 10; num946++)
            {
                ScanTileColumnAndRemoveClumps(num946);
                double num947 = (double)(num946 - 10) / num945;
                progress.Set(0.2 + num947 * 0.8);
            }
        });
        AddGenerationPass("Full Desert", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
            progress.Message = Lang.gen[78].Value;
            Main.tileSolid[484] = false;
            int num934 = 0;
            int num935 = GenVars.dungeonSide;
            int num936 = Main.maxTilesX / 2;
            int num937 = genRand.Next(num936) / 8;
            num937 += num936 / 8;
            int num938 = num936 + num937 * -num935;
            int num939 = 0;
            DesertBiome desertBiome = GenVars.configuration.CreateBiome<DesertBiome>();
            while (!desertBiome.Place(new Point(num938, (int)GenVars.worldSurfaceHigh + 25), GenVars.structures))
            {
                num937 = genRand.Next(num936) / 2;
                num937 += num936 / 8;
                num937 += genRand.Next(num939 / 12);
                num938 = num936 + num937 * -num935;
                if (++num939 > Main.maxTilesX / 4)
                {
                    num935 *= -1;
                    num939 = 0;
                    num934++;
                    if (num934 >= 2)
                    {
                        GenVars.skipDesertTileCheck = true;
                    }
                }
            }
            if (remixWorldGen)
            {
                for (int num940 = 50; num940 < Main.maxTilesX - 50; num940++)
                {
                    for (int num941 = (int)Main.rockLayer + genRand.Next(-1, 2); num941 < Main.maxTilesY - 50; num941++)
                    {
                        if ((Main.tile[num940, num941].type == 396 || Main.tile[num940, num941].type == 397 || Main.tile[num940, num941].type == 53) && !SolidTile(num940, num941 - 1))
{
                            for (int num942 = num941; num942 < num941 + genRand.Next(4, 7) && Main.tile[num940, num942 + 1].active() && (Main.tile[num940, num942].type == 396 || Main.tile[num940, num942].type == 397); num942++)
{
                                Main.tile[num940, num942].type = 53;
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Floating Islands", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            GenVars.numIslandHouses = 0;
            GenVars.skyIslandHouseCount = 0;
            progress.Message = Lang.gen[12].Value;
            int num924 = (int)((double)Main.maxTilesX * 0.0008);
            int num925 = 0;
            double num926 = num924 + GenVars.skyLakes;
            for (int num927 = 0; (double)num927 < num926; num927++)
            {
                progress.Set((double)num927 / num926);
                int num928 = Main.maxTilesX;
                while (--num928 > 0)
                {
                    bool flag57 = true;
                    int num929 = genRand.Next((int)((double)Main.maxTilesX * 0.1), (int)((double)Main.maxTilesX * 0.9));
                    while (num929 > Main.maxTilesX / 2 - 150 && num929 < Main.maxTilesX / 2 + 150)
                    {
                        num929 = genRand.Next((int)((double)Main.maxTilesX * 0.1), (int)((double)Main.maxTilesX * 0.9));
                    }
                    for (int num930 = 0; num930 < GenVars.numIslandHouses; num930++)
                    {
                        if (num929 > GenVars.floatingIslandHouseX[num930] - 180 && num929 < GenVars.floatingIslandHouseX[num930] + 180)
{
                            flag57 = false;
                            break;
                        }
                    }
                    if (flag57)
                    {
                        flag57 = false;
                        int num931 = 0;
                        for (int num932 = 200; (double)num932 < Main.worldSurface; num932++)
{
                            if (Main.tile[num929, num932].active())
{
                                num931 = num932;
                                flag57 = true;
                                break;
                            }
                        }
                        if (flag57)
{
                            int num933 = 0;
                            num928 = -1;
                            int val6 = genRand.Next(90, num931 - 100);
                            val6 = Math.Min(val6, (int)GenVars.worldSurfaceLow - 50);
                            if (num925 >= num924)
{
                                GenVars.skyLake[GenVars.numIslandHouses] = true;
                                CloudLake(num929, val6);
                            }
                            else
{
                                GenVars.skyLake[GenVars.numIslandHouses] = false;
                                if (drunkWorldGen && !remixWorldGen)
{
                                    if (genRand.Next(2) == 0)
{
                                        num933 = 3;
                                        SnowCloudIsland(num929, val6);
                                    }
                                    else
{
                                        num933 = 1;
                                        DesertCloudIsland(num929, val6);
                                    }
                                }
                                else
{
                                    if (remixWorldGen && drunkWorldGen)
{
                                        num933 = ((GenVars.crimsonLeft && num929 < Main.maxTilesX / 2) ? 5 : ((GenVars.crimsonLeft || num929 <= Main.maxTilesX / 2) ? 4 : 5));
                                    }
                                    else if (getGoodWorldGen || remixWorldGen)
{
                                        num933 = ((!crimson) ? 4 : 5);
                                    }
                                    else if (Main.tenthAnniversaryWorld)
{
                                        num933 = 6;
                                    }
                                    CloudIsland(num929, val6);
                                }
                            }
                            GenVars.floatingIslandHouseX[GenVars.numIslandHouses] = num929;
                            GenVars.floatingIslandHouseY[GenVars.numIslandHouses] = val6;
                            GenVars.floatingIslandStyle[GenVars.numIslandHouses] = num933;
                            GenVars.numIslandHouses++;
                            num925++;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Mushroom Patches", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_02a4: Unknown result type (might be due to invalid IL or missing references)
            //IL_025c: Unknown result type (might be due to invalid IL or missing references)
            progress.Message = Lang.gen[13].Value;
            if (remixWorldGen)
            {
                for (int num905 = 10; num905 < Main.maxTilesX - 10; num905++)
                {
                    for (int num906 = Main.maxTilesY + genRand.Next(3) - 350; num906 < Main.maxTilesY - 10; num906++)
                    {
                        if (Main.tile[num905, num906].type == 0)
{
                            Main.tile[num905, num906].type = 59;
                        }
                    }
                }
            }
            double num907 = (double)Main.maxTilesX / 700.0;
            if (num907 > (double)GenVars.maxMushroomBiomes)
            {
                num907 = GenVars.maxMushroomBiomes;
            }
            for (int num908 = 0; (double)num908 < num907; num908++)
            {
                int num909 = 0;
                bool flag56 = true;
                while (flag56)
                {
                    int num910 = genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                    if (num909 > Main.maxTilesX / 4)
                    {
                        num910 = genRand.Next((int)((double)Main.maxTilesX * 0.25), (int)((double)Main.maxTilesX * 0.975));
                    }
                    int num911 = ((!remixWorldGen) ? genRand.Next((int)Main.rockLayer + 50, Main.maxTilesY - 300) : genRand.Next((int)Main.worldSurface + 50, (int)Main.rockLayer - 50));
                    flag56 = false;
                    int num912 = 100;
                    int num913 = 500;
                    for (int num914 = num910 - num912; num914 < num910 + num912; num914 += 3)
                    {
                        for (int num915 = num911 - num912; num915 < num911 + num912; num915 += 3)
{
                            if (InWorld(num914, num915))
{
                                if (Main.tile[num914, num915].type == 147 || Main.tile[num914, num915].type == 161 || Main.tile[num914, num915].type == 162 || Main.tile[num914, num915].type == 60 || Main.tile[num914, num915].type == 368 || Main.tile[num914, num915].type == 367)
{
                                    flag56 = true;
                                    break;
                                }
                                if (((Rectangle)(ref GenVars.UndergroundDesertLocation)).Contains(new Point(num914, num915)))
{
                                    flag56 = true;
                                    break;
                                }
                            }
                            else
{
                                flag56 = true;
                            }
                        }
                    }
                    if (!flag56)
                    {
                        for (int num916 = 0; num916 < GenVars.numMushroomBiomes; num916++)
{
                            if (Vector2D.Distance(GenVars.mushroomBiomesPosition[num916].ToVector2D(), new Vector2D(num910, num911)) < (double)num913)
{
                                flag56 = true;
                            }
                        }
                    }
                    if (!flag56 && GenVars.numMushroomBiomes < GenVars.maxMushroomBiomes)
                    {
                        ShroomPatch(num910, num911);
                        for (int num917 = 0; num917 < 5; num917++)
{
                            int i4 = num910 + genRand.Next(-40, 41);
                            int j6 = num911 + genRand.Next(-40, 41);
                            ShroomPatch(i4, j6);
                        }
                        GenVars.mushroomBiomesPosition[GenVars.numMushroomBiomes].X = num910;
                        GenVars.mushroomBiomesPosition[GenVars.numMushroomBiomes].Y = num911;
                        GenVars.numMushroomBiomes++;
                    }
                    num909++;
                    if (num909 > Main.maxTilesX / 2)
                    {
                        break;
                    }
                }
            }
            for (int num918 = 0; num918 < Main.maxTilesX; num918++)
            {
                progress.Set((double)num918 / (double)Main.maxTilesX);
                for (int num919 = (int)Main.worldSurface; num919 < Main.maxTilesY; num919++)
                {
                    if (InWorld(num918, num919, 50) && Main.tile[num918, num919].active())
                    {
                        grassSpread = 0;
                        SpreadGrass(num918, num919, 59, 70, repeat: false);
                    }
                }
            }
            for (int num920 = 0; num920 < Main.maxTilesX; num920++)
            {
                for (int num921 = (int)Main.worldSurface; num921 < Main.maxTilesY; num921++)
                {
                    if (Main.tile[num920, num921].active() && Main.tile[num920, num921].type == 70)
                    {
                        int type9 = 59;
                        for (int num922 = num920 - 1; num922 <= num920 + 1; num922++)
{
                            for (int num923 = num921 - 1; num923 <= num921 + 1; num923++)
{
                                if (Main.tile[num922, num923].active())
{
                                    if (!Main.tile[num922 - 1, num923].active() && !Main.tile[num922 + 1, num923].active())
{
                                        KillTile(num922, num923);
                                    }
                                    else if (!Main.tile[num922, num923 - 1].active() && !Main.tile[num922, num923 + 1].active())
{
                                        KillTile(num922, num923);
                                    }
                                }
                                else if (Main.tile[num922 - 1, num923].active() && Main.tile[num922 + 1, num923].active())
{
                                    PlaceTile(num922, num923, type9);
                                    if (Main.tile[num922 - 1, num921].type == 70)
{
                                        Main.tile[num922 - 1, num921].type = 59;
                                    }
                                    if (Main.tile[num922 + 1, num921].type == 70)
{
                                        Main.tile[num922 + 1, num921].type = 59;
                                    }
                                }
                                else if (Main.tile[num922, num923 - 1].active() && Main.tile[num922, num923 + 1].active())
{
                                    PlaceTile(num922, num923, type9);
                                    if (Main.tile[num922, num921 - 1].type == 70)
{
                                        Main.tile[num922, num921 - 1].type = 59;
                                    }
                                    if (Main.tile[num922, num921 + 1].type == 70)
{
                                        Main.tile[num922, num921 + 1].type = 59;
                                    }
                                }
                            }
                        }
                        if (genRand.Next(4) == 0)
{
                            int x29 = num920 + genRand.Next(-20, 21);
                            int y24 = num921 + genRand.Next(-20, 21);
                            if (InWorld(x29, y24) && Main.tile[x29, y24].type == 59)
{
                                Main.tile[x29, y24].type = 70;
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Marble", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_0091: Unknown result type (might be due to invalid IL or missing references)
            //IL_0096: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
            //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
            //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
            //IL_0130: Unknown result type (might be due to invalid IL or missing references)
            //IL_0111: Unknown result type (might be due to invalid IL or missing references)
            progress.Message = Lang.gen[80].Value;
            int num900 = passConfig.Get<WorldGenRange>("Count").GetRandom(genRand);
            double num901 = (double)(Main.maxTilesX - 160) / (double)num900;
            MarbleBiome marbleBiome = GenVars.configuration.CreateBiome<MarbleBiome>();
            int num902 = 0;
            int num903 = 0;
            while (num903 < num900)
            {
                double num904 = (double)num903 / (double)num900;
                progress.Set(num904);
                Point val5 = RandomRectanglePoint((int)(num904 * (double)(Main.maxTilesX - 160)) + 80, (int)GenVars.rockLayer + 20, (int)num901, Main.maxTilesY - ((int)GenVars.rockLayer + 40) - 200);
                if (remixWorldGen)
                {
                    val5 = RandomRectanglePoint((int)(num904 * (double)(Main.maxTilesX - 160)) + 80, (int)GenVars.worldSurface + 100, (int)num901, (int)GenVars.rockLayer - (int)GenVars.worldSurface - 100);
                }
                while ((double)val5.X > (double)Main.maxTilesX * 0.45 && (double)val5.X < (double)Main.maxTilesX * 0.55)
                {
                    val5.X = genRand.Next(beachDistance, Main.maxTilesX - beachDistance);
                }
                num902++;
                if (marbleBiome.Place(val5, GenVars.structures))
                {
                    num903++;
                    num902 = 0;
                }
                else if (num902 > Main.maxTilesX * 10)
                {
                    num900 = num903;
                    num903++;
                    num902 = 0;
                }
            }
        });
        AddGenerationPass("Granite", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_008d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0092: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
            //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
            //IL_012b: Unknown result type (might be due to invalid IL or missing references)
            //IL_010d: Unknown result type (might be due to invalid IL or missing references)
            //IL_017d: Unknown result type (might be due to invalid IL or missing references)
            //IL_013a: Unknown result type (might be due to invalid IL or missing references)
            progress.Message = Lang.gen[81].Value;
            int num894 = passConfig.Get<WorldGenRange>("Count").GetRandom(genRand);
            double num895 = (double)(Main.maxTilesX - 200) / (double)num894;
            List<Point> list2 = new List<Point>(num894);
            int num896 = 0;
            int num897 = 0;
            while (num897 < num894)
            {
                double num898 = (double)num897 / (double)num894;
                progress.Set(num898);
                Point val4 = RandomRectanglePoint((int)(num898 * (double)(Main.maxTilesX - 200)) + 100, (int)GenVars.rockLayer + 20, (int)num895, Main.maxTilesY - ((int)GenVars.rockLayer + 40) - 200);
                if (remixWorldGen)
                {
                    val4 = RandomRectanglePoint((int)(num898 * (double)(Main.maxTilesX - 200)) + 100, (int)GenVars.worldSurface + 100, (int)num895, (int)GenVars.rockLayer - (int)GenVars.worldSurface - 100);
                }
                while ((double)val4.X > (double)Main.maxTilesX * 0.45 && (double)val4.X < (double)Main.maxTilesX * 0.55)
                {
                    val4.X = genRand.Next(beachDistance, Main.maxTilesX - beachDistance);
                }
                num896++;
                if (GraniteBiome.CanPlace(val4, GenVars.structures))
                {
                    list2.Add(val4);
                    num897++;
                }
                else if (num896 > Main.maxTilesX * 10)
                {
                    num894 = num897;
                    num897++;
                    num896 = 0;
                }
            }
            GraniteBiome graniteBiome = GenVars.configuration.CreateBiome<GraniteBiome>();
            for (int num899 = 0; num899 < num894; num899++)
            {
                graniteBiome.Place(list2[num899], GenVars.structures);
            }
        });
        AddGenerationPass("Dirt To Mud", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[14].Value;
            double num892 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.001;
            for (int num893 = 0; (double)num893 < num892; num893++)
            {
                progress.Set((double)num893 / num892);
                if (remixWorldGen)
                {
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.worldSurface, (int)GenVars.rockLayerLow), genRand.Next(2, 6), genRand.Next(2, 40), 59, addTile: false, 0.0, 0.0, noYChange: false, overRide: true, 53);
                }
                else
                {
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(2, 6), genRand.Next(2, 40), 59, addTile: false, 0.0, 0.0, noYChange: false, overRide: true, 53);
                }
            }
        });
        AddGenerationPass("Silt", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[15].Value;
            for (int num886 = 0; num886 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0001); num886++)
            {
                int num887 = genRand.Next(0, Main.maxTilesX);
                int num888 = genRand.Next((int)GenVars.rockLayerHigh, Main.maxTilesY);
                if (remixWorldGen)
                {
                    num888 = genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                }
                if (Main.tile[num887, num888].wall != 187 && Main.tile[num887, num888].wall != 216)
                {
                    TileRunner(num887, num888, genRand.Next(5, 12), genRand.Next(15, 50), 123);
                }
            }
            for (int num889 = 0; num889 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0005); num889++)
            {
                int num890 = genRand.Next(0, Main.maxTilesX);
                int num891 = genRand.Next((int)GenVars.rockLayerHigh, Main.maxTilesY);
                if (remixWorldGen)
                {
                    num891 = genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                }
                if (Main.tile[num890, num891].wall != 187 && Main.tile[num890, num891].wall != 216)
                {
                    TileRunner(num890, num891, genRand.Next(2, 5), genRand.Next(2, 5), 123);
                }
            }
        });
        AddGenerationPass("Shinies", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[16].Value;
            if (remixWorldGen)
            {
                for (int num856 = 0; num856 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 6E-05); num856++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.copper = 7;
                        }
                        else
{
                            GenVars.copper = 166;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh), genRand.Next(3, 6), genRand.Next(2, 6), GenVars.copper);
                }
                for (int num857 = 0; num857 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 8E-05); num857++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.copper = 7;
                        }
                        else
{
                            GenVars.copper = 166;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), genRand.Next(3, 7), genRand.Next(3, 7), GenVars.copper);
                }
                for (int num858 = 0; num858 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0002); num858++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.copper = 7;
                        }
                        else
{
                            GenVars.copper = 166;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.copper);
                }
                for (int num859 = 0; num859 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 3E-05); num859++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.iron = 6;
                        }
                        else
{
                            GenVars.iron = 167;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh), genRand.Next(3, 7), genRand.Next(2, 5), GenVars.iron);
                }
                for (int num860 = 0; num860 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 8E-05); num860++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.iron = 6;
                        }
                        else
{
                            GenVars.iron = 167;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), genRand.Next(3, 6), genRand.Next(3, 6), GenVars.iron);
                }
                for (int num861 = 0; num861 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0002); num861++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.iron = 6;
                        }
                        else
{
                            GenVars.iron = 167;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.iron);
                }
                for (int num862 = 0; num862 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.6E-05); num862++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.silver = 9;
                        }
                        else
{
                            GenVars.silver = 168;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.rockLayer - 100, Main.maxTilesY - 250), genRand.Next(3, 6), genRand.Next(3, 6), GenVars.silver);
                }
                for (int num863 = 0; num863 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00015); num863++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.silver = 9;
                        }
                        else
{
                            GenVars.silver = 168;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.worldSurface, (int)Main.rockLayer), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.silver);
                }
                for (int num864 = 0; num864 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00017); num864++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.silver = 9;
                        }
                        else
{
                            GenVars.silver = 168;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next(0, (int)GenVars.worldSurfaceLow), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.silver);
                }
                for (int num865 = 0; num865 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00012); num865++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.gold = 8;
                        }
                        else
{
                            GenVars.gold = 169;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.worldSurface, (int)Main.rockLayer), genRand.Next(4, 8), genRand.Next(4, 8), GenVars.gold);
                }
                for (int num866 = 0; num866 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00012); num866++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.gold = 8;
                        }
                        else
{
                            GenVars.gold = 169;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next(0, (int)GenVars.worldSurfaceLow - 20), genRand.Next(4, 8), genRand.Next(4, 8), GenVars.gold);
                }
                if (drunkWorldGen)
                {
                    for (int num867 = 0; num867 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05 / 2.0); num867++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.rockLayer, Main.maxTilesY), genRand.Next(3, 6), genRand.Next(4, 8), 204);
                    }
                    for (int num868 = 0; num868 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05 / 2.0); num868++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.rockLayer, Main.maxTilesY), genRand.Next(3, 6), genRand.Next(4, 8), 22);
                    }
                }
                if (crimson)
                {
                    for (int num869 = 0; num869 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 4.25E-05); num869++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.worldSurface, (int)Main.rockLayer), genRand.Next(3, 6), genRand.Next(4, 8), 204);
                    }
                }
                else
                {
                    for (int num870 = 0; num870 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 4.25E-05); num870++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.worldSurface, (int)Main.rockLayer), genRand.Next(3, 6), genRand.Next(4, 8), 22);
                    }
                }
            }
            else
            {
                for (int num871 = 0; num871 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 6E-05); num871++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.copper = 7;
                        }
                        else
{
                            GenVars.copper = 166;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh), genRand.Next(3, 6), genRand.Next(2, 6), GenVars.copper);
                }
                for (int num872 = 0; num872 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 8E-05); num872++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.copper = 7;
                        }
                        else
{
                            GenVars.copper = 166;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), genRand.Next(3, 7), genRand.Next(3, 7), GenVars.copper);
                }
                for (int num873 = 0; num873 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0002); num873++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.copper = 7;
                        }
                        else
{
                            GenVars.copper = 166;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.copper);
                }
                for (int num874 = 0; num874 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 3E-05); num874++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.iron = 6;
                        }
                        else
{
                            GenVars.iron = 167;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh), genRand.Next(3, 7), genRand.Next(2, 5), GenVars.iron);
                }
                for (int num875 = 0; num875 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 8E-05); num875++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.iron = 6;
                        }
                        else
{
                            GenVars.iron = 167;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), genRand.Next(3, 6), genRand.Next(3, 6), GenVars.iron);
                }
                for (int num876 = 0; num876 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0002); num876++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.iron = 6;
                        }
                        else
{
                            GenVars.iron = 167;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.iron);
                }
                for (int num877 = 0; num877 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.6E-05); num877++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.silver = 9;
                        }
                        else
{
                            GenVars.silver = 168;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), genRand.Next(3, 6), genRand.Next(3, 6), GenVars.silver);
                }
                for (int num878 = 0; num878 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00015); num878++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.silver = 9;
                        }
                        else
{
                            GenVars.silver = 168;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.silver);
                }
                for (int num879 = 0; num879 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00017); num879++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.silver = 9;
                        }
                        else
{
                            GenVars.silver = 168;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next(0, (int)GenVars.worldSurfaceLow), genRand.Next(4, 9), genRand.Next(4, 8), GenVars.silver);
                }
                for (int num880 = 0; num880 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00012); num880++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.gold = 8;
                        }
                        else
{
                            GenVars.gold = 169;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), genRand.Next(4, 8), genRand.Next(4, 8), GenVars.gold);
                }
                for (int num881 = 0; num881 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00012); num881++)
                {
                    if (drunkWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            GenVars.gold = 8;
                        }
                        else
{
                            GenVars.gold = 169;
                        }
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next(0, (int)GenVars.worldSurfaceLow - 20), genRand.Next(4, 8), genRand.Next(4, 8), GenVars.gold);
                }
                if (drunkWorldGen)
                {
                    for (int num882 = 0; num882 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05 / 2.0); num882++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.rockLayer, Main.maxTilesY), genRand.Next(3, 6), genRand.Next(4, 8), 204);
                    }
                    for (int num883 = 0; num883 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05 / 2.0); num883++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.rockLayer, Main.maxTilesY), genRand.Next(3, 6), genRand.Next(4, 8), 22);
                    }
                }
                if (crimson)
                {
                    for (int num884 = 0; num884 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05); num884++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.rockLayer, Main.maxTilesY), genRand.Next(3, 6), genRand.Next(4, 8), 204);
                    }
                }
                else
                {
                    for (int num885 = 0; num885 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05); num885++)
                    {
                        TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next((int)Main.rockLayer, Main.maxTilesY), genRand.Next(3, 6), genRand.Next(4, 8), 22);
                    }
                }
            }
        });
        AddGenerationPass("Webs", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[17].Value;
            for (int num852 = 0; num852 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0006); num852++)
            {
                int num853 = genRand.Next(20, Main.maxTilesX - 20);
                int num854 = genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY - 20);
                if (num852 < GenVars.numMCaves)
                {
                    num853 = GenVars.mCaveX[num852];
                    num854 = GenVars.mCaveY[num852];
                }
                if (!Main.tile[num853, num854].active() && ((double)num854 > Main.worldSurface || Main.tile[num853, num854].wall > 0))
                {
                    while (!Main.tile[num853, num854].active() && num854 > (int)GenVars.worldSurfaceLow)
                    {
                        num854--;
                    }
                    num854++;
                    int num855 = 1;
                    if (genRand.Next(2) == 0)
                    {
                        num855 = -1;
                    }
                    for (; !Main.tile[num853, num854].active() && num853 > 10 && num853 < Main.maxTilesX - 10; num853 += num855)
                    {
                    }
                    num853 -= num855;
                    if ((double)num854 > Main.worldSurface || Main.tile[num853, num854].wall > 0)
                    {
                        TileRunner(num853, num854, genRand.Next(4, 11), genRand.Next(2, 4), 51, addTile: true, num855, -1.0, noYChange: false, overRide: false);
                    }
                }
            }
        });
        AddGenerationPass("Underworld", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[18].Value;
            progress.Set(0.0);
            int num816 = Main.maxTilesY - genRand.Next(150, 190);
            for (int num817 = 0; num817 < Main.maxTilesX; num817++)
            {
                num816 += genRand.Next(-3, 4);
                if (num816 < Main.maxTilesY - 190)
                {
                    num816 = Main.maxTilesY - 190;
                }
                if (num816 > Main.maxTilesY - 160)
                {
                    num816 = Main.maxTilesY - 160;
                }
                for (int num818 = num816 - 20 - genRand.Next(3); num818 < Main.maxTilesY; num818++)
                {
                    if (num818 >= num816)
                    {
                        Main.tile[num817, num818].active(active: false);
                        Main.tile[num817, num818].lava(lava: false);
                        Main.tile[num817, num818].liquid = 0;
                    }
                    else
                    {
                        Main.tile[num817, num818].type = 57;
                    }
                }
            }
            int num819 = Main.maxTilesY - genRand.Next(40, 70);
            for (int num820 = 10; num820 < Main.maxTilesX - 10; num820++)
            {
                num819 += genRand.Next(-10, 11);
                if (num819 > Main.maxTilesY - 60)
                {
                    num819 = Main.maxTilesY - 60;
                }
                if (num819 < Main.maxTilesY - 100)
                {
                    num819 = Main.maxTilesY - 120;
                }
                for (int num821 = num819; num821 < Main.maxTilesY - 10; num821++)
                {
                    if (!Main.tile[num820, num821].active())
                    {
                        Main.tile[num820, num821].lava(lava: true);
                        Main.tile[num820, num821].liquid = byte.MaxValue;
                    }
                }
            }
            for (int num822 = 0; num822 < Main.maxTilesX; num822++)
            {
                if (genRand.Next(50) == 0)
                {
                    int num823 = Main.maxTilesY - 65;
                    while (!Main.tile[num822, num823].active() && num823 > Main.maxTilesY - 135)
                    {
                        num823--;
                    }
                    TileRunner(genRand.Next(0, Main.maxTilesX), num823 + genRand.Next(20, 50), genRand.Next(15, 20), 1000, 57, addTile: true, 0.0, genRand.Next(1, 3), noYChange: true);
                }
            }
            Liquid.QuickWater(-2);
            for (int num824 = 0; num824 < Main.maxTilesX; num824++)
            {
                double num825 = (double)num824 / (double)(Main.maxTilesX - 1);
                progress.Set(num825 / 2.0 + 0.5);
                if (genRand.Next(13) == 0)
                {
                    int num826 = Main.maxTilesY - 65;
                    while ((Main.tile[num824, num826].liquid > 0 || Main.tile[num824, num826].active()) && num826 > Main.maxTilesY - 140)
                    {
                        num826--;
                    }
                    if ((!drunkWorldGen && !remixWorldGen) || genRand.Next(3) == 0 || !((double)num824 > (double)Main.maxTilesX * 0.4) || !((double)num824 < (double)Main.maxTilesX * 0.6))
                    {
                        TileRunner(num824, num826 - genRand.Next(2, 5), genRand.Next(5, 30), 1000, 57, addTile: true, 0.0, genRand.Next(1, 3), noYChange: true);
                    }
                    double num827 = genRand.Next(1, 3);
                    if (genRand.Next(3) == 0)
                    {
                        num827 *= 0.5;
                    }
                    if ((!drunkWorldGen && !remixWorldGen) || genRand.Next(3) == 0 || !((double)num824 > (double)Main.maxTilesX * 0.4) || !((double)num824 < (double)Main.maxTilesX * 0.6))
                    {
                        if (genRand.Next(2) == 0)
{
                            TileRunner(num824, num826 - genRand.Next(2, 5), (int)((double)genRand.Next(5, 15) * num827), (int)((double)genRand.Next(10, 15) * num827), 57, addTile: true, 1.0, 0.3);
                        }
                        if (genRand.Next(2) == 0)
{
                            num827 = genRand.Next(1, 3);
                            TileRunner(num824, num826 - genRand.Next(2, 5), (int)((double)genRand.Next(5, 15) * num827), (int)((double)genRand.Next(10, 15) * num827), 57, addTile: true, -1.0, 0.3);
                        }
                    }
                    TileRunner(num824 + genRand.Next(-10, 10), num826 + genRand.Next(-10, 10), genRand.Next(5, 15), genRand.Next(5, 10), -2, addTile: false, genRand.Next(-1, 3), genRand.Next(-1, 3));
                    if (genRand.Next(3) == 0)
                    {
                        TileRunner(num824 + genRand.Next(-10, 10), num826 + genRand.Next(-10, 10), genRand.Next(10, 30), genRand.Next(10, 20), -2, addTile: false, genRand.Next(-1, 3), genRand.Next(-1, 3));
                    }
                    if (genRand.Next(5) == 0)
                    {
                        TileRunner(num824 + genRand.Next(-15, 15), num826 + genRand.Next(-15, 10), genRand.Next(15, 30), genRand.Next(5, 20), -2, addTile: false, genRand.Next(-1, 3), genRand.Next(-1, 3));
                    }
                }
            }
            for (int num828 = 0; num828 < Main.maxTilesX; num828++)
            {
                TileRunner(genRand.Next(20, Main.maxTilesX - 20), genRand.Next(Main.maxTilesY - 180, Main.maxTilesY - 10), genRand.Next(2, 7), genRand.Next(2, 7), -2);
            }
            if (drunkWorldGen || remixWorldGen)
            {
                for (int num829 = 0; num829 < Main.maxTilesX * 2; num829++)
                {
                    TileRunner(genRand.Next((int)((double)Main.maxTilesX * 0.35), (int)((double)Main.maxTilesX * 0.65)), genRand.Next(Main.maxTilesY - 180, Main.maxTilesY - 10), genRand.Next(5, 20), genRand.Next(5, 10), -2);
                }
            }
            for (int num830 = 0; num830 < Main.maxTilesX; num830++)
            {
                if (!Main.tile[num830, Main.maxTilesY - 145].active())
                {
                    Main.tile[num830, Main.maxTilesY - 145].liquid = byte.MaxValue;
                    Main.tile[num830, Main.maxTilesY - 145].lava(lava: true);
                }
                if (!Main.tile[num830, Main.maxTilesY - 144].active())
                {
                    Main.tile[num830, Main.maxTilesY - 144].liquid = byte.MaxValue;
                    Main.tile[num830, Main.maxTilesY - 144].lava(lava: true);
                }
            }
            for (int num831 = 0; num831 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0008); num831++)
            {
                TileRunner(genRand.Next(0, Main.maxTilesX), genRand.Next(Main.maxTilesY - 140, Main.maxTilesY), genRand.Next(2, 7), genRand.Next(3, 7), 58);
            }
            if (remixWorldGen)
            {
                int num832 = (int)((double)Main.maxTilesX * 0.38);
                int num833 = (int)((double)Main.maxTilesX * 0.62);
                int num834 = num832;
                int num835 = Main.maxTilesY - 1;
                int num836 = Main.maxTilesY - 135;
                int num837 = Main.maxTilesY - 160;
                bool flag55 = false;
                Liquid.QuickWater(-2);
                for (; num835 < Main.maxTilesY - 1 || num834 < num833; num834++)
                {
                    if (!flag55)
                    {
                        num835 -= genRand.Next(1, 4);
                        if (num835 < num836)
{
                            flag55 = true;
                        }
                    }
                    else if (num834 >= num833)
                    {
                        num835 += genRand.Next(1, 4);
                        if (num835 > Main.maxTilesY - 1)
{
                            num835 = Main.maxTilesY - 1;
                        }
                    }
                    else
                    {
                        if ((num834 <= Main.maxTilesX / 2 - 5 || num834 >= Main.maxTilesX / 2 + 5) && genRand.Next(4) == 0)
{
                            if (genRand.Next(3) == 0)
{
                                num835 += genRand.Next(-1, 2);
                            }
                            else if (genRand.Next(6) == 0)
{
                                num835 += genRand.Next(-2, 3);
                            }
                            else if (genRand.Next(8) == 0)
{
                                num835 += genRand.Next(-4, 5);
                            }
                        }
                        if (num835 < num837)
{
                            num835 = num837;
                        }
                        if (num835 > num836)
{
                            num835 = num836;
                        }
                    }
                    for (int num838 = num835; num838 > num835 - 20; num838--)
                    {
                        Main.tile[num834, num838].liquid = 0;
                    }
                    for (int num839 = num835; num839 < Main.maxTilesY; num839++)
                    {
                        Main.tile[num834, num839].Clear(TileDataType.All);
                        Main.tile[num834, num839].active(active: true);
                        Main.tile[num834, num839].type = 57;
                    }
                }
                Liquid.QuickWater(-2);
                for (int num840 = num832; num840 < num833 + 15; num840++)
                {
                    for (int num841 = Main.maxTilesY - 300; num841 < num836 + 20; num841++)
                    {
                        Main.tile[num840, num841].liquid = 0;
                        if (Main.tile[num840, num841].type == 57 && Main.tile[num840, num841].active() && (!Main.tile[num840 - 1, num841 - 1].active() || !Main.tile[num840, num841 - 1].active() || !Main.tile[num840 + 1, num841 - 1].active() || !Main.tile[num840 - 1, num841].active() || !Main.tile[num840 + 1, num841].active() || !Main.tile[num840 - 1, num841 + 1].active() || !Main.tile[num840, num841 + 1].active() || !Main.tile[num840 + 1, num841 + 1].active()))
{
                            Main.tile[num840, num841].type = 633;
                        }
                    }
                }
                for (int num842 = num832; num842 < num833 + 15; num842++)
                {
                    for (int num843 = Main.maxTilesY - 200; num843 < num836 + 20; num843++)
                    {
                        if (Main.tile[num842, num843].type == 633 && Main.tile[num842, num843].active() && !Main.tile[num842, num843 - 1].active() && genRand.Next(3) == 0)
{
                            TryGrowingTreeByType(634, num842, num843);
                        }
                    }
                }
            }
            else if (!drunkWorldGen)
            {
                for (int num844 = 25; num844 < Main.maxTilesX - 25; num844++)
                {
                    if ((double)num844 < (double)Main.maxTilesX * 0.17 || (double)num844 > (double)Main.maxTilesX * 0.83)
                    {
                        for (int num845 = Main.maxTilesY - 300; num845 < Main.maxTilesY - 100 + genRand.Next(-1, 2); num845++)
{
                            if (Main.tile[num844, num845].type == 57 && Main.tile[num844, num845].active() && (!Main.tile[num844 - 1, num845 - 1].active() || !Main.tile[num844, num845 - 1].active() || !Main.tile[num844 + 1, num845 - 1].active() || !Main.tile[num844 - 1, num845].active() || !Main.tile[num844 + 1, num845].active() || !Main.tile[num844 - 1, num845 + 1].active() || !Main.tile[num844, num845 + 1].active() || !Main.tile[num844 + 1, num845 + 1].active()))
{
                                Main.tile[num844, num845].type = 633;
                            }
                        }
                    }
                }
                for (int num846 = 25; num846 < Main.maxTilesX - 25; num846++)
                {
                    if ((double)num846 < (double)Main.maxTilesX * 0.17 || (double)num846 > (double)Main.maxTilesX * 0.83)
                    {
                        for (int num847 = Main.maxTilesY - 200; num847 < Main.maxTilesY - 50; num847++)
{
                            if (Main.tile[num846, num847].type == 633 && Main.tile[num846, num847].active() && !Main.tile[num846, num847 - 1].active() && genRand.Next(3) == 0)
{
                                TryGrowingTreeByType(634, num846, num847);
                            }
                        }
                    }
                }
            }
            AddHellHouses();
            if (drunkWorldGen)
            {
                for (int num848 = 25; num848 < Main.maxTilesX - 25; num848++)
                {
                    for (int num849 = Main.maxTilesY - 300; num849 < Main.maxTilesY - 100 + genRand.Next(-1, 2); num849++)
                    {
                        if (Main.tile[num848, num849].type == 57 && Main.tile[num848, num849].active() && (!Main.tile[num848 - 1, num849 - 1].active() || !Main.tile[num848, num849 - 1].active() || !Main.tile[num848 + 1, num849 - 1].active() || !Main.tile[num848 - 1, num849].active() || !Main.tile[num848 + 1, num849].active() || !Main.tile[num848 - 1, num849 + 1].active() || !Main.tile[num848, num849 + 1].active() || !Main.tile[num848 + 1, num849 + 1].active()))
{
                            Main.tile[num848, num849].type = 633;
                        }
                    }
                }
                for (int num850 = 25; num850 < Main.maxTilesX - 25; num850++)
                {
                    for (int num851 = Main.maxTilesY - 200; num851 < Main.maxTilesY - 50; num851++)
                    {
                        if (Main.tile[num850, num851].type == 633 && Main.tile[num850, num851].active() && !Main.tile[num850, num851 - 1].active() && genRand.Next(3) == 0)
{
                            TryGrowingTreeByType(634, num850, num851);
                        }
                    }
                }
            }
        });
        AddGenerationPass("Corruption", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            int num757 = Main.maxTilesX;
            int num758 = 0;
            int num759 = Main.maxTilesX;
            int num760 = 0;
            for (int num761 = 0; num761 < Main.maxTilesX; num761++)
            {
                for (int num762 = 0; (double)num762 < Main.worldSurface; num762++)
                {
                    if (Main.tile[num761, num762].active())
                    {
                        if (Main.tile[num761, num762].type == 60)
{
                            if (num761 < num757)
{
                                num757 = num761;
                            }
                            if (num761 > num758)
{
                                num758 = num761;
                            }
                        }
                        else if (Main.tile[num761, num762].type == 147 || Main.tile[num761, num762].type == 161)
{
                            if (num761 < num759)
{
                                num759 = num761;
                            }
                            if (num761 > num760)
{
                                num760 = num761;
                            }
                        }
                    }
                }
            }
            int num763 = 10;
            num757 -= num763;
            num758 += num763;
            num759 -= num763;
            num760 += num763;
            int num764 = 500;
            int num765 = 100;
            bool flag49 = crimson;
            double num766 = (double)Main.maxTilesX * 0.00045;
            if (remixWorldGen)
            {
                num766 *= 2.0;
            }
            else if (tenthAnniversaryWorldGen)
            {
                num764 *= 2;
                num765 *= 2;
            }
            if (drunkWorldGen)
            {
                flag49 = true;
                num766 /= 2.0;
            }
            if (flag49)
            {
                progress.Message = Lang.gen[72].Value;
                for (int num767 = 0; (double)num767 < num766; num767++)
                {
                    int num768 = num759;
                    int num769 = num760;
                    int num770 = num757;
                    int num771 = num758;
                    double value15 = (double)num767 / num766;
                    progress.Set(value15);
                    bool flag50 = false;
                    int num772 = 0;
                    int num773 = 0;
                    int num774 = 0;
                    while (!flag50)
                    {
                        flag50 = true;
                        int num775 = Main.maxTilesX / 2;
                        int num776 = 200;
                        if (drunkWorldGen)
{
                            num776 = 100;
                            num772 = ((!GenVars.crimsonLeft) ? genRand.Next((int)((double)Main.maxTilesX * 0.5), Main.maxTilesX - num764) : genRand.Next(num764, (int)((double)Main.maxTilesX * 0.5)));
                        }
                        else
{
                            num772 = genRand.Next(num764, Main.maxTilesX - num764);
                        }
                        num773 = num772 - genRand.Next(200) - 100;
                        num774 = num772 + genRand.Next(200) + 100;
                        if (num773 < GenVars.evilBiomeBeachAvoidance)
{
                            num773 = GenVars.evilBiomeBeachAvoidance;
                        }
                        if (num774 > Main.maxTilesX - GenVars.evilBiomeBeachAvoidance)
{
                            num774 = Main.maxTilesX - GenVars.evilBiomeBeachAvoidance;
                        }
                        if (num772 < num773 + GenVars.evilBiomeAvoidanceMidFixer)
{
                            num772 = num773 + GenVars.evilBiomeAvoidanceMidFixer;
                        }
                        if (num772 > num774 - GenVars.evilBiomeAvoidanceMidFixer)
{
                            num772 = num774 - GenVars.evilBiomeAvoidanceMidFixer;
                        }
                        if (GenVars.dungeonSide < 0 && num773 < 400)
{
                            num773 = 400;
                        }
                        else if (GenVars.dungeonSide > 0 && num773 > Main.maxTilesX - 400)
{
                            num773 = Main.maxTilesX - 400;
                        }
                        if (num773 < GenVars.dungeonLocation + num765 && num774 > GenVars.dungeonLocation - num765)
{
                            flag50 = false;
                        }
                        if (!remixWorldGen)
{
                            if (!tenthAnniversaryWorldGen)
{
                                if (num772 > num775 - num776 && num772 < num775 + num776)
{
                                    flag50 = false;
                                }
                                if (num773 > num775 - num776 && num773 < num775 + num776)
{
                                    flag50 = false;
                                }
                                if (num774 > num775 - num776 && num774 < num775 + num776)
{
                                    flag50 = false;
                                }
                            }
                            if (num772 > GenVars.UndergroundDesertLocation.X && num772 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                flag50 = false;
                            }
                            if (num773 > GenVars.UndergroundDesertLocation.X && num773 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                flag50 = false;
                            }
                            if (num774 > GenVars.UndergroundDesertLocation.X && num774 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                flag50 = false;
                            }
                            if (num773 < num769 && num774 > num768)
{
                                num768++;
                                num769--;
                                flag50 = false;
                            }
                            if (num773 < num771 && num774 > num770)
{
                                num770++;
                                num771--;
                                flag50 = false;
                            }
                        }
                    }
                    CrimStart(num772, (int)GenVars.worldSurfaceLow - 10);
                    for (int num777 = num773; num777 < num774; num777++)
                    {
                        for (int num778 = (int)GenVars.worldSurfaceLow; (double)num778 < Main.worldSurface - 1.0; num778++)
{
                            if (Main.tile[num777, num778].active())
{
                                int num779 = num778 + genRand.Next(10, 14);
                                for (int num780 = num778; num780 < num779; num780++)
{
                                    if (Main.tile[num777, num780].type == 60 && num777 >= num773 + genRand.Next(5) && num777 < num774 - genRand.Next(5))
{
                                        Main.tile[num777, num780].type = 662;
                                    }
                                }
                                break;
                            }
                        }
                    }
                    double num781 = Main.worldSurface + 40.0;
                    for (int num782 = num773; num782 < num774; num782++)
                    {
                        num781 += (double)genRand.Next(-2, 3);
                        if (num781 < Main.worldSurface + 30.0)
{
                            num781 = Main.worldSurface + 30.0;
                        }
                        if (num781 > Main.worldSurface + 50.0)
{
                            num781 = Main.worldSurface + 50.0;
                        }
                        bool flag51 = false;
                        for (int num783 = (int)GenVars.worldSurfaceLow; (double)num783 < num781; num783++)
{
                            if (Main.tile[num782, num783].active())
{
                                if (Main.tile[num782, num783].type == 53 && num782 >= num773 + genRand.Next(5) && num782 <= num774 - genRand.Next(5))
{
                                    Main.tile[num782, num783].type = 234;
                                }
                                if ((double)num783 < Main.worldSurface - 1.0 && !flag51)
{
                                    if (Main.tile[num782, num783].type == 0)
{
                                        grassSpread = 0;
                                        SpreadGrass(num782, num783, 0, 199);
                                    }
                                    else if (Main.tile[num782, num783].type == 59)
{
                                        grassSpread = 0;
                                        SpreadGrass(num782, num783, 59, 662);
                                    }
                                }
                                flag51 = true;
                                if (Main.tile[num782, num783].wall == 216)
{
                                    Main.tile[num782, num783].wall = 218;
                                }
                                else if (Main.tile[num782, num783].wall == 187)
{
                                    Main.tile[num782, num783].wall = 221;
                                }
                                if (Main.tile[num782, num783].type == 1)
{
                                    if (num782 >= num773 + genRand.Next(5) && num782 <= num774 - genRand.Next(5))
{
                                        Main.tile[num782, num783].type = 203;
                                    }
                                }
                                else if (Main.tile[num782, num783].type == 2)
{
                                    Main.tile[num782, num783].type = 199;
                                }
                                else if (Main.tile[num782, num783].type == 60)
{
                                    Main.tile[num782, num783].type = 662;
                                }
                                else if (Main.tile[num782, num783].type == 161)
{
                                    Main.tile[num782, num783].type = 200;
                                }
                                else if (Main.tile[num782, num783].type == 396)
{
                                    Main.tile[num782, num783].type = 401;
                                }
                                else if (Main.tile[num782, num783].type == 397)
{
                                    Main.tile[num782, num783].type = 399;
                                }
                            }
                        }
                    }
                    int num784 = genRand.Next(10, 15);
                    for (int num785 = 0; num785 < num784; num785++)
                    {
                        int num786 = 0;
                        bool flag52 = false;
                        int num787 = 0;
                        while (!flag52)
{
                            num786++;
                            int x28 = genRand.Next(num773 - num787, num774 + num787);
                            int num788 = genRand.Next((int)(Main.worldSurface - (double)(num787 / 2)), (int)(Main.worldSurface + 100.0 + (double)num787));
                            while (oceanDepths(x28, num788))
{
                                x28 = genRand.Next(num773 - num787, num774 + num787);
                                num788 = genRand.Next((int)(Main.worldSurface - (double)(num787 / 2)), (int)(Main.worldSurface + 100.0 + (double)num787));
                            }
                            if (num786 > 100)
{
                                num787++;
                                num786 = 0;
                            }
                            if (!Main.tile[x28, num788].active())
{
                                for (; !Main.tile[x28, num788].active(); num788++)
{
                                }
                                num788--;
                            }
                            else
{
                                while (Main.tile[x28, num788].active() && (double)num788 > Main.worldSurface)
{
                                    num788--;
                                }
                            }
                            if ((num787 > 10 || (Main.tile[x28, num788 + 1].active() && Main.tile[x28, num788 + 1].type == 203)) && !IsTileNearby(x28, num788, 26, 3))
{
                                Place3x2(x28, num788, 26, 1);
                                if (Main.tile[x28, num788].type == 26)
{
                                    flag52 = true;
                                }
                            }
                            if (num787 > 100)
{
                                flag52 = true;
                            }
                        }
                    }
                }
                CrimPlaceHearts();
            }
            if (drunkWorldGen)
            {
                flag49 = false;
            }
            if (!flag49)
            {
                progress.Message = Lang.gen[20].Value;
                for (int num789 = 0; (double)num789 < num766; num789++)
                {
                    int num790 = num759;
                    int num791 = num760;
                    int num792 = num757;
                    int num793 = num758;
                    double value16 = (double)num789 / num766;
                    progress.Set(value16);
                    bool flag53 = false;
                    int num794 = 0;
                    int num795 = 0;
                    int num796 = 0;
                    while (!flag53)
                    {
                        flag53 = true;
                        int num797 = Main.maxTilesX / 2;
                        int num798 = 200;
                        num794 = ((!drunkWorldGen) ? genRand.Next(num764, Main.maxTilesX - num764) : (GenVars.crimsonLeft ? genRand.Next((int)((double)Main.maxTilesX * 0.5), Main.maxTilesX - num764) : genRand.Next(num764, (int)((double)Main.maxTilesX * 0.5))));
                        num795 = num794 - genRand.Next(200) - 100;
                        num796 = num794 + genRand.Next(200) + 100;
                        if (num795 < GenVars.evilBiomeBeachAvoidance)
{
                            num795 = GenVars.evilBiomeBeachAvoidance;
                        }
                        if (num796 > Main.maxTilesX - GenVars.evilBiomeBeachAvoidance)
{
                            num796 = Main.maxTilesX - GenVars.evilBiomeBeachAvoidance;
                        }
                        if (num794 < num795 + GenVars.evilBiomeAvoidanceMidFixer)
{
                            num794 = num795 + GenVars.evilBiomeAvoidanceMidFixer;
                        }
                        if (num794 > num796 - GenVars.evilBiomeAvoidanceMidFixer)
{
                            num794 = num796 - GenVars.evilBiomeAvoidanceMidFixer;
                        }
                        if (num795 < GenVars.dungeonLocation + num765 && num796 > GenVars.dungeonLocation - num765)
{
                            flag53 = false;
                        }
                        if (!remixWorldGen)
{
                            if (!tenthAnniversaryWorldGen)
{
                                if (num794 > num797 - num798 && num794 < num797 + num798)
{
                                    flag53 = false;
                                }
                                if (num795 > num797 - num798 && num795 < num797 + num798)
{
                                    flag53 = false;
                                }
                                if (num796 > num797 - num798 && num796 < num797 + num798)
{
                                    flag53 = false;
                                }
                            }
                            if (num794 > GenVars.UndergroundDesertLocation.X && num794 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                flag53 = false;
                            }
                            if (num795 > GenVars.UndergroundDesertLocation.X && num795 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                flag53 = false;
                            }
                            if (num796 > GenVars.UndergroundDesertLocation.X && num796 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                flag53 = false;
                            }
                            if (num795 < num791 && num796 > num790)
{
                                num790++;
                                num791--;
                                flag53 = false;
                            }
                            if (num795 < num793 && num796 > num792)
{
                                num792++;
                                num793--;
                                flag53 = false;
                            }
                        }
                    }
                    int num799 = 0;
                    for (int num800 = num795; num800 < num796; num800++)
                    {
                        if (num799 > 0)
{
                            num799--;
                        }
                        if (num800 == num794 || num799 == 0)
{
                            for (int num801 = (int)GenVars.worldSurfaceLow; (double)num801 < Main.worldSurface - 1.0; num801++)
{
                                if (Main.tile[num800, num801].active() || Main.tile[num800, num801].wall > 0)
{
                                    if (num800 == num794)
{
                                        num799 = 20;
                                        ChasmRunner(num800, num801, genRand.Next(150) + 150, makeOrb: true);
                                    }
                                    else if (genRand.Next(35) == 0 && num799 == 0)
{
                                        num799 = 30;
                                        bool makeOrb = true;
                                        ChasmRunner(num800, num801, genRand.Next(50) + 50, makeOrb);
                                    }
                                    break;
                                }
                            }
                        }
                        for (int num802 = (int)GenVars.worldSurfaceLow; (double)num802 < Main.worldSurface - 1.0; num802++)
{
                            if (Main.tile[num800, num802].active())
{
                                int num803 = num802 + genRand.Next(10, 14);
                                for (int num804 = num802; num804 < num803; num804++)
{
                                    if (Main.tile[num800, num804].type == 60 && num800 >= num795 + genRand.Next(5) && num800 < num796 - genRand.Next(5))
{
                                        Main.tile[num800, num804].type = 661;
                                    }
                                }
                                break;
                            }
                        }
                    }
                    double num805 = Main.worldSurface + 40.0;
                    for (int num806 = num795; num806 < num796; num806++)
                    {
                        num805 += (double)genRand.Next(-2, 3);
                        if (num805 < Main.worldSurface + 30.0)
{
                            num805 = Main.worldSurface + 30.0;
                        }
                        if (num805 > Main.worldSurface + 50.0)
{
                            num805 = Main.worldSurface + 50.0;
                        }
                        bool flag54 = false;
                        for (int num807 = (int)GenVars.worldSurfaceLow; (double)num807 < num805; num807++)
{
                            if (Main.tile[num806, num807].active())
{
                                if (Main.tile[num806, num807].type == 53 && num806 >= num795 + genRand.Next(5) && num806 <= num796 - genRand.Next(5))
{
                                    Main.tile[num806, num807].type = 112;
                                }
                                if ((double)num807 < Main.worldSurface - 1.0 && !flag54)
{
                                    if (Main.tile[num806, num807].type == 0)
{
                                        grassSpread = 0;
                                        SpreadGrass(num806, num807, 0, 23);
                                    }
                                    else if (Main.tile[num806, num807].type == 59)
{
                                        grassSpread = 0;
                                        SpreadGrass(num806, num807, 59, 661);
                                    }
                                }
                                flag54 = true;
                                if (Main.tile[num806, num807].wall == 216)
{
                                    Main.tile[num806, num807].wall = 217;
                                }
                                else if (Main.tile[num806, num807].wall == 187)
{
                                    Main.tile[num806, num807].wall = 220;
                                }
                                if (Main.tile[num806, num807].type == 1)
{
                                    if (num806 >= num795 + genRand.Next(5) && num806 <= num796 - genRand.Next(5))
{
                                        Main.tile[num806, num807].type = 25;
                                    }
                                }
                                else if (Main.tile[num806, num807].type == 2)
{
                                    Main.tile[num806, num807].type = 23;
                                }
                                else if (Main.tile[num806, num807].type == 60)
{
                                    Main.tile[num806, num807].type = 661;
                                }
                                else if (Main.tile[num806, num807].type == 161)
{
                                    Main.tile[num806, num807].type = 163;
                                }
                                else if (Main.tile[num806, num807].type == 396)
{
                                    Main.tile[num806, num807].type = 400;
                                }
                                else if (Main.tile[num806, num807].type == 397)
{
                                    Main.tile[num806, num807].type = 398;
                                }
                            }
                        }
                    }
                    for (int num808 = num795; num808 < num796; num808++)
                    {
                        for (int num809 = 0; num809 < Main.maxTilesY - 50; num809++)
{
                            if (Main.tile[num808, num809].active() && Main.tile[num808, num809].type == 31)
{
                                int num810 = num808 - 13;
                                int num811 = num808 + 13;
                                int num812 = num809 - 13;
                                int num813 = num809 + 13;
                                for (int num814 = num810; num814 < num811; num814++)
{
                                    if (num814 > 10 && num814 < Main.maxTilesX - 10)
{
                                        for (int num815 = num812; num815 < num813; num815++)
{
                                            if (Math.Abs(num814 - num808) + Math.Abs(num815 - num809) < 9 + genRand.Next(11) && genRand.Next(3) != 0 && Main.tile[num814, num815].type != 31)
{
                                                Main.tile[num814, num815].active(active: true);
                                                Main.tile[num814, num815].type = 25;
                                                if (Math.Abs(num814 - num808) <= 1 && Math.Abs(num815 - num809) <= 1)
{
                                                    Main.tile[num814, num815].active(active: false);
                                                }
                                            }
                                            if (Main.tile[num814, num815].type != 31 && Math.Abs(num814 - num808) <= 2 + genRand.Next(3) && Math.Abs(num815 - num809) <= 2 + genRand.Next(3))
{
                                                Main.tile[num814, num815].active(active: false);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Lakes", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_03d2: Unknown result type (might be due to invalid IL or missing references)
            progress.Message = Lang.gen[19].Value;
            double num739 = (double)Main.maxTilesX / 4200.0;
            int num740 = genRand.Next((int)(num739 * 3.0), (int)(num739 * 6.0));
            for (int num741 = 0; num741 < num740; num741++)
            {
                int num742 = Main.maxTilesX / 4;
                if (GenVars.numLakes >= GenVars.maxLakes - 1)
                {
                    break;
                }
                double value14 = (double)num741 / (double)num740;
                progress.Set(value14);
                while (num742 > 0)
                {
                    bool flag48 = false;
                    num742--;
                    int num743 = genRand.Next(GenVars.lakesBeachAvoidance, Main.maxTilesX - GenVars.lakesBeachAvoidance);
                    if (tenthAnniversaryWorldGen && !remixWorldGen)
                    {
                        num743 = genRand.Next((int)((double)Main.maxTilesX * 0.15), (int)((double)Main.maxTilesX * 0.85));
                    }
                    else
                    {
                        while ((double)num743 > (double)Main.maxTilesX * 0.45 && (double)num743 < (double)Main.maxTilesX * 0.55)
{
                            num743 = genRand.Next(GenVars.lakesBeachAvoidance, Main.maxTilesX - GenVars.lakesBeachAvoidance);
                        }
                    }
                    for (int num744 = 0; num744 < GenVars.numLakes; num744++)
                    {
                        if (Math.Abs(num743 - GenVars.LakeX[num744]) < 150)
{
                            flag48 = true;
                            break;
                        }
                    }
                    for (int num745 = 0; num745 < GenVars.numMCaves; num745++)
                    {
                        if (Math.Abs(num743 - GenVars.mCaveX[num745]) < 100)
{
                            flag48 = true;
                            break;
                        }
                    }
                    for (int num746 = 0; num746 < GenVars.numTunnels; num746++)
                    {
                        if (Math.Abs(num743 - GenVars.tunnelX[num746]) < 100)
{
                            flag48 = true;
                            break;
                        }
                    }
                    if (!flag48)
                    {
                        int num747 = (int)GenVars.worldSurfaceLow - 20;
                        while (!Main.tile[num743, num747].active())
{
                            num747++;
                            if ((double)num747 >= Main.worldSurface || Main.tile[num743, num747].wall > 0)
{
                                flag48 = true;
                                break;
                            }
                        }
                        if (Main.tile[num743, num747].type == 53)
{
                            flag48 = true;
                        }
                        if (!flag48)
{
                            int num748 = 50;
                            for (int num749 = num743 - num748; num749 <= num743 + num748; num749++)
{
                                for (int num750 = num747 - num748; num750 <= num747 + num748; num750++)
{
                                    if (Main.tile[num749, num750].type == 203 || Main.tile[num749, num750].type == 25)
{
                                        flag48 = true;
                                        break;
                                    }
                                }
                            }
                            if (!flag48)
{
                                int num751 = num747;
                                num748 = 20;
                                while (!SolidTile(num743 - num748, num747) || !SolidTile(num743 + num748, num747))
{
                                    num747++;
                                    if ((double)num747 > Main.worldSurface - 50.0)
{
                                        flag48 = true;
                                    }
                                }
                                if (num747 - num751 <= 10)
{
                                    num748 = 60;
                                    for (int num752 = num743 - num748; num752 <= num743 + num748; num752++)
{
                                        int y23 = num747 - 20;
                                        if (Main.tile[num752, y23].active() || Main.tile[num752, y23].wall > 0)
{
                                            flag48 = true;
                                        }
                                    }
                                    if (!flag48)
{
                                        int num753 = 0;
                                        for (int num754 = num743 - num748; num754 <= num743 + num748; num754++)
{
                                            for (int num755 = num747; num755 <= num747 + num748 * 2; num755++)
{
                                                if (SolidTile(num754, num755))
{
                                                    num753++;
                                                }
                                            }
                                        }
                                        int num756 = (num748 * 2 + 1) * (num748 * 2 + 1);
                                        if (!((double)num753 < (double)num756 * 0.8) && !((Rectangle)(ref GenVars.UndergroundDesertLocation)).Intersects(new Rectangle(num743 - 8, num747 - 8, 16, 16)))
{
                                            SonOfLakinater(num743, num747);
                                            GenVars.LakeX[GenVars.numLakes] = num743;
                                            GenVars.numLakes++;
                                            break;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Dungeon", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            int dungeonLocation = GenVars.dungeonLocation;
            int num735 = (int)((Main.worldSurface + Main.rockLayer) / 2.0) + genRand.Next(-200, 200);
            int num736 = (int)((Main.worldSurface + Main.rockLayer) / 2.0) + 200;
            int num737 = num735;
            bool flag47 = false;
            for (int num738 = 0; num738 < 10; num738++)
            {
                if (SolidTile(dungeonLocation, num737 + num738))
                {
                    flag47 = true;
                    break;
                }
            }
            if (!flag47)
            {
                for (; num737 < num736 && !SolidTile(dungeonLocation, num737 + 10); num737++)
                {
                }
            }
            if (drunkWorldGen)
            {
                num737 = (int)Main.worldSurface + 70;
            }
            MakeDungeon(dungeonLocation, num737);
        });
        AddGenerationPass("Slush", delegate
        {
            for (int num730 = GenVars.snowTop; num730 < GenVars.snowBottom; num730++)
            {
                for (int num731 = GenVars.snowMinX[num730]; num731 < GenVars.snowMaxX[num730]; num731++)
                {
                    switch (Main.tile[num731, num730].type)
                    {
                    case 123:
                        Main.tile[num731, num730].type = 224;
                        break;
                    case 59:
                    {
                        bool flag46 = true;
                        int num732 = 3;
                        for (int num733 = num731 - num732; num733 <= num731 + num732; num733++)
{
                            for (int num734 = num730 - num732; num734 <= num730 + num732; num734++)
{
                                if (Main.tile[num733, num734].type == 60 || Main.tile[num733, num734].type == 70 || Main.tile[num733, num734].type == 71 || Main.tile[num733, num734].type == 72)
{
                                    flag46 = false;
                                    break;
                                }
                            }
                        }
                        if (flag46)
{
                            Main.tile[num731, num730].type = 224;
                        }
                        break;
                    }
                    case 1:
                        Main.tile[num731, num730].type = 161;
                        break;
                    }
                }
            }
        });
        AddGenerationPass("Mountain Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[21].Value;
            for (int num729 = 0; num729 < GenVars.numMCaves; num729++)
            {
                int i3 = GenVars.mCaveX[num729];
                int j5 = GenVars.mCaveY[num729];
                CaveOpenater(i3, j5);
                Cavinator(i3, j5, genRand.Next(40, 50));
            }
        });
        AddGenerationPass("Beaches", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            int num711 = 50;
            progress.Message = Lang.gen[22].Value;
            bool floridaStyle = false;
            bool floridaStyle2 = false;
            if (genRand.Next(4) == 0)
            {
                if (genRand.Next(2) == 0)
                {
                    floridaStyle = true;
                }
                else
                {
                    floridaStyle2 = true;
                }
            }
            for (int num712 = 0; num712 < 2; num712++)
            {
                int num713 = 0;
                int num714 = 0;
                if (num712 == 0)
                {
                    num713 = 0;
                    num714 = genRand.Next(GenVars.oceanWaterStartRandomMin, GenVars.oceanWaterStartRandomMax);
                    if (GenVars.dungeonSide == 1)
                    {
                        num714 = GenVars.oceanWaterForcedJungleLength;
                    }
                    int num715 = GenVars.leftBeachEnd - num711;
                    if (num714 > num715)
                    {
                        num714 = num715;
                    }
                    int num716 = 0;
                    double num717 = 1.0;
                    int num718;
                    for (num718 = 0; !Main.tile[num714 - 1, num718].active(); num718++)
                    {
                    }
                    GenVars.shellStartYLeft = num718;
                    num718 += genRand.Next(1, 5);
                    for (int num719 = num714 - 1; num719 >= num713; num719--)
                    {
                        if (num719 > 30)
{
                            num716++;
                            num717 = TuneOceanDepth(num716, num717, floridaStyle);
                        }
                        else
{
                            num717 += 1.0;
                        }
                        int num720 = genRand.Next(15, 20);
                        for (int num721 = 0; (double)num721 < (double)num718 + num717 + (double)num720; num721++)
{
                            if ((double)num721 < (double)num718 + num717 * 0.75 - 3.0)
{
                                Main.tile[num719, num721].active(active: false);
                                if (num721 > num718)
{
                                    Main.tile[num719, num721].liquid = byte.MaxValue;
                                    Main.tile[num719, num721].lava(lava: false);
                                }
                                else if (num721 == num718)
{
                                    Main.tile[num719, num721].liquid = 127;
                                    if (GenVars.shellStartXLeft == 0)
{
                                        GenVars.shellStartXLeft = num719;
                                    }
                                }
                            }
                            else if (num721 > num718)
{
                                Main.tile[num719, num721].type = 53;
                                Main.tile[num719, num721].active(active: true);
                            }
                            Main.tile[num719, num721].wall = 0;
                        }
                    }
                }
                else
                {
                    num713 = Main.maxTilesX - genRand.Next(GenVars.oceanWaterStartRandomMin, GenVars.oceanWaterStartRandomMax);
                    num714 = Main.maxTilesX;
                    if (GenVars.dungeonSide == -1)
                    {
                        num713 = Main.maxTilesX - GenVars.oceanWaterForcedJungleLength;
                    }
                    int num722 = GenVars.rightBeachStart + num711;
                    if (num713 < num722)
                    {
                        num713 = num722;
                    }
                    double num723 = 1.0;
                    int num724 = 0;
                    int num725;
                    for (num725 = 0; !Main.tile[num713, num725].active(); num725++)
                    {
                    }
                    GenVars.shellStartXRight = 0;
                    GenVars.shellStartYRight = num725;
                    num725 += genRand.Next(1, 5);
                    for (int num726 = num713; num726 < num714; num726++)
                    {
                        if (num726 < num714 - 30)
{
                            num724++;
                            num723 = TuneOceanDepth(num724, num723, floridaStyle2);
                        }
                        else
{
                            num723 += 1.0;
                        }
                        int num727 = genRand.Next(15, 20);
                        for (int num728 = 0; (double)num728 < (double)num725 + num723 + (double)num727; num728++)
{
                            if ((double)num728 < (double)num725 + num723 * 0.75 - 3.0)
{
                                Main.tile[num726, num728].active(active: false);
                                if (num728 > num725)
{
                                    Main.tile[num726, num728].liquid = byte.MaxValue;
                                    Main.tile[num726, num728].lava(lava: false);
                                }
                                else if (num728 == num725)
{
                                    Main.tile[num726, num728].liquid = 127;
                                    if (GenVars.shellStartXRight == 0)
{
                                        GenVars.shellStartXRight = num726;
                                    }
                                }
                            }
                            else if (num728 > num725)
{
                                Main.tile[num726, num728].type = 53;
                                Main.tile[num726, num728].active(active: true);
                            }
                            Main.tile[num726, num728].wall = 0;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Gems", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[23].Value;
            Main.tileSolid[484] = false;
            for (int num699 = 63; num699 <= 68; num699++)
            {
                double value13 = (double)(num699 - 63) / 6.0;
                progress.Set(value13);
                double num700 = 0.0;
                switch (num699)
                {
                case 67:
                    num700 = (double)Main.maxTilesX * 0.5;
                    break;
                case 66:
                    num700 = (double)Main.maxTilesX * 0.45;
                    break;
                case 63:
                    num700 = (double)Main.maxTilesX * 0.3;
                    break;
                case 65:
                    num700 = (double)Main.maxTilesX * 0.25;
                    break;
                case 64:
                    num700 = (double)Main.maxTilesX * 0.1;
                    break;
                case 68:
                    num700 = (double)Main.maxTilesX * 0.05;
                    break;
                }
                num700 *= 0.2;
                for (int num701 = 0; (double)num701 < num700; num701++)
                {
                    int num702 = genRand.Next(0, Main.maxTilesX);
                    int num703 = genRand.Next((int)Main.worldSurface, Main.maxTilesY);
                    while (Main.tile[num702, num703].type != 1)
                    {
                        num702 = genRand.Next(0, Main.maxTilesX);
                        num703 = genRand.Next((int)Main.worldSurface, Main.maxTilesY);
                    }
                    TileRunner(num702, num703, genRand.Next(2, 6), genRand.Next(3, 7), num699);
                }
            }
            for (int num704 = 0; num704 < 2; num704++)
            {
                int num705 = 1;
                int num706 = 5;
                int num707 = Main.maxTilesX - 5;
                if (num704 == 1)
                {
                    num705 = -1;
                    num706 = Main.maxTilesX - 5;
                    num707 = 5;
                }
                for (int num708 = num706; num708 != num707; num708 += num705)
                {
                    if (num708 <= ((Rectangle)(ref GenVars.UndergroundDesertLocation)).Left || num708 >= ((Rectangle)(ref GenVars.UndergroundDesertLocation)).Right)
                    {
                        for (int num709 = 10; num709 < Main.maxTilesY - 10; num709++)
{
                            if (Main.tile[num708, num709].active() && Main.tile[num708, num709 + 1].active() && Main.tileSand[Main.tile[num708, num709].type] && Main.tileSand[Main.tile[num708, num709 + 1].type])
{
                                ushort type8 = Main.tile[num708, num709].type;
                                int x27 = num708 + num705;
                                int num710 = num709 + 1;
                                if (!Main.tile[x27, num709].active() && !Main.tile[x27, num710].active())
{
                                    for (; !Main.tile[x27, num710].active(); num710++)
{
                                    }
                                    num710--;
                                    Main.tile[num708, num709].active(active: false);
                                    Main.tile[x27, num710].active(active: true);
                                    Main.tile[x27, num710].type = type8;
                                }
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Gravitating Sand", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[24].Value;
            for (int num695 = 0; num695 < Main.maxTilesX; num695++)
            {
                double value12 = (double)num695 / (double)(Main.maxTilesX - 1);
                progress.Set(value12);
                bool flag45 = false;
                int num696 = 0;
                for (int num697 = Main.maxTilesY - 1; num697 > 0; num697--)
                {
                    if (SolidOrSlopedTile(num695, num697))
                    {
                        ushort type7 = Main.tile[num695, num697].type;
                        if (flag45 && num697 < (int)Main.worldSurface && num697 != num696 - 1 && TileID.Sets.Falling[type7])
{
                            for (int num698 = num697; num698 < num696; num698++)
{
                                Main.tile[num695, num698].ResetToType(type7);
                            }
                        }
                        flag45 = true;
                        num696 = num697;
                    }
                }
            }
        });
        AddGenerationPass("Create Ocean Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            int maxValue11 = 3;
            if (remixWorldGen)
            {
                maxValue11 = 2;
            }
            for (int num692 = 0; num692 < 2; num692++)
            {
                if ((num692 != 0 || GenVars.dungeonSide <= 0) && (num692 != 1 || GenVars.dungeonSide >= 0) && (genRand.Next(maxValue11) == 0 || drunkWorldGen || tenthAnniversaryWorldGen))
                {
                    progress.Message = Lang.gen[90].Value;
                    int num693 = genRand.Next(55, 95);
                    if (num692 == 1)
                    {
                        num693 = genRand.Next(Main.maxTilesX - 95, Main.maxTilesX - 55);
                    }
                    int num694;
                    for (num694 = 0; !Main.tile[num693, num694].active(); num694++)
                    {
                    }
                    oceanCave(num693, num694);
                }
            }
        });
        AddGenerationPass("Shimmer", delegate
        {
            //IL_02a6: Unknown result type (might be due to invalid IL or missing references)
            int num683 = 50;
            int num684 = (int)(Main.worldSurface + Main.rockLayer) / 2 + num683;
            int num685 = (int)((double)((Main.maxTilesY - 250) * 2) + Main.rockLayer) / 3;
            if (num685 > Main.maxTilesY - 330 - 100 - 30)
            {
                num685 = Main.maxTilesY - 330 - 100 - 30;
            }
            if (num685 <= num684)
            {
                num685 = num684 + 50;
            }
            int num686 = genRand.Next(num684, num685);
            int num687 = ((GenVars.dungeonSide < 0) ? genRand.Next((int)((double)Main.maxTilesX * 0.89), Main.maxTilesX - 200) : genRand.Next(200, (int)((double)Main.maxTilesX * 0.11)));
            int num688 = (int)Main.worldSurface + 150;
            int num689 = (int)(Main.rockLayer + Main.worldSurface + 200.0) / 2;
            if (num689 <= num688)
            {
                num689 = num688 + 50;
            }
            if (tenthAnniversaryWorldGen)
            {
                num686 = genRand.Next(num688, num689);
            }
            int num690 = 0;
            while (!ShimmerMakeBiome(num687, num686))
            {
                num690++;
                if (tenthAnniversaryWorldGen && num690 < 10000)
                {
                    num686 = genRand.Next(num688, num689);
                    num687 = ((GenVars.dungeonSide < 0) ? genRand.Next((int)((double)Main.maxTilesX * 0.89), Main.maxTilesX - 200) : genRand.Next(200, (int)((double)Main.maxTilesX * 0.11)));
                }
                else if (num690 > 20000)
                {
                    num686 = genRand.Next((int)Main.worldSurface + 100 + 20, num685);
                    num687 = ((GenVars.dungeonSide < 0) ? genRand.Next((int)((double)Main.maxTilesX * 0.8), Main.maxTilesX - 200) : genRand.Next(200, (int)((double)Main.maxTilesX * 0.2)));
                }
                else
                {
                    num686 = genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2 + 20, num685);
                    num687 = ((GenVars.dungeonSide < 0) ? genRand.Next((int)((double)Main.maxTilesX * 0.89), Main.maxTilesX - 200) : genRand.Next(200, (int)((double)Main.maxTilesX * 0.11)));
                }
            }
            GenVars.shimmerPosition = new Vector2D(num687, num686);
            int num691 = 200;
            GenVars.structures.AddProtectedStructure(new Rectangle(num687 - num691 / 2, num686 - num691 / 2, num691, num691));
        });
        AddGenerationPass("Clean Up Dirt", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[25].Value;
            for (int num677 = 3; num677 < Main.maxTilesX - 3; num677++)
            {
                double num678 = (double)num677 / (double)Main.maxTilesX;
                progress.Set(0.5 * num678);
                bool flag43 = true;
                for (int num679 = 0; (double)num679 < Main.worldSurface; num679++)
                {
                    if (flag43)
                    {
                        if (Main.tile[num677, num679].wall == 2 || Main.tile[num677, num679].wall == 40 || Main.tile[num677, num679].wall == 64 || Main.tile[num677, num679].wall == 86)
{
                            Main.tile[num677, num679].wall = 0;
                        }
                        if (Main.tile[num677, num679].type != 53 && Main.tile[num677, num679].type != 112 && Main.tile[num677, num679].type != 234)
{
                            if (Main.tile[num677 - 1, num679].wall == 2 || Main.tile[num677 - 1, num679].wall == 40 || Main.tile[num677 - 1, num679].wall == 40)
{
                                Main.tile[num677 - 1, num679].wall = 0;
                            }
                            if ((Main.tile[num677 - 2, num679].wall == 2 || Main.tile[num677 - 2, num679].wall == 40 || Main.tile[num677 - 2, num679].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num677 - 2, num679].wall = 0;
                            }
                            if ((Main.tile[num677 - 3, num679].wall == 2 || Main.tile[num677 - 3, num679].wall == 40 || Main.tile[num677 - 3, num679].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num677 - 3, num679].wall = 0;
                            }
                            if (Main.tile[num677 + 1, num679].wall == 2 || Main.tile[num677 + 1, num679].wall == 40 || Main.tile[num677 + 1, num679].wall == 40)
{
                                Main.tile[num677 + 1, num679].wall = 0;
                            }
                            if ((Main.tile[num677 + 2, num679].wall == 2 || Main.tile[num677 + 2, num679].wall == 40 || Main.tile[num677 + 2, num679].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num677 + 2, num679].wall = 0;
                            }
                            if ((Main.tile[num677 + 3, num679].wall == 2 || Main.tile[num677 + 3, num679].wall == 40 || Main.tile[num677 + 3, num679].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num677 + 3, num679].wall = 0;
                            }
                            if (Main.tile[num677, num679].active())
{
                                flag43 = false;
                            }
                        }
                    }
                    else if (Main.tile[num677, num679].wall == 0 && Main.tile[num677, num679 + 1].wall == 0 && Main.tile[num677, num679 + 2].wall == 0 && Main.tile[num677, num679 + 3].wall == 0 && Main.tile[num677, num679 + 4].wall == 0 && Main.tile[num677 - 1, num679].wall == 0 && Main.tile[num677 + 1, num679].wall == 0 && Main.tile[num677 - 2, num679].wall == 0 && Main.tile[num677 + 2, num679].wall == 0 && !Main.tile[num677, num679].active() && !Main.tile[num677, num679 + 1].active() && !Main.tile[num677, num679 + 2].active() && !Main.tile[num677, num679 + 3].active())
                    {
                        flag43 = true;
                    }
                }
            }
            for (int num680 = Main.maxTilesX - 5; num680 >= 5; num680--)
            {
                double num681 = (double)num680 / (double)Main.maxTilesX;
                progress.Set(1.0 - 0.5 * num681);
                bool flag44 = true;
                for (int num682 = 0; (double)num682 < Main.worldSurface; num682++)
                {
                    if (flag44)
                    {
                        if (Main.tile[num680, num682].wall == 2 || Main.tile[num680, num682].wall == 40 || Main.tile[num680, num682].wall == 64)
{
                            Main.tile[num680, num682].wall = 0;
                        }
                        if (Main.tile[num680, num682].type != 53)
{
                            if (Main.tile[num680 - 1, num682].wall == 2 || Main.tile[num680 - 1, num682].wall == 40 || Main.tile[num680 - 1, num682].wall == 40)
{
                                Main.tile[num680 - 1, num682].wall = 0;
                            }
                            if ((Main.tile[num680 - 2, num682].wall == 2 || Main.tile[num680 - 2, num682].wall == 40 || Main.tile[num680 - 2, num682].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num680 - 2, num682].wall = 0;
                            }
                            if ((Main.tile[num680 - 3, num682].wall == 2 || Main.tile[num680 - 3, num682].wall == 40 || Main.tile[num680 - 3, num682].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num680 - 3, num682].wall = 0;
                            }
                            if (Main.tile[num680 + 1, num682].wall == 2 || Main.tile[num680 + 1, num682].wall == 40 || Main.tile[num680 + 1, num682].wall == 40)
{
                                Main.tile[num680 + 1, num682].wall = 0;
                            }
                            if ((Main.tile[num680 + 2, num682].wall == 2 || Main.tile[num680 + 2, num682].wall == 40 || Main.tile[num680 + 2, num682].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num680 + 2, num682].wall = 0;
                            }
                            if ((Main.tile[num680 + 3, num682].wall == 2 || Main.tile[num680 + 3, num682].wall == 40 || Main.tile[num680 + 3, num682].wall == 40) && genRand.Next(2) == 0)
{
                                Main.tile[num680 + 3, num682].wall = 0;
                            }
                            if (Main.tile[num680, num682].active())
{
                                flag44 = false;
                            }
                        }
                    }
                    else if (Main.tile[num680, num682].wall == 0 && Main.tile[num680, num682 + 1].wall == 0 && Main.tile[num680, num682 + 2].wall == 0 && Main.tile[num680, num682 + 3].wall == 0 && Main.tile[num680, num682 + 4].wall == 0 && Main.tile[num680 - 1, num682].wall == 0 && Main.tile[num680 + 1, num682].wall == 0 && Main.tile[num680 - 2, num682].wall == 0 && Main.tile[num680 + 2, num682].wall == 0 && !Main.tile[num680, num682].active() && !Main.tile[num680, num682 + 1].active() && !Main.tile[num680, num682 + 2].active() && !Main.tile[num680, num682 + 3].active())
                    {
                        flag44 = true;
                    }
                }
            }
        });
        AddGenerationPass("Pyramids", delegate
        {
            //IL_0000: Unknown result type (might be due to invalid IL or missing references)
            //IL_0005: Unknown result type (might be due to invalid IL or missing references)
            //IL_000f: Unknown result type (might be due to invalid IL or missing references)
            Rectangle undergroundDesertLocation = GenVars.UndergroundDesertLocation;
            if (Main.tenthAnniversaryWorld)
            {
                int x26 = ((Rectangle)(ref undergroundDesertLocation)).Center.X;
                int j4 = ((Rectangle)(ref undergroundDesertLocation)).Top - 10;
                Pyramid(x26, j4);
            }
            for (int num670 = 0; num670 < GenVars.numPyr; num670++)
            {
                int num671 = GenVars.PyrX[num670];
                int num672 = GenVars.PyrY[num670];
                if (num671 > 300 && num671 < Main.maxTilesX - 300 && (GenVars.dungeonSide >= 0 || !((double)num671 < (double)GenVars.dungeonX + (double)Main.maxTilesX * 0.15)) && (GenVars.dungeonSide <= 0 || !((double)num671 > (double)GenVars.dungeonX - (double)Main.maxTilesX * 0.15)) && (!Main.tenthAnniversaryWorld || !((Rectangle)(ref undergroundDesertLocation)).Contains(num671, num672)))
                {
                    for (; !Main.tile[num671, num672].active() && (double)num672 < Main.worldSurface; num672++)
                    {
                    }
                    if (!((double)num672 >= Main.worldSurface) && Main.tile[num671, num672].type == 53)
                    {
                        int num673 = Main.maxTilesX;
                        for (int num674 = 0; num674 < num670; num674++)
{
                            int num675 = Math.Abs(num671 - GenVars.PyrX[num674]);
                            if (num675 < num673)
{
                                num673 = num675;
                            }
                        }
                        int num676 = 220;
                        if (drunkWorldGen)
{
                            num676 /= 2;
                        }
                        if (num673 >= num676)
{
                            num672--;
                            Pyramid(num671, num672);
                        }
                    }
                }
            }
        });
        AddGenerationPass("Dirt Rock Wall Runner", delegate
        {
            for (int num667 = 0; num667 < Main.maxTilesX; num667++)
            {
                int num668 = genRand.Next(10, Main.maxTilesX - 10);
                int num669 = genRand.Next(10, (int)Main.worldSurface);
                if (Main.tile[num668, num669].wall == 2)
                {
                    DirtyRockRunner(num668, num669);
                }
            }
        });
        AddGenerationPass("Living Trees", delegate
        {
            int num650 = 200;
            double num651 = (double)Main.maxTilesX / 4200.0;
            int num652 = genRand.Next(0, (int)(2.0 * num651) + 1);
            if (num652 == 0 && genRand.Next(2) == 0)
            {
                num652++;
            }
            if (drunkWorldGen)
            {
                num652 += (int)(2.0 * num651);
            }
            else if (Main.tenthAnniversaryWorld)
            {
                num652 += (int)(3.0 * num651);
            }
            else if (remixWorldGen)
            {
                num652 += (int)(2.0 * num651);
            }
            for (int num653 = 0; num653 < num652; num653++)
            {
                bool flag41 = false;
                int num654 = 0;
                while (!flag41)
                {
                    num654++;
                    if (num654 > Main.maxTilesX / 2)
                    {
                        flag41 = true;
                    }
                    int num655 = genRand.Next(beachDistance, Main.maxTilesX - beachDistance);
                    if (tenthAnniversaryWorldGen && !remixWorldGen)
                    {
                        num655 = genRand.Next((int)((double)Main.maxTilesX * 0.15), (int)((float)Main.maxTilesX * 0.85f));
                    }
                    if (num655 <= Main.maxTilesX / 2 - num650 || num655 >= Main.maxTilesX / 2 + num650)
                    {
                        int num656;
                        for (num656 = 0; !Main.tile[num655, num656].active() && (double)num656 < Main.worldSurface; num656++)
{
                        }
                        if (Main.tile[num655, num656].type == 0)
{
                            num656--;
                            if (num656 > 150)
{
                                bool flag42 = true;
                                for (int num657 = num655 - 50; num657 < num655 + 50; num657++)
{
                                    for (int num658 = num656 - 50; num658 < num656 + 50; num658++)
{
                                        if (Main.tile[num657, num658].active())
{
                                            switch (Main.tile[num657, num658].type)
{
                                            case 41:
                                            case 43:
                                            case 44:
                                            case 189:
                                            case 196:
                                            case 460:
                                            case 481:
                                            case 482:
                                            case 483:
                                                flag42 = false;
                                                break;
                                            }
                                        }
                                    }
                                }
                                for (int num659 = 0; num659 < GenVars.numMCaves; num659++)
{
                                    if (num655 > GenVars.mCaveX[num659] - 50 && num655 < GenVars.mCaveX[num659] + 50)
{
                                        flag42 = false;
                                        break;
                                    }
                                }
                                if (flag42)
{
                                    flag41 = GrowLivingTree(num655, num656);
                                    if (flag41)
{
                                        for (int num660 = -1; num660 <= 1; num660++)
{
                                            if (num660 != 0)
{
                                                int num661 = num655;
                                                int num662 = genRand.Next(4);
                                                if (drunkWorldGen || Main.tenthAnniversaryWorld)
{
                                                    num662 += genRand.Next(2, 5);
                                                }
                                                else if (remixWorldGen)
{
                                                    num662 += genRand.Next(1, 6);
                                                }
                                                for (int num663 = 0; num663 < num662; num663++)
{
                                                    num661 += genRand.Next(13, 31) * num660;
                                                    if (num661 <= Main.maxTilesX / 2 - num650 || num661 >= Main.maxTilesX / 2 + num650)
{
                                                        int num664 = num656;
                                                        if (Main.tile[num661, num664].active())
{
                                                            while (Main.tile[num661, num664].active())
{
                                                                num664--;
                                                            }
                                                        }
                                                        else
{
                                                            for (; !Main.tile[num661, num664].active(); num664++)
{
                                                            }
                                                            num664--;
                                                        }
                                                        flag42 = true;
                                                        for (int num665 = num655 - 50; num665 < num655 + 50; num665++)
{
                                                            for (int num666 = num656 - 50; num666 < num656 + 50; num666++)
{
                                                                if (Main.tile[num665, num666].active())
{
                                                                    switch (Main.tile[num665, num666].type)
{
                                                                    case 41:
                                                                    case 43:
                                                                    case 44:
                                                                    case 189:
                                                                    case 196:
                                                                    case 460:
                                                                    case 481:
                                                                    case 482:
                                                                    case 483:
                                                                        flag42 = false;
                                                                        break;
                                                                    }
                                                                }
                                                            }
                                                        }
                                                        if (flag42)
{
                                                            GrowLivingTree(num661, num664, patch: true);
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            Main.tileSolid[192] = false;
        });
        AddGenerationPass("Wood Tree Walls", delegate
        {
            for (int num646 = 25; num646 < Main.maxTilesX - 25; num646++)
            {
                for (int num647 = 25; (double)num647 < Main.worldSurface; num647++)
                {
                    if (Main.tile[num646, num647].type == 191 || Main.tile[num646, num647 - 1].type == 191 || Main.tile[num646 - 1, num647].type == 191 || Main.tile[num646 + 1, num647].type == 191 || Main.tile[num646, num647 + 1].type == 191)
                    {
                        bool flag40 = true;
                        for (int num648 = num646 - 1; num648 <= num646 + 1; num648++)
{
                            for (int num649 = num647 - 1; num649 <= num647 + 1; num649++)
{
                                if (num648 != num646 && num649 != num647 && Main.tile[num648, num649].type != 191 && Main.tile[num648, num649].wall != 244)
{
                                    flag40 = false;
                                }
                            }
                        }
                        if (flag40)
{
                            Main.tile[num646, num647].wall = 244;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Altars", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            Main.tileSolid[484] = false;
            progress.Message = Lang.gen[26].Value;
            int num641 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 3.3E-06);
            if (remixWorldGen)
            {
                num641 *= 3;
            }
            for (int num642 = 0; num642 < num641; num642++)
            {
                progress.Set((double)num642 / (double)num641);
                for (int num643 = 0; num643 < 10000; num643++)
                {
                    int num644 = genRand.Next(281, Main.maxTilesX - 3 - 280);
                    while ((double)num644 > (double)Main.maxTilesX * 0.45 && (double)num644 < (double)Main.maxTilesX * 0.55)
                    {
                        num644 = genRand.Next(281, Main.maxTilesX - 3 - 280);
                    }
                    int num645 = genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, (int)(Main.rockLayer + (double)((Main.maxTilesY - 350) * 2)) / 3);
                    if (remixWorldGen)
                    {
                        num645 = genRand.Next(100, (int)((double)Main.maxTilesY * 0.9));
                    }
                    while (oceanDepths(num644, num645) || Vector2D.Distance(new Vector2D(num644, num645), GenVars.shimmerPosition) < (double)shimmerSafetyDistance)
                    {
                        num644 = genRand.Next(281, Main.maxTilesX - 3 - 280);
                        while ((double)num644 > (double)Main.maxTilesX * 0.45 && (double)num644 < (double)Main.maxTilesX * 0.55)
{
                            num644 = genRand.Next(281, Main.maxTilesX - 3 - 280);
                        }
                        num645 = genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, (int)(Main.rockLayer + (double)((Main.maxTilesY - 350) * 2)) / 3);
                        if (remixWorldGen)
{
                            num645 = genRand.Next(100, (int)((double)Main.maxTilesY * 0.9));
                        }
                    }
                    int style2 = (crimson ? 1 : 0);
                    if (drunkWorldGen)
                    {
                        style2 = ((!GenVars.crimsonLeft) ? ((num644 >= Main.maxTilesX / 2) ? 1 : 0) : ((num644 < Main.maxTilesX / 2) ? 1 : 0));
                    }
                    if (!IsTileNearby(num644, num645, 26, 3))
                    {
                        Place3x2(num644, num645, 26, style2);
                    }
                    if (Main.tile[num644, num645].type == 26)
                    {
                        break;
                    }
                }
            }
        });
        AddGenerationPass("Wet Jungle", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num639 = 0; num639 < Main.maxTilesX; num639++)
            {
                for (int num640 = (int)GenVars.worldSurfaceLow; (double)num640 < Main.worldSurface - 1.0; num640++)
                {
                    if (Main.tile[num639, num640].active())
                    {
                        if (Main.tile[num639, num640].type == 60)
{
                            Main.tile[num639, num640 - 1].liquid = byte.MaxValue;
                            Main.tile[num639, num640 - 2].liquid = byte.MaxValue;
                        }
                        break;
                    }
                }
            }
        });
        AddGenerationPass("Jungle Temple", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            int num630 = 0;
            progress.Message = Lang.gen[70].Value;
            long num631 = 0L;
            double num632 = 0.25;
            bool flag38 = false;
            while (true)
            {
                int num633 = (int)Main.rockLayer;
                int num634 = Main.maxTilesY - 500;
                if (num633 > num634 - 1)
                {
                    num633 = num634 - 1;
                }
                int num635 = genRand.Next(num633, num634);
                int x24 = (int)(((genRand.NextDouble() * num632 + 0.1) * (double)(-GenVars.dungeonSide) + 0.5) * (double)Main.maxTilesX);
                if (remixWorldGen)
                {
                    if (notTheBees)
                    {
                        x24 = ((GenVars.dungeonSide <= 0) ? genRand.Next((int)((double)Main.maxTilesX * 0.6), (int)((double)Main.maxTilesX * 0.8)) : genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.4)));
                    }
                    else
                    {
                        x24 = genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                        while ((double)x24 > (double)Main.maxTilesX * 0.4 && (double)x24 < (double)Main.maxTilesX * 0.6)
{
                            x24 = genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                        }
                    }
                    while (Main.tile[x24, num635].active() || Main.tile[x24, num635].wall > 0 || (double)num635 > Main.worldSurface - 5.0)
                    {
                        num635--;
                    }
                    num635++;
                    if (Main.tile[x24, num635].active() && (Main.tile[x24, num635].type == 60 || Main.tile[x24, num635].type == 59))
                    {
                        int num636 = 10;
                        bool flag39 = false;
                        for (int num637 = x24 - num636; num637 <= num637 + num636; num637++)
{
                            for (int num638 = num635 - num636; num638 < num636; num638++)
{
                                if (Main.tile[num637, num638].type == 191 || Main.tileDungeon[Main.tile[num637, num638].type])
{
                                    flag39 = true;
                                }
                            }
                        }
                        if (!flag39)
{
                            flag38 = true;
                            num635 -= 10 + genRand.Next(10);
                            makeTemple(x24, num635);
                            break;
                        }
                    }
                }
                else if (Main.tile[x24, num635].active() && Main.tile[x24, num635].type == 60)
                {
                    flag38 = true;
                    makeTemple(x24, num635);
                    break;
                }
                if (num631++ > 2000000)
                {
                    if (num632 == 0.35)
                    {
                        num630++;
                        if (num630 > 10)
{
                            break;
                        }
                    }
                    num632 = Math.Min(0.35, num632 + 0.05);
                    num631 = 0L;
                }
            }
            if (!flag38)
            {
                int x25 = Main.maxTilesX - GenVars.dungeonX;
                int y22 = (int)Main.rockLayer + 100;
                if (remixWorldGen)
                {
                    x25 = (notTheBees ? ((GenVars.dungeonSide > 0) ? ((int)((double)Main.maxTilesX * 0.3)) : ((int)((double)Main.maxTilesX * 0.7))) : ((GenVars.dungeonSide > 0) ? ((int)((double)Main.maxTilesX * 0.4)) : ((int)((double)Main.maxTilesX * 0.6))));
                }
                makeTemple(x25, y22);
            }
        });
        AddGenerationPass("Hives", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_009a: Unknown result type (might be due to invalid IL or missing references)
            //IL_009f: Unknown result type (might be due to invalid IL or missing references)
            //IL_00be: Unknown result type (might be due to invalid IL or missing references)
            //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
            //IL_0135: Unknown result type (might be due to invalid IL or missing references)
            //IL_0148: Unknown result type (might be due to invalid IL or missing references)
            //IL_0170: Unknown result type (might be due to invalid IL or missing references)
            progress.Message = Lang.gen[71].Value;
            double num620 = (double)Main.maxTilesX / 4200.0;
            double num621 = 1 + genRand.Next((int)(5.0 * num620), (int)(8.0 * num620));
            if (drunkWorldGen)
            {
                num621 *= 0.667;
            }
            int num622 = 10000;
            HiveBiome hiveBiome = GenVars.configuration.CreateBiome<HiveBiome>();
            HoneyPatchBiome honeyPatchBiome = GenVars.configuration.CreateBiome<HoneyPatchBiome>();
            while (num621 > 0.0 && num622 > 0)
            {
                num622--;
                Point val3 = RandomWorldPoint((int)(Main.worldSurface + Main.rockLayer) >> 1, 20, 300, 20);
                if (drunkWorldGen)
                {
                    RandomWorldPoint((int)Main.worldSurface, 20, 300, 20);
                }
                if (hiveBiome.Place(val3, GenVars.structures))
                {
                    num621 -= 1.0;
                    int num623 = genRand.Next(5);
                    int num624 = 0;
                    int num625 = 10000;
                    while (num624 < num623 && num625 > 0)
                    {
                        double num626 = genRand.NextDouble() * 60.0 + 30.0;
                        double num627 = genRand.NextDouble() * 6.2831854820251465;
                        int num628 = (int)(Math.Cos(num627) * num626) + val3.X;
                        int num629 = (int)(Math.Sin(num627) * num626) + val3.Y;
                        num625--;
                        if (num628 > 50 && num628 < Main.maxTilesX - 50 && honeyPatchBiome.Place(new Point(num628, num629), GenVars.structures))
{
                            num624++;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Jungle Chests", delegate
        {
            //IL_0245: Unknown result type (might be due to invalid IL or missing references)
            //IL_05e7: Unknown result type (might be due to invalid IL or missing references)
            int num593 = genRand.Next(40, Main.maxTilesX - 40);
            int num594 = genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 400);
            double num595 = genRand.Next(7, 12);
            num595 *= (double)Main.maxTilesX / 4200.0;
            int num596 = 0;
            Rectangle area = default(Rectangle);
            for (int num597 = 0; (double)num597 < num595; num597++)
            {
                bool flag36 = true;
                while (flag36)
                {
                    num596++;
                    num593 = genRand.Next(40, Main.maxTilesX / 2 - 40);
                    if (GenVars.dungeonSide < 0)
                    {
                        num593 += Main.maxTilesX / 2;
                    }
                    num594 = genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 400);
                    int num598 = genRand.Next(2, 4);
                    int num599 = genRand.Next(2, 4);
                    ((Rectangle)(ref area))._002Ector(num593 - num598 - 1, num594 - num599 - 1, num598 + 1, num599 + 1);
                    if (Main.tile[num593, num594].type == 60)
                    {
                        int num600 = 30;
                        flag36 = false;
                        for (int num601 = num593 - num600; num601 < num593 + num600; num601 += 3)
{
                            for (int num602 = num594 - num600; num602 < num594 + num600; num602 += 3)
{
                                if (Main.tile[num601, num602].active() && (Main.tile[num601, num602].type == 225 || Main.tile[num601, num602].type == 229 || Main.tile[num601, num602].type == 226 || Main.tile[num601, num602].type == 119 || Main.tile[num601, num602].type == 120))
{
                                    flag36 = true;
                                }
                                if (Main.tile[num601, num602].wall == 86 || Main.tile[num601, num602].wall == 87)
{
                                    flag36 = true;
                                }
                            }
                        }
                        if (!GenVars.structures.CanPlace(area, 1))
{
                            flag36 = true;
                        }
                    }
                    if (!flag36)
                    {
                        ushort num603 = 0;
                        if (GenVars.jungleHut == 119)
{
                            num603 = 23;
                        }
                        else if (GenVars.jungleHut == 120)
{
                            num603 = 24;
                        }
                        else if (GenVars.jungleHut == 158)
{
                            num603 = 42;
                        }
                        else if (GenVars.jungleHut == 175)
{
                            num603 = 45;
                        }
                        else if (GenVars.jungleHut == 45)
{
                            num603 = 10;
                        }
                        for (int num604 = num593 - num598 - 1; num604 <= num593 + num598 + 1; num604++)
{
                            for (int num605 = num594 - num599 - 1; num605 <= num594 + num599 + 1; num605++)
{
                                Main.tile[num604, num605].active(active: true);
                                Main.tile[num604, num605].type = GenVars.jungleHut;
                                Main.tile[num604, num605].liquid = 0;
                                Main.tile[num604, num605].lava(lava: false);
                            }
                        }
                        for (int num606 = num593 - num598; num606 <= num593 + num598; num606++)
{
                            for (int num607 = num594 - num599; num607 <= num594 + num599; num607++)
{
                                Main.tile[num606, num607].active(active: false);
                                Main.tile[num606, num607].wall = num603;
                            }
                        }
                        bool flag37 = false;
                        int num608 = 0;
                        while (!flag37 && num608 < 100)
{
                            num608++;
                            int num609 = genRand.Next(num593 - num598, num593 + num598 + 1);
                            int num610 = genRand.Next(num594 - num599, num594 + num599 - 2);
                            PlaceTile(num609, num610, 4, mute: true, forced: false, -1, 3);
                            if (TileID.Sets.Torch[Main.tile[num609, num610].type])
{
                                flag37 = true;
                            }
                        }
                        for (int num611 = num593 - num598 - 1; num611 <= num593 + num598 + 1; num611++)
{
                            for (int num612 = num594 + num599 - 2; num612 <= num594 + num599; num612++)
{
                                Main.tile[num611, num612].active(active: false);
                            }
                        }
                        for (int num613 = num593 - num598 - 1; num613 <= num593 + num598 + 1; num613++)
{
                            for (int num614 = num594 + num599 - 2; num614 <= num594 + num599 - 1; num614++)
{
                                Main.tile[num613, num614].active(active: false);
                            }
                        }
                        for (int num615 = num593 - num598 - 1; num615 <= num593 + num598 + 1; num615++)
{
                            int num616 = 4;
                            int num617 = num594 + num599 + 2;
                            while (!Main.tile[num615, num617].active() && num617 < Main.maxTilesY && num616 > 0)
{
                                Main.tile[num615, num617].active(active: true);
                                Main.tile[num615, num617].type = 59;
                                num617++;
                                num616--;
                            }
                        }
                        num598 -= genRand.Next(1, 3);
                        int num618 = num594 - num599 - 2;
                        while (num598 > -1)
{
                            for (int num619 = num593 - num598 - 1; num619 <= num593 + num598 + 1; num619++)
{
                                Main.tile[num619, num618].active(active: true);
                                Main.tile[num619, num618].type = GenVars.jungleHut;
                            }
                            num598 -= genRand.Next(1, 3);
                            num618--;
                        }
                        GenVars.JChestX[GenVars.numJChests] = num593;
                        GenVars.JChestY[GenVars.numJChests] = num594;
                        GenVars.structures.AddProtectedStructure(area);
                        GenVars.numJChests++;
                        num596 = 0;
                    }
                    else if (num596 > Main.maxTilesX * 10)
                    {
                        num597++;
                        num596 = 0;
                        break;
                    }
                }
            }
            Main.tileSolid[137] = false;
        });
        AddGenerationPass("Settle Liquids", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[27].Value;
            if (notTheBees)
            {
                NotTheBees();
            }
            Liquid.worldGenTilesIgnoreWater(ignoreSolids: true);
            Liquid.QuickWater(3);
            WaterCheck();
            int num586 = 0;
            Liquid.quickSettle = true;
            int num587 = 10;
            while (num586 < num587)
            {
                int num588 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                num586++;
                double num589 = 0.0;
                int num590 = num588 * 5;
                while (Liquid.numLiquid > 0)
                {
                    num590--;
                    if (num590 < 0)
                    {
                        break;
                    }
                    double num591 = (double)(num588 - (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer)) / (double)num588;
                    if (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer > num588)
                    {
                        num588 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                    }
                    if (num591 > num589)
                    {
                        num589 = num591;
                    }
                    else
                    {
                        num591 = num589;
                    }
                    if (num586 == 1)
                    {
                        progress.Set(num591 / 3.0 + 0.33);
                    }
                    int num592 = 10;
                    if (num586 > num592)
                    {
                        num592 = num586;
                    }
                    Liquid.UpdateLiquid();
                }
                WaterCheck();
                progress.Set((double)num586 * 0.1 / 3.0 + 0.66);
            }
            Liquid.quickSettle = false;
            Liquid.worldGenTilesIgnoreWater(ignoreSolids: false);
            Main.tileSolid[484] = false;
        });
        AddGenerationPass("Remove Water From Sand", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num583 = 400; num583 < Main.maxTilesX - 400; num583++)
            {
                for (int num584 = 100; (double)num584 < Main.worldSurface - 1.0; num584++)
                {
                    if (Main.tile[num583, num584].active())
                    {
                        ushort type6 = Main.tile[num583, num584].type;
                        if (type6 == 53 || type6 == 396 || type6 == 397 || type6 == 404 || type6 == 407 || type6 == 151)
{
                            int num585 = num584;
                            while (num585 > 100)
{
                                num585--;
                                if (Main.tile[num583, num585].active())
{
                                    break;
                                }
                                Main.tile[num583, num585].liquid = 0;
                            }
                        }
                        break;
                    }
                }
            }
            Main.tileSolid[192] = true;
        });
        AddGenerationPass("Oasis", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (!notTheBees)
            {
                progress.Set(1.0);
                int num579 = Main.maxTilesX / 2100;
                num579 += genRand.Next(2);
                for (int num580 = 0; num580 < num579; num580++)
                {
                    int num581 = beachDistance + 300;
                    int num582 = Main.maxTilesX * 2;
                    while (num582 > 0)
                    {
                        num582--;
                        int x23 = genRand.Next(num581, Main.maxTilesX - num581);
                        int y21 = genRand.Next(100, (int)Main.worldSurface);
                        if (PlaceOasis(x23, y21))
{
                            num582 = -1;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Shell Piles", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (dontStarveWorldGen)
            {
                int num567 = (int)(5.0 * ((double)Main.maxTilesX / 4200.0));
                int num568 = 0;
                int num569 = 100;
                int num570 = Main.maxTilesX / 2;
                int num571 = num570 - num569;
                int num572 = num570 + num569;
                for (int num573 = 0; num573 < 80; num573++)
                {
                    int num574 = genRand.Next(100, Main.maxTilesX - 100);
                    if (num574 >= num571 && num574 <= num572)
                    {
                        num574 = genRand.Next(100, Main.maxTilesX - 100);
                        if (num574 >= num571 && num574 <= num572)
{
                            continue;
                        }
                    }
                    int y20 = (int)Main.worldSurface / 2;
                    if (MarblePileWithStatues(num574, y20))
                    {
                        num568++;
                        if (num568 >= num567)
{
                            break;
                        }
                    }
                }
            }
            if (!notTheBees)
            {
                progress.Set(1.0);
                if (genRand.Next(2) == 0)
                {
                    int shellStartXLeft = GenVars.shellStartXLeft;
                    int shellStartYLeft = GenVars.shellStartYLeft;
                    for (int num575 = shellStartXLeft - 20; num575 <= shellStartXLeft + 20; num575++)
                    {
                        for (int num576 = shellStartYLeft - 10; num576 <= shellStartYLeft + 10; num576++)
{
                            if (Main.tile[num575, num576].active() && Main.tile[num575, num576].type == 53 && !Main.tile[num575, num576 - 1].active() && Main.tile[num575, num576 - 1].liquid == 0 && !Main.tile[num575 - 1, num576].active() && Main.tile[num575 - 1, num576].liquid > 0)
{
                                GenVars.shellStartXLeft = num575;
                                GenVars.shellStartYLeft = num576;
                            }
                        }
                    }
                    GenVars.shellStartYLeft -= 50;
                    GenVars.shellStartXLeft -= genRand.Next(5);
                    if (genRand.Next(2) == 0)
                    {
                        GenVars.shellStartXLeft -= genRand.Next(10);
                    }
                    if (genRand.Next(3) == 0)
                    {
                        GenVars.shellStartXLeft -= genRand.Next(15);
                    }
                    if (genRand.Next(4) != 0)
                    {
                        ShellPile(GenVars.shellStartXLeft, GenVars.shellStartYLeft);
                    }
                    int maxValue9 = genRand.Next(2, 4);
                    if (genRand.Next(maxValue9) == 0)
                    {
                        ShellPile(GenVars.shellStartXLeft - genRand.Next(10, 35), GenVars.shellStartYLeft);
                    }
                    if (genRand.Next(maxValue9) == 0)
                    {
                        ShellPile(GenVars.shellStartXLeft - genRand.Next(40, 65), GenVars.shellStartYLeft);
                    }
                    if (genRand.Next(maxValue9) == 0)
                    {
                        ShellPile(GenVars.shellStartXLeft - genRand.Next(70, 95), GenVars.shellStartYLeft);
                    }
                    if (genRand.Next(maxValue9) == 0)
                    {
                        ShellPile(GenVars.shellStartXLeft - genRand.Next(100, 125), GenVars.shellStartYLeft);
                    }
                    if (genRand.Next(maxValue9) == 0)
                    {
                        ShellPile(GenVars.shellStartXLeft + genRand.Next(10, 25), GenVars.shellStartYLeft);
                    }
                }
                if (genRand.Next(2) == 0)
                {
                    int shellStartXRight = GenVars.shellStartXRight;
                    int shellStartYRight = GenVars.shellStartYRight;
                    for (int num577 = shellStartXRight - 20; num577 <= shellStartXRight + 20; num577++)
                    {
                        for (int num578 = shellStartYRight - 10; num578 <= shellStartYRight + 10; num578++)
{
                            if (Main.tile[num577, num578].active() && Main.tile[num577, num578].type == 53 && !Main.tile[num577, num578 - 1].active() && Main.tile[num577, num578 - 1].liquid == 0 && !Main.tile[num577 + 1, num578].active() && Main.tile[num577 + 1, num578].liquid > 0)
{
                                GenVars.shellStartXRight = num577;
                                GenVars.shellStartYRight = num578;
                            }
                        }
                    }
                    GenVars.shellStartYRight -= 50;
                    GenVars.shellStartXRight += genRand.Next(5);
                    if (genRand.Next(2) == 0)
                    {
                        GenVars.shellStartXLeft += genRand.Next(10);
                    }
                    if (genRand.Next(3) == 0)
                    {
                        GenVars.shellStartXLeft += genRand.Next(15);
                    }
                    if (genRand.Next(4) != 0)
                    {
                        ShellPile(GenVars.shellStartXRight, GenVars.shellStartYRight);
                    }
                    int maxValue10 = genRand.Next(2, 4);
                    if (genRand.Next(maxValue10) == 0)
                    {
                        ShellPile(GenVars.shellStartXRight + genRand.Next(10, 35), GenVars.shellStartYRight);
                    }
                    if (genRand.Next(maxValue10) == 0)
                    {
                        ShellPile(GenVars.shellStartXRight + genRand.Next(40, 65), GenVars.shellStartYRight);
                    }
                    if (genRand.Next(maxValue10) == 0)
                    {
                        ShellPile(GenVars.shellStartXRight + genRand.Next(70, 95), GenVars.shellStartYRight);
                    }
                    if (genRand.Next(maxValue10) == 0)
                    {
                        ShellPile(GenVars.shellStartXRight + genRand.Next(100, 125), GenVars.shellStartYRight);
                    }
                    if (genRand.Next(maxValue10) == 0)
                    {
                        ShellPile(GenVars.shellStartXRight - genRand.Next(10, 25), GenVars.shellStartYRight);
                    }
                }
            }
        });
        AddGenerationPass("Smooth World", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[60].Value;
            Main.tileSolid[GenVars.crackedType] = true;
            for (int num563 = 20; num563 < Main.maxTilesX - 20; num563++)
            {
                double value11 = (double)num563 / (double)Main.maxTilesX;
                progress.Set(value11);
                for (int num564 = 20; num564 < Main.maxTilesY - 20; num564++)
                {
                    if (Main.tile[num563, num564].type != 48 && Main.tile[num563, num564].type != 137 && Main.tile[num563, num564].type != 232 && Main.tile[num563, num564].type != 191 && Main.tile[num563, num564].type != 151 && Main.tile[num563, num564].type != 274)
                    {
                        if (!Main.tile[num563, num564 - 1].active() && Main.tile[num563 - 1, num564].type != 136 && Main.tile[num563 + 1, num564].type != 136)
{
                            if (SolidTile(num563, num564) && TileID.Sets.CanBeClearedDuringGeneration[Main.tile[num563, num564].type])
{
                                if (!Main.tile[num563 - 1, num564].halfBrick() && !Main.tile[num563 + 1, num564].halfBrick() && Main.tile[num563 - 1, num564].slope() == 0 && Main.tile[num563 + 1, num564].slope() == 0)
{
                                    if (SolidTile(num563, num564 + 1))
{
                                        if (!SolidTile(num563 - 1, num564) && !Main.tile[num563 - 1, num564 + 1].halfBrick() && SolidTile(num563 - 1, num564 + 1) && SolidTile(num563 + 1, num564) && !Main.tile[num563 + 1, num564 - 1].active())
{
                                            if (genRand.Next(2) == 0)
{
                                                SlopeTile(num563, num564, 2);
                                            }
                                            else
{
                                                PoundTile(num563, num564);
                                            }
                                        }
                                        else if (!SolidTile(num563 + 1, num564) && !Main.tile[num563 + 1, num564 + 1].halfBrick() && SolidTile(num563 + 1, num564 + 1) && SolidTile(num563 - 1, num564) && !Main.tile[num563 - 1, num564 - 1].active())
{
                                            if (genRand.Next(2) == 0)
{
                                                SlopeTile(num563, num564, 1);
                                            }
                                            else
{
                                                PoundTile(num563, num564);
                                            }
                                        }
                                        else if (SolidTile(num563 + 1, num564 + 1) && SolidTile(num563 - 1, num564 + 1) && !Main.tile[num563 + 1, num564].active() && !Main.tile[num563 - 1, num564].active())
{
                                            PoundTile(num563, num564);
                                        }
                                        if (SolidTile(num563, num564))
{
                                            if (SolidTile(num563 - 1, num564) && SolidTile(num563 + 1, num564 + 2) && !Main.tile[num563 + 1, num564].active() && !Main.tile[num563 + 1, num564 + 1].active() && !Main.tile[num563 - 1, num564 - 1].active())
{
                                                KillTile(num563, num564);
                                            }
                                            else if (SolidTile(num563 + 1, num564) && SolidTile(num563 - 1, num564 + 2) && !Main.tile[num563 - 1, num564].active() && !Main.tile[num563 - 1, num564 + 1].active() && !Main.tile[num563 + 1, num564 - 1].active())
{
                                                KillTile(num563, num564);
                                            }
                                            else if (!Main.tile[num563 - 1, num564 + 1].active() && !Main.tile[num563 - 1, num564].active() && SolidTile(num563 + 1, num564) && SolidTile(num563, num564 + 2))
{
                                                if (genRand.Next(5) == 0)
{
                                                    KillTile(num563, num564);
                                                }
                                                else if (genRand.Next(5) == 0)
{
                                                    PoundTile(num563, num564);
                                                }
                                                else
{
                                                    SlopeTile(num563, num564, 2);
                                                }
                                            }
                                            else if (!Main.tile[num563 + 1, num564 + 1].active() && !Main.tile[num563 + 1, num564].active() && SolidTile(num563 - 1, num564) && SolidTile(num563, num564 + 2))
{
                                                if (genRand.Next(5) == 0)
{
                                                    KillTile(num563, num564);
                                                }
                                                else if (genRand.Next(5) == 0)
{
                                                    PoundTile(num563, num564);
                                                }
                                                else
{
                                                    SlopeTile(num563, num564, 1);
                                                }
                                            }
                                        }
                                    }
                                    if (SolidTile(num563, num564) && !Main.tile[num563 - 1, num564].active() && !Main.tile[num563 + 1, num564].active())
{
                                        KillTile(num563, num564);
                                    }
                                }
                            }
                            else if (!Main.tile[num563, num564].active() && Main.tile[num563, num564 + 1].type != 151 && Main.tile[num563, num564 + 1].type != 274)
{
                                if (Main.tile[num563 + 1, num564].type != 190 && Main.tile[num563 + 1, num564].type != 48 && Main.tile[num563 + 1, num564].type != 232 && SolidTile(num563 - 1, num564 + 1) && SolidTile(num563 + 1, num564) && !Main.tile[num563 - 1, num564].active() && !Main.tile[num563 + 1, num564 - 1].active())
{
                                    if (Main.tile[num563 + 1, num564].type == 495)
{
                                        PlaceTile(num563, num564, Main.tile[num563 + 1, num564].type);
                                    }
                                    else
{
                                        PlaceTile(num563, num564, Main.tile[num563, num564 + 1].type);
                                    }
                                    if (genRand.Next(2) == 0)
{
                                        SlopeTile(num563, num564, 2);
                                    }
                                    else
{
                                        PoundTile(num563, num564);
                                    }
                                }
                                if (Main.tile[num563 - 1, num564].type != 190 && Main.tile[num563 - 1, num564].type != 48 && Main.tile[num563 - 1, num564].type != 232 && SolidTile(num563 + 1, num564 + 1) && SolidTile(num563 - 1, num564) && !Main.tile[num563 + 1, num564].active() && !Main.tile[num563 - 1, num564 - 1].active())
{
                                    if (Main.tile[num563 - 1, num564].type == 495)
{
                                        PlaceTile(num563, num564, Main.tile[num563 - 1, num564].type);
                                    }
                                    else
{
                                        PlaceTile(num563, num564, Main.tile[num563, num564 + 1].type);
                                    }
                                    if (genRand.Next(2) == 0)
{
                                        SlopeTile(num563, num564, 1);
                                    }
                                    else
{
                                        PoundTile(num563, num564);
                                    }
                                }
                            }
                        }
                        else if (!Main.tile[num563, num564 + 1].active() && genRand.Next(2) == 0 && SolidTile(num563, num564) && !Main.tile[num563 - 1, num564].halfBrick() && !Main.tile[num563 + 1, num564].halfBrick() && Main.tile[num563 - 1, num564].slope() == 0 && Main.tile[num563 + 1, num564].slope() == 0 && SolidTile(num563, num564 - 1))
{
                            if (SolidTile(num563 - 1, num564) && !SolidTile(num563 + 1, num564) && SolidTile(num563 - 1, num564 - 1))
{
                                SlopeTile(num563, num564, 3);
                            }
                            else if (SolidTile(num563 + 1, num564) && !SolidTile(num563 - 1, num564) && SolidTile(num563 + 1, num564 - 1))
{
                                SlopeTile(num563, num564, 4);
                            }
                        }
                        if (TileID.Sets.Conversion.Sand[Main.tile[num563, num564].type])
{
                            Tile.SmoothSlope(num563, num564, applyToNeighbors: false);
                        }
                    }
                }
            }
            for (int num565 = 20; num565 < Main.maxTilesX - 20; num565++)
            {
                for (int num566 = 20; num566 < Main.maxTilesY - 20; num566++)
                {
                    if (genRand.Next(2) == 0 && !Main.tile[num565, num566 - 1].active() && Main.tile[num565, num566].type != 137 && Main.tile[num565, num566].type != 48 && Main.tile[num565, num566].type != 232 && Main.tile[num565, num566].type != 191 && Main.tile[num565, num566].type != 151 && Main.tile[num565, num566].type != 274 && Main.tile[num565, num566].type != 75 && Main.tile[num565, num566].type != 76 && SolidTile(num565, num566) && Main.tile[num565 - 1, num566].type != 137 && Main.tile[num565 + 1, num566].type != 137)
                    {
                        if (SolidTile(num565, num566 + 1) && SolidTile(num565 + 1, num566) && !Main.tile[num565 - 1, num566].active())
{
                            SlopeTile(num565, num566, 2);
                        }
                        if (SolidTile(num565, num566 + 1) && SolidTile(num565 - 1, num566) && !Main.tile[num565 + 1, num566].active())
{
                            SlopeTile(num565, num566, 1);
                        }
                    }
                    if (Main.tile[num565, num566].slope() == 1 && !SolidTile(num565 - 1, num566))
                    {
                        SlopeTile(num565, num566);
                        PoundTile(num565, num566);
                    }
                    if (Main.tile[num565, num566].slope() == 2 && !SolidTile(num565 + 1, num566))
                    {
                        SlopeTile(num565, num566);
                        PoundTile(num565, num566);
                    }
                }
            }
            Main.tileSolid[137] = true;
            Main.tileSolid[190] = false;
            Main.tileSolid[192] = false;
            Main.tileSolid[GenVars.crackedType] = false;
        });
        AddGenerationPass("Waterfalls", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[69].Value;
            Main.tileSolid[191] = false;
            for (int num554 = 20; num554 < Main.maxTilesX - 20; num554++)
            {
                double num555 = (double)num554 / (double)Main.maxTilesX;
                progress.Set(num555 * 0.5);
                for (int num556 = 20; num556 < Main.maxTilesY - 20; num556++)
                {
                    if (SolidTile(num554, num556) && !Main.tile[num554 - 1, num556].active() && SolidTile(num554, num556 + 1) && !Main.tile[num554 + 1, num556].active() && (Main.tile[num554 - 1, num556].liquid > 0 || Main.tile[num554 + 1, num556].liquid > 0))
                    {
                        bool flag35 = true;
                        int num557 = genRand.Next(8, 20);
                        int num558 = genRand.Next(8, 20);
                        num557 = num556 - num557;
                        num558 += num556;
                        for (int num559 = num557; num559 <= num558; num559++)
{
                            if (Main.tile[num554, num559].halfBrick())
{
                                flag35 = false;
                            }
                        }
                        if ((Main.tile[num554, num556].type == 75 || Main.tile[num554, num556].type == 76) && genRand.Next(10) != 0)
{
                            flag35 = false;
                        }
                        if (flag35)
{
                            PoundTile(num554, num556);
                        }
                    }
                }
            }
            for (int num560 = 20; num560 < Main.maxTilesX - 20; num560++)
            {
                double num561 = (double)num560 / (double)Main.maxTilesX;
                progress.Set(num561 * 0.5 + 0.5);
                for (int num562 = 20; num562 < Main.maxTilesY - 20; num562++)
                {
                    if (Main.tile[num560, num562].type != 48 && Main.tile[num560, num562].type != 232 && SolidTile(num560, num562) && SolidTile(num560, num562 + 1))
                    {
                        if (!SolidTile(num560 + 1, num562) && Main.tile[num560 - 1, num562].halfBrick() && Main.tile[num560 - 2, num562].liquid > 0)
{
                            PoundTile(num560, num562);
                        }
                        if (!SolidTile(num560 - 1, num562) && Main.tile[num560 + 1, num562].halfBrick() && Main.tile[num560 + 2, num562].liquid > 0)
{
                            PoundTile(num560, num562);
                        }
                    }
                }
            }
            Main.tileSolid[191] = true;
        });
        AddGenerationPass("Ice", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (notTheBees)
            {
                NotTheBees();
            }
            progress.Set(1.0);
            for (int num552 = 10; num552 < Main.maxTilesX - 10; num552++)
            {
                for (int num553 = (int)Main.worldSurface; num553 < Main.maxTilesY - 100; num553++)
                {
                    if (Main.tile[num552, num553].liquid > 0 && (!Main.tile[num552, num553].lava() || remixWorldGen))
                    {
                        MakeWateryIceThing(num552, num553);
                    }
                }
            }
            Main.tileSolid[226] = false;
            Main.tileSolid[162] = false;
        });
        AddGenerationPass("Wall Variety", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_0066: Unknown result type (might be due to invalid IL or missing references)
            //IL_006b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0083: Unknown result type (might be due to invalid IL or missing references)
            //IL_008b: Unknown result type (might be due to invalid IL or missing references)
            //IL_007c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0081: Unknown result type (might be due to invalid IL or missing references)
            //IL_00af: Unknown result type (might be due to invalid IL or missing references)
            //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
            //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
            //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
            //IL_0186: Unknown result type (might be due to invalid IL or missing references)
            //IL_012a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0195: Unknown result type (might be due to invalid IL or missing references)
            //IL_0139: Unknown result type (might be due to invalid IL or missing references)
            //IL_02b5: Unknown result type (might be due to invalid IL or missing references)
            //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
            //IL_02c5: Unknown result type (might be due to invalid IL or missing references)
            //IL_0229: Unknown result type (might be due to invalid IL or missing references)
            //IL_0230: Unknown result type (might be due to invalid IL or missing references)
            //IL_0239: Unknown result type (might be due to invalid IL or missing references)
            //IL_0370: Unknown result type (might be due to invalid IL or missing references)
            //IL_0377: Unknown result type (might be due to invalid IL or missing references)
            //IL_037e: Unknown result type (might be due to invalid IL or missing references)
            progress.Message = Lang.gen[79].Value;
            double num548 = (double)(Main.maxTilesX * Main.maxTilesY) / 5040000.0;
            int num549 = (int)(300.0 * num548);
            int num550 = num549;
            ShapeData shapeData = new ShapeData();
            while (num549 > 0)
            {
                progress.Set(1.0 - (double)num549 / (double)num550);
                Point val2 = RandomWorldPoint((int)GenVars.worldSurface, 2, 190, 2);
                while (Vector2D.Distance(new Vector2D(val2.X, val2.Y), GenVars.shimmerPosition) < (double)shimmerSafetyDistance)
                {
                    val2 = RandomWorldPoint((int)GenVars.worldSurface, 2, 190, 2);
                }
                Tile tile7 = Main.tile[val2.X, val2.Y];
                Tile tile8 = Main.tile[val2.X, val2.Y - 1];
                ushort num551 = 0;
                if (tile7.type == 60)
                {
                    num551 = (ushort)(204 + genRand.Next(4));
                }
                else if (tile7.type == 1 && tile8.wall == 0)
                {
                    num551 = ((!remixWorldGen) ? (((double)val2.Y < GenVars.rockLayer) ? ((ushort)(196 + genRand.Next(4))) : ((val2.Y >= GenVars.lavaLine) ? ((ushort)(208 + genRand.Next(4))) : ((ushort)(212 + genRand.Next(4))))) : (((double)val2.Y > GenVars.rockLayer) ? ((ushort)(196 + genRand.Next(4))) : ((val2.Y <= GenVars.lavaLine || genRand.Next(2) != 0) ? ((ushort)(212 + genRand.Next(4))) : ((ushort)(208 + genRand.Next(4))))));
                }
                if (tile7.active() && num551 != 0 && !tile8.active())
                {
                    bool foundInvalidTile = false;
                    bool flag34 = ((tile7.type != 60) ? WorldUtils.Gen(new Point(val2.X, val2.Y - 1), new ShapeFloodFill(1000), Actions.Chain(new Modifiers.IsNotSolid(), new Actions.Blank().Output(shapeData), new Actions.ContinueWrapper(Actions.Chain(new Modifiers.IsTouching(true, 60, 147, 161, 396, 397, 70, 191), new Modifiers.IsTouching(true, 147, 161, 396, 397, 70, 191), new Actions.Custom(delegate
                    {
                        foundInvalidTile = true;
                        return true;
                    }))))) : WorldUtils.Gen(new Point(val2.X, val2.Y - 1), new ShapeFloodFill(1000), Actions.Chain(new Modifiers.IsNotSolid(), new Actions.Blank().Output(shapeData), new Actions.ContinueWrapper(Actions.Chain(new Modifiers.IsTouching(true, 147, 161, 396, 397, 70, 191), new Actions.Custom(delegate
                    {
                        foundInvalidTile = true;
                        return true;
                    }))))));
                    if (shapeData.Count > 50 && flag34 && !foundInvalidTile)
                    {
                        WorldUtils.Gen(new Point(val2.X, val2.Y), new ModShapes.OuterOutline(shapeData, useDiagonals: true, useInterior: true), Actions.Chain(new Modifiers.SkipWalls(87), new Actions.PlaceWall(num551)));
                        num549--;
                    }
                    shapeData.Clear();
                }
            }
        });
        AddGenerationPass("Life Crystals", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (getGoodWorldGen)
            {
                Main.tileSolid[56] = false;
            }
            if (notTheBees)
            {
                NotTheBees();
            }
            progress.Message = Lang.gen[28].Value;
            double num545 = (double)(Main.maxTilesX * Main.maxTilesY) * 2E-05;
            if (tenthAnniversaryWorldGen)
            {
                num545 *= 1.2;
            }
            if (Main.starGame)
            {
                num545 *= Main.starGameMath(0.2);
            }
            for (int num546 = 0; num546 < (int)num545; num546++)
            {
                double value10 = (double)num546 / ((double)(Main.maxTilesX * Main.maxTilesY) * 2E-05);
                progress.Set(value10);
                bool flag33 = false;
                int num547 = 0;
                while (!flag33)
                {
                    int j3 = genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, Main.maxTilesY - 300);
                    if (remixWorldGen)
                    {
                        j3 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                    }
                    if (AddLifeCrystal(genRand.Next(Main.offLimitBorderTiles, Main.maxTilesX - Main.offLimitBorderTiles), j3))
                    {
                        flag33 = true;
                    }
                    else
                    {
                        num547++;
                        if (num547 >= 10000)
{
                            flag33 = true;
                        }
                    }
                }
            }
            Main.tileSolid[225] = false;
        });
        AddGenerationPass("Statues", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[29].Value;
            int num538 = 0;
            double num539 = (double)Main.maxTilesX / 4200.0;
            int num540 = (int)((double)(GenVars.statueList.Length * 2) * num539);
            if (noTrapsWorldGen)
            {
                num540 *= 15;
                if (tenthAnniversaryWorldGen || notTheBees)
                {
                    num540 /= 5;
                }
            }
            if (Main.starGame)
            {
                num540 = (int)((double)num540 * Main.starGameMath(0.2));
            }
            for (int num541 = 0; num541 < num540; num541++)
            {
                if (num538 >= GenVars.statueList.Length)
                {
                    num538 = 0;
                }
                int x22 = GenVars.statueList[num538].X;
                int y19 = GenVars.statueList[num538].Y;
                double value9 = num541 / num540;
                progress.Set(value9);
                bool flag32 = false;
                int num542 = 0;
                while (!flag32)
                {
                    int num543 = genRand.Next(20, Main.maxTilesX - 20);
                    int num544 = genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, Main.maxTilesY - 300);
                    if (remixWorldGen)
                    {
                        genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                    }
                    while (oceanDepths(num543, num544))
                    {
                        num543 = genRand.Next(20, Main.maxTilesX - 20);
                        num544 = genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, Main.maxTilesY - 300);
                        if (remixWorldGen)
{
                            genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                        }
                    }
                    while (!Main.tile[num543, num544].active())
                    {
                        num544++;
                        if (num544 >= Main.maxTilesY)
{
                            break;
                        }
                    }
                    if (num544 < Main.maxTilesY)
                    {
                        num544--;
                        if (!Main.tile[num543, num544].shimmer())
{
                            PlaceTile(num543, num544, x22, mute: true, forced: true, -1, y19);
                        }
                        if (Main.tile[num543, num544].active() && Main.tile[num543, num544].type == x22)
{
                            flag32 = true;
                            if (GenVars.StatuesWithTraps.Contains(num538))
{
                                PlaceStatueTrap(num543, num544);
                            }
                            num538++;
                        }
                        else
{
                            num542++;
                            if (num542 >= 10000)
{
                                flag32 = true;
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Buried Chests", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_031d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0322: Unknown result type (might be due to invalid IL or missing references)
            //IL_0324: Unknown result type (might be due to invalid IL or missing references)
            //IL_0346: Unknown result type (might be due to invalid IL or missing references)
            //IL_02eb: Unknown result type (might be due to invalid IL or missing references)
            //IL_0388: Unknown result type (might be due to invalid IL or missing references)
            //IL_038a: Unknown result type (might be due to invalid IL or missing references)
            progress.Message = Lang.gen[30].Value;
            Main.tileSolid[226] = true;
            Main.tileSolid[162] = true;
            Main.tileSolid[225] = true;
            CaveHouseBiome caveHouseBiome = GenVars.configuration.CreateBiome<CaveHouseBiome>();
            int random6 = passConfig.Get<WorldGenRange>("CaveHouseCount").GetRandom(genRand);
            int random7 = passConfig.Get<WorldGenRange>("UnderworldChestCount").GetRandom(genRand);
            int num524 = passConfig.Get<WorldGenRange>("CaveChestCount").GetRandom(genRand);
            int random8 = passConfig.Get<WorldGenRange>("AdditionalDesertHouseCount").GetRandom(genRand);
            if (Main.starGame)
            {
                num524 = (int)((double)num524 * Main.starGameMath(0.2));
            }
            int num525 = random6 + random7 + num524 + random8;
            int num526 = 10000;
            for (int num527 = 0; num527 < num524; num527++)
            {
                if (num526 <= 0)
                {
                    break;
                }
                progress.Set((double)num527 / (double)num525);
                int num528 = genRand.Next(20, Main.maxTilesX - 20);
                int num529 = genRand.Next((int)((GenVars.worldSurfaceHigh + 20.0 + Main.rockLayer) / 2.0), Main.maxTilesY - 230);
                if (remixWorldGen)
                {
                    num529 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                }
                ushort wall = Main.tile[num528, num529].wall;
                if (Main.wallDungeon[wall] || wall == 87 || oceanDepths(num528, num529) || !AddBuriedChest(num528, num529, 0, notNearOtherChests: false, -1, trySlope: false, 0))
                {
                    num526--;
                    num527--;
                }
            }
            num526 = 10000;
            for (int num530 = 0; num530 < random7; num530++)
            {
                if (num526 <= 0)
                {
                    break;
                }
                progress.Set((double)(num530 + num524) / (double)num525);
                int num531 = genRand.Next(20, Main.maxTilesX - 20);
                int num532 = genRand.Next(Main.UnderworldLayer, Main.maxTilesY - 50);
                if (Main.wallDungeon[Main.tile[num531, num532].wall] || !AddBuriedChest(num531, num532, 0, notNearOtherChests: false, -1, trySlope: false, 0))
                {
                    num526--;
                    num530--;
                }
            }
            num526 = 10000;
            for (int num533 = 0; num533 < random6; num533++)
            {
                if (num526 <= 0)
                {
                    break;
                }
                progress.Set((double)(num533 + num524 + random7) / (double)num525);
                int num534 = genRand.Next(80, Main.maxTilesX - 80);
                int num535 = genRand.Next((int)(GenVars.worldSurfaceHigh + 20.0), Main.maxTilesY - 230);
                if (remixWorldGen)
                {
                    num535 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                }
                if (oceanDepths(num534, num535) || !caveHouseBiome.Place(new Point(num534, num535), GenVars.structures))
                {
                    num526--;
                    num533--;
                }
            }
            num526 = 10000;
            Rectangle undergroundDesertHiveLocation = GenVars.UndergroundDesertHiveLocation;
            if ((double)undergroundDesertHiveLocation.Y < Main.worldSurface + 26.0)
            {
                int num536 = (int)Main.worldSurface + 26 - undergroundDesertHiveLocation.Y;
                undergroundDesertHiveLocation.Y += num536;
                undergroundDesertHiveLocation.Height -= num536;
            }
            for (int num537 = 0; num537 < random8; num537++)
            {
                if (num526 <= 0)
                {
                    break;
                }
                progress.Set((double)(num537 + num524 + random7 + random6) / (double)num525);
                if (!caveHouseBiome.Place(RandomRectanglePoint(undergroundDesertHiveLocation), GenVars.structures))
                {
                    num526--;
                    num537--;
                }
            }
            Main.tileSolid[226] = false;
            Main.tileSolid[162] = false;
            Main.tileSolid[225] = false;
        });
        AddGenerationPass("Surface Chests", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[31].Value;
            for (int num514 = 0; num514 < (int)((double)Main.maxTilesX * 0.005); num514++)
            {
                double value8 = (double)num514 / ((double)Main.maxTilesX * 0.005);
                progress.Set(value8);
                bool flag30 = false;
                int num515 = 0;
                while (!flag30)
                {
                    int num516 = genRand.Next(200, Main.maxTilesX - 200);
                    int num517 = genRand.Next((int)GenVars.worldSurfaceLow, (int)Main.worldSurface);
                    if (remixWorldGen)
                    {
                        num517 = genRand.Next(Main.maxTilesY - 400, Main.maxTilesY - 150);
                    }
                    else
                    {
                        while (oceanDepths(num516, num517))
{
                            num516 = genRand.Next(300, Main.maxTilesX - 300);
                            num517 = genRand.Next((int)GenVars.worldSurfaceLow, (int)Main.worldSurface);
                        }
                    }
                    bool flag31 = false;
                    if (!Main.tile[num516, num517].active())
                    {
                        if (Main.tile[num516, num517].wall == 2 || Main.tile[num516, num517].wall == 59 || Main.tile[num516, num517].wall == 244 || remixWorldGen)
{
                            flag31 = true;
                        }
                    }
                    else
                    {
                        int num518 = 50;
                        int num519 = num516;
                        int num520 = num517;
                        int num521 = 1;
                        for (int num522 = num519 - num518; num522 <= num519 + num518; num522 += 2)
{
                            for (int num523 = num520 - num518; num523 <= num520 + num518; num523 += 2)
{
                                if ((double)num523 < Main.worldSurface && !Main.tile[num522, num523].active() && Main.tile[num522, num523].wall == 244 && genRand.Next(num521) == 0)
{
                                    num521++;
                                    flag31 = true;
                                    num516 = num522;
                                    num517 = num523;
                                }
                            }
                        }
                    }
                    if (flag31 && AddBuriedChest(num516, num517, 0, notNearOtherChests: true, -1, trySlope: false, 0))
                    {
                        flag30 = true;
                    }
                    else
                    {
                        num515++;
                        if (num515 >= 2000)
{
                            flag30 = true;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Jungle Chests Placement", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[32].Value;
            for (int num509 = 0; num509 < GenVars.numJChests; num509++)
            {
                double value7 = (double)num509 / (double)GenVars.numJChests;
                progress.Set(value7);
                int nextJungleChestItem = GetNextJungleChestItem();
                if (!AddBuriedChest(GenVars.JChestX[num509] + genRand.Next(2), GenVars.JChestY[num509], nextJungleChestItem, notNearOtherChests: false, 10, trySlope: false, 0))
                {
                    for (int num510 = GenVars.JChestX[num509] - 1; num510 <= GenVars.JChestX[num509] + 1; num510++)
                    {
                        for (int num511 = GenVars.JChestY[num509]; num511 <= GenVars.JChestY[num509] + 2; num511++)
{
                            KillTile(num510, num511);
                        }
                    }
                    for (int num512 = GenVars.JChestX[num509] - 1; num512 <= GenVars.JChestX[num509] + 1; num512++)
                    {
                        for (int num513 = GenVars.JChestY[num509]; num513 <= GenVars.JChestY[num509] + 3; num513++)
{
                            if (num513 < Main.maxTilesY)
{
                                Main.tile[num512, num513].slope(0);
                                Main.tile[num512, num513].halfBrick(halfBrick: false);
                            }
                        }
                    }
                    AddBuriedChest(GenVars.JChestX[num509], GenVars.JChestY[num509], nextJungleChestItem, notNearOtherChests: false, 10, trySlope: false, 0);
                }
            }
        });
        AddGenerationPass("Water Chests", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[33].Value;
            for (int num496 = 0; num496 < GenVars.numOceanCaveTreasure; num496++)
            {
                int contain = genRand.NextFromList(new short[5] { 863, 186, 277, 187, 4404 });
                bool flag28 = false;
                double num497 = 2.0;
                while (!flag28 && num497 < 50.0)
                {
                    num497 += 0.1;
                    int num498 = genRand.Next(GenVars.oceanCaveTreasure[num496].X - (int)num497, GenVars.oceanCaveTreasure[num496].X + (int)num497 + 1);
                    int num499 = genRand.Next(GenVars.oceanCaveTreasure[num496].Y - (int)num497 / 2, GenVars.oceanCaveTreasure[num496].Y + (int)num497 / 2 + 1);
                    num498 = ((num498 >= Main.maxTilesX) ? ((int)((double)num498 + num497 / 2.0)) : ((int)((double)num498 - num497 / 2.0)));
                    if (Main.tile[num498, num499].liquid > 250 && (Main.tile[num498, num499].liquidType() == 0 || notTheBees || remixWorldGen))
                    {
                        flag28 = AddBuriedChest(num498, num499, contain, notNearOtherChests: false, 17, trySlope: true, 0);
                    }
                }
            }
            int num500 = 0;
            double num501 = (double)Main.maxTilesX / 4200.0;
            for (int num502 = 0; (double)num502 < 9.0 * num501; num502++)
            {
                double value6 = (double)num502 / (9.0 * num501);
                progress.Set(value6);
                int num503 = 0;
                num500++;
                int maxValue8 = 10;
                if (tenthAnniversaryWorldGen)
                {
                    maxValue8 = 7;
                }
                if (genRand.Next(maxValue8) == 0)
                {
                    num503 = 863;
                }
                else
                {
                    switch (num500)
                    {
                    case 1:
                        num503 = 186;
                        break;
                    case 2:
                        num503 = 4404;
                        break;
                    case 3:
                        num503 = 277;
                        break;
                    default:
                        num503 = 187;
                        num500 = 0;
                        break;
                    }
                }
                bool flag29 = false;
                int num504 = 0;
                while (!flag29)
                {
                    int num505 = genRand.Next(50, Main.maxTilesX - 50);
                    int num506 = genRand.Next(1, Main.UnderworldLayer);
                    while (Main.tile[num505, num506].liquid < 250 || (Main.tile[num505, num506].liquidType() != 0 && !notTheBees && !remixWorldGen))
                    {
                        num505 = genRand.Next(50, Main.maxTilesX - 50);
                        num506 = genRand.Next(50, Main.UnderworldLayer);
                    }
                    flag29 = AddBuriedChest(num505, num506, num503, notNearOtherChests: false, 17, num505 < beachDistance || num505 > Main.maxTilesX - beachDistance, 0);
                    num504++;
                    if (num504 > 10000)
                    {
                        break;
                    }
                }
                flag29 = false;
                num504 = 0;
                while (!flag29)
                {
                    int num507 = genRand.Next(50, Main.maxTilesX - 50);
                    int num508 = genRand.Next((int)Main.worldSurface, Main.UnderworldLayer);
                    while (Main.tile[num507, num508].liquid < 250 || (Main.tile[num507, num508].liquidType() != 0 && !notTheBees))
                    {
                        num507 = genRand.Next(50, Main.maxTilesX - 50);
                        num508 = genRand.Next((int)Main.worldSurface, Main.UnderworldLayer);
                    }
                    flag29 = AddBuriedChest(num507, num508, num503, notNearOtherChests: false, 17, num507 < beachDistance || num507 > Main.maxTilesX - beachDistance, 0);
                    num504++;
                    if (num504 > 10000)
                    {
                        break;
                    }
                }
            }
        });
        AddGenerationPass("Spider Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[64].Value;
            maxTileCount = 3500;
            int num491 = Main.maxTilesX / 2;
            int num492 = (int)((double)Main.maxTilesX * 0.005);
            if (getGoodWorldGen)
            {
                num492 *= 3;
            }
            if (notTheBees)
            {
                Main.tileSolid[225] = true;
            }
            for (int num493 = 0; num493 < num492; num493++)
            {
                double value5 = (double)num493 / ((double)Main.maxTilesX * 0.005);
                progress.Set(value5);
                int num494 = 0;
                int x21 = genRand.Next(200, Main.maxTilesX - 200);
                int y18 = genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 230);
                if (remixWorldGen)
                {
                    y18 = genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                }
                int num495 = countTiles(x21, y18, jungle: false, lavaOk: true);
                while ((num495 >= 3500 || num495 < 500) && num494 < num491)
                {
                    num494++;
                    x21 = genRand.Next(200, Main.maxTilesX - 200);
                    y18 = genRand.Next((int)Main.rockLayer + 30, Main.maxTilesY - 230);
                    if (remixWorldGen)
                    {
                        y18 = genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                    }
                    num495 = countTiles(x21, y18, jungle: false, lavaOk: true);
                    if (shroomCount > 1)
                    {
                        num495 = 0;
                    }
                }
                if (num494 < num491)
                {
                    Spread.Spider(x21, y18);
                }
            }
            if (notTheBees)
            {
                Main.tileSolid[225] = false;
            }
            Main.tileSolid[162] = true;
        });
        AddGenerationPass("Gem Caves", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (!notTheBees)
            {
                progress.Message = Lang.gen[64].Value;
                maxTileCount = 300;
                double num487 = (double)Main.maxTilesX * 0.003;
                if (tenthAnniversaryWorldGen)
                {
                    num487 *= 1.5;
                }
                if (Main.starGame)
                {
                    num487 *= Main.starGameMath(0.2);
                }
                for (int num488 = 0; (double)num488 < num487; num488++)
                {
                    double value4 = (double)num488 / num487;
                    progress.Set(value4);
                    int num489 = 0;
                    int x20 = genRand.Next(200, Main.maxTilesX - 200);
                    int y17 = genRand.Next((int)Main.rockLayer + 30, Main.maxTilesY - 230);
                    if (remixWorldGen)
                    {
                        y17 = genRand.Next((int)Main.worldSurface + 30, (int)Main.rockLayer - 30);
                    }
                    int num490 = countTiles(x20, y17);
                    while ((num490 >= 300 || num490 < 50 || lavaCount > 0 || iceCount > 0 || rockCount == 0) && num489 < 1000)
                    {
                        num489++;
                        x20 = genRand.Next(200, Main.maxTilesX - 200);
                        y17 = genRand.Next((int)Main.rockLayer + 30, Main.maxTilesY - 230);
                        if (remixWorldGen)
{
                            y17 = genRand.Next((int)Main.worldSurface + 30, (int)Main.rockLayer - 30);
                        }
                        num490 = countTiles(x20, y17);
                    }
                    if (num489 < 1000)
                    {
                        gemCave(x20, y17);
                    }
                }
            }
        });
        AddGenerationPass("Moss", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (!notTheBees || remixWorldGen)
            {
                progress.Message = Lang.gen[61].Value;
                randMoss();
                int num457 = Main.maxTilesX / 2100;
                if (remixWorldGen)
                {
                    num457 = (int)((double)num457 * 1.5);
                }
                else if (tenthAnniversaryWorldGen)
                {
                    num457 *= 2;
                }
                int num458 = 0;
                int num459 = 0;
                while (num459 < num457)
                {
                    int num460 = genRand.Next(100, Main.maxTilesX - 100);
                    if (remixWorldGen)
                    {
                        num460 = genRand.Next((int)((double)Main.maxTilesX * 0.3), (int)((double)Main.maxTilesX * 0.7));
                    }
                    else if (tenthAnniversaryWorldGen)
                    {
                        if (genRand.Next(2) == 0)
{
                            randMoss(justNeon: true);
                        }
                    }
                    else if (getGoodWorldGen)
                    {
                        while ((double)num460 > (double)Main.maxTilesX * 0.42 && (double)num460 < (double)Main.maxTilesX * 0.48)
{
                            num460 = genRand.Next(100, Main.maxTilesX - 100);
                        }
                    }
                    else if (!drunkWorldGen)
                    {
                        while ((double)num460 > (double)Main.maxTilesX * 0.38 && (double)num460 < (double)Main.maxTilesX * 0.62)
{
                            num460 = genRand.Next(100, Main.maxTilesX - 100);
                        }
                    }
                    int num461 = ((!remixWorldGen) ? genRand.Next((int)Main.rockLayer + 40, GenVars.lavaLine - 40) : genRand.Next((int)Main.worldSurface + 50, (int)Main.rockLayer - 50));
                    bool flag27 = false;
                    int num462 = 50;
                    for (int num463 = num460 - num462; num463 <= num460 + num462; num463++)
                    {
                        for (int num464 = num461 - num462; num464 <= num461 + num462; num464++)
{
                            if (Main.tile[num463, num464].active())
{
                                int type5 = Main.tile[num463, num464].type;
                                if (remixWorldGen)
{
                                    if (type5 == 60 || type5 == 161 || type5 == 147 || Main.tileDungeon[type5] || type5 == 25 || type5 == 203)
{
                                        flag27 = true;
                                        num463 = num460 + num462 + 1;
                                        break;
                                    }
                                }
                                else if (type5 == 70 || type5 == 60 || type5 == 367 || type5 == 368 || type5 == 161 || type5 == 147 || type5 == 396 || type5 == 397 || Main.tileDungeon[type5])
{
                                    flag27 = true;
                                    num463 = num460 + num462 + 1;
                                    break;
                                }
                            }
                        }
                    }
                    if (flag27)
                    {
                        num458++;
                        if (num458 > Main.maxTilesX)
{
                            num459++;
                        }
                    }
                    else
                    {
                        num458 = 0;
                        num459++;
                        int maxY = GenVars.lavaLine;
                        if (remixWorldGen)
{
                            maxY = (int)Main.rockLayer + 50;
                        }
                        neonMossBiome(num460, num461, maxY);
                    }
                }
                maxTileCount = 2500;
                for (int num465 = 0; num465 < (int)((double)Main.maxTilesX * 0.01); num465++)
                {
                    double value3 = (double)num465 / ((double)Main.maxTilesX * 0.01);
                    progress.Set(value3);
                    int num466 = 0;
                    int num467 = genRand.Next(200, Main.maxTilesX - 200);
                    int num468 = genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, GenVars.waterLine);
                    if (remixWorldGen)
                    {
                        num468 = genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                    }
                    if (!(Vector2D.Distance(new Vector2D(num467, num468), GenVars.shimmerPosition) < (double)shimmerSafetyDistance))
                    {
                        int num469 = countTiles(num467, num468);
                        while ((num469 >= 2500 || num469 < 10 || lavaCount > 0 || iceCount > 0 || rockCount == 0 || shroomCount > 0) && num466 < 1000)
{
                            num466++;
                            num467 = genRand.Next(200, Main.maxTilesX - 200);
                            num468 = genRand.Next((int)Main.rockLayer + 30, Main.maxTilesY - 230);
                            num469 = countTiles(num467, num468);
                        }
                        if (num466 < 1000)
{
                            setMoss(num467, num468);
                            Spread.Moss(num467, num468);
                        }
                    }
                }
                for (int num470 = 0; num470 < Main.maxTilesX; num470++)
                {
                    int num471 = genRand.Next(50, Main.maxTilesX - 50);
                    int num472 = ((!remixWorldGen) ? genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, GenVars.lavaLine) : genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300));
                    if (!(Vector2D.Distance(new Vector2D(num471, num472), GenVars.shimmerPosition) < (double)shimmerSafetyDistance) && Main.tile[num471, num472].type == 1)
                    {
                        setMoss(num471, num472);
                        Main.tile[num471, num472].type = GenVars.mossTile;
                    }
                }
                double num473 = (double)Main.maxTilesX * 0.05;
                while (num473 > 0.0)
                {
                    int num474 = genRand.Next(50, Main.maxTilesX - 50);
                    int num475 = ((!remixWorldGen) ? genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, GenVars.lavaLine) : genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300));
                    if (!(Vector2D.Distance(new Vector2D(num474, num475), GenVars.shimmerPosition) < (double)shimmerSafetyDistance) && Main.tile[num474, num475].type == 1 && (!Main.tile[num474 - 1, num475].active() || !Main.tile[num474 + 1, num475].active() || !Main.tile[num474, num475 - 1].active() || !Main.tile[num474, num475 + 1].active()))
                    {
                        setMoss(num474, num475);
                        Main.tile[num474, num475].type = GenVars.mossTile;
                        num473 -= 1.0;
                    }
                }
                num473 = (double)Main.maxTilesX * 0.065;
                if (remixWorldGen)
                {
                    num473 *= 2.0;
                }
                while (num473 > 0.0)
                {
                    int num476 = genRand.Next(50, Main.maxTilesX - 50);
                    int num477 = ((!remixWorldGen) ? genRand.Next(GenVars.waterLine, Main.UnderworldLayer) : genRand.Next(GenVars.lavaLine, (int)Main.rockLayer + 50));
                    if (Main.tile[num476, num477].type == 1 && (!Main.tile[num476 - 1, num477].active() || !Main.tile[num476 + 1, num477].active() || !Main.tile[num476, num477 - 1].active() || !Main.tile[num476, num477 + 1].active()))
                    {
                        int num478 = 25;
                        int num479 = 0;
                        for (int num480 = num476 - num478; num480 < num476 + num478; num480++)
{
                            for (int num481 = num477 - num478; num481 < num477 + num478; num481++)
{
                                if (Main.tile[num480, num481].liquid > 0 && Main.tile[num480, num481].lava())
{
                                    num479++;
                                }
                            }
                        }
                        if (num479 > 20)
{
                            Main.tile[num476, num477].type = 381;
                            num473 -= 1.0;
                        }
                        else
{
                            num473 -= 0.002;
                        }
                    }
                    num473 -= 0.001;
                }
                for (int num482 = 0; num482 < Main.maxTilesX; num482++)
                {
                    for (int num483 = 0; num483 < Main.maxTilesY; num483++)
                    {
                        if (Main.tile[num482, num483].active() && Main.tileMoss[Main.tile[num482, num483].type])
{
                            for (int num484 = 0; num484 < 4; num484++)
{
                                int num485 = num482;
                                int num486 = num483;
                                if (num484 == 0)
{
                                    num485--;
                                }
                                if (num484 == 1)
{
                                    num485++;
                                }
                                if (num484 == 2)
{
                                    num486--;
                                }
                                if (num484 == 3)
{
                                    num486++;
                                }
                                try
{
                                    grassSpread = 0;
                                    SpreadGrass(num485, num486, 1, Main.tile[num482, num483].type);
                                }
                                catch
{
                                    grassSpread = 0;
                                    SpreadGrass(num485, num486, 1, Main.tile[num482, num483].type, repeat: false);
                                }
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Temple", delegate
        {
            Main.tileSolid[162] = false;
            Main.tileSolid[226] = true;
            templePart2();
            Main.tileSolid[232] = false;
        });
        AddGenerationPass("Cave Walls", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[63].Value;
            maxTileCount = 1500;
            for (int num443 = 0; num443 < (int)((double)Main.maxTilesX * 0.04); num443++)
            {
                double num444 = (double)num443 / ((double)Main.maxTilesX * 0.04);
                progress.Set(num444 * 0.66);
                int num445 = 0;
                int x17 = genRand.Next(200, Main.maxTilesX - 200);
                int y14 = genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 220);
                if (remixWorldGen)
                {
                    y14 = genRand.Next((int)Main.worldSurface + 25, (int)Main.rockLayer);
                }
                int num446 = countTiles(x17, y14, jungle: false, lavaOk: true);
                while ((num446 >= maxTileCount || num446 < 10) && num445 < 500)
                {
                    num445++;
                    x17 = genRand.Next(200, Main.maxTilesX - 200);
                    y14 = genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 220);
                    if (remixWorldGen)
                    {
                        y14 = genRand.Next((int)Main.worldSurface + 25, (int)Main.rockLayer);
                    }
                    num446 = countTiles(x17, y14, jungle: false, lavaOk: true);
                }
                if (num445 < 500)
                {
                    int num447 = genRand.Next(2);
                    if ((double)shroomCount > (double)rockCount * 0.75)
                    {
                        num447 = 80;
                    }
                    else if (iceCount > 0)
                    {
                        switch (num447)
{
                        case 0:
                            num447 = 40;
                            break;
                        case 1:
                            num447 = 71;
                            break;
                        }
                    }
                    else if (lavaCount > 0)
                    {
                        num447 = 79;
                    }
                    else
                    {
                        num447 = genRand.Next(4);
                        switch (num447)
{
                        case 0:
                            num447 = 59;
                            break;
                        case 1:
                            num447 = 61;
                            break;
                        case 2:
                            num447 = 170;
                            break;
                        case 3:
                            num447 = 171;
                            break;
                        }
                    }
                    Spread.Wall(x17, y14, num447);
                }
            }
            if (remixWorldGen)
            {
                maxTileCount = 1500;
                for (int num448 = 0; num448 < (int)((double)Main.maxTilesX * 0.04); num448++)
                {
                    double num449 = (double)num448 / ((double)Main.maxTilesX * 0.04);
                    progress.Set(num449 * 0.66);
                    int num450 = 0;
                    int x18 = genRand.Next(200, Main.maxTilesX - 200);
                    int y15 = genRand.Next((int)Main.rockLayer, Main.maxTilesY - 350);
                    int num451 = countTiles(x18, y15, jungle: false, lavaOk: true);
                    while ((num451 >= maxTileCount || num451 < 10) && num450 < 500)
                    {
                        num450++;
                        x18 = genRand.Next(200, Main.maxTilesX - 200);
                        y15 = genRand.Next((int)Main.rockLayer, Main.maxTilesY - 350);
                        num451 = countTiles(x18, y15, jungle: false, lavaOk: true);
                    }
                    if (num450 < 500 && iceCount == 0 && lavaCount == 0 && sandCount == 0)
                    {
                        int wallType2 = ((genRand.Next(2) != 0) ? 63 : 2);
                        Spread.Wall(x18, y15, wallType2);
                    }
                }
            }
            maxTileCount = 1500;
            double num452 = (double)Main.maxTilesX * 0.02;
            for (int num453 = 0; (double)num453 < num452; num453++)
            {
                double num454 = (double)num453 / ((double)Main.maxTilesX * 0.02);
                progress.Set(num454 * 0.33 + 0.66);
                int num455 = 0;
                int x19 = genRand.Next(200, Main.maxTilesX - 200);
                int y16 = genRand.Next((int)Main.worldSurface, GenVars.lavaLine);
                int num456 = 0;
                if (Main.tile[x19, y16].wall == 64)
                {
                    num456 = countTiles(x19, y16, jungle: true);
                }
                while ((num456 >= maxTileCount || num456 < 10) && num455 < 1000)
                {
                    num455++;
                    x19 = genRand.Next(200, Main.maxTilesX - 200);
                    y16 = genRand.Next((int)Main.worldSurface, GenVars.lavaLine);
                    if (!Main.wallHouse[Main.tile[x19, y16].wall] && Main.tile[x19, y16].wall != 244)
                    {
                        num456 = ((Main.tile[x19, y16].wall == 64) ? countTiles(x19, y16, jungle: true) : 0);
                    }
                }
                if (num455 < 1000)
                {
                    Spread.Wall2(x19, y16, 15);
                }
            }
        });
        AddGenerationPass("Jungle Trees", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[83].Value;
            for (int num441 = 0; num441 < Main.maxTilesX; num441++)
            {
                progress.Set((double)num441 / (double)Main.maxTilesX);
                for (int num442 = (int)Main.worldSurface - 1; num442 < Main.maxTilesY - 350; num442++)
                {
                    if (genRand.Next(10) == 0 || drunkWorldGen)
                    {
                        GrowUndergroundTree(num441, num442);
                    }
                }
            }
        });
        AddGenerationPass("Floating Island Houses", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num440 = 0; num440 < GenVars.numIslandHouses; num440++)
            {
                if (!GenVars.skyLake[num440])
                {
                    IslandHouse(GenVars.floatingIslandHouseX[num440], GenVars.floatingIslandHouseY[num440], GenVars.floatingIslandStyle[num440]);
                }
            }
        });
        AddGenerationPass("Quick Cleanup", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            if (notTheBees)
            {
                NotTheBees();
            }
            Main.tileSolid[137] = false;
            Main.tileSolid[130] = false;
            for (int num433 = 20; num433 < Main.maxTilesX - 20; num433++)
            {
                for (int num434 = 20; num434 < Main.maxTilesY - 20; num434++)
                {
                    if ((double)num434 < Main.worldSurface && oceanDepths(num433, num434) && Main.tile[num433, num434].type == 53 && Main.tile[num433, num434].active())
                    {
                        if (Main.tile[num433, num434].bottomSlope())
{
                            Main.tile[num433, num434].slope(0);
                        }
                        for (int num435 = num434 + 1; num435 < num434 + genRand.Next(4, 7) && (!Main.tile[num433, num435].active() || (Main.tile[num433, num435].type != 397 && Main.tile[num433, num435].type != 53)) && (!Main.tile[num433, num435 + 1].active() || (Main.tile[num433, num435 + 1].type != 397 && Main.tile[num433, num435 + 1].type != 53 && Main.tile[num433, num435 + 1].type != 495)) && (!Main.tile[num433, num435 + 2].active() || (Main.tile[num433, num435 + 2].type != 397 && Main.tile[num433, num435 + 2].type != 53 && Main.tile[num433, num435 + 2].type != 495)); num435++)
{
                            Main.tile[num433, num435].type = 0;
                            Main.tile[num433, num435].active(active: true);
                            Main.tile[num433, num435].halfBrick(halfBrick: false);
                            Main.tile[num433, num435].slope(0);
                        }
                    }
                    if (Main.tile[num433, num434].wall == 187 || Main.tile[num433, num434].wall == 216)
                    {
                        if (Main.tile[num433, num434].type == 59 || Main.tile[num433, num434].type == 123 || Main.tile[num433, num434].type == 224)
{
                            Main.tile[num433, num434].type = 397;
                        }
                        if (Main.tile[num433, num434].type == 368 || Main.tile[num433, num434].type == 367)
{
                            Main.tile[num433, num434].type = 397;
                        }
                        if ((double)num434 <= Main.rockLayer)
{
                            Main.tile[num433, num434].liquid = 0;
                        }
                        else if (Main.tile[num433, num434].liquid > 0)
{
                            Main.tile[num433, num434].liquid = byte.MaxValue;
                            Main.tile[num433, num434].lava(lava: true);
                        }
                    }
                    if ((double)num434 < Main.worldSurface && Main.tile[num433, num434].active() && Main.tile[num433, num434].type == 53 && Main.tile[num433, num434 + 1].wall == 0 && !SolidTile(num433, num434 + 1))
                    {
                        ushort num436 = 0;
                        int num437 = 3;
                        for (int num438 = num433 - num437; num438 <= num433 + num437; num438++)
{
                            for (int num439 = num434 - num437; num439 <= num434 + num437; num439++)
{
                                if (Main.tile[num438, num439].wall > 0)
{
                                    num436 = Main.tile[num438, num439].wall;
                                    break;
                                }
                            }
                        }
                        if (num436 > 0)
{
                            Main.tile[num433, num434 + 1].wall = num436;
                            if (Main.tile[num433, num434].wall == 0)
{
                                Main.tile[num433, num434].wall = num436;
                            }
                        }
                    }
                    if (Main.tile[num433, num434].type != 19 && TileID.Sets.CanBeClearedDuringGeneration[Main.tile[num433, num434].type])
                    {
                        if (Main.tile[num433, num434].topSlope() || Main.tile[num433, num434].halfBrick())
{
                            if (Main.tile[num433, num434].type != 225 || !Main.tile[num433, num434].halfBrick())
{
                                if (!SolidTile(num433, num434 + 1))
{
                                    Main.tile[num433, num434].active(active: false);
                                }
                                if (Main.tile[num433 + 1, num434].type == 137 || Main.tile[num433 - 1, num434].type == 137)
{
                                    Main.tile[num433, num434].active(active: false);
                                }
                            }
                        }
                        else if (Main.tile[num433, num434].bottomSlope())
{
                            if (!SolidTile(num433, num434 - 1))
{
                                Main.tile[num433, num434].active(active: false);
                            }
                            if (Main.tile[num433 + 1, num434].type == 137 || Main.tile[num433 - 1, num434].type == 137)
{
                                Main.tile[num433, num434].active(active: false);
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Pots", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            Main.tileSolid[137] = true;
            Main.tileSolid[130] = true;
            progress.Message = Lang.gen[35].Value;
            if (noTrapsWorldGen)
            {
                Main.tileSolid[138] = true;
                int num421 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0004);
                if (remixWorldGen)
                {
                    num421 /= 2;
                }
                for (int num422 = 0; num422 < num421; num422++)
                {
                    int num423 = genRand.Next(50, Main.maxTilesX - 50);
                    int num424;
                    for (num424 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 250); !Main.tile[num423, num424].active() && num424 < Main.maxTilesY - 250; num424++)
                    {
                    }
                    num424--;
                    if (!Main.tile[num423, num424].shimmer())
                    {
                        PlaceTile(num423, num424, 138, mute: true);
                        PlaceTile(num423 + 2, num424, 138, mute: true);
                        PlaceTile(num423 + 1, num424 - 2, 138, mute: true);
                    }
                }
                Main.tileSolid[138] = false;
            }
            double num425 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.0008;
            if (Main.starGame)
            {
                num425 *= Main.starGameMath(0.2);
            }
            for (int num426 = 0; (double)num426 < num425; num426++)
            {
                double num427 = (double)num426 / num425;
                progress.Set(num427);
                bool flag25 = false;
                int num428 = 0;
                while (!flag25)
                {
                    int num429 = genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY - 10);
                    if (num427 > 0.93)
                    {
                        num429 = Main.maxTilesY - 150;
                    }
                    else if (num427 > 0.75)
                    {
                        num429 = (int)GenVars.worldSurfaceLow;
                    }
                    int x16 = genRand.Next(20, Main.maxTilesX - 20);
                    bool flag26 = false;
                    for (int num430 = num429; num430 < Main.maxTilesY - 20; num430++)
                    {
                        if (!flag26)
{
                            if (Main.tile[x16, num430].active() && Main.tileSolid[Main.tile[x16, num430].type] && !Main.tile[x16, num430 - 1].lava() && !Main.tile[x16, num430 - 1].shimmer())
{
                                flag26 = true;
                            }
                        }
                        else if (!((double)num430 < Main.worldSurface) || Main.tile[x16, num430].wall != 0)
{
                            int style = genRand.Next(0, 4);
                            int num431 = 0;
                            int num432 = 0;
                            if (num430 < Main.maxTilesY - 5)
{
                                num431 = Main.tile[x16, num430 + 1].type;
                                num432 = Main.tile[x16, num430].wall;
                            }
                            if (num431 == 147 || num431 == 161 || num431 == 162)
{
                                style = genRand.Next(4, 7);
                            }
                            if (num431 == 60)
{
                                style = genRand.Next(7, 10);
                            }
                            if (Main.wallDungeon[Main.tile[x16, num430].wall])
{
                                style = genRand.Next(10, 13);
                            }
                            if (num431 == 41 || num431 == 43 || num431 == 44 || num431 == 481 || num431 == 482 || num431 == 483)
{
                                style = genRand.Next(10, 13);
                            }
                            if (num431 == 22 || num431 == 23 || num431 == 25)
{
                                style = genRand.Next(16, 19);
                            }
                            if (num431 == 199 || num431 == 203 || num431 == 204 || num431 == 200)
{
                                style = genRand.Next(22, 25);
                            }
                            if (num431 == 367)
{
                                style = genRand.Next(31, 34);
                            }
                            if (num431 == 226)
{
                                style = genRand.Next(28, 31);
                            }
                            if (num432 == 187 || num432 == 216)
{
                                style = genRand.Next(34, 37);
                            }
                            if (num430 > Main.UnderworldLayer)
{
                                style = genRand.Next(13, 16);
                            }
                            if (!oceanDepths(x16, num430) && !Main.tile[x16, num430].shimmer() && PlacePot(x16, num430, 28, style))
{
                                flag25 = true;
                                break;
                            }
                            num428++;
                            if (num428 >= 10000)
{
                                flag25 = true;
                                break;
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Hellforge", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[36].Value;
            for (int num417 = 0; num417 < Main.maxTilesX / 200; num417++)
            {
                double value2 = (double)num417 / (double)(Main.maxTilesX / 200);
                progress.Set(value2);
                bool flag24 = false;
                int num418 = 0;
                while (!flag24)
                {
                    int num419 = genRand.Next(1, Main.maxTilesX);
                    int num420 = genRand.Next(Main.maxTilesY - 250, Main.maxTilesY - 30);
                    try
                    {
                        if (Main.tile[num419, num420].wall == 13 || Main.tile[num419, num420].wall == 14)
{
                            for (; !Main.tile[num419, num420].active() && num420 < Main.maxTilesY - 20; num420++)
{
                            }
                            num420--;
                            PlaceTile(num419, num420, 77);
                            if (Main.tile[num419, num420].type == 77)
{
                                flag24 = true;
                            }
                            else
{
                                num418++;
                                if (num418 >= 10000)
{
                                    flag24 = true;
                                }
                            }
                        }
                    }
                    catch
                    {
                        num418++;
                        if (num418 >= 10000)
{
                            flag24 = true;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Spreading Grass", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (!notTheBees || remixWorldGen)
            {
                progress.Message = Lang.gen[37].Value;
                for (int num395 = 50; num395 < Main.maxTilesX - 50; num395++)
                {
                    for (int num396 = 50; (double)num396 <= Main.worldSurface; num396++)
                    {
                        if (Main.tile[num395, num396].active())
{
                            int type4 = Main.tile[num395, num396].type;
                            if (Main.tile[num395, num396].active() && type4 == 60)
{
                                for (int num397 = num395 - 1; num397 <= num395 + 1; num397++)
{
                                    for (int num398 = num396 - 1; num398 <= num396 + 1; num398++)
{
                                        if (Main.tile[num397, num398].active() && Main.tile[num397, num398].type == 0)
{
                                            if (!Main.tile[num397, num398 - 1].active())
{
                                                Main.tile[num397, num398].type = 60;
                                            }
                                            else
{
                                                Main.tile[num397, num398].type = 59;
                                            }
                                        }
                                    }
                                }
                            }
                            else if (type4 == 1 || type4 == 40 || TileID.Sets.Ore[type4])
{
                                int num399 = 3;
                                bool flag22 = false;
                                ushort num400 = 0;
                                for (int num401 = num395 - num399; num401 <= num395 + num399; num401++)
{
                                    for (int num402 = num396 - num399; num402 <= num396 + num399; num402++)
{
                                        if (Main.tile[num401, num402].active())
{
                                            if (Main.tile[num401, num402].type == 53 || num400 == 53)
{
                                                num400 = 53;
                                            }
                                            else if (Main.tile[num401, num402].type == 59 || Main.tile[num401, num402].type == 60 || Main.tile[num401, num402].type == 147 || Main.tile[num401, num402].type == 161 || Main.tile[num401, num402].type == 199 || Main.tile[num401, num402].type == 23)
{
                                                num400 = Main.tile[num401, num402].type;
                                            }
                                        }
                                        else if (num402 < num396 && Main.tile[num401, num402].wall == 0)
{
                                            flag22 = true;
                                        }
                                    }
                                }
                                if (flag22)
{
                                    switch (num400)
{
                                    case 23:
                                    case 199:
                                        if (Main.tile[num395, num396 - 1].active())
{
                                            num400 = 0;
                                        }
                                        break;
                                    case 59:
                                    case 60:
                                        if (num395 >= GenVars.jungleMinX && num395 <= GenVars.jungleMaxX)
{
                                            num400 = (ushort)(Main.tile[num395, num396 - 1].active() ? 59u : 60u);
                                        }
                                        break;
                                    }
                                    Main.tile[num395, num396].type = num400;
                                }
                            }
                        }
                    }
                }
                for (int num403 = 10; num403 < Main.maxTilesX - 10; num403++)
                {
                    bool flag23 = true;
                    for (int num404 = 0; (double)num404 < Main.worldSurface - 1.0; num404++)
                    {
                        if (Main.tile[num403, num404].active())
{
                            if (flag23 && Main.tile[num403, num404].type == 0)
{
                                try
{
                                    grassSpread = 0;
                                    SpreadGrass(num403, num404);
                                }
                                catch
{
                                    grassSpread = 0;
                                    SpreadGrass(num403, num404, 0, 2, repeat: false);
                                }
                            }
                            if ((double)num404 > GenVars.worldSurfaceHigh)
{
                                break;
                            }
                            flag23 = false;
                        }
                        else if (Main.tile[num403, num404].wall == 0)
{
                            flag23 = true;
                        }
                    }
                }
                if (remixWorldGen)
                {
                    for (int num405 = 5; num405 < Main.maxTilesX - 5; num405++)
                    {
                        for (int num406 = (int)GenVars.rockLayerLow + genRand.Next(-1, 2); num406 < Main.maxTilesY - 200; num406++)
{
                            if (Main.tile[num405, num406].type == 0 && Main.tile[num405, num406].active() && (!Main.tile[num405 - 1, num406 - 1].active() || !Main.tile[num405, num406 - 1].active() || !Main.tile[num405 + 1, num406 - 1].active() || !Main.tile[num405 - 1, num406].active() || !Main.tile[num405 + 1, num406].active() || !Main.tile[num405 - 1, num406 + 1].active() || !Main.tile[num405, num406 + 1].active() || !Main.tile[num405 + 1, num406 + 1].active()))
{
                                Main.tile[num405, num406].type = 2;
                            }
                        }
                    }
                    for (int num407 = 5; num407 < Main.maxTilesX - 5; num407++)
                    {
                        for (int num408 = (int)GenVars.rockLayerLow + genRand.Next(-1, 2); num408 < Main.maxTilesY - 200; num408++)
{
                            if (Main.tile[num407, num408].type == 2 && !Main.tile[num407, num408 - 1].active() && genRand.Next(20) == 0)
{
                                PlaceTile(num407, num408 - 1, 27, mute: true);
                            }
                        }
                    }
                    int conversionType = 1;
                    if (crimson)
                    {
                        conversionType = 4;
                    }
                    int num409 = Main.maxTilesX / 7;
                    for (int num410 = 10; num410 < Main.maxTilesX - 10; num410++)
                    {
                        for (int num411 = 10; num411 < Main.maxTilesY - 10; num411++)
{
                            if ((double)num411 < Main.worldSurface + (double)genRand.Next(3) || num410 < num409 + genRand.Next(3) || num410 >= Main.maxTilesX - num409 - genRand.Next(3))
{
                                if (drunkWorldGen)
{
                                    if (GenVars.crimsonLeft)
{
                                        if (num410 < Main.maxTilesX / 2 + genRand.Next(-2, 3))
{
                                            Convert(num410, num411, 4, 1);
                                        }
                                        else
{
                                            Convert(num410, num411, 1, 1);
                                        }
                                    }
                                    else if (num410 < Main.maxTilesX / 2 + genRand.Next(-2, 3))
{
                                        Convert(num410, num411, 1, 1);
                                    }
                                    else
{
                                        Convert(num410, num411, 4, 1);
                                    }
                                }
                                else
{
                                    Convert(num410, num411, conversionType, 1);
                                }
                                Main.tile[num410, num411].color(0);
                                Main.tile[num410, num411].wallColor(0);
                            }
                        }
                    }
                    if (remixWorldGen)
                    {
                        Main.tileSolid[225] = true;
                        int num412 = (int)((double)Main.maxTilesX * 0.31);
                        int num413 = (int)((double)Main.maxTilesX * 0.69);
                        _ = Main.maxTilesY;
                        int num414 = Main.maxTilesY - 135;
                        _ = Main.maxTilesY;
                        Liquid.QuickWater(-2);
                        for (int num415 = num412; num415 < num413 + 15; num415++)
{
                            for (int num416 = Main.maxTilesY - 200; num416 < num414; num416++)
{
                                Main.tile[num415, num416].liquid = 0;
                            }
                        }
                        Main.tileSolid[225] = false;
                        Main.tileSolid[484] = false;
                    }
                }
            }
        });
        AddGenerationPass("Surface Ore and Stone", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            int num386 = genRand.Next(Main.maxTilesX * 5 / 4200, Main.maxTilesX * 10 / 4200);
            for (int num387 = 0; num387 < num386; num387++)
            {
                int num388 = Main.maxTilesX / 420;
                while (num388 > 0)
                {
                    num388--;
                    int num389 = genRand.Next(beachDistance, Main.maxTilesX - beachDistance);
                    while ((double)num389 >= (double)Main.maxTilesX * 0.48 && (double)num389 <= (double)Main.maxTilesX * 0.52)
                    {
                        num389 = genRand.Next(beachDistance, Main.maxTilesX - beachDistance);
                    }
                    int y12 = genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurface);
                    bool flag20 = false;
                    for (int num390 = 0; num390 < GenVars.numOrePatch; num390++)
                    {
                        if (Math.Abs(num389 - GenVars.orePatchX[num390]) < 200)
{
                            flag20 = true;
                        }
                    }
                    if (!flag20 && OrePatch(num389, y12))
                    {
                        if (GenVars.numOrePatch < GenVars.maxOrePatch - 1)
{
                            GenVars.orePatchX[GenVars.numOrePatch] = num389;
                            GenVars.numOrePatch++;
                        }
                        break;
                    }
                }
            }
            num386 = genRand.Next(1, Main.maxTilesX * 7 / 4200);
            for (int num391 = 0; num391 < num386; num391++)
            {
                int num392 = Main.maxTilesX / 420;
                while (num392 > 0)
                {
                    num392--;
                    int num393 = genRand.Next(beachDistance, Main.maxTilesX - beachDistance);
                    while ((double)num393 >= (double)Main.maxTilesX * 0.47 && (double)num393 <= (double)Main.maxTilesX * 0.53)
                    {
                        num393 = genRand.Next(beachDistance, Main.maxTilesX - beachDistance);
                    }
                    int y13 = genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurface);
                    bool flag21 = false;
                    for (int num394 = 0; num394 < GenVars.numOrePatch; num394++)
                    {
                        if (Math.Abs(num393 - GenVars.orePatchX[num394]) < 100)
{
                            flag21 = true;
                        }
                    }
                    if (!flag21 && StonePatch(num393, y13))
                    {
                        break;
                    }
                }
            }
        });
        AddGenerationPass("Place Fallen Log", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[85].Value;
            int num372 = Main.maxTilesX / 2100;
            num372 = ((!remixWorldGen) ? (num372 + genRand.Next(-1, 2)) : (num372 + genRand.Next(0, 2)));
            for (int num373 = 0; num373 < num372; num373++)
            {
                progress.Set((double)num373 / (double)num372);
                int num374 = beachDistance + 20;
                int num375 = 50000;
                int num376 = 5000;
                while (num375 > 0)
                {
                    num375--;
                    int num377 = genRand.Next(num374, Main.maxTilesX - num374);
                    int num378 = genRand.Next(10, (int)Main.worldSurface);
                    if (remixWorldGen)
                    {
                        num378 = genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY - 350);
                    }
                    bool flag18 = false;
                    if (num375 < num376)
                    {
                        flag18 = true;
                    }
                    if (num375 > num376 / 2)
                    {
                        while ((double)num377 > (double)Main.maxTilesX * 0.4 && (double)num377 < (double)Main.maxTilesX * 0.6)
{
                            num377 = genRand.Next(num374, Main.maxTilesX - num374);
                        }
                    }
                    if (!Main.tile[num377, num378].active() && Main.tile[num377, num378].wall == 0)
                    {
                        bool flag19 = true;
                        if (remixWorldGen)
{
                            for (; !Main.tile[num377, num378].active() && Main.tile[num377, num378].wall == 0 && num378 <= Main.maxTilesY - 350; num378++)
{
                            }
                        }
                        else
{
                            for (; !Main.tile[num377, num378].active() && Main.tile[num377, num378].wall == 0 && (double)num378 <= Main.worldSurface; num378++)
{
                            }
                        }
                        if ((double)num378 > Main.worldSurface - 10.0 && !remixWorldGen)
{
                            flag19 = false;
                        }
                        else if (!flag18)
{
                            int num379 = 50;
                            for (int num380 = num377 - num379; num380 < num377 + num379; num380++)
{
                                if (num380 > 10 && num380 < Main.maxTilesX - 10)
{
                                    for (int num381 = num378 - num379; num381 < num378 + num379; num381++)
{
                                        if (num381 > 10 && num381 < Main.maxTilesY - 10)
{
                                            int type3 = Main.tile[num380, num381].type;
                                            switch (type3)
{
                                            case 189:
                                                flag19 = false;
                                                break;
                                            case 53:
                                                flag19 = false;
                                                break;
                                            default:
                                                if (Main.tileDungeon[type3])
{
                                                    flag19 = false;
                                                }
                                                else if (TileID.Sets.Crimson[type3])
{
                                                    flag19 = false;
                                                }
                                                else if (TileID.Sets.Corrupt[type3])
{
                                                    flag19 = false;
                                                }
                                                break;
                                            }
                                        }
                                    }
                                }
                            }
                            if (flag19)
{
                                int num382 = 10;
                                int num383 = 10;
                                for (int num384 = num377 - num382; num384 < num377 + num382; num384++)
{
                                    for (int num385 = num378 - num383; num385 < num378 - 1; num385++)
{
                                        if (Main.tile[num384, num385].active() && Main.tileSolid[Main.tile[num384, num385].type])
{
                                            flag19 = false;
                                        }
                                        if (Main.tile[num384, num385].wall != 0)
{
                                            flag19 = false;
                                        }
                                    }
                                }
                            }
                        }
                        if (flag19 && (Main.tile[num377, num378 - 1].liquid == 0 || num375 < num376 / 5) && (Main.tile[num377, num378].type == 2 || (notTheBees && Main.tile[num377, num378].type == 60)) && (Main.tile[num377 - 1, num378].type == 2 || (notTheBees && Main.tile[num377 - 1, num378].type == 60)) && (Main.tile[num377 + 1, num378].type == 2 || (notTheBees && Main.tile[num377 + 1, num378].type == 60)))
{
                            num378--;
                            PlaceTile(num377, num378, 488);
                            if (Main.tile[num377, num378].active() && Main.tile[num377, num378].type == 488)
{
                                if (genRand.Next(2) == 0)
{
                                    GenVars.logX = num377;
                                    GenVars.logY = num378;
                                }
                                num375 = -1;
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Traps", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (!notTheBees || noTrapsWorldGen || remixWorldGen)
            {
                placingTraps = true;
                progress.Message = Lang.gen[34].Value;
                if (noTrapsWorldGen)
                {
                    progress.Message = Lang.gen[91].Value;
                }
                double num358 = (double)Main.maxTilesX * 0.05;
                if (noTrapsWorldGen)
                {
                    num358 = ((!tenthAnniversaryWorldGen && !notTheBees) ? (num358 * 100.0) : (num358 * 5.0));
                }
                else if (getGoodWorldGen)
                {
                    num358 *= 1.5;
                }
                if (Main.starGame)
                {
                    num358 *= Main.starGameMath(0.2);
                }
                for (int num359 = 0; (double)num359 < num358; num359++)
                {
                    progress.Set((double)num359 / num358 / 2.0);
                    for (int num360 = 0; num360 < 1150; num360++)
                    {
                        if (noTrapsWorldGen)
{
                            int num361 = genRand.Next(50, Main.maxTilesX - 50);
                            int num362 = genRand.Next(50, Main.maxTilesY - 50);
                            if (remixWorldGen)
{
                                num362 = genRand.Next(50, Main.maxTilesY - 210);
                            }
                            if (((double)num362 > Main.worldSurface || Main.tile[num361, num362].wall > 0) && placeTrap(num361, num362))
{
                                break;
                            }
                        }
                        else
{
                            int num363 = genRand.Next(200, Main.maxTilesX - 200);
                            int num364 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 210);
                            while (oceanDepths(num363, num364))
{
                                num363 = genRand.Next(200, Main.maxTilesX - 200);
                                num364 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 210);
                            }
                            if (Main.tile[num363, num364].wall == 0 && placeTrap(num363, num364))
{
                                break;
                            }
                        }
                    }
                }
                if (noTrapsWorldGen)
                {
                    num358 = Main.maxTilesX * 3;
                    if (Main.remixWorld)
                    {
                        num358 = Main.maxTilesX / 3;
                    }
                    if (Main.starGame)
                    {
                        num358 *= Main.starGameMath(0.2);
                    }
                    for (int num365 = 0; (double)num365 < num358; num365++)
                    {
                        if (Main.remixWorld)
{
                            placeTNTBarrel(genRand.Next(50, Main.maxTilesX - 50), genRand.Next((int)Main.worldSurface, (int)((double)(Main.maxTilesY - 350) + Main.rockLayer) / 2));
                        }
                        else
{
                            placeTNTBarrel(genRand.Next(50, Main.maxTilesX - 50), genRand.Next((int)Main.rockLayer, Main.maxTilesY - 200));
                        }
                    }
                }
                num358 = (double)Main.maxTilesX * 0.003;
                if (noTrapsWorldGen)
                {
                    num358 *= 5.0;
                }
                else if (getGoodWorldGen)
                {
                    num358 *= 1.5;
                }
                for (int num366 = 0; (double)num366 < num358; num366++)
                {
                    progress.Set((double)num366 / num358 / 2.0 + 0.5);
                    for (int num367 = 0; num367 < 20000; num367++)
                    {
                        int num368 = genRand.Next((int)((double)Main.maxTilesX * 0.15), (int)((double)Main.maxTilesX * 0.85));
                        int num369 = genRand.Next((int)Main.worldSurface + 20, Main.maxTilesY - 210);
                        if (Main.tile[num368, num369].wall == 187 && PlaceSandTrap(num368, num369))
{
                            break;
                        }
                    }
                }
                if (drunkWorldGen && !noTrapsWorldGen && !notTheBees)
                {
                    for (int num370 = 0; num370 < 8; num370++)
                    {
                        progress.Message = Lang.gen[34].Value;
                        num358 = 100.0;
                        for (int num371 = 0; (double)num371 < num358; num371++)
{
                            progress.Set((double)num371 / num358);
                            Thread.Sleep(10);
                        }
                    }
                }
                if (noTrapsWorldGen)
                {
                    Main.tileSolid[138] = true;
                }
                placingTraps = false;
            }
        });
        AddGenerationPass("Piles", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[89].Value;
            Main.tileSolid[229] = false;
            Main.tileSolid[190] = false;
            Main.tileSolid[196] = false;
            Main.tileSolid[189] = false;
            Main.tileSolid[202] = false;
            Main.tileSolid[460] = false;
            Main.tileSolid[484] = false;
            if (noTrapsWorldGen)
            {
                Main.tileSolid[138] = false;
            }
            for (int num300 = 0; (double)num300 < (double)Main.maxTilesX * 0.06; num300++)
            {
                int num301 = Main.maxTilesX / 2;
                bool flag11 = false;
                while (!flag11 && num301 > 0)
                {
                    num301--;
                    int num302 = genRand.Next(25, Main.maxTilesX - 25);
                    int num303 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300);
                    while (oceanDepths(num302, num303))
                    {
                        num302 = genRand.Next(25, Main.maxTilesX - 25);
                        num303 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300);
                    }
                    if (!Main.tile[num302, num303].active())
                    {
                        int num304 = 186;
                        for (; !Main.tile[num302, num303 + 1].active() && num303 < Main.maxTilesY - 5; num303++)
{
                        }
                        int num305 = genRand.Next(22);
                        if (num305 >= 16 && num305 <= 22)
{
                            num305 = genRand.Next(22);
                        }
                        if ((Main.tile[num302, num303 + 1].type == 0 || Main.tile[num302, num303 + 1].type == 1 || Main.tileMoss[Main.tile[num302, num303 + 1].type]) && genRand.Next(5) == 0)
{
                            num305 = genRand.Next(23, 29);
                            num304 = 187;
                        }
                        if (num303 > Main.maxTilesY - 300 || Main.wallDungeon[Main.tile[num302, num303].wall] || Main.tile[num302, num303 + 1].type == 30 || Main.tile[num302, num303 + 1].type == 19 || Main.tile[num302, num303 + 1].type == 25 || Main.tile[num302, num303 + 1].type == 203)
{
                            num305 = genRand.Next(7);
                            num304 = 186;
                        }
                        if (Main.tile[num302, num303 + 1].type == 147 || Main.tile[num302, num303 + 1].type == 161 || Main.tile[num302, num303 + 1].type == 162)
{
                            num305 = genRand.Next(26, 32);
                            num304 = 186;
                        }
                        if (Main.tile[num302, num303 + 1].type == 60)
{
                            num304 = 187;
                            num305 = genRand.Next(6);
                        }
                        if ((Main.tile[num302, num303 + 1].type == 57 || Main.tile[num302, num303 + 1].type == 58) && genRand.Next(3) < 2)
{
                            num304 = 187;
                            num305 = genRand.Next(6, 9);
                        }
                        if (Main.tile[num302, num303 + 1].type == 226)
{
                            num304 = 187;
                            num305 = genRand.Next(18, 23);
                        }
                        if (Main.tile[num302, num303 + 1].type == 70)
{
                            num305 = genRand.Next(32, 35);
                            num304 = 186;
                        }
                        if (Main.tile[num302, num303 + 1].type == 396 || Main.tile[num302, num303 + 1].type == 397 || Main.tile[num302, num303 + 1].type == 404)
{
                            num305 = genRand.Next(29, 35);
                            num304 = 187;
                        }
                        if (Main.tile[num302, num303 + 1].type == 368)
{
                            num305 = genRand.Next(35, 41);
                            num304 = 187;
                        }
                        if (Main.tile[num302, num303 + 1].type == 367)
{
                            num305 = genRand.Next(41, 47);
                            num304 = 187;
                        }
                        if (num304 == 186 && num305 >= 7 && num305 <= 15 && genRand.Next(75) == 0)
{
                            num304 = 187;
                            num305 = 17;
                        }
                        if (Main.wallDungeon[Main.tile[num302, num303].wall] && genRand.Next(3) != 0)
{
                            flag11 = true;
                        }
                        else
{
                            if (!Main.tile[num302, num303].shimmer())
{
                                PlaceTile(num302, num303, num304, mute: true, forced: false, -1, num305);
                            }
                            if (Main.tile[num302, num303].type == 186 || Main.tile[num302, num303].type == 187)
{
                                flag11 = true;
                            }
                            if (flag11 && num304 == 186 && num305 <= 7)
{
                                int num306 = genRand.Next(1, 5);
                                for (int num307 = 0; num307 < num306; num307++)
{
                                    int num308 = num302 + genRand.Next(-10, 11);
                                    int num309 = num303 - genRand.Next(5);
                                    if (!Main.tile[num308, num309].active())
{
                                        for (; !Main.tile[num308, num309 + 1].active() && num309 < Main.maxTilesY - 5; num309++)
{
                                        }
                                        int x12 = genRand.Next(12, 36);
                                        PlaceSmallPile(num308, num309, x12, 0, 185);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            for (int num310 = 0; (double)num310 < (double)Main.maxTilesX * 0.01; num310++)
            {
                int num311 = Main.maxTilesX / 2;
                bool flag12 = false;
                while (!flag12 && num311 > 0)
                {
                    num311--;
                    int num312 = genRand.Next(25, Main.maxTilesX - 25);
                    int num313 = genRand.Next(Main.maxTilesY - 300, Main.maxTilesY - 10);
                    if (!Main.tile[num312, num313].active())
                    {
                        int num314 = 186;
                        for (; !Main.tile[num312, num313 + 1].active() && num313 < Main.maxTilesY - 5; num313++)
{
                        }
                        int num315 = genRand.Next(22);
                        if (num315 >= 16 && num315 <= 22)
{
                            num315 = genRand.Next(22);
                        }
                        if (num313 > Main.maxTilesY - 300 || Main.wallDungeon[Main.tile[num312, num313].wall] || Main.tile[num312, num313 + 1].type == 30 || Main.tile[num312, num313 + 1].type == 19)
{
                            num315 = genRand.Next(7);
                        }
                        if ((Main.tile[num312, num313 + 1].type == 57 || Main.tile[num312, num313 + 1].type == 58) && genRand.Next(3) < 2)
{
                            num314 = 187;
                            num315 = genRand.Next(6, 9);
                        }
                        if (Main.tile[num312, num313 + 1].type == 147 || Main.tile[num312, num313 + 1].type == 161 || Main.tile[num312, num313 + 1].type == 162)
{
                            num315 = genRand.Next(26, 32);
                        }
                        PlaceTile(num312, num313, num314, mute: true, forced: false, -1, num315);
                        if (Main.tile[num312, num313].type == 186 || Main.tile[num312, num313].type == 187)
{
                            flag12 = true;
                        }
                        if (flag12 && num314 == 186 && num315 <= 7)
{
                            int num316 = genRand.Next(1, 5);
                            for (int num317 = 0; num317 < num316; num317++)
{
                                int num318 = num312 + genRand.Next(-10, 11);
                                int num319 = num313 - genRand.Next(5);
                                if (!Main.tile[num318, num319].active())
{
                                    for (; !Main.tile[num318, num319 + 1].active() && num319 < Main.maxTilesY - 5; num319++)
{
                                    }
                                    int x13 = genRand.Next(12, 36);
                                    PlaceSmallPile(num318, num319, x13, 0, 185);
                                }
                            }
                        }
                    }
                }
            }
            for (int num320 = 0; (double)num320 < (double)Main.maxTilesX * 0.003; num320++)
            {
                int num321 = Main.maxTilesX / 2;
                bool flag13 = false;
                while (!flag13 && num321 > 0)
                {
                    num321--;
                    int num322 = 186;
                    int num323 = genRand.Next(25, Main.maxTilesX - 25);
                    int num324 = genRand.Next(10, (int)Main.worldSurface);
                    while (oceanDepths(num323, num324))
                    {
                        num323 = genRand.Next(25, Main.maxTilesX - 25);
                        num324 = genRand.Next(10, (int)Main.worldSurface);
                    }
                    if (!Main.tile[num323, num324].active())
                    {
                        for (; !Main.tile[num323, num324 + 1].active() && num324 < Main.maxTilesY - 5; num324++)
{
                        }
                        int num325 = genRand.Next(7, 13);
                        if (num324 > Main.maxTilesY - 300 || Main.wallDungeon[Main.tile[num323, num324].wall] || Main.tile[num323, num324 + 1].type == 30 || Main.tile[num323, num324 + 1].type == 19 || Main.tile[num323, num324 + 1].type == 25 || Main.tile[num323, num324 + 1].type == 203 || Main.tile[num323, num324 + 1].type == 234 || Main.tile[num323, num324 + 1].type == 112)
{
                            num325 = -1;
                        }
                        if (Main.tile[num323, num324 + 1].type == 147 || Main.tile[num323, num324 + 1].type == 161 || Main.tile[num323, num324 + 1].type == 162)
{
                            num325 = genRand.Next(26, 32);
                        }
                        if (Main.tile[num323, num324 + 1].type == 53)
{
                            num322 = 187;
                            num325 = genRand.Next(52, 55);
                        }
                        if (Main.tile[num323, num324 + 1].type == 2 || Main.tile[num323 - 1, num324 + 1].type == 2 || Main.tile[num323 + 1, num324 + 1].type == 2)
{
                            num322 = 187;
                            num325 = genRand.Next(14, 17);
                        }
                        if (Main.tile[num323, num324 + 1].type == 151 || Main.tile[num323, num324 + 1].type == 274)
{
                            num322 = 186;
                            num325 = genRand.Next(7);
                        }
                        if (num325 >= 0)
{
                            PlaceTile(num323, num324, num322, mute: true, forced: false, -1, num325);
                        }
                        if (Main.tile[num323, num324].type == num322)
{
                            flag13 = true;
                        }
                    }
                }
            }
            for (int num326 = 0; (double)num326 < (double)Main.maxTilesX * 0.0035; num326++)
            {
                int num327 = Main.maxTilesX / 2;
                bool flag14 = false;
                while (!flag14 && num327 > 0)
                {
                    num327--;
                    int num328 = genRand.Next(25, Main.maxTilesX - 25);
                    int num329 = genRand.Next(10, (int)Main.worldSurface);
                    if (!Main.tile[num328, num329].active() && Main.tile[num328, num329].wall > 0)
                    {
                        int num330 = 186;
                        for (; !Main.tile[num328, num329 + 1].active() && num329 < Main.maxTilesY - 5; num329++)
{
                        }
                        int num331 = genRand.Next(7, 13);
                        if (num329 > Main.maxTilesY - 300 || Main.wallDungeon[Main.tile[num328, num329].wall] || Main.tile[num328, num329 + 1].type == 30 || Main.tile[num328, num329 + 1].type == 19)
{
                            num331 = -1;
                        }
                        if (Main.tile[num328, num329 + 1].type == 25)
{
                            num331 = genRand.Next(7);
                        }
                        if (Main.tile[num328, num329 + 1].type == 147 || Main.tile[num328, num329 + 1].type == 161 || Main.tile[num328, num329 + 1].type == 162)
{
                            num331 = genRand.Next(26, 32);
                        }
                        if (Main.tile[num328, num329 + 1].type == 2 || Main.tile[num328 - 1, num329 + 1].type == 2 || Main.tile[num328 + 1, num329 + 1].type == 2)
{
                            num330 = 187;
                            num331 = genRand.Next(14, 17);
                        }
                        if (Main.tile[num328, num329 + 1].type == 151 || Main.tile[num328, num329 + 1].type == 274)
{
                            num330 = 186;
                            num331 = genRand.Next(7);
                        }
                        if (num331 >= 0)
{
                            PlaceTile(num328, num329, num330, mute: true, forced: false, -1, num331);
                        }
                        if (Main.tile[num328, num329].type == num330)
{
                            flag14 = true;
                        }
                        if (flag14 && num331 <= 7)
{
                            int num332 = genRand.Next(1, 5);
                            for (int num333 = 0; num333 < num332; num333++)
{
                                int num334 = num328 + genRand.Next(-10, 11);
                                int num335 = num329 - genRand.Next(5);
                                if (!Main.tile[num334, num335].active())
{
                                    for (; !Main.tile[num334, num335 + 1].active() && num335 < Main.maxTilesY - 5; num335++)
{
                                    }
                                    int x14 = genRand.Next(12, 36);
                                    PlaceSmallPile(num334, num335, x14, 0, 185);
                                }
                            }
                        }
                    }
                }
            }
            for (int num336 = 0; (double)num336 < (double)Main.maxTilesX * 0.6; num336++)
            {
                int num337 = Main.maxTilesX / 2;
                bool flag15 = false;
                while (!flag15 && num337 > 0)
                {
                    num337--;
                    int num338 = genRand.Next(25, Main.maxTilesX - 25);
                    int num339 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 20);
                    if (Main.tile[num338, num339].wall == 87 && genRand.Next(2) == 0)
                    {
                        num338 = genRand.Next(25, Main.maxTilesX - 25);
                        num339 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 20);
                    }
                    while (oceanDepths(num338, num339))
                    {
                        num338 = genRand.Next(25, Main.maxTilesX - 25);
                        num339 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 20);
                    }
                    if (!Main.tile[num338, num339].active())
                    {
                        for (; !Main.tile[num338, num339 + 1].active() && num339 < Main.maxTilesY - 5; num339++)
{
                        }
                        int num340 = genRand.Next(2);
                        int num341 = genRand.Next(36);
                        if (num341 >= 28 && num341 <= 35)
{
                            num341 = genRand.Next(36);
                        }
                        if (num340 == 1)
{
                            num341 = genRand.Next(25);
                            if (num341 >= 16 && num341 <= 24)
{
                                num341 = genRand.Next(25);
                            }
                        }
                        if (num339 > Main.maxTilesY - 300)
{
                            if (num340 == 0)
{
                                num341 = genRand.Next(12, 28);
                            }
                            if (num340 == 1)
{
                                num341 = genRand.Next(6, 16);
                            }
                        }
                        if (Main.wallDungeon[Main.tile[num338, num339].wall] || Main.tile[num338, num339 + 1].type == 30 || Main.tile[num338, num339 + 1].type == 19 || Main.tile[num338, num339 + 1].type == 25 || Main.tile[num338, num339 + 1].type == 203 || Main.tile[num338, num339].wall == 87)
{
                            if (num340 == 0 && num341 < 12)
{
                                num341 += 12;
                            }
                            if (num340 == 1 && num341 < 6)
{
                                num341 += 6;
                            }
                            if (num340 == 1 && num341 >= 17)
{
                                num341 -= 10;
                            }
                        }
                        if (Main.tile[num338, num339 + 1].type == 147 || Main.tile[num338, num339 + 1].type == 161 || Main.tile[num338, num339 + 1].type == 162)
{
                            if (num340 == 0 && num341 < 12)
{
                                num341 += 36;
                            }
                            if (num340 == 1 && num341 >= 20)
{
                                num341 += 6;
                            }
                            if (num340 == 1 && num341 < 6)
{
                                num341 += 25;
                            }
                        }
                        if (Main.tile[num338, num339 + 1].type == 151 || Main.tile[num338, num339 + 1].type == 274)
{
                            if (num340 == 0)
{
                                num341 = genRand.Next(12, 28);
                            }
                            if (num340 == 1)
{
                                num341 = genRand.Next(12, 19);
                            }
                        }
                        if (Main.tile[num338, num339 + 1].type == 368)
{
                            if (num340 == 0)
{
                                num341 = genRand.Next(60, 66);
                            }
                            if (num340 == 1)
{
                                num341 = genRand.Next(47, 53);
                            }
                        }
                        if (Main.tile[num338, num339 + 1].type == 367)
{
                            if (num340 == 0)
{
                                num341 = genRand.Next(66, 72);
                            }
                            if (num340 == 1)
{
                                num341 = genRand.Next(53, 59);
                            }
                        }
                        if (Main.wallDungeon[Main.tile[num338, num339].wall] && genRand.Next(3) != 0)
{
                            flag15 = true;
                        }
                        else if (!Main.tile[num338, num339].shimmer())
{
                            flag15 = PlaceSmallPile(num338, num339, num341, num340, 185);
                        }
                        if (flag15 && num340 == 1 && num341 >= 6 && num341 <= 15)
{
                            int num342 = genRand.Next(1, 5);
                            for (int num343 = 0; num343 < num342; num343++)
{
                                int num344 = num338 + genRand.Next(-10, 11);
                                int num345 = num339 - genRand.Next(5);
                                if (!Main.tile[num344, num345].active())
{
                                    for (; !Main.tile[num344, num345 + 1].active() && num345 < Main.maxTilesY - 5; num345++)
{
                                    }
                                    int x15 = genRand.Next(12, 36);
                                    PlaceSmallPile(num344, num345, x15, 0, 185);
                                }
                            }
                        }
                    }
                }
            }
            for (int num346 = 0; (double)num346 < (double)Main.maxTilesX * 0.02; num346++)
            {
                int num347 = Main.maxTilesX / 2;
                bool flag16 = false;
                while (!flag16 && num347 > 0)
                {
                    num347--;
                    int num348 = genRand.Next(25, Main.maxTilesX - 25);
                    int num349 = genRand.Next(15, (int)Main.worldSurface);
                    while (oceanDepths(num348, num349))
                    {
                        num348 = genRand.Next(25, Main.maxTilesX - 25);
                        num349 = genRand.Next(15, (int)Main.worldSurface);
                    }
                    if (!Main.tile[num348, num349].active())
                    {
                        for (; !Main.tile[num348, num349 + 1].active() && num349 < Main.maxTilesY - 5; num349++)
{
                        }
                        int num350 = genRand.Next(2);
                        int num351 = genRand.Next(11);
                        if (num350 == 1)
{
                            num351 = genRand.Next(5);
                        }
                        if (Main.tile[num348, num349 + 1].type == 147 || Main.tile[num348, num349 + 1].type == 161 || Main.tile[num348, num349 + 1].type == 162)
{
                            if (num350 == 0 && num351 < 12)
{
                                num351 += 36;
                            }
                            if (num350 == 1 && num351 >= 20)
{
                                num351 += 6;
                            }
                            if (num350 == 1 && num351 < 6)
{
                                num351 += 25;
                            }
                        }
                        if (Main.tile[num348, num349 + 1].type == 2 && num350 == 1)
{
                            num351 = genRand.Next(38, 41);
                        }
                        if (Main.tile[num348, num349 + 1].type == 151 || Main.tile[num348, num349 + 1].type == 274)
{
                            if (num350 == 0)
{
                                num351 = genRand.Next(12, 28);
                            }
                            if (num350 == 1)
{
                                num351 = genRand.Next(12, 19);
                            }
                        }
                        if (!Main.wallDungeon[Main.tile[num348, num349].wall] && Main.tile[num348, num349 + 1].type != 30 && Main.tile[num348, num349 + 1].type != 19 && Main.tile[num348, num349 + 1].type != 41 && Main.tile[num348, num349 + 1].type != 43 && Main.tile[num348, num349 + 1].type != 44 && Main.tile[num348, num349 + 1].type != 481 && Main.tile[num348, num349 + 1].type != 482 && Main.tile[num348, num349 + 1].type != 483 && Main.tile[num348, num349 + 1].type != 45 && Main.tile[num348, num349 + 1].type != 46 && Main.tile[num348, num349 + 1].type != 47 && Main.tile[num348, num349 + 1].type != 175 && Main.tile[num348, num349 + 1].type != 176 && Main.tile[num348, num349 + 1].type != 177 && Main.tile[num348, num349 + 1].type != 53 && Main.tile[num348, num349 + 1].type != 25 && Main.tile[num348, num349 + 1].type != 203)
{
                            flag16 = PlaceSmallPile(num348, num349, num351, num350, 185);
                        }
                    }
                }
            }
            for (int num352 = 0; (double)num352 < (double)Main.maxTilesX * 0.15; num352++)
            {
                int num353 = Main.maxTilesX / 2;
                bool flag17 = false;
                while (!flag17 && num353 > 0)
                {
                    num353--;
                    int num354 = genRand.Next(25, Main.maxTilesX - 25);
                    int num355 = genRand.Next(15, (int)Main.worldSurface);
                    if (!Main.tile[num354, num355].active() && (Main.tile[num354, num355].wall == 2 || Main.tile[num354, num355].wall == 40))
                    {
                        for (; !Main.tile[num354, num355 + 1].active() && num355 < Main.maxTilesY - 5; num355++)
{
                        }
                        int num356 = genRand.Next(2);
                        int num357 = genRand.Next(11);
                        if (num356 == 1)
{
                            num357 = genRand.Next(5);
                        }
                        if (Main.tile[num354, num355 + 1].type == 147 || Main.tile[num354, num355 + 1].type == 161 || Main.tile[num354, num355 + 1].type == 162)
{
                            if (num356 == 0 && num357 < 12)
{
                                num357 += 36;
                            }
                            if (num356 == 1 && num357 >= 20)
{
                                num357 += 6;
                            }
                            if (num356 == 1 && num357 < 6)
{
                                num357 += 25;
                            }
                        }
                        if (Main.tile[num354, num355 + 1].type == 2 && num356 == 1)
{
                            num357 = genRand.Next(38, 41);
                        }
                        if (Main.tile[num354, num355 + 1].type == 151 || Main.tile[num354, num355 + 1].type == 274)
{
                            if (num356 == 0)
{
                                num357 = genRand.Next(12, 28);
                            }
                            if (num356 == 1)
{
                                num357 = genRand.Next(12, 19);
                            }
                        }
                        if ((Main.tile[num354, num355].liquid != byte.MaxValue || Main.tile[num354, num355 + 1].type != 53 || Main.tile[num354, num355].wall != 0) && !Main.wallDungeon[Main.tile[num354, num355].wall] && Main.tile[num354, num355 + 1].type != 30 && Main.tile[num354, num355 + 1].type != 19 && Main.tile[num354, num355 + 1].type != 41 && Main.tile[num354, num355 + 1].type != 43 && Main.tile[num354, num355 + 1].type != 44 && Main.tile[num354, num355 + 1].type != 481 && Main.tile[num354, num355 + 1].type != 482 && Main.tile[num354, num355 + 1].type != 483 && Main.tile[num354, num355 + 1].type != 45 && Main.tile[num354, num355 + 1].type != 46 && Main.tile[num354, num355 + 1].type != 47 && Main.tile[num354, num355 + 1].type != 175 && Main.tile[num354, num355 + 1].type != 176 && Main.tile[num354, num355 + 1].type != 177 && Main.tile[num354, num355 + 1].type != 25 && Main.tile[num354, num355 + 1].type != 203)
{
                            flag17 = PlaceSmallPile(num354, num355, num357, num356, 185);
                        }
                    }
                }
            }
            Main.tileSolid[190] = true;
            Main.tileSolid[192] = true;
            Main.tileSolid[196] = true;
            Main.tileSolid[189] = true;
            Main.tileSolid[202] = true;
            Main.tileSolid[225] = true;
            Main.tileSolid[460] = true;
            Main.tileSolid[138] = true;
        });
        AddGenerationPass("Spawn Point", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            int num291 = 5;
            bool flag10 = true;
            int num292 = Main.maxTilesX / 2;
            if (Main.tenthAnniversaryWorld && !remixWorldGen)
            {
                int num293 = GenVars.beachBordersWidth + 15;
                num292 = ((genRand.Next(2) != 0) ? (Main.maxTilesX - num293) : num293);
            }
            while (flag10)
            {
                int num294 = num292 + genRand.Next(-num291, num291 + 1);
                for (int num295 = 0; num295 < Main.maxTilesY; num295++)
                {
                    if (Main.tile[num294, num295].active())
                    {
                        Main.spawnTileX = num294;
                        Main.spawnTileY = num295;
                        break;
                    }
                }
                flag10 = false;
                num291++;
                if ((double)Main.spawnTileY > Main.worldSurface)
                {
                    flag10 = true;
                }
                if (Main.tile[Main.spawnTileX, Main.spawnTileY - 1].liquid > 0)
                {
                    flag10 = true;
                }
            }
            int num296 = 10;
            while ((double)Main.spawnTileY > Main.worldSurface)
            {
                int num297 = genRand.Next(num292 - num296, num292 + num296);
                for (int num298 = 0; num298 < Main.maxTilesY; num298++)
                {
                    if (Main.tile[num297, num298].active())
                    {
                        Main.spawnTileX = num297;
                        Main.spawnTileY = num298;
                        break;
                    }
                }
                num296++;
            }
            if (remixWorldGen)
            {
                int num299 = Main.maxTilesY - 10;
                while (SolidTile(Main.spawnTileX, num299))
                {
                    num299--;
                }
                Main.spawnTileY = num299 + 1;
            }
        });
        AddGenerationPass("Grass Wall", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            maxTileCount = 3500;
            progress.Set(1.0);
            for (int num279 = 50; num279 < Main.maxTilesX - 50; num279++)
            {
                for (int num280 = 0; (double)num280 < Main.worldSurface - 10.0; num280++)
                {
                    if (genRand.Next(4) == 0)
                    {
                        bool flag8 = false;
                        int num281 = -1;
                        int num282 = -1;
                        if (Main.tile[num279, num280].active() && Main.tile[num279, num280].type == 2 && (Main.tile[num279, num280].wall == 2 || Main.tile[num279, num280].wall == 63))
{
                            for (int num283 = num279 - 1; num283 <= num279 + 1; num283++)
{
                                for (int num284 = num280 - 1; num284 <= num280 + 1; num284++)
{
                                    if (Main.tile[num283, num284].wall == 0 && !SolidTile(num283, num284))
{
                                        flag8 = true;
                                    }
                                }
                            }
                            if (flag8)
{
                                for (int num285 = num279 - 1; num285 <= num279 + 1; num285++)
{
                                    for (int num286 = num280 - 1; num286 <= num280 + 1; num286++)
{
                                        if ((Main.tile[num285, num286].wall == 2 || Main.tile[num285, num286].wall == 15) && !SolidTile(num285, num286))
{
                                            num281 = num285;
                                            num282 = num286;
                                        }
                                    }
                                }
                            }
                        }
                        if (flag8 && num281 > -1 && num282 > -1 && countDirtTiles(num281, num282) < maxTileCount)
{
                            try
{
                                ushort wallType = 63;
                                if (dontStarveWorldGen && genRand.Next(3) != 0)
{
                                    wallType = 62;
                                }
                                Spread.Wall2(num281, num282, wallType);
                            }
                            catch
{
                            }
                        }
                    }
                }
            }
            for (int num287 = 5; num287 < Main.maxTilesX - 5; num287++)
            {
                for (int num288 = 10; (double)num288 < Main.worldSurface - 1.0; num288++)
                {
                    if (Main.tile[num287, num288].wall == 63 && genRand.Next(10) == 0)
                    {
                        Main.tile[num287, num288].wall = 65;
                    }
                    if (Main.tile[num287, num288].active() && Main.tile[num287, num288].type == 0)
                    {
                        bool flag9 = false;
                        for (int num289 = num287 - 1; num289 <= num287 + 1; num289++)
{
                            for (int num290 = num288 - 1; num290 <= num288 + 1; num290++)
{
                                if (Main.tile[num289, num290].wall == 63 || Main.tile[num289, num290].wall == 65)
{
                                    flag9 = true;
                                    break;
                                }
                            }
                        }
                        if (flag9)
{
                            SpreadGrass(num287, num288);
                        }
                    }
                }
            }
        });
        AddGenerationPass("Guide", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_011d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0122: Unknown result type (might be due to invalid IL or missing references)
            //IL_0129: Unknown result type (might be due to invalid IL or missing references)
            //IL_0132: Unknown result type (might be due to invalid IL or missing references)
            //IL_0167: Unknown result type (might be due to invalid IL or missing references)
            //IL_0179: Unknown result type (might be due to invalid IL or missing references)
            //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
            //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
            //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e0: Unknown result type (might be due to invalid IL or missing references)
            //IL_0215: Unknown result type (might be due to invalid IL or missing references)
            //IL_0227: Unknown result type (might be due to invalid IL or missing references)
            //IL_027f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0284: Unknown result type (might be due to invalid IL or missing references)
            //IL_028b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0294: Unknown result type (might be due to invalid IL or missing references)
            //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
            //IL_02db: Unknown result type (might be due to invalid IL or missing references)
            //IL_0333: Unknown result type (might be due to invalid IL or missing references)
            //IL_0338: Unknown result type (might be due to invalid IL or missing references)
            //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
            //IL_03aa: Unknown result type (might be due to invalid IL or missing references)
            //IL_0346: Unknown result type (might be due to invalid IL or missing references)
            //IL_034f: Unknown result type (might be due to invalid IL or missing references)
            //IL_03f2: Unknown result type (might be due to invalid IL or missing references)
            //IL_0404: Unknown result type (might be due to invalid IL or missing references)
            progress.Set(1.0);
            if (Main.tenthAnniversaryWorld)
            {
                BirthdayParty.GenuineParty = true;
                BirthdayParty.PartyDaysOnCooldown = 5;
                if (getGoodWorldGen)
                {
                    Main.afterPartyOfDoom = true;
                }
                int num273;
                if (remixWorldGen)
                {
                    num273 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 441);
                    NPC.savedTaxCollector = true;
                }
                else
                {
                    num273 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 22);
                }
                Main.npc[num273].homeTileX = Main.spawnTileX;
                Main.npc[num273].homeTileY = Main.spawnTileY;
                Main.npc[num273].direction = 1;
                Main.npc[num273].homeless = true;
                Main.npc[num273].GivenName = Language.GetTextValue("GuideNames.Andrew");
                BirthdayParty.CelebratingNPCs.Add(num273);
                Point adjustedFloorPosition = GetAdjustedFloorPosition(Main.spawnTileX + 2, Main.spawnTileY);
                num273 = NPC.NewNPC(new EntitySource_WorldGen(), adjustedFloorPosition.X * 16, adjustedFloorPosition.Y * 16, 178);
                Main.npc[num273].homeTileX = adjustedFloorPosition.X;
                Main.npc[num273].homeTileY = adjustedFloorPosition.Y;
                Main.npc[num273].direction = -1;
                Main.npc[num273].homeless = true;
                Main.npc[num273].GivenName = Language.GetTextValue("SteampunkerNames.Whitney");
                BirthdayParty.CelebratingNPCs.Add(num273);
                adjustedFloorPosition = GetAdjustedFloorPosition(Main.spawnTileX - 2, Main.spawnTileY);
                num273 = NPC.NewNPC(new EntitySource_WorldGen(), adjustedFloorPosition.X * 16, adjustedFloorPosition.Y * 16, 663);
                Main.npc[num273].homeTileX = adjustedFloorPosition.X;
                Main.npc[num273].homeTileY = adjustedFloorPosition.Y;
                Main.npc[num273].direction = 1;
                Main.npc[num273].homeless = true;
                Main.npc[num273].GivenName = Language.GetTextValue("PrincessNames.Yorai");
                BirthdayParty.CelebratingNPCs.Add(num273);
                NPC.unlockedPrincessSpawn = true;
                adjustedFloorPosition = GetAdjustedFloorPosition(Main.spawnTileX + 4, Main.spawnTileY);
                num273 = NPC.NewNPC(new EntitySource_WorldGen(), adjustedFloorPosition.X * 16, adjustedFloorPosition.Y * 16, 208);
                Main.npc[num273].homeTileX = adjustedFloorPosition.X;
                Main.npc[num273].homeTileY = adjustedFloorPosition.Y;
                Main.npc[num273].direction = -1;
                Main.npc[num273].homeless = true;
                Main.npc[num273].GivenName = Language.GetTextValue("PartyGirlNames.Amanda");
                BirthdayParty.CelebratingNPCs.Add(num273);
                NPC.unlockedPartyGirlSpawn = true;
                adjustedFloorPosition = GetAdjustedFloorPosition(Main.spawnTileX - 4, Main.spawnTileY);
                if (Main.remixWorld)
                {
                    num273 = NPC.NewNPC(new EntitySource_WorldGen(), adjustedFloorPosition.X * 16, adjustedFloorPosition.Y * 16, 681);
                    Main.npc[num273].GivenName = Language.GetTextValue("SlimeNames_Rainbow.Slimestar");
                    NPC.unlockedSlimeRainbowSpawn = true;
                }
                else
                {
                    num273 = NPC.NewNPC(new EntitySource_WorldGen(), adjustedFloorPosition.X * 16, adjustedFloorPosition.Y * 16, 656);
                    NPC.boughtBunny = true;
                    Main.npc[num273].townNpcVariationIndex = 1;
                }
                Main.npc[num273].homeTileX = adjustedFloorPosition.X;
                Main.npc[num273].homeTileY = adjustedFloorPosition.Y;
                Main.npc[num273].direction = 1;
                Main.npc[num273].homeless = true;
            }
            else if (remixWorldGen)
            {
                int num274 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 441);
                Main.npc[num274].homeTileX = Main.spawnTileX;
                Main.npc[num274].homeTileY = Main.spawnTileY;
                Main.npc[num274].direction = 1;
                Main.npc[num274].homeless = true;
                NPC.savedTaxCollector = true;
            }
            else if (notTheBees)
            {
                int num275 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 17);
                Main.npc[num275].homeTileX = Main.spawnTileX;
                Main.npc[num275].homeTileY = Main.spawnTileY;
                Main.npc[num275].direction = 1;
                Main.npc[num275].homeless = true;
                NPC.unlockedMerchantSpawn = true;
            }
            else if (drunkWorldGen)
            {
                int num276 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 208);
                Main.npc[num276].homeTileX = Main.spawnTileX;
                Main.npc[num276].homeTileY = Main.spawnTileY;
                Main.npc[num276].direction = 1;
                Main.npc[num276].homeless = true;
                NPC.unlockedPartyGirlSpawn = true;
            }
            else if (getGoodWorldGen)
            {
                int num277 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 38);
                Main.npc[num277].homeTileX = Main.spawnTileX;
                Main.npc[num277].homeTileY = Main.spawnTileY;
                Main.npc[num277].direction = 1;
                Main.npc[num277].homeless = true;
                NPC.unlockedDemolitionistSpawn = true;
            }
            else
            {
                int num278 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 22);
                Main.npc[num278].homeTileX = Main.spawnTileX;
                Main.npc[num278].homeTileY = Main.spawnTileY;
                Main.npc[num278].direction = 1;
                Main.npc[num278].homeless = true;
            }
        });
        AddGenerationPass("Sunflowers", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[39].Value;
            double num264 = (double)Main.maxTilesX * 0.002;
            for (int num265 = 0; (double)num265 < num264; num265++)
            {
                progress.Set((double)num265 / num264);
                int num266 = 0;
                int num267 = 0;
                _ = Main.maxTilesX / 2;
                int num268 = genRand.Next(Main.maxTilesX);
                num266 = num268 - genRand.Next(10) - 7;
                num267 = num268 + genRand.Next(10) + 7;
                if (num266 < 0)
                {
                    num266 = 0;
                }
                if (num267 > Main.maxTilesX - 1)
                {
                    num267 = Main.maxTilesX - 1;
                }
                int num269 = 1;
                int num270 = (int)Main.worldSurface - 1;
                for (int num271 = num266; num271 < num267; num271++)
                {
                    for (int num272 = num269; num272 < num270; num272++)
                    {
                        if (Main.tile[num271, num272].type == 2 && Main.tile[num271, num272].active() && !Main.tile[num271, num272 - 1].active())
{
                            PlaceTile(num271, num272 - 1, 27, mute: true);
                        }
                        if (Main.tile[num271, num272].active())
{
                            break;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Planting Trees", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[40].Value;
            if (!drunkWorldGen && !Main.tenthAnniversaryWorld)
            {
                for (int num259 = 0; (double)num259 < (double)Main.maxTilesX * 0.003; num259++)
                {
                    progress.Set((double)num259 / ((double)Main.maxTilesX * 0.003));
                    int num260 = genRand.Next(50, Main.maxTilesX - 50);
                    int num261 = genRand.Next(25, 50);
                    for (int num262 = num260 - num261; num262 < num260 + num261; num262++)
                    {
                        for (int num263 = 20; (double)num263 < Main.worldSurface; num263++)
{
                            GrowEpicTree(num262, num263);
                        }
                    }
                }
            }
            AddTrees();
        });
        AddGenerationPass("Herbs", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            double num257 = (double)Main.maxTilesX * 1.7;
            if (remixWorldGen)
            {
                num257 *= 5.0;
            }
            progress.Message = Lang.gen[41].Value;
            for (int num258 = 0; (double)num258 < num257; num258++)
            {
                progress.Set((double)num258 / num257);
                PlantAlch();
            }
        });
        AddGenerationPass("Dye Plants", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num256 = 0; num256 < Main.maxTilesX; num256++)
            {
                plantDye(genRand.Next(100, Main.maxTilesX - 100), genRand.Next(100, Main.UnderworldLayer));
            }
            MatureTheHerbPlants();
            GrowGlowTulips();
        });
        AddGenerationPass("Webs And Honey", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num246 = 100; num246 < Main.maxTilesX - 100; num246++)
            {
                int num247 = (int)Main.worldSurface;
                if (dontStarveWorldGen)
                {
                    num247 = 50;
                }
                for (int num248 = num247; num248 < Main.maxTilesY - 100; num248++)
                {
                    if (Main.tile[num246, num248].wall == 86)
                    {
                        if (Main.tile[num246, num248].liquid > 0)
{
                            Main.tile[num246, num248].honey(honey: true);
                        }
                        if (genRand.Next(3) == 0)
{
                            PlaceTight(num246, num248);
                        }
                    }
                    if (Main.tile[num246, num248].wall == 62)
                    {
                        Main.tile[num246, num248].liquid = 0;
                        Main.tile[num246, num248].lava(lava: false);
                    }
                    if (Main.tile[num246, num248].wall == 62 && !Main.tile[num246, num248].active() && genRand.Next(10) != 0)
                    {
                        int num249 = genRand.Next(2, 5);
                        int num250 = num246 - num249;
                        int num251 = num246 + num249;
                        int num252 = num248 - num249;
                        int num253 = num248 + num249;
                        bool flag7 = false;
                        for (int num254 = num250; num254 <= num251; num254++)
{
                            for (int num255 = num252; num255 <= num253; num255++)
{
                                if (SolidTile(num254, num255))
{
                                    flag7 = true;
                                    break;
                                }
                            }
                        }
                        if (flag7)
{
                            PlaceTile(num246, num248, 51, mute: true);
                            TileFrame(num246, num248);
                        }
                    }
                }
            }
        });
        AddGenerationPass("Weeds", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[42].Value;
            if (Main.halloween)
            {
                for (int num240 = 40; num240 < Main.maxTilesX - 40; num240++)
                {
                    for (int num241 = 50; (double)num241 < Main.worldSurface; num241++)
                    {
                        if (Main.tile[num240, num241].active() && Main.tile[num240, num241].type == 2 && genRand.Next(15) == 0)
{
                            PlacePumpkin(num240, num241 - 1);
                            int num242 = genRand.Next(5);
                            for (int num243 = 0; num243 < num242; num243++)
{
                                GrowPumpkin(num240, num241 - 1, 254);
                            }
                        }
                    }
                }
            }
            for (int num244 = 0; num244 < Main.maxTilesX; num244++)
            {
                progress.Set((double)num244 / (double)Main.maxTilesX);
                for (int num245 = 1; num245 < Main.maxTilesY; num245++)
                {
                    if (Main.tile[num244, num245].type == 2 && Main.tile[num244, num245].nactive())
                    {
                        if (!Main.tile[num244, num245 - 1].active())
{
                            PlaceTile(num244, num245 - 1, 3, mute: true);
                            Main.tile[num244, num245 - 1].CopyPaintAndCoating(Main.tile[num244, num245]);
                        }
                    }
                    else if (Main.tile[num244, num245].type == 23 && Main.tile[num244, num245].nactive())
                    {
                        if (!Main.tile[num244, num245 - 1].active())
{
                            PlaceTile(num244, num245 - 1, 24, mute: true);
                        }
                    }
                    else if (Main.tile[num244, num245].type == 199 && Main.tile[num244, num245].nactive())
                    {
                        if (!Main.tile[num244, num245 - 1].active())
{
                            PlaceTile(num244, num245 - 1, 201, mute: true);
                        }
                    }
                    else if (Main.tile[num244, num245].type == 633 && Main.tile[num244, num245].nactive() && !Main.tile[num244, num245 - 1].active())
                    {
                        PlaceTile(num244, num245 - 1, 637, mute: true);
                    }
                }
            }
        });
        AddGenerationPass("Glowing Mushrooms and Jungle Plants", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num238 = 0; num238 < Main.maxTilesX; num238++)
            {
                for (int num239 = 0; num239 < Main.maxTilesY; num239++)
                {
                    if (Main.tile[num238, num239].active())
                    {
                        if (num239 >= (int)Main.worldSurface && Main.tile[num238, num239].type == 70 && !Main.tile[num238, num239 - 1].active())
{
                            GrowTree(num238, num239);
                            if (!Main.tile[num238, num239 - 1].active())
{
                                GrowTree(num238, num239);
                                if (!Main.tile[num238, num239 - 1].active())
{
                                    GrowTree(num238, num239);
                                    if (!Main.tile[num238, num239 - 1].active())
{
                                        PlaceTile(num238, num239 - 1, 71, mute: true);
                                    }
                                }
                            }
                        }
                        if (Main.tile[num238, num239].type == 60 && !Main.tile[num238, num239 - 1].active())
{
                            PlaceTile(num238, num239 - 1, 61, mute: true);
                        }
                    }
                }
            }
        });
        AddGenerationPass("Jungle Plants", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num235 = 0; num235 < Main.maxTilesX * 100; num235++)
            {
                int num236 = genRand.Next(40, Main.maxTilesX / 2 - 40);
                if (GenVars.dungeonSide < 0)
                {
                    num236 += Main.maxTilesX / 2;
                }
                int num237;
                for (num237 = genRand.Next(Main.maxTilesY - 300); !Main.tile[num236, num237].active() && num237 < Main.maxTilesY - 300; num237++)
                {
                }
                if (Main.tile[num236, num237].active() && Main.tile[num236, num237].type == 60)
                {
                    num237--;
                    PlaceJunglePlant(num236, num237, 233, genRand.Next(8), 0);
                    if (Main.tile[num236, num237].type != 233)
                    {
                        PlaceJunglePlant(num236, num237, 233, genRand.Next(12), 1);
                    }
                }
            }
        });
        AddGenerationPass("Vines", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[43].Value;
            for (int num213 = 5; num213 < Main.maxTilesX - 5; num213++)
            {
                progress.Set((double)num213 / (double)Main.maxTilesX);
                int num214 = 0;
                ushort num215 = 52;
                int num216 = (int)Main.worldSurface;
                if (remixWorldGen)
                {
                    num216 = Main.maxTilesY - 200;
                }
                for (int num217 = 0; num217 < num216; num217++)
                {
                    if (num214 > 0 && !Main.tile[num213, num217].active())
                    {
                        Main.tile[num213, num217].active(active: true);
                        Main.tile[num213, num217].type = num215;
                        Main.tile[num213, num217].CopyPaintAndCoating(Main.tile[num213, num217 - 1]);
                        num214--;
                    }
                    else
                    {
                        num214 = 0;
                    }
                    if (Main.tile[num213, num217].active() && !Main.tile[num213, num217].bottomSlope() && (Main.tile[num213, num217].type == 2 || (Main.tile[num213, num217].type == 192 && genRand.Next(4) == 0)) && GrowMoreVines(num213, num217))
                    {
                        num215 = 52;
                        if (Main.tile[num213, num217].wall == 68 || Main.tile[num213, num217].wall == 65 || Main.tile[num213, num217].wall == 66 || Main.tile[num213, num217].wall == 63)
{
                            num215 = 382;
                        }
                        else if (Main.tile[num213, num217 + 1].wall == 68 || Main.tile[num213, num217 + 1].wall == 65 || Main.tile[num213, num217 + 1].wall == 66 || Main.tile[num213, num217 + 1].wall == 63)
{
                            num215 = 382;
                        }
                        if (remixWorldGen && genRand.Next(5) == 0)
{
                            num215 = 382;
                        }
                        if (genRand.Next(5) < 3)
{
                            num214 = genRand.Next(1, 10);
                        }
                    }
                }
                num214 = 0;
                for (int num218 = 5; num218 < Main.maxTilesY - 5; num218++)
                {
                    if (num214 > 0 && !Main.tile[num213, num218].active())
                    {
                        Main.tile[num213, num218].active(active: true);
                        Main.tile[num213, num218].type = 62;
                        num214--;
                    }
                    else
                    {
                        num214 = 0;
                    }
                    if (Main.tile[num213, num218].active() && Main.tile[num213, num218].type == 60 && !Main.tile[num213, num218].bottomSlope() && GrowMoreVines(num213, num218))
                    {
                        if (notTheBees && num218 < Main.maxTilesY - 10 && Main.tile[num213, num218 - 1].active() && !Main.tile[num213, num218 - 1].bottomSlope() && Main.tile[num213 + 1, num218 - 1].active() && !Main.tile[num213 + 1, num218 - 1].bottomSlope() && (Main.tile[num213, num218 - 1].type == 60 || Main.tile[num213, num218 - 1].type == 444 || Main.tile[num213, num218 - 1].type == 230))
{
                            bool flag5 = true;
                            for (int num219 = num213; num219 < num213 + 2; num219++)
{
                                for (int num220 = num218 + 1; num220 < num218 + 3; num220++)
{
                                    if (Main.tile[num219, num220].active() && (!Main.tileCut[Main.tile[num219, num220].type] || Main.tile[num219, num220].type == 444))
{
                                        flag5 = false;
                                        break;
                                    }
                                    if (Main.tile[num219, num220].liquid > 0 || Main.wallHouse[Main.tile[num219, num220].wall])
{
                                        flag5 = false;
                                        break;
                                    }
                                }
                                if (!flag5)
{
                                    break;
                                }
                            }
                            if (flag5 && CountNearBlocksTypes(num213, num218, genRand.Next(3, 10), 1, 444) > 0)
{
                                flag5 = false;
                            }
                            if (flag5)
{
                                for (int num221 = num213; num221 < num213 + 2; num221++)
{
                                    for (int num222 = num218 + 1; num222 < num218 + 3; num222++)
{
                                        KillTile(num221, num222);
                                    }
                                }
                                for (int num223 = num213; num223 < num213 + 2; num223++)
{
                                    for (int num224 = num218 + 1; num224 < num218 + 3; num224++)
{
                                        Main.tile[num223, num224].active(active: true);
                                        Main.tile[num223, num224].type = 444;
                                        Main.tile[num223, num224].frameX = (short)((num223 - num213) * 18);
                                        Main.tile[num223, num224].frameY = (short)((num224 - num218 - 1) * 18);
                                    }
                                }
                                continue;
                            }
                        }
                        else if (num213 < Main.maxTilesX - 1 && num218 < Main.maxTilesY - 2 && Main.tile[num213 + 1, num218].active() && Main.tile[num213 + 1, num218].type == 60 && !Main.tile[num213 + 1, num218].bottomSlope() && genRand.Next(40) == 0)
{
                            bool flag6 = true;
                            for (int num225 = num213; num225 < num213 + 2; num225++)
{
                                for (int num226 = num218 + 1; num226 < num218 + 3; num226++)
{
                                    if (Main.tile[num225, num226].active() && (!Main.tileCut[Main.tile[num225, num226].type] || Main.tile[num225, num226].type == 444))
{
                                        flag6 = false;
                                        break;
                                    }
                                    if (Main.tile[num225, num226].liquid > 0 || Main.wallHouse[Main.tile[num225, num226].wall])
{
                                        flag6 = false;
                                        break;
                                    }
                                }
                                if (!flag6)
{
                                    break;
                                }
                            }
                            if (flag6 && CountNearBlocksTypes(num213, num218, 20, 1, 444) > 0)
{
                                flag6 = false;
                            }
                            if (flag6)
{
                                for (int num227 = num213; num227 < num213 + 2; num227++)
{
                                    for (int num228 = num218 + 1; num228 < num218 + 3; num228++)
{
                                        KillTile(num227, num228);
                                    }
                                }
                                for (int num229 = num213; num229 < num213 + 2; num229++)
{
                                    for (int num230 = num218 + 1; num230 < num218 + 3; num230++)
{
                                        Main.tile[num229, num230].active(active: true);
                                        Main.tile[num229, num230].type = 444;
                                        Main.tile[num229, num230].frameX = (short)((num229 - num213) * 18);
                                        Main.tile[num229, num230].frameY = (short)((num230 - num218 - 1) * 18);
                                    }
                                }
                                continue;
                            }
                        }
                        if (genRand.Next(5) < 3)
{
                            num214 = genRand.Next(1, 10);
                        }
                    }
                }
                num214 = 0;
                for (int num231 = 0; num231 < Main.maxTilesY; num231++)
                {
                    if (num214 > 0 && !Main.tile[num213, num231].active())
                    {
                        Main.tile[num213, num231].active(active: true);
                        Main.tile[num213, num231].type = 528;
                        num214--;
                    }
                    else
                    {
                        num214 = 0;
                    }
                    if (Main.tile[num213, num231].active() && Main.tile[num213, num231].type == 70 && genRand.Next(5) == 0 && !Main.tile[num213, num231].bottomSlope() && GrowMoreVines(num213, num231) && genRand.Next(5) < 3)
                    {
                        num214 = genRand.Next(1, 10);
                    }
                }
                num214 = 0;
                for (int num232 = 0; num232 < Main.maxTilesY; num232++)
                {
                    if (num214 > 0 && !Main.tile[num213, num232].active())
                    {
                        Main.tile[num213, num232].active(active: true);
                        Main.tile[num213, num232].type = 636;
                        num214--;
                    }
                    else
                    {
                        num214 = 0;
                    }
                    if (Main.tile[num213, num232].active() && !Main.tile[num213, num232].bottomSlope() && Main.tile[num213, num232].type == 23 && GrowMoreVines(num213, num232) && genRand.Next(5) < 3)
                    {
                        num214 = genRand.Next(1, 10);
                    }
                }
                num214 = 0;
                for (int num233 = 0; num233 < Main.maxTilesY; num233++)
                {
                    if (num214 > 0 && !Main.tile[num213, num233].active())
                    {
                        Main.tile[num213, num233].active(active: true);
                        Main.tile[num213, num233].type = 205;
                        num214--;
                    }
                    else
                    {
                        num214 = 0;
                    }
                    if (Main.tile[num213, num233].active() && !Main.tile[num213, num233].bottomSlope() && Main.tile[num213, num233].type == 199 && GrowMoreVines(num213, num233) && genRand.Next(5) < 3)
                    {
                        num214 = genRand.Next(1, 10);
                    }
                }
                num214 = 0;
                for (int num234 = 0; num234 < Main.maxTilesY; num234++)
                {
                    if (num214 > 0 && !Main.tile[num213, num234].active())
                    {
                        Main.tile[num213, num234].active(active: true);
                        Main.tile[num213, num234].type = 638;
                        num214--;
                    }
                    else
                    {
                        num214 = 0;
                    }
                    if (Main.tile[num213, num234].active() && !Main.tile[num213, num234].bottomSlope() && Main.tile[num213, num234].type == 633 && GrowMoreVines(num213, num234) && genRand.Next(5) < 3)
                    {
                        num214 = genRand.Next(1, 10);
                    }
                }
            }
        });
        AddGenerationPass("Flowers", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[44].Value;
            int num200 = (int)((double)Main.maxTilesX * 0.004);
            if (remixWorldGen)
            {
                num200 *= 6;
            }
            for (int num201 = 0; num201 < num200; num201++)
            {
                progress.Set((double)num201 / (double)num200);
                int num202 = genRand.Next(100, Main.maxTilesX - 100);
                int num203 = genRand.Next(15, 30);
                int num204 = genRand.Next(15, 30);
                if (remixWorldGen)
                {
                    num203 = genRand.Next(15, 45);
                    num204 = genRand.Next(15, 45);
                    int num205 = genRand.Next((int)Main.rockLayer, Main.maxTilesY - 350);
                    if (GenVars.logX >= 0)
                    {
                        num202 = GenVars.logX;
                        num205 = GenVars.logY;
                        GenVars.logX = -1;
                    }
                    int num206 = genRand.NextFromList<int>(21, 24, 27, 30, 33, 36, 39, 42);
                    for (int num207 = num202 - num203; num207 < num202 + num203; num207++)
                    {
                        for (int num208 = num205 - num204; num208 < num205 + num204; num208++)
{
                            if (Main.tile[num207, num208].type != 488 && !Main.tileSolid[Main.tile[num207, num208].type])
{
                                if (Main.tile[num207, num208].type == 3)
{
                                    Main.tile[num207, num208].frameX = (short)((num206 + genRand.Next(3)) * 18);
                                    if (genRand.Next(3) != 0)
{
                                        Main.tile[num207, num208].type = 73;
                                    }
                                }
                                else if (Main.tile[num207, num208 + 1].wall == 0 && (Main.tile[num207, num208 + 1].type == 2 || ((Main.tile[num207, num208 + 1].type == 40 || Main.tile[num207, num208 + 1].type == 1 || TileID.Sets.Ore[Main.tile[num207, num208 + 1].type]) && !Main.tile[num207, num208].active())) && (!Main.tile[num207, num208].active() || Main.tile[num207, num208].type == 185 || Main.tile[num207, num208].type == 186 || Main.tile[num207, num208].type == 187 || (Main.tile[num207, num208].type == 5 && (double)num207 < (double)Main.maxTilesX * 0.48) || (double)num207 > (double)Main.maxTilesX * 0.52))
{
                                    if (Main.tile[num207, num208 + 1].type == 40 || Main.tile[num207, num208 + 1].type == 1 || TileID.Sets.Ore[Main.tile[num207, num208 + 1].type])
{
                                        Main.tile[num207, num208 + 1].type = 2;
                                        if (Main.tile[num207, num208 + 2].type == 40 || Main.tile[num207, num208 + 2].type == 1 || TileID.Sets.Ore[Main.tile[num207, num208 + 2].type])
{
                                            Main.tile[num207, num208 + 2].type = 2;
                                        }
                                    }
                                    KillTile(num207, num208);
                                    if (genRand.Next(2) == 0)
{
                                        Main.tile[num207, num208 + 1].slope(0);
                                        Main.tile[num207, num208 + 1].halfBrick(halfBrick: false);
                                    }
                                    PlaceTile(num207, num208, 3);
                                    if (Main.tile[num207, num208].active() && Main.tile[num207, num208].type == 3)
{
                                        Main.tile[num207, num208].frameX = (short)((num206 + genRand.Next(3)) * 18);
                                        if (genRand.Next(3) != 0)
{
                                            Main.tile[num207, num208].type = 73;
                                        }
                                    }
                                    if (Main.tile[num207, num208 + 2].type == 40 || Main.tile[num207, num208 + 2].type == 1 || TileID.Sets.Ore[Main.tile[num207, num208 + 2].type])
{
                                        Main.tile[num207, num208 + 2].type = 0;
                                    }
                                }
                            }
                        }
                    }
                }
                else
                {
                    for (int num209 = num204; (double)num209 < Main.worldSurface - (double)num204 - 1.0; num209++)
                    {
                        if (Main.tile[num202, num209].active())
{
                            if (GenVars.logX >= 0)
{
                                num202 = GenVars.logX;
                                num209 = GenVars.logY;
                                GenVars.logX = -1;
                            }
                            int num210 = genRand.NextFromList<int>(21, 24, 27, 30, 33, 36, 39, 42);
                            for (int num211 = num202 - num203; num211 < num202 + num203; num211++)
{
                                for (int num212 = num209 - num204; num212 < num209 + num204; num212++)
{
                                    if (Main.tile[num211, num212].type != 488 && !Main.tileSolid[Main.tile[num211, num212].type])
{
                                        if (Main.tile[num211, num212].type == 3)
{
                                            Main.tile[num211, num212].frameX = (short)((num210 + genRand.Next(3)) * 18);
                                            if (genRand.Next(3) != 0)
{
                                                Main.tile[num211, num212].type = 73;
                                            }
                                        }
                                        else if (Main.tile[num211, num212 + 1].wall == 0 && (Main.tile[num211, num212 + 1].type == 2 || ((Main.tile[num211, num212 + 1].type == 40 || Main.tile[num211, num212 + 1].type == 1 || TileID.Sets.Ore[Main.tile[num211, num212 + 1].type]) && !Main.tile[num211, num212].active())) && (!Main.tile[num211, num212].active() || Main.tile[num211, num212].type == 185 || Main.tile[num211, num212].type == 186 || Main.tile[num211, num212].type == 187 || (Main.tile[num211, num212].type == 5 && (double)num211 < (double)Main.maxTilesX * 0.48) || (double)num211 > (double)Main.maxTilesX * 0.52))
{
                                            if (Main.tile[num211, num212 + 1].type == 40 || Main.tile[num211, num212 + 1].type == 1 || TileID.Sets.Ore[Main.tile[num211, num212 + 1].type])
{
                                                Main.tile[num211, num212 + 1].type = 2;
                                                if (Main.tile[num211, num212 + 2].type == 40 || Main.tile[num211, num212 + 2].type == 1 || TileID.Sets.Ore[Main.tile[num211, num212 + 2].type])
{
                                                    Main.tile[num211, num212 + 2].type = 2;
                                                }
                                            }
                                            KillTile(num211, num212);
                                            if (genRand.Next(2) == 0)
{
                                                Main.tile[num211, num212 + 1].slope(0);
                                                Main.tile[num211, num212 + 1].halfBrick(halfBrick: false);
                                            }
                                            PlaceTile(num211, num212, 3);
                                            if (Main.tile[num211, num212].active() && Main.tile[num211, num212].type == 3)
{
                                                Main.tile[num211, num212].frameX = (short)((num210 + genRand.Next(3)) * 18);
                                                if (genRand.Next(3) != 0)
{
                                                    Main.tile[num211, num212].type = 73;
                                                }
                                            }
                                            if (Main.tile[num211, num212 + 2].type == 40 || Main.tile[num211, num212 + 2].type == 1 || TileID.Sets.Ore[Main.tile[num211, num212 + 2].type])
{
                                                Main.tile[num211, num212 + 2].type = 0;
                                            }
                                        }
                                    }
                                }
                            }
                            break;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Mushrooms", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[45].Value;
            int num189 = (int)((double)Main.maxTilesX * 0.002);
            if (remixWorldGen)
            {
                num189 *= 9;
            }
            for (int num190 = 0; num190 < num189; num190++)
            {
                progress.Set((double)num190 / (double)num189);
                int num191 = genRand.Next(20, Main.maxTilesX - 20);
                int num192 = genRand.Next(4, 10);
                int num193 = genRand.Next(15, 30);
                if (remixWorldGen)
                {
                    num192 = genRand.Next(8, 17);
                    num193 = genRand.Next(8, 17);
                    int num194 = genRand.Next((int)Main.rockLayer, Main.maxTilesY - 350);
                    if (Main.tile[num191, num194].active())
                    {
                        for (int num195 = num191 - num192; num195 < num191 + num192; num195++)
{
                            for (int num196 = num194 - num193; num196 < num194 + num193; num196++)
{
                                if (num195 < 10)
{
                                    break;
                                }
                                if (num196 < 0)
{
                                    break;
                                }
                                if (num195 > Main.maxTilesX - 10)
{
                                    break;
                                }
                                if (num196 > Main.maxTilesY - 10)
{
                                    break;
                                }
                                if (Main.tile[num195, num196].type == 3 || Main.tile[num195, num196].type == 24)
{
                                    Main.tile[num195, num196].frameX = 144;
                                }
                                else if (Main.tile[num195, num196].type == 201)
{
                                    Main.tile[num195, num196].frameX = 270;
                                }
                            }
                        }
                    }
                }
                else
                {
                    for (int num197 = 1; (double)num197 < Main.worldSurface - 1.0; num197++)
                    {
                        if (Main.tile[num191, num197].active())
{
                            for (int num198 = num191 - num192; num198 < num191 + num192; num198++)
{
                                for (int num199 = num197 - num193; num199 < num197 + num193; num199++)
{
                                    if (num198 < 10)
{
                                        break;
                                    }
                                    if (num199 < 0)
{
                                        break;
                                    }
                                    if (num198 > Main.maxTilesX - 10)
{
                                        break;
                                    }
                                    if (num199 > Main.maxTilesY - 10)
{
                                        break;
                                    }
                                    if (Main.tile[num198, num199].type == 3 || Main.tile[num198, num199].type == 24)
{
                                        Main.tile[num198, num199].frameX = 144;
                                    }
                                    else if (Main.tile[num198, num199].type == 201)
{
                                        Main.tile[num198, num199].frameX = 270;
                                    }
                                }
                            }
                            break;
                        }
                    }
                }
            }
        });
        AddGenerationPass("Gems In Ice Biome", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num178 = 0; (double)num178 < (double)Main.maxTilesX * 0.25; num178++)
            {
                int num179 = ((!remixWorldGen) ? genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, GenVars.lavaLine) : genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300));
                int num180 = genRand.Next(GenVars.snowMinX[num179], GenVars.snowMaxX[num179]);
                if (Main.tile[num180, num179].active() && (Main.tile[num180, num179].type == 147 || Main.tile[num180, num179].type == 161 || Main.tile[num180, num179].type == 162 || Main.tile[num180, num179].type == 224))
                {
                    int num181 = genRand.Next(1, 4);
                    int num182 = genRand.Next(1, 4);
                    int num183 = genRand.Next(1, 4);
                    int num184 = genRand.Next(1, 4);
                    int num185 = genRand.Next(12);
                    int num186 = 0;
                    num186 = ((num185 >= 3) ? ((num185 < 6) ? 1 : ((num185 < 8) ? 2 : ((num185 < 10) ? 3 : ((num185 >= 11) ? 5 : 4)))) : 0);
                    for (int num187 = num180 - num181; num187 < num180 + num182; num187++)
                    {
                        for (int num188 = num179 - num183; num188 < num179 + num184; num188++)
{
                            if (!Main.tile[num187, num188].active())
{
                                PlaceTile(num187, num188, 178, mute: true, forced: false, -1, num186);
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Random Gems", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num164 = 0; num164 < Main.maxTilesX; num164++)
            {
                int num165 = genRand.Next(20, Main.maxTilesX - 20);
                int num166 = genRand.Next((int)Main.rockLayer, Main.maxTilesY - 300);
                if (!Main.tile[num165, num166].active() && !Main.tile[num165, num166].lava() && !Main.wallDungeon[Main.tile[num165, num166].wall] && Main.tile[num165, num166].wall != 27)
                {
                    int num167 = genRand.Next(12);
                    int num168 = 0;
                    num168 = ((num167 >= 3) ? ((num167 < 6) ? 1 : ((num167 < 8) ? 2 : ((num167 < 10) ? 3 : ((num167 >= 11) ? 5 : 4)))) : 0);
                    PlaceTile(num165, num166, 178, mute: true, forced: false, -1, num168);
                }
            }
            for (int num169 = 0; num169 < Main.maxTilesX; num169++)
            {
                int num170 = genRand.Next(20, Main.maxTilesX - 20);
                int num171 = genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300);
                if (!Main.tile[num170, num171].active() && !Main.tile[num170, num171].lava() && (Main.tile[num170, num171].wall == 216 || Main.tile[num170, num171].wall == 187))
                {
                    int num172 = genRand.Next(1, 4);
                    int num173 = genRand.Next(1, 4);
                    int num174 = genRand.Next(1, 4);
                    int num175 = genRand.Next(1, 4);
                    for (int num176 = num170 - num172; num176 < num170 + num173; num176++)
                    {
                        for (int num177 = num171 - num174; num177 < num171 + num175; num177++)
{
                            if (!Main.tile[num176, num177].active())
{
                                PlaceTile(num176, num177, 178, mute: true, forced: false, -1, 6);
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Moss Grass", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num159 = 5; num159 < Main.maxTilesX - 5; num159++)
            {
                for (int num160 = 5; num160 < Main.maxTilesY - 5; num160++)
                {
                    if (Main.tile[num159, num160].active() && Main.tileMoss[Main.tile[num159, num160].type])
                    {
                        for (int num161 = 0; num161 < 4; num161++)
{
                            int num162 = num159;
                            int num163 = num160;
                            if (num161 == 0)
{
                                num162--;
                            }
                            if (num161 == 1)
{
                                num162++;
                            }
                            if (num161 == 2)
{
                                num163--;
                            }
                            if (num161 == 3)
{
                                num163++;
                            }
                            if (!Main.tile[num162, num163].active())
{
                                PlaceTile(num162, num163, 184, mute: true);
                            }
                        }
                    }
                }
            }
        });
        AddGenerationPass("Muds Walls In Jungle", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            int num151 = 0;
            int num152 = 0;
            bool flag4 = false;
            for (int num153 = 5; num153 < Main.maxTilesX - 5; num153++)
            {
                for (int num154 = 0; (double)num154 < Main.worldSurface + 20.0; num154++)
                {
                    if (Main.tile[num153, num154].active() && Main.tile[num153, num154].type == 60)
                    {
                        num151 = num153;
                        flag4 = true;
                        break;
                    }
                }
                if (flag4)
                {
                    break;
                }
            }
            flag4 = false;
            for (int num155 = Main.maxTilesX - 5; num155 > 5; num155--)
            {
                for (int num156 = 0; (double)num156 < Main.worldSurface + 20.0; num156++)
                {
                    if (Main.tile[num155, num156].active() && Main.tile[num155, num156].type == 60)
                    {
                        num152 = num155;
                        flag4 = true;
                        break;
                    }
                }
                if (flag4)
                {
                    break;
                }
            }
            GenVars.jungleMinX = num151;
            GenVars.jungleMaxX = num152;
            for (int num157 = num151; num157 <= num152; num157++)
            {
                for (int num158 = 0; (double)num158 < Main.worldSurface + 20.0; num158++)
                {
                    if (((num157 >= num151 + 2 && num157 <= num152 - 2) || genRand.Next(2) != 0) && ((num157 >= num151 + 3 && num157 <= num152 - 3) || genRand.Next(3) != 0) && (Main.tile[num157, num158].wall == 2 || Main.tile[num157, num158].wall == 59))
                    {
                        Main.tile[num157, num158].wall = 15;
                    }
                }
            }
        });
        AddGenerationPass("Larva", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            Main.tileSolid[229] = true;
            progress.Set(1.0);
            for (int num146 = 0; num146 < GenVars.numLarva; num146++)
            {
                int num147 = GenVars.larvaX[num146];
                int num148 = GenVars.larvaY[num146];
                for (int num149 = num147 - 1; num149 <= num147 + 1; num149++)
                {
                    for (int num150 = num148 - 2; num150 <= num148 + 1; num150++)
                    {
                        if (num150 != num148 + 1)
{
                            Main.tile[num149, num150].active(active: false);
                        }
                        else
{
                            Main.tile[num149, num150].active(active: true);
                            Main.tile[num149, num150].type = 225;
                            Main.tile[num149, num150].slope(0);
                            Main.tile[num149, num150].halfBrick(halfBrick: false);
                        }
                    }
                }
                PlaceTile(num147, num148, 231, mute: true);
            }
            Main.tileSolid[232] = true;
            Main.tileSolid[162] = true;
        });
        AddGenerationPass("Settle Liquids Again", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            if (getGoodWorldGen)
            {
                Main.tileSolid[56] = true;
            }
            progress.Message = Lang.gen[27].Value;
            if (notTheBees)
            {
                NotTheBees();
            }
            Liquid.worldGenTilesIgnoreWater(ignoreSolids: true);
            Liquid.QuickWater(3);
            WaterCheck();
            int num140 = 0;
            Liquid.quickSettle = true;
            int num141 = 10;
            while (num140 < num141)
            {
                int num142 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                num140++;
                double num143 = 0.0;
                int num144 = num142 * 5;
                while (Liquid.numLiquid > 0)
                {
                    num144--;
                    if (num144 < 0)
                    {
                        break;
                    }
                    double num145 = (double)(num142 - (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer)) / (double)num142;
                    if (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer > num142)
                    {
                        num142 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                    }
                    if (num145 > num143)
                    {
                        num143 = num145;
                    }
                    else
                    {
                        num145 = num143;
                    }
                    if (num140 == 1)
                    {
                        progress.Set(num145 / 3.0 + 0.33);
                    }
                    Liquid.UpdateLiquid();
                }
                WaterCheck();
                progress.Set((double)num140 / (double)num141 / 3.0 + 0.66);
            }
            Liquid.quickSettle = false;
            Liquid.worldGenTilesIgnoreWater(ignoreSolids: false);
            Main.tileSolid[484] = false;
        });
        AddGenerationPass("Cactus, Palm Trees, & Coral", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[38].Value;
            int num114 = 8;
            if (remixWorldGen)
            {
                num114 = 2;
            }
            int num115 = 400;
            int num116 = genRand.Next(3, 13);
            int num117 = genRand.Next(3, 13);
            genRand.Next(2, 6);
            genRand.Next(2, 6);
            int num118 = 380;
            for (int num119 = 0; num119 < GenVars.numOasis; num119++)
            {
                int num120 = (int)((double)GenVars.oasisWidth[num119] * 1.5);
                for (int num121 = GenVars.oasisPosition[num119].X - num120; num121 <= GenVars.oasisPosition[num119].X + num120; num121++)
                {
                    for (int num122 = GenVars.oasisPosition[num119].Y - GenVars.oasisHeight; num122 <= GenVars.oasisPosition[num119].Y + GenVars.oasisHeight; num122++)
                    {
                        double num123 = 1.0;
                        int num124 = 8;
                        for (int num125 = num121 - num124; num125 <= num121 + num124; num125++)
{
                            for (int num126 = num122 - num124; num126 <= num122 + num124; num126++)
{
                                if (InWorld(num125, num126) && Main.tile[num125, num126] != null && Main.tile[num125, num126].active() && Main.tile[num125, num126].type == 323)
{
                                    num123 = 0.13;
                                }
                            }
                        }
                        if (genRand.NextDouble() < num123)
{
                            GrowPalmTree(num121, num122);
                        }
                        if (PlantSeaOat(num121, num122))
{
                            if (genRand.Next(2) == 0)
{
                                GrowSeaOat(num121, num122);
                            }
                            if (genRand.Next(2) == 0)
{
                                GrowSeaOat(num121, num122);
                            }
                        }
                        PlaceOasisPlant(num121, num122, 530);
                    }
                }
            }
            for (int num127 = 0; num127 < 3; num127++)
            {
                progress.Set((double)num127 / 3.0);
                int num128;
                int num129;
                bool flag3;
                int maxValue4;
                switch (num127)
                {
                default:
                    num128 = 5;
                    num129 = num118;
                    flag3 = false;
                    maxValue4 = num116;
                    break;
                case 1:
                    num128 = num115;
                    num129 = Main.maxTilesX - num115;
                    flag3 = true;
                    maxValue4 = num114;
                    break;
                case 2:
                    num128 = Main.maxTilesX - num118;
                    num129 = Main.maxTilesX - 5;
                    flag3 = false;
                    maxValue4 = num117;
                    break;
                }
                double num130 = Main.worldSurface - 1.0;
                if (remixWorldGen)
                {
                    num130 = Main.maxTilesY - 50;
                }
                for (int num131 = num128; num131 < num129; num131++)
                {
                    if (genRand.Next(maxValue4) == 0)
                    {
                        for (int num132 = 0; (double)num132 < num130; num132++)
{
                            Tile tile5 = Main.tile[num131, num132];
                            if (tile5.active() && (tile5.type == 53 || tile5.type == 112 || tile5.type == 234))
{
                                Tile tile6 = Main.tile[num131, num132 - 1];
                                if (!tile6.active() && tile6.wall == 0)
{
                                    if (flag3)
{
                                        if (remixWorldGen)
{
                                            if ((double)num132 > Main.worldSurface)
{
                                                if (SolidTile(num131, num132) && Main.tile[num131, num132 + 1].type == 53 && Main.tile[num131, num132 + 2].type == 53)
{
                                                    int maxValue5 = 3;
                                                    GrowPalmTree(num131, num132);
                                                    if (!Main.tile[num131, num132 - 1].active() && genRand.Next(maxValue5) == 0)
{
                                                        PlantCactus(num131, num132);
                                                    }
                                                }
                                            }
                                            else
{
                                                int num133 = 0;
                                                for (int num134 = num131 - cactusWaterWidth; num134 < num131 + cactusWaterWidth; num134++)
{
                                                    for (int num135 = num132 - cactusWaterHeight; num135 < num132 + cactusWaterHeight; num135++)
{
                                                        num133 += Main.tile[num134, num135].liquid;
                                                    }
                                                }
                                                if (num133 / 255 > cactusWaterLimit)
{
                                                    int maxValue6 = 4;
                                                    if (genRand.Next(maxValue6) == 0)
{
                                                        GrowPalmTree(num131, num132);
                                                    }
                                                }
                                                else
{
                                                    PlantCactus(num131, num132);
                                                }
                                            }
                                        }
                                        else
{
                                            int num136 = 0;
                                            for (int num137 = num131 - cactusWaterWidth; num137 < num131 + cactusWaterWidth; num137++)
{
                                                for (int num138 = num132 - cactusWaterHeight; num138 < num132 + cactusWaterHeight; num138++)
{
                                                    num136 += Main.tile[num137, num138].liquid;
                                                }
                                            }
                                            if (num136 / 255 > cactusWaterLimit)
{
                                                int maxValue7 = 4;
                                                if (genRand.Next(maxValue7) == 0)
{
                                                    GrowPalmTree(num131, num132);
                                                }
                                            }
                                            else
{
                                                PlantCactus(num131, num132);
                                            }
                                        }
                                    }
                                    else
{
                                        if (Main.tile[num131, num132 - 2].liquid == byte.MaxValue && Main.tile[num131, num132 - 3].liquid == byte.MaxValue && Main.tile[num131, num132 - 4].liquid == byte.MaxValue)
{
                                            if (genRand.Next(2) == 0)
{
                                                PlaceTile(num131, num132 - 1, 81, mute: true);
                                            }
                                            else
{
                                                PlaceTile(num131, num132 - 1, 324, mute: true, forced: false, -1, RollRandomSeaShellStyle());
                                            }
                                            break;
                                        }
                                        if (Main.tile[num131, num132 - 2].liquid == 0 && (double)num132 < Main.worldSurface)
{
                                            PlaceTile(num131, num132 - 1, 324, mute: true, forced: false, -1, RollRandomSeaShellStyle());
                                            break;
                                        }
                                    }
                                }
                            }
                        }
                    }
                    else
                    {
                        for (int num139 = 0; (double)num139 < num130; num139++)
{
                            if (PlantSeaOat(num131, num139))
{
                                if (genRand.Next(2) == 0)
{
                                    GrowSeaOat(num131, num139);
                                }
                                if (genRand.Next(2) == 0)
{
                                    GrowSeaOat(num131, num139);
                                }
                            }
                            PlaceOasisPlant(num131, num139, 530);
                        }
                    }
                }
            }
        });
        AddGenerationPass("Tile Cleanup", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Message = Lang.gen[84].Value;
            for (int num57 = 40; num57 < Main.maxTilesX - 40; num57++)
            {
                progress.Set((double)(num57 - 40) / (double)(Main.maxTilesX - 80));
                for (int num58 = 40; num58 < Main.maxTilesY - 40; num58++)
                {
                    if (Main.tile[num57, num58].active() && Main.tile[num57, num58].topSlope() && ((Main.tile[num57, num58].leftSlope() && Main.tile[num57 + 1, num58].halfBrick()) || (Main.tile[num57, num58].rightSlope() && Main.tile[num57 - 1, num58].halfBrick())))
                    {
                        Main.tile[num57, num58].slope(0);
                        Main.tile[num57, num58].halfBrick(halfBrick: true);
                    }
                    if (Main.tile[num57, num58].active() && Main.tile[num57, num58].liquid > 0 && TileID.Sets.SlowlyDiesInWater[Main.tile[num57, num58].type])
                    {
                        KillTile(num57, num58);
                    }
                    if (!Main.tile[num57, num58].active() && Main.tile[num57, num58].liquid == 0 && genRand.Next(3) != 0 && SolidTile(num57, num58 - 1))
                    {
                        int num59 = genRand.Next(15, 21);
                        for (int num60 = num58 - 2; num60 >= num58 - num59; num60--)
{
                            if (Main.tile[num57, num60].liquid >= 128 && !Main.tile[num57, num60].shimmer())
{
                                int num61 = 373;
                                if (Main.tile[num57, num60].lava())
{
                                    num61 = 374;
                                }
                                else if (Main.tile[num57, num60].honey())
{
                                    num61 = 375;
                                }
                                int maxValue3 = num58 - num60;
                                if (genRand.Next(maxValue3) <= 1)
{
                                    if (Main.tile[num57, num58].wall == 86)
{
                                        num61 = 375;
                                    }
                                    Main.tile[num57, num58].type = (ushort)num61;
                                    Main.tile[num57, num58].frameX = 0;
                                    Main.tile[num57, num58].frameY = 0;
                                    Main.tile[num57, num58].active(active: true);
                                    break;
                                }
                            }
                        }
                        if (!Main.tile[num57, num58].active())
{
                            num59 = genRand.Next(3, 11);
                            for (int num62 = num58 + 1; num62 <= num58 + num59; num62++)
{
                                if (Main.tile[num57, num62].liquid >= 200 && !Main.tile[num57, num62].shimmer())
{
                                    int num63 = 373;
                                    if (Main.tile[num57, num62].lava())
{
                                        num63 = 374;
                                    }
                                    else if (Main.tile[num57, num62].honey())
{
                                        num63 = 375;
                                    }
                                    int num64 = num62 - num58;
                                    if (genRand.Next(num64 * 3) <= 1)
{
                                        Main.tile[num57, num58].type = (ushort)num63;
                                        Main.tile[num57, num58].frameX = 0;
                                        Main.tile[num57, num58].frameY = 0;
                                        Main.tile[num57, num58].active(active: true);
                                        break;
                                    }
                                }
                            }
                        }
                        if (!Main.tile[num57, num58].active() && genRand.Next(4) == 0)
{
                            Tile tile4 = Main.tile[num57, num58 - 1];
                            if (TileID.Sets.Conversion.Sandstone[tile4.type] || TileID.Sets.Conversion.HardenedSand[tile4.type])
{
                                Main.tile[num57, num58].type = 461;
                                Main.tile[num57, num58].frameX = 0;
                                Main.tile[num57, num58].frameY = 0;
                                Main.tile[num57, num58].active(active: true);
                            }
                        }
                    }
                    if (Main.tile[num57, num58].type == 137)
                    {
                        int num65 = Main.tile[num57, num58].frameY / 18;
                        if (num65 <= 2 || num65 == 5)
{
                            int num66 = -1;
                            if (Main.tile[num57, num58].frameX >= 18)
{
                                num66 = 1;
                            }
                            if (Main.tile[num57 + num66, num58].halfBrick() || Main.tile[num57 + num66, num58].slope() != 0)
{
                                Main.tile[num57 + num66, num58].active(active: false);
                            }
                        }
                    }
                    else if (Main.tile[num57, num58].type == 162 && Main.tile[num57, num58 + 1].liquid == 0 && CanKillTile(num57, num58))
                    {
                        Main.tile[num57, num58].active(active: false);
                    }
                    if (Main.tile[num57, num58].wall == 13 || Main.tile[num57, num58].wall == 14)
                    {
                        Main.tile[num57, num58].liquid = 0;
                    }
                    if (Main.tile[num57, num58].type == 31)
                    {
                        int num67 = Main.tile[num57, num58].frameX / 18;
                        int num68 = 0;
                        int num69 = num57;
                        num68 += num67 / 2;
                        num68 = (drunkWorldGen ? ((Main.tile[num57, num58].wall == 83) ? 1 : 0) : (crimson ? 1 : 0));
                        num67 %= 2;
                        num69 -= num67;
                        int num70 = Main.tile[num57, num58].frameY / 18;
                        int num71 = 0;
                        int num72 = num58;
                        num71 += num70 / 2;
                        num70 %= 2;
                        num72 -= num70;
                        for (int num73 = 0; num73 < 2; num73++)
{
                            for (int num74 = 0; num74 < 2; num74++)
{
                                int x6 = num69 + num73;
                                int y6 = num72 + num74;
                                Main.tile[x6, y6].active(active: true);
                                Main.tile[x6, y6].slope(0);
                                Main.tile[x6, y6].halfBrick(halfBrick: false);
                                Main.tile[x6, y6].type = 31;
                                Main.tile[x6, y6].frameX = (short)(num73 * 18 + 36 * num68);
                                Main.tile[x6, y6].frameY = (short)(num74 * 18 + 36 * num71);
                            }
                        }
                    }
                    if (Main.tile[num57, num58].type == 12)
                    {
                        int num75 = Main.tile[num57, num58].frameX / 18;
                        int num76 = 0;
                        int num77 = num57;
                        num76 += num75 / 2;
                        num75 %= 2;
                        num77 -= num75;
                        int num78 = Main.tile[num57, num58].frameY / 18;
                        int num79 = 0;
                        int num80 = num58;
                        num79 += num78 / 2;
                        num78 %= 2;
                        num80 -= num78;
                        for (int num81 = 0; num81 < 2; num81++)
{
                            for (int num82 = 0; num82 < 2; num82++)
{
                                int x7 = num77 + num81;
                                int y7 = num80 + num82;
                                Main.tile[x7, y7].active(active: true);
                                Main.tile[x7, y7].slope(0);
                                Main.tile[x7, y7].halfBrick(halfBrick: false);
                                Main.tile[x7, y7].type = 12;
                                Main.tile[x7, y7].frameX = (short)(num81 * 18 + 36 * num76);
                                Main.tile[x7, y7].frameY = (short)(num82 * 18 + 36 * num79);
                            }
                            if (!Main.tile[num81, num58 + 2].active())
{
                                Main.tile[num81, num58 + 2].active(active: true);
                                if (!Main.tileSolid[Main.tile[num81, num58 + 2].type] || Main.tileSolidTop[Main.tile[num81, num58 + 2].type])
{
                                    Main.tile[num81, num58 + 2].type = 0;
                                }
                            }
                            Main.tile[num81, num58 + 2].slope(0);
                            Main.tile[num81, num58 + 2].halfBrick(halfBrick: false);
                        }
                    }
                    if (Main.tile[num57, num58].type == 639)
                    {
                        int num83 = Main.tile[num57, num58].frameX / 18;
                        int num84 = 0;
                        int num85 = num57;
                        num84 += num83 / 2;
                        num83 %= 2;
                        num85 -= num83;
                        int num86 = Main.tile[num57, num58].frameY / 18;
                        int num87 = 0;
                        int num88 = num58;
                        num87 += num86 / 2;
                        num86 %= 2;
                        num88 -= num86;
                        for (int num89 = 0; num89 < 2; num89++)
{
                            for (int num90 = 0; num90 < 2; num90++)
{
                                int x8 = num85 + num89;
                                int y8 = num88 + num90;
                                Main.tile[x8, y8].active(active: true);
                                Main.tile[x8, y8].slope(0);
                                Main.tile[x8, y8].halfBrick(halfBrick: false);
                                Main.tile[x8, y8].type = 639;
                                Main.tile[x8, y8].frameX = (short)(num89 * 18 + 36 * num84);
                                Main.tile[x8, y8].frameY = (short)(num90 * 18 + 36 * num87);
                            }
                            if (!Main.tile[num89, num58 + 2].active())
{
                                Main.tile[num89, num58 + 2].active(active: true);
                                if (!Main.tileSolid[Main.tile[num89, num58 + 2].type] || Main.tileSolidTop[Main.tile[num89, num58 + 2].type])
{
                                    Main.tile[num89, num58 + 2].type = 0;
                                }
                            }
                            Main.tile[num89, num58 + 2].slope(0);
                            Main.tile[num89, num58 + 2].halfBrick(halfBrick: false);
                        }
                    }
                    if (TileID.Sets.BasicChest[Main.tile[num57, num58].type])
                    {
                        int num91 = Main.tile[num57, num58].frameX / 18;
                        int num92 = 0;
                        ushort num93 = 21;
                        int num94 = num57;
                        int num95 = num58 - Main.tile[num57, num58].frameY / 18;
                        if (Main.tile[num57, num58].type == 467)
{
                            num93 = 467;
                        }
                        if (TileID.Sets.BasicChest[Main.tile[num57, num58].type])
{
                            num93 = Main.tile[num57, num58].type;
                        }
                        while (num91 >= 2)
{
                            num92++;
                            num91 -= 2;
                        }
                        num94 -= num91;
                        int num96 = Chest.FindChest(num94, num95);
                        if (num96 != -1)
{
                            switch (Main.chest[num96].item[0].type)
{
                            case 1156:
                                num92 = 23;
                                break;
                            case 1571:
                                num92 = 24;
                                break;
                            case 1569:
                                num92 = 25;
                                break;
                            case 1260:
                                num92 = 26;
                                break;
                            case 1572:
                                num92 = 27;
                                break;
                            }
                        }
                        for (int num97 = 0; num97 < 2; num97++)
{
                            for (int num98 = 0; num98 < 2; num98++)
{
                                int x9 = num94 + num97;
                                int y9 = num95 + num98;
                                Main.tile[x9, y9].active(active: true);
                                Main.tile[x9, y9].slope(0);
                                Main.tile[x9, y9].halfBrick(halfBrick: false);
                                Main.tile[x9, y9].type = num93;
                                Main.tile[x9, y9].frameX = (short)(num97 * 18 + 36 * num92);
                                Main.tile[x9, y9].frameY = (short)(num98 * 18);
                            }
                            if (!Main.tile[num97, num58 + 2].active())
{
                                Main.tile[num97, num58 + 2].active(active: true);
                                if (!Main.tileSolid[Main.tile[num97, num58 + 2].type] || Main.tileSolidTop[Main.tile[num97, num58 + 2].type])
{
                                    Main.tile[num97, num58 + 2].type = 0;
                                }
                            }
                            Main.tile[num97, num58 + 2].slope(0);
                            Main.tile[num97, num58 + 2].halfBrick(halfBrick: false);
                        }
                    }
                    if (Main.tile[num57, num58].type == 28)
                    {
                        int num99 = Main.tile[num57, num58].frameX / 18;
                        int num100 = 0;
                        int num101 = num57;
                        while (num99 >= 2)
{
                            num100++;
                            num99 -= 2;
                        }
                        num101 -= num99;
                        int num102 = Main.tile[num57, num58].frameY / 18;
                        int num103 = 0;
                        int num104 = num58;
                        while (num102 >= 2)
{
                            num103++;
                            num102 -= 2;
                        }
                        num104 -= num102;
                        for (int num105 = 0; num105 < 2; num105++)
{
                            for (int num106 = 0; num106 < 2; num106++)
{
                                int x10 = num101 + num105;
                                int y10 = num104 + num106;
                                Main.tile[x10, y10].active(active: true);
                                Main.tile[x10, y10].slope(0);
                                Main.tile[x10, y10].halfBrick(halfBrick: false);
                                Main.tile[x10, y10].type = 28;
                                Main.tile[x10, y10].frameX = (short)(num105 * 18 + 36 * num100);
                                Main.tile[x10, y10].frameY = (short)(num106 * 18 + 36 * num103);
                            }
                            if (!Main.tile[num105, num58 + 2].active())
{
                                Main.tile[num105, num58 + 2].active(active: true);
                                if (!Main.tileSolid[Main.tile[num105, num58 + 2].type] || Main.tileSolidTop[Main.tile[num105, num58 + 2].type])
{
                                    Main.tile[num105, num58 + 2].type = 0;
                                }
                            }
                            Main.tile[num105, num58 + 2].slope(0);
                            Main.tile[num105, num58 + 2].halfBrick(halfBrick: false);
                        }
                    }
                    if (Main.tile[num57, num58].type == 26)
                    {
                        int num107 = Main.tile[num57, num58].frameX / 18;
                        int num108 = 0;
                        int num109 = num57;
                        int num110 = num58 - Main.tile[num57, num58].frameY / 18;
                        while (num107 >= 3)
{
                            num108++;
                            num107 -= 3;
                        }
                        num109 -= num107;
                        num108 = ((!drunkWorldGen) ? (crimson ? 1 : 0) : ((Main.tile[num57, num58].wall == 83) ? 1 : 0));
                        for (int num111 = 0; num111 < 3; num111++)
{
                            for (int num112 = 0; num112 < 2; num112++)
{
                                int x11 = num109 + num111;
                                int y11 = num110 + num112;
                                Main.tile[x11, y11].active(active: true);
                                Main.tile[x11, y11].slope(0);
                                Main.tile[x11, y11].halfBrick(halfBrick: false);
                                Main.tile[x11, y11].type = 26;
                                Main.tile[x11, y11].frameX = (short)(num111 * 18 + 54 * num108);
                                Main.tile[x11, y11].frameY = (short)(num112 * 18);
                            }
                            if (!Main.tile[num109 + num111, num110 + 2].active() || !Main.tileSolid[Main.tile[num109 + num111, num110 + 2].type] || Main.tileSolidTop[Main.tile[num109 + num111, num110 + 2].type])
{
                                Main.tile[num109 + num111, num110 + 2].active(active: true);
                                if (!TileID.Sets.Platforms[Main.tile[num109 + num111, num110 + 2].type])
{
                                    if (Main.tile[num109 + num111, num110 + 2].type == 484)
{
                                        Main.tile[num109 + num111, num110 + 2].type = 397;
                                    }
                                    else if (TileID.Sets.Boulders[Main.tile[num109 + num111, num110 + 2].type] || !Main.tileSolid[Main.tile[num109 + num111, num110 + 2].type] || Main.tileSolidTop[Main.tile[num109 + num111, num110 + 2].type])
{
                                        Main.tile[num109 + num111, num110 + 2].type = 0;
                                    }
                                }
                            }
                            Main.tile[num109 + num111, num110 + 2].slope(0);
                            Main.tile[num109 + num111, num110 + 2].halfBrick(halfBrick: false);
                            if (Main.tile[num109 + num111, num110 + 3].type == 28 && Main.tile[num109 + num111, num110 + 3].frameY % 36 >= 18)
{
                                Main.tile[num109 + num111, num110 + 3].type = 0;
                                Main.tile[num109 + num111, num110 + 3].active(active: false);
                            }
                        }
                        for (int num113 = 0; num113 < 3; num113++)
{
                            if ((Main.tile[num109 - 1, num110 + num113].type == 28 || Main.tile[num109 - 1, num110 + num113].type == 12 || Main.tile[num109 - 1, num110 + num113].type == 639) && Main.tile[num109 - 1, num110 + num113].frameX % 36 < 18)
{
                                Main.tile[num109 - 1, num110 + num113].type = 0;
                                Main.tile[num109 - 1, num110 + num113].active(active: false);
                            }
                            if ((Main.tile[num109 + 3, num110 + num113].type == 28 || Main.tile[num109 + 3, num110 + num113].type == 12 || Main.tile[num109 - 1, num110 + num113].type == 639) && Main.tile[num109 + 3, num110 + num113].frameX % 36 >= 18)
{
                                Main.tile[num109 + 3, num110 + num113].type = 0;
                                Main.tile[num109 + 3, num110 + num113].active(active: false);
                            }
                        }
                    }
                    if (Main.tile[num57, num58].type == 237 && Main.tile[num57, num58 + 1].type == 232)
                    {
                        Main.tile[num57, num58 + 1].type = 226;
                    }
                    if (Main.tile[num57, num58].wall == 87)
                    {
                        Main.tile[num57, num58].liquid = 0;
                    }
                }
            }
        });
        AddGenerationPass("Lihzahrd Altars", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num53 = 0; num53 < 3; num53++)
            {
                for (int num54 = 0; num54 < 2; num54++)
                {
                    int x5 = GenVars.lAltarX + num53;
                    int y5 = GenVars.lAltarY + num54;
                    Main.tile[x5, y5].active(active: true);
                    Main.tile[x5, y5].type = 237;
                    Main.tile[x5, y5].frameX = (short)(num53 * 18);
                    Main.tile[x5, y5].frameY = (short)(num54 * 18);
                }
                Main.tile[GenVars.lAltarX + num53, GenVars.lAltarY + 2].active(active: true);
                Main.tile[GenVars.lAltarX + num53, GenVars.lAltarY + 2].slope(0);
                Main.tile[GenVars.lAltarX + num53, GenVars.lAltarY + 2].halfBrick(halfBrick: false);
                Main.tile[GenVars.lAltarX + num53, GenVars.lAltarY + 2].type = 226;
            }
            for (int num55 = 0; num55 < 3; num55++)
            {
                for (int num56 = 0; num56 < 2; num56++)
                {
                    int i2 = GenVars.lAltarX + num55;
                    int j2 = GenVars.lAltarY + num56;
                    SquareTileFrame(i2, j2);
                }
            }
        });
        AddGenerationPass("Micro Biomes", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
            //IL_0182: Unknown result type (might be due to invalid IL or missing references)
            //IL_0243: Unknown result type (might be due to invalid IL or missing references)
            //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
            //IL_02f0: Unknown result type (might be due to invalid IL or missing references)
            //IL_055d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0622: Unknown result type (might be due to invalid IL or missing references)
            //IL_04c4: Unknown result type (might be due to invalid IL or missing references)
            //IL_0494: Unknown result type (might be due to invalid IL or missing references)
            //IL_06cd: Unknown result type (might be due to invalid IL or missing references)
            progress.Message = Lang.gen[76].Value + "..Dead Man's Chests";
            _ = (double)(Main.maxTilesX * Main.maxTilesY) / 5040000.0;
            double num31 = 10.0;
            if (getGoodWorldGen || noTrapsWorldGen)
            {
                num31 *= 3.0;
            }
            DeadMansChestBiome deadMansChestBiome = GenVars.configuration.CreateBiome<DeadMansChestBiome>();
            List<int> possibleChestsToTrapify = deadMansChestBiome.GetPossibleChestsToTrapify(GenVars.structures);
            int random = passConfig.Get<WorldGenRange>("DeadManChests").GetRandom(genRand);
            int num32 = 0;
            int num33 = 3000;
            Point origin = default(Point);
            while (num32 < random && possibleChestsToTrapify.Count > 0)
            {
                num33--;
                if (num33 <= 0)
                {
                    break;
                }
                int num34 = possibleChestsToTrapify[genRand.Next(possibleChestsToTrapify.Count)];
                ((Point)(ref origin))._002Ector(Main.chest[num34].x, Main.chest[num34].y);
                deadMansChestBiome.Place(origin, GenVars.structures);
                num32++;
                possibleChestsToTrapify.Remove(num34);
            }
            progress.Message = Lang.gen[76].Value + "..Thin Ice";
            progress.Set(1.0 / num31);
            if (!notTheBees || remixWorldGen)
            {
                ThinIceBiome thinIceBiome = GenVars.configuration.CreateBiome<ThinIceBiome>();
                int random2 = passConfig.Get<WorldGenRange>("ThinIcePatchCount").GetRandom(genRand);
                int num35 = 0;
                int num36 = 1000;
                int num37 = 0;
                while (num37 < random2)
                {
                    if (thinIceBiome.Place(RandomWorldPoint((int)Main.worldSurface + 20, 50, 200, 50), GenVars.structures))
                    {
                        num37++;
                        num35 = 0;
                    }
                    else
                    {
                        num35++;
                        if (num35 > num36)
{
                            num37++;
                            num35 = 0;
                        }
                    }
                }
            }
            progress.Message = Lang.gen[76].Value + "..Sword Shrines";
            progress.Set(0.1);
            progress.Set(2.0 / num31);
            EnchantedSwordBiome enchantedSwordBiome = GenVars.configuration.CreateBiome<EnchantedSwordBiome>();
            int num38 = passConfig.Get<WorldGenRange>("SwordShrineAttempts").GetRandom(genRand);
            double num39 = passConfig.Get<double>("SwordShrinePlacementChance");
            if (tenthAnniversaryWorldGen)
            {
                num38 *= 2;
                num39 /= 2.0;
            }
            Point origin2 = default(Point);
            for (int num40 = 0; num40 < num38; num40++)
            {
                if ((num40 == 0 && tenthAnniversaryWorldGen) || !(genRand.NextDouble() > num39))
                {
                    int num41 = 0;
                    while (num41++ <= Main.maxTilesX)
                    {
                        origin2.Y = (int)GenVars.worldSurface + genRand.Next(50, 100);
                        if (genRand.Next(2) == 0)
{
                            origin2.X = genRand.Next(50, (int)((double)Main.maxTilesX * 0.3));
                        }
                        else
{
                            origin2.X = genRand.Next((int)((double)Main.maxTilesX * 0.7), Main.maxTilesX - 50);
                        }
                        if (enchantedSwordBiome.Place(origin2, GenVars.structures))
{
                            break;
                        }
                    }
                }
            }
            progress.Message = Lang.gen[76].Value + "..Campsites";
            progress.Set(0.2);
            progress.Set(3.0 / num31);
            if (!notTheBees || remixWorldGen)
            {
                CampsiteBiome campsiteBiome = GenVars.configuration.CreateBiome<CampsiteBiome>();
                int random3 = passConfig.Get<WorldGenRange>("CampsiteCount").GetRandom(genRand);
                num33 = 1000;
                int num42 = 0;
                while (num42 < random3)
                {
                    num33--;
                    if (num33 <= 0)
                    {
                        break;
                    }
                    if (campsiteBiome.Place(RandomWorldPoint((int)Main.worldSurface, beachDistance, 200, beachDistance), GenVars.structures))
                    {
                        num42++;
                    }
                }
            }
            progress.Message = Lang.gen[76].Value + "..Explosive Traps";
            progress.Set(4.0 / num31);
            if (!notTheBees || remixWorldGen)
            {
                MiningExplosivesBiome miningExplosivesBiome = GenVars.configuration.CreateBiome<MiningExplosivesBiome>();
                int num43 = passConfig.Get<WorldGenRange>("ExplosiveTrapCount").GetRandom(genRand);
                if ((getGoodWorldGen || noTrapsWorldGen) && !notTheBees)
                {
                    num43 = (int)((double)num43 * 1.5);
                }
                num33 = 3000;
                int num44 = 0;
                while (num44 < num43)
                {
                    num33--;
                    if (num33 <= 0)
                    {
                        break;
                    }
                    if (remixWorldGen)
                    {
                        if (miningExplosivesBiome.Place(RandomWorldPoint((int)Main.worldSurface, beachDistance, (int)GenVars.rockLayer, beachDistance), GenVars.structures))
{
                            num44++;
                        }
                    }
                    else if (miningExplosivesBiome.Place(RandomWorldPoint((int)GenVars.rockLayer, beachDistance, 200, beachDistance), GenVars.structures))
                    {
                        num44++;
                    }
                }
            }
            progress.Message = Lang.gen[76].Value + "..Living Trees";
            progress.Set(0.3);
            progress.Set(5.0 / num31);
            MahoganyTreeBiome mahoganyTreeBiome = GenVars.configuration.CreateBiome<MahoganyTreeBiome>();
            int random4 = passConfig.Get<WorldGenRange>("LivingTreeCount").GetRandom(genRand);
            int num45 = 0;
            int num46 = 0;
            while (num45 < random4 && num46 < 20000)
            {
                if (mahoganyTreeBiome.Place(RandomWorldPoint((int)Main.worldSurface + 50, 50, 500, 50), GenVars.structures))
                {
                    num45++;
                }
                num46++;
            }
            progress.Message = Lang.gen[76].Value + "..Long Minecart Tracks";
            progress.Set(0.4);
            progress.Set(6.0 / num31);
            progress.Set(7.0 / num31);
            TrackGenerator trackGenerator = new TrackGenerator();
            int random5 = passConfig.Get<WorldGenRange>("LongTrackCount").GetRandom(genRand);
            WorldGenRange worldGenRange = passConfig.Get<WorldGenRange>("LongTrackLength");
            int maxTilesX = Main.maxTilesX;
            int num47 = 0;
            int num48 = 0;
            while (num48 < random5)
            {
                if (trackGenerator.Place(RandomWorldPoint((int)Main.worldSurface, 10, 200, 10), worldGenRange.ScaledMinimum, worldGenRange.ScaledMaximum))
                {
                    num48++;
                    num47 = 0;
                }
                else
                {
                    num47++;
                    if (num47 > maxTilesX)
                    {
                        num48++;
                        num47 = 0;
                    }
                }
            }
            progress.Message = Lang.gen[76].Value + "..Standard Minecart Tracks";
            progress.Set(8.0 / num31);
            random5 = passConfig.Get<WorldGenRange>("StandardTrackCount").GetRandom(genRand);
            worldGenRange = passConfig.Get<WorldGenRange>("StandardTrackLength");
            num47 = 0;
            int num49 = 0;
            while (num49 < random5)
            {
                if (trackGenerator.Place(RandomWorldPoint((int)Main.worldSurface, 10, 200, 10), worldGenRange.ScaledMinimum, worldGenRange.ScaledMaximum))
                {
                    num49++;
                    num47 = 0;
                }
                else
                {
                    num47++;
                    if (num47 > maxTilesX)
                    {
                        num49++;
                        num47 = 0;
                    }
                }
            }
            progress.Message = Lang.gen[76].Value + "..Lava Traps";
            progress.Set(9.0 / num31);
            if (!notTheBees)
            {
                double num50 = (double)Main.maxTilesX * 0.02;
                if (noTrapsWorldGen)
                {
                    num31 *= 5.0;
                }
                else if (getGoodWorldGen)
                {
                    num31 *= 2.0;
                }
                for (int num51 = 0; (double)num51 < num50; num51++)
                {
                    for (int num52 = 0; num52 < 10150; num52++)
                    {
                        int x4 = genRand.Next(200, Main.maxTilesX - 200);
                        int y4 = genRand.Next(GenVars.lavaLine - 100, Main.maxTilesY - 210);
                        if (placeLavaTrap(x4, y4))
{
                            break;
                        }
                    }
                }
            }
            progress.Set(1.0);
        });
        AddGenerationPass("Water Plants", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
            //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
            //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
            //IL_00de: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
            //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
            progress.Message = Lang.gen[88].Value;
            int num23 = (int)Main.worldSurface;
            if (remixWorldGen)
            {
                num23 = Main.maxTilesY - 200;
            }
            for (int num24 = 20; num24 < Main.maxTilesX - 20; num24++)
            {
                progress.Set((double)num24 / (double)Main.maxTilesX);
                for (int num25 = 1; num25 < num23; num25++)
                {
                    if (genRand.Next(5) == 0 && Main.tile[num24, num25].liquid > 0)
                    {
                        if (!Main.tile[num24, num25].active())
{
                            if (genRand.Next(2) == 0)
{
                                PlaceLilyPad(num24, num25);
                            }
                            else
{
                                Point val = PlaceCatTail(num24, num25);
                                if (InWorld(val.X, val.Y))
{
                                    int num26 = genRand.Next(14);
                                    for (int num27 = 0; num27 < num26; num27++)
{
                                        GrowCatTail(val.X, val.Y);
                                    }
                                    SquareTileFrame(val.X, val.Y);
                                }
                            }
                        }
                        if ((!Main.tile[num24, num25].active() || Main.tile[num24, num25].type == 61 || Main.tile[num24, num25].type == 74) && PlaceBamboo(num24, num25))
{
                            int num28 = genRand.Next(10, 20);
                            for (int num29 = 0; num29 < num28 && PlaceBamboo(num24, num25 - num29); num29++)
{
                            }
                        }
                    }
                }
                int num30 = Main.UnderworldLayer;
                while ((double)num30 > Main.worldSurface)
                {
                    if (Main.tile[num24, num30].type == 53 && genRand.Next(3) != 0)
                    {
                        GrowCheckSeaweed(num24, num30);
                    }
                    else if (Main.tile[num24, num30].type == 549)
                    {
                        GrowCheckSeaweed(num24, num30);
                    }
                    num30--;
                }
            }
        });
        AddGenerationPass("Stalac", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            progress.Set(1.0);
            for (int num19 = 20; num19 < Main.maxTilesX - 20; num19++)
            {
                for (int num20 = (int)Main.worldSurface; num20 < Main.maxTilesY - 20; num20++)
                {
                    if ((Main.tenthAnniversaryWorld || drunkWorldGen || genRand.Next(5) == 0) && Main.tile[num19, num20 - 1].liquid == 0)
                    {
                        int num21 = genRand.Next(7);
                        int treeTileType = 0;
                        switch (num21)
{
                        case 0:
                            treeTileType = 583;
                            break;
                        case 1:
                            treeTileType = 584;
                            break;
                        case 2:
                            treeTileType = 585;
                            break;
                        case 3:
                            treeTileType = 586;
                            break;
                        case 4:
                            treeTileType = 587;
                            break;
                        case 5:
                            treeTileType = 588;
                            break;
                        case 6:
                            treeTileType = 589;
                            break;
                        }
                        TryGrowingTreeByType(treeTileType, num19, num20);
                    }
                    if (!oceanDepths(num19, num20) && !Main.tile[num19, num20].active() && genRand.Next(5) == 0)
                    {
                        if ((Main.tile[num19, num20 - 1].type == 1 || Main.tile[num19, num20 - 1].type == 147 || Main.tile[num19, num20 - 1].type == 161 || Main.tile[num19, num20 - 1].type == 25 || Main.tile[num19, num20 - 1].type == 203 || Main.tileStone[Main.tile[num19, num20 - 1].type] || Main.tileMoss[Main.tile[num19, num20 - 1].type]) && !Main.tile[num19, num20].active() && !Main.tile[num19, num20 + 1].active())
{
                            Main.tile[num19, num20 - 1].slope(0);
                        }
                        if ((Main.tile[num19, num20 + 1].type == 1 || Main.tile[num19, num20 + 1].type == 147 || Main.tile[num19, num20 + 1].type == 161 || Main.tile[num19, num20 + 1].type == 25 || Main.tile[num19, num20 + 1].type == 203 || Main.tileStone[Main.tile[num19, num20 + 1].type] || Main.tileMoss[Main.tile[num19, num20 + 1].type]) && !Main.tile[num19, num20].active() && !Main.tile[num19, num20 - 1].active())
{
                            Main.tile[num19, num20 + 1].slope(0);
                        }
                        PlaceTight(num19, num20);
                    }
                }
                for (int num22 = 5; num22 < (int)Main.worldSurface; num22++)
                {
                    if ((Main.tile[num19, num22 - 1].type == 147 || Main.tile[num19, num22 - 1].type == 161) && genRand.Next(5) == 0)
                    {
                        if (!Main.tile[num19, num22].active() && !Main.tile[num19, num22 + 1].active())
{
                            Main.tile[num19, num22 - 1].slope(0);
                        }
                        PlaceTight(num19, num22);
                    }
                    if ((Main.tile[num19, num22 - 1].type == 25 || Main.tile[num19, num22 - 1].type == 203) && genRand.Next(5) == 0)
                    {
                        if (!Main.tile[num19, num22].active() && !Main.tile[num19, num22 + 1].active())
{
                            Main.tile[num19, num22 - 1].slope(0);
                        }
                        PlaceTight(num19, num22);
                    }
                    if ((Main.tile[num19, num22 + 1].type == 25 || Main.tile[num19, num22 + 1].type == 203) && genRand.Next(5) == 0)
                    {
                        if (!Main.tile[num19, num22].active() && !Main.tile[num19, num22 - 1].active())
{
                            Main.tile[num19, num22 + 1].slope(0);
                        }
                        PlaceTight(num19, num22);
                    }
                }
            }
        });
        AddGenerationPass("Remove Broken Traps", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_0071: Unknown result type (might be due to invalid IL or missing references)
            //IL_0080: Unknown result type (might be due to invalid IL or missing references)
            if (!noTrapsWorldGen || tenthAnniversaryWorldGen || notTheBees)
            {
                progress.Message = Lang.gen[82].Value;
                List<Point> list = new List<Point>();
                int num16 = 50;
                for (int num17 = num16; num17 < Main.maxTilesX - num16; num17++)
                {
                    double value = (double)(num17 - num16) / (double)(Main.maxTilesX - num16 * 2);
                    progress.Set(value);
                    for (int num18 = 50; num18 < Main.maxTilesY - 50; num18++)
                    {
                        if (Main.tile[num17, num18].wire() && !list.Contains(new Point(num17, num18)))
{
                            ClearBrokenTraps(new Point(num17, num18), list);
                        }
                    }
                }
            }
        });
        AddGenerationPass("Final Cleanup", delegate(GenerationProgress progress, GameConfiguration passConfig)
        {
            //IL_0019: Unknown result type (might be due to invalid IL or missing references)
            Main.tileSolid[484] = false;
            FillWallHolesInArea(new Rectangle(0, 0, Main.maxTilesX, (int)Main.worldSurface));
            progress.Message = Lang.gen[86].Value;
            for (int i = 0; i < Main.maxTilesX; i++)
            {
                progress.Set((double)i / (double)Main.maxTilesX);
                int num = 0;
                while (num < Main.maxTilesY)
                {
                    Tile tile = Main.tile[i, num];
                    if (tile.active() && !SolidTile(i, num + 1))
                    {
                        tile = Main.tile[i, num];
                        if (tile.type != 53)
{
                            tile = Main.tile[i, num];
                            if (tile.type != 112)
{
                                tile = Main.tile[i, num];
                                if (tile.type != 234)
{
                                    tile = Main.tile[i, num];
                                    if (tile.type != 224)
{
                                        tile = Main.tile[i, num];
                                        if (tile.type != 123)
{
                                            goto IL_06be;
                                        }
                                    }
                                }
                            }
                        }
                        if ((double)num < Main.worldSurface + 10.0)
{
                            tile = Main.tile[i, num + 1];
                            if (!tile.active())
{
                                tile = Main.tile[i, num + 1];
                                if (tile.wall != 191 && !oceanDepths(i, num))
{
                                    int num2 = 10;
                                    int num3 = num + 1;
                                    for (int j = num3; j < num3 + 10; j++)
{
                                        tile = Main.tile[i, j];
                                        if (tile.active())
{
                                            tile = Main.tile[i, j];
                                            if (tile.type == 314)
{
                                                num2 = 0;
                                                break;
                                            }
                                        }
                                    }
                                    while (true)
{
                                        tile = Main.tile[i, num3];
                                        if (tile.active() || num2 <= 0 || num3 >= Main.maxTilesY - 50)
{
                                            break;
                                        }
                                        tile = Main.tile[i, num3 - 1];
                                        tile.slope(0);
                                        tile = Main.tile[i, num3 - 1];
                                        tile.halfBrick(halfBrick: false);
                                        tile = Main.tile[i, num3];
                                        tile.active(active: true);
                                        tile = Main.tile[i, num3];
                                        ref ushort type = ref tile.type;
                                        tile = Main.tile[i, num];
                                        type = tile.type;
                                        tile = Main.tile[i, num3];
                                        tile.slope(0);
                                        tile = Main.tile[i, num3];
                                        tile.halfBrick(halfBrick: false);
                                        num3++;
                                        num2--;
                                    }
                                    if (num2 == 0)
{
                                        tile = Main.tile[i, num3];
                                        if (!tile.active())
{
                                            tile = Main.tile[i, num];
                                            switch (tile.type)
{
                                            case 53:
                                                tile = Main.tile[i, num3];
                                                tile.type = 397;
                                                tile = Main.tile[i, num3];
                                                tile.active(active: true);
                                                break;
                                            case 112:
                                                tile = Main.tile[i, num3];
                                                tile.type = 398;
                                                tile = Main.tile[i, num3];
                                                tile.active(active: true);
                                                break;
                                            case 234:
                                                tile = Main.tile[i, num3];
                                                tile.type = 399;
                                                tile = Main.tile[i, num3];
                                                tile.active(active: true);
                                                break;
                                            case 224:
                                                tile = Main.tile[i, num3];
                                                tile.type = 147;
                                                tile = Main.tile[i, num3];
                                                tile.active(active: true);
                                                break;
                                            case 123:
                                                tile = Main.tile[i, num3];
                                                tile.type = 1;
                                                tile = Main.tile[i, num3];
                                                tile.active(active: true);
                                                break;
                                            }
                                            goto IL_0690;
                                        }
                                    }
                                    tile = Main.tile[i, num3];
                                    if (tile.active())
{
                                        bool[] tileSolid = Main.tileSolid;
                                        tile = Main.tile[i, num3];
                                        if (tileSolid[tile.type])
{
                                            bool[] tileSolidTop = Main.tileSolidTop;
                                            tile = Main.tile[i, num3];
                                            if (!tileSolidTop[tile.type])
{
                                                tile = Main.tile[i, num3];
                                                tile.slope(0);
                                                tile = Main.tile[i, num3];
                                                tile.halfBrick(halfBrick: false);
                                            }
                                        }
                                    }
                                    goto IL_0690;
                                }
                            }
                        }
                        bool[] tileSolid2 = Main.tileSolid;
                        tile = Main.tile[i, num + 1];
                        if (tileSolid2[tile.type])
{
                            bool[] tileSolidTop2 = Main.tileSolidTop;
                            tile = Main.tile[i, num + 1];
                            if (!tileSolidTop2[tile.type])
{
                                tile = Main.tile[i, num + 1];
                                if (!tile.topSlope())
{
                                    tile = Main.tile[i, num + 1];
                                    if (!tile.halfBrick())
{
                                        goto IL_05aa;
                                    }
                                }
                                tile = Main.tile[i, num + 1];
                                tile.slope(0);
                                tile = Main.tile[i, num + 1];
                                tile.halfBrick(halfBrick: false);
                                goto IL_0690;
                            }
                        }
                        goto IL_05aa;
                    }
                    goto IL_06be;
                    IL_05aa:
                    tile = Main.tile[i, num];
                    switch (tile.type)
                    {
                    case 53:
                        tile = Main.tile[i, num];
                        tile.type = 397;
                        break;
                    case 112:
                        tile = Main.tile[i, num];
                        tile.type = 398;
                        break;
                    case 234:
                        tile = Main.tile[i, num];
                        tile.type = 399;
                        break;
                    case 224:
                        tile = Main.tile[i, num];
                        tile.type = 147;
                        break;
                    case 123:
                        tile = Main.tile[i, num];
                        tile.type = 1;
                        break;
                    }
                    goto IL_0690;
                    IL_0753:
                    tile = Main.tile[i, num];
                    if (tile.type != 485)
                    {
                        tile = Main.tile[i, num];
                        if (tile.type != 187)
{
                            tile = Main.tile[i, num];
                            if (tile.type != 165)
{
                                goto IL_07bb;
                            }
                        }
                    }
                    TileFrame(i, num);
                    goto IL_07bb;
                    IL_0825:
                    tile = Main.tile[i, num];
                    if (tile.type == 26)
                    {
                        TileFrame(i, num);
                    }
                    bool[] isATreeTrunk = TileID.Sets.IsATreeTrunk;
                    tile = Main.tile[i, num];
                    if (!isATreeTrunk[tile.type])
                    {
                        tile = Main.tile[i, num];
                        if (tile.type != 323)
{
                            goto IL_0896;
                        }
                    }
                    TileFrame(i, num);
                    goto IL_0896;
                    IL_0690:
                    tile = Main.tile[i, num - 1];
                    if (tile.type == 323)
                    {
                        TileFrame(i, num - 1);
                    }
                    goto IL_06be;
                    IL_07bb:
                    tile = Main.tile[i, num];
                    if (tile.type == 28)
                    {
                        TileFrame(i, num);
                    }
                    tile = Main.tile[i, num];
                    if (tile.type != 10)
                    {
                        tile = Main.tile[i, num];
                        if (tile.type != 11)
{
                            goto IL_0825;
                        }
                    }
                    TileFrame(i, num);
                    goto IL_0825;
                    IL_0896:
                    tile = Main.tile[i, num];
                    if (tile.type == 137)
                    {
                        tile = Main.tile[i, num];
                        tile.slope(0);
                        tile = Main.tile[i, num];
                        tile.halfBrick(halfBrick: false);
                    }
                    tile = Main.tile[i, num];
                    if (tile.active())
                    {
                        bool[] boulders = TileID.Sets.Boulders;
                        tile = Main.tile[i, num];
                        if (boulders[tile.type])
{
                            tile = Main.tile[i, num];
                            int num4 = tile.frameX / 18;
                            int num5 = i;
                            num5 -= num4;
                            tile = Main.tile[i, num];
                            int num6 = tile.frameY / 18;
                            int num7 = num;
                            num7 -= num6;
                            bool flag = false;
                            for (int k = 0; k < 2; k++)
{
                                Tile tile2 = Main.tile[num5 + k, num7 - 1];
                                if (tile2 != null && tile2.active() && tile2.type == 26)
{
                                    flag = true;
                                    break;
                                }
                                for (int l = 0; l < 2; l++)
{
                                    int x = num5 + k;
                                    int y = num7 + l;
                                    tile = Main.tile[x, y];
                                    tile.active(active: true);
                                    tile = Main.tile[x, y];
                                    tile.slope(0);
                                    tile = Main.tile[x, y];
                                    tile.halfBrick(halfBrick: false);
                                    tile = Main.tile[x, y];
                                    ref ushort type2 = ref tile.type;
                                    tile = Main.tile[i, num];
                                    type2 = tile.type;
                                    tile = Main.tile[x, y];
                                    tile.frameX = (short)(k * 18);
                                    tile = Main.tile[x, y];
                                    tile.frameY = (short)(l * 18);
                                }
                            }
                            if (flag)
{
                                ushort num8 = 0;
                                tile = Main.tile[i, num];
                                if (tile.type == 484)
{
                                    num8 = 397;
                                }
                                for (int m = 0; m < 2; m++)
{
                                    for (int n = 0; n < 2; n++)
{
                                        int x2 = num5 + m;
                                        int y2 = num7 + n;
                                        tile = Main.tile[x2, y2];
                                        tile.active(active: true);
                                        tile = Main.tile[x2, y2];
                                        tile.slope(0);
                                        tile = Main.tile[x2, y2];
                                        tile.halfBrick(halfBrick: false);
                                        tile = Main.tile[x2, y2];
                                        tile.type = num8;
                                        tile = Main.tile[x2, y2];
                                        tile.frameX = 0;
                                        tile = Main.tile[x2, y2];
                                        tile.frameY = 0;
                                    }
                                }
                            }
                        }
                    }
                    tile = Main.tile[i, num];
                    if (tile.type == 323)
                    {
                        tile = Main.tile[i, num];
                        if (tile.liquid > 0)
{
                            KillTile(i, num);
                        }
                    }
                    bool[] wallDungeon = Main.wallDungeon;
                    tile = Main.tile[i, num];
                    if (wallDungeon[tile.wall])
                    {
                        tile = Main.tile[i, num];
                        tile.lava(lava: false);
                        tile = Main.tile[i, num];
                        if (tile.active())
{
                            tile = Main.tile[i, num];
                            if (tile.type == 56)
{
                                KillTile(i, num);
                                tile = Main.tile[i, num];
                                tile.lava(lava: false);
                                tile = Main.tile[i, num];
                                tile.liquid = byte.MaxValue;
                            }
                        }
                    }
                    tile = Main.tile[i, num];
                    if (tile.active())
                    {
                        tile = Main.tile[i, num];
                        if (tile.type == 314)
{
                            int num9 = 15;
                            int num10 = 1;
                            int num11 = num;
                            while (num - num11 < num9)
{
                                tile = Main.tile[i, num11];
                                tile.liquid = 0;
                                num11--;
                            }
                            for (num11 = num; num11 - num < num10; num11++)
{
                                tile = Main.tile[i, num11];
                                tile.liquid = 0;
                            }
                        }
                    }
                    tile = Main.tile[i, num];
                    if (tile.active())
                    {
                        tile = Main.tile[i, num];
                        if (tile.type == 332)
{
                            tile = Main.tile[i, num + 1];
                            if (!tile.active())
{
                                tile = Main.tile[i, num + 1];
                                tile.ClearEverything();
                                tile = Main.tile[i, num + 1];
                                tile.active(active: true);
                                tile = Main.tile[i, num + 1];
                                tile.type = 332;
                            }
                        }
                    }
                    if (i > beachDistance && i < Main.maxTilesX - beachDistance && (double)num < Main.worldSurface)
                    {
                        tile = Main.tile[i, num];
                        if (tile.liquid > 0)
{
                            tile = Main.tile[i, num];
                            if (tile.liquid < byte.MaxValue)
{
                                tile = Main.tile[i - 1, num];
                                if (tile.liquid < byte.MaxValue)
{
                                    tile = Main.tile[i + 1, num];
                                    if (tile.liquid < byte.MaxValue)
{
                                        tile = Main.tile[i, num + 1];
                                        if (tile.liquid < byte.MaxValue)
{
                                            bool[] clouds = TileID.Sets.Clouds;
                                            tile = Main.tile[i - 1, num];
                                            if (!clouds[tile.type])
{
                                                bool[] clouds2 = TileID.Sets.Clouds;
                                                tile = Main.tile[i + 1, num];
                                                if (!clouds2[tile.type])
{
                                                    bool[] clouds3 = TileID.Sets.Clouds;
                                                    tile = Main.tile[i, num + 1];
                                                    if (!clouds3[tile.type])
{
                                                        tile = Main.tile[i, num];
                                                        tile.liquid = 0;
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    num++;
                    continue;
                    IL_06be:
                    tile = Main.tile[i, num];
                    if (tile.wall != 187)
                    {
                        tile = Main.tile[i, num];
                        if (tile.wall != 216)
{
                            goto IL_0753;
                        }
                    }
                    tile = Main.tile[i, num];
                    if (tile.liquid > 0 && !remixWorldGen)
                    {
                        tile = Main.tile[i, num];
                        tile.liquid = byte.MaxValue;
                        tile = Main.tile[i, num];
                        tile.lava(lava: true);
                    }
                    goto IL_0753;
                }
            }
            int num12 = 0;
            int num13 = 3;
            num13 = GetWorldSize() switch
            {
                1 => 6,
                2 => 9,
                _ => 3,
            };
            if (tenthAnniversaryWorldGen)
            {
                num13 *= 5;
            }
            int num14 = 50;
            int minValue = num14;
            int minValue2 = num14;
            int maxValue = Main.maxTilesX - num14;
            int maxValue2 = Main.maxTilesY - 200;
            int num15 = 3000;
            while (num12 < num13)
            {
                num15--;
                if (num15 <= 0)
                {
                    break;
                }
                int x3 = genRand.Next(minValue, maxValue);
                int y3 = genRand.Next(minValue2, maxValue2);
                Tile tile3 = Main.tile[x3, y3];
                if (tile3.active() && tile3.type >= 0)
                {
                    bool flag2 = TileID.Sets.Dirt[tile3.type];
                    if (notTheBees)
                    {
                        flag2 = flag2 || TileID.Sets.Mud[tile3.type];
                    }
                    if (flag2)
                    {
                        num12++;
                        tile3.ClearTile();
                        tile3.active(active: true);
                        tile3.type = 668;
                    }
                }
            }
            if (noTrapsWorldGen)
            {
                FinishNoTraps();
            }
            if (Main.tenthAnniversaryWorld)
            {
                FinishTenthAnniversaryWorld();
            }
            if (drunkWorldGen)
            {
                FinishDrunkGen();
            }
            if (notTheBees)
            {
                NotTheBees();
                FinishNotTheBees();
            }
            if (getGoodWorldGen)
            {
                FinishGetGoodWorld();
            }
            if (remixWorldGen)
            {
                FinishRemixWorld();
            }
            ShimmerCleanUp();
            notTheBees = false;
            getGoodWorldGen = false;
            noTileActions = false;
            Main.tileSolid[659] = true;
            Main.tileSolid[GenVars.crackedType] = true;
            Main.tileSolid[484] = true;
            gen = false;
            Main.AnglerQuestSwap();
            skipFramingDuringGen = false;
            progress.Message = Lang.gen[87].Value;
        });
    }
References Terraria.WorldGen.AddGenerationPass(), Terraria.WorldGen.AddHellHouses(), Terraria.WorldGen.beachDistance, Terraria.WorldBuilding.GenVars.beachSandDungeonExtraWidth, Terraria.WorldBuilding.GenVars.beachSandJungleExtraWidth, Terraria.WorldBuilding.GenVars.beachSandRandomCenter, Terraria.WorldBuilding.GenVars.beachSandRandomWidthRange, Terraria.GameContent.Biomes.GraniteBiome.CanPlace(), Terraria.WorldGen.CaveOpenater(), Terraria.WorldGen.Caverer(), Terraria.WorldGen.Cavinator(), Terraria.WorldGen.ChasmRunner(), Terraria.Main.checkHalloween(), Terraria.Main.checkXMas(), Terraria.WorldGen.CloudIsland(), Terraria.WorldGen.CloudLake(), Terraria.WorldBuilding.GenVars.configuration, Terraria.WorldBuilding.GenVars.copper, Terraria.GameContent.TreeTopsInfo.CopyExistingWorldInfoForWorldGeneration(), Terraria.WorldGen.CrimPlaceHearts(), Terraria.WorldGen.crimson, Terraria.WorldBuilding.GenVars.crimsonLeft, Terraria.WorldGen.CrimStart(), Terraria.WorldGen.DesertCloudIsland(), Terraria.WorldGen.dontStarveWorldGen, Terraria.WorldGen.drunkWorldGen, Terraria.WorldBuilding.GenVars.dungeonLocation, Terraria.WorldBuilding.GenVars.dungeonSide, Terraria.WorldBuilding.GenVars.evilBiomeAvoidanceMidFixer, Terraria.WorldBuilding.GenVars.evilBiomeBeachAvoidance, Terraria.WorldBuilding.GenVars.floatingIslandHouseX, Terraria.WorldBuilding.GenVars.floatingIslandHouseY, Terraria.WorldBuilding.GenVars.floatingIslandStyle, Terraria.Lang.gen, Terraria.WorldGen.gen, Terraria.WorldGen.genRand, Terraria.WorldGen.getGoodWorldGen, Terraria.Localization.Language.GetTextValue(), Terraria.WorldBuilding.GenVars.gold, Terraria.WorldGen.grassSpread, Terraria.WorldGen.growGrassUnderground, Terraria.WorldGen.heartCount, Terraria.WorldGen.InWorld(), Terraria.WorldBuilding.GenVars.iron, Terraria.WorldGen.IsTileNearby(), Terraria.WorldBuilding.GenVars.jungleHut, Terraria.WorldBuilding.GenVars.jungleOriginX, Terraria.WorldGen.KillTile(), Terraria.WorldBuilding.GenVars.lakesBeachAvoidance, Terraria.WorldBuilding.GenVars.LakeX, Terraria.WorldBuilding.GenVars.lavaLine, Terraria.WorldBuilding.GenVars.leftBeachEnd, Terraria.WorldGen.MakeDungeon(), Terraria.WorldBuilding.GenVars.maxLakes, Terraria.WorldBuilding.GenVars.maxMushroomBiomes, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldBuilding.GenVars.maxTunnels, Terraria.WorldBuilding.GenVars.mCaveX, Terraria.WorldBuilding.GenVars.mCaveY, Terraria.WorldGen.Mountinater(), Terraria.WorldBuilding.GenVars.mushroomBiomesPosition, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.WorldGen.noTileActions, Terraria.WorldGen.NotTheBees(), Terraria.WorldBuilding.GenVars.numIslandHouses, Terraria.WorldBuilding.GenVars.numLakes, Terraria.WorldBuilding.GenVars.numMCaves, Terraria.WorldBuilding.GenVars.numMushroomBiomes, Terraria.WorldBuilding.GenVars.numOceanCaveTreasure, Terraria.WorldBuilding.GenVars.numPyr, Terraria.WorldBuilding.GenVars.numTunnels, Terraria.WorldGen.oceanDepths(), Terraria.WorldBuilding.GenVars.oceanWaterForcedJungleLength, Terraria.WorldBuilding.GenVars.oceanWaterStartRandomMax, Terraria.WorldBuilding.GenVars.oceanWaterStartRandomMin, Terraria.WorldGen.Place3x2(), Terraria.WorldGen.PlaceTile(), Terraria.WorldBuilding.GenVars.PyrX, Terraria.WorldBuilding.GenVars.PyrY, Terraria.Liquid.QuickWater(), Terraria.WorldGen.RandomizeBackgrounds(), Terraria.WorldGen.RandomizeCaveBackgrounds(), Terraria.WorldGen.RandomizeMoonState(), Terraria.WorldGen.RandomizeTreeStyle(), Terraria.WorldGen.RandomizeWeather(), Terraria.WorldGen.RandomRectanglePoint(), Terraria.WorldGen.RandomWorldPoint(), Terraria.Liquid.ReInit(), Terraria.Main.remixWorld, Terraria.WorldGen.remixWorldGen, Terraria.WorldGen.ResetGenerator(), Terraria.WorldBuilding.GenVars.rightBeachStart, Terraria.WorldBuilding.GenVars.rockLayer, Terraria.Main.rockLayer, Terraria.WorldBuilding.GenVars.rockLayerHigh, Terraria.WorldBuilding.GenVars.rockLayerLow, Terraria.WorldGen.ScanTileColumnAndRemoveClumps(), Terraria.WorldBuilding.GenerationProgress.Set(), Terraria.WorldGen.SetupStatueList(), Terraria.WorldBuilding.GenVars.shellStartXLeft, Terraria.WorldBuilding.GenVars.shellStartXRight, Terraria.WorldGen.ShroomPatch(), Terraria.WorldBuilding.GenVars.silver, Terraria.WorldGen.skipFramingDuringGen, Terraria.WorldBuilding.GenVars.skyLake, Terraria.WorldBuilding.GenVars.skyLakes, Terraria.WorldGen.SmallConsecutivesEliminated, Terraria.WorldGen.SmallConsecutivesFound, Terraria.WorldBuilding.GenVars.smallHolesBeachAvoidance, Terraria.WorldBuilding.GenVars.snowBottom, Terraria.WorldGen.SnowCloudIsland(), Terraria.WorldBuilding.GenVars.snowMaxX, Terraria.WorldBuilding.GenVars.snowMinX, Terraria.WorldBuilding.GenVars.snowOriginLeft, Terraria.WorldBuilding.GenVars.snowOriginRight, Terraria.WorldBuilding.GenVars.snowTop, Terraria.Enums.SolidTile, Terraria.WorldGen.SonOfLakinater(), Terraria.WorldGen.SpreadGrass(), Terraria.WorldBuilding.GenVars.structures, Terraria.WorldBuilding.GenVars.surfaceCavesBeachAvoidance2, Terraria.Main.tenthAnniversaryWorld, Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.WorldGen.TileRunner(), Terraria.Main.tileSolid, Terraria.WorldGen.TreeTops, Terraria.WorldGen.TryGrowingTreeByType(), Terraria.WorldGen.TuneOceanDepth(), Terraria.WorldBuilding.GenVars.tunnelX, Terraria.WorldBuilding.GenVars.UndergroundDesertLocation, Terraria.Localization.LocalizedText.Value, Terraria.WorldGen.WavyCaverer(), Terraria.WorldGen.WorldGenParam_Evil, Terraria.WorldBuilding.GenVars.worldSurface, Terraria.Main.worldSurface, Terraria.WorldBuilding.GenVars.worldSurfaceHigh, and Terraria.WorldBuilding.GenVars.worldSurfaceLow.
Referenced by Terraria.Main.Initialize().