TModLoader: Terraria.WorldGen.CheckRoom
CheckRoom()
static void Terraria.WorldGen.CheckRoom (int x, int y) inline static
    {
        if (!canSpawn)
        {
            return;
        }
        if (x < 10 || y < 10 || x >= Main.maxTilesX - 10 || y >= lastMaxTilesY - 10)
        {
            roomCheckFailureReason = TownNPCRoomCheckFailureReason.TooCloseToWorldEdge;
            canSpawn = false;
            return;
        }
        for (int i = 0; i < numRoomTiles; i++)
        {
            if (roomX[i] == x && roomY[i] == y)
            {
                return;
            }
        }
        roomX[numRoomTiles] = x;
        roomY[numRoomTiles] = y;
        bool flag = false;
        for (int j = 0; j < roomCeilingsCount; j++)
        {
            if (roomCeilingX[j] == x)
            {
                flag = true;
                if (roomCeilingY[j] > y)
                {
                    roomCeilingY[j] = y;
                }
                break;
            }
        }
        if (!flag)
        {
            roomCeilingX[roomCeilingsCount] = x;
            roomCeilingY[roomCeilingsCount] = y;
            roomCeilingsCount++;
        }
        numRoomTiles++;
        if (numRoomTiles >= maxRoomTiles)
        {
            roomCheckFailureReason = TownNPCRoomCheckFailureReason.RoomIsTooBig;
            canSpawn = false;
            return;
        }
        if (Main.tile[x, y].nactive())
        {
            houseTile[Main.tile[x, y].type] = true;
            if (Main.tileSolid[Main.tile[x, y].type] || (Main.tile[x, y].type == 11 && (Main.tile[x, y].frameX == 0 || Main.tile[x, y].frameX == 54 || Main.tile[x, y].frameX == 72 || Main.tile[x, y].frameX == 126)) || Main.tile[x, y].type == 389 || (Main.tile[x, y].type == 386 && ((Main.tile[x, y].frameX < 36 && Main.tile[x, y].frameY == 18) || (Main.tile[x, y].frameX >= 36 && Main.tile[x, y].frameY == 0))) || (TileLoader.CloseDoorID(Main.tile[x, y]) >= 0 && (Main.tile[x, y].frameX == 0 || Main.tile[x, y].frameX == 54 || Main.tile[x, y].frameX == 72 || Main.tile[x, y].frameX == 126)))
            {
                return;
            }
        }
        if (x < roomX1)
        {
            roomX1 = x;
        }
        if (x > roomX2)
        {
            roomX2 = x;
        }
        if (y < roomY1)
        {
            roomY1 = y;
        }
        if (y > roomY2)
        {
            roomY2 = y;
        }
        if (Main.tile[x, y].type == 630)
        {
            roomHasStinkbug = true;
        }
        if (Main.tile[x, y].type == 631)
        {
            roomHasEchoStinkbug = true;
        }
        bool flag2 = false;
        bool flag3 = false;
        for (int k = -2; k < 3; k++)
        {
            if (Main.wallHouse[Main.tile[x + k, y].wall])
            {
                flag2 = true;
            }
            if (Main.tile[x + k, y].nactive() && (Main.tileSolid[Main.tile[x + k, y].type] || TileID.Sets.HousingWalls[Main.tile[x + k, y].type]))
            {
                flag2 = true;
            }
            if (Main.wallHouse[Main.tile[x, y + k].wall])
            {
                flag3 = true;
            }
            if (Main.tile[x, y + k].nactive() && (Main.tileSolid[Main.tile[x, y + k].type] || TileID.Sets.HousingWalls[Main.tile[x, y + k].type]))
            {
                flag3 = true;
            }
        }
        if (!flag2 || !flag3)
        {
            roomCheckFailureReason = TownNPCRoomCheckFailureReason.HoleInWallIsTooBig;
            canSpawn = false;
            return;
        }
        for (int l = x - 1; l < x + 2; l++)
        {
            for (int m = y - 1; m < y + 2; m++)
            {
                if ((l != x || m != y) && canSpawn)
                {
                    CheckRoom(l, m);
                }
            }
        }
    }
References Terraria.WorldGen.canSpawn, Terraria.WorldGen.CheckRoom(), Terraria.ModLoader.TileLoader.CloseDoorID(), Terraria.WorldGen.houseTile, Terraria.ID.TileID.Sets.HousingWalls, Terraria.WorldGen.lastMaxTilesY, Terraria.WorldGen.maxRoomTiles, Terraria.Main.maxTilesX, Terraria.WorldGen.numRoomTiles, Terraria.WorldGen.roomCeilingsCount, Terraria.WorldGen.roomCeilingX, Terraria.WorldGen.roomCeilingY, Terraria.WorldGen.roomCheckFailureReason, Terraria.WorldGen.roomHasEchoStinkbug, Terraria.WorldGen.roomHasStinkbug, Terraria.WorldGen.roomX, Terraria.WorldGen.roomX1, Terraria.WorldGen.roomX2, Terraria.WorldGen.roomY, Terraria.WorldGen.roomY1, Terraria.WorldGen.roomY2, Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Main.wallHouse.
Referenced by Terraria.WorldGen.CheckRoom(), and Terraria.WorldGen.StartRoomCheck().