TModLoader: Terraria.WorldGen.placeTrap
placeTrap()
static bool Terraria.WorldGen.placeTrap (int x2, int y2, int type = -1) inline static
Definition at line 5666 of file WorldGen.cs.
    {
        int num = y2;
        if (Vector2D.Distance(new Vector2D(x2, y2), GenVars.shimmerPosition) < 100.0)
        {
            return false;
        }
        bool flag = false;
        bool flag2 = false;
        if (noTrapsWorldGen)
        {
            Main.tileSolid[138] = false;
        }
        while (!SolidTile(x2, num))
        {
            num++;
            if (num > Main.maxTilesY - 10)
            {
                return false;
            }
            if (num >= Main.maxTilesY - 300)
            {
                flag2 = true;
            }
        }
        if (noTrapsWorldGen)
        {
            Main.tileSolid[138] = true;
        }
        num--;
        if (!noTrapsWorldGen && IsTileNearby(x2, num, 70, 20))
        {
            return false;
        }
        Tile tile = Main.tile[x2, num];
        if (tile.wall == 87)
        {
            return false;
        }
        tile = Main.tile[x2, num];
        if (tile.liquid > 0)
        {
            tile = Main.tile[x2, num];
            if (tile.lava())
            {
                flag = true;
            }
        }
        if (Main.remixWorld)
        {
            if (type == -1 && genRand.Next(20) == 0)
            {
                type = 2;
            }
            else if (type == -1 && (double)num < Main.rockLayer - 30.0 && genRand.Next(3) != 0)
            {
                type = 3;
            }
            else if (type == -1)
            {
                type = genRand.Next(2);
            }
        }
        else if (type == -1 && genRand.Next(20) == 0)
        {
            type = 2;
        }
        else if (type == -1 && num > GenVars.lavaLine + 30 && genRand.Next(6) != 0)
        {
            type = 3;
        }
        else if (type == -1)
        {
            type = genRand.Next(2);
        }
        if (!InWorld(x2, num, 3))
        {
            return false;
        }
        if (flag && type != 3)
        {
            return false;
        }
        if (flag2 && type != 3)
        {
            return false;
        }
        tile = Main.tile[x2, num];
        if (!tile.nactive())
        {
            tile = Main.tile[x2 - 1, num];
            if (!tile.nactive())
            {
                tile = Main.tile[x2 + 1, num];
                if (!tile.nactive())
                {
                    tile = Main.tile[x2, num - 1];
                    if (!tile.nactive())
                    {
                        tile = Main.tile[x2 - 1, num - 1];
                        if (!tile.nactive())
{
                            tile = Main.tile[x2 + 1, num - 1];
                            if (!tile.nactive())
{
                                tile = Main.tile[x2, num - 2];
                                if (!tile.nactive())
{
                                    tile = Main.tile[x2 - 1, num - 2];
                                    if (!tile.nactive())
{
                                        tile = Main.tile[x2 + 1, num - 2];
                                        if (!tile.nactive())
{
                                            tile = Main.tile[x2, num + 1];
                                            if (tile.type == 48)
{
                                                return false;
                                            }
                                            tile = Main.tile[x2, num + 1];
                                            if (tile.type == 232)
{
                                                return false;
                                            }
                                            if (type == 1)
{
                                                for (int i = x2 - 3; i <= x2 + 3; i++)
{
                                                    for (int j = num - 3; j <= num + 3; j++)
{
                                                        tile = Main.tile[i, j];
                                                        if (tile.type != 147)
{
                                                            tile = Main.tile[i, j];
                                                            if (tile.type != 161)
{
                                                                continue;
                                                            }
                                                        }
                                                        type = 0;
                                                    }
                                                }
                                            }
                                            if (noTrapsWorldGen)
{
                                                Main.tileSolid[138] = false;
                                            }
                                            int num14;
                                            int num15;
                                            int num16;
                                            bool flag5;
                                            bool flag6;
                                            int num19;
                                            int num13;
                                            int num20;
                                            int num21;
                                            switch (type)
{
                                            case 0:
{
                                                num13 = x2;
                                                num14 = num;
                                                num14 -= genRand.Next(3);
                                                while (!SolidTile(num13, num14))
{
                                                    bool[] tileCracked = Main.tileCracked;
                                                    tile = Main.tile[num13, num14];
                                                    if (tileCracked[tile.type])
{
                                                        break;
                                                    }
                                                    num13--;
                                                    if (num13 < 0)
{
                                                        return false;
                                                    }
                                                }
                                                num15 = num13;
                                                num13 = x2;
                                                while (!SolidTile(num13, num14))
{
                                                    bool[] tileCracked2 = Main.tileCracked;
                                                    tile = Main.tile[num13, num14];
                                                    if (tileCracked2[tile.type])
{
                                                        break;
                                                    }
                                                    num13++;
                                                    if (num13 > Main.maxTilesX)
{
                                                        return false;
                                                    }
                                                }
                                                num16 = num13;
                                                int num17 = x2 - num15;
                                                int num18 = num16 - x2;
                                                flag5 = false;
                                                flag6 = false;
                                                if (num17 > 5 && num17 < 50)
{
                                                    flag5 = true;
                                                }
                                                if (num18 > 5 && num18 < 50)
{
                                                    flag6 = true;
                                                }
                                                if (flag5 && !SolidTile(num15, num14 + 1))
{
                                                    flag5 = false;
                                                }
                                                if (flag6 && !SolidTile(num16, num14 + 1))
{
                                                    flag6 = false;
                                                }
                                                if (flag5)
{
                                                    tile = Main.tile[num15, num14];
                                                    if (tile.type != 10)
{
                                                        tile = Main.tile[num15, num14];
                                                        if (tile.type != 48)
{
                                                            tile = Main.tile[num15, num14 + 1];
                                                            if (tile.type != 10)
{
                                                                tile = Main.tile[num15, num14 + 1];
                                                                if (tile.type != 48)
{
                                                                    goto IL_04cc;
                                                                }
                                                            }
                                                        }
                                                    }
                                                    flag5 = false;
                                                }
                                                goto IL_04cc;
                                            }
                                            case 1:
{
                                                if (noTrapsWorldGen)
{
                                                    Main.tileSolid[138] = true;
                                                }
                                                int num22 = x2;
                                                int num23 = num - 8;
                                                num22 += genRand.Next(-1, 2);
                                                if (noTrapsWorldGen)
{
                                                    if (IsTileNearby(num22, num23, 138, 6))
{
                                                        return false;
                                                    }
                                                    if (IsTileNearby(num22, num23, 664, 6))
{
                                                        return false;
                                                    }
                                                }
                                                else
{
                                                    if (IsTileNearby(num22, num23, 138, 10))
{
                                                        return false;
                                                    }
                                                    if (IsTileNearby(num22, num23, 664, 10))
{
                                                        return false;
                                                    }
                                                    if (IsTileNearby(num22, num23, 665, 10))
{
                                                        return false;
                                                    }
                                                }
                                                bool flag3 = true;
                                                while (flag3)
{
                                                    bool flag4 = true;
                                                    int num24 = 0;
                                                    for (int m = num22 - 2; m <= num22 + 3; m++)
{
                                                        for (int n = num23; n <= num23 + 3; n++)
{
                                                            if (!SolidTile(m, n))
{
                                                                flag4 = false;
                                                            }
                                                            tile = Main.tile[m, n];
                                                            if (!tile.active())
{
                                                                continue;
                                                            }
                                                            tile = Main.tile[m, n];
                                                            if (tile.type == 226)
{
                                                                trapDiag[type, 0]++;
                                                                return false;
                                                            }
                                                            tile = Main.tile[m, n];
                                                            if (tile.type != 0)
{
                                                                tile = Main.tile[m, n];
                                                                if (tile.type != 1)
{
                                                                    tile = Main.tile[m, n];
                                                                    if (tile.type != 59)
{
                                                                        continue;
                                                                    }
                                                                }
                                                            }
                                                            num24++;
                                                        }
                                                    }
                                                    num23--;
                                                    if ((double)num23 < Main.worldSurface)
{
                                                        trapDiag[type, 0]++;
                                                        return false;
                                                    }
                                                    if (flag4 && num24 > 2)
{
                                                        flag3 = false;
                                                    }
                                                }
                                                if (num - num23 <= 5 || num - num23 >= 40)
{
                                                    trapDiag[type, 0]++;
                                                    return false;
                                                }
                                                for (int num25 = num22; num25 <= num22 + 1; num25++)
{
                                                    for (int num26 = num23; num26 <= num; num26++)
{
                                                        KillTile(num25, num26);
                                                    }
                                                }
                                                for (int num27 = num22 - 2; num27 <= num22 + 3; num27++)
{
                                                    for (int num28 = num23 - 2; num28 <= num23 + 3; num28++)
{
                                                        if (SolidTile(num27, num28))
{
                                                            tile = Main.tile[num27, num28];
                                                            tile.type = 1;
                                                        }
                                                    }
                                                }
                                                if (IsTileNearby(num22, num23, 21, 4) || IsTileNearby(num22, num23, 467, 4))
{
                                                    trapDiag[type, 0]++;
                                                    return false;
                                                }
                                                PlaceTile(x2, num, 135, mute: true, forced: true, -1, 7);
                                                PlaceTile(num22, num23 + 2, 130, mute: true);
                                                PlaceTile(num22 + 1, num23 + 2, 130, mute: true);
                                                if ((tenthAnniversaryWorldGen || noTrapsWorldGen) && genRand.Next(3) == 0)
{
                                                    PlaceTile(num22 + 1, num23 + 1, 664, mute: true);
                                                }
                                                else
{
                                                    PlaceTile(num22 + 1, num23 + 1, 138, mute: true);
                                                }
                                                num23 += 2;
                                                tile = Main.tile[num22, num23];
                                                tile.wire(wire: true);
                                                tile = Main.tile[num22 + 1, num23];
                                                tile.wire(wire: true);
                                                num23++;
                                                PlaceTile(num22, num23, 130, mute: true);
                                                PlaceTile(num22 + 1, num23, 130, mute: true);
                                                tile = Main.tile[num22, num23];
                                                tile.wire(wire: true);
                                                tile = Main.tile[num22 + 1, num23];
                                                tile.wire(wire: true);
                                                PlaceTile(num22, num23 + 1, 130, mute: true);
                                                PlaceTile(num22 + 1, num23 + 1, 130, mute: true);
                                                tile = Main.tile[num22, num23 + 1];
                                                tile.wire(wire: true);
                                                tile = Main.tile[num22 + 1, num23 + 1];
                                                tile.wire(wire: true);
                                                int num2 = x2;
                                                int num3 = num;
                                                while (num2 != num22 || num3 != num23)
{
                                                    tile = Main.tile[num2, num3];
                                                    tile.wire(wire: true);
                                                    if (num2 > num22)
{
                                                        num2--;
                                                    }
                                                    if (num2 < num22)
{
                                                        num2++;
                                                    }
                                                    tile = Main.tile[num2, num3];
                                                    tile.wire(wire: true);
                                                    if (num3 > num23)
{
                                                        num3--;
                                                    }
                                                    if (num3 < num23)
{
                                                        num3++;
                                                    }
                                                    tile = Main.tile[num2, num3];
                                                    tile.wire(wire: true);
                                                }
                                                trapDiag[type, 1]++;
                                                return true;
                                            }
                                            case 2:
{
                                                int num4 = genRand.Next(4, 7);
                                                int num5 = x2;
                                                num5 += genRand.Next(-1, 2);
                                                int num6 = num;
                                                for (int num7 = 0; num7 < num4; num7++)
{
                                                    num6++;
                                                    if (!SolidTile(num5, num6))
{
                                                        trapDiag[type, 0]++;
                                                        return false;
                                                    }
                                                }
                                                for (int num8 = num5 - 2; num8 <= num5 + 2; num8++)
{
                                                    for (int num9 = num6 - 2; num9 <= num6 + 2; num9++)
{
                                                        if (!SolidTile(num8, num9))
{
                                                            return false;
                                                        }
                                                    }
                                                }
                                                KillTile(num5, num6);
                                                tile = Main.tile[num5, num6];
                                                tile.active(active: true);
                                                tile = Main.tile[num5, num6];
                                                tile.type = 141;
                                                tile = Main.tile[num5, num6];
                                                tile.frameX = 0;
                                                tile = Main.tile[num5, num6];
                                                tile.frameY = (short)(18 * genRand.Next(2));
                                                PlaceTile(x2, num, 135, mute: true, forced: true, -1, genRand.Next(2, 4));
                                                int num10 = x2;
                                                int num11 = num;
                                                while (num10 != num5 || num11 != num6)
{
                                                    tile = Main.tile[num10, num11];
                                                    tile.wire(wire: true);
                                                    if (num10 > num5)
{
                                                        num10--;
                                                    }
                                                    if (num10 < num5)
{
                                                        num10++;
                                                    }
                                                    tile = Main.tile[num10, num11];
                                                    tile.wire(wire: true);
                                                    if (num11 > num6)
{
                                                        num11--;
                                                    }
                                                    if (num11 < num6)
{
                                                        num11++;
                                                    }
                                                    tile = Main.tile[num10, num11];
                                                    tile.wire(wire: true);
                                                }
                                                trapDiag[type, 1]++;
                                                break;
                                            }
                                            case 3:
{
                                                    tile = Main.tile[x2 + 1, num];
                                                    if (tile.active())
{
                                                        return false;
                                                    }
                                                    tile = Main.tile[x2, num];
                                                    if (tile.liquid > 0)
{
                                                        tile = Main.tile[x2, num];
                                                        if (!tile.lava())
{
                                                            return false;
                                                        }
                                                    }
                                                    if (noTrapsWorldGen && (tenthAnniversaryWorldGen || notTheBees))
{
                                                        if (genRand.Next(3) != 0)
{
                                                            return false;
                                                        }
                                                        if (IsTileNearby(x2, num, 443, 30))
{
                                                            return false;
                                                        }
                                                    }
                                                    for (int k = x2; k <= x2 + 1; k++)
{
                                                        int j2 = num + 1;
                                                        if (!SolidTile(k, j2))
{
                                                            return false;
                                                        }
                                                    }
                                                    int num12 = genRand.Next(2);
                                                    for (int l = 0; l < 2; l++)
{
                                                        tile = Main.tile[x2 + l, num];
                                                        tile.active(active: true);
                                                        tile = Main.tile[x2 + l, num];
                                                        tile.type = 443;
                                                        tile = Main.tile[x2 + l, num];
                                                        tile.frameX = (short)(18 * l + 36 * num12);
                                                        tile = Main.tile[x2 + l, num];
                                                        tile.frameY = 0;
                                                    }
                                                    return true;
                                                }
                                                IL_04cc:
                                                if (flag6)
{
                                                    tile = Main.tile[num16, num14];
                                                    if (tile.type != 10)
{
                                                        tile = Main.tile[num16, num14];
                                                        if (tile.type != 48)
{
                                                            tile = Main.tile[num16, num14 + 1];
                                                            if (tile.type != 10)
{
                                                                tile = Main.tile[num16, num14 + 1];
                                                                if (tile.type != 48)
{
                                                                    goto IL_0543;
                                                                }
                                                            }
                                                        }
                                                    }
                                                    flag6 = false;
                                                }
                                                goto IL_0543;
                                                IL_0543:
                                                num19 = 0;
                                                if (flag5 && flag6)
{
                                                    num19 = 1;
                                                    num13 = num15;
                                                    if (genRand.Next(2) == 0)
{
                                                        num13 = num16;
                                                        num19 = -1;
                                                    }
                                                }
                                                else if (flag6)
{
                                                    num13 = num16;
                                                    num19 = -1;
                                                }
                                                else
{
                                                    if (!flag5)
{
                                                        trapDiag[type, 0]++;
                                                        return false;
                                                    }
                                                    num13 = num15;
                                                    num19 = 1;
                                                }
                                                tile = Main.tile[num13, num14];
                                                if (tile.type == 190)
{
                                                    trapDiag[type, 0]++;
                                                    return false;
                                                }
                                                tile = Main.tile[x2, num];
                                                if (tile.wall > 0)
{
                                                    PlaceTile(x2, num, 135, mute: true, forced: true, -1, 2);
                                                }
                                                else
{
                                                    PlaceTile(x2, num, 135, mute: true, forced: true, -1, genRand.Next(2, 4));
                                                }
                                                KillTile(num13, num14);
                                                PlaceTile(num13, num14, 137, mute: true, forced: true);
                                                if (num19 == 1)
{
                                                    tile = Main.tile[num13, num14];
                                                    tile.frameX += 18;
                                                }
                                                num20 = x2;
                                                num21 = num;
                                                while (num20 != num13 || num21 != num14)
{
                                                    tile = Main.tile[num20, num21];
                                                    tile.wire(wire: true);
                                                    if (num20 > num13)
{
                                                        num20--;
                                                    }
                                                    if (num20 < num13)
{
                                                        num20++;
                                                    }
                                                    tile = Main.tile[num20, num21];
                                                    tile.wire(wire: true);
                                                    if (num21 > num14)
{
                                                        num21--;
                                                    }
                                                    if (num21 < num14)
{
                                                        num21++;
                                                    }
                                                    tile = Main.tile[num20, num21];
                                                    tile.wire(wire: true);
                                                }
                                                trapDiag[type, 1]++;
                                                return true;
                                            }
                                            if (noTrapsWorldGen)
{
                                                Main.tileSolid[138] = true;
                                            }
                                            return false;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        return false;
    }
References Terraria.Tile.active(), Terraria.WorldGen.genRand, Terraria.WorldGen.InWorld(), Terraria.WorldGen.IsTileNearby(), Terraria.WorldGen.KillTile(), Terraria.Tile.lava(), Terraria.WorldBuilding.GenVars.lavaLine, Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.WorldGen.noTrapsWorldGen, Terraria.WorldGen.notTheBees, Terraria.WorldGen.PlaceTile(), Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.WorldBuilding.GenVars.shimmerPosition, Terraria.Enums.SolidTile, Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.Main.tileCracked, Terraria.Main.tileSolid, Terraria.WorldGen.trapDiag, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wire(), and Terraria.Main.worldSurface.