TModLoader: Terraria.WorldGen.Check2x1
Check2x1()
static void Terraria.WorldGen.Check2x1 (int i, int y, ushort type) inline static
    {
        if (destroyObject)
        {
            return;
        }
        int num = i;
        bool flag = true;
        Tile tile4;
        if (Main.tile[num, y] == null)
        {
            tile4 = (Main.tile[num, y] = default(Tile));
        }
        tile4 = Main.tile[num, y];
        int num2 = tile4.frameX / 18;
        int num3 = num2 >> 1;
        tile4 = Main.tile[num, y];
        int num4 = tile4.frameY / 18;
        num2 %= 2;
        num -= num2;
        if (Main.tile[num, y] == null)
        {
            tile4 = (Main.tile[num, y] = default(Tile));
        }
        if (Main.tile[num + 1, y] == null)
        {
            tile4 = (Main.tile[num + 1, y] = default(Tile));
        }
        if (Main.tile[num, y + 1] == null)
        {
            tile4 = (Main.tile[num, y + 1] = default(Tile));
        }
        if (Main.tile[num + 1, y + 1] == null)
        {
            tile4 = (Main.tile[num + 1, y + 1] = default(Tile));
        }
        tile4 = Main.tile[num + 1, y];
        short frameX2 = tile4.frameX;
        tile4 = Main.tile[num, y];
        if (frameX2 == tile4.frameX + 18)
        {
            tile4 = Main.tile[num, y];
            if (tile4.type == type)
            {
                tile4 = Main.tile[num + 1, y];
                if (tile4.type == type)
                {
                    flag = false;
                }
            }
        }
        if (type == 29 || type == 103 || type == 462)
        {
            tile4 = Main.tile[num, y + 1];
            if (tile4.active())
            {
                bool[] tileTable = Main.tileTable;
                tile4 = Main.tile[num, y + 1];
                if (tileTable[tile4.type])
                {
                    tile4 = Main.tile[num, y + 1];
                    if (!tile4.halfBrick())
                    {
                        tile4 = Main.tile[num, y + 1];
                        if (!tile4.topSlope())
{
                            goto IL_021a;
                        }
                    }
                }
            }
            flag = true;
            goto IL_021a;
        }
        if (!SolidTileAllowBottomSlope(num, y + 1))
        {
            flag = true;
        }
        if (!SolidTileAllowBottomSlope(num + 1, y + 1))
        {
            flag = true;
        }
        goto IL_02ad;
        IL_021a:
        tile4 = Main.tile[num + 1, y + 1];
        if (tile4.active())
        {
            bool[] tileTable2 = Main.tileTable;
            tile4 = Main.tile[num + 1, y + 1];
            if (tileTable2[tile4.type])
            {
                tile4 = Main.tile[num + 1, y + 1];
                if (!tile4.halfBrick())
                {
                    tile4 = Main.tile[num + 1, y + 1];
                    if (!tile4.topSlope())
                    {
                        goto IL_02ad;
                    }
                }
            }
        }
        flag = true;
        goto IL_02ad;
        IL_02ad:
        if (type == 185)
        {
            tile4 = Main.tile[num, y];
            if (tile4.frameX >= 1368)
            {
                tile4 = Main.tile[num, y];
                if (tile4.frameX <= 1458)
                {
                    tile4 = Main.tile[num, y + 1];
                    if (tile4.type != 2)
                    {
                        tile4 = Main.tile[num + 1, y + 1];
                        if (tile4.type != 2)
{
                            tile4 = Main.tile[num, y + 1];
                            if (tile4.type != 477)
{
                                tile4 = Main.tile[num + 1, y + 1];
                                if (tile4.type != 477)
{
                                    tile4 = Main.tile[num, y + 1];
                                    if (tile4.type != 492)
{
                                        tile4 = Main.tile[num + 1, y + 1];
                                        if (tile4.type != 492)
{
                                            tile4 = Main.tile[num, y];
                                            tile4.frameX -= 1368;
                                            tile4 = Main.tile[num + 1, y];
                                            tile4.frameX -= 1368;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            Tile tile = Main.tile[num, y];
            int num5 = tile.frameX / 36;
            num5 += (tile.frameY / 18 - 1) * 52;
            for (int j = num; j < num + 2; j++)
            {
                Tile tile2 = Main.tile[j, y + 1];
                if (tile2 == null || !tile2.active() || tile2.type < 0)
                {
                    continue;
                }
                ushort type2 = tile2.type;
                switch (num5)
                {
                case 25:
                case 26:
                case 27:
                case 28:
                case 29:
                case 30:
                    if (!TileID.Sets.Snow[type2] && !TileID.Sets.Conversion.Ice[type2] && type2 != 162 && type2 != 224)
                    {
                        flag = true;
                    }
                    break;
                case 41:
                case 42:
                case 43:
                case 44:
                case 45:
                case 46:
                case 62:
                case 63:
                case 64:
                    if (!TileID.Sets.Conversion.Sand[type2] && !TileID.Sets.Conversion.HardenedSand[type2] && !TileID.Sets.Conversion.Sandstone[type2])
                    {
                        flag = true;
                    }
                    break;
                }
            }
        }
        if (!flag)
        {
            return;
        }
        tile4 = Main.tile[num, y];
        int frameX = tile4.frameX;
        tile4 = Main.tile[num, y];
        if (!tile4.active())
        {
            tile4 = Main.tile[num + 1, y];
            frameX = tile4.frameX;
        }
        destroyObject = true;
        bool drop = TileLoader.Drop(i, y, type);
        tile4 = Main.tile[num, y];
        if (tile4.type == type)
        {
            KillTile(num, y);
        }
        tile4 = Main.tile[num + 1, y];
        if (tile4.type == type)
        {
            KillTile(num + 1, y);
        }
        using (new Item.DisableNewItemMethod(!drop))
        {
            if (type == 16)
            {
                if (num3 == 1)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 716);
                }
                else
                {
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 35);
                }
            }
            if (type == 18)
            {
                int type3 = 36;
                if (num3 >= 1 && num3 <= 3)
                {
                    type3 = 634 + num3;
                }
                else if (num3 >= 4 && num3 <= 8)
                {
                    type3 = 807 + num3;
                }
                else
                {
                    switch (num3)
                    {
                    case 9:
                        type3 = 916;
                        break;
                    case 10:
                        type3 = 1145;
                        break;
                    case 11:
                        type3 = 1398;
                        break;
                    case 12:
                        type3 = 1401;
                        break;
                    case 13:
                        type3 = 1404;
                        break;
                    case 14:
                        type3 = 1461;
                        break;
                    case 15:
                        type3 = 1511;
                        break;
                    case 16:
                        type3 = 1795;
                        break;
                    case 17:
                        type3 = 1817;
                        break;
                    case 18:
                        type3 = 2229;
                        break;
                    case 19:
                        type3 = 2251;
                        break;
                    case 20:
                        type3 = 2252;
                        break;
                    case 21:
                        type3 = 2253;
                        break;
                    case 22:
                        type3 = 2534;
                        break;
                    case 23:
                        type3 = 673;
                        break;
                    case 24:
                        type3 = 2631;
                        break;
                    case 25:
                        type3 = 2632;
                        break;
                    case 26:
                        type3 = 2633;
                        break;
                    case 27:
                        type3 = 2826;
                        break;
                    case 28:
                        type3 = 3156;
                        break;
                    case 29:
                        type3 = 3158;
                        break;
                    case 30:
                        type3 = 3157;
                        break;
                    case 31:
                        type3 = 3909;
                        break;
                    case 32:
                        type3 = 3910;
                        break;
                    case 33:
                        type3 = 3949;
                        break;
                    case 34:
                        type3 = 3975;
                        break;
                    case 35:
                        type3 = 4163;
                        break;
                    case 36:
                        type3 = 4184;
                        break;
                    case 37:
                        type3 = 4205;
                        break;
                    case 38:
                        type3 = 4226;
                        break;
                    case 39:
                        type3 = 4315;
                        break;
                    case 40:
                        type3 = 4584;
                        break;
                    case 41:
                        type3 = 5166;
                        break;
                    case 42:
                        type3 = 5187;
                        break;
                    case 43:
                        type3 = 5208;
                        break;
                    }
                }
                Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, type3);
            }
            if (type == 185)
            {
                if (frameX >= 576 && frameX <= 610)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 71, genRand.Next(10, 100));
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 71, genRand.Next(20, 100));
                    if (genRand.Next(3) != 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 71, genRand.Next(10, 100));
                    }
                    if (genRand.Next(3) != 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 71, genRand.Next(20, 100));
                    }
                    if (genRand.Next(2) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 71, genRand.Next(10, 100));
                    }
                    if (genRand.Next(2) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 71, genRand.Next(20, 100));
                    }
                    if (genRand.Next(3) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 71, genRand.Next(10, 100));
                    }
                    if (genRand.Next(3) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 71, genRand.Next(20, 100));
                    }
                    if (genRand.Next(4) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 71, genRand.Next(10, 100));
                    }
                    if (genRand.Next(4) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 71, genRand.Next(20, 100));
                    }
                    if (genRand.Next(5) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 71, genRand.Next(10, 100));
                    }
                    if (genRand.Next(5) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 71, genRand.Next(20, 100));
                    }
                }
                if (frameX >= 612 && frameX <= 646)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 72, genRand.Next(10, 100));
                    if (genRand.Next(2) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 72, genRand.Next(20, 100));
                    }
                    if (genRand.Next(3) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 72, genRand.Next(30, 100));
                    }
                }
                if (frameX >= 648 && frameX <= 682)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 73, genRand.Next(1, 6));
                    if (genRand.Next(2) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 73, genRand.Next(2, 6));
                    }
                    if (genRand.Next(3) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 73, genRand.Next(3, 6));
                    }
                }
                if (frameX >= 684 && frameX <= 718)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 181, genRand.Next(1, 4));
                }
                if (frameX >= 720 && frameX <= 754)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 180, genRand.Next(1, 4));
                }
                if (frameX >= 756 && frameX <= 790)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 177, genRand.Next(1, 4));
                }
                if (frameX >= 792 && frameX <= 826)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 179, genRand.Next(1, 4));
                }
                if (frameX >= 828 && frameX <= 862)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 178, genRand.Next(1, 4));
                }
                if (frameX >= 864 && frameX <= 898)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 182, genRand.Next(1, 4));
                }
            }
            if (type == 462)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 3795);
            }
            if (type == 29)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 87);
                SoundEngine.PlaySound(13, i * 16, y * 16);
            }
            switch (type)
            {
            case 103:
            {
                int type4 = 356;
                if (num3 == 1)
                {
                    type4 = 2235;
                }
                if (num3 == 2)
                {
                    type4 = 2242;
                }
                if (num3 == 3)
                {
                    type4 = 2243;
                }
                Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, type4);
                SoundEngine.PlaySound(13, i * 16, y * 16);
                break;
            }
            case 134:
                if (num3 == 1)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 1220);
                }
                else
                {
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, 525);
                }
                break;
            case 649:
            {
                num3 += num4 * 53;
                int num6 = 0;
                if (num3 < 6)
                {
                    num6 = 3;
                }
                else if (num3 < 16)
                {
                    num6 = 154;
                }
                else if (num3 < 17)
                {
                    num6 = 71;
                }
                else if (num3 < 18)
                {
                    num6 = 72;
                }
                else if (num3 < 19)
                {
                    num6 = 73;
                }
                else if (num3 < 20)
                {
                    num6 = 181;
                }
                else if (num3 < 21)
                {
                    num6 = 180;
                }
                else if (num3 < 22)
                {
                    num6 = 177;
                }
                else if (num3 < 23)
                {
                    num6 = 179;
                }
                else if (num3 < 24)
                {
                    num6 = 178;
                }
                else if (num3 < 25)
                {
                    num6 = 182;
                }
                else if (num3 < 31)
                {
                    num6 = 593;
                }
                else if (num3 < 34)
                {
                    num6 = 9;
                }
                else if (num3 < 38)
                {
                    num6 = 150;
                }
                else if (num3 < 41)
                {
                    num6 = 3;
                }
                else if (num3 < 47)
                {
                    num6 = 3271;
                }
                else if (num3 < 53)
                {
                    num6 = 3086;
                }
                else if (num3 < 59)
                {
                    num6 = 3081;
                }
                else if (num3 < 62)
                {
                    num6 = 62;
                }
                else if (num3 < 65)
                {
                    num6 = 169;
                }
                if (num6 != 0)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(num, y), num * 16, y * 16, 32, 32, num6);
                }
                break;
            }
            }
            destroyObject = false;
            SquareTileFrame(num, y);
            SquareTileFrame(num + 1, y);
        }
    }
References Terraria.ModLoader.TileLoader.Drop(), Terraria.ID.TileID.Sets.Conversion.HardenedSand, Terraria.ID.TileID.Sets.Conversion.Ice, Terraria.Item.NewItem(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.ID.TileID.Sets.Conversion.Sandstone, Terraria.ID.TileID.Sets.Snow, Terraria.Main.tile, and Terraria.Main.tileTable.