TModLoader: Terraria.WorldGen.SlopeTile
SlopeTile()
static bool Terraria.WorldGen.SlopeTile (int i, int j, int slope = 0, bool noEffects = false) inline static
    {
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        if (!CanPoundTile(i, j))
        {
            return false;
        }
        Main.tile[i, j].halfBrick(halfBrick: false);
        Main.tile[i, j].slope((byte)slope);
        if (!gen)
        {
            if (!noEffects)
            {
                KillTile(i, j, fail: true, effectOnly: true);
            }
            SoundEngine.PlaySound(0, i * 16, j * 16);
            SquareTileFrame(i, j);
            if (Main.tile[i, j].slope() == 0)
            {
                Rectangle rectangle = default(Rectangle);
                ((Rectangle)(ref rectangle))._002Ector(i * 16, j * 16, 16, 16);
                for (int k = 0; k < 255; k++)
                {
                    if (Main.player[k].active && !Main.player[k].dead && ((Rectangle)(ref rectangle)).Intersects(new Rectangle((int)Main.player[k].position.X, (int)Main.player[k].position.Y, Main.player[k].width, Main.player[k].height)))
                    {
                        Main.player[k].gfxOffY += Main.player[k].position.Y + (float)Main.player[k].height - (float)rectangle.Y;
                        Main.player[k].position.Y = rectangle.Y - Main.player[k].height;
                    }
                }
            }
        }
        return true;
    }
References Terraria.Entity.active, Terraria.Player.dead, Terraria.Player.gfxOffY, Terraria.Entity.height, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.tile, and Terraria.Entity.width.
Referenced by Terraria.Projectile.AI_010(), Terraria.WorldBuilding.Actions.SetSlope.Apply(), Terraria.MessageBuffer.GetData(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.Projectile.Kill(), Terraria.TileObject.Place(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform(), Terraria.Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids(), and Terraria.DelegateMethods.SpreadDirt().