TModLoader: Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single
ReplaceTile_DoActualReplacement_Single()
static void Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single (ushort targetType, int targetStyle, int topLeftX, int topLeftY, Tile t) inline static private
    {
        ReplaceTile_EliminateNaturalExtras(topLeftX, topLeftY);
        int type = t.type;
        t.type = targetType;
        if (TileID.Sets.Platforms[t.type])
        {
            t.frameY = (short)(targetStyle * 18);
        }
        if (TileID.Sets.Torch[t.type])
        {
            t.frameY = (short)(targetStyle * 22);
        }
        t.ClearBlockPaintAndCoating();
        bool flag = !CanPoundTile(topLeftX, topLeftY);
        if (TileID.Sets.Platforms[type] && TileID.Sets.Platforms[t.type])
        {
            flag = false;
        }
        if (flag)
        {
            t.slope(0);
            t.halfBrick(halfBrick: false);
        }
        if (Main.tenthAnniversaryWorld && !Main.remixWorld && (targetType == 53 || targetType == 396 || targetType == 397))
        {
            t.color(7);
        }
        TileFrame(topLeftX, topLeftY);
        SquareTileFrame(topLeftX, topLeftY);
    }
References Terraria.Tile.ClearBlockPaintAndCoating(), Terraria.Tile.color(), Terraria.Tile.halfBrick(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.remixWorld, Terraria.Tile.slope(), Terraria.Main.tenthAnniversaryWorld, Terraria.ID.TileID.Sets.Torch, and Terraria.Tile.type.