TModLoader: Terraria.WorldGen.Check2xX
Check2xX()
static void Terraria.WorldGen.Check2xX (int i, int j, ushort type) inline static
    {
        if (destroyObject)
        {
            return;
        }
        int num = i;
        int num8;
        for (num8 = Main.tile[i, j].frameX; num8 >= 36; num8 -= 36)
        {
        }
        if (num8 == 18)
        {
            num--;
        }
        if (Main.tile[num, j] == null)
        {
            Main.tile[num, j] = default(Tile);
        }
        int num9 = Main.tile[num, j].frameY / 18;
        int num10 = 3;
        if (type == 104)
        {
            num10 = 5;
        }
        if (type == 207)
        {
            num10 = 4;
        }
        int num11 = 0;
        while (num9 >= num10)
        {
            num9 -= num10;
            num11 += num10 * 18;
        }
        int num12 = j - num9;
        if (type == 410 && num11 != 0)
        {
            num11 += 2;
        }
        if (Main.tile[num, num12] == null)
        {
            Main.tile[num, num12] = default(Tile);
        }
        int frameX = Main.tile[num, j].frameX;
        int frameY = Main.tile[num, j].frameY;
        bool flag = false;
        for (int k = 0; k < num10; k++)
        {
            if (Main.tile[num, num12 + k] == null)
            {
                Main.tile[num, num12 + k] = default(Tile);
            }
            if (!Main.tile[num, num12 + k].active())
            {
                flag = true;
            }
            else if (Main.tile[num, num12 + k].type != type)
            {
                flag = true;
            }
            else if (Main.tile[num, num12 + k].frameY != k * 18 + num11)
            {
                flag = true;
            }
            else if (Main.tile[num, num12 + k].frameX != frameX)
            {
                flag = true;
            }
            if (Main.tile[num + 1, num12 + k] == null)
            {
                Main.tile[num + 1, num12 + k] = default(Tile);
            }
            if (!Main.tile[num + 1, num12 + k].active())
            {
                flag = true;
            }
            else if (Main.tile[num + 1, num12 + k].type != type)
            {
                flag = true;
            }
            else if (Main.tile[num + 1, num12 + k].frameY != k * 18 + num11)
            {
                flag = true;
            }
            else if (Main.tile[num + 1, num12 + k].frameX != frameX + 18)
            {
                flag = true;
            }
        }
        if (type == 465 || type == 531 || type == 591 || type == 592)
        {
            bool flag2 = false;
            for (int l = 0; l < 2; l++)
            {
                bool flag3 = false;
                Tile tileSafely = Framing.GetTileSafely(num + l, num12 - 1);
                if (type != 531 && tileSafely.type == 380)
                {
                    flag3 = true;
                }
                else if (type != 531 && TileID.Sets.Platforms[tileSafely.type])
                {
                    if (l == 0)
                    {
                        flag2 = IsBelowANonHammeredPlatform(num + l, num12);
                        flag3 = true;
                    }
                    else if (flag2 == IsBelowANonHammeredPlatform(num + l, num12))
                    {
                        flag3 = true;
                    }
                }
                else
                {
                    flag3 = SolidTileAllowTopSlope(num + l, num12 - 1);
                }
                if (!flag3)
                {
                    flag = true;
                    break;
                }
            }
        }
        else
        {
            if (!SolidTileAllowBottomSlope(num, num12 + num10))
            {
                flag = true;
            }
            if (!SolidTileAllowBottomSlope(num + 1, num12 + num10))
            {
                flag = true;
            }
        }
        if (!flag)
        {
            return;
        }
        destroyObject = true;
        bool drop = TileLoader.Drop(i, j, type);
        for (int m = 0; m < num10; m++)
        {
            if (Main.tile[num, num12 + m].type == type)
            {
                KillTile(num, num12 + m);
            }
            if (Main.tile[num + 1, num12 + m].type == type)
            {
                KillTile(num + 1, num12 + m);
            }
        }
        using (new Item.DisableNewItemMethod(!drop))
        {
            if (type == 104)
            {
                int num13 = frameX / 36;
                int num14 = 0;
                if (num13 >= 1 && num13 <= 5)
                {
                    num14 = 2237 + num13 - 1;
                }
                else
                {
                    switch (num13)
                    {
                    case 6:
                        num14 = 2560;
                        break;
                    case 7:
                        num14 = 2575;
                        break;
                    case 8:
                    case 9:
                    case 10:
                    case 11:
                    case 12:
                    case 13:
                    case 14:
                    case 15:
                    case 16:
                    case 17:
                    case 18:
                    case 19:
                    case 20:
                    case 21:
                    case 22:
                    case 23:
                        num14 = 2591 + num13 - 8;
                        break;
                    case 24:
                        num14 = 2809;
                        break;
                    case 25:
                        num14 = 3126;
                        break;
                    case 26:
                        num14 = 3128;
                        break;
                    case 27:
                        num14 = 3127;
                        break;
                    case 28:
                        num14 = 3898;
                        break;
                    case 29:
                        num14 = 3899;
                        break;
                    case 30:
                        num14 = 3900;
                        break;
                    case 31:
                        num14 = 3901;
                        break;
                    case 32:
                        num14 = 3902;
                        break;
                    case 33:
                        num14 = 3940;
                        break;
                    case 34:
                        num14 = 3966;
                        break;
                    case 35:
                        num14 = 4154;
                        break;
                    case 36:
                        num14 = 4175;
                        break;
                    case 37:
                        num14 = 4196;
                        break;
                    case 38:
                        num14 = 4217;
                        break;
                    case 39:
                        num14 = 4306;
                        break;
                    case 40:
                        num14 = 4575;
                        break;
                    case 41:
                        num14 = 5157;
                        break;
                    case 42:
                        num14 = 5178;
                        break;
                    case 43:
                        num14 = 5199;
                        break;
                    default:
                        num14 = 359;
                        break;
                    }
                }
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, num14);
            }
            if (type == 105)
            {
                int num15 = frameX / 36;
                int num2 = frameY / 54;
                num2 %= 3;
                num15 += num2 * 55;
                switch (num15)
                {
                case 0:
                    num15 = 360;
                    break;
                case 1:
                    num15 = 52;
                    break;
                case 43:
                    num15 = 1152;
                    break;
                case 44:
                    num15 = 1153;
                    break;
                case 45:
                    num15 = 1154;
                    break;
                case 46:
                    num15 = 1408;
                    break;
                case 47:
                    num15 = 1409;
                    break;
                case 48:
                    num15 = 1410;
                    break;
                case 49:
                    num15 = 1462;
                    break;
                case 50:
                    num15 = 2672;
                    break;
                case 51:
                case 52:
                case 53:
                case 54:
                case 55:
                case 56:
                case 57:
                case 58:
                case 59:
                case 60:
                case 61:
                case 62:
                    num15 = 3651 + num15 - 51;
                    break;
                case 63:
                case 64:
                case 65:
                case 66:
                case 67:
                case 68:
                case 69:
                case 70:
                case 71:
                case 72:
                case 73:
                case 74:
                case 75:
                    num15 = 3708 + num15 - 63;
                    break;
                default:
                    num15 = num15 switch
                    {
                        76 => 4397,
                        77 => 4360,
                        78 => 4342,
                        79 => 4466,
                        80 => 5317,
                        81 => 5318,
                        82 => 5319,
                        _ => 438 + num15 - 2,
                    };
                    break;
                }
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, num15);
            }
            if (type == 356)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 3064);
            }
            if (type == 663)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 5381);
            }
            if (type == 456)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 3748);
            }
            if (type == 337)
            {
                int num3 = frameX / 36;
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 2702 + num3);
            }
            if (type == 207)
            {
                int num4 = frameX / 36;
                switch (num4)
                {
                case 0:
                    num4 = 909;
                    break;
                case 1:
                    num4 = 910;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                    num4 = 938 + num4;
                    break;
                case 8:
                    num4 = 4922;
                    break;
                case 9:
                    num4 = 4417;
                    break;
                }
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, num4);
            }
            if (type == 410)
            {
                int num5 = frameX / 36;
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, num5 + 3536);
            }
            if (type == 480)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 4054);
            }
            if (type == 509)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 4318);
            }
            if (type == 657)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 5345);
            }
            if (type == 658)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 5347);
            }
            if (type == 489)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 4074);
            }
            if (type == 320)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 2496);
            }
            if (type == 349)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 470);
            }
            if (type == 506)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 4276);
            }
            if (type == 545)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 4420);
            }
            if (type == 465)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 3815);
            }
            if (type == 531)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 4355);
            }
            if (type == 378)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 48, 3202);
                TETrainingDummy.Kill(num, num12);
            }
            if (type == 560)
            {
                int num6 = frameX / 36;
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, num6 + 4599);
            }
            if (type == 591)
            {
                int num7 = frameX / 36;
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, num7 + 4858);
            }
            if (type == 592)
            {
                Item.NewItem(GetItemSource_FromTileBreak(num, j), num * 16, j * 16, 32, 32, 4867);
            }
            destroyObject = false;
        }
    }
References Terraria.ModLoader.TileLoader.Drop(), Terraria.Framing.GetTileSafely(), Terraria.GameContent.Tile_Entities.TETrainingDummy.Kill(), Terraria.Item.NewItem(), Terraria.ID.TileID.Sets.Platforms, and Terraria.Main.tile.