TModLoader: Terraria.WorldGen.UnspawnTravelNPC
UnspawnTravelNPC()
static void Terraria.WorldGen.UnspawnTravelNPC () inline static
Definition at line 1990 of file WorldGen.cs.
    {
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b4: Unknown result type (might be due to invalid IL or missing references)
        int num = -1;
        for (int i = 0; i < 200; i++)
        {
            if (Main.npc[i].active && Main.npc[i].type == 368)
            {
                num = i;
                break;
            }
        }
        if (num < 0)
        {
            return;
        }
        int num2 = (int)(Main.npc[num].Center.X / 16f);
        int num3 = (int)(Main.npc[num].Center.Y / 16f);
        bool flag = true;
        Rectangle value = default(Rectangle);
        ((Rectangle)(ref value))._002Ector(num2 * 16 + 8 - NPC.sWidth / 2 - NPC.safeRangeX, num3 * 16 + 8 - NPC.sHeight / 2 - NPC.safeRangeY, NPC.sWidth + NPC.safeRangeX * 2, NPC.sHeight + NPC.safeRangeY * 2);
        for (int j = 0; j < 255; j++)
        {
            if (Main.player[j].active)
            {
                Rectangle val = new Rectangle((int)Main.player[j].position.X, (int)Main.player[j].position.Y, Main.player[j].width, Main.player[j].height);
                if (((Rectangle)(ref val)).Intersects(value))
                {
                    flag = false;
                    break;
                }
            }
        }
        if (flag)
        {
            string fullName = Main.npc[num].FullName;
            if (Main.netMode == 0)
            {
                Main.NewText(Lang.misc[35].Format(fullName), 50, 125);
            }
            else if (Main.netMode == 2)
            {
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[35].Key, Main.npc[num].GetFullNetName()), new Color(50, 125, 255));
            }
            Main.npc[num].active = false;
            Main.npc[num].netSkip = -1;
            Main.npc[num].life = 0;
            NetMessage.SendData(23, -1, -1, null, num);
        }
    }
References Terraria.Entity.active, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Entity.Center, Terraria.Localization.LocalizedText.Format(), Terraria.Localization.NetworkText.FromKey(), Terraria.NPC.FullName, Terraria.NPC.GetFullNetName(), Terraria.Entity.height, Terraria.Localization.LocalizedText.Key, Terraria.NPC.life, Terraria.Lang.misc, Terraria.Main.netMode, Terraria.NPC.netSkip, Terraria.Main.NewText(), Terraria.Main.npc, Terraria.Main.player, Terraria.Entity.position, Terraria.NPC.safeRangeX, Terraria.NPC.safeRangeY, Terraria.NetMessage.SendData(), Terraria.NPC.sHeight, Terraria.NPC.sWidth, Terraria.NPC.type, and Terraria.Entity.width.
Referenced by Terraria.Main.UpdateTime().