TModLoader: Terraria.WorldGen.serverLoadWorldCallBack
serverLoadWorldCallBack()
static void Terraria.WorldGen.serverLoadWorldCallBack () inline static
Definition at line 3701 of file WorldGen.cs.
    {
        Logging.Terraria.InfoFormat("Loading World: {0}, IsCloud={1}, Width: {2}, Height: {3}, Evil: {4}, GameMode: {5}", new object[6]
        {
            Main.ActiveWorldFileData.Name,
            Main.ActiveWorldFileData.IsCloudSave,
            Main.ActiveWorldFileData.WorldSizeX,
            Main.ActiveWorldFileData.WorldSizeY,
            Main.ActiveWorldFileData.HasCrimson.ToInt(),
            Main.ActiveWorldFileData.GameMode
        });
        Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
        WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
        if (loadFailed || !loadSuccess)
        {
            WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
            if (loadFailed || !loadSuccess)
            {
                bool isCloudSave = Main.ActiveWorldFileData.IsCloudSave;
                if (FileUtilities.Exists(Main.worldPathName + ".bak", isCloudSave))
                {
                    worldBackup = true;
                }
                else
                {
                    worldBackup = false;
                }
                if (!Main.dedServ)
                {
                    if (worldBackup)
                    {
                        Main.menuMode = 200;
                    }
                    else
                    {
                        Main.menuMode = 201;
                    }
                    return;
                }
                if (!worldBackup)
                {
                    Console.WriteLine(Language.GetTextValue("Error.LoadFailedNoBackup"));
                    return;
                }
                FileUtilities.Copy(Main.worldPathName + ".bak", Main.worldPathName, isCloudSave);
                FileUtilities.Delete(Main.worldPathName + ".bak", isCloudSave);
                WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
                if (loadFailed || !loadSuccess)
                {
                    WorldFile.LoadWorld(Main.ActiveWorldFileData.IsCloudSave);
                    if (loadFailed || !loadSuccess)
                    {
                        Console.WriteLine(Language.GetTextValue("Error.LoadFailed"));
                        return;
                    }
                }
            }
        }
        _lastSeed = Main.ActiveWorldFileData.Seed;
        SoundEngine.PlaySound(10);
        WorldFile.SetOngoingToTemps();
        Hooks.WorldLoaded();
    }
References Terraria.WorldGen._lastSeed, Terraria.Main.ActiveWorldFileData, Terraria.ModLoader.Console, Terraria.Utilities.FileUtilities.Copy(), Terraria.Main.dedServ, Terraria.Utilities.FileUtilities.Delete(), Terraria.Utilities.FileUtilities.Exists(), Terraria.Localization.Language.GetTextValue(), Terraria.WorldGen.loadFailed, Terraria.WorldGen.loadSuccess, Terraria.IO.WorldFile.LoadWorld(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.IO.WorldFile.SetOngoingToTemps(), Terraria.ModLoader.Logging.Terraria, Terraria.WorldGen.worldBackup, Terraria.WorldGen.Hooks.WorldLoaded(), and Terraria.Main.worldPathName.
Referenced by Terraria.WorldGen.serverLoadWorld().