TModLoader: Terraria.WorldGen.HardmodeWallsTask
HardmodeWallsTask()
static void Terraria.WorldGen.HardmodeWallsTask (GenerationProgress progress, GameConfiguration configuration) inline static private
Definition at line 24716 of file WorldGen.cs.
    {
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        double num13 = (double)Main.maxTilesX / 4200.0;
        int num10 = (int)(25.0 * num13);
        ShapeData shapeData = new ShapeData();
        int num11 = 0;
        while (num10 > 0)
        {
            if (++num11 % 15000 == 0)
            {
                num10--;
            }
            Point point = RandomWorldPoint((int)Main.worldSurface - 100, 1, 190, 1);
            Tile tile = Main.tile[point.X, point.Y];
            Tile tile2 = Main.tile[point.X, point.Y - 1];
            ushort num12 = 0;
            if (TileID.Sets.Crimson[tile.type])
            {
                num12 = (ushort)(192 + genRand.Next(4));
            }
            else if (TileID.Sets.Corrupt[tile.type])
            {
                num12 = (ushort)(188 + genRand.Next(4));
            }
            else if (TileID.Sets.Hallow[tile.type])
            {
                num12 = (ushort)(200 + genRand.Next(4));
            }
            if (tile.active() && num12 != 0 && !tile2.active())
            {
                bool flag = WorldUtils.Gen(new Point(point.X, point.Y - 1), new ShapeFloodFill(1000), Actions.Chain(new Modifiers.IsNotSolid(), new Modifiers.OnlyWalls(0, 54, 55, 56, 57, 58, 59, 61, 185, 212, 213, 214, 215, 2, 196, 197, 198, 199, 15, 40, 71, 64, 204, 205, 206, 207, 208, 209, 210, 211, 71), new Actions.Blank().Output(shapeData)));
                if (shapeData.Count > 50 && flag)
                {
                    WorldUtils.Gen(new Point(point.X, point.Y), new ModShapes.OuterOutline(shapeData, useDiagonals: true, useInterior: true), new Actions.PlaceWall(num12));
                    num10--;
                }
                shapeData.Clear();
            }
        }
    }
References Terraria.Tile.active(), Terraria.WorldBuilding.Actions.Chain(), Terraria.ID.TileID.Sets.Corrupt, Terraria.ID.TileID.Sets.Crimson, Terraria.WorldBuilding.WorldUtils.Gen(), Terraria.ID.TileID.Sets.Hallow, Terraria.Main.maxTilesX, Terraria.WorldBuilding.GenAction.Output(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Main.worldSurface.