TModLoader: Terraria.WorldGen.UnlockDoor
UnlockDoor()
static void Terraria.WorldGen.UnlockDoor (int i, int j) inline static
Definition at line 33780 of file WorldGen.cs.
    {
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        int num = j;
        if (Main.tile[i, num] == null)
        {
            return;
        }
        Tile tile;
        while (true)
        {
            tile = Main.tile[i, num];
            if (tile.frameY == 594)
            {
                break;
            }
            num--;
            tile = Main.tile[i, num];
            if (tile.frameY < 594 || num <= 0)
            {
                return;
            }
        }
        SoundEngine.PlaySound(22, i * 16, num * 16 + 16);
        for (int k = num; k <= num + 2; k++)
        {
            if (Main.tile[i, k] == null)
            {
                tile = (Main.tile[i, k] = default(Tile));
            }
            tile = Main.tile[i, k];
            tile.frameY += 54;
            for (int l = 0; l < 4; l++)
            {
                Dust.NewDust(new Vector2((float)(i * 16), (float)(k * 16)), 16, 16, 11);
            }
        }
        AchievementsHelper.NotifyProgressionEvent(22);
    }
References Terraria.Tile.frameY, Terraria.Dust.NewDust(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.tile.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Player.TileInteractionsUse().