TModLoader: Terraria.WorldGen.TreeGrowFX_AshShake
TreeGrowFX_AshShake()
static void Terraria.WorldGen.TreeGrowFX_AshShake (int x, int y, int height, bool hitTree = false) inline static private
    {
        //IL_0004: Unknown result type (might be due to invalid IL or missing references)
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_0238: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_0256: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0283: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_0126: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = new Vector2((float)x, (float)y) * 16f + new Vector2(8f, 8f);
        for (int num = 0; num > -height; num--)
        {
            if (num >= -height / 2 && Main.rand.Next(3) != 0)
            {
                int num2 = (hitTree ? 10 : 5);
                for (int i = 0; i < num2; i++)
                {
                    Dust.NewDustDirect(vector + new Vector2(-16f, (float)(num * 16)) + Utils.RandomVector2(Main.rand, -30f, 30f), 4, 4, 31, 0f, -3f, 100).velocity = Main.rand.NextVector2Circular(2f, 2f) + new Vector2(0f, -0.6f);
                }
            }
            if ((float)num >= (float)(-height) * 0.7f && Main.rand.Next(3) != 0)
            {
                int num3 = (hitTree ? 16 : 10);
                for (int j = 0; j < num3; j++)
                {
                    Dust dust = Dust.NewDustDirect(vector + new Vector2(-16f, (float)(num * 16)) + Utils.RandomVector2(Main.rand, -30f, 30f), 4, 4, 6, 0f, -4f, 0, default(Color), 1f + 0.7f * Main.rand.NextFloat());
                    dust.velocity = Main.rand.NextVector2Circular(2f, 2f) + new Vector2(0f, -0.6f);
                    if (Main.rand.Next(2) == 0)
                    {
                        dust.velocity *= 2f;
                        dust.noGravity = true;
                    }
                    dust.velocity += new Vector2(0f, hitTree ? (-1f) : (-2f));
                }
            }
            if (!hitTree)
            {
                Gore gore = Gore.NewGoreDirect(vector + new Vector2(-16f, (float)(num * 16 - 40)) + Utils.RandomVector2(Main.rand, -40f, 40f) * new Vector2(0.5f, 1f), Vector2.Zero, 61 + Main.rand.Next(3));
                gore.velocity *= 0.5f;
            }
        }
    }
References Terraria.Dust.NewDustDirect(), Terraria.Gore.NewGoreDirect(), Terraria.Main.rand, and Terraria.Utils.RandomVector2().