TModLoader: Terraria.WorldGen.IsThereASpawnablePrioritizedTownNPC
IsThereASpawnablePrioritizedTownNPC()
static bool Terraria.WorldGen.IsThereASpawnablePrioritizedTownNPC (int x, int y, ref bool canSpawnNewTownNPC) inline static
Definition at line 1861 of file WorldGen.cs.
    {
        if (CheckSpecialTownNPCSpawningConditions(prioritizedTownNPCType) && NPC.AnyNPCs(prioritizedTownNPCType))
        {
            canSpawnNewTownNPC = false;
            return true;
        }
        List<int> list = new List<int>();
        TownManager.AddOccupantsToList(x, y, list);
        for (int i = 0; i < list.Count; i++)
        {
            int num = list[i];
            if (Main.townNPCCanSpawn[num] && !NPC.AnyNPCs(num) && CheckSpecialTownNPCSpawningConditions(num))
            {
                prioritizedTownNPCType = num;
                canSpawnNewTownNPC = true;
                return true;
            }
        }
        for (int j = 0; j < NPCLoader.NPCCount; j++)
        {
            if (!Main.townNPCCanSpawn[j] || !CheckSpecialTownNPCSpawningConditions(j))
            {
                continue;
            }
            if (NPC.AnyNPCs(j))
            {
                Main.townNPCCanSpawn[j] = false;
                continue;
            }
            if (TownManager.HasRoomQuick(j))
            {
                prioritizedTownNPCType = j;
                canSpawnNewTownNPC = true;
                return true;
            }
            if (!NPCID.Sets.IsTownPet[prioritizedTownNPCType] || NPCID.Sets.IsTownPet[j])
            {
                prioritizedTownNPCType = j;
                canSpawnNewTownNPC = true;
                return true;
            }
        }
        return false;
    }
References Terraria.NPC.AnyNPCs(), Terraria.WorldGen.CheckSpecialTownNPCSpawningConditions(), Terraria.ID.NPCID.Sets.IsTownPet, Terraria.ModLoader.NPCLoader.NPCCount, Terraria.WorldGen.prioritizedTownNPCType, Terraria.WorldGen.TownManager, and Terraria.Main.townNPCCanSpawn.
Referenced by Terraria.WorldGen.SpawnTownNPC().