TModLoader: Terraria.WorldGen.AddBuriedChest
AddBuriedChest() [2/2]
static bool Terraria.WorldGen.AddBuriedChest (Point point, int contain = 0, bool notNearOtherChests = false, int Style = -1) inline static
Definition at line 32342 of file WorldGen.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        return AddBuriedChest(point.X, point.Y, contain, notNearOtherChests, Style, trySlope: false, 0);
    }
Referenced by Terraria.GameContent.Biomes.MahoganyTreeBiome.Place(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceChests(), and Terraria.WorldGen.Spread.Spider().