TModLoader: Terraria.WorldGen.CheckChand
CheckChand()
static void Terraria.WorldGen.CheckChand (int i, int j, int type) inline static
    {
        if (destroyObject)
        {
            return;
        }
        bool flag = false;
        int num = i;
        int num12 = j;
        int num14 = 3;
        if (type == 454)
        {
            num14 = 4;
        }
        num = Main.tile[i, j].frameX / 18;
        int num15 = 0;
        while (num >= num14)
        {
            num15++;
            num -= num14;
        }
        int num16 = i - num;
        int num17 = 18 * num14 * num15;
        if (num >= num14)
        {
            num -= num14;
        }
        num = i - num;
        num12 = Main.tile[i, j].frameY / 18;
        int num18 = 0;
        while (num12 >= 3)
        {
            num18++;
            num12 -= 3;
        }
        if (num17 >= 108)
        {
            num18 += 37 * (num17 / 108);
        }
        int num19 = 54 * num18;
        if (num17 >= 108)
        {
            num19 -= 54 * (num17 / 108) * 37;
        }
        if (num12 >= 3)
        {
            num12 -= 3;
        }
        num12 = j - num12;
        for (int k = num; k < num + num14; k++)
        {
            for (int l = num12; l < num12 + 3; l++)
            {
                if (Main.tile[k, l] == null)
                {
                    Main.tile[k, l] = default(Tile);
                }
                if (!Main.tile[k, l].active() || Main.tile[k, l].type != type || Main.tile[k, l].frameX != (k - num16) * 18 + num17 || Main.tile[k, l].frameY != (l - num12) * 18 + num19)
                {
                    flag = true;
                }
            }
        }
        if (Main.tile[num + 1, num12 - 1] == null)
        {
            Main.tile[num + 1, num12 - 1] = default(Tile);
        }
        if (!Main.tile[num + 1, num12 - 1].nactive() || !Main.tileSolid[Main.tile[num + 1, num12 - 1].type] || Main.tileSolidTop[Main.tile[num + 1, num12 - 1].type])
        {
            flag = true;
        }
        if (!flag)
        {
            return;
        }
        destroyObject = true;
        bool drop = TileLoader.Drop(i, j, type);
        for (int m = num; m < num + num14; m++)
        {
            for (int n = num12; n < num12 + 3; n++)
            {
                if (Main.tile[m, n].type == type && Main.tile[m, n].active())
                {
                    KillTile(m, n);
                }
            }
        }
        using (new Item.DisableNewItemMethod(!drop))
        {
            if (type == 454)
            {
                switch (Main.rand.Next(9))
                {
                case 2:
                case 3:
                case 4:
                {
                    int num5 = Main.rand.Next(10, 31);
                    while (num5 > 0)
                    {
                        int num6 = Main.rand.Next(2, 11);
                        if (num6 > num5)
{
                            num6 = num5;
                        }
                        num5 -= num6;
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 72, num6);
                    }
                    break;
                }
                case 5:
                case 6:
                {
                    int num9 = Main.rand.Next(60, 80);
                    while (num9 > 0)
                    {
                        int num10 = Main.rand.Next(3, 16);
                        if (num10 > num9)
{
                            num10 = num9;
                        }
                        num9 -= num10;
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16 - 10, j * 16 - 10, 52, 52, 72, num10);
                    }
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1358);
                    break;
                }
                case 7:
                {
                    int num7 = Main.rand.Next(10, 31);
                    while (num7 > 0)
                    {
                        int num8 = Main.rand.Next(2, 9);
                        if (num8 > num7)
{
                            num8 = num7;
                        }
                        num7 -= num8;
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16 - 10, j * 16 - 10, 52, 52, 72, num8);
                    }
                    if (Main.rand.Next(8) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3532);
                    }
                    if (Main.rand.Next(8) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3532);
                    }
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 73);
                    break;
                }
                case 8:
                {
                    int num20 = 100;
                    while (num20 > 0)
                    {
                        int num2 = Main.rand.Next(3, 16);
                        if (num2 > num20)
{
                            num2 = num20;
                        }
                        num20 -= num2;
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16 - 10, j * 16 - 10, 52, 52, 72, num2);
                    }
                    int num3 = Main.rand.Next(30, 91);
                    while (num3 > 0)
                    {
                        int num4 = Main.rand.Next(7, 14);
                        if (num4 > num3)
{
                            num4 = num3;
                        }
                        num3 -= num4;
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16 - 10, j * 16 - 10, 52, 52, 1349, num4);
                    }
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1358);
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 73);
                    break;
                }
                }
            }
            if (type == 34)
            {
                int type2;
                switch (num18)
                {
                case 1:
                    type2 = 107;
                    break;
                case 2:
                    type2 = 108;
                    break;
                case 3:
                    type2 = 710;
                    break;
                case 4:
                    type2 = 711;
                    break;
                case 5:
                    type2 = 712;
                    break;
                case 6:
                    type2 = 1812;
                    break;
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                case 13:
                case 14:
                case 15:
                case 16:
                case 17:
                    type2 = 2055 + num18 - 7;
                    break;
                case 18:
                case 19:
                case 20:
                case 21:
                    type2 = 2141 + num18 - 18;
                    break;
                default:
                    type2 = num18 switch
                    {
                        22 => 2224,
                        23 => 2525,
                        24 => 2543,
                        25 => 2558,
                        26 => 2573,
                        27 => 2652,
                        28 => 2653,
                        29 => 2654,
                        30 => 2655,
                        31 => 2656,
                        32 => 2657,
                        33 => 2813,
                        34 => 3177,
                        35 => 3179,
                        36 => 3178,
                        37 => 3894,
                        38 => 3938,
                        39 => 3964,
                        40 => 4152,
                        41 => 4173,
                        42 => 4194,
                        43 => 4215,
                        44 => 4305,
                        45 => 4573,
                        46 => 5155,
                        47 => 5176,
                        48 => 5197,
                        _ => 106,
                    };
                    break;
                }
                Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, type2);
            }
            destroyObject = false;
            for (int num11 = num - 1; num11 < num + num14 + 1; num11++)
            {
                for (int num13 = num12 - 1; num13 < num12 + 4; num13++)
                {
                    TileFrame(num11, num13);
                }
            }
        }
    }
References Terraria.ModLoader.TileLoader.Drop(), Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Main.tileSolidTop.