TModLoader: Terraria.WorldGen.SpawnTownNPC
SpawnTownNPC()
static TownNPCSpawnResult Terraria.WorldGen.SpawnTownNPC (int x, int y) inline static
    {
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_024e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_0558: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0403: Unknown result type (might be due to invalid IL or missing references)
        if (Main.wallHouse[Main.tile[x, y].wall])
        {
            canSpawn = true;
        }
        if (!canSpawn)
        {
            return TownNPCSpawnResult.Blocked;
        }
        if (!StartRoomCheck(x, y))
        {
            return TownNPCSpawnResult.Blocked;
        }
        if (!RoomNeeds(prioritizedTownNPCType))
        {
            return TownNPCSpawnResult.Blocked;
        }
        int num = FindAHomelessNPC();
        int type = prioritizedTownNPCType;
        if (num != -1)
        {
            type = Main.npc[num].type;
        }
        Point roomPosition = Point.Zero;
        bool flag = NPCID.Sets.IsTownPet[type] && TownManager.HasRoom(type, out roomPosition);
        if ((roomHasStinkbug || roomHasEchoStinkbug) && !flag)
        {
            return TownNPCSpawnResult.Blocked;
        }
        ScoreRoom(-1, type);
        if (hiScore <= 0)
        {
            return TownNPCSpawnResult.Blocked;
        }
        bool canSpawnNewTownNPC = true;
        if (!IsThereASpawnablePrioritizedTownNPC(bestX, bestY, ref canSpawnNewTownNPC))
        {
            return TownNPCSpawnResult.Blocked;
        }
        type = prioritizedTownNPCType;
        if (num != -1)
        {
            Main.townNPCCanSpawn[prioritizedTownNPCType] = false;
            Main.npc[num].homeTileX = bestX;
            Main.npc[num].homeTileY = bestY;
            Main.npc[num].homeless = false;
            AchievementsHelper.NotifyProgressionEvent(8);
            prioritizedTownNPCType = 0;
            return TownNPCSpawnResult.RelocatedHomeless;
        }
        if (canSpawnNewTownNPC && num == -1)
        {
            if (TownManager.HasRoom(type, out var roomPosition2) && !currentlyTryingToUseAlternateHousingSpot)
            {
                int num8 = bestX;
                int num2 = bestY;
                currentlyTryingToUseAlternateHousingSpot = true;
                TownNPCSpawnResult townNPCSpawnResult = SpawnTownNPC(roomPosition2.X, roomPosition2.Y - 2);
                currentlyTryingToUseAlternateHousingSpot = false;
                bestX = num8;
                bestY = num2;
                if (townNPCSpawnResult == TownNPCSpawnResult.Successful)
                {
                    return townNPCSpawnResult;
                }
            }
            int num3 = bestX;
            int num4 = bestY;
            int npcTypeToSpawn = prioritizedTownNPCType;
            if (IsRoomConsideredAlreadyOccupied(num3, num4, npcTypeToSpawn))
            {
                return TownNPCSpawnResult.BlockedInfiHousing;
            }
            bool flag2 = false;
            Rectangle val;
            if (!flag2)
            {
                flag2 = true;
                Rectangle value = default(Rectangle);
                ((Rectangle)(ref value))._002Ector(num3 * 16 + 8 - NPC.sWidth / 2 - NPC.safeRangeX, num4 * 16 + 8 - NPC.sHeight / 2 - NPC.safeRangeY, NPC.sWidth + NPC.safeRangeX * 2, NPC.sHeight + NPC.safeRangeY * 2);
                for (int i = 0; i < 255; i++)
                {
                    if (Main.player[i].active)
                    {
                        val = new Rectangle((int)Main.player[i].position.X, (int)Main.player[i].position.Y, Main.player[i].width, Main.player[i].height);
                        if (((Rectangle)(ref val)).Intersects(value))
{
                            flag2 = false;
                            break;
                        }
                    }
                }
            }
            if (!flag2 && !((double)num4 > Main.worldSurface))
            {
                Rectangle value2 = default(Rectangle);
                for (int j = 1; j < 500; j++)
                {
                    for (int k = 0; k < 2; k++)
                    {
                        num3 = ((k != 0) ? (bestX - j) : (bestX + j));
                        if (num3 > 10 && num3 < Main.maxTilesX - 10)
{
                            int num5 = bestY - j;
                            double num6 = bestY + j;
                            if (num5 < 10)
{
                                num5 = 10;
                            }
                            if (num6 > Main.worldSurface)
{
                                num6 = Main.worldSurface;
                            }
                            for (int l = num5; (double)l < num6; l++)
{
                                num4 = l;
                                if (!Main.tile[num3, num4].nactive() || !Main.tileSolid[Main.tile[num3, num4].type])
{
                                    continue;
                                }
                                if (Collision.SolidTiles(num3 - 1, num3 + 1, num4 - 3, num4 - 1))
{
                                    break;
                                }
                                flag2 = true;
                                ((Rectangle)(ref value2))._002Ector(num3 * 16 + 8 - NPC.sWidth / 2 - NPC.safeRangeX, num4 * 16 + 8 - NPC.sHeight / 2 - NPC.safeRangeY, NPC.sWidth + NPC.safeRangeX * 2, NPC.sHeight + NPC.safeRangeY * 2);
                                for (int m = 0; m < 255; m++)
{
                                    if (Main.player[m].active)
{
                                        val = new Rectangle((int)Main.player[m].position.X, (int)Main.player[m].position.Y, Main.player[m].width, Main.player[m].height);
                                        if (((Rectangle)(ref val)).Intersects(value2))
{
                                            flag2 = false;
                                            break;
                                        }
                                    }
                                }
                                break;
                            }
                        }
                        if (flag2)
{
                            break;
                        }
                    }
                    if (flag2)
                    {
                        break;
                    }
                }
            }
            int num7 = NPC.NewNPC(NPC.GetSpawnSourceForTownSpawn(), num3 * 16, num4 * 16, type, 1);
            Main.townNPCCanSpawn[type] = false;
            Main.npc[num7].homeTileX = bestX;
            Main.npc[num7].homeTileY = bestY;
            if (num3 < bestX)
            {
                Main.npc[num7].direction = 1;
            }
            else if (num3 > bestX)
            {
                Main.npc[num7].direction = -1;
            }
            Main.npc[num7].netUpdate = true;
            string fullName = Main.npc[num7].FullName;
            if (Main.netMode == 0)
            {
                Main.NewText(Language.GetTextValue("Announcement.HasArrived", fullName), 50, 125);
            }
            else if (Main.netMode == 2)
            {
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasArrived", Main.npc[num7].GetFullNetName()), new Color(50, 125, 255));
            }
            AchievementsHelper.NotifyProgressionEvent(8);
            switch (Main.npc[num7].type)
            {
            case 160:
                AchievementsHelper.NotifyProgressionEvent(18);
                NPC.unlockedTruffleSpawn = true;
                NetMessage.SendData(7);
                break;
            case 17:
                NPC.unlockedMerchantSpawn = true;
                break;
            case 207:
                NPC.unlockedDyeTraderSpawn = true;
                break;
            case 18:
                NPC.unlockedNurseSpawn = true;
                break;
            case 19:
                NPC.unlockedArmsDealerSpawn = true;
                break;
            case 38:
                NPC.unlockedDemolitionistSpawn = true;
                break;
            case 208:
                NPC.unlockedPartyGirlSpawn = true;
                break;
            case 663:
                NPC.unlockedPrincessSpawn = true;
                break;
            case 678:
                NPC.unlockedSlimeGreenSpawn = true;
                break;
            }
            CheckAchievement_RealEstateAndTownSlimes();
            prioritizedTownNPCType = 0;
        }
        return TownNPCSpawnResult.Successful;
    }
References Terraria.WorldGen.bestX, Terraria.WorldGen.bestY, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.WorldGen.canSpawn, Terraria.WorldGen.CheckAchievement_RealEstateAndTownSlimes(), Terraria.WorldGen.currentlyTryingToUseAlternateHousingSpot, Terraria.WorldGen.FindAHomelessNPC(), Terraria.Localization.NetworkText.FromKey(), Terraria.NPC.GetSpawnSourceForTownSpawn(), Terraria.Localization.Language.GetTextValue(), Terraria.WorldGen.hiScore, Terraria.WorldGen.IsRoomConsideredAlreadyOccupied(), Terraria.WorldGen.IsThereASpawnablePrioritizedTownNPC(), Terraria.ID.NPCID.Sets.IsTownPet, Terraria.Main.maxTilesX, Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.NewText(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Main.npc, Terraria.Main.player, Terraria.WorldGen.prioritizedTownNPCType, Terraria.WorldGen.roomHasEchoStinkbug, Terraria.WorldGen.roomHasStinkbug, Terraria.WorldGen.RoomNeeds(), Terraria.NPC.safeRangeX, Terraria.NPC.safeRangeY, Terraria.WorldGen.ScoreRoom(), Terraria.NetMessage.SendData(), Terraria.NPC.sHeight, Terraria.Collision.SolidTiles(), Terraria.WorldGen.SpawnTownNPC(), Terraria.WorldGen.StartRoomCheck(), Terraria.NPC.sWidth, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.WorldGen.TownManager, Terraria.Main.townNPCCanSpawn, Terraria.Main.wallHouse, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.moveRoom(), and Terraria.WorldGen.SpawnTownNPC().