TModLoader: Terraria.WorldGen.IsThereASpawnablePrioritizedTownNPC_Old
IsThereASpawnablePrioritizedTownNPC_Old()
static bool Terraria.WorldGen.IsThereASpawnablePrioritizedTownNPC_Old (int x, int y) inline static
Definition at line 1907 of file WorldGen.cs.
    {
        if (CheckSpecialTownNPCSpawningConditions(prioritizedTownNPCType) && NPC.AnyNPCs(prioritizedTownNPCType))
        {
            return true;
        }
        List<int> list = new List<int>();
        TownManager.AddOccupantsToList(x, y, list);
        for (int i = 0; i < list.Count; i++)
        {
            int num = list[i];
            if (Main.townNPCCanSpawn[num] && !NPC.AnyNPCs(num) && CheckSpecialTownNPCSpawningConditions(num))
            {
                prioritizedTownNPCType = num;
                return true;
            }
        }
        int num2 = -1;
        for (int j = 0; j < Main.townNPCCanSpawn.Length; j++)
        {
            if (!Main.townNPCCanSpawn[j] || !CheckSpecialTownNPCSpawningConditions(j))
            {
                continue;
            }
            if (NPC.AnyNPCs(j))
            {
                Main.townNPCCanSpawn[j] = false;
            }
            else if (TownManager.HasRoomQuick(j))
            {
                if (num2 == -1)
                {
                    num2 = j;
                }
            }
            else if (!NPCID.Sets.IsTownPet[prioritizedTownNPCType] || NPCID.Sets.IsTownPet[j])
            {
                prioritizedTownNPCType = j;
                return true;
            }
        }
        if (num2 != -1)
        {
            prioritizedTownNPCType = num2;
            return true;
        }
        return false;
    }
References Terraria.GameContent.TownRoomManager.AddOccupantsToList(), Terraria.NPC.AnyNPCs(), Terraria.WorldGen.CheckSpecialTownNPCSpawningConditions(), Terraria.GameContent.TownRoomManager.HasRoomQuick(), Terraria.ID.NPCID.Sets.IsTownPet, Terraria.WorldGen.prioritizedTownNPCType, Terraria.WorldGen.TownManager, and Terraria.Main.townNPCCanSpawn.