TModLoader: Terraria.WorldGen.paintColor
paintColor()
static Color Terraria.WorldGen.paintColor (int color) inline static
Definition at line 36685 of file WorldGen.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c5: Unknown result type (might be due to invalid IL or missing references)
        Color white = Color.White;
        if (color == 1 || color == 13)
        {
            ((Color)(ref white)).R = byte.MaxValue;
            ((Color)(ref white)).G = 0;
            ((Color)(ref white)).B = 0;
        }
        if (color == 2 || color == 14)
        {
            ((Color)(ref white)).R = byte.MaxValue;
            ((Color)(ref white)).G = 127;
            ((Color)(ref white)).B = 0;
        }
        if (color == 3 || color == 15)
        {
            ((Color)(ref white)).R = byte.MaxValue;
            ((Color)(ref white)).G = byte.MaxValue;
            ((Color)(ref white)).B = 0;
        }
        if (color == 4 || color == 16)
        {
            ((Color)(ref white)).R = 127;
            ((Color)(ref white)).G = byte.MaxValue;
            ((Color)(ref white)).B = 0;
        }
        if (color == 5 || color == 17)
        {
            ((Color)(ref white)).R = 0;
            ((Color)(ref white)).G = byte.MaxValue;
            ((Color)(ref white)).B = 0;
        }
        if (color == 6 || color == 18)
        {
            ((Color)(ref white)).R = 0;
            ((Color)(ref white)).G = byte.MaxValue;
            ((Color)(ref white)).B = 127;
        }
        if (color == 7 || color == 19)
        {
            ((Color)(ref white)).R = 0;
            ((Color)(ref white)).G = byte.MaxValue;
            ((Color)(ref white)).B = byte.MaxValue;
        }
        if (color == 8 || color == 20)
        {
            ((Color)(ref white)).R = 0;
            ((Color)(ref white)).G = 127;
            ((Color)(ref white)).B = byte.MaxValue;
        }
        if (color == 9 || color == 21)
        {
            ((Color)(ref white)).R = 0;
            ((Color)(ref white)).G = 0;
            ((Color)(ref white)).B = byte.MaxValue;
        }
        if (color == 10 || color == 22)
        {
            ((Color)(ref white)).R = 127;
            ((Color)(ref white)).G = 0;
            ((Color)(ref white)).B = byte.MaxValue;
        }
        if (color == 11 || color == 23)
        {
            ((Color)(ref white)).R = byte.MaxValue;
            ((Color)(ref white)).G = 0;
            ((Color)(ref white)).B = byte.MaxValue;
        }
        if (color == 12 || color == 24)
        {
            ((Color)(ref white)).R = byte.MaxValue;
            ((Color)(ref white)).G = 0;
            ((Color)(ref white)).B = 127;
        }
        if (color == 25)
        {
            ((Color)(ref white)).R = 75;
            ((Color)(ref white)).G = 75;
            ((Color)(ref white)).B = 75;
        }
        if (color == 26)
        {
            ((Color)(ref white)).R = byte.MaxValue;
            ((Color)(ref white)).G = byte.MaxValue;
            ((Color)(ref white)).B = byte.MaxValue;
        }
        if (color == 27)
        {
            ((Color)(ref white)).R = 175;
            ((Color)(ref white)).G = 175;
            ((Color)(ref white)).B = 175;
        }
        if (color == 28)
        {
            ((Color)(ref white)).R = byte.MaxValue;
            ((Color)(ref white)).G = 178;
            ((Color)(ref white)).B = 125;
        }
        if (color == 29)
        {
            ((Color)(ref white)).R = 25;
            ((Color)(ref white)).G = 25;
            ((Color)(ref white)).B = 25;
        }
        if (color == 30)
        {
            ((Color)(ref white)).R = 200;
            ((Color)(ref white)).G = 200;
            ((Color)(ref white)).B = 200;
            ((Color)(ref white)).A = 150;
        }
        return white;
    }
Referenced by Terraria.Graphics.Light.TileLightScanner.ApplyTileLight(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.Map.MapHelper.MapColor(), and Terraria.Main.TryApplyingPlayerStringColor().