TModLoader: Terraria.WorldGen.SpawnFallingBlockProjectile
SpawnFallingBlockProjectile()
static bool Terraria.WorldGen.SpawnFallingBlockProjectile (int i, int j, Tile tileCache, Tile tileTopCache, Tile tileBottomCache, int type) inline static private
    {
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode == 1)
        {
            return false;
        }
        if (tileCache == null || tileTopCache == null || tileBottomCache == null)
        {
            return false;
        }
        if (!BlockBelowMakesSandFall(i, j))
        {
            return false;
        }
        if (!AllowsSandfall(tileTopCache))
        {
            return false;
        }
        GetSandfallProjData(type, out var projType, out var dmg);
        tileCache.ClearTile();
        if (Main.netMode == 0)
        {
            int num = Projectile.NewProjectile(GetProjectileSource_TileBreak(i, j), i * 16 + 8, j * 16 + 8, 0f, 0.41f, projType, dmg, 0f, Main.myPlayer);
            Main.projectile[num].ai[0] = 1f;
            SquareTileFrame(i, j);
        }
        if (Main.netMode == 2)
        {
            bool flag = false;
            for (int k = 0; k < 1000; k++)
            {
                if (Main.projectile[k].active && Main.projectile[k].owner == Main.myPlayer && Main.projectile[k].type == projType && Math.Abs(Main.projectile[k].timeLeft - 3600) < 60 && Main.projectile[k].Distance(new Vector2((float)(i * 16 + 8), (float)(j * 16 + 10))) < 4f)
                {
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                int num2 = Projectile.NewProjectile(GetProjectileSource_TileBreak(i, j), i * 16 + 8, j * 16 + 8, 0f, 2.5f, projType, dmg, 0f, Main.myPlayer);
                Main.projectile[num2].velocity.Y = 0.5f;
                Main.projectile[num2].position.Y += 2f;
                Main.projectile[num2].netUpdate = true;
            }
            SquareTileFrame(i, j);
            NetMessage.SendTileSquare(-1, i, j);
            ExploitDestroyQueue.Enqueue(new Point(i, j));
            ExploitDestroyQueue.Enqueue(new Point(i, j - 1));
        }
        return true;
    }
References Terraria.Entity.active, Terraria.Projectile.ai, Terraria.Tile.ClearTile(), Terraria.Entity.Distance(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.netUpdate, Terraria.Projectile.NewProjectile(), Terraria.Projectile.owner, Terraria.Entity.position, Terraria.Main.projectile, Terraria.NetMessage.SendTileSquare(), Terraria.Projectile.timeLeft, Terraria.Projectile.type, and Terraria.Entity.velocity.