TModLoader: Terraria.WorldGen.HardmodeAnnouncementTask
HardmodeAnnouncementTask()
static void Terraria.WorldGen.HardmodeAnnouncementTask (GenerationProgress progress, GameConfiguration configuration) inline static private
Definition at line 24769 of file WorldGen.cs.
    {
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode == 0)
        {
            Main.NewText(Lang.misc[15].Value, 50, byte.MaxValue, 130);
        }
        else if (Main.netMode == 2)
        {
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[15].Key), new Color(50, 255, 130));
        }
        AchievementsHelper.NotifyProgressionEvent(9);
    }
References Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Localization.NetworkText.FromKey(), Terraria.Localization.LocalizedText.Key, Terraria.Lang.misc, Terraria.Main.netMode, Terraria.Main.NewText(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), and Terraria.Localization.LocalizedText.Value.