TModLoader: Terraria.WorldGen.CheckTree
CheckTree()
static void Terraria.WorldGen.CheckTree (int i, int j) inline static
Definition at line 48834 of file WorldGen.cs.
    {
        int num = -1;
        int num2 = -1;
        int num3 = -1;
        int num4 = -1;
        Tile tile = Main.tile[i, j];
        int type = tile.type;
        tile = Main.tile[i, j];
        int frameX = tile.frameX;
        tile = Main.tile[i, j];
        int frameY = tile.frameY;
        if (Main.tile[i - 1, j] != null)
        {
            tile = Main.tile[i - 1, j];
            if (tile.active())
            {
                tile = Main.tile[i - 1, j];
                num2 = tile.type;
            }
        }
        if (Main.tile[i + 1, j] != null)
        {
            tile = Main.tile[i + 1, j];
            if (tile.active())
            {
                tile = Main.tile[i + 1, j];
                num3 = tile.type;
            }
        }
        if (Main.tile[i, j - 1] != null)
        {
            tile = Main.tile[i, j - 1];
            if (tile.active())
            {
                tile = Main.tile[i, j - 1];
                num = tile.type;
            }
        }
        if (Main.tile[i, j + 1] != null)
        {
            tile = Main.tile[i, j + 1];
            if (tile.active())
            {
                tile = Main.tile[i, j + 1];
                num4 = tile.type;
            }
        }
        if (Main.tile[i - 1, j - 1] != null)
        {
            tile = Main.tile[i - 1, j - 1];
            if (tile.active())
            {
                tile = Main.tile[i - 1, j - 1];
                _ = ref tile.type;
            }
        }
        if (Main.tile[i + 1, j - 1] != null)
        {
            tile = Main.tile[i + 1, j - 1];
            if (tile.active())
            {
                tile = Main.tile[i + 1, j - 1];
                _ = ref tile.type;
            }
        }
        if (Main.tile[i - 1, j + 1] != null)
        {
            tile = Main.tile[i - 1, j + 1];
            if (tile.active())
            {
                tile = Main.tile[i - 1, j + 1];
                _ = ref tile.type;
            }
        }
        if (Main.tile[i + 1, j + 1] != null)
        {
            tile = Main.tile[i + 1, j + 1];
            if (tile.active())
            {
                tile = Main.tile[i + 1, j + 1];
                _ = ref tile.type;
            }
        }
        if (num4 == 23 || num4 == 661)
        {
            num4 = 2;
        }
        if (num4 == 477)
        {
            num4 = 2;
        }
        if (num4 == 60)
        {
            num4 = 2;
        }
        if (num4 == 70)
        {
            num4 = 2;
        }
        if (num4 == 109)
        {
            num4 = 2;
        }
        if (num4 == 147)
        {
            num4 = 2;
        }
        if (num4 == 199 || num4 == 662)
        {
            num4 = 2;
        }
        if (num4 == 492)
        {
            num4 = 2;
        }
        if (TileLoader.CanGrowModTree(num4))
        {
            num4 = 2;
        }
        if (num4 != 2 && num4 != type)
        {
            tile = Main.tile[i, j];
            if (tile.frameX == 0)
            {
                tile = Main.tile[i, j];
                if (tile.frameY <= 130)
                {
                    goto IL_03b4;
                }
            }
            tile = Main.tile[i, j];
            if (tile.frameX == 22)
            {
                tile = Main.tile[i, j];
                if (tile.frameY <= 130)
                {
                    goto IL_03b4;
                }
            }
            tile = Main.tile[i, j];
            if (tile.frameX == 44)
            {
                tile = Main.tile[i, j];
                if (tile.frameY <= 130)
                {
                    goto IL_03b4;
                }
            }
        }
        goto IL_03be;
        IL_03b4:
        KillTile(i, j);
        goto IL_03be;
        IL_05e9:
        if (num2 == type && num3 == type)
        {
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 0)
            {
                tile = Main.tile[i, j];
                tile.frameX = 110;
                tile = Main.tile[i, j];
                tile.frameY = 66;
            }
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 1)
            {
                tile = Main.tile[i, j];
                tile.frameX = 110;
                tile = Main.tile[i, j];
                tile.frameY = 88;
            }
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 2)
            {
                tile = Main.tile[i, j];
                tile.frameX = 110;
                tile = Main.tile[i, j];
                tile.frameY = 110;
            }
        }
        else if (num2 == type)
        {
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 0)
            {
                tile = Main.tile[i, j];
                tile.frameX = 88;
                tile = Main.tile[i, j];
                tile.frameY = 0;
            }
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 1)
            {
                tile = Main.tile[i, j];
                tile.frameX = 88;
                tile = Main.tile[i, j];
                tile.frameY = 22;
            }
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 2)
            {
                tile = Main.tile[i, j];
                tile.frameX = 88;
                tile = Main.tile[i, j];
                tile.frameY = 44;
            }
        }
        else if (num3 == type)
        {
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 0)
            {
                tile = Main.tile[i, j];
                tile.frameX = 66;
                tile = Main.tile[i, j];
                tile.frameY = 66;
            }
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 1)
            {
                tile = Main.tile[i, j];
                tile.frameX = 66;
                tile = Main.tile[i, j];
                tile.frameY = 88;
            }
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 2)
            {
                tile = Main.tile[i, j];
                tile.frameX = 66;
                tile = Main.tile[i, j];
                tile.frameY = 110;
            }
        }
        else
        {
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 0)
            {
                tile = Main.tile[i, j];
                tile.frameX = 0;
                tile = Main.tile[i, j];
                tile.frameY = 0;
            }
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 1)
            {
                tile = Main.tile[i, j];
                tile.frameX = 0;
                tile = Main.tile[i, j];
                tile.frameY = 22;
            }
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 2)
            {
                tile = Main.tile[i, j];
                tile.frameX = 0;
                tile = Main.tile[i, j];
                tile.frameY = 44;
            }
        }
        goto IL_0978;
        IL_0e29:
        tile = Main.tile[i, j];
        if (tile.frameX == 44)
        {
            tile = Main.tile[i, j];
            if (tile.frameY != 198)
            {
                tile = Main.tile[i, j];
                if (tile.frameY != 220)
                {
                    tile = Main.tile[i, j];
                    if (tile.frameY != 242)
                    {
                        goto IL_0eb1;
                    }
                }
            }
            goto IL_0e9a;
        }
        goto IL_0eb1;
        IL_0f1f:
        tile = Main.tile[i, j];
        if (tile.frameX == 66)
        {
            tile = Main.tile[i, j];
            if (tile.frameY != 198)
            {
                tile = Main.tile[i, j];
                if (tile.frameY != 220)
                {
                    tile = Main.tile[i, j];
                    if (tile.frameY != 242)
                    {
                        goto IL_0fa7;
                    }
                }
            }
            goto IL_0f90;
        }
        goto IL_0fa7;
        IL_103b:
        if (num2 == type || num3 == type)
        {
            if (num4 == type)
            {
                if (num2 == type && num3 == type)
                {
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 0)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 132;
                        tile = Main.tile[i, j];
                        tile.frameY = 132;
                    }
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 1)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 132;
                        tile = Main.tile[i, j];
                        tile.frameY = 154;
                    }
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 2)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 132;
                        tile = Main.tile[i, j];
                        tile.frameY = 176;
                    }
                }
                else if (num2 == type)
                {
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 0)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 132;
                        tile = Main.tile[i, j];
                        tile.frameY = 0;
                    }
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 1)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 132;
                        tile = Main.tile[i, j];
                        tile.frameY = 22;
                    }
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 2)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 132;
                        tile = Main.tile[i, j];
                        tile.frameY = 44;
                    }
                }
                else if (num3 == type)
                {
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 0)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 132;
                        tile = Main.tile[i, j];
                        tile.frameY = 66;
                    }
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 1)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 132;
                        tile = Main.tile[i, j];
                        tile.frameY = 88;
                    }
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 2)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 132;
                        tile = Main.tile[i, j];
                        tile.frameY = 110;
                    }
                }
            }
            else if (num2 == type && num3 == type)
            {
                tile = Main.tile[i, j];
                if (tile.frameNumber() == 0)
                {
                    tile = Main.tile[i, j];
                    tile.frameX = 154;
                    tile = Main.tile[i, j];
                    tile.frameY = 132;
                }
                tile = Main.tile[i, j];
                if (tile.frameNumber() == 1)
                {
                    tile = Main.tile[i, j];
                    tile.frameX = 154;
                    tile = Main.tile[i, j];
                    tile.frameY = 154;
                }
                tile = Main.tile[i, j];
                if (tile.frameNumber() == 2)
                {
                    tile = Main.tile[i, j];
                    tile.frameX = 154;
                    tile = Main.tile[i, j];
                    tile.frameY = 176;
                }
            }
            else if (num2 == type)
            {
                tile = Main.tile[i, j];
                if (tile.frameNumber() == 0)
                {
                    tile = Main.tile[i, j];
                    tile.frameX = 154;
                    tile = Main.tile[i, j];
                    tile.frameY = 0;
                }
                tile = Main.tile[i, j];
                if (tile.frameNumber() == 1)
                {
                    tile = Main.tile[i, j];
                    tile.frameX = 154;
                    tile = Main.tile[i, j];
                    tile.frameY = 22;
                }
                tile = Main.tile[i, j];
                if (tile.frameNumber() == 2)
                {
                    tile = Main.tile[i, j];
                    tile.frameX = 154;
                    tile = Main.tile[i, j];
                    tile.frameY = 44;
                }
            }
            else if (num3 == type)
            {
                tile = Main.tile[i, j];
                if (tile.frameNumber() == 0)
                {
                    tile = Main.tile[i, j];
                    tile.frameX = 154;
                    tile = Main.tile[i, j];
                    tile.frameY = 66;
                }
                tile = Main.tile[i, j];
                if (tile.frameNumber() == 1)
                {
                    tile = Main.tile[i, j];
                    tile.frameX = 154;
                    tile = Main.tile[i, j];
                    tile.frameY = 88;
                }
                tile = Main.tile[i, j];
                if (tile.frameNumber() == 2)
                {
                    tile = Main.tile[i, j];
                    tile.frameX = 154;
                    tile = Main.tile[i, j];
                    tile.frameY = 110;
                }
            }
        }
        else
        {
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 0)
            {
                tile = Main.tile[i, j];
                tile.frameX = 110;
                tile = Main.tile[i, j];
                tile.frameY = 0;
            }
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 1)
            {
                tile = Main.tile[i, j];
                tile.frameX = 110;
                tile = Main.tile[i, j];
                tile.frameY = 22;
            }
            tile = Main.tile[i, j];
            if (tile.frameNumber() == 2)
            {
                tile = Main.tile[i, j];
                tile.frameX = 110;
                tile = Main.tile[i, j];
                tile.frameY = 44;
            }
        }
        goto IL_16e6;
        IL_0f90:
        if (num2 != type)
        {
            KillTile(i, j);
        }
        goto IL_16e6;
        IL_0fa7:
        if (num4 == -1 || num4 == 23)
        {
            KillTile(i, j);
        }
        else if (num != type)
        {
            tile = Main.tile[i, j];
            if (tile.frameY < 198)
            {
                tile = Main.tile[i, j];
                if (tile.frameX != 22)
                {
                    tile = Main.tile[i, j];
                    if (tile.frameX != 44)
                    {
                        goto IL_103b;
                    }
                }
                tile = Main.tile[i, j];
                if (tile.frameY < 132)
                {
                    goto IL_103b;
                }
            }
        }
        goto IL_16e6;
        IL_0978:
        tile = Main.tile[i, j];
        if (tile.frameY >= 132)
        {
            tile = Main.tile[i, j];
            if (tile.frameY <= 176)
            {
                tile = Main.tile[i, j];
                if (tile.frameX != 0)
                {
                    tile = Main.tile[i, j];
                    if (tile.frameX != 66)
                    {
                        tile = Main.tile[i, j];
                        if (tile.frameX != 88)
{
                            goto IL_0dbd;
                        }
                    }
                }
                if (num4 != 2)
                {
                    KillTile(i, j);
                }
                if (num2 != type && num3 != type)
                {
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 0)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 0;
                        tile = Main.tile[i, j];
                        tile.frameY = 0;
                    }
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 1)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 0;
                        tile = Main.tile[i, j];
                        tile.frameY = 22;
                    }
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 2)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 0;
                        tile = Main.tile[i, j];
                        tile.frameY = 44;
                    }
                }
                else if (num2 != type)
                {
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 0)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 0;
                        tile = Main.tile[i, j];
                        tile.frameY = 132;
                    }
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 1)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 0;
                        tile = Main.tile[i, j];
                        tile.frameY = 154;
                    }
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 2)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 0;
                        tile = Main.tile[i, j];
                        tile.frameY = 176;
                    }
                }
                else if (num3 != type)
                {
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 0)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 66;
                        tile = Main.tile[i, j];
                        tile.frameY = 132;
                    }
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 1)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 66;
                        tile = Main.tile[i, j];
                        tile.frameY = 154;
                    }
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 2)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 66;
                        tile = Main.tile[i, j];
                        tile.frameY = 176;
                    }
                }
                else
                {
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 0)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 88;
                        tile = Main.tile[i, j];
                        tile.frameY = 132;
                    }
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 1)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 88;
                        tile = Main.tile[i, j];
                        tile.frameY = 154;
                    }
                    tile = Main.tile[i, j];
                    if (tile.frameNumber() == 2)
                    {
                        tile = Main.tile[i, j];
                        tile.frameX = 88;
                        tile = Main.tile[i, j];
                        tile.frameY = 176;
                    }
                }
            }
        }
        goto IL_0dbd;
        IL_0dbd:
        tile = Main.tile[i, j];
        if (tile.frameX != 66)
        {
            goto IL_0e29;
        }
        tile = Main.tile[i, j];
        if (tile.frameY != 0)
        {
            tile = Main.tile[i, j];
            if (tile.frameY != 22)
            {
                tile = Main.tile[i, j];
                if (tile.frameY != 44)
                {
                    goto IL_0e29;
                }
            }
        }
        goto IL_0e9a;
        IL_0e9a:
        if (num3 != type)
        {
            KillTile(i, j);
        }
        goto IL_16e6;
        IL_16e6:
        tile = Main.tile[i, j];
        if (tile.frameX != frameX)
        {
            tile = Main.tile[i, j];
            if (tile.frameY != frameY && frameX >= 0 && frameY >= 0)
            {
                TileFrame(i - 1, j);
                TileFrame(i + 1, j);
                TileFrame(i, j - 1);
                TileFrame(i, j + 1);
            }
        }
        return;
        IL_0eb1:
        tile = Main.tile[i, j];
        if (tile.frameX != 88)
        {
            goto IL_0f1f;
        }
        tile = Main.tile[i, j];
        if (tile.frameY != 66)
        {
            tile = Main.tile[i, j];
            if (tile.frameY != 88)
            {
                tile = Main.tile[i, j];
                if (tile.frameY != 110)
                {
                    goto IL_0f1f;
                }
            }
        }
        goto IL_0f90;
        IL_03be:
        tile = Main.tile[i, j];
        if (tile.frameX >= 22)
        {
            tile = Main.tile[i, j];
            if (tile.frameX <= 44)
            {
                tile = Main.tile[i, j];
                if (tile.frameY >= 132)
                {
                    tile = Main.tile[i, j];
                    if (tile.frameY <= 176)
                    {
                        if (num4 != 2)
{
                            KillTile(i, j);
                        }
                        else
{
                            tile = Main.tile[i, j];
                            if (tile.frameX != 22 || num2 != type)
{
                                tile = Main.tile[i, j];
                                if (tile.frameX != 44 || num3 != type)
{
                                    KillTile(i, j);
                                }
                            }
                        }
                        goto IL_0978;
                    }
                }
            }
        }
        tile = Main.tile[i, j];
        if (tile.frameX == 88)
        {
            tile = Main.tile[i, j];
            if (tile.frameY >= 0)
            {
                tile = Main.tile[i, j];
                if (tile.frameY <= 44)
                {
                    goto IL_05e9;
                }
            }
        }
        tile = Main.tile[i, j];
        if (tile.frameX == 66)
        {
            tile = Main.tile[i, j];
            if (tile.frameY >= 66)
            {
                tile = Main.tile[i, j];
                if (tile.frameY <= 130)
                {
                    goto IL_05e9;
                }
            }
        }
        tile = Main.tile[i, j];
        if (tile.frameX == 110)
        {
            tile = Main.tile[i, j];
            if (tile.frameY >= 66)
            {
                tile = Main.tile[i, j];
                if (tile.frameY <= 110)
                {
                    goto IL_05e9;
                }
            }
        }
        tile = Main.tile[i, j];
        if (tile.frameX == 132)
        {
            tile = Main.tile[i, j];
            if (tile.frameY >= 0)
            {
                tile = Main.tile[i, j];
                if (tile.frameY <= 176)
                {
                    goto IL_05e9;
                }
            }
        }
        goto IL_0978;
    }
References Terraria.Tile.active(), Terraria.ModLoader.TileLoader.CanGrowModTree(), Terraria.Tile.frameNumber(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Main.tile, and Terraria.Tile.type.