TModLoader: Terraria.WorldGen.PlaceWire
PlaceWire()
static bool Terraria.WorldGen.PlaceWire (int i, int j) inline static
Definition at line 52249 of file WorldGen.cs.
    {
        if (!Main.tile[i, j].wire())
        {
            SoundEngine.PlaySound(0, i * 16, j * 16);
            Main.tile[i, j].wire(wire: true);
            return true;
        }
        return false;
    }
References Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.tile.
Referenced by Terraria.MessageBuffer.GetData(), Terraria.Player.ItemCheck_UseWiringTools(), Terraria.Wiring.MassWireOperationStep(), and Terraria.WorldBuilding.WorldUtils.WireLine().