TModLoader: Terraria.WorldGen.PlantCheck
PlantCheck()
static void Terraria.WorldGen.PlantCheck (int x, int y) inline static
    {
        x = Utils.Clamp(x, 1, Main.maxTilesX - 2);
        y = Utils.Clamp(y, 1, Main.maxTilesY - 2);
        for (int i = x - 1; i <= x + 1; i++)
        {
            for (int j = y - 1; j <= y + 1; j++)
            {
                if (Main.tile[i, j] == null)
                {
                    return;
                }
            }
        }
        int num = -1;
        Tile tile = Main.tile[x, y];
        int num2 = tile.type;
        _ = Main.maxTilesX;
        if (y + 1 >= Main.maxTilesY)
        {
            num = num2;
        }
        if (x - 1 >= 0 && Main.tile[x - 1, y] != null)
        {
            tile = Main.tile[x - 1, y];
            if (tile.nactive())
            {
                tile = Main.tile[x - 1, y];
                _ = ref tile.type;
            }
        }
        if (x + 1 < Main.maxTilesX && Main.tile[x + 1, y] != null)
        {
            tile = Main.tile[x + 1, y];
            if (tile.nactive())
            {
                tile = Main.tile[x + 1, y];
                _ = ref tile.type;
            }
        }
        if (y - 1 >= 0 && Main.tile[x, y - 1] != null)
        {
            tile = Main.tile[x, y - 1];
            if (tile.nactive())
            {
                tile = Main.tile[x, y - 1];
                _ = ref tile.type;
            }
        }
        if (y + 1 < Main.maxTilesY && Main.tile[x, y + 1] != null)
        {
            tile = Main.tile[x, y + 1];
            if (tile.nactive())
            {
                tile = Main.tile[x, y + 1];
                if (!tile.halfBrick())
                {
                    tile = Main.tile[x, y + 1];
                    if (tile.slope() == 0)
                    {
                        tile = Main.tile[x, y + 1];
                        num = tile.type;
                    }
                }
            }
        }
        if (x - 1 >= 0 && y - 1 >= 0 && Main.tile[x - 1, y - 1] != null)
        {
            tile = Main.tile[x - 1, y - 1];
            if (tile.nactive())
            {
                tile = Main.tile[x - 1, y - 1];
                _ = ref tile.type;
            }
        }
        if (x + 1 < Main.maxTilesX && y - 1 >= 0 && Main.tile[x + 1, y - 1] != null)
        {
            tile = Main.tile[x + 1, y - 1];
            if (tile.nactive())
            {
                tile = Main.tile[x + 1, y - 1];
                _ = ref tile.type;
            }
        }
        if (x - 1 >= 0 && y + 1 < Main.maxTilesY && Main.tile[x - 1, y + 1] != null)
        {
            tile = Main.tile[x - 1, y + 1];
            if (tile.nactive())
            {
                tile = Main.tile[x - 1, y + 1];
                _ = ref tile.type;
            }
        }
        if (x + 1 < Main.maxTilesX && y + 1 < Main.maxTilesY && Main.tile[x + 1, y + 1] != null)
        {
            tile = Main.tile[x + 1, y + 1];
            if (tile.nactive())
            {
                tile = Main.tile[x + 1, y + 1];
                _ = ref tile.type;
            }
        }
        if ((num2 != 3 || num == 2 || num == 477 || num == 78 || num == 380 || num == 579) && (num2 != 73 || num == 2 || num == 477 || num == 78 || num == 380 || num == 579) && (num2 != 24 || num == 23 || num == 661) && (num2 != 61 || num == 60) && (num2 != 74 || num == 60) && (num2 != 71 || num == 70) && (num2 != 110 || num == 109 || num == 492) && (num2 != 113 || num == 109 || num == 492) && (num2 != 201 || num == 199 || num == 662) && (num2 != 637 || num == 633))
        {
            return;
        }
        bool flag = false;
        if (num2 == 3 || num2 == 110 || num2 == 24)
        {
            tile = Main.tile[x, y];
            flag = tile.frameX == 144;
        }
        if (num2 == 201)
        {
            tile = Main.tile[x, y];
            flag = tile.frameX == 270;
        }
        if ((num2 == 3 || num2 == 73) && num != 2 && num != 477)
        {
            tile = Main.tile[x, y];
            if (tile.frameX >= 162)
            {
                tile = Main.tile[x, y];
                tile.frameX = 126;
            }
        }
        if (num2 == 74 && num != 60)
        {
            tile = Main.tile[x, y];
            if (tile.frameX >= 162)
            {
                tile = Main.tile[x, y];
                tile.frameX = 126;
            }
        }
        switch (num)
        {
        case 23:
        case 661:
            num2 = 24;
            tile = Main.tile[x, y];
            if (tile.frameX >= 162)
            {
                tile = Main.tile[x, y];
                tile.frameX = 126;
            }
            break;
        case 2:
        case 477:
            num2 = ((num2 != 113) ? 3 : 73);
            break;
        case 109:
        case 492:
            num2 = ((num2 != 73) ? 110 : 113);
            break;
        case 199:
        case 662:
            num2 = 201;
            break;
        case 60:
            num2 = 61;
            while (true)
            {
                tile = Main.tile[x, y];
                if (tile.frameX > 126)
                {
                    tile = Main.tile[x, y];
                    tile.frameX -= 126;
                    continue;
                }
                break;
            }
            break;
        case 70:
            num2 = 71;
            while (true)
            {
                tile = Main.tile[x, y];
                if (tile.frameX <= 72)
                {
                    break;
                }
                tile = Main.tile[x, y];
                tile.frameX -= 72;
            }
            break;
        }
        int num3 = num2;
        tile = Main.tile[x, y];
        if (num3 != tile.type)
        {
            tile = Main.tile[x, y];
            tile.type = (ushort)num2;
            if (flag)
            {
                tile = Main.tile[x, y];
                tile.frameX = 144;
                if (num2 == 201)
                {
                    tile = Main.tile[x, y];
                    tile.frameX = 270;
                }
            }
        }
        else
        {
            KillTile(x, y);
        }
    }
References Terraria.Tile.frameX, Terraria.Tile.halfBrick(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Tile.slope(), Terraria.Main.tile, and Terraria.Tile.type.