TModLoader: Terraria.WorldGen.Check2x2Style
Check2x2Style()
static void Terraria.WorldGen.Check2x2Style (int i, int j, int type) inline static
    {
        if (destroyObject)
        {
            return;
        }
        bool flag = false;
        int num = j;
        int num2;
        for (num2 = Main.tile[i, j].frameY / 18; num2 > 1; num2 -= 2)
        {
        }
        num -= num2;
        int num3 = Main.tile[i, j].frameX / 18;
        int num4 = 0;
        while (num3 > 1)
        {
            num3 -= 2;
            num4++;
        }
        num3 = i - num3;
        int num5 = num4 * 36;
        for (int k = num3; k < num3 + 2; k++)
        {
            for (int l = num; l < num + 2; l++)
            {
                if (Main.tile[k, l] == null)
                {
                    Main.tile[k, l] = default(Tile);
                }
                if (!Main.tile[k, l].active() || Main.tile[k, l].type != type || Main.tile[k, l].frameX != (k - num3) * 18 + num5)
                {
                    flag = true;
                }
            }
            if (!SolidTileAllowBottomSlope(k, num + 2))
            {
                flag = true;
            }
            else
            {
                if (type != 254)
                {
                    continue;
                }
                Tile tile = Main.tile[k, num + 2];
                if (tile != null && tile.active() && tile.type >= 0 && tile.type < TileID.Count)
                {
                    ushort type2 = tile.type;
                    if (type2 != 2 && type2 != 109 && type2 != 477 && type2 != 492)
                    {
                        flag = true;
                    }
                }
            }
        }
        if (!flag)
        {
            return;
        }
        int frameX = Main.tile[i, j].frameX;
        destroyObject = true;
        bool drop = TileLoader.Drop(i, j, type);
        for (int m = num3; m < num3 + 2; m++)
        {
            for (int n = num; n < num + 2; n++)
            {
                if (Main.tile[m, n] == null)
                {
                    Main.tile[m, n] = default(Tile);
                }
                if (Main.tile[m, n].type == type && Main.tile[m, n].active())
                {
                    KillTile(m, n);
                }
            }
        }
        using (new Item.DisableNewItemMethod(!drop))
        {
            switch (type)
            {
            case 254:
                if (frameX < 72)
                {
                    break;
                }
                if (frameX < 108)
                {
                    if (genRand.Next(2) == 0)
                    {
                        Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1725, genRand.Next(1, 3));
                    }
                    break;
                }
                if (frameX < 144)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1725, genRand.Next(2, 6));
                    break;
                }
                Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1725, genRand.Next(5, 11));
                if (Main.halloween && genRand.Next(200) == 0)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1799);
                }
                break;
            case 457:
                Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3749);
                break;
            case 96:
                if (num4 == 0)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 345);
                }
                if (num4 == 1)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1791);
                }
                break;
            case 441:
            {
                int num7 = -1;
                switch (num4)
                {
                case 0:
                    num7 = 3665;
                    break;
                case 1:
                    num7 = 3666;
                    break;
                case 3:
                    num7 = 3667;
                    break;
                case 7:
                    num7 = 3668;
                    break;
                case 8:
                    num7 = 3669;
                    break;
                case 9:
                    num7 = 3670;
                    break;
                case 10:
                    num7 = 3671;
                    break;
                case 11:
                    num7 = 3672;
                    break;
                case 12:
                    num7 = 3673;
                    break;
                case 13:
                    num7 = 3674;
                    break;
                case 14:
                    num7 = 3675;
                    break;
                case 15:
                    num7 = 3676;
                    break;
                case 16:
                    num7 = 3677;
                    break;
                case 17:
                    num7 = 3678;
                    break;
                case 18:
                    num7 = 3679;
                    break;
                case 19:
                    num7 = 3680;
                    break;
                case 20:
                    num7 = 3681;
                    break;
                case 21:
                    num7 = 3682;
                    break;
                case 22:
                    num7 = 3683;
                    break;
                case 28:
                    num7 = 3684;
                    break;
                case 29:
                    num7 = 3685;
                    break;
                case 30:
                    num7 = 3686;
                    break;
                case 31:
                    num7 = 3687;
                    break;
                case 32:
                    num7 = 3688;
                    break;
                case 33:
                    num7 = 3689;
                    break;
                case 34:
                    num7 = 3690;
                    break;
                case 35:
                    num7 = 3691;
                    break;
                case 37:
                    num7 = 3692;
                    break;
                case 39:
                    num7 = 3693;
                    break;
                case 41:
                    num7 = 3694;
                    break;
                case 42:
                    num7 = 3695;
                    break;
                case 43:
                    num7 = 3696;
                    break;
                case 44:
                    num7 = 3697;
                    break;
                case 45:
                    num7 = 3698;
                    break;
                case 46:
                    num7 = 3699;
                    break;
                case 47:
                    num7 = 3700;
                    break;
                case 48:
                    num7 = 3701;
                    break;
                case 49:
                    num7 = 3702;
                    break;
                case 50:
                    num7 = 3703;
                    break;
                case 51:
                    num7 = 3704;
                    break;
                }
                if (num7 != -1)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, num7);
                }
                break;
            }
            case 468:
            {
                int num6 = -1;
                switch (num4)
                {
                case 0:
                    num6 = 3886;
                    break;
                case 1:
                    num6 = 3887;
                    break;
                case 2:
                    num6 = 3950;
                    break;
                case 3:
                    num6 = 3976;
                    break;
                case 4:
                    num6 = -1;
                    break;
                case 5:
                    num6 = 4164;
                    break;
                case 6:
                    num6 = 4185;
                    break;
                case 7:
                    num6 = 4206;
                    break;
                case 8:
                    num6 = 4227;
                    break;
                case 9:
                    num6 = 4266;
                    break;
                case 10:
                    num6 = 4268;
                    break;
                case 11:
                    num6 = 4585;
                    break;
                case 12:
                    num6 = 4713;
                    break;
                case 13:
                    num6 = -1;
                    break;
                case 14:
                    num6 = 5167;
                    break;
                case 15:
                    num6 = 5188;
                    break;
                case 16:
                    num6 = 5209;
                    break;
                }
                if (num6 != -1)
                {
                    Item.NewItem(GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, num6);
                }
                break;
            }
            }
            destroyObject = false;
            for (int num8 = num3 - 1; num8 < num3 + 3; num8++)
            {
                for (int num9 = num - 1; num9 < num + 3; num9++)
                {
                    TileFrame(num8, num9);
                }
            }
        }
    }
References Terraria.Tile.active(), Terraria.ID.TileID.Count, Terraria.ModLoader.TileLoader.Drop(), Terraria.Main.halloween, Terraria.Item.NewItem(), Terraria.Main.tile, and Terraria.Tile.type.