TModLoader: Terraria.WorldGen.LaunchRocketSmall
LaunchRocketSmall()
static void Terraria.WorldGen.LaunchRocketSmall (int x, int y, bool fromWiring) inline static
Definition at line 56406 of file WorldGen.cs.
    {
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        if (Main.tile[x, y].frameX == 18)
        {
            x--;
        }
        if (Main.tile[x, y].frameY == 18)
        {
            y--;
        }
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)(x * 16 + 16), (float)(y * 16));
        int type = 415 + Main.rand.Next(4);
        int damage = 0;
        int num = 0;
        int num2 = Projectile.NewProjectile(GetProjectileSource_PlayerOrWires(x, y, fromWiring, Main.LocalPlayer), vector.X, vector.Y + 2f, 0f, -8f, type, damage, num, Main.myPlayer);
        Main.projectile[num2].originatedFromActivableTile = true;
    }
References Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Projectile.originatedFromActivableTile, Terraria.Main.projectile, Terraria.Main.rand, and Terraria.Main.tile.
Referenced by Terraria.Wiring.HitWireSingle(), and Terraria.Player.TileInteractionsUse().