TModLoader: Terraria.WorldGen.paintCoatTile
paintCoatTile()
static bool Terraria.WorldGen.paintCoatTile (int x, int y, byte paintCoatId, bool broadcast = false) inline static
Definition at line 36915 of file WorldGen.cs.
    {
        Tile tile = Main.tile[x, y];
        if (tile == null || !tile.active())
        {
            return false;
        }
        List<Color> oldColors = coatingColors(tile, block: true);
        switch (paintCoatId)
        {
        default:
            return false;
        case 0:
            if (!tile.fullbrightBlock() && !tile.invisibleBlock())
            {
                return false;
            }
            tile.fullbrightBlock(fullbrightBlock: false);
            tile.invisibleBlock(invisibleBlock: false);
            SquareTileFrame(x, y, resetFrame: false);
            break;
        case 1:
            if (tile.fullbrightBlock())
            {
                return false;
            }
            tile.fullbrightBlock(fullbrightBlock: true);
            break;
        case 2:
            if (tile.invisibleBlock())
            {
                return false;
            }
            tile.invisibleBlock(invisibleBlock: true);
            SquareTileFrame(x, y, resetFrame: false);
            break;
        }
        if (broadcast)
        {
            NetMessage.SendData(63, -1, -1, null, x, y, (int)paintCoatId, 1f);
        }
        paintCoatEffect(x, y, paintCoatId, oldColors);
        return true;
    }
References Terraria.Tile.active(), Terraria.Tile.fullbrightBlock(), Terraria.Tile.invisibleBlock(), Terraria.NetMessage.SendData(), and Terraria.Main.tile.
Referenced by Terraria.Player.ApplyCoating(), Terraria.MessageBuffer.GetData(), and Terraria.Player.PlaceThing_PaintScrapper_TryScrapping().