TModLoader: Terraria.ModLoader.Core.GlobalLoaderUtils.SetDefaultsBeforeLookupsAreBuilt
SetDefaultsBeforeLookupsAreBuilt() [1/2]
static void Terraria.ModLoader.Core.GlobalLoaderUtils< TGlobal, TEntity >.SetDefaultsBeforeLookupsAreBuilt (TEntity entity, TGlobal[] entityGlobals, Action< TEntity > setModEntityDefaults) inline static private
Definition at line 75 of file GlobalLoaderUtils.cs.
    {
        InstantiationTime[] instTimes = ArrayPool<InstantiationTime>.Shared.Rent(Globals.Length);
        try
        {
            SetDefaultsBeforeLookupsAreBuilt(entity, entityGlobals, setModEntityDefaults, ref instTimes);
            UpdateGlobalTypeData?.Invoke(entity.Type, instTimes.AsSpan().Slice(0, Globals.Length));
        }
        finally
        {
            ArrayPool<InstantiationTime>.Shared.Return(instTimes, clearArray: true);
        }
    }
References Terraria.ModLoader.Core.GlobalLoaderUtils< TGlobal, TEntity >.Globals, Terraria.ModLoader.Core.GlobalLoaderUtils< TGlobal, TEntity >.SetDefaultsBeforeLookupsAreBuilt(), and Terraria.ModLoader.Core.GlobalLoaderUtils< TGlobal, TEntity >.UpdateGlobalTypeData.
Referenced by Terraria.ModLoader.Core.GlobalLoaderUtils< TGlobal, TEntity >.SetDefaults(), and Terraria.ModLoader.Core.GlobalLoaderUtils< TGlobal, TEntity >.SetDefaultsBeforeLookupsAreBuilt().