TModLoader: Terraria.GameContent.Tile_Entities.TEItemFrame.TryPlacing
TryPlacing()
static void Terraria.GameContent.Tile_Entities.TEItemFrame.TryPlacing (int x, int y, Item item, int stack) inline static
    {
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        WorldGen.RangeFrame(x, y, x + 2, y + 2);
        int num = Find(x, y);
        if (num == -1)
        {
            Item.NewItem((IEntitySource)new EntitySource_TileBreak(x, y), new Rectangle(x * 16, y * 16, 16, 16), item, noBroadcast: false, noGrabDelay: false, reverseLookup: false);
            return;
        }
        TEItemFrame tEItemFrame = (TEItemFrame)TileEntity.ByID[num];
        if (tEItemFrame.item.stack > 0)
        {
            tEItemFrame.DropItem();
        }
        tEItemFrame.item = ItemLoader.TransferWithLimit(item, stack);
        NetMessage.SendData(86, -1, -1, null, tEItemFrame.ID, x, y);
    }
References Terraria.GameContent.Tile_Entities.TEItemFrame.TEItemFrame(), Terraria.DataStructures.TileEntity.ByID, Terraria.GameContent.Tile_Entities.TEItemFrame.Find(), Terraria.GameContent.Tile_Entities.TEItemFrame.item, Terraria.Item.NewItem(), Terraria.WorldGen.RangeFrame(), Terraria.NetMessage.SendData(), and Terraria.ModLoader.ItemLoader.TransferWithLimit().
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.GameContent.Tile_Entities.TEItemFrame.PlaceItemInFrame().