TModLoader: Terraria.PopupText.NewText
NewText() [3/3]
static int Terraria.PopupText.NewText (PopupTextContext context, Item newItem, int stack, bool noStack = false, bool longText = false) inline static
Creates a new T:Terraria.PopupText in F:Terraria.Main.popupText at the center of the picked-up newItem .
If a T:Terraria.PopupText already exists with the M:Terraria.Item.AffixName of newItem , that text will instead be modified unless noStack is true.
Parameters
context The T:Terraria.PopupTextContext in which this T:Terraria.PopupText was created.
newItem The T:Terraria.Item to ceate the new text from.
stack The stack of newItem .
noStack If true, always create a new T:Terraria.PopupText instead of modifying an existing one.
longText If true, then this T:Terraria.PopupText will spawn with F:Terraria.PopupText.lifeTime == 5 * 60.
Returns
Also returns -1 if P:Terraria.Item.Name is null.
Definition at line 329 of file PopupText.cs.
    {
        //IL_03ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0409: Unknown result type (might be due to invalid IL or missing references)
        //IL_043c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0451: Unknown result type (might be due to invalid IL or missing references)
        //IL_0456: Unknown result type (might be due to invalid IL or missing references)
        //IL_0475: Unknown result type (might be due to invalid IL or missing references)
        //IL_047a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        //IL_049e: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_033c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0519: Unknown result type (might be due to invalid IL or missing references)
        //IL_051e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0556: Unknown result type (might be due to invalid IL or missing references)
        //IL_055b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_057f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0584: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0206: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0800: Unknown result type (might be due to invalid IL or missing references)
        //IL_0248: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0841: Unknown result type (might be due to invalid IL or missing references)
        //IL_0846: Unknown result type (might be due to invalid IL or missing references)
        //IL_0287: Unknown result type (might be due to invalid IL or missing references)
        //IL_028c: Unknown result type (might be due to invalid IL or missing references)
        //IL_061a: Unknown result type (might be due to invalid IL or missing references)
        //IL_061f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0884: Unknown result type (might be due to invalid IL or missing references)
        //IL_0889: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_063b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0640: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_065f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0664: Unknown result type (might be due to invalid IL or missing references)
        //IL_0682: Unknown result type (might be due to invalid IL or missing references)
        //IL_0687: Unknown result type (might be due to invalid IL or missing references)
        if (!Main.showItemText)
        {
            return -1;
        }
        if (newItem.Name == null || !newItem.active)
        {
            return -1;
        }
        if (Main.netMode == 2)
        {
            return -1;
        }
        bool flag = newItem.type >= 71 && newItem.type <= 74;
        for (int i = 0; i < 20; i++)
        {
            PopupText popupText = Main.popupText[i];
            if (!popupText.active || popupText.notActuallyAnItem || (!(popupText.name == newItem.AffixName()) && (!flag || !popupText.coinText)) || popupText.NoStack || noStack)
            {
                continue;
            }
            string text = newItem.Name + " (" + (popupText.stack + stack) + ")";
            string text2 = newItem.Name;
            if (popupText.stack > 1)
            {
                text2 = text2 + " (" + popupText.stack + ")";
            }
            Vector2 vector = FontAssets.MouseText.Value.MeasureString(text2);
            vector = FontAssets.MouseText.Value.MeasureString(text);
            if (popupText.lifeTime < 0)
            {
                popupText.scale = 1f;
            }
            if (popupText.lifeTime < 60)
            {
                popupText.lifeTime = 60;
            }
            if (flag && popupText.coinText)
            {
                long num = 0L;
                if (newItem.type == 71)
                {
                    num += stack;
                }
                else if (newItem.type == 72)
                {
                    num += 100 * stack;
                }
                else if (newItem.type == 73)
                {
                    num += 10000 * stack;
                }
                else if (newItem.type == 74)
                {
                    num += 1000000 * stack;
                }
                popupText.AddToCoinValue(num);
                text = ValueToName(popupText.coinValue);
                vector = FontAssets.MouseText.Value.MeasureString(text);
                popupText.name = text;
                if (popupText.coinValue >= 1000000)
                {
                    if (popupText.lifeTime < 300)
                    {
                        popupText.lifeTime = 300;
                    }
                    popupText.color = new Color(220, 220, 198);
                }
                else if (popupText.coinValue >= 10000)
                {
                    if (popupText.lifeTime < 240)
                    {
                        popupText.lifeTime = 240;
                    }
                    popupText.color = new Color(224, 201, 92);
                }
                else if (popupText.coinValue >= 100)
                {
                    if (popupText.lifeTime < 180)
                    {
                        popupText.lifeTime = 180;
                    }
                    popupText.color = new Color(181, 192, 193);
                }
                else if (popupText.coinValue >= 1)
                {
                    if (popupText.lifeTime < 120)
                    {
                        popupText.lifeTime = 120;
                    }
                    popupText.color = new Color(246, 138, 96);
                }
            }
            popupText.stack += stack;
            popupText.scale = 0f;
            popupText.rotation = 0f;
            popupText.position.X = newItem.position.X + (float)newItem.width * 0.5f - vector.X * 0.5f;
            popupText.position.Y = newItem.position.Y + (float)newItem.height * 0.25f - vector.Y * 0.5f;
            popupText.velocity.Y = -7f;
            popupText.context = context;
            popupText.npcNetID = 0;
            if (popupText.coinText)
            {
                popupText.stack = 1L;
            }
            return i;
        }
        int num2 = FindNextItemTextSlot();
        if (num2 >= 0)
        {
            string text3 = newItem.AffixName();
            if (stack > 1)
            {
                text3 = text3 + " (" + stack + ")";
            }
            Vector2 vector2 = FontAssets.MouseText.Value.MeasureString(text3);
            PopupText popupText2 = Main.popupText[num2];
            ResetText(popupText2);
            popupText2.active = true;
            popupText2.position.X = newItem.position.X + (float)newItem.width * 0.5f - vector2.X * 0.5f;
            popupText2.position.Y = newItem.position.Y + (float)newItem.height * 0.25f - vector2.Y * 0.5f;
            popupText2.color = Color.White;
            if (newItem.rare == 1)
            {
                popupText2.color = new Color(150, 150, 255);
            }
            else if (newItem.rare == 2)
            {
                popupText2.color = new Color(150, 255, 150);
            }
            else if (newItem.rare == 3)
            {
                popupText2.color = new Color(255, 200, 150);
            }
            else if (newItem.rare == 4)
            {
                popupText2.color = new Color(255, 150, 150);
            }
            else if (newItem.rare == 5)
            {
                popupText2.color = new Color(255, 150, 255);
            }
            else if (newItem.rare == -13)
            {
                popupText2.master = true;
            }
            else if (newItem.rare == -11)
            {
                popupText2.color = new Color(255, 175, 0);
            }
            else if (newItem.rare == -1)
            {
                popupText2.color = new Color(130, 130, 130);
            }
            else if (newItem.rare == 6)
            {
                popupText2.color = new Color(210, 160, 255);
            }
            else if (newItem.rare == 7)
            {
                popupText2.color = new Color(150, 255, 10);
            }
            else if (newItem.rare == 8)
            {
                popupText2.color = new Color(255, 255, 10);
            }
            else if (newItem.rare == 9)
            {
                popupText2.color = new Color(5, 200, 255);
            }
            else if (newItem.rare == 10)
            {
                popupText2.color = new Color(255, 40, 100);
            }
            else if (newItem.rare == 11)
            {
                popupText2.color = new Color(180, 40, 255);
            }
            else if (newItem.rare >= 12)
            {
                popupText2.color = RarityLoader.GetRarity(newItem.rare).RarityColor;
            }
            popupText2.rarity = newItem.rare;
            popupText2.expert = newItem.expert;
            popupText2.master = newItem.master;
            popupText2.name = newItem.AffixName();
            popupText2.stack = stack;
            popupText2.velocity.Y = -7f;
            popupText2.lifeTime = 60;
            popupText2.context = context;
            if (longText)
            {
                popupText2.lifeTime *= 5;
            }
            popupText2.coinValue = 0L;
            popupText2.coinText = newItem.type >= 71 && newItem.type <= 74;
            if (popupText2.coinText)
            {
                long num3 = 0L;
                if (newItem.type == 71)
                {
                    num3 += popupText2.stack;
                }
                else if (newItem.type == 72)
                {
                    num3 += 100 * popupText2.stack;
                }
                else if (newItem.type == 73)
                {
                    num3 += 10000 * popupText2.stack;
                }
                else if (newItem.type == 74)
                {
                    num3 += 1000000 * popupText2.stack;
                }
                popupText2.AddToCoinValue(num3);
                popupText2.ValueToName();
                popupText2.stack = 1L;
                if (popupText2.coinValue >= 1000000)
                {
                    if (popupText2.lifeTime < 300)
                    {
                        popupText2.lifeTime = 300;
                    }
                    popupText2.color = new Color(220, 220, 198);
                }
                else if (popupText2.coinValue >= 10000)
                {
                    if (popupText2.lifeTime < 240)
                    {
                        popupText2.lifeTime = 240;
                    }
                    popupText2.color = new Color(224, 201, 92);
                }
                else if (popupText2.coinValue >= 100)
                {
                    if (popupText2.lifeTime < 180)
                    {
                        popupText2.lifeTime = 180;
                    }
                    popupText2.color = new Color(181, 192, 193);
                }
                else if (popupText2.coinValue >= 1)
                {
                    if (popupText2.lifeTime < 120)
                    {
                        popupText2.lifeTime = 120;
                    }
                    popupText2.color = new Color(246, 138, 96);
                }
            }
        }
        return num2;
    }
References Terraria.PopupText.active, Terraria.PopupText.AddToCoinValue(), Terraria.PopupText.coinText, Terraria.PopupText.coinValue, Terraria.PopupText.context, Terraria.PopupText.FindNextItemTextSlot(), Terraria.ModLoader.RarityLoader.GetRarity(), Terraria.PopupText.lifeTime, Terraria.GameContent.FontAssets.MouseText, Terraria.PopupText.name, Terraria.Main.netMode, Terraria.PopupText.NoStack, Terraria.PopupText.notActuallyAnItem, Terraria.Main.popupText, Terraria.ModLoader.ModRarity.RarityColor, Terraria.PopupText.ResetText(), Terraria.Main.showItemText, Terraria.PopupText.stack, and Terraria.PopupText.ValueToName().