TModLoader: Terraria.ModLoader.UI.UIExpandablePanel.Update
Update()
override void Terraria.ModLoader.UI.UIExpandablePanel.Update (GameTime gameTime) inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 50 of file UIExpandablePanel.cs.
    {
        base.Update(gameTime);
        if (!pendingChanges)
        {
            return;
        }
        pendingChanges = false;
        float newHeight = defaultHeight;
        if (expanded)
        {
            foreach (UIElement item in VisibleWhenExpanded)
            {
                Append(item);
                CalculatedStyle innerDimensions = item.GetInnerDimensions();
                if (innerDimensions.Height > newHeight)
                {
                    newHeight = 30f + innerDimensions.Height + PaddingBottom + PaddingTop;
                }
            }
            expandButton.HoverText = Language.GetTextValue("tModLoader.ModConfigCollapse");
            expandButton.SetImage(ExpandedTexture);
            this.OnExpanded?.Invoke();
        }
        else
        {
            foreach (UIElement item2 in VisibleWhenExpanded)
            {
                RemoveChild(item2);
            }
            this.OnCollapsed?.Invoke();
            expandButton.HoverText = Language.GetTextValue("tModLoader.ModConfigExpand");
            expandButton.SetImage(CollapsedTexture);
        }
        Height.Set(newHeight, 0f);
    }
References Terraria.UI.UIElement.Append(), Terraria.ModLoader.UI.UIExpandablePanel.CollapsedTexture, Terraria.ModLoader.UI.UIExpandablePanel.defaultHeight, Terraria.ModLoader.UI.UIExpandablePanel.expandButton, Terraria.ModLoader.UI.UIExpandablePanel.expanded, Terraria.ModLoader.UI.UIExpandablePanel.ExpandedTexture, Terraria.UI.UIElement.GetInnerDimensions(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.Height, Terraria.UI.UIElement.PaddingBottom, Terraria.UI.UIElement.PaddingTop, Terraria.ModLoader.UI.UIExpandablePanel.pendingChanges, Terraria.UI.UIElement.RemoveChild(), Terraria.UI.StyleDimension.Set(), Terraria.GameContent.UI.Elements.UIImage.SetImage(), and Terraria.ModLoader.UI.UIExpandablePanel.VisibleWhenExpanded.