TModLoader: Terraria.ModLoader.UI.UIExpandablePanel.UIExpandablePanel
UIExpandablePanel()
Terraria.ModLoader.UI.UIExpandablePanel.UIExpandablePanel () inline
    {
        Width.Set(0f, 1f);
        Height.Set(defaultHeight, 0f);
        SetPadding(6f);
        expandButton = new UIHoverImage(CollapsedTexture, Language.GetTextValue("tModLoader.ModConfigExpand"));
        expandButton.Top.Set(3f, 0f);
        expandButton.Left.Set(-25f, 1f);
        expandButton.OnLeftClick += delegate
        {
            expanded = !expanded;
            pendingChanges = true;
        };
        Append(expandButton);
    }
References Terraria.UI.UIElement.Append(), Terraria.ModLoader.UI.UIExpandablePanel.CollapsedTexture, Terraria.ModLoader.UI.UIExpandablePanel.defaultHeight, Terraria.ModLoader.UI.UIExpandablePanel.expandButton, Terraria.ModLoader.UI.UIExpandablePanel.expanded, Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.ModLoader.UI.UIExpandablePanel.pendingChanges, Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.Top, and Terraria.UI.UIElement.Width.