TModLoader: Terraria.WorldGen.Spread.Spider
Spider()
static void Terraria.WorldGen.Spread.Spider (int x, int y) inline static
        {
            //IL_0023: Unknown result type (might be due to invalid IL or missing references)
            //IL_004c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0051: Unknown result type (might be due to invalid IL or missing references)
            //IL_0053: Unknown result type (might be due to invalid IL or missing references)
            //IL_005a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0078: Unknown result type (might be due to invalid IL or missing references)
            //IL_0081: Unknown result type (might be due to invalid IL or missing references)
            //IL_008e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0095: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
            //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
            //IL_006a: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
            //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
            //IL_029b: Unknown result type (might be due to invalid IL or missing references)
            //IL_02a4: Unknown result type (might be due to invalid IL or missing references)
            //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
            //IL_0124: Unknown result type (might be due to invalid IL or missing references)
            //IL_012b: Unknown result type (might be due to invalid IL or missing references)
            //IL_02c4: Unknown result type (might be due to invalid IL or missing references)
            //IL_02cd: Unknown result type (might be due to invalid IL or missing references)
            //IL_02da: Unknown result type (might be due to invalid IL or missing references)
            //IL_02bb: Unknown result type (might be due to invalid IL or missing references)
            //IL_02ed: Unknown result type (might be due to invalid IL or missing references)
            //IL_02f4: Unknown result type (might be due to invalid IL or missing references)
            //IL_0303: Unknown result type (might be due to invalid IL or missing references)
            //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
            //IL_01a7: Unknown result type (might be due to invalid IL or missing references)
            //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
            //IL_0316: Unknown result type (might be due to invalid IL or missing references)
            //IL_031d: Unknown result type (might be due to invalid IL or missing references)
            //IL_032c: Unknown result type (might be due to invalid IL or missing references)
            //IL_030d: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e5: Unknown result type (might be due to invalid IL or missing references)
            //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
            //IL_0177: Unknown result type (might be due to invalid IL or missing references)
            //IL_017e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0157: Unknown result type (might be due to invalid IL or missing references)
            //IL_015e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0336: Unknown result type (might be due to invalid IL or missing references)
            //IL_0200: Unknown result type (might be due to invalid IL or missing references)
            //IL_0207: Unknown result type (might be due to invalid IL or missing references)
            //IL_01cc: Unknown result type (might be due to invalid IL or missing references)
            //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
            //IL_0240: Unknown result type (might be due to invalid IL or missing references)
            //IL_0247: Unknown result type (might be due to invalid IL or missing references)
            //IL_0271: Unknown result type (might be due to invalid IL or missing references)
            //IL_0278: Unknown result type (might be due to invalid IL or missing references)
            if (!InWorld(x, y))
            {
                return;
            }
            byte wall = 62;
            List<Point> list = new List<Point>();
            List<Point> list2 = new List<Point>();
            HashSet<Point> hashSet = new HashSet<Point>();
            list2.Add(new Point(x, y));
            Point item2 = default(Point);
            while (list2.Count > 0)
            {
                list.Clear();
                list.AddRange(list2);
                list2.Clear();
                while (list.Count > 0)
                {
                    Point item = list[0];
                    if (!InWorld(item.X, item.Y, 1))
                    {
                        list.Remove(item);
                        continue;
                    }
                    hashSet.Add(item);
                    list.Remove(item);
                    Tile tile = Main.tile[item.X, item.Y];
                    if (SolidTile(item.X, item.Y) || tile.wall != 0)
                    {
                        if (tile.active() && tile.wall == 0)
{
                            tile.wall = wall;
                        }
                        continue;
                    }
                    tile.wall = wall;
                    SquareWallFrame(item.X, item.Y);
                    if (!tile.active())
                    {
                        tile.liquid = 0;
                        tile.lava(lava: false);
                        if (SolidTile(item.X, item.Y + 1) && genRand.Next(3) == 0)
{
                            if (genRand.Next(15) == 0)
{
                                AddBuriedChest(item.X, item.Y, 939, notNearOtherChests: true, 15, trySlope: false, 0);
                            }
                            else
{
                                PlacePot(item.X, item.Y, 28, genRand.Next(19, 21));
                            }
                        }
                        if (!tile.active())
{
                            if (SolidTile(item.X, item.Y - 1) && genRand.Next(3) == 0)
{
                                PlaceTight(item.X, item.Y, spiders: true);
                            }
                            else if (SolidTile(item.X, item.Y + 1))
{
                                PlaceTile(item.X, item.Y, 187, mute: true, forced: false, -1, 9 + genRand.Next(5));
                                if (genRand.Next(3) == 0)
{
                                    if (!tile.active())
{
                                        PlaceSmallPile(item.X, item.Y, 34 + genRand.Next(4), 1, 185);
                                    }
                                    if (!tile.active())
{
                                        PlaceSmallPile(item.X, item.Y, 48 + genRand.Next(6), 0, 185);
                                    }
                                }
                            }
                        }
                    }
                    ((Point)(ref item2))._002Ector(item.X - 1, item.Y);
                    if (!hashSet.Contains(item2))
                    {
                        list2.Add(item2);
                    }
                    ((Point)(ref item2))._002Ector(item.X + 1, item.Y);
                    if (!hashSet.Contains(item2))
                    {
                        list2.Add(item2);
                    }
                    ((Point)(ref item2))._002Ector(item.X, item.Y - 1);
                    if (!hashSet.Contains(item2))
                    {
                        list2.Add(item2);
                    }
                    ((Point)(ref item2))._002Ector(item.X, item.Y + 1);
                    if (!hashSet.Contains(item2))
                    {
                        list2.Add(item2);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.AddBuriedChest(), Terraria.WorldGen.genRand, Terraria.WorldGen.InWorld(), Terraria.Tile.lava(), Terraria.WorldGen.PlacePot(), Terraria.WorldGen.PlaceSmallPile(), Terraria.WorldGen.PlaceTight(), Terraria.WorldGen.PlaceTile(), Terraria.Enums.SolidTile, Terraria.WorldGen.SquareWallFrame(), Terraria.Main.tile, and Terraria.Tile.wall.