TModLoader: Terraria.WorldGen.Spread.Gem
Gem()
static void Terraria.WorldGen.Spread.Gem (int x, int y) inline static
        {
            //IL_0020: Unknown result type (might be due to invalid IL or missing references)
            //IL_0049: Unknown result type (might be due to invalid IL or missing references)
            //IL_004e: Unknown result type (might be due to invalid IL or missing references)
            //IL_004f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0055: Unknown result type (might be due to invalid IL or missing references)
            //IL_0071: Unknown result type (might be due to invalid IL or missing references)
            //IL_0079: Unknown result type (might be due to invalid IL or missing references)
            //IL_0085: Unknown result type (might be due to invalid IL or missing references)
            //IL_008b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0098: Unknown result type (might be due to invalid IL or missing references)
            //IL_009e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0064: Unknown result type (might be due to invalid IL or missing references)
            //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
            //IL_0209: Unknown result type (might be due to invalid IL or missing references)
            //IL_0211: Unknown result type (might be due to invalid IL or missing references)
            //IL_021d: Unknown result type (might be due to invalid IL or missing references)
            //IL_011c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0124: Unknown result type (might be due to invalid IL or missing references)
            //IL_0230: Unknown result type (might be due to invalid IL or missing references)
            //IL_0238: Unknown result type (might be due to invalid IL or missing references)
            //IL_0244: Unknown result type (might be due to invalid IL or missing references)
            //IL_0227: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
            //IL_01ee: Unknown result type (might be due to invalid IL or missing references)
            //IL_0152: Unknown result type (might be due to invalid IL or missing references)
            //IL_0158: Unknown result type (might be due to invalid IL or missing references)
            //IL_0257: Unknown result type (might be due to invalid IL or missing references)
            //IL_025d: Unknown result type (might be due to invalid IL or missing references)
            //IL_026b: Unknown result type (might be due to invalid IL or missing references)
            //IL_024e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0188: Unknown result type (might be due to invalid IL or missing references)
            //IL_018e: Unknown result type (might be due to invalid IL or missing references)
            //IL_027e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0284: Unknown result type (might be due to invalid IL or missing references)
            //IL_0292: Unknown result type (might be due to invalid IL or missing references)
            //IL_0275: Unknown result type (might be due to invalid IL or missing references)
            //IL_029c: Unknown result type (might be due to invalid IL or missing references)
            if (!InWorld(x, y))
            {
                return;
            }
            List<Point> list = new List<Point>();
            List<Point> list2 = new List<Point>();
            HashSet<Point> hashSet = new HashSet<Point>();
            list2.Add(new Point(x, y));
            Point item2 = default(Point);
            while (list2.Count > 0)
            {
                list.Clear();
                list.AddRange(list2);
                list2.Clear();
                while (list.Count > 0)
                {
                    Point item = list[0];
                    if (!InWorld(item.X, item.Y, 1))
                    {
                        list.Remove(item);
                        continue;
                    }
                    hashSet.Add(item);
                    list.Remove(item);
                    Tile tile = Main.tile[item.X, item.Y];
                    if (SolidTile(item.X, item.Y) || tile.wall != 0)
                    {
                        if (tile.active())
{
                            if (Gemmable(tile.type))
{
                                tile.type = randGemTile();
                            }
                            Tile tile2 = Main.tile[item.X - 1, item.Y];
                            if (Gemmable(tile2.type))
{
                                tile2.type = randGemTile();
                            }
                            tile2 = Main.tile[item.X + 1, item.Y];
                            if (Gemmable(tile2.type))
{
                                tile2.type = randGemTile();
                            }
                            tile2 = Main.tile[item.X, item.Y - 1];
                            if (Gemmable(tile2.type))
{
                                tile2.type = randGemTile();
                            }
                            tile2 = Main.tile[item.X, item.Y + 1];
                            if (Gemmable(tile2.type))
{
                                tile2.type = randGemTile();
                            }
                        }
                    }
                    else
                    {
                        tile.wall = (ushort)(48 + randGem());
                        if (!tile.active() && genRand.Next(2) == 0)
{
                            PlaceTile(item.X, item.Y, 178, mute: true, forced: false, -1, randGem());
                        }
                        ((Point)(ref item2))._002Ector(item.X - 1, item.Y);
                        if (!hashSet.Contains(item2))
{
                            list2.Add(item2);
                        }
                        ((Point)(ref item2))._002Ector(item.X + 1, item.Y);
                        if (!hashSet.Contains(item2))
{
                            list2.Add(item2);
                        }
                        ((Point)(ref item2))._002Ector(item.X, item.Y - 1);
                        if (!hashSet.Contains(item2))
{
                            list2.Add(item2);
                        }
                        ((Point)(ref item2))._002Ector(item.X, item.Y + 1);
                        if (!hashSet.Contains(item2))
{
                            list2.Add(item2);
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.Spread.Gemmable(), Terraria.WorldGen.genRand, Terraria.WorldGen.InWorld(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.randGem(), Terraria.WorldGen.randGemTile(), Terraria.Enums.SolidTile, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.gemCave().