TModLoader: Terraria.GameContent.UI.Elements.UIDifficultyButton.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIDifficultyButton.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
    {
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0102: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        if (_hovered)
        {
            if (!_soundedHover)
            {
                SoundEngine.PlaySound(12);
            }
            _soundedHover = true;
        }
        else
        {
            _soundedHover = false;
        }
        CalculatedStyle dimensions = GetDimensions();
        int num = 7;
        if (dimensions.Height < 30f)
        {
            num = 5;
        }
        int num2 = 10;
        int num3 = 10;
        bool num4 = _difficulty == _player.difficulty;
        Utils.DrawSplicedPanel(spriteBatch, _BasePanelTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, num2, num2, num3, num3, Color.Lerp(Color.Black, _color, 0.8f) * 0.5f);
        if (num4)
        {
            Utils.DrawSplicedPanel(spriteBatch, _BasePanelTexture.Value, (int)dimensions.X + num, (int)dimensions.Y + num - 2, (int)dimensions.Width - num * 2, (int)dimensions.Height - num * 2, num2, num2, num3, num3, Color.Lerp(_color, Color.White, 0.7f) * 0.5f);
        }
        if (_hovered)
        {
            Utils.DrawSplicedPanel(spriteBatch, _hoveredBorderTexture.Value, (int)dimensions.X, (int)dimensions.Y, (int)dimensions.Width, (int)dimensions.Height, num2, num2, num3, num3, Color.White);
        }
    }
References Terraria.GameContent.UI.Elements.UIDifficultyButton._BasePanelTexture, Terraria.GameContent.UI.Elements.UIDifficultyButton._color, Terraria.GameContent.UI.Elements.UIDifficultyButton._difficulty, Terraria.GameContent.UI.Elements.UIDifficultyButton._hovered, Terraria.GameContent.UI.Elements.UIDifficultyButton._hoveredBorderTexture, Terraria.GameContent.UI.Elements.UIDifficultyButton._player, Terraria.GameContent.UI.Elements.UIDifficultyButton._soundedHover, Terraria.Utils.DrawSplicedPanel(), Terraria.UI.UIElement.GetDimensions(), and Terraria.Audio.SoundEngine.PlaySound().