TModLoader: Terraria.WorldBuilding.TileFont.VLineLabel
VLineLabel()
static void Terraria.WorldBuilding.TileFont.VLineLabel (Point start, int height, string text, DrawMode mode, bool bottomText = false) inline static
Definition at line 405 of file TileFont.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        Point point = MeasureString(text);
        for (int i = start.Y; i < start.Y + height; i++)
        {
            Main.tile[start.X, i].ResetToType(mode.ForegroundTile);
            WorldGen.TileFrame(start.X, i);
        }
        DrawString(new Point(start.X - point.X / 2, bottomText ? (start.Y + height + 1) : (start.Y - point.Y - 1)), text, mode);
    }
References Terraria.WorldBuilding.TileFont.DrawString(), Terraria.WorldBuilding.TileFont.MeasureString(), Terraria.Main.tile, and Terraria.WorldGen.TileFrame().