TModLoader: Terraria.Utilities.FileUtilities.ReadAllBytes
ReadAllBytes()
static byte[] Terraria.Utilities.FileUtilities.ReadAllBytes (string path, bool cloud) inline static
Definition at line 83 of file FileUtilities.cs.
    {
        if (cloud && SocialAPI.Cloud != null)
        {
            return SocialAPI.Cloud.Read(path);
        }
        return File.ReadAllBytes(path);
    }
References Terraria.Social.SocialAPI.Cloud, Terraria.Utilities.FileUtilities.path, and Terraria.Social.Steam.CloudSocialModule.Read().
Referenced by Terraria.ModLoader.BackupIO.AddZipEntry(), Terraria.Utilities.FileUtilities.CopyToLocal(), Terraria.IO.WorldFile.InternalSaveWorld(), Terraria.IO.FavoritesFile.Load(), Terraria.Map.WorldMap.Load(), Terraria.Achievements.AchievementManager.Load(), Terraria.ModLoader.IO.WorldIO.Load(), Terraria.Player.LoadPlayer(), Terraria.IO.WorldFile.LoadWorld(), Terraria.Utilities.FileUtilities.MoveToCloud(), Terraria.Utilities.FileUtilities.MoveToLocal(), Terraria.ModLoader.IO.MapIO.ReadModFile(), Terraria.ModLoader.IO.PlayerIO.TryLoadData(), Terraria.ModLoader.BackupIO.Player.WriteCloudFiles(), and Terraria.Utilities.FileUtilities.WriteTagCompound().