TModLoader: Terraria.Utilities.FileUtilities.CopyFolderEXT
CopyFolderEXT()
static void Terraria.Utilities.FileUtilities.CopyFolderEXT (string sourcePath, string destinationPath, bool isCloud = false, Regex excludeFilter = null, bool overwriteAlways = false, bool overwriteOld = false) inline static
Definition at line 245 of file FileUtilities.cs.
    {
        Directory.CreateDirectory(destinationPath);
        string[] directories = Directory.GetDirectories(sourcePath, "*", SearchOption.AllDirectories);
        for (int i = 0; i < directories.Length; i++)
        {
            string relativePath2 = ConvertToRelativePath(sourcePath, directories[i]);
            if (excludeFilter == null || !excludeFilter.IsMatch(relativePath2))
            {
                Directory.CreateDirectory(directories[i].Replace(sourcePath, destinationPath));
            }
        }
        directories = Directory.GetFiles(sourcePath, "*.*", SearchOption.AllDirectories);
        Logging.tML.Info((object)$"Number of files to Copy: {directories.Length}. Estimated time for HDD @15 MB/s: {directories.Length / 30} seconds");
        string[] array = directories;
        foreach (string obj in array)
        {
            string relativePath = ConvertToRelativePath(sourcePath, obj);
            if (excludeFilter == null || !excludeFilter.IsMatch(relativePath))
            {
                CopyExtended(obj, obj.Replace(sourcePath, destinationPath), isCloud, overwriteAlways, overwriteOld);
            }
        }
    }
References Terraria.Utilities.FileUtilities.ConvertToRelativePath(), Terraria.Utilities.FileUtilities.CopyExtended(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.Utilities.FileUtilities.CopyFolder(), and Terraria.Program.PortFilesFromXtoY().