TModLoader: Terraria.Utilities.FileUtilities.WriteAllBytes
WriteAllBytes()
static void Terraria.Utilities.FileUtilities.WriteAllBytes (string path, byte[] data, bool cloud) inline static
    {
        Write(path, data, data.Length, cloud);
    }
References Terraria.Utilities.FileUtilities.path, and Terraria.Utilities.FileUtilities.Write().
Referenced by Terraria.Utilities.FileUtilities.CopyToLocal(), Terraria.Map.MapHelper.InternalSaveMap(), Terraria.Player.InternalSavePlayerFile(), Terraria.IO.WorldFile.InternalSaveWorld(), Terraria.Utilities.FileUtilities.MoveToCloud(), Terraria.Utilities.FileUtilities.MoveToLocal(), Terraria.IO.FavoritesFile.Save(), Terraria.Achievements.AchievementManager.Save(), and Terraria.ModLoader.IO.MapIO.WriteModFile().