TModLoader: Terraria.Utilities.FileUtilities.Exists
Exists()
static bool Terraria.Utilities.FileUtilities.Exists (string path, bool cloud) inline static
Definition at line 18 of file FileUtilities.cs.
    {
        if (cloud && SocialAPI.Cloud != null)
        {
            return SocialAPI.Cloud.HasFile(path);
        }
        return File.Exists(path);
    }
References Terraria.Social.SocialAPI.Cloud, Terraria.Social.Steam.CloudSocialModule.HasFile(), and Terraria.Utilities.FileUtilities.path.
Referenced by Terraria.IO.WorldFile.DoRollingBackups(), Terraria.Main.DrawMenu(), Terraria.IO.WorldFile.GetAllMetadata(), Terraria.Player.GetFileData(), Terraria.Main.GetPlayerPathFromName(), Terraria.Main.GetWorldPathFromName(), Terraria.Player.InternalSavePlayerFile(), Terraria.IO.WorldFile.InternalSaveWorld(), Terraria.Player.KillMeForGood(), Terraria.IO.FavoritesFile.Load(), Terraria.Map.WorldMap.Load(), Terraria.Achievements.AchievementManager.Load(), Terraria.ModLoader.IO.WorldIO.Load(), Terraria.ModLoader.IO.PlayerIO.LoadBackup(), Terraria.ModLoader.IO.WorldIO.LoadBackup(), Terraria.ModLoader.IO.WorldIO.LoadDedServBackup(), Terraria.IO.WorldFile.LoadWorld(), Terraria.ModLoader.IO.PlayerIO.MoveToLocal(), Terraria.ModLoader.IO.WorldIO.MoveToLocal(), Terraria.WorldGen.playWorldCallBack(), Terraria.ModLoader.IO.MapIO.ReadModFile(), Terraria.ModLoader.IO.WorldIO.ReadWorldHeader(), Terraria.ModLoader.IO.WorldIO.RevertDedServBackup(), Terraria.ModLoader.IO.WorldIO.Save(), Terraria.ModLoader.IO.PlayerIO.Save(), Terraria.WorldGen.serverLoadWorldCallBack(), Terraria.ModLoader.IO.PlayerIO.TryLoadData(), Terraria.ModLoader.BackupIO.World.WriteArchive(), and Terraria.ModLoader.BackupIO.Player.WriteArchive().