TModLoader: Terraria.Utilities.FileUtilities.WriteTagCompound
WriteTagCompound()
static bool Terraria.Utilities.FileUtilities.WriteTagCompound (string path, bool isCloud, TagCompound tag) inline static package
Definition at line 320 of file FileUtilities.cs.
    {
        MemoryStream stream = new MemoryStream();
        TagIO.ToStream(tag, stream);
        byte[] data = stream.ToArray();
        string fileName = Path.GetFileName(path);
        if (data[0] != 31 || data[1] != 139)
        {
            Write(path + ".corr", data, data.Length, isCloud);
            throw new IOException("Detected Corrupted Save Stream attempt.\nAborting to avoid " + fileName + " corruption.\nYour last successful save will be kept. ERROR: Stream Missing NBT Header.");
        }
        Write(path, data, data.Length, isCloud);
        if (ReadAllBytes(path, isCloud).SequenceEqual(data))
        {
            return true;
        }
        Logging.tML.Warn((object)("Detected failed save for " + fileName + ". Re-attempting after 2 seconds"));
        Thread.Sleep(2000);
        Write(path, data, data.Length, isCloud);
        if (!ReadAllBytes(path, isCloud).SequenceEqual(data))
        {
            throw new IOException("Unable to save current progress.\nAborting to avoid " + fileName + " corruption.\nYour last successful save will be kept. ERROR: Stream Missing NBT Header.");
        }
        return true;
    }
References Terraria.Utilities.FileUtilities.path, Terraria.Utilities.FileUtilities.ReadAllBytes(), Terraria.ModLoader.Logging.tML, Terraria.ModLoader.IO.TagIO.ToStream(), and Terraria.Utilities.FileUtilities.Write().
Referenced by Terraria.ModLoader.IO.WorldIO.Save(), and Terraria.ModLoader.IO.PlayerIO.Save().