TModLoader: Terraria.Utilities.FileUtilities.CopyExtended
CopyExtended()
static void Terraria.Utilities.FileUtilities.CopyExtended (string source, string destination, bool cloud, bool overwriteAlways, bool overwriteOld = true) inline static
    {
        bool overwrite = DetermineIfShouldOverwrite(overwriteAlways, overwriteOld, source, destination);
        if (!overwrite && File.Exists(destination))
        {
            return;
        }
        if (!cloud)
        {
            try
            {
                File.Copy(source, destination, overwrite);
                return;
            }
            catch (IOException ex)
            {
                if (ex.GetType() != typeof(IOException))
                {
                    throw;
                }
                using FileStream inputstream = File.OpenRead(source);
                using FileStream outputstream = File.Create(destination);
                inputstream.CopyTo(outputstream);
                return;
            }
        }
        string cloudSaveLocation = CoreSocialModule.GetCloudSaveLocation();
        destination = ConvertToRelativePath(cloudSaveLocation, destination);
        source = ConvertToRelativePath(cloudSaveLocation, source);
        if (SocialAPI.Cloud != null && (overwrite || !SocialAPI.Cloud.HasFile(destination)))
        {
            byte[] bytes = SocialAPI.Cloud.Read(source);
            SocialAPI.Cloud.Write(destination, bytes);
        }
    }
References Terraria.Social.SocialAPI.Cloud, Terraria.Utilities.FileUtilities.ConvertToRelativePath(), Terraria.Utilities.FileUtilities.DetermineIfShouldOverwrite(), and Terraria.Social.Steam.CoreSocialModule.GetCloudSaveLocation().
Referenced by Terraria.Utilities.FileUtilities.Copy(), and Terraria.Utilities.FileUtilities.CopyFolderEXT().