TModLoader: Terraria.Social.Steam.WorkshopBrowserModule.DownloadItem
DownloadItem()
void Terraria.Social.Steam.WorkshopBrowserModule.DownloadItem (ModDownloadItem item, IDownloadProgress uiProgress) inline
Implements Terraria.Social.Base.SocialBrowserModule.
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        item.UpdateInstallState();
        PublishedFileId_t publishId = default(PublishedFileId_t);
        ((PublishedFileId_t)(ref publishId))._002Ector(ulong.Parse(item.PublishId.m_ModPubId));
        bool forceUpdate = item.NeedUpdate || !SteamedWraps.IsWorkshopItemInstalled(publishId);
        uiProgress?.DownloadStarted(item.DisplayName);
        Utils.LogAndConsoleInfoMessage(Language.GetTextValue("tModLoader.BeginDownload", item.DisplayName));
        SteamedWraps.Download(publishId, uiProgress, forceUpdate);
        EnsureInstallationComplete(item);
    }
References Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.DisplayName, Terraria.Social.Steam.SteamedWraps.Download(), Terraria.Social.Steam.WorkshopBrowserModule.EnsureInstallationComplete(), Terraria.Localization.Language.GetTextValue(), Terraria.Social.Steam.SteamedWraps.IsWorkshopItemInstalled(), Terraria.Utils.LogAndConsoleInfoMessage(), Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.PublishId, and Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.UpdateInstallState().