TModLoader: Terraria.Social.Steam.WorkshopBrowserModule.EnsureInstallationComplete
EnsureInstallationComplete()
void Terraria.Social.Steam.WorkshopBrowserModule.EnsureInstallationComplete (ModDownloadItem item) inline
    {
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        Logging.tML.Info((object)"Validating Installation Has Completed: Step 1 / 2");
        string workshopFolder = WorkshopHelper.GetWorkshopFolder(Terraria.ModLoader.Engine.Steam.TMLAppID_t);
        AppId_t tMLAppID_t = Terraria.ModLoader.Engine.Steam.TMLAppID_t;
        string itemFolder = Path.Combine(workshopFolder, "content", ((object)(AppId_t)(ref tMLAppID_t)).ToString(), item.PublishId.m_ModPubId.ToString());
        for (int j = 0; j < 30; j++)
        {
            Thread.Sleep(500);
            if (Directory.Exists(itemFolder))
            {
                break;
            }
            Logging.tML.Info((object)$"Workshop Folder Missing. Awaiting. Attempt {j} / 20");
        }
        if (!Directory.Exists(itemFolder))
        {
            throw new Exception("Workshop Item " + item.DisplayNameClean + " Failed to Install during this play session!\nPlease restart the game to resolve.");
        }
        Logging.tML.Info((object)"Validating Installation Has Completed: Step 2 / 2");
        for (int i = 0; i < 20; i++)
        {
            Thread.Sleep(500);
            string fileName = ModOrganizer.GetActiveTmodInRepo(itemFolder);
            if (string.IsNullOrEmpty(fileName))
            {
                continue;
            }
            TmodFile modFile = new TmodFile(fileName);
            using (modFile.Open())
            {
                if (modFile.Version == item.Version)
                {
                    break;
                }
            }
            Logging.tML.Info((object)$"Mod Update Not Received. Awaiting. Attempt {i} / 20");
        }
    }
References Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.DisplayNameClean, Terraria.ModLoader.Core.ModOrganizer.GetActiveTmodInRepo(), Terraria.Social.Steam.WorkshopHelper.GetWorkshopFolder(), Terraria.ModLoader.Core.TmodFile.Open(), Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.PublishId, Terraria.ModLoader.Logging.tML, Terraria.ModLoader.Engine.Steam.TMLAppID_t, Terraria.ModLoader.Core.TmodFile.Version, and Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.Version.
Referenced by Terraria.Social.Steam.WorkshopBrowserModule.DownloadItem().