TModLoader: Terraria.Social.Steam.WorkshopBrowserModule.OnLocalModsChanged
OnLocalModsChanged()
void Terraria.Social.Steam.WorkshopBrowserModule.OnLocalModsChanged (HashSet< string > modSlugs, bool isDeletion) inline private
Definition at line 45 of file WorkshopBrowserModule.cs.
    {
        InstalledItems = ModOrganizer.FindWorkshopMods();
        if (SteamedWraps.SteamAvailable)
        {
            CachedInstalledModDownloadItems = ((SocialBrowserModule)this).DirectQueryInstalledMDItems(default(QueryParameters));
        }
        if (!isDeletion)
        {
            return;
        }
        foreach (string item in modSlugs)
        {
            intermediateInstallStateMods.Add(item);
        }
    }
References Terraria.Social.Steam.WorkshopBrowserModule.CachedInstalledModDownloadItems, Terraria.ModLoader.Core.ModOrganizer.FindWorkshopMods(), Terraria.Social.Steam.WorkshopBrowserModule.InstalledItems, Terraria.Social.Steam.WorkshopBrowserModule.intermediateInstallStateMods, and Terraria.Social.Steam.SteamedWraps.SteamAvailable.
Referenced by Terraria.Social.Steam.WorkshopBrowserModule.WorkshopBrowserModule(), and Terraria.Social.Steam.WorkshopBrowserModule.Initialize().