TModLoader: Terraria.ModLoader.Core.ModOrganizer.SelectAndSortMods
SelectAndSortMods()
static List< LocalMod > Terraria.ModLoader.Core.ModOrganizer.SelectAndSortMods (IEnumerable< LocalMod > availableMods, CancellationToken token) inline static package
Definition at line 357 of file ModOrganizer.cs.
    {
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        List<string> missing = ModLoader.EnabledMods.Except(availableMods.Select((LocalMod mod) => mod.Name)).ToList();
        if (missing.Any())
        {
            Logging.tML.Info((object)("Missing previously enabled mods: " + string.Join(", ", missing)));
            foreach (string name in missing)
            {
                ModLoader.EnabledMods.Remove(name);
            }
            SaveEnabledMods();
        }
        if ((((Game)Main.instance).IsActive && Main.oldKeyState.PressingShift()) || ModLoader.skipLoad || token.IsCancellationRequested)
        {
            ModLoader.skipLoad = false;
            Interface.loadMods.SetLoadStage("tModLoader.CancellingLoading");
            return new List<LocalMod>();
        }
        CommandLineModPackOverride(availableMods);
        Interface.loadMods.SetLoadStage("tModLoader.MSFinding");
        foreach (LocalMod item in GetModsToLoad(availableMods))
        {
            EnableWithDeps(item, availableMods);
        }
        SaveEnabledMods();
        List<LocalMod> modsToLoad = GetModsToLoad(availableMods);
        try
        {
            EnsureDependenciesExist(modsToLoad, includeWeak: false);
            EnsureTargetVersionsMet(modsToLoad);
            return Sort(modsToLoad);
        }
        catch (ModSortingException e)
        {
            e.Data["mods"] = e.errored.Select((LocalMod m) => m.Name).ToArray();
            e.Data["hideStackTrace"] = true;
            throw;
        }
    }
References Terraria.ModLoader.Core.ModOrganizer.CommandLineModPackOverride(), Terraria.ModLoader.ModLoader.EnabledMods, Terraria.ModLoader.Core.ModOrganizer.EnableWithDeps(), Terraria.ModLoader.Core.ModOrganizer.EnsureDependenciesExist(), Terraria.ModLoader.Core.ModOrganizer.EnsureTargetVersionsMet(), Terraria.ModLoader.Core.ModOrganizer.GetModsToLoad(), Terraria.Main.instance, Terraria.ModLoader.UI.Interface.loadMods, Terraria.ModLoader.Core.LocalMod.Name, Terraria.Main.oldKeyState, Terraria.ModLoader.Core.ModOrganizer.SaveEnabledMods(), Terraria.ModLoader.UI.UILoadMods.SetLoadStage(), Terraria.ModLoader.ModLoader.skipLoad, Terraria.ModLoader.Core.ModOrganizer.Sort(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.ModLoader.ModLoader.Load().