TModLoader: Terraria.ModLoader.Core.ModOrganizer.ApplyPreviewChecks
ApplyPreviewChecks()
static bool Terraria.ModLoader.Core.ModOrganizer.ApplyPreviewChecks (LocalMod mod) inline static package
Definition at line 168 of file ModOrganizer.cs.
    {
        if (BuildInfo.IsPreview)
        {
            return IsModFromSteam(mod.modFile.path);
        }
        return false;
    }
References Terraria.ModLoader.Core.ModOrganizer.IsModFromSteam(), Terraria.ModLoader.BuildInfo.IsPreview, and Terraria.ModLoader.Core.LocalMod.modFile.
Referenced by Terraria.ModLoader.Core.ModOrganizer.CheckStableBuildOnPreview(), and Terraria.ModLoader.Core.ModOrganizer.SkipModForPreviewNotPlayable().