TModLoader: Terraria.ModLoader.Core.ModOrganizer.AnalyzeWorkshopTmods
AnalyzeWorkshopTmods()
static List<(string file, Version tModVersion, bool isInFolder)> Terraria.ModLoader.Core.ModOrganizer.AnalyzeWorkshopTmods (string repo) inline static package
Definition at line 717 of file ModOrganizer.cs.
    {
        string[] files = Directory.GetFiles(repo, "*.tmod", SearchOption.AllDirectories);
        List<(string, Version, bool)> information = new List<(string, Version, bool)>();
        string[] array = files;
        foreach (string filename in array)
        {
            Match match = PublishFolderMetadata.Match(filename);
            if (match.Success)
            {
                information.Add((filename, new Version(match.Groups[1].Value), true));
            }
            else
            {
                information.Add((filename, new Version(0, 12), false));
            }
        }
        return information;
    }
References Terraria.ModLoader.Core.ModOrganizer.PublishFolderMetadata.
Referenced by Terraria.ModLoader.Core.ModOrganizer.CleanupOldPublish(), Terraria.Social.Steam.WorkshopSocialModule.DetermineSupportedVersionsFromWorkshop(), and Terraria.ModLoader.Core.ModOrganizer.GetActiveTmodInRepo().