TModLoader: Terraria.ModLoader.Core.ModOrganizer.EnsureTargetVersionsMet
EnsureTargetVersionsMet()
static void Terraria.ModLoader.Core.ModOrganizer.EnsureTargetVersionsMet (ICollection< LocalMod > mods) inline static package
    {
        Dictionary<string, LocalMod> nameMap = mods.ToDictionary((LocalMod mod) => mod.Name);
        HashSet<LocalMod> errored = new HashSet<LocalMod>();
        StringBuilder errorLog = new StringBuilder();
        foreach (LocalMod mod2 in mods)
        {
            foreach (BuildProperties.ModReference dep in mod2.properties.Refs(includeWeak: true))
            {
                if (!(dep.target == null) && nameMap.TryGetValue(dep.mod, out var inst))
                {
                    if (inst.properties.version < dep.target)
                    {
                        errored.Add(mod2);
                        errorLog.AppendLine(Language.GetTextValue("tModLoader.LoadErrorDependencyVersionTooLow", mod2, dep.target, dep.mod, inst.properties.version));
                    }
                    else if (inst.properties.version.Major != dep.target.Major)
                    {
                        errored.Add(mod2);
                        errorLog.AppendLine(Language.GetTextValue("tModLoader.LoadErrorMajorVersionMismatch", mod2, dep.target, dep.mod, inst.properties.version));
                    }
                }
            }
        }
        if (errored.Count > 0)
        {
            throw new ModSortingException(errored, errorLog.ToString());
        }
    }
References Terraria.Localization.Language.GetTextValue(), and Terraria.ModLoader.Core.LocalMod.Name.
Referenced by Terraria.ModLoader.Core.ModCompile.BuildAll(), and Terraria.ModLoader.Core.ModOrganizer.SelectAndSortMods().