TModLoader: Terraria.ModLoader.Core.ModOrganizer.DetectModChangesForInfoMessage
DetectModChangesForInfoMessage()
static string Terraria.ModLoader.Core.ModOrganizer.DetectModChangesForInfoMessage () inline static package
Returns changes based on last time M:Terraria.ModLoader.Core.ModOrganizer.SaveLastLaunchedMods was called. Can be null if no changes.
    {
        if (!ModLoader.showNewUpdatedModsInfo || !File.Exists(lastLaunchedModsFilePath))
        {
            return null;
        }
        Dictionary<string, LocalMod> currMods = FindWorkshopMods().ToDictionary((LocalMod mod) => mod.Name, (LocalMod mod) => mod);
        Logging.tML.Info((object)("3 most recently changed workshop mods: " + string.Join(", ", from x in currMods.OrderByDescending((KeyValuePair<string, LocalMod> x) => x.Value.lastModified).Take(3)
            select $"{x.Value.Name} v{x.Value.properties.version} {x.Value.lastModified:d}")));
        try
        {
            IEnumerable<string> enumerable = File.ReadLines(lastLaunchedModsFilePath);
            Dictionary<string, Version> lastMods = new Dictionary<string, Version>();
            foreach (string item2 in enumerable)
            {
                string[] parts = item2.Split(' ');
                if (parts.Length == 2)
                {
                    string name3 = parts[0];
                    string versionString = parts[1];
                    lastMods.Add(name3, new Version(versionString));
                }
            }
            List<string> newMods = new List<string>();
            List<string> updatedMods = new List<string>();
            StringBuilder messages = new StringBuilder();
            foreach (KeyValuePair<string, LocalMod> item in currMods)
            {
                string name2 = item.Key;
                Version version = item.Value.properties.version;
                Version lastVersion2;
                if (!lastMods.ContainsKey(name2))
                {
                    newMods.Add(name2);
                    modsThatUpdatedSinceLastLaunch.Add((name2, null));
                }
                else if (lastMods.TryGetValue(name2, out lastVersion2) && lastVersion2 < version)
                {
                    updatedMods.Add(name2);
                    modsThatUpdatedSinceLastLaunch.Add((name2, lastVersion2));
                }
            }
            if (newMods.Count > 0)
            {
                messages.Append(Language.GetTextValue("tModLoader.ShowNewUpdatedModsInfoMessageNewMods"));
                foreach (string newMod in newMods)
                {
                    StringBuilder stringBuilder = messages;
                    StringBuilder stringBuilder2 = stringBuilder;
                    StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(6, 2, stringBuilder);
                    handler.AppendLiteral("\n  ");
                    handler.AppendFormatted(newMod);
                    handler.AppendLiteral(" (");
                    handler.AppendFormatted(currMods[newMod].DisplayName);
                    handler.AppendLiteral(")");
                    stringBuilder2.Append(ref handler);
                }
            }
            if (updatedMods.Count > 0)
            {
                messages.Append(Language.GetTextValue("tModLoader.ShowNewUpdatedModsInfoMessageUpdatedMods"));
                foreach (string name in updatedMods)
                {
                    string displayName = currMods[name].DisplayName;
                    Version lastVersion = lastMods[name];
                    Version currVersion = currMods[name].properties.version;
                    StringBuilder stringBuilder = messages;
                    StringBuilder stringBuilder3 = stringBuilder;
                    StringBuilder.AppendInterpolatedStringHandler handler = new StringBuilder.AppendInterpolatedStringHandler(13, 4, stringBuilder);
                    handler.AppendLiteral("\n  ");
                    handler.AppendFormatted(name);
                    handler.AppendLiteral(" (");
                    handler.AppendFormatted(displayName);
                    handler.AppendLiteral(") v");
                    handler.AppendFormatted(lastVersion);
                    handler.AppendLiteral(" -> v");
                    handler.AppendFormatted(currVersion);
                    stringBuilder3.Append(ref handler);
                }
            }
            return (messages.Length > 0) ? messages.ToString() : null;
        }
        catch
        {
            return null;
        }
    }
References Terraria.ModLoader.Core.ModOrganizer.FindWorkshopMods(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.Core.ModOrganizer.lastLaunchedModsFilePath, Terraria.ModLoader.Core.ModOrganizer.modsThatUpdatedSinceLastLaunch, Terraria.ModLoader.Core.LocalMod.Name, Terraria.ModLoader.ModLoader.showNewUpdatedModsInfo, and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.ModLoader.UI.Interface.ModLoaderMenus().