TModLoader: Terraria.ModLoader.Core.ModOrganizer.CleanupOldPublish
CleanupOldPublish()
static void Terraria.ModLoader.Core.ModOrganizer.CleanupOldPublish (string repo) inline static package
Must Be called AFTER the new files are added to the publishing repo. Assumes one .tmod per YYYY.XX folder in the publishing repo.
Parameters
repo
Definition at line 670 of file ModOrganizer.cs.
    {
        if (BuildInfo.IsPreview)
        {
            RemoveSkippablePreview(repo);
        }
        if (Directory.GetFiles(repo, "*.tmod", SearchOption.AllDirectories).Length <= 3)
        {
            return;
        }
        List<(string, Version, bool)> information = AnalyzeWorkshopTmods(repo);
        if (information == null || information.Count() <= 3)
        {
            return;
        }
        (string, int)[] array = new(string, int)[4]
        {
            ("1.4.3", 1),
            ("1.4.4", 3),
            ("1.3", 1),
            ("1.4.4-Transitive", 0)
        };
        for (int i = 0; i < array.Length; i++)
        {
            (string, int) requirement = array[i];
            foreach (var item in GetOrderedTmodWorkshopInfoForVersion(information, requirement.Item1).Skip(requirement.Item2))
            {
                if (item.isInFolder)
                {
                    Directory.Delete(Path.GetDirectoryName(item.file), recursive: true);
                }
                else
                {
                    File.Delete(item.file);
                }
            }
        }
    }
References Terraria.ModLoader.Core.ModOrganizer.AnalyzeWorkshopTmods(), Terraria.ModLoader.Core.ModOrganizer.GetOrderedTmodWorkshopInfoForVersion(), Terraria.ModLoader.BuildInfo.IsPreview, and Terraria.ModLoader.Core.ModOrganizer.RemoveSkippablePreview().
Referenced by Terraria.Social.Steam.WorkshopSocialModule._PublishMod(), and Terraria.Social.Steam.WorkshopSocialModule.SteamCMDPublishPreparer().