TModLoader: Terraria.ModLoader.Core.ModOrganizer.CommandLineModPackOverride
CommandLineModPackOverride()
static void Terraria.ModLoader.Core.ModOrganizer.CommandLineModPackOverride (IEnumerable< LocalMod > mods) inline static private
    {
        if (string.IsNullOrWhiteSpace(commandLineModPack))
        {
            return;
        }
        if (!commandLineModPack.EndsWith(".json"))
        {
            commandLineModPack += ".json";
        }
        string filePath = Path.Combine(UIModPacks.ModPacksDirectory, commandLineModPack);
        try
        {
            Directory.CreateDirectory(UIModPacks.ModPacksDirectory);
            Logging.ServerConsoleLine(Language.GetTextValue("tModLoader.LoadingSpecifiedModPack", commandLineModPack));
            HashSet<string> modSet = JsonConvert.DeserializeObject<HashSet<string>>(File.ReadAllText(filePath));
            foreach (LocalMod mod in mods)
            {
                mod.Enabled = modSet.Contains(mod.Name);
            }
        }
        catch (Exception e)
        {
            throw new Exception((e is FileNotFoundException) ? Language.GetTextValue("tModLoader.ModPackDoesNotExist", filePath) : Language.GetTextValue("tModLoader.ModPackMalformed", commandLineModPack), e);
        }
        finally
        {
            commandLineModPack = null;
        }
    }
References Terraria.ModLoader.Core.ModOrganizer.commandLineModPack, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.UIModPacks.ModPacksDirectory, Terraria.ModLoader.Core.LocalMod.Name, and Terraria.ModLoader.Logging.ServerConsoleLine().
Referenced by Terraria.ModLoader.Core.ModOrganizer.SelectAndSortMods().