TModLoader: Terraria.ModLoader.Core.ModOrganizer._FindMods
_FindMods()
static LocalMod[] Terraria.ModLoader.Core.ModOrganizer._FindMods (bool ignoreModsFolder = false, bool ignoreWorkshop = false, bool logDuplicates = false) inline static package
    {
        Directory.CreateDirectory(ModLoader.ModPath);
        List<LocalMod> mods = new List<LocalMod>();
        HashSet<string> names = new HashSet<string>();
        DeleteTemporaryFiles();
        WorkshopFileFinder.Refresh(new WorkshopIssueReporter());
        if (!ignoreModsFolder && !string.IsNullOrEmpty(ModPackActive))
        {
            if (Directory.Exists(ModPackActive))
            {
                Logging.tML.Info((object)("Loaded Mods from Active Mod Pack: " + ModPackActive));
                string[] files = Directory.GetFiles(ModPackActive, "*.tmod", SearchOption.AllDirectories);
                for (int i = 0; i < files.Length; i++)
                {
                    AttemptLoadMod(files[i], ref mods, ref names, logDuplicates, devLocation: true);
                }
            }
            else
            {
                ModPackActive = null;
            }
        }
        if (!ignoreModsFolder)
        {
            string[] files = Directory.GetFiles(modPath, "*.tmod", SearchOption.TopDirectoryOnly);
            for (int i = 0; i < files.Length; i++)
            {
                AttemptLoadMod(files[i], ref mods, ref names, logDuplicates, devLocation: true);
            }
        }
        if (!ignoreWorkshop)
        {
            foreach (string modPath in WorkshopFileFinder.ModPaths)
            {
                string fileName = GetActiveTmodInRepo(modPath);
                if (fileName != null)
                {
                    AttemptLoadMod(fileName, ref mods, ref names, logDuplicates, devLocation: false);
                }
            }
        }
        return mods.OrderBy<LocalMod, string>((LocalMod x) => x.Name, StringComparer.InvariantCulture).ToArray();
    }
References Terraria.ModLoader.Core.ModOrganizer.AttemptLoadMod(), Terraria.ModLoader.Core.ModOrganizer.DeleteTemporaryFiles(), Terraria.ModLoader.Core.ModOrganizer.GetActiveTmodInRepo(), Terraria.ModLoader.Core.ModOrganizer.ModPackActive, Terraria.ModLoader.Core.ModOrganizer.modPath, Terraria.ModLoader.ModLoader.ModPath, Terraria.ModLoader.Logging.tML, and Terraria.ModLoader.Core.ModOrganizer.WorkshopFileFinder.
Referenced by Terraria.ModLoader.Core.ModOrganizer.FindDevFolderMods(), Terraria.ModLoader.Core.ModOrganizer.FindMods(), and Terraria.ModLoader.Core.ModOrganizer.FindWorkshopMods().