TModLoader: Terraria.ModLoader.Core.ModOrganizer.DeleteMod
DeleteMod()
static void Terraria.ModLoader.Core.ModOrganizer.DeleteMod (LocalMod tmod) inline static package
Definition at line 754 of file ModOrganizer.cs.
    {
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        string tmodPath = tmod.modFile.path;
        string parentDir = GetParentDir(tmodPath);
        if (TryReadManifest(parentDir, out var info))
        {
            SteamedWraps.UninstallWorkshopItem(new PublishedFileId_t(info.workshopEntryId), parentDir);
        }
        else
        {
            File.Delete(tmodPath);
        }
        LocalModsChanged(new HashSet<string> { tmod.Name }, isDeletion: true);
    }
References Terraria.ModLoader.Core.ModOrganizer.GetParentDir(), Terraria.ModLoader.Core.ModOrganizer.LocalModsChanged(), Terraria.ModLoader.Core.ModOrganizer.TryReadManifest(), and Terraria.Social.Steam.SteamedWraps.UninstallWorkshopItem().
Referenced by Terraria.ModLoader.UI.UIModInfo.DeleteMod(), and Terraria.ModLoader.UI.UIModItem.DeleteMod().