TModLoader: Terraria.ModLoader.Core.ModOrganizer.GetActiveTmodInRepo
GetActiveTmodInRepo()
static string Terraria.ModLoader.Core.ModOrganizer.GetActiveTmodInRepo (string repo) inline static package
Definition at line 642 of file ModOrganizer.cs.
    {
        IEnumerable<(string, Version, bool)> information = from t in AnalyzeWorkshopTmods(repo)
            where !SocialBrowserModule.GetBrowserVersionNumber(t.tModVersion).Contains("Transitive")
            select t;
        if (information == null || information.Count() == 0)
        {
            Logging.tML.Warn((object)("Unexpectedly missing .tMods in Workshop Folder " + repo));
            return null;
        }
        (string, Version, bool) recommendedTmod = (from t in information
            where t.tModVersion <= BuildInfo.tMLVersion
            orderby t.tModVersion descending
            select t).FirstOrDefault();
        (string, Version, bool) tuple = recommendedTmod;
        if (tuple.Item1 == null && tuple.Item2 == null && !tuple.Item3)
        {
            Logging.tML.Warn((object)("No .tMods found for this version in Workshop Folder " + repo + ". Defaulting to show newest"));
            return information.OrderByDescending<(string, Version, bool), Version>(((string file, Version tModVersion, bool isInFolder) t) => t.tModVersion).First().Item1;
        }
        return recommendedTmod.Item1;
    }
References Terraria.ModLoader.Core.ModOrganizer.AnalyzeWorkshopTmods(), Terraria.Social.Base.SocialBrowserModule.GetBrowserVersionNumber(), Terraria.ModLoader.Logging.tML, and Terraria.ModLoader.BuildInfo.tMLVersion.
Referenced by Terraria.ModLoader.Core.ModOrganizer._FindMods(), and Terraria.Social.Steam.WorkshopBrowserModule.EnsureInstallationComplete().