TModLoader: Terraria.Audio.SoundPlayer.Play
Play()
SlotId Terraria.Audio.SoundPlayer.Play (in SoundStyle style, Vector2? position = null, SoundUpdateCallback? updateCallback = null) inline
Definition at line 13 of file SoundPlayer.cs.
    {
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        SoundUpdateCallback updateCallback2 = updateCallback;
        if (Main.dedServ)
        {
            return SlotId.Invalid;
        }
        if (position.HasValue && Vector2.DistanceSquared(Main.screenPosition + new Vector2((float)(Main.screenWidth / 2), (float)(Main.screenHeight / 2)), position.Value) > 100000000f)
        {
            return SlotId.Invalid;
        }
        if (style.PlayOnlyIfFocused && !Main.hasFocus)
        {
            return SlotId.Invalid;
        }
        if (!Program.IsMainThread)
        {
            SoundStyle styleCopy = style;
            return Main.RunOnMainThread(() => Play_Inner(in styleCopy, position, updateCallback2)).GetAwaiter().GetResult();
        }
        return Play_Inner(in style, position, updateCallback2);
    }
References Terraria.Main.dedServ, Terraria.Main.hasFocus, Terraria.Program.IsMainThread, Terraria.Audio.SoundPlayer.Play_Inner(), Terraria.Main.RunOnMainThread(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, and Terraria.Audio.SoundUpdateCallback().
Referenced by Terraria.Audio.SoundEngine.PlaySound().