TModLoader: Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryOpenDoor
TryOpenDoor()
bool Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryOpenDoor (DoorOpenCloseTogglingInfo doorInfo, PlayerInfoForOpeningDoors playerInfo) inline
Implements Terraria.GameContent.DoorOpeningHelper.DoorAutoHandler.
Definition at line 78 of file DoorOpeningHelper.cs.
        {
            //IL_0001: Unknown result type (might be due to invalid IL or missing references)
            //IL_0006: Unknown result type (might be due to invalid IL or missing references)
            //IL_0011: Unknown result type (might be due to invalid IL or missing references)
            //IL_001f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0073: Unknown result type (might be due to invalid IL or missing references)
            //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
            //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
            //IL_010b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0111: Unknown result type (might be due to invalid IL or missing references)
            //IL_0149: Unknown result type (might be due to invalid IL or missing references)
            //IL_014f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0162: Unknown result type (might be due to invalid IL or missing references)
            //IL_0168: Unknown result type (might be due to invalid IL or missing references)
            //IL_012f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0136: Unknown result type (might be due to invalid IL or missing references)
            //IL_0186: Unknown result type (might be due to invalid IL or missing references)
            //IL_018d: Unknown result type (might be due to invalid IL or missing references)
            Point tileCoordsForToggling = doorInfo.tileCoordsForToggling;
            int intendedOpeningDirection = playerInfo.intendedOpeningDirection;
            Rectangle rectangle = default(Rectangle);
            ((Rectangle)(ref rectangle))._002Ector(doorInfo.tileCoordsForToggling.X * 16, doorInfo.tileCoordsForToggling.Y * 16, 16, 48);
            switch (playerInfo.playerGravityDirection)
            {
            case 1:
                rectangle.Height += 16;
                break;
            case -1:
                rectangle.Y -= 16;
                rectangle.Height += 16;
                break;
            }
            if (!((Rectangle)(ref rectangle)).Intersects(playerInfo.hitboxToOpenDoor))
            {
                return false;
            }
            if (((Rectangle)(ref playerInfo.hitboxToOpenDoor)).Top < ((Rectangle)(ref rectangle)).Top || ((Rectangle)(ref playerInfo.hitboxToOpenDoor)).Bottom > ((Rectangle)(ref rectangle)).Bottom)
            {
                return false;
            }
            int originalClosedDoorType = 10;
            ModTile modTile = ModContent.GetModTile(Main.tile[tileCoordsForToggling.X, tileCoordsForToggling.Y].type);
            if (modTile != null && TileID.Sets.OpenDoorID[modTile.Type] > -1)
            {
                originalClosedDoorType = modTile.Type;
            }
            WorldGen.OpenDoor(tileCoordsForToggling.X, tileCoordsForToggling.Y, intendedOpeningDirection);
            if (Main.tile[tileCoordsForToggling.X, tileCoordsForToggling.Y].type != originalClosedDoorType)
            {
                NetMessage.SendData(19, -1, -1, null, 0, tileCoordsForToggling.X, tileCoordsForToggling.Y, intendedOpeningDirection);
                return true;
            }
            WorldGen.OpenDoor(tileCoordsForToggling.X, tileCoordsForToggling.Y, -intendedOpeningDirection);
            if (Main.tile[tileCoordsForToggling.X, tileCoordsForToggling.Y].type != originalClosedDoorType)
            {
                NetMessage.SendData(19, -1, -1, null, 0, tileCoordsForToggling.X, tileCoordsForToggling.Y, -intendedOpeningDirection);
                return true;
            }
            return false;
        }
References Terraria.ModLoader.ModContent.GetModTile(), Terraria.WorldGen.OpenDoor(), Terraria.ID.TileID.Sets.OpenDoorID, Terraria.NetMessage.SendData(), and Terraria.Main.tile.