TModLoader: Terraria.DelegateMethods.Minecart.SpawnFartCloud
SpawnFartCloud()
static void Terraria.DelegateMethods.Minecart.SpawnFartCloud (Player Player, Vector2 Position, int Width, int Height, bool useDelay = true) inline static
        {
            //IL_0022: Unknown result type (might be due to invalid IL or missing references)
            //IL_002f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0034: Unknown result type (might be due to invalid IL or missing references)
            //IL_003a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0044: Unknown result type (might be due to invalid IL or missing references)
            //IL_0049: Unknown result type (might be due to invalid IL or missing references)
            //IL_006e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0075: Unknown result type (might be due to invalid IL or missing references)
            //IL_007a: Unknown result type (might be due to invalid IL or missing references)
            //IL_007f: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
            //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
            //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
            //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
            //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
            //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
            //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
            //IL_0104: Unknown result type (might be due to invalid IL or missing references)
            //IL_0130: Unknown result type (might be due to invalid IL or missing references)
            //IL_013a: Unknown result type (might be due to invalid IL or missing references)
            //IL_013f: Unknown result type (might be due to invalid IL or missing references)
            //IL_014c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0151: Unknown result type (might be due to invalid IL or missing references)
            //IL_0152: Unknown result type (might be due to invalid IL or missing references)
            //IL_0157: Unknown result type (might be due to invalid IL or missing references)
            //IL_0178: Unknown result type (might be due to invalid IL or missing references)
            //IL_017d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0182: Unknown result type (might be due to invalid IL or missing references)
            //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
            //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
            //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
            //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
            //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
            //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
            //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
            //IL_0058: Unknown result type (might be due to invalid IL or missing references)
            //IL_0059: Unknown result type (might be due to invalid IL or missing references)
            //IL_005e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0068: Unknown result type (might be due to invalid IL or missing references)
            //IL_006d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0216: Unknown result type (might be due to invalid IL or missing references)
            //IL_0220: Unknown result type (might be due to invalid IL or missing references)
            //IL_0225: Unknown result type (might be due to invalid IL or missing references)
            //IL_022a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0242: Unknown result type (might be due to invalid IL or missing references)
            //IL_026d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0272: Unknown result type (might be due to invalid IL or missing references)
            //IL_0279: Unknown result type (might be due to invalid IL or missing references)
            //IL_028e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0293: Unknown result type (might be due to invalid IL or missing references)
            //IL_02a8: Unknown result type (might be due to invalid IL or missing references)
            //IL_02b9: Unknown result type (might be due to invalid IL or missing references)
            //IL_02d3: Unknown result type (might be due to invalid IL or missing references)
            //IL_02d8: Unknown result type (might be due to invalid IL or missing references)
            //IL_0327: Unknown result type (might be due to invalid IL or missing references)
            //IL_032c: Unknown result type (might be due to invalid IL or missing references)
            //IL_032d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0332: Unknown result type (might be due to invalid IL or missing references)
            if (useDelay)
            {
                if (Player.fartKartCloudDelay > 0)
                {
                    return;
                }
                Player.fartKartCloudDelay = 20;
            }
            float num = 10f;
            float y = -4f;
            Vector2 val = Position + new Vector2((float)(Width / 2 - 18), (float)(Height - 16));
            Vector2 vector2 = Player.velocity * 0.1f;
            if (((Vector2)(ref vector2)).Length() > 2f)
            {
                vector2 = vector2.SafeNormalize(Vector2.Zero) * 2f;
            }
            int num2 = Gore.NewGore(val + new Vector2(0f, y), Vector2.Zero, Main.rand.Next(435, 438));
            Gore obj = Main.gore[num2];
            obj.velocity *= 0.2f;
            Gore obj2 = Main.gore[num2];
            obj2.velocity += vector2;
            Main.gore[num2].velocity.Y *= 0.75f;
            num2 = Gore.NewGore(val + new Vector2(0f - num, y), Vector2.Zero, Main.rand.Next(435, 438));
            Gore obj3 = Main.gore[num2];
            obj3.velocity *= 0.2f;
            Gore obj4 = Main.gore[num2];
            obj4.velocity += vector2;
            Main.gore[num2].velocity.Y *= 0.75f;
            num2 = Gore.NewGore(val + new Vector2(num, y), Vector2.Zero, Main.rand.Next(435, 438));
            Gore obj5 = Main.gore[num2];
            obj5.velocity *= 0.2f;
            Gore obj6 = Main.gore[num2];
            obj6.velocity += vector2;
            Main.gore[num2].velocity.Y *= 0.75f;
            if (Player.mount.Active && Player.mount.Type == 53)
            {
                Vector2 vector3 = Position + new Vector2((float)(Width / 2), (float)(Height + 10));
                float num3 = 30f;
                float num4 = -16f;
                for (int i = 0; i < 15; i++)
                {
                    Dust dust = Dust.NewDustPerfect(vector3 + new Vector2(0f - num3 + num3 * 2f * Main.rand.NextFloat(), num4 * Main.rand.NextFloat()), 107, Vector2.Zero, 100, Color.Lerp(new Color(64, 220, 96), Color.White, Main.rand.NextFloat() * 0.3f), 0.6f);
                    dust.velocity *= (float)Main.rand.Next(15, 51) * 0.01f;
                    dust.velocity.X *= (float)Main.rand.Next(25, 101) * 0.01f;
                    dust.velocity.Y -= (float)Main.rand.Next(15, 31) * 0.1f;
                    dust.velocity += vector2;
                    dust.velocity.Y *= 0.75f;
                    dust.fadeIn = 0.2f + Main.rand.NextFloat() * 0.1f;
                    dust.noGravity = Main.rand.Next(3) == 0;
                    dust.noLightEmittence = true;
                }
            }
        }
References Terraria.Mount.Active, Terraria.Player.fartKartCloudDelay, Terraria.Main.gore, Terraria.Player.mount, Terraria.Dust.NewDustPerfect(), Terraria.Gore.NewGore(), Terraria.Main.rand, and Terraria.Mount.Type.
Referenced by Terraria.DelegateMethods.Minecart.BumperSoundFart(), Terraria.DelegateMethods.Minecart.JumpingSoundFart(), and Terraria.DelegateMethods.Minecart.LandingSoundFart().