TModLoader: Terraria.DelegateMethods.Minecart.SparksFart
SparksFart()
static void Terraria.DelegateMethods.Minecart.SparksFart (Vector2 dustPosition) inline static
Definition at line 391 of file DelegateMethods.cs.
        {
            //IL_0000: Unknown result type (might be due to invalid IL or missing references)
            //IL_001a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0027: Unknown result type (might be due to invalid IL or missing references)
            //IL_002d: Unknown result type (might be due to invalid IL or missing references)
            //IL_002e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0033: Unknown result type (might be due to invalid IL or missing references)
            //IL_0038: Unknown result type (might be due to invalid IL or missing references)
            //IL_003a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0062: Unknown result type (might be due to invalid IL or missing references)
            //IL_0068: Unknown result type (might be due to invalid IL or missing references)
            //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
            //IL_0101: Unknown result type (might be due to invalid IL or missing references)
            //IL_0106: Unknown result type (might be due to invalid IL or missing references)
            dustPosition += Utils.RotatedBy(new Vector2((float)((Main.rand.Next(2) == 0) ? 13 : (-13)), 0f), rotation);
            int num = Dust.NewDust(dustPosition, 1, 1, 211, Main.rand.Next(-2, 3), Main.rand.Next(-2, 3), 50, default(Color), 0.8f);
            if (Main.rand.Next(2) == 0)
            {
                Main.dust[num].alpha += 25;
            }
            if (Main.rand.Next(2) == 0)
            {
                Main.dust[num].alpha += 25;
            }
            Main.dust[num].noLight = true;
            Main.dust[num].noGravity = Main.rand.Next(3) == 0;
            Dust obj = Main.dust[num];
            obj.velocity *= (float)Main.rand.Next(15, 51) * 0.01f;
            Main.dust[num].velocity.X *= (float)Main.rand.Next(25, 101) * 0.01f;
            Main.dust[num].velocity.Y -= (float)Main.rand.Next(15, 31) * 0.1f;
            Main.dust[num].position.Y -= 4f;
        }
References Terraria.Dust.alpha, Terraria.Main.dust, Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Dust.position, Terraria.Main.rand, Terraria.Utils.RotatedBy(), Terraria.DelegateMethods.Minecart.rotation, and Terraria.Dust.velocity.
Referenced by Terraria.Mount.Initialize(), and Terraria.DelegateMethods.Minecart.SparksTerraFart().