TModLoader: Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.GameContent.UI.Elements.UIPanel.
Definition at line 178 of file UIWorkshopImportWorldListItem.cs.
    {
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00de: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_023d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0269: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0294: Unknown result type (might be due to invalid IL or missing references)
        //IL_0299: Unknown result type (might be due to invalid IL or missing references)
        //IL_029e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0360: Unknown result type (might be due to invalid IL or missing references)
        //IL_0369: Unknown result type (might be due to invalid IL or missing references)
        //IL_036e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0373: Unknown result type (might be due to invalid IL or missing references)
        //IL_0388: Unknown result type (might be due to invalid IL or missing references)
        base.DrawSelf(spriteBatch);
        CalculatedStyle innerDimensions = GetInnerDimensions();
        CalculatedStyle dimensions = _worldIcon.GetDimensions();
        float num = dimensions.X + dimensions.Width;
        Color color = (_data.IsValid ? Color.White : Color.Gray);
        string worldName = _data.GetWorldName(allowCropping: true);
        if (worldName != null)
        {
            Utils.DrawBorderString(spriteBatch, worldName, new Vector2(num + 6f, dimensions.Y - 2f), color);
        }
        spriteBatch.Draw(_workshopIconTexture.Value, new Vector2(GetDimensions().X + GetDimensions().Width - (float)_workshopIconTexture.Width() - 3f, GetDimensions().Y + 2f), (Rectangle?)_workshopIconTexture.Frame(), Color.White);
        spriteBatch.Draw(_dividerTexture.Value, new Vector2(num, innerDimensions.Y + 21f), (Rectangle?)null, Color.White, 0f, Vector2.Zero, new Vector2((GetDimensions().X + GetDimensions().Width - num) / 8f, 1f), (SpriteEffects)0, 0f);
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(num + 6f, innerDimensions.Y + 29f);
        float num2 = 100f;
        DrawPanel(spriteBatch, vector, num2);
        string expertText = "";
        Color gameModeColor = Color.White;
        GetDifficulty(out expertText, out gameModeColor);
        float x = FontAssets.MouseText.Value.MeasureString(expertText).X;
        float x2 = num2 * 0.5f - x * 0.5f;
        Utils.DrawBorderString(spriteBatch, expertText, vector + new Vector2(x2, 3f), gameModeColor);
        vector.X += num2 + 5f;
        if (_data._worldSizeName != null)
        {
            float num3 = 150f;
            if (!GameCulture.FromCultureName(GameCulture.CultureName.English).IsActive)
            {
                num3 += 40f;
            }
            DrawPanel(spriteBatch, vector, num3);
            string textValue = Language.GetTextValue("UI.WorldSizeFormat", _data.WorldSizeName);
            float x3 = FontAssets.MouseText.Value.MeasureString(textValue).X;
            float x4 = num3 * 0.5f - x3 * 0.5f;
            Utils.DrawBorderString(spriteBatch, textValue, vector + new Vector2(x4, 3f), Color.White);
            vector.X += num3 + 5f;
        }
        float num4 = innerDimensions.X + innerDimensions.Width - vector.X;
        DrawPanel(spriteBatch, vector, num4);
        string arg = ((!GameCulture.FromCultureName(GameCulture.CultureName.English).IsActive) ? _data.CreationTime.ToShortDateString() : _data.CreationTime.ToString("d MMMM yyyy"));
        string textValue2 = Language.GetTextValue("UI.WorldCreatedFormat", arg);
        float x5 = FontAssets.MouseText.Value.MeasureString(textValue2).X;
        float x6 = num4 * 0.5f - x5 * 0.5f;
        Utils.DrawBorderString(spriteBatch, textValue2, vector + new Vector2(x6, 3f), Color.White);
        vector.X += num4 + 5f;
    }
References Terraria.GameContent.UI.Elements.AWorldListItem._data, Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem._dividerTexture, Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem._workshopIconTexture, Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem._worldIcon, Terraria.IO.WorldFileData._worldSizeName, Terraria.IO.WorldFileData.CreationTime, Terraria.Utils.DrawBorderString(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.DrawPanel(), Terraria.Localization.GameCulture.FromCultureName(), Terraria.GameContent.UI.Elements.AWorldListItem.GetDifficulty(), Terraria.UI.UIElement.GetDimensions(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.Localization.Language.GetTextValue(), Terraria.IO.WorldFileData.GetWorldName(), Terraria.Localization.GameCulture.IsActive, Terraria.GameContent.FontAssets.MouseText, Terraria.UI.CalculatedStyle.Width, Terraria.UI.UIElement.Width, Terraria.IO.WorldFileData.WorldSizeName, and Terraria.UI.CalculatedStyle.X.