TModLoader: Terraria.Utilities.UnifiedRandom.Next
Next() [1/3]
virtual int Terraria.Utilities.UnifiedRandom.Next () inline virtual
Definition at line 98 of file UnifiedRandom.cs.
    {
        return InternalSample();
    }
References Terraria.Utilities.UnifiedRandom.InternalSample().
Referenced by Terraria.GameContent.Skies.SolarSky.Activate(), Terraria.GameContent.Skies.StardustSky.Activate(), Terraria.Cloud.addCloud(), Terraria.GameContent.Events.MoonlordDeathDrama.AddExplosion(), Terraria.WorldGen.AddGenPasses(), Terraria.GameContent.Biomes.Desert.DesertHive.AddTileVariance(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_001_Slimes_GenerateItemInsideBody(), Terraria.NPC.AI_002_FloatingEye(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_AttemptToPlayIdleAnimationsForPets(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_007_TryForcingSitting(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_009_MagicMissiles_Old(), Terraria.Projectile.AI_010(), Terraria.Projectile.AI_015_Flails_Dust(), Terraria.Projectile.AI_016(), Terraria.Projectile.AI_019_Spears(), Terraria.Projectile.AI_019_Spears_Old(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_045_Golem(), Terraria.NPC.AI_047_GolemFist(), Terraria.Projectile.AI_047_MagnetSphere_TryAttacking(), Terraria.Projectile.AI_061_FishingBobber(), Terraria.Projectile.AI_061_FishingBobber_GiveItemToPlayer(), Terraria.Projectile.AI_062(), Terraria.NPC.AI_065_Butterflies(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_067_TigerSpecialAttack(), Terraria.NPC.AI_069_DukeFishron(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.Projectile.AI_099_2(), Terraria.Projectile.AI_100_Medusa(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.Projectile.AI_111_DryadsWard(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_114_Dragonflies(), Terraria.NPC.AI_115_LadyBugs(), Terraria.NPC.AI_116_WaterStriders(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_118_Seahorses(), Terraria.NPC.AI_119_Dandelion(), Terraria.NPC.AI_120_HallowBoss_DoMagicEffect(), Terraria.NPC.AI_121_QueenSlime(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.NPC.AI_123_Deerclops_ShootRubbleUp(), Terraria.Projectile.AI_130_FlameBurstTower(), Terraria.Projectile.AI_131_FlameBurstShot(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.Projectile.AI_136_BetsyBreath(), Terraria.Projectile.AI_137_LightningAura(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.AI_142_MonkStaffT2And3(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_147_Explosion(), Terraria.Projectile.AI_151_SuperStar(), Terraria.Projectile.AI_152_SuperStarSlash(), Terraria.Projectile.AI_153_ToiletPop(), Terraria.Projectile.AI_155_MysticSnakeCoil(), Terraria.Projectile.AI_155_SpawnRopeIn(), Terraria.Projectile.AI_156_Think(), Terraria.Projectile.AI_157_SharpTears(), Terraria.Projectile.AI_159_PaperAirplanes(), Terraria.Projectile.AI_160_Kites(), Terraria.Projectile.AI_162_TigerPounce(), Terraria.Projectile.AI_163_Chum(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_166_Dove(), Terraria.Projectile.AI_168_FirstFractal(), Terraria.Projectile.AI_169_Smolstars(), Terraria.Projectile.AI_175_TitaniumStormShards(), Terraria.Projectile.AI_176_EdgyLightning(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_178_FireExplosion(), Terraria.Projectile.AI_179_FairyQueenLance(), Terraria.Projectile.AI_181_FairyQueenRangedItemShot(), Terraria.Projectile.AI_184_BadTorchLuck(), Terraria.Projectile.AI_186_PrincessWeapon(), Terraria.Projectile.AI_189_Volcano(), Terraria.Projectile.AI_190_NightsEdge(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.Projectile.AI_192_JuminoAnimation(), Terraria.Projectile.AI_193_Flamethrower(), Terraria.Projectile.AI_194_HorsemanPumpkin(), Terraria.Projectile.AI_195_JimsDrone(), Terraria.NPC.AI_87_BigMimic_FireStuffCannonBurst(), Terraria.NPC.AI_87_BigMimic_ShootItem(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.Main.AnglerQuestSwap(), Terraria.Main.AnimateTiles(), Terraria.Main.AnimateTiles_CritterCages(), Terraria.Player.ApplyEquipFunctional(), Terraria.Player.ApplyLifeAndOrMana(), Terraria.Player.ApplyNPCOnHitEffects(), Terraria.Player.ApplyPotionDelay(), Terraria.Player.ApplyTouchDamage(), Terraria.Player.ApplyWilsonBeard(), Terraria.Player.ArmorSetDye(), Terraria.GameContent.Skies.MartianSky.Ufo.AssignNewBehavior(), Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.AttemptClaim(), Terraria.Lang.BartenderChat(), Terraria.Player.beeDamage(), Terraria.Player.beeType(), Terraria.NPC.BloodNautilus_CallForHelp(), Terraria.Projectile.BoulderExplosion(), Terraria.Main.ChangeRain(), Terraria.GameContent.Events.Sandstorm.ChangeSeverityIntentions(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.CheckChand(), Terraria.Player.CheckCrackedBrickBreak(), Terraria.NPC.checkDead(), Terraria.NPC.CheckDrowning(), Terraria.Player.CheckDrowning(), Terraria.Player.CheckForGoodTeleportationSpot(), Terraria.Item.CheckLavaDeath(), Terraria.WorldGen.CheckOrb(), Terraria.HitTile.HitTileObject.Clear(), Terraria.NPC.Collision_WaterCollision(), Terraria.WorldGen.ConvertSkyIslands(), Terraria.Lang.CreateDeathMessage(), Terraria.Projectile.CreateGroundExplosion(), Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel(), Terraria.Projectile.Damage(), Terraria.Main.DamageVar(), Terraria.Player.DashMovement(), Terraria.Main.DedServ(), Terraria.Item.DespawnIfMeetingConditions(), Terraria.Player.DoBootsEffect_PlaceFlowersOnTile(), Terraria.NPC.DoDeathEvents(), Terraria.NPC.DoDeathEvents_DropBossPotionsAndHearts(), Terraria.Player.DoEyebrellaRainEffect(), Terraria.Projectile.DoRainbowCrystalStaffExplosion(), Terraria.Main.DoUpdate(), Terraria.GameContent.Drawing.TileDrawing.DrawAnimatedTile_AdjustForVisionChangers(), Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.Main.DrawItem(), Terraria.Main.DrawMenu(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.Main.DrawNPCDirect_Inner(), Terraria.Main.DrawProj_DrawNormalProjs(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.Main.DrawSunAndMoon(), Terraria.Main.DrawSurfaceBG_Mushroom(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip(), Terraria.Player.DropCoins(), Terraria.Projectile.DropGeodeLoot(), Terraria.Player.DropItem(), Terraria.GameContent.ItemDropRules.CommonCode.DropItem(), Terraria.GameContent.ItemDropRules.CommonCode.DropItemForEachInteractingPlayerOnThePlayer(), Terraria.WorldGen.dropMeteor(), Terraria.Player.DropTombstone(), Terraria.NPC.DropTombstoneTownNPC(), Terraria.Lang.DyeTraderQuestChat(), Terraria.GameContent.Drawing.TileDrawing.EmitAlchemyHerbParticles(), Terraria.GameContent.Events.Sandstorm.EmitDust(), Terraria.Projectile.EmitEnchantmentVisualsAt(), Terraria.GameContent.Drawing.TileDrawing.EmitLiquidDrops(), Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf(), Terraria.Player.EmitMaxManaEffect(), Terraria.GameContent.Drawing.TileDrawing.EmitTreeLeaves(), Terraria.Player.ExtractinatorUse(), Terraria.NPC.FairyEffects(), Terraria.Star.Fall(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FillRooms(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindBoulderTrapSpots(), Terraria.NPC.FindCattailTop(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpots(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindExplosiveTrapSpots(), Terraria.Player.FindSharpTearsSpot(), Terraria.NPC.FindTreeBranch(), Terraria.WorldGen.FinishRemixWorld(), Terraria.Projectile.FishingCheck(), Terraria.Projectile.FishingCheck_RollDropLevels(), Terraria.Projectile.FishingCheck_RollEnemySpawns(), Terraria.Projectile.FishingCheck_RollItemDrop(), Terraria.WorldGen.Spread.Gem(), Terraria.WorldGen.gemCave(), Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.Generate(), Terraria.GameContent.Skies.PartySky.GenerateBalloons(), Terraria.GameContent.Skies.LanternSky.GenerateLanterns(), Terraria.GameContent.Skies.SlimeSky.GenerateSlimes(), Terraria.WorldGen.GenerateWorld(), Terraria.Player.GetAnglerReward_Bait(), Terraria.Player.GetAnglerReward_Decoration(), Terraria.Player.GetAnglerReward_MainReward(), Terraria.Player.GetAnglerReward_Money(), Terraria.NPC.GetChat(), Terraria.Player.GetDyeTraderReward(), Terraria.NPC.getNewNPCName(), Terraria.WorldGen.GetNextJungleChestItem(), Terraria.Item.GetPickedUpByMonsters_Money(), Terraria.WorldBuilding.WorldGenRange.GetRandom(), Terraria.GameContent.FlexibleTileWand.OptionBucket.GetRandomOption(), Terraria.Item.GetShimmered(), Terraria.Projectile.ghostHurt(), Terraria.Main.GUIChatDrawInner(), Terraria.Projectile.HandleMovement(), Terraria.WorldGen.hardUpdateWorld(), Terraria.NPC.HasLuckTextForWizard(), Terraria.NPC.HasSpecialEventText(), Terraria.Player.HorizontalMovement(), Terraria.Player.HorsemansBlade_SpawnPumpkin(), Terraria.Player.Hurt(), Terraria.Player.Hurt(), Terraria.NPC.IdleSounds(), Terraria.Main.Initialize(), Terraria.GameContent.Skies.MartianSky.ZipBehavior.InitializeUfo(), Terraria.GameContent.Skies.MartianSky.HoverBehavior.InitializeUfo(), Terraria.Player.IsAmmoFreeThisShot(), Terraria.Player.ItemCheck_ApplyHoldStyle_Inner(), Terraria.Player.ItemCheck_ApplyPetBuffs(), Terraria.Player.ItemCheck_ApplyUseStyle_Inner(), Terraria.Player.ItemCheck_CheckFishingBobber_PickAndConsumeBait(), Terraria.Player.ItemCheck_CheckFishingBobber_PullBobber(), Terraria.Player.ItemCheck_CutTiles(), Terraria.Player.ItemCheck_EmitDrinkParticles(), Terraria.Player.ItemCheck_EmitFoodParticles(), Terraria.Player.ItemCheck_EmitHeldItemLight(), Terraria.Player.ItemCheck_EmitUseVisuals(), Terraria.Player.ItemCheck_GetMeleeHitbox(), Terraria.Player.ItemCheck_Inner(), Terraria.Player.ItemCheck_ManageRightClickFeatures_ShieldRaise(), Terraria.Player.ItemCheck_MeleeHitPVP(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_UseTeleportRod(), Terraria.Projectile.Kill(), Terraria.Player.KillMe(), Terraria.WorldGen.KillTile_GetItemDrops(), Terraria.WorldGen.KillTile_GetTreeDrops(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.WorldGen.KillTile_ShouldDropSeeds(), Terraria.WorldGen.LaunchRocketSmall(), Terraria.IO.WorldFile.LoadHeader(), Terraria.Initializers.AssetInitializer.LoadSplashAssets(), Terraria.IO.WorldFile.LoadWorld(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.Player.MakeFloorDust(), Terraria.NPC.MakeTransitionEffectsForTextureChanges(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.WorldGen.mayanTrap(), Terraria.WorldGen.meteor(), Terraria.Player.ModifyFlexibleWandPlacementInfo(), Terraria.Item.MoveInWorld(), Terraria.WorldGen.neonMossBiome(), Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Item.NewItem_Inner(), Terraria.Main.NewLightning(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.Utils.Next(), Terraria.Utils.NextFromCollection< T >(), Terraria.Utils.NextFromList< T >(), Terraria.Star.NightSetup(), Terraria.Player.NinjaDodge(), Terraria.NPC.NPCLoot_DropCommonLifeAndMana(), Terraria.NPC.NPCLoot_DropHeals(), Terraria.NPC.NPCLoot_DropMoney(), Terraria.Main.oldDrawWater(), Terraria.Player.OnHit_Inner(), Terraria.Player.OnHurt_Part3(), Terraria.WorldGen.OrePatch(), Terraria.WorldGen.paintCoatEffect(), Terraria.GameContent.Biomes.Desert.ChambersEntrance.Place(), Terraria.GameContent.Biomes.HiveBiome.Place(), Terraria.GameContent.Biomes.Desert.ChambersEntrance.PlaceAt(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceBiomeSpecificPriorityTool(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceBiomeSpecificTool(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceChests(), Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea(), Terraria.WorldGen.PlaceOasis(), Terraria.Player.PlaceThing_PaintScrapper_LongMoss(), Terraria.Player.PlaceThing_Tiles_PlaceIt_AdjustPlants(), Terraria.Player.PlaceThing_Tiles_PlaceIt_GetLegacyTileStyle(), Terraria.WorldGen.placeTrap(), Terraria.Player.PlayerFrame(), Terraria.Utils.PoofOfSmoke(), Terraria.Main.PostContentLoadInitialize(), Terraria.WorldGen.PrefixItemFromOptions(), Terraria.Player.ProcessHitAgainstNPC(), Terraria.Projectile.ProjLight(), Terraria.Player.QuickBuff(), Terraria.Main.randColor(), Terraria.WorldGen.randGem(), Terraria.WorldGen.randGemTile(), Terraria.WorldGen.randMoss(), Terraria.WorldGen.RandomizeBackgroundBasedOnPlayer(), Terraria.WorldGen.RandomizeBackgrounds(), Terraria.WorldGen.RandomizeCaveBackgrounds(), Terraria.Projectile.RandomizeInsanityShadowFor(), Terraria.WorldGen.RandomizeMoonState(), Terraria.WorldGen.RandomizeTreeStyle(), Terraria.GameContent.TreeTopsInfo.RandomizeTreeStyle(), Terraria.WorldGen.RandomizeWeather(), Terraria.NPC.ReflectProjectile(), Terraria.NPC.ReleaseNPC(), Terraria.GameContent.Skies.PartySky.ResetBalloon(), Terraria.GameContent.Skies.LanternSky.ResetLantern(), Terraria.Player.RocketBootVisuals(), Terraria.Player.RollLuck(), Terraria.WorldGen.RollRandomForestBGStyle(), Terraria.Cloud.RollRareCloud(), Terraria.Utils.SelectRandom< T >(), Terraria.Projectile.SetDefaults(), Terraria.NPC.setFireFlyChance(), Terraria.WorldGen.SetGemTreeDrops(), Terraria.WorldGen.SetVanityTreeDrops(), Terraria.WorldGen.ShakeTree(), Terraria.WorldGen.ShellPile(), Terraria.Item.ShimmerEffect(), Terraria.NPC.SlimeRainSpawns(), Terraria.WorldGen.SmashAltar(), Terraria.Main.snowing(), Terraria.GameContent.AmbientWindSystem.SpawnAirborneCloud(), Terraria.NPC.SpawnFaelings(), Terraria.Player.SpawnFastRunParticles(), Terraria.GameContent.AmbientWindSystem.SpawnFloorCloud(), Terraria.Player.SpawnHallucination(), Terraria.NPC.SpawnNPC(), Terraria.NPC.SpawnNPC_CheckToSpawnRockGolem(), Terraria.NPC.SpawnNPC_GetGemBunnyToSpawn(), Terraria.NPC.SpawnNPC_GetGemSquirrelToSpawn(), Terraria.NPC.SpawnNPC_SpawnLavaBaitCritters(), Terraria.NPC.SpawnOnPlayer(), Terraria.WorldGen.SpawnPlanteraThorns(), Terraria.NPC.SpawnStardustMark_StardustTower(), Terraria.NPC.SpawnStardustMark_StardustWorm(), Terraria.WorldGen.SpawnThingsFromPot(), Terraria.WorldGen.SpawnTravelNPC(), Terraria.Projectile.SpawnWebs(), Terraria.WorldGen.Spread.Spider(), Terraria.Player.SporeSac(), Terraria.Main.StartInvasion(), Terraria.Main.StartRain(), Terraria.GameContent.Events.Sandstorm.StartSandstorm(), Terraria.Main.StartSlimeRain(), Terraria.WorldGen.Statue(), Terraria.Player.StatusFromNPC(), Terraria.Projectile.StatusNPC(), Terraria.Projectile.StatusPlayer(), Terraria.Projectile.StatusPvP(), Terraria.Player.StatusToNPC(), Terraria.Player.StatusToPlayerPvP(), Terraria.Player.StickyMovement(), Terraria.NPC.StingerExplosion(), Terraria.WorldGen.StonePatch(), Terraria.Main.StopSlimeRain(), Terraria.NPC.StrikeNPC(), Terraria.Projectile.SummonMonkGhast(), Terraria.Main.TeleportEffect(), Terraria.GameContent.AmbientWindSystem.TestAirCloud(), Terraria.Player.TileInteractionsUse(), Terraria.Player.TorchAttack(), Terraria.NPC.TransformVisuals(), Terraria.WorldGen.TreeGrowFX_AshShake(), Terraria.WorldGen.TriggerLunarApocalypse(), Terraria.Player.TryDroppingSingleItem(), Terraria.Player.TryGettingDevArmor(), Terraria.WorldGen.TryGrowingAbigailsFlower(), Terraria.WorldGen.TrySpawningTownNPC(), Terraria.GameContent.AmbientWindSystem.TrySpawningWind(), Terraria.Player.TryToPoop(), Terraria.GameContent.Biomes.DeadMansChestBiome.TurnGoldChestIntoDeadMansChest(), Terraria.Cloud.Update(), Terraria.Gore.Update(), Terraria.Player.RabbitOrderFrameHelper.Update(), Terraria.GameContent.Skies.LanternSky.Update(), Terraria.GameContent.Skies.PartySky.Update(), Terraria.GameContent.Skies.SlimeSky.Update(), Terraria.GameContent.Skies.VortexSky.Update(), Terraria.Player.Update(), Terraria.Projectile.Update(), Terraria.Gore.UpdateAmbientAirborneCloud(), Terraria.Player.UpdateArmorSets(), Terraria.Main.UpdateAudio_DecideOnNewMusic(), Terraria.Player.UpdateBuffs(), Terraria.Main.updateCloudLayer(), Terraria.Cloud.UpdateClouds(), Terraria.Main.UpdateDragonflyJarFrame(), Terraria.Dust.UpdateDust(), Terraria.Gore.UpdateFogMachineCloud(), Terraria.Player.UpdateHairDyeDust(), Terraria.Item.UpdateItem(), Terraria.Item.UpdateItem_VisualEffects(), Terraria.Player.UpdateLifeRegen(), Terraria.Gore.UpdateLightningBunnySparks(), Terraria.Player.UpdateManaRegen(), Terraria.Main.UpdateMenu(), Terraria.NPC.UpdateNPC_BuffApplyVFX(), Terraria.NPC.UpdateNPC_CastLights(), Terraria.NPC.UpdateNPC_CritterSounds(), Terraria.NPC.UpdateNPC_Inner(), Terraria.NPC.UpdateNPC_SoulDrainDebuff(), Terraria.NPC.UpdateNPC_TeleportVisuals(), Terraria.Main.UpdateOwlCageFrame(), Terraria.Player.UpdateTeleportVisuals(), Terraria.GameContent.Events.Sandstorm.UpdateTime(), Terraria.Main.UpdateTime(), Terraria.Main.UpdateTime_SpawnTownNPCs(), Terraria.Main.UpdateTime_StartDay(), Terraria.Main.UpdateTime_StartNight(), Terraria.Main.UpdateWeather(), Terraria.WorldGen.UpdateWorld_Inner(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), Terraria.Projectile.VanillaAI(), Terraria.NPC.VanillaAI_Inner(), Terraria.NPC.VanillaFindFrame(), Terraria.NPC.VanillaHitEffect(), Terraria.Player.WingAirVisuals(), and Terraria.Player.WingFrame().