TModLoader: Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadMods
DownloadMods() [1/2]
Task< bool > Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadMods (IEnumerable< ModDownloadItem > mods) inline package
Definition at line 424 of file UIModBrowser.cs.
    {
        return DownloadMods(mods, 10007, delegate
        {
            reloadOnExit = true;
        }, delegate
        {
            newModInstalled = true;
            _ = ModLoader.autoReloadAndEnableModsLeavingModBrowser;
        });
    }
References Terraria.ModLoader.ModLoader.autoReloadAndEnableModsLeavingModBrowser, Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadMods(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.newModInstalled, and Terraria.ModLoader.UI.ModBrowser.UIModBrowser.reloadOnExit.
Referenced by Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadMods(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadModsAndReturnToBrowser(), and Terraria.ModLoader.UI.Interface.ModLoaderMenus().