TModLoader: Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ModListStartLoading
ModListStartLoading()
void Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ModListStartLoading (AsyncProviderState state) inline private
    {
        _browserStatus.SetCurrentState(state);
        _reloadButton.SetText(Language.GetText("tModLoader.MBCancelLoading"));
    }
References Terraria.ModLoader.UI.ModBrowser.UIModBrowser._browserStatus, Terraria.ModLoader.UI.ModBrowser.UIModBrowser._reloadButton, Terraria.Localization.Language.GetText(), Terraria.ModLoader.UI.ModBrowser.UIBrowserStatus.SetCurrentState(), and Terraria.GameContent.UI.Elements.UITextPanel< T >.SetText().
Referenced by Terraria.ModLoader.UI.ModBrowser.UIModBrowser.InitializeInteractions().