TModLoader: Terraria.ModLoader.UI.ModBrowser.UIModBrowser.InitializeInteractions
InitializeInteractions()
void Terraria.ModLoader.UI.ModBrowser.UIModBrowser.InitializeInteractions () inline private
    {
        _reloadButton.OnLeftClick += ReloadList;
        _backButton.OnLeftClick += delegate
        {
            HandleBackButtonUsage();
        };
        _clearButton.OnLeftClick += ClearTextFilters;
        _downloadAllButton.OnLeftClick += DownloadAllFilteredMods;
        _updateAllButton.OnLeftClick += UpdateAllMods;
        ModList.OnStartLoading += ModListStartLoading;
        ModList.OnFinished += ModListFinished;
        _filterTextBoxBackground.OnRightClick += delegate
        {
            FilterTextBox.Text = "";
        };
        FilterTextBox.OnRightClick += delegate
        {
            FilterTextBox.Text = "";
        };
        FilterTextBox.OnTextChange += UpdateHandler;
        foreach (UICycleImage categoryButton in CategoryButtons)
        {
            categoryButton.OnStateChanged += UpdateHandler;
        }
    }
References Terraria.ModLoader.UI.ModBrowser.UIModBrowser.CategoryButtons, Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ClearTextFilters(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadAllFilteredMods(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.HandleBackButtonUsage(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ModListFinished(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ModListStartLoading(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ReloadList(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.UpdateAllMods(), and Terraria.ModLoader.UI.ModBrowser.UIModBrowser.UpdateHandler().
Referenced by Terraria.ModLoader.UI.ModBrowser.UIModBrowser.OnInitialize().