TModLoader: Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadMods
DownloadMods() [2/2]
static async Task< bool > Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadMods (IEnumerable< ModDownloadItem > mods, int previousMenuId, Action setReloadRequred = null, Action< ModDownloadItem > onNewModInstalled = null) inline static package
Downloads all ModDownloadItems provided.
    {
        HashSet<ModDownloadItem> set = mods.ToHashSet();
        Interface.modBrowser.SocialBackend.GetDependenciesRecursive(set);
        List<ModDownloadItem> fullList = ModDownloadItem.NeedsInstallOrUpdate(set).ToList();
        if (!fullList.Any())
        {
            return true;
        }
        HashSet<string> downloadedList = new HashSet<string>();
        try
        {
            UIWorkshopDownload ui = new UIWorkshopDownload();
            Main.menuMode = 888;
            Main.MenuUI.SetState(ui);
            await Task.Yield();
            foreach (ModDownloadItem mod in fullList)
            {
                bool isInstalled = mod.IsInstalled;
                if (ModLoader.TryGetMod(mod.ModName, out var loadedMod))
                {
                    loadedMod.Close();
                    mod.Installed = null;
                    setReloadRequred?.Invoke();
                }
                Interface.modBrowser.SocialBackend.DownloadItem(mod, ui);
                if (!isInstalled)
                {
                    onNewModInstalled?.Invoke(mod);
                }
                downloadedList.Add(mod.ModName);
            }
            return true;
        }
        catch (Exception e)
        {
            LogModBrowserException(e, previousMenuId);
            return false;
        }
        finally
        {
            ModOrganizer.LocalModsChanged(downloadedList, isDeletion: false);
        }
    }
References Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.IsInstalled, Terraria.ModLoader.Core.ModOrganizer.LocalModsChanged(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.LogModBrowserException(), Terraria.Main.MenuUI, Terraria.ModLoader.UI.Interface.modBrowser, Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.ModName, Terraria.ModLoader.UI.ModBrowser.ModDownloadItem.NeedsInstallOrUpdate(), Terraria.UI.UserInterface.SetState(), and Terraria.ModLoader.ModLoader.TryGetMod().