TModLoader: Terraria.ModLoader.UI.ModBrowser.UIModBrowser.PopulateModBrowser
PopulateModBrowser()
void Terraria.ModLoader.UI.ModBrowser.UIModBrowser.PopulateModBrowser () inline package
    {
        _firstLoad = false;
        SpecialModPackFilter = null;
        SpecialModPackFilterTitle = null;
        SetHeading(Language.GetText("tModLoader.MenuModBrowser"));
        ModList.SetEnumerable(SocialBackend.QueryBrowser(FilterParameters));
    }
References Terraria.ModLoader.UI.ModBrowser.UIModBrowser._firstLoad, Terraria.ModLoader.UI.ModBrowser.UIModBrowser.FilterParameters, Terraria.Localization.Language.GetText(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ModList, Terraria.Social.Base.SocialBrowserModule.QueryBrowser(), Terraria.ModLoader.UI.Elements.UIAsyncList< TResource, TUIElement >.SetEnumerable(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.SetHeading(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.SocialBackend, Terraria.ModLoader.UI.ModBrowser.UIModBrowser.SpecialModPackFilter, and Terraria.ModLoader.UI.ModBrowser.UIModBrowser.SpecialModPackFilterTitle.
Referenced by Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ClearTextFilters(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.OnActivate(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ReloadList(), and Terraria.ModLoader.UI.ModBrowser.UIModBrowser.Update().