TModLoader: Terraria.ModLoader.UI.ModBrowser.UIModBrowser.OnInitialize
OnInitialize()
override void Terraria.ModLoader.UI.ModBrowser.UIModBrowser.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 536 of file UIModBrowser.cs.
    {
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0261: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        //IL_026a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_0273: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        //IL_027c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0282: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0302: Unknown result type (might be due to invalid IL or missing references)
        //IL_0308: Unknown result type (might be due to invalid IL or missing references)
        //IL_030b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0311: Unknown result type (might be due to invalid IL or missing references)
        //IL_038e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0398: Unknown result type (might be due to invalid IL or missing references)
        //IL_039d: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03be: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_043f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0449: Unknown result type (might be due to invalid IL or missing references)
        //IL_044e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0453: Unknown result type (might be due to invalid IL or missing references)
        //IL_0458: Unknown result type (might be due to invalid IL or missing references)
        //IL_0462: Unknown result type (might be due to invalid IL or missing references)
        //IL_0469: Unknown result type (might be due to invalid IL or missing references)
        //IL_046f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0472: Unknown result type (might be due to invalid IL or missing references)
        //IL_0478: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0504: Unknown result type (might be due to invalid IL or missing references)
        //IL_0509: Unknown result type (might be due to invalid IL or missing references)
        //IL_0513: Unknown result type (might be due to invalid IL or missing references)
        //IL_051a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0520: Unknown result type (might be due to invalid IL or missing references)
        //IL_0523: Unknown result type (might be due to invalid IL or missing references)
        //IL_0529: Unknown result type (might be due to invalid IL or missing references)
        _rootElement = new UIElement
        {
            Width =
            {
                Percent = 0.8f
            },
            MaxWidth = UICommon.MaxPanelWidth,
            Top =
            {
                Pixels = 220f
            },
            Height =
            {
                Pixels = -220f,
                Percent = 1f
            },
            HAlign = 0.5f
        };
        _backgroundElement = new UIPanel
        {
            Width =
            {
                Percent = 1f
            },
            Height =
            {
                Pixels = -110f,
                Percent = 1f
            },
            BackgroundColor = UICommon.MainPanelBackground,
            PaddingTop = 0f
        };
        _rootElement.Append(_backgroundElement);
        ModList = new UIAsyncList_ModDownloadItem
        {
            Width =
            {
                Pixels = -25f,
                Percent = 1f
            },
            Height =
            {
                Pixels = -50f,
                Percent = 1f
            },
            Top =
            {
                Pixels = 50f
            },
            ListPadding = 5f
        };
        UIScrollbar listScrollbar = new UIScrollbar
        {
            Height =
            {
                Pixels = -50f,
                Percent = 1f
            },
            Top =
            {
                Pixels = 50f
            },
            HAlign = 1f
        }.WithView(100f, 1000f);
        _backgroundElement.Append(listScrollbar);
        _backgroundElement.Append(ModList);
        ModList.SetScrollbar(listScrollbar);
        HeaderTextPanel = new UITextPanel<LocalizedText>(Language.GetText("tModLoader.MenuModBrowser"), 0.8f, large: true)
        {
            HAlign = 0.5f,
            Top =
            {
                Pixels = -35f
            },
            BackgroundColor = UICommon.DefaultUIBlue
        }.WithPadding(15f);
        _backgroundElement.Append(HeaderTextPanel);
        _reloadButton = new UITextPanel<LocalizedText>(Language.GetText("tModLoader.MBCancelLoading"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.5f
            },
            Height =
            {
                Pixels = 25f
            },
            VAlign = 1f,
            Top =
            {
                Pixels = -65f
            }
        }.WithFadedMouseOver();
        _backButton = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.5f
            },
            Height =
            {
                Pixels = 25f
            },
            VAlign = 1f,
            Top =
            {
                Pixels = -20f
            }
        }.WithFadedMouseOver();
        _clearButton = new UITextPanel<string>(Language.GetTextValue("tModLoader.MBClearSpecialFilter", "??"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.5f
            },
            Height =
            {
                Pixels = 25f
            },
            HAlign = 1f,
            VAlign = 1f,
            Top =
            {
                Pixels = -65f
            },
            BackgroundColor = Color.Purple * 0.7f
        }.WithFadedMouseOver(Color.Purple, Color.Purple * 0.7f);
        _updateAllButton = new UITextPanel<LocalizedText>(Language.GetText("tModLoader.MBUpdateAll"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.5f
            },
            Height =
            {
                Pixels = 25f
            },
            HAlign = 1f,
            VAlign = 1f,
            Top =
            {
                Pixels = -20f
            },
            BackgroundColor = Color.Orange * 0.7f
        }.WithFadedMouseOver(Color.Orange, Color.Orange * 0.7f);
        _downloadAllButton = new UITextPanel<LocalizedText>(Language.GetText("tModLoader.MBDownloadAll"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.5f
            },
            Height =
            {
                Pixels = 25f
            },
            HAlign = 1f,
            VAlign = 1f,
            Top =
            {
                Pixels = -20f
            },
            BackgroundColor = Color.Azure * 0.7f
        }.WithFadedMouseOver(Color.Azure, Color.Azure * 0.7f);
        NoModsFoundText = new UIText(Language.GetTextValue("tModLoader.MBNoModsFound"))
        {
            HAlign = 0.5f
        }.WithPadding(15f);
        FilterTextBox = new UIInputTextField(Language.GetTextValue("tModLoader.ModsTypeToSearch"))
        {
            Top =
            {
                Pixels = 5f
            },
            Left =
            {
                Pixels = -160f,
                Percent = 1f
            },
            Width =
            {
                Pixels = 100f
            },
            Height =
            {
                Pixels = 20f
            }
        };
        _upperMenuContainer = new UIElement
        {
            Width =
            {
                Percent = 1f
            },
            Height =
            {
                Pixels = 32f
            },
            Top =
            {
                Pixels = 10f
            }
        };
        _filterTextBoxBackground = new UIPanel
        {
            Top =
            {
                Percent = 0f
            },
            Left =
            {
                Pixels = -170f,
                Percent = 1f
            },
            Width =
            {
                Pixels = 135f
            },
            Height =
            {
                Pixels = 40f
            }
        };
        SortModeFilterToggle = new UIBrowserFilterToggle<ModBrowserSortMode>(0, 0)
        {
            Left = new StyleDimension
            {
                Pixels = 8f
            }
        };
        UpdateFilterToggle = new UIBrowserFilterToggle<UpdateFilter>(34, 0)
        {
            Left = new StyleDimension
            {
                Pixels = 44f
            }
        };
        SearchFilterToggle = new UIBrowserFilterToggle<SearchFilter>(68, 0)
        {
            Left = new StyleDimension
            {
                Pixels = 545f
            }
        };
        ModSideFilterToggle = new UIBrowserFilterToggle<ModSideFilter>(170, 0)
        {
            Left = new StyleDimension
            {
                Pixels = 80f
            }
        };
        SearchFilterToggle.SetCurrentState(SearchFilter.Name);
        UpdateFilterToggle.SetCurrentState(UpdateFilter.All);
        ModSideFilterToggle.SetCurrentState(ModSideFilter.All);
        SortModeFilterToggle.SetCurrentState(ModBrowserSortMode.RecentlyUpdated);
        _browserStatus = new UIBrowserStatus
        {
            VAlign = 1f,
            Top =
            {
                Pixels = -72f
            },
            Left =
            {
                Pixels = 545f
            }
        };
        _rootElement.Append(_browserStatus);
        _rootElement.Append(_reloadButton);
        _rootElement.Append(_backButton);
        CategoryButtons.Add(SortModeFilterToggle);
        _upperMenuContainer.Append(SortModeFilterToggle);
        CategoryButtons.Add(UpdateFilterToggle);
        _upperMenuContainer.Append(UpdateFilterToggle);
        CategoryButtons.Add(ModSideFilterToggle);
        _upperMenuContainer.Append(ModSideFilterToggle);
        CategoryButtons.Add(SearchFilterToggle);
        _upperMenuContainer.Append(SearchFilterToggle);
        InitializeInteractions();
        _upperMenuContainer.Append(_filterTextBoxBackground);
        _upperMenuContainer.Append(FilterTextBox);
        _backgroundElement.Append(_upperMenuContainer);
        Append(_rootElement);
    }
References Terraria.ModLoader.UI.ModBrowser.UIModBrowser._backButton, Terraria.ModLoader.UI.ModBrowser.UIModBrowser._backgroundElement, Terraria.ModLoader.UI.ModBrowser.UIModBrowser._browserStatus, Terraria.ModLoader.UI.ModBrowser.UIModBrowser._clearButton, Terraria.ModLoader.UI.ModBrowser.UIModBrowser._downloadAllButton, Terraria.ModLoader.UI.ModBrowser.UIModBrowser._filterTextBoxBackground, Terraria.ModLoader.UI.ModBrowser.UIModBrowser._reloadButton, Terraria.ModLoader.UI.ModBrowser.UIModBrowser._rootElement, Terraria.ModLoader.UI.ModBrowser.UIModBrowser._updateAllButton, Terraria.ModLoader.UI.ModBrowser.UIModBrowser._upperMenuContainer, Terraria.UI.UIElement.Append(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.CategoryButtons, Terraria.ModLoader.UI.ModBrowser.UIModBrowser.FilterTextBox, Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.HAlign, Terraria.ModLoader.UI.ModBrowser.UIModBrowser.HeaderTextPanel, Terraria.UI.UIElement.Height, Terraria.ModLoader.UI.ModBrowser.UIModBrowser.InitializeInteractions(), Terraria.UI.UIElement.Left, Terraria.ModLoader.UI.UICommon.MainPanelBackground, Terraria.ModLoader.UI.UICommon.MaxPanelWidth, Terraria.UI.UIElement.MaxWidth, Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ModList, Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ModSideFilterToggle, Terraria.ModLoader.UI.ModBrowser.UIModBrowser.NoModsFoundText, Terraria.UI.UIElement.PaddingTop, Terraria.ModLoader.UI.ModBrowser.UIModBrowser.SearchFilterToggle, Terraria.ModLoader.UI.ModBrowser.UIBrowserFilterToggle< T >.SetCurrentState(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.SortModeFilterToggle, Terraria.UI.UIElement.Top, Terraria.ModLoader.UI.ModBrowser.UIModBrowser.UpdateFilterToggle, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.