TModLoader: Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ReloadList
ReloadList()
void Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ReloadList (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 307 of file UIModBrowser.cs.
    {
        if (Loading)
        {
            SoundEngine.PlaySound(in SoundID.MenuOpen);
            ModList.Cancel();
        }
        else
        {
            SoundEngine.PlaySound(in SoundID.MenuOpen);
            PopulateModBrowser();
        }
    }
References Terraria.ModLoader.UI.Elements.UIAsyncList< TResource, TUIElement >.Cancel(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.Loading, Terraria.ID.SoundID.MenuOpen, Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ModList, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.ModLoader.UI.ModBrowser.UIModBrowser.PopulateModBrowser().
Referenced by Terraria.ModLoader.UI.ModBrowser.UIModBrowser.InitializeInteractions().