TModLoader: Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadModsAndReturnToBrowser
DownloadModsAndReturnToBrowser()
async void Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadModsAndReturnToBrowser (List< ModPubId_t > modIds) inline package
Enqueues a list of mods, if found on the browser (also used for ModPacks)
    {
        List<string> missingMods;
        List<ModDownloadItem> downloadsQueried = SocialBackend.DirectQueryItems(new QueryParameters
        {
            searchModIds = modIds.ToArray()
        }, out missingMods);
        if (!(await DownloadMods(downloadsQueried)))
        {
            return;
        }
        if (missingMods.Any())
        {
            Interface.errorMessage.Show(Language.GetTextValue("tModLoader.MBModsNotFoundOnline", string.Join(",", missingMods)), 10007);
            return;
        }
        Main.QueueMainThreadAction(delegate
        {
            Main.menuMode = 10007;
        });
    }
References Terraria.Social.Base.SocialBrowserModule.DirectQueryItems(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadMods(), Terraria.ModLoader.UI.Interface.errorMessage, Terraria.Localization.Language.GetTextValue(), Terraria.Main.QueueMainThreadAction(), and Terraria.ModLoader.UI.ModBrowser.UIModBrowser.SocialBackend.
Referenced by Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadAllFilteredMods(), and Terraria.ModLoader.UI.ModBrowser.UIModBrowser.UpdateAllMods().