TModLoader: Terraria.ModLoader.DustLoader.GetDust
GetDust()
static ModDust Terraria.ModLoader.DustLoader.GetDust (int type) inline static
Gets the ModDust instance with the given type. Returns null if no ModDust with the given type exists.
Definition at line 18 of file DustLoader.cs.
    {
        if (type < DustID.Count || type >= DustCount)
        {
            return null;
        }
        return dusts[type - DustID.Count];
    }
References Terraria.ID.DustID.Count, Terraria.ModLoader.DustLoader.DustCount, and Terraria.ModLoader.DustLoader.dusts.
Referenced by Terraria.Main.DrawDust(), Terraria.Dust.GetAlpha(), Terraria.ModLoader.ModContent.GetModDust(), Terraria.ModLoader.DustLoader.SetupDust(), Terraria.ModLoader.DustLoader.SetupUpdateType(), and Terraria.Dust.UpdateDust().