TModLoader: Terraria.ModLoader.LocalizationLoader.LoadTranslations
LoadTranslations()
static List<(string key, string value)> Terraria.ModLoader.LocalizationLoader.LoadTranslations (Mod mod, GameCulture culture) inline static private
Definition at line 228 of file LocalizationLoader.cs.
    {
        if (mod.File == null)
        {
            return new List<(string, string)>();
        }
        try
        {
            List<(string, string)> flattened = new List<(string, string)>();
            foreach (TmodFile.FileEntry translationFile in mod.File.Where((TmodFile.FileEntry entry) => Path.GetExtension(entry.Name) == ".hjson"))
            {
                var (fileCulture, prefix) = GetCultureAndPrefixFromPath(translationFile.Name);
                if (fileCulture != culture)
                {
                    continue;
                }
                using Stream stream = mod.File.GetStream(translationFile);
                using StreamReader streamReader = new StreamReader(stream, Encoding.UTF8, detectEncodingFromByteOrderMarks: true);
                string translationFileContents = streamReader.ReadToEnd();
                string modpath = Path.Combine(mod.Name, translationFile.Name).Replace('/', '\\');
                if (changedFiles.Select(((string Mod, string fileName) x) => Path.Join(x.Mod, x.fileName)).Contains(modpath))
                {
                    string path2 = Path.Combine(ModCompile.ModSourcePath, modpath);
                    if (File.Exists(path2))
                    {
                        try
{
                            translationFileContents = File.ReadAllText(path2);
                        }
                        catch (Exception)
{
                        }
                    }
                }
                string jsonString;
                try
                {
                    jsonString = ((object)HjsonValue.Parse(translationFileContents)).ToString();
                }
                catch (Exception e)
                {
                    throw new Exception("The localization file \"" + translationFile.Name + "\" is malformed and failed to load: ", e);
                }
                foreach (JToken t in ((JToken)JObject.Parse(jsonString)).SelectTokens("$..*"))
                {
                    if (t.HasValues)
                    {
                        continue;
                    }
                    JObject obj = (JObject)(object)((t is JObject) ? t : null);
                    if (obj != null && ((JContainer)obj).Count == 0)
                    {
                        continue;
                    }
                    string path = "";
                    JToken current = t;
                    for (JToken parent = (JToken)(object)t.Parent; parent != null; parent = (JToken)(object)parent.Parent)
                    {
                        JProperty property = (JProperty)(object)((parent is JProperty) ? parent : null);
                        string text;
                        if (property == null)
{
                            JArray array = (JArray)(object)((parent is JArray) ? parent : null);
                            text = ((array == null) ? path : (array.IndexOf(current) + ((path == string.Empty) ? string.Empty : ("." + path))));
                        }
                        else
{
                            text = property.Name + ((path == string.Empty) ? string.Empty : ("." + path));
                        }
                        path = text;
                        current = parent;
                    }
                    path = path.Replace(".$parentVal", "");
                    if (!string.IsNullOrWhiteSpace(prefix))
                    {
                        path = prefix + "." + path;
                    }
                    flattened.Add((path, ((object)t).ToString()));
                }
            }
            return flattened;
        }
        catch (Exception ex2)
        {
            ex2.Data["mod"] = mod.Name;
            throw;
        }
    }
References Terraria.ModLoader.LocalizationLoader.changedFiles, Terraria.ModLoader.LocalizationLoader.culture, Terraria.ModLoader.Mod.File, Terraria.ModLoader.LocalizationLoader.GetCultureAndPrefixFromPath(), Terraria.ModLoader.Core.TmodFile.GetStream(), Terraria.ModLoader.Core.ModCompile.ModSourcePath, and Terraria.ModLoader.Mod.Name.
Referenced by Terraria.ModLoader.LocalizationLoader.Autoload(), Terraria.ModLoader.LocalizationLoader.GetLocalizationCounts(), and Terraria.ModLoader.LocalizationLoader.LoadModTranslations().