TModLoader: Terraria.ModLoader.LocalizationLoader.LocalizationEntry
LocalizationEntry()
record Terraria.ModLoader.LocalizationLoader.LocalizationEntry (string key, string value, string comment, JsonType type = 0) inline
    {
        [CompilerGenerated]
        protected virtual bool PrintMembers(StringBuilder builder)
        {
            //IL_005e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0063: Unknown result type (might be due to invalid IL or missing references)
            RuntimeHelpers.EnsureSufficientExecutionStack();
            builder.Append("key = ");
            builder.Append((object?)key);
            builder.Append(", value = ");
            builder.Append((object?)value);
            builder.Append(", comment = ");
            builder.Append((object?)comment);
            builder.Append(", type = ");
            JsonType val = type;
            builder.Append(((object)(JsonType)(ref val)).ToString());
            return true;
        }
        [CompilerGenerated]
        public void Deconstruct(out string key, out string value, out string comment, out JsonType type)
        {
            //IL_001b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0021: Expected I4, but got Unknown
            key = this.key;
            value = this.value;
            comment = this.comment;
            type = (JsonType)(int)this.type;
        }
    }
Referenced by Terraria.ModLoader.LocalizationLoader.AddEntryToHJSON(), Terraria.ModLoader.LocalizationLoader.LocalizationFileToHjsonText(), Terraria.ModLoader.LocalizationLoader.LongestMatchingPrefix(), Terraria.ModLoader.LocalizationLoader.ParseLocalizationEntries(), and Terraria.ModLoader.LocalizationLoader.UpdateLocalizationFilesForMod().