TModLoader: Terraria.ModLoader.LocalizationLoader.LocalizationFileToHjsonText
LocalizationFileToHjsonText()
static string Terraria.ModLoader.LocalizationLoader.LocalizationFileToHjsonText (LocalizationFile baseFile, Dictionary< string, string > localizationsForCulture) inline static private
Definition at line 558 of file LocalizationLoader.cs.
    {
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Invalid comparison between Unknown and I4
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Invalid comparison between Unknown and I4
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Invalid comparison between Unknown and I4
        Dictionary<string, int> prefixCounts = new Dictionary<string, int>();
        foreach (LocalizationEntry entry4 in baseFile.Entries)
        {
            if ((int)entry4.type != 2)
            {
                string[] splitKey2 = GetKeyFromFilePrefixAndEntry(baseFile, entry4).Split(".");
                for (int k = 0; k < splitKey2.Length; k++)
                {
                    string partialKey2 = string.Join(".", splitKey2.Take(k + 1));
                    prefixCounts.TryGetValue(partialKey2, out var count4);
                    prefixCounts[partialKey2] = count4 + 1;
                }
            }
        }
        for (int i = baseFile.Entries.Count - 1; i >= 0; i--)
        {
            LocalizationEntry entry3 = baseFile.Entries[i];
            if ((int)entry3.type == 2)
            {
                string key2 = GetKeyFromFilePrefixAndEntry(baseFile, entry3);
                if (prefixCounts.TryGetValue(key2, out var count3) && count3 <= 1)
                {
                    baseFile.Entries.RemoveAt(i);
                }
            }
            if ((int)entry3.type == 0)
            {
                string key = GetKeyFromFilePrefixAndEntry(baseFile, entry3);
                if (prefixCounts.TryGetValue(key, out var count2) && count2 > 1)
                {
                    baseFile.Entries[i] = entry3 with
                    {
                        key = entry3.key + ".$parentVal"
                    };
                }
            }
        }
        CommentedWscJsonObject rootObject = new CommentedWscJsonObject();
        foreach (LocalizationEntry entry2 in baseFile.Entries)
        {
            CommentedWscJsonObject parent2 = rootObject;
            string[] splitKey = GetKeyFromFilePrefixAndEntry(baseFile, entry2).Split(".");
            string finalKey = splitKey[^1];
            for (int j = 0; j < splitKey.Length - 1; j++)
            {
                string partialKey = string.Join(".", splitKey.Take(j + 1));
                if (prefixCounts.TryGetValue(partialKey, out var count) && count <= 1)
                {
                    finalKey = string.Join(".", splitKey.Skip(j));
                    break;
                }
                string l = splitKey[j];
                if (((JsonValue)parent2).ContainsKey(l))
                {
                    parent2 = (CommentedWscJsonObject)(object)((JsonValue)parent2)[l];
                    continue;
                }
                CommentedWscJsonObject newParent = new CommentedWscJsonObject();
                ((JsonObject)parent2).Add(l, (JsonValue)(object)newParent);
                parent2 = newParent;
            }
            if (entry2.value == null && (int)entry2.type == 2)
            {
                if (!((JsonValue)parent2).ContainsKey(splitKey[^1]))
                {
                    PlaceCommentAboveNewEntry(entry2, parent2);
                    ((JsonObject)parent2).Add(splitKey[^1], (JsonValue)(object)new CommentedWscJsonObject());
                }
                continue;
            }
            string realKey = entry2.key.Replace(".$parentVal", "");
            if (!localizationsForCulture.TryGetValue(realKey, out var value))
            {
                parent2.CommentedOut.Add(finalKey);
                value = entry2.value;
            }
            PlaceCommentAboveNewEntry(entry2, parent2);
            ((JsonObject)parent2).Add(finalKey, JsonValue.op_Implicit(value));
        }
        return ((JsonValue)(object)rootObject).ToFancyHjsonString() + Environment.NewLine;
        static string GetKeyFromFilePrefixAndEntry(LocalizationFile baseLocalizationFileEntry, LocalizationEntry entry)
        {
            string key3 = entry.key;
            if (!string.IsNullOrWhiteSpace(baseLocalizationFileEntry.prefix))
            {
                key3 = key3.Substring(baseLocalizationFileEntry.prefix.Length + 1);
            }
            return key3;
        }
        static void PlaceCommentAboveNewEntry(LocalizationEntry entry, CommentedWscJsonObject parent)
        {
            if (((JsonValue)parent).Count == 0)
            {
                ((WscJsonObject)parent).Comments[""] = entry.comment;
            }
            else
            {
                string actualCommentKey = ((JsonObject)parent).Keys.Last();
                ((WscJsonObject)parent).Comments[actualCommentKey] = entry.comment;
            }
        }
    }
References Terraria.Count, Terraria.ModLoader.Environment, Terraria.ModLoader.LocalizationLoader.LocalizationEntry(), and Terraria.ModLoader.LocalizationLoader.LocalizationFile().
Referenced by Terraria.ModLoader.LocalizationLoader.UpdateLocalizationFilesForMod().