TModLoader: Terraria.ModLoader.LocalizationLoader.UpdateLocalizationFilesForMod
UpdateLocalizationFilesForMod()
static void Terraria.ModLoader.LocalizationLoader.UpdateLocalizationFilesForMod (Mod mod, string outputPath = null, GameCulture specificCulture = null) inline static private
Definition at line 340 of file LocalizationLoader.cs.
    {
        //IL_0244: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_0255: Expected O, but got Unknown
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0287: Expected O, but got Unknown
        HashSet<GameCulture> desiredCultures = new HashSet<GameCulture>();
        if (specificCulture != null)
        {
            desiredCultures.Add(specificCulture);
        }
        List<Mod> mods = new List<Mod> { mod };
        string sourceFolder = outputPath ?? Path.Combine(ModCompile.ModSourcePath, mod.Name);
        if (!Directory.Exists(sourceFolder))
        {
            return;
        }
        string localBuiltTModFile = Path.Combine(ModLoader.ModPath, mod.Name + ".tmod");
        if (outputPath == null && !File.Exists(localBuiltTModFile))
        {
            return;
        }
        DateTime modLastModified = File.GetLastWriteTime(mod.File.path);
        if (mod.TranslationForMods != null)
        {
            foreach (string translationForMod in mod.TranslationForMods)
            {
                ModLoader.TryGetMod(translationForMod, out var otherMod);
                if (otherMod == null)
                {
                    return;
                }
                mods.Add(otherMod);
                DateTime otherModLastModified = File.GetLastWriteTime(otherMod.File.path);
                if (otherModLastModified > modLastModified)
                {
                    modLastModified = otherModLastModified;
                }
            }
        }
        Dictionary<GameCulture, List<LocalizationFile>> localizationFilesByCulture = new Dictionary<GameCulture, List<LocalizationFile>>();
        Dictionary<string, string> localizationFileContentsByPath = new Dictionary<string, string>();
        foreach (Mod inputMod in mods)
        {
            foreach (TmodFile.FileEntry translationFile in inputMod.File.Where((TmodFile.FileEntry entry) => Path.GetExtension(entry.Name) == ".hjson"))
            {
                using Stream stream = inputMod.File.GetStream(translationFile);
                using StreamReader streamReader = new StreamReader(stream, Encoding.UTF8, detectEncodingFromByteOrderMarks: true);
                string translationFileContents = streamReader.ReadToEnd();
                (GameCulture culture, string prefix) cultureAndPrefixFromPath = GetCultureAndPrefixFromPath(translationFile.Name);
                GameCulture culture4 = cultureAndPrefixFromPath.culture;
                string prefix2 = cultureAndPrefixFromPath.prefix;
                string fixedFileName = translationFile.Name;
                if (culture4 == GameCulture.DefaultCulture && !fixedFileName.Contains("en-US"))
                {
                    fixedFileName = Path.Combine(Path.GetDirectoryName(fixedFileName), "en-US.hjson").Replace("\\", "/");
                }
                if (!localizationFilesByCulture.TryGetValue(culture4, out var fileList2))
                {
                    fileList2 = (localizationFilesByCulture[culture4] = new List<LocalizationFile>());
                }
                if (inputMod == mod)
                {
                    desiredCultures.Add(culture4);
                    if (!localizationFileContentsByPath.ContainsKey(translationFile.Name))
                    {
                        localizationFileContentsByPath[translationFile.Name] = translationFileContents;
                    }
                }
                JsonValue jsonValueEng;
                try
                {
                    jsonValueEng = HjsonValue.Parse(translationFileContents, new HjsonOptions
                    {
                        KeepWsc = true
                    });
                }
                catch (Exception e2)
                {
                    throw new Exception("The localization file \"" + translationFile.Name + "\" is malformed and failed to load: ", e2);
                }
                List<LocalizationEntry> entries = ParseLocalizationEntries((WscJsonObject)jsonValueEng, prefix2);
                if (!fileList2.Any((LocalizationFile x) => x.path == fixedFileName))
                {
                    fileList2.Add(new LocalizationFile(fixedFileName, prefix2, entries));
                    continue;
                }
                LocalizationFile localizationFile = fileList2.First((LocalizationFile x) => x.path == fixedFileName);
                foreach (LocalizationEntry entry4 in entries)
                {
                    if (!localizationFile.Entries.Exists((LocalizationEntry x) => x.key == entry4.key))
                    {
                        localizationFile.Entries.Add(entry4);
                    }
                }
            }
        }
        if (!localizationFilesByCulture.TryGetValue(GameCulture.DefaultCulture, out var baseLocalizationFiles))
        {
            localizationFilesByCulture[GameCulture.DefaultCulture] = (baseLocalizationFiles = new List<LocalizationFile>());
            desiredCultures.Add(GameCulture.DefaultCulture);
            string prefix = "Mods." + mod.Name;
            string translationFileName = "Localization/en-US_" + prefix + ".hjson";
            baseLocalizationFiles.Add(new LocalizationFile(translationFileName, prefix, new List<LocalizationEntry>()));
        }
        Dictionary<string, List<LocalizationEntry>> duplicates = (from w in baseLocalizationFiles.SelectMany((LocalizationFile f) => f.Entries)
            where (int)w.type == 0
            select w into x
            group x by x.key into c
            where c.Count() > 1
            select c).ToDictionary((IGrouping<string, LocalizationEntry> g) => g.Key, (IGrouping<string, LocalizationEntry> g) => g.ToList());
        foreach (LocalizationFile baseLocalizationFile in baseLocalizationFiles.OrderByDescending((LocalizationFile x) => x.path.Length))
        {
            List<LocalizationEntry> toRemove = new List<LocalizationEntry>();
            foreach (LocalizationEntry entry3 in baseLocalizationFile.Entries)
            {
                if (duplicates.ContainsKey(entry3.key))
                {
                    duplicates.Remove(entry3.key);
                    toRemove.Add(entry3);
                }
            }
            foreach (LocalizationEntry entry2 in toRemove)
            {
                baseLocalizationFile.Entries.Remove(entry2);
            }
        }
        HashSet<string> baseLocalizationKeys = baseLocalizationFiles.SelectMany((LocalizationFile f) => f.Entries.Select((LocalizationEntry e) => e.key)).ToHashSet();
        foreach (LocalizedText translation in LanguageManager.Instance._localizedTexts.Values)
        {
            if (translation.Key.StartsWith("Mods." + mod.Name + ".") && !baseLocalizationKeys.Contains(translation.Key))
            {
                LocalizationEntry newEntry = new LocalizationEntry(translation.Key, translation.Value, null, (JsonType)0);
                AddEntryToHJSON(FindHJSONFileForKey(baseLocalizationFiles, newEntry.key), newEntry.key, newEntry.value);
            }
        }
        IEnumerable<GameCulture> targetCultures = desiredCultures.ToList();
        if (specificCulture != null)
        {
            targetCultures = new GameCulture[1] { specificCulture };
            if (!localizationFilesByCulture.TryGetValue(specificCulture, out var fileList))
            {
                fileList = (localizationFilesByCulture[specificCulture] = new List<LocalizationFile>());
            }
        }
        foreach (GameCulture culture3 in targetCultures)
        {
            IEnumerable<LocalizationEntry> enumerable = localizationFilesByCulture[culture3].SelectMany((LocalizationFile f) => f.Entries);
            Dictionary<string, string> localizationsForCulture = new Dictionary<string, string>();
            foreach (LocalizationEntry localizationEntry in enumerable)
            {
                if (localizationEntry.value != null)
                {
                    string key = localizationEntry.key;
                    if (key.EndsWith(".$parentVal"))
                    {
                        key = key.Replace(".$parentVal", "");
                    }
                    localizationsForCulture[key] = localizationEntry.value;
                }
            }
            foreach (LocalizationFile item in baseLocalizationFiles)
            {
                string hjsonContents = LocalizationFileToHjsonText(item, localizationsForCulture).ReplaceLineEndings();
                string outputFileName = GetPathForCulture(item, culture3);
                string outputFilePath = Path.Combine(sourceFolder, outputFileName);
                DateTime dateTime = File.GetLastWriteTime(outputFilePath);
                if (!localizationFileContentsByPath.TryGetValue(outputFileName, out var existingFileContents) || (existingFileContents.ReplaceLineEndings() != hjsonContents && dateTime < modLastModified) || specificCulture != null)
                {
                    Directory.CreateDirectory(Path.GetDirectoryName(outputFilePath));
                    File.WriteAllText(outputFilePath, hjsonContents);
                    changedMods.Add(mod.Name);
                }
            }
        }
        HashSet<string> outputPathsForAllLangs = localizationFilesByCulture.Keys.SelectMany((GameCulture culture) => baseLocalizationFiles.Select((LocalizationFile baseFile) => GetPathForCulture(baseFile, culture))).ToHashSet();
        foreach (string name in localizationFileContentsByPath.Keys.Except(outputPathsForAllLangs))
        {
            string originalPath = Path.Combine(sourceFolder, name);
            string newPath = originalPath + ".legacy";
            if (File.Exists(originalPath))
            {
                File.Move(originalPath, newPath);
            }
        }
        if (specificCulture != null)
        {
            return;
        }
        Dictionary<GameCulture, int> localizationCounts = new Dictionary<GameCulture, int>();
        foreach (GameCulture culture2 in targetCultures)
        {
            int countNonTrivialEntries = (from x in localizationFilesByCulture[culture2].SelectMany((LocalizationFile f) => f.Entries).ToList()
                where HasTextThatNeedsLocalization(x.value)
                select x).Count();
            localizationCounts.Add(culture2, countNonTrivialEntries);
        }
        localizationEntriesCounts[mod.Name] = localizationCounts;
        string translationsNeededPath = Path.Combine(sourceFolder, "Localization", "TranslationsNeeded.txt");
        if (File.Exists(translationsNeededPath))
        {
            int countMaxEntries = localizationCounts.DefaultIfEmpty().Max((KeyValuePair<GameCulture, int> x) => x.Value);
            string neededText = string.Join(Environment.NewLine, from x in localizationCounts
                orderby x.Key.LegacyId
                select $"{x.Key.Name}, {x.Value}/{countMaxEntries}, {(float)x.Value / (float)countMaxEntries:0%}, missing {countMaxEntries - x.Value}") + Environment.NewLine;
            if (File.ReadAllText(translationsNeededPath).ReplaceLineEndings() != neededText.ReplaceLineEndings())
            {
                File.WriteAllText(translationsNeededPath, neededText);
            }
        }
    }
References Terraria.Localization.LanguageManager._localizedTexts, Terraria.ModLoader.LocalizationLoader.AddEntryToHJSON(), Terraria.ModLoader.LocalizationLoader.changedMods, Terraria.Count, Terraria.ModLoader.LocalizationLoader.culture, Terraria.Localization.GameCulture.DefaultCulture, Terraria.ModLoader.Environment, Terraria.ModLoader.Mod.File, Terraria.ModLoader.LocalizationLoader.FindHJSONFileForKey(), Terraria.ModLoader.LocalizationLoader.GetCultureAndPrefixFromPath(), Terraria.ModLoader.LocalizationLoader.GetPathForCulture(), Terraria.ModLoader.LocalizationLoader.HasTextThatNeedsLocalization(), Terraria.Localization.LanguageManager.Instance, Terraria.ModLoader.LocalizationLoader.localizationEntriesCounts, Terraria.ModLoader.LocalizationLoader.LocalizationEntry(), Terraria.ModLoader.LocalizationLoader.LocalizationFile(), Terraria.ModLoader.LocalizationLoader.LocalizationFileToHjsonText(), Terraria.ModLoader.ModLoader.ModPath, Terraria.ModLoader.Core.ModCompile.ModSourcePath, Terraria.ModLoader.Mod.Name, Terraria.ModLoader.LocalizationLoader.ParseLocalizationEntries(), Terraria.ModLoader.Core.TmodFile.path, Terraria.ModLoader.Mod.TranslationForMods, and Terraria.ModLoader.ModLoader.TryGetMod().
Referenced by Terraria.ModLoader.LocalizationLoader.ExtractLocalizationFiles(), and Terraria.ModLoader.LocalizationLoader.UpdateLocalizationFiles().