TModLoader: Terraria.ModLoader.LocalizationLoader.FindHJSONFileForKey
FindHJSONFileForKey()
static LocalizationFile Terraria.ModLoader.LocalizationLoader.FindHJSONFileForKey (List< LocalizationFile > files, string key) inline static private
Definition at line 715 of file LocalizationLoader.cs.
    {
        int levelFound = -1;
        LocalizationFile best = null;
        foreach (LocalizationFile file in files)
        {
            if (string.IsNullOrWhiteSpace(file.prefix) || key.StartsWith(file.prefix))
            {
                int level = LongestMatchingPrefix(file, key);
                if (level > levelFound)
                {
                    levelFound = level;
                    best = file;
                }
            }
        }
        if (best == null)
        {
            best = new LocalizationFile("en-US.hjson", "", new List<LocalizationEntry>());
            files.Add(best);
        }
        return best;
    }
References Terraria.ModLoader.LocalizationLoader.LocalizationFile(), and Terraria.ModLoader.LocalizationLoader.LongestMatchingPrefix().
Referenced by Terraria.ModLoader.LocalizationLoader.UpdateLocalizationFilesForMod().