TModLoader: Terraria.Initializers.UILinksInitializer.HandleOptionsSpecials
HandleOptionsSpecials()
static void Terraria.Initializers.UILinksInitializer.HandleOptionsSpecials () inline static
Definition at line 1904 of file UILinksInitializer.cs.
    {
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        //IL_01be: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_022c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_025a: Unknown result type (might be due to invalid IL or missing references)
        //IL_025f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0290: Unknown result type (might be due to invalid IL or missing references)
        //IL_0291: Unknown result type (might be due to invalid IL or missing references)
        //IL_0296: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_038f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0394: Unknown result type (might be due to invalid IL or missing references)
        //IL_0395: Unknown result type (might be due to invalid IL or missing references)
        //IL_039a: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0402: Unknown result type (might be due to invalid IL or missing references)
        //IL_042b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0430: Unknown result type (might be due to invalid IL or missing references)
        //IL_0431: Unknown result type (might be due to invalid IL or missing references)
        //IL_0436: Unknown result type (might be due to invalid IL or missing references)
        //IL_045f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0464: Unknown result type (might be due to invalid IL or missing references)
        //IL_0465: Unknown result type (might be due to invalid IL or missing references)
        //IL_046a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0490: Unknown result type (might be due to invalid IL or missing references)
        //IL_0495: Unknown result type (might be due to invalid IL or missing references)
        //IL_0496: Unknown result type (might be due to invalid IL or missing references)
        //IL_049b: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_05eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0619: Unknown result type (might be due to invalid IL or missing references)
        //IL_061e: Unknown result type (might be due to invalid IL or missing references)
        //IL_061f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0624: Unknown result type (might be due to invalid IL or missing references)
        //IL_064d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0652: Unknown result type (might be due to invalid IL or missing references)
        //IL_0653: Unknown result type (might be due to invalid IL or missing references)
        //IL_0658: Unknown result type (might be due to invalid IL or missing references)
        //IL_0681: Unknown result type (might be due to invalid IL or missing references)
        //IL_0686: Unknown result type (might be due to invalid IL or missing references)
        //IL_0687: Unknown result type (might be due to invalid IL or missing references)
        //IL_068c: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ee: Unknown result type (might be due to invalid IL or missing references)
        switch (UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE)
        {
        case 1:
            Main.bgScroll = (int)HandleSliderHorizontalInput(Main.bgScroll, 0f, 100f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 1f);
            Main.caveParallax = 1f - (float)Main.bgScroll / 500f;
            break;
        case 2:
            Main.musicVolume = HandleSliderHorizontalInput(Main.musicVolume, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
            break;
        case 3:
            Main.soundVolume = HandleSliderHorizontalInput(Main.soundVolume, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
            break;
        case 4:
            Main.ambientVolume = HandleSliderHorizontalInput(Main.ambientVolume, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
            break;
        case 5:
        {
            float hBar = Main.hBar;
            float num3 = (Main.hBar = HandleSliderHorizontalInput(hBar, 0f, 1f));
            if (hBar != num3)
            {
                switch (Main.menuMode)
                {
                case 17:
                    Main.player[Main.myPlayer].hairColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 18:
                    Main.player[Main.myPlayer].eyeColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 19:
                    Main.player[Main.myPlayer].skinColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 21:
                    Main.player[Main.myPlayer].shirtColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 22:
                    Main.player[Main.myPlayer].underShirtColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 23:
                    Main.player[Main.myPlayer].pantsColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 24:
                    Main.player[Main.myPlayer].shoeColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 25:
                    Main.mouseColorSlider.Hue = num3;
                    break;
                case 252:
                    Main.mouseBorderColorSlider.Hue = num3;
                    break;
                }
                SoundEngine.PlaySound(12);
            }
            break;
        }
        case 6:
        {
            float sBar = Main.sBar;
            float num2 = (Main.sBar = HandleSliderHorizontalInput(sBar, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX));
            if (sBar != num2)
            {
                switch (Main.menuMode)
                {
                case 17:
                    Main.player[Main.myPlayer].hairColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 18:
                    Main.player[Main.myPlayer].eyeColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 19:
                    Main.player[Main.myPlayer].skinColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 21:
                    Main.player[Main.myPlayer].shirtColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 22:
                    Main.player[Main.myPlayer].underShirtColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 23:
                    Main.player[Main.myPlayer].pantsColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 24:
                    Main.player[Main.myPlayer].shoeColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 25:
                    Main.mouseColorSlider.Saturation = num2;
                    break;
                case 252:
                    Main.mouseBorderColorSlider.Saturation = num2;
                    break;
                }
                SoundEngine.PlaySound(12);
            }
            break;
        }
        case 7:
        {
            float lBar3 = Main.lBar;
            float min = 0.15f;
            if (Main.menuMode == 252)
            {
                min = 0f;
            }
            Main.lBar = HandleSliderHorizontalInput(lBar3, min, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX);
            float lBar2 = Main.lBar;
            if (lBar3 != lBar2)
            {
                switch (Main.menuMode)
                {
                case 17:
                    Main.player[Main.myPlayer].hairColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 18:
                    Main.player[Main.myPlayer].eyeColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 19:
                    Main.player[Main.myPlayer].skinColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 21:
                    Main.player[Main.myPlayer].shirtColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 22:
                    Main.player[Main.myPlayer].underShirtColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 23:
                    Main.player[Main.myPlayer].pantsColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 24:
                    Main.player[Main.myPlayer].shoeColor = (Main.selColor = Main.hslToRgb(Main.hBar, Main.sBar, Main.lBar));
                    break;
                case 25:
                    Main.mouseColorSlider.Luminance = lBar2;
                    break;
                case 252:
                    Main.mouseBorderColorSlider.Luminance = lBar2;
                    break;
                }
                SoundEngine.PlaySound(12);
            }
            break;
        }
        case 8:
        {
            float aBar = Main.aBar;
            float num4 = (Main.aBar = HandleSliderHorizontalInput(aBar, 0f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX));
            if (aBar != num4)
            {
                if (Main.menuMode == 252)
                {
                    Main.mouseBorderColorSlider.Alpha = num4;
                }
                SoundEngine.PlaySound(12);
            }
            break;
        }
        case 9:
        {
            bool left = PlayerInput.Triggers.Current.Left;
            bool right = PlayerInput.Triggers.Current.Right;
            if (PlayerInput.Triggers.JustPressed.Left || PlayerInput.Triggers.JustPressed.Right)
            {
                SomeVarsForUILinkers.HairMoveCD = 0;
            }
            else if (SomeVarsForUILinkers.HairMoveCD > 0)
            {
                SomeVarsForUILinkers.HairMoveCD--;
            }
            if (SomeVarsForUILinkers.HairMoveCD == 0 && (left || right))
            {
                if (left)
                {
                    Main.PendingPlayer.hair--;
                }
                if (right)
                {
                    Main.PendingPlayer.hair++;
                }
                SomeVarsForUILinkers.HairMoveCD = 12;
            }
            int num = 51;
            if (Main.PendingPlayer.hair >= num)
            {
                Main.PendingPlayer.hair = 0;
            }
            if (Main.PendingPlayer.hair < 0)
            {
                Main.PendingPlayer.hair = num - 1;
            }
            break;
        }
        case 10:
            Main.GameZoomTarget = HandleSliderHorizontalInput(Main.GameZoomTarget, 1f, 2f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
            break;
        case 11:
            Main.UIScale = HandleSliderHorizontalInput(Main.UIScaleWanted, 0.5f, 2f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.35f);
            Main.temporaryGUIScaleSlider = Main.UIScaleWanted;
            break;
        case 12:
            Main.MapScale = HandleSliderHorizontalInput(Main.MapScale, 0.5f, 1f, PlayerInput.CurrentProfile.InterfaceDeadzoneX, 0.7f);
            break;
        }
    }
References Terraria.Main.aBar, Terraria.Main.ambientVolume, Terraria.Main.bgScroll, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.Main.GameZoomTarget, Terraria.Initializers.UILinksInitializer.SomeVarsForUILinkers.HairMoveCD, Terraria.Initializers.UILinksInitializer.HandleSliderHorizontalInput(), Terraria.Main.hBar, Terraria.Main.hslToRgb(), Terraria.Main.lBar, Terraria.Main.MapScale, Terraria.Main.menuMode, Terraria.Main.musicVolume, Terraria.Main.myPlayer, Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE, Terraria.Main.PendingPlayer, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.sBar, Terraria.Main.soundVolume, Terraria.GameInput.PlayerInput.Triggers, and Terraria.Main.UIScaleWanted.
Referenced by Terraria.Initializers.UILinksInitializer.Load().