TModLoader: Terraria.GameContent.Skies.AmbientSky.SeagullsGroupSkyEntity.CreateGroup
CreateGroup()
static List< SeagullsGroupSkyEntity > Terraria.GameContent.Skies.AmbientSky.SeagullsGroupSkyEntity.CreateGroup (Player player, FastRandom random) inline static
Definition at line 717 of file AmbientSky.cs.
        {
            //IL_0032: Unknown result type (might be due to invalid IL or missing references)
            //IL_0036: Unknown result type (might be due to invalid IL or missing references)
            //IL_003c: Unknown result type (might be due to invalid IL or missing references)
            //IL_003f: Invalid comparison between Unknown and I4
            //IL_006a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0045: Unknown result type (might be due to invalid IL or missing references)
            //IL_0051: Unknown result type (might be due to invalid IL or missing references)
            //IL_0121: Unknown result type (might be due to invalid IL or missing references)
            //IL_0127: Unknown result type (might be due to invalid IL or missing references)
            //IL_012c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0158: Unknown result type (might be due to invalid IL or missing references)
            //IL_017a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0184: Unknown result type (might be due to invalid IL or missing references)
            //IL_0189: Unknown result type (might be due to invalid IL or missing references)
            //IL_018e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0195: Unknown result type (might be due to invalid IL or missing references)
            //IL_0197: Unknown result type (might be due to invalid IL or missing references)
            //IL_01a0: Unknown result type (might be due to invalid IL or missing references)
            //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
            //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
            List<SeagullsGroupSkyEntity> list = new List<SeagullsGroupSkyEntity>();
            int num = 100;
            int num2 = random.Next(5, 9);
            float num3 = 100f;
            VirtualCamera virtualCamera = new VirtualCamera(player);
            SpriteEffects spriteEffects = (SpriteEffects)(!(Main.WindForVisuals > 0f));
            Vector2 vector = default(Vector2);
            if ((int)spriteEffects == 1)
            {
                vector.X = virtualCamera.Position.X + virtualCamera.Size.X + (float)num;
            }
            else
            {
                vector.X = virtualCamera.Position.X - (float)num;
            }
            vector.Y = random.NextFloat() * ((float)Main.worldSurface * 16f - 1600f - 2400f) + 2400f;
            float num4 = random.NextFloat() * 2f + 1f;
            int num5 = random.Next(30, 61) * 60;
            Vector2 vector2 = default(Vector2);
            ((Vector2)(ref vector2))._002Ector(random.NextFloat() * 0.5f + 0.5f, random.NextFloat() * 0.5f + 0.5f);
            Vector2 targetOffset = new Vector2(random.NextFloat() * 2f - 1f, random.NextFloat() * 2f - 1f) * num3;
            for (int i = 0; i < num2; i++)
            {
                SeagullsGroupSkyEntity seagullsGroupSkyEntity = new SeagullsGroupSkyEntity(player, random);
                seagullsGroupSkyEntity.Depth = num4 + random.NextFloat() * 0.5f;
                seagullsGroupSkyEntity.Position = vector + new Vector2(random.NextFloat() * 20f - 10f, random.NextFloat() * 3f) * 50f;
                seagullsGroupSkyEntity.Effects = spriteEffects;
                seagullsGroupSkyEntity.SetPositionInWorldBasedOnScreenSpace(seagullsGroupSkyEntity.Position);
                seagullsGroupSkyEntity.LifeTime = num5 + random.Next(301);
                seagullsGroupSkyEntity.SetMagnetization(vector2 * (random.NextFloat() * 0.3f + 0.85f) * 0.05f, targetOffset);
                list.Add(seagullsGroupSkyEntity);
            }
            return list;
        }
References Terraria.GameContent.Skies.AmbientSky.SeagullsGroupSkyEntity.SeagullsGroupSkyEntity(), Terraria.Utilities.FastRandom.Next(), Terraria.Utilities.FastRandom.NextFloat(), Terraria.Main.WindForVisuals, and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.Skies.AmbientSky.Spawn().