TModLoader: Terraria.ModLoader.Config.UI.PropertyFieldWrapper.GetValue
GetValue()
object Terraria.ModLoader.Config.UI.PropertyFieldWrapper.GetValue (object obj) inline
    {
        if (fieldInfo != null)
        {
            return fieldInfo.GetValue(obj);
        }
        return propertyInfo.GetValue(obj, null);
    }
References Terraria.ModLoader.Config.UI.PropertyFieldWrapper.fieldInfo, and Terraria.ModLoader.Config.UI.PropertyFieldWrapper.propertyInfo.
Referenced by Terraria.ModLoader.Config.UI.ConfigElement< T >.GetObject(), Terraria.ModLoader.Config.UI.ConfigElement< T >.OnBind(), and Terraria.ModLoader.Config.UI.UIModConfig.WrapIt().