TModLoader: Terraria.ModLoader.IO.MapIO.ReadModMap
ReadModMap()
static void Terraria.ModLoader.IO.MapIO.ReadModMap (BinaryReader reader) inline static package
Definition at line 96 of file MapIO.cs.
    {
        IDictionary<ushort, ushort> table = new Dictionary<ushort, ushort>();
        ushort count = reader.ReadUInt16();
        for (ushort i = 0; i < count; i++)
        {
            ushort type = reader.ReadUInt16();
            bool num = reader.ReadBoolean();
            string modName = reader.ReadString();
            string name = reader.ReadString();
            ushort option = reader.ReadUInt16();
            ushort newType = 0;
            ModWall wall;
            if (num)
            {
                if (ModContent.TryFind<ModTile>(modName, name, out var tile))
                {
                    if (option >= MapLoader.modTileOptions(tile.Type))
                    {
                        option = 0;
                    }
                    newType = (ushort)MapHelper.TileToLookup(tile.Type, option);
                }
            }
            else if (ModContent.TryFind<ModWall>(modName, name, out wall))
            {
                if (option >= MapLoader.modWallOptions(wall.Type))
                {
                    option = 0;
                }
                newType = (ushort)(MapHelper.wallLookup[wall.Type] + option);
            }
            table[type] = newType;
        }
        ReadMapData(reader, table);
    }
References Terraria.ModLoader.MapLoader.modTileOptions(), Terraria.ModLoader.MapLoader.modWallOptions(), Terraria.ModLoader.IO.MapIO.ReadMapData(), Terraria.Map.MapHelper.TileToLookup(), Terraria.ModLoader.ModBlockType.Type, and Terraria.Map.MapHelper.wallLookup.
Referenced by Terraria.ModLoader.IO.MapIO.ReadModFile().