TModLoader: Terraria.ModLoader.IO.MapIO.NextTile
NextTile()
static bool Terraria.ModLoader.IO.MapIO.NextTile (ref int i, ref int j) inline static private
    {
        j++;
        if (j >= Main.maxTilesY)
        {
            j = 0;
            i++;
            if (i >= Main.maxTilesX)
            {
                return false;
            }
        }
        return true;
    }
References Terraria.Main.maxTilesX, and Terraria.Main.maxTilesY.
Referenced by Terraria.ModLoader.IO.MapIO.ReadMapData(), Terraria.ModLoader.IO.MapIO.ReadMapTile(), Terraria.ModLoader.IO.MapIO.WriteMapData(), and Terraria.ModLoader.IO.MapIO.WriteMapTile().