TModLoader: Terraria.ModLoader.IO.MapIO.WriteMapData
WriteMapData()
static void Terraria.ModLoader.IO.MapIO.WriteMapData (BinaryWriter writer) inline static package
    {
        byte skip = 0;
        bool nextModTile = false;
        int i = 0;
        int j = 0;
        do
        {
            MapTile tile = Main.Map[i, j];
            if (tile.Type >= MapHelper.modPosition && tile.Light > 18)
            {
                if (!nextModTile)
                {
                    writer.Write(skip);
                    skip = 0;
                }
                else
                {
                    nextModTile = false;
                }
                WriteMapTile(ref i, ref j, writer, ref nextModTile);
            }
            else
            {
                skip++;
                if (skip == byte.MaxValue)
                {
                    writer.Write(skip);
                    skip = 0;
                }
            }
        }
        while (NextTile(ref i, ref j));
        if (skip > 0)
        {
            writer.Write(skip);
        }
    }
References Terraria.Map.MapTile.Light, Terraria.Main.Map, Terraria.Map.MapHelper.modPosition, Terraria.ModLoader.IO.MapIO.NextTile(), Terraria.Map.MapTile.Type, and Terraria.ModLoader.IO.MapIO.WriteMapTile().
Referenced by Terraria.ModLoader.IO.MapIO.WriteModMap().