TModLoader: Terraria.ModLoader.IO.MapIO.WriteMapTile
WriteMapTile()
static void Terraria.ModLoader.IO.MapIO.WriteMapTile (ref int i, ref int j, BinaryWriter writer, ref bool nextModTile) inline static package
Definition at line 209 of file MapIO.cs.
    {
        MapTile tile = Main.Map[i, j];
        byte flags = 0;
        byte[] data = new byte[9];
        int index = 1;
        data[index] = (byte)tile.Type;
        index++;
        data[index] = (byte)(tile.Type >> 8);
        index++;
        if (tile.Light < byte.MaxValue)
        {
            flags = (byte)(flags | 1u);
            data[index] = tile.Light;
            index++;
        }
        if (tile.Color > 0)
        {
            flags = (byte)(flags | 2u);
            data[index] = tile.Color;
            index++;
        }
        int nextI = i;
        int nextJ = j;
        uint sameCount = 0u;
        while (NextTile(ref nextI, ref nextJ))
        {
            MapTile nextTile = Main.Map[nextI, nextJ];
            if (tile.Equals(ref nextTile) && sameCount < uint.MaxValue)
            {
                sameCount++;
                i = nextI;
                j = nextJ;
                continue;
            }
            if (nextTile.Type >= MapHelper.modPosition && nextTile.Light > 18)
            {
                flags = (byte)(flags | 0x20u);
                nextModTile = true;
            }
            break;
        }
        if (sameCount != 0)
        {
            flags = (byte)(flags | 4u);
            data[index] = (byte)sameCount;
            index++;
            if (sameCount > 255)
            {
                flags = (byte)(flags | 8u);
                data[index] = (byte)(sameCount >> 8);
                index++;
                if (sameCount > 65535)
                {
                    flags = (byte)(flags | 0x10u);
                    data[index] = (byte)(sameCount >> 16);
                    index++;
                    data[index] = (byte)(sameCount >> 24);
                    index++;
                }
            }
        }
        data[0] = flags;
        writer.Write(data, 0, index);
    }
References Terraria.Map.MapTile.Color, Terraria.Map.MapTile.Equals(), Terraria.Map.MapTile.Light, Terraria.Main.Map, Terraria.Map.MapHelper.modPosition, Terraria.ModLoader.IO.MapIO.NextTile(), and Terraria.Map.MapTile.Type.
Referenced by Terraria.ModLoader.IO.MapIO.WriteMapData().