TModLoader: Terraria.ModLoader.IO.MapIO.ReadMapTile
ReadMapTile()
static void Terraria.ModLoader.IO.MapIO.ReadMapTile (ref int i, ref int j, IDictionary< ushort, ushort > table, BinaryReader reader, ref bool nextModTile) inline static package
Definition at line 275 of file MapIO.cs.
    {
        byte flags = reader.ReadByte();
        ushort type = table[reader.ReadUInt16()];
        byte light = (((flags & 1) == 1) ? reader.ReadByte() : byte.MaxValue);
        byte color = (byte)(((flags & 2) == 2) ? reader.ReadByte() : 0);
        MapTile tile = MapTile.Create(type, light, color);
        Main.Map.SetTile(i, j, ref tile);
        if ((flags & 4) == 4)
        {
            uint sameCount = (((flags & 0x10) == 16) ? reader.ReadUInt32() : (((flags & 8) != 8) ? reader.ReadByte() : reader.ReadUInt16()));
            for (uint k = 0u; k < sameCount; k++)
            {
                NextTile(ref i, ref j);
                tile = MapTile.Create(type, light, color);
                Main.Map.SetTile(i, j, ref tile);
            }
        }
        if ((flags & 0x20) == 32)
        {
            nextModTile = true;
        }
    }
References Terraria.Map.MapTile.Create(), Terraria.Main.Map, and Terraria.ModLoader.IO.MapIO.NextTile().
Referenced by Terraria.ModLoader.IO.MapIO.ReadMapData().