TModLoader: Terraria.ModLoader.IO.MapIO.WriteModMap
WriteModMap()
static bool Terraria.ModLoader.IO.MapIO.WriteModMap (BinaryWriter writer) inline static package
Definition at line 46 of file MapIO.cs.
    {
        ISet<ushort> types = new HashSet<ushort>();
        for (int i = 0; i < Main.maxTilesX; i++)
        {
            for (int j = 0; j < Main.maxTilesY; j++)
            {
                ushort type2 = Main.Map[i, j].Type;
                if (type2 >= MapHelper.modPosition)
                {
                    types.Add(type2);
                }
            }
        }
        if (types.Count == 0)
        {
            return false;
        }
        writer.Write((ushort)types.Count);
        foreach (ushort type in types)
        {
            writer.Write(type);
            if (MapLoader.entryToTile.ContainsKey(type))
            {
                ModTile tile = TileLoader.GetTile(MapLoader.entryToTile[type]);
                writer.Write(value: true);
                writer.Write(tile.Mod.Name);
                writer.Write(tile.Name);
                writer.Write((ushort)(type - MapHelper.tileLookup[tile.Type]));
            }
            else if (MapLoader.entryToWall.ContainsKey(type))
            {
                ModWall wall = WallLoader.GetWall(MapLoader.entryToWall[type]);
                writer.Write(value: false);
                writer.Write(wall.Mod.Name);
                writer.Write(wall.Name);
                writer.Write((ushort)(type - MapHelper.wallLookup[wall.Type]));
            }
            else
            {
                writer.Write(value: true);
                writer.Write("");
                writer.Write("");
                writer.Write((ushort)0);
            }
        }
        WriteMapData(writer);
        return true;
    }
References Terraria.ModLoader.MapLoader.entryToTile, Terraria.ModLoader.MapLoader.entryToWall, Terraria.ModLoader.TileLoader.GetTile(), Terraria.ModLoader.WallLoader.GetWall(), Terraria.Main.Map, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.ModLoader.ModType< TEntity, TModType >.Mod, Terraria.Map.MapHelper.modPosition, Terraria.ModLoader.Mod.Name, Terraria.ModLoader.ModType< TEntity, TModType >.Name, Terraria.Map.MapHelper.tileLookup, Terraria.ModLoader.ModBlockType.Type, Terraria.Map.MapHelper.wallLookup, and Terraria.ModLoader.IO.MapIO.WriteMapData().
Referenced by Terraria.ModLoader.IO.MapIO.WriteModFile().