TModLoader: Terraria.GameContent.UI.Elements.UITextPanel.SetText
SetText() [1/2]
void Terraria.GameContent.UI.Elements.UITextPanel< T >.SetText (T text) inline
Definition at line 98 of file UITextPanel.cs.
    {
        SetText(text, _textScale, _isLarge);
    }
References Terraria.GameContent.UI.Elements.UITextPanel< T >._isLarge, Terraria.GameContent.UI.Elements.UITextPanel< T >._textScale, and Terraria.GameContent.UI.Elements.UITextPanel< T >.SetText().
Referenced by Terraria.GameContent.UI.Elements.UITextPanel< T >.UITextPanel(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ModListFinished(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.ModListStartLoading(), Terraria.ModLoader.UI.UICreateMod.OKClick(), Terraria.ModLoader.Config.UI.UIModConfig.OnActivate(), Terraria.ModLoader.UI.UICreateMod.OnActivate(), Terraria.ModLoader.UI.UIErrorMessage.OnActivate(), Terraria.ModLoader.UI.UIInfoMessage.OnActivate(), Terraria.ModLoader.UI.UIModInfo.OnActivate(), Terraria.GameContent.UI.Elements.UITextPanel< T >.Recalculate(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.SetHeading(), Terraria.GameContent.UI.States.UIVirtualKeyboard.SetKeyState(), Terraria.ModLoader.Config.UI.UIModConfig.SetMessage(), Terraria.GameContent.UI.Elements.UITextPanel< T >.SetText(), and Terraria.ModLoader.UI.UIForcedDelayInfoMessage.Update().