TModLoader: Terraria.NPC.HitModifiers.GetDamage
GetDamage()
readonly int Terraria.NPC.HitModifiers.GetDamage (float baseDamage, bool crit, bool damageVariation = false, float luck = 0f) inline
Definition at line 286 of file NPC.cs.
        {
            crit = _critOverride ?? crit;
            if (SuperArmor)
            {
                float dmg = 1f;
                if (crit)
                {
                    dmg *= CritDamage.Additive * CritDamage.Multiplicative;
                }
                return Math.Clamp((int)dmg, 1, Math.Min(_damageLimit, 4));
            }
            float damage = SourceDamage.ApplyTo(baseDamage);
            damage += FlatBonusDamage.Value + ScalingBonusDamage.Value * damage;
            damage *= TargetDamageMultiplier.Value;
            int variationPercent = Utils.Clamp((int)Math.Round((float)Main.DefaultDamageVariationPercent * DamageVariationScale.Value), 0, 100);
            if (damageVariation && variationPercent > 0)
            {
                damage = Main.DamageVar(damage, variationPercent, luck);
            }
            float num = Math.Max(Defense.ApplyTo(0f), 0f);
            float armorPenetration = num * Math.Clamp(ScalingArmorPenetration.Value, 0f, 1f) + ArmorPenetration.Value;
            float damageReduction = Math.Max(num - armorPenetration, 0f) * DefenseEffectiveness.Value;
            damage = Math.Max(damage - damageReduction, 1f);
            damage = (crit ? CritDamage : NonCritDamage).ApplyTo(damage);
            return Math.Clamp((int)FinalDamage.ApplyTo(damage), 1, _damageLimit);
        }
References Terraria.NPC.HitModifiers._critOverride, Terraria.NPC.HitModifiers._damageLimit, Terraria.ModLoader.StatModifier.ApplyTo(), Terraria.NPC.HitModifiers.ArmorPenetration, Terraria.NPC.HitModifiers.CritDamage, Terraria.NPC.damage, Terraria.Main.DamageVar(), Terraria.NPC.HitModifiers.DamageVariationScale, Terraria.Main.DefaultDamageVariationPercent, Terraria.NPC.HitModifiers.Defense, Terraria.NPC.HitModifiers.DefenseEffectiveness, Terraria.NPC.HitModifiers.FinalDamage, Terraria.ModLoader.StatModifier.Multiplicative, Terraria.NPC.HitModifiers.NonCritDamage, Terraria.NPC.HitModifiers.ScalingArmorPenetration, Terraria.NPC.HitModifiers.SourceDamage, Terraria.NPC.HitModifiers.SuperArmor, Terraria.NPC.HitModifiers.TargetDamageMultiplier, Terraria.ModLoader.AddableFloat.Value, and Terraria.ModLoader.MultipliableFloat.Value.
Referenced by Terraria.NPC.HitModifiers.ToHitInfo().