TModLoader: Terraria.NPC.HitModifiers.ToHitInfo
ToHitInfo()
HitInfo Terraria.NPC.HitModifiers.ToHitInfo (float baseDamage, bool crit, float baseKnockback, bool damageVariation = false, float luck = 0f) inline
Definition at line 319 of file NPC.cs.
        {
            HitInfo hitInfo2 = new HitInfo();
            hitInfo2.DamageType = DamageType ?? DamageClass.Default;
            hitInfo2.SourceDamage = Math.Max((int)SourceDamage.ApplyTo(baseDamage), 1);
            hitInfo2.Damage = (_instantKill ? 1 : GetDamage(baseDamage, crit, damageVariation, luck));
            hitInfo2.Crit = _critOverride ?? crit;
            hitInfo2.Knockback = GetKnockback(baseKnockback);
            hitInfo2.HitDirection = HitDirectionOverride ?? HitDirection;
            hitInfo2.InstantKill = _instantKill;
            hitInfo2.HideCombatText = _combatTextHidden;
            HitInfo hitInfo = hitInfo2;
            this.ModifyHitInfo?.Invoke(ref hitInfo);
            this.ModifyHitInfo = null;
            return hitInfo;
        }
References Terraria.NPC.HitModifiers._combatTextHidden, Terraria.NPC.HitModifiers._critOverride, Terraria.NPC.HitModifiers._instantKill, Terraria.ModLoader.StatModifier.ApplyTo(), Terraria.NPC.HitModifiers.DamageType, Terraria.ModLoader.DamageClass.Default, Terraria.NPC.HitModifiers.GetDamage(), Terraria.NPC.HitModifiers.GetKnockback(), Terraria.NPC.HitModifiers.HitDirection, Terraria.NPC.HitModifiers.HitDirectionOverride, and Terraria.NPC.HitModifiers.SourceDamage.