TModLoader: Terraria.GameContent.UI.Elements.UIList.Clear
Clear()
virtual void Terraria.GameContent.UI.Elements.UIList.Clear () inline virtual inherited
    {
        _innerList.RemoveAllChildren();
        _items.Clear();
    }
References Terraria.GameContent.UI.Elements.UIList._innerList, Terraria.GameContent.UI.Elements.UIList._items, and Terraria.UI.UIElement.RemoveAllChildren().
Referenced by Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.FillInfoForEntry(), Terraria.GameContent.UI.States.UIManageControls.FillList(), Terraria.GameContent.UI.States.UIAchievementsMenu.FilterList(), Terraria.ModLoader.Config.UI.UIModConfig.OnActivate(), Terraria.ModLoader.Config.UI.UIModConfigList.OnActivate(), Terraria.ModLoader.UI.UIModPacks.OnActivate(), Terraria.ModLoader.UI.UIMods.OnActivate(), Terraria.ModLoader.UI.UIModSources.OnActivate(), Terraria.ModLoader.Config.UI.UIModConfigList.PopulateConfigs(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.PopulateEntries(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.PopulateEntries(), Terraria.ModLoader.Config.UI.UIModConfigList.PopulateMods(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.PopulatePackList(), Terraria.ModLoader.Config.UI.ObjectElement.SetupList(), Terraria.ModLoader.Config.UI.UIModConfig.Unload(), Terraria.ModLoader.Config.UI.UIModConfigList.Unload(), Terraria.ModLoader.Config.UI.UIModConfig.Update(), Terraria.ModLoader.UI.Elements.UIAsyncList< TResource, TUIElement >.Update(), Terraria.ModLoader.UI.UIMods.Update(), Terraria.ModLoader.UI.UIModSources.Update(), Terraria.GameContent.UI.States.UICharacterSelect.UpdatePlayersList(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.UpdateWorldsList(), and Terraria.GameContent.UI.States.UIWorldSelect.UpdateWorldsList().