TModLoader: Terraria.Recipe.AddTile
AddTile() [1/3]
Recipe Terraria.Recipe.AddTile (int tileID) inline
Adds a required crafting station with the given tile type to this recipe. Ex: recipe.AddTile(TileID.WorkBenches)
Parameters
tileID The tile identifier.
Exceptions
T:Terraria.ModLoader.Exceptions.RecipeException No tile has ID " + tileID
Definition at line 16299 of file Recipe.cs.
    {
        if (tileID < 0 || tileID >= TileLoader.TileCount)
        {
            throw new RecipeException($"No tile has ID '{tileID}'.");
        }
        requiredTile.Add(tileID);
        return this;
    }
References Terraria.Recipe.requiredTile, and Terraria.ModLoader.TileLoader.TileCount.
Referenced by Terraria.Recipe.AddTile(), Terraria.Recipe.AddTile(), and Terraria.Recipe.AddTile< T >().