TModLoader: Terraria.GameContent.UI.Elements.UIList.AddRange
AddRange()
virtual void Terraria.GameContent.UI.Elements.UIList.AddRange (IEnumerable< UIElement > items) inline virtual inherited
    {
        foreach (UIElement item in items)
        {
            _items.Add(item);
            _innerList.Append(item);
        }
        UpdateOrder();
        _innerList.Recalculate();
    }
References Terraria.GameContent.UI.Elements.UIList._innerList, Terraria.GameContent.UI.Elements.UIList._items, Terraria.UI.UIElement.Append(), Terraria.UI.UIElement.Recalculate(), and Terraria.GameContent.UI.Elements.UIList.UpdateOrder().
Referenced by Terraria.ModLoader.UI.UIModPacks.OnActivate(), Terraria.ModLoader.Config.UI.UIModConfig.Update(), Terraria.ModLoader.UI.Elements.UIAsyncList< TResource, TUIElement >.Update(), Terraria.ModLoader.UI.UIMods.Update(), and Terraria.ModLoader.UI.UIModSources.Update().