TModLoader: Terraria.Recipe.Clone
Clone()
Recipe Terraria.Recipe.Clone () inline
Returns a clone of this recipe except the source mod of the Recipe will the currently loading mod.
The clone will have to be registered after being tweaked.
Definition at line 16539 of file Recipe.cs.
    {
        if (!RecipeLoader.setupRecipes)
        {
            throw new RecipeException("A Recipe can only be cloned inside recipe related methods");
        }
        ArgumentNullException.ThrowIfNull(RecipeLoader.CurrentMod, "RecipeLoader.CurrentMod");
        Recipe clone = new Recipe(RecipeLoader.CurrentMod);
        clone.createItem = createItem.Clone();
        clone.requiredItem = new List<Item>(requiredItem.Select((Item x) => x.Clone()).ToArray());
        clone.requiredTile = new List<int>(requiredTile.ToArray());
        clone.acceptedGroups = new List<int>(acceptedGroups.ToArray());
        clone.notDecraftable = notDecraftable;
        clone.crimson = crimson;
        clone.corruption = corruption;
        clone.needHoney = needHoney;
        clone.needWater = needWater;
        clone.needLava = needLava;
        clone.anyWood = anyWood;
        clone.anyIronBar = anyIronBar;
        clone.anyPressurePlate = anyPressurePlate;
        clone.anySand = anySand;
        clone.anyFragment = anyFragment;
        clone.alchemy = alchemy;
        clone.needSnowBiome = needSnowBiome;
        clone.needGraveyardBiome = needGraveyardBiome;
        clone.needEverythingSeed = needEverythingSeed;
        clone.OnCraftHooks = OnCraftHooks;
        clone.ConsumeItemHooks = ConsumeItemHooks;
        foreach (Condition condition2 in Conditions)
        {
            clone.AddCondition(condition2);
        }
        foreach (Condition condition in DecraftConditions)
        {
            clone.AddDecraftCondition(condition);
        }
        if (clone.requiredTile.Contains(13))
        {
            clone.ConsumeItemHooks = (ConsumeItemCallback)Delegate.Remove(clone.ConsumeItemHooks, ConsumptionRules.Alchemy);
        }
        return clone;
    }
References Terraria.Recipe.Recipe(), Terraria.Recipe.acceptedGroups, Terraria.Recipe.ConsumptionRules.Alchemy, Terraria.Recipe.alchemy, Terraria.Recipe.anyFragment, Terraria.Recipe.anyIronBar, Terraria.Recipe.anyPressurePlate, Terraria.Recipe.anySand, Terraria.Recipe.anyWood, Terraria.Item.Clone(), Terraria.Condition(), Terraria.Recipe.Conditions, Terraria.Recipe.ConsumeItemCallback(), Terraria.Recipe.ConsumeItemHooks, Terraria.Recipe.corruption, Terraria.Recipe.createItem, Terraria.Recipe.crimson, Terraria.ModLoader.RecipeLoader.CurrentMod, Terraria.Recipe.DecraftConditions, Terraria.Recipe.needEverythingSeed, Terraria.Recipe.needGraveyardBiome, Terraria.Recipe.needHoney, Terraria.Recipe.needLava, Terraria.Recipe.needSnowBiome, Terraria.Recipe.needWater, Terraria.Recipe.notDecraftable, Terraria.Recipe.OnCraftHooks, Terraria.Recipe.requiredItem, Terraria.Recipe.requiredTile, and Terraria.ModLoader.RecipeLoader.setupRecipes.
Referenced by Terraria.ModLoader.Mod.CloneRecipe().