TModLoader: Terraria.Recipe.AddRecipe
AddRecipe()
static void Terraria.Recipe.AddRecipe () inline static private
Definition at line 15835 of file Recipe.cs.
    {
        if (currentRecipe.requiredTile.Count > 0 && currentRecipe.requiredTile[0] == 13)
        {
            currentRecipe.AddConsumeItemCallback(ConsumptionRules.Alchemy);
        }
        ReplaceCondition(ref currentRecipe.needGraveyardBiome, Condition.InGraveyard);
        ReplaceCondition(ref currentRecipe.needSnowBiome, Condition.InSnow);
        ReplaceCondition(ref currentRecipe.needWater, Condition.NearWater);
        ReplaceCondition(ref currentRecipe.needLava, Condition.NearLava);
        ReplaceCondition(ref currentRecipe.needHoney, Condition.NearHoney);
        ReplaceCondition(ref currentRecipe.needEverythingSeed, Condition.ZenithWorld);
        ReplaceDecraftCondition(ref currentRecipe.crimson, Condition.CrimsonWorld);
        ReplaceDecraftCondition(ref currentRecipe.corruption, Condition.CorruptWorld);
        currentRecipe.ReplaceItemUseFlagWithGroup(ref currentRecipe.anyWood, RecipeGroupID.Wood);
        currentRecipe.ReplaceItemUseFlagWithGroup(ref currentRecipe.anySand, RecipeGroupID.Sand);
        currentRecipe.ReplaceItemUseFlagWithGroup(ref currentRecipe.anyPressurePlate, RecipeGroupID.PressurePlate);
        currentRecipe.ReplaceItemUseFlagWithGroup(ref currentRecipe.anyIronBar, RecipeGroupID.IronBar);
        currentRecipe.ReplaceItemUseFlagWithGroup(ref currentRecipe.anyFragment, RecipeGroupID.Fragment);
        currentRecipe.requiredItem.RemoveAll((Item item) => item.IsAir);
        currentRecipe.requiredTile.RemoveAll((int tile) => tile == -1);
        currentRecipe.acceptedGroups.RemoveAll((int group) => group == -1);
        Main.recipe[numRecipes] = currentRecipe;
        currentRecipe.RecipeIndex = numRecipes;
        if (RecipeLoader.FirstRecipeForItem[currentRecipe.createItem.type] == null)
        {
            RecipeLoader.FirstRecipeForItem[currentRecipe.createItem.type] = currentRecipe;
        }
        ResetCurrentRecipe();
        numRecipes++;
        static void ReplaceCondition(ref bool field, Condition cond)
        {
            if (field)
            {
                currentRecipe.AddCondition(cond);
            }
            field = false;
        }
        static void ReplaceDecraftCondition(ref bool field, Condition cond)
        {
            if (field)
            {
                currentRecipe.AddDecraftCondition(cond);
            }
            field = false;
        }
    }
References Terraria.Recipe.acceptedGroups, Terraria.Recipe.AddCondition(), Terraria.Recipe.AddConsumeItemCallback(), Terraria.Recipe.AddDecraftCondition(), Terraria.Recipe.ConsumptionRules.Alchemy, Terraria.Recipe.anyFragment, Terraria.Recipe.anyIronBar, Terraria.Recipe.anyPressurePlate, Terraria.Recipe.anySand, Terraria.Recipe.anyWood, Terraria.Condition(), Terraria.Recipe.corruption, Terraria.Recipe.createItem, Terraria.Recipe.crimson, Terraria.Recipe.currentRecipe, Terraria.ModLoader.RecipeLoader.FirstRecipeForItem, Terraria.ID.RecipeGroupID.Fragment, Terraria.ID.RecipeGroupID.IronBar, Terraria.Item.IsAir, Terraria.Recipe.needEverythingSeed, Terraria.Recipe.needGraveyardBiome, Terraria.Recipe.needHoney, Terraria.Recipe.needLava, Terraria.Recipe.needSnowBiome, Terraria.Recipe.needWater, Terraria.Recipe.numRecipes, Terraria.ID.RecipeGroupID.PressurePlate, Terraria.Main.recipe, Terraria.Recipe.ReplaceItemUseFlagWithGroup(), Terraria.Recipe.requiredItem, Terraria.Recipe.requiredTile, Terraria.Recipe.ResetCurrentRecipe(), Terraria.ID.RecipeGroupID.Sand, Terraria.Item.type, and Terraria.ID.RecipeGroupID.Wood.
Referenced by Terraria.Recipe.AddAshWoodFurnitureArmorAndItems(), Terraria.Recipe.AddBalloonFurniture(), Terraria.Recipe.AddBambooFurniture(), Terraria.Recipe.AddCoralFurniture(), Terraria.Recipe.AddLesionFurniture(), Terraria.Recipe.AddNebulaFurniture(), Terraria.Recipe.AddSandstoneFurniture(), Terraria.Recipe.AddSolarFurniture(), Terraria.Recipe.AddSpiderFurniture(), Terraria.Recipe.AddStardustFurniture(), Terraria.Recipe.AddVortexFurniture(), Terraria.Recipe.CreateReversePlatformRecipes(), Terraria.Recipe.CreateReverseWallRecipes(), and Terraria.Recipe.SetupRecipes().