TModLoader: Terraria.Recipe.requiredItem
requiredItem
List<Item> Terraria.Recipe.requiredItem = new List<Item>()
Referenced by Terraria.Recipe.AddIngredient(), Terraria.Recipe.Clone(), Terraria.Recipe.CollectGuideRecipes(), Terraria.Recipe.ConsumeForCraft(), Terraria.Recipe.Create(), Terraria.Recipe.CreateRequiredItemQuickLookups(), Terraria.Item.GetShimmered(), Terraria.Recipe.HasIngredient(), Terraria.Recipe.RemoveIngredient(), Terraria.Recipe.RemoveIngredient(), Terraria.Recipe.ResetCurrentRecipe(), Terraria.Recipe.SetIngredients(), and Terraria.Recipe.TryGetIngredient().