TModLoader: Terraria.Recipe.CollectGuideRecipes
CollectGuideRecipes()
static void Terraria.Recipe.CollectGuideRecipes () inline static private
    {
        int type = Main.guideItem.type;
        for (int i = 0; i < maxRecipes; i++)
        {
            Recipe recipe = Main.recipe[i];
            if (recipe.createItem.type == 0)
            {
                break;
            }
            if (recipe.Disabled)
            {
                continue;
            }
            for (int j = 0; j < recipe.requiredItem.Count; j++)
            {
                Item item = recipe.requiredItem[j];
                if (item.type == 0)
                {
                    break;
                }
                if (Main.guideItem.IsTheSameAs(item) || recipe.useWood(type, item.type) || recipe.useSand(type, item.type) || recipe.useIronBar(type, item.type) || recipe.useFragment(type, item.type) || recipe.AcceptedByItemGroups(type, item.type) || recipe.usePressurePlate(type, item.type))
                {
                    Main.availableRecipe[Main.numAvailableRecipes] = i;
                    Main.numAvailableRecipes++;
                    break;
                }
            }
        }
    }
References Terraria.Recipe.AcceptedByItemGroups(), Terraria.Main.availableRecipe, Terraria.Recipe.createItem, Terraria.Recipe.Disabled, Terraria.Main.guideItem, Terraria.Recipe.maxRecipes, Terraria.Main.numAvailableRecipes, Terraria.Main.recipe, Terraria.Recipe.requiredItem, Terraria.Item.type, Terraria.Recipe.useFragment(), Terraria.Recipe.useIronBar(), Terraria.Recipe.usePressurePlate(), Terraria.Recipe.useSand(), and Terraria.Recipe.useWood().
Referenced by Terraria.Recipe.FindRecipes().