TModLoader: Terraria.Recipe.Recipe
Recipe() [1/2]
static Terraria.Recipe.Recipe () inline static private
Definition at line 130 of file Recipe.cs.
    {
        maxVanillaRequirements = 15;
        maxRecipes = 3000;
        _ownedItems = new Dictionary<int, int>();
        ResetCurrentRecipe();
    }
References Terraria.Recipe._ownedItems, Terraria.Recipe.maxRecipes, Terraria.Recipe.maxVanillaRequirements, and Terraria.Recipe.ResetCurrentRecipe().
Referenced by Terraria.Recipe.Clone(), Terraria.Recipe.Create(), and Terraria.Recipe.Register().