TModLoader: Terraria.Recipe.ConsumeForCraft
ConsumeForCraft()
bool Terraria.Recipe.ConsumeForCraft (Item item, Item requiredItem, ref int stackRequired) inline private
    {
        if (item.stack == 0 || (!item.IsTheSameAs(requiredItem) && !AcceptedByItemGroups(item.type, requiredItem.type)))
        {
            return false;
        }
        Item consumed = item.Clone();
        consumed.stack = Math.Min(item.stack, stackRequired);
        RecipeLoader.ConsumedItems.Add(consumed);
        item.stack -= consumed.stack;
        stackRequired -= consumed.stack;
        if (item.stack == 0)
        {
            item.TurnToAir();
        }
        return true;
    }
References Terraria.Recipe.AcceptedByItemGroups(), Terraria.Item.Clone(), Terraria.ModLoader.RecipeLoader.ConsumedItems, Terraria.Item.IsTheSameAs(), Terraria.Recipe.requiredItem, Terraria.Item.stack, Terraria.Item.TurnToAir(), and Terraria.Item.type.
Referenced by Terraria.Recipe.Create().