TModLoader: Terraria.GameContent.UI.States.UIWorkshopWorldImport.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIWorkshopWorldImport.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 213 of file UIWorkshopWorldImport.cs.
    {
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        UILinkPointNavigator.Shortcuts.BackButtonCommand = 7;
        int num = 3000;
        Rectangle val = _backPanel.GetInnerDimensions().ToRectangle();
        UILinkPointNavigator.SetPosition(num, ((Rectangle)(ref val)).Center.ToVector2());
        int key = num;
        UILinkPoint uILinkPoint = UILinkPointNavigator.Points[key];
        uILinkPoint.Unlink();
        float num2 = 1f / Main.UIScale;
        Rectangle clippingRectangle = _containerPanel.GetClippingRectangle(spriteBatch);
        Vector2 minimum = clippingRectangle.TopLeft() * num2;
        Vector2 maximum = clippingRectangle.BottomRight() * num2;
        List<SnapPoint> snapPoints = GetSnapPoints();
        for (int i = 0; i < snapPoints.Count; i++)
        {
            if (!snapPoints[i].Position.Between(minimum, maximum))
            {
                snapPoints.Remove(snapPoints[i]);
                i--;
            }
        }
        SnapPoint[,] array = new SnapPoint[_worldList.Count, 1];
        foreach (SnapPoint item in snapPoints.Where((SnapPoint a) => a.Name == "Import"))
        {
            array[item.Id, 0] = item;
        }
        key = num + 2;
        int[] array2 = new int[_worldList.Count];
        for (int j = 0; j < array2.Length; j++)
        {
            array2[j] = -1;
        }
        for (int k = 0; k < 1; k++)
        {
            int num3 = -1;
            for (int l = 0; l < array.GetLength(0); l++)
            {
                if (array[l, k] != null)
                {
                    uILinkPoint = UILinkPointNavigator.Points[key];
                    uILinkPoint.Unlink();
                    UILinkPointNavigator.SetPosition(key, array[l, k].Position);
                    if (num3 != -1)
                    {
                        uILinkPoint.Up = num3;
                        UILinkPointNavigator.Points[num3].Down = key;
                    }
                    if (array2[l] != -1)
                    {
                        uILinkPoint.Left = array2[l];
                        UILinkPointNavigator.Points[array2[l]].Right = key;
                    }
                    uILinkPoint.Down = num;
                    if (k == 0)
                    {
                        UILinkPointNavigator.Points[num].Up = (UILinkPointNavigator.Points[num + 1].Up = key);
                    }
                    num3 = key;
                    array2[l] = key;
                    UILinkPointNavigator.Shortcuts.FANCYUI_HIGHEST_INDEX = key;
                    key++;
                }
            }
        }
        if (PlayerInput.UsingGamepadUI && _worldList.Count == 0 && UILinkPointNavigator.CurrentPoint > 3001)
        {
            UILinkPointNavigator.ChangePoint(3001);
        }
    }
References Terraria.GameContent.UI.States.UIWorkshopWorldImport._backPanel, Terraria.GameContent.UI.States.UIWorkshopWorldImport._containerPanel, Terraria.GameContent.UI.States.UIWorkshopWorldImport._worldList, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), Terraria.GameContent.UI.Elements.UIList.Count, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Terraria.UI.UIElement.GetClippingRectangle(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.UIScale, and Terraria.GameInput.PlayerInput.UsingGamepadUI.
Referenced by Terraria.GameContent.UI.States.UIWorkshopWorldImport.Draw().