TModLoader: Terraria.ModLoader.Config.UI.ObjectElement.SetupList
SetupList()
void Terraria.ModLoader.Config.UI.ObjectElement.SetupList () inline private
Definition at line 209 of file ObjectElement.cs.
    {
        dataList.Clear();
        object data = Value;
        if (data == null)
        {
            return;
        }
        if (separatePage && !ignoreSeparatePage)
        {
            separatePagePanel = UIModConfig.MakeSeparateListPanel(base.Item, data, base.MemberInfo, base.List, base.Index, AbridgedTextDisplayFunction);
            return;
        }
        int order = 0;
        foreach (PropertyFieldWrapper variable in ConfigManager.GetFieldsAndProperties(data))
        {
            if (!Attribute.IsDefined(variable.MemberInfo, typeof(JsonIgnoreAttribute)))
            {
                int top = 0;
                UIModConfig.HandleHeader(dataList, ref top, ref order, variable);
                Tuple<UIElement, UIElement> wrapped = UIModConfig.WrapIt(dataList, ref top, variable, data, order++);
                if (base.List != null)
                {
                    wrapped.Item1.Width.Pixels += 20f;
                }
            }
        }
    }
References Terraria.ModLoader.Config.UI.ObjectElement.AbridgedTextDisplayFunction, Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.ModLoader.Config.UI.ObjectElement.dataList, Terraria.ModLoader.Config.ConfigManager.GetFieldsAndProperties(), Terraria.ModLoader.Config.UI.UIModConfig.HandleHeader(), Terraria.ModLoader.Config.UI.ObjectElement.ignoreSeparatePage, Terraria.ModLoader.Config.UI.ConfigElement< object >.List, Terraria.ModLoader.Config.UI.UIModConfig.MakeSeparateListPanel(), Terraria.ModLoader.Config.UI.ObjectElement.separatePage, Terraria.ModLoader.Config.UI.ObjectElement.separatePagePanel, Terraria.ModLoader.Config.UI.ConfigElement< object >.Value, and Terraria.ModLoader.Config.UI.UIModConfig.WrapIt().
Referenced by Terraria.ModLoader.Config.UI.ObjectElement.OnBind().