TModLoader: Terraria.ModLoader.Config.UI.ObjectElement.OnBind
OnBind()
override void Terraria.ModLoader.Config.UI.ObjectElement.OnBind () inline virtual
Reimplemented from Terraria.ModLoader.Config.UI.ConfigElement< object >.
Definition at line 43 of file ObjectElement.cs.
    {
        base.OnBind();
        if (base.List != null)
        {
            MethodInfo methodInfo = base.MemberInfo.Type.GetGenericArguments()[0].GetMethod("ToString", Array.Empty<Type>());
            if (methodInfo != null && methodInfo.DeclaringType != typeof(object))
            {
                base.TextDisplayFunction = () => base.Index + 1 + ": " + (base.List[base.Index]?.ToString() ?? "null");
                AbridgedTextDisplayFunction = () => base.List[base.Index]?.ToString() ?? "null";
            }
            else
            {
                base.TextDisplayFunction = () => base.Index + 1 + ": ";
            }
        }
        else if (base.MemberInfo.Type.GetMethod("ToString", Array.Empty<Type>()).DeclaringType != typeof(object))
        {
            base.TextDisplayFunction = () => Label + ((Value == null) ? "" : (": " + Value.ToString()));
            AbridgedTextDisplayFunction = () => Value?.ToString() ?? "";
        }
        if (Value == null && base.List != null)
        {
            object data = Activator.CreateInstance(base.MemberInfo.Type, nonPublic: true);
            JsonConvert.PopulateObject(JsonDefaultValueAttribute?.Json ?? "{}", data, ConfigManager.serializerSettings);
            Value = data;
        }
        separatePage = ConfigManager.GetCustomAttributeFromMemberThenMemberType<SeparatePageAttribute>(base.MemberInfo, base.Item, base.List) != null;
        if (separatePage && !ignoreSeparatePage)
        {
            separatePageButton = new UITextPanel<FuncStringWrapper>(new FuncStringWrapper(base.TextDisplayFunction));
            separatePageButton.HAlign = 0.5f;
            separatePageButton.OnLeftClick += delegate
            {
                UIModConfig.SwitchToSubConfig(separatePagePanel);
            };
        }
        if (base.List == null)
        {
            ExpandAttribute expandAttribute = ConfigManager.GetCustomAttributeFromMemberThenMemberType<ExpandAttribute>(base.MemberInfo, base.Item, base.List);
            if (expandAttribute != null)
            {
                expanded = expandAttribute.Expand;
            }
        }
        else
        {
            ExpandAttribute expandAttribute2 = (ExpandAttribute)Attribute.GetCustomAttribute(base.MemberInfo.Type.GetGenericArguments()[0], typeof(ExpandAttribute), inherit: true);
            if (expandAttribute2 != null)
            {
                expanded = expandAttribute2.Expand;
            }
            expandAttribute2 = (ExpandAttribute)Attribute.GetCustomAttribute(base.MemberInfo.MemberInfo, typeof(ExpandAttribute), inherit: true);
            if (expandAttribute2 != null && expandAttribute2.ExpandListElements.HasValue)
            {
                expanded = expandAttribute2.ExpandListElements.Value;
            }
        }
        dataList = new NestedUIList();
        dataList.Width.Set(-14f, 1f);
        dataList.Left.Set(14f, 0f);
        dataList.Height.Set(-30f, 1f);
        dataList.Top.Set(30f, 0f);
        dataList.ListPadding = 5f;
        if (expanded)
        {
            Append(dataList);
        }
        _ = base.List;
        initializeButton = new UIModConfigHoverImage(base.PlayTexture, Language.GetTextValue("tModLoader.ModConfigInitialize"));
        initializeButton.Top.Pixels += 4f;
        initializeButton.Left.Pixels -= 3f;
        initializeButton.HAlign = 1f;
        initializeButton.OnLeftClick += delegate
        {
            SoundEngine.PlaySound(21);
            object obj = Activator.CreateInstance(base.MemberInfo.Type, nonPublic: true);
            JsonConvert.PopulateObject(JsonDefaultValueAttribute?.Json ?? "{}", obj, ConfigManager.serializerSettings);
            Value = obj;
            pendingChanges = true;
            SetupList();
            Interface.modConfig.RecalculateChildren();
            Interface.modConfig.SetPendingChanges();
        };
        expandButton = new UIModConfigHoverImage(expanded ? base.ExpandedTexture : base.CollapsedTexture, expanded ? Language.GetTextValue("tModLoader.ModConfigCollapse") : Language.GetTextValue("tModLoader.ModConfigExpand"));
        expandButton.Top.Set(4f, 0f);
        expandButton.Left.Set(-52f, 1f);
        expandButton.OnLeftClick += delegate
        {
            expanded = !expanded;
            pendingChanges = true;
        };
        deleteButton = new UIModConfigHoverImage(base.DeleteTexture, Language.GetTextValue("tModLoader.ModConfigClear"));
        deleteButton.Top.Set(4f, 0f);
        deleteButton.Left.Set(-25f, 1f);
        deleteButton.OnLeftClick += delegate
        {
            Value = null;
            pendingChanges = true;
            SetupList();
            Interface.modConfig.SetPendingChanges();
        };
        if (Value != null)
        {
            SetupList();
        }
        else
        {
            Append(initializeButton);
        }
        pendingChanges = true;
        Recalculate();
    }
References Terraria.ModLoader.Config.UI.ObjectElement.AbridgedTextDisplayFunction, Terraria.ModLoader.Config.UI.ObjectElement.dataList, Terraria.ModLoader.Config.UI.ObjectElement.deleteButton, Terraria.ModLoader.Config.UI.ObjectElement.expandButton, Terraria.ModLoader.Config.UI.ObjectElement.expanded, Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.Height, Terraria.ModLoader.Config.UI.ObjectElement.ignoreSeparatePage, Terraria.ModLoader.Config.UI.ObjectElement.initializeButton, Terraria.ModLoader.Config.UI.ConfigElement< object >.Label, Terraria.UI.UIElement.Left, Terraria.ModLoader.Config.UI.ConfigElement< object >.List, Terraria.ModLoader.UI.Interface.modConfig, Terraria.ModLoader.Config.UI.ObjectElement.pendingChanges, Terraria.Audio.SoundEngine.PlaySound(), Terraria.ModLoader.Config.UI.ObjectElement.Recalculate(), Terraria.ModLoader.Config.UI.ObjectElement.separatePage, Terraria.ModLoader.Config.UI.ObjectElement.separatePageButton, Terraria.ModLoader.Config.UI.ObjectElement.separatePagePanel, Terraria.ModLoader.Config.ConfigManager.serializerSettings, Terraria.UI.StyleDimension.Set(), Terraria.ModLoader.Config.UI.ObjectElement.SetupList(), Terraria.ModLoader.Config.UI.UIModConfig.SwitchToSubConfig(), Terraria.UI.UIElement.Top, Terraria.ModLoader.Config.UI.ConfigElement< object >.Value, and Terraria.UI.UIElement.Width.