TModLoader: Terraria.Sign.ReadSign
ReadSign()
static int Terraria.Sign.ReadSign (int i, int j, bool CreateIfMissing = true) inline static
Definition at line 24 of file Sign.cs.
    {
        int num = Main.tile[i, j].frameX / 18;
        int num2 = Main.tile[i, j].frameY / 18;
        num %= 2;
        int num3 = i - num;
        int num4 = j - num2;
        if (!Main.tileSign[Main.tile[num3, num4].type])
        {
            KillSign(num3, num4);
            return -1;
        }
        int num5 = -1;
        for (int k = 0; k < 1000; k++)
        {
            if (Main.sign[k] != null && Main.sign[k].x == num3 && Main.sign[k].y == num4)
            {
                num5 = k;
                break;
            }
        }
        if (num5 < 0 && CreateIfMissing)
        {
            for (int l = 0; l < 1000; l++)
            {
                if (Main.sign[l] == null)
                {
                    num5 = l;
                    Main.sign[l] = new Sign();
                    Main.sign[l].x = num3;
                    Main.sign[l].y = num4;
                    Main.sign[l].text = "";
                    break;
                }
            }
        }
        return num5;
    }
References Terraria.Sign.KillSign(), Terraria.Main.sign, Terraria.Sign.text, Terraria.Main.tile, Terraria.Main.tileSign, Terraria.Sign.x, and Terraria.Sign.y.
Referenced by Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.MessageBuffer.GetData(), Terraria.Wiring.HitWireSingle(), Terraria.Player.TileInteractionsCheckLongDistance(), Terraria.Player.TileInteractionsMouseOver(), and Terraria.Player.TileInteractionsUse().