TModLoader: Terraria.GameContent.UI.CustomCurrencyManager.PayCurrency
PayCurrency()
static bool Terraria.GameContent.UI.CustomCurrencyManager.PayCurrency (Player player, long price, int currencyIndex = -1) inline static
Definition at line 124 of file CustomCurrencyManager.cs.
    {
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        CustomCurrencySystem customCurrencySystem = _currencies[currencyIndex];
        List<Item[]> list = new List<Item[]>();
        Dictionary<int, List<int>> dictionary = new Dictionary<int, List<int>>();
        List<Point> list2 = new List<Point>();
        List<Point> list3 = new List<Point>();
        List<Point> list4 = new List<Point>();
        List<Point> list5 = new List<Point>();
        List<Point> list6 = new List<Point>();
        List<Point> list7 = new List<Point>();
        list.Add(player.inventory);
        list.Add(player.bank.item);
        list.Add(player.bank2.item);
        list.Add(player.bank3.item);
        list.Add(player.bank4.item);
        for (int i = 0; i < list.Count; i++)
        {
            dictionary[i] = new List<int>();
        }
        dictionary[0] = new List<int> { 58, 57, 56, 55, 54 };
        for (int j = 0; j < list.Count; j++)
        {
            for (int k = 0; k < list[j].Length; k++)
            {
                if (!dictionary[j].Contains(k) && customCurrencySystem.Accepts(list[j][k]))
                {
                    list3.Add(new Point(j, k));
                }
            }
        }
        FindEmptySlots(list, dictionary, list2, 0);
        FindEmptySlots(list, dictionary, list4, 1);
        FindEmptySlots(list, dictionary, list5, 2);
        FindEmptySlots(list, dictionary, list6, 3);
        FindEmptySlots(list, dictionary, list7, 4);
        if (!customCurrencySystem.TryPurchasing(price, list, list3, list2, list4, list5, list6, list7))
        {
            return false;
        }
        return true;
    }
References Terraria.GameContent.UI.CustomCurrencyManager._currencies, Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.GameContent.UI.CustomCurrencyManager.FindEmptySlots(), Terraria.Player.inventory, and Terraria.Chest.item.
Referenced by Terraria.GameContent.UI.CustomCurrencyManager.BuyItem(), and Terraria.Player.PayCurrency().