TModLoader: Terraria.GameContent.UI.CustomCurrencyManager.DrawSavings
DrawSavings()
static void Terraria.GameContent.UI.CustomCurrencyManager.DrawSavings (SpriteBatch sb, int currencyIndex, float shopx, float shopy, bool horizontal = false) inline static
Definition at line 29 of file CustomCurrencyManager.cs.
    {
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0217: Unknown result type (might be due to invalid IL or missing references)
        //IL_0228: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01de: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ed: Unknown result type (might be due to invalid IL or missing references)
        CustomCurrencySystem customCurrencySystem = _currencies[currencyIndex];
        Player player = Main.player[Main.myPlayer];
        bool overFlowing;
        long num = customCurrencySystem.CountCurrency(out overFlowing, player.bank.item);
        long num2 = customCurrencySystem.CountCurrency(out overFlowing, player.bank2.item);
        long num3 = customCurrencySystem.CountCurrency(out overFlowing, player.bank3.item);
        long num4 = customCurrencySystem.CountCurrency(out overFlowing, player.bank4.item);
        long num5 = customCurrencySystem.CombineStacks(out overFlowing, num, num2, num3, num4);
        if (num5 > 0)
        {
            Main.GetItemDrawFrame(4076, out var itemTexture, out var itemFrame);
            Main.GetItemDrawFrame(3813, out var itemTexture2, out var itemFrame2);
            Main.GetItemDrawFrame(346, out var itemTexture3, out var itemFrame3);
            Main.GetItemDrawFrame(87, out var itemTexture4, out var itemFrame4);
            if (num4 > 0)
            {
                sb.Draw(itemTexture, Utils.CenteredRectangle(new Vector2(shopx + 96f, shopy + 50f), itemFrame.Size() * 0.65f), (Rectangle?)null, Color.White);
            }
            if (num3 > 0)
            {
                sb.Draw(itemTexture2, Utils.CenteredRectangle(new Vector2(shopx + 80f, shopy + 50f), itemFrame2.Size() * 0.65f), (Rectangle?)null, Color.White);
            }
            if (num2 > 0)
            {
                sb.Draw(itemTexture3, Utils.CenteredRectangle(new Vector2(shopx + 80f, shopy + 50f), itemFrame3.Size() * 0.65f), (Rectangle?)null, Color.White);
            }
            if (num > 0)
            {
                sb.Draw(itemTexture4, Utils.CenteredRectangle(new Vector2(shopx + 70f, shopy + 60f), itemFrame4.Size() * 0.65f), (Rectangle?)null, Color.White);
            }
            Utils.DrawBorderStringFourWay(sb, FontAssets.MouseText.Value, Lang.inter[66].Value, shopx, shopy + 40f, Color.White * ((float)(int)Main.mouseTextColor / 255f), Color.Black, Vector2.Zero);
            customCurrencySystem.DrawSavingsMoney(sb, Lang.inter[66].Value, shopx, shopy, num5, horizontal);
        }
    }
References Terraria.GameContent.UI.CustomCurrencyManager._currencies, Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Utils.CenteredRectangle(), Terraria.Utils.DrawBorderStringFourWay(), Terraria.Main.GetItemDrawFrame(), Terraria.Lang.inter, Terraria.Chest.item, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.myPlayer, and Terraria.Main.player.
Referenced by Terraria.UI.ItemSlot.DrawSavings().