TModLoader: Terraria.ModLoader.Engine.FolderShortcutSupport.UpdateFolderShortcuts
UpdateFolderShortcuts()
static void Terraria.ModLoader.Engine.FolderShortcutSupport.UpdateFolderShortcuts () inline static package
    {
        if (!OperatingSystem.IsWindows())
        {
            return;
        }
        try
        {
            CreateLogsFolderShortcut();
        }
        catch (Exception ex) when (ex is COMException || ex is FileNotFoundException)
        {
            if (ControlledFolderAccessSupport.ControlledFolderAccessDetected)
            {
                Utils.OpenToURL("https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#controlled-folder-access");
                throw new Exception("\n\nControlled Folder Access feature detected.\n\nIf game fails to launch make sure to add \"" + Environment.ProcessPath + "\" to the \"Allow an app through Controlled folder access\" menu found in the \"Ransomware protection\" menu.\n\nMore instructions can be found in the website that just opened.\n\n");
            }
        }
        catch (Exception e)
        {
            Logging.tML.Warn((object)$"Unable to create logs folder shortcuts - an exception of type {e.GetType().Name} was thrown:\r\n'{e.Message}'.");
        }
    }
References Terraria.ModLoader.Engine.ControlledFolderAccessSupport.ControlledFolderAccessDetected, Terraria.ModLoader.Engine.FolderShortcutSupport.CreateLogsFolderShortcut(), Terraria.ModLoader.Environment, Terraria.Utils.OpenToURL(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.ModLoader.ModLoader.EngineInit().