TModLoader: Terraria.GameContent.Tile_Entities.TEDisplayDoll.DrawSlotPairSet
DrawSlotPairSet()
void Terraria.GameContent.Tile_Entities.TEDisplayDoll.DrawSlotPairSet (Player player, SpriteBatch spriteBatch, int slotsToShowLine, int slotsArrayOffset, float offsetX, float offsetY, int inventoryContextTarget) inline private
Definition at line 389 of file TEDisplayDoll.cs.
    {
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        Item[] items = _items;
        int num = inventoryContextTarget;
        for (int i = 0; i < slotsToShowLine; i++)
        {
            for (int j = 0; j < 2; j++)
            {
                int num2 = (int)(73f + ((float)i + offsetX) * 56f * Main.inventoryScale);
                int num3 = (int)((float)Main.instance.invBottom + ((float)j + offsetY) * 56f * Main.inventoryScale);
                if (j == 0)
                {
                    items = _items;
                    num = inventoryContextTarget;
                }
                else
                {
                    items = _dyes;
                    num = 25;
                }
                if (Utils.FloatIntersect(Main.mouseX, Main.mouseY, 0f, 0f, num2, num3, (float)TextureAssets.InventoryBack.Width() * Main.inventoryScale, (float)TextureAssets.InventoryBack.Height() * Main.inventoryScale) && !PlayerInput.IgnoreMouseInterface)
                {
                    player.mouseInterface = true;
                    ItemSlot.Handle(items, num, i + slotsArrayOffset);
                }
                ItemSlot.Draw(spriteBatch, items, num, i + slotsArrayOffset, new Vector2((float)num2, (float)num3));
            }
        }
    }
References Terraria.GameContent.Tile_Entities.TEDisplayDoll._dyes, Terraria.GameContent.Tile_Entities.TEDisplayDoll._items, Terraria.UI.ItemSlot.Draw(), Terraria.Utils.FloatIntersect(), Terraria.UI.ItemSlot.Handle(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.Main.inventoryScale, Terraria.Main.mouseX, and Terraria.Main.mouseY.
Referenced by Terraria.GameContent.Tile_Entities.TEDisplayDoll.DrawInner().