TModLoader: Terraria.ModLoader.Engine.InstallVerifier.CheckSteam
CheckSteam()
static void Terraria.ModLoader.Engine.InstallVerifier.CheckSteam () inline static private
    {
        if (!HashMatchesFile(steamAPIPath, steamAPIHash))
        {
            Utils.OpenToURL("https://terraria.org");
            ErrorReporting.FatalExit(Language.GetTextValue("tModLoader.SteamAPIHashMismatch"));
        }
        else if (!Main.dedServ)
        {
            TerrariaSteamClient.LaunchResult result = TerrariaSteamClient.Launch();
            switch (result)
            {
            case TerrariaSteamClient.LaunchResult.ErrClientProcDied:
                ErrorReporting.FatalExit("The terraria steam client process exited unexpectedly");
                break;
            case TerrariaSteamClient.LaunchResult.ErrSteamInitFailed:
                ErrorReporting.FatalExit(Language.GetTextValue("tModLoader.SteamInitFailed"));
                break;
            case TerrariaSteamClient.LaunchResult.ErrNotInstalled:
                ErrorReporting.FatalExit(Language.GetTextValue("tModLoader.TerrariaNotInstalled"));
                break;
            case TerrariaSteamClient.LaunchResult.ErrInstallOutOfDate:
                ErrorReporting.FatalExit(Language.GetTextValue("tModLoader.TerrariaOutOfDateMessage"));
                break;
            default:
                throw new Exception("Unsupported result type: " + result);
            case TerrariaSteamClient.LaunchResult.Ok:
                break;
            }
        }
    }
References Terraria.Main.dedServ, Terraria.ModLoader.Engine.ErrorReporting.FatalExit(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.Engine.InstallVerifier.HashMatchesFile(), Terraria.ModLoader.Engine.TerrariaSteamClient.Launch(), Terraria.Utils.OpenToURL(), Terraria.ModLoader.Engine.InstallVerifier.steamAPIHash, and Terraria.ModLoader.Engine.InstallVerifier.steamAPIPath.
Referenced by Terraria.ModLoader.Engine.InstallVerifier.Startup().