TModLoader: Terraria.ModLoader.Engine.InstallVerifier.Startup
Startup()
static void Terraria.ModLoader.Engine.InstallVerifier.Startup () inline static package
    {
        DistributionPlatform = DetectPlatform(out var detectionDetails);
        Logging.tML.Info((object)$"Distribution Platform: {DistributionPlatform}. Detection method: {detectionDetails}");
        if (DistributionPlatform == DistributionPlatform.GoG)
        {
            CheckGoG();
        }
        else
        {
            CheckSteam();
        }
    }
References Terraria.ModLoader.Engine.InstallVerifier.CheckGoG(), Terraria.ModLoader.Engine.InstallVerifier.CheckSteam(), Terraria.ModLoader.Engine.InstallVerifier.DetectPlatform(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.Program.RunGame().