TModLoader: Terraria.GameContent.UI.Elements.UICharacterNameButton.TrimDisplayIfOverElementDimensions
TrimDisplayIfOverElementDimensions()
void Terraria.GameContent.UI.Elements.UICharacterNameButton.TrimDisplayIfOverElementDimensions (int padding) inline
Definition at line 106 of file UICharacterNameButton.cs.
    {
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_019d: Unknown result type (might be due to invalid IL or missing references)
        CalculatedStyle dimensions = GetDimensions();
        Point point = default(Point);
        ((Point)(ref point))._002Ector((int)dimensions.X, (int)dimensions.Y);
        Point point2 = default(Point);
        ((Point)(ref point2))._002Ector(point.X + (int)dimensions.Width, point.Y + (int)dimensions.Height);
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector(point.X, point.Y, point2.X - point.X, point2.Y - point.Y);
        CalculatedStyle dimensions2 = _text.GetDimensions();
        Point point3 = default(Point);
        ((Point)(ref point3))._002Ector((int)dimensions2.X, (int)dimensions2.Y);
        Point point4 = default(Point);
        ((Point)(ref point4))._002Ector(point3.X + (int)dimensions2.Width, point3.Y + (int)dimensions2.Height);
        Rectangle rectangle2 = default(Rectangle);
        ((Rectangle)(ref rectangle2))._002Ector(point3.X, point3.Y, point4.X - point3.X, point4.Y - point3.Y);
        int num = 0;
        while (((Rectangle)(ref rectangle2)).Right > ((Rectangle)(ref rectangle)).Right - padding)
        {
            _text.SetText(_text.Text.Substring(0, _text.Text.Length - 1));
            num++;
            RecalculateChildren();
            dimensions2 = _text.GetDimensions();
            ((Point)(ref point3))._002Ector((int)dimensions2.X, (int)dimensions2.Y);
            ((Point)(ref point4))._002Ector(point3.X + (int)dimensions2.Width, point3.Y + (int)dimensions2.Height);
            ((Rectangle)(ref rectangle2))._002Ector(point3.X, point3.Y, point4.X - point3.X, point4.Y - point3.Y);
        }
        if (num > 0)
        {
            _text.SetText(_text.Text.Substring(0, _text.Text.Length - 1) + "…");
        }
    }
References Terraria.GameContent.UI.Elements.UICharacterNameButton._text, Terraria.UI.UIElement.GetDimensions(), Terraria.UI.UIElement.RecalculateChildren(), Terraria.GameContent.UI.Elements.UIText.SetText(), and Terraria.GameContent.UI.Elements.UIText.Text.
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.UpdateInputFields().