TModLoader: Terraria.Wiring.Teleport
Teleport()
static void Terraria.Wiring.Teleport () inline static private
Definition at line 3081 of file Wiring.cs.
    {
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_0255: Unknown result type (might be due to invalid IL or missing references)
        //IL_0268: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0273: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0350: Unknown result type (might be due to invalid IL or missing references)
        //IL_035d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0387: Unknown result type (might be due to invalid IL or missing references)
        //IL_038c: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        if (_teleport[0].X < _teleport[1].X + 3f && _teleport[0].X > _teleport[1].X - 3f && _teleport[0].Y > _teleport[1].Y - 3f && _teleport[0].Y < _teleport[1].Y)
        {
            return;
        }
        Rectangle[] array = (Rectangle[])(object)new Rectangle[2];
        array[0].X = (int)(_teleport[0].X * 16f);
        array[0].Width = 48;
        array[0].Height = 48;
        array[0].Y = (int)(_teleport[0].Y * 16f - (float)array[0].Height);
        array[1].X = (int)(_teleport[1].X * 16f);
        array[1].Width = 48;
        array[1].Height = 48;
        array[1].Y = (int)(_teleport[1].Y * 16f - (float)array[1].Height);
        Vector2 vector = default(Vector2);
        for (int i = 0; i < 2; i++)
        {
            ((Vector2)(ref vector))._002Ector((float)(array[1].X - array[0].X), (float)(array[1].Y - array[0].Y));
            if (i == 1)
            {
                ((Vector2)(ref vector))._002Ector((float)(array[0].X - array[1].X), (float)(array[0].Y - array[1].Y));
            }
            if (!blockPlayerTeleportationForOneIteration)
            {
                for (int j = 0; j < 255; j++)
                {
                    if (Main.player[j].active && !Main.player[j].dead && !Main.player[j].teleporting && TeleporterHitboxIntersects(array[i], Main.player[j].Hitbox))
                    {
                        Vector2 vector2 = Main.player[j].position + vector;
                        Main.player[j].teleporting = true;
                        if (Main.netMode == 2)
{
                            RemoteClient.CheckSection(j, vector2);
                        }
                        Main.player[j].Teleport(vector2);
                        if (Main.netMode == 2)
{
                            NetMessage.SendData(65, -1, -1, null, 0, j, vector2.X, vector2.Y);
                        }
                    }
                }
            }
            for (int k = 0; k < 200; k++)
            {
                if (Main.npc[k].active && !Main.npc[k].teleporting && Main.npc[k].lifeMax > 5 && !Main.npc[k].boss && !Main.npc[k].noTileCollide)
                {
                    int type = Main.npc[k].type;
                    if (!NPCID.Sets.TeleportationImmune[type] && TeleporterHitboxIntersects(array[i], Main.npc[k].Hitbox))
                    {
                        Main.npc[k].teleporting = true;
                        Main.npc[k].Teleport(Main.npc[k].position + vector);
                    }
                }
            }
        }
        for (int l = 0; l < 255; l++)
        {
            Main.player[l].teleporting = false;
        }
        for (int m = 0; m < 200; m++)
        {
            Main.npc[m].teleporting = false;
        }
    }
References Terraria.RemoteClient.CheckSection(), Terraria.Main.netMode, Terraria.Main.npc, Terraria.Main.player, Terraria.NetMessage.SendData(), and Terraria.ID.NPCID.Sets.TeleportationImmune.
Referenced by Terraria.Wiring.TripWire().