TModLoader: Terraria.Wiring.MassWireOperationStep
MassWireOperationStep()
static ? bool Terraria.Wiring.MassWireOperationStep (Player user, Point pt, WiresUI::Settings::MultiToolMode mode, ref int wiresLeftToConsume, ref int actuatorsLeftToConstume) inline static private
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_029f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0340: Unknown result type (might be due to invalid IL or missing references)
        //IL_0346: Unknown result type (might be due to invalid IL or missing references)
        //IL_0309: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_0391: Unknown result type (might be due to invalid IL or missing references)
        //IL_0397: Unknown result type (might be due to invalid IL or missing references)
        //IL_035a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0361: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0239: Unknown result type (might be due to invalid IL or missing references)
        //IL_023f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_0258: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0404: Unknown result type (might be due to invalid IL or missing references)
        if (!WorldGen.InWorld(pt.X, pt.Y, 1))
        {
            return null;
        }
        Tile tile = Main.tile[pt.X, pt.Y];
        if (tile == null)
        {
            return null;
        }
        if (user != null && !user.CanDoWireStuffHere(pt.X, pt.Y))
        {
            return null;
        }
        if (!mode.HasFlag(WiresUI.Settings.MultiToolMode.Cutter))
        {
            if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Red) && !tile.wire())
            {
                if (wiresLeftToConsume <= 0)
                {
                    return false;
                }
                wiresLeftToConsume--;
                WorldGen.PlaceWire(pt.X, pt.Y);
                NetMessage.SendData(17, -1, -1, null, 5, pt.X, pt.Y);
            }
            if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Green) && !tile.wire3())
            {
                if (wiresLeftToConsume <= 0)
                {
                    return false;
                }
                wiresLeftToConsume--;
                WorldGen.PlaceWire3(pt.X, pt.Y);
                NetMessage.SendData(17, -1, -1, null, 12, pt.X, pt.Y);
            }
            if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Blue) && !tile.wire2())
            {
                if (wiresLeftToConsume <= 0)
                {
                    return false;
                }
                wiresLeftToConsume--;
                WorldGen.PlaceWire2(pt.X, pt.Y);
                NetMessage.SendData(17, -1, -1, null, 10, pt.X, pt.Y);
            }
            if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Yellow) && !tile.wire4())
            {
                if (wiresLeftToConsume <= 0)
                {
                    return false;
                }
                wiresLeftToConsume--;
                WorldGen.PlaceWire4(pt.X, pt.Y);
                NetMessage.SendData(17, -1, -1, null, 16, pt.X, pt.Y);
            }
            if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Actuator) && !tile.actuator())
            {
                if (actuatorsLeftToConstume <= 0)
                {
                    return false;
                }
                actuatorsLeftToConstume--;
                WorldGen.PlaceActuator(pt.X, pt.Y);
                NetMessage.SendData(17, -1, -1, null, 8, pt.X, pt.Y);
            }
        }
        if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Cutter))
        {
            if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Red) && tile.wire() && WorldGen.KillWire(pt.X, pt.Y))
            {
                NetMessage.SendData(17, -1, -1, null, 6, pt.X, pt.Y);
            }
            if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Green) && tile.wire3() && WorldGen.KillWire3(pt.X, pt.Y))
            {
                NetMessage.SendData(17, -1, -1, null, 13, pt.X, pt.Y);
            }
            if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Blue) && tile.wire2() && WorldGen.KillWire2(pt.X, pt.Y))
            {
                NetMessage.SendData(17, -1, -1, null, 11, pt.X, pt.Y);
            }
            if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Yellow) && tile.wire4() && WorldGen.KillWire4(pt.X, pt.Y))
            {
                NetMessage.SendData(17, -1, -1, null, 17, pt.X, pt.Y);
            }
            if (mode.HasFlag(WiresUI.Settings.MultiToolMode.Actuator) && tile.actuator() && WorldGen.KillActuator(pt.X, pt.Y))
            {
                NetMessage.SendData(17, -1, -1, null, 9, pt.X, pt.Y);
            }
        }
        return true;
    }
References Terraria.Tile.actuator(), Terraria.WorldGen.InWorld(), Terraria.WorldGen.KillActuator(), Terraria.WorldGen.KillWire(), Terraria.WorldGen.KillWire2(), Terraria.WorldGen.KillWire3(), Terraria.WorldGen.KillWire4(), Terraria.WorldGen.PlaceActuator(), Terraria.WorldGen.PlaceWire(), Terraria.WorldGen.PlaceWire2(), Terraria.WorldGen.PlaceWire3(), Terraria.WorldGen.PlaceWire4(), Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), and Terraria.Tile.wire4().