TModLoader: Terraria.Wiring.TripWire
TripWire()
static void Terraria.Wiring.TripWire (int left, int top, int width, int height) inline static
Used to send a single to wiring wired up to the specified area. The parameters represent the tile coordinates where wire signals will be sent. Mechanism tiles such as F:Terraria.ID.TileID.Switches, F:Terraria.ID.TileID.PressurePlates, F:Terraria.ID.TileID.Timers, and F:Terraria.ID.TileID.LogicSensor use this method as part of their interaction code.
Parameters
left
top
width
height
Definition at line 607 of file Wiring.cs.
    {
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0248: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_035f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0364: Unknown result type (might be due to invalid IL or missing references)
        //IL_0375: Unknown result type (might be due to invalid IL or missing references)
        //IL_037a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0476: Unknown result type (might be due to invalid IL or missing references)
        //IL_047b: Unknown result type (might be due to invalid IL or missing references)
        //IL_048c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0491: Unknown result type (might be due to invalid IL or missing references)
        //IL_04aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_04af: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c4: Unknown result type (might be due to invalid IL or missing references)
        if (Main.netMode == 1)
        {
            return;
        }
        running = true;
        if (_wireList.Count != 0)
        {
            _wireList.Clear(quickClear: true);
        }
        if (_wireDirectionList.Count != 0)
        {
            _wireDirectionList.Clear(quickClear: true);
        }
        Vector2[] array = (Vector2[])(object)new Vector2[8];
        int num = 0;
        for (int i = left; i < left + width; i++)
        {
            for (int j = top; j < top + height; j++)
            {
                Point16 back3 = new Point16(i, j);
                Tile tile = Main.tile[i, j];
                if (tile != null && tile.wire())
                {
                    _wireList.PushBack(back3);
                }
            }
        }
        _teleport[0].X = -1f;
        _teleport[0].Y = -1f;
        _teleport[1].X = -1f;
        _teleport[1].Y = -1f;
        if (_wireList.Count > 0)
        {
            _numInPump = 0;
            _numOutPump = 0;
            HitWire(_wireList, 1);
            if (_numInPump > 0 && _numOutPump > 0)
            {
                XferWater();
            }
        }
        array[num++] = _teleport[0];
        array[num++] = _teleport[1];
        for (int k = left; k < left + width; k++)
        {
            for (int l = top; l < top + height; l++)
            {
                Point16 back4 = new Point16(k, l);
                Tile tile2 = Main.tile[k, l];
                if (tile2 != null && tile2.wire2())
                {
                    _wireList.PushBack(back4);
                }
            }
        }
        _teleport[0].X = -1f;
        _teleport[0].Y = -1f;
        _teleport[1].X = -1f;
        _teleport[1].Y = -1f;
        if (_wireList.Count > 0)
        {
            _numInPump = 0;
            _numOutPump = 0;
            HitWire(_wireList, 2);
            if (_numInPump > 0 && _numOutPump > 0)
            {
                XferWater();
            }
        }
        array[num++] = _teleport[0];
        array[num++] = _teleport[1];
        _teleport[0].X = -1f;
        _teleport[0].Y = -1f;
        _teleport[1].X = -1f;
        _teleport[1].Y = -1f;
        for (int m = left; m < left + width; m++)
        {
            for (int n = top; n < top + height; n++)
            {
                Point16 back2 = new Point16(m, n);
                Tile tile3 = Main.tile[m, n];
                if (tile3 != null && tile3.wire3())
                {
                    _wireList.PushBack(back2);
                }
            }
        }
        if (_wireList.Count > 0)
        {
            _numInPump = 0;
            _numOutPump = 0;
            HitWire(_wireList, 3);
            if (_numInPump > 0 && _numOutPump > 0)
            {
                XferWater();
            }
        }
        array[num++] = _teleport[0];
        array[num++] = _teleport[1];
        _teleport[0].X = -1f;
        _teleport[0].Y = -1f;
        _teleport[1].X = -1f;
        _teleport[1].Y = -1f;
        for (int num2 = left; num2 < left + width; num2++)
        {
            for (int num3 = top; num3 < top + height; num3++)
            {
                Point16 back = new Point16(num2, num3);
                Tile tile4 = Main.tile[num2, num3];
                if (tile4 != null && tile4.wire4())
                {
                    _wireList.PushBack(back);
                }
            }
        }
        if (_wireList.Count > 0)
        {
            _numInPump = 0;
            _numOutPump = 0;
            HitWire(_wireList, 4);
            if (_numInPump > 0 && _numOutPump > 0)
            {
                XferWater();
            }
        }
        array[num++] = _teleport[0];
        array[num++] = _teleport[1];
        running = false;
        for (int num4 = 0; num4 < 8; num4 += 2)
        {
            _teleport[0] = array[num4];
            _teleport[1] = array[num4 + 1];
            if (_teleport[0].X >= 0f && _teleport[1].X >= 0f)
            {
                Teleport();
            }
        }
        PixelBoxPass();
        LogicGatePass();
    }
References Terraria.Wiring._numInPump, Terraria.Wiring._numOutPump, Terraria.Wiring._teleport, Terraria.Wiring._wireDirectionList, Terraria.Wiring._wireList, Terraria.Wiring.HitWire(), Terraria.Wiring.LogicGatePass(), Terraria.Main.netMode, Terraria.Wiring.PixelBoxPass(), Terraria.Wiring.running, Terraria.Wiring.Teleport(), Terraria.Main.tile, Terraria.Tile.wire(), and Terraria.Wiring.XferWater().
Referenced by Terraria.Wiring.HitSwitch(), Terraria.Wiring.LogicGatePass(), and Terraria.Wiring.UpdateMech().