TModLoader: Terraria.Wiring.ToggleCandle
ToggleCandle()
static void Terraria.Wiring.ToggleCandle (int i, int j, Tile tileCache, bool? forcedStateWhereTrueIsOn) inline static
Definition at line 2879 of file Wiring.cs.
    {
        short num = 18;
        if (tileCache.frameX > 0)
        {
            num = -18;
        }
        bool flag = tileCache.frameX > 0;
        if (!forcedStateWhereTrueIsOn.HasValue || !forcedStateWhereTrueIsOn.Value != flag)
        {
            tileCache.frameX += num;
            NetMessage.SendTileSquare(-1, i, j, 3);
        }
    }
References Terraria.Tile.frameX, and Terraria.NetMessage.SendTileSquare().
Referenced by Terraria.Wiring.HitWireSingle(), and Terraria.WorldGen.TryToggleLight().