TModLoader: Terraria.Wiring.GeyserTrap
GeyserTrap()
static void Terraria.Wiring.GeyserTrap (int i, int j) inline static private
    {
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        Tile tile = Main.tile[i, j];
        if (tile.type != 443)
        {
            return;
        }
        int num = tile.frameX / 36;
        int num2 = i - (tile.frameX - num * 36) / 18;
        if (CheckMech(num2, j, 200))
        {
            Vector2 zero = Vector2.Zero;
            Vector2 zero2 = Vector2.Zero;
            int num3 = 654;
            int damage = 20;
            if (num < 2)
            {
                zero = new Vector2((float)(num2 + 1), (float)j) * 16f;
                ((Vector2)(ref zero2))._002Ector(0f, -8f);
            }
            else
            {
                zero = new Vector2((float)(num2 + 1), (float)(j + 1)) * 16f;
                ((Vector2)(ref zero2))._002Ector(0f, 8f);
            }
            if (num3 != 0)
            {
                Projectile.NewProjectile(GetProjectileSource(num2, j), (int)zero.X, (int)zero.Y, zero2.X, zero2.Y, num3, damage, 2f, Main.myPlayer);
            }
        }
    }
References Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.Wiring.HitSwitch(), and Terraria.Wiring.HitWireSingle().