TModLoader: Terraria.Wiring.HitSwitch
HitSwitch()
static void Terraria.Wiring.HitSwitch (int i, int j) inline static
    {
        if (!WorldGen.InWorld(i, j) || Main.tile[i, j] == null)
        {
            return;
        }
        Tile tile = Main.tile[i, j];
        if (tile.type != 135)
        {
            tile = Main.tile[i, j];
            if (tile.type != 314)
            {
                tile = Main.tile[i, j];
                if (tile.type != 423)
                {
                    tile = Main.tile[i, j];
                    if (tile.type != 428)
                    {
                        tile = Main.tile[i, j];
                        if (tile.type != 442)
{
                            tile = Main.tile[i, j];
                            if (tile.type != 476)
{
                                tile = Main.tile[i, j];
                                if (tile.type == 440)
{
                                    SoundEngine.PlaySound(28, i * 16 + 16, j * 16 + 16, 0);
                                    TripWire(i, j, 3, 3);
                                    return;
                                }
                                tile = Main.tile[i, j];
                                if (tile.type == 136)
{
                                    tile = Main.tile[i, j];
                                    if (tile.frameY == 0)
{
                                        tile = Main.tile[i, j];
                                        tile.frameY = 18;
                                    }
                                    else
{
                                        tile = Main.tile[i, j];
                                        tile.frameY = 0;
                                    }
                                    SoundEngine.PlaySound(28, i * 16, j * 16, 0);
                                    TripWire(i, j, 1, 1);
                                    return;
                                }
                                tile = Main.tile[i, j];
                                if (tile.type == 443)
{
                                    GeyserTrap(i, j);
                                    return;
                                }
                                tile = Main.tile[i, j];
                                if (tile.type == 144)
{
                                    tile = Main.tile[i, j];
                                    if (tile.frameY == 0)
{
                                        tile = Main.tile[i, j];
                                        tile.frameY = 18;
                                        if (Main.netMode != 1)
{
                                            CheckMech(i, j, 18000);
                                        }
                                    }
                                    else
{
                                        tile = Main.tile[i, j];
                                        tile.frameY = 0;
                                    }
                                    SoundEngine.PlaySound(28, i * 16, j * 16, 0);
                                    return;
                                }
                                tile = Main.tile[i, j];
                                if (tile.type != 441)
{
                                    tile = Main.tile[i, j];
                                    if (tile.type != 468)
{
                                        tile = Main.tile[i, j];
                                        if (tile.type == 467)
{
                                            tile = Main.tile[i, j];
                                            if (tile.frameX / 36 == 4)
{
                                                tile = Main.tile[i, j];
                                                int num3 = tile.frameX / 18 * -1;
                                                tile = Main.tile[i, j];
                                                int num4 = tile.frameY / 18 * -1;
                                                num3 %= 4;
                                                if (num3 < -1)
{
                                                    num3 += 2;
                                                }
                                                num3 += i;
                                                num4 += j;
                                                SoundEngine.PlaySound(28, i * 16, j * 16, 0);
                                                TripWire(num3, num4, 2, 2);
                                            }
                                            return;
                                        }
                                        tile = Main.tile[i, j];
                                        if (tile.type != 132)
{
                                            tile = Main.tile[i, j];
                                            if (tile.type != 411)
{
                                                return;
                                            }
                                        }
                                        short num5 = 36;
                                        tile = Main.tile[i, j];
                                        int num6 = tile.frameX / 18 * -1;
                                        tile = Main.tile[i, j];
                                        int num7 = tile.frameY / 18 * -1;
                                        num6 %= 4;
                                        if (num6 < -1)
{
                                            num6 += 2;
                                            num5 = -36;
                                        }
                                        num6 += i;
                                        num7 += j;
                                        if (Main.netMode != 1)
{
                                            tile = Main.tile[num6, num7];
                                            if (tile.type == 411)
{
                                                CheckMech(num6, num7, 60);
                                            }
                                        }
                                        for (int k = num6; k < num6 + 2; k++)
{
                                            for (int l = num7; l < num7 + 2; l++)
{
                                                tile = Main.tile[k, l];
                                                if (tile.type != 132)
{
                                                    tile = Main.tile[k, l];
                                                    if (tile.type != 411)
{
                                                        continue;
                                                    }
                                                }
                                                tile = Main.tile[k, l];
                                                tile.frameX += num5;
                                            }
                                        }
                                        WorldGen.TileFrame(num6, num7);
                                        SoundEngine.PlaySound(28, i * 16, j * 16, 0);
                                        TripWire(num6, num7, 2, 2);
                                        return;
                                    }
                                }
                                tile = Main.tile[i, j];
                                int num = tile.frameX / 18 * -1;
                                tile = Main.tile[i, j];
                                int num2 = tile.frameY / 18 * -1;
                                num %= 4;
                                if (num < -1)
{
                                    num += 2;
                                }
                                num += i;
                                num2 += j;
                                SoundEngine.PlaySound(28, i * 16, j * 16, 0);
                                TripWire(num, num2, 2, 2);
                                return;
                            }
                        }
                    }
                }
            }
        }
        SoundEngine.PlaySound(28, i * 16, j * 16, 0);
        TripWire(i, j, 1, 1);
    }
References Terraria.Wiring.CheckMech(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Wiring.GeyserTrap(), Terraria.WorldGen.InWorld(), Terraria.Main.netMode, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Terraria.Wiring.TripWire(), and Terraria.Tile.type.
Referenced by Terraria.MessageBuffer.GetData(), Terraria.Minecart.HitTrackSwitch(), Terraria.Wiring.HitWireSingle(), Terraria.GameContent.Tile_Entities.TELogicSensor.Kill(), Terraria.GameContent.PressurePlateHelper.PokeLocation(), Terraria.GameContent.Golf.GolfHelper.ContactListener.PutBallInCup(), Terraria.WorldGen.ReplaceTIle_DoActualReplacement(), Terraria.Collision.SwitchTiles(), Terraria.Player.TileInteractionsUse(), Terraria.WorldGen.ToggleGemLock(), Terraria.Player.TryLandingOnDetonator(), and Terraria.GameContent.Tile_Entities.TELogicSensor.UpdateEndInternal().