TModLoader: Terraria.Wiring.MassWireOperationInner
MassWireOperationInner()
static void Terraria.Wiring.MassWireOperationInner (Player user, Point ps, Point pe, Vector2 dropPoint, bool dir, ref int wireCount, ref int actuatorCount) inline static private
Definition at line 3215 of file Wiring.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0137: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_00de: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        Math.Abs(ps.X - pe.X);
        Math.Abs(ps.Y - pe.Y);
        int num = Math.Sign(pe.X - ps.X);
        int num2 = Math.Sign(pe.Y - ps.Y);
        WiresUI.Settings.MultiToolMode toolMode = WiresUI.Settings.ToolMode;
        Point pt = default(Point);
        bool flag = false;
        Item.StartCachingType(530);
        Item.StartCachingType(849);
        bool flag2 = dir;
        int num3;
        int num4;
        int num5;
        if (flag2)
        {
            pt.X = ps.X;
            num3 = ps.Y;
            num4 = pe.Y;
            num5 = num2;
        }
        else
        {
            pt.Y = ps.Y;
            num3 = ps.X;
            num4 = pe.X;
            num5 = num;
        }
        for (int i = num3; i != num4; i += num5)
        {
            if (flag)
            {
                break;
            }
            if (flag2)
            {
                pt.Y = i;
            }
            else
            {
                pt.X = i;
            }
            bool? flag3 = MassWireOperationStep(user, pt, toolMode, ref wireCount, ref actuatorCount);
            if (flag3.HasValue && !flag3.Value)
            {
                flag = true;
                break;
            }
        }
        if (flag2)
        {
            pt.Y = pe.Y;
            num3 = ps.X;
            num4 = pe.X;
            num5 = num;
        }
        else
        {
            pt.X = pe.X;
            num3 = ps.Y;
            num4 = pe.Y;
            num5 = num2;
        }
        for (int j = num3; j != num4; j += num5)
        {
            if (flag)
            {
                break;
            }
            if (!flag2)
            {
                pt.Y = j;
            }
            else
            {
                pt.X = j;
            }
            bool? flag4 = MassWireOperationStep(user, pt, toolMode, ref wireCount, ref actuatorCount);
            if (flag4.HasValue && !flag4.Value)
            {
                flag = true;
                break;
            }
        }
        if (!flag)
        {
            MassWireOperationStep(user, pe, toolMode, ref wireCount, ref actuatorCount);
        }
        IEntitySource source_Misc = user.GetSource_Misc(ItemSourceID.ToContextString(5));
        Item.DropCache(source_Misc, dropPoint, Vector2.Zero, 530);
        Item.DropCache(source_Misc, dropPoint, Vector2.Zero, 849);
    }
References Terraria.Item.DropCache(), Terraria.Item.StartCachingType(), Terraria.ID.ItemSourceID.ToContextString(), and Terraria.GameContent.UI.WiresUI.Settings.ToolMode.
Referenced by Terraria.Wiring.MassWireOperation().