TModLoader: Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress.DownloadMods
DownloadMods()
void Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress.DownloadMods () inline private
Definition at line 73 of file UIDownloadProgress.cs.
    {
        downloadTimer.Start();
        _downloadFile = _downloads.First();
        if (_downloadFile != null)
        {
            _progressBar.UpdateProgress(0f);
            _progressBar.DisplayText = Language.GetTextValue("tModLoader.MBDownloadingMod", _downloadFile.DisplayText);
            _downloadFile.Download(_cts.Token, UpdateDownloadProgress).ContinueWith(HandleNextDownload, _cts.Token);
        }
    }
References Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress._cts, Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress._downloadFile, Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress._downloads, Terraria.ModLoader.UI.UIProgress._progressBar, Terraria.ModLoader.UI.DownloadManager.DownloadFile.DisplayText, Terraria.ModLoader.UI.DownloadManager.DownloadFile.Download(), Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress.downloadTimer, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress.HandleNextDownload(), Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress.UpdateDownloadProgress(), and Terraria.ModLoader.UI.UIProgressBar.UpdateProgress().
Referenced by Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress.HandleNextDownload(), and Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress.OnActivate().