TModLoader: Terraria.IngameOptions.DrawValueBar
DrawValueBar()
static float Terraria.IngameOptions.DrawValueBar (SpriteBatch sb, float scale, float perc, int lockState = 0, Utils::ColorLerpMethod colorMethod = null) inline static
Definition at line 2000 of file IngameOptions.cs.
    {
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0160: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_019b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_020d: Unknown result type (might be due to invalid IL or missing references)
        if (colorMethod == null)
        {
            colorMethod = Utils.ColorLerp_BlackToWhite;
        }
        Texture2D value = TextureAssets.ColorBar.Value;
        Vector2 vector = new Vector2((float)value.Width, (float)value.Height) * scale;
        valuePosition.X -= (int)vector.X;
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector((int)valuePosition.X, (int)valuePosition.Y - (int)vector.Y / 2, (int)vector.X, (int)vector.Y);
        Rectangle destinationRectangle = rectangle;
        sb.Draw(value, rectangle, Color.White);
        int num = 167;
        float num2 = (float)rectangle.X + 5f * scale;
        float num3 = (float)rectangle.Y + 4f * scale;
        for (float num4 = 0f; num4 < (float)num; num4 += 1f)
        {
            float percent = num4 / (float)num;
            sb.Draw(TextureAssets.ColorBlip.Value, new Vector2(num2 + num4 * scale, num3), (Rectangle?)null, colorMethod(percent), 0f, Vector2.Zero, scale, (SpriteEffects)0, 0f);
        }
        ((Rectangle)(ref rectangle)).Inflate((int)(-5f * scale), 0);
        bool flag = ((Rectangle)(ref rectangle)).Contains(new Point(Main.mouseX, Main.mouseY));
        if (lockState == 2)
        {
            flag = false;
        }
        if (flag || lockState == 1)
        {
            sb.Draw(TextureAssets.ColorHighlight.Value, destinationRectangle, Main.OurFavoriteColor);
        }
        sb.Draw(TextureAssets.ColorSlider.Value, new Vector2(num2 + 167f * scale * perc, num3 + 4f * scale), (Rectangle?)null, Color.White, 0f, new Vector2(0.5f * (float)TextureAssets.ColorSlider.Width(), 0.5f * (float)TextureAssets.ColorSlider.Height()), scale, (SpriteEffects)0, 0f);
        if (Main.mouseX >= rectangle.X && Main.mouseX <= rectangle.X + rectangle.Width)
        {
            inBar = flag;
            return (float)(Main.mouseX - rectangle.X) / (float)rectangle.Width;
        }
        inBar = false;
        if (rectangle.X >= Main.mouseX)
        {
            return 0f;
        }
        return 1f;
    }
References Terraria.GameContent.TextureAssets.ColorBar, Terraria.GameContent.TextureAssets.ColorBlip, Terraria.GameContent.TextureAssets.ColorHighlight, Terraria.Utils.ColorLerp_BlackToWhite(), Terraria.GameContent.TextureAssets.ColorSlider, Terraria.Main.mouseX, Terraria.Main.mouseY, and Terraria.Main.OurFavoriteColor.
Referenced by Terraria.IngameOptions.Draw(), Terraria.Main.DrawMenu(), and Terraria.GameContent.UI.Elements.UIKeybindingSliderItem.DrawSelf().