TModLoader: Terraria.Localization.LanguageManager.LoadActiveCultureTranslationsFromSources
LoadActiveCultureTranslationsFromSources()
void Terraria.Localization.LanguageManager.LoadActiveCultureTranslationsFromSources () inline private
    {
        IContentSource[] contentSources = _contentSources;
        string assetNameStart = string.Concat(str2: ActiveCulture.Name, str0: "Localization", str1: Path.DirectorySeparatorChar.ToString()).ToLower();
        IContentSource[] array = contentSources;
        foreach (IContentSource item in array)
        {
            foreach (string item2 in item.GetAllAssetsStartingWith(assetNameStart))
            {
                string extension = item.GetExtension(item2);
                if (!(extension == ".json") && !(extension == ".csv"))
                {
                    continue;
                }
                using Stream stream = item.OpenStream(item2);
                using StreamReader streamReader = new StreamReader(stream);
                string fileText = streamReader.ReadToEnd();
                if (extension == ".json")
                {
                    LoadLanguageFromFileTextJson(fileText, canCreateCategories: false);
                }
                if (extension == ".csv")
                {
                    LoadLanguageFromFileTextCsv(fileText);
                }
            }
        }
    }
References Terraria.Localization.LanguageManager._contentSources, Terraria.Localization.LanguageManager.ActiveCulture, Terraria.Localization.LanguageManager.LoadLanguageFromFileTextCsv(), Terraria.Localization.LanguageManager.LoadLanguageFromFileTextJson(), and Terraria.Localization.GameCulture.Name.
Referenced by Terraria.Localization.LanguageManager.ReloadLanguage().