TModLoader: Terraria.Localization.LanguageManager.ReloadLanguage
ReloadLanguage()
void Terraria.Localization.LanguageManager.ReloadLanguage (bool resetValuesToKeysFirst = true) inline package
Definition at line 170 of file LanguageManager.cs.
    {
        if (resetValuesToKeysFirst)
        {
            SetAllTextValuesToKeys();
        }
        LoadFilesForCulture(_fallbackCulture);
        if (ActiveCulture != _fallbackCulture)
        {
            LoadFilesForCulture(ActiveCulture);
        }
        LoadActiveCultureTranslationsFromSources();
        ProcessCopyCommandsInTexts();
        RecalculateBoundTextValues();
        ChatInitializer.PrepareAliases();
        SystemLoader.OnLocalizationsLoaded();
    }
References Terraria.Localization.LanguageManager._fallbackCulture, Terraria.Localization.LanguageManager.ActiveCulture, Terraria.Localization.LanguageManager.LoadActiveCultureTranslationsFromSources(), Terraria.Localization.LanguageManager.LoadFilesForCulture(), Terraria.ModLoader.SystemLoader.OnLocalizationsLoaded(), Terraria.Initializers.ChatInitializer.PrepareAliases(), Terraria.Localization.LanguageManager.ProcessCopyCommandsInTexts(), Terraria.Localization.LanguageManager.RecalculateBoundTextValues(), and Terraria.Localization.LanguageManager.SetAllTextValuesToKeys().
Referenced by Terraria.ModLoader.ModContent.Load(), Terraria.Localization.LanguageManager.SetLanguage(), Terraria.Localization.LanguageManager.UnloadModdedEntries(), Terraria.ModLoader.LocalizationLoader.Update(), and Terraria.Localization.LanguageManager.UseSources().