TModLoader: Terraria.Localization.LanguageManager.ProcessCopyCommandsInTexts
ProcessCopyCommandsInTexts()
void Terraria.Localization.LanguageManager.ProcessCopyCommandsInTexts () inline private
Definition at line 545 of file LanguageManager.cs.
    {
        Regex referenceRegex = new Regex("{\\$([\\w\\.]+)(?:@(\\d+))?}", RegexOptions.Compiled);
        Regex argRemappingRegex = new Regex("(?<={\\^?)(\\d+)(?=(?::[^\\r\\n]+?)?})", RegexOptions.Compiled);
        HashSet<LocalizedText> processed = new HashSet<LocalizedText>();
        foreach (LocalizedText text2 in _localizedTexts.Values)
        {
            Process(text2);
        }
        string FindKeyInScope(string key, string scope)
        {
            if (Exists(key))
            {
                return key;
            }
            string[] splitKey = scope.Split(".");
            for (int i = splitKey.Length - 1; i >= 0; i--)
            {
                string combinedKey = string.Join(".", splitKey.Take(i + 1)) + "." + key;
                if (Exists(combinedKey))
                {
                    return combinedKey;
                }
            }
            return key;
        }
        void Process(LocalizedText text)
        {
            if (processed.Add(text))
            {
                string newValue = referenceRegex.Replace(text.Value, delegate(Match match)
                {
                    LocalizedText text3 = GetText(FindKeyInScope(match.Groups[1].Value, text.Key));
                    Process(text3);
                    string text4 = text3.Value;
                    if (match.Groups[2].Success && int.TryParse(match.Groups[2].Value, out var offset))
                    {
                        text4 = argRemappingRegex.Replace(text4, (Match match) => (int.Parse(match.Groups[1].Value) + offset).ToString());
                    }
                    return text4;
                });
                text.SetValue(newValue);
            }
        }
    }
References Terraria.Localization.LanguageManager._localizedTexts, Terraria.Localization.LanguageManager.Exists(), Terraria.Localization.LanguageManager.GetText(), Terraria.Localization.LocalizedText.Key, Terraria.Localization.LocalizedText.SetValue(), and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Localization.LanguageManager.ReloadLanguage().