TModLoader: Terraria.Social.Steam.SteamedWraps.InnerDownloadHandler
InnerDownloadHandler()
static void Terraria.Social.Steam.SteamedWraps.InnerDownloadHandler (IDownloadProgress uiProgress, PublishedFileId_t publishId) inline static private
Definition at line 653 of file SteamedWraps.cs.
    {
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        int nextPercentageToLog = 10;
        int numFailures = 0;
        ulong dlBytes = default(ulong);
        ulong totalBytes = default(ulong);
        while (!IsWorkshopItemInstalled(publishId))
        {
            if (SteamClient)
            {
                SteamUGC.GetItemDownloadInfo(publishId, ref dlBytes, ref totalBytes);
            }
            else
            {
                SteamGameServerUGC.GetItemDownloadInfo(publishId, ref dlBytes, ref totalBytes);
            }
            if (totalBytes == 0L)
            {
                if (numFailures++ < 10)
                {
                    Thread.Sleep(100);
                    continue;
                }
                break;
            }
            uiProgress?.UpdateDownloadProgress((float)dlBytes / (float)Math.Max(totalBytes, 1uL), (long)dlBytes, (long)totalBytes);
            int percentage = (int)MathF.Round((float)dlBytes / (float)totalBytes * 100f);
            if (percentage >= nextPercentageToLog)
            {
                Utils.LogAndConsoleInfoMessage(Language.GetTextValue("tModLoader.DownloadProgress", percentage));
                nextPercentageToLog = percentage + 10;
                if (nextPercentageToLog > 100 && nextPercentageToLog != 110)
                {
                    nextPercentageToLog = 100;
                }
            }
            if ((float)(dlBytes / totalBytes) != 1f)
            {
                continue;
            }
            break;
        }
    }
References Terraria.Localization.Language.GetTextValue(), Terraria.Social.Steam.SteamedWraps.IsWorkshopItemInstalled(), Terraria.Utils.LogAndConsoleInfoMessage(), and Terraria.Social.Steam.SteamedWraps.SteamClient.
Referenced by Terraria.Social.Steam.SteamedWraps.Download().