TModLoader: Terraria.Social.Steam.SteamedWraps.ModifyQueryHandle
ModifyQueryHandle()
static void Terraria.Social.Steam.SteamedWraps.ModifyQueryHandle (ref UGCQueryHandle_t qHandle, QueryParameters qP) inline static private
    {
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        FilterByText(ref qHandle, qP.searchGeneric);
        FilterByTags(ref qHandle, qP.searchTags);
        FilterModSide(ref qHandle, qP.modSideFilter);
        if (SteamClient)
        {
            SteamUGC.SetAllowCachedResponse(qHandle, 0u);
            SteamUGC.SetLanguage(qHandle, GetCurrentSteamLangKey());
            SteamUGC.SetReturnChildren(qHandle, true);
            SteamUGC.SetReturnKeyValueTags(qHandle, true);
            SteamUGC.SetReturnPlaytimeStats(qHandle, 30u);
        }
        else if (SteamAvailable)
        {
            SteamGameServerUGC.SetAllowCachedResponse(qHandle, 0u);
            SteamGameServerUGC.SetLanguage(qHandle, GetCurrentSteamLangKey());
            SteamGameServerUGC.SetReturnChildren(qHandle, true);
            SteamGameServerUGC.SetReturnKeyValueTags(qHandle, true);
            SteamGameServerUGC.SetReturnPlaytimeStats(qHandle, 30u);
        }
    }
References Terraria.Social.Steam.SteamedWraps.FilterByTags(), Terraria.Social.Steam.SteamedWraps.FilterByText(), Terraria.Social.Steam.SteamedWraps.FilterModSide(), Terraria.Social.Steam.SteamedWraps.GetCurrentSteamLangKey(), Terraria.Social.Steam.SteamedWraps.SteamAvailable, and Terraria.Social.Steam.SteamedWraps.SteamClient.
Referenced by Terraria.Social.Steam.SteamedWraps.GenerateAndSubmitModBrowserQuery(), and Terraria.Social.Steam.SteamedWraps.GenerateDirectItemsQuery().