TModLoader: Terraria.Social.Steam.SteamedWraps.GenerateAndSubmitModBrowserQuery
GenerateAndSubmitModBrowserQuery()
static SteamAPICall_t Terraria.Social.Steam.SteamedWraps.GenerateAndSubmitModBrowserQuery (uint page, QueryParameters qP, string internalName = null) inline static
    {
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        if (SteamClient)
        {
            UGCQueryHandle_t qHandle = SteamUGC.CreateQueryAllUGCRequest(CalculateQuerySort(qP), (EUGCMatchingUGCType)0, new AppId_t(1281930u), new AppId_t(1281930u), page);
            ModifyQueryHandle(ref qHandle, qP);
            FilterByInternalName(ref qHandle, internalName);
            return SteamUGC.SendQueryUGCRequest(qHandle);
        }
        if (SteamAvailable)
        {
            UGCQueryHandle_t qHandle2 = SteamGameServerUGC.CreateQueryAllUGCRequest(CalculateQuerySort(qP), (EUGCMatchingUGCType)0, new AppId_t(1281930u), new AppId_t(1281930u), page);
            ModifyQueryHandle(ref qHandle2, qP);
            FilterByInternalName(ref qHandle2, internalName);
            return SteamGameServerUGC.SendQueryUGCRequest(qHandle2);
        }
        return default(SteamAPICall_t);
    }
References Terraria.Social.Steam.SteamedWraps.CalculateQuerySort(), Terraria.Social.Steam.SteamedWraps.FilterByInternalName(), Terraria.Social.Steam.SteamedWraps.ModifyQueryHandle(), Terraria.Social.Steam.SteamedWraps.SteamAvailable, and Terraria.Social.Steam.SteamedWraps.SteamClient.
Referenced by Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.QueryAllWorkshopItems(), and Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.TrySearchByInternalName().