TModLoader: Terraria.Social.Steam.SteamedWraps.Initialize
Initialize()
static void Terraria.Social.Steam.SteamedWraps.Initialize () inline static package
    {
        if (!FamilyShared && SocialAPI.Mode == SocialMode.Steam)
        {
            SteamAvailable = true;
            SteamClient = true;
            Logging.tML.Info((object)"SteamBackend: Running standard Steam Desktop Client API");
        }
        else if (!Main.dedServ && !TryInitViaGameServer())
        {
            Utils.ShowFancyErrorMessage("Steam Game Server failed to Init. Steam Workshop downloading on GoG is unavailable. Make sure Steam is installed", 0);
        }
    }
References Terraria.Main.dedServ, Terraria.Social.Steam.SteamedWraps.FamilyShared, Terraria.Social.SocialAPI.Mode, Terraria.Utils.ShowFancyErrorMessage(), Terraria.Social.Steam.SteamedWraps.SteamAvailable, Terraria.Social.Steam.SteamedWraps.SteamClient, Terraria.ModLoader.Logging.tML, and Terraria.Social.Steam.SteamedWraps.TryInitViaGameServer().
Referenced by Terraria.Social.SocialAPI.Initialize().