TModLoader: Terraria.Social.Steam.SteamedWraps.Download
Download()
static void Terraria.Social.Steam.SteamedWraps.Download (PublishedFileId_t publishId, IDownloadProgress uiProgress = null, bool forceUpdate = false) inline static package
Updates and/or Downloads the Item specified by publishId.
    {
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        if (!SteamAvailable)
        {
            return;
        }
        if (SteamClient)
        {
            SteamUGC.SubscribeItem(publishId);
        }
        if (DoesWorkshopItemNeedUpdate(publishId) || forceUpdate)
        {
            Utils.LogAndConsoleInfoMessage(Language.GetTextValue("tModLoader.SteamDownloader"));
            if (!((!SteamClient) ? SteamGameServerUGC.DownloadItem(publishId, true) : SteamUGC.DownloadItem(publishId, true)))
            {
                ReportCheckSteamLogs();
                throw new ArgumentException("Downloading Workshop Item failed due to unknown reasons");
            }
            InnerDownloadHandler(uiProgress, publishId);
            Utils.LogAndConsoleInfoMessage(Language.GetTextValue("tModLoader.EndDownload"));
        }
        else
        {
            Utils.LogAndConsoleErrorMessage(Language.GetTextValue("tModLoader.SteamRejectUpdate", publishId));
        }
    }
References Terraria.Social.Steam.SteamedWraps.DoesWorkshopItemNeedUpdate(), Terraria.Localization.Language.GetTextValue(), Terraria.Social.Steam.SteamedWraps.InnerDownloadHandler(), Terraria.Utils.LogAndConsoleErrorMessage(), Terraria.Utils.LogAndConsoleInfoMessage(), Terraria.Social.Steam.SteamedWraps.ReportCheckSteamLogs(), Terraria.Social.Steam.SteamedWraps.SteamAvailable, and Terraria.Social.Steam.SteamedWraps.SteamClient.
Referenced by Terraria.Social.Steam.WorkshopBrowserModule.DownloadItem(), and Terraria.Social.Steam.WorkshopSocialModule.TryGetInfoForMod().