TModLoader: Terraria.ID.ItemID.Sets.ExtractinatorMode
ExtractinatorMode
int [] Terraria.ID.ItemID.Sets.ExtractinatorMode = Factory.CreateIntSet(-1, 424, 0, 1103, 0, 3347, 3347, 2339, 2337, 2338, 2337, 2337, 2337, 4354, 4354, 4389, 4354, 4377, 4354, 4378, 4354, 5127, 4354, 5128, 4354) static
Indicates which extractinator type an item belongs to. An extractType of 0 represents the default extraction (Silt and Slush). 0, F:Terraria.ID.ItemID.DesertFossil, F:Terraria.ID.ItemID.OldShoe, and F:Terraria.ID.ItemID.LavaMoss are vanilla extraction types. Modded types by convention will correspond to the iconic item of the extraction type. The Extractinator wiki pagehas more info. Use this in conjunction with M:Terraria.ModLoader.ModItem.ExtractinatorUse(System.Int32,System.Int32@,System.Int32@) or M:Terraria.ModLoader.GlobalItem.ExtractinatorUse(System.Int32,System.Int32,System.Int32@,System.Int32@).
Referenced by Terraria.Player.PlaceThing_ItemInExtractinator(), Terraria.Player.SmartSelect_GetAvailableToolRanges(), Terraria.Player.SmartSelect_PickToolForStrategy(), and Terraria.Player.TileInteractionsMouseOver().