TModLoader: Terraria.ID.ItemID.Sets.OreDropsFromSlime
OreDropsFromSlime
Dictionary<int, (int minStack, int maxStack)> Terraria.ID.ItemID.Sets.OreDropsFromSlime static
Initial value:
= new Dictionary<int, (int, int)>
        {
            {
                12,
                (3, 13)
            },
            {
                699,
                (3, 13)
            },
            {
                11,
                (3, 13)
            },
            {
                700,
                (3, 13)
            },
            {
                14,
                (3, 13)
            },
            {
                701,
                (3, 13)
            },
            {
                13,
                (3, 13)
            },
            {
                702,
                (3, 13)
            }
        }
Dictionary for defining what ores can spawn as bonus drop inside slime body. All items in this dictionary are equally likely to roll, and will drop with a stack size between minStack and maxStack (inclusive).
Stack sizes with less than 1 or where minStack is not strictly smaller than maxStack will lead to exceptions being thrown.
        {
            {
                12,
                (3, 13)
            },
            {
                699,
                (3, 13)
            },
            {
                11,
                (3, 13)
            },
            {
                700,
                (3, 13)
            },
            {
                14,
                (3, 13)
            },
            {
                701,
                (3, 13)
            },
            {
                13,
                (3, 13)
            },
            {
                702,
                (3, 13)
            }
        };
Referenced by Terraria.NPC.AI_001_Slimes_GenerateItemInsideBody(), Terraria.GameContent.ItemDropRules.SlimeBodyItemDropRule.GetDropInfo(), and Terraria.ModLoader.ItemLoader.ValidateDropsSet().