TModLoader: Terraria.ModLoader.MenuLoader.UpdateAndDrawModMenu
UpdateAndDrawModMenu()
static void Terraria.ModLoader.MenuLoader.UpdateAndDrawModMenu (SpriteBatch spriteBatch, GameTime gameTime, Color color, float logoRotation, float logoScale) inline static package
Definition at line 92 of file MenuLoader.cs.
    {
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_027a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0292: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0364: Unknown result type (might be due to invalid IL or missing references)
        //IL_036c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0393: Unknown result type (might be due to invalid IL or missing references)
        //IL_038c: Unknown result type (might be due to invalid IL or missing references)
        //IL_039d: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b1: Unknown result type (might be due to invalid IL or missing references)
        if (switchToMenu != null && switchToMenu != currentMenu)
        {
            currentMenu.OnDeselected();
            currentMenu = switchToMenu;
            currentMenu.OnSelected();
            if (currentMenu.IsNew)
            {
                currentMenu.IsNew = false;
                AddKnownMenu(currentMenu.FullName);
            }
        }
        switchToMenu = null;
        if (!loading && currentMenu.FullName != LastSelectedModMenu)
        {
            LastSelectedModMenu = currentMenu.FullName;
            Main.SaveSettings();
        }
        currentMenu.UserInterface.Update(gameTime);
        currentMenu.UserInterface.Draw(spriteBatch, gameTime);
        currentMenu.Update(Main.menuMode == 0);
        Texture2D logo = currentMenu.Logo.Value;
        Vector2 logoDrawPos = default(Vector2);
        ((Vector2)(ref logoDrawPos))._002Ector((float)(Main.screenWidth / 2), 100f);
        float scale = logoScale;
        if (currentMenu.PreDrawLogo(spriteBatch, ref logoDrawPos, ref logoRotation, ref scale, ref color))
        {
            spriteBatch.Draw(logo, logoDrawPos, (Rectangle?)new Rectangle(0, 0, logo.Width, logo.Height), color, logoRotation, new Vector2((float)logo.Width * 0.5f, (float)logo.Height * 0.5f), scale, (SpriteEffects)0, 0f);
        }
        currentMenu.PostDrawLogo(spriteBatch, logoDrawPos, logoRotation, scale, color);
        int newMenus;
        lock (menus)
        {
            string[] knownMenus = KnownMenus;
            foreach (ModMenu menu in menus)
            {
                menu.IsNew = menu.IsAvailable && !knownMenus.Contains(menu.FullName);
            }
            newMenus = menus.Count((ModMenu m) => m.IsNew);
        }
        string text = Language.GetTextValue("tModLoader.ModMenuSwap") + ": " + currentMenu.DisplayName + ((newMenus == 0) ? "" : (ModLoader.notifyNewMainMenuThemes ? $" ({newMenus} New)" : ""));
        Vector2 size = ChatManager.GetStringSize(FontAssets.MouseText.Value, ChatManager.ParseMessage(text, color).ToArray(), Vector2.One);
        Rectangle switchTextRect = (Rectangle)((Main.menuMode == 0) ? new Rectangle((int)((float)(Main.screenWidth / 2) - size.X / 2f), (int)((float)(Main.screenHeight - 2) - size.Y), (int)size.X, (int)size.Y) : Rectangle.Empty);
        if (((Rectangle)(ref switchTextRect)).Contains(Main.mouseX, Main.mouseY) && !Main.alreadyGrabbingSunOrMoon)
        {
            if (Main.mouseLeftRelease && Main.mouseLeft)
            {
                SoundEngine.PlaySound(in SoundID.MenuTick);
                OffsetModMenu(1);
            }
            else if (Main.mouseRightRelease && Main.mouseRight)
            {
                SoundEngine.PlaySound(in SoundID.MenuTick);
                OffsetModMenu(-1);
            }
        }
        if (Main.menuMode == 0)
        {
            ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, text, new Vector2((float)switchTextRect.X, (float)switchTextRect.Y), (Color)(((Rectangle)(ref switchTextRect)).Contains(Main.mouseX, Main.mouseY) ? Main.OurFavoriteColor : new Color(120, 120, 120, 76)), 0f, Vector2.Zero, Vector2.One);
        }
    }
References Terraria.ModLoader.MenuLoader.AddKnownMenu(), Terraria.Main.alreadyGrabbingSunOrMoon, Terraria.ModLoader.MenuLoader.currentMenu, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.ModLoader.ModType< TEntity, TModType >.FullName, Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.MenuLoader.KnownMenus, Terraria.ModLoader.MenuLoader.LastSelectedModMenu, Terraria.ModLoader.MenuLoader.loading, Terraria.Main.menuMode, Terraria.ModLoader.MenuLoader.menus, Terraria.ID.SoundID.MenuTick, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.ModLoader.MenuLoader.OffsetModMenu(), Terraria.Main.OurFavoriteColor, Terraria.UI.Chat.ChatManager.ParseMessage(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.SaveSettings(), Terraria.Main.screenHeight, Terraria.Main.screenWidth, and Terraria.ModLoader.MenuLoader.switchToMenu.
Referenced by Terraria.Main.DrawMenu().