TModLoader: Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 96 of file UIAchievementListItem.cs.
    {
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0107: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_0209: Unknown result type (might be due to invalid IL or missing references)
        //IL_021a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_0222: Unknown result type (might be due to invalid IL or missing references)
        //IL_022c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_0236: Unknown result type (might be due to invalid IL or missing references)
        //IL_0237: Unknown result type (might be due to invalid IL or missing references)
        //IL_023c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0240: Unknown result type (might be due to invalid IL or missing references)
        //IL_0244: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_0293: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0306: Unknown result type (might be due to invalid IL or missing references)
        //IL_0308: Unknown result type (might be due to invalid IL or missing references)
        //IL_030f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0314: Unknown result type (might be due to invalid IL or missing references)
        //IL_031d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_033d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0342: Unknown result type (might be due to invalid IL or missing references)
        //IL_0347: Unknown result type (might be due to invalid IL or missing references)
        //IL_0348: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0351: Unknown result type (might be due to invalid IL or missing references)
        //IL_0355: Unknown result type (might be due to invalid IL or missing references)
        //IL_0389: Unknown result type (might be due to invalid IL or missing references)
        //IL_038b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0392: Unknown result type (might be due to invalid IL or missing references)
        //IL_0397: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03be: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_041d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0424: Unknown result type (might be due to invalid IL or missing references)
        //IL_0429: Unknown result type (might be due to invalid IL or missing references)
        //IL_0465: Unknown result type (might be due to invalid IL or missing references)
        //IL_0467: Unknown result type (might be due to invalid IL or missing references)
        //IL_0471: Unknown result type (might be due to invalid IL or missing references)
        //IL_0476: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_04af: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_050b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0522: Unknown result type (might be due to invalid IL or missing references)
        //IL_0524: Unknown result type (might be due to invalid IL or missing references)
        //IL_0535: Unknown result type (might be due to invalid IL or missing references)
        //IL_053a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0546: Unknown result type (might be due to invalid IL or missing references)
        //IL_0496: Unknown result type (might be due to invalid IL or missing references)
        //IL_0498: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a7: Unknown result type (might be due to invalid IL or missing references)
        base.DrawSelf(spriteBatch);
        int num = _large.ToInt() * 6;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)num, 0f);
        _locked = !_achievement.IsCompleted;
        UpdateIconFrame();
        CalculatedStyle innerDimensions = GetInnerDimensions();
        CalculatedStyle dimensions = _achievementIconBorders.GetDimensions();
        float num2 = dimensions.X + dimensions.Width;
        Vector2 val = new Vector2(num2 + 7f, innerDimensions.Y);
        Tuple<decimal, decimal> trackerValues = GetTrackerValues();
        bool flag = false;
        if ((!(trackerValues.Item1 == 0m) || !(trackerValues.Item2 == 0m)) && _locked)
        {
            flag = true;
        }
        float num3 = innerDimensions.Width - dimensions.Width + 1f - (float)(num * 2);
        Vector2 baseScale = default(Vector2);
        ((Vector2)(ref baseScale))._002Ector(0.85f);
        Vector2 baseScale2 = default(Vector2);
        ((Vector2)(ref baseScale2))._002Ector(0.92f);
        string text = FontAssets.ItemStack.Value.CreateWrappedText(_achievement.Description.Value, (num3 - 20f) * (1f / baseScale2.X), Language.ActiveCulture.CultureInfo);
        Vector2 stringSize = ChatManager.GetStringSize(FontAssets.ItemStack.Value, text, baseScale2, num3);
        if (!_large)
        {
            stringSize = ChatManager.GetStringSize(FontAssets.ItemStack.Value, _achievement.Description.Value, baseScale2, num3);
        }
        float num4 = 38f + (float)(_large ? 20 : 0);
        if (stringSize.Y > num4)
        {
            baseScale2.Y *= num4 / stringSize.Y;
        }
        Color value = (_locked ? Color.Silver : Color.Gold);
        value = Color.Lerp(value, Color.White, base.IsMouseHovering ? 0.5f : 0f);
        Color value2 = (_locked ? Color.DarkGray : Color.Silver);
        value2 = Color.Lerp(value2, Color.White, base.IsMouseHovering ? 1f : 0f);
        Color color = (base.IsMouseHovering ? Color.White : Color.Gray);
        Vector2 vector2 = val - Vector2.UnitY * 2f + vector;
        DrawPanelTop(spriteBatch, vector2, num3, color);
        AchievementCategory category = _achievement.Category;
        vector2.Y += 2f;
        vector2.X += 4f;
        spriteBatch.Draw(_categoryTexture.Value, vector2, (Rectangle?)_categoryTexture.Frame(4, 2, (int)category), base.IsMouseHovering ? Color.White : Color.Silver, 0f, Vector2.Zero, 0.5f, (SpriteEffects)0, 0f);
        vector2.X += 4f;
        vector2.X += 17f;
        ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, _achievement.FriendlyName.Value, vector2, value, 0f, Vector2.Zero, baseScale, num3);
        vector2.X -= 17f;
        Vector2 position = val + Vector2.UnitY * 27f + vector;
        DrawPanelBottom(spriteBatch, position, num3, color);
        position.X += 8f;
        position.Y += 4f;
        ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, text, position, value2, 0f, Vector2.Zero, baseScale2);
        if (flag)
        {
            Vector2 vector3 = vector2 + Vector2.UnitX * num3 + Vector2.UnitY;
            string text2 = (int)trackerValues.Item1 + "/" + (int)trackerValues.Item2;
            Vector2 baseScale3 = default(Vector2);
            ((Vector2)(ref baseScale3))._002Ector(0.75f);
            Vector2 stringSize2 = ChatManager.GetStringSize(FontAssets.ItemStack.Value, text2, baseScale3);
            float progress = (float)(trackerValues.Item1 / trackerValues.Item2);
            float num5 = 80f;
            Color color2 = default(Color);
            ((Color)(ref color2))._002Ector(100, 255, 100);
            if (!base.IsMouseHovering)
            {
                color2 = Color.Lerp(color2, Color.Black, 0.25f);
            }
            Color color3 = default(Color);
            ((Color)(ref color3))._002Ector(255, 255, 255);
            if (!base.IsMouseHovering)
            {
                color3 = Color.Lerp(color3, Color.Black, 0.25f);
            }
            DrawProgressBar(spriteBatch, progress, vector3 - Vector2.UnitX * num5 * 0.7f, num5, color3, color2, color2.MultiplyRGBA(new Color(new Vector4(1f, 1f, 1f, 0.5f))));
            vector3.X -= num5 * 1.4f + stringSize2.X;
            ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, text2, vector3, value, 0f, new Vector2(0f, 0f), baseScale3, 90f);
        }
    }
References Terraria.GameContent.UI.Elements.UIAchievementListItem._achievement, Terraria.GameContent.UI.Elements.UIAchievementListItem._achievementIconBorders, Terraria.GameContent.UI.Elements.UIAchievementListItem._categoryTexture, Terraria.GameContent.UI.Elements.UIAchievementListItem._large, Terraria.GameContent.UI.Elements.UIAchievementListItem._locked, Terraria.Localization.Language.ActiveCulture, Terraria.Achievements.Achievement.Category, Terraria.Achievements.Achievement.Description, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawPanelBottom(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawPanelTop(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawProgressBar(), Terraria.Achievements.Achievement.FriendlyName, Terraria.UI.UIElement.GetDimensions(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.GameContent.UI.Elements.UIAchievementListItem.GetTrackerValues(), Terraria.Achievements.Achievement.IsCompleted, Terraria.GameContent.FontAssets.ItemStack, and Terraria.GameContent.UI.Elements.UIAchievementListItem.UpdateIconFrame().