TModLoader: Terraria.ModLoader.Core.AssemblyManager.GetDependencies
GetDependencies()
static IEnumerable< Mod > Terraria.ModLoader.Core.AssemblyManager.GetDependencies (Mod mod) inline static
    {
        return GetLoadContext(mod.Name).dependencies.Select((ModLoadContext m) => ModLoader.GetMod(mod.Name));
    }
References Terraria.ModLoader.Core.AssemblyManager.GetLoadContext(), Terraria.ModLoader.ModLoader.GetMod(), and Terraria.ModLoader.Mod.Name.
Referenced by Terraria.ModLoader.ModNet.AddNoSyncDeps().