TModLoader: Terraria.ModLoader.Core.AssemblyManager.JITAssemblies
JITAssemblies()
static void Terraria.ModLoader.Core.AssemblyManager.JITAssemblies (IEnumerable< Assembly > assemblies, PreJITFilter filter) inline static
Definition at line 417 of file AssemblyManager.cs.
    {
        ConcurrentQueue<(Exception exception, MethodBase method)> exceptions = new ConcurrentQueue<(Exception, MethodBase)>();
        foreach (Assembly assembly in assemblies)
        {
            MethodBase[] methodsToJIT = GetLoadableTypes(assembly).Where(filter.ShouldJIT).SelectMany((Type type) => (from m in ((IEnumerable<MethodBase>)(from m in type.GetMethods(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)
                    where !m.IsSpecialName
                    select m)).Concat((IEnumerable<MethodBase>)type.GetConstructors(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)).Concat(type.GetProperties(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic).Where(filter.ShouldJIT).SelectMany((PropertyInfo p) => p.GetAccessors()))
                where !m.IsAbstract && !m.ContainsGenericParameters && m.DeclaringType == type
                select m).Where(filter.ShouldJIT)).ToArray();
            if (Environment.ProcessorCount > 1)
            {
                methodsToJIT.AsParallel().AsUnordered().ForAll(delegate(MethodBase method)
                {
                    try
                    {
                        ForceJITOnMethod(method);
                    }
                    catch (Exception item)
                    {
                        exceptions.Enqueue((item, method));
                    }
                });
                continue;
            }
            MethodBase[] array = methodsToJIT;
            foreach (MethodBase method2 in array)
            {
                try
                {
                    ForceJITOnMethod(method2);
                }
                catch (Exception e)
                {
                    exceptions.Enqueue((e, method2));
                }
            }
        }
        if (exceptions.Count > 0)
        {
            throw new JITException("\n" + string.Join("\n", exceptions.Select(((Exception exception, MethodBase method) x) => $"In {x.method.DeclaringType.FullName}.{x.method.Name}, {x.exception.Message}")) + "\n");
        }
    }
References Terraria.ModLoader.Environment, Terraria.ModLoader.Core.AssemblyManager.ForceJITOnMethod(), and Terraria.ModLoader.Core.AssemblyManager.GetLoadableTypes().
Referenced by Terraria.ModLoader.Core.AssemblyManager.JITMod().