TModLoader: Terraria.ModLoader.Core.AssemblyManager.GetAssemblyOwner
GetAssemblyOwner()
static bool Terraria.ModLoader.Core.AssemblyManager.GetAssemblyOwner (Assembly assembly, out string modName) inline static
Definition at line 339 of file AssemblyManager.cs.
    {
        modName = null;
        if (!(AssemblyLoadContext.GetLoadContext(assembly) is ModLoadContext mlc))
        {
            return false;
        }
        modName = mlc.Name;
        if (loadedModContexts[modName] != mlc)
        {
            throw new Exception("Attempt to retrieve owner for mod assembly from a previous load");
        }
        return true;
    }
References Terraria.ModLoader.Core.AssemblyManager.loadedModContexts.
Referenced by Terraria.ModLoader.Core.AssemblyManager.FirstModInStackTrace(), Terraria.ModLoader.Config.ConfigManager.GetDefaultLocalizationKey(), Terraria.ModLoader.Logging.PrettifyStackTraceSources(), and Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForMembers().