TModLoader: Terraria.ModLoader.Core.AssemblyManager.InstantiateMods
InstantiateMods()
static List< Mod > Terraria.ModLoader.Core.AssemblyManager.InstantiateMods (List< LocalMod > modsToLoad, CancellationToken token) inline static package
Definition at line 259 of file AssemblyManager.cs.
    {
        AddAssemblyResolver();
        List<ModLoadContext> modList = modsToLoad.Select((LocalMod m) => new ModLoadContext(m)).ToList();
        foreach (ModLoadContext mod4 in modList)
        {
            loadedModContexts.Add(mod4.Name, mod4);
        }
        foreach (ModLoadContext mod3 in modList)
        {
            foreach (string depName in mod3.properties.RefNames(includeWeak: true))
            {
                if (loadedModContexts.TryGetValue(depName, out var dep))
                {
                    mod3.AddDependency(dep);
                }
            }
        }
        if (Debugger.IsAttached)
        {
            ModCompile.activelyModding = true;
        }
        try
        {
            Interface.loadMods.SetLoadStage("tModLoader.MSSandboxing", modsToLoad.Count);
            int i = 0;
            foreach (ModLoadContext mod2 in modList)
            {
                token.ThrowIfCancellationRequested();
                Interface.loadMods.SetCurrentMod(i++, mod2.Name, mod2.properties?.displayName ?? "", mod2.modFile.Version);
                mod2.LoadAssemblies();
            }
            foreach (ModLoadContext item in modList)
            {
                item.ClearAssemblyBytes();
            }
            Interface.loadMods.SetLoadStage("tModLoader.MSInstantiating");
            MemoryTracking.Checkpoint();
            return modList.Select(delegate(ModLoadContext mod)
            {
                token.ThrowIfCancellationRequested();
                return Instantiate(mod);
            }).ToList();
        }
        catch (AggregateException ae)
        {
            ae.Data["mods"] = ae.InnerExceptions.Select((Exception e) => (string)e.Data["mod"]).ToArray();
            throw;
        }
    }
References Terraria.ModLoader.Core.AssemblyManager.AddAssemblyResolver(), Terraria.ModLoader.Core.MemoryTracking.Checkpoint(), Terraria.ModLoader.Core.AssemblyManager.ModLoadContext.ClearAssemblyBytes(), Terraria.ModLoader.Core.AssemblyManager.Instantiate(), Terraria.ModLoader.Core.AssemblyManager.loadedModContexts, and Terraria.ModLoader.UI.Interface.loadMods.
Referenced by Terraria.ModLoader.ModLoader.Load().