TModLoader: Terraria.ModLoader.Core.AssemblyManager.GetLoadableTypes
GetLoadableTypes() [1/2]
static Type[] Terraria.ModLoader.Core.AssemblyManager.GetLoadableTypes (Assembly assembly) inline static
Definition at line 373 of file AssemblyManager.cs.
    {
        if (!(AssemblyLoadContext.GetLoadContext(assembly) is ModLoadContext mlc))
        {
            return assembly.GetTypes();
        }
        return mlc.loadableTypes[assembly];
    }
Referenced by Terraria.ModLoader.Mod.Autoload(), Terraria.ModLoader.Mod.AutoloadConfig(), Terraria.ModLoader.Core.AssemblyManager.JITAssemblies(), Terraria.ModLoader.Core.AssemblyManager.ModLoadContext.LoadAssemblies(), and Terraria.ModLoader.Core.AssemblyManager.VerifyMod().