TModLoader: Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.TryToHover
TryToHover()
void Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.TryToHover () inline
Implements Terraria.GameContent.UI.ResourceSets.IPlayerResourcesDisplaySet.
Definition at line 252 of file ClassicPlayerResourcesDisplaySet.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        Vector2 mouseScreen = Main.MouseScreen;
        Player localPlayer = Main.LocalPlayer;
        PlayerStatsSnapshot snapshot = new PlayerStatsSnapshot(localPlayer);
        int num = 26 * snapshot.AmountOfLifeHearts;
        float num2 = 0f;
        if (snapshot.AmountOfLifeHearts > 10)
        {
            num = 260;
            num2 += 26f;
        }
        if (mouseScreen.X > (float)(500 + UI_ScreenAnchorX) && mouseScreen.X < (float)(500 + num + UI_ScreenAnchorX) && mouseScreen.Y > 32f && mouseScreen.Y < (float)(32 + TextureAssets.Heart.Height()) + num2 && ResourceOverlayLoader.DisplayHoverText(snapshot, this, drawingLife: true))
        {
            CommonResourceBarMethods.DrawLifeMouseOver();
        }
        num = 24;
        num2 = 28 * snapshot.AmountOfManaStars;
        if (mouseScreen.X > (float)(762 + UI_ScreenAnchorX) && mouseScreen.X < (float)(762 + num + UI_ScreenAnchorX) && mouseScreen.Y > 30f && mouseScreen.Y < 30f + num2 && ResourceOverlayLoader.DisplayHoverText(snapshot, this, drawingLife: false))
        {
            CommonResourceBarMethods.DrawManaMouseOver();
        }
    }
References Terraria.GameContent.UI.ResourceSets.PlayerStatsSnapshot.AmountOfLifeHearts, Terraria.GameContent.UI.ResourceSets.PlayerStatsSnapshot.AmountOfManaStars, Terraria.ModLoader.ResourceOverlayLoader.DisplayHoverText(), Terraria.GameContent.UI.ResourceSets.CommonResourceBarMethods.DrawLifeMouseOver(), Terraria.GameContent.UI.ResourceSets.CommonResourceBarMethods.DrawManaMouseOver(), Terraria.GameContent.TextureAssets.Heart, Terraria.Main.LocalPlayer, Terraria.Main.MouseScreen, and Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.UI_ScreenAnchorX.