TModLoader: Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.DrawMana
DrawMana()
void Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.DrawMana () inline private
    {
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_0258: Unknown result type (might be due to invalid IL or missing references)
        //IL_025d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0269: Unknown result type (might be due to invalid IL or missing references)
        //IL_0273: Unknown result type (might be due to invalid IL or missing references)
        //IL_0278: Unknown result type (might be due to invalid IL or missing references)
        //IL_0281: Unknown result type (might be due to invalid IL or missing references)
        //IL_0286: Unknown result type (might be due to invalid IL or missing references)
        Player localPlayer = Main.LocalPlayer;
        SpriteBatch spriteBatch = Main.spriteBatch;
        Color color = default(Color);
        ((Color)(ref color))._002Ector((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor);
        UIDisplay_ManaPerStar = 20f;
        PlayerStatsSnapshot snapshot = new PlayerStatsSnapshot(localPlayer);
        if (localPlayer.ghost || localPlayer.statManaMax2 <= 0 || snapshot.AmountOfManaStars <= 0)
        {
            return;
        }
        UIDisplay_ManaPerStar = snapshot.ManaPerSegment;
        bool drawText;
        bool num5 = ResourceOverlayLoader.PreDrawResourceDisplay(snapshot, this, drawingLife: false, ref color, out drawText);
        if (drawText)
        {
            _ = localPlayer.statManaMax2 / 20;
            Vector2 vector = FontAssets.MouseText.Value.MeasureString(Lang.inter[2].Value);
            int num = 50;
            if (vector.X >= 45f)
            {
                num = (int)vector.X + 5;
            }
            spriteBatch.DrawString(FontAssets.MouseText.Value, Lang.inter[2].Value, new Vector2((float)(800 - num + UI_ScreenAnchorX), 6f), color, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        }
        if (num5)
        {
            Vector2 position = default(Vector2);
            for (int i = 1; (float)i < (float)localPlayer.statManaMax2 / UIDisplay_ManaPerStar + 1f; i++)
            {
                int num2 = 255;
                bool flag = false;
                float num3 = 1f;
                if ((float)localPlayer.statMana >= (float)i * UIDisplay_ManaPerStar)
                {
                    num2 = 255;
                    if ((float)localPlayer.statMana == (float)i * UIDisplay_ManaPerStar)
                    {
                        flag = true;
                    }
                }
                else
                {
                    float num4 = ((float)localPlayer.statMana - (float)(i - 1) * UIDisplay_ManaPerStar) / UIDisplay_ManaPerStar;
                    num2 = (int)(30f + 225f * num4);
                    if (num2 < 30)
                    {
                        num2 = 30;
                    }
                    num3 = num4 / 4f + 0.75f;
                    if ((double)num3 < 0.75)
                    {
                        num3 = 0.75f;
                    }
                    if (num4 > 0f)
                    {
                        flag = true;
                    }
                }
                if (flag)
                {
                    num3 += Main.cursorScale - 1f;
                }
                ((Vector2)(ref position))._002Ector((float)(775 + UI_ScreenAnchorX), (float)(30 + TextureAssets.Mana.Height() / 2) + (float)TextureAssets.Mana.Height() * (1f - num3) / 2f + (float)(28 * (i - 1)));
                int a = (int)((double)num2 * 0.9);
                ResourceOverlayDrawContext drawContext = new ResourceOverlayDrawContext(snapshot, this, i - 1, TextureAssets.Mana);
                drawContext.position = position;
                drawContext.color = new Color(num2, num2, num2, a);
                drawContext.origin = TextureAssets.Mana.Size() / 2f;
                drawContext.scale = new Vector2(num3);
                ResourceOverlayLoader.DrawResource(drawContext);
            }
        }
        ResourceOverlayLoader.PostDrawResourceDisplay(snapshot, this, drawingLife: false, color, drawText);
    }
References Terraria.GameContent.UI.ResourceSets.PlayerStatsSnapshot.AmountOfManaStars, Terraria.ModLoader.ResourceOverlayLoader.DrawResource(), Terraria.Lang.inter, Terraria.Main.LocalPlayer, Terraria.GameContent.TextureAssets.Mana, Terraria.GameContent.UI.ResourceSets.PlayerStatsSnapshot.ManaPerSegment, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.ModLoader.ResourceOverlayLoader.PostDrawResourceDisplay(), Terraria.ModLoader.ResourceOverlayLoader.PreDrawResourceDisplay(), Terraria.Main.spriteBatch, Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.UI_ScreenAnchorX, Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.UIDisplay_ManaPerStar, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.Draw().