TModLoader: Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.DrawLife
DrawLife()
void Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.DrawLife () inline private
Definition at line 38 of file ClassicPlayerResourcesDisplaySet.cs.
    {
        //IL_0403: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_019b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_039a: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d6: Unknown result type (might be due to invalid IL or missing references)
        Player localPlayer = Main.LocalPlayer;
        SpriteBatch spriteBatch = Main.spriteBatch;
        Color color = default(Color);
        ((Color)(ref color))._002Ector((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor);
        UIDisplay_LifePerHeart = 20f;
        PlayerStatsSnapshot snapshot = new PlayerStatsSnapshot(localPlayer);
        if (localPlayer.ghost || localPlayer.statLifeMax2 <= 0 || snapshot.AmountOfLifeHearts <= 0)
        {
            return;
        }
        UIDisplay_LifePerHeart = snapshot.LifePerSegment;
        int num2 = snapshot.LifeFruitCount;
        bool drawText;
        bool drawHearts = ResourceOverlayLoader.PreDrawResourceDisplay(snapshot, this, drawingLife: true, ref color, out drawText);
        if (drawText)
        {
            int num3 = (int)((float)localPlayer.statLifeMax2 / UIDisplay_LifePerHeart);
            if (num3 >= 10)
            {
                num3 = 10;
            }
            string text = Lang.inter[0].Value + " " + localPlayer.statLifeMax2 + "/" + localPlayer.statLifeMax2;
            Vector2 vector = FontAssets.MouseText.Value.MeasureString(text);
            if (!localPlayer.ghost)
            {
                spriteBatch.DrawString(FontAssets.MouseText.Value, Lang.inter[0].Value, new Vector2((float)(500 + 13 * num3) - vector.X * 0.5f + (float)UI_ScreenAnchorX, 6f), color, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                spriteBatch.DrawString(FontAssets.MouseText.Value, localPlayer.statLife + "/" + localPlayer.statLifeMax2, new Vector2((float)(500 + 13 * num3) + vector.X * 0.5f + (float)UI_ScreenAnchorX, 6f), color, 0f, new Vector2(FontAssets.MouseText.Value.MeasureString(localPlayer.statLife + "/" + localPlayer.statLifeMax2).X, 0f), 1f, (SpriteEffects)0, 0f);
            }
        }
        if (drawHearts)
        {
            Vector2 position = default(Vector2);
            for (int i = 1; i < (int)((float)localPlayer.statLifeMax2 / UIDisplay_LifePerHeart) + 1; i++)
            {
                int num4 = 255;
                float num5 = 1f;
                bool flag = false;
                if ((float)localPlayer.statLife >= (float)i * UIDisplay_LifePerHeart)
                {
                    num4 = 255;
                    if ((float)localPlayer.statLife == (float)i * UIDisplay_LifePerHeart)
                    {
                        flag = true;
                    }
                }
                else
                {
                    float num6 = ((float)localPlayer.statLife - (float)(i - 1) * UIDisplay_LifePerHeart) / UIDisplay_LifePerHeart;
                    num4 = (int)(30f + 225f * num6);
                    if (num4 < 30)
                    {
                        num4 = 30;
                    }
                    num5 = num6 / 4f + 0.75f;
                    if ((double)num5 < 0.75)
                    {
                        num5 = 0.75f;
                    }
                    if (num6 > 0f)
                    {
                        flag = true;
                    }
                }
                if (flag)
                {
                    num5 += Main.cursorScale - 1f;
                }
                int num7 = 0;
                int num8 = 0;
                if (i > 10)
                {
                    num7 -= 260;
                    num8 += 26;
                }
                int a = (int)((double)num4 * 0.9);
                if (!localPlayer.ghost)
                {
                    Asset<Texture2D> heartTexture = ((num2 > 0) ? TextureAssets.Heart2 : TextureAssets.Heart);
                    if (num2 > 0)
                    {
                        num2--;
                    }
                    ((Vector2)(ref position))._002Ector((float)(500 + 26 * (i - 1) + num7 + UI_ScreenAnchorX + heartTexture.Width() / 2), 32f + (float)heartTexture.Height() * (1f - num5) / 2f + (float)num8 + (float)(heartTexture.Height() / 2));
                    ResourceOverlayDrawContext drawContext = new ResourceOverlayDrawContext(snapshot, this, i - 1, heartTexture);
                    drawContext.position = position;
                    drawContext.color = new Color(num4, num4, num4, a);
                    drawContext.origin = heartTexture.Size() / 2f;
                    drawContext.scale = new Vector2(num5);
                    ResourceOverlayLoader.DrawResource(drawContext);
                }
            }
        }
        ResourceOverlayLoader.PostDrawResourceDisplay(snapshot, this, drawingLife: true, color, drawText);
    }
References Terraria.GameContent.UI.ResourceSets.PlayerStatsSnapshot.AmountOfLifeHearts, Terraria.ModLoader.ResourceOverlayLoader.DrawResource(), Terraria.GameContent.TextureAssets.Heart, Terraria.GameContent.TextureAssets.Heart2, Terraria.Lang.inter, Terraria.GameContent.UI.ResourceSets.PlayerStatsSnapshot.LifeFruitCount, Terraria.GameContent.UI.ResourceSets.PlayerStatsSnapshot.LifePerSegment, Terraria.Main.LocalPlayer, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.ModLoader.ResourceOverlayLoader.PostDrawResourceDisplay(), Terraria.ModLoader.ResourceOverlayLoader.PreDrawResourceDisplay(), Terraria.Main.spriteBatch, Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.UI_ScreenAnchorX, Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.UIDisplay_LifePerHeart, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.Draw().