TModLoader: Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItem
UpdateItem()
void Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItem (bool creatingItem = false) inline private inherited
            {
                //IL_0027: Unknown result type (might be due to invalid IL or missing references)
                //IL_002d: Unknown result type (might be due to invalid IL or missing references)
                //IL_0032: Unknown result type (might be due to invalid IL or missing references)
                //IL_0037: Unknown result type (might be due to invalid IL or missing references)
                //IL_02ad: Unknown result type (might be due to invalid IL or missing references)
                //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
                //IL_0045: Unknown result type (might be due to invalid IL or missing references)
                //IL_008a: Unknown result type (might be due to invalid IL or missing references)
                //IL_009c: Unknown result type (might be due to invalid IL or missing references)
                //IL_0069: Unknown result type (might be due to invalid IL or missing references)
                //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
                //IL_02dd: Unknown result type (might be due to invalid IL or missing references)
                //IL_02f7: Unknown result type (might be due to invalid IL or missing references)
                //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
                //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
                //IL_0300: Unknown result type (might be due to invalid IL or missing references)
                //IL_0301: Unknown result type (might be due to invalid IL or missing references)
                //IL_030c: Unknown result type (might be due to invalid IL or missing references)
                //IL_0105: Unknown result type (might be due to invalid IL or missing references)
                //IL_00df: Unknown result type (might be due to invalid IL or missing references)
                //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
                //IL_028b: Unknown result type (might be due to invalid IL or missing references)
                //IL_0290: Unknown result type (might be due to invalid IL or missing references)
                //IL_0292: Unknown result type (might be due to invalid IL or missing references)
                //IL_034c: Unknown result type (might be due to invalid IL or missing references)
                //IL_0163: Unknown result type (might be due to invalid IL or missing references)
                //IL_016c: Unknown result type (might be due to invalid IL or missing references)
                WrappedWriteManifest();
                Utils.LogAndConsoleInfoMessage(Language.GetTextValue("tModLoader.UpdateItem", _entryData.Title));
                PrepareContentForUpdate();
                UGCUpdateHandle_t uGCUpdateHandle_t = SteamUGC.StartItemUpdate(SteamUtils.GetAppID(), _publishedFileID);
                if (_entryData.Title != null)
                {
                    SteamUGC.SetItemTitle(uGCUpdateHandle_t, _entryData.Title);
                }
                if (!string.IsNullOrEmpty(_entryData.Description))
                {
                    SteamUGC.SetItemDescription(uGCUpdateHandle_t, _entryData.Description);
                }
                Logging.tML.Info((object)"Adding tags and visibility");
                SteamUGC.SetItemContent(uGCUpdateHandle_t, _entryData.ContentFolderPath);
                SteamUGC.SetItemTags(uGCUpdateHandle_t, (IList<string>)_entryData.Tags);
                if (_entryData.PreviewImagePath != null)
                {
                    SteamUGC.SetItemPreview(uGCUpdateHandle_t, _entryData.PreviewImagePath);
                }
                if (_entryData.Visibility.HasValue)
                {
                    SteamUGC.SetItemVisibility(uGCUpdateHandle_t, _entryData.Visibility.Value);
                }
                Logging.tML.Info((object)"Setting the language for default description");
                SteamUGC.SetItemUpdateLanguage(uGCUpdateHandle_t, SteamedWraps.GetCurrentSteamLangKey());
                string patchNotes = "";
                _entryData.BuildData["version"] = "0.0.0";
                if (_entryData.BuildData != null)
                {
                    Logging.tML.Info((object)"Adding tModLoader Metadata to Workshop Upload");
                    string[] metadataKeys = MetadataKeys;
                    foreach (string key in metadataKeys)
                    {
                        SteamUGC.RemoveItemKeyValueTags(uGCUpdateHandle_t, key);
                        SteamUGC.AddItemKeyValueTag(uGCUpdateHandle_t, key, _entryData.BuildData[key]);
                    }
                    patchNotes = _entryData.ChangeNotes;
                    if (string.IsNullOrWhiteSpace(patchNotes))
                    {
                        patchNotes = "Version {ModVersion} has been published to {tMLBuildPurpose} tModLoader v{tMLVersion}";
                        if (!string.IsNullOrWhiteSpace(_entryData.BuildData["homepage"]))
{
                            patchNotes += ", learn more at the [url={ModHomepage}]homepage[/url]";
                        }
                    }
                    patchNotes = Language.GetText(patchNotes).FormatWith(new
                    {
                        ModVersion = _entryData.BuildData["trueversion"],
                        ModHomepage = _entryData.BuildData["homepage"],
                        tMLVersion = BuildInfo.tMLVersion.MajorMinor().ToString(),
                        tMLBuildPurpose = BuildInfo.Purpose.ToString()
                    });
                    string refs = _entryData.BuildData["workshopdeps"];
                    if (!string.IsNullOrWhiteSpace(refs))
                    {
                        Logging.tML.Info((object)"Adding dependencies to Workshop Upload");
                        metadataKeys = refs.Split(",", StringSplitOptions.TrimEntries);
                        PublishedFileId_t child = default(PublishedFileId_t);
                        foreach (string dependency in metadataKeys)
{
                            try
{
                                ((PublishedFileId_t)(ref child))._002Ector((ulong)uint.Parse(dependency));
                                SteamUGC.AddDependency(_publishedFileID, child);
                            }
                            catch (Exception)
{
                                ILog tML = Logging.tML;
                                PublishedFileId_t publishedFileID = _publishedFileID;
                                tML.Error((object)("Failed to add Workshop dependency: " + dependency + " to " + ((object)(PublishedFileId_t)(ref publishedFileID)).ToString()));
                            }
                        }
                    }
                }
                _updateCallback = (EResult)0;
                Logging.tML.Info((object)"Submitting workshop update handle to Steam");
                CoreSocialModule.SetSkipPulsing(shouldSkipPausing: true);
                SteamAPICall_t hAPICall = SteamUGC.SubmitItemUpdate(uGCUpdateHandle_t, patchNotes);
                _updateHandle = uGCUpdateHandle_t;
                _updateItemHook.Set(hAPICall, (APIDispatchDelegate<SubmitItemUpdateResult_t>)UpdateItemResult);
                CoreSocialModule.SetSkipPulsing(shouldSkipPausing: false);
                Logging.tML.Info((object)"Handle submitted. Waiting on Steam");
                if (!(!Main.dedServ || creatingItem))
                {
                    do
                    {
                        Thread.Sleep(1);
                        SteamedWraps.RunCallbacks();
                    }
                    while ((int)_updateCallback == 0);
                }
            }
References Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._entryData, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._publishedFileID, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._updateCallback, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._updateHandle, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._updateItemHook, Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.BuildData, Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.ChangeNotes, Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.ContentFolderPath, Terraria.Main.dedServ, Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.Description, Terraria.Localization.LocalizedText.FormatWith(), Terraria.Social.Steam.SteamedWraps.GetCurrentSteamLangKey(), Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), Terraria.Utils.LogAndConsoleInfoMessage(), Terraria.Social.Steam.WorkshopHelper.MetadataKeys, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PrepareContentForUpdate(), Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.PreviewImagePath, Terraria.ModLoader.BuildInfo.Purpose, Terraria.Social.Steam.SteamedWraps.RunCallbacks(), Terraria.Social.Steam.CoreSocialModule.SetSkipPulsing(), Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.Tags, Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.Title, Terraria.ModLoader.Logging.tML, Terraria.ModLoader.BuildInfo.tMLVersion, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItemResult(), Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.Visibility, and Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.WrappedWriteManifest().
Referenced by Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItem(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItemResult(), and Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PublishContent().