TModLoader: Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItemResult
UpdateItemResult()
void Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItemResult (SubmitItemUpdateResult_t param, bool bIOFailure) inline private inherited
            {
                //IL_0001: Unknown result type (might be due to invalid IL or missing references)
                //IL_0002: Unknown result type (might be due to invalid IL or missing references)
                //IL_0007: Unknown result type (might be due to invalid IL or missing references)
                //IL_000c: Unknown result type (might be due to invalid IL or missing references)
                //IL_0032: Unknown result type (might be due to invalid IL or missing references)
                //IL_0038: Invalid comparison between Unknown and I4
                //IL_0040: Unknown result type (might be due to invalid IL or missing references)
                //IL_0045: Unknown result type (might be due to invalid IL or missing references)
                //IL_0046: Unknown result type (might be due to invalid IL or missing references)
                //IL_0049: Invalid comparison between Unknown and I4
                //IL_005d: Unknown result type (might be due to invalid IL or missing references)
                //IL_0060: Invalid comparison between Unknown and I4
                //IL_004b: Unknown result type (might be due to invalid IL or missing references)
                //IL_004d: Invalid comparison between Unknown and I4
                //IL_0062: Unknown result type (might be due to invalid IL or missing references)
                //IL_0065: Invalid comparison between Unknown and I4
                //IL_004f: Unknown result type (might be due to invalid IL or missing references)
                //IL_0051: Invalid comparison between Unknown and I4
                //IL_0110: Unknown result type (might be due to invalid IL or missing references)
                //IL_0115: Unknown result type (might be due to invalid IL or missing references)
                //IL_006a: Unknown result type (might be due to invalid IL or missing references)
                //IL_006d: Invalid comparison between Unknown and I4
                //IL_0053: Unknown result type (might be due to invalid IL or missing references)
                //IL_0056: Invalid comparison between Unknown and I4
                _updateCallback = param.m_eResult;
                if (param.m_bUserNeedsToAcceptWorkshopLegalAgreement)
                {
                    _issueReporter.ReportDelayedUploadProblem("Workshop.ReportIssue_FailedToPublish_UserDidNotAcceptWorkshopTermsOfService");
                    _endAction(this);
                    return;
                }
                if ((int)_updateCallback != 1)
                {
                    SteamedWraps.ReportCheckSteamLogs();
                }
                EResult updateCallback = _updateCallback;
                if ((int)updateCallback <= 9)
                {
                    if ((int)updateCallback != 1)
                    {
                        if ((int)updateCallback != 8)
{
                            if ((int)updateCallback != 9)
{
                                goto IL_0093;
                            }
                            _issueReporter.ReportDelayedUploadProblem("Workshop.ReportIssue_FailedToPublish_CouldNotFindFolderToUpload");
                        }
                        else
{
                            _issueReporter.ReportDelayedUploadProblem("Workshop.ReportIssue_FailedToPublish_InvalidParametersForPublishing");
                        }
                    }
                    else
                    {
                        SteamFriends.ActivateGameOverlayToWebPage("steam://url/CommunityFilePage/" + _publishedFileID.m_PublishedFileId, (EActivateGameOverlayToWebPageMode)0);
                    }
                }
                else if ((int)updateCallback != 15)
                {
                    if ((int)updateCallback != 25)
                    {
                        if ((int)updateCallback != 33)
{
                            goto IL_0093;
                        }
                        _issueReporter.ReportDelayedUploadProblem("Workshop.ReportIssue_FailedToPublish_SteamFileLockFailed");
                    }
                    else
                    {
                        _issueReporter.ReportDelayedUploadProblem("Workshop.ReportIssue_FailedToPublish_LimitExceeded");
                    }
                }
                else
                {
                    _issueReporter.ReportDelayedUploadProblem("Workshop.ReportIssue_FailedToPublish_AccessDeniedBecauseUserDoesntOwnLicenseForApp");
                }
                goto IL_010f;
                IL_0093:
                _issueReporter.ReportDelayedUploadProblemWithoutKnownReason("Workshop.ReportIssue_FailedToPublish_WithoutKnownReason", ((object)(EResult)(ref param.m_eResult)).ToString());
                goto IL_010f;
                IL_010f:
                SteamUGC.SubscribeItem(_publishedFileID);
                _endAction(this);
            }
References Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._endAction, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._issueReporter, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._publishedFileID, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._updateCallback, Terraria.Social.Steam.SteamedWraps.ReportCheckSteamLogs(), Terraria.Social.Base.WorkshopIssueReporter.ReportDelayedUploadProblem(), and Terraria.Social.Base.WorkshopIssueReporter.ReportDelayedUploadProblemWithoutKnownReason().
Referenced by Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PublishContent(), and Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItem().