TModLoader: Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PublishContent
PublishContent()
void Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PublishContent (PublishedItemsFinder finder, WorkshopIssueReporter issueReporter, FinishedPublishingAction endAction, string itemTitle, string itemDescription, string contentFolderPath, string previewImagePath, WorkshopItemPublicSettingId publicity, string[] tags, NameValueCollection buildData = null, ulong existingID = 0uL, string changeNotes = null) inline inherited
            {
                //IL_0061: Unknown result type (might be due to invalid IL or missing references)
                //IL_0066: Unknown result type (might be due to invalid IL or missing references)
                //IL_009f: Unknown result type (might be due to invalid IL or missing references)
                //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
                //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
                //IL_012d: Unknown result type (might be due to invalid IL or missing references)
                //IL_0132: Unknown result type (might be due to invalid IL or missing references)
                Utils.LogAndConsoleInfoMessage(Language.GetTextValueWith("tModLoader.PublishItem", _entryData.Title));
                _issueReporter = issueReporter;
                _endAction = endAction;
                _createItemHook = CallResult<CreateItemResult_t>.Create((APIDispatchDelegate<CreateItemResult_t>)CreateItemResult);
                _updateItemHook = CallResult<SubmitItemUpdateResult_t>.Create((APIDispatchDelegate<SubmitItemUpdateResult_t>)UpdateItemResult);
                _publicity = publicity;
                ERemoteStoragePublishedFileVisibility visibility = GetVisibility(publicity);
                _entryData = new SteamWorkshopItem
                {
                    Title = itemTitle,
                    Description = itemDescription,
                    ContentFolderPath = contentFolderPath,
                    Tags = tags,
                    PreviewImagePath = previewImagePath,
                    Visibility = visibility,
                    BuildData = buildData,
                    ChangeNotes = changeNotes
                };
                if (!File.Exists(previewImagePath))
                {
                    _issueReporter.ReportInstantUploadProblem("Workshop.ReportIssue_FailedToPublish_CouldNotFindFolderToUpload");
                    return;
                }
                if (!Directory.Exists(contentFolderPath))
                {
                    _issueReporter.ReportInstantUploadProblem("Workshop.ReportIssue_FailedToPublish_CouldNotFindFolderToUpload");
                    return;
                }
                _publishedFileID = new PublishedFileId_t(existingID);
                if (existingID == 0L && AWorkshopEntry.TryReadingManifest(contentFolderPath + Path.DirectorySeparatorChar + "workshop.json", out var info))
                {
                    _publishedFileID = new PublishedFileId_t(info.workshopEntryId);
                }
                if (!WrappedWriteManifest())
                {
                    return;
                }
                if (_publishedFileID.m_PublishedFileId != 0L)
                {
                    if (buildData == null)
                    {
                        PreventUpdatingCertainThings();
                    }
                    UpdateItem();
                }
                else
                {
                    CreateItem();
                }
            }
References Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._createItemHook, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._endAction, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._entryData, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._issueReporter, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._publicity, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._publishedFileID, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._updateItemHook, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItem(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItemResult(), Terraria.Localization.Language.GetTextValueWith(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.GetVisibility(), Terraria.Utils.LogAndConsoleInfoMessage(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PreventUpdatingCertainThings(), Terraria.Social.Base.WorkshopIssueReporter.ReportInstantUploadProblem(), Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.Title, Terraria.Social.Base.AWorkshopEntry.TryReadingManifest(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItem(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItemResult(), and Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.WrappedWriteManifest().