TModLoader: Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItem
CreateItem()
void Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItem () inline private inherited
Definition at line 321 of file WorkshopHelper.cs.
            {
                //IL_001c: Unknown result type (might be due to invalid IL or missing references)
                //IL_0027: Unknown result type (might be due to invalid IL or missing references)
                //IL_002d: Unknown result type (might be due to invalid IL or missing references)
                //IL_0032: Unknown result type (might be due to invalid IL or missing references)
                //IL_0039: Unknown result type (might be due to invalid IL or missing references)
                //IL_0065: Unknown result type (might be due to invalid IL or missing references)
                //IL_006d: Unknown result type (might be due to invalid IL or missing references)
                //IL_0073: Invalid comparison between Unknown and I4
                //IL_0089: Unknown result type (might be due to invalid IL or missing references)
                Utils.LogAndConsoleInfoMessage(Language.GetTextValue("tModLoader.CreateItem", _entryData.Title));
                _createCallback = (EResult)0;
                CoreSocialModule.SetSkipPulsing(shouldSkipPausing: true);
                SteamAPICall_t hAPICall = SteamUGC.CreateItem(SteamUtils.GetAppID(), (EWorkshopFileType)0);
                _createItemHook.Set(hAPICall, (APIDispatchDelegate<CreateItemResult_t>)CreateItemResult);
                CoreSocialModule.SetSkipPulsing(shouldSkipPausing: false);
                if (!Main.dedServ)
                {
                    return;
                }
                do
                {
                    Thread.Sleep(1);
                    SteamedWraps.RunCallbacks();
                }
                while ((int)_createCallback == 0);
                if ((int)_createCallback == 1)
                {
                    UpdateItem(creatingItem: true);
                    do
                    {
                        Thread.Sleep(1);
                        SteamedWraps.RunCallbacks();
                    }
                    while ((int)_createCallback == 0);
                }
            }
References Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._createCallback, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._createItemHook, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._entryData, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItemResult(), Terraria.Main.dedServ, Terraria.Localization.Language.GetTextValue(), Terraria.Utils.LogAndConsoleInfoMessage(), Terraria.Social.Steam.SteamedWraps.RunCallbacks(), Terraria.Social.Steam.CoreSocialModule.SetSkipPulsing(), Terraria.Social.Steam.WorkshopHelper.UGCBased.SteamWorkshopItem.Title, and Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItem().
Referenced by Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PublishContent().