TModLoader: Terraria.ModLoader.Config.UI.UIModConfigList.OnActivate
OnActivate()
override void Terraria.ModLoader.Config.UI.UIModConfigList.OnActivate () inline virtual
Reimplemented from Terraria.UI.UIElement.
    {
        modList?.Clear();
        configList?.Clear();
        PopulateMods();
        if (SelectedMod != null)
        {
            PopulateConfigs();
        }
    }
References Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.ModLoader.Config.UI.UIModConfigList.configList, Terraria.ModLoader.Config.UI.UIModConfigList.modList, Terraria.ModLoader.Config.UI.UIModConfigList.PopulateConfigs(), Terraria.ModLoader.Config.UI.UIModConfigList.PopulateMods(), and Terraria.ModLoader.Config.UI.UIModConfigList.SelectedMod.