TModLoader: Terraria.StrayMethods.CheckArenaScore
CheckArenaScore()
static void Terraria.StrayMethods.CheckArenaScore (Vector2 arenaCenter, out Point xLeftEnd, out Point xRightEnd, int walkerWidthInTiles = 5, int walkerHeightInTiles = 10) inline static
Definition at line 93 of file StrayMethods.cs.
    {
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_0003: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        bool flag = false;
        Point point = arenaCenter.ToTileCoordinates();
        xLeftEnd = (xRightEnd = point);
        Collision.ExpandVertically(point.X, point.Y, out var topY, out var bottomY, 0, 4);
        point.Y = bottomY;
        if (flag)
        {
            Dust.QuickDust(point, Color.Blue).scale = 5f;
        }
        SendWalker(point, walkerHeightInTiles, -1, out topY, out var lastIteratedFloorSpot, 120, flag);
        SendWalker(point, walkerHeightInTiles, 1, out topY, out var lastIteratedFloorSpot2, 120, flag);
        lastIteratedFloorSpot.X++;
        lastIteratedFloorSpot2.X--;
        if (flag)
        {
            Dust.QuickDustLine(lastIteratedFloorSpot.ToWorldCoordinates(), lastIteratedFloorSpot2.ToWorldCoordinates(), 50f, Color.Pink);
        }
        xLeftEnd = lastIteratedFloorSpot;
        xRightEnd = lastIteratedFloorSpot2;
    }
References Terraria.Collision.ExpandVertically(), Terraria.Dust.QuickDust(), Terraria.Dust.QuickDustLine(), Terraria.Dust.scale, and Terraria.StrayMethods.SendWalker().
Referenced by Terraria.NPC.VanillaAI_Inner(), and Terraria.GameContent.Events.DD2Event.WouldFailSpawningHere().