TModLoader: Terraria.ModLoader.Config.UI.UIModConfigList.PopulateMods
PopulateMods()
void Terraria.ModLoader.Config.UI.UIModConfigList.PopulateMods () inline private
    {
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        modList?.Clear();
        List<Mod> list = ModLoader.Mods.ToList();
        list.Sort((Mod x, Mod y) => x.DisplayName.CompareTo(y.DisplayName));
        foreach (Mod mod in list)
        {
            if (ConfigManager.Configs.TryGetValue(mod, out List<ModConfig> _))
            {
                UIButton<string> modPanel = new UIButton<string>(mod.DisplayName)
                {
                    MaxWidth =
                    {
                        Percent = 0.95f
                    },
                    HAlign = 0.5f,
                    ScalePanel = true,
                    AltPanelColor = UICommon.MainPanelBackground,
                    AltHoverPanelColor = UICommon.MainPanelBackground * 1.25f,
                    UseAltColors = () => SelectedMod != mod,
                    ClickSound = SoundID.MenuTick
                };
                modPanel.OnLeftClick += delegate
                {
                    SelectedMod = mod;
                    PopulateConfigs();
                };
                modList.Add(modPanel);
            }
        }
    }
References Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.ModLoader.Config.ConfigManager.Configs, Terraria.ModLoader.Mod.DisplayName, Terraria.UI.UIElement.HAlign, Terraria.ModLoader.UI.UICommon.MainPanelBackground, Terraria.UI.UIElement.MaxWidth, Terraria.ID.SoundID.MenuTick, Terraria.ModLoader.Config.UI.UIModConfigList.modList, Terraria.ModLoader.ModLoader.Mods, Terraria.ModLoader.Config.UI.UIModConfigList.PopulateConfigs(), and Terraria.ModLoader.Config.UI.UIModConfigList.SelectedMod.
Referenced by Terraria.ModLoader.Config.UI.UIModConfigList.OnActivate().