TModLoader: Terraria.ModLoader.Config.UI.UIModConfigList.PopulateConfigs
PopulateConfigs()
void Terraria.ModLoader.Config.UI.UIModConfigList.PopulateConfigs () inline private
    {
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        configList?.Clear();
        if (SelectedMod == null || !ConfigManager.Configs.TryGetValue(SelectedMod, out List<ModConfig> configs))
        {
            return;
        }
        foreach (ModConfig config in configs.OrderBy((ModConfig x) => x.DisplayName.Value).ToList())
        {
            float indicatorOffset = 20f;
            UIButton<LocalizedText> configPanel = new UIButton<LocalizedText>(config.DisplayName)
            {
                MaxWidth =
                {
                    Percent = 0.95f
                },
                HAlign = 0.5f,
                ScalePanel = true,
                UseInnerDimensions = true,
                ClickSound = SoundID.MenuOpen
            };
            configPanel.PaddingRight += indicatorOffset;
            configPanel.OnLeftClick += delegate
            {
                Interface.modConfig.SetMod(SelectedMod, config);
                if (Main.gameMenu)
                {
                    Main.menuMode = 10024;
                }
                else
                {
                    Main.InGameUI.SetState(Interface.modConfig);
                }
            };
            configList.Add(configPanel);
            Asset<Texture2D> indicatorTexture = Main.Assets.Request<Texture2D>("Images/UI/Settings_Toggle");
            Rectangle indicatorFrame = indicatorTexture.Frame(2, 1, 1);
            Color serverColor = Colors.RarityRed;
            Color clientColor = Colors.RarityCyan;
            UIImageFramed sideIndicator = new UIImageFramed(indicatorTexture, indicatorFrame)
            {
                VAlign = 0.5f,
                HAlign = 1f,
                Color = ((config.Mode == ConfigScope.ServerSide) ? serverColor : clientColor),
                MarginRight = 0f - indicatorOffset
            };
            sideIndicator.OnUpdate += delegate
            {
                //IL_0030: Unknown result type (might be due to invalid IL or missing references)
                //IL_0023: Unknown result type (might be due to invalid IL or missing references)
                if (sideIndicator.IsMouseHovering)
                {
                    string value = ((config.Mode == ConfigScope.ServerSide) ? serverColor.Hex3() : clientColor.Hex3());
                    string textValue = Language.GetTextValue((config.Mode == ConfigScope.ServerSide) ? "tModLoader.ModConfigServerSide" : "tModLoader.ModConfigClientSide");
                    Main.instance.MouseText($"[c/{value}:{textValue}]", 0, 0);
                }
            };
            configPanel.Append(sideIndicator);
        }
    }
References Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.ModLoader.Config.UI.UIModConfigList.configList, Terraria.ModLoader.Config.ConfigManager.Configs, Terraria.ModLoader.Config.ModConfig.DisplayName, Terraria.Main.gameMenu, Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.HAlign, Terraria.Main.InGameUI, Terraria.Main.instance, Terraria.UI.UIElement.MarginRight, Terraria.UI.UIElement.MaxWidth, Terraria.ModLoader.UI.Interface.modConfig, Terraria.Main.MouseText(), Terraria.ID.Colors.RarityCyan, Terraria.ID.Colors.RarityRed, Terraria.ModLoader.Config.UI.UIModConfigList.SelectedMod, Terraria.UI.UserInterface.SetState(), and Terraria.UI.UIElement.VAlign.
Referenced by Terraria.ModLoader.Config.UI.UIModConfigList.OnActivate(), and Terraria.ModLoader.Config.UI.UIModConfigList.PopulateMods().