TModLoader: Terraria.ModLoader.Config.UI.UIModConfigList.OnInitialize
OnInitialize()
override void Terraria.ModLoader.Config.UI.UIModConfigList.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 30 of file UIModConfigList.cs.
    {
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_047d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0483: Unknown result type (might be due to invalid IL or missing references)
        //IL_0487: Unknown result type (might be due to invalid IL or missing references)
        //IL_048d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0491: Unknown result type (might be due to invalid IL or missing references)
        //IL_0497: Unknown result type (might be due to invalid IL or missing references)
        //IL_049b: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a1: Unknown result type (might be due to invalid IL or missing references)
        uIElement = new UIElement
        {
            Width =
            {
                Percent = 0.8f
            },
            MaxWidth =
            {
                Pixels = 800f,
                Percent = 0f
            },
            Top =
            {
                Pixels = 220f
            },
            Height =
            {
                Pixels = -220f,
                Percent = 1f
            },
            HAlign = 0.5f
        };
        Append(uIElement);
        uIPanel = new UIPanel
        {
            Width =
            {
                Percent = 1f
            },
            Height =
            {
                Pixels = -110f,
                Percent = 1f
            },
            BackgroundColor = UICommon.MainPanelBackground
        };
        uIElement.Append(uIPanel);
        UITextPanel<LocalizedText> uIHeaderTextPanel = new UITextPanel<LocalizedText>(Language.GetText("tModLoader.ModConfiguration"), 0.8f, large: true)
        {
            HAlign = 0.5f,
            Top =
            {
                Pixels = -35f
            },
            BackgroundColor = UICommon.DefaultUIBlue
        }.WithPadding(15f);
        uIElement.Append(uIHeaderTextPanel);
        UIPanel modListPanel = new UIPanel
        {
            Width =
            {
                Pixels = uIPanel.PaddingTop / -2f,
                Percent = 0.5f
            },
            Height =
            {
                Percent = 1f
            }
        };
        uIPanel.Append(modListPanel);
        UIPanel configListPanel = new UIPanel
        {
            Width =
            {
                Pixels = uIPanel.PaddingTop / -2f,
                Percent = 0.5f
            },
            Height =
            {
                Percent = 1f
            },
            HAlign = 1f
        };
        uIPanel.Append(configListPanel);
        float headerHeight = 35f;
        UIText modListHeader = new UIText(Language.GetText("tModLoader.MenuMods"), 0.5f, large: true)
        {
            Top =
            {
                Pixels = 5f
            },
            Left =
            {
                Pixels = 12.5f
            },
            HAlign = 0.5f
        };
        modListPanel.Append(modListHeader);
        UIText configListHeader = new UIText(Language.GetText("tModLoader.ModConfigs"), 0.5f, large: true)
        {
            Top =
            {
                Pixels = 5f
            },
            Left =
            {
                Pixels = -12.5f
            },
            HAlign = 0.5f
        };
        configListPanel.Append(configListHeader);
        modList = new UIList
        {
            Top =
            {
                Pixels = headerHeight
            },
            Width =
            {
                Pixels = -25f,
                Percent = 1f
            },
            Height =
            {
                Pixels = 0f - headerHeight,
                Percent = 1f
            },
            ListPadding = 5f,
            HAlign = 1f
        };
        modListPanel.Append(modList);
        configList = new UIList
        {
            Top =
            {
                Pixels = headerHeight
            },
            Width =
            {
                Pixels = -25f,
                Percent = 1f
            },
            Height =
            {
                Pixels = 0f - headerHeight,
                Percent = 1f
            },
            ListPadding = 5f,
            HAlign = 0f
        };
        configListPanel.Append(configList);
        UIScrollbar modListScrollbar = new UIScrollbar
        {
            Top =
            {
                Pixels = headerHeight
            },
            Height =
            {
                Pixels = 0f - headerHeight,
                Percent = 1f
            }
        };
        modListScrollbar.SetView(100f, 1000f);
        modList.SetScrollbar(modListScrollbar);
        modListPanel.Append(modListScrollbar);
        UIScrollbar configListScrollbar = new UIScrollbar
        {
            Top =
            {
                Pixels = headerHeight
            },
            Height =
            {
                Pixels = 0f - headerHeight,
                Percent = 1f
            },
            HAlign = 1f
        };
        configListScrollbar.SetView(100f, 1000f);
        configList.SetScrollbar(configListScrollbar);
        configListPanel.Append(configListScrollbar);
        backButton = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true)
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.5f
            },
            Height =
            {
                Pixels = 50f
            },
            Top =
            {
                Pixels = -45f
            },
            VAlign = 1f,
            HAlign = 0.5f
        }.WithFadedMouseOver();
        backButton.OnLeftClick += delegate
        {
            SoundEngine.PlaySound(in SoundID.MenuClose);
            SelectedMod = null;
            if (Main.gameMenu)
            {
                Main.menuMode = 10000;
            }
            else
            {
                IngameFancyUI.Close();
            }
        };
        uIElement.Append(backButton);
    }
References Terraria.UI.UIElement.Append(), Terraria.ModLoader.Config.UI.UIModConfigList.backButton, Terraria.UI.IngameFancyUI.Close(), Terraria.ModLoader.Config.UI.UIModConfigList.configList, Terraria.Main.gameMenu, Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.MaxWidth, Terraria.ID.SoundID.MenuClose, Terraria.ModLoader.Config.UI.UIModConfigList.modList, Terraria.Audio.SoundEngine.PlaySound(), Terraria.ModLoader.Config.UI.UIModConfigList.SelectedMod, Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.UI.UIElement.Top, Terraria.ModLoader.Config.UI.UIModConfigList.uIElement, Terraria.ModLoader.Config.UI.UIModConfigList.uIPanel, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.