TModLoader: Terraria.Localization.Language.GetTextValue
GetTextValue() [1/5]
static string Terraria.Localization.Language.GetTextValue (string key) inline static
Retrieves the text value for a specified localization key. The text returned will be for the currently selected language.
Parameters
key
Returns
Definition at line 35 of file Language.cs.
    {
        return LanguageManager.Instance.GetTextValue(key);
    }
References Terraria.Localization.LanguageManager.GetTextValue(), and Terraria.Localization.LanguageManager.Instance.
Referenced by Terraria.ModLoader.Engine.InstallVerifier.InstallVerifier(), Terraria.ModLoader.UI.UIExpandablePanel.UIExpandablePanel(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.UIModDownloadItem(), Terraria.ModLoader.UI.UIModPackItem.UIModPackItem(), Terraria.ModLoader.UI.UIModSourceItem.UIModSourceItem(), Terraria.ModLoader.Default.ModlistCommand.Action(), Terraria.GameContent.UI.States.UICharacterSelect.AddAutomaticPlayerMigrationButtons(), Terraria.GameContent.UI.States.UIWorldSelect.AddAutomaticWorldMigrationButtons(), Terraria.ModLoader.BackgroundTextureLoader.AddBackgroundTexture(), Terraria.ModLoader.Mod.AddContent(), Terraria.GameContent.Creative.CreativePowersHelper.AddDescriptionIfNeeded(), Terraria.WorldGen.AddGenPasses(), Terraria.ModLoader.GoreLoader.AddGoreFromTexture< TGore >(), Terraria.GameContent.Creative.CreativePowersHelper.AddPermissionTextIfNeeded(), Terraria.GameContent.UI.Elements.UICharacterListItem.AddTmlElements(), Terraria.GameContent.UI.Elements.UIWorldListItem.AddTmlElements(), Terraria.GameContent.Creative.CreativePowersHelper.AddUnlockTextIfNeeded(), Terraria.Projectile.AI_061_FishingBobber(), Terraria.GameContent.UI.States.UIWorldCreation.AssignRandomWorldName(), Terraria.ModLoader.Mod.Autoload(), Terraria.ModLoader.ModNPC.AutoStaticDefaults(), Terraria.GameContent.ShopHelper.BiomeNameByKey(), Terraria.ModLoader.Core.ModCompile.Build(), Terraria.GameContent.UI.Elements.UIResourcePack.BuildChildren(), Terraria.ModLoader.UI.UIBuildMod.BuildMod(), Terraria.ModLoader.Core.ModCompile.BuildMod(), Terraria.GameContent.UI.States.UIReportsPage.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.BuildPage(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.button_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.ASharedButtonPower.button_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.button_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.categoryButton_OnUpdate(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.categoryButton_OnUpdate(), Terraria.GameContent.UI.States.UICreativePowersMenu.CategoryButton_OnUpdate_DisplayTooltips(), Terraria.ModLoader.Engine.InstallVerifier.CheckGoG(), Terraria.Social.WeGame.NetClientSocialModule.CheckParameters(), Terraria.RemoteClient.CheckSection(), Terraria.Player.CheckSpawn_Internal(), Terraria.ModLoader.Engine.InstallVerifier.CheckSteam(), Terraria.GameContent.UI.States.UIWorldCreation.Click_SetSeed(), Terraria.Netplay.ClientLoopSetup(), Terraria.RemoteServer.ClientReadCallBack(), Terraria.GameContent.UI.Elements.UICharacterListItem.CloudButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.CloudButtonClick(), Terraria.GameContent.UI.Elements.UICharacterListItem.CloudMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.CloudMouseOver(), Terraria.ModLoader.Core.ModOrganizer.CommandLineModPackOverride(), Terraria.GameContent.Bestiary.SortingSteps.Alphabetical.Compare(), Terraria.ModLoader.Core.ModCompile.CompileMod(), Terraria.Social.Steam.NetClientSocialModule.ConnectToLobby(), Terraria.Lang.CreateDialogSubstitutionObject(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItem(), Terraria.Main.DedServ_PostModLoad(), Terraria.ModLoader.ModPylon.DefaultMapClickHandle(), Terraria.GameContent.UI.Elements.UICharacterListItem.DeleteMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.DeleteMouseOver(), Terraria.ModLoader.Core.ModOrganizer.DetectModChangesForInfoMessage(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.DisplayMouseTextIfHovered(), Terraria.ModLoader.AutoActuateBuilderToggle.DisplayValue(), Terraria.ModLoader.AutoPaintBuilderToggle.DisplayValue(), Terraria.ModLoader.BlockSwapBuilderToggle.DisplayValue(), Terraria.ModLoader.HideAllWiresBuilderToggle.DisplayValue(), Terraria.ModLoader.RulerGridBuilderToggle.DisplayValue(), Terraria.ModLoader.RulerLineBuilderToggle.DisplayValue(), Terraria.ModLoader.TorchBiomeBuilderToggle.DisplayValue(), Terraria.ModLoader.WireVisibilityBuilderToggle.DisplayValue(), Terraria.NPC.DoDeathEvents_CelebrateBossDeath(), Terraria.Social.Steam.SteamedWraps.Download(), Terraria.Social.Steam.WorkshopBrowserModule.DownloadItem(), Terraria.ModLoader.UI.UIModPackItem.DownloadMissingMods(), Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress.DownloadMods(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadModsAndReturnToBrowser(), Terraria.GameContent.UI.LegacyMultiplayerClosePlayersOverlay.Draw(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.Draw(), Terraria.IngameOptions.Draw(), Terraria.Map.SpawnMapLayer.Draw(), Terraria.GameContent.UI.States.UIAchievementsMenu.Draw(), Terraria.GameContent.UI.States.UICharacterCreation.Draw(), Terraria.GameContent.UI.IssueReportsIndicator.Draw(), Terraria.ModLoader.UI.UIModInfo.Draw(), Terraria.ModLoader.UI.UIMods.Draw(), Terraria.Main.DrawBestiaryIcon(), Terraria.UI.ChestUI.DrawButton(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.DrawChildren(), Terraria.ModLoader.UI.UIModSourceItem.DrawChildren(), Terraria.Main.DrawClothesWindow(), Terraria.Main.DrawEmoteBubblesButton(), Terraria.ModLoader.UI.UIModPackItem.DrawEnabledText(), Terraria.Main.DrawHairWindow(), Terraria.Main.DrawInfoAccs(), Terraria.Main.DrawInterface_35_YouDied(), Terraria.Main.DrawInterface_InstrumentMouseText(), Terraria.Main.DrawInvasionProgress(), Terraria.Main.DrawInventory(), Terraria.Main.DrawLoadoutButtons(), Terraria.Main.DrawMap(), Terraria.Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition(), Terraria.Main.DrawMapIcons_PotionOfReturnHomePosition(), Terraria.Main.DrawMenu(), Terraria.Main.DrawMouseOver(), Terraria.Main.DrawNPCChatButtons(), Terraria.GameContent.UI.Elements.EmoteButton.DrawSelf(), Terraria.GameContent.UI.Elements.UICharacterListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorldListItem.DrawSelf(), Terraria.GameContent.UI.States.UIWorldLoad.DrawSelf(), Terraria.ModLoader.Config.UI.ConfigElement< T >.DrawSelf(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.DrawSelf(), Terraria.ModLoader.UI.UIModItem.DrawSelf(), Terraria.ModLoader.UI.UIModPackItem.DrawSelf(), Terraria.ModLoader.UI.UIModSourceItem.DrawSelf(), Terraria.GameContent.Creative.CreativeUI.DrawToggleButton(), Terraria.DataStructures.TitleLinkButton.DrawTooltip(), Terraria.Main.DrawVersionNumber(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.DrawWaterChoices(), Terraria.ModLoader.UI.UIModItem.EnableDependencies(), Terraria.ModLoader.UI.UIModPackItem.EnableList(), Terraria.ModLoader.Core.ModOrganizer.EnsureDependenciesExist(), Terraria.NetMessage.EnsureLocalPlayerIsPresent(), Terraria.ModLoader.Core.ModOrganizer.EnsureTargetVersionsMet(), Terraria.GameContent.UI.Elements.UICharacterListItem.ErrorButtonClick(), Terraria.Main.ExecuteCommand(), Terraria.ModLoader.UI.UIExtractMod.Extract(), Terraria.ModLoader.UI.UIModInfo.ExtractLocalization(), Terraria.ModLoader.Engine.ErrorReporting.FatalExit(), Terraria.GameContent.UI.Elements.UICharacterListItem.FavoriteButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.FavoriteButtonClick(), Terraria.GameContent.UI.Elements.UICharacterListItem.FavoriteMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.FavoriteMouseOver(), Terraria.ModLoader.Core.ModCompile.FindReferencedMods(), Terraria.ModLoader.ModPacket.Finish(), Terraria.Graphics.Capture.CaptureCamera.FinishCapture(), Terraria.ModLoader.Logging.FirstChanceExceptionHandler(), Terraria.Projectile.FishingCheck(), Terraria.ModLoader.Config.ConfigManager.FormatTextAttribute(), Terraria.WorldBuilding.WorldGenerator.GenerateWorld(), Terraria.Main.GetBuffTooltip(), Terraria.ModLoader.ModNPC.GetChat(), Terraria.NPC.GetChat(), Terraria.ModLoader.NPCLoader.GetChat(), Terraria.GameContent.ItemDropRules.Conditions.FrostMoonDropGatingChance.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.PumpkinMoonDropGatingChance.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.FromCertainWaveAndAbove.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.PirateMap.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.IsChristmas.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.NotExpert.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.NotMasterMode.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.EmpressOfLightIsGenuinelyEnraged.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.PlayerNeedsHealing.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.LegacyHack_IsBossAndExpert.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.LegacyHack_IsBossAndNotExpert.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.IsExpert.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.IsMasterMode.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.IsCrimson.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.IsCorruption.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.IsCrimsonAndNotExpert.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.IsCorruptionAndNotExpert.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.HalloweenWeapons.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.SoulOfNight.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.SoulOfLight.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.NotFromStatue.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.HalloweenGoodieBagDrop.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.XmasPresentDrop.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.LivingFlames.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.NamedNPC.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.HallowKeyCondition.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.JungleKeyCondition.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.CorruptKeyCondition.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.CrimsonKeyCondition.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.FrozenKeyCondition.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.DesertKeyCondition.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.BeatAnyMechBoss.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.YoyoCascade.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.YoyosAmarok.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.YoyosYelets.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.YoyosKraken.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.YoyosHelFire.GetConditionDescription(), Terraria.GameContent.ItemDropRules.Conditions.WindyEnoughForKiteDrops.GetConditionDescription(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.UI.Elements.AWorldListItem.GetDifficulty(), Terraria.DataStructures.EntrySorter< TEntryType, TStepType >.GetDisplayName(), Terraria.Lang.GetDryadWorldStatusDialog(), Terraria.ModLoader.UI.Elements.UIAsyncList< TResource, TUIElement >.GetEndItemText(), Terraria.ModLoader.ModContent.GetFileBytes(), Terraria.GameContent.UI.Elements.UIKeybindingListItem.GetFriendlyName(), Terraria.UI.ItemSlot.GetGamepadInstructions(), Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.GetHoverText(), Terraria.ModLoader.ILocalizedModTypeExtensions.GetLocalizedValue(), Terraria.Lang.GetNPCHouseBannerText(), Terraria.Main.GUIChatDrawInner(), Terraria.ModLoader.Config.ConfigManager.HandleInGameChangeConfigPacket(), Terraria.Main.HelpText(), Terraria.ModLoader.UI.ModBrowser.TimeHelper.HumanTimeSpanString(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.ImportButtonClick_ImportWorldToLocalFiles(), Terraria.Main.InfoDisplayPageHandler(), Terraria.Audio.SoundEngine.Initialize(), Terraria.Social.Steam.CoreSocialModule.Initialize(), Terraria.Social.Steam.NetServerSocialModule.Initialize(), Terraria.Social.WeGame.NetServerSocialModule.Initialize(), Terraria.Netplay.InitializeServer(), Terraria.Main.InitTMLContentManager(), Terraria.Netplay.InnerClientLoop(), Terraria.Social.Steam.SteamedWraps.InnerDownloadHandler(), Terraria.ModLoader.BossBarLoader.InsertMenu(), Terraria.Player.ItemCheck_UseCombatBook(), Terraria.Player.ItemCheck_UsePeddlersSatchel(), Terraria.Netplay.KickClient(), Terraria.Social.Steam.NetClientSocialModule.LaunchLocalServer(), Terraria.Social.WeGame.NetClientSocialModule.LaunchLocalServer(), Terraria.ModLoader.ModLoader.Load(), Terraria.IO.WorldFile.LoadFileFormatHeader(), Terraria.GameContent.UI.States.UICharacterSelect.LoadMigratablePlayers(), Terraria.GameContent.UI.States.UIWorldSelect.LoadMigratableWorlds(), Terraria.Lang.LocalizedDuration(), Terraria.ModLoader.Config.UI.UIModConfig.MakeSeparateListPanel(), Terraria.ModLoader.Default.UnloadedChest.MapChestName(), Terraria.ModLoader.Engine.ErrorReporting.MessageBoxShow(), Terraria.ModLoader.Default.Patreon.PatreonItem.ModifyTooltips(), Terraria.ModLoader.Default.UnloadedItem.ModifyTooltips(), Terraria.ModLoader.SystemLoader.ModifyWorldGenTasks(), Terraria.ModLoader.UI.Interface.ModLoaderMenus(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.MouseOver_Expert(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.MouseOver_Journey(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.MouseOver_Master(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.MouseOver_Normal(), Terraria.Main.MouseText_DrawBuffTooltip(), Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo(), Terraria.WorldGen.MoveTownNPC(), Terraria.NPC.NewNPC(), Terraria.Initializers.AchievementInitializer.OnAchievementCompleted(), Terraria.ModLoader.UI.UIErrorMessage.OnActivate(), Terraria.ModLoader.UI.UIModInfo.OnActivate(), Terraria.ModLoader.UI.UIModPacks.OnActivate(), Terraria.Social.WeGame.NetClientSocialModule.OnAuthSuccess(), Terraria.ModLoader.Config.UI.CollectionElement.OnBind(), Terraria.ModLoader.Config.UI.DefinitionElement< T >.OnBind(), Terraria.ModLoader.Config.UI.ObjectElement.OnBind(), Terraria.Netplay.OnConnectionAccepted(), Terraria.ModLoader.Config.UI.UIModConfig.OnInitialize(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.OnInitialize(), Terraria.ModLoader.UI.UICreateMod.OnInitialize(), Terraria.ModLoader.UI.UIErrorMessage.OnInitialize(), Terraria.ModLoader.UI.UIForcedDelayInfoMessage.OnInitialize(), Terraria.ModLoader.UI.UIInfoMessage.OnInitialize(), Terraria.ModLoader.UI.UIModInfo.OnInitialize(), Terraria.ModLoader.UI.UIModItem.OnInitialize(), Terraria.ModLoader.UI.UIMods.OnInitialize(), Terraria.ModLoader.UI.UIModSources.OnInitialize(), Terraria.Social.Steam.NetServerSocialModule.OnLobbyCreated(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyEntered(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyJoinRequest(), Terraria.Social.WeGame.NetClientSocialModule.OnRailRespondInvation(), Terraria.Main.OnSubmitServerPort(), Terraria.UI.IngameFancyUI.OpenVirtualKeyboard(), Terraria.ModLoader.Core.ModCompile.PackageMod(), Terraria.GameContent.UI.Elements.UICharacterListItem.PlayMouseOver(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.PlayMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.PlayMouseOver(), Terraria.WorldGen.playWorldCallBack(), Terraria.ModLoader.Config.UI.UIModConfigList.PopulateConfigs(), Terraria.GameContent.UI.States.UIReportsPage.PopulateLogs(), Terraria.ModLoader.Exceptions.MissingResourceException.ProcessMessage(), Terraria.Social.Steam.WorkshopHelper.PublishMod(), Terraria.ModLoader.UI.UIModSourceItem.PublishMod(), Terraria.ModLoader.UI.UIModSourceItem.PublishServerSideMod(), Terraria.ModLoader.UI.UIModItem.QuickModDelete(), Terraria.ModLoader.Core.TmodFile.Read(), Terraria.ModLoader.Core.ModCompile.ReadBuildInfo(), Terraria.ModLoader.UI.UIMemoryBar.RecalculateMemory(), Terraria.NetMessage.ReceiveBytes(), Terraria.ModLoader.ModNet.ReceiveMod(), Terraria.ModLoader.NPCLoader.RegisterTownNPCMoodLocalizations(), Terraria.ModLoader.ModTypeLookup< T >.RegisterWithName(), Terraria.GameContent.UI.Elements.UICharacterListItem.RenameMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.RenameMouseOver(), Terraria.Social.Steam.SteamedWraps.ReportCheckSteamLogs(), Terraria.Social.Base.WorkshopIssueReporter.ReportDelayedUploadProblem(), Terraria.Social.Base.WorkshopIssueReporter.ReportInstantUploadProblem(), Terraria.ModLoader.ModContent.Request< T >(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.research_OnUpdate(), Terraria.IO.Preferences.Save(), Terraria.ModLoader.Config.UI.UIModConfig.SaveConfig(), Terraria.GameContent.UI.Elements.UIWorldListItem.SeedButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.SeedMouseOver(), Terraria.NetMessage.SendData(), Terraria.Net.NetManager.SendData(), Terraria.WorldGen.serverLoadWorldCallBack(), Terraria.ModLoader.UI.Interface.ServerModMenu(), Terraria.ModLoader.UI.UILoadMods.SetCurrentMod(), Terraria.Main.SetDisplayMode(), Terraria.ModLoader.UI.UILoadMods.SetLoadStage(), Terraria.ModLoader.Config.UI.DictionaryElement.SetupList(), Terraria.ModLoader.Config.UI.ListElement.SetupList(), Terraria.ModLoader.Config.UI.SetElement.SetupList(), Terraria.Recipe.SetupRecipeGroups(), Terraria.Chest.SetupShop(), Terraria.ModLoader.UI.UIModInfo.Show(), Terraria.GameContent.Bestiary.FilterProviderInfoElement.ShowButtonName(), Terraria.GameContent.Bestiary.ModBestiaryInfoElement.ShowButtonName(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.ShowButtonName(), Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.ShowButtonName(), Terraria.GameContent.Bestiary.NPCKillCounterInfoElement.ShowDescription(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ShowGameNeedsRestart(), Terraria.ModLoader.UI.UIModSources.ShowInfoMessages(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ShowModDependencies(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ShowStats_Attack(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ShowStats_Defense(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ShowStats_Knockback(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ShowStats_Life(), Terraria.ModLoader.UI.UIModSources.ShowWelcomeMessage(), Terraria.NPC.SpawnBoss(), Terraria.NPC.SpawnOnPlayer(), Terraria.NPC.SpawnSkeletron(), Terraria.WorldGen.SpawnTownNPC(), Terraria.WorldGen.SpawnTravelNPC(), Terraria.NPC.SpawnWOF(), Terraria.ModLoader.ModContent.SplitName(), Terraria.Liquid.StartPanic(), Terraria.Lang.SupportGlyphs(), Terraria.ModLoader.ModNet.SyncClientMods(), Terraria.Player.TileInteractionsUse(), Terraria.Localization.NetworkText.ToDebugInfoString(), Terraria.ModLoader.UI.EnabledFilterModesExtensions.ToFriendlyString(), Terraria.ModLoader.UI.ModBrowser.ModBrowserSortModesExtensions.ToFriendlyString(), Terraria.ModLoader.UI.ModBrowser.ModSideFilterModesExtensions.ToFriendlyString(), Terraria.ModLoader.UI.ModsMenuSortModesExtensions.ToFriendlyString(), Terraria.ModLoader.UI.ModBrowser.SearchFilterModesExtensions.ToFriendlyString(), Terraria.ModLoader.UI.ModBrowser.UpdateFilterModesExtensions.ToFriendlyString(), Terraria.Localization.NetworkText.ToString(), Terraria.UI.ItemSlot.TryEnteringFastUseMode(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.TryMovingToRejectionMenuIfNeeded(), Terraria.GameContent.UI.Elements.UIWorldListItem.TryMovingToRejectionMenuIfNeeded(), Terraria.ModLoader.ModLoader.Unload(), Terraria.ModLoader.LocalizationLoader.Update(), Terraria.ModLoader.Config.UI.CollectionElement.Update(), Terraria.ModLoader.Config.UI.ObjectElement.Update(), Terraria.ModLoader.UI.DownloadManager.UIWorkshopDownload.Update(), Terraria.ModLoader.UI.UIExpandablePanel.Update(), Terraria.ModLoader.UI.UIForcedDelayInfoMessage.Update(), Terraria.ModLoader.UI.UIModInfo.Update(), Terraria.ModLoader.UI.UIMods.Update(), Terraria.ModLoader.MenuLoader.UpdateAndDrawModMenu(), Terraria.Player.UpdateArmorSets(), Terraria.GameContent.DontStarveDarknessDamageDealer.UpdateDarknessState(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItem(), Terraria.Liquid.UpdateLiquid(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.UpdateSliderAndShowMultiplierMouseOver(), Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.UpdateSliderAndShowMultiplierMouseOver(), Terraria.RemoteClient.UpdateStatusText(), Terraria.Main.ValueToCoins(), Terraria.PopupText.ValueToName(), Terraria.PopupText.ValueToName(), Terraria.ModLoader.Core.AssemblyManager.VerifyMod(), Terraria.ModLoader.Core.ModOrganizer.VerifyNames(), Terraria.ModLoader.UI.UIModPackItem.ViewListInfo(), and Terraria.WorldGen.worldGenCallback().