TModLoader: Terraria.Localization.Language.GetOrRegister
GetOrRegister() [2/2]
static LocalizedText Terraria.Localization.Language.GetOrRegister (string key, Func< string > makeDefaultValue = null) inline static
Returns a T:Terraria.Localization.LocalizedText for a given key.
If no existing localization exists for the key, it will be defined so it can be exported to a matching mod localization file.
Parameters
key The localization key
makeDefaultValue A factory method for creating the default value, used to update localization files with missing entries
Returns
    {
        return LanguageManager.Instance.GetOrRegister(key, makeDefaultValue);
    }
References Terraria.Localization.LanguageManager.Instance.
Referenced by Terraria.ModLoader.ModKeybind.ModKeybind(), Terraria.Condition(), Terraria.ModLoader.Mod.GetLocalization(), Terraria.ModLoader.ILocalizedModTypeExtensions.GetLocalization(), Terraria.Localization.Language.GetOrRegister(), Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForEnumMembers(), Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForMembers(), Terraria.ModLoader.Config.ConfigManager.RegisterLocalizationKeysForMemberType(), Terraria.ModLoader.NPCLoader.RegisterTownNPCMoodLocalizations(), and Terraria.ModLoader.ModBiome.SetupContent().