TModLoader: Terraria.GameContent.CoinLossRevengeSystem.CheckRespawns
CheckRespawns()
void Terraria.GameContent.CoinLossRevengeSystem.CheckRespawns () inline
    {
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        lock (_markersLock)
        {
            if (_markers.Count == 0)
            {
                return;
            }
        }
        List<Tuple<int, Rectangle, Rectangle>> list = new List<Tuple<int, Rectangle, Rectangle>>();
        for (int i = 0; i < 255; i++)
        {
            Player player = Main.player[i];
            if (player.active && !player.dead)
            {
                list.Add(Tuple.Create<int, Rectangle, Rectangle>(i, Utils.CenteredRectangle(player.Center, _playerBoxSizeInner), Utils.CenteredRectangle(player.Center, _playerBoxSizeOuter)));
            }
        }
        if (list.Count == 0)
        {
            return;
        }
        RemoveExpiredOrInvalidMarkers();
        lock (_markersLock)
        {
            List<RevengeMarker> list2 = new List<RevengeMarker>();
            for (int j = 0; j < _markers.Count; j++)
            {
                RevengeMarker revengeMarker = _markers[j];
                bool flag = false;
                Tuple<int, Rectangle, Rectangle> tuple = null;
                foreach (Tuple<int, Rectangle, Rectangle> item in list)
                {
                    if (revengeMarker.Intersects(item.Item2, item.Item3))
                    {
                        tuple = item;
                        flag = true;
                        break;
                    }
                }
                if (!flag)
                {
                    revengeMarker.SetRespawnAttemptLock(state: false);
                }
                else
                {
                    if (revengeMarker.RespawnAttemptLocked)
                    {
                        continue;
                    }
                    revengeMarker.SetRespawnAttemptLock(state: true);
                    if (revengeMarker.WouldNPCBeDiscouraged(Main.player[tuple.Item1]))
                    {
                        revengeMarker.SetToExpire();
                        continue;
                    }
                    revengeMarker.SpawnEnemy();
                    list2.Add(revengeMarker);
                    if (Main.dedServ)
                    {
                        NetMessage.SendData(127, -1, -1, null, revengeMarker.UniqueID);
                    }
                }
            }
            _markers = _markers.Except(list2).ToList();
        }
    }
References Terraria.GameContent.CoinLossRevengeSystem._markers, Terraria.GameContent.CoinLossRevengeSystem._markersLock, Terraria.GameContent.CoinLossRevengeSystem._playerBoxSizeInner, Terraria.GameContent.CoinLossRevengeSystem._playerBoxSizeOuter, Terraria.Entity.active, Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.Player.dead, Terraria.Main.dedServ, Terraria.Main.player, Terraria.GameContent.CoinLossRevengeSystem.RemoveExpiredOrInvalidMarkers(), and Terraria.NetMessage.SendData().
Referenced by Terraria.NPC.SpawnNPC().