TModLoader: Terraria.ModLoader.IO.PlayerIO.SaveData
SaveData()
static TagCompound Terraria.ModLoader.IO.PlayerIO.SaveData (Player player) inline static package
Definition at line 38 of file PlayerIO.cs.
    {
        Item[] _temporaryItemSlots = new Item[4]
        {
            Main.mouseItem,
            Main.CreativeMenu.GetItemByIndex(0),
            Main.guideItem,
            Main.reforgeItem
        };
        return new TagCompound
        {
            ["armor"] = SaveInventory(player.armor),
            ["dye"] = SaveInventory(player.dye),
            ["loadouts"] = SaveLoadouts(player.Loadouts),
            ["inventory"] = SaveInventory(player.inventory),
            ["miscEquips"] = SaveInventory(player.miscEquips),
            ["miscDyes"] = SaveInventory(player.miscDyes),
            ["bank"] = SaveInventory(player.bank.item),
            ["bank2"] = SaveInventory(player.bank2.item),
            ["bank3"] = SaveInventory(player.bank3.item),
            ["bank4"] = SaveInventory(player.bank4.item),
            ["temporaryItemSlots"] = SaveInventory(_temporaryItemSlots),
            ["hairDye"] = SaveHairDye(player.hairDye),
            ["research"] = SaveResearch(player),
            ["modData"] = SaveModData(player),
            ["modBuffs"] = SaveModBuffs(player),
            ["infoDisplays"] = SaveInfoDisplays(player),
            ["builderToggles"] = SaveBuilderToggles(player),
            ["usedMods"] = SaveUsedMods(player),
            ["usedModPack"] = SaveUsedModPack(player),
            ["hair"] = SaveHair(player.hair)
        };
    }
References Terraria.Player.armor, Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Main.CreativeMenu, Terraria.Player.dye, Terraria.GameContent.Creative.CreativeUI.GetItemByIndex(), Terraria.Main.guideItem, Terraria.Player.hair, Terraria.Player.hairDye, Terraria.Player.inventory, Terraria.Chest.item, Terraria.Player.Loadouts, Terraria.Player.miscDyes, Terraria.Player.miscEquips, Terraria.Main.mouseItem, Terraria.ModLoader.IO.PlayerIO.SaveBuilderToggles(), Terraria.ModLoader.IO.PlayerIO.SaveHair(), Terraria.ModLoader.IO.PlayerIO.SaveHairDye(), Terraria.ModLoader.IO.PlayerIO.SaveInfoDisplays(), Terraria.ModLoader.IO.PlayerIO.SaveInventory(), Terraria.ModLoader.IO.PlayerIO.SaveLoadouts(), Terraria.ModLoader.IO.PlayerIO.SaveModBuffs(), Terraria.ModLoader.IO.PlayerIO.SaveModData(), Terraria.ModLoader.IO.PlayerIO.SaveResearch(), Terraria.ModLoader.IO.PlayerIO.SaveUsedModPack(), and Terraria.ModLoader.IO.PlayerIO.SaveUsedMods().
Referenced by Terraria.Player.InternalSavePlayerFile(), and Terraria.Player.SerializedClone().