TModLoader: Terraria.ModLoader.IO.PlayerIO.Save
Save()
static void Terraria.ModLoader.IO.PlayerIO.Save (TagCompound tag, string path, bool isCloudSave) inline static package
    {
        path = Path.ChangeExtension(path, ".tplr");
        if (FileUtilities.Exists(path, isCloudSave))
        {
            FileUtilities.Copy(path, path + ".bak", isCloudSave);
        }
        FileUtilities.WriteTagCompound(path, isCloudSave, tag);
    }
References Terraria.Utilities.FileUtilities.Copy(), Terraria.Utilities.FileUtilities.Exists(), and Terraria.Utilities.FileUtilities.WriteTagCompound().
Referenced by Terraria.Player.InternalSavePlayerFile().