TModLoader: Terraria.ModLoader.IO.PlayerIO.TryLoadData
TryLoadData()
static bool Terraria.ModLoader.IO.PlayerIO.TryLoadData (string path, bool isCloudSave, out TagCompound tag) inline static package
    {
        path = Path.ChangeExtension(path, ".tplr");
        tag = new TagCompound();
        if (!FileUtilities.Exists(path, isCloudSave))
        {
            return false;
        }
        byte[] buf = FileUtilities.ReadAllBytes(path, isCloudSave);
        if (buf[0] != 31 || buf[1] != 139)
        {
            throw new IOException(Path.GetFileName(path) + ":: File Corrupted during Last Save Step. Aborting... ERROR: Missing NBT Header");
        }
        tag = TagIO.FromStream(buf.ToMemoryStream());
        return true;
    }
References Terraria.Utilities.FileUtilities.Exists(), Terraria.ModLoader.IO.TagIO.FromStream(), and Terraria.Utilities.FileUtilities.ReadAllBytes().
Referenced by Terraria.Player.Deserialize().