TModLoader: Terraria.ModLoader.ResourceOverlayLoader.overlays
overlays
readonly IList<ModResourceOverlay> Terraria.ModLoader.ResourceOverlayLoader.overlays = new List<ModResourceOverlay>() static package
Referenced by Terraria.ModLoader.ResourceOverlayLoader.Add(), Terraria.ModLoader.ResourceOverlayLoader.DisplayHoverText(), Terraria.ModLoader.ResourceOverlayLoader.GetOverlay(), Terraria.ModLoader.ResourceOverlayLoader.PostDrawResource(), Terraria.ModLoader.ResourceOverlayLoader.PostDrawResourceDisplay(), Terraria.ModLoader.ResourceOverlayLoader.PreDrawResource(), Terraria.ModLoader.ResourceOverlayLoader.PreDrawResourceDisplay(), and Terraria.ModLoader.ResourceOverlayLoader.Unload().