TModLoader: Terraria.ModLoader.ResourceOverlayLoader.DisplayHoverText
DisplayHoverText()
static bool Terraria.ModLoader.ResourceOverlayLoader.DisplayHoverText (PlayerStatsSnapshot snapshot, IPlayerResourcesDisplaySet displaySet, bool drawingLife) inline static
Definition at line 85 of file ResourceOverlayLoader.cs.
    {
        bool result = true;
        foreach (ModResourceOverlay overlay in overlays)
        {
            result &= overlay.DisplayHoverText(snapshot, displaySet, drawingLife);
        }
        return result;
    }
References Terraria.ModLoader.ResourceOverlayLoader.overlays.
Referenced by Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.DrawLifeBar(), Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.DrawManaBar(), and Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.TryToHover().