TModLoader: Terraria.GameContent.UI.States.UIEmotesMenu.InitializePage
InitializePage()
void Terraria.GameContent.UI.States.UIEmotesMenu.InitializePage () inline
    {
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        RemoveAllChildren();
        UIElement uIElement = new UIElement();
        uIElement.Width.Set(590f, 0f);
        uIElement.Top.Set(220f, 0f);
        uIElement.Height.Set(-220f, 1f);
        uIElement.HAlign = 0.5f;
        _outerContainer = uIElement;
        Append(uIElement);
        UIPanel uIPanel = new UIPanel();
        uIPanel.Width.Set(0f, 1f);
        uIPanel.Height.Set(-110f, 1f);
        uIPanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
        uIPanel.PaddingTop = 0f;
        uIElement.Append(uIPanel);
        _container = uIPanel;
        UIList uIList = new UIList();
        uIList.Width.Set(-25f, 1f);
        uIList.Height.Set(-50f, 1f);
        uIList.Top.Set(50f, 0f);
        uIList.HAlign = 0.5f;
        uIList.ListPadding = 14f;
        uIPanel.Append(uIList);
        _list = uIList;
        UIScrollbar uIScrollbar = new UIScrollbar();
        uIScrollbar.SetView(100f, 1000f);
        uIScrollbar.Height.Set(-20f, 1f);
        uIScrollbar.HAlign = 1f;
        uIScrollbar.VAlign = 1f;
        uIScrollbar.Top = StyleDimension.FromPixels(-5f);
        uIList.SetScrollbar(uIScrollbar);
        _scrollBar = uIScrollbar;
        UITextPanel<LocalizedText> uITextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, large: true);
        uITextPanel.Width.Set(-10f, 0.5f);
        uITextPanel.Height.Set(50f, 0f);
        uITextPanel.VAlign = 1f;
        uITextPanel.HAlign = 0.5f;
        uITextPanel.Top.Set(-45f, 0f);
        uITextPanel.OnMouseOver += FadedMouseOver;
        uITextPanel.OnMouseOut += FadedMouseOut;
        uITextPanel.OnLeftClick += GoBackClick;
        uITextPanel.SetSnapPoint("Back", 0);
        uIElement.Append(uITextPanel);
        _backPanel = uITextPanel;
        int currentGroupIndex = 0;
        TryAddingList(Language.GetText("UI.EmoteCategoryGeneral"), ref currentGroupIndex, 10, GetEmotesGeneral());
        TryAddingList(Language.GetText("UI.EmoteCategoryRPS"), ref currentGroupIndex, 10, GetEmotesRPS());
        TryAddingList(Language.GetText("UI.EmoteCategoryItems"), ref currentGroupIndex, 11, GetEmotesItems());
        TryAddingList(Language.GetText("UI.EmoteCategoryBiomesAndEvents"), ref currentGroupIndex, 8, GetEmotesBiomesAndEvents());
        TryAddingList(Language.GetText("UI.EmoteCategoryTownNPCs"), ref currentGroupIndex, 9, GetEmotesTownNPCs());
        TryAddingList(Language.GetText("UI.EmoteCategoryCritters"), ref currentGroupIndex, 7, GetEmotesCritters());
        TryAddingList(Language.GetText("UI.EmoteCategoryBosses"), ref currentGroupIndex, 8, GetEmotesBosses());
        foreach (var (mod, emotes) in EmoteBubbleLoader.GetAllUnlockedModEmotes())
        {
            TryAddingList(new LocalizedText(mod.Name, mod.DisplayName), ref currentGroupIndex, -1, emotes);
        }
        _totalGroups = currentGroupIndex;
    }
References Terraria.UI.UIElement.UIElement(), Terraria.GameContent.UI.States.UIEmotesMenu._backPanel, Terraria.GameContent.UI.States.UIEmotesMenu._container, Terraria.GameContent.UI.States.UIEmotesMenu._list, Terraria.GameContent.UI.States.UIEmotesMenu._outerContainer, Terraria.GameContent.UI.States.UIEmotesMenu._scrollBar, Terraria.GameContent.UI.States.UIEmotesMenu._totalGroups, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UIEmotesMenu.FadedMouseOut(), Terraria.GameContent.UI.States.UIEmotesMenu.FadedMouseOver(), Terraria.UI.StyleDimension.FromPixels(), Terraria.ModLoader.EmoteBubbleLoader.GetAllUnlockedModEmotes(), Terraria.GameContent.UI.States.UIEmotesMenu.GetEmotesBiomesAndEvents(), Terraria.GameContent.UI.States.UIEmotesMenu.GetEmotesBosses(), Terraria.GameContent.UI.States.UIEmotesMenu.GetEmotesCritters(), Terraria.GameContent.UI.States.UIEmotesMenu.GetEmotesGeneral(), Terraria.GameContent.UI.States.UIEmotesMenu.GetEmotesItems(), Terraria.GameContent.UI.States.UIEmotesMenu.GetEmotesRPS(), Terraria.GameContent.UI.States.UIEmotesMenu.GetEmotesTownNPCs(), Terraria.Localization.Language.GetText(), Terraria.GameContent.UI.States.UIEmotesMenu.GoBackClick(), Terraria.UI.UIElement.Height, Terraria.UI.UIElement.RemoveAllChildren(), Terraria.UI.StyleDimension.Set(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.UI.UIElement.Top, Terraria.GameContent.UI.States.UIEmotesMenu.TryAddingList(), and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIEmotesMenu.OnActivate().