TModLoader: Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        UILinkPointNavigator.Shortcuts.BackButtonCommand = 1;
        int num = 3001;
        int num4 = num;
        List<SnapPoint> snapPoints = GetSnapPoints();
        Rectangle val = _backPanel.GetInnerDimensions().ToRectangle();
        UILinkPointNavigator.SetPosition(num, ((Rectangle)(ref val)).Center.ToVector2());
        UILinkPoint uILinkPoint = UILinkPointNavigator.Points[num4];
        uILinkPoint.Unlink();
        uILinkPoint.Up = num4 + 1;
        UILinkPoint uILinkPoint2 = uILinkPoint;
        num4++;
        float num5 = 1f / Main.UIScale;
        Rectangle clippingRectangle = _container.GetClippingRectangle(spriteBatch);
        Vector2 minimum = clippingRectangle.TopLeft() * num5;
        Vector2 maximum = clippingRectangle.BottomRight() * num5;
        for (int i = 0; i < snapPoints.Count; i++)
        {
            if (!snapPoints[i].Position.Between(minimum, maximum))
            {
                snapPoints.Remove(snapPoints[i]);
                i--;
            }
        }
        int num6 = 0;
        int num7 = 0;
        int num8 = 7;
        List<List<SnapPoint>> list = new List<List<SnapPoint>>();
        for (int j = 0; j < num8; j++)
        {
            List<SnapPoint> emoteGroup = GetEmoteGroup(snapPoints, j);
            if (emoteGroup.Count > 0)
            {
                list.Add(emoteGroup);
            }
        }
        List<SnapPoint>[] array = list.ToArray();
        for (int k = 0; k < array.Length; k++)
        {
            List<SnapPoint> list2 = array[k];
            int num9 = list2.Count / 14;
            if (list2.Count % 14 > 0)
            {
                num9++;
            }
            int num10 = 14;
            if (list2.Count % 14 != 0)
            {
                num10 = list2.Count % 14;
            }
            for (int l = 0; l < list2.Count; l++)
            {
                uILinkPoint = UILinkPointNavigator.Points[num4];
                uILinkPoint.Unlink();
                UILinkPointNavigator.SetPosition(num4, list2[l].Position);
                int num11 = 14;
                if (l / 14 == num9 - 1 && list2.Count % 14 != 0)
                {
                    num11 = list2.Count % 14;
                }
                int num2 = l % 14;
                uILinkPoint.Left = num4 - 1;
                uILinkPoint.Right = num4 + 1;
                uILinkPoint.Up = num4 - 14;
                uILinkPoint.Down = num4 + 14;
                if (num2 == num11 - 1)
                {
                    uILinkPoint.Right = num4 - num11 + 1;
                }
                if (num2 == 0)
                {
                    uILinkPoint.Left = num4 + num11 - 1;
                }
                if (num2 == 0)
                {
                    uILinkPoint2.Up = num4;
                }
                if (l < 14)
                {
                    if (num6 == 0)
                    {
                        uILinkPoint.Up = -1;
                    }
                    else
                    {
                        uILinkPoint.Up = num4 - 14;
                        if (num2 >= num6)
{
                            uILinkPoint.Up -= 14;
                        }
                        int num3 = k - 1;
                        while (num3 > 0 && array[num3].Count <= num2)
{
                            uILinkPoint.Up -= 14;
                            num3--;
                        }
                    }
                }
                int down = num;
                if (k == array.Length - 1)
                {
                    if (l / 14 < num9 - 1 && num2 >= list2.Count % 14)
                    {
                        uILinkPoint.Down = down;
                    }
                    if (l / 14 == num9 - 1)
                    {
                        uILinkPoint.Down = down;
                    }
                }
                else if (l / 14 == num9 - 1)
                {
                    uILinkPoint.Down = num4 + 14;
                    for (int m = k + 1; m < array.Length && array[m].Count <= num2; m++)
                    {
                        uILinkPoint.Down += 14;
                    }
                    if (k == array.Length - 1)
                    {
                        uILinkPoint.Down = down;
                    }
                }
                else if (num2 >= num10)
                {
                    uILinkPoint.Down = num4 + 14 + 14;
                    for (int n = k + 1; n < array.Length && array[n].Count <= num2; n++)
                    {
                        uILinkPoint.Down += 14;
                    }
                }
                num4++;
            }
            num6 = num10;
            num7 = 14 - num6;
            num4 += num7;
        }
    }
References Terraria.GameContent.UI.States.UIEmotesMenu._backPanel, Terraria.GameContent.UI.States.UIEmotesMenu._container, Terraria.GameContent.Count, Terraria.UI.UIElement.GetClippingRectangle(), Terraria.GameContent.UI.States.UIEmotesMenu.GetEmoteGroup(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.UI.CalculatedStyle.ToRectangle(), and Terraria.Main.UIScale.