TModLoader: Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.DrawSelf
DrawSelf()
override void Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.GameContent.UI.Elements.UIPanel.
Definition at line 212 of file UIModDownloadItem.cs.
    {
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        base.DrawSelf(spriteBatch);
        if (HasModIcon && ModIconStatus == ModIconStatus.UNKNOWN)
        {
            RequestModIcon();
        }
        CalculatedStyle innerDimensions = GetInnerDimensions();
        float leftOffset = (HasModIcon ? ModIconAdjust : 0f);
        Vector2 drawPos = default(Vector2);
        ((Vector2)(ref drawPos))._002Ector(innerDimensions.X + 5f + leftOffset, innerDimensions.Y + 30f);
        spriteBatch.Draw(_dividerTexture.Value, drawPos, (Rectangle?)null, Color.White, 0f, Vector2.Zero, new Vector2((innerDimensions.Width - 10f - leftOffset) / 8f, 1f), (SpriteEffects)0, 0f);
        ((Vector2)(ref drawPos))._002Ector(innerDimensions.X + innerDimensions.Width - 125f, innerDimensions.Y + 45f);
        DrawTimeText(spriteBatch, drawPos);
        UIImage updateButton = _updateButton;
        if (updateButton != null && updateButton.IsMouseHovering)
        {
            tooltip = Language.GetTextValue("tModLoader.BrowserRejectWarning");
            return;
        }
        UIImage updateWithDepsButton = _updateWithDepsButton;
        if (updateWithDepsButton != null && updateWithDepsButton.IsMouseHovering)
        {
            tooltip = UpdateWithDepsText;
            return;
        }
        UIImage moreInfoButton = _moreInfoButton;
        if (moreInfoButton != null && moreInfoButton.IsMouseHovering)
        {
            tooltip = ViewModInfoText;
        }
    }
References Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem._dividerTexture, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem._moreInfoButton, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem._updateButton, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem._updateWithDepsButton, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.DrawTimeText(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.HasModIcon, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ModIconAdjust, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.RequestModIcon(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.tooltip, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.UpdateWithDepsText, and Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ViewModInfoText.