TModLoader: Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ShowGameNeedsRestart
ShowGameNeedsRestart()
void Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ShowGameNeedsRestart (UIMouseEvent evt, UIElement element) inline private
    {
        Utils.ShowFancyErrorMessage(Language.GetTextValue("tModLoader.SteamRejectUpdate", ModDownload.DisplayName), 10007);
    }
References Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ModDownload, and Terraria.Utils.ShowFancyErrorMessage().
Referenced by Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.UIModDownloadItem().