TModLoader: Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.UIModDownloadItem
UIModDownloadItem()
Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.UIModDownloadItem (ModDownloadItem modDownloadItem) inline
Definition at line 78 of file UIModDownloadItem.cs.
    {
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_0220: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_0237: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_0253: Unknown result type (might be due to invalid IL or missing references)
        //IL_0258: Unknown result type (might be due to invalid IL or missing references)
        ModDownload = modDownloadItem;
        BorderColor = new Color(89, 116, 213) * 0.7f;
        _dividerTexture = UICommon.DividerTexture;
        _innerPanelTexture = UICommon.InnerPanelTexture;
        Height.Pixels = 90f;
        Width.Percent = 1f;
        SetPadding(6f);
        float leftOffset = (HasModIcon ? ModIconAdjust : 0f);
        _modName = new UIText(ModDownload.DisplayName)
        {
            Left = new StyleDimension(leftOffset + 5f, 0f),
            Top =
            {
                Pixels = 5f
            }
        };
        Append(_modName);
        _moreInfoButton = new UIImage(UICommon.ButtonModInfoTexture)
        {
            Width =
            {
                Pixels = 36f
            },
            Height =
            {
                Pixels = 36f
            },
            Left =
            {
                Pixels = leftOffset
            },
            Top =
            {
                Pixels = 40f
            }
        };
        _moreInfoButton.OnLeftClick += ViewModInfo;
        Append(_moreInfoButton);
        Version modBuildVersion = ModDownload.ModloaderVersion;
        tMLNeedUpdate = !BuildInfo.IsDev && BuildInfo.tMLVersion < modBuildVersion;
        if (tMLNeedUpdate)
        {
            string updateVersion = $"v{modBuildVersion}";
            bool lastMonth = BuildInfo.tMLVersion.Minor == 12;
            if (BuildInfo.IsStable && new Version(modBuildVersion.Major, modBuildVersion.Minor) == new Version(BuildInfo.tMLVersion.Major + (lastMonth ? 1 : 0), BuildInfo.tMLVersion.Minor + ((!lastMonth) ? 1 : 0)))
            {
                updateVersion = "Preview " + updateVersion;
            }
            tMLUpdateRequired = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.MBRequiresTMLUpdate", updateVersion)).WithFadedMouseOver(Color.Orange, Color.Orange * 0.7f);
            tMLUpdateRequired.BackgroundColor = Color.Orange * 0.7f;
            tMLUpdateRequired.CopyStyle(_moreInfoButton);
            tMLUpdateRequired.Width.Pixels = 340f;
            tMLUpdateRequired.Left.Pixels += 41f;
            tMLUpdateRequired.OnLeftClick += delegate
            {
                Utils.OpenToURL("https://github.com/tModLoader/tModLoader/releases/latest");
            };
            Append(tMLUpdateRequired);
        }
        _updateButton = new UIImage(UICommon.ButtonExclamationTexture);
        _updateButton.CopyStyle(_moreInfoButton);
        _updateButton.Left.Pixels += 41f;
        _updateButton.OnLeftClick += ShowGameNeedsRestart;
        _updateWithDepsButton = new UIImage(UICommon.ButtonDownloadMultipleTexture);
        _updateWithDepsButton.CopyStyle(_moreInfoButton);
        _updateWithDepsButton.Left.Pixels += 41f;
        _updateWithDepsButton.OnLeftClick += DownloadWithDeps;
        string modReferencesBySlug = ModDownload.ModReferencesBySlug;
        if (modReferencesBySlug != null && modReferencesBySlug.Length > 0)
        {
            Asset<Texture2D> icon = UICommon.ButtonExclamationTexture;
            UIHoverImage modReferenceIcon = new UIHoverImage(icon, Language.GetTextValue("tModLoader.MBClickToViewDependencyMods", string.Join("\n", from x in ModDownload.ModReferencesBySlug.Split(',')
                select x.Trim())))
            {
                Left =
                {
                    Pixels = (float)(-icon.Width()) - 5f,
                    Percent = 1f
                }
            };
            modReferenceIcon.OnLeftClick += ShowModDependencies;
            Append(modReferenceIcon);
        }
        base.OnLeftDoubleClick += ViewModInfo;
        UpdateInstallDisplayState();
    }
References Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem._dividerTexture, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem._innerPanelTexture, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem._modName, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem._moreInfoButton, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem._updateButton, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem._updateWithDepsButton, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIPanel.BorderColor, Terraria.ModLoader.UI.UICommon.ButtonDownloadMultipleTexture, Terraria.ModLoader.UI.UICommon.ButtonExclamationTexture, Terraria.ModLoader.UI.UICommon.ButtonModInfoTexture, Terraria.ModLoader.UI.UICommon.DividerTexture, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.DownloadWithDeps(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.HasModIcon, Terraria.UI.UIElement.Height, Terraria.ModLoader.UI.UICommon.InnerPanelTexture, Terraria.ModLoader.BuildInfo.IsStable, Terraria.UI.UIElement.Left, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ModDownload, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ModIconAdjust, Terraria.Utils.OpenToURL(), Terraria.UI.UIElement.SetPadding(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ShowGameNeedsRestart(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ShowModDependencies(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.tMLNeedUpdate, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.tMLUpdateRequired, Terraria.ModLoader.BuildInfo.tMLVersion, Terraria.UI.UIElement.Top, Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.UpdateInstallDisplayState(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ViewModInfo(), and Terraria.UI.UIElement.Width.
Referenced by Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ShowModDependencies().