TModLoader: Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.DrawTimeText
DrawTimeText()
void Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.DrawTimeText (SpriteBatch spriteBatch, Vector2 drawPos) inline private
    {
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0102: Unknown result type (might be due to invalid IL or missing references)
        //IL_0107: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        if (ModDownload.TimeStamp == DateTime.MinValue)
        {
            return;
        }
        spriteBatch.Draw(_innerPanelTexture.Value, drawPos, (Rectangle?)new Rectangle(0, 0, 8, _innerPanelTexture.Height()), Color.White);
        spriteBatch.Draw(_innerPanelTexture.Value, new Vector2(drawPos.X + 8f, drawPos.Y), (Rectangle?)new Rectangle(8, 0, 8, _innerPanelTexture.Height()), Color.White, 0f, Vector2.Zero, new Vector2(13.625f, 1f), (SpriteEffects)0, 0f);
        spriteBatch.Draw(_innerPanelTexture.Value, new Vector2(drawPos.X + 125f - 8f, drawPos.Y), (Rectangle?)new Rectangle(16, 0, 8, _innerPanelTexture.Height()), Color.White);
        drawPos += new Vector2(0f, 2f);
        try
        {
            string text = TimeHelper.HumanTimeSpanString(ModDownload.TimeStamp);
            int textWidth = (int)FontAssets.MouseText.Value.MeasureString(text).X;
            int diffWidth = 125 - textWidth;
            drawPos.X += (float)diffWidth * 0.5f;
            Utils.DrawBorderString(spriteBatch, text, drawPos, Color.White);
        }
        catch (Exception e)
        {
            Logging.tML.Error((object)"Problem during drawing of time text", e);
        }
    }
References Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem._innerPanelTexture, Terraria.Utils.DrawBorderString(), Terraria.ModLoader.UI.ModBrowser.TimeHelper.HumanTimeSpanString(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ModDownload, Terraria.GameContent.FontAssets.MouseText, and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.DrawSelf().