TModLoader: Terraria.ModLoader.PlayerDrawLayer.DrawWithTransformationAndChildren
DrawWithTransformationAndChildren()
void Terraria.ModLoader.PlayerDrawLayer.DrawWithTransformationAndChildren (ref PlayerDrawSet drawInfo) inline inherited
    {
        if (!Visible)
        {
            return;
        }
        Transform?.PreDrawRecursive(ref drawInfo);
        foreach (PlayerDrawLayer item in ChildrenBefore)
        {
            item.DrawWithTransformationAndChildren(ref drawInfo);
        }
        Draw(ref drawInfo);
        foreach (PlayerDrawLayer item2 in ChildrenAfter)
        {
            item2.DrawWithTransformationAndChildren(ref drawInfo);
        }
        Transform?.PostDrawRecursive(ref drawInfo);
    }
References Terraria.ModLoader.PlayerDrawLayer.ChildrenAfter, Terraria.ModLoader.PlayerDrawLayer.ChildrenBefore, Terraria.ModLoader.PlayerDrawLayer.Draw(), Terraria.ModLoader.PlayerDrawLayer.DrawWithTransformationAndChildren(), Terraria.ModLoader.PlayerDrawLayer.Transform, and Terraria.ModLoader.PlayerDrawLayer.Visible.
Referenced by Terraria.ModLoader.PlayerDrawLayer.DrawWithTransformationAndChildren().