TModLoader: Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.DrawManaBar
DrawManaBar()
void Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.DrawManaBar (SpriteBatch spriteBatch) inline private
Definition at line 256 of file FancyClassicPlayerResourcesDisplaySet.cs.
    {
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        Color color = default(Color);
        ((Color)(ref color))._002Ector((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor);
        if (ResourceOverlayLoader.PreDrawResourceDisplay(preparedSnapshot, this, drawingLife: false, ref color, out var drawText))
        {
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector((float)(Main.screenWidth - 40), 22f);
            _ = _starCount;
            bool isHovered = false;
            ResourceDrawSettings resourceDrawSettings = defaultResourceDrawSettings;
            resourceDrawSettings.ElementCount = _starCount;
            resourceDrawSettings.ElementIndexOffset = 0;
            resourceDrawSettings.TopLeftAnchor = vector;
            resourceDrawSettings.GetTextureMethod = StarPanelDrawer;
            resourceDrawSettings.OffsetPerDraw = Vector2.Zero;
            resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.UnitY;
            resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
            resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = Vector2.Zero;
            resourceDrawSettings.Draw(spriteBatch, ref isHovered);
            resourceDrawSettings = defaultResourceDrawSettings;
            resourceDrawSettings.ElementCount = _starCount;
            resourceDrawSettings.ElementIndexOffset = 0;
            resourceDrawSettings.TopLeftAnchor = vector + new Vector2(15f, 16f);
            resourceDrawSettings.GetTextureMethod = StarFillingDrawer;
            resourceDrawSettings.OffsetPerDraw = Vector2.UnitY * -2f;
            resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.UnitY;
            resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
            resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = new Vector2(0.5f, 0.5f);
            resourceDrawSettings.Draw(spriteBatch, ref isHovered);
            _hoverMana = isHovered && ResourceOverlayLoader.DisplayHoverText(preparedSnapshot, this, drawingLife: false);
        }
        ResourceOverlayLoader.PostDrawResourceDisplay(preparedSnapshot, this, drawingLife: false, color, drawText);
    }
References Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet._hoverMana, Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet._starCount, Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.defaultResourceDrawSettings, Terraria.ModLoader.ResourceOverlayLoader.DisplayHoverText(), Terraria.Main.mouseTextColor, Terraria.ModLoader.ResourceOverlayLoader.PostDrawResourceDisplay(), Terraria.ModLoader.ResourceOverlayLoader.PreDrawResourceDisplay(), Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.preparedSnapshot, Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.StarFillingDrawer(), and Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.StarPanelDrawer().
Referenced by Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.Draw().