TModLoader: Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.DrawLifeBar
DrawLifeBar()
void Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.DrawLifeBar (SpriteBatch spriteBatch) inline private
    {
        //IL_02e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00de: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        //IL_0146: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0198: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_0233: Unknown result type (might be due to invalid IL or missing references)
        //IL_023e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0243: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_0257: Unknown result type (might be due to invalid IL or missing references)
        //IL_025c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0276: Unknown result type (might be due to invalid IL or missing references)
        //IL_0280: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        //IL_028c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0291: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        Color color = default(Color);
        ((Color)(ref color))._002Ector((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor);
        if (ResourceOverlayLoader.PreDrawResourceDisplay(preparedSnapshot, this, drawingLife: true, ref color, out var drawText))
        {
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector((float)(Main.screenWidth - 300 + 4), 15f);
            if (_drawText)
            {
                vector.Y += 6f;
                DrawLifeBarText(spriteBatch, vector + new Vector2(-4f, 3f));
            }
            bool isHovered = false;
            ResourceDrawSettings resourceDrawSettings = defaultResourceDrawSettings;
            resourceDrawSettings.ElementCount = _heartCountRow1;
            resourceDrawSettings.ElementIndexOffset = 0;
            resourceDrawSettings.TopLeftAnchor = vector;
            resourceDrawSettings.GetTextureMethod = HeartPanelDrawer;
            resourceDrawSettings.OffsetPerDraw = Vector2.Zero;
            resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.UnitX;
            resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
            resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = Vector2.Zero;
            resourceDrawSettings.Draw(spriteBatch, ref isHovered);
            resourceDrawSettings = defaultResourceDrawSettings;
            resourceDrawSettings.ElementCount = _heartCountRow2;
            resourceDrawSettings.ElementIndexOffset = 10;
            resourceDrawSettings.TopLeftAnchor = vector + new Vector2(0f, 28f);
            resourceDrawSettings.GetTextureMethod = HeartPanelDrawer;
            resourceDrawSettings.OffsetPerDraw = Vector2.Zero;
            resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.UnitX;
            resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
            resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = Vector2.Zero;
            resourceDrawSettings.Draw(spriteBatch, ref isHovered);
            resourceDrawSettings = defaultResourceDrawSettings;
            resourceDrawSettings.ElementCount = _heartCountRow1;
            resourceDrawSettings.ElementIndexOffset = 0;
            resourceDrawSettings.TopLeftAnchor = vector + new Vector2(15f, 15f);
            resourceDrawSettings.GetTextureMethod = HeartFillingDrawer;
            resourceDrawSettings.OffsetPerDraw = Vector2.UnitX * 2f;
            resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.UnitX;
            resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
            resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = new Vector2(0.5f, 0.5f);
            resourceDrawSettings.Draw(spriteBatch, ref isHovered);
            resourceDrawSettings = defaultResourceDrawSettings;
            resourceDrawSettings.ElementCount = _heartCountRow2;
            resourceDrawSettings.ElementIndexOffset = 10;
            resourceDrawSettings.TopLeftAnchor = vector + new Vector2(15f, 15f) + new Vector2(0f, 28f);
            resourceDrawSettings.GetTextureMethod = HeartFillingDrawer;
            resourceDrawSettings.OffsetPerDraw = Vector2.UnitX * 2f;
            resourceDrawSettings.OffsetPerDrawByTexturePercentile = Vector2.UnitX;
            resourceDrawSettings.OffsetSpriteAnchor = Vector2.Zero;
            resourceDrawSettings.OffsetSpriteAnchorByTexturePercentile = new Vector2(0.5f, 0.5f);
            resourceDrawSettings.Draw(spriteBatch, ref isHovered);
            _hoverLife = isHovered && ResourceOverlayLoader.DisplayHoverText(preparedSnapshot, this, drawingLife: true);
        }
        ResourceOverlayLoader.PostDrawResourceDisplay(preparedSnapshot, this, drawingLife: true, color, drawText);
    }
References Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet._drawText, Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet._heartCountRow1, Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet._heartCountRow2, Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet._hoverLife, Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.defaultResourceDrawSettings, Terraria.ModLoader.ResourceOverlayLoader.DisplayHoverText(), Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.DrawLifeBarText(), Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.HeartFillingDrawer(), Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.HeartPanelDrawer(), Terraria.Main.mouseTextColor, Terraria.ModLoader.ResourceOverlayLoader.PostDrawResourceDisplay(), Terraria.ModLoader.ResourceOverlayLoader.PreDrawResourceDisplay(), and Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.preparedSnapshot.
Referenced by Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.Draw().