TModLoader: Terraria.Player.OverheadMessage.NewMessage
NewMessage()
void Terraria.Player.OverheadMessage.NewMessage (string message, int displayTime) inline
        {
            //IL_000e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0033: Unknown result type (might be due to invalid IL or missing references)
            //IL_003d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0042: Unknown result type (might be due to invalid IL or missing references)
            chatText = message;
            snippets = ChatManager.ParseMessage(chatText, Color.White).ToArray();
            messageSize = ChatManager.GetStringSize(FontAssets.MouseText.Value, snippets, Vector2.One);
            timeLeft = displayTime;
        }
References Terraria.Player.OverheadMessage.chatText, Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Player.OverheadMessage.messageSize, Terraria.GameContent.FontAssets.MouseText, Terraria.UI.Chat.ChatManager.ParseMessage(), Terraria.Player.OverheadMessage.snippets, and Terraria.Player.OverheadMessage.timeLeft.
Referenced by Terraria.Chat.ChatHelper.DisplayMessage().