TModLoader: Terraria.Map.MapHelper.CreateMapTile
CreateMapTile()
static MapTile Terraria.Map.MapHelper.CreateMapTile (int i, int j, byte Light) inline static
Definition at line 4303 of file MapHelper.cs.
    {
        Tile tile = Main.tile[i, j];
        if (tile == null)
        {
            return default(MapTile);
        }
        int num = 0;
        int num4 = Light;
        _ = Main.Map[i, j];
        int num5 = 0;
        int baseOption = 0;
        if (tile.active())
        {
            int num6 = tile.type;
            num5 = tileLookup[num6];
            bool flag = tile.invisibleBlock();
            if (tile.fullbrightBlock() && !flag)
            {
                num4 = 255;
            }
            if (flag)
            {
                num5 = 0;
            }
            else if (num6 == 5)
            {
                if (WorldGen.IsThisAMushroomTree(i, j))
                {
                    baseOption = 1;
                }
                num = tile.color();
            }
            else
            {
                switch (num6)
                {
                case 51:
                    if ((i + j) % 2 == 0)
                    {
                        num5 = 0;
                    }
                    break;
                case 19:
                    if (tile.frameY == 864)
                    {
                        num5 = 0;
                    }
                    break;
                case 184:
                    if (tile.frameX / 22 == 10)
                    {
                        num6 = 627;
                        num5 = tileLookup[num6];
                    }
                    break;
                }
                if (num5 != 0)
                {
                    GetTileBaseOption(i, j, num6, tile, ref baseOption);
                    num = ((num6 != 160) ? tile.color() : 0);
                }
            }
        }
        if (num5 == 0)
        {
            bool flag2 = tile.invisibleWall();
            if (tile.wall > 0 && tile.fullbrightWall() && !flag2)
            {
                num4 = 255;
            }
            if (tile.liquid > 32)
            {
                int num7 = tile.liquidType();
                num5 = liquidPosition + num7;
            }
            else if (!tile.invisibleWall() && tile.wall > 0 && tile.wall < WallLoader.WallCount)
            {
                int wall = tile.wall;
                num5 = wallLookup[wall];
                num = tile.wallColor();
                switch (wall)
                {
                case 21:
                case 88:
                case 89:
                case 90:
                case 91:
                case 92:
                case 93:
                case 168:
                case 241:
                    num = 0;
                    break;
                case 27:
                    baseOption = i % 2;
                    break;
                default:
                    baseOption = 0;
                    break;
                }
            }
        }
        if (num5 == 0)
        {
            if ((double)j < Main.worldSurface)
            {
                if (Main.remixWorld)
                {
                    num4 = 5;
                    num5 = 100;
                }
                else
                {
                    int num8 = (byte)(255.0 * ((double)j / Main.worldSurface));
                    num5 = skyPosition + num8;
                    num4 = 255;
                    num = 0;
                }
            }
            else if (j < Main.UnderworldLayer)
            {
                num = 0;
                byte b = 0;
                float num9 = Main.screenPosition.X / 16f - 5f;
                float num10 = (Main.screenPosition.X + (float)Main.screenWidth) / 16f + 5f;
                float num11 = Main.screenPosition.Y / 16f - 5f;
                float num2 = (Main.screenPosition.Y + (float)Main.screenHeight) / 16f + 5f;
                if (((float)i < num9 || (float)i > num10 || (float)j < num11 || (float)j > num2) && i > 40 && i < Main.maxTilesX - 40 && j > 40 && j < Main.maxTilesY - 40)
                {
                    for (int k = i - 36; k <= i + 30; k += 10)
                    {
                        for (int l = j - 36; l <= j + 30; l += 10)
{
                            int type = Main.Map[k, l].Type;
                            for (int m = 0; m < snowTypes.Length; m++)
{
                                if (snowTypes[m] == type)
{
                                    b = byte.MaxValue;
                                    k = i + 31;
                                    l = j + 31;
                                    break;
                                }
                            }
                        }
                    }
                }
                else
                {
                    float num3 = (float)Main.SceneMetrics.SnowTileCount / (float)SceneMetrics.SnowTileMax;
                    num3 *= 255f;
                    if (num3 > 255f)
                    {
                        num3 = 255f;
                    }
                    b = (byte)num3;
                }
                num5 = ((!((double)j < Main.rockLayer)) ? (rockPosition + b) : (dirtPosition + b));
            }
            else
            {
                num5 = hellPosition;
            }
        }
        ushort mapType = (ushort)(num5 + baseOption);
        MapLoader.ModMapOption(ref mapType, i, j);
        return MapTile.Create(mapType, (byte)num4, (byte)num);
    }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.Map.MapTile.Create(), Terraria.Map.MapHelper.dirtPosition, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.fullbrightBlock(), Terraria.Tile.fullbrightWall(), Terraria.Map.MapHelper.GetTileBaseOption(), Terraria.Map.MapHelper.hellPosition, Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.WorldGen.IsThisAMushroomTree(), Terraria.Tile.liquid, Terraria.Map.MapHelper.liquidPosition, Terraria.Tile.liquidType(), Terraria.Main.Map, Terraria.ModLoader.MapLoader.ModMapOption(), Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.Map.MapHelper.rockPosition, Terraria.Main.SceneMetrics, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Map.MapHelper.skyPosition, Terraria.SceneMetrics.SnowTileMax, Terraria.Map.MapHelper.snowTypes, Terraria.Main.tile, Terraria.Map.MapHelper.tileLookup, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.Tile.wall, Terraria.Tile.wallColor(), Terraria.ModLoader.WallLoader.WallCount, Terraria.Map.MapHelper.wallLookup, and Terraria.Main.worldSurface.
Referenced by Terraria.Map.WorldMap.Update(), Terraria.Map.WorldMap.UpdateLighting(), and Terraria.Map.WorldMap.UpdateType().