TModLoader: Terraria.ModLoader.BackupIO.DeleteOldArchives
DeleteOldArchives()
static void Terraria.ModLoader.BackupIO.DeleteOldArchives (string dir, bool isCloudSave, string name) inline static private
Will delete old archive files Algorithm details:
One backup per day for the last week
One backup per week for the last month
One backup per month for all time
Definition at line 203 of file BackupIO.cs.
    {
        string path = Path.Combine(dir, TodaysBackup(name, isCloudSave));
        if (File.Exists(path))
        {
            DeleteArchive(path);
        }
        DateTime result;
        (FileInfo f, DateTime)[] array = (from f in new DirectoryInfo(dir).GetFiles("*" + GetArchiveName(name, isCloudSave) + "*.zip", SearchOption.TopDirectoryOnly)
            select (f: f, TryGetTime(f.Name, out result) ? result : default(DateTime)) into tuple
            where tuple.Item2 != default(DateTime)
            orderby tuple.Item2
            select tuple).ToArray();
        (FileInfo, DateTime)? previous = null;
        (FileInfo, DateTime)[] array2 = array;
        for (int i = 0; i < array2.Length; i++)
        {
            (FileInfo, DateTime) archived = array2[i];
            if (!previous.HasValue)
            {
                previous = archived;
                continue;
            }
            int freshness = (IsArchiveOlder(archived.Item2, TimeSpan.FromDays(30.0)) ? 30 : ((!IsArchiveOlder(archived.Item2, TimeSpan.FromDays(7.0))) ? 1 : 7));
            if ((archived.Item2 - previous.Value.Item2).Days < freshness)
            {
                DeleteArchive(previous.Value.Item1.FullName);
            }
            previous = archived;
        }
    }
References Terraria.ModLoader.BackupIO.DeleteArchive(), Terraria.ModLoader.BackupIO.GetArchiveName(), Terraria.ModLoader.BackupIO.IsArchiveOlder(), Terraria.ModLoader.BackupIO.TodaysBackup(), and Terraria.ModLoader.BackupIO.TryGetTime().
Referenced by Terraria.ModLoader.BackupIO.RunArchiving().