TModLoader: Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddEmptyEntries_CrittersAndEnemies_Automated
AddEmptyEntries_CrittersAndEnemies_Automated()
void Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AddEmptyEntries_CrittersAndEnemies_Automated () inline private
    {
        HashSet<int> exclusions = GetExclusions();
        foreach (KeyValuePair<int, NPC> item in ContentSamples.NpcsByNetId)
        {
            if (!exclusions.Contains(item.Key))
            {
                NPCLoader.SetBestiary(bestiaryEntry: item.Value.CountsAsACritter ? Register(BestiaryEntry.Critter(item.Key)) : ((!item.Value.isLikeATownNPC) ? Register(BestiaryEntry.Enemy(item.Key)) : Register(BestiaryEntry.TownNPC(item.Key))), npc: item.Value, database: _currentDatabase);
            }
        }
    }
References Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator._currentDatabase, Terraria.GameContent.Bestiary.BestiaryEntry.Critter(), Terraria.GameContent.Bestiary.BestiaryEntry.Enemy(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.GetExclusions(), Terraria.ID.ContentSamples.NpcsByNetId, Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.Register(), Terraria.ModLoader.NPCLoader.SetBestiary(), and Terraria.GameContent.Bestiary.BestiaryEntry.TownNPC().
Referenced by Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.Populate().