TModLoader: Terraria.NetMessage.SendPlayerHurt
SendPlayerHurt() [2/2]
static void Terraria.NetMessage.SendPlayerHurt (int playerTargetIndex, PlayerDeathReason reason, int damage, int direction, bool critical, bool pvp, int hitContext, int remoteClient = -1, int ignoreClient = -1) inline static package
Definition at line 2778 of file NetMessage.cs.
    {
        if (!pvp)
        {
            throw new ArgumentException("SendPlayerHurt is legacy, for pvp usage only. Call Player.Hurt with quiet: false, or use the Player.HurtInfo overload");
        }
        _currentPlayerDeathReason = reason;
        BitsByte bitsByte = (byte)0;
        bitsByte[0] = critical;
        bitsByte[1] = pvp;
        SendData(117, remoteClient, ignoreClient, null, playerTargetIndex, damage, direction, (int)(byte)bitsByte, hitContext);
    }
References Terraria.NetMessage._currentPlayerDeathReason, and Terraria.NetMessage.SendData().
Referenced by Terraria.Projectile.Damage(), Terraria.MessageBuffer.GetData(), Terraria.Player.Hurt(), Terraria.Player.ItemCheck_MeleeHitPVP(), and Terraria.Player.UpdateBuffs().