TModLoader: Terraria.NetMessage.greetPlayer
greetPlayer()
static void Terraria.NetMessage.greetPlayer (int plr) inline static
Definition at line 2918 of file NetMessage.cs.
    {
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        if (Main.motd == "")
        {
            ChatHelper.SendChatMessageToClient(NetworkText.FromFormattable("{0} {1}!", Lang.mp[18].ToNetworkText(), Main.worldName), new Color(255, 240, 20), plr);
        }
        else
        {
            ChatHelper.SendChatMessageToClient(NetworkText.FromLiteral(Main.motd), new Color(255, 240, 20), plr);
        }
        string text = "";
        for (int i = 0; i < 255; i++)
        {
            if (Main.player[i].active)
            {
                text = ((!(text == "")) ? (text + ", " + Main.player[i].name) : (text + Main.player[i].name));
            }
        }
        ChatHelper.SendChatMessageToClient(NetworkText.FromKey("Game.JoinGreeting", text), new Color(255, 240, 20), plr);
    }
References Terraria.Entity.active, Terraria.Localization.NetworkText.FromFormattable(), Terraria.Localization.NetworkText.FromKey(), Terraria.Localization.NetworkText.FromLiteral(), Terraria.Main.motd, Terraria.Lang.mp, Terraria.Player.name, Terraria.Main.player, Terraria.Chat.ChatHelper.SendChatMessageToClient(), Terraria.Localization.LocalizedText.ToNetworkText(), and Terraria.Main.worldName.
Referenced by Terraria.MessageBuffer.GetData().