TModLoader: Terraria.NetMessage.ReceiveBytes
ReceiveBytes()
static void Terraria.NetMessage.ReceiveBytes (byte[] bytes, int streamLength, int i = 256) inline static
Definition at line 2634 of file NetMessage.cs.
    {
        if (ModNet.DetailedLogging)
        {
            ModNet.Debug(i, $"recv {streamLength}");
        }
        DateTime lockStart = DateTime.Now;
        lock (buffer[i])
        {
            bool firstWait = true;
            while (buffer[i].totalData + streamLength > buffer[i].readBuffer.Length)
            {
                if (firstWait)
                {
                    if (ModNet.DetailedLogging)
                    {
                        ModNet.Debug(i, "waiting for space in readBuffer");
                    }
                    firstWait = false;
                }
                Monitor.Exit(buffer[i]);
                Thread.Yield();
                Monitor.Enter(buffer[i]);
            }
            double timeToAcquireLock = (DateTime.Now - lockStart).TotalMilliseconds;
            if (timeToAcquireLock > 1.0 && ModNet.DetailedLogging)
            {
                ModNet.Debug(i, $"buffer lock contended for {timeToAcquireLock:0.0}ms");
            }
            try
            {
                Buffer.BlockCopy(bytes, 0, buffer[i].readBuffer, buffer[i].totalData, streamLength);
                buffer[i].totalData += streamLength;
                buffer[i].checkBytes = true;
            }
            catch (Exception e)
            {
                if (Main.netMode == 1)
                {
                    Main.menuMode = 15;
                    Main.statusText = Language.GetTextValue("Error.BadHeaderBufferOverflow");
                    ModNet.Error($"BlockCopy bounds error: srclen={bytes.Length}, dstlen={buffer[i].readBuffer.Length}, dstoffset={buffer[i].totalData}, num={streamLength}", e);
                    Netplay.Disconnect = true;
                }
                else
                {
                    Netplay.Clients[i].SetPendingTermination("Exception in ReceiveBytes " + e.Message);
                }
            }
        }
    }
References Terraria.NetMessage.buffer, Terraria.MessageBuffer.checkBytes, Terraria.Netplay.Clients, Terraria.ModLoader.ModNet.Debug(), Terraria.ModLoader.ModNet.DetailedLogging, Terraria.ModLoader.ModNet.Error(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.netMode, Terraria.RemoteClient.SetPendingTermination(), and Terraria.MessageBuffer.totalData.
Referenced by Terraria.RemoteServer.ClientReadCallBack(), and Terraria.RemoteClient.ServerReadCallBack().