TModLoader: Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.Generate
Generate()
void Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.Generate () inline private
        {
            //IL_003f: Unknown result type (might be due to invalid IL or missing references)
            //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
            //IL_0053: Unknown result type (might be due to invalid IL or missing references)
            //IL_0075: Unknown result type (might be due to invalid IL or missing references)
            //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
            //IL_019d: Unknown result type (might be due to invalid IL or missing references)
            //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
            //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
            //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
            //IL_0204: Unknown result type (might be due to invalid IL or missing references)
            //IL_0209: Unknown result type (might be due to invalid IL or missing references)
            //IL_0330: Unknown result type (might be due to invalid IL or missing references)
            //IL_03d4: Unknown result type (might be due to invalid IL or missing references)
            //IL_03d9: Unknown result type (might be due to invalid IL or missing references)
            //IL_03dd: Unknown result type (might be due to invalid IL or missing references)
            //IL_0404: Unknown result type (might be due to invalid IL or missing references)
            Clear();
            bool[,] array = new bool[Width, Height];
            int num = Width / 2 - 1;
            int num2 = Height / 2 - 1;
            int num3 = (num + 1) * (num + 1);
            Point point = default(Point);
            ((Point)(ref point))._002Ector(num, num2);
            for (int i = point.Y - num2; i <= point.Y + num2; i++)
            {
                double num4 = (double)num / (double)num2 * (double)(i - point.Y);
                int num5 = Math.Min(num, (int)Math.Sqrt((double)num3 - num4 * num4));
                for (int j = point.X - num5; j <= point.X + num5; j++)
                {
                    array[j, i] = WorldGen.genRand.Next(2) == 0;
                }
            }
            List<List<Point>> list = new List<List<Point>>();
            for (int k = 0; k < array.GetLength(0); k++)
            {
                for (int l = 0; l < array.GetLength(1); l++)
                {
                    if (array[k, l] && WorldGen.genRand.Next(2) == 0)
                    {
                        List<Point> list2 = new List<Point>();
                        SearchForCluster(array, list2, k, l);
                        if (list2.Count > 2)
{
                            list.Add(list2);
                        }
                    }
                }
            }
            int[,] array2 = new int[array.GetLength(0), array.GetLength(1)];
            for (int m = 0; m < array2.GetLength(0); m++)
            {
                for (int n = 0; n < array2.GetLength(1); n++)
                {
                    array2[m, n] = -1;
                }
            }
            for (int num6 = 0; num6 < list.Count; num6++)
            {
                foreach (Point item in list[num6])
                {
                    array2[item.X, item.Y] = num6;
                }
            }
            for (int num7 = 0; num7 < list.Count; num7++)
            {
                foreach (Point item5 in list[num7])
                {
                    int x = item5.X;
                    int y = item5.Y;
                    if (array2[x, y] == -1)
                    {
                        break;
                    }
                    int index = array2[x, y];
                    if (x > 0)
                    {
                        AttemptClaim(x - 1, y, array2, list, index);
                    }
                    if (x < array2.GetLength(0) - 1)
                    {
                        AttemptClaim(x + 1, y, array2, list, index);
                    }
                    if (y > 0)
                    {
                        AttemptClaim(x, y - 1, array2, list, index);
                    }
                    if (y < array2.GetLength(1) - 1)
                    {
                        AttemptClaim(x, y + 1, array2, list, index);
                    }
                }
            }
            foreach (List<Point> item6 in list)
            {
                item6.Clear();
            }
            for (int num8 = 0; num8 < array2.GetLength(0); num8++)
            {
                for (int num9 = 0; num9 < array2.GetLength(1); num9++)
                {
                    if (array2[num8, num9] != -1)
                    {
                        list[array2[num8, num9]].Add(new Point(num8, num9));
                    }
                }
            }
            foreach (List<Point> item2 in list)
            {
                if (item2.Count < 4)
                {
                    item2.Clear();
                }
            }
            foreach (List<Point> item3 in list)
            {
                Cluster cluster = new Cluster();
                if (item3.Count <= 0)
                {
                    continue;
                }
                foreach (Point item4 in item3)
                {
                    cluster.Add(new Block((double)item4.X + (WorldGen.genRand.NextDouble() - 0.5) * 0.5, (double)item4.Y + (WorldGen.genRand.NextDouble() - 0.5) * 0.5));
                }
                Add(cluster);
            }
        }
References Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.AttemptClaim(), Terraria.WorldGen.genRand, Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.Height, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.SearchForCluster(), and Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.Width.
Referenced by Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.ClusterGroup().