TModLoader: Terraria.ID.NPCID.Sets.NPCBestiaryDrawOffsetCreation
NPCBestiaryDrawOffsetCreation()
static Dictionary< int, NPCBestiaryDrawModifiers > Terraria.ID.NPCID.Sets.NPCBestiaryDrawOffsetCreation () inline static
Definition at line 733 of file NPCID.cs.
        {
            Dictionary<int, NPCBestiaryDrawModifiers> redigitEntries = GetRedigitEntries();
            Dictionary<int, NPCBestiaryDrawModifiers> leinforsEntries = GetLeinforsEntries();
            Dictionary<int, NPCBestiaryDrawModifiers> groxEntries = GetGroxEntries();
            Dictionary<int, NPCBestiaryDrawModifiers> dictionary = new Dictionary<int, NPCBestiaryDrawModifiers>();
            foreach (KeyValuePair<int, NPCBestiaryDrawModifiers> item in groxEntries)
            {
                dictionary[item.Key] = FilterPaths(item.Value);
            }
            foreach (KeyValuePair<int, NPCBestiaryDrawModifiers> item2 in leinforsEntries)
            {
                dictionary[item2.Key] = FilterPaths(item2.Value);
            }
            foreach (KeyValuePair<int, NPCBestiaryDrawModifiers> item3 in redigitEntries)
            {
                dictionary[item3.Key] = FilterPaths(item3.Value);
            }
            return dictionary;
            static NPCBestiaryDrawModifiers FilterPaths(NPCBestiaryDrawModifiers modifiers)
            {
                if (modifiers.CustomTexturePath != null)
                {
                    modifiers.CustomTexturePath = "Terraria/" + modifiers.CustomTexturePath;
                }
                return modifiers;
            }
        }
References Terraria.ID.NPCID.Sets.GetGroxEntries(), Terraria.ID.NPCID.Sets.GetLeinforsEntries(), and Terraria.ID.NPCID.Sets.GetRedigitEntries().
Referenced by Terraria.ID.NPCID.Sets.Sets().