TModLoader: Terraria.ModLoader.UI.UIModSourceItem.PublishModCommandLine
PublishModCommandLine()
static void Terraria.ModLoader.UI.UIModSourceItem.PublishModCommandLine (string modName) inline static package
Definition at line 453 of file UIModSourceItem.cs.
    {
        try
        {
            TmodFile modFile = new TmodFile(Path.Combine(ModLoader.ModPath, modName + ".tmod"));
            LocalMod localMod;
            using (modFile.Open())
            {
                localMod = new LocalMod(modFile);
            }
            string icon = Path.Combine(ModCompile.ModSourcePath, modName, "icon_workshop.png");
            if (!File.Exists(icon))
            {
                icon = Path.Combine(ModCompile.ModSourcePath, modName, "icon.png");
            }
            WorkshopHelper.PublishMod(localMod, icon);
        }
        catch (Exception ex)
        {
            Console.WriteLine("Something went wrong with command line mod publishing.");
            Console.WriteLine(ex.ToString());
            SteamAPI.Shutdown();
            Environment.Exit(1);
        }
        Console.WriteLine("exiting ");
        SteamAPI.Shutdown();
        Environment.Exit(0);
    }
References Terraria.ModLoader.Console, Terraria.ModLoader.Environment, Terraria.ModLoader.UI.UIModSourceItem.modName, Terraria.ModLoader.ModLoader.ModPath, Terraria.ModLoader.Core.ModCompile.ModSourcePath, Terraria.ModLoader.Core.TmodFile.Open(), and Terraria.Social.Steam.WorkshopHelper.PublishMod().
Referenced by Terraria.Initializers.LaunchInitializer.LoadServerParameters().