TModLoader: Terraria.ModLoader.UI.UIModSourceItem.PublishServerSideMod
PublishServerSideMod()
void Terraria.ModLoader.UI.UIModSourceItem.PublishServerSideMod (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 430 of file UIModSourceItem.cs.
    {
        SoundEngine.PlaySound(10);
        try
        {
            if (!SteamedWraps.SteamClient)
            {
                Utils.ShowFancyErrorMessage(Language.GetTextValue("tModLoader.SteamPublishingLimit"), 10001);
                return;
            }
            Process.Start(new ProcessStartInfo
            {
                UseShellExecute = true,
                FileName = Process.GetCurrentProcess().MainModule.FileName,
                Arguments = "tModLoader.dll -server -steam -publish " + _builtMod.modFile.path.Remove(_builtMod.modFile.path.LastIndexOf(".tmod"))
            }).WaitForExit();
        }
        catch (WebException e)
        {
            UIModBrowser.LogModBrowserException(e, 10001);
        }
    }
References Terraria.ModLoader.UI.UIModSourceItem._builtMod, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.LogModBrowserException(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Utils.ShowFancyErrorMessage(), and Terraria.Social.Steam.SteamedWraps.SteamClient.
Referenced by Terraria.ModLoader.UI.UIModSourceItem.UIModSourceItem().