TModLoader: Terraria.ModLoader.UI.UIModSourceItem.UIModSourceItem
UIModSourceItem()
Terraria.ModLoader.UI.UIModSourceItem.UIModSourceItem (string mod, LocalMod builtMod) inline
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0158: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0201: Unknown result type (might be due to invalid IL or missing references)
        //IL_0207: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_021b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0318: Unknown result type (might be due to invalid IL or missing references)
        //IL_031e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0322: Unknown result type (might be due to invalid IL or missing references)
        //IL_0328: Unknown result type (might be due to invalid IL or missing references)
        //IL_032c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0332: Unknown result type (might be due to invalid IL or missing references)
        //IL_0336: Unknown result type (might be due to invalid IL or missing references)
        //IL_033c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        _mod = mod;
        BorderColor = new Color(89, 116, 213) * 0.7f;
        _dividerTexture = UICommon.DividerTexture;
        Height.Pixels = 90f;
        Width.Percent = 1f;
        SetPadding(6f);
        string addendum = (Path.GetFileName(mod).Contains(" ") ? ("  [c/FF0000:" + Language.GetTextValue("tModLoader.MSModSourcesCantHaveSpaces") + "]") : "");
        modName = Path.GetFileName(mod);
        _modName = new UIText(modName + addendum)
        {
            Left =
            {
                Pixels = 10f
            },
            Top =
            {
                Pixels = 5f
            }
        };
        Append(_modName);
        UIAutoScaleTextTextPanel<string> buildButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.MSBuild"))
        {
            Width =
            {
                Pixels = 100f
            },
            Height =
            {
                Pixels = 36f
            },
            Left =
            {
                Pixels = 10f
            },
            Top =
            {
                Pixels = 40f
            }
        }.WithFadedMouseOver();
        buildButton.PaddingTop -= 2f;
        buildButton.PaddingBottom -= 2f;
        buildButton.OnLeftClick += BuildMod;
        Append(buildButton);
        UIAutoScaleTextTextPanel<string> buildReloadButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.MSBuildReload"));
        buildReloadButton.CopyStyle(buildButton);
        buildReloadButton.Width.Pixels = 200f;
        buildReloadButton.Left.Pixels = 150f;
        buildReloadButton.WithFadedMouseOver();
        buildReloadButton.OnLeftClick += BuildAndReload;
        Append(buildReloadButton);
        _builtMod = builtMod;
        if (builtMod != null && LocalizationLoader.changedMods.Contains(modName))
        {
            needRebuildButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.MSRebuildRequired"));
            needRebuildButton.CopyStyle(buildReloadButton);
            needRebuildButton.Width.Pixels = 180f;
            needRebuildButton.Left.Pixels = 360f;
            needRebuildButton.BackgroundColor = Color.Red;
            Append(needRebuildButton);
        }
        else if (builtMod != null)
        {
            UIAutoScaleTextTextPanel<string> publishButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.MSPublish"));
            publishButton.CopyStyle(buildReloadButton);
            publishButton.Width.Pixels = 100f;
            publishButton.Left.Pixels = 390f;
            publishButton.WithFadedMouseOver();
            if (builtMod.properties.side == ModSide.Server)
            {
                publishButton.OnLeftClick += PublishServerSideMod;
                Append(publishButton);
            }
            else if (builtMod.Enabled)
            {
                publishButton.OnLeftClick += PublishMod;
                Append(publishButton);
            }
        }
        base.OnLeftDoubleClick += BuildAndReload;
        string modFolderName = Path.GetFileName(_mod);
        string csprojFile = Path.Combine(_mod, modFolderName + ".csproj");
        if (!File.Exists(csprojFile))
        {
            return;
        }
        UIHoverImage openCSProjButton = new UIHoverImage(UICommon.CopyCodeButtonTexture, Language.GetTextValue("tModLoader.MSOpenCSProj"))
        {
            Left =
            {
                Pixels = contextButtonsLeft,
                Percent = 1f
            },
            Top =
            {
                Pixels = 4f
            }
        };
        openCSProjButton.OnLeftClick += delegate
        {
            if (Platform.IsWindows)
            {
                Process.Start(new ProcessStartInfo("explorer", csprojFile)
                {
                    UseShellExecute = true
                });
            }
            else
            {
                Process.Start(new ProcessStartInfo(csprojFile)
                {
                    UseShellExecute = true
                });
            }
        };
        Append(openCSProjButton);
        contextButtonsLeft -= 26;
    }
References Terraria.ModLoader.UI.UIModSourceItem._builtMod, Terraria.ModLoader.UI.UIModSourceItem._dividerTexture, Terraria.ModLoader.UI.UIModSourceItem._mod, Terraria.ModLoader.UI.UIModSourceItem._modName, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIPanel.BorderColor, Terraria.ModLoader.UI.UIModSourceItem.BuildAndReload(), Terraria.ModLoader.UI.UIModSourceItem.BuildMod(), Terraria.ModLoader.LocalizationLoader.changedMods, Terraria.ModLoader.UI.UIModSourceItem.contextButtonsLeft, Terraria.ModLoader.UI.UICommon.CopyCodeButtonTexture, Terraria.ModLoader.UI.UICommon.DividerTexture, Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.ModLoader.UI.UIModSourceItem.modName, Terraria.ModLoader.UI.UIModSourceItem.needRebuildButton, Terraria.ModLoader.UI.UIModSourceItem.PublishMod(), Terraria.ModLoader.UI.UIModSourceItem.PublishServerSideMod(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.Top, and Terraria.UI.UIElement.Width.