TModLoader: Terraria.ModLoader.UI.UIModSourceItem.PublishMod
PublishMod()
void Terraria.ModLoader.UI.UIModSourceItem.PublishMod (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 389 of file UIModSourceItem.cs.
    {
        SoundEngine.PlaySound(10);
        try
        {
            Mod result;
            if (!SteamedWraps.SteamClient)
            {
                Utils.ShowFancyErrorMessage(Language.GetTextValue("tModLoader.SteamPublishingLimit"), 10001);
            }
            else if (!ModLoader.TryGetMod(_builtMod.Name, out result))
            {
                if (!_builtMod.Enabled)
                {
                    _builtMod.Enabled = true;
                }
                Main.menuMode = 10006;
                ModLoader.OnSuccessfulLoad = (Action)Delegate.Combine(ModLoader.OnSuccessfulLoad, (Action)delegate
                {
                    Main.QueueMainThreadAction(delegate
                    {
                        PublishMod(null, null);
                    });
                });
            }
            else
            {
                string icon = Path.Combine(_mod, "icon_workshop.png");
                if (!File.Exists(icon))
                {
                    icon = Path.Combine(_mod, "icon.png");
                }
                WorkshopHelper.PublishMod(_builtMod, icon);
            }
        }
        catch (WebException e)
        {
            UIModBrowser.LogModBrowserException(e, 10001);
        }
    }
References Terraria.ModLoader.UI.UIModSourceItem._builtMod, Terraria.ModLoader.UI.UIModSourceItem._mod, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.LogModBrowserException(), Terraria.ModLoader.ModLoader.OnSuccessfulLoad, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Social.Steam.WorkshopHelper.PublishMod(), Terraria.ModLoader.UI.UIModSourceItem.PublishMod(), Terraria.Main.QueueMainThreadAction(), Terraria.Utils.ShowFancyErrorMessage(), Terraria.Social.Steam.SteamedWraps.SteamClient, and Terraria.ModLoader.ModLoader.TryGetMod().
Referenced by Terraria.ModLoader.UI.UIModSourceItem.UIModSourceItem(), and Terraria.ModLoader.UI.UIModSourceItem.PublishMod().