TModLoader: Terraria.ModLoader.UI.UIModSourceItem.BuildMod
BuildMod()
void Terraria.ModLoader.UI.UIModSourceItem.BuildMod (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 377 of file UIModSourceItem.cs.
    {
        SoundEngine.PlaySound(10);
        Interface.buildMod.Build(_mod, reload: false);
    }
References Terraria.ModLoader.UI.UIModSourceItem._mod, Terraria.ModLoader.UI.UIBuildMod.Build(), Terraria.ModLoader.UI.Interface.buildMod, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.ModLoader.UI.UIModSourceItem.UIModSourceItem().