TModLoader: Terraria.ModLoader.UI.UIModSourceItem.DrawSelf
DrawSelf()
override void Terraria.ModLoader.UI.UIModSourceItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.GameContent.UI.Elements.UIPanel.
    {
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        base.DrawSelf(spriteBatch);
        CalculatedStyle innerDimensions = GetInnerDimensions();
        Vector2 drawPos = default(Vector2);
        ((Vector2)(ref drawPos))._002Ector(innerDimensions.X + 5f, innerDimensions.Y + 30f);
        spriteBatch.Draw(_dividerTexture.Value, drawPos, (Rectangle?)null, Color.White, 0f, Vector2.Zero, new Vector2((innerDimensions.Width - 10f) / 8f, 1f), (SpriteEffects)0, 0f);
        if (_upgradePotentialChecked)
        {
            return;
        }
        _upgradePotentialChecked = true;
        string modFolderName = Path.GetFileName(_mod);
        string csprojFile = Path.Combine(_mod, modFolderName + ".csproj");
        bool projNeedsUpdate = false;
        if (!File.Exists(csprojFile) || Interface.createMod.CsprojUpdateNeeded(File.ReadAllText(csprojFile)))
        {
            Asset<Texture2D> icon2 = UICommon.ButtonExclamationTexture;
            UIHoverImage upgradeCSProjButton = new UIHoverImage(icon2, Language.GetTextValue("tModLoader.MSUpgradeCSProj"))
            {
                Left =
                {
                    Pixels = contextButtonsLeft,
                    Percent = 1f
                },
                Top =
                {
                    Pixels = 4f
                }
            };
            upgradeCSProjButton.OnLeftClick += delegate
            {
                File.WriteAllText(csprojFile, Interface.createMod.GetModCsproj(modFolderName));
                string text2 = Path.Combine(_mod, "Properties");
                string path = Path.Combine(text2, "AssemblyInfo.cs");
                if (File.Exists(path))
                {
                    File.Delete(path);
                }
                try
                {
                    string path2 = Path.Combine(_mod, "obj");
                    if (Directory.Exists(path2))
                    {
                        Directory.Delete(path2, recursive: true);
                    }
                    string path3 = Path.Combine(_mod, "bin");
                    if (Directory.Exists(path3))
                    {
                        Directory.Delete(path3, recursive: true);
                    }
                }
                catch (Exception)
                {
                }
                Directory.CreateDirectory(text2);
                File.WriteAllText(Path.Combine(text2, "launchSettings.json"), Interface.createMod.GetLaunchSettings());
                SoundEngine.PlaySound(in SoundID.MenuOpen);
                Main.menuMode = 10001;
                upgradeCSProjButton.Remove();
                _upgradePotentialChecked = false;
            };
            Append(upgradeCSProjButton);
            contextButtonsLeft -= 26;
            projNeedsUpdate = true;
        }
        string[] files = Directory.GetFiles(_mod, "*.lang", SearchOption.AllDirectories);
        if (files.Length != 0)
        {
            Asset<Texture2D> icon = UICommon.ButtonExclamationTexture;
            UIHoverImage upgradeLangFilesButton = new UIHoverImage(icon, Language.GetTextValue("tModLoader.MSUpgradeLangFiles"))
            {
                Left =
                {
                    Pixels = contextButtonsLeft,
                    Percent = 1f
                },
                Top =
                {
                    Pixels = 4f
                }
            };
            upgradeLangFilesButton.OnLeftClick += delegate
            {
                string[] array = files;
                for (int i = 0; i < array.Length; i++)
                {
                    LocalizationLoader.UpgradeLangFile(array[i], modName);
                }
                upgradeLangFilesButton.Remove();
            };
            Append(upgradeLangFilesButton);
            contextButtonsLeft -= 26;
        }
        if (Platform.IsWindows && !projNeedsUpdate)
        {
            UIHoverImage portModButton = new UIHoverImage(UICommon.ButtonExclamationTexture, Language.GetTextValue("tModLoader.MSPortToLatest"))
            {
                Left =
                {
                    Pixels = contextButtonsLeft,
                    Percent = 1f
                },
                Top =
                {
                    Pixels = 4f
                }
            };
            portModButton.OnLeftClick += delegate
            {
                string fileName = Path.GetFileName(_mod);
                string text = Path.Combine(_mod, fileName + ".csproj");
                string arguments = "\"" + text + "\"";
                string fileName2 = Path.Combine(Path.GetDirectoryName(Path.GetFileName(Assembly.GetExecutingAssembly().Location)), "tModPorter", "tModPorter.bat");
                Process.Start(new ProcessStartInfo
                {
                    FileName = fileName2,
                    Arguments = arguments,
                    UseShellExecute = true
                });
            };
            Append(portModButton);
            contextButtonsLeft -= 26;
        }
    }
References Terraria.ModLoader.UI.UIModSourceItem._dividerTexture, Terraria.ModLoader.UI.UIModSourceItem._mod, Terraria.ModLoader.UI.UIModSourceItem._upgradePotentialChecked, Terraria.UI.UIElement.Append(), Terraria.ModLoader.UI.UICommon.ButtonExclamationTexture, Terraria.ModLoader.UI.UIModSourceItem.contextButtonsLeft, Terraria.ModLoader.UI.Interface.createMod, Terraria.ModLoader.UI.UICreateMod.CsprojUpdateNeeded(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.ModLoader.UI.UICreateMod.GetLaunchSettings(), Terraria.ModLoader.UI.UICreateMod.GetModCsproj(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.Left, Terraria.ID.SoundID.MenuOpen, Terraria.ModLoader.UI.UIModSourceItem.modName, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.UIElement.Top, and Terraria.ModLoader.LocalizationLoader.UpgradeLangFile().