TModLoader: Terraria.Graphics.Capture.CaptureInterface.GetMapCoords
GetMapCoords()
static bool Terraria.Graphics.Capture.CaptureInterface.GetMapCoords (int PinX, int PinY, int Goal, out Point result) inline static private
Definition at line 1824 of file CaptureInterface.cs.
    {
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0405: Unknown result type (might be due to invalid IL or missing references)
        //IL_040a: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        if (!Main.mapFullscreen)
        {
            result = new Point(-1, -1);
            return false;
        }
        float num = 0f;
        float num9 = 0f;
        float num10 = 2f;
        _ = Main.maxTilesX / Main.textureMaxWidth;
        _ = Main.maxTilesY / Main.textureMaxHeight;
        float num11 = 10f;
        float num12 = 10f;
        float num13 = Main.maxTilesX - 10;
        float num14 = Main.maxTilesY - 10;
        num = 200f;
        num9 = 300f;
        num10 = Main.mapFullscreenScale;
        float num15 = (float)Main.screenWidth / (float)Main.maxTilesX * 0.8f;
        if (Main.mapFullscreenScale < num15)
        {
            Main.mapFullscreenScale = num15;
        }
        if (Main.mapFullscreenScale > 16f)
        {
            Main.mapFullscreenScale = 16f;
        }
        num10 = Main.mapFullscreenScale;
        if (Main.mapFullscreenPos.X < num11)
        {
            Main.mapFullscreenPos.X = num11;
        }
        if (Main.mapFullscreenPos.X > num13)
        {
            Main.mapFullscreenPos.X = num13;
        }
        if (Main.mapFullscreenPos.Y < num12)
        {
            Main.mapFullscreenPos.Y = num12;
        }
        if (Main.mapFullscreenPos.Y > num14)
        {
            Main.mapFullscreenPos.Y = num14;
        }
        float x = Main.mapFullscreenPos.X;
        float y = Main.mapFullscreenPos.Y;
        float num16 = x * num10;
        y *= num10;
        num = 0f - num16 + (float)(Main.screenWidth / 2);
        num9 = 0f - y + (float)(Main.screenHeight / 2);
        num += num11 * num10;
        num9 += num12 * num10;
        float num2 = Main.maxTilesX / 840;
        num2 *= Main.mapFullscreenScale;
        float num3 = num;
        float num4 = num9;
        float num5 = TextureAssets.Map.Width();
        float num6 = TextureAssets.Map.Height();
        if (Main.maxTilesX == 8400)
        {
            num2 *= 0.999f;
            num3 -= 40.6f * num2;
            num4 = num9 - 5f * num2;
            num5 -= 8.045f;
            num5 *= num2;
            num6 += 0.12f;
            num6 *= num2;
            if ((double)num2 < 1.2)
            {
                num6 += 1f;
            }
        }
        else if (Main.maxTilesX == 6400)
        {
            num2 *= 1.09f;
            num3 -= 38.8f * num2;
            num4 = num9 - 3.85f * num2;
            num5 -= 13.6f;
            num5 *= num2;
            num6 -= 6.92f;
            num6 *= num2;
            if ((double)num2 < 1.2)
            {
                num6 += 2f;
            }
        }
        else if (Main.maxTilesX == 6300)
        {
            num2 *= 1.09f;
            num3 -= 39.8f * num2;
            num4 = num9 - 4.08f * num2;
            num5 -= 26.69f;
            num5 *= num2;
            num6 -= 6.92f;
            num6 *= num2;
            if ((double)num2 < 1.2)
            {
                num6 += 2f;
            }
        }
        else if (Main.maxTilesX == 4200)
        {
            num2 *= 0.998f;
            num3 -= 37.3f * num2;
            num4 -= 1.7f * num2;
            num5 -= 16f;
            num5 *= num2;
            num6 -= 8.31f;
            num6 *= num2;
        }
        switch (Goal)
        {
        case 0:
        {
            int num7 = (int)((0f - num + (float)PinX) / num10 + num11);
            int num8 = (int)((0f - num9 + (float)PinY) / num10 + num12);
            bool flag = false;
            if ((float)num7 < num11)
            {
                flag = true;
            }
            if ((float)num7 >= num13)
            {
                flag = true;
            }
            if ((float)num8 < num12)
            {
                flag = true;
            }
            if ((float)num8 >= num14)
            {
                flag = true;
            }
            if (!flag)
            {
                result = new Point(num7, num8);
                return true;
            }
            result = new Point(-1, -1);
            return false;
        }
        case 1:
        {
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector(num, num9);
            Vector2 vector2 = new Vector2((float)PinX, (float)PinY) * num10 - new Vector2(10f * num10);
            result = (vector + vector2).ToPoint();
            return true;
        }
        default:
            result = new Point(-1, -1);
            return false;
        }
    }
References Terraria.GameContent.TextureAssets.Map, Terraria.Main.mapFullscreen, Terraria.Main.mapFullscreenPos, Terraria.Main.mapFullscreenScale, Terraria.Main.maxTilesX, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Main.textureMaxHeight, and Terraria.Main.textureMaxWidth.
Referenced by Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DragBounds(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawCursors(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawMarkedArea(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DrawMarkedArea(), and Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.EdgePlacement().