TModLoader: Terraria.Graphics.Capture.CaptureInterface.DrawCameraLock
DrawCameraLock()
void Terraria.Graphics.Capture.CaptureInterface.DrawCameraLock (SpriteBatch sb) inline private
Definition at line 2101 of file CaptureInterface.cs.
    {
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        //IL_014b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        if (CameraFrame == 0f)
        {
            return;
        }
        sb.Draw(TextureAssets.MagicPixel.Value, new Rectangle(0, 0, Main.screenWidth, Main.screenHeight), (Rectangle?)new Rectangle(0, 0, 1, 1), Color.Black * (CameraFrame / 5f));
        if (CameraFrame != 5f)
        {
            return;
        }
        float num = CameraWaiting - 60f + 5f;
        if (!(num <= 0f))
        {
            num /= 5f;
            float num2 = CaptureManager.Instance.GetProgress() * 100f;
            if (num2 > 100f)
            {
                num2 = 100f;
            }
            string text = num2.ToString("##") + " ";
            string text2 = "/ 100%";
            Vector2 vector = FontAssets.DeathText.Value.MeasureString(text);
            Vector2 vector2 = FontAssets.DeathText.Value.MeasureString(text2);
            Vector2 vector3 = default(Vector2);
            ((Vector2)(ref vector3))._002Ector(0f - vector.X, (0f - vector.Y) / 2f);
            Vector2 vector4 = default(Vector2);
            ((Vector2)(ref vector4))._002Ector(0f, (0f - vector2.Y) / 2f);
            ChatManager.DrawColorCodedStringWithShadow(sb, FontAssets.DeathText.Value, text, new Vector2((float)Main.screenWidth, (float)Main.screenHeight) / 2f + vector3, Color.White * num, 0f, Vector2.Zero, Vector2.One);
            ChatManager.DrawColorCodedStringWithShadow(sb, FontAssets.DeathText.Value, text2, new Vector2((float)Main.screenWidth, (float)Main.screenHeight) / 2f + vector4, Color.White * num, 0f, Vector2.Zero, Vector2.One);
        }
    }
References Terraria.Graphics.Capture.CaptureInterface.CameraFrame, Terraria.Graphics.Capture.CaptureInterface.CameraWaiting, Terraria.GameContent.FontAssets.DeathText, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Graphics.Capture.CaptureManager.GetProgress(), Terraria.Graphics.Capture.CaptureManager.Instance, Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.screenHeight, and Terraria.Main.screenWidth.
Referenced by Terraria.Graphics.Capture.CaptureInterface.Draw().