using System;
using Terraria.Localization;

namespace Terraria.ModLoader.Config;

[Obsolete("Labels are now automatically localized in localization files. Use LabelKeyAttribute to customize the key or use the autogenerated translation key instead. The functionality for showing this field or property in the ModConfig UI despite using [JsonIgnore] is now done through [ShowDespiteJsonIgnoreAttribute]")]
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Property | AttributeTargets.Field)]
public class LabelAttribute : Attribute
{
	private readonly string label;

	public string Label
	{
		get
		{
			if (!label.StartsWith("$"))
			{
				return label;
			}
			return Language.GetTextValue(label.Substring(1));
		}
	}

	public string LocalizationEntry
	{
		get
		{
			if (!label.StartsWith("$"))
			{
				return label;
			}
			return "{" + label + "}";
		}
	}

	public LabelAttribute(string label)
	{
		this.label = label;
	}
}
