TModLoader: Terraria.GameInput.LockOnHelper.SetUP
SetUP()
static void Terraria.GameInput.LockOnHelper.SetUP () inline static
    {
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        if (_canLockOn)
        {
            _ = AimedTarget;
            SetLockPosition(Main.ReverseGravitySupport(PredictedPosition - Main.screenPosition));
        }
    }
References Terraria.GameInput.LockOnHelper._canLockOn, Terraria.GameInput.LockOnHelper.AimedTarget, Terraria.GameInput.LockOnHelper.PredictedPosition, Terraria.Main.ReverseGravitySupport(), Terraria.Main.screenPosition, and Terraria.GameInput.LockOnHelper.SetLockPosition().
Referenced by Terraria.Main.DoUpdateInWorld(), and Terraria.Player.ItemCheckWrapped().