TModLoader: Terraria.GameInput.LockOnHelper.GetClosestTarget
GetClosestTarget()
static void Terraria.GameInput.LockOnHelper.GetClosestTarget (Vector2 position) inline static private
    {
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        _pickedTarget = -1;
        float num = -1f;
        if (UseMode == LockOnMode.ThreeDS)
        {
            Vector2 center = Main.player[Main.myPlayer].Center;
            Vector2 value = Main.player[Main.myPlayer].DirectionTo(Main.MouseWorld);
            for (int i = 0; i < _targets.Count; i++)
            {
                int num2 = _targets[i];
                NPC obj = Main.npc[num2];
                float num3 = Vector2.Dot(obj.DirectionFrom(center), value);
                if (ValidTarget(obj) && (_pickedTarget == -1 || !(num3 <= num)))
                {
                    _pickedTarget = i;
                    num = num3;
                }
            }
            return;
        }
        for (int j = 0; j < _targets.Count; j++)
        {
            int num4 = _targets[j];
            NPC nPC = Main.npc[num4];
            if (ValidTarget(nPC) && (_pickedTarget == -1 || !(nPC.Distance(position) >= num)))
            {
                _pickedTarget = j;
                num = nPC.Distance(position);
            }
        }
    }
References Terraria.GameInput.LockOnHelper._pickedTarget, Terraria.GameInput.LockOnHelper._targets, Terraria.Main.MouseWorld, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Main.player, Terraria.GameInput.LockOnHelper.UseMode, and Terraria.GameInput.LockOnHelper.ValidTarget().
Referenced by Terraria.GameInput.LockOnHelper.CycleTargetThreeDS(), Terraria.GameInput.LockOnHelper.FindMostViableTarget(), and Terraria.GameInput.LockOnHelper.SetActive().