TModLoader: Terraria.GameInput.LockOnHelper.Update
Update()
static void Terraria.GameInput.LockOnHelper.Update () inline static
Definition at line 150 of file LockOnHelper.cs.
    {
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0113: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0137: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        _canLockOn = false;
        if (!CanUseLockonSystem())
        {
            SetActive(on: false);
            return;
        }
        if (--_lifeTimeArrowDisplay < 0)
        {
            _lifeTimeArrowDisplay = 0;
        }
        FindMostViableTarget(LockOnMode.ThreeDS, ref _threeDSTarget);
        FindMostViableTarget(LockOnMode.TargetClosest, ref _targetClosestTarget);
        if (PlayerInput.Triggers.JustPressed.LockOn && !PlayerInput.WritingText)
        {
            _lifeTimeCounter = 40;
            _lifeTimeArrowDisplay = 30;
            HandlePressing();
        }
        if (!_enabled)
        {
            return;
        }
        if (UseMode == LockOnMode.FocusTarget && PlayerInput.Triggers.Current.LockOn)
        {
            if (_lifeTimeCounter <= 0)
            {
                SetActive(on: false);
                return;
            }
            _lifeTimeCounter--;
        }
        NPC aimedTarget = AimedTarget;
        if (!ValidTarget(aimedTarget))
        {
            SetActive(on: false);
        }
        if (UseMode == LockOnMode.TargetClosest)
        {
            SetActive(on: false);
            SetActive(CanEnable());
        }
        if (_enabled)
        {
            Player player = Main.player[Main.myPlayer];
            Vector2 predictedPosition = PredictedPosition;
            bool flag = false;
            if (ShouldLockOn(player) && (ItemID.Sets.LockOnIgnoresCollision[player.inventory[player.selectedItem].type] || Collision.CanHit(player.Center, 0, 0, predictedPosition, 0, 0) || Collision.CanHitLine(player.Center, 0, 0, predictedPosition, 0, 0) || Collision.CanHit(player.Center, 0, 0, aimedTarget.Center, 0, 0) || Collision.CanHitLine(player.Center, 0, 0, aimedTarget.Center, 0, 0)))
            {
                flag = true;
            }
            if (flag)
            {
                _canLockOn = true;
            }
        }
    }
References Terraria.GameInput.LockOnHelper._canLockOn, Terraria.GameInput.LockOnHelper._enabled, Terraria.GameInput.LockOnHelper._lifeTimeArrowDisplay, Terraria.GameInput.LockOnHelper._lifeTimeCounter, Terraria.GameInput.LockOnHelper._targetClosestTarget, Terraria.GameInput.LockOnHelper._threeDSTarget, Terraria.GameInput.LockOnHelper.AimedTarget, Terraria.GameInput.LockOnHelper.CanEnable(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.GameInput.LockOnHelper.CanUseLockonSystem(), Terraria.Entity.Center, Terraria.GameInput.LockOnHelper.FindMostViableTarget(), Terraria.GameInput.LockOnHelper.HandlePressing(), Terraria.Player.inventory, Terraria.ID.ItemID.Sets.LockOnIgnoresCollision, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.GameInput.LockOnHelper.PredictedPosition, Terraria.Player.selectedItem, Terraria.GameInput.LockOnHelper.SetActive(), Terraria.GameInput.LockOnHelper.ShouldLockOn(), Terraria.GameInput.PlayerInput.Triggers, Terraria.Item.type, Terraria.GameInput.LockOnHelper.UseMode, Terraria.GameInput.LockOnHelper.ValidTarget(), and Terraria.GameInput.PlayerInput.WritingText.
Referenced by Terraria.Player.Update().