TModLoader: Terraria.GameInput.LockOnHelper.Draw
Draw()
static void Terraria.GameInput.LockOnHelper.Draw (SpriteBatch spriteBatch) inline static
    {
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0264: Unknown result type (might be due to invalid IL or missing references)
        //IL_026b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_027a: Unknown result type (might be due to invalid IL or missing references)
        //IL_027f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0281: Unknown result type (might be due to invalid IL or missing references)
        //IL_0291: Unknown result type (might be due to invalid IL or missing references)
        //IL_0296: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_029c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0301: Unknown result type (might be due to invalid IL or missing references)
        //IL_0303: Unknown result type (might be due to invalid IL or missing references)
        //IL_0309: Unknown result type (might be due to invalid IL or missing references)
        //IL_030d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0314: Unknown result type (might be due to invalid IL or missing references)
        //IL_031e: Unknown result type (might be due to invalid IL or missing references)
        //IL_031f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0329: Unknown result type (might be due to invalid IL or missing references)
        //IL_0338: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0346: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_035d: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_046a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0474: Unknown result type (might be due to invalid IL or missing references)
        //IL_047a: Unknown result type (might be due to invalid IL or missing references)
        //IL_047c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0481: Unknown result type (might be due to invalid IL or missing references)
        //IL_0483: Unknown result type (might be due to invalid IL or missing references)
        //IL_0485: Unknown result type (might be due to invalid IL or missing references)
        //IL_0487: Unknown result type (might be due to invalid IL or missing references)
        //IL_048c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0491: Unknown result type (might be due to invalid IL or missing references)
        //IL_0496: Unknown result type (might be due to invalid IL or missing references)
        //IL_0498: Unknown result type (might be due to invalid IL or missing references)
        //IL_049f: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0434: Unknown result type (might be due to invalid IL or missing references)
        //IL_0436: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04db: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0503: Unknown result type (might be due to invalid IL or missing references)
        //IL_050a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0517: Unknown result type (might be due to invalid IL or missing references)
        //IL_0521: Unknown result type (might be due to invalid IL or missing references)
        //IL_0533: Unknown result type (might be due to invalid IL or missing references)
        //IL_0535: Unknown result type (might be due to invalid IL or missing references)
        //IL_053b: Unknown result type (might be due to invalid IL or missing references)
        //IL_053f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0546: Unknown result type (might be due to invalid IL or missing references)
        //IL_054d: Unknown result type (might be due to invalid IL or missing references)
        //IL_054e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0558: Unknown result type (might be due to invalid IL or missing references)
        //IL_0567: Unknown result type (might be due to invalid IL or missing references)
        //IL_056e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0575: Unknown result type (might be due to invalid IL or missing references)
        //IL_0582: Unknown result type (might be due to invalid IL or missing references)
        //IL_058c: Unknown result type (might be due to invalid IL or missing references)
        if (Main.gameMenu)
        {
            return;
        }
        Texture2D value = TextureAssets.LockOnCursor.Value;
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector(0, 0, value.Width, 12);
        Rectangle rectangle2 = default(Rectangle);
        ((Rectangle)(ref rectangle2))._002Ector(0, 16, value.Width, 12);
        Color t = Main.OurFavoriteColor.MultiplyRGBA(new Color(0.75f, 0.75f, 0.75f, 1f));
        ((Color)(ref t)).A = 220;
        Color t2 = Main.OurFavoriteColor;
        ((Color)(ref t2)).A = 220;
        float num = 0.94f + (float)Math.Sin(Main.GlobalTimeWrappedHourly * ((float)Math.PI * 2f)) * 0.06f;
        t2 *= num;
        t *= num;
        Utils.Swap(ref t, ref t2);
        Color color = t.MultiplyRGBA(new Color(0.8f, 0.8f, 0.8f, 0.8f));
        Color color2 = t.MultiplyRGBA(new Color(0.8f, 0.8f, 0.8f, 0.8f));
        float gravDir = Main.player[Main.myPlayer].gravDir;
        float num7 = 1f;
        float num8 = 0.1f;
        float num9 = 0.8f;
        float num10 = 1f;
        float num11 = 10f;
        float num12 = 10f;
        bool flag = false;
        for (int i = 0; i < _drawProgress.GetLength(0); i++)
        {
            int num13 = 0;
            if (_pickedTarget != -1 && _targets.Count > 0 && i == _targets[_pickedTarget])
            {
                num13 = 2;
            }
            else if ((flag && _targets.Contains(i)) || (UseMode == LockOnMode.ThreeDS && _threeDSTarget == i) || (UseMode == LockOnMode.TargetClosest && _targetClosestTarget == i))
            {
                num13 = 1;
            }
            _drawProgress[i, 0] = MathHelper.Clamp(_drawProgress[i, 0] + ((num13 == 1) ? num8 : (0f - num8)), 0f, 1f);
            _drawProgress[i, 1] = MathHelper.Clamp(_drawProgress[i, 1] + ((num13 == 2) ? num8 : (0f - num8)), 0f, 1f);
            float num14 = _drawProgress[i, 0];
            if (num14 > 0f)
            {
                float num2 = 1f - num14 * num14;
                Vector2 pos = Main.npc[i].Top + new Vector2(0f, 0f - num12 - num2 * num11) * gravDir - Main.screenPosition;
                pos = Main.ReverseGravitySupport(pos, (float)Main.npc[i].height);
                spriteBatch.Draw(value, pos, (Rectangle?)rectangle, color * num14, 0f, rectangle.Size() / 2f, new Vector2(0.58f, 1f) * num7 * num9 * (1f + num14) / 2f, (SpriteEffects)0, 0f);
                spriteBatch.Draw(value, pos, (Rectangle?)rectangle2, color2 * num14 * num14, 0f, rectangle2.Size() / 2f, new Vector2(0.58f, 1f) * num7 * num9 * (1f + num14) / 2f, (SpriteEffects)0, 0f);
            }
            float num3 = _drawProgress[i, 1];
            if (num3 > 0f)
            {
                int num4 = Main.npc[i].width;
                if (Main.npc[i].height > num4)
                {
                    num4 = Main.npc[i].height;
                }
                num4 += 20;
                if ((float)num4 < 70f)
                {
                    num10 *= (float)num4 / 70f;
                }
                float num5 = 3f;
                Vector2 vector = Main.npc[i].Center;
                if (_targets.Count >= 0 && _pickedTarget >= 0 && _pickedTarget < _targets.Count && i == _targets[_pickedTarget] && NPC.GetNPCLocation(i, seekHead: true, averageDirection: false, out var _, out var pos2))
                {
                    vector = pos2;
                }
                for (int j = 0; (float)j < num5; j++)
                {
                    float num6 = (float)Math.PI * 2f / num5 * (float)j + Main.GlobalTimeWrappedHourly * ((float)Math.PI * 2f) * 0.25f;
                    Vector2 vector2 = Utils.RotatedBy(new Vector2(0f, (float)(num4 / 2)), num6);
                    Vector2 pos3 = vector + vector2 - Main.screenPosition;
                    pos3 = Main.ReverseGravitySupport(pos3);
                    float rotation = num6 * (float)((gravDir == 1f) ? 1 : (-1)) + (float)Math.PI * (float)((gravDir == 1f) ? 1 : 0);
                    spriteBatch.Draw(value, pos3, (Rectangle?)rectangle, t * num3, rotation, rectangle.Size() / 2f, new Vector2(0.58f, 1f) * num7 * num10 * (1f + num3) / 2f, (SpriteEffects)0, 0f);
                    spriteBatch.Draw(value, pos3, (Rectangle?)rectangle2, t2 * num3 * num3, rotation, rectangle2.Size() / 2f, new Vector2(0.58f, 1f) * num7 * num10 * (1f + num3) / 2f, (SpriteEffects)0, 0f);
                }
            }
        }
    }
References Terraria.GameInput.LockOnHelper._drawProgress, Terraria.GameInput.LockOnHelper._pickedTarget, Terraria.GameInput.LockOnHelper._targetClosestTarget, Terraria.GameInput.LockOnHelper._targets, Terraria.GameInput.LockOnHelper._threeDSTarget, Terraria.Main.gameMenu, Terraria.NPC.GetNPCLocation(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.TextureAssets.LockOnCursor, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.Main.ReverseGravitySupport(), Terraria.Utils.RotatedBy(), Terraria.Main.screenPosition, and Terraria.GameInput.LockOnHelper.UseMode.
Referenced by Terraria.Main.DrawInterface_5_GamepadLockOn().