TModLoader: Terraria.GameInput.LockOnHelper.RefreshTargets
RefreshTargets()
static void Terraria.GameInput.LockOnHelper.RefreshTargets (Vector2 position, float radius) inline static private
Definition at line 388 of file LockOnHelper.cs.
    {
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        _targets.Clear();
        Rectangle rectangle = Utils.CenteredRectangle(Main.player[Main.myPlayer].Center, new Vector2(1920f, 1200f));
        _ = Main.player[Main.myPlayer].Center;
        Main.player[Main.myPlayer].DirectionTo(Main.MouseWorld);
        for (int i = 0; i < Main.npc.Length; i++)
        {
            NPC nPC = Main.npc[i];
            if (ValidTarget(nPC) && !(nPC.Distance(position) > radius) && ((Rectangle)(ref rectangle)).Intersects(nPC.Hitbox))
            {
                Vector3 subLight = Lighting.GetSubLight(nPC.Center);
                if (!(((Vector3)(ref subLight)).Length() / 3f < 0.03f))
                {
                    _targets.Add(i);
                }
            }
        }
    }
References Terraria.GameInput.LockOnHelper._targets, Terraria.Utils.CenteredRectangle(), Terraria.Lighting.GetSubLight(), Terraria.Main.MouseWorld, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Main.player, and Terraria.GameInput.LockOnHelper.ValidTarget().
Referenced by Terraria.GameInput.LockOnHelper.CycleTargetFocus(), Terraria.GameInput.LockOnHelper.CycleTargetThreeDS(), Terraria.GameInput.LockOnHelper.FindMostViableTarget(), and Terraria.GameInput.LockOnHelper.SetActive().