TModLoader: Terraria.ModLoader.ModItem.SetupContent
SetupContent()
override void Terraria.ModLoader.ModItem.SetupContent () inline sealed virtual inherited
If you make a new ModType, seal this override, and call M:Terraria.ModLoader.ModType.SetStaticDefaults in it.
Reimplemented from Terraria.ModLoader.ModType< Item, ModItem >.
    {
        ItemLoader.SetDefaults(Item, createModItem: false);
        AutoStaticDefaults();
        SetStaticDefaults();
        ItemID.Search.Add(base.FullName, Type);
    }
References Terraria.ModLoader.ModItem.AutoStaticDefaults(), Terraria.ID.ItemID.Search, Terraria.ModLoader.ItemLoader.SetDefaults(), Terraria.ModLoader.ModType< Item, ModItem >.SetStaticDefaults(), and Terraria.ModLoader.ModItem.Type.