TModLoader: Terraria.Graphics.LightDiscDrawer.Draw
Draw()
void Terraria.Graphics.LightDiscDrawer.Draw (Projectile proj) inline
    {
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        MiscShaderData miscShaderData = GameShaders.Misc["LightDisc"];
        miscShaderData.UseSaturation(-2.8f);
        miscShaderData.UseOpacity(2f);
        miscShaderData.Apply();
        _vertexStrip.PrepareStripWithProceduralPadding(proj.oldPos, proj.oldRot, StripColors, StripWidth, -Main.screenPosition + proj.Size / 2f);
        _vertexStrip.DrawTrail();
        Main.pixelShader.CurrentTechnique.Passes[0].Apply();
    }
References Terraria.Graphics.LightDiscDrawer._vertexStrip, Terraria.Graphics.VertexStrip.DrawTrail(), Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.Main.pixelShader, Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding(), Terraria.Main.screenPosition, Terraria.Graphics.LightDiscDrawer.StripColors(), and Terraria.Graphics.LightDiscDrawer.StripWidth().