TModLoader: Terraria.ModLoader.FartInAJarJump.OnStarted
OnStarted()
override void Terraria.ModLoader.FartInAJarJump.OnStarted (Player player, ref bool playSound) inline virtual
This hook runs when the player uses this jump via pressing the jump key
Effects that should appear when the jump starts can be spawned here.
For example, the Cloud in a Bottle's initial puff of smoke is spawned here.
To make the jump re-usable, set P:Terraria.DataStructures.ExtraJumpState.Available to true
Parameters
player The player performing the jump
playSound Whether the poof sound should play. Set this parameter to false if you want to play a different sound.
Reimplemented from Terraria.ModLoader.ExtraJump.
    {
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0158: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_023c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_0328: Unknown result type (might be due to invalid IL or missing references)
        //IL_034f: Unknown result type (might be due to invalid IL or missing references)
        int num7 = player.height;
        if (player.gravDir == -1f)
        {
            num7 = 0;
        }
        playSound = false;
        SoundEngine.PlaySound(in SoundID.Item16, player.position);
        for (int i = 0; i < 10; i++)
        {
            int num8 = Dust.NewDust(new Vector2(player.position.X - 34f, player.position.Y + (float)num7 - 16f), 102, 32, 188, (0f - player.velocity.X) * 0.5f, player.velocity.Y * 0.5f, 100, default(Color), 1.5f);
            Main.dust[num8].velocity.X = Main.dust[num8].velocity.X * 0.5f - player.velocity.X * 0.1f;
            Main.dust[num8].velocity.Y = Main.dust[num8].velocity.Y * 0.5f - player.velocity.Y * 0.3f;
        }
        int num9 = Gore.NewGore(new Vector2(player.position.X + (float)(player.width / 2) - 16f, player.position.Y + (float)num7 - 16f), new Vector2(0f - player.velocity.X, 0f - player.velocity.Y), Main.rand.Next(435, 438));
        Main.gore[num9].velocity.X = Main.gore[num9].velocity.X * 0.1f - player.velocity.X * 0.1f;
        Main.gore[num9].velocity.Y = Main.gore[num9].velocity.Y * 0.1f - player.velocity.Y * 0.05f;
        num9 = Gore.NewGore(new Vector2(player.position.X - 36f, player.position.Y + (float)num7 - 16f), new Vector2(0f - player.velocity.X, 0f - player.velocity.Y), Main.rand.Next(435, 438));
        Main.gore[num9].velocity.X = Main.gore[num9].velocity.X * 0.1f - player.velocity.X * 0.1f;
        Main.gore[num9].velocity.Y = Main.gore[num9].velocity.Y * 0.1f - player.velocity.Y * 0.05f;
        num9 = Gore.NewGore(new Vector2(player.position.X + (float)player.width + 4f, player.position.Y + (float)num7 - 16f), new Vector2(0f - player.velocity.X, 0f - player.velocity.Y), Main.rand.Next(435, 438));
        Main.gore[num9].velocity.X = Main.gore[num9].velocity.X * 0.1f - player.velocity.X * 0.1f;
        Main.gore[num9].velocity.Y = Main.gore[num9].velocity.Y * 0.1f - player.velocity.Y * 0.05f;
    }
References Terraria.Main.dust, Terraria.Main.gore, Terraria.Player.gravDir, Terraria.Entity.height, Terraria.ID.SoundID.Item16, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Gore.velocity, and Terraria.Entity.width.