TModLoader: Terraria.ModLoader.SystemLoader.HookList.Enumerate
Enumerate()
ReadOnlySpan< ModSystem > Terraria.ModLoader.SystemLoader.HookList.Enumerate () inline
Definition at line 35 of file SystemLoader.cs.
        {
            return arr;
        }
References Terraria.ModLoader.SystemLoader.HookList.arr.
Referenced by Terraria.ModLoader.SystemLoader.CanWorldBePlayed(), Terraria.ModLoader.SystemLoader.ClearWorld(), Terraria.ModLoader.SystemLoader.HijackGetData(), Terraria.ModLoader.SystemLoader.HijackSendData(), Terraria.ModLoader.SystemLoader.ModifyGameTipVisibility(), Terraria.ModLoader.SystemLoader.ModifyHardmodeTasks(), Terraria.ModLoader.SystemLoader.ModifyInterfaceLayers(), Terraria.ModLoader.SystemLoader.ModifyLightingBrightness(), Terraria.ModLoader.SystemLoader.ModifyScreenPosition(), Terraria.ModLoader.SystemLoader.ModifySunLightColor(), Terraria.ModLoader.SystemLoader.ModifyTimeRate(), Terraria.ModLoader.SystemLoader.ModifyTransformMatrix(), Terraria.ModLoader.SystemLoader.ModifyWorldGenTasks(), Terraria.ModLoader.SystemLoader.OnLocalizationsLoaded(), Terraria.ModLoader.SystemLoader.OnWorldLoad(), Terraria.ModLoader.SystemLoader.OnWorldUnload(), Terraria.ModLoader.SystemLoader.PostDrawFullscreenMap(), Terraria.ModLoader.SystemLoader.PostDrawInterface(), Terraria.ModLoader.SystemLoader.PostDrawTiles(), Terraria.ModLoader.SystemLoader.PostUpdateDusts(), Terraria.ModLoader.SystemLoader.PostUpdateEverything(), Terraria.ModLoader.SystemLoader.PostUpdateGores(), Terraria.ModLoader.SystemLoader.PostUpdateInput(), Terraria.ModLoader.SystemLoader.PostUpdateInvasions(), Terraria.ModLoader.SystemLoader.PostUpdateItems(), Terraria.ModLoader.SystemLoader.PostUpdateNPCs(), Terraria.ModLoader.SystemLoader.PostUpdatePlayers(), Terraria.ModLoader.SystemLoader.PostUpdateProjectiles(), Terraria.ModLoader.SystemLoader.PostUpdateTime(), Terraria.ModLoader.SystemLoader.PostUpdateWorld(), Terraria.ModLoader.SystemLoader.PostWorldGen(), Terraria.ModLoader.SystemLoader.PreDrawMapIconOverlay(), Terraria.ModLoader.SystemLoader.PreSaveAndQuit(), Terraria.ModLoader.SystemLoader.PreUpdateDusts(), Terraria.ModLoader.SystemLoader.PreUpdateEntities(), Terraria.ModLoader.SystemLoader.PreUpdateGores(), Terraria.ModLoader.SystemLoader.PreUpdateInvasions(), Terraria.ModLoader.SystemLoader.PreUpdateItems(), Terraria.ModLoader.SystemLoader.PreUpdateNPCs(), Terraria.ModLoader.SystemLoader.PreUpdatePlayers(), Terraria.ModLoader.SystemLoader.PreUpdateProjectiles(), Terraria.ModLoader.SystemLoader.PreUpdateTime(), Terraria.ModLoader.SystemLoader.PreUpdateWorld(), Terraria.ModLoader.SystemLoader.PreWorldGen(), Terraria.ModLoader.IO.WorldIO.ReceiveModData(), Terraria.ModLoader.SystemLoader.ResetNearbyTileEffects(), Terraria.ModLoader.IO.WorldIO.SendModData(), Terraria.ModLoader.SystemLoader.TileCountsAvailable(), and Terraria.ModLoader.SystemLoader.UpdateUI().