TModLoader: Terraria.GameContent.PortalHelper.SupportedTilesAreFine
SupportedTilesAreFine()
static bool Terraria.GameContent.PortalHelper.SupportedTilesAreFine (Vector2 portalCenter, float portalAngle) inline static
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0158: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        Point point = portalCenter.ToTileCoordinates();
        int num = (int)Math.Round(MathHelper.WrapAngle(portalAngle) / ((float)Math.PI / 4f));
        int num7;
        int num2;
        int num3;
        int num6;
        int num5;
        switch (num)
        {
        case 2:
            num7 = -1;
            goto IL_004e;
        case -2:
            num7 = 1;
            goto IL_004e;
        case 0:
        case 4:
            num2 = 0;
            num3 = ((num == 0) ? 1 : (-1));
            break;
        case 3:
            num6 = -1;
            goto IL_0068;
        case -3:
            num6 = 1;
            goto IL_0068;
        case 1:
            num5 = -1;
            goto IL_0075;
        case -1:
            num5 = 1;
            goto IL_0075;
        default:
            {
                Main.NewText("Broken portal! (over4s = " + num + " , " + portalAngle + ")");
                return false;
            }
            IL_0075:
            num2 = num5;
            num3 = 1;
            break;
            IL_0068:
            num2 = num6;
            num3 = -1;
            break;
            IL_004e:
            num2 = num7;
            num3 = 0;
            break;
        }
        if (num2 != 0 && num3 != 0)
        {
            int num4 = 3;
            if (num2 == -1 && num3 == 1)
            {
                num4 = 5;
            }
            if (num2 == 1 && num3 == -1)
            {
                num4 = 2;
            }
            if (num2 == 1 && num3 == 1)
            {
                num4 = 4;
            }
            num4--;
            if (SupportedSlope(point.X, point.Y, num4) && SupportedSlope(point.X + num2, point.Y - num3, num4))
            {
                return SupportedSlope(point.X - num2, point.Y + num3, num4);
            }
            return false;
        }
        if (num2 != 0)
        {
            if (num2 == 1)
            {
                point.X--;
            }
            if (SupportedNormal(point.X, point.Y) && SupportedNormal(point.X, point.Y - 1))
            {
                return SupportedNormal(point.X, point.Y + 1);
            }
            return false;
        }
        if (num3 != 0)
        {
            if (num3 == 1)
            {
                point.Y--;
            }
            if (!SupportedNormal(point.X, point.Y) || !SupportedNormal(point.X + 1, point.Y) || !SupportedNormal(point.X - 1, point.Y))
            {
                if (SupportedHalfbrick(point.X, point.Y) && SupportedHalfbrick(point.X + 1, point.Y))
                {
                    return SupportedHalfbrick(point.X - 1, point.Y);
                }
                return false;
            }
            return true;
        }
        return true;
    }
References Terraria.Main.NewText(), Terraria.GameContent.PortalHelper.SupportedHalfbrick(), Terraria.GameContent.PortalHelper.SupportedNormal(), and Terraria.GameContent.PortalHelper.SupportedSlope().
Referenced by Terraria.GameContent.PortalHelper.AddPortal().