TModLoader: Terraria.GameContent.PortalHelper.TryPlacingPortal
TryPlacingPortal()
static int Terraria.GameContent.PortalHelper.TryPlacingPortal (Projectile theBolt, Vector2 velocity, Vector2 theCrashVelocity) inline static
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0212: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_021b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = velocity / ((Vector2)(ref velocity)).Length();
        Point position = FindCollision(theBolt.position, theBolt.position + velocity + vector * 32f).ToTileCoordinates();
        Tile tile = Main.tile[position.X, position.Y];
        Vector2 vector2 = default(Vector2);
        ((Vector2)(ref vector2))._002Ector((float)(position.X * 16 + 8), (float)(position.Y * 16 + 8));
        if (!WorldGen.SolidOrSlopedTile(tile))
        {
            return -1;
        }
        int num = tile.slope();
        bool flag = tile.halfBrick();
        for (int i = 0; i < (flag ? 2 : EDGES.Length); i++)
        {
            if (Vector2.Dot(EDGES[i], vector) > 0f && FindValidLine(position, (int)EDGES[i].Y, (int)(0f - EDGES[i].X), out var bestPosition))
            {
                ((Vector2)(ref vector2))._002Ector((float)(bestPosition.X * 16 + 8), (float)(bestPosition.Y * 16 + 8));
                return AddPortal(theBolt, vector2 - EDGES[i] * (flag ? 0f : 8f), (float)Math.Atan2(EDGES[i].Y, EDGES[i].X) + (float)Math.PI / 2f, (int)theBolt.ai[0], theBolt.direction);
            }
        }
        if (num != 0)
        {
            Vector2 value = SLOPE_EDGES[num - 1];
            if (Vector2.Dot(value, -vector) > 0f && FindValidLine(position, -SLOPE_OFFSETS[num - 1].Y, SLOPE_OFFSETS[num - 1].X, out var bestPosition2))
            {
                ((Vector2)(ref vector2))._002Ector((float)(bestPosition2.X * 16 + 8), (float)(bestPosition2.Y * 16 + 8));
                return AddPortal(theBolt, vector2, (float)Math.Atan2(value.Y, value.X) - (float)Math.PI / 2f, (int)theBolt.ai[0], theBolt.direction);
            }
        }
        return -1;
    }
References Terraria.GameContent.PortalHelper.AddPortal(), Terraria.GameContent.PortalHelper.EDGES, Terraria.GameContent.PortalHelper.FindCollision(), Terraria.GameContent.PortalHelper.FindValidLine(), Terraria.Tile.halfBrick(), Terraria.Tile.slope(), Terraria.GameContent.PortalHelper.SLOPE_EDGES, Terraria.GameContent.PortalHelper.SLOPE_OFFSETS, Terraria.WorldGen.SolidOrSlopedTile(), and Terraria.Main.tile.
Referenced by Terraria.Projectile.HandleMovement().