TModLoader: Terraria.GameContent.PortalHelper.AddPortal
AddPortal()
static int Terraria.GameContent.PortalHelper.AddPortal (Projectile sourceProjectile, Vector2 position, float angle, int form, int direction) inline static private
Definition at line 499 of file PortalHelper.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        if (!SupportedTilesAreFine(position, angle))
        {
            return -1;
        }
        RemoveMyOldPortal(form);
        RemoveIntersectingPortals(position, angle);
        int num = Projectile.NewProjectile(Entity.InheritSource(sourceProjectile), position.X, position.Y, 0f, 0f, 602, 0, 0f, Main.myPlayer, angle, form);
        Main.projectile[num].direction = direction;
        Main.projectile[num].netUpdate = true;
        return num;
    }
References Terraria.Entity.direction, Terraria.Entity.InheritSource(), Terraria.Main.myPlayer, Terraria.Projectile.netUpdate, Terraria.Projectile.NewProjectile(), Terraria.Main.projectile, Terraria.GameContent.PortalHelper.RemoveIntersectingPortals(), Terraria.GameContent.PortalHelper.RemoveMyOldPortal(), and Terraria.GameContent.PortalHelper.SupportedTilesAreFine().
Referenced by Terraria.GameContent.PortalHelper.TryPlacingPortal().