TModLoader: Terraria.GameContent.PortalHelper.TryGoingThroughPortals
TryGoingThroughPortals()
static void Terraria.GameContent.PortalHelper.TryGoingThroughPortals (Entity ent) inline static
Definition at line 124 of file PortalHelper.cs.
    {
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_0140: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_0164: Unknown result type (might be due to invalid IL or missing references)
        //IL_0169: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_019d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0206: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0217: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_022f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_0236: Unknown result type (might be due to invalid IL or missing references)
        //IL_023d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0242: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_0268: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0290: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_030c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0311: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_041f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_043d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0444: Unknown result type (might be due to invalid IL or missing references)
        if (!anyPortalAtAll)
        {
            return;
        }
        float collisionPoint = 0f;
        _ = ent.velocity;
        int width = ent.width;
        int height = ent.height;
        int num = 1;
        if (ent is Player)
        {
            num = (int)((Player)ent).gravDir;
        }
        for (int i = 0; i < FoundPortals.GetLength(0); i++)
        {
            if (FoundPortals[i, 0] == -1 || FoundPortals[i, 1] == -1 || (ent is Player && (i >= PortalCooldownForPlayers.Length || PortalCooldownForPlayers[i] > 0)) || (ent is NPC && (i >= PortalCooldownForNPCs.Length || PortalCooldownForNPCs[i] > 0)))
            {
                continue;
            }
            for (int j = 0; j < 2; j++)
            {
                Projectile projectile = Main.projectile[FoundPortals[i, j]];
                GetPortalEdges(projectile.Center, projectile.ai[0], out var start, out var end);
                if (!Collision.CheckAABBvLineCollision(ent.position + ent.velocity, ent.Size, start, end, 2f, ref collisionPoint))
                {
                    continue;
                }
                Projectile projectile2 = Main.projectile[FoundPortals[i, 1 - j]];
                float num2 = ent.Hitbox.Distance(projectile.Center);
                int bonusX;
                int bonusY;
                Vector2 vector = GetPortalOutingPoint(ent.Size, projectile2.Center, projectile2.ai[0], out bonusX, out bonusY) + Vector2.Normalize(new Vector2((float)bonusX, (float)bonusY)) * num2;
                Vector2 vector2 = Vector2.UnitX * 16f;
                if (Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: true, fall2: true, num) != vector2)
                {
                    continue;
                }
                vector2 = -Vector2.UnitX * 16f;
                if (Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: true, fall2: true, num) != vector2)
                {
                    continue;
                }
                vector2 = Vector2.UnitY * 16f;
                if (Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: true, fall2: true, num) != vector2)
                {
                    continue;
                }
                vector2 = -Vector2.UnitY * 16f;
                if (Collision.TileCollision(vector - vector2, vector2, width, height, fallThrough: true, fall2: true, num) != vector2)
                {
                    continue;
                }
                float num3 = 0.1f;
                if (bonusY == -num)
                {
                    num3 = 0.1f;
                }
                if (ent.velocity == Vector2.Zero)
                {
                    ent.velocity = (projectile.ai[0] - (float)Math.PI / 2f).ToRotationVector2() * num3;
                }
                if (((Vector2)(ref ent.velocity)).Length() < num3)
                {
                    ((Vector2)(ref ent.velocity)).Normalize();
                    ent.velocity *= num3;
                }
                Vector2 vector3 = Vector2.Normalize(new Vector2((float)bonusX, (float)bonusY));
                if (vector3.HasNaNs() || vector3 == Vector2.Zero)
                {
                    vector3 = Vector2.UnitX * (float)ent.direction;
                }
                ent.velocity = vector3 * ((Vector2)(ref ent.velocity)).Length();
                if ((bonusY == -num && Math.Sign(ent.velocity.Y) != -num) || Math.Abs(ent.velocity.Y) < 0.1f)
                {
                    ent.velocity.Y = (float)(-num) * 0.1f;
                }
                int num4 = (int)((float)(projectile2.owner * 2) + projectile2.ai[1]);
                int lastPortalColorIndex = num4 + ((num4 % 2 == 0) ? 1 : (-1));
                if (ent is Player)
                {
                    Player player = (Player)ent;
                    player.lastPortalColorIndex = lastPortalColorIndex;
                    player.Teleport(vector, 4, num4);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(96, -1, -1, null, player.whoAmI, vector.X, vector.Y, num4);
                        NetMessage.SendData(13, -1, -1, null, player.whoAmI);
                    }
                    PortalCooldownForPlayers[i] = 10;
                }
                else if (ent is NPC)
                {
                    NPC nPC = (NPC)ent;
                    nPC.lastPortalColorIndex = lastPortalColorIndex;
                    nPC.Teleport(vector, 4, num4);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(100, -1, -1, null, nPC.whoAmI, vector.X, vector.Y, num4);
                        NetMessage.SendData(23, -1, -1, null, nPC.whoAmI);
                    }
                    PortalCooldownForPlayers[i] = 10;
                    if (bonusY == -1 && ent.velocity.Y > -3f)
                    {
                        ent.velocity.Y = -3f;
                    }
                }
                return;
            }
        }
    }
References Terraria.Projectile.ai, Terraria.GameContent.PortalHelper.anyPortalAtAll, Terraria.Entity.Center, Terraria.Collision.CheckAABBvLineCollision(), Terraria.GameContent.PortalHelper.FoundPortals, Terraria.GameContent.PortalHelper.GetPortalEdges(), Terraria.GameContent.PortalHelper.GetPortalOutingPoint(), Terraria.Main.netMode, Terraria.GameContent.PortalHelper.PortalCooldownForNPCs, Terraria.GameContent.PortalHelper.PortalCooldownForPlayers, Terraria.Main.projectile, Terraria.NetMessage.SendData(), Terraria.Player.Teleport(), Terraria.Collision.TileCollision(), and Terraria.Entity.whoAmI.
Referenced by Terraria.NPC.TryPortalJumping(), and Terraria.Player.TryPortalJumping().