TModLoader: Terraria.ModLoader.BuffLoader.GetBuff
GetBuff()
static ModBuff Terraria.ModLoader.BuffLoader.GetBuff (int type) inline static
Gets the ModBuff instance with the given type. If no ModBuff with the given type exists, returns null.
    {
        if (type < BuffID.Count || type >= BuffCount)
        {
            return null;
        }
        return buffs[type - BuffID.Count];
    }
References Terraria.ModLoader.BuffLoader.BuffCount, Terraria.ModLoader.BuffLoader.buffs, and Terraria.ID.BuffID.Count.
Referenced by Terraria.ModLoader.ModContent.GetModBuff(), Terraria.ModLoader.Config.UI.BuffDefinitionElement.GetPassedOptionElements(), Terraria.ModLoader.BuffLoader.ModifyBuffText(), Terraria.ModLoader.BuffLoader.PostDraw(), Terraria.ModLoader.BuffLoader.PreDraw(), Terraria.ModLoader.BuffLoader.ReApply(), Terraria.ModLoader.BuffLoader.ReApply(), Terraria.ModLoader.BuffLoader.RightClick(), Terraria.ModLoader.IO.PlayerIO.SaveModBuffs(), Terraria.ModLoader.BuffLoader.Update(), and Terraria.ModLoader.BuffLoader.Update().