TModLoader: Terraria.ModLoader.BuffLoader.ReApply
ReApply() [2/2]
static bool Terraria.ModLoader.BuffLoader.ReApply (int buff, Player player, int time, int buffIndex) inline static
Definition at line 176 of file BuffLoader.cs.
    {
        Func<int, Player, int, int, bool>[] hookReApplyPlayer = HookReApplyPlayer;
        for (int i = 0; i < hookReApplyPlayer.Length; i++)
        {
            if (hookReApplyPlayer[i](buff, player, time, buffIndex))
            {
                return true;
            }
        }
        if (IsModBuff(buff))
        {
            return GetBuff(buff).ReApply(player, time, buffIndex);
        }
        return false;
    }
References Terraria.ModLoader.BuffLoader.GetBuff(), Terraria.ModLoader.BuffLoader.HookReApplyPlayer, Terraria.ModLoader.BuffLoader.IsModBuff(), and Terraria.ModLoader.ModBuff.ReApply().
Referenced by Terraria.NPC.AddBuff(), and Terraria.Player.AddBuff_TryUpdatingExistingBuffTime().