TModLoader: Terraria.ModLoader.BuffLoader.ResizeArrays
ResizeArrays()
static void Terraria.ModLoader.BuffLoader.ResizeArrays () inline static package
Definition at line 84 of file BuffLoader.cs.
    {
        Array.Resize(ref TextureAssets.Buff, nextBuff);
        LoaderUtils.ResetStaticMembers(typeof(BuffID));
        Array.Resize(ref Main.pvpBuff, nextBuff);
        Array.Resize(ref Main.persistentBuff, nextBuff);
        Array.Resize(ref Main.vanityPet, nextBuff);
        Array.Resize(ref Main.lightPet, nextBuff);
        Array.Resize(ref Main.meleeBuff, nextBuff);
        Array.Resize(ref Main.debuff, nextBuff);
        Array.Resize(ref Main.buffNoSave, nextBuff);
        Array.Resize(ref Main.buffNoTimeDisplay, nextBuff);
        Array.Resize(ref Main.buffDoubleApply, nextBuff);
        Array.Resize(ref Main.buffAlpha, nextBuff);
        Array.Resize(ref Lang._buffNameCache, nextBuff);
        Array.Resize(ref Lang._buffDescriptionCache, nextBuff);
        for (int i = BuffID.Count; i < nextBuff; i++)
        {
            Lang._buffNameCache[i] = LocalizedText.Empty;
            Lang._buffDescriptionCache[i] = LocalizedText.Empty;
        }
        extraPlayerBuffCount = (ModLoader.Mods.Any() ? ModLoader.Mods.Max((Mod m) => (int)m.ExtraPlayerBuffSlots) : 0);
        ModLoader.BuildGlobalHook<GlobalBuff, DelegateUpdatePlayer>(ref HookUpdatePlayer, globalBuffs, (GlobalBuff g) => g.Update);
        ModLoader.BuildGlobalHook<GlobalBuff, DelegateUpdateNPC>(ref HookUpdateNPC, globalBuffs, (GlobalBuff g) => g.Update);
        ModLoader.BuildGlobalHook<GlobalBuff, Func<int, Player, int, int, bool>>(ref HookReApplyPlayer, globalBuffs, (GlobalBuff g) => g.ReApply);
        ModLoader.BuildGlobalHook<GlobalBuff, Func<int, NPC, int, int, bool>>(ref HookReApplyNPC, globalBuffs, (GlobalBuff g) => g.ReApply);
        ModLoader.BuildGlobalHook<GlobalBuff, DelegateModifyBuffText>(ref HookModifyBuffText, globalBuffs, (GlobalBuff g) => g.ModifyBuffText);
        ModLoader.BuildGlobalHook<GlobalBuff, Action<string, List<Vector2>>>(ref HookCustomBuffTipSize, globalBuffs, (GlobalBuff g) => g.CustomBuffTipSize);
        ModLoader.BuildGlobalHook<GlobalBuff, Action<string, SpriteBatch, int, int>>(ref HookDrawCustomBuffTip, globalBuffs, (GlobalBuff g) => g.DrawCustomBuffTip);
        ModLoader.BuildGlobalHook<GlobalBuff, DelegatePreDraw>(ref HookPreDraw, globalBuffs, (GlobalBuff g) => g.PreDraw);
        ModLoader.BuildGlobalHook<GlobalBuff, DelegatePostDraw>(ref HookPostDraw, globalBuffs, (GlobalBuff g) => g.PostDraw);
        ModLoader.BuildGlobalHook<GlobalBuff, DelegateRightClick>(ref HookRightClick, globalBuffs, (GlobalBuff g) => g.RightClick);
    }
References Terraria.Lang._buffDescriptionCache, Terraria.Lang._buffNameCache, Terraria.GameContent.TextureAssets.Buff, Terraria.Main.buffAlpha, Terraria.Main.buffDoubleApply, Terraria.Main.buffNoSave, Terraria.Main.buffNoTimeDisplay, Terraria.ID.BuffID.Count, Terraria.Main.debuff, Terraria.ModLoader.BuffLoader.DelegateModifyBuffText(), Terraria.ModLoader.BuffLoader.DelegatePostDraw(), Terraria.ModLoader.BuffLoader.DelegatePreDraw(), Terraria.ModLoader.BuffLoader.DelegateRightClick(), Terraria.ModLoader.BuffLoader.DelegateUpdateNPC(), Terraria.ModLoader.BuffLoader.DelegateUpdatePlayer(), Terraria.Localization.LocalizedText.Empty, Terraria.ModLoader.BuffLoader.extraPlayerBuffCount, Terraria.ModLoader.BuffLoader.globalBuffs, Terraria.ModLoader.BuffLoader.HookCustomBuffTipSize, Terraria.ModLoader.BuffLoader.HookDrawCustomBuffTip, Terraria.ModLoader.BuffLoader.HookModifyBuffText, Terraria.ModLoader.BuffLoader.HookPostDraw, Terraria.ModLoader.BuffLoader.HookPreDraw, Terraria.ModLoader.BuffLoader.HookReApplyNPC, Terraria.ModLoader.BuffLoader.HookReApplyPlayer, Terraria.ModLoader.BuffLoader.HookRightClick, Terraria.ModLoader.BuffLoader.HookUpdateNPC, Terraria.ModLoader.BuffLoader.HookUpdatePlayer, Terraria.Main.lightPet, Terraria.Main.meleeBuff, Terraria.ModLoader.ModLoader.Mods, Terraria.ModLoader.BuffLoader.nextBuff, Terraria.Main.persistentBuff, Terraria.Main.pvpBuff, Terraria.ModLoader.Core.LoaderUtils.ResetStaticMembers(), and Terraria.Main.vanityPet.
Referenced by Terraria.ModLoader.ModContent.ResizeArrays().