TModLoader: Terraria.ModLoader.BuffLoader.IsModBuff
IsModBuff()
static bool Terraria.ModLoader.BuffLoader.IsModBuff (int type) inline static package
Definition at line 139 of file BuffLoader.cs.
    {
        return type >= BuffID.Count;
    }
References Terraria.ID.BuffID.Count.
Referenced by Terraria.ModLoader.BuffLoader.ModifyBuffText(), Terraria.ModLoader.BuffLoader.PostDraw(), Terraria.ModLoader.BuffLoader.PreDraw(), Terraria.ModLoader.BuffLoader.ReApply(), Terraria.ModLoader.BuffLoader.ReApply(), Terraria.ModLoader.BuffLoader.RightClick(), Terraria.ModLoader.IO.PlayerIO.SaveModBuffs(), Terraria.ModLoader.BuffLoader.Update(), and Terraria.ModLoader.BuffLoader.Update().