TModLoader: Terraria.ModLoader.UI.Elements.UIGrid.UpdateScrollbar
UpdateScrollbar()
void Terraria.ModLoader.UI.Elements.UIGrid.UpdateScrollbar () inline private
    {
        if (_scrollbar != null)
        {
            _scrollbar.SetView(GetInnerDimensions().Height, _innerListHeight);
        }
    }
References Terraria.ModLoader.UI.Elements.UIGrid._innerListHeight, Terraria.ModLoader.UI.Elements.UIGrid._scrollbar, Terraria.UI.UIElement.GetInnerDimensions(), Terraria.UI.UIElement.Height, and Terraria.GameContent.UI.Elements.UIScrollbar.SetView().
Referenced by Terraria.ModLoader.UI.Elements.UIGrid.Recalculate(), Terraria.ModLoader.UI.Elements.UIGrid.SetScrollbar(), and Terraria.ModLoader.UI.Elements.UIGrid.UpdateOrder().