TModLoader: Terraria.ModLoader.UI.Elements.UIGrid.RecalculateChildren
RecalculateChildren()
override void Terraria.ModLoader.UI.Elements.UIGrid.RecalculateChildren () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 143 of file UIGrid.cs.
    {
        float availableWidth = GetInnerDimensions().Width;
        base.RecalculateChildren();
        float top = 0f;
        float left = 0f;
        float maxRowHeight = 0f;
        for (int i = 0; i < _items.Count; i++)
        {
            UIElement uIElement = _items[i];
            CalculatedStyle outerDimensions = uIElement.GetOuterDimensions();
            if (left + outerDimensions.Width > availableWidth && left > 0f)
            {
                top += maxRowHeight + ListPadding;
                left = 0f;
                maxRowHeight = 0f;
            }
            maxRowHeight = Math.Max(maxRowHeight, outerDimensions.Height);
            uIElement.Left.Set(left, 0f);
            left += outerDimensions.Width + ListPadding;
            uIElement.Top.Set(top, 0f);
        }
        _innerListHeight = top + maxRowHeight;
    }
References Terraria.ModLoader.UI.Elements.UIGrid._innerListHeight, Terraria.ModLoader.UI.Elements.UIGrid._items, Terraria.UI.UIElement.GetInnerDimensions(), Terraria.UI.UIElement.GetOuterDimensions(), Terraria.UI.UIElement.Left, Terraria.ModLoader.UI.Elements.UIGrid.ListPadding, Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.Top, and Terraria.UI.CalculatedStyle.Width.