TModLoader: Terraria.ModLoader.ExtraJumpLoader.JumpVisuals
JumpVisuals()
static void Terraria.ModLoader.ExtraJumpLoader.JumpVisuals (Player player) inline static
    {
        ExtraJump[] array = orderedJumps;
        foreach (ExtraJump jump in array)
        {
            if (player.GetJumpState(jump).Active && jump.CanShowVisuals(player) && PlayerLoader.CanShowExtraJumpVisuals(jump, player))
            {
                jump.ShowVisuals(player);
                PlayerLoader.ExtraJumpVisuals(jump, player);
            }
        }
    }
References Terraria.ModLoader.PlayerLoader.CanShowExtraJumpVisuals(), Terraria.ModLoader.ExtraJump.CanShowVisuals(), Terraria.ModLoader.PlayerLoader.ExtraJumpVisuals(), Terraria.ModLoader.ExtraJumpLoader.orderedJumps, and Terraria.ModLoader.ExtraJump.ShowVisuals().
Referenced by Terraria.Player.DoubleJumpVisuals().