TModLoader: Terraria.ModLoader.ExtraJumpLoader.PerformJump
PerformJump()
static void Terraria.ModLoader.ExtraJumpLoader.PerformJump (ExtraJump jump, Player player) inline static private
    {
        float duration = jump.GetDurationMultiplier(player);
        PlayerLoader.ModifyExtraJumpDurationMultiplier(jump, player, ref duration);
        player.velocity.Y = (0f - Player.jumpSpeed) * player.gravDir;
        player.jump = (int)((float)Player.jumpHeight * duration);
        bool playSound = true;
        jump.OnStarted(player, ref playSound);
        PlayerLoader.OnExtraJumpStarted(jump, player, ref playSound);
        if (playSound)
        {
            SoundEngine.PlaySound(16, (int)player.position.X, (int)player.position.Y);
        }
    }
References Terraria.ModLoader.ExtraJump.GetDurationMultiplier(), Terraria.Player.gravDir, Terraria.Player.jumpSpeed, Terraria.ModLoader.PlayerLoader.ModifyExtraJumpDurationMultiplier(), Terraria.ModLoader.PlayerLoader.OnExtraJumpStarted(), Terraria.ModLoader.ExtraJump.OnStarted(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Entity.position.
Referenced by Terraria.ModLoader.ExtraJumpLoader.ProcessJumps().