TModLoader: Terraria.ModLoader.ExtraJumpLoader.StopActiveJump
StopActiveJump()
static void Terraria.ModLoader.ExtraJumpLoader.StopActiveJump (Player player, out bool anyJumpCancelled) inline static package
    {
        anyJumpCancelled = false;
        ExtraJump[] array = orderedJumps;
        foreach (ExtraJump jump in array)
        {
            if (player.GetJumpState(jump).Active)
            {
                StopJump(jump, player);
                anyJumpCancelled = true;
            }
        }
    }
References Terraria.ModLoader.ExtraJumpLoader.orderedJumps, and Terraria.ModLoader.ExtraJumpLoader.StopJump().
Referenced by Terraria.Player.CancelAllJumpVisualEffects(), and Terraria.Player.StopExtraJumpInProgress().