TModLoader: Terraria.Graphics.Shaders.GameShaders.Armor
Armor
ArmorShaderDataSet Terraria.Graphics.Shaders.GameShaders.Armor = new ArmorShaderDataSet() static
Referenced by Terraria.Projectile.AI_026(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_120_StardustGuardian(), Terraria.ModLoader.Engine.EffectsTracker.CacheVanillaState(), Terraria.Player.DashMovement(), Terraria.Mount.DoConfettiMinecartEffect(), Terraria.Mount.DoExhaustMinecartEffect(), Terraria.Mount.DoGemMinecartEffect(), Terraria.Mount.DoSteamMinecartEffect(), Terraria.ModLoader.Default.Developer.Jofairden.JofairdenArmorGlowLayer.Draw(), Terraria.ModLoader.Default.Developer.Jofairden.JofairdenArmorShaderLayer.Draw(), Terraria.Main.DrawNPCDirect_Inner(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_14_2_GlassSlipperSparkles(), Terraria.Main.DrawWithOutlines(), Terraria.Main.EntitySpriteDraw(), Terraria.Main.EntitySpriteDraw(), Terraria.Initializers.DyeInitializer.FixRecipes(), Terraria.Player.Hurt(), Terraria.Projectile.Kill(), Terraria.Player.KillMe(), Terraria.Initializers.DyeInitializer.LoadArmorDyes(), Terraria.Initializers.DyeInitializer.LoadBasicColorDye(), Terraria.Initializers.DyeInitializer.LoadMisc(), Terraria.Player.NinjaDodge(), Terraria.ModLoader.BasiliskMountJump.OnStarted(), Terraria.ModLoader.GoatMountJump.OnStarted(), Terraria.ModLoader.UnicornMountJump.OnStarted(), Terraria.Player.PlayerFrame(), Terraria.ID.ContentSamples.CommonlyUsedContentSamples.PrepareAfterEverythingElseLoaded(), Terraria.ModLoader.Engine.EffectsTracker.RemoveModEffects(), Terraria.Player.RocketBootVisuals(), Terraria.Item.SetDefaults(), Terraria.DataStructures.PlayerDrawHelper.SetShaderForData(), Terraria.ModLoader.UnicornMountJump.ShowVisuals(), Terraria.DelegateMethods.Minecart.SparksMeow(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FlameWaders(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_WallOfFleshGoatMountFlames(), Terraria.Player.SpawnFastRunParticles(), Terraria.Player.Update(), Terraria.Player.UpdateArmorSets(), Terraria.Mount.UpdateEffects(), Terraria.Mount.UpdateFrame(), Terraria.Player.UpdateMinionTarget(), Terraria.Player.WallslideMovement(), Terraria.Player.WingAirVisuals(), Terraria.Player.WingFrame(), and Terraria.Player.Yoraiz0rEye().