TModLoader: Terraria.ModLoader.UI.UIModStateText.DrawPanel
DrawPanel()
void Terraria.ModLoader.UI.UIModStateText.DrawPanel (SpriteBatch spriteBatch) inline private
Definition at line 92 of file UIModStateText.cs.
    {
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        Vector2 position = GetDimensions().Position();
        float width = Width.Pixels;
        spriteBatch.Draw(UICommon.InnerPanelTexture.Value, position, (Rectangle?)new Rectangle(0, 0, 8, UICommon.InnerPanelTexture.Height()), Color.White);
        spriteBatch.Draw(UICommon.InnerPanelTexture.Value, new Vector2(position.X + 8f, position.Y), (Rectangle?)new Rectangle(8, 0, 8, UICommon.InnerPanelTexture.Height()), Color.White, 0f, Vector2.Zero, new Vector2((width - 16f) / 8f, 1f), (SpriteEffects)0, 0f);
        spriteBatch.Draw(UICommon.InnerPanelTexture.Value, new Vector2(position.X + width - 8f, position.Y), (Rectangle?)new Rectangle(16, 0, 8, UICommon.InnerPanelTexture.Height()), Color.White);
    }
References Terraria.UI.UIElement.GetDimensions(), Terraria.ModLoader.UI.UICommon.InnerPanelTexture, Terraria.UI.StyleDimension.Pixels, Terraria.UI.CalculatedStyle.Position(), and Terraria.UI.UIElement.Width.
Referenced by Terraria.ModLoader.UI.UIModStateText.DrawSelf().