TModLoader: Terraria.ModLoader.UI.UIModStateText.DrawEnabledText
DrawEnabledText()
void Terraria.ModLoader.UI.UIModStateText.DrawEnabledText (SpriteBatch spriteBatch) inline private
Definition at line 118 of file UIModStateText.cs.
    {
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        Vector2 pos = GetDimensions().Position() + new Vector2(PaddingLeft, PaddingTop * 0.5f);
        Utils.DrawBorderString(spriteBatch, DisplayText, pos, DisplayColor);
    }
References Terraria.ModLoader.UI.UIModStateText.DisplayColor, Terraria.ModLoader.UI.UIModStateText.DisplayText, Terraria.Utils.DrawBorderString(), Terraria.UI.UIElement.GetDimensions(), Terraria.UI.UIElement.PaddingLeft, Terraria.UI.UIElement.PaddingTop, and Terraria.UI.CalculatedStyle.Position().
Referenced by Terraria.ModLoader.UI.UIModStateText.DrawSelf().