TModLoader: Terraria.ModLoader.UI.UIMessageBox.OnInitialize
OnInitialize()
override void Terraria.ModLoader.UI.UIMessageBox.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 36 of file UIMessageBox.cs.
    {
        UIList obj = new UIList
        {
            Left = StyleDimension.Empty,
            Top = StyleDimension.Empty,
            Width = StyleDimension.Fill,
            Height = StyleDimension.Fill
        };
        UIList element = obj;
        _list = obj;
        Append(element);
        _list.SetScrollbar(_scrollbar);
        UIList list = _list;
        UIText obj2 = new UIText(_text)
        {
            Width = StyleDimension.Fill,
            IsWrapped = true,
            MinWidth = StyleDimension.Empty,
            TextOriginX = 0f
        };
        UIText item = obj2;
        _textElement = obj2;
        list.Add(item);
    }
References Terraria.ModLoader.UI.UIMessageBox._list, Terraria.ModLoader.UI.UIMessageBox._scrollbar, Terraria.ModLoader.UI.UIMessageBox._text, Terraria.ModLoader.UI.UIMessageBox._textElement, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.UI.UIElement.Append(), Terraria.UI.StyleDimension.Empty, Terraria.UI.StyleDimension.Fill, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.MinWidth, Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.UI.UIElement.Top, and Terraria.UI.UIElement.Width.