TModLoader: Terraria.ModLoader.UI.UIMessageBox.SetText
SetText()
void Terraria.ModLoader.UI.UIMessageBox.SetText (string text) inline
    {
        _text = text;
        _textElement?.SetText(_text);
        ResetScrollbar();
    }
References Terraria.ModLoader.UI.UIMessageBox._text, Terraria.ModLoader.UI.UIMessageBox._textElement, Terraria.ModLoader.UI.UIMessageBox.ResetScrollbar(), and Terraria.GameContent.UI.Elements.UIText.SetText().
Referenced by Terraria.ModLoader.UI.UIErrorMessage.OnActivate(), Terraria.ModLoader.UI.UIInfoMessage.OnActivate(), Terraria.ModLoader.UI.UIModInfo.OnActivate(), and Terraria.ModLoader.UI.UIModInfo.Update().