TModLoader: Terraria.ModLoader.UI.UIBestiaryBar.DrawSelf
DrawSelf()
override void Terraria.ModLoader.UI.UIBestiaryBar.DrawSelf (SpriteBatch sb) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 90 of file UIBestiaryBar.cs.
    {
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0102: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        int xOffset = 0;
        Rectangle rectangle = GetDimensions().ToRectangle();
        rectangle.Height -= 3;
        bool drawHover = false;
        BestiaryBarItem hoverData = null;
        Rectangle drawArea = default(Rectangle);
        Rectangle outlineArea = default(Rectangle);
        for (int i = 1; i < _bestiaryBarItems.Count; i++)
        {
            BestiaryBarItem barData = _bestiaryBarItems[i];
            int offset = (int)((float)rectangle.Width * ((float)barData.EntryCount / (float)_db.Entries.Count));
            if (i == _bestiaryBarItems.Count - 1)
            {
                offset = rectangle.Width - xOffset;
            }
            int width = (int)((float)offset * ((float)barData.CompletedCount / (float)barData.EntryCount));
            ((Rectangle)(ref drawArea))._002Ector(rectangle.X + xOffset, rectangle.Y, width, rectangle.Height);
            ((Rectangle)(ref outlineArea))._002Ector(rectangle.X + xOffset, rectangle.Y, offset, rectangle.Height);
            xOffset += offset;
            sb.Draw(TextureAssets.MagicPixel.Value, outlineArea, barData.DrawColor * 0.3f);
            sb.Draw(TextureAssets.MagicPixel.Value, drawArea, barData.DrawColor);
            if (!drawHover && ((Rectangle)(ref outlineArea)).Contains(new Point(Main.mouseX, Main.mouseY)))
            {
                drawHover = true;
                hoverData = barData;
            }
        }
        BestiaryBarItem bottomData = _bestiaryBarItems[0];
        int bottomWidth = (int)((float)rectangle.Width * ((float)bottomData.CompletedCount / (float)bottomData.EntryCount));
        Rectangle bottomDrawArea = default(Rectangle);
        ((Rectangle)(ref bottomDrawArea))._002Ector(rectangle.X, ((Rectangle)(ref rectangle)).Bottom, bottomWidth, 3);
        Rectangle bottomOutlineArea = default(Rectangle);
        ((Rectangle)(ref bottomOutlineArea))._002Ector(rectangle.X, ((Rectangle)(ref rectangle)).Bottom, rectangle.Width, 3);
        sb.Draw(TextureAssets.MagicPixel.Value, bottomOutlineArea, bottomData.DrawColor * 0.3f);
        sb.Draw(TextureAssets.MagicPixel.Value, bottomDrawArea, bottomData.DrawColor);
        if (!drawHover && ((Rectangle)(ref bottomOutlineArea)).Contains(new Point(Main.mouseX, Main.mouseY)))
        {
            drawHover = true;
            hoverData = bottomData;
        }
        if (drawHover && hoverData != null)
        {
            Main.instance.MouseText(hoverData.Tooltop, 0, 0);
        }
    }
References Terraria.ModLoader.UI.UIBestiaryBar._bestiaryBarItems, Terraria.ModLoader.UI.UIBestiaryBar._db, Terraria.GameContent.Bestiary.BestiaryDatabase.Entries, Terraria.UI.UIElement.GetDimensions(), Terraria.Main.instance, Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.MouseText(), Terraria.Main.mouseX, Terraria.Main.mouseY, and Terraria.UI.CalculatedStyle.ToRectangle().