TModLoader: Terraria.ModLoader.ModTile.SetupContent
SetupContent()
override void Terraria.ModLoader.ModTile.SetupContent () inline sealed virtual inherited
If you make a new ModType, seal this override, and call M:Terraria.ModLoader.ModType.SetStaticDefaults in it.
Reimplemented from Terraria.ModLoader.ModType< TEntity, TModType >.
Definition at line 129 of file ModTile.cs.
    {
        TextureAssets.Tile[base.Type] = ModContent.Request<Texture2D>(Texture);
        SetStaticDefaults();
        if (TileObjectData.newTile.Width > 1 || TileObjectData.newTile.Height > 1)
        {
            TileObjectData.FixNewTile();
            throw new Exception("It appears that you have an error surrounding TileObjectData.AddTile in " + GetType().FullName)
            {
                HelpLink = "https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Modding-FAQ#tileobjectdataaddtile-issues"
            };
        }
        if (Main.tileLavaDeath[base.Type])
        {
            Main.tileObsidianKill[base.Type] = true;
        }
        if (Main.tileSolid[base.Type])
        {
            Main.tileNoSunLight[base.Type] = true;
        }
        PostSetDefaults();
        if (TileID.Sets.HasOutlines[base.Type])
        {
            TextureAssets.HighlightMask[base.Type] = ModContent.Request<Texture2D>(HighlightTexture);
        }
        TileID.Search.Add(base.FullName, base.Type);
    }
References Terraria.ObjectData.TileObjectData.FixNewTile(), Terraria.ModLoader.IModType.FullName, Terraria.ID.TileID.Sets.HasOutlines, Terraria.GameContent.TextureAssets.HighlightMask, Terraria.ModLoader.ModTile.HighlightTexture, Terraria.ObjectData.TileObjectData.newTile, Terraria.ModLoader.ModTile.PostSetDefaults(), Terraria.ID.TileID.Search, Terraria.ModLoader.ModBlockType.SetStaticDefaults(), Terraria.ModLoader.ModTexturedType.Texture, Terraria.GameContent.TextureAssets.Tile, Terraria.Main.tileLavaDeath, Terraria.Main.tileNoSunLight, Terraria.Main.tileObsidianKill, and Terraria.Main.tileSolid.