TModLoader: Terraria.GameContent.VoidLensHelper.DrawToDrawData
DrawToDrawData()
void Terraria.GameContent.VoidLensHelper.DrawToDrawData (List< DrawData > drawDataList, int selectionMode) inline
Definition at line 150 of file VoidLensHelper.cs.
    {
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        Main.instance.LoadProjectile(734);
        Asset<Texture2D> asset = TextureAssets.Projectile[734];
        Rectangle rectangle = asset.Frame(1, 8, 0, _frameNumber);
        Color color = Lighting.GetColor(_position.ToTileCoordinates());
        color = Color.Lerp(color, Color.White, 0.5f);
        color *= _opacity;
        DrawData drawData = new DrawData(asset.Value, _position - Main.screenPosition, rectangle, color, 0f, rectangle.Size() / 2f, 1f, (SpriteEffects)0);
        drawDataList.Add(drawData);
        for (float num = 0f; num < 1f; num += 0.34f)
        {
            DrawData item = drawData;
            item.color = new Color(127, 50, 127, 0) * _opacity;
            ref Vector2 scale = ref item.scale;
            scale *= 1.1f;
            float x = (Main.GlobalTimeWrappedHourly / 5f * ((float)Math.PI * 2f)).ToRotationVector2().X;
            ref Color color2 = ref item.color;
            color2 *= x * 0.1f + 0.3f;
            ref Vector2 position = ref item.position;
            position += ((Main.GlobalTimeWrappedHourly / 5f + num) * ((float)Math.PI * 2f)).ToRotationVector2() * (x * 1f + 2f);
            drawDataList.Add(item);
        }
        if (selectionMode != 0)
        {
            int num2 = (((Color)(ref color)).R + ((Color)(ref color)).G + ((Color)(ref color)).B) / 3;
            if (num2 > 10)
            {
                Color selectionGlowColor = Colors.GetSelectionGlowColor(selectionMode == 2, num2);
                drawData = new DrawData(TextureAssets.Extra[93].Value, _position - Main.screenPosition, rectangle, selectionGlowColor, 0f, rectangle.Size() / 2f, 1f, (SpriteEffects)0);
                drawDataList.Add(drawData);
            }
        }
    }
References Terraria.GameContent.VoidLensHelper._frameNumber, Terraria.GameContent.VoidLensHelper._opacity, Terraria.GameContent.VoidLensHelper._position, Terraria.DataStructures.DrawData.color, Terraria.GameContent.TextureAssets.Extra, Terraria.Lighting.GetColor(), Terraria.ID.Colors.GetSelectionGlowColor(), Terraria.Main.instance, Terraria.Main.LoadProjectile(), Terraria.DataStructures.DrawData.position, Terraria.GameContent.TextureAssets.Projectile, Terraria.DataStructures.DrawData.scale, and Terraria.Main.screenPosition.