TModLoader: Terraria.Main.DrawNPCDirect_Deerclops
DrawNPCDirect_Deerclops()
static void Terraria.Main.DrawNPCDirect_Deerclops (SpriteBatch mySpriteBatch, NPC rCurrentNPC, ref Vector2 screenPos, int typeCache, ref Color npcColor, ref Vector2 halfSize, SpriteEffects npcSpriteEffect) inline static private
Definition at line 30329 of file Main.cs.
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_0137: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_0158: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0207: Unknown result type (might be due to invalid IL or missing references)
        //IL_0209: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_025b: Unknown result type (might be due to invalid IL or missing references)
        //IL_025f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0264: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02da: Unknown result type (might be due to invalid IL or missing references)
        //IL_03da: Unknown result type (might be due to invalid IL or missing references)
        //IL_03db: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0451: Unknown result type (might be due to invalid IL or missing references)
        //IL_045c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0463: Unknown result type (might be due to invalid IL or missing references)
        //IL_046d: Unknown result type (might be due to invalid IL or missing references)
        //IL_047a: Unknown result type (might be due to invalid IL or missing references)
        //IL_047f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0313: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_0339: Unknown result type (might be due to invalid IL or missing references)
        //IL_033b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0342: Unknown result type (might be due to invalid IL or missing references)
        //IL_0347: Unknown result type (might be due to invalid IL or missing references)
        //IL_0349: Unknown result type (might be due to invalid IL or missing references)
        //IL_0373: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_037b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0382: Unknown result type (might be due to invalid IL or missing references)
        //IL_0387: Unknown result type (might be due to invalid IL or missing references)
        //IL_038b: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        //IL_038f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0394: Unknown result type (might be due to invalid IL or missing references)
        //IL_0396: Unknown result type (might be due to invalid IL or missing references)
        //IL_039b: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0486: Unknown result type (might be due to invalid IL or missing references)
        //IL_0487: Unknown result type (might be due to invalid IL or missing references)
        //IL_048c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0498: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04be: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04df: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f1: Unknown result type (might be due to invalid IL or missing references)
        Texture2D value = TextureAssets.Npc[typeCache].Value;
        Vector2 vector = rCurrentNPC.Bottom - screenPos;
        Rectangle rectangle = value.Frame(5, 5, rCurrentNPC.frame.Y / 5, rCurrentNPC.frame.Y % 5, 2, 2);
        Vector2 origin = rectangle.Size() * new Vector2(0.5f, 1f);
        origin.Y -= 4f;
        int num = 106;
        if (rCurrentNPC.spriteDirection == 1)
        {
            origin.X = num;
        }
        else
        {
            origin.X = rectangle.Width - num;
        }
        Color value2 = Color.White;
        float amount = 0f;
        float amount2 = 0f;
        int num5 = 0;
        float num6 = 0f;
        float num7 = 0f;
        float num8 = 10f;
        Color color = npcColor;
        if (rCurrentNPC.localAI[3] > 0f)
        {
            float num9 = rCurrentNPC.localAI[3] / 36f;
            num5 = 2;
            num6 = num9 * num9;
            num7 = 20f;
            value2 = new Color(80, 0, 0, 255) * 0.5f;
            amount2 = 1f;
            color = Color.Lerp(Color.Transparent, color, 1f - num9 * num9);
        }
        for (int i = 0; i < num5; i++)
        {
            Color value3 = npcColor;
            value3 = Color.Lerp(value3, value2, amount);
            value3 = rCurrentNPC.GetAlpha(value3);
            value3 = Color.Lerp(value3, value2, amount2);
            value3 *= 1f - num6 * 0.5f;
            Vector2 vector2 = vector;
            mySpriteBatch.Draw(value, vector2 + Utils.RotatedBy(new Vector2(0f, 1f), (float)i * ((float)Math.PI * 2f) / (float)num5 + GlobalTimeWrappedHourly * num8) * num6 * num7, (Rectangle?)rectangle, value3, rCurrentNPC.rotation, origin, rCurrentNPC.scale, (SpriteEffects)(npcSpriteEffect ^ 1), 0f);
        }
        Color color2 = rCurrentNPC.GetAlpha(color);
        Color value4 = default(Color);
        ((Color)(ref value4))._002Ector(50, 0, 160);
        float num10 = 0f;
        if (rCurrentNPC.localAI[3] > 0f)
        {
            float amount3 = Utils.Remap(rCurrentNPC.localAI[3], 0f, 20f, 0f, 1f);
            color2 = Color.Lerp(color2, value4, amount3);
        }
        if (rCurrentNPC.ai[0] == 7f || rCurrentNPC.ai[0] == 8f)
        {
            num10 = Utils.Remap(rCurrentNPC.ai[1], 20f, 60f, 0f, 2f);
            if (num10 > 1f)
            {
                num10 = 2f - num10;
            }
            color2 = Color.Lerp(color2, value4, num10);
            color2 *= 1f - num10;
            float num11 = 5f;
            for (int j = 0; (float)j < num11; j++)
            {
                Vector2 vector3 = vector;
                float num12 = num10 * num10;
                float num2 = 80f * num12;
                float num3 = 80f * num12 + (float)(30 * j) * num12;
                Vector2 vector4 = Vector2.UnitX.RotatedBy((float)j * ((float)Math.PI * 2f) / num11 + GlobalTimeWrappedHourly * 6f) * num2;
                Vector2 vector5 = Vector2.UnitX.RotatedBy((float)j * ((float)Math.PI * 2f) / num11 + GlobalTimeWrappedHourly * 3f * ((float)j * 0.5f)) * num3;
                mySpriteBatch.Draw(value, vector3 + vector4 + vector5, (Rectangle?)rectangle, color2 * 0.5f, rCurrentNPC.rotation, origin, rCurrentNPC.scale, (SpriteEffects)(npcSpriteEffect ^ 1), 0f);
            }
        }
        mySpriteBatch.Draw(value, vector, (Rectangle?)rectangle, color2, rCurrentNPC.rotation, origin, rCurrentNPC.scale, (SpriteEffects)(npcSpriteEffect ^ 1), 0f);
        if (rCurrentNPC.localAI[3] > 0f)
        {
            Texture2D value5 = TextureAssets.Extra[245].Value;
            float num4 = Utils.Remap(rCurrentNPC.localAI[3], 0f, 20f, 0f, 1f);
            Color color3 = new Color(255, 30, 30, 66) * rCurrentNPC.Opacity * num4 * 0.25f * (1f - num10);
            for (int k = 0; k < num5; k++)
            {
                Vector2 vector6 = vector;
                mySpriteBatch.Draw(value5, vector6 + Utils.RotatedBy(new Vector2(0f, 1f), (float)k * ((float)Math.PI * 2f) / (float)num5 + GlobalTimeWrappedHourly * num8) * num6 * 4f, (Rectangle?)rectangle, color3, rCurrentNPC.rotation, origin, rCurrentNPC.scale, (SpriteEffects)(npcSpriteEffect ^ 1), 0f);
            }
        }
    }
References Terraria.Graphics.Light.Color, Terraria.GameContent.TextureAssets.Extra, Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.TextureAssets.Npc, Terraria.Utils.Remap(), and Terraria.Utils.RotatedBy().
Referenced by Terraria.Main.DrawNPCDirect_Inner().