TModLoader: Terraria.Main.DrawNPCs
DrawNPCs()
void Terraria.Main.DrawNPCs (bool behindTiles = false) inline protected
Definition at line 21897 of file Main.cs.
    {
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08af: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_087a: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0405: Unknown result type (might be due to invalid IL or missing references)
        //IL_040f: Unknown result type (might be due to invalid IL or missing references)
        //IL_066b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0675: Unknown result type (might be due to invalid IL or missing references)
        //IL_0687: Unknown result type (might be due to invalid IL or missing references)
        //IL_0691: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0500: Unknown result type (might be due to invalid IL or missing references)
        //IL_050b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0519: Unknown result type (might be due to invalid IL or missing references)
        //IL_051e: Unknown result type (might be due to invalid IL or missing references)
        //IL_052f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0541: Unknown result type (might be due to invalid IL or missing references)
        //IL_0553: Unknown result type (might be due to invalid IL or missing references)
        //IL_0566: Unknown result type (might be due to invalid IL or missing references)
        //IL_0570: Unknown result type (might be due to invalid IL or missing references)
        //IL_0596: Unknown result type (might be due to invalid IL or missing references)
        //IL_0720: Unknown result type (might be due to invalid IL or missing references)
        //IL_072a: Unknown result type (might be due to invalid IL or missing references)
        //IL_074f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0759: Unknown result type (might be due to invalid IL or missing references)
        //IL_0776: Unknown result type (might be due to invalid IL or missing references)
        //IL_0781: Unknown result type (might be due to invalid IL or missing references)
        //IL_078f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0794: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_080c: Unknown result type (might be due to invalid IL or missing references)
        //IL_027d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        //IL_0293: Unknown result type (might be due to invalid IL or missing references)
        //IL_029e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0301: Unknown result type (might be due to invalid IL or missing references)
        //IL_030b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0331: Unknown result type (might be due to invalid IL or missing references)
        bool flag = false;
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector((int)screenPosition.X - 800, (int)screenPosition.Y - 800, screenWidth + 1600, screenHeight + 1600);
        Vector2 vector = default(Vector2);
        Vector2 vector2 = default(Vector2);
        Vector2 vector3 = default(Vector2);
        for (int num = 199; num >= 0; num--)
        {
            try
            {
                if (npc[num].active && npc[num].type > 0 && !npc[num].hide)
                {
                    NPC obj = npc[num];
                    obj.position += npc[num].netOffset;
                    if (npc[num].behindTiles == behindTiles)
                    {
                        if (npc[num].type == 125 || npc[num].type == 126)
{
                            if (!NPC.IsMechQueenUp && !flag)
{
                                flag = true;
                                for (int i = 0; i < 200; i++)
{
                                    if (!npc[i].active || num == i || (npc[i].type != 125 && npc[i].type != 126))
{
                                        continue;
                                    }
                                    float scale = npc[i].scale;
                                    float x = npc[i].Center.X;
                                    float num10 = npc[i].Bottom.Y - (float)npc[i].height * 0.5f * scale;
                                    float x2 = npc[num].Center.X;
                                    float y = npc[num].Bottom.Y - (float)npc[num].height * 0.5f * scale;
                                    ((Vector2)(ref vector))._002Ector(x2, y);
                                    float num11 = x - vector.X;
                                    float num12 = num10 - vector.Y;
                                    float rotation = (float)Math.Atan2(num12, num11) - 1.57f;
                                    bool flag2 = true;
                                    float num13 = (float)Math.Sqrt(num11 * num11 + num12 * num12);
                                    if (num13 > 2000f)
{
                                        flag2 = false;
                                    }
                                    float num14 = 40f * scale;
                                    while (flag2)
{
                                        num13 = (float)Math.Sqrt(num11 * num11 + num12 * num12);
                                        if (num13 < num14)
{
                                            flag2 = false;
                                            continue;
                                        }
                                        num13 = (float)TextureAssets.Chain12.Height() * scale / num13;
                                        num11 *= num13;
                                        num12 *= num13;
                                        vector.X += num11;
                                        vector.Y += num12;
                                        num11 = x - vector.X;
                                        num12 = num10 - vector.Y;
                                        Color color = Lighting.GetColor((int)vector.X / 16, (int)(vector.Y / 16f));
                                        spriteBatch.Draw(TextureAssets.Chain12.Value, new Vector2(vector.X - screenPosition.X, vector.Y - screenPosition.Y), (Rectangle?)new Rectangle(0, 0, TextureAssets.Chain12.Width(), TextureAssets.Chain12.Height()), color, rotation, new Vector2((float)TextureAssets.Chain12.Width() * 0.5f, (float)TextureAssets.Chain12.Height() * 0.5f), scale, (SpriteEffects)0, 0f);
                                    }
                                }
                            }
                        }
                        else if (npc[num].type == 263 && npc[num].aiStyle == 52 && NPC.plantBoss >= 0)
{
                            ((Vector2)(ref vector2))._002Ector(npc[num].position.X + (float)(npc[num].width / 2), npc[num].position.Y + (float)(npc[num].height / 2));
                            float num15 = npc[NPC.plantBoss].Center.X - vector2.X;
                            float num16 = npc[NPC.plantBoss].Center.Y - vector2.Y;
                            float rotation2 = (float)Math.Atan2(num16, num15) - 1.57f;
                            bool flag3 = true;
                            while (flag3)
{
                                int num17 = 16;
                                int num2 = 32;
                                float num3 = (float)Math.Sqrt(num15 * num15 + num16 * num16);
                                if (num3 < (float)num2)
{
                                    num17 = (int)num3 - num2 + num17;
                                    flag3 = false;
                                }
                                num3 = (float)num17 / num3;
                                num15 *= num3;
                                num16 *= num3;
                                vector2.X += num15;
                                vector2.Y += num16;
                                num15 = npc[NPC.plantBoss].Center.X - vector2.X + npc[NPC.plantBoss].netOffset.X;
                                num16 = npc[NPC.plantBoss].Center.Y - vector2.Y + npc[NPC.plantBoss].netOffset.Y;
                                Color color2 = Lighting.GetColor((int)vector2.X / 16, (int)(vector2.Y / 16f));
                                spriteBatch.Draw(TextureAssets.Chain26.Value, new Vector2(vector2.X - screenPosition.X, vector2.Y - screenPosition.Y), (Rectangle?)new Rectangle(0, 0, TextureAssets.Chain26.Width(), num17), color2, rotation2, new Vector2((float)TextureAssets.Chain26.Width() * 0.5f, (float)TextureAssets.Chain26.Height() * 0.5f), 1f, (SpriteEffects)0, 0f);
                            }
                        }
                        else if (npc[num].type == 264 && npc[num].aiStyle == 53 && NPC.plantBoss >= 0)
{
                            int num4 = NPC.plantBoss;
                            if (npc[num].ai[3] > 0f)
{
                                num4 = (int)npc[num].ai[3] - 1;
                            }
                            ((Vector2)(ref vector3))._002Ector(npc[num].position.X + (float)(npc[num].width / 2), npc[num].position.Y + (float)(npc[num].height / 2));
                            float num5 = npc[num4].Center.X - vector3.X;
                            float num6 = npc[num4].Center.Y - vector3.Y;
                            float rotation3 = (float)Math.Atan2(num6, num5) - 1.57f;
                            bool flag4 = true;
                            while (flag4)
{
                                int num7 = 16;
                                int num8 = 32;
                                float num9 = (float)Math.Sqrt(num5 * num5 + num6 * num6);
                                if (num9 < (float)num8)
{
                                    num7 = (int)num9 - num8 + num7;
                                    flag4 = false;
                                }
                                num9 = (float)num7 / num9;
                                num5 *= num9;
                                num6 *= num9;
                                vector3.X += num5;
                                vector3.Y += num6;
                                num5 = npc[num4].Center.X - vector3.X + npc[num4].netOffset.X;
                                num6 = npc[num4].Center.Y - vector3.Y + npc[num4].netOffset.Y;
                                Color color3 = Lighting.GetColor((int)vector3.X / 16, (int)(vector3.Y / 16f));
                                spriteBatch.Draw(TextureAssets.Chain27.Value, new Vector2(vector3.X - screenPosition.X, vector3.Y - screenPosition.Y), (Rectangle?)new Rectangle(0, 0, TextureAssets.Chain27.Width(), num7), color3, rotation3, new Vector2((float)TextureAssets.Chain27.Width() * 0.5f, (float)TextureAssets.Chain27.Height() * 0.5f), 1f, (SpriteEffects)0, 0f);
                            }
                        }
                        if (NPCID.Sets.MustAlwaysDraw[npc[num].type] || ((Rectangle)(ref rectangle)).Intersects(new Rectangle((int)npc[num].position.X, (int)npc[num].position.Y, npc[num].width, npc[num].height)))
{
                            DrawNPCCheckAlt(npc[num]);
                            DrawNPC(num, behindTiles);
                        }
                    }
                    NPC obj2 = npc[num];
                    obj2.position -= npc[num].netOffset;
                }
            }
            catch
            {
                npc[num].active = false;
            }
        }
    }
References Terraria.GameContent.TextureAssets.Chain12, Terraria.GameContent.TextureAssets.Chain26, Terraria.GameContent.TextureAssets.Chain27, Terraria.Main.DrawNPC(), Terraria.Main.DrawNPCCheckAlt(), Terraria.Lighting.GetColor(), Terraria.NPC.IsMechQueenUp, Terraria.ID.NPCID.Sets.MustAlwaysDraw, Terraria.Main.npc, Terraria.NPC.plantBoss, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DoDraw_DrawNPCsBehindTiles(), Terraria.Main.DoDraw_DrawNPCsOverTiles(), and Terraria.Main.DrawCapture().