TModLoader: Terraria.Main.DrawMiscMapIcons
DrawMiscMapIcons()
void Terraria.Main.DrawMiscMapIcons (SpriteBatch spriteBatch, Vector2 mapTopLeft, Vector2 mapX2Y2AndOff, Rectangle? mapRect, float mapScale, float drawScale, ref string mouseTextString) inline private
Definition at line 71971 of file Main.cs.
    {
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_0003: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        DrawMapIcons_PotionOfReturnHomePosition(spriteBatch, mapTopLeft, mapX2Y2AndOff, mapRect, mapScale, drawScale, ref mouseTextString);
        DrawMapIcons_PotionOfReturnAppearAfterUsePosition(spriteBatch, mapTopLeft, mapX2Y2AndOff, mapRect, mapScale, drawScale, ref mouseTextString);
        DrawMapIcons_LastGolfballHit(spriteBatch, mapTopLeft, mapX2Y2AndOff, mapRect, mapScale, drawScale, ref mouseTextString);
    }
References Terraria.Main.DrawMapIcons_LastGolfballHit(), Terraria.Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition(), Terraria.Main.DrawMapIcons_PotionOfReturnHomePosition(), and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawMap().