TModLoader: Terraria.Main.DrawItem
DrawItem()
void Terraria.Main.DrawItem (Item item, int whoami) inline protected
Definition at line 49591 of file Main.cs.
    {
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_03af: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_052d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0539: Unknown result type (might be due to invalid IL or missing references)
        //IL_054c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0552: Unknown result type (might be due to invalid IL or missing references)
        //IL_0554: Unknown result type (might be due to invalid IL or missing references)
        //IL_055b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0560: Unknown result type (might be due to invalid IL or missing references)
        //IL_0565: Unknown result type (might be due to invalid IL or missing references)
        //IL_0576: Unknown result type (might be due to invalid IL or missing references)
        //IL_057d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_089f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0882: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_070a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0711: Unknown result type (might be due to invalid IL or missing references)
        //IL_042f: Unknown result type (might be due to invalid IL or missing references)
        //IL_043b: Unknown result type (might be due to invalid IL or missing references)
        //IL_044e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0454: Unknown result type (might be due to invalid IL or missing references)
        //IL_0456: Unknown result type (might be due to invalid IL or missing references)
        //IL_045d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0462: Unknown result type (might be due to invalid IL or missing references)
        //IL_0467: Unknown result type (might be due to invalid IL or missing references)
        //IL_047b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0482: Unknown result type (might be due to invalid IL or missing references)
        //IL_092c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0931: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0916: Unknown result type (might be due to invalid IL or missing references)
        //IL_091d: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05df: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0609: Unknown result type (might be due to invalid IL or missing references)
        //IL_0610: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0322: Unknown result type (might be due to invalid IL or missing references)
        //IL_032c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0331: Unknown result type (might be due to invalid IL or missing references)
        //IL_0943: Unknown result type (might be due to invalid IL or missing references)
        //IL_0945: Unknown result type (might be due to invalid IL or missing references)
        //IL_094c: Unknown result type (might be due to invalid IL or missing references)
        //IL_094e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0955: Unknown result type (might be due to invalid IL or missing references)
        //IL_0754: Unknown result type (might be due to invalid IL or missing references)
        //IL_0760: Unknown result type (might be due to invalid IL or missing references)
        //IL_0773: Unknown result type (might be due to invalid IL or missing references)
        //IL_0779: Unknown result type (might be due to invalid IL or missing references)
        //IL_077b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0782: Unknown result type (might be due to invalid IL or missing references)
        //IL_0787: Unknown result type (might be due to invalid IL or missing references)
        //IL_078c: Unknown result type (might be due to invalid IL or missing references)
        //IL_079a: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a03: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a05: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a29: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a76: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a78: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0adf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b05: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b12: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b17: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b44: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b49: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b50: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b54: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b56: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b60: Unknown result type (might be due to invalid IL or missing references)
        if (!item.active || item.IsAir)
        {
            return;
        }
        instance.LoadItem(item.type);
        DrawItem_GetBasics(item, whoami, out var texture, out var frame, out var glowmaskFrame);
        Vector2 vector = frame.Size() / 2f;
        Vector2 vector2 = default(Vector2);
        ((Vector2)(ref vector2))._002Ector((float)(item.width / 2) - vector.X, (float)(item.height - frame.Height));
        Vector2 vector3 = item.position - screenPosition + vector + vector2;
        float num = item.velocity.X * 0.2f;
        if (item.shimmered)
        {
            num = 0f;
        }
        float scale = 1f;
        Color color = Lighting.GetColor(item.Center.ToTileCoordinates());
        Color currentColor = item.GetAlpha(color);
        if (item.shimmered)
        {
            ((Color)(ref currentColor)).R = (byte)(255f * (1f - item.shimmerTime));
            ((Color)(ref currentColor)).G = (byte)(255f * (1f - item.shimmerTime));
            ((Color)(ref currentColor)).B = (byte)(255f * (1f - item.shimmerTime));
            ((Color)(ref currentColor)).A = (byte)(255f * (1f - item.shimmerTime));
        }
        else if (item.shimmerTime > 0f)
        {
            ((Color)(ref currentColor)).R = (byte)((float)(int)((Color)(ref currentColor)).R * (1f - item.shimmerTime));
            ((Color)(ref currentColor)).G = (byte)((float)(int)((Color)(ref currentColor)).G * (1f - item.shimmerTime));
            ((Color)(ref currentColor)).B = (byte)((float)(int)((Color)(ref currentColor)).B * (1f - item.shimmerTime));
            ((Color)(ref currentColor)).A = (byte)((float)(int)((Color)(ref currentColor)).A * (1f - item.shimmerTime));
        }
        ItemSlot.GetItemLight(ref currentColor, ref scale, item);
        if (ItemLoader.PreDrawInWorld(item, spriteBatch, color, currentColor, ref num, ref scale, whoami))
        {
            int num5 = item.glowMask;
            if (!gamePaused && ((Game)this).IsActive && (item.IsACoin || item.type == 58 || item.type == 109) && ((Color)(ref color)).R > 60 && (float)rand.Next(500) - (Math.Abs(item.velocity.X) + Math.Abs(item.velocity.Y)) * 10f < (float)(((Color)(ref color)).R / 50))
            {
                int type = 43;
                Color newColor = Color.White;
                int alpha = 254;
                float scale2 = 0.5f;
                if (item.IsACoin)
                {
                    newColor = default(Color);
                    alpha = 0;
                    scale2 = 1f;
                }
                switch (item.type)
                {
                case 71:
                    type = 244;
                    break;
                case 72:
                    type = 245;
                    break;
                case 73:
                    type = 246;
                    break;
                case 74:
                    type = 247;
                    break;
                }
                int num6 = Dust.NewDust(item.position, item.width, item.height, type, 0f, 0f, alpha, newColor, scale2);
                Dust obj = dust[num6];
                obj.velocity *= 0f;
            }
            if (ItemID.Sets.BossBag[item.type])
            {
                float num7 = (float)item.timeSinceItemSpawned / 240f + GlobalTimeWrappedHourly * 0.04f;
                float globalTimeWrappedHourly = GlobalTimeWrappedHourly;
                globalTimeWrappedHourly %= 4f;
                globalTimeWrappedHourly /= 2f;
                if (globalTimeWrappedHourly >= 1f)
                {
                    globalTimeWrappedHourly = 2f - globalTimeWrappedHourly;
                }
                globalTimeWrappedHourly = globalTimeWrappedHourly * 0.5f + 0.5f;
                for (float num8 = 0f; num8 < 1f; num8 += 0.25f)
                {
                    spriteBatch.Draw(texture, vector3 + Utils.RotatedBy(new Vector2(0f, 8f), (num8 + num7) * ((float)Math.PI * 2f)) * globalTimeWrappedHourly, (Rectangle?)frame, new Color(90, 70, 255, 50), num, vector, scale, (SpriteEffects)0, 0f);
                }
                for (float num9 = 0f; num9 < 1f; num9 += 0.34f)
                {
                    spriteBatch.Draw(texture, vector3 + Utils.RotatedBy(new Vector2(0f, 4f), (num9 + num7) * ((float)Math.PI * 2f)) * globalTimeWrappedHourly, (Rectangle?)frame, new Color(140, 120, 255, 77), num, vector, scale, (SpriteEffects)0, 0f);
                }
            }
            else if (item.type == 75)
            {
                float num10 = (float)item.timeSinceItemSpawned / 240f + GlobalTimeWrappedHourly * 0.04f;
                float globalTimeWrappedHourly2 = GlobalTimeWrappedHourly;
                globalTimeWrappedHourly2 %= 5f;
                globalTimeWrappedHourly2 /= 2.5f;
                if (globalTimeWrappedHourly2 >= 1f)
                {
                    globalTimeWrappedHourly2 = 2f - globalTimeWrappedHourly2;
                }
                globalTimeWrappedHourly2 = globalTimeWrappedHourly2 * 0.5f + 0.5f;
                for (float num11 = 0f; num11 < 1f; num11 += 0.25f)
                {
                    spriteBatch.Draw(TextureAssets.Item[item.type].Value, vector3 + Utils.RotatedBy(new Vector2(0f, 8f), (num11 + num10) * ((float)Math.PI * 2f)) * globalTimeWrappedHourly2, (Rectangle?)frame, new Color(50, 50, 255, 50), num, vector, scale, (SpriteEffects)0, 0f);
                }
                for (float num12 = 0f; num12 < 1f; num12 += 0.34f)
                {
                    spriteBatch.Draw(TextureAssets.Item[item.type].Value, vector3 + Utils.RotatedBy(new Vector2(0f, 4f), (num12 + num10) * ((float)Math.PI * 2f)) * globalTimeWrappedHourly2, (Rectangle?)frame, new Color(120, 120, 255, 127), num, vector, scale, (SpriteEffects)0, 0f);
                }
            }
            else if (item.type == 4143)
            {
                float num2 = (float)item.timeSinceItemSpawned / 240f + GlobalTimeWrappedHourly * 0.04f;
                float globalTimeWrappedHourly3 = GlobalTimeWrappedHourly;
                globalTimeWrappedHourly3 %= 5f;
                globalTimeWrappedHourly3 /= 2.5f;
                if (globalTimeWrappedHourly3 >= 1f)
                {
                    globalTimeWrappedHourly3 = 2f - globalTimeWrappedHourly3;
                }
                globalTimeWrappedHourly3 = globalTimeWrappedHourly3 * 0.5f + 0.5f;
                for (float num3 = 0f; num3 < 1f; num3 += 0.34f)
                {
                    spriteBatch.Draw(TextureAssets.Item[item.type].Value, vector3 + Utils.RotatedBy(new Vector2(0f, 8f), (num3 + num2) * ((float)Math.PI * 2f)) * globalTimeWrappedHourly3, (Rectangle?)frame, new Color(30, 30, 155, 60), num, vector, scale, (SpriteEffects)0, 0f);
                }
                for (float num4 = 0f; num4 < 1f; num4 += 0.34f)
                {
                    spriteBatch.Draw(TextureAssets.Item[item.type].Value, vector3 + Utils.RotatedBy(new Vector2(0f, 4f), (num4 + num2) * ((float)Math.PI * 2f)) * globalTimeWrappedHourly3, (Rectangle?)frame, new Color(60, 60, 127, 57), num, vector, scale, (SpriteEffects)0, 0f);
                }
                spriteBatch.Draw(texture, vector3, (Rectangle?)frame, new Color(255, 255, 255, 128), num, vector, scale, (SpriteEffects)0, 0f);
            }
            if ((item.type >= 1522 && item.type <= 1527) || item.type == 3643)
            {
                currentColor = ((!(item.shimmerTime > 0f)) ? new Color(250, 250, 250, mouseTextColor / 2) : new Color((int)(250f * (1f - item.shimmerTime)), (int)(250f * (1f - item.shimmerTime)), (int)(250f * (1f - item.shimmerTime)), (int)((float)(mouseTextColor / 2) * (1f - item.shimmerTime))));
                scale = (float)(int)mouseTextColor / 1000f + 0.8f;
            }
            if (item.type == 3779)
            {
                num5 = -1;
            }
            spriteBatch.Draw(texture, vector3, (Rectangle?)frame, currentColor, num, vector, scale, (SpriteEffects)0, 0f);
            if (item.shimmered)
            {
                spriteBatch.Draw(texture, vector3, (Rectangle?)frame, new Color((int)((Color)(ref currentColor)).R, (int)((Color)(ref currentColor)).G, (int)((Color)(ref currentColor)).B, 0), num, vector, scale, (SpriteEffects)0, 0f);
            }
            if (item.color != Color.Transparent)
            {
                spriteBatch.Draw(texture, vector3, (Rectangle?)frame, item.GetColor(color), num, vector, scale, (SpriteEffects)0, 0f);
            }
            if (num5 != -1)
            {
                Color color2 = default(Color);
                ((Color)(ref color2))._002Ector(250, 250, 250, item.alpha);
                if (item.type == 5146)
                {
                    ((Color)(ref color2))._002Ector(DiscoR, DiscoG, DiscoB);
                }
                spriteBatch.Draw(TextureAssets.GlowMask[num5].Value, vector3, (Rectangle?)frame, color2, num, vector, scale, (SpriteEffects)0, 0f);
            }
            if (ItemID.Sets.TrapSigned[item.type])
            {
                spriteBatch.Draw(TextureAssets.Wire.Value, vector3 + frame.Size().RotatedBy(num) * 0.45f * item.scale, (Rectangle?)new Rectangle(4, 58, 8, 8), currentColor, 0f, new Vector2(4f), 1f, (SpriteEffects)0, 0f);
            }
            if (item.type == 3858)
            {
                spriteBatch.Draw(TextureAssets.GlowMask[233].Value, vector3, (Rectangle?)glowmaskFrame, new Color(255, 255, 255, 63) * 0.75f, num, glowmaskFrame.Size() / 2f, scale, (SpriteEffects)0, 0f);
            }
            if (ItemID.Sets.DrawUnsafeIndicator[item.type])
            {
                Vector2 vector4 = new Vector2(-4f, -4f) * scale;
                Texture2D value = TextureAssets.Extra[258].Value;
                Rectangle rectangle = value.Frame();
                spriteBatch.Draw(value, vector3 + vector4 + frame.Size().RotatedBy(num) * 0.45f * item.scale, (Rectangle?)rectangle, currentColor, num, rectangle.Size() / 2f, 1f, (SpriteEffects)0, 0f);
            }
        }
        ItemLoader.PostDrawInWorld(item, spriteBatch, color, currentColor, num, scale, whoami);
    }
References Terraria.Entity.active, Terraria.Item.alpha, Terraria.ID.ItemID.Sets.BossBag, Terraria.Entity.Center, Terraria.Graphics.Light.Color, Terraria.Item.color, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.Main.DrawItem_GetBasics(), Terraria.ID.ItemID.Sets.DrawUnsafeIndicator, Terraria.Main.dust, Terraria.GameContent.TextureAssets.Extra, Terraria.Main.gamePaused, Terraria.Item.GetAlpha(), Terraria.Item.GetColor(), Terraria.Lighting.GetColor(), Terraria.UI.ItemSlot.GetItemLight(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.TextureAssets.GlowMask, Terraria.Item.glowMask, Terraria.Entity.height, Terraria.Main.instance, Terraria.Item.IsACoin, Terraria.Item.IsAir, Terraria.GameContent.TextureAssets.Item, Terraria.Main.item, Terraria.Main.LoadItem(), Terraria.Main.mouseTextColor, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Entity.position, Terraria.ModLoader.ItemLoader.PostDrawInWorld(), Terraria.ModLoader.ItemLoader.PreDrawInWorld(), Terraria.Main.rand, Terraria.Utils.RotatedBy(), Terraria.Item.scale, Terraria.Main.screenPosition, Terraria.Item.shimmered, Terraria.Item.shimmerTime, Terraria.Main.spriteBatch, Terraria.Item.timeSinceItemSpawned, Terraria.ID.ItemID.Sets.TrapSigned, Terraria.Item.type, Terraria.Entity.velocity, Terraria.Entity.width, and Terraria.GameContent.TextureAssets.Wire.
Referenced by Terraria.Main.DrawItems().