TModLoader: Terraria.Main.DrawBackground
DrawBackground()
void Terraria.Main.DrawBackground () inline protected
Definition at line 67299 of file Main.cs.
    {
        //IL_1738: Unknown result type (might be due to invalid IL or missing references)
        //IL_173d: Unknown result type (might be due to invalid IL or missing references)
        //IL_173f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1758: Unknown result type (might be due to invalid IL or missing references)
        //IL_1762: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_10f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_10fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c34: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c39: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c54: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bdf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1be8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bed: Unknown result type (might be due to invalid IL or missing references)
        //IL_118b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1190: Unknown result type (might be due to invalid IL or missing references)
        //IL_1192: Unknown result type (might be due to invalid IL or missing references)
        //IL_1197: Unknown result type (might be due to invalid IL or missing references)
        //IL_119c: Unknown result type (might be due to invalid IL or missing references)
        //IL_11aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_11af: Unknown result type (might be due to invalid IL or missing references)
        //IL_11b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_11b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_11bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_1205: Unknown result type (might be due to invalid IL or missing references)
        //IL_120a: Unknown result type (might be due to invalid IL or missing references)
        //IL_120c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1225: Unknown result type (might be due to invalid IL or missing references)
        //IL_1231: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cfe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d12: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fa4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fb8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a87: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1aa7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ab1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ac9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b68: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b88: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b92: Unknown result type (might be due to invalid IL or missing references)
        //IL_235d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2371: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_17de: Unknown result type (might be due to invalid IL or missing references)
        //IL_3367: Unknown result type (might be due to invalid IL or missing references)
        //IL_337b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2415: Unknown result type (might be due to invalid IL or missing references)
        //IL_23e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_229e: Unknown result type (might be due to invalid IL or missing references)
        //IL_22a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2272: Unknown result type (might be due to invalid IL or missing references)
        //IL_12da: Unknown result type (might be due to invalid IL or missing references)
        //IL_12dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_12de: Unknown result type (might be due to invalid IL or missing references)
        //IL_12e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_341b: Unknown result type (might be due to invalid IL or missing references)
        //IL_33e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_18d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_18db: Unknown result type (might be due to invalid IL or missing references)
        //IL_18dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_18fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_1904: Unknown result type (might be due to invalid IL or missing references)
        //IL_2049: Unknown result type (might be due to invalid IL or missing references)
        //IL_204e: Unknown result type (might be due to invalid IL or missing references)
        //IL_191a: Unknown result type (might be due to invalid IL or missing references)
        //IL_191c: Unknown result type (might be due to invalid IL or missing references)
        //IL_19c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_19c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_19c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_19e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_19ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_1581: Unknown result type (might be due to invalid IL or missing references)
        //IL_1586: Unknown result type (might be due to invalid IL or missing references)
        //IL_1588: Unknown result type (might be due to invalid IL or missing references)
        //IL_15a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_15b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1335: Unknown result type (might be due to invalid IL or missing references)
        //IL_133a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1368: Unknown result type (might be due to invalid IL or missing references)
        //IL_136d: Unknown result type (might be due to invalid IL or missing references)
        //IL_139b: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_13ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_13d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1416: Unknown result type (might be due to invalid IL or missing references)
        //IL_141b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1446: Unknown result type (might be due to invalid IL or missing references)
        //IL_144b: Unknown result type (might be due to invalid IL or missing references)
        //IL_147a: Unknown result type (might be due to invalid IL or missing references)
        //IL_147f: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_14b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_20d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_20d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_20d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_20ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_20f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2091: Unknown result type (might be due to invalid IL or missing references)
        //IL_209a: Unknown result type (might be due to invalid IL or missing references)
        //IL_209f: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_166e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1673: Unknown result type (might be due to invalid IL or missing references)
        //IL_1675: Unknown result type (might be due to invalid IL or missing references)
        //IL_1694: Unknown result type (might be due to invalid IL or missing references)
        //IL_169e: Unknown result type (might be due to invalid IL or missing references)
        //IL_210e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2110: Unknown result type (might be due to invalid IL or missing references)
        //IL_219b: Unknown result type (might be due to invalid IL or missing references)
        //IL_21a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_21a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_21b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_21c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_30ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_30ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_1de7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a36: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa3: Unknown result type (might be due to invalid IL or missing references)
        //IL_3dad: Unknown result type (might be due to invalid IL or missing references)
        //IL_3dc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ed8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1edd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1edf: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ef8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cae: Unknown result type (might be due to invalid IL or missing references)
        //IL_3152: Unknown result type (might be due to invalid IL or missing references)
        //IL_3157: Unknown result type (might be due to invalid IL or missing references)
        //IL_31c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_31c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_31ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_31e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_31f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3e5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_3e62: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ece: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ed3: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ed5: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ef1: Unknown result type (might be due to invalid IL or missing references)
        //IL_3efb: Unknown result type (might be due to invalid IL or missing references)
        //IL_3206: Unknown result type (might be due to invalid IL or missing references)
        //IL_3208: Unknown result type (might be due to invalid IL or missing references)
        //IL_3293: Unknown result type (might be due to invalid IL or missing references)
        //IL_3298: Unknown result type (might be due to invalid IL or missing references)
        //IL_329a: Unknown result type (might be due to invalid IL or missing references)
        //IL_32b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_32c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b71: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f92: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f11: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f13: Unknown result type (might be due to invalid IL or missing references)
        //IL_3f9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fa3: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fa5: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_3fcb: Unknown result type (might be due to invalid IL or missing references)
        //IL_2549: Unknown result type (might be due to invalid IL or missing references)
        //IL_254e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bfa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bfc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c11: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff5: Unknown result type (might be due to invalid IL or missing references)
        //IL_356c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3571: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d52: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d92: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d94: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e26: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e45: Unknown result type (might be due to invalid IL or missing references)
        //IL_3ccb: Unknown result type (might be due to invalid IL or missing references)
        //IL_3cd0: Unknown result type (might be due to invalid IL or missing references)
        //IL_3cd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_3cf9: Unknown result type (might be due to invalid IL or missing references)
        //IL_3d03: Unknown result type (might be due to invalid IL or missing references)
        //IL_3d0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3d12: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f18: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f38: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f42: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ec3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ecc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ed1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f58: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ff9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ffe: Unknown result type (might be due to invalid IL or missing references)
        //IL_3000: Unknown result type (might be due to invalid IL or missing references)
        //IL_3019: Unknown result type (might be due to invalid IL or missing references)
        //IL_3023: Unknown result type (might be due to invalid IL or missing references)
        //IL_369a: Unknown result type (might be due to invalid IL or missing references)
        //IL_369c: Unknown result type (might be due to invalid IL or missing references)
        //IL_369e: Unknown result type (might be due to invalid IL or missing references)
        //IL_36a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a06: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a08: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a12: Unknown result type (might be due to invalid IL or missing references)
        //IL_3bf2: Unknown result type (might be due to invalid IL or missing references)
        //IL_3bf7: Unknown result type (might be due to invalid IL or missing references)
        //IL_3bf9: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c20: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c33: Unknown result type (might be due to invalid IL or missing references)
        //IL_3c39: Unknown result type (might be due to invalid IL or missing references)
        //IL_2682: Unknown result type (might be due to invalid IL or missing references)
        //IL_2684: Unknown result type (might be due to invalid IL or missing references)
        //IL_2686: Unknown result type (might be due to invalid IL or missing references)
        //IL_2688: Unknown result type (might be due to invalid IL or missing references)
        //IL_393e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3943: Unknown result type (might be due to invalid IL or missing references)
        //IL_3945: Unknown result type (might be due to invalid IL or missing references)
        //IL_3972: Unknown result type (might be due to invalid IL or missing references)
        //IL_397c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3985: Unknown result type (might be due to invalid IL or missing references)
        //IL_398b: Unknown result type (might be due to invalid IL or missing references)
        //IL_36f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_36fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_3728: Unknown result type (might be due to invalid IL or missing references)
        //IL_372d: Unknown result type (might be due to invalid IL or missing references)
        //IL_375b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3760: Unknown result type (might be due to invalid IL or missing references)
        //IL_378e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3793: Unknown result type (might be due to invalid IL or missing references)
        //IL_37d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_37db: Unknown result type (might be due to invalid IL or missing references)
        //IL_3806: Unknown result type (might be due to invalid IL or missing references)
        //IL_380b: Unknown result type (might be due to invalid IL or missing references)
        //IL_383a: Unknown result type (might be due to invalid IL or missing references)
        //IL_383f: Unknown result type (might be due to invalid IL or missing references)
        //IL_386b: Unknown result type (might be due to invalid IL or missing references)
        //IL_3870: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ab6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ab8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2abd: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ac2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d70: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d72: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d95: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b07: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b39: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b43: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_3b52: Unknown result type (might be due to invalid IL or missing references)
        //IL_2dab: Unknown result type (might be due to invalid IL or missing references)
        //IL_2dad: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e51: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e53: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e76: Unknown result type (might be due to invalid IL or missing references)
        //IL_2929: Unknown result type (might be due to invalid IL or missing references)
        //IL_292e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2930: Unknown result type (might be due to invalid IL or missing references)
        //IL_294f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2959: Unknown result type (might be due to invalid IL or missing references)
        //IL_26dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_26e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2710: Unknown result type (might be due to invalid IL or missing references)
        //IL_2715: Unknown result type (might be due to invalid IL or missing references)
        //IL_2743: Unknown result type (might be due to invalid IL or missing references)
        //IL_2748: Unknown result type (might be due to invalid IL or missing references)
        //IL_2776: Unknown result type (might be due to invalid IL or missing references)
        //IL_277b: Unknown result type (might be due to invalid IL or missing references)
        //IL_27be: Unknown result type (might be due to invalid IL or missing references)
        //IL_27c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_27ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_27f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2822: Unknown result type (might be due to invalid IL or missing references)
        //IL_2827: Unknown result type (might be due to invalid IL or missing references)
        //IL_2853: Unknown result type (might be due to invalid IL or missing references)
        //IL_2858: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bba: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bbf: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bde: Unknown result type (might be due to invalid IL or missing references)
        //IL_2be8: Unknown result type (might be due to invalid IL or missing references)
        //IL_296f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2971: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a16: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a46: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bfe: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c00: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ca5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2caa: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cac: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cc9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cd3: Unknown result type (might be due to invalid IL or missing references)
        float num = shimmerAlpha;
        if (num == 1f)
        {
            ugBackTransition = 0f;
            return;
        }
        if (!BackgroundEnabled)
        {
            OldDrawBackground();
            return;
        }
        Color[] slices = (Color[])(object)new Color[9];
        Stopwatch stopwatch = new Stopwatch();
        stopwatch.Start();
        double num10 = maxTilesY - 330;
        double num20 = (int)((num10 - worldSurface) / 6.0) * 6;
        num10 = worldSurface + num20 - 5.0;
        int num30 = (int)(255f * (1f - gfxQuality) + 140f * gfxQuality);
        int num40 = (int)(200f * (1f - gfxQuality) + 40f * gfxQuality);
        int num50 = 128;
        Vector2 vector = (Vector2)(drawToScreen ? Vector2.Zero : new Vector2((float)offScreenRange, (float)offScreenRange));
        Vector3 vector2 = default(Vector3);
        ((Vector3)(ref vector2))._002Ector(0.9f);
        float num59 = MathHelper.Clamp((screenPosition.Y - (float)worldSurface * 16f) / 300f, 0f, 1f);
        float globalBrightness = Lighting.GlobalBrightness;
        Lighting.GlobalBrightness = globalBrightness * (1f - num59) + 1f * num59;
        float value = (float)((double)(screenPosition.Y - (float)(screenHeight / 2) + 200f) - rockLayer * 16.0) / 300f;
        value = MathHelper.Clamp(value, 0f, 1f);
        int num69 = (int)((screenPosition.X + (float)(screenWidth / 2)) / 16f);
        LoaderManager.Get<UndergroundBackgroundStylesLoader>().ChooseStyle(out var modBG, out var priority);
        int num71 = 3;
        num71 = ((num69 <= caveBackX[0]) ? caveBackStyle[0] : ((num69 <= caveBackX[1]) ? caveBackStyle[1] : ((num69 > caveBackX[2]) ? caveBackStyle[3] : caveBackStyle[2])));
        num71 += 3;
        if (priority == SceneEffectPriority.BiomeLow)
        {
            num71 = modBG;
        }
        if (SceneMetrics.SnowTileCount > SceneMetrics.SnowTileThreshold && (screenPosition.Y + (float)screenHeight + 1200f) / 16f < (float)(maxTilesY - 250))
        {
            num71 = 1;
        }
        if (SceneMetrics.JungleTileCount > SceneMetrics.JungleTileThreshold)
        {
            if (num71 == 1)
            {
                if (SceneMetrics.JungleTileCount > SceneMetrics.SnowTileCount)
                {
                    num71 = 11;
                }
            }
            else
            {
                num71 = 11;
            }
        }
        if (priority == SceneEffectPriority.BiomeMedium)
        {
            num71 = modBG;
        }
        if (WorldGen.oceanDepths((int)(screenPosition.X + (float)(screenHeight / 2)) / 16, (int)(screenPosition.Y + (float)(screenHeight / 2)) / 16))
        {
            num71 = (player[myPlayer].ZoneCorrupt ? 19 : (player[myPlayer].ZoneCrimson ? 21 : ((!player[myPlayer].ZoneHallow) ? 18 : 20)));
        }
        else if ((double)(screenPosition.Y / 16f) > rockLayer + 60.0 && (double)(screenPosition.Y / 16f) < num10 - 60.0)
        {
            if (player[myPlayer].ZoneSnow)
            {
                if (player[myPlayer].ZoneCorrupt)
                {
                    num71 = 15;
                }
                else if (player[myPlayer].ZoneCrimson)
                {
                    num71 = 16;
                }
                else if (player[myPlayer].ZoneHallow)
                {
                    num71 = 17;
                }
            }
            else if (player[myPlayer].ZoneCorrupt)
            {
                num71 = 12;
            }
            else if (player[myPlayer].ZoneCrimson)
            {
                num71 = 13;
            }
            else if (player[myPlayer].ZoneHallow)
            {
                num71 = 14;
            }
        }
        if (player[myPlayer].ZoneGlowshroom)
        {
            num71 = 2;
        }
        if (priority >= SceneEffectPriority.BiomeHigh)
        {
            num71 = modBG;
        }
        if (GlobalBackgroundStyleLoader.loaded)
        {
            GlobalBackgroundStyleLoader.DelegateChooseUndergroundBackgroundStyle[] hookChooseUndergroundBackgroundStyle = GlobalBackgroundStyleLoader.HookChooseUndergroundBackgroundStyle;
            for (int num72 = 0; num72 < hookChooseUndergroundBackgroundStyle.Length; num72++)
            {
                hookChooseUndergroundBackgroundStyle[num72](ref num71);
            }
        }
        if (num71 != undergroundBackground)
        {
            oldUndergroundBackground = undergroundBackground;
            undergroundBackground = num71;
            ugBackTransition = 1f;
        }
        if (num > 0f)
        {
            ugBackTransition = 0f;
        }
        if (ugBackTransition > 0f)
        {
            ugBackTransition -= 0.25f;
        }
        if (ugBackTransition < 0f)
        {
            ugBackTransition = 0f;
        }
        int[] array = new int[7];
        int[] array2 = new int[7];
        for (int i = 0; i < 2; i++)
        {
            int num2 = undergroundBackground;
            if (i == 1)
            {
                num2 = oldUndergroundBackground;
            }
            int[] array3 = new int[7];
            switch (num2)
            {
            case 0:
                array3[0] = 1;
                array3[1] = 2;
                array3[2] = 4;
                array3[3] = 3;
                array3[4] = 6;
                array3[5] = 5;
                break;
            case 1:
                if (iceBackStyle == 0)
                {
                    array3[1] = 33;
                    array3[3] = 32;
                    array3[0] = 40;
                    array3[2] = 34;
                }
                else if (iceBackStyle == 1)
                {
                    array3[1] = 118;
                    array3[3] = 117;
                    array3[0] = 160;
                    array3[2] = 161;
                }
                else if (iceBackStyle == 2)
                {
                    array3[1] = 165;
                    array3[3] = 167;
                    array3[0] = 164;
                    array3[2] = 166;
                }
                else
                {
                    array3[1] = 120;
                    array3[3] = 119;
                    array3[0] = 162;
                    array3[2] = 163;
                }
                array3[4] = 128 + hellBackStyle;
                break;
            case 2:
                array3[0] = 62;
                array3[1] = 63;
                array3[2] = 64;
                array3[3] = 65;
                array3[4] = 143 + hellBackStyle;
                break;
            case 3:
                array3[0] = 66;
                array3[1] = 67;
                array3[2] = 68;
                array3[3] = 69;
                array3[4] = 128 + hellBackStyle;
                break;
            case 4:
                array3[0] = 70;
                array3[1] = 71;
                array3[2] = 68;
                array3[3] = 72;
                array3[4] = 128 + hellBackStyle;
                break;
            case 5:
                array3[0] = 73;
                array3[1] = 74;
                array3[2] = 75;
                array3[3] = 76;
                array3[4] = 131 + hellBackStyle;
                break;
            case 6:
                array3[0] = 77;
                array3[1] = 78;
                array3[2] = 79;
                array3[3] = 80;
                array3[4] = 134 + hellBackStyle;
                break;
            case 7:
                array3[0] = 77;
                array3[1] = 81;
                array3[2] = 79;
                array3[3] = 82;
                array3[4] = 134 + hellBackStyle;
                break;
            case 8:
                array3[0] = 83;
                array3[1] = 84;
                array3[2] = 85;
                array3[3] = 86;
                array3[4] = 137 + hellBackStyle;
                break;
            case 9:
                array3[0] = 83;
                array3[1] = 87;
                array3[2] = 88;
                array3[3] = 89;
                array3[4] = 137 + hellBackStyle;
                break;
            case 10:
                array3[0] = 121;
                array3[1] = 122;
                array3[2] = 123;
                array3[3] = 124;
                array3[4] = 140 + hellBackStyle;
                break;
            case 11:
                if (jungleBackStyle == 0)
                {
                    array3[0] = 153;
                    array3[1] = 147;
                    array3[2] = 148;
                    array3[3] = 149;
                    array3[4] = 150 + hellBackStyle;
                }
                else
                {
                    array3[0] = 146;
                    array3[1] = 154;
                    array3[2] = 155;
                    array3[3] = 156;
                    array3[4] = 157 + hellBackStyle;
                }
                break;
            case 12:
            case 13:
            case 14:
                array3[0] = 66;
                array3[1] = 67;
                array3[2] = 68;
                array3[4] = 128 + hellBackStyle;
                switch (num2)
                {
                case 12:
                    array3[3] = 193 + worldID % 4;
                    break;
                case 13:
                    array3[3] = 188 + worldID % 5;
                    break;
                case 14:
                    array3[3] = 197 + worldID % 3;
                    break;
                }
                break;
            case 15:
            case 16:
            case 17:
                array3[0] = 40;
                array3[1] = 33;
                array3[2] = 34;
                array3[4] = 128 + hellBackStyle;
                switch (num2)
                {
                case 15:
                    array3[3] = 200;
                    break;
                case 16:
                    array3[3] = 201 + worldID % 2;
                    break;
                case 17:
                    array3[3] = 203 + worldID % 4;
                    break;
                }
                break;
            default:
                switch (num2)
                {
                case 18:
                    array3[0] = 290;
                    array3[1] = 291;
                    break;
                case 19:
                    array3[0] = 292;
                    array3[1] = 293;
                    break;
                case 20:
                    array3[0] = 294;
                    array3[1] = 295;
                    break;
                case 21:
                    array3[0] = 296;
                    array3[1] = 297;
                    break;
                }
                break;
            }
            if (hellBackStyle == 0)
            {
                array3[5] = 125;
            }
            if (hellBackStyle == 1)
            {
                array3[5] = 126;
            }
            if (hellBackStyle == 2)
            {
                array3[5] = 127;
            }
            array3[6] = 185 + hellBackStyle;
            LoaderManager.Get<UndergroundBackgroundStylesLoader>().FillTextureArray(num2, array3);
            LoadBackground(array3[0]);
            LoadBackground(array3[1]);
            LoadBackground(array3[2]);
            LoadBackground(array3[3]);
            LoadBackground(array3[4]);
            LoadBackground(array3[5]);
            LoadBackground(array3[6]);
            if (i == 0)
            {
                for (int j = 0; j < 7; j++)
                {
                    array[j] = array3[j];
                }
            }
            else
            {
                for (int k = 0; k < 7; k++)
                {
                    array2[k] = array3[k];
                }
            }
        }
        globalBrightness = 1.2f - 0.2f * value;
        float x = vector2.X;
        float y = vector2.Y;
        float z = vector2.Z;
        num50 = TextureAssets.Background[array[0]].Width() - 32;
        bgParallax = caveParallax;
        bgStartX = (int)(0.0 - Math.IEEERemainder((double)num50 + (double)screenPosition.X * bgParallax, num50) - (double)(num50 / 2)) - (int)vector.X;
        bgLoops = (screenWidth + (int)vector.X * 2) / num50 + 2;
        bgTopY = (int)((float)((int)worldSurface * 16 - 16) - screenPosition.Y + 16f);
        for (int l = 0; l < bgLoops; l++)
        {
            for (int m = 0; m < num50 / 16; m++)
            {
                int num3 = (int)(float)Math.Round(0f - (float)Math.IEEERemainder((float)bgStartX + screenPosition.X, 16.0));
                if (num3 == -8)
                {
                    num3 = 8;
                }
                float num73 = bgStartX + num50 * l + m * 16 + 8;
                float num4 = bgTopY;
                Color color = Lighting.GetColor((int)((num73 + screenPosition.X) / 16f), (int)((screenPosition.Y + num4) / 16f));
                ((Color)(ref color)).R = (byte)((float)(int)((Color)(ref color)).R * x);
                ((Color)(ref color)).G = (byte)((float)(int)((Color)(ref color)).G * y);
                ((Color)(ref color)).B = (byte)((float)(int)((Color)(ref color)).B * z);
                if (num > 0f)
                {
                    color *= 1f - num;
                }
                spriteBatch.Draw(TextureAssets.Background[array[0]].Value, new Vector2((float)(bgStartX + num50 * l + 16 * m + num3), (float)bgTopY) + vector, (Rectangle?)new Rectangle(16 * m + num3 + 16, 0, 16, 16), color);
            }
        }
        if (ugBackTransition > 0f)
        {
            num50 = TextureAssets.Background[array2[0]].Width() - 32;
            bgStartX = (int)(0.0 - Math.IEEERemainder((double)num50 + (double)screenPosition.X * bgParallax, num50) - (double)(num50 / 2)) - (int)vector.X;
            bgLoops = (screenWidth + (int)vector.X * 2) / num50 + 2;
            for (int n = 0; n < bgLoops; n++)
            {
                for (int num5 = 0; num5 < num50 / 16; num5++)
                {
                    int num6 = (int)(float)Math.Round(0f - (float)Math.IEEERemainder((float)bgStartX + screenPosition.X, 16.0));
                    if (num6 == -8)
                    {
                        num6 = 8;
                    }
                    float num74 = bgStartX + num50 * n + num5 * 16 + 8;
                    float num7 = bgTopY;
                    Color color12 = Lighting.GetColor((int)((num74 + screenPosition.X) / 16f), (int)((screenPosition.Y + num7) / 16f));
                    ((Color)(ref color12)).R = (byte)((float)(int)((Color)(ref color12)).R * x);
                    ((Color)(ref color12)).G = (byte)((float)(int)((Color)(ref color12)).G * y);
                    ((Color)(ref color12)).B = (byte)((float)(int)((Color)(ref color12)).B * z);
                    Color color23 = color12;
                    ((Color)(ref color23)).R = (byte)((float)(int)((Color)(ref color23)).R * ugBackTransition);
                    ((Color)(ref color23)).G = (byte)((float)(int)((Color)(ref color23)).G * ugBackTransition);
                    ((Color)(ref color23)).B = (byte)((float)(int)((Color)(ref color23)).B * ugBackTransition);
                    ((Color)(ref color23)).A = (byte)((float)(int)((Color)(ref color23)).A * ugBackTransition);
                    spriteBatch.Draw(TextureAssets.Background[array2[0]].Value, new Vector2((float)(bgStartX + num50 * n + 16 * num5 + num6), (float)bgTopY) + vector, (Rectangle?)new Rectangle(16 * num5 + num6 + 16, 0, 16, 16), color23);
                }
            }
        }
        bool flag = false;
        bool flag2 = false;
        bgTopY = (int)((float)((int)worldSurface * 16) - screenPosition.Y + 16f);
        if (worldSurface * 16.0 <= (double)(screenPosition.Y + (float)screenHeight + (float)offScreenRange))
        {
            bgParallax = caveParallax;
            num50 = TextureAssets.Background[array[1]].Width() - 32;
            bgStartX = (int)(0.0 - Math.IEEERemainder((double)num50 + (double)screenPosition.X * bgParallax, num50) - (double)(num50 / 2)) - (int)vector.X;
            bgLoops = (screenWidth + (int)vector.X * 2) / num50 + 2;
            if (worldSurface * 16.0 < (double)(screenPosition.Y - 16f))
            {
                bgStartY = (int)(Math.IEEERemainder(bgTopY, backgroundHeight[2]) - (double)backgroundHeight[2]);
                bgLoopsY = (screenHeight - bgStartY + (int)vector.Y * 2) / backgroundHeight[2] + 1;
            }
            else
            {
                bgStartY = bgTopY;
                bgLoopsY = (screenHeight - bgTopY + (int)vector.Y * 2) / backgroundHeight[2] + 1;
            }
            if (rockLayer * 16.0 < (double)(Camera.ScaledPosition.Y + 600f))
            {
                bgLoopsY = (int)(rockLayer * 16.0 - (double)screenPosition.Y + 600.0 - (double)bgStartY) / backgroundHeight[2];
                flag2 = true;
            }
            int num8 = (int)(float)Math.Round(0f - (float)Math.IEEERemainder((float)bgStartX + screenPosition.X, 16.0));
            if (num8 == -8)
            {
                num8 = 8;
            }
            for (int num9 = 0; num9 < bgLoops; num9++)
            {
                for (int num11 = 0; num11 < bgLoopsY; num11++)
                {
                    for (int num12 = 0; num12 < num50 / 16; num12++)
                    {
                        for (int num13 = 0; num13 < 6; num13++)
{
                            float num75 = bgStartY + num11 * 96 + num13 * 16 + 8;
                            int num14 = (int)(((float)(bgStartX + num50 * num9 + num12 * 16 + 8) + screenPosition.X) / 16f);
                            int num15 = (int)((num75 + screenPosition.Y) / 16f);
                            Color color27 = Lighting.GetColor(num14, num15);
                            if (!WorldGen.InWorld(num14, num15))
{
                                continue;
                            }
                            if (tile[num14, num15] == null)
{
                                tile[num14, num15] = default(Tile);
                            }
                            if (num == 0f && (((Color)(ref color27)).R > 0 || ((Color)(ref color27)).G > 0 || ((Color)(ref color27)).B > 0))
{
                                if (!drawToScreen)
{
                                    Lighting.GetCornerColors(num14, num15, out var vertices);
                                    vertices.BottomLeftColor = new Color(((Color)(ref vertices.BottomLeftColor)).ToVector3() * vector2);
                                    vertices.BottomRightColor = new Color(((Color)(ref vertices.BottomRightColor)).ToVector3() * vector2);
                                    tileBatch.Draw(TextureAssets.Background[array[1]].Value, new Vector2((float)(bgStartX + num50 * num9 + 16 * num12 + num8), (float)(bgStartY + backgroundHeight[array[1]] * num11 + 16 * num13)) + vector, (Rectangle?)new Rectangle(16 * num12 + num8 + 16, 16 * num13, 16, 16), vertices, Vector2.Zero, 1f, (SpriteEffects)0);
                                }
                                else if ((((Color)(ref color27)).R > num30 || (double)(int)((Color)(ref color27)).G > (double)num30 * 1.1 || (double)(int)((Color)(ref color27)).B > (double)num30 * 1.2) && !tile[num14, num15].active() && WallLightAt(num14, num15) && ugBackTransition == 0f)
{
                                    Lighting.GetColor9Slice(num14, num15, ref slices);
                                    try
{
                                        for (int num16 = 0; num16 < 9; num16++)
{
                                            int num17 = 0;
                                            int num18 = 0;
                                            int width = 4;
                                            int height = 4;
                                            Color color28 = color27;
                                            Color color29 = color27;
                                            switch (num16)
{
                                            case 0:
                                                if (!tile[num14 - 1, num15 - 1].active())
{
                                                    color29 = slices[num16];
                                                }
                                                break;
                                            case 1:
                                                width = 8;
                                                num17 = 4;
                                                if (!tile[num14, num15 - 1].active())
{
                                                    color29 = slices[num16];
                                                }
                                                break;
                                            case 2:
                                                num17 = 12;
                                                if (!tile[num14 + 1, num15 - 1].active())
{
                                                    color29 = slices[num16];
                                                }
                                                break;
                                            case 3:
                                                height = 8;
                                                num18 = 4;
                                                if (!tile[num14 - 1, num15].active())
{
                                                    color29 = slices[num16];
                                                }
                                                break;
                                            case 4:
                                                width = 8;
                                                height = 8;
                                                num17 = 4;
                                                num18 = 4;
                                                break;
                                            case 5:
                                                num17 = 12;
                                                num18 = 4;
                                                height = 8;
                                                if (!tile[num14 + 1, num15].active())
{
                                                    color29 = slices[num16];
                                                }
                                                break;
                                            case 6:
                                                num18 = 12;
                                                if (!tile[num14 - 1, num15 + 1].active())
{
                                                    color29 = slices[num16];
                                                }
                                                break;
                                            case 7:
                                                width = 8;
                                                height = 4;
                                                num17 = 4;
                                                num18 = 12;
                                                if (!tile[num14, num15 + 1].active())
{
                                                    color29 = slices[num16];
                                                }
                                                break;
                                            case 8:
                                                num17 = 12;
                                                num18 = 12;
                                                if (!tile[num14 + 1, num15 + 1].active())
{
                                                    color29 = slices[num16];
                                                }
                                                break;
                                            }
                                            ((Color)(ref color28)).R = (byte)((((Color)(ref color27)).R + ((Color)(ref color29)).R) / 2);
                                            ((Color)(ref color28)).G = (byte)((((Color)(ref color27)).G + ((Color)(ref color29)).G) / 2);
                                            ((Color)(ref color28)).B = (byte)((((Color)(ref color27)).B + ((Color)(ref color29)).B) / 2);
                                            ((Color)(ref color28)).R = (byte)((float)(int)((Color)(ref color28)).R * x);
                                            ((Color)(ref color28)).G = (byte)((float)(int)((Color)(ref color28)).G * y);
                                            ((Color)(ref color28)).B = (byte)((float)(int)((Color)(ref color28)).B * z);
                                            spriteBatch.Draw(TextureAssets.Background[array[1]].Value, new Vector2((float)(bgStartX + num50 * num9 + 16 * num12 + num17 + num8), (float)(bgStartY + backgroundHeight[array[1]] * num11 + 16 * num13 + num18)) + vector, (Rectangle?)new Rectangle(16 * num12 + num17 + num8 + 16, 16 * num13 + num18, width, height), color28);
                                            if (ugBackTransition > 0f)
{
                                                Color color30 = color28;
                                                ((Color)(ref color30)).R = (byte)((float)(int)((Color)(ref color30)).R * ugBackTransition);
                                                ((Color)(ref color30)).G = (byte)((float)(int)((Color)(ref color30)).G * ugBackTransition);
                                                ((Color)(ref color30)).B = (byte)((float)(int)((Color)(ref color30)).B * ugBackTransition);
                                                ((Color)(ref color30)).A = (byte)((float)(int)((Color)(ref color30)).A * ugBackTransition);
                                                spriteBatch.Draw(TextureAssets.Background[array2[1]].Value, new Vector2((float)(bgStartX + num50 * num9 + 16 * num12 + num17 + num8), (float)(bgStartY + backgroundHeight[array2[1]] * num11 + 16 * num13 + num18)) + vector, (Rectangle?)new Rectangle(16 * num12 + num17 + num8 + 16, 16 * num13 + num18, width, height), color30);
                                            }
                                        }
                                    }
                                    catch
{
                                        ((Color)(ref color27)).R = (byte)((float)(int)((Color)(ref color27)).R * x);
                                        ((Color)(ref color27)).G = (byte)((float)(int)((Color)(ref color27)).G * y);
                                        ((Color)(ref color27)).B = (byte)((float)(int)((Color)(ref color27)).B * z);
                                        spriteBatch.Draw(TextureAssets.Background[array[1]].Value, new Vector2((float)(bgStartX + num50 * num9 + 16 * num12 + num8), (float)(bgStartY + backgroundHeight[array[1]] * num11 + 16 * num13)) + vector, (Rectangle?)new Rectangle(16 * num12 + num8 + 16, 16 * num13, 16, 16), color27);
                                    }
                                }
                                else if ((((Color)(ref color27)).R > num40 || (double)(int)((Color)(ref color27)).G > (double)num40 * 1.1 || (double)(int)((Color)(ref color27)).B > (double)num40 * 1.2) && ugBackTransition == 0f)
{
                                    Lighting.GetColor4Slice(num14, num15, ref slices);
                                    for (int num19 = 0; num19 < 4; num19++)
{
                                        int num21 = 0;
                                        int num22 = 0;
                                        Color color31 = color27;
                                        Color color32 = slices[num19];
                                        switch (num19)
{
                                        case 1:
                                            num21 = 8;
                                            break;
                                        case 2:
                                            num22 = 8;
                                            break;
                                        case 3:
                                            num21 = 8;
                                            num22 = 8;
                                            break;
                                        }
                                        ((Color)(ref color31)).R = (byte)((((Color)(ref color27)).R + ((Color)(ref color32)).R) / 2);
                                        ((Color)(ref color31)).G = (byte)((((Color)(ref color27)).G + ((Color)(ref color32)).G) / 2);
                                        ((Color)(ref color31)).B = (byte)((((Color)(ref color27)).B + ((Color)(ref color32)).B) / 2);
                                        ((Color)(ref color31)).R = (byte)((float)(int)((Color)(ref color31)).R * x);
                                        ((Color)(ref color31)).G = (byte)((float)(int)((Color)(ref color31)).G * y);
                                        ((Color)(ref color31)).B = (byte)((float)(int)((Color)(ref color31)).B * z);
                                        spriteBatch.Draw(TextureAssets.Background[array[1]].Value, new Vector2((float)(bgStartX + num50 * num9 + 16 * num12 + num21 + num8), (float)(bgStartY + backgroundHeight[array[1]] * num11 + 16 * num13 + num22)) + vector, (Rectangle?)new Rectangle(16 * num12 + num21 + num8 + 16, 16 * num13 + num22, 8, 8), color31);
                                        if (ugBackTransition > 0f)
{
                                            Color color2 = color31;
                                            ((Color)(ref color2)).R = (byte)((float)(int)((Color)(ref color2)).R * ugBackTransition);
                                            ((Color)(ref color2)).G = (byte)((float)(int)((Color)(ref color2)).G * ugBackTransition);
                                            ((Color)(ref color2)).B = (byte)((float)(int)((Color)(ref color2)).B * ugBackTransition);
                                            ((Color)(ref color2)).A = (byte)((float)(int)((Color)(ref color2)).A * ugBackTransition);
                                            spriteBatch.Draw(TextureAssets.Background[array2[1]].Value, new Vector2((float)(bgStartX + num50 * num9 + 16 * num12 + num21 + num8), (float)(bgStartY + backgroundHeight[array2[1]] * num11 + 16 * num13 + num22)) + vector, (Rectangle?)new Rectangle(16 * num12 + num21 + num8 + 16, 16 * num13 + num22, 8, 8), color2);
                                        }
                                    }
                                }
                                else
{
                                    ((Color)(ref color27)).R = (byte)((float)(int)((Color)(ref color27)).R * x);
                                    ((Color)(ref color27)).G = (byte)((float)(int)((Color)(ref color27)).G * y);
                                    ((Color)(ref color27)).B = (byte)((float)(int)((Color)(ref color27)).B * z);
                                    spriteBatch.Draw(TextureAssets.Background[array[1]].Value, new Vector2((float)(bgStartX + num50 * num9 + 16 * num12 + num8), (float)(bgStartY + backgroundHeight[array[1]] * num11 + 16 * num13)) + vector, (Rectangle?)new Rectangle(16 * num12 + num8 + 16, 16 * num13, 16, 16), color27);
                                    if (ugBackTransition > 0f)
{
                                        Color color3 = color27;
                                        ((Color)(ref color3)).R = (byte)((float)(int)((Color)(ref color3)).R * ugBackTransition);
                                        ((Color)(ref color3)).G = (byte)((float)(int)((Color)(ref color3)).G * ugBackTransition);
                                        ((Color)(ref color3)).B = (byte)((float)(int)((Color)(ref color3)).B * ugBackTransition);
                                        ((Color)(ref color3)).A = (byte)((float)(int)((Color)(ref color3)).A * ugBackTransition);
                                        spriteBatch.Draw(TextureAssets.Background[array2[1]].Value, new Vector2((float)(bgStartX + num50 * num9 + 16 * num12 + num8), (float)(bgStartY + backgroundHeight[array2[1]] * num11 + 16 * num13)) + vector, (Rectangle?)new Rectangle(16 * num12 + num8 + 16, 16 * num13, 16, 16), color3);
                                    }
                                }
                            }
                            else
{
                                ((Color)(ref color27)).R = (byte)((float)(int)((Color)(ref color27)).R * x);
                                ((Color)(ref color27)).G = (byte)((float)(int)((Color)(ref color27)).G * y);
                                ((Color)(ref color27)).B = (byte)((float)(int)((Color)(ref color27)).B * z);
                                if (num > 0f)
{
                                    color27 *= 1f - num;
                                }
                                spriteBatch.Draw(TextureAssets.Background[array[1]].Value, new Vector2((float)(bgStartX + num50 * num9 + 16 * num12 + num8), (float)(bgStartY + backgroundHeight[array[1]] * num11 + 16 * num13)) + vector, (Rectangle?)new Rectangle(16 * num12 + num8 + 16, 16 * num13, 16, 16), color27);
                            }
                        }
                    }
                }
            }
            if (ugBackTransition > 0f)
            {
                num50 = TextureAssets.Background[array2[1]].Width() - 32;
                bgStartX = (int)(0.0 - Math.IEEERemainder((double)num50 + (double)screenPosition.X * bgParallax, num50) - (double)(num50 / 2)) - (int)vector.X;
                bgLoops = (screenWidth + (int)vector.X * 2) / num50 + 2;
                num8 = (int)(float)Math.Round(0f - (float)Math.IEEERemainder((float)bgStartX + screenPosition.X, 16.0));
                if (num8 == -8)
                {
                    num8 = 8;
                }
                for (int num23 = 0; num23 < bgLoops; num23++)
                {
                    for (int num24 = 0; num24 < bgLoopsY; num24++)
                    {
                        for (int num25 = 0; num25 < num50 / 16; num25++)
{
                            for (int num26 = 0; num26 < 6; num26++)
{
                                float num76 = bgStartY + num24 * 96 + num26 * 16 + 8;
                                int num27 = (int)(((float)(bgStartX + num50 * num23 + num25 * 16 + 8) + screenPosition.X) / 16f);
                                int num28 = (int)((num76 + screenPosition.Y) / 16f);
                                if (WorldGen.InWorld(num27, num28))
{
                                    Color color4 = Lighting.GetColor(num27, num28);
                                    if (tile[num27, num28] == null)
{
                                        tile[num27, num28] = default(Tile);
                                    }
                                    if (((Color)(ref color4)).R > 0 || ((Color)(ref color4)).G > 0 || ((Color)(ref color4)).B > 0)
{
                                        Lighting.GetCornerColors(num27, num28, out var vertices2, ugBackTransition);
                                        byte a = (byte)(255f * ugBackTransition);
                                        ((Color)(ref vertices2.BottomLeftColor)).A = a;
                                        ((Color)(ref vertices2.BottomRightColor)).A = a;
                                        ((Color)(ref vertices2.TopLeftColor)).A = a;
                                        ((Color)(ref vertices2.TopRightColor)).A = a;
                                        tileBatch.Draw(TextureAssets.Background[array2[1]].Value, new Vector2((float)(bgStartX + num50 * num23 + 16 * num25 + num8), (float)(bgStartY + backgroundHeight[array2[1]] * num24 + 16 * num26)) + vector, (Rectangle?)new Rectangle(16 * num25 + num8 + 16, 16 * num26, 16, 16), vertices2, Vector2.Zero, 1f, (SpriteEffects)0);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            num50 = 128;
            if (flag2)
            {
                bgParallax = caveParallax;
                bgStartX = (int)(0.0 - Math.IEEERemainder((double)num50 + (double)screenPosition.X * bgParallax, num50) - (double)(num50 / 2)) - (int)vector.X;
                bgLoops = (screenWidth + (int)vector.X * 2) / num50 + 2;
                bgTopY = bgStartY + bgLoopsY * backgroundHeight[2];
                if (bgTopY > -32)
                {
                    for (int num29 = 0; num29 < bgLoops; num29++)
                    {
                        for (int num31 = 0; num31 < num50 / 16; num31++)
{
                            float num77 = bgStartX + num50 * num29 + num31 * 16 + 8;
                            float num32 = bgTopY;
                            Color color5 = Lighting.GetColor((int)((num77 + screenPosition.X) / 16f), (int)((screenPosition.Y + num32) / 16f));
                            ((Color)(ref color5)).R = (byte)((float)(int)((Color)(ref color5)).R * x);
                            ((Color)(ref color5)).G = (byte)((float)(int)((Color)(ref color5)).G * y);
                            ((Color)(ref color5)).B = (byte)((float)(int)((Color)(ref color5)).B * z);
                            if (num > 0f)
{
                                color5 *= 1f - num;
                            }
                            spriteBatch.Draw(TextureAssets.Background[array[2]].Value, new Vector2((float)(bgStartX + num50 * num29 + 16 * num31 + num8), (float)bgTopY) + vector, (Rectangle?)new Rectangle(16 * num31 + num8 + 16, 0, 16, 16), color5);
                            if (ugBackTransition > 0f)
{
                                Color color6 = color5;
                                ((Color)(ref color6)).R = (byte)((float)(int)((Color)(ref color6)).R * ugBackTransition);
                                ((Color)(ref color6)).G = (byte)((float)(int)((Color)(ref color6)).G * ugBackTransition);
                                ((Color)(ref color6)).B = (byte)((float)(int)((Color)(ref color6)).B * ugBackTransition);
                                ((Color)(ref color6)).A = (byte)((float)(int)((Color)(ref color6)).A * ugBackTransition);
                                spriteBatch.Draw(TextureAssets.Background[array2[2]].Value, new Vector2((float)(bgStartX + num50 * num29 + 16 * num31 + num8), (float)bgTopY) + vector, (Rectangle?)new Rectangle(16 * num31 + num8 + 16, 0, 16, 16), color6);
                            }
                        }
                    }
                }
            }
        }
        if (num10 * 16.0 <= (double)(screenPosition.Y + (float)screenHeight) && (!remixWorld || maxTilesX >= 5000))
        {
            int y2 = 0;
            int x2 = 0;
            int num33 = screenHeight + 200;
            int width2 = screenWidth + 100;
            if ((float)UnderworldLayer * 16f < screenPosition.Y + (float)screenHeight)
            {
                int num34 = (int)(hellBlackBoxBottom - screenPosition.Y + vector.Y);
                if (num33 > num34)
                {
                    num33 = num34;
                }
            }
            spriteBatch.Draw(TextureAssets.BlackTile.Value, new Rectangle(x2, y2, width2, num33), new Color(0, 0, 0));
        }
        hellBlackBoxBottom = screenPosition.Y + (float)screenHeight + 100f;
        bgTopY = (int)((float)((int)rockLayer * 16) - screenPosition.Y + 16f + 600f - 8f);
        if (rockLayer * 16.0 <= (double)(screenPosition.Y + (float)screenHeight))
        {
            bgParallax = caveParallax;
            bgStartX = (int)(0.0 - Math.IEEERemainder((double)num50 + (double)screenPosition.X * bgParallax, num50) - (double)(num50 / 2)) - (int)vector.X;
            bgLoops = (screenWidth + (int)vector.X * 2) / num50 + 2;
            if (rockLayer * 16.0 + (double)screenHeight < (double)(screenPosition.Y - 16f))
            {
                bgStartY = (int)(Math.IEEERemainder(bgTopY, backgroundHeight[3]) - (double)backgroundHeight[3]);
                bgLoopsY = (screenHeight - bgStartY + (int)vector.Y * 2) / backgroundHeight[2] + 1;
            }
            else
            {
                bgStartY = bgTopY;
                bgLoopsY = (screenHeight - bgTopY + (int)vector.Y * 2) / backgroundHeight[2] + 1;
            }
            if (num10 * 16.0 < (double)(screenPosition.Y + (float)screenHeight))
            {
                bgLoopsY = (int)(num10 * 16.0 - (double)screenPosition.Y + 600.0 - (double)bgStartY) / backgroundHeight[2];
                flag = true;
            }
            int num35 = (int)(float)Math.Round(0f - (float)Math.IEEERemainder((float)bgStartX + screenPosition.X, 16.0));
            if (num35 == -8)
            {
                num35 = 8;
            }
            for (int num36 = 0; num36 < bgLoops; num36++)
            {
                for (int num37 = 0; num37 < bgLoopsY; num37++)
                {
                    for (int num38 = 0; num38 < num50 / 16; num38++)
                    {
                        for (int num39 = 0; num39 < 6; num39++)
{
                            float num78 = bgStartY + num37 * 96 + num39 * 16 + 8;
                            int num41 = (int)(((float)(bgStartX + num50 * num36 + num38 * 16 + 8) + screenPosition.X) / 16f);
                            int num42 = (int)((num78 + screenPosition.Y) / 16f);
                            if (!WorldGen.InWorld(num41, num42, 1))
{
                                continue;
                            }
                            Color color7 = Lighting.GetColor(num41, num42);
                            if ((!ShouldDrawBackgroundTileAt(num41, num42) && ((Color)(ref color7)).R != 0 && ((Color)(ref color7)).G != 0 && ((Color)(ref color7)).B != 0) || (((Color)(ref color7)).R <= 0 && ((Color)(ref color7)).G <= 0 && ((Color)(ref color7)).B <= 0) || (!WallLightAt(num41, num42) && caveParallax == 0f))
{
                                continue;
                            }
                            if (num == 0f && Lighting.NotRetro && ((Color)(ref color7)).R < 230 && ((Color)(ref color7)).G < 230 && ((Color)(ref color7)).B < 230 && ugBackTransition == 0f)
{
                                if ((((Color)(ref color7)).R > num30 || (double)(int)((Color)(ref color7)).G > (double)num30 * 1.1 || (double)(int)((Color)(ref color7)).B > (double)num30 * 1.2) && !tile[num41, num42].active())
{
                                    Lighting.GetColor9Slice(num41, num42, ref slices);
                                    for (int num43 = 0; num43 < 9; num43++)
{
                                        int num44 = 0;
                                        int num45 = 0;
                                        int width3 = 4;
                                        int height2 = 4;
                                        Color color8 = color7;
                                        Color color9 = color7;
                                        switch (num43)
{
                                        case 0:
                                            if (!tile[num41 - 1, num42 - 1].active())
{
                                                color9 = slices[num43];
                                            }
                                            break;
                                        case 1:
                                            width3 = 8;
                                            num44 = 4;
                                            if (!tile[num41, num42 - 1].active())
{
                                                color9 = slices[num43];
                                            }
                                            break;
                                        case 2:
                                            num44 = 12;
                                            if (!tile[num41 + 1, num42 - 1].active())
{
                                                color9 = slices[num43];
                                            }
                                            break;
                                        case 3:
                                            height2 = 8;
                                            num45 = 4;
                                            if (!tile[num41 - 1, num42].active())
{
                                                color9 = slices[num43];
                                            }
                                            break;
                                        case 4:
                                            width3 = 8;
                                            height2 = 8;
                                            num44 = 4;
                                            num45 = 4;
                                            break;
                                        case 5:
                                            num44 = 12;
                                            num45 = 4;
                                            height2 = 8;
                                            if (!tile[num41 + 1, num42].active())
{
                                                color9 = slices[num43];
                                            }
                                            break;
                                        case 6:
                                            num45 = 12;
                                            if (!tile[num41 - 1, num42 + 1].active())
{
                                                color9 = slices[num43];
                                            }
                                            break;
                                        case 7:
                                            width3 = 8;
                                            height2 = 4;
                                            num44 = 4;
                                            num45 = 12;
                                            if (!tile[num41, num42 + 1].active())
{
                                                color9 = slices[num43];
                                            }
                                            break;
                                        case 8:
                                            num44 = 12;
                                            num45 = 12;
                                            if (!tile[num41 + 1, num42 + 1].active())
{
                                                color9 = slices[num43];
                                            }
                                            break;
                                        }
                                        ((Color)(ref color8)).R = (byte)((((Color)(ref color7)).R + ((Color)(ref color9)).R) / 2);
                                        ((Color)(ref color8)).G = (byte)((((Color)(ref color7)).G + ((Color)(ref color9)).G) / 2);
                                        ((Color)(ref color8)).B = (byte)((((Color)(ref color7)).B + ((Color)(ref color9)).B) / 2);
                                        ((Color)(ref color8)).R = (byte)((float)(int)((Color)(ref color8)).R * x);
                                        ((Color)(ref color8)).G = (byte)((float)(int)((Color)(ref color8)).G * y);
                                        ((Color)(ref color8)).B = (byte)((float)(int)((Color)(ref color8)).B * z);
                                        spriteBatch.Draw(TextureAssets.Background[array[3]].Value, new Vector2((float)(bgStartX + num50 * num36 + 16 * num38 + num44 + num35), (float)(bgStartY + backgroundHeight[array[3]] * num37 + 16 * num39 + num45)) + vector, (Rectangle?)new Rectangle(16 * num38 + num44 + num35 + 16, 16 * num39 + num45, width3, height2), color8);
                                        if (ugBackTransition > 0f)
{
                                            Color color10 = color8;
                                            ((Color)(ref color10)).R = (byte)((float)(int)((Color)(ref color10)).R * ugBackTransition);
                                            ((Color)(ref color10)).G = (byte)((float)(int)((Color)(ref color10)).G * ugBackTransition);
                                            ((Color)(ref color10)).B = (byte)((float)(int)((Color)(ref color10)).B * ugBackTransition);
                                            ((Color)(ref color10)).A = (byte)((float)(int)((Color)(ref color10)).A * ugBackTransition);
                                            spriteBatch.Draw(TextureAssets.Background[array2[3]].Value, new Vector2((float)(bgStartX + num50 * num36 + 16 * num38 + num44 + num35), (float)(bgStartY + backgroundHeight[array2[3]] * num37 + 16 * num39 + num45)) + vector, (Rectangle?)new Rectangle(16 * num38 + num44 + num35 + 16, 16 * num39 + num45, width3, height2), color10);
                                        }
                                    }
                                }
                                else if (((Color)(ref color7)).R > num40 || (double)(int)((Color)(ref color7)).G > (double)num40 * 1.1 || (double)(int)((Color)(ref color7)).B > (double)num40 * 1.2)
{
                                    Lighting.GetColor4Slice(num41, num42, ref slices);
                                    for (int num46 = 0; num46 < 4; num46++)
{
                                        int num47 = 0;
                                        int num48 = 0;
                                        Color color11 = color7;
                                        Color color13 = slices[num46];
                                        switch (num46)
{
                                        case 1:
                                            num47 = 8;
                                            break;
                                        case 2:
                                            num48 = 8;
                                            break;
                                        case 3:
                                            num47 = 8;
                                            num48 = 8;
                                            break;
                                        }
                                        ((Color)(ref color11)).R = (byte)((((Color)(ref color7)).R + ((Color)(ref color13)).R) / 2);
                                        ((Color)(ref color11)).G = (byte)((((Color)(ref color7)).G + ((Color)(ref color13)).G) / 2);
                                        ((Color)(ref color11)).B = (byte)((((Color)(ref color7)).B + ((Color)(ref color13)).B) / 2);
                                        ((Color)(ref color11)).R = (byte)((float)(int)((Color)(ref color11)).R * x);
                                        ((Color)(ref color11)).G = (byte)((float)(int)((Color)(ref color11)).G * y);
                                        ((Color)(ref color11)).B = (byte)((float)(int)((Color)(ref color11)).B * z);
                                        spriteBatch.Draw(TextureAssets.Background[array[3]].Value, new Vector2((float)(bgStartX + num50 * num36 + 16 * num38 + num47 + num35), (float)(bgStartY + backgroundHeight[array[3]] * num37 + 16 * num39 + num48)) + vector, (Rectangle?)new Rectangle(16 * num38 + num47 + num35 + 16, 16 * num39 + num48, 8, 8), color11);
                                        if (ugBackTransition > 0f)
{
                                            Color color14 = color11;
                                            ((Color)(ref color14)).R = (byte)((float)(int)((Color)(ref color14)).R * ugBackTransition);
                                            ((Color)(ref color14)).G = (byte)((float)(int)((Color)(ref color14)).G * ugBackTransition);
                                            ((Color)(ref color14)).B = (byte)((float)(int)((Color)(ref color14)).B * ugBackTransition);
                                            ((Color)(ref color14)).A = (byte)((float)(int)((Color)(ref color14)).A * ugBackTransition);
                                            spriteBatch.Draw(TextureAssets.Background[array2[3]].Value, new Vector2((float)(bgStartX + num50 * num36 + 16 * num38 + num47 + num35), (float)(bgStartY + backgroundHeight[array2[3]] * num37 + 16 * num39 + num48)) + vector, (Rectangle?)new Rectangle(16 * num38 + num47 + num35 + 16, 16 * num39 + num48, 8, 8), color14);
                                        }
                                    }
                                }
                                else
{
                                    ((Color)(ref color7)).R = (byte)((float)(int)((Color)(ref color7)).R * x);
                                    ((Color)(ref color7)).G = (byte)((float)(int)((Color)(ref color7)).G * y);
                                    ((Color)(ref color7)).B = (byte)((float)(int)((Color)(ref color7)).B * z);
                                    spriteBatch.Draw(TextureAssets.Background[array[3]].Value, new Vector2((float)(bgStartX + num50 * num36 + 16 * num38 + num35), (float)(bgStartY + backgroundHeight[array[3]] * num37 + 16 * num39)) + vector, (Rectangle?)new Rectangle(16 * num38 + num35 + 16, 16 * num39, 16, 16), color7);
                                    if (ugBackTransition > 0f)
{
                                        Color color15 = color7;
                                        ((Color)(ref color15)).R = (byte)((float)(int)((Color)(ref color15)).R * ugBackTransition);
                                        ((Color)(ref color15)).G = (byte)((float)(int)((Color)(ref color15)).G * ugBackTransition);
                                        ((Color)(ref color15)).B = (byte)((float)(int)((Color)(ref color15)).B * ugBackTransition);
                                        ((Color)(ref color15)).A = (byte)((float)(int)((Color)(ref color15)).A * ugBackTransition);
                                        spriteBatch.Draw(TextureAssets.Background[array2[3]].Value, new Vector2((float)(bgStartX + num50 * num36 + 16 * num38 + num35), (float)(bgStartY + backgroundHeight[array2[3]] * num37 + 16 * num39)) + vector, (Rectangle?)new Rectangle(16 * num38 + num35 + 16, 16 * num39, 16, 16), color15);
                                    }
                                }
                            }
                            else
{
                                ((Color)(ref color7)).R = (byte)((float)(int)((Color)(ref color7)).R * x);
                                ((Color)(ref color7)).G = (byte)((float)(int)((Color)(ref color7)).G * y);
                                ((Color)(ref color7)).B = (byte)((float)(int)((Color)(ref color7)).B * z);
                                if (num > 0f)
{
                                    color7 *= 1f - num;
                                }
                                spriteBatch.Draw(TextureAssets.Background[array[3]].Value, new Vector2((float)(bgStartX + num50 * num36 + 16 * num38 + num35), (float)(bgStartY + backgroundHeight[array[3]] * num37 + 16 * num39)) + vector, (Rectangle?)new Rectangle(16 * num38 + num35 + 16, 16 * num39, 16, 16), color7);
                                if (ugBackTransition > 0f)
{
                                    Color color16 = color7;
                                    ((Color)(ref color16)).R = (byte)((float)(int)((Color)(ref color16)).R * ugBackTransition);
                                    ((Color)(ref color16)).G = (byte)((float)(int)((Color)(ref color16)).G * ugBackTransition);
                                    ((Color)(ref color16)).B = (byte)((float)(int)((Color)(ref color16)).B * ugBackTransition);
                                    ((Color)(ref color16)).A = (byte)((float)(int)((Color)(ref color16)).A * ugBackTransition);
                                    spriteBatch.Draw(TextureAssets.Background[array2[3]].Value, new Vector2((float)(bgStartX + num50 * num36 + 16 * num38 + num35), (float)(bgStartY + backgroundHeight[array2[3]] * num37 + 16 * num39)) + vector, (Rectangle?)new Rectangle(16 * num38 + num35 + 16, 16 * num39, 16, 16), color16);
                                }
                            }
                        }
                    }
                }
            }
            num50 = 128;
            if (flag)
            {
                bgParallax = caveParallax;
                bgStartX = (int)(0.0 - Math.IEEERemainder((double)num50 + (double)screenPosition.X * bgParallax, num50) - (double)(num50 / 2)) - (int)vector.X;
                bgLoops = (screenWidth + (int)vector.X * 2) / num50 + 2;
                bgTopY = bgStartY + bgLoopsY * backgroundHeight[2];
                for (int num49 = 0; num49 < bgLoops; num49++)
                {
                    for (int num51 = 0; num51 < num50 / 16; num51++)
                    {
                        float num79 = bgStartX + num50 * num49 + num51 * 16 + 8;
                        float num52 = bgTopY;
                        Color color17 = Lighting.GetColor((int)((num79 + screenPosition.X) / 16f), (int)((screenPosition.Y + num52) / 16f));
                        ((Color)(ref color17)).R = (byte)((float)(int)((Color)(ref color17)).R * x);
                        ((Color)(ref color17)).G = (byte)((float)(int)((Color)(ref color17)).G * y);
                        ((Color)(ref color17)).B = (byte)((float)(int)((Color)(ref color17)).B * z);
                        spriteBatch.Draw(TextureAssets.Background[array[4]].Value, new Vector2((float)(bgStartX + num50 * num49 + 16 * num51 + num35), (float)bgTopY) + vector, (Rectangle?)new Rectangle(16 * num51 + num35 + 16, magmaBGFrame * 16, 16, 16), color17);
                        if (ugBackTransition > 0f)
{
                            Color color18 = color17;
                            ((Color)(ref color18)).R = (byte)((float)(int)((Color)(ref color18)).R * ugBackTransition);
                            ((Color)(ref color18)).G = (byte)((float)(int)((Color)(ref color18)).G * ugBackTransition);
                            ((Color)(ref color18)).B = (byte)((float)(int)((Color)(ref color18)).B * ugBackTransition);
                            ((Color)(ref color18)).A = (byte)((float)(int)((Color)(ref color18)).A * ugBackTransition);
                            spriteBatch.Draw(TextureAssets.Background[array2[4]].Value, new Vector2((float)(bgStartX + num50 * num49 + 16 * num51 + num35), (float)bgTopY) + vector, (Rectangle?)new Rectangle(16 * num51 + num35 + 16, magmaBGFrame * 16, 16, 16), color18);
                        }
                    }
                }
            }
        }
        bgTopY = (int)((float)((int)num10 * 16) - screenPosition.Y + 16f + 600f) - 8;
        bool flag3 = false;
        if (num10 * 16.0 <= (double)(screenPosition.Y + (float)screenHeight))
        {
            bgStartX = (int)(0.0 - Math.IEEERemainder((double)num50 + (double)screenPosition.X * bgParallax, num50) - (double)(num50 / 2)) - (int)vector.X;
            bgLoops = (screenWidth + (int)vector.X * 2) / num50 + 2;
            if (num10 * 16.0 + (double)screenHeight < (double)(screenPosition.Y - 16f))
            {
                bgStartY = (int)(Math.IEEERemainder(bgTopY, backgroundHeight[2]) - (double)backgroundHeight[2]);
                bgLoopsY = (screenHeight - bgStartY + (int)vector.Y * 2) / backgroundHeight[2] + 1;
            }
            else
            {
                bgStartY = bgTopY;
                bgLoopsY = (screenHeight - bgTopY + (int)vector.Y * 2) / backgroundHeight[2] + 1;
            }
            if ((float)UnderworldLayer * 16f < screenPosition.Y + (float)screenHeight)
            {
                bgLoopsY = (int)Math.Ceiling(((float)UnderworldLayer * 16f - screenPosition.Y - (float)bgStartY) / (float)backgroundHeight[2]);
                flag3 = true;
            }
            num30 = (int)((double)num30 * 1.5);
            num40 = (int)((double)num40 * 1.5);
            int num53 = (int)(float)Math.Round(0f - (float)Math.IEEERemainder((float)bgStartX + screenPosition.X, 16.0));
            if (num53 == -8)
            {
                num53 = 8;
            }
            for (int num54 = 0; num54 < bgLoops; num54++)
            {
                for (int num55 = 0; num55 < bgLoopsY; num55++)
                {
                    for (int num56 = 0; num56 < num50 / 16; num56++)
                    {
                        for (int num57 = 0; num57 < 6; num57++)
{
                            float num80 = bgStartY + num55 * 96 + num57 * 16 + 8;
                            int num58 = (int)(((float)(bgStartX + num50 * num54 + num56 * 16 + 8) + screenPosition.X) / 16f);
                            int num60 = (int)((num80 + screenPosition.Y) / 16f);
                            if (!WorldGen.InWorld(num58, num60, 1))
{
                                continue;
                            }
                            Color color19 = Lighting.GetColor(num58, num60);
                            if ((!ShouldDrawBackgroundTileAt(num58, num60) && ((Color)(ref color19)).R != 0 && ((Color)(ref color19)).G != 0 && ((Color)(ref color19)).B != 0) || (((Color)(ref color19)).R <= 0 && ((Color)(ref color19)).G <= 0 && ((Color)(ref color19)).B <= 0 && num60 <= maxTilesY - 300) || (!WallLightAt(num58, num60) && caveParallax == 0f))
{
                                continue;
                            }
                            if (Lighting.NotRetro && ((Color)(ref color19)).R < 230 && ((Color)(ref color19)).G < 230 && ((Color)(ref color19)).B < 230)
{
                                if ((((Color)(ref color19)).R > num30 || (double)(int)((Color)(ref color19)).G > (double)num30 * 1.1 || (double)(int)((Color)(ref color19)).B > (double)num30 * 1.2) && !tile[num58, num60].active())
{
                                    Lighting.GetColor9Slice(num58, num60, ref slices);
                                    for (int num61 = 0; num61 < 9; num61++)
{
                                        int num62 = 0;
                                        int num63 = 0;
                                        int width4 = 4;
                                        int height3 = 4;
                                        Color color20 = color19;
                                        Color color21 = color19;
                                        switch (num61)
{
                                        case 0:
                                            if (!tile[num58 - 1, num60 - 1].active())
{
                                                color21 = slices[num61];
                                            }
                                            break;
                                        case 1:
                                            width4 = 8;
                                            num62 = 4;
                                            if (!tile[num58, num60 - 1].active())
{
                                                color21 = slices[num61];
                                            }
                                            break;
                                        case 2:
                                            num62 = 12;
                                            if (!tile[num58 + 1, num60 - 1].active())
{
                                                color21 = slices[num61];
                                            }
                                            break;
                                        case 3:
                                            height3 = 8;
                                            num63 = 4;
                                            if (!tile[num58 - 1, num60].active())
{
                                                color21 = slices[num61];
                                            }
                                            break;
                                        case 4:
                                            width4 = 8;
                                            height3 = 8;
                                            num62 = 4;
                                            num63 = 4;
                                            break;
                                        case 5:
                                            num62 = 12;
                                            num63 = 4;
                                            height3 = 8;
                                            if (!tile[num58 + 1, num60].active())
{
                                                color21 = slices[num61];
                                            }
                                            break;
                                        case 6:
                                            num63 = 12;
                                            if (!tile[num58 - 1, num60 + 1].active())
{
                                                color21 = slices[num61];
                                            }
                                            break;
                                        case 7:
                                            width4 = 8;
                                            height3 = 4;
                                            num62 = 4;
                                            num63 = 12;
                                            if (!tile[num58, num60 + 1].active())
{
                                                color21 = slices[num61];
                                            }
                                            break;
                                        case 8:
                                            num62 = 12;
                                            num63 = 12;
                                            if (!tile[num58 + 1, num60 + 1].active())
{
                                                color21 = slices[num61];
                                            }
                                            break;
                                        }
                                        ((Color)(ref color20)).R = (byte)((((Color)(ref color19)).R + ((Color)(ref color21)).R) / 2);
                                        ((Color)(ref color20)).G = (byte)((((Color)(ref color19)).G + ((Color)(ref color21)).G) / 2);
                                        ((Color)(ref color20)).B = (byte)((((Color)(ref color19)).B + ((Color)(ref color21)).B) / 2);
                                        ((Color)(ref color20)).R = (byte)((float)(int)((Color)(ref color20)).R * x);
                                        ((Color)(ref color20)).G = (byte)((float)(int)((Color)(ref color20)).G * y);
                                        ((Color)(ref color20)).B = (byte)((float)(int)((Color)(ref color20)).B * z);
                                        spriteBatch.Draw(TextureAssets.Background[array[5]].Value, new Vector2((float)(bgStartX + num50 * num54 + 16 * num56 + num62 + num53), (float)(bgStartY + backgroundHeight[2] * num55 + 16 * num57 + num63)) + vector, (Rectangle?)new Rectangle(16 * num56 + num62 + num53 + 16, 16 * num57 + backgroundHeight[2] * magmaBGFrame + num63, width4, height3), color20, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                                    }
                                }
                                else if (((Color)(ref color19)).R > num40 || (double)(int)((Color)(ref color19)).G > (double)num40 * 1.1 || (double)(int)((Color)(ref color19)).B > (double)num40 * 1.2)
{
                                    Lighting.GetColor4Slice(num58, num60, ref slices);
                                    for (int num64 = 0; num64 < 4; num64++)
{
                                        int num65 = 0;
                                        int num66 = 0;
                                        Color color22 = color19;
                                        Color color24 = slices[num64];
                                        switch (num64)
{
                                        case 1:
                                            num65 = 8;
                                            break;
                                        case 2:
                                            num66 = 8;
                                            break;
                                        case 3:
                                            num65 = 8;
                                            num66 = 8;
                                            break;
                                        }
                                        ((Color)(ref color22)).R = (byte)((((Color)(ref color19)).R + ((Color)(ref color24)).R) / 2);
                                        ((Color)(ref color22)).G = (byte)((((Color)(ref color19)).G + ((Color)(ref color24)).G) / 2);
                                        ((Color)(ref color22)).B = (byte)((((Color)(ref color19)).B + ((Color)(ref color24)).B) / 2);
                                        ((Color)(ref color22)).R = (byte)((float)(int)((Color)(ref color22)).R * x);
                                        ((Color)(ref color22)).G = (byte)((float)(int)((Color)(ref color22)).G * y);
                                        ((Color)(ref color22)).B = (byte)((float)(int)((Color)(ref color22)).B * z);
                                        spriteBatch.Draw(TextureAssets.Background[array[5]].Value, new Vector2((float)(bgStartX + num50 * num54 + 16 * num56 + num65 + num53), (float)(bgStartY + backgroundHeight[2] * num55 + 16 * num57 + num66)) + vector, (Rectangle?)new Rectangle(16 * num56 + num65 + num53 + 16, 16 * num57 + backgroundHeight[2] * magmaBGFrame + num66, 8, 8), color22, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                                    }
                                }
                                else
{
                                    ((Color)(ref color19)).R = (byte)((float)(int)((Color)(ref color19)).R * x);
                                    ((Color)(ref color19)).G = (byte)((float)(int)((Color)(ref color19)).G * y);
                                    ((Color)(ref color19)).B = (byte)((float)(int)((Color)(ref color19)).B * z);
                                    spriteBatch.Draw(TextureAssets.Background[array[5]].Value, new Vector2((float)(bgStartX + num50 * num54 + 16 * num56 + num53), (float)(bgStartY + backgroundHeight[2] * num55 + 16 * num57)) + vector, (Rectangle?)new Rectangle(16 * num56 + num53 + 16, 16 * num57 + backgroundHeight[2] * magmaBGFrame, 16, 16), color19, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                                }
                            }
                            else
{
                                ((Color)(ref color19)).R = (byte)((float)(int)((Color)(ref color19)).R * x);
                                ((Color)(ref color19)).G = (byte)((float)(int)((Color)(ref color19)).G * y);
                                ((Color)(ref color19)).B = (byte)((float)(int)((Color)(ref color19)).B * z);
                                spriteBatch.Draw(TextureAssets.Background[array[5]].Value, new Vector2((float)(bgStartX + num50 * num54 + 16 * num56 + num53), (float)(bgStartY + backgroundHeight[2] * num55 + 16 * num57)) + vector, (Rectangle?)new Rectangle(16 * num56 + num53 + 16, 16 * num57 + backgroundHeight[2] * magmaBGFrame, 16, 16), color19, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                            }
                        }
                    }
                }
            }
            if (flag3)
            {
                bgParallax = caveParallax;
                bgStartX = (int)(0.0 - Math.IEEERemainder((double)num50 + (double)screenPosition.X * bgParallax, num50) - (double)(num50 / 2)) - (int)vector.X;
                bgLoops = (screenWidth + (int)vector.X * 2) / num50 + 2;
                bgTopY = bgStartY + bgLoopsY * backgroundHeight[2];
                hellBlackBoxBottom = (float)bgTopY + screenPosition.Y;
                for (int num67 = 0; num67 < bgLoops; num67++)
                {
                    for (int num68 = 0; num68 < num50 / 16; num68++)
                    {
                        float num81 = bgStartX + num50 * num67 + num68 * 16 + 8;
                        float num70 = bgTopY;
                        Color color25 = Lighting.GetColor((int)((num81 + screenPosition.X) / 16f), (int)((screenPosition.Y + num70) / 16f));
                        ((Color)(ref color25)).R = (byte)((float)(int)((Color)(ref color25)).R * x);
                        ((Color)(ref color25)).G = (byte)((float)(int)((Color)(ref color25)).G * y);
                        ((Color)(ref color25)).B = (byte)((float)(int)((Color)(ref color25)).B * z);
                        spriteBatch.Draw(TextureAssets.Background[array[6]].Value, new Vector2((float)(bgStartX + num50 * num67 + 16 * num68 + num53), (float)bgTopY) + vector, (Rectangle?)new Rectangle(16 * num68 + num53 + 16, magmaBGFrame * 16, 16, 16), color25);
                        if (ugBackTransition > 0f)
{
                            Color color26 = color25;
                            ((Color)(ref color26)).R = (byte)((float)(int)((Color)(ref color26)).R * ugBackTransition);
                            ((Color)(ref color26)).G = (byte)((float)(int)((Color)(ref color26)).G * ugBackTransition);
                            ((Color)(ref color26)).B = (byte)((float)(int)((Color)(ref color26)).B * ugBackTransition);
                            ((Color)(ref color26)).A = (byte)((float)(int)((Color)(ref color26)).A * ugBackTransition);
                            spriteBatch.Draw(TextureAssets.Background[array2[6]].Value, new Vector2((float)(bgStartX + num50 * num67 + 16 * num68 + num53), (float)bgTopY) + vector, (Rectangle?)new Rectangle(16 * num68 + num53 + 16, magmaBGFrame * 16, 16, 16), color26);
                        }
                    }
                }
            }
        }
        Lighting.GlobalBrightness = globalBrightness;
        TimeLogger.DrawTime(3, stopwatch.Elapsed.TotalMilliseconds);
    }
References Terraria.GameContent.TextureAssets.Background, Terraria.Main.BackgroundEnabled, Terraria.Main.backgroundHeight, Terraria.Main.bgLoops, Terraria.Main.bgLoopsY, Terraria.Main.bgParallax, Terraria.Main.bgStartX, Terraria.Main.bgStartY, Terraria.Main.bgTopY, Terraria.GameContent.TextureAssets.BlackTile, Terraria.Main.caveBackStyle, Terraria.Main.caveBackX, Terraria.Main.caveParallax, Terraria.Graphics.Light.Color, Terraria.ModLoader.GlobalBackgroundStyleLoader.DelegateChooseUndergroundBackgroundStyle(), Terraria.TimeLogger.DrawTime(), Terraria.Main.drawToScreen, Terraria.Lighting.GetColor(), Terraria.Lighting.GetColor4Slice(), Terraria.Lighting.GetColor9Slice(), Terraria.Lighting.GetCornerColors(), Terraria.Main.gfxQuality, Terraria.Lighting.GlobalBrightness, Terraria.Main.hellBackStyle, Terraria.Main.hellBlackBoxBottom, Terraria.ModLoader.GlobalBackgroundStyleLoader.HookChooseUndergroundBackgroundStyle, Terraria.Main.iceBackStyle, Terraria.WorldGen.InWorld(), Terraria.Main.jungleBackStyle, Terraria.SceneMetrics.JungleTileCount, Terraria.SceneMetrics.JungleTileThreshold, Terraria.Main.LoadBackground(), Terraria.ModLoader.GlobalBackgroundStyleLoader.loaded, Terraria.Main.magmaBGFrame, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.myPlayer, Terraria.Lighting.NotRetro, Terraria.WorldGen.oceanDepths(), Terraria.Main.offScreenRange, Terraria.Main.OldDrawBackground(), Terraria.Main.oldUndergroundBackground, Terraria.Main.player, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.shimmerAlpha, Terraria.Main.ShouldDrawBackgroundTileAt(), Terraria.SceneMetrics.SnowTileCount, Terraria.SceneMetrics.SnowTileThreshold, Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Main.tileBatch, Terraria.Main.ugBackTransition, Terraria.Main.undergroundBackground, Terraria.Main.UnderworldLayer, Terraria.Main.WallLightAt(), Terraria.Main.worldID, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DoDraw(), Terraria.Main.DrawCapture(), and Terraria.Main.RenderBackground().