TModLoader: Terraria.Main.DrawProj_TerraBlade2
DrawProj_TerraBlade2()
void Terraria.Main.DrawProj_TerraBlade2 (Projectile proj) inline private
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_0228: Unknown result type (might be due to invalid IL or missing references)
        //IL_022e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_024f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_0269: Unknown result type (might be due to invalid IL or missing references)
        //IL_026a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        //IL_0290: Unknown result type (might be due to invalid IL or missing references)
        //IL_0293: Unknown result type (might be due to invalid IL or missing references)
        //IL_02aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0300: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0311: Unknown result type (might be due to invalid IL or missing references)
        //IL_032b: Unknown result type (might be due to invalid IL or missing references)
        //IL_032e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0345: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_0361: Unknown result type (might be due to invalid IL or missing references)
        //IL_0368: Unknown result type (might be due to invalid IL or missing references)
        //IL_0382: Unknown result type (might be due to invalid IL or missing references)
        //IL_038b: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03be: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03df: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_044c: Unknown result type (might be due to invalid IL or missing references)
        //IL_044f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0467: Unknown result type (might be due to invalid IL or missing references)
        //IL_046e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0473: Unknown result type (might be due to invalid IL or missing references)
        //IL_0478: Unknown result type (might be due to invalid IL or missing references)
        //IL_048b: Unknown result type (might be due to invalid IL or missing references)
        //IL_049d: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_051e: Unknown result type (might be due to invalid IL or missing references)
        //IL_054b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0563: Unknown result type (might be due to invalid IL or missing references)
        //IL_056a: Unknown result type (might be due to invalid IL or missing references)
        //IL_056f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0574: Unknown result type (might be due to invalid IL or missing references)
        //IL_057d: Unknown result type (might be due to invalid IL or missing references)
        //IL_058f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0596: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0600: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = proj.Center - screenPosition;
        Asset<Texture2D> asset = TextureAssets.Projectile[proj.type];
        Rectangle rectangle = asset.Frame(1, 4);
        Vector2 origin = rectangle.Size() / 2f;
        float num = proj.scale * 1.1f;
        SpriteEffects effects = (SpriteEffects)((!(proj.ai[0] >= 0f)) ? 2 : 0);
        float num2 = proj.localAI[0] / proj.ai[1];
        float num3 = Utils.Remap(num2, 0f, 0.6f, 0f, 1f) * Utils.Remap(num2, 0.6f, 1f, 1f, 0f);
        float num4 = 0.975f;
        Color color6 = Lighting.GetColor(proj.Center.ToTileCoordinates());
        Vector3 val = ((Color)(ref color6)).ToVector3();
        float num5 = ((Vector3)(ref val)).Length() / (float)Math.Sqrt(3.0);
        num5 = 0.5f + num5 * 0.5f;
        num5 = Utils.Remap(num5, 0.2f, 1f, 0f, 1f);
        Color color = default(Color);
        ((Color)(ref color))._002Ector(45, 124, 205);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color * num5 * num3, proj.rotation + proj.ai[0] * ((float)Math.PI / 4f) * -1f * (1f - num2), origin, num * 0.95f, effects, 0f);
        Color color2 = default(Color);
        ((Color)(ref color2))._002Ector(181, 230, 29);
        Color color3 = default(Color);
        ((Color)(ref color3))._002Ector(34, 177, 76);
        Color color4 = Color.White * num3 * 0.5f;
        ((Color)(ref color4)).A = (byte)((float)(int)((Color)(ref color4)).A * (1f - num5));
        Color color5 = color4 * num5 * 0.5f;
        ((Color)(ref color5)).G = (byte)((float)(int)((Color)(ref color5)).G * num5);
        ((Color)(ref color5)).B = (byte)((float)(int)((Color)(ref color5)).R * (0.25f + num5 * 0.75f));
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color5 * 0.15f, proj.rotation + proj.ai[0] * 0.01f, origin, num, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color3 * num5 * num3 * 0.3f, proj.rotation, origin, num, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color2 * num5 * num3 * 0.5f, proj.rotation, origin, num * num4, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)asset.Frame(1, 4, 0, 3), Color.White * 0.6f * num3, proj.rotation + proj.ai[0] * 0.01f, origin, num, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)asset.Frame(1, 4, 0, 3), Color.White * 0.5f * num3, proj.rotation + proj.ai[0] * -0.05f, origin, num * 0.8f, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)asset.Frame(1, 4, 0, 3), Color.White * 0.4f * num3, proj.rotation + proj.ai[0] * -0.1f, origin, num * 0.6f, effects, 0f);
        for (float num6 = 0f; num6 < 12f; num6 += 1f)
        {
            float num7 = proj.rotation + proj.ai[0] * (num6 - 2f) * ((float)Math.PI * -2f) * 0.025f + Utils.Remap(num2, 0f, 1f, 0f, (float)Math.PI / 4f) * proj.ai[0];
            Vector2 drawpos = vector + num7.ToRotationVector2() * ((float)asset.Width() * 0.5f - 6f) * num;
            float num8 = num6 / 12f;
            DrawPrettyStarSparkle(proj.Opacity, (SpriteEffects)0, drawpos, new Color(255, 255, 255, 0) * num3 * num8, color3, num2, 0f, 0.5f, 0.5f, 1f, num7, new Vector2(0f, Utils.Remap(num2, 0f, 1f, 3f, 0f)) * num, Vector2.One * num);
        }
        Vector2 drawpos2 = vector + (proj.rotation + Utils.Remap(num2, 0f, 1f, 0f, (float)Math.PI / 4f) * proj.ai[0]).ToRotationVector2() * ((float)asset.Width() * 0.5f - 4f) * num;
        DrawPrettyStarSparkle(proj.Opacity, (SpriteEffects)0, drawpos2, new Color(255, 255, 255, 0) * num3 * 0.5f, color3, num2, 0f, 0.5f, 0.5f, 1f, 0f, new Vector2(2f, Utils.Remap(num2, 0f, 1f, 4f, 1f)) * num, Vector2.One * num * 1.5f);
    }
References Terraria.Graphics.Light.Color, Terraria.Main.DrawPrettyStarSparkle(), Terraria.Lighting.GetColor(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Utils.Remap(), Terraria.Main.screenPosition, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawProj_DrawSpecialProjs().