TModLoader: Terraria.Main.CacheProjDraws
CacheProjDraws()
void Terraria.Main.CacheProjDraws () inline protected
    {
        DrawCacheProjsBehindNPCsAndTiles.Clear();
        DrawCacheProjsBehindNPCs.Clear();
        DrawCacheProjsBehindProjectiles.Clear();
        DrawCacheProjsOverWiresUI.Clear();
        DrawCacheProjsOverPlayers.Clear();
        DrawCacheFirstFractals.Clear();
        for (int i = 0; i < 1000; i++)
        {
            if (!projectile[i].active)
            {
                continue;
            }
            if (projectile[i].type == 857)
            {
                DrawCacheFirstFractals.Add(i);
            }
            if (projectile[i].type == 578 || projectile[i].type == 579 || projectile[i].type == 641 || projectile[i].type == 617 || projectile[i].type == 813)
            {
                DrawCacheProjsBehindNPCsAndTiles.Add(i);
            }
            if (projectile[i].type == 625 || projectile[i].type == 626 || projectile[i].type == 627 || projectile[i].type == 628 || projectile[i].type == 525 || projectile[i].type == 960 || projectile[i].type == 734 || projectile[i].type == 946 || (projectile[i].type == 908 && projectile[i].localAI[0] <= 0f))
            {
                DrawCacheProjsBehindProjectiles.Add(i);
            }
            if (projectile[i].type == 759 || (projectile[i].type == 908 && projectile[i].localAI[0] > 0f))
            {
                DrawCacheProjsOverPlayers.Add(i);
            }
            if (projectile[i].type == 651)
            {
                DrawCacheProjsOverWiresUI.Add(i);
            }
            if (projectile[i].type == 673 || projectile[i].type == 674 || projectile[i].type == 691 || projectile[i].type == 692 || projectile[i].type == 693 || projectile[i].type == 923)
            {
                DrawCacheProjsBehindNPCs.Add(i);
            }
            if (projectile[i].type == 636 || projectile[i].type == 598 || projectile[i].type == 971)
            {
                bool flag = true;
                if (projectile[i].ai[0] == 1f)
                {
                    int num = (int)projectile[i].ai[1];
                    if (num >= 0 && num < 200 && npc[num].active && npc[num].type != 492)
                    {
                        if (npc[num].behindTiles)
{
                            DrawCacheProjsBehindNPCsAndTiles.Add(i);
                        }
                        else
{
                            DrawCacheProjsBehindNPCs.Add(i);
                        }
                        flag = false;
                    }
                }
                if (flag)
                {
                    DrawCacheProjsBehindProjectiles.Add(i);
                }
            }
            ProjectileLoader.DrawBehind(projectile[i], i, DrawCacheProjsBehindNPCsAndTiles, DrawCacheProjsBehindNPCs, DrawCacheProjsBehindProjectiles, DrawCacheProjsOverPlayers, DrawCacheProjsOverWiresUI);
        }
    }
References Terraria.ModLoader.ProjectileLoader.DrawBehind(), Terraria.Main.DrawCacheFirstFractals, Terraria.Main.DrawCacheProjsBehindNPCs, Terraria.Main.DrawCacheProjsBehindNPCsAndTiles, Terraria.Main.DrawCacheProjsBehindProjectiles, Terraria.Main.DrawCacheProjsOverPlayers, Terraria.Main.DrawCacheProjsOverWiresUI, Terraria.Main.npc, and Terraria.Main.projectile.
Referenced by Terraria.Main.DoDraw_WallsTilesNPCs(), and Terraria.Main.DrawCapture().