TModLoader: Terraria.Main.DrawGuideCraftText
DrawGuideCraftText()
static void Terraria.Main.DrawGuideCraftText (int adjY, Color craftingTipColor, out int inventoryX, out int inventoryY) inline static private
    {
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_028c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0292: Unknown result type (might be due to invalid IL or missing references)
        //IL_0218: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_0228: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_022f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0230: Unknown result type (might be due to invalid IL or missing references)
        //IL_0266: Unknown result type (might be due to invalid IL or missing references)
        //IL_0268: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        inventoryX = 73;
        inventoryY = 331;
        inventoryY += adjY;
        string text = null;
        _requiredObjecsForCraftingText.Clear();
        if (guideItem.IsAir)
        {
            text = Lang.inter[24].Value;
        }
        else
        {
            text = Lang.inter[21].Value + " " + guideItem.Name;
            Recipe recipe = Main.recipe[availableRecipe[focusRecipe]];
            for (int i = 0; i < recipe.requiredTile.Count; i++)
            {
                int num = recipe.requiredTile[i];
                if (num == -1)
                {
                    break;
                }
                int requiredTileStyle = Recipe.GetRequiredTileStyle(num);
                string mapObjectName = Lang.GetMapObjectName(MapHelper.TileToLookup(num, requiredTileStyle));
                _requiredObjecsForCraftingText.Add(mapObjectName);
            }
            if (recipe.needWater)
            {
                _requiredObjecsForCraftingText.Add(Lang.inter[53].Value);
            }
            if (recipe.needHoney)
            {
                _requiredObjecsForCraftingText.Add(Lang.inter[58].Value);
            }
            if (recipe.needLava)
            {
                _requiredObjecsForCraftingText.Add(Lang.inter[56].Value);
            }
            if (recipe.needSnowBiome)
            {
                _requiredObjecsForCraftingText.Add(Lang.inter[123].Value);
            }
            if (recipe.needGraveyardBiome)
            {
                _requiredObjecsForCraftingText.Add(Lang.inter[124].Value);
            }
            _requiredObjecsForCraftingText.AddRange(recipe.Conditions.Select((Condition x) => x.Description.Value));
            if (_requiredObjecsForCraftingText.Count == 0)
            {
                string value = Lang.inter[23].Value;
                _requiredObjecsForCraftingText.Add(value);
            }
        }
        Color color = default(Color);
        ((Color)(ref color))._002Ector((int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor);
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)(inventoryX + 50), (float)(inventoryY + 12));
        DynamicSpriteFont value2 = FontAssets.MouseText.Value;
        if (_requiredObjecsForCraftingText.Count > 0)
        {
            vector.Y -= 14f;
            Vector2 position = vector + new Vector2(0f, 26f);
            Color color2 = color;
            string value3 = Lang.inter[22].Value;
            string text2 = string.Join(", ", _requiredObjecsForCraftingText);
            string text3 = value3 + " " + text2;
            spriteBatch.DrawString(value2, text3, position, color2, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
        }
        spriteBatch.DrawString(value2, text, vector, color, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
    }
References Terraria.Main._requiredObjecsForCraftingText, Terraria.Main.availableRecipe, Terraria.Graphics.Light.Color, Terraria.Condition(), Terraria.Recipe.Conditions, Terraria.Main.focusRecipe, Terraria.Lang.GetMapObjectName(), Terraria.Recipe.GetRequiredTileStyle(), Terraria.Main.guideItem, Terraria.Lang.inter, Terraria.Item.IsAir, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Item.Name, Terraria.Recipe.needGraveyardBiome, Terraria.Recipe.needHoney, Terraria.Recipe.needLava, Terraria.Recipe.needSnowBiome, Terraria.Recipe.needWater, Terraria.Main.recipe, Terraria.Recipe.requiredTile, Terraria.Main.spriteBatch, Terraria.Map.MapHelper.TileToLookup(), and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.DrawInventory().