TModLoader: Terraria.Main.TryApplyingPlayerStringColor
TryApplyingPlayerStringColor()
static Color Terraria.Main.TryApplyingPlayerStringColor (int playerStringColor, Color stringColor) inline static private
    {
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        if (playerStringColor > 0)
        {
            stringColor = WorldGen.paintColor(playerStringColor);
            if (((Color)(ref stringColor)).R < 75)
            {
                ((Color)(ref stringColor)).R = 75;
            }
            if (((Color)(ref stringColor)).G < 75)
            {
                ((Color)(ref stringColor)).G = 75;
            }
            if (((Color)(ref stringColor)).B < 75)
            {
                ((Color)(ref stringColor)).B = 75;
            }
            switch (playerStringColor)
            {
            case 13:
                ((Color)(ref stringColor))._002Ector(20, 20, 20);
                break;
            case 0:
            case 14:
                ((Color)(ref stringColor))._002Ector(200, 200, 200);
                break;
            case 28:
                ((Color)(ref stringColor))._002Ector(163, 116, 91);
                break;
            case 27:
                ((Color)(ref stringColor))._002Ector(DiscoR, DiscoG, DiscoB);
                break;
            }
            ((Color)(ref stringColor)).A = (byte)((float)(int)((Color)(ref stringColor)).A * 0.4f);
        }
        return stringColor;
    }
References Terraria.Graphics.Light.Color, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, and Terraria.WorldGen.paintColor().
Referenced by Terraria.Main.DrawProj_DrawYoyoString(), and Terraria.Main.DrawProj_FishingLine().