TModLoader: Terraria.Main.DrawProj_TheHorsemansBlade
DrawProj_TheHorsemansBlade()
void Terraria.Main.DrawProj_TheHorsemansBlade (Projectile proj) inline private
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_0214: Unknown result type (might be due to invalid IL or missing references)
        //IL_021a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_023b: Unknown result type (might be due to invalid IL or missing references)
        //IL_023e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0255: Unknown result type (might be due to invalid IL or missing references)
        //IL_0256: Unknown result type (might be due to invalid IL or missing references)
        //IL_025c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        //IL_0271: Unknown result type (might be due to invalid IL or missing references)
        //IL_027c: Unknown result type (might be due to invalid IL or missing references)
        //IL_027f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0296: Unknown result type (might be due to invalid IL or missing references)
        //IL_0297: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02da: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0317: Unknown result type (might be due to invalid IL or missing references)
        //IL_031a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0331: Unknown result type (might be due to invalid IL or missing references)
        //IL_0339: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0354: Unknown result type (might be due to invalid IL or missing references)
        //IL_036e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0377: Unknown result type (might be due to invalid IL or missing references)
        //IL_038e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0396: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0432: Unknown result type (might be due to invalid IL or missing references)
        //IL_0435: Unknown result type (might be due to invalid IL or missing references)
        //IL_044d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0454: Unknown result type (might be due to invalid IL or missing references)
        //IL_0459: Unknown result type (might be due to invalid IL or missing references)
        //IL_045e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0471: Unknown result type (might be due to invalid IL or missing references)
        //IL_0483: Unknown result type (might be due to invalid IL or missing references)
        //IL_048a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0491: Unknown result type (might be due to invalid IL or missing references)
        //IL_0496: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0504: Unknown result type (might be due to invalid IL or missing references)
        //IL_0531: Unknown result type (might be due to invalid IL or missing references)
        //IL_0549: Unknown result type (might be due to invalid IL or missing references)
        //IL_0550: Unknown result type (might be due to invalid IL or missing references)
        //IL_0555: Unknown result type (might be due to invalid IL or missing references)
        //IL_055a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0563: Unknown result type (might be due to invalid IL or missing references)
        //IL_0575: Unknown result type (might be due to invalid IL or missing references)
        //IL_057c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0586: Unknown result type (might be due to invalid IL or missing references)
        //IL_058b: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d7: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = proj.Center - screenPosition;
        Asset<Texture2D> asset = TextureAssets.Projectile[proj.type];
        Rectangle rectangle = asset.Frame(1, 4);
        Vector2 origin = rectangle.Size() / 2f;
        float num = proj.scale * 1.1f;
        SpriteEffects effects = (SpriteEffects)((!(proj.ai[0] >= 0f)) ? 2 : 0);
        float num2 = proj.localAI[0] / proj.ai[1];
        float num3 = Utils.Remap(num2, 0f, 0.6f, 0f, 1f) * Utils.Remap(num2, 0.6f, 1f, 1f, 0f);
        float num4 = 0.975f;
        Color color6 = Lighting.GetColor(proj.Center.ToTileCoordinates());
        Vector3 val = ((Color)(ref color6)).ToVector3();
        float fromValue = ((Vector3)(ref val)).Length() / (float)Math.Sqrt(3.0);
        fromValue = Utils.Remap(fromValue, 0.2f, 1f, 0f, 1f);
        Color color = default(Color);
        ((Color)(ref color))._002Ector(193, 43, 43);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color * fromValue * num3, proj.rotation + proj.ai[0] * ((float)Math.PI / 4f) * -1f * (1f - num2), origin, num, effects, 0f);
        Color color2 = default(Color);
        ((Color)(ref color2))._002Ector(247, 115, 0);
        Color color3 = default(Color);
        ((Color)(ref color3))._002Ector(255, 202, 130);
        Color color4 = Color.White * num3 * 0.5f;
        ((Color)(ref color4)).A = (byte)((float)(int)((Color)(ref color4)).A * (1f - fromValue));
        Color color5 = color4 * fromValue * 0.5f;
        ((Color)(ref color5)).G = (byte)((float)(int)((Color)(ref color5)).G * fromValue);
        ((Color)(ref color5)).B = (byte)((float)(int)((Color)(ref color5)).R * (0.25f + fromValue * 0.75f));
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color5 * 0.15f, proj.rotation + proj.ai[0] * 0.01f, origin, num, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color3 * fromValue * num3 * 0.3f, proj.rotation, origin, num, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color2 * fromValue * num3 * 0.5f, proj.rotation, origin, num * num4, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)asset.Frame(1, 4, 0, 3), Color.White * 0.6f * num3, proj.rotation + proj.ai[0] * 0.01f, origin, num, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)asset.Frame(1, 4, 0, 3), Color.White * 0.5f * num3, proj.rotation + proj.ai[0] * -0.05f, origin, num * 0.8f, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)asset.Frame(1, 4, 0, 3), Color.White * 0.4f * num3, proj.rotation + proj.ai[0] * -0.1f, origin, num * 0.6f, effects, 0f);
        for (float num5 = 0f; num5 < 8f; num5 += 1f)
        {
            float num6 = proj.rotation + proj.ai[0] * num5 * ((float)Math.PI * -2f) * 0.025f + Utils.Remap(num2, 0f, 1f, 0f, (float)Math.PI / 4f) * proj.ai[0];
            Vector2 drawpos = vector + num6.ToRotationVector2() * ((float)asset.Width() * 0.5f - 6f) * num;
            float num7 = num5 / 9f;
            DrawPrettyStarSparkle(proj.Opacity, (SpriteEffects)0, drawpos, new Color(255, 255, 255, 0) * num3 * num7, color3, num2, 0f, 0.5f, 0.5f, 1f, num6, new Vector2(0f, Utils.Remap(num2, 0f, 1f, 3f, 0f)) * num, Vector2.One * num);
        }
        Vector2 drawpos2 = vector + (proj.rotation + Utils.Remap(num2, 0f, 1f, 0f, (float)Math.PI / 4f) * proj.ai[0]).ToRotationVector2() * ((float)asset.Width() * 0.5f - 4f) * num;
        DrawPrettyStarSparkle(proj.Opacity, (SpriteEffects)0, drawpos2, new Color(255, 255, 255, 0) * num3 * 0.5f, color3, num2, 0f, 0.5f, 0.5f, 1f, (float)Math.PI / 4f, new Vector2(Utils.Remap(num2, 0f, 1f, 4f, 1f)) * num, Vector2.One * num);
    }
References Terraria.Graphics.Light.Color, Terraria.Main.DrawPrettyStarSparkle(), Terraria.Lighting.GetColor(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Utils.Remap(), Terraria.Main.screenPosition, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawProj_DrawSpecialProjs().