TModLoader: Terraria.Main.DrawWindowsIMEPanel
DrawWindowsIMEPanel()
void Terraria.Main.DrawWindowsIMEPanel (Vector2 position, float xAnchor = 0f) inline
Definition at line 52540 of file Main.cs.
    {
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0174: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        if (!Platform.Get<IImeService>().IsCandidateListVisible)
        {
            return;
        }
        List<string> list = new List<string>();
        for (uint num = 0u; num < Platform.Get<IImeService>().CandidateCount; num++)
        {
            string candidate = Platform.Get<IImeService>().GetCandidate(num);
            list.Add(candidate);
        }
        if (list.Count == 0)
        {
            return;
        }
        uint selectedCandidate = Platform.Get<IImeService>().SelectedCandidate;
        DynamicSpriteFont value = FontAssets.MouseText.Value;
        float num2 = 0.85f;
        float num3 = 14f;
        float num4 = 0f;
        int num5 = 32;
        num4 += num3;
        string text = "{0,2}: {1}";
        string text2 = "  ";
        for (int i = 0; i < list.Count; i++)
        {
            int num6 = i + 1;
            string text3 = text;
            if (i < list.Count - 1)
            {
                text3 += text2;
            }
            num4 += value.MeasureString(string.Format(text3, num6, list[i])).X * num2;
            num4 += num3;
        }
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(num4 * (0f - xAnchor), 0f);
        Utils.DrawSettings2Panel(spriteBatch, position + vector + new Vector2(0f, (float)(-num5)), num4, new Color(63, 65, 151, 255) * 0.785f);
        Vector2 pos = position + new Vector2(10f, (float)(-num5 / 2)) + vector;
        for (uint num7 = 0u; num7 < list.Count; num7++)
        {
            Color color = Color.Gray;
            if (num7 == selectedCandidate)
            {
                color = Color.White;
            }
            uint num8 = num7 + 1;
            string text4 = text;
            if (num7 < list.Count - 1)
            {
                text4 += text2;
            }
            string text5 = string.Format(text4, num8, list[(int)num7]);
            Vector2 vector2 = value.MeasureString(text5) * num2;
            Utils.DrawBorderString(spriteBatch, text5, pos, color, num2, 0f, 0.4f);
            pos.X += vector2.X + num3;
        }
    }
References Terraria.Graphics.Light.Color, Terraria.Utils.DrawBorderString(), Terraria.Utils.DrawSettings2Panel(), Terraria.GameContent.FontAssets.MouseText, Terraria.Enums.Platform, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawPlayerChat().