TModLoader: Terraria.Main.DrawWhip_RainbowWhip
DrawWhip_RainbowWhip()
static Vector2 Terraria.Main.DrawWhip_RainbowWhip (Projectile proj, List< Vector2 > controlPoints) inline static
Definition at line 46915 of file Main.cs.
    {
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_023e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0240: Unknown result type (might be due to invalid IL or missing references)
        //IL_0242: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_016f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0174: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0209: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_021b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0222: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        Texture2D value = TextureAssets.Projectile[proj.type].Value;
        Rectangle rectangle = value.Frame(1, 5);
        int height = rectangle.Height;
        rectangle.Height -= 2;
        Vector2 vector = rectangle.Size() / 2f;
        Vector2 vector2 = controlPoints[0];
        float miscCounterNormalized = player[proj.owner].miscCounterNormalized;
        for (int i = 0; i < controlPoints.Count - 1; i++)
        {
            bool flag = true;
            Vector2 origin = vector;
            switch (i)
            {
            case 0:
                origin.Y -= 4f;
                break;
            case 39:
                rectangle.Y = height * 4;
                break;
            default:
                flag = i % 2 == 0;
                rectangle.Y = height * (1 + i % 3);
                break;
            }
            Vector2 vector3 = controlPoints[i];
            Vector2 vector4 = controlPoints[i + 1] - vector3;
            if (flag)
            {
                Color color = hslToRgb((miscCounterNormalized * 5f + (float)i * 0.05f) % 1f, 1f, 0.5f);
                Color color2 = color;
                float lerpValue = Utils.GetLerpValue(controlPoints.Count - 10, controlPoints.Count - 2, i, clamped: true);
                float num = MathHelper.Lerp(1f, 1f, lerpValue);
                ((Color)(ref color2)).A = (byte)(((Color)(ref color2)).A / 2);
                ((Color)(ref color2)).A = (byte)((float)(int)((Color)(ref color2)).A * lerpValue);
                float rotation = vector4.ToRotation() - (float)Math.PI / 2f;
                Color color3 = Lighting.GetColor(vector3.ToTileCoordinates());
                spriteBatch.Draw(value, vector2 - screenPosition, (Rectangle?)rectangle, Color.Lerp(color3, color2, 0.5f), rotation, origin, num, (SpriteEffects)0, 0f);
                ((Color)(ref color2)).A = 0;
                spriteBatch.Draw(value, vector2 - screenPosition, (Rectangle?)rectangle, color2 * 0.1f, rotation, origin, num * 1.2f, (SpriteEffects)0, 0f);
                if (i == 39)
                {
                    color2 = color;
                    ((Color)(ref color2)).A = 127;
                    spriteBatch.Draw(value, vector2 - screenPosition, (Rectangle?)rectangle, color2 * 0.3f, rotation, origin, num * 1.4f, (SpriteEffects)0, 0f);
                }
            }
            vector2 += vector4;
        }
        return vector2;
    }
References Terraria.Graphics.Light.Color, Terraria.Lighting.GetColor(), Terraria.Utils.GetLerpValue(), Terraria.Main.hslToRgb(), Terraria.Player.miscCounterNormalized, Terraria.Main.player, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.screenPosition, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawWhip().