TModLoader: Terraria.Main.DrawProj_DrawSpecialProjs
DrawProj_DrawSpecialProjs()
void Terraria.Main.DrawProj_DrawSpecialProjs (Projectile proj, ref bool earlyReturn) inline private
Definition at line 33641 of file Main.cs.
    {
        //IL_0176: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_0287: Unknown result type (might be due to invalid IL or missing references)
        //IL_028c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0312: Unknown result type (might be due to invalid IL or missing references)
        //IL_0317: Unknown result type (might be due to invalid IL or missing references)
        //IL_031c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0321: Unknown result type (might be due to invalid IL or missing references)
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0352: Unknown result type (might be due to invalid IL or missing references)
        //IL_0354: Unknown result type (might be due to invalid IL or missing references)
        //IL_0356: Unknown result type (might be due to invalid IL or missing references)
        //IL_0365: Unknown result type (might be due to invalid IL or missing references)
        //IL_036a: Unknown result type (might be due to invalid IL or missing references)
        //IL_036f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03db: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0419: Unknown result type (might be due to invalid IL or missing references)
        //IL_0424: Unknown result type (might be due to invalid IL or missing references)
        //IL_0429: Unknown result type (might be due to invalid IL or missing references)
        //IL_0453: Unknown result type (might be due to invalid IL or missing references)
        //IL_045a: Unknown result type (might be due to invalid IL or missing references)
        //IL_045f: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05de: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0605: Unknown result type (might be due to invalid IL or missing references)
        //IL_060a: Unknown result type (might be due to invalid IL or missing references)
        //IL_060c: Unknown result type (might be due to invalid IL or missing references)
        //IL_060e: Unknown result type (might be due to invalid IL or missing references)
        //IL_061d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0622: Unknown result type (might be due to invalid IL or missing references)
        //IL_0627: Unknown result type (might be due to invalid IL or missing references)
        //IL_0639: Unknown result type (might be due to invalid IL or missing references)
        //IL_0644: Unknown result type (might be due to invalid IL or missing references)
        //IL_0649: Unknown result type (might be due to invalid IL or missing references)
        //IL_0476: Unknown result type (might be due to invalid IL or missing references)
        //IL_0478: Unknown result type (might be due to invalid IL or missing references)
        //IL_0482: Unknown result type (might be due to invalid IL or missing references)
        //IL_0487: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0468: Unknown result type (might be due to invalid IL or missing references)
        //IL_046f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0474: Unknown result type (might be due to invalid IL or missing references)
        //IL_0514: Unknown result type (might be due to invalid IL or missing references)
        //IL_0516: Unknown result type (might be due to invalid IL or missing references)
        //IL_0520: Unknown result type (might be due to invalid IL or missing references)
        //IL_0525: Unknown result type (might be due to invalid IL or missing references)
        //IL_053e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0540: Unknown result type (might be due to invalid IL or missing references)
        //IL_0547: Unknown result type (might be due to invalid IL or missing references)
        //IL_054f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0551: Unknown result type (might be due to invalid IL or missing references)
        //IL_0558: Unknown result type (might be due to invalid IL or missing references)
        //IL_056f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0571: Unknown result type (might be due to invalid IL or missing references)
        //IL_0578: Unknown result type (might be due to invalid IL or missing references)
        //IL_057f: Unknown result type (might be due to invalid IL or missing references)
        //IL_058a: Unknown result type (might be due to invalid IL or missing references)
        //IL_058c: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0506: Unknown result type (might be due to invalid IL or missing references)
        //IL_050d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0512: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0801: Unknown result type (might be due to invalid IL or missing references)
        //IL_0803: Unknown result type (might be due to invalid IL or missing references)
        //IL_080e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0813: Unknown result type (might be due to invalid IL or missing references)
        //IL_0816: Unknown result type (might be due to invalid IL or missing references)
        //IL_0829: Unknown result type (might be due to invalid IL or missing references)
        //IL_082e: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_06bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0703: Unknown result type (might be due to invalid IL or missing references)
        //IL_0719: Unknown result type (might be due to invalid IL or missing references)
        //IL_071b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0722: Unknown result type (might be due to invalid IL or missing references)
        //IL_072a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0746: Unknown result type (might be due to invalid IL or missing references)
        //IL_0748: Unknown result type (might be due to invalid IL or missing references)
        //IL_074f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0757: Unknown result type (might be due to invalid IL or missing references)
        //IL_076d: Unknown result type (might be due to invalid IL or missing references)
        //IL_076f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0776: Unknown result type (might be due to invalid IL or missing references)
        //IL_077e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0682: Unknown result type (might be due to invalid IL or missing references)
        //IL_068d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0692: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a08: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a12: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a19: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a21: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a25: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a53: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a58: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_08da: Unknown result type (might be due to invalid IL or missing references)
        //IL_08df: Unknown result type (might be due to invalid IL or missing references)
        //IL_090d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0912: Unknown result type (might be due to invalid IL or missing references)
        //IL_0917: Unknown result type (might be due to invalid IL or missing references)
        //IL_091b: Unknown result type (might be due to invalid IL or missing references)
        //IL_091d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0922: Unknown result type (might be due to invalid IL or missing references)
        //IL_0932: Unknown result type (might be due to invalid IL or missing references)
        //IL_0937: Unknown result type (might be due to invalid IL or missing references)
        //IL_093c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0943: Unknown result type (might be due to invalid IL or missing references)
        //IL_0947: Unknown result type (might be due to invalid IL or missing references)
        //IL_0952: Unknown result type (might be due to invalid IL or missing references)
        //IL_0959: Unknown result type (might be due to invalid IL or missing references)
        //IL_0967: Unknown result type (might be due to invalid IL or missing references)
        //IL_0969: Unknown result type (might be due to invalid IL or missing references)
        //IL_096e: Unknown result type (might be due to invalid IL or missing references)
        //IL_097e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0983: Unknown result type (might be due to invalid IL or missing references)
        //IL_0988: Unknown result type (might be due to invalid IL or missing references)
        //IL_098f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0993: Unknown result type (might be due to invalid IL or missing references)
        //IL_099e: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a9: Unknown result type (might be due to invalid IL or missing references)
        if (proj.aiStyle == 160)
        {
            DrawKite(proj);
            return;
        }
        if (proj.aiStyle == 165)
        {
            DrawWhip(proj);
            return;
        }
        if (proj.type == 879 || proj.type == 877 || proj.type == 878)
        {
            proj.position.Y -= Main.player[proj.owner].gfxOffY;
        }
        if (proj.aiStyle == 174)
        {
            DrawMultisegmentPet(proj);
            return;
        }
        if (proj.type == 1020)
        {
            DrawContinuousTrail(proj);
        }
        bool flag3 = true;
        switch (proj.type)
        {
        default:
            flag3 = false;
            break;
        case 932:
            DrawProj_FairyQueenRangedItemShot(proj);
            break;
        case 919:
            DrawProj_FairyQueenLance(proj);
            break;
        case 974:
            DrawProj_LightsBane(proj);
            break;
        case 972:
            DrawProj_NightsEdge(proj);
            break;
        case 973:
            DrawProj_TrueNightsEdge(proj);
            break;
        case 982:
            DrawProj_Excalibur(proj);
            break;
        case 997:
            DrawProj_TheHorsemansBlade(proj);
            break;
        case 984:
            DrawProj_TerraBlade2(proj);
            break;
        case 985:
            DrawProj_TerraBlade2Shot(proj);
            break;
        case 983:
            DrawProj_TrueExcalibur(proj);
            break;
        case 995:
            _stardewAnimation.Draw(spriteBatch, (int)proj.ai[0], proj.Center - screenPosition);
            flag3 = false;
            break;
        }
        if (flag3)
        {
            return;
        }
        if (proj.type == 34)
        {
            default(FlameLashDrawer).Draw(proj);
        }
        if (proj.type == 16)
        {
            default(MagicMissileDrawer).Draw(proj);
        }
        if (proj.type == 106)
        {
            default(LightDiscDrawer).Draw(proj);
        }
        if (proj.type == 933)
        {
            default(FinalFractalHelper).Draw(proj);
        }
        if (proj.type == 79)
        {
            default(RainbowRodDrawer).Draw(proj);
        }
        if (proj.type == 946)
        {
            EmpressBladeDrawer empressBladeDrawer = default(EmpressBladeDrawer);
            float num12 = GlobalTimeWrappedHourly % 3f / 3f;
            Player player = Main.player[proj.owner];
            float num13 = MathHelper.Max(1f, (float)player.maxMinions);
            float num14 = (float)proj.identity % num13 / num13 + num12;
            Color fairyQueenWeaponsColor = proj.GetFairyQueenWeaponsColor(0f, 0f, num14 % 1f);
            Color fairyQueenWeaponsColor2 = proj.GetFairyQueenWeaponsColor(0f, 0f, (num14 + 0.5f) % 1f);
            empressBladeDrawer.ColorStart = fairyQueenWeaponsColor;
            empressBladeDrawer.ColorEnd = fairyQueenWeaponsColor2;
            empressBladeDrawer.Draw(proj);
            DrawProj_EmpressBlade(proj, num14);
        }
        else if (proj.type == 927)
        {
            DrawProj_PiercingStarlight(proj);
        }
        else if (proj.type == 917)
        {
            DrawProj_CoolWhipMinion(proj);
        }
        else if (proj.type == 923)
        {
            Vector2 position = proj.Center - screenPosition;
            Texture2D value = TextureAssets.Projectile[proj.type].Value;
            Rectangle rectangle = value.Frame(1, 2);
            Rectangle value2 = value.Frame(1, 2, 0, 1);
            Vector2 origin = rectangle.Size() * new Vector2(0.03f, 0.5f);
            float num15 = 180f;
            float num23 = proj.ai[0] / ((float)Math.PI * 2f) + proj.localAI[0] / num15;
            float num16 = Utils.GetLerpValue(0f, 30f, proj.localAI[0], clamped: true) * Utils.GetLerpValue(num15, num15 - 30f, proj.localAI[0], clamped: true);
            Color color2 = hslToRgb(num23 % 1f, 1f, 1f) * num16;
            float lerpValue = Utils.GetLerpValue(40f, 60f, proj.localAI[0], clamped: true);
            Vector2 vector2 = new Vector2(1f, MathHelper.Lerp(0.25f, 0.7f, lerpValue)) * proj.scale;
            Color value3 = hslToRgb((num23 + 0.3f) % 1f, 1f, MathHelper.Lerp(0.3f, 0.66f, lerpValue)) * num16;
            if (NPC.ShouldEmpressBeEnraged())
            {
                value3 = OurFavoriteColor * num16;
            }
            value3 = Color.Lerp(value3, Color.White, 0.1f);
            ((Color)(ref value3)).A = (byte)(((Color)(ref value3)).A / 2);
            spriteBatch.Draw(value, position, (Rectangle?)value2, value3, proj.rotation, origin, vector2 * 1.2f, (SpriteEffects)0, 0f);
            Color value4 = hslToRgb((num23 + 0.15f) % 1f, 1f, MathHelper.Lerp(0.3f, 0.5f, lerpValue)) * num16;
            if (NPC.ShouldEmpressBeEnraged())
            {
                value4 = OurFavoriteColor * num16;
            }
            value4 = Color.Lerp(value4, Color.White, 0.1f);
            ((Color)(ref value4)).A = (byte)(((Color)(ref value4)).A / 2);
            spriteBatch.Draw(value, position, (Rectangle?)value2, value4, proj.rotation, origin, vector2 * 1.1f, (SpriteEffects)0, 0f);
            spriteBatch.Draw(value, position, (Rectangle?)rectangle, color2 * 0.5f, proj.rotation, origin, vector2, (SpriteEffects)0, 0f);
            spriteBatch.Draw(value, position, (Rectangle?)value2, color2 * lerpValue, proj.rotation, origin, vector2, (SpriteEffects)0, 0f);
        }
        else if (proj.type == 950)
        {
            Vector2 position2 = proj.Center - screenPosition;
            Texture2D value5 = TextureAssets.Projectile[proj.type].Value;
            Rectangle rectangle2 = value5.Frame();
            Vector2 origin2 = rectangle2.Size() * new Vector2(0.5f, 0.5f);
            Color color3 = new Color(255, 255, 255, 0) * proj.Opacity;
            float hue = ((proj.ai[2] == 1f) ? 0.96f : 0.92f);
            if (proj.ai[2] == 1f)
            {
                color3 = new Color(255, 0, 30, 180) * proj.Opacity;
            }
            Color color4 = hslToRgb(hue, 1f, 0.5f) * proj.Opacity;
            ((Color)(ref color4)).A = 0;
            color3 *= 0.6f;
            color4 *= 0.6f;
            float scale = proj.scale;
            float num17 = proj.localAI[0];
            spriteBatch.Draw(value5, position2, (Rectangle?)rectangle2, color3, proj.rotation, origin2, num17, (SpriteEffects)0, 0f);
            spriteBatch.Draw(value5, position2, (Rectangle?)rectangle2, color4, proj.rotation, origin2, num17 * 0.95f, (SpriteEffects)0, 0f);
            spriteBatch.Draw(value5, position2, (Rectangle?)rectangle2, color3, proj.rotation, origin2, scale, (SpriteEffects)0, 0f);
            spriteBatch.Draw(value5, position2, (Rectangle?)rectangle2, color4, proj.rotation, origin2, scale * 0.95f, (SpriteEffects)0, 0f);
        }
        else if (proj.type == 888)
        {
            DrawTwinsPet(proj);
        }
        else if (proj.type == 874)
        {
            DrawMurderAurora(proj);
        }
        else if (proj.type == 871)
        {
            Texture2D value6 = TextureAssets.Projectile[proj.type].Value;
            Rectangle rectangle3 = value6.Frame(1, 4);
            Vector2 origin3 = rectangle3.Size() / 2f;
            Color color5 = Color.White * proj.Opacity;
            SpriteEffects effects = (SpriteEffects)0;
            ((Color)(ref color5)).A = (byte)(((Color)(ref color5)).A / 2);
            Color color6 = proj.AI_171_GetColor();
            ((Color)(ref color6)).A = (byte)(((Color)(ref color6)).A / 2);
            float num18 = proj.scale * 1.3f;
            float num19 = 1f;
            int num20 = proj.AI_172_GetPelletStormsCount();
            bool flag4 = false;
            float num21 = float.PositiveInfinity;
            for (int i = 0; i < num20; i++)
            {
                Projectile.HallowBossPelletStormInfo hallowBossPelletStormInfo = proj.AI_172_GetPelletStormInfo(i);
                for (int j = 0; j < hallowBossPelletStormInfo.BulletsInStorm; j++)
                {
                    float bulletProgress = hallowBossPelletStormInfo.GetBulletProgress(j);
                    if (bulletProgress < num21)
                    {
                        num21 = bulletProgress;
                    }
                    if (hallowBossPelletStormInfo.IsValid(j))
                    {
                        if (i == num20 - 1 && bulletProgress > 0f)
{
                            flag4 = true;
                        }
                        rectangle3 = value6.Frame(1, 4, 0, (int)((double)(j + i * 6) + timeForVisualEffects / 4.0) % 4);
                        float num22 = Utils.GetLerpValue(0f, 0.1f, bulletProgress, clamped: true) * Utils.GetLerpValue(1f, 0.8f, bulletProgress, clamped: true);
                        Vector2 bulletPosition = hallowBossPelletStormInfo.GetBulletPosition(j, proj.Center);
                        EntitySpriteDraw(value6, bulletPosition - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle3, color6 * num22, proj.rotation, origin3, num18 * num19, effects);
                        EntitySpriteDraw(value6, bulletPosition - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle3, color5 * num22, proj.rotation, origin3, proj.scale * num19, effects);
                    }
                }
            }
            if (!flag4 && num21 <= 1f)
            {
                EntitySpriteDraw(value6, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle3, color6, proj.rotation, origin3, num18, effects);
                EntitySpriteDraw(value6, proj.Center - screenPosition + new Vector2(0f, proj.gfxOffY), rectangle3, color5, proj.rotation, origin3, proj.scale, effects);
            }
        }
        else
        {
            earlyReturn = false;
        }
    }
References Terraria.Main._stardewAnimation, Terraria.Graphics.Light.Color, Terraria.GameContent.Animations.StardewValleyAnimation.Draw(), Terraria.Main.DrawContinuousTrail(), Terraria.Main.DrawKite(), Terraria.Main.DrawMultisegmentPet(), Terraria.Main.DrawMurderAurora(), Terraria.Main.DrawProj_CoolWhipMinion(), Terraria.Main.DrawProj_EmpressBlade(), Terraria.Main.DrawProj_Excalibur(), Terraria.Main.DrawProj_FairyQueenLance(), Terraria.Main.DrawProj_FairyQueenRangedItemShot(), Terraria.Main.DrawProj_LightsBane(), Terraria.Main.DrawProj_NightsEdge(), Terraria.Main.DrawProj_PiercingStarlight(), Terraria.Main.DrawProj_TerraBlade2(), Terraria.Main.DrawProj_TerraBlade2Shot(), Terraria.Main.DrawProj_TheHorsemansBlade(), Terraria.Main.DrawProj_TrueExcalibur(), Terraria.Main.DrawProj_TrueNightsEdge(), Terraria.Main.DrawTwinsPet(), Terraria.Main.DrawWhip(), Terraria.Main.EntitySpriteDraw(), Terraria.Utils.GetLerpValue(), Terraria.Player.gfxOffY, Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.hslToRgb(), Terraria.Player.maxMinions, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.screenPosition, Terraria.NPC.ShouldEmpressBeEnraged(), Terraria.Main.spriteBatch, and Terraria.Main.timeForVisualEffects.
Referenced by Terraria.Main.DrawProj_Inner_DoDrawProj().