TModLoader: Terraria.Main.GetItemDrawFrame
GetItemDrawFrame()
static void Terraria.Main.GetItemDrawFrame (int item, out Texture2D itemTexture, out Rectangle itemFrame) inline static
Gets the texture and frame of the given item type (F:Terraria.Item.type).
Parameters
item The item type to use.
itemTexture The T:Microsoft.Xna.Framework.Graphics.Texture2D in F:Terraria.GameContent.TextureAssets.Item of item .
itemFrame The T:Microsoft.Xna.Framework.Rectangle covering this item's current frame on itemTexture .
    {
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        instance.LoadItem(item);
        itemTexture = TextureAssets.Item[item].Value;
        if (itemAnimations[item] != null)
        {
            itemFrame = itemAnimations[item].GetFrame(itemTexture);
        }
        else
        {
            itemFrame = itemTexture.Frame();
        }
    }
References Terraria.DataStructures.DrawAnimation.GetFrame(), Terraria.Main.instance, Terraria.GameContent.TextureAssets.Item, Terraria.Main.item, Terraria.Main.itemAnimations, Terraria.Main.itemFrame, and Terraria.Main.LoadItem().
Referenced by Terraria.Main.DrawItemIcon(), Terraria.Main.DrawNPC_SlimeItem(), Terraria.Main.DrawNPCDirect_Inner(), Terraria.Main.DrawNPCExtras(), Terraria.Main.DrawPlayerItemPos(), Terraria.UI.ItemSlot.DrawSavings(), Terraria.GameContent.UI.CustomCurrencyManager.DrawSavings(), Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy(), and Terraria.Main.GUIChatDrawInner().