TModLoader: Terraria.Main.DrawStarsInBackground
DrawStarsInBackground()
void Terraria.Main.DrawStarsInBackground (SceneArea sceneArea, bool artificial) inline private
Definition at line 79903 of file Main.cs.
    {
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        if (netMode == 2 || ((double)screenPosition.Y >= worldSurface * 16.0 + 16.0 && shimmerAlpha == 0f))
        {
            return;
        }
        float num = 1f;
        if (GraveyardVisualIntensity > 0f)
        {
            float num2 = 1f - GraveyardVisualIntensity * 1.4f;
            if (num2 <= 0f)
            {
                return;
            }
            num *= num2;
        }
        Color colorOfTheSkies = ColorOfTheSkies;
        if (shimmerAlpha > 0f)
        {
            colorOfTheSkies *= 1f - shimmerAlpha;
        }
        if (remixWorld || !(255f * (1f - cloudAlpha * atmo) - (float)(int)((Color)(ref colorOfTheSkies)).R - 25f <= 0f))
        {
            for (int i = 0; i < numStars; i++)
            {
                DrawStar(ref sceneArea, num, colorOfTheSkies, i, star[i], artificial);
            }
        }
    }
References Terraria.Main.atmo, Terraria.Main.cloudAlpha, Terraria.Graphics.Light.Color, Terraria.Main.ColorOfTheSkies, Terraria.Main.DrawStar(), Terraria.Main.GraveyardVisualIntensity, Terraria.Main.netMode, Terraria.Main.numStars, Terraria.Main.remixWorld, Terraria.Main.screenPosition, Terraria.Main.shimmerAlpha, Terraria.Main.star, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.DrawCapture().