TModLoader: Terraria.Main.InvasionWarning
InvasionWarning()
static void Terraria.Main.InvasionWarning () inline static private
    {
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        LocalizedText empty = LocalizedText.Empty;
        empty = ((invasionSize > 0) ? ((!(invasionX < (double)spawnTileX)) ? ((!(invasionX > (double)spawnTileX)) ? ((invasionType == 2) ? Lang.misc[7] : ((invasionType == 3) ? Lang.misc[27] : ((invasionType == 4) ? Lang.misc[41] : (empty = Lang.misc[3])))) : ((invasionType == 2) ? Lang.misc[6] : ((invasionType == 3) ? Lang.misc[26] : ((invasionType == 4) ? LocalizedText.Empty : (empty = Lang.misc[2]))))) : ((invasionType == 2) ? Lang.misc[5] : ((invasionType == 3) ? Lang.misc[25] : ((invasionType == 4) ? LocalizedText.Empty : (empty = Lang.misc[1]))))) : ((invasionType == 2) ? Lang.misc[4] : ((invasionType == 3) ? Lang.misc[24] : ((invasionType == 4) ? Lang.misc[42] : (empty = Lang.misc[0])))));
        if (netMode == 0)
        {
            NewText(empty.ToString(), 175, 75);
        }
        else if (netMode == 2 && empty.Value != "")
        {
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey(empty.Key), new Color(175, 75, 255));
        }
    }
References Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Graphics.Light.Color, Terraria.Localization.LocalizedText.Empty, Terraria.Localization.NetworkText.FromKey(), Terraria.Main.invasionSize, Terraria.Main.invasionType, Terraria.Main.invasionX, Terraria.Lang.misc, Terraria.Main.netMode, Terraria.Main.NewText(), and Terraria.Main.spawnTileX.
Referenced by Terraria.Main.UpdateInvasion_Inner().