TModLoader: Terraria.Main.buffColor
buffColor()
static Color Terraria.Main.buffColor (Color newColor, float R, float G, float B, float A) inline static
    {
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        ((Color)(ref newColor)).R = (byte)((float)(int)((Color)(ref newColor)).R * R);
        ((Color)(ref newColor)).G = (byte)((float)(int)((Color)(ref newColor)).G * G);
        ((Color)(ref newColor)).B = (byte)((float)(int)((Color)(ref newColor)).B * B);
        ((Color)(ref newColor)).A = (byte)((float)(int)((Color)(ref newColor)).A * A);
        return newColor;
    }
References Terraria.Graphics.Light.Color.
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup_2(), Terraria.Main.DrawNPCDirect_Inner(), Terraria.Main.DrawSmartCursor(), and Terraria.Main.DrawSmartInteract().