TModLoader: Terraria.Main.DrawProj_NightsEdge
DrawProj_NightsEdge()
void Terraria.Main.DrawProj_NightsEdge (Projectile proj) inline private
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_0130: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_020c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        //IL_0240: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        //IL_0257: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0268: Unknown result type (might be due to invalid IL or missing references)
        //IL_0273: Unknown result type (might be due to invalid IL or missing references)
        //IL_027c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0293: Unknown result type (might be due to invalid IL or missing references)
        //IL_0294: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_029e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02af: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_030d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0327: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0336: Unknown result type (might be due to invalid IL or missing references)
        //IL_0363: Unknown result type (might be due to invalid IL or missing references)
        //IL_037b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0382: Unknown result type (might be due to invalid IL or missing references)
        //IL_0387: Unknown result type (might be due to invalid IL or missing references)
        //IL_038c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0395: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e9: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = proj.Center - screenPosition;
        Asset<Texture2D> asset = TextureAssets.Projectile[proj.type];
        Rectangle rectangle = asset.Frame(1, 4);
        Vector2 origin = rectangle.Size() / 2f;
        float num = proj.scale * 1.1f;
        SpriteEffects effects = (SpriteEffects)((!(proj.ai[0] >= 0f)) ? 2 : 0);
        float num2 = proj.localAI[0] / proj.ai[1];
        float num3 = Utils.Remap(num2, 0f, 0.6f, 0f, 1f) * Utils.Remap(num2, 0.6f, 1f, 1f, 0f);
        float num4 = 0.975f;
        Color color5 = Lighting.GetColor(proj.Center.ToTileCoordinates());
        Vector3 val = ((Color)(ref color5)).ToVector3();
        float fromValue = ((Vector3)(ref val)).Length() / (float)Math.Sqrt(3.0);
        fromValue = Utils.Remap(fromValue, 0.2f, 1f, 0f, 1f);
        Color color = default(Color);
        ((Color)(ref color))._002Ector(40, 20, 60);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color * fromValue * num3, proj.rotation + proj.ai[0] * ((float)Math.PI / 4f) * -1f * (1f - num2), origin, num * num4, effects, 0f);
        Color color2 = default(Color);
        ((Color)(ref color2))._002Ector(80, 40, 180);
        Color color3 = Color.White * num3 * 0.5f;
        ((Color)(ref color3)).A = (byte)((float)(int)((Color)(ref color3)).A * (1f - fromValue));
        Color color4 = color3 * fromValue * 0.5f;
        ((Color)(ref color4)).G = (byte)((float)(int)((Color)(ref color4)).G * fromValue);
        ((Color)(ref color4)).R = (byte)((float)(int)((Color)(ref color4)).R * (0.25f + fromValue * 0.75f));
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color4 * 0.15f, proj.rotation + proj.ai[0] * 0.01f, origin, num, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, new Color(80, 30, 160) * fromValue * num3 * 0.3f, proj.rotation, origin, num * 0.8f, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color2 * fromValue * num3 * 0.7f, proj.rotation, origin, num * num4, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)asset.Frame(1, 4, 0, 3), Color.White * 0.3f * num3 * (1f - fromValue * 0.7f), proj.rotation + proj.ai[0] * 0.01f, origin, num, effects, 0f);
        Vector2 drawpos = vector + (proj.rotation + Utils.Remap(num2, 0f, 1f, 0f, (float)Math.PI / 2f) * proj.ai[0]).ToRotationVector2() * ((float)asset.Width() * 0.5f - 4f) * num;
        DrawPrettyStarSparkle(proj.Opacity, (SpriteEffects)0, drawpos, new Color(255, 255, 255, 0) * num3 * 0.5f, color2, num2, 0f, 0.5f, 0.5f, 1f, (float)Math.PI / 4f, new Vector2(2f, 2f), Vector2.One);
    }
References Terraria.Graphics.Light.Color, Terraria.Main.DrawPrettyStarSparkle(), Terraria.Lighting.GetColor(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Utils.Remap(), Terraria.Main.screenPosition, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawProj_DrawSpecialProjs().