TModLoader: Terraria.Main.EntitySpriteDraw
EntitySpriteDraw() [2/3]
static void Terraria.Main.EntitySpriteDraw (Texture2D texture, Vector2 position, Rectangle? sourceRectangle, Color color, float rotation, Vector2 origin, float scale, SpriteEffects effects, float worthless = 0f) inline static
Definition at line 48883 of file Main.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0003: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        EntitySpriteDraw(texture, position, sourceRectangle, color, rotation, origin, new Vector2(scale), effects, worthless);
    }
References Terraria.Main.EntitySpriteDraw().
Referenced by Terraria.Main.DrawKite(), Terraria.Main.DrawMultisegmentPet(), Terraria.Main.DrawMurderAurora(), Terraria.Main.DrawPrettyStarSparkle(), Terraria.Main.DrawProj_DrawExtras(), Terraria.Main.DrawProj_DrawNormalProjs(), Terraria.Main.DrawProj_DrawSpecialProjs(), Terraria.Main.DrawProj_DrawVoidLens(), Terraria.Main.DrawProj_DrawYoyoString(), Terraria.Main.DrawProj_EmpressBlade(), Terraria.Main.DrawProj_FishingLine(), Terraria.Main.DrawProj_FlailChains_Old(), Terraria.Main.DrawProj_Flamethrower(), Terraria.Main.DrawProj_Spear(), Terraria.Main.DrawProjWithStarryTrail(), Terraria.Main.DrawTrail(), Terraria.Main.DrawTwinsPet(), and Terraria.Main.EntitySpriteDraw().