TModLoader: Terraria.Main.DedServ_PostModLoad
DedServ_PostModLoad()
void Terraria.Main.DedServ_PostModLoad (out bool reloadMods) inline private
Definition at line 5130 of file Main.cs.
    {
        //IL_0cc4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cce: Expected O, but got Unknown
        //IL_0dcb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd5: Expected O, but got Unknown
        reloadMods = false;
        while (worldPathName == null || worldPathName == "")
        {
            bool flag = true;
            while (flag)
            {
                LoadWorlds();
                Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber2) + " - " + Terraria.ModLoader.ModLoader.versionedName);
                Console.WriteLine("");
                for (int i = 0; i < WorldList.Count; i++)
                {
                    Console.WriteLine(i + 1 + "\t\t" + WorldList[i].Name);
                }
                string textValue = Language.GetTextValue("CLI.NewWorld_Command");
                string textValue2 = Language.GetTextValue("CLI.DeleteWorld_Example");
                int num = (Math.Max(newWorldName.Length, textValue2.Length) + 1) / 8 + 1;
                textValue = textValue + new string('\t', num - textValue.Length / 8) + Language.GetTextValue("CLI.NewWorld_Description");
                textValue2 = textValue2 + new string('\t', num - textValue2.Length / 8) + Language.GetTextValue("CLI.DeleteWorld_Description");
                Console.WriteLine(textValue);
                Console.WriteLine(textValue2);
                Console.WriteLine("m\t\tMods Menu");
                Console.WriteLine("");
                Console.Write(Language.GetTextValue("CLI.ChooseWorld"));
                string text2 = ReadLineInput();
                if (text2 == null)
                {
                    text2 = "";
                }
                try
                {
                    Console.Clear();
                }
                catch
                {
                }
                if (text2.StartsWith(Language.GetTextValue("CLI.DeleteWorld_Command") + " "))
                {
                    try
                    {
                        int length = Language.GetTextValue("CLI.DeleteWorld_Command").Length;
                        int num2 = Convert.ToInt32(text2.Substring(length + 1)) - 1;
                        if (num2 < WorldList.Count)
{
                            Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber2) + " - " + Terraria.ModLoader.ModLoader.versionedName);
                            Console.WriteLine("");
                            Console.WriteLine(Language.GetTextValue("CLI.DeleteConfirmation", WorldList[num2].Name));
                            Console.Write("({0}/{1}): ", Language.GetTextValue("CLI.ShortYes"), Language.GetTextValue("CLI.ShortNo"));
                            if (ReadLineInput().ToLower() == Language.GetTextValue("CLI.ShortYes").ToLower())
{
                                EraseWorld(num2);
                            }
                        }
                    }
                    catch
                    {
                    }
                    try
                    {
                        Console.Clear();
                    }
                    catch
                    {
                    }
                    continue;
                }
                switch (text2)
                {
                case "n":
                case "N":
                {
                    bool flag2 = true;
                    while (flag2)
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber2) + " - " + Terraria.ModLoader.ModLoader.versionedName);
                        Console.WriteLine("");
                        Console.WriteLine("1\t" + Language.GetTextValue("UI.WorldSizeSmall"));
                        Console.WriteLine("2\t" + Language.GetTextValue("UI.WorldSizeMedium"));
                        Console.WriteLine("3\t" + Language.GetTextValue("UI.WorldSizeLarge"));
                        Console.WriteLine("");
                        Console.Write(Language.GetTextValue("CLI.ChooseSize"));
                        string value3 = ReadLineInput();
                        try
{
                            switch (Convert.ToInt32(value3))
{
                            case 1:
                                maxTilesX = 4200;
                                maxTilesY = 1200;
                                flag2 = false;
                                break;
                            case 2:
                                maxTilesX = 6400;
                                maxTilesY = 1800;
                                flag2 = false;
                                break;
                            case 3:
                                maxTilesX = 8400;
                                maxTilesY = 2400;
                                flag2 = false;
                                break;
                            }
                        }
                        catch
{
                        }
                        try
{
                            Console.Clear();
                        }
                        catch
{
                        }
                    }
                    flag2 = true;
                    while (flag2)
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber2) + " - " + Terraria.ModLoader.ModLoader.versionedName);
                        Console.WriteLine("");
                        Console.WriteLine("1\t" + Language.GetTextValue("UI.Normal"));
                        Console.WriteLine("2\t" + Language.GetTextValue("UI.Expert"));
                        Console.WriteLine("3\t" + Language.GetTextValue("UI.Master"));
                        Console.WriteLine("4\t" + Language.GetTextValue("UI.Creative"));
                        Console.WriteLine("");
                        Console.Write(Language.GetTextValue("CLI.ChooseDifficulty"));
                        string value2 = ReadLineInput();
                        try
{
                            switch (Convert.ToInt32(value2))
{
                            case 1:
                                GameMode = 0;
                                flag2 = false;
                                break;
                            case 2:
                                GameMode = 1;
                                flag2 = false;
                                break;
                            case 3:
                                GameMode = 2;
                                flag2 = false;
                                break;
                            case 4:
                                GameMode = 3;
                                flag2 = false;
                                break;
                            }
                        }
                        catch
{
                        }
                        try
{
                            Console.Clear();
                        }
                        catch
{
                        }
                    }
                    flag2 = true;
                    while (flag2)
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber2) + " - " + Terraria.ModLoader.ModLoader.versionedName);
                        Console.WriteLine("");
                        Console.WriteLine("1\t" + Language.GetTextValue("CLI.Random"));
                        Console.WriteLine("2\t" + Language.GetTextValue("CLI.Corrupt"));
                        Console.WriteLine("3\t" + Language.GetTextValue("CLI.Crimson"));
                        Console.WriteLine("");
                        Console.Write(Language.GetTextValue("CLI.ChooseEvil"));
                        string value = ReadLineInput();
                        try
{
                            switch (Convert.ToInt32(value))
{
                            case 1:
                                WorldGen.WorldGenParam_Evil = -1;
                                flag2 = false;
                                break;
                            case 2:
                                WorldGen.WorldGenParam_Evil = 0;
                                flag2 = false;
                                break;
                            case 3:
                                WorldGen.WorldGenParam_Evil = 1;
                                flag2 = false;
                                break;
                            }
                        }
                        catch
{
                        }
                        try
{
                            Console.Clear();
                        }
                        catch
{
                        }
                    }
                    flag2 = true;
                    Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber2) + " - " + Terraria.ModLoader.ModLoader.versionedName);
                    while (flag2)
                    {
                        Console.WriteLine("");
                        Console.Write(Language.GetTextValue("CLI.EnterWorldName"));
                        newWorldName = ReadLineInput();
                        if (newWorldName != null && newWorldName != "" && newWorldName != " ")
{
                            if (newWorldName.Length >= 27)
{
                                Console.WriteLine("");
                                Console.WriteLine(Language.GetTextValue("CLI.WorldNameLengthTooLong", 26));
                                continue;
                            }
                            flag2 = false;
                            try
{
                                Console.Clear();
                            }
                            catch
{
                            }
                        }
                        else
{
                            try
{
                                Console.Clear();
                            }
                            catch
{
                            }
                            Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber2));
                        }
                    }
                    string text3 = "";
                    flag2 = true;
                    Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber2) + " - " + Terraria.ModLoader.ModLoader.versionedName);
                    while (flag2)
                    {
                        Console.WriteLine("");
                        Console.Write(Language.GetTextValue("CLI.EnterSeed"));
                        text3 = ReadLineInput();
                        if (text3 != null)
{
                            if (text3.Length >= 40)
{
                                Console.WriteLine("");
                                Console.WriteLine(Language.GetTextValue("CLI.SeedLengthTooLong", 39));
                                continue;
                            }
                            flag2 = false;
                            try
{
                                Console.Clear();
                            }
                            catch
{
                            }
                        }
                        else
{
                            text3 = "";
                        }
                    }
                    worldName = newWorldName;
                    ActiveWorldFileData = WorldFile.CreateMetadata(worldName, SocialAPI.Cloud != null && SocialAPI.Cloud.EnabledByDefault, GameMode);
                    text3 = text3.Trim();
                    if (text3.Length == 0)
                    {
                        ActiveWorldFileData.SetSeedToRandom();
                    }
                    else
                    {
                        ActiveWorldFileData.SetSeed(text3);
                    }
                    UIWorldCreation.ProcessSpecialWorldSeeds(text3);
                    menuMode = 10;
                    GenerationProgress generationProgress = new GenerationProgress();
                    Task task = WorldGen.CreateNewWorld(generationProgress);
                    flag2 = false;
                    while (menuMode == 10)
                    {
                        if (oldStatusText != statusText && !WorldGen.drunkWorldGen)
{
                            oldStatusText = statusText;
                            Console.WriteLine(statusText);
                        }
                    }
                    try
                    {
                        Console.Clear();
                    }
                    catch
                    {
                    }
                    while (!task.IsCompleted)
                    {
                        statusText = string.Format("{0:0.0%} - " + generationProgress.Message + " - {1:0.0%}", generationProgress.TotalProgress, generationProgress.Value);
                        if (oldStatusText != statusText)
{
                            oldStatusText = statusText;
                            string value4 = statusText;
                            if (WorldGen.notTheBees && !WorldGen.getGoodWorldGen)
{
                                value4 = string.Format("{0:0.0%} - " + Language.GetTextValue("UI.WorldGenEasterEgg_GeneratingBees") + " - {1:0.0%}", generationProgress.TotalProgress, generationProgress.Value);
                            }
                            Console.WriteLine(value4);
                        }
                    }
                    continue;
                }
                case "m":
                case "M":
                    Interface.ServerModMenu(out reloadMods);
                    if (reloadMods)
                    {
                        return;
                    }
                    continue;
                }
                try
                {
                    int num3 = Convert.ToInt32(text2);
                    num3--;
                    if (num3 < 0 || num3 >= WorldList.Count)
                    {
                        continue;
                    }
                    bool flag3 = true;
                    while (flag3)
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber2) + " - " + Terraria.ModLoader.ModLoader.versionedName);
                        Console.WriteLine("");
                        Console.Write(Language.GetTextValue("CLI.SetInitialMaxPlayers"));
                        string text4 = ReadLineInput();
                        try
{
                            if (text4 == "")
{
                                text4 = "16";
                            }
                            int num4 = Convert.ToInt32(text4);
                            if (num4 <= 255 && num4 >= 1)
{
                                SetNetPlayers(num4);
                                flag3 = false;
                            }
                            flag3 = false;
                        }
                        catch
{
                        }
                        try
{
                            Console.Clear();
                        }
                        catch
{
                        }
                    }
                    flag3 = true;
                    while (flag3)
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber2) + " - " + Terraria.ModLoader.ModLoader.versionedName);
                        Console.WriteLine("");
                        Console.Write(Language.GetTextValue("CLI.SetInitialPort"));
                        string text5 = ReadLineInput();
                        try
{
                            if (text5 == "")
{
                                text5 = "7777";
                            }
                            int num5 = Convert.ToInt32(text5);
                            if (num5 <= 65535)
{
                                Netplay.ListenPort = num5;
                                flag3 = false;
                            }
                        }
                        catch
{
                        }
                        try
{
                            Console.Clear();
                        }
                        catch
{
                        }
                    }
                    flag3 = true;
                    while (flag3)
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber2) + " - " + Terraria.ModLoader.ModLoader.versionedName);
                        Console.WriteLine("");
                        Console.Write(Language.GetTextValue("CLI.AutomaticPortForward", Language.GetTextValue("CLI.ShortYes"), Language.GetTextValue("CLI.ShortNo")));
                        string text6 = ReadLineInput();
                        try
{
                            if (text6 == "" || text6.ToLower() == Language.GetTextValue("CLI.ShortYes").ToLower() || text6.ToLower() == Language.GetTextValue("CLI.Yes").ToLower())
{
                                Netplay.UseUPNP = true;
                                flag3 = false;
                            }
                            else if (text6.ToLower() == Language.GetTextValue("CLI.ShortNo").ToLower() || text6.ToLower() == Language.GetTextValue("CLI.No").ToLower())
{
                                Netplay.UseUPNP = false;
                                flag3 = false;
                            }
                        }
                        catch
{
                        }
                        try
{
                            Console.Clear();
                        }
                        catch
{
                        }
                    }
                    Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber2) + " - " + Terraria.ModLoader.ModLoader.versionedName);
                    Console.WriteLine("");
                    Console.Write(Language.GetTextValue("CLI.EnterServerPassword"));
                    Netplay.ServerPassword = ReadLineInput();
                    ActiveWorldFileData = WorldList[num3];
                    flag = false;
                    try
                    {
                        Console.Clear();
                    }
                    catch
                    {
                    }
                }
                catch
                {
                }
            }
        }
        try
        {
            Console.Clear();
        }
        catch
        {
        }
        Task task2 = WorldGen.serverLoadWorld();
        Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber));
        Console.WriteLine("");
        while (!task2.IsCompleted)
        {
            if (WorldFile.LastThrownLoadException == null)
            {
                if (AutogenProgress.TotalProgress != 0.0)
                {
                    statusText = string.Format("{0:0.0%} - " + AutogenProgress.Message + " - {1:0.0%}", AutogenProgress.TotalProgress, AutogenProgress.Value);
                }
                if (oldStatusText != statusText)
                {
                    oldStatusText = statusText;
                    Console.WriteLine(statusText);
                }
            }
        }
        try
        {
            if (WorldFile.LastThrownLoadException == null)
            {
                Console.Clear();
            }
        }
        catch
        {
        }
        Logging.ServerConsoleLine("Running one update...");
        Logging.tML.Info((object)$"Server starting with AllowVanillaClients set to {ModNet.AllowVanillaClients}");
        ((Game)this).Update(new GameTime());
        if (WorldGen.loadFailed || !WorldGen.loadSuccess)
        {
            WriteFancyWorldLoadErrorToConsole();
            if (!autoShutdown)
            {
                Console.ReadKey();
            }
            YouCanSleepNow();
            return;
        }
        Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber));
        Console.WriteLine("");
        Logging.ServerConsoleLine(Language.GetTextValue("CLI.ListeningOnPort", Netplay.ListenPort));
        Console.WriteLine(Language.GetTextValue("CLI.HelpHint"));
        Console.WriteLine("");
        Console.Title = "Terraria Server: " + worldName;
        Stopwatch stopwatch = new Stopwatch();
        if (!autoShutdown || showServerConsole)
        {
            startDedInput();
        }
        stopwatch.Start();
        double delta = 16.666666666666668;
        double target = delta;
        Netplay.StartServer();
        AddSignalTraps();
        gameMenu = false;
        while (!Netplay.Disconnect)
        {
            ServerHangWatchdog.Checkin();
            if (oldStatusText != statusText)
            {
                oldStatusText = statusText;
                Console.WriteLine(statusText);
            }
            if (Netplay.HasClients)
            {
                ((Game)this).Update(new GameTime());
            }
            else if (saveTime.IsRunning)
            {
                saveTime.Stop();
            }
            if (Main.OnTickForThirdPartySoftwareOnly != null)
            {
                Main.OnTickForThirdPartySoftwareOnly();
            }
            double now = stopwatch.ElapsedMilliseconds;
            double remaining = target - now;
            target += delta;
            if (target < now)
            {
                target = now + delta;
            }
            Thread.Sleep(Math.Max((int)remaining, 0));
        }
        if (Netplay.SaveOnServerExit)
        {
            Console.WriteLine(Language.GetTextValue("Net.ServerSavingOnExit"));
            WorldFile.SaveWorld();
        }
        SystemLoader.OnWorldUnload();
        YouCanSleepNow();
    }
References Terraria.Main.ActiveWorldFileData, Terraria.Main.AddSignalTraps(), Terraria.Main.AutogenProgress, Terraria.Main.autoShutdown, Terraria.ModLoader.Engine.ServerHangWatchdog.Checkin(), Terraria.Social.SocialAPI.Cloud, Terraria.ModLoader.Console, Terraria.IO.WorldFile.CreateMetadata(), Terraria.WorldGen.CreateNewWorld(), Terraria.Netplay.Disconnect, Terraria.WorldGen.drunkWorldGen, Terraria.Main.EraseWorld(), Terraria.UI.Game, Terraria.Main.gameMenu, Terraria.Main.GameMode, Terraria.WorldGen.getGoodWorldGen, Terraria.Localization.Language.GetTextValue(), Terraria.Netplay.HasClients, Terraria.IO.WorldFile.LastThrownLoadException, Terraria.Netplay.ListenPort, Terraria.WorldGen.loadFailed, Terraria.WorldGen.loadSuccess, Terraria.Main.LoadWorlds(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.menuMode, Terraria.Main.newWorldName, Terraria.WorldGen.notTheBees, Terraria.Main.oldStatusText, Terraria.Main.OnTickForThirdPartySoftwareOnly, Terraria.ModLoader.SystemLoader.OnWorldUnload(), Terraria.GameContent.UI.States.UIWorldCreation.ProcessSpecialWorldSeeds(), Terraria.Main.ReadLineInput(), Terraria.Netplay.SaveOnServerExit, Terraria.Main.saveTime, Terraria.IO.WorldFile.SaveWorld(), Terraria.ModLoader.Logging.ServerConsoleLine(), Terraria.WorldGen.serverLoadWorld(), Terraria.ModLoader.UI.Interface.ServerModMenu(), Terraria.Main.SetNetPlayers(), Terraria.Main.showServerConsole, Terraria.Main.startDedInput(), Terraria.Netplay.StartServer(), Terraria.Main.statusText, Terraria.ModLoader.Logging.tML, Terraria.ModLoader.ModLoader.versionedName, Terraria.Main.versionNumber, Terraria.Main.versionNumber2, Terraria.Main.WorldList, Terraria.Main.worldName, Terraria.Main.worldPathName, Terraria.Main.WriteFancyWorldLoadErrorToConsole(), and Terraria.Main.YouCanSleepNow().
Referenced by Terraria.Main.DedServ().