TModLoader: Terraria.Main.CraftItem
CraftItem()
static void Terraria.Main.CraftItem (Recipe r) inline static
Definition at line 55070 of file Main.cs.
    {
        if (mouseItem.stack <= 0 || ItemLoader.CanStack(mouseItem, r.createItem))
        {
            Item crafted = r.createItem.Clone();
            crafted.Prefix(-1);
            r.Create();
            RecipeLoader.OnCraft(crafted, r, mouseItem);
            if (mouseItem.stack > 0)
            {
                ItemLoader.StackItems(mouseItem, crafted, out var _);
            }
            else
            {
                mouseItem = crafted;
            }
            mouseItem.position.X = player[myPlayer].position.X + (float)(player[myPlayer].width / 2) - (float)(mouseItem.width / 2);
            mouseItem.position.Y = player[myPlayer].position.Y + (float)(player[myPlayer].height / 2) - (float)(mouseItem.height / 2);
            PopupText.NewText(PopupTextContext.ItemCraft, mouseItem, r.createItem.stack);
            if (mouseItem.type > 0 || r.createItem.type > 0)
            {
                SoundEngine.PlaySound(7);
            }
        }
    }
References Terraria.ModLoader.ItemLoader.CanStack(), Terraria.Entity.height, Terraria.Main.mouseItem, Terraria.Main.myPlayer, Terraria.PopupText.NewText(), Terraria.ModLoader.RecipeLoader.OnCraft(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Item.stack, Terraria.ModLoader.ItemLoader.StackItems(), Terraria.Item.type, and Terraria.Entity.width.
Referenced by Terraria.Main.HoverOverCraftingItemButton(), and Terraria.Initializers.UILinksInitializer.Load().