TModLoader: Terraria.Main.DrawPVPIcons
DrawPVPIcons()
static void Terraria.Main.DrawPVPIcons () inline static private
    {
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0164: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01de: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0201: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_0236: Unknown result type (might be due to invalid IL or missing references)
        //IL_0238: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0258: Unknown result type (might be due to invalid IL or missing references)
        //IL_0264: Unknown result type (might be due to invalid IL or missing references)
        //IL_0278: Unknown result type (might be due to invalid IL or missing references)
        //IL_027d: Unknown result type (might be due to invalid IL or missing references)
        //IL_036c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0403: Unknown result type (might be due to invalid IL or missing references)
        //IL_0408: Unknown result type (might be due to invalid IL or missing references)
        //IL_040a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0414: Unknown result type (might be due to invalid IL or missing references)
        //IL_0419: Unknown result type (might be due to invalid IL or missing references)
        //IL_0391: Unknown result type (might be due to invalid IL or missing references)
        //IL_0396: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03aa: Unknown result type (might be due to invalid IL or missing references)
        if (EquipPage == 1)
        {
            if (hidePVPIcons)
            {
                return;
            }
        }
        else
        {
            hidePVPIcons = false;
        }
        inventoryScale = 0.6f;
        int num = (int)(52f * inventoryScale);
        int num2 = 707 - num * 4 + screenWidth - 800;
        int num3 = 114 + mH + num * 2 + num / 2 - 12;
        if (EquipPage == 2)
        {
            num2 += num + num / 2;
        }
        int num4 = (player[myPlayer].hostile ? 2 : 0);
        if (mouseX > num2 - 7 && mouseX < num2 + 25 && mouseY > num3 - 2 && mouseY < num3 + 37 && !PlayerInput.IgnoreMouseInterface)
        {
            player[myPlayer].mouseInterface = true;
            if (teamCooldown == 0)
            {
                num4++;
            }
            if (mouseLeft && mouseLeftRelease && teamCooldown == 0)
            {
                teamCooldown = teamCooldownLen;
                SoundEngine.PlaySound(12);
                player[myPlayer].hostile = !player[myPlayer].hostile;
                NetMessage.SendData(30, -1, -1, null, myPlayer);
            }
        }
        Rectangle rectangle = TextureAssets.Pvp[0].Frame(4, 6);
        ((Rectangle)(ref rectangle)).Location = new Point(rectangle.Width * num4, rectangle.Height * player[myPlayer].team);
        rectangle.Width -= 2;
        rectangle.Height--;
        spriteBatch.Draw(TextureAssets.Pvp[0].Value, new Vector2((float)(num2 - 10), (float)num3), (Rectangle?)rectangle, Color.White, 0f, Vector2.Zero, Vector2.One, (SpriteEffects)0, 0f);
        UILinkPointNavigator.SetPosition(1550, new Vector2((float)(num2 - 10), (float)num3) + rectangle.Size() * 0.75f);
        num3 += 60;
        num2 -= 10;
        rectangle = TextureAssets.Pvp[1].Frame(6);
        Rectangle r = rectangle;
        for (int i = 0; i < 6; i++)
        {
            ((Rectangle)(ref r)).Location = new Point(num2 + i % 2 * 20, num3 + i / 2 * 20);
            rectangle.X = rectangle.Width * i;
            bool flag = false;
            if (((Rectangle)(ref r)).Contains(MouseScreen.ToPoint()) && !PlayerInput.IgnoreMouseInterface)
            {
                player[myPlayer].mouseInterface = true;
                if (teamCooldown == 0)
                {
                    flag = true;
                }
                if (mouseLeft && mouseLeftRelease && player[myPlayer].team != i && teamCooldown == 0)
                {
                    if (!player[myPlayer].TeamChangeAllowed())
                    {
                        NewText(Lang.misc[84].Value, byte.MaxValue, 240, 20);
                    }
                    else
                    {
                        teamCooldown = teamCooldownLen;
                        SoundEngine.PlaySound(12);
                        player[myPlayer].team = i;
                        NetMessage.SendData(45, -1, -1, null, myPlayer);
                    }
                }
            }
            r.Width = rectangle.Width - 2;
            if (flag)
            {
                spriteBatch.Draw(TextureAssets.Pvp[2].Value, ((Rectangle)(ref r)).Location.ToVector2() + new Vector2(-2f), Color.White);
            }
            Rectangle value = rectangle;
            value.Width -= 2;
            spriteBatch.Draw(TextureAssets.Pvp[1].Value, ((Rectangle)(ref r)).Location.ToVector2(), (Rectangle?)value, Color.White);
            UILinkPointNavigator.SetPosition(1550 + i + 1, ((Rectangle)(ref r)).Location.ToVector2() + r.Size() * 0.75f);
        }
    }
References Terraria.Graphics.Light.Color, Terraria.Main.EquipPage, Terraria.Main.hidePVPIcons, Terraria.Player.hostile, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.inventoryScale, Terraria.Main.mH, Terraria.Lang.misc, Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.MouseScreen, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.NewText(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.TextureAssets.Pvp, Terraria.Main.screenWidth, Terraria.NetMessage.SendData(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.spriteBatch, Terraria.Player.team, Terraria.Main.teamCooldown, Terraria.Main.teamCooldownLen, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.DrawInventory().