TModLoader: Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo
MouseText_DrawItemTooltip_GetLinesInfo()
static void Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo (Item item, ref int yoyoLogo, ref int researchLine, float oldKB, ref int numLines, string[] toolTipLine, bool[] preFixLine, bool[] badPreFixLine, string[] toolTipNames, out int prefixlineIndex) inline static
Definition at line 20053 of file Main.cs.
    {
        //IL_1aaf: Unknown result type (might be due to invalid IL or missing references)
        prefixlineIndex = -1;
        toolTipLine[0] = item.HoverName;
        toolTipNames[0] = "ItemName";
        if (item.favorited)
        {
            toolTipLine[numLines++] = Lang.tip[56].Value;
            toolTipNames[numLines - 1] = "Favorite";
            toolTipLine[numLines++] = Lang.tip[57].Value;
            toolTipNames[numLines - 1] = "FavoriteDesc";
            if (LocalPlayer.chest != -1)
            {
                ChestUI.GetContainerUsageInfo(out var _, out var chestinv);
                if (ChestUI.IsBlockedFromTransferIntoChest(item, chestinv))
                {
                    toolTipLine[numLines++] = Language.GetTextValue("UI.ItemCannotBePlacedInsideItself");
                    toolTipNames[numLines - 1] = "NoTransfer";
                }
            }
        }
        if (item.social)
        {
            toolTipLine[numLines] = Lang.tip[0].Value;
            toolTipNames[numLines] = "Social";
            numLines++;
            toolTipLine[numLines] = Lang.tip[1].Value;
            toolTipNames[numLines] = "SocialDesc";
            numLines++;
        }
        else
        {
            if (item.damage > 0 && (!item.notAmmo || item.useStyle != 0) && (item.type < 71 || item.type > 74 || player[myPlayer].HasItem(905)) && item.DamageType.ShowStatTooltipLine(player[myPlayer], "Damage"))
            {
                LocalizedText tip;
                if (item.DamageType != null)
                {
                    bool addLeadingSpace = !(item.DamageType is VanillaDamageClass);
                    tip = new LocalizedText("", (addLeadingSpace ? " " : "") + item.DamageType.DisplayName);
                }
                else
                {
                    tip = Lang.tip[55];
                }
                int damage = player[myPlayer].GetWeaponDamage(item, forTooltip: true);
                toolTipLine[numLines] = damage + tip.Value;
                toolTipNames[numLines] = "Damage";
                numLines++;
                if (item.DamageType.UseStandardCritCalcs && item.DamageType.ShowStatTooltipLine(player[myPlayer], "CritChance"))
                {
                    int crit = player[myPlayer].GetWeaponCrit(item);
                    toolTipLine[numLines] = crit + Lang.tip[5].Value;
                    toolTipNames[numLines] = "CritChance";
                    numLines++;
                }
                if (item.useStyle != 0 && item.DamageType.ShowStatTooltipLine(player[myPlayer], "Speed"))
                {
                    if (item.useAnimation <= 8)
                    {
                        toolTipLine[numLines] = Lang.tip[6].Value;
                    }
                    else if (item.useAnimation <= 20)
                    {
                        toolTipLine[numLines] = Lang.tip[7].Value;
                    }
                    else if (item.useAnimation <= 25)
                    {
                        toolTipLine[numLines] = Lang.tip[8].Value;
                    }
                    else if (item.useAnimation <= 30)
                    {
                        toolTipLine[numLines] = Lang.tip[9].Value;
                    }
                    else if (item.useAnimation <= 35)
                    {
                        toolTipLine[numLines] = Lang.tip[10].Value;
                    }
                    else if (item.useAnimation <= 45)
                    {
                        toolTipLine[numLines] = Lang.tip[11].Value;
                    }
                    else if (item.useAnimation <= 55)
                    {
                        toolTipLine[numLines] = Lang.tip[12].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = Lang.tip[13].Value;
                    }
                    toolTipNames[numLines] = "Speed";
                    numLines++;
                    if (item.DamageType == DamageClass.MeleeNoSpeed || ItemID.Sets.BonusAttackSpeedMultiplier[item.type] == 0f)
                    {
                        if (Terraria.ModLoader.ModLoader.attackSpeedScalingTooltipVisibility == 0)
{
                            toolTipLine[numLines] = Language.GetTextValue("tModLoader.NoAttackSpeedScaling");
                            toolTipNames[numLines] = "NoSpeedScaling";
                            numLines++;
                        }
                    }
                    else if (ItemID.Sets.BonusAttackSpeedMultiplier[item.type] != 1f && Terraria.ModLoader.ModLoader.attackSpeedScalingTooltipVisibility <= 1)
                    {
                        int attackSpeedScaling = (int)(ItemID.Sets.BonusAttackSpeedMultiplier[item.type] * 100f);
                        toolTipLine[numLines] = Language.GetTextValue("tModLoader.SpecialAttackSpeedScaling", attackSpeedScaling);
                        toolTipNames[numLines] = "SpecialSpeedScaling";
                        numLines++;
                    }
                }
                if (item.DamageType.ShowStatTooltipLine(player[myPlayer], "Knockback"))
                {
                    float num15 = player[myPlayer].GetWeaponKnockback(item, item.knockBack);
                    if (num15 == 0f)
                    {
                        toolTipLine[numLines] = Lang.tip[14].Value;
                    }
                    else if ((double)num15 <= 1.5)
                    {
                        toolTipLine[numLines] = Lang.tip[15].Value;
                    }
                    else if (num15 <= 3f)
                    {
                        toolTipLine[numLines] = Lang.tip[16].Value;
                    }
                    else if (num15 <= 4f)
                    {
                        toolTipLine[numLines] = Lang.tip[17].Value;
                    }
                    else if (num15 <= 6f)
                    {
                        toolTipLine[numLines] = Lang.tip[18].Value;
                    }
                    else if (num15 <= 7f)
                    {
                        toolTipLine[numLines] = Lang.tip[19].Value;
                    }
                    else if (num15 <= 9f)
                    {
                        toolTipLine[numLines] = Lang.tip[20].Value;
                    }
                    else if (num15 <= 11f)
                    {
                        toolTipLine[numLines] = Lang.tip[21].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = Lang.tip[22].Value;
                    }
                    toolTipNames[numLines] = "Knockback";
                    numLines++;
                }
            }
            if (item.fishingPole > 0)
            {
                toolTipLine[numLines] = Language.GetTextValue("GameUI.PrecentFishingPower", item.fishingPole);
                toolTipNames[numLines] = "FishingPower";
                numLines++;
                toolTipLine[numLines] = Language.GetTextValue("GameUI.BaitRequired");
                toolTipNames[numLines] = "NeedsBait";
                numLines++;
            }
            if (item.bait > 0)
            {
                toolTipLine[numLines] = Language.GetTextValue("GameUI.BaitPower", item.bait);
                toolTipNames[numLines] = "BaitPower";
                numLines++;
            }
            if (item.headSlot > 0 || item.bodySlot > 0 || item.legSlot > 0 || item.accessory || projHook[item.shoot] || item.mountType != -1 || (item.buffType > 0 && (lightPet[item.buffType] || vanityPet[item.buffType])))
            {
                if ((item.type == 854 || item.type == 3035) && npcShop > 0)
                {
                    toolTipLine[numLines] = Lang.tip[60].Value;
                }
                else
                {
                    toolTipLine[numLines] = Lang.tip[23].Value;
                }
                toolTipNames[numLines] = "Equipable";
                numLines++;
            }
            if (item.tileWand > 0)
            {
                toolTipLine[numLines] = Lang.tip[52].Value + Lang.GetItemNameValue(item.tileWand);
                toolTipNames[numLines] = "WandConsumes";
                numLines++;
            }
            if (item.questItem)
            {
                toolTipLine[numLines] = Lang.inter[65].Value;
                toolTipNames[numLines] = "Quest";
                numLines++;
            }
            if (item.vanity)
            {
                toolTipLine[numLines] = Lang.tip[24].Value;
                toolTipNames[numLines] = "Vanity";
                numLines++;
            }
            if (item.defense > 0)
            {
                toolTipLine[numLines] = item.defense + Lang.tip[25].Value;
                toolTipNames[numLines] = "Defense";
                numLines++;
            }
            if (item.pick > 0)
            {
                toolTipLine[numLines] = item.pick + Lang.tip[26].Value;
                toolTipNames[numLines] = "PickPower";
                numLines++;
            }
            if (item.axe > 0)
            {
                toolTipLine[numLines] = item.axe * 5 + Lang.tip[27].Value;
                toolTipNames[numLines] = "AxePower";
                numLines++;
            }
            if (item.hammer > 0)
            {
                toolTipLine[numLines] = item.hammer + Lang.tip[28].Value;
                toolTipNames[numLines] = "HammerPower";
                numLines++;
            }
            if (item.tileBoost != 0)
            {
                int tileBoost = item.tileBoost;
                if (tileBoost > 0)
                {
                    toolTipLine[numLines] = "+" + tileBoost + Lang.tip[54].Value;
                }
                else
                {
                    toolTipLine[numLines] = tileBoost + Lang.tip[54].Value;
                }
                toolTipNames[numLines] = "TileBoost";
                numLines++;
            }
            if (item.healLife > 0)
            {
                if (item.type == 3001)
                {
                    int healLife = item.healLife;
                    int num16 = 120;
                    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.RestoresLifeRange", healLife, num16);
                }
                else
                {
                    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.RestoresLife", item.healLife);
                }
                toolTipNames[numLines] = "HealLife";
                numLines++;
            }
            if (item.healMana > 0)
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.RestoresMana", item.healMana);
                toolTipNames[numLines] = "HealMana";
                numLines++;
            }
            if (item.mana > 0)
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.UsesMana", player[myPlayer].GetManaCost(item));
                toolTipNames[numLines] = "UseMana";
                numLines++;
            }
            if (item.createWall > 0 || item.createTile > -1)
            {
                if (item.type != 213 && item.type != 5295 && item.tileWand < 1)
                {
                    toolTipLine[numLines] = Lang.tip[33].Value;
                    toolTipNames[numLines] = "Placeable";
                    numLines++;
                }
            }
            else if (item.ammo > 0 && !item.notAmmo)
            {
                toolTipLine[numLines] = Lang.tip[34].Value;
                toolTipNames[numLines] = "Ammo";
                numLines++;
            }
            else if (item.consumable && !item.chlorophyteExtractinatorConsumable)
            {
                toolTipLine[numLines] = Lang.tip[35].Value;
                toolTipNames[numLines] = "Consumable";
                numLines++;
            }
            if (item.material)
            {
                toolTipLine[numLines] = Lang.tip[36].Value;
                toolTipNames[numLines] = "Material";
                numLines++;
            }
            if (item.ToolTip != null)
            {
                for (int i = 0; i < item.ToolTip.Lines; i++)
                {
                    if (i == 0 && ItemID.Sets.UsesCursedByPlanteraTooltip[item.type] && !NPC.downedPlantBoss)
                    {
                        toolTipLine[numLines] = Lang.tip[59].Value;
                        toolTipNames[numLines] = "Tooltip" + i;
                        numLines++;
                    }
                    else
                    {
                        toolTipLine[numLines] = item.ToolTip.GetLine(i);
                        toolTipNames[numLines] = "Tooltip" + i;
                        numLines++;
                    }
                }
            }
            if (tenthAnniversaryWorld && item.type == 238)
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.WizardHatDuringAnniversary");
                numLines++;
            }
            if (getGoodWorld && remixWorld)
            {
                if (item.type == 556 || item.type == 557 || item.type == 544)
                {
                    numLines--;
                    toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.MechSummonDuringEverything");
                    numLines++;
                }
            }
            else if (item.type == 5334)
            {
                numLines--;
                toolTipLine[numLines] = "";
                numLines--;
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.MechdusaSummonNotDuringEverything");
                numLines++;
            }
            if ((item.type == 3818 || item.type == 3819 || item.type == 3820 || item.type == 3824 || item.type == 3825 || item.type == 3826 || item.type == 3829 || item.type == 3830 || item.type == 3831 || item.type == 3832 || item.type == 3833 || item.type == 3834) && !player[myPlayer].downedDD2EventAnyDifficulty)
            {
                toolTipLine[numLines] = Lang.misc[104].Value;
                toolTipNames[numLines] = "EtherianManaWarning";
                numLines++;
            }
            if (item.buffType > 0 && BuffID.Sets.IsWellFed[item.buffType] && expertMode)
            {
                toolTipLine[numLines] = Lang.misc[40].Value;
                toolTipNames[numLines] = "WellFedExpert";
                numLines++;
            }
            if (item.buffTime > 0)
            {
                string text = ((item.buffTime / 60 < 60) ? Language.GetTextValue("CommonItemTooltip.SecondDuration", Math.Round((double)item.buffTime / 60.0)) : Language.GetTextValue("CommonItemTooltip.MinuteDuration", Math.Round((double)(item.buffTime / 60) / 60.0)));
                toolTipNames[numLines] = "BuffTime";
                toolTipLine[numLines] = text;
                numLines++;
            }
            if (item.type == 3262 || item.type == 3282 || item.type == 3283 || item.type == 3284 || item.type == 3285 || item.type == 3286 || item.type == 3316 || item.type == 3315 || item.type == 3317 || item.type == 3291 || item.type == 3389)
            {
                toolTipLine[numLines] = " ";
                yoyoLogo = numLines;
                toolTipNames[numLines] = "OneDropLogo";
                numLines++;
            }
            if (item.prefix > 0)
            {
                Item item2 = tooltipPrefixComparisonItem;
                if (item2 == null || item2.netID != item.netID)
                {
                    item2 = new Item();
                    item2.netDefaults(item.netID);
                }
                if (item2.damage != item.damage)
                {
                    double num17 = (float)item.damage - (float)item2.damage;
                    num17 = num17 / (double)item2.damage * 100.0;
                    num17 = Math.Round(num17);
                    if (num17 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num17 + Lang.tip[39].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num17 + Lang.tip[39].Value;
                    }
                    if (num17 < 0.0)
                    {
                        badPreFixLine[numLines] = true;
                    }
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixDamage";
                    numLines++;
                }
                if (item2.useAnimation != item.useAnimation)
                {
                    double num18 = (float)item.useAnimation - (float)item2.useAnimation;
                    num18 = num18 / (double)item2.useAnimation * 100.0;
                    num18 = Math.Round(num18);
                    num18 *= -1.0;
                    if (num18 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num18 + Lang.tip[40].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num18 + Lang.tip[40].Value;
                    }
                    if (num18 < 0.0)
                    {
                        badPreFixLine[numLines] = true;
                    }
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixSpeed";
                    numLines++;
                }
                if (item2.crit != item.crit)
                {
                    double num10 = (float)item.crit - (float)item2.crit;
                    if (num10 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num10 + Lang.tip[41].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num10 + Lang.tip[41].Value;
                    }
                    if (num10 < 0.0)
                    {
                        badPreFixLine[numLines] = true;
                    }
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixCritChance";
                    numLines++;
                }
                if (item2.mana != item.mana)
                {
                    double num11 = (float)item.mana - (float)item2.mana;
                    num11 = num11 / (double)item2.mana * 100.0;
                    num11 = Math.Round(num11);
                    if (num11 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num11 + Lang.tip[42].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num11 + Lang.tip[42].Value;
                    }
                    if (num11 > 0.0)
                    {
                        badPreFixLine[numLines] = true;
                    }
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixUseMana";
                    numLines++;
                }
                if (item2.scale != item.scale)
                {
                    double num12 = item.scale - item2.scale;
                    num12 = num12 / (double)item2.scale * 100.0;
                    num12 = Math.Round(num12);
                    if (num12 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num12 + Lang.tip[43].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num12 + Lang.tip[43].Value;
                    }
                    if (num12 < 0.0)
                    {
                        badPreFixLine[numLines] = true;
                    }
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixSize";
                    numLines++;
                }
                if (item2.shootSpeed != item.shootSpeed)
                {
                    double num13 = item.shootSpeed - item2.shootSpeed;
                    num13 = num13 / (double)item2.shootSpeed * 100.0;
                    num13 = Math.Round(num13);
                    if (num13 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num13 + Lang.tip[44].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num13 + Lang.tip[44].Value;
                    }
                    if (num13 < 0.0)
                    {
                        badPreFixLine[numLines] = true;
                    }
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixShootSpeed";
                    numLines++;
                }
                if (item2.knockBack != oldKB)
                {
                    double num14 = oldKB - item2.knockBack;
                    num14 = num14 / (double)item2.knockBack * 100.0;
                    num14 = Math.Round(num14);
                    if (num14 > 0.0)
                    {
                        toolTipLine[numLines] = "+" + num14 + Lang.tip[45].Value;
                    }
                    else
                    {
                        toolTipLine[numLines] = num14 + Lang.tip[45].Value;
                    }
                    if (num14 < 0.0)
                    {
                        badPreFixLine[numLines] = true;
                    }
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixKnockback";
                    numLines++;
                }
                if (item.prefix == 62)
                {
                    toolTipLine[numLines] = "+1" + Lang.tip[25].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccDefense";
                    numLines++;
                }
                if (item.prefix == 63)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[25].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccDefense";
                    numLines++;
                }
                if (item.prefix == 64)
                {
                    toolTipLine[numLines] = "+3" + Lang.tip[25].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccDefense";
                    numLines++;
                }
                if (item.prefix == 65)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[25].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccDefense";
                    numLines++;
                }
                if (item.prefix == 66)
                {
                    toolTipLine[numLines] = "+20 " + Lang.tip[31].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccMaxMana";
                    numLines++;
                }
                if (item.prefix == 67)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[5].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccCritChance";
                    numLines++;
                }
                if (item.prefix == 68)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[5].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccCritChance";
                    numLines++;
                }
                if (item.prefix == 69)
                {
                    toolTipLine[numLines] = "+1" + Lang.tip[39].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccDamage";
                    numLines++;
                }
                if (item.prefix == 70)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[39].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccDamage";
                    numLines++;
                }
                if (item.prefix == 71)
                {
                    toolTipLine[numLines] = "+3" + Lang.tip[39].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccDamage";
                    numLines++;
                }
                if (item.prefix == 72)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[39].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccDamage";
                    numLines++;
                }
                if (item.prefix == 73)
                {
                    toolTipLine[numLines] = "+1" + Lang.tip[46].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccMoveSpeed";
                    numLines++;
                }
                if (item.prefix == 74)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[46].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccMoveSpeed";
                    numLines++;
                }
                if (item.prefix == 75)
                {
                    toolTipLine[numLines] = "+3" + Lang.tip[46].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccMoveSpeed";
                    numLines++;
                }
                if (item.prefix == 76)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[46].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccMoveSpeed";
                    numLines++;
                }
                if (item.prefix == 77)
                {
                    toolTipLine[numLines] = "+1" + Lang.tip[47].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccMeleeSpeed";
                    numLines++;
                }
                if (item.prefix == 78)
                {
                    toolTipLine[numLines] = "+2" + Lang.tip[47].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccMeleeSpeed";
                    numLines++;
                }
                if (item.prefix == 79)
                {
                    toolTipLine[numLines] = "+3" + Lang.tip[47].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccMeleeSpeed";
                    numLines++;
                }
                if (item.prefix == 80)
                {
                    toolTipLine[numLines] = "+4" + Lang.tip[47].Value;
                    preFixLine[numLines] = true;
                    toolTipNames[numLines] = "PrefixAccMeleeSpeed";
                    numLines++;
                }
                prefixlineIndex = numLines;
            }
            if (item.wornArmor && player[myPlayer].setBonus != "")
            {
                toolTipLine[numLines] = Lang.tip[48].Value + " " + player[myPlayer].setBonus;
                toolTipNames[numLines] = "SetBonus";
                numLines++;
            }
        }
        if (item.expert)
        {
            toolTipLine[numLines] = Language.GetTextValue("GameUI.Expert");
            toolTipNames[numLines] = "Expert";
            numLines++;
        }
        if (item.master)
        {
            toolTipLine[numLines] = Language.GetTextValue("GameUI.Master");
            toolTipNames[numLines] = "Master";
            numLines++;
        }
        if ((item.tooltipContext == 0 || item.tooltipContext == 2 || item.tooltipContext == 1 || item.tooltipContext == 3 || item.tooltipContext == 4 || item.tooltipContext == 32 || item.tooltipContext == 15 || item.tooltipContext == 6 || item.tooltipContext == 22 || item.tooltipContext == 7 || item.tooltipContext == 5) && LocalPlayer.difficulty == 3 && CreativeItemSacrificesCatalog.Instance.TryGetSacrificeCountCapToUnlockInfiniteItems(item.type, out var amountNeeded))
        {
            int sacrificeCount = LocalPlayerCreativeTracker.ItemSacrifices.GetSacrificeCount(item.type);
            if (amountNeeded - sacrificeCount > 0)
            {
                toolTipLine[numLines] = Language.GetTextValue("CommonItemTooltip.CreativeSacrificeNeeded", amountNeeded - sacrificeCount);
                researchLine = numLines;
                toolTipNames[numLines] = "JourneyResearch";
                numLines++;
            }
        }
        if (item.StatsModifiedBy.Count > 0)
        {
            if (keyState.PressingShift())
            {
                string modNames = string.Join(", ", item.StatsModifiedBy.Select((Mod m) => m.DisplayName));
                toolTipLine[numLines] = Language.GetTextValue("tModLoader.ModifiedByMods") + modNames;
            }
            else
            {
                toolTipLine[numLines] = Language.GetTextValue("tModLoader.ModifiedByModsHoldSHIFT");
            }
            toolTipNames[numLines] = "ModifiedByMods";
            numLines++;
        }
        string bestiaryNotes = item.BestiaryNotes;
        if (!string.IsNullOrWhiteSpace(bestiaryNotes))
        {
            string[] array = bestiaryNotes.Split('\n');
            foreach (string text2 in array)
            {
                toolTipLine[numLines++] = text2;
                toolTipNames[numLines - 1] = "BestiaryNotes";
            }
        }
    }
References Terraria.Item.accessory, Terraria.Item.ammo, Terraria.ModLoader.ModLoader.attackSpeedScalingTooltipVisibility, Terraria.Item.axe, Terraria.Item.bait, Terraria.Item.BestiaryNotes, Terraria.Item.bodySlot, Terraria.ID.ItemID.Sets.BonusAttackSpeedMultiplier, Terraria.Item.buffTime, Terraria.Item.buffType, Terraria.Player.chest, Terraria.Item.chlorophyteExtractinatorConsumable, Terraria.Item.consumable, Terraria.Item.createTile, Terraria.Item.createWall, Terraria.Item.crit, Terraria.Item.damage, Terraria.Item.DamageType, Terraria.Item.defense, Terraria.Player.difficulty, Terraria.ModLoader.DamageClass.DisplayName, Terraria.Player.downedDD2EventAnyDifficulty, Terraria.NPC.downedPlantBoss, Terraria.Item.expert, Terraria.Main.expertMode, Terraria.Item.favorited, Terraria.Item.fishingPole, Terraria.UI.ChestUI.GetContainerUsageInfo(), Terraria.Main.getGoodWorld, Terraria.Lang.GetItemNameValue(), Terraria.UI.ItemTooltip.GetLine(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.GetSacrificeCount(), Terraria.Localization.Language.GetTextValue(), Terraria.Player.GetWeaponCrit(), Terraria.Player.GetWeaponDamage(), Terraria.Player.GetWeaponKnockback(), Terraria.Item.hammer, Terraria.Player.HasItem(), Terraria.Item.headSlot, Terraria.Item.healLife, Terraria.Item.healMana, Terraria.Item.HoverName, Terraria.GameContent.Creative.CreativeItemSacrificesCatalog.Instance, Terraria.Lang.inter, Terraria.UI.ChestUI.IsBlockedFromTransferIntoChest(), Terraria.ID.BuffID.Sets.IsWellFed, Terraria.Main.item, Terraria.GameContent.Creative.CreativeUnlocksTracker.ItemSacrifices, Terraria.Main.keyState, Terraria.Item.knockBack, Terraria.Item.legSlot, Terraria.Main.lightPet, Terraria.UI.ItemTooltip.Lines, Terraria.Main.LocalPlayer, Terraria.Main.LocalPlayerCreativeTracker, Terraria.Item.mana, Terraria.Item.master, Terraria.Item.material, Terraria.ModLoader.DamageClass.MeleeNoSpeed, Terraria.Lang.misc, Terraria.Item.mountType, Terraria.Main.myPlayer, Terraria.Item.netID, Terraria.Item.notAmmo, Terraria.Main.npcShop, Terraria.Item.pick, Terraria.Main.player, Terraria.Item.prefix, Terraria.Main.projHook, Terraria.Item.questItem, Terraria.Main.remixWorld, Terraria.Item.scale, Terraria.Player.setBonus, Terraria.Item.shoot, Terraria.Item.shootSpeed, Terraria.ModLoader.DamageClass.ShowStatTooltipLine(), Terraria.Item.social, Terraria.Item.StatsModifiedBy, Terraria.Main.tenthAnniversaryWorld, Terraria.Item.tileBoost, Terraria.Item.tileWand, Terraria.Lang.tip, Terraria.Item.ToolTip, Terraria.Item.tooltipContext, Terraria.Main.tooltipPrefixComparisonItem, Terraria.GameContent.Creative.CreativeItemSacrificesCatalog.TryGetSacrificeCountCapToUnlockInfiniteItems(), Terraria.Item.type, Terraria.Item.useAnimation, Terraria.ID.ItemID.Sets.UsesCursedByPlanteraTooltip, Terraria.ModLoader.DamageClass.UseStandardCritCalcs, Terraria.Item.useStyle, Terraria.Localization.LocalizedText.Value, Terraria.Item.vanity, Terraria.Main.vanityPet, and Terraria.Item.wornArmor.
Referenced by Terraria.GameContent.Creative.ItemFilters.BySearch.FitsFilter(), and Terraria.Main.MouseText_DrawItemTooltip().