TModLoader: Terraria.Main.UpdateTime_SpawnTownNPCs
UpdateTime_SpawnTownNPCs()
static void Terraria.Main.UpdateTime_SpawnTownNPCs () inline static private
Definition at line 82643 of file Main.cs.
    {
        double worldUpdateRate = WorldGen.GetWorldUpdateRate();
        if (netMode == 1 || worldUpdateRate <= 0.0)
        {
            return;
        }
        checkForSpawns++;
        if ((double)checkForSpawns < 7200.0 / worldUpdateRate)
        {
            return;
        }
        checkForSpawns = 0;
        int num = 0;
        for (int i = 0; i < 255; i++)
        {
            if (player[i].active)
            {
                num++;
            }
        }
        for (int j = 0; j < townNPCCanSpawn.Length; j++)
        {
            townNPCCanSpawn[j] = false;
        }
        WorldGen.prioritizedTownNPCType = 0;
        int num12 = 0;
        int num23 = 0;
        int num34 = 0;
        int num38 = 0;
        int num39 = 0;
        int num40 = 0;
        int num41 = 0;
        int num42 = 0;
        int num2 = 0;
        int num3 = 0;
        int num4 = 0;
        int num5 = 0;
        int num6 = 0;
        int num7 = 0;
        int num8 = 0;
        int num9 = 0;
        int num10 = 0;
        int num11 = 0;
        int num13 = 0;
        int num14 = 0;
        int num15 = 0;
        int num16 = 0;
        int num17 = 0;
        int num18 = 0;
        int num19 = 0;
        int num20 = 0;
        int num21 = 0;
        int num22 = 0;
        int num24 = 0;
        int num25 = 0;
        int num26 = 0;
        int num27 = 0;
        int num28 = 0;
        int num29 = 0;
        int num30 = 0;
        int num31 = 0;
        int num32 = 0;
        int num33 = 0;
        int num35 = 0;
        for (int k = 0; k < 200; k++)
        {
            if (npc[k].active && npc[k].townNPC)
            {
                if (npc[k].type != 368 && npc[k].type != 37 && npc[k].type != 453 && !npc[k].homeless)
                {
                    WorldGen.QuickFindHome(k);
                }
                if (npc[k].type == 37)
                {
                    num40++;
                }
                if (npc[k].type == 17)
                {
                    num12++;
                }
                if (npc[k].type == 18)
                {
                    num23++;
                }
                if (npc[k].type == 19)
                {
                    num38++;
                }
                if (npc[k].type == 20)
                {
                    num34++;
                }
                if (npc[k].type == 22)
                {
                    num39++;
                }
                if (npc[k].type == 38)
                {
                    num41++;
                }
                if (npc[k].type == 54)
                {
                    num42++;
                }
                if (npc[k].type == 107)
                {
                    num3++;
                }
                if (npc[k].type == 108)
                {
                    num2++;
                }
                if (npc[k].type == 124)
                {
                    num4++;
                }
                if (npc[k].type == 142)
                {
                    num5++;
                }
                if (npc[k].type == 160)
                {
                    num6++;
                }
                if (npc[k].type == 178)
                {
                    num7++;
                }
                if (npc[k].type == 207)
                {
                    num8++;
                }
                if (npc[k].type == 208)
                {
                    num9++;
                }
                if (npc[k].type == 209)
                {
                    num10++;
                }
                if (npc[k].type == 227)
                {
                    num11++;
                }
                if (npc[k].type == 228)
                {
                    num13++;
                }
                if (npc[k].type == 229)
                {
                    num14++;
                }
                if (npc[k].type == 353)
                {
                    num15++;
                }
                if (npc[k].type == 369)
                {
                    num16++;
                }
                if (npc[k].type == 441)
                {
                    num17++;
                }
                if (npc[k].type == 550)
                {
                    num18++;
                }
                if (npc[k].type == 588)
                {
                    num19++;
                }
                if (npc[k].type == 633)
                {
                    num20++;
                }
                if (npc[k].type == 637)
                {
                    num21++;
                }
                if (npc[k].type == 638)
                {
                    num22++;
                }
                if (npc[k].type == 656)
                {
                    num24++;
                }
                if (npc[k].type == 670)
                {
                    num25++;
                }
                if (npc[k].type == 678)
                {
                    num26++;
                }
                if (npc[k].type == 679)
                {
                    num27++;
                }
                if (npc[k].type == 680)
                {
                    num28++;
                }
                if (npc[k].type == 681)
                {
                    num29++;
                }
                if (npc[k].type == 682)
                {
                    num30++;
                }
                if (npc[k].type == 683)
                {
                    num31++;
                }
                if (npc[k].type == 684)
                {
                    num32++;
                }
                if (npc[k].type == 663)
                {
                    num33++;
                }
                num35++;
            }
        }
        if (WorldGen.prioritizedTownNPCType == 0)
        {
            bool flag = NPC.SpawnAllowed_Merchant();
            bool flag2 = NPC.SpawnAllowed_ArmsDealer();
            bool flag3 = NPC.SpawnAllowed_Nurse();
            bool flag4 = NPC.SpawnAllowed_DyeTrader();
            bool flag5 = NPC.SpawnAllowed_Demolitionist();
            BestiaryUnlockProgressReport bestiaryProgressReport = GetBestiaryProgressReport();
            if (!NPC.downedBoss3 && num40 == 0)
            {
                int num36 = NPC.NewNPC(NPC.GetSpawnSourceForTownSpawn(), dungeonX * 16 + 8, dungeonY * 16, 37);
                npc[num36].homeless = false;
                npc[num36].homeTileX = dungeonX;
                npc[num36].homeTileY = dungeonY;
            }
            bool flag6 = false;
            if (rand.Next(40) == 0)
            {
                flag6 = true;
            }
            bool flag7 = flag6 && num35 >= 14;
            if (NPC.unlockedPartyGirlSpawn)
            {
                flag7 = true;
            }
            bool flag8 = BirthdayParty.GenuineParty;
            if (NPC.unlockedSlimeGreenSpawn)
            {
                flag8 = true;
            }
            if (num39 < 1)
            {
                townNPCCanSpawn[22] = true;
            }
            if (flag && num12 < 1)
            {
                townNPCCanSpawn[17] = true;
            }
            if (flag3 && num23 < 1 && num12 > 0)
            {
                townNPCCanSpawn[18] = true;
            }
            if (flag2 && num38 < 1)
            {
                townNPCCanSpawn[19] = true;
            }
            if ((NPC.downedBoss1 || NPC.downedBoss2 || NPC.downedBoss3) && num34 < 1)
            {
                townNPCCanSpawn[20] = true;
            }
            if (flag5 && num12 > 0 && num41 < 1)
            {
                townNPCCanSpawn[38] = true;
            }
            if (NPC.savedStylist && num15 < 1)
            {
                townNPCCanSpawn[353] = true;
            }
            if (NPC.savedAngler && num16 < 1)
            {
                townNPCCanSpawn[369] = true;
            }
            if (NPC.downedBoss3 && num42 < 1)
            {
                townNPCCanSpawn[54] = true;
            }
            if (NPC.savedGoblin && num3 < 1)
            {
                townNPCCanSpawn[107] = true;
            }
            if (NPC.savedTaxCollector && num17 < 1)
            {
                townNPCCanSpawn[441] = true;
            }
            if (NPC.savedWizard && num2 < 1)
            {
                townNPCCanSpawn[108] = true;
            }
            if (NPC.savedMech && num4 < 1)
            {
                townNPCCanSpawn[124] = true;
            }
            if (NPC.downedFrost && num5 < 1 && xMas)
            {
                townNPCCanSpawn[142] = true;
            }
            if (((tenthAnniversaryWorld && !remixWorld) || NPC.downedMechBossAny) && num7 < 1)
            {
                townNPCCanSpawn[178] = true;
            }
            if (flag4 && num8 < 1 && num35 >= 4)
            {
                townNPCCanSpawn[207] = true;
            }
            if (NPC.downedQueenBee && num13 < 1)
            {
                townNPCCanSpawn[228] = true;
            }
            if (NPC.downedPirates && num14 < 1)
            {
                townNPCCanSpawn[229] = true;
            }
            if (num6 < 1 && hardMode)
            {
                townNPCCanSpawn[160] = true;
            }
            if (hardMode && NPC.downedPlantBoss && num10 < 1)
            {
                townNPCCanSpawn[209] = true;
            }
            if (num35 >= 8 && num11 < 1)
            {
                townNPCCanSpawn[227] = true;
            }
            if (flag7 && num9 < 1)
            {
                townNPCCanSpawn[208] = true;
            }
            if (NPC.savedBartender && num18 < 1)
            {
                townNPCCanSpawn[550] = true;
            }
            if (NPC.savedGolfer && num19 < 1)
            {
                townNPCCanSpawn[588] = true;
            }
            if (bestiaryProgressReport.CompletionPercent >= 0.1f && num20 < 1)
            {
                townNPCCanSpawn[633] = true;
            }
            if (NPC.boughtCat && num21 < 1)
            {
                townNPCCanSpawn[637] = true;
            }
            if (NPC.boughtDog && num22 < 1)
            {
                townNPCCanSpawn[638] = true;
            }
            if (NPC.boughtBunny && num24 < 1)
            {
                townNPCCanSpawn[656] = true;
            }
            if (NPC.unlockedSlimeBlueSpawn && num25 < 1)
            {
                townNPCCanSpawn[670] = true;
            }
            if (flag8 && num26 < 1)
            {
                townNPCCanSpawn[678] = true;
            }
            if (NPC.unlockedSlimeOldSpawn && num27 < 1)
            {
                townNPCCanSpawn[679] = true;
            }
            if (NPC.unlockedSlimePurpleSpawn && num28 < 1)
            {
                townNPCCanSpawn[680] = true;
            }
            if (NPC.unlockedSlimeRainbowSpawn && num29 < 1)
            {
                townNPCCanSpawn[681] = true;
            }
            if (NPC.unlockedSlimeRedSpawn && num30 < 1)
            {
                townNPCCanSpawn[682] = true;
            }
            if (NPC.unlockedSlimeYellowSpawn && num31 < 1)
            {
                townNPCCanSpawn[683] = true;
            }
            if (NPC.unlockedSlimeCopperSpawn && num32 < 1)
            {
                townNPCCanSpawn[684] = true;
            }
            bool flag9 = num12 > 0 && num23 > 0 && num34 > 0 && num38 > 0 && num39 > 0 && num41 > 0 && num42 > 0 && num2 > 0 && num3 > 0 && num4 > 0 && num6 > 0 && num7 > 0 && num8 > 0 && num9 > 0 && num10 > 0 && num11 > 0 && num13 > 0 && num14 > 0 && num15 > 0 && num16 > 0 && num17 > 0 && num18 > 0 && num19 > 0 && num20 > 0;
            if (tenthAnniversaryWorld && !remixWorld)
            {
                flag9 = true;
            }
            if (NPC.unlockedPrincessSpawn)
            {
                flag9 = true;
            }
            if (flag9 && num33 < 1)
            {
                townNPCCanSpawn[663] = true;
            }
            int num37 = WorldGen.prioritizedTownNPCType;
            if (num37 == 0 && NPC.boughtCat && num21 < 1)
            {
                num37 = 637;
            }
            if (num37 == 0 && NPC.boughtDog && num22 < 1)
            {
                num37 = 638;
            }
            if (num37 == 0 && NPC.boughtBunny && num24 < 1)
            {
                num37 = 656;
            }
            if (num37 == 0 && NPC.unlockedSlimeBlueSpawn && num25 < 1)
            {
                num37 = 670;
            }
            if (num37 == 0 && flag8 && num26 < 1)
            {
                num37 = 678;
            }
            if (num37 == 0 && NPC.unlockedSlimeOldSpawn && num27 < 1)
            {
                num37 = 679;
            }
            if (num37 == 0 && NPC.unlockedSlimePurpleSpawn && num28 < 1)
            {
                num37 = 680;
            }
            if (num37 == 0 && NPC.unlockedSlimeRainbowSpawn && num29 < 1)
            {
                num37 = 681;
            }
            if (num37 == 0 && NPC.unlockedSlimeRedSpawn && num30 < 1)
            {
                num37 = 682;
            }
            if (num37 == 0 && NPC.unlockedSlimeYellowSpawn && num31 < 1)
            {
                num37 = 683;
            }
            if (num37 == 0 && NPC.unlockedSlimeCopperSpawn && num32 < 1)
            {
                num37 = 684;
            }
            if (num37 == 0 && num39 < 1)
            {
                num37 = 22;
            }
            if (num37 == 0 && flag && num12 < 1)
            {
                num37 = 17;
            }
            if (num37 == 0 && flag3 && num23 < 1 && num12 > 0)
            {
                num37 = 18;
            }
            if (num37 == 0 && flag2 && num38 < 1)
            {
                num37 = 19;
            }
            if (num37 == 0 && NPC.savedGoblin && num3 < 1)
            {
                num37 = 107;
            }
            if (num37 == 0 && NPC.savedTaxCollector && num17 < 1)
            {
                num37 = 441;
            }
            if (num37 == 0 && NPC.savedWizard && num2 < 1)
            {
                num37 = 108;
            }
            if (num37 == 0 && hardMode && num6 < 1)
            {
                num37 = 160;
            }
            if (num37 == 0 && (NPC.downedBoss1 || NPC.downedBoss2 || NPC.downedBoss3) && num34 < 1)
            {
                num37 = 20;
            }
            if (num37 == 0 && flag5 && num12 > 0 && num41 < 1)
            {
                num37 = 38;
            }
            if (num37 == 0 && NPC.downedQueenBee && num13 < 1)
            {
                num37 = 228;
            }
            if (num37 == 0 && NPC.downedMechBossAny && num7 < 1)
            {
                num37 = 178;
            }
            if (num37 == 0 && NPC.savedMech && num4 < 1)
            {
                num37 = 124;
            }
            if (num37 == 0 && NPC.savedAngler && num16 < 1)
            {
                num37 = 369;
            }
            if (num37 == 0 && hardMode && NPC.downedPlantBoss && num10 < 1)
            {
                num37 = 209;
            }
            if (num37 == 0 && NPC.downedPirates && num14 < 1)
            {
                num37 = 229;
            }
            if (num37 == 0 && NPC.downedBoss3 && num42 < 1)
            {
                num37 = 54;
            }
            if (num37 == 0 && NPC.savedStylist && num15 < 1)
            {
                num37 = 353;
            }
            if (num37 == 0 && num35 >= 4 && flag4 && num8 < 1)
            {
                num37 = 207;
            }
            if (num37 == 0 && num35 >= 8 && num11 < 1)
            {
                num37 = 227;
            }
            if (num37 == 0 && flag7 && num9 < 1)
            {
                num37 = 208;
            }
            if (num37 == 0 && NPC.downedFrost && num5 < 1 && xMas)
            {
                num37 = 142;
            }
            if (num37 == 0 && NPC.savedBartender && num18 < 1)
            {
                num37 = 550;
            }
            if (num37 == 0 && NPC.savedGolfer && num19 < 1)
            {
                num37 = 588;
            }
            if (num37 == 0 && bestiaryProgressReport.CompletionPercent >= 0.1f && num20 < 1)
            {
                num37 = 633;
            }
            if (num37 == 0 && flag9 && num33 < 1)
            {
                num37 = 663;
            }
            WorldGen.prioritizedTownNPCType = num37;
        }
        NPCLoader.CanTownNPCSpawn(num35);
    }
References Terraria.NPC.boughtBunny, Terraria.NPC.boughtCat, Terraria.NPC.boughtDog, Terraria.ModLoader.NPCLoader.CanTownNPCSpawn(), Terraria.Main.checkForSpawns, Terraria.NPC.downedBoss1, Terraria.NPC.downedBoss2, Terraria.NPC.downedBoss3, Terraria.NPC.downedFrost, Terraria.NPC.downedMechBossAny, Terraria.NPC.downedPirates, Terraria.NPC.downedPlantBoss, Terraria.NPC.downedQueenBee, Terraria.Main.dungeonX, Terraria.Main.dungeonY, Terraria.GameContent.Events.BirthdayParty.GenuineParty, Terraria.Main.GetBestiaryProgressReport(), Terraria.NPC.GetSpawnSourceForTownSpawn(), Terraria.WorldGen.GetWorldUpdateRate(), Terraria.Main.hardMode, Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.npc, Terraria.Main.player, Terraria.WorldGen.prioritizedTownNPCType, Terraria.WorldGen.QuickFindHome(), Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.NPC.savedAngler, Terraria.NPC.savedBartender, Terraria.NPC.savedGoblin, Terraria.NPC.savedGolfer, Terraria.NPC.savedMech, Terraria.NPC.savedStylist, Terraria.NPC.savedTaxCollector, Terraria.NPC.savedWizard, Terraria.NPC.SpawnAllowed_ArmsDealer(), Terraria.NPC.SpawnAllowed_Demolitionist(), Terraria.NPC.SpawnAllowed_DyeTrader(), Terraria.NPC.SpawnAllowed_Merchant(), Terraria.NPC.SpawnAllowed_Nurse(), Terraria.Main.tenthAnniversaryWorld, Terraria.Main.townNPCCanSpawn, Terraria.NPC.unlockedPartyGirlSpawn, Terraria.NPC.unlockedPrincessSpawn, Terraria.NPC.unlockedSlimeBlueSpawn, Terraria.NPC.unlockedSlimeCopperSpawn, Terraria.NPC.unlockedSlimeGreenSpawn, Terraria.NPC.unlockedSlimeOldSpawn, Terraria.NPC.unlockedSlimePurpleSpawn, Terraria.NPC.unlockedSlimeRainbowSpawn, Terraria.NPC.unlockedSlimeRedSpawn, Terraria.NPC.unlockedSlimeYellowSpawn, and Terraria.Main.xMas.
Referenced by Terraria.Main.UpdateTime().