TModLoader: Terraria.Main.DrawRain
DrawRain()
void Terraria.Main.DrawRain () inline protected
    {
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        bool flag = ((Game)this).IsActive || netMode == 1;
        Rectangle value = default(Rectangle);
        ((Rectangle)(ref value))._002Ector(0, 0, 2, 40);
        Texture2D value2 = TextureAssets.Rain.Value;
        Vector2 zero = Vector2.Zero;
        for (int i = 0; i < maxRain; i++)
        {
            Rain rain = Main.rain[i];
            if (!rain.active)
            {
                continue;
            }
            value.X = rain.type * 4;
            Color color = Lighting.GetColor((int)(rain.position.X + 4f) >> 4, (int)(rain.position.Y + 4f) >> 4) * 0.85f;
            if (shimmerAlpha > 0f)
            {
                color *= 1f - shimmerAlpha;
            }
            if (rain.waterStyle >= 15)
            {
                value2 = LoaderManager.Get<WaterStylesLoader>().Get(rain.waterStyle).GetRainTexture()
                    .Value;
                if (value2 == null)
                {
                    goto IL_012a;
                }
            }
            else
            {
                value2 = TextureAssets.Rain.Value;
            }
            spriteBatch.Draw(value2, rain.position - screenPosition, (Rectangle?)value, color, rain.rotation, zero, rain.scale, (SpriteEffects)0, 0f);
            goto IL_012a;
            IL_012a:
            if (flag)
            {
                rain.Update();
            }
        }
        TimeLogger.DetailedDrawTime(23);
    }
References Terraria.Rain.active, Terraria.Graphics.Light.Color, Terraria.TimeLogger.DetailedDrawTime(), Terraria.Lighting.GetColor(), Terraria.Main.maxRain, Terraria.Main.netMode, Terraria.Rain.position, Terraria.GameContent.TextureAssets.Rain, Terraria.Main.rain, Terraria.Rain.rotation, Terraria.Rain.scale, Terraria.Main.screenPosition, Terraria.Main.shimmerAlpha, Terraria.Main.spriteBatch, Terraria.Rain.Update(), and Terraria.Rain.waterStyle.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.DrawCapture().