TModLoader: Terraria.Main.DrawProj_Flamethrower
DrawProj_Flamethrower()
static void Terraria.Main.DrawProj_Flamethrower (Projectile proj) inline static private
Definition at line 44911 of file Main.cs.
    {
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        //IL_028e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0301: Unknown result type (might be due to invalid IL or missing references)
        //IL_0306: Unknown result type (might be due to invalid IL or missing references)
        //IL_0308: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_026c: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0282: Unknown result type (might be due to invalid IL or missing references)
        //IL_0268: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03da: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0402: Unknown result type (might be due to invalid IL or missing references)
        //IL_0409: Unknown result type (might be due to invalid IL or missing references)
        //IL_040d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0417: Unknown result type (might be due to invalid IL or missing references)
        //IL_0424: Unknown result type (might be due to invalid IL or missing references)
        //IL_0426: Unknown result type (might be due to invalid IL or missing references)
        //IL_0430: Unknown result type (might be due to invalid IL or missing references)
        //IL_0444: Unknown result type (might be due to invalid IL or missing references)
        //IL_0446: Unknown result type (might be due to invalid IL or missing references)
        //IL_044d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0451: Unknown result type (might be due to invalid IL or missing references)
        //IL_0458: Unknown result type (might be due to invalid IL or missing references)
        //IL_045a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0464: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_0253: Unknown result type (might be due to invalid IL or missing references)
        //IL_0261: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_023c: Unknown result type (might be due to invalid IL or missing references)
        //IL_024a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0483: Unknown result type (might be due to invalid IL or missing references)
        //IL_0486: Unknown result type (might be due to invalid IL or missing references)
        //IL_0493: Unknown result type (might be due to invalid IL or missing references)
        //IL_049a: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0503: Unknown result type (might be due to invalid IL or missing references)
        //IL_0510: Unknown result type (might be due to invalid IL or missing references)
        //IL_0512: Unknown result type (might be due to invalid IL or missing references)
        //IL_051c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0233: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_0218: Unknown result type (might be due to invalid IL or missing references)
        //IL_022c: Unknown result type (might be due to invalid IL or missing references)
        bool flag = proj.ai[0] == 1f;
        float num = 60f;
        float num10 = 12f;
        float fromMax = num + num10;
        Texture2D value = TextureAssets.Projectile[proj.type].Value;
        _ = Color.Transparent;
        Color color = default(Color);
        ((Color)(ref color))._002Ector(255, 80, 20, 200);
        Color color2 = default(Color);
        ((Color)(ref color2))._002Ector(255, 255, 20, 70);
        Color color3 = Color.Lerp(new Color(255, 80, 20, 100), color2, 0.25f);
        Color color4 = default(Color);
        ((Color)(ref color4))._002Ector(80, 80, 80, 100);
        float num11 = 0.35f;
        float num12 = 0.7f;
        float num13 = 0.85f;
        float num14 = ((proj.localAI[0] > num - 10f) ? 0.175f : 0.2f);
        if (flag)
        {
            ((Color)(ref color))._002Ector(95, 120, 255, 200);
            ((Color)(ref color2))._002Ector(50, 180, 255, 70);
            ((Color)(ref color3))._002Ector(95, 160, 255, 100);
            ((Color)(ref color4))._002Ector(33, 125, 202, 100);
        }
        int verticalFrames = 7;
        float num15 = Utils.Remap(proj.localAI[0], num, fromMax, 1f, 0f);
        float num2 = Math.Min(proj.localAI[0], 20f);
        float num3 = Utils.Remap(proj.localAI[0], 0f, fromMax, 0f, 1f);
        float num4 = Utils.Remap(num3, 0.2f, 0.5f, 0.25f, 1f);
        Rectangle rectangle = ((!flag) ? value.Frame(1, verticalFrames, 0, 3) : value.Frame(1, verticalFrames, 0, (int)Utils.Remap(num3, 0.5f, 1f, 3f, 5f)));
        if (!(num3 < 1f))
        {
            return;
        }
        for (int i = 0; i < 2; i++)
        {
            for (float num5 = 1f; num5 >= 0f; num5 -= num14)
            {
                Color val = ((num3 < 0.1f) ? Color.Lerp(Color.Transparent, color, Utils.GetLerpValue(0f, 0.1f, num3, clamped: true)) : ((num3 < 0.2f) ? Color.Lerp(color, color2, Utils.GetLerpValue(0.1f, 0.2f, num3, clamped: true)) : ((num3 < num11) ? color2 : ((num3 < num12) ? Color.Lerp(color2, color3, Utils.GetLerpValue(num11, num12, num3, clamped: true)) : ((num3 < num13) ? Color.Lerp(color3, color4, Utils.GetLerpValue(num12, num13, num3, clamped: true)) : ((!(num3 < 1f)) ? Color.Transparent : Color.Lerp(color4, Color.Transparent, Utils.GetLerpValue(num13, 1f, num3, clamped: true))))))));
                float num6 = (1f - num5) * Utils.Remap(num3, 0f, 0.2f, 0f, 1f);
                Vector2 vector = proj.Center - screenPosition + proj.velocity * (0f - num2) * num5;
                Color color5 = val * num6;
                Color color6 = color5;
                if (!flag)
                {
                    ((Color)(ref color6)).G = (byte)(((Color)(ref color6)).G / 2);
                    ((Color)(ref color6)).B = (byte)(((Color)(ref color6)).B / 2);
                    ((Color)(ref color6)).A = (byte)Math.Min((float)(int)((Color)(ref color5)).A + 80f * num6, 255f);
                    Utils.Remap(proj.localAI[0], 20f, fromMax, 0f, 1f);
                }
                float num7 = 1f / num14 * (num5 + 1f);
                float num8 = proj.rotation + num5 * ((float)Math.PI / 2f) + GlobalTimeWrappedHourly * num7 * 2f;
                float num9 = proj.rotation - num5 * ((float)Math.PI / 2f) - GlobalTimeWrappedHourly * num7 * 2f;
                switch (i)
                {
                case 0:
                    EntitySpriteDraw(value, vector + proj.velocity * (0f - num2) * num14 * 0.5f, rectangle, color6 * num15 * 0.25f, num8 + (float)Math.PI / 4f, rectangle.Size() / 2f, num4, (SpriteEffects)0);
                    EntitySpriteDraw(value, vector, rectangle, color6 * num15, num9, rectangle.Size() / 2f, num4, (SpriteEffects)0);
                    break;
                case 1:
                    if (!flag)
                    {
                        EntitySpriteDraw(value, vector + proj.velocity * (0f - num2) * num14 * 0.2f, rectangle, color5 * num15 * 0.25f, num8 + (float)Math.PI / 2f, rectangle.Size() / 2f, num4 * 0.75f, (SpriteEffects)0);
                        EntitySpriteDraw(value, vector, rectangle, color5 * num15, num9 + (float)Math.PI / 2f, rectangle.Size() / 2f, num4 * 0.75f, (SpriteEffects)0);
                    }
                    break;
                }
            }
        }
    }
References Terraria.Graphics.Light.Color, Terraria.Main.EntitySpriteDraw(), Terraria.Utils.GetLerpValue(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.TextureAssets.Projectile, Terraria.Utils.Remap(), and Terraria.Main.screenPosition.
Referenced by Terraria.Main.DrawProj_DrawNormalProjs().