TModLoader: Terraria.Main.DrawKite
DrawKite()
void Terraria.Main.DrawKite (Projectile proj) inline private
    {
        //IL_054c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0565: Unknown result type (might be due to invalid IL or missing references)
        //IL_056a: Unknown result type (might be due to invalid IL or missing references)
        //IL_056c: Unknown result type (might be due to invalid IL or missing references)
        //IL_056e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0578: Unknown result type (might be due to invalid IL or missing references)
        //IL_057d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0580: Unknown result type (might be due to invalid IL or missing references)
        //IL_0585: Unknown result type (might be due to invalid IL or missing references)
        //IL_058a: Unknown result type (might be due to invalid IL or missing references)
        //IL_058f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0592: Unknown result type (might be due to invalid IL or missing references)
        //IL_0597: Unknown result type (might be due to invalid IL or missing references)
        //IL_059c: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0601: Unknown result type (might be due to invalid IL or missing references)
        //IL_0603: Unknown result type (might be due to invalid IL or missing references)
        //IL_060d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0612: Unknown result type (might be due to invalid IL or missing references)
        //IL_0622: Unknown result type (might be due to invalid IL or missing references)
        //IL_0627: Unknown result type (might be due to invalid IL or missing references)
        //IL_062a: Unknown result type (might be due to invalid IL or missing references)
        //IL_062f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0631: Unknown result type (might be due to invalid IL or missing references)
        //IL_0633: Unknown result type (might be due to invalid IL or missing references)
        //IL_0642: Unknown result type (might be due to invalid IL or missing references)
        //IL_0644: Unknown result type (might be due to invalid IL or missing references)
        //IL_0646: Unknown result type (might be due to invalid IL or missing references)
        //IL_064b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0650: Unknown result type (might be due to invalid IL or missing references)
        //IL_0657: Unknown result type (might be due to invalid IL or missing references)
        //IL_065d: Unknown result type (might be due to invalid IL or missing references)
        //IL_065f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0661: Unknown result type (might be due to invalid IL or missing references)
        //IL_0663: Unknown result type (might be due to invalid IL or missing references)
        //IL_0665: Unknown result type (might be due to invalid IL or missing references)
        //IL_066a: Unknown result type (might be due to invalid IL or missing references)
        //IL_066d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0672: Unknown result type (might be due to invalid IL or missing references)
        //IL_0674: Unknown result type (might be due to invalid IL or missing references)
        //IL_0680: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06db: Unknown result type (might be due to invalid IL or missing references)
        //IL_06dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06df: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0900: Unknown result type (might be due to invalid IL or missing references)
        //IL_0925: Unknown result type (might be due to invalid IL or missing references)
        //IL_0933: Unknown result type (might be due to invalid IL or missing references)
        //IL_0746: Unknown result type (might be due to invalid IL or missing references)
        //IL_074a: Unknown result type (might be due to invalid IL or missing references)
        //IL_074f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0751: Unknown result type (might be due to invalid IL or missing references)
        //IL_0753: Unknown result type (might be due to invalid IL or missing references)
        //IL_0755: Unknown result type (might be due to invalid IL or missing references)
        //IL_075a: Unknown result type (might be due to invalid IL or missing references)
        //IL_075c: Unknown result type (might be due to invalid IL or missing references)
        //IL_075e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0760: Unknown result type (might be due to invalid IL or missing references)
        //IL_0765: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dde: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0893: Unknown result type (might be due to invalid IL or missing references)
        //IL_077a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0786: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a26: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a86: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b30: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b36: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b38: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b42: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b46: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0825: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b71: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b76: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b78: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c73: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bde: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bfa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c06: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c08: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b86: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c30: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c42: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c44: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c20: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b96: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d34: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d36: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d38: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d49: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c96: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cce: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cda: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cde: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf0: Unknown result type (might be due to invalid IL or missing references)
        Texture2D value = TextureAssets.Projectile[proj.type].Value;
        Texture2D value2 = TextureAssets.Extra[103].Value;
        int num = 15;
        float num12 = 0f;
        int num23 = 10;
        int num33 = 5;
        float num34 = 10f;
        float num35 = 0f;
        int num36 = -14;
        int num37 = -2;
        int num38 = -1;
        int num2 = -1;
        int num3 = 8;
        int num4 = 0;
        int num5 = 1;
        int num6 = 0;
        int num7 = 0;
        bool flag = true;
        bool flag2 = false;
        switch (proj.type)
        {
        case 771:
            value2 = TextureAssets.Extra[104].Value;
            num = 12;
            num4 = 12;
            num12 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
            num23 = 12;
            num34 = 22f;
            num35 += (float)Math.PI / 8f * (float)proj.spriteDirection;
            num36 = -8;
            num37 = -6;
            num38 = 10;
            num2 = 8;
            num3 = 12;
            break;
        case 822:
            value2 = TextureAssets.Extra[132].Value;
            num = 7;
            num4 = 7;
            num12 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
            num23 = 7;
            num34 = 22f;
            num35 += (float)Math.PI / 12f * (float)proj.spriteDirection;
            num36 = -20;
            num37 = -6;
            num3 = 12;
            break;
        case 850:
            value2 = TextureAssets.Extra[147].Value;
            num = 8;
            num4 = 8;
            num12 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
            num23 = 8;
            num34 = 22f;
            num35 += (float)Math.PI / 12f * (float)proj.spriteDirection;
            num36 = -20;
            num37 = -38;
            num3 = 12;
            num6 = 6;
            num7 = 2;
            flag = false;
            break;
        case 823:
        case 846:
            value2 = TextureAssets.Extra[133].Value;
            if (proj.type == 846)
            {
                value2 = TextureAssets.Extra[146].Value;
            }
            num = 6;
            num4 = 6;
            num12 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
            num23 = 6;
            num34 = 40f;
            num35 += (float)Math.PI / 12f * (float)proj.spriteDirection;
            num36 = -16;
            num37 = -10;
            num3 = 30;
            break;
        case 827:
        case 844:
            value2 = TextureAssets.Extra[135].Value;
            if (proj.type == 844)
            {
                value2 = TextureAssets.Extra[144].Value;
            }
            num = 4;
            num4 = 3;
            num12 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
            num23 = 16;
            num34 = 10f;
            num35 += (float)Math.PI / 12f * (float)proj.spriteDirection;
            num37 = -4;
            num33 = 4;
            flag2 = true;
            break;
        case 828:
        case 829:
            value2 = TextureAssets.Extra[136].Value;
            if (proj.type == 829)
            {
                value2 = TextureAssets.Extra[137].Value;
            }
            num = 2;
            num4 = 1;
            num12 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
            num23 = 6;
            num34 = 10f;
            num35 += (float)Math.PI / 12f * (float)proj.spriteDirection;
            num3 = 10;
            num37 = -4;
            num5 = 3;
            flag = false;
            flag2 = true;
            break;
        case 852:
            value2 = TextureAssets.Extra[148].Value;
            num = 2;
            num4 = 1;
            num12 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
            num23 = 6;
            num34 = 10f;
            num35 += (float)Math.PI / 12f * (float)proj.spriteDirection;
            num3 = 10;
            num37 = -4;
            num5 = 4;
            flag = false;
            flag2 = true;
            break;
        case 830:
        case 838:
            value2 = TextureAssets.Extra[138].Value;
            if (proj.type == 838)
            {
                value2 = TextureAssets.Extra[139].Value;
            }
            num = 3;
            num4 = 3;
            num12 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
            num23 = 3;
            num34 = 60f;
            num2 = 40;
            num38 = 3;
            num35 += (float)Math.PI / 12f * (float)proj.spriteDirection;
            num3 = 50;
            num37 = -20;
            num6 = -10;
            break;
        case 843:
            value2 = TextureAssets.Extra[140].Value;
            num = 2;
            num4 = 2;
            num12 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
            num23 = 2;
            num34 = 30f;
            num35 += (float)Math.PI / 12f * (float)proj.spriteDirection;
            num3 = 20;
            num37 = -16;
            num6 = -10;
            break;
        case 845:
            value2 = TextureAssets.Extra[145].Value;
            num = 3;
            num4 = 3;
            num12 = ((proj.spriteDirection == 1) ? ((float)Math.PI / 2f) : (-(float)Math.PI / 2f));
            num23 = 3;
            num34 = 42f;
            num2 = 50;
            num38 = 2;
            num35 += (float)Math.PI / 12f * (float)proj.spriteDirection;
            num3 = 30;
            num37 = -8;
            num6 = -10;
            break;
        case 824:
        case 826:
        case 839:
        case 840:
        case 853:
            num5 = 0;
            break;
        case 766:
        case 767:
        case 768:
        case 769:
        case 770:
            num4 = (proj.type - 766) * 3 + 3;
            break;
        }
        SpriteEffects effects = (SpriteEffects)(proj.spriteDirection != 1);
        Rectangle rectangle = value.Frame(projFrames[proj.type], 1, proj.frame);
        Vector2 origin = rectangle.Size() / 2f;
        Vector2 position = proj.Center - screenPosition;
        Color color = Lighting.GetColor(proj.Center.ToTileCoordinates());
        Color alpha = proj.GetAlpha(color);
        Texture2D value3 = TextureAssets.FishingLine.Value;
        Rectangle value4 = value3.Frame();
        Vector2 origin2 = default(Vector2);
        ((Vector2)(ref origin2))._002Ector((float)(value4.Width / 2), 2f);
        Rectangle rectangle2 = value2.Frame(num);
        int width = rectangle2.Width;
        rectangle2.Width -= 2;
        Vector2 origin3 = rectangle2.Size() / 2f;
        rectangle2.X = width * (num - 1);
        Vector2 playerArmPosition = GetPlayerArmPosition(proj);
        Vector2 center = proj.Center;
        Vector2.Distance(center, playerArmPosition);
        float num8 = 12f;
        _ = (playerArmPosition - center).SafeNormalize(Vector2.Zero) * num8;
        Vector2 vector = playerArmPosition;
        Vector2 vector3 = center - vector;
        Vector2 velocity = proj.velocity;
        if (Math.Abs(velocity.X) > Math.Abs(velocity.Y))
        {
            Utils.Swap(ref velocity.X, ref velocity.Y);
        }
        float num9 = ((Vector2)(ref vector3)).Length();
        float num10 = 16f;
        float num11 = 80f;
        bool flag3 = true;
        if (num9 == 0f)
        {
            flag3 = false;
        }
        else
        {
            vector3 *= 12f / num9;
            vector -= vector3;
            vector3 = center - vector;
        }
        while (flag3)
        {
            float num13 = 12f;
            float num14 = ((Vector2)(ref vector3)).Length();
            float num15 = num14;
            if (float.IsNaN(num14) || num14 == 0f)
            {
                flag3 = false;
                continue;
            }
            if (num14 < 20f)
            {
                num13 = num14 - 8f;
                flag3 = false;
            }
            num14 = 12f / num14;
            vector3 *= num14;
            vector += vector3;
            vector3 = center - vector;
            if (num15 > 12f)
            {
                float num16 = 0.3f;
                float num17 = Math.Abs(velocity.X) + Math.Abs(velocity.Y);
                if (num17 > num10)
                {
                    num17 = num10;
                }
                num17 = 1f - num17 / num10;
                num16 *= num17;
                num17 = num15 / num11;
                if (num17 > 1f)
                {
                    num17 = 1f;
                }
                num16 *= num17;
                if (num16 < 0f)
                {
                    num16 = 0f;
                }
                num17 = 1f;
                num16 *= num17;
                if (vector3.Y > 0f)
                {
                    vector3.Y *= 1f + num16;
                    vector3.X *= 1f - num16;
                }
                else
                {
                    num17 = Math.Abs(velocity.X) / 3f;
                    if (num17 > 1f)
                    {
                        num17 = 1f;
                    }
                    num17 -= 0.5f;
                    num16 *= num17;
                    if (num16 > 0f)
                    {
                        num16 *= 2f;
                    }
                    vector3.Y *= 1f + num16;
                    vector3.X *= 1f - num16;
                }
            }
            float rotation = vector3.ToRotation() - (float)Math.PI / 2f;
            if (!flag3)
            {
                value4.Height = (int)num13;
            }
            Color color2 = Lighting.GetColor(center.ToTileCoordinates());
            EntitySpriteDraw(value3, vector - screenPosition, value4, color2, rotation, origin2, 1f, (SpriteEffects)0);
        }
        Vector2 vector4 = proj.Size / 2f;
        float num18 = Math.Abs(WindForVisuals);
        float num19 = MathHelper.Lerp(0.5f, 1f, num18);
        float num20 = num18;
        if (vector3.Y >= -0.02f && vector3.Y < 1f)
        {
            num20 = Utils.GetLerpValue(0.2f, 0.5f, num18, clamped: true);
        }
        int num21 = num33;
        int num22 = num23 + 1;
        for (int i = 0; i < num5; i++)
        {
            rectangle2.X = width * (num - 1);
            List<Vector2> list = new List<Vector2>();
            Vector2 vector5 = new Vector2(num19 * (float)num3 * (float)proj.spriteDirection, (float)Math.Sin(timeForVisualEffects / 300.0 * 6.2831854820251465) * num20) * 2f;
            float num24 = num36 + num6;
            float num25 = num37 + num7;
            switch (i)
            {
            case 1:
                vector5 = new Vector2(num19 * (float)num3 * (float)proj.spriteDirection, (float)Math.Sin(timeForVisualEffects / 300.0 * 6.2831854820251465) * num20 + 0.5f) * 2f;
                num24 -= 8f;
                num25 -= 8f;
                break;
            case 2:
                vector5 = new Vector2(num19 * (float)num3 * (float)proj.spriteDirection, (float)Math.Sin(timeForVisualEffects / 300.0 * 6.2831854820251465) * num20 + 1f) * 2f;
                num24 -= 4f;
                num25 -= 4f;
                break;
            case 3:
                vector5 = new Vector2(num19 * (float)num3 * (float)proj.spriteDirection, (float)Math.Sin(timeForVisualEffects / 300.0 * 6.2831854820251465) * num20 + 1.5f) * 2f;
                num24 -= 12f;
                num25 -= 12f;
                break;
            }
            Vector2 vector6 = proj.Center + Utils.RotatedBy(new Vector2(((float)rectangle.Width * 0.5f + num24) * (float)proj.spriteDirection, num25), proj.rotation + num35);
            list.Add(vector6);
            int num26 = num21;
            int num27 = 1;
            while (num26 < num22 * num21)
            {
                if (num38 != -1 && num38 == num27)
                {
                    num34 = num2;
                }
                Vector2 vector7 = proj.oldPos[num26];
                if (vector7.X == 0f && vector7.Y == 0f)
                {
                    list.Add(vector6);
                }
                else
                {
                    vector7 += vector4 + Utils.RotatedBy(new Vector2(((float)rectangle.Width * 0.5f + num24) * (float)proj.oldSpriteDirection[num26], num25), proj.oldRot[num26] + num35);
                    vector7 += vector5 * (float)(num27 + 1);
                    Vector2 vector8 = vector6 - vector7;
                    float num28 = ((Vector2)(ref vector8)).Length();
                    if (num28 > num34)
                    {
                        vector8 *= num34 / num28;
                    }
                    vector7 = vector6 - vector8;
                    list.Add(vector7);
                    vector6 = vector7;
                }
                num26 += num21;
                num27++;
            }
            if (flag)
            {
                Rectangle value5 = value3.Frame();
                for (int num29 = list.Count - 2; num29 >= 0; num29--)
                {
                    Vector2 vector9 = list[num29];
                    Vector2 v = list[num29 + 1] - vector9;
                    float num30 = ((Vector2)(ref v)).Length();
                    if (!(num30 < 2f))
                    {
                        float rotation2 = v.ToRotation() - (float)Math.PI / 2f;
                        EntitySpriteDraw(value3, vector9 - screenPosition, value5, alpha, rotation2, origin2, new Vector2(1f, num30 / (float)value5.Height), (SpriteEffects)0);
                    }
                }
            }
            for (int num31 = list.Count - 2; num31 >= 0; num31--)
            {
                Vector2 vector10 = list[num31];
                Vector2 vector2 = list[num31 + 1];
                Vector2 v2 = vector2 - vector10;
                ((Vector2)(ref v2)).Length();
                float rotation3 = v2.ToRotation() - (float)Math.PI / 2f + num12;
                EntitySpriteDraw(value2, vector2 - screenPosition, rectangle2, alpha, rotation3, origin3, proj.scale, effects);
                rectangle2.X -= width;
                if (rectangle2.X < 0)
                {
                    int num32 = num4;
                    if (flag2)
                    {
                        num32--;
                    }
                    rectangle2.X = num32 * width;
                }
            }
        }
        EntitySpriteDraw(value, position, rectangle, alpha, proj.rotation + num35, origin, proj.scale, effects);
    }
References Terraria.Main.EntitySpriteDraw(), Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.TextureAssets.FishingLine, Terraria.Lighting.GetColor(), Terraria.Utils.GetLerpValue(), Terraria.Main.GetPlayerArmPosition(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.projFrames, Terraria.Utils.RotatedBy(), Terraria.Main.screenPosition, Terraria.Main.timeForVisualEffects, and Terraria.Main.WindForVisuals.
Referenced by Terraria.Main.DrawProj_DrawSpecialProjs().