TModLoader: Terraria.Main.DrawMap
DrawMap()
void Terraria.Main.DrawMap (GameTime gameTime) inline protected
Definition at line 70609 of file Main.cs.
    {
        //IL_12d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffe: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_14bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_14f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1505: Unknown result type (might be due to invalid IL or missing references)
        //IL_151e: Unknown result type (might be due to invalid IL or missing references)
        //IL_153f: Unknown result type (might be due to invalid IL or missing references)
        //IL_154d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1566: Unknown result type (might be due to invalid IL or missing references)
        //IL_15a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_021a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_0228: Unknown result type (might be due to invalid IL or missing references)
        //IL_1135: Unknown result type (might be due to invalid IL or missing references)
        //IL_113a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1144: Unknown result type (might be due to invalid IL or missing references)
        //IL_115b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1160: Unknown result type (might be due to invalid IL or missing references)
        //IL_1165: Unknown result type (might be due to invalid IL or missing references)
        //IL_1049: Unknown result type (might be due to invalid IL or missing references)
        //IL_1413: Unknown result type (might be due to invalid IL or missing references)
        //IL_1418: Unknown result type (might be due to invalid IL or missing references)
        //IL_1430: Unknown result type (might be due to invalid IL or missing references)
        //IL_1440: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_122e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1240: Unknown result type (might be due to invalid IL or missing references)
        //IL_1286: Unknown result type (might be due to invalid IL or missing references)
        //IL_1186: Unknown result type (might be due to invalid IL or missing references)
        //IL_118b: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_105c: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0239: Unknown result type (might be due to invalid IL or missing references)
        //IL_023b: Unknown result type (might be due to invalid IL or missing references)
        //IL_023d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0242: Unknown result type (might be due to invalid IL or missing references)
        //IL_0244: Unknown result type (might be due to invalid IL or missing references)
        //IL_0246: Unknown result type (might be due to invalid IL or missing references)
        //IL_0248: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ea2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1edd: Unknown result type (might be due to invalid IL or missing references)
        //IL_120f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1214: Unknown result type (might be due to invalid IL or missing references)
        //IL_1219: Unknown result type (might be due to invalid IL or missing references)
        //IL_121b: Unknown result type (might be due to invalid IL or missing references)
        //IL_121d: Unknown result type (might be due to invalid IL or missing references)
        //IL_17d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_17de: Unknown result type (might be due to invalid IL or missing references)
        //IL_17e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_17ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_1804: Unknown result type (might be due to invalid IL or missing references)
        //IL_1809: Unknown result type (might be due to invalid IL or missing references)
        //IL_15eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_2e66: Unknown result type (might be due to invalid IL or missing references)
        //IL_233b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2354: Unknown result type (might be due to invalid IL or missing references)
        //IL_2376: Unknown result type (might be due to invalid IL or missing references)
        //IL_238f: Unknown result type (might be due to invalid IL or missing references)
        //IL_18d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_18e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_182a: Unknown result type (might be due to invalid IL or missing references)
        //IL_182f: Unknown result type (might be due to invalid IL or missing references)
        //IL_15fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_11aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_11b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_11b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_11be: Unknown result type (might be due to invalid IL or missing references)
        //IL_18b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_18b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_18bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_18bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_18c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2593: Unknown result type (might be due to invalid IL or missing references)
        //IL_2598: Unknown result type (might be due to invalid IL or missing references)
        //IL_25a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_25b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_25be: Unknown result type (might be due to invalid IL or missing references)
        //IL_25c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2407: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a16: Unknown result type (might be due to invalid IL or missing references)
        //IL_184e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1858: Unknown result type (might be due to invalid IL or missing references)
        //IL_185d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1862: Unknown result type (might be due to invalid IL or missing references)
        //IL_1790: Unknown result type (might be due to invalid IL or missing references)
        //IL_268c: Unknown result type (might be due to invalid IL or missing references)
        //IL_269e: Unknown result type (might be due to invalid IL or missing references)
        //IL_26e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_25e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_25e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_241a: Unknown result type (might be due to invalid IL or missing references)
        //IL_28c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bf2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bf7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_254a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d88: Unknown result type (might be due to invalid IL or missing references)
        //IL_1da3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dad: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dd9: Unknown result type (might be due to invalid IL or missing references)
        //IL_266d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2672: Unknown result type (might be due to invalid IL or missing references)
        //IL_2677: Unknown result type (might be due to invalid IL or missing references)
        //IL_2679: Unknown result type (might be due to invalid IL or missing references)
        //IL_267b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c63: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0749: Unknown result type (might be due to invalid IL or missing references)
        //IL_0758: Unknown result type (might be due to invalid IL or missing references)
        //IL_0762: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0805: Unknown result type (might be due to invalid IL or missing references)
        //IL_0814: Unknown result type (might be due to invalid IL or missing references)
        //IL_081e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2608: Unknown result type (might be due to invalid IL or missing references)
        //IL_2612: Unknown result type (might be due to invalid IL or missing references)
        //IL_2617: Unknown result type (might be due to invalid IL or missing references)
        //IL_261c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d73: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d94: Unknown result type (might be due to invalid IL or missing references)
        //IL_2da6: Unknown result type (might be due to invalid IL or missing references)
        //IL_2db2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2db8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2dd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0efe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f76: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0857: Unknown result type (might be due to invalid IL or missing references)
        //IL_085c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a86: Unknown result type (might be due to invalid IL or missing references)
        //IL_2a8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aa3: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ab3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_086d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0886: Unknown result type (might be due to invalid IL or missing references)
        //IL_088b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0892: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e19: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b98: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_2bc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c13: Unknown result type (might be due to invalid IL or missing references)
        string text = "";
        if (!mapEnabled || !mapReady)
        {
            return;
        }
        float num = 0f;
        float num49 = 0f;
        float num60 = num;
        float num70 = num49;
        float num81 = 2f;
        byte b = byte.MaxValue;
        _ = maxTilesX / textureMaxWidth;
        int num92 = maxTilesY / textureMaxHeight;
        float num103 = Lighting.OffScreenTiles;
        float num114 = Lighting.OffScreenTiles;
        float num125 = maxTilesX - Lighting.OffScreenTiles - 1;
        float num2 = maxTilesY - Lighting.OffScreenTiles - 42;
        float num13 = 0f;
        float num24 = 0f;
        num103 = 10f;
        num114 = 10f;
        num125 = maxTilesX - 10;
        num2 = maxTilesY - 10;
        for (int i = 0; i < mapTarget.GetLength(0); i++)
        {
            for (int j = 0; j < mapTarget.GetLength(1); j++)
            {
                if (mapTarget[i, j] != null)
                {
                    if (mapTarget[i, j].IsContentLost && !mapWasContentLost[i, j])
                    {
                        mapWasContentLost[i, j] = true;
                        refreshMap = true;
                        clearMap = true;
                    }
                    else if (!mapTarget[i, j].IsContentLost && mapWasContentLost[i, j])
                    {
                        mapWasContentLost[i, j] = false;
                    }
                }
            }
        }
        num = 200f;
        num49 = 300f;
        float num35 = 0f;
        float num43 = 0f;
        float num44 = num125 - 1f;
        float num45 = num2 - 1f;
        num81 = (mapFullscreen ? mapFullscreenScale : ((mapStyle != 1) ? mapOverlayScale : mapMinimapScale));
        bool flag = false;
        float mapScale = MapScale;
        float num46 = 1f / mapScale;
        int num47 = mouseX;
        int num48 = mouseY;
        Matrix uIScaleMatrix = UIScaleMatrix;
        Matrix transformMatrix = uIScaleMatrix;
        Matrix transformMatrix2 = uIScaleMatrix;
        Matrix matrix = Matrix.CreateScale(mapScale);
        CoinLossRevengeSystem.RevengeMarker revengeMarker = null;
        int num50 = -1;
        if (mapStyle != 1)
        {
            transformMatrix = Matrix.Identity;
        }
        if (mapFullscreen)
        {
            transformMatrix = Matrix.Identity;
        }
        if (!mapFullscreen && mapStyle == 1)
        {
            transformMatrix *= matrix;
            transformMatrix2 *= matrix;
        }
        if (!mapFullscreen)
        {
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, transformMatrix);
            if (num81 > 1f)
            {
                flag = true;
            }
        }
        if (mapFullscreen)
        {
            if (mouseLeft && ((Game)this).IsActive && !CaptureManager.Instance.UsingMap)
            {
                if (mouseLeftRelease)
                {
                    grabMapX = mouseX;
                    grabMapY = mouseY;
                }
                else
                {
                    float num51 = (float)mouseX - grabMapX;
                    float num52 = (float)mouseY - grabMapY;
                    grabMapX = mouseX;
                    grabMapY = mouseY;
                    num51 *= 0.06255f;
                    num52 *= 0.06255f;
                    mapFullscreenPos.X -= num51 * (16f / mapFullscreenScale);
                    mapFullscreenPos.Y -= num52 * (16f / mapFullscreenScale);
                }
            }
            player[myPlayer].mouseInterface = true;
            float num53 = (float)screenWidth / (float)maxTilesX * 0.599f;
            if (mapFullscreenScale < num53)
            {
                mapFullscreenScale = num53;
            }
            if (mapFullscreenScale > 31.2f)
            {
                mapFullscreenScale = 31.18f;
            }
            num81 = mapFullscreenScale;
            b = byte.MaxValue;
            if (mapFullscreenPos.X < num103)
            {
                mapFullscreenPos.X = num103;
            }
            if (mapFullscreenPos.X > num125)
            {
                mapFullscreenPos.X = num125;
            }
            if (mapFullscreenPos.Y < num114)
            {
                mapFullscreenPos.Y = num114;
            }
            if (mapFullscreenPos.Y > num2)
            {
                mapFullscreenPos.Y = num2;
            }
            float num54 = mapFullscreenPos.X;
            float num55 = mapFullscreenPos.Y;
            if (resetMapFull)
            {
                resetMapFull = false;
                num54 = (screenPosition.X + (float)(screenWidth / 2)) / 16f;
                num55 = (screenPosition.Y + (float)(screenHeight / 2)) / 16f;
                mapFullscreenPos.X = num54;
                mapFullscreenPos.Y = num55;
            }
            num54 *= num81;
            num55 *= num81;
            num = 0f - num54 + (float)(screenWidth / 2);
            num49 = 0f - num55 + (float)(screenHeight / 2);
            num += num103 * num81;
            num49 += num114 * num81;
            float num56 = maxTilesX / 840;
            num56 *= mapFullscreenScale;
            float num57 = num;
            float num58 = num49;
            float num59 = TextureAssets.Map.Width();
            float num61 = TextureAssets.Map.Height();
            if (maxTilesX == 8400)
            {
                num56 *= 0.999f;
                num57 -= 40.6f * num56;
                num58 = num49 - 5f * num56;
                num59 -= 8.045f;
                num59 *= num56;
                num61 += 0.12f;
                num61 *= num56;
                if ((double)num56 < 1.2)
                {
                    num61 += 1f;
                }
            }
            else if (maxTilesX == 6400)
            {
                num56 *= 1.09f;
                num57 -= 38.8f * num56;
                num58 = num49 - 3.85f * num56;
                num59 -= 13.6f;
                num59 *= num56;
                num61 -= 6.92f;
                num61 *= num56;
                if ((double)num56 < 1.2)
                {
                    num61 += 2f;
                }
            }
            else if (maxTilesX == 6300)
            {
                num56 *= 1.09f;
                num57 -= 39.8f * num56;
                num58 = num49 - 4.08f * num56;
                num59 -= 26.69f;
                num59 *= num56;
                num61 -= 6.92f;
                num61 *= num56;
                if ((double)num56 < 1.2)
                {
                    num61 += 2f;
                }
            }
            else if (maxTilesX == 4200)
            {
                num56 *= 0.998f;
                num57 -= 37.3f * num56;
                num58 -= 1.7f * num56;
                num59 -= 16f;
                num59 *= num56;
                num61 -= 8.31f;
                num61 *= num56;
            }
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise);
            flag = true;
            DrawMapFullscreenBackground(screenPosition, screenWidth, screenHeight);
            int x = (int)(num + mapFullscreenScale * 10f);
            int y = (int)(num49 + mapFullscreenScale * 10f);
            int width = (int)((float)(maxTilesX - 40) * mapFullscreenScale);
            int height = (int)((float)(maxTilesY - 40) * mapFullscreenScale);
            Rectangle destinationRectangle = default(Rectangle);
            ((Rectangle)(ref destinationRectangle))._002Ector(x, y, width, height);
            spriteBatch.Draw(TextureAssets.Map.Value, destinationRectangle, (Rectangle?)new Rectangle(40, 4, 848, 240), Color.White);
            int edgeWidth = (int)(40f * mapFullscreenScale * 5f);
            int edgeHeight = (int)(4f * mapFullscreenScale * 5f);
            ((Rectangle)(ref destinationRectangle))._002Ector(x - edgeWidth, y - edgeHeight, edgeWidth, height + 2 * edgeHeight);
            spriteBatch.Draw(TextureAssets.Map.Value, destinationRectangle, (Rectangle?)new Rectangle(0, 0, 40, 248), Color.White);
            ((Rectangle)(ref destinationRectangle))._002Ector(x + width, y - edgeHeight, edgeWidth, height + 2 * edgeHeight);
            spriteBatch.Draw(TextureAssets.Map.Value, destinationRectangle, (Rectangle?)new Rectangle(888, 0, 40, 248), Color.White);
            if (mouseLeft && mouseLeftRelease)
            {
                double totalSeconds = gameTime.TotalGameTime.TotalSeconds;
                if (totalSeconds - _lastPingMouseDownTime < 0.5 && Vector2.Distance(MouseScreen, _lastPingMousePosition) < 2f)
                {
                    TriggerPing((MouseScreen - new Vector2(num - 10f * num81, num49 - 10f * num81)) / num81);
                }
                _lastPingMouseDownTime = totalSeconds;
                _lastPingMousePosition = MouseScreen;
            }
            if (num81 < 1f)
            {
                spriteBatch.End();
                spriteBatch.Begin();
                flag = false;
            }
        }
        else if (mapStyle == 1)
        {
            UpdateMinimapAnchors();
            miniMapWidth = 240;
            miniMapHeight = 240;
            miniMapX = screenWidth - _minimapTopRightAnchorOffsetTowardsLeft;
            miniMapY = _minimapTopRightAnchorOffsetTowardsBottom;
            miniMapX = (int)((float)miniMapX * num46);
            miniMapY = (int)((float)miniMapY * num46);
            mouseX = (int)((float)mouseX * num46);
            mouseY = (int)((float)mouseY * num46);
            _ = (float)miniMapHeight / (float)maxTilesY;
            if ((double)mapMinimapScale < 0.2)
            {
                mapMinimapScale = 0.2f;
            }
            if (mapMinimapScale > 3f)
            {
                mapMinimapScale = 3f;
            }
            if ((double)mapMinimapAlpha < 0.01)
            {
                mapMinimapAlpha = 0.01f;
            }
            if (mapMinimapAlpha > 1f)
            {
                mapMinimapAlpha = 1f;
            }
            num81 = mapMinimapScale;
            b = (byte)(255f * mapMinimapAlpha);
            num = miniMapX;
            num49 = miniMapY;
            num60 = num;
            num70 = num49;
            float num62 = (screenPosition.X + (float)(PlayerInput.RealScreenWidth / 2)) / 16f;
            float num63 = (screenPosition.Y + (float)(PlayerInput.RealScreenHeight / 2)) / 16f;
            num13 = (0f - (num62 - (float)(int)((screenPosition.X + (float)(PlayerInput.RealScreenWidth / 2)) / 16f))) * num81;
            num24 = (0f - (num63 - (float)(int)((screenPosition.Y + (float)(PlayerInput.RealScreenHeight / 2)) / 16f))) * num81;
            num44 = (float)miniMapWidth / num81;
            num45 = (float)miniMapHeight / num81;
            num35 = (float)(int)num62 - num44 / 2f;
            num43 = (float)(int)num63 - num45 / 2f;
            _ = maxTilesY;
            float num64 = num60 - 6f;
            float num65 = num70 - 6f;
            MinimapFrameManagerInstance.DrawTo(spriteBatch, new Vector2(num64 + 10f, num65 + 10f));
        }
        else if (mapStyle == 2)
        {
            float num66 = (float)screenWidth / (float)maxTilesX;
            if (mapOverlayScale < num66)
            {
                mapOverlayScale = num66;
            }
            if (mapOverlayScale > 16f * GameViewMatrix.Zoom.X)
            {
                mapOverlayScale = 16f * GameViewMatrix.Zoom.X;
            }
            if ((double)mapOverlayAlpha < 0.01)
            {
                mapOverlayAlpha = 0.01f;
            }
            if (mapOverlayAlpha > 1f)
            {
                mapOverlayAlpha = 1f;
            }
            num81 = mapOverlayScale;
            b = (byte)(255f * mapOverlayAlpha);
            _ = maxTilesX;
            _ = maxTilesY;
            float num67 = (screenPosition.X + (float)(screenWidth / 2)) / 16f;
            float num136 = (screenPosition.Y + (float)(screenHeight / 2)) / 16f;
            num67 *= num81;
            float num68 = num136 * num81;
            num = 0f - num67 + (float)(screenWidth / 2);
            num49 = 0f - num68 + (float)(screenHeight / 2);
            num += num103 * num81;
            num49 += num114 * num81;
        }
        if (mapStyle == 1 && !mapFullscreen)
        {
            if (num35 < num103)
            {
                num -= (num35 - num103) * num81;
            }
            if (num43 < num114)
            {
                num49 -= (num43 - num114) * num81;
            }
        }
        num44 = num35 + num44;
        num45 = num43 + num45;
        if (num35 > num103)
        {
            num103 = num35;
        }
        if (num43 > num114)
        {
            num114 = num43;
        }
        if (num44 < num125)
        {
            num125 = num44;
        }
        if (num45 < num2)
        {
            num2 = num45;
        }
        float num69 = (float)textureMaxWidth * num81;
        float num71 = (float)textureMaxHeight * num81;
        float num72 = num;
        float num73 = 0f;
        Rectangle value = default(Rectangle);
        for (int k = 0; k <= mapTargetX - 1; k++)
        {
            if (!((float)((k + 1) * textureMaxWidth) > num103) || !((float)(k * textureMaxWidth) < num103 + num125))
            {
                continue;
            }
            for (int l = 0; l <= num92; l++)
            {
                if ((float)((l + 1) * textureMaxHeight) > num114 && (float)(l * textureMaxHeight) < num114 + num2)
                {
                    float num74 = num + (float)(int)((float)k * num69);
                    float num75 = num49 + (float)(int)((float)l * num71);
                    float num76 = k * textureMaxWidth;
                    float num77 = l * textureMaxHeight;
                    float num78 = 0f;
                    float num79 = 0f;
                    if (num76 < num103)
                    {
                        num78 = num103 - num76;
                        num74 = num;
                    }
                    else
                    {
                        num74 -= num103 * num81;
                    }
                    if (num77 < num114)
                    {
                        num79 = num114 - num77;
                        num75 = num49;
                    }
                    else
                    {
                        num75 -= num114 * num81;
                    }
                    num74 = num72;
                    float num80 = textureMaxWidth;
                    float num82 = textureMaxHeight;
                    float num83 = (k + 1) * textureMaxWidth;
                    float num84 = (l + 1) * textureMaxHeight;
                    if (num83 >= num125)
                    {
                        num80 -= num83 - num125;
                    }
                    if (num84 >= num2)
                    {
                        num82 -= num84 - num2;
                    }
                    num74 += num13;
                    num75 += num24;
                    if (num80 > num78)
                    {
                        ((Rectangle)(ref value))._002Ector((int)num78, (int)num79, (int)num80 - (int)num78, (int)num82 - (int)num79);
                        spriteBatch.Draw((Texture2D)(object)mapTarget[k, l], new Vector2(num74, num75), (Rectangle?)value, new Color((int)b, (int)b, (int)b, (int)b), 0f, default(Vector2), num81, (SpriteEffects)0, 0f);
                    }
                    num73 = (float)((int)num80 - (int)num78) * num81;
                }
                if (l == num92)
                {
                    num72 += num73;
                }
            }
        }
        if (flag)
        {
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, transformMatrix);
        }
        if (!mapFullscreen)
        {
            if (mapStyle == 2)
            {
                float num85 = (num81 * 0.2f * 2f + 1f) / 3f;
                if (num85 > 1f)
                {
                    num85 = 1f;
                }
                num85 *= UIScale;
                MapIcons.Draw(Vector2.Zero, new Vector2(num - 10f * num81, num49 - 10f * num81), null, num81, num85, ref text);
                revengeMarker = NPC.RevengeManager.DrawMapIcons(spriteBatch, Vector2.Zero, new Vector2(num - 10f * num81, num49 - 10f * num81), null, num81, num85, ref text);
                DrawMiscMapIcons(spriteBatch, Vector2.Zero, new Vector2(num - 10f * num81, num49 - 10f * num81), null, num81, num85, ref text);
                spriteBatch.End();
                if (revengeMarker != null)
                {
                    spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, uIScaleMatrix);
                    try
                    {
                        revengeMarker.UseMouseOver(spriteBatch, ref text, num85);
                    }
                    catch (Exception e)
                    {
                        TimeLogger.DrawException(e);
                    }
                    spriteBatch.End();
                }
                spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, transformMatrix);
                try
                {
                    for (int m = 0; m < 200; m++)
                    {
                        if (npc[m].active && npc[m].townNPC)
{
                            int headIndexSafe = TownNPCProfiles.GetHeadIndexSafe(npc[m]);
                            if (headIndexSafe > 0)
{
                                SpriteEffects dir = (SpriteEffects)0;
                                if (npc[m].direction > 0)
{
                                    dir = (SpriteEffects)1;
                                }
                                float num86 = (npc[m].position.X + (float)(npc[m].width / 2)) / 16f * num81;
                                float num87 = (npc[m].position.Y + (float)(npc[m].height / 2)) / 16f * num81;
                                num86 += num;
                                num87 += num49;
                                num86 -= 10f * num81;
                                num87 -= 10f * num81;
                                DrawNPCHeadFriendly(npc[m], b, num85, dir, headIndexSafe, num86, num87);
                            }
                        }
                        if (!npc[m].active || npc[m].GetBossHeadTextureIndex() == -1)
{
                            continue;
                        }
                        float bossHeadRotation = npc[m].GetBossHeadRotation();
                        SpriteEffects bossHeadSpriteEffects = npc[m].GetBossHeadSpriteEffects();
                        Vector2 vector = npc[m].Center + new Vector2(0f, npc[m].gfxOffY);
                        if (npc[m].type == 134)
{
                            Vector2 center = npc[m].Center;
                            int num88 = 1;
                            int num89 = (int)npc[m].ai[0];
                            while (num88 < 15 && npc[num89].active && npc[num89].type >= 134 && npc[num89].type <= 136)
{
                                num88++;
                                center += npc[num89].Center;
                                num89 = (int)npc[num89].ai[0];
                            }
                            center /= (float)num88;
                            vector = center;
                        }
                        int bossHeadTextureIndex = npc[m].GetBossHeadTextureIndex();
                        float num90 = vector.X / 16f * num81;
                        float num91 = vector.Y / 16f * num81;
                        num90 += num;
                        num91 += num49;
                        num90 -= 10f * num81;
                        num91 -= 10f * num81;
                        DrawNPCHeadBoss(npc[m], b, num85, bossHeadRotation, bossHeadSpriteEffects, bossHeadTextureIndex, num90, num91);
                    }
                }
                catch (Exception e2)
                {
                    TimeLogger.DrawException(e2);
                }
                spriteBatch.End();
                spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, transformMatrix);
                for (int n = 0; n < 255; n++)
                {
                    if (player[n].active && !player[n].dead && n != myPlayer && ((!player[myPlayer].hostile && !player[n].hostile) || (player[myPlayer].team == player[n].team && player[n].team != 0) || n == myPlayer))
                    {
                        float num93 = (player[n].position.X + (float)(player[n].width / 2)) / 16f * num81;
                        float num94 = player[n].position.Y / 16f * num81;
                        num93 += num;
                        num94 += num49;
                        num93 -= 6f;
                        num94 -= 2f;
                        num94 -= 2f - num81 / 5f * 2f;
                        num93 -= 10f * num81;
                        num94 -= 10f * num81;
                        Color playerHeadBordersColor = GetPlayerHeadBordersColor(player[n]);
                        MapPlayerRenderer.DrawPlayerHead(Camera, player[n], new Vector2(num93, num94), (float)(int)b / 255f, num85, playerHeadBordersColor);
                    }
                }
                spriteBatch.End();
                spriteBatch.Begin();
            }
            if (mapStyle == 1)
            {
                float num95 = (num81 * 0.25f * 2f + 1f) / 3f;
                if (num95 > 1f)
                {
                    num95 = 1f;
                }
                MapIcons.Draw(new Vector2(num35, num43), new Vector2(num60 + num13, num70 + num24), (Rectangle?)new Rectangle(miniMapX, miniMapY, miniMapWidth, miniMapHeight), num81, num95, ref text);
                revengeMarker = NPC.RevengeManager.DrawMapIcons(spriteBatch, new Vector2(num35, num43), new Vector2(num60 + num13, num70 + num24), (Rectangle?)new Rectangle(miniMapX, miniMapY, miniMapWidth, miniMapHeight), num81, num95, ref text);
                DrawMiscMapIcons(spriteBatch, new Vector2(num35, num43), new Vector2(num60 + num13, num70 + num24), (Rectangle?)new Rectangle(miniMapX, miniMapY, miniMapWidth, miniMapHeight), num81, num95, ref text);
                spriteBatch.End();
                spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, transformMatrix2);
                for (int num96 = 0; num96 < 200; num96++)
                {
                    if (npc[num96].active && npc[num96].townNPC)
                    {
                        int headIndexSafe2 = TownNPCProfiles.GetHeadIndexSafe(npc[num96]);
                        if (headIndexSafe2 > 0)
{
                            SpriteEffects dir2 = (SpriteEffects)0;
                            if (npc[num96].direction > 0)
{
                                dir2 = (SpriteEffects)1;
                            }
                            float num97 = ((npc[num96].position.X + (float)npc[num96].width / 2f) / 16f - num35) * num81;
                            float num98 = ((npc[num96].position.Y + npc[num96].gfxOffY + (float)npc[num96].height / 2f) / 16f - num43) * num81;
                            num97 += num60;
                            num98 += num70;
                            num98 -= 2f * num81 / 5f;
                            num97 += num13;
                            num98 += num24;
                            if (num97 > (float)(miniMapX + 12) && num97 < (float)(miniMapX + miniMapWidth - 16) && num98 > (float)(miniMapY + 10) && num98 < (float)(miniMapY + miniMapHeight - 14))
{
                                float num99 = num97 - (float)(TextureAssets.NpcHead[headIndexSafe2].Width() / 2) * num95;
                                float num100 = num98 - (float)(TextureAssets.NpcHead[headIndexSafe2].Height() / 2) * num95;
                                float num101 = num99 + (float)TextureAssets.NpcHead[headIndexSafe2].Width() * num95;
                                float num102 = num100 + (float)TextureAssets.NpcHead[headIndexSafe2].Height() * num95;
                                if ((float)mouseX >= num99 && (float)mouseX <= num101 && (float)mouseY >= num100 && (float)mouseY <= num102)
{
                                    text = npc[num96].FullName;
                                }
                                DrawNPCHeadFriendly(npc[num96], b, num95, dir2, headIndexSafe2, num97, num98);
                            }
                        }
                    }
                    if (!npc[num96].active || npc[num96].GetBossHeadTextureIndex() == -1)
                    {
                        continue;
                    }
                    float bossHeadRotation2 = npc[num96].GetBossHeadRotation();
                    SpriteEffects bossHeadSpriteEffects2 = npc[num96].GetBossHeadSpriteEffects();
                    Vector2 vector2 = npc[num96].Center + new Vector2(0f, npc[num96].gfxOffY);
                    if (npc[num96].type == 134)
                    {
                        Vector2 center2 = npc[num96].Center;
                        int num104 = 1;
                        int num105 = (int)npc[num96].ai[0];
                        while (num104 < 15 && npc[num105].active && npc[num105].type >= 134 && npc[num105].type <= 136)
{
                            num104++;
                            center2 += npc[num105].Center;
                            num105 = (int)npc[num105].ai[0];
                        }
                        center2 /= (float)num104;
                        vector2 = center2;
                    }
                    int bossHeadTextureIndex2 = npc[num96].GetBossHeadTextureIndex();
                    float num106 = (vector2.X / 16f - num35) * num81;
                    float num107 = (vector2.Y / 16f - num43) * num81;
                    num106 += num60;
                    num107 += num70;
                    num107 -= 2f * num81 / 5f;
                    num106 += num13;
                    num107 += num24;
                    if (num106 > (float)(miniMapX + 12) && num106 < (float)(miniMapX + miniMapWidth - 16) && num107 > (float)(miniMapY + 10) && num107 < (float)(miniMapY + miniMapHeight - 14))
                    {
                        float num108 = num106 - (float)(TextureAssets.NpcHeadBoss[bossHeadTextureIndex2].Width() / 2) * num95;
                        float num109 = num107 - (float)(TextureAssets.NpcHeadBoss[bossHeadTextureIndex2].Height() / 2) * num95;
                        float num110 = num108 + (float)TextureAssets.NpcHeadBoss[bossHeadTextureIndex2].Width() * num95;
                        float num111 = num109 + (float)TextureAssets.NpcHeadBoss[bossHeadTextureIndex2].Height() * num95;
                        if ((float)mouseX >= num108 && (float)mouseX <= num110 && (float)mouseY >= num109 && (float)mouseY <= num111)
{
                            text = npc[num96].GivenOrTypeName;
                        }
                        DrawNPCHeadBoss(npc[num96], b, num95, bossHeadRotation2, bossHeadSpriteEffects2, bossHeadTextureIndex2, num106, num107);
                    }
                }
                spriteBatch.End();
                spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, transformMatrix2);
                for (int num112 = 0; num112 < 255; num112++)
                {
                    if (!player[num112].active || ((player[myPlayer].hostile || player[num112].hostile) && (player[myPlayer].team != player[num112].team || player[num112].team == 0) && num112 != myPlayer))
                    {
                        continue;
                    }
                    float num113 = ((player[num112].position.X + (float)(player[num112].width / 2)) / 16f - num35) * num81;
                    float num115 = ((player[num112].position.Y + player[num112].gfxOffY + (float)(player[num112].height / 2)) / 16f - num43) * num81;
                    num113 += num60;
                    num115 += num70;
                    num113 -= 6f;
                    num115 -= 6f;
                    num115 -= 2f - num81 / 5f * 2f;
                    num113 += num13;
                    num115 += num24;
                    if (!player[num112].dead && num113 > (float)(miniMapX + 6) && num113 < (float)(miniMapX + miniMapWidth - 16) && num115 > (float)(miniMapY + 6) && num115 < (float)(miniMapY + miniMapHeight - 14))
                    {
                        Color playerHeadBordersColor2 = GetPlayerHeadBordersColor(player[num112]);
                        MapPlayerRenderer.DrawPlayerHead(Camera, player[num112], new Vector2(num113, num115), (float)(int)b / 255f, num95, playerHeadBordersColor2);
                        if (num112 != myPlayer)
{
                            float num116 = num113 + 4f - 14f * num95;
                            float num117 = num115 + 2f - 14f * num95;
                            float num118 = num116 + 28f * num95;
                            float num119 = num117 + 28f * num95;
                            if ((float)mouseX >= num116 && (float)mouseX <= num118 && (float)mouseY >= num117 && (float)mouseY <= num119)
{
                                text = player[num112].name;
                            }
                        }
                    }
                    if (!player[num112].showLastDeath)
                    {
                        continue;
                    }
                    num113 = (player[num112].lastDeathPostion.X / 16f - num35) * num81;
                    num115 = (player[num112].lastDeathPostion.Y / 16f - num43) * num81;
                    num113 += num60;
                    num115 += num70;
                    num115 -= 2f - num81 / 5f * 2f;
                    num113 += num13;
                    num115 += num24;
                    if (num113 > (float)(miniMapX + 8) && num113 < (float)(miniMapX + miniMapWidth - 18) && num115 > (float)(miniMapY + 8) && num115 < (float)(miniMapY + miniMapHeight - 16))
                    {
                        spriteBatch.Draw(TextureAssets.MapDeath.Value, new Vector2(num113, num115), (Rectangle?)new Rectangle(0, 0, TextureAssets.MapDeath.Width(), TextureAssets.MapDeath.Height()), Color.White, 0f, new Vector2((float)TextureAssets.MapDeath.Width() * 0.5f, (float)TextureAssets.MapDeath.Height() * 0.5f), num95, (SpriteEffects)0, 0f);
                        float num120 = num113 + 4f - 14f * num95;
                        float num121 = num115 + 2f - 14f * num95;
                        num120 -= 4f;
                        num121 -= 4f;
                        float num122 = num120 + 28f * num95;
                        float num123 = num121 + 28f * num95;
                        if ((float)mouseX >= num120 && (float)mouseX <= num122 && (float)mouseY >= num121 && (float)mouseY <= num123)
{
                            num50 = num112;
                        }
                    }
                }
                spriteBatch.End();
                spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, transformMatrix2);
                MinimapFrameManagerInstance.DrawForeground(spriteBatch);
                spriteBatch.End();
                spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, uIScaleMatrix);
                if (num50 != -1)
                {
                    TimeSpan timeSpan = DateTime.Now - player[num50].lastDeathTime;
                    text = Language.GetTextValue("Game.PlayerDeathTime", player[num50].name, Lang.LocalizedDuration(timeSpan, abbreviated: false, showAllAvailableUnits: false));
                }
                else
                {
                    revengeMarker?.UseMouseOver(spriteBatch, ref text);
                }
            }
        }
        if (mapFullscreen)
        {
            int num124 = (int)((0f - num + (float)mouseX) / num81 + num103);
            int num126 = (int)((0f - num49 + (float)mouseY) / num81 + num114);
            bool flag2 = false;
            if ((float)num124 < num103)
            {
                flag2 = true;
            }
            if ((float)num124 >= num125)
            {
                flag2 = true;
            }
            if ((float)num126 < num114)
            {
                flag2 = true;
            }
            if ((float)num126 >= num2)
            {
                flag2 = true;
            }
            if (!flag2 && Map[num124, num126].Light > 40)
            {
                int type = Map[num124, num126].Type;
                int num127 = MapHelper.tileLookup[21];
                int num128 = MapHelper.tileLookup[441];
                int num129 = MapHelper.tileOptionCounts[21];
                int num130 = MapHelper.tileLookup[467];
                int num131 = MapHelper.tileLookup[468];
                int num132 = MapHelper.tileOptionCounts[467];
                int num133 = MapHelper.tileLookup[88];
                int num134 = MapHelper.tileOptionCounts[88];
                LocalizedText[] chestType = Lang.chestType;
                LocalizedText[] chestType2 = Lang.chestType2;
                if (type >= num127 && type < num127 + num129)
                {
                    Tile tile = Main.tile[num124, num126];
                    if (tile != null)
                    {
                        int num135 = num124;
                        int num3 = num126;
                        if (tile.frameX % 36 != 0)
{
                            num135--;
                        }
                        if (tile.frameY % 36 != 0)
{
                            num3--;
                        }
                        text = DrawMap_FindChestName(chestType, tile, num135, num3);
                    }
                }
                else if (type >= num130 && type < num130 + num132)
                {
                    Tile tile2 = Main.tile[num124, num126];
                    if (tile2 != null)
                    {
                        int num4 = num124;
                        int num5 = num126;
                        if (tile2.frameX % 36 != 0)
{
                            num4--;
                        }
                        if (tile2.frameY % 36 != 0)
{
                            num5--;
                        }
                        text = DrawMap_FindChestName(chestType2, tile2, num4, num5);
                    }
                }
                else if (type >= num128 && type < num128 + num129)
                {
                    Tile tile3 = Main.tile[num124, num126];
                    if (tile3 != null)
                    {
                        int num6 = num124;
                        int num7 = num126;
                        if (tile3.frameX % 36 != 0)
{
                            num6--;
                        }
                        if (tile3.frameY % 36 != 0)
{
                            num7--;
                        }
                        text = chestType[tile3.frameX / 36].Value;
                    }
                }
                else if (type >= num131 && type < num131 + num132)
                {
                    Tile tile4 = Main.tile[num124, num126];
                    if (tile4 != null)
                    {
                        int num8 = num124;
                        int num9 = num126;
                        if (tile4.frameX % 36 != 0)
{
                            num8--;
                        }
                        if (tile4.frameY % 36 != 0)
{
                            num9--;
                        }
                        text = chestType2[tile4.frameX / 36].Value;
                    }
                }
                else if (type >= num133 && type < num133 + num134)
                {
                    Tile tile5 = Main.tile[num124, num126];
                    if (tile5 != null)
                    {
                        int num10 = num126;
                        int x2 = num124 - tile5.frameX % 54 / 18;
                        if (tile5.frameY % 36 != 0)
{
                            num10--;
                        }
                        int num11 = Chest.FindChest(x2, num10);
                        text = ((num11 < 0) ? Lang.dresserType[0].Value : ((!(chest[num11].name != "")) ? Lang.dresserType[tile5.frameX / 54].Value : (Lang.dresserType[tile5.frameX / 54].Value + ": " + chest[num11].name)));
                    }
                }
                else
                {
                    text = Lang._mapLegendCache.FromTile(Map[num124, num126], num124, num126);
                }
            }
            float num12 = (num81 * 0.25f * 2f + 1f) / 3f;
            if (num12 > 1f)
            {
                num12 = 1f;
            }
            num12 = 1f;
            num12 = UIScale;
            revengeMarker = NPC.RevengeManager.DrawMapIcons(spriteBatch, Vector2.Zero, new Vector2(num - 10f * num81, num49 - 10f * num81), null, num81, num12, ref text);
            DrawMiscMapIcons(spriteBatch, Vector2.Zero, new Vector2(num - 10f * num81, num49 - 10f * num81), null, num81, num12, ref text);
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend);
            for (int num14 = 0; num14 < 200; num14++)
            {
                if (npc[num14].active && npc[num14].townNPC)
                {
                    int headIndexSafe3 = TownNPCProfiles.GetHeadIndexSafe(npc[num14]);
                    if (headIndexSafe3 > 0)
                    {
                        SpriteEffects dir3 = (SpriteEffects)0;
                        if (npc[num14].direction > 0)
{
                            dir3 = (SpriteEffects)1;
                        }
                        float num15 = (npc[num14].position.X + (float)(npc[num14].width / 2)) / 16f * num81;
                        float num16 = (npc[num14].position.Y + npc[num14].gfxOffY + (float)(npc[num14].height / 2)) / 16f * num81;
                        num15 += num;
                        num16 += num49;
                        num15 -= 10f * num81;
                        num16 -= 10f * num81;
                        float num17 = num15 - (float)(TextureAssets.NpcHead[headIndexSafe3].Width() / 2) * num12;
                        float num18 = num16 - (float)(TextureAssets.NpcHead[headIndexSafe3].Height() / 2) * num12;
                        float num19 = num17 + (float)TextureAssets.NpcHead[headIndexSafe3].Width() * num12;
                        float num20 = num18 + (float)TextureAssets.NpcHead[headIndexSafe3].Height() * num12;
                        if ((float)mouseX >= num17 && (float)mouseX <= num19 && (float)mouseY >= num18 && (float)mouseY <= num20)
{
                            text = npc[num14].FullName;
                        }
                        DrawNPCHeadFriendly(npc[num14], b, num12, dir3, headIndexSafe3, num15, num16);
                    }
                }
                if (!npc[num14].active || npc[num14].GetBossHeadTextureIndex() == -1)
                {
                    continue;
                }
                float bossHeadRotation3 = npc[num14].GetBossHeadRotation();
                SpriteEffects bossHeadSpriteEffects3 = npc[num14].GetBossHeadSpriteEffects();
                Vector2 vector3 = npc[num14].Center + new Vector2(0f, npc[num14].gfxOffY);
                if (npc[num14].type == 134)
                {
                    Vector2 center3 = npc[num14].Center;
                    int num21 = 1;
                    int num22 = (int)npc[num14].ai[0];
                    while (num21 < 15 && npc[num22].active && npc[num22].type >= 134 && npc[num22].type <= 136)
                    {
                        num21++;
                        center3 += npc[num22].Center;
                        num22 = (int)npc[num22].ai[0];
                    }
                    center3 /= (float)num21;
                    vector3 = center3;
                }
                int bossHeadTextureIndex3 = npc[num14].GetBossHeadTextureIndex();
                float num23 = vector3.X / 16f * num81;
                float num25 = vector3.Y / 16f * num81;
                num23 += num;
                num25 += num49;
                num23 -= 10f * num81;
                num25 -= 10f * num81;
                DrawNPCHeadBoss(npc[num14], b, num12, bossHeadRotation3, bossHeadSpriteEffects3, bossHeadTextureIndex3, num23, num25);
                float num26 = num23 - (float)(TextureAssets.NpcHeadBoss[bossHeadTextureIndex3].Width() / 2) * num12;
                float num27 = num25 - (float)(TextureAssets.NpcHeadBoss[bossHeadTextureIndex3].Height() / 2) * num12;
                float num28 = num26 + (float)TextureAssets.NpcHeadBoss[bossHeadTextureIndex3].Width() * num12;
                float num29 = num27 + (float)TextureAssets.NpcHeadBoss[bossHeadTextureIndex3].Height() * num12;
                if ((float)mouseX >= num26 && (float)mouseX <= num28 && (float)mouseY >= num27 && (float)mouseY <= num29)
                {
                    text = npc[num14].GivenOrTypeName;
                }
            }
            bool flag3 = false;
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend);
            for (int num30 = 0; num30 < 255; num30++)
            {
                if (player[num30].active && ((!player[myPlayer].hostile && !player[num30].hostile) || (player[myPlayer].team == player[num30].team && player[num30].team != 0) || num30 == myPlayer) && player[num30].showLastDeath && DrawPlayerDeathMarker(num, num49, num81, num35, num43, num12, num30))
                {
                    num50 = num30;
                }
            }
            if (num50 != -1)
            {
                TimeSpan timeSpan2 = DateTime.Now - player[num50].lastDeathTime;
                text = Language.GetTextValue("Game.PlayerDeathTime", player[num50].name, Lang.LocalizedDuration(timeSpan2, abbreviated: false, showAllAvailableUnits: false));
            }
            else if (revengeMarker != null)
            {
                spriteBatch.End();
                spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, uIScaleMatrix);
                revengeMarker.UseMouseOver(spriteBatch, ref text, num12);
                spriteBatch.End();
                spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend);
            }
            for (int num31 = 0; num31 < 255; num31++)
            {
                if (!player[num31].active || ((player[myPlayer].hostile || player[num31].hostile) && (player[myPlayer].team != player[num31].team || player[num31].team == 0) && num31 != myPlayer))
                {
                    continue;
                }
                float num32 = ((player[num31].position.X + (float)(player[num31].width / 2)) / 16f - num35) * num81;
                float num33 = ((player[num31].position.Y + player[num31].gfxOffY + (float)(player[num31].height / 2)) / 16f - num43) * num81;
                num32 += num;
                num33 += num49;
                num32 -= 6f;
                num33 -= 2f;
                num33 -= 2f - num81 / 5f * 2f;
                num32 -= 10f * num81;
                num33 -= 10f * num81;
                float num34 = num32 + 4f - 14f * num12;
                float num36 = num33 + 2f - 14f * num12;
                float num37 = num34 + 28f * num12;
                float num38 = num36 + 28f * num12;
                if (player[num31].dead)
                {
                    continue;
                }
                Color playerHeadBordersColor3 = GetPlayerHeadBordersColor(player[num31]);
                MapPlayerRenderer.DrawPlayerHead(Camera, player[num31], new Vector2(num32, num33), (float)(int)b / 255f, num12, playerHeadBordersColor3);
                if (!((float)mouseX >= num34) || !((float)mouseX <= num37) || !((float)mouseY >= num36) || !((float)mouseY <= num38))
                {
                    continue;
                }
                text = player[num31].name;
                if (num31 != myPlayer && player[myPlayer].team > 0 && player[myPlayer].team == player[num31].team && netMode == 1 && player[myPlayer].HasUnityPotion() && !flag3 && !cancelWormHole)
                {
                    flag3 = true;
                    if (!unityMouseOver)
                    {
                        SoundEngine.PlaySound(12);
                    }
                    unityMouseOver = true;
                    playerHeadBordersColor3 = OurFavoriteColor;
                    MapPlayerRenderer.DrawPlayerHead(Camera, player[num31], new Vector2(num32, num33), 1f, num12 + 0.5f, playerHeadBordersColor3);
                    text = Language.GetTextValue("Game.TeleportTo", player[num31].name);
                    if (mouseLeft && mouseLeftRelease)
                    {
                        mouseLeftRelease = false;
                        mapFullscreen = false;
                        player[myPlayer].UnityTeleport(player[num31].position);
                        player[myPlayer].TakeUnityPotion();
                    }
                }
            }
            cancelWormHole = false;
            MapIcons.Draw(Vector2.Zero, new Vector2(num - 10f * num81, num49 - 10f * num81), null, num81, num12, ref text);
            if (!flag3 && unityMouseOver)
            {
                unityMouseOver = false;
            }
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerStateForCursor, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, UIScaleMatrix);
            PlayerInput.SetZoom_UI();
            int num39 = 10;
            int num40 = screenHeight - 40;
            if (showFrameRate)
            {
                num40 -= 15;
            }
            int num41 = 0;
            int num42 = 130;
            if (mouseX >= num39 && mouseX <= num39 + 32 && mouseY >= num40 && mouseY <= num40 + 30)
            {
                num42 = 255;
                num41 += 4;
                player[myPlayer].mouseInterface = true;
                if (mouseLeft && mouseLeftRelease)
                {
                    SoundEngine.PlaySound(10);
                    mapFullscreen = false;
                }
            }
            spriteBatch.Draw(TextureAssets.MapIcon[num41].Value, new Vector2((float)num39, (float)num40), (Rectangle?)new Rectangle(0, 0, TextureAssets.MapIcon[num41].Width(), TextureAssets.MapIcon[num41].Height()), new Color(num42, num42, num42, num42), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            SystemLoader.PostDrawFullscreenMap(ref text);
            DrawCursor(DrawThickCursor());
        }
        mouseX = num47;
        mouseY = num48;
        float t = 3f;
        Utils.Swap(ref t, ref inventoryScale);
        if (text != "")
        {
            MouseText(text, 0, 0);
        }
        Utils.Swap(ref t, ref inventoryScale);
        spriteBatch.End();
        try
        {
            if (num35 < num103)
            {
                num += (num35 - num103) * num81;
            }
            if (num43 < num114)
            {
                num49 += (num43 - num114) * num81;
            }
            if (mapFullscreen && Main.OnPostFullscreenMapDraw != null)
            {
                Main.OnPostFullscreenMapDraw(new Vector2(num, num49), num81);
            }
        }
        catch (Exception e3)
        {
            TimeLogger.DrawException(e3);
        }
        spriteBatch.Begin();
        PlayerInput.SetZoom_Unscaled();
        TimeLogger.DetailedDrawTime(9);
    }
References Terraria.Main._lastPingMouseDownTime, Terraria.Main._lastPingMousePosition, Terraria.Lang._mapLegendCache, Terraria.Main._minimapTopRightAnchorOffsetTowardsBottom, Terraria.Main._minimapTopRightAnchorOffsetTowardsLeft, Terraria.Main.cancelWormHole, Terraria.Main.chest, Terraria.Lang.chestType, Terraria.Lang.chestType2, Terraria.Main.clearMap, Terraria.Graphics.Light.Color, Terraria.TimeLogger.DetailedDrawTime(), Terraria.Main.DrawCursor(), Terraria.TimeLogger.DrawException(), Terraria.Main.DrawMap_FindChestName(), Terraria.Main.DrawMapFullscreenBackground(), Terraria.Main.DrawMiscMapIcons(), Terraria.Main.DrawNPCHeadBoss(), Terraria.Main.DrawNPCHeadFriendly(), Terraria.Main.DrawPlayerDeathMarker(), Terraria.Main.DrawThickCursor(), Terraria.Lang.dresserType, Terraria.Chest.FindChest(), Terraria.Main.GameViewMatrix, Terraria.GameContent.TownNPCProfiles.GetHeadIndexSafe(), Terraria.Main.GetPlayerHeadBordersColor(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.grabMapX, Terraria.Main.grabMapY, Terraria.Graphics.Capture.CaptureManager.Instance, Terraria.Main.inventoryScale, Terraria.Lang.LocalizedDuration(), Terraria.GameContent.TextureAssets.Map, Terraria.GameContent.TextureAssets.MapDeath, Terraria.Main.mapEnabled, Terraria.Main.mapFullscreen, Terraria.Main.mapFullscreenPos, Terraria.Main.mapFullscreenScale, Terraria.GameContent.TextureAssets.MapIcon, Terraria.Main.MapIcons, Terraria.Main.mapMinimapAlpha, Terraria.Main.mapMinimapScale, Terraria.Main.mapOverlayAlpha, Terraria.Main.mapOverlayScale, Terraria.Main.MapPlayerRenderer, Terraria.Main.mapReady, Terraria.Main.MapScale, Terraria.Main.mapStyle, Terraria.Main.mapTarget, Terraria.Main.mapTargetX, Terraria.Main.mapWasContentLost, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.MinimapFrameManagerInstance, Terraria.Main.miniMapHeight, Terraria.Main.miniMapWidth, Terraria.Main.miniMapX, Terraria.Main.miniMapY, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.MouseScreen, Terraria.Main.MouseText(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.npc, Terraria.GameContent.TextureAssets.NpcHead, Terraria.GameContent.TextureAssets.NpcHeadBoss, Terraria.Lighting.OffScreenTiles, Terraria.Main.OnPostFullscreenMapDraw, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.ModLoader.SystemLoader.PostDrawFullscreenMap(), Terraria.GameInput.PlayerInput.RealScreenHeight, Terraria.GameInput.PlayerInput.RealScreenWidth, Terraria.Main.refreshMap, Terraria.Main.resetMapFull, Terraria.NPC.RevengeManager, Terraria.Main.SamplerStateForCursor, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameInput.PlayerInput.SetZoom_Unscaled(), Terraria.Main.showFrameRate, Terraria.Main.spriteBatch, Terraria.Main.textureMaxHeight, Terraria.Main.textureMaxWidth, Terraria.Main.tile, Terraria.Map.MapHelper.tileLookup, Terraria.Map.MapHelper.tileOptionCounts, Terraria.Main.TriggerPing(), Terraria.Main.UIScale, Terraria.Main.UIScaleMatrix, Terraria.Main.unityMouseOver, Terraria.Main.UpdateMinimapAnchors(), and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.DrawInterface_16_MapOrMinimap().