TModLoader: Terraria.Main.DrawPlayerChat
DrawPlayerChat()
void Terraria.Main.DrawPlayerChat () inline protected
    {
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        //IL_033a: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0350: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        TextSnippet[] array = null;
        if (drawingPlayerChat)
        {
            PlayerInput.WritingText = true;
        }
        HandleIME();
        if (drawingPlayerChat)
        {
            textBlinkerCount++;
            if (textBlinkerCount >= 20)
            {
                if (textBlinkerState == 0)
                {
                    textBlinkerState = 1;
                }
                else
                {
                    textBlinkerState = 0;
                }
                textBlinkerCount = 0;
            }
            string text = chatText;
            if (screenWidth > 800)
            {
                int num = screenWidth - 300;
                int num2 = 78;
                spriteBatch.Draw(TextureAssets.TextBack.Value, new Vector2((float)num2, (float)(screenHeight - 36)), (Rectangle?)new Rectangle(0, 0, TextureAssets.TextBack.Width() - 100, TextureAssets.TextBack.Height()), new Color(100, 100, 100, 100), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                num -= 400;
                num2 += 400;
                while (num > 0)
                {
                    if (num > 300)
                    {
                        spriteBatch.Draw(TextureAssets.TextBack.Value, new Vector2((float)num2, (float)(screenHeight - 36)), (Rectangle?)new Rectangle(100, 0, TextureAssets.TextBack.Width() - 200, TextureAssets.TextBack.Height()), new Color(100, 100, 100, 100), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                        num -= 300;
                        num2 += 300;
                    }
                    else
                    {
                        spriteBatch.Draw(TextureAssets.TextBack.Value, new Vector2((float)num2, (float)(screenHeight - 36)), (Rectangle?)new Rectangle(TextureAssets.TextBack.Width() - num, 0, TextureAssets.TextBack.Width() - (TextureAssets.TextBack.Width() - num), TextureAssets.TextBack.Height()), new Color(100, 100, 100, 100), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                        num = 0;
                    }
                }
            }
            else
            {
                spriteBatch.Draw(TextureAssets.TextBack.Value, new Vector2(78f, (float)(screenHeight - 36)), (Rectangle?)new Rectangle(0, 0, TextureAssets.TextBack.Width(), TextureAssets.TextBack.Height()), new Color(100, 100, 100, 100), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            int hoveredSnippet = -1;
            List<TextSnippet> list = ChatManager.ParseMessage(text, Color.White);
            string compositionString = Platform.Get<IImeService>().CompositionString;
            if (compositionString != null && compositionString.Length > 0)
            {
                list.Add(new TextSnippet(compositionString, new Color(255, 240, 20)));
            }
            if (textBlinkerState == 1)
            {
                list.Add(new TextSnippet("|", Color.White));
            }
            array = list.ToArray();
            ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, array, new Vector2(88f, (float)(screenHeight - 30)), 0f, Vector2.Zero, Vector2.One, out hoveredSnippet);
            if (hoveredSnippet > -1)
            {
                array[hoveredSnippet].OnHover();
                if (mouseLeft && mouseLeftRelease)
                {
                    array[hoveredSnippet].OnClick();
                }
            }
        }
        chatMonitor.DrawChat(drawingPlayerChat);
        if (drawingPlayerChat && array != null)
        {
            Vector2 stringSize = ChatManager.GetStringSize(FontAssets.MouseText.Value, array, Vector2.Zero);
            DrawWindowsIMEPanel(new Vector2(88f, (float)(screenHeight - 30)) + new Vector2(stringSize.X + 10f, -6f));
        }
        TimeLogger.DetailedDrawTime(10);
    }
References Terraria.Main.chatMonitor, Terraria.Main.chatText, Terraria.Graphics.Light.Color, Terraria.TimeLogger.DetailedDrawTime(), Terraria.GameContent.UI.Chat.IChatMonitor.DrawChat(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Main.drawingPlayerChat, Terraria.Main.DrawWindowsIMEPanel(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Main.HandleIME(), Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.GameContent.FontAssets.MouseText, Terraria.UI.Chat.TextSnippet.OnClick(), Terraria.UI.Chat.TextSnippet.OnHover(), Terraria.UI.Chat.ChatManager.ParseMessage(), Terraria.Enums.Platform, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, Terraria.GameContent.TextureAssets.TextBack, Terraria.Main.textBlinkerCount, and Terraria.Main.textBlinkerState.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.DrawInterface_34_PlayerChat().