TModLoader: Terraria.Main.DrawInterface_Resources_GolfPower
DrawInterface_Resources_GolfPower()
static void Terraria.Main.DrawInterface_Resources_GolfPower () inline static private
    {
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        Projectile projectile = null;
        for (int i = 0; i < 1000; i++)
        {
            Projectile projectile2 = Main.projectile[i];
            if (projectile2.active && projectile2.owner == myPlayer && projectile2.type == 722)
            {
                projectile = projectile2;
                break;
            }
        }
        if (projectile == null)
        {
            return;
        }
        Projectile projectile3 = GolfHelper.FindGolfBallForHelper(projectile);
        if (projectile3 != null)
        {
            float relativeStrength = GolfHelper.CalculateShotStrength(projectile, projectile3).RelativeStrength;
            if (!(relativeStrength < 0.001f))
            {
                Vector2 position = LocalPlayer.Bottom - Camera.ScaledPosition;
                position *= GameViewMatrix.Zoom;
                position /= UIScale;
                position.X -= 27f;
                position.Y += 14f;
                spriteBatch.Draw(TextureAssets.GolfSwingBarPanel.Value, position, (Rectangle?)null, Color.White);
                spriteBatch.Draw(TextureAssets.GolfSwingBarFill.Value, position, (Rectangle?)new Rectangle(0, 0, (int)(54f * relativeStrength), 14), Color.White);
            }
        }
    }
References Terraria.GameContent.Golf.GolfHelper.CalculateShotStrength(), Terraria.Graphics.Light.Color, Terraria.GameContent.Golf.GolfHelper.FindGolfBallForHelper(), Terraria.Main.GameViewMatrix, Terraria.GameContent.TextureAssets.GolfSwingBarFill, Terraria.GameContent.TextureAssets.GolfSwingBarPanel, Terraria.Main.myPlayer, Terraria.Main.projectile, Terraria.GameContent.Golf.GolfHelper.ShotStrength.RelativeStrength, Terraria.Graphics.Camera.ScaledPosition, Terraria.Main.spriteBatch, Terraria.Main.UIScale, and Terraria.Graphics.SpriteViewMatrix.Zoom.
Referenced by Terraria.Main.DrawInterface_9_WireSelection().