TModLoader: Terraria.Main.DrawBuffIcon
DrawBuffIcon()
static int Terraria.Main.DrawBuffIcon (int drawBuffText, int buffSlotOnPlayer, int x, int y) inline static
Draws the buff icon corresponding to the buff in Main.LocalPlayer.buffType[buffSlotOnPlayer ].
Calls TML hooks related to drawing and clicking.
Has two exclusive contexts: Below the accessory slots (Main.EquipPage == 2), and regular under-the-inventory.
Parameters
drawBuffText The return from a previous DrawBuffIcon call, -1 if first drawn buff
buffSlotOnPlayer The index for buffType and buffTime
x Top-left draw position on the x-axis
y Top-left draw position on the y-axis
Returns
The index of the currently mouseovered buff icon, equal to buffSlotOnPlayer if it's currently mouseovered, -1 otherwise
    {
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0092: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        int num = player[myPlayer].buffType[buffSlotOnPlayer];
        if (num == 0)
        {
            return drawBuffText;
        }
        Color color = default(Color);
        ((Color)(ref color))._002Ector(buffAlpha[buffSlotOnPlayer], buffAlpha[buffSlotOnPlayer], buffAlpha[buffSlotOnPlayer], buffAlpha[buffSlotOnPlayer]);
        Asset<Texture2D> obj = TextureAssets.Buff[num];
        Texture2D texture = obj.Value;
        Vector2 drawPosition = default(Vector2);
        ((Vector2)(ref drawPosition))._002Ector((float)x, (float)y);
        int width = obj.Width();
        int height = obj.Height();
        Vector2 textPosition = default(Vector2);
        ((Vector2)(ref textPosition))._002Ector((float)x, (float)(y + height));
        Rectangle sourceRectangle = default(Rectangle);
        ((Rectangle)(ref sourceRectangle))._002Ector(0, 0, width, height);
        Rectangle mouseRectangle = default(Rectangle);
        ((Rectangle)(ref mouseRectangle))._002Ector(x, y, width, height);
        Color drawColor = color;
        BuffDrawParams drawParams = new BuffDrawParams(texture, drawPosition, textPosition, sourceRectangle, mouseRectangle, drawColor);
        bool num2 = !BuffLoader.PreDraw(spriteBatch, num, buffSlotOnPlayer, ref drawParams);
        BuffDrawParams buffDrawParams = drawParams;
        (texture, drawPosition, textPosition, sourceRectangle, mouseRectangle, drawColor) = (BuffDrawParams)(ref buffDrawParams);
        if (!num2)
        {
            spriteBatch.Draw(texture, drawPosition, (Rectangle?)sourceRectangle, drawColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        }
        BuffLoader.PostDraw(spriteBatch, num, buffSlotOnPlayer, drawParams);
        if (TryGetBuffTime(buffSlotOnPlayer, out var buffTimeValue) && buffTimeValue > 2)
        {
            string text = Lang.LocalizedDuration(new TimeSpan(0, 0, buffTimeValue / 60), abbreviated: true, showAllAvailableUnits: false);
            spriteBatch.DrawString(FontAssets.ItemStack.Value, text, textPosition, color, 0f, default(Vector2), 0.8f, (SpriteEffects)0, 0f);
        }
        if (((Rectangle)(ref mouseRectangle)).Contains(new Point(mouseX, mouseY)))
        {
            drawBuffText = buffSlotOnPlayer;
            buffAlpha[buffSlotOnPlayer] += 0.1f;
            bool flag = mouseRight && mouseRightRelease;
            if (PlayerInput.UsingGamepad)
            {
                flag = mouseLeft && mouseLeftRelease && playerInventory;
                if (playerInventory)
                {
                    player[myPlayer].mouseInterface = true;
                }
            }
            else
            {
                player[myPlayer].mouseInterface = true;
            }
            if (flag)
            {
                flag &= BuffLoader.RightClick(num, buffSlotOnPlayer);
            }
            if (flag)
            {
                TryRemovingBuff(buffSlotOnPlayer, num);
            }
        }
        else
        {
            buffAlpha[buffSlotOnPlayer] -= 0.05f;
        }
        if (buffAlpha[buffSlotOnPlayer] > 1f)
        {
            buffAlpha[buffSlotOnPlayer] = 1f;
        }
        else if ((double)buffAlpha[buffSlotOnPlayer] < 0.4)
        {
            buffAlpha[buffSlotOnPlayer] = 0.4f;
        }
        if (PlayerInput.UsingGamepad && !playerInventory)
        {
            drawBuffText = -1;
        }
        return drawBuffText;
    }
References Terraria.GameContent.TextureAssets.Buff, Terraria.Main.buffAlpha, Terraria.Player.buffType, Terraria.Graphics.Light.Color, Terraria.GameContent.FontAssets.ItemStack, Terraria.Lang.LocalizedDuration(), Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.ModLoader.BuffLoader.PostDraw(), Terraria.ModLoader.BuffLoader.PreDraw(), Terraria.ModLoader.BuffLoader.RightClick(), Terraria.Main.spriteBatch, Terraria.Main.TryGetBuffTime(), Terraria.Main.TryRemovingBuff(), and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.Main.DrawInterface_Resources_Buffs(), and Terraria.Main.DrawInventory().