TModLoader: Terraria.Main.DrawMouseOver
DrawMouseOver()
void Terraria.Main.DrawMouseOver () inline
    {
        //IL_03d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0478: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0505: Unknown result type (might be due to invalid IL or missing references)
        //IL_050f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0514: Unknown result type (might be due to invalid IL or missing references)
        //IL_0519: Unknown result type (might be due to invalid IL or missing references)
        //IL_0536: Unknown result type (might be due to invalid IL or missing references)
        //IL_051e: Unknown result type (might be due to invalid IL or missing references)
        //IL_052a: Unknown result type (might be due to invalid IL or missing references)
        //IL_052f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0534: Unknown result type (might be due to invalid IL or missing references)
        //IL_0558: Unknown result type (might be due to invalid IL or missing references)
        //IL_0591: Unknown result type (might be due to invalid IL or missing references)
        //IL_0593: Unknown result type (might be due to invalid IL or missing references)
        //IL_059d: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05db: Unknown result type (might be due to invalid IL or missing references)
        //IL_05eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0622: Unknown result type (might be due to invalid IL or missing references)
        //IL_0629: Unknown result type (might be due to invalid IL or missing references)
        //IL_0637: Unknown result type (might be due to invalid IL or missing references)
        //IL_0639: Unknown result type (might be due to invalid IL or missing references)
        //IL_063e: Unknown result type (might be due to invalid IL or missing references)
        PlayerInput.SetZoom_Unscaled();
        PlayerInput.SetZoom_MouseInWorld();
        Rectangle mouseRectangle = default(Rectangle);
        ((Rectangle)(ref mouseRectangle))._002Ector((int)((float)mouseX + screenPosition.X), (int)((float)mouseY + screenPosition.Y), 1, 1);
        if (player[myPlayer].gravDir == -1f)
        {
            mouseRectangle.Y = (int)screenPosition.Y + screenHeight - mouseY;
        }
        PlayerInput.SetZoom_UI();
        if (!LocalPlayer.ghost)
        {
            ResourceSetsManager.TryToHoverOverResources();
        }
        AchievementAdvisor.DrawMouseHover();
        IngameOptions.MouseOver();
        IngameFancyUI.MouseOver();
        if (!mouseText)
        {
            Rectangle value = default(Rectangle);
            for (int i = 0; i < 400; i++)
            {
                if (!item[i].active)
                {
                    continue;
                }
                Rectangle drawHitbox = Item.GetDrawHitbox(item[i].type, null);
                Vector2 bottom = item[i].Bottom;
                ((Rectangle)(ref value))._002Ector((int)(bottom.X - (float)drawHitbox.Width * 0.5f), (int)(bottom.Y - (float)drawHitbox.Height), drawHitbox.Width, drawHitbox.Height);
                if (((Rectangle)(ref mouseRectangle)).Intersects(value))
                {
                    player[myPlayer].cursorItemIconEnabled = false;
                    string text = item[i].AffixName();
                    if (item[i].stack > 1)
                    {
                        text = text + " (" + item[i].stack + ")";
                    }
                    if (item[i].playerIndexTheItemIsReservedFor < 255 && showItemOwner)
                    {
                        text = text + " <" + player[item[i].playerIndexTheItemIsReservedFor].name + ">";
                    }
                    rare = item[i].rare;
                    if (item[i].expert)
                    {
                        rare = -12;
                    }
                    if (item[i].master)
                    {
                        rare = -13;
                    }
                    MouseTextHackZoom(text, rare, 0);
                    mouseText = true;
                    break;
                }
            }
        }
        Rectangle value2 = default(Rectangle);
        for (int j = 0; j < 255; j++)
        {
            if (!player[j].active || myPlayer == j || player[j].dead || player[j].ShouldNotDraw || !((double)player[j].stealth > 0.5))
            {
                continue;
            }
            ((Rectangle)(ref value2))._002Ector((int)((double)player[j].position.X + (double)player[j].width * 0.5 - 16.0), (int)(player[j].position.Y + (float)player[j].height - 48f), 32, 48);
            if (!mouseText && ((Rectangle)(ref mouseRectangle)).Intersects(value2))
            {
                player[myPlayer].cursorItemIconEnabled = false;
                int num = player[j].statLife;
                if (num < 0)
                {
                    num = 0;
                }
                string text2 = player[j].name + ": " + num + "/" + player[j].statLifeMax2;
                if (player[j].hostile)
                {
                    text2 = text2 + " " + Language.GetTextValue("Game.PvPFlag");
                }
                MouseTextHackZoom(text2, 0, player[j].difficulty);
                mouseText = true;
            }
        }
        HoveringOverAnNPC = false;
        if (!mouseText)
        {
            HoverOverNPCs(mouseRectangle);
        }
        if (!mouseText && signHover != -1 && sign[signHover] != null && !player[myPlayer].mouseInterface && !string.IsNullOrWhiteSpace(sign[signHover].text))
        {
            int lineAmount;
            string[] array = Utils.WordwrapString(sign[signHover].text, FontAssets.MouseText.Value, 460, 10, out lineAmount);
            lineAmount++;
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)0, (BlendState)null, (SamplerState)null, (DepthStencilState)null, (RasterizerState)null, (Effect)null, _uiScaleMatrix);
            PlayerInput.SetZoom_UI();
            int num2 = screenWidth;
            int num3 = screenHeight;
            int num4 = mouseX;
            int num5 = mouseY;
            PlayerInput.SetZoom_UI();
            PlayerInput.SetZoom_Test();
            float num6 = 0f;
            for (int k = 0; k < lineAmount; k++)
            {
                float x = FontAssets.MouseText.Value.MeasureString(array[k]).X;
                if (num6 < x)
                {
                    num6 = x;
                }
            }
            if (num6 > 460f)
            {
                num6 = 460f;
            }
            bool settingsEnabled_OpaqueBoxBehindTooltips = SettingsEnabled_OpaqueBoxBehindTooltips;
            Vector2 vector = new Vector2((float)num4, (float)num5) + new Vector2(16f);
            if (settingsEnabled_OpaqueBoxBehindTooltips)
            {
                vector += new Vector2(8f, 2f);
            }
            if (vector.Y > (float)(num3 - 30 * lineAmount))
            {
                vector.Y = num3 - 30 * lineAmount;
            }
            if (vector.X > (float)num2 - num6)
            {
                vector.X = (float)num2 - num6;
            }
            Color color = default(Color);
            ((Color)(ref color))._002Ector((int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor);
            if (settingsEnabled_OpaqueBoxBehindTooltips)
            {
                color = Color.Lerp(color, Color.White, 1f);
                int num7 = 10;
                int num8 = 5;
                Utils.DrawInvBG(spriteBatch, new Rectangle((int)vector.X - num7, (int)vector.Y - num8, (int)num6 + num7 * 2, 30 * lineAmount + num8 + num8 / 2), new Color(23, 25, 81, 255) * 0.925f * 0.85f);
            }
            for (int l = 0; l < lineAmount; l++)
            {
                Utils.DrawBorderStringFourWay(spriteBatch, FontAssets.MouseText.Value, array[l], vector.X, vector.Y + (float)(l * 30), color, Color.Black, Vector2.Zero);
            }
            mouseText = true;
        }
        PlayerInput.SetZoom_UI();
    }
References Terraria.Main._uiScaleMatrix, Terraria.Graphics.Light.Color, Terraria.Utils.DrawBorderStringFourWay(), Terraria.Utils.DrawInvBG(), Terraria.UI.AchievementAdvisor.DrawMouseHover(), Terraria.Item.GetDrawHitbox(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.HoveringOverAnNPC, Terraria.Main.HoverOverNPCs(), Terraria.Main.item, Terraria.Main.LocalPlayer, Terraria.UI.IngameFancyUI.MouseOver(), Terraria.IngameOptions.MouseOver(), Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseText, Terraria.Main.mouseTextColor, Terraria.Main.MouseTextHackZoom(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.rare, Terraria.Main.ResourceSetsManager, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.SettingsEnabled_OpaqueBoxBehindTooltips, Terraria.GameInput.PlayerInput.SetZoom_MouseInWorld(), Terraria.GameInput.PlayerInput.SetZoom_Test(), Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameInput.PlayerInput.SetZoom_Unscaled(), Terraria.Main.showItemOwner, Terraria.Main.sign, Terraria.Main.signHover, Terraria.Main.spriteBatch, and Terraria.Utils.WordwrapString().
Referenced by Terraria.Main.DrawInterface_39_MouseOver().