TModLoader: Terraria.Main.PlayInteractiveProjectileOpenCloseSound
PlayInteractiveProjectileOpenCloseSound()
static void Terraria.Main.PlayInteractiveProjectileOpenCloseSound (int projType, bool open) inline static
Definition at line 48747 of file Main.cs.
    {
        switch (projType)
        {
        case 525:
            SoundEngine.PlaySound(in SoundID.Item59);
            break;
        case 960:
        {
            SoundStyle style = (open ? SoundID.ChesterOpen : SoundID.ChesterClose);
            SoundEngine.PlaySound(in style);
            break;
        }
        }
    }
References Terraria.ID.SoundID.ChesterClose, Terraria.ID.SoundID.Item59, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.Player.HandleBeingInChestRange(), and Terraria.Main.TryInteractingWithMoneyTrough().