TModLoader: Terraria.Main.StartRain
StartRain()
static void Terraria.Main.StartRain () inline static
Starts rain for a random amount of time. Should be called on the server (netMode != client) - vanilla syncs it using M:Terraria.Main.SyncRain.
You can also call this on the client to update visuals immediately, assuming it was/will be called serverside as well (Journey Mode rain slider does this).
    {
        int num = 86400;
        int num2 = num / 24;
        int num3 = rand.Next(num2 * 8, num);
        if (rand.Next(3) == 0)
        {
            num3 += rand.Next(0, num2);
        }
        if (rand.Next(4) == 0)
        {
            num3 += rand.Next(0, num2 * 2);
        }
        if (rand.Next(5) == 0)
        {
            num3 += rand.Next(0, num2 * 2);
        }
        if (rand.Next(6) == 0)
        {
            num3 += rand.Next(0, num2 * 3);
        }
        if (rand.Next(7) == 0)
        {
            num3 += rand.Next(0, num2 * 4);
        }
        if (rand.Next(8) == 0)
        {
            num3 += rand.Next(0, num2 * 5);
        }
        float num4 = 1f;
        if (rand.Next(2) == 0)
        {
            num4 += 0.05f;
        }
        if (rand.Next(3) == 0)
        {
            num4 += 0.1f;
        }
        if (rand.Next(4) == 0)
        {
            num4 += 0.15f;
        }
        if (rand.Next(5) == 0)
        {
            num4 += 0.2f;
        }
        rainTime = (int)((float)num3 * num4);
        ChangeRain();
        raining = true;
    }
References Terraria.Main.ChangeRain(), Terraria.Main.raining, Terraria.Main.rainTime, and Terraria.Main.rand.
Referenced by Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.UpdateInfoFromSliderValueCache(), and Terraria.Main.UpdateTime().