TModLoader: Terraria.Main.DrawWhip
DrawWhip()
void Terraria.Main.DrawWhip (Projectile proj) inline private
    {
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00de: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_014b: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_016f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_0214: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_021e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_0228: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_0237: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_023c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        List<Vector2> list = new List<Vector2>();
        Projectile.FillWhipControlPoints(proj, list);
        Texture2D value = TextureAssets.FishingLine.Value;
        Rectangle value2 = value.Frame();
        Vector2 origin = default(Vector2);
        ((Vector2)(ref origin))._002Ector((float)(value2.Width / 2), 2f);
        Color originalColor = Color.White;
        switch (proj.type)
        {
        case 847:
            originalColor = Color.OrangeRed;
            break;
        case 849:
            originalColor = Color.SlateBlue;
            originalColor = Color.Black;
            break;
        case 848:
            originalColor = Color.DarkBlue;
            break;
        case 912:
            originalColor = Color.LightBlue;
            break;
        case 913:
            originalColor = Color.Firebrick;
            break;
        case 914:
            originalColor = Color.ForestGreen;
            break;
        case 915:
            originalColor = Color.White;
            break;
        case 952:
            originalColor = Color.Tan;
            break;
        }
        Vector2 vector = list[0];
        Vector2 scale = default(Vector2);
        for (int i = 0; i < list.Count - 1; i++)
        {
            Vector2 vector2 = list[i];
            Vector2 vector3 = list[i + 1] - vector2;
            float rotation = vector3.ToRotation() - (float)Math.PI / 2f;
            Color color = Lighting.GetColor(vector2.ToTileCoordinates(), originalColor);
            ((Vector2)(ref scale))._002Ector(1f, (((Vector2)(ref vector3)).Length() + 2f) / (float)value2.Height);
            spriteBatch.Draw(value, vector - screenPosition, (Rectangle?)value2, color, rotation, origin, scale, (SpriteEffects)0, 0f);
            vector += vector3;
        }
        switch (proj.type)
        {
        case 847:
            vector = DrawWhip_WhipSword(proj, list);
            break;
        case 841:
            vector = DrawWhip_WhipBland(proj, list);
            break;
        case 848:
            vector = DrawWhip_WhipMace(proj, list);
            break;
        case 849:
            vector = DrawWhip_WhipScythe(proj, list);
            break;
        case 912:
            vector = DrawWhip_CoolWhip(proj, list);
            break;
        case 913:
            vector = DrawWhip_FireWhip(proj, list);
            break;
        case 914:
            vector = DrawWhip_ThornWhip(proj, list);
            break;
        case 915:
            vector = DrawWhip_RainbowWhip(proj, list);
            break;
        case 952:
            vector = DrawWhip_BoneWhip(proj, list);
            break;
        }
    }
References Terraria.Main.DrawWhip_BoneWhip(), Terraria.Main.DrawWhip_CoolWhip(), Terraria.Main.DrawWhip_FireWhip(), Terraria.Main.DrawWhip_RainbowWhip(), Terraria.Main.DrawWhip_ThornWhip(), Terraria.Main.DrawWhip_WhipBland(), Terraria.Main.DrawWhip_WhipMace(), Terraria.Main.DrawWhip_WhipScythe(), Terraria.Main.DrawWhip_WhipSword(), Terraria.Projectile.FillWhipControlPoints(), Terraria.GameContent.TextureAssets.FishingLine, Terraria.Lighting.GetColor(), Terraria.Main.screenPosition, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawProj_DrawSpecialProjs().