TModLoader: Terraria.Main.DrawToMap_Section
DrawToMap_Section()
void Terraria.Main.DrawToMap_Section (int secX, int secY) inline protected
    {
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_0145: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        Stopwatch stopwatch = Stopwatch.StartNew();
        Color[] mapColorCacheArray = _mapColorCacheArray;
        int num = secX * 200;
        int num2 = num + 200;
        int num3 = secY * 150;
        int num4 = num3 + 150;
        int num5 = num / textureMaxWidth;
        int num6 = num3 / textureMaxHeight;
        int num7 = num % textureMaxWidth;
        int num8 = num3 % textureMaxHeight;
        if (!checkMap(num5, num6))
        {
            return;
        }
        int num9 = 0;
        _ = Color.Transparent;
        for (int i = num3; i < num4; i++)
        {
            for (int j = num; j < num2; j++)
            {
                MapTile mapTile = Map[j, i];
                mapColorCacheArray[num9] = MapHelper.GetMapTileXnaColor(ref mapTile);
                num9++;
            }
        }
        try
        {
            ((Game)this).GraphicsDevice.SetRenderTarget(mapTarget[num5, num6]);
        }
        catch (ObjectDisposedException)
        {
            initMap[num5, num6] = false;
            return;
        }
        spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend);
        _ = stopwatch.Elapsed.TotalMilliseconds;
        ((Texture2D)mapSectionTexture).SetData<Color>(mapColorCacheArray, 0, mapColorCacheArray.Length);
        _ = stopwatch.Elapsed.TotalMilliseconds;
        _ = stopwatch.Elapsed.TotalMilliseconds;
        spriteBatch.Draw((Texture2D)(object)mapSectionTexture, new Vector2((float)num7, (float)num8), Color.White);
        spriteBatch.End();
        ((Game)this).GraphicsDevice.SetRenderTarget((RenderTarget2D)null);
        _ = stopwatch.Elapsed.TotalMilliseconds;
        stopwatch.Stop();
    }
References Terraria.Main._mapColorCacheArray, Terraria.Main.checkMap(), Terraria.Graphics.Light.Color, Terraria.Map.MapHelper.GetMapTileXnaColor(), Terraria.Main.initMap, Terraria.Main.Map, Terraria.Main.mapSectionTexture, Terraria.Main.mapTarget, Terraria.Main.spriteBatch, Terraria.Main.textureMaxHeight, and Terraria.Main.textureMaxWidth.
Referenced by Terraria.Main.DoDraw().