TModLoader: Terraria.Main.DrawPlayers_BehindNPCs
DrawPlayers_BehindNPCs()
void Terraria.Main.DrawPlayers_BehindNPCs () inline protected
Definition at line 21861 of file Main.cs.
    {
        PotionOfReturnRenderer.DrawPlayers(Camera, _playersThatDrawBehindNPCs.Where((Player p) => p.PotionOfReturnOriginalUsePosition.HasValue));
        PlayerRenderer.DrawPlayers(Camera, _playersThatDrawBehindNPCs);
    }
References Terraria.Main._playersThatDrawBehindNPCs, Terraria.Graphics.Renderers.IPlayerRenderer.DrawPlayers(), Terraria.Main.PlayerRenderer, and Terraria.Main.PotionOfReturnRenderer.
Referenced by Terraria.Main.DoDraw_WallsTilesNPCs(), and Terraria.Main.DrawCapture().