TModLoader: Terraria.Main.DrawMenu
DrawMenu()
void Terraria.Main.DrawMenu (GameTime gameTime) inline protected
Definition at line 62265 of file Main.cs.
    {
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_052a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0625: Unknown result type (might be due to invalid IL or missing references)
        //IL_0640: Unknown result type (might be due to invalid IL or missing references)
        //IL_064a: Unknown result type (might be due to invalid IL or missing references)
        //IL_066b: Unknown result type (might be due to invalid IL or missing references)
        //IL_069d: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ff1: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ff6: Unknown result type (might be due to invalid IL or missing references)
        //IL_5ffb: Unknown result type (might be due to invalid IL or missing references)
        //IL_6003: Unknown result type (might be due to invalid IL or missing references)
        //IL_072a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0745: Unknown result type (might be due to invalid IL or missing references)
        //IL_074f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0770: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_60a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_60a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_7172: Unknown result type (might be due to invalid IL or missing references)
        //IL_7177: Unknown result type (might be due to invalid IL or missing references)
        //IL_7181: Unknown result type (might be due to invalid IL or missing references)
        //IL_7190: Unknown result type (might be due to invalid IL or missing references)
        //IL_719f: Unknown result type (might be due to invalid IL or missing references)
        //IL_71a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_71a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_617b: Unknown result type (might be due to invalid IL or missing references)
        //IL_6180: Unknown result type (might be due to invalid IL or missing references)
        //IL_611b: Unknown result type (might be due to invalid IL or missing references)
        //IL_6120: Unknown result type (might be due to invalid IL or missing references)
        //IL_75c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_75cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_74e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_74e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_74f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_7502: Unknown result type (might be due to invalid IL or missing references)
        //IL_7511: Unknown result type (might be due to invalid IL or missing references)
        //IL_7516: Unknown result type (might be due to invalid IL or missing references)
        //IL_751b: Unknown result type (might be due to invalid IL or missing references)
        //IL_7096: Unknown result type (might be due to invalid IL or missing references)
        //IL_7097: Unknown result type (might be due to invalid IL or missing references)
        //IL_7c52: Unknown result type (might be due to invalid IL or missing references)
        //IL_7c61: Unknown result type (might be due to invalid IL or missing references)
        //IL_7c66: Unknown result type (might be due to invalid IL or missing references)
        //IL_7c6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_7c75: Unknown result type (might be due to invalid IL or missing references)
        //IL_7c7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_7c7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_7c92: Unknown result type (might be due to invalid IL or missing references)
        //IL_7c9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_7ca1: Unknown result type (might be due to invalid IL or missing references)
        //IL_7ca3: Unknown result type (might be due to invalid IL or missing references)
        //IL_7129: Unknown result type (might be due to invalid IL or missing references)
        //IL_712b: Unknown result type (might be due to invalid IL or missing references)
        //IL_7130: Unknown result type (might be due to invalid IL or missing references)
        //IL_7204: Unknown result type (might be due to invalid IL or missing references)
        //IL_7209: Unknown result type (might be due to invalid IL or missing references)
        //IL_7213: Unknown result type (might be due to invalid IL or missing references)
        //IL_7222: Unknown result type (might be due to invalid IL or missing references)
        //IL_7231: Unknown result type (might be due to invalid IL or missing references)
        //IL_7236: Unknown result type (might be due to invalid IL or missing references)
        //IL_723b: Unknown result type (might be due to invalid IL or missing references)
        //IL_6248: Unknown result type (might be due to invalid IL or missing references)
        //IL_6257: Unknown result type (might be due to invalid IL or missing references)
        //IL_6261: Unknown result type (might be due to invalid IL or missing references)
        //IL_6266: Unknown result type (might be due to invalid IL or missing references)
        //IL_628c: Unknown result type (might be due to invalid IL or missing references)
        //IL_6291: Unknown result type (might be due to invalid IL or missing references)
        //IL_75f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_75fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_73b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_73b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_73be: Unknown result type (might be due to invalid IL or missing references)
        //IL_73bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_7296: Unknown result type (might be due to invalid IL or missing references)
        //IL_729b: Unknown result type (might be due to invalid IL or missing references)
        //IL_72a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_72b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_72c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_72c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_72cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_62b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_62b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_62d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_62dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_7630: Unknown result type (might be due to invalid IL or missing references)
        //IL_7631: Unknown result type (might be due to invalid IL or missing references)
        //IL_7635: Unknown result type (might be due to invalid IL or missing references)
        //IL_763a: Unknown result type (might be due to invalid IL or missing references)
        //IL_763e: Unknown result type (might be due to invalid IL or missing references)
        //IL_7643: Unknown result type (might be due to invalid IL or missing references)
        //IL_7647: Unknown result type (might be due to invalid IL or missing references)
        //IL_764c: Unknown result type (might be due to invalid IL or missing references)
        //IL_7650: Unknown result type (might be due to invalid IL or missing references)
        //IL_7655: Unknown result type (might be due to invalid IL or missing references)
        //IL_7b0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_7b17: Unknown result type (might be due to invalid IL or missing references)
        //IL_7b1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_79eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_79f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_79fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_7a05: Unknown result type (might be due to invalid IL or missing references)
        //IL_79a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_79bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_7d6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_7dc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_7dd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_7e0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_7659: Unknown result type (might be due to invalid IL or missing references)
        //IL_765a: Unknown result type (might be due to invalid IL or missing references)
        //IL_7b39: Unknown result type (might be due to invalid IL or missing references)
        //IL_7a2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_6ace: Unknown result type (might be due to invalid IL or missing references)
        //IL_6ad3: Unknown result type (might be due to invalid IL or missing references)
        //IL_6c72: Unknown result type (might be due to invalid IL or missing references)
        //IL_63b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_63bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_6357: Unknown result type (might be due to invalid IL or missing references)
        //IL_635c: Unknown result type (might be due to invalid IL or missing references)
        //IL_7e82: Unknown result type (might be due to invalid IL or missing references)
        //IL_7eab: Unknown result type (might be due to invalid IL or missing references)
        //IL_7e4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_7e2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_7e3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_6ada: Unknown result type (might be due to invalid IL or missing references)
        //IL_6adb: Unknown result type (might be due to invalid IL or missing references)
        //IL_7ec6: Unknown result type (might be due to invalid IL or missing references)
        //IL_7ecb: Unknown result type (might be due to invalid IL or missing references)
        //IL_6e24: Unknown result type (might be due to invalid IL or missing references)
        //IL_6e29: Unknown result type (might be due to invalid IL or missing references)
        //IL_6c9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_6484: Unknown result type (might be due to invalid IL or missing references)
        //IL_6493: Unknown result type (might be due to invalid IL or missing references)
        //IL_649d: Unknown result type (might be due to invalid IL or missing references)
        //IL_64a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_64c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_64cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_7f43: Unknown result type (might be due to invalid IL or missing references)
        //IL_7f48: Unknown result type (might be due to invalid IL or missing references)
        //IL_747e: Unknown result type (might be due to invalid IL or missing references)
        //IL_7483: Unknown result type (might be due to invalid IL or missing references)
        //IL_748c: Unknown result type (might be due to invalid IL or missing references)
        //IL_7492: Unknown result type (might be due to invalid IL or missing references)
        //IL_6e30: Unknown result type (might be due to invalid IL or missing references)
        //IL_6e31: Unknown result type (might be due to invalid IL or missing references)
        //IL_650a: Unknown result type (might be due to invalid IL or missing references)
        //IL_650f: Unknown result type (might be due to invalid IL or missing references)
        //IL_652d: Unknown result type (might be due to invalid IL or missing references)
        //IL_6532: Unknown result type (might be due to invalid IL or missing references)
        //IL_6b9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_6b9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_6ba8: Unknown result type (might be due to invalid IL or missing references)
        //IL_6bae: Unknown result type (might be due to invalid IL or missing references)
        //IL_6619: Unknown result type (might be due to invalid IL or missing references)
        //IL_661e: Unknown result type (might be due to invalid IL or missing references)
        //IL_65ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_65b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_6ee9: Unknown result type (might be due to invalid IL or missing references)
        //IL_6eee: Unknown result type (might be due to invalid IL or missing references)
        //IL_6ef7: Unknown result type (might be due to invalid IL or missing references)
        //IL_6efd: Unknown result type (might be due to invalid IL or missing references)
        //IL_66f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_6704: Unknown result type (might be due to invalid IL or missing references)
        //IL_670e: Unknown result type (might be due to invalid IL or missing references)
        //IL_6713: Unknown result type (might be due to invalid IL or missing references)
        //IL_674e: Unknown result type (might be due to invalid IL or missing references)
        //IL_6753: Unknown result type (might be due to invalid IL or missing references)
        //IL_6768: Unknown result type (might be due to invalid IL or missing references)
        //IL_676d: Unknown result type (might be due to invalid IL or missing references)
        //IL_69ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_69b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_7934: Unknown result type (might be due to invalid IL or missing references)
        //IL_7949: Unknown result type (might be due to invalid IL or missing references)
        //IL_794e: Unknown result type (might be due to invalid IL or missing references)
        //IL_795a: Unknown result type (might be due to invalid IL or missing references)
        //IL_7961: Unknown result type (might be due to invalid IL or missing references)
        //IL_78d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_78eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_78f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_78f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_677d: Unknown result type (might be due to invalid IL or missing references)
        //IL_6781: Unknown result type (might be due to invalid IL or missing references)
        //IL_6786: Unknown result type (might be due to invalid IL or missing references)
        //IL_67a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_67a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_6884: Unknown result type (might be due to invalid IL or missing references)
        //IL_6889: Unknown result type (might be due to invalid IL or missing references)
        //IL_6824: Unknown result type (might be due to invalid IL or missing references)
        //IL_6829: Unknown result type (might be due to invalid IL or missing references)
        //IL_6954: Unknown result type (might be due to invalid IL or missing references)
        //IL_6963: Unknown result type (might be due to invalid IL or missing references)
        //IL_696d: Unknown result type (might be due to invalid IL or missing references)
        //IL_6972: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d46: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d4b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2575: Unknown result type (might be due to invalid IL or missing references)
        //IL_257a: Unknown result type (might be due to invalid IL or missing references)
        //IL_23ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_23b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1dae: Unknown result type (might be due to invalid IL or missing references)
        //IL_1db3: Unknown result type (might be due to invalid IL or missing references)
        //IL_26fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_2703: Unknown result type (might be due to invalid IL or missing references)
        //IL_23e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_23e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cb7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_27b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_27be: Unknown result type (might be due to invalid IL or missing references)
        //IL_2416: Unknown result type (might be due to invalid IL or missing references)
        //IL_241b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2874: Unknown result type (might be due to invalid IL or missing references)
        //IL_2879: Unknown result type (might be due to invalid IL or missing references)
        //IL_242e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2433: Unknown result type (might be due to invalid IL or missing references)
        //IL_2930: Unknown result type (might be due to invalid IL or missing references)
        //IL_2935: Unknown result type (might be due to invalid IL or missing references)
        //IL_29ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_29f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aa8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2aad: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fd9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fe6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1feb: Unknown result type (might be due to invalid IL or missing references)
        //IL_202c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2031: Unknown result type (might be due to invalid IL or missing references)
        //IL_203c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2041: Unknown result type (might be due to invalid IL or missing references)
        //IL_204c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2051: Unknown result type (might be due to invalid IL or missing references)
        //IL_205c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2061: Unknown result type (might be due to invalid IL or missing references)
        //IL_206c: Unknown result type (might be due to invalid IL or missing references)
        //IL_2071: Unknown result type (might be due to invalid IL or missing references)
        //IL_2112: Unknown result type (might be due to invalid IL or missing references)
        //IL_2117: Unknown result type (might be due to invalid IL or missing references)
        //IL_4812: Unknown result type (might be due to invalid IL or missing references)
        //IL_4817: Unknown result type (might be due to invalid IL or missing references)
        //IL_4821: Unknown result type (might be due to invalid IL or missing references)
        //IL_48c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_48cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_48d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_4584: Unknown result type (might be due to invalid IL or missing references)
        //IL_4589: Unknown result type (might be due to invalid IL or missing references)
        //IL_4593: Unknown result type (might be due to invalid IL or missing references)
        //IL_45de: Unknown result type (might be due to invalid IL or missing references)
        //IL_45e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_45ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_4cce: Unknown result type (might be due to invalid IL or missing references)
        //IL_5079: Unknown result type (might be due to invalid IL or missing references)
        if (!IsEngineLoaded)
        {
            IsEngineLoaded = true;
            if (Main.OnEngineLoad != null)
            {
                Main.OnEngineLoad();
            }
        }
        GamepadMainMenuHandler.Update();
        GamepadMainMenuHandler.MenuItemPositions.Clear();
        int num = menuMode;
        if (menuMode <= 1 && slimeRain)
        {
            StopSlimeRain();
        }
        render = false;
        SceneMetrics.Reset();
        drawingPlayerChat = false;
        chatMonitor.Clear();
        screenLastPosition = screenPosition;
        screenPosition.Y = (float)(worldSurface * 16.0 - (double)screenHeight);
        MenuXMovement = 4f;
        if (alreadyGrabbingSunOrMoon && !playOldTile)
        {
            playOldTile = true;
            MenuLoader.ActivateOldVanillaMenu();
            if (starGame)
            {
                playOldTile = false;
            }
        }
        screenPosition.X += MenuXMovement;
        if (screenPosition.X > 2.1474835E+09f)
        {
            screenPosition.X = 0f;
        }
        if (screenPosition.X < -2.1474835E+09f)
        {
            screenPosition.X = 0f;
        }
        Star.UpdateStars();
        Cloud.UpdateClouds();
        DrawFPS();
        background = 0;
        byte b = (byte)((255 + ((Color)(ref tileColor)).R * 2) / 3);
        Color color = default(Color);
        ((Color)(ref color))._002Ector((int)b, (int)b, (int)b, 255);
        if (WorldGen.remixWorldGen)
        {
            logoRotation += logoRotationSpeed * 4E-05f;
            if ((double)logoRotation < 3.04)
            {
                logoRotation += logoRotationSpeed * 0.0016f;
                if (logoRotationSpeed < 0f)
                {
                    logoRotationSpeed = 0f;
                }
            }
            if ((double)logoRotation > 3.22)
            {
                logoRotationDirection = -1f;
            }
            else if ((double)logoRotation < 3.06)
            {
                logoRotationDirection = 1f;
            }
            if (logoRotationSpeed < 20f && logoRotationDirection == 1f)
            {
                logoRotationSpeed += 1f;
            }
            else if (logoRotationSpeed > -20f && logoRotationDirection == -1f)
            {
                logoRotationSpeed -= 1f;
            }
            logoScale += logoScaleSpeed * 9E-05f;
            if (logoScale > 1f)
            {
                logoScaleDirection = -1f;
            }
            else if (logoScale < 0.9f)
            {
                logoScaleDirection = 1f;
            }
            if (logoScaleSpeed < 50f && logoScaleDirection == 1f)
            {
                logoScaleSpeed += 1f;
            }
            else if (logoScaleSpeed > -50f && logoScaleDirection == -1f)
            {
                logoScaleSpeed -= 1f;
            }
        }
        else if (WorldGen.drunkWorldGen)
        {
            logoRotation += logoRotationSpeed * 4E-06f;
            if (logoRotationSpeed > 0f)
            {
                logoRotationSpeed += 1500f;
            }
            else
            {
                logoRotationSpeed -= 1500f;
            }
            logoScale -= 0.05f;
            if (logoScale < 0f)
            {
                logoScale = 0f;
            }
        }
        else
        {
            if ((double)logoRotation > 0.09)
            {
                logoRotation += logoRotationSpeed * 0.0016f;
                if (logoRotationSpeed > 0f)
                {
                    logoRotationSpeed = 0f;
                }
            }
            logoRotation += logoRotationSpeed * 4E-06f;
            if ((double)logoRotation > 0.08)
            {
                logoRotationDirection = -1f;
            }
            else if ((double)logoRotation < -0.08)
            {
                logoRotationDirection = 1f;
            }
            if (logoRotationSpeed < 20f && logoRotationDirection == 1f)
            {
                logoRotationSpeed += 1f;
            }
            else if (logoRotationSpeed > -20f && logoRotationDirection == -1f)
            {
                logoRotationSpeed -= 1f;
            }
            logoScale += logoScaleSpeed * 9E-06f;
            if ((double)logoScale > 1.35)
            {
                logoScaleDirection = -1f;
            }
            else if (logoScale < 1f)
            {
                logoScaleDirection = 1f;
            }
            if (logoScaleSpeed < 50f && logoScaleDirection == 1f)
            {
                logoScaleSpeed += 1f;
            }
            else if (logoScaleSpeed > -50f && logoScaleDirection == -1f)
            {
                logoScaleSpeed -= 1f;
            }
        }
        MenuLoader.UpdateAndDrawModMenu(spriteBatch, gameTime, color, logoRotation, logoScale);
        Color color5 = default(Color);
        ((Color)(ref color5))._002Ector((int)(byte)((float)(int)((Color)(ref color)).R * ((float)LogoA / 255f)), (int)(byte)((float)(int)((Color)(ref color)).G * ((float)LogoA / 255f)), (int)(byte)((float)(int)((Color)(ref color)).B * ((float)LogoA / 255f)), (int)(byte)((float)(int)((Color)(ref color)).A * ((float)LogoA / 255f)));
        Color color6 = default(Color);
        ((Color)(ref color6))._002Ector((int)(byte)((float)(int)((Color)(ref color)).R * ((float)LogoB / 255f)), (int)(byte)((float)(int)((Color)(ref color)).G * ((float)LogoB / 255f)), (int)(byte)((float)(int)((Color)(ref color)).B * ((float)LogoB / 255f)), (int)(byte)((float)(int)((Color)(ref color)).A * ((float)LogoB / 255f)));
        if (MenuLoader.MenuOldVanilla.IsSelected)
        {
            spriteBatch.Draw(TextureAssets.Logo3.Value, new Vector2((float)(screenWidth / 2), 100f), (Rectangle?)new Rectangle(0, 0, TextureAssets.Logo.Width(), TextureAssets.Logo.Height()), color5, logoRotation, new Vector2((float)(TextureAssets.Logo.Width() / 2), (float)(TextureAssets.Logo.Height() / 2)), logoScale, (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.Logo4.Value, new Vector2((float)(screenWidth / 2), 100f), (Rectangle?)new Rectangle(0, 0, TextureAssets.Logo.Width(), TextureAssets.Logo.Height()), color6, logoRotation, new Vector2((float)(TextureAssets.Logo.Width() / 2), (float)(TextureAssets.Logo.Height() / 2)), logoScale, (SpriteEffects)0, 0f);
        }
        else if (MenuLoader.MenuJourneysEnd.IsSelected)
        {
            spriteBatch.Draw(TextureAssets.Logo.Value, new Vector2((float)(screenWidth / 2), 100f), (Rectangle?)new Rectangle(0, 0, TextureAssets.Logo.Width(), TextureAssets.Logo.Height()), color5, logoRotation, new Vector2((float)(TextureAssets.Logo.Width() / 2), (float)(TextureAssets.Logo.Height() / 2)), logoScale, (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.Logo2.Value, new Vector2((float)(screenWidth / 2), 100f), (Rectangle?)new Rectangle(0, 0, TextureAssets.Logo.Width(), TextureAssets.Logo.Height()), color6, logoRotation, new Vector2((float)(TextureAssets.Logo.Width() / 2), (float)(TextureAssets.Logo.Height() / 2)), logoScale, (SpriteEffects)0, 0f);
        }
        if (dayTime && !WorldGen.remixWorldGen)
        {
            LogoA += 2;
            if (LogoA > 255)
            {
                LogoA = 255;
            }
            LogoB--;
            if (LogoB < 0)
            {
                LogoB = 0;
            }
        }
        else
        {
            LogoB += 2;
            if (LogoB > 255)
            {
                LogoB = 255;
            }
            LogoA--;
            if (LogoA < 0)
            {
                LogoA = 0;
                LogoT = true;
            }
        }
        int num24 = 250;
        int num35 = screenWidth / 2;
        int num46 = 80;
        int num57 = 0;
        int num68 = menuMode;
        int num79 = 0;
        int num90 = 0;
        bool flag = false;
        bool flag4 = false;
        bool flag5 = false;
        int num101 = 0;
        bool[] array = new bool[maxMenuItems];
        bool[] array4 = new bool[maxMenuItems];
        bool[] array5 = new bool[maxMenuItems];
        int[] array6 = new int[maxMenuItems];
        int[] array7 = new int[maxMenuItems];
        byte[] array8 = new byte[maxMenuItems];
        float[] array9 = new float[maxMenuItems];
        bool[] array10 = new bool[maxMenuItems];
        bool flag6 = false;
        bool flag7 = UILinkPointNavigator.Shortcuts.BackButtonInUse && !UILinkPointNavigator.Shortcuts.BackButtonLock;
        for (int i = 0; i < maxMenuItems; i++)
        {
            array[i] = false;
            array4[i] = false;
            array6[i] = 0;
            array7[i] = 0;
            array9[i] = 1f;
        }
        string[] array11 = new string[maxMenuItems];
        if (menuMode == -1)
        {
            menuMode = 0;
        }
        if (Program.LoadedEverything)
        {
            GamepadMainMenuHandler.CanRun = true;
            if (menuMode == 1212)
            {
                array11[0] = Lang.menu[102].Value;
                num46 = 50;
                num24 = 200;
                num46 = 33;
                num24 = 200;
                array6[0] = -20;
                array6[1] = 25;
                array6[2] = 25;
                array6[3] = 25;
                array6[4] = 25;
                array6[5] = 25;
                array6[6] = 25;
                array6[7] = 25;
                array6[8] = 25;
                array6[9] = 25;
                array[0] = true;
                array11[1] = Language.GetTextValue("Language.English");
                array11[2] = Language.GetTextValue("Language.German");
                array11[3] = Language.GetTextValue("Language.Italian");
                array11[4] = Language.GetTextValue("Language.French");
                array11[5] = Language.GetTextValue("Language.Spanish");
                array11[6] = Language.GetTextValue("Language.Russian");
                array11[7] = Language.GetTextValue("Language.Chinese");
                array11[8] = Language.GetTextValue("Language.Portuguese");
                array11[9] = Language.GetTextValue("Language.Polish");
                num57 = 10;
                for (int j = 0; j < num57; j++)
                {
                    array9[j] = 0.75f;
                }
                array9[0] = 1f;
                if (selectedMenu >= 1)
                {
                    changeTheTitle = true;
                    LanguageManager.Instance.SetLanguage(selectedMenu);
                    menuMode = 10002;
                    SoundEngine.PlaySound(10);
                    SaveSettings();
                }
            }
            else if (menuMode == 1213)
            {
                array11[0] = Lang.menu[102].Value;
                array[0] = true;
                array11[1] = Language.GetTextValue("Language.English");
                array11[2] = Language.GetTextValue("Language.German");
                array11[3] = Language.GetTextValue("Language.Italian");
                array11[4] = Language.GetTextValue("Language.French");
                array11[5] = Language.GetTextValue("Language.Spanish");
                array11[6] = Language.GetTextValue("Language.Russian");
                array11[7] = Language.GetTextValue("Language.Chinese");
                array11[8] = Language.GetTextValue("Language.Portuguese");
                array11[9] = Language.GetTextValue("Language.Polish");
                array11[10] = Lang.menu[5].Value;
                num57 = 11;
                if (selectedMenu == 10 || flag7)
                {
                    flag7 = false;
                    menuMode = 11;
                    SoundEngine.PlaySound(11);
                }
                else if (selectedMenu >= 1)
                {
                    changeTheTitle = true;
                    LanguageManager.Instance.SetLanguage(selectedMenu);
                    SoundEngine.PlaySound(12);
                    SaveSettings();
                }
                num46 = 33;
                num24 = 200;
                array6[0] = -20;
                array6[10] = 10;
                for (int k = 0; k < num57; k++)
                {
                    array9[k] = 0.75f;
                }
                array9[0] = 0.85f;
                array9[10] = 0.95f;
            }
            else if (netMode == 2)
            {
                bool flag8 = true;
                for (int l = 0; l < 8; l++)
                {
                    if (l >= 255)
                    {
                        continue;
                    }
                    try
                    {
                        array11[l] = Netplay.Clients[l].StatusText;
                        if (Netplay.Clients[l].IsActive && showSpam)
{
                            ref string reference = ref array11[l];
                            reference = reference + " (" + NetMessage.buffer[l].spamCount + ")";
                        }
                    }
                    catch
                    {
                        array11[l] = "";
                    }
                    array[l] = true;
                    if (array11[l] != "" && array11[l] != null)
                    {
                        flag8 = false;
                    }
                }
                if (flag8)
                {
                    array11[0] = Lang.menu[0].Value;
                    array11[1] = Lang.menu[1].Value + Netplay.ListenPort + ".";
                }
                num57 = 11;
                array11[9] = statusText;
                array[9] = true;
                num24 = 170;
                num46 = 30;
                array6[10] = 20;
                array6[10] = 40;
                array11[10] = Lang.menu[2].Value;
                if (selectedMenu == 10 || flag7)
                {
                    flag7 = false;
                    Netplay.Disconnect = true;
                    SoundEngine.PlaySound(11);
                }
            }
            else if (menuMode == 31)
            {
                if (PlayerInput.SettingsForUI.ShowGamepadHints)
                {
                    UIVirtualKeyboard uIVirtualKeyboard = new UIVirtualKeyboard(Lang.menu[3].Value, Netplay.ServerPassword, OnSubmitServerPasswordFromRequest, CanceledGivingServerPassword, 0, allowEmpty: true);
                    uIVirtualKeyboard.HideContents = HidePassword;
                    UserInterface.ActiveInstance.SetState(uIVirtualKeyboard);
                    menuMode = 888;
                }
                string serverPassword = Netplay.ServerPassword;
                PlayerInput.WritingText = true;
                instance.HandleIME();
                Netplay.ServerPassword = GetInputText(Netplay.ServerPassword);
                if (serverPassword != Netplay.ServerPassword)
                {
                    SoundEngine.PlaySound(12);
                }
                array11[0] = Lang.menu[3].Value;
                textBlinkerCount++;
                if (textBlinkerCount >= 20)
                {
                    if (textBlinkerState == 0)
                    {
                        textBlinkerState = 1;
                    }
                    else
                    {
                        textBlinkerState = 0;
                    }
                    textBlinkerCount = 0;
                }
                array11[1] = Netplay.ServerPassword;
                if (HidePassword)
                {
                    array11[1] = "";
                    for (int m = 0; m < Netplay.ServerPassword.Length; m++)
                    {
                        array11[1] += "*";
                    }
                }
                if (textBlinkerState == 1)
                {
                    array11[1] += "|";
                    array7[1] = 1;
                }
                else
                {
                    array11[1] += " ";
                }
                array[0] = true;
                array[1] = true;
                array6[1] = -20;
                array6[2] = 20;
                array11[2] = Lang.menu[4].Value;
                array11[3] = Lang.menu[5].Value;
                num57 = 4;
                if (selectedMenu == 3 || flag7)
                {
                    flag7 = false;
                    CanceledGivingServerPassword();
                }
                else if (selectedMenu == 2 || inputTextEnter)
                {
                    OnSubmitServerPasswordFromRequest();
                }
            }
            else if ((netMode == 1 && menuMode < 10000 && menuMode != 888) || menuMode == 14)
            {
                num57 = 2;
                array11[0] = statusText;
                array[0] = true;
                num24 = 300;
                int num2 = statusText.Split('\n').Length - 1;
                array9[0] = 1f - (float)num2 * 0.04f;
                array6[0] = num2 * -18;
                array6[1] = num2 * 28;
                array11[1] = Lang.menu[6].Value;
                gameTips.Update();
                gameTips.Draw();
                if (selectedMenu == 1 || flag7)
                {
                    flag7 = false;
                    Netplay.InvalidateAllOngoingIPSetAttempts();
                    Netplay.Disconnect = true;
                    Netplay.Connection.Socket.Close();
                    SoundEngine.PlaySound(11);
                    menuMode = 0;
                    netMode = 0;
                    if (tServer != null)
                    {
                        try
{
                            tServer.Kill();
                            tServer = null;
                        }
                        catch
{
                        }
                    }
                }
            }
            else if (menuMode == 882)
            {
                num57 = 2;
                array[0] = true;
                num24 = 300;
                array11[0] = statusText;
                array11[1] = Lang.menu[6].Value;
                if (selectedMenu == 1 || flag7)
                {
                    flag7 = false;
                    SoundEngine.PlaySound(11);
                    menuMode = 0;
                    netMode = 0;
                    if (SocialAPI.Network != null)
                    {
                        SocialAPI.Network.CancelJoin();
                    }
                }
            }
            else if (menuMode == 30)
            {
                if (PlayerInput.SettingsForUI.ShowGamepadHints)
                {
                    UIVirtualKeyboard uIVirtualKeyboard2 = new UIVirtualKeyboard(Lang.menu[7].Value, Netplay.ServerPassword, OnSubmitServerPassword, ExitServerPasswordMenu, 0, allowEmpty: true);
                    uIVirtualKeyboard2.HideContents = HidePassword;
                    UserInterface.ActiveInstance.SetState(uIVirtualKeyboard2);
                    menuMode = 888;
                }
                string serverPassword2 = Netplay.ServerPassword;
                PlayerInput.WritingText = true;
                instance.HandleIME();
                Netplay.ServerPassword = GetInputText(Netplay.ServerPassword);
                if (serverPassword2 != Netplay.ServerPassword)
                {
                    SoundEngine.PlaySound(12);
                }
                array11[0] = Lang.menu[7].Value;
                textBlinkerCount++;
                if (textBlinkerCount >= 20)
                {
                    if (textBlinkerState == 0)
                    {
                        textBlinkerState = 1;
                    }
                    else
                    {
                        textBlinkerState = 0;
                    }
                    textBlinkerCount = 0;
                }
                array11[1] = Netplay.ServerPassword;
                if (HidePassword)
                {
                    array11[1] = "";
                    for (int n = 0; n < Netplay.ServerPassword.Length; n++)
                    {
                        array11[1] += "*";
                    }
                }
                if (textBlinkerState == 1)
                {
                    array11[1] += "|";
                    array7[1] = 1;
                }
                else
                {
                    array11[1] += " ";
                }
                array[0] = true;
                array[1] = true;
                array6[1] = -20;
                array6[2] = 20;
                array11[2] = Lang.menu[4].Value;
                array11[3] = Lang.menu[5].Value;
                num57 = 4;
                if (selectedMenu == 3 || flag7)
                {
                    flag7 = false;
                    ExitServerPasswordMenu();
                }
                else if (selectedMenu == 2 || inputTextEnter || autoPass)
                {
                    OnSubmitServerPassword();
                }
            }
            else if (menuMode == 889)
            {
                num24 = 200;
                num46 = 60;
                array6[1] = 30;
                array6[2] = 30;
                array6[3] = 30;
                array6[4] = 70;
                array6[5] = 70;
                num57 = 6;
                int serverConsoleToggleId = num57++;
                array6[serverConsoleToggleId] = 70;
                array11[serverConsoleToggleId] = Language.GetTextValue(showServerConsole ? "tModLoader.MPShowServerConsoleYes" : "tModLoader.MPShowServerConsoleNo");
                array9[serverConsoleToggleId] = 0.5f;
                array11[0] = Lang.menu[135].Value;
                array11[4] = Lang.menu[144].Value;
                array11[5] = Lang.menu[5].Value;
                array[0] = true;
                if (!MenuServerMode.HasFlag(ServerMode.Lobby))
                {
                    MenuServerMode = ServerMode.None;
                    array[2] = true;
                    array[3] = true;
                    array11[1] = Lang.menu[136].Value;
                    array11[2] = "";
                    array11[3] = "";
                }
                else
                {
                    array11[1] = Lang.menu[137].Value;
                    if (MenuServerMode.HasFlag(ServerMode.FriendsCanJoin))
                    {
                        array11[2] = Lang.menu[139].Value;
                        if (MenuServerMode.HasFlag(ServerMode.FriendsOfFriends))
{
                            array11[3] = Lang.menu[143].Value;
                        }
                        else
{
                            array11[3] = Lang.menu[142].Value;
                        }
                    }
                    else
                    {
                        array11[2] = Lang.menu[138].Value;
                        if (MenuServerMode.HasFlag(ServerMode.FriendsOfFriends))
{
                            array11[3] = Lang.menu[141].Value;
                        }
                        else
{
                            array11[3] = Lang.menu[140].Value;
                        }
                    }
                }
                if (flag7)
                {
                    flag7 = false;
                    selectedMenu = 5;
                }
                switch (selectedMenu)
                {
                case 1:
                    MenuServerMode ^= ServerMode.Lobby;
                    SoundEngine.PlaySound(12);
                    break;
                case 2:
                    MenuServerMode ^= ServerMode.FriendsCanJoin;
                    SoundEngine.PlaySound(12);
                    break;
                case 3:
                    MenuServerMode ^= ServerMode.FriendsOfFriends;
                    SoundEngine.PlaySound(12);
                    break;
                case 4:
                    clrInput();
                    Netplay.ServerPassword = "";
                    GetInputText("");
                    autoPass = false;
                    menuMode = 30;
                    SoundEngine.PlaySound(10);
                    break;
                case 5:
                    menuMode = 6;
                    SoundEngine.PlaySound(11);
                    break;
                default:
                    if (selectedMenu == serverConsoleToggleId)
                    {
                        showServerConsole = !showServerConsole;
                        SoundEngine.PlaySound(12);
                    }
                    break;
                }
            }
            else if (menuMode == 15)
            {
                num57 = 2;
                array11[0] = statusText;
                array[0] = true;
                num24 = 80;
                num46 = 400;
                array11[1] = Lang.menu[5].Value;
                if (selectedMenu == 1 || flag7)
                {
                    flag7 = false;
                    Netplay.Disconnect = true;
                    SoundEngine.PlaySound(11);
                    menuMode = 0;
                    netMode = 0;
                }
            }
            else if (menuMode == 200)
            {
                num57 = 3;
                array11[0] = Lang.menu[9].Value;
                if (WorldIO.customDataFail != null)
                {
                    array11[0] = WorldIO.customDataFail.modName + ": " + array11[0];
                }
                array[0] = true;
                num24 -= 30;
                array6[1] = 70;
                array6[2] = 50;
                array11[1] = Lang.menu[10].Value;
                array11[2] = Lang.menu[6].Value;
                if (WorldIO.customDataFail != null)
                {
                    array11[2] = Language.GetTextValue("tModLoader.OpenLogs");
                }
                if (selectedMenu == 1)
                {
                    if (FileUtilities.Exists(worldPathName + ".bak", ActiveWorldFileData.IsCloudSave))
                    {
                        FileUtilities.Move(worldPathName, worldPathName + ".bad", ActiveWorldFileData.IsCloudSave);
                        FileUtilities.Move(worldPathName + ".bak", worldPathName, ActiveWorldFileData.IsCloudSave);
                        WorldIO.LoadBackup(worldPathName, ActiveWorldFileData.IsCloudSave);
                        SoundEngine.PlaySound(10);
                        WorldGen.playWorld();
                        menuMode = 10;
                    }
                    else
                    {
                        SoundEngine.PlaySound(11);
                        menuMode = 0;
                        netMode = 0;
                    }
                }
                if (selectedMenu == 2 || flag7)
                {
                    flag7 = false;
                    SoundEngine.PlaySound(11);
                    if (WorldIO.customDataFail == null)
                    {
                        menuMode = 0;
                    }
                    else
                    {
                        Logging.tML.Error((object)Language.GetTextValue("tModLoader.WorldIODataException"), WorldIO.customDataFail.InnerException);
                        SoundEngine.PlaySound(in SoundID.MenuOpen);
                        Utils.OpenFolder(Logging.LogDir);
                    }
                    netMode = 0;
                }
            }
            else if (menuMode == 201)
            {
                num57 = 3;
                array11[0] = Lang.menu[9].Value;
                if (WorldIO.customDataFail != null)
                {
                    array11[0] = WorldIO.customDataFail.modName + ": " + array11[0];
                }
                array[0] = true;
                array[1] = true;
                num24 -= 30;
                array6[1] = -30;
                array6[2] = 50;
                array11[1] = Lang.menu[11].Value;
                array11[2] = Lang.menu[5].Value;
                if (WorldIO.customDataFail != null)
                {
                    array11[2] = Language.GetTextValue("tModLoader.OpenLogs");
                }
                if (selectedMenu == 2 || flag7)
                {
                    flag7 = false;
                    SoundEngine.PlaySound(11);
                    if (WorldIO.customDataFail == null)
                    {
                        menuMode = 0;
                    }
                    else
                    {
                        Logging.tML.Error((object)Language.GetTextValue("tModLoader.WorldIODataException"), WorldIO.customDataFail.InnerException);
                        SoundEngine.PlaySound(in SoundID.MenuOpen);
                        Utils.OpenFolder(Logging.LogDir);
                    }
                    menuMode = 0;
                    netMode = 0;
                }
            }
            else if (menuMode == 10)
            {
                num57 = 1;
                array11[0] = statusText;
                array[0] = true;
                num24 = 300;
                gameTips.Update();
                gameTips.Draw();
            }
            else if (menuMode == 100)
            {
                num57 = 1;
                array11[0] = statusText;
                array[0] = true;
                num24 = 300;
            }
            else if (menuMode == 0)
            {
                _blockFancyUIWhileLoading = false;
                _pendingCharacterSelect = null;
                DD2Event.Ongoing = false;
                eclipse = false;
                pumpkinMoon = false;
                snowMoon = false;
                ServerSideCharacter = false;
                menuMultiplayer = false;
                menuServer = false;
                netMode = 0;
                ClearVisualPostProcessEffects();
                int num13 = 0;
                num24 = 220;
                num57 = 7;
                num46 = 52;
                array11[num13] = Lang.menu[12].Value;
                if (selectedMenu == num13)
                {
                    SoundEngine.PlaySound(10);
                    ClearPendingPlayerSelectCallbacks();
                    menuMode = 1;
                }
                num13++;
                array11[num13] = Lang.menu[13].Value;
                if (selectedMenu == num13)
                {
                    SoundEngine.PlaySound(10);
                    menuMode = 12;
                }
                num13++;
                array11[num13] = Lang.menu[131].Value;
                if (selectedMenu == num13)
                {
                    SoundEngine.PlaySound(10);
                    menuMode = 888;
                    MenuUI.SetState(AchievementsMenu);
                }
                num13++;
                array11[num13] = Language.GetText("UI.Workshop").Value;
                if (selectedMenu == num13)
                {
                    SoundEngine.PlaySound(10);
                    menuMode = 888;
                    UIWorkshopHub uIWorkshopHub = new UIWorkshopHub(null);
                    uIWorkshopHub.EnterHub();
                    MenuUI.SetState(uIWorkshopHub);
                }
                num13++;
                Interface.AddMenuButtons(this, selectedMenu, array11, array9, ref num24, ref num46, ref num13, ref num57);
                array11[num13] = Lang.menu[14].Value;
                if (selectedMenu == num13)
                {
                    SoundEngine.PlaySound(10);
                    menuMode = 11;
                }
                num13++;
                array11[num13] = Language.GetText("UI.Credits").Value;
                if (selectedMenu == num13)
                {
                    SoundEngine.PlaySound(10);
                    menuMode = 3000;
                    SkyManager.Instance.Activate("CreditsRoll", default(Vector2));
                }
                num13++;
                array11[num13] = Lang.menu[15].Value;
                if (selectedMenu == num13)
                {
                    GameAskedToQuit = true;
                }
                num13++;
            }
            else if (menuMode == 1)
            {
                OpenCharacterSelectUI();
            }
            else if (menuMode == 2)
            {
                flag6 = true;
                if (selectedMenu == 0)
                {
                    menuMode = 17;
                    SoundEngine.PlaySound(10);
                    selColor = PendingPlayer.hairColor;
                }
                if (selectedMenu == 1)
                {
                    menuMode = 18;
                    SoundEngine.PlaySound(10);
                    selColor = PendingPlayer.eyeColor;
                }
                if (selectedMenu == 2)
                {
                    menuMode = 19;
                    SoundEngine.PlaySound(10);
                    selColor = PendingPlayer.skinColor;
                }
                if (selectedMenu == 3)
                {
                    menuMode = 20;
                    SoundEngine.PlaySound(10);
                }
                array11[0] = Lang.menu[18].Value;
                array11[1] = Lang.menu[19].Value;
                array11[2] = Lang.menu[20].Value;
                array11[3] = Lang.menu[21].Value;
                num24 = 220;
                for (int num16 = 0; num16 < 9; num16++)
                {
                    if (num16 < 6)
                    {
                        array9[num16] = 0.75f;
                    }
                    else
                    {
                        array9[num16] = 0.9f;
                    }
                }
                num46 = 38;
                array6[6] = 6;
                array6[7] = 12;
                array6[8] = 18;
                num79 = screenWidth / 2 - 16;
                num90 = 176;
                if (PendingPlayer.Male)
                {
                    array11[4] = Lang.menu[22].Value;
                }
                else
                {
                    array11[4] = Lang.menu[23].Value;
                }
                if (selectedMenu == 4)
                {
                    if (PendingPlayer.Male)
                    {
                        SoundEngine.PlaySound(20);
                        PendingPlayer.Male = false;
                    }
                    else
                    {
                        SoundEngine.PlaySound(1);
                        PendingPlayer.Male = true;
                    }
                }
                if (PendingPlayer.difficulty == 2)
                {
                    array11[5] = Lang.menu[24].Value;
                    array8[5] = PendingPlayer.difficulty;
                }
                else if (PendingPlayer.difficulty == 1)
                {
                    array11[5] = Lang.menu[25].Value;
                    array8[5] = PendingPlayer.difficulty;
                }
                else
                {
                    array11[5] = Lang.menu[26].Value;
                }
                if (selectedMenu == 5)
                {
                    SoundEngine.PlaySound(10);
                    menuMode = 222;
                }
                if (selectedMenu == 7)
                {
                    SoundEngine.PlaySound(12);
                    PendingPlayer.hair = rand.Next(51);
                    PendingPlayer.eyeColor = randColor();
                    while (((Color)(ref PendingPlayer.eyeColor)).R + ((Color)(ref PendingPlayer.eyeColor)).G + ((Color)(ref PendingPlayer.eyeColor)).B > 300)
                    {
                        PendingPlayer.eyeColor = randColor();
                    }
                    PendingPlayer.hairColor = randColor();
                    PendingPlayer.pantsColor = randColor();
                    PendingPlayer.shirtColor = randColor();
                    PendingPlayer.shoeColor = randColor();
                    PendingPlayer.skinColor = randColor();
                    float num17 = (float)rand.Next(60, 120) * 0.01f;
                    if (num17 > 1f)
                    {
                        num17 = 1f;
                    }
                    ((Color)(ref PendingPlayer.skinColor)).R = (byte)((float)rand.Next(240, 255) * num17);
                    ((Color)(ref PendingPlayer.skinColor)).G = (byte)((float)rand.Next(110, 140) * num17);
                    ((Color)(ref PendingPlayer.skinColor)).B = (byte)((float)rand.Next(75, 110) * num17);
                    PendingPlayer.underShirtColor = randColor();
                    int num18 = PendingPlayer.hair + 1;
                    if (num18 == 5 || num18 == 6 || num18 == 7 || num18 == 10 || num18 == 12 || num18 == 19 || num18 == 22 || num18 == 23 || num18 == 26 || num18 == 27 || num18 == 30 || num18 == 33)
                    {
                        PendingPlayer.Male = false;
                    }
                    else
                    {
                        PendingPlayer.Male = true;
                    }
                    PendingPlayer.skinVariant = rand.Next(PlayerVariantID.Count);
                }
                array11[7] = Lang.menu[27].Value;
                array11[6] = Lang.menu[28].Value;
                array11[8] = Lang.menu[5].Value;
                num57 = 9;
                if (selectedMenu == 8 || flag7)
                {
                    flag7 = false;
                    SoundEngine.PlaySound(11);
                    menuMode = 1;
                }
                else if (selectedMenu == 6)
                {
                    SoundEngine.PlaySound(10);
                    PendingPlayer.name = "";
                    menuMode = 3;
                    clrInput();
                }
            }
            else if (menuMode == 222)
            {
                if (focusMenu == 3)
                {
                    array11[0] = Lang.menu[29].Value;
                }
                else if (focusMenu == 2)
                {
                    array11[0] = Lang.menu[30].Value;
                }
                else if (focusMenu == 1)
                {
                    array11[0] = Lang.menu[31].Value;
                }
                else
                {
                    array11[0] = Lang.menu[32].Value;
                }
                num46 = 50;
                array6[1] = 25;
                array6[2] = 25;
                array6[3] = 25;
                array[0] = true;
                array11[1] = Lang.menu[26].Value;
                array11[2] = Lang.menu[25].Value;
                array8[2] = 1;
                array11[3] = Lang.menu[24].Value;
                array8[3] = 2;
                num57 = 4;
                if (selectedMenu == 1)
                {
                    PendingPlayer.difficulty = 0;
                    menuMode = 2;
                }
                else if (selectedMenu == 2)
                {
                    menuMode = 2;
                    PendingPlayer.difficulty = 1;
                }
                else if (selectedMenu == 3)
                {
                    PendingPlayer.difficulty = 2;
                    menuMode = 2;
                }
            }
            else if (menuMode == 20)
            {
                flag6 = true;
                if (selectedMenu == 0)
                {
                    menuMode = 21;
                    SoundEngine.PlaySound(10);
                    selColor = PendingPlayer.shirtColor;
                }
                if (selectedMenu == 1)
                {
                    menuMode = 22;
                    SoundEngine.PlaySound(10);
                    selColor = PendingPlayer.underShirtColor;
                }
                if (selectedMenu == 2)
                {
                    menuMode = 23;
                    SoundEngine.PlaySound(10);
                    selColor = PendingPlayer.pantsColor;
                }
                if (selectedMenu == 3)
                {
                    selColor = PendingPlayer.shoeColor;
                    menuMode = 24;
                    SoundEngine.PlaySound(10);
                }
                if (selectedMenu == 5 || flag7)
                {
                    flag7 = false;
                    SoundEngine.PlaySound(11);
                    menuMode = 2;
                }
                if (selectedMenu == 4)
                {
                    SoundEngine.PlaySound(12);
                    CycleClothingStyle(PendingPlayer);
                }
                num79 = screenWidth / 2 - 16;
                num90 = 210;
                num24 = 260;
                num46 = 50;
                num57 = 6;
                array11[0] = Lang.menu[33].Value;
                array11[1] = Lang.menu[34].Value;
                array11[2] = Lang.menu[35].Value;
                array11[3] = Lang.menu[36].Value;
                array11[4] = Lang.menu[127].Value;
                array11[5] = Lang.menu[5].Value;
                array6[5] = 20;
            }
            else if (menuMode == 17)
            {
                flag6 = true;
                num79 = screenWidth / 2 - 16;
                num90 = 210;
                flag = true;
                num101 = 390;
                num24 = 260;
                num46 = 60;
                PendingPlayer.hairColor = selColor;
                num57 = 3;
                array11[0] = Lang.menu[37].Value + " " + (PendingPlayer.hair + 1);
                array11[1] = Lang.menu[38].Value;
                array[1] = true;
                array6[2] = 150;
                array6[1] = 10;
                array11[2] = Lang.menu[5].Value;
                int num19 = 51;
                if (focusMenu == 0)
                {
                    UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 9;
                }
                if (selectedMenu == 0)
                {
                    SoundEngine.PlaySound(12);
                    PendingPlayer.hair++;
                    if (PendingPlayer.hair >= num19)
                    {
                        PendingPlayer.hair = 0;
                    }
                }
                else if (selectedMenu2 == 0)
                {
                    SoundEngine.PlaySound(12);
                    PendingPlayer.hair--;
                    if (PendingPlayer.hair < 0)
                    {
                        PendingPlayer.hair = num19 - 1;
                    }
                }
                if (selectedMenu == 2 || flag7)
                {
                    flag7 = false;
                    menuMode = 2;
                    SoundEngine.PlaySound(11);
                }
            }
            else if (menuMode == 18)
            {
                flag6 = true;
                num79 = screenWidth / 2 - 16;
                num90 = 210;
                flag = true;
                num101 = 370;
                num24 = 240;
                num46 = 60;
                PendingPlayer.eyeColor = selColor;
                num57 = 3;
                array11[0] = "";
                array11[1] = Lang.menu[39].Value;
                array[1] = true;
                array6[2] = 170;
                array6[1] = 10;
                array11[2] = Lang.menu[5].Value;
                if (selectedMenu == 2 || flag7)
                {
                    flag7 = false;
                    menuMode = 2;
                    SoundEngine.PlaySound(11);
                }
            }
            else if (menuMode == 19)
            {
                flag6 = true;
                num79 = screenWidth / 2 - 16;
                num90 = 210;
                flag = true;
                num101 = 370;
                num24 = 240;
                num46 = 60;
                PendingPlayer.skinColor = selColor;
                num57 = 3;
                array11[0] = "";
                array11[1] = Lang.menu[40].Value;
                array[1] = true;
                array6[2] = 170;
                array6[1] = 10;
                array11[2] = Lang.menu[5].Value;
                if (selectedMenu == 2 || flag7)
                {
                    flag7 = false;
                    menuMode = 2;
                    SoundEngine.PlaySound(11);
                }
            }
            else if (menuMode == 21)
            {
                flag6 = true;
                num79 = screenWidth / 2 - 16;
                num90 = 210;
                flag = true;
                num101 = 370;
                num24 = 240;
                num46 = 60;
                PendingPlayer.shirtColor = selColor;
                num57 = 3;
                array11[0] = "";
                array11[1] = Lang.menu[41].Value;
                array[1] = true;
                array6[2] = 170;
                array6[1] = 10;
                array11[2] = Lang.menu[5].Value;
                if (selectedMenu == 2 || flag7)
                {
                    flag7 = false;
                    menuMode = 20;
                    SoundEngine.PlaySound(11);
                }
            }
            else if (menuMode == 22)
            {
                flag6 = true;
                num79 = screenWidth / 2 - 16;
                num90 = 210;
                flag = true;
                num101 = 370;
                num24 = 240;
                num46 = 60;
                PendingPlayer.underShirtColor = selColor;
                num57 = 3;
                array11[0] = "";
                array11[1] = Lang.menu[42].Value;
                array[1] = true;
                array6[2] = 170;
                array6[1] = 10;
                array11[2] = Lang.menu[5].Value;
                if (selectedMenu == 2 || flag7)
                {
                    flag7 = false;
                    menuMode = 20;
                    SoundEngine.PlaySound(11);
                }
            }
            else if (menuMode == 23)
            {
                flag6 = true;
                num79 = screenWidth / 2 - 16;
                num90 = 210;
                flag = true;
                num101 = 370;
                num24 = 240;
                num46 = 60;
                PendingPlayer.pantsColor = selColor;
                num57 = 3;
                array11[0] = "";
                array11[1] = Lang.menu[43].Value;
                array[1] = true;
                array6[2] = 170;
                array6[1] = 10;
                array11[2] = Lang.menu[5].Value;
                if (selectedMenu == 2 || flag7)
                {
                    flag7 = false;
                    menuMode = 20;
                    SoundEngine.PlaySound(11);
                }
            }
            else if (menuMode == 24)
            {
                flag6 = true;
                num79 = screenWidth / 2 - 16;
                num90 = 210;
                flag = true;
                num101 = 370;
                num24 = 240;
                num46 = 60;
                PendingPlayer.shoeColor = selColor;
                num57 = 3;
                array11[0] = "";
                array11[1] = Lang.menu[44].Value;
                array[1] = true;
                array6[2] = 170;
                array6[1] = 10;
                array11[2] = Lang.menu[5].Value;
                if (selectedMenu == 2 || flag7)
                {
                    flag7 = false;
                    menuMode = 20;
                    SoundEngine.PlaySound(11);
                }
            }
            else if (menuMode == 3)
            {
                UIVirtualKeyboard uIVirtualKeyboard3 = new UIVirtualKeyboard(Lang.menu[45].Value, "", OnCharacterNamed, CreateGoToMenuEvent(2));
                uIVirtualKeyboard3.SetMaxInputLength(20);
                menuMode = 888;
                MenuUI.SetState(uIVirtualKeyboard3);
            }
            else if (menuMode != 4)
            {
                if (menuMode == 5)
                {
                    array11[0] = Lang.menu[46].Value + " " + PlayerList[selectedPlayer].Player.name + "?";
                    array[0] = true;
                    array11[1] = Lang.menu[104].Value;
                    array11[2] = Lang.menu[105].Value;
                    num57 = 3;
                    if (selectedMenu == 1)
                    {
                        ErasePlayer(selectedPlayer);
                        SoundEngine.PlaySound(10);
                        menuMode = 1;
                    }
                    else if (selectedMenu == 2 || flag7)
                    {
                        flag7 = false;
                        SoundEngine.PlaySound(11);
                        menuMode = 1;
                    }
                }
                else if (menuMode == 6)
                {
                    menuMode = 888;
                    MenuUI.SetState(_worldSelectMenu);
                }
                else if (menuMode == -7)
                {
                    num24 = 200;
                    num46 = 60;
                    array6[2] = 30;
                    array6[3] = 30;
                    array6[4] = 30;
                    array8[3] = 1;
                    array8[4] = 2;
                    array6[5] = 70;
                    if (focusMenu == 2)
                    {
                        array11[1] = Language.GetTextValue("UI.WorldDescriptionNormal");
                    }
                    else if (focusMenu == 3)
                    {
                        array11[1] = Language.GetTextValue("UI.WorldDescriptionExpert");
                    }
                    else if (focusMenu == 4)
                    {
                        array11[1] = Language.GetTextValue("UI.WorldDescriptionMaster");
                    }
                    array11[0] = Lang.menu[32].Value;
                    array[0] = true;
                    array[1] = true;
                    array11[2] = Language.GetTextValue("UI.Normal");
                    array11[3] = Language.GetTextValue("UI.Expert");
                    array11[4] = Language.GetTextValue("UI.Master");
                    array11[5] = Language.GetTextValue("UI.Back");
                    num57 = 6;
                    if (selectedMenu == 2)
                    {
                        GameMode = 0;
                        SoundEngine.PlaySound(10);
                        menuMode = 7;
                        if (SettingsUnlock_WorldEvil)
{
                            menuMode = -71;
                        }
                    }
                    else if (selectedMenu == 3)
                    {
                        GameMode = 1;
                        SoundEngine.PlaySound(10);
                        menuMode = 7;
                        if (SettingsUnlock_WorldEvil)
{
                            menuMode = -71;
                        }
                    }
                    else if (selectedMenu == 4)
                    {
                        GameMode = 2;
                        SoundEngine.PlaySound(10);
                        menuMode = 7;
                        if (SettingsUnlock_WorldEvil)
{
                            menuMode = -71;
                        }
                    }
                    else if (selectedMenu == 5 || flag7)
                    {
                        flag7 = false;
                        SoundEngine.PlaySound(11);
                        menuMode = 16;
                    }
                    clrInput();
                }
                else if (menuMode == -71)
                {
                    num24 = 200;
                    num46 = 60;
                    array6[1] = 30;
                    array6[2] = 30;
                    array6[3] = 30;
                    array6[4] = 70;
                    num57 = 5;
                    int num20 = 0;
                    array11[num20] = Lang.misc[100].Value;
                    array[num20] = true;
                    num20++;
                    array11[num20] = Lang.misc[101].Value;
                    if (selectedMenu == num20)
                    {
                        WorldGen.WorldGenParam_Evil = 0;
                        SoundEngine.PlaySound(10);
                        menuMode = 7;
                    }
                    num20++;
                    array11[num20] = Lang.misc[102].Value;
                    if (selectedMenu == num20)
                    {
                        WorldGen.WorldGenParam_Evil = 1;
                        SoundEngine.PlaySound(10);
                        menuMode = 7;
                    }
                    num20++;
                    array11[num20] = Lang.misc[103].Value;
                    if (selectedMenu == num20)
                    {
                        WorldGen.WorldGenParam_Evil = -1;
                        SoundEngine.PlaySound(10);
                        menuMode = 7;
                    }
                    num20++;
                    array11[num20] = Language.GetTextValue("UI.Back");
                    if (selectedMenu == num20 || flag7)
                    {
                        flag7 = false;
                        SoundEngine.PlaySound(11);
                        menuMode = -7;
                    }
                    num20++;
                    clrInput();
                }
                else if (menuMode == 7)
                {
                    menuMode = 888;
                    MenuUI.SetState(new UIVirtualKeyboard(Lang.menu[48].Value, "", OnWorldNamed, CreateGoToMenuEvent(-7)));
                }
                else if (menuMode == 5000)
                {
                    menuMode = 888;
                    MenuUI.SetState(new UIVirtualKeyboard(Language.GetTextValue("UI.EnterSeed"), "", OnSeedSelected, CreateGoToMenuEvent(7), 0, allowEmpty: true));
                }
                else if (menuMode == 8)
                {
                    num24 = 180;
                    num46 = 40;
                    num57 = 8;
                    array6[7] += 30;
                    for (int num21 = 0; num21 < num57; num21++)
                    {
                        array9[num21] = 0.8f;
                    }
                    array11[7] = Lang.menu[5].Value;
                    for (int num22 = 0; num22 < 7; num22++)
                    {
                        if (num22 < WorldList.Count)
{
                            array11[num22] = WorldList[num22 + menuSkip].Name;
                            if (WorldList[num22 + menuSkip].GameMode == 1)
{
                                array8[num22] = 1;
                            }
                            else if (WorldList[num22 + menuSkip].GameMode == 2)
{
                                array8[num22] = 2;
                            }
                        }
                        else
{
                            array11[num22] = null;
                        }
                    }
                    if (WorldList.Count > 7 + menuSkip)
                    {
                        array11[6] = Language.GetTextValue("UI.More");
                        array11[6] = "";
                        array9[6] = 0.6f;
                        array6[6] += 8;
                        menuWide[6] = true;
                    }
                    if (menuSkip > 0)
                    {
                        array11[0] = "";
                        array9[0] = 0.6f;
                        array6[0] += 8;
                        menuWide[0] = true;
                    }
                    if (selectedMenu == 0 && menuSkip > 0)
                    {
                        SoundEngine.PlaySound(12);
                        menuSkip -= 5;
                        if (menuSkip < 0)
{
                            menuSkip = 0;
                        }
                    }
                    else if (selectedMenu == 6 && menuSkip < WorldList.Count - 7)
                    {
                        SoundEngine.PlaySound(12);
                        menuSkip += 5;
                        if (menuSkip >= PlayerList.Count - 7)
{
                            menuSkip = WorldList.Count - 7;
                        }
                    }
                    else if (selectedMenu == 7 || flag7)
                    {
                        flag7 = false;
                        SoundEngine.PlaySound(11);
                        menuMode = 6;
                    }
                    else if (selectedMenu >= 0)
                    {
                        selectedWorld = selectedMenu + menuSkip;
                        SoundEngine.PlaySound(10);
                        menuMode = 9;
                    }
                }
                else if (menuMode == 9)
                {
                    array11[0] = Lang.menu[46].Value + " " + WorldList[selectedWorld].Name + "?";
                    array[0] = true;
                    array11[1] = Lang.menu[104].Value;
                    array11[2] = Lang.menu[105].Value;
                    num57 = 3;
                    if (selectedMenu == 1)
                    {
                        EraseWorld(selectedWorld);
                        SoundEngine.PlaySound(10);
                        menuMode = 6;
                    }
                    else if (selectedMenu == 2 || flag7)
                    {
                        SoundEngine.PlaySound(11);
                        menuMode = 6;
                    }
                }
                else if (menuMode == 3000)
                {
                    num57 = 1;
                    num24 = 500;
                    array9[0] = 0.9f;
                    array11[0] = Lang.menu[5].Value;
                    if (selectedMenu == 0 || flag7)
                    {
                        flag7 = false;
                        SoundEngine.PlaySound(11);
                        menuMode = 0;
                    }
                }
                else if (menuMode == 11)
                {
                    num24 = 210;
                    num46 = 37;
                    num57 = 8;
                    num57++;
                    array6[num57 - 1] = 8;
                    for (int num23 = 0; num23 < num57; num23++)
                    {
                        array9[num23] = 0.75f;
                    }
                    int num25 = 0;
                    array11[num25] = Lang.menu[114].Value;
                    if (selectedMenu == num25)
                    {
                        SoundEngine.PlaySound(10);
                        menuMode = 112;
                    }
                    num25++;
                    array11[num25] = Lang.menu[210].Value;
                    if (selectedMenu == num25)
                    {
                        SoundEngine.PlaySound(10);
                        menuMode = 1112;
                    }
                    num25++;
                    array11[num25] = Lang.menu[63].Value;
                    if (selectedMenu == num25)
                    {
                        SoundEngine.PlaySound(10);
                        menuMode = 1111;
                    }
                    num25++;
                    array11[num25] = Lang.menu[65].Value;
                    if (selectedMenu == num25)
                    {
                        SoundEngine.PlaySound(11);
                        menuMode = 26;
                    }
                    num25++;
                    array11[num25] = Lang.menu[218].Value;
                    if (selectedMenu == num25)
                    {
                        SoundEngine.PlaySound(10);
                        menuMode = 1125;
                    }
                    num25++;
                    array11[num25] = Lang.menu[219].Value;
                    if (selectedMenu == num25)
                    {
                        SoundEngine.PlaySound(10);
                        menuMode = 1127;
                    }
                    num25++;
                    array11[num25] = Lang.menu[103].Value;
                    if (selectedMenu == num25)
                    {
                        SoundEngine.PlaySound(10);
                        menuMode = 1213;
                    }
                    num25++;
                    array11[num25] = Language.GetTextValue("tModLoader.tModLoaderSettings");
                    if (selectedMenu == num25)
                    {
                        SoundEngine.PlaySound(in SoundID.MenuOpen);
                        menuMode = 10017;
                    }
                    num25++;
                    array11[num25] = Lang.menu[5].Value;
                    if (selectedMenu == num25 || flag7)
                    {
                        flag7 = false;
                        SoundEngine.PlaySound(11);
                        menuMode = 0;
                        SaveSettings();
                    }
                }
                else if (menuMode == 112)
                {
                    num24 = 250;
                    num46 = 52;
                    num57 = 5;
                    array6[num57 - 1] = 18;
                    for (int num26 = 0; num26 < num57; num26++)
                    {
                        array9[num26] = 0.78f;
                    }
                    int num27 = 0;
                    if (autoSave)
                    {
                        array11[num27] = Lang.menu[67].Value;
                    }
                    else
                    {
                        array11[num27] = Lang.menu[68].Value;
                    }
                    if (selectedMenu == num27)
                    {
                        SoundEngine.PlaySound(12);
                        if (autoSave)
{
                            autoSave = false;
                        }
                        else
{
                            autoSave = true;
                        }
                    }
                    num27++;
                    if (autoPause)
                    {
                        array11[num27] = Lang.menu[69].Value;
                    }
                    else
                    {
                        array11[num27] = Lang.menu[70].Value;
                    }
                    if (selectedMenu == num27)
                    {
                        SoundEngine.PlaySound(12);
                        if (autoPause)
{
                            autoPause = false;
                        }
                        else
{
                            autoPause = true;
                        }
                    }
                    num27++;
                    if (mapEnabled)
                    {
                        array11[num27] = Lang.menu[112].Value;
                    }
                    else
                    {
                        array11[num27] = Lang.menu[113].Value;
                    }
                    if (selectedMenu == num27)
                    {
                        SoundEngine.PlaySound(12);
                        if (mapEnabled)
{
                            mapEnabled = false;
                        }
                        else
{
                            mapEnabled = true;
                        }
                    }
                    num27++;
                    array11[num27] = (HidePassword ? Lang.menu[212].Value : Lang.menu[211].Value);
                    if (selectedMenu == num27)
                    {
                        SoundEngine.PlaySound(12);
                        HidePassword = !HidePassword;
                    }
                    num27++;
                    array11[num27] = Lang.menu[5].Value;
                    if (selectedMenu == num27 || flag7)
                    {
                        flag7 = false;
                        menuMode = 11;
                        SoundEngine.PlaySound(11);
                    }
                }
                else if (menuMode == 1112)
                {
                    num24 = 210;
                    num46 = 32;
                    num57 = 10;
                    num57++;
                    array6[num57 - 1] = 18;
                    for (int num28 = 0; num28 < num57; num28++)
                    {
                        array9[num28] = 0.7f;
                    }
                    int num29 = 0;
                    if (showItemText)
                    {
                        array11[num29] = Lang.menu[71].Value;
                    }
                    else
                    {
                        array11[num29] = Lang.menu[72].Value;
                    }
                    if (selectedMenu == num29)
                    {
                        SoundEngine.PlaySound(12);
                        if (showItemText)
{
                            showItemText = false;
                        }
                        else
{
                            showItemText = true;
                        }
                    }
                    num29++;
                    array11[num29] = Lang.menu[123].Value + " " + Lang.menu[124 + invasionProgressMode].Value;
                    if (selectedMenu == num29)
                    {
                        SoundEngine.PlaySound(12);
                        invasionProgressMode++;
                        if (invasionProgressMode >= 3)
{
                            invasionProgressMode = 0;
                        }
                    }
                    num29++;
                    array11[num29] = (placementPreview ? Lang.menu[128].Value : Lang.menu[129].Value);
                    if (selectedMenu == num29)
                    {
                        SoundEngine.PlaySound(12);
                        placementPreview = !placementPreview;
                    }
                    num29++;
                    array11[num29] = (ItemSlot.Options.HighlightNewItems ? Lang.inter[117].Value : Lang.inter[116].Value);
                    if (selectedMenu == num29)
                    {
                        SoundEngine.PlaySound(12);
                        ItemSlot.Options.HighlightNewItems = !ItemSlot.Options.HighlightNewItems;
                    }
                    num29++;
                    array11[num29] = (MouseShowBuildingGrid ? Lang.menu[229].Value : Lang.menu[230].Value);
                    if (selectedMenu == num29)
                    {
                        SoundEngine.PlaySound(12);
                        MouseShowBuildingGrid = !MouseShowBuildingGrid;
                    }
                    num29++;
                    array11[num29] = (GamepadDisableInstructionsDisplay ? Lang.menu[241].Value : Lang.menu[242].Value);
                    if (selectedMenu == num29)
                    {
                        SoundEngine.PlaySound(12);
                        GamepadDisableInstructionsDisplay = !GamepadDisableInstructionsDisplay;
                    }
                    num29++;
                    string textValue = Language.GetTextValue("UI.MinimapFrame_" + MinimapFrameManagerInstance.ActiveSelectionKeyName);
                    array11[num29] = Language.GetTextValue("UI.SelectMapBorder", textValue);
                    if (selectedMenu == num29)
                    {
                        MinimapFrameManagerInstance.CycleSelection();
                    }
                    num29++;
                    string textValue2 = ResourceSetsManager.ActiveSet.DisplayedName;
                    array11[num29] = Language.GetTextValue("UI.SelectHealthStyle", textValue2);
                    if (selectedMenu == num29)
                    {
                        ResourceSetsManager.CycleResourceSet();
                    }
                    num29++;
                    array11[num29] = Language.GetTextValue(BigProgressBarSystem.ShowText ? "UI.ShowBossLifeTextOn" : "UI.ShowBossLifeTextOff");
                    if (selectedMenu == num29)
                    {
                        BigProgressBarSystem.ToggleShowText();
                    }
                    num29++;
                    array11[num29] = BossBarLoader.InsertMenu(out var onClick);
                    if (selectedMenu == num29)
                    {
                        onClick();
                    }
                    num29++;
                    array11[num29] = Lang.menu[5].Value;
                    if (selectedMenu == num29 || flag7)
                    {
                        flag7 = false;
                        menuMode = 11;
                        SoundEngine.PlaySound(11);
                    }
                }
                else if (menuMode == 1111)
                {
                    bgScroll = (int)Math.Round((1f - caveParallax) * 500f);
                    int num30 = 0;
                    array11[num30] = Lang.menu[51].Value;
                    if (selectedMenu == num30)
                    {
                        SoundEngine.PlaySound(10);
                        menuMode = 111;
                    }
                    num30++;
                    array11[num30] = Lang.menu[52].Value;
                    if (selectedMenu == num30)
                    {
                        SoundEngine.PlaySound(11);
                        menuMode = 28;
                    }
                    num30++;
                    array11[num30] = Lang.menu[(int)(247 + FrameSkipMode)].Value;
                    if (selectedMenu == num30)
                    {
                        SoundEngine.PlaySound(12);
                        CycleFrameSkipMode();
                    }
                    num30++;
                    array11[num30] = Language.GetTextValue("UI.LightMode_" + Lighting.Mode);
                    if (selectedMenu == num30)
                    {
                        SoundEngine.PlaySound(12);
                        Lighting.NextLightMode();
                    }
                    num30++;
                    switch (qaStyle)
                    {
                    case 0:
                        array11[num30] = Lang.menu[59].Value;
                        break;
                    case 1:
                        array11[num30] = Lang.menu[60].Value;
                        break;
                    case 2:
                        array11[num30] = Lang.menu[61].Value;
                        break;
                    default:
                        array11[num30] = Lang.menu[62].Value;
                        break;
                    }
                    if (selectedMenu == num30)
                    {
                        SoundEngine.PlaySound(12);
                        if (++qaStyle > 3)
{
                            qaStyle = 0;
                        }
                    }
                    num30++;
                    array11[num30] = (BackgroundEnabled ? Lang.menu[100].Value : Lang.menu[101].Value);
                    if (selectedMenu == num30)
                    {
                        SoundEngine.PlaySound(12);
                        BackgroundEnabled = !BackgroundEnabled;
                    }
                    num30++;
                    array11[num30] = (ChildSafety.Disabled ? Lang.menu[132].Value : Lang.menu[133].Value);
                    if (selectedMenu == num30)
                    {
                        SoundEngine.PlaySound(12);
                        ChildSafety.Disabled = !ChildSafety.Disabled;
                    }
                    num30++;
                    array11[num30] = (SettingsEnabled_MinersWobble ? Lang.menu[250].Value : Lang.menu[251].Value);
                    if (selectedMenu == num30)
                    {
                        SoundEngine.PlaySound(12);
                        SettingsEnabled_MinersWobble = !SettingsEnabled_MinersWobble;
                    }
                    num30++;
                    array11[num30] = (SettingsEnabled_TilesSwayInWind ? Language.GetTextValue("UI.TilesSwayInWindOn") : Language.GetTextValue("UI.TilesSwayInWindOff"));
                    if (selectedMenu == num30)
                    {
                        SoundEngine.PlaySound(12);
                        SettingsEnabled_TilesSwayInWind = !SettingsEnabled_TilesSwayInWind;
                    }
                    num30++;
                    array11[num30] = Language.GetTextValue("UI.Effects");
                    if (selectedMenu == num30)
                    {
                        SoundEngine.PlaySound(11);
                        menuMode = 2008;
                    }
                    int num31 = num30;
                    int num32 = num31;
                    array11[num32] = Lang.menu[5].Value;
                    array6[num32] = 8;
                    if (selectedMenu == num32 || flag7)
                    {
                        flag7 = false;
                        SoundEngine.PlaySound(11);
                        SaveSettings();
                        menuMode = 11;
                    }
                    num24 = 186;
                    num46 = 30;
                    num57 = num32 + 1;
                    for (int num33 = 0; num33 < num31; num33++)
                    {
                        array9[num33] = 0.6f;
                    }
                }
                else if (menuMode == 2008)
                {
                    num24 = 240;
                    num46 = 60;
                    num57 = 6;
                    array11[0] = "";
                    array11[1] = Language.GetTextValue("UI.Effects");
                    array[1] = true;
                    array6[1] = 10;
                    array11[2] = Language.GetTextValue("GameUI.StormEffects", UseStormEffects ? Language.GetTextValue("GameUI.Enabled") : Language.GetTextValue("GameUI.Disabled"));
                    array9[2] = 0.8f;
                    array11[3] = Language.GetTextValue("GameUI.HeatDistortion", UseHeatDistortion ? Language.GetTextValue("GameUI.Enabled") : Language.GetTextValue("GameUI.Disabled"));
                    array9[3] = 0.8f;
                    array11[4] = Language.GetTextValue("GameUI.WaveQuality", WaveQuality switch
                    {
                        1 => Language.GetTextValue("GameUI.QualityLow"),
                        2 => Language.GetTextValue("GameUI.QualityMedium"),
                        3 => Language.GetTextValue("GameUI.QualityHigh"),
                        _ => Language.GetTextValue("GameUI.QualityOff"),
                    });
                    array9[4] = 0.8f;
                    array11[5] = Lang.menu[5].Value;
                    if (selectedMenu == 2)
                    {
                        UseStormEffects = !UseStormEffects;
                    }
                    if (selectedMenu == 3)
                    {
                        UseHeatDistortion = !UseHeatDistortion;
                    }
                    if (selectedMenu == 4)
                    {
                        WaveQuality = (WaveQuality + 1) % 4;
                    }
                    if (selectedMenu == 5 || flag7)
                    {
                        flag7 = false;
                        menuMode = 1111;
                        SoundEngine.PlaySound(11);
                    }
                }
                else if (menuMode == 111)
                {
                    for (int num34 = 0; num34 < 9; num34++)
                    {
                        array9[num34] = 0.85f;
                    }
                    num24 = 210;
                    num46 = 55;
                    int num36 = 0;
                    array11[num36] = Lang.menu[73].Value + ": " + PendingResolutionWidth + "x" + PendingResolutionHeight;
                    if (selectedMenu == num36 || selectedMenu2 == num36)
                    {
                        SoundEngine.PlaySound(12);
                        int num37 = 0;
                        for (int num38 = 0; num38 < numDisplayModes; num38++)
{
                            if (displayWidth[num38] == PendingResolutionWidth && BorderedHeight(displayHeight[num38], graphics.IsFullScreen) == PendingResolutionHeight)
{
                                num37 = num38;
                                break;
                            }
                        }
                        num37 = Utils.Repeat(num37 + ((selectedMenu == num36) ? 1 : (-1)), numDisplayModes);
                        PendingResolutionWidth = displayWidth[num37];
                        PendingResolutionHeight = BorderedHeight(displayHeight[num37], graphics.IsFullScreen);
                    }
                    num36++;
                    if (IsBorderlessDisplayAvailable())
                    {
                        array11[num36] = Lang.menu[PendingBorderlessState ? 245 : 246].Value;
                        if (selectedMenu == num36)
{
                            SoundEngine.PlaySound(12);
                            PendingBorderlessState = !PendingBorderlessState;
                        }
                        num36++;
                    }
                    array11[num36] = (graphics.IsFullScreen ? Lang.menu[49].Value : Lang.menu[50].Value);
                    if (selectedMenu == num36)
                    {
                        ToggleFullScreen();
                    }
                    num36++;
                    array6[num36] = 100;
                    array11[num36] = Lang.menu[134].Value;
                    if (selectedMenu == num36)
                    {
                        if (graphics.IsFullScreen || PendingBorderlessState != screenBorderless || PendingResolutionWidth != screenWidth || PendingResolutionHeight != screenHeight)
{
                            screenBorderless = PendingBorderlessState;
                            screenBorderlessPendingResizes = (screenBorderless ? 6 : 0);
                            SetResolution(PendingResolutionWidth, PendingResolutionHeight);
                        }
                        SoundEngine.PlaySound(11);
                        menuMode = 1111;
                    }
                    num36++;
                    array11[num36] = Lang.menu[5].Value;
                    array6[num36] = 100;
                    if (selectedMenu == num36 || flag7)
                    {
                        flag7 = false;
                        PendingResolutionWidth = graphics.PreferredBackBufferWidth;
                        PendingResolutionHeight = graphics.PreferredBackBufferHeight;
                        PendingBorderlessState = screenBorderless;
                        menuMode = 1111;
                        SoundEngine.PlaySound(11);
                    }
                    num36++;
                    num57 = num36;
                }
                else if (menuMode == 1125)
                {
                    num24 = 232;
                    num46 = 38;
                    num57 = 7;
                    array6[num57 - 1] = 18;
                    for (int num39 = 0; num39 < num57; num39++)
                    {
                        array9[num39] = 0.73f;
                    }
                    int num40 = 0;
                    array11[num40] = Lang.menu[64].Value;
                    if (selectedMenu == num40)
                    {
                        SoundEngine.PlaySound(10);
                        selColor = mouseColor;
                        mouseColorSlider.SetHSL(mouseColor);
                        menuMode = 25;
                    }
                    num40++;
                    array11[num40] = Lang.menu[217].Value;
                    if (selectedMenu == num40)
                    {
                        SoundEngine.PlaySound(10);
                        selColor = MouseBorderColor;
                        mouseBorderColorSlider.SetHSL(mouseColor);
                        menuMode = 252;
                    }
                    num40++;
                    array11[num40] = (cSmartCursorModeIsToggleAndNotHold ? Lang.menu[121].Value : Lang.menu[122].Value);
                    if (selectedMenu == num40)
                    {
                        SoundEngine.PlaySound(12);
                        cSmartCursorModeIsToggleAndNotHold = !cSmartCursorModeIsToggleAndNotHold;
                    }
                    num40++;
                    array11[num40] = (Player.SmartCursorSettings.SmartAxeAfterPickaxe ? Lang.menu[214].Value : Lang.menu[213].Value);
                    if (selectedMenu == num40)
                    {
                        SoundEngine.PlaySound(12);
                        Player.SmartCursorSettings.SmartAxeAfterPickaxe = !Player.SmartCursorSettings.SmartAxeAfterPickaxe;
                    }
                    num40++;
                    array11[num40] = (Player.SmartCursorSettings.SmartBlocksEnabled ? Lang.menu[215].Value : Lang.menu[216].Value);
                    if (selectedMenu == num40)
                    {
                        SoundEngine.PlaySound(12);
                        Player.SmartCursorSettings.SmartBlocksEnabled = !Player.SmartCursorSettings.SmartBlocksEnabled;
                    }
                    num40++;
                    switch (LockOnHelper.UseMode)
                    {
                    case LockOnHelper.LockOnMode.FocusTarget:
                        array11[num40] = Lang.menu[232].Value;
                        break;
                    case LockOnHelper.LockOnMode.TargetClosest:
                        array11[num40] = Lang.menu[233].Value;
                        break;
                    case LockOnHelper.LockOnMode.ThreeDS:
                        array11[num40] = Lang.menu[234].Value;
                        break;
                    }
                    if (selectedMenu == num40)
                    {
                        SoundEngine.PlaySound(12);
                        LockOnHelper.CycleUseModes();
                    }
                    num40++;
                    array11[num40] = Lang.menu[5].Value;
                    if (selectedMenu == num40 || flag7)
                    {
                        flag7 = false;
                        menuMode = 11;
                        SoundEngine.PlaySound(11);
                    }
                }
                else if (menuMode == 25)
                {
                    flag = true;
                    num101 = 320;
                    num24 = 200;
                    num46 = 10;
                    mouseColor = selColor;
                    mouseColorSlider.SetHSL(mouseColor);
                    num57 = 3;
                    array11[0] = "";
                    array11[1] = Lang.menu[64].Value;
                    array[1] = true;
                    array6[2] = 250;
                    array6[1] = 10;
                    array11[2] = Lang.menu[5].Value;
                    if (selectedMenu == 2 || flag7)
                    {
                        flag7 = false;
                        menuMode = 1125;
                        SoundEngine.PlaySound(11);
                    }
                }
                else if (menuMode == 252)
                {
                    flag = true;
                    num101 = 320;
                    num24 = 200;
                    num46 = 10;
                    MouseBorderColor = selColor;
                    mouseBorderColorSlider.SetHSL(mouseColor);
                    num57 = 3;
                    array11[0] = "";
                    array11[1] = Lang.menu[217].Value;
                    array[1] = true;
                    array6[2] = 250;
                    array6[1] = 10;
                    array11[2] = Lang.menu[5].Value;
                    if (selectedMenu == 2 || flag7)
                    {
                        flag7 = false;
                        menuMode = 1125;
                        SoundEngine.PlaySound(11);
                    }
                }
                else if (menuMode == 26)
                {
                    flag4 = true;
                    num24 = 200;
                    num46 = 10;
                    num57 = 3;
                    array11[0] = "";
                    array11[1] = Lang.menu[65].Value;
                    array[1] = true;
                    array6[2] = 250;
                    array6[1] = 10;
                    array11[2] = Lang.menu[5].Value;
                    if (selectedMenu == 2 || flag7)
                    {
                        flag7 = false;
                        menuMode = 11;
                        SoundEngine.PlaySound(11);
                    }
                }
                else if (menuMode == 28)
                {
                    caveParallax = 1f - (float)bgScroll / 500f;
                    flag5 = true;
                    num24 = 240;
                    num46 = 60;
                    num57 = 3;
                    array11[0] = "";
                    array11[1] = Lang.menu[52].Value;
                    array[1] = true;
                    array6[2] = 170;
                    array6[1] = 10;
                    array11[2] = Lang.menu[5].Value;
                    if (selectedMenu == 2 || flag7)
                    {
                        flag7 = false;
                        menuMode = 1111;
                        SoundEngine.PlaySound(11);
                    }
                }
                else if (menuMode == 272727)
                {
                    num24 = 200;
                    num46 = 30;
                    num57 = 14;
                    string[] array2 = new string[12]
                    {
                        cMapStyle, cMapFull, cMapZoomIn, cMapZoomOut, cMapAlphaUp, cMapAlphaDown, null, null, null, null,
                        null, null
                    };
                    if (setKey >= 0)
                    {
                        array2[setKey] = "_";
                    }
                    array11[0] = Lang.menu[106].Value + array2[0];
                    array11[1] = Lang.menu[107].Value + array2[1];
                    array11[2] = Lang.menu[108].Value + array2[2];
                    array11[3] = Lang.menu[109].Value + array2[3];
                    array11[4] = Lang.menu[110].Value + array2[4];
                    array11[5] = Lang.menu[111].Value + array2[5];
                    for (int num41 = 0; num41 < 6; num41++)
                    {
                        array10[num41] = true;
                        array9[num41] = 0.55f;
                        array7[num41] = -140;
                    }
                    array9[6] = 0.8f;
                    array9[6] = 0.8f;
                    array6[6] = 6;
                    array11[6] = Lang.menu[86].Value;
                    array6[7] = 16;
                    array11[7] = Lang.menu[5].Value;
                    if (selectedMenu == 7 || flag7)
                    {
                        flag7 = false;
                        menuMode = 11;
                        SoundEngine.PlaySound(11);
                    }
                    else if (selectedMenu == 6)
                    {
                        cMapStyle = "Tab";
                        cMapFull = "M";
                        cMapZoomIn = "Add";
                        cMapZoomOut = "Subtract";
                        cMapAlphaUp = "PageUp";
                        cMapAlphaDown = "PageDown";
                        setKey = -1;
                        SoundEngine.PlaySound(11);
                    }
                    else if (selectedMenu >= 0)
                    {
                        setKey = selectedMenu;
                    }
                    if (setKey >= 0)
                    {
                        List<Keys> pressedKeys = PlayerInput.GetPressedKeys();
                        if (pressedKeys.Count > 0)
{
                            string text = string.Concat(pressedKeys[0]);
                            if (text != "None")
{
                                if (setKey == 0)
{
                                    cMapStyle = text;
                                }
                                if (setKey == 1)
{
                                    cMapFull = text;
                                }
                                if (setKey == 2)
{
                                    cMapZoomIn = text;
                                }
                                if (setKey == 3)
{
                                    cMapZoomOut = text;
                                }
                                if (setKey == 4)
{
                                    cMapAlphaUp = text;
                                }
                                if (setKey == 5)
{
                                    cMapAlphaDown = text;
                                }
                                setKey = -1;
                            }
                        }
                    }
                }
                else if (menuMode == 27)
                {
                    num24 = 176;
                    num46 = 22;
                    num57 = 16;
                    string[] array3 = new string[14]
                    {
                        cUp, cDown, cLeft, cRight, cJump, cThrowItem, cInv, cHeal, cMana, cBuff,
                        cHook, cTorch, cSmart, cMount
                    };
                    if (setKey >= 0)
                    {
                        array3[setKey] = "_";
                    }
                    array11[0] = Lang.menu[74].Value + array3[0];
                    array11[1] = Lang.menu[75].Value + array3[1];
                    array11[2] = Lang.menu[76].Value + array3[2];
                    array11[3] = Lang.menu[77].Value + array3[3];
                    array11[4] = Lang.menu[78].Value + array3[4];
                    array11[5] = Lang.menu[79].Value + array3[5];
                    array11[6] = Lang.menu[80].Value + array3[6];
                    array11[7] = Lang.menu[81].Value + array3[7];
                    array11[8] = Lang.menu[82].Value + array3[8];
                    array11[9] = Lang.menu[83].Value + array3[9];
                    array11[10] = Lang.menu[84].Value + array3[10];
                    array11[11] = Lang.menu[85].Value + array3[11];
                    array11[12] = Lang.menu[120].Value + array3[12];
                    array11[13] = Lang.menu[130].Value + array3[13];
                    for (int num42 = 0; num42 < 14; num42++)
                    {
                        array10[num42] = true;
                        array9[num42] = 0.45f;
                        array7[num42] = -80;
                    }
                    array9[14] = 0.8f;
                    array6[14] = 6;
                    array11[14] = Lang.menu[86].Value;
                    array9[15] = 0.8f;
                    array6[15] = 16;
                    array11[15] = Lang.menu[5].Value;
                    if (selectedMenu == 15 || flag7)
                    {
                        flag7 = false;
                        menuMode = 11;
                        SoundEngine.PlaySound(11);
                    }
                    else if (selectedMenu == 14)
                    {
                        ResetKeyBindings();
                        setKey = -1;
                        SoundEngine.PlaySound(11);
                    }
                    else if (selectedMenu >= 0)
                    {
                        setKey = selectedMenu;
                    }
                    if (setKey >= 0)
                    {
                        List<Keys> pressedKeys2 = PlayerInput.GetPressedKeys();
                        if (pressedKeys2.Count > 0)
{
                            string text2 = string.Concat(pressedKeys2[0]);
                            if (text2 != "None")
{
                                if (setKey == 0)
{
                                    cUp = text2;
                                }
                                if (setKey == 1)
{
                                    cDown = text2;
                                }
                                if (setKey == 2)
{
                                    cLeft = text2;
                                }
                                if (setKey == 3)
{
                                    cRight = text2;
                                }
                                if (setKey == 4)
{
                                    cJump = text2;
                                }
                                if (setKey == 5)
{
                                    cThrowItem = text2;
                                }
                                if (setKey == 6)
{
                                    cInv = text2;
                                }
                                if (setKey == 7)
{
                                    cHeal = text2;
                                }
                                if (setKey == 8)
{
                                    cMana = text2;
                                }
                                if (setKey == 9)
{
                                    cBuff = text2;
                                }
                                if (setKey == 10)
{
                                    cHook = text2;
                                }
                                if (setKey == 11)
{
                                    cTorch = text2;
                                }
                                if (setKey == 12)
{
                                    cSmart = text2;
                                }
                                if (setKey == 13)
{
                                    cMount = text2;
                                }
                                setKey = -1;
                            }
                        }
                    }
                }
                else if (menuMode == 1127)
                {
                    num24 = 250;
                    num46 = 52;
                    num57 = 4;
                    array6[num57 - 1] = 18;
                    for (int num43 = 0; num43 < num57; num43++)
                    {
                        array9[num43] = 0.78f;
                    }
                    int num44 = 0;
                    array11[num44] = (ReversedUpDownArmorSetBonuses ? Lang.menu[220].Value : Lang.menu[221].Value);
                    if (selectedMenu == num44)
                    {
                        SoundEngine.PlaySound(12);
                        ReversedUpDownArmorSetBonuses = !ReversedUpDownArmorSetBonuses;
                    }
                    num44++;
                    if (ItemSlot.Options.DisableQuickTrash)
                    {
                        array11[num44] = Lang.menu[253].Value;
                    }
                    else
                    {
                        array11[num44] = (ItemSlot.Options.DisableLeftShiftTrashCan ? Lang.menu[224].Value : Lang.menu[223].Value);
                    }
                    if (selectedMenu == num44)
                    {
                        SoundEngine.PlaySound(12);
                        if (ItemSlot.Options.DisableQuickTrash)
{
                            ItemSlot.Options.DisableQuickTrash = false;
                            ItemSlot.Options.DisableLeftShiftTrashCan = true;
                        }
                        else if (ItemSlot.Options.DisableLeftShiftTrashCan)
{
                            ItemSlot.Options.DisableLeftShiftTrashCan = false;
                        }
                        else
{
                            ItemSlot.Options.DisableQuickTrash = true;
                            ItemSlot.Options.DisableLeftShiftTrashCan = false;
                        }
                    }
                    num44++;
                    array11[num44] = Lang.menu[222].Value;
                    if (selectedMenu == num44)
                    {
                        SoundEngine.PlaySound(10);
                        menuMode = 888;
                        MenuUI.SetState(ManageControlsMenu);
                    }
                    num44++;
                    array11[num44] = Lang.menu[5].Value;
                    if (selectedMenu == num44 || flag7)
                    {
                        flag7 = false;
                        menuMode = 11;
                        SoundEngine.PlaySound(11);
                    }
                }
                else if (menuMode == 12)
                {
                    int num45 = ((SocialAPI.Network != null) ? 1 : 0);
                    menuServer = false;
                    array11[0] = Lang.menu[(SocialAPI.Network != null) ? 146 : 87].Value;
                    array11[1] = Lang.menu[145].Value;
                    array11[1 + num45] = Lang.menu[88].Value;
                    array11[2 + num45] = Lang.menu[5].Value;
                    if (selectedMenu == 0)
                    {
                        LoadPlayers();
                        menuMultiplayer = true;
                        SoundEngine.PlaySound(10);
                        ClearPendingPlayerSelectCallbacks();
                        menuMode = 1;
                    }
                    else if (selectedMenu == 1 + num45)
                    {
                        LoadPlayers();
                        SoundEngine.PlaySound(10);
                        ClearPendingPlayerSelectCallbacks();
                        menuMode = 1;
                        menuMultiplayer = true;
                        menuServer = true;
                    }
                    else if (selectedMenu == 1)
                    {
                        SoundEngine.PlaySound(10);
                        SocialAPI.Friends.OpenJoinInterface();
                    }
                    else if (selectedMenu == 2 + num45 || flag7)
                    {
                        flag7 = false;
                        SoundEngine.PlaySound(11);
                        menuMode = 0;
                    }
                    num57 = 3 + num45;
                }
                else if (menuMode == 13)
                {
                    if (PlayerInput.SettingsForUI.ShowGamepadHints)
                    {
                        num24 = 180;
                        num46 = 30;
                        int num47 = 0;
                        array11[num47] = Lang.menu[89].Value.Replace(":", "");
                        if (selectedMenu == num47)
{
                            UIVirtualKeyboard state = new UIVirtualKeyboard(Lang.menu[89].Value, getIP, OnSubmitServerIP, CreateGoToMenuEvent(13), 0, allowEmpty: true);
                            UserInterface.ActiveInstance.SetState(state);
                            menuMode = 888;
                        }
                        array9[num47] = 0.6f;
                        array6[num47] = 40;
                        num47++;
                        for (int num48 = 0; num48 <= 6; num48++)
{
                            if (recentWorld[num48] != null && recentWorld[num48] != "")
{
                                array11[num47] = recentWorld[num48] + " (" + recentIP[num48] + ":" + recentPort[num48] + ")";
                            }
                            else
{
                                array11[num47] = "";
                                array[num47] = true;
                            }
                            array9[num47] = 0.6f;
                            array6[num47] = 40;
                            if (selectedMenu == num47)
{
                                autoPass = false;
                                Netplay.ListenPort = recentPort[num48];
                                getIP = recentIP[num48];
                                Netplay.SetRemoteIPAsync(getIP, StartClientGameplay);
                                menuMode = 14;
                                statusText = Language.GetTextValue("Net.ConnectingTo", getIP);
                            }
                            num47++;
                        }
                        array6[num47] = 64;
                        array11[num47] = Lang.menu[5].Value;
                        if (selectedMenu == num47 || flag7)
{
                            flag7 = false;
                            SoundEngine.PlaySound(11);
                            menuMode = 1;
                        }
                        num47++;
                        num57 = num47;
                    }
                    else
                    {
                        string text6 = getIP;
                        PlayerInput.WritingText = true;
                        instance.HandleIME();
                        getIP = GetInputText(getIP);
                        if (text6 != getIP)
{
                            SoundEngine.PlaySound(12);
                        }
                        num57 = 11;
                        num24 = 180;
                        num46 = 30;
                        array11[0] = Lang.menu[89].Value;
                        array[0] = true;
                        array11[1] = getIP;
                        array6[1] = 19;
                        if (textBlinkerState == 1)
{
                            array11[1] += "|";
                            array7[1] = 1;
                        }
                        else
{
                            array11[1] += " ";
                        }
                        array[1] = true;
                        array6[9] = 44;
                        array11[9] = Lang.menu[4].Value;
                        array4[9] = true;
                        if (getIP != "")
{
                            if (getIP.Substring(0, 1) == " ")
{
                                getIP = "";
                            }
                            for (int num49 = 0; num49 < getIP.Length; num49++)
{
                                if (getIP != " ")
{
                                    array4[9] = false;
                                }
                            }
                        }
                        array6[10] = 64;
                        array11[10] = Lang.menu[5].Value;
                        for (int num50 = 2; num50 <= 8; num50++)
{
                            int num51 = num50 - 2;
                            if (recentWorld[num51] != null && recentWorld[num51] != "")
{
                                array11[num50] = recentWorld[num51] + " (" + recentIP[num51] + ":" + recentPort[num51] + ")";
                            }
                            else
{
                                array11[num50] = "";
                                array[num50] = true;
                            }
                            array9[num50] = 0.6f;
                            array6[num50] = 40;
                        }
                        if (selectedMenu >= 2 && selectedMenu < 9)
{
                            autoPass = false;
                            int num52 = selectedMenu - 2;
                            Netplay.ListenPort = recentPort[num52];
                            getIP = recentIP[num52];
                            Netplay.SetRemoteIPAsync(getIP, StartClientGameplay);
                            menuMode = 14;
                            statusText = Language.GetTextValue("Net.ConnectingTo", getIP);
                        }
                        if (selectedMenu == 10 || flag7)
{
                            flag7 = false;
                            SoundEngine.PlaySound(11);
                            menuMode = 1;
                        }
                        if (selectedMenu == 9 || (!array4[2] && inputTextEnter))
{
                            OnSubmitServerIP(getIP);
                        }
                        textBlinkerCount++;
                        if (textBlinkerCount >= 20)
{
                            if (textBlinkerState == 0)
{
                                textBlinkerState = 1;
                            }
                            else
{
                                textBlinkerState = 0;
                            }
                            textBlinkerCount = 0;
                        }
                    }
                }
                else if (menuMode == 131)
                {
                    if (PlayerInput.SettingsForUI.ShowGamepadHints)
                    {
                        UIVirtualKeyboard uIVirtualKeyboard4 = new UIVirtualKeyboard(Lang.menu[90].Value, getPort, OnSubmitServerPort, CreateGoToMenuEvent(13), 0, allowEmpty: true);
                        uIVirtualKeyboard4.CustomTextValidationForUpdate = IsGoodPortAddress;
                        uIVirtualKeyboard4.CustomTextValidationForSubmit = IsGoodPortAddress;
                        UserInterface.ActiveInstance.SetState(uIVirtualKeyboard4);
                        menuMode = 888;
                    }
                    int num53 = 7777;
                    PlayerInput.WritingText = true;
                    instance.HandleIME();
                    string text7 = getPort;
                    getPort = GetInputText(getPort);
                    if (text7 != getPort)
                    {
                        SoundEngine.PlaySound(12);
                    }
                    array11[0] = Lang.menu[90].Value;
                    array4[2] = true;
                    if (getPort != "")
                    {
                        bool flag9 = false;
                        try
{
                            num53 = Convert.ToInt32(getPort);
                            if (num53 > 0 && num53 <= 65535)
{
                                flag9 = true;
                            }
                        }
                        catch
{
                        }
                        if (flag9)
{
                            array4[2] = false;
                        }
                    }
                    textBlinkerCount++;
                    if (textBlinkerCount >= 20)
                    {
                        if (textBlinkerState == 0)
{
                            textBlinkerState = 1;
                        }
                        else
{
                            textBlinkerState = 0;
                        }
                        textBlinkerCount = 0;
                    }
                    array11[1] = getPort;
                    if (textBlinkerState == 1)
                    {
                        array11[1] += "|";
                        array7[1] = 1;
                    }
                    else
                    {
                        array11[1] += " ";
                    }
                    array[0] = true;
                    array[1] = true;
                    array6[1] = -20;
                    array6[2] = 20;
                    array11[2] = Lang.menu[4].Value;
                    array11[3] = Lang.menu[5].Value;
                    num57 = 4;
                    if (selectedMenu == 3 || flag7)
                    {
                        flag7 = false;
                        SoundEngine.PlaySound(11);
                        menuMode = 1;
                    }
                    if (selectedMenu == 2 || (!array4[2] && inputTextEnter))
                    {
                        OnSubmitServerPort(getPort);
                    }
                }
                else if (menuMode == 16)
                {
                    num24 = 200;
                    num46 = 60;
                    array6[1] = 30;
                    array6[2] = 30;
                    array6[3] = 30;
                    array6[4] = 70;
                    array11[0] = Lang.menu[91].Value;
                    array[0] = true;
                    array11[1] = Lang.menu[92].Value;
                    array11[2] = Lang.menu[93].Value;
                    array11[3] = Lang.menu[94].Value;
                    array11[4] = Lang.menu[5].Value;
                    num57 = 5;
                    if (selectedMenu == 4 || flag7)
                    {
                        flag7 = false;
                        menuMode = 6;
                        SoundEngine.PlaySound(11);
                    }
                    else if (selectedMenu > 0)
                    {
                        if (selectedMenu == 1)
{
                            maxTilesX = 4200;
                            maxTilesY = 1200;
                        }
                        else if (selectedMenu == 2)
{
                            maxTilesX = 6400;
                            maxTilesY = 1800;
                        }
                        else
{
                            maxTilesX = 8400;
                            maxTilesY = 8400;
                        }
                        clrInput();
                        menuMode = -7;
                        SoundEngine.PlaySound(10);
                        WorldGen.setWorldSize();
                    }
                }
                else if (menuMode == 1000000)
                {
                    num57 = 2;
                    array11[0] = statusText;
                    array[0] = true;
                    num24 = 220;
                    num46 = 250;
                    array11[1] = Lang.menu[5].Value;
                    if (selectedMenu == 1 || flag7)
                    {
                        flag7 = false;
                        SoundEngine.PlaySound(11);
                        menuMode = 6;
                        netMode = 0;
                    }
                }
                else if (menuMode == 1000001)
                {
                    num57 = 2;
                    array11[0] = statusText;
                    array[0] = true;
                    num24 = 220;
                    num46 = 250;
                    RejectionMenuInfo rejectionMenuInfo = RejectionMenuInfo;
                    if (rejectionMenuInfo != null)
                    {
                        array11[0] = rejectionMenuInfo.TextToShow;
                    }
                    array11[1] = Lang.menu[5].Value;
                    if (selectedMenu == 1 || flag7)
                    {
                        flag7 = false;
                        ReturnFromRejectionMenuAction returnFromRejectionMenuAction = null;
                        if (RejectionMenuInfo != null)
{
                            returnFromRejectionMenuAction = RejectionMenuInfo.ExitAction;
                        }
                        if (returnFromRejectionMenuAction != null)
{
                            returnFromRejectionMenuAction();
                        }
                        else
{
                            SoundEngine.PlaySound(11);
                            menuMode = 0;
                            netMode = 0;
                        }
                    }
                }
                else
                {
                    Interface.ModLoaderMenus(this, selectedMenu, array11, array9, array6, ref num24, ref num46, ref num57, ref flag7);
                }
            }
        }
        else
        {
            array11[0] = string.Format("{0}  {1}", Language.GetTextValue("UI.LoadingCode"), Program.LoadedPercentage.ToString("P0"));
            if (!Terraria.ModLoader.ModLoader.skipLoad)
            {
                array11[1] = "Click to skip loading mods";
                array9[1] = 0.5f;
                num57 = 2;
                if (selectedMenu == 1)
                {
                    Terraria.ModLoader.ModLoader.skipLoad = true;
                }
            }
        }
        if (menuMode == 888)
        {
            if (!_blockFancyUIWhileLoading)
            {
                MenuUI.Draw(spriteBatch, gameTime);
            }
        }
        else
        {
            MenuUI.SetState(null);
        }
        if (UILinkPointNavigator.Shortcuts.BackButtonInUse && !flag7)
        {
            UILinkPointNavigator.Shortcuts.BackButtonLock = true;
        }
        int num54 = focusMenu;
        if (menuMode != num68)
        {
            if (menuMode == 10 || netMode == 1 || menuMode == 14)
            {
                gameTips.ClearTips();
            }
            blockMouse = true;
            menuSkip = 0;
            num57 = 0;
            if (PlayerInput.UsingGamepad && InvisibleCursorForGamepad)
            {
                num54 = (focusMenu = -1);
                mouseX = (mouseY = (PlayerInput.MouseX = (PlayerInput.MouseY = 0)));
            }
            for (int num55 = 0; num55 < maxMenuItems; num55++)
            {
                menuItemScale[num55] = 0.8f;
            }
        }
        if (!mouseLeft)
        {
            blockMouse = true;
        }
        selectedMenu = -1;
        selectedMenu2 = -1;
        focusMenu = -1;
        bool flag10 = mouseLeft && !PlayerInput.UsingGamepad;
        if (!flag)
        {
            grabColorSlider = 0;
            hBar = -1f;
            sBar = -1f;
            lBar = -1f;
            aBar = -1f;
        }
        if (flag)
        {
            if (!mouseLeft)
            {
                grabColorSlider = 0;
                blockMouse = false;
            }
            int num56 = focusColor;
            focusColor = 0;
            int num58 = num101;
            int num59 = screenWidth / 2 - TextureAssets.Hue.Width() / 2;
            int num60 = 167;
            Vector3 val = rgbToHsl(selColor);
            float num61 = val.X;
            float num62 = val.Y;
            float luminosity = val.Z;
            float num63 = (float)(int)((Color)(ref selColor)).A / 255f;
            if (hBar == -1f || sBar == -1f || lBar == -1f || aBar == -1f)
            {
                hBar = num61;
                sBar = num62;
                lBar = luminosity;
                aBar = num63;
            }
            else
            {
                num61 = hBar;
                num62 = sBar;
                luminosity = lBar;
                num63 = aBar;
            }
            spriteBatch.Draw(TextureAssets.Hue.Value, new Vector2((float)num59, (float)num58), Color.White);
            if ((mouseX > num59 - 4 && mouseX < num59 + TextureAssets.Hue.Width() + 4 && mouseY > num58 - 4 && mouseY < num58 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 1)
            {
                spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2((float)num59, (float)num58), OurFavoriteColor);
            }
            spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num59 + (float)(TextureAssets.Hue.Width() - 2) * hBar - (float)(TextureAssets.ColorSlider.Width() / 2), (float)(num58 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2)), Color.White);
            if ((mouseX > num59 - 4 && mouseX < num59 + TextureAssets.Hue.Width() + 4 && mouseY > num58 - 4 && mouseY < num58 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 1)
            {
                focusColor = 1;
                UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 5;
                if (flag10 && !blockMouse)
                {
                    grabColorSlider = 1;
                    num61 = mouseX - num59;
                    num61 /= (float)TextureAssets.Hue.Width();
                    if (num61 < 0f)
                    {
                        num61 = 0f;
                    }
                    if (num61 > 1f)
                    {
                        num61 = 1f;
                    }
                    hBar = num61;
                }
            }
            GamepadMainMenuHandler.MenuItemPositions.Add(new Vector2((float)num59, (float)num58) + TextureAssets.ColorBar.Value.Size() / 2f);
            num58 += 26;
            spriteBatch.Draw(TextureAssets.ColorBar.Value, new Vector2((float)num59, (float)num58), Color.White);
            for (int num64 = 0; num64 <= num60; num64++)
            {
                float saturation = (float)num64 / (float)num60;
                Color color7 = hslToRgb(num61, saturation, luminosity);
                spriteBatch.Draw(TextureAssets.ColorBlip.Value, new Vector2((float)(num59 + num64 + 5), (float)(num58 + 4)), color7);
            }
            if ((mouseX > num59 - 4 && mouseX < num59 + TextureAssets.Hue.Width() + 4 && mouseY > num58 - 4 && mouseY < num58 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 2)
            {
                spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2((float)num59, (float)num58), OurFavoriteColor);
            }
            spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num59 + (float)(TextureAssets.Hue.Width() - 2) * sBar - (float)(TextureAssets.ColorSlider.Width() / 2), (float)(num58 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2)), Color.White);
            if ((mouseX > num59 - 4 && mouseX < num59 + TextureAssets.Hue.Width() + 4 && mouseY > num58 - 4 && mouseY < num58 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 2)
            {
                focusColor = 2;
                UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 6;
                if (flag10 && !blockMouse)
                {
                    grabColorSlider = 2;
                    num62 = mouseX - num59;
                    num62 /= (float)TextureAssets.Hue.Width();
                    if (num62 < 0f)
                    {
                        num62 = 0f;
                    }
                    if (num62 > 1f)
                    {
                        num62 = 1f;
                    }
                    sBar = num62;
                }
            }
            GamepadMainMenuHandler.MenuItemPositions.Add(new Vector2((float)num59, (float)num58) + TextureAssets.ColorBar.Value.Size() / 2f);
            num58 += 26;
            spriteBatch.Draw(TextureAssets.ColorBar.Value, new Vector2((float)num59, (float)num58), Color.White);
            float num65 = 0.15f;
            if (menuMode == 252)
            {
                num65 = 0f;
            }
            for (int num66 = 0; num66 <= num60; num66++)
            {
                float luminosity2 = (float)num66 / (float)num60;
                Color color8 = hslToRgb(num61, num62, luminosity2);
                spriteBatch.Draw(TextureAssets.ColorBlip.Value, new Vector2((float)(num59 + num66 + 5), (float)(num58 + 4)), color8);
            }
            if ((mouseX > num59 - 4 && mouseX < num59 + TextureAssets.Hue.Width() + 4 && mouseY > num58 - 4 && mouseY < num58 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 3)
            {
                spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2((float)num59, (float)num58), OurFavoriteColor);
            }
            spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num59 + (float)(TextureAssets.Hue.Width() - 2) * ((lBar - num65) / (1f - num65)) - (float)(TextureAssets.ColorSlider.Width() / 2), (float)(num58 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2)), Color.White);
            if ((mouseX > num59 - 4 && mouseX < num59 + TextureAssets.Hue.Width() + 4 && mouseY > num58 - 4 && mouseY < num58 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 3)
            {
                focusColor = 3;
                UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 7;
                if (flag10 && !blockMouse)
                {
                    grabColorSlider = 3;
                    luminosity = mouseX - num59;
                    luminosity /= (float)TextureAssets.Hue.Width();
                    if (luminosity < 0f)
                    {
                        luminosity = 0f;
                    }
                    if (luminosity > 1f)
                    {
                        luminosity = 1f;
                    }
                    luminosity = (lBar = luminosity * (1f - num65) + num65);
                }
            }
            GamepadMainMenuHandler.MenuItemPositions.Add(new Vector2((float)num59, (float)num58) + TextureAssets.ColorBar.Value.Size() / 2f);
            bool flag11 = false;
            if (menuMode == 252)
            {
                num58 += 26;
                flag11 = true;
                spriteBatch.Draw(TextureAssets.ColorBar.Value, new Vector2((float)num59, (float)num58), Color.White);
                Color color9 = hslToRgb(num61, num62, luminosity);
                for (int num67 = 0; num67 <= num60; num67++)
                {
                    float num69 = (float)num67 / (float)num60;
                    Color color10 = color9 * num69;
                    spriteBatch.Draw(TextureAssets.ColorBlip.Value, new Vector2((float)(num59 + num67 + 5), (float)(num58 + 4)), color10);
                }
                if ((mouseX > num59 - 4 && mouseX < num59 + TextureAssets.Hue.Width() + 4 && mouseY > num58 - 4 && mouseY < num58 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 4)
                {
                    spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2((float)num59, (float)num58), OurFavoriteColor);
                }
                spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num59 + (float)(TextureAssets.Hue.Width() - 2) * aBar - (float)(TextureAssets.ColorSlider.Width() / 2), (float)(num58 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2)), Color.White);
                if ((mouseX > num59 - 4 && mouseX < num59 + TextureAssets.Hue.Width() + 4 && mouseY > num58 - 4 && mouseY < num58 + TextureAssets.Hue.Height() + 4 && grabColorSlider == 0) || grabColorSlider == 4)
                {
                    focusColor = 4;
                    UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 8;
                    if (mouseLeft && !blockMouse)
                    {
                        grabColorSlider = 4;
                        num63 = mouseX - num59;
                        num63 /= (float)TextureAssets.Hue.Width();
                        if (num63 < 0f)
{
                            num63 = 0f;
                        }
                        if (num63 > 1f)
{
                            num63 = 1f;
                        }
                        aBar = num63;
                    }
                }
                GamepadMainMenuHandler.MenuItemPositions.Add(new Vector2((float)num59, (float)num58) + TextureAssets.ColorBar.Value.Size() / 2f);
            }
            if (num56 != focusColor)
            {
                SoundEngine.PlaySound(12);
            }
            selColor = hslToRgb(hBar, sBar, lBar);
            if (flag11)
            {
                ((Color)(ref selColor)).A = (byte)(aBar * 255f);
            }
        }
        else if (flag)
        {
            string text3 = "";
            for (int num70 = 0; num70 < 6; num70++)
            {
                int num71 = num101;
                int num72 = 370 + screenWidth / 2 - 400;
                if (num70 == 0)
                {
                    text3 = Lang.menu[95].Value;
                }
                if (num70 == 1)
                {
                    text3 = Lang.menu[96].Value;
                    num71 += 30;
                }
                if (num70 == 2)
                {
                    text3 = Lang.menu[97].Value;
                    num71 += 60;
                }
                if (num70 == 3)
                {
                    text3 = string.Concat(((Color)(ref selColor)).R);
                    num72 += 90;
                }
                if (num70 == 4)
                {
                    text3 = string.Concat(((Color)(ref selColor)).G);
                    num72 += 90;
                    num71 += 30;
                }
                if (num70 == 5)
                {
                    text3 = string.Concat(((Color)(ref selColor)).B);
                    num72 += 90;
                    num71 += 60;
                }
                for (int num73 = 0; num73 < 5; num73++)
                {
                    Color color11 = Color.Black;
                    if (num73 == 4)
                    {
                        color11 = color;
                        ((Color)(ref color11)).R = (byte)((255 + ((Color)(ref color11)).R) / 2);
                        ((Color)(ref color11)).G = (byte)((255 + ((Color)(ref color11)).R) / 2);
                        ((Color)(ref color11)).B = (byte)((255 + ((Color)(ref color11)).R) / 2);
                    }
                    int num74 = 255;
                    int num75 = ((Color)(ref color11)).R - (255 - num74);
                    if (num75 < 0)
                    {
                        num75 = 0;
                    }
                    ((Color)(ref color11))._002Ector((int)(byte)num75, (int)(byte)num75, (int)(byte)num75, (int)(byte)num74);
                    int num76 = 0;
                    int num77 = 0;
                    if (num73 == 0)
                    {
                        num76 = -2;
                    }
                    if (num73 == 1)
                    {
                        num76 = 2;
                    }
                    if (num73 == 2)
                    {
                        num77 = -2;
                    }
                    if (num73 == 3)
                    {
                        num77 = 2;
                    }
                    spriteBatch.DrawString(FontAssets.DeathText.Value, text3, new Vector2((float)(num72 + num76), (float)(num71 + num77)), color11, 0f, default(Vector2), 0.5f, (SpriteEffects)0, 0f);
                }
            }
            bool flag2 = false;
            Vector2 vector2 = default(Vector2);
            for (int num78 = 0; num78 < 2; num78++)
            {
                for (int num80 = 0; num80 < 3; num80++)
                {
                    int num81 = num101 + num80 * 30 - 12;
                    int num82 = 360 + screenWidth / 2 - 400;
                    float scale = 0.9f;
                    if (num78 == 0)
                    {
                        num82 -= 70;
                        num81 += 2;
                    }
                    else
                    {
                        num82 -= 40;
                    }
                    text3 = "-";
                    if (num78 == 1)
                    {
                        text3 = "+";
                    }
                    ((Vector2)(ref vector2))._002Ector(24f, 24f);
                    int num83 = 142;
                    if (mouseX > num82 && (float)mouseX < (float)num82 + vector2.X && mouseY > num81 + 13 && (float)mouseY < (float)(num81 + 13) + vector2.Y)
                    {
                        if (focusColor != (num78 + 1) * (num80 + 10))
{
                            SoundEngine.PlaySound(12);
                        }
                        focusColor = (num78 + 1) * (num80 + 10);
                        flag2 = true;
                        num83 = 255;
                        if (mouseLeft)
{
                            if (colorDelay <= 1)
{
                                if (colorDelay == 0)
{
                                    colorDelay = 40;
                                }
                                else
{
                                    colorDelay = 3;
                                }
                                int num84 = num78;
                                if (num78 == 0)
{
                                    num84 = -1;
                                    if (((Color)(ref selColor)).R + ((Color)(ref selColor)).G + ((Color)(ref selColor)).B <= 150)
{
                                        num84 = 0;
                                    }
                                }
                                if (num80 == 0 && ((Color)(ref selColor)).R + num84 >= 0 && ((Color)(ref selColor)).R + num84 <= 255)
{
                                    ((Color)(ref selColor)).R = (byte)(((Color)(ref selColor)).R + num84);
                                }
                                if (num80 == 1 && ((Color)(ref selColor)).G + num84 >= 0 && ((Color)(ref selColor)).G + num84 <= 255)
{
                                    ((Color)(ref selColor)).G = (byte)(((Color)(ref selColor)).G + num84);
                                }
                                if (num80 == 2 && ((Color)(ref selColor)).B + num84 >= 0 && ((Color)(ref selColor)).B + num84 <= 255)
{
                                    ((Color)(ref selColor)).B = (byte)(((Color)(ref selColor)).B + num84);
                                }
                            }
                            colorDelay--;
                        }
                        else
{
                            colorDelay = 0;
                        }
                    }
                    for (int num85 = 0; num85 < 5; num85++)
                    {
                        Color color12 = Color.Black;
                        if (num85 == 4)
{
                            color12 = color;
                            ((Color)(ref color12)).R = (byte)((255 + ((Color)(ref color12)).R) / 2);
                            ((Color)(ref color12)).G = (byte)((255 + ((Color)(ref color12)).R) / 2);
                            ((Color)(ref color12)).B = (byte)((255 + ((Color)(ref color12)).R) / 2);
                        }
                        int num86 = ((Color)(ref color12)).R - (255 - num83);
                        if (num86 < 0)
{
                            num86 = 0;
                        }
                        ((Color)(ref color12))._002Ector((int)(byte)num86, (int)(byte)num86, (int)(byte)num86, (int)(byte)num83);
                        int num87 = 0;
                        int num88 = 0;
                        if (num85 == 0)
{
                            num87 = -2;
                        }
                        if (num85 == 1)
{
                            num87 = 2;
                        }
                        if (num85 == 2)
{
                            num88 = -2;
                        }
                        if (num85 == 3)
{
                            num88 = 2;
                        }
                        spriteBatch.DrawString(FontAssets.DeathText.Value, text3, new Vector2((float)(num82 + num87), (float)(num81 + num88)), color12, 0f, default(Vector2), scale, (SpriteEffects)0, 0f);
                    }
                }
            }
            if (!flag2)
            {
                focusColor = 0;
                colorDelay = 0;
            }
        }
        if (flag4)
        {
            float x = screenWidth / 2 - 40 + 37;
            int num89 = 320;
            string text4 = "";
            Color textColor = default(Color);
            for (int num91 = 0; num91 < 6; num91++)
            {
                int num92 = num89;
                int num93 = 370 + screenWidth / 2 - 400 + 37;
                switch (num91)
                {
                case 0:
                    text4 = Lang.menu[98].Value;
                    num92 += 30;
                    break;
                case 1:
                    text4 = Lang.menu[99].Value;
                    break;
                case 2:
                    text4 = Lang.menu[119].Value;
                    num92 += 60;
                    break;
                case 3:
                    text4 = Math.Round(musicVolume * 100f) + "%";
                    num93 += 90;
                    break;
                case 4:
                    text4 = Math.Round(soundVolume * 100f) + "%";
                    num93 += 90;
                    num92 += 30;
                    break;
                case 5:
                    text4 = Math.Round(ambientVolume * 100f) + "%";
                    num93 += 90;
                    num92 += 60;
                    break;
                }
                Color color2 = color;
                ((Color)(ref color2)).R = (byte)((255 + ((Color)(ref color2)).R) / 2);
                ((Color)(ref color2)).G = (byte)((255 + ((Color)(ref color2)).R) / 2);
                ((Color)(ref color2)).B = (byte)((255 + ((Color)(ref color2)).R) / 2);
                int num94 = 255;
                int num95 = ((Color)(ref color2)).R - (255 - num94);
                if (num95 < 0)
                {
                    num95 = 0;
                }
                ((Color)(ref textColor))._002Ector((int)(byte)num95, (int)(byte)num95, (int)(byte)num95, (int)(byte)num94);
                Utils.DrawBorderStringFourWay(spriteBatch, FontAssets.DeathText.Value, text4, num93, num92, textColor, Color.Black, Vector2.Zero, 0.5f);
            }
            int rightHover = IngameOptions.rightHover;
            IngameOptions.rightHover = -1;
            if (!mouseLeft)
            {
                IngameOptions.rightLock = -1;
            }
            IngameOptions.valuePosition = new Vector2(x, (float)(num89 - 18 + 30));
            GamepadMainMenuHandler.MenuItemPositions.Add(IngameOptions.valuePosition - TextureAssets.ColorBar.Value.Size() * new Vector2(0.5f, 0f));
            float num96 = IngameOptions.DrawValueBar(spriteBatch, 1f, musicVolume);
            if (IngameOptions.inBar || IngameOptions.rightLock == 3)
            {
                UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 2;
                IngameOptions.rightHover = 3;
                if (flag10 && IngameOptions.rightLock == 3)
                {
                    musicVolume = num96;
                }
            }
            IngameOptions.valuePosition = new Vector2(x, (float)(num89 - 18 + 60));
            GamepadMainMenuHandler.MenuItemPositions.Add(IngameOptions.valuePosition - TextureAssets.ColorBar.Value.Size() * new Vector2(0.5f, 0f));
            float num97 = IngameOptions.DrawValueBar(spriteBatch, 1f, soundVolume);
            if (IngameOptions.inBar || IngameOptions.rightLock == 2)
            {
                UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 3;
                IngameOptions.rightHover = 2;
                if (flag10 && IngameOptions.rightLock == 2)
                {
                    soundVolume = num97;
                }
            }
            IngameOptions.valuePosition = new Vector2(x, (float)(num89 - 18 + 90));
            GamepadMainMenuHandler.MenuItemPositions.Add(IngameOptions.valuePosition - TextureAssets.ColorBar.Value.Size() * new Vector2(0.5f, 0f));
            float num98 = IngameOptions.DrawValueBar(spriteBatch, 1f, ambientVolume);
            if (IngameOptions.inBar || IngameOptions.rightLock == 4)
            {
                UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 4;
                IngameOptions.rightHover = 4;
                if (flag10 && IngameOptions.rightLock == 4)
                {
                    ambientVolume = num98;
                }
            }
            if (IngameOptions.rightHover != -1)
            {
                IngameOptions.rightLock = IngameOptions.rightHover;
            }
            if (IngameOptions.rightHover != rightHover)
            {
                SoundEngine.PlaySound(12);
            }
        }
        if (flag5)
        {
            int num99 = 400;
            string text5 = "";
            for (int num100 = 0; num100 < 4; num100++)
            {
                int num102 = num99;
                int num103 = 370 + screenWidth / 2 - 400;
                if (num100 == 0)
                {
                    text5 = Lang.menu[52].Value + ": " + bgScroll;
                }
                for (int num104 = 0; num104 < 5; num104++)
                {
                    Color color3 = Color.Black;
                    if (num104 == 4)
                    {
                        color3 = color;
                        ((Color)(ref color3)).R = (byte)((255 + ((Color)(ref color3)).R) / 2);
                        ((Color)(ref color3)).G = (byte)((255 + ((Color)(ref color3)).R) / 2);
                        ((Color)(ref color3)).B = (byte)((255 + ((Color)(ref color3)).R) / 2);
                    }
                    int num105 = 255;
                    int num106 = ((Color)(ref color3)).R - (255 - num105);
                    if (num106 < 0)
                    {
                        num106 = 0;
                    }
                    ((Color)(ref color3))._002Ector((int)(byte)num106, (int)(byte)num106, (int)(byte)num106, (int)(byte)num105);
                    int num107 = 0;
                    int num108 = 0;
                    if (num104 == 0)
                    {
                        num107 = -2;
                    }
                    if (num104 == 1)
                    {
                        num107 = 2;
                    }
                    if (num104 == 2)
                    {
                        num108 = -2;
                    }
                    if (num104 == 3)
                    {
                        num108 = 2;
                    }
                    spriteBatch.DrawString(FontAssets.DeathText.Value, text5, new Vector2((float)(num103 + num107), (float)(num102 + num108)), color3, 0f, default(Vector2), 0.5f, (SpriteEffects)0, 0f);
                }
            }
            IngameOptions.rightHover = -1;
            if (!mouseLeft)
            {
                IngameOptions.rightLock = -1;
            }
            IngameOptions.valuePosition = new Vector2((float)(screenWidth / 2 - 40), (float)(num99 + 12));
            GamepadMainMenuHandler.MenuItemPositions.Add(IngameOptions.valuePosition - TextureAssets.ColorBar.Value.Size() * new Vector2(0.5f, 0f));
            float num109 = IngameOptions.DrawValueBar(spriteBatch, 1f, (float)bgScroll / 100f);
            if (IngameOptions.inBar || IngameOptions.rightLock == 2)
            {
                UILinkPointNavigator.Shortcuts.OPTIONS_BUTTON_SPECIALFEATURE = 1;
                IngameOptions.rightHover = 2;
                if (flag10 && IngameOptions.rightLock == 2)
                {
                    bgScroll = (int)(num109 * 100f);
                    caveParallax = 1f - (float)bgScroll / 500f;
                }
            }
            if (IngameOptions.rightHover != -1)
            {
                IngameOptions.rightLock = IngameOptions.rightHover;
            }
        }
        bool flag3 = false;
        for (int num110 = 0; num110 < num57; num110++)
        {
            if (array11[num110] == null)
            {
                continue;
            }
            Vector2 origin = FontAssets.DeathText.Value.MeasureString(array11[num110]);
            origin.X *= 0.5f;
            origin.Y *= 0.5f;
            for (int num111 = 0; num111 < 5; num111++)
            {
                Color color4 = Color.Black;
                if (num111 == 4)
                {
                    switch (array8[num110])
                    {
                    case 0:
                        color4 = color;
                        break;
                    case 1:
                        color4 = mcColor;
                        break;
                    case 2:
                        color4 = hcColor;
                        break;
                    case 3:
                        color4 = highVersionColor;
                        break;
                    case 4:
                    case 5:
                    case 6:
                        color4 = errorColor;
                        break;
                    default:
                        color4 = color;
                        break;
                    }
                    ((Color)(ref color4)).R = (byte)((255 + ((Color)(ref color4)).R) / 2);
                    ((Color)(ref color4)).G = (byte)((255 + ((Color)(ref color4)).G) / 2);
                    ((Color)(ref color4)).B = (byte)((255 + ((Color)(ref color4)).B) / 2);
                }
                int num3 = (int)(255f * (menuItemScale[num110] * 2f - 1f));
                if (array[num110])
                {
                    num3 = 255;
                }
                int num4 = ((Color)(ref color4)).R - (255 - num3);
                if (num4 < 0)
                {
                    num4 = 0;
                }
                int num5 = ((Color)(ref color4)).G - (255 - num3);
                if (num5 < 0)
                {
                    num5 = 0;
                }
                int num6 = ((Color)(ref color4)).B - (255 - num3);
                if (num6 < 0)
                {
                    num6 = 0;
                }
                if (num54 == num110 && num111 == 4)
                {
                    float num7 = (float)num3 / 255f;
                    num4 = (int)((float)num4 * (1f - num7) + 255f * num7);
                    num5 = (int)((float)num5 * (1f - num7) + 215f * num7);
                    num6 = (int)((float)num6 * (1f - num7) + 0f * num7);
                }
                ((Color)(ref color4))._002Ector((int)(byte)num4, (int)(byte)num5, (int)(byte)num6, (int)(byte)num3);
                if (array5[num110])
                {
                    if (num111 == 4)
                    {
                        ((Color)(ref color4)).R = (byte)(((Color)(ref color4)).R * mouseTextColor / 300);
                        ((Color)(ref color4)).G = (byte)(((Color)(ref color4)).G * mouseTextColor / 300);
                        ((Color)(ref color4)).B = (byte)(((Color)(ref color4)).B * mouseTextColor / 300);
                        ((Color)(ref color4)).A = (byte)(((Color)(ref color4)).A * mouseTextColor / 300);
                    }
                    else
                    {
                        ((Color)(ref color4)).A = (byte)(((Color)(ref color4)).A - (byte)(mouseTextColor / 5));
                    }
                }
                int num8 = 0;
                int num9 = 0;
                if (num111 == 0)
                {
                    num8 = -2;
                }
                if (num111 == 1)
                {
                    num8 = 2;
                }
                if (num111 == 2)
                {
                    num9 = -2;
                }
                if (num111 == 3)
                {
                    num9 = 2;
                }
                float num10 = menuItemScale[num110];
                if (menuMode == 15 && num110 == 0)
                {
                    num10 *= 0.35f;
                }
                else if (menuMode == 1000000 && num110 == 0)
                {
                    num10 *= 0.75f;
                }
                else if (netMode == 2)
                {
                    num10 *= 0.5f;
                }
                num10 *= array9[num110];
                if (!array10[num110])
                {
                    spriteBatch.DrawString(FontAssets.DeathText.Value, array11[num110], new Vector2((float)(num35 + num8 + array7[num110]), (float)(num24 + num46 * num110 + num9) + origin.Y * array9[num110] + (float)array6[num110]), color4, 0f, origin, num10, (SpriteEffects)0, 0f);
                }
                else
                {
                    spriteBatch.DrawString(FontAssets.DeathText.Value, array11[num110], new Vector2((float)(num35 + num8 + array7[num110]), (float)(num24 + num46 * num110 + num9) + origin.Y * array9[num110] + (float)array6[num110]), color4, 0f, new Vector2(0f, origin.Y), num10, (SpriteEffects)0, 0f);
                }
            }
            if (!array[num110] && !array4[num110])
            {
                GamepadMainMenuHandler.MenuItemPositions.Add(new Vector2((float)(num35 + array7[num110]), (float)(num24 + num46 * num110) + origin.Y * array9[num110] + (float)array6[num110]));
            }
            if (!array10[num110])
            {
                int num11 = 0;
                menuWide[num110] = false;
                Vector2 vector3 = FontAssets.DeathText.Value.MeasureString(array11[num110]) * array9[num110];
                if (!((float)mouseX > (float)num35 - vector3.X * 0.5f + (float)array7[num110] - (float)num11) || !((float)mouseX < (float)num35 + vector3.X * 0.5f * array9[num110] + (float)array7[num110] + (float)num11) || mouseY <= num24 + num46 * num110 + array6[num110] || !((float)mouseY < (float)(num24 + num46 * num110 + array6[num110]) + 50f * array9[num110]) || !hasFocus)
                {
                    continue;
                }
                focusMenu = num110;
                if (array[num110] || array4[num110])
                {
                    focusMenu = -1;
                    continue;
                }
                if (num54 != focusMenu)
                {
                    flag3 = true;
                }
                if (mouseLeftRelease && mouseLeft)
                {
                    selectedMenu = num110;
                }
                if (mouseRightRelease && mouseRight)
                {
                    selectedMenu2 = num110;
                }
                continue;
            }
            Vector2 vector4 = FontAssets.DeathText.Value.MeasureString(array11[num110]) * array9[num110];
            if (mouseX <= num35 + array7[num110] || !((float)mouseX < (float)num35 + vector4.X + (float)array7[num110]) || mouseY <= num24 + num46 * num110 + array6[num110] || !((float)mouseY < (float)(num24 + num46 * num110 + array6[num110]) + 50f * array9[num110]) || !hasFocus)
            {
                continue;
            }
            focusMenu = num110;
            if (array[num110] || array4[num110])
            {
                focusMenu = -1;
                continue;
            }
            if (num54 != focusMenu)
            {
                flag3 = true;
            }
            if (mouseLeftRelease && mouseLeft)
            {
                selectedMenu = num110;
            }
            if (mouseRightRelease && mouseRight)
            {
                selectedMenu2 = num110;
            }
        }
        if (flag3 && num54 != focusMenu)
        {
            SoundEngine.PlaySound(12);
        }
        if (GamepadMainMenuHandler.MenuItemPositions.Count == 0)
        {
            Vector2 vector5 = new Vector2((float)Math.Cos(GlobalTimeWrappedHourly * ((float)Math.PI * 2f)), (float)Math.Sin(GlobalTimeWrappedHourly * ((float)Math.PI * 2f) * 2f)) * new Vector2(30f, 15f) + Vector2.UnitY * 20f;
            UILinkPointNavigator.SetPosition(2000, new Vector2((float)screenWidth, (float)screenHeight) / 2f + vector5);
        }
        for (int num12 = 0; num12 < maxMenuItems; num12++)
        {
            if (num12 == focusMenu)
            {
                if (menuItemScale[num12] < 1f)
                {
                    menuItemScale[num12] += 0.02f;
                }
                if (menuItemScale[num12] > 1f)
                {
                    menuItemScale[num12] = 1f;
                }
            }
            else if ((double)menuItemScale[num12] > 0.8)
            {
                menuItemScale[num12] -= 0.02f;
            }
        }
        if (flag6)
        {
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, UIScaleMatrix);
            Player pendingPlayer = PendingPlayer;
            pendingPlayer.PlayerFrame();
            pendingPlayer.position.X = (float)num79 + screenPosition.X;
            pendingPlayer.position.Y = (float)num90 + screenPosition.Y;
            PlayerRenderer.DrawPlayer(Camera, pendingPlayer, pendingPlayer.position, 0f, Vector2.Zero);
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, UIScaleMatrix);
        }
        float num14 = 0f;
        if (!WorldGen.drunkWorldGen && menuMode == 0)
        {
            DrawSocialMediaButtons(color, num14);
            num14 += 32f;
            DrawtModLoaderSocialMediaButtons(color, num14);
        }
        if (!WorldGen.drunkWorldGen)
        {
            DrawVersionNumber(color, num14);
            num14 += 20f;
        }
        spriteBatch.End();
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerStateForCursor, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, UIScaleMatrix);
        WorkshopPublishingIndicator.Draw(spriteBatch);
        IssueReporterIndicator.Draw(spriteBatch);
        DrawCursor(DrawThickCursor());
        DrawPendingMouseText();
        if (fadeCounter > 0)
        {
            Color white = Color.White;
            byte b2 = 0;
            fadeCounter--;
            float num15 = (float)fadeCounter / 120f * 255f;
            if (quickSplash)
            {
                num15 = (float)fadeCounter / 75f * 255f;
            }
            b2 = (byte)num15;
            ((Color)(ref white))._002Ector((int)b2, (int)b2, (int)b2, (int)b2);
            spriteBatch.Draw(TextureAssets.Fade.Value, new Rectangle(-5, -5, screenWidth + 10, screenHeight + 10), white);
        }
        spriteBatch.End();
        if (mouseLeft)
        {
            mouseLeftRelease = false;
        }
        else
        {
            mouseLeftRelease = true;
        }
        if (mouseRight)
        {
            mouseRightRelease = false;
        }
        else
        {
            mouseRightRelease = true;
        }
        if (mouseMiddle)
        {
            mouseMiddleRelease = false;
        }
        else
        {
            mouseMiddleRelease = true;
        }
        if (mouseXButton1)
        {
            mouseXButton1Release = false;
        }
        else
        {
            mouseXButton1Release = true;
        }
        if (mouseXButton2)
        {
            mouseXButton2Release = false;
        }
        else
        {
            mouseXButton2Release = true;
        }
        if (menuMode == num)
        {
            GamepadMainMenuHandler.LastDrew = num;
        }
    }
References Terraria.Main._blockFancyUIWhileLoading, Terraria.Main._pendingCharacterSelect, Terraria.Main._worldSelectMenu, Terraria.Main.aBar, Terraria.Main.AchievementsMenu, Terraria.ModLoader.MenuLoader.ActivateOldVanillaMenu(), Terraria.UI.UserInterface.ActiveInstance, Terraria.Main.ActiveWorldFileData, Terraria.ModLoader.UI.Interface.AddMenuButtons(), Terraria.Main.alreadyGrabbingSunOrMoon, Terraria.Main.ambientVolume, Terraria.Main.autoPass, Terraria.Main.autoPause, Terraria.Main.autoSave, Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.BackButtonInUse, Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.BackButtonLock, Terraria.Main.background, Terraria.Main.BackgroundEnabled, Terraria.Main.bgScroll, Terraria.Main.blockMouse, Terraria.Main.BorderedHeight(), Terraria.NetMessage.buffer, Terraria.Main.CanceledGivingServerPassword(), Terraria.Main.caveParallax, Terraria.Main.cBuff, Terraria.Main.cDown, Terraria.Main.changeTheTitle, Terraria.Main.chatMonitor, Terraria.Main.cHeal, Terraria.Main.cHook, Terraria.Main.cInv, Terraria.Main.cJump, Terraria.Main.ClearPendingPlayerSelectCallbacks(), Terraria.Main.ClearVisualPostProcessEffects(), Terraria.Main.cLeft, Terraria.Netplay.Clients, Terraria.Main.clrInput(), Terraria.Main.cMana, Terraria.Main.cMapAlphaDown, Terraria.Main.cMapAlphaUp, Terraria.Main.cMapFull, Terraria.Main.cMapStyle, Terraria.Main.cMapZoomIn, Terraria.Main.cMapZoomOut, Terraria.Main.cMount, Terraria.Graphics.Light.Color, Terraria.GameContent.TextureAssets.ColorBar, Terraria.GameContent.TextureAssets.ColorBlip, Terraria.Main.colorDelay, Terraria.GameContent.TextureAssets.ColorHighlight, Terraria.GameContent.TextureAssets.ColorSlider, Terraria.Netplay.Connection, Terraria.ID.PlayerVariantID.Count, Terraria.Main.CreateGoToMenuEvent(), Terraria.Main.cRight, Terraria.Main.cSmart, Terraria.Main.cSmartCursorModeIsToggleAndNotHold, Terraria.Main.cThrowItem, Terraria.Main.cTorch, Terraria.Main.cUp, Terraria.ModLoader.IO.WorldIO.customDataFail, Terraria.Main.CycleClothingStyle(), Terraria.Main.CycleFrameSkipMode(), Terraria.GameInput.LockOnHelper.CycleUseModes(), Terraria.Main.dayTime, Terraria.GameContent.FontAssets.DeathText, Terraria.GameContent.ChildSafety.Disabled, Terraria.UI.ItemSlot.Options.DisableLeftShiftTrashCan, Terraria.UI.ItemSlot.Options.DisableQuickTrash, Terraria.Main.displayHeight, Terraria.Main.displayWidth, Terraria.GameContent.UI.WorkshopPublishingIndicator.Draw(), Terraria.Utils.DrawBorderStringFourWay(), Terraria.Main.DrawCursor(), Terraria.Main.DrawFPS(), Terraria.Main.drawingPlayerChat, Terraria.Main.DrawPendingMouseText(), Terraria.Main.DrawSocialMediaButtons(), Terraria.Main.DrawThickCursor(), Terraria.Main.DrawtModLoaderSocialMediaButtons(), Terraria.IngameOptions.DrawValueBar(), Terraria.Main.DrawVersionNumber(), Terraria.WorldGen.drunkWorldGen, Terraria.Main.eclipse, Terraria.Main.ErasePlayer(), Terraria.Main.EraseWorld(), Terraria.Main.errorColor, Terraria.Utilities.FileUtilities.Exists(), Terraria.DataStructures.RejectionMenuInfo.ExitAction, Terraria.Main.ExitServerPasswordMenu(), Terraria.GameContent.TextureAssets.Fade, Terraria.Main.fadeCounter, Terraria.Main.focusColor, Terraria.Main.focusMenu, Terraria.Social.SocialAPI.Friends, Terraria.Main.GameAskedToQuit, Terraria.Main.GameMode, Terraria.Main.GamepadDisableInstructionsDisplay, Terraria.Main.gameTips, Terraria.Main.GetInputText(), Terraria.Main.getIP, Terraria.Main.getPort, Terraria.GameInput.PlayerInput.GetPressedKeys(), Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.grabColorSlider, Terraria.Main.graphics, Terraria.Main.hasFocus, Terraria.Main.hBar, Terraria.Main.hcColor, Terraria.Main.HidePassword, Terraria.UI.ItemSlot.Options.HighlightNewItems, Terraria.Main.highVersionColor, Terraria.Main.hslToRgb(), Terraria.GameContent.TextureAssets.Hue, Terraria.IngameOptions.inBar, Terraria.Main.inputTextEnter, Terraria.ModLoader.BossBarLoader.InsertMenu(), Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Localization.LanguageManager.Instance, Terraria.Main.instance, Terraria.Lang.inter, Terraria.Netplay.InvalidateAllOngoingIPSetAttempts(), Terraria.Main.invasionProgressMode, Terraria.Main.InvisibleCursorForGamepad, Terraria.Main.IsBorderlessDisplayAvailable(), Terraria.Main.IsEngineLoaded, Terraria.Main.IsGoodPortAddress(), Terraria.Main.IssueReporterIndicator, Terraria.Main.lBar, Terraria.ModLoader.IO.WorldIO.LoadBackup(), Terraria.Program.LoadedEverything, Terraria.Program.LoadedPercentage, Terraria.Main.LoadPlayers(), Terraria.ModLoader.Logging.LogDir, Terraria.GameContent.TextureAssets.Logo, Terraria.GameContent.TextureAssets.Logo2, Terraria.GameContent.TextureAssets.Logo3, Terraria.GameContent.TextureAssets.Logo4, Terraria.Main.LogoA, Terraria.Main.LogoB, Terraria.Main.logoRotation, Terraria.Main.logoRotationDirection, Terraria.Main.logoRotationSpeed, Terraria.Main.logoScale, Terraria.Main.logoScaleDirection, Terraria.Main.logoScaleSpeed, Terraria.Main.LogoT, Terraria.Main.ManageControlsMenu, Terraria.Main.mapEnabled, Terraria.Main.maxMenuItems, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.mcColor, Terraria.Lang.menu, Terraria.UI.Gamepad.GamepadMainMenuHandler.MenuItemPositions, Terraria.Main.menuItemScale, Terraria.ModLoader.MenuLoader.MenuJourneysEnd, Terraria.Main.menuMode, Terraria.Main.menuMultiplayer, Terraria.ModLoader.MenuLoader.MenuOldVanilla, Terraria.ID.SoundID.MenuOpen, Terraria.Main.menuServer, Terraria.Main.MenuServerMode, Terraria.Main.menuSkip, Terraria.Main.MenuUI, Terraria.Main.menuWide, Terraria.Main.MenuXMovement, Terraria.Main.MinimapFrameManagerInstance, Terraria.Lang.misc, Terraria.Lighting.Mode, Terraria.ModLoader.UI.Interface.ModLoaderMenus(), Terraria.Main.MouseBorderColor, Terraria.Main.mouseBorderColorSlider, Terraria.Main.mouseColor, Terraria.Main.mouseColorSlider, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseMiddle, Terraria.Main.mouseMiddleRelease, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.MouseShowBuildingGrid, Terraria.Main.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseXButton1, Terraria.Main.mouseXButton1Release, Terraria.Main.mouseXButton2, Terraria.Main.mouseXButton2Release, Terraria.Main.mouseY, Terraria.Utilities.FileUtilities.Move(), Terraria.Main.musicVolume, Terraria.Main.netMode, Terraria.Social.SocialAPI.Network, Terraria.Lighting.NextLightMode(), Terraria.Main.numDisplayModes, Terraria.Main.OnCharacterNamed(), Terraria.Main.OnEngineLoad, Terraria.Main.OnSeedSelected(), Terraria.Main.OnSubmitServerIP(), Terraria.Main.OnSubmitServerPassword(), Terraria.Main.OnSubmitServerPasswordFromRequest(), Terraria.Main.OnSubmitServerPort(), Terraria.Main.OnWorldNamed(), Terraria.Main.OpenCharacterSelectUI(), Terraria.Utils.OpenFolder(), Terraria.Main.OurFavoriteColor, Terraria.Main.PendingBorderlessState, Terraria.Main.PendingPlayer, Terraria.Main.PendingResolutionHeight, Terraria.Main.PendingResolutionWidth, Terraria.Main.placementPreview, Terraria.Main.PlayerList, Terraria.Main.PlayerRenderer, Terraria.Main.playOldTile, Terraria.Audio.SoundEngine.PlaySound(), Terraria.WorldGen.playWorld(), Terraria.Main.pumpkinMoon, Terraria.Main.qaStyle, Terraria.Main.quickSplash, Terraria.Main.rand, Terraria.Main.randColor(), Terraria.Main.recentIP, Terraria.Main.recentPort, Terraria.Main.recentWorld, Terraria.Main.RejectionMenuInfo, Terraria.WorldGen.remixWorldGen, Terraria.Main.render, Terraria.Utils.Repeat(), Terraria.SceneMetrics.Reset(), Terraria.Main.ResetKeyBindings(), Terraria.Main.ResourceSetsManager, Terraria.Main.ReversedUpDownArmorSetBonuses, Terraria.Main.rgbToHsl(), Terraria.IngameOptions.rightHover, Terraria.IngameOptions.rightLock, Terraria.Main.SamplerStateForCursor, Terraria.Main.SaveSettings(), Terraria.Main.sBar, Terraria.Main.screenBorderless, Terraria.Main.screenBorderlessPendingResizes, Terraria.Main.screenHeight, Terraria.Main.screenLastPosition, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.selColor, Terraria.Main.selectedMenu, Terraria.Main.selectedMenu2, Terraria.Main.selectedPlayer, Terraria.Main.selectedWorld, Terraria.Netplay.ServerPassword, Terraria.Main.ServerSideCharacter, Terraria.Main.setKey, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Netplay.SetRemoteIPAsync(), Terraria.Main.SetResolution(), Terraria.Main.SettingsEnabled_MinersWobble, Terraria.Main.SettingsEnabled_TilesSwayInWind, Terraria.Main.SettingsUnlock_WorldEvil, Terraria.WorldGen.setWorldSize(), Terraria.GameInput.PlayerInput.SettingsForUI.ShowGamepadHints, Terraria.Main.showItemText, Terraria.Main.showServerConsole, Terraria.Main.showSpam, Terraria.GameContent.UI.BigProgressBar.BigProgressBarSystem.ShowText, Terraria.ModLoader.ModLoader.skipLoad, Terraria.Main.slimeRain, Terraria.Player.SmartCursorSettings.SmartAxeAfterPickaxe, Terraria.Player.SmartCursorSettings.SmartBlocksEnabled, Terraria.Main.snowMoon, Terraria.Main.soundVolume, Terraria.Main.spriteBatch, Terraria.Main.starGame, Terraria.Main.StartClientGameplay(), Terraria.Main.statusText, Terraria.Main.StopSlimeRain(), Terraria.Main.textBlinkerCount, Terraria.Main.textBlinkerState, Terraria.Main.tileColor, Terraria.ModLoader.Logging.tML, Terraria.Main.ToggleFullScreen(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarSystem.ToggleShowText(), Terraria.Main.tServer, Terraria.Main.UIScaleMatrix, Terraria.UI.Gamepad.GamepadMainMenuHandler.Update(), Terraria.ModLoader.MenuLoader.UpdateAndDrawModMenu(), Terraria.Cloud.UpdateClouds(), Terraria.Star.UpdateStars(), Terraria.Main.UseHeatDistortion, Terraria.GameInput.LockOnHelper.UseMode, Terraria.Main.UseStormEffects, Terraria.GameInput.PlayerInput.UsingGamepad, Terraria.IngameOptions.valuePosition, Terraria.Main.WaveQuality, Terraria.Main.WorldList, Terraria.Main.worldPathName, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DoDraw().