TModLoader: Terraria.Main.DrawCursor
DrawCursor()
static void Terraria.Main.DrawCursor (Vector2 bonus, bool smart = false) inline static
    {
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0311: Unknown result type (might be due to invalid IL or missing references)
        //IL_0316: Unknown result type (might be due to invalid IL or missing references)
        //IL_0317: Unknown result type (might be due to invalid IL or missing references)
        //IL_031c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0321: Unknown result type (might be due to invalid IL or missing references)
        //IL_036c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0378: Unknown result type (might be due to invalid IL or missing references)
        //IL_037e: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_0126: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0280: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0202: Unknown result type (might be due to invalid IL or missing references)
        //IL_0207: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_0222: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_0237: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_0256: Unknown result type (might be due to invalid IL or missing references)
        //IL_025b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        if (gameMenu && alreadyGrabbingSunOrMoon)
        {
            return;
        }
        if (player[myPlayer].dead || player[myPlayer].mouseInterface)
        {
            ClearSmartInteract();
            TileInteractionLX = (TileInteractionHX = (TileInteractionLY = (TileInteractionHY = -1)));
        }
        Color color = cursorColor;
        if (!gameMenu && LocalPlayer.hasRainbowCursor)
        {
            color = hslToRgb(GlobalTimeWrappedHourly * 0.25f % 1f, 1f, 0.5f);
        }
        bool flag = UILinkPointNavigator.Available && !PlayerInput.InBuildingMode;
        if (PlayerInput.SettingsForUI.ShowGamepadCursor)
        {
            if ((player[myPlayer].dead && !player[myPlayer].ghost && !gameMenu) || PlayerInput.InvisibleGamepadInMenus)
            {
                return;
            }
            Vector2 t = default(Vector2);
            ((Vector2)(ref t))._002Ector((float)mouseX, (float)mouseY);
            Vector2 t2 = Vector2.Zero;
            bool flag2 = SmartCursorIsUsed;
            if (flag2)
            {
                PlayerInput.smartSelectPointer.UpdateCenter(ScreenSize.ToVector2() / 2f);
                t2 = PlayerInput.smartSelectPointer.GetPointerPosition();
                if (Vector2.Distance(t2, t) < 1f)
                {
                    flag2 = false;
                }
                else
                {
                    Utils.Swap(ref t, ref t2);
                }
            }
            float num = 1f;
            if (flag2)
            {
                num = 0.3f;
                color = Color.White * GamepadCursorAlpha;
                int num2 = 17;
                int frameX = 0;
                spriteBatch.Draw(TextureAssets.Cursors[num2].Value, t2 + bonus, (Rectangle?)TextureAssets.Cursors[num2].Frame(1, 1, frameX), color, (float)Math.PI / 2f * GlobalTimeWrappedHourly, TextureAssets.Cursors[num2].Frame(1, 1, frameX).Size() / 2f, cursorScale, (SpriteEffects)0, 0f);
            }
            if (smart && !flag)
            {
                color = Color.White * GamepadCursorAlpha * num;
                int num3 = 13;
                int frameX2 = 0;
                spriteBatch.Draw(TextureAssets.Cursors[num3].Value, t + bonus, (Rectangle?)TextureAssets.Cursors[num3].Frame(2, 1, frameX2), color, 0f, TextureAssets.Cursors[num3].Frame(2, 1, frameX2).Size() / 2f, cursorScale, (SpriteEffects)0, 0f);
            }
            else
            {
                color = Color.White;
                int num4 = 15;
                spriteBatch.Draw(TextureAssets.Cursors[num4].Value, new Vector2((float)mouseX, (float)mouseY) + bonus, (Rectangle?)null, color, 0f, TextureAssets.Cursors[num4].Value.Size() / 2f, cursorScale, (SpriteEffects)0, 0f);
            }
        }
        else
        {
            int num5 = smart.ToInt();
            spriteBatch.Draw(TextureAssets.Cursors[num5].Value, new Vector2((float)mouseX, (float)mouseY) + bonus + Vector2.One, (Rectangle?)null, new Color((int)((float)(int)((Color)(ref color)).R * 0.2f), (int)((float)(int)((Color)(ref color)).G * 0.2f), (int)((float)(int)((Color)(ref color)).B * 0.2f), (int)((float)(int)((Color)(ref color)).A * 0.5f)), 0f, default(Vector2), cursorScale * 1.1f, (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.Cursors[num5].Value, new Vector2((float)mouseX, (float)mouseY) + bonus, (Rectangle?)null, color, 0f, default(Vector2), cursorScale, (SpriteEffects)0, 0f);
        }
    }
References Terraria.Main.alreadyGrabbingSunOrMoon, Terraria.Main.ClearSmartInteract(), Terraria.Graphics.Light.Color, Terraria.Main.cursorColor, Terraria.GameContent.TextureAssets.Cursors, Terraria.Main.cursorScale, Terraria.Main.gameMenu, Terraria.Main.GamepadCursorAlpha, Terraria.GameInput.SmartSelectGamepadPointer.GetPointerPosition(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Player.hasRainbowCursor, Terraria.Main.hslToRgb(), Terraria.GameInput.PlayerInput.InBuildingMode, Terraria.GameInput.PlayerInput.InvisibleGamepadInMenus, Terraria.Main.LocalPlayer, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.ScreenSize, Terraria.GameInput.PlayerInput.SettingsForUI.ShowGamepadCursor, Terraria.Main.SmartCursorIsUsed, Terraria.GameInput.PlayerInput.smartSelectPointer, Terraria.Main.spriteBatch, Terraria.Main.TileInteractionHX, Terraria.Main.TileInteractionHY, Terraria.Main.TileInteractionLX, Terraria.Main.TileInteractionLY, and Terraria.GameInput.SmartSelectGamepadPointer.UpdateCenter().
Referenced by Terraria.Main.DoDraw(), Terraria.UI.IngameFancyUI.Draw(), Terraria.Main.DrawInterface_36_Cursor(), Terraria.Main.DrawMap(), and Terraria.Main.DrawMenu().