TModLoader: Terraria.Main.PreDrawMenu
PreDrawMenu()
void Terraria.Main.PreDrawMenu (out Point screenSizeCache, out Point screenSizeCacheAfterScaling) inline private
Definition at line 66671 of file Main.cs.
    {
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        float uiScaleWanted = _uiScaleWanted;
        float num = (float)screenHeight / 900f;
        if (num < 1f)
        {
            num = 1f;
        }
        if (SettingDontScaleMainMenuUp)
        {
            num = 1f;
        }
        screenSizeCache = ScreenSize;
        UIScale = num;
        PlayerInput.SetZoom_UI();
        screenSizeCacheAfterScaling = ScreenSize;
        if (_needsMenuUIRecalculation)
        {
            _needsMenuUIRecalculation = false;
            MenuUI.Recalculate();
        }
        _uiScaleWanted = uiScaleWanted;
    }
References Terraria.Main._needsMenuUIRecalculation, Terraria.Main._uiScaleWanted, Terraria.Main.MenuUI, Terraria.UI.UserInterface.Recalculate(), Terraria.Main.screenHeight, Terraria.Main.ScreenSize, Terraria.Main.SettingDontScaleMainMenuUp, Terraria.GameInput.PlayerInput.SetZoom_UI(), and Terraria.Main.UIScale.
Referenced by Terraria.Main.DoDraw().