TModLoader: Terraria.Main.DrawInterface_33_MouseText
DrawInterface_33_MouseText()
void Terraria.Main.DrawInterface_33_MouseText () inline private
Definition at line 58541 of file Main.cs.
    {
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        SystemLoader.PostDrawInterface(spriteBatch);
        if (mouseItem.stack <= 0)
        {
            mouseItem.type = 0;
        }
        if (hoverItemName != null && hoverItemName != "" && mouseItem.type == 0)
        {
            player[myPlayer].cursorItemIconEnabled = false;
            if (SettingsEnabled_OpaqueBoxBehindTooltips)
            {
                MouseText(hoverItemName, rare, 0, mouseX + 6, mouseY + 6);
            }
            else
            {
                MouseText(hoverItemName, rare, 0);
            }
            mouseText = true;
        }
        if (LocalPlayer.rulerLine && LocalPlayer.builderAccStatus[0] == 0 && ((Vector2)(ref LocalPlayer.velocity)).Length() <= 6f)
        {
            int num = Math.Abs(rulerLineDisplayValues.X) + 1;
            int num2 = Math.Abs(rulerLineDisplayValues.Y) + 1;
            if (num > 1 || num2 > 1)
            {
                Utils.DrawBorderString(spriteBatch, num + "x" + num2, MouseScreen + new Vector2(16f, 0f), new Color(0.24f, 0.8f, 0.9f, 1f), GameZoomTarget, 0f, 0.8f);
            }
        }
        DrawInterface_InstrumentMouseText();
    }
References Terraria.Player.builderAccStatus, Terraria.Graphics.Light.Color, Terraria.Player.cursorItemIconEnabled, Terraria.Utils.DrawBorderString(), Terraria.Main.DrawInterface_InstrumentMouseText(), Terraria.Main.GameZoomTarget, Terraria.Main.hoverItemName, Terraria.Main.LocalPlayer, Terraria.Main.mouseItem, Terraria.Main.MouseScreen, Terraria.Main.mouseText, Terraria.Main.MouseText(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.ModLoader.SystemLoader.PostDrawInterface(), Terraria.Main.rare, Terraria.Player.rulerLine, Terraria.Main.rulerLineDisplayValues, Terraria.Main.SettingsEnabled_OpaqueBoxBehindTooltips, Terraria.Main.spriteBatch, Terraria.Item.stack, Terraria.Item.type, and Terraria.Entity.velocity.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().