TModLoader: Terraria.Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition
DrawMapIcons_PotionOfReturnAppearAfterUsePosition()
void Terraria.Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition (SpriteBatch spriteBatch, Vector2 mapTopLeft, Vector2 mapX2Y2AndOff, Rectangle? mapRect, float mapScale, float drawScale, ref string mouseTextString) inline private
Definition at line 71984 of file Main.cs.
    {
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00da: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0102: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        Vector2? potionOfReturnOriginalUsePosition = LocalPlayer.PotionOfReturnOriginalUsePosition;
        if (!potionOfReturnOriginalUsePosition.HasValue)
        {
            return;
        }
        Vector2? val = potionOfReturnOriginalUsePosition;
        Vector2 val2 = default(Vector2);
        ((Vector2)(ref val2))._002Ector(0f, (float)(-LocalPlayer.height / 2));
        Vector2 vec = (val.HasValue ? new Vector2?(val.GetValueOrDefault() + val2) : null).Value / 16f - mapTopLeft;
        vec *= mapScale;
        vec += mapX2Y2AndOff;
        vec = vec.Floor();
        Rectangle val3;
        if (mapRect.HasValue)
        {
            val3 = mapRect.Value;
            if (!((Rectangle)(ref val3)).Contains(vec.ToPoint()))
            {
                return;
            }
        }
        Texture2D value = TextureAssets.Extra[173].Value;
        Rectangle rectangle = value.Frame();
        spriteBatch.Draw(value, vec, (Rectangle?)rectangle, Color.White, 0f, rectangle.Size() / 2f, drawScale, (SpriteEffects)0, 0f);
        val3 = Utils.CenteredRectangle(vec, rectangle.Size() * drawScale);
        if (((Rectangle)(ref val3)).Contains(MouseScreen.ToPoint()))
        {
            mouseTextString = Language.GetTextValue("GameUI.PotionOfReturnExitPortal");
            _ = MouseScreen + new Vector2(-28f) + new Vector2(4f, 0f);
        }
    }
References Terraria.Utils.CenteredRectangle(), Terraria.Graphics.Light.Color, Terraria.GameContent.TextureAssets.Extra, Terraria.Localization.Language.GetTextValue(), Terraria.Main.LocalPlayer, Terraria.Main.MouseScreen, Terraria.Player.PotionOfReturnOriginalUsePosition, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawMiscMapIcons().