TModLoader: Terraria.Main.HandleIME
HandleIME()
void Terraria.Main.HandleIME () inline
Definition at line 52625 of file Main.cs.
    {
        if (_imeToggle != PlayerInput.WritingText)
        {
            _imeToggle = PlayerInput.WritingText;
            if (_imeToggle)
            {
                Platform.Get<IImeService>().Enable();
            }
            else
            {
                Platform.Get<IImeService>().Disable();
            }
        }
    }
References Terraria.Main._imeToggle, Terraria.Enums.Platform, and Terraria.GameInput.PlayerInput.WritingText.
Referenced by Terraria.Main.DrawMenu(), Terraria.Main.DrawPlayerChat(), Terraria.GameContent.UI.Elements.UISearchBar.DrawSelf(), Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf(), Terraria.ModLoader.UI.UIFocusInputTextField.DrawSelf(), Terraria.ModLoader.UI.UIInputTextField.DrawSelf(), and Terraria.Main.InputTextSign().