TModLoader: Terraria.Main.DrawTrashItemSlot
DrawTrashItemSlot()
static void Terraria.Main.DrawTrashItemSlot (int pivotTopLeftX, int pivotTopLeftY) inline static private
    {
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        inventoryScale = 0.85f;
        int num = 448 + pivotTopLeftX;
        int num2 = 258 + pivotTopLeftY;
        if ((player[myPlayer].chest != -1 || npcShop > 0) && !recBigList)
        {
            num2 += 168;
            inventoryScale = 0.755f;
            num += 5;
        }
        else if ((player[myPlayer].chest == -1 || npcShop == -1) && trashSlotOffset != Point16.Zero)
        {
            num += trashSlotOffset.X;
            num2 += trashSlotOffset.Y;
            inventoryScale = 0.755f;
        }
        new Color(150, 150, 150, 150);
        if (mouseX >= num && (float)mouseX <= (float)num + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= num2 && (float)mouseY <= (float)num2 + (float)TextureAssets.InventoryBack.Height() * inventoryScale && !PlayerInput.IgnoreMouseInterface)
        {
            player[myPlayer].mouseInterface = true;
            ItemSlot.LeftClick(ref player[myPlayer].trashItem, 6);
            if (mouseLeftRelease && mouseLeft)
            {
                Recipe.FindRecipes();
            }
            ItemSlot.MouseHover(ref player[myPlayer].trashItem, 6);
        }
        ItemSlot.Draw(spriteBatch, ref player[myPlayer].trashItem, 6, new Vector2((float)num, (float)num2));
    }
References Terraria.Main.chest, Terraria.Graphics.Light.Color, Terraria.UI.ItemSlot.Draw(), Terraria.Recipe.FindRecipes(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.Main.inventoryScale, Terraria.UI.ItemSlot.LeftClick(), Terraria.UI.ItemSlot.MouseHover(), Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.npcShop, Terraria.Main.player, Terraria.Main.recBigList, Terraria.Main.spriteBatch, Terraria.Main.trashSlotOffset, Terraria.DataStructures.Point16.X, Terraria.DataStructures.Point16.Y, and Terraria.DataStructures.Point16.Zero.
Referenced by Terraria.Main.DrawInventory().