TModLoader: Terraria.Main.TeleportEffect
TeleportEffect()
static void Terraria.Main.TeleportEffect (Rectangle effectRect, int Style, int extraInfo = 0, float dustCountMult = 1f, TeleportationSide side = TeleportationSide::Entry, Vector2 otherPosition = default(Vector2)) inline static
    {
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0481: Unknown result type (might be due to invalid IL or missing references)
        //IL_0487: Unknown result type (might be due to invalid IL or missing references)
        //IL_0490: Unknown result type (might be due to invalid IL or missing references)
        //IL_0496: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0550: Unknown result type (might be due to invalid IL or missing references)
        //IL_0551: Unknown result type (might be due to invalid IL or missing references)
        //IL_0556: Unknown result type (might be due to invalid IL or missing references)
        //IL_0625: Unknown result type (might be due to invalid IL or missing references)
        //IL_0626: Unknown result type (might be due to invalid IL or missing references)
        //IL_062b: Unknown result type (might be due to invalid IL or missing references)
        //IL_076b: Unknown result type (might be due to invalid IL or missing references)
        //IL_076d: Unknown result type (might be due to invalid IL or missing references)
        //IL_076e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0773: Unknown result type (might be due to invalid IL or missing references)
        //IL_0778: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a28: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        //IL_019b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        //IL_0257: Unknown result type (might be due to invalid IL or missing references)
        //IL_025c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0262: Unknown result type (might be due to invalid IL or missing references)
        //IL_0279: Unknown result type (might be due to invalid IL or missing references)
        //IL_028a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0294: Unknown result type (might be due to invalid IL or missing references)
        //IL_0299: Unknown result type (might be due to invalid IL or missing references)
        //IL_02eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0304: Unknown result type (might be due to invalid IL or missing references)
        //IL_031c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0322: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0503: Unknown result type (might be due to invalid IL or missing references)
        //IL_0508: Unknown result type (might be due to invalid IL or missing references)
        //IL_056a: Unknown result type (might be due to invalid IL or missing references)
        //IL_056c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0572: Unknown result type (might be due to invalid IL or missing references)
        //IL_058d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0593: Unknown result type (might be due to invalid IL or missing references)
        //IL_0614: Unknown result type (might be due to invalid IL or missing references)
        //IL_0619: Unknown result type (might be due to invalid IL or missing references)
        //IL_063f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0641: Unknown result type (might be due to invalid IL or missing references)
        //IL_0647: Unknown result type (might be due to invalid IL or missing references)
        //IL_065f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0665: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_071b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0739: Unknown result type (might be due to invalid IL or missing references)
        //IL_0745: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07de: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_091f: Unknown result type (might be due to invalid IL or missing references)
        //IL_092b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0951: Unknown result type (might be due to invalid IL or missing references)
        //IL_0956: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a46: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a82: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0983: Unknown result type (might be due to invalid IL or missing references)
        //IL_0988: Unknown result type (might be due to invalid IL or missing references)
        //IL_098c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0991: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aaf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0998: Unknown result type (might be due to invalid IL or missing references)
        //IL_0999: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_09dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0358: Unknown result type (might be due to invalid IL or missing references)
        //IL_0362: Unknown result type (might be due to invalid IL or missing references)
        //IL_0367: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0397: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0861: Unknown result type (might be due to invalid IL or missing references)
        //IL_0866: Unknown result type (might be due to invalid IL or missing references)
        //IL_086d: Unknown result type (might be due to invalid IL or missing references)
        //IL_087c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0881: Unknown result type (might be due to invalid IL or missing references)
        //IL_0886: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03da: Unknown result type (might be due to invalid IL or missing references)
        //IL_03df: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ff: Unknown result type (might be due to invalid IL or missing references)
        switch (Style)
        {
        case 0:
        {
            SoundEngine.PlaySound(SoundID.Item6, effectRect.X + effectRect.Width / 2, effectRect.Y + effectRect.Height / 2);
            int num12 = effectRect.Width * effectRect.Height / 5;
            num12 = (int)((float)num12 * dustCountMult);
            for (int j = 0; j < num12; j++)
            {
                int num14 = Dust.NewDust(new Vector2((float)effectRect.X, (float)effectRect.Y), effectRect.Width, effectRect.Height, 159);
                Main.dust[num14].scale = (float)rand.Next(20, 70) * 0.01f;
                if (j < 10)
                {
                    Main.dust[num14].scale += 0.25f;
                }
                if (j < 5)
                {
                    Main.dust[num14].scale += 0.25f;
                }
            }
            break;
        }
        case 1:
        {
            SoundEngine.PlaySound(SoundID.Item8, effectRect.X + effectRect.Width / 2, effectRect.Y + effectRect.Height / 2);
            int num2 = effectRect.Width * effectRect.Height / 5;
            num2 = (int)((float)num2 * dustCountMult);
            for (int num3 = 0; num3 < num2; num3++)
            {
                int num4 = Dust.NewDust(new Vector2((float)effectRect.X, (float)effectRect.Y), effectRect.Width, effectRect.Height, 164);
                Main.dust[num4].scale = (float)rand.Next(20, 70) * 0.01f;
                if (num3 < 10)
                {
                    Main.dust[num4].scale += 0.25f;
                }
                if (num3 < 5)
                {
                    Main.dust[num4].scale += 0.25f;
                }
            }
            break;
        }
        case 2:
        {
            int num7 = (int)(50f * dustCountMult);
            for (int num8 = 0; num8 < num7; num8++)
            {
                Dust obj9 = Main.dust[Dust.NewDust(new Vector2((float)effectRect.X, (float)effectRect.Y), effectRect.Width, effectRect.Height, 58, 0f, 0f, 150, Color.GhostWhite, 1.2f)];
                obj9.velocity *= 0.5f;
            }
            break;
        }
        case 3:
        {
            SoundEngine.PlaySound(SoundID.Item6, effectRect.X + effectRect.Width / 2, effectRect.Y + effectRect.Height / 2);
            int num16 = (int)(50f * dustCountMult);
            for (int l = 0; l < num16; l++)
            {
                int num17 = Dust.NewDust(new Vector2((float)effectRect.X, (float)effectRect.Y), effectRect.Width, effectRect.Height, 180);
                Main.dust[num17].noGravity = true;
                for (int m = 0; m < 5; m++)
                {
                    if (rand.Next(3) == 0)
                    {
                        Dust obj4 = Main.dust[num17];
                        obj4.velocity *= 0.75f;
                    }
                }
                if (rand.Next(3) == 0)
                {
                    Dust obj5 = Main.dust[num17];
                    obj5.velocity *= 2f;
                    Main.dust[num17].scale *= 1.2f;
                }
                if (rand.Next(3) == 0)
                {
                    Dust obj6 = Main.dust[num17];
                    obj6.velocity *= 2f;
                    Main.dust[num17].scale *= 1.2f;
                }
                if (rand.Next(2) == 0)
                {
                    Main.dust[num17].fadeIn = (float)rand.Next(75, 100) * 0.01f;
                    Main.dust[num17].scale = (float)rand.Next(25, 75) * 0.01f;
                }
                Main.dust[num17].scale *= 0.8f;
            }
            break;
        }
        case 4:
        {
            SoundEngine.PlaySound(SoundID.Item8, effectRect.X + effectRect.Width / 2, effectRect.Y + effectRect.Height / 2);
            int num9 = effectRect.Width * effectRect.Height / 5;
            num9 = (int)((float)num9 * dustCountMult);
            for (int num10 = 0; num10 < num9; num10++)
            {
                Dust obj10 = Main.dust[Dust.NewDust(effectRect.TopLeft(), effectRect.Width, effectRect.Height, 263)];
                obj10.color = PortalHelper.GetPortalColor(extraInfo);
                obj10.noLight = true;
                obj10.noGravity = true;
                obj10.scale = 1.2f;
                obj10.fadeIn = 0.4f;
                ((Color)(ref obj10.color)).A = byte.MaxValue;
            }
            break;
        }
        case 5:
        {
            Vector2 position = effectRect.TopLeft();
            int num19 = (int)(100f * dustCountMult);
            for (int num20 = 0; num20 < num19; num20++)
            {
                Dust obj8 = Dust.NewDustDirect(position, effectRect.Width, effectRect.Height + 24, Dust.dustWater());
                obj8.velocity.Y *= 0f;
                obj8.velocity.Y -= 3.5f;
                obj8.velocity.X *= 1.5f;
                obj8.scale = 0.8f;
                obj8.alpha = 130;
                obj8.noGravity = true;
                obj8.fadeIn = 1.2f;
            }
            SoundEngine.PlaySound(19, ((Rectangle)(ref effectRect)).Center.ToVector2(), 0);
            break;
        }
        case 7:
        {
            Vector2 position2 = effectRect.TopLeft();
            int num11 = (int)(50f * dustCountMult);
            for (int num13 = 0; num13 < num11; num13++)
            {
                Dust obj11 = Dust.NewDustDirect(position2, effectRect.Width, effectRect.Height + 24, 35);
                obj11.velocity.Y *= 0f;
                obj11.velocity.Y -= 3.5f;
                obj11.velocity.X *= 1.5f;
                obj11.scale = 0.8f;
                obj11.alpha = 130;
                obj11.noGravity = true;
                obj11.fadeIn = 1.2f;
            }
            SoundEngine.PlaySound(in SoundID.Item8, ((Rectangle)(ref effectRect)).Center.ToVector2());
            break;
        }
        case 9:
        {
            ((Rectangle)(ref effectRect)).Inflate(15, 15);
            int num5 = (int)(100f * dustCountMult);
            for (int num6 = 0; num6 < num5; num6++)
            {
                TeleportPylonsSystem.SpawnInWorldDust(extraInfo, effectRect);
            }
            SoundEngine.PlaySound(SoundID.Item6, ((Rectangle)(ref effectRect)).Center.X, ((Rectangle)(ref effectRect)).Center.Y);
            break;
        }
        case 10:
        {
            ((Rectangle)(ref effectRect)).Inflate(15, 15);
            int num18 = (int)(60f * dustCountMult);
            Vector2 vector = otherPosition - effectRect.TopLeft();
            for (int n = 0; n < num18; n++)
            {
                float fadeIn = 0.4f + rand.NextFloat();
                float scale = 0.4f + rand.NextFloat();
                Color newColor = hslToRgb(0.66f + rand.NextFloat() * 0.24f, 1f, 0.5f);
                Dust dust = Dust.NewDustDirect(effectRect.TopLeft(), effectRect.Width, effectRect.Height, 267, 0f, 0f, 127, newColor);
                dust.scale = (float)rand.Next(20, 70) * 0.01f;
                if (n < 10)
                {
                    dust.scale += 0.25f;
                }
                if (n < 5)
                {
                    dust.scale += 0.25f;
                }
                if ((float)n < (float)num18 * 0.8f)
                {
                    dust.velocity += vector * 0.1f * rand.NextFloat();
                }
                dust.noGravity = true;
                dust.noLight = true;
                dust.scale = scale;
                dust.fadeIn = fadeIn;
                if (dust.dustIndex != 6000)
                {
                    Dust obj7 = Dust.CloneDust(dust);
                    obj7.scale *= 0.65f;
                    obj7.fadeIn *= 0.65f;
                    obj7.color = new Color(255, 255, 255, 255);
                }
            }
            SoundEngine.PlaySound(SoundID.Item8, ((Rectangle)(ref effectRect)).Center.X, ((Rectangle)(ref effectRect)).Center.Y);
            break;
        }
        case 11:
        {
            for (int k = 0; k < 50; k++)
            {
                int num15 = rand.Next(4);
                Color color = Color.Green;
                switch (num15)
                {
                case 0:
                case 1:
                    ((Color)(ref color))._002Ector(100, 255, 100);
                    break;
                case 2:
                    color = Color.Yellow;
                    break;
                case 3:
                    color = Color.White;
                    break;
                }
                Dust obj3 = Dust.NewDustPerfect(rand.NextVector2FromRectangle(effectRect), 267);
                obj3.noGravity = true;
                obj3.color = color;
                obj3.velocity *= 2f;
                obj3.scale = 0.8f + rand.NextFloat() * 0.6f;
                obj3.fadeIn = 0.5f;
            }
            break;
        }
        case 13:
        {
            SoundEngine.PlaySound(in SoundID.Item8, ((Rectangle)(ref effectRect)).Center.ToVector2());
            for (int i = 0; i < 21; i++)
            {
                int num = Dust.NewDust(rand.NextVector2FromRectangle(effectRect), 2, 2, 27, 0f, 0f, 100, default(Color), rand.Next(1, 3));
                Dust obj = Main.dust[num];
                obj.velocity *= 1.75f;
                if (i % 3 == 0)
                {
                    Dust obj2 = Main.dust[num];
                    obj2.velocity *= 1.5f;
                }
                Main.dust[num].noLightEmittence = true;
                Main.dust[num].noGravity = true;
            }
            break;
        }
        case 6:
        case 8:
        case 12:
            break;
        }
    }
References Terraria.Dust.CloneDust(), Terraria.Graphics.Light.Color, Terraria.Main.dust, Terraria.Dust.dustIndex, Terraria.Dust.dustWater(), Terraria.Dust.fadeIn, Terraria.GameContent.PortalHelper.GetPortalColor(), Terraria.Main.hslToRgb(), Terraria.ID.SoundID.Item6, Terraria.ID.SoundID.Item8, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLightEmittence, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Dust.scale, and Terraria.GameContent.TeleportPylonsSystem.SpawnInWorldDust().
Referenced by Terraria.NPC.Teleport(), and Terraria.Player.Teleport().