TModLoader: Terraria.Main.DrawGore
DrawGore()
void Terraria.Main.DrawGore () inline protected
    {
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0202: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_0208: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0225: Unknown result type (might be due to invalid IL or missing references)
        //IL_022e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0365: Unknown result type (might be due to invalid IL or missing references)
        //IL_0371: Unknown result type (might be due to invalid IL or missing references)
        //IL_0376: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f7: Unknown result type (might be due to invalid IL or missing references)
        drawBackGore = false;
        Vector2 vector = default(Vector2);
        for (int i = 0; i < 600; i++)
        {
            if (!gore[i].active || gore[i].type <= 0)
            {
                continue;
            }
            if (GoreID.Sets.DrawBehind[gore[i].type])
            {
                if (gore[i].type < GoreID.Count)
                {
                    byte frame = gore[i].frame;
                    if (frame >= 7 && frame <= 9)
                    {
                        goto IL_0078;
                    }
                }
                drawBackGore = true;
                continue;
            }
            goto IL_0078;
            IL_0078:
            LoadGore(gore[i].type);
            if (gore[i].Frame.ColumnCount > 1 || gore[i].Frame.RowCount > 1)
            {
                Rectangle sourceRectangle = gore[i].Frame.GetSourceRectangle(TextureAssets.Gore[gore[i].type].Value);
                ((Vector2)(ref vector))._002Ector(0f, 0f);
                if (gore[i].type == 1217)
                {
                    vector.Y += 4f;
                }
                vector += gore[i].drawOffset;
                Color alpha = gore[i].GetAlpha(Lighting.GetColor((int)((double)gore[i].position.X + (double)sourceRectangle.Width * 0.5) / 16, (int)(((double)gore[i].position.Y + (double)sourceRectangle.Height * 0.5) / 16.0)));
                spriteBatch.Draw(TextureAssets.Gore[gore[i].type].Value, new Vector2(gore[i].position.X - screenPosition.X + (float)(sourceRectangle.Width / 2), gore[i].position.Y - screenPosition.Y + (float)(sourceRectangle.Height / 2) - 2f) + vector, (Rectangle?)sourceRectangle, alpha, gore[i].rotation, new Vector2((float)(sourceRectangle.Width / 2), (float)(sourceRectangle.Height / 2)), gore[i].scale, (SpriteEffects)0, 0f);
            }
            else
            {
                Color alpha2 = gore[i].GetAlpha(Lighting.GetColor((int)((double)gore[i].position.X + (double)TextureAssets.Gore[gore[i].type].Width() * 0.5) / 16, (int)(((double)gore[i].position.Y + (double)TextureAssets.Gore[gore[i].type].Height() * 0.5) / 16.0)));
                spriteBatch.Draw(TextureAssets.Gore[gore[i].type].Value, new Vector2(gore[i].position.X - screenPosition.X + (float)(TextureAssets.Gore[gore[i].type].Width() / 2), gore[i].position.Y - screenPosition.Y + (float)(TextureAssets.Gore[gore[i].type].Height() / 2)) + gore[i].drawOffset, (Rectangle?)new Rectangle(0, 0, TextureAssets.Gore[gore[i].type].Width(), TextureAssets.Gore[gore[i].type].Height()), alpha2, gore[i].rotation, new Vector2((float)(TextureAssets.Gore[gore[i].type].Width() / 2), (float)(TextureAssets.Gore[gore[i].type].Height() / 2)), gore[i].scale, (SpriteEffects)0, 0f);
            }
        }
        TimeLogger.DetailedDrawTime(24);
    }
References Terraria.ID.GoreID.Count, Terraria.TimeLogger.DetailedDrawTime(), Terraria.Main.drawBackGore, Terraria.ID.GoreID.Sets.DrawBehind, Terraria.Lighting.GetColor(), Terraria.GameContent.TextureAssets.Gore, Terraria.Main.gore, Terraria.Main.LoadGore(), Terraria.Main.screenPosition, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.DrawCapture().