TModLoader: Terraria.Main.HoverOverNPCs
HoverOverNPCs()
void Terraria.Main.HoverOverNPCs (Rectangle mouseRectangle) inline private
Definition at line 55537 of file Main.cs.
    {
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0137: Unknown result type (might be due to invalid IL or missing references)
        //IL_054f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0555: Unknown result type (might be due to invalid IL or missing references)
        //IL_055a: Unknown result type (might be due to invalid IL or missing references)
        //IL_055f: Unknown result type (might be due to invalid IL or missing references)
        //IL_038a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0537: Unknown result type (might be due to invalid IL or missing references)
        //IL_053d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0542: Unknown result type (might be due to invalid IL or missing references)
        //IL_0547: Unknown result type (might be due to invalid IL or missing references)
        //IL_051b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0521: Unknown result type (might be due to invalid IL or missing references)
        //IL_0526: Unknown result type (might be due to invalid IL or missing references)
        //IL_052b: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[myPlayer];
        Rectangle value = default(Rectangle);
        Rectangle rectangle = default(Rectangle);
        Rectangle value2 = default(Rectangle);
        for (int i = 0; i < 200; i++)
        {
            NPC nPC = npc[i];
            if (!nPC.ShowNameOnHover || !(nPC.active & (nPC.shimmerTransparency == 0f || nPC.CanApplyHunterPotionEffects())))
            {
                continue;
            }
            int type = nPC.type;
            LoadNPC(type);
            nPC.position += nPC.netOffset;
            ((Rectangle)(ref value))._002Ector((int)nPC.Bottom.X - nPC.frame.Width / 2, (int)nPC.Bottom.Y - nPC.frame.Height, nPC.frame.Width, nPC.frame.Height);
            if (nPC.type >= 87 && nPC.type <= 92)
            {
                ((Rectangle)(ref value))._002Ector((int)((double)nPC.position.X + (double)nPC.width * 0.5 - 32.0), (int)((double)nPC.position.Y + (double)nPC.height * 0.5 - 32.0), 64, 64);
            }
            NPCLoader.ModifyHoverBoundingBox(nPC, ref value);
            bool flag = ((Rectangle)(ref mouseRectangle)).Intersects(value);
            bool flag2 = flag || (SmartInteractShowingGenuine && SmartInteractNPC == i);
            if (flag2 && ((nPC.type != 85 && nPC.type != 341 && nPC.type != 629 && nPC.aiStyle != 87) || nPC.ai[0] != 0f) && nPC.type != 488)
            {
                if (nPC.type == 685)
                {
                    player.cursorItemIconEnabled = true;
                    player.cursorItemIconID = 327;
                    player.cursorItemIconText = "";
                    player.noThrow = 2;
                    if (!player.dead)
                    {
                        PlayerInput.SetZoom_MouseInWorld();
                        if (mouseRight && npcChatRelease)
{
                            npcChatRelease = false;
                            if (PlayerInput.UsingGamepad)
{
                                player.releaseInventory = false;
                            }
                            if (player.talkNPC != i && !player.tileInteractionHappened && TryFreeingElderSlime(i))
{
                                NPC.TransformElderSlime(i);
                                SoundEngine.PlaySound(22);
                            }
                        }
                    }
                }
                else
                {
                    bool flag3 = SmartInteractShowingGenuine && SmartInteractNPC == i;
                    bool vanillaCanChat = false;
                    if (nPC.townNPC || nPC.type == 105 || nPC.type == 106 || nPC.type == 123 || nPC.type == 354 || nPC.type == 376 || nPC.type == 579 || nPC.type == 453 || nPC.type == 589)
                    {
                        vanillaCanChat = true;
                    }
                    if (NPCLoader.CanChat(nPC) ?? vanillaCanChat)
                    {
                        ((Rectangle)(ref rectangle))._002Ector((int)(player.position.X + (float)(player.width / 2) - (float)(Player.tileRangeX * 16)), (int)(player.position.Y + (float)(player.height / 2) - (float)(Player.tileRangeY * 16)), Player.tileRangeX * 16 * 2, Player.tileRangeY * 16 * 2);
                        ((Rectangle)(ref value2))._002Ector((int)nPC.position.X, (int)nPC.position.Y, nPC.width, nPC.height);
                        if (((Rectangle)(ref rectangle)).Intersects(value2))
{
                            flag3 = true;
                        }
                    }
                    if (player.ownedProjectileCounts[651] > 0)
                    {
                        flag3 = false;
                    }
                    if (flag3 && !player.dead)
                    {
                        PlayerInput.SetZoom_MouseInWorld();
                        HoveringOverAnNPC = true;
                        currentNPCShowingChatBubble = i;
                        if (mouseRight && npcChatRelease)
{
                            npcChatRelease = false;
                            if (PlayerInput.UsingGamepad)
{
                                player.releaseInventory = false;
                            }
                            if (player.talkNPC != i && !player.tileInteractionHappened)
{
                                CancelHairWindow();
                                SetNPCShopIndex(0);
                                InGuideCraftMenu = false;
                                player.dropItemCheck();
                                npcChatCornerItem = 0;
                                player.sign = -1;
                                editSign = false;
                                player.SetTalkNPC(i);
                                playerInventory = false;
                                player.chest = -1;
                                Recipe.FindRecipes();
                                npcChatText = nPC.GetChat();
                                SoundEngine.PlaySound(24);
                            }
                        }
                    }
                    if (flag && !player.mouseInterface)
                    {
                        player.cursorItemIconEnabled = false;
                        string text = nPC.GivenOrTypeName;
                        int num = i;
                        if (nPC.realLife >= 0)
{
                            num = nPC.realLife;
                        }
                        if (npc[num].lifeMax > 1 && !npc[num].dontTakeDamage)
{
                            text = text + ": " + npc[num].life + "/" + npc[num].lifeMax;
                        }
                        MouseTextHackZoom(text);
                        mouseText = true;
                        nPC.position -= nPC.netOffset;
                        break;
                    }
                    if (flag2)
                    {
                        nPC.position -= nPC.netOffset;
                        break;
                    }
                }
            }
            nPC.position -= nPC.netOffset;
        }
    }
References Terraria.Main.CancelHairWindow(), Terraria.ModLoader.NPCLoader.CanChat(), Terraria.Main.currentNPCShowingChatBubble, Terraria.Player.dead, Terraria.Player.dropItemCheck(), Terraria.Main.editSign, Terraria.Recipe.FindRecipes(), Terraria.Entity.height, Terraria.Main.HoveringOverAnNPC, Terraria.Main.InGuideCraftMenu, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.Main.LoadNPC(), Terraria.ModLoader.NPCLoader.ModifyHoverBoundingBox(), Terraria.Player.mouseInterface, Terraria.Main.mouseRight, Terraria.Main.mouseText, Terraria.Main.MouseTextHackZoom(), Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Main.npcChatCornerItem, Terraria.Main.npcChatRelease, Terraria.Main.npcChatText, Terraria.Player.ownedProjectileCounts, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.SetNPCShopIndex(), Terraria.Player.SetTalkNPC(), Terraria.GameInput.PlayerInput.SetZoom_MouseInWorld(), Terraria.Main.SmartInteractNPC, Terraria.Main.SmartInteractShowingGenuine, Terraria.Player.talkNPC, Terraria.Player.tileInteractionHappened, Terraria.Player.tileRangeX, Terraria.Player.tileRangeY, Terraria.NPC.TransformElderSlime(), Terraria.Main.TryFreeingElderSlime(), Terraria.GameInput.PlayerInput.UsingGamepad, and Terraria.Entity.width.
Referenced by Terraria.Main.DrawMouseOver().