TModLoader: Terraria.Main.LoadContent
LoadContent()
override void Terraria.Main.LoadContent () inline protected
    {
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Expected O, but got Unknown
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Expected O, but got Unknown
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Expected O, but got Unknown
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Expected O, but got Unknown
        Asset<Texture2D>.DefaultValue = new Texture2D(((Game)this).GraphicsDevice, 1, 1)
        {
            Name = "Asynchronously-loaded Asset Dummy Texture (do not dispose or modify!)"
        };
        Asset<Texture2D>.DefaultValue.SetData<Color>((Color[])(object)new Color[1] { Color.Transparent });
        SoundEngine.Initialize();
        if (((IServiceProvider)((Game)this).Services).Get<IAssetRepository>() == null)
        {
            AssetInitializer.CreateAssetServices(((Game)this).Services);
        }
        Assets = ((IServiceProvider)((Game)this).Services).Get<IAssetRepository>();
        Assets.AssetLoadFailHandler = OnceFailedLoadingAnAsset;
        mapSectionTexture = new RenderTarget2D(((Game)this).GraphicsDevice, 200, 150);
        ShaderContentManager = new ContentManager(((Game)this).Content.ServiceProvider, ((Game)this).Content.RootDirectory);
        PixelShaderRef.Value = ShaderContentManager.Load<Effect>("PixelShader");
        VertexPixelShaderRef.Value = ShaderContentManager.Load<Effect>("PixelShader");
        TileShaderRef.Value = ShaderContentManager.Load<Effect>("TileShader");
        ScreenShaderRef.Value = ShaderContentManager.Load<Effect>("ScreenShader");
        spriteBatch = new SpriteBatch(((Game)this).GraphicsDevice);
        tileBatch = new TileBatch(((Game)this).GraphicsDevice);
        DebugDrawer = new BasicDebugDrawer(((Game)this).GraphicsDevice);
        GameViewMatrix = new SpriteViewMatrix(((Game)this).GraphicsDevice);
        BackgroundViewMatrix = new SpriteViewMatrix(((Game)this).GraphicsDevice);
        if (SoundEngine.IsAudioSupported)
        {
            audioSystem = new LegacyAudioSystem();
        }
        else
        {
            audioSystem = new DisabledAudioSystem();
        }
        AssetSourceController = new AssetSourceController(Assets, new IContentSource[1]
        {
            new XnaDirectContentSource(((TMLContentManager)(object)((Game)this).Content).RootDirectories)
        });
        VanillaContentValidator.Instance = new VanillaContentValidator("Terraria.IO.Data.ResourcePacksDefaultInfo.tsv");
        if (SocialAPI.Workshop != null)
        {
            SocialAPI.Workshop.LoadEarlyContent();
        }
        CaptureManager.Instance = new CaptureManager();
        AssetSourceController.UseResourcePacks(AssetInitializer.CreateResourcePackList((IServiceProvider)((Game)this).Services));
        AssetInitializer.LoadSplashAssets(asyncLoadForSounds: true);
        ChromaInitializer.Load();
        _gameContentLoadProcess = LoadContent_Deferred();
        Terraria.ModLoader.ModLoader.PrepareAssets();
    }
References Terraria.Main._gameContentLoadProcess, Terraria.Main.AssetSourceController, Terraria.Main.audioSystem, Terraria.Main.BackgroundViewMatrix, Terraria.Initializers.AssetInitializer.CreateAssetServices(), Terraria.Initializers.AssetInitializer.CreateResourcePackList(), Terraria.Main.DebugDrawer, Terraria.UI.Game, Terraria.Main.GameViewMatrix, Terraria.Audio.SoundEngine.Initialize(), Terraria.Audio.SoundEngine.IsAudioSupported, Terraria.Initializers.ChromaInitializer.Load(), Terraria.Main.LoadContent_Deferred(), Terraria.Initializers.AssetInitializer.LoadSplashAssets(), Terraria.Main.mapSectionTexture, Terraria.Main.OnceFailedLoadingAnAsset(), Terraria.ModLoader.ModLoader.PrepareAssets(), Terraria.Main.ShaderContentManager, Terraria.Main.spriteBatch, Terraria.Main.tileBatch, Terraria.GameContent.AssetSourceController.UseResourcePacks(), and Terraria.Social.SocialAPI.Workshop.