TModLoader: Terraria.Main.DoDraw_Tiles_Solid
DoDraw_Tiles_Solid()
void Terraria.Main.DoDraw_Tiles_Solid () inline private
Definition at line 80349 of file Main.cs.
    {
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        TilesRenderer.PreDrawTiles(solidLayer: true, !drawToScreen, intoRenderTargets: false);
        tileBatch.Begin(Rasterizer, Transform);
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
        try
        {
            if (drawToScreen)
            {
                DrawTiles(solidLayer: true, !drawToScreen, intoRenderTargets: false);
            }
            else
            {
                spriteBatch.Draw((Texture2D)(object)tileTarget, sceneTilePos - screenPosition, Color.White);
                TimeLogger.DetailedDrawTime(17);
            }
        }
        catch (Exception e)
        {
            TimeLogger.DrawException(e);
        }
        tileBatch.End();
        spriteBatch.End();
        DrawTileEntities(solidLayer: true, !drawToScreen, intoRenderTargets: false);
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
        try
        {
            player[myPlayer].hitReplace.DrawFreshAnimations(spriteBatch);
            player[myPlayer].hitTile.DrawFreshAnimations(spriteBatch);
        }
        catch (Exception e2)
        {
            TimeLogger.DrawException(e2);
        }
        spriteBatch.End();
    }
References Terraria.Graphics.TileBatch.Begin(), Terraria.Graphics.Light.Color, Terraria.Main.DefaultSamplerState, Terraria.TimeLogger.DetailedDrawTime(), Terraria.TimeLogger.DrawException(), Terraria.HitTile.DrawFreshAnimations(), Terraria.Main.DrawTileEntities(), Terraria.Main.DrawTiles(), Terraria.Main.drawToScreen, Terraria.Graphics.TileBatch.End(), Terraria.Player.hitReplace, Terraria.Player.hitTile, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.GameContent.Drawing.TileDrawing.PreDrawTiles(), Terraria.Main.Rasterizer, Terraria.Main.sceneTilePos, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.Main.tileBatch, Terraria.Main.TilesRenderer, Terraria.Main.tileTarget, and Terraria.Main.Transform.
Referenced by Terraria.Main.DoDraw_WallsTilesNPCs().