TModLoader: Terraria.Main.ExecuteCommand
ExecuteCommand()
static void Terraria.Main.ExecuteCommand (string text, CommandCaller commandCaller) inline static
Definition at line 5708 of file Main.cs.
    {
        //IL_0a27: Unknown result type (might be due to invalid IL or missing references)
        Console.Write(": ");
        string text2 = text;
        text = text.ToLower();
        try
        {
            if (text == Language.GetTextValue("CLI.Help_Command"))
            {
                Console.WriteLine(Language.GetTextValue("CLI.AvailableCommands"));
                Console.WriteLine("");
                List<string> list = new List<string>
                {
                    "Help", "Playing", "Clear", "Exit", "ExitNoSave", "Save", "Kick", "Ban", "Password", "SetPassword",
                    "Version", "Time", "Port", "MaxPlayers", "Say", "MOTD", "SetMOTD", "Dawn", "Noon", "Dusk",
                    "Midnight", "Settle", "Seed"
                };
                int num = 0;
                for (int i = 0; i < list.Count; i++)
                {
                    string text3 = (Language.Exists("CLI." + list[i] + "_Example") ? Language.GetTextValue("CLI." + list[i] + "_Example") : Language.GetTextValue("CLI." + list[i] + "_Command"));
                    if (text3.Length > num)
                    {
                        num = text3.Length;
                    }
                }
                List<Tuple<string, string>> modHelpList = CommandLoader.GetHelp(CommandType.Console);
                foreach (Tuple<string, string> entry2 in modHelpList)
                {
                    if (entry2.Item1.Length > num)
                    {
                        num = entry2.Item1.Length;
                    }
                }
                int num2 = (num + 1) / 8;
                for (int j = 0; j < list.Count; j++)
                {
                    string text4 = (Language.Exists("CLI." + list[j] + "_Example") ? Language.GetTextValue("CLI." + list[j] + "_Example") : Language.GetTextValue("CLI." + list[j] + "_Command"));
                    Console.WriteLine(text4 + new string('\t', num2 - text4.Length / 8) + Language.GetTextValue("CLI." + list[j] + "_Description"));
                }
                {
                    foreach (Tuple<string, string> entry in modHelpList)
                    {
                        Console.WriteLine(entry.Item1 + new string('\t', num2 - entry.Item1.Length / 8) + entry.Item2);
                    }
                    return;
                }
            }
            if (CommandLoader.HandleCommand(text, commandCaller))
            {
                return;
            }
            if (text == Language.GetTextValue("CLI.Settle_Command"))
            {
                if (!Liquid.panicMode)
                {
                    Liquid.StartPanic();
                }
                else
                {
                    Console.WriteLine(Language.GetTextValue("CLI.WaterIsAlreadySettling"));
                }
                return;
            }
            if (text == Language.GetTextValue("CLI.Dawn_Command"))
            {
                dayTime = true;
                time = 0.0;
                NetMessage.SendData(7);
                return;
            }
            if (text == Language.GetTextValue("CLI.Dusk_Command"))
            {
                dayTime = false;
                time = 0.0;
                NetMessage.SendData(7);
                return;
            }
            if (text == Language.GetTextValue("CLI.Noon_Command"))
            {
                dayTime = true;
                time = 27000.0;
                NetMessage.SendData(7);
                return;
            }
            if (text == Language.GetTextValue("CLI.Midnight_Command"))
            {
                dayTime = false;
                time = 16200.0;
                NetMessage.SendData(7);
                return;
            }
            if (text == Language.GetTextValue("CLI.ExitNoSave_Command"))
            {
                Netplay.SaveOnServerExit = false;
                Netplay.Disconnect = true;
                return;
            }
            if (text == Language.GetTextValue("CLI.Exit_Command"))
            {
                Netplay.Disconnect = true;
                SocialAPI.Shutdown();
                return;
            }
            if (text == Language.GetTextValue("CLI.FPS_Command"))
            {
                if (!dedServFPS)
                {
                    dedServFPS = true;
                    fpsTimer.Reset();
                }
                else
                {
                    dedServCount1 = 0;
                    dedServCount2 = 0;
                    dedServFPS = false;
                }
                return;
            }
            if (text == Language.GetTextValue("CLI.Save_Command"))
            {
                WorldFile.SaveWorld();
                return;
            }
            if (text == Language.GetTextValue("CLI.Time_Command"))
            {
                string textValue = Language.GetTextValue("GameUI.TimeAtMorning");
                double num3 = time;
                if (!dayTime)
                {
                    num3 += 54000.0;
                }
                num3 = num3 / 86400.0 * 24.0;
                double num4 = 7.5;
                num3 = num3 - num4 - 12.0;
                if (num3 < 0.0)
                {
                    num3 += 24.0;
                }
                if (num3 >= 12.0)
                {
                    textValue = Language.GetTextValue("GameUI.TimePastMorning");
                }
                int num5 = (int)num3;
                double num7 = (int)((num3 - (double)num5) * 60.0);
                string text5 = string.Concat(num7);
                if (num7 < 10.0)
                {
                    text5 = "0" + text5;
                }
                if (num5 > 12)
                {
                    num5 -= 12;
                }
                if (num5 == 0)
                {
                    num5 = 12;
                }
                Console.WriteLine(Language.GetTextValue("CLI.Time", num5 + ":" + text5 + " " + textValue));
                return;
            }
            if (text == Language.GetTextValue("CLI.MaxPlayers_Command"))
            {
                Console.WriteLine(Language.GetTextValue("CLI.PlayerLimit", maxNetPlayers));
                return;
            }
            if (text == Language.GetTextValue("CLI.Port_Command"))
            {
                Console.WriteLine(Language.GetTextValue("CLI.Port", Netplay.ListenPort));
                return;
            }
            if (text == Language.GetTextValue("CLI.Version_Command"))
            {
                Console.WriteLine(Language.GetTextValue("CLI.Server", versionNumber) + " - " + Terraria.ModLoader.ModLoader.versionedName);
                return;
            }
            if (text == Language.GetTextValue("CLI.Clear_Command"))
            {
                try
                {
                    Console.Clear();
                    Logging.ResetPastExceptions();
                    return;
                }
                catch
                {
                    return;
                }
            }
            if (text == Language.GetTextValue("CLI.Playing_Command"))
            {
                int num6 = 0;
                for (int k = 0; k < 255; k++)
                {
                    if (player[k].active)
                    {
                        num6++;
                        Console.WriteLine(string.Concat(player[k].name, " (", Netplay.Clients[k].Socket.GetRemoteAddress(), ")"));
                    }
                }
                switch (num6)
                {
                case 0:
                    Console.WriteLine(Language.GetTextValue("CLI.NoPlayers"));
                    break;
                case 1:
                    Console.WriteLine(Language.GetTextValue("CLI.OnePlayerConnected"));
                    break;
                default:
                    Console.WriteLine(Language.GetTextValue("CLI.PlayersConnected", num6));
                    break;
                }
            }
            else
            {
                if (text == "")
                {
                    return;
                }
                if (text == Language.GetTextValue("CLI.MOTD_Command"))
                {
                    if (motd == "")
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.NoMOTD", worldName));
                    }
                    else
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.MOTD", motd));
                    }
                }
                else if (text.StartsWith(Language.GetTextValue("CLI.SetMOTD_Command") + " "))
                {
                    motd = text2.Substring(Language.GetTextValue("CLI.SetMOTD_Command").Length + 1);
                }
                else if (text == Language.GetTextValue("CLI.Password_Command"))
                {
                    if (Netplay.ServerPassword == "")
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.NoPassword"));
                    }
                    else
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.Password", Netplay.ServerPassword));
                    }
                }
                else if (text.StartsWith(Language.GetTextValue("CLI.SetPassword_Command") + " "))
                {
                    string text6 = text2.Substring(Language.GetTextValue("CLI.SetPassword_Command").Length + 1);
                    if (text6 == "")
                    {
                        Netplay.ServerPassword = "";
                        Console.WriteLine(Language.GetTextValue("CLI.PasswordDisabled"));
                    }
                    else
                    {
                        Netplay.ServerPassword = text6;
                        Console.WriteLine(Language.GetTextValue("CLI.PasswordSet", Netplay.ServerPassword));
                    }
                }
                else if (text == Language.GetTextValue("CLI.Say_Command"))
                {
                    Console.WriteLine(Language.GetTextValue("CLI.Say_Usage"));
                }
                else if (text.StartsWith(Language.GetTextValue("CLI.Say_Command") + " "))
                {
                    int length = Language.GetTextValue("CLI.Say_Command").Length;
                    if (text.Length <= length + 1)
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.Say_Usage"));
                        return;
                    }
                    string text7 = text2.Substring(length + 1);
                    Console.WriteLine(Language.GetTextValue("CLI.ServerMessage", text7));
                    ChatHelper.BroadcastChatMessage(NetworkText.FromKey("CLI.ServerMessage", text7), new Color(255, 240, 20));
                }
                else if (text == Language.GetTextValue("CLI.Kick_Command"))
                {
                    Console.WriteLine(Language.GetTextValue("CLI.Kick_Usage"));
                }
                else if (text.StartsWith(Language.GetTextValue("CLI.Kick_Command") + " "))
                {
                    int length2 = Language.GetTextValue("CLI.Kick_Command").Length;
                    if (text.Length <= length2 + 1)
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.Kick_Usage"));
                        return;
                    }
                    string text8 = text.Substring(length2 + 1);
                    text8 = text8.ToLower();
                    for (int l = 0; l < 255; l++)
                    {
                        if (player[l].active && player[l].name.ToLower() == text8)
{
                            NetMessage.SendData(2, l, -1, NetworkText.FromKey("CLI.KickMessage"));
                        }
                    }
                }
                else if (text == Language.GetTextValue("CLI.Seed_Command"))
                {
                    if (ActiveWorldFileData == null || !ActiveWorldFileData.HasValidSeed)
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.NoValidSeed"));
                    }
                    else
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.DisplaySeed", ActiveWorldFileData.GetFullSeedText()));
                    }
                }
                else if (text == Language.GetTextValue("CLI.Ban_Command"))
                {
                    Console.WriteLine(Language.GetTextValue("CLI.Ban_Usage"));
                }
                else if (text.StartsWith(Language.GetTextValue("CLI.Ban_Command") + " "))
                {
                    int length3 = Language.GetTextValue("CLI.Ban_Command").Length;
                    if (text.Length <= length3 + 1)
                    {
                        Console.WriteLine(Language.GetTextValue("CLI.Ban_Usage"));
                        return;
                    }
                    string text9 = text.Substring(4);
                    text9 = text9.ToLower();
                    for (int m = 0; m < 255; m++)
                    {
                        if (player[m].active && player[m].name.ToLower() == text9)
{
                            Netplay.AddBan(m);
                            NetMessage.SendData(2, m, -1, NetworkText.FromKey("CLI.BanMessage"));
                        }
                    }
                }
                else
                {
                    Console.WriteLine(Language.GetTextValue("CLI.InvalidCommand"));
                }
            }
        }
        catch
        {
            Console.WriteLine(Language.GetTextValue("CLI.InvalidCommand"));
        }
    }
References Terraria.Main.ActiveWorldFileData, Terraria.Netplay.AddBan(), Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Netplay.Clients, Terraria.Graphics.Light.Color, Terraria.ModLoader.Console, Terraria.Main.dayTime, Terraria.Main.dedServCount1, Terraria.Main.dedServCount2, Terraria.Main.dedServFPS, Terraria.Localization.Language.Exists(), Terraria.Main.fpsTimer, Terraria.Localization.NetworkText.FromKey(), Terraria.ModLoader.CommandLoader.GetHelp(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.CommandLoader.HandleCommand(), Terraria.Netplay.ListenPort, Terraria.Main.maxNetPlayers, Terraria.Main.motd, Terraria.Liquid.panicMode, Terraria.Main.player, Terraria.ModLoader.Logging.ResetPastExceptions(), Terraria.IO.WorldFile.SaveWorld(), Terraria.NetMessage.SendData(), Terraria.Netplay.ServerPassword, Terraria.Social.SocialAPI.Shutdown(), Terraria.Liquid.StartPanic(), Terraria.Main.time, Terraria.ModLoader.ModLoader.versionedName, Terraria.Main.versionNumber, and Terraria.Main.worldName.
Referenced by Terraria.Main.startDedInputCallBack().