TModLoader: Terraria.Main.DrawNPCChatButtons
DrawNPCChatButtons()
static void Terraria.Main.DrawNPCChatButtons (int superColor, Color chatColor, int numLines, string focusText, string focusText3) inline static private
Definition at line 52045 of file Main.cs.
    {
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_0158: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0164: Unknown result type (might be due to invalid IL or missing references)
        //IL_0169: Unknown result type (might be due to invalid IL or missing references)
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0212: Unknown result type (might be due to invalid IL or missing references)
        //IL_0214: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_025a: Unknown result type (might be due to invalid IL or missing references)
        //IL_025c: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0262: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0273: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0294: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0303: Unknown result type (might be due to invalid IL or missing references)
        //IL_0308: Unknown result type (might be due to invalid IL or missing references)
        //IL_0315: Unknown result type (might be due to invalid IL or missing references)
        //IL_0311: Unknown result type (might be due to invalid IL or missing references)
        //IL_031f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0326: Unknown result type (might be due to invalid IL or missing references)
        //IL_032b: Unknown result type (might be due to invalid IL or missing references)
        //IL_032d: Unknown result type (might be due to invalid IL or missing references)
        //IL_032f: Unknown result type (might be due to invalid IL or missing references)
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_0355: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0361: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0394: Unknown result type (might be due to invalid IL or missing references)
        //IL_039b: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03db: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0400: Unknown result type (might be due to invalid IL or missing references)
        //IL_0402: Unknown result type (might be due to invalid IL or missing references)
        //IL_0404: Unknown result type (might be due to invalid IL or missing references)
        //IL_0406: Unknown result type (might be due to invalid IL or missing references)
        //IL_0408: Unknown result type (might be due to invalid IL or missing references)
        //IL_040d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0414: Unknown result type (might be due to invalid IL or missing references)
        //IL_0419: Unknown result type (might be due to invalid IL or missing references)
        //IL_043a: Unknown result type (might be due to invalid IL or missing references)
        //IL_043e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0443: Unknown result type (might be due to invalid IL or missing references)
        //IL_0494: Unknown result type (might be due to invalid IL or missing references)
        //IL_0496: Unknown result type (might be due to invalid IL or missing references)
        //IL_0498: Unknown result type (might be due to invalid IL or missing references)
        //IL_049a: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_054f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0556: Unknown result type (might be due to invalid IL or missing references)
        //IL_055d: Unknown result type (might be due to invalid IL or missing references)
        //IL_056d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0582: Unknown result type (might be due to invalid IL or missing references)
        //IL_0594: Unknown result type (might be due to invalid IL or missing references)
        //IL_059b: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0602: Unknown result type (might be due to invalid IL or missing references)
        //IL_0606: Unknown result type (might be due to invalid IL or missing references)
        //IL_060b: Unknown result type (might be due to invalid IL or missing references)
        //IL_065c: Unknown result type (might be due to invalid IL or missing references)
        //IL_065e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0660: Unknown result type (might be due to invalid IL or missing references)
        //IL_0662: Unknown result type (might be due to invalid IL or missing references)
        //IL_066c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0671: Unknown result type (might be due to invalid IL or missing references)
        //IL_0676: Unknown result type (might be due to invalid IL or missing references)
        //IL_0683: Unknown result type (might be due to invalid IL or missing references)
        //IL_067f: Unknown result type (might be due to invalid IL or missing references)
        //IL_068d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0694: Unknown result type (might be due to invalid IL or missing references)
        //IL_0699: Unknown result type (might be due to invalid IL or missing references)
        //IL_069b: Unknown result type (might be due to invalid IL or missing references)
        //IL_069d: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c5: Unknown result type (might be due to invalid IL or missing references)
        float y = 130 + numLines * 30;
        int num = 180 + (screenWidth - 800) / 2;
        Vector2 vec = default(Vector2);
        ((Vector2)(ref vec))._002Ector((float)mouseX, (float)mouseY);
        Player player = Main.player[myPlayer];
        Vector2 val = new Vector2((float)num, y);
        string text = focusText;
        DynamicSpriteFont value = FontAssets.MouseText.Value;
        Vector2 vector2 = val;
        Vector2 vector3 = default(Vector2);
        ((Vector2)(ref vector3))._002Ector(0.9f);
        Vector2 stringSize = ChatManager.GetStringSize(value, text, vector3);
        Color baseColor = chatColor;
        _ = Color.Black;
        Vector2 vector4 = default(Vector2);
        ((Vector2)(ref vector4))._002Ector(1f);
        Color brown = Color.Brown;
        float num2 = 1.2f;
        if (stringSize.X > 260f)
        {
            vector4.X *= 260f / stringSize.X;
        }
        if (vec.Between(vector2, vector2 + stringSize * vector3 * vector4.X) && !PlayerInput.IgnoreMouseInterface)
        {
            player.mouseInterface = true;
            player.releaseUseItem = false;
            vector3 *= num2;
            if (!npcChatFocus2)
            {
                SoundEngine.PlaySound(12);
            }
            npcChatFocus2 = true;
        }
        else
        {
            if (npcChatFocus2)
            {
                SoundEngine.PlaySound(12);
            }
            npcChatFocus2 = false;
        }
        ChatManager.DrawColorCodedStringWithShadow(spriteBatch, value, text, vector2 + stringSize * vector4 * 0.5f, baseColor, (!npcChatFocus2) ? Color.Black : brown, 0f, stringSize * 0.5f, vector3 * vector4);
        if (text.Length > 0)
        {
            UILinkPointNavigator.SetPosition(2500, vector2 + stringSize * 0.5f);
            UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsLeft = true;
        }
        Vector2 vector5 = default(Vector2);
        ((Vector2)(ref vector5))._002Ector((float)num + stringSize.X * vector4.X + 30f, y);
        text = Lang.inter[52].Value;
        value = FontAssets.MouseText.Value;
        vector2 = vector5;
        ((Vector2)(ref vector3))._002Ector(0.9f);
        stringSize = ChatManager.GetStringSize(value, text, vector3);
        ((Color)(ref baseColor))._002Ector(superColor, (int)((double)superColor / 1.1), superColor / 2, superColor);
        ((Vector2)(ref vector4))._002Ector(1f);
        if (vec.Between(vector2, vector2 + stringSize * vector3 * vector4.X) && !PlayerInput.IgnoreMouseInterface)
        {
            player.mouseInterface = true;
            player.releaseUseItem = false;
            vector3 *= num2;
            if (!npcChatFocus1)
            {
                SoundEngine.PlaySound(12);
            }
            npcChatFocus1 = true;
        }
        else
        {
            if (npcChatFocus1)
            {
                SoundEngine.PlaySound(12);
            }
            npcChatFocus1 = false;
        }
        ChatManager.DrawColorCodedStringWithShadow(spriteBatch, value, text, vector2 + stringSize * vector4 * 0.5f, baseColor, (!npcChatFocus1) ? Color.Black : brown, 0f, stringSize * 0.5f, vector3 * vector4);
        if (text.Length > 0)
        {
            UILinkPointNavigator.SetPosition(2501, vector2 + stringSize * 0.5f);
            UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsMiddle = true;
        }
        if (string.IsNullOrWhiteSpace(focusText3))
        {
            npcChatFocus3 = false;
            UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight = false;
        }
        else
        {
            Vector2 vector6 = default(Vector2);
            ((Vector2)(ref vector6))._002Ector(vector5.X + stringSize.X * vector4.X + 30f, y);
            text = focusText3;
            value = FontAssets.MouseText.Value;
            vector2 = vector6;
            ((Vector2)(ref vector3))._002Ector(0.9f);
            stringSize = ChatManager.GetStringSize(value, text, vector3);
            baseColor = chatColor;
            ((Vector2)(ref vector4))._002Ector(1f);
            vector5.X = vector6.X;
            if (vec.Between(vector2, vector2 + stringSize * vector3 * vector4.X) && !PlayerInput.IgnoreMouseInterface)
            {
                player.mouseInterface = true;
                player.releaseUseItem = false;
                vector3 *= num2;
                if (!npcChatFocus3)
                {
                    SoundEngine.PlaySound(12);
                }
                npcChatFocus3 = true;
            }
            else
            {
                if (npcChatFocus3)
                {
                    SoundEngine.PlaySound(12);
                }
                npcChatFocus3 = false;
            }
            ChatManager.DrawColorCodedStringWithShadow(spriteBatch, value, text, vector2 + stringSize * vector4 * 0.5f, baseColor, (!npcChatFocus3) ? Color.Black : brown, 0f, stringSize * 0.5f, vector3 * vector4);
            UILinkPointNavigator.SetPosition(2502, vector2 + stringSize * 0.5f);
            UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight = true;
        }
        if (remixWorld)
        {
            return;
        }
        if (Main.player[myPlayer].currentShoppingSettings.HappinessReport == "")
        {
            npcChatFocus4 = false;
            UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight2 = false;
            return;
        }
        string textValue = Language.GetTextValue("UI.NPCCheckHappiness");
        Vector2 val2 = new Vector2(vector5.X + stringSize.X * vector4.X + 30f, y);
        text = textValue;
        value = FontAssets.MouseText.Value;
        vector2 = val2;
        ((Vector2)(ref vector3))._002Ector(0.9f);
        stringSize = ChatManager.GetStringSize(value, text, vector3);
        ((Color)(ref baseColor))._002Ector(superColor, (int)((double)superColor / 1.1), superColor / 2, superColor);
        ((Vector2)(ref vector4))._002Ector(1f);
        if (vec.Between(vector2, vector2 + stringSize * vector3 * vector4.X) && !PlayerInput.IgnoreMouseInterface)
        {
            player.mouseInterface = true;
            player.releaseUseItem = false;
            vector3 *= num2;
            if (!npcChatFocus4)
            {
                SoundEngine.PlaySound(12);
            }
            npcChatFocus4 = true;
        }
        else
        {
            if (npcChatFocus4)
            {
                SoundEngine.PlaySound(12);
            }
            npcChatFocus4 = false;
        }
        ChatManager.DrawColorCodedStringWithShadow(spriteBatch, value, text, vector2 + stringSize * vector4 * 0.5f, baseColor, (!npcChatFocus4) ? Color.Black : brown, 0f, stringSize * 0.5f, vector3 * vector4);
        UILinkPointNavigator.SetPosition(2503, vector2 + stringSize * 0.5f);
        UILinkPointNavigator.Shortcuts.NPCCHAT_ButtonsRight2 = true;
    }
References Terraria.Graphics.Light.Color, Terraria.Player.currentShoppingSettings, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Localization.Language.GetTextValue(), Terraria.ShoppingSettings.HappinessReport, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Lang.inter, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.npcChatFocus1, Terraria.Main.npcChatFocus2, Terraria.Main.npcChatFocus3, Terraria.Main.npcChatFocus4, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.remixWorld, Terraria.Main.screenWidth, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.spriteBatch, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.GUIChatDrawInner().