TModLoader: Terraria.Main.SetupDrawInterfaceLayers
SetupDrawInterfaceLayers()
void Terraria.Main.SetupDrawInterfaceLayers () inline private
Definition at line 57795 of file Main.cs.
    {
        if (_needToSetupDrawInterfaceLayers)
        {
            _needToSetupDrawInterfaceLayers = false;
            _gameInterfaceLayers = new List<GameInterfaceLayer>();
            _gameInterfaceLayers.AddRange(new GameInterfaceLayer[43]
            {
                new LegacyGameInterfaceLayer("Vanilla: Interface Logic 1", delegate
                {
                    DrawInterface_0_InterfaceLogic1();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: MP Player Names", delegate
                {
                    DrawInterface_20_MultiplayerPlayerNames();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: Emote Bubbles", delegate
                {
                    DrawInterface_1_1_DrawEmoteBubblesInWorld();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: Entity Markers", delegate
                {
                    DrawInterface_1_2_DrawEntityMarkersInWorld();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: Smart Cursor Targets", delegate
                {
                    DrawInterface_2_SmartCursorTargets();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: Laser Ruler", delegate
                {
                    DrawInterface_3_LaserRuler();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: Ruler", delegate
                {
                    DrawInterface_4_Ruler();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: Gamepad Lock On", delegate
                {
                    DrawInterface_5_GamepadLockOn();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: Tile Grid Option", delegate
                {
                    DrawInterface_6_TileGridOption();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: Town NPC House Banners", delegate
                {
                    DrawInterface_7_TownNPCHouseBanners();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: Hide UI Toggle", DrawInterface_8_CheckF11UIHideToggle, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Wire Selection", delegate
                {
                    DrawInterface_9_WireSelection();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Capture Manager Check", DrawInterface_10_CheckCaptureManager),
                new LegacyGameInterfaceLayer("Vanilla: Ingame Options", DrawInterface_11_IngameOptionsMenu, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Fancy UI", DrawInterface_12_IngameFancyUI, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Achievement Complete Popups", delegate
                {
                    DrawInterface_13_AchievementCompletePopups();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Entity Health Bars", delegate
                {
                    DrawInterface_14_EntityHealthBars();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: Invasion Progress Bars", delegate
                {
                    DrawInterface_15_InvasionProgressBars();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Map / Minimap", delegate
                {
                    DrawInterface_16_MapOrMinimap();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Diagnose Net", delegate
                {
                    DrawInterface_17_DiagnoseNet();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Diagnose Video", delegate
                {
                    DrawInterface_18_DiagnoseVideo();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Sign Tile Bubble", delegate
                {
                    DrawInterface_19_SignTileBubble();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: Hair Window", delegate
                {
                    DrawInterface_21_HairWindow();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Dresser Window", delegate
                {
                    DrawInterface_22_DresserWindow();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: NPC / Sign Dialog", delegate
                {
                    DrawInterface_23_NPCSignsDialog();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Interface Logic 2", delegate
                {
                    DrawInterface_24_InterfaceLogic2();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: Resource Bars", delegate
                {
                    DrawInterface_25_ResourceBars();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Interface Logic 3", delegate
                {
                    DrawInterface_26_InterfaceLogic3();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: Inventory", delegate
                {
                    DrawInterface_27_Inventory();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Info Accessories Bar", delegate
                {
                    DrawInterface_28_InfoAccs();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Settings Button", delegate
                {
                    DrawInterface_29_SettingsButton();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Hotbar", delegate
                {
                    DrawInterface_30_Hotbar();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Builder Accessories Bar", delegate
                {
                    DrawInterface_31_BuilderAccToggles();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Radial Hotbars", delegate
                {
                    DrawInterface_32_GamepadRadialHotbars();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Mouse Text", delegate
                {
                    DrawInterface_33_MouseText();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Player Chat", delegate
                {
                    DrawInterface_34_PlayerChat();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Death Text", delegate
                {
                    DrawInterface_35_YouDied();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Cursor", delegate
                {
                    DrawInterface_36_Cursor();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Debug Stuff", delegate
                {
                    DrawInterface_37_DebugStuff();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Mouse Item / NPC Head", delegate
                {
                    DrawInterface_38_MouseCarriedObject();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Mouse Over", delegate
                {
                    DrawInterface_39_MouseOver();
                    return true;
                }),
                new LegacyGameInterfaceLayer("Vanilla: Interact Item Icon", delegate
                {
                    DrawInterface_40_InteractItemIcon();
                    return true;
                }, InterfaceScaleType.UI),
                new LegacyGameInterfaceLayer("Vanilla: Interface Logic 4", delegate
                {
                    DrawInterface_41_InterfaceLogic4();
                    return true;
                }, InterfaceScaleType.UI)
            });
        }
    }
References Terraria.Main._gameInterfaceLayers, Terraria.Main._needToSetupDrawInterfaceLayers, Terraria.Main.DrawInterface_0_InterfaceLogic1(), Terraria.Main.DrawInterface_10_CheckCaptureManager(), Terraria.Main.DrawInterface_11_IngameOptionsMenu(), Terraria.Main.DrawInterface_12_IngameFancyUI(), Terraria.Main.DrawInterface_13_AchievementCompletePopups(), Terraria.Main.DrawInterface_14_EntityHealthBars(), Terraria.Main.DrawInterface_15_InvasionProgressBars(), Terraria.Main.DrawInterface_16_MapOrMinimap(), Terraria.Main.DrawInterface_17_DiagnoseNet(), Terraria.Main.DrawInterface_18_DiagnoseVideo(), Terraria.Main.DrawInterface_19_SignTileBubble(), Terraria.Main.DrawInterface_1_1_DrawEmoteBubblesInWorld(), Terraria.Main.DrawInterface_1_2_DrawEntityMarkersInWorld(), Terraria.Main.DrawInterface_20_MultiplayerPlayerNames(), Terraria.Main.DrawInterface_21_HairWindow(), Terraria.Main.DrawInterface_22_DresserWindow(), Terraria.Main.DrawInterface_23_NPCSignsDialog(), Terraria.Main.DrawInterface_24_InterfaceLogic2(), Terraria.Main.DrawInterface_25_ResourceBars(), Terraria.Main.DrawInterface_26_InterfaceLogic3(), Terraria.Main.DrawInterface_27_Inventory(), Terraria.Main.DrawInterface_28_InfoAccs(), Terraria.Main.DrawInterface_29_SettingsButton(), Terraria.Main.DrawInterface_2_SmartCursorTargets(), Terraria.Main.DrawInterface_30_Hotbar(), Terraria.Main.DrawInterface_31_BuilderAccToggles(), Terraria.Main.DrawInterface_32_GamepadRadialHotbars(), Terraria.Main.DrawInterface_33_MouseText(), Terraria.Main.DrawInterface_34_PlayerChat(), Terraria.Main.DrawInterface_35_YouDied(), Terraria.Main.DrawInterface_36_Cursor(), Terraria.Main.DrawInterface_37_DebugStuff(), Terraria.Main.DrawInterface_38_MouseCarriedObject(), Terraria.Main.DrawInterface_39_MouseOver(), Terraria.Main.DrawInterface_3_LaserRuler(), Terraria.Main.DrawInterface_40_InteractItemIcon(), Terraria.Main.DrawInterface_41_InterfaceLogic4(), Terraria.Main.DrawInterface_4_Ruler(), Terraria.Main.DrawInterface_5_GamepadLockOn(), Terraria.Main.DrawInterface_6_TileGridOption(), Terraria.Main.DrawInterface_7_TownNPCHouseBanners(), Terraria.Main.DrawInterface_8_CheckF11UIHideToggle(), and Terraria.Main.DrawInterface_9_WireSelection().
Referenced by Terraria.Main.DrawInterface().