TModLoader: Terraria.Main.DrawBlack
DrawBlack()
void Terraria.Main.DrawBlack (bool force = false) inline protected
Definition at line 73870 of file Main.cs.
    {
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0160: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_019a: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03db: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fb: Unknown result type (might be due to invalid IL or missing references)
        if (shimmerAlpha == 1f)
        {
            return;
        }
        Stopwatch stopwatch = new Stopwatch();
        stopwatch.Start();
        Vector2 vector = (Vector2)(drawToScreen ? Vector2.Zero : new Vector2((float)offScreenRange, (float)offScreenRange));
        int num = (((Color)(ref tileColor)).R + ((Color)(ref tileColor)).G + ((Color)(ref tileColor)).B) / 3;
        float num2 = (float)((double)num * 0.4) / 255f;
        if (Lighting.Mode == LightMode.Retro)
        {
            num2 = (float)(((Color)(ref tileColor)).R - 55) / 255f;
            if (num2 < 0f)
            {
                num2 = 0f;
            }
        }
        else if (Lighting.Mode == LightMode.Trippy)
        {
            num2 = (float)(num - 55) / 255f;
            if (num2 < 0f)
            {
                num2 = 0f;
            }
        }
        Point screenOverdrawOffset = GetScreenOverdrawOffset();
        Point point = default(Point);
        ((Point)(ref point))._002Ector(-offScreenRange / 16 + screenOverdrawOffset.X, -offScreenRange / 16 + screenOverdrawOffset.Y);
        int num3 = (int)((screenPosition.X - vector.X) / 16f - 1f) + point.X;
        int num4 = (int)((screenPosition.X + (float)screenWidth + vector.X) / 16f) + 2 - point.X;
        int num5 = (int)((screenPosition.Y - vector.Y) / 16f - 1f) + point.Y;
        int num6 = (int)((screenPosition.Y + (float)screenHeight + vector.Y) / 16f) + 5 - point.Y;
        if (num3 < 0)
        {
            num3 = point.X;
        }
        if (num4 > maxTilesX)
        {
            num4 = maxTilesX - point.X;
        }
        if (num5 < 0)
        {
            num5 = point.Y;
        }
        if (num6 > maxTilesY)
        {
            num6 = maxTilesY - point.Y;
        }
        if (!force)
        {
            if (num5 < maxTilesY / 2)
            {
                num6 = Math.Min(num6, (int)worldSurface + 1);
                num5 = Math.Min(num5, (int)worldSurface + 1);
            }
            else
            {
                num6 = Math.Max(num6, UnderworldLayer);
                num5 = Math.Max(num5, UnderworldLayer);
            }
        }
        bool flag = ShouldShowInvisibleWalls();
        for (int i = num5; i < num6; i++)
        {
            bool flag2 = i >= UnderworldLayer;
            if (flag2)
            {
                num2 = 0.2f;
            }
            for (int j = num3; j < num4; j++)
            {
                int num7 = j;
                for (; j < num4; j++)
                {
                    if (!WorldGen.InWorld(j, i))
                    {
                        return;
                    }
                    if (Main.tile[j, i] == null)
                    {
                        Main.tile[j, i] = default(Tile);
                    }
                    Tile tile = Main.tile[j, i];
                    float num8 = Lighting.Brightness(j, i);
                    num8 = (float)Math.Floor(num8 * 255f) / 255f;
                    byte b = tile.liquid;
                    bool num9 = num8 <= num2 && ((!flag2 && b < 250) || WorldGen.SolidTile(tile) || (b >= 200 && num8 == 0f));
                    bool flag3 = tile.active() && tileBlockLight[tile.type] && (!tile.invisibleBlock() || flag);
                    bool flag4 = !WallID.Sets.Transparent[tile.wall] && (!tile.invisibleWall() || flag);
                    if (!num9 || (!flag4 && !flag3) || (!drawToScreen && LiquidRenderer.Instance.HasFullWater(j, i) && tile.wall == 0 && !tile.halfBrick() && !((double)i <= worldSurface)))
                    {
                        break;
                    }
                }
                if (j - num7 > 0)
                {
                    spriteBatch.Draw(TextureAssets.BlackTile.Value, new Vector2((float)(num7 << 4), (float)(i << 4)) - screenPosition + vector, (Rectangle?)new Rectangle(0, 0, j - num7 << 4, 16), Color.Black);
                }
            }
        }
        TimeLogger.DrawTime(5, stopwatch.Elapsed.TotalMilliseconds);
    }
References Terraria.GameContent.TextureAssets.BlackTile, Terraria.Lighting.Brightness(), Terraria.Graphics.Light.Color, Terraria.TimeLogger.DrawTime(), Terraria.Main.drawToScreen, Terraria.Main.GetScreenOverdrawOffset(), Terraria.GameContent.Liquid.LiquidRenderer.Instance, Terraria.WorldGen.InWorld(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Lighting.Mode, Terraria.Main.offScreenRange, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.shimmerAlpha, Terraria.Main.ShouldShowInvisibleWalls(), Terraria.WorldGen.SolidTile(), Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Main.tileBlockLight, Terraria.Main.tileColor, Terraria.ID.WallID.Sets.Transparent, Terraria.Main.UnderworldLayer, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DoDraw_WallsAndBlacks(), Terraria.Main.DrawCapture(), and Terraria.Main.RenderBlack().