TModLoader: Terraria.Main.BindSettingsTo
BindSettingsTo()
void Terraria.Main.BindSettingsTo (Preferences preferences) inline private
    {
        waterfallManager.BindTo(preferences);
        MinimapFrameManagerInstance.BindTo(preferences);
        BigBossProgressBar.BindTo(preferences);
        ResourceSetsManager.BindTo(preferences);
        ChromaInitializer.BindTo(preferences);
        Terraria.Graphics.Effects.Filters.Scene.BindTo(preferences);
        if (SocialAPI.Cloud != null)
        {
            SocialAPI.Cloud.BindTo(preferences);
        }
        preferences.OnSave += SaveResourcePacks;
        preferences.OnLoad += LoadResourcePacks;
    }
References Terraria.Main.BigBossProgressBar, Terraria.DataStructures.SelectionHolder< TCycleType >.BindTo(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarSystem.BindTo(), Terraria.GameContent.UI.ResourceSets.PlayerResourceSetsManager.BindTo(), Terraria.Graphics.Effects.FilterManager.BindTo(), Terraria.Initializers.ChromaInitializer.BindTo(), Terraria.Social.Base.CloudSocialModule.BindTo(), Terraria.WaterfallManager.BindTo(), Terraria.Social.SocialAPI.Cloud, Terraria.Main.LoadResourcePacks(), Terraria.Main.MinimapFrameManagerInstance, Terraria.Main.ResourceSetsManager, Terraria.Main.SaveResourcePacks(), Terraria.Graphics.Effects.Filters.Scene, and Terraria.Main.waterfallManager.
Referenced by Terraria.Main.Initialize().