TModLoader: Terraria.Main.DrawWhip_WhipMace
DrawWhip_WhipMace()
static Vector2 Terraria.Main.DrawWhip_WhipMace (Projectile proj, List< Vector2 > controlPoints) inline static
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0181: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        SpriteEffects spriteEffects = (SpriteEffects)0;
        if (proj.spriteDirection == 1)
        {
            spriteEffects = (SpriteEffects)(spriteEffects ^ 1);
        }
        Texture2D value = TextureAssets.Projectile[proj.type].Value;
        Rectangle rectangle = value.Frame(1, 5);
        int height = rectangle.Height;
        rectangle.Height -= 2;
        Vector2 vector = rectangle.Size() / 2f;
        Vector2 vector2 = controlPoints[0];
        for (int i = 0; i < controlPoints.Count - 1; i++)
        {
            bool flag = false;
            Vector2 origin = vector;
            float scale = 1f;
            if (i == 0)
            {
                origin.Y -= 4f;
                flag = true;
            }
            else if (i % 2 == 0)
            {
                flag = true;
                int num = 1;
                if (i > 10)
                {
                    num = 2;
                }
                if (i > 20)
                {
                    num = 3;
                }
                rectangle.Y = height * num;
            }
            if (i == controlPoints.Count - 2)
            {
                flag = true;
                rectangle.Y = height * 4;
                scale = 1.3f;
                Projectile.GetWhipSettings(proj, out var timeToFlyOut, out var _, out var _);
                float t = proj.ai[0] / timeToFlyOut;
                float amount = Utils.GetLerpValue(0.1f, 0.7f, t, clamped: true) * Utils.GetLerpValue(0.9f, 0.7f, t, clamped: true);
                scale = MathHelper.Lerp(0.5f, 2f, amount);
            }
            Vector2 vector3 = controlPoints[i];
            Vector2 vector4 = controlPoints[i + 1] - vector3;
            if (flag)
            {
                float rotation = vector4.ToRotation() - (float)Math.PI / 2f;
                Color color = Lighting.GetColor(vector3.ToTileCoordinates());
                spriteBatch.Draw(value, vector2 - screenPosition, (Rectangle?)rectangle, color, rotation, origin, scale, spriteEffects, 0f);
            }
            vector2 += vector4;
        }
        return vector2;
    }
References Terraria.Lighting.GetColor(), Terraria.Utils.GetLerpValue(), Terraria.Projectile.GetWhipSettings(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.screenPosition, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawWhip().