TModLoader: Terraria.Main.DrawProj_PiercingStarlight
DrawProj_PiercingStarlight()
void Terraria.Main.DrawProj_PiercingStarlight (Projectile proj) inline private
    {
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00da: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0160: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0272: Unknown result type (might be due to invalid IL or missing references)
        //IL_028a: Unknown result type (might be due to invalid IL or missing references)
        //IL_028c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0296: Unknown result type (might be due to invalid IL or missing references)
        //IL_029b: Unknown result type (might be due to invalid IL or missing references)
        //IL_029f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02da: Unknown result type (might be due to invalid IL or missing references)
        //IL_032f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0336: Unknown result type (might be due to invalid IL or missing references)
        //IL_033d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0342: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_0363: Unknown result type (might be due to invalid IL or missing references)
        //IL_0368: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03db: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0401: Unknown result type (might be due to invalid IL or missing references)
        //IL_0403: Unknown result type (might be due to invalid IL or missing references)
        //IL_0407: Unknown result type (might be due to invalid IL or missing references)
        //IL_040c: Unknown result type (might be due to invalid IL or missing references)
        //IL_040f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0418: Unknown result type (might be due to invalid IL or missing references)
        //IL_0424: Unknown result type (might be due to invalid IL or missing references)
        //IL_0428: Unknown result type (might be due to invalid IL or missing references)
        //IL_042a: Unknown result type (might be due to invalid IL or missing references)
        //IL_042c: Unknown result type (might be due to invalid IL or missing references)
        //IL_043f: Unknown result type (might be due to invalid IL or missing references)
        //IL_044b: Unknown result type (might be due to invalid IL or missing references)
        //IL_044f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0451: Unknown result type (might be due to invalid IL or missing references)
        //IL_0458: Unknown result type (might be due to invalid IL or missing references)
        //IL_045d: Unknown result type (might be due to invalid IL or missing references)
        float num = proj.ai[1];
        if (num == 0f)
        {
            num = 1f;
        }
        int num12 = (int)Math.Ceiling(3f * num);
        LoadProjectile(proj.type);
        LoadItem(4923);
        int num13 = 2;
        Vector2 vector = proj.Center - proj.rotation.ToRotationVector2() * (float)num13;
        for (int i = 0; i < 1; i++)
        {
            float num14 = rand.NextFloat();
            float num15 = Utils.GetLerpValue(0f, 0.3f, num14, clamped: true) * Utils.GetLerpValue(1f, 0.5f, num14, clamped: true);
            Color color = proj.GetAlpha(Lighting.GetColor(proj.Center.ToTileCoordinates())) * num15;
            Texture2D value = TextureAssets.Item[4923].Value;
            Vector2 origin = value.Size() / 2f;
            float num16 = rand.NextFloatDirection();
            float num17 = 8f + MathHelper.Lerp(0f, 20f, num14) + rand.NextFloat() * 6f;
            float num18 = proj.rotation + num16 * ((float)Math.PI * 2f) * 0.04f;
            float num19 = num18 + (float)Math.PI / 4f;
            Vector2 position = vector + num18.ToRotationVector2() * num17 + rand.NextVector2Circular(8f, 8f) - screenPosition;
            SpriteEffects spriteEffects = (SpriteEffects)0;
            if (proj.rotation < -(float)Math.PI / 2f || proj.rotation > (float)Math.PI / 2f)
            {
                num19 += (float)Math.PI / 2f;
                spriteEffects = (SpriteEffects)(spriteEffects | 1);
            }
            spriteBatch.Draw(value, position, (Rectangle?)null, color, num19, origin, 1f, spriteEffects, 0f);
        }
        for (int j = 0; j < num12; j++)
        {
            float num2 = rand.NextFloat();
            float num3 = Utils.GetLerpValue(0f, 0.3f, num2, clamped: true) * Utils.GetLerpValue(1f, 0.5f, num2, clamped: true);
            float amount = Utils.GetLerpValue(0f, 0.3f, num2, clamped: true) * Utils.GetLerpValue(1f, 0.5f, num2, clamped: true);
            float num4 = MathHelper.Lerp(0.6f, 1f, amount);
            Color fairyQueenWeaponsColor = proj.GetFairyQueenWeaponsColor(0.25f, 0f, (rand.NextFloat() * 0.33f + GlobalTimeWrappedHourly) % 1f);
            Texture2D value2 = TextureAssets.Projectile[proj.type].Value;
            Color color2 = fairyQueenWeaponsColor;
            color2 *= num3 * 0.5f;
            Vector2 origin2 = value2.Size() / 2f;
            Color color3 = Color.White * num3;
            ((Color)(ref color3)).A = (byte)(((Color)(ref color3)).A / 2);
            Color color4 = color3 * 0.5f;
            float num5 = 1f;
            float num6 = (num - 1f) / 2f;
            float num7 = rand.NextFloat() * 2f * num;
            num7 += num6;
            float num8 = rand.NextFloatDirection();
            Vector2 vector2 = new Vector2(2.8f + num7 * (1f + num6), 1f) * num5 * num4;
            float value3 = 50f * num;
            Vector2 vector3 = proj.rotation.ToRotationVector2() * (float)((j >= 1) ? 56 : 0);
            float num9 = 0.03f - (float)j * 0.012f;
            num9 /= num;
            float num10 = 30f + MathHelper.Lerp(0f, value3, num2) + num7 * 16f;
            float num11 = proj.rotation + num8 * ((float)Math.PI * 2f) * num9;
            float rotation = num11;
            Vector2 position2 = vector + num11.ToRotationVector2() * num10 + rand.NextVector2Circular(20f, 20f) + vector3 - screenPosition;
            color2 *= num5;
            color4 *= num5;
            SpriteEffects effects = (SpriteEffects)0;
            spriteBatch.Draw(value2, position2, (Rectangle?)null, color2, rotation, origin2, vector2, effects, 0f);
            spriteBatch.Draw(value2, position2, (Rectangle?)null, color4, rotation, origin2, vector2 * 0.6f, effects, 0f);
        }
    }
References Terraria.Graphics.Light.Color, Terraria.Lighting.GetColor(), Terraria.Utils.GetLerpValue(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.TextureAssets.Item, Terraria.Main.LoadItem(), Terraria.Main.LoadProjectile(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.rand, Terraria.Main.screenPosition, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawProj_DrawSpecialProjs().