TModLoader: Terraria.Main.DrawSurfaceBG_Snow
DrawSurfaceBG_Snow()
void Terraria.Main.DrawSurfaceBG_Snow (double backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack, int[] bgTexIndexes) inline private
    {
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_019b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0338: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_035d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0369: Unknown result type (might be due to invalid IL or missing references)
        //IL_036f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0504: Unknown result type (might be due to invalid IL or missing references)
        //IL_051f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0529: Unknown result type (might be due to invalid IL or missing references)
        //IL_0535: Unknown result type (might be due to invalid IL or missing references)
        //IL_053b: Unknown result type (might be due to invalid IL or missing references)
        if (bgTexIndexes[0] >= 0)
        {
            bgScale = 1.25f;
            bgParallax = 0.4;
            bgTopY = (int)(backgroundTopMagicNumber * 1800.0 + 1500.0) + (int)scAdj + pushBGTopHack;
            SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
            bgScale *= bgGlobalScaleMultiplier;
            LoadBackground(bgTexIndexes[0]);
            bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[0]] * bgScale);
            SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
            bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
            if (gameMenu)
            {
                bgTopY = 320 + pushBGTopHack;
            }
            bgTopY += DrawSurfaceBG_GetLayerYOffset(bgTexIndexes[0]);
            bgLoops = screenWidth / bgWidthScaled + 2;
            if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
            {
                for (int i = 0; i < bgLoops; i++)
                {
                    spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[0]].Value, new Vector2((float)(bgStartX + bgWidthScaled * i), (float)bgTopY), (Rectangle?)new Rectangle(0, 0, backgroundWidth[bgTexIndexes[0]], backgroundHeight[bgTexIndexes[0]]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
                }
            }
        }
        if (bgTexIndexes[1] >= 0)
        {
            bgScale = 1.31f;
            bgParallax = 0.43;
            bgTopY = (int)(backgroundTopMagicNumber * 1950.0 + 1750.0) + (int)scAdj + pushBGTopHack;
            SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
            bgScale *= bgGlobalScaleMultiplier;
            LoadBackground(bgTexIndexes[1]);
            bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[1]] * bgScale);
            SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
            bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
            if (gameMenu)
            {
                bgTopY = 400 + pushBGTopHack;
                bgStartX -= 80;
            }
            bgTopY += DrawSurfaceBG_GetLayerYOffset(bgTexIndexes[1]);
            bgLoops = screenWidth / bgWidthScaled + 2;
            if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
            {
                for (int j = 0; j < bgLoops; j++)
                {
                    spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[1]].Value, new Vector2((float)(bgStartX + bgWidthScaled * j), (float)bgTopY), (Rectangle?)new Rectangle(0, 0, backgroundWidth[bgTexIndexes[1]], backgroundHeight[bgTexIndexes[1]]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
                }
            }
        }
        if (bgTexIndexes[2] < 0)
        {
            return;
        }
        bgScale = 1.34f;
        bgParallax = 0.49;
        bgTopY = (int)(backgroundTopMagicNumber * 2100.0 + 2000.0) + (int)scAdj + pushBGTopHack;
        SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
        bgScale *= bgGlobalScaleMultiplier;
        LoadBackground(bgTexIndexes[2]);
        bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[2]] * bgScale);
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
        bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
        if (gameMenu)
        {
            bgTopY = 480 + pushBGTopHack;
            bgStartX -= 120;
        }
        bgTopY += DrawSurfaceBG_GetLayerYOffset(bgTexIndexes[2]);
        bgLoops = screenWidth / bgWidthScaled + 2;
        if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
        {
            for (int k = 0; k < bgLoops; k++)
            {
                spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[2]].Value, new Vector2((float)(bgStartX + bgWidthScaled * k), (float)bgTopY), (Rectangle?)new Rectangle(0, 0, backgroundWidth[bgTexIndexes[2]], backgroundHeight[bgTexIndexes[2]]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
            }
        }
    }
References Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundHeight, Terraria.Main.backgroundWidth, Terraria.Main.bgLoops, Terraria.Main.bgParallax, Terraria.Main.bgScale, Terraria.Main.bgStartX, Terraria.Main.bgTopY, Terraria.Main.bgWidthScaled, Terraria.Main.ColorOfSurfaceBackgroundsModified, Terraria.Main.DrawSurfaceBG_GetLayerYOffset(), Terraria.Main.gameMenu, Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.LoadBackground(), Terraria.Main.scAdj, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.SetBackgroundOffsets(), Terraria.Main.spriteBatch, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DrawSurfaceBG().