TModLoader: Terraria.Main.DrawInterface_GolfBallIndicator
DrawInterface_GolfBallIndicator()
static void Terraria.Main.DrawInterface_GolfBallIndicator () inline static private
    {
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_004f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_0126: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0140: Unknown result type (might be due to invalid IL or missing references)
        //IL_0145: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_0158: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_0219: Unknown result type (might be due to invalid IL or missing references)
        //IL_021e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_022a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0230: Unknown result type (might be due to invalid IL or missing references)
        //IL_0246: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        //IL_0291: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02db: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_030b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0312: Unknown result type (might be due to invalid IL or missing references)
        //IL_0318: Unknown result type (might be due to invalid IL or missing references)
        //IL_031f: Unknown result type (might be due to invalid IL or missing references)
        if (!Item.IsAGolfingItem(LocalPlayer.HeldItem))
        {
            return;
        }
        Projectile lastHitBall = LocalGolfState.GetLastHitBall();
        if (lastHitBall != null && GolfHelper.IsGolfBallResting(lastHitBall))
        {
            Vector2 vector = lastHitBall.Top - Camera.ScaledPosition;
            vector *= GameViewMatrix.Zoom;
            vector /= UIScale;
            Vector2 val = LocalPlayer.position - lastHitBall.position;
            float num = MathHelper.Clamp((((Vector2)(ref val)).Length() - 150f) / 50f, 0f, 1f);
            Vector2 vector2 = Vector2.Clamp(vector, new Vector2(20f), Camera.UnscaledSize - new Vector2(20f));
            float num2 = 0f;
            if (vector2 != vector)
            {
                num2 = (vector2 - vector).ToRotation() + (float)Math.PI / 2f;
            }
            vector2 -= (num2 + (float)Math.PI / 2f).ToRotationVector2() * (((float)Math.Sin(GlobalTimeWrappedHourly * 4f) * 0.5f + 0.5f) * 5f + 14f);
            Texture2D value = TextureAssets.GolfBallArrow.Value;
            Rectangle rectangle = value.Frame(2);
            Vector2 origin = rectangle.Size() * new Vector2(0.5f, 1f);
            Rectangle value2 = value.Frame(2, 1, 1);
            spriteBatch.Draw(TextureAssets.GolfBallArrowShadow.Value, vector2 + new Vector2(-4f, 4f) * 1.5f, (Rectangle?)rectangle, Color.White * num, num2, origin, 1.5f, (SpriteEffects)0, 0f);
            float amount = (float)Math.Sin(GlobalTimeWrappedHourly * 4f) * 0.5f + 0.5f;
            for (float num3 = 0f; num3 < 1f; num3 += 0.25f)
            {
                spriteBatch.Draw(value, vector2 + ((float)Math.PI * 2f * num3 + num2).ToRotationVector2() * MathHelper.Lerp(2f, 2f, amount), (Rectangle?)value2, Color.Black * num * MathHelper.Lerp(1f, 1f, amount), num2, origin, 1.5f, (SpriteEffects)0, 0f);
            }
            for (float num4 = 0f; num4 < 1f; num4 += 0.25f)
            {
                spriteBatch.Draw(value, vector2 + ((float)Math.PI * 2f * num4 + num2).ToRotationVector2() * MathHelper.Lerp(0f, 0f, amount), (Rectangle?)value2, Color.White * num * MathHelper.Lerp(0.8f, 0.8f, amount), num2, origin, 1.5f, (SpriteEffects)0, 0f);
            }
            spriteBatch.Draw(value, vector2, (Rectangle?)rectangle, mouseColor * num, num2, origin, 1.5f, (SpriteEffects)0, 0f);
        }
    }
References Terraria.Graphics.Light.Color, Terraria.Main.GameViewMatrix, Terraria.GameContent.Golf.GolfState.GetLastHitBall(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.GameContent.TextureAssets.GolfBallArrow, Terraria.GameContent.TextureAssets.GolfBallArrowShadow, Terraria.Player.HeldItem, Terraria.Item.IsAGolfingItem(), Terraria.GameContent.Golf.GolfHelper.IsGolfBallResting(), Terraria.Main.LocalGolfState, Terraria.Main.LocalPlayer, Terraria.Main.mouseColor, Terraria.Graphics.Camera.ScaledPosition, Terraria.Main.spriteBatch, Terraria.Main.UIScale, Terraria.Graphics.Camera.UnscaledSize, and Terraria.Graphics.SpriteViewMatrix.Zoom.
Referenced by Terraria.Main.DrawInterface_9_WireSelection().