TModLoader: Terraria.Main.DrawSurfaceBG_Mushroom
DrawSurfaceBG_Mushroom()
void Terraria.Main.DrawSurfaceBG_Mushroom (double backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack, int[] bgTexIndexes) inline private
Definition at line 76417 of file Main.cs.
    {
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00de: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0352: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_0387: Unknown result type (might be due to invalid IL or missing references)
        //IL_038f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0312: Unknown result type (might be due to invalid IL or missing references)
        //IL_0321: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        //IL_0601: Unknown result type (might be due to invalid IL or missing references)
        //IL_0606: Unknown result type (might be due to invalid IL or missing references)
        //IL_0636: Unknown result type (might be due to invalid IL or missing references)
        //IL_063f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0651: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05df: Unknown result type (might be due to invalid IL or missing references)
        //IL_086a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0879: Unknown result type (might be due to invalid IL or missing references)
        //IL_0882: Unknown result type (might be due to invalid IL or missing references)
        //IL_0888: Unknown result type (might be due to invalid IL or missing references)
        float num = 0.33f;
        Vector3 vector = default(Vector3);
        ((Vector3)(ref vector))._002Ector(0.1f, 0.15f, 0.3f);
        float num2 = 0.5f;
        Vector3 vector2 = default(Vector3);
        ((Vector3)(ref vector2))._002Ector(0.1f, 0.175f, 0.3f);
        float num3 = 0.75f;
        Vector3 vector3 = default(Vector3);
        ((Vector3)(ref vector3))._002Ector(0.125f, 0.2f, 0.3f);
        num = 0.5f;
        num2 = 0.625f;
        num3 = 0.75f;
        vector *= 3f;
        vector2 *= 3f;
        vector3 *= 3f;
        float num4 = (float)(int)((Color)(ref ColorOfSurfaceBackgroundsModified)).A / 255f;
        Color colorOfSurfaceBackgroundsModified = ColorOfSurfaceBackgroundsModified;
        float num5 = (float)rand.Next(28, 42) * 0.001f;
        num5 += (float)(270 - mouseTextColor) / 5000f;
        float x = vector.X;
        float num6 = vector.Y + num5 / 2f;
        float num7 = vector.Z + num5;
        x *= 255f;
        num6 *= 255f;
        num7 *= 255f;
        x *= num * num4;
        num6 *= num * num4;
        num7 *= num * num4;
        if (x > 255f)
        {
            x = 255f;
        }
        if (num6 > 255f)
        {
            num6 = 255f;
        }
        if (num7 > 255f)
        {
            num7 = 255f;
        }
        if (x > (float)(int)((Color)(ref colorOfSurfaceBackgroundsModified)).R)
        {
            ((Color)(ref colorOfSurfaceBackgroundsModified)).R = (byte)x;
        }
        if (num6 > (float)(int)((Color)(ref colorOfSurfaceBackgroundsModified)).G)
        {
            ((Color)(ref colorOfSurfaceBackgroundsModified)).G = (byte)num6;
        }
        if (num7 > (float)(int)((Color)(ref colorOfSurfaceBackgroundsModified)).B)
        {
            ((Color)(ref colorOfSurfaceBackgroundsModified)).B = (byte)num7;
        }
        bgScale = 1.25f;
        bgScale *= bgGlobalScaleMultiplier;
        LoadBackground(bgTexIndexes[0]);
        bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[0]] * bgScale);
        bgParallax = 0.4;
        SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
        bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
        bgTopY = (int)(backgroundTopMagicNumber * 1800.0 + 1400.0) + (int)scAdj + pushBGTopHack;
        SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
        if (gameMenu)
        {
            bgTopY = 320 + pushBGTopHack;
        }
        if (bgWidthScaled != 0)
        {
            bgLoops = screenWidth / bgWidthScaled + 2;
        }
        if (TextureAssets.Background[bgTexIndexes[0]].Value == null)
        {
            return;
        }
        if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
        {
            for (int i = 0; i < bgLoops; i++)
            {
                spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[0]].Value, new Vector2((float)(bgStartX + bgWidthScaled * i), (float)bgTopY), GetBackgroundRect(bgTexIndexes[0]), colorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
            }
        }
        colorOfSurfaceBackgroundsModified = ColorOfSurfaceBackgroundsModified;
        num5 = (float)rand.Next(28, 42) * 0.001f;
        num5 += (float)(270 - mouseTextColor) / 5000f;
        x = vector2.X;
        num6 = vector2.Y + num5 / 2f;
        num7 = vector2.Z + num5;
        x *= 255f;
        num6 *= 255f;
        num7 *= 255f;
        x *= num2 * num4;
        num6 *= num2 * num4;
        num7 *= num2 * num4;
        if (x > 255f)
        {
            x = 255f;
        }
        if (num6 > 255f)
        {
            num6 = 255f;
        }
        if (num7 > 255f)
        {
            num7 = 255f;
        }
        if (x > (float)(int)((Color)(ref colorOfSurfaceBackgroundsModified)).R)
        {
            ((Color)(ref colorOfSurfaceBackgroundsModified)).R = (byte)x;
        }
        if (num6 > (float)(int)((Color)(ref colorOfSurfaceBackgroundsModified)).G)
        {
            ((Color)(ref colorOfSurfaceBackgroundsModified)).G = (byte)num6;
        }
        if (num7 > (float)(int)((Color)(ref colorOfSurfaceBackgroundsModified)).B)
        {
            ((Color)(ref colorOfSurfaceBackgroundsModified)).B = (byte)num7;
        }
        bgScale = 1.32f;
        bgScale *= bgGlobalScaleMultiplier;
        LoadBackground(bgTexIndexes[1]);
        bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[1]] * bgScale);
        bgParallax = 0.43;
        SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
        bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
        bgTopY = (int)(backgroundTopMagicNumber * 1950.0 + 1675.0) + (int)scAdj + pushBGTopHack;
        SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
        if (gameMenu)
        {
            bgTopY = 400 + pushBGTopHack;
            bgStartX -= 80;
        }
        if (bgWidthScaled == 0)
        {
            return;
        }
        bgLoops = screenWidth / bgWidthScaled + 2;
        if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
        {
            for (int j = 0; j < bgLoops; j++)
            {
                spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[1]].Value, new Vector2((float)(bgStartX + bgWidthScaled * j), (float)bgTopY), GetBackgroundRect(bgTexIndexes[1]), colorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
            }
        }
        colorOfSurfaceBackgroundsModified = ColorOfSurfaceBackgroundsModified;
        num5 = (float)rand.Next(28, 42) * 0.001f;
        num5 += (float)(270 - mouseTextColor) / 3000f;
        x = vector3.X;
        num6 = vector3.Y + num5 / 2f;
        num7 = vector3.Z + num5;
        x *= 255f * num4 * num3;
        num6 *= 255f * num4 * num3;
        num7 *= 255f * num4 * num3;
        if (x > 255f)
        {
            x = 255f;
        }
        if (num6 > 255f)
        {
            num6 = 255f;
        }
        if (num7 > 255f)
        {
            num7 = 255f;
        }
        if (x > (float)(int)((Color)(ref colorOfSurfaceBackgroundsModified)).R)
        {
            ((Color)(ref colorOfSurfaceBackgroundsModified)).R = (byte)x;
        }
        if (num6 > (float)(int)((Color)(ref colorOfSurfaceBackgroundsModified)).G)
        {
            ((Color)(ref colorOfSurfaceBackgroundsModified)).G = (byte)num6;
        }
        if (num7 > (float)(int)((Color)(ref colorOfSurfaceBackgroundsModified)).B)
        {
            ((Color)(ref colorOfSurfaceBackgroundsModified)).B = (byte)num7;
        }
        bgScale = 1.36f;
        bgScale *= bgGlobalScaleMultiplier;
        LoadBackground(bgTexIndexes[2]);
        bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[2]] * bgScale);
        bgParallax = 0.49;
        SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
        bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
        bgTopY = (int)(backgroundTopMagicNumber * 2100.0 + 1950.0) + (int)scAdj + pushBGTopHack;
        SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
        if (gameMenu)
        {
            bgTopY = 480 + pushBGTopHack;
            bgStartX -= 120;
        }
        if (bgWidthScaled == 0)
        {
            return;
        }
        bgLoops = screenWidth / bgWidthScaled + 2;
        if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
        {
            for (int k = 0; k < bgLoops; k++)
            {
                spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[2]].Value, new Vector2((float)(bgStartX + bgWidthScaled * k), (float)bgTopY), GetBackgroundRect(bgTexIndexes[2]), colorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
            }
        }
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f);
    }
References Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundWidth, Terraria.Main.bgLoops, Terraria.Main.bgParallax, Terraria.Main.bgScale, Terraria.Main.bgStartX, Terraria.Main.bgTopY, Terraria.Main.bgWidthScaled, Terraria.Graphics.Light.Color, Terraria.Main.ColorOfSurfaceBackgroundsModified, Terraria.Graphics.Effects.SkyManager.DrawToDepth(), Terraria.Main.gameMenu, Terraria.Main.GetBackgroundRect(), Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.LoadBackground(), Terraria.Main.mouseTextColor, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Main.scAdj, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.SetBackgroundOffsets(), Terraria.Main.spriteBatch, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DrawSurfaceBG().