TModLoader: Terraria.Main.DrawUnderworldBackground
DrawUnderworldBackground()
void Terraria.Main.DrawUnderworldBackground (bool flat) inline protected
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        if (!(screenPosition.Y + (float)screenHeight < (float)(maxTilesY - 220) * 16f))
        {
            Vector2 screenOffset = screenPosition + new Vector2((float)(screenWidth >> 1), (float)(screenHeight >> 1));
            float pushUp = (GameViewMatrix.Zoom.Y - 1f) * 0.5f * 200f;
            SkyManager.Instance.ResetDepthTracker();
            for (int num = 4; num >= 0; num--)
            {
                DrawUnderworldBackgroudLayer(flat, screenOffset, pushUp, num);
            }
            if (!mapFullscreen)
            {
                SkyManager.Instance.DrawRemainingDepth(spriteBatch);
            }
            DrawSurfaceBG_DrawChangeOverlay(12);
        }
    }
References Terraria.Graphics.Effects.SkyManager.DrawRemainingDepth(), Terraria.Main.DrawSurfaceBG_DrawChangeOverlay(), Terraria.Main.DrawUnderworldBackgroudLayer(), Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.mapFullscreen, Terraria.Main.maxTilesY, Terraria.Graphics.Effects.SkyManager.ResetDepthTracker(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawBG(), and Terraria.Main.DrawCapture().