TModLoader: Terraria.Main.DrawProj_FlailChains
DrawProj_FlailChains()
static void Terraria.Main.DrawProj_FlailChains (Projectile proj, Vector2 mountedCenter) inline static private
Definition at line 45312 of file Main.cs.
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_0126: Unknown result type (might be due to invalid IL or missing references)
        //IL_0130: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0118: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0140: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0176: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0282: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        //IL_028f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0293: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_026a: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[proj.owner];
        Vector2 playerArmPosition = GetPlayerArmPosition(proj);
        playerArmPosition -= Vector2.UnitY * player.gfxOffY;
        Asset<Texture2D> asset = null;
        Rectangle? sourceRectangle = null;
        float num = 0f;
        switch (proj.type)
        {
        default:
            asset = TextureAssets.Chain3;
            break;
        case 25:
            asset = TextureAssets.Chain2;
            break;
        case 35:
            asset = TextureAssets.Chain6;
            break;
        case 63:
            asset = TextureAssets.Chain7;
            break;
        case 154:
            asset = TextureAssets.Chain13;
            break;
        case 247:
            asset = TextureAssets.Chain19;
            break;
        case 757:
            asset = TextureAssets.Extra[99];
            sourceRectangle = asset.Frame(1, 6);
            num = -2f;
            break;
        case 947:
            asset = TextureAssets.Chain41;
            break;
        case 948:
            asset = TextureAssets.Chain43;
            break;
        }
        Vector2 origin = (sourceRectangle.HasValue ? (sourceRectangle.Value.Size() / 2f) : (asset.Size() / 2f));
        Vector2 center = proj.Center;
        Vector2 v = playerArmPosition.MoveTowards(center, 4f) - center;
        Vector2 vector = v.SafeNormalize(Vector2.Zero);
        float num2 = (float)(sourceRectangle.HasValue ? sourceRectangle.Value.Height : asset.Height()) + num;
        float rotation = vector.ToRotation() + (float)Math.PI / 2f;
        int num3 = 0;
        float num4 = ((Vector2)(ref v)).Length() + num2 / 2f;
        int num5 = 0;
        while (num4 > 0f)
        {
            Color color = Lighting.GetColor((int)center.X / 16, (int)(center.Y / 16f));
            switch (proj.type)
            {
            case 757:
                sourceRectangle = asset.Frame(1, 6, 0, num3 % 6);
                break;
            case 948:
                if (num5 >= 6)
                {
                    asset = (asset = TextureAssets.Chain41);
                }
                else if (num5 >= 4)
                {
                    asset = (asset = TextureAssets.Chain42);
                    byte b = 140;
                    if (((Color)(ref color)).R < b)
                    {
                        ((Color)(ref color)).R = b;
                    }
                    if (((Color)(ref color)).G < b)
                    {
                        ((Color)(ref color)).G = b;
                    }
                    if (((Color)(ref color)).B < b)
                    {
                        ((Color)(ref color)).B = b;
                    }
                }
                else
                {
                    color = Color.White;
                }
                num5++;
                break;
            }
            spriteBatch.Draw(asset.Value, center - screenPosition, sourceRectangle, color, rotation, origin, 1f, (SpriteEffects)0, 0f);
            center += vector * num2;
            num3++;
            num4 -= num2;
        }
    }
References Terraria.GameContent.TextureAssets.Chain13, Terraria.GameContent.TextureAssets.Chain19, Terraria.GameContent.TextureAssets.Chain2, Terraria.GameContent.TextureAssets.Chain3, Terraria.GameContent.TextureAssets.Chain41, Terraria.GameContent.TextureAssets.Chain42, Terraria.GameContent.TextureAssets.Chain43, Terraria.GameContent.TextureAssets.Chain6, Terraria.GameContent.TextureAssets.Chain7, Terraria.Graphics.Light.Color, Terraria.GameContent.TextureAssets.Extra, Terraria.Lighting.GetColor(), Terraria.Main.GetPlayerArmPosition(), Terraria.Player.gfxOffY, Terraria.Main.player, Terraria.Main.screenPosition, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawProj_DrawExtras().