TModLoader: Terraria.Main.DrawProj_Inner
DrawProj_Inner()
void Terraria.Main.DrawProj_Inner (Projectile proj) inline private
    {
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        float polePosX = 0f;
        float polePosY = 0f;
        LoadProjectile(proj.type);
        Vector2 mountedCenter = player[proj.owner].MountedCenter;
        if (player[proj.owner].mount.Active && player[proj.owner].mount.Type == 52)
        {
            mountedCenter += new Vector2((float)(player[proj.owner].direction * 14), -10f);
        }
        if (ProjectileLoader.PreDrawExtras(proj))
        {
            DrawProj_DrawYoyoString(proj, mountedCenter);
            DrawProj_DrawExtras(proj, mountedCenter, ref polePosX, ref polePosY);
        }
        DrawProj_Inner_DoDrawProj(proj, mountedCenter, polePosX, polePosY);
    }
References Terraria.Mount.Active, Terraria.Entity.direction, Terraria.Main.DrawProj_DrawExtras(), Terraria.Main.DrawProj_DrawYoyoString(), Terraria.Main.DrawProj_Inner_DoDrawProj(), Terraria.Main.LoadProjectile(), Terraria.Player.mount, Terraria.Player.MountedCenter, Terraria.Main.player, Terraria.ModLoader.ProjectileLoader.PreDrawExtras(), and Terraria.Mount.Type.
Referenced by Terraria.Main.DrawProjDirect().