TModLoader: Terraria.Main.InSmartCursorHighlightArea
InSmartCursorHighlightArea()
static bool Terraria.Main.InSmartCursorHighlightArea (int x, int y, out bool actuallySelected) inline static
    {
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        actuallySelected = SmartInteractTileCoordsSelected.Contains(new Point(x, y));
        if (hideUI)
        {
            return false;
        }
        if (Collision.InTileBounds(x, y, TileInteractionLX, TileInteractionLY, TileInteractionHX, TileInteractionHY))
        {
            return SmartInteractTileCoords.Contains(new Point(x, y));
        }
        return false;
    }
References Terraria.Main.hideUI, Terraria.Collision.InTileBounds(), Terraria.Main.SmartInteractTileCoords, Terraria.Main.SmartInteractTileCoordsSelected, Terraria.Main.TileInteractionHX, Terraria.Main.TileInteractionHY, Terraria.Main.TileInteractionLX, and Terraria.Main.TileInteractionLY.
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup_2(), Terraria.ModLoader.ModPylon.DefaultDrawPylonCrystal(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.GameContent.Drawing.TileDrawing.DrawVoidLenses(), and Terraria.GameContent.Drawing.TileDrawing.GetTileOutlineInfo().