TModLoader: Terraria.Main.DrawStar
DrawStar()
void Terraria.Main.DrawStar (ref SceneArea sceneArea, float starOpacity, Color bgColorForStars, int i, Star theStar, bool artificial, bool foreground = false) inline private
Definition at line 79943 of file Main.cs.
    {
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_021a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0352: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0361: Unknown result type (might be due to invalid IL or missing references)
        //IL_029f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0303: Unknown result type (might be due to invalid IL or missing references)
        //IL_032d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0336: Unknown result type (might be due to invalid IL or missing references)
        //IL_033b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0239: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0536: Unknown result type (might be due to invalid IL or missing references)
        //IL_0542: Unknown result type (might be due to invalid IL or missing references)
        //IL_054a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0278: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0404: Unknown result type (might be due to invalid IL or missing references)
        //IL_0406: Unknown result type (might be due to invalid IL or missing references)
        //IL_0408: Unknown result type (might be due to invalid IL or missing references)
        //IL_0417: Unknown result type (might be due to invalid IL or missing references)
        //IL_0420: Unknown result type (might be due to invalid IL or missing references)
        //IL_0479: Unknown result type (might be due to invalid IL or missing references)
        //IL_047e: Unknown result type (might be due to invalid IL or missing references)
        //IL_049d: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d8: Unknown result type (might be due to invalid IL or missing references)
        if (theStar == null || theStar.hidden)
        {
            return;
        }
        float num = shimmerAlpha;
        Color color = default(Color);
        float num3 = 1f - theStar.fadeIn;
        int num4 = (int)((float)(255 - ((Color)(ref bgColorForStars)).R - 100) * theStar.twinkle * num3);
        int num5 = (int)((float)(255 - ((Color)(ref bgColorForStars)).G - 100) * theStar.twinkle * num3);
        int num6 = (int)((float)(255 - ((Color)(ref bgColorForStars)).B - 100) * theStar.twinkle * num3);
        num4 = (num4 + num6 + num5) / 3;
        if (num4 <= 0)
        {
            return;
        }
        num4 = (int)((double)num4 * 1.4);
        if (num4 > 255)
        {
            num4 = 255;
        }
        num5 = num4;
        num6 = num4;
        ((Color)(ref color)).R = (byte)num4;
        ((Color)(ref color)).G = (byte)num5;
        ((Color)(ref color)).B = (byte)num6;
        color *= starOpacity;
        if (num > 0f)
        {
            Color value = color;
            if (i % 3 == 0)
            {
                ((Color)(ref value)).G = (byte)((float)(int)((Color)(ref color)).G * (1f - num * 0f) * theStar.twinkle * theStar.twinkle);
            }
            else if (i % 3 == 1)
            {
                ((Color)(ref value)).B = (byte)((float)(int)((Color)(ref color)).B * (1f - num * 0f) * theStar.twinkle * theStar.twinkle);
            }
            else if (i % 3 == 2)
            {
                ((Color)(ref value)).R = (byte)((float)(int)((Color)(ref color)).R * (1f - num * 0f) * theStar.twinkle * theStar.twinkle);
            }
            color = Color.Lerp(color, value, num);
            color = ((!artificial) ? (color * (1f - num)) : (color * num));
        }
        Vector2 vector = new Vector2(theStar.position.X / 1920f, theStar.position.Y / 1200f) * new Vector2(sceneArea.totalWidth, sceneArea.totalHeight) + new Vector2(0f, (float)sceneArea.bgTopY) + sceneArea.SceneLocalScreenPositionOffset;
        if (!theStar.falling)
        {
            if (vector.X < 0f)
            {
                vector.X += screenWidth;
            }
            if (vector.X > (float)screenWidth)
            {
                vector.X -= screenWidth;
            }
            if (vector.Y < 0f)
            {
                vector.Y += screenHeight;
            }
            if (vector.Y > (float)screenHeight)
            {
                vector.Y -= screenHeight;
            }
        }
        if (foreground)
        {
            Vector2 val = vector / ScreenSize.ToVector2();
            float fromMax = 0.35f;
            float num7 = Utils.Remap(Vector2.Distance(val, new Vector2(0.5f, 0.5f)), 0f, fromMax, 0f, 1f);
            color *= num7;
            Color color2 = Lighting.GetColor((vector + screenPosition).ToTileCoordinates());
            float num8 = (float)(int)Math.Max(Math.Max(((Color)(ref color2)).R, ((Color)(ref color2)).G), ((Color)(ref color2)).B) / 255f;
            color *= 1f - num8;
        }
        Texture2D value2 = TextureAssets.Star[theStar.type].Value;
        Vector2 origin = value2.Size() / 2f;
        if (theStar.falling)
        {
            theStar.fadeIn = 0f;
            double num9 = theStar.fallTime;
            float num10 = 30f;
            if ((float)num9 > num10)
            {
                num9 = (int)num10;
            }
            for (int j = 1; (double)j < num9; j++)
            {
                Vector2 vector2 = theStar.fallSpeed * (float)j * 0.4f;
                float num2 = theStar.scale * (1f - (float)j * 1f / num10);
                Color color3 = color;
                _ = theStar.rotation;
                color3 *= 1f - (float)j * 1f / num10;
                spriteBatch.Draw(value2, vector - vector2, (Rectangle?)null, color3, theStar.rotation, origin, num2 * theStar.twinkle * ForcedMinimumZoom, (SpriteEffects)0, 0f);
            }
            if (starGame && theStar.fallSpeed.Y > 0f && Vector2.Distance(new Vector2((float)mouseX, (float)mouseY), vector) < 70f)
            {
                starsHit++;
                theStar.fallSpeed = vector - new Vector2((float)mouseX, (float)mouseY);
                ((Vector2)(ref theStar.fallSpeed)).Normalize();
                theStar.fallSpeed *= 10f;
                if (theStar.fallSpeed.Y > 0f)
                {
                    theStar.fallSpeed.Y *= -1f;
                }
                SoundEngine.PlaySound(38);
                SoundEngine.PlaySound(37);
            }
        }
        spriteBatch.Draw(value2, vector, (Rectangle?)null, color, theStar.rotation, origin, theStar.scale * theStar.twinkle * ForcedMinimumZoom, (SpriteEffects)0, 0f);
    }
References Terraria.Graphics.Light.Color, Terraria.Main.ForcedMinimumZoom, Terraria.Lighting.GetColor(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Utils.Remap(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.ScreenSize, Terraria.Main.screenWidth, Terraria.Main.shimmerAlpha, Terraria.Main.spriteBatch, Terraria.GameContent.TextureAssets.Star, Terraria.Main.starGame, and Terraria.Main.starsHit.
Referenced by Terraria.Main.DrawStarsInBackground().