TModLoader: Terraria.Main.DrawEmoteBubblesButton
DrawEmoteBubblesButton()
static void Terraria.Main.DrawEmoteBubblesButton (int pivotTopLeftX, int pivotTopLeftY) inline static private
Definition at line 54839 of file Main.cs.
    {
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        inventoryScale = 0.85f;
        int num = (int)((float)(450 + pivotTopLeftX) - 56f * inventoryScale);
        int num2 = 258 + pivotTopLeftY;
        int num3 = 244;
        int width = 30;
        int num4 = 30;
        num = 534;
        num2 = num3 + num4 + 4;
        if ((player[myPlayer].chest != -1 || npcShop > 0) && !recBigList)
        {
            num2 += 168;
            inventoryScale = 0.755f;
            num += 5;
            num3 += 24;
        }
        if (editChest)
        {
            num2 += 24;
        }
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector(num, num2, (int)((float)TextureAssets.InventoryBack.Width() * inventoryScale), (int)((float)TextureAssets.InventoryBack.Height() * inventoryScale));
        ((Rectangle)(ref rectangle))._002Ector(num, num2, width, num4);
        bool flag = false;
        if (((Rectangle)(ref rectangle)).Contains(new Point(mouseX, mouseY)) && !PlayerInput.IgnoreMouseInterface)
        {
            player[myPlayer].mouseInterface = true;
            flag = true;
            if (mouseLeft && mouseLeftRelease)
            {
                player[myPlayer].SetTalkNPC(-1);
                npcChatCornerItem = 0;
                npcChatText = "";
                mouseLeftRelease = false;
                SoundEngine.PlaySound(12);
                IngameFancyUI.OpenUIState(new UIEmotesMenu());
            }
        }
        Texture2D value = TextureAssets.EmoteMenuButton.Value;
        Vector2 position = ((Rectangle)(ref rectangle)).Center.ToVector2();
        Rectangle rectangle2 = value.Frame(2, 1, flag ? 1 : 0);
        rectangle2.Width -= 2;
        rectangle2.Height -= 2;
        Vector2 origin = rectangle2.Size() / 2f;
        Color white = Color.White;
        spriteBatch.Draw(value, position, (Rectangle?)rectangle2, white, 0f, origin, 1f, (SpriteEffects)0, 0f);
        UILinkPointNavigator.SetPosition(309, position);
        if (!mouseText && flag)
        {
            instance.MouseText(Language.GetTextValue("GameUI.Emote"), 0, 0);
        }
    }
References Terraria.Main.chest, Terraria.Graphics.Light.Color, Terraria.Main.editChest, Terraria.GameContent.TextureAssets.EmoteMenuButton, Terraria.Localization.Language.GetTextValue(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.instance, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.Main.inventoryScale, Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseText, Terraria.Main.MouseText(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.npcChatCornerItem, Terraria.Main.npcChatText, Terraria.Main.npcShop, Terraria.UI.IngameFancyUI.OpenUIState(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.recBigList, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Player.SetTalkNPC(), and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawInventory().