TModLoader: Terraria.Main.CheckMonoliths
CheckMonoliths()
static void Terraria.Main.CheckMonoliths () inline static private
    {
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0169: Unknown result type (might be due to invalid IL or missing references)
        if (dedServ)
        {
            return;
        }
        bool flag = player[myPlayer].ZoneTowerVortex || player[myPlayer].ZoneTowerNebula || player[myPlayer].ZoneTowerStardust || player[myPlayer].ZoneTowerSolar;
        bool stardustMonolithShader = player[myPlayer].stardustMonolithShader;
        bool nebulaMonolithShader = player[myPlayer].nebulaMonolithShader;
        bool vortexMonolithShader = player[myPlayer].vortexMonolithShader;
        bool solarMonolithShader = player[myPlayer].solarMonolithShader;
        bool moonLordMonolithShader = player[myPlayer].moonLordMonolithShader;
        for (int i = 0; i < MonolithFilterNames.Length; i++)
        {
            bool flag2 = !flag && i == SceneMetrics.ActiveMonolithType;
            if ((i == 0 && vortexMonolithShader) || (i == 1 && nebulaMonolithShader) || (i == 2 && stardustMonolithShader) || (i == 3 && solarMonolithShader) || (i == 4 && moonLordMonolithShader))
            {
                flag2 = true;
            }
            if (flag2)
            {
                if (!Terraria.Graphics.Effects.Filters.Scene[MonolithFilterNames[i]].IsActive())
                {
                    Terraria.Graphics.Effects.Filters.Scene.Activate(MonolithFilterNames[i], default(Vector2));
                }
                if (!SkyManager.Instance[MonolithSkyNames[i]].IsActive())
                {
                    SkyManager.Instance.Activate(MonolithSkyNames[i], default(Vector2));
                }
            }
            else
            {
                if (Terraria.Graphics.Effects.Filters.Scene[MonolithFilterNames[i]].IsActive())
                {
                    Terraria.Graphics.Effects.Filters.Scene.Deactivate(MonolithFilterNames[i]);
                }
                if (SkyManager.Instance[MonolithSkyNames[i]].IsActive())
                {
                    SkyManager.Instance.Deactivate(MonolithSkyNames[i]);
                }
            }
        }
    }
References Terraria.Graphics.Effects.EffectManager< T >.Activate(), Terraria.SceneMetrics.ActiveMonolithType, Terraria.Graphics.Effects.EffectManager< T >.Deactivate(), Terraria.Main.dedServ, Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.MonolithFilterNames, Terraria.Main.MonolithSkyNames, Terraria.Player.moonLordMonolithShader, Terraria.Main.myPlayer, Terraria.Player.nebulaMonolithShader, Terraria.Main.player, Terraria.Graphics.Effects.Filters.Scene, Terraria.Player.solarMonolithShader, Terraria.Player.stardustMonolithShader, Terraria.Player.vortexMonolithShader, Terraria.Player.ZoneTowerNebula, Terraria.Player.ZoneTowerSolar, Terraria.Player.ZoneTowerStardust, and Terraria.Player.ZoneTowerVortex.
Referenced by Terraria.Main.DoDraw().