TModLoader: Terraria.Main.CheckInvasionProgressDisplay
CheckInvasionProgressDisplay()
static void Terraria.Main.CheckInvasionProgressDisplay () inline static
Definition at line 61292 of file Main.cs.
    {
        //IL_03a9: Unknown result type (might be due to invalid IL or missing references)
        if (invasionProgressMode != 2)
        {
            invasionProgressNearInvasion = false;
            return;
        }
        bool flag = false;
        Player player = Main.player[myPlayer];
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector((int)screenPosition.X, (int)screenPosition.Y, screenWidth, screenHeight);
        int num = 5000;
        int num2 = 0;
        Rectangle value = default(Rectangle);
        for (int i = 0; i < 200; i++)
        {
            if (!npc[i].active)
            {
                continue;
            }
            num2 = 0;
            switch (npc[i].type)
            {
            case 338:
            case 339:
            case 340:
            case 341:
            case 342:
            case 343:
            case 344:
            case 345:
            case 346:
            case 347:
            case 348:
            case 349:
            case 350:
                num2 = 1;
                break;
            case 305:
            case 306:
            case 307:
            case 308:
            case 309:
            case 310:
            case 311:
            case 312:
            case 313:
            case 314:
            case 315:
            case 325:
            case 326:
            case 327:
            case 329:
            case 330:
                num2 = 2;
                break;
            case 26:
            case 27:
            case 28:
            case 29:
            case 111:
                num2 = 4;
                break;
            case 143:
            case 144:
            case 145:
                num2 = 5;
                break;
            case 212:
            case 213:
            case 214:
            case 215:
            case 216:
            case 491:
                num2 = 6;
                break;
            case 381:
            case 382:
            case 383:
            case 385:
            case 386:
            case 388:
            case 389:
            case 390:
            case 391:
            case 395:
                num2 = 7;
                break;
            case 548:
            case 549:
            case 551:
            case 552:
            case 553:
            case 554:
            case 555:
            case 556:
            case 557:
            case 558:
            case 559:
            case 560:
            case 561:
            case 562:
            case 563:
            case 564:
            case 565:
            case 568:
            case 569:
            case 570:
            case 571:
            case 572:
            case 573:
            case 574:
            case 575:
            case 576:
            case 577:
            case 578:
                num2 = 3;
                break;
            }
            if (num2 != 0 && (num2 != 1 || (!((double)player.position.Y > worldSurface * 16.0) && !dayTime && snowMoon)) && (num2 != 2 || (!((double)player.position.Y > worldSurface * 16.0) && !dayTime && pumpkinMoon)) && (num2 != 3 || DD2Event.Ongoing) && (num2 <= 3 || (!((double)player.position.Y > worldSurface * 16.0) && invasionType == num2 - 3)))
            {
                ((Rectangle)(ref value))._002Ector((int)(npc[i].position.X + (float)(npc[i].width / 2)) - num, (int)(npc[i].position.Y + (float)(npc[i].height / 2)) - num, num * 2, num * 2);
                if (((Rectangle)(ref rectangle)).Intersects(value))
                {
                    flag = true;
                    break;
                }
            }
        }
        invasionProgressNearInvasion = flag;
        if (!flag || invasionProgressIcon != 0)
        {
            return;
        }
        int waveNumber = NPC.waveNumber;
        if (snowMoon)
        {
            int progressMax = NPC.MoonEventRequiredPointsPerWaveLookup[waveNumber];
            ReportInvasionProgress((int)NPC.waveKills, progressMax, 1, waveNumber);
            return;
        }
        if (pumpkinMoon)
        {
            int progressMax2 = NPC.MoonEventRequiredPointsPerWaveLookup[waveNumber];
            ReportInvasionProgress((int)NPC.waveKills, progressMax2, 2, waveNumber);
            return;
        }
        if (DD2Event.Ongoing)
        {
            DD2Event.ReportEventProgress();
            return;
        }
        int progressMax3 = 1;
        if (invasionType != 0 && invasionSizeStart != 0)
        {
            progressMax3 = invasionSizeStart;
        }
        ReportInvasionProgress(invasionSizeStart - invasionSize, progressMax3, num2, 0);
    }
References Terraria.Main.dayTime, Terraria.Main.invasionProgressIcon, Terraria.Main.invasionProgressMode, Terraria.Main.invasionProgressNearInvasion, Terraria.Main.invasionSize, Terraria.Main.invasionSizeStart, Terraria.Main.invasionType, Terraria.NPC.MoonEventRequiredPointsPerWaveLookup, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.pumpkinMoon, Terraria.GameContent.Events.DD2Event.ReportEventProgress(), Terraria.Main.ReportInvasionProgress(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.snowMoon, Terraria.NPC.waveKills, Terraria.NPC.waveNumber, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DoUpdate().