TModLoader: Terraria.Main.DrawMurderAurora
DrawMurderAurora()
void Terraria.Main.DrawMurderAurora (Projectile proj) inline private
    {
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0040: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cd: Unknown result type (might be due to invalid IL or missing references)
        Texture2D value = TextureAssets.Projectile[proj.type].Value;
        Vector2 origin = value.Size() / 2f;
        float num = GlobalTimeWrappedHourly % 10f / 10f;
        Vector2 vector = proj.Center - screenPosition;
        float[] array = new float[15];
        float[] array2 = new float[15];
        float[] array3 = new float[15];
        float[] array4 = new float[15];
        float[] array5 = new float[15];
        float num2 = 0.5f;
        int num3 = 210;
        num2 = Utils.GetLerpValue(0f, 60f, proj.timeLeft, clamped: true) * Utils.GetLerpValue(num3, num3 - 60, proj.timeLeft, clamped: true);
        float amount = Utils.GetLerpValue(0f, 60f, proj.timeLeft, clamped: true) * Utils.GetLerpValue(num3, 90f, proj.timeLeft, clamped: true);
        amount = MathHelper.Lerp(0.2f, 0.5f, amount);
        float num9 = 800f / (float)value.Width;
        float num4 = num9 * 0.8f;
        float num5 = (num9 - num4) / 15f;
        float num6 = 30f;
        float num7 = 300f;
        Vector2 vector2 = default(Vector2);
        ((Vector2)(ref vector2))._002Ector(3f, 6f);
        for (int i = 0; i < 15; i++)
        {
            _ = (float)(i + 1) / 50f;
            float num8 = (float)Math.Sin(num * ((float)Math.PI * 2f) + (float)Math.PI / 2f + (float)i / 2f);
            array[i] = num8 * (num7 - (float)i * 3f);
            array2[i] = (float)Math.Sin(num * ((float)Math.PI * 2f) * 2f + (float)Math.PI / 3f + (float)i) * num6;
            array2[i] -= (float)i * 3f;
            array3[i] = (float)i / 15f * 2f + num;
            array3[i] = (num8 * 0.5f + 0.5f) * 0.6f + num;
            array4[i] = (float)(1.0 - Math.Pow(1f * (float)i / 15f, 2.0));
            array5[i] = num4 + (float)(i + 1) * num5;
            array5[i] *= 0.3f;
            Color color = hslToRgb(array3[i] % 1f, 1f, 0.5f) * num2 * amount;
            ((Color)(ref color)).A = (byte)(((Color)(ref color)).A / 4);
            float rotation = (float)Math.PI / 2f + num8 * ((float)Math.PI / 4f) * -0.3f + (float)Math.PI * (float)i;
            EntitySpriteDraw(value, vector + new Vector2(array[i], array2[i]), null, color, rotation, origin, new Vector2(array5[i], array5[i]) * vector2, (SpriteEffects)0);
        }
    }
References Terraria.Graphics.Light.Color, Terraria.Main.EntitySpriteDraw(), Terraria.Utils.GetLerpValue(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.hslToRgb(), Terraria.GameContent.TextureAssets.Projectile, and Terraria.Main.screenPosition.
Referenced by Terraria.Main.DrawProj_DrawSpecialProjs().