TModLoader: Terraria.Main.DrawInterface_40_InteractItemIcon
DrawInterface_40_InteractItemIcon()
void Terraria.Main.DrawInterface_40_InteractItemIcon () inline private
Definition at line 58132 of file Main.cs.
    {
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        //IL_0198: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_025d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0264: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0277: Unknown result type (might be due to invalid IL or missing references)
        //IL_027d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0281: Unknown result type (might be due to invalid IL or missing references)
        //IL_039f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0307: Unknown result type (might be due to invalid IL or missing references)
        //IL_0311: Unknown result type (might be due to invalid IL or missing references)
        //IL_031a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0320: Unknown result type (might be due to invalid IL or missing references)
        //IL_0324: Unknown result type (might be due to invalid IL or missing references)
        //IL_0430: Unknown result type (might be due to invalid IL or missing references)
        //IL_045c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0466: Unknown result type (might be due to invalid IL or missing references)
        //IL_046f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0475: Unknown result type (might be due to invalid IL or missing references)
        if (HoveringOverAnNPC || LocalPlayer.mouseInterface)
        {
            return;
        }
        Item item = player[myPlayer].inventory[player[myPlayer].selectedItem];
        int num = item.type;
        if (player[myPlayer].UsingBiomeTorches)
        {
            switch (num)
            {
            case 8:
                num = player[myPlayer].BiomeTorchHoldStyle(num);
                break;
            case 966:
                num = player[myPlayer].BiomeCampfireHoldStyle(num);
                break;
            }
        }
        if (player[myPlayer].cursorItemIconID != 0)
        {
            num = player[myPlayer].cursorItemIconID;
        }
        bool flag = player[myPlayer].cursorItemIconEnabled && (player[myPlayer].inventory[player[myPlayer].selectedItem].type > 0 || player[myPlayer].cursorItemIconID != 0);
        ItemIconCacheVerification();
        bool flag2 = _itemIconCacheTime > 0 && mouseItem.type < 1;
        if (!(flag || flag2))
        {
            return;
        }
        int t = _itemIconCacheSelectedItemID;
        if (!flag)
        {
            Utils.Swap(ref t, ref player[myPlayer].cursorItemIconID);
        }
        Color currentColor = player[myPlayer].inventory[player[myPlayer].selectedItem].GetAlpha(Color.White);
        Color color = player[myPlayer].inventory[player[myPlayer].selectedItem].GetColor(Color.White);
        if (player[myPlayer].cursorItemIconID != 0)
        {
            currentColor = Color.White;
            color = default(Color);
        }
        if (player[myPlayer].cursorItemIconID == 269)
        {
            currentColor = player[myPlayer].shirtColor;
        }
        float num2 = 1f;
        num2 = cursorScale;
        ItemSlot.GetItemLight(ref currentColor, num);
        SpriteEffects effects = (SpriteEffects)0;
        if (player[myPlayer].cursorItemIconReversed)
        {
            effects = (SpriteEffects)1;
        }
        if (num > 0)
        {
            int num3 = 10 + player[myPlayer].cursorItemIconPush;
            instance.LoadItem(num);
            spriteBatch.Draw(TextureAssets.Item[num].Value, new Vector2((float)(mouseX + num3), (float)(mouseY + num3)), (Rectangle?)Item.GetDrawHitbox(num, null), currentColor, 0f, default(Vector2), num2, effects, 0f);
            if (num == item.type && TryGetAmmo(item, out var ammoItem, out var ammoColor, out var ammoScale, out var ammoOffset))
            {
                float scale = num2 * ammoScale;
                int type = ammoItem.type;
                Color alpha = ammoItem.GetAlpha(ammoColor);
                instance.LoadItem(type);
                spriteBatch.Draw(TextureAssets.Item[type].Value, new Vector2((float)(mouseX + 10), (float)(mouseY + 10)) + ammoOffset, (Rectangle?)Item.GetDrawHitbox(type, null), alpha, 0f, default(Vector2), scale, effects, 0f);
            }
        }
        if (player[myPlayer].cursorItemIconText != "")
        {
            MouseText(player[myPlayer].cursorItemIconText, 0, 0);
        }
        if (player[myPlayer].cursorItemIconID == 0 && player[myPlayer].inventory[player[myPlayer].selectedItem].color != default(Color))
        {
            instance.LoadItem(player[myPlayer].inventory[player[myPlayer].selectedItem].type);
            spriteBatch.Draw(TextureAssets.Item[player[myPlayer].inventory[player[myPlayer].selectedItem].type].Value, new Vector2((float)(mouseX + 10), (float)(mouseY + 10)), (Rectangle?)Item.GetDrawHitbox(player[myPlayer].inventory[player[myPlayer].selectedItem].type, null), color, 0f, default(Vector2), num2, (SpriteEffects)0, 0f);
        }
        if (!flag)
        {
            Utils.Swap(ref t, ref player[myPlayer].cursorItemIconID);
        }
    }
References Terraria.Main._itemIconCacheSelectedItemID, Terraria.Main._itemIconCacheTime, Terraria.Main.cursorScale, Terraria.Item.GetDrawHitbox(), Terraria.UI.ItemSlot.GetItemLight(), Terraria.Main.HoveringOverAnNPC, Terraria.Main.instance, Terraria.GameContent.TextureAssets.Item, Terraria.Main.item, Terraria.Main.ItemIconCacheVerification(), Terraria.Main.LocalPlayer, Terraria.Main.MouseText(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.spriteBatch, and Terraria.Main.TryGetAmmo().
Referenced by Terraria.Main.DrawInterface_11_IngameOptionsMenu(), and Terraria.Main.SetupDrawInterfaceLayers().