TModLoader: Terraria.Main.TryInteractingWithVoidLens
TryInteractingWithVoidLens()
static int Terraria.Main.TryInteractingWithVoidLens (Projectile proj) inline static private
Definition at line 48537 of file Main.cs.
    {
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_019f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        if (gamePaused || gameMenu)
        {
            return 0;
        }
        bool flag = !SmartCursorIsUsed && !PlayerInput.UsingGamepad;
        Player localPlayer = LocalPlayer;
        Point point = proj.Center.ToTileCoordinates();
        Vector2 compareSpot = localPlayer.Center;
        if (!localPlayer.IsProjectileInteractibleAndInInteractionRange(proj, ref compareSpot))
        {
            return 0;
        }
        Matrix matrix = Matrix.Invert(GameViewMatrix.ZoomMatrix);
        Vector2 val = ReverseGravitySupport(MouseScreen);
        Vector2.Transform(screenPosition, matrix);
        Vector2 v = Vector2.Transform(val, matrix) + screenPosition;
        Rectangle hitbox = proj.Hitbox;
        bool flag2 = ((Rectangle)(ref hitbox)).Contains(v.ToPoint());
        if (!((flag2 || SmartInteractProj == proj.whoAmI) & !localPlayer.lastMouseInterface))
        {
            if (!flag)
            {
                return 1;
            }
            return 0;
        }
        HasInteractibleObjectThatIsNotATile = true;
        if (flag2)
        {
            localPlayer.noThrow = 2;
            localPlayer.cursorItemIconEnabled = true;
            localPlayer.cursorItemIconID = 4131;
        }
        if (PlayerInput.UsingGamepad)
        {
            localPlayer.GamepadEnableGrappleCooldown();
        }
        if (mouseRight && mouseRightRelease && Player.BlockInteractionWithProjectiles == 0)
        {
            mouseRightRelease = false;
            localPlayer.tileInteractAttempted = true;
            localPlayer.tileInteractionHappened = true;
            localPlayer.releaseUseTile = false;
            if (localPlayer.chest == -5)
            {
                localPlayer.chest = -1;
                SoundEngine.PlaySound(in SoundID.Item130);
                Recipe.FindRecipes();
            }
            else if (localPlayer.disableVoidBag < 0)
            {
                localPlayer.chest = -5;
                for (int i = 0; i < 40; i++)
                {
                    ItemSlot.SetGlow(i, -1f, chest: true);
                }
                localPlayer.voidLensChest.Set(proj);
                localPlayer.chestX = point.X;
                localPlayer.chestY = point.Y;
                localPlayer.SetTalkNPC(-1);
                SetNPCShopIndex(0);
                playerInventory = true;
                SoundEngine.PlaySound(in SoundID.Item130);
                Recipe.FindRecipes();
            }
        }
        if (!SmartCursorIsUsed && !PlayerInput.UsingGamepad)
        {
            return 0;
        }
        if (!flag)
        {
            return 2;
        }
        return 0;
    }
References Terraria.Player.BlockInteractionWithProjectiles, Terraria.Main.chest, Terraria.Recipe.FindRecipes(), Terraria.Main.gameMenu, Terraria.Main.gamePaused, Terraria.Main.GameViewMatrix, Terraria.Main.HasInteractibleObjectThatIsNotATile, Terraria.ID.SoundID.Item130, Terraria.Main.LocalPlayer, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.MouseScreen, Terraria.Main.playerInventory, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.ReverseGravitySupport(), Terraria.Main.screenPosition, Terraria.UI.ItemSlot.SetGlow(), Terraria.Main.SetNPCShopIndex(), Terraria.Main.SmartCursorIsUsed, Terraria.Main.SmartInteractProj, Terraria.GameInput.PlayerInput.UsingGamepad, and Terraria.Graphics.SpriteViewMatrix.ZoomMatrix.
Referenced by Terraria.Main.DrawProj_DrawVoidLens().