TModLoader: Terraria.Main.DrawSurfaceBG_Crimson
DrawSurfaceBG_Crimson()
void Terraria.Main.DrawSurfaceBG_Crimson (double backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack, int[] bgTexIndexes) inline private
Definition at line 76662 of file Main.cs.
    {
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_0363: Unknown result type (might be due to invalid IL or missing references)
        //IL_036f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0375: Unknown result type (might be due to invalid IL or missing references)
        //IL_0528: Unknown result type (might be due to invalid IL or missing references)
        //IL_0543: Unknown result type (might be due to invalid IL or missing references)
        //IL_054d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0559: Unknown result type (might be due to invalid IL or missing references)
        //IL_055f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01be: Unknown result type (might be due to invalid IL or missing references)
        if (bgTexIndexes[0] > -1)
        {
            bgScale = 1.25f;
            bgParallax = 0.4;
            bgTopY = (int)(backgroundTopMagicNumber * 1800.0 + 1500.0) + (int)scAdj + pushBGTopHack;
            SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
            bgScale *= bgGlobalScaleMultiplier;
            LoadBackground(bgTexIndexes[0]);
            bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[0]] * bgScale);
            SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
            bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
            if (bgTexIndexes[0] == 105)
            {
                bgTopY += 50;
            }
            if (bgTexIndexes[0] == 174)
            {
                bgTopY -= 350;
            }
            if (gameMenu)
            {
                bgTopY = 320 + pushBGTopHack;
            }
            bgLoops = screenWidth / bgWidthScaled + 2;
            if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
            {
                for (int i = 0; i < bgLoops; i++)
                {
                    spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[0]].Value, new Vector2((float)(bgStartX + bgWidthScaled * i), (float)bgTopY), (Rectangle?)new Rectangle(0, 0, backgroundWidth[bgTexIndexes[0]], backgroundHeight[bgTexIndexes[0]]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
                }
            }
        }
        if (bgTexIndexes[1] > -1)
        {
            bgScale = 1.31f;
            bgParallax = 0.43;
            bgTopY = (int)(backgroundTopMagicNumber * 1950.0 + 1750.0) + (int)scAdj + pushBGTopHack;
            SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
            bgScale *= bgGlobalScaleMultiplier;
            LoadBackground(bgTexIndexes[1]);
            bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[1]] * bgScale);
            SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
            bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
            if (gameMenu)
            {
                bgTopY = 400 + pushBGTopHack;
                bgStartX -= 80;
            }
            bgLoops = screenWidth / bgWidthScaled + 2;
            if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
            {
                for (int j = 0; j < bgLoops; j++)
                {
                    spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[1]].Value, new Vector2((float)(bgStartX + bgWidthScaled * j), (float)bgTopY), (Rectangle?)new Rectangle(0, 0, backgroundWidth[bgTexIndexes[1]], backgroundHeight[bgTexIndexes[1]]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
                }
            }
        }
        bgScale = 1.34f;
        bgParallax = 0.49;
        bgTopY = (int)(backgroundTopMagicNumber * 2100.0 + 2000.0) + (int)scAdj + pushBGTopHack;
        SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
        bgScale *= bgGlobalScaleMultiplier;
        LoadBackground(bgTexIndexes[2]);
        bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[2]] * bgScale);
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
        bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
        if (gameMenu)
        {
            bgTopY = 480 + pushBGTopHack;
            bgStartX -= 120;
        }
        bgLoops = screenWidth / bgWidthScaled + 2;
        if (bgTexIndexes[2] == 175)
        {
            bgStartX -= 1000;
            bgTopY -= 400;
            bgLoops++;
        }
        if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
        {
            for (int k = 0; k < bgLoops; k++)
            {
                spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[2]].Value, new Vector2((float)(bgStartX + bgWidthScaled * k), (float)bgTopY), (Rectangle?)new Rectangle(0, 0, backgroundWidth[bgTexIndexes[2]], backgroundHeight[bgTexIndexes[2]]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
            }
        }
    }
References Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundHeight, Terraria.Main.backgroundWidth, Terraria.Main.bgLoops, Terraria.Main.bgParallax, Terraria.Main.bgScale, Terraria.Main.bgStartX, Terraria.Main.bgTopY, Terraria.Main.bgWidthScaled, Terraria.Main.ColorOfSurfaceBackgroundsModified, Terraria.Main.gameMenu, Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.LoadBackground(), Terraria.Main.scAdj, Terraria.Main.screenWidth, Terraria.Main.SetBackgroundOffsets(), Terraria.Main.spriteBatch, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DrawSurfaceBG().