TModLoader: Terraria.Main.DrawBG
DrawBG()
void Terraria.Main.DrawBG () inline private
    {
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        //IL_019a: Unknown result type (might be due to invalid IL or missing references)
        float num = Math.Min(PlayerInput.RealScreenHeight, LogicCheckScreenHeight);
        float num2 = screenPosition.Y + (float)(screenHeight / 2) - num / 2f;
        scAdj = (float)(worldSurface * 16.0) / (num2 + num);
        float num3 = (float)maxTilesY * 0.15f * 16f;
        num3 -= num2;
        if (num3 < 0f)
        {
            num3 = 0f;
        }
        num3 *= 0.00025f;
        float num4 = num3 * num3;
        scAdj *= 0.45f - num4;
        if (maxTilesY <= 1200)
        {
            scAdj *= -500f;
        }
        else if (maxTilesY <= 1800)
        {
            scAdj *= -300f;
        }
        else
        {
            scAdj *= -150f;
        }
        float num5 = screenHeight;
        screenOff = num5 - 600f;
        bgTopY = (int)((double)(0f - screenPosition.Y + screenOff / 2f) / (worldSurface * 16.0) * 1200.0 + 1190.0) + (int)scAdj;
        cTop = bgTopY - 50;
        if (resetClouds)
        {
            Cloud.resetClouds();
            resetClouds = false;
        }
        bgScale = 1f;
        bgWidthScaled = (int)((float)backgroundWidth[treeMntBGSet1[0]] * bgScale);
        ColorOfSurfaceBackgroundsModified = ColorOfTheSkies;
        ColorOfSurfaceBackgroundsBase = ColorOfTheSkies;
        int preferredBGStyleForPlayer = GetPreferredBGStyleForPlayer();
        int num6 = 30;
        backgroundLayerTransitionSpeed = 0.05f;
        if (preferredBGStyleForPlayer == 0)
        {
            num6 = 60;
        }
        if (bgDelay < 0)
        {
            bgDelay++;
        }
        else if (preferredBGStyleForPlayer != bgStyle)
        {
            bgDelay++;
            if (bgDelay > num6)
            {
                bgDelay = -60;
                bgStyle = preferredBGStyleForPlayer;
                if (preferredBGStyleForPlayer == 0)
                {
                    bgDelay = 0;
                }
            }
        }
        else if (bgDelay > 0)
        {
            bgDelay--;
        }
        if (gameMenu)
        {
            backgroundLayerTransitionSpeed = 0.02f;
            if (!dayTime)
            {
                bgStyle = 1;
            }
            else
            {
                bgStyle = 0;
            }
            preferredBGStyleForPlayer = bgStyle;
            if (WorldGen.drunkWorldGen)
            {
                bgStyle = 9;
            }
            ModSurfaceBackgroundStyle menuBackgroundStyle = MenuLoader.CurrentMenu.MenuBackgroundStyle;
            if (menuBackgroundStyle != null)
            {
                bgStyle = menuBackgroundStyle.Slot;
            }
        }
        if (instantBGTransitionCounter > 0)
        {
            instantBGTransitionCounter--;
            bgStyle = preferredBGStyleForPlayer;
            backgroundLayerTransitionSpeed = 1f;
        }
        UpdateBGVisibility_BackLayer(null, null);
        UpdateBGVisibility_FrontLayer(null, null);
        LoaderManager.Get<SurfaceBackgroundStylesLoader>().ModifyFarFades(bgStyle, bgAlphaFrontLayer, backgroundLayerTransitionSpeed);
        try
        {
            DrawSurfaceBG();
            if (BackgroundEnabled)
            {
                DrawUnderworldBackground(flat: false);
            }
        }
        catch (Exception ex)
        {
            if (!ignoreErrors)
            {
                throw ex;
            }
            TimeLogger.DrawException(ex);
        }
        TimeLogger.DetailedDrawTime(8);
    }
References Terraria.Main.BackgroundEnabled, Terraria.Main.backgroundLayerTransitionSpeed, Terraria.Main.backgroundWidth, Terraria.Main.bgAlphaFrontLayer, Terraria.Main.bgDelay, Terraria.Main.bgScale, Terraria.Main.bgStyle, Terraria.Main.bgTopY, Terraria.Main.bgWidthScaled, Terraria.Main.ColorOfSurfaceBackgroundsBase, Terraria.Main.ColorOfSurfaceBackgroundsModified, Terraria.Main.ColorOfTheSkies, Terraria.Main.cTop, Terraria.ModLoader.MenuLoader.CurrentMenu, Terraria.Main.dayTime, Terraria.TimeLogger.DetailedDrawTime(), Terraria.TimeLogger.DrawException(), Terraria.Main.DrawSurfaceBG(), Terraria.Main.DrawUnderworldBackground(), Terraria.WorldGen.drunkWorldGen, Terraria.Main.gameMenu, Terraria.Main.GetPreferredBGStyleForPlayer(), Terraria.Main.ignoreErrors, Terraria.Main.instantBGTransitionCounter, Terraria.Main.LogicCheckScreenHeight, Terraria.Main.maxTilesY, Terraria.GameInput.PlayerInput.RealScreenHeight, Terraria.Cloud.resetClouds(), Terraria.Main.resetClouds, Terraria.Main.scAdj, Terraria.Main.screenHeight, Terraria.Main.screenOff, Terraria.Main.treeMntBGSet1, Terraria.Main.UpdateBGVisibility_BackLayer(), Terraria.Main.UpdateBGVisibility_FrontLayer(), and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DoDraw().