TModLoader: Terraria.Main.DrawGuideCraftText_Old
DrawGuideCraftText_Old()
static void Terraria.Main.DrawGuideCraftText_Old (int adjY, Color craftingTipColor, out int inventoryX, out int inventoryY) inline static private
Definition at line 54612 of file Main.cs.
    {
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0484: Unknown result type (might be due to invalid IL or missing references)
        //IL_049d: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_027f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_028c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0292: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_0358: Unknown result type (might be due to invalid IL or missing references)
        //IL_0360: Unknown result type (might be due to invalid IL or missing references)
        //IL_0366: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0427: Unknown result type (might be due to invalid IL or missing references)
        //IL_042c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0434: Unknown result type (might be due to invalid IL or missing references)
        //IL_043a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        inventoryX = 73;
        inventoryY = 331;
        inventoryY += adjY;
        int num = 0;
        int num4 = 0;
        inventoryX += num;
        inventoryY += num4;
        string text;
        if (guideItem.type > 0)
        {
            text = Lang.inter[21].Value + " " + guideItem.Name;
            spriteBatch.DrawString(FontAssets.MouseText.Value, Lang.inter[22].Value, new Vector2((float)inventoryX, (float)(inventoryY + 118)), craftingTipColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            int num5 = focusRecipe;
            int num6 = 0;
            for (int i = 0; i < recipe[availableRecipe[num5]].requiredTile.Count; i++)
            {
                int num7 = (i + 1) * 26;
                if (recipe[availableRecipe[num5]].requiredTile[i] == -1)
                {
                    if (i == 0 && !recipe[availableRecipe[num5]].needWater && !recipe[availableRecipe[num5]].needHoney && !recipe[availableRecipe[num5]].needLava && !recipe[availableRecipe[num5]].needSnowBiome && !recipe[availableRecipe[num5]].needGraveyardBiome)
                    {
                        spriteBatch.DrawString(FontAssets.MouseText.Value, Lang.inter[23].Value, new Vector2((float)inventoryX, (float)(inventoryY + 118 + num7)), craftingTipColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                    }
                    break;
                }
                num6++;
                int num8 = recipe[availableRecipe[num5]].requiredTile[i];
                spriteBatch.DrawString(FontAssets.MouseText.Value, Lang.GetMapObjectName(MapHelper.TileToLookup(num8, Recipe.GetRequiredTileStyle(num8))), new Vector2((float)inventoryX, (float)(inventoryY + 118 + num7)), craftingTipColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            if (recipe[availableRecipe[num5]].needWater)
            {
                int num9 = (num6 + 1) * 26;
                spriteBatch.DrawString(FontAssets.MouseText.Value, Lang.inter[53].Value, new Vector2((float)inventoryX, (float)(inventoryY + 118 + num9)), craftingTipColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            if (recipe[availableRecipe[num5]].needHoney)
            {
                int num10 = (num6 + 1) * 26;
                spriteBatch.DrawString(FontAssets.MouseText.Value, Lang.inter[58].Value, new Vector2((float)inventoryX, (float)(inventoryY + 118 + num10)), craftingTipColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            if (recipe[availableRecipe[num5]].needLava)
            {
                int num11 = (num6 + 1) * 26;
                spriteBatch.DrawString(FontAssets.MouseText.Value, Lang.inter[56].Value, new Vector2((float)inventoryX, (float)(inventoryY + 118 + num11)), craftingTipColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            if (recipe[availableRecipe[num5]].needSnowBiome)
            {
                int num2 = (num6 + 1) * 26;
                spriteBatch.DrawString(FontAssets.MouseText.Value, Lang.inter[123].Value, new Vector2((float)inventoryX, (float)(inventoryY + 118 + num2)), craftingTipColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            if (recipe[availableRecipe[num5]].needGraveyardBiome)
            {
                int num3 = (num6 + 1) * 26;
                spriteBatch.DrawString(FontAssets.MouseText.Value, Lang.inter[124].Value, new Vector2((float)inventoryX, (float)(inventoryY + 118 + num3)), craftingTipColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
        }
        else
        {
            text = Lang.inter[24].Value;
        }
        inventoryX -= num;
        inventoryY -= num4;
        spriteBatch.DrawString(FontAssets.MouseText.Value, text, new Vector2((float)(inventoryX + 50), (float)(inventoryY + 12)), new Color((int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
    }
References Terraria.Main.availableRecipe, Terraria.Graphics.Light.Color, Terraria.Main.focusRecipe, Terraria.Lang.GetMapObjectName(), Terraria.Recipe.GetRequiredTileStyle(), Terraria.Main.guideItem, Terraria.Lang.inter, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Item.Name, Terraria.Main.recipe, Terraria.Recipe.requiredTile, Terraria.Main.spriteBatch, Terraria.Map.MapHelper.TileToLookup(), Terraria.Item.type, and Terraria.Localization.LocalizedText.Value.