TModLoader: Terraria.Main.DrawProjWithStarryTrail
DrawProjWithStarryTrail()
void Terraria.Main.DrawProjWithStarryTrail (Projectile proj, Color projectileColor, SpriteEffects dir) inline private
Definition at line 48311 of file Main.cs.
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_025d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0262: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0290: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_030f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_0316: Unknown result type (might be due to invalid IL or missing references)
        //IL_031b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0320: Unknown result type (might be due to invalid IL or missing references)
        //IL_0322: Unknown result type (might be due to invalid IL or missing references)
        //IL_032c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_0338: Unknown result type (might be due to invalid IL or missing references)
        //IL_0342: Unknown result type (might be due to invalid IL or missing references)
        //IL_0345: Unknown result type (might be due to invalid IL or missing references)
        //IL_034a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0354: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_035c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0366: Unknown result type (might be due to invalid IL or missing references)
        //IL_0369: Unknown result type (might be due to invalid IL or missing references)
        //IL_036e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0378: Unknown result type (might be due to invalid IL or missing references)
        //IL_0382: Unknown result type (might be due to invalid IL or missing references)
        //IL_0384: Unknown result type (might be due to invalid IL or missing references)
        //IL_0389: Unknown result type (might be due to invalid IL or missing references)
        //IL_038e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0390: Unknown result type (might be due to invalid IL or missing references)
        //IL_0395: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03db: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0400: Unknown result type (might be due to invalid IL or missing references)
        //IL_0406: Unknown result type (might be due to invalid IL or missing references)
        //IL_0408: Unknown result type (might be due to invalid IL or missing references)
        //IL_040d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0412: Unknown result type (might be due to invalid IL or missing references)
        //IL_0419: Unknown result type (might be due to invalid IL or missing references)
        //IL_0423: Unknown result type (might be due to invalid IL or missing references)
        //IL_043a: Unknown result type (might be due to invalid IL or missing references)
        //IL_043c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0441: Unknown result type (might be due to invalid IL or missing references)
        //IL_0446: Unknown result type (might be due to invalid IL or missing references)
        //IL_0448: Unknown result type (might be due to invalid IL or missing references)
        //IL_044d: Unknown result type (might be due to invalid IL or missing references)
        //IL_045f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0465: Unknown result type (might be due to invalid IL or missing references)
        //IL_0467: Unknown result type (might be due to invalid IL or missing references)
        //IL_046c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0471: Unknown result type (might be due to invalid IL or missing references)
        //IL_0478: Unknown result type (might be due to invalid IL or missing references)
        //IL_0482: Unknown result type (might be due to invalid IL or missing references)
        //IL_0497: Unknown result type (might be due to invalid IL or missing references)
        //IL_049d: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_0107: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_019b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0504: Unknown result type (might be due to invalid IL or missing references)
        //IL_050b: Unknown result type (might be due to invalid IL or missing references)
        //IL_050f: Unknown result type (might be due to invalid IL or missing references)
        //IL_051c: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0600: Unknown result type (might be due to invalid IL or missing references)
        //IL_0602: Unknown result type (might be due to invalid IL or missing references)
        //IL_0604: Unknown result type (might be due to invalid IL or missing references)
        //IL_060b: Unknown result type (might be due to invalid IL or missing references)
        //IL_060e: Unknown result type (might be due to invalid IL or missing references)
        Color color = default(Color);
        ((Color)(ref color))._002Ector(255, 255, 255, ((Color)(ref projectileColor)).A - proj.alpha);
        Vector2 vector = proj.velocity;
        Color color2 = Color.Blue * 0.1f;
        Vector2 spinningpoint = default(Vector2);
        ((Vector2)(ref spinningpoint))._002Ector(0f, -4f);
        float num = 0f;
        float t = ((Vector2)(ref vector)).Length();
        float num2 = Utils.GetLerpValue(3f, 5f, t, clamped: true);
        bool flag = true;
        if (proj.type == 856 || proj.type == 857)
        {
            vector = proj.position - proj.oldPos[1];
            float num3 = ((Vector2)(ref vector)).Length();
            vector = ((num3 != 0f) ? (vector * (5f / num3)) : Vector2.UnitY);
            Vector2 origin = default(Vector2);
            ((Vector2)(ref origin))._002Ector(proj.ai[0], proj.ai[1]);
            Vector2 center = player[proj.owner].Center;
            float lerpValue = Utils.GetLerpValue(0f, 120f, origin.Distance(center), clamped: true);
            float num4 = 90f;
            if (proj.type == 857)
            {
                num4 = 60f;
                flag = false;
            }
            float lerpValue2 = Utils.GetLerpValue(num4, num4 * (5f / 6f), proj.localAI[0], clamped: true);
            float lerpValue3 = Utils.GetLerpValue(0f, 120f, proj.Center.Distance(center), clamped: true);
            lerpValue *= lerpValue3;
            lerpValue2 *= Utils.GetLerpValue(0f, 15f, proj.localAI[0], clamped: true);
            color2 = Color.HotPink * 0.15f * (lerpValue2 * lerpValue);
            if (proj.type == 857)
            {
                color2 = proj.GetFirstFractalColor() * 0.15f * (lerpValue2 * lerpValue);
            }
            ((Vector2)(ref spinningpoint))._002Ector(0f, -2f);
            float lerpValue4 = Utils.GetLerpValue(num4, num4 * (2f / 3f), proj.localAI[0], clamped: true);
            lerpValue4 *= Utils.GetLerpValue(0f, 20f, proj.localAI[0], clamped: true);
            num = -0.3f * (1f - lerpValue4);
            num += -1f * Utils.GetLerpValue(15f, 0f, proj.localAI[0], clamped: true);
            num *= lerpValue;
            num2 = lerpValue2 * lerpValue;
        }
        Vector2 val = proj.Center + vector;
        Texture2D value = TextureAssets.Projectile[proj.type].Value;
        _ = Utils.Size(new Rectangle(0, 0, value.Width, value.Height)) / 2f;
        Texture2D value2 = TextureAssets.Extra[91].Value;
        Rectangle value3 = value2.Frame();
        Vector2 origin2 = default(Vector2);
        ((Vector2)(ref origin2))._002Ector((float)value3.Width / 2f, 10f);
        _ = Color.Cyan * 0.5f * num2;
        Vector2 vector2 = default(Vector2);
        ((Vector2)(ref vector2))._002Ector(0f, proj.gfxOffY);
        float num5 = (float)timeForVisualEffects / 60f;
        Vector2 vector3 = val + vector * 0.5f;
        Color color3 = Color.White * 0.5f * num2;
        ((Color)(ref color3)).A = 0;
        Color color4 = color2 * num2;
        ((Color)(ref color4)).A = 0;
        Color color5 = color2 * num2;
        ((Color)(ref color5)).A = 0;
        Color color6 = color2 * num2;
        ((Color)(ref color6)).A = 0;
        float num6 = vector.ToRotation();
        EntitySpriteDraw(value2, vector3 - screenPosition + vector2 + spinningpoint.RotatedBy((float)Math.PI * 2f * num5), value3, color4, num6 + (float)Math.PI / 2f, origin2, 1.5f + num, (SpriteEffects)0);
        EntitySpriteDraw(value2, vector3 - screenPosition + vector2 + spinningpoint.RotatedBy((float)Math.PI * 2f * num5 + (float)Math.PI * 2f / 3f), value3, color5, num6 + (float)Math.PI / 2f, origin2, 1.1f + num, (SpriteEffects)0);
        EntitySpriteDraw(value2, vector3 - screenPosition + vector2 + spinningpoint.RotatedBy((float)Math.PI * 2f * num5 + 4.1887903f), value3, color6, num6 + (float)Math.PI / 2f, origin2, 1.3f + num, (SpriteEffects)0);
        Vector2 vector4 = val - vector * 0.5f;
        for (float num7 = 0f; num7 < 1f; num7 += 0.5f)
        {
            float num8 = num5 % 0.5f / 0.5f;
            num8 = (num8 + num7) % 1f;
            float num9 = num8 * 2f;
            if (num9 > 1f)
            {
                num9 = 2f - num9;
            }
            EntitySpriteDraw(value2, vector4 - screenPosition + vector2, value3, color3 * num9, num6 + (float)Math.PI / 2f, origin2, 0.3f + num8 * 0.5f, (SpriteEffects)0);
        }
        if (flag)
        {
            float rotation = proj.rotation + proj.localAI[1];
            _ = (float)timeForVisualEffects / 240f;
            _ = GlobalTimeWrappedHourly;
            float globalTimeWrappedHourly = GlobalTimeWrappedHourly;
            globalTimeWrappedHourly %= 5f;
            globalTimeWrappedHourly /= 2.5f;
            if (globalTimeWrappedHourly >= 1f)
            {
                globalTimeWrappedHourly = 2f - globalTimeWrappedHourly;
            }
            globalTimeWrappedHourly = globalTimeWrappedHourly * 0.5f + 0.5f;
            Vector2 position = proj.Center - screenPosition;
            instance.LoadItem(75);
            Texture2D value4 = TextureAssets.Item[75].Value;
            Rectangle rectangle = value4.Frame(1, 8);
            EntitySpriteDraw(origin: rectangle.Size() / 2f, texture: value4, position: position, sourceRectangle: rectangle, color: color, rotation: rotation, scale: proj.scale, effects: (SpriteEffects)0);
        }
    }
References Terraria.Graphics.Light.Color, Terraria.Main.EntitySpriteDraw(), Terraria.GameContent.TextureAssets.Extra, Terraria.Utils.GetLerpValue(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.instance, Terraria.GameContent.TextureAssets.Item, Terraria.Main.player, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.screenPosition, Terraria.Utils.Size(), and Terraria.Main.timeForVisualEffects.
Referenced by Terraria.Main.DrawProj_DrawNormalProjs().